### ISSUE TITLE
dyld: Library not loaded: @rpath/Realm.framework/Versions/A/Realm

### ISSUE THREAD

**Issue by anhhtz** [realm/realm-cocoa#1000]
Hello,

I just run a simple OS X app with Realm and it is crash when running with error:

dyld: Library not loaded: @rpath/Realm.framework/Versions/A/Realm
  Referenced from: /Users/HTAD/Library/Developer/Xcode/DerivedData/REALM-cdxzyeduoxphmoefhjxihxunuzkd/Build/Products/Debug/REALM.app/Contents/MacOS/REALM
  Reason: image not found
(lldb) 

I don't know what image is ?

P/s: XCode 6.0.1, Mac OS X 10.9.5

**Comment by stanislaw** [comment]
@jpsim's linked comment worked for me. I would love if I could learn it from [Swift/OSX documentation](http://realm.io/docs/swift/latest/).

**Comment by kiritmodi2702** [comment]
See this one : http://iosdevcenters.blogspot.in/2015/12/realm-error-dyld-library-not-loaded.html

**Comment by tt3tt3tt** [comment]
fix it by adding the Swift framework (MySDK.framework) to the "Embedded Binaries" section of the "General" tab of the Xcode project settings. Then deleting the derived data and rebuilding. 
See: http://stackoverflow.com/questions/24211549/dyld-library-not-loaded-rpath-mydsk-framework-mydsk-swift-ios-8-0

**Comment by wflores96** [comment]
I just migrated from cocoapods to carthage for better build times and was getting this error. @Archerlly your answer fixed mine! thanks!
