### ISSUE TITLE
Map keys based on provided dictionary

### ISSUE THREAD

**Issue by eni9889** [realm/realm-cocoa#1012]
Key mapping similar to https://github.com/icanzilb/JSONModel/ would be super useful. Especially because there are server endpoints that return keys like 'description' which I would like to map to something else.

**Comment by arielpollack** [comment]
+1
Realm-JSON lib doesn't support swift.
the mapping is already implemented in Mantle library, so the same logic can be used here.

**Comment by timanglade** [comment]
Closing this as a duplicate of #694
