### ISSUE TITLE
Provide defaultDateFormats for date properties

### ISSUE THREAD

**Issue by eni9889** [realm/realm-cocoa#1013]
I would love if the following existed:
```
-(NSDictionary *)defaultDateFormats {
    return @{ 
                    @"created_at" :@"yyyy-MM-dd HH:mm:ss 'UTC'",
                    @"updated_at" :@"yyyy-MM-dd HH:mm:ss 'UTC'",
                  };
}
```

**Comment by mikecole20** [comment]
I'd love to see this as well. We're having issues getting dates to work and I would like to avoid adding another third-party layer on if possible.

**Comment by lucianocn** [comment]
+1

**Comment by Payload-Lee** [comment]
+1

**Comment by tbaranes** [comment]
+1

**Comment by jpsim** [comment]
This is a subset of #694 and the same rationale for closing that applies here. Please use one of the many available third party model mapping libraries.
