### ISSUE TITLE
Exception when querying on a relationship based object.

### ISSUE THREAD

**Issue by mitchellporter** [realm/realm-cocoa#1019]
I am trying to perform a query on an RLMObject's property, which happens to be an RLMArray.

Here is the exception that keeps getting thrown:
`'RLMException', reason: 'This method can only be called in RLMArray instances retrieved from an RLMRealm'`

The problem is that my property represents a relationship.

It seems that others have been having similar problems. I just came across this StackOverflow answer provided by Tim Anglade of Realm: http://stackoverflow.com/a/25896545/3344977

In that answer he recommends the following solution:

"In the meantime, you unfortunately have to deep-copy the RLMArray into an NSArray and sort it."

I looked up deep linking and have tried several methods, but I couldn't get any of them to work. Maybe I'm using this wrong?

Does anyone know what he meant, and could you direct me in the right direction as to how to implement his solution?

Really appreciate the help.

**Comment by mkolodny** [comment]
I just ran into this exact same issue on 0.91.3. Is querying a `RLMArray` relation not allowed anymore?

**Comment by jpsim** [comment]
What's your query? We'll need a bit more information to troubleshoot your problem.

**Comment by mkolodny** [comment]
var friends = RLMArray(objectClassName: User.className())
    friends.sortedResultsUsingProperty("name", ascending: true)

I'm using Swift 1.2 with XCode 6.3.

**Comment by jpsim** [comment]
That should work. What results is it giving you?

**Comment by jpsim** [comment]
Sorry, I spoke too soon. Sorting an RLMArray can only be done on a persisted RLMArray. I've just created a ticket for us to enable sorting on standalone RLMArrays: #1794.

**Comment by mkolodny** [comment]
No worries, thanks @jpsim

**Comment by marchy** [comment]
What's the suggested workaround for this?

**Comment by jpsim** [comment]
@marchy from Swift, you can use [SequenceType.sort(_:)](http://swiftdoc.org/v2.2/protocol/SequenceType/#func--sort_), from Objective-C, you can use KVC to turn the RLMCollection into an NSArray: `[[realmCollection valueForKeyPath:@"self"] sortedArrayUsingComparator:]`.

**Comment by marchy** [comment]
@jpsim sorry let me clarify. I meant that it's not just the one-time sorted results that we're interested in, it's also the live-updating Results with notifications of when those results or their orders change.

In other words, for the following fields:
`var DAL_messages:List<Message>!
var messages:Results<Message>!`

we want to make messages initialize to be a sorted view upon the underlying data:
`messages = DAL_messages.sorted( "sentAt" )`

However when initializing a new object this way before it's persisted (which in our case we do not want to persist quite yet) we run into this limitation.

Our closest approach/workaround has been to persist to the DB:
`try! database.write {
	database.add( self, update: true )
}`
and then presumably delete the object if the user changes their mind (ie: does not want to save/persist it).

**Comment by jpsim** [comment]
Instead of writing these objects to the same Realm as your persisted objects, you could add these objects to a different Realm, preferably an [in-memory Realm](https://realm.io/docs/swift/latest/#in-memory-realms).

You could also maintain an updated array version of the results using [collection notifications](https://realm.io/docs/swift/latest/#notifications).

**Comment by marchy** [comment]
Oooh that's an interesting approach (the in-memory one). Might be the answer - will look into the caveats of transferring these objects to the persisted domain once they are to be written.

Thanks a lot JP!
