### ISSUE TITLE
Swift default value of nil with optional flag not recognized, fails

### ISSUE THREAD

**Issue by javierjulio** [realm/realm-cocoa#1024]
If I have:

``` swift
class FlashCard: RLMObject {
  dynamic var lastReviewedAt: NSDate? = nil
}
```

And then in a test case if I do the following:

``` swift
  func test() {
    let realm = realmWithTestPath()

    let firstFlashCard = FlashCard()
    firstFlashCard.definition = "first"

    realm.transactionWithBlock() {
      realm.addObject(firstFlashCard)
    }
  }
```

I get the following error which is unexpected: `failed: caught "RLMException", "No value or default value specified for property 'lastReviewedAt' in 'FlashCard'"` since I set the value to nil and expect it at some points that it can be nil. Am I doing something wrong or is this default value not supported? Do I have to instantiate the FlashCard object within the block?

**Comment by scottfister** [comment]
I am attempting to do this with a float or double and I get the error `'NSUnknownKeyException', reason: '[<__NSCFNumber 0x7fe509f350e0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key float.'`.

My code:
```
class NullableFloat: Object {
    dynamic var float: Float = 0.0
}
class Foo: Object {
  dynamic var bar : NullableFloat?
}
```

What am I doing wrong?

**Comment by jpsim** [comment]
@scottfister could you please open a new issue with step-by-step instructions to reproduce the issue you're seeing? Thanks!
