### ISSUE TITLE
Swift Dynamic Cast Conditional Error

### ISSUE THREAD

**Issue by javierjulio** [realm/realm-cocoa#1044]
I have a repo containing a project that replicates the error at: https://github.com/javierjulio/realm-issues. The iOS project was built on Yosemite (updated last night), Xcode 6.0.1, and using Realm 0.86.3. I've noticed this happen when I'm creating a default object and saving it to the Realm but only making sure I have one instance of that object ever saved. In my case I have an app where we'd expose that app to the user to allow them to create more but for now we aren't. So to proceed with that I ended up creating a service in the repo I linked earlier that had this:

``` swift
import Realm

class UserService {

  var realm: RLMRealm

  init(realm: RLMRealm) {
    self.realm = realm
  }

  func defaultUser() -> User {
    if User.allObjects().count == 0 {
      realm.transactionWithBlock() {
        let user = User()
        user.firstName = "Javier"
        user.lastName = "Julio"
        self.realm.addObject(user)
      }
    }

    return User.allObjects().firstObject() as User
  }
}
```

I'm using a Service class here since I need to pass in the realm so I can do tests. I have a separate issue where if I try to override RLMRealm.defaultRealm (test target) I get an ambiguous error if I reference it in my app target code. So I avoid doing that by using service classes where I can pass the realm in to do tests.

In the example service above I sporadically get a swift dynamic cast conditional error (most of the time). I thought maybe if I save an object to Realm it might not be immediately available to query but in a twitter conversation with @jpsim this shouldn't be the case. I'm not sure if that's the problem but it came to mind so I tried writing the method a different way, and this solution seems to always work (tests always pass):

``` swift
func defaultUser() -> User {
  if User.allObjects().count == 0 {
    let user = User()
    realm.transactionWithBlock() {
      user.firstName = "Javier"
      user.lastName = "Julio"
      self.realm.addObject(user)
    }
    return user
  }
  else {
    return User.allObjects().firstObject() as User
  }
}
```

**Comment by AnthonyMDev** [comment]
Have those new Swift APIs been released? I'm having this issue right now, and I'd really like to see this fixed! Thanks

**Comment by alazier** [comment]
We are hard at work on the new swift apis. The current work in progress can be seen on the al-swfit branch. There is quite a bit more testing and api changes that need to be made before it will be ready for release so it should be at least another few weeks.
