### ISSUE TITLE
Converting a RLMResults to [RLMObject] most efficiently

### ISSUE THREAD

**Issue by aleclarson** [realm/realm-cocoa#1046]
As of now I'm using:

``` Swift
extension RLMResults {
  func toArray () -> [RLMObject] {
    var array = [RLMObject]()
    for result in self {
      array.append(result)
    }
    return array
  }
}
```

Is there a faster way available to get this conversion? I use it with generic global functions to implicitly cast the `RLMResults` to the appropriate `RLMObject` subclass.

``` Swift
public func RLMQuery <T:RLMObject> (_ predicate: String = "TRUEPREDICATE") -> [T] {
  return T.objectsWithPredicate(NSPredicate(format: predicate)).toArray() as [T]
}

class Photo {
  init (disk: RLMPhoto) {}
}

// first photo in the default realm
let photo = Photo(RLMQuery().first!)

// all photos by the user
let photos: [RLMPhoto] = RLMQuery("creator == \(user.id)")
```

Thanks! :grin:

**Comment by duemunk** [comment]
I tried to replicate the solution that @aleclarson showed with generics. 
```swift
func toArray<T>(ofType: T.Type) -> [T] {
    var array = [T]()
    for result in self {
        if let result = result as? T {
            array.append(result)
        }
    }
    return array
}
```
This allows me to do:
```swift
 let tracks = Track.allObjects().toArray(Track.self) // tracks is of type [Track]
```

**Comment by ldesroziers** [comment]
I met the same problem using Swift and found a better way of doing that, without any enumeration at all.
Of course, it can be improved a lot more! It's currently a kind of wrapper for RLMResults, but sure can be used as a pure Swift dynamic collection instead.

```swift
extension RLMRealm {
	func allObjects<T: RLMObject>(fromClass cls: T.Type) -> RLMSwiftyResults<T> {
		return RLMSwiftyResults<T>(results: cls.allObjectsInRealm(self))
   	}
}


class RLMSwiftyResults<T: RLMObject> {
   	let results: RLMResults
    	init(results: RLMResults) {
        	self.results = results
    	}
    
    	func objectAtIndex(i: UInt) -> T {
        	return self.results.objectAtIndex(i) as! T
    	}
    
    	// And all other methods from RLMResults…
}

let mediaItems = RLMRealm.defaultRealm().allObjects(fromClass: MediaItem.self) // mediaItems is now a RLMSwiftyResults<MediaItem>
let firstMediaItem = mediaItem.objectAtIndex(0) // firstMediaItem is now a MediaItem

**Comment by phamquochoan** [comment]
I also ran into this problem today
Since swift 2.0, we can do this (based on @duemunk's solution):

```
extension Results {
    
    func toArray() -> [Results.Generator.Element] {
        var array = [T]()
        for item in self { array.append(item as Results.Generator.Element) }
    
        return array
    }
}
```

**Comment by jpsim** [comment]
You could just use [map](http://swiftdoc.org/v2.0/protocol/SequenceType/#func-map):

```swift
extension Results {
    func toArray() -> [Results.Generator.Element] {
        return map { $0 }
    }
}
```

**Comment by chrism21** [comment]
For those with still working with RLMObject in Swift (objc & swift projects), you can put the implementation @duemunk used into one line:

```
extension RLMResults {
    func toArray<T>(ofType: T.Type) -> [T] {
        return (0..<self.count).flatMap { self.objectAtIndex($0) as? T }
    }
}
```

Thanks @duemunk!

**Comment by jpsim** [comment]
@chrism21 

```swift
extension RLMResults {
    func toArray<T>(ofType: T.Type) -> [T] {
        return flatMap { $0 as? T }
    }
}
```

**Comment by chrism21** [comment]
Even nicer, thanks! @jpsim

**Comment by DHidee66** [comment]
Is there a way to do this on JS?

**Comment by jpsim** [comment]
@cmajordev sorry I never saw your last message. `RLMResults` conforms to `SequenceType` if you're using `RLMSupport.swift` as we recommend in our installation instructions: https://realm.io/docs/objc/latest/#installation

`flatMap` is defined on `SequenceType`.

@DHidee66 I don't know, this is the cocoa repo. You can file issues towards the realm-js repo for questions like that: https://github.com/realm/realm-js/issues/new

**Comment by charliefulton** [comment]
@jpsim just wanted to say thanks for the sweet toArray extension!

**Comment by tomekc** [comment]
@jpsim I guess your nice extension would work with Swift 2.x only?
I get compilation error:

> Extension of generic Objective-C class cannot access the class's generic parameters in runtime

I guess this is a limitation.

**Comment by jpsim** [comment]
@tomekc just use the `Array()` initializer as I mentioned in https://github.com/realm/realm-cocoa/issues/1046#issuecomment-143804257

```swift
let results: Results<...> // Results
let array = Array(results)
```

**Comment by MuqThe2nd** [comment]
I did this and it seemed pretty neat.

```
let results = Results<MyObjectModel>
var dataSource = [MyObjectModel]()
dataSource.append(contentsOf: results)
```

**Comment by jpsim** [comment]
Again:

```swift
let results: Results<MyObjectModel>
let dataSource = Array(results)
```

But if you're finding yourself copying data out of Realm Collections, you're losing many of their advantages, such as their live updating, lazy-loading, notifications & the ability to pass them across threads via `ThreadSafeReference` to name a few.

**Comment by matloobhasnain** [comment]
Hi guys I have an RLMObject 

[      @interface Job : RLMObject <NSCoding, NSCopying>
      @property (nonatomic, strong) Contact  *contact; // this is another RLMObject
      @property (nonatomic, strong) Location  *location; // this is another RLMObject](url)
Its saving fine and once I try to do it also giving excellent result , 
[RLMResults<Job *> *jobListArray = [Job allobjects];](url)
but issue is once I get job object from this [jobListArray](url) its returning me Contact and Location Object Nil.If any one can help would be appreciated
