### ISSUE TITLE
Expose framework version number

### ISSUE THREAD

**Issue by javierjulio** [realm/realm-cocoa#1057]
I'm trying to help someone with a testing issue on the Realm Google Groups. I've tried in the past sifting through the header files in the Realm.framework I include in my Xcode project to see if I can find a version but I don't see any. If its not listed there I wanted to suggest if it were possible to build the framework header files to include the Realm version, would be helpful for debugging an issue I'd imagine. Just a suggestion.

**Comment by jpsim** [comment]
The version is now available in `Realm.framework/Info.plist`.
