### ISSUE TITLE
What is the best way to get RLMResults from RLMArray?

### ISSUE THREAD

**Issue by ppeszko** [realm/realm-cocoa#1062]
Hi *.

First of all, thank you for the great work and let me say that I really like how you are leading this community. Your patient for some answers is on legendary level ;) 

I've just upgraded our app to 0.87.1 and I'm not sure about one thing. I have a method wich in the past accepted RLMArray as parameter. Right now I would rather prefer that this method works with RLMResults as this way would be more transparent and not bound to relationship concept. 

So how can I get all objects from the relationship? What is the best praxis to do it?
Currently I'm doing something like 
`RLMResults *assets = [self.company.assets objectsWithPredicate:nil]`
but this feels a bit hacky to me :/ I'm feeling there should be a better way which I'm not seeing right now.

Not sure if I explain myself clear enough :)

**Comment by martinprot** [comment]
Hello What exactly do you mean, using the RLMCollection?

I tryied changing:
`@property RLMArray<User> *followers;`

with
`@property RLMArray<User, RLMCollection> *followers;`

But Realm crashes with the error message: 
`Terminating app due to uncaught exception 'RLMException', reason: ''User><RLMCollection' is not supported as an RLMArray object type. RLMArrays can only contain instances of RLMObject subclasses. See http://realm.io/docs/cocoa/#to-many for more information.`

**Comment by martinprot** [comment]
Ah ok, I misread. `RLMArray` *already* conforms to `RLMCollection`, so the solution is just to call, for example

`[user.followers sortedResultsUsingProperty:@"firstname" ascending:YES];`

**Comment by anbarasu0504** [comment]
```
var objects:RLMCollection!

if selectedObject != nil {
            objects = selectedObject.childobjects as RLMArray
        } else {
            objects = RealmObject.objectsInRealm(realm, "isFavourite == 1")
        }

println(couplets.objectAtIndex(indexPath.row) as! RealmObject)
```

I had a senario, where I won't know whether I need to work with RLMArray or RLMResults, so I used RLMCollection.

How can I achieve the same in RealmSwift 0.93.1

**Comment by segiddins** [comment]
You can use CollectionType, although we've been meaning to add a RealmCollectionType

**Comment by anbarasu0504** [comment]
hi can anyone provide sample code on how to achieve this using CollectionType
