### ISSUE TITLE
New API to support wrapping NSDocument

### ISSUE THREAD

**Issue by tonyarnold** [realm/realm-cocoa#1066]
Following a brief conversion with @jpsim on Twitter (https://twitter.com/simjp/status/525059086614663168), here are the things I think Realm will need in order to properly support being wrapped in an NSDocument on OS X (and potentially UIDocument on iOS):

1. Some indicator of whether the realm has changes that are yet to be saved to disk (is this possible?)
2. If 1 is possible, some method of flushing said changes to disk (when the user hits Apple-S)
3. NSDocument generally expects to be able to pick the document representation up off disk and move it somewhere else — it's probably possible to do that ourselves, but we would need a method of ensuring a realm is flushed to disk, then closed before moving the file elsewhere. It's possible some kind of realm to realm migration/copy might be a better option here (essentially atomically copying the contents of the realm to another location)
4. It seems like the realm file is only created after the first transaction is committed? There would need to be an option to initialise an empty realm on disk so that NSDocument is happy (it expects to be able to locate a file for the document after saving)

There's really two scenarios here that I'd love to see supported:

1. The realm file itself is the document (flat NSDocument)
2. The realm file is inside a document bundle

I'll have a bit more of a think about what else is missing — my early experiments with getting this working weren't particularly successful, but I haven't had much time to dedicate to it yet.

**Comment by timanglade** [comment]
It looks like we added all the primitives needed for this, please re-open if you see anything missing!
