### ISSUE TITLE
Move/copy objects between realms?

### ISSUE THREAD

**Issue by raulperez** [realm/realm-cocoa#1076]
Hi,

Is it possible to move/copy objects between realms?

Regards,

Raul Perez

**Comment by conradev** [comment]
Here's a permalink for anyone reading this retroactively: https://github.com/realm/realm-cocoa/blob/569a6dc401b55fc273dbc3e23c63cbf02ab0a951/Realm/Tests/RealmTests.mm#L254

**Comment by i-schuetz** [comment]
I'm looking for this functionality but can't find this method - only `create` with a dictionary. Anyone knows if it's still possible to do this, and if yes how? (Using Swift).
