### ISSUE TITLE
Crash when query executed in background

### ISSUE THREAD

**Issue by kronik** [realm/realm-cocoa#1077]
Hi! 

My app is crashing almost every time (about 90% cases) when the app (voip) is running in background and later is trying to handle push notification. It executes a query to select all object of particular type. Crash:

 Error Domain=io.realm Code=1 "open() failed: Operation not permitted" UserInfo=0x170a62340 {NSLocalizedDescription=open() failed: Operation not permitted, Error Code=1}

iOS8, iPhone5S, Locked with passcode. This issue doesn't happen on iOS7 Locked WITHOUT passcode.

**Comment by frankcjw** [comment]
I have the same issue that realm crash when handle push notification in background  ..

**Comment by jpsim** [comment]
@frankcjw if your phone is locked when this happens, please refer to my answer in https://github.com/realm/realm-cocoa/issues/1260#issuecomment-88949065.

If the phone is unlocked, then that's possibly a bug in Realm and we'd really appreciate a sample Xcode project that we can run to reproduce the issue. Thanks!

**Comment by Fab1n** [comment]
I get the same issue. Totally works on simulator, crashes on device

**Comment by jpsim** [comment]
@Fab1n have you tried setting the realm file's parent directory to use `NSFileProtectionNone` as discussed here: https://github.com/realm/realm-cocoa/issues/1874#issuecomment-101057887? 

```
[[NSFileManager defaultManager] setAttributes:@{NSFileProtectionKey: NSFileProtectionNone} ofItemAtPath:[RLMRealm.defaultRealmPath stringByDeletingLastPathComponent] error:&err];
```

**Comment by Fab1n** [comment]
I found the "bug". My fault, used a file from the bundle with file protection... And then realm cannot alter the file. Should be as expected. Sorry for the inconvenience

**Comment by yoshyosh** [comment]
is there a way we can have a better error message around this?

**Comment by Fab1n** [comment]
OK, still there is an issue. I cannot open the file on device from bundle in readonly mode. The FilePermission exception is not catched but instead the last catch statement (exception ex). 
The file is contained in the main bundle 2 folders below the main executable.

**Comment by jpsim** [comment]
@Fab1n could you send us a project that reproduces this issue? You should definitely be able to open a readonly realm file in your app bundle.

**Comment by Fab1n** [comment]
Sorry for this late answer. I managed to open the realm from the bundles folder in readonly mode. No problem here with Realm!!!
