### ISSUE TITLE
Crashed in my project just call [RLMRealm defaultRealm]

### ISSUE THREAD

**Issue by NemoAir** [realm/realm-cocoa#1080]
In my project, i simply call [RLMRealm defaultRealm] in 
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  {
  [RLMRealm defaultRealm];
  }
  
  of appDelegate.m, i get the follow erros:

**\* Terminating app due to uncaught exception 'RLMException', reason: ''NSNumber' is not supported as an RLMObject property. Supported number types include int, long, float, double, and other primitive number types. See http://realm.io/docs/cocoa/latest/api/Constants/RLMPropertyType.html for all supported types.'

![0eec5970-7d14-4951-8e3b-c9fd883c4cf8](https://cloud.githubusercontent.com/assets/5069545/4803863/97bf8c14-5e5f-11e4-9b7b-38ae85999e65.png)

Is   [RLMRealm defaultRealm] would call [RLMProperty setTypeFromRawType],because the log was printed by this method, i am sure i haven't  do any initialize things.
The App immediately crashed when call the [RLMRealm defaultRealm] ,and stop on

_dispatch_once(dispatch_once_t _predicate, dispatch_block_t block)
{
    if (DISPATCH_EXPECT(_predicate, ~0l) != ~0l) {
        dispatch_once(predicate, block);
    }
}

I am sure i haven't    created any subclass  of RLMObject or call any other realm method before it.
I also had link the Realm.framework and libc++.dylib.,and had created a new demo project,all is fine. So i guess it's my project's setting cause the problem .

My project was created by Xcode5,deployment target is 6.0,and now i was using Xcode6.1 to build my project.

Can any project setting  cause the realm not work?

**Comment by hovox** [comment]
Hi @jpsim for me this error happens because I have a private property which is not ignored, adding it to the ignored list fixed the issue
