### ISSUE TITLE
Unable to define realtionships in model classes

### ISSUE THREAD

**Issue by milo01-exe** [realm/realm-cocoa#1087]
Hey all hoping someone can help me figure out what the issue is, I've been looking for an alternative for a persistence engine in place of Core Data. I stumbled across Realm and must say I find it very interesting and want to incorporate it in my latest project. The issue I'm running into is that I can't seem to define relationships between my model classes. I've followed the docs but can't seem to get this working at all. I've installed Realm through Cocoapods and then at first created my model classes through the plugin on Alcatraz but that didn't seem to be working, so I created my classes the good old fashion way but still no luck. The issue seems to be that the classes are not seeing the other even though I'm importing the headers of the relationships I hope to make.

**Comment by Siriss** [comment]
I am having the same problem. @marlowcharite How did you fix this? I still get the Cannot find protocol declaration no matter what combination of class or import combinations I use.

**Comment by marlowcharite** [comment]
@Siriss I don't have the project in front of me right now but basically if I remember correctly I had to forward declare both a class that was the other side of the relationship. And then import any other needed classes

**Comment by HannahCarney** [comment]
I am also having this issue. No type of protocol named 'User' I can't start a new project as I'm trying to integrate this into a huge project.

**Comment by jpsim** [comment]
> EDIT: Fixed, but the documentation is wrong on where we need to declare RLM_ARRAYS

@HannahCarney you probably meant `RLM_ARRAY_TYPE(User)`? Which documentation is wrong? This is specified a few times in the "Models" section of our docs: https://realm.io/docs/objc/latest/#models
