### ISSUE TITLE
Many concurrent accesses lead to crash

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#1096]
Hey guys,

I'm currently running many concurrent writes on my realm to insert a lot of entries in parallel. At some point a random crash occurs. When restarting the app, mmap() immediately crashes again with the very same error message.

Any ideas?

2014-11-03 16:56:00.263 myApp[4690:13003] **\* Terminating app due to uncaught exception 'RLMException', reason: 'mmap() failed: Cannot allocate memory'
**\* First throw call stack:
(0x2fe89fd3 0x3a636ccf 0x4a9d57 0x4a9485 0x4a9215 0x4731c9 0x778e5 0x3ab1e833 0x3ab31921 0x3ab31b21 0x3ac60bd3 0x3ac60a98)
libc++abi.dylib: terminating with uncaught exception of type NSException
2014-11-03 16:56:00.273 mmap[4690:13803] **\* Terminating app due to uncaught exception 'RLMException', reason: 'mmap() failed: Cannot allocate memory'
**\* First throw call stack:
(0x2fe89fd3 0x3a636ccf 0x4a9d57 0x4a9485 0x4a9215 0x4731c9 0x778e5 0x3ab1e833 0x3ab31921 0x3ab31b21 0x3ac60bd3 0x3ac60a98)
libc++abi.dylib: terminating with uncaught exception of type NSException
2014-11-03 16:56:00.277 mmap[4690:fe03] **\* Terminating app due to uncaught exception 'RLMException', reason: 'Bad transaction log'
**\* First throw call stack:
(0x2fe89fd3 0x3a636ccf 0x4ab87d 0x4ab677 0x4abdab 0x779ad 0x3ab1e833 0x3ab31921 0x3ab31b21 0x3ac60bd3 0x3ac60a98)

**Comment by duemunk** [comment]
I can't seem to follow your track on this issue. For me still persists for me when changing realm data on background thread.

**Comment by jpsim** [comment]
@duemunk can you send us a code sample demonstrating what you think should work, and how it fails?

Keep in mind that the `mmap() failed: Cannot allocate memory` happens once the device no longer has any available mmap-able space and that the bigger the realm file and the more concurrent transactions are used, the higher the odds of running out of allocatable mmap memory.

We'll be cutting a release very soon which switches to Realm Core 0.89.3, which lowers the maximum doubling threshold for Realm file sizes from 128MB to 16MB. (#1933)

**Comment by duemunk** [comment]
My Realm file size had indeed increase quite a lot. I did a fake compress using the write-copy-routine, and it alleviated the issues – for now. The doubling threshold is a good thing, but an semi-automatic compress function would be nice, to avoid everyone having to write their own write-copy-routine.

**Comment by matteogobbi** [comment]
I had the same problem, solved with an easy dispatching on a serial queue. The problem is that I had a for cycle fetching stuff from the web and then writing in the database..this by multiple threads. 
I solved dispatching in serial queue the writing group of operations:

```
dispatch_queue_t serialRealmWritingQueue = dispatch_queue_create(NULL, DISPATCH_QUEUE_SERIAL);

for (..) {
    [network fetchWithCompletion:^(){
        dispatch_async(serialRealmWritingQueue, ^{
            [realm writing..];
            [realm writing..];
            [realm writing..];
        });
    }];
```
