### ISSUE TITLE
Support custom RLMObject initializers in Swift

### ISSUE THREAD

**Issue by maciejtrybilo** [realm/realm-cocoa#1101]
```swift
class Foo: RLMObject {
    dynamic var bar: String
    
    init(bar: String) {
        self.bar = bar
        
        super.init()
    }
}

let foo = Foo(bar: "😿")
```

The last line results in ```fatal error: use of unimplemented initializer 'init()' for class 'moduleName.Foo'```. Somehow Realm seems to want to call the default initializer, but ideally I wouldn't want to implement it because I don't necessarily have reasonable default values and would rather avoid optionals.

**Comment by Pintouch** [comment]
@mrh-is I tried defining the default constructor as you mention, I'm getting ``` fatal error: use of unimplemented initializer 'init(objectSchema:)' for class Foo ```.

```
class Foo: RLMObject {
    dynamic var bar = ""
    override init() {
        super.init()
    }
    init(bar: String) {
        self.bar = bar

        super.init()
    }
}

let foo = Foo(bar: "😿")
```
3 months passed since you commented it, so maybe it's not working anymore since new Xcode version? Is there a workaround ?

**Comment by mrh-is** [comment]
@Pintouch Yep, it's a change sometime between 0.87.4 and 0.90.0. Still investigating...

**Comment by mrh-is** [comment]
OK, I'm not totally certain, because I (sadly!) can't spend the whole work day on debugging this so I didn't test with this commit, but I _think_ it's [commit 94c2dee](https://github.com/realm/realm-cocoa/commit/94c2deedaaa41429b881cf975c378140b3f5bd4c). My suspicion (again, untested, sorry) is that there's some issue with `isSwift` being applied to the whole chain rather than decided per class. I think someone with more familiarity with the schema loader will need to look into this, I'm at the limits of my abilities.

But definitely a breaking change for the Swift side of things. (Or is there a better way to set up Swift classes with custom initializers?)

**Comment by jpsim** [comment]
This change happened in #1284 and lays the groundwork for a super awesome new Swift API, but makes using Realm in Swift a bit more cumbersome in the meantime :cry:.

Until our super awesome new Swift API is released, you'll unfortunately have to implement the following initializers if you want to use custom initializers:

```swift
init() {
  super.init()
}
init(object:) {
  super.init(object:object)
}
init(object:schema:) {
  super.init(object: object, schema: schema)
}
init(objectSchema:) {
  super.init(objectSchema: objectSchema)
}
```

**Comment by jpsim** [comment]
I understand this is suuuuper awkward, but as I said, this lays an important foundation.

**Comment by mrh-is** [comment]
Ah, that's ok! As long as there are clear directions. :+1: Thanks @jpsim! (YEAH SWIFT API)

**Comment by Pintouch** [comment]
Thanks! Overriding those constructors works!
Can't wait for the Swift API with generics Support!! :)

**Comment by xzf158** [comment]
class Sentence: RLMObject {
    convenience init(content: String){
        self.init(object: content)
    }
}
This is working for me.
http://quabr.com/27294702/how-do-i-fix-this-error-use-of-unimplemented-initializer-init-for-class

**Comment by LoganWright** [comment]
Just in case anyone else comes here that is beginning Realm for the first time and doesn't know the argument types, here's a drop in solution for RLMObjects with custom initializers.  Just add this to your class

```Swift
    // MARK: RLMSupport
    
    /*
    Initializers required for RLM Support -- https://github.com/realm/realm-cocoa/issues/1101
    */
    
    override init(object: AnyObject?) {
        super.init(object:object)
    };
    override init(object value: AnyObject!, schema: RLMSchema!) {
        super.init(object: value, schema: schema)
    }
    override init(objectSchema: RLMObjectSchema) {
        super.init(objectSchema: objectSchema)
    }
```

**Comment by jdelaune** [comment]
Will we know when the new Swift API hits? I assume it hasn't yet

**Comment by tgoyne** [comment]
It's now merged to master if you want to play around with it. We'll make an official announcement once it's included in a release.

**Comment by weixiyen** [comment]
Nice! when is the anticipated release?

**Comment by depl0y** [comment]
It would be awesome if the podspec could be updated to include the Swift release. Makes it a lot easier to *test* it out :)

One of the things I really don't like is specifying default values for my properties because some of them are required and now this isn't enforced at compile-time.

**Comment by jpsim** [comment]
@depl0y we'll be writing a new podspec for RealmSwift. Subscribe to #1705 to know when that's done.

> One of the things I really don't like is specifying default values for my properties because some of them are required and now this isn't enforced at compile-time. Also, adding the initializers mentioned here will not work when you work with non-optional properties without a default value.

Default values aren't strictly necessary, although calling `init()` is required to succeed. Aside from that, you can create any number of initializers in any format you like, as long as it calls `super.init()` at some point.

**Comment by depl0y** [comment]
@jpsim yup, but you can't create a custom init, if there are **required** properties.

For example:

```
class MyOwnClass: RLMObject {
	
	dynamic var on: Bool = false;
	dynamic var someRelation: MyOtherClass
	
	init(someRelationParameter: MyOtherClass) {
		
		self.someRelation = someRelationParameter;
		super.init();
		
	}
}
```

This throws an error without a initialiser called `init()`. So then you create a simple initialiser, like this:

```
override init() {
	super.init();
}
```

Of course you get a compile error here, because you are calling `super.init()` before the property `someRelation` is set. So should I set the `someRelation` property just to `MyOtherClass()`?

```
override init() {
	self.someRelation = MyOtherClass();
	super.init();
}
```

Finally you end up with a bunch of initialisers (`override init()`, `override init!(objectSchema schema: RLMObjectSchema!)` and your custom initialiser).  And this leads to all kinds of bugs, like objects being created with default values.

I created an example:

```
class DemoObject1: RLMObject {
 
	dynamic var someObject: DemoObject2;
	
	
	override init() {
		self.someObject = DemoObject2();
		super.init();
	}
	
	override init!(objectSchema schema: RLMObjectSchema!) {
		self.someObject = DemoObject2();
		super.init(objectSchema: schema);
	}
	
	init(someObject: DemoObject2) {
		self.someObject = someObject;
		
		super.init();
	}
	
}

class DemoObject2: RLMObject {
	
	dynamic var name: String = "";
	
}
```

Now, what should be the appropriate way to init a DemoObject2, init a DemoObject1 and commit them to the database?

I tried:
```
RLMRealm.defaultRealm().beginWriteTransaction()
var demo2 = DemoObject2()
demo2.name = "MyDemoObject"
RLMRealm.defaultRealm().addObject(demo2);

var demo1 = DemoObject1(someObject: demo2)
RLMRealm.defaultRealm().addObject(demo1);
RLMRealm.defaultRealm().commitWriteTransaction();
```
But this results in 2 DemoObject2 objects being stored, one with a `name` and the other without. The DemoObject1 is stored in the database, but the `someObject` property is always pointing to a record without the `name` value set.

I tried splitting it up in multiple transactions, but this ends in the same problem. (This might even be a separate thread, sorry about that).

**Comment by yoshyosh** [comment]
Another example of a working init
![custominit](https://cloud.githubusercontent.com/assets/775056/7169572/8cfd535a-e37b-11e4-82bd-2559a9f9c639.png)

**Comment by jpsim** [comment]
@yoshyosh are you sure `init()` and `init!(objectSchema schema: RLMObjectSchema!)` are necessary at all here? All they do is call super.

**Comment by tgoyne** [comment]
They're needed for the default property values to work when the other initializers are called from obj-c. It's (probably) a swift bug.

**Comment by lbanders** [comment]
We have run in to similar problems, but it seems to be gone in 0.91.3 and Swift 1.2. In fact the build failed when we had the override init() methods.

**Comment by jpsim** [comment]
We'll be releasing a Swift-specific optimized API in the very near future, which will make using custom initializers in Swift much friendlier.

**Comment by acoleman-apc** [comment]
If this is required, why is it not mentioned in the swift docs located here: https://realm.io/docs/swift/latest/#models

It seems to me that the models section needs a init subsection with a copy of the latest / working examples listed here . . . .

**Comment by jpsim** [comment]
@acoleman-apc this issue was last active over 4 months ago and is no longer relevant.

To override an `Object` initializer, just add it to your model:

```swift
public class MyModel: Object {
    required public init() {
        // custom initialization logic
        super.init()
    }
}
```

**Comment by acoleman-apc** [comment]
@jpsim Thanks but I have already added similar code to my project.  The point was that this isn't mentioned in the current documentation but is instead in an issue that has been open since November of 2014.  At this point, doesn't it deserve a mention in the official documentation?

**Comment by jpsim** [comment]
This issue is actually not open, but rather has been closed for over 4 months.

However, as with anything you may be struggling with in Realm, we're open to updating our docs in order to clarify. But we generally avoid documenting standard language behavior like overriding parent class methods or adding custom methods, as seems to be the case here.

**Comment by frankradocaj** [comment]
@jpsim I'm kind of a newbie with Swift (hey, aren't we all?). Documentation in the main website stating that you have to implement like the following would be *very helpful* in getting started with Realm (aka "the happy path" 😀). 

To create a custom constructor:

    class MyModel: Object {

        // Make sure to declare this constructor if you wanna have a custom one like below
        required init() { 
            super.init()
        }

        // Now go nuts creating your own constructor
        init(myCustomValue: String) {
            ...
        }
    }

**Comment by DrJid** [comment]
+1 to @frankradocaj 
I'm a newbie to Realm and this was actually quite frustrating. So a mention in the docs for someone just getting started would be *really* nice. Was going to skip on realm because it seemed harder than it should be.

**Comment by kharmabum** [comment]
+1 on including this in the docs. Especially an example with relations.

**Comment by art-divin** [comment]
+1 for adding this into the "happy path" reference part. -3 hours.

**Comment by ed-mejia** [comment]
+1 @frankradocaj  for the example, that should be on the main documentation :tired_face:

**Comment by jpsim** [comment]
@ed-mejia we have a section in our docs on this: https://realm.io/docs/swift/latest/#adding-custom-initializers-to-object-subclasses

**Comment by ed-mejia** [comment]
Hey @jpsim thanks for your comment.

In my case it did't work just with that, maybe because I need other init since Im using a parsing Json library, look at my actual model:

```
import Foundation
import Realm
import RealmSwift
import Gloss

public final class RoleModel: Object, Decodable {
    
    dynamic var roleId = 0
    dynamic var title = ""
    dynamic var updatedAt: NSDate? = NSDate()
    
    override public static func primaryKey() -> String? {
        return "roleId"
    }
    
    public init?(json: JSON) {
        super.init()
        // check for required values in order to return a valid object
        guard let roleId: Int = "role_id" <~~ json, let title: String = "title" <~~ json else {
            return nil
        }
        
        self.roleId = roleId
        self.title = title
        self.updatedAt = Decoder.decodeDate("updated_at")(json)
    }

    // MARK: - Required initializers to make Realm works with custom inits
    required public init() {
        super.init()
    }
    
    required override public init(realm: RLMRealm, schema: RLMObjectSchema) {
        super.init(realm: realm, schema: schema)
    }
}
```

In my case the compiler requires me to implement ***required public init()***

***public init(realm: RLMRealm, schema: RLMObjectSchema)*** is not required by the compiler but the App crash when I try to do this after a query:

```
let contents = realm.objects(RoleModel)
print("from DB: \(contents.count)")
print(contents[0]) //<- it crash here
```

And the crash indicates that I haven't implemented ***public init(realm: RLMRealm, schema: RLMObjectSchema)***

**Comment by kishikawakatsumi** [comment]
@ed-mejia It is more simple to use `public convenience init?(json: JSON)` instead `public init?(json: JSON)`. If you implement the convenience initializer, the compiler doesn't require to implement other initializers.

Like the following (Change `public init?` to `public convenience init?` and `super.init()` to `self.init()`):

```
public final class RoleModel: Object, Decodable {
    dynamic var roleId = 0
    dynamic var title = ""
    dynamic var updatedAt: NSDate? = NSDate()

    override public static func primaryKey() -> String? {
        return "roleId"
    }

    public convenience init?(json: JSON) {
        self.init()
        // check for required values in order to return a valid object
        guard let roleId: Int = "role_id" <~~ json, let title: String = "title" <~~ json else {
            return nil
        }

        self.roleId = roleId
        self.title = title
        self.updatedAt = Decoder.decodeDate("updated_at")(json)
    }
}
```

**Comment by ed-mejia** [comment]
@kishikawakatsumi You are totally right :+1: thanks for that clarification :smile:

**Comment by rameez-leftshift** [comment]
Hey guys have the same issue but not able to resolve it by following the above steps. Can you help me with it??/

**Comment by ed-mejia** [comment]
@rameez-leftshift Please explain your case, attach examples and maybe we could help you ..

**Comment by rameez-leftshift** [comment]
Here is my class which is causing the crash 
`public class StoryBoard: Object, Deserializable {
    
    public let categories = List<Category>()
    public dynamic var status: Status?
    public dynamic var id = ""
    public dynamic var title = ""
    public dynamic var description_text = ""
    public dynamic var sample_video_url = ""
    public dynamic var start_screen_text = ""
    public dynamic var end_screen_text = ""
    public let scenes = List<Scene>()
    public  let image_assets = List<ImageAsset>()
    public  let music_assets = List<MusicAsset>()
    public dynamic var featured = false
    public dynamic var artwork = ""
    public dynamic var artworkTile = ""
    public dynamic var artworkVideoURL = ""
    public dynamic var artworkVideoLocalPath = ""
    public dynamic var createdAt = NSDate()
    public dynamic var updatedAt = NSDate()
    public dynamic var isPrivate = false
    public dynamic var organizationID = ""
    public dynamic var min_time = 0
    public dynamic var max_time = 0
    public required init() {
        status = Status()
        super.init()
    }
    
    class func find(id:String) -> StoryBoard? {
        let realm = try! Realm()
        let storyBoard = realm.objectForPrimaryKey(StoryBoard.self, key: id)
        print("\(storyBoard)")
        if let storyBoard = storyBoard {
            return storyBoard 
        } else {
            return nil   
        }    }
    
    public class func allPublicObjects() -> Array<StoryBoard> {
        let realm = try! Realm()
        let results = Array(realm.objects(StoryBoard).filter("isPrivate == false"))
        return results
        //        return self.objectsWithPredicate(NSPredicate(format: "isPrivate = %@", NSNumber(bool: false)))
    }
    
    public class func allPrivateObjects() -> Results<StoryBoard> {
        let realm = try! Realm()
        let results = realm.objects(StoryBoard).filter("isPrivate == true")
        return results
        // return self.objectsWithPredicate(NSPredicate(format: "isPrivate = %@", NSNumber(bool: true)))
    }
    
    public class func getLastUpdatedAt(isPrivate: Bool = false) -> NSDate? {
        let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
        let currentUser = appDelegate.getCurrentUser()
        let organization = currentUser.objectForKey("organization") as? [String: AnyObject] ?? [:]
        let orgID = organization["id"] as? Int ?? 0
        var orgIdStr = ""
        
        if isPrivate && orgID != 0 {
            orgIdStr = "\(orgID)"
        }
        let realm = try! Realm()
        let predicate : NSPredicate = NSPredicate(format: "isPrivate = %@ AND organizationID = %@", NSNumber(bool: isPrivate), orgIdStr)
        
        let result = realm.objects(StoryBoard).filter(predicate).sorted("updatedAt", ascending: false)
        //  let result = StoryBoard.objectsWithPredicate(NSPredicate(format: "isPrivate = %@ AND organizationID = %@", NSNumber(bool: isPrivate), orgIdStr)).sortedResultsUsingProperty("updatedAt", ascending: false)
        if result.count > 0 {
            return (result.first!).updatedAt
            // return (result.firstObject() as! StoryBoard).updatedAt
        }
        
        return nil
    }
    
    // Specified primaryKey.
    public override class func primaryKey() -> String {
        return "id"
    }
    
    required public init(data: [String: AnyObject]) {
        let new_id: Int = data["id"]! as! Int
        id =  "\(new_id)"
        isPrivate <-- data["is_private"] as Bool
        organizationID <-- data["organization_id"] as String
        title <-- data["title"]
        description_text <-- data["description"]
        sample_video_url <-- data["sample_video_url"]
        start_screen_text <-- data["start_screen_text"]
        end_screen_text <-- data["end_screen_text"]
        featured <-- data["featured"]
        let artworkUrl = data["artwork"] as! [String : AnyObject]
        artwork <-- artworkUrl["url"]!
        let artworkTileUrl = data["artwork_tile"] as! [String: AnyObject]
        artworkTile <-- artworkTileUrl["url"]
        artworkVideoURL <-- data["artwork_video_url"]
        min_time <-- data["min_time"] as Int
        max_time <-- data["max_time"] as Int
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm::ss Z"
        createdAt <-- dateFormatter.dateFromString(data["created_at"] as! String)
        updatedAt <-- dateFormatter.dateFromString(data["updated_at"] as! String)
        //Check if Status is present then add reference or just add reference
        status = Status(data: data["status"] as! [String : AnyObject])
        let rawOrdering: [String:Int] = data["shot_ordering"] as! [String:Int]
        var reverseShordOrdering: [Int:Int] = {
            var reversedOrdering = [Int:Int]()
            for (key, value) in rawOrdering {
                let value = value as Int
                let key = Int(key)
                reversedOrdering[value] = key
            }
            return reversedOrdering
        }()
        // Parse all Scenes and store in db
        var _scenes = [Scene]()
        _scenes <-- data["shots"]
        for _scene in _scenes {
            _scene.order = reverseShordOrdering[Int(_scene.id)!]!
            _scene.storyBoardId = Int(id)!
        }
        scenes.appendContentsOf(_scenes)
        
        // Parse all ImageAsset and store in db
        var _image_assets = [ImageAsset]()
        _image_assets <-- data["image_assets"]
        //        image_assets.addObjects(_image_assets)
        image_assets.appendContentsOf(_image_assets)
        // Parse all Categories and store in db
        var _categories = [Category]()
        _categories <-- data["categories"]
        //categories.addObjects(_categories)
        categories.appendContentsOf(_categories)
        // Parse all MusicAsset and store in db
        var _music_assets = [MusicAsset]()
        _music_assets <-- data["music_assets"]
        // music_assets.addObjects(_music_assets)
        music_assets.appendContentsOf(_music_assets)
        DirOperations.CreateDirIfNotExists(Paths.Musics.stringByAppendingPathComponent("/\(new_id)"))
        DirOperations.CreateDirIfNotExists(Paths.Videos.stringByAppendingPathComponent("/story_boards/\(new_id)/artwork"))
        super.init()
    }
    
    public class func fromJSON(data: [String : AnyObject]) -> StoryBoard? {
        return StoryBoard(data: data)
    }
    
`

let me know if you need anything else

**Comment by ed-mejia** [comment]
Without knowing what's you crash about.

could you please try this first, replace your init this way:

```
public convenience init(data: [String: AnyObject]) {
        self.init()
// PUT ALL your initialisation here
}
```

**Comment by rameez-leftshift** [comment]
This is the error which i get : 
use of unimplemented initializer 'init(realm:schema:)' for class 'App.StoryBoard'. 

Your mentioned solution doesn't work. Thank you for the help though. Also i'm using swift 2.1.1 and realm version 0.97.4.

**Comment by ed-mejia** [comment]
Weird, that's the same error I got previously and it's working fine with the provided solution,

try to put this in your class:

```
// MARK: - Required initializers to make Realm works with custom inits
    required public init() {
        super.init()
    }
```

And let's see if you can avoid the crash... this should not be the final solution though.

**Comment by rameez-leftshift** [comment]
i already have the at the start of the code snippet, its immediately after my declarations.

**Comment by rameez-leftshift** [comment]
Have created a new question for my problem (https://github.com/realm/realm-cocoa/issues/3185).

**Comment by jhoughjr** [comment]
I'm noticing the docs on custom initializers aren't working for me.
`import Foundation
import RealmSwift

class Session: Object {
    
    dynamic var uuid: String = NSUUID().UUIDString
    dynamic var startTime: NSTimeInterval
    dynamic var endTime: NSTimeInterval


    convenience init(startDate:NSDate) {
        self.init()
        self.startTime = startDate.timeIntervalSince1970
        
    }
    
    func spanString() -> String {
        var returnString = ""
      

        return returnString
    }
    
    override class func primaryKey() -> String {
        return "uuid"
    }
}`

The compile error is : Missing argument for parameter 'startDate'
It occurs at the self.init() call.
I used the code example in the docs section on custom initializers.
Any ideas?

**Comment by kharmabum** [comment]
Try setting initial values for both startTime and endTime.

**Comment by jhoughjr** [comment]
So from reading this and the linked issue, I infer that Realm simply cannot support optionals and convenience initializers. Is that the case?

**Comment by jpsim** [comment]
> So from reading this and the linked issue, I infer that Realm simply cannot support optionals and convenience initializers. Is that the case?

That's not the case, see Realm's documentation on custom initializers: https://realm.io/docs/swift/latest#adding-custom-initializers-to-object-subclasses

**Comment by bdkjones** [comment]
I realize this is an old thread, but it would be REALLY handy if stuff like this were documented *right up front* for Realm. Important details like, "You have to use the default `init()` method on `Object` subclasses" is something to tell folks right away, in the "Welcome to your first Realm project" tutorials. Otherwise, you spend hours writing your own `init()` methods only to get a crash and then dig through GitHub issues to discover yet another arcane limitation of Realm.

**Comment by xingheng** [comment]
It's mid-2023, and Realm 10.33 still has the same issue.
