### ISSUE TITLE
Crash on trying to access default Realm

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#1126]
Hey guys,

when trying to access the default Realm I sometimes get a very strange error:

Error Domain=io.realm Code=6 "/var/mobile/Applications/24C981CC-5D88-478B-AD13-260DFBC7DB91/Documents/default.realm.lock" UserInfo=0x16ece4f0 {Error Code=6, NSLocalizedDescription=/var/mobile/Applications/24C981CC-5D88-478B-AD13-260DFBC7DB91/Documents/default.realm.lock}

I tried deleting the lock file because I thought it maybe was corrupted but that didn't help. Any hints on what is going wrong here? The exception is thrown in + (instancetype)realmWithPath:(NSString _)path
                     readOnly:(BOOL)readonly
                     inMemory:(BOOL)inMemory
                      dynamic:(BOOL)dynamic
                       schema:(RLMSchema *)customSchema
                        error:(NSError *_)outError

(RLMRealm.mm Line 331)

**Comment by shukla12manish** [comment]
how to access default.realm.lock file in Android Device Monitor ? I am saving it as log.txt but it is showing empty.
