### ISSUE TITLE
Support .@count and other aggregates in queries

### ISSUE THREAD

**Issue by laptobbe** [realm/realm-cocoa#1166]
Would be great if you could filter in a query based on the count of a to many relationship. See the example below. Right now it gives the following error: Column name @count not found in table

````
[Company objectsWhere:@"ANY projects.@count > 0"];
````

**Comment by ciryon** [comment]
What's the status here? I'm getting ```Property '@count' not found in object of type 'Bottle'``` when I try to do ```Realm().objects(Wine).filter("ANY bottles.@count > 0")```

**Comment by tgoyne** [comment]
It's still not implemented.

**Comment by kivannc** [comment]
Is there any workarounds for "ANY array.@count > 0" the query.

**Comment by bryanbartow** [comment]
Not having this is killing me.  Anyone found a workaround?

**Comment by RipRyness** [comment]
This is a workaround I used "ANY properties.id > 0"

**Comment by rdougan** [comment]
This now appears to work in 0.96.1 thanks to the above commits by @bdash.

    realm.objects(Brand).filter("ANY items.@count == 0")

**Comment by jpsim** [comment]
Yes, this is officially supported as of 0.96.0. Please see our release blogpost for details: https://realm.io/news/realm-objc-swift-0.96.0/

**Comment by Gerst20051** [comment]
👍

**Comment by StackHelp** [comment]
My app crashed when trying to filter with `@count`

`class PSMedia: Object {
    @objc dynamic var id = ""
    @objc dynamic var promotional_status = false
    var promotions = List<String>()
`

And here is that query that caused an issue

`realm.objects(PSMedia.self).filter("promotions.@count <= 5")`
