### ISSUE TITLE
RLMResults should be frozen during each runloop iteration

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1179]
We may also want to delay any updates until the next even loop when the entire Realm is updated. This will depend on how and when we decide to apply writelogs/changes on commits.

**Comment by alazier** [comment]
As a consequence of this RLMResults should also be frozen during fast enumeration.

**Comment by segiddins** [comment]
Merged via https://github.com/realm/realm-cocoa/pull/2170.
