### ISSUE TITLE
Support ALL and NONE queries

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1187]
Right now we only support any.

ANY: one or more objects matches
NONE: no objects matches
ALL: all objects matches
SOME: one or more, but not all objects matches.

**Comment by bdash** [comment]
SOME is a synonym for ANY, and is converted to ANY by NSPredicate:
```
>>> NSPredicate.predicateWithFormat_('SOME a = 1')
ANY a == 1
```

**Comment by yoshyosh** [comment]
NONE works

ALL is the only one left

**Comment by bdash** [comment]
It will be possible to support `ALL` when core is able to support subqueries. We'd be able to convert it to a core query that looks something like the following for `ALL collection.property == 1`:
```c++
auto collection = table->column<LinkList>(collection);
(collection->column<Int>(property) == 1).count() == collection.count();
```

**Comment by jpsim** [comment]
Closing since this is also being tracked in #1490
