### ISSUE TITLE
Document limitations when using Realm in GCD/background threads

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1188]
https://twitter.com/nicnocquee/status/500296839178891264

**Comment by pizthewiz** [comment]
With the multi-process handling in v0.91.0, this is probably still needed no?

**Comment by jpsim** [comment]
> With the multi-process handling in v0.91.0, this is probably still needed no?

There are still some rules regarding what's possible to do with regards to multithreading in Realm, even with the latest multi-process improvements.

Most notably, instances of `RLMObject`, `RLMArray`, `RLMResults` and `RLMRealm` are thread-specific.

That being said, any operation in Realm is thread safe and you never have to worry about a change from one thread affecting a transaction in progress on a different thread.

**Comment by jpsim** [comment]
The docs at realm.io/docs/cocoa now discuss this more.
