### ISSUE TITLE
Sign Realm Browser.app

### ISSUE THREAD

**Issue by pizthewiz** [realm/realm-cocoa#1202]
Semi-related to #680, it would be nice if `Realm Browser.app` in the binary distribution were signed - it would be a bummer if users dropped their whole system's security to run the app instead of treating it like an exception via initial launch from contextual menu.
```sh
$ codesign -dv ~/Downloads/realm-cocoa-0.88.0/browser/Realm\ Browser.app 
/Users/pizthewiz/Downloads/realm-cocoa-0.88.0/browser/Realm Browser.app: code object is not signed at all
```

**Comment by jpsim** [comment]
Closing in favor of #1733.
