### ISSUE TITLE
New Swift APIs

### ISSUE THREAD

**Issue by shmidt** [realm/realm-cocoa#1238]
```swift
extension RLMObject {
    // Swift query convenience functions
    public class func objectsWhere(predicateFormat: String, _ args: CVarArgType...) -> RLMResults {
        return objectsWhere(predicateFormat, args: getVaList(args))
    }

    public class func objectsInRealm(realm: RLMRealm, _ predicateFormat: String, _ args: CVarArgType...) -> RLMResults {
        return objectsInRealm(realm, `where`: predicateFormat, args: getVaList(args))
    }
}
```

As for me, I would like to see something like:

```swift
extension RLMObject {
    // Swift query convenience functions
    public class func objects(where predicateFormat: String, _ args: CVarArgType...) -> RLMResults {
        return objectsWhere(predicateFormat, args: getVaList(args))
    }

    public class func objects(inRealm realm: RLMRealm, _ predicateFormat: String, _ args: CVarArgType...) -> RLMResults {
        return objectsInRealm(realm, `where`: predicateFormat, args: getVaList(args))
    }
}
```

**Comment by alazier** [comment]
What's left to be done:
- [ ] documentation
- [ ] swift versions for RLMObjectBase methods `primaryKey`, `ignoaredProperties` etc. - these currently take/return objc types
- [ ] migrations/dynamic interface
- [ ] hide `getGenericListPropertyNames` and other private apis
- [ ] fix/workaround the auto-linking issue
- [ ] comprehensive testing

@jpsim please add other missing items you are aware of.

**Comment by jpsim** [comment]
I've just checked the "walk through Objective-C API and add missing aspects in Swift interface", but that excludes `Migration.swift`.

**Comment by alazier** [comment]
The new apis have been merged to master.
