### ISSUE TITLE
Crash when device is locked

### ISSUE THREAD

**Issue by melbyruarus** [realm/realm-cocoa#1260]
# Goal
Use Realm while the device is locked
# Expected results
Realm will behave the same as it does when the device is not locked, or will fail gracefully if this is not possible.
# Actual results
Calling any Realm method that will read/write data to the disk while the device is locked will cause the app to crash.
# Steps to reproduce
Will require:
* An iOS 8 device with PIN set and auto lock set to immediate

1. Create a new Swift Xcode project linking against Realm 0.89
2. Add code to the project which will execute in the background by using location services, audio, app refresh etc. Easiest option is to use background location services. This requires selecting the appropriate option in the Background Modes of the capability tab and starting to listen for updates before the app is backgrounded.
3. Add code to the background callback code which will trigger a read/write of the database.
4. Install on a device
5. Open the app
6. Give permissions to use whatever background modes were selected
7. Lock the device

The app will then crash sometime later when iOS stops allowing access to encrypted data.

# Code sample
https://github.com/melbyruarus/Realm-Background-Crash

The crash is triggered in the LocationHelper.log method

# Discussion
I believe this occurs because if a PIN is set and the device is locked then shortly thereafter iOS throws away the decryption keys for files which are only accessible while the device is unlocked (the default?). This means that the Realm database file becomes inaccessible and gets a read/write/open error when accessed, and this error is not correctly handled.

Ideally there would either be a way to customise the creation of the database file so that it can be specified as not needing to be protected on lock, and additionally any read/write/opens should fail gracefully rather than exploding.

This may well be a duplicate of https://github.com/realm/realm-cocoa/issues/773

# Version info
iOS 8, Realm 0.89, Xcode 6.1.1

**Comment by kronik** [comment]
I had the same issue in obj-c code: https://github.com/realm/realm-cocoa/issues/1077

**Comment by alazier** [comment]
@kronik this does seem to be the same issue.

I think we can make this work for the case @melbyruarus provided. If make things fail gracefully by properly returning an error when opening a Realm using the initializer with an output error, then users can at least detect and avoid crashing by getting a new Realm instance and checking the error before performing any potentially unsafe background operations.

The ideal long term solution though would be to actually make things work in the background.

**Comment by segiddins** [comment]
It appears to me that we already catch any C++ exceptions inside `-[RLMRealm initWithPath:key:readOnly:inMemory:error:]` (https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm.mm#L262).

**Comment by alazier** [comment]
@segiddins there are other core operations in the factory method which are not wrapped with an exception handler - these cases should also return an error from the factory methods. There is also the possibility that we are not catching the type of exception being thrown in this case as we may be missing some handers.

**Comment by segiddins** [comment]
Realm actually will fail gracefully as long as you use on of the factory methods that takes an error parameter (and a pointer to an `NSError` is passed in). The answer in situations like this is either to disable `NSFIleProtection` entirely (and optionally use Realm's built-in encryption support), or to recognize that opening the Realm when the app is in the background can fail, and using the appropriate factory method so you can handle the error (and thus the exception won't be thrown by Realm).

@melbyruarus I hope this helps.

**Comment by frankcjw** [comment]
Is there any way to read/write while device was locked ?

**Comment by jpsim** [comment]
You'll have to set `NSFileProtectionAttributes` on the realm files to allow reading when locked. See https://github.com/realm/realm-cocoa/issues/1571#issuecomment-77901737

**Comment by rex-remind101** [comment]
@jpsim it seems that the parent directory advised to change `NSFileProtectionAttributes` of in the documentation may contain files not pertaining to realm. Is there a way to set the realm config to store all realm files and auxiliary files into a specific directly, separate from the rest of the application documents directory?

**Comment by rex-remind101** [comment]
Figured it out:
```
config.fileURL = [[[[config.fileURL URLByDeletingLastPathComponent]
                        URLByAppendingPathComponent:kRealmDirectory]
                       URLByAppendingPathComponent:kRealmDBName]
                      URLByAppendingPathExtension:kRealmExtension];
```

**Comment by rex-remind101** [comment]
Also, fyi, using a subdirectory doesn't seem to work with `config.deleteRealmIfMigrationNeeded = YES;`. Have to `@try{} @catch{}` manually.
