### ISSUE TITLE
make the push_cocoapods Jenkins job work on any CI machine

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1263]

**Comment by jpsim** [comment]
Should also lint with `--use-frameworks`

**Comment by segiddins** [comment]
Can use the `COCOAPODS_TRUNK_TOKEN`

**Comment by tgoyne** [comment]
The thing that doesn't work is that the job assumes that the workspace already has the repo present and with the correct thing checked out from a previous job, and that stopped being the case when we started using multiple machines.

**Comment by jpsim** [comment]
This is now fixed.
