### ISSUE TITLE
Compile error 'Could not build Objective-C module Realm'

### ISSUE THREAD

**Issue by Jeswang** [realm/realm-cocoa#1275]
System:
- OS X 10.10.1
- Xcode 6.1

Problem:
I created a command line program with swift and followed the tutorial in the website. When I compiled, the compiler said error  'Could not build Objective-C module Realm'.

Current solution:
If I remove the Realm.framework in my debug folder(mine is /Users/jeswang/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug), then it will compile OK. Every time I change something in code, I have to delete it. 

Why is this? Anybody knows or faces the same problem? The Xcode's problem or the setting's problem?

**Comment by schmitzoide** [comment]
Still happens with Xcode 6.4 and Swift 1.2, very annoying.

**Comment by Legoless** [comment]
Hm, I have this issue too, cleaning DerivedData directory sadly does not help. :(
