### ISSUE TITLE
Add method exchangeObjectAtIndex:withObjectAtIndex: to RLMArray

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1276]
This is available on NSMutableArray. Requested by a user.

**Comment by alazier** [comment]
We should add a ```swap``` method in link_view.hpp before implementing this method.

**Comment by astigsen** [comment]
There is already a task for this in asana

**Comment by astigsen** [comment]
While such a method does not exist on NSMutableArray, I also think we should have a `moveObjectAtIndex:toIndex` method.

**Comment by wgywgy** [comment]
Is There any process?

**Comment by jpsim** [comment]
No progress to report.

**Comment by jpsim** [comment]
@wgywgy this is now merged into `master`! thanks for your patience...
