### ISSUE TITLE
Support sorting by keypath

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1277]
Lets say I have:

```
 class Quote: RLMObject {
   dynamic var sentence = ""
 }
```

Could I sort an RLMResults, generated by a query, by the length of the sentence property?

**Comment by alazier** [comment]
I think the proper solution here is to support sorting by keypath. Will change the issue name accordingly.

**Comment by CraigSiemens** [comment]
I recently ran into a similar issue.

Would this also include being able to sort based on a property on a related object? For example, if I have two models with the relationship `Car -> Color`, I would like to be able to sort the Cars by `color.name`.

**Comment by jpsim** [comment]
That's precisely what this issue is tracking.

**Comment by sbooth** [comment]
I'm very interested in this as well.

**Comment by iantheparker** [comment]
+1

**Comment by guillermomuntaner** [comment]
+1 I expected this to work same way subqueries do!

**Comment by maxoly** [comment]
+1

**Comment by maxoly** [comment]
+1

**Comment by njovy** [comment]
+1

**Comment by BartBM** [comment]
+1

**Comment by rex-remind101** [comment]
:+1:

**Comment by marchy** [comment]
Any updates on this? This seems to keep popping up in our domain (ie: for a simple Chat and Messages, want to sort chats by last message's CreatedAt date). Right now have to duplicate the data ("LastMessageCreatedAt" property on chat to do this.) These must be explicitly updated every time a new message appears in order for both sorting AND notifications to work properly (ie: Chats list screen to update to display the latest chat at the top).

Would be tremendously better if this was supported natively.

**Comment by jpsim** [comment]
Sorry, nothing to report on this feature.

**Comment by Koranda** [comment]
+1 (same way as with subqueries person.dog.name)

**Comment by minoue10** [comment]
+1

**Comment by gerardo55** [comment]
+1
I already asked a question on this issue on Stackoverflow before I was aware of this issue tracker at Github. Hopefully, this functionality could be added to Realm in the near future.
http://stackoverflow.com/questions/37316378/how-to-combine-swift-sort-methods-with-realm-containers

**Comment by sehajc** [comment]
+1

**Comment by OllaAshour** [comment]
+1

**Comment by rorlig** [comment]
+1

**Comment by Nick-The-Uncharted** [comment]
+1

**Comment by JonCox** [comment]
+1

**Comment by nicolasguenther** [comment]
+1

**Comment by TheSwifter** [comment]
+1

**Comment by michaelpace** [comment]
+1

**Comment by rjvir** [comment]
+1

**Comment by spee** [comment]
+1

**Comment by scompton** [comment]
+1

**Comment by JotaMelo** [comment]
+1

**Comment by mwahlig** [comment]
+1

**Comment by mureatencio** [comment]
+1

**Comment by marchy** [comment]
Any plans on this now that 1.1 is out?

I'm sure the Swift 3 migration has kept the team very busy but it would be great to see some new features come in not just the platform support  =)

**Comment by A1iAshoor** [comment]
+1

**Comment by kaunteya** [comment]
+1

**Comment by mkayswork** [comment]
+1

**Comment by Maxwellimus** [comment]
+1

**Comment by dhansiddh** [comment]
+1

**Comment by laferilsmith** [comment]
+1

**Comment by dylangwight** [comment]
+1

**Comment by VladasZ** [comment]
+1

**Comment by ivedeneev** [comment]
+1

**Comment by BlueVirusX** [comment]
+1

**Comment by randolphlee** [comment]
+1

**Comment by jpmcosta** [comment]
+1

**Comment by insch** [comment]
+1

**Comment by rslim087g** [comment]
+1

**Comment by LukasGram** [comment]
+1

**Comment by timofverberg** [comment]
+1

**Comment by ecaste** [comment]
+1

**Comment by juanmatm82** [comment]
+1

**Comment by weibel** [comment]
+1

**Comment by bogosmer** [comment]
+1

**Comment by michal-skrabacz** [comment]
+1

**Comment by abeintopalo** [comment]
+1

**Comment by hsandyque** [comment]
+1

**Comment by mamalat** [comment]
People, use reactions instead of writing "+1". It doesn't help anyone. Just getting too much useless of notifications.

**Comment by bdash** [comment]
Support for sorting based on simple key paths (traversing to-one relationships only, with no support for collection operators or non-persisted properties) is being added in #4505.

**Comment by jpsim** [comment]
Now available in Realm 2.2! https://realm.io/news/obj-c-swift-2-2-thread-safe-reference-sort-properties-relationships/

**Comment by Taco55** [comment]
This is a really great improvement!

I was just wondering whether key path sorting for to-many relationships will be supported in a future release as well? For my use case it would be even better to sort like: 
dogOwners.sorted(byKeyPath: "dogs.last.age")

**Comment by bdash** [comment]
Sorting over to-many relationships is a bit more involved than sorting over to-one relationships. Would you mind filing a new issue so we can track demand for that functionality?

**Comment by Taco55** [comment]
I just filed a new issue in #4554 for this.

**Comment by Isuru-Nanayakkara** [comment]
+1
