### ISSUE TITLE
Swift support for Cocoapods 0.36

### ISSUE THREAD

**Issue by newlix** [realm/realm-cocoa#1279]
The Cocoapods 0.36.beta1 is released. It would be nice to have official support. Thank you!
http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by drn** [comment]
:+1: Would really love to see this as well. Currently manually importing the framework into our Swift project.

**Comment by allaire** [comment]
I could make this works with the beta release by also including a pod that support the new cocoapods version (like alamofire)

**Comment by ealeksandrov** [comment]
This feature is required to use modules from Cocoapods, am I right?

Currently receiving this error after `pod install`:
`import Realm` - No such module 'Realm'
(For manually installed Realm it is working ok)

**Comment by allaire** [comment]
@ealeksandrov add `use_frameworks!` to your Podfile and it should works (make sure to use prerelease version of cocoapods).

**Comment by ealeksandrov** [comment]
@allaire that's fixed it, thanks a lot!
