### ISSUE TITLE
How to delete classes in realm file?

### ISSUE THREAD

**Issue by tailang** [realm/realm-cocoa#1283]
I have a realm file. It has six classes, but now I want to delete some classes. I find realm browser can delete object, but can't delete classes. thanks.

**Comment by xilin** [comment]
@jpsim May I asked how about the cost of the call `[realm deleteObjects:[MyRLMObjectSubclass allObjects]]`? Is it expensive for a large table?

**Comment by tgoyne** [comment]
Deleting allObjects uses an optimized implementation that does much less work than deleting the objects individually, but it does still do work proportional to the size of the table so for a sufficiently large table it could become expensive.

**Comment by xilin** [comment]
@tgoyne Thanks. So maybe in the future we can have better way to do this in realm.
