### ISSUE TITLE
Support comparing two linked properties

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1285]
For example, to get all persons with more children than siblings: `[Person objectsWhere:@"numberOfChildren > numberOfSiblings"]`. See [this Asana ticket in Core](https://app.asana.com/0/1462112455450/23162501187763) (private link).

**Comment by jpsim** [comment]
I was mistaken. Realm supports comparing two properties, but not two linked properties. So this works:

```objc
[ModelA objectsWhere:@"int1 > int2"]
```

but this doesn't:

```objc
[ModelB objectsWhere:@"modelA.int1 > modelA.int2"]
```

**Comment by jpsim** [comment]
Multilevel *equality* was added in #3419, but other comparisons still aren't supported.

**Comment by bdash** [comment]
This was mostly done in #2895. There are some complex predicates involving multi-level key paths that are not yet supported, but the `link.property > link.otherProperty` case [definitely works](https://github.com/realm/realm-cocoa/blob/v0.103.0/Realm/Tests/QueryTests.m#L1126-L1131).
