### ISSUE TITLE
Support comparing two linked keypaths in a query

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1286]
See https://groups.google.com/d/msg/realm-cocoa/WRI5oq1Y6zU/sk9-qVIYdjcJ.

**Comment by jpsim** [comment]
Blocked on https://github.com/realm/realm-core/pull/621.

**Comment by tgoyne** [comment]
That implements something different (comparing non-linked string properties).

**Comment by jpsim** [comment]
ok, I removed the blocked tag and unassigned myself.

**Comment by tgoyne** [comment]
Well, it is blocked on core support.

**Comment by jpsim** [comment]
@bdash could you look into whether or not this has been done recently?

**Comment by bdash** [comment]
Fixed in #2895.
