### ISSUE TITLE
data order be changed after deleteObject

### ISSUE THREAD

**Issue by DaidoujiChen** [realm/realm-cocoa#1289]
Hello,

i have a question for `deleteObject` behavior.

i `addObject` to realm like

     1
     2
     3
     4
     5
     6
     7

than delete the `3` object use `deleteObject`, i think the data should change to

     1
     2
     4
     5
     6
     7

but the data change to

     1
     2
     7
     4
     5
     6
     
why the latest object fill to the third position? is this a normal behavior?
if my english is not clear enough, i can create a repository to reproduce what i say.
thanks.

**Comment by GreatApe** [comment]
Hello! First of all, this only happens for lists of objects of a certain class that you can get from e,g. +allObjects (and not for RLMArrays) In these cases there is no guarantee on the ordering of objects, Realm can change it whenever it wants. In this case the behaviour you have experienced avoids having to 'move' all the objects that 'come after' the one you deleted!

So in short, if you need an ordered list of objects, put it in an RLMArray property!

**Comment by DaidoujiChen** [comment]
Hello @GreatApe,

thanks, i got it.
close this issue.
