### ISSUE TITLE
Dynamic interface support

### ISSUE THREAD

**Issue by Kirow** [realm/realm-cocoa#1291]
Does it possible to make two realm files with different data structure in single project? 
i.e. smth like SQLite with attach feature.

For example it will be very useful when I have large catalog of items on server, and i will upload only this catalog file with single table (no need to parse and save to db locally) and use it with my local db which have different structure.

**Comment by alazier** [comment]
Yes this makes sense, but only using a dynamic interface. With the object interface there would be no way to specify two differing schema as your table structure is defined at compile time. With a dynamic interface you can specify schema at runtime.

The good new is there is already internal support for a dynamic interface in Realm but the apis are currently private. We eventually plan to make these or similar apis public (after working through a few issues). The browser currently uses these apis if you want to take a look but at the moment they are liable to change.
