### ISSUE TITLE
Duplicate interface definition for class 'RLMResults', compile error when installing Realm via CocoaPods

### ISSUE THREAD

**Issue by cyanware** [realm/realm-cocoa#1303]
When installing Realm via CocoaPods for iOS and MacOSX targets within the same Xcode project, CocoaPods is creating duplicate references for each Realm header file when creating the Pods project.

This issue generates compiler errors "Duplicate interface definition for class ...".

A simple Podfile such as this one, will demonstrate the issue:

```
source 'https://github.com/CocoaPods/Specs.git'

target 'target-osx' do
    platform :osx, '10.9'
    pod 'Realm', '~> 0.87'
end

target 'target-ios' do
    platform :ios, '7.0'
    pod 'Realm', '~> 0.87'
end
```

The best explanation for this issue that I could find appears to be caused by an issue in the PodSpec file defining the Pod, and not an issue with CocoaPods itself: [Duplicate header references in build step #2565](https://github.com/CocoaPods/CocoaPods/issues/2565). We are using CocoaPods version 0.35.0, if that makes any difference.

**Comment by jpsim** [comment]
Thanks for filing this, @cyanware. This should be fixed in the next CocoaPods release thanks to @tgoyne's handiwork.
