### ISSUE TITLE
Rename api methods which take encryption keys

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1307]
We kind of depart from convention with our naming for methods which take an encryption key. For instance. Instead of using the phrase ```encryptedRealm```, we should just rename the ```key``` parameter to ```encryptionKey```. We should change the following methods from:
```objc
+ (instancetype)encryptedRealmWithPath:(NSString *)path
                                   key:(NSData *)key
                              readOnly:(BOOL)readonly
                                 error:(NSError **)error;
- (BOOL)writeEncryptedCopyToPath:(NSString *)path key:(NSData *)key error:(NSError **)error;
```
to
```objc
+ (instancetype)realmWithPath:(NSString *)path encryptionKey:(NSData *)key readOnly:(BOOL)readonly error:(NSError **)error;
- (BOOL)writeCopyToPath:(NSString *)path encryptionKey:(NSData *)key error:(NSError **)error;
```
which aligns better with the other method names and with the ```+ (void)setEncryptionKey:(NSData *)key forRealmsAtPath:(NSString *)path;``` method.

@tgoyne mentioned that someone objected to this naming in the past. Does this objection still exist? Thoughts @jpsim @segiddins ?

**Comment by segiddins** [comment]
:+1:

**Comment by jpsim** [comment]
I like your proposed changes, @alazier. Would make discovering the encrypted variants easier to discover through autocomplete too.

**Comment by tgoyne** [comment]
:+1:

**Comment by marcoscurvello** [comment]
I don't know if theses new version feature news on the website are published by you guys, but the method listed on the following url still uses the old method, thus misleading people, including myself.

[http://realm.io/news/realm-cocoa-0.89.0/](http://realm.io/news/realm-cocoa-0.89.0/)

**Comment by jpsim** [comment]
Hi @marcoscurvello, yes we post updates to the blog, twitter account and docs every time there's a new major version, which sometimes includes API changes. I'm sure you can understand that we can't possibly update old announcements. You can always see the latest documentation at https://realm.io/docs/objc/latest/.
