### ISSUE TITLE
Can Realm migration perform a type transformation?

### ISSUE THREAD

**Issue by bzmario** [realm/realm-cocoa#1311]
I've a property which is an `int` type, now I want to change it to `float`. Can I make it through a migration?

**Comment by mclark4386** [comment]
I see no reason why you couldn't. Check out the example of a migration here: https://github.com/realm/realm-cocoa/blob/master/examples/ios/objc/Migration/AppDelegate.m 
Hopefully that help^^

**Comment by bzmario** [comment]
@mclark4386 Thank you!
