### ISSUE TITLE
Support in RLMArray for basic types (int, strings, etc)

### ISSUE THREAD

**Issue by maxgoedjen** [realm/realm-cocoa#1312]
It'd be awesome if `RLMArray` supported the types `RLMObject` does (or just plain `NSArray`/Swift `Array` types for basic types), for use cases like this:

```
{
"id": "1234",
"name": "test",
"tags": ["one", "two", "three"]
}
```

**Comment by segiddins** [comment]
Closing as a duplicate of https://github.com/realm/realm-cocoa/issues/1120.
