### ISSUE TITLE
Install via carthage: Project [...] has no shared schemes

### ISSUE THREAD

**Issue by Jachobsen** [realm/realm-cocoa#1313]
When trying to install realm through Carthage, following your instructions, I get the following error:
```sh
$ carthage update
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "b30"
*** xcodebuild output can be found in /var/folders/rg/9gzvgrx177j1ldg25s71m6d40000gn/T/carthage-xcodebuild.OyBEi0.log
Project "TightDbObjcDyn.xcodeproj" has no shared schemes
```

The log is empty.

Cartfile
```
github "realm/realm-cocoa"
```

If I clone the repo and try to run `carthage build`, everything seems to work fine.

```sh
$ git clone git@github.com:realm/realm-cocoa
$ cd realm-cocoa
$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/rg/9gzvgrx177j1ldg25s71m6d40000gn/T/carthage-xcodebuild.mAepyX.log
*** Building scheme "iOS" in Realm.xcodeproj
*** Building scheme "iOS 8" in Realm.xcodeproj
...
```

**Comment by jpsim** [comment]
You're attempting to install a very old version of Realm ([b30](https://github.com/realm/realm-cocoa/releases/tag/b30) is from October 2013). You should try with our latest stable release ([v0.89.2](https://github.com/realm/realm-cocoa/releases/tag/v0.89.2)) or master.

**Comment by Jachobsen** [comment]
I see that b30 is an old tag, but I haven't specified anything except the repo name in my Cartfile. I tried adding `=> 0.89.2` but it still fetches b30. This might be a carthage issue though so I'll try to move the discussion there. Thanks!

**Comment by jpsim** [comment]
We've renamed our old releases of the b* format to v0.0.*, which now makes Realm play nice with Carthage's version parsing.

**Comment by Jachobsen** [comment]
Thanks!
