### ISSUE TITLE
Add mechanism to remove all cached Realms

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#1316]
I noticed that internally Realm is using an NSMutableDictionary to store the global RLMRealm instance cache. I want to be able to delete a secondary Realm file after the app is open but, without being able to know if the cache is clean, deleting the file I think is dangerous?

Instead could the cache be held as an NSMapTable so that the Realm instances can be held weakly or could there be a method to clean the cache?

**Comment by tgoyne** [comment]
The actual realm instances are stored in a a weak NSMapTable. The NSMutableDictionary maps paths to NSMapTables which hold weak references to RLMRealm instances for each thread. If you aren't holding any references to the realm (and it isn't sitting in an autorelease pool somewhere), the instances should be released.

**Comment by bigfish24** [comment]
Ok, well when I try to delete the Realm file and recreate a new Realm instance, I don't seem to be able to write to this new file? I perform a write transaction and then the Realm doesn't appear to actually have the data?

Here is the code snippet:

```
NSString *cacheRealmPath = cacheRealm.path.copy;
        
// Nil the Realm so that internally there is no reference to it in cache
cacheRealm = nil;
        
NSError *error;
if (![[NSFileManager defaultManager] removeItemAtPath:cacheRealmPath error:&error]) {
        NSLog(@"%@",error.localizedDescription);
}

// Requests a Realm instance utilizing the same path as previous deleted file
cacheRealm = [self realmForCache];
```

**Comment by bigfish24** [comment]
The issue I was having is that to properly remove the Realm file, requires deleting the *realm.lock too. Also, I noticed that I can call [RLMRealm performSelector:@selector(clearRealmCache)...] to clear the cache.
