### ISSUE TITLE
Sort a column in browser?

### ISSUE THREAD

**Issue by rmvz3** [realm/realm-cocoa#1321]
It would be very useful to me to be able to sort columns when I'm previewing the database in browser. As far I know, there's no way to do it in mac (and that's waaaaay strange in my opinion)

Thanks

**Comment by GreatApe** [comment]
This is something that is being considered. Constructing a good UI for this is not trivial but it would indeed be useful to have.

**Comment by rmvz3** [comment]
That would be nice. It would really help a lot. Thank you.
