### ISSUE TITLE
RLMResults for the IN operator aren't sorted as expected

### ISSUE THREAD

**Issue by rciobanu-omnifone** [realm/realm-cocoa#1325]
**Goal:**
I am trying to retrieve a bunch of objects from the Realm using the **IN** operator and an array of IDs and retrieve the results in the exact order of the IDs that I specified.
**Steps to reproduce:**
`    NSArray *listOfValues = @[@"a", @"b", @"c"];`
`    RLMResults *results = [aClass objectsInRealm:self.realm where:@"primaryKey IN %@", listOfValues];`
**Expected results:**
The objects in `results` when enumerated will be in the order specified in the `listOfValues`. So first object's `primaryKey` will be "a", second objects `primaryKey` will be "b", etc.
**Actual results:**
The results are, apparently, in the exact same order they appear in the database. As when seen with RealmBrowser.
**Version of Realm:**
0.89.1

I searched in case this is a duplicate but couldn't find any open issue to match this one. Also couldn't find this behaviour documented. Thanks.

**Comment by segiddins** [comment]
@rciobanu-omnifone queries with the `IN` operator are actually checking for _set inclusion_ (which happens element by element). If you want to get sorted results, you can sort the `RLMResults` you're getting back using [`sortedResultsUsingProperty:ascending:`](http://realm.io/docs/cocoa/0.89.2/api/Classes/RLMResults.html#//api/name/sortedResultsUsingProperty:ascending:) or [`sortedResultsUsingDescriptors:`](http://realm.io/docs/cocoa/0.89.2/api/Classes/RLMResults.html#//api/name/sortedResultsUsingDescriptors:).

**Comment by rciobanu-omnifone** [comment]
@segiddins Thank you for the reply.
My use case doesn't have a specific ascending or descending order, in the end it comes from a server response or user input.
I can't figure out a way to achieve that without additional post-processing (re-ordering the results)
or pre-processing by populating some transient property that will hold some order index.
Anyway, that's not your concern.
Thanks again for pointing me to the operator definition.
