### ISSUE TITLE
Swift: Create Int property when Int8 is used in a Swift model

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1329]
As @tgoyne stated in [this mailing list post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/realm-cocoa/gWvJ_uxY5kk/HnlHDFCwLGYJ):

> Objective-C's BOOL is unfortunately a typedef for char on 32-bit platforms rather than a proper boolean type, so we assume all 8-bit ints are boolean properties.

But we could still throw an exception if a model is declared in Swift using an Int8. The exception message could suggest that these properties be declared with an `Int` instead.

**Comment by alazier** [comment]
We should try to actually make this work properly if possible.

**Comment by jpsim** [comment]
I renamed the ticket to reflect actually fixing this instead of failing gracefully. Are there other types we should be doing this with?

**Comment by segiddins** [comment]
As far as I can tell, it's not possible to get that type info via swift reflection?

**Comment by tgoyne** [comment]
There's no additional information needed beyond what we're already getting from the obj-c introspection. We just need to treat properties of type 'c' as Int rather than Bool when they're defined on a Swift class.
