### ISSUE TITLE
RLMObject persisted in 2nd Realm requires migration before either is open

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#1334]
When utilizing two separate Realm's in one app, if a property is added to an RLMObject only persisted in the 2nd Realm, a migration must still be performed before the first Realm is opened, rather than just before the 2nd Realm is opened.

**Comment by bigfish24** [comment]
Looking at this further, it appears that any RLMObject in the project will get a table even if no objects of that class exist in that Realm. I assume this is where the dynamic API would allow for schema definitions that are unique to each Realm...

**Comment by alazier** [comment]
A migration is required anytime the schema has changed. Both of your Realms share the same schema (as it is defined by your object interfaces) so when any object changes, all Realms need to be updated to the latest schema and version.

In the future we will add the ability to use a dynamic interface where you can have multiple Realms at different schema versions, but in this case I think the behavior is correct.

**Comment by bigfish24** [comment]
Ok, I assumed it would be possible with the dynamic interface. Thanks for the follow up.

**Comment by alazier** [comment]
You are right that if you open the Realm using the dynamic interface the migration will not be applied. The api to do this is not public yet but you are welcome to give it a go. There is a private factory method for Realm which takes a dynamic flag.

**Comment by bigfish24** [comment]
Ah yeah. Does this require migration ever (seems like the scheme is generated on demand)?

**Comment by alazier** [comment]
Dynamic Realms never require a migration - but once the api is made public we will have to require this when their schema changes. At the moment there actually isn't a way to apply a custom migration to a dynamic realm, although the global migration block will be applied to a dynamic Realm when calling ```migrateRealmAtPath:```.

**Comment by bigfish24** [comment]
Got it. Well while it is tempting to use the functionality private functionality, we want to put this code into production so we can handle the migration globally if the cache objects ever need to change, but at this point, I don't anticipate it will be necessary. If anyone else ends up using the library I will just try to make it clear if a migration ever ends up being required.
