### ISSUE TITLE
Auto-refreshing realms and notifications possible race condition

### ISSUE THREAD

**Issue by BrentleyJones** [realm/realm-cocoa#1357]
I think I ran into a race condition regarding auto-refreshing realms and notifications.

When I have a notification on a realm it causes it to be cached for that thread, which means that it follows the auto-refreshing rules when reading from it instead of always being the latest data (Something I hadn't encountered before I used notifications, since I throw away my realm objects after reading from them). When the notification comes through it causes it to auto-refresh, so the latest write data is available.

The way that I have been using realm is to write in a background thread, then post a block on the main thread to do something with the written data. Before registering for notifications my realm object would always have the latest data, because we would be on the next run loop and the realm object was fresh. Now with notifications I would not find my data available, since my block would run before the notification was posted to the cached realm object.

For now I've fixed this by calling `refresh` on any realm that I plan on reading from. This is not ideal, so I was hoping that there would be a way to ensure that the auto-refreshing happens before any block of mine is run. I assumed that after the `commitWriteTransaction` or `transactionWithBlock` any dispatch_async on the main thread would run on an updated realm.

**Comment by segiddins** [comment]
Brentley,

There are two potential solutions to the issues you're running into. We cannot guarantee that the auto-refresh will happen on _any_ queue before your own block runs, or even that the refresh will happen on the exact next spin of the run loop. That being said, the following should work for you:

1) Using `-[RLMRealm addNotificationBlock:]` on your main queue `RLMRealm` instance. That block will be guaranteed to be called once that thread's realm instance is refreshed.

2) Do exactly what you're doing, which is dispatching your own notification and manually `refresh`ing the realm on the target thread (that `refresh` will guarantee that you're dealing with the most recently-committed data).

**Comment by BrentleyJones** [comment]
1 won't work, because it's way too broad, and this is my abstraction layer between my cached data and the client (we don't consume Realm objects in the app).

2 is fine, I just thought it was non-performant, otherwise it would already be done for auto-refreshed realms when I called `[Realm realmWithPath]`.

Also, it's not *any queue*, it's the main queue, which is the same queue that I have the notification setup on. By calling `dispatch_async` after the write commit, I am already after the point that realm itself should have done the same thing, so my block should be run after it (the blocks are queued serially). I believe the issue is that Realm is using `performSelector`, which is causing the realm notification to happen after block dispatches, since I read somewhere that the run loop will interleave two different types of events on the run loop?

Anyway, maybe there is another way for me to queue so I'm guaranteed to run after the notification, if realm won't change to update sooner.

**Comment by tgoyne** [comment]
Calling `refresh` manually won't hurt your performance. Calling `refresh` with nothing to do is very close to free, so calling it before the autorefresh happens just means that the work happens at a different time.

The notifications being unordered due to the mixing on GCD and `performSelect:onThread:` does sound plausible to me, since they do pretty different things.

**Comment by segiddins** [comment]
@BrentleyJones I just want to follow up and make sure you have refreshing working in your app?

**Comment by BrentleyJones** [comment]
Calling it manually is working.

**Comment by segiddins** [comment]
Glad to hear it!
