### ISSUE TITLE
crash when deleteAllObjects in the block called by dispatch_barrier_async

### ISSUE THREAD

**Issue by amo12937** [realm/realm-cocoa#1359]
I create dispatch_queue_t using `DISPATCH_QUEUE_CONCURRENT`.
When I tried to read tables using `dispatch_async` and write tables using `dispatch_barrier_async`, app was crashed by `EXC_BAD_ACCESS` sometimes.
Sometimes succeeded, but I cannot read a new data changed in write-transaction.

Here is my sample code. Please check out the repository, git-submodule-update (I use Realm as submodule), and run test.
https://github.com/amo12937/amo.RealmQueueHandler

- version of
    - xcode: 6.1.1 (6A2008a)
    - OSX: 10.10 Yosemite

Thanks.

**Comment by alazier** [comment]
It looks like this was introduced with this pr #1346. This has been merged to master but we have not released these changes yet (and wont until we have a fix). For the time being if you use the latest release from the website or you build from a commit before this pr was merged you should be able to avoid the issue.

**Comment by amo12937** [comment]
Thanks for replying.
I use the latest master branch, but still crash.
Here is screenshot when crashed.
![2015-01-21 12 43 01](https://cloud.githubusercontent.com/assets/6604044/5830934/2d26d304-a16b-11e4-847a-587f475e690e.png)
It looks like this is caused on `tightdb`.

**Comment by alazier** [comment]
You probably need to 'Reset Content and Settings...` on your simulator, or delete the app from a device. If an old Realm file with the int index still exists then you would still run into the same issue. When building from master I no longer see the crash.

**Comment by amo12937** [comment]
Thank you. I do `Reset Content and Settings...`, then I no longer see the crash.

Now I still have another error...
![2015-01-21 14 12 06](https://cloud.githubusercontent.com/assets/6604044/5831535/edd844fa-a177-11e4-8347-53d3ce35a224.png)

I close this issue and will create new issue..
Thanks m(_ _)m
