### ISSUE TITLE
Is it possible to create unique pair in realm?

### ISSUE THREAD

**Issue by Kirow** [realm/realm-cocoa#1360]
SQLite analogue:
```
UNIQUE(col1, col2)
```
OK csv Example:
**col1 | col2**
valA | val1
valA | val2
valB | val1
valB | val2

CONFLICT csv Example
**col1 | col2**
valA | val1:boom:
valA | val2
valA | val1:boom:

**Comment by segiddins** [comment]
@Kirow, Realm does not support creating multi-column unique constraints. Right now, the only way to guarantee the uniqueness of a column at the database level is to make that column the primary key.

**Comment by eriktelepovsky** [comment]
Is it on the features roadmap?

**Comment by jpsim** [comment]
> Is it on the features roadmap?

Not at the moment. There's a large number of features we want to add before getting to this.

**Comment by eriktelepovsky** [comment]
Issue #1192 seems to be a valid workaround. Right?

**Comment by jpsim** [comment]
Indeed.
