### ISSUE TITLE
Support object reuse/linking by primary key in createOrUpdate methods - remove RLMValidatedDictionary and RLMValidatedArray

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1362]
When calling one of the createOrUpdate variants, all object properties are required to reuse existing nested objects. We should support reusing nested objects with only the primary key specified.

**Comment by darren102** [comment]
Would it also be possible to have this go down the tree a few levels normally we stop around 3 or 4 but this is to consume the information where we don't want to make 2 or 3 requests when it can be nested into one request. I.e. not just doing one level deep, if the primary key exists two / three or four levels deep would be very nice to just have them associated together.

**Comment by alazier** [comment]
Once we get this fixed this should work the same at all levels of your object graph. At the moment it looks like this is not the case.

**Comment by alazier** [comment]
We need to refactor the RLMValidatedArray and RLMValidatedDictionary code paths to not use standalone objects. Alternatively we could keep these code paths for initializing standalone objects and have a new code path which correctly calls createOrUpdate for nested objects.
