### ISSUE TITLE
Fix templates installation

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1366]
See https://twitter.com/nate_west/status/557685148314259456

**Comment by jpsim** [comment]
Installing Xcode templates no longer fully works.

The "Cocoa" and "Cocoa Touch" in the left sidebar should not be there:

![image](https://cloud.githubusercontent.com/assets/474794/5828856/79e32790-a0be-11e4-8488-30515fb00c76.png)

But attempting to create it through there creates all the language files at once:

![image](https://cloud.githubusercontent.com/assets/474794/5828847/62dc4fe0-a0be-11e4-9112-36c7aa8d571b.png)

I think we should just install our templates under "Realm" and not under the system templates, which I never really liked anyway, and required root privileges.

**Comment by yoshyosh** [comment]
Does this also affect plugin installs from Alcatraz? I can update the docs to reflect how people should use the plugin

**Comment by nwest** [comment]
Thanks, guys. Is there any more info you need for me? I can provide the steps I took if needed.

**Comment by jpsim** [comment]
Yes, what we do here affects Alcatraz since it's really the same installation process.
