### ISSUE TITLE
'No value or default value specified for property' error with defaultPropertyValues implemented

### ISSUE THREAD

**Issue by frowing** [realm/realm-cocoa#1371]
It seems like when adding an object in `RLMAddObjectToRealm` it doesn't use the `defaultValues` that exist in the schema to populate the properties. This is my model object:

```
@interface Place : RLMObject

@property (nonatomic, strong) NSString *guid;
@property (nonatomic, strong) NSString *title;

@end

@implementation Place

+ (NSString *)primaryKey
{
    return @"guid";
}

+ (NSDictionary *)defaultPropertyValues
{
    return @{@"guid" : @"", @"title" : @""};
}

@end

```

And this is how I create new object:

 ```
Place *place = [Place objectForPrimaryKey:guid];
        
if (!place)
{
    place = [[Place alloc] init];
}

place.guid = guid;
place.title = title;
        
[realm addObject:place];

```

**Comment by yoshyosh** [comment]
Hi @frowing you are setting place's values here:

````obj-c
place.guid = guid;
place.title = title;
````
So you are overriding the default property values. When guid or title is nil this error is thrown. So you will need to make sure you aren't passing in nil values into your place object

**Comment by amccarri** [comment]
@yoshyosh are you saying this is as designed?

**Comment by jpsim** [comment]
@amccarri yes, setting a property to `nil` has a distinctly different meaning than not setting it at all once we officially release null support as described here: https://realm.io/news/realm-objc-swift-0.96.0-beta/
