### ISSUE TITLE
Using single code path for creating exceptions/Add library version to user info

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-cocoa#1372]
Add the version text of the cocoa binding to all exceptions thrown from core. In RLMRealm:throw_objc_exception()
In likely doesn't make sense to include it in make_realm_error.

**Comment by alazier** [comment]
If we do this at all we should add it to the userInfo for the exception, not to the message.

There is currently not a common code path used for exceptions at the moment so this requires changing quite a bit of code.

**Comment by bmunkholm** [comment]
agree to adding to user info.
Most likely the interesting exceptions that would benefit from this info are the ones thrown from core which are "exceptional" in nature. That's only one place in the method mentioned - right?
