### ISSUE TITLE
Interprocess: add integration tests to example apps

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1380]
For iOS we should do our interprocess testing in an example app.

Should be run from build.sh/verify

**Comment by segiddins** [comment]
@tgoyne has now written interprocess tests, can this be closed?

**Comment by jpsim** [comment]
At one point, we didn't think it'd be possible to build proper interprocess tests within our unit tests, but @tgoyne proved that wrong by building awesome interprocess unit tests, so this can be closed.
