### ISSUE TITLE
Reading from the realm is not supported in migration block?

### ISSUE THREAD

**Issue by michaelcameron** [realm/realm-cocoa#1384]
I'm trying to convert an object in a migration block where the old version has a string property that will now become a relation to another RLMObject. I thought I could just do a realm call in the migration block but that seems to block on a mutex and hang (kind of makes sense).

Old Object
`@property NSString *template;`

New Object:
`@property AttractionTemplate *attractionTemplate;`

Migration block
```objective-c
[migration enumerateObjects:UserDestination.className
                      block:^(RLMObject *oldObject, RLMObject *newObject) {
                          newObject[@"attractionTemplate"] = [[AttractionTemplate objectsWhere:@"classPrefix = %@", oldObject[@"template"]] firstObject];
                      }];
```

Is there any way to look up an object when adding a new relation in a migration block?

Realm 0.89.2, XCode 6.1.1, OSX 10.10.1

**Comment by alazier** [comment]
When you execute the code ```objc
[[AttractionTemplate objectsWhere:@"classPrefix = %@", oldObject[@"template"]] firstObject];
```
you are trying to create a new instance of the default Realm which is deadlocking. Querying isn't supported yet within migrations so there isn't a sanctioned way to do this property. To get around this you can either enumerate all AttractionTemplate objects first and create a query-able structure (eg a dictionary keyed on classPrefix), or you could use private apis to access the internal Realm used during migration and query that.

I created an issue #1385 to add proper support for queries in migrations.

**Comment by michaelcameron** [comment]
Thanks, I had tried to get the objects I need before the migration block but then it complained about an unmigrated realm. Accessing the private realm reference on the migration worked fine, thanks. Looking forward for a properly supported approach with issue #1385.
