### ISSUE TITLE
Space Browser designs

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1387]
Here are the browser designs https://www.dropbox.com/sh/l4oby8qv58aom6w/AABNKpT_AqopP-1QoQgb9bKda?dl=0

The main problem comes from accessing linked objects. With this design, when you click a link it will create a new table to the right of the link you clicked. This will allow data to be traversed infinitely.

We need to see what this feels like, with general json data samples like an actual request from the foursquare api, or anything more complex.

The prototype and experience are the most important at this stage vs being fully integrated with Realm

**Comment by alazier** [comment]
@GreatApe 's WIP is now here: https://github.com/realm/realm-cocoa/tree/gk-new-browser

**Comment by timanglade** [comment]
See also #1828.

**Comment by TimOliver** [comment]
This issue was moved to realm/realm-browser#9
