### ISSUE TITLE
RLMAccessor.h:20:9: 'RLMObjectStore.hpp' file not found - podspec issue

### ISSUE THREAD

**Issue by ldiqual** [realm/realm-cocoa#1388]
Related issue: https://github.com/realm/realm-cocoa/issues/1280
Related PR: https://github.com/realm/realm-cocoa/pull/1358

I am now getting this error when installing Realm 0.90.0 via cocoapods 0.36.0.beta.1

```
RLMAccessor.h:20:9: 'RLMObjectStore.hpp' file not found
```

![image](https://cloud.githubusercontent.com/assets/941453/5850872/f050517a-a1b1-11e4-9bf9-606d720950f8.png)

### Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

pod 'Realm', '0.90.0'
```

**Comment by segiddins** [comment]
RLMAccessor.h should be marked as a private header, right @mrackwitz ?

**Comment by mrackwitz** [comment]
Yes, `RLMAccessor.h` should be private. I will update the podspec, accordingly.

**Comment by hartbit** [comment]
Same problem here.
