### ISSUE TITLE
"RLMObject" Model auto create?

### ISSUE THREAD

**Issue by kingmax123** [realm/realm-cocoa#1390]
Realm 0.9.0, Cocoa

When i create my model, and see .realm file with Real Browser, i see RLMObject Model in my database. Why?

In Realm 0.89, RLMObject does not auto create.

![screen shot 2015-01-22 at 5 54 30 pm](https://cloud.githubusercontent.com/assets/9254220/5854446/5f84cef0-a260-11e4-9fe4-d1c6aff5f71b.png)

**Comment by segiddins** [comment]
This is closed by https://github.com/realm/realm-cocoa/pull/1391.
