### ISSUE TITLE
Update release process to zip repo

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1404]
Due to difficulties in shipping prebuilt fat dynamic binaries for iOS (see #1163), it would be much simpler to recommend that users drag in `Realm.xcodeproj` as a subproject (or use Carthage/CocoaPods if they don't like that). It would also greatly simplify packaging the release zip since we wouldn't need to script a number of mutating steps.

Subtasks for this issue:

- [ ] remove `ios-dynamic` from `build.sh`
- [ ] update `package-release` in `build.sh` to clean the repo and zip it, including `ios/Realm.framework`, `osx/Realm.framework`, `browser/Realm Browser.app`
- [ ] update realm.io installation instructions
- [ ] update Jenkins to reflect these changes

**Comment by alazier** [comment]
This has been superseded by the new swift apis.
