### ISSUE TITLE
Passing a realm-backed RLMObject to createOrUpdate should throw an exception

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1409]
Otherwise, people try to do this:

```swift
class StringInt: RLMObject {
    dynamic var string = ""
    dynamic var int = 0

    override class func primaryKey() -> String! {
        return "string"
    }
}

let realm = RLMRealm.defaultRealm()
realm.beginTransaction()
let object = StringInt.createInRealm(realm, withObject: ["0", 0])
object.int = 1 // This already updates the object
StringInt.createOrUpdateInRealm(realm, withObject: object) // This should throw an exception
realm.commitTransaction()
```

Thoughts @tgoyne @alazier ?

**Comment by segiddins** [comment]
@jpsim in your mind, would `createInRealm` still allow passing in an `RLMObject`?

**Comment by jpsim** [comment]
Yes, `createOrUpdate:`, `createInRealm:` et al. should continue to support passing in standalone `RLMObject`s as well as `RLMObject`s backed by a different realm (i.e. copying `RLMObject`s between realms).

**Comment by alazier** [comment]
This does not work. Users need to be able to pass persisted objects to this method. This is currently how we recommend users copy objects between Realms.

I don't see any reason why the code you have posted is not valid and should throw.

**Comment by jpsim** [comment]
See #1322 for an example of how this bit a user. I agree that we should continue to allow users to copy RLMObject's between realms, but trying to `createOrUpdate` with an `RLMObject` backed by the same realm is never the appropriate approach.
