### ISSUE TITLE
RealmDescription, a thread-safe RLMRealm factory

### ISSUE THREAD

**Issue by drewcrawford** [realm/realm-cocoa#1410]
# Problem

Let's say that I have an app, and let's further say that on startup this app loads some data from the network and puts it in Realm.

Most probably, there is a lot of code at various layers inside the app (networking code, UI code) that makes calls to `RLMRealm.defaultRealm()`, either to insert or display data.

Now let's say I want to write a unit test, let's say for some particular class.  Because of the peculiarities of the iOS unit test architecture, my unit test will run simultaneously with the main application.  Since the main application inserts data into the default realm on each launch, and I want to test something specific, it follows that I need to create a second Realm with a disjoint object graph for my test to use as a scratch area.

So I write some code like

```swift
class TestSuite : XCTestCase {
    func testSomething() {
        let myTestRealm = RLMRealm.inMemoryRealm(identifier: "NameOfMyTest")
        let somethingToBeTested = SomethingToBeTested(realm: myTestRealm)
        let result = somethingToBeTested.doSomething()
        XCTAssert(result.reasonable == true, "Result wasn't reasonable \(result)")
    }
```

It's important to see here, *this is very general*.  Pretty much *any* test in an iOS application that tests something that ends up talking to Realm, uses approximately this pattern.

Now this works, *if `SomethingToBeTested` is single-threaded*.  But in general, it could be multithreaded: for example, the class may want to process some Realm data across e.g. 4 cores.

In that case, this architecture is insufficient, because `RLMRealm` is not threadsafe.  In fact what we need to do is to pass our `identifier` into the `SomethingToBeTestested` class, so that it can generate `RLMRealm`s arbitrarily.

But presumably the `SomethingToBeTested` class, when not being tested, operates as part of the application on the default realm.  And the default realm has no identifier.  Further, we could have another unit test that operates on a particular non-default **on-disk** realm (and those have, not an identifier, but a *path*).  So passing the `identifier` into the `SomethingToBeTested` class is insufficient, in general.

# Solution

What we need is some way to package up the *information that is needed to create a Realm*.  I call this a `RealmDescription`.  So we can do

```swift
let description = RealmDescription(realmSpecifier: .InMemory(identifier: "myTest"))
```

or

```swift
let description = RealmDescription(realmSpecifier: .OnDisk(path: "myPath"))
```

or

```swift
let description = RealmDescription(realmSpecifier: .Default)
```

And then we can create a Realm lazily and on-the-fly from our description:

```swift
let realm = description.getRealm()
```

The important bit here is that the `RealmDescription` is threadsafe and it can be used on demand to generate whatever realms on whatever threads are required.

# Implementation

A Swift implementation is provided [here](https://gist.github.com/drewcrawford/ebd7045bff7db6e4571e).  However, I think you're still developing in ObjC in part because you're building a static library.  So this would need to be ported before it can be merged.

My implementation also packs a reference to the `RLMRealm` in the memory case.  This is because RLMRealm.h documents:

> Because in-memory Realms are not persisted, you must be sure to hold on to a reference to the `RLMRealm` object returned from this for as long as you want the data to last.

Since I think it the sensible semantics are for a `RealmDescription` to be the *complete* information required to generate a particular realm, I pack a strong reference to the Realm inside the description (this isn't accessed any further, so there aren't threading issues, once it's created).  By this mechanism the Realm is guaranteed to last at least as long as its description, or conversely, a Realm will not be cleaned up when there are descriptions of it that are still live.

**Comment by alazier** [comment]
We've been discussing this quite a bit, and the consensus among the Realm devs is that the simplest way to do what you are asking using our current apis is to create a block which vendors a Realm object configured as needed. You can then pass this block around to multiple threads and use it to create Realm objects configured in the same way.

This may or may not cover all of your use cases and we are open to exploring other alternatives in the future.
