### ISSUE TITLE
sortedResultsUsingProperty with non stored properties

### ISSUE THREAD

**Issue by malcommac** [realm/realm-cocoa#1411]
Is there a way to sort RLMResults instances with computed properties? (not stored on realm db).
I've tried with my "distance" @property evaluated at runtime but I get this:
" *** Terminating app due to uncaught exception 'Invalid sort column', reason: 'Column named '(null)' not found.'"

Is there a way to get it? Convert RLMResults in a normal NSArray?

**Comment by segiddins** [comment]
Hi @malcommac, it is currently not possible to sort an `RLMResults` by anything but a realm-persisted property. We have a ticket at https://github.com/realm/realm-cocoa/issues/1265 that is tracking adding a way to do such sorting.
