### ISSUE TITLE
Support copying a realm into an in-memory realm

### ISSUE THREAD

**Issue by BrentleyJones** [realm/realm-cocoa#1418]
I want to be able to copy a realm, ala `- (BOOL)writeCopyToPath:(NSString *)path error:(NSError **)error`, but to an in-memory realm instead of to a disk. Maybe even open an in-memory realm from a disk path.

**Comment by bmunkholm** [comment]
Could you detail your usecase a bit?
Specifically would you be updating the in-memory version or just using it for read-only? In that case it won't actually be faster than the file-based.

**Comment by BrentleyJones** [comment]
I would be updating it in memory. My use case is I have a preloaded database that I either copy to a new disk location for a new on disk database, or I can do the same thing, but in memory. The point is being able to preload in memory or on disk databases.

**Comment by segiddins** [comment]
Since Realm uses memory-mapping, there's no performance difference on reads between an in-memory Realm and a disk-backed Realm. Copying the file to a new location on disk should do just fine for using a pre-loaded realm file.

**Comment by BrentleyJones** [comment]
But then if I modify it, I want to be able to throw it away, like an in-memory realm. I would have written it to disk, which is not what I would necessarily want.

**Comment by tgoyne** [comment]
In-memory Realms only really have two differences from normal Realms: we skip calling msync (and skip a small amount of work related to ensuring that we're msyncing the correc things), and automatically delete the file when it's closed. Not calling msync means that typically no data is ever written to disk, but the backing file does still need to be writable and there's no guarantee that the kernel won't decide to write modified pages, so they do need a copy of the input file.

I suppose we could have an in-memory Realm `memcpy` the initial data from an input buffer to the mmaped file, but it's not something the code is set up to support at all at the moment, and my expectation would be that there's a fairly small window where it's a meaningful speedup before having to have two copies of the file in memory starts to be an issue.
