### ISSUE TITLE
Support object equality in ANY queries

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1424]
e.g. `[A objectsWhere:@"ANY bArray = %@", instanceOfB]`. AFAICT core supports this, we just don't cover it in `RLMQueryUtil`.

**Comment by vuk-nikolic** [comment]
+1 :)

**Comment by bdash** [comment]
[`-[QueryTests testQueryWithObjects]`](https://github.com/realm/realm-cocoa/blob/3e070fe215445dd5acb99bba102d9dd0a016a637/Realm/Tests/QueryTests.m#L1353-L1357) appears to have test coverage showing this is already supported?

**Comment by jpsim** [comment]
Indeed! Thanks for pointing that out.
