### ISSUE TITLE
Missing comma in Cocoa migration docs

### ISSUE THREAD

**Issue by mmertsock** [realm/realm-cocoa#1433]
Thanks for the great documentation! In the *Performing a Migration* section of the documentation, the two Swift code samples missing a comma:

```Swift
RLMRealm.setSchemaVersion(1, forRealmAtPath: RLMRealm.defaultRealmPath() 
                         withMigrationBlock: { migration, oldSchemaVersion in ...
```

There should be a comma after `RLMRealm.defaultRealmPath()`.

**Comment by yoshyosh** [comment]
Thanks for pointing this out, just made a fix!
