### ISSUE TITLE
Schema without Objects in Tests

### ISSUE THREAD

**Issue by vittoriom** [realm/realm-cocoa#1436]
Hi,
first of all thanks for your great job!

I'm having an issue similar to #690 except for the thing that I'm not using CocoaPods.
My test target has the main app as a dependency, and I setup a stub Realm database just with the purpose of running tests against it.

The issue I'm having, even though I'm obviously initializing the realm with 

```
let realm = RLMRealm(path: path_to_the_test_realm)
```

and querying it with

```
let elements = MyModelObject.objectsInRealm(realm, withPredicate: aPredicate)
```
where <code>realm</code> is the instance created above,

I'm getting 
<code>Assertions: failed: caught "RLMException", "Object type 'MyModelObject' not persisted in Realm"</code>

No need to paste the full stack trace since I suppose we already know what's going on here. That is, I need to add my model objects to the test target (even though this is discouraged from a number of sources (example: https://github.com/Quick/Quick/issues/91)).
The funny thing is that I tried, and then I got an even better error in the tests file:
<code>'MyModelObject' is not identical to 'MyModelObject'</code>
at line:
```
result = manager.doFoo()
```

The function should return an instance of <code>MyModelObject</code> and that should be assigned to a variable of the same type. But it looks like the type coming from the function is actually different (maybe this is one of the drawbacks of adding classes to two targets).

My question is eventually:

Is there a way to have a proper <code>RLMSchema</code> working without having to include the model objects in more than the needed target?

Thanks!

**Comment by vittoriom** [comment]
A small update: 
I managed to get the build working again by prefixing the ambiguous <code>MyModelObject</code> declarations in the tests with the main target module name, but I don't know if the tests would be working because when I run them, my whole Xcode crashes :-1: so the question is still valid :smile:

**Comment by segiddins** [comment]
You are correct in the assumption that the issue comes from having the class added to both targets. Your best bet would be to simply import your application's implicitly-defined module into your test target.

**Comment by vittoriom** [comment]
Hi Samuel and thanks for the reply

Unfortunately my application's implicitly-defined module is already
imported into my test file, but this doesn't seem to help Realm in building
the schema. It's also worth noting that the test realm already includes
some data but still, the RLMSchema is empty.

2015-02-02 21:29 GMT+01:00 Samuel E. Giddins <notifications@github.com>:

**Comment by segiddins** [comment]
Would it be possible for you to share an example project that reproduces the issue? That would make debugging much easier. Thanks!

**Comment by vittoriom** [comment]
I just prepared a new project trying to reproduce the issue and it looks like importing Realm and the application's implicitly-defined module in the test file, I can read and write in the database without issues.
At this point I guess I will have to make incremental steps to get to my real configuration and see what's breaking stuff.
Thanks for your support :)

**Comment by segiddins** [comment]
@vittoriom were you able to reproduce the issue in your test project?

**Comment by vittoriom** [comment]
Unfortunately I had no luck since I could not spend too much time on trying to reproduce the environment. I hope I'll have some spare time before the end of one of the sprints to dedicate some time to this. 
I think you can close the issue since I didn't manage to repro on a clean project. I'll create then a more specific one when I have more results.

**Comment by segiddins** [comment]
@vittoriom thanks so much!

**Comment by vittoriom** [comment]
Just wanted to update you about the status of this issue. 
We fixed it by **unchecking the test target for the Realm.framework**
So, all is good with testing persistence for our project :)
thanks for your support!

**Comment by vittoriom** [comment]
Just got this again since some time :( Running tests from the Jenkins machine crashes because of missing model objects. On developers' machines it doesn't happen

**Comment by jpsim** [comment]
@vittoriom it's odd that you can trigger this in Jenkins but not locally. Please let us know if you manage to find a way to reproduce it reliably and we'll investigate.
