### ISSUE TITLE
Truncate description for NSData properties

### ISSUE THREAD

**Issue by MattKiazyk** [realm/realm-cocoa#1439]
If I have an NSData property on an object, when I log the object it belongs to, it currently spits it all out.

Requesting that a truncated version of it be used instead ex: `lengh:4232 bytes`

Thanks

-Matt

**Comment by anlaital** [comment]
:+1:

**Comment by alazier** [comment]
I think we want this to behave the same as RLMArray - print out the data only up to a certain size and truncate NSData which is any larger. I would imagine something like 100 bytes would be a good tradeoff. I also think we should print out the total size in the description as you have suggested.
