### ISSUE TITLE
RLMResults contains doubled objects

### ISSUE THREAD

**Issue by kronik** [realm/realm-cocoa#1443]
Hi! 

I faced with an issue when after I executed a query I see all objects in RLMResults (objectsWithPredicate) twice. But in desktop realm browser actual data exists only once i.e.:

in browser records:

1. aaa
2. bbb
3. ccc

in RLMResults:

1. aaa
2. aaa
3. bbb
4. bbb
5. ccc
6. ccc

Any ideas why?

**Comment by bmunkholm** [comment]
Hi,
That sounds odd. Can you in any way share some code that reproduce this? I.e. the data file itself and the code you use to query? You can send privately at help@realm.io

**Comment by kronik** [comment]
Sent

**Comment by kronik** [comment]
Sent

**Comment by segiddins** [comment]
This was just fixed in the core database, and the fix will be in the next release!

**Comment by kronik** [comment]
Thanks!

**Comment by kronik** [comment]
When or in which version of Realm it will be released?

**Comment by kronik** [comment]
Fixed
