### ISSUE TITLE
Duplicate interface definition for class RLMObject with 0.90.4

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#1444]
Hi guys,

I just wanted to update to 0.90.4 but unfortunately Realm is not compiling anymore since apparently duplicated definitions for RLMObject are present. Am I just being totally stupid or is there a problem with the current CocoaPods release?

**Comment by segiddins** [comment]
@tspecht can you please share the error that you're seeing, as well as the Podfile you're using?

**Comment by Kirow** [comment]
Sometimes get this error when AppCode adds ```#import``` to files I don't need (don't remember filename, but it is always the same). Just check all your imports.

**Comment by tspecht** [comment]
I upgraded to 0.90.5 and this now seems fixed without changing any code. Unfortunately there are still major problems regarding migrations as described in https://github.com/realm/realm-cocoa/issues/1474

**Comment by alazier** [comment]
@tspecht what version are you upgrading from? In 0.90.0 there was a change made that now requires you to call `setSchemaVersion` for each Realm path individually. Previously you only needed to call this method once for your entire app rather than for each Realm used.

**Comment by tspecht** [comment]
I upgraded from 0.89.2. I saw the changes in the migrations and changed my code accordingly, otherwise my app wouldn't have been able to compile ;) I deleted the app, was able to start it once but with the next start, without changing anything Realm related it was broken again causing me to go back to 0.89.2 again unfortunately.

**Comment by segiddins** [comment]
So, @tspecht, are you saying that the original error (`Duplicate interface definition for class RLMObject`) has been fixed? In that case, it'd be great to close this issue and continue discussion on the migration issue in #1474. Thanks!
