### ISSUE TITLE
Carthage builds both "iOS" and "iOS 8" targets to same output file

### ISSUE THREAD

**Issue by a2** [realm/realm-cocoa#1447]
I noticed that when using Carthage, it builds both the "iOS" and "iOS 8" targets to the same output `.framework` file in _Carthage/Builds/iOS_.

**Comment by segiddins** [comment]
Wouldn't this be a bug in Carthage, not making sure that each scheme's artifact is preserved?

**Comment by a2** [comment]
Why are there both a 7-targeted and an 8-targeted dynamic libraries to begin with?

**Comment by mrackwitz** [comment]
The `iOS` target builds a static framework for pre iOS 8, while the `iOS 8` target builds a dynamic framework.

**Comment by jpsim** [comment]
I spoke to the Carthage people about this. Carthage skips static frameworks, so this "works as expected". I think we're starting to have an interesting conversation about this in the Carthage issue you linked, though. If you think Realm should do anything differently, please reopen this issue.
