### ISSUE TITLE
Make List and Results Sliceable

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#1448]

**Comment by alazier** [comment]
This requires core support for querying on results/listViews with offset/limit

**Comment by bmunkholm** [comment]
That was supported years ago :-) Check query.hpp find_all() and aggregates support it already.

**Comment by tgoyne** [comment]
The problem is further querying the sliced results. Filtering a Query on a TableView doesn't retain the TableView, so we can't use anything that requires that.

**Comment by bmunkholm** [comment]
So we need a ticket in core that describes the needed updates.

**Comment by timanglade** [comment]
Closing as a duplicate of #1580
