### ISSUE TITLE
handling inconsistent data type

### ISSUE THREAD

**Issue by yasirmturk** [realm/realm-cocoa#1460]
I have a strange situation where the values from json vary from nil, int & string .. Currently, i am handling nil by passing default value a empty string ... but it does not handles converting int json to string attribute.. while other libraries do that seemlessly like ObjectiveRecord

**Comment by yoshyosh** [comment]
There are a few like [Mantle](https://github.com/Mantle/Mantle) and [Realm-JSON](https://github.com/matthewcheok/Realm-JSON)
The latter has been heavily used by the community to handle these kinds of situations. Building your own workarounds works as well, those are documented [here](http://stackoverflow.com/questions/26458585/how-to-handle-null-value-in-realm-io)

**Comment by yoshyosh** [comment]
Hi @yasirmturk just checking in, did these solutions work for you?

**Comment by yasirmturk** [comment]
[Realm-JSON](https://github.com/matthewcheok/Realm-JSON) is cool for mapping keys to attributes.. i have solved my issue by using this 
`+ (NSDictionary *)defaultPropertyValues {
    return @{
             @"Id": @"",
             };
}`

**Comment by yoshyosh** [comment]
Ah great to hear and see you using `defaultPropertyValues` to handle this!

**Comment by yasirmturk** [comment]
Yeah [Realm-JSON](https://github.com/matthewcheok/Realm-JSON) actually fails to work if there is no primary key

**Comment by yoshyosh** [comment]
Yea, the method `createOrUpdateInRealm:` requires a primary key to be used

**Comment by yasirmturk** [comment]
that is why there is a need to be able to specify columns, which could be used as insert-update condition without specifying primary key #1473 , because in a real world primary key is not there in many cases ..may be something like:
`+ (NSArray *)uniqueKeys { return @[@"countryCode", @"postalCode"] }` for a Geo Area

**Comment by yoshyosh** [comment]
Similar to this request https://github.com/realm/realm-cocoa/issues/1192
