### ISSUE TITLE
Extra argument 'forRealmAtPath' in call

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1463]
I have Realm 0.90.5 installed with cocoapods. Here is my code:

    RLMRealm.setSchemaVersion(17, forRealmAtPath: RLMRealm.defaultRealmPath(),
			withMigrationBlock: { migration, oldSchemaVersion in
				if oldSchemaVersion < 1 { }
		})

In xcode I am getting the following error: ```Extra argument 'forRealmAtPath' in call```.

What could be my issue?

**Comment by segiddins** [comment]
@webmagnets is CocoaPods integrating that target using frameworks or static libraries? Are you importing Realm in your bridging header, or via an `import Realm` statement in Swift?

**Comment by webmagnets** [comment]
1) I'm not sure. I am attaching a screenshot to see if that helps. Thanks.
![realm-problem](https://cloud.githubusercontent.com/assets/1189875/6087313/810e3ae2-ae0f-11e4-81ab-26c0ed7a9ebf.png)

2) I am using ```import Realm```.

**Comment by segiddins** [comment]
@webmagnets that line of code compiles fine for me when I paste it into a test project. Is there any more context you can share?

**Comment by webmagnets** [comment]
Do you have a bitbucket account? I can add you as a viewer.



-
Nathan Cain
501-463-6336www.jw.org

------------------

[+] Add me to your address book

**Comment by segiddins** [comment]
@webmagnets I can reproduce the issue on your project, however I have no idea why the compiler's Swift-generated interface for `RLMRealm` is different from the contents of `RLMRealm.h`

**Comment by webmagnets** [comment]
Do you think it has to do with me changing from manual installation to cocoapods?



-
Nathan Cain
501-463-6336www.jw.org

------------------

[+] Add me to your address book

**Comment by segiddins** [comment]
@webmagnets you need to delete the existing `Realm.framework` from your project directory, add `#import <Realm/Realm.h>` to your bridging header, and remove the `import Realm` statements from your swift code.

**Comment by segiddins** [comment]
@webmagnets feel free to close the issue if that fixed things for you!

**Comment by webmagnets** [comment]
I had to completely remove cocoapods and realm and then reinstall realm. Thanks for your help.
