### ISSUE TITLE
Realm in different app versions

### ISSUE THREAD

**Issue by Bruno-Furtado** [realm/realm-cocoa#1464]
Hello,

My application has a silenty login at the application entry.
This login information is saved in the realm.

Everytime I create a new version of the application some users complain that they can no longer perform this login and the app closes.

I tried to find a solution looking for in the log but it was not possible.

It is possible that this error is occurring in the realm due to version change? 
(I'm not changing the database model).

**Comment by yoshyosh** [comment]
Hi @Bruno-Furtado can you share the project with us privately at help@realm.io? You can also post code here that shows us how you are storing and retrieving this login information.

As long as you aren't changing the database model, realm won't require a migration, so your file should still be on the device like usual.

**Comment by yoshyosh** [comment]
Hi @Bruno-Furtado just checking in, were you able to resolve this issue?

**Comment by Bruno-Furtado** [comment]
@yoshyosh,
It's hard to explain because the situation itself involves the application logic.

In short some users are having problems. 
They note that when entering the application it's a hung time and closes.

Have you ever seen a situation like this?
This same failure occurs on iOS and Android with some users.

**Comment by yoshyosh** [comment]
I haven't, sorry to hear that it is affecting users as well. Perhaps we can setup a screen share to go over the code? Is there any way you can get some sample code for us to look at?

**Comment by yoshyosh** [comment]
Hi Bruno just checking in. Any updates on this?

**Comment by Bruno-Furtado** [comment]
@yoshyosh,

I managed to retrieve log iTunes Connect and the failure doesn't involve the Realm.
Sorry and thanks for the help.

**Comment by yoshyosh** [comment]
Got it, good luck with finding the fix :(!
