### ISSUE TITLE
Add a way to ignore adding an empty table to schema

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1466]
A few people have been asking for this, our default answer has been that it doesn't have any performance impact. I'm thinking its a aesthetic thing while looking at your data.

**Comment by alazier** [comment]
We could just hide objects with no columns in the browser.

**Comment by yoshyosh** [comment]
Might not work for situations where people are testing the browser but haven't added any data yet. I could see that situation being odd

**Comment by alazier** [comment]
I think you misunderstood - objects with no objects but with columns would show up. Only object without any properties would be hidden.

**Comment by yoshyosh** [comment]
:+1:
