### ISSUE TITLE
Ability to parse a single hardcoded cvs-file into multiple tables with loose relationships.

### ISSUE THREAD

**Issue by MKGitHub** [realm/realm-cocoa#1469]
It would be nice if the editor could do this.
For instance, if I have a huge cvs-file with the following duplicate data and hardcoded relationships  – the editor can separate this into multiple tables with loose relationships.

```
col1 | col2 | col3
------------------
0, Hello, World
1, Hello, World
2, Foo, Bar
3, Foo, Bar
```

will become 3 tables with

```
Table 1
col1 | col2 | col3
------------------
0, 0, 0
1, 0, 0
2, 1, 1
3, 1, 1

Table 2 (relationship to Table 1 col2)
col1 | col2
------------------
0, Hello
1, Foo

Table 3 (relationship to Table 1 col3)
col1 | col2
------------------
0, World
1, Bar
```

**Comment by segiddins** [comment]
@MKGitHub we agree that having some sort of editor import functionality would be cool, we just haven't gotten to it yet. As to your particular request for that sort of hypernormalization -- it would be possible to do that with a relatively small amount of code, but I'm not sure it'd be necessary with Realm -- Realm stores relationships as links, so there's nothing like the cost of a SQL `JOIN` to traverse relationships.

Hope that helps!
