### ISSUE TITLE
Unable to declare RLMArray in Swift

### ISSUE THREAD

**Issue by LoganWright** [realm/realm-cocoa#1471]
When I add the following code:

```Swift
class Test : RLMObject {
    dynamic var array = RLMArray(objectClassName: Realm.className())
}
class Realm : RLMObject {   
}
```

And then test like so:

```Swift
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        let test = Test()
        return true
    }
```

The program crashes on an NSException:

>RLMArray properties require a protocol defining the contained type - example: RLMArray<Person>

I feel like this is exactly the way it's setup in the Docs and I'm not sure what is happening.  There's no information related to the error message except for #750 which doesn't address my issue.

<b> Update </b>

It turns out that this issue is related to some underlying mapping that I've built in for translating JSON into realm object models.  It appears that the problem is something in the underlying order of Swift initialization resulting in the introspection of Realm happening before the initialization of the property.  This means that the `objectClassName` of the array property is always `nil` when it needs to be used.  To temporarily resolve the issue, I am changing the following code:

#### `RLArray.mm`
```ObjC
static void RLMValidateMatchingObjectType(RLMArray *array, RLMObject *object) {
    if (![array->_objectClassName isEqualToString:object.objectSchema.className]) {
        @throw [NSException exceptionWithName:@"RLMException"
                                       reason:@"Object type does not match RLMArray"
                                     userInfo:nil];
    }
}
```

To

```ObjC
static void RLMValidateMatchingObjectType(RLMArray *array, RLMObject *object) {
    if (array->_objectClassName && ![array->_objectClassName isEqualToString:object.objectSchema.className]) {
        @throw [NSException exceptionWithName:@"RLMException"
                                       reason:@"Object type does not match RLMArray"
                                     userInfo:nil];
    }
}
```

#### `RLProperty.mm`

```ObjC
            else if (strcmp(code, "@\"RLMArray\"") == 0) {
                @throw [NSException exceptionWithName:@"RLMException"
                                               reason:@"RLMArray properties require a protocol defining the contained type - example: RLMArray<Person>"
                                             userInfo:nil];
            }
```

To:

```ObjC
            else if (strcmp(code, "@\"RLMArray\"") == 0) {
                _type = RLMPropertyTypeArray;
            }
```

I do NOT recommend this to go into the codebase as it takes away the built in safety mechanisms of Realm and leaves more room for potential errors in code.  This is a temporary workaround, I only wanted to share my findings in the hope it might lead to a better solution to the problem.

I read somewhere that a Swift api is in progress.  I assume you're already doing this, but it would be nice to have a declaration like this:

```Swift
class RLMArraySwift<T: RLMObject> : RLMArray {
    class func itemType() -> String {
        return T.className()
    }
}
```

I was going to add this, but unfortunately, this doesn't support dynamic property declarations because of generics, so further thinking is required.

**Comment by LoganWright** [comment]
Note that this happens even when I copy your example exactly from the docs:

```Swift
// Dog model
class Dog: RLMObject {
    dynamic var name = ""
    dynamic var owner: Person? // Can be optional
}

// Person model
class Person: RLMObject {
    dynamic var name = ""
    dynamic var birthdate = NSDate(timeIntervalSince1970: 1)
    dynamic var dogs = RLMArray(objectClassName: Dog.className())
}
```

And attempt to instantiate:

```Swift
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        let person = Person()
        // Crashes before it ever gets here.
        return true
    }
```

**Comment by segiddins** [comment]
@LoganWright I cannot reproduce this with Realm v0.90.5. Can you share an example project that reproduces the issue? Thanks!

**Comment by LoganWright** [comment]
@segiddins - Thanks for getting back to me, I'm enjoying the library so far!

 I posted my current version of the project to a repo <a href="https://github.com/LoganWright/ShowTracker">here</a>.

If you pull it, I marked my current changes to the Realm library with the tag `//: LoganWright` so you can do a project search to see what I did.

I believe the underlying problem is in `JSONMapping`, and the way it loads objects from JSON.  This causes the `property->_objectClassName` to be nil during introspection and it cascades into more problems throughout the process because it's never properly set.

There shouldn't be a problem from what I can see, and I'm stuck trying to get the two to play nicely.  The show tracker app is really a means to an end, I'm more interested in building a layer that meshes my mapping, w/ Alamofire and Realm to make easy Rest consumption and persistence.  The show tracker is just a means to this.  

If you have any suggestions I can make to my class to help it play nicely, I'd love to get some of these issues figured out, or build a good workaround.

### Modeling:
All of my realm modeling is in `TVRageNetworking.swift`.  (Some of it looks strange, it's a very old api, so it has a lot of edge cases)

### Mapping:
You can see my mapping process in `JSONMapping.swift`.  My first root class is `LGCodable` which subclasses `RLMObject`.

### Reproduce:
If you remove my changes here:

```ObjC
            else if (strcmp(code, "@\"RLMArray\"") == 0) {
                
                //: LoganWright
                _type = RLMPropertyTypeArray;
                NSString *className = classNameTable[self.name];
                if (className) {
                    _objectClassName = className;
                } else {
                    @throw [NSException exceptionWithName:@"RLMException"
                                                   reason:@"RLMArray properties require a protocol defining the contained type - example: RLMArray<Person>"
                                                 userInfo:nil];
                }
            }
```

If you remove these changes, you'll see the base problem which is that the objectClassName is still nil at this point.

**Comment by LoganWright** [comment]
Update.  I was able to git the issue somewhat resolved by switching to the `al-swift` branch and building the `RealmSwift.framework`.  It created a couple of other minor problems, but all of these had easy workarounds.  It seams that the `RealmSwift.List<Class>` syntax somehow fixes something.

**Comment by segiddins** [comment]
@LoganWright what you're doing is unsupported -- by using the `@objc(ClassName)` annotation on your `RLMObject` Swift subclasses, you're making it impossible for Realm to know that these are Swift classes, and thus they need to support the 'Swift way' of declaring `RLMArrays`. (Since they only way we can tell that a class was declared in Swift is by seeing if it has a namespaced class name).

I hope this helps!

**Comment by LoganWright** [comment]
@segiddins - Ahhhh, thank you! I'll try that and if it works, I'll close the issue.  Thanks for helping me figure it out!
