### ISSUE TITLE
Realm sometimes crashes when first accessing it

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#1472]
We are currently doing internal piloting on the version of our app that uses Realm with encryption enabled, and I'm seeing a few of these crashes. These are taken from  Crashlytics and the app is built in release mode. The [RLMObject allObjects] is the first Realm call that is invoked in the app when this crash happens.

These crashes seem to be fairly frequent. Realm version is 0.90.5.

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE at 0x000000010487810c

Thread : Crashed: com.apple.main-thread
0  *                           0x0000000100335d10 tightdb::Array::init_from_mem(tightdb::MemRef) + 336
1  *                           0x00000001003aecd4 tightdb::SharedGroup::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, tightdb::SharedGroup::DurabilityLevel, bool, char const*) + 2504
2  *                           0x00000001003aecd4 tightdb::SharedGroup::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, tightdb::SharedGroup::DurabilityLevel, bool, char const*) + 2504
3  *                           0x00000001003b0034 tightdb::SharedGroup::open(tightdb::Replication&, tightdb::SharedGroup::DurabilityLevel, char const*) + 7464
4  *                           0x00000001002f90f4 tightdb::SharedGroup::SharedGroup(tightdb::Replication&, tightdb::SharedGroup::DurabilityLevel, char const*) (group_shared.hpp:610)
5  *                           0x00000001002f3d5c -[RLMRealm initWithPath:key:readOnly:inMemory:dynamic:error:] (RLMRealm.mm:303)
6  *                           0x00000001002f4ce0 +[RLMRealm realmWithPath:key:readOnly:inMemory:dynamic:schema:error:] (RLMRealm.mm:483)
7  *                           0x00000001002f4910 +[RLMRealm realmWithPath:readOnly:error:] (RLMRealm.mm:408)
8  *                           0x00000001002f4870 +[RLMRealm defaultRealm] (RLMRealm.mm:396)
9  *                           0x00000001002cd390 +[RLMObject allObjects] (RLMObject.mm:78)
```

**Comment by yoshyosh** [comment]
Hi @anlaital could you provide us with more code that leads up to this? If you could send a small reproducible project or the actual project privately to help@realm.io it will help us look into this. Thanks for your patience!

**Comment by yoshyosh** [comment]
A few questions:
Are you setting encryption key?
Are you using version 0.90.5?  There was a bug in previous versions for 64 bit iOS

**Comment by anlaital** [comment]
I am using 0.90.5. I have not been able to reproduce this crash outside of our main project.

```
#ifdef __OPTIMIZE__
            [RLMRealm setEncryptionKey:[encryptionKey dataUsingEncoding:NSUTF8StringEncoding] forRealmsAtPath:[RLMRealm defaultRealmPath]];
#endif

// This method directly called after setting the encryption key.
+ (instancetype)metadata
{
    PersistentMetadata *metadata = [PersistentMetadata allObjects].firstObject; // This causes the crash.
    if (!metadata) {
        RLMRealm *realm = [RLMRealm defaultRealm];
        metadata = [PersistentMetadata new];
        [realm transactionWithBlock:^{
            [realm addObject:metadata];
        }];
    }
    return metadata;
}
```

That's it. There is nothing in between. This seems to be completely random and relaunching the application solves the problem.

This also happens very frequently, so most likely this is a showstopper for us. I will try to investigate this issue further today. If there is something you'd like me to do related to this, then please let me know and I'll happily oblige.

**Comment by tgoyne** [comment]
Are you using `writeCopyToPath:encryptionKey:`? That's broken on ARM64 devices in 0.90.5 and could produce that failure when opening the file.

**Comment by anlaital** [comment]
I'm not using ```writeCopyToPath:encryptionKey:```, but I am using an encrypted Realm. One possibility is to narrow this issue down to the encryption implementation, so I'll release the next internal beta without it just to see if this issue no longer happens. That way there's at least a way of knowing something more about this.

If this happens even without encryption then that also helps a lot with debugging efforts.

**Comment by anlaital** [comment]
Crashlytics reports this crash every time you forcibly close the application by swiping it up in the task switcher. This also happens under low-memory pressure when the application using Realm is closed by the system to regain some RAM.

**Comment by anlaital** [comment]
This crash happens only when encryption is enabled. This issue is also blocking our release, so I would really appreciate if you could investigate this thoroughly.

**Comment by tgoyne** [comment]
I can reproduce issues when killing an app while spamming write transactions on an encrypted realm and I'm working on fixing it.

**Comment by anlaital** [comment]
@tgoyne awesome, thanks a lot! :+1:

**Comment by anlaital** [comment]
I will be changing our internal pilot build to use an encrypted Realm now that it should be working again. I will report any and all findings here at the earliest possible time.

**Comment by archansel** [comment]
I'm still having this issue when closing app by swiping in task switcher (encryption enabled), I use 0.98.0
