### ISSUE TITLE
Insert-Update does not allows for multiple columns

### ISSUE THREAD

**Issue by yasirmturk** [realm/realm-cocoa#1473]
`+ (instancetype)createOrUpdateInRealm:(RLMRealm *)realm withObject:(id)object;` requires a primary key to be set in order to perform updates, but in actual use case there could multiple unique columns and no primary for a given entity. 
Note: Can we define a virtual attribute by combining 2 or more column values and provide it as primary key??

**Comment by alazier** [comment]
You can't currently use 2 combined columns as a primary key. At the moment you can manually combine these columns and store the combined value in a third column which is primary. Using a helper method which updates both the base and combined column simultaneously can make this easier.

**Comment by farri** [comment]
+1

**Comment by yasirmturk** [comment]
any update on this one?

**Comment by eriktelepovsky** [comment]
+1
