### ISSUE TITLE
_inWriteTransaction should be set to YES before triggering notificaions in beginWriteTransaction

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1477]
Currently this is not the case, and calling beginWriteTranaction in a notification causes an assert rather than an exception.

**Comment by segiddins** [comment]
@alazier any issue you can point to where that assertion is being hit?

**Comment by alazier** [comment]
A user hit this. Repro steps:
1. Perform a write transaction in a backround thread and wait for completion on main thread
2. Begin write transaction on main thread
3. In notification block (which is fired from beginWriteTransaction) call beginWriteTransaction
Instead of getting the 'transaction in progress' exception, we instead get an assertion. I'm happy to make the fix/write the test for this one.
