### ISSUE TITLE
sortedResultsUsingProperty cannot work when Property is primaryKey

### ISSUE THREAD

**Issue by BruceZCQ** [realm/realm-cocoa#1483]
sortedResultsUsingProperty cannot work when Property is primaryKey

**Comment by alazier** [comment]
Can you give more information/repro steps? I have tried this with both string and int primary keys and it seems to work fine at least in my tests.

**Comment by BruceZCQ** [comment]
this is my code
```
@interface IMTFriendReqRLModel : RLMObject

#pragma mark - V1.0.0

/// mymeetId
@property NSString *mymeetid;

/// reqid
@property NSString *reqid;

/// request user id
@property NSString *requserid;

/// request user name
@property NSString *requsername;

/// request time
@property NSString *reqtime;

/// request Statue
@property NSInteger reqstatus;

#pragma mark - End V1.0.0

@end

...
/// primaryKey : reqid
+ (NSString *)primaryKey
{
    return @"reqid";
}

RLMResults *ret = [[IMTFriendReqRLModel objectsWhere:@"mymeetid = %@",kMyMeetId] sortedResultsUsingProperty:@"reqid" ascending:YES];

``` 
When I was in the test found that when using reqid ret didn't sort the data
```
Printing description of ret:
RLMResults <0x184b5e10> (
	[0] IMTFriendReqRLModel {
		mymeetid = 11001;
		reqid = 110;
		requserid = 11019;
		requsername = ~\(≧▽≦)/~;
		reqtime = 1423479309;
		reqstatus = 1;
	},
	[1] IMTFriendReqRLModel {
		mymeetid = 11001;
		reqid = 20;
		requserid = 11012;
		requsername = zzzzz;
		reqtime = 1422329897;
		reqstatus = 1;
	},
	[2] IMTFriendReqRLModel {
		mymeetid = 11001;
		reqid = 86;
		requserid = 11029;
		requsername = 11029;
		reqtime = 1423230238;
		reqstatus = 1;
	},
	[3] IMTFriendReqRLModel {
		mymeetid = 11001;
		reqid = 89;
		requserid = 11027;
		requsername = xxx;
		reqtime = 1423232582;
		reqstatus = 1;
	}
)
```
when i used reqtime property work fine
```
Printing description of ret:
RLMResults <0x1693f410> (
	[0] IMTFriendReqRLModel {
		mymeetid = 11001;
		reqid = 20;
		requserid = 11012;
		requsername = zzzzz;
		reqtime = 1422329897;
		reqstatus = 1;
	},
	[1] IMTFriendReqRLModel {
		mymeetid = 11001;
		reqid = 86;
		requserid = 11029;
		requsername = 11029;
		reqtime = 1423230238;
		reqstatus = 1;
	},
	[2] IMTFriendReqRLModel {
		mymeetid = 11001;
		reqid = 89;
		requserid = 11027;
		requsername = xxx;
		reqtime = 1423232582;
		reqstatus = 1;
	},
	[3] IMTFriendReqRLModel {
		mymeetid = 11001;
		reqid = 110;
		requserid = 11019;
		requsername = ~\(≧▽≦)/~;
		reqtime = 1423479309;
		reqstatus = 1;
	}
)

```

**Comment by segiddins** [comment]
@BruceZCQ it actually looks like everything is being sorted properly, as `reqid` is an `NSString` property, and thus string comparison (rather than numeric comparison) is being used when sorting.

**Comment by BruceZCQ** [comment]
this code
```
Printing description of ret:
RLMResults <0x184b5e10> (
    [0] IMTFriendReqRLModel {
        mymeetid = 11001;
        reqid = 110;
        requserid = 11019;
        requsername = ~\(≧▽≦)/~;
        reqtime = 1423479309;
        reqstatus = 1;
    },
    [1] IMTFriendReqRLModel {
        mymeetid = 11001;
        reqid = 20;
        requserid = 11012;
        requsername = zzzzz;
        reqtime = 1422329897;
        reqstatus = 1;
    },
    [2] IMTFriendReqRLModel {
        mymeetid = 11001;
        reqid = 86;
        requserid = 11029;
        requsername = 11029;
        reqtime = 1423230238;
        reqstatus = 1;
    },
    [3] IMTFriendReqRLModel {
        mymeetid = 11001;
        reqid = 89;
        requserid = 11027;
        requsername = xxx;
        reqtime = 1423232582;
        reqstatus = 1;
    }
)
```
used reqid by sort, but the result is reqid 110, reqid 20, reqid 86, reqid 89. it was not sorted.

**Comment by segiddins** [comment]
That is sorted, since 1 comes before 2 lexicographically. 

-Samuel E. Giddins

On Feb 11, 2015, at 8:02 PM, BruceZCQ <notifications@github.com> wrote:

this code

Printing description of ret:
RLMResults <0x184b5e10> (
    [0] IMTFriendReqRLModel {
        mymeetid = 11001;
        reqid = 110;
        requserid = 11019;
        requsername = ~\(≧▽≦)/~;
        reqtime = 1423479309;
        reqstatus = 1;
    },
    [1] IMTFriendReqRLModel {
        mymeetid = 11001;
        reqid = 20;
        requserid = 11012;
        requsername = zzzzz;
        reqtime = 1422329897;
        reqstatus = 1;
    },
    [2] IMTFriendReqRLModel {
        mymeetid = 11001;
        reqid = 86;
        requserid = 11029;
        requsername = 11029;
        reqtime = 1423230238;
        reqstatus = 1;
    },
    [3] IMTFriendReqRLModel {
        mymeetid = 11001;
        reqid = 89;
        requserid = 11027;
        requsername = xxx;
        reqtime = 1423232582;
        reqstatus = 1;
    }
)
used reqid by sort, but the result is reqid 110, reqid 20, reqid 86, reqid 89. it was not sorted.

**Comment by BruceZCQ** [comment]
Got it , I am sorry,I known it that NString using dictionary order. Thanks a lot.
