### ISSUE TITLE
RLMArray -indexOfObjectWhere: queries not reliable

### ISSUE THREAD

**Issue by rciobanu-omnifone** [realm/realm-cocoa#1485]
**1. Goals:** an `RLMArray` property contains references to other `RLMObjects`. This property is mutated (objects added/removed), after which it should be possible to searching an object by ID in this array.
**2. Expected results:** if the `RLMArray` property contains at least an object corresponding to the query passed in `-indexOfObjectWhere:` then the method should return the first index of such object. Otherwise the method should return `NSNotFound`.
**3. Actual results:** `NSNotFound` is returned even in cases when printing that `RLMArray` property in the console definitely shows at least one corresponding object is present. The search returns the correct index IF the process is closed and re-started (the NSLog on line 96 of `ViewController.m` isn't triggered after restarting).

**4. Steps to reproduce:** I'll send an example project helpATrealm.io. Please notice the `NSLog` in the `ViewController.m` on line 96 as this should indicate exactly when such contradiction occurs.
**5. Code sample that highlights the issue:** Notice that in `RealmCacheModel.m` file I've commented out an alternative implementation that doesn't cause `NSNotFounds` by avoiding deleting objects from the `RLMArray` property `artistsInCache`.
In other words this works, probably because it's avoiding deletions:
```objc
    NSInteger existingIndex = [self.artistsInCache
        indexOfObjectWhere:@"artistId == %@", artist.artistId];
    if (existingIndex == NSNotFound) {
      [self safeAddObject:artist toArray:self.artistsInCache];
    }
```
While this doesn't:
```objc
  NSInteger existingIndex = [self.artistsInCache
      indexOfObjectWhere:@"artistId == %@", artist.artistId];
  if (existingIndex != NSNotFound) {
    [self.artistsInCache removeObjectAtIndex:existingIndex];
  }
  [self safeAddObject:artist toArray:self.artistsInCache];
```

Here's the `safeAddObject:toArray` method, in case anyone is interested:
```objc
- (void)safeAddObject:(RLMObject *)object toArray:(RLMArray *)array {
  if (object.realm != array.realm && array.realm != nil) {
    // If the object isn't in this Realm - bring it in
    RLMObject *newlyCreatedObject =
        [[object class] createOrUpdateInRealm:array.realm withObject:object];
    [array addObject:newlyCreatedObject];
  } else {
    // If the object is already in this Realm, it's safe to just add a link to it
    [array addObject:object];
  }
}
```

Also note that in ViewController.m I'm always requesting a new instance of realmWithPath during Realm operations, but some NSLog statements I've added shows that I'm correctly getting the exact same in-memory instance of RLMRealm every time.
```objc
@interface ViewController ()

@property(nonatomic, readonly) RLMRealm *realm;
@property(nonatomic, readonly) RealmCacheModel *cacheModel;
[...]
@end
@implementation ViewController
- (RLMRealm *)realm {
  return [RLMRealm realmWithPath:self.realmPath];
} 
- (RealmCacheModel *)cacheModel {
  RLMRealm *realm = self.realm;
  RLMResults *array = [RealmCacheModel allObjectsInRealm:realm];
  RealmCacheModel *_trackCacheModel = nil;

  if ([array count] != 0) {
    _trackCacheModel = [array objectAtIndex:0];
  } else {
    _trackCacheModel = [RealmCacheModel new];
    [realm addObject:_trackCacheModel];
  }

  return _trackCacheModel;
}
[...]
```
Same holds for the `self.cacheModel` property.
**6. Version of Realm/Xcode/OSX:** Realm 0.90.5, Xcode 6.1.1 (6A2008a), OSX 10.10.2 (14C109)

**Comment by segiddins** [comment]
@rciobanu-omnifone I was able to boil this down to a test case -- thanks so much for helping us investigate!

**Comment by jpsim** [comment]
I have a feeling this was fixed recently. @segiddins do you still have this test case so we can check?

**Comment by rciobanu-omnifone** [comment]
Re-tested on Realm 0.93.1 and can confirm this problem can't be observed anymore. Looks fixed. Thank you.

**Comment by jpsim** [comment]
Great to hear, and thanks for confirming!
