### ISSUE TITLE
Trying to iterate through RLMResults in swift

### ISSUE THREAD

**Issue by juhaelee** [realm/realm-cocoa#1487]
I'm trying to iterate through RLMResults in swift using:

```
for item in allItems(:RLMResults) {

}
```

and I get the compile error: **'RLMResults' does not have a member named 'Generator'**

**Comment by yoshyosh** [comment]
Hi @juhaelee did you include RLMSupport.swift?

**Comment by juhaelee** [comment]
Oops that was it. thank you
