### ISSUE TITLE
Ream: full text search

### ISSUE THREAD

**Issue by dimazen** [realm/realm-cocoa#1488]
I'm wondering about FTS support. 
For sure it is an sql's feature, but do you have something similar for such queries?

**Comment by yoshyosh** [comment]
We currently don't support that, it is something we want to add in the future though

**Comment by dimazen** [comment]
@yoshyosh sad :( 
I wish to know hw to help you with it :)

**Comment by yoshyosh** [comment]
Maybe one day as we get going with it, thanks :)!
