### ISSUE TITLE
Realm alway stops a a break point when used in an Asynchronous XCTTest

### ISSUE THREAD

**Issue by macdevnet** [realm/realm-cocoa#1493]
When ever realm in written to in an asynchonous XCText it stops at a break point in libswiftCore.dylib`swift_dynamicCastClassUnconditional:  

This makes running a test suite on a CI server impossible. 
For each test I am using an inMemory realm with the name of the test so that is tests do not collide. 

![screenshot 2015-02-12 14 34 57](https://cloud.githubusercontent.com/assets/5823681/6169395/21a8585c-b2c5-11e4-8e19-e7839dcd75b0.png)

**Comment by segiddins** [comment]
@macdevnet can you share the code in question? It seems like you're casting something to the incorrect type.

**Comment by macdevnet** [comment]
This is really strange it is indeed a typecast problem as the error suggests. The problem is it only seems to happen when the code runs in a unit test not when the code runs in the app. 

However the problem has now gone but I don't know why.

Here is the object model.

	class RLMIdentity: RLMObject {
		dynamic var serverUrl : String = ""
		dynamic var identity : String = ""
		dynamic var sessionToken : String = ""
		dynamic var fullName : String = ""
		dynamic var shortName : String = ""
		dynamic var personId : String = ""
		dynamic var clientUUID : String = ""
	}

and the code that set it 

	if self!.sessionCaching {
		var rIdentity : RLMIdentity
		var newIdentity = false;
		let realm = self!.getNewRealm()
		var rIds  : RLMResults =   RLMIdentity.objectsInRealm(realm, withPredicate: self!.identityPredicate)
		if  rIds.count > 0 {
			rIdentity = rIds.firstObject() as RLMIdentity
		} else {
			rIdentity = RLMIdentity()
			newIdentity = true
		}                          
		realm.beginWriteTransaction()
		rIdentity.sessionToken = response.json[self!.kSessionKey].stringValue
		rIdentity.serverUrl = self!.serverUrl
		rIdentity.fullName = response.json[self!.kFullNameKey].stringValue
		rIdentity.shortName = response.json[self!.kShortNameKey].stringValue
		rIdentity.personId = response.json[self!.kBackEnduserId].stringValue
		rIdentity.identity = identity
		rIdentity.clientUUID = clientUID
		if newIdentity {
			realm.addObject(rIdentity)
		}
		realm.commitWriteTransaction()
	}

the line that was causing the problem was `rIdentity.serverUrl = self!.serverUrl`

When I simply went into the model and changed the name of the property to just server and changed the code to just set the property called server the problem went away... 

(Unit testing is using in memory Realms so there was no migration as it is a fresh realm for each test).

Just out of interest I then renamed the property back to serverUrl and it still works , so I have no idea what happened.

Anyway thanks for following up.

**Comment by segiddins** [comment]
My guess would be that you might have your model included twice, once in the app target and once in the test target, that would cause the issues you're seeing. Anyways, I'm glad to hear you figured things out!

**Comment by macdevnet** [comment]
Yep … it’s in both … but why would changing the name and back again fix it?




Sent with Unibox

**Comment by segiddins** [comment]
That, I have no clue about.
