### ISSUE TITLE
Realm Browser shows a user wrong counts of rows.

### ISSUE THREAD

**Issue by ghmlee** [realm/realm-cocoa#1496]
I got a feedback from a user. He said Realm Browser shows him wrong counts of rows like the below image. Ok. I am explaining that there is a class called 'Word' related to another class called 'Published'. In left side menu the 'Word' class has 115 counts but the 'Word' class has 105 counts in 'Published' class. If you want to get a .realm file, I can give you this sample. Thank you. :)

<img src="https://farm8.staticflickr.com/7359/16488426606_a47261fce5_o.png">

**Comment by segiddins** [comment]
Is it possible there are `Word`s that are in the realm but not in the `Published` object's `words` `RLMArray`?

**Comment by njovy** [comment]
@segiddins  I am the one whom asked this question to @ghmlee . 
There are a few classes which have Word or List<Word> in the realm. I checked the count of values and it looked fine.
If one realm object has a Word and the object is getting removed from a realm, do I have to delete the Word object as well or the realm will take care of deleting the word object as CascadeType.Remove would do in JPA.

**Comment by segiddins** [comment]
Realm doesn't have cascading deletes, so removing the object from the RLMArray won't delete it entirely. 

-Samuel E. Giddins

On Feb 12, 2015, at 6:51 PM, Taehyun Park <notifications@github.com> wrote:

@segiddins I am the one whom asked this question to @ghmlee . 
There are a few classes which have Word or List in the realm. I checked the count of values and it looked fine.
If one realm object has a Word and the object is getting removed from a realm, do I have to delete the Word object as well or the realm will take care of deleting the word object as CascadeType.Remove would do in JPA.

**Comment by njovy** [comment]
Thank you so much for the prompt reply. I am not sure if the cascading delete is doable in realm in nosql but it would be great if the feature is supported.
I will add some code to remove related realm objects upon deletion.

**Comment by segiddins** [comment]
@njovy we have an issue tracking adding cascading deletes, https://github.com/realm/realm-cocoa/issues/1186, so you'll see any updates on that front over there.
