### ISSUE TITLE
Fix a typo in the Japanese translation

### ISSUE THREAD

**Issue by laiso** [realm/realm-cocoa#1497]
http://realm.io/jp/docs/cocoa/0.90.5/index.html

I found the following typo :point_down:
https://gist.github.com/laiso/ade3bcae8592f87c1f5f/revisions

**Comment by yuuki1224** [comment]
@laiso さん
ご指摘くださり、ありがとうございます。すぐ修正いたしますね 🙇

**Comment by yuuki1224** [comment]
@laiso さん
修正、反映されました!
今後も日本語ドキュメントで何かお気付きな点等ございましたら、
お手数ですが、ご指摘のほどよろしくお願い致します 🙇

**Comment by timanglade** [comment]
Thanks @laiso!

**Comment by laiso** [comment]
:ok:  :+1:
