### ISSUE TITLE
Add predicate tests learned from the cheatsheet

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1499]

**Comment by timanglade** [comment]
@yoshyosh any update on this? Feel free to close.

**Comment by yoshyosh** [comment]
No updates going to unassign

**Comment by jpsim** [comment]
What does this even mean?

**Comment by yoshyosh** [comment]
The issue was for adding tests for the predicates we don't support yet, the ones that are unmarked here http://realm.io/news/nspredicate-cheatsheet/

**Comment by jpsim** [comment]
Let's open a new ticket if ever we can think of concrete examples.
