### ISSUE TITLE
Add support for RLMSet

### ISSUE THREAD

**Issue by timanglade** [realm/realm-cocoa#1501]
As an alternative to RLMArray if objects need to be contained 1 time max.

**Comment by alazier** [comment]
I think this would only work for objects with defined primary keys.

**Comment by segiddins** [comment]
Not necessarily, since RLMArrays (currently) only store links, and we can just do raw pointer equality on them.

**Comment by kunalsood** [comment]
+1 for this. RLMSet would hopefully also have a `removeObject:` method.

**Comment by natanrolnik** [comment]
+1

**Comment by enricenrich** [comment]
+1 on this!

@kunalsood I created a category for RLMArray to have `removeObject:`. Basically, I get the index of this project, I check if the index isn't bigger than the RLMArray count, and then I delete the object with `removeObjectAtIndex:`. :)

**Comment by kunalsood** [comment]
@enricenrich Thanks mate! :-) I have done something similar (see my second questions at: https://groups.google.com/forum/#!topic/realm-cocoa/eGPMVdPppI8), I also have to need to check if an object already exists in a relationship before I add it, so another kind of hacked on `ks_addObject:` method in my category. RLMSet would hopefully rid me of this category.
