### ISSUE TITLE
`objectsWhere` on RLMResults

### ISSUE THREAD

**Issue by AnthonyMDev** [realm/realm-cocoa#1507]
Why does `RLMResults` not have an `objectsWhere` convenience function, but `RLMArray` does? Additionally, if this was the case, then the `RLMCollection` protocol could have `objectsWhere` defined.

I have a situation where I am using a `id<RLMCollection>` object and I need to filter through them. I should be able to use `objectsWhere`, no?

Thanks

**Comment by segiddins** [comment]
The `RLMCollection` protocol does indeed include the `- (RLMResults *)objectsWhere:(NSString *)predicateFormat, ...;` instance method.
