### ISSUE TITLE
Back links as `RLMResults` or `RLMArray`

### ISSUE THREAD

**Issue by AnthonyMDev** [realm/realm-cocoa#1508]
If my whole project is set up to be manipulating data based on `RLMArray` and `RLMResults`, I need to be able to manipulate back linked objects from an inverse relationship as well. It seems very counter-intuitive to me to have the `linkingObjectsOfClass: forProperty:` method return an `NSArray`.

This is causing me problems in how I am able to work with the data I'm receiving from this query. Is there a way to convert this into `RLMResults`?

**Comment by segiddins** [comment]
Hi @AnthonyMDev, we totally agree it would be great to represent backlinks as `RLMResults`, but unfortunately there's some infrastructure we need to get into place for that to be possible.

**Comment by AnthonyMDev** [comment]
Okay, so this isn't just an odd design decision, but a current limitation? Makes sense. Thanks

**Comment by segiddins** [comment]
@AnthonyMDev yup! As soon as we have support in Core for this, we'll change backlinks to return an `RLMResults`.

**Comment by jpsim** [comment]
This will be done as part of #1324, so I'm closing this as a duplicate.
