### ISSUE TITLE
No results in RLMRealm after restarting app

### ISSUE THREAD

**Issue by AnarH93** [realm/realm-cocoa#1511]
some code from my project. step by step:
```objective-c
RLMRealm *realm = [RLMRealm defaultRealm];
    
UserRLMO *current = [[UserRLMO allObjects] firstObject];
//current not exist (is null)
UserRLMO *newUser = [[UserRLMO alloc] init];
//... newUser init
[realm transactionWithBlock:^{
    [UserRLMO createInDefaultRealmWithObject:newUser];
}];
//or trying this: 
[realm beginWriteTransaction];
[realm addObject:newUser];
[realm commitWriteTransaction];

 UserRLMO *current = [[UserRLMO allObjects] firstObject];
 NSLog(@"login: %@",current); /// yeah - it is exist
```
but, when i restart my app - user again not exist. This is similar to i store RLMRealm in memory, but didn't.

**Comment by yoshyosh** [comment]
Is UserRLMObject == UserRLMO in this sample code?
Referring to this line
````obj-c
UserRLMO *current = [[UserRLMObject allObjects] firstObject];
````

**Comment by AnarH93** [comment]
yea, sorry, i edit code before send issue and lost this one
upd: correct comment

**Comment by yoshyosh** [comment]
Just tried this really quickly, everything is working. When I first run it, current is null since we haven't ran anything. The second time I run it, it does return an object

````
2015-02-17 14:09:42.267 objc905[21244:8122025] Initial current user: UserRLMO {
	name = Peeky;
}
2015-02-17 14:09:42.269 objc905[21244:8122025] login: UserRLMO {
	name = Peeky;
}
````

````obj-c

@interface UserRLMO : RLMObject
@property NSString *name;
@end

@implementation UserRLMO
@end

    RLMRealm *realm = [RLMRealm defaultRealm];
    
    UserRLMO *current = [[UserRLMO allObjects] firstObject];
    NSLog(@"Initial current user: %@", current);
    
    UserRLMO *newUser = [[UserRLMO alloc] init];
    newUser.name = @"Peeky";
    [realm transactionWithBlock:^{
        [UserRLMO createInDefaultRealmWithObject:newUser];
    }];
    
    UserRLMO *lastCurrent = [[UserRLMO allObjects] firstObject];
    NSLog(@"login: %@",lastCurrent); /// yeah - it is exist
````

Perhaps there's something else going on with how you are setting up your models? Can you share more code?

**Comment by AnarH93** [comment]
It is my models class.
REALModels.h
```objective-c
#import <Realm/Realm.h>

@interface REALModels : RLMObject
@property NSString      *demo;
@end

@interface UserRLMObject : RLMObject
@property NSString      *id;
@property NSString      *login;
@property NSString      *access_token;
@property NSString      *first_name;
@property NSString      *second_name;
@property NSString      *photo_url;
@property NSDate        *birthdate;
@property NSInteger     gender;
@end
RLM_ARRAY_TYPE(UserRLMObject)
```

REALModels.m
```objective-c
@implementation REALModels @end

@implementation UserRLMObject

+(NSString*)primaryKey{
    return @"id";
}

@end
```

**Comment by yoshyosh** [comment]
Hey @AnarH93 just tested this out and it also worked . Can you send a project privately to help@realm.io?

Can you share the exact code that you omitted using comments here:
````obj-c
RLMRealm *realm = [RLMRealm defaultRealm];

UserRLMO *current = [[UserRLMO allObjects] firstObject];
//current not exist (is null)
UserRLMO *newUser = [[UserRLMO alloc] init];
//... newUser init
[realm transactionWithBlock:^{
    [UserRLMO createInDefaultRealmWithObject:newUser];
}];
//or trying this: 
[realm beginWriteTransaction];
[realm addObject:newUser];
[realm commitWriteTransaction];

 UserRLMO *current = [[UserRLMO allObjects] firstObject];
 NSLog(@"login: %@",current); /// yeah - it is exist
````

**Comment by AnarH93** [comment]
sorry, i can't send you this project. it's private ^(
Also - i showed all of code, where i use RLMRealm, in "//... newUser init" row - only what i do - it initialize all variables in RLMRealm by default objc type, like 123, @"somestring", etc.
so yeah, it's weird. May i have some way for check this record on RLMR db, or where it records stored? 
i'll be checked local db before and after restarting app for get more information about this "bug"

**Comment by yoshyosh** [comment]
Yes, you can use the Realm Browser to check after first run that your UserRLMObject is indeed stored. Without seeing more of the code it's hard for me to debug this since everything I've run in this thread is working. Giving things default values should have an impact either.

**Comment by AnarH93** [comment]
Ho-ho.
Good news - Realm store object in DB.
Bad news - [UserRLMO allObjects] still return nothing.
Where i can check - what going wrong?

**Comment by AnarH93** [comment]
I'm sorry. it's my fault:
i forgot remove
```objective-c
[[NSFileManager defaultManager] removeItemAtPath:[RLMRealm defaultRealmPath] error:nil];
```
from:
```objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
```

i don't remember - why i did this

**Comment by AnarH93** [comment]
I'm sorry. it's my fault:
i forgot remove
```objective-c
[[NSFileManager defaultManager] removeItemAtPath:[RLMRealm defaultRealmPath] error:nil];
```
from:
```objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
```

i don't remember - why i did this

**Comment by yoshyosh** [comment]
Nice! Good to hear you found the culprit. I think you might have got that from one of the samples, the main reason people use that line is when they are avoiding migrations while testing out the DB
