### ISSUE TITLE
Desktop app's column headers are incorrectly labeled.

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1514]
Sometimes my column headers get mixed up in the desktop app.
The columns in the attached screenshot should be as follows: "Simplified" "Traditional" "pinyin" "englishDefinitions" *then* "sentences". As you can see, they are out of order.

![screen shot 2015-02-17 at 3 29 54 pm](https://cloud.githubusercontent.com/assets/1189875/6237703/ab408992-b6ba-11e4-8a09-81cb21147373.png)

**Comment by segiddins** [comment]
@webmagnets what version of the Realm Browser are you running? (`Realm Browser` -> `About Realm Browser`)

**Comment by webmagnets** [comment]
0.90.5



-
Nathan Cain
501-463-6336

www.jw.org

**Comment by segiddins** [comment]
Would it be possible for you to share the Realm file you're opening in the browser with us, so we can take a closer look at what's going on?

**Comment by webmagnets** [comment]
Can I email is to you please?

**Comment by segiddins** [comment]
Of course! help@realm.io

**Comment by webmagnets** [comment]
I just emailed it, let me know if you don't get it. Thanks.

**Comment by segiddins** [comment]
I cannot reproduce this -- 
![screenshot 2015-02-17 14 21 38](https://cloud.githubusercontent.com/assets/1946610/6238505/7c07f552-b6b0-11e4-8a23-74bdd52254b3.png)

Is it possible you once accidentally re-ordered the columns in a previous version of the Realm Browser (before column re-ordering was disabled)?

**Comment by webmagnets** [comment]
I never knew you ever could reorder, but it is possible.




-
Nathan Cain
501-463-6336

www.jw.org

**Comment by jpsim** [comment]
Hopefully #1304 fixed this.

**Comment by webmagnets** [comment]
Is there a way to fix my realm file? I would rather not have to rebuild it.
