### ISSUE TITLE
Error installing Realm cocoapod

### ISSUE THREAD

**Issue by drmarkpowell** [realm/realm-cocoa#1520]
I'm having a similar issue to #1022. I'm on OS X 10.10.2, running XCode 6.1.1 and Cocoapods 0.35.0.

I get an error running pod install to configure Realm.
I tried removing /tmp/core_bin as suggested in issue #1022 but it didn't help.
Please advise!

````
Installing Realm (0.90.5)
[!] /usr/local/bin/bash
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...

Downloading dependency: core 0.88.1

Archive:  /tmp/core_bin/core-0.88.1.zip
  End-of-central-directory signature not found.  Either this file is not

  a zipfile, or it constitutes one disk of a multi-part archive.  In the

  latter case the central directory and zipfile comment will be found on

  the last disk(s) of this archive.

unzip:  cannot find zipfile directory in one of /tmp/core_bin/core-0.88.1.zip or

        /tmp/core_bin/core-0.88.1.zip.zip, and cannot find /tmp/core_bin/core-0.88.1.zip.ZIP, period.
````

**Comment by drmarkpowell** [comment]
Wow, now *today* I removed the tmp/core_bin directory and tried again and it worked. Yesterday it was definitely broken on repeated attempts. At a guess, maybe the CI process was successful last night?

**Comment by mrackwitz** [comment]
>```
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
```

What has seemingly happened here is that your download was corrupted.

>At a guess, maybe the CI process was successful last night?

The versioned Core binary isn't altered once it is uploaded and no new version was released since yesterday.

As the problem doesn't continue to exist for you anymore, I'd close this issue for now. If you see this appearing again, feel free to reopen / comment on this issue to bring that to our attention.
