### ISSUE TITLE
-[RLMArray insertOrUpdateObject:atIndex:]

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#1521]

**Comment by jpsim** [comment]
Can you give an example of how this could be used? I have trouble thinking of a scenario where you'd actually want this.

```swift
rlmArray // => [0, 1]
zero // => 0
rlmArray.insertOrUpdateObject(one, atIndex: 1) // => [0, 0, 1]
one // => 1
rlmArray.insertOrUpdateObject(one, atIndex: 2) // => [0, 0, 1]
two // => 2
rlmArray.insertOrUpdateObject(two, atIndex: 1) // => [0, 2, 0, 1]
```

Am I misunderstanding what this method would do? It seems very odd to me.

**Comment by jpsim** [comment]
Even something like `+[RLMArray addOrUpdateObject:]` wouldn't make much sense because you wouldn't be able to update objects, they're always up to date. Hurray Realm :sparkles:.

**Comment by nakp** [comment]
@jpsim I find this kind of useful, I've tried to add the same object twice and now I have duplicate relationships, as the way to use 1:n relationships is with RLMArray, this seems pretty logic if you are trying to avoid adding the same object again and having duplicate relationships, `- [RLMArray addObject:]` does not take care of this

**Comment by jpsim** [comment]
@nakp so you'd like a shortcut method for this?

```swift
if rlmArray.indexOfObject(object) == NSNotFound {
  rlmArray.addObject(object)
}
```

I'm not convinced adding such a simple convenience method in Realm is worth the impact on our interface.

**Comment by nakp** [comment]
It is as convenient as `+ [RLMObject createOrUpdateInDefaultRealmWithObject:]`, so far I'm using Objective C and my solution for the moment was to use arrays and backlinks, thanks for the recommendation
