### ISSUE TITLE
Realm Locking Main Thread Indefinitely

### ISSUE THREAD

**Issue by jimjeffers** [realm/realm-cocoa#1522]
When I attempt to migrate my default realm the main thread locks indefinitely. I set a break point just before the call to setSchemaVersion: and attempt to print out the path in LLDB:

    (lldb) po [RLMRealm defaultRealmPath]
    /Users/jim/Library/Developer/CoreSimulator/Devices/39EF0DDD-8D57-4F70-BC5C-283B84AE4D7D/data/Containers/Data/Application/38784568-3D9C-40BE-B514-F6071C152D8B/Documents/default.realm

But then even trying to instantiate the realm and print the path (which I believe should throw an exception because my realm has not been migrated yet causes the application to lock up:

    (lldb) po [RLMRealm defaultRealm].path
    error: Execution was interrupted, reason: signal SIGTERM.
    The process has been returned to the state before expression evaluation.

I get no actual error. The error printed out is thrown once I terminate the simulator after a few minutes. Is there any way I can further diagnose this error?

**Comment by segiddins** [comment]
@jimjeffers is it possible you're trying to use the Realm from multiple processes? Could you possibly share the backtrace that happens when the main thread hangs?

**Comment by jimjeffers** [comment]
That was the issue. There was no backtrace I had to actually press stop in Xcode to terminate the process. It was very bizarre. I deleted the application from the simulator and everything is fine again. I will post back if I can recreate the instance again. Otherwise, it may be an issue with the simulator.

**Comment by segiddins** [comment]
If it happens again, instead of pressing stop in Xcode, press pause and type `bt` in the debugger, that'll show you the backtrace (and certainly let us know!).

**Comment by jimjeffers** [comment]
Got it. Well just a heads up. It happened again but this time I closed the Realm Browser and reran the app. Now I'm getting the expected error instead of a hanging process! I'll be sure not to have that running in the background as I test the app.
