### ISSUE TITLE
dyld: Symbol not found: _CFAutorelease in iOS 6

### ISSUE THREAD

**Issue by Rebirthble** [realm/realm-cocoa#1526]
I can't get objects when launched app in iOS 6

### code

```objective-c
RLMResults *points = [CheckPoint objectsWhere:[NSString stringWithFormat:@"name = '%@'", name]];
CheckPoint *savedPoint = [points firstObject];
```

### error

```
dyld: Symbol not found: _CFAutorelease
  Referenced from: /var/mobile/Applications/EE24F85E-E8DC-441A-9B12-78D8A9C300A5/PushSample.app/PushSample
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
```

CFAutorelease has called from RLMAutorelease function in RLMRealm.mm

```objective-c
// ARC tries to eliminate calls to autorelease when the value is then immediately
// returned, but this results in significantly different semantics between debug
// and release builds for RLMRealm, so force it to always autorelease.
static id RLMAutorelease(id value) {
    // +1 __bridge_retained, -1 CFAutorelease
    return value ? (__bridge id)CFAutorelease((__bridge_retained CFTypeRef)value) : nil;
}
```

But CFAutorelease has been added to the CoreFoundation.framework in iOS7.

https://developer.apple.com/library/ios/releasenotes/General/iOS70APIDiffs/

Can I use Realm with iOS6?

**Comment by Rebirthble** [comment]
* Realm version0.90.5
* Xcode 6.1
* OS X version 10.9.5

**Comment by segiddins** [comment]
Realm is actually built to target iOS 7.0 and above, sorry. If you were using CocoaPods, you'll get a proper error once https://github.com/realm/realm-cocoa/issues/1529 is merged.
