### ISSUE TITLE
Json support with 'null' value and missing fields

### ISSUE THREAD

**Issue by TofPlay** [realm/realm-cocoa#1527]
**Goals**
Like some many people I would like to store under Realm some json sent by servers. I don't have control of these servers. I can not change the json. Most of the time they send only fields with values to reduce the network bandwidth or sets the value to 'null'. 

**Expected results**
- Ignore missing fields
- Ignore null values

**Actual results**
Generate exceptions:
```
RealmTest[86832:5424687] *** Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value '<null>' for property 'value2Null''
```
```
RealmTest[86832:5424687] *** Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value '<null>' for property 'value3Optional''
```

**Steps to reproduce**
1 Define RMLObject:
```objc
@interface DataFromServer : RLMObject
@property NSString *value1;
@property NSString *value2Null;
@property NSString *value3Optional;
@end
```
2 Load this json and store on Realm:
```json
 {
    "value1": "XXXXXX",
     "value2Null": null,
}
```
**Version of Realm/Xcode/OSX**
0.90.5/6.1.1/10.10.1
I use cocoapod

**Comment by segiddins** [comment]
@TofPlay, we're sketching out building some APIs that would make that sort of object mapping a lot easier -- for example, https://github.com/realm/realm-cocoa/issues/1063, https://github.com/realm/realm-cocoa/issues/694, and https://github.com/realm/realm-cocoa/pull/1272. In short, it's on our radar as something we need to address, but in the meantime, you'll need to remove those null values yourself before passing them into Realm (and also perhaps take advantage of Realm's support for `defaultValues`).

**Comment by TofPlay** [comment]
@segiddins I talked with my boss and without a real support to integrate json we will move towards an alternative. Tell us when you have a more mature version of it reassess Realm.

**Comment by segiddins** [comment]
Have you taken a look at Realm-JSON yet? It's a third party framework that a lot of people have reported success using. (There are also some other old standbys such as Mantle and RestKit that do more general object mapping).

**Comment by TofPlay** [comment]
Yes. We also evaluate this components. Is not fully compatible with json, the design is pretty bad (with 1/3 of the code I was able to do the same) and it's add an overload. The solution is not to add a layer on a layer to patch Realm. The proper solution is that Realm supports concepts of null properties and autoresized missing values.

**Comment by segiddins** [comment]
We agree about nullable properties and we're actually working on adding those into the core database. As for missing properties, that's exactly what the defaultProperties are used for.

**Comment by TofPlay** [comment]
A missing property conceptually is not exactly the same as to set the property with a default value. When a server sent a json with a missing property this means that the property is not used at all. Set a default value means we will used the property with a default value. Missing and default value are different concepts.
Let us know when nullable properties will be supported and we will evaluate Realm.

**Comment by anlaital** [comment]
I use Realm extensively in our application currently and working around this limitation is not that big of a hassle. You can just wrap values that are optional in the JSON (i.e. null or missing) in a custom ```RLMObject``` subtype, such as ```OptionalDate```, which encapsulates the ```NSDate``` value but can actually be null in Realm as it inherits from ```RLMObject```.

This doesn't really add any overhead to speak of and is a reasonable solution for the time being. I would strongly encourage @TofPlay not to stop using Realm just because of this. This is just my opinion, but using Realm has saved me insane amounts of time and headache.

**Comment by RuiAAPeres** [comment]
Has there been any update on this?

**Comment by yoshyosh** [comment]
A little here https://github.com/realm/realm-cocoa/issues/628#issuecomment-66784833. We should have null support for strings very soon. We will be running a quick beta test so be sure to checkout/follow that thread
