### ISSUE TITLE
Migration on parent object changes - assert error

### ISSUE THREAD

**Issue by MattKiazyk** [realm/realm-cocoa#1528]
Currently I'm trying to add a new property called deleted on a parent RLMObject Class

```
@interface GTRemoteObject : RLMObject
@property (assign, nonatomic) BOOL deleted;
```

I then have various subclasses inheriting from `GTRemoteObject`. I have a default value set on `GTRemoteObject` for deleted.

My migration is set to the following:

```
    [RLMRealm setSchemaVersion:1 forRealmAtPath:[RLMRealm defaultRealmPath]
            withMigrationBlock:^(RLMMigration *migration, NSUInteger oldSchemaVersion) {
        if (oldSchemaVersion < 1) {
            [migration enumerateObjects:GTRemoteObject.className block:^(RLMObject *oldObject, RLMObject *newObject) {
                newObject[@"deleted"] = @NO;
            }];
        }
    }];
```
It then will error out on the line:
```
// verify that we didn't add any properties twice due to inheritance
assert(props.count == [NSSet setWithArray:[props valueForKey:@"name"]].count);
```
If I remove the enumerate and just use a simple migration, same issue. If I set a migration for *every* subclass of `GTRemoteObject`, same error. I'm assuming this is because it's trying to add `deleted` to each subclass again, when I've already added it to the parent class in the migration?

What am I missing? 

Thanks

-Matt

**Comment by segiddins** [comment]
@MattKiazyk would it be possible for you to share your model definitions? No matter what, though, you'll need to call `enumerate` for all of the subclasses, since in Realm, each subclass is its own, unrelated entity.

**Comment by MattKiazyk** [comment]
An example:

```
@interface GTRemoteObject : RLMObject
@property (assign, nonatomic) NSInteger remoteID;
@property (assign, nonatomic) BOOL deleted;
@property (strong, nonatomic) NSDate *synchronizedAt;
@end
```
A subclass
```
@interface GTCity : GTRemoteObject
@property (strong, nonatomic) NSString *name;
@property (strong, nonatomic) NSString *state;
@property (assign, nonatomic) CGFloat latitude;
@property (assign, nonatomic) CGFloat longitude;
@property (assign, nonatomic) BOOL majorCity;
@end
```

Again in this example, was just adding the deleted onto the `GTRemoteObject` class

**Comment by segiddins** [comment]
@MattKiazyk is it possible that you just need to set the schema version to a higher number?

**Comment by jpsim** [comment]
Hi @MattKiazyk, have you made any progress on this?

I think @segiddins is right in thinking that you're likely not setting an appropriate schema value.

Here's some code I used to attempt to reproduce the behavior you're seeing:

**First Run: Schema 0**
```objc
@interface ParentObject : RLMObject
@property NSString *name;
@end
@implementation ParentObject
@end

@interface ChildObject : ParentObject
@property NSInteger age;
@end
@implementation ChildObject
@end

// Later...

RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[ChildObject createInRealm:realm withObject:@[@"child name", @10]];
[realm commitWriteTransaction];

for (ChildObject *obj in [ChildObject allObjects]) {
  NSLog(@"%@", obj);
}

// Prints
// 
// ChildObject {
//     name = child name;
//     age = 10;
// }
```

**Second Run: Schema 1**
```objc
@interface ParentObject : RLMObject
@property NSString *name;
@property BOOL deleted;
@end
@implementation ParentObject
@end

@interface ChildObject : ParentObject
@property NSInteger age;
@end
@implementation ChildObject
@end

// Later...

[RLMRealm setDefaultRealmSchemaVersion:1
                    withMigrationBlock:^(RLMMigration *migration, NSUInteger oldSchemaVersion) {
    [migration enumerateObjects:@"ParentObject"
                          block:^(RLMObject *oldObject, RLMObject *newObject) {
        newObject[@"deleted"] = @NO;
    }];
    [migration enumerateObjects:@"ChildObject"
                          block:^(RLMObject *oldObject, RLMObject *newObject) {
        newObject[@"deleted"] = @NO;
    }];
}
for (ChildObject *obj in [ChildObject allObjects]) {
  NSLog(@"%@", obj);
}

// Prints
// 
// ChildObject {
//     name = child name;
//     age = 10;
//     deleted = 0;
// }
```

Please reopen this issue if we've misunderstood the problem you're hitting. We'd greatly appreciate if you could send us code to reproduce the behavior if that's the case.

**Comment by MattKiazyk** [comment]
Hi @jpsim sorry for not getting back to you. Tried a quick project to see if I could duplicate and it was working fine. Even on the migration setting just the parent object seemed to be ok.  Thanks for your feedback.
