### ISSUE TITLE
Test invalid schema

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1530]
We really need to have this for the new swift apis.

**Comment by segiddins** [comment]
I actually was playing around in https://github.com/realm/realm-cocoa/compare/seg-customizable-schemas, you might find some of that interesting.

**Comment by alazier** [comment]
We can add tests for this using the same methodology we use in swift (testing classes which do no derive from RLMObject).

**Comment by segiddins** [comment]
We've since added some tests that do that (mainly done by @bdash in https://github.com/realm/realm-cocoa/blob/16de7a70830d9f7dff969186334f335761ad2d58/Realm/Tests/SchemaTests.mm) but now the infrastructure's all in place.
