### ISSUE TITLE
access to static.realm.io at app launch

### ISSUE THREAD

**Issue by Fab1n** [realm/realm-cocoa#1532]
today we detected that realm wanted to make a call to static.realm.io at launch of our app.

Why? And what for?

**Comment by yoshyosh** [comment]
Hey Fab1n, Realm checks to make sure you have the latest version available. Since things are rapidly changing there are a lot of fixes in both and the core and bindings that can improve the performance of the framework

**Comment by segiddins** [comment]
@Fab1n, the only place we make that network request is at https://github.com/realm/realm-cocoa/blob/master/Realm/RLMUpdateChecker.mm -- as Joe said, we're just checking to see whether an updated version of Realm is available.

**Comment by Fab1n** [comment]
Ok, but that doesn't change anything if my app is running, as if there is an update you cannot inject the new sources. 
For the User this request is not useful. Is this only in debug mode?

Ah ok. Just checked sources. Only in simulator. Nice. Well done!!!
