### ISSUE TITLE
What has changed in v0.90.6?

### ISSUE THREAD

**Issue by Fab1n** [realm/realm-cocoa#1535]
Hey guys, 

great work with this db. 
Where can easily see, what's new in each new version?

**Comment by alazier** [comment]
The v0.90.6 changelog hasn't been pushed to master yet:

https://github.com/realm/realm-cocoa/blob/v0.90.6/CHANGELOG.md

**Comment by alazier** [comment]
Usually the changelog on master has the changes for all previous releases.
