### ISSUE TITLE
Schema Development

### ISSUE THREAD

**Issue by adhiravishankar** [realm/realm-cocoa#1540]
Realm is great and it has been a pleasure working with it.

However, Realm has one problem. Realm should allow for a way to be able to disable or at least give developers the option to throwaway the old database without having to migrate to a new one. Under development, there are times where I have to change the database for a multitude of reasons: changing app requirements, design. I think Realm should allow at least the option to make it optional if not standard like Android, and having something like strict mode where it would not be allowed. Also, many apps don't require the old data simply because it doesn't need it, for example a weather app. I'm not going to need data from two weeks ago or even yesterday. Also, making us do new classes underneath the old ones is not going to help code readability and keeping our app as simple as possible. Migrate statements should be a must, but it should throw an exception if it encounters something that is not in the migrate statement. I would try to do this myself, but I'm new to iOS programming and I have only done Swift. It would be great if you implemented this.

Ideally, if there was no strict mode enabled and no migration code, it should automatically throw away the old database file and make a new one with the new schema.

**Comment by segiddins** [comment]
You can always delete the realm file before opening it if the scheme version is lower that what what you expect, that way you'll never need a migration. Hope that helps!

**Comment by jpsim** [comment]
For anyone looking for how to do this, you can use [`+[RLMRealm schemaVersionAtPath:error:]`](http://realm.io/docs/cocoa/api/Classes/RLMRealm.html#//api/name/schemaVersionAtPath:error:) to get the schema version of the current database.
