### ISSUE TITLE
Make inWriteTransaction public

### ISSUE THREAD

**Issue by romaonthego** [realm/realm-cocoa#1541]
I have the following category on `RLMObject` in my app:

```objective-c
- (void)app_transactionWithBlock:(void(^)(RLMRealm *realm, id model))block
{
    NSAssert(block, @"Block is required.");
    RLMRealm *realm = [RLMRealm defaultRealm];
    if (!realm.inWriteTransaction) {
        [realm transactionWithBlock:^{
            block(realm, self);
        }];
    } else {
        block(realm, self);
    }
}
```

It would have been very handy if `inWriteTransaction` was public. Thanks!

**Comment by alazier** [comment]
We intentionally left this out but have had a few other requests for this features. At this point I think we should add this.

**Comment by natanrolnik** [comment]
@romaonthego that's interesting - I had a similar problem in my app, where I had nested call to write transactions and it ended up crashing. Did you manager to use your solution even with the fact that `inWriteTransaction` is private?

**Comment by romaonthego** [comment]
@natanrolnik since you have the source code you can make it public for your class, like this:

```objc
@interface RLMRealm ()

@property (nonatomic, readonly) BOOL inWriteTransaction;

@end
```
