### ISSUE TITLE
Add removeObjects to RLMArray

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1543]
Since we have `addObject`, `addObjects`, and `removeObjectAtIndex` what about `removeObject` and `removeObjects` that accepts an array of objects? Seems like this would rely on a hidden primary key

**Comment by segiddins** [comment]
Why would this rely on a hidden primary key? `removeObject` doesn't.

**Comment by yoshyosh** [comment]
Oops there isn't a `removeObject` only a `removeObjectAtIndex`

**Comment by segiddins** [comment]
You can already achieve the same thing by doing `[array removeObjectAtIndex:[array indexOfObject:object]]`

**Comment by yoshyosh** [comment]
Going to look for more instances of people doing verbose things with removing objects

**Comment by kunalsood** [comment]
Question: What is the expected behavior when NSNotFound gets passed to removeObjectAtIndex: method of RLMArray?

I found myself checking for NSNotFound often enough that I ended up adding the following method in an RLMArray category.
```
- (void)removeObject:(RLMObject *)object
{
    NSUInteger idx = [self indexOfObject:object];
    if (idx != NSNotFound)
    {
        [self removeObjectAtIndex:idx];
    }
}
```
