### ISSUE TITLE
Change +attributesForProperty: to indexedProperties

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1549]
RLMObject is inconsistent with this according to the API reference http://realm.io/docs/cocoa/0.90.6/api/Classes/RLMObject.html#//api/name/indexedProperties, doesn't seem like indexedProperties exists?

**Comment by segiddins** [comment]
@yoshyosh it's on master, but not yet released.

**Comment by yoshyosh** [comment]
:+1:
