### ISSUE TITLE
Support querying "%@ IN (RLMArray keypath)"

### ISSUE THREAD

**Issue by ceeK** [realm/realm-cocoa#1550]
**Summary**
Querying existence of objects in an RLMArray needs a specific query syntax.

**Steps**
Query an RLMArray of objects:
 - First with: (ANY types = %@)
 - Then with (%@ IN types)

**Expected**
(%@ IN types) should work as it makes grammatical sense, even if array contains one value.

**Actual**
Only (ANY types = %@) works, and the second option does not.
 Error message: Predicate with IN operator must compare a KeyPath with an aggregate with two values

**Workaround**
Had to figure this out manually, would be good to put this in the docs for querying to-many relationships.

**Comment by yoshyosh** [comment]
%@ IN types will receive a string literal for %@. %K is a way you can pass in a KeyPath.

We haven't released this yet but here is a [predicate cheat sheet](https://www.dropbox.com/s/fx52t5o1tmhwrz9/NSPredicateCheatsheet.pdf?dl=0) that covers what you can do with NSPredicate and the things we support in Realm.

**Comment by romaonthego** [comment]
@yoshyosh that cheat sheet mentions support for "Keypath collection queries", on the other hand there's this open issue https://github.com/realm/realm-cocoa/issues/1490. Is that something that will be supported in the future (work in progress) or am I missing something? In my app I want to have the following predicate: 
`[Item objectsWhere:@"categories.@count == 0"];` but Realm asserts that `@count` is not supported.

**Comment by yoshyosh** [comment]
We don't support Keypath collection queries yet, everything with the pink dot next to it is what we currently support. #1490 also shows all the unsupported predicates we need to work on.

You can either store a bool on your item object that you can check if categories are empty or not, or you can create an NSArray of items and run predicate on that.

**Comment by romaonthego** [comment]
@yoshyosh I see, thanks! I ended up doing this: 
```objective-c
[Item objectsWhere:@"NOT ANY categories IN %@", [Category allObjects]];
```

**Comment by yoshyosh** [comment]
Oh nice! I'll have to remember this one :), thanks for sharing that

**Comment by yoshyosh** [comment]
Hi @ceeK just checking in, did this solve your issue?

**Comment by ceeK** [comment]
Hi Yoshyosh - it did solve my issue! Thanks :) 

It's still slightly confusing why one works and one does not however:

1:
(ANY types = <FITType>)

2:
(<FITType> IN types)

I was passing in a 'FITType' object into both scenarios. How come scenario 1 doesn't receive a String literal but scenario 2 does? 

If this is just my naivety towards NSPredicate then I apologise.

**Comment by jpsim** [comment]
@ceeK's original report is correct, `%@ IN types` should work since it yields a logically equivalent predicate to `ANY types = %@` and `types CONTAINS %@`.

```swift
let array = [[0], [1]] as NSArray

let predContains = NSPredicate(format: "self CONTAINS 0")
array.filteredArrayUsingPredicate(predContains) // => [[0]]

let predIn = NSPredicate(format: "0 IN self")
array.filteredArrayUsingPredicate(predIn)       // => [[0]]

let predAny = NSPredicate(format: "ANY self = 0")
array.filteredArrayUsingPredicate(predAny)      // => [[0]]
```

**Comment by michaelloistl** [comment]
I'm slightly confused. ```NSPredicate(format: "RLMObject IN RLMArray")``` throws an exception for me. Is that not yet supported? The cheat sheet suggests ```@"'name' IN $NAME_LIST"```.

**Comment by yoshyosh** [comment]
name refers to the property of the RLMObject, could you share an example of your code?

**Comment by michaelloistl** [comment]
I have a RLMObject ```Tag``` as well as a RLMObject ```Item```. The ```Item``` object has a relationship ```dynamic var tags = RLMArray(objectClassName: Tag.className())```.
I would need a predicate to get all items that include a specific ```Tag```  object in tags. So basically like ```NSPredicate(format: "%@ IN tags", tag)```.

**Comment by yoshyosh** [comment]
You are correct this currently isn't supported, you can only compared a keyPath with RLMArray with a value. You could also do something like `NSPredicate(format: "ANY tags.name = %@", tagNameHere)`

**Comment by michaelloistl** [comment]
That works brilliantly for what I need. Thank you!

**Comment by yoshyosh** [comment]
No problem :+1: glad to hear it :)!
