### ISSUE TITLE
Iteration skips one item

### ISSUE THREAD

**Issue by attheodo** [realm/realm-cocoa#1561]
Hello everyone,

I have this method https://gist.github.com/attheodo/2943745229e3e8873bf8 

First of all, I want to ask if this is the proper way of making this query. Essentially, `PSTChatMsg` objects have a many-to-one relationship with a `PSTChannelEnvironment` that keeps them in a `chatMessages: RLMArray`. But since the `PSTChatMsg` also happens to have the `channelName` property I believe I can leave `PSTChannelEnvironment` out of the equation. Do you think it'd be faster to query it through `PSTChannelEnvironment` ?

My main issue however is that the iterator pretty much always skips one item that should be there. I can confirm that my predicate  should also match this item by checking the `lastObject` of the `chatMessages: RLMArray` property of the `PSTChannelEnvironment` that matches the same channel name. 

My eye caught a thread somewhere where some mentioned Realm marks some objects "dirty" and that could be the reason they are sometimes skipped from an iteration but he didn't elaborate further.

I was hoping you might be able to point me to the right direction.

Thank you all

**Comment by yoshyosh** [comment]
I think it will be faster to just use the PSTChannelEnvironment that you know holds your RLMArray of chatMessages. PSTChatMsg will have the most rows so it will ultimately take longer to check your predicate conditions on each. Instead it will be nice to just grab the one specific channel and all of its chatMessages without much overhead with predicates especially if PSTChannelEnvironment is unique or has a primary key. In general this is the power of a graph model since all of the objects you need can be on a specific object.

The iterator skipping 1 object is a bit odd...Do you think you could add some sample data to this code (like a pre-made array) to see if there is any weird behavior anywhere. Also is it a specific object it skips, like always the last object? Anything you can do to narrow this done will help with debugging it.

**Comment by attheodo** [comment]
@yoshyosh thanks for your response. Regarding the iterator, yes it is always the last object being skipped. Shortly before this code executes, a job in `realmqueue` adds a new PSTChatMsg in Realm. It might be the case that the code executes before this job finishes, but again, the last object wouldn't show up in `chatMessages.lastObject()` right?

**Comment by yoshyosh** [comment]
Correct, a quick test could be to put 
````swift
println(chatMessage.lastObject())
````
After these lines
````swift
var predicate = NSPredicate(format: "(channel = %@) AND (hasBeenRead = %d) AND (uuid = %@)", channel, -1, uuid)
var unreadMessages = PSTChatMsg.objectsInRealm(realmdb, withPredicate: predicate)
````

**Comment by attheodo** [comment]
@yoshyosh please check this out https://gist.github.com/attheodo/dcb199dc2237f63cc19c

**Comment by jpsim** [comment]
Hi @attheodo, one of my favorite Realm features is that everything is always up to date. But, it can hit you by surprise sometimes if you forget about it.

So what's happening here is you're changing the set of objects in the `unreadMessages` RLMResults by changing its `hasBeenRead` property. So as you're iterating over the results, they change and some of them end up being skipped.

So a different way to mark all the objects as read is to use a while loop like this:

```swift
while unreadMessages.count > 0 {
  let chatMessage = unreadMessages.first() as! PSTChatMsg
  chatMessage.hasBeenRead = timetokenAtRead
  log.verbose("Marked message \"\(chatMessage)\" as read")
}
```

Once we have #1536 completed, performing bulk updates will be much easier and faster: `unreadMessages.setValue(timetokenAtRead, forKey: "hasBeenRead")`.

Please don't hesitate to ask us if there's anything else we can help you with.

**Comment by attheodo** [comment]
Oh god! So you're telling me the RLMResults array is being dynamically updated when some of the messages cease to conform to the predicate because I am changing their values in the loop..!? Thats crazy and yet wonderful! Thanks man, that solves my problem and restores my sanity levels. Cheers.

**Comment by jpsim** [comment]
You got it! Powerful, but it still bites you when you forget.
