### ISSUE TITLE
App and WatckKit App Extension share objects

### ISSUE THREAD

**Issue by Bruno-Furtado** [realm/realm-cocoa#1565]
I use the realm to save a local object.
When trying to get this object through the app everything works correctly.

When I try to get this same object through the Watch App is not returned any results.
You can share this object through the two environments?

I believe it is not possible:
[WatchKit App Architecture](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/WatchKitProgrammingGuide/DesigningaWatchKitApp.html#//apple_ref/doc/uid/TP40014969-CH3-SW4)

**Comment by yoshyosh** [comment]
Hey Bruno, this is still a WIP https://github.com/realm/realm-cocoa/issues/824, feel free to comment on this issue there!
