### ISSUE TITLE
deleteObjects does not delete objects when when giving NSArray to [realm deleteObjects:]

### ISSUE THREAD

**Issue by issue2k** [realm/realm-cocoa#1566]
Hi,

API says i can give an NSArray* to the deleteObjects method. While i can delete objects when giving RLMResults it does not delete them when giving an NSArray of RLMObjects. I tried to call [realm invalidate] afterwards but this even does not help. Am i missing something? Might it be a problem that these objects are still referenced from an RLMResults?

thanks,
Jakob

**Comment by yoshyosh** [comment]
I just tried this out by passing an NSArray of RLMObjects, it does work as expected. There could be something else going on with your code. Can you share a code snippet of how you are building the array and doing the delete?

**Comment by issue2k** [comment]
Yes maybe i am doing it wrong. This is basically what i try to do. I want to delete every second LocationData object. The problem is that it does not delete any location when giving in the NSMutableArray (tried NSArray too) to deleteObjects. When i just give all locations by passing the RLMResults in there its working.

```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
    NSNumber *tripId = [task.userInfo objectForKey:@"id"];            
    RLMRealm *realm = [RLMRealm defaultRealm];
    Trip *trip = [[Trip objectsInRealm:realm where:@"id == %@", tripId] firstObject];
    RLMResults *locations = [LocationData objectsInRealm:realm where:@"trip == %@", trip];
    
    // Select every second location
    NSMutableArray *locationsToDelete = [NSMutableArray new];
    for(int i = 0; i < [locations count]; i++) {
        if((i % 2) == 0) {
            LocationData *locationToDelete = [locations objectAtIndex:i];
            [locationsToDelete addObject:locationsToDelete];
        }
    }
          
    // Delete selected locations 
   if([locationsToDelete count] > 0) {
        [realm beginWriteTransaction];
        [realm deleteObjects:locationsToDelete];
        [realm commitWriteTransaction];
   }
                
    // Mark trip as cleaned up
    [realm beginWriteTransaction];
    trip.cleanupDone = YES;
    [realm commitWriteTransaction];
});
                
```

**Comment by yoshyosh** [comment]
````obj-c
LocationData *locationToDelete = [locations objectAtIndex:i];
            [locationsToDelete addObject:locationsToDelete];
````
Can you check this typo here `locationsToDelete` is being added not `locationToDelete`

**Comment by issue2k** [comment]
omg i am ashamed. Sorry that i bothered you with this...working perfectly when adding the right objects and not adding the list to itself.

**Comment by yoshyosh** [comment]
Don't worry about it @issue2k I'm happy to hear you got it working!
