### ISSUE TITLE
Encrypted interprocess sharing is currently unsupported

### ISSUE THREAD

**Issue by Fab1n** [realm/realm-cocoa#1567]
We get this exception when trying to secure our Realm db. 

In run config we switched to "Release" and unticked "Debug executable".

We are working with `RLMRealm.setEncryptionKey(EncryptionHelper.getKey(), forRealmsAtPath: RLMRealm.defaultRealm().path)`

Until now I had no change of using an application encrypted. We need to test this as it is key to our product!!!

**Comment by Fab1n** [comment]
I know, you guys are awesome and do a great job with Realm!

Please tell me that encryption works in another queue with gcd... This is a total requirement for us

**Comment by tgoyne** [comment]
Encrypted realms can only be open in one process at a time, and this will not change even when we officially roll out support for sharing normal realms between processes.

Opening encrypted realms on multiple threads works as normal.

**Comment by Fab1n** [comment]
Ok, I know that because of the error message Realm gives me. Then what do I do wrong with setting the encryption key for a realm at a path and then running a importer that imports data from json in the background with dispatch_async. 
If I am importing on the main thread (without dispatch_async) I don't get this exception "Encrypted interprocess sharing is currently unsupported"

**Comment by jpsim** [comment]
That exception should only be thrown when opening an encrypted Realm from a different process. Are you sure there are no other processes accessing that file? Perhaps the Realm Browser, or an iOS Extension?

**Comment by Fab1n** [comment]
No, nothing. Just running inside simulator or on device CMD-R.

**Comment by jpsim** [comment]
> You even don't have gcd tests as far as I can see. So nobody knows, if it works or what best practices are...

There are in fact several multithreaded tests (just search for `dispatch_`) and with the recent encryption improvements (#1562) it's now possible to run the entire test suite using encrypted realms (see [`encryptTests()`](https://github.com/realm/realm-cocoa/blob/ed498a1a56a50496871b19ed29d615a6618dd64a/Realm/Tests/RLMTestCase.m#L78)). All the tests pass with this enabled.

Once Realm's multi-process support is officially released (which will be very very soon), we'll elaborate more on best practices.

Now back to the issue you're facing, does it occur consistently or intermittently? Is there any code you could share to help us identify what may be going wrong? An Xcode project highlighting the issue would go a long way to helping us troubleshoot this with you.

Thanks.

**Comment by Fab1n** [comment]
Thanks for your straight replies. I finally figured it out. And I can say that it works!
Multiprocess support is what we definitely need! As an extension should act on the same database file even when encrypted. 
I'll stay tuned

**Comment by jpsim** [comment]
We're sorry you had difficulty debugging this. We're always after feedback on how to improve our docs so thanks for sharing!

Since learning about your experience, I've drafted an entry to the "Limitations" section of our Objective-C and Swift docs, which is currently pending review.
