### ISSUE TITLE
Update NSFileProtection samples to set attributes on lock files

### ISSUE THREAD

**Issue by kronik** [realm/realm-cocoa#1571]
This issue is very similar to https://github.com/realm/realm-cocoa/issues/1260 . 
Application tries to select data from Realm db when app fetch in background handler is called.

And I

 disabled protection at all:

```objective-c
+ (void)initialize {
    NSError *error = nil;
    NSURL   *fileUrl = [NSURL fileURLWithPath:[RLMRealm defaultRealmPath]];
    
    [fileUrl setResourceValue:@YES forKey:NSURLIsExcludedFromBackupKey error:&error];
    
    [[NSFileManager defaultManager] setAttributes:@{NSFileProtectionKey:NSFileProtectionNone}
                                     ofItemAtPath:[RLMRealm defaultRealmPath]
                                            error:&error];
}

```

tried also with NSFileProtectionCompleteUntilFirstUserAuthentication but still the same.

What I'm doing wrong?

**Comment by kronik** [comment]
I tried to compare behaviour with https://github.com/marcoarment/FCModel and FCModel works fine even in background locked mode.

**Comment by segiddins** [comment]
What sort of error are you seeing when realm crashes? It'd be really helpful if you could share a stack trace!

**Comment by kronik** [comment]
failed to open(). something related with permissions...

**Comment by kronik** [comment]
It seems like NSFileProtectionKey:NSFileProtectionNone needs to be applied to db log file or something else you guys use in addition to main db file.

**Comment by jpsim** [comment]
Hi @kronik, you're right that you'll have to set the `NSFileProtection` file attributes for the lock and log files if you're writing to the realm in the background.

```objc
NSString *pathToRealmFile = [RLMRealm defaultRealmPath];
NSArray *allRealmRelatedFiles = @[
  pathToRealmFile,
  [pathToRealmFile stringByAppendingPathComponent:@".lock"],
  [pathToRealmFile stringByAppendingPathComponent:@".log"],
  [pathToRealmFile stringByAppendingPathComponent:@".log_a"],
  [pathToRealmFile stringByAppendingPathComponent:@".log_b"]
];
for (NSString *path in allRealmRelatedFiles) {
  NSError *error = nil;
  [[NSFileManager defaultManager] setAttributes:@{NSFileProtectionKey: NSFileProtectionNone}
                                   ofItemAtPath:path
                                          error:&error];
}
```

We'll be updating our `NSFileProtection` related samples to reflect this as soon as possible.

**Comment by jpsim** [comment]
That's what we'll do in the short term. However users really shouldn't have to know about all these potential ancillary files so we'll be adding a convenience method like `setFileProtectionKeyForRealmsAtPath:`. We'll track this in a more flexible `RLMConfiguration` in #1584.

**Comment by alazier** [comment]
Lets just do #1584 rather than adding a new global configuration method that we will remove soon after adding.

**Comment by dismory** [comment]
Similarly, do I need to delete all these five files explicitly if I want to delete a Realm?

**Comment by tgoyne** [comment]
If you're just deleting and recreating the Realm file, then no (barring bugs in Realm).

**Comment by dismory** [comment]
If not, will it take more disk space?

**Comment by jpsim** [comment]
This is now documented in https://realm.io/docs/objc/latest/#encryption.
