### ISSUE TITLE
Upsert function?

### ISSUE THREAD

**Issue by acoleman-apc** [realm/realm-cocoa#1573]
Salesforce has a function called UPSERT.   This UPDATEs existing records (if the primary key is found) and INSERTs records where the primary key wasn't found. 

It would be great if Realm had an commit upsert operation.  It would prevent errors like this: RLMException, reason: 'Can't set primary key property

Thoughts?

**Comment by segiddins** [comment]
Such a method already exists, in the form of `-[RLMObject createOrUpdateWithObject]` and -[RLMRealm addOrUpdate]`. I hope that helps!

**Comment by acoleman-apc** [comment]
Thanks for the quick reply.  That method seems interesting and I will look into it but am I correct that it only takes a single object and not an array?  I was hoping to pass in just an array but I guess I can just loop over an array and call this method.  Thanks again for your responsiveness!

**Comment by jpsim** [comment]
> I was hoping to pass in just an array but I guess I can just loop over an array and call this method.

You should loop over. If Realm offered a `createOrUpdateWithObjects:`, it would just loop over the input as well, that's unlikely to happen.
