### ISSUE TITLE
Add createOrUpdateFromArray method to RLMObject

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1574]
That might not be the exact naming, but the idea would be to do upserts given an array of objects

Currently there is an addOrUpdateFromArray http://realm.io/docs/cocoa/0.90.6/api/Classes/RLMRealm.html#//api/name/addOrUpdateObjectsFromArray:

This was brought up here https://github.com/realm/realm-cocoa/issues/1573

**Comment by jpsim** [comment]
It's trivial to loop over an array and call this on its members so I really don't think we should do this. This is also why we have `-[RLMObject initWithObject:]` but not `initWithObjects:`.

**Comment by yoshyosh** [comment]
I think this will make more sense when done on the Realm, that example does make it look a bit weird
