### ISSUE TITLE
Throw an exception when declaring a nested RLMObject subclass in Swift

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1577]
Adding the code below causes this Assertion failed: top_size>=3 [0, 3]

We should prevent/warn the user about what they are doing

````swift
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        
        class CardDeck: RLMObject {
            dynamic var name = ""
        }
        
        let deck = CardDeck()
        deck.name = "New Deck"
        let realm = RLMRealm.defaultRealm()
        realm.beginWriteTransaction()
        realm.addObject(deck)
        realm.commitWriteTransaction()
        
        return true
    }
````

**Comment by jpsim** [comment]
The problem that's happening here is that `CardDeck` is being defined as a nested class, scoped to `application(application:didFinishLaunchingWithOptions:)`.

Swift's mangling doesn't provide enough information to determine all the details we need from this class when we initialize the schema.

I recall seeing this a few months ago and briefly looking into whether or not we could inform the user of what they were doing wrong, but we clearly didn't find a suitable solution. It's worth looking into it again, though.

**Comment by segiddins** [comment]
We currently only check if a class definition is nested inside another class, clearly we need to also see if the mangled name points to it being nested inside a function, struct, or enum as well.
