### ISSUE TITLE
Result of sort is different from the standard way of Cocoa.

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-cocoa#1578]
It looks like the result of sort is different from the standard way of Cocoa.
**Ampersand "&" and single-quote "'" are exchanged.**

### Steps to reproduce

1. Define brand model class that has only name property, like below:

  ```objc
@interface Brand : RLMObject
@property NSString *name;
@end

@implementation Brand
@end
```

2. Create and save brands to ream
3. fetch and sort the brand from realm like below:

  ```objc
  NSArray *brandNames = @[@"08 sircus", @"'PalinkA", @"A.I.C", @"&byP&D", @".efiLevol"];

  RLMRealm *realm = [RLMRealm defaultRealm];
  [realm transactionWithBlock:^{
      for (NSString *brandName in brandNames) {
          Brand *brand = [[Brand alloc] init];
          brand.name = brandName;
        
          [realm addObject:brand];
      }
  }];

  RLMResults *sortedBrands = [[Brand allObjects] sortedResultsUsingProperty:@"name" ascending:YES];
  for (Brand *brand in sortedBrands) {
      NSLog(@"%@", brand.name);
  }
```

3. Output is:

  ```
'PalinkA
&byP&D
.efiLevol
08 sircus
A.I.C
```

4. But if use `NSArray#sortedArrayUsingDescriptors:` like below:

  ```objc
  NSMutableArray *brands = [[NSMutableArray alloc] init];
  for (NSString *brandName in brandNames) {
      Brand *brand = [[Brand alloc] init];
      brand.name = brandName;
    
      [brands addObject:brand];
  }

  NSArray *sorted = [brands sortedArrayUsingDescriptors:@[[NSSortDescriptor sortDescriptorWithKey:@"name" ascending:YES]]];
  for (BrandObject *brand in sorted) {
      NSLog(@"%@", brand.name);
  }
  ```

5. Output is:

  ```
&byP&D
'PalinkA
.efiLevol
08 sircus
A.I.C
```

### Results
When use Realm, single-quote is put **before** ampersand.
When use `NSArray#sortedArrayUsingDescriptors:`, single-quote is put **after** ampersand.

Is this in the specifications?

### Environment
Realm: 0.90.6
Xcode: Version 6.1.1 (6A2008a)
OS X: 10.10.2 (14C109)

**Comment by rrrlasse** [comment]
It's true that there are differences in sorting compared to Cocoa.

This is because we are using a fixed lookuptable so that sorting yields the same order regardles of operating system, development framwork and country (locale).

We are working on a feature that lets you cusomize all such settings, e.g. sort according to Cocoa, as you request.

**Comment by kishikawakatsumi** [comment]
Thanks.

> We are working on a feature that lets you cusomize all such settings, e.g. sort according to Cocoa, as you request.

Sounds good.
