### ISSUE TITLE
transaction exception message when removing object from realm

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1579]
This is coming from https://secure.helpscout.net/conversation/76155296/628/, he accidentally was trying to remove an object that didn't exist in the realm. Turns out he was doing it from the wrong realm. Maybe there's a way to warn the user somehow?

**Comment by segiddins** [comment]
We should really just validate that the realm you're deleting from is the same realm the object belongs to.

**Comment by tgoyne** [comment]
We do validate that on master.
