### ISSUE TITLE
Rename initWithObject/createWithObject to withValue

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1585]
We need to make this change in objective-c to be consistent with the new swift apis and to make things more clear/less confusing. 

This change should be made once al-swift is merged to master, at which point in time we can fix Object.init(object:)

Old api calls should be deprecated for a few releases.

**Comment by segiddins** [comment]
This was started in `set-with-value`, but a swift compiler error is preventing the Realm tests from compiling.
