### ISSUE TITLE
Support Carthage prebuilt framework

### ISSUE THREAD

**Issue by l4u** [realm/realm-cocoa#1595]
Please add `Realm-cocoa.framework.zip` in releases, so that Carthage can pull from prebuilt binaries instead of building it from source.

**Comment by jpsim** [comment]
Thanks for the feature request, @l4u. We'll update this issue once we've updated our release scripts to do this.

**Comment by timanglade** [comment]
For our first swift release, we will manually upload a prebuilt framework to our Github releases.

**Comment by jpsim** [comment]
If you specify `github "realm/realm-cocoa" ~> 0.92` in your Cartfile, it'll download the prebuilt Realm Objective-C and Swift frameworks from our [v0.92.0 release](https://github.com/realm/realm-cocoa/releases/tag/v0.92.0).
