### ISSUE TITLE
Swift documentation for ordering result is incorrect

### ISSUE THREAD

**Issue by selwin** [realm/realm-cocoa#1596]
Realm.io's Swift [documentation](http://realm.io/docs/cocoa/0.91.0/) for ordering results still uses `arraySortedByProperty` instead of `sortedResultsUsingProperty`

**Comment by kishikawakatsumi** [comment]
Thank you for reporting this issue. We will fix it soon.

**Comment by kishikawakatsumi** [comment]
Fixed http://realm.io/docs/cocoa/
