### ISSUE TITLE
RLMException when calling callback closure

### ISSUE THREAD

**Issue by attheodo** [realm/realm-cocoa#1609]
I was wondering if anyone can help with this http://stackoverflow.com/questions/28994363/rlmexception-when-calling-callback-closure

Full stack-trace dump here: http://pastie.org/10019692

**Comment by jpsim** [comment]
What does your `handler` block look like? Since that's where Realm is throwing, I'd expect there to be some Realm-related methods being called in there expecting a different thread.

**Comment by attheodo** [comment]
Here's the part with the `handler` block being utilized:
```
let channelName = message.channel
                
PSTChatHelpers.placeNameForChatChannel(channelName) { placeName in
                
      if let placeName = placeName {
                        
             let notificationMessage = "\(placeName): \(message.text)"
                        
             NSNotificationCenter.defaultCenter().postNotificationName(
                     kPestoNotificationDidReceiveMsgInOtherChannel,
                     object: self,
                     userInfo: ["messageBody": notificationMessage]
            )

     }
```

**Comment by jpsim** [comment]
This code looks fine to me. Is there any way you could share a full code sample or Xcode project that can fully reproduce the issue? You can always email us code privately at help@realm.io.

**Comment by segiddins** [comment]
Responded via email.
