### ISSUE TITLE
Equivalent “completion handler” from MagicalRecord to Realm.io

### ISSUE THREAD

**Issue by mhergon** [realm/realm-cocoa#1610]
Hi,

I searched for a many days, but I can not find it. What would be the equivalent of the following MagicalRecord statement in Realm.io?

```objc
[MagicalRecord saveUsingCurrentThreadContextWithBlock:^(NSManagedObjectContext *localContext) {

    // Save block

} completion:^(BOOL success, NSError *error) {

    // Completion block

}];
```

I need "Save block", and when it finish, execute "Completion block"

Thanks!!

**Comment by jpsim** [comment]
Hi @mhergon, the equivalent in Realm is [`-[RLMRealm transactionWithBlock:]`](http://realm.io/docs/cocoa/api/Classes/RLMRealm.html#//api/name/transactionWithBlock:).

Since both your MagicalRecord example and Realm's equivalent run in the current thread, the completion block is a bit redundant because it's equivalent to adding code immediately after the call to this method.

**Comment by mhergon** [comment]
And which one is more correct?

```objc
// Save
RLMRealm *realm = [RLMRealm defaultRealm];
[realm transactionWithBlock:^{
    
    User *user = [User new];
    user.userName = "name!!!";
    
    if (completion) {
        completion();
    }
    
}];
```
or...
```objc
// Save
RLMRealm *realm = [RLMRealm defaultRealm];
[realm transactionWithBlock:^{
    
    User *user = [User new];
    user.userName = "name!!!";
    
}];

if (completion) {
    completion();
}
```


Thanks!!

**Comment by jpsim** [comment]
It depends what you want to do in your completion block. The first version will run before the transaction is committed (persisted to the database), the second version will run after. Both versions will have access to the changes in the transaction as long as you stay on the same thread. In the second version, the transaction changes will be available from all threads.

**Comment by jpsim** [comment]
Basically, the second version is safer.

**Comment by mhergon** [comment]
@jpsim Thanks thanks thanks! I will appreci

**Comment by wgywgy** [comment]
if (completion) {
}

and completion value?

**Comment by mhergon** [comment]
@wgywgy Yes, it's a block!
