### ISSUE TITLE
Move subscripting out of RLMObjectBase

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#1613]
This will allow for better types in swift 1.2

**Comment by JadenGeller** [comment]
It's not clear to me why this is necessary. Could you elaborate @segiddins?

**Comment by segiddins** [comment]
@JadenGeller it appears I did this in https://github.com/realm/realm-cocoa/pull/1631

**Comment by JadenGeller** [comment]
Yes, I see. I was wondering the motivation. I was just thinking it would be nice to consolidate this logic, but noticed in the blame that it was intentionally moved out of `RLMObjectBase`. It's not obvious to me how this allows for better types in Swift.

**Comment by segiddins** [comment]
I think it might've been so that the key could be `String` instead of `AnyObject` but don't quote me on that

**Comment by JadenGeller** [comment]
That was likely it. It was marking as `id<NSCopying>`, but I think that was changed. Is there any reason subscript was marked `id<NSCopying>`? Want to make sure I didn't break anything with that change.

**Comment by segiddins** [comment]
It might've been a limitation in the swift objc importer, but you'd have to grab an old Xcode to verify.

**Comment by JadenGeller** [comment]
Maybe. Not necessary to verify historical motivation; just making sure it wasn't something important I overlooked 👍
