### ISSUE TITLE
Allow for optionals in Swift

### ISSUE THREAD

**Issue by petaren** [realm/realm-cocoa#1614]
I would like to be able to use optionals in my model like such:

```swift
class Person: RLMObject {
    dynamic var name: String?
    dynamic var age: Int?
}
```

Right now that isn't possible because an objc (c) int cannot be null/nil. But I bet you can fix that! :)

A possible solution would be to allow for the use of NSNumber.

**Comment by yoshyosh** [comment]
We are working on null support, but unfortunately can't support optionals at this moment. We also don't support native types to help keep the data universal to work cross platform. We are aware and you will be sure to know if this ever changes!

Null support will be coming soon :)

**Comment by jpsim** [comment]
Until we support null values, depending on your use case, you could work around this in a number of ways.

The most flexible one is likely to wrap nullable properties in RLMObjects:

```swift
class StringObject: RLMObject {
    dynamic var string = ""
}

class Person: RLMObject {
    var name: String? {
        get {
            return backingName?.string
        }
        set {
            if let newValue = newValue {
                if backingName == nil {
                    backingName = StringObject()
                }
                backingName?.string = newValue
            } else {
                backingName = nil
            }
        }
    }
    dynamic var backingName: StringObject? = StringObject()
}
```

**Comment by petaren** [comment]
Thank you for your comments! :+1: on null support!

**Comment by bryan1anderson** [comment]
is there an update? It's been several months since the answer so I'm wondering if "Coming Soon" already came? :)

**Comment by tgoyne** [comment]
We now have [beta support for optional strings and data properties](https://github.com/realm/realm-cocoa/issues/628#issuecomment-106952727), and your help testing it would be greatly appreciated. Support for other types will come after that's done.

**Comment by bryan1anderson** [comment]
@tgoyne is it available for Swift? I noticed the podfile referenced is pod 'Realm', not pod 'RealmSwift'

**Comment by bryan1anderson** [comment]
@tgoyne Ok thanks!
