### ISSUE TITLE
Unable to query database using double precision

### ISSUE THREAD

**Issue by pronebird** [realm/realm-cocoa#1633]
Hi,

I am trying to use Realm to store geo location and data associated with it. I use two double columns, latitude and longitude. 

This is my model:

```objc
@interface LocationRecord : RLMObject

@property double latitude;
@property double longitude;
@property NSData* placemarkData;

@end

@implementation LocationRecord

- (CLPlacemark *)placemark {
    CLPlacemark* placemark;
    
    @try {
        placemark = [NSKeyedUnarchiver unarchiveObjectWithData:self.placemarkData];
    }
    @catch(NSException* e) {
        NSLog(@"NSKeyedUnarchiver exception: %@", e);
    }
    
    return placemark;
}

@end
```

I query db for records but it never returns any results:

```objc
CLLocation* location; // comes from somewhere
RLMResults* results = [LocationRecord objectsWhere:@"latitude = %f and longitude = %f", location.coordinate.latitude, location.coordinate.longitude];
LocationRecord* cachedRecord = results.firstObject; // always nil
```

This is how I save model into Realm:

```objc
LocationRecord* record = [LocationRecord new];
        
record.latitude = location.coordinate.latitude;
record.longitude = location.coordinate.longitude;
        
[[RLMRealm defaultRealm] transactionWithBlock:^{
    [LocationRecord createInDefaultRealmWithObject:record];
}];
```

Realm browser shows that records are saved, however it also shows that float was used to store columns with double precision.

**Comment by segiddins** [comment]
@pronebird could you please share your model definition for `LocationRecord`?

**Comment by pronebird** [comment]
@segiddins Hi, I've updated my post. I tried to use float instead of double but without any success.

**Comment by pronebird** [comment]
NSLog in console:

```
Query location = { 28.048520, -14.333117 }
```

What's in DB:
![screenshot 2015-03-14 18 07 15](https://cloud.githubusercontent.com/assets/704044/6652615/fb53e41a-ca74-11e4-823d-1e5c10319b24.png)

**Comment by pronebird** [comment]
Wiped DB and re-tested, it seems to work with FLOAT fields.

**Comment by jefferybradley** [comment]
I have encountered this same problem, only with NSTimeInterval values instead of Double.

When my model stored NSTimeInterval values, my queries returned 0 search results.  Changing the model to Double still yielded no results.  But changing the model to Float did finally returned the expected number of results.

**Comment by pronebird** [comment]
@jefferybradley NSTimeInterval is a double.

**Comment by jefferybradley** [comment]
I know.  Just reporting the issue.  Thanks!

**Comment by segiddins** [comment]
@pronebird and @jefferybradley, a project that reproduces the query issues you were experiencing would be very helpful in tracking down the issue. You can send a project to help@realm.io if you'd prefer to keep things private. Thanks!

**Comment by pronebird** [comment]
@segiddins here you go https://github.com/pronebird/RealmDoubleBug/blob/master/RealmDoubleBug/ViewController.m#L25

Couple of observations:

1. FLOAT fields work
2. Wrapping doubles in `NSNumber` and using `%@` instead of `%f` in predicate format helps to resolve the issue.

I've tested everything on iOS 8.2 simulator / iPhone 5.

**Comment by jpsim** [comment]
Note that this is not a Realm-specific problem. What's happening here is that you're casting a double as a float, which causes the equality to fail. This is why you should always avoid checking equality with floating-point types.

If you're absolutely sure that the values won't change even slightly, you could use `%lf` for direct equality:

```objc
RLMResults* results = [LocationRecord objectsWhere:@"latitude = %lf and longitude = %lf", location.coordinate.latitude, location.coordinate.longitude];
```

but you'll likely be better off by doing a range comparison:

```objc
double lat = location.coordinate.latitude;
double long = location.coordinate.longitude;
double epsilon = 0.001;
RLMResults* results = [LocationRecord objectsWhere:@"latitude > %lf AND latitude < %lf AND longitude > %lf AND longitude < %lf", lat - epsilon, lat + epsilon, long - epsilon, long + epsilon];
```

**Comment by pronebird** [comment]
Thanks for explanation. I use Realm as caching layer so I want to receive the same results back for the same input, values don't change, deviation should produce different set of results. 

According to docs %f should work for 64-bit floating point (double) when formatting, but there are special considerations for scanning.

https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html

**Comment by jpsim** [comment]
Regardless of those docs, a double will not be accurately represented by `%f`. See this playground demonstrating this behavior:

![image](https://cloud.githubusercontent.com/assets/474794/6835751/051368a8-d2fa-11e4-953e-343aab71a277.png)

**Comment by pronebird** [comment]
@jpsim thanks again.

**Comment by segiddins** [comment]
Additionally, the docs you linked to are for _creating_ strings from a format string, and `predicateWithFormat:`  follows slightly different rules.
