### ISSUE TITLE
Is objectsWhere no longer available?

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1636]
I just updated to 0.91.1 and now I am getting many errors. One of the errors is saying that I can't use objectsWhere. objectsWithPredicate seems to be available. Here are some screen shots.

![screen shot 2015-03-16 at 7 03 23 am](https://cloud.githubusercontent.com/assets/1189875/6665729/dcf789ea-cbaa-11e4-898b-c7701eb2fbef.png)
![screen shot 2015-03-16 at 7 04 29 am](https://cloud.githubusercontent.com/assets/1189875/6665732/e40e600a-cbaa-11e4-810d-9e0fb009cfd1.png)

**Comment by jpsim** [comment]
Are you linking `Swift/RLMSupport.swift`? `objectsWhere()` is defined there, while `objectsWithPredicate()` is defined in `Realm.framework` so it could explain why you can only find the latter.

**Comment by webmagnets** [comment]
No, I wasn't. Thanks for your help.
