### ISSUE TITLE
Collection was mutated while being enumerated

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#1643]
Hey guys,

with the most recent update of Realm for iOS I noticed that I sometimes get a "Enumeration was mutated while being enumerated". I know where this originates from and totally agree with that exception but nevertheless I can't seem to figure out how to update a given set of objects anymore. Until this release I used to do it like this:

``` 
RLMResults* myResults = [MyObject objectsWhere:...];
            for (MyObject* object in myResults) {
                object.aProperty = aValue;
            } 
```

Any ideas on that one?

**Comment by jpsim** [comment]
Hi @tspecht, whenever mutating an `RLMResults` while enumerating, you should use a `while` loop to only operate on the remaining objects. For example:

```objc
RLMResults* myResults = [MyObject objectsWhere:...];
while (myResults.count > 0) {
  MyObject *firstObject = myResults.firstObject;
  firstObject.aProperty = aValue;
}
```

We have an issue open to freeze `RLMResults` during each runloop iteration which would simplify this pattern: #1179.

**Comment by tspecht** [comment]
But this would only change the first object in my results, right? How would I change *every* object in my result set?

**Comment by jpsim** [comment]
No, this would change every object in your results. Not that it's a `while` loop, not an `if` statement.

**Comment by tspecht** [comment]
But wouldn't -firstObject always return the same object since the result set is not changed?

**Comment by jpsim** [comment]
Let's use a more concrete example to demonstrate how this technique can be used:

```objc
RLMResults* myResults = [MyObject objectsWhere:@"boolProp == NO"];
while (myResults.count > 0) { // This expression is evaluated at the start of every iteration
  MyObject *firstObject = myResults.firstObject; // This is guaranteed to be non-null because of the above expression
  firstObject.boolProp = YES; // This makes firstObject no longer match the results query, so the results shrink by one member. Eventually, this will be the last object, at which point the expression in the while loop will be false and we'll exit
}
```

**Comment by tspecht** [comment]
Yeah I got that point. The only problem is, I'm not changing the property that was filtered on in the for-loop but some other one ...

**Comment by jpsim** [comment]
Ah, I see. So instead, you shouldn't use NSFastEnumeration, but rather just a regular for loop, iterating over the indexes.

```objc
RLMResults* myResults = [MyObject objectsWhere:...];
for (int i = 0; i < myResults.count; i++) {
    MyObject* object = myResults[i];
    object.aProperty = aValue;
} 
```

This will be safe as long as you're not mutating the number or order of objects in the results.
