### ISSUE TITLE
Loss of information when objects are retrieved from a realm

### ISSUE THREAD

**Issue by yujuncho7** [realm/realm-cocoa#1653]
I have an issue while dealing with models that inherit from each other and are saved in separate realms. After creating a RLMObject, retrieving the object produces unexpected behavior. The object exists and executing print(object.description) works; however simply calling print(object) does not work. Another odd outcome is that after casting the object from AnyObject to my model class, the _deletedFromRealm variable switches from NO to YES. Lastly, the information that is supposed to persist, is no longer available. Although, this information is seen in print(object.description).

More information and code that replicates the issue can be found <a href="https://github.com/yujuncho7/realm-issue">here</a>

**Comment by segiddins** [comment]
This is a known bug with trying to print out an RLMObject subclass directly -- Swift does not play nicely with the `description` method being implemented in Objective-C. This issue is resolved with our new set of Swift APIs.
