### ISSUE TITLE
Associated object via json not saving?

### ISSUE THREAD

**Issue by BeamerCola** [realm/realm-cocoa#1654]
I have some pretty basic code, but my associated objects are saving the ids, but no attributes.

It's strange the ids work.  Also, i tried removing the default values.  And only stored lastName (Which guaranteed all artists have) - and it gave me error inserting null lastName

Sample JSON from AFNetworking
```
{
            id = 271;
            title = "Papago Wine Basket";
            artist =             {
                "first_name" = Leonard;
                id = 87;
                "items_count" = 4;
                "last_name" = Wren;
                "middle_name" = "<null>";
            };
        }
```

Sample models
```
@interface Item : RLMObject
@property NSInteger id;
@property NSString *title;
@property Artist *artist;
@end

@interface Artist : RLMObject
@property NSInteger id;
@property NSString *firstName;
@property NSString *middleName;
@property NSString *lastName;
+ (NSDictionary *)defaultPropertyValues
{
    return @{
             @"firstName": @"",
             @"middleName": @"",
             @"lastName": @""
             };
}
@end
```

```
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        for (NSDictionary *item in JSON[@"items"]) {
            [Item createOrUpdateInDefaultRealmWithObject:item];
        }
        [realm commitWriteTransaction];
```

After saving all my Artist objects look like:
```
Artist {
	id = 67;
	firstName = ;
	middleName = ;
	lastName = ;
}
```

**Comment by segiddins** [comment]
How is `createOrUpdateInDefaultRealmWithObject:` even working, given that neither of your model objects has primary keys defined?

**Comment by BeamerCola** [comment]
I'm sorry, they both have:
```
+ (NSString *)primaryKey
{
    return @"id";
}
```

Just left that out

**Comment by segiddins** [comment]
Just had another look at your code, and the issue is that the keys in your JSON payload and the properties on your object don't match -- you have `snake_case` in JSON and `camelCase` in Obj-C -- you'll need to manually map those key paths, or use a tool like Realm-JSON or RestKit to do it for you. I hope that helps!
