### ISSUE TITLE
Unable to load string table file after upgrading to 0.91.1

### ISSUE THREAD

**Issue by yasirmturk** [realm/realm-cocoa#1655]
Unable to load string table file: CFBundle 0x134d4c6d0 </private/var/mobile/Containers/Bundle/Application/724C1EBF-949C-4A98-8C7A-FED28BD3AC14/mobilmaegler.app> (executable, loaded) / Main: The operation could not be completed. (Cocoa error 3840.)

**Comment by jpsim** [comment]
Hi @yasirmturk, I doubt this is a problem with Realm. The string table file is a localized strings file, often used by storyboards even when not directly creating multiple localizations.

See this StackOverflow post for details: http://stackoverflow.com/questions/27222001/cfbundle-runtime-error-what-does-this-mean

So I'd recommend you diff your project file to see where changes may have happened.
