### ISSUE TITLE
Equivalent query MagicalRecord -> Realm.io

### ISSUE THREAD

**Issue by mhergon** [realm/realm-cocoa#1656]
Does anyone know if there is an equivalent expression in Realm.io for this query? I need results grouped by "dreamDate" property

```objc
// Search all dreams grouped by date
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"user == %@ AND parseSyncDeleted == false", user];
    
NSFetchedResultsController *groups = [Dream MR_fetchAllGroupedBy:@"dreamDate.dateWithoutTime"
                                                       withPredicate:predicate
                                                            sortedBy:@"dreamDate"
                                                           ascending:YES];
    
return groups;
```
**dreamDate** -> NSDate property
**dateWithoutTime** -> Category that converts it to NSDate without time components

Thanks!

**Comment by jpsim** [comment]
Realm doesn't have a built-in data structure to group results, but you can do this very easily *and* efficiently by holding an NSArray or NSDictionary of RLMResults. Please see our GroupedTableView for an example of how to do this: https://github.com/realm/realm-cocoa/blob/master/examples/ios/objc/GroupedTableView/TableViewController.m

**Comment by mhergon** [comment]
Yes! Finally I created a NSDictionary with NSDate as keys.

Thanks!
