### ISSUE TITLE
Reference cycle in one of the examples

### ISSUE THREAD

**Issue by khanov** [realm/realm-cocoa#1658]
Hi! 

I think [one of the examples](https://github.com/realm/realm-cocoa/blob/master/examples/ios/swift/TableView/TableViewController.swift#L40) has a reference cycle.

    class TableViewController: UITableViewController {

        var notificationToken: RLMNotificationToken?

        override func viewDidLoad() {
            // Set realm notification block
            notificationToken = RLMRealm.defaultRealm().addNotificationBlock { note, realm in
                self.tableView.reloadData()
            }
            ...
        }
    }

The block above captures a strong reference to `self`, which is then stored in RLMNotificationToken:

    @interface RLMNotificationToken ()
    @property (nonatomic, copy) RLMNotificationBlock block;
    @end

And the TableViewController stores RLMNotificationToken in the `notificationToken` property.

So that creates a reference cycle: 
`self.notificationToken —>  RLMNotificationToken.block —> self`

If I've missed something, please let me know. I'd love to understand how it works :) Thanks!

**Comment by jpsim** [comment]
Thanks for reporting this, @khanov. I've opened a PR to address this.
