### ISSUE TITLE
How can I change my simulator to 64 bit?

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1659]
I am getting the "Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. For sharing files between the Realm Browser and an iOS simulator, this means that you must use a 64-bit simulator." error.

How can I change to the correct simulator?

**Comment by jpsim** [comment]
When running your app in the simulator, make sure you pick either the "iPhone 5s", "iPhone 6" or "iPhone 6 Plus" as the destination.

**Comment by leijing7** [comment]
I still get this error even I choose the iPhone 6, 6s. Can not open the Realm Browser and the app in iOS simulator at the same time.

**Comment by bdash** [comment]
@leijing7, please see #3353 for discussion of a recent issue that would lead to this error. It's likely to be what you're hitting.

**Comment by MrHubble** [comment]
@leijing7 did you fix this?

In the other issue (https://github.com/realm/realm-cocoa/issues/3353), @bdash said:

>Realm v0.98.5, used by Realm Browser v0.98.5, included a change to the format of the lock file. As your application is using an older version of Realm you'll need to use a corresponding version of the Browser that expects the older lock file format. You can find older versions on the Realm Browser's releases page.

I updated to the latest version of Realm Javascript (1.2.0) which uses `REALM_CORE_VERSION=2.5.1`, which is the same as Realm Browser so I should no longer see this error.
