### ISSUE TITLE
'Realm is not a dylib' warning in Test Environment

### ISSUE THREAD

**Issue by floriankrueger** [realm/realm-cocoa#1661]
I have this warning in my XCTest target and can't get rid of it. This is most definitely a trivial thing but I'm stuck right now:

```
ld: warning: Auto-Linking supplied '/path/to/xcode/project/Realm.framework/Realm', framework linker option at /path/to/xcode/project/Realm.framework/Realm is not a dylib
```

I'm using Xcode 6.2 (6C131e), the iOS SDK 8.2, my Deployment Target is 7.0

The warning only exists in the test target, not in the app target(s). Any idea?

**Comment by jpsim** [comment]
How did you install Realm? Are you using CocoaPods, Carthage, a prebuilt framework or building from source?

Is it possible you've linked `Realm.framework` to your test target, instead of just your app/framework target? As we briefly mention in the ["Testing Realm Apps"](http://realm.io/docs/cocoa#testing-realm-apps) section of our docs, this can lead to some unwanted behavior and should be avoided.

**Comment by floriankrueger** [comment]
Oh yeah, I forgot to add this: I've installed Realm manually as installation w/ Cocoapods leads to the "module Realm not found" error. And no, I haven't linked Realm to my test target.

I also tried removing Realm completely from the project and re-adding it, but nothing changed.

**Comment by jpsim** [comment]
So I assume you're using Realm in a Swift project then?

This warning might be happening if you've accidentally linked some tests files to your app target, or app files to your test target. Can you check if that's the case here?

**Comment by floriankrueger** [comment]
It's a Mix and Match project actually and I double checked that there are only test classes linked to the test target. Anything else that I might try to solve this?

**Comment by jpsim** [comment]
Could you share your project with us? I could troubleshoot it if I had access. Otherwise, I'd say try setting up a new, minimal project with Realm including tests and comparing the projects' configurations might help identify what's causing this.

**Comment by floriankrueger** [comment]
Hi JP, sorry for the delay. We tried to reproduce the problem in a separate project but couldn't. In the end, we added the `Realm.framework` and the `libc++.dylib` to the test target explicitly and the warning is gone. However, we didn't need to do this in our tests and we never saw the warning except in our main project (which we unfortunately can't share w/ you).

Anyways, thank you for your help. If I'll ever get to know what the problem is I'll post it here.

**Comment by jpsim** [comment]
> we added the Realm.framework and the libc++.dylib to the test target explicitly and the warning is gone. However, we didn't need to do this in our tests and we never saw the warning except in our main project

It really sounds like you have some test files linked to your main target if you added Realm to your test target and it fixed warnings in the main target. Linking both targets could lead to some surprising test failures since your model classes could be duplicated.

**Comment by floriankrueger** [comment]
@jpsim not sure if I understood you correctly but we had the warnings in the *test* target and adding the realm framework to the *test* target fixed the warning. I double-checked that there are no test files linked to the main target and no files from the main target linked to the test target.

**Comment by jpsim** [comment]
Alright, I see what you mean. I'm happy you managed to fix it.
