### ISSUE TITLE
Update Carthage, it's using an outdated version of core

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1664]
We need to update what Carthage installs. Currently a user is seeing 0.88.1 for core rather than 0.88.5 w/ the latest 0.91.1 release https://github.com/realm/realm-cocoa/issues/1663

**Comment by segiddins** [comment]
Carthage should just be running the Download Core build phase of the dynamic framework target, right?

**Comment by jpsim** [comment]
Your assessment of this issue isn't quite right. I just did a quick check with the following contents of my `Cartfile`: `github "realm/realm-cocoa" >= 0.91` and it built v0.91.1 with core 0.88.5.

So maybe it's an issue with *updating* a Carthage project? I'll look into it.

**Comment by jpsim** [comment]
Updating Realm (`~> 0.90` to `~> 0.91`) using Carthage just worked for me without problem, using the correct version of core. However, the old core folders still stick around in the `Carthage/Checkout` directory.

**Comment by segiddins** [comment]
Since @jpsim can't reproduce this, can we close the issue for now?
