### ISSUE TITLE
dyld error when linking with RealmSwift

### ISSUE THREAD

**Issue by exsortis** [realm/realm-cocoa#1681]
I have an iOS project that is pure Swift. I have added RealmSwift.xcodeproj as a subproject to it, and added it to the link phase. When the app starts via Xcode build and run, whether in the simulator or on a device, the following error occurs:

```
dyld: Library not loaded: @rpath/Realm.framework/Realm
```

My resolved LD_RUNPATH_SEARCH_PATHS is:
```
@executable_path/Frameworks
@loader_path/Frameworks
@executable_path/Frameworks
```

I have verified that RealmSwift.framework is copied to the app's Frameworks folder, and that Realm.framework is also inside the RealmSwift.framework's Frameworks folder.

**Comment by exsortis** [comment]
Note that if I manually copy Realm.framework into the app's Frameworks folder, the app starts without issue.

**Comment by segiddins** [comment]
It sounds like our fiddling with the runtime search paths of `RealmSwift` to look for the vendored `Realm.framework` isn't working. 
@exsortis thanks for trying RealmSwift out! It's not yet released, so this feedback is incredibly valuable to us!

**Comment by alazier** [comment]
I tried to reproduce using the following steps:
1. Create new swift project
2. Drag in RealmSwift.xcodeproj
3. Add the iOS RealmSwift framework to Link Libraries phase
4. Add new Copy Files phase to Frameworks and add the iOS RealmSwift framework

Everything builds and runs fine for me when following these steps. Are you doing something differently? if not Is there anyway you can share your project so we can try to debug it?

**Comment by jpsim** [comment]
Once RealmSwift is officially released, please let us know if you still have issues after following our official installation instructions (we have yet to write them).

**Comment by mahesh46** [comment]
follow these steps

in link binary libraries

add libc++.dylib
copy realm.framework and realm swift.framework to project


in  build settings press + in top left corner
select new copy file phases

now in the copy files
change destination resource  to framework
+ add items   realm.framework and realm swift.framework

**Comment by kiritmodi2702** [comment]
See this one : http://iosdevcenters.blogspot.in/2015/12/realm-error-dyld-library-not-loaded.html

**Comment by SeanZK** [comment]
Please send the realm.  framework  from the Embedded Binaries to join ，then clean and run
