### ISSUE TITLE
Realm Swift API

### ISSUE THREAD

**Issue by AJ1310** [realm/realm-cocoa#1682]
Some time ago, it was mentioned that there was being planned a Swift API of Realm that would adjust a little better to the features of the language. Is there anything that can be disclosed about the current state of the API, or what things are expected to change in a general way?

**Comment by segiddins** [comment]
@AJ1310 we actually just merged RealmSwift into master in the last week, so feel free to check it out! In short, it provides all the functionality of Realm, but in a way that fits in more naturally with the Swift language.

**Comment by AJ1310** [comment]
Is there any plan on the future of this API to provide functionality for Swift components like: struct, enum, options and such?

**Comment by segiddins** [comment]
Unfortunately, the swift runtime is lacking some of the functionality we'd need to support structs and enums alongside classes, so at the moment only directly storing objects will be supported.

**Comment by AJ1310** [comment]
Ok thanks a lot for the info. Glad it's possible in the future to be implemented and looking forward to it.
