### ISSUE TITLE
Error installing Realm with CocoaPods

### ISSUE THREAD

**Issue by beowulfdk** [realm/realm-cocoa#1683]
I alway get this error when trying to install Realm with CocoaPods.
My XCode version is 6.2 but it didn't work with 6.1.1 either.

```
Installing Realm (0.91.1)
[!] /bin/bash 
set -e
sh build.sh cocoapods-setup
: command not found
: command not found
: invalid option namet: pipefail
: invalid option4: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
```

Installing other cocoapods (like AFNetworking) works fine

**Comment by segiddins** [comment]
What version of CocoaPods are you running?

**Comment by beowulfdk** [comment]
I'm running the latest version of cocoapods 0.36.0, but the problem also existed with the previous version 0.35.0

**Comment by segiddins** [comment]
I can't seem to reproduce this particular error... Does it happen consistently for you?

**Comment by beowulfdk** [comment]
Yes, I have tried it several times to install it also with other projects and I always get this error.

**Comment by jpsim** [comment]
Realm uses Bash's `set -o pipefail` as part of its installation script, which was introduced in Bash 3.0 (released 10 years ago). So I doubt that this is failing because your bash version is too old.

Is it possible that you have a custom shell installed (zsh, fish, etc) and that the Realm installation script is using that shell instead of system bash?

**Comment by segiddins** [comment]
Also, what is the output of `which sh` on your machine?

**Comment by beowulfdk** [comment]
No I'm using the original shell installed with the system 
bash-3.2$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.

bash-3.2$ which sh
/bin/sh

**Comment by jpsim** [comment]
I'm at a loss for other possible causes of this problem. Are there any other aspects of your system's configuration that you feel may be relevant? OS version, ruby version, etc? We won't be able to fix this until we can reproduce it on some machine where we can troubleshoot.

**Comment by segiddins** [comment]
@beowulfdk I'm going to close out this issue, since we haven't been able to reproduce the issue nor have we seen other reports of this happening. If there's any further information that might help us track this down, we'll re-open the issue. Thanks!

**Comment by bzdybowicz** [comment]
I have this is issue with realm 1.1.0
<img width="860" alt="screen shot 2017-01-26 at 14 29 51" src="https://cloud.githubusercontent.com/assets/5787245/22332966/ed12402a-e3d3-11e6-9110-e020c1823783.png">
