### ISSUE TITLE
row accessors can be deallocated on the incorrect thread

### ISSUE THREAD

**Issue by alazier** [realm/realm-cocoa#1684]
It is possible for a row to get deallocated on a different thread from which it is created. This can cause issues as structures used to track accessors for a shared_group can in this case be changed on an incorrect thread possibly causing issues. We need to somehow ensure that row accessors are deallocated on the correct thread, even if the parent objc accessor is deallocated on a different thread.

**Comment by tgoyne** [comment]
We could just call `RLMCheckThread` in `dealloc` since you aren't supposed to pass objects to other threads at all currently. For handover we'll need locks around everything that touches the row accessor linked list (which is not very much).

**Comment by segiddins** [comment]
@tgoyne should this go in the accessor's dealloc or the realm's?

**Comment by tgoyne** [comment]
Accessors being deallocated on the wrong thread is the potentially problematic case.
