### ISSUE TITLE
How to construct the query for this case? 

### ISSUE THREAD

**Issue by dismory** [realm/realm-cocoa#1685]
If I get 2 Realm classes:

```objective-c
@interface Foo : RLMObject

@end

@interface Bar : RLMObject

@property Foo *foo;

@end
```

How can I construct an query to find all `Foo` objects which all `Bar` objects point to.

**Comment by segiddins** [comment]
There's no shorthand way to do this, but the following code snippet should work:

```objc
RLMRealm *realm; // Whatever your Realm is
NSMutableArray *pointedToFoos = [NSMutableArray array];
for (Bar *bar in [Bar allObjectsInRealm:realm]) {
  if (bar.foo) {
    [pointedToFoos addObject:bar.foo];
  }
}
```

**Comment by dismory** [comment]
What if I want to get an instance of <RLMCollection> as a result?

**Comment by segiddins** [comment]
Unfortunately, it's not currently possible to query directly on back links, so there's no way to get an RLMResults of that collection.

**Comment by dmiedema** [comment]
Could you filter the `Bar` objects with an `NSPredicate` where `self.foo != nil`?

**Comment by segiddins** [comment]
Yes, you could.

**Comment by jpsim** [comment]
Given NSPredicate's syntax, it'd be nice to be able to do something like this:

```objc
[[Bar objectsWhere:@"foo != nil"] valueForKey:@"foo"];
```

but we don't currently support that in Realm. But even if that worked, you'd get an `NSArray` of `Foo`s, which wouldn't auto-update.

The best thing you can do now if you need an auto-updating `RLMResults` is to follow @dmiedema's suggestion and query `RLMResults *foos = [Bar objectsWhere:@"foo != nil"]` and every time you need to access a `Foo`, use `((Bar *)foos[index]).foo`.
