### ISSUE TITLE
Support Swift Betas

### ISSUE THREAD

**Issue by timanglade** [realm/realm-cocoa#1689]
We should try to support Swift betas as they happen. After a conversation with @jpsim we propose that master should support the latest stable version of swift, but we could consider adding a long-running branch (“swift-beta”) that has support for the latest beta, at least for a while.
@segiddins @alazier @tgoyne thoughts?

**Comment by rlimberger** [comment]
That sounds like a good plan. Thanks guys.

**Comment by tgoyne** [comment]
A git branch really isn't very suited to keeping an up-to-date long-lived set of changes to another branch. I guess we could set up a Jenkins job to automatically rebase it onto latest master whenever commits are pushed to master, and notify us when manual merge resolution is required.

**Comment by rlimberger** [comment]
i have done an initial quick and dirty port to Swift 1.2 (just so i can continue looking at Realm in context of our app). If you want a pull request, let me know.

https://github.com/rlimberger/realm-cocoa/commit/70daf2b7d8410342e38c595c85f667c8ae0ac9ae

**Comment by timanglade** [comment]
@tgoyne the big advantage of a long-running branch is that it’s easy for us to link to from the docs. I expect many people to want this, and it may be hard for them to find it if it’s not clearly advertised. If you can think of another way, happy to use whatever is easier engineering-wise

@rlimberger thanks for the offer! I’ll let @segiddins @jpsim get back to you on that :)

**Comment by jpsim** [comment]
Thanks for the commit, @rlimberger. We'll be making a `swift-beta` branch in the near future, making sure to avoid force-unwrapping in scenarios where it may fail, using dynamic casting in a safe way and making `assertThrows()` and `Realm().write()` play nicely with `@noescape`.

**Comment by Goles** [comment]
Looking forward to `swift-beta`, thanks for this.

**Comment by rlimberger** [comment]
can we assume that the mr-swift-1.2 branch pretty much takes care of this issue? any ETA on when that might get merged into the master? thanks guys!

**Comment by jpsim** [comment]
We're updating our continuous integration system today to move to Yosemite and Xcode 6.3. We intend to merge mr-swift-1.2 shortly after that.

**Comment by segiddins** [comment]
We've now addressed this by putting both swift versions side-by-side in the repo.
