### ISSUE TITLE
Add section to docs about deleting realm files

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1690]
Realm files should be done when there are no more RLMRealm instances at that path. Not doing this leads to hard to diagnose errors for users (see #1589).

**Comment by tgoyne** [comment]
I think I was previously opposed to it, but I now think that the fact that we legitimately need to document how to delete the Realm file beyond "use the standard library function to delete files" suggests that we do need a helper method for it. With some simple-to-add help from core we could even enforce there being no RLMRealm instances for the given path.

**Comment by yoshyosh** [comment]
agreed, people are already struggling with deleting realm files in its current state using NSFileManager

**Comment by jpsim** [comment]
Done: https://realm.io/docs/objc/latest/#deleting-realm-files
