### ISSUE TITLE
Allow configuring a Realm file to be deleted when a migration is required

### ISSUE THREAD

**Issue by pronebird** [realm/realm-cocoa#1692]
I have a cache storage which is ok to be wiped on schema changes. I don't want to migrate it since it's transitory anyway. Is there any way to nuke my realm when schema inconsistency found? This would also help a lot during development when schema changes occur pretty often.

I found a workaround but that requires a version bump, which I can probably simulate by using bundle version. What would be the official way? :)

```objc
#import <Realm/RLMObjectSchema.h>

[RLMRealm setSchemaVersion:1 forRealmAtPath:realmPath withMigrationBlock:^(RLMMigration *migration, NSUInteger oldSchemaVersion) {
    for(RLMObjectSchema *objectSchema in migration.oldSchema.objectSchema) {
        [migration enumerateObjects:objectSchema.className block:^(RLMObject *oldObject, RLMObject *newObject) {
            [migration deleteObject:newObject];
        }];
    }
}];

RLMRealm  *cleanAndTidy = [RLMRealm realmWithPath:realmPath];
```

The better option I found is to nuke realm when things go south:

```objc
#import <Realm/RLMConstants.h>

static void RLMCleanupFiles(NSString *path) {
    // delete files starting with xxx.realm* name
}

@try {
    cacheRealm = [RLMRealm realmWithPath:realmPath];
}
@catch(NSException *exception) {
    NSLog(@"Caught exception while opening Realm: %@", exception);
    
    if([exception.name isEqualToString:RLMExceptionName]) {
        RLMCleanupFiles(realmPath);
        cacheRealm = [RLMRealm realmWithPath:realmPath];
    }
    else {
        @throw; // rethrow
    }
}
```

**Comment by segiddins** [comment]
@pronebird we're going to be introducing the concept of an [`RLMConfiguration`](https://github.com/realm/realm-cocoa/issues/1584) that will likely give you the ability to specify a "delete if migration needed" option. Until then, I can't really think of a great way to do this in Swift.

**Comment by alazier** [comment]
I'm not sure I like the idea of specifying this in `RLMConfiguration`. I think in this case it might be nice to add a new method `-clearRealm` to the RLMMigration object.

**Comment by jpsim** [comment]
> I think in this case it might be nice to add a new method `-clearRealm` to the RLMMigration object.

That would require increasing the schema version and defining a migration block, which I don't think would serve the needs prompting users to ask for this.

As much as I'd like to discourage the behavior of deleting realms on schema mismatch, the truth is that users are already finding hacky and dangerous ways to do this (try/catch block around first `RLMRealm` access). Maybe we should instead publicly expose something like `+[RLMRealm requiresMigrationAtPath:encryptionKey:error:]`.

**Comment by drn** [comment]
I was running into the same problem in development and came up with a roundabout solution.

Though not officially supported in Swift, you can catch objc exception by doing something like this:
```objc
//
//  ThanxRSA.h
//  Thanx
//
//  Created by Darren Cheng on 11/12/14.
//
//

#import <Foundation/Foundation.h>

@interface ThanxRSA : NSObject

+(NSString *)encrypt:(NSString *)plainTextString publicKeyFilepath:(NSString*)filepath;
+(NSString *)encrypt:(NSString *)plainTextString publicKeyString:(NSString*)publicKeyString;
+(NSString*)decrypt:(NSString*)cipherString privateKeyFilepath:(NSString*)filepath password:(NSString*)password;

@end
```
```objc
//
//  TryCatch.m
//  Thanx
//
//  Created by Darren Cheng on 2/11/15.
//  Copyright (c) 2015 Thanx. All rights reserved.
//

#import "TryCatch.h"

@implementation TryCatch

+(void)try:(void(^)())try catch:(void(^)(NSException *exception))catch {
  [self try:try catch:catch finally:nil];
}

+(void)try:(void(^)())try catch:(void(^)(NSException *exception))catch finally:(void(^)())finally {
  @try {
    if(try) try();
  }
  @catch(NSException *exception) {
    if(catch) catch(exception);
  }
  @finally {
    if(finally) finally();
  }
}

@end
```

You can then bridge it to Swift with a bridging header. Then do something like:
```swift
public class DB {
  public class func migrate() {
    // TODO - migrations
    TryCatch.try({ ()
      RLMRealm.defaultRealm()
    },
    catch: { (exception) -> Void in
      println("Migration Missing. Recreating Default Realm")
      self.teardown()
    })
  }

  private class func teardown() {
    NSFileManager.defaultManager().removeItemAtPath(
      RLMRealm.defaultRealmPath(), error: nil
    )
  }
```

Now, you can just stick DB.migrate() at the beginning of application didFinishLaunchingWithOptions and you should be good to go. If you use more than just the default realm, you'll have to modify the teardown method to support the other realm,

Anyway, this was tested against Realm v0.91.1, Swift 1.1, XCode 6.2 on iOS. Hope this helps.

**Comment by lordkev** [comment]
Just to chime in, as we're running into this too. Currently our use case is for alpha/beta versions of an app in development. We'd prefer not to bother with migrations every time we change the schema in a non-production app.

Additionally, our use of Realm is as a persistent local cache that can be re-created if necessary. I understand discouraging the behavior of deleting realms on schema mismatch, but it's also definitely useful to have deleting the realm as an option of last resort if a migration goes south for some reason. We do a similar thing with Core Data in another app, and although it's considered the "nuclear" option, it's better than crashing at every startup.

**Comment by jpsim** [comment]
#1723 is now pending review, which should enable safely deleting a realm file on schema mismatch.

**Comment by dougdiego** [comment]
I too have the same need. Not sure if this is the best solution, but this works for me:

```
    @try {
        RLMRealm *realm = [RLMRealm defaultRealm];
    }
    @catch (NSException *exception) {
        NSLog(@"Realm needs migration... Delete realm: %@", [RLMRealm defaultRealmPath]);
        NSFileManager *fileManager = [NSFileManager defaultManager];
        NSError *error;
        BOOL success = [fileManager removeItemAtPath:[RLMRealm defaultRealmPath] error:&error];
        if (success) {
            NSLog(@"Successfully deleted realm");
        } else {
            NSLog(@"Could not delete file -:%@ ",[error localizedDescription]);
        }
    }
```
Is that safe?

**Comment by ikonst** [comment]
@jpsim #1723 was closed without merging. Now all hope is on #1584. Is it coming up?

**Comment by jpsim** [comment]
> Now all hope is on #1584. Is it coming up?

That's still our preferred direction, but no one on our team is actively working on it at the moment. However, since this functionality can be built entirely at the Objective-C level, it's actually a task anyone from the community could contribute to Realm, if you're looking to get involved.

We're currently quite involved with fine-grain notifications, KVO, cascading deletes, thread handover and preparing an official release with functionality that recently landed in master.

**Comment by ikonst** [comment]
I just might.

**Comment by segiddins** [comment]
This will be trivial to implement via `RLMRealmConfiguration` once https://github.com/realm/realm-cocoa/pull/2252 is merged

**Comment by shfishburn** [comment]
How do we implement this in Swift 2.0?

**Comment by bdash** [comment]
Using [`Realm.Configuration.deleteRealmIfMigrationNeeded`](https://realm.io/docs/swift/latest/api/Classes/Realm/Configuration.html#/s:vVC10RealmSwift5Realm13Configuration28deleteRealmIfMigrationNeededSb).

**Comment by jpsim** [comment]
> If I may ask, where do we inject that line?

@shfishburn you pass a `Realm.Configuration` value when initializing a Realm: [`Realm.init(configuration:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5RealmcFzT13configurationVS0_13Configuration_S0_). So wherever you're opening a Realm for the first time in your app, you should make sure that the configuration value used has the `deleteRealmIfMigrationNeeded` value set to what you want it.

**Comment by NikKovIos** [comment]
Here is how to use it. Thumbs up if did help.

```
 let configuration = Realm.Configuration(deleteRealmIfMigrationNeeded: true)
    Realm.Configuration.defaultConfiguration = configuration
    do { _ = try Realm() } catch {}
```
