### ISSUE TITLE
RLMObject.objectsWhere is returning non-optional RLMResults

### ISSUE THREAD

**Issue by toshi0383** [realm/realm-cocoa#1698]
'objectsWhere' returns objectsWithPredicate return value which is RLMResults!.
But return type of objectsWhere is RLMResults.
Why is this ?

**Comment by jpsim** [comment]
`objectsWithPredicate` is defined in Objective-C, so Swift can't determine whether or not the return value can be nil, so it is treated as an implicitly unwrapped optional.

`objectsWhere` is defined in our Swift support file `RLMSupport.swift`, so we have full control over the nullability semantics of the return type, so we return a non-optional `RLMResults`.

We'll soon be releasing a new Swift interface which will have full nullability semantics for the entire API. You can try it out under `RealmSwift.xcodeproj` in the root of this repo, but keep in mind, our support for this will be limited until we officially launch it in the coming weeks.

**Comment by toshi0383** [comment]
Thanks for response !
