### ISSUE TITLE
Swift Generics

### ISSUE THREAD

**Issue by depl0y** [realm/realm-cocoa#1699]
In my project I have a couple of `RLMObject` definitions which contain to-many relations to different models. For example, I have the following object:

```
class Room: RLMObject {
	dynamic var name: String = "";
	dynamic var devices = RLMArray(objectClassName: BaseDevice.className());
	dynamic var identifier: String = "";
}
```
The `devices` property contains an array of objects with the type `BaseDevice`. Once I created a `Room` object, I can get an object from this array using the `objectAtIndex`.
```
var device = room.devices.objectAtIndex(0);
```

But the way this works now this code gives me a `RLMObject` instead of a `BaseDevice`. This needs to be cast to the right type for me to access the right properties. To fix this for myself, I created an extension on the Swift `Array` like this:

```
static func fromRealmArray(array: RLMArray) -> [T] {
	var returnArray = [T]();
	
	for (var index: UInt = 0; index < array.count; index++) {
		returnArray.append(array.objectAtIndex(index) as! T);
	}
	
	return returnArray;
}
```

This way I can do the following (where the `room!` object is of type `Room` as shown above). The result of this method is a nice `[BaseDevice]`.

```
var devices = Array<BaseDevice>.fromRealmArray(room!.devices);
```

**Proposal**
What I would love to see is generics being implemented here, where the definition of the `devices` property in my `Room` model could be something like this:

```
dynamic var devices = RLMArray<BaseDevice>();
```

This would be closer to the type-safe Array of Swift. The same thing could of course be said about `RLMResults` and other methods returning a `RLMObject` where a specific type is specified.

**Comment by jpsim** [comment]
Hi @depl0y, we'll soon be releasing a new Swift interface which will include support for generics. You can try it out under `RealmSwift.xcodeproj` in the root of this repo, but keep in mind, our support for this will be limited until we officially launch it in the coming weeks.

**Comment by depl0y** [comment]
Yeah, I think I will do that, but maybe after a Podspec for the Swift version is ready. 

Just saw #1705 appear ;)
