### ISSUE TITLE
Review jazzy-generated HTML docs for RealmSwift

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1703]

**Comment by jpsim** [comment]
This includes making sure cocoadocs.org renders our docs correctly.

**Comment by segiddins** [comment]
Verifying CocoaDocs behavior is contingent upon the podspec being contributed

**Comment by jpsim** [comment]
The docs are now reasonably rendered. There's always more we could improve, but this is no longer blocking a release of RealmSwift.
