### ISSUE TITLE
RLMArray init memory leak

### ISSUE THREAD

**Issue by seanooi** [realm/realm-cocoa#1714]
Created a new project and ran the example code here https://github.com/realm/realm-cocoa/blob/master/examples/ios/swift/Simple/AppDelegate.swift on simulator and device and both showed leaks when profiling with instruments.
![screen shot 2015-03-31 at 11 18 38 pm](https://cloud.githubusercontent.com/assets/561976/6934561/4c2f30c6-d7fc-11e4-85e4-31794d164df0.png)

Commenting `dynamic var dogs = RLMArray(objectClassName: Dog.className())` resulted in no leaks. Is it something to be worried about?

**Comment by segiddins** [comment]
I ran through the example in Instruments, and can confirm it leaks one RLMArray and one NSArray. On the other hand, I checked with our next RealmSwift examples, and there was no leak there.

**Comment by segiddins** [comment]
I just spent a couple of hours trying to figure this out, but it seems a leak will happen for any non-bridged `NSObject` property on an `RLMObject`.

**Comment by segiddins** [comment]
I actually just went back and profiled this, but I can't see the leak any more?

**Comment by seanooi** [comment]
Did you use the pre-build copy on the website or was it a build from the most current source?

**Comment by segiddins** [comment]
I just ran the example from `master`.

**Comment by jpsim** [comment]
We'll be closing this as we can't reproduce the issue with the new upcoming Swift API.
