### ISSUE TITLE
Document Subclassing (vs. Composition)

### ISSUE THREAD

**Issue by timanglade** [realm/realm-cocoa#1722]
At the end of the [“Models” section of our docs](https://realm.io/docs/cocoa/#models), we should have a section clearly highlighting that you _can_ subclass your RLMObject subclasses, what the implications of that are, and when you should use that vs. composition.

**Comment by jpsim** [comment]
@TimOliver please refer to https://github.com/realm/realm-cocoa/issues/1109#issuecomment-143834756 and https://github.com/realm/realm-cocoa/issues/1109#issuecomment-143985250 when writing this.

**Comment by jpsim** [comment]
From #3040:

> As long as #1109 is still outstanding, we should describe the limitations in our documentation and also have the proposed workarounds in our documentation as well. It would likely also very helpful if we would describe how class inheritances are mapped to tables in the model.

**Comment by TimOliver** [comment]
No worries! I've now added a PR including those points. Please let me know what you think!

**Comment by TimOliver** [comment]
PR's been merged and made live!
