### ISSUE TITLE
Issues with ObjectMapper

### ISSUE THREAD

**Issue by zocario** [realm/realm-cocoa#1726]
I am using Realm on my project (using Swift 1.2) with ObjectMapper to serialize and deserialize JSON Objects I receive and send to my REST Api.
Deserialization of objects works fine, but when I want to serialize one of my Realm object, I am having crashes like this:

    *** Terminating app due to uncaught exception 'RLMException', reason: 'Primary key can't be changed after an object is inserted.'

Or this if I don't include the primary key of the objects

    *** Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'

My Realm objects implement the Mappable protocol of ObjectMapper

    func mapping(map: Map) {
        id <= map["id"]
        name <= map["name"]
        about <= map["about"]
        goal <= map["goal"]
    }

I was really surprised to have this kind of error, as Realm acts as if I was editing my objects but I am just creating a JSON dictionary to send them to my API using this code:

    let json = Mapper<MyClass>().toJSON(self)

This is a [known issue](https://github.com/Hearst-DD/ObjectMapper/issues/31) on the ObjectMapper repository.
It seems the problem is the custom operator used by ObjectMapper ```<=``` that makes Realm thinks we want to edit the fields as they are passed as ```inout``` parameters:

    public func <- <T>(inout left: T, right: Map)

But this operator, depending on the mapping type (fromJSON or toJSON), will not always edit the inout field. When we are in a "toJSON" case, it'll only read its value and put it in the new JSON dictionary.

The creator of ObjectMapper hasn't find a solution for the moment, and I was wondering if you have any suggestions or pending changes that could help to solve this problem?

**Comment by segiddins** [comment]
Hi @zocario , do you have a project that you can share that we can use to reproduce the issue?

**Comment by zocario** [comment]
Hi @segiddins, check this a [demo project](https://www.dropbox.com/sh/v78sk4uljl58pmg/AACGL4i4SG5uo2C1hMh3KwZya?dl=0) that crashes with this issue.
The code that crashes is in the```viewDidLoad``` of the ```ViewController``` class.

**Comment by segiddins** [comment]
@zocario so, the issue there is that it's using an `inout` parameter. In Swift, inout means that the variable at the callsite is reassigned every time, even if there are no changes. I'd lean towards saying this is an issue with the design of `ObjectMapper`.

**Comment by zocario** [comment]
Thanks @segiddins for your answer.
I'll go with Mantle instead of ObjectMapper as there is no easy fix to get ObjectMapper working fine with Realm.

**Comment by zendobk** [comment]
+1, temp solution for me
`if realm == nil { id <-  map["id"] }`

**Comment by dmorrow** [comment]
I solved this issue by making a clone of the object I wanted to transform to JSON

    let preferencesCopy: Preferences = Preferences(value: preferences)
    preferencesCopy.toJSON()
