### ISSUE TITLE
deleteObject doesn't work 

### ISSUE THREAD

**Issue by nuke99** [realm/realm-cocoa#1732]
RLMRealm *realm = RLMRealm.defaultRealm;
            EBooks *eBookdb = [[EBooks alloc]init];
            eBookdb.eBook_ID = @"1124";
            [realm beginWriteTransaction];
            [realm deleteObject:eBookdb];
            [realm commitWriteTransaction];

I'm trying to delete a single object from the database and I'm getting the following error 
*** Terminating app due to uncaught exception 'RLMException', reason: 'Can only delete an object from the Realm it belongs to.'

But when I do a query I get results to the 1124 eBook_ID 
   NSString *filter_query = @"eBook_ID = '1124' ";
    RLMResults *res = [EBooks objectsWhere:filter_query];

FYI  eBook_ID is a NSString  I'm not sure if its a issue

**Comment by jpsim** [comment]
Initializing an `RLMObject` with alloc/init won't add it to a realm, which is why attempting to delete it is throwing the exception you posted. To add it to a realm, you need to either call `[EBooks createInRealm:withObject:]` (or similar creation method), or add it to the realm with `[realm addObject:eBookdb]`.

I suspect that the query is returning an object that was added elsewhere.

**Comment by nuke99** [comment]
Yes it was added in a different button action 

- (IBAction)previewPDFButtonAction:(id)sender {
       RLMRealm *realm = RLMRealm.defaultRealm;
        [realm beginWriteTransaction];
        EBooks *eBookdb = [[EBooks alloc]init];
        
        eBookdb.eBook_ID =  [NSString stringWithFormat:@"%@",eBookID];
        eBookdb.eBook_Name =  [NSString stringWithUTF8String:[[NSString stringWithFormat:@"%@",self.eBookName] UTF8String]];

        eBookdb.precentage = @"0.0";
        eBookdb.filePath = @"";
        eBookdb.fileName = @"";
        eBookdb.status = @"isdownloading";
        eBookdb.isSample = YES;
        
        [realm  addObject:eBookdb];
        
        
        [realm commitWriteTransaction];
}


I'm calling the delete function in delete button 

- (IBAction)previewDeleteAction:(id)sender {
          // Delete Current Object
            RLMRealm *realm = RLMRealm.defaultRealm;
            EBooks *eBookdb = [[EBooks alloc]init];
            eBookdb.eBook_ID = [NSString stringWithFormat:@"%@",self.eBookID];
            
            [realm beginWriteTransaction];
            [realm deleteObject:eBookdb];
            [realm commitWriteTransaction];

}


if I do [EBooks createInRealm:realm withObject:eBookdb]; what would it do ?

**Comment by nuke99** [comment]
Again I tried this also 
```
    // Delete Current Object
            RLMRealm *realm = RLMRealm.defaultRealm;
            
            [realm beginWriteTransaction];
            EBooks *eBookdb = [[EBooks alloc]init];
            eBookdb.eBook_ID = [NSString stringWithFormat:@"%@",self.eBookID];
            eBookdb.status = @"canceled";
            [EBooks createOrUpdateInRealm:realm withObject:eBookdb];
            
            [realm commitWriteTransaction];
            
//=> break point here before crash      
            
            [realm beginWriteTransaction];
            [realm deleteObject:eBookdb];
            [realm commitWriteTransaction];
```

and it updates the given row but when it executing [realm deleteObject:eBookdb]; app crashes with error 
```
'Can only delete an object from the Realm it belongs to.'
```


FYI I'm following the documentation in http://realm.io/docs/cocoa/0.91.1/#deleting-objects

**Comment by tgoyne** [comment]
Calling `createOrUpdateInRealm:withObject:` creates and returns a new object using the property values from the passed-in object, and does not modify the object passed in. Using `[realm addOrUpdateObject:eBookdb]` instead to add the existing object to the Realm will give the behavior you're expecting.

**Comment by yoshyosh** [comment]
@nuke99 you will need to fetch the object first and then delete it, I'm going to update the docs to represent this more clearly

**Comment by nuke99** [comment]
Yea I got it fixed . This is the working code 

```
    // Delete Current Object
            RLMRealm *realm = RLMRealm.defaultRealm;

            [realm beginWriteTransaction];
            EBooks *eBookdb = [[EBooks alloc]init];
            eBookdb.eBook_ID = [NSString stringWithFormat:@"%@",self.eBookID];
            eBookdb.status = @"canceled";
            eBookdb = [EBooks createOrUpdateInRealm:realm withObject:eBookdb];

            [realm commitWriteTransaction];

//=> break point here before crash      

            [realm beginWriteTransaction];
            [realm deleteObject:eBookdb];
            [realm commitWriteTransaction];
```

**Comment by onmyway133** [comment]
@tgoyne so how is `createOrUpdateInRealm:withObject` helpful?

**Comment by jpsim** [comment]
It's useful if you're getting a value from outside the realm that you want to map to a persisted object:

```objc
// Creating a book with the same primary key as a previously saved book
Book *cheeseBook = [[Book alloc] init];
cheeseBook.title = @"Cheese recipes";
cheeseBook.price = @9000;
cheeseBook.id = @1;

// Updating book with id = 1
[realm beginWriteTransaction];
[Book createOrUpdateInRealm:realm withValue:cheeseBook];
[realm commitWriteTransaction];
```
This example was taken from our documentation: https://realm.io/docs/objc/latest/#updating-objects
