### ISSUE TITLE
Release Realm Browser on the Mac App Store

### ISSUE THREAD

**Issue by timanglade** [realm/realm-cocoa#1733]
Since the browser is a relevant tool for users who otherwise don’t need to download realm-cocoa (e.g. Java developers, administrators, app designers, etc.), it makes sense at this point to distribute the browser on the app store (in addition to including it in our .zip realm-cocoa releases).

**Comment by palewar** [comment]
I am not sure if they will approve a < 1.0 version on App Store though? They don't allow beta apps for iOS for sure.

**Comment by tgoyne** [comment]
The browser itself isn't really a beta. We could give it its own version number if that's necessary.

**Comment by GreatApe** [comment]
I could look into it this week, but there is also the sandboxing issue. We would probably need to look over the IO bit.


On 06 Apr 2015, at 18:51, Thomas Goyne <notifications@github.com<mailto:notifications@github.com>> wrote:


The browser itself isn't really a beta. We could give it its own version number if that's necessary.

-

**Comment by TimOliver** [comment]
This issue was moved to realm/realm-browser#7
