### ISSUE TITLE
(IOS) Still no Relation Query?

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#1736]
For me everything is fine,Except no Relation Query.
It's a big issue for me to consider whether or not to use Realm.
Right now I just can only transform part of my sqlite tables to Realm,the rest which need relation query I cannot. I have to maintain sqlite and realm tables the same time,and cannot avoid duplication data.

[one-many]:
select Person.name,Dog.name from Person , Dog where Person.id = Dog.personid And Dog.color='red'
How to fetch the data one time,and not use FOR in program,is there a way?
When will the next version release?

thanks.

**Comment by segiddins** [comment]
@github2016a since Realm is _not_ a relational database, you don't need to worry about this sort of query! Realm has native support for to-many relationships, and you can read more about it on our docs at http://realm.io/docs/cocoa/0.91.1/#relationships. Hope that helps!

**Comment by github2016a** [comment]
Hi segiddins:
Thanks for your answer,sorry to bother again. I had saw the doc several times,but still cannot find a better way.
sorry for my poor english,I hope i can explain clearly.
for example,there are two objects:

class Person: RLMObject {
    dynamic var id : String = ""
    dynamic var name : String = ""
    dynamic var age : Int = 0
    dynamic var books = RLMArray(objectClassName: Book.className())
}
class Book: RLMObject {
    dynamic var ownerId : String = ""
    dynamic var title : String = ""
    dynamic var color : String = ""
}

If i want to see the person with age>40 who has red books(show all book title)
In relation database i just need:
    select count(1) from Person,Book where Book.ownerId = Person.id AND Person.age>40 AND Book.color='red'
    select Person.name,Book.title from Person,Book where Book.ownerId = Person.id AND Person.age>40 AND Book.color='red'
And in Realm I have to:

// get list
func getList()->[[String]]{
    let persons = Person.objectsWhere("age > 40")
    var countNeeded = 0
    var listNeeded = [[String]]()
    for obj in persons {
        var person = obj as Person
        let books = person.books.objectsWhere("color = 'red'")
        for obj2 in books{
            var book = obj as Book
            listNeeded.append([person.name,book.title])
        }
    }
    countNeeded = listNeeded.count
    return listNeeded;
}
// get Count
func getCount()->Int{
    let persons = Person.objectsWhere("age > 40")
    var countNeeded = 0
    for obj in persons {
        var person = obj as Person
        let books = person.books.objectsWhere("color = 'red'")
        countNeeded += Int(books.count)
    }
    return countNeeded
}

When the table data is big,the FOR still take time.There are so many such queries(such as group by) in my project,so it bothered me a lot.
If i made any mistake,or if there is a better way,please let me know.
Best Regards.

**Comment by yoshyosh** [comment]
Working on the answer to this in the new issue #1741
