### ISSUE TITLE
Migration block documentation issues

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#1737]
The following snippet is taken directly from the documentation  (http://realm.io/docs/cocoa/0.91.1/#migrations):

```
// Notice setSchemaVersion is set to 1, this is always set manually. It must be
// higher than the previous version (oldSchemaVersion) or an RLMException is thrown
[RLMRealm setSchemaVersion:1
            forRealmAtPath:[RLMRealm defaultRealmPath] 
        withMigrationBlock:^(RLMMigration *migration, NSUInteger oldSchemaVersion) {
  // We haven’t migrated anything yet, so oldSchemaVersion == 0
  if (oldSchemaVersion < 1) {
    // Nothing to do!
    // Realm will automatically detect new properties and removed properties
    // And will update the schema on disk automatically
  }
}];
```

Firstly, ```It must be higher than the previous version (oldSchemaVersion) or an RLMException is thrown``` is incorrect, as no exception will be thrown if you set the schema version to be equal to what it is on disk.

Secondly, ```oldSchemaVersion``` is of type NSUInteger. The default value of this is ```RLMNotVersioned``` (-1, not part of the public API). ```We haven’t migrated anything yet, so oldSchemaVersion == 0``` is also therefore incorrect.

**Comment by tgoyne** [comment]
The migration block isn't supposed to be getting called at all when the Realm is first created (which is the only time it's RLMNotVersioned; the version is set to zero on init if you don't set a schema version), but it appears that at some point "needs a migration" and "needs the schema version to be set" got lumped together.

**Comment by anlaital** [comment]
It would appear that my migration block is in fact being called when the database is first created. However, with oldSchemaVersion being -1 (NSUIntegerMax) all the linear migrations simply fall through.

**Comment by lbanders** [comment]
I see the same thing. We are just started on adding Realm.IO, so could be doing something wrong :) Here is the code I use for creating the RLMRealm. 
<pre>
    static func RealmFromPath(realmPath: String) -> RLMRealm? {
        RLMRealm.setSchemaVersion(CURRENT_DATABASE_VERSION, forRealmAtPath: realmPath, withMigrationBlock: migrationBlock)

        return RLMRealm(path: realmPath, readOnly: false, error: nil)
    }
</pre>

During this process the migration i started from a database version set to RLMNotVersioned but was expected to be 0.

**Comment by segiddins** [comment]
I believe we've changed it so that the block isn't called when the realm is first created?

**Comment by jpsim** [comment]
Sam's right, this is no longer necessary as of #1739.
