### ISSUE TITLE
Question about in memory Realm 

### ISSUE THREAD

**Issue by imanzarrabian** [realm/realm-cocoa#1738]
Hey, 
Quick question : 
The comment on the "realm" property of a RLMObject is a bit ambiguous to me :( 
```swift
/**
The Realm in which this object is persisted. Returns nil for standalone objects.
*/
var realm: RLMRealm! { get }
```
Does this also mean that a RLMObject inserted into an in memory realm created via     
```swift 
class func inMemoryRealmWithIdentifier(identifier: String!) -> Self!
``` 
will always have its realm property to nil?

**Comment by segiddins** [comment]
@imanzarrabian, in-memory Realms are basically the same as persisted Realms, except they're not written to disk. A standalone object is an object that is not saved to _any_ Realm, whereas an object that is inserted into an in-memory Realm is still a persisted object. Hope that helps!

**Comment by imanzarrabian** [comment]
thx @segiddins
