### ISSUE TITLE
Parsing improvements

### ISSUE THREAD

**Issue by Samback** [realm/realm-cocoa#1742]
For rest parsing everything should works fine if names from JSON and in your class the same . But if something is not OK, can you add a method that will provide possibility to override for that name path.
For example 
If in class I have a  property with name "color" and on JSON it's "bestColor"
I think it will be cool to make nameOverrides = {@"bestColor" : @"color"}
and add it like instruction.
If it's already implemented, can you please provide a link for the documentation, because I have probably miss that.

Regards,
Max

**Comment by segiddins** [comment]
@Samback, we already have a couple of issues tracking this, namely https://github.com/realm/realm-cocoa/issues/694 and https://github.com/realm/realm-cocoa/issues/1063.
