### ISSUE TITLE
Swift 1.2 Compatibility

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#1744]

**Comment by carl2013** [comment]
Go Sam! ;)

**Comment by segiddins** [comment]
We've got things working on the `mr-swift-1.2` branch, fore those who are interested.  I'm not sure what the timeline will be like for merging that to master yet (there are considerations for documentation and CI) but it is functional.

**Comment by segiddins** [comment]
Our ability to offer `@noescape` parameters is severely limited at the moment, because the Swift compiler, when interfacing with Objective-C, does not allow passing that `@noescape` closure into another `__attribute((noescape))` context.

**Comment by bennichols** [comment]
I'm trying to integrate this branch into my project, but I'm having issues figuring out the proper method. Can you please quickly summarize the integration steps? Thanks!

**Comment by segiddins** [comment]
@bennichols your best bet will be to clone this repo and add `RealmSwift.xcodeproj` as a subproject to your own project (or workspace)

**Comment by lewo** [comment]
I do that too, but end up having to add the realm.framework as well, other wise I get an error compiling about realm.private missing.
