### ISSUE TITLE
Realm treats my NSString field as an int

### ISSUE THREAD

**Issue by kaff1** [realm/realm-cocoa#1745]
This seems like something that must have come up already, but here's the problem I'm running into:

When trying to save a shipping address object, my zip code field (which is NSString, because I want to be able to use the same field for other sorts of postal codes, such as the alphanumeric ones in Canada & the UK) seems to get treated as an int.

If I try to store the object in Realm (from an NSString * field) using just the actual value for a zip code, I get a RealmException with "invalid value for property zipcode". If I throw that zip code into a string with a space at the end, everything is fine.

Goals: To be able to save an object (such as a shipping address) that has a field that is a string that only consists of numbers (but that I don't want to treat as a number)

Expected Results: Realm should save my string as a string and not worry about if it looks like a number

Actual Results: Realm complains that my string contains only numbers

Steps to repro: 
1) Create object that contains a string field 
2) set string field to a string that only contains numbers 
3) save object in Realm 
4) receive exception

Code sample: Available if desired. Didn't want to clutter this up further.

Version of Realm: Current as fetched via CocoaPods. (0.91.1)

**Comment by yoshyosh** [comment]
Hey Jon, can you try making sure that your int is a string rather than just an int? I know with some JSON responses they can show up as int's but actually come out as strings. As long as you make sure you are adding a string you should be fine!

If that doesn't fix it, can you share your code where this part is happening?

**Comment by kaff1** [comment]
Sure Joseph. That's what I thought too. I'm going to grab a coffee and make sure this isn't just a lack-of-sleep problem, but I'll step through everything one more time and get back to you with the results.

**Comment by yoshyosh** [comment]
Feel free to post your model and the code where you are adding the zipcode in case I can spot anything quickly

**Comment by kaff1** [comment]
Snippet of properties from the model:

@property (nonatomic) NSInteger accountId;
@property (strong, nonatomic) NSString *city;
@property (nonatomic) NSInteger addressId;
@property (strong, nonatomic) NSString *country;
@property (strong, nonatomic) NSString *updateTime;
@property (strong, nonatomic) NSString *zipCode;
@property (strong, nonatomic) NSString *street1;
@property (strong, nonatomic) NSString *street2;
@property (strong, nonatomic) NSString *addressState;

**Comment by yoshyosh** [comment]
SO far so good :-)

**Comment by kaff1** [comment]
Good news: Populating & storing the model this way worked out:

        NSString *zipcodeString = [NSString stringWithFormat:@"%@",[addressObject valueForKey:[FBit_AddressObject key_zipCode]]];

        shippingAddress = [[FBit_AddressObject alloc] initWithAccountId:[[addressObject valueForKey:[FBit_AddressObject key_accountId]] intValue]
                                                                andCity:[addressObject valueForKey:[FBit_AddressObject key_city]]
                                                             andCountry:[addressObject valueForKey:[FBit_AddressObject key_country]]
                                                             andStreet1:[addressObject valueForKey:[FBit_AddressObject key_street1]]
                                                             andStreet2:[addressObject valueForKey:[FBit_AddressObject key_street2]]
                                                               andState:[addressObject valueForKey:[FBit_AddressObject key_state]]
                                                             andZipCode:zipcodeString
                                                           andAddressId:[[addressObject valueForKey:[FBit_AddressObject key_addressId]] intValue]
                                                          andUpdateTime:[addressObject valueForKey:[FBit_AddressObject key_updateTime]]];

**Comment by kaff1** [comment]
Which I thought I had already tried, but apparently not. Sorry to waste your time, but thanks for the quick response :)

Setting zipcode via [addressObject valueForKey:[FBit_AddressObject key_zipCode]] was where the issue seems to have been

**Comment by yoshyosh** [comment]
Great news :)! Was that one line of code returning an integer rather than string?

**Comment by yoshyosh** [comment]
Also no need for apologies! We're really stoked that you are using Realm and appreciate you reaching out

**Comment by kaff1** [comment]
Thanks, I'm stoked to be using it! Sure beats writing a whole bunch of SQL
:)

And yes, it looks like that one line was deserializing as an int instead of
a string. As someone who's spent a lot more time doing Android development
than iOS, I'm still picking up the finer points of Obj-C :)

**Comment by yoshyosh** [comment]
Haha I agree but I may be biased of course ;)

Good to know, welcome back from the dark side :dancer:
