### ISSUE TITLE
Fix dynamic framework instructions

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1747]
In our docs we say Drag `Realm-dynamic.framework` & `Realm-dynamic-simulator.framework` from the ios/ directory... but `Realm-dynamic` and `Realm-dynamic-simulator.framework` is no where to be found based on the folder structure mentioned above. I know JP said these instructions will be fixed when the new Swift api's launch. This will be needed for the Obj-c api's even once the RealmSwift api is released

**Comment by segiddins** [comment]
This is closed by https://github.com/realm/realm.io/pull/452, I believe.
