### ISSUE TITLE
Realm not persisting changes made to RLMObjects from RLMResults

### ISSUE THREAD

**Issue by seancatkinson** [realm/realm-cocoa#1748]
Tested using Swift 1.2 - not supported yet

Example Project: https://github.com/seancatkinson/realm-swift-update-issue

Having an issue where I can't update my RLMObjects. Process is a follows:
1) Click Add - New Screen shows
2) Add Object Details
3) Click Save - screen dismisses
4) table view reloads from realm notification - new object shows
5) click the new object - new screen shows
6) modify the text, click save - screen dismisses
7) notification fires, table reloads, object does not change

The object that is 'updated' does get the changes, however those changes are lost once the object is released. Using the Realm Browser suggests no changes are happening on the back-end.

**Comment by segiddins** [comment]
@seancatkinson, I made a [PR](https://github.com/seancatkinson/realm-swift-update-issue/pull/1) that fixes the issue you were seeing.

**Comment by seancatkinson** [comment]
Ah! Of course, because I'm not editing the original object but a new object created from the original. Thanks a lot Xcode Autocomplete...
Cheers :)
