### ISSUE TITLE
Add string to addNotificationBlock method.

### ISSUE THREAD

**Issue by karadis** [realm/realm-cocoa#1756]
Hey, this is a suggestion rather than an issue.
As i understand using Realm notification mechanism will invoke a notification block in all alive objects that holds an existing noitificationToken.

Why not pass a string argument ("name") to the notification (along with the notification and the realm objects), to specify the specific notification type that is used, so it would be easy to handle it accordingly - meaning the developer will decide what block will run according to the name.

For example:

```objc
 [[RLMRealm defaultRealm] addNotificationBlock:^(NSString *notification, NSString *name, RLMRealm *realm) {
        if ([name isEqualToString:SOME_NOTIFICATION_STRING]) {
// do your thing
        }
    }];
```

I think it's easy to implement, and would be a great enhancement to the API.
Thanks.

**Comment by segiddins** [comment]
@karadis, I believe what you're asking for is the `notification` argument which we already pass in, whose values are documented at http://realm.io/docs/cocoa/api/Constants/RLMRealmNotification.html.

**Comment by jpsim** [comment]
It seems to me like @karadis is asking for the ability to "tag" transactions, which would allow conditionally running code in a notification block based on what write transaction it corresponds to.

The (small) problem with that is that multiple transactions may have triggered the notification block, so at the very least, the notification block would have to pass an array of those tags/names.

@karadis is that a fair assessment of what you're requesting? Could you think of a scenario where tagging a write would be preferable than parsing the fine-grain notifications information that we're currently working to offer (#601)?

**Comment by karadis** [comment]
Thanks @jpsim , yes, thats what i was referring to, and actually the fine-grain solution would be a great solution.

Either way, I can give you an example to what i had in mind:
It's basically referring to a number of operations i perform in a transaction; If for example i'm performing a Login process to a user, and in that process I am saving a User object and another different object (let's say for argument sake) a Favorites Object. 
This whole login process can be tagged as "Login_process_completed" (string).

The LoginViewController (or other classes for that matter) can register to a notification block, and check the tag/name that is passed. if it is equals to "Login_process_completed", than i can continue with what i want.

I'm assuming the fine-grain solution can solve this problem as well, althuogh if i understand correctly i would have to "register" to a notification block for User object and for Favorites Object, and handle them separately. (or will they be passed as an array inside the same block?)

Thank you for the reply

**Comment by segiddins** [comment]
I actually think that using a normal `NSNotificationCenter` might be the best option for the kind of notifications you're looking for, @karadis -- `NSNotification`s can have semantic meaning that commit a transaction probably will never have.
