### ISSUE TITLE
Realm Browser Feature Request - Realm file may not end up with "realm" extension

### ISSUE THREAD

**Issue by puttin** [realm/realm-cocoa#1762]
as the title

**Comment by jpsim** [comment]
That's very true. Until we add a way to open realm files without a `.realm` extension, you can always just rename it to include `.realm`, make a copy whose name includes `.realm` or make a symlink with a `.realm` extension.

**Comment by TimOliver** [comment]
This issue was moved to realm/realm-browser#10
