### ISSUE TITLE
Cannot access elements of RLMResults

### ISSUE THREAD

**Issue by kevinmlong** [realm/realm-cocoa#1764]
Please see screen shot below...

Not sure what the issue is, but we're running some tests and it seems like Realm will sometimes allow us to access the objects and sometimes won't. We're trying loop through the `RLMResults` object and add them to another structure (in this case a quad tree). The `RLMResults` object says it has a count of 19459, which is correct, but if we try to get the object at index 0, it throws a `EXC_BAD_ACCESS`. 

Before this takes place, we've copied a Realm from the bundle to our document directory (iOS Simulator) and set that path for the default. We print out the path of the default realm and, as can be seen in the console window, it points to the copy we created. Is this perhaps a race condition with the copy? I wouldn't think so though, since the count on the `RLMResults` is what we expect.

Any thoughts?

![screen shot 2015-04-17 at 12 32 24 pm](https://cloud.githubusercontent.com/assets/6371696/7206293/d814fae0-e4fd-11e4-9c84-955a1aed7fe5.png)

**Comment by segiddins** [comment]
@kevinmlong are you sure the RLMResults actually contains objects of type `Airport`? I wouldn't be surprised if it was your forced downcast that was failing. Additionally, I can see that this is happening inside your test suite -- have you made sure to only link your model classes to your app target?

**Comment by kevinmlong** [comment]
@segiddins - Yes. The RLMResults indeed contains `Airport`. It works sometimes, but not others, which is the confusing part. The model is linked to both the app and testing targets. The db is not encrypted and we're using version 0.91.2 (Xcode Beta 6.3)

**Comment by segiddins** [comment]
Right, so you can't link your model to both the app and test targets, as it will lead to having two versions of your model class at runtime. Instead, it should be linked only to your app target. Let me know if that fixes things for you!

**Comment by kevinmlong** [comment]
@segiddins - ok, so is it possible to run unit tests using the model?

**Comment by segiddins** [comment]
You should be able to write unit tests just fine, as long as you import the app into your test target.

**Comment by kevinmlong** [comment]
I should have mentioned that I'm using swift, and my understanding is that a class (and any that they depend on) used in XCTest needs to be included in the test target. Am I confused on this? Have y'all done tests with Swift?

**Comment by segiddins** [comment]
You should not need to add your app's swift files to the test target, you should be able to just `import APP_NAME` inside your tests.

**Comment by kevinmlong** [comment]
Do y'all have an example project that does this? I haven't been successful getting that to work with Swift.

**Comment by kevinmlong** [comment]
Ah! So....we figured out the testing stuff. I guess everything that we want to test needs to be public. It appeared that is was before, but I guess it's because the default was internal and the testing module couldn't access the classes and members from the app target. I'm going to close this.

Thanks for the help!

**Comment by kevinmlong** [comment]
For those that are intersted in the testing stuff, here is a good tutorial that seems far more appropriate than just adding swift files to your testing target. http://www.andrewcbancroft.com/2014/12/29/getting-started-unit-testing-swift/
