### ISSUE TITLE
Extra argument 'objectClassName' in call

### ISSUE THREAD

**Issue by staticdreams** [realm/realm-cocoa#1765]
I admit, I haven't been updating Realm for a few weeks now, but since today's "pod update" + building I got this:
``Extra argument 'objectClassName' in call`` on RLMArray

Here's my code:

	class Stop: RLMObject {
		dynamic var physicalStopCode = ""
		dynamic var stopCode = ""
		dynamic var stopName = ""
		dynamic var coordinates = Coordinates()
		dynamic var connections = RLMArray(objectClassName: Connection.className())  // <---- Error occurs right here
		dynamic var distance:Double = 0.0
		override class func primaryKey() -> String! {
			return "physicalStopCode"
		}
	}

Everything was working fine before but now on each occurrence of  ``RLMArray(objectClassName: MyClassNameHere.className())`` I'm getting this error. It seems that it may have been caused by the latest realm update. If not I apologise. In any case some help would appreciated.

I forgot to add that I'm on Xcode 6.3. Building for iOS 8.3. Cleaned build folder and purged DerivedData.

**Comment by tgoyne** [comment]
Looks like this was broken by some of the changes for RealmSwift. As a temporary workaround, you can add a declaration of `- (instancetype)initWithObjectClassName:(NSString *)objectClassName;` to RLMArray in a class extension in a bridging header.

**Comment by staticdreams** [comment]
Thank you @tgoyne ! This seem to have fixed the issue. 
Should I close this or should it remain open until merged?
