### ISSUE TITLE
Not sure what is happening with beginWriteTransaction inside of didFinishSpeechUtterance

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1766]
Why does println not print after the beginWriteTransaction.

What is happening here? It doesn't crash, it just skips the rest of the delegate method.

![screen shot 2015-04-17 at 12 55 59 pm](https://cloud.githubusercontent.com/assets/1189875/7207747/79cd83f4-e501-11e4-88b5-6d22e07e7a09.png)

**Comment by segiddins** [comment]
@webmagnets, are you sure that it's not just being blocked on opening up a new write transaction (i.e. you might already have a write transaction going on another thread, and so the call to `beginWriteTransaction()` will block until that other transaction is either committed or canceled)

**Comment by webmagnets** [comment]
There is not other transaction open.

If there were, wouldn't the app crash?

**Comment by segiddins** [comment]
No, attempting to open a write transaction will block (i.e. the call will not return and will wait) until the existing write transaction is either committed or cancelled.

**Comment by webmagnets** [comment]
Thanks for that info. However, there are no transaction blocks opened before this one.

**Comment by segiddins** [comment]
@webmagnets that's really the only thing that would cause a blocking call to `beginWriteTransaction()`. I'd be happy to take a look at your project, but I'm fairly confident that this is a symptom of having another open write transaction.

**Comment by webmagnets** [comment]
That would be great. What would be the best way to share it with you?

**Comment by segiddins** [comment]
Either a link here or you can send it to us privately at help@realm.io if you prefer.

**Comment by webmagnets** [comment]
Ok the upload to dropbox is finished.

**Comment by webmagnets** [comment]
This appears to have resolved itself after I started with a new Realm file.

**Comment by jpsim** [comment]
Glad to hear it! Please let us know if this happens again.
