### ISSUE TITLE
How to use defaultPropertyValues while using response data from server ?

### ISSUE THREAD

**Issue by tariq235** [realm/realm-cocoa#1768]
I know we have to use defaultPropertyValues.
Class structure:

@interface Event : RLMObject
@property (nonatomic, copy) NSString *roomName;
....
- (instancetype)initWithAttributes:(NSDictionary *)attributes;

@end

@implementation Event

+ (NSDictionary *)defaultPropertyValues {
    return @{@"roomName" : @""};
}
    
- (instancetype)initWithAttributes:(NSDictionary *)attributes {
    self = [super init];
    if (self) {
        self.roomName = [attributes valueForKeyPath:@"room"];
        .......
    }
    return self;
}

Event *school = [[IVEvent alloc] initWithAttributes:dict];
[realm addObject:school];

'RLMException', reason: 'No value or default value specified for property 'roomName' in 'Event''

This is because roomName is getting assigned by defaultPropertyValues class method. But as soon as it get parsed from attributes dictionary it becomes roomName nil and getting crashed. Is there any better way to handle this ? I don't want to put if condition on [attributes valueForKeyPath:@"room"]

Thanks!

**Comment by CraigSiemens** [comment]
I ran into this exact same issue in my app. I ended up creating a category on RLMObject with a method that replaces nil values with a default value. I just call the method after creating or updating an object from a dictionary.

``` objc
- (void)applyDefaults {
    for (RLMProperty *property in self.objectSchema.properties) {
        id defaultValue = [[self class] defaultPropertyValues][property.name];
        id propertyValue = [self valueForKey:property.name];
        if (defaultValue && propertyValue == nil) {
            [self setValue:defaultValue forKey:property.name];
        }
    }
}
```

Hopefully this will be obsolete once [null support](https://github.com/realm/realm-cocoa/issues/628#issuecomment-94050752) is added.

**Comment by tariq235** [comment]
Thanks @CraigSiemens I'll try this solution. However I am also interested in null support branch merge to the master :) 
I'll try to do some beta testing as per Tim instruction.

**Comment by segiddins** [comment]
@tariq235 as it stands right now, you will need to do your own data sanitization for nulls before passing dictionaries into realm. We are, however, actively working on null support, which should make this all much easier. Hope that helps!
