### ISSUE TITLE
Cannot use RLMArray with custom protocols

### ISSUE THREAD

**Issue by francoismarceau29** [realm/realm-cocoa#1773]
Hi! I am trying to use a RLMArray which contains RLMObjects shielded by a protocol and I get the error:   

    'APPOption' is not supported as an RLMArray object type. RLMArrays can only contain instances of RLMObject subclasses

I have a "ShopifyOption" and a "MagentoOption" which are both shielded by the APPOption protocol :

    @interface ShopifyOption : RLMObject <APPOption>
    @end

    @interface MagentoOption : RLMObject <APPOption>
    @end

I have an object which hold an array of options:

    @property RLMArray<APPOption>

Realm uses reflection to get the class name from the property above so it clearly can't work. Is there a way around this?

Thanks

**Comment by jpsim** [comment]
Hi @francoismarceau29, RLMArray's can only link to objects of a single type. We have an issue open discussing the possibility of adding support for abstract classes or polymorphic link support in #1109.

**Comment by francoismarceau29** [comment]
Thanks, hope it makes it in soon!
