### ISSUE TITLE
New version log notification 

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#1777]
Hi folks!
```
Version 0.91.3 of Realm is now available: http://static.realm.io/downloads/cocoa/latest
```
The main issue is that due to a policy on our project, all libraries that we use are of a specific version. All updates are done on a separate special testing procedure. 
What it means is that we update our pods every 3-4 weeks (bureaucracy...)
This means that the up-mentioned log becomes somehow annoying, especially on unit tests.

Is there a way to mute it?

**Comment by tgoyne** [comment]
If you set an environment variable named `REALM_DISABLE_UPDATE_CHECKER` to any value for your test scheme the update check will be skipped.

**Comment by OlegAnghelov** [comment]
Thank you a lot :)
