### ISSUE TITLE
Seg fault when accepting an array of a generic type

### ISSUE THREAD

**Issue by mkolodny** [realm/realm-cocoa#1780]
We have two class functions that accept a generic type:

    class Resource: RLMObject {
        ...

        class func getInstance<T: Resource>(..., T, ...) {
            ...
        }

        class func getInstances<T: Resource>(..., [T], ...) {
            ...
        }
    }

Both functions (`getInstance` and `getInstances`) compile successfully when Realm isn't included in the workspace. With Realm included, the first function compiles, yet the second doesn't. We've determined that accepting array of type T is causing a seg fault: `Command failed due to signal: Segmentation fault: 11`.

Do you have any suggestions regarding how we can fix this? Should we expect a RLMArray instead of a Swift array? If so, how?

Note: We're using Realm with XCode 6.3 and Swift 1.2.

**Comment by segiddins** [comment]
Is that segfault happening while compiling? If so, that would be a Swift bug rather than a Realm bug, and should be reported as a radar to bug report.apple.com. If it is indeed a runtime segfault, would you be able to share a backtrace? Thanks!

**Comment by mkolodny** [comment]
It's happening while compiling. I'll report the bug to Apple. Thanks @segiddins!
