### ISSUE TITLE
+ [RLMRealm resetRealmState] is not available?

### ISSUE THREAD

**Issue by nakp** [realm/realm-cocoa#1781]
The latest docs [recommend to make a Realm reset when testing](http://realm.io/docs/cocoa/#testing-realm-apps),  and I'd like to reset the Realm state but seems that method is not public and I could only find it [here](https://github.com/realm/realm-cocoa/blob/1f3bad0e6046e7e0d1de1ac28a77a66e20aabf59/Realm/RLMRealm_Private.h#L35)

**Comment by jpsim** [comment]
Hi @nakp, those docs are unfortunately referring to a method that is now private in Realm.

However, as you can see from its implementation [here](https://github.com/realm/realm-cocoa/blob/64b8aed755a6dd8eba842eb48903e0268f73eb96/Realm/RLMRealm.mm#L436-L441), it shouldn't actually be necessary in your tests. We'll update the docs as soon as possible to remove this method.

**Comment by jpsim** [comment]
The updated docs are now online.
