### ISSUE TITLE
Support Carthage for RealmSwift

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1790]
Because Carthage only builds framework schemes from the first Xcode project it finds in a repo, it builds the frameworks in `Realm.xcodeproj` but not `RealmSwift.xcodeproj`. There are a few ways we could support Carthage for RealmSwift:

## 1. Merge RealmSwift and Realm into a single Xcode project.

I believe this to be the simplest option and won't really have any adverse effects on our development. The biggest downsides to this are that:

1. including the RealmSwift source and Xcode project in a release zip will be more complicated
2. there will be more schemes to scroll through in Xcode

Although at this point 1) shouldn't matter too much because I think we should only be including prebuilt binaries in our release zip (see discussion here: https://github.com/Carthage/Carthage/issues/433).

## 2. Move RealmSwift into a separate repo.

Since RealmSwift is really just an alternative API to Realm.framework, and that it relies on many of the same parts of the repo, keeping both in a single repo is much simpler and better. So I don't think this is a viable option.

## 3. Add support for multiple projects to Carthage.

This was my original intention, but after thinking about it a bit, it probably wouldn't be ideal in the general case. Consider the different ways Carthage could be modified to build frameworks from multiple Xcode projects:

a. Build all framework schemes from all Xcode projects in a repo. This will build many more frameworks than are required (all development and test resources)
b. Build all framework schemes from an Xcode workspace, if present. This has the same problem as a).
c. Add the ability to specify which frameworks should be built in a Cartfile. Since Cartfile syntax should be simple, backwards-compatible, parseable and have smart defaults, I don't think this is viable either.

**Comment by tonyarnold** [comment]
Option 1 is the sanest, IMO.

**Comment by jpsim** [comment]
I was unable to combine both Xcode projects (see #1809).

However, we do support pre-built frameworks through Carthage's GitHub releases feature, which should be sufficient for most users.

So I'll be closing this issue until we decide that supporting using Carthage building Realm Swift from source is a priority.
