### ISSUE TITLE
Testing whether a RLMArray contains a value using indexOf

### ISSUE THREAD

**Issue by underbluewaters** [realm/realm-cocoa#1795]
![screen shot 2015-04-24 at 11 27 06 am](https://cloud.githubusercontent.com/assets/511063/7328938/4d63e1b8-ea75-11e4-911d-f1abc4c3ac27.png)

I've got this code in my latest project. Is this the only way to test whether an object is in a RLMArray when using Swift? I'm afraid this test might be platform dependent.

**Comment by jpsim** [comment]
To test if an object is a member of an RLMArray, you can compare the result of `indexOfObject(_:)` with `NSNotFound`.

**Comment by underbluewaters** [comment]
For anyone else confused, I had to cast NSNotFound to a UInt. The Xcode error messages were giving me very poor feedback.

![screen shot 2015-04-24 at 5 06 12 pm](https://cloud.githubusercontent.com/assets/511063/7331257/5deea278-eaa4-11e4-9a8c-6e844429bec2.png)
