### ISSUE TITLE
add validation of input parameters to [realm deleteObject:

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-cocoa#1799]
currently it crashes core if you pass an RLMResult for instance.

**Comment by segiddins** [comment]
I'm not so sure we need this, since the method's parameter is an `RLMObject`.

**Comment by bmunkholm** [comment]
Core crashes according to a user issue (see helpscout #919).

**Comment by tgoyne** [comment]
Crashes when you pass in the wrong type of object to a function are expected. It would not be reasonable to add runtime type checks for every single parameter of every method in the entire API.
