### ISSUE TITLE
Compile error with Realm Core Null v1 BETA

### ISSUE THREAD

**Issue by kitasuke** [realm/realm-cocoa#1801]
I'm trying to use the beta version right now. I followed the instruction for using Realm through Cocoapods on this issue. https://github.com/realm/realm-cocoa/issues/628#issuecomment-94050752. However, I got a compile error below. 
```
Undefined symbols for architecture x86_64:
  "realm::Table::add_column(realm::DataType, realm::StringData, realm::util::bind_ptr<realm::Descriptor>*)", referenced from:
      _RLMRealmCreateMetadataTables in libPods-MyProjectName WatchKit Extension-Realm.a(RLMSchema.o)
      RLMCreateColumn(RLMRealm*, realm::Table&, RLMProperty*) in libPods-MyProjectName WatchKit Extension-Realm.a(RLMObjectStore.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My project has a WatchKit extension, you might notice from the message of compile error though. Here is my Podfile content.
```
pod 'Realm', '~> 0.91.3'
target 'MyProjectName WatchKit Extension', :exclusive => true do
    pod 'Realm', '~> 0.91.3'
end
```

Is this related to using beta version or is it other issue?

**Comment by kishikawakatsumi** [comment]
You are probably forgot to copy the "include" directory contains the beta zip file. The directory structure of the zip file looks like the following. You need to copy both `Include` directory and `librealm-ios.a` to `Pods / Realm` directory from zip.

```
├── LICENSE
├── include
│   ├── realm
│   │   ├── impl
│   │   ├── util
│   │   ├── utilities.hpp
│   │   ├── version.hpp
│   │   └── views.hpp
│   └── realm.hpp
├── librealm-dbg.a
├── librealm-ios-dbg.a
├── librealm-ios.a
├── librealm.a
└── releasenotes.txt
```

**Comment by kitasuke** [comment]
Well, I didn't care about the files inside `core` directory, so what I did is to just copy the `core` folder itself to `Pods/Realm` which was not appropriate...

Now it successfully runs without any compile errors!
Thank you for your quick response!
