### ISSUE TITLE
Freeze if you save nil property in not main thread

### ISSUE THREAD

**Issue by ako2009** [realm/realm-cocoa#1812]
1) Write RLMObject with nil property in any thread, but not the main thread where the database was initialized.

    RLMRealm* realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    [realm addObject:obj];
    [realm commitWriteTransaction];

2) Observe no exceptions, no warning logs and no object in the default.realm.

3) Restart the app.

4) First call of [realm beginWriteTransaction] in the main thread freezes the app.

If you do (1) in the main thread then you can observe warning logs.

**Comment by jpsim** [comment]
I don't think the information you've provided is enough to reproduce the issue you're having.

For example, with the following code:

```objc
@interface Object : RLMObject
@property NSString *property;
@end
@implementation Object
@end

// Later...

dispatch_async(dispatch_queue_create("background", 0), ^{
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        Object *object = [[Object alloc] init]; // `property` is nil by default
        [realm addObject:object];
    }];
});
```

A `No value or default value specified for property` exception is thrown immediately and subsequent launches of the app are able to perform write transactions in the main thread without issue.

Could it be possible that another write transaction on a different thread is causing the background transaction you're attempting to wait? Writes block other writes in Realm.

Would it be possible for you to share a project which reproduces this issue with us? You can email us privately at help@realm.io if discretion is necessary.

**Comment by ako2009** [comment]
Thank you, @jpsim! I've sent you details by email.

**Comment by jpsim** [comment]
Based on the code we received via email, the problem was that an `RLMObject` was being modified by a different thread than the one that was used to create or obtain the object.
