### ISSUE TITLE
How to call init(forPrimaryKey:) in Swift

### ISSUE THREAD

**Issue by malcommac** [realm/realm-cocoa#1813]
Hi guys,
This is not really a bug I think.
In my model I would to create a class method which return an object of my class with a specific primary key.

That's my method:

```
class func localUser(username : String!) -> User? {
		let userObj: User? = User(forPrimaryKey: username)
		return userObj
}
```
However it returns an error:
`User.swift:42:28: Incorrect argument label in call (have 'forPrimaryKey:', expected 'rawData:')`

Why? (rawData: is another convenience init method I've added as you can see above).

```
import UIKit
import Realm
import SwiftyJSON

class User: RLMObject {
	dynamic var username = ""
	dynamic var email = ""
	dynamic var timezone = ""
	dynamic var isLoggedUser = false
	
	override init() {
		super.init()
	}
	
	override class func primaryKey() -> String {
		return "username"
	}
	
	init(username: String, email: String?) {
		super.init()
		self.username = username
		self.email = (email != nil ? email as String! : "")
	}

	init(rawData : JSON?) {
		if let rawData = rawData as JSON! {
			self.username = rawData["username"].string!
			self.email = rawData["email"].string!
			self.timezone = rawData["timezone"].string!
		}
	}
	
	class func localUser(username : String!) -> User? {
		let userObj: User? = User(forPrimaryKey: username)
		return userObj
	}
}
```

**Comment by segiddins** [comment]
The issue is that two two initializers you've defined are not convenience initializers.

**Comment by codeleader** [comment]
You have to you use convenience *init* to implement other initializers.



Cordialement,




2015-04-30 17:24 GMT+01:00 Samuel E. Giddins <notifications@github.com>:
