### ISSUE TITLE
Query subclasses from parent class?

### ISSUE THREAD

**Issue by jpchmura** [realm/realm-cocoa#1814]
For Realm objects where:

``` swift
class Parent: RLMObject {
dynamic var id: String
dynamic var type: String
}

// type == ChildA
class ChlidA: Parent {
// Additional fields
}

// type == ChildB
class ChildB: Parent {
// Additional fields
}
```

I would like to query all child classes from the parent class type. Such as:

``` swift
var result = Parent.AllObjects()
```

I wrote some tests and doing this will not return any "child" objects.  Is this a limitation in Realm?  Core Data supports this design pattern.

**Comment by jpsim** [comment]
Yes, this is a limitation in Realm. We're tracking this issue in #1109. Closing as a duplicate. That issue has a number of workarounds if you need functionality like this.
