### ISSUE TITLE
How to get [realm createOrUpdate] change set?

### ISSUE THREAD

**Issue by fooevr** [realm/realm-cocoa#1824]
I want to get the changed set when call createOrUpdate to commit data, is there any way to get it?

**Comment by jpsim** [comment]
Hi @fooevr, Realm doesn't currently have any mechanisms in place to expose what data has changed in a [notification](http://realm.io/docs/cocoa/latest/#notifications). We're already tracking this functionality in #601, so I'm closing this one as a duplicate.

**Comment by fooevr** [comment]
@jpsim thanks, I hope realize this practical feature soon.
