### ISSUE TITLE
Disable Automatic Version Checking

### ISSUE THREAD

**Issue by jcjee** [realm/realm-cocoa#1825]
Hi, I am using Realm on the company network which requires an authenticated proxy access to the internet. I am getting my company proxy authentication error html in the console, and it is due to Realm trying to access the following link:

http://static.realm.io/update/cocoa?0.91.5

I believe Realm is trying to check for version updates in the background. How can I prevent Realm from "phoning home"? Thanks.

**Comment by jpsim** [comment]
You can set the `REALM_DISABLE_UPDATE_CHECKER` environment variable to any value to disable Realm from checking for versions. The relevant code is all in https://github.com/realm/realm-cocoa/blob/master/Realm/RLMUpdateChecker.mm.
