### ISSUE TITLE
Better crash logging caused by invalid fields

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#1827]
Hi guys!
Thanks again for your great work.

I have a small issue. 
We got a crash report, with the following exception:
`Terminating app due to uncaught exception 'Invalid value', reason: 'object must be of type string'`

Usually when this happens while developing, we put some breakpoints in the Realm pod and see what key failed.
In this case we cannot do this.
Can you guys give the log some more information? What was the field, what was the value? The more the better...
What do you think?

**Comment by jpsim** [comment]
I agree the message here could be more descriptive.
