### ISSUE TITLE
Fix Cobertura reports for all members

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1831]
Some users (at least @kishikawakatsumi) can't see the test coverage source file visualizations in Jenkins (e.g. https://ci.realm.io/view/6.%20Pull%20Requests/job/objc_pr/configuration=Release,target=osx/508/cobertura/Realm/RLMMigration_mm/), which makes those reports quite unhelpful.

It works fine for me, though. @emanuelez do you have any thoughts as to why this might be happening?

**Comment by segiddins** [comment]
Is it possible that only admins can see it?

**Comment by jpsim** [comment]
It seems that the Cobertura Jenkins plugin doesn't preserve the entire source for old builds, which is good because the CI workers are already constrained for space. So if you can't see the source code visualization, please look at the latest build instead.
