### ISSUE TITLE
All query on array (any workarounds?) 

### ISSUE THREAD

**Issue by jonandersen** [realm/realm-cocoa#1835]
I have been trying to find out how to do the following query without any success.

I have a set of Tag objects that I want to query for. I want to have all posts that contains all the Tags in the set. Is there any way to do this currently? I am currently using: `var query = Post("ANY tags = %@", tags)` but it returns all post containing any of the tags. Is there any workaround to this case that I can use until the All operator is implemented? 

```
Post {
    tags: [Tag]
    text: String
}

Tag{
   tag: String
}
```

**Comment by jpsim** [comment]
Until Realm adds support for `ALL` predicates, you'll have to combine your queries like so:

```swift
var query = Post.allObjects()
for tag in tags {
  query.objectsWhere("tags CONTAINS %@", tag)
}
// `query` contains all `Post`s whose `tags` property includes all the queried `tags`
```

**Comment by jonandersen** [comment]
@jpsim thanks for the fast response however with that method I get the following error: 
`RLMArray predicates must contain the ANY modifier'` 

The working query for me was:

```
var query = Post.allObjects()
for tag in tags {
  query = query.objectsWhere("ANY tags = %@", tag)
}
```
