### ISSUE TITLE
Realm Browser Icon Needs Updating

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-cocoa#1836]
I was cruising through the Realm Browser's project file looking at what needs to be updated for our next release, and I noticed that its app icon still had the 'β' beta symbol on it. 

Unfortunately, upon removing the beta badge, all that was left behind a simple, flat, black 'R' on it's own. Needless to say, it looked pretty plain, and definitely didn't fit the app icon design standards of OS X Yosemite.

So, ideally, before we launch v1.0, it'd be great to have a nicer looking icon for the Realm Browser. :)

I just spent around 10 minutes playing with my copy of [Element 3D](https://www.videocopilot.net/products/element2/) and came up with this image:

![realmbrowsericon](https://cloud.githubusercontent.com/assets/429119/7468725/ae5c3430-f33e-11e4-93e5-6d50bad92a9f.png)

It's a OpenGL-rendered version of the Realm 'R' in the same 3D perspective as the Yosemite system apps. It's just to get the ball rolling for now, so what do you think? :)

/cc @yoshyosh

**Comment by TimOliver** [comment]
I just had another idea. If we'd want to continue re-using the Realm pink color, we can always use the "iTunes/iBooks" style as well. :)

![realm-appstorestyle-icon](https://cloud.githubusercontent.com/assets/429119/7471610/c73bd33a-f35b-11e4-96b5-c4eb32c2ad45.png)

**Comment by morqon** [comment]
Definitely needs to be changed. 
My two pennies: shy away from metal effects, and keep circle boarders slim (if any at all).

**Comment by TimOliver** [comment]
The first image shown in the context of the dock.

@morqon Fair enough! The metal does look a little too bright in the scaled down version. If we choose to go with this one, I'll have another play with it.

![realmicondock](https://cloud.githubusercontent.com/assets/429119/7473961/25dd8374-f371-11e4-862e-584cafb3962b.jpg)

**Comment by timanglade** [comment]
Hm in context the perspective looks a bit too strong for me. A bit too LOST

![lost-gift](http://stream1.gifsoup.com/view2/2011699/lost-main-title-o.gif)

**Comment by TimOliver** [comment]
Fair enough. I'll see if I can straighten out the perspective a bit, and like @morqon recommended, make the metal a little less pronounced.

(Actually. Hilariously enough, I think the LOST logo was made with the same tool I was using here! They were both created by the same guy! XD)

**Comment by yoshyosh** [comment]
Great idea :))) I would definitely go a bit more subtle with any effects! I like the pink one the most but being on brand will be key. We've been using the pink style for slack/stackoverflow badge. Can you try two fairly flat styles (black/white and pink)? Having a background seems like it will work well given the general OS X icon styles

**Comment by TimOliver** [comment]
@yoshyosh Cool! Yeah, after @timanglade said the first one seems to look a little 'floaty' with no proper grounding in the Dock. The Yosemite circle design seems a bit better to me.

Alright. I really quickly tried out a black version, as well as removed all of the effects from the 'R' to make it more consistent with our normal brand appearance.

![realmituneslogovariants](https://cloud.githubusercontent.com/assets/429119/7487105/4a612378-f3e3-11e4-96bb-a4d36ece5f62.jpg)

If you'd like to have a play with the coloring yourself, here's a Sketch version of the template I was using. :)
http://www.sketchappsources.com/free-source/600-yosemite-osx-icon-template.html

**Comment by timanglade** [comment]
I like the last pink circle one! pretty close to how we did the Slack icon
and the StackOverflow icon too… Might be worth agreeing on specific
gradient colors though.

**Comment by yoshyosh** [comment]
Can you add this to our [shared design repo](https://drive.google.com/a/tightdb.com/folderview?id=0BzeKUYqyvz3hfmNLdTNPLTVzbUg2SUtzcjBpbTA5VHJkSHNoTnhnUC1ueDJ2VjMzb2dHTHM&usp=sharing)? I'd like to check it out without the white border :)

**Comment by morqon** [comment]
Same. Also like the last pink one. Also think the boarder might be legacy design.

**Comment by mrh-is** [comment]
Made one this morning, @yoshyosh and I iterated a bit, seems close, follows the Yosemite conventions (as I've seen them?). Also have an `icns` file for it (which can't be attached here).
![screen shot 2015-05-06 at 3 24 36 pm](https://cloud.githubusercontent.com/assets/1855036/7505083/1ad4bb94-f404-11e4-82ee-7e9d44ddb204.png)

**Comment by timanglade** [comment]
Maybe we could make that gradient pop a bit more? I really like the depth
of the gradient of the iMessage icon for example, even Atom does it well
too.

On Wed, May 6, 2015 at 3:26 PM, Michael Helmbrecht <notifications@github.com

**Comment by mrh-is** [comment]
@timanglade Your wish is my command! Gradient a bit more visible. Going to be harder to get more without the top being too close to white and the bottom being too dusty. I think this is good until the rebrand. :+1:
![screen shot 2015-05-07 at 11 48 42 am](https://cloud.githubusercontent.com/assets/1855036/7523313/cb9f547e-f4af-11e4-8375-d631731976b6.png)

Review requests: @yoshyosh @TimOliver

**Comment by timanglade** [comment]
Interesting, maybe I’m wrong but it feels like the iMessage icon makes the
gradient pop by going extremely dark on the bottom/right edges, and kinda
light on the top/left edges, but a nice moderate hue without much shift in
the middle. As it stands the center shade of pink is maybe a bit too light
to keep the R very visible in our icon, so maybe we can try something like
that, if I’m not reading the iMessage gradient wrong?

**Comment by mrh-is** [comment]
@timanglade said he wants to lick this, so it must be good!
![screen shot 2015-05-07 at 11 48 42 am](https://cloud.githubusercontent.com/assets/1855036/7526160/4b456952-f4c4-11e4-8552-06d65584548e.png)
