### ISSUE TITLE
Crash when use sort function in 0.90

### ISSUE THREAD

**Issue by AmitBhavsarIphone** [realm/realm-cocoa#1838]
I have face problem when sort the array result
Here is the log.
**core/include/tightdb/link_view.hpp:241: Assertion failed: m_row_indexes.is_attached()
0   Keyboard                            0x002711c7 _ZN7tightdb4util9terminateEPKcS2_l + 394
1   Keyboard                            0x0024cb9d _ZN7tightdb8LinkView3getEm + 312
2   Keyboard                            0x002fba7f _ZNK7tightdb8LinkView15get_sorted_viewENSt3__16vectorImNS1_9allocatorImEEEENS2_IbNS3_IbEEEE + 246
3   Keyboard                            0x00238105 -[RLMArrayLinkView sortedResultsUsingDescriptors:] + 384
4   Keyboard                            0x00235287 -[RLMArray sortedResultsUsingProperty:ascending:] + 202
5   Keyboard                            0x001ae550 _TFC8Keyboard22KeyboardViewController28generatePredictionsForStringfS0_FT_GSaSS_ + 20776
6   Keyboard                            0x001dea04 _TFFC8Keyboard22KeyboardViewController26setPredictionAndSuggestionFS0_FT_T_U_FT_T_ + 1388
7   Keyboard                            0x001dda18 _TTRXFo__dT__XFdCb__dT__ + 56
8   libdispatch.dylib                   0x36880423 <redacted> + 10
9   libdispatch.dylib                   0x3688c2db <redacted> + 850
10  libdispatch.dylib                   0x3688d1fb <redacted> + 106
11  libsystem_pthread.dylib             0x369fde25 _pthread_wqthread + 668
12  libsystem_pthread.dylib             0x369fdb78 start_wqthread + 8
IMPORTANT: if you see this error, please send this log to help@realm.io.**

My code is like below where Exception is arise.
var arrNext = wordT.nextKeys.sortedResultsUsingProperty("frequency", ascending: false)

**Comment by segiddins** [comment]
It looks to me like you're using an older version of Realm -- we did not official support using Realm from multiple processes (such as with as keyboard) until 0.91. Could you try updating to 0.91.5 and let me know if that fixes things for you? Thanks!

**Comment by jpsim** [comment]
@AmitBhavsarIphone could you try updating to the latest version of Realm (currently 0.92.4) to see if the issue persists? Thanks!

**Comment by AmitBhavsarIphone** [comment]
Yes the above issue is solved by using latest version of the RealM 0.92.4, 
Thanks for your quick support and guide.
