### ISSUE TITLE
Using duplicate property definitions in models should throw a more descriptive exception message

### ISSUE THREAD

**Issue by andrelind** [realm/realm-cocoa#1844]
I can't instantiate Realm at all, I just get this assertion:

let r = Realm() // It fails already here!

Assertion failed: (props.count == [NSSet setWithArray:[props valueForKey:@"name"]].count), function +[RLMObjectSchema schemaForObjectClass:], file /Users/realmpro/workspace/Package iOS Swift/tightdb_objc/Realm/RLMObjectSchema.mm, line 102.

**Comment by jpsim** [comment]
Hi @andrelind, you closed this issue so I assume you've worked around this problem. We haven't seen this one before and would appreciate any insight you may have about how this happened and how you fixed it.

**Comment by jpsim** [comment]
Alright @andrelind, @segiddins just helped me understand what happened here. It seems the same property was being declared twice in an `Object` model (perhaps in an extension?). In any case, the assertion message you saw should be improved to be more informative.

**Comment by bdash** [comment]
The following code snippet will result in the assertion failure within `+[RLMObjectSchema schemaForObjectClass:]`:

```
@interface TestObject : RLMObject
@property (nonatomic, copy) NSString *string;
@end

@interface SubTestObject : TestObject
@property (nonatomic, copy) NSString *string;
@end

@implementation TestObject
@end

@implementation SubTestObject
@end
```

**Comment by anbarasu0504** [comment]
Updated to Realm Swift 0.92.1 and can't run my Project

Getting this

Assertion failed: (props.count == [NSSet setWithArray:[props valueForKey:@"name"]].count), function +[RLMObjectSchema schemaForObjectClass:], file /Users/realm/workspace/Package iOS Swift/tightdb_objc/Realm/RLMObjectSchema.mm, line 102.

It was working fine before ..

I checked and I haven't declared same property twice. Even if so, how can I find that ? 

@bdash  How can I pull commits made in #1867 to the framework ? (Am sorry to ask this, I cloned this Repo, but can't find the RealmSwift.framework which I can drag into my project)

**Comment by jpsim** [comment]
@anbarasu0504 is it possible some of your models have two properties with the same name? That's what this assertion is preventing.

To answer your other question, you can build Realm Swift from source in a number of ways, the simplest of which is to use CocoaPods:

```ruby
pod 'Realm', :git => 'git@github.com:realm/realm-cocoa.git'
pod 'RealmSwift', :git => 'git@github.com:realm/realm-cocoa.git'
```

**Comment by jpsim** [comment]
Reopening issue as we've been able to reproduce it without having duplicate property definitions.

**Comment by anbarasu0504** [comment]
Changing dynamic var arrayOfThings = List<Thing>. to
                 dynamic let arrayOfThings = ...

worked :+1: 

@yoshyosh
