### ISSUE TITLE
addObjects has different behaviors by using RLMArray or RLMArrayLinkView 

### ISSUE THREAD

**Issue by kitasuke** [realm/realm-cocoa#1845]
1. Goals
I would like to make sure that `addObjects` method can update some values even though a given primary key's value already exists. However, if there is duplicate value for primary key using `addObjects`, an exception will be thrown. I would like to know whether it's a right way to update the values.

1. Expected results
If it's allowed to update each object's value by using `addObjects`, the method name might not be appropriate. If it's appropriate, there should be some explanation somewhere because it might be confusing.

1. Actual results
One can do `addOrUpdateObjects` even if each object has a primary key, but another one can only do `addObjects` and exception will be thrown if same value for primary key is added.

1. Steps to reproduce, Code sample that highlights the issue
Sample code is below.

Here is the situation.
I already stored some objects in Realm.
Then I'll get some response which has same article id accidentally.
I'll store it again.

This is what I have in Realm

User | id | articles
-------- | ------------- | ---
           | 1 | [Article(id=1, title="test")]

Article | id | title
-------- | ------------- | ---
           | 1 | test 

I would like to add more articles object.
Sample code below is what I did.

```
class name User: RLMObject {
    dynamic var id = 0
    dynamic var articles = RLMArray(objectClassName: Article.className())

    override class func primaryKey() -> String {
        return "id"
    }
}
```
```
class Article: RLMObject {
    dynamic var id = 0
    dynamic var title = ""

    override class func primaryKey() -> String {
        return "id"
    }
}
```
```
let article = Article()
article.id = 1
article.title = "test"
let articles = [article]
RLMRealm.defaultRealm().transactionWithBlock({ () -> Void in
    let user = User.allObjects().firstObject() as! User
    user.articles.addObjects(articles)  // add objects or throw an exception if there is duplicate id in Article
})
```
```
let article = Article()
article.id = 1
article.title = "test"
let articles = [article]
RLMRealm.defaultRealm().transactionWithBlock({ () -> Void in
    let user = User()
    user.id = 1
    user.articles.addObjects(articles)
    User.createOrUpdateInDefaultRealmWithObject(user)  // add or update objects even if there is duplicate one
})
```

If I create a new instance of `RLMObject`, I can add or update objects in `RLMArray`. What I was able to find out is that `[self addObject:obj]` inside `addObjects` method is the key point.
`self` could be `RLMArray` or `RLMArrayLinkView` in this case. 
If it's `RLMArrayLinkView`, `RLMDynamicSet` is called with `RLMCreationOptionsEnforceUnique` option for primary key's value.
If it's `RLMArray`, each value is just added into `_backingArray` and `RLMDynamicSet` is called with `RLMCreationOptionsUpdateOrCreate` and `RLMCreationOptionsAllowCopy` options by `createOrUpdateInDefaultRealmWithObject`
I haven't fully understood how Realm handles RLMArray object yet, so I apologize if I'm wrong. 

Version of Realm/Xcode/OSX
Realm: 0.91.5
Xcode: 6.3.1
Swift: 1.2

**Comment by kishikawakatsumi** [comment]
To be clear, he feels strange that there are differences in behavior in the same method, depending on whether the receiver is standalone or not.

If `user` objects is not standalone, `addObjects()` method throws exception immediately when duplicate primary key.

```
RLMRealm.defaultRealm().transactionWithBlock({ () -> Void in
    let user = User.allObjects().firstObject() as! User
    user.articles.addObjects(articles)  // Throws exception immediately
})
```

But if `user` objects is standalone, `addObjects()` method just update relationship objects instead throwing exception.

```
RLMRealm.defaultRealm().transactionWithBlock({ () -> Void in
    let user = User()
    user.id = 1
    user.articles.addObjects(articles)
    User.createOrUpdateInDefaultRealmWithObject(user)  // Never throws exception
})
```

**Comment by segiddins** [comment]
In general, we try to be lenient in the cases where the user is _not_ definitely doing something that violates the API contract, and only throw exceptions when there's absolutely nothing we can do about it.

**Comment by kitasuke** [comment]
Thanks for your clarification! I get it now.

**Comment by zykis** [comment]
I am wondering, if there could possibly be somewhat like addOrUpdateObject: method for RLMArray? So i could force Realm to update any **nested** object, that is already presents with existing ID.
Or may be i am missing something and may be there is a right way to do that?

Say, i have a following entities structure:
```
class Player: RLMObject {
  long long ID;
  RLMArray<Round*><Round> rounds;
}

class Round: RLMObject {
  long long ID;
  RLMArray<Question*><Question> questions;
}

class Question: RLMObject {
  long long ID;
  NSString* text;
}
```
So, there is to-many relationship Player --> Round
and also to-many relationship Round --> Question
And I'd like to do the following:

```
RLMRealm* realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
Question* question1 = [[Question alloc] init];
question1.ID = 1;

Round* round1 = [[Round alloc] init];
round1.ID = 1;
[[round1 questions] addObject: question1];

Player* john = [[Player alloc] init];
john.ID = 1;
[[john rounds] addObject: round1];
[realm commitWriteTransaction];
```
Seems ok, eh?
Let's assume i get a new Round from an API, parsing it and want to add to existing [john rounds]:
```
Round* round2 = [RoundService obtainWithID:2];
RLMRealm* realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[[john rounds] addObject: round2];
```
Seems fine too, but if in round2 we have a question, with ID, that is already presented in Realm, we'll have an exception.
The workaround for this is to check (while parsing Round) if there is an existing object. If no - add new, else - add existing one, managed object.
I am wondering, if there is any better way to handle this particular case?
Anyway, i really appreciate your work guys. Thanks in advance!
