### ISSUE TITLE
RealmSwift installation instructions cause Signed Resource modified error

### ISSUE THREAD

**Issue by marcvanolmen** [realm/realm-cocoa#1854]
http://realm.io/docs/swift/latest/ This step is manual setup
```
If using Realm in an iOS project, create a new “Run Script Phase” in your app’s 
target’s “Build Phases” and paste the following snippet in the script text field: ${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/RealmSwift.framework/strip-frameworks.sh 
This step is required to work around an App Store submission bug when archiving universal binaries.
```
is causing 
```
A signed resource has been added, modified, or deleted.
```
error.

**Comment by jpsim** [comment]
We're looking into this issue, @marcvanolmen. Until this is resolved, you could simply remove that script phase as it's only required when submitting to the App Store.

**Comment by marcvanolmen** [comment]
I did but then I ran in issue #1850, but I just switched my project in using Cocoapods and that worked.

**Comment by segiddins** [comment]
@marcvanolmen I can confirm that this happens with the strip frameworks script, we're looking into potential fixes.
