### ISSUE TITLE
Deal with multiple users

### ISSUE THREAD

**Issue by marcoscurvello** [realm/realm-cocoa#1857]
I'm working on a multiple user app which creates a new encrypted sqlite database for every new/different user that successfully authenticates/logs in. I'm really impressed by Realm and all it's features, still I am uncertain if theres a way to achieve a similar pattern using Realm. If so any pointers would much appreciated.

Thanks in advance! :wink:  :+1:

**Comment by segiddins** [comment]
Realms are files, so I see no reason why you can't use separate databases for each user if you want to -- you just won't be able to use the `+[RLMRealm defaultRealm]` convenience method. I hope that answers your question?

**Comment by marcoscurvello** [comment]
Thanks so much @segiddins for the explanation, that did it for me! :smiley:
