### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by vivekCZ** [realm/realm-cocoa#1858]
I am using realm for my ios app to store keywords in my keyboard app.

On the every key press I am accessing realm and fetching words for predection. I am doing this for that :

let realmObj = RLMRealm(path: wordDBPath, readOnly: true, error: nil)

And when User press return key on keyboard I am saving all words to same database.

let realmObj = RLMRealm(path: wordDBPath, readOnly: false, error: nil)

When User type more words and long message My app getting crashed with following message:

"open() failed: Too many open files".

**Comment by segiddins** [comment]
@vivekCZ I don't see how that's possible, given that opening a realm as both readonly and readwrite should be throwing an exception. Would it be possible for you to share a reproducible example of this happening?

**Comment by jpsim** [comment]
@vivekCZ were you able to find out more about this issue? If it still happens with the latest version of Realm (currently 0.92.4), we'd really appreciate a sample Xcode project that would help us reproduce the issue. Thanks!

**Comment by segiddins** [comment]
@vivekCZ I'm going to close this issue for now, but feel free to add a comment and reopen if you can reproduce it!
