### ISSUE TITLE
'RLMArray_Private.hpp' file not found in CocoaPods Install RealmSwift

### ISSUE THREAD

**Issue by mtgomes** [realm/realm-cocoa#1859]
I'm getting a 'RLMArray_Private.hpp' file not found (the same for "RLMAccessor.h" , "RLMConstants.h" and other files) while upgrading via cocoa pods from 0.91 to 0.92 using RealmSwift.

Am I doing something wrong or something else I need to do?

Thanks in advance.

PS: I've upgraded the CocoaPods and tried re-installing Realm from scratch with no success

**Comment by segiddins** [comment]
What version of CocoaPods are you using? You'll need to be in at least 0.37.1.

**Comment by mtgomes** [comment]
Yes it's 0.37.1 (mentioned that I did the upgrade but not to what version, sorry about that)

**Comment by segiddins** [comment]
Hm, could you try clearing the cached download of the Realm and RealmSwift pods (`rm -r ~/Library/Caches/CocoaPods/Pods/Released/Realm*`)? You'll then need to force re-installation by deleting the `Pods/Realm*`

**Comment by tanglx61** [comment]
I had the same issue, solved it by running the following commands:
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update

hope this helps with your case.

**Comment by ares-huy-le** [comment]
@mtgomes : My solution is remove Realm in Podfile -> Pod install -> Add Realm in Podfile again -> Pod install. It's work for me.

**Comment by mtgomes** [comment]
Thanks for the great suggestions. It's working now. I removed and re-added the pods and now it's compiling with no errors. This doesn't help a lot, I know, but can't really figure out how it was fixed.

**Comment by jasperblues** [comment]
This issue happened for us too (identified by CI server, then reproduced after a clean checkout). Unfortunately the fixes here don't work. Instead: 

```
Installing Realm (0.94.1)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.92.1.1
Downloading core failed. Please try again once you have an Internet connection.
```
I *do* have an internet connection, and a reasonably decent one. 

To fix: 

* Got colleauge to run steps and commit (we have checked in pods). 
* Failing that I was about to go looking for a Realm.framework binary.

**Comment by jpsim** [comment]
@jasperblues we serve our core builds from AWS S3, which I believe was experiencing issues around the time you posted this. Please check http://status.aws.amazon.com/ next time this happens.

**Comment by jasperblues** [comment]
Hello @jpsim Thanks for the information. We ended up linking Realm as a framework. Perhaps we'll try going back to CocoaPods.
