### ISSUE TITLE
Import Realm using bridging headers

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#1860]
Hi guys,

I'm just getting my feet wet with Swift, so this is probably a really stupid question:

I got an Objective-C class I'd like to use in a new Swift class and therefore imported its header file in my bridging header. Unfortunately, the class itself imports Realm in its header which causes the compiler to bail out and fail. I tried also adding 
```
#import <Realm/Realm.h>
```
in my bridging header but this didn't work either. Any suggestions?

**Comment by alexdd55** [comment]
i did it like 
```
#import Realm/Realm.h
````
and it worked fine for me.

I recommend to use cocoapods for easy integration. way mor comfortable and makes updating way better.

**Comment by tspecht** [comment]
I'm using cocoa pods already. I tried your way, but still not working :/ It then find the Realm.h but inside that file it complains, that Realm/RLMArray.h for example could not be found

**Comment by alexdd55** [comment]
my pod info:
```
source 'https://github.com/CocoaPods/Specs.git'
xcodeproj '../test.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'Realm', '~> 0.92.1'
```

**Comment by tspecht** [comment]
Mhm, I still need to support iOS 7, so I can't use use_frameworks I'm afraid

**Comment by alexdd55** [comment]
then might try to download and integrate Realm manually.
The downlaoded archive got everything you need for swift integration

**Comment by yoshyosh** [comment]
Realm Swift only works for iOS8+ http://realm.io/docs/swift/latest/#prerequisites

**Comment by tgoyne** [comment]
He's using the obj-c interface from Swift, which still supports iOS 7.

**Comment by yoshyosh** [comment]
ah oops :+1:

**Comment by segiddins** [comment]
@tspecht how are you importing Realm in your class' header?

**Comment by jpsim** [comment]
Hi @tspecht and @alexdd55, if you need to use Realm Objective-C from Swift in iOS 7 through CocoaPods, you can use the following in your Podfile (no `use_frameworks!`):

```ruby
pod 'Realm'
```

and your app's Objective-C bridging header:

```objc
#import <Realm/Realm.h>
```

Please reopen this issue if you're still having trouble even after following these steps.

**Comment by ajimix** [comment]
The solution proposed by @jpsim doesn't work. The bridging header complains about `<Realm/Realm.h> ` not found.

**Comment by jpsim** [comment]
My last comment should certainly work. Are you sure your project's configuration isn't interfering with this setup? I'd be happy to look at your project's configuration if you can share it @ajimix.

**Comment by reduxdj** [comment]
cocoapods and realm does not work currently, with .97 and cocoapods

**Comment by jpsim** [comment]
@reduxdj please file a new issue [following our guidelines](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) and we'll be happy to help!

**Comment by wishsoul** [comment]
cocoaPods v1.0 `Clean Build Folder` it works for me!
