### ISSUE TITLE
Improve error message try to sort on multi-level keypaths

### ISSUE THREAD

**Issue by hdoria** [realm/realm-cocoa#1861]
I've been using RLMResults as my data model for my tableview. One of my models has an optional property (date). I need to sort my RLMResults array using this property.

Here's my Goal model:

```swift
class DateObject: RLMObject {
    dynamic var date: NSDate = NSDate()
}

class Goal: RLMObject {
    dynamic var user = User()
    dynamic var name = ""
    dynamic var desc = ""
    ...
    dynamic var targetDate: DateObject?
}
```

Here's my RLMResults (without sort):

```swift
var bodyGoals:RLMResults {
        get {
            var predicate = NSPredicate(format: "user.email = %@ AND ...", user!.email, ...)   
            return Goal.objectsWithPredicate(predicate)
        }
    }
```

This is how I was trying to sort:

```swift
return Goal.objectsWithPredicate(predicate).sortedResultsUsingProperty("targetDate.date", ascending: false)
```

Which gives me the error below (which makes sense):

```swift
Terminating app due to uncaught exception 'Invalid sort column', reason: 'Column named '(null)' not found.'
```

What options do I have now? What would be the best approach to solve this? Is there something like sortedArrayUsingComparator to RLMResults?

**Comment by tgoyne** [comment]
We currently don't support sorting on multi-level keypaths. The error message certainly needs to be improved, though.

**Comment by bdash** [comment]
Sorting by multi-level keypaths is tracked by issue #1277.
