### ISSUE TITLE
'RLMResults' does not have a member named 'generate'

### ISSUE THREAD

**Issue by michaelloistl** [realm/realm-cocoa#1862]
Since updating to 0.92.1 I get that error in case I want to iterate through a RLMResults object.
That was handled in RLMSupport.swift which I removed now from the project due to the dedicated swift framework (Adding RLMSupport.swift results in various compiler errors).
What do I miss here?

**Comment by segiddins** [comment]
What compiler errors are you seeing with RLMSupport.swift?

**Comment by jpsim** [comment]
It sounds like you're continuing to use `Realm.framework` from Swift, which would require linking `RLMSupport.swift`.

To use the dedicated Swift framework (`import RealmSwift`), you'll have to use `Results<T>` instead of `RLMResults`.

**Comment by michaelloistl** [comment]
All working :)
Should have read the doc first.
