### ISSUE TITLE
Error installing RealmSwift with Cocoapods 0.37.1

### ISSUE THREAD

**Issue by bre7** [realm/realm-cocoa#1870]
Error message:
>Errno::ENOENT - No such file or directory - /Users/xxxx/Desktop/yyyyy/Pods/Realm/Realm/module.modulemap

Podfile:
>source 'https://github.com/CocoaPods/Specs.git'

>platform :ios, '8.0'
>use_frameworks!

>pod 'RealmSwift',               '~> 0.92'

**Comment by segiddins** [comment]
What version of CocoaPods are you using?

**Comment by bre7** [comment]
0.37.1

**Comment by segiddins** [comment]
what's the output of `pod install --verbose`? Have you tried deleting the `Pods` directory and re-installing?

**Comment by bre7** [comment]
Forgot to delete Pods/Realm* :X ...
