### ISSUE TITLE
in -Swift.h ,"Type name requires a specifier or qualifier"

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#1873]
hi guys ,i'm using **RealmSwift 0.92**
i have a class 
```swift
class MediaSentenceWord: Object {
   let librarywords = List<LibraryWord>()
}
```
but in the -Swift.h file (to use in objc ) that generated by system,there is a error:
```swift
SWIFT_CLASS("_TtC12eTimeMachine17MediaSentenceWord")
@interface MediaSentenceWord : Object
@property (nonatomic, readonly) /* List<LibraryWord> */ librarywords;
```
__error:Type name requires a specifier or qualifier__
so what's the problem?

**Comment by jpsim** [comment]
Hi @github2016a, I assume you managed to work around the issue since this ticket is now closed. Can you share more details about what happened and how you fixed it?

**Comment by zipme** [comment]
I got the same error here, also wondering how I can work around this..

**Comment by zipme** [comment]
According to this SO question http://stackoverflow.com/questions/29533420/generic-classes-in-frameworkname-swift-h-causes-type-name-requires-a-specifie

I managed to work around this by setting `Build Settings -> Swift Compiler - Code Generation -> Intall Objective-C Compatibility Header` to `No`

**Comment by jpsim** [comment]
@mrackwitz this could be good to add in the troubleshooting guide you've been meaning to write :wink:

**Comment by github2016a** [comment]
@jpsim  
Hi,jpsim,just saw your comment.I solved this problem,by manually altered the -Swift.h file : I deleted the unnecessary classes generated by system,including Realm Object classes **with generic**.
the error Is happened because The -Swift.h used by objc do not support generic 。
so：
```swift
1，Build Settings -> Swift Compiler - Code Generation -> Intall Objective-C Compatibility Header : No
2，Build Settings -> Swift Compiler - Code Generation -> Objective-C Generated Interface Header Name : your edited -Swift.h file.
```

**Comment by billburgess** [comment]
Has anyone found a workaround for this when you actually need to include the compatibility header? Marking private cleans up the error but doesn't do me much good when I need to access the property.

**Comment by jpsim** [comment]
@billburgess if you need to access that property (only from Swift), you can write getter and setter functions for it:

```swift
class MediaSentenceWord: Object {
  private let librarywords = List<LibraryWord>()
  func getLibrarywords() -> List<LibraryWord> {
    return librarywords
  }
  func setLibrarywords(value: List<LibraryWord>) {
    librarywords = value
  }
}
```
