### ISSUE TITLE
List accessors aren't properly initialized in Swift fast enumeration

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#1876]
hi guys ,i'm using RealmSwift 0.92
i have a class
```swift
class MediaSentenceWord: Object {
   let librarywords = List<LibraryWord>()
}
```
```
var results = realm.objects(MediaSentenceWord)
for i in 0...results.count-1{
       println(libResults[i].librarywords.count) // every thing ok
}
```
but if i write this ,there is a problem:
```
for item in results{
        println(item.librarywords.count) // always 0  !!!!!
}
```

**Comment by jpsim** [comment]
We can confirm that this is an issue with Realm Swift preventing relationships from properly resolving during Swift's fast enumeration. We'll have a fix out shortly. Thanks for reporting this.
