### ISSUE TITLE
Incorrect conversion from Realm core string representation to NSString

### ISSUE THREAD

**Issue by kspangsege** [realm/realm-cocoa#1877]
The Cocoa binding currently uses `[NSString initWithBytes:length:encoding:]` to convert strings from Realm core representation (UTF-8) to Cocoa representation (presumably UTF-16). The assumption here is that `initWithBytes:` respects the specified number of bytes, and does not interpret a null byte in the specified buffer as a string terminator. Unfortunately, this assumption seems to be invalid. We have seen examples that strongly suggest that `initWithBytes:` does interpret the specified byte buffer as a zero terminated string. If this is true, we need to find a different way of performing the conversion.

Also, check whether Cocoas UTF-8 <-> UTF-16 conversion functions assume genuine, or some form of modified UTF-8. The observed behavior might be taken as a sign of a modified form of UTF-8 were the null character is not represented as a null byte (and there may be other differences too).

http://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8

If Cocoa uses non-genuine UTF-8, the best solution is probably to use our own UTF-8 <-> UTF-16 conversion functions (these are already used in the Java binding because Java assumes a modified form of UTF-8 natively).

Even if Cocoa assumes genuine UTF-8 in its conversion functions, it may still be necessary to use our own UTF-8 -> UTF-16 conversion function to be able to bypass the (presumed) scan for null termination in `initWithBytes:`.

Note also that I did use our own UTF-8 <-> UTF-16 conversion functions in an earlier version of the Cocoa binding, so it may be possible to find some useful code in the Git history.

See also http://www.cocoabuilder.com/archive/cocoa/174917-nul-characters-in-nsstring-cause-unexpected-results.html.

**Comment by danielpovlsen** [comment]
I cannot reproduce this problem with an isolated test of the various NSString init methods:
```Objective-C
        NSString* foobar = @"foobar";
        NSLog(@"@\"foobar\": %@", foobar);
        NSLog(@"(length = %lu)", (unsigned long)[foobar length]);


        {
            char bytes[] = "foobar"; // this is 7 bytes including terminating null byte, which is required for initWithUTF8String
            NSUInteger size = sizeof(bytes) - 1;

            NSLog(@"--- \"foobar\" ---");
            NSData* data = [NSData dataWithBytes:bytes length:size];
            NSLog(@"dataWithBytes: %@", data);
            NSLog(@"(length = %lu)", (unsigned long)[data length]);

            NSString* str1 = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
            NSString* str2 = [[NSString alloc] initWithUTF8String:bytes];
            NSString* str3 = [[NSString alloc] initWithBytes:bytes length:size encoding:NSUTF8StringEncoding];

            NSLog(@"initWithData: %@", str1);
            NSLog(@"(length = %lu)", (unsigned long)[str1 length]);

            NSLog(@"initWithUTF8String: %@", str2);
            NSLog(@"(length = %lu)", (unsigned long)[str2 length]);

            NSLog(@"initWithBytes: %@", str3);
            NSLog(@"(length = %lu)", (unsigned long)[str3 length]);
        }
        
        {
            char bytes[] = "\0foobar\0\0\0"; // this is 11 bytes including terminating null byte, which is required for initWithUTF8String
            NSUInteger size = sizeof(bytes) - 1;

            NSLog(@"--- \"\\0foobar\\0\\0\\0\" ---");
            NSData* data = [NSData dataWithBytes:bytes length:size];
            NSLog(@"dataWithBytes: %@", data);
            NSLog(@"(length = %lu)", (unsigned long)[data length]);

            NSString* str1 = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
            NSString* str2 = [[NSString alloc] initWithUTF8String:bytes];
            NSString* str3 = [[NSString alloc] initWithBytes:bytes length:size encoding:NSUTF8StringEncoding];

            NSLog(@"initWithData: %@", str1);
            NSLog(@"(length = %lu)", (unsigned long)[str1 length]);

            NSLog(@"initWithUTF8String: %@", str2);
            NSLog(@"(length = %lu)", (unsigned long)[str2 length]);

            NSLog(@"initWithBytes: %@", str3);
            NSLog(@"(length = %lu)", (unsigned long)[str3 length]);
        }
```
Which on both iOS and OS X outputs:
```
@"foobar": foobar
(length = 6)
--- "foobar" ---
dataWithBytes: <666f6f62 6172>
(length = 6)
initWithData: foobar
(length = 6)
initWithUTF8String: foobar
(length = 6)
initWithBytes: foobar
(length = 6)
--- "\0foobar\0\0\0" ---
dataWithBytes: <00666f6f 62617200 0000>
(length = 10)
initWithData: 
(length = 10)
initWithUTF8String: 
(length = 0)
initWithBytes: 
(length = 10)
```

**Comment by kspangsege** [comment]
I acknowledge that this information contradicts my thesis. I think we can safely assume that our string conversion is fine as it is then.

**Comment by kspangsege** [comment]
But it leaves us with a mystery as to why it is possible to open a particular apparently corrupted Realm file in the Realm browser. In the case that I am referring to, as far as I know, the number of bytes that we pass to `initWithBytes:` is some astronomical 64-bit number.

**Comment by danielpovlsen** [comment]
```Objective-C
NSString* str3 = [[NSString alloc] initWithBytes:bytes length:10000000 encoding:NSUTF8StringEncoding];
```
yields: `str3 == null`

**Comment by kspangsege** [comment]
@danielpovlsen, ok, that explains it. Thanks.
