### ISSUE TITLE
Accessing to-many relationship throws exception in Swift 0.92.1

### ISSUE THREAD

**Issue by EsbenRud** [realm/realm-cocoa#1880]
Hi,first of all thanks for a great database, loving it over CoreData. But after 0.92.0 I have discovered what might be an error in your Swift support. This code works before:

```swift
for driver in team.drivers {
    if let drive = driver.getValidDriveForDate(date)
```

But with 0.92.0 and 0.92.1 I get an exception:

```
2015-05-08 16:51:58.003 Driving[10639:227597] *** Terminating app due to uncaught exception 'RLMException', reason: 'This method can only be called on RLMArray instances retrieved from an RLMRealm'
```

If I change the code to:

```swift
for index in 0...team.drivers.count - 1 {
    let driver = team.drivers[index]
    if let drive = driver.getValidDriveForDate(date)
```

Then it works again.

`getValidDriveForDate` look like this:

```swift
func getValidDriveForDate(date: NSDate) -> Drive? {
    return drives.filter("date == %@ and role in %@", date, Drive.ValidRoles).first
}
```
I use filter with a predicate. Am I doing something wrong or is it a bug?

Best regards
Esben Rud Nielsen, NetBryggeriet

**Comment by jpsim** [comment]
Thanks for reporting this, although we're already tracking the issue in #1876 and have a fix pending in #1882. Closing as a duplicate.
