### ISSUE TITLE
Unable to build using RealmSwift 0.92.1 cocoapod

### ISSUE THREAD

**Issue by carlson** [realm/realm-cocoa#1881]
I've got an existing Swift project using the Realm 0.92.1 cocoapod and it works fine. When I attempt to build using the RealmSwift 0.92.1 cocoapod I get a "No such module 'Realm.Private' error message for Aliases.swift, List.swift, Migration.swift, and Object.swift. I followed the cocoapod instructions (http://realm.io/docs/swift/latest/). Did I miss something?

btw - I'm using CocoaPods 0.37.1.

**Comment by jpsim** [comment]
Did you include `pod 'Realm'` in your Podfile? (you shouldn't)
Did you include `use_frameworks!` in your Podfile? (you should)

**Comment by carlson** [comment]
I didn't include pod 'Realm' and I did include use_frameworks! 

To Repro:

* Create new iOS xcode project
* pod init
* edit Podfile to include use_frameworks! and add RealmSwift pod
* pod install (installs Realm (0.92.1) & RealmSwift (0.92.1))
* open RealmPod.xcworkspace
* clean & build
* Error: No such module Realm.Private
* edit Podfile from pod 'RealmSwift' to pod 'Realm'
* pod install (installs Realm (0.92.1))
* clean & build
* Success!

```
platform :ios, '8.0'
use_frameworks!

target 'RealmPod' do
  pod 'RealmSwift' # Change to 'Realm' and it works
end

target 'RealmPodTests' do

end
```

**Comment by segiddins** [comment]
@carlson I can't reproduce the issues you're seeing with the steps provided... Could you zip up your project directory so we can have a look? Thanks!

**Comment by carlson** [comment]
Sure. Thanks!

**Comment by segiddins** [comment]
So, I can reproduce the issue you were seeing, but it's fixed for me if I force re-installation of the Realm pod (and clean the download cache for good measure)

```bash
rm -r Pods/Realm
rm -r ~/Library/Caches/CocoaPods/Pods/Released/Realm
pod install
```

**Comment by carlson** [comment]
@segiddins - worked for me too. Thanks!

**Comment by sxua** [comment]
I had the same problem with the latest `RealmSwift`, but only with 0.36.+ version of CocoaPods, 0.37.+ plays well.
