### ISSUE TITLE
"Could not build Objc module" using RealmSwift with Swift-only source

### ISSUE THREAD

**Issue by jpchmura** [realm/realm-cocoa#1884]
I'm working on a Swift only project and just converted my Realm models to RealmSwift (which is awesome, nice work guys!).  My model is actually shared between 2 apps so I'm building it into a framework (Using cocoapods).  This fails when trying to generate "<module-name>-Swift.h" header file.  Really this file is only needed should there be Objc source code that needs to use the models but it seems to insist on creating it anyway. 
When building this header file the compiler correctly ignores any properties defined as Results<T> however properties defined as List<T> are not ignored.  It just comments the type which obviously causes a compilation error. 

This is what it looks like in the header file.
``` Objective-C
@property (nonatomic) /* List<ModelObject> */ objects;
```

My working theory is that the compiler is confused because List is a descendent of NSObject.  It seems like Xcode / Swift is at fault here.  It works just fine if I delete these lines from the header which is not a very good solution since it gets rebuilt every time.

**Comment by segiddins** [comment]
@jpchmura what exactly is forcing the generation of the `-Swift.h` header? This definitely seems like a Swift bug regardless, so I'd recommend filing a Radar for  at bugreport.apple.com

**Comment by jpchmura** [comment]
I'm not sure.  It may just be default behavior for building a framework since it could in theory be included in an Objc project.  I'll head over there and file a radar.

**Comment by jpchmura** [comment]
I created a bug report for this.  Also I was able to recreate it with a really simple example, not including Realm.   So definitely not a RealmSwift bug but something to be aware of. 

``` swift 
class Foo<T>: NSObject { }

class Bar: NSObject {
    var foo = Foo<String>()
}
```

``` Objective-C 
#import "ProjectName-Swift.h"

// In generated header file
SWIFT_CLASS("_TtC12OpenRadarBug3Bar")
@interface Bar : NSObject
@property (nonatomic) /* Foo<String> */ foo;   // <<-- This fails compilation obviously 
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

```

**Comment by segiddins** [comment]
@jpchmura thanks for filing that radar!
