### ISSUE TITLE
Create unit test for NONE predicate

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#1886]

**Comment by segiddins** [comment]
@yoshyosh testing what behavior in particular?

**Comment by yoshyosh** [comment]
A check that returns objects where none of the predicate results are true. I think it's like the concept of !=

**Comment by jpsim** [comment]
Marking as blocked as this depends on https://github.com/realm/realm-core/pull/1026.

**Comment by bdash** [comment]
#1187 indicates that `NONE` is already supported. I believe this is because `NSPredicate` normalizes it to `NOT ANY`, which should be supported by our path that deals with `ANY`.

**Comment by jpsim** [comment]
Ah yes, I had a suspicion this was the case but couldn't find any supporting evidence. Thanks!
