### ISSUE TITLE
Question about a line:

### ISSUE THREAD

**Issue by RyanCopley** [realm/realm-cocoa#1892]
https://github.com/realm/realm-cocoa/blob/master/Realm/RLMObjectBase.mm#L186

What is the purpose of this thread check here? This is causing crashes in some contexts of AFNetworking (failed requests). I'm not an expert in the realm codebase, but that seems frivolous-- I probably don't know something about how Realm works, though.

I did remove the line and run the tests, and everything passes fine...

**Comment by segiddins** [comment]
That's there to prevent internal data structures from getting corrupted when the row property's destructor is run on an incorrect thread.

**Comment by RyanCopley** [comment]
Could you please re-open this... I'm trying to open a discussion (or solve my confusion) about a confliction between AFNetworking and Realm (or a corner-case I've found). I don't see the need to immediately close issues...

(On the main thread)
```
    for (MyObject* myObject in [MyObject allObjects]) {
        [myObject auth:nil];
    }
```


(MyObject)
```
-(void)auth:(void (^)(BOOL success, NSDictionary* response))cb {
        
    NSString* authURL = [self authUrl]; //Grabs the authentication URL, based on some properties of the MyObject model
    AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
    [manager GET: authURL parameters:nil success:^(AFHTTPRequestOperation *operation, NSData* responseObject) {
                NSDictionary* data = [NSDictionary dictionaryWithXMLData:responseObject];
                [[RLMRealm defaultRealm] beginWriteTransaction];
                self.authToken = [data objectForKey:@"auth"];
                if ([self.originalToken isEqualToString:@""]){
                    self.originalToken = self.authToken;
                }
                [[RLMRealm defaultRealm] commitWriteTransaction];

                 if (cb){
                     cb(YES, data);
                 }
        } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            if (cb){
                cb(NO, nil);
            }
    }];
}
```

This crashes on the -dealloc call in RLMBaseObject, as soon as the HTTP request FAILS. It *only* happens during HTTP Request failure.

**Comment by jpsim** [comment]
For anyone who discovers this issue, we continued the conversation in #1893.
