### ISSUE TITLE
containsString: unrecognized selector sent to iOS 7

### ISSUE THREAD

**Issue by buh** [realm/realm-cocoa#1894]
Hi!
In class `RLMQueryUtil` used selector `containsString` that appeared in iOS 8, but in your docs Prerequisites: iOS >= 7. Do you still support/test iOS 7?
Thank you!

**Comment by kishikawakatsumi** [comment]
Thank you reporting it. We fixed this at https://github.com/realm/realm-cocoa/pull/1896.
