### ISSUE TITLE
multi time query crash

### ISSUE THREAD

**Issue by qingpengchen2011** [realm/realm-cocoa#1897]
I have a class function that retrieve all objects from database and sort the results to get the latest one. And I test it in the testcase. And I run the testcase, it works well. But When I continue to run to testcase and about at my fourth attemp, it crashed. This situation occurs many times.
![3f346dae-d662-4c50-bdd9-321b10f75850](https://cloud.githubusercontent.com/assets/5146161/7555266/20e7bbc2-f778-11e4-8fd8-7414f2d7b3a1.png)
It do print the count variable's value.
![861da07d-8196-4443-9037-e23a28add5d5](https://cloud.githubusercontent.com/assets/5146161/7555293/2a9f14e8-f779-11e4-88e1-622fec6027b6.png)

This is the stack info:
![bb1be618-6167-4860-a73a-876e0e9586ba](https://cloud.githubusercontent.com/assets/5146161/7555299/5553148c-f779-11e4-80e5-81c97294b9d3.png)

**Comment by segiddins** [comment]
@qingpengchen2011 thanks so much for reporting this issue. Since I can't really think of what could be causing this, would it be possible for you to share a sample project that reproduces the issue, either here or privately at help@realm.io? Thanks!

**Comment by qingpengchen2011** [comment]
@segiddins  Hello, I've sent an sample project to  help@realm.io. 
Thanks for help.

**Comment by segiddins** [comment]
The gist of the problem is that you were linking your model class into both your app target and test target, and thus had different versions of the User class, which was confusing Swift's dynamic casting facilities. By only linking the model class to the app target and importing the app target into the test target, the issue goes away.

**Comment by qingpengchen2011** [comment]
@segiddins  I've done what you suggest, and added the parent path to RealmSwift.framework to unit test’s “Framework Search Paths”. But there is linking error in test target. Saying: ld: framework not found Realm for architecture x86_64. I've done some searching, but I can not figure out.

**Comment by qingpengchen2011** [comment]
@segiddins  @realm-ci  Hello, I've figure it out. Just by following the steps described in the Realm home page doc, Maybe I did some misconfigure before.  Thanks for your great help.

**Comment by jpsim** [comment]
We're glad you figured it out!
