### ISSUE TITLE
Swift Bash script fails when Target's app filename contains a space

### ISSUE THREAD

**Issue by acoleman-apc** [realm/realm-cocoa#1899]
The new swift library requires the addition of a bash shell script that strips frame works to avoid the App Store submission bug.

However, whenever the app has a space in the file name(s) (in the Debug-iphoneos directory), the script returns No such file or directory.

**Comment by jpsim** [comment]
Hi @acoleman-apc, thanks for reporting this issue! The problem was that the installation instructions didn't specify to use quotes around the script path, so it should actually be this:

```bash
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/RealmSwift.framework/strip-frameworks.sh"
```

We've updated the installation instructions on our website to reflect this.
