### ISSUE TITLE
Using Carthage -- Realm.framework depends on RealmSwift.framework??

### ISSUE THREAD

**Issue by amccarri** [realm/realm-cocoa#1900]
I have a pure Objective-c (no swift) project that I'm trying to install Realm into.  Everything builds fine but running unit tests I get the following:

```Library not loaded: @rpath/RealmSwift.framework/Frameworks/Realm.framework/Realm```

This is with Realm 0.92.2.

**Comment by amccarri** [comment]
Found the problem.  I am using Carthage and I had to add the RealmSwift.framework to carthage copy-frameworks build phase, but NOT add it to the linked frameworks.

**Comment by jpsim** [comment]
It really shouldn't be necessary to do anything with `RealmSwift.framework` if you're just using `Realm.framework` from Carthage. To double-check, I just followed the "Carthage" installation steps listed here with no issue: https://realm.io/docs/objc/latest/#installation

Can you share the steps you took to produce the error?

**Comment by amccarri** [comment]
My steps were similar, but I already had Carthage set up so Framework build dir was already in my framework search path.  I also didn't add the strip frameworks script yet as this will probably never see an app store build, and I wasn't sure if that's still an issue in XCode 6.3 or not.  

Here's what I did:

# Config
* Xcode 6.3.1 / OSX 10.10.3 / iOS 8.1
* Follow carthage setup instructions in Carthage github README.md

# STR
1. add realm to Cartfile (0.92.2)
1. carthage update
1. link to Realm.framework
1. Add Realm.framework to carthage copy-frameworks
1. build (success)
1. build for test (success)
1. run unit tests (fail)

# Solution:
1. Add RealmSwift.framework to carthage copy-frameworks phase. 
1. run unit tests (success)
