### ISSUE TITLE
Database upgrade from 0.91.3 to 0.92.2 results in corrupted database

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#1903]
Updating Realm with CocoaPods from 0.91.3 to 0.92.2 corrupts the database:

```
Installing Realm 0.92.2 (was 0.91.3)

*** Terminating app due to uncaught exception 'RLMException', reason: 'Invalid database'
```

I have sent you the corrupted database file. Opening it with Realm Browser also says it's invalid.

**Comment by tgoyne** [comment]
The database file appears to have been written by a core build with null-string support, so it can't be opened by one without null-string support.

**Comment by anlaital** [comment]
That'd explain it, then. Closing this as I didn't remember having used null-string support build in the test project.
