### ISSUE TITLE
Subscripting `Results` with a range

### ISSUE THREAD

**Issue by duemunk** [realm/realm-cocoa#1904]
When subscripting a `Results` with a range:
```swift
let objects: Results<SomeType> = Realm().objects(SomeType)
let sliceOfObjects: ArraySlice<SomeType> = objects[0...2]
```
I get the following compile error:
```console
Cannot subscript a value of type 'Results<SomeType>' with an index of type 'Range<Int>'
```

My current workaround is to convert the `Results` to an `Array`:
```swift
extension Results {   
    func toArray() -> [T] {
        var array = [T]()
        for result in self {
            array.append(result)
        }
        return array
    }
}
```
which allows for:
```swift
let sliceOfObjects: ArraySlice<SomeType> = objects.toArray()[0...2]
```

**Comment by segiddins** [comment]
@duemunk this is a known limitation, being tracked by https://github.com/realm/realm-cocoa/issues/1580. In short, we can't make `Results` nor `List` subscriptable with a range until we can use that same type to represent the slice (i.e. we can't have a slice of `Result` or `List` return an array)

**Comment by tgoyne** [comment]
Closing as it's covered by #1580.
