### ISSUE TITLE
Realm comparison operators yield incorrect RLMResults

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#1905]
This is reproduced using Realm 0.92.2.

If you take the following object:

```
@interface Obj : RLMObject

@property NSString *s;
@property int16_t type;

@end

@implementation Obj

+ (NSString *)primaryKey
{
    return @"s";
}

@end
```

Then create some objects:

```
    [realm transactionWithBlock:^{
        for (NSUInteger i = 0; i < 100; ++i) {
            Obj *o = [Obj new];
            o.s = [NSUUID UUID].UUIDString;
            o.type = arc4random_uniform(6);
            [realm addObject:o];
        }
    }];
```

Compare the results (causes assertion):

```
RLMResults *t1 = [Obj objectsWhere:@"type != 2"];
RLMResults *t2 = [Obj objectsWhere:@"type = 2"];
RLMResults *all = [Obj allObjects];
    
NSParameterAssert(t1.count + t2.count == all.count);
```    

I have sent you a reproducible project for this issue.

**Comment by tgoyne** [comment]
Appears to be specific to `query.count()`, as doing anything that makes it build the results table view (e.g. calling `lastObject` ) makes it correct.

**Comment by tgoyne** [comment]
Simplest workaround for now is `[Obj objectsWhere:@"type != 2 AND TRUEPREDICATE"]` (the bug is in the optimized find code that isn't used if there's multiple conditions).

**Comment by tgoyne** [comment]
Will be fixed by https://github.com/realm/realm-core/pull/822.

The bug is specific to `!=` on int properties with no other conditions.
