### ISSUE TITLE
Iterating over List<T> where T has a property of type List<> crashes

### ISSUE THREAD

**Issue by AlDrago** [realm/realm-cocoa#1906]
```Swift 
class ModelA: Object {
    dynamic var myListProperty = List<ModelB>()
}

class ModelB: Object {
    dynamic var blah = List<ModelB>()
}

let a = ModelA()
a.myListProperty.append(ModelB())
        
for b in a.myListProperty { // EXC_BAD_ACCESS here
    println("blah")
}
```
The crash happens only if the list is not empty. 

[Download XCode Project](https://copy.com/sGEhqmpbAXWvJwaI)

![screen shot 2015-05-11 at 15 29 08](https://cloud.githubusercontent.com/assets/1269664/7565713/831bf374-f7f2-11e4-986a-6362c00e7475.png)

**Comment by segiddins** [comment]
@AlDrago this should have been fixed by https://github.com/realm/realm-cocoa/pull/1882, which is included in RealmSwift v0.92.2. Could you try updating and see if that fixes the issue? Thanks!

**Comment by AlDrago** [comment]
No, I am using v0.92.2 already. (And the project uploaded in my first post demonstrate the issue with v0.92.2).

**Comment by segiddins** [comment]
Ah ok, I think I see the issue here -- we need to be checking that the object's `row` property is not NULL.

**Comment by tgoyne** [comment]
`RLMInitializeSwiftListAccessor` either needs to be a no-op if `!_row.is_attached()` or it needs to not be called on standalone objects. First sounds easier.
