### ISSUE TITLE
How to add the items from an RLMResults to an RLMArray or NSArray?

### ISSUE THREAD

**Issue by jrpetersjr** [realm/realm-cocoa#1913]
Is there a way to take the answers in RLMResults and add them into RLMArray or NSArray? I haven't been able to figure it out.

**Comment by segiddins** [comment]
@jrpetersjr, you can call `[rlmArray addObjects:results]` to add the results to an `RLMArray`, or use the following snippet to add the objects in the results to an `NSArray`:

```objc
for (RLMObject *object in results) {
    [array addObject:object];
}
```

**Comment by jpsim** [comment]
And from Realm Swift, the equivalents would be [`listProperty.extend(results)`](http://realm.io/docs/swift/latest/api/Classes/List.html#/s:FC10RealmSwift4List6extendU__FGS0_Q__USs12SequenceType_USs13GeneratorType__FQ_T_) to add `Results` to a `List` and `swiftArray.extend(results)`.
