### ISSUE TITLE
Mutiple realms/threads with RLMObject subclass instance methods writing to its own realm

### ISSUE THREAD

**Issue by hermanolsson** [realm/realm-cocoa#1915]
Is this a secure way of getting the current realm for an RLMObject subclass instance on a specific thread?

```Swift
let realm = Realm(path: self.realm.path)
```

For example. This might be called on different realms on different threads depending on the context.
```Swift
class MyObject: RLMObject {
  ...
  func share() {
    let realm = Realm(path: self.realm.path)
    realm.beginWriteTransaction()
    self.shareDate = NSDate()
    realm.commitWriteTransaction()
 } 
}
```
Are we approaching this the right way?

**Comment by segiddins** [comment]
Just allowing your persisted `RLMObject` subclass to be retained/released on another thread has the potential to cause issues, and in this case you're attempting to modify a property on that object from (potentially) the wrong thread. Our recommended approach is to refetch objects on the thread that you wish to modify them on.

**Comment by hermanolsson** [comment]
Okay, yeah, it feels a bit sketchy. It works fine for now, but we might need to rethink it a bit. We have made a couple of decisions to keep single property changes like this in the model layer, but I see the potential issues related to this.

How about the realm path fetching? Is it save to call self.realm.path or object.realm.path to reach for the path, or will that cause issues as well?

**Comment by segiddins** [comment]
Just allowing the object to be retained/released on a separate thread can trigger exceptions, so you should do your best to not capture your persisted object in any blocks that might be passed to another thread, nor access the `realm` property on them.

**Comment by hermanolsson** [comment]
Affirmative! I'm not totally sure on when it's safe and not, since creating an object in a separate realm (on another thread) will need me to share that object with that realm. The docs only show when creating from a dictionary.

Would this be a better solution based on the case above?

```Swift
class func share(realmPath: String, originalObject: RLMObject) {
  //... do other stuff, like API calls ...

  dispatch_async(someOtherQueue, { () -> Void in
    let realm = RLMRealm(path: realmPath)
    let newObject = RLMObject.createOrUpdateInRealm(realm, withValue: originalObject)
    realm.beginWriteTransaction()
    newObject.shareDate = NSDate()
    realm.commitTransaction()
  })
} 
```

I really want to get this right, since our app is heavily dependant on this working properly.

**Comment by tgoyne** [comment]
Reading just the `path` property from an `RLMRealm` instance that you have direct access to on the wrong thread is safe, but it's not a pattern we recommend because a lot of very similar things aren't.

That bit of code won't work because it's reading the values from an `RLMObject` on a different thread. Since your objects appear to have a primary key, the safe way is to use that to refetch the object on the background thread:

```swift
class func share(realmPath: String, originalObject: RLMObject) {
  //... do other stuff, like API calls ...

  let pk = originalObject.yourPrimaryKey
  dispatch_async(someOtherQueue), {
    let realm = RLMRealm(path: realmPath)
    let object = RLMObject(forPrimaryKey: pk, inRealm: realm)
    realm.beginWriteTransaction()
    object.shareDate = NSDate()
    realm.commitTransaction()
  }
}
```

**Comment by hermanolsson** [comment]
That I knew and still did it wrong. Thanks for the clarification.

I guess this is really two questions now, and regarding the path one, I think I have to go into more detail about our app to present my problems better. Good think I'll join you for the open office hours in just a few minutes. I think we can close this now.
