### ISSUE TITLE
 'Object type 'Object' not persisted in Realm' when creating instances using generics

### ISSUE THREAD

**Issue by erkie** [realm/realm-cocoa#1916]
An exception is thrown in the new RealmSwift `0.92.2` when trying to create an instance using a generic type (for example in a generic class or function).

## Expected results
It worked in `~> 0.91` so it must have been a bug introduced in `0.92`.

## Actual results
I have created a sample project with a README detailing how to steps and stack traces here:
https://github.com/erkie/ReamGenericsBug

## Offending code

```swift
import UIKit
import RealmSwift

class Post: Object {
    dynamic var title = "Default title"
    dynamic var body = "Default body"
}

class GenericExample<T: Object> {
    func create() -> T {
        return T()
    }
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        
        let examplePostGenerator = GenericExample<Post>()
        
        // BLOWS UP HERE
        let myPost = examplePostGenerator.create()
        
        println("Title: \(myPost.title)")
        
        return true
    }
}
```

# Expected output:

`Title: Default title`

## Stack trace

    2015-05-12 08:06:39.130 RealmGenericsBug[52930:5659603] *** Terminating app due to uncaught exception 'RLMException', reason: 'Object type 'Object' not persisted in Realm'
    *** First throw call stack:
    (
        0   CoreFoundation                      0x000000010f958c65 __exceptionPreprocess + 165
        1   libobjc.A.dylib                     0x00000001114c3bb7 objc_exception_throw + 45
        2   Realm                               0x000000010f518653 -[RLMSchema objectForKeyedSubscript:] + 227
        3   Realm                               0x000000010f4ac7eb +[RLMObjectBase sharedSchema] + 123
        4   Realm                               0x000000010f4ab6e5 -[RLMObjectBase init] + 181
        5   RealmSwift                          0x000000010f7a6b61 _TFC10RealmSwift6ObjectcfMS0_FT_S0_ + 49
        6   RealmSwift                          0x000000010f7a6c64 _TFC10RealmSwift6ObjectCfMS0_FT_S0_ + 52
        7   RealmGenericsBug                    0x000000010f3e3c83 _TFC16RealmGenericsBug14GenericExample6createU__fGS0_Q__FT_Q_ + 35
        8   RealmGenericsBug                    0x000000010f3e3f2a _TFC16RealmGenericsBug11AppDelegate11applicationfS0_FTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVSs10DictionaryCSo8NSObjectPSs9AnyObject____Sb + 90
        9   RealmGenericsBug                    0x000000010f3e4144 _TToFC16RealmGenericsBug11AppDelegate11applicationfS0_FTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVSs10DictionaryCSo8NSObjectPSs9AnyObject____Sb + 180
        10  UIKit                               0x00000001101f2788 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 240
        11  UIKit                               0x00000001101f3397 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2540
        12  UIKit                               0x00000001101f61de -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
        13  UIKit                               0x00000001101f50d5 -[UIApplication workspaceDidEndTransaction:] + 179
        14  FrontBoardServices                  0x0000000116c5a5e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
        15  CoreFoundation                      0x000000010f88c41c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
        16  CoreFoundation                      0x000000010f882165 __CFRunLoopDoBlocks + 341
        17  CoreFoundation                      0x000000010f881f25 __CFRunLoopRun + 2389
        18  CoreFoundation                      0x000000010f881366 CFRunLoopRunSpecific + 470
        19  UIKit                               0x00000001101f4b42 -[UIApplication _run] + 413
        20  UIKit                               0x00000001101f7900 UIApplicationMain + 1282
        21  RealmGenericsBug                    0x000000010f3e43a7 main + 135
        22  libdyld.dylib                       0x0000000111d16145 start + 1
        23  ???                                 0x0000000000000001 0x0 + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

## Versions

```bash
$ pod --version
0.37.1
```

Xcode: Version 6.3.1 (6D1002)
Realm Cocoapod: 

```ruby
pod 'RealmSwift', '0.92.2'
```

**Comment by kishikawakatsumi** [comment]
This is temporary workaround, to change "Type Constraint" `Object` to `NSObject`.

Like below:

```swift
class GenericExample<T: NSObject> {
    func create() -> T {
        return T()
    }
}
```

**Comment by segiddins** [comment]
I don't think this is really a Realm bug, but either a quirk or a bug in Swift's type system, when dealing with generic types. As we can see from your example, in this case Swift isn't calling the initializer for the concrete type represented by `T`, but rather the initializer for `T` itself, which is not what is expected.

**Comment by erkie** [comment]
But it did actually work in the previous version of Realm (`~> 0.91.0`) so it has been possible. As such I would call it a bug. Would you classify this as a Realm bug or a Swift bug?

**Comment by segiddins** [comment]
I'd say it's probably a Swift bug.

**Comment by kishikawakatsumi** [comment]
It is probably due to Swift bugs. For example, there is a following code almost the same structure except Realm. This is similar to the code you wrote, it will crash when try to access the name property.

This crash is due to Swift compiler can not dispatch properly `T()` call. Strictly speaking, Swift compiler does not call `init()` of the subclass, the crash occurred at the initial value of the name property is not set.

```swift
class Base {

}

class Sub: Base {
    var name = "John"
}

class Generic<T: Base> {
    var object = T()
}
```

```swift
let generic = Generic<Sub>()
println(generic.object.name) // EXC_BAD_ACCESS
```


If define `require init()` to the base class, it will not occur crash. Because to define the init method, Swift compiler can know that it is guaranteed there is init method in the subclass. So Swift compiler can call the correct subclass of `init()`.


```swift
class Base {
    required init() {} // To fix the issue, to add this line
}

class Sub: Base {
    var name = "John"
}

class Generic<T: Base> {
    var object = T()
}
```

**Comment by erkie** [comment]
Thanks for the great explanation @kishikawakatsumi and thanks @jpsim for making the PR!

In the meantime, this is the workaround that I went with:

If I define my own initializer in an extension and call that it works. So adding this code, and using that initializer in subsequent generic template calls worked:

```
extension Object {
    convenience init(completelyBogusInitializerDoesNothing: Bool) {
        self.init()
    }
}

// T(completelyBogusInitializerDoesNothing: true)
```

**Comment by michaelloistl** [comment]
I'm having also an issue with types since switching to RealmSwift. Here a sample project that demonstrates the issue: https://github.com/michaelloistl/RealmSwiftGeneric
This issue happens with creating, filtering, etc. 
Please let me know if I am doing anything wrong here or if that's an issue with realmSwift or Swift's type system.

**Comment by segiddins** [comment]
@michaelloistl it's possible that @jpsim's pull request (https://github.com/realm/realm-cocoa/issues/1928) might fix your case as well -- feel free to try that branch out, otherwise we'll get around to adding more tests to that branch soon.

**Comment by michaelloistl** [comment]
Any idea when this will be merged into the master to be available as an official version?

**Comment by michaelloistl** [comment]
Adding the required initializer hasn't fixed the issue for me. Not sure if I have missed anything else. Any status update from your side? This issue is currently causing me massive troubles as it breaks all syncing, mapping, etc.
Would need an urgent solution for it, otherwise I need to go back to the obj-c implementation (which I really want to avoid due to massive time constraints).
Any help here would be appreciated!

**Comment by jpsim** [comment]
@michaelloistl we've merged the fix to master. This is the unit test we added to make sure it works:

```swift
func testGenericInit() {
    func createObject<T: Object>() -> T {
        return T()
    }
    let obj1: SwiftBoolObject = createObject()
    let obj2 = SwiftBoolObject()
    XCTAssertEqual(obj1.boolCol, obj2.boolCol, "object created via generic initializer should equal object created by calling initializer directly")
}
```

Are you saying that's failing for you? Or is there some other scenario that is still not covered by the fix?

**Comment by michaelloistl** [comment]
@jpsim if you try the following, the test fails:
````
let objectTypes: [Object.Type] = [SwiftStringObject.self, SwiftBoolObject.self]

for objectType in objectTypes {
    let object = realm.create(objectType)
}
````
The created object will be of type ````Object```` and not ````SwiftStringObject```` or ````SwiftBoolObject````

**Comment by jpsim** [comment]
I'm afraid that's Swift limitation at the moment, @michaelloistl, not something Realm-specific. Take a look at this self-contained Swift code (no Realm dependency in there, you can run this in a Playground):

```swift
import Foundation

class Object {
    init() {}
}

class Realm {
    func create<T: Object>(object: T.Type) -> T {
        return T()
    }
}

class MyModel: Object {}

NSStringFromClass(Realm().create(MyModel).dynamicType) // => 'Object'
NSStringFromClass(Realm().create(Object).dynamicType)  // => 'Object'
NSStringFromClass(MyModel().dynamicType)               // => 'MyModel'
NSStringFromClass(Object().dynamicType)                // => 'Object'
```

**Comment by michaelloistl** [comment]
Thank you @jpsim!
That means that I can't use RealmSwift until Apple fixes that Type issue. That sucks!

**Comment by AlDrago** [comment]
I have been having the same problem, but I found simple temporarily solution. If you want to use the generic function for `NSObject` subclasses only (`RealmSwift.Object` is `NSObject` subclass) you can just create the object in ObjC.

Example:
Objective-C function bridged to Swift:
``` Objective-C
id initClass(Class cls) {
    return [[cls alloc] init];
}
```

Updated example from @jpsim 
``` Swift
class Object : NSObject {
    override init() {
        super.init()
    }
}

class Realm {
    func create<T: Object>(object: T.Type) -> T {
        return initClass(T.self) as! T
    }
}

class MyModel: Object {}

println(NSStringFromClass(Realm().create(MyModel).dynamicType)) // "xyz.MyModel" tadaaa
println(NSStringFromClass(Realm().create(Object).dynamicType)) // "xyz.Object"
```
