### ISSUE TITLE
[RealmSwift] Method to get object instance by primary key and .linkingObjects for inverse relationship

### ISSUE THREAD

**Issue by malcommac** [realm/realm-cocoa#1917]
Hi guys,
First of all thank you for your awesome work! it is a breath of fresh air compared to CoreData :)
Looking at RealmSwift project I've not found a way to get an object instance by specifying it's primary key.
How can I do that?
Should I really use NSPredicate and return the first (and only) result (if any)?

Another problem is this.
I've a Device object and an User object. User has a devices properties while Device should have an inverse relationship property. As [the doc says](http://realm.io/docs/swift/latest/#inverse-relationships) this is my code portion:

```swift
class Device: Object {
	var user: User {
		return linkingObjects(Device.self, forProperty: "devices")
	}
}
```
but it does not compile (Type of expression is ambiguous without more context).
By adding Object() or Device() before the call the result is the same. Where I'm wrong?
(I've also noticed that the code reports an old call ```linkingObjectsOfClass``` while the doc above say ```Object().linkingObjects(_:forProperty:) ```)

**Comment by segiddins** [comment]
You can use `realm.objectForPrimaryKey(User.self, key: "key")` to return the `User` object with the given primary key.

`linkingObjects` returns an array, so changing your computed property to the following should work:

```swift
var users: [User] {
    return linkingObjects(User.self, forProperty: "devices")
}
```

**Comment by malcommac** [comment]
Yeah, it works like a charm.
So it's not possible to get a many to one relationship? I'm sure I've a single User for each device.

**Comment by segiddins** [comment]
You can only have explicit one-to-many relationships at the moment, so you'll need to manually set a `user` property on your object.

**Comment by ataibarkai** [comment]
> so you'll need to manually set a user property on your object

What do you mean by that @segiddins?

Have another *stored* property `user` on each `Device`, in addition to the `devices` property on `User`?

Is there a more elegant way to achieve this for one-to-one relationships?

**Comment by segiddins** [comment]
@ataibarkai either approach should work!

**Comment by jpsim** [comment]
I'd also recommend @ataibarkai's approach if you only expect to have a single object linking from that property.

**Comment by jpsim** [comment]
Oh, and thanks for reporting that the docs were outdated, @malcommac, they're now up-to-date: http://realm.io/docs/swift/latest/#inverse-relationships
