### ISSUE TITLE
How to use a model object in working threads situation (read only)

### ISSUE THREAD

**Issue by marcvanolmen** [realm/realm-cocoa#1922]
We have dozens of working threads trying to use one Realm object (with relationships), now currently we get the

Realm accessed from incorrect thread

Which is a great feature, but I would like to detach an object I load from this Realm database. 
Because:

• the object will be used in multiple threads in read only mode, and I don't want to load the object all the time again from database 
• each of this working thread needs their own realm for the moment and I don't know how many threads the OS will create in the NSOperationQueue. 

is there something like realm.detach(anObject)? i looked at the Api docs in Swift Docs and couldn't see anything.

I currently do this on every start of one of the working tasks. 
```
var aRealm = Realm()
var aResult = aRealm.objects(CMProject).filter("localID = '\(self.projectID)'")
```
But this is getting called 20000 times in my case.

**Comment by segiddins** [comment]
You can create a shallow, standalone copy of a persisted object by doing

```swift
let project = CMProject(value: persistedProject)
```

**Comment by marcvanolmen** [comment]
Indeed that workedI just tested it, it also worked with the relationships models that were linked to 
```
class CMProject: Object {

        var clips = List<CMClip>()

}
```

I was able to access the full model hierarchy in the working thread like that.

thanks for quick response.

**Comment by segiddins** [comment]
Ah, well that must be a happy coincidence from some of the refactors of that code path I did a couple of weeks ago! Glad to hear that this approach will work for you!
