### ISSUE TITLE
[Solved] Not working in 10.10.3

### ISSUE THREAD

**Issue by 1above** [realm/realm-cocoa#1923]
When you copy the framework in 10.10.3 and you want to use it, it will give you an error when importing RealmSwift that the module is not built for 10.9. 

However if you get this error just make sure you change inside RealmSwift.framework > Resources > Info.plist change under DSDTKName from 10.10 to 10.10.3 and it will work! Have a good day!

**Comment by jpsim** [comment]
Hi @1above, are you saying that you were unable to use the prebuilt Realm Swift OS X framework in a Mac app until you changed the contents of the framework's plist?

Can you outline how you had installed Realm Swift in the first place, and what the final configuration was? Thanks!

**Comment by 1above** [comment]
Well I installed it through Alcatraz and then imported the framework into the project.Then the error popped up that the file was built in for 10.9 and I use 10.10.3. But when I changed the .plist it worked for some reason.

**Comment by segiddins** [comment]
Wait, I'm confused about how you got things working. Alcatraz is a package manager for Xcode plugins, and it shouldn't have anything to do with installing `RealmSwift.framework`. Could you please detail how you installed `RealmSwift` that lead to the error you were seeing? Thanks!

**Comment by jpsim** [comment]
Hi @1above, could you please elaborate? What did you install through Alcatraz? Which `.plist` did you update?

**Comment by segiddins** [comment]
@1above I'm going to close this issue for now, but feel free to reopen if you're still having issues!
