### ISSUE TITLE
[RealmSwift] Errors in Swift->ObjC Generated Header for Realm Objects with List<> Properties

### ISSUE THREAD

**Issue by leegoodrich** [realm/realm-cocoa#1925]
RealmSwift v0.92.2
XCode 6.3.1

In a project with mixed Swift / Objective-C code, target fails to compile due to missing type information for List<> properties in the generated Swift->ObjC header. Here is a snippet of the generated ObjC interface for one of my affected classes:

```objective-c
@interface RealmPlaylist : Object
@property (nonatomic, copy) NSString * __nonnull name;
@property (nonatomic) NSInteger id;
@property (nonatomic, readonly) /* List<RealmTrack> */ tracks;
@end
```

The compiler complains that tracks "requires a specifier or qualifier", which definitely seems to be the case.

The docs say to use the Realm-ObjectiveC framework for projects with mixed codebases, so I'll migrate over to that one and have to unfortunately give up all the nice Swift-ness. I initially assumed I could get away using RealmSwift as my Objective-C code does not use any of the Realm objects, but they do use other Swift objects defined in the generated header.

Generally, XCode simply forgoes generating interfaces exposing Swift features that are incapable of providing an Objective-C equivalent, such as generics and Swift-style enums. Is that not possible here?

**Comment by segiddins** [comment]
Thanks @leegoodrich -- we've seen a couple of reports of this earlier, and it appears to be a swift bug. We recommend using Realm Objective-C if you will need to use Realm from both Swift and Objective-C in the same project.

**Comment by jpsim** [comment]
What does your `RealmPlaylist` class definition look like in Swift? I think this happens when attempting to expose `List` properties to Objective-C as `dynamic`, but then Objective-C can't represent the generic.

So what happens if you define your property as `public let tracks = List<RealmTrack>()` rather than `public dynamic var tracks = List<RealmTrack>()`? (assuming that's what you're doing)

**Comment by leegoodrich** [comment]
I have it defined like so:

```swift
class RealmPlaylist: Object {
    dynamic var name : String = ""
    dynamic var id : Int = -1

    let tracks = List<RealmTrack>()
```

Adding the 'public' keyword to tracks makes no difference in the generated header

**Comment by jpsim** [comment]
I was speaking to @nkirby earlier, who had hit the same issue, but managed to work around it by making his `List` property internal, and exposing the equivalent of `public func tracksInPlaylist(playlist: RealmPlaylist) -> Results<RealmTrack> {…}`. @nkirby can you comment on that?

**Comment by leegoodrich** [comment]
So, I noticed that my Results<> properties are not being included in the generated header, and whipped up this quick hack to test as a workaround:

```swift
public class RealmPlaylist: Object {
    dynamic var name : String = ""
    dynamic var id : Int = -1

    private let _tracks : List<RealmTrack> = List<RealmTrack>()
    public var tracks : Results<RealmTrack> {
        get { return _tracks.filter("") }
    }
```

Not sure if an empty-string predicate returns all values or not, but you get the idea. Any reason you think this plus adding some custom setters to wrap append() and extend()  wouldn't work? Probably more of a PITA than just switching over to the Objective-C framework, but might work for limited uses while waiting for a fix.

**Comment by segiddins** [comment]
This is probably due to `Results` being a native swift class, whereas `List` inherits from `RLMListBase`, which is an `NSObject` subclass declared in Objective-C.

**Comment by leegoodrich** [comment]
Ah, @jpsim, you updated right when I was finishing my comment! Yeah, so it sounds like that works as a work-around. Well, I figure you guys will figure out a solution here (or bug Apple on Radar enough to get them to fix it in the next Swift update, let me know if you need a dupe). I might go ahead with this for now.

**Comment by segiddins** [comment]
This is a known swift issue: https://twitter.com/UINT_MIN/status/598247846639370240

**Comment by jpsim** [comment]
I'm closing this issue since it's out of our hands, but I've opened #1926 to make sure we document this as a limitation and provide work-arounds. Thanks for reporting @leegoodrich.

**Comment by shahankit** [comment]
@jpsim Can implementing a getter function for private List objects instead of creating two variables as mentioned by @leegoodrich.

**Comment by segiddins** [comment]
@shahankit yup!

By the way, I believe this has been fixed in the Xcode 7 betas.

**Comment by shahankit** [comment]
Ok so, List no longer are required to be declared as private in Xcode 7.
