### ISSUE TITLE
Nesting of objects

### ISSUE THREAD

**Issue by depl0y** [realm/realm-cocoa#1930]
I have been working on a PR that will make RealmSwift support nesting of `Object` classes.

Currently it works like this:

```
import RealmSwift

public class DemoObject: Object {
	
	dynamic var name: String = "DemoObjectName"
	
	public class NestedObject: Object {
		
		dynamic var name: String = "NestedObjectName"
		
	}
}

extension DemoObject {
	
	 public class NestedObject2: Object {
		dynamic var name: String = "NestedObject2Name"
	}
	
}
```

This results in the tables **`DemoObject`**, **`NestedObject`** and **`NestedObject2`**. But because you can now nest classes, this will cause clashes with other nested classes with the same name (mostly the reason to perform nesting is the naming clashes).

What would be a good naming convention for the tables? Are there already any thoughts about the way this should be done?

My proposal would be to use something like **`DemoObject.NestedObject`** and **`DemoObject.NestedObject2`** as table names.

What are your thoughts about this?

**Comment by depl0y** [comment]
I dropped my changes in my forked cocoa-realm repository. You can check them out here.

https://github.com/depl0y/realm-cocoa/commit/c6b02dbb49b131e70e33132e556ebfe642771bb7

I feel to n00b to actually submit a PR at this moment, till we probably have figured out some of the consequences of these changes (table naming, etc).

**Comment by depl0y** [comment]
Ok, one of the things I am coming across at the moment (with these changes) is that you can't set up a relation correctly. 

For example:
```
extension DemoObject {
	 public class NestedObject2: Object {
		dynamic var name: String = "NestedObject2Name"
		dynamic var nestObject: DemoObject.NestedObject = DemoObject.NestedObject()
	}
}
```

This throws an error in the `RLMProperty.mm` file at `setTypeFromRawType` where it checks the type of properties. the className variable in the following piece of code is actually `NestedObject` instead of `DemoObject.NestedObject`.

```
else {
	// for objects strip the quotes and @
	NSString *className = [_objcRawType substringWithRange:NSMakeRange(2, _objcRawType.length-3)];
	
	// verify type
	Class cls = [RLMSchema classForString:className];
	if (!RLMIsObjectSubclass(cls)) {
		@throw RLMException([NSString stringWithFormat:@"'%@' is not supported as an RLMObject property. All properties must be primitives, NSString, NSDate, NSData, RLMArray, or subclasses of RLMObject. See http://realm.io/docs/cocoa/api/Classes/RLMObject.html for more information.", className]);
	}
	
	_type = RLMPropertyTypeObject;
	_objectClassName = className;
}
```

It may be that I am approaching this the wrong way.

**Comment by jpsim** [comment]
Keep in mind that Realm is a cross-platform database and that any table created from one binding should be accessible from another. So using dots in the table name may be a deal-breaker.

Can I ask *why* you're interested in supporting nested models? If you're interested in the stylistic effect, could you not use a nested typealias?

```swift
class A: Object {}

class B: Object {
    typealias NestedA = A
}
```

We're open to reviewing a PR adding support for nesting model classes, but it should add clear value and keep Realm's promise of cross-platform compatibility.

**Comment by depl0y** [comment]
Of course you can ask that :). In my project I really miss namespaces.

I for example have a class called `Light` which is a light specifically connected to a HomeWizard device. Then I also have a `Light` class which is connected to a Hue Bridge device.

Because there are currently 4 different lights I have to support, which all have different properties and due to the lack of polymorphism in Realm. I want to have class names like `HomeWizard.Light` and `Hue.Light` to make my code more readable.

Ok, I understand my story is quite confusing. Let me try to create a small diagram:

![screen shot 2015-05-13 at 19 27 08](https://cloud.githubusercontent.com/assets/111713/7616620/1c41e874-f9a6-11e4-83e9-98b8ab43e713.PNG)

My `HomeWizard` and `Hue` class both conform to the `Controller` protocol. The `HomeWizard Light` and the `Hue Light` have a relation to either the `HomeWizard` or the `Hue` class. The `Light` classes conform to a protocol called `Device`.

Not so sure this makes my story less confusing... sorry.

**Comment by jpsim** [comment]
So why not do the following?

```swift
class BaseLight: Object {
  // some common Light properties
}
class HomeWizardLight: BaseLight {}

class HomeWizard: Controller {
    typealias Light = HomeWizardLight
}
```

You can now use `HomeWizard.Light` to refer to `HomeWizardLight`, and cross-platform compatibility is maintained.

**Comment by depl0y** [comment]
Well, I haven't though of that... *crap*

**Comment by jpsim** [comment]
I don't think the additional complexity, potential bugs, performance impact, maintenance, cross-platform issues are worth the feature. Especially since the workaround is so simple and complete, unless I'm missing something.

**Comment by depl0y** [comment]
Probably not ;). Well at least it was a day well spent debugging through Realm. Thanks.
