### ISSUE TITLE
Add iOS Objective-C CocoaPods Dynamic Example

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#1939]

**Comment by rbaulin** [comment]
@jpsim @tgoyne mapping between transient NSObjects and RLMObjects would be so much easier with dynamic schema.

I have found a great example in [tests](https://github.com/realm/realm-cocoa/blob/123f97cdb2819397e289e088558f36e365e712a7/Realm/Tests/DynamicTests.m), but unfortunately it seems to be using private headers for now. Do you have plans to public source the API in the near future?
