### ISSUE TITLE
Question:  One - Many Relationships and Transactions

### ISSUE THREAD

**Issue by ArEnSc** [realm/realm-cocoa#1941]

**Comment by segiddins** [comment]
@ArEnSc It's not clear hear what you're asking about. Feel free to elaborate, and reopen the issue. Thanks!

**Comment by ArEnSc** [comment]
Lets assume I have a one to many relationship

1 Person to Many Dogs

and I work with the RLMArray and modify a Dog RLMModel and commit the transaction 
Does this change reflect on the original Person RLMModel ? 

I would assume it does ? Or do I have to commit the transaction using the Person RLMModel ?

What I mean is do I save with the root aggregate (Person RLM Model) or can I save with the Child (Dog RLMModel) ?

**Comment by segiddins** [comment]
@ArEnSc you actually save the entire `RLMRealm`, and not individual objects, nor individual segments of your object graph.

**Comment by ArEnSc** [comment]
Can you give me a quick example ?

**Comment by segiddins** [comment]
Sure! We actually have a great section on writes in our docs, at http://realm.io/docs/objc/latest/#writes. I hope the docs' examples help explain things!

**Comment by ArEnSc** [comment]
Okay so this what I am trying to do, unify my create delete update logic into one interface called saveObjectGraphWithRoot: ....

if ( rootObject.primarykey  == nil) // assuming it doesn't have a primary key then it must be persisted
else if (rootObject.primarykey !=nil) // it has primary key then it can be updated.
else if (rootObject.isMarkedForDelete = YES) // delete this

So two questions to help me out, in the latest version of Realm ...
Have you included primary key properties on the objects by it's self ? or do I have to override the function to get generate a primary key? 
```Obj-C 
+ (NSString *)primaryKey {
    return @"key"; // generate key here ?
}
```
Are the primary keys generated when the object is created in memory ? or when the object is committed ?

**Comment by segiddins** [comment]
@ArEnSc as http://realm.io/docs/objc/latest/#models says, `+[RLMObject primaryKey]` just returns the _name_ of the primary key proper -- you set the actual property as you would any other object.

**Comment by ArEnSc** [comment]
Hey Thanks alot! I got it to work out! I think I am gonna update the documentation to make it clear some time thanks!
