### ISSUE TITLE
Validate all ObjectSchemas have >= 1 column

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#1943]
Ensure that every table has at least one property or back link column, otherwise Core won't be able to track inserted "rows" after re-opening the Realm.

**Comment by segiddins** [comment]
Keep in mind, some people like to have 'abstract' superclasses that they never initialize, so this would require making `+[RLMObjectBase shouldPersistToRealm]` public.

**Comment by tgoyne** [comment]
We could make zero-property objects work by just inserting a dummy int column if there's zero persisted properties.

**Comment by segiddins** [comment]
But then we'd need to verify that no descendant object schemas have the same name?

**Comment by tgoyne** [comment]
Just inserting a column, not adding an RLMProperty to the array of properties, so it wouldn't be inherited.

**Comment by segiddins** [comment]
Sure, I can do that, but then it will go back to showing up in the browser.

**Comment by segiddins** [comment]
Hm... preferably we'd just throw an exception when trying to `RLMCreateOrGetRowForObject` when there are no public columns nor backlinks (or core could do it in `insert_empty_rows`, it would probably be more performant that way).

**Comment by mrackwitz** [comment]
This was implemented in core and first shipped with its version 1.3.1.
