### ISSUE TITLE
Better documentation & debugging of mmap issues

### ISSUE THREAD

**Issue by timanglade** [realm/realm-cocoa#1944]
1. Docs should have a section about all various types of mmap errors you might encounter, including the version pinning issue.
2. Throw a specific error from Realm when there is an mmap exception, link to docs explaining mmap errors
3. If possible, we should automatically detect version pinning (with excessively large number of old versions (I remember someone in Copenhagen having some code for that?) and log a warning when this happens, with a link to the specific section of the docs explaining version pinning and how to resolve it
4. Regardless of whether or not we can detect version pinning is happening, there should be a way to log when read transactions open & close, so people can look for unclosed read transactions. (Or similar.)

**Comment by jpsim** [comment]
We've made some significant improvements in this area up until our 1.0 release. We'll reopen something like this if we see reports of mmap issues in the future.
