### ISSUE TITLE
app is frozen, I back after few minutes and I have error

### ISSUE THREAD

**Issue by sebasx** [realm/realm-cocoa#1945]
Hello,

sometimes on my back when app is in background and I back to foreground I have "The Realm is already in a write transaction". App return me that error on all time, after few seconds, minutes (like some transaction is opened and not finished never) but why? I have ease data to insert and fast iPhone 5S, it should be finished in second. I use  "transactionWithBlock" format always, not "beginWriteTransaction" / "commitWriteTransaction".

**Comment by sebasx** [comment]
It's looks like some transaction which started in the same moment when app go to background will be never finished

**Comment by segiddins** [comment]
@sebasx we'd love to look into this, would it be possible to share an example project that reproduces the issue? Thanks!

**Comment by jpsim** [comment]
@sebasx following up on our request for a reproducible case. Without that, I'm afraid we don't have much to go on.

**Comment by segiddins** [comment]
@sebasx I'm going to close this issue for now, but feel free to reopen it if you come up with a reproducible case!
