### ISSUE TITLE
Unable to use new RealmSwift syntax

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1952]
I changed over to RealmSwift and removed RLMSupport.swift.

Now when I change ```let backgroundRealm = RLMRealm.defaultRealm()```(which has no errors) to ```let backgroundRealm = Realm()```, I see these errors: 

Invalid use of '()' to call a value of non-function type 'module<Realm>'
and
Expected module member name after module name

Could someone please help me figure out what I am missing?

**Comment by angrybear11** [comment]
In any swift files using realm, you need to change your import statements from `import Realm` to `import RealmSwift`.

**Comment by jpsim** [comment]
Thanks for answering, @angrybear11. That's most certainly the appropriate solution, as Swift is likely confused between `Realm` the module and `RealmSwift.Realm` the type.
