### ISSUE TITLE
Using Realm in Cocoapods above iOS 7

### ISSUE THREAD

**Issue by amycheong19** [realm/realm-cocoa#1954]
I need to use Realm in my Pods but it only allow iOS above 8. I changed  to use static framework but ended up I got a lot of errors even if I followed the steps I use in my app

Error: embedded dylibs/frameworks only run on iOS 8 or later
"std::runtime_error::what() const"
"std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(char const*) const", referenced from:

**Comment by segiddins** [comment]
@amycheong19 can you please try removing the Realm framework from your project, and re-integrating by following the instructions at http://realm.io/docs/objc/latest/#installation? Thanks!

**Comment by segiddins** [comment]
@amycheong19 I'm going to close this issue for now, but feel free to re-open if you're still running into trouble!
