### ISSUE TITLE
Update README for objc/swift split

### ISSUE THREAD

**Issue by timanglade** [realm/realm-cocoa#1955]
Currently our README has many old links that now resolve to the Objective-C docs. We should rewrite the necessary parts of the README to avoid this and point to both Objective-C and Swift resources equally.

Also bear in mind that the README is automatically picked up and used as the main page for our [Jazzy docs](http://realm.io/docs/swift/latest/api/index.html) and [CocoaDocs](http://cocoadocs.org/docsets/RealmSwift/0.92.3/)

**Comment by jpsim** [comment]
This was done in #1981.
