### ISSUE TITLE
RLMNotVersioned has different values in 32- and 64-bit

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#1957]
`RLMNotVersioned` is initialized like so:

```objectivec
    const NSUInteger RLMNotVersioned = (NSUInteger)-1;
```
This results in `RLMNotVersioned` having the value 4294967295 in 32-bit, but 18446744073709551615 in 64-bit. This could result in incorrect behavior when moving a Realm that was created on 32-bit device to a 64-bit device.

**Comment by bmunkholm** [comment]
I think this must be fixed before Rel 1.0, and thus be a P1.

**Comment by astigsen** [comment]
Will this be a breaking change (will it change the file format)?

**Comment by bdash** [comment]
I don't think so. As @tgoyne noted in #1967, the schema version is always updated to an actual version before the initial transaction is committed. The differing values were only apparent in the commit log, since different entries were generated for 32- and 64-bit.

**Comment by kspangsege** [comment]
Please talk to @simonask about this. He already committed a fix here https://github.com/realm/realm-cocoa-private/commit/96d310f3418e3a94104976a60d61da4ecc46a9ba.
