### ISSUE TITLE
InvalidDatabase Error when accessing a encrypted database using REALM_DISABLE_ENCRYPTION=YES

### ISSUE THREAD

**Issue by Fab1n** [realm/realm-cocoa#1958]
I can't get it working...
I generate a realm database with encryption, ship it with my app, move it to library folder and then try to access the path using a RLMRealm.

I correctly flag it with REALM_DISABLE_ENCRYPTION=YES, but it is catching an exception `File::AccessError` with a text "invalid database".

If I disable debugging and remove the env variable, the app crashes...

So, now, I don't know, what to do anymore. Using the same database completely without encryption works as desired. 

Please provide help, otherwise I cannot stick with Realm, though I like the db a lot

**Comment by Fab1n** [comment]
When will the underlaying debugging issue be fixed? We cannot roll out if we are not able to debug...

**Comment by danielpovlsen** [comment]
Hi Fab1n,

Setting `REALM_DISABLE_ENCRYPTION=YES` _disables_ all encryption code and thus only work with non-encrypted databases. If I misunderstand your issue please reply with reproduction steps and I will look into it in more detail.

Cheers,
Daniel

**Comment by Fab1n** [comment]
Thanks for your great support. Finally fixed it. Everything is like you said it should be!
