### ISSUE TITLE
Unable to inherit from RLMRealm

### ISSUE THREAD

**Issue by cfeckardt** [realm/realm-cocoa#1965]
As a developer I am unable to subclass RLMRealm because the convenience methods call [RLMRealm alloc] instead of [self alloc], causing the initializer to instantiate the base class.

**Comment by segiddins** [comment]
Why are you trying to subclass RLMRealm? It's not really intended to be subclassed.

**Comment by cfeckardt** [comment]
I'm looking to hook into the lifecycle of RLMObjects and I want to trigger specific events as individual objects change in the realm, in a more granual way than RLMNotification currently allows me to do.

**Comment by segiddins** [comment]
@cfeckardt a lot of Realm's internals are implemented in terms of functions not inside `RLMRealm`, so even overriding `RLMRealm` methods wouldn't guarantee that you'd be able to hook into Realm in the places you'd like. We're actually working on implementing fine-grained notifications at the moment, you can track that at https://github.com/realm/realm-cocoa/issues/601.

**Comment by cfeckardt** [comment]
There are a number of reasons why one might want to hook in to the public methods that I could think of. Running validations on objects before they are written to the database comes to mind. This patch would make that possible by inheriting from RLMObject (setValue) and RLMRealm (commitWriteTransaction)

**Comment by segiddins** [comment]
@cfeckardt I understand the desire to hook into Realm objects' life cycle events, but we believe the best way to do so will be when we expose fine-grained notifications that can be used a building blocks for things like this. Since `RLMRealm` (and many parts of `RLMObject`) are not built to be subclassed, you'd run into lots of _really_ weird behavior where your overridden methods would never be called when you expected them to be, since those methods are really just an interface to a lot of Realm's underlying functionality. We'd also run into issues with our caching of realm instances, since we could be returning an instance of the wrong class.

I hope this explains a bit why this isn't something we plan on supporting directly, but if there are specific use cases you're interested in, let us know and maybe we can thing of other ways of implementing them!

**Comment by cfeckardt** [comment]
Consider this use-case:

```objective-c
// In my RLMRealmSubclass
- (void) addObject:(RLMObject *) obj {
  if([obj isKindOfClass:[RLMObjectSubclass class]]) {
    [self.pendingChanges addObj:object];
  }
  [super addObject:obj];
}
// Others ...

- (void) commitWriteTransaction {
  BOOL valid = YES;
  for(RLMObjectSubclass x in pendingChanges) {
    valid &= [x valid];
  }

  if(valid) {
    [super commitWriteTransaction];
  } else {
    [self cancelWriteTransaction];
    // Perhaps raise an error as well?
}
```

How could you implement this with the notifications that are being implemented?

There is no expectation of any methods being called from within the object, or them being called from the outside, as the only callers of these methods, are in the users application, and the subclass delegates functionality to the superclass as necessary.

**Comment by segiddins** [comment]
In that case, your best bet would just be to use composition and make a wrapper around `RLMRealm` that adds your functionality, rather than trying to do it via subclassing.

**Comment by cfeckardt** [comment]
Yes, that would work well for the methods that are explicitly defined in RLMRealm, but not in this case:

```objective-c
SomeRealmObject * obj = [SomeRealmObject allObjects].firstObject;

[myRealm beginWriteTransaction];
obj.someAttribute = @"something";
[myRealm commitWriteTransaction];
```

For that to work you would require, in your SomeRealmObject:

```objective-c
- (void)setValue:(id)value forKey:(NSString *)key {
    [super setValue:value forKey:key];
    if([self realm] && [self valueForKey:[[self class] primaryKey]]) {
        [self changed];
    }
}

- (void) changed {
    if(![[self realm] isKindOfClass:[MyRealmSubclass class]]) {
        return;
    }
    
    MyRealmSubclass * realm = (MyRealmSubclass *)[self realm];
    
    [realm objectChanged:self];
}
```

which only works when RLMRealm is subclassed.

**Comment by segiddins** [comment]
I'm trying to understand what exactly is the feature you're trying to implement here... if we can sketch that out, maybe I'll have an easier time understanding what some alternative implementations are?

**Comment by cfeckardt** [comment]
Sure,

By extending RLMRealm and RLMObject I've implemented two things:
1. Fine grained notifications (with ReactiveCocoa)
2. Custom object validations - whenever I edit an object (or create it) within a write transaction, my custom RLMRealmSubclass validates any changes, before committing them. For example, validating the e-mail field for a user.

The reason for case 1, is because I want to sync my database with a remote service, and update the user interface as each synced object is written to the database. And the reason for case 2, is because I uh, want each object to be valid ...

The first case is covered in #601, but the second case is not.
For the second case I could manually call a validate-method on each object, but that is just poor form and makes the code somewhat ubiquitous and complicated, and is prone to bugs.

I looked at the threading cache, that code basically takes whatever initWithPath... returns, and adds it to an NSMutableDictionary. So I don't think that my proposed change, would cause any problems (in fact, I've been testing it rather extensively over the past few days, and have as of yet not discovered any problems at all. The subclass is cached correctly, and returns my subclass as expected.

My custom initWithPath in RLMRealmSubclass looks like this:

```objective-c
- (instancetype) initWithPath:(NSString *) path key:(NSData *)key readOnly:(BOOL) readOnly inMemory:(BOOL) inMemory dynamic:(BOOL) dynamic error:(NSError **) error {
    self = [super initWithPath:path key:key readOnly:readOnly inMemory:inMemory dynamic:dynamic error:error];
    if(self) {
        self.changes = [NSMutableDictionary new];
    }
    return self;
}
```

**Comment by cfeckardt** [comment]
Poking around a bit, this might also solve #1994 ?

**Comment by jpsim** [comment]
There are a few reasons why we're hesitant to make RLMRealm subclass-able and we should really share those with you.

One of them is that there are many parts of the codebase that assume that `RLMRealm` is just a single class, and not a subclass. [RLMRealm caching](https://github.com/realm/realm-cocoa/blob/v0.92.4/Realm/RLMRealmUtil.mm#L29-L58) to name just one example.

Also, to support subclassing RLMRealm, we'd need to write tests to make sure that in whatever arbitrary way users subclass and override functionality, the database file should never become corrupted, or other internal state should be resilient to such modifications. This is very difficult to do in a general sense.

Not to mention the additional support load of users trying to subclass RLMRealm and inevitably running into corner cases. We have our hands more than full already with even just supporting users who use Realm's public API, and we have to be quite careful about making any changes that would increase that support load and take time away from us fixing bugs and writing new features.

Finally, to echo what @segiddins has said here, we're very happy to work with you to improve Realm for everyone, including reviewing your work to add fine grain notifications and custom object validation (something that's useful to *all* users of Realm). If that's not appropriate for these changes, then I'd encourage you to find ways other than subclassing, like composition, to achieve your goals.

**Comment by cfeckardt** [comment]
@jpsim I understand your reluctance to make any changes. As of now, I'll remain on my branch and rebase it with every release until it breaks.

I would be happy to share my work with object validation and notifications for someone to have a look at, but it requires a little bit more work on my end first (as I make some assumptions about the objects and primary keys). Ideally I should split this into two separate pull requests too.

As soon as I have had the time to make my code a little bit more generic, I'll make a new issue and share it with the rest of the community. I will try to get around to doing it this week.

**Comment by jpsim** [comment]
Thanks for understanding, and please do let us know how we can help!
