### ISSUE TITLE
autoreleasepool for dispatch_async now necessary in new version of Realm / RealmSwift

### ISSUE THREAD

**Issue by alexanderjarvis** [realm/realm-cocoa#1970]
Hey there!

The most recent versions of Realm introduced some new functionality called "Interprocess communication" by means of a notifier that internally uses a `kqueue`.

I have found that in our app this notifier doesn't go away unless we wrap everything in an `autoreleasepool` (so that the Realm is `deinit` and also the notifier is stopped).

The problem is quite severe as basically the thread usage continues to climb (as we are using `dispatch_async`) until the point when no new network requests can be made by the app.

Wrapping stuff in `autoreleasepool` inside the `dispatch_async` seems to fix the issue. This was not an issue in previous versions of Realm however (we also migrated to RealmSwift at the same time).

Some guidance on how to properly use Realm and GCD would be helpful as at this stage I've tried various things including keeping a Realm instance around for a specific serial queue but found that the queue is not always equal to the thread so although my test case would work, it would fail when running as an app.

We don't actually care for the notifier as we call `realm.refresh()` on the main thread realm manually when there is a write transaction anyway (by means of callback). Being able to create a Realm inside `dispatch_async` that doesn't also create a notifier could be a solution for this pattern.

In addition to this, if we are creating new Realm instances in `dispatch_async` blocks where of course sometimes there are cached instances if on the same pthread, how do we effectively limit the number of concurrent operations without using a serial queue?

**Comment by bdash** [comment]
Is the key issue that you're hitting that after creating Realms on various dispatch queues, threads become tied up and you're unable to make new network requests?

As for guidance on using Realm with GCD:

* Realm uses thread confinement for its objects, so you need to ensure that all work with a given object is performed on the same thread. Since GCD doesn't guarantee that all blocks submitted to a given serial queue will execute on the same thread, you'll need to get a fresh Realm instance inside each block.

* Wrapping work in autorelease pools is beneficial since GCD makes no guarantee as to how timely its own autorelease pools will be drained. Keeping Realm instances alive in undrained autorelease pools will result in higher than necessary footprint, and other related issues.

**Comment by tgoyne** [comment]
#1975 will significantly mitigate this, but you can still run into issues with autoreleased realm objects if you have your own long blocking operations on background queues -- the autorelease pool for a GCD worker thread is drained only when the queue is empty, and the resulting long-lived RLMRealm will pin the data for its version, resulting in the realm file growing with each write transaction.

**Comment by bigfish24** [comment]
:+1:!

**Comment by alexanderjarvis** [comment]
Yes that is the key issue. And thanks for the tip about GCD draining.

That PR which moves things to an NSThread surely just moves the problem elsewhere. It looks like it creates a new Thread each time rather than reusing one thread?

**Comment by bdash** [comment]
There's a relatively small, hard limit on the number of worker threads that can service dispatch queues (64, when I last checked). In contrast, the normal thread limit is much higher (> 2,000), so it's significantly less likely to be reached accidentally.

**Comment by alexanderjarvis** [comment]
That depends what your application is doing..

I think there must be a better solution?

What is wrong with using NSNotificationCenter?

**Comment by bdash** [comment]
I wrote up #1976 to track further reducing the number of threads.

**Comment by bdash** [comment]
`NSNotificationCenter` cannot listen for notifications posted by other processes, and so isn't usable for this purpose.

The change in #1975 combined will prevent the dispatch worker threads from being tied up by `RLMNotifier` and interfering with your networking. Adding autorelease pools around the work you perform on dispatch queues will prevent the number of threads used from growing beyond the number of Realms you're using concurrently, and should also serve as a workaround until #1975 makes it into a release.

Please let me know if you feel that this doesn't address your issue.

**Comment by alexanderjarvis** [comment]
Thanks!

So just to understand further, the notifier is supposed to broadcast when there are changes in the Realm (of the same path)?

And you are using kqueue because the db core is in C++ right?

So really the (single) thread that contains kqueue to monitor for changes should maintain (weak) references to the Realms in order to broadcast to them.

**Comment by bdash** [comment]
See [Thomas's recent blog post](http://realm.io/news/thomas-goyne-fast-inter-process-communication/) for why a named pipe and kqueue is used, and #1975 for further thoughts on reducing the number of threads used for observing notifications.
