### ISSUE TITLE
Realm Swift submission to AppStore fails with Carthage

### ISSUE THREAD

**Issue by pietbrauer** [realm/realm-cocoa#1971]
Hello 👋,

I ran into another issue with Carthage, AppStore submission and Realm and maybe one of you has an idea.

I installed it using the guide and realm-cocoa and it worked fine.

I also did the `copy-frameworks` thingy:

![screen shot 2015-05-21 at 13 44 51](https://cloud.githubusercontent.com/assets/759730/7747903/95e406a2-ffbf-11e4-9dc9-9be34605fa85.png)

Here is the error I get:

![screen shot 2015-05-21 at 13 36 29](https://cloud.githubusercontent.com/assets/759730/7747907/9d1a5d90-ffbf-11e4-9e5d-2598a113c667.png)

From the command line it gives me the following error:

```bash
$ bundle exec ipa distribute:itunesconnect --upload -f AirportQuiz.ipa --verbose
security: SecKeychainItemCreateFromContent (<default>): The specified item already exists in the keychain.
/Applications/Xcode-6.3.2.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter -m upload -f Package.itmsp -u me@example.com -p ******



Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/Users/piet.brauer/Documents/Projekte/iOS/AirportQuiz/Package.itmsp - Error Messages:
		ERROR ITMS-90034: "Missing or invalid signature. The bundle 'io.Realm.Realm' at bundle path 'Payload/AiportQuiz.app/Frameworks/RealmSwift.framework/Frameworks/Realm.framework' is not signed using an Apple submission certificate."
An error occurred when trying to upload the build to iTunesConnect.
Run with --verbose for more info.

```

Thanks guys!

**Comment by pietbrauer** [comment]
@jspahrsummers had a good hint on twitter. He suspected that the nested framework might not be signed correctly, which sounds reasonable to me too. I will open another issue on Carthage because I think the issue is on their side. Feel free to close this one.

Twitter convo: https://twitter.com/jspahrsummers/status/601396290560217091

**Comment by segiddins** [comment]
@pietbrauer thanks for reporting this, but I'm 99% sure the issue is with us and not carthage -- see https://github.com/realm/realm-cocoa/issues/1907 (which we're working on addressing in https://github.com/realm/realm-cocoa/pull/1942).

**Comment by pietbrauer** [comment]
@segiddins Thanks, I was late to the game as always. Will follow the other issues and the PR then. Thanks for the hint!
