### ISSUE TITLE
Running Queries on the Background Thread (GCD)

### ISSUE THREAD

**Issue by ArEnSc** [realm/realm-cocoa#1973]
When I run a query is it best to perform it on the main thread or a background thread?
I understand that the RLMResults is lazy.
I would assume that when I use a predicate I should perform the predicate query on the background thread because it needs to order the data resulting in blocking the main thread?

**Comment by tariq235** [comment]
In my project I have called all predicate and operations on background thread and then returned final results on main thread.

**Comment by tgoyne** [comment]
You currently can't pass RLMResults between threads, so if you need it on the main thread you'll need to run it there.

**Comment by ArEnSc** [comment]
Okay so that means that I don't really need to run the queries on the background thread because it should require little to no compute time.?

**Comment by yoshyosh** [comment]
For most cases (a majority of the time) you should be fine doing that. Realm lazy loads down to the property so it's really fast.

If you really need to query in the background, you can use primary keys, then build an array of primary keys that you pass to the main thread and requery against. Or you can manually build an NSArray in the background and pass that to the main thread

**Comment by puttin** [comment]
Maybe #1097 is related

**Comment by ArEnSc** [comment]
Solved guys, Run them on the main thread

**Comment by jpsim** [comment]
For anyone landing here looking for the ability to handoff objects between threads, we're tracking that in #1097.

**Comment by alexliubj** [comment]
@yoshyosh  
As you mentioned above, I was trying to use NSArray and initwith with array something like that and then I got a new array objects `A` with retrieved realm array object `B`. But when I tried to use this `A` in my main thread (assume `B` was retrieved from a gcd background queue thread) it is still having the `REALM, accessing from differentness thread ..` something like that error. How should I fixed the according to what you said like `a primary key `, do you have any simple example by your hand?

Thanks,

**Comment by yoshyosh** [comment]
I believe this is the simplest example general https://github.com/matthewcheok/Realm-JSON#working-with-background-threads. The main idea is you want to query realm looking for objects that are `IN` your array. So use the `IN` query. Hope this helps!
