### ISSUE TITLE
Is there any way to cancel ongoing insertion on Realm DB ?

### ISSUE THREAD

**Issue by tariq235** [realm/realm-cocoa#1974]
I can cancel AFNetworking API request but if insertion is in progress and user tapped logout then i want to cancel the ongoing insertion and perform deleteAllObjects

**Comment by segiddins** [comment]
@tariq235 you can use [`-[RLMRealm cancelWriteTransaction]`](http://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/cancelWriteTransaction) to cancel your current write transaction.

**Comment by tariq235** [comment]
@segiddins  Before applying cancelWriteTransaction I have to check whether inWriteTransaction is in progress. Correct ?

Because I just got exception i.e. Can't cancel a non-existing write transaction

**Comment by jpsim** [comment]
That's correct, you can only call `cancelWriteTransaction` if there's a write transaction to cancel.

**Comment by tariq235** [comment]
Ok great.

I am going to call this on logout to remove everything:

RLMRealm *realm = [RLMRealm defaultRealm];
    if ([realm inWriteTransaction]) {
        [realm cancelWriteTransaction];
    }
    [realm beginWriteTransaction];
    [realm deleteAllObjects];
    [realm commitWriteTransaction];

**Comment by jpsim** [comment]
In that code, `inWriteTransaction` will always return false because that `RLMRealm` instance will have just been created.

If you need to cancel write transactions, you should do so from those specific write transactions. You could just change that code to:

```objc
RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[realm deleteAllObjects];
[realm commitWriteTransaction];
```

If there are write transactions on other threads already running, they will complete before this deletion code because write transactions are always performed serially in Realm.

**Comment by tariq235** [comment]
I see.. I thought it will cancel my write transaction for other threads. 

I have another screen where user can fetch plenty of records on background thread but user has always option to logout the app. And as per the requirement I have to clean the database on logout.

The problem is if write transaction on other thread is in progress and on logout if I deleteAllObjects then there will be mismatch.

**Comment by jpsim** [comment]
> The problem is if write transaction on other thread is in progress and on logout if I deleteAllObjects then there will be mismatch.

That won't be a problem because write transactions are a *blocking* operation in Realm. So if a write transaction on another thread is in progress and you call `deleteAllObjects` on logout, the deletion write transaction will wait for all other write transactions to complete before running.

**Comment by jpsim** [comment]
Please reopen this issue if you have any further questions.
