### ISSUE TITLE
A single RLMNotifier should service all RLMRealms accessing the same path

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#1976]
Currently each `RLMRealm` creates its own `RLMNotifier`, and thus has a dedicated thread parked waiting for notifications. When there are multiple `RLMRealm`s for a single path, this leads to redundant threads parked waiting for notifications. A single `RLMNotifier` could wait for notifications and broadcast to all `RLMRealm`s that share the path.

**Comment by bdash** [comment]
An alternative could be to have a single `RLMNotifier` for all realms. The approach described above seemed conceptually simpler on first thought.

**Comment by tgoyne** [comment]
The reason for the current design was just that trying to share notifiers made everything way more complicated and the overhead appears to be completely insignificant other than that the extra open() call to open the named pipe is surprisingly expensive.

**Comment by mrackwitz** [comment]
I think this was fixed in 0.97.
