### ISSUE TITLE
Remove duplicate object method ?

### ISSUE THREAD

**Issue by wgywgy** [realm/realm-cocoa#1978]
How to remove duplicate object method in RLMResult with @property? (@property may be two to judge)

**Comment by segiddins** [comment]
@wgywgy are you asking for a way to do `distinct` queries? If so, we have an open issue that's tracking adding that feature at https://github.com/realm/realm-cocoa/issues/1103.

**Comment by wgywgy** [comment]
it slove the problem of read, but I want save the distinct result.

**Comment by jpsim** [comment]
You're likely looking to use [`-[RLMRealm deleteObjects:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/deleteObjects:) along with some logic to determine what constitutes a duplicate object.

For example, if you considered a model to be unique based on some value pair `int1`/`int2`, you could remove duplicates with the following code:

**Model**

```objc
@interface MyModel : RLMObject
@property NSInteger int1;
@property NSInteger int2;
@end
@implementation MyModel
@end
```

**Usage**

```objc
RLMRealm *realm = [RLMRealm defaultRealm]; // or some other Realm
NSMutableSet *seenIntegerPairs = [NSMutableSet set];
NSMutableArray *duplicateObjects = [NSMutableArray array];
for (MyModel *object in [MyModel allObjectsInRealm:realm]) {
  NSDictionary *integerPair = @{@"int1": @(object.int1), @"int2": @(object.int2)};
  if ([seenIntegerPairs containsObject:integerPair]) {
    [duplicateObjects addObject:object];
  } else {
    [seenIntegerPairs addObject:integerPair];
  }
}
[realm writeTransactionWithBlock:^{
  [realm deleteObjects:duplicateObjects];
}];

// All duplicate `MyModel` objects with the same `int1`/`int2` pair have been deleted
```

**Comment by jpsim** [comment]
Please reopen this issue if you have any further questions, @wgywgy
