### ISSUE TITLE
how to compare string use filter

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#1979]
hi guys,i'm using RealmSwift.
**but how to compare string using filter:**
```swift
class Person: Object {
    dynamic var name : String = ""
}
```
For example, there are four Persons ("A","B","C","D"), how can i get those with name before C.
```swift
realm.objects(Person).filter(name <= 'C') // error
```

**Comment by segiddins** [comment]
@github2016a try the following:

```swift
realm.objects(Person).filter("name <= 'C'")
```

Notice that the entire `filter` method call is now a string.
