### ISSUE TITLE
Any mass inserting features in realm?

### ISSUE THREAD

**Issue by kyawmyintthein** [realm/realm-cocoa#1980]
Is there any mass inserting features for Objective-C?

**Comment by segiddins** [comment]
@kyawmyintthein Realm doesn't have any bulk-insert specific features, however enumerating through a list of items and calling `+[RLMObject createInRealm:withValue:]` for each object you wish to create should do the trick.

**Comment by kyawmyintthein** [comment]
thanks @segiddins
