### ISSUE TITLE
Realm Predicate

### ISSUE THREAD

**Issue by WayneNotTaken** [realm/realm-cocoa#1983]
Hi There

I am using the new realm 0.92.3 and my predicate is for some reason ordered by id.  I am using a for loop on specific id's from an array and return results.  example my id array [21,2,3,5] (previously ordered).  If I use a realm predicate to return something like 'name' from a specific id in that order (id = 21, id = 2 etc), the predicate orders the realm objects ascending in terms of id.  E.g name for id = 2, id = 3, id = 5 and not is the above mentioned order.

**Comment by segiddins** [comment]
@WayneNotTaken could you please share the code you're using to construct your result?

**Comment by WayneNotTaken** [comment]
Sure.  

   for var i=0; i < gigIdArray.count; i++ {
            
            let ii = gigIdArray[i]
            
            
            let artistPredicate = NSPredicate(format: "id = %@", argumentArray: [ii])
                let details = realm.objects(Gigs).filter(predicate)
            
            
            for event in details { // 2
                let eventDetails = event  as Gigs
                let artistNames = eventDetails.artists
                let gigDate = eventDetails.startDate
                
                
                self.gigArtistsName.append(artistNames)
                self.gigDate.append(gigDate)
                
            }

So my gigIdArray reads as follows [58, 38, 12, 73, 72], if i run a println(artistPredicate) it returns in that order.  But if I run a println on details it returns the object ordered accending but gigId. e.g 12,38,58 etc.

This snippet of code worked on the old realm release.

**Comment by jpsim** [comment]
Filtering objects has no guarantee of ordering in Realm, so you should used [`Results.sorted(_:)`](http://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sortedU__FGS0_Q__USs12SequenceType_USs13GeneratorType__FQ_GS0_Qd___) for your details:

```swift
for gigID in gigIdArray {
  let details = realm.objects(Gigs).filter("id = %@", gigID).sorted("id")
  for eventDetails in details { // 2
    self.gigArtistsName.append(eventDetails.artists)
    self.gigDate.append(eventDetails.startDate)
  }
}
```

**Comment by WayneNotTaken** [comment]
Thanks JP. Half asleep here. Thanks so much for your help.

**Comment by jpsim** [comment]
haha, no problem! anytime
