### ISSUE TITLE
Support for querying object hierarchies

### ISSUE THREAD

**Issue by voidref** [realm/realm-cocoa#1987]
I would like a way to get a `Result` that contains not only the exact class type, but also it's descendants.

For example, I have:

    BaseObject <- DerivedOne
    BaseObject <- DerivedTwo
    BaseObject <- DerivedTwo <- DerivedThree

I would like to query for all `Objects` that are, or derived from `BaseObject` in a single `Result`

<3 Realm, thanks!

**Comment by segiddins** [comment]
@voidref this is something we plan on doing, you can track progress on it at https://github.com/realm/realm-cocoa/issues/1109!

**Comment by voidref** [comment]
Thanks! Following that one now.
