### ISSUE TITLE
how to compare string use filter

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#1989]
thanks guys,sorry i did not descripe my issue clearly yesterday #1979.
i'm using RealmSwift 0.92.1
i did not **find a way to compare string using filter**:
```swift
class Person: Object {
    dynamic var name : String = ""
}
realm.write{
        var A = Person()
        A.name = "A"
        var B = Person()
        B.name = "B"
        var C = Person()
        C.name = "C"

        realm.add(A)
        realm.add(B)
        realm.add(C)
}
var obj = realm.objects(Person).filter("name <= 'B'")
// error:'Invalid operator type', reason: 'Operator type 1 not supported for string type'
```
**<=** do not support string.

**Comment by puttin** [comment]
Or something like
```swift
A.value = "1"
B.value = "2"
var obj = realm.objects(Person).filter("value.integerValue <= '2'")
```

**Comment by jpsim** [comment]
The reason an exception is being thrown when attempting to perform those queries (`name <= 'B'` or `value.integerValue <= 2`) is that strings cannot be compared using the following operators: `<`/`<=`/`>`/`>=`.

It's unclear what `name <= 'B'` is attempting to represent. `Person objects with a name property whose length is less than the length of 'B'` comes to mind, but that's certainly not valid NSPredicate syntax.

As for the second example, the `value` property (a string) has no property named `integerValue` persisted in Realm.

For more information on how NSPredicates work, we've created an NSPredicate Cheatsheet that you can find here: https://realm.io/news/nspredicate-cheatsheet/

There's also Apple's [NSPredicate Programming Guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Predicates/Articles/pUsing.html) which is a must-read.

**Comment by puttin** [comment]
```swift
import Foundation

var number1Str = NSString(string: "1")
var number2Str = NSString(string: "2")
var number3Str = NSString(string: "3")
var number4Str = NSString(string: "4")
var number5Str = NSString(string: "5")

var array = NSArray(objects: number1Str, number2Str, number3Str, number4Str, number5Str)
var predicate = NSPredicate(format: "self.integerValue < 4")

var result = array.filteredArrayUsingPredicate(predicate)

println(result)
```

will works

**Comment by jpsim** [comment]
What you're referring to is the ability to perform a selector (integerValue) as NSArray does when evaluating a predicate. If you want to filter your objects beyond what Realm offers in its query capabilities, you'll have to do so yourself.

**Comment by themythIOS** [comment]
How to deal with words with apostrophe with filter...  like..

theName = "Soarin' Eagle"
let query = try!Realm().objects(myQuery_Realm).filter("name = '\(theName)'")

Error: Unable to parse the format string

**Comment by jpsim** [comment]
use NSPredicate's formatter rather than string formatting:

```
theName = "Soarin' Eagle"
let query = try!Realm().objects(myQuery_Realm).filter("name = %@", theName)
```

also, please don't comment on such old issues, it's a sure way for others to miss your comment.
