### ISSUE TITLE
Default NSDate in defaultPropertyValues Bug ? 

### ISSUE THREAD

**Issue by ArEnSc** [realm/realm-cocoa#1991]
When initializing the object I appear to get nil for NSDate date and then when I am saving it appears to be a null value.

```objective-c
+(NSDictionary *)defaultPropertyValues
{
    NSDate* date = [NSDate date];
    return @{@"id":@"",@"name":@"",@"isMarkedForDelete":@NO,@"complete":@YES,@"imagePath":@"",@"startDate":date,@"value":@0.00};
}

or 

+(NSDictionary *)defaultPropertyValues
{
    return @{@"id":@"",@"name":@"",@"isMarkedForDelete":@NO,@"complete":@YES,@"imagePath":@"",@"startDate":[NSDate date],@"value":@0.00};
}

Does not appear to set the NSDate to the today date? 


```

**Comment by jpsim** [comment]
It's curious that `[NSDate date]` is returning null in your examples. `+[RLMObject defaultPropertyValues]` is called whenever your object is created, so the `startDate` property of your object should always be the time at which it was created.

Could you send us a sample project that we could run to reproduce the issue you're seeing? Thanks!

**Comment by ArEnSc** [comment]
So I fixed this issue it was a misunderstanding on my end I will probably make modifications to the documentation as a result. I had assumed that the parent properties of the child would be inherited without calling super so..

```Objective-C

// Parent

+(NSDictionary *)defaultPropertyValues
{
    NSDate* date = [NSDate date];
    return @{@"id":@"",@"name":@"",@"complete":@YES,@"imagePath":@"",@"startDate":date,@"completeDate":date,@"dateLastDateActivated":date,@"value":@0.00,@"activityType":@0};
}


// Child
+(NSDictionary *)defaultPropertyValues{
    
    NSMutableDictionary* properties = [[super defaultPropertyValues] mutableCopy];
    [properties addEntriesFromDictionary:@{@"hasChildren":@YES}];
    
    return properties;
}
```

**Comment by jpsim** [comment]
I'm glad you worked it out, @ArEnSc!
