### ISSUE TITLE
Shallow Copies of Realm Objects do not correctly shallow copy children in 1 to many relationships.

### ISSUE THREAD

**Issue by ArEnSc** [realm/realm-cocoa#1992]
I understand in Realm to update an object that has been retrieved I must update it in this context.

```objective-c

// Creating a book with the same primary key as a previously saved book
Book *cheeseBook = [[Book alloc] init];
cheeseBook.title = @"Cheese recipes";
cheeseBook.price = @9000;
cheeseBook.id = @1;

// Updating book with id = 1
[realm beginWriteTransaction];
[Book createOrUpdateInRealm:realm withValue:cheeseBook];
[realm commitWriteTransaction];
```
When I try and change the values of the cheeseBook.title it appears to assert saying that I need to do it between a write and commit transaction.

Is there a quick way to copy over the previous values and only change the values that I would need to change? i.e
I don't want to write a function for this. Any cues? 

```objective-c

// Creating a book with the same primary key as a previously saved book
Book *cheeseBook = [[Book previousValues:olderCheeseBook]];
// id is copied over
cheeseBook.price = @1000;

// Updating book with id = 1
[realm beginWriteTransaction];
[Book createOrUpdateInRealm:realm withValue:cheeseBook];
[realm commitWriteTransaction];
```

**Comment by jpsim** [comment]
It's simpler than you think... you can just mutate objects in-place, as long as those mutations are done from within a write transaction:

```objc
[realm beginWriteTransaction];
olderCheeseBook.price = 1000;
[realm commitWriteTransaction];
```

**Comment by ArEnSc** [comment]
The issue with doing updates that way, is that it litters the code with begin and commit write transactions, in areas where you want to update the object.

I wrote a wrapper service as the data service, it relies on the fact that fact that updates are done with an Id

and create update delete are all unified under the save interface.
so create if it does not have an id
update if it does have an id
delete if it is marked for delete.

This would help me update objects without much boilerplate through a uniform interface, if there was a function to perform the quick mapping of two objects that would be ideal since I cannot 'modify properties outside of the begin and commits' .

**Comment by segiddins** [comment]
You can create a standalone (un-persisted) copy of your persisted object by using `-[RLMObject initWithValue:persistedObject]`, but I'm not sure if that's really answering your question?

**Comment by ArEnSc** [comment]
I think this is what I could be looking for but it's causing a Realm Accessed from a different thread issue when clearly I am accessing the child from the background thread. I believe the initWithValue:PersistedObject give me a half hour and ill let you know

**Comment by ArEnSc** [comment]
Alright so that is the issue.

So when I use
//Main thread
 RLMObject* new =  [RLMObject initWithValue:persistedObject], then access a read on another thread it

// Send to background thread to be saved.
[save onbackgroundThread:new]

// Background thread
new.id -> assertion
 says that I am trying to access the property from another thread, which is true. I went from main to background.

**Comment by jpsim** [comment]
That's indeed a constraint when using Realm, that you can only use objects from the thread on which they were created (or added to the Realm in this case).

You'll have to re-fetch the object somehow (e.g. by passing its primary key) on any other thread you wish to access it from.

**Comment by jpsim** [comment]
Please let us know if this answers your question and if we can close this issue. Thanks!

**Comment by ArEnSc** [comment]
Let me see if I can reproduce this, I think that the  [RLMObject initWithValue:persistedObject] doesn't properly reference the Children in the relationship when initWithValue is called and resulting in the realm accessed from incorrect thread. 

Let me see if I can make a demo.

**Comment by jpsim** [comment]
We look forward to seeing it!

**Comment by ArEnSc** [comment]
https://github.com/ArEnSc/RealmBug

So there are 4 cases outlined in the app code above.

Case 1: Everything works as expected.

Case 2: Using [RLMObject initWithValue:persistedObject] works and allows me to copy the references over to the parent object

Case 3: Adding in the children causes thread access assert when using [RLMObject initWithValue:persistedObject] Perhaps there is a special way to use this if children are included in the mix?  

Case 4: Referencing children from another object causes thread access assert which makes sense sorta and could be related to case 3.

Repo
https://github.com/ArEnSc/RealmBug

**Comment by jpsim** [comment]
Where is the relevant code in the RealmBug repo? What steps can we take to reproduce each of the 4 cases you've outlined.

**Comment by ArEnSc** [comment]
Look in app delegate.m each of the cases are commented the code is async so you want to run one case at a time and comment out cases you do not wish to run

**Comment by jpsim** [comment]
Are you sure you've pushed those commits? The `AppDelegate.m` file looks pretty empty to me:

![image](https://cloud.githubusercontent.com/assets/474794/7825079/c14c3556-03bd-11e5-94d0-1a5a6e4a7f35.png)

**Comment by ArEnSc** [comment]
I am sorry I was rushing to get out of work the ac broke and had to find a starbucks the commits should be push now! =)

**Comment by ArEnSc** [comment]
I am sorry I was rushing to get out of work the ac broke and had to find a starbucks the commits should be push now! =)

**Comment by ArEnSc** [comment]
Yeah so I decided to change the name of the bug to better reflect what the issue is. The Shallow copy of the children in the 1 to many relationship appears to cause an assert accessed from another thread error upon a property access. That better explains the issue.

**Comment by segiddins** [comment]
@ArEnSc I've been running all of the cases in that app delegate, and I'm not seeing any exceptions getting thrown?

**Comment by ArEnSc** [comment]
Are you using version 0.92.3 this is pretty interesting none the less

**Comment by ArEnSc** [comment]
Right so.. remember bug https://github.com/realm/realm-cocoa/issues/1993
So I like you ran the code a couple of times and encountered this bug again. It appears to be a schrodingers bug. So run test case number 4 a couple of times alone, and you will see the thread access error, and or issue 1993 appear. So if the exception is not being thrown, then it means issue 1993 has a appeared and it is blocking on [RLM begin write transaction], if the exception is being thrown it relates to this current bug.
```objective-c
  /**
     This shows if I just provide a reference to the children it says I am accessing it from a different thread.
     **/
    [self threadIssueTwo];
```

**Comment by ArEnSc** [comment]
![screen shot 2015-05-27 at 1 19 59 pm](https://cloud.githubusercontent.com/assets/6252325/7842743/32bdcbd6-0473-11e5-9cbc-a4106acc247a.png)

**Comment by ArEnSc** [comment]
So I was able to reproduce two of the bugs 
The picture above shows the incorrect thread issue.

The picture below shows where you should put the break point and where the code seems to skip executing code below that statement. Thus resulting in the problems in #1993 

put a break point in the file
dataservice

![screen shot 2015-05-27 at 1 25 12 pm](https://cloud.githubusercontent.com/assets/6252325/7842845/d5289bd0-0473-11e5-98a3-83f730fd2c7f.png)

So either way you can catch one of the two bugs.

Just make sure you are using version 0.93.3 and cocoapods.

**Comment by segiddins** [comment]
@ArEnSc making the following change seems to fix the crash for me:

```diff
diff --git a/RealmBug/AppDelegate.m b/RealmBug/AppDelegate.m
index fa2773e..3a68e2e 100644
--- a/RealmBug/AppDelegate.m
+++ b/RealmBug/AppDelegate.m
@@ -113,12 +113,9 @@
         
         // updating parent object
         
-        RParent* updatingParent = [[RParent alloc] init];
+        RParent* updatingParent = [[RParent alloc] initWithValue:parent];
         
         updatingParent.name = @"Updated Parent name";
-        updatingParent.id = parent.id;
-        
-        updatingParent.children = parent.children;
         
         // this will not a thread error.
         // but requires quite a bit of work inorder to do a save alot of type
@@ -182,14 +179,14 @@
      This shows iusing init with value with children 
      I add children to the mix it causes a thread access error.
      **/
-    //[self threadIssue];
-    
+    [self threadIssue];
+
     
     /**
      This shows if I just provide a reference to the children it says I am acessing it from a different thread.
      **/
-    [self threadIssueTwo];
-    
+//    [self threadIssueTwo];
+
     
     // Conclusion initWithValue:(RLMObject*) does not properly reference the children ? 
     
```

**Comment by ArEnSc** [comment]
It a race condition of somekind I still get the bug, and sometimes I don't get the bug occuring based on your changes

**Comment by ArEnSc** [comment]
```objective-c

-(void) threadIssue {
    
    
    // This piece of code WILL cause a thread access error.
    
    [self.dataservice saveRoot:[self giveMeParentObject] withCompleteBlock:^(BOOL Yep) {
        
        RLMResults* results = [RParent allObjects];
        
        RParent* parent = [results objectAtIndex:[results count]-1];
        
        // updating parent object
        
        RParent* updatingParent = [[RParent alloc] initWithValue:parent];
        
        updatingParent.name = @"Updated Parent name";
        
        [self.dataservice saveRoot:updatingParent withCompleteBlock:^(BOOL Yep) {
            
        }];
        
    }];
    
    
}




```

Run this a couple of times and eventually you will see the realm being accessed on another thread exception.

**Comment by ArEnSc** [comment]
@segiddins Let me know if you are not able to reproduce this, perhaps this only occurs on the simulator and not on the device.

**Comment by ArEnSc** [comment]
This is still reproducible on 0.93.0

**Comment by bdash** [comment]
I was able to reproduce this by following the steps provided.

In both `threadIssue` and `threadIssueTwo` the `children` property is set to an existing `RLMArray` of `RChild` instances retrieved from a Realm. `-saveRoot:withCompleteBlock:` then accesses those instances from a secondary thread. This happens to work some / most of the time because GCD is often scheduling the block that `-saveRoot:withCompleteBlock:` `dispatch_async`s on the same thread that the caller was using. If GCD schedules it to a different thread (which you can force it to do by adding a `sleep(1)` immediately after the call to `-saveRoot:withCompleteBlock:`) then you will always see the `Realm accessed from incorrect thread` exception.

**Comment by ArEnSc** [comment]
So yu are telling me if I use a serialized queue or a concurrent queue this architecture will work ?

**Comment by segiddins** [comment]
Your best bet would probably be to set the `children` property to be an array of standalone `RChild` instances, instead of an array of persisted objects.

**Comment by ArEnSc** [comment]
Well I used a serial background queue and it worked well it basically solves all my thread access issues. Also my database consistency issues
