### ISSUE TITLE
A new version of realm notification  causes app to stop executing code? 

### ISSUE THREAD

**Issue by ArEnSc** [realm/realm-cocoa#1993]
Version 0.92.4 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v0.92.4/CHANGELOG.md

For some odd reason when I am using an older version of Realm it stops processing my code? is this how realm behaves?

**Comment by ArEnSc** [comment]
```Objective-c
RLMRealm* db = [RLMRealm defaultRealm];
    [db beginWriteTransaction];
    
    [db commitWriteTransaction];

```
Version 0.92.4 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v0.92.4/CHANGELOG.md
The bad part about this is that it stops the execution of realm code and could break all realm apps ?

**Comment by segiddins** [comment]
What do you mean when you say realm stops processing your code?

**Comment by ArEnSc** [comment]
It appears to halt the app after this function call
This occurs in the simulator btw, I have yet to be able to test this on the device.
```objective-c
RLMRealm* db = [RLMRealm defaultRealm];
    [db beginWriteTransaction]; // Stops code here and doesn't exit app delegate
    
    [db commitWriteTransaction];

// Following debug to this function


```objective-c

- (void)beginWriteTransaction {
    CheckReadWrite(self);
    RLMCheckThread(self);

    if (!self.inWriteTransaction) {
        try {
            // if the upgrade to write will move the transaction forward,
            // announce the change after promoting
            bool announce = _sharedGroup->has_changed();

            // begin the read transaction if needed
            [self getOrCreateGroup];

            LangBindHelper::promote_to_write(*_sharedGroup); // The app just halts after this function call

            // update state and make all objects in this realm writable
            _inWriteTransaction = YES;

            if (announce) {
                [self sendNotifications:RLMRealmDidChangeNotification];
            }
        }
        catch (std::exception& ex) {
            // File access errors are treated as exceptions here since they should not occur after the shared
            // group has already been successfully opened on the file and memory mapped. The shared group constructor handles
            // the excepted error related to file access.
            @throw RLMException(ex);
        }
    } else {
        @throw RLMException(@"The Realm is already in a write transaction");
    }
}

```


```

**Comment by jpsim** [comment]
The reason you were being prompted to update was that we had to stop our release of 0.92.4 part-way through the process. I've updated the latest version on our website to point to 0.92.3, which is the latest stable release, and you'll no longer be prompted to update if you're on 0.92.3.

Now, about Realm "halting" at a `beginWriteTransaction` call, my guess would be that this is because there's another write transaction that's still in progress. It's important to understand that writes are performed serially in Realm (i.e. they're blocking operations). So every time you attempt to start a write transaction in a thread, that thread will wait for all other pending write transactions to complete before it can start.

If you have a particularly large write transaction taking place, it could cause the app to appear to hang for a long time. I encourage you to look through your code to see if there's possibly other write transactions enqueued.

**Comment by ArEnSc** [comment]
Reproduction of Bug
Roll back your changes and have it send the notification for 0.92.4 
Open the simulator iOS 8 
Run the app.


Place In App Delegate.h
```objective-c
RLMRealm* db = [RLMRealm defaultRealm];
    [db beginWriteTransaction]; // , Stops code here and doesn't exit app delegate
    [db commitWriteTransaction];
```

**Comment by ArEnSc** [comment]
Alright it all works again ! but I would look into this it seems like a show stopper. I am not sure how to detect a new version of the library is available but that code could be causing the issues.

**Comment by jpsim** [comment]
@ArEnSc could you please send us a sample Xcode project that reproduces this "halting" so we can investigate further? I doubt that the update checker is at fault here, but it's not impossible.

**Comment by ArEnSc** [comment]
Hey I have tried to reproduce it and it doesn't appear to occur anymore which is interesting, but Ill keep a look out for this one.

**Comment by ArEnSc** [comment]
Okay this happens sporadically pretty schrondingers bug going on here.

**Comment by ArEnSc** [comment]
Could this be due to the fact that I have the Realm Browser open ? on the default.realm ? while the iOS device is trying to read and write ?

**Comment by jpsim** [comment]
Although it's possible that having the Realm Browser open while you perform operations on the Realm in your app could be at fault, that scenario is generally something that Realm supports.

Again, a repro case would be very useful in digging into what's happening here.

**Comment by ArEnSc** [comment]
Solved Thanks guys
