### ISSUE TITLE
Crash moving from 0.90.5 to 0.92.3

### ISSUE THREAD

**Issue by MattKiazyk** [realm/realm-cocoa#1997]
Hi,

I recently updated my realm base to 0.92.3 and am getting a crash now just loading the app.

Schema:
```
GTAmenity {
	remoteID {
		type = int;
		objectClassName = (null);
		indexed = NO;
		isPrimary = YES;
	}
	synchronizedAt {
		type = date;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	modifiedAt {
		type = date;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	company {
		type = string;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	address {
		type = string;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	zip {
		type = string;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	url {
		type = string;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	phone {
		type = string;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	city {
		type = object;
		objectClassName = GTCity;
		indexed = NO;
		isPrimary = NO;
	}
	photos {
		type = array;
		objectClassName = GTOptionalString;
		indexed = NO;
		isPrimary = NO;
	}
	latitude {
		type = double;
		objectClassName = (null);
		indexed = YES;
		isPrimary = NO;
	}
	longitude {
		type = double;
		objectClassName = (null);
		indexed = YES;
		isPrimary = NO;
	}
	trailType {
		type = int;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	distance {
		type = double;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	reviewCount {
		type = int;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	averageRating {
		type = double;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
	category {
		type = object;
		objectClassName = GTAmenityCategory;
		indexed = NO;
		isPrimary = NO;
	}
	sponsorType {
		type = int;
		objectClassName = (null);
		indexed = NO;
		isPrimary = NO;
	}
}
 ```

![screenshot 2015-05-25 14 03 10](https://cloud.githubusercontent.com/assets/1119565/7801215/d157b6a0-02e6-11e5-8075-aaf587288190.png)

with the offending property:
```
latitude {
	type = double;
	objectClassName = (null);
	indexed = YES;
	isPrimary = NO;
}```

crashes with:
```WARNING: An RLMRealm instance was deallocated during a write transaction and all pending changes have been rolled back. Make sure to retain a reference to the RLMRealm for the duration of the write transaction.
libc++abi.dylib: terminating with uncaught exception of type realm::LogicError: Illegal combination
```
Note: the code is siimply calling `[RLMRealm defaultRealm];` in AppDelegate

no code has changed in since the base was 0.90.5. What has changed, or what do I need to change in order to get this to work?

Thanks

-Matt

**Comment by jpsim** [comment]
Hi @MattKiazyk, that exception is thrown because the search index for your `latitude` property couldn't be properly created. It would be very useful for us to have access to your database file so we could determine why that's the case.

In the meantime, you could try disabling indexing on that property to see if the problem persists.

There appears to be another unrelated issue though: your app has an `RLMRealm` instance which isn't kept alive long enough for a write transaction to complete, which causes that transaction to be rolled back (discarded). If you set a breakpoint on `-[RLMRealm dealloc]`, you should be able to see where that happens.

**Comment by MattKiazyk** [comment]
Hi @jpsim 

Removing the indexes (latitude/longitude) loads the app correctly. Realm DB is at https://www.dropbox.com/s/govej1dugfdu402/realmCrash.zip?dl=0

I tried putting a break point on the dealloc, however it only hits it after the original crash. So perhaps that is a result of the first issue?

If you need anything else, let me know.

-Matt

**Comment by tgoyne** [comment]
Indexing double properties is not supported. There's supposed to be some error checking to report a more helpful error, but apparently that's broken.
