### ISSUE TITLE
RealmSwift.framework 0.92.3 on OSX: code signing problem

### ISSUE THREAD

**Issue by stanislaw** [realm/realm-cocoa#1998]
I've just downloaded [realm-swift-0.92.3.zip](https://static.realm.io/downloads/swift/realm-swift-0.92.3.zip) from [Realm Swift 0.92.3 Docs](http://realm.io/docs/swift/latest/) and tried to run it on fresh Swift/OSX application. I followed the instructions and now I see two errors:

```
CodeSign Build/Products/Debug/Realm-Swift-OSX-CodeSign-Problem.app/Contents/Frameworks/RealmSwift.framework/Versions/A
    cd /Users/Stanislaw/Temporary/Realm-Swift-OSX-CodeSign-Problem
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --preserve-metadata=identifier,entitlements,resource-rules /Users/Stanislaw/Temporary/Realm-Swift-OSX-CodeSign-Problem/Build/Products/Debug/Realm-Swift-OSX-CodeSign-Problem.app/Contents/Frameworks/RealmSwift.framework/Versions/A

Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
/Users/Stanislaw/Temporary/Realm-Swift-OSX-CodeSign-Problem/Build/Products/Debug/Realm-Swift-OSX-CodeSign-Problem.app/Contents/Frameworks/RealmSwift.framework/Versions/A: code object is not signed at all
In subcomponent: /Users/stanislaw/Temporary/Realm-Swift-OSX-CodeSign-Problem/Build/Products/Debug/Realm-Swift-OSX-CodeSign-Problem.app/Contents/Frameworks/RealmSwift.framework/Versions/A/Frameworks/Realm.framework
Command /usr/bin/codesign failed with exit code 1
```

and 

```
ld: warning: directory not found for option '-F/Users/Stanislaw/Temporary/Realm-Swift-OSX-CodeSign-Problem/RealmSwift.framework/Frameworks'
```

I have pushed this demo project to Github: [Realm-Swift-OSX-CodeSign-Problem](https://github.com/stanislaw/Realm-Swift-OSX-CodeSign-Problem).

I hope I didn't overlook anything that could make this a misreport.

Thanks.

**Comment by jpsim** [comment]
I'm under the impression that our Swift instructions for OS X are incorrect, and I'll need to spend a bit more time digging into the problem to figure out exactly what should be the correct instructions.

The *semi* good news is that we've set up mechanisms to test many of our installation methods in a continuous fashion and should be in a better position to minimize these issues in the future (see #1935).

**Comment by stanislaw** [comment]
Thanks for response. I can't see the details of that build script from realm-cocoa-private so let me share with you my thoughts:

Be I in your place, I would try to not only automate building of example projects but also a process of creation of this projects.

I am not sure if there is some tool among Xcode Command-line Tools that allows creation of blank iOS/OSX projects from command line. But if this is possible, some tinkering around .xcodeproj/proj.pbx could give you complete automation of setup process so that each step in build script (tweaking .pbx) would correspond to a step in documentation.

This could bring you the desired: ["I can sleep when the wind blows."](http://www.threeriversinstitute.org/Accountability%20in%20Software%20Development.htm) to your delivery process.

Thanks.

**Comment by jpsim** [comment]
The tool you're looking for is [liftoff](https://github.com/thoughtbot/liftoff) which allows the creation of Xcode projects, but ultimately scripting the creation of Xcode projects for all the configurations that we support would take considerable effort, for arguably little gain.

The goal of our installation examples is to go through the same steps an end-user would, and that's likely through doing things manually than through liftoff.

**Comment by segiddins** [comment]
This has actually been fixed by https://github.com/realm/realm-cocoa/pull/1942, and when the next version of Realm comes out we'll have corrected installation instructions.

**Comment by mikekirkwood** [comment]
Hi,

Have been having this issue and trying several things to fix it, but not yet successfully.   

Am using .03 version.   Switched it over to CocoaPods.    Removed the extra Frameworks directory.   Performed the chmod -x on the strip-frameworks.sh file...

All errors are removed except the "...../Frameworks/RealmSwift.framework/strip-frameworks.sh contains an invalid signature...."

Before the above referenced items are included in the next release, do you have a suggestion of best course of action?

Build locally a new version that includes the updates?
Remove the strip-frameworks.sh file?
Other?

Any assistance would be appreciated!

**Comment by segiddins** [comment]
When building with CocoaPods, `strip-frameworks.sh` should be included at all. is it possible you forgot to remove the 0.92.x prebuilt binary? If not, could you please open up a new issue detailing how you've installed RealmSwift in you Xcode project? Thanks!

**Comment by mikekirkwood** [comment]
Do you mean that strip-frameworks.sh should *not* be included at all?

**Comment by segiddins** [comment]
Well, when installed via CocoaPods it isn't.

**Comment by mikekirkwood** [comment]
That makes sense.   It was already there from the other install.
