### ISSUE TITLE
Occasional BAD ACCESS when accessing Results through subscript

### ISSUE THREAD

**Issue by flipchen** [realm/realm-cocoa#2003]
I am oftentimes having a BAD ACCESS when accessing an array of `Results` by subscript. Before accessing the index I make sure, that the count is greater than 0 but that seems to be always the case, that's why it I don't get an array out of bounds exception. It happened on different objects already and most recently on a query that I sorted by an attribute like so:

```swift
let users = realm.objects(ManagedUser.self).sorted("loggedInAt", ascending: false)
if users.count == 0 { return nil }
let user = users[0] // crashes right here
```

Edit: Apparently this also happens when I leave out the sorting, which means sorting has no effect on this behavior.

This is on an in-memory realm that's being created in my test suite and I'm currently on RealmSwift 0.92.2. Please let me know if you need further information or if I'm doing something wrong/ this is a known problem. 

Thank you!

**Comment by jpsim** [comment]
Hi @flipchen, could you try with the latest version of Realm (0.92.4)? We've fixed some issues with `Results.count` which may be causing this.

Also, please make sure that you're only linking your `ManagedUser` class to your application target, and not to your test target.

Finally, if this issue persists even after updating Realm and making sure you're only linking your model to your application target, I'd encourage you to write a failing unit test in [`ResultsTests.swift`](https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Tests/ResultsTests.swift).

**Comment by flipchen** [comment]
Hey @jpsim, thanks for the quick reply! I updated to 0.92.4 which didn't change anything.
I'm not sure how to build the project without linking all the classes, that are used in the tests to the test target. I read that there are ways to pass all the classes on to the test target, but that doesn't work in my project and doesn't seem to work in a newly created project, where I basically only have one class to test.
Can you enlighten me as to why this is necessary or how I can achieve not having to link application classes against my test target?

**Comment by segiddins** [comment]
@flipchen it should be sufficient to just `import AppName` in your test files and declare your classes as `public class`.

**Comment by flipchen** [comment]
I tried that and struggle with a couple of segmentation faults. The test target complains now, that it doesn't know about the frameworks I added through the bridging-header file. Does that mean I have to link the exact same libraries from the app target to the test target as well? There are one or two I added manually to the project, not through cocoapods. Sorry to bother you with this crap now, but proper project setup for iOS projects is still a complete mistery to me after all this time.

**Comment by segiddins** [comment]
You'll only need to link the libraries to the test target if you plan on using them directly in the test target.

**Comment by joamaki** [comment]
I am seeing something similar to this. I was testing Realm with the iOS Swift example and doing
a large add every second and a deleteAll every 10 seconds and can crash it by doing the table view delete action:

```
2015-06-01 16:27:55.413 TableView[4917:3747447] *** Terminating app due to uncaught exception 'RLMException', reason: 'Index is out of bounds.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a740c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010c2aebb7 objc_exception_throw + 45
	2   Realm                               0x000000010a286e10 -[RLMResults objectAtIndex:] + 366
	3   RealmSwift                          0x000000010a4d30d4 _TFC10RealmSwift7Resultsg9subscriptFSiQ_ + 68
	4   TableView                           0x000000010a177ce5 _TFC9TableView19TableViewController9tableViewfS0_FTCSo11UITableView18commitEditingStyleOSC27UITableViewCellEditingStyle17forRowAtIndexPathCSo11NSIndexPath_T_ + 357
```

The background add is the same as in TableView demo, except adding 10000 objects. It
gets run every second with dispatch_after on a private queue. The background delete is:
```
    let realm = Realm()
    realm.write {
      realm.deleteAll()
    }
```

I'll have a look if I can get a failing test case for this. I think in my case this
might require an interaction with table view (can queued UI actions get between the
update to the RLMArray and the reloadData notification?).

**Comment by segiddins** [comment]
@joamaki the issue there is that UIKit doesn't necessary dispatch events synchronously, so the table view itself can get out of sync with the underlying datasource momentarily (which is almost certainly what's happening in the example you shared). It's not a realm-specific issue, but the safest thing to do in scenarios where you're relying on data from a UI-driven action is verify that that data is still valid when it's handed over to you -- in this case, that would mean verifying that the index selected is still in bounds before attempting to subscript the results.

**Comment by joamaki** [comment]
@segiddins thanks, that's what I thought as well. Verifying the index works.

**Comment by LivioGama** [comment]
I'm not sure that is normal to check the index in method cellForRowAtIndexPath. I'm facing the same issue and only since I switched to Realm. Step to reproduce : use a WS search and type something that give 10 results, then add a lot of characters that you know will give you a 0 result and play with the tableview at the same time : it will crash
