### ISSUE TITLE
Realm not empty even when the realm file is removed

### ISSUE THREAD

**Issue by zipme** [realm/realm-cocoa#2013]
My unit test looks like this:

```swift
class ImportTests: XCTestCase {

  let path = "path/to/test.realm"

  func deleteRealmFilesAtPath(path: String) {
    let fileManager = NSFileManager.defaultManager()
    fileManager.removeItemAtPath(path, error: nil)
    let lockPath = path + ".lock"
    fileManager.removeItemAtPath(lockPath, error: nil)
  }

  override func setUp() {
    super.setUp()
    deleteRealmFilesAtPath(path)
  }
  
  override func tearDown() {
    deleteRealmFilesAtPath(path)
    super.tearDown()
  }

  func testImport1() {
    let realm = Realm(path: path)
    XCTAssertFalse(NSFileManager.defaultManager().fileExistsAtPath(realm.path)) // passes
    XCTAssertEqual(realm.objects(Card).count, 0) // passes

    // Doing some import tasks...    
   XCTAssertEqual(realm.objects(Card).count, 2) // passes
  }

  func testImport2() {
    let realm = Realm(path: path)
    XCTAssertFalse(NSFileManager.defaultManager().fileExistsAtPath(realm.path)) // passes
    XCTAssertEqual(realm.objects(Card).count, 0) // failed

   // Doing some import tasks...    
   XCTAssertEqual(realm.objects(Card).count, 2)
  }

}

```

As you can see, the first test passes, but thet second one doesn't. If I remove the first test, then the second one passes. Somehow even the realm file doesn't exist, the Realm#objects still returns data.. I am using Realm (0.92.4), it seems Realm would cache data for the same file path?

**Comment by zipme** [comment]
Just tested it against 0.92.3, all tests pass.

**Comment by jpsim** [comment]
Realm database connections are only closed when `Realm` instances are deallocated, which you can enforce by wrapping its usage in an `autorelease {}` block. The fact that this works in 0.92.3 but not 0.92.4 is a red herring, IMO. So try wrapping your test cases in autorelease pools and let us know how that goes.

**Comment by zipme** [comment]
Strange thing just happened, so I switched back to 0.92.4 (by `pod install`) and everything works as before even though I didn't change anything.. But anyway I will wrap my test in `autorelease {}` as you suggested, thanks! I will close this issue.
