### ISSUE TITLE
Exception when loading realm

### ISSUE THREAD

**Issue by souhl** [realm/realm-cocoa#2014]
Hi,

when I load realm I get exception in [RLMRealm defaultRealm]; that usually tells me that the schema needs to be updated.

But this is happening even with reset iOS simulator (all data deleted) and with having a migration block in place.

Code is the following:
```swift
[RLMRealm setDefaultRealmPath:[[[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:@"group.com.flaschengeist-studios.mwc.documents"] URLByAppendingPathComponent:@"default.realm"].path];
    
    [RLMRealm setSchemaVersion:2 forRealmAtPath:[RLMRealm defaultRealmPath]
            withMigrationBlock:^(RLMMigration *migration,
                                 NSUInteger oldSchemaVersion)
     {
         
         NSLog(@"Migration complete.");
     }];
    
    @try {
        [RLMRealm defaultRealm];
    }
    @catch (NSException *exception) {
        NSLog(@"Trying to open an outdated realm a migration block threw an exception. Version: %li",(long)[RLMRealm version]);
    }
```

What is causing this exception?

Thanks
Sascha

**Comment by segiddins** [comment]
@souhl can you please share the exception that Realm is throwing when you call `[RLMRealm defaultRealm]`?

**Comment by souhl** [comment]
@segiddins sure:

0x10e0d43d0 <+327>: jmp    0x10e0d4440               ; <+439> at RLMRealm.mm:818
    0x10e0d43d2 <+329>: leaq   0x398357(%rip), %rdi      ; @"Cannot set schema version for Realms that are already open."
    0x10e0d43d9 <+336>: xorl   %esi, %esi
    0x10e0d43db <+338>: callq  0x10e0dda20               ; RLMException(NSString*, NSDictionary*) at RLMUtil.mm:303
    0x10e0d43e0 <+343>: movq   %rax, %rdi
    0x10e0d43e3 <+346>: callq  0x10e333fee               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10e0d43e8 <+351>: movq   %rax, %rdi
    0x10e0d43eb <+354>: callq  0x10e333f4c               ; symbol stub for: objc_autorelease
    0x10e0d43f0 <+359>: movq   %rax, %rdi
    0x10e0d43f3 <+362>: callq  0x10e333f8e               ; symbol stub for: objc_exception_throw
->  0x10e0d43f8 <+367>: leaq   0x398351(%rip), %rdi      ; @"Cannot set schema version to RLMNotVersioned."
    0x10e0d43ff <+374>: xorl   %esi, %esi
    0x10e0d4401 <+376>: callq  0x10e0dda20               ; RLMException(NSString*, NSDictionary*) at RLMUtil.mm:303
    0x10e0d4406 <+381>: movq   %rax, %rdi

**Comment by bdash** [comment]
Can you please provide the backtrace at the point the exception is thrown?

**Comment by jpsim** [comment]
@souhl I'm closing this since we need more information from you to investigate further. Please reopen if you can provide more info.

**Comment by wyn15811017** [comment]
What should I do when I set migration I also get a exception "Cannot set schema version for Realms that are already open."

**Comment by jpsim** [comment]
@wyn15811017 this happens when `setSchemaVersion:` is called *after* a realm file has already been opened. My suggestion is to debug your app to identify where you may be opening a realm file (you could set a breakpoint on `-[RLMRealm init]`) and make sure to call `setSchemaVersion:` before this point.
