### ISSUE TITLE
2.23 - Apps must follow the iOS Data Storage Guidelines or they will be rejected

### ISSUE THREAD

**Issue by vlonjatg** [realm/realm-cocoa#2016]
Hey everyone,

After two weeks of "Waiting For Review", Apple finally reviewed my app and it rejected it for the reason: "2.23 - Apps must follow the iOS Data Storage Guidelines or they will be rejected". Here is the full message:

```
2.23 Details

On launch and content download, your app stores 24.62 mb, which does not comply with the iOS Data Storage Guidelines.

Next Steps

Please verify that only the content that the user creates using your app, e.g., documents, new files, edits, etc. is backed up by iCloud as required by the iOS Data Storage Guidelines. Also, check that any temporary files used by your app are only stored in the /tmp directory; please remember to remove or delete the files stored in this location when it is determined they are no longer needed.

Data that can be recreated but must persist for proper functioning of your app - or because users expect it to be available for offline use - should be marked with the "do not back up" attribute. For NSURL objects, add the NSURLIsExcludedFromBackupKey attribute to prevent the corresponding file from being backed up. For CFURLRef objects, use the corresponding kCRUFLIsExcludedFromBackupKey attribute.

Resources

To check how much data your app is storing:

    - Install and launch your app
    - Go to Settings > iCloud > Storage > Manage Storage
    - Select your device
    - If necessary, tap "Show all apps"
    - Check your app's storage

For additional information on preventing files from being backed up to iCloud and iTunes, see Technical Q&A 1719: How do I prevent files from being backed up to iCloud and iTunes.
If you have difficulty reproducing a reported issue, please try testing the workflow described in Technical Q&A QA1764: How to reproduce bugs reported against App Store submissions.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log
```

When the app first starts, the user needs to sync about 25mb of data which is saved on the Realm as NSData. It turns out that this solution is violating Apple Guidelines and from the message seems that I need to exclude the data downloaded from syncing to iCloud.

My question is: do I need somehow to mark the whole .realm file as excluded or there is another way.

Thanks!

**Comment by tgoyne** [comment]
If you want to have some data backed up without having the cache backed up, you'll need to split things into two separate Realm files. Enforcement is inconsistent, but Apple will also want you to put the Realm file with the downloaded data in the Caches directory rather than just marking it as not backed up.

**Comment by tgoyne** [comment]
Depending on what you're doing with the data, you may also find it simpler to simply store the downloaded data in files in the Caches directory, and only store the path to the files in your Realm file.

**Comment by vlonjatg** [comment]
Hi @tgoyne, thanks for your reply.

Well, since I'm downloading over 132 files, saving them when the app opens for the first time adds another 2 minute loading time until all the files are downloaded & created. Instead what I'm doing is getting the files as NSData and saving them in the default realm, then when I need them, I generate only those that I need on the fly in the temp directory.

According to your suggestion, I'm thinking that the way to go is instead of using the default realm (```RLMRealm.defaultRealm()```), create a new realm file in the Caches directory and save the data there. Then probably Apple won't consider this as an issue since that directory is not backed up.

Since I found the documentation about creating new realm files a bit light, can you suggest me where would be the best place to create the new realm file and a few code lines how the new file is created. If you have a link to any example it would be even better.

Thanks for your time,

V.

**Comment by tgoyne** [comment]
You could do something like the following (or put it in a free function, or whatever you prefer):
```swift
extension RLMRealm {
    static var onceToken: dispatch_once_t = 0
    static var cachePath: String? = nil

    public class func cacheRealm() -> RLMRealm {
        dispatch_once(&onceToken) {
            if let dir = NSSearchPathForDirectoriesInDomains(.CachesDirectory, .UserDomainMask, true).first as? String? {
                NSFileManager.defaultManager().createDirectoryAtPath(dir!, withIntermediateDirectories: true, attributes: nil, error: nil)
                self.cachePath = dir?.stringByAppendingPathComponent("cache.realm")
            }
        }

        return RLMRealm(path: cachePath)
    }
}
```

With this you would use `RLMRealm.cacheRealm()` when you want the Realm for the cache, and `RLMRealm.defaultRealm()` for user data that needs to be backed up.

**Comment by vlonjatg** [comment]
Thanks @tgoyne. I just re-submited the app and I will post here what I get any status update.

**Comment by vlonjatg** [comment]
Update: with the changes made, the app was accepted. To anyone having this problem please use @tgoyne provided solution, and your app will go through.

**Comment by tgoyne** [comment]
Great to hear that it was accepted!

**Comment by mitchins** [comment]
Hi,
I know this is old, but doesn't this run the risk of your database being inadvertently deleted everytime the system scrounges around for new disk space as it is marked as cache?

**Comment by tgoyne** [comment]
That's the entire point. Data which can be redownloaded from a server should be placed in the Cache directory so that the system knows it's safe to delete it when it needs more space, and data which cannot should be stored in the Documents directory.

**Comment by jpsim** [comment]
Yes, that's one of the tenets of Apple's storage guidelines is that anything that can be otherwise recovered should be stored so that if the system needs to reclaim some disk space, it can delete those files. This isn't specific to Realm.

**Comment by mitchins** [comment]
Sorry, I think I confused my own use case with yours.
While the data can be re-downloaded the user can also customise the data. Storing a diff against the original set of data might be difficult or slow performing.

I just thought I'd mention that to anyone who might have been concerned.

Thanks for replying after all!
