### ISSUE TITLE
Relationships Lost When Updating Child Object of Relationship

### ISSUE THREAD

**Issue by hkmushtaq** [realm/realm-cocoa#2020]
I'm having an issue with how relationships are dealt with when updating the child object.

```swift
class Parent : Object {
dynamic var id: Int // This is the primary key
let children = List<Child>
}

class Child: Object {
dynamic var id: Int // This is the primary key
// Some properties...
}
```

The issue that I'm facing is the following:

I add some children to the parent and then a network call retrieves the latest data for a certain child object. When I save that child object to the database using realm.add(latestChildObject, update: true), it replaces the existing object instead of just updating it which causes it to be removed from the children array of the Parent object.

I hope that makes sense.

EDIT:  Adding the primary key

**Comment by segiddins** [comment]
@hkmushtaq as long as you have a primary key on the child objects, it should be re-added to the `List`. Could you possibly share some code that reproduces this issue so we can dig in? Additionally, some changes around this part of the Realm code were made in the past few releases, so can you verify if the issue persists even with v0.93.1? Thanks!

**Comment by hkmushtaq** [comment]
self.success = { (responseDictionary:Dictionary<String, AnyObject>, headers:Dictionary<String, AnyObject>) -> () in
            println("Search performed successfully!");
            
            // Save the search results to the database
            let searchResults = responseDictionary[NetworkPropertyResults] as? [Dictionary<String, AnyObject>]
            
            if searchResults != nil {
                DatabaseManager.sharedManager.saveObjects(User.parseUsers(searchResults!), callback: nil)
                self.complete(Error.NO_ERROR)
            }
            else {
                self.complete(Error.INVALID_RESPONSE)
            }
        }

User.parseUsers : 

    class func parseUsers(userDictionaries : [Dictionary<String, AnyObject>]) -> Array<User> {
        var users = Array<User>()
        
        for userDict in userDictionaries {
            users.append(User(value: userDict))
        }
        
        return users
    }

I will try with .93.1

**Comment by hkmushtaq** [comment]
I tried with 0.93.1, and it didnt work

**Comment by segiddins** [comment]
What is your `DatabaseManager.sharedManager.saveObjects` function doing?

**Comment by hkmushtaq** [comment]
It just saves the objects to the database in a loop

            let realm = Realm()
            
            realm.beginWrite()
            for object in objects {
                realm.add(object, update: true)
            }
            realm.commitWrite()

**Comment by segiddins** [comment]
In that case, this sound like a potential bug! Could you possibly share an example project that reproduces the issue, either here or privately with help@realm.io? Thanks!

**Comment by hkmushtaq** [comment]
WOW I think I figured out the issue. I made the sample project to repro the issue and I couldnt get it to repro. I then realized that the search results may contain the current user object and the object may not have all the fields populated ( for efficiency) and if it overwrites the current user object in the database the current user object will not have the relationships since the object coming from the backend was not fully populated with all the fields... I hope that makes sense.

**Comment by jpsim** [comment]
Yes, that makes sense. Thanks for digging into that, @hkmushtaq

**Comment by JRascagneres** [comment]
I am having a similar issue? Could you explain the fix? I am using copyOrUpdate

**Comment by Mohsinraza880** [comment]
how to insert record in child table regarding their parent primary key in realm swift

**Comment by hkmushtaq** [comment]
Recommend opening a separate topic as this one is ~5 years old and your question doesnt seem related
