### ISSUE TITLE
Memory issues in notification center widget

### ISSUE THREAD

**Issue by conradev** [realm/realm-cocoa#2021]
I have been experiencing issues with Realm when used in an iOS notification center widget. Widgets have strict limits on memory usage. If they exceed 4096 pages (or 16 MB) of memory, they are terminated by Jetsam.

If I initialize an `RLMRealm` (393 KB) that is in the app group container, the widget is killed due to memory pressure. If I don't initialize it, the widget loads. I am not allocating any `RLMObject` subclasses or initializing any UI. The process does have other objects in memory, but not enough that it should kill the process. Using the realm as readonly does not seem to help.

I know Realm takes advantage of memory mapping, which means that if the process is under memory pressure it should sync any modified pages back to disk and remove them from memory. I see a 5 MB increase in virtual memory usage when a realm is initialized.

Any idea why I might be experiencing this? Does Realm lock any pages into memory?

**Comment by segiddins** [comment]
@conradev are you opening the Realm from multiple different threads?

**Comment by conradev** [comment]
Only the main thread from the widget, for UI purposes.

**Comment by segiddins** [comment]
@conradev I just tested with a 3+MB Realm file in a today widget, and my process wasn't getting killed. Could you provide us with some steps to reproduce the issue so we can continue to look into it? Thanks!

**Comment by conradev** [comment]
So, actually, loading the realm isn't the issue. It's loading the realm and having other objects in memory. Our WatchKit extension is crashing due to memory pressure now, and it wasn't before. In both extensions, it seems to me that the 5 MB is counting towards the process limit.

Why does Realm be take up 5 MB of memory if the file on disk is smaller than that?

**Comment by conradev** [comment]
@segiddins - I finally figured it out. It turns out that the issue is [here](https://github.com/realm/realm-cocoa/blob/b51bbf47f508b7815a26c824cd0039824493ea07/Realm/RLMSchema.mm#L86). Workflow links against a lot of frameworks, and `objc_copyClassList` initializes every single class into structures in the runtime. Normally this process is lazy. For a sense of scale, in a sample app that links against every single framework, `objc_copyClassList` causes 7 MB of memory to be used, and the penalty in Workflow is 5 MB. This is roughly a third of the memory available to Notification Center widgets.

I hardcoded a list of `RLMObject` subclasses into `Realm.framework` and the issue is fixed. Do you think you could provide an alternate way of registering `RLMObject` subclasses, perhaps like this:

```
+ (void)load {
    [RLMSchema registerRealmObjectSubclass:self];
}
```

Let me know if this is something you'd consider supporting, if not I'll continue to maintain our "fork".

**Comment by tgoyne** [comment]
If `+load` was inherited we could just automatically register subclases there, but alas, it is not.

Making it possible to disable the automatic registration and explicitly register the subclasses isn't an awful idea, but I'm not sure what the API would look like for that.

**Comment by segiddins** [comment]
It's something that will be possible once RLMConfiguration is done. But even then, I'm not sure we won't initialize the shared schema?

-Samuel E. Giddins

On Jun 12, 2015, at 4:41 PM, Thomas Goyne <notifications@github.com> wrote:

If +load was inherited we could just automatically register subclases there, but alas, it is not.

Making it possible to disable the automatic registration and explicitly register the subclasses isn't an awful idea, but I'm not sure what the API would look like for that.

**Comment by tgoyne** [comment]
Yes, a good way to disable the automatic registration is the awkward part, not the manual registering.

**Comment by segiddins** [comment]
Lazy loading the shared schema?

-Samuel E. Giddins

On Jun 12, 2015, at 5:03 PM, Thomas Goyne <notifications@github.com> wrote:

Yes, a good way to disable the automatic registration is the awkward part, not the manual registering.

**Comment by skrew** [comment]
We have the same problem, and #2079 don't fixes the problem. 
@conradev What do you do for fixing this problem ? We are ready to submit and we can't because of this problem. Thanks.

**Comment by segiddins** [comment]
I filed http://www.openradar.me/21404245 asking for a way to get the class list without allocating a buffer.

**Comment by tgoyne** [comment]
It sounds like allocating the buffer isn't the problem; it's that classes are lazy-loaded and getting the list of classes forces them to all be loaded.

**Comment by segiddins** [comment]
Nope, looking at the source for `objc_copyClassList`, it doesn't do anything to force class loading.

**Comment by tgoyne** [comment]
The first thing it does after acquiring the lock is call realizeAllClasses().
