### ISSUE TITLE
<unknown>:0: error: cannot override 'init' which has been marked unavailable

### ISSUE THREAD

**Issue by Sourcebits-Padmapreethi** [realm/realm-cocoa#2025]
Using realm objective C framework in swift class caused this error.When i tried to subclass RLMObject , this issue occurs.

**Comment by segiddins** [comment]
Overriding `init` on `RLMObject` subclasses in Swift is not something we can support right now, due to limitations in Swift's initializer rules. You can read some of the background on this issue at https://github.com/realm/realm-cocoa/issues/1101.
