### ISSUE TITLE
Use of unresolved identifier 'NSDate'  in Model class

### ISSUE THREAD

**Issue by abdulrauf618** [realm/realm-cocoa#2028]
Hi,
I am following the this link
https://realm.io/docs/swift/latest/#models

Xcode giving me an error,
Use of unresolved identifier 'NSDate' 
Please check attachments

![screen shot 2015-05-31 at 12 02 16 pm](https://cloud.githubusercontent.com/assets/12670040/7901028/21f2a510-078e-11e5-84f7-5d4778f9d627.png)

When I check the documentation for NSDate, its also Undocumented .
https://realm.io/docs/swift/latest/api/Extensions.html#/c:objc(cs)NSDate

![screen shot 2015-05-31 at 12 00 35 pm](https://cloud.githubusercontent.com/assets/12670040/7901027/21e77b36-078e-11e5-8e38-14ff65b88d74.png)

Please let me know what's wrong in this code.

**Comment by segiddins** [comment]
do you have an `import Foundation` or `import Foundation.NSDate` in your Swift file?

**Comment by abdulrauf618** [comment]
v.thanks @segiddins , issue fixed with importing Foundation.NSDate

import RealmSwift
import Foundation.NSDate

I think you guys have to mention this in your sample code.

**Comment by segiddins** [comment]
Keep in mind, this is nothing Realm specific -- in swift, imports aren't transitive, so you always need to include every symbol you want to use. 

-Samuel E. Giddins

On May 31, 2015, at 1:14 AM, abdulrauf618 <notifications@github.com> wrote:

Closed #2028.
