### ISSUE TITLE
Carthage: RealmSwift unavailable after running 'carthage update'

### ISSUE THREAD

**Issue by kevinmlong** [realm/realm-cocoa#2035]
Having trouble getting RealSwift.framework to appear in the **Carthage/Build/iOS/** folder after running `carthage update`. Using Carthage v0.7.4-beta.2

Have cleared the cache and removed the .resolved, etc. Not sure what the issue is...

**Comment by jpsim** [comment]
What are the contents of your Cartfile? Realm Swift cannot be built from source by Carthage (see https://github.com/Carthage/Carthage/issues/437), so you'll have to use a prebuilt binary release from GitHub. So you can specify `github "ReactiveCocoa/ReactiveCocoa" ~> 0.93.1` (or any other versioned requirement) in your Cartfile. Also see #2034 for potentially more information.

**Comment by kevinmlong** [comment]
I've haven't had to do this before. In the past using github
"realm\realm-cocoa" did the trick.

Why the change?

If this is the new method, please update the docs on realm.io to reflect
this.

Thanks!

**Comment by jpsim** [comment]
We recently introduced a new tag (`null-string-beta-2`), which caused Carthage to think that this was actually Realm v2.0.0, which doesn't have an associated GitHub release, and therefore no attached binaries, which finally means no prebuilt `RealmSwift.framework`.

https://github.com/Carthage/Carthage/pull/508 was just merged into Carthage, and should likely be available in an upcoming version of the tool. This will restore the previous behavior you saw which is that specifying `github "realm/realm-cooca"` in your Cartfile should detect the latest stable version of Realm Objective-C and Realm Swift and not `null-string-beta-2`.

**Comment by kevinmlong** [comment]
Ok. So for now, we have to manually copy the RealmSwift.framework into the Carthage build directory?

**Comment by segiddins** [comment]
@kevinmlong in the meantime, you can specify `github "realm/realm-cocoa" ~> 0.93.1` in your `Cartfile`.

**Comment by kevinmlong** [comment]
Great. Thanks!

**Comment by NicholasTD07** [comment]
Hi guys, I am trying to use Realm with Carthage and also Swift 2 here. Any idea how I can get this combination to work since there's no prebuilt binary release for the swift branch?

**Comment by segiddins** [comment]
@NicholasTD07 at the moment, you'll either need to build for source or use something like a git submodule and a subproject to build non-released versions of RealmSwift due to some limitations in Carthage.

**Comment by NicholasTD07** [comment]
@segiddins Thank you.

It came to me that, I can use Carthage to manage Realm as a dependency. The only thing Carthage can't do, well, without a prebuilt binary, is to build the RealmSwift project which I can do it by hand. :)
