### ISSUE TITLE
Current RealmSwift Version RLMArray

### ISSUE THREAD

**Issue by bryan1anderson** [realm/realm-cocoa#2036]
All the API Documentation points towards an RLMArray object.

However, the current version of RealmSwift either does not have that object, or it has been renamed and the API's have not been updated accordingly.

Trying to accomplish this: http://stackoverflow.com/questions/27135188/how-to-save-an-array-to-a-realm-object

And the out-of-date docs: https://realm.io/docs/objc/latest/api/Classes/RLMArray.html

**Comment by jpsim** [comment]
I think you're confusing Realm Objective-C with Realm Swift. Realm's collection type in Objective-C is [RLMArray](https://realm.io/docs/objc/latest/api/Classes/RLMArray.html), whereas it is [List](https://realm.io/docs/swift/latest/api/Classes/List.html) in Swift.

The equivalent code from that StackOverflow post in Swift is

```swift
class Alias: Object {
  dynamic var alias = ""
}

class Person: Object {
  dynamic var name = ""
  let aliases = List<Alias>()
}
```

**Comment by bryan1anderson** [comment]
Ok thanks for the response.

If I print the AgendaData Object to the logs, I get a list of items that look like this:

    Results<AgendaData> (
 	[0] AgendaData {
		date = 2015-06-05;
		agendas = RLMArray <0x78661640> (
			[0] Agenda {
				id = ;
				title = ;
			},


From my understanding, I set everything up correctly. However, the List, or RLMArray's items don't actually contain any data. All the items in the List/RLMArray are empty

Is there something I am doing wrong? Or is a List not the correct way for me to be doing what I"m trying





My JSON data looks like this: 


    "data": [
        {
            "date": "2015-06-05",
            "agendas": [
                {
                    "Agenda": {
                        "id": "1",
                        "title": "Main Event"

                    }
                },
                {
                    "Agenda": {
                        "id": "2",
                        "title": "Lunch"

                    }
                },
                {
                    "Agenda": {
                        "id": "3",
                        "title": "Breakout Sessions"

                    }
                }
            ]
        },
        {
            "date": "2015-06-06",
            "agendas": [
                {
                    "Agenda": {
                        "id": "4",
                        "title": "Pump Up Meeting"
                        
                    }
                },
                {
                    "Agenda": {
                        "id": "5",
                        "title": "After Party"

                    }
                }
            ]
        }
    ],
    "response_code": "list_agendas"


my data model like this: 

    class AgendaData: Object {
    dynamic var date = ""
    let agendas = List<Agenda>()
    
    override static func primaryKey() -> String? {
        return "date"
    }
}


    class Agenda: Object {
    

    dynamic var id = ""
    dynamic var title = ""
   
    
    override static func primaryKey() -> String? {
        return "id"
    }
    
    
    
    
}

**Comment by segiddins** [comment]
The issue here is that your `JSON` structure doesn't exactly map to your Realm schema -- there's an extra level of nesting in the `agendas` array (it's an array of dictionaries with a single key who's value is the dictionary you want, rather than just an array of objects). You'll need to either manually flatten that out, or use a framework like `RestKit` or `Realm-JSON` to handle that for you.

**Comment by jpsim** [comment]
@segiddins is right. If you don't want to use the 3rd party mapping tools mentioned above, here's another way to sanitize your json data to match up with your schema:

```swift
func sanitizedJSONObject() -> [NSDictionary]? {
    if let jsonFilePath = NSBundle.mainBundle().pathForResource("data", ofType: "json"),
        let jsonData = NSData(contentsOfFile: jsonFilePath),
        let jsonObject = NSJSONSerialization.JSONObjectWithData(jsonData, options: nil, error: nil) as? NSDictionary,
        let jsonDataObject = jsonObject["data"] as? [NSDictionary] {
            return map(jsonDataObject) { agendaData in
                return [
                    "date": agendaData["date"]!,
                    "agendas": map(agendaData["agendas"] as! [NSDictionary]) { $0["Agenda"]! }
                ]
            }
    }
    return nil
}
if let sanitizedJSONObject = sanitizedJSONObject() {
    let realm = Realm()
    realm.write {
        for agendaData in sanitizedJSONObject {
            realm.create(AgendaData.self, value: agendaData)
        }
    }
    println(realm.objects(AgendaData))
}
```

Should print

```
Results<AgendaData> (
	[0] AgendaData {
		date = 2015-06-05;
		agendas = RLMArray <0x7f91da4c4780> (
			[0] Agenda {
				id = 1;
				title = Main Event;
			},
			[1] Agenda {
				id = 2;
				title = Lunch;
			},
			[2] Agenda {
				id = 3;
				title = Breakout Sessions;
			}
		);
	},
	[1] AgendaData {
		date = 2015-06-06;
		agendas = RLMArray <0x7f91da4d2c10> (
			[0] Agenda {
				id = 4;
				title = Pump Up Meeting;
			},
			[1] Agenda {
				id = 5;
				title = After Party;
			}
		);
	}
)
```
