### ISSUE TITLE
Declaring data model for both swift and objective c

### ISSUE THREAD

**Issue by amitai-hoze** [realm/realm-cocoa#2038]
Hi, I declared my data model in swift like so:

```swift
class Example: Object {
    dynamic var field: Int32 = 0
}
```
When I try to query the model in an objective c file like so:
```objective-c
#import <Realm/Realm.h>
#import "Module_Name-Swift.h"

RLMResults *res = [Example objectsWhere:@"field=0"];
```

I get `No known class method for selector 'objectsWhere:'`. I did a little digging and found out that the imported data model swift class does not implement the objective-c way of querying. Moreover, when I try the swift way:

```objective-c
RLMRealm *realm = [RLMRealm defaultRealm];
RLMResults *res = [realm objects:@"Example" where:@"field=0"];
```

I get `No visible @interface for 'RLMRealm' declares the selector 'objects:where:'`.
What's the best practice here? Declaring the data model twice?

Thanks, Amitai

**Comment by segiddins** [comment]
@amitai-hoze if you need to use Realm from both Swift and Objective-C, we recommend using the Realm Objective-C framework (and thus making your model classes subclass `RLMObject`), since Realm Swift takes advantage of swift-only features.
