### ISSUE TITLE
Unexpected Realm exception

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#2047]
I got a "please_report_this_error_to_help_at_realm_dot_io".
What part of the crash report do you exactly need?
The original crash report, or how the HockeyApp is showing it is enough?

**Comment by segiddins** [comment]
@OlegAnghelov seeing the entire crash report would be helpful, as would having a project that reproduces the issue, if it's something that is happening reliably for you. Thanks!

**Comment by OlegAnghelov** [comment]
here is the crash report:
https://gist.github.com/39dade943f3d39107c2c.git

I did made some sensitive sanitizing, but tried to kept the logic behind the names, hopefully it will be helpful.

Sadly, cannot give any projects because the only was we actually saw these crashes is by HockeyApp reports from Production (the version that is actually on appstore). 
Worth mentioning that we use Realm 0.91.1 .

**Comment by segiddins** [comment]
Thanks for sharing this, @OlegAnghelov. It looks identical to https://github.com/realm/realm-cocoa/issues/1582, so it's an issue we're actively investigating and working on fixing (it's a corrupt database file). You can follow that issue for more updates, thanks!
