### ISSUE TITLE
Conflicting Transactions

### ISSUE THREAD

**Issue by jimjeffers** [realm/realm-cocoa#2051]
Hey there,

I'm encountering a significant amount of crashes in my app due to the following RLMException:

Fatal Exception - The Realm is already in a write transaction.

I'm using realm primarily to cache results we get back from our API. At times it looks like AlamoFire responses are coming in and triggering writes to the DB as another is in progress. What is the best way to mitigate this issue? Should I try dispatching all of my updates to Realm on the main thread? Do I need to partition different aspects of my project into multiple realms?

**Comment by segiddins** [comment]
@jimjeffers It sounds to me like you have open write transaction's that you've not yet committed. You're actually not running into conflicting transactions, but are rather trying to begin a write transaction when one is already open. The best advice I can give you is to not leave right transactions open across iterations of the runloop, and that should help keep your multi-threading safe!

**Comment by jimjeffers** [comment]
@segiddins in my caching algorithm I have something along the lines of...

    realm.beginWriteTransaction
    for item in responseItems
       do something...
       realm.addOrUpdateObject(item)
    end for loop
   realm.commitWriteTransaction

Would it be best to treat this as an anti-pattern and instead do something like this?
  
   cachedObjects = []
   for item in responseItems
       do something...
       cachedObjects.push[item]
    end for loop
   realm.beginWriteTransaction
   realm.addOrUpdateObjectsFromArray cachedObjects
   realm.commitWriteTransaction

**Comment by segiddins** [comment]
No, what you have is totally fine, but it does appear you have an open write transaction hanging around somewhere.

**Comment by jimjeffers** [comment]
I gotcha -- so somehow a transaction is never getting committed. Strange. I'll have to go snooping around. Is there any way good way to debug this?

**Comment by segiddins** [comment]
Probably just auditing your code, and making sure every `beginWriteTransaction` has a matching `commitWriteTransaction`

**Comment by jimjeffers** [comment]
@segiddins Well it looks like we were 63 for 63 so I couldn't find any transactions that were left without a commit. 

I ended up refactoring any transaction that had extensive loops manipulating items and instead opted to do that prior and just submit the array for batch updates in the realm. We haven't seen anymore errors since. I think one of the loops in particular was troublesome because it was querying realm based on the specific object in question. Basically, I think our developers were doing a lot of things we shouldn't have been doing inside of a write transaction ;)
