### ISSUE TITLE
EXC_BAD_ACCESS in Results.swift when unwrapping rlmResults objects

### ISSUE THREAD

**Issue by kortina** [realm/realm-cocoa#2052]
I am intermittently (but very often) getting errors in all spots where the Realm libs try to force unwrap a rlmResults object, eg...

When I do a call in my app to 

    realm.objects(Message.self).first

I get 

    EXC_BAD_ACCESS (code=1, address=0x8)

at 

    public var first: T? { return rlmResults.firstObject() as! T? }

https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Results.swift#L132

This was happening like 1 in 10 times, now is happening more than 50% of the time. 

Only think I can think is that perhaps Realm doesn't handle threading correctly? I am doing some work saving objects to a Realm on a background thread, but am doing that inside a transaction and instantiating a new Realm() object when the crash happens: ```let msg = Realm().objects(Message.self).first``` and can't really see any way to get "safer" with this from.

What is odd is that rlmResults is not nil. If I do the following just before the crash:

    let obs = Realm().objects(Message.self)
    println("\(obs)")

I see results:

    Results<Message> (
            [0] Message {
                    text = la notte;
                    created_at = 2015-06-05 15:16:19 +0000;
                    pk = spk-1234;
                    id = 1234;
            }
    )

that look like they should unwrap correctly

**Comment by kortina** [comment]
NB: I am getting this error when running my test target, if that makes a difference.

**Comment by jpsim** [comment]
It's quite likely that you've accidentally linked your model class to both your app and test targets, causing that class to be different for each target (one for each Swift module). We have more information about this in our docs (https://realm.io/docs/swift/latest/#avoid-linking-realm-and-tested-code-in-test-targets) and just created #2054 to track printing a nicer error when this happens.

Let us know if this isn't the case in your situation and we'll gladly reopen the issue to work with you to resolve this. Thanks!
