### ISSUE TITLE
Realm podspec enforces C++11 standard on app

### ISSUE THREAD

**Issue by ikonst** [realm/realm-cocoa#2053]
See commit https://github.com/realm/realm-cocoa/commit/1d414aee6bfadb011bf2466dfe848fb096b82b8d.

The app should be free to choose its own C++ standard, e.g. GNU++11, preferably without CocoaPod warnings.

**Comment by segiddins** [comment]
This is blocked by https://github.com/CocoaPods/CocoaPods/pull/3573

**Comment by ikonst** [comment]
https://github.com/CocoaPods/CocoaPods/pull/3573 is now merged. Is it still blocked?

**Comment by segiddins** [comment]
@ikonst the only issue is that making that migration would require every realm user to update to CocoaPods 0.38, which I just release about an hour ago.

**Comment by ikonst** [comment]
Heh, understandable.

Hm, /me wonders if CocoaPods spec can have multiple branches for different spec versions (i.e. condition on the running CocoaPods version). Judging from the docs, there's no such common practice.

**Comment by segiddins** [comment]
So as of 0.38 there's actually a minimum CocoaPods version field in the podspec, but obviously that won't be helpful until 0.38 is the old version.
