### ISSUE TITLE
Possible typo in migrations documentation

### ISSUE THREAD

**Issue by ashfurrow** [realm/realm-cocoa#2058]
Under the "adding more versions" section of https://realm.io/docs/swift/latest/ , there is the following code: 

```swift
setSchemaVersion(1, Realm.defaultPath, { migration, oldSchemaVersion in
  // The enumerateObjects:block: method iterates
  // over every 'Person' object stored in the Realm file
  migration.enumerate(Person.className()) { oldObject, newObject in
    // Add the `fullName` property only to Realms with a schema version of 0
    if oldSchemaVersion < 1 {
      let firstName = oldObject!["firstName"] as! String
      let lastName = oldObject!["lastName"] as! String
      newObject!["fullName"] = "\(firstName) \(lastName)"
    }

    // Add the `email` property to Realms with a schema version of 0 or 1
    if oldSchemaVersion < 2 {
        newObject!["email"] = ""
    }
  }
})

// Realm will automatically perform the migration and opening the Realm will succeed
let realm = Realm()
```

I believe that the first parameter to `setSchemaVersion` ought to be 2, since the example is illustrating how to move from version zero, then one, then two. 

It's also possible I'm misunderstanding something, in which case I'd love some clarification.

**Comment by jpsim** [comment]
Yuuuuuup! Nice catch, you're right, that should be `setSchemaVersion(2, ...`. I just fixed it and should be live now: https://realm.io/docs/swift/latest/#adding-more-versions
