### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by valeIT** [realm/realm-cocoa#2059]
I tried looking for an email address or something on the site, but I couldn't find anything. Just wanted to say thank you for what you do. I watched almost all the videos of the Swift summit and I'm looking forward to watch the streams from AltConf. Guess the least I can do is finally try realm on my next project ;)

**Comment by jpsim** [comment]
You're very welcome! The community has given us much, and we're happy to give back!

PS: You can always email us at help@realm.io for technical assistance.
