### ISSUE TITLE
Carthage only builds Realm.framework

### ISSUE THREAD

**Issue by aschuch** [realm/realm-cocoa#2065]
```bash
➜ cat Cartfile 
github "realm/realm-cocoa" "v0.93.1"

➜ carthage build --platform iOS  --no-use-binaries
```

At the moment, Carthage only builds Realm.framework, but ignores RealmSwift.framework.

**Comment by jpsim** [comment]
That's because Carthage doesn't support building Realm Swift from source. Use Carthage binaries instead: `github "realm/realm-cocoa" ~> 0.93`

**Comment by aschuch** [comment]
Thanks. Is there a specific reason for this?
I think this should explicitly be added to the installation guide. We are constantly hitting the Github API limit on one of our projects, thus are required to use `--no-use-binaries` in some cases.

**Comment by tgoyne** [comment]
Carthage doesn't support [multiple projects in a single repo](https://github.com/Carthage/Carthage/issues/437), and we couldn't get building Realm and RealmSwift from a single xcodeproj to work correctly (https://github.com/realm/realm-cocoa/pull/1809).

**Comment by michaelsand** [comment]
@jpsim 

1. This didn't work for me, adding " ~> 0.93" made no difference. Is there another Carthage option to specify use binaries?
2. Someone should probably change the RealmSwift/Cartage option on https://realm.io/docs/swift/latest/ since those instructions are apparently not accurate.

**Comment by segiddins** [comment]
@michaelsand are you using Carthage 0.7.4?

**Comment by michaelsand** [comment]
That was it, apparently the link I'd followed to the latest version was outdated, thanks.
