### ISSUE TITLE
Compatibility for iOS 9, watchOS 2 and Xcode 7

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-cocoa#2066]
### Realm (Objecive-C static)

| | Existing app | Prebuilt Binary | CocoaPods |
| ------------- | ------------- | ------------- | ------------- 
| iOS 9  | ○ | ○  | ○  |
| watchOS 2 | ○ | ○  | ○  |

### Realm (Objecive-C dynamic)

| | Existing app | Prebuilt Binary | CocoaPods |
| ------------- | ------------- | ------------- | ------------- 
| iOS 9  | ○ | ○  | ○  |
| watchOS 2 | ○  | ○  | ○  |

### RealmSwift

| | Existing app | Prebuilt Binary | CocoaPods |
| ------------- | ------------- | ------------- | ------------- 
| iOS 9  | ○ | Need to rebuild | Need to upgrade Swift 2 |
| watchOS 2 | ○ | Need to rebuild  | Need to upgrade Swift 2  |

**Comment by kishikawakatsumi** [comment]
If using RealmSwift on Xcode 7, the following error occurs

```
Module file was created by an older version of the compiler: 
```

**Comment by jlaws** [comment]
+1

**Comment by jpsim** [comment]
I'm closing this issue since we're already tracking what needs to be done in https://github.com/realm/realm-cocoa/pull/2069 and https://github.com/realm/realm-core/pull/880#issuecomment-112736319.
