### ISSUE TITLE
update to Realm Swift 0.93.1,strip-frameworks.sh: Permission denied

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#2070]
hi guys, i am updating from Swift 0.92.1 to 0.93.1. 
but when build the project, I always got the error :
```swift
Frameworks/Realm.framework/strip-frameworks.sh: Permission denied
```
I followed the solution in #1865 : 
```swift
git clone https://github.com/realm/realm-cocoa.git
cd realm-cocoa
git pull origin seg-package-swift
git checkout seg-package-swift
sh build.sh build
open build
``` 
but 
```swift 
git pull origin seg-package-swift // fatal: Couldn't find remote ref seg-package-swift
git checkout seg-package-swift // error: pathspec 'seg-package-swift' did not match any file(s) known to git.
``` 
so I Just run the follow script :
```swift
git clone https://github.com/realm/realm-cocoa.git
cd realm-cocoa
sh build.sh build
``` 
when it finished successfully,i copy the build/ios/swift/Realm.framework、RealmSwift.framework  to my project，The error still appeared.
so is there any suggestion?

**Comment by github2016a** [comment]
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh
I forgot bash,I will test later.

**Comment by github2016a** [comment]
sorry guys,everything is fine. follow the document is ok 
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh

**Comment by pardel** [comment]
@jpsim could I suggest adding another step to (potentially) correct the permission error?
Happens for me in 0.95.3 (might be a system error):

    chmod +x "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh"
    bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh"

**Comment by jpsim** [comment]
@pardel we can't make the shell script executable because then Apple would enforce that it be codesigned! We found this out the hard way: https://realm.io/news/realm-objc-swift-0.93/#lessons-in-executable-code-signing

**Comment by pardel** [comment]
@jpsim ah! Thank you for the link.

**Comment by karloscarweber** [comment]
I ran into this same problem, and I think it can be avoided if the documentation is updated. Right now the "bash" portion of the command appears on a different line than the rest the command no matter what size the browser is at. Perhaps changing this to be in an inline code block would make it very clear what the command is intended to look like.

**Comment by jpsim** [comment]
Thanks for the suggestion, @karloscarweber, we've just pushed a change to do just that!

![image](https://cloud.githubusercontent.com/assets/474794/12540915/5057d8ac-c2c4-11e5-9e53-b8276b12aadf.png)

**Comment by SolYsky** [comment]
Thank you
