### ISSUE TITLE
lipo error from strip-frameworks.sh

### ISSUE THREAD

**Issue by dudeinthemirror** [realm/realm-cocoa#2071]
In the Run script phase I have added:

```bash
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/RealmSwift.framework/strip-frameworks.sh"
```
as per docs. I am getting the following error, when trying to build for Simulator. It works fine on the device:

```
Stripping frameworks
fatal error: lipo: input file (./Alamofire.framework/Alamofire) must be a fat file when the -remove option is specified
```

**Comment by jpsim** [comment]
I guess this would be because `strip-frameworks.sh` is expecting that the other frameworks are fat binaries as well. We should fix this.

**Comment by segiddins** [comment]
This actually isn't really an issue, since `lipo` is failing because your `Alamofire` dynamic library is missing architectures that you would've needed to run anyways.
