### ISSUE TITLE
Allow specifying a new encryption key in writeCopyToPath:encryptionKey:

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2078]
/cc @fab1n

**Comment by tgoyne** [comment]
This is already possible? That overload was added specifically to support key rotation.

**Comment by jpsim** [comment]
Oh, you're absolutely right! We were discussing this in person and I didn't dive in to the code/docs to see what the `encryptionKey:` parameter was for. Consider this done @fab1n

**Comment by Fab1n** [comment]
Oh, man, brillant. Would have been a showstopper! Nice work.
