### ISSUE TITLE
How to delete object by primaryKey?

### ISSUE THREAD

**Issue by onmyway133** [realm/realm-cocoa#2081]
Is there method like this

`[MyCustomRealmObject deleteByPrimaryKey:@"A001"]` ?

**Comment by kishikawakatsumi** [comment]
You can use a combination of `-[RLMRealm deleteObject:]` and `-[RLMObject objectForPrimaryKey:]`.

```
[realm transactionWithBlock:^{
    [realm deleteObject:[MyCustomRealmObject objectForPrimaryKey:@"A001"]];
}];
```

**Comment by jpsim** [comment]
Agreed. That's also what I'd recommend.

**Comment by onmyway133** [comment]
@kishikawakatsumi @jpsim thanks

**Comment by crontab** [comment]
Should be noted, if the object with that key is not found and objectForPrimaryKey returns nil then deleteObject crashes (as of 2.10.2). Would be nice to have a trivial check in the Realm source, but before that you need to check the result yourself before passing it to deleteObject.
