### ISSUE TITLE
Realm: Module was created by an older version of compiler

### ISSUE THREAD

**Issue by imran20487** [realm/realm-cocoa#2082]
Hi,
I am using Xcode 7 beta with base SDK as ios 9.
Followed the steps of installing realm.freamework and realmswift.framework.

However when I tried to: import realmswift it throws an error saying "Module was created by an older version of compiler: myProject/frameworks/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64.swiftmodule"

how do solve this?

**Comment by jpsim** [comment]
You're trying to use a precompiled version of `RealmSwift.framework` that was built with Swift 1.2 (Xcode 6.3) but your project is using Swift 2.0 (Xcode 7). You'll have to wait for us to support Swift 2.0 (#2062) before you can use Realm Swift in your Swift 2.0 project.
