### ISSUE TITLE
Umbrella Header for Module RealmSwift does not include header

### ISSUE THREAD

**Issue by bryan1anderson** [realm/realm-cocoa#2090]
I attempted to archive my xcode project for submission to the app store. The archive didn't appear in the Organizer. I attempted everything from updating cocoapods, deleting derived data, cleaning the project, etc...

Finally I deleted all references to Cocoapods on realmswift. It worked! Of course my app didn't because it now heavily relies on Realm

I reinstalled the RealmSwift pod, and guess what happened? Didn't work..

So! I went performed the same thing several times and found that I receive this warning when using cocoapods:

    Umbrella header for module 'RealmSwift' does not include header 'Pods-MY APP WatchKit     Extension-RealmSwift-umbrella.h'

I'm am completely unsure as to whether or not these problems are related, but i absolutely need to know how to fix this

**Comment by jpsim** [comment]
Hi @bryan1anderson, I'm sorry you're having trouble installing Realm Swift.

We'll need a sample project, or steps to reproduce, to look into this further. Although this sounds like more of an issue with CocoaPods than Realm, we'll do our best to look into it for you.

We have a number of [installation examples](https://github.com/realm/realm-cocoa/tree/master/examples/installation), which tests all of our supported installation methods (including CocoaPods with Swift), which we verify as part of our continuous integration process.

You could use the [ios/swift/CocoaPodsExample](https://github.com/realm/realm-cocoa/tree/master/examples/installation/ios/swift/CocoaPodsExample) project as a starting point to create a reproduction sample for us.

**Comment by bryan1anderson** [comment]
I removed CocoaPods and used the dynamic library option. Worked. Thanks

**Comment by mrackwitz** [comment]
There is a [PR](https://github.com/CocoaPods/CocoaPods/pull/3550) on CocoaPods, which is expected to be merged soon to resolve this and similar issues.
