### ISSUE TITLE
Unexpected behaviour CreateOrUpdate, is it bug or feature

### ISSUE THREAD

**Issue by romanvbabenko** [realm/realm-cocoa#2091]
So when I do createOrUpdate with the same primary key e.g. not change any properties, the existing record properties override with default or null values. In other words createOrUpdate simply cannot update an object partially, you must assign all properties and if you forget any one, the existing info will be override and lost.

Am I right? So I'd be great to implement createOrPatch method for behaviour I expected and how Rails CREATE_OR_UPDATE works.

**Comment by segiddins** [comment]
Can you please share a code sample of how you're using `createOrUpdate`, since it should allow missing keys. Thanks!

**Comment by romanvbabenko** [comment]
@interface Book : RLMObject

    @property NSInteger id;
    @property NSString *title;
    @property float price;

    @end   

   @implementation Book

    + (NSString *)primaryKey {
        return @"id";
    }

    @end

   RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm deleteAllObjects];
    }];
    
    Book *cheeseBook = [[Book alloc] init];
    cheeseBook.title = @"Cheese recipes";
    cheeseBook.price = 9000;
    cheeseBook.id = 1; 
    
    // Updating book with id = 1
    [realm beginWriteTransaction];
    [Book createOrUpdateInRealm:realm withValue:cheeseBook];
    [realm commitWriteTransaction];
    
    Book *cheeseBook2 = [[Book alloc] init];
    cheeseBook2.id = 1; // here I update nothing
    [realm transactionWithBlock:^{
        [Book createOrUpdateInRealm:realm withValue:cheeseBook2];
    }];

    NSLog(@"book:{\"title\":%@}", cheeseBook2.title);
    NSLog(@"Books count: %lu", (unsigned long)[[Book allObjects] count]);

Output

    book:{"title":(null)}
    Books count: 1

**Comment by segiddins** [comment]
The issue here is that there's no way for `createOrUpdate` to know which properties you wish to change, since your `cheeseBook2` object has a "key" for every property. If you wish to selectively update an object, either fetch the existing object and manipulate its properties (using `objectWithPrimaryKey:`), or use an `NSDictionary` with only the keys you wish to be updated.

**Comment by romanvbabenko** [comment]
Yep, I've user that approach and found object by primary key, but it's very a rare case when you need to update all properties of object at the same time and it would be better to change that behaviour to selectively update one.
Anyway, how can I use createOrUpdat with NSDictionary?  I didn't find out so

**Comment by segiddins** [comment]
You would just create a dictionary of your changes, such as the following:

```objc
[realm transactionWithBlock:^{
    [Book createOrUpdateInRealm:realm withValue:@{@"id": @1, @"propertyToChange" : newValue}];
}];

```

**Comment by jpsim** [comment]
Also important to note that we'll soon be adding support for null values (see #1798), so we're reserving having NSNull values in a dictionary to set that property to nil.

```objc
[Book createOrUpdateInRealm:realm withValue:@{@"id": @1, @"nullableProperty" : [NSNull null]}];
```

**Comment by romanvbabenko** [comment]
@segiddins Oh, I see and it works. Thanks.
So pay your attention, please, to documentation issues I've mentioned above
@jpsim Thanks I'll try it as soon as it'll be added
