### ISSUE TITLE
WatchOS support

### ISSUE THREAD

**Issue by MarcoSero** [realm/realm-cocoa#2099]
I don't think there's anything to track the support of watchOS, so I thought of opening this.
#2062 seems to be mostly for Swift 2.

**Comment by segiddins** [comment]
@MarcoSero is there anything in particular realm doesn't support for watchos? I believe @kishikawakatsumi looked into this earlier?

**Comment by MarcoSero** [comment]
From what I can see in the Swift 2 branch, Realm doesn't have a watchOS target and RealmSwift doesn't list watchOS in the list of supported architectures.

**Comment by segiddins** [comment]
We have watchOS support in 0.94.
