### ISSUE TITLE
unexplained behaviour

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [realm/realm-cocoa#2101]
Hello,

Thanks for this framework it really helps me a lot in all the apps that I'm developing.
But there is something that happen that i couldn't understand.

I'm saving a record in the realm, and its saves the record. But when i close the app the record is also deleted or when I run and save data its overwritten. any help ?

by the way for the record I'm still using 
- swift 1.1 (the older version)
- realm 91.1 (the older version)

Any help are highly appreciated.

Thank you.

**Comment by segiddins** [comment]
@rjjohnpatrickcruz could you possibly share some code that demonstrates what's going wrong so we can help you figure out what's happening? Are you sure you'll not using an in-memory realm, and that you're adding your objects to the Realm and committing that inside a write transaction? Thanks!

**Comment by rjjohnpatrickcruz** [comment]
Thanks for your quick response.

here is my code:

        let detailed_survey = Detailed_survey_answer.allObjects()
        let GSRealm = RLMRealm.defaultRealm()
        
        var detailed_survey_id = detailed_survey.count + 1
        
        for d_survey in arrAnswers {
            
            var bir_stamp = d_survey["bir_stamp"] as NSString
            var brand_id = d_survey["brand_id"] as NSString
            var graphical_warning = d_survey["graphical_warning"] as NSString
            var guid = d_survey["guid"] as NSString
            var other_brand_name = d_survey["other_brand_name"] as NSString
            var other_variant_name = d_survey["other_variant_name"] as NSString
            var pack_id = d_survey["pack_id"] as NSString
            var price = d_survey["price"] as NSString
            var variant_id = d_survey["variant_id"] as NSString
            
            let setDetailedSurvey = Detailed_survey_answer()
            GSRealm.beginWriteTransaction()

            setDetailedSurvey.id = Int(detailed_survey_id)
            setDetailedSurvey.store_id = store_id.integerValue
            setDetailedSurvey.bir_stamp = bir_stamp.integerValue
            setDetailedSurvey.brand_id = brand_id.integerValue
            setDetailedSurvey.graphical_warning = graphical_warning.integerValue
            setDetailedSurvey.other_brand_name = other_brand_name
            setDetailedSurvey.other_variant_name = other_variant_name
            setDetailedSurvey.pack_id = pack_id.integerValue
            setDetailedSurvey.price = price
            setDetailedSurvey.variant_id = variant_id.integerValue
            setDetailedSurvey.guid = guid
            setDetailedSurvey.status = 0
            setDetailedSurvey.sync_status = constants.STATUS_UNSYNC
            setDetailedSurvey.ts = dateToday
            
            GSRealm.addObject(setDetailedSurvey)
            GSRealm.commitWriteTransaction()
            
            detailed_survey_id++
        
        }

        arrAnswers = [] // clean up the array for the next item that Im going to save later.

-------------
here is my realm object:

class Detailed_survey_answer: RLMObject {

    dynamic var id:Int = 0
    dynamic var store_id:Int = 0
    dynamic var bir_stamp:Int = 0
    dynamic var brand_id:Int = 0
    dynamic var graphical_warning:Int = 0
    dynamic var pack_id:Int = 0
    dynamic var variant_id:Int = 0
    dynamic var other_brand_name:NSString = ""
    dynamic var other_variant_name:NSString = ""
    dynamic var price:NSString = ""
    dynamic var guid:NSString = ""
    dynamic var status:Int = 0
    dynamic var sync_status:Int = 0
    dynamic var ts:NSDate?
    
    override class func primaryKey() -> String{
        return "id"
    }

}

**Comment by segiddins** [comment]
That should work! What makes it seem like your saved object isn't being persisted?

**Comment by rjjohnpatrickcruz** [comment]
Yup its working, my problem is that when i save another data my old data was overwritten or deleted .. I don't know why.. =(

**Comment by rjjohnpatrickcruz** [comment]
Hi,

I've already resolve this problem.

Thanks for the quick response.
Cheers!

**Comment by segiddins** [comment]
@rjjohnpatrickcruz glad to hear you figured things out!
