### ISSUE TITLE
pod install

### ISSUE THREAD

**Issue by longxianlin** [realm/realm-cocoa#2102]
Installing Realm (0.93.2)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...

Downloading dependency: core 0.89.6

**Comment by longxianlin** [comment]
xcode 6.3

**Comment by segiddins** [comment]
@longxianlin is there anything in particular that's not working?

**Comment by jpsim** [comment]
Closing due to insufficient information and lack of activity.

**Comment by junjielu** [comment]
same issue
