### ISSUE TITLE
Pods-frameworks.sh: No such file or directory

### ISSUE THREAD

**Issue by ciminuv** [realm/realm-cocoa#2103]
I follow your document at: https://realm.io/docs/swift/latest/#installation

This is my Podfile:
```yml
platform :ios, '8.0'
use_frameworks!

inhibit_all_warnings!

target 'XXX' do
  pod 'RealmSwift'
end

target 'XXXTests' do
  pod 'RealmSwift'
end
```

Error message:
```
Pods-frameworks.sh: No such file or directory
```
What was possibly wrong?

P/s: After I moved `pod 'RealmSwift'` outside target everything worked just fine except some warring from cocoapods:
```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `XXX` to `Pods/Target Support Files/Pods/Pods.release.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.release.xcconfig` in your build configuration.
```

**Comment by segiddins** [comment]
@ciminuv can you dry deleting the `Pods` directory and re-installing? This seems like a weird CocoaPods integration issue. Thanks!

**Comment by ciminuv** [comment]
@segiddins: After adding this line `source 'https://github.com/CocoaPods/Specs.git'` into `Podfile` it works like magic :smiley:

**Comment by segiddins** [comment]
Excellent!
