### ISSUE TITLE
RLMMigrationBlock documentation wrong

### ISSUE THREAD

**Issue by ikonst** [realm/realm-cocoa#2107]
In the sample for https://realm.io/docs/objc/latest/#performing-a-migration, you specify a migration block with:
```objc
^(RLMMigration *migration, NSUInteger oldSchemaVersion)
```
while the second argument is actually `uint64_t`.

**Comment by jpsim** [comment]
Thanks for pointing that out, @ikonst! @segiddins updated that part of our docs this morning thanks to your keen eye and for telling us about the inaccuracy: https://realm.io/docs/objc/latest/#performing-a-migration
