### ISSUE TITLE
Realm isn't fast enough to scroll through table view

### ISSUE THREAD

**Issue by bryan1anderson** [realm/realm-cocoa#2115]
Here is my setup:

     func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        let realm = Realm()
        let agendaData = realm.objects(AgendaData)
        return agendaData.count
    }
    
    
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        
        let realm = Realm()
        let agendaData = realm.objects(AgendaData)
        //Get number of sections
       return agendaData[section].agendas.count
        
    }

    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell: AgendaCell = tableView.dequeueReusableCellWithIdentifier("AgendaCell", forIndexPath: indexPath) as! AgendaCell
     
        let realm = Realm()
        let agendaData = realm.objects(AgendaData)
        let singleAgenda = agendaData[indexPath.section].agendas[indexPath.row]
        
        cell.agendaLabel.text = singleAgenda["title"] as? String
        cell.timeLabel.text = singleAgenda["time"] as? String
        
            
            return cell
       
    }

What i get is a tableview too slow to navigate through. It pauses at each cell to load and then scrolls through. It gives the feeling that it doesn't work at all..

Am I following best practices? If not please tell me what I can do to speed up. If i am, what else can I do to optimize for a tableview

Thanks

**Comment by segiddins** [comment]
@bryan1anderson you can have a look at our table view example (https://github.com/realm/realm-cocoa/blob/master/examples/ios/swift/TableView/TableViewController.swift) to get a sense for what we recommend. The biggest difference from how you have things set up is that the example has a `Results` property to hold the backing results, instead of refetching it every time it's needed.

```swift
let agendaData = Realm().objects(AgendaData)
 
 func numberOfSectionsInTableView(tableView: UITableView) -> Int {
    return agendaData.count
}


func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    //Get number of sections
   return agendaData[section].agendas.count
}

func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let cell: AgendaCell = tableView.dequeueReusableCellWithIdentifier("AgendaCell", forIndexPath: indexPath) as! AgendaCell

    let singleAgenda = agendaData[indexPath.section].agendas[indexPath.row]

    cell.agendaLabel.text = singleAgenda["title"] as? String
    cell.timeLabel.text = singleAgenda["time"] as? String

        return cell
}
```

**Comment by bryan1anderson** [comment]
Yes That did it. Thanks for your support

**Comment by segiddins** [comment]
Glad to see that helps!
