### ISSUE TITLE
cocoapods install realm,the RLMArray_Private.hpp, RLMAccessor.h, Realm / RLMConstants.h file is not found

### ISSUE THREAD

**Issue by VNSKing** [realm/realm-cocoa#2116]
OX S：10.10.3
Xcode：6.3
CocoaPods： 0.37.1

I created a project swift clearance CocoaPods mounted the Realm, open .xcworkspace, prompted me RLMArray_Private.hpp, RLMAccessor.h, Realm / RLMConstants.h file is not found, how do I fix it?

https://github.com/VNSKing/RealmSample

**Comment by segiddins** [comment]
@VNSKing it's very strange that the `Pods` directory doesn't contain a `Headers` subdir -- that's almost certainly a CocoaPods bug if it's happening, and the CocoaPods team would definitely appreciate a reproducible bug report! In the meantime, I'd recommend

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

**Comment by VNSKing** [comment]
@segiddins Thanks！！ The problem is resolved.
