### ISSUE TITLE
What is the proper approach for defining a new primary key during migration?

### ISSUE THREAD

**Issue by Luke47** [realm/realm-cocoa#2118]
I'm using Realm with Swift. 

I have a subclass of `Object`, with only one property `name`, which I want to be the primaryKey.

Sadly, I forgot to override the "primaryKey" function. Now I need to migrate. But how is this done properly? I guess I need to iterate over the old objects, but what do I need to do exactly?

```swift

setSchemaVersion(1, Realm.defaultPath, { migration, oldSchemaVersion in

             if oldSchemaVersion < 1 {
                // The enumerate(_:_:) method iterates
                migration.enumerate(Test.className()) { oldObject, newObject in
                    // What to put here?
                }
            }
            })

```

Thank you!

**Comment by tgoyne** [comment]
You don't need to do anything in the migration block.

We always automatically update the schema to the latest version, and the only thing that you have to handle in the migration block is adjusting your data to fit it (e.g. if you rename a property you have to copy the data from the old property to the new one in the migration block). We require the schema version bump even in non-destructive cases to ensure that you're aware that you've made a schema change, and to avoid some goofy edge-cases like two processes with slightly different schemas migrating a realm file back and forth between them.

**Comment by Luke47** [comment]
Thank you for the fast reply!

One remaining problem is that I already have something like this in my database:

object1: name = test1
object2: name = test2
object3: name = test1

If I do the migration and set the primaryKey, this will throw an error, because object1 and object3 will have the same primaryKey (=test1).

So I guess I need to clean up all duplicates during the migration block?

**Comment by tgoyne** [comment]
Yes, you'll either need to delete the duplicates or change their names to make them unique.

**Comment by Luke47** [comment]
Okay, thank you! This can be closed. Have a nice day! :)
