### ISSUE TITLE
testNotificationsForChangesWhileSuspended occasionally fails

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2119]
See https://ci.realm.io/job/objc_pr/1031/configuration=Debug,target=osx/console

**Comment by jpsim** [comment]
This only seems to occasionally fail on Debug OSX builds.

**Comment by jpsim** [comment]
I was unable to reproduce this test failure, even when running ~40 times on the workers, even when their hosts were under heavy load.

**Comment by segiddins** [comment]
@tgoyne observed this this morning on his machine -- appeared to be waiting for the process to finish when it was no longer alive
