### ISSUE TITLE
Combining queries?

### ISSUE THREAD

**Issue by ProjectDent** [realm/realm-cocoa#2121]
I have these two objects in my model:

**Message**:

    class Message: Object {
        //Precise UNIX time the message was sent
        dynamic var sentTime: NSTimeInterval = NSDate().timeIntervalSince1970
        let images = List<Image>()
    }

**Image**:

    class Image: Object {
        dynamic var mediaURL: String = ""
        var messageContainingImage: Message {
            return linkingObjects(Message.self, forProperty: "images")[0]
        }
    }

I want to form a query which returns messages and images, messages sorted by `sentTime` and images sorted by their `messageContainingImage`'s sent time. They'd be sorted together.

The recommended code for a query is this:

    let messages = Realm().objects(Message).sorted("sentTime", ascending: true)

This returns a `Result<Message>` object. A `Result` doesn't have a way to be joined to another Result. There are other issues in my way too, such as, if I could combine them, how would I then perform a sort.

Additional thoughts:
- I could also add a property to Image called `sentTime`, then once they're combined I'd be able to call that property on both of them.
- I could make them both subclass from a type which has `sentTime`. The problem is, doing `Realm().objects(Message)` would only returns things which are messages, and not subclasses of Message.

How would I be able to do this?

My end goal is to display these message and image results in a tableview, messages separately from their attached image.

**Comment by ProjectDent** [comment]
I've been thinking more about this - the ideal solution to this whole thing is if a call to `Realm().objects(Message)` would return anything which is a Message or subclasses from Message, and if Results could be `append`ed. Then I could pull in all relevant Messages, pull in all relevant Images, then sort them by their own property of sentTime.

**Comment by segiddins** [comment]
(@ProjectDent we're currently tracking adding support for that kind of polymorphism at https://github.com/realm/realm-cocoa/issues/1109)

**Comment by mrackwitz** [comment]
I think, inheritance is not the right solution here, this introduces more drawbacks by complicating your object schema, than it's worth for your use case.

Let's go back to what you wrote is your end goal: I guess you want to display messages and images together in one table view as separated rows, where the images follow their message. Do I understand that correctly?

You don't need to sort both, sorting the messages and accessing them and their images in a suitable way will ensure that everything is sorted correctly. The main challenge is more how to enumerate / random-access this two-dimensional data structure as an one-dimensional sequence.

Depending on the amount of data, you query, you have to decide, whether you can go a simple approach by keeping them all in memory at once, or introducing a view object on top of Results, which takes care of accessing all objects in order.

The first solution could just look like this:

```swift
let messages = Realm().objects(Message).sorted("sentTime", ascending: true)
array = reduce(messages, [Object]()) { (var result, message) in
            result.append(message)
            result += map(message.images) { $0 }
            return result
        }
```

While the latter solution is more complex, but could look [like this](https://gist.github.com/mrackwitz/340e38e7f67627d0ba38).
