### ISSUE TITLE
Uniqueness validation

### ISSUE THREAD

**Issue by stefanvermaas** [realm/realm-cocoa#2123]
Hi guys,

I pretty new to iOS development, so sorry if this is some sort of rookie mistake, but I've got some problems with uniqueness validations.

I've got this tableView that lists all the current conversations. I'm now using Realm to store the conversations on the device, though I'm running into an issue with the primary_key.

Every time the view is loaded/opened I'm looking up the latest conversations from my web API. This web API then returns all the conversations for an user. As this respons returns to the app, I want to add them to the Realm store. 

```swift
  private func getAllConversations() {
    Alamofire.request(Router.All("conversations"))
      .validate(statusCode: 200..<300)
      .responseJSON { (_, _, rawConversations, error) in
        if let theError = error { return }
        
        // Add all conversations to the Realm store
        let theConversations = JSON(rawConversations!)
        for (id, c) in theConversations {
          let conversation = self.newConversation(c)
          RealmManager.sharedInstance.add(conversation)
        }
    }
  }
  
  private func newConversation(c: JSON!) -> Conversation {
    let conversation = Conversation()
    
    // Add the values to the conversation
    conversation.id         = c["id"].intValue
    conversation.title      = c["title"].stringValue
    conversation.timestamp  = c["timestamp"].intValue
    
    // Return the conversation
    return conversation
  }
```

Though using this an exception will be thrown because I've already added the conversation to the store. Is it possible to catch this exception (I believe it's not in swift right now). Or is there an workaround?

I was thinking of checking myself or an conversation already existed or not, but this is a bit ugly, because Realm is already doing this. Shouldn't Realm fail silently or make it possible to handle the exception?!

Cheers!

**Comment by stefanvermaas** [comment]
I'm now doing this like this:

```swift
  private func createConversation(c: JSON!) {
    // Find out or the conversation already exists
    let predicate = NSPredicate(format: "id = %i", c["id"].intValue)
    if ( RealmManager.sharedInstance.store.objects(Conversation).filter(predicate).count > 0 ) {
      return
    }
    
    // Create a new conversation
    var conversation        = Conversation()
    conversation.id         = c["id"].intValue
    conversation.title      = c["title"].stringValue
    conversation.timestamp  = c["timestamp"].intValue
    
    // Add the participants
    for p in c["participants"].arrayValue {
      // Create a new participant
      var participant       = Participant()
      participant.id        = p["id"].intValue
      participant.firstName = p["first_name"].stringValue
      participant.lastName  = p["last_name"].stringValue
      participant.email     = p["email"].stringValue
      
      // Add the participant to the participants array
      conversation.participants.append(participant)
    }

    // Return the conversation
    RealmManager.sharedInstance.add(conversation)
  }
```

Though it doesn't feel right.

**Comment by segiddins** [comment]
@stefanvermaas you can use `Realm.add(_:update:)` (and `Realm.create(_:update:)`) where `update == true` to update an existing object with the given primary key. We have some more docs at https://realm.io/docs/swift/latest/#updating-objects, hope that helps!

**Comment by stefanvermaas** [comment]
Thanks @segiddins, though this still doesn't feel right. Though I guess checking or the item already exists isn't that bad. Okay thanks, I'll figure it out!

**Comment by stefanvermaas** [comment]
Hmm this won't work if you import a model with models inside. So let's say we retrieve a receipt with a message and an sender from the server. This could be the response:

```json
{
  "id" : 1722,
  "is_read" : true,
  "trashed" : false
  "message" : {
    "body" : "test?",
    "id" : 861,
    "timestamp" : "2015-06-26T10:20:23.284+02:00", 
    "sender" : {
      "id" : 2,
      "last_name" : "Van der maas",
      "first_name" : "Steven"
    }
  }
}
```

To parse this JSON data I've got three Realm objects: `account`, `receipt`, `message`. Those three objects are linked together, so when I do: `Receipt(value: jsonData)`, three objects will be created. 

Though this works fine the first time, but the second time I receive an other receipt from the server with the same sender. This is where things are getting interesting, because now an exception will be thrown and I can't proceed.

Is there something I should do different? I personally think it would be nice not to throw an exception, but find that one record and add it to the collection.

**Comment by stefanvermaas** [comment]
An other way to solve this, is allowing AnyObjects to be saved in the Realm store, though I'm not sure or this is even possible.

**Comment by NicholasTD07** [comment]
@segiddins Thank you. Your comment about `add(_:update:)` saved my day. :smile: NicholasTD07/SwiftDaily-ZhiHu@d49b9b82b72487d01ce574018ecbcdd4a201e168

@stefanvermaas Do you have `primaryKey` for all three models? In the project above, I also have embedded models. `add(_:update:)` works. All models in my project have `primaryKey`

**Comment by segiddins** [comment]
@stefanvermaas doing `realm.create(Receipt.self, value: jsonData, update: true)` there should do what you want. If it isn't, could you please share an example project that exhibits the issues you seeing here or privately at help@realm.io? Thanks!

**Comment by NicholasTD07** [comment]
@stefanvermaas Another thing is that I see you are using a `sharedInstance` of `Realm` in your code. If you are sharing it across threads, you may run into problems. Quote from Realm's documentation, "*Sharing Realm instances across threads is not supported.*"

**Comment by stefanvermaas** [comment]
Both thanks for pointing this out! I'll try it in a second. 

@NicholasTD07: I'm only using this in the (UI) default thread and not in a background thread, so this should be fine, right?! Or am I interpreting your suggestion wrongly?

**Comment by NicholasTD07** [comment]
@stefanvermaas if that is used only in one thread then it is ok. :)

**Comment by stefanvermaas** [comment]
Ah okay cool :)! Well thanks for the heads up!

**Comment by NicholasTD07** [comment]
My pleasure.
