### ISSUE TITLE
Realm fetch gets stuck sometimes, and even hang the UI

### ISSUE THREAD

**Issue by tariq235** [realm/realm-cocoa#2131]
One of the frustrated issue since beginning. No steps and not enough information or logs. Just sometime on device my app is getting hanged. Then I have to go in background and foreground to make it work. After that UI got completely hanged and started behaving weirdly. This situation is only occurring on UI where I have integrated realm and other tabbar views are working great.

Here is the code snippet:

On UITableViewCell tap I am calling this:

```
[self.interactor eventDisplayDataForEventID:eventID completionBlock:^(IVFormattedDisplayData *displayData) {
        IVEventDetailViewController *viewController = [[IVEventDetailViewController alloc] init];
        viewController.displayData = displayData;
        [self.navigationController pushViewController:viewController animated:YES];
    }];
```

```
- (void)eventDisplayDataForEventID:(NSString *)eventID completionBlock:(void(^)(IVFormattedDisplayData *displayData))block {
    NSAssert(eventID, @"eventID is nil");

    dispatch_async(self.realmQueryQueue, ^{
        RLMRealm *realm = [RLMRealm defaultRealm];
        IVEvent *event = [IVEvent objectInRealm:realm forPrimaryKey:eventID];

        IVFormattedDisplayData *displayData = [[IVFormattedDisplayData alloc] init];
        [displayData updateForEventData:event];
        
        dispatch_async(dispatch_get_main_queue(), ^{
            block(displayData);
        });
    });
}
```

Looks like realmdb sometime not performing operation and because of that pushNavigation is not getting called but as soon as I go in background and comes in foreground then push automatically get called with proper event object. But then hanging situation is all started and then UI never work properly.

Let me know if I can get some help on this. Sorry I don't have logs or complete details for you.

**Comment by segiddins** [comment]
@tariq235 so sorry to hear you're running into issues, but I don't see anything wrong with the code snippet you shared. If you'd like to share a project that reproduces the issue with us, either here or privately at help@realm.io, we'd be happy to take a look!

**Comment by tariq235** [comment]
hey @segiddins  Bad news for me that nothing wrong with the code :D Because now I have to go back n forth with other code pieces.

Code is linked to our major product release so probably I'll create a sample and try to reproduce the issue and then will handover the sample privately.

**Comment by mrackwitz** [comment]
@tariq235: Did you were able to figure out the issue in the product or reproduce this issue in a sample app?

**Comment by tariq235** [comment]
hey @mrackwitz  @jpsim  @segiddins  Closing this issue because it wasn't related to Realm. It was really hard for me to troubleshoot the problem and at the end root cause was custom navigation.
