### ISSUE TITLE
TableView crash

### ISSUE THREAD

**Issue by longxianlin** [realm/realm-cocoa#2132]
```swift
    override func tableView(tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {
        if editingStyle == .Delete {
            let realm = Realm()
            realm.beginWrite()
            realm.delete(array[indexPath.row])
            realm.commitWrite()
           
            //below cause crash, realm do UI jobs, please try
//            tableView.deleteRowsAtIndexPaths([indexPath],
//                withRowAnimation: .Fade)

```

**Comment by jpsim** [comment]
@longxianlin is it possible you set a notification block in your table view controller to reload its data? Like this?

```swift
notificationToken = Realm().addNotificationBlock { [unowned self] note, realm in
  self.tableView.reloadData()
}
```

If so, then you're attempting to delete a non-existing row from UITableView's internal model. Say you have one row, and you try to delete it. You delete it from the Realm and commit the transaction, which triggers the notification block, which reloads the table view's data, so now there are no rows, and then the table view attempts to animate the first row being deleted (but it doesn't exist any more).

Here's a gist demonstrating how you could adapt our Swift TableView example to animate adding and removing rows: https://gist.github.com/jpsim/5e95958ed064d0b45ce3

**Comment by longxianlin** [comment]
thanks. noted that.
