### ISSUE TITLE
Possible Swift-2 build directory issue

### ISSUE THREAD

**Issue by marchyman** [realm/realm-cocoa#2135]
This is similar to an issue reported and corrected earlier but slightly different, I think. 

* Using Xcode 7 beta2 on OS X 10.10.3
*  Built Realm/RealmSwift from the Swift-2.0 branch using the command

    CONFIGURATION=Debug build.sh osx-swift

* Copied the resulting Realm and RealmSwift frameworks from the build/osx directory to a project I'm playing with.

The project compiles, links, and runs without error.  HOWEVER, when I try to edit a source file that contains an “import RealmSwift” statement I get an error “Missing required modules: ‘Realm.private’, ‘Realm’”.   I believe this is related to lldb/REPL as on breakpoints the contents of objects are no longer available and doing something like `po self` results in

    warning: Swift error in module memo: 
        Swift had fatal errors constructing the ast context for this module: <built-in>:2:16: error: module 'Realm' was built in directory '/Realm.framework' but now resides in directory './Realm.framework'
    #define __clang__ 1
                   ^
    missing required modules: 'Realm.Private', 'Realm'
    Debug info from this module will be unavailable in the debugger.

Swift/Xcode issue or Realm configuration issue?

**Comment by segiddins** [comment]
This is an lldb issue, I'm like 90% sure, since I've seen it happen with other frameworks as well.

**Comment by allending** [comment]
Just chiming in, I'm seeing this issue as well, and it makes Realm unusable for me. Including the Realm framework kills the rest of my project w/ regards to debugging and editing. Since Xcode/LLDB is dying when processing the Realm frameworks, I guess its isn't strictly a Realm issue.

**Comment by kunass2** [comment]
This issue exists for every other framework... Still looking for a solution

**Comment by jpsim** [comment]
I'm closing this issue since it really seems like a problem with LLDB and Swift modules rather than Realm itself.

I'd encourage you to file a radar at https://bugreport.apple.com, especially since Apple will be making a slew of fixes leading up to Xcode 7's release.

**Comment by voidref** [comment]
Submitted Radar: 21859260

**Comment by voidref** [comment]
This appears to be working in Xcode 7 beta 5. You will need to build realm via `build.sh ios-swift`

**Comment by BrettThePark** [comment]
For reference, the solution can be found here 
http://stackoverflow.com/questions/31219422/swift-debugger-does-not-show-variable-values-when-importing-objc-framework/31455774#31455774
