### ISSUE TITLE
Can't build Realm-Cocoa on case-sensitive HFS

### ISSUE THREAD

**Issue by ikonst** [realm/realm-cocoa#2136]
On case sensitive HFS, you'd get errors such as:
```
Pods/Realm/include/realm/RLMArray_Private.h:19:9: fatal error: 'Realm/RLMArray.h' file not found
```

Note the lowercase "realm/" in the path above. This path comes from the realm-core ZIP file.

**Comment by ikonst** [comment]
A workaround would be:
```sh
ln -s realm Pods/Headers/Private/Realm/Realm
ln -s realm Pods/Headers/Public/Realm/Realm
ln -s realm Pods/Realm/include/Realm
```

**Comment by segiddins** [comment]
@ikonst, I just took a look at the `build.sh` code in question, and I believe the current version of Realm should work fine via CocoaPods on case-sensitive systems. What version of Realm are you currently installing, and could you try updating to 0.93.2 to see if that fixes things? Thanks!

**Comment by ikonst** [comment]
We're using Realm 0.93.2 and I've installed it from scratch.

Here's a link to a test project on a case-sensitive disk image:
https://drive.google.com/open?id=0B359dq-Bj8zdczVzZ1h1OUQ5ZWs

Or you can create your own with Disk Utility :)

**Comment by segiddins** [comment]
Thanks for the disk image! I tried playing around with it to install onto the DMG, but things such as `git` and `cat` were breaking pretty badly for me.

**Comment by ikonst** [comment]
Strange, works well for me.

**Comment by kishikawakatsumi** [comment]
I think it will occur when copying a project that was set up on a case-insensitive file system to a case-sensitive file system.

Because there are the following differences in projects that were set up by CocoaPods in each file systems.
Both `Realm` and `realm` directory exist in the project set up in a case-sensitive file system. 

It is probably due to the lines of `build.sh`. https://github.com/realm/realm-cocoa/blob/master/build.sh#L536-L539

```
In case-insensitive file system
├── Headers
│   ├── Private
│   │   └── Realm
│   │       ├── Realm
│   │       └── realm.hpp
│   └── Public
│       └── Realm
│           └── Realm
├── Local\ Podspecs
├── Manifest.lock
├── Pods.xcodeproj
├── Realm
│   ├── LICENSE
│   ├── README.md
│   ├── Realm
│   ├── build.sh
│   ├── core
│   │   └── librealm-ios.a
│   └── include
│       ├── Realm
│       └── realm.hpp
└── Target Support Files
```

```
In case-sensitive file system
├── Headers
│   ├── Private
│   │   └── Realm
│   │       ├── Realm <= !
│   │       ├── realm  <= !
│   │       └── realm.hpp
│   └── Public
│       └── Realm
│           └── Realm
├── Local Podspecs
├── Manifest.lock
├── Pods.xcodeproj
├── Realm
│   ├── LICENSE
│   ├── README.md
│   ├── Realm
│   ├── build.sh
│   ├── core
│   │   └── librealm-ios.a
│   └── include
│       ├── Realm <= !
│       ├── realm <= !
│       └── realm.hpp
└── Target Support Files
```

**Comment by ikonst** [comment]
> I think it will occur when copying a project that was set up on a case-insensitive file system to a case-sensitive file system.

To reproduce this, I've created an entirely new project on a case-sensitive filesystem. (This is the .dmg I've linked to above.)

@kishikawakatsumi Are you having trouble reproducing this on your machine?

**Comment by kishikawakatsumi** [comment]
@ikonst I usually use the case-sensitive file system. As mentioned above, it does not have any issue to a new setup, except the directory structure is a little different.

**Comment by ikonst** [comment]
@kishikawakatsumi I'll re-test it on my side. Is it enough to create a new project in Xcode, add a Podfile with Realm and `pod install`, or should I also delete something in ~/.cocoapods?

**Comment by kishikawakatsumi** [comment]
@ikonst Just in case, 

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
```

then,

```
pod install
```

**Comment by jpsim** [comment]
The outcome of this thread is that using Realm on a case-sensitive file system should work, but mixing case-sensitive and case-insensitive projects will lead to problems.

Generally, I'd advise against using HFS+ in case-sensitive mode because many apps aren't tested in this configuration.

Closing for now, @ikonst let us know if we need to reopen this.
