### ISSUE TITLE
Realm threading issue when object has NSData property

### ISSUE THREAD

**Issue by mfclarke** [realm/realm-cocoa#2145]
I have a schema as follows:

```
Person hasMany Dogs
Dog has an NSData property
```

I create my children objects and populate their NSData property on a separate thread, since committing ~100KB data per object can noticeably pause the main thread while animations/scrolling is happening.

After doing this I call a method on the main thread, but inside this method the created child object doesn't exist as a child of the parent. However, I can successfully verify that the children are present before calling the method on the main thread.

I may be doing something wrong, so I have created a concise example project here: https://github.com/mfclarke/RealmThreadingIssue

The "RealmIssueManifester" class contains the relevant code and NSAssert's to verify the unexpected behaviour.

**Comment by mfclarke** [comment]
For reference, here is the offending section of code:

```
dispatch_async([RealmIssueManifester testQueue], ^{
        RLMRealm *realm = [RLMRealm defaultRealm];
        Person *person = [Person objectForPrimaryKey:key];
        
        [realm beginWriteTransaction];
        Dog *dog = [[Dog alloc] init];
        dog.imageData = imageData;
        [person.dogs addObject:dog];
        [[RLMRealm defaultRealm] addObject:dog];
        [realm commitWriteTransaction];
        
        // Check the person has a dog on the current thread
        person = [Person objectForPrimaryKey:key];
        NSAssert([person.dogs count] > 0, @"");
        
        dispatch_async(dispatch_get_main_queue(), ^{
            // Check the person has a dog on the main thread
            Person *mainThreadPerson = [Person objectForPrimaryKey:key];
            NSAssert([mainThreadPerson.dogs count] > 0, @"");
        });
    });
```

The second NSAssert (inside the main thread dispatch) fails

**Comment by tgoyne** [comment]
`dispatch_async(dispatch_get_main_queue(), ^{ ... });` immediately after a write transaction is committed will sometimes run the block before our cross-thread change notifications get a chance to run, and thus before the realm on the main thread is refreshed. If this is the problem you're hitting, explicitly calling `[[RLMRealm defaultRealm] refresh]` at the beginning of your block dispatched to the main queue will fix it.

**Comment by mfclarke** [comment]
Thanks @tgoyne that has resolved the issue in the test app.

Unfortunately I'm still seeing the issue in the actual code I'm working on. It must be something different but related. I'll keep investigating and post what I find in case someone else has similar issues.

**Comment by mrackwitz** [comment]
@mfclarke: Were you able to resolve that issue in your actual code? I'd close that for now, but if you found something new and related, feel free to come back and reopen this issue.

**Comment by mfclarke** [comment]
Hi @mrackwitz, sorry for not updating this issue sooner. I had to get this code working with a deadline so I ended up reworking it to create the Realm objects all at once rather than individually. I know this isn't necessarily a solution but I hope it helps someone if they run into a similar problem.
