### ISSUE TITLE
Nullable primitives in Swift

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#2147]
`dynamic var prop: Int` works, but `dynamic var prop: Int?` wont even compile
compiler complains that `Int?` is a type that can't be represented in ObjC

`dynamic var prop: RLMInt?` works (when `RLMInt` is an `@objc protocol` that
`NSNumber` conforms to) and we can use swift runtime reflection to figure out the 
proper type (protocols only seem to get type-erased when they're not being used 
as generic parameters). You can assign any 'number' type to these properties,
but you'd need to force downcast to get a value out. We cant make the protocols 
conform to their swift equivalents (i.e. `IntegerType`) because then it couldn't 
be `@objc` and thus couldn't be used as a `dynamic` property.
[This solution is the one most analogous to how I've successfully prototyped 
object-type primitives in ObjC]

using raw `dynamic var prop: NSNumber?` would work, except there's no good way to
figure out _which_ type of number to use during schema initialization. Swift has
no way to define a property as a type composed of a class and a protocol 
(ala `NSNumber<RLMInt> *`), so that approach is also out. 

If we required users to specify a non-nil default value for these properties,
we could require them to wrap those defaults in a function call
(`dynamic var prop: NSNumber? = RealmInt(5)`) that could return a subclass that 
we could use to identify the proper type, but that's gross, is easy to forget,
and doesnt allow for nil default values.

We could also use new classes, either a subclass of `NSNumber` or `NSObject`.
Either way, we'd be giving up on tagged pointer numbers, which would be a _massive_
performance loss. Either way, we could make assigning number literals work via
custom literal convertible protocols, but assigning computed values would only 
work if it were an `NSNumber` subclass. I'm not sure using swift's arithmetic 
operators would work with either or these approaches, although it's more likely
they would as an `NSNumber` subclass.

**Comment by jpsim** [comment]
I feel like we're going further and further down the rabbit hole with these approaches and it may be worth exploring completely new options.

Here are two more bad options I could think of:

**Approach 1: Codegen (i.e. custom setter/getter for every property)**
```swift
import Foundation

class Object: NSObject {
    var _rlmObject = Dictionary<String, AnyObject?>()

    subscript(key: String) -> AnyObject? {
        get {
            return _rlmObject[key]!
        }
        set {
            _rlmObject[key] = newValue
        }
    }
}

class Model: Object {
    var intProp: Int? { get { return self["intProp"] as? Int } set { self["intProp"] = newValue } }
}

let instance = Model()
instance.intProp = nil
instance.intProp // => nil
instance.intProp = 123
instance.intProp // => 123
```

**Approach 2: RealmOptional type**
```swift
import Foundation

protocol OptionalRealmType {}

extension Int: OptionalRealmType {}

struct RealmOptional<T: OptionalRealmType>: NilLiteralConvertible, CustomStringConvertible {
    private var backingValue: T? = nil
    var value: T? {
        get {
            return backingValue // get value from Realm
        }
        set {
            backingValue = newValue // set value in Realm
        }
    }
    init(_ value: T?) {
        self.value = value
    }
    init(nilLiteral: ()) {
        value = nil
    }

    var description: String {
        if let value = value {
            return String(value)
        }
        return "nil"
    }
}

class Object: NSObject {}

class Model: Object {
    var intProp: RealmOptional<Int> = nil
}

let instance = Model()
instance.intProp // => nil
instance.intProp.value = 123
instance.intProp // => 123
```

**Comment by thanyalukj** [comment]
Im inclined toward the badness of option 2 If I have to.

**Comment by bdash** [comment]
Is there anything remaining here that #2458 didn't address?
