### ISSUE TITLE
Function to update/add object in realm data models 

### ISSUE THREAD

**Issue by perwyl** [realm/realm-cocoa#2149]
I want to auto add a `timestamp field` for each `realm data model object` . It will be helpful for the synchorization (merging decisions) between the devices and server. Thus I need a function to add new `realm data model object` base on the `realm data model's keys`. 

Currently, from what i understand is that one can only add a new object within the migration block.  So my current proposed solution is that i will do a reflection on the realm data models to get the keys, then create a migration block and add new objects for each key. After which, i will update the database. Which is definitely not the right approach! 

Is it possible to have a function that allows me to `create if not exist update` for the realm data model field? 

 ```
 realm.write {
  realm.add(<realm data model>,"<realm data model object field name>", update: true)
} 
```
I am using realm swift for development. 

Thanks 
Perwyl

**Comment by segiddins** [comment]
@perwyl as it turns out, we already have such a method! The following code snippet should do the trick, using [`Realm.create(_:value:update:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6createFS0_U__FTMQ_5valuePSs9AnyObject_6updateSb_Q_).

```swift
 realm.write {
  realm.create(<realm data model>,["propertyName" : newValue], update: true)
} 
```

**Comment by perwyl** [comment]
@segiddins  i got this error msg `*** Terminating app due to uncaught exception 'RLMException', reason: 'Missing property value'
*** First throw call stack:
libc++abi.dylib: terminating with uncaught exception of type NSException`  

What i did was, 
1. add the `realmObject` to `realm`
2. get a reflected object on `realmObject`
3. create a timestamp for each key in `realmObject`
4. update `realmObject` with the timestamps

PS: the timestamp keys does not exist in `realmObject` 

`var realmObject = RLMObject()
realm.write{
realm.add(realmObject, update: true)
}

var reflectedObject = reflect(realmObject)
var timestampList = [String: NSDate]()

for var index = 0; index < reflectedObject ; ++index {
  var property : String  = reflectedObject[index].0 + "TimeStamp"
  timeStampList[property] = NSDate()
}

realm.write {
  realm.create(RLMObject.self, value:timeStampList, update: true)
}`

**Comment by jpsim** [comment]
It looks as though you're mixing Realm Objective-C and Realm Swift (passing `RLMObject()` to `realm.add(_:)`), which is unsupported. I've just added a note at the very top of our online documentation to reflect this.

Also, from our `Object` docs ([link](https://realm.io/docs/swift/latest/api/Classes/Object.html)):

> In Realm you define your model classes by subclassing Object and adding properties to be persisted. You then instantiate and use your custom subclasses instead of using the Object class directly.

So instead of creating `Object()` directly, you should define your model as a subclass (like `class MyModel: Object { /* properties here... */}`) and create instances of that directly. You can read more about modeling data in Realm in the [Models section of our Swift documentation](https://realm.io/docs/swift/latest/#models).

Finally, you should be setting properties directly rather than constructing a property name at runtime from the reflection, which I'm confused as to why you would want to do this at the moment.

So here's another take on your code from my assumptions in what you're trying to accomplish:

```swift
import RealmSwift

// MARK: Model definitions

// schema v0
// class Person: Object {
//   dynamic var name = ""
// }

// schema v1
class Person: Object {
  dynamic var name = ""
  dynamic var nameTimeStamp = NSDate()
}

// MARK: Migration

setSchemaVersion(1, Realm.defaultPath, { migration, oldSchemaVersion in
  if oldSchemaVersion < 1 {
    // Nothing to do, since the default value of `Person().nameTimeStamp` is already the current date.
  }
})
```

**Comment by perwyl** [comment]
Thanks @jpsim  for the quick reply. Sorry for my bad naming, `RLMObject ` is just a class name representation. I want to create the properties at runtime is that for each class, I had a lot of properties. 

Just thinking it might be good for me to create (dynamically ) new properties (timestamps) at run time (i need a timestamp for each property in a class). The reason for the timestamps is that it will be helpful for synchorization (merging decisions) between the devices and server.    

```
class RLMObject: Object {
 dynamic var name = ""
...
}
```

**Comment by jpsim** [comment]
I see! If you want a dynamic list of timestamps, I'd still do this in a type-safe manner defined at compile-time like so:

```swift
class TimeStamp: Object {
  dynamic var propertyName = ""
  dynamic var lastModified = NSDate()
}
class BaseModel: Object {
  let propertyTimeStamps = List<TimeStamp>()
}
class Person: BaseModel {
  dynamic var name = ""
}
```

This does mean that every time you edit the property on an object, you'll have to update its respective entry in `propertyTimeStamps`, but this will give you the behavior you want, without requiring you to duplicate every property on your models.

**Comment by perwyl** [comment]
@jpsim thanks ! Let me try it out. 

And may i know the purpose of this method ?

```
 realm.write {
  realm.create(<realm data model>,["propertyName" : newValue], update: true)
} 
```

**Comment by jpsim** [comment]
You can see the API documentation for that method [here](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6createFS0_U__FTMQ_5valuePSs9AnyObject_6updateSb_Q_):

> Create an `Object` with the given value.

> Creates or updates an instance of this object and adds it to the Realm populating the object with the given value.

> When ‘update’ is ‘true’, the object must have a primary key. If no objects exist in the Realm instance with the same primary key value, the object is inserted. Otherwise, the existing object is updated with any changed values.
