### ISSUE TITLE
Calling .sorted on List<T> causes crash

### ISSUE THREAD

**Issue by staticdreams** [realm/realm-cocoa#2150]
I'm using RealmSwift

From what I gathered in documentation ``List`` types are much more like ``Result`` and can be sorted.
Code gives no warning or error, but my app crashes every time I'm trying to sort a ``List`` saying ``This method can only be called on RLMArray instances retrieved from RLMRealm``

What am I doing wrong?

**Comment by segiddins** [comment]
@staticdreams that exception message could probably be made more clear for Realm Swift, but the gist of it is that you can only call `sorted` on a `List` property that comes from an object that is persisted in a `Realm`.

**Comment by staticdreams** [comment]
I'm confused. So, ``sorted`` can only be called on ``List`` that comes from ``Result`` and not a standalone List I created? All I wanted if to sort the existing List by property. Too bad realm lacks those simple array methods on List to make a few manipulations :(

**Comment by mrackwitz** [comment]
The sorting of retrieved `List` instances is done by the DBMS. `Lists` are not intended for being instanced standalone. So you either have to ensure that your data is persisted and can be retrieved or you would need to use the standard libraries capabilities of sorting by using e.g. Swift's `Array`.
But please feel free to explain your use case more and why you want to use `List` for that, so we can understand your needs a bit better.

**Comment by staticdreams** [comment]
@mrackwitz , thanks for your answer.

Sometimes, (and perhaps I'm not the only one) I need some further data processing when I retrieve records from realm. Manipulating data before presenting it to the view (like joining with other data, sorting, etc) gives additional flexibility. Don't get me wrong I love realm, but I always felt constrained but little things like inability to handle data easily since end up with custom data types like ``Results`` and ``List``. Ok, here's my example:

I got a table containing bus stops (``List<Stop>``) Each stop has coordinates (latitude and longitude). Before Displaying the data to the view I grab it (and all associated relations), see where the user is currently positioned and enumerating through each item, measuring its distance to the user and putting the ones  within 100m in an empty ``List<Stop>``. Say, now I want to sort this List by distance... or process it further, removing some items based on on some other changing conditions. I do not mind, but since ``List`` isn't a standard type, handling it can be a challenge if you see what I mean.

Reading other issues here I see people are starting to come up with ``Extension``s for List and Result types, making some "post-query" operations easier.

**Comment by mrackwitz** [comment]
Did you saw [ABFRealmMapView](https://github.com/bigfish24/ABFRealmMapView)? That's a reusable implementation of some ideas, how you could let Realm do the location-related filtering.
One idea which is also implemented there, is that, once you have a subset of relevant objects, you can wrap each of them in a helper class/struct. There you can also store the current distance from the user position, so you have some caching for the distance calculation for the sorting and you can use the standard libraries to achieve that and further filtering.

**Comment by bigfish24** [comment]
@staticdreams I built [ABFMapView](https://github.com/bigfish24/ABFRealmMapView) and at least for your example, I would recommend first doing a bounding box query in Realm to return objects within within the 100m region and then iterating over this list to either add the temporal distance calculation directly to the object or in a helper class/struct that points to the object (assuming you are using primary keys to make it thread-safe, which is what [ABFMapView](https://github.com/bigfish24/ABFRealmMapView) does). This will help make sure you aren't doing the distance calculation and secondary sorting on the entire dataset.

To make it easy to create a predicate from a coordinate region, [ABFMapView](https://github.com/bigfish24/ABFRealmMapView) has a [function](https://github.com/bigfish24/ABFRealmMapView/blob/master/ABFRealmMapView/ABFLocationFetchRequest.h) that does this for you:

```
/**
 *  Converts a MKCoordinate region to an NSPredicate
 *
 *  If the region span cross the -180/180 longitude meridian, the return value is an NSCompoundPredicate containing two NSPredicates that comprise of the region before the meridian and another region of the overflow beyond it.
 *
 *  @param region           MKCoordinate region representing the location fetch limits
 *  @param latitudeKeyPath  the latitude key path for the value to test the latitude limits against
 *  @param longitudeKeyPath the longitude key path for the value to test the longitude limits against
 *
 *  @return instance of NSPredicate (can be NSCompoundPredicate, see description for more info)
 */
extern NSPredicate * NSPredicateForCoordinateRegion(MKCoordinateRegion region,
                                                    NSString *latitudeKeyPath,
                                                    NSString *longitudeKeyPath);
```

**Comment by staticdreams** [comment]
Thanks @mrackwitz , I guess I'll have to do most of the work within queries :)
@bigfish24 Cool! Although my example here was to illustrate that it is hard to manipulate non standard objects once the DB has been queried. 
What I did was a loop thought query results and used ``fromLocation.distanceFromLocation(toLocation)`` on each object. Work fine, but regrouping it all together and sorting by distance was a pain :) Anyway, thanks, I'll give your project a try.
