### ISSUE TITLE
Could not build Objective-C module 'Realm'

### ISSUE THREAD

**Issue by reeichert** [realm/realm-cocoa#2151]
Hi, i'm using Xcode 6.4, my project run and compile on simulator, but when I try to run on my device (iPhone 6 & iPad 4) i getting this error 

![captura de tela 2015-07-02 as 11 50 01](https://cloud.githubusercontent.com/assets/1337535/8479900/0cb86ac2-20b1-11e5-9079-ed1d011b3d9f.png)

**Comment by jpsim** [comment]
@reeichert sorry for the delay on getting back to you on this issue. Are you possibly using Realm via CocoaPods? If so, I'd recommend first reinstalling your pods after clearing the CP cache:

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

If that fixes the problem, I'd encourage you to file an issue at https://github.com/CocoaPods/CocoaPods/issues.

This is an issue I believe we've seen in the past, but I can't find a prior case at the moment.

Please let us know if this helps at all.

**Comment by jpsim** [comment]
As we never heard back from you, @reeichert, we'll be closing this issue. Let us know if our suggested fix didn't work and then we'll reopen the issue and work with you to address. Thanks!
