### ISSUE TITLE
NSDates in the far future are not stored correctly

### ISSUE THREAD

**Issue by camh** [realm/realm-cocoa#2152]
(Using Realm 0.93.2)

I'm trying to store an expiration date on a subclass of `RLMObject`. So the default `expiresAt` property (*cough* since `nil` in unsupported *cough*) must be a date in the far future. I saw `[NSDate distantFuture]` is not supported in the documentation. So using [DateTools](https://github.com/MatthewYork/DateTools/tree/master/DateTools), I made the default value 500 years in the future.

```
+ (NSDictionary *)defaultPropertyValues{
	return @{
			 @"expiresAt" : [[NSDate date] dateByAddingYears:500]
			 };
}
```

But after it has been committed to the Realm:

```
expiresAt = 1901-12-13 20:45:52 +0000;
```

Huh. Well, that's fine, maybe 100 years in the future?

```
expiresAt = 1901-12-13 20:45:52 +0000;
```

So how many years in the future is supported? 25 doesn't work. 20 does. This is a huge limitation. I knew about no second precision, but this is not documented at all. Are there other limitations in your implementation of storing dates that are not documented? Why don't you store lossless dates?

**Comment by marchyman** [comment]
> 
> So how many years in the future is supported? 25 doesn't work. 20 does. This is a huge limitation. I knew about no second precision, but this is not documented at all. Are there other limitations in your implementation of storing dates that are not documented? Why don't you store lossless dates?

Guess: The furthest date that can be expressed is 03:14:07 UTC on Tuesday, 19 January 2038.

Google “Year 2038 problem” to see why I made that guess.

Marc

**Comment by segiddins** [comment]
Yup, I can reproduce this on 32-bit iOS devices. I'm going to have a look at supporting greater date ranges on 32-bit devices :)
