### ISSUE TITLE
Realm instance persisting unexpectedly

### ISSUE THREAD

**Issue by ezwu** [realm/realm-cocoa#2157]
Hello,

I'm developing an app that uses Realm in conjunction with user accounts. I've recently added this code for migration:
```
RLMRealm setSchemaVersion:1
                        forRealmAtPath:[GGRealmUtils realmPath]
                    withMigrationBlock:^(RLMMigration *migration, uint64_t oldSchemaVersion) {
        //migration code
}
[RLMRealm realmWithPath: realmPath]]
```
The app itself is user account based, so each realmPath is unique to the userId, and I can't just put this migration code in appdelegate since if a user logs out on their phone and has someone else log in, I would need to migrate for the new person as well, so I put it in my login controller and trigger it whenever someone logs in using the associated realmPath.

The issue I am having arises from writing to the user realm a second time while they are logged in, basically. Upon log in I make my first write transaction as follows:
```
// Instantiate realm object
RLMRealm *realm = [self realmForCurrentUser];
	
    [realm beginWriteTransaction];
    // write some objects using [realm addObject:]
    [realm commitWriteTransaction];
```
And at a certain point in the app after the user has done something I need to make another write transaction, so I run a variation on that same code again. 

However, through testing and logging I've seen that the first realm instance gets deleted by ARC automatically as soon as the scope of my write transaction ends, but the second time I do it it persists for some reason and ARC doesn't clean it up, even though I don't have any references to it in my code. And so, if the user tries to log out and log back in, the migration code will through an exception:
```Cannot set schema version for Realms that are already open.```
because the realm instance is still cached.

Is there a method I can use to manually clear the realm cache? I'm very certain that I don't have any references to the realm (my code is pretty much the exact same for both the first and second write, minus the different objects to write), so why is the realm instance not being deleted from the cache?

**Comment by segiddins** [comment]
@ezwu there's no publicly exposed way to manually clear the Realm cache, but it's really not something you should ever have to do. If there's already a Realm open, I suspect something still has a strong reference to it, and we'd be happy to have a look at help you debug that, either here or privately at help@realm.io.

If I could offer a suggestion, however, I'd advise just calling `setSchemaVersion:ForRealmAtPath:withMigrationBlock:` for every `.realm` file in the directory you store the Realm files in at program launch -- that way, there would be no possibility of trying to set the schema version for a Realm that is already open.

**Comment by ezwu** [comment]
@segiddins thanks for the reply and the suggestion. I've checked my code for remaining references over and over but I just can't seem to find anything. I'm doing the bugged realm operations within a AWSTask continueWithBlock:^id(AWSTask *task) call, could that possibly be an issue?

If I were to migrate in the manner you described, what would happen in terms of schema version and migration when a new user logs in and I create a new realm? Would their realm automatically be updated to the post-migration version?

**Comment by segiddins** [comment]
@ezwu you _could_ just set the schema version when creating the realm for the first time.  If you're capturing any Realm objects in a block that's being bounced to a different queue, that could definitely be causing your RLMRealm to be retained, but it's hard to know for sure without seeing the code in question.

**Comment by ezwu** [comment]
@segiddins Thanks immensely for your help. The queue issue doesn't seem to be the cause after some testing, since my other calls to realm occur on a background thread as well and don't cause me any problems.
I think what might be happening is that I'm potentially holding onto a reference of the object I am adding to the realm. Would that RLMObject's reference to the realm instance cause the realm to fail to deallocate? If that's the case, I think that that might be the reason for my issue.

I've tested two different ways of writing the necessary object to realm, the first being the original bugged way which is to call ```[realm addObject:]``` using my local reference to the object. The second way is to first pull from the online database Amazon dynamoDB, where the object is stored and then to add it to realm using the reference dynamoDB gives me, and that way doesn't cause the migration code to throw an exception.

As for your suggestion, could I just ask you to clarify how schema versions work? Specifically, my migration code sets, for specific objects, a new property that didn't exist on the old version to some default value. So if I were to open a new realm and write these objects with the new property already set to some other value into it, would the schema automatically update to reflect the fact that this property now exists or would it be some default value like 0 that would trigger the migration code to overwrite the value?

**Comment by segiddins** [comment]
Yes, a persisted `RLMObject` has a strong reference to its RLMRealm.

We just talked over the API here in the office, and we think it makes sense to _not_ throw an exception when using the `setSchemaVersion` API in the manner you are (aka. your use case should be supported), so disregard my wacky suggestions for working around our api :)

**Comment by ezwu** [comment]
Awesome, I understand now. Thanks very much for you help!
