### ISSUE TITLE
Having to assign both sides of a relationship - am I doing it wrong?

### ISSUE THREAD

**Issue by iandundas** [realm/realm-cocoa#2158]
_If this would be better submitted to StackOverflow, let me know and I'll move it there :)_

I'm just looking for help understanding what's happening behind the scenes, with regards to Relationships.
	
When we have a one-many relationship, it seems we must set the relationship at both ends, (e.g. if we have a Town with many places, we must set `place.town=town` _as well as_ `[town.places addObject:place]`, whereas what I'd expect is that if I set `place.town=town`, then querying `town.places` would automatically contain that place.

It seems we must set it at both ends, i.e.:

    Town *amsterdam = [Town new];
    amsterdam.name = @"Amsterdam";

    Place *brewery = [Place new];
    brewery.name = @"Brouwerij t Ij";

    brewery.town = amsterdam; // associate once
    [amsterdam.places addObject:brewery]; // associate in the other direction, too

    [realm beginWriteTransaction];
    [realm addObject:amsterdam];
    [realm addObject:brewery];
    [realm commitWriteTransaction];

If we don't, those unset references will remain set to nil.

Is this a limitation of Realm, or am I missing something? 

Cheers,
Ian

**Comment by yoshyosh** [comment]
This is correct, you can also use backlinks so that you don't have to add them to both. https://realm.io/docs/swift/latest/#inverse-relationships
