### ISSUE TITLE
Crashing during a write transaction makes other processes "hang" indefinitely

### ISSUE THREAD

**Issue by conradev** [realm/realm-cocoa#2159]
![screen shot 2015-07-04 at 7 32 04 pm](https://cloud.githubusercontent.com/assets/170649/8514307/19cf1020-2341-11e5-8d4b-536d7efef6a7.png)

If our WatchKit extension crashes while a write transaction is open, the lock is never released. Our main app then hangs. Is this a known/expected issue?

**Comment by segiddins** [comment]
I believe this is to be expected, as we're using a `pthread_mutex` under the hood, which is not robust against crashing processes.

**Comment by tgoyne** [comment]
Yes, this is expected. POSIX has robust mutexes that support recovering from a process crashing while the mutex is locked, but Apple hasn't implemented them. We've looked into some workarounds, but we haven't found any particularly reliable options. The mutex is recreated when a Realm file is opened and no other threads/processes have it opened already.

**Comment by jpsim** [comment]
#2169 should resolve this.

**Comment by tgoyne** [comment]
Only very partially. There's a lot of ways for a process to crash other than an uncaught exception.

**Comment by bdash** [comment]
@tgoyne, do you recall what workarounds we looked at for this?

**Comment by tgoyne** [comment]
The ideas I remember are storing the pid of the locking process and doing ~something~ if a process with that pid doesn't exist, using `flock()` for the write lock rather than a mutex, and using a named pipe rather than a mutex.

**Comment by jpsim** [comment]
Moved to P2 because we don't think we can resolve this in the short term, along the same level of priorities as the rest of our P1 issues.

**Comment by conradev** [comment]
That's unfortunate – an enable-able workaround would be an ideal solution for our use case. I'm not sure how hard it would be to get an alternate locking system to work reliably, but I would definitely enable "slightly slower, but more robust" locking.

If I decide to kill Workflow from the app switcher or Jetsam decides to kill one of our extensions and the process happens to be modifying the database at the time, I have to reboot my device in order to use Workflow. Granted, it's rare, but we do get support emails about it.

**Comment by bdash** [comment]
Out of the options @tgoyne mentions, `flock` seems most directly suited to this purpose. I can't see any obvious downsides to it, except the potential for worse performance compared with our current use of mutexes.

**Comment by conradev** [comment]
I use `flock` to great success in [mixpanel-simple](https://github.com/conradev/mixpanel-simple) and [WFNotificationCenter](https://github.com/DeskConnect/WFNotificationCenter), it seems like a great candidate.

While `flock` handles the case in which the process is terminated, it doesn't handle the case in which the process is suspended with the lock acquired, but, alas, nothing handles that… :(

**Comment by AriX** [comment]
@jpsim @bdash Unfortunately this issue is seriously affecting some of our users. Is it possible to switch to `flock`, perhaps as an option in the `RLMConfiguration` (if you are concerned about the performance drawbacks compared to the mutex)?

We would be happy to work on this, but it looks like this functionality is in the Realm core and not in this repo, unless I missed it?

**Comment by bdash** [comment]
You're correct that the relevant functionality lives in Realm's core rather than at the Cocoa level.

**Comment by AriX** [comment]
Ahh, got it. What do you think is the best way forward here? We would gladly pay for Realm's consulting services if it meant we could get this implemented.

**Comment by jpsim** [comment]
Moving back to P1 since now there's a clear path to resolution and thanks to @conradev and @AriX sharing how important it is to them.

**Comment by bdash** [comment]
Work on a more robust interprocess locking mechanism is underway in Realm's core.

**Comment by AriX** [comment]
Thanks for the update, Mark!

**Comment by bdash** [comment]
Realm core has landed a robust mutex implementation based on file locks. This change will make it into a core release in the near future, where it can then be picked up in realm-cocoa.

**Comment by AriX** [comment]
🎉🎉🎉 Can't wait to see this release! This will be very helpful to our users. We've partially solved the issue since we last discussed this (by minimizing the number of write transactions that occur and fixing certain crashes that might interrupt them), but it still happens at times -- this solution will be great for our affected users.

Many thanks!

**Comment by bdash** [comment]
This was part of v0.101.

**Comment by AriX** [comment]
Amazing - thank you so much! Very excited to get this out to people.
