### ISSUE TITLE
Enhancing RLMSortDescriptor by taking something similar to NSComparator

### ISSUE THREAD

**Issue by francisykl** [realm/realm-cocoa#2161]
This allows easier / direct implementation for sorting logics, and reduces performance penalty.

For reference/more details please refer to http://stackoverflow.com/questions/31237962/how-can-i-shuffle-rlmresults-in-swift?

**Comment by jpsim** [comment]
Thanks for filing this, @francisykl. We're already tracking this feature in #1265 so I'll be closing this ticket as a duplicate. Subscribe to that one for any updates on the topic.
