### ISSUE TITLE
Inheritance Querying or Combining Queries

### ISSUE THREAD

**Issue by jboulter11** [realm/realm-cocoa#2164]
I need functionality to combine a query of multiple RLMObjects, so I can either query a superclass, query a group of objects, or query objects separately and combine their responses.  Can anyone suggest a solution?  My current setup is one superclass and three subclasses with different properties.

If this functionality doesn't exist, I might suggest adding a function to RLMObjects like so:

```objective-c
+(NSArray*)subclasses
{
    return @[@"subclass1", @"subclass2", @"subclass3"];
}
```

And then using that information to chain a query internally and return a combined result.

This is a really key feature that would help me out.

**Comment by jpsim** [comment]
This kind of query polymorphism isn't yet possible in Realm, but we are tracking this feature request as #1109. I'm closing this as a duplicate of that issue, which you can subscribe to for any updates on the topic. Thanks!
