### ISSUE TITLE
What means "Unevaluated query on"?

### ISSUE THREAD

**Issue by Luke47** [realm/realm-cocoa#2165]
I try to query my Realm Swift database for a given message (by messageID). `UserMessage` and `ActionMessage` are subclasses of `ChatMessage` and I found out, that I need to query each subclass individually, to fetch them all. That's why I combine them in the `allResults` array.

```swift
let realm = Realm()
let messageToDeleteResult1 = realm.objects(ChatMessage).filter("messageId == '\(messageID)'")
let messageToDeleteResult2 = realm.objects(UserMessage).filter("messageId == '\(messageID)'")
let messageToDeleteResult3 = realm.objects(ActionMessage).filter("messageId == '\(messageID)'")
let allResults = map(messageToDeleteResult1) { $0 } + map(messageToDeleteResult2) { $0 } + map(messageToDeleteResult3) { $0 }
```

Now, my problem is, that each single result gives me `Unevaluated query on`, it finds however a single value, but the properties for that are only the default ones, as stated in the class file. (I use the debugger to see that).

Can you please tell me what the error is and how I can fetch the object properly with all his attributes?

**Comment by jpsim** [comment]
The `Unevaluated query on (class name)` should only appear in the debugger (lldb is unable to materialize the `Results`). In fact, Realm's lldb plugin is only supported for Objective-C at the moment.

The code you posted should work, although if I could recommend a variation, you could use `flatMap` to apply the same query on all 3 classes and combine their results:

```swift
let allResults = [ChatMessage.self, UserMessage.self, ActionMessage.self].flatMap { modelClass in
  return map(realm.objects(modelClass).filter("messageId == '\(messageID)'")) { $0 }
}
```

**Comment by Luke47** [comment]
Ok, thank you very much @jpsim !

BTW: Is this a proper place to ask questions? Because I just read that you want to have all questions asked on StackOverflow?

**Comment by Luke47** [comment]
I've tried your suggestion, but I keep receiving the following error:
`Object type 'Object' not persisted in Realm`
- Guess it's a Swift bug?

**Comment by segiddins** [comment]
@Luke47 do you have a full back trace for where that exception message is popping up?

**Comment by jpsim** [comment]
> BTW: Is this a proper place to ask questions? Because I just read that you want to have all questions asked on StackOverflow?

If you have a general usage question, like when you're unsure how to do something that you think is supported, StackOverflow is a good place to ask.

When you think you've found a bug, filing a GitHub issue on this repo is appreciated.

In this case, it seems like this could be a bug, so a GH issue was a good idea :smile:.

I'd try disabling Realm's LLDB plugin (you can do this by temporarily renaming your `~/.lldbinit` file to something else). Although if that fixes the issue for you, I think we'll have to add a check for this in `rlm_lldb.py` to avoid this happening in the future.

**Comment by Luke47** [comment]
@segiddins , sure here you go. It seems that by using `flatMap` the results lose their subclass information and simply become `Object`

![screen shot 2015-07-08 at 12 11 02](https://cloud.githubusercontent.com/assets/5190003/8568108/21744d6e-256b-11e5-9b79-28573c1be49f.png)

**Comment by jpsim** [comment]
> It seems that by using flatMap the results lose their subclass information and simply become Object

No, I think the debugger is showing you that because you're in the generic `objects(_:)` function, which is specialized on `T: Object`. If you look at the inferred type from that function, it will be `Results<YourObjectType>`.
