### ISSUE TITLE
Can't use Realm (installed with Carthage) with a framework in a Swift app

### ISSUE THREAD

**Issue by Pym** [realm/realm-cocoa#2172]
I'm working on an iOS App and a Watchkit App.

I read a few things regarding best practices and I decided to create a custom framework, as NathashaTheRobot advise here:
https://realm.io/news/architecting-app-apple-watch-natashatherobot/

So I'm trying to use Realm in my framework.

I followed the [installation instructions for Carthage][1]:

>  1. Add `github "realm/realm-cocoa"` to your `Cartfile`.
> 
>  2. Run `carthage update`.
> 
>  3. Drag `RealmSwift.framework` and `Realm.framework` from the
>     `Carthage/Build/iOS/` directory to the “Linked Frameworks and
>     Libraries” section of your Xcode project’s “General” settings.
> 
>  4. On your application targets’ “Build Phases” settings tab, click the
>     “+” icon and choose “New Run Script Phase”. Create a Run Script with
>     the following contents:
> 
>     `/usr/local/bin/carthage copy-frameworks`
> 
> and add the paths to the frameworks you want to use under “Input
> Files”, e.g.:
> 
>     $(SRCROOT)/Carthage/Build/iOS/Realm.framework 
>     $(SRCROOT)/Carthage/Build/iOS/RealmSwift.framework

Then I added my framework to the `Target Membership` of both `Realm.framework` and `RealmSwift.framework`.

But when I try to build the project, I get this error:

    ld: framework not found Realm for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Then I gave a shot to `lipo`:

    $ lipo -info Carthage/Build/iOS/Realm.framework/Realm                                                                                                       
    Architectures in the fat file: Carthage/Build/iOS/Realm.framework/Realm are: i386 x86_64 armv7 arm64

Do you have any ideas of what I might be doing wrong here? Thank you.

  [1]: https://realm.io/docs/swift/latest/

**Comment by jpsim** [comment]
Closing and continuing the conversation at http://stackoverflow.com/q/31250342/373262.
