### ISSUE TITLE
Realm (0.91.1) corruption post crash

### ISSUE THREAD

**Issue by benagarr** [realm/realm-cocoa#2176]
I have found that sometimes, after my app crashes, or the disk fills up, the Realm database becomes corrupted.

Attached is the stack trace from XCode.  It crashes during launch.  The other interesting thing is that I cannot download the container from the device because Apple File Conduit complains about the Realm files.

Jul  7 18:01:14 FuryPad mobile_house_arrest[199] <Error>: AFCVersion="232.5" AFCCode="-402636790" AFCFileName="server.c" NSDescription="/private/var/mobile/Containers/Data/Application/06607B93-C65A-4169-8E66-4AF509FEC851//Documents/default.realm.note is special file" AFCFileLine="204" 
Jul  7 18:01:14 FuryPad mobile_house_arrest[199] <Error>: NSDescription="read" NSDebugDescription="Result too large" AFCFileLine="2033" NSUnderlyingError="34" AFCFileName="server.c" AFCCode="-402636796" AFCVersion="232.5" 

I'm not sure what exactly is inferred by the "Result too large" errors and the "default.realm.note is a special file".

I am on an older version of Realm (0.91.1) but reading the release notes for more recent versions gives me pause since there are discussions of crashes on those versions too.  Please advise.  

<img width="1326" alt="screen shot 2015-07-07 at 18 42 18" src="https://cloud.githubusercontent.com/assets/679271/8561317/8757773e-24d8-11e5-87a2-4904419c6a41.png">

I am working on switching to Core Data since Realm has been a big source of crashes and problems for months.  We regret using it at all.

Thanks!
-ben

**Comment by segiddins** [comment]
@benagarr sorry to hear you've been running into problems! Just looking at the stack trace, it's hard to tell what exactly is going wrong trying to open the Realm file, but if this is happening consistently, we'd love to take a look at the file itself (you can share it privately with us at help@realm.io).
As to issues with database corruption, I'd advise you to update to the latest release of Realm as soon as possible. Realm is still improving, and in the latest release, we're confident we addressed our number one outstanding issue with corruption, which had to do with ordering guarantees (or the lack thereof) around `ftruncate` and `fsync`. 0.93.2 should no longer produce truncated files, which is likely the issue you were running into previously.

**Comment by benagarr** [comment]
Do you have any clue about the "default.realm.note is a special file" error message that occurs when the I try to download the container.  It's kind of difficult to give you the realm.db file or examine it without being able to download the container from the device.

**Comment by segiddins** [comment]
I have no idea about that -- it might just be Xcode not knowing how to deal with files that are named pipes?

**Comment by benagarr** [comment]
I see in the release notes for 0.93.2 it says "Fix a case where data loss would occur if a device was hard-powered-off shortly after a write transaction was committed which had to expand the Realm file."

That's great, but I think the problem I'm experiencing has to do with a device's disk being full.  I think this happens to a lot of 16GB users and that seems to break Realm.  Perhaps it is a similar issue but perhaps not.  I would like to have a sense that you guys understand what happens when the DB needs to expand while the disk is full.  Is that a supported situation?  What will happen in that case?

I recreated this on my device by downloading lots of TV shows and then using apps until the disk filled.  I then used my app that uses Realm and perhaps it wrote some things to the DB.

**Comment by tgoyne** [comment]
Realm's persistence format is specifically designed to avoid modifying any of the data currently on disk until after all the new data is written (and then it flips a single bit to start using that new data), which means that running out of space when committing a write transaction should at most result in that write transaction being lost and the database left in a functional state. That's not a scenario we have automated tests for at the moment, so it's possible that a bug has slipped in at some point.

**Comment by benagarr** [comment]
Ok, I'm going to try to find a way to pull the potentially truncated Realm today.  If I can get it, I'll send it along.  Excited to hear your response about the disk full issue.  

Another side request I thought of that would make me feel a lot more comfortable would be if there were less frequent "stable" releases as opposed to just a new release every month or so.  

Thanks for looking into it.

**Comment by tgoyne** [comment]
Full disk handling does appear to be working correctly -- I made several disk images of various small sizes, inserted data until committing a write transaction threw an exception, and then verified that the Realm file was still openable and everything but the last write transaction was present.

**Comment by jpsim** [comment]
I believe this is not an issue given our tests on the matter. Please make sure you're using the latest version of Realm.
