### ISSUE TITLE
Compile error on swift-2.0 branch

### ISSUE THREAD

**Issue by pixeldock** [realm/realm-cocoa#2178]
The `swift-2.0` branch currently has a compile error:

`'RLMProperty' does not have a member named 'optional'` 

The error occurs in `Property.swift` line 46 in the RealmSwift pod

**Comment by pixeldock** [comment]
Closing this issue as it seems to work now.

**Comment by catherineschwartz** [comment]
Hey, I had the exact same issue this morning.

I found a workaround for `'RLMProperty'` to have the `optional` property: I forced the Cocoapods to include the same Realm (with the `optional` property, which wasn't there by including the first pod line alone):
```
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
```
But now I get the following error every time I call `Realm()`:
```
Call can throw, but errors cannot be thrown out of a property initializer
```
Have you seen something similar, or do you have any ideas on how to solve it? 

--
Xcode 7 beta 3
CocoaPods version 0.37.2
Build folders and Derived Data cleaned up

**Comment by jpsim** [comment]
> `Call can throw, but errors cannot be thrown out of a property initializer`
>
> Have you seen something similar, or do you have any ideas on how to solve it?

This isn't something I've seen before, but it looks as though it has to do with Swift 2's error handling. Is it possible that one of your Realm models has a default property value set to a function or initializer that `throws`?

**Comment by catherineschwartz** [comment]
Yes, the initializers were throwing the exception. I had to instantiate `Realm` like that:
```
let realm = try! Realm()
```
It works like a charm now, thanks :)

**Comment by segiddins** [comment]
Great, glad to hear you got it working, @catherineschwartz !
