### ISSUE TITLE
Look into making RLMSupport.swift support Swift 1.2 & 2.0

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2181]

**Comment by tgoyne** [comment]
It's currently identical on `master` and `swift-2.0`, so nothing to do.

**Comment by chucktee** [comment]
RLMSupport.swift has 2 compile errors (in two places.) First, GeneratorOf has been replaced with AnyGenerator, then once making that swap, the next is:
RLMSupport.swift:37:16: Cannot invoke initializer for type 'AnyGenerator<RLMObject>' with an argument list of type '(() -> _)'

**Comment by jpsim** [comment]
@chucktee take a look at [`RLMSupport.swift` on the master branch](https://github.com/realm/realm-cocoa/blob/master/Realm/Swift/RLMSupport.swift). It should work in both Xcode 6.4 & Xcode 7.

**Comment by chucktee** [comment]
@jpsim - Thanks a ton.  Compiles fine.
