### ISSUE TITLE
7.0.0-beta3: Build fails on swift-2.0 branch

### ISSUE THREAD

**Issue by jsslai** [realm/realm-cocoa#2184]
I'm using the latest version from swift-2.0 branch: https://github.com/realm/realm-cocoa/commit/4f2dcd95b3a5b573983f03d8eb1738c4796497f3 and using build command: 

>sh build.sh build

Now the buid fails and the log is as following:

>ld: warning: Auto-Linking supplied 'build/ios-dynamic/Realm.framework/Realm', 'build/ios-dynamic/Realm.framework/Realm' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
>Undefined symbols for architecture armv7:
>  "_RLMNotVersioned", referenced from:
>      RealmSwift.schemaVersionAtPath (Swift.String, encryptionKey : ObjectiveC.NSData?, error : Swift.AutoreleasingUnsafeMutablePointer<ObjectiveC.NSError?>) -> Swift.UInt64? in Migration.o
>..

Is the problem with the bitcode or something else? I thought the bitcode was already disabled.

**Comment by foffer** [comment]
I get the same trying to build this to my phone

**Comment by allending** [comment]
@jsslai @foffer 

- The current commit in the swift-2.0 only has bitcode disabled for the Realm.xcodeproj (https://github.com/realm/realm-cocoa/commit/308b0fa5099bdf8c985ef312962782668e56994e).
- You need to open the RealmSwift.xcodeproj project and explicitly set ENABLE_BITCODE to No - **Even if it already shows it as No by default, set it anyway**.
- Remember that any of your app targets using the framework also need to have bitcode disabled.

**Comment by jpsim** [comment]
@jsslai @foffer we just merged @allending 's PR addressing this issue. Please open a new issue if the latest `swift-2.0` is still causing problems for you! Thanks all!
