### ISSUE TITLE
program, between ios and java.

### ISSUE THREAD

**Issue by codesourse** [realm/realm-cocoa#2185]
How did you test this program, between ios and java.

**Comment by TimOliver** [comment]
Hi there!

How do you mean test exactly? Each version of Realm comes with several sample apps to let you see how it works. Are you having any trouble with that?

**Comment by codesourse** [comment]
java encrypt realm file,iOS decrypt realm file , throw following problem:
Error Domain=io.realm Code=2 "Invalid database" UserInfo=0x1708701c0 {NSLocalizedDescription=Invalid database, Error Code=2}

**Comment by codesourse** [comment]
i have a realm file , it create by android .when i query the data in iOS, i got a crash

*** Terminating app due to uncaught exception 'RLMException', reason: 'Migration is required for object type 'ZtyHomeWorkContent' due to the following errors:

Property 'ho_id' has been made a primary key.' *** First throw call stack:

**Comment by codesourse** [comment]
I use the realm encryption, decryption is unable to open ,in release.


    NSData *data=[self getKey];
    NSError *error=nil;
    @autoreleasepool {
        NSString *defaultRealmPath = [RLMRealm defaultRealmPath];
        NSString *v0Path = [[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:ML];
        [[NSFileManager defaultManager] removeItemAtPath:defaultRealmPath error:nil];
        [[NSFileManager defaultManager] copyItemAtPath:v0Path toPath:defaultRealmPath error:nil];
        [RLMRealm setEncryptionKey:data forRealmsAtPath:defaultRealmPath];
    }

    @autoreleasepool {
        RLMRealm *realmv1 = [RLMRealm realmWithPath:[RLMRealm defaultRealmPath] encryptionKey:data readOnly:YES error:&error];
        UILabel *numView = [[UILabel alloc] init];
        [numView setFont:[UIFont systemFontOfSize:15]];
        numView.textAlignment=NSTextAlignmentLeft;
        numView.numberOfLines=100;
        [numView setBackgroundColor:[UIColor clearColor]];
        [numView setTextColor:UIColorFromRGB(0x000000)];
        [self.view addSubview:numView];
        [numView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.edges.equalTo(self.view);
        }];

        if ([error code]!=0) {
            numView.text = [NSString stringWithFormat:@"%@+++",[error description]];
        }else{
            RLMResults *dogs = [ZtyHomeWorkContent allObjects];
            numView.text = [NSString stringWithFormat:@"%@----",dogs];
            NSLog(@"%@",dogs);
        }
    }

**Comment by codesourse** [comment]
i use your demo to encryption in release environment,meetting the problem too.
https://github.com/realm/realm-cocoa/blob/master/examples/ios/objc/Encryption/LabelViewController.m

**Comment by codesourse** [comment]
Have you tested these processes!

**Comment by TimOliver** [comment]
Hrmm, if it's saying you need to perform a migration, then your model files between the Android and iOS version aren't matching. You'll need to either double check them, or perform a migration on the iOS side (https://realm.io/docs/objc/latest/#performing-a-migration)

As to encryption, it's should be working just fine in the sample code. Make sure to have a look at the documentation article on encryption to make sure you're using the right methods and ordering to set they key (https://realm.io/docs/objc/latest/#encryption).

Hope that helps!

**Comment by codesourse** [comment]
Thank you,i have solve this problem.
I feel sorry for what i said.
Mainly if encryption cannot solve, my project will be failed.
Please amend the getKey method in the demo.

- (NSData *)getKey:(NSString *)keyString {
    // Identifier for our keychain entry - should be unique for your application
    static const uint8_t kKeychainIdentifier[] = "io.Realm.EncryptionExampleKey";
    NSData *tag = [[NSData alloc] initWithBytesNoCopy:(void *)kKeychainIdentifier
                                               length:sizeof(kKeychainIdentifier)
                                         freeWhenDone:NO];
    
    // First check in the keychain for an existing key
    NSDictionary *query = @{(__bridge id)kSecClass: (__bridge id)kSecClassKey,
                            (__bridge id)kSecAttrApplicationTag: tag,
                            (__bridge id)kSecAttrKeySizeInBits: @512,
                            (__bridge id)kSecReturnData: @YES};
    
    CFTypeRef dataRef = NULL;
    OSStatus status = SecItemCopyMatching((__bridge CFDictionaryRef)query, &dataRef);
    if (status == errSecSuccess) {
        return (__bridge NSData *)dataRef;
    }
    // No pre-existing key from this application, so generate a new one
    const char *buffer=[keyString UTF8String];
    NSData *keyData = [[NSData alloc] initWithBytes:buffer length:(int)strlen(buffer)];
    NSLog(@"%@=====%lu",keyData,strlen(buffer));
    // Store the key in the keychain
    query = @{(__bridge id)kSecClass: (__bridge id)kSecClassKey,
              (__bridge id)kSecAttrApplicationTag: tag,
              (__bridge id)kSecAttrKeySizeInBits: @512,
              (__bridge id)kSecValueData: keyData};
    status = SecItemAdd((__bridge CFDictionaryRef)query, NULL);
    NSAssert(status == errSecSuccess, @"Failed to insert new key in the keychain");
    return keyData;
}
