### ISSUE TITLE
Create self relationships in realm [Objective-c]

### ISSUE THREAD

**Issue by jplazcano87** [realm/realm-cocoa#2186]
i have this model but when i try to do a RLMArray for "Test Model" it says "Cannot find protocol declaration for "TestModel""
```
#import <Realm/Realm.h>
#import "QuestionModel.h"


@interface TestModel : RLMObject

@property NSDate *timestamp;
@property NSString *repetition_id;
@property RLMArray<TestModel> *tests;   //this array has problems
@property RLMArray<TestModel> *repetitionsTests;  //this array has problems
@property NSString *type;
@property int order;
@property NSString *execution_uuid;
@property NSString *uuid;
@property NSString *title;

@property RLMArray<QuestionModel> *questions;

@end

RLM_ARRAY_TYPE(TestModel)
```

i do the same thing in java / android and is working fine, in objective c i can´t create a RLMArray from the same class, i need to create a typed collection from the "self" class

**Comment by segiddins** [comment]
@jplazcano87 you need to do `RLM_ARRAY_TYPE(TestModel)` before your `TestModel` interface.

**Comment by jplazcano87** [comment]
Thanks is working!
