### ISSUE TITLE
Updating Cloned object issue

### ISSUE THREAD

**Issue by jplazcano87** [realm/realm-cocoa#2190]
i have cloned a RealmObject with primary key and it has been created fine, but when i update
a children from the cloned object, the original children is also updated, how can i update only cloned object?

this is the cloning code
```
 Model *originalModel =[[Model allObjects] firstObject]; //original model
 
 Model *cloneModel = [[Model alloc] initWithValue:originalModel]; //clone model
 
 RLMRealm *realm = [RLMRealm defaultRealm];

 
 [realm beginWriteTransaction];
 cloneActivity.uuid =  @"new uuid";
 
 for (ScreenModel *page in cloneActivity.screens) {
  //this line is also updating the original object
  page.execution_uuid = @"new uuid";

  }
  [ActivityTreeModel createInRealm:realm withValue:cloneModel];
  [realm commitWriteTransaction];
  
```

**Comment by bigfish24** [comment]
I am having trouble understanding your code. Can you provide the object schemas?

**Comment by jplazcano87** [comment]
sure here this is my model as i said before, i create the first one, then the second, when i update the second one , the first is also been updated

main model 
```
#import <Realm/Realm.h>
#import "ScreenModel.h"


@interface Model : RLMObject


@property NSString *uuid;
@property NSString *execution_uuid;
@property NSString *name;
@property RLMArray<ScreenModel> *screens;

@end

RLM_ARRAY_TYPE(ActivityTreeModel)
```
childen model

```
#import <Realm/Realm.h>
#import "QuestionModel.h"

RLM_ARRAY_TYPE(ScreenModel)
@interface ScreenModel : RLMObject

@property RLMArray<ScreenModel> *screens;
@property RLMArray<ScreenModel> *repetitionsResults;

@property NSString *execution_uuid;
@property NSString *uuid;
@property NSString *title;

@property BOOL finished;


@end
```

**Comment by bigfish24** [comment]
No problem! I understand what you are asking now. The issue is that Realm doesn't support making copies of linked objects yet. This PR shows the progress to implement this: https://github.com/realm/realm-cocoa/pull/2043

So the objects that are linked are still pointing to the original children.

To fix in the short term you will need to manually copy the properties and create new children in the process.

**Comment by jplazcano87** [comment]
ok, i'll do a manual copy of the children 
thanks for the help, keep on the good work

**Comment by bigfish24** [comment]
Happy to help and glad you are enjoying Realm!
