### ISSUE TITLE
override className doesn't work for initialization in Swift

### ISSUE THREAD

**Issue by codywinton** [realm/realm-cocoa#2194]
I'm using `RealmSwift` in my project. I have an object subclass named `RLMDocument`:

    class RLMDocument: Object {
    
        dynamic var barcodeData = ""
        dynamic var barcodeType = ""

        override class func className() -> String {
            return "Document"
        }
    }

I want Realm to save the object in the database as `Document`. However, when I initialize the `RLMDocument()` object, it returns an object with a class of `RLMDocument`, not `Document`. What am I doing wrong?

**Comment by jpsim** [comment]
Realm requires `className` to be the same name as the actual class name, and will enforce this by changing the implementation of the method, although that's mostly done for performance reasons. So overriding this class method isn't encouraged or supported.

What do you wish to achieve by overriding `className`? If for some reason you need to prefix your Realm classes with `RLM`, but you want some other way to get an unprefixed custom class name for other parts of your code, you should implement a different class method (`unprefixedClassName()` maybe?).

**Comment by codywinton** [comment]
It's rather complicated why I need the RLM prefix for my subclasses, but I was wondering if I could just initialize the object with a custom `ObjectSchema` and set the class name myself?

**Comment by codywinton** [comment]
@jpsim - What are your thoughts?

**Comment by jpsim** [comment]
> I was wondering if I could just initialize the object with a custom `ObjectSchema` and set the class name myself?

I strongly discourage any modifications to how Realm works internally, including changing class names at runtime.

I'd love to hear why you need to prefix your classes with `RLM` yet cannot have its class name be the same. Maybe your end goal can be achieved through simpler ways.

**Comment by codywinton** [comment]
I actually was able to resolve the issue and remove the RLM prefix. Thanks!

**Comment by codywinton** [comment]
However, I do believe that adding the ability to change a class name would be a wise idea.  For example, if you are using Parse.com for online storage as well realm for local storage, it would be very useful to have `RLMDocument` and `PFDocument` classes but store them in the server and local database as merely `Document`. This is possible with PFObjects via. Parse

**Comment by jpsim** [comment]
I'm glad you were able to resolve this issue. It's unlikely that we'll support decoupling the mode name from its class name in the future, but I believe this would be an appropriate use case for a dynamic Realm API.
