### ISSUE TITLE
Swift 2: Framework not found

### ISSUE THREAD

**Issue by Neilq5** [realm/realm-cocoa#2196]
I've recently downloaded Realm, trying to add it to my project.  I've followed the specific instructions for installing for Swift 2 using the source.  I'm running on xCode 7, El Capitan and tried deploying to both iOS 8.4 and iOS 9.

When attempting to build, either on device or simulator I'm getting;

`ld: framework not found RealmSwift`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I've attempted cleaning the project and the build, deleting the DerivedData Directory, tried importing the framework into a new project and rebooting, none of which are solving the problem.

Any suggestion for a fix?

I would try CocoaPods but I haven't reinstalled it since I got El Capitan.  If needs be I'll try it, was just hoping to get it working this way for now.

**Comment by segiddins** [comment]
@Neilq5 are you sure that the framework search paths include the path the the directory that contains the realm and RealmSwift frameworks?

**Comment by Neilq5** [comment]
I tried the search paths yesterday with no luck.  I reinstalled Xcode the that problem has seemingly disappeared.  Moving on to a new problem.
If I import Realm and build, I'm getting errors anywhere I force a downcast to string;

`Cannot assign a value of type 'String' to a value of type 'String'

If I remove the import, it disappears.  Tried cleaning and stuff again with no difference.

**Comment by segiddins** [comment]
Hm, that is a strange error indeed... Would you mind sharing a project with us, either here or privately at help@realm.io, so we can take a look? Thanks!

**Comment by Neilq5** [comment]
Thanks, just sent it in an email.

**Comment by segiddins** [comment]
This is likely not a Realm issue, but keep us posted, @Neilq5 !
