### ISSUE TITLE
Unable to debug swift project with Realm-swift-2.0 branch

### ISSUE THREAD

**Issue by voidref** [realm/realm-cocoa#2197]
When I attempt to debug a project built with the swift-2.0 branch, I get the following in the console:

```
warning: Swift error in module <my app>: 
    Swift had fatal errors constructing the ast context for this module: <built-in>:3:2: error: module 'Realm' was built in directory '/Realm.framework' but now resides in directory './Realm.framework'
#define __clang_major__ 7
 ^
missing required modules: 'Realm.Private', 'Realm'
Debug info from this module will be unavailable in the debugger.

warning: Swift error in module RealmSwift: 
    Swift had fatal errors constructing the ast context for this module: missing required modules: 'Realm.Private', 'Realm'
Debug info from this module will be unavailable in the debugger.
```

I have added both `Realm` and `RealmSwift` frameworks to the app. Had to remove the build script step as it could not find the path that was provided. Are there updated instructions for this branch?

**Comment by marchyman** [comment]
See  issue [2135](https://github.com/realm/realm-cocoa/issues/2135) which is the same problem.   It was recently closed as a Swift/lldb problem, not a realm problem.

**Comment by voidref** [comment]
Dupe of #2139
