### ISSUE TITLE
Failure to create new project in XCode 7.0 beta 3 using Realm for Swift 2.0

### ISSUE THREAD

**Issue by thabz** [realm/realm-cocoa#2204]
I've followed the instructions on https://realm.io/docs/swift/latest/#swift-20 for Swift 2.0. I'm not using CocoaPods.

I've dragged the two freshly built frameworks into the project as described, but I consistently get the error *No such module 'RealmSwift'* in my `import RealmSwift` line.

I can compile and run the examples in the swift-2.0 branch just fine, so I'm wondering if you've left something out in your Installation (Swift 2.0) docs? 

The last commit on swift-2.0 branch is currently 2efcfdc26ac16aecbef2cbd35630225eb91efda1.

**Comment by thabz** [comment]
Just found out that it works if I add the parent path of the .framework files to the "Frameworks Search Paths" in my target's Build Settings. I got the inspiration from step 3 in your "Installation (Swift 1.2)" section on https://realm.io/docs/swift/latest/#swift-20. 

Maybe the same step or similar should be added to the Swift 2.0 section too?

**Comment by mrackwitz** [comment]
Good catch! Yes, it should be added there too. I took care of it. The change will be soon online.
But did the failing build happen for your test target or did that occur for your main target (app/framework/cli)? The path should be always present for all targets, which link to the frameworks. But Xcode is or at least used to be able to add the path itself for the targets, which you directly add in the "Embedded Binaries" section.

**Comment by thabz** [comment]
Cool. Thanks for the impressively quick response. 

It was my main app target that failed to build. Now I know what to do when I get to working on my test target.
