### ISSUE TITLE
Can i get any help in a realm query ?

### ISSUE THREAD

**Issue by tariq235** [realm/realm-cocoa#2211]
I have multi day events stored in realm database.

In my database i have two columns i.e. startDate and endDate and if user pressed any date in UI like 16July 2015 then it should fetch all events which fall between startDate and endDate.

Earlier I wrote a predicate for fetching staring events:

```
[NSPredicate predicateWithFormat:[NSString stringWithFormat:@"%@ >= %%@ AND %@ < %%@", @"startTime", @"endTime"], date, [date dateForNextDay]]
```

But above query will not work if given date is not an event's starting date.

**Comment by segiddins** [comment]
@tariq235 can you be a bit more specific how things are not working?

**Comment by tariq235** [comment]
@segiddins For example: If i have a conference date as 7/13 - 7/16 and given date is 7/14 then conference event should be able to fetch using predicate. My old query will only work on 7/13. It should fetch that event on given dates - 7/13, 7/14, 7/15, 7/16 and if given date is 7/17 then nil will be returned.

**Comment by segiddins** [comment]
Ah OK, I think I see the issue now!

Can you try changing your predicate to the following:

```objc
[NSPredicate predicateWithFormat:@"%K >= %@ AND %@ < %K", @"startTime", date, @"endTime", [date dateForNextDay]]
```

**Comment by tariq235** [comment]
@segiddins  Something wrong with predicate. What is K ?
I copy pasted with my code and i got this crash on predicate:

[__NSTaggedDate rangeOfString:]: unrecognized selector sent to instance 0xe41bb582fa800000

**Comment by segiddins** [comment]
Ah totally my bad, I ordered them wrong:

```objc
[NSPredicate predicateWithFormat:@"%K >= %@ AND %@ < %K", @"startTime", date, [date dateForNextDay], @"endTime"]
```

As explained in https://realm.io/news/nspredicate-cheatsheet/, `%K` is the proper way to specify a keypath outside of the format string itself.

**Comment by tariq235** [comment]
Just tried its returning all future events irrespective of endDate

po date
2015-05-12 18:30:00 +0000

(lldb) po predicate
startTime >= CAST(453148200.000000, "NSDate") AND CAST(453234600.000000, "NSDate") < endTime

And RLMResults returned all future events
<img width="373" alt="screen shot 2015-07-16 at 8 20 45 pm" src="https://cloud.githubusercontent.com/assets/349211/8726501/36a43d6e-2bf8-11e5-8056-8fd7b1b65044.png">

**Comment by segiddins** [comment]
```objc
[NSPredicate predicateWithFormat:@"%K >= %@ AND %@ > %K", @"startTime", date, [date dateForNextDay], @"endTime"]
```

The last comparison needed to be flipped -- greater than versus less than.

**Comment by tariq235** [comment]
Optimized a bit but still not getting accurate data. Let me debug and analyze the data with your new predicate.

**Comment by tariq235** [comment]
So as per attachment I can see an event on 07July - 09 July but RLMResults returned 0 output.

(lldb) po date
2015-07-07 18:30:00 +0000

(lldb) po [date dateForNextDay]
2015-07-08 18:30:00 +0000

(lldb) po results
RLMResults <0x7f92c3343e30> (

)

(lldb) po predicate
startTime >= CAST(457986600.000000, "NSDate") AND CAST(458073000.000000, "NSDate") > endTime
<img width="397" alt="screen shot 2015-07-16 at 9 10 48 pm" src="https://cloud.githubusercontent.com/assets/349211/8727791/4af3a0d2-2bff-11e5-94df-0c8d05b5ab35.png">

Code used:
```
        RLMRealm *realm = [RLMRealm defaultRealm];
        
        NSPredicate *predicate;
        predicate =  [NSPredicate predicateWithFormat:@"%K >= %@ AND %@ > %K", @"startTime", date, [date dateForNextDay], @"endTime"]
;
        
        RLMResults *results = [IVEvent objectsInRealm:realm withPredicate:predicate];
```

**Comment by segiddins** [comment]
Could you help me understand exactly what the query is supposed to be querying?

**Comment by tariq235** [comment]
I have solved with this 
[NSPredicate predicateWithFormat:[NSString stringWithFormat:@"%@ < %%@ AND %@ >= %%@", IVEventStartTimeKey, IVEventEndTimeKey], [date dateForNextDay], date]

But for very large set of data I think realm is fetching wrong data. I need some more time to prepare concrete results.

**Comment by segiddins** [comment]
@tariq235 I'm going to close the issue for now, but feel free to reopen it if you can come up with an example where Realm is returning the wrong results. Thanks!
