### ISSUE TITLE
Support for mixed objc/swift projects

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#2214]
For external components, the current plan is to use the dynamic api. Since this lives in objc, we need a way to re-expose `RLMResults` or `RLMObjects` used internally by the component as swift objects.

**Comment by jpsim** [comment]
I don't think this is the appropriate approach. Wouldn't offering a dynamic Swift API solve this problem in a more elegant way?

**Comment by bigfish24** [comment]
This PR: https://github.com/realm/realm-cocoa/pull/2213 introduces dynamic api methods in Swift. I will close this for now.
