### ISSUE TITLE
Parse Objective Property is wrong

### ISSUE THREAD

**Issue by PhilipBale** [realm/realm-cocoa#2217]
I'm having a problem where Realm is trying to parse a long in RLMProperty's 
"- (bool)parseObjcProperty:(objc_property_t)property", but _objRawType is being set to '^q' instead of 'q'.  Has anyone else seen this?

**Comment by segiddins** [comment]
@PhilipBale I've not seen that happen before... can you share your class definitions, (or even better, an Xcode project) that demonstrates this? Thanks!

**Comment by bdash** [comment]
A type of `^q` would indicate that the property is declared as `long *` rather than `long`.

**Comment by PhilipBale** [comment]
Missed that darn star... thanks!
