### ISSUE TITLE
Writes section improvements

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#2228]
- Add section for Partial updates w/ nsdictionary
- Use bold titles (h4)

**Comment by jpsim** [comment]
Done!

**Comment by schickling** [comment]
@jpsim could you quickly explain how partial updates using dictionaries can be made?

**Comment by jpsim** [comment]
To partially update an object using a dictionary, only include the keys for the values you wish to update (and the primary key). From our docs ([Updating Objects With Primary Keys](https://realm.io/docs/objc/latest/#updating-objects-with-primary-keys)):

> You can also partially update objects with primary keys by passing the subset of
values you wish to update, along with the primary key:

> ```objc
// Assuming a "Book" with a primary key of `1` already exists.
[realm beginWriteTransaction];
[Book createOrUpdateInRealm:realm withValue:@{@"id": @1, @"price": @9000.0f}];
// the book's `title` property will remain unchanged.
[realm commitWriteTransaction];
```
