### ISSUE TITLE
Queries section improvements

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#2229]
Change current names
- Remove Retrieving Objects by Type h3
- Remove everything in that code block besides the line that shows how to return all objects

New top level names	
- Filtering
  - Code samples w/ each predicate w/ comments
  - Come up with 10 companies, 10 people, 10 dogs to consistently use for docs and testing (eventually monkeys and bananas - zoo theme)
  - Potential interactive predicates (this could be its own page/tutorial)
- Sorting
- Chaining

**Comment by jpsim** [comment]
Done in https://github.com/realm/realm.io/pull/802.
