### ISSUE TITLE
Simplify passing objects between threads

### ISSUE THREAD

**Issue by CraigSiemens** [realm/realm-cocoa#2230]
As far as I know, the only way to pass an object to another thread is like this.

```objc
MyObject *object = ...
NSInteger identifier = object.identifier;
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    MyObject *objectToUpdate = [MyObject objectForPrimaryKey:@(identifier)];
    // update object
});
```

There are a couple problems with this.
- It has to go from an Object to Unique Identifier back to an Object since `object.identifier` can't be called on another thread. It would be nice to just go from Object to Object.
- You need some method of uniquely identifying objects, either a primary key or using some combination of properties which is not possible for every data set.

## Possible Solution
Add a method to `RLMObject` called `objectForCurrentThread` or just `forCurrentThread`
- This method would return an instance of the Object that is the same as the receiver but can be accessed/modified on the current thread. As far as I can tell, it looks like every row in Realm has an index that can be used to uniquely identify it
- This would function similarly to [`- [NSManagedObject MR_inContext:]` in MagicalRecord](https://github.com/magicalpanda/MagicalRecord/blob/master/MagicalRecord/Categories/NSManagedObject/NSManagedObject+MagicalRecord.m#L284)

```objc
MyObject *object = ...
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    MyObject *objectToUpdate = [object objectForCurrentThread];
    // update object
});
```

**Comment by segiddins** [comment]
@CraigSiemens I've actually been working on implementing a way to pass `RLMResult`s between threads, which is being tracked by https://github.com/realm/realm-cocoa/issues/1097, which I believe should cover the vast majority of cross-thread usage

**Comment by jpsim** [comment]
@CraigSiemens since #1097 will actually avoid re-fetching data from the disk in most cases, it's a preferable solution to something like `MR_inContext:`. I'm therefore closing this issue.
