### ISSUE TITLE
Realms section improvements

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#2231]
Will be named Realm Configuration (once we have it)

Move "Using a Realm Across Threads" item to a top level item within the new Threading section
- Finding a realm file, make it doc specific how to find it

**Comment by TimOliver** [comment]
This looks like it's already done. Is it alright to close this issue?

/cc @yoshyosh @jpsim

**Comment by jpsim** [comment]
Yes, this has been done for a while. We now have a top-level "Threading" section with a "Using a Realm Across Threads" subsection, as well as a "Realm Configuration" subsection of "Realms".
