### ISSUE TITLE
FAQ & Limitations section

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#2239]
- Update faq (memory limitations)
- Remove tightdb (in a month or 2)

**Comment by TimOliver** [comment]
What are the specific details behind the memory limitations?

References to TightDB have been completely removed from the code now (Except for the change log), so it might be worth removing that particular section now rather than later.

**Comment by jpsim** [comment]
I don't recall what we wanted to do about the memory limitations FAQ entry. Closing this issue as the other half is done.
