### ISSUE TITLE
Cocoapod for Swift 2 fails to download core dependency

### ISSUE THREAD

**Issue by jlaws** [realm/realm-cocoa#2240]
This is the same issue from #2102.

> [!] /bin/bash -c
> set -e
> sh build.sh cocoapods-setup
> core is not a symlink. Deleting...
> Downloading dependency: core 0.91.2

I am running Xcode 7 beta 3 and cocoapods 0.38.0.beta.2.

I tried clearing my cocoapods cache, removing the temp files created during the install in /var/folders/...., and even running the build.sh script directly from the cocoapod cache.

Anyone know whats going on?

**Comment by segiddins** [comment]
@jlaws could you please share the entire output of `pod install --verbose`? Thanks!

**Comment by jlaws** [comment]
Uninstalled cocoapods and went back to 0.37.2 after clearing the entire cache and even reinstalling ruby.  Still get the same error.  Here is the output for `pod install --verbose`
```
$ pod install --verbose
  Preparing

Analyzing dependencies

Updating spec repositories
Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.

CocoaPods 0.38.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.


Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-server`: (``)

Fetching external sources
-> Pre-downloading: `Realm` from `git@github.com:realm/realm-cocoa.git`, branch `swift-2.0`
 > Git download
 > Git download
     $ /usr/bin/git clone git@github.com:realm/realm-cocoa.git /var/folders/jx/92fq5k5j3sqckfzxmj6lpjmc0000gn/T/d20150718-7841-1q4ars5 --single-branch --depth 1
     --branch swift-2.0
     Cloning into '/var/folders/jx/92fq5k5j3sqckfzxmj6lpjmc0000gn/T/d20150718-7841-1q4ars5'...
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: core 0.91.2
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...

Downloading dependency: core 0.91.2


/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:70:in `execute_command'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:64:in `block (2 levels) in run_prepare_command'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:154:in `copy_and_clean'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:111:in `block (2 levels) in uncached_pod'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:109:in `each'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:109:in `block in uncached_pod'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:133:in `call'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:133:in `in_tmpdir'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:106:in `uncached_pod'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:34:in `download'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/abstract_external_source.rb:108:in `block in pre_download'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/abstract_external_source.rb:106:in `pre_download'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:358:in `fetch_external_source'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:335:in `block (2 levels) in fetch_external_sources'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:334:in `each'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:334:in `block in fetch_external_sources'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:333:in `fetch_external_sources'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:62:in `analyze'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/jlaws/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-0.8.2/lib/claide/command.rb:312:in `run'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Users/jlaws/.gem/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/Users/jlaws/.gem/bin/pod:23:in `load'
/Users/jlaws/.gem/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Can you try installing again? https://github.com/realm/realm-cocoa/commit/c430e8a9d4630373ff0e32c13aa8f0fedba14ff1 should fix things!

**Comment by jlaws** [comment]
awesome, works great now, thanks @segiddins !

**Comment by samiq** [comment]
Hi guys, I'm getting the same issue here:
```
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.92.1.1
Downloading core failed. Please try again once you have an Internet connection.
```
while doing update on the pods

```
$ /usr/bin/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/85/bp09qzc17m58ckcb1yq5p6lr0000gn/T/d20150901-11294-qoq5fx
     --single-branch --depth 1 --branch v0.95.0
     Cloning into '/var/folders/85/bp09qzc17m58ckcb1yq5p6lr0000gn/T/d20150901-11294-qoq5fx'...
     Note: checking out 'fafb219f2b1c633cf27e8e8227058384b36d83c7'.

```

any suggestions?

**Comment by jpsim** [comment]
We've had issues for the last ~2 hours with assets stored on static.realm.io, but those should now be resolved. See https://github.com/realm/realm-cocoa/issues/2446#issuecomment-136813872 for more information.

**Comment by samiq** [comment]
yeap, confirmed is all good now, thanks for the quick reply :)

**Comment by aelam** [comment]
I've got stuck at  ` Downloading dependency: core 1.3.1` too.

pod install --no-repo-update --verbose         
  Preparing
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0`

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-PackageCLI`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-PackageDecode`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-PackageCLITest`: (``)

Finding Podfile changes
  - Expecta
  - MSPackageManager
  - Specta

Fetching external sources
-> Fetching podspec for `MSPackageManager` from `../`

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A Realm
  M MSPackageManager
  - AFNetworking
  - Expecta
  - Specta

Downloading dependencies

-> Using AFNetworking (3.1.0)

-> Using Expecta (1.0.5)

-> Installing MSPackageManager 0.1.0 (was 0.1.0)

-> Installing Realm (1.0.2)
 > Git download
 > Git download
     $ /usr/local/opt/git/libexec/git-core/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/zp/g4lt8dzj4p3b1tb8jwl702m40000gp/T/d20160722-69260-j26dzn --single-branch --depth
     1 --branch v1.0.2
     Cloning into '/var/folders/zp/g4lt8dzj4p3b1tb8jwl702m40000gp/T/d20160722-69260-j26dzn'...
     Note: checking out '10ef693b9935694f58f49b264008f6cf3ccccf61'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: core 1.3.1

**Comment by bdash** [comment]
@aelam, Please file a new issue rather than commenting on an issue that's been closed for over a year.
