### ISSUE TITLE
RLMException: Binary too big

### ISSUE THREAD

**Issue by xnth97** [realm/realm-cocoa#2241]
Hey all,

The RLMObject that I use Realm to storage has a NSData property, which was archived from an NSAttributedString with some images as NSTextAttachment. I used some code like `[NSKeyedArchiver archiveDataWithRootObject: textView.attributedText];` to archive the attributed string and I got `*** Terminating app due to uncaught exception 'RLMException', reason: 'Binary too big'` while committing the write transaction. 

I'm wondering what's the correct way to save big binary data (i.e, images) in realm? Is there a size limit for RLMObjects? Thanks for help.

**Comment by segiddins** [comment]
@xnth97 the maximum size for any single `NSData` property is 16 MB, as documented at https://realm.io/docs/objc/latest/#current-limitations.

**Comment by xnth97** [comment]
@segiddins Thanks a lot. That section is not included in official chinese documents. Is there any place to contribute some translation?

**Comment by segiddins** [comment]
I don't know about the translations, but I'll ping @yoshyosh on that.

**Comment by yoshyosh** [comment]
@tebica is the best person for this
