### ISSUE TITLE
[RLMArray][List] Implement Move method

### ISSUE THREAD

**Issue by astigsen** [realm/realm-cocoa#2242]
To support drag'n'drop reordering in lists we need a move method.

This is needed by sync as a move is semantically very different from a delete and insert. It is also important to avoid triggering cascading deletes when we start supporting that.
```obj-c
- (void)moveObjectFromIndex:(NSUInteger)from toIndex:(NSUInteger)to;
```

**Comment by segiddins** [comment]
Does list_list already implement the necessary methods?

**Comment by astigsen** [comment]
​The` LinkView` class in Core already has a `move()` method. I guess it
just have to be exposed at the binding level.
