### ISSUE TITLE
Cocoapods crash when installing realm

### ISSUE THREAD

**Issue by DennisGoldfinger** [realm/realm-cocoa#2243]
After adding the code shown in the docs to my podfile and running pod install, I get the following:

<pre>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:130: warning: Insecure world writable dir /usr in PATH, mode 040777
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `Realm` from `https://github.com/realm/realm-cocoa.git`, branch `swift-2.0`
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.91.2
mv: rename ./.git//Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description to ./.git/description: No such file or directory
</pre>

If I had to guess, I would say that the issue is in the build script where it is trying to rename a file that does not exist (./.git//Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description).

I have been all over the internet looking for a solution and have tried everything in the following links with no success:

https://github.com/realm/realm-cocoa/issues/1022
https://github.com/realm/realm-cocoa/issues/1520
https://github.com/CocoaPods/CocoaPods/issues/2598
https://github.com/realm/realm-cocoa/issues/908
https://github.com/realm/realm-cocoa/issues/2102

Realm version: v0.93.2
XCode version: 7.0 beta (7A120f)

**Comment by segiddins** [comment]
Hm, that's very very strong that it seems to think there's a symlink from `./.git/description` to `/Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description`, and I can't reproduce that locally...

**Comment by segiddins** [comment]
What version of git do you have? Do you have any weird git setup on your local machine?

**Comment by DennisGoldfinger** [comment]
Git version 2.1.3.36.g8e36a6d and honestly, it's possible. I've had to tweak things before when coming up on errors like this with no solution. Although I can't say for sure that I've tweaked git itself.

**Comment by DennisGoldfinger** [comment]
Also, I don't think the issue is so much that there is a symlink there as it is that the script is trying to rename a file that doesn't exist. Let me specify:

The script calls:

<code>mv ./.git//Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description ./.git/description</code>

The first clause in the mv command is what is breaking. It calls

<code>./.git//Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description</code>

When it should (or could?) be calling

<code>/Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description</code>

I'm not sure where it's getting that first file path. If it were to call it with the file path I just wrote, it would get that the file exists and nothing would actually change (and the script would continue).

**Comment by segiddins** [comment]
Right, but it's calling `mv` in the first place because `find . -type l` has returned a symlink. I can't see that symlink locally, nor can I imaging how anything related to GitHub for Mac has gotten into the repo, so I'm at a loss as to why this is happening for you (especially since I can't reproduce it myself)

**Comment by DennisGoldfinger** [comment]
Yeah I have no idea either, let me know if I can help in any way. By the way, this is what find . -type l returns for me locally:

<pre>
./.git/description
./.git/hooks/applypatch-msg.sample
./.git/hooks/commit-msg.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/pre-commit.sample
./.git/hooks/pre-push.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/update.sample
./.git/info/exclude
</pre>

**Comment by segiddins** [comment]
That's ... really strange. And would certainly explain the issue your seeing. I suppose it makes no sense to muck around with stuff in the `.git` dir, so I'll exclude that from the `find`

**Comment by adad184** [comment]
same problem

**Comment by kordziu** [comment]
Since today we have also experiencing issues with swift-2.0 branch and cocoa pods. Once installed/updated with pods RealmSwift module is not being visible during build process.

**Comment by konradowy** [comment]
The same here. I'm not able to build project. On Friday worked perfect, since today after pod update (and also upgrading cocoa pods to ver 0.38.0) stopped working. The error shows: "No such module 'RealmSwift'".

**Comment by fewspider** [comment]
same problem today.

**Comment by jpsim** [comment]
@fewspider please send us steps to reproduce and we'll reopen this issue if we missed something.

**Comment by fewspider** [comment]
@jpsim It was solved https://github.com/realm/realm-cocoa/issues/2312 ,thanks again.
