### ISSUE TITLE
Highlight the fact that every realm will have the same schema regardless of whether any objects have been saved.

### ISSUE THREAD

**Issue by maciejtrybilo** [realm/realm-cocoa#2245]
Apologies if it's just me being special, but I've nearly shipped an update that would crash on startup due to not understanding the schema behaviour across several realms. It would also only crash if the previous version had been launched more than once, so standard upgrade test hadn't caught that out.

Apparently when you have more than one realm object defined and more than one realm, all of the realms will share the schema that will include all objects.Thus, it's crucial to perform the same migration for all realms, even if you don't intend to store the migrated object type in all realms.

I think this could be made more clear in the docs.

**Comment by jpsim** [comment]
Sorry for the late reply, @maciejtrybilo. We agree this should be better explained in the docs and @TimOliver is working on improving that right now. We'll close this issue once we've updated our docs accordingly.

**Comment by segiddins** [comment]
Obsoleted by https://github.com/realm/realm-cocoa/pull/2401?

**Comment by jpsim** [comment]
#2401 is now merged, so this should not longer be a problem.
