### ISSUE TITLE
plain sql query

### ISSUE THREAD

**Issue by ehsaanwelcome** [realm/realm-cocoa#2247]
Hi Realm team,
I would love to know that is there a way to execute simple sql ('select * from table .....')?
Sometimes, queries are complicated and writing in plain sql is better.
Thanks

**Comment by mrackwitz** [comment]
No, Realm doesn't offer at the moment a text based query language and there are not yet concrete plans for that. Where exactly do you see the advantage and where would you use it?

**Comment by ehsaanwelcome** [comment]
Thanks for replying.
Actually, i was looking for a way to to *limit *query results with
*offset/page*.
Is there a way to fetch 100 results and skip first 100 results just like
paging?
Thanks.

On Mon, Jul 20, 2015 at 4:54 PM, Marius Rackwitz <notifications@github.com>
wrote:

> No, Realm doesn't offer at the moment a text based query language and
> there are not yet concrete plans for that. Where exactly do you see the
> advantage and where would you use it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2247#issuecomment-122910013>.
>



-- 
Muhammad Ahsan Ashraf
MS ITISInternet Technologies & Information System
Sr. Software Engineer
B.Sc. Computer Science

**Comment by jpsim** [comment]
Paging in Realm is largely not needed because queries in Realm don't actually fetch data from disk. So to avoid fetching the first 100 results, just read `Results[start..<end]` and Realm won't fetch `< start` or `>= end`.

**Comment by jpsim** [comment]
@ehsaanwelcome I've created #2264 to track adding more explicit information to our documentation about how to "page" data in Realm. Let us know if you have any further questions!
