### ISSUE TITLE
Cocoa pods and Swift 2.0 - module not found

### ISSUE THREAD

**Issue by kordziu** [realm/realm-cocoa#2250]
Hi there. Shortly:

0. Xcode 7 beta 3

1. Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
```
2. pod install (with Cocoapods 0.38)

3. import RealmSwift anywhere in project's code

4. Result: 

<img width="864" alt="zrzut ekranu 2015-07-20 o 21 06 58" src="https://cloud.githubusercontent.com/assets/3457792/8784804/e3bec0f4-2f23-11e5-856b-bc335e250882.png">

This started happening after weekend. I can send you test project I have created to reproduce this issue.

very best!

**Comment by d6u** [comment]
Same issue here with fresh Xcode 7 beta 3 project.

**Comment by kordziu** [comment]
Just one addition. Unlike before weekend, now RealmSwift group in Pods project does not contain any single file.

**Comment by segiddins** [comment]
Thanks for the issue! I'll look into this momentarily.

**Comment by segiddins** [comment]
@kordziu @d6u give it another shot, I should've just fixed this

**Comment by segiddins** [comment]
ah actually there's another issue, hold on a moment

**Comment by d6u** [comment]
:+1:

**Comment by kordziu** [comment]
Thanks a lot!
