### ISSUE TITLE
installing realm from carthage not producing RealmSwift.framework only Realm.framework

### ISSUE THREAD

**Issue by edwardIshaq** [realm/realm-cocoa#2253]

**Comment by edwardIshaq** [comment]
Following the instruction on https://realm.io/docs/swift/latest installation via Carthage. I"m assuming i should be getting Realm.framework & RealmSwift.framework after following step 1 & 2. but for some reason I only get Realm.framework Any idea why would realmSwift be missing ?

**Comment by segiddins** [comment]
@edwardIshaq can you share the contents of your Cartfile, and the version of Carthage you're running? Thanks!

**Comment by edwardIshaq** [comment]
Hi @segiddins 
Please find it below:
$ cat Cartfile
github "realm/realm-cocoa"
$ carthage version
0.5.2

**Comment by segiddins** [comment]
@edwardIshaq can you try updating to Carthage 0.7.5 or later, since Realm relies on more recent Carthage features? Thanks!

**Comment by edwardIshaq** [comment]
@segiddins That was the issue. Thanks for pointing it out for me.
