### ISSUE TITLE
Can't open Swift realm databases with browser

### ISSUE THREAD

**Issue by mark-anders** [realm/realm-cocoa#2272]
I'm just getting started with Realm swift using the swift-2.0 branch. I've both successfully written a program that can write to and read from a database as well as run the TableView sample.  In both cases, when I attempt to open the default.realm file, which is located in my simulator directory, I get an "Invalid database" error.

Is this supposed to work?

**Comment by segiddins** [comment]
@mark-anders sorry to year you're having trouble with the browser! If you could open up an issue over on the browser's repo (https://github.com/realm/realm-browser-osx) that includes a Realm file the team can use to debug, that would be awesome, thanks!

**Comment by mark-anders** [comment]
@segiddins - when you say a "realm" file, is default.realm enough?  Or do I need to zip up the .lock, .log* files too?

**Comment by segiddins** [comment]
Just the .realm file should be good!

**Comment by mark-anders** [comment]
And how does one attach it?

**Comment by segiddins** [comment]
Realm files are just regular files, so you should be able to attach it the same way you'd attach an image or a text file.

**Comment by mark-anders** [comment]
When I try to attach it, Github complains: 

Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG.

I'll put it in Dropbox and include a link.

**Comment by segiddins** [comment]
That'd be great, thanks!
