### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by iSynth** [realm/realm-cocoa#2274]
./build.sh ios-swift

cp: build/DerivedData/Realm/Build/Products/Release-iphoneos-dynamic/Realm.framework: No such file or directory
Showing first 200 notices only
** BUILD FAILED **
The following build commands failed:
	PhaseScriptExecution Run\ Script Build/Intermediates/RealmSwift.build/Release-iphoneos/Realm.build/Script-026B0EFF1A78041A005E26C8.sh
(1 failure)

**Comment by jpsim** [comment]
`xcodebuild -version` should print `Xcode 7.0 Build version 7A152u`. What does it print for you?

**Comment by marchyman** [comment]
FYI: Xode 7b4 is version **7A165t** and changes in Swift means that `sh build.sh osx-swift` fails to compile.

**Comment by segiddins** [comment]
(Xcode 7 Beta 4 support is addressed in https://github.com/realm/realm-cocoa/pull/2270, which is on the `seg-swift-2.0-beta-4`, if that's indeed what you're trying to build with)

**Comment by jpsim** [comment]
Confirmed by user, so closing.
