### ISSUE TITLE
Type 'List<T>' does not conform to protocol 'RangeReplaceableCollectionType'

### ISSUE THREAD

**Issue by konradowy** [realm/realm-cocoa#2277]
Hi there,

since yesterday a new problem with swift-2.0 branch:

.../Pods/RealmSwift/RealmSwift/List.swift:308:1: Type 'List<T>' does not conform to protocol 'RangeReplaceableCollectionType'

won't compile

**Comment by kishikawakatsumi** [comment]
Swift 2 build is now required Xcode 7 beta**4** from https://github.com/realm/realm-cocoa/commit/0cd7a8ef9637b608ce14cabb673ea0230a42318b

Please upgrade your Xcode to beta**4**.

**Comment by konradowy** [comment]
thanks, working on beta4.
