### ISSUE TITLE
Updating List< > which is part of another object [Swift]

### ISSUE THREAD

**Issue by kresovic-milos** [realm/realm-cocoa#2278]
I have object Event with some attributes and a list of users who are attendees of the event:
```
class Event: Object {
    dynamic var eventId:Int = -1
    dynamic var type:Int = -1
    dynamic var title:String = ""
    dynamic var descriptionText:String = ""
    dynamic var creatorId:Int = -1
    dynamic var owner:User = User()
    dynamic var place:String = ""
    dynamic var startDate:String = ""
    dynamic var lat:Double = 0.0
    dynamic var lng:Double = 0.0
    dynamic var availability:String = ""
    dynamic var attendeesCount:Int = 0
    dynamic var attendees = List<User>()
    
    override static func primaryKey() -> String? {
        return "eventId"
    }
```

In the first moment in the app, Event is created without any attendees and later, when I want to update it with one or more new attendees ```event!.attendees.append(attendee)```, I am having a problem. If the same ```User``` as new attendee is already added in database, new one can not be added and the app crashes.

I was also thinking to have another object(table) that will solve this but in that case I will have another issues:
```
class Attendee: Object {
    dynamic var eventId:Int = -1
    dynamic var userId:Int = -1
```

Can somebody give me advice how to solve this, I really want to stay with Realm on this project.

Thanks in advance.

**Comment by yoshyosh** [comment]
Are you using this `event!.attendees.append(attendee)` within a write transaction? Can you share the error message and code where you are doing this?

**Comment by jpsim** [comment]
The problem is actually that `List.append()` will add the object to the Realm if it's unpersisted, but you already have a `User` with that primary key, so you can't create another User with the same primary key. Instead, you should update the User with the same primary key and append *that* to the list:

```swift
let attendeeValue...
let attendee = realm.create(User.self, value: attendeeValue, update: true)
event!.attendees.append(attendee)
```

**Comment by kresovic-milos** [comment]
@yoshyosh  sure it's inside write transaction closure, I just wrote the most important parts of code to keep my question simple. Error message claims that user with the same id can not be added.

@jpsim thanks for the answer, I will try it out and let you know if it works.

**Comment by kresovic-milos** [comment]
@jpsim it works, thank you!

**Comment by immortalsantee** [comment]
> The problem is actually that `List.append()` will add the object to the Realm if it's unpersisted, but you already have a `User` with that primary key, so you can't create another User with the same primary key. Instead, you should update the User with the same primary key and append _that_ to the list:
> 
> ```swift
> let attendeeValue...
> let attendee = realm.create(User.self, value: attendeeValue, update: true)
> event!.attendees.append(attendee)
> ```

I tried your approach but I have getting new entries with same primary key. Please see image attached.
![screen shot 2019-02-11 at 6 50 15 pm](https://user-images.githubusercontent.com/6284566/52565216-4efbaa00-2e2e-11e9-9c81-10bf9ca02f79.jpg)

**Comment by immortalsantee** [comment]
`guard let recipe = uiRealm.object(ofType: SLRecipe.self, forPrimaryKey: "1") else { return }
        
        let _i1: [String: Any] = [
            "name": "Pitho",
            "id": "1",
            "quantity": 10,
            "note": "White pitho kinda ramro."
        ]
        
        let _i2: [String: Any] = [
            "name": "ata",
            "id": "2",
            "quantity": 20,
            "note": "Ata chai optional ho."
        ]

        let _i3: [String: Any] = [
            "name": "puri",
            "id": "3",
            "quantity": 30,
            "note": "Puri pani use garda ramro. But yo chai alternate ho. Use garda pani huncha or na garda pani huncha."
        ]
        
        try? uiRealm.write { () -> Void in
            let updatedIngredients = [_i1, _i2, _i3].map{ uiRealm.create(SLIngredient.self, value: $0, update: true) }
            recipe.ingredient.append(objectsIn: updatedIngredients)
        }`
