### ISSUE TITLE
Exception is not thrown when inside a background thread.

### ISSUE THREAD

**Issue by grd888** [realm/realm-cocoa#2282]
I'm trying to sync my data from Parse service (parse.com) to Realm inside a background thread:

```objc
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
   // do my realml stuff here

});
```

My issue is that if I get any errors with Realm ,( like for example invalid property types, or using createOrUpdate without a primary key) , no exception is thrown and the app just continues to run. However the background thread processing stops. I know because using the Realm browser shows data was not persisted. 

Debugging is difficult because I don't know the cause of the problem.

Is there a special way to work with Realm inside a background thread? If this is a bug, what workarounds can i do so that Xcode can stop execution and show me the Exception like the usual?

**Comment by segiddins** [comment]
@grd888 if that's happening, it's not supposed to -- is there any way you could share a project with us that demonstrates these issues, either here or privately at help@realm.io, so we can investigate? Thanks!

**Comment by grd888** [comment]
Thanks for your response. I sent you a sample project demonstrating the issue. I also found out that the issue is not with the fact that it is running inside a dispatch_async block. Rather this issue occurs when inside a Parse API results block.

 In the sample project I sent to you by email, the issue occurs inside the Parse findObjectsInBackground API call. To reproduce it, add any new property to an RLMObject subclass. Now the background process does not finish because of the error in the line [RLMRealm defaultRealm]. However program execution just continues with no Exception being raised.

**Comment by segiddins** [comment]
@grd888 so I just ran your sample project, and confirmed that Realm is indeed throwing exceptions as expected, but since that code is executing inside the parse results block, Parse is catching that exception and not rethrowing it. Unfortunately, there's really nothing we can do about that -- we're throwing the exception, and it's being caught.

**Comment by grd888** [comment]
yes, that's right. Anyway, I have resorted to putting the statements inside a try-catch block so the exceptions are now caught. Thank you again for the quick responses.
