### ISSUE TITLE
Inconsistent behaviour

### ISSUE THREAD

**Issue by vishaltelangre** [realm/realm-cocoa#2285]
I have following snippet of code:

```swift
let users = User.objectsWithPredicate(NSPredicate(format: "name = %@", "Unknown"))
println("# of users: \(users.count)")
for user in users {
        let user = user as! User
        println("Modifying user -- \(user.id)")
        let realm = RLMRealm.defaultRealm()
        realm.beginWriteTransaction()
        user.isGuest = true
        realm.addOrUpdateObject(user)
        realm.commitWriteTransaction()
        println("Modified user -- \(user.id)")
}
println("Outside the loop")
```
The output is as follows:

```
# of users: 5
Modifying user -- 2
Modified user -- 2
Modifying user -- 4
Modified user -- 4
Outside the loop
```

This is unexpected. I am not blocking the write transaction here or anywhere else in my code. If I re-run this block of code over again using an exponentially incrementing explicitly invoked non-repeating timer, the output gets reduced as follows with many retries:

```
# of users: 3
Modifying user -- 1
Modified user -- 1
Modifying user -- 5
Modified user -- 5
Outside the loop
```

and one more time:

```
# of users: 1
Modifying user -- 3
Modified user -- 3
Outside the loop
```

What the heck?!

**Comment by jpsim** [comment]
Queries in Realm are views into your data, so in this case it looks like you're modifying data matching your query within your loop, which is reflected instantly. Is it possible that you have a default property value for `name` set to `Unknown`?

But really, in this case, I'd recommend you use KVC to update your objects' values all at once:

```swift
Realm().write {
    let users = User.objectsWhere("name = %@", "Unknown")
    users.setValue(true, forKeyPath: "isGuest")
}
```

**Comment by vishaltelangre** [comment]
Haven't tried yet, but sounds a reasonable solution! @jpsim thanks for elaborative answer.

**Comment by vishaltelangre** [comment]
FYI, application quits with an alert on XCode without any error while it's executes above code:

```
Lost connection to "Vishal's iPhone"

Restore the connection to "Vishal's iPhone" and run "Yogurt" again, or if "Yogurt" is still running, you can attach to it by selecting Debug > Attach to Process > Yogurt.
```

When I reopen app, it shows that those modifications have been successful.
