### ISSUE TITLE
New Realm tutorial

### ISSUE THREAD

**Issue by bonzoq** [realm/realm-cocoa#2286]
Hi,

I'm not sure if this is the best place but I wanted to let you know that I wrote a tutorial on using Realm with Mantle model framework. Hope you could help spread the word. http://www.toptal.com/ios/simplifying-restful-api-use-and-data-persistence-on-ios-with-mantle-and-realm

Thanks!

**Comment by jpsim** [comment]
Thank you so much for writing such a great article. We retweeted it this morning. In the future, just mention us on twitter and we'll see it :smile:

**Comment by bonzoq** [comment]
Thanks for the retweet!:-)
