### ISSUE TITLE
Using NSDate().distantPast irreversibly damages property

### ISSUE THREAD

**Issue by ronaldmannak** [realm/realm-cocoa#2292]
Using RealmSwift 0.93.2

It seems that when a property is set to NSDate.distantPast(), the year is saved as a negative value. NSDate.distantFuture() seems to work fine. Furthermore, trying to overwrite a property that once was set to NSDate.distantPast() will always be saved with a negative year value after that, the record is permanently damaged. I haven't found a way to restore a record once a value is set to NSDate.distantPast() other than deleting the complete record and recreating it again. 

(Saving NSDate.distantPast().timeIntervalSince1970 as a Double shows a different unexpected behavior, it is seen as a nil and crashes queries). 

Could it be that Realm's internal date format doesn't consider 0 to be a valid date?

```swift
class Record: Object {
    dynamic var startDate: NSDate = NSDate.distantPast()   // Year will be saved as a negative value
    dynamic var endDate: NSDate = NSDate.distantFuture() // This works fine, unless endDate is changed 
}

...

let record = Record() // startDate is 0000-12-30 00:00:00 +0000, endDate is 4000-07-24 23:00:00 +0000
record.startDate = NSDate() // Unexpected: startDate is -2014-07-25 00:00:00 +0000 (note year is -2014, not 2015)

record.endDate = NSDate() // startDate is 2015-07-25 00:00:00 +0000
record.endDate = NSDate.distantPast() // endDate is 0000-12-30 00:00:00 +0000
record.endDate = NSDate()  // Unexpected: startDate is -2014-07-25 00:00:00 +0000 (note year is -2014, not 2015)
```

**Comment by segiddins** [comment]
@ronaldmannak that's quite strange, and I'd love to be able to investigate more thoroughly -- could you possibly share a project with us, either here or privately at help@realm.io, that demonstrates the issue so I can dig in? Thanks!

(I tried reproducing with the code in your comment, and here's the debugger output I saw:
```
(lldb) po record
Record {
	startDate = 0000-12-30 00:00:00 +0000;
	endDate = 4001-01-01 00:00:00 +0000;
}

(lldb) po record
Record {
	startDate = 2015-07-25 00:51:23 +0000;
	endDate = 4001-01-01 00:00:00 +0000;
}

(lldb) po record
Record {
	startDate = 2015-07-25 00:51:23 +0000;
	endDate = 2015-07-25 00:51:29 +0000;
}

(lldb) po record
Record {
	startDate = 2015-07-25 00:51:23 +0000;
	endDate = 0000-12-30 00:00:00 +0000;
}

(lldb) po record
Record {
	startDate = 2015-07-25 00:51:23 +0000;
	endDate = 2015-07-25 00:51:41 +0000;
}
```
)

**Comment by ronaldmannak** [comment]
I found the issue and it's unrelated to Realm. I used OSX' NSDatePicker to change the dates in the database and once you feed it NSDate.distantPast(), NSDatePicker only can go down, hence the negative years. Closing issue
