### ISSUE TITLE
Use RealmObject setValue for key, but  the key is don't had...

### ISSUE THREAD

**Issue by burning-git** [realm/realm-cocoa#2295]
'[<RLMStandalone_InformationList 0x7f8fe5ea9da0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key fcount.'
How to judge the key is had in this class?

**Comment by jpsim** [comment]
Looks like you're calling `-[RLMObject setValue:value forKey:@"fcount"]` on an `RLMObject` instance without an `fcount` property. Is it possible you've misspelled the property you're trying to set? Or forgotten to add an `fcount` property to your model? Or maybe you're attempting to set this property on an object of a different class?

**Comment by burning-git** [comment]
yes,RLMObject instance without an fcount property,,but  now, I need how to juadge fcount belong to RLMObject ? I try to use setFcount: method, but it 's  failse.

**Comment by jpsim** [comment]
Could you please show us some code that demonstrates the issue you're having, @burning-git ? I'm having difficulty understanding your question.

**Comment by burning-git** [comment]
#import "RLMObject.h"

@interface InformationType : RLMObject
@property(copy,nonatomic) NSString * name;
@property(copy,nonatomic) NSString * id;

@end
RLM_ARRAY_TYPE(InformationType)
Use:

InformationType *Model=[[InformationType alloc] init];
[Model setValue:@"1" forKey:@"type"];
I wan't juadge the property type it's belong to the Model??   then I try to use "setType" method,but it's not Model..

**Comment by segiddins** [comment]
@burning-git that's actually the way key-value coding is supposed to work, as described in [Apple's programming guide](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/KeyValueCoding/Articles/KeyValueCoding.html). (i.e. it's intentional that an exception is raised when trying to get/set the value for an unknown key)

If you want to determine if a given RLMObject has a particular property, you can either use `-[RLMObject respondsToSelector:@selector(propertyName)]`, or check if `[[object.objectSchema.properties valueForKey:@"name"] containsObject:@"propertyName"]`.

I hope that answers your question!

**Comment by burning-git** [comment]
1:
I try use  [RLMObject respondsToSelector:@selector(propertyName)]  then, find the RMLObject is  RLMStandalone_InformationType  (but RMLObject is InfomationType in fact).  
 2:
[[object.objectSchema.properties valueForKey:@"name"] containsObject:@"propertyName"]  It's success,  
then  I want to konw  Why 1 not function,, I try to  use setPropertyName,,,but It's  wrong!  Can you help me?

**Comment by segiddins** [comment]
@burning-git can you try and help us understand exactly what it is you're trying to accomplish?

**Comment by burning-git** [comment]
oh,sorry ,my english not well...
I use    -[RLMObject respondsToSelector:@selector(propertyName)]   method, It's not fuction

**Comment by burning-git** [comment]
Then ,I try to use "SetPropertyName" methond,but It's also  not function

**Comment by jpsim** [comment]
I'm sorry @burning-git but none of us can understand what you're asking.

Can you please reformulate your issue in Japanese? @kishikawakatsumi should be able to help.

**Comment by jpsim** [comment]
You're misusing KVC in this case. Please read [Apple's Key Value Coding guide](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/KeyValueCoding/Articles/KeyValueCoding.html).
