### ISSUE TITLE
'RLMArray' does not have a member named 'exchangeObjectAtIndex'

### ISSUE THREAD

**Issue by i-schuetz** [realm/realm-cocoa#2297]
After update swift2.0 branch, (commit 2b1d6689fa956aee78b1d673b620dd55dc5e536d), the project doesn't compile.

proj/Pods/RealmSwift/RealmSwift/List.swift:320:9: 'RLMArray' does not have a member named 'exchangeObjectAtIndex'

**Comment by segiddins** [comment]
Are you also using the Realm framework from the swift 2.0 branch?

**Comment by i-schuetz** [comment]
Yes, these are my dependencies:
```swift
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
```
I could fix it temporarily by specifying the commit of RealmSwift, to last one when it was working:

```swift
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0', :commit => 'beb7778ce12829c78242c6bc39cc0fd031e7423c'
```

**Comment by i-schuetz** [comment]
Right - after removing Realm and RealmSwift from the lock file and reinstalling it works again.
