### ISSUE TITLE
CI sometimes fails to get past the "Touch" step

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2304]
See https://ci.realm.io/job/objc_pr/1444/configuration=Debug,swift_version=2.0,target=ios-swift/consoleFull.

It'd be nice to have further diagnostics on this.

**Comment by jpsim** [comment]
This seems to happen when the simulator fails to boot and is a possible reason why #2074 is failing.

**Comment by bdash** [comment]
I'm able to reproduce this locally by doing the following:

    rm -rf build
    sh build.sh verify-ios-swift

If I re-run `sh build.sh verify-ios-swift` after the failure, it succeeds.

When it fails, I consistently see the following message during the build output:

    2015-10-08 13:17:33.051 xcodebuild[57711:240667]  iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.

The same message is present in the failing builds seen on CI.

**Comment by bdash** [comment]
This doesn't happen if I tweak the `test-ios-swift` target in build.sh to run `xcodebuild … build` prior to running `xcodebuild … test`. :confused:

**Comment by tgoyne** [comment]
That's way less ugly than what we're already doing to get switching between simulator versions to mostly work, so I'd be okay with it...

**Comment by bdash** [comment]
I wish I had some understanding of why `xcodebuild test` is failing like this, and why `xcodebuild build` helps. Doing `xcodebuild … build test` also works around the issue and is less ugly, so I'll post a PR with that change shortly.

**Comment by bdash** [comment]
Wrote up http://openradar.appspot.com/radar?id=4968894137630720 about the underlying Xcode issue, including some analysis as to why it's happening.

**Comment by jpsim** [comment]
Very nice investigative work, @bdash!
