### ISSUE TITLE
0.38.2 use_frameworks! still fails to archive properly

### ISSUE THREAD

**Issue by codywinton** [realm/realm-cocoa#2305]
0.38.2 `use_frameworks!` still fails to archive properly. The archive doesn't automatically show up and when I try to open the archive I get the this message: `The archive may be corrupt or unreadable`

**Comment by segiddins** [comment]
@codywinton this sounds more like a CocoaPods issue than a Realm one, does anything at https://github.com/CocoaPods/CocoaPods/issues sound familiar?

**Comment by codywinton** [comment]
Yup, my bad. Wrong place to post the issue. Sorry.
