### ISSUE TITLE
Build Carthage swift-2.0 branch

### ISSUE THREAD

**Issue by QoT** [realm/realm-cocoa#2306]
It looks like `./build.sh build` fails when trying to build `swift-2.0` branch (https://github.com/realm/realm-cocoa/tree/swift-2.0) by Xcode version 7.0 (7A120f) resulting in:

`/Users/<user>/Desktop/realm-cocoa-swift-2.0/RealmSwift/List.swift:324:1: error: type 'List<T>' does not conform to protocol 'RangeReplaceableCollectionType'
extension List: RangeReplaceableCollectionType {
^
Swift.RangeReplaceableCollectionType:43:17: note: protocol requires function 'splice(_:atIndex:)' with type '<S> (S, atIndex: List<T>.Index) -> ()'
  mutating func splice<S : CollectionType where S.Generator.Element == Generator.Element>(newElements: S, atIndex i: Self.Index)
                ^
Swift.RangeReplaceableCollectionType:54:17: note: protocol requires function 'removeAtIndex' with type '(List<T>.Index) -> List<T>.Generator.Element'
  mutating func removeAtIndex(i: Self.Index) -> Self.Generator.Element
                ^
/Users/vedranozir/Desktop/realm-cocoa-swift-2.0/RealmSwift/List.swift:269:17: note: candidate has non-matching type '<T> (Int) -> ()'
    public func removeAtIndex(index: Int) {
                ^
Swift.RangeReplaceableCollectionType:65:17: note: protocol requires function 'removeRange' with type '(Range<List<T>.Index>) -> ()'
  mutating func removeRange(subRange: Range<Self.Index>)
                ^
Swift.RangeReplaceableCollectionType:80:17: note: protocol requires function 'removeAll(keepCapacity:)' with type '(keepCapacity: Bool) -> ()'
  mutating func removeAll(keepCapacity keepCapacity: Bool)
                ^
/Users/vedranozir/Desktop/realm-cocoa-swift-2.0/RealmSwift/List.swift:288:17: note: candidate has non-matching type '<T> () -> ()'
    public func removeAll() {
                ^
`

It looks like `RealmSwift/List.swift@324` instead:
`extension List: RangeReplaceableCollectionType {`

should read:
`extension List {`

After that change, build completes successfully.

**Comment by segiddins** [comment]
You need to use beta 4 to build the swift 3 framework, and if memory serves that build number comes from an earlier beta.

**Comment by neon0619** [comment]
Type 'List<T>' does not conform to protocol 'RangeReplaceableCollectionType'

im using Xcode 7 Beta 5. im still getting this error, what should i do to fix this error.?

**Comment by jpsim** [comment]
FYI `7A120f` is the build number for Xcode 7 beta 1. @neon0619 I don't know which version of Xcode 7 you're using, but the latest one is beta 4 (`7A165t`), which is the only version Realm Swift supports at the moment.

**Comment by neon0619** [comment]
@jpsim Thanks for the correction, the Beta 5 that i mention is actually for OS X El Capitan Developer Beta 5. Thanks again for your comment. :)

**Comment by jpsim** [comment]
Ok, so which version of Xcode 7 are you using?

**Comment by neon0619** [comment]
im currently using Version 7.0 beta 3 (7A152u).

**Comment by jpsim** [comment]
Alright, that would explain it. We'll continue to keep the `swift-2.0` branch up to date with the latest Xcode 7 beta's from Apple. Cheers!

**Comment by neon0619** [comment]
@jpsim  Thanks again. I appreciate your comment here. :+1:

**Comment by imran20487** [comment]
With Xcode 7 beta 4. I am getting this error when running on the iPhone: 

dyld: Symbol not found: __TMPdVSs12_prext_Slice
  Referenced from: /private/var/mobile/Containers/Bundle/Application/D9A865DC-74FD-4D7E-A340-78DBE34AD98B/MyApp.app/Frameworks/RealmSwift.framework/RealmSwift
  Expected in: /private/var/mobile/Containers/Bundle/Application/D9A865DC-74FD-4D7E-A340-78DBE34AD98B/MyApp.app/Frameworks/libswiftCore.dylib
 in /private/var/mobile/Containers/Bundle/Application/D9A865DC-74FD-4D7E-A340-78DBE34AD98B/MyApp.app/Frameworks/RealmSwift.framework/RealmSwift

**Comment by segiddins** [comment]
@imran20487 currently, the Swift 2 branch of Realm Swift requires Xcode 7 beta 5

**Comment by imran20487** [comment]
@segiddins With cocoapods it does not work, but with Using source (realm.framework, realmswift.framework) it works.

**Comment by marlowcharite** [comment]
I'm getting the same error that @imran20487 was getting 3 weeks back. `dyld: Symbol not found: __` only mine is with `__TMPdVSs12MapGenerator`
