### ISSUE TITLE
Adding RLMSupport.swift through Cocoapods?

### ISSUE THREAD

**Issue by bensarz** [realm/realm-cocoa#2307]
I'm adding Realm (the ObjC library since I'm working in a bilingual code base) through Cocoapods:

```
platform :ios, '8.0'
use_frameworks!

target 'MyProject' do

pod 'Realm', '~> 0.93.2'

end
```

I find myself looking to iterate over an `RLMArray` object. I'm reading that I should be adding RLMSupport.swift to my project.

Is there a clean way of adding this file to my project as it is currently not included as part of the default podspec?

**Comment by jpsim** [comment]
You'll have to drag it in to your app's target. We don't want to bundle it with the framework because that would force everyone using Realm Objective-C it to pull in the Swift dynamic libraries, which would be problematic for Objective-C-only apps.

**Comment by bensarz** [comment]
Ok cool, thanks @jpsim for the quick response.
