### ISSUE TITLE
Carthage installation occasionally fails

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2315]
Printing the following error message:

> The file “iOS” couldn’t be saved in the folder “Build” because a file with the same name already exists.

Sometimes it's "Mac" rather than "iOS", and I'm sure the same could happen with "watchOS"

**Comment by brentleyjones** [comment]
We've been seeing the same thing on our build server. None of our developers have been seeing it though.

**Comment by segiddins** [comment]
@brentleyjones what version of Carthage are you running on the server?

**Comment by brentleyjones** [comment]
0.8.0 (or, a couple commits before they cut 0.8.0).

**Comment by istx25** [comment]
I'm pretty sure this is an issue with Carthage. I've seen it happens with other frameworks. It was supposed to be fixed somewhere in the last few Carthage releases.

**Comment by jairobjunior** [comment]
@istx25 Yeah, I was having the same problem using Carthage 0.8. I just updated to 0.10 and everything seems to be fine.

**Comment by jpsim** [comment]
Carthage and our support for it has come a long way since this issue was filed. I'm quite certain this is no longer a problem.
