### ISSUE TITLE
Add strong reference example to notification sample code block

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#2324]
We describe this below the code sample but it would be nice to show it. User struggling with current sample: http://stackoverflow.com/questions/31754245/how-to-use-realm-notifications-in-swift

**Comment by segiddins** [comment]
We already do? We explicitly assign the notification token to a property

**Comment by segiddins** [comment]
@yoshyosh and I just agreed that the current code sample is clear enough, since we're already assigning to `self.token`.
