### ISSUE TITLE
Support for map

### ISSUE THREAD

**Issue by shmidt** [realm/realm-cocoa#2327]
Can you please add support for ```map```?

I would like to use something like that: 
```swift
let realmObjectIDs = Realm().objects(Address).map({$0.objectId})
```
but currently have compiler error: ```Cannot invoke 'map' with an argument list of type '((_) -> _)'```

**Comment by jpsim** [comment]
Since `Results` (and `List`) conform to `SequenceType`, you can already use the Swift standard library's version of `map(_:_:)`: 

```swift
let realmObjectIDs = map(Realm().objects(Address)) {$0.objectId}
```

And in Swift 2.0, thanks to protocol extensions, it looks exactly like the code sample you posted!

```swift
let realmObjectIDs = Realm().objects(Address).map({$0.objectId})
```

**Comment by hsavit1** [comment]
@jpsim does it actually conform to SequenceType? I thought only GeneratorType ?

**Comment by jpsim** [comment]
The [`RealmCollectionType`](https://realm.io/docs/swift/latest/api/Protocols/RealmCollectionType.html) protocol, which `Results` and `List` conform to, inherits from `CollectionType` ([source](https://github.com/realm/realm-cocoa/blob/v0.97.1/RealmSwift-swift2.0/RealmCollectionType.swift#L52)), which in turn inherits from `	Indexable` and `SequenceType` ([source](http://swiftdoc.org/v2.1/protocol/CollectionType/)). In Swift 2.x, `map` is declared as a method in a protocol extension on `SequenceType`: http://swiftdoc.org/v2.1/protocol/SequenceType/#func-map_
