### ISSUE TITLE
Swift: realm.objectForPrimaryKey(Object, key: id) expects Object.self

### ISSUE THREAD

**Issue by schickling** [realm/realm-cocoa#2330]
The `realm.objects` API allows the form `realm.objects(Object)` while the `realm.objectForPrimaryKey(Object.self, key: id)` API expects the `Object` param to be `Object.self`. Is this an intended behavior?

Imo just writing `realm.objectForPrimaryKey(Object, key: id)` would be the more Swift-way to do :+1: 

The same applies to the `realm.create(Object, value: ..., update: ...)` API.

**Comment by segiddins** [comment]
This is a limitation of Swift itself, we totally agree that the trailing `.self` is suboptimal.

**Comment by schickling** [comment]
Could you quickly explain why it works for `realm.objects`?

**Comment by segiddins** [comment]
Because the type name is the only thing inside the parenthesis--there are no parameter labels or other parameters.
