### ISSUE TITLE
Question: Update/Set relationship without updating existing child object

### ISSUE THREAD

**Issue by schickling** [realm/realm-cocoa#2331]
Given the following data model, is there a way to update or set a child relationship without updating the (existing) child object?

**Data Model**
```swift
class Person: Object {
    dynamic var id = 0
    dynamic var dog: Dog?
    
    override static func primaryKey() -> String? {
        return "id"
    }
}

class Dog: Object {
    dynamic var id = 0
    dynamic var name = ""
    
    override static func primaryKey() -> String? {
        return "id"
    }
}
```

**Code**
```swift
let realm = Realm()

// query existing dog
let existingDog = realm.objectForPrimaryKey(Dog.self, key: 42)
print(existingDog) // id: 42, name: Rex

let newDog = Dog(value: ["id": 42, "name": "Pluto"])
let person = Person()


realm.write {
    // this shouldn't update the existing dog
    // i.e. the name of the dog with id: 42 in the database should still be "Rex"
    person.dog = newDog
    realm.add(person, update: true)
}

```
I've also tried to do this via `realm.create` but had no success either. Any ideas?

Note: This question is also [on stackoverflow](http://stackoverflow.com/questions/31772664/realm-update-set-relationship-without-updating-existing-child-object).

**Comment by segiddins** [comment]
@schickling what's happening there is the expected behavior, since your adding the person with a dog with the same id  (the primary key) as the existing one, causing the existing one to be updated. If you don't want to see the existing object updated, you'd have to give the new dog a different primary key value. I hope that helps!

**Comment by schickling** [comment]
Is there a way to set a relationship without updating the child object?

**Comment by segiddins** [comment]
Sure! You could do either one of the following:

```swift
realm.write {
  realm.create(Person.self, value: ["dog" : existingDog])
}
```

```swift
realm.write {
  let person = Person()
  person.dog = existingDog
  realm.add(person)
}
```
