### ISSUE TITLE
crash after upgrade from 0.92.3

### ISSUE THREAD

**Issue by pengj** [realm/realm-cocoa#2341]
Hi,

After upgrade from 0.92.3 (RealmSwift) to 0.92.4 or 0.94.0, app crashed at the same place when call 
`let realm = Realm()`

This crash occurs only when running on the devices. (No crashes occur on the simulators iOS 8.4)

Environment:

iOS 8.1.3
iPhone 5
Xcode 6.4
RealmSwift (0.92.4 to 0.94.0)

There is no output, only `(lldb) ` 
<img width="1139" alt="object_swift_and_slack" src="https://cloud.githubusercontent.com/assets/1306240/9057588/0734a3c6-3a93-11e5-86af-1ee85d6e848b.png">

**Comment by segiddins** [comment]
@pengj are you sure it's not an exception being thrown, with a message? If not, having a project we can run would make investigating much easier, thanks!

**Comment by Armenm** [comment]
I also have crash on launch with version 0.94.0
Link to the crash http://crashes.to/s/ab443d71878

**Comment by segiddins** [comment]
@Armenm that crash looks like https://github.com/realm/realm-cocoa/issues/2332, and does not look like @pengj's crash.

**Comment by Armenm** [comment]
Thanks @segiddins for quick reply. Will comment there. Maybe it will help to fix the bug.

**Comment by pengj** [comment]
@segiddins There is no exception being thrown when app crashed, the screenshot shows the moment when app crashed. I try to make a simple project to reproduce the error, but I can't reproduce it.

**Comment by pengj** [comment]
@segiddins When I configure the app build as release, there is no crash.

**Comment by segiddins** [comment]
@pengj in that case, since it's actually the swift standard library crashing and not Realm, and since you can't reproduce it, I'm going to close this issue for now. Feel free to re-open it if you see this happening again!

**Comment by pengj** [comment]
@segiddins see my updated comments

**Comment by segiddins** [comment]
Can you

**Comment by pengj** [comment]
@segiddins I sent you a email with my project. Thanks for you help.

**Comment by segiddins** [comment]
@pengj I can't reproduce this on the iPad Mini 2 I have at hand.

**Comment by pengj** [comment]
@segiddins the app crash when test in iPhone5 with iOS 8.1.3, it works for iPad air with iOS 8.4.

**Comment by segiddins** [comment]
@pengj I don't have an iOS 8.1.3 device around, but it worked fine on a 32 bit iPod touch running 8.3.

**Comment by pengj** [comment]
@segiddins I will close the issue for now. The crash only happens on iPhone 5 with iOS 8.1.3 as far as I can see, works well for simulator with iOS 8.1. If the build is configure as release rather than debug, it also works well. Let's wait if other developers have the same problem when update. Thanks for your help.
