### ISSUE TITLE
Prediate Queries: Optional operators combined with required

### ISSUE THREAD

**Issue by bryan1anderson** [realm/realm-cocoa#2342]
I'm not sure really how to ask this. Whether this is already possible or not I'm not sure. But would be an excellent enhancement if it was

I'm using several NSPredicates to filter a query. 

However I'm having trouble getting the results I want. Basically I want to return objects that contain two different boolean properties. In order to display, one or the either of these properties must be true. 

This is easily done: NSPredicate("enabledByBeacon == true OR enabledByDate == true")

However, while this query can return if either of the boolean properties equal true, I want to add a third property that must always be true. 

So 1 or 2 must be true, 3 must always be false 

I've tried these unsuccessfully 
filter("enabledByBeacon == true OR enabledByDate == true AND wasSubmitted == false")
filter("enabledByBeacon == true OR enabledByDate == true NOT wasSubmitted == false")
filter("isEnabledByiBeacon == true OR isBetweenDates == true", "wasSubmitted == false")

**Comment by segiddins** [comment]
Does the following predicate work for you?

`NSPredicate(format: "(enabledByBeacon == true || enabledByDate == true) && wasSubmitted == true")`

**Comment by bryan1anderson** [comment]
Yes, I wasn't aware subqueries could be created using semicolons

Thanks for the help
