### ISSUE TITLE
Leaking memory when instantiating Realm object

### ISSUE THREAD

**Issue by ganzogo** [realm/realm-cocoa#2345]
I noticed memory leaking in my Swift project and have distilled it down to a line of code creating an instance of a simple Realm Object. The object is defined as: 

    class MyModel: Object {
      dynamic var name:String = ""
    }

And the line of code, (which appears in `viewDidLoad` on a view controller) is:

    let myInstance = MyModel()

I'm using Xcode 6.4, Swift 1.2, Realm 0.9.4 included via Carthage. Runnning on a device (iPhone 6, iOS 8.4) using Instruments I can consistently see 64 bytes of memory leaked by `libswiftCore.dylib`. 

You can checkout the project at https://github.com/ganzogo/RealmLeakTest. 

Stack trace is...

    31 libdyld.dylib start
    30 RealmLeakTest main /Users/matthew/Documents/ganzogo/RealmLeakTest/RealmLeakTest/AppDelegate.swift:12
    29 UIKit UIApplicationMain
    28 UIKit -[UIApplication _run]
    27 CoreFoundation CFRunLoopRunSpecific
    26 CoreFoundation __CFRunLoopRun
    25 CoreFoundation __CFRunLoopDoBlocks
    24 CoreFoundation __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
    23 FrontBoardServices __31-[FBSSerialQueue performAsync:]_block_invoke_2
    22 UIKit -[UIApplication workspaceDidEndTransaction:]
    21 UIKit -[UIApplication _runWithMainScene:transitionContext:completion:]
    20 UIKit -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
    19 UIKit -[UIWindow makeKeyAndVisible]
    18 UIKit -[UIWindow _setHidden:forced:]
    17 UIKit -[UIWindow addRootViewControllerViewIfPossible]
    16 UIKit -[UIViewController view]
    15 UIKit -[UIViewController loadViewIfRequired]
    14 RealmLeakTest @objc RealmLeakTest.ViewController.viewDidLoad (RealmLeakTest.ViewController)() -> () /Users/matthew/Documents/ganzogo/RealmLeakTest/RealmLeakTest/ViewController.swift:18
    13 RealmSwift 0x1022d49af
    12 Realm 0x1000c829b
    11 libobjc.A.dylib _objc_msgSend_uncached_impcache
    10 libobjc.A.dylib lookUpImpOrForward
     9 libobjc.A.dylib _class_initialize
     8 Realm 0x1000c4df3
     7 Realm 0x1000935cb
     6 Realm 0x10009407b
     5 RealmSwift 0x1022d90df
     4 libswiftCore.dylib 0x102474e3f
     3 libswiftCore.dylib 0x1023b1757
     2 libswiftCore.dylib 0x102471cb3
     1 libsystem_malloc.dylib malloc
     0 libsystem_malloc.dylib malloc_zone_malloc

**Comment by segiddins** [comment]
This is interesting -- the leak seems to be coming from the mirror that swift's reflection is giving us.

**Comment by segiddins** [comment]
So, this only happens during Realm's schema initialization, for a total of 128 bytes reported as "leaked" for each `Object` subclass. At the end of the day, we can't even be sure this is a leak, since Realm intentionally holds onto a global `RLMSchema` instance, which will have a much bigger memory footprint than those few leaked bytes.
Thanks for the report, though!
