### ISSUE TITLE
Question: Is there a way to delete objects if the primary key doesn't match JSON data?

### ISSUE THREAD

**Issue by bryan1anderson** [realm/realm-cocoa#2346]
Say I have an array of several JSON dictionaries being downloaded, then stored using Realm.

I use:
      
        for detail in self.dataArray {
                    let realm = Realm()
                    realm.beginWrite()
                    realm.create(Details.self, value: detailDic, update: true)
                    let details = realm.objects(Details)
                    
             
                    realm.commitWrite()
  

                }
                }

The expected functionality of update is to check the primaryKey against the dictionaries coming in. If any of the values in the dictionary associated with the primary key change, update, if an dictionary with a new primary key is present, then create a new object.. lastly I expected that if realm was storing a primary key that does not match any of the primary keys in the JSON dictionary, it would be deleted.

Is there an elegant way for realm to do this automatically?

**Comment by segiddins** [comment]
Well, you could do `realm.delete(realm.objects(Details))` before the loop of create or update operations?

**Comment by bryan1anderson** [comment]
Okay. I was trying to avoid a few issues by doing a full wipe. I'll need to rework a few things. Right now I have all my data coming in at once. So for up to a few seconds after I delete everything, the app lags, the data disappears and I need to use a loading screen to deal with this. Not too big of a deal, but wanted to see if there was a simple way around it

Thanks

**Comment by segiddins** [comment]
Well, another option could be to aggregate all the IDs of the objects you've received, and delete the objects whose IDs are not in that set.

**Comment by bryan1anderson** [comment]
Yeah I'l likely need to do just that. I lose all kinds of stored properties that I've manually created if I delete all every time a pull is triggered. 
Thanks
