### ISSUE TITLE
Unsupported architectures Error When Uploading to iTunes Connect

### ISSUE THREAD

**Issue by strongwillow** [realm/realm-cocoa#2352]
My env: Xcode 7 beta 4, Realm swift-2.0 branch.

It's doing well on both simulator and my devices. However, when I was archiving, Xcode reported:
    
    Unsupported architectures.  The executable for xxxx/Realm.framwork contains unsupported architectures [x86_64, i386]
    Unsupported architectures.  The executable for xxxx/RealmSwift.framwork contains unsupported architectures [x86_64, i386]

I think I should do something with strip-frameworks.sh. 
What should I do exactly?
Thx!

==== updated Friday=====
This morning I found Xcode had an update to beta 5, so I updated. After fixing some problems coming along, I managed to get the aforementioned problem again.

**Comment by strongwillow** [comment]
I solved the problem using lipo. But can we set the target arch in build command?

http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by jpsim** [comment]
Hi @strongwillow, how did you install Realm Swift? If you're using the prebuilt binary frameworks, please make sure to add a build phase to your app's main target: `bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh"`. We detail this in our [Swift 1.2 installation instructions](https://realm.io/docs/swift/latest/#installation-swift-12), but have't reflected that in our Swift 2.0 instructions yet. I've created an issue to track updating our docs accordingly (#2353).

**Comment by dhmspector** [comment]
I am having the same problem -- but in my case the added build phase to call strip-frameworks.sh is failing.   I followed all the instructions to the letter, including removing my old Realm.Framework and starting from scratch -- it looks like in Xcode6.4 Xcode isn't copying all of the framework to the derived data directory but only the LIPO'd archive and headers (or perhaps moving them to a different place)... so the strip-frameworks.sh file cannot be found .   This is with version 0.92.x  and still occurs with 0.94

**Comment by strongwillow** [comment]
@dhmspector In fact I didn't follow exactly what the blog suggested. I only used lipo to extract and combine into one arm architecture library. 
Then when I'm testing in simulator, I use the fat version of the two lib. When I'm archiving, I use the slim version. That work fine.

**Comment by strongwillow** [comment]
@jpsim Thanks for your input. I never used Swift-1.2 version so I didn't know:( I saw you flagged a doc update:)
