### ISSUE TITLE
"Primary key can't be changed after an object is inserted."

### ISSUE THREAD

**Issue by shmidt** [realm/realm-cocoa#2361]
I believe that "Primary key can't be changed after an object is inserted" should be added to the docs, because it's not obvious. 

In my case, I create some temporary ID's, and later I need to update them when object synchronized with server. It could be great if in future it could be nullable string used as primary property with possibility to assign it later.

**Comment by segiddins** [comment]
Fair point, I'll update the documentation for primary keys to say they can't be modified after the object is added to the Realm.

**Comment by markst** [comment]
@shmidt hey I'm working on something similar to what you mention - where by once my object is synchronised with our server the primary key may update. Are you able to provide any insight as to how you overcame the fact primary keys can't be changed after an object is persisted?

**Comment by shmidt** [comment]
@markst Sorry, no. I switched to Core Data instead.
