### ISSUE TITLE
Realm EXC_BAD_ACCESS when querying database

### ISSUE THREAD

**Issue by crhuber** [realm/realm-cocoa#2363]
Im using realm 0.94 and getting the EXC_BAD_ACCESS when querying database on the let realm = Realm() line. 

         // Get the default Realm
                let realm = Realm()
                // Query using an NSPredicate
                let predicate = NSPredicate(format: "s3_url = %@", s3_url)
                let medias =  realm.objects(MediaRealm).filter(predicate)

RealmSwift`RealmSwift.Realm.__allocating_init (RealmSwift.Realm.Type)(path : Swift.String) -> RealmSwift.Realm:
    0x1031c7170 <+0>:   pushq  %rbp
    0x1031c7171 <+1>:   movq   %rsp, %rbp
    0x1031c7174 <+4>:   pushq  %r15
    0x1031c7176 <+6>:   pushq  %r14
    0x1031c7178 <+8>:   pushq  %r12
    0x1031c717a <+10>:  pushq  %rbx
    0x1031c717b <+11>:  movq   %rdx, %r14
    0x1031c717e <+14>:  movq   %rsi, %r12
    0x1031c7181 <+17>:  movq   %rdi, %rbx
    0x1031c7184 <+20>:  movq   0x30(%rcx), %rdx
    0x1031c7188 <+24>:  movl   %edx, %esi
    0x1031c718a <+26>:  shrq   $0x20, %rdx
    0x1031c718e <+30>:  movq   %rcx, %rdi
    0x1031c7191 <+33>:  callq  0x1031dbe28               ; symbol stub for: swift_allocObject
    0x1031c7196 <+38>:  movq   %rax, %r15
    0x1031c7199 <+41>:  movq   %r14, %rdi
    0x1031c719c <+44>:  callq  0x1031dbf30               ; symbol stub for: swift_unknownRetain
    0x1031c71a1 <+49>:  movq   %rbx, %rdi
    0x1031c71a4 <+52>:  movq   %r12, %rsi
    0x1031c71a7 <+55>:  movq   %r14, %rdx
    0x1031c71aa <+58>:  callq  0x1031dbe58               ; symbol stub for: swift_convertStringToNSString
    0x1031c71af <+63>:  movq   %rax, %rbx
    0x1031c71b2 <+66>:  movq   0x16eaf(%rip), %rdi       ; (void *)0x0000000102fd4590: RLMRealm
    0x1031c71b9 <+73>:  callq  0x1031dbebe               ; symbol stub for: swift_getInitializedObjCClass
    0x1031c71be <+78>:  movq   0x191fb(%rip), %rsi       ; "realmWithPath:readOnly:error:"
    0x1031c71c5 <+85>:  xorl   %ecx, %ecx
    0x1031c71c7 <+87>:  xorl   %r8d, %r8d
    0x1031c71ca <+90>:  movq   %rax, %rdi
    0x1031c71cd <+93>:  movq   %rbx, %rdx
    0x1031c71d0 <+96>:  callq  0x1031dbcea               ; symbol stub for: objc_msgSend
    0x1031c71d5 <+101>: movq   %rax, %rdi

what am i doing wrong?

**Comment by strongwillow** [comment]
Try:

        realms = try! Realm(path: (url.path)!)

**Comment by crhuber** [comment]
I think this was caused by a adding new fields to realm but not making a migration.
