### ISSUE TITLE
Simple model throws exception (Swift 2.0)

### ISSUE THREAD

**Issue by remotevision** [realm/realm-cocoa#2364]
I am new to Realm and trying to create a simple model as shown in the sample doc. Every time I run it my code throws the exception below. I realize I'm using the Swift 2.0 branch which may not be stable, but I assume this much should work and I'm doing something wrong. 

Thoughts?

Model
```
class Consent: Object {
    dynamic var test: String = ""
}
```

Invocation
```
let mydog = Consent()
mydog.test = "Rex"
print("name of dog: \(mydog.test)")
```

Exception thrown
```
*** Terminating app due to uncaught exception 'RLMException', reason: ''NSArray' is not supported as an RLMObject property. All properties must be primitives, NSString, NSDate, NSData, RLMArray, or subclasses of RLMObject. See http://realm.io/docs/cocoa/api/Classes/RLMObject.html for more information.'
```

**Comment by segiddins** [comment]
Do you have any other subclasses of `Object` in your app?

**Comment by remotevision** [comment]
yes, i do. 

```
class Person: Object {
    dynamic var id = ""
    dynamic var name = ""
    dynamic var birthdate = NSDate()
    dynamic var male = true
    dynamic var created = NSDate()
    dynamic var triggers = [String]()
    
    dynamic var consent: Consent?
    let journalEntries = List<JournalEntry>()
}
```

**Comment by segiddins** [comment]
So the exception here is being thrown because of the `triggers` property -- Realm can't store arrays of strings at the moment.

**Comment by remotevision** [comment]
I wasn't even think about the other models since I'm only using that simple one. thanks @segiddins!!

**Comment by segiddins** [comment]
I'll look into making that exception message a bit more helpful too :+1:

**Comment by staticdreams** [comment]
I had the same exception yesterday when I upgrading my project to Swift 2.0.
Funny thing is it was working fine with Swift 1.2 (and maybe a bit earlier version of Realm). Has something changed internally in Realm?
It is really handy to have simple types like array (instead of ``List<T>`` in your model. For instance I was using [``ObjectMapper``](https://github.com/Hearst-DD/ObjectMapper) to automatically map JSON model to Realm model, but since it wont recognise the ``List`` type I have to do some of the mapping manually.
I found some other discussions here about getting simple arrays to work as properties, but is it still a planner feature?

**Comment by jpsim** [comment]
@staticdreams I'm working on improving this exception message in #2496. Support for arrays of primitives is being tracked in #1120.

**Comment by fxpage** [comment]
@segiddins Then how can I handle string arrays in my realm object?

**Comment by kishikawakatsumi** [comment]
@fxpage Currently, you need to wrap strings in `Object`, then storing as `List`. Like following:

```
class StringWrapper: Object {
    ...
    dynamic var string = ""
    ...
}

class Person: Object {
    ...
    let triggers = List<StringWrapper>()
    ...
}
```

**Comment by fxpage** [comment]
@kishikawakatsumi Thanks for your reply.

**Comment by fxpage** [comment]
@kishikawakatsumi But create a object for only one variable?
Is there any way to make it more simple?

**Comment by fxpage** [comment]
@kishikawakatsumi I did as you recommended, but now I got an error Property 'stringWrapper' has been added to latest object model.
What is the issue?

**Comment by staticdreams** [comment]
@fxpage I think it a migration issue. You need to either migrate your db or simple delete the db file and let you app recreate it.

**Comment by fxpage** [comment]
@staticdreams Thank you for your help.
