### ISSUE TITLE
Swift + Cocoapods -> " No such module 'Realm.Private' " error

### ISSUE THREAD

**Issue by redent** [realm/realm-cocoa#2367]
Steps to reproduce.

- Create an empty Swift project
- Add the following Podspec file:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!
    
    pod 'RealmSwift'

- Execute `pod install`.
- Open xcworkspace file in XCode.
- Compile

It raises the following error while in Aliases.swift, List.swift, Migration.Swift and Object.swift:

    No such module 'Realm.Private'

Is there any workaround to get it to work using cocoapods?

**Comment by segiddins** [comment]
What version of CocoaPods are you using? We have tests that ensure CocoaPods installation succeeds, and they're all currently passing.

**Comment by redent** [comment]
Not sure which version I was running, but after updating to 0.38.2 it's working fine. Sorry for the noise.

**Comment by segiddins** [comment]
No worries! Glad you were able to get everything working :)

**Comment by nafetswirth** [comment]
i had the same problem with CocoaPods 0.36.4 - resolved after updating to 0.38.2
