### ISSUE TITLE
Partial Date Query Support?

### ISSUE THREAD

**Issue by cody1024d** [realm/realm-cocoa#2369]
I'm interested in querying for my Model (let's call it ModelX) by a property on that model of type NSDate.

The complexity, though, is that I DON'T wan't to take into consideration the time of the NSDate object.

For example:

I want to query for all objects that occurred on 8/10/2015, regardless of what time of the day they occurred.

The only way I can think of doing this is by using a predicate, and find all ModelX's that have occurred between NSDates that represents 12:00 midnight (of 8/10/2015) and 11:59 PM (of 8/10/2015).

Is there a better practice for doing something like this?

**Comment by segiddins** [comment]
@cody1024d your best bet is to do exactly what you suggested -- constructing a predicate that makes those two comparisons.

**Comment by cody1024d** [comment]
@segiddins Ok, thank you very much!
