### ISSUE TITLE
Support types that conform to RawRepresentable

### ISSUE THREAD

**Issue by psophis** [realm/realm-cocoa#2375]
If I have a type that conforms to RawRepresentable I should be able to store that without storing the whole object.

**Comment by segiddins** [comment]
@psophis we agree that this would be awesome, and in fact, we're already tracking it over at https://github.com/realm/realm-cocoa/issues/921 :)

**Comment by psophis** [comment]
Thanks. Did a search for RawRepresentable and didn't see anything. Glad this is being worked on.
