### ISSUE TITLE
Allow omission of required properties in `initWithValue:`

### ISSUE THREAD

**Issue by MarcAudefroy** [realm/realm-cocoa#2377]
Hi!

In my project, I would initialize an RealmObject with a dictionary. This object has a primary key "identifier". When I use initWithValue with a dictionary (which does not contain identifier) in order to start fill the object, app crashes. Why? Because initWithValue validates each realmObject's property value. 

I see initWithValue like an init method but with "default values". Given that addObject method validates primaryKey or optional property. Why verify the property in the initWithValue method?

It's possible to use a method taking a dictionary or array variable and fill the realmObject without validating? 

Thanks.

**Comment by segiddins** [comment]
I believe this is the intended behavior, as it mirrors how `createWithValue:` works.

**Comment by MarcAudefroy** [comment]
Hum... it's seems inconsistent.

When I use createWithValue, I know I will save into realm. 

But with initWithValue, I just want to initialize the object. So, rules checking like property type are ok but rules checking like mandatory properties => not now.

**Comment by segiddins** [comment]
I personally don't find it inconsistent with `init`, since the promise there is that you will fill in all of the properties without default values. If you're not creating the object all in one go, just using `init` and manually setting properties is probably going to be the recommended approach.

**Comment by MarcAudefroy** [comment]
I use ```initWithValue``` if I want manipulate object after that but If I can't because of the rules checking, as well use ```createWithValue``` directly. On my opinion, ```init``` is just initialization, nothing others.  Do you understand?

But it's your choice and I accept it. It's just two different visions  :)

**Comment by jpsim** [comment]
I agree that `-[RLMObject initWithValue:]` shouldn't validate that all required properties are set at that point, so I'm adding this as a feature request.

**Comment by AliSoftware** [comment]
Wow that's really good news @jpsim :tada: Your comment just made my day!! :smiley: 

Having a huge JSON dictionary with only 1 or 2 key missing, it would really be a PITA to affect the properties and relationships (recursively) one by one manually… just because of this.  
And mutating the dictionary before calling `initWithValue:` (only workaround to far) is far from ideal either (string-typed + not this code's responsibility to know the JSON keys anyway)

I'm really looking forward for this change, would make much more sense to the API and our life much easier! :+1:

**Comment by JadenGeller** [comment]
@jpsim If I'm understanding correctly, this issue is requesting that required properties not be checked on initialization. The properties only ought to be required once added to a Realm. Is this correct?

**Comment by JadenGeller** [comment]
I imagine we should still validate the type at the very least since `initWithValue` avoids compile-time type checks.

**Comment by jpsim** [comment]
@JadenGeller your understanding is correct.
