### ISSUE TITLE
Does RealmSwift 0.94.1 not support "String?" anymore?

### ISSUE THREAD

**Issue by pvegh** [realm/realm-cocoa#2379]
I just updated RealmSwift (via CocoaPods) from 0.93.2 to 0.94.1 which crashes like this: 

```
Terminating app due to uncaught exception 'RLMException', reason: 'Only 'object' properties can be made optional, and property 'something' is of type 'any'.
If this is a 'String?' property, it must be declared as 'NSString?' instead.'
```
Not liking the idea to switch to "NSString?", I did that anyway just to see it. Which delivers just a slightly different error:
```
Terminating app due to uncaught exception 'RLMException', reason: 'Only 'object' properties can be made optional, and property 'something' is of type 'string'.'
```

I will probably find the solution the second after posting this, but since I saw a question on Stack too, I thought this could save time for others in that "worst case".

**Comment by segiddins** [comment]
Realm does not yet support optional types, but we did have a beta out a while back that did. For now, though, you either need to use a `String` or `NSString` property, until optional support is released.

**Comment by pvegh** [comment]
0.93.2 seems to have had support for optionals. A simple upgrade to the new version
-  pod 'RealmSwift', '0.93.2'
+  pod 'RealmSwift', '0.94.1'
makes the optionals support go away. Was 0.93 the beta you mentioned?

**Comment by segiddins** [comment]
No, 0.93 was not a beta, and it certainly didn't have support for optionals. My guess is that your `nil` strings were actually being stored as empty strings, in which case throwing an exception now is preferable, as it prevents the surprising thing from happening.

**Comment by pvegh** [comment]
Thanks for the info.
I think the first error message in my original post is incorrect then, because it says I should use "NSString?" instead of "String?" which only leads to another error message.
Maybe it should advise to use "String" instead of "String?"

**Comment by segiddins** [comment]
Yeah, the error message is changed in the wrong place -- I'll fix that, so thanks for pointing it out!
