### ISSUE TITLE
Realm 0.94.1 RLMAccessor.h file not found

### ISSUE THREAD

**Issue by Onetaway** [realm/realm-cocoa#2385]
I update to 0.94.1 Realm.    RLMAccessor.h file not found when compiled. How to fix it?  :)

**Comment by segiddins** [comment]
How are you installing realm? Have you tried cleaning before building?

**Comment by Onetaway** [comment]
I build with cocoa pods.  Using Realm   not RealmSwift, I have cleaned before building.   Xcode 6.4

**Comment by segiddins** [comment]
Please verify you're using CocoaPods 0.38.2.

Could you please try running the following and letting me know if it helps? Thanks!

```bash
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

**Comment by Onetaway** [comment]
Yep  It works. Problem solved. Thanks segiddins :+1:

**Comment by segiddins** [comment]
Glad to see you got everything working :)
