### ISSUE TITLE
Cannot find protocol declaration (v0.94.0 and v0.94.1)

### ISSUE THREAD

**Issue by tbeech** [realm/realm-cocoa#2386]
There seems to be an issue when declaring a RLMArray<Type>  property when the model classes are declared using their own .h files. The example below results in Xcode complaining that it cannot find the protocol declaration for 'ClassB'. I want to be able to split out the implementation into separate files vs. having one giant file.

I was finally able to solve my issue by creating a single .h describing the model interfaces, then putting each implementation into its own file. Maybe I missed it somewhere in the documentation? 

#### Example (Compiler Error)
ClassA.h
```objective-c
@interface ClassA : RLMObject
@property NSInteger id;
@property RLMArray<ClassB> *bObjects;
@end
```
ClassB.h
```objective-c
@interface ClassB : RLMObject
@property NSInteger id;
@end
RLM_ARRAY_TYPE(ClassB)
```

#### Example (No Compiler Error)
DataModel.h
```objective-c
@interface ClassA : RLMObject
@property NSInteger id;
@property RLMArray<ClassB> *bObjects;
@end

@interface ClassB : RLMObject
@property NSInteger id;
@end
RLM_ARRAY_TYPE(ClassB)
```

ClassA.m
```objective-c
@implementation Variable
@end
```
ClassB.m
```objective-c
@implementation Variable
@end
```

**Comment by segiddins** [comment]
Do you have an `#import "ClassB.h"` statement inside your `ClassA.h` file? If not, the compiler has no way of seeing that the `ClassB` protocol that's being declared by the `RLM_ARRAY_TYPE` macro exists.

**Comment by tbeech** [comment]
I just tried using the import vs. a forward declaration again and my build issues are gone. Perhaps my Xcode was just acting up earlier, because I swear I tried the import and it didn't work. This issue can be closed. Sorry for any inconvenience.

**Comment by segiddins** [comment]
No worries! Glad you were able to sort things out!
