### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ifeherva** [realm/realm-cocoa#2393]
I am using the cocoapods objective c version in my project and linking gives me hundreds of errors. Such as:

Undefined symbols for architecture x86_64:
"realm::BpTreeBase::write_subtree(realm::Array const&, unsigned long, unsigned long, unsigned long, realm::BpTreeBase::SliceHandler&, realm::_impl::OutputStream&)", referenced from:
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMResults.o)
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in librealm.a(RLMResults.o)
      realm::BpTree<long long, false>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(object_store.o)

osx 10.10, every other pod seems to work fine though. Any idea what linker option is missing? Thanks!

**Comment by segiddins** [comment]
@ifeherva this can sometimes happen when downloading Realm has failed. Can you try running the following for me, and installing again? Thanks!

```bash
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

**Comment by ifeherva** [comment]
I tried again on another computer where cocoapods were not even installed. The project is very simple, yet I get the same error.

**Comment by segiddins** [comment]
How did you install Realm on the non-CocoaPods machine?

**Comment by ifeherva** [comment]
I mean everything was freshly installed so there was no need to wipe the cache from ~/Library. Even though I tried again and same result.

**Comment by segiddins** [comment]
But did you also delete the `Pods` directory?

**Comment by tbaranes** [comment]
I'm getting the same error, I was just creating sample project to make a test on Realm for 10.10.
The project is just empty, just did a `pod install`. Also tried to remove everything link to cocoa pods and reinstall it.

Moreover, I'm already using in another project Realm with CocoaPods which is working well.

Podfile very simple:
```
source 'https://github.com/CocoaPods/Specs.git'
workspace './RealmTest.xcworkspace'
xcodeproj './RealmTest.xcodeproj'
inhibit_all_warnings!

platform :osx, '10.10'
pod 'Realm'
```

I can send the sample project if that can hep.

**Comment by segiddins** [comment]
@tbaranes yes, a sample project that demonstrates the issue would be very helpful!

**Comment by tbaranes** [comment]
Just sent at help@realm.io
Hope it helps

**Comment by segiddins** [comment]
OK, figured this out. The issue is that the CocoaPods static library is named `Realm`, and Realm is also linking against a static library called `realm` -- thanks to running on case-insensitive file systems, there's no way to link them both. The immediate fix for you (if possible) is to add the `use_frameworks!` flag to the `Podfile`, and I'll pull together a PR here with a less hacky fix.

**Comment by tbaranes** [comment]
I'm getting again this error on OSX using CocoaPods, but this time using RealmSwift. Any issues about it?

**Comment by HudiDev** [comment]
> @ifeherva this can sometimes happen when downloading Realm has failed. Can you try running the following for me, and installing again? Thanks!
> 
> ```shell
> rm -rf ~/Library/Caches/CocoaPods
> rm -rf Pods
> pod install
> ```



> @ifeherva this can sometimes happen when downloading Realm has failed. Can you try running the following for me, and installing again? Thanks!
> 
> ```shell
> rm -rf ~/Library/Caches/CocoaPods
> rm -rf Pods
> pod install
> ```

saved my day :)

**Comment by HudiDev** [comment]
> @ifeherva this can sometimes happen when downloading Realm has failed. Can you try running the following for me, and installing again? Thanks!
> 
> ```shell
> rm -rf ~/Library/Caches/CocoaPods
> rm -rf Pods
> pod install
> ```

saved my day :)

**Comment by hellowupeng** [comment]
> > @ifeherva this can sometimes happen when downloading Realm has failed. Can you try running the following for me, and installing again? Thanks!
> > ```shell
> > rm -rf ~/Library/Caches/CocoaPods
> > rm -rf Pods
> > pod install
> > ```
> 
> saved my day :)

save my day :)

**Comment by bbynog** [comment]
> @ifeherva this can sometimes happen when downloading Realm has failed. Can you try running the following for me, and installing again? Thanks!
> 
> ```shell
> rm -rf ~/Library/Caches/CocoaPods
> rm -rf Pods
> pod install
> ```

saved my day! thank you very much, mate!
