### ISSUE TITLE
missing required architecture armv7 in file RealmSwift on device

### ISSUE THREAD

**Issue by shahankit** [realm/realm-cocoa#2394]
I'm getting [this][1] long error for almost the files which are realm objects while compiling on device. I didn't get anywhere similar question.

[1]: http://pastebin.com/kP6mfJAg

**Comment by bigfish24** [comment]
@shahankit how have you installed RealmSwift in your project?

**Comment by shahankit** [comment]
Yeah bigfist24 I have and things are working great on simulator. Also I made a demo project and it worked fine on device. But it's giving me this weird error in my main project.

**Comment by bigfish24** [comment]
Did you install via Cocoapods, Carthage or just added the dynamic framework to your project?

**Comment by shahankit** [comment]
Using dynamic framework, the first method shown on getting started page.



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=shahankit2313@gmail.com&idSignature=22>

On Thu, Aug 13, 2015 at 10:58 PM, Adam Fish <notifications@github.com>
wrote:

> Did you install via Cocoapods, Carthage or just added the dynamic
> framework to your project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2394#issuecomment-130770987>.
>



-- 
Ankit Shah

**Comment by bigfish24** [comment]
If you go to the "General" section in your target settings, is Realm & RealmSwift included in Embedded Binaries section?

**Comment by shahankit** [comment]
Yeah Realm and RealmSwift both are there in Embedded binaries. I used the
first method only and have also included the Run Script.




On Thu, Aug 13, 2015 at 11:06 PM, Adam Fish <notifications@github.com>
wrote:

> If you go to the "General" section in your target settings, is Realm &
> RealmSwift included in Embedded Binaries section?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2394#issuecomment-130773209>.
>



-- 
Ankit Shah

**Comment by bigfish24** [comment]
Ok, can you let me know what your build settings are for the following:

`Build Active Architecture Only`
`Valid Architectures`

**Comment by shahankit** [comment]
Build Active Architectures only:
Debug: Yes
Release: No
Valid architectures : arm64 armv7


On Thu, Aug 13, 2015 at 11:10 PM, Adam Fish <notifications@github.com>
wrote:

> Ok, can you let me know what your build settings are for the following:
>
> Build Active Architecture Only
> Valid Architectures
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2394#issuecomment-130775049>.
>



-- 
Ankit Shah

**Comment by bigfish24** [comment]
What is the path in `Framework Search Paths` in your build settings?

**Comment by shahankit** [comment]
$(PROJECT_DIR)
$(inherited)
$(PROJECT_DIR)/Frameworks




On Thu, Aug 13, 2015 at 11:49 PM, Adam Fish <notifications@github.com>
wrote:

> What is the path in Framework Search Paths in your build settings?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2394#issuecomment-130787495>.
>



-- 
Ankit Shah

**Comment by bigfish24** [comment]
Can you make sure the RealmSwift framework is in the folder for one of those paths?

**Comment by shahankit** [comment]
Yes I can because if it isn't then I would get a error because of Run
script phase but there is no such error.




On Thu, Aug 13, 2015 at 11:56 PM, Adam Fish <notifications@github.com>
wrote:

> Can you make sure the RealmSwift framework is in the folder for one of
> those paths?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2394#issuecomment-130789771>.
>



-- 
Ankit Shah

**Comment by bigfish24** [comment]
Which version of Realm are you using?

**Comment by shahankit** [comment]
1.2

On Fri, Aug 14, 2015 at 12:12 AM, Adam Fish <notifications@github.com>
wrote:

> Which version of Realm are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2394#issuecomment-130796759>.
>



-- 
Ankit Shah

**Comment by bigfish24** [comment]
Sorry which release version of Realm are you using such as 0.94.1?

**Comment by shahankit** [comment]
0.94.1





On Fri, Aug 14, 2015 at 12:15 AM, Adam Fish <notifications@github.com>
wrote:

> Sorry which release version of Realm are you using such as 0.94.1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2394#issuecomment-130797918>.
>



-- 
Ankit Shah

**Comment by bigfish24** [comment]
Can you make sure you are using the iOS Realm and RealmSwift frameworks and not the OS X versions?

**Comment by shahankit** [comment]
Tell me how do you want me to make sure, because things are working fine
with simulator? You want me repeat installations steps and try out or is it
ok because it's working fine on simulator and confirm that I'm using ios
versions only (Although I perfectly remember that I've done that only)?




On Fri, Aug 14, 2015 at 2:37 AM, Adam Fish <notifications@github.com> wrote:

> Can you make sure you are using the iOS Realm and RealmSwift frameworks
> and not the OS X versions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2394#issuecomment-130845254>.
>



-- 
Ankit Shah

**Comment by bigfish24** [comment]
I would recommend you remove the frameworks and drag the iOS frameworks back in and retry running on the device.

**Comment by shahankit** [comment]
@bigfish24 Things got fixed I was mistakenly using 0.94.0 instead of 0.94.1.
