### ISSUE TITLE
Invalid Executable - Realm.framework/Realm contains bitcode

### ISSUE THREAD

**Issue by mcvasquez** [realm/realm-cocoa#2397]
I'm trying to upload my app to app store but my builds on iTunes Connect shows this message: 
> "Invalid Binary".

I received an email with this message: 
> "Invalid Executable - The executable 'MyApp.app/Frameworks/Realm.framework/Realm' contains bitcode"

I'm using Realm-Swift 0.94.1 with CocoaPods on Xcode 6.4 Swift 1.2.

**Comment by segiddins** [comment]
@mcvasquez given that you're using CocoaPods and Xcode 6.4, it's very odd that the produced framework even includes bitcode
(It's also odd that including bitcode would make it 'invalid', since bitcode is just another section of the executable)

**Comment by mcvasquez** [comment]
@segiddins do I have to downgrade to 0.93.2? Because don't have bitcode support.

One more thing, each time I run my app the console shows me: 
> Version 0.94.0 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v0.94.0/CHANGELOG.md

But I've installed 0.94.1. Can be this related to my problem?

**Comment by segiddins** [comment]
@mcvasquez no, that message is unrelated -- looks like our release process just forgot to update a file on S3. You shouldn't have to downgrade at all, but we need to do a bit of investigating to determine why you're experiencing app store submission issues. Are you integrating via CocoaPods as a static library or as a dynamic framework?

**Comment by mcvasquez** [comment]
@segiddins As a dynamic framework.

**Comment by segiddins** [comment]
@mcvasquez could you share the output of running the following command?
`xcodebuild -showBuildSettings | grep -i bitcode`

**Comment by mcvasquez** [comment]
@segiddins below the message:

>2015-08-13 22:44:47.963 xcodebuild[33387:237031] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
objc[33387]: Class XCBuildConfiguration is implemented in both /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore and /Users/mcvasquez/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster. One of the two will be used. Which one is undefined.

**Comment by segiddins** [comment]
(See also https://github.com/realm/realm-cocoa/issues/2399 for more details)

**Comment by tgoyne** [comment]
https://static.realm.io/downloads/temp/realm-core-0.92.1-no-bitcode.tar.bz2 has a build of the core library built without bitcode enabled. While we're sorting out a proper fix, you should be able to replace the automatically downloaded copy of `librealm-ios.a` in the `Pods/Realm` directory with the one from there and have things work.

**Comment by tgoyne** [comment]
Where does it say "Invalid Binary"? I uploaded a simple app using RealmSwift via CocoaPods and Xcode 6.4, and iTC appears to have accepted it and I can submit the build for review.

**Comment by mcvasquez** [comment]
@tgoyne in Prerelease tab.

**Comment by strongwillow** [comment]
Go to build settings, in user-defined, set ENABLE_BITCODE to NO

**Comment by mcvasquez** [comment]
@strongwillow that option is not available on Xcode 6.4.

**Comment by strongwillow** [comment]
If it's not there, add one.

<img width="515" alt="capture d ecran 2015-08-17 a 16 54 26" src="https://cloud.githubusercontent.com/assets/359745/9307812/eb3ad0d2-4500-11e5-8015-4f2f1470f15d.png">

**Comment by tgoyne** [comment]
I tried explicitly enabling bitcode in Xcode 7, then building and submitting with Xcode 6.4, and iTC still accepts it and lets me invite internal testers and submit for beta app review. For good measure I tried lowering the deployment target to 8.0 in case 8.3 was required for bitcode or something, and that doesn't seem to have made any difference.

Building and submitting with Xcode 7 also works (with bitcode explicitly enabled), but gives the banner that says that it can't be sent to external testers due to being submitted with a prerelease version.

**Comment by jpsim** [comment]
To recap, it seems this issue happens if `ENABLE_BITCODE` is set to `YES` in your Build Settings (or the `-fembed-bitcode` compiler flag set) while submitting an app via Xcode 6, and that either setting `ENABLE_BITCODE` to `NO` and/or removing the `-fembed-bitcode` compiler flag is sufficient to disable the bitcode check in the app submission process.

Is that right? Unless I'm missing something, I'd say this issue can be closed.

**Comment by tgoyne** [comment]
No. I wasn't able to get it to happen by setting `ENABLE_BITCODE` to `YES` and then building/submitting with Xcode 6 (and manually passing -fembed-bitcode makes it fail to compile at all with Xcode 6).

**Comment by segiddins** [comment]
@tgoyne, I can't remember if you ever managed to figure out what was going on here, but I think we can safely close this issue?
