### ISSUE TITLE
ios/swift/RealmExamples.xcodeproj is missing its project.pbxproj file

### ISSUE THREAD

**Issue by phatblat** [realm/realm-cocoa#2400]
The `RealmExamples.xcodeproj` in [examples/ios/swift](https://github.com/realm/realm-cocoa/tree/master/examples/ios/swift) looks like it was checked in without the underlying project.pbxproj file. Normally, this would be a minor issue (not being able to build the examples), but this actually breaks the build when Realm is built using Carthage. 

```
xcodebuild: error: Unable to read project 'RealmExamples.xcodeproj' from folder 'APP_PATH/Carthage/Checkouts/realm-cocoa/examples/ios/swift'.
	Reason: Project APP_PATH/Carthage/Checkouts/realm-cocoa/examples/ios/swift/RealmExamples.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```

`xcodebuild` is generating the error due to this corrupted project which fails the Carthage build, which is really just trying to find shared schemes to build.

Can this RealmExamples project be fixed or removed? Thanks!

**Comment by segiddins** [comment]
@phatblat this was caused by a bad merge, but I'm shocked to see that an issue with the example project is causing carthage to be unable to build `Realm.xcodeproj` ?

**Comment by phatblat** [comment]
This is from carthage [0.8](https://github.com/Carthage/Carthage/releases) which has a change related to inspecting projects, looking for framework targets. So, quite possible that it's due to some of this new behavior in carthage.
