### ISSUE TITLE
How to use min on Results?

### ISSUE THREAD

**Issue by shahankit** [realm/realm-cocoa#2402]
I have results as `let todo = realm.objects(ToDoItem)`. How do I use `.min()` function. The documentation says passing a String parameter, but I'm not getting how? Can you please add some examples of this in Getting Started guide one with Dog and Person example.

**Comment by segiddins** [comment]
@shahankit we definitely can improve the docs, but you use the `min` method by passing in the name of the property you wish to get the minimum of. For example, `realm.objects(Person).min("age")` would return the minimum age of all the people (and not the youngest person).

**Comment by shahankit** [comment]
`realm.objects(Person).min("age")` fails to compile. Cannot invoke min with type '(String)'. http://postimg.org/image/5p5h2t8uf/

**Comment by kishikawakatsumi** [comment]
It is required to specify the data type, like below:

```
let min: Int? = realm.objects(Person).min("age")
```
