### ISSUE TITLE
Build Errors in 0.94.1

### ISSUE THREAD

**Issue by jovito-royeca** [realm/realm-cocoa#2404]
Realm 0.94.1 is not compiling with Cocoapods. I have an OS X CLI project with Objective-C and here is the error: (There are actually 197 errors)

Undefined symbols for architecture x86_64:
"realm::BpTreeBase::replace_root(std::__1::unique_ptr >)", referenced from:
realm::Column::replace_root_array(std::__1::unique_ptr >) in libRealm.a(RLMArray.o)
realm::BpTree::clear() in libRealm.a(RLMArray.o)
realm::BpTree::EraseHandler::replace_root_by_leaf(realm::MemRef) in libRealm.a(RLMArray.o)
realm::BpTree::EraseHandler::replace_root_by_empty_leaf() in libRealm.a(RLMArray.o)
realm::Column::replace_root_array(std::__1::unique_ptr >) in libRealm.a(RLMObject.o)
realm::BpTree::clear() in libRealm.a(RLMObject.o)
realm::BpTree::EraseHandler::replace_root_by_leaf(realm::MemRef) in libRealm.a(RLMObject.o)
...
"realm::BpTreeBase::write_subtree(realm::Array const&, unsigned long, unsigned long, unsigned long, realm::BpTreeBase::SliceHandler&, realm::_impl::OutputStream&)", referenced from:
realm::BpTree::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMArray.o)
realm::BpTree::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMObject.o)
realm::BpTree::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMObjectBase.o)
realm::BpTree::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMObjectSchema.o)
realm::BpTree::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMArrayLinkView.o)
realm::BpTree::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMResults.o)
realm::BpTree::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in libRealm.a(RLMRealmUtil.o)

**Comment by bdash** [comment]
This looks to be the same as #2393.

> The issue is that the CocoaPods static library is named Realm, and Realm is also linking against a static library called realm -- thanks to running on case-insensitive file systems, there's no way to link them both. The immediate fix for you (if possible) is to add the use_frameworks! flag to the Podfile, and I'll pull together a PR here with a less hacky fix.
