### ISSUE TITLE
Performance: Swift API is a lot slower the ObjC API (?)

### ISSUE THREAD

**Issue by itchingpixels** [realm/realm-cocoa#2405]
Hello,

I have been doing some basic comparison between Realm and SQLite, and in the meantime, I found that the Swift API is a lot slower in certain cases (query + insert?).
https://github.com/itchingpixels/realm-vs-sqlite

Am I doing something wrong? Are you guys aware of this?

Thanks a lot!

**Comment by tgoyne** [comment]
Some performance differences are expected, but insertions taking twice as long with RealmSwift is definitely worse than expected, and I don't see anything obviously wrong with your benchmarking code. The other two tests took roughly the same amount of time for me.

**Comment by tgoyne** [comment]
Difference appears to be due to `RealmSwift.Object`'s handling of `List` properties in `valueForKey()` significantly hurting the non-List property case. Should be simple to fix.
