### ISSUE TITLE
writeCopyToPath returns "open() failed: No such file or directory"

### ISSUE THREAD

**Issue by switchCTRL** [realm/realm-cocoa#2406]
Hey, 

i am trying to save my realm file to a given Path but always get open() failed: No such file or directory. Can you give an example how to save the realm file on os x?

**Comment by segiddins** [comment]
@switchCTRL do you have permissions to read and write to the given path?

**Comment by tgoyne** [comment]
"No such file or directory" suggests that the directory you're trying to write to doesn't exist. Realm doesn't create any containing directories in the path automatically.

**Comment by switchCTRL** [comment]
I know what no such file or directory mean ;) Yes i think i have the permissions, the directory is the desktop.

**Comment by switchCTRL** [comment]
I have tryed to get the path with an NSOpenPanel to select a folder... I also tryed other directorys...

**Comment by switchCTRL** [comment]
I have found a solution by setting the path from an NSURL. (openPanel.URL!.relativePath! + "/realm.realm")
