### ISSUE TITLE
Accessing objects across multiple threads (Documentation) [Swift 2.0] 

### ISSUE THREAD

**Issue by pranavss11** [realm/realm-cocoa#2411]
How is realm supposed to handle saving and returning objects across multiple threads?

say I have an object that I want to save it without blocking the main thread, so I do something like this:
```
class Helper {
    let queue = dispatch_queue_create("MyQueue", DISPATCH_QUEUE_CONCURRENT)

    func testSave() {
        let object = Object()
        object.name = "test"

        save(object, { () -> Void in 
        }
    }
    func save(object: Object, completion:() -> Void) {

        dispatch_async(self.queue) { () -> Void in
            let realm = try! Realm()
            
            realm.write {
                realm.add(object, update: true)
            }
            dispatch_async(dispatch_get_main_queue(), { () -> Void in
                completion()
            })
        }
    }
}
```

My question is this: If I wanted to return this object to another method, how do I return the Results<Object> that is used by Realm? Should I be doing a fetch on the main thread after the write is complete?

**Comment by bdash** [comment]
Yes, if you want to use the object from the main thread you'll need to do a fetch on the main thread after the write is complete. You can add a primary key to your class to make it easy to retrieve the object from the main thread.

**Comment by jpsim** [comment]
We've added more documentation about threading considerations in Realm: https://realm.io/docs/objc/latest/#threading and https://realm.io/docs/swift/latest/#threading.

**Comment by pranavss11** [comment]
@bdash following up to this question. If instead of creating the object, I have an instance of the object that is fetched from realm, will I need to refetch that in the background, then update that, and the refetch on main thread? 

Updated example:

```
class Helper {
        let queue = dispatch_queue_create("MyQueue", DISPATCH_QUEUE_CONCURRENT)
        
        func testSave() {
            let object = Object()
            object.name = "test"
            
            save(object, { result in
            }
        }
        
        func testSaveFetchedObject() {
            let realm = try! Realm()
            let object = self.findObjectInMainRealm("1234")
            object.name = "new name"
            
            save(object, { result in
                
            })
        }
        
        func findObjectInMainRealm(id: String) -> Result {
            ////
            dispatch_async(dispatch_get_main_queue(), {
                let realm = try! Realm()
                realm.refresh()
                
                guard let object = realm.objectForPrimaryKey(SEOrganizer.self, key: originalObject.slug) else {
                    let error = NSError(domain: ShuddleEngineErrorDomain, code: ShuddleEngineErrors.SaveFailed.rawValue, userInfo: nil)
                    return result(.Failure(error))
                }
                return result(.Success(object))
            })
        }
        
        func save(originalObject: Object, completion:(Result) -> Void) {
            dispatch_async(self.queue) { () -> Void in
                let backgroundRealm = try! Realm()
                backgroundRealm.refresh()
                
                guard let backgroundObject = backgroundRealm.objectForPrimaryKey(Object.self, key: originalObject.id) else {
                    try! backgroundRealm.write({
                        backgroundRealm.add(originalObject)
                    })
                    
                    completion(findObjectInMainRealm(originalObject.id))
                    
                    return
                    
                }
                
                try! backgroundRealm.write( {
                    backgroundRealm.add(backgroundObject, update: true)
                })
                
                completion(findObjectInMainRealm(originalObject.id))
                
            }
        }
    }

```

**Comment by jpsim** [comment]
To do this right, you'll need proper thread handover of objects, which is tracked in #3136

**Comment by pranavss11** [comment]
@jpsim that looks like it's currently backlogged. If I was shipping this today, what would be the recommended way of doing this?

**Comment by jpsim** [comment]
> If I was shipping this today, what would be the recommended way of doing this?

We outline some strategies in the [Threading](https://realm.io/docs/objc/latest/#threading) section of our docs.

**Comment by donaldking** [comment]
I'm experiencing some really slow reads / updating UI when scrolling over large data set. Should the reads be done on the background thread? or main thread?

**Comment by jpsim** [comment]
@donaldking reads should be done on the thread that need that data, and since you appear to be using Realm to populate your UI, that implies reads should be done on the main thread.
