### ISSUE TITLE
RealmConfiguration missing in latest swift2.0 branch?

### ISSUE THREAD

**Issue by pvegh** [realm/realm-cocoa#2413]
Cocoapod from swift-2.0 branch
Xcode 7 Beta 5
-> Build fails

Seems like the RealmConfiguration.swift file is deleted after the pod update. Is that correct or am I missing something?

**Comment by pvegh** [comment]
Might also help:

Pods/RealmSwift/RealmSwift/RealmConfiguration.swift:129:40: Use of undeclared type 'RLMRealmConfiguration'

Pods/RealmSwift/RealmSwift/Realm.swift:90:9: Use of unresolved identifier 'RLMRealmAddPathSettingsToConfiguration'

Pods/RealmSwift/RealmSwift/Realm.swift:540:9: Use of unresolved identifier 'RLMRealmSetEncryptionKeyForPath'

**Comment by segiddins** [comment]
Could you please ensure you're also using realm from the swift-2.0 branch as well? Thanks!

**Comment by pvegh** [comment]
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'

"Realm" is automatically pulled as a dependency of RealmSwift as far as I know Cocoapods?

**Comment by pvegh** [comment]
Adding the line:
```
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
```
seems to have fixed the issue. Thanks for the hint!
