### ISSUE TITLE
Backlink migration

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#2414]
Hi!
Using Realm 0.94.1, Xcode 6.

Imagine we have two classes: Person and Dog, with a one-to-many relationship, the only thing that Dog doesn't know about the person. 
And I wish to make a migration that will add a Person property to Dog class.

Before I post what i've tried so far, I guess it's worth asking first: did you guys implement such possibility?

**Comment by tgoyne** [comment]
Add the property, then in your migration block do something like the following:

```
[migration enumerateObjects:@"Dog" block:^(RLMObject *oldObject, RLMObject *newObject) {
    newObject[@"person"] = [newObject linkingObjectsOfClass:@"Person" forProperty:@"dogs"].firstObject;
}];
```

**Comment by tgoyne** [comment]
Or if you want to use a computed property for the backlink rather than storing it, no migration is needed.

**Comment by OlegAnghelov** [comment]
@tgoyne 
By computed property do you mean this part of the documentation:
https://realm.io/docs/objc/latest/#relationships in the `Inverse Relationships` section, with readonly properties?

**Comment by segiddins** [comment]
@OlegAnghelov yup, that's exactly it!

**Comment by OlegAnghelov** [comment]
The migration worked perfectly. I missed the "firstObject" part.
Thanks a lot :)

But the backlink should be managed manually? (on adding/removing objects from each other)

On Person-Dog example:
When we add the dog to `dogs`, we manually set `dog.owner = self`, and when removing we should take care to set `dog.owner = nil`.
Is it correct way to implement this?

**Comment by segiddins** [comment]
If you want explicit backlinks, then yes, you'll have to manage them yourself.

**Comment by OlegAnghelov** [comment]
Are there any performance differences? For example would the computed properties be slower that the fully managed that stored in DB/memory?

**Comment by segiddins** [comment]
There shouldn’t be any performance difference other than that you are doing double bookkeeping (since the implicit backlinks are maintained anyways). So that will affect performance of any updates. It will also take up more space, but the effect of that is probably minimal.

The benefit is obviously that you can do regular queries on both sides, instead of having to use the special backlink methods.

**Comment by OlegAnghelov** [comment]
Great, thanks a lot for great support!
I guess we can close the issue?
