### ISSUE TITLE
Delay in Object's Persisting

### ISSUE THREAD

**Issue by aksharbonu** [realm/realm-cocoa#2415]
Say if I make a change to an object x in dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), after it is completed, if I try to access the object after calling [Class objectForPrimaryKey: ***], the changes don't seem to be there...

Is there something I'm doing wrong / not aware of?

**Comment by segiddins** [comment]
You might need to manually refresh the realm on the new thread after the write if the realm did change notification hasn't been sent yet.

**Comment by aksharbonu** [comment]
Did the trick for me.
