### ISSUE TITLE
Using filter on List.

### ISSUE THREAD

**Issue by shahankit** [realm/realm-cocoa#2425]
I queried the database and got Results<Type> object. I used the following to convert it to List because feel that more comfortable:
```    
let listFromResults = List<Type>()
listFromResults.extend(resultObject)
```

Now when I try to use `listFromResults.filter(typeName == 'xyz')` I get an error stating `This method can only be called on RLMArray instances retrieved from an RLMRealm`. Is there any other way to filter List?

**Comment by segiddins** [comment]
You should be filtering the Results -- List instances are only meant to be used as Object properties.

**Comment by shahankit** [comment]
Ok then where does the `filter` method on List help out for?

**Comment by segiddins** [comment]
When the List is a property on an object that you get from a Realm

**Comment by shahankit** [comment]
ok so suppose I have ToDoItem containing list of comments. Then I can use filter on comments is it so?
