### ISSUE TITLE
It is now supports Schemas

### ISSUE THREAD

**Issue by yaming116** [realm/realm-cocoa#2431]

**Comment by jpsim** [comment]
Hi @yaming116, do you have a question?

**Comment by yaming116** [comment]
Hi, @jpsim . It is support schemas , like Android .Unlike now all the tables are in a database inside

**Comment by jpsim** [comment]
If you're asking if it's possible to only store a subset of RLMObject subclasses in a given Realm, that functionality was just merged to master from #2401 and will be in our next release.

**Comment by yaming116** [comment]
ok,thx
