### ISSUE TITLE
Incompatibility between Realm Browser v0.93 and v0.94 App in Simulator

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-cocoa#2432]
This was an issue originally posted in Realm Browser's repo (https://github.com/realm/realm-browser-osx/issues/52 courtesy of @lionpants), but after testing it out, it's looking like a bug in Realm Cocoa and/or the Core.

The bug is this: When an iOS app running Realm 0.94 is opened in iOS Simulator, and the App Store version of Realm Browser (running Realm 0.93) has the same .realm file open, upon performing a write transaction in the app, Realm Browser will crash. If a new copy of Realm Browser is built, integrating Realm 0.94, and the same process is repeated, the issue is resolved.

Since there was apparently no breaking changes made to the file format between these two versions, this may be indicative of some kind of regression.

@lionpants has provided this [sample test app](http://puu.sh/jNEP4/a9f80e9d8f.zip), and laid out the following steps to reproduce:

* Start the app in iOS Simulator.
* Click the "Do Things" button, this will insert 10000 Animals into the Realm DB.
* Open the copy of [Realm Browser from the App Store](https://itunes.apple.com/app/realm-browser/id1007457278).
* Open the Realm DB file for the TestApp in Realm Browser.
* You should see the 10000 Animals and 4 Food objects.
* Press the "Do Things" button again.
* Realm Browser should crash.

I've tested this issue myself and confirmed that these reproduction steps end in a crash.

**Comment by segiddins** [comment]
Could this possibly be happening in the `TransactLogAdvancer`? I think we might have renumbered some of the operation enums, which _might_ explain this.

**Comment by TimOliver** [comment]
Where's `TransactLogAdvancer` at?

**Comment by segiddins** [comment]
Ah my bad, it's actually `TransactLogParser`, in `transact_log.cpp` in core.

**Comment by tgoyne** [comment]
The write logs are currently explicitly not portable between versions of Realm, so it's not expected to work. It'd be good to have some better way to check that and report it to the user rather than just crashing, though.

**Comment by jpsim** [comment]
Since this is now being tracked in core (https://github.com/realm/realm-core/issues/1052), there's no need to maintain this version of the issue.
