### ISSUE TITLE
RLMCheckForUpdates() and RLMSendAnalytics() are OK with ATS?

### ISSUE THREAD

**Issue by StanislavK** [realm/realm-cocoa#2433]
For Xcode 7b (ios9) and Swift 2, the following is shown when an app is run in the simulator:

```
  NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)  
```

i.e. it seems, that for functions `RLMCheckForUpdates()` and `RLMSendAnalytics()` the requested urls are not ATS (App Transport Security) compliant?

PS: The above warning/error can be disabled by setting up env. variables `REALM_DISABLE_ANALYTICS` and `REALM_DISABLE_UPDATE_CHECKER` in Xcode.

**Comment by jpsim** [comment]
Thanks for reporting this, @StanislavK. I can reproduce this, but what's odd is that TLSv1.2 *is* being used for the URL connections, and according to Apple's documentation on ATS, connections made via that TLS protocol shouldn't need to be explicitly whitelisted. I'm looking into this now and will report back my findings.

**Comment by jpsim** [comment]
Actually, it looks like even though the https://static.relam.io server (AWS S3 via Cloudflare) supports TLS 1.2, it serves using TLS 1.1 by default.

**Comment by bdash** [comment]
You can use `nscurl --ats-diagnostics https://static.realm.io/update/cocoa` to see which aspect of the ATS verification is failing. The issue appears to be only the lack of advertised ciphers supporting perfect forward secrecy. If `NSExceptionRequiresForwardSecrecy` is specified as false, the connection succeeds.

**Comment by bdash** [comment]
The SSL Labs [SSL Server Test results](https://www.ssllabs.com/ssltest/analyze.html?d=static.realm.io&s=108.162.203.182&hideResults=on) show a number of ciphers supported by static.realm.io that are on the [App Transport Security whitelist](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/index.html#//apple_ref/doc/uid/TP40016240-CH1-SW2). I'm not sure why ATS is rejecting them.

**Comment by bdash** [comment]
A [post](https://forums.developer.apple.com/message/41025#41025) on the Apple developer forums indicates that `NSExceptionRequiresForwardSecrecy` currently unintentionally disables the requirement that the SSL certificate be signed using SHA-256 or greater. The SSL Server Test results indicate that the certificate is using SHA1.

**Comment by jpsim** [comment]
Nice find! So it seems like the appropriate solution is to use an SSL certificate signed using SHA-256 or greater, which would have to be done in Cloudflare, so I'm working on doing that now.

@StanislavK are you sure you're seeing similar issues with `RLMSendAnalytics()`? I don't see any ATS issues when running in an app, and here's what `nscurl --ats-diagnostics https://api.mixpanel.com/track` gives me:

```
Starting ATS Diagnostics

Configuring ATS Info.plist keys and displaying the result of HTTPS loads to https://api.mixpanel.com/track.
A test will "PASS" if URLSession:task:didCompleteWithError: returns a nil error.
Use '--verbose' to view the ATS dictionaries used and to display the error received in URLSession:task:didCompleteWithError:.
================================================================================

Default ATS Secure Connection
---
ATS Default Connection
Result : PASS
---

================================================================================

Allowing Arbitrary Loads

---
Allow All Loads
Result : PASS
---

================================================================================

Configuring TLS exceptions for api.mixpanel.com

---
TLSv1.2
Result : PASS
---

---
TLSv1.1
Result : PASS
---

---
TLSv1.0
Result : PASS
---

================================================================================

Configuring PFS exceptions for api.mixpanel.com

---
Disabling Perfect Forward Secrecy
Result : PASS
---

================================================================================

Configuring PFS exceptions and allowing insecure HTTP for api.mixpanel.com

---
Disabling Perfect Forward Secrecy and Allowing Insecure HTTP
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled for api.mixpanel.com

---
TLSv1.2 with PFS disabled
Result : PASS
---

---
TLSv1.1 with PFS disabled
Result : PASS
---

---
TLSv1.0 with PFS disabled
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled and insecure HTTP allowed for api.mixpanel.com

---
TLSv1.2 with PFS disabled and insecure HTTP allowed
Result : PASS
---

---
TLSv1.1 with PFS disabled and insecure HTTP allowed
Result : PASS
---

---
TLSv1.0 with PFS disabled and insecure HTTP allowed
Result : PASS
---

================================================================================
```

**Comment by StanislavK** [comment]
@jpsim - you are right. I have double checked* and the behaviour is not related to the `RLMSendAnalytics()`!

\* i.e. the warning related to ATS is showed (even) when the following env. variable is set up:

`REALM_DISABLE_ANALYTICS` TRUE

**Comment by StanislavK** [comment]
Setting up Xcode env. variable `CFNETWORK_DIAGNOSTICS` to 3 creates a log with an extended info where you can see URL that causes NSAppTransportSecurity to block a request.

See https://developer.apple.com/library/ios/qa/qa1887/_index.html.
(thanks to @soffes tweet)

**Comment by soffes** [comment]
<3

**Comment by jpsim** [comment]
https://static.realm.io is now using an SSL certificate signed with SHA256 so Realm is now fully compatible with iOS 9's App Transport Security. See most recent [SSL Server Test results](https://www.ssllabs.com/ssltest/analyze.html?d=static.realm.io&s=104.20.12.57&hideResults=on).
