### ISSUE TITLE
Update KVO mention in current limitations section on website

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#2439]
"KVO is not supported
Realm doe not support KVO yet but has its own notification mechanism (see Notifications). We are working to add KVO support at the moment: see Github issue #601."

**Comment by segiddins** [comment]
I'm not seeing this on https://realm.io/docs/objc/latest/#current-limitations

**Comment by yoshyosh** [comment]
Ah oops, it was just on the Swift version. I'll update the typo in the swift docs

**Comment by yoshyosh** [comment]
Nm, KVO is missing from the swift docs

**Comment by yoshyosh** [comment]
"See the docs for Objective-C or [Swift](https://realm.io/docs/swift/latest/#key-value-observation) for more information on KVO with Realm" in the blog post

The swift link leads to a dead link since there is no section for that

**Comment by segiddins** [comment]
Just fixed this -- thanks for the heads up @yoshyosh !
