### ISSUE TITLE
Cannot save object with RLMArray property - nil

### ISSUE THREAD

**Issue by apassant** [realm/realm-cocoa#2443]
Trying to save objects with nil values, so I'm using the `null-string-beta-2` branch. I can properly save nil values for NSStrings, but it fails for RLMArray properties.

Here's my model:

    @interface User : RLMObject
    @property NSString *name;
    @property RLMArray<User> *friends;
    @end

Creating a new user instance:

    User *user = [[User alloc] init];
    user.name = @"alex";
    user.friends = nil;

Saving the user:

    2015-08-26 00:36:25.748 YapMe[58301:897478] *** Terminating app due to uncaught exception 'RLMException', reason: 'No value or default value specified for property 'friends' in 'User''

I though that nil values were supported for RLMObject - isn't that the case for RLMArray?

**Comment by segiddins** [comment]
@apassant at the moment, `nil` values are only supported for `RLMObject` properties -- we haven't even decided yet if `nil` `RLMArray` properties are something that we want to support.

**Comment by apassant** [comment]
@segiddins My bad, so I guess I misunderstood the docs. I think that would be a helpful addition, toi avoid creating RLMObjects that are simply array containers (which seems to be the current workaround?)

    @interface User : RLMUserArray
    @property RLMArray<User> *users;
    @end

    @interface User : RLMObject
    @property NSString *name;
    @property RLMUserArray *friends;
    @end

Do you also have an ETA re. merging null-string-beta-2 with the master branch? As currently using nil values for string prevents via null-string-beta-2 from using the latest features or the master.

**Comment by segiddins** [comment]
Actually, the code for null is merged, but has been disabled via a feature flag. We have some things to work out before we enable it, but I don't have an eta on shipping proper null support, sorry.

**Comment by apassant** [comment]
No problem, thanks for the notice!
