### ISSUE TITLE
Framework targeting WatchOS tries to link against iOS

### ISSUE THREAD

**Issue by mattdelves** [realm/realm-cocoa#2453]
Hi,
I have a framework in my iOS app that has been duplicated so that it can target both iOS 9 and watchOS 2. I believe (though am not certain) that this is according to the apple doc https://developer.apple.com/library/prerelease/watchos/documentation/General/Conceptual/AppleWatch2TransitionGuide/ConfiguretheXcodeProject.html

While I am using Carthage in the app, I've built realmswift.framework for iOS and watchOS using the build.sh script and placed these frameworks in the corresponding carthage directories.

I've then added the realm and realm swift frameworks to the shared framework. It manages to build the iOS app correctly though fails to build the watchOS app.

Any help in this would be greatly appreciated.

Thanks,
Matt.

**Comment by mattdelves** [comment]
So a bit more of a follow up having done some more investigation. I removed the iOS version of the Realm and RealmSwift frameworks from the project and the watchOS started building correctly.

Could it be that Xcode is finding the first Realm.framework or RealmSwift.framework and just using that rather than the one which is for the correct target?

**Comment by mattdelves** [comment]
Okay, so the issue was due to the framework search path being incorrectly set. Closing the issue now.

**Comment by segiddins** [comment]
@mattdelves glad to see you got things working!

**Comment by justinging** [comment]
Would you give some guidelines on how to make it working in both IOS9 & WatchOS2 at the same time?
Where should the frameworks be located?

Thanks!
