### ISSUE TITLE
Sematic Issues

### ISSUE THREAD

**Issue by vlonjatg** [realm/realm-cocoa#2454]
So I have this Objective-C project that also has some Swift files. So I'm planning to use Realm inside this project but do all the work in the Swift files (that's how the project is set up).

So I went ahead and imported Realm.framework and also RLMSupport.swift. But when I build, I'm getting these errors:

![img](http://i.imgur.com/nLNumL9.png)

Do you guys have any workaround for this. Should I configure or import something in the bridging file or something?

**Comment by segiddins** [comment]
Can you try `#import <Realm/Realm.h>` in the bridging header?

**Comment by vlonjatg** [comment]
@segiddins, thanks for the reply. 

I added it in the bridging header but the issues were still there. One thing that i did is included ```#import "Realm/Realm.h"``` in the ```Fitonomy-Swift.h``` file and it worked. The only problem is that it is getting overridden for every build and I need to add it there again every time.

**Comment by jpsim** [comment]
Could you please check if `Enable Modules` is set to `YES` in your app target's build settings? That would explain why the `-Swift.h` file has `@import Realm;` (wrapped in a check for modules support) but that Realm types aren't being resolved further in the file.

If that still doesn't fix things, I'd be happy to look into your Xcode project, which you can send privately to help@realm.io.

**Comment by jpsim** [comment]
@vlonjatg did you get a chance to check if `Enable Modules` is set to `YES` in your app target's build settings?

**Comment by jpsim** [comment]
Closing since we never heard back.

**Comment by vlonjatg** [comment]
Hey guys, really sorry for this late reply. As for the issue, I don't exactly know what fixed it but it is not appearing anymore.
