### ISSUE TITLE
Add installation examples for watchOS

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#2455]
(Probably just adding watchOS to all of the Swift 2 examples?)

**Comment by justinging** [comment]
I got problem for adding the frameworks to project as well.
Anyone make that working  before?

(Supporting both IOS 9 and watchOS)

**Comment by jpsim** [comment]
iOS 9 and watchOS 2 are fully supported. They are different frameworks, however. We'll update our installation instructions shortly to have exact steps for watchOS 2. It's essentially the same as our iOS instructions, replacing 'iOS' with 'watchOS' whenever necessary.

**Comment by jpsim** [comment]
To clarify, this issue is tracking adding installation examples to https://github.com/realm/realm-cocoa/tree/master/examples/installation.

**Comment by justinging** [comment]
Sorry for wrong thread maybe
But any successful try on submiting watchOS2 project to iTunes?
Get errors for it

**Comment by skrew** [comment]
In my podfile i use:

```
target "APPNAMEWatchOS2 Extension" do
    platform :watchos, '2.0'
    pod "Realm", "0.95.0"
end
```

But it don't download `core/librealm-watchos.a`

I miss something ?

**Comment by jpsim** [comment]
@skrew Realm 0.95.0 depends on realm-core-0.92.1.1, which includes `core/librealm-watchos.a`, so it should be available. Could you try deleting and recreating your `Pods` directory to force it to download again?

**Comment by skrew** [comment]
Working after deleting Pods directory. Thanks.
