### ISSUE TITLE
Cocoapods install of RealmSwift not working

### ISSUE THREAD

**Issue by ajc6432** [realm/realm-cocoa#2457]
Hi,

I'm trying to install RealmSwift using Cocoapods.  I followed the steps here:

https://realm.io/docs/swift/latest/

to the letter and it simply will not work.  I'm using Cocoapods 0.38.2, XCode 6.4 and my Podfile includes:

    pod 'Realm', '0.94.1'
    pod 'RealmSwift'

for both the main and unit test targets and have added "use_frameworks!" to it as well.

Yet, every time I try to pod install, I get the following output from Cocoapods in the terminal:

    Updating local specs repositories
    
    CocoaPods 0.39.0.beta.2 is available.
    To update use: `sudo gem install cocoapods --pre`
    [!] This is a test version we'd love you to try.
    
    For more information see http://blog.cocoapods.org
    and the CHANGELOG for this version http://git.io/BaH8pQ.
    
    Analyzing dependencies
    [!] Unable to satisfy the following requirements:
    
    - `RealmSwift` required by `Podfile`
    - `RealmSwift` required by `Podfile`
    
What can I do to get RealmSwift up and running?  Thank you.

**Comment by segiddins** [comment]
Can you make sure that your minimum deployment target is iOS 8 / OS X 10.9 or greater? As of the 0.39 beta, CocoaPods has a more helpful error message.

**Comment by jpsim** [comment]
Whenever specifying custom versions of Realm, make sure that version is identical for both the `Realm` and `RealmSwift` pods, as they are released together. So if you need to use 0.94.1 explicitly, try this in your Podfile:

```ruby
pod 'Realm', '0.94.1'
pod 'RealmSwift', '0.94.1'
```

or to use the latest:

```ruby
pod 'Realm'
pod 'RealmSwift'
```

**Comment by segiddins** [comment]
@jpsim that isn't necessary, as the resolver can find the set of versions that match,

**Comment by jpsim** [comment]
ah, yes, I was thinking of the non-released case. thanks for clarifying.

**Comment by ajc6432** [comment]
The deployment target was not a 8.0 or higher, so I tried making it 8.0 and 8.1.  I still have been running into the same errors with a pod install.  Is there something else simple that I might be missing?

**Comment by segiddins** [comment]
Can you see if CocoaPods 0.39.0.beta.3 gives you a more helpful error message? And also try adding an explicit `platform :ios, '8.0'` to the top of your `Podfile`? Thanks!

**Comment by ajc6432** [comment]
I actually added that explicit ios versioning after the fact and it did the trick.  Been too busy to post about that here.  Thanks for the help @segiddins and @jpsim

**Comment by jpsim** [comment]
Happy you worked it out!
