### ISSUE TITLE
Assertion failed in Realm 0.95.0

### ISSUE THREAD

**Issue by ikeyboard** [realm/realm-cocoa#2460]
0x1072617cf <+79>:  leaq   0x372f4(%rip), %rax       ; "[realm-core-0.88.0] Assertion failed: col_ndx < m_columns.size()"
    0x1072617d6 <+86>:  leaq   0x369fc(%rip), %rcx       ; "table.cpp"
    0x1072617dd <+93>:  movl   $0x9b9, %edx
    0x1072617e2 <+98>:  jmp    0x10726180c               ; <+140>
    0x1072617e4 <+100>: leaq   0x34ab1(%rip), %rax       ; "[realm-core-0.88.0] Assertion failed: ndx < m_size"
    0x1072617eb <+107>: leaq   0x369e7(%rip), %rcx       ; "table.cpp"
    0x1072617f2 <+114>: movl   $0x9ba, %edx
    0x1072617f7 <+119>: jmp    0x10726180c               ; <+140>
    0x1072617f9 <+121>: leaq   0x36104(%rip), %rax       ; "[realm-core-0.88.0] Assertion failed: typeid(Col) == typeid(col)"
    0x107261800 <+128>: leaq   0x34906(%rip), %rcx       ; "../tightdb/table.hpp"
    0x107261807 <+135>: movl   $0x5cf, %edx
    0x10726180c <+140>: movq   %rax, %rdi
    0x10726180f <+143>: movq   %rcx, %rsi
    0x107261812 <+146>: callq  0x107146060               ; tightdb::util::terminate(char const*, char const*, long)
->  0x107261817 <+151>: nopw   (%rax,%rax)

**Comment by segiddins** [comment]
@ikeyboard can you try updating to Realm 0.95 and seeing if we've fixed the issue already? Thanks!

**Comment by ikeyboard** [comment]
Thanks! This issue happen in Realm Objective-C latest 0.95.0(static) in Xcode 6.4 - iOS8.4 simulator.
I happy rarely, and not happy now. I just worry sometime happy in real app.

**Comment by segiddins** [comment]
Can you share the assertion failure when using 0.95.0, and if possible, a project that demonstrates the issue (either here or privately at help@realm.io)? Thanks!

**Comment by jpsim** [comment]
@ikeyboard I'm sure you're under the impression that you're actually using Realm Objective-C 0.95.0, but your stack trace indicates that you're running a version between 0.90.0 and 0.90.4, so please double check your Realm version.

**Comment by ikeyboard** [comment]
Thanks for your reply! I can only copy the failed log, it's in my project. The assertion not happen again now. I recheck again and again, Surely the version is 0.95.0 but log message warning me to update.
//Version 0.95.0 of Realm is now available: http://static.realm.io/downloads/cocoa/latest
Waning message when I access real only realm    
 RLMRealm *realm = [RLMRealm realmWithPath:SWIPEREALMPATH readOnly:YES error:&error];
--
Anyway, it work OK now. Thank you!
