### ISSUE TITLE
0.95.0 release binaries were produced with Xcode 7

### ISSUE THREAD

**Issue by rcmcastro** [realm/realm-cocoa#2462]
Hi, I'm using a Realm 0.95 dynamic framework that I downloaded from your site. When I tried today to submit my app  to review on Itunesconnect, this error appeared:

![screen shot 2015-08-28 at 6 45 33 am](https://cloud.githubusercontent.com/assets/2885008/9543627/9b54f9be-4d50-11e5-8247-0a23601d1e7b.png)

**Comment by jpsim** [comment]
Thanks for reporting this, and sorry about the trouble!

It looks like our CI system built that version of the framework using Xcode 7 Beta 6 rather than Xcode 6.4. We may have to re-run our binary release process again, ensuring Xcode 6.4 is used to produce the final binaries.

**Comment by jpsim** [comment]
Closing this issue since we've cut two official releases since 0.95.0. If you're on 0.95.0 and this is affecting you, please update to 0.95.2.
