### ISSUE TITLE
Setting Schema Version Deprecation Issue

### ISSUE THREAD

**Issue by mamaral** [realm/realm-cocoa#2463]
Upgraded to the most recent version of Realm today, and am running into some issues.

My realm setup code is currently the following 

    [RLMRealm setSchemaVersion:5 forRealmAtPath:[RLMRealm defaultRealmPath] withMigrationBlock:^(RLMMigration *migration, uint64_t oldSchemaVersion) {}];
    self.realm = [RLMRealm defaultRealm];

The following two warnings were given:

1) 'defaultRealmPath' is deprecated: Use [RLMRealmConfiguration defaultConfiguration].path
2) 'setSchemaVersion:forRealmAtPath:withMigrationBlock:' is deprecated: Use RLMRealmConfiguration.schemaVersion and RLMRealmConfiguration.migrationBlock

Following the warning recommendations, the previous code was updated to the following:

    [RLMRealmConfiguration defaultConfiguration].schemaVersion = 5;
    [RLMRealmConfiguration defaultConfiguration].migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {};
    self.realm = [RLMRealm defaultRealm];

The warnings went away, but every time my app starts an exception is thrown 'Terminating app due to uncaught exception 'RLMException', reason: 'Provided schema version 0 is less than last set version 5.''

It appears as though setting the schema version on the default config doesn't stick? Perhaps I don't understand the new changes, and I bet I'm missing something simple, I'd just like to get this back up and running ASAP.

**Comment by tgoyne** [comment]
`defaultConfiguration` returns a copy of the current configuration, so you have to do:

```objc
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
config.schemaVersion = 5;
config.migrationBlock = ...;
[RLMRealmConfiguration setDefaultConfiguration:config];
```

**Comment by mamaral** [comment]
Gotcha, thanks for the clarification!

**Comment by cbess** [comment]
@tgoyne Funny, your *fix* helped a current issue with `[RLMRealm asyncOpen...]` that caused this error: 
```
Provided schema version 0 is less than last set version 1
```

For everyone else, basically, the default configuration must be set before you execute `asyncOpen`.
