### ISSUE TITLE
swift 2.0 compile failed with seg fault:11

### ISSUE THREAD

**Issue by swangy** [realm/realm-cocoa#2464]
hi, trying to compile example files in swift 2.0 and getting a seg fault:11 

this is with cocoapod successfully installed, any suggestions?  what details can i provide?

**Comment by segiddins** [comment]
@swangy we test that all examples can compile on CI. What version of CocoaPods are you using, and can you share the full error message that you're seeing? Thanks!

**Comment by swangy** [comment]
cocoapods version 0.39.beta.3

here's the dump:



/Users/user/Downloads/realm-swift-0.95.0/examples/ios/swift-2.0/Pods/RealmSwift/RealmSwift/List.swift:392:1: error: type 'List<T>' does not conform to protocol 'RangeReplaceableCollectionType'
extension List: RealmCollectionType, RangeReplaceableCollectionType {
^
Swift.RangeReplaceableCollectionType:43:17: note: protocol requires function 'splice(_:atIndex:)' with type '<S> (S, atIndex: List<T>.Index) -> ()'
  mutating func splice<S : CollectionType where S.Generator.Element == Generator.Element>(newElements: S, atIndex i: Self.Index)
                ^
Swift.RangeReplaceableCollectionType:54:17: note: protocol requires function 'removeAtIndex' with type '(List<T>.Index) -> List<T>.Generator.Element'
  mutating func removeAtIndex(i: Self.Index) -> Self.Generator.Element
                ^
/Users/user/Downloads/realm-swift-0.95.0/examples/ios/swift-2.0/Pods/RealmSwift/RealmSwift/List.swift:322:17: note: candidate has non-matching type '<T> (Int) -> ()'
    public func removeAtIndex(index: Int) {
                ^
Swift.RangeReplaceableCollectionType:65:17: note: protocol requires function 'removeRange' with type '(Range<List<T>.Index>) -> ()'
  mutating func removeRange(subRange: Range<Self.Index>)
                ^
Swift.RangeReplaceableCollectionType:80:17: note: protocol requires function 'removeAll(keepCapacity:)' with type '(keepCapacity: Bool) -> ()'
  mutating func removeAll(keepCapacity keepCapacity: Bool)
                ^
/Users/user/Downloads/realm-swift-0.95.0/examples/ios/swift-2.0/Pods/RealmSwift/RealmSwift/List.swift:341:17: note: candidate has non-matching type '<T> () -> ()'
    public func removeAll() {
                ^
/Users/user/Downloads/realm-swift-0.95.0/examples/ios/swift-2.0/Pods/RealmSwift/RealmSwift/List.swift:392:1: error: type 'List<T>' does not conform to protocol 'ExtensibleCollectionType'
extension List: RealmCollectionType, RangeReplaceableCollectionType {
^
Swift.ExtensibleCollectionType:14:17: note: protocol requires function 'reserveCapacity' with type '(List<T>.Index.Distance) -> ()'
  mutating func reserveCapacity(n: Self.Index.Distance)
                ^
Swift.ExtensibleCollectionType:34:17: note: protocol requires function 'extend' with type '<S> (S) -> ()'
  mutating func extend<S : SequenceType where S.Generator.Element == Generator.Element>(newElements: S)
                ^
0  swift                    0x000000010b71de0b llvm::sys::PrintStackTrace(__sFILE*) + 43
1  swift                    0x000000010b71e54b SignalHandler(int) + 379
2  libsystem_platform.dylib 0x00007fff95019f1a _sigtramp + 26
3  libsystem_platform.dylib 0x000000010c582a00 _sigtramp + 2002160384
4  swift                    0x0000000109db46ab (anonymous namespace)::DeclChecker::adjustSuperclassMemberDeclType(swift::TypeChecker&, swift::ValueDecl const*, swift::Type) + 331
5  swift                    0x0000000109daaf4d (anonymous namespace)::DeclChecker::checkOverrides(swift::TypeChecker&, swift::ValueDecl*) + 2157
6  swift                    0x0000000109da4d9e swift::TypeChecker::validateDecl(swift::ValueDecl*, bool) + 2622
7  swift                    0x0000000109dbd4ec std::__1::__function::__func<(anonymous namespace)::DeclChecker::visitBoundVars(swift::Pattern*)::'lambda'(swift::VarDecl*), std::__1::allocator<(anonymous namespace)::DeclChecker::visitBoundVars(swift::Pattern*)::'lambda'(swift::VarDecl*)>, void (swift::VarDecl*)>::operator()(swift::VarDecl*&&) + 140
8  swift                    0x0000000109edcd83 swift::Pattern::forEachVariable(std::__1::function<void (swift::VarDecl*)> const&) const + 243
9  swift                    0x0000000109dac870 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 1088
10 swift                    0x0000000109db768b (anonymous namespace)::DeclChecker::visitClassDecl(swift::ClassDecl*) + 571
11 swift                    0x0000000109dac6bb (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 651
12 swift                    0x0000000109dac418 swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) + 152
13 swift                    0x0000000109d7c5c1 swift::performTypeChecking(swift::SourceFile&, swift::TopLevelContext&, swift::OptionSet<swift::TypeCheckingFlags, unsigned int>, unsigned int) + 1393
14 swift                    0x0000000109b8f635 swift::CompilerInstance::performSema() + 4341
15 swift                    0x00000001097355b0 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 736
16 swift                    0x00000001097350b3 frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2515
17 swift                    0x000000010973128f main + 1983
18 libdyld.dylib            0x00007fff9a8e85c9 start + 1
Stack dump:

<edit>

1.	While type-checking '_AnyRealmCollection' at /Users/user/Downloads/realm-swift-0.95.0/examples/ios/swift-2.0/Pods/RealmSwift/RealmSwift/RealmCollectionType.swift:237:15

**Comment by segiddins** [comment]
And are you using Xcode 7 Beta 6?

**Comment by swangy** [comment]
7 beta 7a120f

**Comment by segiddins** [comment]
Beta 6 is 7A192o, can you try updating to the latest Xcode Beta? (we can only support one version of the betas at the time, and it's almost always the latest one) Thanks!

**Comment by swangy** [comment]
ah, got it thanks
