### ISSUE TITLE
After adding Realm through CocoaPods, NSURLConnection delegate methods are not getting called.

### ISSUE THREAD

**Issue by anbarasu0504** [realm/realm-cocoa#2468]
Previously I added Realm manually to my project. But once after changing it to cocapods, NSURLConnection delegate methods are not getting called. 

I changed
```
self.connection = NSURLConnection(request: httpRequest, delegate: self)
```
to 
```
NSURLConnection(request: httpRequest, delegate: self, startImmediately: true)
```
but still delegates are not getting called.

**Comment by segiddins** [comment]
@anbarasu0504 I find it very surprising that including Realm in your project would have any bearing on how `NSURLConnection` works whatsoever. Are you sure you didn't make any other changes to your project at the same time, such as switching Xcode versions?

**Comment by anbarasu0504** [comment]
Moved to NSUrlSession and now its ok .. working fine
