### ISSUE TITLE
"Migration" documentation for 0.95.0 is outdated

### ISSUE THREAD

**Issue by dvor** [realm/realm-cocoa#2470]
First paragraph in [Performing a Migration](https://realm.io/docs/objc/0.95.0/#performing-a-migration) section is outdated. There should be `migrationBlock` from `RLMRealmConfiguration` instead of `setSchemaVersion:...` method.

> You define a migration and the associated schema version by calling `+[RLMRealm setSchemaVersion:forRealmAtPath:withMigrationBlock:`]. Your migration block provides all the logic for converting data models from previous schemas to the new schema. After calling `+[RLMRealm setSchemaVersion:forRealmAtPath:withMigrationBlock:]`, any Realms which require migration will automatically apply the migration block provided and be updated to the provided version.

**Comment by segiddins** [comment]
Thanks for pointing this out, @dvor !
