### ISSUE TITLE
core download fails on OS X 10.11 beta 8

### ISSUE THREAD

**Issue by exsortis** [realm/realm-cocoa#2474]
`pod update` fails on 10.11 beta 8 (worked on beta 7). I'm suspecting that ATS is now enforced in this beta, and the "core" dependency is being accessed over HTTP (just a shot in the dark).

```
Installing Realm 0.95.0 (was 0.95.0)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.92.1.1
Downloading core failed. Please try again once you have an Internet connection.
```

**Comment by jpsim** [comment]
We've had issues for the last ~2 hours with assets stored on static.realm.io, but those should now be resolved. See https://github.com/realm/realm-cocoa/issues/2446#issuecomment-136813872 for more information.
