### ISSUE TITLE
JSON mapping for Realm

### ISSUE THREAD

**Issue by dimazen** [realm/realm-cocoa#2478]
I'm working on mapping lib for Realm and have some questions:
1. I'm querying objects dynamically using `-[RLMRealm objects:withPredicate:]`. However, it is not presented in `Realm.h` headers, but in `RLMRealm_Dynamic.h`. Is it a private header? If so is there any other way to fetch objects having object class name only? 
2. During mapping of relationships I'm producing an NSArray as a target value. Then `-[RLMObject setValue:forKey:]` is invoked. And it works due to [RLMAccessor](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMAccessor.mm#L748)! How valid is to use NSArray for this purpose? 

Thanks!

**Comment by tgoyne** [comment]
The dynamic API is "semi-public". You're free to use it and we won't remove any of the functionality currently exposed via it entirely, but it may change without warning (although realistically the only thing that's likely to change is the RLMRealm initialization, as that still needs to be switched fully to RLMRealmConfiguration).

If you have class definitions for all of your models, you can use `NSClassFromString(className)` and then call the regular `objectsWithPredicate:` method on that.

Passing an `NSArray` or any other fast enumerable to `setValue:forKey:` is perfectly fine.

**Comment by dimazen** [comment]
@tgoyne Thanks for your response!
I'm actually very surprised, since even after `-[RLMObject setValue:forKey:]` with `NSArray` it will return `RLMArrayLinkView` due to `RLMGetArray`. 
How likely this can be changed in future? Can I rely on this behaviour (which is perfectly fine!)

**Comment by tgoyne** [comment]
It's very unlikely to change. It's needed for `createWithValue:` to be useful, and we depend on it internally for some of the handling of `List` properties in Realm Swift (and a huge number of our tests).

**Comment by dimazen** [comment]
Thank you!
