### ISSUE TITLE
Submission to TestFlight fails on watchOS target

### ISSUE THREAD

**Issue by dgrekov** [realm/realm-cocoa#2480]
I have attempted to submit a watchOS app with the Realm framework linked against the target. 

I have used both the published version of the framework and also tried building it from scratch for swift2.

I get the following errors:
![screen shot 2015-09-02 at 13 09 55](https://cloud.githubusercontent.com/assets/225443/9638296/0270fb6c-5174-11e5-8274-044eb1c7eac4.png)
![screen shot 2015-09-02 at 13 10 06](https://cloud.githubusercontent.com/assets/225443/9638299/06efc894-5174-11e5-834d-e65c03b6e6bc.png)

 I am able to build and deploy to the physical device but not submit to test flight.

**Comment by jpsim** [comment]
Looks like you're attempting to link the watchOS version of the frameworks to an iOS app extension binary (which would cause the warnings "Unsupported armv7k architecture for ...appex", etc.). Can you make sure you're only linking Realm.framework and RealmSwift.framework to your watchOS target?

**Comment by dgrekov** [comment]
The frameworks are in the watchos 2 target, specifically in the extension of the 2 targets, that's where all of the code is. Should I be building it differently? that target is set to compile for armv7k

**Comment by jpsim** [comment]
There definitely seems to be a problem with the configuration because ITMS is reporting that the armv7k architecture is unsupported, but that's the only architecture available on watchOS.

**Comment by dgrekov** [comment]
Indeed. To reproduce, create a fresh project and it will submit just fine, then add the watchOS version of Realm.framework and it will fail. Has anyone been able to upload a watchOS app to TestFlight with Realm?

**Comment by jpsim** [comment]
Which version of Realm Swift and Xcode are you using?

**Comment by dgrekov** [comment]
RealmSwift is latest cloned from GitHub, It's 0.95 i believe. Xcode is 7b6

**Comment by dgrekov** [comment]
Steps I used to build:

1. Clone Realm from our repository on GitHub.
2. Run REALM_SWIFT_VERSION=2.0 sh build.sh build in the cloned repository.
3. Make sure that you remove the existing binaries of RealmSwift.framework and Realm.framework from your project.
4. Go to your Xcode project’s “General” settings. Drag the versions of RealmSwift.framework and Realm.framework from build/ios/swift-2.0/ or build/osx/swift-2.0/ directory to the “Embedded Binaries” section. Make sure Copy items if needed is selected and click Finish.
5. In your unit test target’s “Build Settings”, add the parent path to RealmSwift.framework in the “Framework Search Paths” section.

**Comment by dgrekov** [comment]
For what it's worth, the Alamofire framework errors out in the same way...

**Comment by dgrekov** [comment]
Posted on radar and cross posted here: http://www.openradar.me/radar?id=5578626653224960

**Comment by jpsim** [comment]
Thanks for filing that radar, @dgrekov. Let's keep this issue open as a reminder to check again once Xcode 7 goes GM.

**Comment by archfear** [comment]
I was able to use this build script to strip the unsupported architectures as a workaround: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by dgrekov** [comment]
Yes, that's a great link and script. I use it elsewhere. The problem here is that the framework is actually correct, yet the uploader is rejecting it.

**Comment by jpsim** [comment]
Has anyone here tried submitting a watchOS 2 app using Realm to TestFlight or the App Store since Xcode 7 was officially released last week? This is potentially related to why Apple delayed the official watchOS 2 release.

**Comment by dgrekov** [comment]
I have tried. Under some compile time settings (building for release straight in Xcode), I was able to get it uploaded to iTunes connect but then it is no stuck on processing. Additionally, building using the normal build.sh script, makes it work on simulator and physical device but not iTunes Connect.

Interestingly, after trying to push last Friday, with no further action, I received this email:

Hello,

We have encountered issues processing your latest build uploaded to iTunes Connect. We are investigating these issues and will have additional information for you with regard to a resolution soon.

Best Regards,

Sharon

App Store Developer Support Escalation Team

**Comment by justinging** [comment]
Hi, would you give some guildine on how to produce the framework for watchos and able to submit to itunes without the error?

thanks!

**Comment by jpsim** [comment]
I could successfully submit an iOS 9 & watchOS 2 app using Realm Swift to the App Store and TestFlight.

See jpsim/DeckRocket#28 for a working example.

If you have any problems submitting watchOS apps using Realm to iTunes Connect, I suggest comparing your project's configuration to the one above. If you still have problems, please open a new issue providing as much detail as possible and we'll be happy to help.
