### ISSUE TITLE
Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

### ISSUE THREAD

**Issue by keyclipse** [realm/realm-cocoa#2481]
Hi I know I think we should have solved this issue already but I still have this problem

Update all pods
Updating local specs repositories

CocoaPods 0.39.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `AirwardLibrary` from `../AirwardLibrary`
Pre-downloading: `RealmSwift` from `https://github.com/realm/realm-cocoa.git`, branch `master`
Pre-downloading: `SignalR-ObjC` from `https://github.com/keyclipse/SignalR-ObjC.git`, branch `master`
Downloading dependencies
Installing AFNetworking (2.6.0)
Installing AirwardLibrary (0.1.0)
Installing Alamofire (1.3.1)
Installing Bolts (1.2.1)
Installing Crashlytics (3.1.1)
Installing FBSDKCoreKit (4.5.1)
Installing FBSDKLoginKit (4.5.1)
Installing Fabric (1.4.0)
Installing KeychainAccess (1.2.1)
Installing PureLayout (3.0.1)
Installing QRCode (0.2)
Installing Realm (0.95.0)
Installing RealmSwift (0.95.0)
Installing SDWebImage (3.7.3)
Installing SignalR-ObjC (2.0.0.beta1)
Installing SocketRocket (0.3.1-beta2)
Installing SwiftyJSON (2.2.1)
Installing TPKeyboardAvoiding (1.2.9)
Installing UIAlertController+Blocks (0.9)
Installing pop (1.0.7)
Generating Pods project
Integrating client project
Sending stats
Sending stats

[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

Have I missed anything here?

**Comment by segiddins** [comment]
You can point your Podfile to the `master` branch of Realm to fix this issue as long as you're using CocoaPods 0.38 or later.

**Comment by keyclipse** [comment]
This is my current podfile:

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'AirwardClientSwift' do
pod 'PureLayout'
pod 'TPKeyboardAvoiding'

pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON'
pod 'KeychainAccess'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'SDWebImage'

pod 'pop', '~> 1.0'
pod 'RealmSwift', :git => "https://github.com/realm/realm-cocoa.git", :branch => "master"
pod 'UIAlertController+Blocks'
pod "QRCode", "~> 0.1"

pod 'Fabric'
pod 'Crashlytics'

pod 'SignalR-ObjC', :git => "https://github.com/keyclipse/SignalR-ObjC.git", :branch => "master"
pod "AirwardLibrary", :path => "../AirwardLibrary"

end

target 'AirwardClientSwiftTests' do

end

It still has the same issue

**Comment by segiddins** [comment]
You'll also need to add

```ruby
pod 'Realm',  :git => "https://github.com/realm/realm-cocoa.git", :branch => "master"
```

**Comment by LuoLee** [comment]
@segiddins It works.

**Comment by keyclipse** [comment]
Yeah It works for me ow as well thanks :)
