### ISSUE TITLE
Cannot instantiate Realm() gives call can throw error Swift 2

### ISSUE THREAD

**Issue by bryan1anderson** [realm/realm-cocoa#2483]
let realm = try! Realm()
                        
                         realm.write {
                            realm.create(Notifications, value: objectDictionary, update: true)
                            
                            var nots = realm.objects(Notifications)
                            print(nots)
                        }

thats how I am currently trying to create objects. With Swift 2.0 the error was introduced "call can throw, but is not marked with try and the error is not handled."

try! is supposed to silence this error, which is does, however my method exits the scope the second it hits the `let realm = try! Realm()` line of code.

So I have tried handling it this way:

          do {
                            let realm = try Realm()
                            
                            do {
                                
                                try realm.write {
                                    realm.create(Notifications, value: objectDictionary, update: true)
                                    
                                    var nots = realm.objects(Notifications)
                                    print(nots)
                                }
                            } catch {
                                print("nope")
                            }
                            
                        } catch {
                            print("nope didn't work")
                        }
                        
                        
                        
Silences all errors, and... exits scope when it hits `let realm = try Realm()`

Only it doesn't go to the catch which I thought was supposed to happen. Just exits the method.

**Comment by bryan1anderson** [comment]
So just be be clear, nothing I have done stops the fact that attempting to instantiate Realm will exit the scope

**Comment by segiddins** [comment]
@bryan1anderson I see you closed the issue -- did you get things sorted out?
