### ISSUE TITLE
Notification block - does not have member named 

### ISSUE THREAD

**Issue by anbarasu0504** [realm/realm-cocoa#2484]
```let token = Realm().addNotificationBlock { notification, realm in
        self.tableView.reloadData()
    }```

is giving error

 'ListViewController -> () -> ListViewController' does not have a member named 'tableView'

**Comment by jpsim** [comment]
Does your `ListViewController` have a `tableView` property?

**Comment by anbarasu0504** [comment]
yes. its an IBOutlet.

**Comment by jpsim** [comment]
I'm trying to figure out what combination would make the Swift compiler generate that error without seeing your code... are you sure you're calling this in an instance method on `ListViewController`? This isn't nested in another type or block, or in a `static`/`class` function, or on a different type altogether?

Posting more of your code would help us identify what's going wrong here.

**Comment by TimOliver** [comment]
@anbarasu0504 If you're still having issues here, please post more of your code for us to have a look. :)

It definitely sounds like some sort of scoping issue with the reference to your tableView.
