### ISSUE TITLE
This exception is confusing: Provided schema version 1 is less than last set version 0

### ISSUE THREAD

**Issue by ahayman** [realm/realm-cocoa#2485]
What actually happened is I switched development branches.  The prior branch was using a file-specific Configuration:

    return Realm.Configuration(
      path: getStorePath(storeName),
      inMemoryIdentifier: nil,
      encryptionKey: nil,
      readOnly: false,
      schemaVersion: storeVersion(storeName),
      migrationBlock: { migration, oldVersion in
        
      },
      objectTypes: nil)

The branch I switched to was an old branch using default Configuration:

    let Realm(path: getStorePath(storeName))

It threw the exception.

It was easy enough to figure out what happened and delete the file.  But that's a confusing error.  1 is definitely not less than 0. :)

**Comment by tgoyne** [comment]
Is the old branch using Realm 0.94.1? That error message was fixed in 0.95.

**Comment by ahayman** [comment]
Yeah... actually, the new branch was using .95 and the old branch was .94.1.  I forgot I updated it.

**Comment by bipinvaylu** [comment]
Getting same error, Exception logs:
```
2015-10-20 00:44:03.162 RealmTest[60656:33271965] *** Terminating app due to uncaught exception 'RLMException', reason: 'Provided schema version 0 is less than last set version 1.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8e48703c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8684a76e objc_exception_throw + 43
	2   Realm                               0x000000010017e738 _Z18RLMSetErrorOrThrowP7NSErrorPU15__autoreleasingS0_ + 264
	3   Realm                               0x0000000100158bbe +[RLMRealm realmWithConfiguration:error:] + 5598
	4   Realm                               0x0000000100156d1d +[RLMRealm defaultRealm] + 93
	5   RealmTest                           0x00000001000028bb _TFC9RealmTest7Trainer11saveTrainerfS0_FT_T_ + 75
	6   RealmTest                           0x0000000100004224 _TFC9RealmTest14ViewController13viewDidAppearfS0_FT_T_ + 612
	7   RealmTest                           0x0000000100004352 _TToFC9RealmTest14ViewController13viewDidAppearfS0_FT_T_ + 34
```

Code: 
```
    func applicationDidFinishLaunching(aNotification: NSNotification) {
        let configuration:RLMRealmConfiguration = RLMRealmConfiguration.defaultConfiguration()
        configuration.schemaVersion = 1
        configuration.migrationBlock = {(migration:RLMMigration, oldSchemaVersion: UInt64) in
            if oldSchemaVersion < 1 {
                migration.deleteDataForClassName("Dog")
                migration.deleteDataForClassName("Person")
            }
        }
        
        RLMRealmConfiguration.setDefaultConfiguration(configuration)
        let realm = RLMRealm.defaultRealm()
    }
```

**Comment by jpsim** [comment]
@bipinvaylu we're working on a fix for that in #2707.

**Comment by bipinvaylu** [comment]
hi @jpsim, schema versioning issue fixed and released ??

**Comment by jpsim** [comment]
Yes, in 0.96.1.

**Comment by bipinvaylu** [comment]
ok, i just did pod install but it's still showing me 0.96.0.
```
Bipins-MacBook-Pro:RealmDemo bipinvaylu$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using Realm (0.96.0)
Using SwiftyJSON (2.3.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total
pods installed.
```

**Comment by jpsim** [comment]
please run `pod setup` to refresh the latest set of available pods.

**Comment by bipinvaylu** [comment]
@jpsim, actually pod update to update dependencies. Great thanks :)

**Comment by jpsim** [comment]
both work. cheers!

**Comment by bipinvaylu** [comment]
@jpsim updated to latest but still facing same issue when going to get default realm object `let realm = RLMRealm.defaultRealm()`. 

<img width="576" alt="screen shot 2015-10-21 at 11 13 49 pm" src="https://cloud.githubusercontent.com/assets/717062/10645175/fa4cb3c0-7849-11e5-931a-e5cbc199563d.png">

**Comment by jpsim** [comment]
Please file a new issue, along with all the steps we need to take to reproduce the issue you're having, along with a description of what you're expecting to happen, and what's actually happening. Following our [CONTRIBUTING.md](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md) guidelines should be a good start to indicate the kind of information that's useful to us.
