### ISSUE TITLE
Documentation Request: What causes an object to be invalidated?

### ISSUE THREAD

**Issue by CraigSiemens** [realm/realm-cocoa#2486]
Currently there is no documentation to explain what would cause a `RLMObject` to be marked as `invalidated`. The two questions I have that would be nice if they were documented are:

* What causes `invalidated` to be `YES`?
* ~~How is `invalidated` related to `deletedFromRealm`, if at all?~~

Edit:
I just noticed `deletedFromRealm` is deprecated in the .h file but the documentation doesn't say that. Another possible update.

**Comment by tgoyne** [comment]
We don't mention the existence of deprecated things in the documentation at all because you shouldn't be writing new code using them.

`invalidated` will currently return true if the object has been deleted from the containing Realm or if `invalidate` is called on the containing RLMRealm.
