### ISSUE TITLE
Create a Realm Array in Swift

### ISSUE THREAD

**Issue by androids-dev** [realm/realm-cocoa#2487]
Hi,

I found that there is no way to create RealmArray instead of Array in RealmSwift.
The reason for using RealmArray is because of the following exception thrown:

`Terminating app due to uncaught exception 'RLMException', reason: 'Inserting invalid object of class Swift._SwiftDeferredNSArray for an RLMPropertyTypeAny property (extras).'`

**Comment by segiddins** [comment]
You'll need to use `List<T>` instead of `Array`.

**Comment by androids-dev** [comment]
But what if I get a JSON Array, how can I map it to any array runtime.
I am using https://github.com/Hearst-DD/ObjectMapper to map JSON Array to Array.

**Comment by androids-dev** [comment]
@segiddins Can you please help me on this?

**Comment by ronjumola** [comment]
The models you use should be extended to Realm Objects

**Comment by androids-dev** [comment]
Is there any example where I can save a JSON object to Realm via some object mapping?
It would be great!!

**Comment by segiddins** [comment]
@androids-dev can you share the code used to define your model? My guess is that the issue is that you have the `extras` property declared as a `Swift.Array`, instead of Realm Swift's `List` type.

**Comment by TimOliver** [comment]
@androids-dev If you still haven't managed to resolve this, please share with us the code that defines your model object so that we can examine it. :)
