### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by marlowcharite** [realm/realm-cocoa#2488]
I'm having trouble using carthage to build realm. Is carthage not supported (I don't see any instructions how to build this using carthage)? Or do I have to checkout the repo and build the framework manually?

**Comment by segiddins** [comment]
We have instructions for installation at https://realm.io/docs/objc/latest. Keep in mind that Realm requires the latest version of Carthage, and only supports installing Realm Swift via GitHub releases.

**Comment by marlowcharite** [comment]
Okay thanks @segiddins

**Comment by marlowcharite** [comment]
I'm trying to use swift 2 and every time I build and link I get the following error within my project on the RealmSwift import `Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again`. I've checked and I'm definitely using the latest version of `xcodebuild`: 

```Swift
~/Developer/iOS/projects/gryphon media/alterate(branch:feature/deintegrate-cocoapods*) » xcodebuild -version
Xcode 7.0
Build version 7A192o
------------------------------------------------------------
```

**Comment by segiddins** [comment]
Realm Swift for Swift 2 does not currently support installation via Carthage, only via CocoaPods, building from source, or from the GitHub release zips, due to a couple of limitations in Carthage.

**Comment by marlowcharite** [comment]
Thanks
