### ISSUE TITLE
Failable intializers for Realm object 

### ISSUE THREAD

**Issue by marlowcharite** [realm/realm-cocoa#2492]
Is there anyway to implement a failable initializer for a Realm object? What I want to do is be able to init any of my model objects with a dictionary of the JSON response and if a key or other issue arises to send back nil.

**Comment by segiddins** [comment]
It should be possible to do that in the latest version of Swift, as long as you delegated to one of the designated initializers? Could you please share what you're doing that you feel should work but isn't working? Thanks!

**Comment by marlowcharite** [comment]
Well anytime I try to implement an initializer of any type I get a fatal error on launch. This is one of my classes: 

```swift

import Foundation
import RealmSwift

class Artist: Object {
    
    private(set) dynamic var id: Int = 0
    private(set) dynamic var name: String = "Unknown"
    private(set) dynamic var profileImageUrl: String = "Unknown"
    private(set) dynamic var permalink: String = "Unknown"
        
    var albums: [Album] {
        return linkingObjects(Album.self, forProperty: "artist")
    }
    
    var tracks: [Track] {
        return linkingObjects(Track.self, forProperty: "artist")
    }
    
    var videos: [Video] {
        return linkingObjects(Video.self, forProperty: "artist")
    }
    
    convenience init(id: Int, name: String, imageUrl: String, permalink: String) {
        self.init()
        self.id = id
        self.name = name
        self.profileImageUrl = imageUrl
        self.permalink = permalink
    }

    required init() {
        super.init()
    }

    override static func primaryKey() -> String {
        return "id"
    }
    
}
```

but I get this error: `fatal error: use of unimplemented initializer 'init(realm:schema:)' for class 'Motley.Artist'`

**Comment by segiddins** [comment]
Can you try just leaving out the no-args initializer from your subclass?

**Comment by marlowcharite** [comment]
An empty init gives the same error

**Comment by bigfish24** [comment]
@marlowcharite Sorry for the slow reply! This got lost on our side since @segiddins was only with us through the summer, and we dropped the ball in passing this off to others on the team.

Are you still having issues? From what I can tell it seems like you need to remove, since you will automatically inherit this:
```swift
required init() {
        super.init()
}
```
and change your convenience initializer to use `super.init()`:
```swift
convenience init(id: Int, name: String, imageUrl: String, permalink: String) {
        super.init()
        self.id = id
        self.name = name
        self.profileImageUrl = imageUrl
        self.permalink = permalink
}
```
to make this a failable initializer, it could look like this:
```swift
convenience init?(id: Int, name: String, imageUrl: String, permalink: String) {
        super.init()
        // Check for valid id
        if id == 0 { return nil }
        self.id = id
        self.name = name
        self.profileImageUrl = imageUrl
        self.permalink = permalink
}
```

**Comment by marlowcharite** [comment]
Thanks for the reply @bigfish24. I will try this out and report back

**Comment by marlowcharite** [comment]
Nope. This is a no go.

<img width="1434" alt="screen shot 2015-09-29 at 9 31 58 pm" src="https://cloud.githubusercontent.com/assets/5712464/10182390/9f77144a-66f1-11e5-8a4b-636692174b60.png">

**Comment by bigfish24** [comment]
Hmm, could you try 'self.init()' instead?

**Comment by marlowcharite** [comment]
Yup that worked. I have no clue why I didn't think of that before hand. @bigfish24

**Comment by bigfish24** [comment]
Cool, the automatic inheritance of initializers still is confusing for me too. Glad it is working.
