### ISSUE TITLE
Realm object with primary key of type Int64

### ISSUE THREAD

**Issue by siuying** [realm/realm-cocoa#2503]
I'm building an app use Realm (Swift) to persist object having Int64 keys.

```swift
class Status : RealmSwift.Object {
  dynamic var id : Int64 = 0
}
```

I found that I cannot do something like:

```swift
realm.objects(Status).filter("id < %@", statusId)
```

as filter expect AnyObject but Int64 is not AnyObject. 

I noticed I can perform the above with: 
```swift
realm.objects(Status).filter("id < %@", NSNumber(longLong: statusId))
```

but it would be handy if it would just worked!

**Comment by tgoyne** [comment]
`filter()` uses [NSPredicate format syntax](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html). You can either use `%lld` for Int64, or just use Swift string interpolation (i.e. `filter("id < \(statusId)")`).

**Comment by siuying** [comment]
``%lld`` will not work as Int64 is not convertible to AnyObject and it will not match ``filter(predicateFormat: String, _ args: AnyObject...)``, which cause compiler error. (I'm using Swift 2 branch)

Swift interpolation will work and it seems more favourable!

**Comment by basememara** [comment]
Ok this works for filters, but is there a solution for `objectForPrimaryKey` with Int16/32/64 primary keys?

**Comment by JadenGeller** [comment]
@basememara You should be able to pass an `NSNumber` there as well. We're looking to fix this to work with `Int8`/`Int16`/`Int32`/`Int64` in Realm Swift for Swift 3. Thanks for bringing attention to this! https://github.com/realm/realm-cocoa/issues/4007
