### ISSUE TITLE
Investigate supporting tvOS

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#2504]
Today,  announced `tvOS`. Once the relevant info is available, we need to investigate what (if anything) we need to do to support using Realm on the big screen.

**Comment by danielreiser** [comment]
Unfortunately I can't build the binary. PhaseScriptExecution fails. Anything I could do to fix that? Thanks a lot for your hard work! I really appreciate it!

**Comment by jpsim** [comment]
@danielreiser as mentioned in #2506, we need an update to our core build process before we can support it here. We'll update that PR if/when we decide to move forward with it.

Given the 1MB local storage limitation, we may need to rethink our Apple TV strategy before committing to anything.

**Comment by danielreiser** [comment]
Thanks a lot for the clarification. I haven't seen the mention in #2506. I totally understand your decision and am excited with what you'll come up. Realm is such a great db replacement and it would be too bad if we couldn't use it on tvOS. I really appreciate all the hard work you guys are putting into it! Cheers!

**Comment by ronaldmannak** [comment]
@jpsim Is there any update you can share on the decision to support tvOS? Do we need temporary move back to CoreData if I want to have an app ready when the Apple TV launched by the end of October?

**Comment by jpsim** [comment]
We'll release official support for tvOS before the hardware starts shipping. I actually built a tvOS app using Realm last week and it was lots of fun!

Has an official ship date been announced yet, other than "some time in October"?

And if anyone has received early access to Apple TV hardware, please get in touch (jp@realm.io), we'd love to test this on real hardware but no one from our team won the lottery...

Also email me (jp@realm.io) if you'd like early access to Realm tvOS builds.

**Comment by ronaldmannak** [comment]
That's great news, thanks @jpsim (email sent)

**Comment by tbaranes** [comment]
Any news about #2506 compilation errors?

**Comment by pilwon** [comment]
[TechCrunch article](http://techcrunch.com/2015/10/19/tim-cook-says-the-new-apple-tvs-are-coming-next-week/):
> Pre-orders for the new Apple TVs are set to begin next Monday, Apple CEO Tim Cook said onstage at the WSJD Live conference, with shipments likely to be sent out by the end of next week.

When will the official RealmSwift support for tvOS be released?

**Comment by jpsim** [comment]
When all the items listed in #2691 have been done.

**Comment by jpsim** [comment]
tvOS support was included in our 0.97 release yesterday: https://realm.io/news/realm-objc-swift-0.97.0/
