### ISSUE TITLE
Model field called 'newValue' caused crashes

### ISSUE THREAD

**Issue by mosesoak** [realm/realm-cocoa#2507]
This just ate a bunch of hours trying to track down, and it's unclear whether it's a Realm or a Swift issue:

RealmSwift 0.95
XCode Version 7.0 beta 6 (7A192o) + Swift 2.0

This model field led to crashes of indeterminate origin:

    dynamic var newValue: String = ""

Symptoms resembled those of a memory leak or memory access error:
* Crashes would not occur until after the property was accessed about 5 times.
* XCode showed no useful stack trace or console errors for the most part. Occasionally there would be unknown selector sent errors targeting internals like "__NSCFData rangeOfCharacterFromSet:", or similar for array or dictionary.

After changing the field's name to "value" the crashes disappeared.

It's possible this is a Swift bug since "newValue" is a keyword used in get/set notation, but seems more likely that it's a Realm memory leak.

**Comment by segiddins** [comment]
@mosesoak this is actually not a bug, but rather Swift & ARC behaving according to ARC's rules. As [documented](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmRules.html#//apple_ref/doc/uid/20000994-BAJHFBGH), methods that begin with `new` return `+1`d objects which must then be balanced by a `release` or `autorelease`, and not `retain`ed.

This [StackOverflow answer](http://stackoverflow.com/questions/15747267/objective-c-naming-conventions-with-arc-and-possible-caveats) does a great job of explaining what exactly ARC is doing under the hood in this situation.

I hope that helps clarify things!

**Comment by mosesoak** [comment]
Thanks Sam, I was not aware of that language feature. Apparently it affects properties as well as methods.

**Comment by segiddins** [comment]
Yup, since properties are really methods under the hood.
