### ISSUE TITLE
RLMNotificationToken in swift bridging header 

### ISSUE THREAD

**Issue by eikebartels** [realm/realm-cocoa#2512]
Hey,

I tried to implement Realm based on the Example "TableView". Unfortunately I get always the following error. 

![screen shot 2015-09-10 at 13 04 26](https://cloud.githubusercontent.com/assets/767979/9786712/7fb01542-57bc-11e5-9ff6-c3a460be6919.png)

"Declaration of 'RLMNotificationToken' must be imported from module 'Realm.RLMRealm' before it is required"

I tried it with the pods "Realm" und with "RealmSwift" but I get for both version the same error.
Any idea??

**Comment by eikebartels** [comment]
Ok I had to set the property to private to avid xcode to bridge this property for Objective C

**Comment by bb-git** [comment]
You saved me :)
