### ISSUE TITLE
Did Apple break binary compatibility with Xcode? 0.94 cannot be used with Xcode

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-cocoa#2513]
<img width="675" alt="screen shot 2015-09-10 at 8 07 05 am" src="https://cloud.githubusercontent.com/assets/21057/9793027/36b0c2c0-5798-11e5-94f0-6a063f45d958.png">
So we were hoping to do a rough test of our app compiling with Xcode7GM with a 8.1 deployment target -- which should work -- but found Apple has broken their promise about link library/binary compatibility ...  any chance of getting a Xcode7 linkable version of the 0.94 version of the library?

**Comment by segiddins** [comment]
@dhmspector  has made no promises about binary compatibility with Swift, unfortunately. We plan on putting out a new point release compiled with the GM imminently, but in the meantime, you can try building RealmSwift from source or via CocoaPods -- instructions for both are given at https://realm.io/docs/swift/latest/#installation-swift-20.
