### ISSUE TITLE
Realm stops processing my code without crashes the app

### ISSUE THREAD

**Issue by klevison** [realm/realm-cocoa#2516]
Realm stops processing my code without crashes the appFor some reason when I call `let realm = Realm()` it ***stops*** processing (doesn't crash)  my code. My app is still running, but the screen keep frozen.

When I try to open default.realm using realm browser app, it shows me:

[![enter image description here][1]][1]

Again, it doesn't crash my app. It is a kind of pause.

1. No braekepoints
2. I've already tried: cocoapods and xcode install
3. I've already tried run on simulator and device (iPad)
4. App already deleted
5. Project cleaned up
6. Derived data cleaned up

  [1]: http://i.stack.imgur.com/6En7l.png

**Comment by segiddins** [comment]
It appears that realm initialization is failing. Could you share a project that reproduces the issue so we can investigate? Thanks!

**Comment by klevison** [comment]
@segiddins how can I share to you this project? Its a restricted project. Can I give you read permission in the repo?

**Comment by segiddins** [comment]
@klevison emailing a zip to help@realm.io would be awesome, thanks!

**Comment by jpsim** [comment]
The code in question was deadlocking because when Realm attempts to build up the model schema, it creates an instance of your Swift objects, but one of them had a Realm property, and therefore the Realm is attempted to be again reinitialized, causing this deadlock.

This could be avoided by making the following change:

```swift
class MyModel: Object {
   ... // properties
   let realmProperty = Realm()
}

// change this to a computed property:

class MyModel: Object {
   ... // properties
   var realmProperty: Realm { return Realm() }
}
```

**Comment by klevison** [comment]
@jpsim @segiddins thank you guys. Amazing job and support.
