### ISSUE TITLE
Updating an object doesn't seem to be working fully. 

### ISSUE THREAD

**Issue by avdgriendt** [realm/realm-cocoa#2518]
I'm trying to update an object by setting a boolean to YES. After that I ask Realm to give me a list of objects with that property that have YES as a value. It doesn't  show any results. But the object in the tableviewcell has the correct value set to yes. Any ideas what I'm doing wrong?

Example:

    BOOL currentValue = self.zone.isFavourite;
    
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    self.zone.isFavourite = !currentValue;
    [realm commitWriteTransaction];
    
    //self.zone.isFavourite = YES
    //But [PMGModelParkingZone objectsWhere:@"isFavourite == YES"] returns an empty array.

**Comment by bmunkholm** [comment]
Did you try to set isFavourite = YES within the write transaction?
Only changes within the write transaction is persisted and visible with a query.

**Comment by avdgriendt** [comment]
I've tried to set it to YES. See the code example. It's within the write transaction

**Comment by bmunkholm** [comment]
Could you reduce this to a fully functional repo case? Including your model.
I can't see how you defined self.zone. Is that object persisted to Realm? How?

**Comment by avdgriendt** [comment]
Alright, I think I've found the problem. I was updating Realm objects from NSArrary, populated by an API call. That was the problem. Sorry about wasting your time :)

**Comment by bmunkholm** [comment]
Happy you got it fixed!
