### ISSUE TITLE
How to migrate on a custom path?

### ISSUE THREAD

**Issue by dilizarov** [realm/realm-cocoa#2521]
I can't seem to find any really simple example for this.

For default, it is this:

    let config = Realm.Configuration(
      schemaVersion: 1,
    
      migrationBlock: { migration, oldSchemaVersion in
        if (oldSchemaVersion < 1) {
        }
      })

    Realm.Configuration.defaultConfiguration = config
    
    let realm = Realm()

I've tried:

    let config = Realm.Configuration(
      path: "myCustomPath"
      schemaVersion: 1,
    
      migrationBlock: { migration, oldSchemaVersion in
        if (oldSchemaVersion < 1) {
        }
      })
    
    let realm = Realm(configuration: config)!

Then, whenever I want to access the realm, of course I do this:

`let realm = Realm(path: "myCustomPath")`

But... I'm getting this error: 

    Terminating app due to uncaught exception 'RLMException', reason: 'Provided schema version 0 is less than last set version 1.'

Why?

The line `let realm = Realm(configuration: config)!` seems to migrate as evidenced when I put a `println('migrated')` statement in the migrationBlock. However, when I call `Realm(path: 'myCustomPath')` I get the exception.

This seems super simple and vanilla, surely it'd work like this?

**Comment by segiddins** [comment]
You'll need to pass the configuration into the `Realm` initializer, or just use `let realm = Realm()` if you've set the default configuration.

**Comment by dilizarov** [comment]
Wait, so I need to pass a configuration around everywhere? I was hoping it'd be as simple as me directing a migration to a specific path. Then, once migrated, I can take the migration out of my code and continue on my merry way by going to the same customPath.

**Comment by segiddins** [comment]
The idea of the configuration object is that it encapsulates _all_ the configuration options used to construct a Realm. If you want to manually migrate, the `migrateRealm` function should do the trick for you.

**Comment by dilizarov** [comment]
@segiddins hmmm, I replaced `let realm = Realm(configuration: config)!` with `migrateRealm(configuration: config)` but I'm still getting `Terminating app due to uncaught exception 'RLMException', reason: 'Provided schema version 0 is less than last set version 1.'`

**Comment by segiddins** [comment]
You really should just be passing in the configuration when you initialize the Realm, or otherwise using the default configuration which is used implicitly elsewhere.

**Comment by dilizarov** [comment]
@segiddins Alright, so I suppose that I'll have a migrationBlock in my defaultConfigs and it'll be empty for the sake of automatically updating added/removed params. Whenever I update my app and change any model parameters (add or remove), then I just need to increment the schemaValue and it'll work perfectly every time?

**Comment by jpsim** [comment]
> Whenever I update my app and change any model parameters (add or remove), then I just need to increment the schemaValue and it'll work perfectly every time?

Yes. Realm enforces that you increment the schema version to encourage you to be aware of these changes to your database file that occur, even when the migration can be applied automatically.

I encourage you to read Realm's migration docs here for more information: https://realm.io/docs/swift/latest/#migrations
