### ISSUE TITLE
Rational behind marking classes `final` in swift?

### ISSUE THREAD

**Issue by angerman** [realm/realm-cocoa#2523]
I've run into this a few times, trying to derive from classes like `Result`, but inevitably being denied, by `Results` being declared `final`.

What's the rational behind declaring all those classes final?

**Comment by jpsim** [comment]
Those classes are final because they're not designed to be subclassed. Realm code often depends on those classes not being subclassed, and with the `final` keyword, we can enforce this at the language level.

**Comment by angerman** [comment]
So the only solution is to fork the project then.

**Comment by bdash** [comment]
@angerman, can you outline why you would find it useful to derive from `Result`?
