### ISSUE TITLE
property of property in nspredicate

### ISSUE THREAD

**Issue by aksharbonu** [realm/realm-cocoa#2524]
Say you have a message object which has a conversation object as a property. 

I'm trying to do a predicate like the following

"conversation.currentUser != sender" but it can't seem to find "conversation.currentUser" on Message (note, there is a message.sender property).

**Comment by yoshyosh** [comment]
If you have your conversation objects, you should be able to just run the predicate `"currentUser != sender"` on those objects

**Comment by mrackwitz** [comment]
Actually, what you tried to achieve can't be really mapped to our current coverage of `NSPredicate` support. I added "multi-level object equality link queries" to https://github.com/realm/realm-cocoa/issues/1490, where we track that.
For now, you would need to enumerate and filter all messages manually:
```swift
let messages = realm.objects(Message).filter { (let message) in 
    message.conversation.currentUser != message.sender
}
```
