### ISSUE TITLE
checking write Transaction

### ISSUE THREAD

**Issue by aniketayachit** [realm/realm-cocoa#2531]
Is there any way to check whether realm is in writeTransaction.

**Comment by jpsim** [comment]
Sure thing! [`-[RLMRealm inWriteTransaction]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/inWriteTransaction). But please be aware of anti-patterns with this:

> **Warning:** Wrapping mutating operations in a write transaction if this property returns NO may cause a large number of write transactions to be created, which could negatively impact Realm’s performance. Always prefer performing multiple mutations in a single transaction when possible.

**Comment by aniketayachit** [comment]
thanks. thats solve my problem. right now i'm using this to check whether realm is ready in writeTransaction or not. If yes then don't do writeTransaction. Is this Ok to do.

**Comment by jpsim** [comment]
> thanks. thats solve my problem. right now i'm using this to check whether realm is already in writeTransaction or not. If yes then don't do writeTransaction. Is this Ok to do.

Generally, we recommend that you factor your code to encourage explicit write transactions and batch writes in logical groups, so you should avoid checking `inWriteTransaction` in all but the most necessary cases.
