### ISSUE TITLE
Add ZenHub to readme?

### ISSUE THREAD

**Issue by feluraschi** [realm/realm-cocoa#2538]
Hey, I'm on the ZenHub.io team. I noticed this repo uses ZenHub task boards to organize issues.

To help contributors know to check the task boards for current priorities, what do you think about adding the ZenHub badge to your ReadMe (or adding a mention to your contributor guidelines)? I'm happy to create a PR. A lot of people don't know ZenHub is free for open-source users :smile: 

Thoughts?

**Comment by bmunkholm** [comment]
Hey @feluraschi,
Yeah we did try it out a while back but settled on waffle.io instead. So if anything we should make a notice of that :-)
I can only recall a few of the reasons for that choice, like you only support chrome, didn't support multiple repos in one board and general UI impression.
Really hope you get some of that resolved. There are a lot of features missing from all github issue tools, so plenty of opportunity to make a great tool. 
Cheers

**Comment by feluraschi** [comment]
Hi @bmunkholm, thank you for your feedback! ZenHub has improved greatly over the recent months. We have added many new features and out of the ones you mentioned that we lacked, we do now have multi-repo boards. 
Would love for you and your team to give it another try and let me know what you think :)
