### ISSUE TITLE
Crash on iPad2 and iPhone5 with Realm 0.95

### ISSUE THREAD

**Issue by shanus** [realm/realm-cocoa#2540]
We have a realm setup with a very simple model

	class Item: Object {
		dynamic var id:String = NSUUID().UUIDString
		dynamic var itemId:Int64 = 0
		dynamic var itemClass:String = ""
	
		override class func primaryKey() -> String {
			return "id"
		}
	}

When we try to run a query on for obejcts with an empty database we get the following crash:

	Terminating app due to uncaught exception 'Invalid value', reason: 'Expected object of type string for property 'itemClass' on object of type 'Item', but received: (null)'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x05869466 __exceptionPreprocess + 182
		1   libobjc.A.dylib                     0x0631fa97 objc_exception_throw + 44
		2   Realm                               0x01796be8 _ZL15RLMPreconditionbP8NSStringS0_z + 328
		3   Realm                               0x0179c30c _ZN12_GLOBAL__N_123validate_property_valueEP11RLMPropertyP11objc_objectP8NSStringP15RLMObjectSchemaS5_ + 844
		4   Realm                               0x0179a2d7 _ZN12_GLOBAL__N_134update_query_with_value_expressionEP9RLMSchemaP15RLMObjectSchemaRN5realm5QueryEP8NSStringP11objc_objectP21NSComparisonPredicate + 823
		5   Realm                               0x01797fe1 _ZN12_GLOBAL__N_127update_query_with_predicateEP11NSPredicateP9RLMSchemaP15RLMObjectSchemaRN5realm5QueryE + 3729
		6   Realm                               0x017974bf _ZN12_GLOBAL__N_127update_query_with_predicateEP11NSPredicateP9RLMSchemaP15RLMObjectSchemaRN5realm5QueryE + 879
		7   Realm                               0x01796dda _Z27RLMUpdateQueryWithPredicatePN5realm5QueryEP11NSPredicateP9RLMSchemaP15RLMObjectSchema + 378
		8   Realm                               0x017ecf79 -[RLMResults objectsWithPredicate:] + 601
		9   RealmSwift                          0x01af334a _TFC10RealmSwift7Results6filterU__fGS0_Q__FCSo11NSPredicateGS0_Q__ + 138
		10  Master                              0x0029b8ce _TFFC6Master23POIDetailViewController14viewWillAppearFS0_FSbT_U_FT_T_ + 158
		11  Master                              0x00298fce _TPA__TFFC6Master23POIDetailViewController14viewWillAppearFS0_FSbT_U_FT_T_ + 78
		12  Master                              0x00064ec8 _TTRXFo__dT__XFdCb__dT__ + 40
		13  libdispatch.dylib                   0x06f5baf8 _dispatch_block_async_invoke_and_release + 347
		14  libdispatch.dylib                   0x06f7abef _dispatch_client_callout + 14
		15  libdispatch.dylib                   0x06f621ef _dispatch_root_queue_drain + 1092
		16  libdispatch.dylib                   0x06f63b70 _dispatch_worker_thread3 + 115
		17  libsystem_pthread.dylib             0x072be1da _pthread_wqthread + 724
		18  libsystem_pthread.dylib             0x072bbe2e start_wqthread + 30
	)
	libc++abi.dylib: terminating with uncaught exception of type NSException

This happens when we call the following

    let predicate = NSPredicate(format: "itemId == %d AND itemClass == %@", id, Event.className())
    if let realm = Realm() {
		if let item = realm.objects(Item).filter(predicate).first {
...

**Comment by jpsim** [comment]
Could you please share the model declaration for `Event`? If it's inheriting from `Object`, calling `className()` on it should theoretically never be returning `nil`.

**Comment by shanus** [comment]
Agreed.  It should not be returning nil.

	class Event: Object {
		dynamic var id:Int64 = 0
		dynamic var name:String = ""
		dynamic var summary:String = ""
		dynamic var startAt:NSDate = NSDate.distantPast() as! NSDate
		dynamic var endAt:NSDate = NSDate.distantPast() as! NSDate
		dynamic var address:String = ""
		dynamic var contactInformation:String = ""
		dynamic var createdAt:NSDate = NSDate.distantPast() as! NSDate
		dynamic var updatedAt:NSDate = NSDate.distantPast() as! NSDate

		override class func primaryKey() -> String {
			return "id"
		}
	}

**Comment by jpsim** [comment]
> When we replaced that with just a hard coded string we were still getting the crash so we thought the nil was happening on the other side of the comparison like it was picking nil from the database.

Well that just seems impossible, since the exception with the message you shared is only thrown when parsing the query, before it's ever evaluated.

Would it be possible for you to share a more complete reproduction case (ideally an Xcode project) that demonstrates the issue? You could email it to us privately at help@realm.io if you'd like.

**Comment by shanus** [comment]
I will see if we can get you a more complete implementation.  Related we just found a work around that appears to bypass the problem.  If we separate the predicate and just call filter like this the crash goes away.

	if let realm = Realm() {
		var items: Results<Item>?
		items = realm.objects(Item).filter("itemId == %d", event.id)
		items!.filter("itemClass == %@", Event.className())
		if let item = items!.first {
		...

**Comment by jpsim** [comment]
I've been unable to reproduce this locally, so I'll wait to see if you can send a minimal repro case before continuing to investigate. Thanks!

**Comment by jpsim** [comment]
Actually, from the issue title, does this only happen on 32-bit devices and not on 64-bit devices? I don't have access to a 32-bit device with me today...

When building up your predicate, is the `id` variable an `Int64`? Could you try this?

```swift
NSPredicate(format: "itemId == %d AND itemClass == %@", Int64(id), Event.className())
```

**Comment by shanus** [comment]
It is possible that it is only on 32 bit devices since these are both 32 bit devices and we do not have the issue on any of our 64 bit devices.  We just did not want to classify it as all 32 bit devices since the iPhone 5 and iPad 2 are the only two 32 bit devices we have to test it.  The id variable is an Int64.

**Comment by jpsim** [comment]
Of course, the `%d` format specifier is for 32-bit values, whereas `%lld` is used to represent 64-bit values, so changing your predicate format to the following will probably address the issue.

```swift
NSPredicate(format: "itemId == %lld AND itemClass == %@", id, Event.className())
```

If this is the case, then this isn't exactly something that Realm could catch and throw a more useful exception message, but rather something that's inherent to how NSPredicate format strings work and not a Realm-specific issue.

**Comment by shanus** [comment]
Thanks, that was the case.  NSPredicate handles it a bit differently and causes the problem.  Thanks for taking a look at it.
