### ISSUE TITLE
Realm synchronization after dispatch_async

### ISSUE THREAD

**Issue by dave-trudes** [realm/realm-cocoa#2543]
I'm using XCode 7, Realm-ObjC v.0.95.0 with RLMSupport.swift.

Following test case fails. Could you please explain how to make this test case pass?

```swift

public class RealmModel : RLMObject {}

class RealmTests: XCTestCase {
	func realm() -> RLMRealm {
		let config = RLMRealmConfiguration.defaultConfiguration()
		config.inMemoryIdentifier = "inMemory.realm"
		return try! RLMRealm(configuration: config)
	}
	
	func testBackground() {
		let models = [RealmModel(), RealmModel(), RealmModel()]
		let mainRealm = self.realm()
		let expect = expectationWithDescription("expectation")
		
		dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0)) {
			let bgRealm = self.realm()
			bgRealm.transactionWithBlock {
				bgRealm.addObjects(models)
			}
			print("model (background): \(RealmModel.allObjectsInRealm(bgRealm).count)") // 3 models

			dispatch_async(dispatch_get_main_queue()) {
				mainRealm.refresh()
				let modelCount = RealmModel.allObjectsInRealm(mainRealm).count
				print("model count: \(modelCount)") // 0 models
				XCTAssertEqual(modelCount, 3, "Must have 3 models") // Assertion fails
				expect.fulfill()
			}
		}
		
		waitForExpectationsWithTimeout(10, handler: nil)
	}
}
```

**Comment by segiddins** [comment]
There's no guarenteed ordering between your two dispatch_async blocks, so the one on the main queue could be running before the background block.

**Comment by dave-trudes** [comment]
The block on the main queue will be executed inside the block on the background queue, so it should be executed after the realm transaction.

Here is the console output:
```
Test Case '-[testBackground]' started.
model (background): 3
model count: 0
```

**Comment by dave-trudes** [comment]
Seems like the reason for failing is that the my RealmModel has no properties. If I add a property with a default value, the test passes.

**Comment by segiddins** [comment]
Ah yeah, there's an open issue on that somewhere. Currently, models with no properties can't actually have instances persisted, and an exception to that extent needs to be thrown somewhere.

**Comment by jpsim** [comment]
> models with no properties can't actually have instances persisted

@dave-trudes we're tracking that issue as #1943, so I'm closing this ticket as a duplicate. But please let us know if you have any further questions.
