### ISSUE TITLE
Error when compiling code with Xcode 7 and Swift 2.0

### ISSUE THREAD

**Issue by mcvasquez** [realm/realm-cocoa#2544]
### **Expected results**
* Run my app on Simulator after update Xcode from 6.4 to 7.0.

### **Actual results**
![screen shot 2015-09-17 at 8](https://cloud.githubusercontent.com/assets/6573722/9949117/ec5e2d30-5d77-11e5-95a8-b11446c7e708.png)

### **Environments**
Realm-Swift - v0.95.0 via Cocoapods (before v0.94.1)
Xcode - 7.0
Swift - 2.0
OSX - 10.10.5

**Comment by staticdreams** [comment]
You're probably using master branch? and from the looks of it master still seem to use the old swift 1.2 syntax. I'm using ``swift-2.0`` branch and it works just fine

**Comment by mcvasquez** [comment]
I'm using the master branch: `pod 'RealmSwift', '~> 0.95.0'`

But when I change my podfile to:
`pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'`
`pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'`

And run `pod install`, it's getting this error: 

> Analyzing dependencies
> 
> CocoaPods 0.39.0.beta.4 is available.
> To update use: `gem install cocoapods --pre`
> [!] This is a test version we'd love you to try.
> 
> For more information see http://blog.cocoapods.org
> and the CHANGELOG for this version http://git.io/BaH8pQ.
> 
> Pre-downloading: `Realm` from `https://github.com/realm/realm-cocoa.git`, branch `swift-2.0`
> 
> ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> ### Command
> 
> ```
> /usr/bin/pod install
> ```
> 
> ### Report
> 
> * What did you do?
> 
> * What did you expect to happen?
> 
> * What happened instead?
> 
> 
> ### Stack
> 
> ```
>    CocoaPods : 0.37.2
>         Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
>     RubyGems : 2.4.8
>         Host : Mac OS X 10.10.5 (14F27)
>        Xcode : 7.0 (7A220)
>          Git : git version 2.3.8 (Apple Git-58)
> Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
> Repositories : master - https://github.com/CocoaPods/Specs.git @ 0e7deb74697893fc54095af5920dd7cd2b445bea
> ```
> 
> ### Plugins
> 
> ```
> cocoapods-plugins : 0.4.2
> cocoapods-trunk   : 0.6.1
> cocoapods-try     : 0.4.5
> ```
> 
> ### Podfile
> 
> ```ruby
> platform :ios, "8.0"
> use_frameworks!
> 
> target 'MyApp' do
> pod 'Alamofire', '~> 2.0'
> pod 'MBProgressHUD', '~> 0.9.1'
> #pod 'RealmSwift', '~> 0.95.0'
> pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
> pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
> pod 'TextFieldEffects', '0.4.2'
> pod 'ZFRippleButton', :git => 'https://github.com/theniceboy/ZFRippleButton.git', :branch => 'swift-2.0'
> pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
> pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'
> pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git'
> pod 'Timepiece', :git => 'https://github.com/naoty/Timepiece.git', :branch => 'swift-2.0'
> end
> 
> target 'MyAppTests' do
> 
> end
> ```
> 
> ### Error
> 
> ```
> Errno::ENOENT - No such file or directory - /var/folders/7l/nqj98bv93bn9v1q865zplgpm0000gp/T/d20150918-1507-1wblxpc
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `stat'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:42:in `block in download'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:140:in `message'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:40:in `download'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/abstract_external_source.rb:108:in `block in pre_download'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/abstract_external_source.rb:106:in `pre_download'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:358:in `fetch_external_source'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:335:in `block (2 levels) in fetch_external_sources'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:334:in `each'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:334:in `block in fetch_external_sources'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:333:in `fetch_external_sources'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:62:in `analyze'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
> /Library/Ruby/Gems/2.0.0/gems/claide-0.8.2/lib/claide/command.rb:312:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
> /usr/bin/pod:23:in `load'
> /usr/bin/pod:23:in `<main>'
> ```
> 
> ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> [!] Oh no, an error occurred.
> 
> Search for existing GitHub issues similar to yours:
> https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+-+%2Fvar%2Ffolders%2F7l%2Fnqj98bv93bn9v1q865zplgpm0000gp%2FT%2Fd20150918-1507-1wblxpc&type=Issues
> 
> If none exists, create a ticket, with the template displayed above, on:
> https://github.com/CocoaPods/CocoaPods/issues/new
> 
> Be sure to first read the contributing guide for details on how to properly submit a ticket:
> https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
> 
> Don't forget to anonymize any private data!

**Comment by segiddins** [comment]
@mcvasquez that's a CocoaPods issue that has been fixed in the 0.39 betas.

**Comment by mcvasquez** [comment]
Fixed. Thanks guys.

**Comment by a-vlad** [comment]
I had same error @mcvasquez Error was complete gibberish and provided no clues. I am on pod 0.37.2 My issue was  s.name value did not match the pod name i had in my podfile.

**Comment by jpsim** [comment]
Please update to CocoaPods 0.39, which we state in our documentation as the minimum supported version.
