### ISSUE TITLE
RLMException', reason: 'open() failed: Operation not permitted (Just on Device) 

### ISSUE THREAD

**Issue by Godlex** [realm/realm-cocoa#2545]
Hi guys, 

I have a little problem with realm. In my simulator everything is fine and it works perfect. 
But if I want to test it on my phone it crashes. The reason is: 
"Terminating app due to uncaught exception 'RLMException', reason: 'open() failed: Operation not permitted'" I don't understand why I don't have the permission. 

My Xcode Version is 7.0 and on the iPhone I am running iOS 8.4.1 
I am using the current version of realm, I pulled it today.

My code looks like this: 

if let path = NSBundle.mainBundle().pathForResource("Realmfile", ofType: "realm")
        {
            
           self.realm = RLMRealm(path: path) 
 
}  

It worked since I updated to xcode 7. 

I hope someone knows what is wrong.

**Comment by segiddins** [comment]
The issue here is that you're trying to open a file that's in your app bundle with read-write permissions. Your best bet, depending on whether you want to be able to write to this file, is either to open it in read-only mode, or move the file from the app bundle into a writable location.

**Comment by Godlex** [comment]
Thank you very much, I tried everything but didn't get it. 
It is working now! Thank you! :)

**Comment by jpsim** [comment]
Thanks for chiming in @segiddins!
