### ISSUE TITLE
How about a beforeSave / willSave hook 

### ISSUE THREAD

**Issue by maremmle** [realm/realm-cocoa#2546]
I'd like to have the ability to execution some custom code in my model class before the entity will be save.

**Comment by jpsim** [comment]
We agree, this would be a great feature, but ends up being a bit tricky to implement well. We're already tracking this issue as #1994, so I'm closing this one as a duplicate, but feel free to contribute to the conversation (or just subscribe) over there.

**Comment by mouse-lin** [comment]
@jpsim Whether they will be implemented ?

**Comment by jpsim** [comment]
See #1994
