### ISSUE TITLE
Errors in xcode after updating to iOS9 support 

### ISSUE THREAD

**Issue by nuke99** [realm/realm-cocoa#2547]
I started to get these errors after updating latest xcode support for iOS 

I have added the screenshots 

http://imgur.com/a/Fw140

# update 
Errors 
Pods/Realm/Realm/RLMAccessor.mm:248:46: Expected ')'
Pods/Realm/Realm/RLMAccessor.mm:256:13: Use of undeclared identifier 'val'
Pods/Realm/Realm/RLMAccessor.mm:257:37: Use of undeclared identifier 'val'
Pods/Realm/Realm/RLMAccessor.mm:258:65: Use of undeclared identifier 'options'; did you mean 'optind'?
Pods/Realm/Realm/RLMAccessor.mm:297:20: Redefinition of 'RLMSetValue'
Pods/Realm/Realm/RLMAccessor.mm:693:13: No matching function for call to 'RLMSetValue'

**Comment by nuke99** [comment]
issue was fixed after updating the latest version 
sorry.  close this thread

**Comment by jpsim** [comment]
Glad your resolved whatever this was, @nuke99!
