### ISSUE TITLE
How to sort RLMArray objects?

### ISSUE THREAD

**Issue by saltwat5r** [realm/realm-cocoa#2551]
I'm trying to sort RLMArray objects. How can I do it?

**Comment by jpsim** [comment]
Use [`-[RLMArray sortedResultsUsingProperty:ascending:]`](https://realm.io/docs/objc/latest/api/Classes/RLMArray.html#//api/name/sortedResultsUsingProperty:ascending:).

**Comment by saltwat5r** [comment]
But I don't save this objects in Realm DB, so I only create objects on fly and I want to sort them.

**Comment by jpsim** [comment]
Oh, I see! RLMArray's are only really useful when used as properties on RLMObject's. In your case, I'd recommend you store your standalone RLMObject's in an NSArray, which you can then sort the normal ways: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Collections/Articles/Arrays.html#//apple_ref/doc/uid/20000132-SW5
