### ISSUE TITLE
Please, help!! Property with "description" name

### ISSUE THREAD

**Issue by mhergon** [realm/realm-cocoa#2553]
Hi,

I have this model created to parse JSON response:
![captura de pantalla 2015-09-22 a las 12 12 10](https://cloud.githubusercontent.com/assets/621373/10015880/4f14947e-6123-11e5-895c-17eab8a426a6.png)
but "description" property returns this error:
```
Getter for 'description' with Objective-C selector 'description' conflicts with getter for 'description' from superclass 'Object' with the same Objective-C selector
```

Is there any way to deal with this without modifying server side?
Thanks!

**Comment by tgoyne** [comment]
`description` is special in Swift: it's the method used to implicitly convert objects to strings, so it's not available as a name for a property. As an alternative to changing the server, you could use one of the Swift JSON mapping libraries to map it to a property with a different name when converting to and from JSON.

**Comment by mhergon** [comment]
@tgoyne Can you recommend me the best Swift JSON mapping library?

Thanks!

**Comment by jpsim** [comment]
Both https://github.com/thoughtbot/Argo and https://github.com/Anviking/Decodable should work well with Realm Swift.

**Comment by mhergon** [comment]
@jpsim Any example with Realm integration and Realm().create() function?

Thanks again!

**Comment by jpsim** [comment]
No, most JSON mapping libraries out there will initialize and object, which you can then add to a Realm with `Realm().add(_:)`

**Comment by mhergon** [comment]
@jpsim  Ok, thanks!

**Comment by vadim-fueled** [comment]
@tgoyne @mhergon I have and existing .realm file with one of the properties named `description`. Is there a way I can read the file, e.g. by mapping `description` from the file to a different key in my `Object` subclass?
