### ISSUE TITLE
ISO 8601 Dates

### ISSUE THREAD

**Issue by lucianocn** [realm/realm-cocoa#2554]
Realm have any support for ISO 8601 Dates?

    *** Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value '2015-09-22T16:51:28Z' for property 'created''

**Comment by jpsim** [comment]
We don't automatically convert strings to dates, but we're tracking adding this feature in #1013, so I'm closing this one as a duplicate. Feel free to continue the conversation in there.

**Comment by lucianocn** [comment]
@jpsim Theres any idea when it will be implemented? It was suggested October 14, 2014 ;(

By the way, theres any date string format that Realm automatically converted as a NSDate?


Thanks,

**Comment by jpsim** [comment]
> Theres any idea when it will be implemented? It was suggested October 14, 2014 ;(

It's not part of our current high priorities (see [P1 issues](https://github.com/realm/realm-cocoa/issues?q=is%3Aopen+is%3Aissue+label%3AP1) to get a sense of what our top priorities are at the moment).

> By the way, theres any date string format that Realm automatically convert as a NSDate?

No.

One of the reasons why this isn't a top priority for us at the moment is that there's a large number of libraries out there that can do this mapping for you in both Objective-C and Swift. So we're focusing on solving the problems that don't already have widespread solutions.

**Comment by lucianocn** [comment]
@jpsim I really appreciate your answer! I'll do my best to help Ream with this feature.
