### ISSUE TITLE
Realm Unable to Fetch the Back References

### ISSUE THREAD

**Issue by azamsharp** [realm/realm-cocoa#2556]
I am using Realm in my application with the following models: 

```
class GroceryItem: GTBase {

    dynamic var title = ""
    dynamic var dateCreated = NSDate()
    dynamic var datePurchased = NSDate()
    dynamic var dateConsumed = NSDate() 
    
    dynamic var shoppingList :ShoppingList!
    dynamic var groceryCategory :GroceryCategory?
    
}
```

And this: 

```
class GroceryCategory: GTBase {

    dynamic var title = ""
    dynamic var dateCreated = NSDate()
    
    let groceryItems = List<GroceryItem>()
}
```

When I save the GroceryCategory I do it like this: 

```
    let realm = try! Realm()
        
        let category = GroceryCategory()
        category.id = NSUUID().UUIDString
        category.title = title
        
        try! realm.write {
            
            category.groceryItems.append(self.groceryItem)
            self.groceryItem.groceryCategory = category
            
            realm.add(category)
        }
```

I open the Realm Browser and I can see everything is saved correctly. The grocery categories has a collection of grocery item and the grocery item has a reference to the grocery category. 

Then I fetch the categories: 

`  self.groceryItems = realm.objects(GroceryItem).filter("shoppingList == %@", self.shoppingList).sorted("dateCreated", ascending: false)`
      
Now, when I iterate through the grocery items the groceryCategory is nil! Why is that?

**Comment by azamsharp** [comment]
I am confirming a bug here about Realm. At this time Realm only supports one kind of relationship on elements. This means you cannot have one to many and back reference to the parent for the same object. If you do this you will always encounter nil values for the parent object even though they are not nil.

**Comment by TimOliver** [comment]
Hi Mohammad! Sorry to hear you were having an issue with this!

There's actually an easier way you could go about doing this. There's a property in the Realm `Object` class that lets you look up whether the object is a child of another object (Located [here](https://realm.io/docs/swift/latest/api/Classes/Object.html#/s:FC10RealmSwift6Object14linkingObjectsFS0_U__FTMQ_11forPropertySS_GSaQ__) in the documentation), so you don't need to manually set up that relation yourself.

That being said, that definitely sounds like that could also be a bug, so I might need to get one of the other engineers' opinion on this. /cc @jpsim @tgoyne

**Comment by jpsim** [comment]
I'm under the impression that this is failing due to List equality predicates not being supported (`"shoppingList == %@", self.shoppingList`), but I'm not 100% sure without digging into this some more.

**Comment by mrackwitz** [comment]
This is not a bug. This may be just a bit surprising behavior coming from a relational database, like SQLite. What you do here, is setting up two relationships in both directions. This is possible, but they are not automatically associated with each other and are not kept in sync. Please checkout the chapter [Inverse Relationships](https://realm.io/docs/swift/latest/#inverse-relationships) in our docs, which explains how to make actual backlinks work.

**Comment by mrackwitz** [comment]
Sorry, did missed previous answers because my page was out-of-date. I'd support @TimOliver's recommendation. But there seems some further investigation needed.

**Comment by jpsim** [comment]
@TimOliver can you look into this? Is my assumption from my last comment accurate, that we don't yet support List equality predicates? Some digging in our tests is necessary here.

**Comment by TimOliver** [comment]
@jpsim Sure! I'll have a look through our tests and see if  I can find something matching this sort of case.

**Comment by TimOliver** [comment]
Oops, actually. Before I get too far ahead of myself. In this code sample, `shoppingList` isn't a `List` object, it's a `ShoppingList` object.

@azamsharp Just to confirm, what exactly is the `ShoppingList` object? Can you post its code here? 

Additionally,y when you're calling the `("shoppingList == %@", self.shoppingList)` filter, you definitely are actually getting `GroceryItem` objects back from it, however each and every one of those objects have a nil value for their `groceryCategory` property, even though they're not supposed to, right?

**Comment by bdash** [comment]
@azamsharp, it looks like we need more information to assist you further. If you still need assistance with this, please reopen the issue and provide the details that @TimOliver requested above.
