### ISSUE TITLE
Primary key handling by derived classes

### ISSUE THREAD

**Issue by peterpaulis** [realm/realm-cocoa#2562]
I have a base class
"A" with primary key "aID"

then i have 2 derived classes from A

B : A
C : A

in C i return primaryKey nil -> so class C doesn't have a primary key and i don't want it to have one (but it still inherits the "aID", which is used) 

When i try to save a C object, which has an existing "aID" i get 

*** Terminating app due to uncaught exception 'RLMException', reason: 'Can't set primary key property 'contributorID' to existing value '442'.'
*** First throw call stack:

**But class C doesn't have a primary Key** (it's base class has a primary key, but not the derived class)

**Comment by peterpaulis** [comment]
When i return nil for primary key in A and return "aID" for primary key in B

and also add aID to defaultPropertyValues in A

then during saving in C i get 
*** Terminating app due to uncaught exception 'RLMException', reason: 'No value or default value specified for property 'aID' in 'C''
*** First throw call stack:

**Comment by TimOliver** [comment]
Hi Peter!

Oh wow! That's a really interesting child class situation there. I would have assumed overriding the same methods in class C would have completely overridden the default functionality of A, but it's possible that with the way Realm is setting up the schema for these objects, the `primaryKey` property is still getting set anyway.

Is it possible you could send us a sample app featuring that code so we can test it out on our end?

Thanks a lot!

**Comment by jpsim** [comment]
@peterpaulis I can't reproduce the issues you've been having. Here are some unit tests I wrote based on your descriptions of your models:

```objc
@interface ParentObject : RLMObject
@property NSInteger intProp;
@end
@implementation ParentObject
+ (NSString *)primaryKey {
    return @"intProp";
}
@end

@interface ChildObject : ParentObject
@end
@implementation ChildObject
+ (NSString *)primaryKey {
    return nil;
}
@end

- (void)testGitHubInheritanceIssue
{
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.path = RLMTestRealmPath();
    config.objectClasses = @[[ParentObject class], [ChildObject class]];
    NSError *error = nil;
    RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:&error];
    if (error) {
        XCTFail(@"Creating Realm failed: %@", error.localizedDescription);
    }
    [realm transactionWithBlock:^{
        [ParentObject createInRealm:realm withValue:@[@0]];
        XCTAssertThrows([ParentObject createInRealm:realm withValue:@[@0]], @"Can't set primary key property 'intProp' to existing value '0'.");
        [ChildObject createInRealm:realm withValue:@[@0]];
        [ChildObject createInRealm:realm withValue:@[@0]];
    }];
    XCTAssertEqual([ChildObject allObjectsInRealm:realm].count, 2U);
}
```

and then from your second comment:

```objc
@interface AObject : RLMObject
@property NSInteger intProp;
@end
@implementation AObject
+ (NSString *)primaryKey {
    return nil;
}
+ (NSDictionary *)defaultPropertyValues {
    return @{@"intProp": @0};
}
@end

@interface BObject : AObject
@end
@implementation BObject
+ (NSString *)primaryKey {
    return @"intProp";
}
@end

@interface CObject : AObject
@end
@implementation CObject
+ (NSString *)primaryKey {
    return nil;
}
@end

- (void)testGitHubInheritanceIssue
{
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.path = RLMTestRealmPath();
    config.objectClasses = @[[AObject class], [BObject class], [CObject class]];
    NSError *error = nil;
    RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:&error];
    if (error) {
        XCTFail(@"Creating Realm failed: %@", error.localizedDescription);
    }
    [realm transactionWithBlock:^{
        [AObject createInRealm:realm withValue:@[@0]];
        [AObject createInRealm:realm withValue:@[@0]];
        [BObject createInRealm:realm withValue:@[@0]];
        XCTAssertThrows([BObject createInRealm:realm withValue:@[@0]]);
        [CObject createInRealm:realm withValue:@[@0]];
        [CObject createInRealm:realm withValue:@[@0]];
    }];
    XCTAssertEqual([AObject allObjectsInRealm:realm].count, 2U);
    XCTAssertEqual([CObject allObjectsInRealm:realm].count, 2U);
}
```

So this is all working as expected for me. Could you please post similar test code that fails for you so we can continue to investigate?

Thanks!

**Comment by peterpaulis** [comment]
Hi

I want to do a sample code

The only way i could go around this was by moving aid to c

**Comment by jpsim** [comment]
I'm not sure what you mean by your last comment, @peterpaulis. Are you asking for more sample code? What about "moving aid to c"?

The sample code I gave above is all in Objective-C and I think covers the use cases you were looking for...

**Comment by jpsim** [comment]
Closing since we've provided sample code and haven't heard back from @peterpaulis.
