### ISSUE TITLE
"jump to definition" not working on Xcode Version 7.0 (7A220)

### ISSUE THREAD

**Issue by edwardIshaq** [realm/realm-cocoa#2564]
Not sure why this stopped working for me.
Since the upgrade to Swift 2.0 i've downloaded the library from the Realm.io site and replaced the version i had from Carthage.

Any idea how to resolve this issue ?

**Comment by jpsim** [comment]
You should file a bug report with Apple, since this seems more Xcode related than a problem with how we built the Realm framework.

**Comment by mrackwitz** [comment]
This may likely happen because of a version incompatiblity. Our latest release was still built with Xcode latest GM version (7A218), which is not compatible with the AppStore release as pointed out by #2572.

**Comment by edwardIshaq** [comment]
Alright will do
Thanks you for the response. 


Edward Ashak

**Comment by jpsim** [comment]
Let's move the conversation to #2572 since it's the same root cause.
