### ISSUE TITLE
“Realm.framework” couldn’t be removed because you don’t have permission to access it 

### ISSUE THREAD

**Issue by 3viewgroup** [realm/realm-cocoa#2568]
in terminal when i carthage update
Failed to write to /Users/jassadakornketkaew/Documents/ShareLookKickFlip/Carthage/Build/iOS/Realm.framework: Error Domain=NSCocoaErrorDomain Code=513 "“Realm.framework” couldn’t be removed because you don’t have permission to access it." UserInfo=0x7f99cb808840 {NSFilePath=/Users/jassadakornketkaew/Documents/ShareLookKickFlip/Carthage/Build/iOS/Realm.framework, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7f99cb8054e0 "The operation couldn’t be completed. Directory not empty"}

**Comment by TimOliver** [comment]
Hi there!

Just wondering real quick, did you try and use `sudo` for that update command? :)

**Comment by jsslai** [comment]
I've seen this when Carthage is using zipped frameworks instead of building. You can try to build dependencies from the sources:

> carthage update --no-use-binaries

**Comment by jpsim** [comment]
> You can try to build dependencies from the sources:

This will only work with Realm Objective-C, as Carthage cannot build Realm Swift from source, only using binaries.

We're already tracking this issue as #2315.

**Comment by tgoyne** [comment]
What version of Carthage are you using? I can reproduce this with 0.8 but not 0.9.2.

**Comment by jpsim** [comment]
Closing as this is tracked by #2315.
