### ISSUE TITLE
Migration of objects with RLMArrays

### ISSUE THREAD

**Issue by mbuchetics** [realm/realm-cocoa#2570]
I have an `RLMObject` which has an array (`RLMArray`). I want to change the name of this property and move the existing array data from the old property name over to the new one. I can't seem to get this to work.

    [migration enumerateObjects:MMKUser.className block:^(RLMObject *oldObject, RLMObject *newObject) {
        newObject[@"converterPrivileges"]  = oldObject[@"privileges"];
     }

This doesn't work because the array coming from `oldObject[@"privileges"]` is stored in a different realm. I tried creating and adding new objects by copying the items but then I have a problem of duplicate primary keys after the migration.
What's the recommended way on doing this?

**Comment by tgoyne** [comment]
This is made very awkward by the fact that we don't enforce primary key uniqueness during a migration, and only at the end, and in fact I don't think there's a good way to do it with our current migration API. A bad way that should work as long as you don't have too many unique privilege objects is the following:

```objc
NSMutableDictionary *privileges = [NSMutableDictionary new];
[migration enumerateObjects:PrivilegesType.className block:^(RLMObject *oldObject, RLMObject *newObject) {
    privileges[newObject[@"primaryKey"]] = newObject;
}];
[migration enumerateObjects:MMKUser.className block:^(RLMObject *oldObject, RLMObject *newObject) {
    for (RLMObject *privilege in oldObject[@"privileges"]) {
        [newObject[@"converterPrivileges"] addObject:privileges[privilege[@"primaryKey"]]];
    }
}];
```

**Comment by jpsim** [comment]
Closing in favor of #2574 to track making this process easier.

**Comment by gebeleysis** [comment]
@tgoyne Hi, I'm trying to implement the proposed solution and it doesn't work:

    NSMutableDictionary *tracks = [NSMutableDictionary new];
    [migration enumerateObjects:[OFMRealmTrack className]
                          block:^(RLMObject *oldObject, RLMObject *newObject) {
                            NSAssert([tracks valueForKey:[newObject valueForKey:@"trackId"]] == nil, @"");
                            [tracks setObject:newObject forKey:[newObject valueForKey:@"trackId"]];
                          }];

    [migration enumerateObjects:[OFMTrackInDownloadQueueModel className]
                          block:^(RLMObject *oldObject, RLMObject *newObject) {
                            NSString *trackId = oldObject[@"serverApiTrackForTrackInDownloadQueue"][@"trackId"];
                            OFMRealmTrack *track = [tracks objectForKey:trackId];
                            newObject[@"realmTrack"] = track;
                          }];

I'm getting `Primary key property 'trackId' has duplicate values after migration.`. Seeing as there should only be 17 track objects in the DB and there are 34, it seems that whenever I'm `newObject[@"realmTrack"] = track;` there's a copy of the object added to the realm.

What is the official way to migrate a Realm DB with renaming properties of RLMObject type? The way I see it right now this is plain impossible.

Current version of Realm is 0.96.2.
