### ISSUE TITLE
Apple rejects builds submitted with 0.95.1

### ISSUE THREAD

**Issue by eskerber** [realm/realm-cocoa#2572]
In the Info.plist, it shows that Realm.framework was built with the GM of Xcode 7 (7A218) and not the App Store version (7A220). This resulted in a post-submission rejection letter:

> **Invalid Bundle** - Failed to verify bitcode in Realm.framework/Realm: error: Cannot extract bundle from MyApp.app/Frameworks/Realm.framework/Realm (armv7) ...

or:

> **Invalid Bundle** - Bitcode segments in the app binary appear to be badly formed. Use an authorized version of Xcode.

(The 2nd error is what we would get a week ago, we think Apple clarified the error message for us)

**Steps to reproduce**:
1. Use Carthage to install 0.95.1
2. Archive the app using Xcode 7 (7A220), bitcode turned off
3. Submit the app, bitcode unchecked
4. Receive rejection email shortly after upload

**Workaround:**
I was able to resolve this by rebuilding the source for 0.95.1 locally with the App Store version of Xcode and re-submitting. 

(I admit my confidence level on the "why" is 70%, but my resolution steps do work)

**Comment by mrackwitz** [comment]
Thanks for pointing out, indeed our CI machines are still on the GM version. We'll update the Xcode versions and provide new release binaries.

**Comment by zpapp** [comment]
What's the ETA on this? Not that I am in a great hurry, but if we can get a new release today, I'll wait for it instead of committing the upgrade to 0.95.1...

**Comment by tgoyne** [comment]
We should have a new release out today.

**Comment by eskerber** [comment]
Thanks for the quick response everyone :+1:

**Comment by zpapp** [comment]
And thanks for the great bug report eskerber, I am sure this will save all Ream users a lot of time.

**Comment by tgoyne** [comment]
0.95.2 is now out.

**Comment by eskerber** [comment]
App submitted successfully with 0.95.2 :+1: :+1: :+1: 

Thanks again
