### ISSUE TITLE
How to link a existed class instance to another class' property

### ISSUE THREAD

**Issue by wakaryry** [realm/realm-cocoa#2580]
In my realm database, I have had a class instance, how could I return it ang assign it to another class' property without save it again?

Do I need to use a RLMResults?

For Example:
class Dog:
property: name;
property:owner;

class Pig:
property:name;
property:owner;

class Person:
property:id(primary key)
property:name;

Now I have a Dog with a person in the realm database.
How could I get the person in the database, and then resign it to the pig without saving the person again?

Or I just donot have to make the person as a property of the Dog or Pig. I just need to save its ID?

Since when I save a Dog or Pig instance into the database, it will save a person into the Person table.
How could I avoid to save the same instance or reuse the instance?

**Comment by wakaryry** [comment]
Or I have a misunderstanding with Realm?

**Comment by mrackwitz** [comment]
Realm is a object store and not a relational database. If you link / assign the same person to a `Pig` and a `Dog`, it is the same entry which will be referenced to both, so you will automatically reuse the same instance until you explicitly create a new instance. You don't operate on copies, but instead the actual data.

```swift
let person = Person()
person.name = "Arthur"

let dog = Dog()
dog.name = "Rex"
dog.owner = person

realm.write {
    realm.add(person)
    realm.add(dog)
}

let arthur = Realm.objects(Person).filter("name = %@", "Arthur")
let pig = Pig()
pig.name = "Babe"
pig.owner = arthur

assert(pig.owner == dog.owner, "It is the same owner for both animals.")
```

**Comment by wakaryry** [comment]
@mrackwitz Thanks! Got it. 
I have a album which has a owner, and user lists who loves it, user list who comment on it. I try to save album with the users once. Then I got the problem:  primary key cannot be the same.
Now I check and save each user when I init user the album contains.
The problem has been solved.
``` objective-c
+ (instancetype) initUserWithDictionary:(NSDictionary *)dictionary{  
    NSInteger userID = [dictionary[@"uid"] integerValue];
    UserModel *aUser = [UserModel objectForPrimaryKey:@(userID)];
    
    if (aUser != nil) {
        return aUser;
    }
    
    UserModel *user = [[UserModel alloc] init];
    user.userID = [dictionary[@"uid"] integerValue];
    
    if ([UserModel isNullWith:dictionary[@"userName"]]) {
        user.userName = @"";//nil;
    } else {
        user.userName = dictionary[@"userName"];
    }

 // the first time I did not save each user when its init method
// I tried to save an album with all users related to the album, and some users are the same
// then problem has come

// now save it each time when init
// problem has been solved
   // persist data
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm addObject:user];
    }]; 
    return user;
}
```

**Comment by mrackwitz** [comment]
Oh, I see. I think what you really want to do is perhaps rather:
```objective-c
NSMutableDictionary *userData = dictionary.mutableCopy
if ([UserModel isNullWith:userData[@"userName"]]) {
    userData[@"userName"] = @"";//nil;
}
UserModel *user;
RLMRealm *realm = [RLMRealm defaultRealm];
[realm transactionWithBlock:^{
    user = [UserModel createOrUpdateInRealm:RLMRealm.defaultRealm withValue:userData];
}];
return user;
```

This takes care of auto-updating the user and creates it only if doesn't already exist via the primary key.

**Comment by wakaryry** [comment]
@mrackwitz Elegant! Thanks a lot!
