### ISSUE TITLE
Realm with real time communication and large amount of data.

### ISSUE THREAD

**Issue by sacrament** [realm/realm-cocoa#2582]
Hello there,
I am trying to use realm as a database for my app, but i don't seem to get it working properly.  When i try to add data to the database , the size of the file grows enormously and then it crashes.

The other case is when i am listening from server, even though i run it in background, yet again crashes.
Could someone give me a hint on how to use and save the data correctly with no crash

Thanks

**Comment by mrackwitz** [comment]
With large amounts of data, it is generally better to have batches of large transactions. The difficulty here is to figure out the optimal size to batch transactions, which highly depends on your schema.
Realm is a thread-safe transactional database. When you commit a new transaction, it takes until all open Realm's to the same file have advanced their commit pointer, before the previous stage can be freed from memory.
Especially if your writes are time-critical, it may help to access the Realm in an own explicit autoreleasepool and limit the number of other open Realms or avoid to have them at all.
Furthermore you could trigger manual compacts by writing a new copy with ` -[RLMRealm writeCopyToPath:]`. Note that there is no in-place compact available yet, but we're also working on reducing the overall file-size requirements of Realm.

Beside that: Are the crashes you get for both scenarios the same and related to the size? We could help better, if you would share the actual crashlogs or even a code example. Feel free to reach out to help@realm.io.

**Comment by sacrament** [comment]
Hi mrackwitz,
the crashes that i'm getting relates to adding the object or updating it. I'm in a loop and then it throws an error that realm accessed from a different thread. Meanwhile the thread is in background with new instance of realm. Sometimes it updates the data without adding new ones but the size of the file is getting larger.
The other thing is that the model, that i am updating won't allow me to update to realm. Here the app crashes

Thanks

**Comment by mrackwitz** [comment]
Seems like sharing the crash logs didn't worked out for you. But from what you describe seems to be more a general threading issue. You have to use dedicated instances of `RLMRealm` per thread, allocated each on the thread where they should be operated on. You can't pass `RLMObject` instances around between threads. If you want to propagate fetched results from a background thread to your main thread, I'd recommend to add a primary key, if needed, and pass that over.

**Comment by sacrament** [comment]
Can someone explain me why this piece of code crashes the app:

Async.background{
            let realm = try! RLMRealm(configuration: RLMRealmConfiguration.defaultConfiguration())
            realm.beginWriteTransaction()
            let js = JSON(list)
            let contact = UserView(js)
            if contact.FullName != "" && contact.GroupId != ""{
                if self.UserListHolder!.contains(contact){
                    let row:Int = self.UserListHolder![contact]
                    let user:UserView = self.UserListHolder![contact]
                    if user.GroupId == contact.GroupId{
                        user.Status = contact.Status
                        user.Active = contact.Active
                        
                        Async.main{
                            self.userListTableView!.reloadDataForRowIndexes(NSIndexSet(index: row), columnIndexes: NSIndexSet(index: 0))
                        }
                    }
                    realm.addOrUpdateObject(user)
                }
            }
            realm.commitWriteTransaction()
        }

**Comment by jpsim** [comment]
It would help to know where the exception is being thrown, and what the exception message is.

My guess is that `list` is a Realm Object that was obtained from outside the `Async.background` scope, and an exception is being thrown when executing the `let js = JSON(list)` line because `list` would then be accessed from a different thread than the one on which it was obtained.

The same could be happening with the `UserListHolder` property, if it contains a Realm object.

This could also be crashing if the RLMRealm can't be created, given that you're force-trying rather than handling possible errors at that point.

You also have a few other force unwraps (`!`) in your code that could be crashing if the `UserListHolder` property has no value when you access it.

**Comment by sacrament** [comment]
Hi jpsim,
The exception is thrown on realm.commitWriteTransaction()
As for the list, it's not a realm object its a NSString, this is the entire method that i am listening from server. UserListHolder does contain a realm object.

**Comment by jpsim** [comment]
So it certainly looks as if the culprit is `UserListHolder`. Realm objects are only accessible from the thread on which they were created.

**Comment by sacrament** [comment]
I doubt that too. Do you have any suggestions?

**Comment by jpsim** [comment]
Can you re-fetch `UserListHolder` from the thread trying to access it without having to read a property persisted by Realm on it? If the Realm object(s) wrapped by the property can be represented via their primary key(s), you could refetch it in the background thread.

**Comment by sacrament** [comment]
And by re-fetch you mean to reload data into UserListHolder? 
I have set a primary key to the Realm Object.

**Comment by jpsim** [comment]
> And by re-fetch you mean to reload data into UserListHolder? 
> I have set a primary key to the Realm Object.

Storing `UserListHolder`'s primary key and accessing *that* from a new thread to re-fetch the object will work fine.
