### ISSUE TITLE
Support for auto-incrementing properties

### ISSUE THREAD

**Issue by aemaddin** [realm/realm-cocoa#2591]
You are do a great job, and i am sorry for being lazy :D, but its important feature.

Thanks.

**Comment by jpsim** [comment]
Let's keep this open as a feature request, but this feature really shouln't be stopping you from doing anything in practice. See http://stackoverflow.com/questions/26252432/how-do-i-set-a-auto-increment-key-in-realm/26257616#26257616 for further discussion.

**Comment by mrackwitz** [comment]
We decided that we're not going to support this feature, because we would be unable to support it with simultaneous access from multiple processes.

**Comment by luccas-bandeira** [comment]
I'm new to realme, I did as mentioned above but it doubled every time I enter the method

`response.data.forEach(data => {

            const lastlojaID = realm.objects('lojas').sorted('id');
            const id = lastlojaID.length > 0 ? lastlojaID[lastlojaID.length - 1].id + 1 : 1;

            realm.write(() => {
              var idRedeLojas = ""
              const bancoLoja = data.loja.grupo.banco;

              if (data.loja.grupo.id_rede_lojas)
                idRedeLojas = data.loja.grupo.id_rede_lojas

              const novas_lojas = realm.create('lojas', {
                id: id,
                id_loja: data.loja.id_loja,
                nome_loja: data.loja.loja,
                id_grupo: data.loja.grupo.id_grupo,
                codigo_linx: data.loja.codigo_linx,
                codigo_tab_preco: data.loja.parametro.codigo_tab_preco,
                id_rede_loja: idRedeLojas,
                banco: bancoLoja.trim()
              }, 'modified');
            });
            //deleteAllLojas()
          });`



how do i not duplicate when passing in foreach? I check in the bank if it already has before entering the loop?
