### ISSUE TITLE
CGFloat & NSInteger causing migration issues on device change & restore iCloud backup

### ISSUE THREAD

**Issue by adomanico** [realm/realm-cocoa#2594]
We are seeing issues with properties defined as CGFloat or NSInteger in our realm.

If a user is on a 32 bit device (4S 5 or 5C) and then upgrades to a 64 bit device (5S, 6/6+ , 6S/6S+) and restores their phone from backup, that back up binary still has the realm for the 32 bit device and doesn't match the 64 bit device causing a migration failure.

Any reason why Realm allows CGFloat or NSInteger ? These types that are defined by arch type should not be allowed as properties.

**Comment by tgoyne** [comment]
There's no way for us to detect them. Code using CGFloat will compile to the exact same thing as code using whichever type it's an alias for on the current platform, since C typedefs don't actually create new types.

**Comment by adomanico** [comment]
What we are seeing on our end is a user who is now on a 6S (previously on a 5 or 4S) crashing on launch with a migration error " Old type 'float', new type 'double' ".

**Comment by adomanico** [comment]
and the properties responsible are of type CGFloat

**Comment by jpsim** [comment]
I'll add a note to our documentation clarifying that using platform-dependent types will lead to having platform-dependent database files.

I'm sorry that was not clear, @adomanico.

**Comment by adomanico** [comment]
OK thanks, I definitely overlooked this. Just curious: Why even allow them? Would it be simpler to just force the use of the primitive float, double , etc ?

**Comment by jpsim** [comment]
> Why even allow them? Would it be simpler to just force the use of the primitive float, double , etc ?

Not possible, as @tgoyne stated above:

> There's no way for us to detect them. Code using CGFloat will compile to the exact same thing as code using whichever type it's an alias for on the current platform, since C typedefs don't actually create new types.

**Comment by adomanico** [comment]
Ah ok so it all looks the same on your end. Ok thanks
