### ISSUE TITLE
After upgrading to 0.95.2 "No calls to throwing function..." warning

### ISSUE THREAD

**Issue by dudeinthemirror** [realm/realm-cocoa#2598]
Our Podfile's were pointing to the 'swift-2.0' branch until recently. With the release of 0.95.2, the doc states that this is not needed anymore. 
However, all the try constructs like this:
```
        do {
            let realm = try Realm()
            try realm.write {
                realm.add(self, update: true)
            }
        } catch let error as NSError {
```
now give this warning:
```
No calls to throwing functions occur within the 'try' expression.
```
Do we need to change back to the Swift-1.2 syntax and error handling in all projects ?
Please advise.
Thanks

**Comment by tgoyne** [comment]
It's complaining about the `try realm.write`, since the change to make `write()` failable isn't in 0.95.2 (as it's a breaking change). You can either remove just that `try`, or if you need to be able to handle write transactions failing, point to `master` until 0.96 is released.

**Comment by dudeinthemirror** [comment]
OK. Knowing that the write() is going to be failable again in 0.96 we can live with the warnings for now, no problem.
Thanks
