### ISSUE TITLE
Swift 2.0 try and Results<T>

### ISSUE THREAD

**Issue by MattKiazyk** [realm/realm-cocoa#2600]
Hi,

This is more of a discussion for how a person would handle a situation now in Swift 2.0 where we have to catch when calling `let realm = Realm()`

Say I have the following code:
```
class Reward: Object {
  dynamic var title = ""
  dynamic var isExpired = false

 class func validRewards() -> Results<Reward>? {
        do {
           return try Realm().objects(Reward).filter(NSPredicate(format: "isExpired = false"))
        } catch {
            return nil
        }
    }
}
```

I have a `validRewards()` function that returns `Result<Reward>`. If the original try fails - I would return nil since I'm only want to know if there are any Rewards.

I'm not a fan of the optional `Results<Reward>?` simply because i know if results.count = 0 there are none. So in my view, i now would have to unwrap the results optional everywhere. 

In what way would `Realm()` fail? In 0.95, you had the `commitWrite()` throw but in 0.95.2 it now doesn't. I think in more cases we would want `commitWrite()` to throw as if that change failed, we could rollback and do other cleanup, etc. Why was that reverted?

Again this is more of a discussion about how best to catch these errors in general. 

Thanks

-Matt

**Comment by jpsim** [comment]
I'd use `throws` in your function rather than return an Optional here:

```swift
class Reward: Object {
  class func validRewards() -> Results<Reward> throws {
    return try Realm().objects(Reward).filter(NSPredicate(format: "isExpired = false"))
  }
}
```

But really it looks as if you're better off putting this function as an extension on `Realm` so you don't have to do the error handling again if you already have a valid Realm:

```swift
extension Realm {
  func validRewards() -> Results<Reward> {
    return objects(Reward).filter("isExpired = false")
  }
}
```

**Comment by MattKiazyk** [comment]
Thank you for the direction! Definitely makes sense.
