### ISSUE TITLE
realm.writeCopyToPath Fails - "No such file or directory"

### ISSUE THREAD

**Issue by Kluskey** [realm/realm-cocoa#2605]
Hey all,

I am having an issue creating another instance of realm in /Documents on the iPhone. Whenever I run this, I receive this error: 
"Error Domain=io.realm Code=2 "open() failed: No such file or directory" UserInfo={NSLocalizedDescription=open() failed: No such file or directory, Error Code=2}"

I also attempted a similar method by using NSFileManager, with which I received this error: 
"Error Domain=NSCocoaErrorDomain Code=4 "The file “default.realm” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/mobile/Containers/Data/Application/A035E1A7-7801-473B-9359-537DC7010572/Documents/default.realm, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=file:///var/mobile/Containers/Data/Application/A035E1A7-7801-473B-9359-537DC7010572/Documents/testrealm.realm, NSFilePath=/var/mobile/Containers/Data/Application/A035E1A7-7801-473B-9359-537DC7010572/Documents/default.realm, NSUnderlyingError=0x125750800 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}"

Any thoughts? Thank you so much for your help.

    var url = NSURL()
            url = NSURL(fileURLWithPath: config.path!)
        
        if let url2 = url.URLByDeletingLastPathComponent {
            let url3 = url2.URLByAppendingPathComponent("testrealm")
            let url4 = url3.URLByAppendingPathExtension("realm")
            let defaultPath = Realm.Configuration.defaultConfiguration.path!
          //  let imgurl1 = defaultPath.URLByDeletingLastPathComponent
            //let imgurl2 = imgu
            config.path = String(url4)
            
      //      config.path = config.path! + "/\(authData.uid).realm"
            do {
                try NSFileManager.defaultManager().copyItemAtPath(defaultPath, toPath: String(url4))
            }
            catch {
                print(error)
            }
            
                    // Set this as the configuration used for the default Realm
            let realm2 = try! Realm()
            do { try realm2.writeCopyToPath(String(url4)) }
            catch {print(error)}

**Comment by Kluskey** [comment]
I've also checked with NSFileManager that the default realm exists, is readable, is writeable, and is executable.

**Comment by TimOliver** [comment]
Hi @Kluskey 

Oh dear. I've had that issue in a lot of my apps before as well. The error usually implies that there was something wrong with the file path you specified, but that sadly means there could be any number of issues with it. Usually the first point of debugging this sort of issue is to print your file path value to the console and see if anything looks incomplete/malformed

In this case, I think the issue might be the way you're converting an `NSURL` value to a `String` in order to pass it to Realm's `writeCopyToPath` method.

Instead of `String(url4)`, try `ur4.path` and let me know if that fixes it. :)

Thanks!

**Comment by Kluskey** [comment]
I owe you a beer.

Aka THANK YOU SO MUCH! I physically got a headache from trying to get this to work. Much much appreciated.

**Comment by TimOliver** [comment]
Haha my pleasure! :D

No beer required; I'm just happy I was able to help solve another user's `NSURL` woes (I'm ALWAYS Googling that one to make sure I'm choosing the right `String` method). ;D

Good luck with the rest of the app!
