### ISSUE TITLE
Cocoapods Swift 2.0 Xcode 7 Yosemite Cannot Find RealmSwift Framework File

### ISSUE THREAD

**Issue by mgreenw** [realm/realm-cocoa#2607]
Realm Version: 0.95.2
Swift 2.0
OSX Yosemite
Xcode 7.0.1

I just created a new project and used cocoa pods to add RealmSwift into the project. I am getting this error when building the project after adding Realm. I simply created a blank project, initialized Cocoapods, and installed Realm through Cocoapods. 

> Error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool:  can't open file: /Users/username/Library/Developer/Xcode/DerivedData/Appnameenebvtvzasbomufbjybndavoepfh/Build/Products/Debug-iphoneos/Appname.app/Frameworks/RealmSwift (No such file or directory)

Any suggestions? Thanks!

**Comment by jpsim** [comment]
Looks like you have stale derived data. Try:

```
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf Pods
pod install
```

PS: In the future, you can just edit your existing GitHub issues rather than creating a new one :smile: (this is a duplicate of #2606).

**Comment by mgreenw** [comment]
That fixed it, thanks!
