### ISSUE TITLE
Database offset and limit

### ISSUE THREAD

**Issue by aniketayachit** [realm/realm-cocoa#2608]
I was parsing through Realm DB for getting objects with paging. Is there any method is available to get objects from Realm DB with offset and limit.

**Comment by jpsim** [comment]
Since querying and reading are separate operations in Realm (unlike SQLite), there's no need to limit to constrain your queries simply to load less data from the disk.

From the [Queries](https://realm.io/docs/swift/latest/#queries) section of our docs:

> All queries (including queries and property access) are lazy in Realm. Data is only read when the properties are accessed.

Data access is *lazy* (as in never eagerly loaded). If you just access a single property on a single object from a query, that's the only data fetched from the disk (not accounting for disk page size).

So to do paging, just access the slice of objects you need:

```swift
do {
  let realm = try Realm()
  let all = realm.objects(Model) // => doesn't fetch all Models from disk
  let pageSize = 10
  // iterate through page 2
  let pageNumber = 2
  for offset in (pageSize * pageNumber)..<(pageSize * (pageNumber + 1)) {
    let itemAtOffset = all[offset]
    // use itemAtOffset, e.g. to populate a table view cell
  }
} catch error {
  // handle error
}
```

**Comment by pnsean** [comment]
This would be useful to have in the realm docs as the current documentation is a little misleading.

https://realm.io/docs/swift/latest/#limiting-results

That describes 'how to loop results' more than it does limiting. :)

**Comment by jpsim** [comment]
@pnsean how do you suggest limiting is appreciably different than reducing the amount that's looped over? As discussed here, item access is lazy, so accessing less of the `Results` is no different than "limiting", since that concept doesn't really apply to Realm.

**Comment by pnsean** [comment]
@jpsim I'm not suggesting that there's an appreciable difference.  I'm suggesting your example is superior to that of the one provided in the documents.  The concept applies to any data source since there are many reasons to paginate beyond just what the datasource can handle.  Any way, just my humble opinion.

**Comment by jpsim** [comment]
Ah, thanks for clarifying! It's sometimes hard to know when a code sample is valuable, so your feedback is appreciated! I've updated the wording in the existing code sample in that section of the docs, which should be live in the next ~5 minutes, and hopefully that'll help future readers understand a bit better.

**Comment by erudonja1** [comment]
You could basically create extension to Results(predefined class from Realm library) like this:

```
extension Results{
    func get <T:Object> (offset: Int, limit: Int ) -> Array<T>{
        //create variables
        var lim = 0 // how much to take
        var off = 0 // start from
        var l: Array<T> = Array<T>() // results list
        let objects = try! Realm().objects(T.self) //lazy loaded list from database
        
        //check indexes
        if off<offset && offset<objects.count - 1 { off = offset }
        if limit > objects.count - 1 { lim = objects.count}
        
        //do slicing
        for i in off..<lim{
            let dog = objects[i]
            l.append(dog)
        }
        
        //results
        return l
    }
}
```


and then usage would be something like this:

`let realm = try! Realm()`
`realm.objects(NewsDb).filter("homepageCategory = 1").get(0, limit: 5)`


ps. This is temporary solution. Optimization would be if you replace for-loop for doing slicing for some functional Swift function...

**Comment by fukemy** [comment]
> You could basically create extension to Results(predefined class from Realm library) like this:
> 
> ```
> import RealmSwift
> import ObjectMapper
> 
> 
> extension Results{
> 
>     func get <T:Object> (offset: Int, limit: Int ) -> Array<T>{
>         //create variables
>         var lim = 0 // how much to take
>         var off = 0 // start from
>         var l: Array<T> = Array<T>() // results list
> 
>         //check indexes
>         if off<=offset && offset<self.count - 1 {
>             off = offset
>         }
>         if limit > self.count {
>             lim = self.count
>         }else{
>             lim = limit
>         }
> 
>         //do slicing
>         for i in off..<lim{
>             let dog = self[i] as! T
>             l.append(dog)
>         }
> 
>         //results
>         return l
>     }
> }
> ```
> 
> and then usage would be something like this:
> 
> `let realm = try! Realm()` `realm.objects(NewsDb).filter("homepageCategory = 1").get(0, limit: 5)`
> 
> ps. This is temporary solution. Optimization would be if you replace for-loop for doing slicing for some functional Swift function...

Can u explain why i got 2 difference model list when using your code, and u how to convert back to my expected Model:
![Ảnh chụp Màn hình 2022-03-12 lúc 11 47 07](https://user-images.githubusercontent.com/8202437/158004119-e91f70bc-88e9-45f6-90a9-1a4416730cc3.png)

other unexpected result

![Ảnh chụp Màn hình 2022-03-12 lúc 11 46 52](https://user-images.githubusercontent.com/8202437/158004115-89004fa7-9012-4e3b-8269-8e9a05b0f257.png)
