### ISSUE TITLE
init(value: AnyObject) Needs Better Mapping

### ISSUE THREAD

**Issue by kylebshr** [realm/realm-cocoa#2615]
Just a thought I had:

init(value:) is really great for creating realm objects with JSON data, because it can be perfectly mapped to the class names and ready to toss in there. However, JSON naming tends_to_have_underscores while the object properties tendToHaveCamelCasing. I think the init method should map this_value in the dict to thisValue in the object. 

I looked into implemented myself, but from a quick look I couldn't even find where the parsing is. I'll keep investigating, but this might be a better job for someone more experienced — or perhaps it shouldn't exist at all, and someone can tell me why!

**Comment by jpsim** [comment]
I just commented on #694, which has been tracking this feature request for a long time. I'm closing this issue as a duplicate, but I'm happy to continue the conversation in #694 instead.
