### ISSUE TITLE
Realm-obj-c can't use with Swift ios 7, Cocoapods

### ISSUE THREAD

**Issue by Chris59160** [realm/realm-cocoa#2625]
Hi Guys,

I have read the other threads of people having the same issue, but none of the solution worked for me.

I have installed Realm-obj-c using cocoa pods. I support ios 7, so can't use the "use frameworks!".

I tried adding #import Realm/Realm.h and #import <Realm/Realm.h> , but the bridge doens't want to compile with either of them.

Every thing works perfectly when used in Objective-c classes. I haven't added the RLMSupport.swift, because it can't compile, even when I remove the import realm inside it.

I tried added Pod/** to my User Header , in recursive mod....but it screws up the Pod of Realm, basically finds errors when trying to compile.

I have no idea what to do to make it work in my Swift classes.

The project was originally in pure Objective-C, but I have started moving onto Swift, since it's what Apple wants and is forcing people to do.
I can do a work around by cloning all of my RLMObject classes into regular NSObject, and use them in Swift...but I'm pretty sure I should be able to use Realm in swift out of the box, I just don't get why it doesn't work :-(

**Comment by kishikawakatsumi** [comment]
Could you please try again the following setup steps?

1. Create Podfile and add `pod 'Realm'` like below:

    ```
platform :ios, '7.0'

target 'ObCSwiftRealm' do
  pod 'Realm'
end
```

2. Run `pod install` from command line 
3. Create bridging header file
4. Add `#import <Realm/Realm.h>` to the bridging header file.

Now, you can use Realm Objective-C from Swift. Please try to write like below:

```
let realm = RLMRealm()
```

I've also shared sample project that is setup by above steps. Please refer it:
https://github.com/kishikawakatsumi/ObCSwiftRealm

**Comment by Chris59160** [comment]
Thanks for the prompt reply.

I tried what you said, but still not working, giving me the :

Realm/Realm.h file not found for the line #import <Realm/Realm.h>

Forgot to mention I am using ABFRealmMapView, so that might be conflicting ?

**Comment by kishikawakatsumi** [comment]
@Chris59160 Could you please share your project? I could more appropriate advice if I see it.

**Comment by Chris59160** [comment]
It is a professional project....so I can't put it on git, but I could send you a zip of the project ? If you give me your email, I'll zip it to you

**Comment by kishikawakatsumi** [comment]
@Chris59160 Thanks, could you please send your project to help@realm.io ? Then I'll investigate it.

**Comment by Chris59160** [comment]
@kishikawakatsumi I just sent the email with the archive to the email you gave me.

I checked both settings, and every thing looks the same....so it's really weird

**Comment by Chris59160** [comment]
@kishikawakatsumi You can cancel your progression, I have recreated a project from scratch, copy/pasted the files from my main project....and now it is actually fine in this new project...No idea why the original one is not working....

Thank you any way. IF you find something though, I'd be interested in knowing what was wrong

**Comment by kishikawakatsumi** [comment]
@Chris59160 Sounds great. I'm going to close this since your problem is solved. I'm also interested in what is wrong. Let you know if I figure out the problems.
