### ISSUE TITLE
Cannot us MATCHES with Regex

### ISSUE THREAD

**Issue by wieseljonas** [realm/realm-cocoa#2629]
Hi I'm trying to get all objects where the name doesn't begin with a letter

    let guidPred = NSPredicate(format: "name MATCHES %@", "[^a-zA-Z].+")
    let unsortedObjects = realm.objects(Organisation).filter("name CONTAINS[c] '\(s)' OR domain CONTAINS[c] '\(s)'").filter(guidPred)

I get this error

    'Invalid operator type', reason: 'Operator 'MATCHES' not supported for string type'

**Comment by kishikawakatsumi** [comment]
Currently regex isn't supported in Realm queries with MATCH, you will need to do this manually. We are aware of this and tracking all unsupported predicates [here](https://github.com/realm/realm-cocoa/issues/1490).

**Comment by wieseljonas** [comment]
@kishikawakatsumi Thank you for the answer.

The documentation on is misleading. https://realm.io/news/nspredicate-cheatsheet/

     MATCHES -> Left hand expression equals the right hand expression using a regex - style comparison

**Comment by kishikawakatsumi** [comment]
I see. There are pink dots next to what we currently support, though. But it is a bit confusing. Thank you for pointing out.
