### ISSUE TITLE
dynamic Realm crash in keyboard extension 

### ISSUE THREAD

**Issue by ikeyboard** [realm/realm-cocoa#2630]
I try dynamic Realm(0.95.2) framework for faster build but it crash instead of static 
Please help! I don't know which one better, in this case, I have to use static one.
--Here the detail log--
dyld: Library not loaded: @rpath/Realm.framework/Realm
  Referenced from: /Users/lequysang/Library/Developer/CoreSimulator/Devices/84A5C2E9-76A1-496D-BFBD-DBC36AC88A82/data/Containers/Bundle/Application/1427FE87-0EDE-4099-9457-18C4EAF7647E/SwipeKeysEN.app/PlugIns/Englishone.appex/Englishone
  Reason: image not found
(lldb) 
----The Assembly log---
dyld`_dyld_start:
    0x7fff6dac2000 <+0>:   popq   %rdi
    0x7fff6dac2001 <+1>:   pushq  $0x0
    0x7fff6dac2003 <+3>:   movq   %rsp, %rbp
    0x7fff6dac2006 <+6>:   andq   $-0x10, %rsp
    0x7fff6dac200a <+10>:  subq   $0x10, %rsp
    0x7fff6dac200e <+14>:  movl   0x8(%rbp), %esi
    0x7fff6dac2011 <+17>:  leaq   0x10(%rbp), %rdx
    0x7fff6dac2015 <+21>:  movq   0x37abc(%rip), %r8        ; _dyld_start_static
    0x7fff6dac201c <+28>:  leaq   -0x23(%rip), %rcx         ; <+0>
    0x7fff6dac2023 <+35>:  subq   %r8, %rcx
    0x7fff6dac2026 <+38>:  leaq   -0x102d(%rip), %r8
    0x7fff6dac202d <+45>:  leaq   -0x8(%rbp), %r9
    0x7fff6dac2031 <+49>:  callq  0x7fff6dac2076            ; dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*)
->  0x7fff6dac2036 <+54>:  movq   -0x8(%rbp), %rdi //// Break here
    0x7fff6dac203a <+58>:  cmpq   $0x0, %rdi
    0x7fff6dac203e <+62>:  jne    0x7fff6dac2050            ; <+80>
    0x7fff6dac2040 <+64>:  movq   %rbp, %rsp
    0x7fff6dac2043 <+67>:  addq   $0x8, %rsp
    0x7fff6dac2047 <+71>:  movq   $0x0, %rbp
    0x7fff6dac204e <+78>:  jmpq   *%rax
    0x7fff6dac2050 <+80>:  addq   $0x10, %rsp
    0x7fff6dac2054 <+84>:  pushq  %rdi
    0x7fff6dac2055 <+85>:  movq   0x8(%rbp), %rdi
    0x7fff6dac2059 <+89>:  leaq   0x10(%rbp), %rsi
    0x7fff6dac205d <+93>:  leaq   0x8(%rsi,%rdi,8), %rdx
    0x7fff6dac2062 <+98>:  movq   %rdx, %rcx
    0x7fff6dac2065 <+101>: movq   (%rcx), %r8
    0x7fff6dac2068 <+104>: addq   $0x8, %rcx
    0x7fff6dac206c <+108>: testq  %r8, %r8
    0x7fff6dac206f <+111>: jne    0x7fff6dac2065            ; <+101>
    0x7fff6dac2071 <+113>: jmpq   *%rax
    0x7fff6dac2073 <+115>: nop

**Comment by kishikawakatsumi** [comment]
Since Realm.framework is a dynamic library you need to bundle it with your app. Because dynamic framework will be linked in runtime. You can do this by dragging it into the Embedded Libraries section in the General tab for your app/target settings.

<img width="860" alt="screen shot 2015-10-05 at 12 27 03" src="https://cloud.githubusercontent.com/assets/40610/10272553/89a5bc92-6b5c-11e5-8f06-9b8fb944174c.png">

**Comment by ikeyboard** [comment]
Thanks so much! It work now!

**Comment by kishikawakatsumi** [comment]
My pleasure!
