### ISSUE TITLE
Assign Results to List using subscript

### ISSUE THREAD

**Issue by CraigSiemens** [realm/realm-cocoa#2634]
```swift
class Conversation: Object {
    let messages = List<Message>()
}

conversation["messages"] = messages
```

This works fine if `messages` is a `RLMArray`, `RLMListBase`, or `NSArray` but does not work if it is a `Results`. It throws an exception in `RLMDynamicValidatedSet`.

As far as I can tell, `RLMDynamicSet` only requires a collection that conforms to `NSFastEnumeration` which `ResultsBase` and `RLMResults` do.

It whole be helpful if you could assign using `Results` or `RLMResults` too.

My current workaround is to create an `Array` from the `Results` before assigning

```swift
let messages = //some query
conversation["messages"] = Array(messages)
```

**Comment by jpsim** [comment]
I don't know off-hand why this doesn't work, but I hope to be able to look into this tomorrow.
