### ISSUE TITLE
Version 0.9.53 is not installable via carthage

### ISSUE THREAD

**Issue by BObereder** [realm/realm-cocoa#2638]
I can not install the newest release version 0.9.53 with carthage.
I always get something like this:

Failed to write to.../Carthage/Build/iOS/Realm.framework: Error Domain=NSCocoaErrorDomain Code=513 "“Realm.framework” couldn’t be removed because you don’t have permission to access it." UserInfo=0x7f9c02abdb20 {NSFilePath=.../Carthage/Build/iOS/Realm.framework, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7f9c02ab0f70 "The operation couldn’t be completed. Directory not empty"}

or this:

Failed to write to .../Carthage/Build/iOS/Realm.framework: Error Domain=NSCocoaErrorDomain Code=4 "The file “strip-frameworks.sh” doesn’t exist." UserInfo=0x7f8e0a213eb0 {NSSourceFilePathErrorKey=/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-archive.xCX70C/Carthage/Build/iOS/Realm.framework/strip-frameworks.sh, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=.../Carthage/Build/iOS/Realm.framework/strip-frameworks.sh, NSFilePath=/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-archive.xCX70C/Carthage/Build/iOS/Realm.framework/strip-frameworks.sh, NSUnderlyingError=0x7f8e0a26dc90 "The operation couldn’t be completed. No such file or directory"}

I had to pin it to 0.9.52 there it works perfectly.
Maybe something with the pre-built zip file went wrong?

best regards
Bernhard

**Comment by kishikawakatsumi** [comment]
What version of Carthage are you using? I heard same error from other users and I can reproduce this with 0.8 but not 0.9.2 (latest version). Carthage 0.9.2 cannot be installed via Homebrew. So you build Carthage from source or download and run the Carthage.pkg from [latest release](https://github.com/Carthage/Carthage/releases)

**Comment by BObereder** [comment]
You are right I am using the last version available with Homebrew (0.8).

**Comment by jpsim** [comment]
> You are right I am using the last version available with Homebrew (0.8).

Updating Carthage to 0.9.3 should fix it then: https://github.com/Carthage/Carthage/releases
