### ISSUE TITLE
Realm 0.95.3, Nested Object not saved

### ISSUE THREAD

**Issue by Chris59160** [realm/realm-cocoa#2639]
Hello,

I download a json array from a WebService, I use the enumerateObjectsUsingBlock to go through the array. I have put beginWriteTransaction and commitWriteTransaction before and after, respectively, the enumerateObjectsUsingBlock.

Inside each block I create RestaurantRLMObject that has regular string properties...and nested RLMObjects as well.
The issue I encountered is if I want the nested object to be persisted and saved in memory, I need to add my RestaurantRLMObject to the realm, then I can set the nested object and they will be persisted. 

However if I set the nested objects, then at the end add the RestaurantRLMObject to the realm, it won't save all of the nested objects.

Is there any reason, or it's a bug ?

Thanks for your help !!

**Comment by kishikawakatsumi** [comment]
@Chris59160 Could you please show the code snippet around `enumerateObjectsUsingBlock`?  I'd like to see your code for further investigation.

**Comment by Chris59160** [comment]
@kishikawakatsumi 
 
[realm beginWriteTransaction]; 
         
 [restaurantList enumerateObjectsUsingBlock:^(NSDictionary* obj, NSUInteger index, BOOL *stop)
 {
 [ref parseRestaurant:obj];
 }];
                 
 [realm commitWriteTransaction];

**Comment by kishikawakatsumi** [comment]
@Chris59160 Please share inside of `parseRestaurant:` method.

**Comment by Chris59160** [comment]
@kishikawakatsumi 

			RestaurantRLMObject* restaurantObj = [[RestaurantRLMObject alloc] init];

            restaurantObj._restaurant_id = [restaInfos objectForKey:FIELD_RESTAURANT];
            restaurantObj._name = [[restaInfos objectForKey:FIELD_TITLE] stringByReplacingOccurrencesOfString:@"'" withString:@"\\'"];
            
			[[RealmUtils sharedInstance]._in_memory_realm addOrUpdateObject:restaurantObj];

            NSDictionary* reviewSummaryDict = [restaInfos objectForKey:FIELD_REVIEWS];
            if (reviewSummaryDict)
            {
                ReviewSummaryRLMObject* reviewSummaryObj = [[ReviewSummaryRLMObject alloc] init];
                reviewSummaryObj._count = [[reviewSummaryDict valueForKey:FIELD_COUNT] intValue];
                reviewSummaryObj._description = [reviewSummaryDict valueForKey:FIELD_REVIEW_DESC];
                reviewSummaryObj._score = [[reviewSummaryDict valueForKey:FIELD_SCORE] floatValue];
                restaurantObj._review_summary = reviewSummaryObj;
            }
            // Best Offer
            NSDictionary* bestOfferDict = [restaInfos objectForKey:FIELD_BEST_OFFER];
            if (bestOfferDict)
            {
                BestOfferRLMObject* bestOfferObj = [[BestOfferRLMObject alloc] init];
                bestOfferObj._description = [bestOfferDict valueForKey:FIELD_DESCRIPTION];
                bestOfferObj._offer = [bestOfferDict valueForKey:FIELD_OFFER];
                bestOfferObj._score = [[bestOfferDict valueForKey:FIELD_SCORE] intValue];
                restaurantObj._best_offer = bestOfferObj;
            }
            // Book Button
            NSDictionary* bookButtonDict = [restaInfos objectForKey:FIELD_BOOK_BUTTON];
            if (bookButtonDict)
            {
                BookButtonRLMObject* bookButtonObj = [[BookButtonRLMObject alloc] init];
                bookButtonObj._label = [bookButtonDict objectForKey:FIELD_LABEL];
                if (!bookButtonObj._label)
                    bookButtonObj._label = [bookButtonDict valueForKey:FIELD_TEXT];

                tmpStr = [bookButtonDict valueForKey:FIELD_COLOR];
                if (tmpStr)
                    bookButtonObj._color = [bookButtonDict valueForKey:FIELD_COLOR];
                
                tmpStr = [bookButtonDict valueForKey:FIELD_STYLE];
                if (tmpStr)
                    bookButtonObj._style = [bookButtonDict valueForKey:FIELD_STYLE];

                restaurantObj._book_button = bookButtonObj;
            }

**Comment by Chris59160** [comment]
I can't show every thing, the code is owned by my company

**Comment by kishikawakatsumi** [comment]
@Chris59160 OK, thanks. It seems good about constructing `restaurantObj`. Are you sure to add `restaurantObj` to the Realm?

And how you confirm that nested object has not been saved? Logging?, see data file with Realm Browser? Or anything else?

**Comment by Chris59160** [comment]
Yeah I definitely add the restaurant to the realm since I access it later on.

I can confirm the nested object isn't saved since when I access the restaurant and try to access the nested object, it returns me nil and there's just no value for the object.

I don't use Realm Browser because every thing is in memory

**Comment by jpsim** [comment]
@Chris59160 were you ever able to resolve this? Based on the information you've provided us so far, there's no way for us to tell if there's a bug in Realm, if Xcode is having issues logging to the console, or if you're using Realm incorrectly.

**Comment by TimOliver** [comment]
@Chris59160 Please let us know if you were able to resolve this issue! If not, feel free to re-open this issue. :)

**Comment by Chris59160** [comment]
Hey,

The issue never really got resolved, I shuffled around how I was setting
the inner RealmObject inside the other one, and it seemed to do the trick.
I don't have the explanation on the why though...
