### ISSUE TITLE
Realm 0.95.3 fails to install via CocoaPods

### ISSUE THREAD

**Issue by rdougan** [realm/realm-cocoa#2641]
`"RLMMigration_Private.h" file not found`

The #import is in RLMMigration.mm (and other files)

**Comment by kishikawakatsumi** [comment]
@rdougan Could you please tell me more details? What version of CocoaPods are you using? Realm or RealmSwift? And could you share your Podfile?

**Comment by rdougan** [comment]
RealmSwift. This is my current podfile:

	source 'https://github.com/CocoaPods/Specs.git'

	platform :ios, '9.0'
	inhibit_all_warnings!
	use_frameworks!

	pod 'RealmSwift', '0.95.2'

Changing the version to 0.95.3 results in the error in the project.

Cocoa pods version is `0.38.2`

**Comment by kishikawakatsumi** [comment]
@rdougan I cannot reproduce the issue in my environment. Could you try first removing cache then re-install

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

If it would not resolve the issue. Could you please share a reproducible project for the investigation? Thanks.

**Comment by rdougan** [comment]
rm -fr Pods fixed the issue. Very strange. I guess something went haywire during the original update..

Thanks!!

**Comment by rdougan** [comment]
For what it's worth: I just had this happen on an update of another project. I had to delete both the CocoaPods cache and Pods folder, as you suggested.
