### ISSUE TITLE
Mutable RLMResults

### ISSUE THREAD

**Issue by eni9889** [realm/realm-cocoa#2651]
Hi,

I am using Realm.io to build a file manager. Right now I fetch a set of files into an RLMResults object and display them as a list on a table view. The issue is I would like to allow swipe to delete on a file and don't want to refresh the entire table view. There should be a way for me to remove a single object from the RLMResults collection. I would also be open to any implementation suggestions. 

cc @jpsim

**Comment by mrackwitz** [comment]
`RLMResults` is auto-updating, which means you can just delete the object from the Realm and it will be propagated to your queried results. You will need to take care of updating the table view though. A component like [RBQFetchedResultsController](https://github.com/Roobiq/RBQFetchedResultsController) may come in helpful for that.
