### ISSUE TITLE
how to add add tables during migration?

### ISSUE THREAD

**Issue by chandana1212** [realm/realm-cocoa#2652]
Hi,
I have few new tables in the new schema. How can I achieve this through migration ? After the schema change I need to access the data from the old realm file too. Is there any way to achieve that ?

**Comment by tgoyne** [comment]
Just add new `RLMObject`/`RealmSwift.Object` subclasses to your project and everything is done automatically, with no migration required.

**Comment by chandana1212** [comment]
When I add new sub classes of RealmObject it is througing io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided

**Comment by tgoyne** [comment]
You should ask for help at [realm-java](https://github.com/realm/realm-java), as this is a place where the different language bindings differ.
