### ISSUE TITLE
Compile Error: Use of unresolved identifier

### ISSUE THREAD

**Issue by rascode** [realm/realm-cocoa#2658]
In an attempt to keep my codebase clean and modular, I would like to break my classes (i.e. Models) into separate files.  However, when I do, the Realm classes defined in a separate swift files are not accessible to other Realm classes defined an alternate file.  Specifically, I receive the following pre-compile error: "Use of unresolved identifier 'ClassName' ".

I initially though the issue might be related to improper use of target (due to a number of troubleshooting articles I found on the web) but I confirmed that all of the files are referring to the same Target membership.  

Can you advise on feasibility and/or troubleshooting options?

**Comment by mrackwitz** [comment]
Have you tried cleaning your build folder and building again from scratch with your refactored model classes?

**Comment by rascode** [comment]
No, I haven't tried that yet, but I will let you know the results once I do.  Out of curiousity, is this something that I would need to do after every model refactor?

**Comment by mrackwitz** [comment]
>is this something that I would need to do after every model refactor?

No, it is more generally the first troubleshooting option, which come to mind, especially with a fast changing language like Swift. Did it help?

**Comment by rascode** [comment]
Cleaning out my build folder didn't do the trick, so I started from scratch with a clean (demo) project to see if I had the same issues with a brand new set-up.  

The new project worked as expected, allowing me to refer to Realm Classes defined in a separate swift file.  Not sure what the root cause is with my existing project, but I'm going to begin again with a clean slate and will reach out if I come across this issue in the future.

Thanks for the support!

Justin

**Comment by mrackwitz** [comment]
Happy to know that this worked out for you. This would been one of my next advices. You're welcome.
