### ISSUE TITLE
Can't mutate a persisted array outside of a write transaction.

### ISSUE THREAD

**Issue by alexliubj** [realm/realm-cocoa#2659]
Hi, 
I'm trying to query one item and delete after this query.
but it has an crash with error of `Can't mutate a persisted array outside of a write transaction` in this function and my code is like this:

Any help would be appreciate. Thanks.

```swift
let realm = try! Realm()
realm.beginWrite()
let chatList =  realm.objects(ChatListItem).filter(String(format:"to = '%@' " ,toUsername))
realm.delete(chatList)
try! realm.commitWrite()
```

**Comment by mrackwitz** [comment]
I can't see how your code would crash for mutations outside of a write transaction. Are you sure it was this code snippet, which failed? Did you got a stack trace?

But you should be careful with writing queries like that. It works only for string properties as long as they don't contain a single apostrophe. You should write them rather like `filter("to = %@", toUsername)` or `filter(NSPredicate(format: "to = %@", toUsername))`

**Comment by alexliubj** [comment]
Sorry I copied the wrong code which works well.
Thanks for your reply and advice.
