### ISSUE TITLE
Realm fails to install via CocoaPods. Problem with build.sh file on El Capitan.

### ISSUE THREAD

**Issue by asqar** [realm/realm-cocoa#2662]
```bash
$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Realm (0.95.3)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

: command not found
: command not found
: invalid option namet: pipefail
: invalid option4: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
```

The result doesn't depend on the version of Realm.
I've tried:

```bash
pod 'Realm'
```

```bash
pod 'Realm', '=0.95.2'
```

```bash
pod 'Realm', '=0.95.0'
```

```bash
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!
pod 'RealmSwift', '0.95.2'
```

```bash
pod --version
0.39.0
```

All other pods work well. I guess, it's somehow related to that I have El Capitan, OS X 10.11 (15A284).
I reinstalled a public release from AppStore again. It didn't change anything.
As I see build.sh file has Windows-style line endings. Therefore, I can't understand why everyone else has no problems with CocoaPods version on Realm.
Using static framework is not an option for me because of 3rd party libraries that depend on Realm CocoaPod.

**Comment by jpsim** [comment]
are you using a custom shell, by any chance? Realm's installation script depends on `bash`.

**Comment by asqar** [comment]
```bash
$ echo $SHELL
/bin/bash
```

**Comment by jpsim** [comment]
We've had one report of this happening several months ago as well, but we were never able to reproduce the issue or figure out why it was happening. See #1683.

Can you think of anything about your computer's configuration that might cause this @asqar? I still have no clue why this could happen.

**Comment by asqar** [comment]
I installed beta version of El Capitan. Then upgraded to the public release from the Mac AppStore.
Yesterday I re-installed El Capitan from the Mac AppStore again, bus it didn't help.

I've tried to reinstall CocoaPods several times.

My ruby version is:
```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
```

```
$ which sh
/bin/sh
```

I have problems with Homebrew updates if it matters.
```
$ brew update
error: The following untracked working tree files would be overwritten by merge:
	Library/Homebrew/extend/enumerable.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull --quiet origin refs/heads/master:refs/remotes/origin/master
```

**Comment by bdash** [comment]
I've seen similar errors in shell scripts in other contexts when the line endings of the files were incorrect (e.g., Windows-style CRLF line endings on Unix). Would you mind posting the output of the following command so we can see if the script has the expected line endings:

    xxd scripts/swift-version.sh | head

**Comment by asqar** [comment]
As I worried and @bdash suggested, I had some *misconfigured* settings for **line endings**.

I ran:
````
git config --global core.autocrlf input
````

Then completely re-installed Homebrew and Ruby.

````
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install )"
````

````
brew install ruby
````

Now everything is cool.

**Comment by jpsim** [comment]
Wow, I'm happy you two were able to resolve this. The previous report of this issue had really puzzled me.

**Comment by oktapodi** [comment]
Hey this was enough for me
`git config --global core.autocrlf input`
didnt have to re install ruby and homebrew

**Comment by hieuvo** [comment]
I suffered the same issue, to fix it I removed and re-installed cocoapods by `gem` instead of `brew` and it works.
