### ISSUE TITLE
Crash while migrating

### ISSUE THREAD

**Issue by 14lox** [realm/realm-cocoa#2674]
Some users are getting this crashing bug after getting latest version:
>RLMException RLMSetErrorOrThrow - Migration is required for object type 'PhoneNumber' due to the following errors: - Property types for 'obfuscated' property do not match. Old type 'any', new type 'string'

How can I fix this in the migration block? 

Using ObjC Realm (old version using `0.94.1`, new crashing version is using `0.95.1`) - the model is in Swift 2 and the property is defined as `dynamic var obfuscated: String?`

**Comment by mrackwitz** [comment]
I saw, that you asked this question also [on Stackoverflow](http://stackoverflow.com/questions/33117203/properties-dont-match-when-migrating-realm). As there seems to be potential from the further info you provided here that this could need some enhancement in the binding, we can also continue the further investigations over here.

So you were using the official distributed binaries and you didn't had null support to any point in time enabled. Did you used Swift 1.2 with the previous version of your app?

**Comment by 14lox** [comment]
Yep, the previous version uses Swift 1.2 (as well as ObjC). We're using Cocoapods. And unsure if null support was added - I'm relatively new to the project. How would I find that out?

The only change to the `obfuscated` property on the model object class is that the `dynamic` type was added to the property. (I can't be certain the users with the crashes were using versions before or after the change, sadly). 

(I will remove the SO post)

**Comment by mrackwitz** [comment]
Okay, good to know. But you defined the in the previous version the model already in Swift, right?

>The only change to the `obfuscated` property on the model object class is that the `dynamic` type was added to the property.

Well, that's an important change. Without `dynamic` the property is not visible to the Objective-C runtime at all, which we use to reflect the schema from the model classes. In this situation I would expect that the property `obfuscated` is just added as any other _new_ property. So I wonder about the mismatch of the migration error with the given situation. Were there further versions of the app involved? e.g.
`Swift 1.2, no dynamic => Swift 1.2, dynamic => Swift 2.0, dynamic`

**Comment by 14lox** [comment]
I think `Swift 1.2, no dynamic => Swift 1.2, dynamic => Swift 2.0, dynamic` is right.

**Comment by mrackwitz** [comment]
So one remaining question, which would be really helpful for me to investigate that further, which Realm version were used with each of these app versions?

**Comment by 14lox** [comment]
Swift 1.2 no dynamic = Realm 0.87.1
Swift 1.2 dynamic = Realm 0.87.1
Swift 2.0 dynamic  = Realm 0.94.1

Thanks for your help with this @mrackwitz

**Comment by mrackwitz** [comment]
But in your top most comment you said the crashing version was with `0.95.1`. How does that fit in?

**Comment by 14lox** [comment]
@mrackwitz my bad - the crashing version is using `0.94.1` - i have a test branch using `0.95.1`.

**Comment by mrackwitz** [comment]
Okay, it's now relatively clear to me what has happened.

## Version A

```swift
// Swift 1.2
// Realm 0.87.1
class PhoneNumber {
    var obfuscated: String?
}
```

`obfuscated` is treated as transient property, because it's completely unavailable to the runtime and so not part of the schema. We couldn't even validate that fact, because it's just not there.

## Version B

```diff
// Swift 1.2
// Realm 0.87.1
class PhoneNumber {
-    var obfuscated: String?
+    dynamic var obfuscated: String?
}
```

`obfuscated` is now available to the runtime. But it's type is optional, which isn't possible with this version of Realm yet. The optional's generic type can't be recognized at all if no default value is provided. The property type is resolved as `any`.

## Version C

```diff
-// Swift 1.2
+// Swift 2.0
-// Realm 0.87.1
+// Realm 0.94.1
class PhoneNumber {
    dynamic var obfuscated: String?
}
```

`obfuscated` is still available to the runtime. But the improved compatibility of Swift let the property type appear as `NSString` to the Objective-C runtime APIs.

---

##  Proposal for Version D

```diff
// Swift 2.0
-// Realm 0.94.1
+// Realm 0.96.0
class PhoneNumber {
    dynamic var obfuscated: String?
}
```

In addition you'd need to **provide a migration block and a schema version bump**, which will ensure that the otherwise automatic type migration can happen. Optional types are officially supported in the latest release of Realm.

**Comment by 14lox** [comment]
OK, many thanks for this. 
The migration block: it can just be empty?
```realmConfig.migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) { // empty };```

**Comment by mrackwitz** [comment]
As long as all values are in fact strings or nil. Otherwise you'd need to enumerate the objects like that:
```swift
realmConfig.migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {
    migration.enumerateObjects(PhoneNumber.className) { (old, new) in
        new["obfuscated"] = old["obfuscated"] as? String
    }
}
```
