### ISSUE TITLE
building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

### ISSUE THREAD

**Issue by bugnaum** [realm/realm-cocoa#2677]
After upgrading to Xcode , linker stops to link library from distribution when building for simulator. This issue only occurs when trying to build for arm64 simulators. I've had no problem building with armv7 simulators ("iPhone 5", "iPhone 4s", & "iPad 2"), as well as physical devices, both arm64 and armv7/s

**Comment by jpsim** [comment]
Have you tried cleaning your derived data? If that doesn't help, could you please post more information about how you're integrating Realm into your project (CocoaPods version, Carthage version, Swift version, etc.) so we can help you?

**Comment by jpsim** [comment]
Running this script should provide us with all the information we need:

```shell
echo "\`\`\`
$(sw_vers)

$(xcode-select -p)
$(xcodebuild -version)

$(which pod && pod --version)
$(test -e Podfile.lock && cat Podfile.lock | sed -nE 's/^  - (Realm(Swift)? [^:]*):?/\1/p' || echo "(not in use here)")

$(which bash && bash -version | head -n1)

$(which carthage && carthage version)
$(test -e Cartfile.resolved && cat Cartfile.resolved | grep --color=no realm || echo "(not in use here)")

$(which git && git --version)
\`\`\`" | tee /dev/tty | pbcopy
```

**Comment by bugnaum** [comment]
I already did it and the result is:

```
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27

/Applications/Xcode.app/Contents/Developer
Xcode 7.0.1
Build version 7A1001

/usr/bin/pod
0.36.3
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)


(not in use here)

/usr/bin/git
git version 2.3.8 (Apple Git-58)
```

In addition, this project is all written in objective c, as you could see, we are not using pods. It was working fine until we updated XCode because we have to fix some issues for iOS 9.

Thank you so much :)

**Comment by bugnaum** [comment]
I google about it and I found some links that didn't help me, it looks like other libraries had the same issue. However, none of them could explain very well what is the problem. I will a link here that can help you to better understand whats is going on.

https://forums.developer.apple.com/thread/13795

Thanks again!

**Comment by bugnaum** [comment]
Another one:

http://karp.id.au/post/xcode_7_linker_rules/

**Comment by jpsim** [comment]
So how are you integrating Realm? Building from source using Realm's Xcode project, or dragging in a prebuilt framework binary from our release zips?

Finally, please make sure you're using the latest stable version of Realm (0.96.0 as of this writing), as versions prior to 0.95.2 were built against beta versions of Xcode 7.

**Comment by bugnaum** [comment]
@jpsim Thanks for your help. I solved that issue, as you said, I get the latest stable version of Realm and everything is fine now.

Thanks again. :)
