### ISSUE TITLE
Using optional values for Int64 will cause app to crash

### ISSUE THREAD

**Issue by siuying** [realm/realm-cocoa#2681]
I'm running Realm 0.96, trying the RealmOptional:

```swift
import Foundation
import RealmSwift

class Person : RealmSwift.Object {
    let id = RealmOptional<Int64>(nil)
    let spouseId = RealmOptional<Int64>(nil)
}

let person = Person()
person.id.value = 1 // CRASH
```

The setter try to case the value to AnyObject, where Int64 is not.

Sample project to reproduce the issue: https://www.dropbox.com/s/2xu277zo6y1rise/RealmOptionalSample.zip?dl=0

**Comment by kishikawakatsumi** [comment]
It seems a Realm's bug. The cause of the error is `Int` are implicitly converted to NSNumber so that it can be cast to `AnyObject`. But `Int64` is not converted implicitly. The workaround is you can use `Int` instead `Int64` if possible.

**Comment by jpsim** [comment]
Looks like we should remove `Int16`, `Int32` and `Int64` from the types that conform to `RealmOptionalType`: https://github.com/realm/realm-cocoa/blob/v0.96.0/RealmSwift-swift2.0/Optional.swift#L22-L29

```swift
Int(0) as AnyObject    // => 0
Int16(0) as? AnyObject // => nil
Int32(0) as? AnyObject // => nil
Int64(0) as? AnyObject // => nil
```

**Comment by jpsim** [comment]
Actually, this should be pretty easy to fix while keeping support for those types.
