### ISSUE TITLE
0.96.0 sharedApplication unavailable

### ISSUE THREAD

**Issue by jrpinteno** [realm/realm-cocoa#2682]
In some places of my code I need to show local notifications, I use
```objective-c
[[UIApplication sharedApplication] presentLocalNotificationNow:notification];
```
That code doesn't have any problems with Realm 0.95.3 and previous versions, but since updating to 0.96.0 it fails to compile and produces next error:

```
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```

I'm not building any app extension, just a regular iOS app and the only change in codebase has been that realm update.

**Comment by matrixx** [comment]
Same issue here. Only one app, no extensions. Started when updating from 0.95.3 to 0.96.0

**Comment by jrpinteno** [comment]
Yep, you're right. I was postponing the cocoapods update due to some minor bugs in headers. But now I had the excuse to fix those.

What I'm wondering now is whether the cocoapods updates masks the problem or is totally unrelated to Realm.

**Comment by bdash** [comment]
Can you share which version of CocoaPods you were using prior to updating to 0.39?

**Comment by jrpinteno** [comment]
It was cocoapods 0.38.2, the immediate previous version.

**Comment by mrackwitz** [comment]
I guess, you're integrating your dependencies as static libraries / without the directive `use_frameworks!`? Then this was very likely caused by https://github.com/CocoaPods/CocoaPods/issues/3906, which was part of 0.39 release. So it's not a masked issue, but a resolved bug.

**Comment by jrpinteno** [comment]
Ok I see. Yes, it's a full objective-c project so I guess all dependencies are static libraries from cocoapods.

**Comment by mrackwitz** [comment]
Ok, thanks for letting us know. :relieved:
