### ISSUE TITLE
Int Property not get saved in the database

### ISSUE THREAD

**Issue by thiagoramos23** [realm/realm-cocoa#2683]
Hi, I'm really struggling with this for two days and I don't know what I'm doing wrong. 

I have a code that saves the object in the database: 

```
let traceabilityRealm = TraceabilityRealm()
traceabilityRealm.id = 1 // Int Property
traceabilityRealm.companyId = 1  // Int Property
traceabilityRealm.buildingId = 1  // Int Property
traceabilityRealm.name = "New traceability"
traceabilityRealm.guid = "E1B3A4F2-F909-49D0-8A82-C02482800BDD"

do {
  let realm = try Realm()
  try realm.write({ () -> Void in
    realm.add(traceabilityRealm)
  })
} catch _ {
  print("Error")
}
 
```

My problem is that the Int properties are not saved in the database. When I open Realm Browser I can see that only the String properties are there. 

This is my TraceabilityRealm class:

```
class TraceabilityRealm: Object {
    
    dynamic var id = NSNotFound
    dynamic var guid = ""
    dynamic var designImageData = NSData()
    dynamic var designImageUrlString = ""
    dynamic var companyId = NSNotFound
    dynamic var buildingId = NSNotFound
    
    override static func primaryKey() -> String? {
        return "guid"
    }
}
```

I would love if someone could bring some light to this.

Thanks

**Comment by mrackwitz** [comment]
Which version of Realm and Xcode do you use?

**Comment by thiagoramos23** [comment]
Hi!

XCode Version 7.0.1 (7A1001)

RealmSwfit 0.96

**Comment by bdash** [comment]
@thiagoramos23, have you tried programmatically retrieving the objects to see if the `Int` properties were saved? If you're only checking via the Realm Browser you may be seeing realm/realm-browser-osx#78, a layout issue on OS X El Capitan that causes some numeric properties to appear empty.

**Comment by thiagoramos23** [comment]
Hi, @bdash! Thanks for the reply. Yep, you are right. I guess i was trying to retrieve the object before commit the transaction. 

Thank you. You saved my day!

**Comment by bdash** [comment]
Glad we could help!
