### ISSUE TITLE
Provide a dynamic method to get List<DynamicObject> properties

### ISSUE THREAD

**Issue by tom-sparo** [realm/realm-cocoa#2685]
Say I have a realm object:

```swift
class TestObject : Object {
    let otherObjects = List<TestObject>()
}
```

If I want to use key value coding:
```swift
let testObject = TestObject()
let aList = testObject.valueForKey("otherObjects")!
aList is List<Object> // false
aList is List<TestObject> // true
```
I have to know the exact type of that relationship.  This makes certain reflection-based approaches sort of difficult, for instance if I want to blindly walk over an object tree performing some action.

Is there a better way to get the KVC to behave, to get generics to behave, or to walk over an object tree?  I see that I can reflect on the objectSchema and get a string representation of the List'd field... but it's a String and I remember NSClassFromString being kind of a bear.  So if I could get the type in the List from the objectSchema that's another option.

Sorry this is sorta hacky!

Just for reference, is this an effect of List<> generics?  Because with normal arrays in swift this works:

```swift
class A: NSObject {}

class B: A {}

class Something: NSObject {
    let array: [B] = [B(), B()]
}

let arr = Something().valueForKey("array")
arr is Array<A> // true
arr is Array<B> // true
arr is Array<Int> // false
```

**Comment by jpsim** [comment]
> Is there a better way to get the KVC to behave, to get generics to behave, or to walk over an object tree?

I think our dynamic API would be better suited for this kind of work. If you can represent the objects you'll be acting on as a query, you could then use [`Realm.dynamicObjects()`](https://github.com/realm/realm-cocoa/blob/v0.96.0/RealmSwift-swift2.0/Realm.swift#L411-L428).

Although we officially support our dynamic API and it is technically "public", we don't generally include it in most of our online documentation because it's really only useful in specific scenarios, but it sounds like yours applies.

If you need something we don't have in our dynamic API, please let us know and we'll gladly consider adding it. For example an `Object.dynamicList(listProperty: String) -> List<DynamicObject>` method in your case.

> Just for reference, is this an effect of List<> generics?

I don't know off the top of my head, but I can dig deeper into this if you'd like.

**Comment by tom-sparo** [comment]
I did some more digging and it turns out that Array/Set/Dict all have different semantics when it comes to the `is` operator :rage: .  Their `is` operator does what looks like a protocol match (IMO the expected behavior), whereas the `is` operator on generics that we can write does a strict match.  How frustrating!  Hadn't noticed/forgot about it.

I thought that List<> was maybe something closer to a true swift Array.  I would go digging into the Array code to see exactly how that's all working but we'll have to wait until Swift open sources.

I'll take a look into dynamicObjects.  Many thanks!

**Comment by jpsim** [comment]
:+1:

**Comment by tom-sparo** [comment]
Hey so I took a look at the dynamic methods, and you're absolutely right.  I think there's no way right now to blindly get the `List<>` off an object using KVC if you don't already know what type of list to expect -- this is because as above none of the `is` or `as?` operators can cast to anything but the exact type.  So it'd be great if there were a new dynamic method on object that returned a `List<DynamicObject>` (or a `List<Object>`.  Really anything that can be reflected) for a RLMProperty.  The other option is to change KVC behavior to return a `List<DynamicObject>` or again even `List<Object>` rather than a `List<T>`, but this requires unsuspecting users to have to cast their objects as their iterate through a List and maybe it's better to just add the extra method?

Let me know what you think.  This exact method looks like it already exists, but internally. [`Object.listForProperty()`](https://github.com/realm/realm-cocoa/blob/v0.96.0/RealmSwift-swift2.0/Object.swift#L227-L230).

**Comment by jpsim** [comment]
Alright @tom-sparo, I've made this issue into a feature request. You're welcome to submit a pull request for this feature yourself, as I don't think we'll be tackling this ourselves in the near future.

**Comment by tom-sparo** [comment]
:+1:  I'll see if I can manage it!
