### ISSUE TITLE
schemaVersionAtPath cause crash after upgrading from 0.95.0 to 0.96.0

### ISSUE THREAD

**Issue by almujtaba** [realm/realm-cocoa#2686]
I've a database created with (Realm **0.95.0**) using **Objective-C** and I used to check its version using

    [RLMRealm schemaVersionAtPath:error:]

But after upgrading to (Realm **0.96.0**) .. I can't check the version of that database which is created before.
Instead I'm getting this error 

> *** Terminating app due to uncaught exception 'RLMException', reason:
> 'Unsupported Realm file format version'

When I replace the realm to the old (Realm **0.95.0**) .. the app works perfectly.
And when go back to (Realm **0.96.0**) it gives a crash

This is my complete method which run in **main.m**

    NSString *documentsDirectory = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject];
    NSString *dir = [documentsDirectory stringByAppendingPathComponent:@"database.realm"];
    
    uint64_t database_ver = 3;
    BOOL fileExists = [[NSFileManager defaultManager] fileExistsAtPath:dir];
    if (fileExists) {
        uint64_t old_database_ver = [RLMRealm schemaVersionAtPath:dir error:nil];
        if (old_database_ver != database_ver) {
            NSLog(@"Deleted Realm");
            NSLog(@"Old database ver : %ld",(long)old_database_ver);
            NSLog(@"New database ver : %ld",(long)database_ver);
            [[NSFileManager defaultManager] removeItemAtPath:dir error:nil];
        }
    }
    
    RLMRealmConfiguration *configuration = [RLMRealmConfiguration defaultConfiguration];
    configuration.path = dir;
    
    RLMMigrationBlock migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {
        NSLog(@"Migration complete.");
    };
    
    // set the schema version and migration block for the default realm
    configuration.schemaVersion = database_ver;
    configuration.migrationBlock = migrationBlock;
    [RLMRealmConfiguration setDefaultConfiguration:configuration];
    RLMRealm *realm = [RLMRealm defaultRealm]; // Create realm pointing to default file

**Comment by mrackwitz** [comment]
The problem here is that there were breaking file format changes introduced with version 0.96. Therefore the realm file needs to be migrated on disk, which only may happen when it was opened once in *read-write mode*. `[RLMRealm schemaVersionAtPath:error:]` relies on opening the realm in *read-only mode* to read the current schema version. This is causing the crash.

As a workaround you may want to open the realm file first in read-write mode with a dynamic schema. This will make sure that the file format migrations happens, but you won't get any errors through the schema not-matching the new version of your schema.
You need to make use of a private Realm API for that declared in `RLMRealm_Private.h`. It is also accessible via `@import Realm.Private;` if you need to rely on module imports. You may want to do that in a dedicated file to make sure that you don't access any other APIs not intended for public usage.

```objective-c
if (fileExists) {
    // Force file format migration
    NSError *error;
    [[RLMRealm alloc] initWithPath:dir key:key readOnly:YES inMemory:NO dynamic:YES error:&error];
    NSAssert(error == nil);

    // … get schema version etc …
}

// Setup your configuration to apply the schema migrations and open the defaultRealm just like usual
```

**Comment by almujtaba** [comment]
Thanks for your help ... @mrackwitz 

I found the explanation a little bit complicated so i solved the problem without using `schemaVersionAtPath:` ..
By storing the DB Version in the **UserDefaults** file like this :

    NSString *documentsDirectory = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject];
    NSString *dir = [documentsDirectory stringByAppendingPathComponent:@"database.realm"];

    uint64_t database_ver = 3;
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    NSInteger old_database_ver = [[defaults objectForKey:@"database_ver"] integerValue];
    if( old_database_ver !=  database_ver){
        BOOL fileExists = [[NSFileManager defaultManager] fileExistsAtPath:dir];
        if (fileExists) {
            NSLog(@"Deleted Realm");
            NSLog(@"Old database ver : %ld",(long)old_database_ver);
            NSLog(@"New database ver : %ld",(long)database_ver);
            [[NSFileManager defaultManager] removeItemAtPath:dir error:nil];
        }
        [defaults setInteger:(NSInteger)database_ver forKey:@"database_ver"];
    }

    // Setup Realm configuration

**Comment by mrackwitz** [comment]
Thanks for sharing your workaround. So if you use your database primarily as a cache layer and can restore everything in it on a schema mismatch, then this is may be a suitable solution as well.
