### ISSUE TITLE
NSData in model

### ISSUE THREAD

**Issue by happiehappie** [realm/realm-cocoa#2689]
I see that in the documentation example Person may have NSData in the model as optional

    class Person: Object {
        dynamic var name = ""
        dynamic var picture: NSData? = nil // optionals supported
        let dogs = List<Dog>()
    }

But I have the following model 

    class PhotoType: Object {
    
        dynamic var id = 0
        dynamic var name = ""
        dynamic var imageData: NSData? = nil
    
        override static func primaryKey() -> String? {
            return "id"
        }
    
    }

But it raised this exception? 
Terminating app due to uncaught exception 'RLMException', reason: 'Only 'object' properties can be made optional, and property 'imageData' is of type 'data'.'

Any ideas?

**Comment by kishikawakatsumi** [comment]
@happiehappie  Realm supports NULL properties from ver. `0.96.0`. `0.95.x` or earlier version does not support optional properties other than `Object` and `List`. If you'd like to make the property nullable, you should use the latest version (0.96.0) of Realm.

**Comment by happiehappie** [comment]
I've ran pod install. Is the current pod version earlier than 0.95.x?

**Comment by kishikawakatsumi** [comment]
No, 0.96.0 is also on CocoaPods. Can you try `pod update`? `pod install` does not update existing pods.

**Comment by happiehappie** [comment]
Ahh, that's silly of me. Thank you very much for your guidance. :) Greatly appreciated

**Comment by happiehappie** [comment]
There goes my whole afternoon
