### ISSUE TITLE
leftovers after removal?

### ISSUE THREAD

**Issue by kristofer** [realm/realm-cocoa#2692]
in the ios simulator...
so in my code, I'm trying to remove the realm file, completely, so I can restore it with one I have saved in cloudkit.
```
                    let realmPath = try Realm().path
                    print("** resetModel: realm to be removed. \(realmPath)")
                    try NSFileManager.defaultManager().removeItemAtPath(realmPath)
```
problem is after this code, I end up with 
```
Aeneid:FF593330-4093-4A11-9FE4-566A44A78FD7 kyounger$ ls -l
total 8
drwxr-xr-x  3 kyounger  staff   102 Oct 16 08:29 Library
-rw-r--r--  1 kyounger  staff  1320 Oct 16 09:49 default-archive.realm.lock
prw-------  1 kyounger  staff     0 Oct 16 09:48 default-archive.realm.note
```
afterward. (and yes, the default realm file in my case is "default-archive.realm", in a shared App Group. 

then when I create a new realm file, the realm seems to be in some weird state? would the vestiges of these old locks be messing with the new db in some way?? should I remove them as well?

**Comment by kristofer** [comment]
or even more, after the removal of "default-archive.realm"

```
-rw-r--r--  1 kyounger  staff  1320 Oct 16 10:19 default-archive.realm.lock
-rw-r--r--  1 kyounger  staff   136 Oct 16 10:19 default-archive.realm.log
-rw-r--r--  1 kyounger  staff  4096 Oct 16 10:19 default-archive.realm.log_a
-rw-r--r--  1 kyounger  staff  4096 Oct 16 10:19 default-archive.realm.log_b
prw-------  1 kyounger  staff     0 Oct 16 10:19 default-archive.realm.note
```

**Comment by jpsim** [comment]
The `lock`, `log` and `note` files shouldn't affect new Realm files, or cause them to be in a "weird" state. What do you mean by that? These files are used for Realm operations (lock file for resource locks, log files for transaction logs, and note file for notifications).

**Comment by kristofer** [comment]
there was a single object inside of the realm file, and I wondered if I had a strong reference to the realm someplace, and was shooting the realmfile out from under the cache? 

but no, it was a failure of my realm init code. bad dog, no biscuit.

**Comment by mrackwitz** [comment]
Anyway I understand your curiosity about those files and created #2695 for that reason. :+1:
