### ISSUE TITLE
Make `schemaVersionAtPath:` work for file format 2 files

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2693]
Not very useful otherwise. See #2686.

**Comment by jpsim** [comment]
This hasn't been an issue so far, so I'm closing this.

**Comment by mrackwitz** [comment]
There was another instance of that. The only workaround we have to offer so far, which retains data, has to make use of a private API for schema-free access. I'd hesitate adding this behavior suggested here at this point. So this might motivate us to properly expose the dynamic property on `RLMRealmConfiguration` in a non-private header?
