### ISSUE TITLE
API to get the file format version of a file at a given path

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2694]
Needed for the Realm Browser (realm/realm-browser-osx#87) and would probably be useful for some app developers as well. We should discuss if this should be a private or public API.

**Comment by TimOliver** [comment]
Do we still need this? Or is the API that explicitly disables file format upgrades sufficient after all?

**Comment by jpsim** [comment]
We haven't received requests for this functionality, so I'd be ok to close this until someone needs it.
