### ISSUE TITLE
Error: Object has been deleted or invalidated.

### ISSUE THREAD

**Issue by lucianocn** [realm/realm-cocoa#2698]
Sometimes (rarely but occurs) I got error `Object has been deleted or invalidated.`, when trying to modify my model object with a property or inside AFnetworking Block. Can anyone help me to find what I'm doing wrong?

--------------------------
**Error - Case 1:**

Code:
```objc
- (void)myFunction {
    Model *model = [Model objectForPrimaryKey:1];

    if (model) {
        [self updateModel:model];
    }
}

- (void)updateModel:(Model *)model {

    __bock = model; // Should I use __block?
    
    AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
    [manager PUT:@"http://www.example.com" parameters:parameters success:^(AFHTTPRequestOperation *operation, id responseObject) {
  
        [[RLMRealm defaultRealm] beginWriteTransaction];
       model.updated = YES; // Crash: Object has been deleted or invalidated.
        [[RLMRealm defaultRealm] commitWriteTransaction];

    } failure:nil];
}
```

--------------------------
**Error - Case 2:**

Property:
```objc
    @property (strong, nonatomic) Model *model;
```

Code:
```objc
- (void)myFunction {
    Model *model = [Model objectForPrimaryKey:1];
   
    if (model) {
        self.model = model;

        UIAlertView * alert = [[UIAlertView alloc] initWithTitle:@"" message:@"Would you like to edit the model?" delegate:self cancelButtonTitle:@"Cancel" otherButtonTitles:@"Ok", nil];
        [alert show];
    }
}
```

UIAlertView Delegate:
```objc
- (void)alertView:(UIAlertView *)alertView clickedButtonAtIndex:(NSInteger)buttonIndex {
    if (buttonIndex == 1) {
        [[RLMRealm defaultRealm] beginWriteTransaction];
        self.model.updated = YES; // Crash: Object has been deleted or invalidated.
        [[RLMRealm defaultRealm] commitWriteTransaction];
    }
}
```

Thanks.

**Comment by kishikawakatsumi** [comment]
@lucianocn Because `PUT` method of `AFHTTPRequestOperationManager` performs asynchronously, there is a possibility that the Model object has been deleted before completionHandler is called.

Similarly, for case 2, there is a possibility that the Model object has been deleted while the UIAlertView is displayed.

Therefore, I strongly recommend that you obtain a model object just before you want to change to ensure that it isn't changed during the method. If other threads can change the model objects, you also ensure not to be changed during the method.

**Comment by mrackwitz** [comment]
For cross-reference: This question was also [answered on StackOverflow](http://stackoverflow.com/questions/33179281/error-object-has-been-deleted-or-invalidated-realm). I'll close this issue here. Feel free though to ask for further clarification here or there if needed.
