### ISSUE TITLE
Realm 0.96.0 static lib for Xcode 7 crash when query but not crash in 0.95.3

### ISSUE THREAD

**Issue by ikeyboard** [realm/realm-cocoa#2704]
I use this code to query but crash when update to 0.96.0 (static fro Xcode 7).
I really don't know how to change code for this version or it maybe have bug.
I copy 0.95.3 back and everything work fine.
Please help! Thanks!
--Code---

        __autoreleasing NSError* error = nil;
        RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
        config.path = UNIREALMPATH;
        
        config.readOnly = YES;
        
        RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:&error];
        
        RLMResults<NoneObject *> *results = [[NoneObject objectsInRealm:realm where:@"word BEGINSWITH[c] %@",string] sortedResultsUsingProperty:@"fre" ascending:NO]; //Crash line

------This is crash Log-----
   0x103460387 <+162>: testq  %r12, %r12
    0x10346038a <+165>: je     0x1034603f0               ; <+267> at RLMObject.mm:119
    0x10346038c <+167>: movq   0x3415b5(%rip), %rdi      ; (void *)0x000000010422fb00: NSString
    0x103460393 <+174>: movq   0x33a2d6(%rip), %rsi      ; "class"
    0x10346039a <+181>: callq  *0x2bd340(%rip)           ; (void *)0x0000000105c00800: objc_msgSend
    0x1034603a0 <+187>: movq   0x33a359(%rip), %rsi      ; "isKindOfClass:"
    0x1034603a7 <+194>: movq   %r12, %rdi
    0x1034603aa <+197>: movq   %rax, %rdx
    0x1034603ad <+200>: callq  *0x2bd32d(%rip)           ; (void *)0x0000000105c00800: objc_msgSend
    0x1034603b3 <+206>: testb  %al, %al
    0x1034603b5 <+208>: jne    0x1034603f0               ; <+267> at RLMObject.mm:119
    0x1034603b7 <+210>: movq   0x341452(%rip), %rdi      ; (void *)0x0000000106ab40d0: NSException
    0x1034603be <+217>: leaq   0x2cc853(%rip), %rax      ; RLMExceptionName
    0x1034603c5 <+224>: movq   (%rax), %rdx
    0x1034603c8 <+227>: movq   0x339da9(%rip), %rsi      ; "exceptionWithName:reason:userInfo:"
    0x1034603cf <+234>: leaq   0x2dcd52(%rip), %rcx      ; @"predicate must be an NSString with optional format va_list"
    0x1034603d6 <+241>: xorl   %r8d, %r8d
    0x1034603d9 <+244>: callq  *0x2bd301(%rip)           ; (void *)0x0000000105c00800: objc_msgSend
    0x1034603df <+250>: movq   %rax, %rdi
    0x1034603e2 <+253>: callq  0x103658b0c               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x1034603e7 <+258>: movq   %rax, %rdi
    0x1034603ea <+261>: callq  *0x2bd300(%rip)           ; (void *)0x0000000105bfdd70: objc_release
    0x1034603f0 <+267>: movq   0x340d81(%rip), %rsi      ; "objectsInRealm:where:args:"
    0x1034603f7 <+274>: leaq   -0x50(%rbp), %r8
    0x1034603fb <+278>: movq   %r15, %rdi
    0x1034603fe <+281>: movq   %r14, %rdx
    0x103460401 <+284>: movq   %r12, %rcx
    0x103460404 <+287>: callq  *0x2bd2d6(%rip)           ; (void *)0x0000000105c00800: objc_msgSend
    0x10346040a <+293>: movq   %rax, %rdi //Crash break here.

**Comment by kishikawakatsumi** [comment]
@ikeyboard I think that the actual problem has occurred when you open the file. Can you please make sure the `error` object passed to `realmWithConfiguration:config:` is `nil` after the method has called?

**Comment by ikeyboard** [comment]
Thanks! Yes, I log the error. 
This is realm file in bundle and I read as Read only.
In this case, how to make change in file for 0.96.0?
----
Error Domain=io.realm Code=2 "Unsupported Realm file format version" UserInfo={NSFilePath=/Users/username/Library/Developer/CoreSimulator/Devices/84A5C2E9-76A1-496D-BFBD-DBC36AC88A82/data/Containers/Bundle/Application/5A446F8C-4B86-498A-B372-4158CF207DE6/qsnotes.app/1.realm, NSLocalizedDescription=Unsupported Realm file format version, Error Code=2}

**Comment by kishikawakatsumi** [comment]
@ikeyboard OK, it is clear to me. Realm v0.96 introduced new file format. The Realm file was updated automatically when the file was opened. But the file in app bundle cannot be written. Because app bundle is not permitted to write.

So you’re bundling a Realm file in your app, it will have to be updated and replaced to use this new file format.

For more information, please read "Automatic Conversion" section of this article.
https://realm.io/news/realm-objc-swift-0.96.0/

**Comment by ikeyboard** [comment]
This new features make me sad. It's not useful, why must it overwrite to readonly file. 
I don't want to copy to document folder before read because it make my app size bigger and not efficient in App Extension. 
Could you report it as a request to make readonly file in bundle back? 
Thank you for great support!

**Comment by kishikawakatsumi** [comment]
@ikeyboard No, you do not need to copy to document folder. You can just bundle upgraded file into your app bundle. 

So, first, upgrade your Ream file to new format. You can use an OS X app or your iOS app running in the simulator. Then the file bundle into your app.

**Comment by hiragram** [comment]
@kishikawakatsumi 
What is the easiest way to convert existing bundled realm file to newer format with contained data?

**Comment by kishikawakatsumi** [comment]
@hiragram Open the file with the latest release of [Realm Browser 0.96.1](https://github.com/realm/realm-browser-osx/releases/tag/0.96.1) **Note: AppStore version has not supported new file format yet**

Or read the file using the simulator.

If you read even once, the file format will be upgraded.

**Comment by hiragram** [comment]
@kishikawakatsumi I have just successfully upgraded realm file using Realm browser. Thank you for your help!
