### ISSUE TITLE
linked one-to-one properties become nil after a write commit

### ISSUE THREAD

**Issue by azraelx23** [realm/realm-cocoa#2705]
note that Settings is a realm object, and has 4 linked properties (alarm,pomodoroTheme,breakTheme,daySession) , and worked fine before commit:

<img width="855" alt="screen shot 2015-10-19 at 5 42 09 pm" src="https://cloud.githubusercontent.com/assets/950254/10575756/db6ddcb2-7688-11e5-935a-a4e822f1813f.png">

but after a single step after a commit write, see that those properties become nil:

<img width="820" alt="screen shot 2015-10-19 at 5 42 32 pm" src="https://cloud.githubusercontent.com/assets/950254/10575759/e4eefde8-7688-11e5-9dcd-13bee1c19444.png">

however, seen on Realm Browser, those properties are persisted just fine to disk:

<img width="947" alt="screen shot 2015-10-19 at 5 47 05 pm" src="https://cloud.githubusercontent.com/assets/950254/10575838/71fb0ace-7689-11e5-97fb-f00a0552d247.png">

**Comment by azraelx23** [comment]
this is using the latest 0.96

**Comment by azraelx23** [comment]
model definitions:

```swift
class Settings: Object {
    dynamic var id = 0
    
    dynamic var currentActiveDaySession: DaySession?
    dynamic var currentActivePomodoro : Pomodoro?
    dynamic var currentActiveReminder : Reminder?
    
    dynamic var currentPomodoroTheme : Theme?
    dynamic var currentBreakTheme : Theme?
    dynamic var currentAlarm : Alarm?

override static func primaryKey() -> String? {
        return "id"
    }
}

class Alarm: Object {
    dynamic var alarmId = 0
    dynamic var alarmName = ""
    dynamic var alarmSoundFile = ""

override static func primaryKey() -> String? {
        return "alarmId"
    }
}

class Theme: Object {
    dynamic var themeId = 0
    dynamic var themeName = ""

override static func primaryKey() -> String? {
        return "themeId"
    }
}

class DaySession: Object {
    dynamic var daySessionId = ""
    dynamic var hasFinishedDailyGoal = false
    
    let pomodoros = List<Pomodoro>()
    
    override static func primaryKey() -> String? {
        return "daySessionId"
    }
}

class Pomodoro: Object {
    dynamic var pomodoroId = NSDate.now().timeIdentifier()
    
    dynamic var pomodoroStartDate = NSDate()
    dynamic var pomodoroEndDate = NSDate()

override static func primaryKey() -> String? {
        return "pomodoroId"
    }
}
```

**Comment by kishikawakatsumi** [comment]
@azraelx23  Realm does not copy any data until actually access the properties. When access the properties, Realm fetch the data directly from its file. So Realm does not store any data to its ivar. Additionally, Realm object will change to another class at the moment it is persisted. That's why you cannot see any values via the debugger and nil out all value after committed.

If you'd like to debug object's value, you can use "Print Description" feature of debugger: Right click the object, and select "Print Description of ...".

**Comment by azraelx23** [comment]
thanks for the explanation, will try again tomorrow!

**Comment by azraelx23** [comment]
an update: 'Print Description of' on the debugger still yields all nil description, but accessing it and print it out like so works :  

```swift
print("theme 1 \(self.currentSettings!.currentPomodoroTheme)")
        print("theme 2 \(self.currentSettings!.currentBreakTheme)")
        print("day session \(self.currentSettings!.currentActiveDaySession)")
        print("alarm \(self.currentSettings!.currentAlarm)")
```

**Comment by jpsim** [comment]
`po` (Print Description of) should work...
