### ISSUE TITLE
Library size

### ISSUE THREAD

**Issue by chico** [realm/realm-cocoa#2710]
I'm using Realm via Cocoapods. Once my app is built up in XCode, I can see that libRealm.a is 23mb, which makes my app very bloated. Is there anyway of sliming it down?

https://cocoapods.org/pods/Realm is reporting that it's even bigger, Integration Size = 67500 kb.

**Comment by jpsim** [comment]
From our [FAQ](https://realm.io/docs/objc/latest/#how-big-is-the-realm-library):

> How big is the Realm library?
> Once your app is built for release, Realm should only add around 1MB to its size. The releases we distribute are significantly larger because they include support for the iOS and watchOS simulators, some debug symbols, and bitcode, which are all stripped by Xcode automatically when you build your app.

**Comment by chico** [comment]
Ok thanks, should've thought of checking FAQ :), I will re-check the size of the app when submitting to the app store, hopefully won't be too bloated.
