### ISSUE TITLE
Installation use Cocoapods ERROR

### ISSUE THREAD

**Issue by junjielu** [realm/realm-cocoa#2711]
```
Installing Realm (0.96.0)
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.94.0
Downloading core failed. Please try again once you have an Internet connection.
```

Cocoapods version:0.39.0

**Comment by zhaochengfeng** [comment]
you need VPN

**Comment by junjielu** [comment]
@zhaochengfeng doesn't work

**Comment by jpsim** [comment]
Hi @junjielu, I'm sorry you're affected by this. We've been getting more and more reports about this from China, and have created a GitHub issue with more details about what's happening and what you can do about it.

Please refer to #2713 for more information.
