### ISSUE TITLE
Duplicate interface definition for class 'RLMObject'

### ISSUE THREAD

**Issue by jeremypiednoel** [realm/realm-cocoa#2712]
Hi, I have an issue with my app (using realm 0.90.6) 

     Duplicate interface definition for class 'RLMObject'
    /Pods/Realm/Realm/RLMArray.mm:22:9: In file included from /Pods/Realm/Realm/RLMArray.mm:22:
    /Pods/Realm/Realm/RLMObjectSchema.h:20:9: In file included from /Pods/Realm/Realm/RLMObjectSchema.h:20:
    /Pods/Realm/Realm/RLMProperty.h:21:9: In file included from /Pods/Realm/Realm/RLMProperty.h:21:

Thank you.

**Comment by mrackwitz** [comment]
The release of version 0.90.6 is quite a while ago. I'd generally recommend to update to last version. That would make it easier to assist you. You'll need to update CocoaPods to version 0.39 therefore.
In any case, we'll need [further info](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#speeding-things-up-runner) to help.

**Comment by jeremypiednoel** [comment]
OK, i found the issue.
It was because of cocoapods 0.39.
Should rollback in 0.38

**Comment by r618** [comment]
getting the same compile error as OP
@jeremypiednoel thanks for digging into it, downgrading to cocoapods 0.38 helped, but running not latest is clearly not ideal.
Does anybody know whether is this cocoapods issue ?

**Comment by bdash** [comment]
@r618, which version of Realm are you using?

**Comment by r618** [comment]
Hi @bdash, the latest pod, i.e. in Podfile:
pod 'Realm'

after downgrading cocoapods to 0.38 it spit out few warnings, but at least it's compilable now

**Comment by bdash** [comment]
Can you please file a new issue with all of the information from the [Filing Issues section of CONTRIBUTING.md](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues)? That will help us understand what you're seeing and investigate the problem. This existing issue was reported against a much older version of Realm, and what you're seeing is quite likely to be different than what was reported here.

**Comment by r618** [comment]
Will try, if possible, it might be clashing with other pods, I will start from empty Xcode workspace.

**Comment by r618** [comment]
ok, it seems to be Xcode / cocoapods issue with reporting
I have version selection in Podfile:
```
platform :ios, '6.0'
pod 'Realm'
```
and, of course, I haven't noticed minimal deployment target for Realm, which is iOS 7.

The pod correctly didn't install into new clean project without any changes, but after creating new project, setting its minimal deployment target to iOS 6.0 and building it, the pod installed successfully afterwards, leading to the OP error. -/

Is there any chance Realm will work on iOS6 ? I am about to test but the chances are probably not very high :(

**Comment by mrackwitz** [comment]
>Is there any chance Realm will work on iOS6 ? I am about to test but the chances are probably not very high :(

No, sadly Realm can't easily support iOS 6. There are some dependencies in the code, which rely on basic APIs which were introduced with iOS 7.

**Comment by srinathp90** [comment]
Simple solution here..it worked for me

Go to edit scheme -> Select Build -> Build option untick the Parallelize Build

Now run your App
