### ISSUE TITLE
RealmSwift with Xcode Version 7.1 beta 3 (7B85)

### ISSUE THREAD

**Issue by structre40** [realm/realm-cocoa#2716]
I have tried using Realm build 0.96.1 with XCode 7.1 Beta 3 and get an error when trying to import RealmSwift. 
The error is: "<path>MasterViewController.swift:12:8: Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again: <path>RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule"

I have tried downloading latest source and using "build.sh build" but I still get the same message when including the build frameworks from build\ios\swift-2.0\*.framework. 

Any ideas when the latest swift frameworks will be released?

**Comment by jpsim** [comment]
The latest release (0.96.1) compiles with Xcode 7.1 Beta 3, but you'll have to build it with that version of Xcode for it to be compatible with Swift 2.1.

Looks like you've been using versions of Realm Swift compiled with Xcode 7.0.x. You can specify which Swift version to build for by specifying the `REALM_SWIFT_VERSION=2.1` environment variable when running `build.sh build`, or you could use CocoaPods, which would enforce that Realm Swift is built with the same version of Xcode as your own project.

**Comment by marlowcharite** [comment]
I'm getting the same issue with the new release of Xcode 7.1. I build through Carthage though. @jpsim any suggestions?

**Comment by structre40** [comment]
After upgrading to the released version of XCode 7.1 and building per jpsim's instructions, all is working again. Thanks!

**Comment by codywinton** [comment]
@jpsim - Can you provide some more details of how to reproduce your Swift 2.1 issue resolution?

**Comment by codywinton** [comment]
Never mind. Got it. Similar to Swift 1.2 installation, but with 2.1 as the variable: https://realm.io/docs/swift/latest/#installation-swift-12

**Comment by hardinm78** [comment]
@codywinton i updated to xcode 7.1(swift 2.1) this morning and now i am stuck with this issue on my current project (my first realm project) and most of the stuff said above is beyond my current knowledge, (i know how to add the realm frameworks to xcode and really not much else outside of swift/xcode/objc). can you you advise me or point me to a version thats already built for swift 2.1?

**Comment by codywinton** [comment]
@hardinm78 -

1. Clone the repo or download as a Zip file and open: https://github.com/realm/realm-cocoa
2. Open up a terminal window (mac) or some comparable alternative.
3. On mac, you'd change to the directory of the repo via. `cd ~/Path/To/The/Repo` command in the terminal window. `cd` stands for change directory.
4. Then, run this command: `REALM_SWIFT_VERSION=2.1 sh build.sh build` which will cause the project to be updated to Swift 2.1
5. Then, you'll be able to drag the frameworks back into your Project.

**Comment by hardinm78** [comment]
@codywinton you are an angel sent from heaven, that worked! i am back in business!

**Comment by codeslubber** [comment]
Got me most of the way there. I was using the strip bash script. That threw up an error so I removed it. Now I am getting dyld library not loaded. Reason: image not found.

**Comment by codeslubber** [comment]
Nevermind: remembered how to solve that. Added back to Embedded Binaries. Thanks!

**Comment by moogle19** [comment]
Hi, I get following error when try building RealmSwift with Xcode 7.1:

    ** BUILD FAILED **


    The following build commands failed:
        CompileC build/DerivedData/Realm/Build/Intermediates/Realm.build/Release- 
        iphoneos/iOS.build/Objects-normal/armv7/RLMConstants.o Realm/RLMConstants.m normal armv7 
        objective-c com.apple.compilers.llvm.clang.1_0.compiler
        (1 failure)

I did set REALM_SWIFT_VERSION=2.1, also tried "sh build.sh build", "sh build.sh ios-swift","sh build.sh ios-static" and "sh build.sh ios-dynamic", but everything failed.

**Comment by timanglade** [comment]
We’re also working to make a new release of Realm compiled with Xcode 7.1 which should make these errors go away. Sorry for the delay!

**Comment by codywinton** [comment]
@moogle19 - Did you try Cleaning your project and deleting the DerivedData?

**Comment by moogle19** [comment]
@codywinton Yes, even tried to do clone the repo again and also used different versions and tested the tg-xcode-7.1 branch. No success. :(

**Comment by codywinton** [comment]
@moogle19 - Then I think you've gone beyond my diagnostic ideas.

**Comment by jakecraige** [comment]
@timanglade Any ETA on that release? For those of us using carthage we're pretty much blocked until it's released :cry:

**Comment by Dudi00** [comment]
@jakecraige You could always install Xcode7 thill new release.

**Comment by jakecraige** [comment]
@Dudi00 Good idea. Thanks!

**Comment by Dudi00** [comment]
@jakecraige yea, no problem, glad that I could help :)

**Comment by timanglade** [comment]
@jakecraige Working on it at the moment! @bdash and @tgoyne are trying to get something out the door asap but the CI upgrade was more complicated than expected due to vacations and other complications. Keep an eye on this issue, our blog or Twitter!

**Comment by shahankit** [comment]
thanks @codywinton

**Comment by dziedziela** [comment]
Is there any chance that Realm is not compatible with 7.1? Thanks guys!

**Comment by bdash** [comment]
Realm 0.96.2 was released today and is compatible with Xcode 7.1 and Swift 2.1.

**Comment by GregIngelmo** [comment]
Building with Realm 0.96.2 Carthage fixes the issue, @bdash @jakecraige

**Comment by amywtlin** [comment]
Had the same issue and now it's working again! Thanks guys

**Comment by dziedziela** [comment]
Awesome! Thanks guys!
