### ISSUE TITLE
Support for .NET / Xamarin / Unity / Windows

### ISSUE THREAD

**Issue by timanglade** [realm/realm-cocoa#2722]
For lack of a better place, I’m creating an issue here to track interest in Realm eventually coming to .NET platforms.

* Xamarin (at least iOS, Android, maybe more),
* Unity (at least iOS, Android, maybe more),
* potentially Windows (primarily targeting phones),
* but maybe other .NET platforms variants as well.

You can register your interest here so we can reach out to you for any eventual beta releases: http://goo.gl/forms/C9HpxRvbqp

**Comment by jpsim** [comment]
Realm Xamarin [has launched](https://realm.io/news/introducing-realm-xamarin/)! 🎉 

We're tracking other Unity, Windows and other .NET platforms on the [realm-dotnet repo](https://github.com/realm/realm-dotnet) now. Specifically:

* Unity Support: realm/realm-dotnet#141
* UWP Support: realm/realm-dotnet#509
* WPF Support: realm/realm-dotnet#526
