### ISSUE TITLE
Carthage 0.93 error: Realm.framework/Realm: The file was not recognized as a valid object file

### ISSUE THREAD

**Issue by eskerber** [realm/realm-cocoa#2726]
Been running into an issue that's been driving me nuts - especially when I don't see another issue like this registered. This reproduces for all members of our team.

This reproduces on anything > Carthage .9 for us.

```bash
 carthage update --use-submodules --use-ssh --platform iOS
```
Cartfile:
```ruby
github "realm/realm-cocoa" ~> 0.96.0
```

Results in the following error:

```bash
error: cannot parse the debug map for "/Users/erik/Project-iOS/Carthage/Build/iOS/Realm.framework/Realm": The file was not recognized as a valid object file
```

Any ideas?

**Comment by kishikawakatsumi** [comment]
@eskerber That's because Carthage doesn't support building Realm Swift from source. Carthage doesn't support multiple projects in a single repo.

You can use Carthage binaries instead: just `carthage update`

**Comment by eskerber** [comment]
Thanks @kishikawakatsumi and sorry I missed the notification.

I'm going to try again tomorrow, but are you saying that:

```
carthage update
```

will grab the pre-built binaries but, that this won't? 

```
 carthage update --use-submodules --use-ssh --platform iOS
```

(Understand you aren't a Carthage dev - but likely have run into this yourself as publishing a framework for Carthage so help is much appreciated :+1: )

**Comment by mrackwitz** [comment]
That's right, you can't use prebuilt binaries and submodules at the same time.

**Comment by eskerber** [comment]
Thanks for the help @mrackwitz , @kishikawakatsumi. A coworker of mine claimed you _could_ in previous versions (which explains why I never got this error in .8). At least, for now, you've helped me white box the problem so I know what's going on. Maybe/hopefully it's supported in future versions.

Thanks again!
