### ISSUE TITLE
delete Object not delete RLMArray property, delete cascade not work?

### ISSUE THREAD

**Issue by com314159** [realm/realm-cocoa#2728]
when you call  

    [realm deleteObject:rlmObject];

it will delete rlmObject , but the RLMArray object associated with with the rlmObject will not deleted.  To delete it, I need to call

    [realm deleteObjects:rlmObject.assets];  // assets is a RLMArray

This will become a big problem. some object will leak, and the realm will become larger and larger. People will forget to delete RLMArray property

I hope you can provide delete cascade method to delete all the object and all the property.

**Comment by com314159** [comment]
ok , I write a Helper to delete model cascade. if you like it , you can check out it at 

   https://github.com/com314159/RealmDeleteCascad

**Comment by kishikawakatsumi** [comment]
We have an issue tracking adding cascading deletes, #1186, so you'll see any updates on that front over there. We are working on that.

And, your repository seems empty for me. Did you forget push to the repository?

**Comment by com314159** [comment]
it pushing now

**Comment by com314159** [comment]
I have write a Helper , you can just delete all the object with code.  I just read all the Realm property value and delete it.

    [RLMHelper deleteModelCascad:model inRealm:realm];

**Comment by kishikawakatsumi** [comment]
It sounds like your workaround is no problem.

**Comment by demoker** [comment]
pefect
