### ISSUE TITLE
Comparing values of aggregate operators crashes

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#2730]
RealmSwift 0.96.1 crashes in the following scenario with reason ```*** Terminating app due to uncaught exception 'Invalid property name', reason: 'Property 'b.@sum.sum' not found in object of type 'A''``` when querying value of an aggregate operator against another value of aggregate operator.

```
class A: Object {
    
    let b = List<B>()
    
}

class B: Object {
    
    dynamic var sum = 0
    dynamic var other = 0
    
}

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    // Override point for customization after application launch.
    
    let a1 = A()
    
    let b1 = B()
    b1.sum = 5
    b1.other = 5
    let b2 = B()
    b2.sum = 10
    b2.other = 5
    
    a1.b.append(b1)
    a1.b.append(b2)

    let realm = try! Realm()
    try! realm.write {
        realm.deleteAll()
        realm.add([a1, b1, b2])
    }
    
    let results = realm.objects(A).filter("b.@sum.sum != b.@sum.other") // This will crash.
    print(results)
    
    return true
}
```

I have also sent this as a sample project to help@realm.io.

**Comment by bdash** [comment]
At the moment we only support key paths in comparisons when the other side of the operator is a constant. We're tracking this limitation in our support for NSPredicate in #1490. This falls in the same group as "multi-level object equality link queries" in that list.
