### ISSUE TITLE
RealmSwift Object DynamicList referenced from: expected in: crash

### ISSUE THREAD

**Issue by bryan1anderson** [realm/realm-cocoa#2731]
dyld: Symbol not found: __TFC10RealmSwift6Object11dynamicListfS0_FSSGCS_4ListCS_13DynamicObject_
  Referenced from: /var/mobile/Containers/Bundle/Application/15474483-948F-49BF-BC63-E0F396D14D69/LGCY.app/LGCY
  Expected in: /private/var/mobile/Containers/Bundle/Application/15474483-948F-49BF-BC63-E0F396D14D69/LGCY.app/Frameworks/RealmSwift.framework/RealmSwift
 in /var/mobile/Containers/Bundle/Application/15474483-948F-49BF-BC63-E0F396D14D69/LGCY.app/LGCY

This started to occur after I updated to RealmSwift 0.96.1

I run my app, the app immediately crashes and this shows up in the log

**Comment by bryan1anderson** [comment]
A little more info: Running xcode 7.1, on El Capitan 11.1, and iOS 9.1

I was able to fix it by removing RealmSwift from my podfile, updating, then add it again to the podfile and pod install

**Comment by kishikawakatsumi** [comment]
Glad your resolved whatever this was.
