### ISSUE TITLE
RLM won't compile

### ISSUE THREAD

**Issue by PatrickOfRubiconRealm** [realm/realm-cocoa#2739]
![screen shot 2015-10-23 at 9 54 20 am](https://cloud.githubusercontent.com/assets/15097348/10699513/20e84e68-796c-11e5-96b2-8ed6542c93fc.png)

**Comment by bdash** [comment]
These errors indicate that Realm is being built with the incorrect compiler flags. It expects to be built with `-std=c++14`, but in your case appears to be building using `-std=c++11`.

Can you share some information about how you're integrating Realm into your project? Are you using CocoaPods, Carthage, or something else? You can run the script in [CONTRIBUTING.md](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#speeding-things-up-runner) to gather some information that's useful in helping us to diagnose these sorts of problems.

**Comment by PatrickOfRubiconRealm** [comment]
Hey thanks for the quick update. I used cocoa pods, although i reverted back to 95.3.

Don't know if this is still valid:

/Applications/Xcode.app/Contents/Developer
Xcode 7.0.1
Build version 7A1001

/usr/bin/pod
0.37.2
Realm (0.95.3)
RealmSwift (0.95.3)
RealmSwift (~> 0.95.3)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)


(not in use here)

/usr/bin/git
git version 2.3.8 (Apple Git-58)

**Comment by bdash** [comment]
The issue is likely the older version of CocoaPods you're using. Realm Swift 0.96 requires at least CocoaPods 0.39.0. Can you try updating CocoaPods to the latest version and see if you have better luck with Realm Swift 0.96?

**Comment by PatrickOfRubiconRealm** [comment]
Thanks so much
