### ISSUE TITLE
Realm createOrUpdateInDefaultRealmWithValue breaks after adding an `NSData` object

### ISSUE THREAD

**Issue by MikeSilvis** [realm/realm-cocoa#2742]
See the following repository for an example

https://github.com/MikeSilvis/realm-create-or-update/blob/master/Realm%20Create%20Or%20Update/ViewController.m

That results in the following output: 

```
2015-10-23 14:56:10.690 Realm Create Or Update[69017:3580508] initial creation and find of ticket objectID: 123 withSeat: 2
2015-10-23 14:56:10.696 Realm Create Or Update[69017:3580508] Verify seat is still persisted even though we didnt add it again objectID: 123 seat: 
2015-10-23 14:56:11.324 Realm Create Or Update[69017:3580858] after we added a PDF to the ticket: 123 seat:  length: 2716227
2015-10-23 14:56:11.359 Realm Create Or Update[69017:3580858] Now that we created and saved a new obj 123 seat:  and pdf 0
```

**Comment by kishikawakatsumi** [comment]
I think this is the intended behavior. If you'd like to update object partially, you should not include properties not to be updated to the object.

You passed ticket object that has zero length pdf data property by default, so existing object will be overwritten.

If you'd like to partial update, you can do following:

```
[realmTwo transactionWithBlock:^{
    [MSTicket createOrUpdateInDefaultRealmWithValue:@{@"objectID": objectId, @"seat": @"3"}];
}];
```

**Comment by MikeSilvis** [comment]
@kishikawakatsumi why would a `defaultPropertyValues` override an existing property value? The default value should only be called if there isn't something in realm to be used otherwise because Realm doesn't understand nil.

**Comment by MikeSilvis** [comment]
I can't really use your example without knowing if the object exists or not already in the database. Basically `createOrUpdateInDefaultRealmWithValue` is pointless because no matter what I need to do a db lookup and then conditionalize around what to do if it is or not

**Comment by kishikawakatsumi** [comment]
Are you talking about line 77-86, right?

`defaultPropertyValues` doesn't overwrite existing value. You create new object at line 77 https://github.com/MikeSilvis/realm-create-or-update/blob/master/Realm%20Create%20Or%20Update/ViewController.m#L77, that is filled by default values. Then you passed the object to `createOrUpdateInDefaultRealmWithValue:` https://github.com/MikeSilvis/realm-create-or-update/blob/master/Realm%20Create%20Or%20Update/ViewController.m#L81, so existing object will be overwrite default values.

Do I understand your queastion correctly?

**Comment by MikeSilvis** [comment]
@kishikawakatsumi yes. `defaultValues` in my opinion should not be called basically until we go to save we see the object doesn't exists and then we add them just to ensure things aren't nil. Because if I just do this:


```
MSTicket *ticket = [MSTicket new];
NSLog(@"seat is: %@", ticket.seat);
```

It is going to return nil, not empty string.

Basically what you are implying is I need to always write something like this:

```
MSTicket *dbTicket = [MSTicket objectWithPrimaryKey:@"123"];
if (dbTicket) {
 // update my values
}
else {
  // Create the new object.
}
```

Essentially I am just trying to get around the unnecessary conditional and IMO realm should just see that the property is nil, and not try and set it on an existing object.

**Comment by kishikawakatsumi** [comment]
> `defaultValues` in my opinion should not be called basically until we go to save 

No, the objects will be filled with default values immediately after the object was created.

https://github.com/realm/realm-cocoa/blob/master/Realm/RLMObjectBase.mm#L45-L48


Your code is one of the solution, since Realm does not support partial update yet https://github.com/realm/realm-cocoa/issues/2644.

Or passed by dictionary as I mentioned.

**Comment by MikeSilvis** [comment]
@kishikawakatsumi okay. I guess basically i'm asking for just a partial update function. Seems like a pain in the ass to always do the look up / slow, but w/e
