### ISSUE TITLE
Could not cast value of type 'RealmSwift.DynamicObject' to MyCustomObject during migration

### ISSUE THREAD

**Issue by perwyl** [realm/realm-cocoa#2747]
During RealmSwift migration, i want to migrate from `dynamic var customObject: CustomObject` to `let customObjectList = List<CustomObject>()`. `CustomObject` is type of `Object`

This is the chunk of code within migration
```
let newList = List<CustomObject>()
if oldObject!["customObject"] != nil {

   print(oldObject!["customObject"])                  
   var obj = oldObject!["customObject"]
   var result: CustomObject = obj as! CustomObject //Crash
   farList.append(result)
}
newObject!["customObjectList"] = newList
```

>
Could not cast value of type 'RealmSwift.DynamicObject' (0x1015c82d0) to 'AppName.CustomObject' (0x1006e5550).

How do i achieve what i want?  Get the `CustomObject` from the older realm and update it(append) to the `CustomObjectList` in the newer realm? 

<link>http://stackoverflow.com/questions/33338568/could-not-cast-value-of-type-realmswift-dynamicobject-to-mycustomobject-during</link>

**Comment by kishikawakatsumi** [comment]
For cross-reference: This question was also answered on StackOverflow. I'll close this issue here. Feel free though to ask for further clarification here or there if needed.
