### ISSUE TITLE
Build fails on Xcode 7.0.1

### ISSUE THREAD

**Issue by hiragram** [realm/realm-cocoa#2751]
I have just created new Xcode project and installed Realm using Carthage.

Cartfile is as follows:

```
github "realm/realm-cocoa"
```

Next ```carthage update --platform iOS``` and tried to build project on Xcode but failed.
Error message says:
```
Module file was created by a newer version of the compiler: /path/to/project/Carthage/Build/iOS/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64.swiftmodule
```
This error appears on the line ```import RealmSwift```.

Version of Xcode is 7.0.1.

I have not install Xcode 7.1 so I cannot understand why ```Module file was created by a newer version of the compiler```.

What causes this error? Realm/Xcode/Carthage/Swift ...?

**Comment by bdash** [comment]
Carthage uses prebuilt binaries of Realm. These binaries come from our release packages on GitHub which are built using Xcode 7.1. This means that you'll need to upgrade to Xcode 7.1 to use Carthage with Realm Swift 0.96.2 or newer. If you're unable to upgrade to Xcode 7.1 for some reason, our documentation [contains information about building Realm from source for Xcode 7.0 / Swift 2.0](https://realm.io/docs/swift/latest/#installation-swift-20).

**Comment by hiragram** [comment]
@bdash Thank you for very quick reply. :pray: 

I have just succeeded to build with Cartfile :

```
github "realm/realm-cocoa" == 0.96.1
```

I know that I should use the latest version of Realm, but I cannot upgrade to Xcode 7.1 immediately (but I will in a month).
I will use older version of Realm till I upgrade Xcode.

Thank you very much for your solving my issue!
