### ISSUE TITLE
- Property 'key' is no longer optional.

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#2752]
realm version:0.96.1

![2015-10-27 5 03 34](https://cloud.githubusercontent.com/assets/3182964/10753669/a41e4ef4-7ccd-11e5-83d7-7b47e77f7fab.png)
![2015-10-27 5 13 57](https://cloud.githubusercontent.com/assets/3182964/10753798/5cb47d30-7cce-11e5-8e79-6be4750df2e9.png)

**Comment by mrackwitz** [comment]
String properties became optional by default with the release of 0.96 and support for optional properties. 

If you explicitly declare them as required and didn't declared that before, you need to provide a schema version bump and at least an empty migration block.

If this all occurred in development, you should rather reset the Realm in the iOS simulator either by deleted the file at the path, or resetting the simulator content and settings from the Simulator.app menu.
