### ISSUE TITLE
Build Error...

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#2753]
latest version:0.96.2

![2015-10-27 6 26 50](https://cloud.githubusercontent.com/assets/3182964/10755666/089ee12a-7cda-11e5-89c7-ab3079183d33.png)

**Comment by bdash** [comment]
Can you please run the [script in CONTRIBUTING.md](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#speeding-things-up-runner) to gather some information that'll help us understand why you're hitting this?

**Comment by hengchengfei** [comment]
0.96.1 or the old version compile ok.

<pre><code>
hengchengfeimatoMac-mini:eval hengchengfei$ echo "\`\`\`
> $(sw_vers)
> 
> $(xcode-select -p)
> $(xcodebuild -version)
> 
> $(which pod && pod --version)
> $(test -e Podfile.lock && cat Podfile.lock | sed -nE 's/^  - (Realm(Swift)? [^:]*):?/\1/p' || echo "(not in use here)")
> 
> $(which bash && bash -version | head -n1)
> 
> $(which carthage && carthage version)
> $(test -e Cartfile.resolved && cat Cartfile.resolved | grep --color=no realm || echo "(not in use here)")
> 
> $(which git && git --version)
> \`\`\`" | tee /dev/tty | pbcopy

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
```
ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A284

/Applications/Xcode.app/Contents/Developer
Xcode 7.1
Build version 7B91b

/usr/local/bin/pod
0.39.0
Realm (0.96.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.7.1
(not in use here)

/usr/bin/git
git version 2.4.9 (Apple Git-60)
```
</code></pre>

**Comment by bdash** [comment]
We're tracking this failure in #2736.
