### ISSUE TITLE
Realm will only run on the simulator, not the phone

### ISSUE THREAD

**Issue by matarali** [realm/realm-cocoa#2760]
I have looked high and low, followed all the advice I can find online, followed the limited documentation but I still cannot resolve this.
Realm works fine in the simulator but does not load on a real phone.
I have installed it with CocoaPods.

One thing, the Realm.framework file under Pods > Frameworks is red but from what I have read that means nothing?

When I add this script to Embed Pods Frameworks 

 ${SRCROOT}/Pods/Target Support Files/Pods-PhoneBook/Pods-PhoneBook-frameworks.sh 
it gives me an error:

```
/Users/*****/Library/Developer/Xcode/DerivedData/Bay_Ferry-gsgmafaphpoghlekccykdqsmqqoi/Build/Intermediates/Bay Ferry.build/Debug-iphoneos/swipre take two.build/Script-92AEBFA81BD9240C007D2C0D.sh: line 2: /Users/*****/Documents/X-code: No such file or directory
```

My Podfile has:

 ```ruby
target 'swipre take two' do
  use_frameworks!
  pod 'RealmSwift'
end
```

**Comment by mrackwitz** [comment]
You can only run on the simulator and not on the actual device, if you don't embed frameworks in your app.

So from what you describe, I understand that you commented out the contents of the **Embed Pods Frameworks** build phase, which was added by CocoaPods to your *PhoneBook* target.
Now you're re-adding the previous contents and it is causing errors on build. Is that right?
Is the error you pasted, really the full error, beside that you redacted your system user name?

> `line 2: /Users/*****/Documents/X-code: No such file or directory`

Can you post the resolved build setting `SRCROOT`?

**Comment by matarali** [comment]
OK.. I have rebuilt the entire app and am still having the same problem..

Here is there error:

PhaseScriptExecution Embed\ Pods\ Frameworks /Users/hayley/Library/Developer/Xcode/DerivedData/Bay_Ferry-exwenfemrtjntmglayibwlrrcqai/Build/Intermediates/Bay\ Ferry.build/Debug-iphoneos/swipre\ take\ two.build/Script-A95392205227735EF6B6C18C.sh
    cd "/Users/hayley/Documents/X-code files/Bay Ferry"
    /bin/sh -c \"/Users/hayley/Library/Developer/Xcode/DerivedData/Bay_Ferry-exwenfemrtjntmglayibwlrrcqai/Build/Intermediates/Bay\ Ferry.build/Debug-iphoneos/swipre\ take\ two.build/Script-A95392205227735EF6B6C18C.sh\"

/Users/hayley/Library/Developer/Xcode/DerivedData/Bay_Ferry-exwenfemrtjntmglayibwlrrcqai/Build/Intermediates/Bay Ferry.build/Debug-iphoneos/swipre take two.build/Script-A95392205227735EF6B6C18C.sh: line 2: /Users/hayley/Documents/X-code: No such file or directory

Here is the code that Coco installed in Embed Pod Frameworks:

"${SRCROOT}/Pods/Target Support Files/Pods-swipre take two/Pods-swipre take two-frameworks.sh"

How do I find out what ${SRCROOT} is?

**Comment by mrackwitz** [comment]
It is very likely related because you have spaces in your paths and they are not properly escaped somewhere. It could be an issue in the CocoaPods script. That's an issue with CocoaPods, which should be fixed. For now, I'd recommend to move your development directory into a path without spaces and dashes, because there might be other scripts involved which don't handle those cases properly.  Alternatively it might already help to quote the path of the script, which is called from the *Embed Frameworks* build phase.

**Comment by matarali** [comment]
Thanks..  you  said "I'd recommend to move your development directory into a path without spaces and dashes"

How do you do this without messing everything up? I have tried it a few times but it seems there are paths everywhere that require manual updating..

**Comment by mrackwitz** [comment]
Renaming a project and it's targets is not really trivial. You would need to change at least:
* the name of the project file
* the name of the app targets
* the source root directory
* adopt the moved source root directory by the project
* the build setting `INFOPLIST_FILE` as it encodes the source root path

It might be easier to re-create the project from scratch.

**Comment by mnshah** [comment]
I'm having the same issue where the app immediately crashes on the phone but works in the simulator. I'm using Realm (objective-c not swift) installed via cocoapods. When inspecting the crash logs on the device, it says the error is:
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x000000000000000c

This happens when we are making some fairly innocuous queries to a realm. The crash occurs when checking the thread that Realm is using:

```
// throw an exception if the realm is being used from the wrong thread
static inline void RLMCheckThread(__unsafe_unretained RLMRealm *const realm) {
    if (realm->_threadID != pthread_mach_thread_np(pthread_self())) {
        @throw RLMException(@"Realm accessed from incorrect thread");
    }
}
```

The crash happens at the if statement. The logs do not show it throwing the RLMException, rather it shows a bad memory access. This is quite concerning, is 0.96 supposed to be a stable release? I have not gotten it to work in the simplest of use cases.

**Comment by jpsim** [comment]
@mnshah you seem to be hitting an entirely different problem than what's described in this issue. In the future, please post new issues as new issues, it'll help us triage and get back to you sooner.

> This happens when we are making some fairly innocuous queries to a realm. The crash occurs when checking the thread that Realm is using:

The complexity of the query has little bearing on which thread you run it from. To enforce thread safety, Realm operations are confined to the thread on which a given object/results/realm was created. In your case, you seem to be accessing one of those on the wrong thread, so Realm throws an exception.

> The crash happens at the if statement. The logs do not show it throwing the RLMException, rather it shows a bad memory access. This is quite concerning, is 0.96 supposed to be a stable release? I have not gotten it to work in the simplest of use cases.

This can happen when throwing exceptions. I suggest you enable a symbolic breakpoint for all exceptions in Xcode to help you debug where you may be accessing Realm from the wrong thread.

**Comment by jpsim** [comment]
@matarali I'm closing this issue as this is a CocoaPods bug, as mentioned by @mrackwitz. The steps posted in https://github.com/realm/realm-cocoa/issues/2760#issuecomment-152528126 should help work around that issue until it can be fixed in CocoaPods itself.
