### ISSUE TITLE
'RLMArray_Private.hpp' file not found

### ISSUE THREAD

**Issue by erinvilair** [realm/realm-cocoa#2762]
I recently updated to pod Realm 0.96.2 and RealmSwift 0.96.2. When I run my app, system reported that 'RLMArray_Private.hpp' file not found. How can I fix the issue?

**Comment by mrackwitz** [comment]
Can you provide [some further information](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#speeding-things-up-runner), as especially: Which version of CocoaPods do you use?

That might be related to #2701 then it would help to just run `pod install` again. If that shouldn't help, the following things might help as well:
* clean DerivedData / build folder (⌥⇧⌘K)
* `sudo xcode-select -r` / make sure to use the same Xcode application path as the one which is selected for command line tools
* close and re-open Xcode
* delete the Pods directory via `rm -rf Pods` or even better using [`pod deintegrate`](https://github.com/kylef/cocoapods-deintegrate) and re-install from scratch again

**Comment by erinvilair** [comment]
Thanks a lot for your help! I followed your instructions but Xcode still told me . I’m using cocoa pods of version 0.38.2, and my Realm folder in Pods folder miss Headers folder and Frameworks order, like this. I broke the pod update process several days ago, it may be the reason. If I update cocoapod to 0.39 may help?

**Comment by erinvilair** [comment]
Problem Solved! Thank you very much! I re-installed cocoapods to the latest version and re-installed Realm and RealmSwift, and it works just fine.

**Comment by mrackwitz** [comment]
Excellent! :+1: Thanks for reporting back.
