### ISSUE TITLE
Include dSYMs in prebuilt binaries for release zips & Carthage binaries

### ISSUE THREAD

**Issue by solidcell** [realm/realm-cocoa#2766]
Is there a reason that the pre-built `Carthage.framework.zip` does not contain a `dSYM`?

**Comment by jpsim** [comment]
No specific reason other than we haven't gone through the trouble of automating the generation & copying of dSYM files. I'll update this issue to identify this as a feature request that we can track.

We'd appreciate a pull request to support this, @solidcell!
