### ISSUE TITLE
realm file is incompatible if model has PrimaryKey

### ISSUE THREAD

**Issue by zaki50** [realm/realm-cocoa#2770]
from slack.

Realm Swift reports an error when opening the realm file generated on Android.

model definition in Java:

```
public class DataItem extends RealmObject {
    @PrimaryKey
    private int id;

    // seter and getter here
}
```

model definition in Swift:

```
class DataItem: Object {
    dynamic var id = 0

    override static func primaryKey() -> String? {
        return "id"
    }
}
```

reported error:

```
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=0 "Migration is required for object type 'DataItem' due to the following errors:
- Property 'id' has been made a primary key." UserInfo={NSLocalizedDescription=Migration is required for object type 'DataItem' due to the following errors:
- Property 'id' has been made a primary key.}: file /Library/Caches/com.apple.xbs/Sources/swiftlang_PONDEROSA/swiftlang_PONDEROSA-700.1.101.6/src/swift/stdlib/public/core/ErrorType.swift, line 50
```

**Comment by zaki50** [comment]
@kishikawakatsumi confirmed that error occurred in the following combination:
- Java 0.82.2/ObjC 0.95.3
- Java 0.84.1/ObjC 0.96.2

**Comment by zaki50** [comment]
`Realm Java` and `Realm Swift` uses different table name in `pk` table.

![pk_table_of_android](https://cloud.githubusercontent.com/assets/406660/10844874/a6fef7d8-7f46-11e5-9e17-be2a5dd5a1f0.png)

![pk_table_of_ios](https://cloud.githubusercontent.com/assets/406660/10844876/aaf312c0-7f46-11e5-95c6-5704eabd2fe6.png)

**Comment by kishikawakatsumi** [comment]
I confirmed that the class name in the pk_table has not had a prefix from Realm ObjC 0.85 (it was the first version introduced primary key feature) to latest one.

I saw pk_table of the file generated 0.85 by a debugger, and also confirmed migration exception was occurred opening in Java. If primary key annotation would be removed, it works fine.

Any thoughts? @tgoyne @jpsim @cmelchior

**Comment by cmelchior** [comment]
I reopened the Java ticket, as it is a Java responsibility then. I am completely baffled we missed this however :(

The task now is the following IMO: 
1) Create automated test-suite to test interoperability as discussed before, i.e. each platform creates a test suite that A) can create a set of test files and B) run those files through a series of unit tests. Then it should be relatively easy to create a set of test files for each version released that can be sent to the other platform to verify we do not regress.

2) Realm Java will fix the bug on our side: 1) Stop appending "class_" to names in the pk_table 2) Make a fallback so it works in both cases with and without "class_" prefix.

**Comment by zaki50** [comment]
I pushed a code of android app which I used for investigation.

https://github.com/zaki50/realm_file_viewer_by_stetho

**Comment by cmelchior** [comment]
Realm-Java merged a fix for this problem here: https://github.com/realm/realm-java/pull/1716

However you might want to consider working around this as well by checking the `class_` prefix in the `pk` table and remove it if one exists. Not doing so will mean that any Realms created by Realm-Java  0.84.1 and below will not be compatible with Realm ObjC/Swift.

**Comment by jpsim** [comment]
Closing this as it's a java issue, for which a fix has been merged.

**Comment by jpsim** [comment]
I read this too quickly, I created #2809 to track adding support for the `class_` prefix in pk tables for existing files.
