### ISSUE TITLE
How to empty a local RLMResults

### ISSUE THREAD

**Issue by jdgong** [realm/realm-cocoa#2771]
For a RLMResults:
> var testResults = RLMObject.allObjects()
>...

To achieve something like:
> testResults.removeAllObjects()

**Comment by mrackwitz** [comment]
If you want to delete specific results, you queried for, you can delete them via the `RLMRealm` method [`- deleteObjects:`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/deleteObjects:). But it seems like you would like to delete *all* objects, then you could use [`- deleteAllObjects`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/deleteAllObjects).

But from the identifier you used for your results, it seems like you want to do that for your tests? If that should be the case, I'd rather recommend to use an [in-memory Realm](https://realm.io/docs/objc/latest/#in-memory-realms). When all in-memory Realm instances with a particular identifier go out of scope with no references, all data is freed for that Realm automatically.

**Comment by jdgong** [comment]
Thanks for help. But what I am trying to achieve is to just merely flush/empty a local variable with type of RLMResults. For example, testResults is a local variable with cached data and I want to empty that data like what we can do an array with Array.removeAll(keepCapacity: false).

**Comment by mrackwitz** [comment]
So I'm unclear whether the proposals in the first paragraph of my answer were of any help with your question and this can be closed. Otherwise you'd need to precise what you mean by flush/empty and what you want to achieve by that. Do you want to delete the objects in the results or just have a reference instead to an empty `RLMResults` container?

**Comment by jdgong** [comment]
The latter. Just a reference to an empty RLMResults container.

**Comment by mrackwitz** [comment]
Okay, then I completely misunderstood what you wanted to do. First of all `RLMResults` are not mutable. Their are reflecting (in an auto-updating manner), what is currently in your database for the query they were constructed for.
That means you'd need to query for something, which never yields any results, e.g. `MyObject.objectsWithPredicate(NSPredicate(value: false))`.
