### ISSUE TITLE
Error while installing Templates

### ISSUE THREAD

**Issue by codesourse** [realm/realm-cocoa#2776]
mkdir: /Users/yozi/Library/Developer/Xcode/Templates/File Templates/Realm: Permission denied
cp: /Users/yozi/Library/Developer/Xcode/Templates/File Templates/Realm: No such file or directory

**Comment by mrackwitz** [comment]
To help you, it would be helpful to know what you want to achieve and how. I guess, you want to install Realm's Xcode file templates. Can you provide some further information, how you attempted to do that? Did you cloned the repository locally, and executed the script `install_templates.sh` from `plugin/Templates`?

**Comment by TimOliver** [comment]
Hi @codesourse! 

Sorry, but we're going to need more information from you in order to help you here. 
I'm going to close this issue for now, but please feel free to re-open it if you need more help. :)
