### ISSUE TITLE
'auto' return without trailing return type; deduced return types are a C++14 extension

### ISSUE THREAD

**Issue by engramyosama6** [realm/realm-cocoa#2778]
Hey, 

After updating Realm to version 0.96.2 I can build my product anymore because of the following errors in Realm/Realm/RLMAnalytics.mm

75:8: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
80:16: error: no viable conversion from 'std::unique_ptr<void, decltype(&free)>' to 'int'
85:16: error: no viable conversion from 'std::unique_ptr<void, decltype(&free)>' to 'int'
93:12: error: no viable conversion from 'std::unique_ptr<void, decltype(&free)>' to 'int'
106:56: error: member reference base type 'int' is not a structure or union
143:84: error: member reference base type 'int' is not a structure or union

Please help

**Comment by mrackwitz** [comment]
How do you integrate Realm? Do you use a dependency manager or the prebuilt binaries?

**Comment by engramyosama6** [comment]
I integrate Real using Cocoa pods

**Comment by mrackwitz** [comment]
Which version of CocoaPods do you use?

**Comment by engramyosama6** [comment]
v0.37.2

**Comment by mrackwitz** [comment]
Please update to at least 0.39.

**Comment by engramyosama6** [comment]
ok...thanks
