### ISSUE TITLE
Cocoapods running version 96.0

### ISSUE THREAD

**Issue by JVSABIM** [realm/realm-cocoa#2779]
Greetings,

Installing the through cocoapods using simply " pod 'RealmSwift' ", was installing version 0.96.0 which was giving me some trouble with nullable strings, after adding '~> 0.96.2' to specify the version it all worked out fine. Is this an exception or something related to the pod spec?

**Comment by mrackwitz** [comment]
It might be related to [bugfixes](https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md#0962-release-notes-2015-10-26), which happened since the release of 0.96.0.

**Comment by mrackwitz** [comment]
Could you explain what kind of troubles you had with nullable strings?

**Comment by JVSABIM** [comment]
I was getting the exception "Terminating app due to uncaught exception 'RLMException', reason: 'Only 'object' properties can be made optional, and property 'type' is of type 'string'"

**Comment by mrackwitz** [comment]
Was that your initial installation of Realm or did you updated to 0.96? If the latter should apply, then the framework might be still cached in your build products directory. Did you cleaned your installation in between?

**Comment by jpsim** [comment]
Closing as it seems likely that this was a CocoaPods cache issue, where Realm Swift was updated but not Realm Objective-C.

**Comment by JVSABIM** [comment]
Indeed that seems to be the case, as we had updated from the previous version. Thanks for the fast replies.
