### ISSUE TITLE
Invalid architecture UUIDs: Could not parse UUIDs using dwarfdump

### ISSUE THREAD

**Issue by Palleas** [realm/realm-cocoa#2785]
I'm getting the following error when I try to setup Realm in my iOS application using Carthage:

```
$ carthage update --use-submodules --platform ios
*** Fetching realm-cocoa
*** Fetching keychain-swift
*** Fetching SwiftyJSON
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out Result at "0.6.0-beta.3"
*** Checking out SwiftyJSON at "2.3.0"
*** Checking out keychain-swift at "3.0.7"
*** Checking out ReactiveCocoa at "9af5f32b4f9f908ae5f26904fbaf49d0a9039e24"
*** Checking out realm-cocoa at "v0.96.2"
*** xcodebuild output can be found in /var/folders/tk/cw93k7v928qf21kppt47d_380000gn/T/carthage-xcodebuild.0HflvL.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Building scheme "KeychainSwift" in KeychainSwift.xcodeproj
*** Building scheme "iOS" in Realm.xcodeproj
Invalid architecture UUIDs: Could not parse UUIDs using dwarfdump from /Users/Romain/Library/Developer/Xcode/DerivedData/Realm-acrmeedomupvqhcepjsgrlqtlowg/Build/Products/Release-iphoneos/Realm.framework/Realm
```

Any idea what could be causing this? I've attached the [xcodebuild full log here](https://gist.github.com/Palleas/7567e783a235ef1dde54) and here is my Cartfile:

```
github "ReactiveCocoa/ReactiveCocoa" "swift2"
github "SwiftyJSON/SwiftyJSON" "2.3.0"
github "exchangegroup/keychain-swift" "3.0.7"
github "realm/realm-cocoa"
```

This doesn't seem to be an issue with Carthage because it really fails as soon as I add Realm in my `Cartfile` and run `cartage update`.
I'm using Xcode 7.1:  
```
xcodebuild -version
Xcode 7.1
Build version 7B91b
```

Thanks for your help !

**Comment by auibrian** [comment]
I think this can be solved if the Realm releases include the dSYMs as well as the frameworks.

**Comment by jpsim** [comment]
Since Carthage doesn't support multiple Xcode projects per repository, and they've refused our offers to add that functionality to Carthage itself, you can't use Carthage to build Realm Swift from source.

This means that to install Realm Swift with Carthage, it needs to pull the prebuilt binaries, which is incompatible with `--use-submodules`.

We're working on a hack that will allow Carthage to build both Realm Objective-C and Realm Swift from source in #2323.

**Comment by TimOliver** [comment]
Since we've folded RealmSwift into the Realm Xcode project in https://github.com/realm/realm-cocoa/pull/2793, this issue should be resolved now.

I'm closing the issue, but feel free to re-open it if you have any more questions. :)
