### ISSUE TITLE
Cannot find protocol declaration for 'YYYProductInfo'

### ISSUE THREAD

**Issue by yuldong** [realm/realm-cocoa#2788]
![Uploading Snip20151103_4.png…]()
I define two classes that contain references to each other.
---
```
#import <Realm/Realm.h>
#import "YYYProductInfo.h"

@interface YYYHighEnergyProduct : RLMObject

@property NSString *name;
@property NSInteger price;
@property RLMArray<YYYProductInfo *><YYYProductInfo> *products; // ### here, has that error

@end

// This protocol enables typed collections. i.e.:
// RLMArray<YYYHighEnergyProduct>
RLM_ARRAY_TYPE(YYYHighEnergyProduct)
```

---

```
#import <Realm/Realm.h>

#import "YYYHighEnergyProduct.h"

@interface YYYProductInfo : RLMObject

@property NSString *name;
@property NSInteger price;
@property NSData *productDescription;
@property NSDate *date;

@property RLMArray<YYYHighEnergyProduct*><YYYHighEnergyProduct> *hignEnergyProducts;

@end

// This protocol enables typed collections. i.e.:
// RLMArray<YYYProductInfo>
RLM_ARRAY_TYPE(YYYProductInfo)
```

---

is there any coding error? how can i fix this?
![Uploading Snip20151103_4.png…]()

**Comment by mrackwitz** [comment]
You have a circular dependency in your headers, which doesn't work.
`YYYHighEnergyProduct.h` tries to `#import "YYYProductInfo.h"` and depends on definitions made there, while `YYYProductInfo` tries to `#import "YYYHighEnergyProduct.h"` and depends again on those definitions. 

You will need to use forward declarations to make the compiler aware of related protocols and classes and have to remove one of the imports. e.g.

```diff
#import <Realm/Realm.h>
-#import "YYYProductInfo.h"
+
+@class YYYProductInfo;
+@protocol YYYProductInfo;

@interface YYYHighEnergyProduct : RLMObject

@property NSString *name;
@property NSInteger price;
@property RLMArray<YYYProductInfo *><YYYProductInfo> *products;

@end

// This protocol enables typed collections. i.e.:
// RLMArray<YYYHighEnergyProduct>
RLM_ARRAY_TYPE(YYYHighEnergyProduct)
```

Beside that I see that you defined to-many relations from `YYYProductInfo` to `YYYHighEnergyProduct` and vice-versa. Note that does act independently as directed relations. They are not automatically handled as many-to-many relation. You may want to define one of them rather as [inverse relationship by using backlinks](https://realm.io/docs/objc/latest/#inverse-relationships).

**Comment by yuldong** [comment]
@mrackwitz  3Q very much.
