### ISSUE TITLE
Crash when adding new objects during a write transaction on same thread

### ISSUE THREAD

**Issue by rudywen** [realm/realm-cocoa#2790]
I recently upgraded my project from Realm 0.95.3 to 0.96.2, and now I'm seeing crashes when adding objects while another function is updating the default Realm.  

Crash Logs for the relevant thread:

    Thread : Crashed: com.apple.root.default-qos
    0  flare                          4297133284 RLMAddObjectToRealm (table.hpp:1698)
    1  flare                          4295357400 __32+[FLPerson updateFollowersInfo:]_block_invoke    (FLPerson.m:539)
    2  libdispatch.dylib              6855022312 _dispatch_call_block_and_release + 24
    3  libdispatch.dylib              6855022248 _dispatch_client_callout + 16
    4  libdispatch.dylib              6855080768 _dispatch_root_queue_drain + 2140
    5  libdispatch.dylib              6855078620 _dispatch_worker_thread3 + 112
    6  libsystem_pthread.dylib        6857200752 _pthread_wqthread + 1092
    7  libsystem_pthread.dylib        6857199648 start_wqthread + 4

    Thread : com.apple.root.default-qos
    0  libsystem_kernel.dylib         6856388496 __psynch_mutexwait + 8
    1  libsystem_pthread.dylib        6857221020 _pthread_mutex_lock_wait + 96
    2  flare                          4298442652 realm::util::RobustMutex::low_level_lock() + 1292
    3  flare                          4299063588 realm::SharedGroup::do_begin_write() + 7392
    4  flare                          4297151420 RLMPromoteToWrite(realm::SharedGroup&, realm::History&, RLMSchema*) (group_shared.hpp:914)
    5  flare                          4297457840 -[RLMRealm beginWriteTransaction] (RLMRealm.mm:579)
    6  flare                          4295359692 +[FLPerson resetBlockingList] (FLPerson.m:639) 
    7  flare                          4295357832 __45+[FLPerson updatePeopleCurrenUserBlocksInfo:]_block_invoke (FLPerson.m:556)
    8  libdispatch.dylib              6855022312 _dispatch_call_block_and_release + 24 
    9  libdispatch.dylib              6855022248 _dispatch_client_callout + 16
    10 libdispatch.dylib              6855080768 _dispatch_root_queue_drain + 2140
    11 libdispatch.dylib              6855078620 _dispatch_worker_thread3 + 112
    12 libsystem_pthread.dylib        6857200752 _pthread_wqthread + 1092
    13 libsystem_pthread.dylib        6857199648 start_wqthread + 4

**Comment by TimOliver** [comment]
Hi @rudywen!

Wow, that's incredibly weird to see! What's going on here exactly? You've got one thread modifying objects already added to a Realm, and another one adding all new objects to the default Realm?

Either way, that shouldn't be happening. When a write transaction is open in Realm, all other write transactions are blocked, so there *shouldn't* be any direct conflicts arising like this.

If you know exactly where the crashes are occurring, are you able to post some sample code for us to check out?

Thanks!

**Comment by rudywen** [comment]
@TimOliver 

This crash also seems to occur when there are no other write transactions....

http://crashes.to/s/e4c3aaf97d6

```objective-c
+ (void)updateFollowersInfo:(NSArray *)users
{
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        
        // Reset the followers list with the information from the network server
        [FLPerson resetFollowersList];
        
        @autoreleasepool {
            // Begin write transaction
            
            RLMRealm *realm = [RLMRealm defaultRealm];
            [realm beginWriteTransaction];
            
            for (PFUser *user in users) {
                NSPredicate *phonePredicate = [NSPredicate predicateWithFormat:@"mobilePhoneNumber = %@",user[kFLUserPhoneNumberKey]];
                RLMResults *personList = [FLPerson objectsWithPredicate:phonePredicate];

                // Should only match one person
                if (personList && personList.count > 0) {

                    
                    for (FLPerson *person in personList) {
                        person.followerStatus = FLContactFollowStatusFollowing;
                    }

                } else {
                    FLUser *flUser = [[FLUser alloc] initWithPFUser:user];
                    
                    // Create the new user and add to the contact list
                    FLPerson *person = [FLPerson initNewContact:flUser];
                    
                    if (person) {
                        person.followerStatus = FLContactFollowStatusFollowing;
                        
// ************** This is where it crashes with ************** 
                        [realm addObject:person];
// *************** end ************** 
                    }
                }
            }
            
            // Commit the write transaction
            [realm commitWriteTransaction];
            
        }
    });
}
```

**Comment by TimOliver** [comment]
Oh wow. That's absolutely bizarre. That code looks absolutely fine to me.

Would you be willing to give us access to the source code so we can run our own diagnostics on it?

**Comment by rudywen** [comment]
I'm not able to share the source code. Is there something I can do on my end to help debug the issue?  

Could it be the way I'm initializing an FLPerson? Are there any requirements to set default values for a realm class.  My FLPerson class overrides `defaultPropertyValues` and `ignoredProperties`.

**Comment by TimOliver** [comment]
Hi @rudywen!

Are you sure you can't share the code? You can send it to us privately if you'd prefer. If there's a corporate reason why you can't share it, that's fine then.

Hmm... actually. Maybe one thing you can try: remove the GCD braces and see what happens when you execute everything on the main queue.

Something I just noticed is you're passing that array `users` across a thread, and if those users are comprised of `RLMObject` subclasses, that would certainly be causing an issue.

Let me know how you go!

**Comment by rudywen** [comment]
@TimOliver 

At this time, I'm not able to share the code base since it belongs to a private company.

I'll try running the realm updates on the main queue and report back.

The `users` array does not contain `RLMObject` subclasses, it consists of `PFUser` (Parse user objects)

**Comment by rudywen** [comment]
@TimOliver 

One thing I noticed when tracing the call stack is that the `RLMCreateOrGetRowForObject` function accesses the primary key 

`RLMProperty *primaryProperty = schema.primaryKeyProperty;`

What happens if there is no primary key set?

**Comment by rudywen** [comment]
@TimOliver 

This crash doesn't occur with Realm 0.95.3.  As you know, now I can't downgrade my current users from 0.96.2 to 0.95.3 with the new Realm file format changes.

**Comment by bdash** [comment]
The point at which we're crashing is:

    0  flare                          4297133284 RLMAddObjectToRealm (table.hpp:1698)

The code that's crashing is:
```c++
inline std::size_t Table::add_empty_row(std::size_t num_rows)
{
    std::size_t row_ndx = m_size;  // 💣
    …
```

The faulting address is 0x0000000000000000. The `m_size` member of `Table` is at offset 0, which indicates that we're accessing the `m_size` member of a null `Table*`. The calling function is `RLMCreateOrGetRowForObject`. It [gets the `Table` reference](https://github.com/realm/realm-cocoa/blob/c4518f9d3f405f204e8cafe070dd44a1863f3f82/Realm/RLMObjectStore.mm#L122) that it calls `add_empty_row` on by doing:
```c++
realm::Table &table = *schema.table;
```

Either `-[RLMObjectSchema table]` is returning null or `schema` itself is nil at this point.

**Comment by bdash** [comment]
`RLMCreateOrGetRowForObject`'s callers all appear to first verify that the `RLMObjectSchema` they're pass in is non-null.

**Comment by bdash** [comment]
@rudywen, are you able to reproduce this crash on demand, or have you only seen it in Crashlytics reports?

**Comment by rudywen** [comment]
@bdash, I can not reproduce the crash consistently, but I have been able to catch it when attached to xcode

**Comment by TimOliver** [comment]
Hi @rudywen! You're in good hands with @bdash helping to track down the cause of the crash in our code, but I'd like to keep checking to see if there's something in your code that might somehow be causing it, making it easier to mitigate.

Just to confirm, `PFUser` is a Parse subclass and `FLPerson` is a Realm subclass; is that correct? Also, what type of class is `FLUser` then?

How much of the implementation code for `FLPerson` are you able to share? I'm curious to see what happens in the `[FLPerson initNewContact:]` method call.

Thanks a lot!

**Comment by rudywen** [comment]
@TimOliver `PFUser` is a Parse subclass, `FLPerson` is a Realm subclass, `FLUser` is custom class that contains a `PFUser`.  

```objective-c
+ (FLPerson *)initNewContact:(FLUser *)user
{
    if (!user) {
        return nil;
    }
    
    FLPerson *person = [[FLPerson alloc] init];
    
    // Set the name
    person.fullName = user.name ? user.name : @"";
    NSArray *nameComponents = [person.fullName componentsSeparatedByCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
    person.firstName = [nameComponents firstObject] ? [nameComponents firstObject] : @"";
    
    if (nameComponents.count > 1) {
        person.lastName = [nameComponents lastObject] ? [nameComponents lastObject] : @"";
    }
    
    // Set the parameters
    person.mobilePhoneNumber = user.phoneNumber ? user.phoneNumber : @"";
    person.email = user.email ? user.email : @"";
    person.channel = user.PFUser[kFLUserPrivateChannelKey] ? user.PFUser[kFLUserPrivateChannelKey] : @"";
    person.parseObjectId = user.userId ? user.userId : @"";
    person.followerStatus = FLContactFollowStatusNotFollowing;
    person.followingStatus = FLContactFollowStatusNotFollowing;
    person.blockingStatus = FLContactBlockStatusNotBlocked;
    person.ignoreStatus = NO;
    person.source = FLContactSourceServer;
    
    // Retreive the profile thumbnail file
    if (user.PFUser[kFLUserThumbNailKey]) {
        NSString *idString = [NSString stringWithFormat:@"profilePhoto-%@", user.userId];
        [[FLOperationQueue sharedInstance] addOperationWithId:idString priority:NSOperationQueuePriorityVeryLow block:^(dispatch_block_t operationCompleted) {
            [user.PFUser[kFLUserThumbNailKey] getDataInBackgroundWithBlock:^(NSData *imageData, NSError *error) {
                operationCompleted();
                if (imageData && !error){
                    [FLPerson setProfileImage:[UIImage imageWithData:imageData] objectId:user.userId];
                }
            }];
        }];
    }
    
    return person;
}
```

**Comment by rudywen** [comment]
@bdash is there anything I can do to help debug this issue?  I'm getting a lot of crash reports with the same reason.

**Comment by bdash** [comment]
The best idea I have to gather further information is to add some custom logging in the case where the crash is about to happen. The following patch will output information that will give us a better idea what's going on:

```diff
diff --git a/Realm/RLMObjectSchema.mm b/Realm/RLMObjectSchema.mm
index 3fe855d..5559f80 100644
--- a/Realm/RLMObjectSchema.mm
+++ b/Realm/RLMObjectSchema.mm
@@ -313,6 +313,16 @@ using namespace realm;
 - (realm::Table *)table {
     if (!_table) {
         _table = ObjectStore::table_for_object_type(_realm.group, _className.UTF8String);
+        if (REALM_UNLIKELY(!_table)) {
+            NSLog(@"-[RLMObjectSchema table] was unable to find a table for %@", _className);
+            NSLog(@"The object schema is associated with a Realm with the following configuration:");
+            NSLog(@"%@", _realm.configuration);
+            NSLog(@"The following tables exist in the Realm:");
+            for (size_t i = 0; i < _realm.group->size(); ++i) {
+                auto table = _realm.group->get_table(i);
+                NSLog(@"%@", RLMStringDataToNSString(table->get_name()));
+            }
+        }
     }
     return _table.get();
 }
```
If you're using CocoaPods you should be able to apply the patch by doing something like the following, after copying the patch above to the pasteboard:
```
cd Pods/Realm/Realm
pbpaste | patch -p2
```

I'd suggest applying the patch locally and reproducing the issue on your machine, if possible. When you hit the crash you should see the new log output in the console. If you can provide that output here, it will give us more to go on.

Please let me know if you have any questions or run into any problems.

**Comment by rudywen** [comment]
@bdash 

I've been able to narrow down the crash, it looks like my entire table is being dropped.  I put a breakpoint in deleteAllObjects but it never gets to this point.  Is there any other way a Realm table could be dropped without explicitly deleting objects?

````
(lldb) po [FLPerson allObjects];
2015-12-13 23:35:27.809 flare[3244:857216] -[RLMObjectSchema table] was unable to find a table for FLPerson
2015-12-13 23:35:27.809 flare[3244:857216] The object schema is associated with a Realm with the following configuration:
error: Execution was interrupted, reason: breakpoint 1.1.
The process has been returned to the state before expression evaluation.
````

When I step through the debug log messages, I get to when trying to access ````_realm.configuration````

```` objective-c
- (void)setSchemaVersion:(uint64_t)schemaVersion {
    if ((_schemaVersion = schemaVersion) == RLMNotVersioned) {
        @throw RLMException(@"Cannot set schema version to %llu (RLMNotVersioned)", RLMNotVersioned);
    }
}
````

I'm setting the schema version in my ````application:didFinishLaunchingWithOptions:````

```` objective-c
    // ------------------------------------- Realm -----------------------------------------------------------
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    // Set the new schema version. This must be greater than the previously used
    // version (if you've never set a schema version before, the version is 0).
    config.schemaVersion = kFLRealmSchemaVersion;
    
    // Set the block which will be called automatically when opening a Realm with a
    // schema version lower than the one set above
    config.migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {
        // We haven’t migrated anything yet, so oldSchemaVersion == 0
        if (oldSchemaVersion < kFLRealmSchemaVersion) {
            // Nothing to do!
            // Realm will automatically detect new properties and removed properties
            // And will update the schema on disk automatically
        }
    };
    
    // Tell Realm to use this new configuration object for the default Realm
    [RLMRealmConfiguration setDefaultConfiguration:config];
    
    // Now that we've told Realm how to handle the schema change, opening the file
    // will automatically perform the migration
    [RLMRealm defaultRealm];
````

**Comment by bdash** [comment]
What breakpoint was being hit that was interrupting the logging when trying to output `_realm.configuration`? Can you disable the breakpoint so that the complete output of the logging is visible?

**Comment by bdash** [comment]
Does your app at any point manipulate the Realm file on disk directly (e.g., moving or deleting it)?

**Comment by rudywen** [comment]
We don't manipulate the Realm file on disk directly but we are using the Document directory to cache some local files, which are deleted at a later time.  I'm going to remove that piece of code to see if that is causing the problem.

**Comment by rudywen** [comment]
It seems that when the app writes and deletes files from the same Document directory somehow the Realm file on disk is reset.

**Comment by bdash** [comment]
Can you share the code you're using to delete files from the Document directory?

**Comment by rudywen** [comment]
I think we found the problem, in certain cases the app is incorrectly calling ````NSFileManager removeItemAtPath:```` on the Document directory which was deleting the Realm file.  We only noticed this behavior recently, was the Realm file moved into the Document directory?

**Comment by bdash** [comment]
The default realm path has not been changed recently.

**Comment by rudywen** [comment]
Do you know in which version of Realm was ````default.realm```` moved to the root folder of the Document's directory? Or has it always been this way?

**Comment by bdash** [comment]
I believe it has always been that way.

**Comment by bdash** [comment]
I'm happy you managed to track down what was causing your problem!

**Comment by rudywen** [comment]
@bdash thanks for all of your help on this issue!
