### ISSUE TITLE
Improve documentation of to-many relations

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-cocoa#2798]
Incoming questions show that to-many and especially many-to-many relations need better documentation.

* [x] Explain that links are always unidirectional
* [x] Explain that two to-many links on classes are *still* independent and not automatically synced
* [ ] Explain how to declare to-many related classes in Objective-C in independent files utilizing forward-declarations

**Comment by gadu** [comment]
+1 
Was messing around with this and had to do some witchcraft combination of forward-declarations and playing with syntax just to get a basic bidirectional relationship to compile

**Comment by jpsim** [comment]
@gadu we've added a sentence about forward-declaring model classes:

> The `RLM_ARRAY_TYPE` macro creates an protocol to enable the use of the `RLMArray<Dog>` syntax. You may have to forward-declare the model class if the macro is not placed at the bottom of the model interface.

**Comment by jpsim** [comment]
https://realm.io/docs/objc/latest/#to-many

**Comment by mrackwitz** [comment]
I don't think this is sufficient yet as it doesn't demonstrate the actual use of forward declarations.
