### ISSUE TITLE
Quality of Swift Support

### ISSUE THREAD

**Issue by fluidsonic** [realm/realm-cocoa#2801]
We were using Realm for the first time today and immediately ran into various issues.

First Realm rejected our class because it "cannot be nested within other declarations".
Actually the class isn't nested within anything. It's just that the class is marked `private`.

Then we tried to work around the issue by annotating the class with `@objc(MyRealmClass)` so the class ends up in the global namespace. But Realm just crashed:
```
+[MyRealmClass requiredProperties]: unrecognized selector sent to class …
```

The way Realm handles Swift classes is very fragile at the moment:
- Realm looks for a dot `.` in the class name to check whether a class is a Swift class ( `+[RLMSwiftSupport isSwiftClassName:]`). Swift classes don't necessarily have a dot in their demangled name when using `@objc`. Instead Realm could just check if the class in question is a subclass of `RealmSwift.Object`.
- Realm does only use the innermost class name and drops the module name (nested types aren't support anyway). So if two distinct Swift modules happen use the same class name for a Realm object the app will crash.
- Also as hinted in the code's comments `NSStringFromClass` doesn't fully demangle names. But Realm can use Swift's [`_stdlib_demangleName(…)`](http://swiftstub.com/743669163) instead to reliably get a class' name without relying in Swift internals.

#### Bottom Line

The bottom line is that Swift cleanly separates types using modules and nesting but Realm works against that by throwing all Realm object classes in one global dictionary again while dropping parts of the type's name.

Since a type's full name (including module, outer types, file hashes, etc.) can and will change from time to time (usual when iterating & refactoring) the developer should be given more control over the process. Also the process should be much more transparent. It's an easy oversight that renaming or even moving a class causes a change in it's full type name which in turn will lead to unexpected behavior at runtime when Realm does no longer find the class' objects. `NSSecureCoding` has the same issue and we were looking forward to not have the same issues again with Realm.

`RealmSwift.Object` already has a property named `className` which unfortunately is `final`. Being able to manually specify the class/table name would allow developers to avoid all the issues listed above. They would have full control over table naming, no more unexpected behavior and Realm doesn't need to perform fragile reverse-engineering of Swift class names.

-----

NB: The variable `RealmSwift.Object.className` is declared `final` and then overridden in dynamically created subclasses. That means the compiler can optimize any access to the variable by using [static access instead of dynamic dispatch](https://developer.apple.com/swift/blog/?id=27). So depending on current and future compiler optimizations the variable may randomly return an empty string instead of the expected value since the implementations in the dynamically created subclasses are never called.

-----

```
ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A284

/Applications/Xcode.app/Contents/Developer
Xcode 7.1
Build version 7B91b

/usr/local/bin/pod
0.39.0
Realm (0.96.2)
RealmSwift (0.96.2)
RealmSwift (= 0.96.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/bin/git
git version 2.4.9 (Apple Git-60)
```

**Comment by tgoyne** [comment]
> Realm looks for a dot . in the class name to check whether a class is a Swift class ( +[RLMSwiftSupport isSwiftClassName:]). Swift classes don't necessarily have a dot in their demangled name when using @objc. Instead Realm could just check if the class in question is a subclass of RealmSwift.Object.

We also support Swift-defined subclases of `RLMObject` (primarily for the sake of people writing Swift targeting iOS 7), which require the same Swift-specific handling despite not being `RealmSwift.Object` subclasses. I don't think there's any reason we couldn't check both, though.

> Realm does only use the innermost class name and drops the module name (nested types aren't support anyway). So if two distinct Swift modules happen use the same class name for a Realm object the app will crash.

The primary reason for this (and also the reason for not supporting nested types) is that Swift itself does the same stripping in the property types reported to the obj-c runtime, so if there are multiple classes with the same name we can't actually determine which one a property is using. We also can't determine it via Swift reflection without requiring a non-nil default for object properties, as you can only get the runtime type of the value of a property and not the declared type.

> Also as hinted in the code's comments NSStringFromClass doesn't fully demangle names. But Realm can use Swift's _stdlib_demangleName(…) instead to reliably get a class' name without relying in Swift internals.

That is not a public function. Using it risks getting app store rejections due to private symbol use, and doesn't eliminate the chance of things breaking when a new Xcode beta comes out, as they could remove it without warning.

**Comment by jpsim** [comment]
Thanks for your critical feedback, @fluidsonic. We value your opinion about our Swift support and integration, and I hope @tgoyne's explanations of the reasons why Realm Swift works the way it does was useful to you.

We hope to address some of those issues by contributing to Swift on a language level when outside contributions are possible, but until then, we have to target the language as it is today.

If you have any further questions or points of feedback, please don't hesitate to let us know.
