### ISSUE TITLE
Loading models into Realm from a relational REST server

### ISSUE THREAD

**Issue by jaydev** [realm/realm-cocoa#2802]
I am trying to reconcile Realm's NOSQL style database with my API server that uses relational modeling.

I set up my Realm models like this:

```swift
class Author: Object {
    dynamic var id = 0
    dynamic var profile: Profile?

    override static func primaryKey() -> String? {
        return "id"
    }
}

class Profile: Object {
    dynamic var id = 0
    dynamic var author: Author?

    override static func primaryKey() -> String? {
        return "id"
    }
}
```

Let's say that my server provides the following JSON responses when queried:

**/api/authors/1/**

```json
{
  "id": 1,
  "profile": 2
}
```

**/api/profiles/2/**

```json
{
  "id": 2
}
```

And then in my view controller I try to fetch and load my data:

```swift
fetchAsync(URL: "/api/authors/1").then { data in 
  try! realm.write {
    realm.create(Author.self, value: data, update: true)
  }
  return fetchAsync(URL: "/api/profiles/\(data["profile"])/")
}.then { data in 
  // save profile object to Realm
}
```

But obviously this isn't going to work because my server is returning foreign keys instead of embedding the Profile model inside of Author. Can Realm accommodate my relational data using some pattern that I'm not aware of?

**Comment by jpsim** [comment]
Hi @jaydev, that's a great question! There's nothing currently built into Realm that would allow converting a primary/foreign key mapping into a proper relationship.

How about doing something like this?

```swift
var authorID = 0
fetchAsync(URL: "/api/authors/1").then { data in 
  try! realm.write {
    let author = realm.create(Author.self, value: data, update: true)
    authorID = author.id
  }
  return fetchAsync(URL: "/api/profiles/\(data["profile"])/")
}.then { data in 
  try! realm.write {
    let profile = realm.create(Profile.self, value: data, update: true)
    let author = realm.objectForPrimaryKey(Author.self, key: authorID)
    author.profile = profile
    profile.author = author
  }
}
```

I'd also recommend that you use [inverse relationships](https://realm.io/docs/swift/latest/#inverse-relationships) to avoid doing the double-bookkeeping you're currently doing (setting both `author.profile` and `profile.author`).

**Comment by jaydev** [comment]
Yes, that is not a bad way to go about it, though it requires more bookkeeping that I'd like. But it appears that `linkingObjects` would not work in this case because the relationship between Profile and Author is one-to-one.

**Comment by jaydev** [comment]
Never mind, just returning the first element of `linkingObjects` would fix that :smile:

**Comment by jpsim** [comment]
> Never mind, just returning the first element of linkingObjects would fix that

Exactly!

> Yes, that is not a bad way to go about it, though it requires more bookkeeping that I'd like.

Here's a different way to accomplish the same thing, with a bit less bookeeping, but the author only being created when all the info for author & profile are available:

```swift
var authorDict = NSDictionary()
fetchAsync(URL: "/api/authors/1").then { data in 
  authorDict = data
  return fetchAsync(URL: "/api/profiles/\(data["profile"])/")
}.then { data in 
  try! realm.write {
    authorDict["profile"] = data
    realm.create(Author.self, value: authorDict, update: true)
  }
}
```
