### ISSUE TITLE
Simulator crash when profile allocation with RealmSwift

### ISSUE THREAD

**Issue by huy-le** [realm/realm-cocoa#2806]
App in simulator always crash when I profile allocation with default config. I have to turn off Identify virtual C++ objects to fix this problem.
<img width="212" alt="screen shot 2015-11-05 at 11 47 37" src="https://cloud.githubusercontent.com/assets/3965573/10960091/22727280-83b3-11e5-878a-41e57655859a.png">

**Comment by jpsim** [comment]
Thanks for reporting this, @ares-huy-le. This could take some time to debug. Do you have any idea why this could be happening?

**Comment by jpsim** [comment]
I can't reproduce this with [this sample app](https://github.com/jviney/realm-memory-leak-test), Xcode 7.3.1 and Realm Swift 1.0. If anyone manages to reproduce this, please open a new issue: https://github.com/realm/realm-cocoa/issues/new
