### ISSUE TITLE
Support reading primary keys create with Realm Java <= 0.84.1

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2809]
Which used a different name for the primary key table: `class_pk` rather than `pk`.

**Comment by zaki50** [comment]
Thank you for creating this issue.
One point to make sure that the problem is not a table name but the values in `pk_table` column which wrongly has the prefix `class_`.

**Comment by jpsim** [comment]
This is increasingly less of an issue as time goes on. I'm closing this so we can focus on higher priority tasks.
