### ISSUE TITLE
How can I get the ObjectClass form a RLMArray <ObjectClass> *property

### ISSUE THREAD

**Issue by yuldong** [realm/realm-cocoa#2810]
I define a property in a class, like this RLMArray<ObjectClass> *propertyName

and i want to get its real type -> ObjectClass
```
// this method using runtime to get the type of property
// in the case , it return @"RLMArray<ObjectClass>"
- (NSString *)getPropertyTypeString:(NSString *)propertyName
```
after this , using Class class = NSClassFromString(@"RLMArray<ObjectClass>") to get its ObjectClass. But it return null;

besides this, i got JSON from server, then use [self setValue:JSON[jsonKey] forKey:propertyName]; 

it throws BAD_ACCESS;
![88e704d8-a6dc-4ece-8946-4a8f150779de](https://cloud.githubusercontent.com/assets/5005006/10988829/efdd4fc0-847a-11e5-89ec-d0c446b69060.png)

after this statement, shows propertyName is nil;
JSON[jsonKey] has many items (array).

**Comment by yuldong** [comment]
@mrackwitz the reason seems that realm can not parse null.

**Comment by mrackwitz** [comment]
If you want to retrieve the related class of a property, you can go over the object schema.

```swift
let object : RLMObject = …
let property = object.objectSchema[propertyName]
if property == .Array {
     let objectClassName = object.objectSchema[propertyName]
     …
}
```

What do you want to achieve with the element type?

---

From what you showed so far; I'd guess that the EXC_BAD_ACCESS originates from a memory management issue in your code. If you need further help with that, please show us more context around that, where is the method called, what is self?

**Comment by yuldong** [comment]
@mrackwitz my fault,  thank you for the example, i'll check my code again, carefully.
