### ISSUE TITLE
App crashing when writing NSTextView String to Realm

### ISSUE THREAD

**Issue by xxtesaxx** [realm/realm-cocoa#2816]
I have a strange bug and I hope you can tell me what to do. I have a very simple application (https://github.com/xxtesaxx/Tube-Bricks) where the user can enter some text in a NSTextView. I use the NSTextView delegate method textDidChange: to write the changed text to Realm like so:
```
func textDidChange(notification: NSNotification) {
        if let textView = notification.object {
            if textView.isEqual(headerTextView){
                try! Realm().write{
                    self.currentGenerator().headerText = textView.string!
                }
            }
      }
}
````

This works good as long as the user enters text via keyboard. Also pasting text does work most of the time. However I found some text by accident which causes the app to consume more and more memory till it finally crashes when pasted into the TextView. The text is 
```
Unsere Ausrüstung:
❌Canon Legria Mini X - http://die.lemanns.de/affiliate/legria
❌Nikon Coolpix S9900 - http://die.lemanns.de/affiliate/coolpix
❌GoPro Hero3 Black - http://die.lemanns.de/affiliate/gopro3
❌Jans Rucksack (Deuter Aircontact Pro 70+15) - http://die.lemanns.de/affiliate/jansbackpack
❌Annikas Rucksack (Deuter Aircontact Pro 70+15) - http://die.lemanns.de/affiliate/annikasbackpack

Diese Links sind sog. "Affiliate-Links". Das bedeutet, dass wenn du das Produkt über diesen Link kaufst, wir eine kleine Provision von Amazon erhalten. Für dich entstehen keine Mehrkosten. Perfekt also wenn du einen Artikel sowieso kaufen und uns gleichzeitig völlig kostenfrei unterstützen möchtest. :)

Danke fürs Einschalten. Konstruktive Kritik kannst du gern in den Kommentaren los werden. Bewerten nicht vergessen! :)


Music / Instrumental by:
Phantom Sage - MIKO [NCS Release] - https://www.youtube.com/watch?v=7t8lRdpv5IQ
• https://www.facebook.com/thefantomofficial
• http://www.youtube.com/phantomsage
• https://soundcloud.com/phantomsage
• https://twitter.com/_phantomsage_
```

Once I copy/paste it into the header or footer TextView on the Generator tab, the app stops responding and start consuming memory like crazy.

**Comment by TimOliver** [comment]
Hi @xxtesaxx! Sorry about the delay in replying.

I just downloaded your app and built it on my Mac (Retina MacBook Pro, running the latest public release of OS X 10.11) and (I really hate to say this), it runs completely fine for me. I copied and pasted your sample text multiple times into both the header and footer views of the Generator tab, and then confirmed in Realm Browser that the text was properly being written to the Realm file on disk.

Can you please confirm with me which version of Realm you were using for this, as well as which version of OS X you're running?

Thanks!

**Comment by xxtesaxx** [comment]
The text was also visible in my realm browser. However, when pasting, the app crashed and afterwards the app could not be used again because when i loaded the text on startup the app crashed again. Mysterious... I'm on OS X 10.11.1 with realm 0.96.2
Maybe it's my MacBook late 2011. Good to hear that it's working for you as expected.

**Comment by jpsim** [comment]
@xxtesaxx I'm sorry this seems to never have been resolved for you. As far as I can tell, we weren't able to reproduce the issue from the code & steps you provided. Could you please try following those steps closely yourself to confirm that it's still an issue? Thanks!

**Comment by TimOliver** [comment]
@xxtesaxx Oops. Sorry for not following this up!

I had another play with this in Realm Browser today, but it was still working fine for me (On a side-note, I uncovered a bug in Realm Browser due to this. So thanks a lot for that! :) )

If you're still experiencing this issue, can you please provide as detailed reproduction steps as you can?

Thanks a lot!

**Comment by jpsim** [comment]
Closing because we haven't heard back from @xxtesaxx in a while.

**Comment by xxtesaxx** [comment]
I think closing it is fine since nobody else could reproduce it. maybe it
was a bug only on my system due to something else than realm

2016-01-06 4:00 GMT+08:00 JP Simard <notifications@github.com>:
