### ISSUE TITLE
Best way to serialize optional property which has a custom class

### ISSUE THREAD

**Issue by malcommac** [realm/realm-cocoa#2818]
I would to use custom classes with optional types in realm.
In order to serialize and work with a CLLocation instance my idea is this:
```swift
class MyClass : Object  {
	dynamic var _coordinates	:NSData?
	
	var coordinates :CLLocation? {
		get {
			if _coordinates == nil {
				return nil
			}
// we can cache it too to avoid deserialization every time
			let coordinatesObj : CLLocation = NSKeyedUnarchiver.unarchiveObjectWithData(_coordinates!) as! CLLocation
			return coordinatesObj
		}
		set(newCoordinates) {
			if newCoordinates == nil {
				_coordinates = nil
			} else {
				_coordinates = NSKeyedArchiver.archivedDataWithRootObject(newCoordinates!)
			}
		}
	}
...
}
```
Is there a better way?
Should we have some sort of protocol in Realm which allow us to return optional NSData for a specific property?
Another idea is to have a custom method like ```ignoredProperties``` which can be used to implement the logic to convert an object to NSData? and viceversa for a set of custom properties.

**Comment by jpsim** [comment]
For simple values, I'd encourage you to "translate" your model into properties that can be stored in Realm so you can perform queries on the underlying data and store/access them more efficiently.

In this specific case, since there are opaque types that you want to persist (like `CLFloor`), using NSKeyedArchiver is probably your best best.

**Comment by malcommac** [comment]
So did you think my proposed solution is the best we can achieve at this time?
I would to avoid all of this boilerplate code and make something more generic for these kind of properties but I'm not sure how to proceed

**Comment by jpsim** [comment]
Your approach is what I'd recommend. If you're looking to cut down on some of the boilerplate, here's a slightly trimmed down version of your property getters & setters:

```swift
class MyClass: Object  {
    dynamic var _coordinates: NSData?

    var coordinates: CLLocation? {
        get {
            return _coordinates.flatMap(NSKeyedUnarchiver.unarchiveObjectWithData) as? CLLocation
        }
        set {
            _coordinates = newValue.flatMap(NSKeyedArchiver.archivedDataWithRootObject)
        }
    }
}
```

**Comment by malcommac** [comment]
Great, thank you, it is much cleaner. Is there any plan to support some sort of [semi]automatic serialization for these properties?

**Comment by mrackwitz** [comment]
No, not currently. We'd easily end-up pulling in CoreLocation for everyone trying to use Realm, which might be a bit problematic in practice. (This was discussed before in #2199 though.)
Closing that for now. If you have other ideas though, please let us know.
