### ISSUE TITLE
Realm accessed from incorrect thread

### ISSUE THREAD

**Issue by hibento** [realm/realm-cocoa#2819]
Hi there,

I wrote a function to write/update an Object (conforming to Realms Object Protocol) into a Realm-File:

     public func writeObject(object: MyClass) {
        dispatch_async(GlobalBackgroundQueue) {
            autoreleasepool {
                ...
                    do {
                        let db = try Realm(path: fullPath)
                        db.beginWrite()
                        db.add(object, update: true)
                        try db.commitWrite()
                        print("Writing object \(object.name) succeed"))
                    } catch let error as NSError {
                        print("Initializing Realm failed: \(err.localizedDescription)")
                    }
               ...
            }
        }
    }

Calling this function once for any number of objects works perfectly, but as soon as I call this function for an object already written I get this error:

     Terminating app due to uncaught exception 'RLMException', 
     reason: 'Realm accessed from incorrect thread'

Disable the dispatch call inside the function and everything works fine, even for multiple function calls for the same object. The Threads themselves changes during each function call, but that´s kind of GCDs behavior.

I'm wondering now for some time where my error is - I create a new realm for each function call, but get this error anyways. Are previous / olds threads still holding some kind of lock to the existing realm-file?

Is there a connection to this issue #1097?

**Comment by TimOliver** [comment]
Hi @hibento! Thanks for your issue! :)

Ahhh, I see what's going on. Given the scope of the input `MyClass` object with this method, you're directly passing a Realm `Object` across threads when you open the GCD block, a pattern that's explicitly disallowed once the `Object` is written to a Realm. While it 'works' when you're creating the object for the first time (Since the object does not yet belong to a Realm file), it's not a good pattern to rely on, and the exception you're getting on subsequent updates is expected behaviour.

You might need to rethink your logic pattern here slightly to avoid explicitly passing objects between threads. For example, instead of directly passing an `Object` between threads, simply provide a dictionary object containing the values you wish to update, and pass that to the new thread instead.

Let me know if you need any more clarification! :)

**Comment by hibento** [comment]
Thanks for the quick replay - I read the documenting section regarding Threading before posting this question, but obviously I misunderstood something: I thought the Realm instance inside my write method() "release its lock" on my object at the end of the function call.

To be precise: Once a Realm instance is created and has a handle / lock on an object, this lock remains intact till the end of the Application lifecycle? Regardless of the actual lifecycle of the corresponding realm code?

**Comment by TimOliver** [comment]
It's not so much a 'locking' system, so much as it's simply managing the confinement of objects on different threads.

For each thread in your app, Realm maintains a separate copy of the `Realm` object. When you perform a fetch for `Object` objects, those objects still belong to that particular instance of the `Realm` object on that thread (You can even [access the parent `Realm`](https://realm.io/docs/swift/latest/api/Classes/Object.html#/s:vC10RealmSwift6Object5realmGSqCS_5Realm_) object from the `Object` itself).

So, when you're wanting to work on an `Object` in a different thread, you cannot simply pass it to that thread. If you want to modify an `Object` on a background thread, best practice is to simply re-fetch that same object from the `Realm` object representing that thread, and modify that one. The easiest way to do that is to use the primary key system, passing the primary key across threads, and then refetching the `Object` via `objectForPrimaryKey(_:key:)`.

Let me know if you require any extra clarification. :)

**Comment by hibento** [comment]
Okay, I think I got it. Since we're already using a primary key for all our objects, I'll modify our methods like you proposed. Thanks a lot - especially since the documentation is clear about this...

**Comment by TimOliver** [comment]
Awesome! Thanks a lot for that! Good luck with the implementation!

We're always looking to improve our documentation, so if there's anything else you think we need to mention, please let us know! Thanks!

**Comment by nishitsplashmath** [comment]
How can i create an unpersisted RLMObject instance to pass it across threads and populate its fields through a shallow copy method?

**Comment by TimOliver** [comment]
@nishitsplashmath 

Hi there! What are you trying to do exactly? If you just want to pass an object between threads, it's easier to simply save it to a `Realm` and then re-fetch it on the new thread.

If you want to perform a shallow copy to an unpersisted `RLMObject` instance, I think it may be necessary to do that manually.
