### ISSUE TITLE
/xxx/Pods/Realm/Realm/ObjectStore/object_schema.cpp:19:10: 'object_schema.hpp' file not found

### ISSUE THREAD

**Issue by hanhailong** [realm/realm-cocoa#2821]
![image](https://cloud.githubusercontent.com/assets/4241807/11037065/e2f7828a-8736-11e5-87c3-3aebf6032bd8.png)

when I use ``pod 'Realm'`` in ``Podfile``,it cause a serious mistake,

**Comment by mrackwitz** [comment]
Can you make sure to use at least CocoaPods 0.39?
What might help additionally is resetting the CocoaPods cache and the integration state by running the following:
```bash
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

**Comment by LukeDurrant** [comment]
FYI I just had this issue and clearing pods cache and Pod folder fixed the issue.

**Comment by mrackwitz** [comment]
Thanks for reporting that. I'll close this issue on base of that feedback.
@hanhailong: If that problem should still persist for you though, please feel free to come back here.
