### ISSUE TITLE
NSCopying

### ISSUE THREAD

**Issue by GreyEcologist** [realm/realm-cocoa#2824]
Hey, I'm building my first realm-based swift app. I'm accessing instances of Object in the main thread, while periodically making server calls to update their values in realm in a background thread. So to prevent race condition, I'm implementing NSCopying in my Object subclasses, and only using the copy() of the instances in the main thread, however I'm having difficulties doing the same thing with the List class. 

I don't see any documentation or info on the subject of using copy() on realm Object instances, so it feels like I'm missing something, is RLMSchema the way to go about it? if not, could you please point me to a link or a documentation on copying instances?

Thanks.

**Comment by TimOliver** [comment]
Hi @GreyEcologist! Thanks for the issue!

It sounds like you're overcomplicating the situation a bit more than you probably need to! It's not possible to create race conditions directly with Realm. When you open up a write transaction on one thread, it blocks the write transactions on all of the other threads until it's finished. Read transactions work regardless, with any new values being made available on the next iteration of the app's run loop.

My recommendation would be to remove all of that NSCopying code, and see how your app goes without it. It should just work. :)

Let us know how you go!

**Comment by GreyEcologist** [comment]
Right on! thanks Tim!
