### ISSUE TITLE
realm database can not be opened

### ISSUE THREAD

**Issue by yuldong** [realm/realm-cocoa#2825]
saved .realm database in an ios device, then import the realm to my MAC desktop, that includes five files <.realm, .lock, .log, .log_a, .log_b> , then i try to open it with Realm Broswer, it show's the following tips;
**'default' could not be opened. It may be encrypted, or it isn't in a compatible file format.**

**Comment by mrackwitz** [comment]
Which version of the Realm browser do you use? Are you on [the latest version](https://github.com/realm/realm-browser-osx/releases/tag/0.96.1)? There was a breaking file format change in the last recent minor version of Realm, which would cause this error.

**Comment by yuldong** [comment]
@mrackwitz after updating to the lastest version, it fix my problem. thanks.
