### ISSUE TITLE
Object deleted exception in Realm

### ISSUE THREAD

**Issue by pavlem** [realm/realm-cocoa#2826]
Hi, 

I implemented Realm DB where in my app I have made a realm model and in some VC I used that model. 

In a VC I have a button where I can SAVE and DELETE DB data.

Model is "FundDB: Object" which has several properties like name, number, etc. 

In VC I created "fundDB", populated it's properties and when I press ADD button I added it to the DB successfully (it's there when I go to another VC aimed to show DB items).

When I press DELETE it does it successfully again (it's removed from VC aimed to show DB items).

The problem emerges when I add it then remove it and then add it again. I get an exception with following info **Terminating app due to uncaught exception 'RLMException', reason: 'Object has been deleted or invalidated**

Here is the code part. 

```javascript
class FundDetailVC: UBSViewController {...
    let fundDB = FundDB()
...
}
```

```javascript
override func viewDidLoad() {
        super.viewDidLoad()

...
        fundDB.fundName = nameForFund
        fundDB.fundIsin = isinForFund
        fundDB.fundValor = valorForFund
        fundDB.fundUrlRequest = urlPath

}
```

```javascript
    @IBAction func addToMyFundsButtonAction(sender: UIButton) {
        
        let fundDBRealmInstance = DB_HANDLER.getFund(primaryKey: self.isinForFund)
               
        if fundDBRealmInstance != nil {
            print(self.fundDB.fundIsin)
            DB_HANDLER.deleteFundFromDB(fundDBRealmInstance!)            
        } else {        
            let fundDBRealmObject = self.fundDB
            DB_HANDLER.saveFundToDB(fundDBRealmObject)
        }
      }
```
DB_Handler is a helper class I created and which uses 
```javascript 

 private func writeToDB(dbObject: Object) {
        do {
            try uiRealm.write({ () -> Void in
                uiRealm.add(dbObject)
            })
        } catch {
            print("DB Realm insert failed")
        }
    }
   
    private func deleteFromDB(dbObject: Object) {
        
        do {
            try uiRealm.write({ () -> Void in
                uiRealm.delete(dbObject)
            })
        } catch {
            print("DB Realm insert failed")
        }
    }
```

For some reason fundDB property in my VC doesn't exist any more. 

Can you please give me some light on the matter :)

**Comment by pavlem** [comment]
I resolved this by replacing 

```javascript
 else {        
            let fundDBRealmObject = self.fundDB
            DB_HANDLER.saveFundToDB(fundDBRealmObject)
        }
```
with 

```javascript
else {
          let fundDBRealmObject = FundDB(value: self.fundDB)
          DB_HANDLER.saveFundToDB(fundDBRealmObject)
        }
```

As I see, when deleting fundDB Realm object from default.realm DB file on disk also deleted fundDB instance (property) on my VC.

**Comment by mrackwitz** [comment]
I can confirm that this is the supposed behavior. Objects, which are added to Realm once represent the contents of your database, following a zero-copy approach. If you delete them, the accessors are invalidated.

**Comment by pavlem** [comment]
Was my approach to resolve this ok?

Thanks for the answer.
