### ISSUE TITLE
Unrecognized Selector `-[Object handleExternalCommit]` crashes seen in field

### ISSUE THREAD

**Issue by eskerber** [realm/realm-cocoa#2830]
Realm .96.2

We have some crash logs I'm rather stumped on. They are all common in that they are unrecognized selector exceptions on the selector `handleExternalCommit`:

![screen shot 2015-11-10 at 12 30 55 pm](https://cloud.githubusercontent.com/assets/75236/11074911/3199723e-87a7-11e5-9b0d-e84c35907a84.png)

The object that is being passed to varies, and I've seen `NSIndexPath`, `NSTaggedPointerString`, and `NSCFNumber` among others. 

Anything that's been seen? Or any idea on what we may be doing maliciously to cause this?

**Comment by jpsim** [comment]
This is an unrecognized selector being sent to an Core Data managed object (`_NSCoreDataTaggedObjectID`), not Realm.

**Comment by eskerber** [comment]
@jpsim You are right, it is. I am getting it on many unrelated objects, however - and `handleExternalCommit` is a private selector within Realm. 

<img width="751" alt="screen shot 2015-11-11 at 7 46 23 am" src="https://cloud.githubusercontent.com/assets/75236/11095128/57b6bd9a-8848-11e5-829e-92040e1f5d82.png">

My gut says it's a memory management issue, but I can't put my finger on what's causing it since the code that invokes `handleExternalCommit` isn't publicly available.

**Comment by jpsim** [comment]
@eskerber can you share the source for this app? You can email it privately to help@realm.io if you prefer. It would help if I could dig through it to investigate how this could be happening.

I'd look at your Core Data & Realm models, and other CD/Realm code that may be interacting with each other.

**Comment by pawelkata** [comment]
I'm having the same problem, it seems. It happens in an app that runs for a few days straight perfectly and then all of a sudden this crash. Restarting this app makes it run flawlessly for a few days again.

Here's what's happening:
```
2015-12-02 06:38:24.722 MTGSpot[34489:10194034] -[NSTaggedPointerString handleExternalCommit]: unrecognized selector sent to instance 0xa00007f99f60783f
2015-12-02 06:38:24.799 MTGSpot[34489:10194034] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString handleExternalCommit]: unrecognized selector sent to instance 0xa00007f99f60783f'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001103d9f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010fe53deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001103e258d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000011032ff7a ___forwarding___ + 970
	4   CoreFoundation                      0x000000011032fb28 _CF_forwarding_prep_0 + 120
	5   MTGSpot                             0x000000010d9c2c3f _ZZ21-[RLMNotifier listen]ENK3$_1clEPv + 95
	6   MTGSpot                             0x000000010d9c2bd8 _ZZ21-[RLMNotifier listen]EN3$_18__invokeEPv + 24
	7   CoreFoundation                      0x00000001103060a1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	8   CoreFoundation                      0x00000001102fbfcc __CFRunLoopDoSources0 + 556
	9   CoreFoundation                      0x00000001102fb483 __CFRunLoopRun + 867
	10  CoreFoundation                      0x00000001102fae98 CFRunLoopRunSpecific + 488
	11  GraphicsServices                    0x0000000112221ad2 GSEventRunModal + 161
	12  UIKit                               0x000000010e56e676 UIApplicationMain + 171
	13  MTGSpot                             0x000000010d7b9baf main + 111
	14  libdyld.dylib                       0x0000000110ae292d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I can't share the full source code with you, but here's the relevant code fragment that brings up the error:
```
// update quantities
DDLogError(@"Presta UPDATING AMOUNTS...");
RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
for (PSArticle *article in [PSArticle allObjects]) {
    RLMResults *amounts = [PSStock objectsWhere:@"stockID == %ld", article.stockID];
    if (amounts.count > 0) {
        PSStock *amount = amounts.firstObject; // <-------  APP STOPS WORKING HERE
        article.count = amount.quantity;
    }
}
[realm commitWriteTransaction];
```

Here's some debug info about objects which take part in this code fragment:
```
(lldb) po amount
 nil
(lldb) po amounts
RLMResults <0x7f99ed139500> (
	[0] PSStock {
		stockID = 6935;
		productID = 6935;
		quantity = 27;
		outOfStock = 0;
	}
)

(lldb) po article
PSArticle {
	articleID = 6935;
	categoryID = 6498;
	stockID = 6935;
	mkmID = 214445818;
	name = Shu Yun, the Silent Tempest [ NM, Fate Reforged ];
	cardName = Shu Yun, the Silent Tempest;
	category = Fate Reforged;
	price = 0.51;
	count = 27;
	condition = NM;
	active = 1;
	available = 1;
	isFoil = 0;
	isSigned = 0;
	isAltered = 0;
	isPlayset = 0;
	isSpecial = 0;
	state = 0;
}

(lldb) po [PSStock allObjects].count
10642

(lldb) po amounts.firstObject
PSStock {
	stockID = 6935;
	productID = 6935;
	quantity = 27;
	outOfStock = 0;
}
```

Here are screenshots of relevant threads (sorry for not providing this info as text):
https://www.dropbox.com/s/bgpobm5s3osiraz/realm-error-shots.zip?dl=0

I hope this helps. If you need more info, I'm here.
Thanks for the great piece of software Realm is!

**Comment by jpsim** [comment]
I'm sorry for the lack of movement on this, I suppose it's because we're all just as confused about why this could be happening as you are!

This seems to be related to `RLMNotifier`, which has been replaced in `master` (#2725) and should be completely removed in our next major release (0.97). So at the very least, I'd encourage you all to integrate Realm from the `master` branch into your apps to see if it resolves this issue.

**Comment by pawelkata** [comment]
Sure, no worries. Any ETA on 0.97?

**Comment by eskerber** [comment]
@jpsim Thanks for the update, and thanks @pawelkata for being able to at least reproduce it (we only know it from thousands of crash logs across millions of sessions)!

Looking forward to .97

**Comment by jpsim** [comment]
> Sure, no worries. Any ETA on 0.97?

as soon as possible.

**Comment by mrackwitz** [comment]
0.97 is out since end of last week. Sorry, that we forgot to ping you guys. :)

**Comment by eskerber** [comment]
@jpsim We just hit our latest version on the app store with Realm .97. Sad to say the external selector crash still exists for us :/

Did you say that RLMNotifier was updated or removed? We're still seeing it in our callstacks.

**Comment by jpsim** [comment]
Ah, thanks for keeping us posted on this @eskerber!
