### ISSUE TITLE
Core Data docs missing Realm code snippets!

### ISSUE THREAD

**Issue by tsheaff** [realm/realm-cocoa#2832]
https://realm.io/news/migrating-from-core-data-to-realm/

For me this page only shows the Core Data examples and not the corresponding Realm example code:

![screen shot 2015-11-10 at 3 12 24 pm](https://cloud.githubusercontent.com/assets/1238684/11078901/7c5122d4-87bd-11e5-8562-a68b663b7891.png)

**Comment by tsheaff** [comment]
The HTML is there (for Objective C and Swift) but it's been set to `display: none` for both languages.

**Comment by kishikawakatsumi** [comment]
@tsheaff Thank you for reporting this! I've fixed and deployed that page. Could you please check it?

**Comment by tsheaff** [comment]
Yes it's now working thanks @kishikawakatsumi
