### ISSUE TITLE
iPhone 4s and 5 write issues

### ISSUE THREAD

**Issue by WayneNotTaken** [realm/realm-cocoa#2836]
Hi guys

I am doing a basic write of information to realm, Id, artists, facebookId and the write works on all phones.  However in my simulator with iPhone 5 and 4s, for some reason the Id is getting altered when writing to the realm.  For example I run the same code on an IPhone 6s and up i get (random object):

FacebookArtists {
		id = 100;
		artist = Indie-Go;
		facebookId = 554654727986033;
	}

and on an iPhone 5 and 4s i get:

FacebookArtists {
		id = 100;
		artist = Indie-Go;
		facebookId = -1643586703;
	}

It is altering every facebookId, that is previously determined by a JSON file.  The JSON file stays the same however the when writing to realm on iPhone 5 and 4s it seems to changing the information.  Can you please assist?  I am using the latest version of Realm currently (0.96.2).

**Comment by kishikawakatsumi** [comment]
@WayneNotTaken Because `554654727986033` is overflowed in a 32-bit integer. If you'd like to store the ID as an integer in 32-bit devices, use `long long` instead `NSInteger`, `int` or `long`. Or you can convert an integer to a string and store the value as `String`.

**Comment by WayneNotTaken** [comment]
Awesome thanks.  All sorted out.  Used a string to write the facebookId and its works perfectly.  Thanks for your quick help.
