### ISSUE TITLE
iOS sortting error by two String.

### ISSUE THREAD

**Issue by codesourse** [realm/realm-cocoa#2837]
[searchArray sortedResultsUsingDescriptors:@[
[RLMSortDescriptor sortDescriptorWithProperty:@"ss_id" ascending:!_haveDone],
[RLMSortDescriptor sortDescriptorWithProperty:@"ss_st_us_id" ascending:YES]]]

Sortting by two string meet error,the order is not the same as android and it is wrong.

**Comment by kishikawakatsumi** [comment]
@codesourse Can you please specific how error are you getting? And could you show the data that you'll sort and results?

**Comment by kishikawakatsumi** [comment]
Closing due to no response. Please reopen if there is any new information.
