### ISSUE TITLE
Is there a way to read realm data directly from a zip file(or NSData) into memory ？

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#2839]
Hi, I want to know if there is a way to create a realm in memory from a NSMutableData(or NSData), not from a realm file path. thanks.

**Comment by jpsim** [comment]
No, that's not possible, but you could open it as a regular disk-backed Realm if you wrote this NSData to a file on disk and opened a Realm pointing at that path.

**Comment by github2016a** [comment]
thanks @jpsim ,my goal Is to solve #2835，i want to read an unencrypted realm without create a file, for safe concern.

**Comment by jpsim** [comment]
Note that in-memory Realms may still page memory to disk, which actually makes them *less secure* than disk-backed encrypted Realms.

**Comment by github2016a** [comment]
thanks,@jpsim ,my problem is my encrypted Realm file is too big, and cannot be zipped, so i have to use a zipped unencrypted realm, to encrypt it on the app first run.

**Comment by jpsim** [comment]
To recap, there are two main issues you're facing with the approach you're taking:

1. Encrypting a file causes its entropy to increase, making it less compressable. This is a fundamental result of information theory.
2. All realms are backed by files, even in-memory Realms can occasionally write their contents to disk.

You might have more luck compacting an unencrypted Realm file (`-[RLMRealm compact]`), compressing the Realm (e.g. using LZFSE or ZLIB), then encrypting that (e.g. using CommonCrypto).

**Comment by github2016a** [comment]
thanks for your advices,@jpsim. i will try the [RLMRealm compact]  method 。but i still cannot avoid creating a temp unencrypted Realm file on disc to execute the 
realm.writeCopyToPath( path, encryptionKey: getKey())
operation。
