### ISSUE TITLE
Detect computed properties by checking for the existence of backing ivars

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-cocoa#2840]
Assumingly, that this Swift code, won't synthesize an ivar for `bar`:

``` swift
class Foo : Object {
    dynamic var foo: String = "foo"
    var bar: String {
        get { return foo }
        set { foo = newValue }
    }
}
```

If we could detect by the absence of this ivar, that `bar` is actually a fully computed property, we could avoid having users to add them to `ignoredProperties` when defining their schema classes.

That would be helpful in cases like #2815.

**Comment by michelalbers** [comment]
+1

**Comment by dantheli** [comment]
+1

**Comment by JadenGeller** [comment]
We can also do this in Objective-C, as the ivar is not automatically synthesized when both the getter and the setter are manually implemented. A property lacking  `V` attribute is lacking an ivar and thus computed. https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtPropertyIntrospection.html

**Comment by austinzheng** [comment]
We're now using `breaking` in this repo to indicate API changes that require a major version increment (per semver), so I'm going to untag this issue.

**Comment by tgoyne** [comment]
Doing this would be an API change that requires a major version increment.

**Comment by austinzheng** [comment]
This is in `master-3.0`.

**Comment by markst** [comment]
What's the go if we *do not* wish a particular computed property to be ignored from Realm?

**Comment by tgoyne** [comment]
What would you expect that to do? A property cannot be both computed and stored in Realm.

**Comment by markst** [comment]
@tgoyne something along these lines as an example:
```swift
@objc dynamic var latestTest:Test? {
    get {
        if let latestTestId = self.latestTestId {
            return self.tests.filter("id == %@",latestTestId).first
        }
        return RLMDynamicGetByName(self, "latestTest", false) as? Test
    }
    set {
        self.latestTestId = newValue?.id
        RLMDynamicValidatedSet(self, "latestTest", newValue)
    }
}
```

**Comment by austinzheng** [comment]
The most straightforward solution is to have a stored property and wrap it manually with a second, computed property you intend the user to use. The difference is purely aesthetic.

**Comment by markst** [comment]
I've tried the following:
```swift
@objc private var test:Test?
@objc dynamic var latestTest:Test? {
    get {
        if let test = self.test {
            return test
        }
        if let latestTestId = self.latestTestId {
            return self.tests.filter("id == %@",latestTestId).first
        }
        return nil
    }
    set {
        self.test = newValue
        self.latestTestId = newValue?.id
    }
}
```

But raises the following error: https://github.com/realm/realm-cocoa/issues/5558
