### ISSUE TITLE
Invalid URL in Error Message http://realm.io/docs/objc/api/Classes/RLMObject.html for more information.

### ISSUE THREAD

**Issue by ArtSabintsev** [realm/realm-cocoa#2843]
I received this error in RealmSwift.

> *** Terminating app due to uncaught exception 'RLMException', reason: ''NSArray' is not supported as an RLMObject property. All properties must be primitives, NSString, NSDate, NSData, RLMArray, or subclasses of RLMObject. See [http://realm.io/docs/objc/api/Classes/RLMObject.html](http://realm.io/docs/objc/api/Classes/RLMObject.htm) for more information.'

Unfortunately, the link that it points to is dead.

**Comment by jpsim** [comment]
That link should be https://realm.io/docs/objc/latest/api/Classes/RLMObject.html, but as the error message states, you can't use Array/NSArray as a Realm property. In Realm Swift, you'll need to use [`List`](https://realm.io/docs/swift/latest/api/Classes/List.html).

To read more about which types are support as Realm Swift Object properties, please refer to https://realm.io/docs/swift/latest/#supported-types.

I've updated the docs link in #2845.

**Comment by ArtSabintsev** [comment]
Thanks, @jpsim. It was my first time using Realm :)

I've fixed the issue, but just wanted to report the docs issue. 

Glad you've gotten it fixed.

**Comment by jpsim** [comment]
Let us know how it goes!
