### ISSUE TITLE
Loading Realm Objects on Backthread

### ISSUE THREAD

**Issue by pavlem** [realm/realm-cocoa#2846]
Hi, 

I am using RealmSwift with Swift 2.1 and have managed to solve ADD and DELETE actions in background thread with loading default realm with **let realm = try! Realm()** instead of using **let uiRealm = try! Realm()**. I followed solution on this issue (https://github.com/realm/realm-cocoa/issues/1445).

Unfortunately, I cannot resolve Fetching of the objects on background thread and do the update on the UI Thread (reloading TableView with fetched data) and I always get an exception **Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread'**

I found these links on issues about my question 
https://github.com/realm/realm-cocoa/issues/2411
https://github.com/realm/realm-java/issues/939 

Here it states
**We are working on introducing async queries for queries that takes a long time. That will hopefully be ready soon.**

My question is how can I, if it's possible, transfer Realm **Results** to main thread and reload my table view?

Here is my code 
```javascript
let queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)
        dispatch_async(queue) {
        
            let realm = try! Realm()
            let funds = realm.objects(FundDB)
            
            dispatch_async(dispatch_get_main_queue()){
                
                self.myFunds = funds
                self.tableView.reloadData()
            }
        }
```

**Comment by mrackwitz** [comment]
No, this is not directly possible. We're actively working on a feature in this direction, tracked by #1097.
Currently you would need to follow one of these strategies:
* Retrieve an array of indexes / primary keys for your results and could transfer that to retrieve the instances via Realm on the main thread.
* Get detached object copies / value objects (`NSArray` of `NSDictionary`).
* Re-run the query on the main thread.
