### ISSUE TITLE
when I update my iOS app , the data store in realm was lost ,why?

### ISSUE THREAD

**Issue by chenshaomou** [realm/realm-cocoa#2847]
when I update my iOS app , the data store in realm was lost ,why?

**Comment by mrackwitz** [comment]
You'd need to provide a little more info to be able to help you.
How do you initialize Realm? Do you modify the configuration?
How did you update your iOS app? Did you re-run on the simulator and you lost your data? Or did that happened for the AppStore version of your app? Did you update Realm in between?

**Comment by chenshaomou** [comment]
here is my init code 

class MZRealmAPI: NSObject {
    
    class func shareInstance() -> Realm{
        let buildInfo = (NSBundle.mainBundle().infoDictionary!["CFBundleVersion"] as! String).mz_toUInt()!
        let schemVersion = UInt64(buildInfo)
        struct Static {
            static var realms =  [String : Realm]()
        }
        if let __instance = Static.realms[User.currentUser.uid!]{
            return __instance
        }else{
            let critLock = NSLock()
            critLock.lock()
            do{
                
                let path = String(format:"%@%@", NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)[0] ,"/\(User.currentUser.uid!).realm");
                let config = Realm.Configuration(
                    path:path,
                    schemaVersion: schemVersion,
                    migrationBlock: { migration, oldSchemaVersion in
                        
                        

                })

                Static.realms[User.currentUser.uid!] = try Realm(configuration: config)
            }catch{
                print("realm init fail")
            }
            critLock.unlock()
            let _instance = Static.realms[User.currentUser.uid!]
            return _instance!
        }
    }
}

then I change my build no from 50 to 51, my data lost, how i should configure the realm? i am using swift

**Comment by chenshaomou** [comment]
I re-run it no my device , after I modify the build no

**Comment by mrackwitz** [comment]
I can't recognize from your code any reason why you would loose data. Even if something with the auto-migration would have failed, you'd end up with some error, but not just no data at all. But are you sure that the last path component `User.currentUser.uid!` doesn't change in between? Did you tried to inspect the Realm file with the browser between the runs?
