### ISSUE TITLE
data persisted last time was gone when I restart my app

### ISSUE THREAD

**Issue by wakaryry** [realm/realm-cocoa#2850]
My app got a problem when use Realm. I configure realm using:
``` objective-c
+ (void)setDefaultRealmForAccount:(NSString*)userID{
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.path = [[[config.path stringByDeletingLastPathComponent]
                    stringByAppendingPathComponent:userID]
                   stringByAppendingPathExtension:@"realm"];
    [RLMRealmConfiguration setDefaultConfiguration:config];
}
```
And everytime I start my app,  I will run this configuration. The data persisted last time was gone.

When should I config realm? Should I config it everytime when I start my app?

**Comment by kishikawakatsumi** [comment]
> When should I config realm? Should I config it everytime when I start my app?

@wakaryry Yes. You need to run above code every time you run your app, before than first instantiate the Realm.

**Comment by wakaryry** [comment]
@kishikawakatsumi  But my data saved last time was gone. I was confused.

**Comment by jpsim** [comment]
> But my data saved last time was gone.

What do you mean by this? How are you writing data to the Realm? Is the write transaction succeeding? How are you then fetching data back out of the Realm on subsequent runs, what results are you expecting and what's actually happening?

We're happy to help you with this problem but need more information to understand what's happening.

Thanks!

**Comment by wakaryry** [comment]
## I was following this way:
**1. Everytime I rerun my app, I will cofig the realm to let the name of default realm be the user's id**
``` objective-c
+ (void)setDefaultRealmForAccount:(NSString*)userID{
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.path = [[[config.path stringByDeletingLastPathComponent]
                    stringByAppendingPathComponent:userID]
                   stringByAppendingPathExtension:@"realm"];
    [RLMRealmConfiguration setDefaultConfiguration:config];
}
```
**2. Then I will retrive the data saved in realm using default realm**
when my app was online, I can save to and retrive data from realm. And all my data was request from server, then save into realm, then retrive it from realm to display. Everything is ok when running app. But when I terminate my app and restart it, I got empty when I retrive the data from realm.

## details
**save data**
``` objective-c
+ (instancetype)initAlbumWithDictionary:(NSDictionary *)dictionary{
AlbumModel *album = [[AlbumModel alloc] init];
    album.postID = [dictionary[@"id"] integerValue];
if([AlbumModel isNullWith:dictionary[@"userLike"]]) {
        album.likeUserList = nil;
    }else{
        for (NSDictionary *userDictionary in dictionary[@"userLike"]) {
            UserModel *likeUser = [UserModel initLikeUserWithDictionary:userDictionary];
            [album.likeUserList addObject:likeUser];
        }
    }
    
    if([AlbumModel isNullWith:dictionary[@"commentList"]]) {
        album.commentList = nil;
    }else{
        for (NSDictionary *userDictionary in dictionary[@"commentList"]) {
            AlbumCommentModel *albumComment = [AlbumCommentModel initAlbumCommentWithDictionary:userDictionary];
            [album.commentList addObject:albumComment];
        }
        
    }
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    // I have setted postID as primaryKey
    [AlbumModel createOrUpdateInRealm:realm withValue:album];
    [realm commitWriteTransaction];
    return album;
}
```
**Data Saved into Realm**
![realmcreated](https://cloud.githubusercontent.com/assets/7576559/11201032/795bab50-8d15-11e5-857a-ea3f4cd3b910.jpg)
![datasaved](https://cloud.githubusercontent.com/assets/7576559/11201042/8d043d70-8d15-11e5-8739-4df43b87af7a.jpg)

** retrive data**
``` objective-c
+ (RLMResults*)getSavedAlbums{
    return [[AlbumModel allObjects] sortedResultsUsingProperty:@"postID" ascending:NO];
}
```
I can got it from realm.
![refresh](https://cloud.githubusercontent.com/assets/7576559/11201195/ee67fe5c-8d16-11e5-8383-5c4e036d98fd.jpg)
And new one and show the new:
![newdatapage](https://cloud.githubusercontent.com/assets/7576559/11201215/1c20a15a-8d17-11e5-83d4-a1cf692b3e4a.jpg)
![newdatasaved](https://cloud.githubusercontent.com/assets/7576559/11201232/3b807cf0-8d17-11e5-9b14-6f1bb78fe566.jpg)

**But! Terminate APP, restart now**
All my data saved last time was gone
![emptydata](https://cloud.githubusercontent.com/assets/7576559/11201255/6919119a-8d17-11e5-93ae-be1809e000c5.jpg)
![restart](https://cloud.githubusercontent.com/assets/7576559/11201256/6f85297e-8d17-11e5-9440-615eec9e467d.jpg)

**refresh**
when I refesh data from server, data saved into realm again
![refresh](https://cloud.githubusercontent.com/assets/7576559/11201276/91f930ae-8d17-11e5-86f4-ce97e8f85b35.jpg)
![datasavedagain](https://cloud.githubusercontent.com/assets/7576559/11201282/98ae5f00-8d17-11e5-946c-8de2535c2eef.jpg)

> All the data was loaded from realml firstly, then request from server to refresh the data in realm. I can save data into and retrive data from realm. But all the data was empty when I restart my app. I remembered I can loaded saved data(Ternimate then restart app) from realm before. But now I can not. I was confused. Something I need to be careful with?

Now it dose not affect the use of my app. But it's really a problem. And I will to do more to test what happened in my app.

Thanks all.

**Comment by wakaryry** [comment]
Solved!
I miswrote a `deleteallobjects` in a class.
Thanks for all!
