### ISSUE TITLE
Realm file  size and space on disk

### ISSUE THREAD

**Issue by smolskyaleksey** [realm/realm-cocoa#2852]
Hi everyone. Any single Realm file cannot be larger than the amount of memory your application would be allowed to map in iOS .Could you prompt how to detect that realm file is big and we can't to save new data? And I should create a new Realm file.

**Comment by bdash** [comment]
The methods that commit write transactions will raise an error if one occurred. One possible error is a failure to expand the memory mapping. For Objective-C, see [`-[RLMRealm transactionWithBlock:error:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/transactionWithBlock:error:) and [`-[RLMRealm commitWriteTransaction:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/commitWriteTransaction:), and for Swift see [`Realm.write(_:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm5writeFS0_FzFT_T_T_) and [`Realm.commitWrite()`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm11commitWriteFS0_FzT_T_).

**Comment by smolskyaleksey** [comment]
Hi, in accordance with source file and doc api  ```-[RLMRealm commitWriteTransaction:]``` throw RLMErrorFail 
https://i.gyazo.com/1357b129c5f74113607e3c33bcb7a5c9.png 

RLMErrorFail
Returned by RLMRealm if no other specific error is returned when a realm is opened.

This error does not describe clearly what has happened. It is can be anything.

**Comment by jpsim** [comment]
@smolskyaleksey is there anything more we can do to help you here? Please reopen if you have any further questions.
