### ISSUE TITLE
module.modulemap:16:16: error: header 'RLMOptionalBase.h' not found

### ISSUE THREAD

**Issue by gunterhager** [realm/realm-cocoa#2853]
I've added Realm (via carthage) to a Swift project and get this error when building:
```
.../Carthage/Build/iOS/Realm.framework/Modules/module.modulemap:16:16: error: header 'RLMOptionalBase.h' not found
        header "RLMOptionalBase.h"
               ^
<unknown>:0: error: could not build Objective-C module 'Realm'
```

Versions:
Realm 0.96.2
Xcode 7.1.1
Carthage 0.10.0

**Comment by jpsim** [comment]
Hey, sorry for the delay in getting back to you on this :grimacing:. It's probably long gone by now, but seeing Carthage's log output from running `carthage update` would greatly help us identify what may have happened here.

If you're still having issues with this, I recommend you just re-bootstrap your Carthage dependencies: `rm -rf Carthage; carthage update`. And if that fails, I encourage you to share the resulting Carthage logs so we can help you troubleshoot.

**Comment by gunterhager** [comment]
Thanks for the reply. The issue wasn't solved, but it happened only when building the project on our continuous integration Xcode server. I could never reproduce the problem on my local Xcode. I created a fresh test project with Realm added via `carthage update` and it built without a problem on our CI server. The issue needs further investigation on my side.

Conclusion: it seems to be a problem with our project/server setup rather than a Realm issue.

**Comment by jpsim** [comment]
> Conclusion: it seems to be a problem with our project/server setup rather than a Realm issue.

Ok, let us know if there's anything we can do to help anyway.
