### ISSUE TITLE
Object_schema.cpp file not found

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-cocoa#2857]
Hi Realm team.

I\`m trying to use the last version(0.96.2) of Realm with Swift 2, Xcode 7.0.1 and CocoaPods 0.39.0. Before, I compile it and works fine for a long time.
But now I updated the version of Realm and this problem starts. 

![captura de tela 2015-11-13 as 17 57 14](https://cloud.githubusercontent.com/assets/5521682/11155963/0500e05a-8a30-11e5-9f4e-043466caea30.png)

My podfile is:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!

    target 'MyHappyApp' do
        pod 'PureLayout'
        pod 'RealmSwift', '~> 0.96.2'
        pod 'Alamofire', '~> 2.0.2'
        pod 'AlamofireObjectMapper', '~> 1.0'
        pod 'AlamofireImage', '~> 1.0'
        pod 'RealmMapView', '~> 1.6.6'  (use the 0.96.2')
        pod 'FBSDKLoginKit', '~> 4.7'
        pod 'MBProgressHUD', '~> 0.9.1'
        pod 'PullToRefreshSwift'
    end

I tried to clean the project and clean the pod too. This would be a problem inside of RealmMapView, but I don\`t know.
Can you help me?

**Comment by kishikawakatsumi** [comment]
@ppamorim It might be hit this issue https://github.com/realm/realm-cocoa/pull/2675

Can you try remove existing pods and caches, then re-install pods again?

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

**Comment by ppamorim** [comment]
@kishikawakatsumi  Not working.

**Comment by jpsim** [comment]
We have a known CocoaPods issue #2701 where Realm fails to install on first run, so I'd recommend you try running `pod install` again. Please let us know if this works for you.

**Comment by ppamorim** [comment]
I`m using the version 0.39.0 and I have cleaned the cache. But this happens when I try to install the pod:
![captura de tela 2015-11-16 as 15 43 01](https://cloud.githubusercontent.com/assets/5521682/11189740/c281b9de-8c78-11e5-9a2c-250fd8ab97b5.png)

**Comment by jpsim** [comment]
Which begs the question... do you have an active internet connection? That message at the bottom is printed when https://static.realm.io/downloads/core/realm-core-0.94.0.tar.bz2 can't be downloaded.

**Comment by ppamorim** [comment]
This problem only happens with Realm. I add another library and works fine.

**Comment by ppamorim** [comment]
![captura de tela 2015-11-16 as 16 47 43](https://cloud.githubusercontent.com/assets/5521682/11191354/fddcab34-8c81-11e5-96b5-41dbb4a095e2.png)
![captura de tela 2015-11-16 as 16 47 55](https://cloud.githubusercontent.com/assets/5521682/11191353/fd4812f8-8c81-11e5-9750-cc581fe13f51.png)

**Comment by jpsim** [comment]
what happens when you run `curl -OL https://static.realm.io/downloads/core/realm-core-0.94.0.tar.bz2`? Does the download succeed?

**Comment by ppamorim** [comment]
@jpsim Not working. No curl, no pods, no website too, I changed the computer and happens the same. :( I've contacted the network manager and he informs that don`t have anything blocking at the network.
I don't know what's happening.

**Comment by ppamorim** [comment]
Network problem solved! Working with 4G...
