### ISSUE TITLE
Extra space in run script phase breaks compiling

### ISSUE THREAD

**Issue by jbennett** [realm/realm-cocoa#2860]
I was having an issue with getting a fresh project to compile after adding realm. It turns out when I copy/pasted the paths for the frameworks when setting up the run script phase, there was an extra space; the compiler wasn't able to find "Realm.framework ". 

It may be worth while to make sure there is no extra white space around that text to help others avoid this too.

**Comment by bdash** [comment]
@jbennett, I'm sorry that caused you trouble. Can you please point me to the page that you copy-pasted from which gave you the extra space character in you Run Script Phase? I'm not seeing anything obviously wrong in this regard with the latest version of our [Objective-C](https://realm.io/docs/objc/latest/) or [Swift](https://realm.io/docs/swift/latest/) documentation.

**Comment by jbennett** [comment]
Sorry, that wasnt very clear. This is part of the Carthage instructions for 2.1 and 1.2 at https://realm.io/docs/swift/latest/. An image demonstrating the problem is attached. 
The current code is:

```
<p><code>
$(SRCROOT)/Carthage/Build/iOS/Realm.framework
<br>$(SRCROOT)/Carthage/Build/iOS/RealmSwift.framework
</code></p>
```

If the code is changed to something similar to the following it will eliminate the white space that is (in)conveniently added for you.

```
<p><code>
$(SRCROOT)/Carthage/Build/iOS/Realm.framework<br>$(SRCROOT)/Carthage/Build/iOS/RealmSwift.framework
</code></p>
```

<img width="508" alt="extra space character" src="https://cloud.githubusercontent.com/assets/84053/11232440/53c04a7e-8d81-11e5-87a8-1c243c6cc61e.png">

**Comment by bdash** [comment]
Thanks, I now see what you mean.

**Comment by jpsim** [comment]
Thanks for the details @jbennett! This is now fixed and should be live on the site in a few minutes.
