### ISSUE TITLE
How to ignore category properties without adding ignoredProperties? 

### ISSUE THREAD

**Issue by singro** [realm/realm-cocoa#2867]
Categories with extra properties are adding to my RLMObject for caching or storing temporary data, but all those properties should add to +ignoredProperties.  Is there any configuration that Realm could ignore all properties added by categories?

**Comment by mrackwitz** [comment]
The information where your properties were defined is lost at runtime, when the schema is reflected from your model classes. Overwriting methods as `+ignoredProperties` from category itself would be indeterministic and not to recommend, you will need to use a different approach.

You could modify the reflected schema and setup your `RLMRealmConfiguration` with a custom schema, but this would require that the properties to ignore, conform to the requirements of persisted properties in the first place.

So, what I would indeed finally recommend, is to use the `+ initialize` method from your category to overwrite `+ignoredProperties` on `RLMObject` at runtime by [method swizzling](http://nshipster.com/method-swizzling/) and inject your list of ignored properties there. You don't need to invoke the original implementation of the method as it is just returning `nil`. But if you define ignored properties anywhere else, you will need to invoke the super implementation consequently and modify the returned array to add further property names to ignore.

This might feel hacky, but as we don't offer a public API to ignore common properties independent from the class and you can't have a custom intermediate parent class inheriting from `RLMObject`, which is not persisted, it's the only way for that case.
