### ISSUE TITLE
Initializing a field with a realm call blocks on thread

### ISSUE THREAD

**Issue by tom-sparo** [realm/realm-cocoa#2868]
Hey Realm people,

I was trying to initialize a field with a realm call, and got a blocked thread.

Here's an example of what I mean:

```swift
//
//  testRealm.swift
//
//  Created by Tom Wilkinson on 11/17/15.
//

import XCTest
import RealmSwift

class TopLevelObject: Object {
    dynamic var nested: NestedObject? = {
        if let object = try? Realm().objectForPrimaryKey(NestedObject.self, key: "default") {
           return object
        }
        return nil
    }()
}

class NestedObject: Object {
    dynamic var key: String = ""
    
    override static func primaryKey() -> String? {
        return "key"
    }
}

class testRealm: XCTestCase {

    func testExample() {
        let _ = TopLevelObject() // Blocks forever
    }
    
}
```

So first to explain why I'm trying for this behavior.  It's useful in my case to query another Realm object to find a default object that should be set for another Realm object's fields.  That default object may change dynamically throughout the lifetime of the Realm, so its not the type of thing that I want to hardcode in, and also would ideally be set on init, and wouldn't have to be set by the user every time.  Concretely, imagine you have a `Session` object, and a `Task` object that has a `session` field that you want to default populate with the current active `Session,` where the current active `Session` is marked with a field of its own, and stored in Realm.

And I think what's causing this is mostly the following lines in RLMSchema.mm

```objc
// schema based on runtime objects
+ (instancetype)sharedSchema {
    static std::once_flag onceFlag;
    std::call_once(onceFlag, [&](){
        RLMSchema *schema = [[RLMSchema alloc] init];

        unsigned int numClasses;
        std::unique_ptr<__unsafe_unretained Class[], decltype(&free)> classes(objc_copyClassList(&numClasses), &free);
        [self registerClasses:classes.get() count:numClasses];

        // set class array
        schema.objectSchema = s_partialSharedSchema.objectSchema;

        // set shared schema
        s_sharedSchema = schema;
    });
    return s_sharedSchema;
}
```

The first time we get to that `std::call_once` is from the `Realm().objectForPrimaryKey()` call to setup the Realm from the configuration, but then to get the properties to get the shared schema, there's this unfortunate swift quirk:

```objc
// For Swift classes we need an instance of the object when parsing properties
    id swiftObjectInstance = isSwiftClass ? [[objectClass alloc] init] : nil;
```

Which then goes and tries to call `Realm().objectForPrimaryKey()` again and hits the `std::call_once` wall and deadlocks.

The workaround for me isn't a big deal, I just have to force users to remember to initialize that field themselves, but I thought I would bring it to your attention in case it's a bug you feel like should be worked on or at least mentioned in docs to avoid (or throw an exception?  Hard to figure out at runtime whether a user is going to try and call Realm inside their init).  Or is this something that I'm doing wrong?

**Comment by mrackwitz** [comment]
I don't see anyway how to avoid that internally. As you see, we need instances of Swift classes to properly reflect all property types.

You could resolve that by making the property optional and initializing the property value from an overwritten initializer, after the super initializer was called.

Alternatively you could implement the property with a private field and decorate that with a method  / non-persisted computed property, which checks whether there is an overwritten value and if not falls back to the default value, which would have the semantic difference that the default value at time of object creation is not retained / persisted, but depending on your exact use case that might work as well.

**Comment by tom-sparo** [comment]
Yes I agree with you.  No way to avoid that until Swift reflection improves.

But I think it should at least throw an error rather than blocking!

**Comment by mrackwitz** [comment]
Yes, that would be preferable, but that could get really ugly as we would need to lock/observe Realm initialization on the same thread with partial schemas, which contain the current class' object schema as well.

I'd agree that we should document that fact better.

Perhaps also introducing an API in Swift allowing to set computed default values for properties after instance initialization could resolve that issue and avoid having to use custom initializers, which brings the side-effect of having to implement all required initializers yourself in the subclass calling the superclass. But makes that models easier to understand?

**Comment by tom-sparo** [comment]
Really?  It seems to me that if you hit that `std::call_once` on the same thread twice then it will always deadlock, no matter what.  A thread can check whether or not it called `std::called_once` and throw an error if it did (store the thread that called c++ method and if it's about to call it again, check to make sure the thread ids are different so it doesn't deadlock).  The conditions for deadlock are well known (same thread getting a lock on an object that it already holds a lock on) and can be checked before trying to get a lock.

But if that's not the case, documentation would be nice I suppose?

A new API is another solution, though it's such a small use-case (I can't imagine many people try to call Realm inside their init) that I can't imagine it'd be a priority for a long long time.

And as a small use-case anyways, seems to me okay to leave it up to the user to handle the custom (partial) initialization.  In the past I've done things with a init then immediately postInit framework.  There are lots of builder-type design patterns that can hide the gritty details of that process if need be.

**Comment by mrackwitz** [comment]
No, you're right. I missed somehow the bigger picture and focused to much on the place where the recursive calls comes from when I was suggesting that. To my understanding, we could indeed just check whether the method was called recursively in the way you proposed. That brought me quickly to other limitations, which were more the current setup of our test harness than really due to the technical possibilities. But meanwhile I found a way to workaround that. See #2990.

**Comment by tom-sparo** [comment]
Looks good to me!  Thanks for getting around to this.
