### ISSUE TITLE
Realm.Configuration.defaultConfiguration.schemaVersion

### ISSUE THREAD

**Issue by seedotlee** [realm/realm-cocoa#2869]
ex:

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?)  {

           let realmVersion:UInt64 = 1
           let defaultConfig = Realm.Configuration.defaultConfiguration
           print("old version:\(defaultConfig),version:\(Realm.Configuration.defaultConfiguration.schemaVersion)")
//there always print 0
            let version = defaultConfig.schemaVersion
            if version != realmVersion {

                if let path = Realm.Configuration.defaultConfiguration.path {
                    try! NSFileManager().removeItemAtPath(path)
                }
            }
            
            Realm.Configuration.defaultConfiguration = Realm.Configuration.init(
                schemaVersion: realmVersion,
                migrationBlock: { migration, oldSchemaVersion in
                    if (oldSchemaVersion < realmVersion) {
                    }
            })
            
            print("new version:\(Realm.Configuration.defaultConfiguration),version:\(Realm.Configuration.defaultConfiguration.schemaVersion)")
//there print 1
...
}
```

App old version is always 0 when the app restart ~

Are there anything wrong to used?

**Comment by jpsim** [comment]
Note that the default configuration is not persisted. It's a Swift struct that's created at runtime. So updates to the default configuration won't be persisted across invocations of your app.

This is why `Realm.Configuration.defaultConfiguration.schemaVersion` is always zero at app launch.

If you want to determine the schema version of a Realm file on disk, you can use Realm Swift's free function [schemaVersionAtPath(_:encryptionKey:error:)](https://realm.io/docs/swift/latest/api/Functions.html#/s:F10RealmSwift19schemaVersionAtPathFTSS13encryptionKeyGSqCSo6NSData_5errorGVSs33AutoreleasingUnsafeMutablePointerGSqCSo7NSError___GSqVSs6UInt64_) to do so.

**Comment by seedotlee** [comment]
OK, Thank you~
`schemaVersionAtPath(_:encryptionKey:error:)` 
That 's the answer I need.
