### ISSUE TITLE
CreateOrUpdate Function : How to modify/update an object without removing the existing values

### ISSUE THREAD

**Issue by modLX4** [realm/realm-cocoa#2872]
By calling CreateOrUpdate function, an existing object is is actually replaced with new values and existing values are wiped. Is it there any work around for just replacing the values without removing the existing values ??

**Comment by jpsim** [comment]
`+[RLMObject createOrUpdate:]` only overwrites existing values if they are passed in. Omitting a key from the value you're passing in will leave the previous property value intact.

```objc
@interface Book : RLMObject
@property float price;
@property NSString *title;
@property int id;
@end

@implementation Book
+ (NSString *)primaryKey {
  return @"id";
}
@end

// Assuming a "Book" with a primary key of `1` does not already exist.
RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[Book createOrUpdateInRealm:realm withValue:@{@"id": @1, @"price": @9000.0f, @"title": @"Cheese recipes"}];

// partially update the object: just the price.
[Book createOrUpdateInRealm:realm withValue:@{@"id": @1, @"price": @4500.0f}];
// the book's `title` property will remain unchanged.
[realm commitWriteTransaction];
```

So by omitting the `title` property from the dictionary, we preserved the existing value of "Cheese recipes".

For more information, please refer to the "Updating Objects" section of our Objective-C documentation: https://realm.io/docs/objc/latest/#updating-objects

**Comment by modLX4** [comment]
Thats great. How to apply this for relationships, how to update values in relationship from top level object ?
<img width="595" alt="screen shot 2015-11-19 at 2 21 19 pm" src="https://cloud.githubusercontent.com/assets/12533332/11266214/edaf99da-8ec8-11e5-801e-41cf2bf71eda.png">

**Comment by modLX4** [comment]
When we try to update the relationship from top level objects, what happens is that the entire array is wiped and updated with this whatever we have passed, even if the relationship object has a primary ID

**Comment by jpsim** [comment]
What method(s) are you calling on the `RLMArray` property? If you're *setting* that property, then anything it linked to previously will no longer be linked to, because you just overrode that property.

I get the feeling I may be misunderstanding what you're referring to though. If that's the case, please share sample code that demonstrates what you expect to happen, and what actually happens. Thanks.

**Comment by jpsim** [comment]
@modLX4 we haven't heard back from you in a while on this issue. Please reopen if you have any further questions.
