### ISSUE TITLE
Weird Crash; Objective-C; Realm 0.96.2; "Object has been deleted or invalidated."

### ISSUE THREAD

**Issue by istx25** [realm/realm-cocoa#2875]
I have been searching everywhere to find a solution to a weird problem I can’t seem to solve. The Realm tag on Stackoverflow has not revealed anything useful and I haven’t found anything in the documentation (yet) that can point me in the right direction.

For context: We are building an application that gets the best restaurants in your area from Foursquare and saves them to Realm. The application then gets a randomised index from the Realm array storing the restaurants to display “a random best restaurant near you”. We also have an object for the User which stores the user’s preferences locally in Realm.

I am trying to implement a button on the settings panel that deletes all of the data in Realm and brings the user back to our on boarding flow to provide new preferences and a clean slate for the restaurants object. When the user taps the button, a `UIAlertController` is presented with a destructive action. The following code is in the handler upon pressing that confirmation button:

```
RLMRealm *realm = [RLMRealm defaultRealm];

[realm beginWriteTransaction];
[realm deleteAllObjects];
[realm commitWriteTransaction];

[[NSUserDefaults standardUserDefaults] removeObjectForKey:kUserCreatedFlag];
[self performSegueWithIdentifier:kSegueToOnboardingFlowAfterDestruction sender:self];
```

My thought process:

1. Delete all objects in the default Realm.
2. Remove the NSUserDefaults flag that is used to check if a user exists/which storyboard to present.
3. Perform a segue to the onboarding flow.

But unfortunately we I can not get around this crash:

```
2015-11-18 11:10:17.218 Lunchtime[8629:3384811] *** Terminating app due to uncaught exception 'RLMException', reason: 'Object has been deleted or invalidated.'
*** First throw call stack:
(0x18433cf48 0x1997e7f80 0x10011e0b0 0x1000980cc 0x100097e48 0x100180fcc 0x100181568 0x100092158 0x189d357d8 0x189d35f70 0x189c24ba4 0x189c27d9c 0x1899ff668 0x18990b240 0x18990ad3c 0x18990abc4 0x1890d1c2c 0x101df1c68 0x101df7710 0x1842f41f8 0x1842f2060 0x184220ca0 0x18f7a4088 0x189938ffc 0x100097b34 0x19a02a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I have confirmed in the Realm Browser that all of the data has been removed from Realm but I am still receiving this crash for some reason. I would really appreciate it if someone could offer some insight into why this is happening. My instructors are also having a hard time figuring out what the issue is. Could this be an undefined/incorrectly defined exception in Realm?

Looking forward to hearing from someone. :)

**Comment by bdash** [comment]
The exception you're seeing, "Object has been deleted or invalidated", is thrown if you attempt to access properties of an object that has been deleted from the Realm or explicitly invalidated via a call to `-invalidate`. After your call to `-[RLMRealm deleteAllObjects]`, all `RLMObject`s that you have previously retrieved from the the Realm are invalid and cannot be accessed. To understand where this is happening in your application, you can add a [breakpoint when Objective-C exceptions are thrown](https://developer.apple.com/library/ios/recipes/xcode_help-breakpoint_navigator/articles/adding_an_exception_breakpoint.html#//apple_ref/doc/uid/TP40010433-CH1-SW1). This will drop you into Xcode's debugger at the point when the exception is thrown, which should help you pinpoint where in your application you're accessing the deleted object.

**Comment by istx25** [comment]
Ouch. So much time spent on such a *dumb* problem. Thanks @bdash for mentioning the Objective-C exception breakpoint. I did turn this on before but it was disabled for Objective-C for some reason. After fixing that issue, I quickly tuned into what was causing this.

In my case, I was using a `RLMNotificationBlock` to update the UI whenever a change was made to the Restaurant model.

```
self.token = [[RLMRealm defaultRealm] addNotificationBlock:^(NSString *notification, RLMRealm *realm) {
    [self updateUI];
}];
```

And because `[self updateUI]` accessed several objects that were deleted beforehand, I was receiving that crash. Adding a quick check to see if `[RLMRealm defaultRealm]` is empty fixed the issue.

Thank you! :dancer:
