### ISSUE TITLE
Creating model object with init(value:_) causes memory leak with To-Many relationship

### ISSUE THREAD

**Issue by samvanderhyden** [realm/realm-cocoa#2882]
I have two models such as these:

```swift
class Person: Object {
    dynamic var name:String = ""
}

class Dog: Object {
    dynamic var name = ""
    dynamic var age = 0
    let owners = List<Person>()
}
```

Simply creating a dog object like this:

```swift
let myOtherDog = Dog(value: ["name" : "Pluto", "age": 3])
```
causes instruments to report a leak of List<Person> and RLMArray 
<img width="1396" alt="screen shot 2015-11-19 at 10 22 59 am" src="https://cloud.githubusercontent.com/assets/2964502/11280332/65457916-8eaa-11e5-89da-d8afece0ac9f.png">

Instruments does not report a leak when just creating an object using init such as 

```swift 
let myDog = Dog()
```

Example Project: https://www.dropbox.com/s/kckg4xqv4uhstd3/RealmSwiftLeak.zip?dl=0

Info:
Realm (0.96.2)
RealmSwift (0.96.2)
OSX 10.10.5
XCode 7.1
CocoaPods 0.39.0

**Comment by tgoyne** [comment]
The `[self init]` call in `-[RLMObjectBase initWithValue:schema:]` appears to be the culprit, since it calls `RealmSwift.Object.init()` rather than `-[RLMObjectBase init]`, resulting in the Swift properties getting initialized a second time and the originals being leaked.
