### ISSUE TITLE
Cannot load underlying module for 'RealmSwift'

### ISSUE THREAD

**Issue by kishanravindra** [realm/realm-cocoa#2885]

**Comment by mrackwitz** [comment]
Would you mind [providing a bit more info](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) to make it possible to help you?

**Comment by ataibarkai** [comment]
Seems to be an Xcode bug (?)

To get it running, make sure you build+run the project before installing Realm using cocoapods.

My specs:
-Swift project
-OS X 10.11.1 (El Capitan)
-Xcode 7.1.1
-Cocoapods 0.39.0
-Realm 0.96.2

**Comment by mrackwitz** [comment]
Hey @ataibarkai, I totally missed your latest comment.
What do you reference here / how do you mean that:
>To get it running, make sure you build+run the project before installing Realm using cocoapods.

Were you able to get it working by building the project as a first step? That'd be really odd.

**Comment by ataibarkai** [comment]
Yes I was, odd indeed.

(Just to clarify:
* New project -> add realm via cocoapods **w/o building first** -> open Xcode workspace -> build&run = failure
* New project -> build&run -> add realm via cocoapods -> open Xcode workspace -> build&run again -> success
)

**Comment by jpsim** [comment]
Looks like #2701.

**Comment by jpsim** [comment]
I'm fairly certain this is #2701 based on the information provided here, so I'm closing this one as a duplicate. This has been a long standing issue, so if anyone would like to take a crack at addressing it, we'd appreciate it!

**Comment by Yakis** [comment]
Just Cmd + B (build), and errors will disapear. :) Worked at me.
