### ISSUE TITLE
Question:  1 to many relationship delete operation

### ISSUE THREAD

**Issue by ArEnSc** [realm/realm-cocoa#2890]
Hey is this feature supported yet?

**Comment by mrackwitz** [comment]
Could you elaborate what you mean by your question? Do you want to delete all associated objects for a given to-many relationship? That's possible by [`List.removeAll()`](https://realm.io/docs/swift/latest/api/Classes/List.html#/s:FC10RealmSwift4List9removeAlluRdq_CS_6Object_FGS0_q__FT_T_).

**Comment by jpsim** [comment]
Actually, `List.removeAll()` removes the objects from the `List` but does not delete those objects from the `Realm`. Passing the `List` to [`Realm.delete(_:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6deleteuRq_Ss12SequenceTypedqqq_S1_9GeneratorSs13GeneratorType7ElementCS_6Object_FS0_Fq_T_) will delete the objects from the `Realm` and by consequence remove them from the `List`.

**Comment by ArEnSc** [comment]
Is there a way to determine generically, whether or not a parent has children? without actually referencing the property ? then access the children generically and deleting the children.

for instance
```obj-c
Task <-- Parent Object
SubTask <-- Child Object

if([task hasChildren]) {
  RLMDelete(task.children); //
}
vs
if([task hasChildren]) {
  RLMDelete(task.subtasks); // 
}


```

**Comment by mrackwitz** [comment]
No, there is no way to achieve something like that without accessing the property in one way or another.
What you could theoretically do is to access the `RLMObjectSchema` of the object, iterate over the properties, filter them by their type and dynamically check for all list properties whether there are objects over the count property and delete them. But you can also pass an empty list to [`Realm.delete(_:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6deleteuRq_Ss12SequenceTypedqqq_S1_9GeneratorSs13GeneratorType7ElementCS_6Object_FS0_Fq_T_).
I wonder how this is necessary at all for your use-case?

**Comment by mrackwitz** [comment]
I'll close this issue for now, but if you feel strong urge that this is something we need to have, please feel free to re-open and describe how you're using it and why this is needed.
