### ISSUE TITLE
Bad access after realm has been deleted from disk and created again

### ISSUE THREAD

**Issue by brianblanchard-wf** [realm/realm-cocoa#2893]
Ok, so I have a realm the directory `[app folder]/Documents/db/` so the path of the realm is `[app folder]/Documents/db/default.realm`. When a user logs out we have to delete the realm for security reasons. I am getting a BAD_ACCESS [here](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMObjectStore.mm#L126). It seems as `table` is not defined. This is happening after I delete a realm at the specified path, recreate it, and then perform a write transaction. I have verified that the realm file and all associated `.lock` files are removed and then recreated correctly. 

I am using realm `0.96.2` on `iOS 9.1`.

Any help you can lend would be greatly appreciated. 

Here is all my system info:
```
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42

/Applications/Xcode.app/Contents/Developer
Xcode 7.1.1
Build version 7B1005

/usr/local/bin/pod
0.39.0

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/bin/git
git version 2.4.9 (Apple Git-60)
```

Edit: If I delete the realm at the specified path above, force quit the app, then recreate it, all is good. Let me know if you need anymore info.

**Comment by mrackwitz** [comment]
Before deleting a Realm file, you need to make sure that you don't hold anymore any accessor to it. This includes all instances of the following classes: `RLMRealm`, `RLMObject`, `RLMResults`. From what you describe, it seems very likely to me that you're still holding a reference to it somewhere and it has an invalid state through that.

**Comment by jpsim** [comment]
I think @mrackwitz's assessment of the situation is correct. @brianblanchard-wf we're closing this issue because we haven't heard back from you in a while, but please do reopen if you'd like some clarifications or have any further questions.
