### ISSUE TITLE
Realm accessed from incorrect thread

### ISSUE THREAD

**Issue by mewehk** [realm/realm-cocoa#2894]
@interface Dialog : RLMObject
@property User *chatUser;
@end

@interface User : RLMObject
@end

There is some User records in DB.
I create a new Dialog object A, then get a User object B from DB on main thread.
A.chatUser = B;

Then call below on other thread, it crash. 'Realm accessed from incorrect thread'
[Dialog createOrUpdateInDefaultRealmWithValue:A];

I want to know how to create relationship with a new object and a exist object ?

**Comment by kishikawakatsumi** [comment]
@mewehk Realm objects cannot across thread at the moment. You can A) create all related objects on other thread, or B) create and save on main thread, then re-fetch these objects on other thread.

A. Create Dialog object A and get a User object B on other thread.
B. Create Dialog object A then save it. Get A and User object B from DB on other thread.

**Comment by mewehk** [comment]
@kishikawakatsumi Thank u. I provide two methods, one is add method, the other is query method. They both use the same dispatch_queue_t. But As I know, GCD queue cannot keep on the same Thread. how should I do?

**Comment by kishikawakatsumi** [comment]
Most robust way is executing fetch and create in same block. Fetch Realm object at beggining of the block, and create objects and save left of the block.

Also I'm wondering why you use GCD for all operaions. Generally, Realm is enough fast to executing queries on main thread.

Could you please more details or show your code snippets? Then I might show you more practical advise.

**Comment by jpsim** [comment]
@mewehk we're closing this issue because we haven't heard back from you in a while. Please reopen if you'd like any clarifications or have any further questions.
