### ISSUE TITLE
JSON Marker error with Realm

### ISSUE THREAD

**Issue by stevelyons** [realm/realm-cocoa#2897]
Hello, 
I am trying to use Realm to handle marker map objects and I continue to get errors: 
// From Marker.h
#import <Foundation/Foundation.h>
#import <CoreLocation/CoreLocation.h>
#import "MTLModel.h"
#import <Mantle/Mantle.h>
#import <Realm/Realm.h>

@interface Marker : RLMObject
@property (nonatomic) NSInteger *markerID;
@property (nonatomic) NSString *markerTitle;
@property (nonatomic) NSString *markerName;
@property (nonatomic) NSString *markerJurisdiction;
@property (nonatomic) NSString *markerAddress;
@property (nonatomic) NSString *markerCity;
@property (nonatomic) NSString *markerState;
@property (nonatomic) NSString *markerInformation;
@property (nonatomic) NSString *markerStatus;
@property (nonatomic) CLLocationDegrees markerLatitude;
@property (nonatomic) CLLocationDegrees markerLongitude;
@end 

// from Marker.m
#import "Marker.h"
#import "RLMObject+JSON.h"

@implementation Marker

+ (NSDictionary *)JSONInboundMappingDictionary {
    return @{
             @"id": @"markerID",
             @"name": @"markerName",
             @"jurisdiction": @"markerJurisdiction",
             @"address": @"markerAddress",
             @"lat": @"markerLatitude",
             @"lng": @"markerLongitude",
             @"type": @"markerStatus",
             @"comment": @"markerInformation",
            };
}

+ (NSDictionary *)JSONOutboundMappingDictionary
{
    return @{
             @"markerID": @"id",
             @"markerName": @"marker.name",
             @"markerJurisdiction": @"marker.jurisdiction",
             @"markerAddress": @"marker.address",
             @"markerStatus": @"marker.status",
             };
}

+ (NSString *)primaryKey
{
    return @"markerID";
}

The Error is: 
Terminating app due to uncaught exception 'RLMException', reason: 'Can't persist property 'markerID' with incompatible type. Add to ignoredPropertyNames: method to ignore.'
*** First throw call stack:

**Comment by jpsim** [comment]
Your `markerID` property's type is a pointer to an `NSInteger`. You probably want to store this as an integer: `@property (nonatomic) int markerID;`.

**Comment by stevelyons** [comment]
Hello again,

I changed in the Marker.h file to 
@property (nonatomic) int *markerID;

Consequently, I changed in the Marker.m file to:

#import "Marker.h"
#import "RLMObject+JSON.h"

@implementation Marker

+ (NSDictionary *)JSONInboundMappingDictionary {
    return @{
             @"id": @"markerID",
             @"name": @"markerName",
             @"jurisdiction": @"markerJurisdiction",
             @"address": @"markerAddress",
             @"lat": @"markerLatitude",
             @"lng": @"markerLongitude",
             @"type": @"markerStatus",
             @"comment": @"markerInformation",
            };
}

+ (NSDictionary *)JSONOutboundMappingDictionary
{
    return @{
             @"markerID": @"id",
             @"markerName": @"marker.name",
             @"markerJurisdiction": @"marker.jurisdiction",
             @"markerAddress": @"marker.address",
             @"markerStatus": @"marker.status",
             };
}

+(int *) primaryKey
{
    //return @"markerID";
    
    int markerID = [@"markerID" intValue];
    return markerID;
}

I'm currently getting errors for the the primaryKey:
Conflicting return type in implementation of primaryKey: NSString * _Nullable vs int * _Nullable

**Comment by jpsim** [comment]
You're still storing `markerID` as a *pointer* to an int, rather than an int.

Change this: `@property (nonatomic) int *markerID;` to this: `@property (nonatomic) int markerID;`.

**Comment by bdash** [comment]
>```objc
> +(int *) primaryKey
> {
>     //return @"markerID";
> 
>     int markerID = [@"markerID" intValue];
>     return markerID;
> }
>```

Note also that `+primaryKey` should be declared as returning a `NSString *`, and should return the name of the primary key property. In other words, fix up the return type, and you can go back to using the commented-out return statement.

**Comment by stevelyons** [comment]
Okay changing back to (NSString *) worked.

I'm now running into an error with markerLatitude:

Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value '30.390406' for property 'markerLatitude''

I'm currently using: @property (nonatomic) CLLocationDegrees markerLatitude;
to represent latitude, but I get an error. 

The JSON I'm reading from looks like 
{
	"markers":[{	    
        "name": "Marker 1",
        "jurisdiction": "J1 ",
        "address": "100 Main Street, City, State",
        "lat": "30.390406",
        "lng": "-97.774994",
        "type": "go",
        "comment": "This is marker 1",
        "id": "1"
        }
]
}

**Comment by jpsim** [comment]
You're attempting to store a string (`"lat": "30.390406"`) in a `CLLocationDegrees` (a `double`). You should either change your JSON input to match the type of the properties you're attempting to store it in.

**Comment by stevelyons** [comment]
I've changed the data type to:
@property (nonatomic) NSString *markerLatitude;
@property (nonatomic) NSString *markerLongitude;

 but now I am getting the following errors 
'RLMException', reason: 'Migration is required for object type 'Marker' due to the following errors:
- Property types for 'markerLatitude' property do not match. Old type 'double', new type 'string'
- Property types for 'markerLongitude' property do not match. Old type 'double', new type 'string'

Is JSON being read as a double or string?

**Comment by stevelyons** [comment]
Now, I'm trying:
@property (nonatomic) double markerLatitude;

And get the following error:
'RLMException', reason: 'Invalid value '30.390406' for property 'markerLatitude''

**Comment by jpsim** [comment]
> but now I am getting the following errors 
> 'RLMException', reason: 'Migration is required for object type 'Marker' due to the following errors:
> 
> Property types for 'markerLatitude' property do not match. Old type 'double', new type 'string'
> Property types for 'markerLongitude' property do not match. Old type 'double', new type 'string'
> Is JSON being read as a double or string?

When you change the type of a model property, you'll need to perform a migration as explained here: https://realm.io/docs/objc/latest/#migrations

> Now, I'm trying:
> @property (nonatomic) double markerLatitude;
> 
> And get the following error:
> 'RLMException', reason: 'Invalid value '30.390406' for property 'markerLatitude''

Now you're back to your original issue of attempting to store a string in a `double`.

**Comment by jpsim** [comment]
@stevelyons we're closing this issue because we haven't heard back from you in a while. Please reopen if you'd like some clarifications or have any further questions.
