### ISSUE TITLE
how to delete api non existing object

### ISSUE THREAD

**Issue by dimakomar** [realm/realm-cocoa#2898]
How to delete api non existing object from realm database?
adding and updating works fine, but got problems with deleting, so for example when I got 3 objects on server i got still 4 objects in realm. 
Im using AlamofireObjectMapper, and ObjectMapper

**Comment by jpsim** [comment]
You can delete a Realm object by passing it in to [`Realm.delete(...)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6deleteFS0_FCS_6ObjectT_).

**Comment by dimakomar** [comment]
i know, but i want to make some sort of sync with server

**Comment by jpsim** [comment]
How you identify which objects need to be deleted is entirely up to you. One way to do this would be to diff which object IDs are available on the server, and delete the local ones that don't belong to those IDs:

```swift
let objectIDsFromServer = [0, 1, 2, 4] // from your server
do {
  let realm = try Realm()
  try realm.write {
    realm.delete(realm.objects(MyObject).filter("id NOT IN %@", objectIDsFromServer))
  }
} catch {
  print(error)
}
```
