### ISSUE TITLE
How I recreate Realm Database file?

### ISSUE THREAD

**Issue by narlei** [realm/realm-cocoa#2902]
I'm using realm database, but the file has been corrupted in any devices. I think delete the file and recreate. 
Anyone knows how is the best way to do it?

**Comment by kishikawakatsumi** [comment]
@narlei 

It is OK just to delete the file before creating any Realm(or RLMRealm) instances.
Then instantiate Realm as usual, new Realm file is created automatically.

If you used the Realm file as default configuration, the way to delete the file is the following:

```
let config = RealmConfiguration.defaultConfiguration
if let path = config.path {
    try NSFileManager().removeItemAtPath(path)
}
```

**Comment by jpsim** [comment]
@narlei we're closing this issue because we haven't heard back from you in a while. Please reopen if you'd like some clarifications or have any further questions.
