### ISSUE TITLE
Allow button disabled on the screen "realm browser needs access to this path"

### ISSUE THREAD

**Issue by pvencill** [realm/realm-cocoa#2903]
Title says it all.  I am trying to open a `default.realm` file and the window says the browser needs access, press allow to continue, but the Allow button is disabled.

**Comment by jpsim** [comment]
That's an unfortunate issue, @pvencill I'm sorry this is affecting you. I just filed https://github.com/realm/realm-browser-osx/issues/109 on our Realm Browser repository. This repository is for the Realm Cocoa framework.

@TimOliver should be able to continue the conversation with you there.
