### ISSUE TITLE
Optional property values missing when copying between realms.

### ISSUE THREAD

**Issue by smpanaro** [realm/realm-cocoa#2905]
Hi!

I have some objects:

```swift
class Task: Object {
    dynamic var name: String? = nil
    let steps = List<Step>()
}

class Step: Object {
    dynamic var name: String? = nil
    let duration = RealmOptional<NSTimeInterval>()
}
```

When I copy a `Task` from a read-only compressed realm into the default realm, everything is copied over except the `duration` property which shows up as 0 in the Realm browser. I verified using the Realm browser that the `duration` property is not 0 in the read-only Realm.

Here's a test project (it's a .zip file, so you'll have to change the extension when you download it):
![test-proj](https://cloud.githubusercontent.com/assets/2950214/11112420/ed10d2de-88e0-11e5-80ed-0d3080d1d49d.png)

My built frameworks were too big to upload, but I can find a way to upload them if needed.

Here's the output I get in my console when running the project:
```
Objects in main realm before deletion: Results<Task> (

)
Deleting all objects from main Realm.
Creating read-only Realm.
Read-only Realm saved to /Users/......./readonly.realm
Objects in the read-only realm: Results<Task> (
	[0] Task {
		name = taskName;
		steps = RLMArray <0x7fcd3b585300> (
			[0] Step {
				name = stepName;
				duration = 3.5;
			}
		);
	}
)
Inserted read-only objects into main Realm.
Objects in main realm after: Results<Task> (
	[0] Task {
		name = taskName;
		steps = RLMArray <0x7fcd3b726d90> (
			[0] Step {
				name = stepName;
				duration = (null);          <<<<< I think this should be 3.5
			}
		);
	}
)
Objects in read-only realm after: Results<Task> (
	[0] Task {
		name = taskName;
		steps = RLMArray <0x7fcd3b738740> (
			[0] Step {
				name = stepName;
				duration = 3.5;
			}
		);
	}
)
```

This is an almost perfect replica of my issue in my other project. The only difference is that my other project persists the default Realm across launches but this one does not seem to do that. 

Let me know what I'm doing wrong or if there's anything else I can provide!

I'm on XCode 7.1 (7B91b) / OS X 10.11.1 / Realm 0.96.2 / Carthage 0.9.2

**Comment by kishikawakatsumi** [comment]
@smpanaro Thank you for reporting and sample project! It will be fixed by https://github.com/realm/realm-cocoa/pull/2901 .

**Comment by jpsim** [comment]
@kishikawakatsumi are you sure that's the same issue? This one seems to be related to `Realm.writeCopyToPath(_:)`.

**Comment by kishikawakatsumi** [comment]
@jpsim I'm sure this issue isn't related to `Realm.writeCopyToPath(_:)`. Because it happens regardless whether to copy or not to copy the Realm. 

I also confirm it will be fixed by #2901 .

I try a little more investigating whether really the same problem. Thank you for your advice.

**Comment by smpanaro** [comment]
@kishikawakatsumi @jpsim Just wanted to report that this bug still exists for me in 0.96.3.

**Comment by jpsim** [comment]
Indeed. That's why it's still open.
