### ISSUE TITLE
Realm fetching empty copy

### ISSUE THREAD

**Issue by mrdavidrees** [realm/realm-cocoa#2917]
I'm having an issue with realm, it's the first time I've seen this, and it only happens in on one ViewController. simply requesting an item from realm returns an empty copy of that item.

A portion of the code

    var timeSheet : TimeSheet!

    print("job id : \(job.jobId)")
    timeSheet = realm.objects(TimeSheet).filter("jobId == \(job.jobId)").first
    print("timesheet job id : \(timeSheet.jobId)")
    print(realm.objects(TimeSheet))

and the result:

    job id : 43211
    timesheet job id : 0
    Results<TimeSheet> (
	[0] TimeSheet {
		localId = 1448935472.698334;
		jobId = 43211;
		vaccinatorId = 6516;
		numberOfParticipants = 123;
		altNumberOfParticipants = 123;
		jobHours = 0.5;
		travelHours = 0;
		extraHours = 0;
		expensesTotal = 0;
		expensesDesc = ;
		comments = ;
		isComplete = 0;
		batchNumber = 123;
	}
    )

as you would expect, by printing out the timesheet jobid, it would be 43211, as that is what it was matched on when fetching it from realm
![screen shot 2015-12-01 at 2 21 52 pm](https://cloud.githubusercontent.com/assets/811705/11492309/f14ff7c0-9836-11e5-88f9-b47bd96d7531.png)

This is the realm at that current time.
I'm using realm 0.96.2, which is the lastest listed on the website at this time.
Xcode 7.1
cocoapods-0.39.0

**Comment by mrackwitz** [comment]
The format string and arguments provided to `Results.filter` is directly passed to `NSPredicate`. You passed instead a complete string containing the value as fixed string. But your column type is an integer, so you get an empty result. Try to query like that instead:
```
realm.objects(TimeSheet).filter("jobId == %@", job.jobId).first
```

**Comment by mrdavidrees** [comment]
Same result.. It shouldn't matter whether I passed a complete predicate string or a predicate with args. Even if changing my filter did fix the issue, realm shouldn't be returning any objects when nothing matches the predicate, let alone empty copies of that object... Right?

When I print(timeSheet.jobId) it proves two things, one that the filter has worked and it has returned an object (otherwise timeSheet would be nil), and that the jobId of the returned object doesn't match the filter that it was queried on.

Surely something is up...

**Comment by mrackwitz** [comment]
>realm shouldn't be returning any objects when nothing matches the predicate, let alone empty copies of that object... Right?

You're absolutely right here. Your implicitly unwrapped optional should have thrown an exception instead, when trying to access the property, missed that somehow when I was skimming your code.

Could you share some example with us (privately to help@realm.io) where you can reproduce this issue? That would be really helpful to investigate that further.

**Comment by mrdavidrees** [comment]
Resolved. My TimeSheet model has all the variables not marked as dynamic

was:

    var jobId = 0
    var vaccinatorId = 0
    var numberOfParticipants = 0
    var altNumberOfParticipants = 0
    var jobHours = 0.0

now is:

    dynamic var jobId = 0
    dynamic var vaccinatorId = 0
    dynamic var numberOfParticipants = 0
    dynamic var altNumberOfParticipants = 0
    dynamic var jobHours = 0.0

Thanks to help@realm.io :)
