### ISSUE TITLE
Include of non-modular header inside framework module 'Realm'/'Realm.Private'

### ISSUE THREAD

**Issue by johnpaulmanoza** [realm/realm-cocoa#2919]
Been trying to resolve this but got no luck. I installed the version 0.96.2 and I started to have this error
Include of non-modular header inside framework module 'Realm'/'Realm.Private'

I tried adding CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES/NO to my post install already but still not working. Xcode fails to compile the RealmSwift Framework for this reason.

Any ideas to resolve this. Thanks.

**Comment by mrackwitz** [comment]
As you refer to "post install" and setting a custom bulid setting there, I guess you're using CocoaPods to integrate Realm in your project? Which version of CocoaPods do you use? Can you make sure to update to the latest version?

**Comment by johnpaulmanoza** [comment]
Updating to the latest version of cocoapods fixed the issues for me. 
Thanks @mrackwitz 
Stay awesome :)

**Comment by mrackwitz** [comment]
Sure, that's what we are striving for. :) Thanks for reporting back and have fun!
