### ISSUE TITLE
realm 0.95.0 crash for few users

### ISSUE THREAD

**Issue by tariq235** [realm/realm-cocoa#2926]
```
PROJECT_NAME
TransformationMatrix.h line 86 in [WebCore::TransformationMatrix::isIdentity() const]
PROJECT_NAME
group_shared.hpp line 268 in [realm::SharedGroup SharedGroup(realm::Replication&, realm::SharedGroup::DurabilityLevel, char const*) ]
PROJECT_NAME
RLMRealm.mm line 235 in [RLMRealm initWithPath:key:readOnly:inMemory:dynamic:error:]
PROJECT_NAME
RLMRealm.mm line 400 in [RLMRealm realmWithConfiguration:error:]
PROJECT_NAME
RLMRealm.mm line 302 in [RLMRealm defaultRealm]
PROJECT_NAME
IVAppDelegate.m line 169 in [IVAppDelegate realmMigration]
PROJECT_NAME
IVAppDelegate.m line 74 in [IVAppDelegate application:didFinishLaunchingWithOptions:]
UIKit
[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
UIKit
[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
UIKit
[UIApplication _runWithMainScene:transitionContext:completion:]
UIKit
[UIApplication workspaceDidEndTransaction:]
FrontBoardServices
[FBSSerialQueue performAsync:]_block_invoke_2]
CoreFoundation
__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
CoreFoundation
__CFRunLoopDoBlocks
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
UIKit
[UIApplication _run]
UIKit
UIApplicationMain
PROJECT_NAME
main.m line 14 in main
libdyld.dylib
start
```

**Comment by mrackwitz** [comment]
Thanks for reporting that. Is that the version of "core" indicated in the log, which equals 0.95.0 or is this the version of `Realm.framework` / `RealmSwift.framework`. As I can recognize that there is a method `realmMigration` in the stack trace, which was invoked, are you doing a migration in this particular version of your app? What did changed in the schema?

**Comment by tariq235** [comment]
0.95.0 is the current realm.framwork in my cocoapods.

Yes I am doing migration but i highly doubt that its crashing due to client side migration. As per our analytics more than 500 users are successfully using the app without any crash and only 2 user got this crash. Its not a high priority task for us to fix this crash because we're considering this as a very rare crash but still I have reported for your consideration.

I am copying migration code -

```
- (void)realmMigration {
    RLMMigrationBlock migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {
        if (oldSchemaVersion < 3) {

        }
        IVLog(@"Migration complete.");
    };
    
    
    RLMRealmConfiguration *configuration = [RLMRealmConfiguration defaultConfiguration];
    configuration.schemaVersion = 3;
    configuration.migrationBlock = migrationBlock;
    [RLMRealmConfiguration setDefaultConfiguration:configuration];
    // now that we have set a schema version and migration block for the configuration,
    // performing the migration and opening the Realm will succeed
    [RLMRealm defaultRealm];
}
```

**Comment by mrackwitz** [comment]
Still if you have a more complete crash log or even log messages of a failed assert, which could have caused these crashes, that would be really helpful for our further investigations.

**Comment by tariq235** [comment]
I am sorry that i don't have more detail on this crash. I have got this log from one of the crash framework. Also no way to reproduce this crash as this crash occured in appstore version :(

Can you give me a little idea why i have got this crash so atleast i do some more investigation.

**Comment by mrackwitz** [comment]
From the few info in the crash log, I can't really say why this occurs, but the first entry can't be really directly related to Realm. (`TransformationMatrix.h line 86 in [WebCore::TransformationMatrix::isIdentity() const]`) Was this perhaps part of another crash or happened on another queue and accidentally smuggled it's way into what you copied over here?
Beside that I'd recommend to update to the latest release. This fixes some crashes, which looked roughly similar to this here.

**Comment by jpsim** [comment]
I agree this looks like this crash appears unrelated to Realm, but we're happy to investigate if you can provide more information @tariq235.
