### ISSUE TITLE
Crash after convert realm file by Realm browser run in Ream 0.96.2

### ISSUE THREAD

**Issue by ikeyboard** [realm/realm-cocoa#2928]
Dear Realm team,
I convert my old file by Realm browser.
I'm sure that I made my file by Objective-C, not Swift, but one property mark as optional.
*** Terminating app due to uncaught exception 'RLMException', reason: 'Migration is required for object type 'NoneObject' due to the following errors:
- Property 'word' has been made optional.'
---
Please check! Thanks!

**Comment by bdash** [comment]
Realm 0.96.2 added support for optional properties of all types. For Objective-C, properties of NSObject types (e.g., `NSString *`, `NSDate *`, `NSData *`, etc.) are optional by default. If you'd like to continue treating properties of these types as required you can implement `+requiredProperties` and return an array of the property names. See https://realm.io/news/realm-objc-swift-0.96.0/#null-support for more information on this change.

**Comment by jpsim** [comment]
@ikeyboard we're closing this issue because we haven't heard back from you in a while. Please reopen if you'd like some clarifications or have any further questions.
