### ISSUE TITLE
Not Running in ipod 

### ISSUE THREAD

**Issue by idevmehra** [realm/realm-cocoa#2930]
ld: '/Users/ABC/Documents/SVN_Projects/XYZ/SourceCode/Pods/Realm/core/librealm-ios.a(bptree-iPhoneOS-no-bitcode.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please reply as soon as possible

**Comment by jpsim** [comment]
It's likely that you ran `pod install` while you had Xcode 6 xcode-selected, which prevented CocoaPods from linking Realm to the bitcode version of core.

**Short answer:** delete your Pods directory, set Xcode 7 as the xcode-select version, and re-install your pods:

```
rm -rf Pods
sudo xcode-select -s /Applications/Xcode-7.app/Contents/Developer
pod install
```

**Longer answer:** To support both Xcode 6 and Xcode 7, Realm provides two different versions of its prebuilt core binaries (with and without bitcode) and determines which one to link into the Pod depending on which Xcode version you have xcode-selected. It's an imperfect solution (as you've experienced), but it's the best way we found to support compiling with both Xcode 6 & 7 simultaneously.

**Comment by jpsim** [comment]
@idevmehra we're closing this issue because we haven't heard back from you in a while. Please reopen if you'd like some clarifications or have any further questions.
