### ISSUE TITLE
Installation (swift 2.1)

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [realm/realm-cocoa#2931]
Hi,

Any help? I'm having truble installing the latest realm. I'm using xcode 7.1(swift 2.1).
Please see attached image.

Thanks.

<img width="880" alt="screen shot 2015-12-03 at 1 31 24 pm" src="https://cloud.githubusercontent.com/assets/5118009/11552704/69d172aa-99c2-11e5-8dd1-4f8257c58b68.png">

**Comment by rjjohnpatrickcruz** [comment]
Quick question how would I do this. 
(Step 3 in the installation)

<img width="754" alt="screen shot 2015-12-03 at 1 57 18 pm" src="https://cloud.githubusercontent.com/assets/5118009/11553042/d9b77c74-99c5-11e5-86fe-f0f561ae7ffd.png">

**Comment by mrackwitz** [comment]
From the error message, it seems like, you didn't added `Realm.framework` (and possibly `RealmSwift.framework`) to the *Embedded Binaries* pane, which you find in the *General* tab of your project, as shown below:

[![Embedded Binaries][1]][1]


For further validation, you can check the tab *Build Phases*. It should look like below:

[![Build Phases][2]][2]


  [1]: http://i.stack.imgur.com/Wsoe3.png
  [2]: http://i.stack.imgur.com/LNZis.png

**Comment by mrackwitz** [comment]
For your other question:
Go to the *Build Settings* tab instead and search for `FRAMEWORKS_SEARCH_PATH`. You will need to add there the path of the directory in your project, where you placed `RealmSwift.framework`.
That might look like below, given that I placed the framework in this example in the directory `vendor`, which lives in the project root (aka `$SRCROOT`):

![screen shot 2015-12-03 at 16 09 34](https://cloud.githubusercontent.com/assets/1389011/11564200/4cfcdcd0-99d8-11e5-821d-900c774280b8.png)
