### ISSUE TITLE
Move methods with `args:(va_list)args` to public interface

### ISSUE THREAD

**Issue by Rusik** [realm/realm-cocoa#2934]
I want to make a default realm to my model classes to write just `[Model objectsWhere:...]` instead of `[Model objectsInRealm:[Model realmForModel] where:...]` every time in my code. So i have to override `+ (RLMResults *)objectsWhere:(NSString *)predicateFormat, ... ` in my model classes but i can't do it because can't just call super for method with variable arguments, i need `+ (RLMResults *)objectsInRealm:(RLMRealm *)realm where:(NSString *)predicateFormat args:(va_list)args;` for this.

**Comment by Rusik** [comment]
Almost every class in Cocoa have this in public, for example:
```
// NSPredicate.h
+ (NSPredicate *)predicateWithFormat:(NSString *)predicateFormat argumentArray:(nullable NSArray *)arguments;
+ (NSPredicate *)predicateWithFormat:(NSString *)predicateFormat, ...;
+ (NSPredicate *)predicateWithFormat:(NSString *)predicateFormat arguments:(va_list)argList;
```
```
// NSString.h
- (instancetype)initWithFormat:(NSString *)format, ... NS_FORMAT_FUNCTION(1,2);
- (instancetype)initWithFormat:(NSString *)format arguments:(va_list)argList NS_FORMAT_FUNCTION(1,0);
```

**Comment by jpsim** [comment]
Thanks for the request, @Rusik. I think I agree with you that this is useful to add to our public interface. I'll make a PR shortly to do this.

**Comment by Rusik** [comment]
Great, thank you!
