### ISSUE TITLE
Exception when migrating a realm to use a primary key that has duplicate entries

### ISSUE THREAD

**Issue by rudywen** [realm/realm-cocoa#2935]
Is there a way to delete duplicate entries inside a migration after adding a primary key to an existing realm? 

Fatal Exception: RLMException
Primary key property 'mobilePhoneNumber' has duplicate values after migration.

    Thread : Fatal Exception: RLMException
    0  CoreFoundation                 0x18216cf48 __exceptionPreprocess
    1  libobjc.A.dylib                0x197617f80 objc_exception_throw
    2  flare                          0x1002f2cbc RLMSetErrorOrThrow(NSError*, NSError* __autoreleasing*) (RLMUtil.mm:285)
    3  flare                          0x1002e12e8 +[RLMRealm realmWithConfiguration:error:] (RLMRealm.mm:434)
    4  flare                          0x1002e056c +[RLMRealm defaultRealm] (RLMRealm.mm:306)
    5  flare                          0x1000b16c0 -[FLAppDelegate application:didFinishLaunchingWithOptions:] (FLAppDelegate.m:88)
    6  UIKit                          0x187775324 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
    7  UIKit                          0x1879a3acc -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
    8  UIKit                          0x1879a7e0c -[UIApplication _runWithMainScene:transitionContext:completion:]
    9  UIKit                          0x1879a4f50 -[UIApplication workspaceDidEndTransaction:]
    10 FrontBoardServices             0x18c2d37c4 -[FBSSerialQueue _performNext]
    11 FrontBoardServices             0x18c2d3b44 -[FBSSerialQueue _performNextFromRunLoopSource]
    12 CoreFoundation                 0x182124544 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
    13 CoreFoundation                 0x182123fd8 __CFRunLoopDoSources0
    14 CoreFoundation                 0x182121cd8 __CFRunLoopRun
    15 CoreFoundation                 0x182050ca0 CFRunLoopRunSpecific
    16 UIKit                          0x18776e1c8 -[UIApplication _run]
    17 UIKit                          0x187768ffc UIApplicationMain
    18 flare                          0x1000d4404 main (main.m:16)
    19 libdyld.dylib                  0x197e5a8b8 start

Looks similar to:
https://github.com/realm/realm-cocoa/issues/1002#event-177056320

**Comment by lata-nga** [comment]
Bump

**Comment by jpsim** [comment]
Realm doesn't enforce primary key uniqueness during the migration process, so if you're converting a property from non-primary to primary, you'll have to manage that uniqueness constraint yourself.

The easiest way to do this is to keep track of which primary keys you've seen while you enumerate over your model objects affected by the primary key migration. Then if you find another object with the same primary key, you can delete it, change its primary key, or anything else you'd like to do.

**Comment by yoshyosh** [comment]
Going to close this issue, but feel free to jump in if there needs to be any more clarification
