### ISSUE TITLE
Exception when filtering a string with non alpha numeric characters

### ISSUE THREAD

**Issue by shmidt** [realm/realm-cocoa#2936]
let realm = try! Realm()
        
        try! realm.write {
            var cat = realm.objects(Category).filter("name = '\(categoryName)'").first
            if cat == nil{
                print("Creating Category with name: \(categoryName)")
                cat = Category()
                cat?.name = categoryName
                realm.add(cat!, update: false)
            }
It causes crash: 
'Unable to parse the format string "name = '!$&'()*+,;='"'

**Comment by jpsim** [comment]
When building predicates like this, you should pass objects to query against rather than using Swift's string interpolation:

```swift
var cat = realm.objects(Category).filter("name = %@", categoryName).first
```

**Comment by shmidt** [comment]
Thanks that worked.
