### ISSUE TITLE
NSPredicate keypath collection query fails on evaluateWithObject:

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#2937]
This was originally reported in an issue with RBQFetchedResultsController: https://github.com/Roobiq/RBQFetchedResultsController/issues/50

Here is the sample project (I made a few updates to the one the user originally provided):
[RBQFetchedResultsControllerExample.zip](https://github.com/realm/realm-cocoa/files/51558/RBQFetchedResultsControllerExample.zip)

If you run the project, you will notice that the predicate (`@"inTable = YES AND objects.@count > 0"`) for the `RBQFetchRequest` works correctly and only objects in the first section appear because those are the only objects with any linked objects in their `RLMArray` objects property.

However, if you click the delete button in the nav bar and then click insert, a new object will be created with a linked object and then it is added to Realm with a notification to trigger the FRC. The FRC will then evaluate the objects that are passed through the notification to verify they match the predicate for the fetch request.

In this case the predicate evaluation fails: `[self.predicate evaluateWithObject:object]`. From what I can tell it seems that internally, this triggers calling `valueForKey:` on the object, with the key being: `@count`.

Is this an incorrect parse of the predicate or do we need to enable support for this sort of `valueForKey:` request?

**Comment by bdash** [comment]
Our array types do not yet implement the KVC collection operators. They should.

**Comment by mrackwitz** [comment]
Is this really a bug? I'd tend to say it's a missing feature / API inconsistency.
