### ISSUE TITLE
Build framework fails with Realm 0.96

### ISSUE THREAD

**Issue by ajitam** [realm/realm-cocoa#2940]
Hi,
I'm working on na project (Cocoapod package) which uses (as dependency) AFNetworking and Realm.
I then use [cocoapods-package](https://github.com/CocoaPods/cocoapods-packager) to build a framework.

Since I upgraded Realm to 0.96+ framework doesn't get build - I get this error - https://github.com/CocoaPods/cocoapods-packager/issues/105#issuecomment-151827193

If I rollback to 0.95 it works 0K.

I know is not very descriptive error but this is the best I can do. You can see that error occurs when script tries to mangle symbols.

**Comment by mrackwitz** [comment]
Could you share a project which reproduces this error with us? (Privately to help@realm.io)

**Comment by ajitam** [comment]
will do

**Comment by jpsim** [comment]
@tgoyne and @ajitam worked this out via email. Which I'll repost here, lightly edited:

Essentially @ajitam was building a framework that bundled Realm & some Realm models. So to support users of that framework also being able to use Realm without being effected by the framework's usage, the `+[RLMObject shouldIncludeInDefaultSchema]` class method on each of the framework's model classes need to be overridden to return `false`, and then explicitly list those object types in the `objectClasses`/`objectTypes` array on the configuration object used to open the Realm.

Supporting the framework user using a different version of Realm from the one you're using in the same process would be tricky. All of the obj-c class names would need to be mangled similar to how `cocoapods-packager` does (but without trying to mangle anything else), and then build the library as a dynamic framework which has Realm statically linked into it.

**Comment by ajitam** [comment]
Hi, I just wanted to update this issue. As it turns out in the end the problem was (is still is) in... xCode :)
The thing is that if I rollback Realm version to 0.95.0 it works and for 0.95.3 it doesn't - but not because of anything **in** the code. Problem is the **length** of code.

I managed to found the error: `Argument list too long`

That means that new version of Realm has increase number of methods that needs to be mangled and it is to much for xCode build process.

I confirmed that by including the 0.95.0 version and then including another POD - which produced the same error.

**Comment by mrackwitz** [comment]
Thanks for reporting back.

I would tend to say that's now primarily an issue with cocoapods-packager's naïve approach to name mangling. Maybe the aliases could be provided by an intermediate file instead of passing them all on in a build setting, which inevitable ends up being passed on the command line by xcodebuild as it seems. Alternatively you could exclude Realm from the mangling once CocoaPods/cocoapods-packager#108 is merged. Disabling it for all dependencies doesn't seem to be an option for you, I guess, given that you use AFNetworking, which has probably the biggest clash potential in that regard.

**Comment by ajitam** [comment]
Thanks for the info! Really hope for solution here :/
