### ISSUE TITLE
Cocoa app crashes 

### ISSUE THREAD

**Issue by shmidt** [realm/realm-cocoa#2942]
[RealmCrash.zip](https://github.com/realm/realm-cocoa/files/52179/RealmCrash.zip)

Realm currently crashes if I have "All Objective C" breakpoint enabled.
If I disable it, then it will crash when I'll do another queries.

Can you please take a look at the attached project (OS X, CocoaPods, Swift)?

Thanks.

**Comment by bdash** [comment]
I don't see any crash when I build and run the project you provided. Can you provide more information about the problem you're seeing?

**Comment by shmidt** [comment]
Thanks for the quick reply.

That's what I see:

libc++abi.dylib`__cxa_begin_catch:
->  0x7fff94085c36 <+0>:   pushq  %rbp
    0x7fff94085c37 <+1>:   movq   %rsp, %rbp
    0x7fff94085c3a <+4>:   pushq  %r14
    0x7fff94085c3c <+6>:   pushq  %rbx
    0x7fff94085c3d <+7>:   movq   %rdi, %r14
    0x7fff94085c40 <+10>:  movq   (%r14), %rbx
    0x7fff94085c43 <+13>:  callq  0x7fff940857ad            ; __cxa_get_globals
    0x7fff94085c48 <+18>:  leaq   -0x58(%r14), %rcx
    0x7fff94085c4c <+22>:  shrq   $0x8, %rbx
    0x7fff94085c50 <+26>:  movabsq $0x434c4e47432b2b, %rdx
    0x7fff94085c5a <+36>:  cmpq   %rdx, %rbx
    0x7fff94085c5d <+39>:  jne    0x7fff94085c88            ; <+82>
    0x7fff94085c5f <+41>:  movl   -0x28(%r14), %edx
    0x7fff94085c63 <+45>:  movl   %edx, %esi
    0x7fff94085c65 <+47>:  negl   %esi
    0x7fff94085c67 <+49>:  cmovll %edx, %esi
    0x7fff94085c6a <+52>:  incl   %esi
    0x7fff94085c6c <+54>:  movl   %esi, -0x28(%r14)
    0x7fff94085c70 <+58>:  movq   (%rax), %rdx
    0x7fff94085c73 <+61>:  cmpq   %rdx, %rcx
    0x7fff94085c76 <+64>:  je     0x7fff94085c7f            ; <+73>
    0x7fff94085c78 <+66>:  movq   %rdx, -0x30(%r14)
    0x7fff94085c7c <+70>:  movq   %rcx, (%rax)
    0x7fff94085c7f <+73>:  decl   0x8(%rax)
    0x7fff94085c82 <+76>:  movq   -0x8(%r14), %r14
    0x7fff94085c86 <+80>:  jmp    0x7fff94085c95            ; <+95>
    0x7fff94085c88 <+82>:  cmpq   $0x0, (%rax)
    0x7fff94085c8c <+86>:  jne    0x7fff94085ca5            ; <+111>
    0x7fff94085c8e <+88>:  movq   %rcx, (%rax)
    0x7fff94085c91 <+91>:  addq   $0x20, %r14
    0x7fff94085c95 <+95>:  movq   %r14, %rax
    0x7fff94085c98 <+98>:  popq   %rbx
    0x7fff94085c99 <+99>:  popq   %r14
    0x7fff94085c9b <+101>: popq   %rbp
    0x7fff94085c9c <+102>: retq   
    0x7fff94085c9d <+103>: movq   %rax, %rdi
    0x7fff94085ca0 <+106>: callq  0x7fff94086ab1            ; __cxa_call_unexpected
    0x7fff94085ca5 <+111>: callq  0x7fff940861e0            ; std::terminate()

**Comment by bdash** [comment]
Thanks for the extra information, @shmidt. `__cxa_begin_catch` is a C++ runtime routine that's called as part of handling an exception. Unfortunately by itself it doesn't provide any actionable information.

What would be most helpful would be a) the stack trace of the crash, and b) information about the exception that is thrown. The backtrace can be found in the Debug Navigator at the point of the crash. Information about the exception should be printed by the application, and will likely be found in the console area at the bottom of Xcode's window. [Xcode's documentation contains a visual guide](https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/debugging_tools.html) to these parts of the window if you're unfamiliar with them.

**Comment by shmidt** [comment]
There is only LLDB console, no output in console window.
Please see screenshot.
![screen shot 2015-12-04 at 9 22 29 am](https://cloud.githubusercontent.com/assets/1472370/11596235/b2d7c4c6-9a68-11e5-99b1-f9efff2041b4.png)

**Comment by bdash** [comment]
That exception is being thrown within `NSURLConnection`'s loading thread. I suspect it is caught by that framework and does not result in your application crashing. You can avoid breaking in the debugger for such exceptions by changing your exception breakpoint from All to Objective-C exceptions only. If you are still seeing a crash at that point, please attach a new screenshot of what you see.

It would be helpful to also disable the "Show only stack frames with debug symbols and between libraries" button at the bottom of the Debug Navigator. It's the one that's blue in your screenshot, just to the right of the Filter field. It'll provide more information in the stack trace on the left.

**Comment by shmidt** [comment]
Additional screenshot of the first thread

![screen shot 2015-12-04 at 9 28 13 am](https://cloud.githubusercontent.com/assets/1472370/11596357/71c11c66-9a69-11e5-99d6-c039f719f399.png)

**Comment by bdash** [comment]
That screenshot appears to be from when you're stopped for the same exception. The fact Realm code appears on the main thread isn't related to the exception on the `NSURLConnection` loader thread.

**Comment by shmidt** [comment]
OK, thanks you very much for your help.
Maybe that CocoaPods issue, because project with Pods doesn't have any issues.

**Comment by bdash** [comment]
Please see my earlier comment about changing your exception breakpoint to gather more information.

**Comment by shmidt** [comment]
@bdash My breakpoint was "Objective-C" from the beginning.
![screen shot 2015-12-04 at 9 35 05 am](https://cloud.githubusercontent.com/assets/1472370/11596525/57926182-9a6a-11e5-8e46-b9856763ae4c.png)

**Comment by bdash** [comment]
My mistake. Is there a problem you're seeing beyond this exception that is thrown on NSURLConnection's loader thread?

**Comment by shmidt** [comment]
Actually i have no idea about this NSURLConnection exception, because I don't use NSURLConnection at all as you see in previously attached project. 

I'll try to implement Realm without CocoaPods to see if it changes anything.

**Comment by shmidt** [comment]
I used dynamic frameworks and  it's the same crash after I added them.
![screen shot 2015-12-04 at 9 55 12 am](https://cloud.githubusercontent.com/assets/1472370/11596981/54710082-9a6d-11e5-87ef-a78a400d35b7.png)

**Comment by bdash** [comment]
What you're showing is not a crash. An exception is being thrown which is triggering a breakpoint that you've set. You can very likely continue from that breakpoint without issue.

**Comment by shmidt** [comment]
OK, thanks. I got it.
