### ISSUE TITLE
Still couldn't get dSYM via Carthage

### ISSUE THREAD

**Issue by minhoryang** [realm/realm-cocoa#2949]
#2766 Is there a reason that the pre-built Carthage.framework.zip does not contain a dSYM?
#2822 Use `carthage archive` command to create Carthage release zip
#2944 Test v0.96.3

According to those 3 updates, Installing v0.96.3 via Carthage should supply .dSYM as expected.
But still not found any .dSYM from https://github.com/realm/realm-cocoa/releases/download/v0.96.3/Carthage.framework.zip

Happened Carthage 0.11.0 and realm/realm-cocoa v0.96.3

**Comment by bdash** [comment]
The change in #2822 requires #2793 to work correctly, but as that's a large restructuring of our build system it wasn't included in v0.96.3. The fix for #2766 will take effect when #2793 is released as part of v0.97.

**Comment by minhoryang** [comment]
Oh! I got it now. Thank you!
