### ISSUE TITLE
Pod install doesn't work when i try to get Realm 0.96.3

### ISSUE THREAD

**Issue by neon0619** [realm/realm-cocoa#2950]
pod install

Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Realm 0.96.3 (was 0.96.2)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.95.4
Downloading core failed. Please try again once you have an Internet connection.

is there something i missed..? please help. Thanks in advance.

**Comment by mrkey0310** [comment]
In my case, all way had some file the project can not find, event I drag the framework in the project manually , so I still using the 0.96.2

**Comment by myloveCc** [comment]
Pod install doesn't work in my project too!

**Comment by Yoncise** [comment]
I can't neither...

**Comment by aberkunov** [comment]
For me 'pod install' works, but I'm still getting 'Cannot open an encrypted Realm with a debugger attached to the process' error message. I had a quick check and found that function `RLMIsDebuggerAttached` is not updated in 0.96.3, but it should be?..

**Comment by tgoyne** [comment]
Whoops, looks like https://github.com/realm/realm-cocoa/commit/59bc771a6c0eca29404ffc1a910c1d28dda23204 is missing from the release branch. As a temporary workaround you can just delete that check in the local copy of the Realm source fetched by cocoapods.

**Comment by jpsim** [comment]
Unfortunately we have 4 different people reporting different issues in here.

@neon0619 in your case, Realm's core binaries couldn't be downloaded, so please try again once you have an internet connection.

@mrkey0310 @myloveCc to help you, we need more information. Please read [CONTRIBUTING.md](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md) and report back.

@aberkunov your issue is fixed in our `master` branch, so you could target that if you need to debug encrypted Realms.

**Comment by neon0619** [comment]
Thanks for your response @jpsim i just installed it now.

**Comment by mrkey0310** [comment]
For my situation, when the I update realm(Objective-C) to 0.96.3, all the '.cpp' file extension change to '.hpp' , so the file that import these files could not found them.....and the realm module can not build for my swift project

**Comment by jpsim** [comment]
@mrkey0310 it looks like a CocoaPods cacheing issue. Try re-installing:

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

**Comment by mrkey0310** [comment]
It seem so! And it's working now !
