### ISSUE TITLE
Clarify that RLMArray has array and not set semantics

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-cocoa#2951]
Also document more thoroughly how to-many links behave when adding objects with primary keys / multiple times with the same primary key.

**Comment by austinzheng** [comment]
I know this is a very old issue. Do you think it's still relevant, or should I close it? If it's still relevant I'll spend a bit of time writing this up.

**Comment by jpsim** [comment]
Still relevant I suppose. Notably just adding the phrase that there can be multiple elements in the RLMArray/List that point to the same Realm object.

**Comment by jpsim** [comment]
We've updated the docs to clarify this: https://realm.io/docs/swift
