### ISSUE TITLE
Can you ditch the download buttons on your main webpage?

### ISSUE THREAD

**Issue by skydivedan** [realm/realm-cocoa#2958]
Sorry, this isn't specifically related to Swift or anything, but those three big buttons that I see on your main web-page, (Java, Swift and Objective-C I believe). Almost every time I visit your page, I click on one of those buttons, thinking it will take me to the *documentation*. Instead, I download a new copy of the code. (Yes, I realize now that there's a Documentation link at the top of your page).

The last thing I want to do is directly download Realm. I'll get it through cocoapods, or carthage.

If it's vital for these buttons to be "download" buttons, can they be labelled as such, as they are when you scroll all the way down to the bottom of the page?

**Comment by jpsim** [comment]
You bring up some great points. I've notified our web team and we'll report back here shortly.

**Comment by mrh-is** [comment]
Hi @skydivedan, thanks for the idea! We've just changed that behavior, so you can enjoy the documentation any time!

**Comment by skydivedan** [comment]
wow, awesome! thanks for listening!
