### ISSUE TITLE
Unable to Run Xcode UI Test Cases when the encryption is on

### ISSUE THREAD

**Issue by xiongemi** [realm/realm-cocoa#2959]
Does anyone know how to run ui test case when realm encryption is on?
I keeps getting the exception that "Cannot open an encrypted Realm with a debugger attached to the process".
I know I need to setup the environment variable REALM_DISABLE_ENCRYPTION, but I am not sure how to set it inside UI test cases.

Could anyone help me?

**Comment by jpsim** [comment]
Hi @xiongemi, we've removed that restriction on our `master` branch, so I encourage you to install Realm from source. I see from #2960 that you're using CocoaPods, so you can do this by setting the `:branch` argument in your `Podfile` to `master`:

```ruby
# note that you also need to specify the version of the 'Realm' pod to use
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'
```

**Comment by xiongemi** [comment]
Thanks, it works.

On Tue, Dec 8, 2015 at 1:17 PM, JP Simard <notifications@github.com> wrote:

> Hi @xiongemi <https://github.com/xiongemi>, we've removed that
> restriction on our master branch, so I encourage you to install Realm
> from source. I see from #2960
> <https://github.com/realm/realm-cocoa/issues/2960> that you're using
> CocoaPods, so you can do this by setting the :branch argument in your
> Podfile to master:
>
> # note that you also need to specify the version of the 'Realm' pod to use
> pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'
> pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/2959#issuecomment-162967234>.
>



-- 
Emily Xiong
