### ISSUE TITLE
"sorted" method crash if array is empty.

### ISSUE THREAD

**Issue by velthune** [realm/realm-cocoa#2967]
I've developed by myself a wrapper for DAO access :

    static func retrieveAll(inClass: Object.Type, sortedBy property: String, ascending: Bool = true) -> Results<Object>? {
        if let results = RealmDAO.retrieveAll(inClass) {
            return results.sorted(property, ascending: ascending)
        }
        return nil
    }

So, crash when "results" is empty.

Now I fixed adding an "if" block before "return":

     if results.isEmpty {
         return results
     }

**Comment by bdash** [comment]
Hi @velthune! I wasn't able to reproduce a crash when sorting an empty `Results` object. Can you please provide some information about the crash you're seeing, along with information about what version of Realm you're using? See [CONTRIBUTING.md](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) for a list of information that will make it easier for us to help you.

**Comment by velthune** [comment]
It' my fault, I found problem in another code position
