### ISSUE TITLE
A signed resource has been added, modified, or deleted"

### ISSUE THREAD

**Issue by dannycohn** [realm/realm-cocoa#2968]

**Comment by bdash** [comment]
@dannycohn, can you please provide any information at all about what problem you're seeing, what you were trying to do when you saw it, and with which version of Realm you saw it?

**Comment by dannycohn** [comment]
Sorry, I thought I stopped and closed the tab, didn't mean to submit the issue. I figured it out.

**Comment by dannycohn** [comment]
Dec  9 08:19:48 iPhone itunesstored[86] <Error>: 0x218b000 __MobileInstallationInstallForLaunchServices_block_invoke240: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.s8jTQN/extracted/Payload/Connect-Order-652.app/Frameworks/Realm.framework identifier = io.Realm.Realm type = Framework> : 0xe8008017 (Signed resources have been added, removed, or modified)" UserInfo=0x16627af0 {LibMISErrorNumber=-402620393, LegacyErrorString=ApplicationVerificationFailed, FunctionName=-[MICodeSigningVerifier performValidationWithError:], NSLocalizedDescription=Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.s8jTQN/extracted/Payload/Connect-Order-652.app/Frameworks/Realm.framework identifier = io.Realm.Realm type = Framework> : 0xe8008017 (Signed resources have been added, removed, or modified), SourceFileLine=192}

**Comment by jpsim** [comment]
An explanation of what's happening here would go a long way in helping us understand what's happening, @dannycohn.

For example, what version of Realm/iOS/Xcode is this error happening on?

The log you've shared seems to be from an iOS device, how did you install your app on that device (TestFlight, HockeyApp, Xcode, App Store, enterprise certificate, etc)?

How did you install Realm in your app (CocoaPods, Carthage, prebuilt binaries, from source, with/without bitcode)?

**Comment by dannycohn** [comment]
Ya sorry, I meant to come back and put in more info.

We're currently on 0.96.2, have been using Realm since May. In the past, to upgrade to new releases, all I've done is copy the Realm.framework and RealmSwift.framework files over the old ones in Finder. We've never done anything in XCode for an upgrade, because we're just replacing the entire framework. I followed the same process this time around.

The log I shared occurred when I tried to run from XCode to a physical device. The same does not occur when I run to a simulator. 

We also have our CI server sign with an enterprise cert so we can do an OTA install. Those builds are giving the same error.

I did a hard reset on one device and while it didn't fix the issue immediately, suddenly it started working. I haven't done hard resets on the other devices because I'm not convinced that it fixed it, and there's a lot of stuff on the test devices that I don't want to have to restore.

In terms of how it was installed, it was just by dragging in the prebuilt binaries. We're not enabling bitcode because we're using a separate library that hasn't enabled it yet. I hope that's enough, let me know if you need more info

**Comment by jpsim** [comment]
And what version of Xcode are you using? Make sure you're dragging the right one (we have a folder for Swift 1.2 and another for Swift 2.1).

**Comment by dannycohn** [comment]
This occurs with XCode 7.1.1 and 7.2. We're using the Swift 2.1 frameworks

**Comment by bdash** [comment]
Can you run `codesign -vvvv App.app` on the built copy of your application that is generating the failure when you attempt to run it on a device? That should give more detailed information about what is wrong with the signature.

**Comment by dannycohn** [comment]
Dannys-MBP-2:Debug-iphoneos dannycohn$ codesign -vvvv App.app
App.app: valid on disk
App.app: satisfies its Designated Requirement

**Comment by dannycohn** [comment]
App.app: valid on disk
App.app: satisfies its Designated Requirement

**Comment by bdash** [comment]
The prebuilt binary releases of the Realm frameworks are not code signed. They're typically signed by the Realm user's build process as part of embedding the frameworks in the application bundle. The error you're seeing indicates Realm.framwork's contents were modified at some point after it was signed during your build.

You may want to try running `codesign -vvvv` directly on the copy of Realm.framework that is mentioned in the error message, rather than on the application that contains it.

**Comment by dannycohn** [comment]
codesign -vvvv Realm.framework/
Realm.framework/: a sealed resource is missing or invalid
file missing: /Users/.../Realm.framework/A0807789-8D56-39AA-ABA8-6BE6DFDAA509.bcsymbolmap
file missing: /Users/.../Realm.framework/2A026F7D-3D77-3C58-8E35-2CBCDDFAA7B1.bcsymbolmap

**Comment by dannycohn** [comment]
In strip-frameworks.sh it deletes the bcsymbolmap files unless the $ACTION is "install". When I click run in XCode to run on a device, $ACTION is "build".  Any thoughts?

**Comment by dannycohn** [comment]
An additional, and probably important, note: this issue only occurs on iOS 8. With iOS 9, even though the same situation occurs where the CodeSignature file lists the bcsymbolmap files despite the fact that they've been deleted, the installation goes fine.

**Comment by bdash** [comment]
Thanks for that extra detail. From what you've described it looks like there is a bug in strip-frameworks.sh. It removes the .bcsymbolmap files after it has re-signed the framework, invalidating the new signature.

**Comment by bdash** [comment]
Tagging as a P1 since this breaks code signatures of the frameworks when following the installation instructions for prebuilt binaries.

**Comment by dannycohn** [comment]
I'm happy to help test a proposed fix if needed

**Comment by kishikawakatsumi** [comment]
@dannycohn Could you please verify the fix of bug by https://github.com/realm/realm-cocoa/pull/3012 ?
Edit `strip-frameworks.sh` in the Realm.framework in your project like the following:
Move copying bcsymbolmap files section to before the code signing section.

Thanks for your patience.

**Comment by dannycohn** [comment]
Yes it fixed it. I was able to use 0.97.0
