### ISSUE TITLE
Use of unresolved identifier 'Realm'

### ISSUE THREAD

**Issue by alearcy** [realm/realm-cocoa#2969]
Hi guys, I'm trying to install Realm 0.96.3 on a new project with CocoaPod version 0.39 on a Swift 2.1 machine with Xcode 7.1.1. 
I tried to clean the build cache, I tried to create from scratch a new project but "Use of unresolved identifier 'Realm'" error appears in "let realm = try! Realm()" line code.
I also tried to install Realm as dynamic frameworks, but the error is the same...
What can I do?
Thanks!

**Comment by jpsim** [comment]
Usually, these issues are resolved by cleaning the CocoaPods cache like so:

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

I know you've already done this, but could you please try again? We also have a pending issue that's proving difficult to fix that prevents Realm from being installed on the first attempt with CocoaPods: #2701, so maybe try running `pod install` twice?

**Comment by alearcy** [comment]
I only cleaned Xcode build cache, not cocoapod cache. I'll try what you suggest me, thanks ;-)

**Comment by alearcy** [comment]
It works, thanks ;-I
