### ISSUE TITLE
Not able to compile with Xcode 7.2 using CocoaPods

### ISSUE THREAD

**Issue by hyouuu** [realm/realm-cocoa#2972]
Seems lots of duplicated declarations - see attached screenshot
![screen shot 2015-12-09 at 1 40 01 pm](https://cloud.githubusercontent.com/assets/5061867/11699695/7ae042d0-9e7a-11e5-89ac-7db300533441.png)

**Comment by jpsim** [comment]
@hyouuu please follow our guidelines for filing issues at https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md and report back here with further information. Posting a screenshot of Xcode isn't enough for us to help you resolve your issue.

**Comment by hyouuu** [comment]
```
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42

/Applications/Xcode.app/Contents/Developer
Xcode 7.2
Build version 7C68

/usr/local/bin/pod
0.39.0
Realm (0.96.3)
RealmSwift (0.96.3)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)


(not in use here)

/opt/facebook/bin/git
git version 1.9.5
```

**Comment by hyouuu** [comment]
Goals: Compile
Expected results: Compile
Actual results: Doesn't compile
Steps to reproduce: Compile

Podfile:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.2'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

link_with 'ProjectName'

pod 'RealmSwift'

**Comment by hyouuu** [comment]
Oops - turns out to be caused by Dropbox - they created some snapshot copies on a certain date (probably some syncing failure) in the Pods dir, which caused the compiler to complain. Weird thing is it happened right after upgrading to Xcode 7.2 - probably previously Xcode has been using some compiled cache so it didn't trigger
