### ISSUE TITLE
Warning: 0.96.3 Implicit conversion loses integer precision

### ISSUE THREAD

**Issue by waveyus** [realm/realm-cocoa#2973]
/Pods/Realm/include/realm/column_link.hpp:175:20: Implicit conversion loses integer precision: 'long long' to 'size_t' (aka 'unsigned long')

inline void LinkColumn::do_swap_link(size_t row_ndx, size_t target_row_ndx_1,
                                     size_t target_row_ndx_2)
{
    // Row pos is offset by one, to allow null refs
    ++target_row_ndx_1;
    ++target_row_ndx_2;

   size_t value = LinkColumnBase::get(row_ndx);   // This is the line triggers warining 
    if (value == target_row_ndx_1) {
        LinkColumnBase::set(row_ndx, target_row_ndx_2);
    }
    else if (value == target_row_ndx_2) {
        LinkColumnBase::set(row_ndx, target_row_ndx_1);
    }
}

**Comment by jpsim** [comment]
We're aware of this warning, you should know that it is harmless. This should be fixed in our next major release.

**Comment by waveyus** [comment]
Thanks!
