### ISSUE TITLE
Realm creation fails at custom path

### ISSUE THREAD

**Issue by exsortis** [realm/realm-cocoa#2975]
I'm trying to create a Realm like so:

```
 let dataConfig = Realm.Configuration(path: "\(sharedContainerPath)\(dataId).characterData",
                schemaVersion: RPGCharacterDataSchemaVersion)
var realm : Realm!
do {
  realm = try Realm(configuration: dataConfig)
}
catch {
...
}
```

The Realm instantiation fails by throwing an error:

```
Error Domain=io.realm Code=2 "open() failed: No such file or directory" UserInfo={NSFilePath=file:///Users/pauly/Library/Developer/CoreSimulator/Devices/2B156935-C765-40F7-9C0E-07B24BAB14BA/data/Containers/Data/Application/7C7524DE-832F-428A-BD20-022DEA2AB1A8/Documents/61667DFC-3AA7-4661-BD83-49810F13CE8A.characterData.lock, NSLocalizedDescription=open() failed: No such file or directory, Error Code=2}
```  

Am I reading the documentation incorrectly on how to create a new Realm at a custom path?

**Comment by mrackwitz** [comment]
This error occurs, if the directory component of the provided path doesn't exist. The file itself would be automatically created as you expect. So how do you compose the `sharedContainerPath` and are you sure that directory `Documents` really exists at this point?

**Comment by exsortis** [comment]
The destination directories exist. They are guaranteed to in the Apple documentation, both for an app's documents directory and for a shared app group container.

But I figured it out. 

In reading your response, however, I had a hunch that there was something wrong with the path. `sharedContainerPath` is a String that is created from calling `absoluteString` on an NSURL. Instead I should have been calling `path`. It works now.

Sorry for the trouble.

**Comment by mrackwitz** [comment]
Thanks for reporting back after you figured out what was going on. :+1:
