### ISSUE TITLE
SwiftPerformanceTests.testQueryConstruction fails since core 0.95.4 on 32-bit

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2978]
Usually at around ~80% slower. This only seems to happen on host 1 (32-bit iPhone 5 running iOS 8).

* https://ci.realm.io/job/objc_pr/configuration=Release,swift_version=2.1,target=ios-device-swift/2543/
* https://ci.realm.io/job/objc_pr/configuration=Release,swift_version=2.1,target=ios-device-swift/2538/
* https://ci.realm.io/job/objc_pr/configuration=Release,swift_version=2.1,target=ios-device-swift/2537/
* https://ci.realm.io/job/objc_pr/configuration=Release,swift_version=2.1,target=ios-device-swift/2536/
* https://ci.realm.io/job/objc_pr/configuration=Release,swift_version=2.1,target=ios-device-swift/2534/

See https://ci.realm.io/job/objc_pr/configuration=Release,swift_version=2.1,target=ios-device-swift/2543/testReport/junit/RealmSwift_Tests/SwiftPerformanceTests/testQueryConstruction/history/ for a history of this failing test.

I think this first started happening after we updated core from 0.95.1 to 0.95.4 (#2943). There were a few failures before then but only in the tvOS branch which was using a more recent build of core for a while.

Seems to me like the most likely culprit is https://github.com/realm/realm-core/pull/1363, which had the biggest impact on query code.

Thoughts @bdash?

**Comment by bdash** [comment]
The test in question looks like:
```swift
func testQueryConstruction() {
    let realm = realmWithTestPath()
    let predicate = "boolCol = false and (intCol = 5 or floatCol = 1.0) and objectCol = nil and doubleCol != 7.0 " +
                    " and stringCol IN {'a', 'b', 'c'}"

    measureBlock {
        for _ in 0..<500 {
            _ = realm.objects(SwiftObject).filter(predicate)
        }
    }
}
```

It's purely measuring the construction of the `Results` objects and query without ever executing the query. I can look into this tomorrow to see why this has regressed.

**Comment by bdash** [comment]
Nothing changed in core's query construction code between 0.95.0 and 0.95.4 that I see. There was a recent change in the Cocoa binding in this area though: #2895.

**Comment by jpsim** [comment]
Based on when the failures have happened, it seems to be entirely tied to using core 0.95.2+.

**Comment by bdash** [comment]
There are no changes at all in core query code between 0.95.2 and 0.95.5.

**Comment by jpsim** [comment]
It's hard to say exactly what this is attributable to. Here's some data to correlate with:

Recent PRs where this test succeeded:

#2842
#2938
#2721
#2943
#2944
#2946

Recent PRs where this test failed:

#2721
#2946
#2954

**Comment by bdash** [comment]
I was able to reproduce a performance difference on this test between current master and master from ~1 month ago on OS X by tweaking the test to run its loop for a larger number of iterations. `git bisect` then narrowed it down to a change made to [make SwiftLint happy with the tests](https://github.com/realm/realm-cocoa/commit/2a2ae542d531a4fe6da132e8dbfdb22710989d7f#diff-a4b76208d090e7af6159cf526eb13691L250). The work of `NSPredicate` parsing the format string was moved into the test, but the test wasn't rebaselined. The parsing is surprisingly expensive, taking almost as long as it takes for us to build up the query from the resulting predicate. I'm going to put up a pull request that pulls the construction of the `NSPredicate` out of the benchmark loop and see if that takes care of the regression on the iOS CI device.

**Comment by astigsen** [comment]
> The parsing is surprisingly expensive, taking almost as long as it takes for us to build up the query from the resulting predicate.

It could be interesting to see if our own parser is faster?

**Comment by bdash** [comment]
It could very easily be faster since we can likely avoid allocating the Objective-C data structures that `NSPredicate` is required to expose via its API. I don't think that's a very interesting case though. The parsing performed by `NSPredicate` is fast in an absolute sense, and is only expensive relative to the very small amount of work that each iteration of the benchmark is doing (only constructing a query, and never executing it). My change also shows that it's currently very easy to pull that work out of any hot loops, which is an ability we'd likely want to preserve if we introduced our own parsing / query format.
