### ISSUE TITLE
Carthage not creating RealmSwift.framework when using --no-use-binaries

### ISSUE THREAD

**Issue by poolqf** [realm/realm-cocoa#2987]
Hi!

I am using Realm in an app through carthage. Since https://github.com/realm/realm-cocoa/pull/2793, I understood that native Carthage building was possible, but it is not working as expected.
The command I run is `carthage update --platform iOS --no-use-binaries`, and it is not creating the RealmSwift.framework

The reason that I want to use the native carthage building instead of your provided pre-compiled framework is to avoid the DWARFs route problem.

Is there any way of achieving it with Carthage? Or now the only way to do it is by building the frameworks manually?

Thanks!

Related with:
- https://github.com/Carthage/Carthage/issues/924
- https://github.com/realm/realm-cocoa/pull/2793

**Comment by bdash** [comment]
#2793 is present on master, but not yet in any releases. Are you explicitly telling Carthage to use the master branch in your Cartfile? If not, Carthage will download from a release tag which does not yet have that change.

**Comment by poolqf** [comment]
But the release [`v0.96.3`](https://github.com/realm/realm-cocoa/releases/tag/v0.96.3) was released 7 days ago, and #2793 was merged on Nov 7.

**Comment by bdash** [comment]
v0.96.3 was released based on a branch, not from master. If you take a look at https://github.com/realm/realm-cocoa/tree/v0.96.3 you can see that RealmSwift.xcodeproj exists.

**Comment by poolqf** [comment]
Sorry, my fault! Waiting for that release then 👍
