### ISSUE TITLE
How to implement ignoredProperties in realm-cocoa using Swift?

### ISSUE THREAD

**Issue by evgeny-sureev** [realm/realm-cocoa#2991]
Following code
```
override class func ignoredProperties() -> NSArray? {
    return ["coordinate"]
}
```
produces error "Method does not override any method from its superclass".

I am using Realm for Objective-C installed from cocoapods.

**Comment by bdash** [comment]
The in the Objective-C interface, `+ignoredProperties` is declared like so:

```objc
+ (nullable NSArray *)ignoredProperties;
```

That is bridged to Swift as:
```swift
public class func ignoredProperties() -> [AnyObject]?
```

If you update the return type of your method you should have better luck.

**Comment by evgeny-sureev** [comment]
Thank you, it works!
