### ISSUE TITLE
Crash in unit tests using Realm

### ISSUE THREAD

**Issue by vincedev** [realm/realm-cocoa#2993]
Here is the setup for our unit tests :

```
- (void)setUp {
	[super setUp];
    RLMRealmConfiguration *configuration = [RLMRealmConfiguration defaultConfiguration];
    NSString *path =  [NSString stringWithFormat:@"%@/.test", [[[NSFileManager defaultManager] defaultAppURL] path]];
    [configuration setPath:path];
    [RLMRealmConfiguration setDefaultConfiguration:configuration];
	[self resetData];
}

- (void)tearDown {
	[super tearDown];
	[self resetData];
}

- (void)resetData {
	[[NSUserDefaults standardUserDefaults] resetUserDefaults];
	RLMDeleteRealmFilesAtPath([RLMRealmConfiguration defaultConfiguration].path);
}
```

This leads to crashes while unit testing in Xcode. 
Seems Xcode plays tests in parallel, can it be that setup and tear down causes the crash ?

Here's a screenshot of where it crashes.
![screen shot 2015-12-14 at 13 16 22](https://cloud.githubusercontent.com/assets/5918528/11780813/0f6654d8-a265-11e5-908a-4c84988c950c.png)

**Comment by jpsim** [comment]
Looks like you might still be accessing Realms while you attempt to delete the file from under it!

Please see the "Testing" section of our docs: https://realm.io/docs/objc/latest/#testing

and Realm's own unit tests to see how to force precise Realm lifespans by using autoreleasepools: https://github.com/realm/realm-cocoa/blob/master/Realm/Tests/RLMTestCase.m

**Comment by vincedev** [comment]
@jpsim Seems you were right.  
We have finally made our tests run fine, and the issue wasn't on Realm side, we were indeed trying to write to Realm, while changing the file from under it.

Thank you for your time and help.
