### ISSUE TITLE
Swift Array Migration

### ISSUE THREAD

**Issue by gevariya-ajit** [realm/realm-cocoa#2994]
I have added new array attribute to the RLMObject and

public class Student: RLMObject {
    dynamic var id = 0
    dynamic var name = ""
    dynamic var resultList = RLMArray(objectClassName:Result.className())
}

public class Result: RLMObject {
}

ERROR Log:
Migration is required for object type 'Student' due to the following errors: - Property 'resultList' has been added to latest object model.

TRY Failed:
let configuration:RLMRealmConfiguration = RLMRealmConfiguration.defaultConfiguration()
...
migration.enumerateObjects(Student.className()) { oldObject, newObject in
    newObject!["resultList"] = RLMArray(objectClassName: Result.className())
}

**Comment by jpsim** [comment]
That exception is thrown because you need to update the schema versions of the Realms using this model.

Also, the `resultList` property will be initialized to an empty list, so you don't need the `newObject!["resultList"] = RLMArray(objectClassName: Result.className())` code in your migration.
