### ISSUE TITLE
Example on batchUpdates with write transactions

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#2997]
A few people are doing things like loops with writeTransactions in them rather than outside the loop. Another common scenario is changing the read bool on things like emails/messages so an example could help here

**Comment by jpsim** [comment]
In the first paragraph of the [Writes section of our docs](https://realm.io/docs/objc/latest/#writes), we write:

> Since write transactions incur non-negligible overhead, you should architect your code to minimize the number of write transactions.

**Comment by yoshyosh** [comment]
:+1:
