### ISSUE TITLE
when I delete one object ,it can't auto delete this object's subObject

### ISSUE THREAD

**Issue by FengDeng** [realm/realm-cocoa#3000]
I think every object in realm must have a retaincount. when two object have same sub object,this sub object's retainCount is 2. I delete one object,retaincount change to 1, I delete another object,retaincount is 0,and then this sub object auto delete. 
I can't get realm core code.it's so sad.

**Comment by jpsim** [comment]
If I'm understanding you correctly, I think you're asking for us to implement cascading deletes behavior, we're tracking that feature as #1186. I'm closing this one as a duplicate. If I'm misunderstanding you, please feel free to reopen this ticket with more information.
