### ISSUE TITLE
readOnly causes empty result

### ISSUE THREAD

**Issue by Godlex** [realm/realm-cocoa#3014]
Hey guys, 

I have a litte problem with setting readOnly to true in the configuration. I am using Swift 
but I am using the normal Realm.framework ...Maybe this causes the error but I don't think so. 

I tried this: 
```swift
  if let path = NSBundle.mainBundle().pathForResource("database", ofType: "realm")
        {
            //Alternative:  or move the file from the app bundle into a writable location
            var config = RLMRealmConfiguration()
            config.path = path
            config.readOnly = true
                       
            do {
                try self.realm = RLMRealm(configuration:config)
            } catch {
                    print("ERROR")
                }
```
I also tried this: 

```swift
  if let path = NSBundle.mainBundle().pathForResource("database", ofType: "realm")
        {
            //Alternative:  or move the file from the app bundle into a writable location
            var config = RLMRealmConfiguration()
            config.path = path
            config.readOnly = true
            
            RLMRealmConfiguration.setDefaultConfiguration(config)
           
            do {
                try self.realm = RLMRealm(configuration: RLMRealmConfiguration.defaultConfiguration())
            } catch {
                    print("ERROR")
                }
```
Both of them fail every time. (Printing: "Error") I figured out that the problem is that readOnly is set to true. I got both snippets working by setting readOnly to false. 
Do you have any idea how to fix this issue?

**Comment by jpsim** [comment]
Instead of printing "ERROR", it would be very useful if you printed the actual error:

```swift
do {
    try self.realm = RLMRealm(configuration:config)
} catch {
    print(error)
}
```

**Comment by Godlex** [comment]
Oh, I forgot. (Sorry, that was stupid...) I changed some names in the error message. 

This is what I get: 

Error Domain=io.realm Code=2 "Unable to open a realm at path '/Users/UserName/Library/Developer/CoreSimulator/Devices/NR/data/Containers/Bundle/Application/NR/AppName.app/database.realm'" UserInfo={NSFilePath=/Users/UserName/Library/Developer/CoreSimulator/Devices/NR/data/Containers/Bundle/Application/NR/AppName.app/database.realm, NSLocalizedDescription=Unable to open a realm at path '/Users/UserName/Library/Developer/CoreSimulator/Devices/NR/data/Containers/Bundle/Application/NR/AppName.app/database.realm', Error Code=2}

**Comment by jpsim** [comment]
That error means that there was a low level I/O related exception when opening the file at the path you provided. What's puzzling to me is that you're saying that setting `readOnly` to `false` makes this work.

We have some [examples](https://github.com/realm/realm-cocoa/tree/master/examples/tvos/objc/PreloadedData) in our repo that use bundled read-only Realms with no issue. Could you please share a sample project that reproduces the error you're getting?

**Comment by Godlex** [comment]
Yes this is what confused me as well. 
After setting up a test project it worked well with your realm database and I 
added my database with my dao to test it and surprise it worked. 

I took a closer look at the structure but I couldn't find any difference. 
I did the same thing I tried a few times and removed the database completely, 
added it again and tested it. And surprise it worked. 

I have no idea what happened but it works again. 
So, thank you very much :)

**Comment by nishiyamaosamu** [comment]
I got this problem after update realm version. I resolved it to re-create mydatabase.realm file on realm of new version.

**Comment by tbondwilkinson** [comment]
I also ran into this problem recently -- the only fix as nishiyamaosamu mentioned is to completely rebuild the static realm file with a newer version of Realm.  I'm not sure which change version of Realm exactly was the breaking one.
