### ISSUE TITLE
0.97 minimum deployment target iOS 9?

### ISSUE THREAD

**Issue by bryan1anderson** [realm/realm-cocoa#3016]
I updated my CocoaPods today, which installed Realm version 0.97

The next time I compiled I got this error
`Module file's minimum target is ios9.0 v9.0` at the import statement of `import RealmSwift`

I checked and my base SDK is set to 9.2, and my deployment target is 8.0, as always.

What changed? It was my understanding that Swift 2 was backwards compatible with iOS 8

Project info:
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50
Xcode 7.2
Build version 7C68
0.39.0
Realm (0.97.0)
RealmSwift (0.97.0)
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
git version 2.5.4 (Apple Git-61)

**Comment by jpsim** [comment]
We haven't changed our deployment target in the Realm podspec, it's still `7.0` for iOS: https://github.com/realm/realm-cocoa/blob/v0.97.0/Realm.podspec#L52-L66

**Comment by jpsim** [comment]
And for Realm Swift: https://github.com/realm/realm-cocoa/blob/v0.97.0/RealmSwift.podspec#L27-L30

Could you please share more information about your project/environment as outlined in our [issue filing guidelines](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues)? Thanks!

**Comment by bryan1anderson** [comment]
Project info:
ProductName: Mac OS X
ProductVersion: 10.11.2
BuildVersion: 15C50
Xcode 7.2
Build version 7C68
0.39.0
Realm (0.97.0)
RealmSwift (0.97.0)
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
git version 2.5.4 (Apple Git-61)

**Comment by jpsim** [comment]
Are you specifying the iOS version in your Podfile?

```ruby
platform :ios, '8.0'
```

See [CocoaPods Podfile Guide](https://guides.cocoapods.org/using/the-podfile.html) for more information.

**Comment by bryan1anderson** [comment]
yes this way: platform :ios, '8.0'

**Comment by jpsim** [comment]
Did you delete your derived data before rebuilding? Is there more information in the build log? What's printed when you run `pod install`?

**Comment by bryan1anderson** [comment]
Since my original post I have deleted RealmSwift in the pod file, ran pod update, uninstalled pods, deleted derived data, reinstalled RealmSwift pod, deleted derived data, built same error

**Comment by jpsim** [comment]
Can you share your project or a different project that reproduces the error? Or steps that we can take to reliably trigger this?

We have examples in this repo that we use for continuous testing that have an iOS deployment target of `7.0` that indicate that this is working for us:

* iOS 7: https://github.com/realm/realm-cocoa/blob/v0.97.0/examples/ios/objc/RealmExamples.xcodeproj/project.pbxproj#L1555
* iOS 8.3: https://github.com/realm/realm-cocoa/blob/v0.97.0/examples/installation/ios/swift-1.2/CocoaPodsExample/CocoaPodsExample.xcodeproj/project.pbxproj#L425

Could you try building any of these examples to see if you still get the same error? If so, I suspect there's something wrong with your installation of CocoaPods. If not, then something's wrong with your project's configuration.

**Comment by jpsim** [comment]
@bryan1anderson we never heard back from you on this, so I'm closing this issue. If you're still having problems after trying the suggestions from my latest comment, please reopen this issue and we'll take it from there.

**Comment by tiagoMaua** [comment]
i'm get same erro with Realm 0.98.8.

iOS Simulator 8.1
Swift 2.2
Pod Version 0.39

**Comment by bryan1anderson** [comment]
I still have the same issue. I blew everything away on my machine. Removed
Xcode, ruby, cocoapods, and 100% fixed the project settings..

It fixed the issues where my project wouldn't compile but that warning is
thrown every single pod update/install

**Comment by jpsim** [comment]
@bryan1anderson can you please open a new issue sharing a project and steps that reproduce your problem?

**Comment by bryan1anderson** [comment]
@jpsim Yes I will try to find time to allocate. Working for launch next week and as I've solved the compile issues its not so so pressing. Thanks
