### ISSUE TITLE
RLMResults behaviour differs between Simulator and Device

### ISSUE THREAD

**Issue by haitham-reda** [realm/realm-cocoa#3021]
Hello,

I've came across a strange issue that i have no explanation to, i have RLMResults that is used  across multiple views, it's behaviour is different from simulator to device, it "auto-updates" results in simulator meanwhile it doesn't on real device.

so the scenario is:
- on 1st tab i filter objects based on a flag
- then i go to second tab, favourite an object to enable flag
- i go back to the 1st tab, it's is updated on simulator meanwhile it isn't on the device.

appreciate explanation.
Thanks.

**Comment by mrackwitz** [comment]
The behavior should be the same (auto-updating on simulator and actual device), while the perceived behavior can differ by threads being still blocked by other activity, if something like that should be able to happen. You can also subscribe to write notifications to act on updates, what could help, depending on what you're trying to achieve. It would be helpful, if you could provide a simple example app, which reproduces the issue.

**Comment by haitham-reda** [comment]
hi @mrackwitz , sorry for the late reply.
to better describe the issue i have, lets assume we have entity `movie` which is `RLMObject` subclass, what i have here is 2 tabs application, at the 1st tab is displayed `favourite` movies, which is like:
|--View <---> ViewModel.RLMResults --| 
`RLMResults` here is objects in realm with `favorite = true`

then in the 2nd tab it's a list of all movies weather `favorite = true` or not, so whenever i favorite item from the list ( 2nd tab ), when i go back to the 1st back the newly favorite item is there without reloading ( on simulator ) meanwhile it doesn't appear on the device.

`UITableViewDatasource` methods are getting data from viewModel, e.g : 
```
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{
    return [self.viewModel numberOfItemsInSection:section];
}
```

Thank you.

**Comment by mrackwitz** [comment]
What is this `viewModel` exactly made of? Are you using a reactive framework? Can you show us the code in there? Would you be able to share a project with us privately to help@realm.io?

**Comment by haitham-reda** [comment]
hey @mrackwitz ,
the `viewModel` here is an `RVVM` subclass, `reactivecocoa`.
the issue was strange, that behaviour was on iOS simulator 8.2, but when i tried with 9.x simulator it behaves exactly like the device, so the only explanation i can think about now that simulator version 8.2 was reloading `tableView` at some point, most probably `-viewDidAppear`.
All good from my end now , thanks for your replies.

**Comment by mrackwitz** [comment]
Oh, okay, so different framework versions. Good that you were able to figure that out and thanks for reporting back on that. :+1:
