### ISSUE TITLE
SIGABRT in [RLMRealm transactionWithBlock] in 0.96.3

### ISSUE THREAD

**Issue by JonFBit** [realm/realm-cocoa#3024]
I haven't seen this in development, but after releasing our latest app update using Realm 0.96.3, I've received a lot of crash reports that appear to be pointing to realm::util::Mutex::lock_failed(int) from transactionWithBlock.

I'm performing writes on the default Realm. For example:

    RLMRealm *safeRealm = [RLMRealm defaultRealm];
    [safeRealm transactionWithBlock:^{
        [FBit_CampaignObject createOrUpdateInRealm:safeRealm withValue:campaign];
    }];

A lot of the time the writes succeed and everything seems to work fine, but they sometimes fail with SIGABRT from com.apple.root.background-qos.

This is happening on iOS 8 & 9, and appears to have started after we moved to Realm 0.96.3. 

Crashlytics info on this issue: http://crashes.to/s/42abc60f2f1

**Comment by tgoyne** [comment]
The main thread's callstack is in `__cxa_finalize_ranges()` and `exit()`, so the crash is happening while the app is in the process of shutting down. The actual crash happens when trying to lock a mutex that's stored in a global variable, which makes sense as the destructor will have run already. Crashlytics says that it happens while the app is in the background, so it probably means that either your background stuff handler function is timing out, or you're calling the completion handler while there's actually still work happening on the background thread.

On an unrelated note, the callstacks also indicate that you have code coverage generation enabled for your release build, which will bloat your binary and hurt performance a bit.

**Comment by JonFBit** [comment]
Thanks for the help, and an extra thank-you for catching that build config issue! 

I'll keep looking into the problem, but I'm having no luck reproducing the issue myself. I found what looks like a good possible cause when I started following up on your suggestion about the completion handler, so I'll get a fix for that implemented and keep an eye on the crash logs going forward.

**Comment by jpsim** [comment]
Hi @JonFBit, I'm just checking in to see if you've made any progress in either reproducing or working around this bug? In your last comment, you mentioned that you had a potential fix in the works, how did that pan out?

Looking at the recent Crashlyitcs reports, it doesn't look like this issue has died down at all in the last month :disappointed:.

Please keep us posted!

**Comment by JonFBit** [comment]
Thanks for checking in @jpsim! 

I haven't been able to reproduce the issue in testing & development,  which makes it tricky to say if there's been any progress or not. 

I've got an app update currently waiting for Apple review that fixes some version-pinning and related issues that I identified in how we were interacting with Realm, as well as gets rid of a long-lived Realm reference that we really didn't need. My hope is that once that goes out to our users there will be a drop-off in Crashlytics reports coming in.

**Comment by jpsim** [comment]
Thanks for following up! Ping us again once the new version is out so we can see if it's had an impact on this crash in the wild.

**Comment by JonFBit** [comment]
Good news! It looks like the fixes I put into the latest version of our app have almost completely resolved this issue. We've had one occurrence that I'm going to investigate on the new version, but that's it. We don't have 100% of our users on the new version yet, but the Crashlytics report is looking pretty promising: http://crashes.to/s/42abc60f2f1

**Comment by jpsim** [comment]
That's great news @JonFBit! Keep us posted if you find out anything about that one assertion hit with the new version.

**Comment by jpsim** [comment]
Hi @JonFBit, any news if your latest version(s) still hit that assertion failure?

**Comment by JonFBit** [comment]
Rock solid on the latest release :)

**Comment by jpsim** [comment]
Great to hear. Let's close this then.
