### ISSUE TITLE
How to check the class of RLMObject descendants?

### ISSUE THREAD

**Issue by yuldong** [realm/realm-cocoa#3025]
`CashPayInput` is a subclass of `RLMObject`.
After creating an instance `cashPayInput` of `CashPayInput`, I use 
```objective-c
BOOL valid = [cashPayInput isMemberOfClass:[CashPayInput class]]`
```
It returns `NO` / `valid` equals `NO`.
On the console, I can see that the `cashPayInput`'s real class is `RLMStandalone_CashPayInput`.
So how can I check whether the instance is a member of a given class?

**Comment by mrackwitz** [comment]
We insert different dynamic intermediate classes depending on whether the object is instantiated standalone or retrieved from the database. Those intermediate classes, instantiated themselves at runtime, have for persisted objects overwritten accessors which retrieve the actual data instead. That means, you can never rely on `-[instance isMemberOfClass:]` or `-[instance.class isEqualTo:]` when working with `RLMObject` descendants / your own model objects. Instead you should always rely on [**`-[instance isKindOfClass:]`**](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Protocols/NSObject_Protocol/index.html#//apple_ref/occ/intfm/NSObject/isKindOfClass:).

I guess as that is a general Objective-C idiom, we abstained from explicitly pointing that out in the documentation so far. E.g. `NSArray` is a class cluster, which uses different subclasses depending on how it was instantiated, so you might came across `_NSPlaceholderArray` and similar variants, so to avoid depending on implementation details, the latter form to check the type of an object might be more preferable, even though the Foundation documentation might be easily interpreted as hints in a different direction.

**Comment by yuldong** [comment]
Yeah, that is ture. the situation I met is a little complicated. thank you for the answer.
