### ISSUE TITLE
-Wl,-sectcreate,__RESTRICT,__restrict,/dev/null  will crash app

### ISSUE THREAD

**Issue by Todd2010** [realm/realm-cocoa#3026]
Hi, 
    In the project `Building Setting` --> `Other Linker Flags`, `Debug` and `Release`, add `-Wl,-sectcreate,__RESTRICT,__restrict,/dev/null`. than will crash app.
    `-Wl,-sectcreate,__RESTRICT,__restrict,/dev/null` could stop dylib hooking in my app.
    It will be a great pleasure for me if you could solve this problem.
    Thanks a lot!

**Comment by Todd2010** [comment]
I have tried some methods, for example, `Dynamic Framework`, `CocoaPods`, `Static Framework`. App crashed also.
If i clean the `Other Linker Flags` statement, it launch successfully.

**Comment by Todd2010** [comment]
![111](https://cloud.githubusercontent.com/assets/7554072/11954375/f0e986b8-a8e2-11e5-8f5a-90cb4543d528.png)
![222](https://cloud.githubusercontent.com/assets/7554072/11954376/f119aef6-a8e2-11e5-97a6-229f3d5c8dd4.png)

**Comment by Todd2010** [comment]
`Other Linker Flags`:
![111](https://cloud.githubusercontent.com/assets/7554072/11954398/12bab5aa-a8e3-11e5-83b5-5e1c6be0d4a3.png)

`-Wl,-sectcreate,__RESTRICT,__restrict,/dev/null` function:
![222](https://cloud.githubusercontent.com/assets/7554072/11954397/12b8c448-a8e3-11e5-892a-f0c774a3ff90.png)

**Comment by bdash** [comment]
When you say that this change will "will crash app", what exactly do you mean? If your application is crashing, can you share the crash log and backtrace from the crash? Can you share why you believe this to be an issue with Realm?

**Comment by Todd2010** [comment]
I have found a reason that maybe not exactly. My project include `Realm` and some `swift` files at the same time, it will crash and log some information such as `libswiftAVFoundation`, `libswiftCore` and other `libswiftxxx` not loaded. 
However, If I delete all `swift` files, App lunch successfully. Either If I delete `Realm`, App lunch successfully too.

**Comment by Todd2010** [comment]
I set the `Embedded Content Contains Swift Code` in `Building Settings` to 'YES' when I get the crashed log. And then clean the project and run again, crashed as before.

**Comment by Todd2010** [comment]
I think it may be a `linker mechanism` problem , such as `Dynamic` and `Static`.

**Comment by bdash** [comment]
Your recent comments still mention that it is crashing, but you've not yet provided a crash log. Can you please share one?

**Comment by Todd2010** [comment]
I have found the reason. After CocoaPods updated and `Pods.debug.xcconfig` file add `inherited` flag to `OTHER_LDFLAGS`. Removed the `inherited` flag, everything is OK.

**Comment by Todd2010** [comment]
@bdash, I did not do proper research on this issue before. It's my mistake. Thank you very much.
