### ISSUE TITLE
bcsymbolmap files deleted when running run

### ISSUE THREAD

**Issue by dannycohn** [realm/realm-cocoa#3029]
When I upgraded the 0.97.0, the bcsymbolmap files included in the downloaded framework files were committed to git as they are within the framework files. When I build in xcode, those files are deleted. Should those files be gitignored?

**Comment by kishikawakatsumi** [comment]
@dannycohn Sorry, this is `strip-frameworks.sh`'s bug. It was introduced by https://github.com/realm/realm-cocoa/pull/3012. It will be fix https://github.com/realm/realm-cocoa/pull/3032.

Those files should not be gitignored.

Thanks for pointing out :bow:
