### ISSUE TITLE
linkingObjectsOfClass:forProperty: doesn't support subclasses

### ISSUE THREAD

**Issue by timothycosta** [realm/realm-cocoa#3030]
I'm indifferent to whether this is implemented or not, and I would imagine there are performance reasons not to.  But it should be added to the documentation that linkingObjectsOfClass:forProperty: returns results only for the exact class name passed to it, and is not aware of subclasses.

**Comment by mrackwitz** [comment]
This is not implemented yet. That's a still open feature request, we have yet to tackle. See #1109.
But I'd agree that we could improve our documentation around this topic.

**Comment by mrackwitz** [comment]
I opened #3040 to keep track of that.
