### ISSUE TITLE
ABFRealmSearchViewController

### ISSUE THREAD

**Issue by taktikal17** [realm/realm-cocoa#3033]
Hey!

I wanted to build a map with realm. I tried the tutorial on realm ( clustered map view ) and on github (https://github.com/bigfish24/ABFRealmSearchViewController).
Actually, I have a bug when I build the projects:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RLMRealmConfiguration", referenced from:
      type metadata accessor for __ObjC.RLMRealmConfiguration in Utilities.o
  "_OBJC_CLASS_$_RLMSortDescriptor", referenced from:
      type metadata accessor for __ObjC.RLMSortDescriptor in FetchRequest.o
  "_OBJC_CLASS_$_RLMRealm", referenced from:
      type metadata accessor for __ObjC.RLMRealm in ChangeLogger.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Build Active Architecture only is on No.Downloading dependencies
Versions:
cocoapods-0.39.0
 RBQFetchedResultsController (2.5)
 Realm (0.97.0)
 RealmSwift (0.97.0)
 SwiftFetchedResultsController (2.5)
 TOWebViewController (2.2.1)

Please, let's me know if you know how fix it!
Thanks

**Comment by mrackwitz** [comment]
It seems like for some reason your project isn't properly linked to the Realm framework target, but that shouldn't be possible if everything goes fine with CocoaPods.

Have you tried to clean your build folder / delete derived data and build again from scratch? If that doesn't help, I'd encourage you to reset the CocoaPods integration. You might want to use the cocoapods-deintegrate plugin for that purpose and just re-run `pod install` and try building again. This can fix issues if you have changed the way how you integrate. If that shouldn't still help, can you show us your full podfile?

**Comment by taktikal17** [comment]
I would like to thank you, I reseted the the CocoaPods integration and after running pod install, everything goes right. By the way great tutorial on the iOS Clustered Map View with Realm.

**Comment by mrackwitz** [comment]
Thanks for reporting back and the nice feedback. Good to hear that and have fun working with the components.
