### ISSUE TITLE
Swift List of Int type

### ISSUE THREAD

**Issue by sudeep23** [realm/realm-cocoa#3036]
I need to create an array of Int like `[1,2,3]`.
But i cannot use 
`var days = List<Int>()`
So, what is the workaround to get this?

Following is the complete class which extends Object and  Mappable for ObjectMapper

```swift
class OfficeTimingData:Object, Mappable{
    dynamic var fromHour:String?
    dynamic var toHour:String?
    //var days: [Int]?
    var days = List<Int>()
    
    required convenience init?(_ map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        fromHour <- map["fromHour"]
        toHour <- map["toHour"]
        days <- map["days"]
    }
}
```

**Comment by mrackwitz** [comment]
Lists of primitives are not supported yet. There is issue #1120 to track adding support for that. You'll find there some ideas how you can workaround that currently.

**Comment by borut-t** [comment]
+1

**Comment by mrackwitz** [comment]
Closing this issue in favor of #1120.
