### ISSUE TITLE
RealmSwift.Object descendants can't be provided to NSPredicate's variadic initializer

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-cocoa#3039]
As a workaround, you can either use `RealmCollectionType.filter` directly or `NSPredicate(format:_argumentArray:_)`.

It will fail with a not very self-explanatory error message as seen below, as you might expect that would be given for any `NSObject` descendant automatically.

>Class A doesn't conform to CVarArgType

As we have some examples which use `NSPredicate` in our documentation, we should point out the fact because it might be surprising that there is a difference when filtering on relationships with `NSPredicate`, what we didn't covered so far.

**Comment by jpsim** [comment]
Seems to work now based on these Swift REPL commands:

```
$ swift -F /Users/jp/Downloads/realm-swift-0.103.1/osx/swift-2.2
Welcome to Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.30). Type :help for assistance.
  1> import Foundation; import RealmSwift; dlopen("/Users/jp/Downloads/realm-swift-0.103.1/osx/swift-2.2/RealmSwift.framework/RealmSwift", 2) 
$R0: UnsafeMutablePointer<Void> = 0x0000000100607590 -> 0x00007fff5fc38e48 dyld`vtable for ImageLoaderMachOCompressed + 16
  2> class MyModel: Object { dynamic var prop = "" } 
  3> let pred = NSPredicate(format: "obj == %@", MyModel())
pred: NSPredicate = {
  ObjectiveC.NSObject = {
    NSObject = {
      isa = NSComparisonPredicate
    }
    reserved = 0
  }
}
```
