### ISSUE TITLE
Unable to delete a realm object

### ISSUE THREAD

**Issue by dudduss** [realm/realm-cocoa#3041]
I get the following error:

reason: 'Can only delete an object from the Realm it belongs to.'

The following is my code..I am following the docs fine. The top function, I am adding an object to realm and second function, I am deleting. What is wrong?

```
    if (selectedlib.selected) {
        
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        
        FavoriteLibraries *information = [[FavoriteLibraries alloc] init];
        information.libraryName = selectedlib.name;
        
        [realm addObject:information];
        [realm commitWriteTransaction];
        
    } else {
        
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        
        FavoriteLibraries *information = [[FavoriteLibraries alloc] init];
        information.libraryName = selectedlib.name;
        
        [realm deleteObject:information];
        [realm commitWriteTransaction];
        
    }

```

**Comment by kishikawakatsumi** [comment]
@dudduss Realm can only delete "persisted" objects. To deleting objects, fetch persisted objects first, then pass the objects to `deleteObject()` or `deleteObjects()` method.

It seems that you are trying to delete the object that was just made​​. What is the object you'd like to delete actually?

**Comment by dudduss** [comment]
Hi I did exactly that and it worked. Thanks for the help.

**Comment by menhui222** [comment]
According to the primary key to delete????
