### ISSUE TITLE
Performance Question about threading issues

### ISSUE THREAD

**Issue by jeeftor** [realm/realm-cocoa#3049]
I have a LARGE amount of writes (20 a second) and I see that I have two options:

1) - Do all my writes on the main queue

2) - Do my writes on a background queue but each time before writing - make sure that I re-read the database to ensure that I'm not going to run into threading issues

Is there a performance benefit of one approach over the other?

**Comment by TimOliver** [comment]
Hi @jeeftor!

Our best practices for handling writes with Realm are:

1. Where possible, always do them on a background thread. Writing to a Realm file can sometimes take a non-trivial amount of time, which could freeze the UI on the main thread. Write transactions do not block read operations (Only other write operations) so deferring your writes to a background thread can help keep your app responsive.

2. Where possible, it's much more efficient to perform multiple write operations inside one write transaction than to open a new transaction for each update. If you know you'll be reliably receiving many write requests, see if you can collect them and batch them inside fewer write transactions.

In regards to your concern on the background thread, you shouldn't need to worry about re-reading the database. Realm is quite smart in that `Results` objects automatically update when the underlying `Realm()` object is refreshed.

On that note, Realm objects on background threads do not auto refresh (Only on the main thread they do), so instead of performing a new fetch, you should just need to call the `refresh()` method on the `Realm()` object in that thread, and the `Results()` objects should update on your behalf.

I hope that helped!

**Comment by jeeftor** [comment]
Thats helpful, however, I'm a little confused about if i'm doing something wrong in my situation.  So I have a realm object that is a data recording and this object itself contains arrays of messages.  So if i create a data recording on a background queue


My basic class structure is:

    final class Session : Object {
        dynamic var messages : MessageList? = MessageList() 

     func addLocationMessage(msg : dmParsedMessage) -> LocationMessage {
        
        let dmsg : dmLocationMessage = msg as! dmLocationMessage
        let locMsg = LocationMessage(locMsg: dmsg)
        self.messages!.locationMessages.append(locMsg)
        return locMsg;
     }
    
     func addAHRSMessage(msg : dmParsedMessage) -> AHRSMessage {
        
        let dmsg : dmAHRSMessage = msg as! dmAHRSMessage
        let ahrsMsg = AHRSMessage(ahrsMsg: dmsg)
        self.messages!.ahrsMessages.append(ahrsMsg)
        return ahrsMsg
    }
    }

And then a message list that I'm writing all my messages to

    public class MessageList : Object {
      let locationMessageList : List<LocationMessage>()
      let ahrsMessageList : List<AHRSMessage>
    }

So initially I created a background queue where i created the initial **Session** object, however, as i discovered queues are not thread locked and as such when I was calling the `addLocationMessage` function to add new `LocationMessage`s into my **Session** object I was getting threading errors. 

The two ways around this "issue" that I can think of are 

1) do everything on the main thread (which is what i'm currently doing now)
2) Break the integration between the **MessageList** and **Session** objects and store a reference id between both of them that could be used to do a query later


I'm assuming there is another way to re-read the session object somehow from the background queue and batch up my writes or something but I'm a little confused as how to achieve that.

**Comment by TimOliver** [comment]
Ahh okay then. I see.

In response to your options, given the volume of write transactions you're performing, it sounds like there would definitely be a significant performance payoff if you're able to offload this work to a background thread. I'd recommend only doing it on the main thread during development so you can gauge that your logic is working properly.

In regards to using a reference ID and re-reading the session object from a background queue, are you aware of the [Primary Key](https://realm.io/docs/swift/latest/#primary-keys) feature of Realm?
If you add a primary key to each object, you can pass that value between queues, and re-fetch the desired object using the `objectForPrimaryKey` method on your `Realm()` object. Hopefully that should let you access objects properly on the appropriate queues.

Let me know how you go!

**Comment by jeeftor** [comment]
I'll try this as soon as it get a chance.  Is there a way to do auto-inc primary keys or should i just take the UTC time value or something if i want a unique number?

**Comment by TimOliver** [comment]
Cool! Let me know how you go!

Primary keys aren't limited to integers in Realm. The most common pattern we recommend is to make primary keys of type `String` and use NSUUID to generate a unique value for each one.

```
class MyObject: Object {
  dynamic var id = NSUUID().UUIDString

  override static func primaryKey() -> String? {
    return "id"
  }
}
```

**Comment by jpsim** [comment]
Hi @jeeftor, I hope @TimOliver's recommendations and explanations were helpful. I agree with his suggestions. I'd also encourage you to apply general performance auditing practices when optimizing your usage of Realm, such as profiling with Instruments on physical devices and identifying if there are areas of your app that can be improved.

The [Threading](https://realm.io/docs/swift/latest/#threading) section of our docs may also prove valuable as you consider design patterns for your Realm usage.

I'm closing this issue as we haven't heard back from you here in a few weeks, but please let us know if you have any further questions and we'll be happy to help!

**Comment by MickeyHub** [comment]
> In regards to your concern on the background thread, you shouldn't need to worry about re-reading the database. Realm is quite smart in that Results objects automatically update when the underlying Realm() object is refreshed.

Is RLMObject also no need to re-read? , what I want to ask is below:
**scenario**: only one `Person` record in default Realm, the only Person's name is `jack`
```objc
Person *personToPrint = [[Person allObjects] firstObject];
    NSLog(@"%@", personToUpdate.name);  // => jack
    
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
       
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        Person *personToUpdate = [[Person allObjects] firstObject];
        personToUpdate.name = @"mickey";
        [realm commitWriteTransaction];

        dispatch_async(dispatch_get_main_queue(), ^{
           
            NSLog(@"%@", personToPrint.name); // => mickey
        });
    });
```

As you see, before update , I get the person in main thread refered with `personToPrint` var, then fetch the same object from default realm refered with `personToUpdate` var, and update the `personToUpdate`'s name to mickey, print `personToPrint`'s name afterwards, the value is update automatically ?  Is it true? but I do not get this point from [Realm Doc](https://realm.io/docs/objc/0.98.0/)

**Comment by MickeyHub** [comment]
Oh, I would may have got it on https://realm.io/docs/objc/latest/#threading,  right?

**Comment by jpsim** [comment]
Yes
