### ISSUE TITLE
CocoaPods 1.0.0.beta.X can't integrate Realm as a dynamic framework

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-cocoa#3052]
Just updated my project to cocoapods 1.0.0 RC and my realm to 0.97 but can't get the realm pod to compile anymore. Installed + reinstalled few times + cleaned derived data but the error is still here.

![image](https://cloud.githubusercontent.com/assets/633862/12078574/bf95e320-b217-11e5-87c5-56104faa7bd7.png)

Xcode can't find a bunch of files in Realm/include/realm and can't compile the Realm pod. Maybe an issue with the 1.0.0 version of Cocoapods?

**Comment by icanzilb** [comment]
The problem exists also in a brand new project. Xcode 7.2 - create new single view project - add a basic podfile:

use_frameworks!

target 'Realm-test1' do
    pod 'RealmSwift'
end

Realm pod doesn't compile anymore with the same error:

![image](https://cloud.githubusercontent.com/assets/633862/12079647/17ddf01c-b241-11e5-89dc-28a4204a17c4.png)

**Comment by weyert** [comment]
Yes, I have the same problem. If I try to build Realm myself for my iOS project I don't have this problem but then it's complaining about unsupported binaries when archiving it for TestFlight.

**Comment by jpsim** [comment]
I've started looking into this. The issue seems limited to CocoaPods 1.0.0RC1 and only with `use_frameworks!`. Doesn't happen with static builds. I'll have to spend more time looking into this to figure out what's happening. In the meantime, please use a stable release of CocoaPods with Realm as dynamic frameworks.

**Comment by cday** [comment]
I ran into the same issue. Tried to resolve the issue by getting rid of local changes and moving CocoaPods back to 0.39.0. However, once I was back down to 0.39.0 anytime I did `pod install` I am getting the same error. I am basically stuck in a situation where I cannot add or update pods to my project.

**Comment by davejlong** [comment]
I find myself unable to use Cocoapods 0.39, because Alamofire only support the 1.0 betas now. Has anyone found a solution that works with both Alamofire and Realm?

**Comment by jpsim** [comment]
@davejlong no this issue is still not fixed. I suggest you use the last version of Alamofire that works with CocoaPods 0.39... which is still the latest stable version of CocoaPods, so it's strange that Alamofire would deprecate its support for it.

**Comment by mishagray** [comment]
has anyone even done a side-by-side of the Pods project comparison between 0.39 and 1.0 beta?   I feel like it's not even clear what has changed in the generated Xcode project.   But it we can track that down, the reason maybe clear.

**Comment by jpsim** [comment]
The issue is with `header_mappings_dir`. @mrackwitz is looking into it.

**Comment by enricenrich** [comment]
@jpsim Will you release a fix for it soon? 🙌

**Comment by mrackwitz** [comment]
I'm working on it. Meanwhile you can either specify on each run which version you want to use e.g. `pod _0.39.0_ install` (if installed via RubyGems) or use [podenv](https://github.com/kylef/podenv) to manage different versions of CocoaPods side-by-side when working on different projects.

**Comment by bdash** [comment]
I've been told that this problem occurred due to a change in CocoaPods, and that a fix is being tracked in CocoaPods at CocoaPods/CocoaPods#4848.

**Comment by mrackwitz** [comment]
I think, I could address this issue for the latest CocoaPods 1.0 beta with the changes I made on #3227.

**Comment by royherma** [comment]
Has the been fixed for 1.0.0.beta.6? Didn't work for me for 1.0.0.beta.5 (objective-c project).

**Comment by bdash** [comment]
Realm works with CocoaPods 1.0 from beta 4 onwards. If you're having problems with a version newer than 1.0.0b4, please file a new issue containing the information mentioned in our documentation on [Filing Issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) and we'll be happy to help you get to the bottom of the problem.

**Comment by royherma** [comment]
@bdash I'm actually having the same issue as mentioned above 

`<realm/util/features.h> file not found`

I switched to use 1.0.0.beta.4 as you mentioned it should work and did a brand new pod install but no luck. Should I file another issue?

**Comment by bdash** [comment]
Try running:
```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

If you're still having problems after that, please file a new issue as I mentioned above.

**Comment by JiriTrecak** [comment]
I can confirm that the problem persists on 1.0.0.beta.6 and it is not fixed in any version above (even after clearing the caches, trying to deintegrate project etc.).

**Comment by jpsim** [comment]
@JiriTrecak as @bdash said earlier, if you're having problems with a version newer than 1.0.0b4, please file a new issue containing the information mentioned in our documentation on [Filing Issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) and we'll be happy to help you get to the bottom of the problem.

**Comment by zhigang1992** [comment]
Remember to update RealmSwift as well.

This worked for me

```
pod update RealmSwift
```

**Comment by royherma** [comment]
Not using RealmSwift - filed a new issue regarding the matter.

**Comment by dielsonsales** [comment]
> `pod update RealmSwift`

Didn't work for me.

**Comment by jpsim** [comment]
@dielsonsales please open a new issue

**Comment by mrackwitz** [comment]
@dielsonsales: Note that there is currently an issue with CocoaPods 1.0 and OS X targets as seen in #3582.

**Comment by dielsonsales** [comment]
I think I just had some issues when upgrading to CocoaPods 1.0 and reinstalling the libaries. It's working now after deleting all the pods caches and reinstalling everything again.

**Comment by vuchau** [comment]
This worked for me
`pod update RealmSwift`

**Comment by gk-brown** [comment]
I'm seeing this problem with CocoaPods 1.0.1.

    .../Pods/Realm/include/realm/binary_data.hpp:28:10: 'realm/util/features.h' file not found

**Comment by jpsim** [comment]
@gk-brown it's unclear from your comment whether or not you followed the troubleshooting steps here: https://realm.io/docs/objc/latest/#reinstalling-via-dependency-managers

**Comment by gk-brown** [comment]
@jpsim Yes. I followed the documented steps to reset the integration state, but I'm still seeing the issue with CocoaPods 1.0.1.

**Comment by jpsim** [comment]
@gk-brown Sorry to hear about your trouble! Could you please file a new issue, taking care to fill out the issue template and share as much relevant information as possible that could help us identify why Realm isn't building for you? Thanks!

---

Note to all: I'll be locking this conversation to encourage everyone to file new issues, which should help minimize the amount of back and forth that's eliminated by filling out the new issue template. Thanks for your understanding!
