### ISSUE TITLE
Realm.framework/Headers/Realm.h:21:9: error: 'Realm/RLMArray.h' file not found

### ISSUE THREAD

**Issue by JasonZengJ** [realm/realm-cocoa#3061]
When build with Realm，I got this error.   
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/Jason/Documents/OnTheWay/OnTheWay/./Realm.framework/Headers/Realm.h"
        ^
/Users/Jason/Documents/OnTheWay/OnTheWay/./Realm.framework/Headers/Realm.h:21:9: error: 'Realm/RLMArray.h' file not found
#import <Realm/RLMArray.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Realm'
```

xcode 7.2 and swift 2.1.1

**Comment by JasonZengJ** [comment]
Help!!

**Comment by JasonZengJ** [comment]
I have tried Installation with  CocoaPods  and Dynamic Framework , and this error still exist.

**Comment by aelbarji** [comment]
Hello @JasonZengJ I have the same issue! I installed RealmSwift by cocoapods and my project not build anymore with the same message like you! Someone faced the same issue? Help please

**Comment by jpsim** [comment]
@JasonZengJ @aelbarji we have two outstanding CocoaPods issues that we're aware of: #2701 and #3052. Is it possible you're experiencing one of those issues?

The workaround for #2701 is to run `pod install` twice.

The workaround for #3052 is to use a stable version of CocoaPods rather than the 1.0 release candidate.

If you think you're experience a different issue than the ones I've linked to, please share more information following the guidelines [here](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues). Thanks!

**Comment by aelbarji** [comment]
@jpsim my cocoapods version is already 0.39.0. Also i try the workaround #2701 but also don't work! here my error /Users/ayoubelbarji/Documents/CACEIS/project/ag2r/Pods/Realm/Realm/module.modulemap:2:21: error: umbrella header 'Realm.h' not found
    umbrella header "Realm.h"
                    ^
<unknown>:0: error: could not build Objective-C module 'Realm'
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/RealmSwift-Swift.h"

**Comment by JasonZengJ** [comment]
@jpsim    I've tried to use cocoapods 0.39.0， and solved the problem!!!!   Thanks!

**Comment by JasonZengJ** [comment]
@aelbarji

**Comment by JasonZengJ** [comment]
@aelbarji  You can try followings:

1,  try `pod --version` to ensure your Cocoapods is 0.39.0 
2,  run `pod install` again

here is my Podfile

```
# Uncomment this line to define a global platform for your project
# platform :ios, "8.0"

target "OnTheWay" do
use_frameworks!
pod 'SDWebImage', '~>3.7'
pod 'AFNetworking', '~> 2.0'
pod 'BaiduMapKit'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'RealmSwift'
#pod 'Masonry'
#pod 'Aspects'
#pod 'pop', '~> 1.0'
#
end
```

**Comment by aelbarji** [comment]
@JasonZengJ pod --version give me 0.39.0
here my Podfile
```
# Uncomment this line to define a global platform for your project
# platform :ios, "8.0"
# Uncomment this line if you're using Swift
use_frameworks!

target 'ag2r' do

pod "PKHUD"
pod 'Calendar-iOS'
use_frameworks!
pod 'PageMenu'
pod 'Charts'
pod 'Fabric'
pod 'Crashlytics'
pod 'ObjectMapper'
pod 'AlamofireObjectMapper'
use_frameworks!
pod 'RealmSwift'

end

target 'ag2rTests' do

end

target 'ag2rUITests' do

end
```
But when i run pod install i have this 
```
[!] The `ag2r [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-ag2r/Pods-ag2r.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `ag2r [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-ag2r/Pods-ag2r.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by JasonZengJ** [comment]
try this Podfile.
```
# Uncomment this line to define a global platform for your project
# platform :ios, "8.0"
# Uncomment this line if you're using Swift
target 'ag2r' do
use_frameworks!
pod "PKHUD"
pod 'Calendar-iOS'
pod 'PageMenu'
pod 'Charts'
pod 'Fabric'
pod 'Crashlytics'
pod 'ObjectMapper'
pod 'AlamofireObjectMapper'
pod 'RealmSwift'

end
```

I ran into the similar warnings when 'pod install' with CocoaPods 1.0.0

**Comment by aelbarji** [comment]
@JasonZengJ i tried your Podfile but no success always the same warnings
and same errors
<img width="1437" alt="capture d ecran 2016-01-06 a 10 35 58" src="https://cloud.githubusercontent.com/assets/10722948/12139534/67a08692-b461-11e5-9434-fa78a7c09c45.png">
<img width="1439" alt="capture d ecran 2016-01-06 a 10 36 17" src="https://cloud.githubusercontent.com/assets/10722948/12139541/78deeb56-b461-11e5-9927-227ed76cff5e.png">

**Comment by jpsim** [comment]
@aelbarji CocoaPods is telling you that your Xcode project is overriding CocoaPods header search path configuration, therefore breaking some pods, in this case Realm:

```
[!] The `ag2r [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-ag2r/Pods-ag2r.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `ag2r [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-ag2r/Pods-ag2r.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

It even shows you how to fix it! :smile: 

> Use the `$(inherited)` flag

Using your Podfile in a new project with Xcode 7.2 builds and runs fine for me: http://static.realm.io/debug/GH3061.tgz

**Comment by aelbarji** [comment]
@jpsim the problem was because of i selected Pods/** in my project settings under Header Search Paths! But when i set $(inherited) flag, i can load my Bridging imports.
<img width="1440" alt="capture d ecran 2016-01-08 a 10 36 47" src="https://cloud.githubusercontent.com/assets/10722948/12194904/c1b641f6-b5f3-11e5-9aca-b459cf30f48a.png">

**Comment by jpsim** [comment]
For help with general CocoaPods usage, I'd recommend you open an issue on their issue tracker: https://github.com/CocoaPods/CocoaPods/issues.

I'm closing this ticket since this problem is unrelated to Realm.

**Comment by siuying** [comment]
I had the same problem, both using CocoaPods and not (dynamic framework).
