### ISSUE TITLE
EXC_BAD_ACCESS trying to iterate over List

### ISSUE THREAD

**Issue by Jonovono** [realm/realm-cocoa#3065]
I have this Model defined:
 
    class Message: Object, Mappable {
    dynamic var message = ""
    dynamic var from_id = ""
    dynamic var to_id = ""
    dynamic var sent_date = NSDate(timeIntervalSince1970: 1)
    
    required convenience init?(_ map: Map) {
        self.init()
    }
    }

    class Match: RLMObject, Mappable {
    dynamic var name = ""
    dynamic var tinder_id = ""
    dynamic var bio = ""
    dynamic var age = 0
    dynamic var birth_date = NSDate(timeIntervalSince1970: 1)
    dynamic var ping_time = NSDate(timeIntervalSince1970: 1)
    dynamic var matched_date = NSDate(timeIntervalSince1970: 1)
    dynamic var distance_km = 0.0
    dynamic var thumbnail = ""
    var messages = List<Message>()

Now I am trying to do this on a match that I have:
 
            for message in match.messages {

But I get a "EXC_BAD_ACCESS" on this line:
    
        public func generate() -> RLMGenerator<T> {

My match looks like this in the output:

     Match {
	distance_km = 213;
	thumbnail = "";
	messages = RLMArray <0x12d794660> (
		[0] Message {
			message = Oh nanaa what's my name;
			from_id = 56181745819805ba0edc2a4b;
			to_id = 556937d9172673113309f337;
			sent_date = 47797-06-18 21:26:31 +0000;
		},
		[1] Message {
			message = Hello there Jordan;
			from_id = 556937d9172673113309f337;
			to_id = 56181745819805ba0edc2a4b;
			sent_date = 47811-02-07 10:14:06 +0000;
		}
	);
}

Any ideas what I am doing wrong?

I should be up to date. I just pod installed this the other day ago.

**Comment by jpsim** [comment]
There are a few things that jump out at me as being incorrect:

1. Mixing Realm Objective-C with Realm Swift. This is untested, and likely to have issues. In this case, you're subclassing `RLMObject` but using `List<>` properties. If using Realm entirely from Swift, you should never have to `import Realm`, just `import RealmSwift`.
2. Using a `var` list property: `var messages = List<Message>()`. This is unsupported, please declare all `List` properties as `let`, as explained in our documentation: https://realm.io/docs/swift/latest/#property-attributes

Please try making these changes and report back if you're still having issues.

**Comment by Jonovono** [comment]
Ah, great thanks @jpsim . I will try that tonight and see if it works.

**Comment by Jonovono** [comment]
@jpsim Worked great, thanks! I got rid of Objective-C Realm uses.

**Comment by jpsim** [comment]
Glad to hear it!
