### ISSUE TITLE
Errors returned by Realm should use different domains for error codes from different sources

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#3069]
The variants of `RLMMakeError` always use `RLMErrorDomain` for the domain of the error, but the error code itself can come from different sources (the value of the `RLMError` argument passed to the function, or `std::error_code::value`). The different sources use the same codes to represent different errors (e.g., 2 could mean either `RLMErrorFileAccess` or `ENOENT`, 4 could be either `RLMErrorFileExists` or `EINTR`).

I think we should be using `NSPOSIXErrorDomain` for `std::system_error`s with a category of `std::generic_category`. I'm not sure what the right approach is for errors from other categories. We could create an `RLMUnknownSystemErrorDomain`, or we could map them all to an `RLMUnknownError` code (is this what `RLMErrorFail` is for?) and include the underlying exception's code in the user info dictionary. Either approach would also benefit from having the category name in the user info dictionary.

**Comment by austinzheng** [comment]
This is in. Unfortunately, it doesn't appear that Realm Cocoa actually throws non-Realm exceptions that can be propagated into `NSError` objects. If this changes in the future additional unit tests should be written.
