### ISSUE TITLE
large data sets

### ISSUE THREAD

**Issue by foobar8675** [realm/realm-cocoa#3072]
Can realm support millions of objects? Say my ios app records samples on a minute by minute basis, and those samples are continuously recording. After hypothetically, 4 years, that would be about 2M records.  

So my question is is realm a fit database wise for my use case? Or is it more intended for smaller datasets?

**Comment by jpsim** [comment]
Hi @foobar8675, Realm is ideally suited for large amounts of data like this. For example, writing 2M objects (with a single boolean property) creates a Realm file weighing in at 281KB.

This test file was created with the following code:

```swift
class A: Object {
  dynamic var b = false
}

let realm = try! Realm()

try! realm.write {
  for index in 0..<2_000_000 {
    if index % 1000 == 0 {
      print(index)
    }
    realm.create(A.self, value: [index % 2 == 0])
  }
}
```

**Comment by foobar8675** [comment]
excellent. thank you.
