### ISSUE TITLE
更新数据时 无效

### ISSUE THREAD

**Issue by yushuyi** [realm/realm-cocoa#3074]
![image](https://cloud.githubusercontent.com/assets/1632740/12167489/575a68fa-b567-11e5-819f-c3ed3bb08634.png)
content = ‘123’ 执行完以后  数据库 里面依旧是旧的值
而remark = ‘123’ 执行完以后  数据库里面正常更新  

为什么

---- English translation ----
After executing `content = ‘123’ `, the Realm db stays with the old value
But after executing `remark = ‘123’`, the Realm db updates to the new value

why?

**Comment by beeender** [comment]
@yoshyosh Can you please post your class declaration of c here?

**Comment by yushuyi** [comment]
@beeender 
        let c =  RealmCloud.objects(DNCaseMessage).filter("userCase = %@ ",userCase)
        currentCaseMessages = c
        RealmCloud.update { () -> Void in
            c[1].content = "123"
            c[1].remark = "123"
            
        }


    
    static func update(@noescape block: (() -> Void)) {
        write(block)
    }
    
    static func delete() {
    
    }
    
    private static func write(@noescape block: (() -> Void)) {
        do {
            try realm.write(block)
        }catch let error as NSError {
            print(error)
        }
    }

**Comment by yushuyi** [comment]
![image](https://cloud.githubusercontent.com/assets/1632740/12167976/4798eb5a-b56a-11e5-816d-c6a4c66ed5f6.png)
@yoshyosh 
@mrackwitz 
@beeender

**Comment by yushuyi** [comment]
首次创建那条时  可以成功写入content值，但是也无法正常读取那个content， 返回nil
![image](https://cloud.githubusercontent.com/assets/1632740/12168815/c00ea962-b56f-11e5-9ee1-278c296c1ee9.png)

**Comment by yushuyi** [comment]
我找到原因了。 原来是 var content : String? 没有声明 dynamic 关键字。导致了。这个原因。
不过 我能不能提个建议： 就是在 当事物提交过程中 修改对象的值 如果 这个属性没有声明 dynamic
能不能给个提示之类的。  提示我  你如果想修复这个属性到数据库 就必须声明 这个属性为 dynamic。

**Comment by beeender** [comment]
@yushuyi 原因是，在 Realm 对象中，声明非 `dynamic var` 是完全合法的，而且有用户有这样的需求。所以我们在碰到属性没有被声明 `dynamic` 的时候不太合适报一个警告。

https://realm.io/cn/docs/swift/latest/#attributes 这里有关于 Realm 使用 dynamic 的声明。可以对比下英文版 :smile:  https://realm.io/docs/swift/latest/#property-attributes

感谢反馈哈！
