### ISSUE TITLE
RealmSwift: Creating a copy of object does not copy its dependencies but assign them to the copy.

### ISSUE THREAD

**Issue by IsmailHassanein** [realm/realm-cocoa#3076]
I have an object of type  `A` which has a list of objects `B` along with other variables. I wanted to get a copy  of `A` using `let copyA = A(value:objectA)`. what I got is a diffrent object of `A` but its list of `B` objects refer to the same objects in `objectA`.

**Comment by bigfish24** [comment]
This is the expected behavior, so you would need to perform the copy manually to trigger copying all of the children (i.e. create a new A copy then loop through and do the same with each child).
