### ISSUE TITLE
realm objective-c  0.97.0 crash 

### ISSUE THREAD

**Issue by com314159** [realm/realm-cocoa#3079]
The Crash log is like this

crash 1

![image](https://cloud.githubusercontent.com/assets/5378240/12191906/b91094c2-b614-11e5-87a0-359a694c2b2c.png)

![image](https://cloud.githubusercontent.com/assets/5378240/12191921/d7589998-b614-11e5-8ff2-f58e910645fa.png)

crash 2
![image](https://cloud.githubusercontent.com/assets/5378240/12191915/c77a5d7c-b614-11e5-88ce-a1733ab4a649.png)

![image](https://cloud.githubusercontent.com/assets/5378240/12191921/d7589998-b614-11e5-8ff2-f58e910645fa.png)

![image](https://cloud.githubusercontent.com/assets/5378240/12191925/de2495d8-b614-11e5-8848-0b8e7de8d811.png)

I download file and use Realm to record the file progress.  when I switch continue and pause state of the download operation, the operation will create for continue download and dealloc for pause, and use Realm to record the state and progress.  When user switch very fast, it will crash, the crash just like before.

**Comment by kishikawakatsumi** [comment]
@com314159 
This crash seems same as https://github.com/realm/realm-cocoa/issues/3013 and https://github.com/realm/realm-cocoa/issues/3035.

This issue was fixed by https://github.com/realm/realm-cocoa/pull/3078

Can you check whether it will reproduce when using master build?

**Comment by com314159** [comment]
I  will  update  Realm  this  mouth，and see  if  It will  reproduce。

**Comment by jpsim** [comment]
Closing assuming #3078 fixed the issue. Will reopen if we hear back from @com314159 if it happens again after updating to Realm on `master` or a release including the fix.
