### ISSUE TITLE
筛选出来的数据DESC排序

### ISSUE THREAD

**Issue by dowhilenet** [realm/realm-cocoa#3080]
```swift
realm.objects(GithubStarsRealm)

//结果是按照插入的顺序，我想最后插入的数据在前边
```

**Comment by mrackwitz** [comment]
If your question is about sorting results descending by a given attribute, then the answer is: you can achieve that with [`sorted("name", ascending: false)`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sorteduRdq_CS_6Object_FGS0_q__FTSS9ascendingSb_GS0_q__). If not, it would be helpful, if you could provide a little more info about what you're trying to achieve in english.

**Comment by dowhilenet** [comment]
I don't have an attribute for  ` sorted("name", ascending: false)`  . 

```swift
class student: Object{
    dynamic var name = ""
    dynamic var age = ""
}
```
I hope sorted by Insertion sequence .  DESC OR ASC

**Comment by kishikawakatsumi** [comment]
@dowhilenet 

> I hope sorted by Insertion sequence.

There is no way to retrieve insertion sequence. You can add property something like `insertionSequence` then manually manage insertion sequence yourself.

For example, increment `insertionSequence` property whenever you add object,
```
try! realm.write {
    ...
    student.insertionSequence += 1
    realm.add(student)
}
```

Then you can sort by `insertionSequence`,

```
results.sorted("insertionSequence", ascending: false)
```
 

```

**Comment by dowhilenet** [comment]
@kishikawakatsumi 

Finally, I also handled this way, very grateful.But still we want to have a more convenient way  :]

**Comment by mrackwitz** [comment]
It looks like you're looking for a SQL-typical feature of auto incrementing properties. Realm doesn't support that. I'd propose as a workaround to add a `createdAt` property, which uses the current time as default value. It seems like that would allow what you want to achieve.

**Comment by dowhilenet** [comment]
@mrackwitz 谢谢。thanks。 :+1:

**Comment by mrackwitz** [comment]
You're welcome. :)
