### ISSUE TITLE
header_mappings_dir probably points to wrong directory

### ISSUE THREAD

**Issue by TadeasKriz** [realm/realm-cocoa#3085]
With Cocoapods 1.0.0.beta2, Realm cannot be compiled because it cannot find headers under `realm/` etc. For example line `#include <realm/util/features.h>` fails because the header directories are flattened. The `pod lib lint` should throw errors in the new Cocoapods 1.0.0.beta2 version.

**Comment by jpsim** [comment]
Closing as a duplicate of #3052.
