### ISSUE TITLE
The official website download framework package very slow in China

### ISSUE THREAD

**Issue by AbooJan** [realm/realm-cocoa#3086]
In China, when i download the framework package in your official website, the download speed is very slow, and sometimes download failed.

I hope your team can optimize this , thank you very much, best wish for realm!

**Comment by mrackwitz** [comment]
Thanks for bringing to our attention again. I think, @beeender is doing ongoing investigations in that direction.

**Comment by beeender** [comment]
@AbooJan We are afraid that our CDN has some problems with some of the ISPs in China. We are trying find a solution for that. But internet access problem in China might take us some time to solve... If possible, please use VPN when downloading. Really sorry for the inconvenience .

**Comment by jpsim** [comment]
Since we're tracking this in a number of other places and are taking measures to improve this, I'll close this issue. Again, sorry about the inconvenience!
