### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by sanshanchuns** [realm/realm-cocoa#3091]
Installing Realm (0.97.0)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.95.5
Downloading core failed. Please try again once you have an Internet connection.

**Comment by sanshanchuns** [comment]
cocoapods-0.39.0
xcode7.2

**Comment by jpsim** [comment]
Are you possibly attempting to download Realm from China? If so, we're tracking some issues with that in #2713, and note some possible workarounds such as using a VPN or downloading a release from GitHub.

**Comment by worchyld** [comment]
I get a similar issue;

```
[!] /usr/local/bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.95.5
Downloading core failed. Please try again once you have an Internet connection.
```

**Comment by jpsim** [comment]
@worchyld Are you possibly attempting to download Realm from China? If so, we're tracking some issues with that in #2713, and note some possible workarounds such as using a VPN or downloading a release from GitHub.

**Comment by worchyld** [comment]
sadly i am not sure if i am downloading it from china, all i do is put in the podfile command and enter pod install.

**Comment by jpsim** [comment]
@worchyld are you, yourself in China? If so, you're likely experiencing #2713 and should try one of the workarounds I've mentioned. Have you tried one of my suggestions yet?

**Comment by GaborWnuk** [comment]
Same thing here, trying to install from Poland.
```
Installing Realm (0.96.3)
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.95.4
Downloading core failed. Please try again once you have an Internet connection.
```

**Comment by worchyld** [comment]
I solved my issue by downloading realm from Github and manually installing it

**Comment by jpsim** [comment]
@GaborWnuk asking the obvious: were you connected to the Internet when running `pod install`? Have you tried again since? When you visit https://static.realm.io/downloads/core/realm-core-0.95.4.tar.bz2 in your web browser, does the file download successfully?

**Comment by rayman-v** [comment]
I am working in VPN, but I still get this issue

**Comment by jpsim** [comment]
I'm closing this as there's no actionable steps for us to take. Downloads will occasionally fail, there's not much we can do about that. The error message being printed is accurate. We are taking steps to improve the situation in China, however: #2713.
