### ISSUE TITLE
Realm always asking permission to access path

### ISSUE THREAD

**Issue by hebertpalomino** [realm/realm-cocoa#3094]
I'm trying to save object to my realm but when I open the database in the newest explorer it says it needs access to this path even though my podfile shows I'm using 0.97.0. 
I've tried deleting pods/lock file and also doing a clean install.
Why is it always asking permission each time I open file? 
This doesn't happen if I open the file twice in a row, only when I re-run the app and things get re-written/updated.

**Comment by bdash** [comment]
Are you asking about Realm Browser's dialog that says "Realm Browser needs to access this path to continue. Click Allow to continue."?

**Comment by hebertpalomino** [comment]
Yes

**Comment by bdash** [comment]
Thanks for clarifying. That dialog is presented by Realm Browser, which is developed in the [Realm Browser repository](/realm/realm-browser-osx). Would you please [re-file your issue in the Realm Browser repository](/realm/realm-browser-osx/issues/new)?
