### ISSUE TITLE
Sqlite3 to Realm convert.

### ISSUE THREAD

**Issue by anandkumarsharma** [realm/realm-cocoa#3096]
Hello sir,

I am converting sqlite3 into Realm.
I am new to Realm, i would like to get count from  Realm model like below as sqlite3 code but i am not get success please help me.

My sqlite3 code are as follow:-

```objc
DatabaseManager *dbManager = [DatabaseManager sharedManager];
__block  NSUInteger counts;

     [dbManager.databaseQueue inDatabase:^(FMDatabase *db)
     {
        counts = [db intForQuery:[NSString stringWithFormat:@"SELECT COUNT(*) FROM  ContactCardTbl where
                                                  contactCardId='%@'", contactCardId]];
      }];

             [dbManager.databaseQueue inDatabase:^(FMDatabase *db)
             {
                 if (counts == 0)
                 {
                      [db executeUpdate:@"INSERT INTO ContactCardTbl (contactCardId,userId,full_Name,changeId,json) values (?,?,?,?,?)",contactCardId,userId,full_Name,changeId,json];
                }
                else
                 {
                    [db executeUpdate:@"UPDATE ContactCardTbl SET userId = ?, full_Name = ?, changeId = ?, json = ? WHERE contactCardId = ?", userId, full_Name, changeId, json, contactCardId];
                 }
            }];

}
```

I am converting this code in Realm as follows:

```objc
 RLMRealm *realm = [RLMRealm defaultRealm];
            
            //Begin a write transaction to save to the default Realm
            [realm beginWriteTransaction];

              contactModel *contactModelInformation = [[contactModel alloc]init];
        
             [contactModel objectsWhere:@"contactModelInformation.@count"];
        
              NSLog(@"contactModel counts -----%@", [contactModel objectsWhere:@"contactModelInformation.@count"]);
        
             contactModelInformation.contactCardId = [dictionary objectForKey:@"contactCardId"];
             contactModelInformation.userId = [dictionary objectForKey:@"userId"]; 
             contactModelInformation.full_Name = [dictionary objectForKey:@"full_Name"];
             contactModelInformation.changeId = [NSString stringWithFormat:@"%@",[dictionary objectForKey:@"changeId"]];

            
             NSData* jsonDataDic;
             if ([dictionary isKindOfClass:[NSDictionary class]]) {
               jsonDataDic = [NSJSONSerialization dataWithJSONObject:dictionary options:0 error:nil];
                 contactModelInformation.json = [[NSString alloc] initWithBytes:[jsonDataDic bytes] length:[jsonDataDic length] encoding:NSUTF8StringEncoding];
            }
            
            //Add the loginInformation object to default Realm.
             [realm addObject:contactModelInformation];
        
        
            //Persist all the loginInformation that were persisted.
             [realm commitWriteTransaction];
            
       // });
    }
```

but i am not get success please help me how this realm code will be work as same as sqlite3 code of above.

Thanks,

**Comment by mrackwitz** [comment]
Can you also share with us what is the error you're getting and causing you troubles?
You can count all objects of a given model by using: `contactModel.allObjects.count`.
Beside that I'd recommend to name your Objective-C classes beginning with an uppercase char. That's a common convention and helps others reading your code differentiating between compile time types and variables.

**Comment by anandkumarsharma** [comment]
Thank you so much for your help and suggestions,
contactModel.allObjects.count give me total count of all objects, I would like total count of a single column value , then how it is possible in Realm.

Actually i want the single column count, if this count returns me zero then i will go to insert value into Realm model , otherwise i will update the ContactModel in Realm.
Please help.

**Comment by mrackwitz** [comment]
Are you sure, what I proposed is really not what you're looking for?
It's unclear to me what you mean by the "total count of a single column value".
What I could imagine alternatively would be the count of objects:
1. where each has for a given column distinct values
2. where each has for a given column a value which differs from nil
If both shouldn't be what you're looking for please clarify what you mean.

**Comment by anandkumarsharma** [comment]
yes, i want,
1. where each has for a given column distinct values.

For example in sqlite3:-

  counts = [db intForQuery:[NSString stringWithFormat:@"SELECT COUNT(*) FROM  ContactCardTbl     where  contactCardId='%@'", contactCardId]];

here i am calculating counts from ContactCardtbl of contactCardId column,
 where contactCardId is a primary key  in a  ContactCardtbl table which uniquely identifies each row/record in a database table.

I want same count in Realm, how it is possible, please help.

Thanks

**Comment by mrackwitz** [comment]
Okay, I see what you want to achieve. You want to check for each object, whether it exists and insert it only if it doesn't exist, right? Realm has built-in support for that.

If your object creation is computationally inexpensive, you can do `[realm addOrUpdateObject:…];`.

Otherwise you can just query for the object by using `[ContactModel objectForPrimaryKey:…]` and check that against `nil`.
