### ISSUE TITLE
ignoredProperties are not ignored

### ISSUE THREAD

**Issue by danielsaidi** [realm/realm-cocoa#3097]
Hi,

I am using Realm Swift 0.97.0 and am having the same problem as previously reported (e.g. https://github.com/realm/realm-cocoa/pull/2734).

In short, I am having a computed UIImage property, let's call it "image":

```
var image: UIImage {
   get { ... }
   set { ... }
}
```

I used to have the type be UIImage?, but refactored it to be UIImage since the link above said that the bug only affected optional properties in Swift.

In order to not have the UIImage property causing problems, I add it to the ignoredProperties list, so that that function looks like this:

```
override class func ignoredProperties() -> [String] {
   return ["image", "hasId"]
}
```

However, this does not work. I still get the following error:

Uncaught exception: 'UIImage' is not supported as an RLMObject property. All properties must be primitives, NSString, NSDate, NSData, RLMArray, or subclasses of RLMObject.

**Comment by mrackwitz** [comment]
Could you please share your full model definition?

**Comment by danielsaidi** [comment]
Sure, I have posted the complete model in terms of design and inheritance, but have removed redundant properties to make the post manageable.

My entity class (let's call it Item) inherits from a base class called Entity:

```
class Entity: RLMObject {
    
    dynamic var id = ""
    
    var hasId: Bool {
        get { return id.characters.count > 0 }
    }
    
    override class func primaryKey() -> String {
        return "id"
    }
    
    override class func ignoredProperties() -> [String] {
        return ["hasId"]
    }
}
```

The Item class then specifies some new properties, as such:

```
class Card: Entity {

    dynamic var name = ""
    dynamic var imageString = ""
    
    
    var image: UIImage {
        get { return stringToImage(imageString) }
        set { imageString = imageToString(newValue) ?? "" }
    }
    

    override class func ignoredProperties() -> [String] {
        return ["image", "hasId"]
    }


    private func imageToString(image: UIImage?) -> String {
        if (image == nil) {
            return ""
        }
        let data = UIImagePNGRepresentation(image!)
        return data != nil ? data!.base64EncodedStringWithOptions(.Encoding64CharacterLineLength) : ""
    }
    
    private func stringToImage(string: String) -> UIImage {
        if (string.characters.count == 0) {
            return UIImage()
        }
        
        let imageString = string.stringByReplacingOccurrencesOfString("\r\n", withString: "")
        let options = NSDataBase64DecodingOptions(rawValue: 0)
        let data = NSData(base64EncodedString: imageString, options: options)
        let image = data != nil ? UIImage(data: data!) : nil
        return image ?? UIImage()
    }
}

```

So, to sum it up, each item will store a base 64 encoded string, using Realm, then decode that string into an UIImage whenever needed.

However, although the image property is added to the list of excluded properties, as you see in the Item class, the app crashes and says that I cannot have UIImage properties.

As I wrote earlier, I used to have the UIImage property being a UIImage?, but tried this instead, since Realm had some issues with nullable properties earlier.

Also, I have tried to remove the Entity inheritance, thinking that it may have caused Realm to grab the excluded property list of the Entity class, but that didn't solve my problem.

All the best

Daniel

**Comment by mrackwitz** [comment]
I was trying to reproduce the error you describe, but it worked fine for me.
Are you sure, you don't have any other class in your model, which has a property of type `UIImage`, which is not ignored?

Beside that, you said initially, you would be using Realm Swift, but your `Entity` base class is inheriting from `RLMObject`. If you use `RLMObject` definitions, you shouldn't be using Realm Swift. They are incompatible. Realm Swift is providing its own entity base class `RealmSwift.Object`.

**Comment by danielsaidi** [comment]
Hi,

That's strange. It does not work at all for me, neither with nor without the Entity inheritance.

I'm positive that this property is the one that is messing it up - Item is the only realm class with a UIImage property and no other class inherits the Item class. Also, as soon as I remove the property, the app builds and runs without problems. 

I have missed the new base class for Realm objects in Realm Swift. I started out using the Objective C lib a while back, so all entities are still using that. I'll give RealmSwift.Object a try and let you know if it solves this problem.

Just so I know, did you make it work with RLMObject or did it work when inheriting RealmSwift.Object?

Thanks!

**Comment by mrackwitz** [comment]
Just had another look at it:
I can reproduce now that it fails for `RLMObject` subclasses from Swift, when Realm Swift is linked. That's the case because Realm Swift provides an alternative internal object utility class, which checks whether the object is a `RealmSwift.Object` and then calls the implementation of `ignoredProperties`, which wouldn't be possible otherwise via the Objective-C runtime. There is no check whether it is an `RLMObject`, but you're not supposed to mix them both.

Can you confirm that you have linked Realm Swift? If so, please don't do that when you use `RLMObject` descendants. Alternatively you use Realm Swift's pendant `Object`, which worked fine for me with your class excerpt, but would mean some migration effort.

**Comment by danielsaidi** [comment]
Ah, ok that's great! Yes, I use Realm Swift and RLMObject with descendants, so that must absolutely be the case. I will make the class inherit Object instead, and will write back here once I have done so. Thank you so much.

**Comment by mrackwitz** [comment]
You're welcome. Thanks for bringing that up.

**Comment by danielsaidi** [comment]
Hi again,

I just wanted to let you know that i have replaced Realm with RealmSwift everywhere and now let my entity classes inherit Object instead of RLMObject. 

I can verify that optional, computed UIImage properties that use underlying NSData properties work perfectly. Thank you for all your help!

**Comment by mrackwitz** [comment]
Sure, glad that it helped. Thanks for reporting back again.
