### ISSUE TITLE
Is Realm require network access?

### ISSUE THREAD

**Issue by ethanliu** [realm/realm-cocoa#3098]
Situation:
When the cell network is bad but not totally disconnect, and without wifi connections.
App or extension crashes or freeze when launching, sometimes turn off/on airplane mode helps sometimes not. And when the network is stable with wifi connected, above issue is gone.

This is hard to reproduce, but I have it a few times in some particular area after implement Realm, then wonder if Realm try to access the network when launching app or extension? Since my app/extension doesn't require network access.

**Comment by mrackwitz** [comment]
Realm is only accessing the network in development when a debugger is attached to ping back some  	anonymized usage information. See https://github.com/realm/realm-cocoa/blob/master/Realm/RLMAnalytics.mm#L19-L53 for more information about what we do there and why. These shouldn't been the cause for any issue like you documented, but feel free to disable that.

**Comment by ethanliu** [comment]
Thanks for the information and I have no problem with the code and usage.
Like I said earlier it's hard to reproduce, so it took me a long time to test, I did turn it off on dev device and so far never have the same issue.
