### ISSUE TITLE
objectForPrimaryKey

### ISSUE THREAD

**Issue by pjebs** [realm/realm-cocoa#3099]
I am using Realm-ObjC in a mixed project.
When my obj-c model is bridged to swift, the `objectForPrimaryKey` is not visible. It is visible in Obj C world.

There are other functions that don't bridge over to swift but the provided `RLMSupport.swift` makes them visible.
Can you please add it to `RLMSupport.swift` Helper because  `objectForPrimaryKey` is very useful.

**Comment by kishikawakatsumi** [comment]
@pjebs Objective-C factory methods get mapped as convenience initializers in Swift automatically. So `objectForPrimaryKey:` method is converted to `RLMObject(forPrimaryKey:)`. 

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html

If `Book` model class is defined like the following:

```
@interface Book : RLMObject
@property NSString *identifier;
@end
```

You can use `Book(forPrimaryKey: "...")` initializer instead `objectForPrimaryKey:` method.
