### ISSUE TITLE
index bool

### ISSUE THREAD

**Issue by pjebs** [realm/realm-cocoa#3102]
Can you please implement indexing for bools.

Although I don't know how Bools are implemented in Realm, given that bools are internally almost always a subset of ints, it should be possible to *easily* index Bools.

That would be a super useful feature. My app is not ready for production just yet, but if I may have to resort to changing the variable type to ints just to put a 0 or 1.

**Comment by kishikawakatsumi** [comment]
@pjebs We are working it on https://github.com/realm/realm-cocoa/pull/3081
