### ISSUE TITLE
RLMException: Illegal recursive call of RLMSchema sharedSchema. Properties of Swift when I'm not using Swift

### ISSUE THREAD

**Issue by crsantos** [realm/realm-cocoa#3103]
I'm having a problem running Unit tests on my test target.
I've linked only the Realm Headers on the test target, but still, An exception is saying that I use Swift code when I'm not event using it...

This is my Podfile:
```ruby
target App_Tests', :exclusive => true do
  pod 'Realm/Headers', '0.97.0'
end
```
The erros I have are:
`  Assertions: failed: caught "RLMException", "Illegal recursive call of +[RLMSchema sharedSchema]. Note: Properties of Swift `Object` classes must not be prepopulated with queried results from a Realm."`

```obj-c
(
	0   CoreFoundation                      0x0000000111929e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000110bc5deb objc_exception_throw + 48
	2   CashYTSDK_Tests                     0x00000001218d86f4 +[RLMSchema sharedSchema] + 244
	3   CashYTSDK_Tests                     0x000000012189c35c +[RLMObjectBase sharedSchema] + 60
	4   CashYTSDK_Tests                     0x00000001218997fc _ZL26RLMInitializedObjectSchemaP13RLMObjectBase + 140
	5   CashYTSDK_Tests                     0x0000000121899708 -[RLMObjectBase init] + 152
	6   CashYTSDK_Tests                     0x000000012189711c -[RLMObject init] + 76
	7   CashYTSDK_Tests                     0x000000012151926a __28-[CYDTOUserProfileSpec spec]_block_invoke6 + 138
	8   CashYTSDK_Tests                     0x00000001218ebd71 runExampleBlock + 193
	9   CashYTSDK_Tests                     0x00000001218ebb4e -[SPTExampleGroup runBeforeAllHooks:] + 862
	10  CashYTSDK_Tests                     0x00000001218eb7c2 -[SPTExampleGroup runBeforeHooks:] + 82
	11  CashYTSDK_Tests                     0x00000001218edbc7 __44-[SPTExampleGroup compileExamplesWithStack:]_block_invoke140 + 183
	12  CashYTSDK_Tests                     0x00000001218f0743 -[SPTSpec spt_runExample:] + 387
	13  CashYTSDK_Tests                     0x00000001218f015b __35+[SPTSpec spt_convertToTestMethod:]_block_invoke + 91
	14  CoreFoundation                      0x00000001118181cc __invoking___ + 140
	15  CoreFoundation                      0x000000011181801e -[NSInvocation invoke] + 286
	16  XCTest                              0x000000011e260080 __24-[XCTestCase invokeTest]_block_invoke_2 + 159
	17  XCTest                              0x000000011e293b14 -[XCTestContext performInScope:] + 184
	18  XCTest                              0x000000011e25ffd0 -[XCTestCase invokeTest] + 169
	19  XCTest                              0x000000011e26046b -[XCTestCase performTest:] + 443
	20  CashYTSDK_Tests                     0x00000001218f1349 -[SPTSpec performTest:] + 121
	21  XCTest                              0x000000011e25e131 -[XCTestSuite performTest:] + 377
	22  XCTest                              0x000000011e25e131 -[XCTestSuite performTest:] + 377
	23  XCTest                              0x000000011e25e131 -[XCTestSuite performTest:] + 377
	24  XCTest                              0x000000011e24b181 __25-[XCTestDriver _runSuite]_block_invoke + 51
	25  XCTest                              0x000000011e26bb5b -[XCTestObservationCenter _observeTestExecutionForBlock:] + 615
	26  XCTest                              0x000000011e24b0cd -[XCTestDriver _runSuite] + 408
	27  XCTest                              0x000000011e24be2c -[XCTestDriver _checkForTestManager] + 263
	28  XCTest                              0x000000011e294e99 _XCTestMain + 628
	29  CoreFoundation                      0x0000000111855a1c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	30  CoreFoundation                      0x000000011184b6a5 __CFRunLoopDoBlocks + 341
	31  CoreFoundation                      0x000000011184ae02 __CFRunLoopRun + 850
	32  CoreFoundation                      0x000000011184a828 CFRunLoopRunSpecific + 488
	33  GraphicsServices                    0x0000000113679ad2 GSEventRunModal + 161
	34  UIKit                               0x000000010ee35610 UIApplicationMain + 171
	35  CashYTSDK_Example                   0x000000010c6074e4 main + 132
	36  libdyld.dylib                       0x000000011261d92d start + 1
)
  File: RLMSchema.mm:185
```

Also this error arises:

`Assertions: failed: caught "NSInvalidArgumentException", "+[RLMObjectBase ignoredProperties]: unrecognized selector sent to class 0x10cfe0860"`

Any ideas?

**Comment by jpsim** [comment]
> Assertions: failed: caught "RLMException", "Illegal recursive call of +[RLMSchema sharedSchema]. Note: Properties of SwiftObjectclasses must not be prepopulated with queried results from a Realm."

This exception gets thrown if `+[RLMSchema sharedSchema]` gets invoked recursively. This *can* happen when performing Realm queries during Realm Swift model initialization, which is why we include that in the error message, but it could happen in other situations as well, even when not using Swift or Realm Swift.

Can you please share the part of your code that triggers this exception?

It would also help if we saw your model class definitions and any code that you think may be relevant.

You can also identify each situation where `+[RLMSchema sharedSchema]` gets invoked by setting a symbolic breakpoint in your app to trigger on that method. See https://developer.apple.com/library/ios/recipes/xcode_help-breakpoint_navigator/articles/adding_a_symbolic_breakpoint.html for details.

**Comment by crsantos** [comment]
This happens on a test target, running my Unit Tests that previously passed.
The only difference was, I'm not using `use_frameworks!`on the _Podfile_ anymore, so I suppose it has something to do with the absence of a Framework compiled Pod.

**Comment by jpsim** [comment]
> I suppose it has something to do with the absence of a Framework compiled Pod.

Your app wouldn't compile if that was the case.

Have you tried my suggestions?

> Can you please share the part of your code that triggers this exception?
> 
> It would also help if we saw your model class definitions and any code that you think may be relevant.
> 
> You can also identify each situation where +[RLMSchema sharedSchema] gets invoked by setting a symbolic breakpoint in your app to trigger on that method. See https://developer.apple.com/library/ios/recipes/xcode_help-breakpoint_navigator/articles/adding_a_symbolic_breakpoint.html for details.

**Comment by crsantos** [comment]
It was an issue that arose when I removed 'use_frameworks' that was messing with a weird FBSDKCoreKit podspec. 
I removed that dependency, restored the 'use_frameworks' and it's all working now so I'll close the issue for now. 
Thanks for the suggestions

**Comment by jpsim** [comment]
Thanks for following up @crsantos!
