### ISSUE TITLE
EXC_BAD_ACCESS when modifying database and creating/destroying realms extensively

### ISSUE THREAD

**Issue by zintus** [realm/realm-cocoa#3108]
Hello!

My app have number of realms per ViewController and creating/destroying such ViewControllers tend to crash app quite frequently. See attached backtrace for example. I couldn't create example project right now, but maybe backtrace will be enough.

[backtrace.txt](https://github.com/realm/realm-cocoa/files/91576/backtrace.txt)

**Comment by zintus** [comment]
Different backtrace and error, but looks related to me 

[backtrace2.txt](https://github.com/realm/realm-cocoa/files/91828/backtrace2.txt)

**Comment by tgoyne** [comment]
This was probably fixed by https://github.com/realm/realm-cocoa/pull/3078, which has not yet been included in a release.

**Comment by zintus** [comment]
Thanks, will test on new version.

**Comment by jpsim** [comment]
@zintus have you seen this error again since testing after #3078 was merged? We haven't heard back from you in a while, so I'll close this assuming the fix worked for you, but please let us know!

**Comment by zintus** [comment]
@jpsim had a chance to test this on 0.97.1 release, works fine, thanks!

**Comment by jpsim** [comment]
Happy to hear it!
