### ISSUE TITLE
Having multiple object types in RLMResults

### ISSUE THREAD

**Issue by koenpunt** [realm/realm-cocoa#3112]
Is it possible to have objects of multiple types in a single `RLMResults`? 

I'm using `RLMResults` as datasource for my UITableView, and it would be nice if the different datatypes the tableview represents, are all in a single `RLMResults`

**Comment by mishagray** [comment]
would your objects logically have a common base class?   How would you even do a query?

In Core Data you could have a common 'parent' object and do a single query that might return different objects.    But in general it can be a bit confusing.   

I've done two things in the past to to your solution...
if I am sectioning the table by "Type" - just use a different Results object for each "section".  You could have a data model like    ```var resultBySection : [RLMResults]```    


But if you want a "mix" model (like say... a Facebook feed?)... then you may want to consider a action or proxy object that has a relationship to the "real" object.

```
class FeedItem : Object {

      dynamic var date : NSDate()
      dynamic var itemObject: Object?
}
```

And you could just add properties to the "FeedItem" that will let you sort it the way you want, but have all the "real" data using the "itemObject" relationship.    I've never tried using an 'Object' pointer for a relationship... but it could work?  Would that work?

**Comment by jpsim** [comment]
Have you read the [Model Inheritance](https://realm.io/docs/objc/latest/#model-inheritance) section of our docs along with the in-depth [code samples](https://github.com/realm/realm-cocoa/issues/1109#issuecomment-143834756) it links to?

That should explain everything you need to know about why a single `RLMResults` can't contain multiple types, along with work-arounds for many scenarios.

If anything isn't clear in that documentation, please let us know and we'll be sure to review it.

**Comment by koenpunt** [comment]
@mishagray @jpsim thanks for your responses. I went with the proxy model (`FeedItem`), which fits my case fairly well.
