### ISSUE TITLE
Incorrect message: Provided schema version 4 is less than last set version 3.

### ISSUE THREAD

**Issue by koenpunt** [realm/realm-cocoa#3113]
The message 

```cpp
m_what = "Provided schema version " + std::to_string(old_version) + " is less than last set version " + std::to_string(new_version) + ".";
```

is not always correct, because it can happen, e.g. when switching branches, that the Realm migration version is already higher than the last in code, where the message displays as follows:

```
Provided schema version 4 is less than last set version 3.
```

My CPP skill are absent so I didn't try to fix it myself, but I guess a simple comparison should be enough:

```
joiner = old_version > new_version ? "greater" : "less"
```

https://github.com/realm/realm-cocoa/blob/facde33440f2d46ece3e32ca60ff58f2a9028080/Realm/ObjectStore/object_store.cpp#L504

**Comment by mrackwitz** [comment]
Turns out that the exception is just thrown at one place, so that `old_version` is always greater than `new_version`. So I guess that we just swapped old and new version in the error message by accident.
