### ISSUE TITLE
When will UInt64 be supported in Realm?

### ISSUE THREAD

**Issue by dickyj** [realm/realm-cocoa#3114]
Hi,
I tried to create an object with id of type UInt64, but I got an error ''Can't persist property 'id' with incompatible type.". I guess its not supported, any timeline on when it will be supported? What are the alternative solution now? I am using Swift.

Thanks,
Dicky

**Comment by kishikawakatsumi** [comment]
@dickyj Realm support only **signed** integer types. Such like `Int`, `Int8`, `Int16`, I`nt32` and `Int64`. Is it possible to use `Int64` instead of `UInt64`? In general, `Int64` has enough capacity.

**Comment by dickyj** [comment]
Ok thx for the reply. It will have to do for now.
