### ISSUE TITLE
RealmSwift: KVC collection operators crashes in 0.97 when using List<>

### ISSUE THREAD

**Issue by thonydam** [realm/realm-cocoa#3115]
Hi Realm team,

I just updated my project to realm 0.97 and I am experiencing a crash, which might be related to this issue:
https://github.com/realm/realm-cocoa/issues/2937

I am getting an crash " -[__NSArray0 compare:]: unrecognized selector sent to instance " when I try to use a collection query in a predicate.

I added an example project that shows the crash:
https://github.com/thonydam/realm-collection-query-crash

Thanks for looking into this.

Tony

**Comment by kishikawakatsumi** [comment]
Thank you for reporting and sample project. I can reproduce it.
More small reproducible code is the following:

```swift
class TestObject: Object {
    dynamic var inTable: Bool = false
    var objects = List<TestObject2>()
}

class TestObject2: Object {
}


let predicate = NSPredicate(format: "inTable = YES AND objects.@count > 0")

let realm = try! Realm()
try! realm.write { () -> Void in
    let obj = TestObject()
    obj.inTable = true

    realm.add(obj)
}

if let obj = realm.objects(TestObject).first {
    let s = predicate.evaluateWithObject(obj) // [__NSArray0 compare:]: unrecognized selector sent to instance
    print(s)
}
```

**Comment by bdash** [comment]
The problem here is that the KVC collection operator support added in #2989 assumes that `@count` will be handled via `valueForKeyPath:`, but we actually end up in `valueForKey:`. In this specific case we're hitting `-[RLMArrayLinkView valueForKey:]`. That calls `RLMCollectionValueForKey`, which always returns an `NSArray`.

**Comment by bdash** [comment]
Looking at this a little more, the reason we end up in `valueForKey:` is that `List` doesn't implement `valueForKeyPath:`. It looks like adding an implementation of `valueForKeyPath` that forwards to `-[RLMArray valueForKeyPath:]` will address this.

**Comment by bdash** [comment]
I pushed a WIP fix to [mar/swift-valueforkeypath](https://github.com/realm/realm-cocoa/compare/mar/swift-valueforkeypath). The remaining portion of the fix is documentation comments for the new methods. I'll tackle that next week.
