### ISSUE TITLE
Using NSNumber property crashes while in a interoperability project 

### ISSUE THREAD

**Issue by shams-ahmed** [realm/realm-cocoa#3118]
my model:

```
public class FSCUserAccessibleCommunityModel: RLMObject {
    
    /// community id
    public dynamic var communityId: NSNumber?

    /// community name
    public dynamic var name: String?

    /// community type
    public dynamic var type: String?
    
    // MARK:
    // MARK: Init
    
    override init(value: AnyObject) {
        if let value = value as? NSDictionary {
            communityId = value["id"] as? Int
            name = value["name"] as? String
            type = value["type"] as? String
        }
        
        super.init()
    }
    
    override init() {
        super.init()
    }
}
```

<img width="1104" alt="screen shot 2016-01-19 at 1 07 42 p m" src="https://cloud.githubusercontent.com/assets/2887472/12419393/ba707d22-bead-11e5-8843-2a1bda99789b.png">

Anyone know what the issue is?

**Comment by mrackwitz** [comment]
What you're trying here is unfortunately not supported for `RLMObject`-based classes defined in Swift.
`NSNumber` in Swift doesn't give enough information how to store the contained value. You need to give a hint what kind of values go in there (int, bool, float etc.). In Objective-C, you can use `NSNumber<RLMInt>` for that purpose. But this cannot be represented in Swift. From Swift, you could use `Int?`, but that cannot be seen from Objective-C.
So your options are:
* using an atomic type and describing a null value by another value (e.g. 0 or -1)
* defining your class from Objective-C

**Comment by shams-ahmed** [comment]
@mrackwitz Thanks for the input, i bypassed this issue by adding a default value for NSNumber which seemed to work without any issues.

**Comment by mrackwitz** [comment]
Sure that works, too. Thanks for reporting back.

**Comment by pofat** [comment]
By the language support of current Swift, I figured out that we can use:
`dynamic var communityId: (NSNumber & RLMInt)?` to declare an optional integer in Swift without providing a non-nil default value.
