### ISSUE TITLE
master doesn't build due to typo in Error.swift

### ISSUE THREAD

**Issue by leetr** [realm/realm-cocoa#3126]
file: RealmSwift/Error.swift

/// The RLMError value, which can be used to derive the error's code.
private var rlmError: RLMError {
    switch self {
     case .Fail:
       return RLMError.Fail
    case .FileAccess:
        return RLMError.FileAccess //should be **RLMError.FileAccessError**
     case .FilePermissionDenied:
            return RLMError.FilePermissionDenied
     case .FileExists:
          return RLMError.FileExists
....

**Comment by jpsim** [comment]
It looks like your version of Realm Objective-C is out of sync with Realm Swift. `RLMError.FileAccessError` was renamed to `RLMError.FileAcces` in f16de82.

**Comment by leetr** [comment]
I didn't do anything manually, installed it via cocoapods
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'

**Comment by jpsim** [comment]
Since Realm Swift depends on Realm Objective-C, their versions have to match, so if you change one, you need to change the other:

```ruby
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'
```

**Comment by leetr** [comment]
@jpsim thank you
I didn't have Realm in my podfile, only RealmSwift.
