### ISSUE TITLE
Realm NSPredicate 'LIKE'

### ISSUE THREAD

**Issue by lisaMel** [realm/realm-cocoa#3127]
Does Realm support 'LIKE' for NSString properties of models?

**Comment by lisaMel** [comment]
*** Terminating app due to uncaught exception 'Invalid operator type', reason: 'Operator 'LIKE' not supported for string type'

**Comment by mrackwitz** [comment]
`LIKE` is not supported by Realm yet. We track adding support for that by #1490. You might be able to use `BEGINSWITH`, `ENDSWITH` or `CONTAINS` meanwhile, which are supported as seen in our [NSPredicate cheatsheet](https://realm.io/news/nspredicate-cheatsheet/#string-comparison-operators).

**Comment by valeriyvan** [comment]
Thank you for really handy cheatsheet.

**Comment by wilferrel** [comment]
Cheatsheet includes LIKE which makes it confusing..

**Comment by jpsim** [comment]
The cheatsheet is for `NSPredicate` in general, but there are pink dots for the queries supported by Realm.

![image](https://cloud.githubusercontent.com/assets/474794/20719519/033ae546-b611-11e6-9c52-da4a3e2f708a.png)
