### ISSUE TITLE
XCODE Instability with Realm

### ISSUE THREAD

**Issue by jeeftor** [realm/realm-cocoa#3134]
I'm not exactly sure how i can be helpful - however I've noticed since adding realm to my projects XCODE becomes a crash-monkey-of-doom.

I've tried with `Xcode 7.2` and `Xcode 7.3 beta`

I'm seeing lots of:

`ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-9542/DVTFoundation/Protocols/DVTInvalidation.m:410`

messages.  

Is there any way I can help track down what is causing these issues?  SourceKit is pretty much crashing non-stop and the IDE itself crashes non stop.

The debugger is a total disaster also - pretty much any print or po command of realm or non realm object is crashing.  I've tried playing with the `.lldbinit` or whatever the file is called to disable the realm scripts but its still just a huge mess.

I'm happy to dig around but if somebody could point me what to look at that would be useful.

**Comment by jpsim** [comment]
This will happen if you use a prebuilt version of Realm Swift compiled with a different version of the Swift compiler than the version Xcode has. I encourage you to build the Realm frameworks from source using the same version of Xcode as your project to avoid this.

The easiest way to do this is to install Realm using CocoaPods or Carthage.

Let us know how that goes!

**Comment by jeeftor** [comment]
I am using Carthage however I believe I have to pass an extra flag to say don't use prebuilt

**Comment by jpsim** [comment]
These smell to me like Swift or Xcode bugs, especially with the SourceKit crashes. Have you filed a radar at https://bugreport.apple.com or https://bugs.swift.org?

**Comment by TimOliver** [comment]
Hi @jeeftor!

Just pinging this issue to see if there's anything more we can do here. Are you still experiencing this issue with Carthage? Did you file a Radar in the end?

Please let us know so we can clear up this issue. Thanks!

**Comment by jeeftor** [comment]
Honestly i'm not working on the realm code at the moment - so its kind of out of sight - out of mind.  We can close this out for the time being i guess.

I think the latest Xcode did help a bit - i didn't really notice a difference from building from source or using the binary release.

sorry
