### ISSUE TITLE
Notification.didPropertyChange possible?

### ISSUE THREAD

**Issue by kbala** [realm/realm-cocoa#3140]
Hi, I have seen we have Notification.didChange is available for any change in Realm. can we differentiate  the notification when a property get changed?

Thanks

**Comment by kishikawakatsumi** [comment]
We will be adding finer grained notifications in a future release. The most commonly requested feature has been changelist notification for queries. Once we support this you can register for a notification on an RLMArray to get a list of objects which were added, removed, or changed in position during a transaction. If we also added the list of objects whose properties were changed, would this work for your purposes? https://github.com/realm/realm-cocoa/issues/601

**Comment by kbala** [comment]
I guess so. For my case i also need a notification for when new row inserted into. is it already exist?

**Comment by jpsim** [comment]
> i also need a notification for when new row inserted into.

If you're inserting into an `RLMArray` property, you can observe that using [KVO](https://realm.io/docs/objc/latest/#key-value-observation). For all other use cases, you'll need general fine-grain notifications support, which is being tracked as #601.

**Comment by TimOliver** [comment]
Hi @kbala!

We recently [released Realm Objective-C and Realm Swift 0.98](https://realm.io/news/realm-objc-swift-0.98.0/) that allows you to now assign notification blocks/closures directly to Realm Array objects to be notified when their contents are modified. I encourage you to check this feature out to see if it fits your implementation needs.

If not, we're still working hard on the fine-grain notification system and should have that ready to go in the near future.

I'm closing this issue now. Please feel free to open it again if you have any additional queries.
