### ISSUE TITLE
Getting file not found when compiling my swift code

### ISSUE THREAD

**Issue by mustafa-almulla** [realm/realm-cocoa#3141]
I have an ios app written in swift, and i am using RealmSwift to save my data, before upgrading to the latest release the app was running fine, but after upgrading to realmswift 0.97 It started getting this issue every time i try to run the app

> Pods/Realm/include/realm/string_data.hpp:33:10:
> 'realm/util/features.h' file not found

Pods/Realm/Realm/ObjectStore/object_schema.cpp:19:10: In file included from Pods/Realm/Realm/ObjectStore/object_schema.cpp:19:

Pods/Realm/include/realm/object_schema.hpp:22:10: In file included from Pods/Realm/include/realm/object_schema.hpp:22:
ios swift realm

**Comment by jpsim** [comment]
Hi @mustafa-almulla, are you using a release candidate of CocoaPods 1.0 by any chance? If so, please note that Realm only supports the latest stable version of CocoaPods (0.39.0) and that we're tracking adding support for CocoaPods 1.0 in #3052.

If you're already using CocoaPods 0.39.0, you can reset your pods installation by running the following commands, which should reinstall Realm successfully:

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

If this still doesn't help your situation, please report back providing more information following our [guidelines](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues).

Thanks!

**Comment by jpsim** [comment]
Closing assuming my assessment is correct.

**Comment by mustafa-almulla** [comment]
Thanks it was related to cocoapod 1.0 release, and i have followed the solution provided in the issue #3052
