### ISSUE TITLE
Unable to debug in AppCode & Xcode with v0.97.0

### ISSUE THREAD

**Issue by lamson** [realm/realm-cocoa#3146]
I struggled figuring out why just importing Realm.framework and RealmSwift.framework v0.97.0 using Carthage broke the IDE debugger. I don't even have any files in my new projects that make use of Realm yet.
Basically, running the app in the debugger will stop at the first break point, then I can't step over, step into, etc. anymore (in AppCode). I tried it in Xcode and similar issue happened, adding a new expression watching o variable caused my Xcode to crash...

Maybe the latest version has something that interferes with the debugger. I updated my Cartfile to use Realm v0.96.3 and my debugger is now working again...

**Comment by tgoyne** [comment]
Are you using the prebuilt framework with Carthage? The Swift debugger is only guaranteed to work if all frameworks are built with the exact same version of the compiler, and we probably upgraded the version of Xcode on our build servers between 0.96.3 and 0.97.0.

**Comment by lamson** [comment]
Yes I'm using Carthage to fetch and build the frameworks. Is there a quick way to check if all frameworks are built with the same version of the compiler? Here's my Cartfile content
`github "DaveWoodCom/XCGLogger"
github "SnapKit/SnapKit"
github "dekatotoro/SlideMenuControllerSwift"
github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON"
github "realm/realm-cocoa"
`
I am using the latest versions of all the frameworks... so if realm-cocoa v0.97 conflicts with any of the others then my debugger is useless now.

**Comment by tgoyne** [comment]
You can use `carthage bootstrap --no-use-binaries` to force Carthage to build all of your dependencies from source. See https://github.com/Carthage/Carthage/issues/924 for more info on why this is needed.

**Comment by TimOliver** [comment]
Hi @lamson!

Hopefully Thomas' recommendations helped you fix your Carthage integration issues. 
I'm going to close this issue, but if you're still having issues, please feel free to open it again. Thanks!
