### ISSUE TITLE
Integrating KVOMapping with Realm...

### ISSUE THREAD

**Issue by ambujshukla** [realm/realm-cocoa#3148]
Hello All,

I tried to integrate KVOMapping with Realm but it is giving nil value inside the Realm Object...Please have a look on this...

**Comment by mrackwitz** [comment]
Can you please clarify what you mean by "KVOMapping" and where you're receiving nil instead of which expected value? A reproducible sample or a snippet from the concerned model might help us understanding your issue.

**Comment by TimOliver** [comment]
Hi @ambujshukla! We're still waiting with bated breath to hear back from you! :)

Did you manage to solve the issue you were having with KVO on your own in the end? If not, can you please provide us with some more information, and if possible a sample of your code?

Thanks!

**Comment by ambujshukla** [comment]
Extremely Sorry for the late response...I was talking about this --- https://github.com/dchohfi/KeyValueObjectMapping... When I try to merge both i.e Realm and KVOMapping...The data inside model class is nil....

**Comment by TimOliver** [comment]
Hi @ambujshukla! No problems at all!
Ahhh, it's a third party library! Alright then!

Hmm, I'm not too sure then. If `KeyValueObjectMapping` is in charge of instantiating the actual object, it's possible it's not setting the `RLMObject` up properly, or failing to properly insert the values.

Do you have a sample app you could send us for us to examine?

Additionally, if all else fails, is there a particular reason why you're using that particular library? If you're doing JSON mapping to a Realm Object, there are other libraries out there, like [Realm-JSON](https://github.com/matthewcheok/Realm-JSON) that we can already confirm work really well! :)

Thanks a lot!

**Comment by mrackwitz** [comment]
Hi again @ambujshukla, were you able to further investigate or even resolve this issue based on the feedback from @TimOliver?

**Comment by jpsim** [comment]
@ambujshukla we're closing this since we haven't heard back from you in a while. Please open a new issue referencing this one, along with more information following the issue template and we'll be happy to take another look!
