### ISSUE TITLE
"[[ZtyHomeWorkContent allObjectsInRealm:realm] count] "  cause  an assertion (top_size).

### ISSUE THREAD

**Issue by codesourse** [realm/realm-cocoa#3149]
2016-01-28 15:04:04.479 XHEnglishBrushStudent[6314:1879418] doJudgeDownloadDBOprate
group.cpp:187: [realm-core-0.94.0] Assertion failed: top_size == 3 || top_size == 5 || top_size == 7 [7419467, 3, 7419467, 5, 7419467, 7]
0   XHEnglishBrushStudent               0x005ae8ef _ZN5realm4util18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 86
1   XHEnglishBrushStudent               0x006504a7 _ZN5realm4util9terminateImJimimiEEEvPKcS3_lT_DpT0_ + 738
2   XHEnglishBrushStudent               0x0064e70b _ZN5realm5Group6attachEm + 698
3   XHEnglishBrushStudent               0x00653e91 _ZN5realm11SharedGroup13do_begin_readENS0_9VersionIDE + 364
4   XHEnglishBrushStudent               0x00653643 _ZN5realm11SharedGroup10begin_readENS0_9VersionIDE + 34
5   XHEnglishBrushStudent               0x005132b5 -[RLMRealm getOrCreateGroup] + 92
6   XHEnglishBrushStudent               0x004788d7 -[RLMObjectSchema table] + 86
7   XHEnglishBrushStudent               0x0047fa35 RLMGetObjects + 268
8   XHEnglishBrushStudent               0x0046ec39 +[RLMObject allObjectsInRealm:] + 172
9   XHEnglishBrushStudent               0x0057ce75 -[ZtyHomeWorkContentDao checkDataExist] + 108
10  XHEnglishBrushStudent               0x0056e9ff -[ExamDownloadManager judgeHaveDatas] + 446
11  XHEnglishBrushStudent               0x0056daaf -[ExamDownloadManager doJudgeDownloadDBOprate] + 122
12  XHEnglishBrushStudent               0x0056d9d9 __45-[ExamDownloadManager execDBDataFileCompress]_block_invoke + 2480
13  libdispatch.dylib                   0x00e42173 _dispatch_call_block_and_release + 10
14  libdispatch.dylib                   0x00e4ad67 _dispatch_queue_drain + 1718
15  libdispatch.dylib                   0x00e44a61 _dispatch_queue_invoke + 88
16  libdispatch.dylib                   0x00e4cb09 _dispatch_root_queue_drain + 1308
17  libdispatch.dylib                   0x00e4de19 _dispatch_worker_thread3 + 100
18  libsystem_pthread.dylib             0x338ffdc1 _pthread_wqthread + 668
19  libsystem_pthread.dylib             0x338ffb14 start_wqthread + 8
IMPORTANT: if you see this error, please send this log to help@realm.io.

**Comment by bdash** [comment]
Which version of Realm are you seeing this with?

**Comment by codesourse** [comment]
version   0.96.2

**Comment by bdash** [comment]
We believe this was fixed in v0.96.3, released towards the start of December last year. Could you please update to the latest version and see whether it addresses the problem?

**Comment by jpsim** [comment]
Closing since we expect this to have been fixed some time ago and never heard back from @codesourse
