### ISSUE TITLE
Why this framework has to be on Embedded Binaries to work? 

### ISSUE THREAD

**Issue by marioduran** [realm/realm-cocoa#3151]
This framework is giving us a lot of headaches because it only works if it is on Embedded Binaries on the project target, and it doesn't work if you add it like a normal framework... 
![screen shot 2016-01-28 at 12 59 14 pm](https://cloud.githubusercontent.com/assets/3925863/12655531/f824ffc2-c5be-11e5-8370-c9638b804830.png)

**Comment by bdash** [comment]
An embedded framework is one that is both linked to and copied into your application's bundle. The framework needs to be copied into the application bundle in order to be available at runtime.

What problems are you experiencing?

**Comment by marioduran** [comment]
Oh! I was hoping that it was some kind of issue building the realm framework, I didn't know that it needs to be on embedded binaries to work (Something I wanted to avoid), sorry guys!
and thanks a lot for the explanation!
