### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#3156]
Hi guys,

I released a new version of my app today and got a bigass crash affecting all my users directly when starting the app.
Any ideas?

```
Thread : Crashed: com.apple.main-thread
0  MyApp                       0x1006884d4 realm::_impl::transaction::advance(realm::SharedGroup&, realm::ClientHistory&, realm::BindingContext*) (transact_log_handler.cpp:227)
1  CoreFoundation                 0x180b68efc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
2  CoreFoundation                 0x180b68990 __CFRunLoopDoSources0 + 540
3  CoreFoundation                 0x180b66690 __CFRunLoopRun + 724
4  CoreFoundation                 0x180a95680 CFRunLoopRunSpecific + 384
5  GraphicsServices               0x181fa4088 GSEventRunModal + 180
6  UIKit                          0x18590cd90 UIApplicationMain + 204
7  MyApp                       0x1000f1e7c main (main.m:33)
8  libdispatch.dylib              0x1806368b8 (Missing)
```

**Comment by tgoyne** [comment]
This was probably fixed by https://github.com/realm/realm-cocoa/pull/3078. A new stable release including this fix should be out today.

**Comment by hitendradeveloper** [comment]
Have you changed something in your Realm Model Classes ? if you have added new properties or deleted some properties, you have to provide migration.

**Comment by tspecht** [comment]
@hitendradeveloper no I didn't, otherwise there would have also been an exception thrown when first trying to access to Realm which would say so. @tgoyne will try out that fix.

**Comment by jpsim** [comment]
@tspecht did you get a chance to try out the fix?

**Comment by jpsim** [comment]
I'm closing this since we haven't heard back from @tspecht in a while and expect this to have been fixed. @tspecht please reopen if you experience this with Realm 0.98.1 or later.
