### ISSUE TITLE
Cocoapods leaves me unable to run workspace project

### ISSUE THREAD

**Issue by reduxdj** [realm/realm-cocoa#3158]
<img width="387" alt="screen shot 2016-01-29 at 11 40 18 am" src="https://cloud.githubusercontent.com/assets/322547/12686235/6517f6c0-c67d-11e5-9565-d0da7391d7d3.png">

**Comment by jpsim** [comment]
Hi @reduxdj, are you using a release candidate of CocoaPods 1.0 by any chance? If so, please note that Realm only supports the latest stable version of CocoaPods (0.39.0) and that we're tracking adding support for CocoaPods 1.0 in #3052.

If you're already using CocoaPods 0.39.0, you can reset your pods installation by running the following commands, which should reinstall Realm successfully:

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

If this still doesn't help your situation, please report back providing more information following our [guidelines](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues).

Thanks!

**Comment by swinghu** [comment]
I also meet the same problem.

**Comment by MickeyHub** [comment]
I failed with `realm/realm.h not found` for 1.0 pre release version, but 0.39.0 version is OK

**Comment by MickeyHub** [comment]
Hi, @swinghu, I guess some build setting has value before pod install, so it override Pod's xcconfig's some setting value. Did you create a demo project to test this issue?

**Comment by jpsim** [comment]
> then error message 
> Object.swift : Printable has been rename to CustomStringConvertible
> redunctant conformance of object to proc .....

@swinghu please be sure to specify the latest version of RealmSwift (0.98). That error would be happening if you're trying to build Realm for Swift 1.2.

**Comment by TimOliver** [comment]
I think this issue has been suitably resolved! Like we've mentioned in our installation documentation, please refrain from using the release candidate versions of CocoaPods 1.0 to install Realm for the time being.

Additionally, as of Realm Swift 0.98, support for Swift versions below 2.0 has been dropped. Please keep this in mind when integrating it into your projects.

Feel free to re-open this issue if you wish to add additional follow-up! Thanks! :)

**Comment by JoeFerrucci** [comment]
Just updated Cocoapods version from 0.39.0 to 1.0.1 -- my project was stable and building previously, but now its broken:

`realm/util/features.h` *file not found*

@jpsim @TimOliver

**Comment by jpsim** [comment]
@JoeFerrucci we added CocoaPods 1.0.x support in Realm 0.98.3. [See our changelog for that entry](https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md#0983-release-notes-2016-02-26).

**Comment by JoeFerrucci** [comment]
@jpsim I updated to latest Realm version (1.0.2) and its building fine now. Thanks

**Comment by JoeFerrucci** [comment]
@jpsim I'm getting this error:

<img width="241" alt="screen shot 2016-07-26 at 5 24 54 pm" src="https://cloud.githubusercontent.com/assets/2114494/17159924/efac14f0-5355-11e6-9c95-bb69147b8ab7.png">

**Comment by jpsim** [comment]
Have you followed the instructions on https://realm.io/docs/objc/latest/#reinstalling-via-dependency-managers ?

**Comment by JoeFerrucci** [comment]
@jpsim Yes, I did.

**Comment by JoeFerrucci** [comment]
I added `${POD_ROOT}/**` to the User Header Search Paths, and that's when this started happening.

**Comment by jpsim** [comment]
@JoeFerrucci to continue helping you, we'll need a complete bug report, so could you please open a new issue, taking care to fill out the issue template, providing full steps to reproduce? I'll be happy to take a closer look.
