### ISSUE TITLE
RLMArray array property inside a swift Class is not allowed

### ISSUE THREAD

**Issue by Carpemeid** [realm/realm-cocoa#3161]
So basically I have a Swift class which inherits from Object and which has a property of RLMArray type. When this needs to be added to realm it stops at the point of calling "internal func listForProperty(prop: RLMProperty) -> RLMListBase" and fails because the propery's "swiftIvar" is nil.

I need it as an RLMArray rather then a List, because I cannot apply predicates to the List type, being a Swift class. For example I cannot apply a NSPredicate which contains @count.

And I cannot make it through other Swift provided means because I'm using RBQFetchedResultsController which for querying objects accepts basically just the old NSPredicate.

**Comment by jpsim** [comment]
Mixing the Realm Swift API with the Realm Objective-C API is unsupported. From [our docs](https://realm.io/docs/swift/latest/):

> If you’re looking to use Realm from Objective-C, or from mixed Objective-C & Swift apps please see Realm Objective-C instead.
> Using both Realm Objective-C and Realm Swift simultaneously is not supported.

---

> I need it as an RLMArray rather then a List, because I cannot apply predicates to the List type, being a Swift class. For example I cannot apply a NSPredicate which contains @count.

This is a bug, which we're tracking as #3115. If you try to work around a bug by doing something we explicitly don't support, you'll have a hard time. The right thing to do here is to fix #3115, which we've prioritized as highly as we can.

In the meantime, you can work around the lack of KVC operator support for `List` properties by performing the equivalent calculations with objects at the language level.

**Comment by Carpemeid** [comment]
Anyways.. for somebody who is also newie to using predicates. Use "ANY" when you need to address a Swift List presence of items.

**Comment by TimOliver** [comment]
I think this issue has been resolved sufficiently. Please feel free to re-open it if you require additional follow-up! :)
