### ISSUE TITLE
How can an object become invalidated?

### ISSUE THREAD

**Issue by jinmin888** [realm/realm-cocoa#3163]
>*** Terminating app due to uncaught exception 'RLMException', reason: 'Object has been deleted or invalidated.'

When I use `po` to inspect the object, it printed 'invalid object'. I don't know what invalidated the object?

**Comment by jinmin888** [comment]
i don't know what made object invaliaded?

**Comment by jpsim** [comment]
From our [API docs](https://realm.io/docs/objc/latest/api/Classes/RLMObject.html#/c:objc(cs)RLMObject(py)invalidated):

> An object can no longer be accessed if the object has been deleted from the containing realm or if `invalidate` is called on the containing realm.

**Comment by TimOliver** [comment]
Hi @jinmin888!

I think this issue has been sufficiently resolved. Please make sure to check the logic of your app, and ensure you're not inadvertently deleting this Realm Object before you're supposed to.

Feel free to re-open this issue if you have additional queries!
