### ISSUE TITLE
Received error on index_set.hpp file not found

### ISSUE THREAD

**Issue by mofodox** [realm/realm-cocoa#3168]
Hello,

I received an index_set.hpp file saying that the file not found, I've updated to the latest version of Realm. The previous version was doing great. 

[Here's the screenshot of the error](http://imgur.com/0eecFhe)

Cocoapods version: 0.39.0 (Latest Stable)
RealmSwift version: 0.97.1 (Latest)

**Comment by hdoria** [comment]
Same here. Seems like https://github.com/realm/realm-cocoa/issues/1859.

**Comment by jpsim** [comment]
This rather seems like the same issue reported in #3159, which I believe to be a CocoaPods and/or Xcode cache invalidation issue. I've suggested some workarounds there.

**Comment by mofodox** [comment]
@jpsim Yep your reply on #3159 really fixed it. Thank you! ;)
