### ISSUE TITLE
Uncaught exception: +[RLMAccessor exception

### ISSUE THREAD

**Issue by pepibumur** [realm/realm-cocoa#3170]
### What?
I've the following scenario on my app:
- **Framework A**:
  - Models `Repository` and `Label` with the relationships defined as shown below:

```swift
final public class Repository: Object {
    public var labels: [Label] {
        return linkingObjects(Label.self, forProperty: "repository")
    }
}
final public class Label: Object  {
    public dynamic var repository: Repository?
}    
```
- **Framework B**
  - It depens on framework A
  - It uses Realm models defined in A

When I try to map the labels of a given repository from B I get the following exception:

```
Uncaught exception: +[RLMAccessor_v0_Label name]: unrecognized selector sent to class 0x7fa73457ff00
2016-02-02 23:53:07.616 Gitdo[79148:1053140] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RLMAccessor_v0_Label name]: unrecognized selector sent to class 0x7fa73457ff00'
```
It seems to be a bug with Realm when working with multiple frameworks.

Thanks for your help.

**Comment by jpsim** [comment]
Is it possible you've linked the Swift files where this model is defined in both frameworks? If so, that could be a manifestation of https://realm.io/docs/swift/latest/#avoid-linking-realm-and-tested-code-in-test-targets

Otherwise, does this issue also manifest itself if `Repository` has persisted properties of its own? I'm assuming you just omitted them from this example, but Realm won't persist objects with no persisted properties, so I just want to confirm that.

**Comment by pepibumur** [comment]
Hello @jpsim 
Thanks for your help, the model `Repository` is currently defined only in one framework. The framework is integrated into the app as `Embedded Framework` using CocoaPods *(I'mt not sure if there might be something wrong with how CocoaPods embeds the framework)*.

Regarding the persisted properties no, the entire model is shown below:

```swift
final public class Repository: Object, Mappable {
    
    // MARK: - Attributes
    
    public dynamic var id: String = ""
    public dynamic var name: String = ""
    public dynamic var fullName: String = ""
    public dynamic var isPrivate: Bool = false
    public dynamic var isFork: Bool = false
    public dynamic var desc: String = ""
    public dynamic var openIssues: Int = 0
    public dynamic var language: String = ""
    public dynamic var hasIssues: Bool = false
    public dynamic var owner: Collaborator?
    public var collaborators: List<Collaborator> = List<Collaborator>()
    public dynamic var source: String = "github" // Default

    public var issues: [Issue] {
        return linkingObjects(Issue.self, forProperty: "repository")
    }
    
    public var labels: [Label] {
        return linkingObjects(Label.self, forProperty: "repository")
    }
    
    override public static func primaryKey() -> String? {
        return "id"
    }
}
```

**Comment by pepibumur** [comment]
@jpsim more useful info:
If I use the `.map` operator to adapt the relationship elements then I get that error but if I iterate through the Realm relationships using a `for` bucle then it works.

**Comment by jpsim** [comment]
I created a sample project from the information you shared here and was unable to reproduce the issue you've described. Could you please take a look at https://github.com/jpsim/RealmGH3170 to let me know if there's anything I missed when creating the project that would allow us to trigger the behavior you're experiencing?

Ideally, please make a PR towards the project that makes the unit test fail or crash.

**Comment by jpsim** [comment]
@pepibumur we still haven't heard back from you since posting an attempt at a repro case over two weeks ago, so we're closing this issue.
