### ISSUE TITLE
deleteAllObjects make the database empty but the same file size ??

### ISSUE THREAD

**Issue by almujtaba** [realm/realm-cocoa#3176]
I've a database full of data and images, its size became 93MB, so I decided to clear it using **deleteAllObjects** ...
it became empty when I open it in the **Realm Browser**, but it still has the same size 93MB .. 

![a](https://cloud.githubusercontent.com/assets/7612635/12829870/61b62a5e-cb9d-11e5-953d-e66d520ef9ab.png)
![bb](https://cloud.githubusercontent.com/assets/7612635/12829879/66db8ac4-cb9d-11e5-8394-0f110e350623.png)

I'm using Objective-C with the latest Realm version at the moment (0.97.1)
Here is my code :
```
RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[realm deleteAllObjects];
[realm commitWriteTransaction];
```

So what's wrong ?? and is there any way to empty the database and reset its size file without deleting it ??

**Comment by jpsim** [comment]
Hi @almujtaba, this is behaving as designed. Expanding files on a file system is an expensive operation, so when data is removed from a Realm, that space is marked as available for new data, which can then quickly be written to that area without requiring more expensive calls to system APIs to continuously shrink & expand the file.

If reclaiming that disk space is important to you, you can write a compacted copy of the file using [`-[RLMRealm writeCopyToPath:error:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)writeCopyToPath:error:) and use the new copy, discarding the old one, but this requires you to stop accessing the Realm file at the previous path altogether.

**Comment by JonathanADaley** [comment]
@almujtaba There is an explanation of file size, and some fixes for large file size, in the "Current Limitations" section, "File size & tracking of intermediate versions" sub-section, of the Ream docs: https://realm.io/docs/objc/0.97.1/#current-limitations It mentions @jpsim 's suggestion for compacting, and also mentions issues that can arise from intermediate versions of data, and when using Grand Central Dispatch.

**Comment by TimOliver** [comment]
This issue appears to have been sufficiently resolved.

@almujtaba If you have any additional follow-up, please feel free to re-open this issue! :)
