### ISSUE TITLE
Warning: Multiple build commands for output file

### ISSUE THREAD

**Issue by minikin** [realm/realm-cocoa#3178]
I've just updated to Realm 0.98 (via Pods) and now I have these two  warnings in Xcode 7.2.1:

> Check dependencies
> 
> Warning: Multiple build commands for output file /Users/Minikin/Library/Developer/Xcode/DerivedData/appName-dabrczkkehpfzsdbpumeqbbdscji/Build/Products/Debug-iphonesimulator/Realm.framework/PrivateHeaders/cached_realm.hpp
> Warning: Multiple build commands for output file /Users/Minikin/Library/Developer/Xcode/DerivedData/appName-dabrczkkehpfzsdbpumeqbbdscji/Build/Products/Debug-iphonesimulator/Realm.framework/PrivateHeaders/external_commit_helper.hpp

Thank you.

**Comment by yosuke1985** [comment]
me too..
![screen shot 2016-02-05 at 21 29 24](https://cloud.githubusercontent.com/assets/7687894/12846393/b3212a3a-cc4f-11e5-8da2-b7b0ea7b766c.png)

**Comment by xcplanet** [comment]
Me too. There are two external_commit_helper.hpp files in the path, one under include/realm/impl/apple /and one under include/realm/impl/. Same for cached_realm.hpp.

**Comment by NSUserDefaults** [comment]
Same problem here. @xcplanet solution works but a cleaner one will be appreciated ;)

**Comment by barfoon** [comment]
Same problem here, can confirm fix from @xcplanet works as well

**Comment by IsmailHassanein** [comment]
same like @barfoon

**Comment by iantheparker** [comment]
+1

**Comment by jpsim** [comment]
We have a fix under review in #3188 which we intend to include in our next point release as soon as possible, likely today or tomorrow. Thanks for your patience as we resolve this.

**Comment by marcoscurvello** [comment]
+ 1
