### ISSUE TITLE
How to use LIKE Operator in Realm at the time of query.

### ISSUE THREAD

**Issue by anandkumarsharma** [realm/realm-cocoa#3179]
I am getting problem related to LIKE operator, at the time of Queries.

I have this query in sqlite3:

   NSString *sqlQuery = [NSString stringWithFormat:@"SELECT * FROM ServiceAccountsTbl WHERE      serviceModes LIKE '%%%@%%'",serviceMode];

  Query of above sqlQuery :
        SELECT * FROM ServiceAccountsTbl WHERE serviceModes LIKE '%Email%'

Equivalent of above query, I have tried in Realm as follows:

 RLMResults *allResults;

 NSPredicate *pred = [NSPredicate predicateWithFormat:@"serviceModes LIKE[c] %@",serviceMode];
 allResults = [ServiceAccountsModel objectsWithPredicate:pred];

But i am not getting success, please help.

**Comment by mrackwitz** [comment]
`LIKE` is not supported yet as operator in NSPredicates by Realm, as seen in #1490. In general please refer to our [predicate cheatsheet for an overview of supported operators](https://realm.io/news/nspredicate-cheatsheet/).
For your specific query here, it seems like you could easily workaround this limitation by falling back to using just the `CONTAINS` operator like that:
```objc
[NSPredicate predicateWithFormat:@"serviceModes CONTAINS %@", serviceMode];
```
