### ISSUE TITLE
Sort RLMCollection by keypath

### ISSUE THREAD

**Issue by smolskyaleksey** [realm/realm-cocoa#3180]
Hi everyone.I have this error "Terminating app due to uncaught exception 'Invalid sort property', reason: 'Cannot sort on 'messages[LAST].timestamp': sorting on key paths is not supported.'"
Could you help, how can I fix it? I have RLMCollection of chat objects and i want to sort it by last message.

**Comment by mrackwitz** [comment]
As the assert message describes, you can't fix that, you hit a feature limitation. We track adding support for this functionality by #1277. As long you would need to workaround that. Depending on the size of the collection, a feasible solution could be to pull your objects from the lazy `RLMCollection` into memory and handling the sorting via `NSArray` (e.g. by using `[coll valueForKeyPath:@"@self"]`). Alternatively, you could store the timestamp of the last message on your model, which holds the relation to messages.

**Comment by smolskyaleksey** [comment]
Thank you, very much.I also thought about the last solution. I decided to check, maybe there is some other solution.

**Comment by mrackwitz** [comment]
You're welcome. But in general we try to direct these kind of questions to StackOverflow, which we actively monitor as well. :wink:
