### ISSUE TITLE
App crashing when I add more than 9 variables to class

### ISSUE THREAD

**Issue by bibicfilip** [realm/realm-cocoa#3181]
When I added 10th variable the app started crashing as you can see on the image below
![screenshot at feb 05 18-36-07](https://cloud.githubusercontent.com/assets/6416956/12853979/6a2d19e6-cc37-11e5-8df5-1ee3ee1adbf2.png)

Here is the image of error

![x0gdryu](https://cloud.githubusercontent.com/assets/6416956/12854012/90d021c4-cc37-11e5-87b3-7d723603f9a5.png)

**Comment by FilipBibic** [comment]
P.S. Even if I try to make it optional with : String, it doesn't work either way.

**Comment by mrackwitz** [comment]
That seems to me to be an issue with your application logic. Where and how do you initialize your `datasource`?

**Comment by bibicfilip** [comment]
I created new project and copied everything, now it works fine.

**Comment by mrackwitz** [comment]
Thanks for reporting back.
