### ISSUE TITLE
terminating with uncaught exception of type realm::LogicError: Attempted to insert null into non-nullable column

### ISSUE THREAD

**Issue by kurko** [realm/realm-cocoa#3184]
I didn't find anything on Google about this. It's either new or I'm really bad at googling.

_How can I debug this?_

### Context

Basically, I was using `0.96.2`. Once I updated to `0.98.0`, my tests started failing. I started deleting code until I got to a point very close to the code below: just no meaningful code.

I downgraded to `0.96.2` and the error persisted (after Cmd+k). I'm using CocoaPods 0.39.

### The error

I get this error:

```
Checking in...
libc++abi.dylib: terminating with uncaught exception of type realm::LogicError: Attempted to insert null into non-nullable column
```

### The code

```swift
import UIKit
import XCTest
import RealmSwift

class MyClassTests: XCTestCase {
    var realm: Realm!
    
    override func setUp() {
        super.setUp()
        realm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "MyInMemoryRealm"))
    }
    
    override func tearDown() {
        super.tearDown()
        realm = nil
    }

    func testMyFunction() {
        let expectation = expectationWithDescription("testSynchronizeRemotely")

        // nothing here
        print("Checking in...")

        waitForExpectationsWithTimeout(10) { error in
            // waiting here on purpose
            XCTAssertNil(error, "\(error)")
        }
    }
}
```

I don't even know where to start debugging.

**Comment by bdash** [comment]
The exception you quote ("Attempted to insert null into non-nullable column") is raised when a property that is not marked as nullable (optional) has its value set to null. You can track down which operation triggered this exception by using an [exception breakpoint in Xcode](http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions). Looking up the call stack from the point where the exception is raised should reveal some of your app's code that is triggering the problem. Feel free to share a screenshot of the stack trace if it's still not clear what's causing the issue.

**Comment by kurko** [comment]
Thanks @bdash. So I found the issue after a week debugging. I new to XCode.

The problem was that XCode was showing the error to be in a place that wasn't the real error place, so I was being misled.
