### ISSUE TITLE
Compilation warning using realm 0.98

### ISSUE THREAD

**Issue by jplazcano87** [realm/realm-cocoa#3191]
i'm having this compilation warning with swift realm, im using cocoapods instalation and no other weird config, also my final build is way too big up to 50 mb just for adding realm

![captura de pantalla 2016-02-09 a las 12 48 02 p m](https://cloud.githubusercontent.com/assets/3168897/12929163/155ff3c2-cf50-11e5-824f-a251f96fda6f.png)

**Comment by beseder42** [comment]
Can confirm this: Warning and size increased from around 11 MB to 75 MB.

**Comment by jplazcano87** [comment]
this warning was fixed, thanks! im closing this issue
