### ISSUE TITLE
Installed RealmSearchViewController and now it gives error

### ISSUE THREAD

**Issue by bibicfilip** [realm/realm-cocoa#3192]
I just installed search view controller and now I cannot work because of error you can see in screenshot.

http://prntscr.com/a1d0wx

**Comment by bigfish24** [comment]
How is the search view controller installed?

**Comment by bibicfilip** [comment]
Via cocoapods

**Comment by bigfish24** [comment]
Which versions are mentioned in your `podfile.lock`. My recommendation would be to make sure you are on the latest versions for `Realm` and `RealmSearchViewController`.

**Comment by bibicfilip** [comment]
I installed the latest version of Realm along with Searchviewcontroller, as it says in documentation.

**Comment by mrackwitz** [comment]
@bibicfilip: Sorry that this got stuck. We would need here just a little bit more information to act on. If you didn't got it working so far, I'd recommend to try it with the latest prerelease of CocoaPods. If that still shouldn't help, please feel free to ask back here or even better on StackOverflow, what we actively monitor to assist in help related issues. Thanks for your understanding.
