### ISSUE TITLE
Mention in docs that ignored properties do not benefit from the single-instance-autoupdating magic

### ISSUE THREAD

**Issue by skensell** [realm/realm-cocoa#3193]
I just spent a long while debugging some unusual behavior with my `User` subclass of `RLMObject`. In the end I came to the rather obvious conclusion that _ignored properties do not autoupdate and you should avoid them_. Let me elaborate on my confusion:

Being the good Realm citizen that I am, I didn't want to pass my `User` all over the place, rather its primaryKey ID, something which is threadsafe.  So I have a Database class which encapsulates a lot of Realm logic and ultimately calls `[User createOrUpdateInRealm:[RLMRealm defaultRealm] withValue:dictionary];` where `dictionary` has the primaryKey inside.

My mistake was that I tried to override `createOrUpdateInRealm:withValue:` to re-derive the properties I'm ignoring. This, however, had no effect on my `User` object being held elsewhere in the app, waiting for updates.  That object did receive new values for the tracked properties, but not for the ignored properties.

I know it seems obvious in retrospect, but there should definitely be more than "Realm won’t interfere with the regular operation of these properties" in the docs.

**Comment by jpsim** [comment]
Thanks for the suggestion @skensell, what do you think the docs should say specifically to make this clearer?
