### ISSUE TITLE
Explain what a Realm collection is and how it is used.

### ISSUE THREAD

**Issue by nosrak113** [realm/realm-cocoa#3196]

**Comment by jpsim** [comment]
@nosrak113 it would really help if you offered more context when filing issues.

In this case, this was brought up earlier today when discussing the concept of "Collection Notifications" introduced in Realm 0.98, and that although we document those, we don't really make a point of defining what we mean by collections in Realm.

We might want to have this as a subsection in "Models", or even as a top-level section in the docs describing all the types of collections and collection interfaces in Realm: `RLMArray`/`List`, `RLMResults`/`Results`, `RLMCollection`/`RealmCollectionType` and `AnyRealmCollection`.

**Comment by jpsim** [comment]
Done: https://realm.io/docs/swift/latest/#collections
