### ISSUE TITLE
Crash when having two realms with different schemes.

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#3200]
Once again, I apologize for not being able to provide an isolated reproducible project for this.

I have two distinct realms inside the app:

```
private lazy var realm: Realm = {
    var configuration = Realm.Configuration.defaultConfiguration
    configuration.objectTypes = [A1.self, A2.self, A3.self, A4.self, A5.self, A6.self, A7.self, A8.self, A9.self, A10.self, A11.self, A12.self]
    configuration.migrationBlock = {
        migration, oldSchemaVersion in
        if oldSchemaVersion < 1 {
            // migration stuff
        }
        if oldSchemaVersion < 2 {
            // migration stuff
        }
    }
    return try! Realm(configuration: configuration)
}()

// note that the in-memory realm contains ALL Realm subclasses inheriting from Object
private lazy var inMemoryRealm: Realm = {
    let configuration = Realm.Configuration(path: nil, inMemoryIdentifier: "someIdentifier", encryptionKey: nil, readOnly: false, schemaVersion: 0, migrationBlock: nil, objectTypes: nil)
    return try! Realm(configuration: configuration)
}()
```

Now the crucial part is the instantiation order. 

If you instantiate the in-memory Realm first ```void Schema::validate() const``` is called having 22 ```ObjectSchema```s. This number includes both the 12 classes that are marked to be persisted inside the regular Realm as well as the 10 others that are only used by the in-memory Realm. Then ```validate``` is called for the persistent Realm having 12 ```ObjectSchema``` classes as expected. There is no problem here and everything is working fine.

However, if you instantiate the persistent Realm first, then its schema is validated having 12 ```ObjectSchema``` classes as expected. But when the in-memory Realm is instantiated, its schema is validated but it contains *only* 10 ```ObjectSchema```s. Then an exception is thrown by ```exceptions.emplace_back(MissingObjectTypeException(object.name, prop));``` stating that:

```
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=0 "Migration is required due to the following errors: 
- Target type 'A6' doesn't exist for property 'user'." UserInfo={
    NSLocalizedDescription = "Migration is required due to the following errors: \n- Target type 'A6' doesn't exist for property 'user'.";
}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.1.101.15/src/swift/stdlib/public/core/ErrorType.swift, line 50
```

**Comment by tgoyne** [comment]
I can hit something like this with the following code:

```
class C1: Object {
    dynamic var prop = 0
    var ignoredLink = C2()

    override class func ignoredProperties() -> [String] { return ["ignoredLink"] }
}

class C2: Object {
    dynamic var link: C1? = nil
}

func test() {
    let c1 = Realm.Configuration(inMemoryIdentifier: "c1", objectTypes: [C1.self])
    let c2 = Realm.Configuration(inMemoryIdentifier: "c2")

    let r1 = try! Realm(configuration: c1)
    let r2 = try! Realm(configuration: c2)
}
```

The key problematic part is the fact that `C1`'s zero-arg initializer creates an instance of `C2`, resulting in the full schema initialization happening in the middle of the partial schema initialization for the explicit set of types. If none of the classes in your persisted subset do anything like that, then this is probably unrelated to your issue, but I'll take a stab at fixing it anyway just in case.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-cocoa/pull/3208 should render the specific symptoms that you're seeing completely impossible, but since it just fixes a pile of kinda-maybe-related bugs it may just shift how problems manifest.

**Comment by anlaital** [comment]
Getting a compiler error from the branch:

```
Pods/Realm/Realm/RLMSchema.mm:160:44: error: member reference type 'struct objc_class *' is a pointer; maybe you meant to use '->'?
            schema->_objectSchemaByName[cls.className] = RLMRegisterClass(cls);
                                        ~~~^
                                           ->
Pods/Realm/Realm/RLMSchema.mm:160:45: error: no member named 'className' in 'objc_class'
            schema->_objectSchemaByName[cls.className] = RLMRegisterClass(cls);
                                        ~~~ ^
2 errors generated.
```

**Comment by tgoyne** [comment]
Fixed that. I wish I knew what makes dot notation on Class sometimes work and sometimes not, since it works when building via the xcode project but not when building via cocoapods on my machine.

**Comment by anlaital** [comment]
Retested from the branch and the crash is gone. @tgoyne thanks a lot, once again! :+1:
