### ISSUE TITLE
Deadlock accessing realm objects from different threads

### ISSUE THREAD

**Issue by zintus** [realm/realm-cocoa#3201]
I'm using realm notification block to read updates from database on background thread. Having many NSThreads, access to realm objects deadlock.

This issue appeared first in 0.98.0, and reproducible in 0.98.1. Right now i'm using 0.97.1 which is working fine in my case.

[deadlock.txt](https://github.com/realm/realm-cocoa/files/126803/deadlock.txt)

**Comment by schwa** [comment]
Bump

**Comment by bdash** [comment]
`RealmCoordinator::advance_to_ready` calls out to user code with `m_query_mutex` locked (by way of `transaction::advance` resulting in Realm change notifications being dispatched). When the notification block executes a query that we determine should be updated asynchronously, `RealmCoordinator::register_query` will be called and will attempt to re-lock `m_query_mutex`.
