### ISSUE TITLE
Ordering results on multiple properties

### ISSUE THREAD

**Issue by Alamoz** [realm/realm-cocoa#3205]
The Sorting section of realm-swift documentation states:

"Results allows you to specify a sort criteria and order based on a single or multiple properties."

The example only shows sorting on a single property. I need to order results on multiple properties, to produce the same result as the plain old SQL:  "select * from some_table order by foo, bar". Is this possible with Realm and if so what is the syntax? I've tried chaining sorted() properties to no avail.

It would be a really good idea to add an example to the documentation. Thank you!

**Comment by bdash** [comment]
The section of the documentation that you mention contains links to the API documentation for [`Results.sorted(_:ascending:)`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sorteduRdq_CS_6Object_FGS0_q__FTSS9ascendingSb_GS0_q__) and [`Results.sorted(_:)`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sortedu__Rdq_CS_6Objectqd__Ss12SequenceTypezqqqd__S2_9GeneratorSs13GeneratorType7ElementVS_14SortDescriptor_FGS0_q__Fqd__GS0_q__). The latter takes a sequence of [`SortDescriptor`s](https://realm.io/docs/swift/latest/api/Structs/SortDescriptor.html), representing the properties to sort by. Using that could look something like:

```swift
// Sort tan dogs with names starting with "B" from oldest to youngest, then by name
let dogs = realm.objects(Dog).filter("color = 'tan' AND name BEGINSWITH 'B'")
let sortedDogs = dogs.sorted([SortDescriptor(property: "age", ascending: false), "name"])
```

**Comment by Alamoz** [comment]
Thank you @bdash that works. It wasn't clear to me when looking at the API doc. One good example does a lot to clear things up.

**Comment by Gerst20051** [comment]
I agree @Alamoz that is the only useful example that I've found... 👍

**Comment by thonydam** [comment]
+1

**Comment by jpsim** [comment]
@thonydam FYI this is currently supported
