### ISSUE TITLE
Bundling a Realm with an App works only on second build

### ISSUE THREAD

**Issue by bibicfilip** [realm/realm-cocoa#3206]
I'm trying to use preloaded database, everything builds with no errors but nothing comes up in the app, when on second build it works normally.

Here is the screenshot of the code used to bundle preloaded database with app.

![screenshot at feb 12 09-30-29](https://cloud.githubusercontent.com/assets/6416956/13002001/496d0b38-d16b-11e5-88fb-008791285370.png)

Also, I did everything from documentation I could find. I added the source to copy bundle resources as well as added target.

**Comment by mrackwitz** [comment]
I guess you open your Realm for the first time in your view controller's initializer or `viewDidLoad` method. These are called before `application(_ didFinishinLaunchingWithOptions: _)` is executed, when you use storyboards and don't provide custom logic to initialize the initial view controller. Solutions here would be to delay the initialization of the first Realm instance after that (`viewWillAppear` might be appropriate), rely on some kind of notification mechanism instead or explicitly initialize the initial view controller from the `AppDelegate`.
