### ISSUE TITLE
Text search in to-many tables in swift

### ISSUE THREAD

**Issue by mrsaif** [realm/realm-cocoa#3207]
Ok I am new to realm. In realm I think full-text search is not supported. I wan to search text in 2 tables. I have following tables. 

>Member(firstName, lastName, location, contacts:List)
>Contact(type, name, value)

I am using following query to search members.

```swift
realmObj.objects(Member).filter("firstName BEGINWITH[c] '(txtSearch.text!)' OR lastName BEGINWITH[c] '(txtSearch.text!)' OR location BEGINWITH[c] '(txtSearch.text!)'")
```

above query is working and returning results. I also want to search the same text in Contact table in and get all the members where name, and value begins with the search text. one way is to have member object in contact table and perform separate filter to get matching members.. and also I have to combine both results so that member records do not repeat.

Is there a way to perform search in one filter/query? I need to do it because my member and contact data might grow to 10000 records.

**Comment by bigfish24** [comment]
I would recommend you perform a search on the `Member` objects but include a `SUBQUERY` on the contacts array:

``` swift
Realm().objects(Member).filter("firstName BEGINWITH[c] 'SEARCHSTRING' OR SUBQUERY(contacts, $contact, $contact.name BEGINSWITH[c] 'SEARCHSTRING').@count > 0")
```

This allows you to search the `Member` objects for any object in which a text field begins with the search text or that one of its `Contact` objects' name property begins with the search text.

**Comment by mrackwitz** [comment]
As we didn't heard back here, I assume we can close this issue. If there should be still any question, please feel free to ask again (while we prefer StackOverflow for help related issues).
