### ISSUE TITLE
Failable initializer crashes for realm objects

### ISSUE THREAD

**Issue by Igor-Palaguta** [realm/realm-cocoa#3211]
I am using realm 0.98.1,  have following failable initializer

```
   convenience init?(message: [String: AnyObject]) {
      guard let x = message["x"] as? Double else {
            return nil
      }
```

When init returns nil this code crashes (EXC_BAD_ACCESS) with stack:
```
#0	0x0000000180b0953c in pthread_mutex_lock ()
#1	0x000000010188489c in realm::Table::unregister_row_accessor(realm::RowBase*) const ()
#2	0x000000010187d908 in realm::RowBase::impl_detach() ()
#3	0x00000001016ff3c8 in realm::BasicRow<realm::Table>::~BasicRow() at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa-master/core/include/realm/row.hpp:761
#4	0x000000018050eb54 in object_cxxDestructFromClass(objc_object*, objc_class*) ()
#5	0x000000018051a080 in objc_destructInstance ()
#6	0x00000001028215b4 in swift_deallocUninitializedClassInstance ()
```

**Comment by tgoyne** [comment]
This looks like a Swift bug to me. The base class's destructor is run even if you return before calling the designated initializer, which will then generally crash because it's operating on uninitialized garbage data. As a workaround you'll need to call `self.init()` before returning.

**Comment by tgoyne** [comment]
Filed a swift bug: https://bugs.swift.org/browse/SR-745

**Comment by jpsim** [comment]
Closing as I believe the Swift bug is now fixed.
