### ISSUE TITLE
Provide API docs in Dash (docset) format.

### ISSUE THREAD

**Issue by hungri-yeti** [realm/realm-cocoa#3214]
If possible, please provide the API docs in Dash docset format. Information regarding the conversion can be found at https://kapeli.com/docsets.

Thank you.

**Comment by jpsim** [comment]
You can install Realm's docs in Dash by clicking the "Install in Dash" link in the upper right corner of our API docs:

* Objective-C: https://realm.io/docs/objc/latest/api/
* Swift: https://realm.io/docs/swift/latest/api/

![image](https://cloud.githubusercontent.com/assets/474794/13055355/b9207bf4-d3c3-11e5-873f-2898b23ace66.png)
