### ISSUE TITLE
Update docs to reflect the proper way to set NSFileProtection attributes

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3223]
We currently recommend to set them on the main Realm file and all auxiliary files in the [Encryption](https://realm.io/docs/objc/latest/#encryption) section of the docs.

In reality, we should be recommending that they be set on the Realm file's parent directory and that a subdirectory should be used if there are other files in that directory that shouldn't share those same attributes.

We should also update that section since those attributes are already set to encrypt the file by default as of iOS 8 (I *think*), so it's currently incorrect.

**Comment by sxua** [comment]
Confirming. Avoid setting file protection attributes on iOS 8+ otherwise Realm file won't be accessible on a second launch.

**Comment by jpsim** [comment]
This was done in https://github.com/realm/realm.io/pull/1791 and is now available at https://realm.io/docs/swift/latest/#using-realm-with-background-app-refresh
