### ISSUE TITLE
mmap() failed: Cannot allocate memory size

### ISSUE THREAD

**Issue by JSONValidator** [realm/realm-cocoa#3226]
I try to save in my Realm a lot of data, but after downloading and saving some data I get this error: 
```Terminating app due to uncaught exception 'RLMException', reason: 'mmap() failed: Cannot allocate memory size: 738197504 offset: 0'```

I tried to make another Realm path with ```writeCopyToPath``` method and use it, but have the same result.
<img width="391" alt="screenshot 2016-02-16 20 22 13" src="https://cloud.githubusercontent.com/assets/5711059/13086278/39d85956-d4eb-11e5-912f-a277758bdf9a.png">

Can you explain me, how can I compress data?

ViewController:
```
for (NSInteger i = 0; i < json.count; i++) {
     [Product parseWithData:((NSMutableArray *)json)[i]];
}
```

Product.m:
```
+ (NSString *)primaryKey
{
    return @"xml_id";
}

+ (Product *)parseWithData:(NSDictionary *)dictionary {
    
    Product *product = [[Product alloc] init];
    product.xml_id =  [dictionary[@"XML_ID"] isKindOfClass:[NSString class]] ? dictionary[@"XML_ID"] : @"";
    product.name = [dictionary[@"name"] isKindOfClass:[NSString class]] ? dictionary[@"name"] : @"";
       
    [[RLMRealm defaultRealm] beginWriteTransaction];
    [[RLMRealm defaultRealm] addOrUpdateObject:product];
    [[RLMRealm defaultRealm] commitWriteTransaction];

    return product;
}
```

**Comment by bdash** [comment]
Are you storing around 1GB of data in the Realm file, or is the ~1GB file size much larger than you expect?

Writing a copy of the Realm can reduce the file size in some cases, but typically only if the Realm contains unused space due to having deleted a large amount of data or having updated large objects.

**Comment by JSONValidator** [comment]
Yes, i am storing around 1 GB.

**Comment by bdash** [comment]
One of [Realm's current limitations](https://realm.io/docs/objc/latest/#current-limitations) is that a Realm file cannot be larger than the amount of memory your application would be allowed to map in iOS. The exception you're seeing occurs when iOS denies Realm's attempt to map further memory, indicating that you've reached the maximum file size we support for that device. There are a few ways you can attempt to work around this limitation:

1. Split your data across multiple Realms, being sure to close those you're not actively using to minimize memory usage.
2. Compress your data within the Realm (using zlib, for example) to reduce the amount of space consumed by larger properties.

If you can share further information about the types of data you're storing, or even a sample dataset, we can provide more specific advice. If you're not comfortable sharing this information publicly feel free to do so privately by emailing help@realm.io and referencing this GitHub issue.

**Comment by mrackwitz** [comment]
@JSONValidator: Were you able to resolve the issue by what @bdash proposed here in his comment or by any other measures you took?

**Comment by jpsim** [comment]
@JSONValidator we're closing this issue since we haven't heard back from you in a while.

**Comment by qianweicheng** [comment]
I get this error too, the DB is about 200+M
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=1 "mmap() failed: Cannot allocate memory size: 234881024 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 234881024 offset: 0, Error Code=1}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.1/src/swift/stdlib/public/core/ErrorType.swift, line 54

**Comment by konradzuwala** [comment]
Guys, I think the issue is still open. We are using the newest version of Realm available and we still get:
`CRASH_INFO_ENTRY_0
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.63/src/swift/stdlib/public/core/ErrorType.swift, line 178`

**Comment by konradzuwala** [comment]
Our database is fairly small, few MB, Realm 2.4.4, Swift 3 project. Happened in earlier versions of Realm too.

**Comment by bdash** [comment]
Please file a new issue and provide all of the information requested in the new issue template.

**Comment by hyouuu** [comment]
This was also reported in https://github.com/realm/realm-cocoa/issues/4820 and https://github.com/realm/realm-cocoa/issues/4642 but no response from the Realm team yet
