### ISSUE TITLE
Accessing the first User object in Results array

### ISSUE THREAD

**Issue by istx25** [realm/realm-cocoa#3231]
Hi,

I have been trying to figure out how to solve this for almost the entire evening. I have created a static method on my "User" Realm object as so:

```swift
static func currentUser() -> User? {
    return try! Realm().objects(User).first
}
```

I am wanting this method to act similarly to how `PFUser.currentUser` works in the sense that I can do the following:

```swift
guard let user = User.currentUser() else {
    // User does not exist, explain what happened
    return
}

// Do something with the user
```

But...I'm experiencing weird behaviour that I can't seem to debug. You can clone the project at http://www.github.com/istx25/delta (on the `ux-improvements-and-user-object-fix` branch) and try it yourself, but essentially the steps to reproduce are:

1. Follow the login flow. (Get Started → Fill out form → Pick Country)
2. Look at Console.

The first view controller after completing registration has the following in `viewDidLoad()`:

```swift
guard let user = User.currentUser() else {
    // User does not exist, explain what happened
    return
}

// Print the user object directly
print("Full: \(User.currentUser()!)")
        
// Print the individual properties
print("Name: \(user.name)")
print("Location: \(user.location?.name)")
print("Email: \(user.email)")
print("ObjectId: \(user.objectId)")
```

The console spits out:
```bash
Full: User {
	name = First Last;
	location = (null);
	email = first.last@demo.ca;
	password = demo_password;
	objectId = l89Z58DS8;
}

Name: nil
Location: nil
Email: nil
ObjectId: nil
```

My question is "Why?" Why are all of the *individual property* print statements printing nil when printing the full User object prints the accurate information?

Related Links: 

- My User Object - <https://github.com/istx25/delta/blob/master/Delta/Model/User.swift>
- The UIViewController - <https://github.com/istx25/delta/blob/ux-improvements-and-user-object-fix/Delta/Controller/ViewController.swift>

I'm sure I've just overlooked something, but if anyone could point me in the right direction—I would personally give you an internet hug. :dancer:

**Comment by bdash** [comment]
The properties on your model need to be declared with `dynamic var` rather than just `var`. Without the `dynamic` keyword Realm's getters and setters are not called, so accessing the properties does not access the data stored in the Realm.

**Comment by istx25** [comment]
Ah. Yes. Thank you, @bdash. Adding `dynamic` fixed the issue. :+1:

**Comment by istx25** [comment]
Where do I send the internet hug? :wink: But seriously... thank you!

**Comment by bdash** [comment]
Happy to help!
