### ISSUE TITLE
Error while installing in cocoapods

### ISSUE THREAD

**Issue by archerLj** [realm/realm-cocoa#3232]
i have tried many times and the error is always here:

[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.96.1
Downloading core failed:
curl: (56) SSLRead() return error -9806

Xcode : Version 7.2 (7C68)
cocoapods : 1.0.0.beta.2

any idea?

**Comment by juggernate** [comment]
You need to use the latest stable cocoapods 0.39.0 see #3052

**Comment by archerLj** [comment]
the error is still there even i use cocoapods 0.39.0

my cocoapods info:
cocoapods (0.39.0)
cocoapods-core (0.39.0)
cocoapods-downloader (0.9.3)
cocoapods-plugins (0.4.2)
cocoapods-search (0.1.0)
cocoapods-stats (0.6.2)
cocoapods-trunk (0.6.4)
cocoapods-try (0.5.1)

the error info:
Installing Realm (0.98.2)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.96.1
Downloading core failed:
curl: (56) SSLRead() return error -9806

**Comment by Jeff-F** [comment]
same issue.  use cocoapods 0.39.0

**Comment by mrackwitz** [comment]
Sorry for the inconveniences here, but currently it seems not possible to use CocoaPods to use Realm from China as seen in https://github.com/realm/realm-cocoa/issues/2713. You would need to use our prebuilt binaries.

**Comment by offbye** [comment]
I have same question
