### ISSUE TITLE
-addOrUpdateObject method name

### ISSUE THREAD

**Issue by kubatru** [realm/realm-cocoa#3233]
Shouldn't it be `addOrReplaceObject` since it compares primary keys and if the object already exists, it will replace it?

We can partially update objects with the `createOrUpdateInRealm` method, but this seem like a clear replacement.

**Comment by nafetswirth** [comment]
+1 I assumed the same behaviour and it took my quite some time to figure out that the object was replaced

**Comment by jpsim** [comment]
`addOrUpdateObject` is an accurate description of what the method does:

1. Adds the object if no existing object with matching primary key exists.
2. Updates the existing object with matching primary key with all the values of the passed object.

This behaves identically to `+[RLMObject createOrUpdateInRealm:]`, although with that method, it's also possible to use other objects with a subset of the properties like a dictionary or array.

We've considered allowing untyped objects for `addOrUpdateObject` too, but ultimately decided that wasn't worth the loss of this typed API.

So thanks for the suggestion, but we stand by our decision to name this method `addOrUpdateObject` for consistency, discoverability and not to mention introducing a breaking API change if we rename it for all existing users.
