### ISSUE TITLE
Object is already persisted in a Realm

### ISSUE THREAD

**Issue by codesourse** [realm/realm-cocoa#3236]
2016-02-18 11:16:54.224 XHEnglishBrushTeacher[1360:310571] <INFO> Bugly: Catch uncaught exception:

RLMException Object is already persisted in a Realm 
 (
	0   CoreFoundation                      0x25ee0007 <redacted> + 150
	1   libobjc.A.dylib                     0x34191c8b objc_exception_throw + 38
	2   XHEnglishBrushTeacher               0x00421d2b RLMAddObjectToRealm + 310
	3   XHEnglishBrushTeacher               0x004bd3c3 -[RLMRealm addOrUpdateObject:] + 406
	4   XHEnglishBrushTeacher               0x004bd579 -[RLMRealm addOrUpdateObjectsFromArray:] + 292
	5   XHEnglishBrushTeacher               0x00521f37 -[ZtyHomeWorkContentDao insertOrUpdate:] + 150
	6   XHEnglishBrushTeacher               0x0050c3b7 -[DownloadExamContentHelper updateAllData] + 594
	7   XHEnglishBrushTeacher               0x0050cf01 -[DownloadExamContentHelper onRequestResult:] + 2112
	8   XHEnglishBrushTeacher               0x00524c0f -[ZtyRequestHelper asyncPerform:withObject:withReceiver:] + 150
	9   XHEnglishBrushTeacher               0x005294af __84-[ZtyRequestHelper requestRsyncHomeWorkExamUpdateWithExParam:rsId:hoId:forReceiver:]_block_invoke + 930
	10  XHEnglishBrushTeacher               0x0052ffc1 __32-[XHDataModel TryIpUrl:ipArray:]_block_invoke + 1248
	11  XHEnglishBrushTeacher               0x0052b3ad __97+[NetRequestClass PostRequestWithRequestURL:WithParameter:WithReturnValeuBlock:WithFailureBlock:]_block_invoke82 + 136
	12  XHEnglishBrushTeacher               0x00284ff9 __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke49 + 36
	13  libdispatch.dylib                   0x00df6173 _dispatch_call_block_and_release + 10
	14  libdispatch.dylib                   0x00e00c39 _dispatch_root_queue_drain + 1612
	15  libdispatch.dylib                   0x00e01e19 _dispatch_worker_thread3 + 100
	16  libsystem_pthread.dylib             0x34863dc1 _pthread_wqthread + 668
	17  libsystem_pthread.dylib             0x34863b14 start_wqthread + 8
)
2016-02-18 11:16:54.228 XHEnglishBrushTeacher[1360:310673] *** Terminating app due to uncaught exception 'RLMException', reason: 'Object is already persisted in a Realm'
*** First throw call stack:
(0x25edffef 0x34191c8b 0x421d2b 0x4bd3c3 0x4bd579 0x521f37 0x50c3b7 0x50cf01 0x524c0f 0x5294af 0x52ffc1 0x52b3ad 0x284ff9 0xdf6173 0xe00c39 0xe01e19 0x34863dc1 0x34863b14)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by bdash** [comment]
This error is thrown when you're adding an object that is already present in a Realm to a different Realm. In other words, one or more of the objects in the array passed to `-[RLMRealm addOrUpdateObjectsFromArray:]` are already associated with a different Realm (perhaps a Realm from a different thread, or a Realm at a different path on disk).

**Comment by mrackwitz** [comment]
@codesourse: Were you able to resolve the crash on base of @bdash's comment here?

**Comment by jpsim** [comment]
@codesourse we're closing this issue because we haven't heard back from you in over three weeks since posting some explanations as to what is likely causing this exception to be thrown.

**Comment by girishnair12345** [comment]
Hi,

I am getting this error
*** Terminating app due to uncaught exception 'RLMException', reason: 'Object is already persisted in a Realm'
*** First throw call stack:
(0x181c2adb0 0x18128ff80 0x1011ad784 0x101787bcc 0x100136140 0x101789adc 0x10128ea64 0x1017876f4 0x1001315a0 0x100131298 0x1000cfe04 0x1000d1e34 0x1001958e8 0x1002631f8 0x1000922f0 0x102199a7c 0x102199a3c 0x1021a6554 0x10219d72c 0x102199a3c 0x1021a8c9c 0x1021a8364 0x18188d470 0x18188d020)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jpsim** [comment]
@girishnair12345 please make sure you've read our [docs on Updating Objects](https://realm.io/docs/swift/latest/#updating-objects) and if you still need help, please file a new issue taking care to fill out the issue template and we'll take a closer look.

**Comment by girishnair12345** [comment]
Ya its same though I found a work around , it seems calling update on an object whose content is changed is causing this issue, I have dont and equals check before updating, it seems to be working fine now
