### ISSUE TITLE
Warn developers about the perils of misplaced build phases when building with Carthage

### ISSUE THREAD

**Issue by Bogidon** [realm/realm-cocoa#3237]
I wasted many hours trying to fix this error:
![6d48a05d-0636-4b8d-a89f-715dbde36204](https://cloud.githubusercontent.com/assets/3252307/13133998/69b1d794-d5cf-11e5-891e-0e0dd47ad997.jpg)

It turns out that I had placed the `Run Script` phase **above** my `Embed Frameworks` phase in my watchOS target. It's a silly mistake, but it's easy enough to make and potentially annoying to debug. (`Applications... require an iOS Development Target of 3.0 or later` really? ) 

I think it would be useful to warn developers about this. I suggest an addition like this to [the docs](https://realm.io/docs/swift/latest/#carthage-install) (my contribution is the section in yellow):
![c214fd6e-2af2-45bc-895b-5a486c8e1223](https://cloud.githubusercontent.com/assets/3252307/13134344/436122da-d5d3-11e5-81a9-133180b49be2.jpg)

I would submit a PR, but I think the docs might not be on GitHub?

**Comment by Bogidon** [comment]
Tagging so devs can find this solution in the future.
- `ITMS-90081: This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later.`
- `ITMS-90209: Invalid Segment Alignment. The app binary at __ does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.`
- `ITMS-90125: The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.`

**Comment by jpsim** [comment]
Thanks for the suggestion, I updated our installation steps to emphasize this. It should be live in a few minutes.

**Comment by Bogidon** [comment]
Great! :smile:
