### ISSUE TITLE
Realm syncronization after background transaction

### ISSUE THREAD

**Issue by dave-trudes** [realm/realm-cocoa#3239]
I want to use Realm transactions in combination with promises (eg. PromiseKit).
Following example:

```swift
 func sync() -> Promise<Void> {
	return Promise { fulfill, reject in
		dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0)) {
			
			// Retrieve realm instance for background thread 
			// Execute realm transaction
			
			dispatch_async(dispatch_get_main_queue()) {
				// How to make sure realms are syncronized before fulfilling the promise?
				fulfill()
			}
		}
	}
}
```

**Comment by anohren** [comment]
I have the same question. I'm getting assertion failures on the state of my objects because they're probably not in sync with previous tasks on the same serial queue.

**Comment by mrackwitz** [comment]
Really sorry, totally missed to answer here somehow!
Make sure to explicitly call `refresh` on **any** Realm instance with the same configuration opened on the main thread when you're going to keep the runloop blocked by activity which needs an immediate update. Please note that you don't need to use the exactly same `Realm` instance as those are cached under the hood per thread and path. This doesn't apply exclusively to the main thread, but in most cases you have only there a runloop running, which is needed for the autorefreshs. On background threads, you will need to call therefore `refresh` manually, if you keep accessors around and write from different threads.

```diff
dispatch_async(dispatch_get_main_queue()) {
     // How to make sure realms are synchronized before fulfilling the promise?
+    try! Realm().refresh()
     fulfill()
}
```

**Comment by mrackwitz** [comment]
Closing this now, assuming this could be resolved. If you have any questions left, feel free though to comment again or ask on StackOverflow, what we prefer in general for Help related questions.

**Comment by anohren** [comment]
Thank you, your answer resolved my issue at least.
