### ISSUE TITLE
Ream Swift: how to create inverse many to many relationship with itself?

### ISSUE THREAD

**Issue by JosephZZ** [realm/realm-cocoa#3241]
In my application I need to link similar photos with each other, so i need to set up many to many relationship and the inversely pointing to each other. I don't find any person talking about this. Is there an established way to do it? If not, I come up with two ways to do it but I'm not sure it'll work or it's a good way to do it. They are:
1>
```
class Photo : Object{
     var similarPhotos : [Photo]{
          return linkingObjects(Photo.self, forProperty: "similarPhotos")
     }
}
```

For this way, firstly I don't know if it would cause any problem for referring to itself. Secondly, suppose it works, I don't know whether it can still work when trying to write to it, aka whether this call `photo.similarPhotos.insert(newPhoto, atIndex:0)` works, since there's no place to store the similarPhotos value.

2> 
```
class Photo:Object{
     private var privateSimilarPhotos = List<Photo>()
     var similarPhotos : [Photo]{
         get {return linkingObjects(Photo.self, forProperty: "privateSimilarPhotos")}
         set {privateSimilarPhotos.insert(newValue.first!, atIndex: 0)}
     }
}
```

This way sounds more likely to function, but then I'm confused how should I write to it. Since it's using get-set, does that mean I have to call something like `photo.similarPhotos = [newPhoto]` instead of  `photo.similarPhotos.append(newPhoto)`? If i have to use the first way it would cause a lot of confusion since its appearance looks like it's assigning the whole array as this new array that only contains only `newPhoto`, but actually it's appending it.

**Comment by jpsim** [comment]
Links in Realm are *unidirectional*. In other words, there must be a source object and a target object. You can't have links with no "owner" like you're attempting in both your approaches.

If you're always going to be setting the `similarPhotos` on each object, then you don't need inverse relationships, since the link will always explicitly be set:

```swift
class Photo: Object {
  let similarPhotos = List<Photo>()
}
```

You could also update your data models to represent what you're looking for in an entirely different way. For example, if you group similar photos by "tag", you could have `similarPhotos` be dynamically generated:

```swift
class Photo: Object {
  let tags = List<Tag>()

  var similarPhotos: Results<Photo> {
    return realm.objects(Photo).filter("ANY tags IN %@", tags)
  }
}
```

I really encourage you to read the [Relationships](https://realm.io/docs/swift/latest/#relationships) section of our docs, especially the [To-Many](https://realm.io/docs/swift/latest/#to-many) and [Inverse Relationships](https://realm.io/docs/swift/latest/#inverse-relationships) subsections, which goes into all this in much more detail.

**Comment by JosephZZ** [comment]
Thanks! I think i got you. Just to clarify, I'm gonna repeat want i want and rephrase what I'm understanding:

What i'm looking for is that, when I set the similarPhotos of any specific photo, this specific photo will also be one of similarPhotos of the photos in its similarPhotos list. For example,
if I let `photoA.similarPhotos.append (photoB)`
then `photoB.similarPhotos` should contain photoA.

But basically Ream can't do that. Realm doesn't persist links. I can either manually persist myself, or I can use getter to retrieve the ones that satisfy the specified matching criteria. `linkingObjects` is not really "linking", but just a convenient getter provided by realm.

So the first way you mentioned needs me manually persist the relations.,That means I have to manually write something like `photoB.similarPhotos.append(photoA)` right? 

And the second way is using getter. I have to create a tag or hash id of every group of similar photos, and every time i just query the photos that share the same tag to find the ones it "links" to.

Am I correct?

**Comment by jpsim** [comment]
> But basically Ream can't do that.

Correct. Realm doesn't allow a `List` property (to-many relationship) to have both explicit and implicit links.

> Realm doesn't persist links.

Incorrect. Realm certainly persists links. When you say `photoA.similarPhotos.append(photoB)` you're permanently storing a link from `photoA` to `photoB`.

> `linkingObjects` is not really "linking", but just a convenient getter provided by realm.

Incorrect. `linkingObjects` gets all objects linking to this one in a "to-many" (`List<Object>`) to "to-one" (`Object`) property. So yes, `linkingObjects` gets all links to this objects from source objects of the given type & property.

> So the first way you mentioned needs me manually persist the relations.,That means I have to manually write something like photoB.similarPhotos.append(photoA) right?

Correct. To set a link, you must append/insert the linked-to object to the linking object's `List` property.

> And the second way is using getter. I have to create a tag or hash id of every group of similar photos, and every time i just query the photos that share the same tag to find the ones it "links" to.

This is just a recommendation to satisfy your end goal of having "pools" of similar photos while only adding a single photo at a time. Another way to do this would be to have a model of `SimilarPhotos`:

```swift
class SimilarPhotos: Object {
  let photos = List<Photo>()
}

class Photo: Object {
  var similarPhotos: SimilarPhotos? {
    return realm.objects(SimilarPhotos).filter("photos CONTAINS %@", self).first
  }
}

let photoA = Photo()
let poolA = SimilarPhotos()
poolA.photos.append(photoA)
```

> And the second way is using getter. I have to create a tag or hash id of every group of similar photos, and every time i just query the photos that share the same tag to find the ones it "links" to.

Correct.

> Am I correct? If so, does that mean using "links" will have a bad influence on the performance since every time I call it it's actually doing a query instead of directly go get the ones?

Correct, performing a query will generally be much more expensive then just getting backlinks via `linkingObjects`.

---

Hopefully this makes sense. I hope my examples of using other data model techniques won't throw you off!

**Comment by JosephZZ** [comment]
> Correct. Realm doesn't allow a List property (to-many relationship) to have both explicit and implicit links.
What do you mean by explicit and implicit links? What are they, how are they different, and how are they used?

And from your first reply, you said
> ... In other words, there must be a source object and a target object. You can't have links with no "owner" like you're attempting in both your approaches.
Can you clarify what do you mean by "owner"? It seems to me in the second approach, the link has an owner `privateSimilarPhotos`. What's wrong here?

Haha the techniques are nice! looks really useful and I will certainly explore more of it!

**Comment by JosephZZ** [comment]
still there?

**Comment by jpsim** [comment]
> What do you mean by explicit and implicit links? What are they, how are they different, and how are they used?

By explicit link, I mean setting a relationship explicitly: `photoB.similarPhotos.append(photoA)`

By implicit link, I mean getting a relationship set elsewhere: `linkingObjects(Photo.self, forProperty: "similarPhotos")`

So I'm saying you can't combine these behaviors into a single property.

Maybe instead of explicit and implicit, I should have called these outgoing & incoming links.

> Can you clarify what do you mean by "owner"? It seems to me in the second approach, the link has an owner `privateSimilarPhotos`. What's wrong here?

By "owner" I mean a property on an object, like your `privateSimilarPhotos` property. But that code sample won't work:

1. `var privateSimilarPhotos` should be `let privateSimilarPhotos`. Attempting to set a `List` property won't work, which is why we very strongly encourage that they be declared with `let`
2. `set {privateSimilarPhotos.insert(newValue.first!, atIndex: 0)}` will just insert the first value of the array set on `similarPhotos`, preserving all the old links too.

```swift
class Photo: Object {
  let similarPhotos = List<Photo>()
  var linkedSimilarPhotos : [Photo] {
    return linkingObjects(Photo.self, forProperty: "similarPhotos")
  }
}
```

or you could also do this to combine outgoing and incoming links:

```swift
class Photo: Object {
  let explicitSimilarPhotos = List<Photo>()
  var similarPhotos : [Photo] {
    return Array(explicitSimilarPhotos) + linkingObjects(Photo.self, forProperty: "similarPhotos")
  }
}
```

**Comment by JosephZZ** [comment]
> set {privateSimilarPhotos.insert(newValue.first!, atIndex: 0)} will just insert the first value of the array set on similarPhotos, preserving all the old links too.
Why it's preserving all the old links? Is it because I was using `insert`? Does it update links if i use `append`?

And for the second approach you give, it seems like the `similarPhotos` of the photo object it belongs to is returning all the photos its own `explicitSimialrPhotos` contains (we can all them children of this photo object) and all photos whose `explicitSimialrPhotos` contains this photo (we can all them parents of this photo). But it seems like the siblings that are not also simultaneously parents or children of this photo are missing. Correct?

If the above is correct, can I achieve the effect of getting all similar photos in something like:
```Swift
class Photo: Object {
  let explicitSimilarPhotos = List<Photo>()
  var similarPhotos : [Photo] {
    return getSimilarPhotos()
  }
  func getSimilarPhotos(){
       var allPhotos = self.explicitSimilarPhotos + linkingObjects(Photo.self, forProperty: "similarPhotos")
       for photo in linkingObjects(Photo.self, forProperty: "similarPhotos") {
           allPhotos += photo.explicitSimilarPhotos
       }
       get rid of duplicates in allPhotos
       return allPhotos
   }
}
```

It might be more complicated now than just creating another similarPhotos model that you proposed in the previous reply. But I would still like to know whether I'm thinking correctly to get a better understanding of how things work in Realm.

Thanks!

**Comment by jpsim** [comment]
Still not quite right. `linkingObjects` just works with Realm links. So because `similarPhotos` isn't a Realm link, you can't write `linkingObjects(Photo.self, forProperty: "similarPhotos")`.

So you could do this instead, but you'd have to be mindful of the quadratic complexity and circular references:

```swift
class Photo: Object {
  let explicitSimilarPhotos = List<Photo>()
  var similarPhotos: Set<Photo> {
    let similarPhotos = explicitSimilarPhotos + linkingObjects(Photo.self, forProperty: "explicitSimilarPhotos")
    let secondDegreeSimilarPhotos = similarPhotos.flatMap { $0.similarPhotos }
    return Set(similarPhotos + secondDegreeSimilarPhotos)
  }
}
```

But really, you're *wayyyy* better off with the `SimilarPhotos` model I suggested earlier.

**Comment by JosephZZ** [comment]
haha yeah i see that too.
But I met the following problem when implementing the SimilarPhotos model:
```
Terminating app due to uncaught exception 'Invalid predicate', reason: 'Key paths that include an array property must use aggregate operations'
```
and the problem lies on this code
```Swift
    var similarPhotos: SimilarPhotos? {
        return realm!.objects(SimilarPhotos).filter("photos CONTAINS %@", self).first
    }
```

**Comment by bdash** [comment]
`CONTAINS` is a string comparison operator. I suspect you want `IN`.

**Comment by JosephZZ** [comment]
Can you show me the code? It's kinda tricky because it's something like `"SELF IN photos"`, but apparently this way doesn't work, and so neither `"SELF IN %@", "photos"` nor `"SELF IN %K", "photos"`

**Comment by bdash** [comment]
I think you want to use `filter("%@ IN photos", self)`, which is supported in v0.98.2 and newer.

Using the `SELF` keyword like you attempted would give you all `SimilarPhotos` objects that were also a member of their own `photos` array. That's a slightly different query than finding all `SimilarPhotos` objects where this particular object is present in the `photos` array. Note that the `SELF` keyword is not yet supported by Realm in predicates.

**Comment by jpsim** [comment]
@JosephZZ we're closing this issue because we haven't heard back from you in a while and I'm hoping that all the guidance we provided about how to model your data and craft queries for it has helped you along. Please let us know if there's anything more we can do for you by filing a new issue. Thanks!

**Comment by JosephZZ** [comment]
hey thank you and @bdash for the help!! i really appreciate it. And yes everthing is working now! 
I was going to respond but couldn't find the notification any more from my github page so I thought this question has been closed already. (apparently it is the first time that I post questions lol~~）
