### ISSUE TITLE
Delete Object with Relationship

### ISSUE THREAD

**Issue by hibento** [realm/realm-cocoa#3243]
Hi,

I noticed something strange (at least from my perspective), please take a look at this Example:

    class Person: Object {
     // ... other property declarations
     dynamic var owner: Dog
    }

Now I try to delete an Object of Type Person:

    try! realm.write {
      realm.delete(JohnDoe)
    }

When I open the Realm File, the Object JohnDoe is indeed removed, but his "Dog" is still there. I thought the Dog will be removed as well? Is there any option to delete an Object "deep", i.e. delete all associated Objects?

**Comment by hermanolsson** [comment]
@hibento Have a look at "Add support for cascading deletes" https://github.com/realm/realm-cocoa/issues/1186 - it was updated about a month ago.

**Comment by hibento** [comment]
@hermanolsson Thank you - I'll follow #1186
