### ISSUE TITLE
Migrations and auto releasing behave differently in 98.x?

### ISSUE THREAD

**Issue by GreatApe** [realm/realm-cocoa#3244]
In the latest versions of the ObjC bindings (used from Swift) it seems that migrations are harder to trigger. I am using Realm dynamically, but I presume there are deeper reasons for this.

In 96.3 I was able to simply do this after changing the schema dynamically:

        config.schemaVersion += 1
        RLMRealm.migrateRealm(config)

and it would run the migration.

Now I need to do this

        config.schemaVersion += 1
        RLMRealmConfiguration.setDefaultConfiguration(config)

within an autoreleasepool{} and then immediately open the realm again in another autoreleasepool, using `RLMRealm.defaultRealm()`.

In general it seems I need a lot of autoreleasepools in order to avoid getting some error like "realm is already opened with another schema version". Is it the case that Realms somehow release slower now?

I tested this in both Simulator and device.

Here is a gist of a test case AppDelegate using 98.1:
https://gist.github.com/GreatApe/4fd59c9a70dedb28ca83

And here the same thing for 96.3:
https://gist.github.com/GreatApe/75b43fb2723b4a6d2416

Just add Realm.framework and add `RLMRealm_Private` and `RLMRealm_Dynamic` to `Realm.h`. I also have two complete projects in DropBox.

**Comment by mrackwitz** [comment]
>I also have two complete projects in DropBox.

Ready to built sample projects are always welcome, so if you have them already, it would save us some time if you could share them with us. Feel free to just send us links privately to help@realm.io, if there might be anything confidential you don't want to share publicly.

**Comment by GreatApe** [comment]
Thanks, I've sent them using icloud maildrop. If that doesn't work I'll invite you to the dropbox, they do contain material under NDA from Realm.

**Comment by GreatApe** [comment]
Did you receive it? I've never tried the maildrop feature before.

**Comment by mrackwitz** [comment]
We got it. :+1:

**Comment by bdash** [comment]
This seems like something that may have changed as a result of @tgoyne's refactoring of Realm initialization into C++ code. @tgoyne, can you please take a look at this?

**Comment by GreatApe** [comment]
Thanks for looking into this. I have a hard time refactoring my actual project to work with 98.1, because I keep a semi-permanent reference to the Realm as an instance variable. Thus I can't use the autoreleasepool trick as far as I can tell.

Bonus question: Is the migration necessary in order to commit the schema change that I performed dynamically, or this there another way of doing that? I don't really need the migration block, I just want to save the new schema and bump the version.

**Comment by tgoyne** [comment]
0.98's behavior looks correct to me. The problematic code is (after inlining some function calls):

        autoreleasepool {
            let realm = try! RLMRealm.dynamicRealm("test")
            let prop = RLMProperty(name: "anotherString", type: .String, objectClassName: nil, indexed: false, optional: false)

            let objectSchema = realm.schema["MyClass"]
            objectSchema.properties += [prop]

            let config = realm.configuration
            config.schemaVersion = config.schemaVersion + 1
            let newVersion = config.schemaVersion
            config.migrationBlock = { migration, oldVersion in
                print("Migrating from \(oldVersion) to \(newVersion)")
            }

            RLMRealm.migrateRealm(config)
        }

This is explicitly trying to run a migration while the Realm is already open. The workaround of setting the default config is just a very roundabout way of pulling the call to migrateRealm out of the autoreleasepool, and thus after the Realm has been closed.

> Bonus question: Is the migration necessary in order to commit the schema change that I performed dynamically, or this there another way of doing that? I don't really need the migration block, I just want to save the new schema and bump the version.

The migration block is allowed to be `nil` if you don't need to do anything in it.

**Comment by GreatApe** [comment]
Thank you for the reply. 

> This is explicitly trying to run a migration while the Realm is already open

That makes sense, I didn't realise that was a problem. It seems that it actually worked in 96.3. I moved the migration outside the autoreleasepool block and it worked now.

Unfortunately it doesn't help much in my actual app, where the realm is an instance variable. No matter what I do, it doesn't seem to get released in time:

    var realm: RLMRealm!

    func migrate() {
        var config: RLMRealmConfiguration!
        
        autoreleasepool {
            config = realm.configuration
            config.schemaVersion += 1
            let newVersion = config.schemaVersion
            config.migrationBlock = { migration, oldVersion in
                print("Migrating \(oldVersion) -> \(newVersion)")
            }
            
            realm = nil
        }

        // Doesn't crash on open, but doesn't migrate
        RLMRealm.migrateRealm(config)
        realm = try! RLMRealm.dynamicRealm("store")
        
        // Crashes on open. "Realm at path already open
        RLMRealmConfiguration.setDefaultConfiguration(config)
        realm = RLMRealm.defaultRealm()

        print(realm.schema)
    }

This is in 98.2. I run this after dynamically adding a new RLMObject class. The first one doesn't crash, but also doesn't migrate. It's curious that the second one does crash. It seems to me that the realm being open or not should not depend on what's written after the pool?

Another thing, I can't really see how migration after a dynamic schema change can work! If I have to close the realm, how does it remember my (dynamically) updated schema? Is it persisted in the realm as soon as I change it? If so, how could option 1 above not crash?

**Comment by jpsim** [comment]
Sorry for the delay @GreatApe. As far as I can tell, because you're holding to a Realm instance outside the autoreleasepool, there's no guarantee that `dealloc` will be called when you set the variable to `nil` or when your explicit autoreleasepool is drained at the end of its scope.

Try calling `realm.invalidate()` before setting it to `nil`. It's a private method on `RLMRealm`, so you'll have to re-expose it in a category interface.

**Comment by jpsim** [comment]
I've posted a bit more on this topic in #3240.

**Comment by GreatApe** [comment]
Thank you for the reply. I have been trying very hard to make sure I'm not holding on to any realm instances, but I will have another try, and also test invalidate. 

The challenge with the actual design is of course that i would like the realm to be an instance variable, for performance reasons (I haven't actually tested the effect yet). Most of the time I'm accessing the same objects and "sub-objects" all the time, and reading more than writing, so I may try to cache the objects and only create an RLMRealm instance when I really need it, i.e. for writing or accessing previously unused objects.

**Comment by jpsim** [comment]
I understand the challenges involved here, so I'm sympathetic to your concerns, but I also don't see a clear solution without redesigning how Realm works and sacrificing some of the main advantages of the current design.

> but I will have another try, and also test invalidate.

I look forward to hearing how this works out for you!

**Comment by jpsim** [comment]
I don't think there's anything further to say on this. Closing.
