### ISSUE TITLE
How to use 'IN' operator in REALM.

### ISSUE THREAD

**Issue by anandkumarsharma** [realm/realm-cocoa#3247]
I have this query result in sqlite:

```sql
SELECT * FROM FileTable WHERE serviceAccountId IN ('480c44e1-ceb8-4b7e-be5c-7591afa50146','65883970-59e5-4263-ab42-1f72e9e7dac2','1ea5a5c9-fe1e-4f63-9ced-5cffe96cdb78','0208e25d-0226-4cd3-8d9e-c2317256a135') AND serviceParentFolderId = '  ' 
ORDER BY upper(name) ASC
```

same query result trying to find using Realm, The code are follows:-

```objc
RLMResults *allResults;

NSPredicate *pred = [NSPredicate predicateWithFormat:@"serviceAccountId IN %@ AND serviceParentFolderId = %@",strServiceAccounts,parentFolderId];

allResults = [[FileModel objectsWithPredicate:pred]sortedResultsUsingProperty:@"name" ascending:YES];
```

but i am not getting success, please help.

**Comment by mrackwitz** [comment]
What error do you get? What type is `strServiceAccounts`? Is that one `NSString` or an `NSArray` of strings. The latter would be expected.

**Comment by anandkumarsharma** [comment]
strServiceAccounts is NSString.

code are follows:
---------------------------------------------
NSString *strServiceAccounts = @"";
        if ([arrFileAccounts count]>0)
        {
            strServiceAccounts = [NSString stringWithFormat:@"("];
            for (int i = 0; i < [arrFileAccounts count]; i++)
            {
                strServiceAccounts = [NSString stringWithFormat:@"%@'%@',",strServiceAccounts,[arrFileAccounts objectAtIndex:i]];
            }
            strServiceAccounts = [strServiceAccounts substringToIndex:[strServiceAccounts length]-1];
            strServiceAccounts = [NSString stringWithFormat:@"%@)",strServiceAccounts];

        RLMResults *allResults;

        NSPredicate *pred = [NSPredicate predicateWithFormat:@"serviceAccountId IN %@ AND            serviceParentFolderId = %@",strServiceAccounts,parentFolderId];

        allResults = [[FileModel objectsWithPredicate:pred]sortedResultsUsingProperty:@"name"   ascending:YES];

}

**Comment by mrackwitz** [comment]
As said, you need to supply the account ids as an array of strings instead of one big string. That means for your code, you can skip building `strServiceAccounts` and use instead `arrFileAccounts` directly.

**Comment by anandkumarsharma** [comment]
Thank you so much, its working now.
