### ISSUE TITLE
Realm queries

### ISSUE THREAD

**Issue by corbrink** [realm/realm-cocoa#3248]
I have a ScoresModel using Swift for iOS which, when queried, produces the following result:

```
[0] ScoresModel {
    courseName = One;
    scoreOne = 4;
    scoreTwo = 10;
    scoreThree = 4;
    datePlayed = Jan 21, 2016;
},
[1] ScoresModel {
    courseName = Two;
    scoreOne = 5;
    scoreTwo = 9;
    scoreThree = 6;
    datePlayed = Feb 2, 2016;
}
```
My question being - When I receive the queried data how can I work with the individual tags received? i.e. all 'scoreOne' together, all 'scoreTwo' together, etc. I want to give feedback on all the data but not in it's raw form, for example average, best, worst, etc.
So if I query:
```swift
let average = realm.objects(ScoresModel).average("scoreOne")
```
I get an error:
> Generic parameter 'U' could not be inferred.

The same for sum, max, min, etc.
scoreOne/Two/Three are declared Int.

**Comment by mrackwitz** [comment]
This error, you describe is a compiler error, I guess? Does the `ScoresModel` have a generic parameter? Can you post the class declaration here?

**Comment by caseynolan** [comment]
I'm getting that same error using sum. Using RealmSwift 0.98.2 with at least two projects to try and weed out what I was doing wrong.

**Comment by bdash** [comment]
You're seeing this error because the Swift compiler cannot tell from the context what type `Result.sum(_:)` or `Result.average(_:)` should return. You can address this by being explicit about what type you expect the result to be, either by adding an explicit type to the variable declaration:

```swift
let average: Double? = realm.objects(ScoresModel).average("scoreOne")
```

or by casting the result:

```swift
let average = realm.objects(ScoresModel).average("scoreOne") as Double?
```

For sum, min, and max you'll likely want to use the same type as the property is declared as, while for average you'll want to use `Float` or `Double`.

**Comment by caseynolan** [comment]
I've been trying to use this in an interpolated String, something like:
`let pages = "\(books?.sum("pages"))"`

Is this not supported or am I going about it the wrong way?

**Comment by bdash** [comment]
As I mentioned above, you need to be explicit as to what type `sum` returns:

```swift
let pages = "\(books?.sum("pages") as Int?)"
```

**Comment by caseynolan** [comment]
OK, a complication: declaring the type as you suggested works, but only when I use:

```swift
let pages = "\(realm.objects(Book).sum("pages") as Int)"
```

This (using a preexisting `Results<Book>` named `books`) doesn't work:

```swift
let pages = "\(books.sum("pages") as Int)"
```

Sorry about hijacking the thread.

**Comment by corbrink** [comment]
My apologies for the late reply. bdash's reply solved most of my issues. caseynolan's reply on the sum issue, which I also had, solved that for me too. Thanks

**Comment by corbrink** [comment]
This issue can be closed.
