### ISSUE TITLE
Loop through Results

### ISSUE THREAD

**Issue by corbrink** [realm/realm-cocoa#3255]
I have a ScoresModel using Swift for iOS which, when queried, produces the following result:

[0] ScoresModel {
    courseName = One;
    scoreOne = 4;
    scoreTwo = 10;
    scoreThree = 4;
    datePlayed = Jan 21, 2016;
},
[1] ScoresModel {
    courseName = Two;
    scoreOne = 5;
    scoreTwo = 9;
    scoreThree = 6;
    datePlayed = Feb 2, 2016;
}

I want to loop through all the scoreOne's as well as others in different scenarios.
         
       var scoresDataSource = ScoresData.fetchAllScoresData()
        let indexPath = 0
        let allScoreOne = scoresDataSource[indexPath].scoreOne
        var sum = 0
        for i in allScoreOne {
            sum = allScoreOne + sum
        }

The for i line gives me an error: Type 'Int' does not conform to protocol 'SequenceType'
What do I need to do to fix this?

**Comment by bdash** [comment]
This line retrieves the value of the `scoreOne` property of a `ScoresModel` object, which is of type `Int`:
```
let allScoreOne = scoresDataSource[indexPath].scoreOne
```

This line attempts to iterate over of the value of `Int` property retrieved above:
```
for i in allScoreOne {
```

`Int` is not a type that can be iterated over since it only represents a single value.

I'm not clear what you intend for this code to compute, but the immediate solution is to not attempt to iterate over something that is not iterable.

**Comment by corbrink** [comment]
That is what I thought but wasn't sure. What got to me is that there will be many scoreOne's and want to iterate through them.
If all the functions (sum, etc) are already built in it should not be a problem.

**Comment by bdash** [comment]
If you need to process one property on several objects you can either iterate the objects and then access the property on each in turn, or you can use [`Results.valueForKey(_:)`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results11valueForKeyuRdq_CS_6Object_FGS0_q__FSSGSqPSs9AnyObject__) to go from a `Results<ScoresModel>` to an `[Int]` containing the values of each `scoreOne` property.

**Comment by corbrink** [comment]
Perfect, thanks.
