### ISSUE TITLE
linkingObjects should return an empty array for standalone objects

### ISSUE THREAD

**Issue by aufflick** [realm/realm-cocoa#3256]
Wouldn't it make more sense to just return an empty array? There's no obvious way for eg. a table view cell to know if an object has been saved or not yet to know whether it's safe to access linked variables or not.

**Comment by jpsim** [comment]
I agree with you that this should return an empty array, which would align with our recent changes to make queries that depend on a deleted object or relationship return no matches.

**Comment by aufflick** [comment]
👍😀

**Comment by jpsim** [comment]
The `linkingObjects()` method was deprecated for `RLMLinkingObjects`/`LinkingObjects` in #3419, which also made it so that those properties return empty results for unmanaged objects.

**Comment by aufflick** [comment]
👍

On Saturday, May 21, 2016, JP Simard <notifications@github.com> wrote:

> Closed #3256 <https://github.com/realm/realm-cocoa/issues/3256>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-cocoa/issues/3256#event-667774600>
>


-- 
-- 
Mark Aufflick
