### ISSUE TITLE
CocoaPod build.sh fails when TMPDIR isn't setup

### ISSUE THREAD

**Issue by semireg** [realm/realm-cocoa#3258]
### Goals

Tried to run "pod install" on Xcode bot. Cocoapod install fails when running Realm's build.sh because TMPDIR env variable is not set.

### Expected Results

Should run without error.

### Actual Results

Installing Realm (0.98.2)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.96.1
mkdir: /core_bin: Permission denied

### Steps to Reproduce

Unset TMPDIR and run build.sh.

### Code Sample

https://github.com/realm/realm-cocoa/blob/master/build.sh#L284

Running "export TMPDIR=/tmp" on a shell allows "pod install" to complete. However, a solution inside of build.sh would be preferred. Alternatively, it would be nice to know how to get launchd (or launchctl, or whatever is the ghost in the machine) to setup _xcsbuildd's environment properly.

We need a check here so it's not trying to mkdir at the root directory.
### Version of Realm and Tooling

El Cap 10.11.3 w/ Xcode Server bot running as user _xcsbuildd.

**Comment by mrackwitz** [comment]
I think the right solution would be to add `TMPDIR` as an environment variable to the `/Library/Server/Xcode/Config/xcsbuildd.plist`, which is responsible for launching the job via `launchd`.
```diff
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
+    <key>EnvironmentVariables</key>
+    <dict>
+           <key>TMPDIR</key>
+           <string>/tmp</string>
+    </dict>
```

Could you give that a try?

(Note: `launchd` is the daemon, who actually launches the jobs, while `launchctl` is a control utility allowing to interface launchd.)

**Comment by bdash** [comment]
We should probably just have build.sh handle the case of missing `TMPDIR` environment variable and use `$(getconf DARWIN_USER_TEMP_DIR)` in that case.
