### ISSUE TITLE
[RLMCache allObjects] Crash

### ISSUE THREAD

**Issue by icaics** [realm/realm-cocoa#3261]
### Goals

Try to use a new RLMObject to replace the old RLMObject, due to add new @property to save.

### Expected Results

Date saved in the new RLMObject in defaultRealm, and, can be read.

### Actual Results

Crash after this line (RLMCacheNew is the new RLMObject):
RLMResults * results = [RLMCacheNew allObjects];

Xcode out put:
> libc++abi.dylib: terminate_handler unexpectedly threw an exception

Set breakpoint to that line:
LLDB log:
> Execution was interrupted, reason: internal c++ exception breakpoint(-2)..
> The process has been returned to the state before expression evaluation

### Steps to Reproduce

1.Make up a RLMObject A with 2 @property, save some data in defaultRealm.

2.Run the app again, make sure the RLMObject A's data can be read.
> RLMResults * results = [RLMObjectA allObjects];
> results will be nil or not, what ever, it won't crash.

3.Create a new RLMObject B with 3 @property, different form A.

4.Run the app again, try to get allObjects first:
> RLMResults * results = [RLMObjectB allObjects];

before save data in it, this is to see if there are data saved before to decide whether to load Data form server or use the data in RLMObject B as cache Data.

5.It will crash.

### Code Sample

> See "Steps to Reproduce"

### Version of Realm and Tooling

Use cocoapods install, iOS 9, Realm version: 0.97.0

**Comment by bdash** [comment]
Can you please share some information about the crash you're seeing? For instance, is it a crash or an exception being thrown? If it's an exception, what is the exception message and backtrace?

From the steps you describe it sounds like you've added a new class to your model without [performing a migration](https://realm.io/docs/objc/latest/#migrations). This will result in an exception being thrown.

**Comment by icaics** [comment]
Sounds cool, I've never notice this step before, I will try this.
Thank you very much.
