### ISSUE TITLE
RealmCoordinator::get_realm() leaks memory

### ISSUE THREAD

**Issue by jinmin888** [realm/realm-cocoa#3270]
**I don't know how to fix the memory leak.**
![screen shot 2016-02-25 at 5 35 27 pm](https://cloud.githubusercontent.com/assets/5707650/13340091/dc5780da-dc70-11e5-82bc-2e1265753c86.png)

**Comment by jpsim** [comment]
@jinmin888 can you please share more information as outlined in our [issue template](https://github.com/realm/realm-cocoa/blob/master/.github/ISSUE_TEMPLATE.md)? Posting a screenshot is not sufficient for us to identify what is happening here.

**Comment by jpsim** [comment]
@jinmin888 just following up on my last request for information.

**Comment by xilin** [comment]
I'm facing the same problem.
Leak Instrument shows that each time when `[RLMRealm defaultRealm]` is called, there is a new leak show up in my app. And the last readable line is same as the first post.

<img width="275" alt="screen shot 2016-04-14 at 3 07 51 pm" src="https://cloud.githubusercontent.com/assets/543395/14519659/d545fae4-0252-11e6-865a-9d0c2194e585.png">

<img width="264" alt="screen shot 2016-04-14 at 3 11 49 pm" src="https://cloud.githubusercontent.com/assets/543395/14519722/3ec56c52-0253-11e6-976d-79de011a47e8.png">

# Version of Realm and Tooling
Realm version: 0.98.6
Xcode version: Version 7.3 (7D175)
iOS/OSX version: 9.3

**Comment by bdash** [comment]
@tgoyne, this looks related to the `CachedRealm` stuff you introduced in the object store.

**Comment by Cyclic** [comment]
I am also seeing a bunch of realm leaks, and all of the call trees point to the default realm, and a set of these are inside of an async call like so:

`dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
    dispatch_async(queue, ^{
        // Get new realm and table since we are in a new thread
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];

        // Do realm createOrUpdateInDefaultRealmWithValue on objects

        [realm commitWriteTransaction];

    });`

![realm_leaks](https://cloud.githubusercontent.com/assets/553800/14689527/93e735f0-06fc-11e6-96a7-eb58fb19d082.png)
