### ISSUE TITLE
Ignored Property of custom class?

### ISSUE THREAD

**Issue by jpayan** [realm/realm-cocoa#3271]
## Goals

I would like to add an ignored property to my RLMObject subclass that is not one of the supported types. If this is not possible, is there an accepted work around?

## Expected Results

I'm not sure why we aren't able to do this. Before trying to set the type in RLMProperty, would it be possible to check if the property is ignored first?

## Actual Results

> *** Terminating app due to uncaught exception 'RLMException', reason: '''MyCustomClass' is not supported as an RLMObject property. All properties must be primitives, NSString, NSDate, NSData, RLMArray, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information.'

## Steps to Reproduce

Create a subclass of RLMObject, add a property of some other non-realm object subclass, add that property name to the 'ignoredProperty' method.

## Code Sample
```objc
@interface SomeModel : RLMObject
@property (strong, nonatomic) SomeOtherModel *otherModel
@end

@implementation SomeModel

+ (NSArray *)ignoredProperties {
   return @[@"otherModel"];
}
@end

@interface SomeOtherModel : NSObject
@end
```

## Version of Realm and Tooling

Realm .98.3
Xcode 7.2.1
OS X 10.10.5

**Comment by bdash** [comment]
The code snippet you provided works as-is for me (after reordering the `@interface` declarations so `SomeOtherModel` is declared before `SomeModel` uses it). I suspect that in the course of editing down your model for this bug report you inadvertently removed whatever it is that was causing the exception to be thrown. Have you verified that all of your `RLMObject` subclasses with a `MyCustomClass` property implement `+ignoredProperties` to ignore those properties?

**Comment by jpayan** [comment]
Ah, you are correct. My model is quite complicated and I missed what was actually causing the problem. Thanks for the help and the great library!
