### ISSUE TITLE
object_schema.cpp:19:10: 'object_schema.hpp' file not found RealmSwift 0.98.3

### ISSUE THREAD

**Issue by georgepoenaru** [realm/realm-cocoa#3274]
Today after I run pod install in my project, Realm was updated to 0.98.3  from 0.98.2 and I was not able to build my project anymore because of this error in RealmSwift module:

....Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:19:10: 'impl/async_query.hpp' file not found

## Version of Realm and Tooling

Xcode 7.2.1
CocoaPods 0.39.0
Realm 0.98.3

**Comment by mrackwitz** [comment]
Please try to clean your build folder, reset your CocoaPods integration (`rm -rf Pods`) and clear the CocoaPods cache. (`rm -rf ~/Library/Caches/CocoaPods`)

**Comment by georgepoenaru** [comment]
Thank you ! I have clear all except clearing CocoaPod cache,  So clearing cache was resolving problem.

**Comment by mrackwitz** [comment]
Thanks for reporting back!

**Comment by filipemvpereira** [comment]
thanks, I clear cocoapods cache and worked

**Comment by jsndev** [comment]
thanks
