### ISSUE TITLE
Specify an operation queue to associate with realm at init-time.

### ISSUE THREAD

**Issue by younata** [realm/realm-cocoa#3275]
Hi Friends!

This is a feature request.

## Goals

It would be incredibly useful, for purposes of dependency injection and testing, to be able to specify at init-time what operation queue (or dispatch queue if you want to go down to that level) to associate with a Realm. That way I don't have to do some weird thing like:

```swift
func realmFactory(operationQueue: NSOperationQueue, callback: Realm -> Void) {
    operationQueue.addOperationWithBlock {
        callback(try! Realm())
    }
}
```

in order to get a realm to work on a background thread. This will also make testing and such easier, as I can still structure my code to mostly work on the main thread.

## Expected Results

I'd love the interface to look something like:

```swift
struct RealmConfiguration {
    [...]
    init([...], operationQueue: NSOperationQueue = NSOperationQueue.mainQueue())
    [...]
}
```

That way I don't have to have to be in callback hell, and can write my code as:

```swift
func realmFactory(operationQueue: NSOperationQueue) -> Realm {
    let configuration = Realm.Configuration(operationQueue: operationQueue)
    return try! Realm(configuration: configuration)
}
```

## Actual Results

n/a

## Steps to Reproduce

n/a

## Code Sample

n/a

## Version of Realm and Tooling

Doesn't exist as of Realm 0.98.3

**Comment by younata** [comment]
Of course, it would be immensely helpful if it was even possible to use Realm in the way I described. Should really have looked into this more before I wrote the issue up.

**Comment by mrackwitz** [comment]
Can you illustrate your use case a little more? It's not exactly clear to me, why you would ever want to retrieve a Realm instance initialized on a background thread, at least with the current thread model. You won't be able to use that instance on any other thread.

**Comment by younata** [comment]
> Can you illustrate your use case a little more? It's not exactly clear to me, why you would ever want to retrieve a Realm instance initialized on a background thread, at least with the current thread model. You won't be able to use that instance on any other thread.

At the time, I hadn't completely grok'd realms (lack of) threading model. Essentially, the request is that it would be awesome if I could pass in, say, a dispatch queue or an NSOperationQueue to bind the realm to, INSTEAD of a thread that realm implicitly binds itself to (meaning that if a queue was passed in, have the thread-checking code check against the queue, otherwise check against the thread). This way, I wouldn't have to pass around the Realm configuration file whenever I wanted to use the Realm in the background, and could instead just pass around a single object that talks to the database file for me.

Additionally, this would also solve the issue of "each time I run a new operation on a queue, I have to take time to new-up a new Realm, which is more overhead than I'd like".

What I did to work around that overhead was to have my RealmService class keep a private dictionary of `[NSThread: Realm]`, that basically works like:

```swift
class RealmService {
  private var realms: [NSThread: Realm] = [:]
  var realm: Realm {
    if let realm = self.realms[NSThread.currentThread()] {
      return realm
    }
    let realm = try! Realm(configuration: self.realmConfiguration)
    self.realms[NSThread.currentThread()] = realm
    return realm
  }
  [...]
}
```

However, I find that this is pretty ugly and a code smell. (Also because I can conceivably have many Realm objects trying to talk to a single database file, which I've found can produce main-thread-blocking behavior in code that should be run entirely in the background.)

**Comment by mrackwitz** [comment]
>Essentially, the request is that it would be awesome if I could pass in, say, a dispatch queue or an NSOperationQueue to bind the realm to, INSTEAD of a thread that realm implicitly binds itself to (meaning that if a queue was passed in, have the thread-checking code check against the queue, otherwise check against the thread).

That just wouldn't work given how threads work because the initialization would need to be done on exactly the given (queue's) thread. Furthermore that wouldn't solve the underlying issue, as you would get an object with which you can't work on the current thread, but which still needs to be passed around.

>What I did to work around that overhead was to have my RealmService class keep a private dictionary of [NSThread: Realm], that basically works like:

Exactly that sort of caching is already happening under the hood by Realm per path. So as long as you keep alive at least one accessor (`Realm`, `Object`, `Results`) on a given thread, the Realm for that thread will be directly returned when initializing a new instance. You're just paying the little overhead of allocating a new wrapper object, which is negligible.

**Comment by younata** [comment]
> Exactly that sort of caching is already happening under the hood by Realm per path. So as long as you keep alive at least one accessor (Realm, Object, Results) on a given thread, the Realm for that thread will be directly returned when initializing a new instance. You're just paying the little overhead of allocating a new wrapper object, which is negligible.

Ah, I'm immediately moving from a Realm object to my own thread-safe model structs, so that I don't leak what kind of backend I'm using to the app. (I have my apps broken up into the frontend app [the app], and a dynamic framework [the kit] that actually performs the work of talking to the network, the database, and other non-ui concerns. Part of this is also having thread-safe model structs that can be (de)serialized to/from Core Data, Realm, even raw data [which makes testing easy]).

So, uh, in my particular case, I'm not keeping hold of any Realm, Object, or Results object long-term, outside of my RealmService object/struct doing the "cache by thread" thing.

**Comment by mrackwitz** [comment]
>So, uh, in my particular case, I'm not keeping hold of any Realm, Object, or Results object long-term, outside of my RealmService object/struct doing the "cache by thread" thing.

Okay, then this `RealmService` idea might help and actually speed up things. If you have other ideas how that can be still solved in a general manner, they are welcome. Perhaps we could also improve our docs around what is happening here under the hood.

**Comment by younata** [comment]
> Perhaps we could also improve our docs around what is happening here under the hood.

That would be welcome. I'll close this issue.
