### ISSUE TITLE
Migrations with extra realms just don't work

### ISSUE THREAD

**Issue by daniel-beard** [realm/realm-cocoa#3277]
## Goals

> Migrate a Realm to add a new NSString property.

## Expected Results

> Migration should work

## Actual Results

> Migration doesn't take place, and instead raises an exception.
> Took into account https://github.com/realm/realm-cocoa/issues/1793 and added a default value to the new property, still does not migrate correctly.

```
RealmTest[23823:2981894] *** Terminating app due to uncaught exception 'RLMException', reason: 'Migration is required due to the following errors: 
- Property 'test' has been added to latest object model.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107323e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106d9cdeb objc_exception_throw + 48
	2   RealmTest                           0x0000000106380d79 _Z18RLMSetErrorOrThrowP7NSErrorPU15__autoreleasingS0_ + 985
	3   RealmTest                           0x000000010635805a +[RLMRealm realmWithConfiguration:error:] + 7306
	4   RealmTest                           0x00000001061a8c8e __41+[DBRealmMigrationHelper migrateIfNeeded]_block_invoke + 558
	5   libdispatch.dylib                   0x0000000108d1749b _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x0000000108d02e28 dispatch_once_f + 543
	7   RealmTest                           0x00000001061a8a47 +[DBRealmMigrationHelper migrateIfNeeded] + 87
	8   RealmTest                           0x00000001061a994c -[AppDelegate application:didFinishLaunchingWithOptions:] + 92
	9   UIKit                               0x00000001076c71f1 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 272
	10  UIKit                               0x00000001076c8397 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3415
	11  UIKit                               0x00000001076cecc6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1760
	12  UIKit                               0x00000001076cbe7b -[UIApplication workspaceDidEndTransaction:] + 188
	13  FrontBoardServices                  0x0000000109ff8754 -[FBSSerialQueue _performNext] + 192
	14  FrontBoardServices                  0x0000000109ff8ac2 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	15  CoreFoundation                      0x000000010724fa31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x000000010724595c __CFRunLoopDoSources0 + 556
	17  CoreFoundation                      0x0000000107244e13 __CFRunLoopRun + 867
	18  CoreFoundation                      0x0000000107244828 CFRunLoopRunSpecific + 488
	19  UIKit                               0x00000001076cb7cd -[UIApplication _run] + 402
	20  UIKit                               0x00000001076d0610 UIApplicationMain + 171
	21  RealmTest                           0x00000001061aad6f main + 111
	22  libdyld.dylib                       0x0000000108d4b92d start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Steps to Reproduce

> Clone https://github.com/daniel-beard/RealmTest
> Checkout dbeard_branch1, build and run with a fresh simulator
> Checkout dbeard_branch2, build and run

## Code Sample

> See above.

## Version of Realm and Tooling

> Realm (Obj-C 0.98.3, Xcode 7.2.1)

**Comment by daniel-beard** [comment]
I'm hoping that this is just something really dumb I'm not changing correctly, but right now migrations on other realms are not working for me at all.

**Comment by mrackwitz** [comment]
I tried out your sample project, but couldn't mention anything not working as expected. The error handling you added for the sample project is a little misleading though and seems to suggest, that it would be failing for all configurations. You only bumped the schema version for the configuration, which can be retrieved for `DBRealmModel1`. As they all are part of the default schema and you don't use partial schemas for any configuration, opening those different Realm files with a lower `schemaVersion` is expected to fail.

**Comment by daniel-beard** [comment]
I'm not sure what you mean about partial schemas, is that documented somewhere?
I'm trying to do this:
- `DBModel1` objects only use realm at path: `cache.channel`
- `DBModel2` objects only use realm at path: `search.history`

So if I modify `DBModel1`, shouldn't I only have to change the migration & schema version for that Realm only?

**Comment by daniel-beard** [comment]
Ignore printing out the errors for now, as I don't pass those in intentionally, to show the exception rather than the errors.

**Comment by mrackwitz** [comment]
No custom / partial schemas are actually not publicly exposed. So what you're trying to do, doesn't work yet with our public API. There is nothing telling Realm, that a given configuration belongs to a given object. All `RLMObject` subclasses are reflected at runtime and one global schema is derived on base of that. You would need instead either bump the schemaVersion whenever you change any of the object models for all configurations (and have them as additional tables in your database) or use the dynamic API.

**Comment by daniel-beard** [comment]
So if I update the object `DBModel1` belonging to `cache.channel` realm, I have to increment all schema versions for every realm configuration in my app? :(

**Comment by mrackwitz** [comment]
Yes, that's indeed the case.

**Comment by daniel-beard** [comment]
Ok, that makes sense, although from the documentation that was not clear to me at all. You can consider this issue resolved I guess.

**Comment by mrackwitz** [comment]
Oh dang, so much confusion, actually we exposed that feature, but I was judging from the wrong end of the code. Just set `objectClasses` on the `RLMRealmConfiguration` and you should be fine.

**Comment by daniel-beard** [comment]
Although, what implications does that have for dependencies? If I link against a framework that uses Realm, and I also use Realm: do I still only get 1 global schema version?

**Comment by daniel-beard** [comment]
Ok, let me try that

**Comment by mrackwitz** [comment]
In the best case the framework just uses a partial schema with classes that it brings on its own or allows to inject Realm configuration. So even if it's using the default Realm, that can be configured still by yourself. Only if the framework setups it's own configuration from scratch, then you would be out of luck.

**Comment by mrackwitz** [comment]
I'll close this for now, but feel free to report back, if you have any questions left about how partial schemas work.

**Comment by daniel-beard** [comment]
Thanks @mrackwitz
