### ISSUE TITLE
Realm crash (EXC_BAD_ACCESS) when writing while device is Locked.

### ISSUE THREAD

**Issue by chucktee** [realm/realm-cocoa#3283]
My application writes location updates into the default Realm on iOS, Objective-C, 9.2.1, Realm 0.98.3

If the app is in the foreground, or background from pressing the home button, writes work as expected.

Once the device is locked, either by pressing the lock button or the device self locking- the next write crashes at in: inline void SharedGroup::commit_and_continue_as_read() at line 966- do_commit(). 

I'm not using Realm encryption nor iOS disk encryption.
 
The app crashes on iPhone 6, iPad mini (1st gen) and iPad Pro (haven't tested others) and it does not crash in the Simulator set to Locked.

I had this issue a few months ago and was able to resolve it by setting NSFileProtectionNone against all files in the Realm path at startup.  Now, I have to set NSFileProtectionNone before every write otherwise I see the crash.  This seems like a lot of overhead and I'm wondering if there is a better approach.

This is what I call to clear the protection:
```
NSString *pathToRealmFile = [RLMRealmConfiguration defaultConfiguration].path;
    NSArray *allRealmRelatedFiles = @[
                                      pathToRealmFile,
                                      [pathToRealmFile stringByAppendingString:@".lock"],
                                      [pathToRealmFile stringByAppendingString:@".log"],
                                      [pathToRealmFile stringByAppendingString:@".log_a"],
                                      [pathToRealmFile stringByAppendingString:@".log_b"]
                                      ];
    for (NSString *path in allRealmRelatedFiles) {
        NSError *error = nil;
        //
        [[NSFileManager defaultManager] setAttributes:@{NSFileProtectionKey: NSFileProtectionNone} ofItemAtPath:path error:&error];
        if (error) {
            NSLog(@"Error clearing protection on %@", path);
        }
    }
```

Any ideas are much appreciated.
Chuck-

**Comment by mrackwitz** [comment]
The problem here is that the auxiliary files are not guaranteed to exist all the time. They might be deleted. If that happens and they are recreated, then you would need to set the file attributes again. But there are no hooks for that. As a workaround, I'd recommend to set the attribute for the directory where the Realm is stored. If there are other files in there, which would better make use of the encryption, then you can move the Realm files into another directory as a workaround by setting the default configuration's path.

**Comment by mrackwitz** [comment]
See https://github.com/realm/realm-cocoa/issues/3224 for reference.
