### ISSUE TITLE
Why - (BOOL)transactionWithBlock:(void(^)(void))block error:(NSError **)error do not work as I except?

### ISSUE THREAD

**Issue by yuldong** [realm/realm-cocoa#3284]
Define my RLMObject:

```objc
@interface YYYProductInfo : RLMObject

@property NSString *name;
@property NSInteger price;
@property NSData *productDescription;
@property NSDate *date;

@property RLMArray<YYYHighEnergyProduct*><YYYHighEnergyProduct> *hignEnergyProducts;

@end
#import "YYYProductInfo.h"

@implementation YYYProductInfo

// Specify default values for properties

+ (NSString *)primaryKey {
    return @"name";
}
@end

```

AddObject like this:

```objc
YYYProductInfo *newProduct = [[YYYProductInfo alloc] init];
newProduct.name = @"test"; //[self randomString];
newProduct.price = arc4random_uniform(20) * 1.0;
newProduct.productDescription = [self getDataByString:@"添加单个商品信息, 价格在20块以下"];
RLMRealm *realm = [RLMRealm defaultRealm];
NSError *error;
[realm transactionWithBlock:^{
    [realm addObject:newProduct];
} error:&error];

if (error != nil) {
    NSLog(@"%@", error.localizedDescription);
}
```

this code crashed after doing twice "crash log":
> Can't set primary key property 'name' to existing value 'test'

why it does not throw the "error" infomation instead of crashing in the second operation?

**Comment by mrackwitz** [comment]
Creating an object with an existing primary key is treated as a program error, because write transactions are exclusive, so that you've a guarantee when checking before the attempt to create it that the operation will succeed. Realm operations fail in general with returning an error, if you've no way to foresee, that this could fail. If you want to add or update the object, please use `-addOrUpdateObject:` instead. Does this help?

**Comment by yuldong** [comment]
@mrackwitz thanks a lot. That means I should modify my Model or code to fix this. What kind of error will i met if i use this method normally?

**Comment by mrackwitz** [comment]
You need to modify your code for object creation. e.g.
```objc
[realm transactionWithBlock:^{
    [realm addOrUpdateObject:newProduct];
} error:&error];
```
This would fail, if the Realm can't be written, e.g. because Realm's auxiliary files can't be created.
