### ISSUE TITLE
default.realm  path changed when app launch every time

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#3285]
because the default.realm  path changed,the result has changed.

```swift
print(Realm.Configuration.defaultConfiguration.path!)
```

/Users/chengfeiheng/Library/Developer/CoreSimulator/Devices/DAED3624-119A-4A05-A0CE-DF6EAEF6AADA/data/Containers/Data/Application/**A72237CB-D878-4D36-8536-4E310703D02F**/Documents/default.realm

/Users/chengfeiheng/Library/Developer/CoreSimulator/Devices/DAED3624-119A-4A05-A0CE-DF6EAEF6AADA/data/Containers/Data/Application/**152DE8A3-E3A1-4814-BE8D-912BF664B987**/Documents/default.realm

**Comment by mrackwitz** [comment]
Xcode beginning from version 6 renames the documents directory every time you launch the app. But don't worry, you won't loose the contents. Just don't rely on absolute paths as they will break.

**Comment by hengchengfei** [comment]
I really appreciate!

**Comment by mrackwitz** [comment]
I guess [this comment](https://github.com/realm/realm-cocoa/issues/3279#issuecomment-192064973) should go here:
>as absolute paths changed , should reopen latest path default.realm in Realm Browser?

@TimOliver: Is that something which need to be addressed in the browser?
