### ISSUE TITLE
Support for Swift 3.0 & Xcode 7.3

### ISSUE THREAD

**Issue by jacobsieradzki** [realm/realm-cocoa#3287]

**Comment by jpsim** [comment]
I just filed #3291 to add support for the latest Xcode beta (7.3 beta 5). Our frameworks already compile fine on `master`, but there's one change necessary for the tests to compile.

As for Swift 3 support, that version of Swift isn't scheduled for release until Fall 2016. We'll continue to support the latest Swift versions as they come out, including Swift 3, but there's not much more we can do right now.

**Comment by jpsim** [comment]
#3291 has been merged and there's nothing further to do for now.
