### ISSUE TITLE
add RLMRealmConfiguration.compactOnLaunch

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3289]
It's common for users with large Realm files with significant amounts of unused space to want to compact them on a regular basis. The code users typically write to accomplish this is error prone due to challenges dealing with Realm instance life cycles.

Unfortunately, if this option existed, it would likely be abused and used in cases in which compaction wouldn't actually reclaim much disk space. If core had a way to get a ballpark estimate of how much space could be reclaimed, this could be used to more intelligently perform compactions.

**Comment by tgoyne** [comment]
Approximating the amount of space that will be freed up by compact() is pretty fast and simple (just add up the size of everything in the free list). Rather than just a binary "always compact on open", we could maybe expose "compact if live data is less than X% of the file"?

**Comment by cmelchior** [comment]
It sounds weird to expose such an option, everybody would just enable it I think?

**Comment by jpsim** [comment]
> > we could maybe expose "compact if live data is less than X% of the file"?
>
> It sounds weird to expose such an option, everybody would just enable it I think?

Maybe having a `RLMRealmConfiguration.compactOnUsageRatio` with a default value of `0.5` could work? Naming needs work, obviously.

**Comment by jasper-ch-chan** [comment]
Any chance this feature can be moved into a P1 backlog?

**Comment by jpsim** [comment]
I don't think so. [Our current P1s](https://github.com/realm/realm-cocoa/issues?q=is%3Aopen+is%3Aissue+label%3A%22S%3AP1+Backlog%22) are all higher priority.

**Comment by jpsim** [comment]
Merged in #4755 and available in today's 2.6 release: https://realm.io/news/realm-objc-swift-2.6
