### ISSUE TITLE
0.98.3 - "impl/async_query.hpp" file not found

### ISSUE THREAD

**Issue by EstebanVallejo** [realm/realm-cocoa#3293]
## In General

Hello, I have updated via cocoa pods to the latest version of the library (0.98.3), but when I try to build the project I'm getting a compile error, some files are not being found :/ . Any ideas ??

PS: Attaching info below
PS 2: It works up to Realm version 0.98.2 (confirmed)

## Expected Results

Being able to use the latest version or the library

## Actual Results

Getting a compile error 
"impl/async_query.hpp" file not found on file "async_query.cpp"

## Steps to Reproduce

Just updated the pods
 ( "pod update" 
Installing Realm 0.98.3 (was 0.97.1)
Installing RealmSwift 0.98.3 (was 0.97.1)
) 

and then build the project (I've tried cleaning the project and erasing the derived data).

## Code Sample

On source file : async_query.cpp
Line : 19  ( #include "impl/async_query.hpp" )

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21

/Applications/Xcode.app/Contents/Developer
Xcode 7.2
Build version 7C68

/usr/local/bin/pod
0.39.0
Realm (0.98.3)
RealmSwift (0.98.3)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/bin/git
git version 2.5.4 (Apple Git-61)
```

**Comment by mrackwitz** [comment]
Please try to clean your build folder, reset your CocoaPods integration (`rm -rf Pods`) and clear the CocoaPods cache. (`rm -rf ~/Library/Caches/CocoaPods`)

**Comment by EstebanVallejo** [comment]
Amazing! Cleaning the CocoaPods cache (rm -rf ~/Library/Caches/CocoaPods) did the trick !
Thanks!  

Marking as closed

**Comment by DigitalRogues** [comment]
just wanted to add, I had to remove the Pods directory also to get the file to be redownloaded/seen
