### ISSUE TITLE
Empty List after assign RLMObject to variable

### ISSUE THREAD

**Issue by nicopuri** [realm/realm-cocoa#3301]
Hi,

I'm using Realm `v0.98.3` and ReactiveCocoa `v4`. I have an issue with `List`. I have a similar case as the documentation your wrote.

```
public class Dog: Object {
    dynamic public var name: String = ""
}

public class Person: Object {
    
    dynamic public var name: String = ""
    public let dogs = List<Dog>()
    
}

public class ViewModel {
    
    public var person: AnyProperty<Person?> { return AnyProperty(_person) }
    
    private var _person = MutableProperty<Person?>(nil)
    
    public func setExistingPerson(person: Person) {
        // print(person) ==> List of dogs is OK
        self._person.value = person
        // print(self._person.value) ==> The list of dogs is empty.
    }
    
}

final class ViewController: UIViewController {
    
    private var db: Realm?
    private let viewModel = ViewModel()
    
    override func viewDidLoad() {
        super.            self.db = try Realm()
        } catch { }
        
        if let existingPerson = self.db?.objectForPrimaryKey(Person.self, key: "puri") {
            self.viewModel.setExistingPerson(existingPerson)
        }
    }
    
}
```

If I print the list of People before assign it to a `MutableProperty`, the objects contains the correct list of dogs. After assign it, if I execute `print(db.objects(Person.self))` the list of dogs for each person is empty. It has a weird behavior, it seems like it's deleting the reference for list objects after assign it. I don't understand why.

Thanks

**Comment by mrackwitz** [comment]
Do you have a ready sample project, which reproduces this error? Just from the code you posted, I can't recognize how this should fail.

**Comment by nicopuri** [comment]
@mrackwitz I can't copy the code here, sorry. I already fixed it, but I can't found the reason of this weird behavior.

**Comment by mrackwitz** [comment]
Okay, thanks for the update.

**Comment by cgomezmendez** [comment]
I'm having same problem How did you solve it?
