### ISSUE TITLE
Different explaination of the same method in Documents and API Reference

### ISSUE THREAD

**Issue by migrant** [realm/realm-cocoa#3306]
In document page, Updating Objects section, there are:

```objc
// Assuming a "Book" with a primary key of `1` already exists.
[realm beginWriteTransaction];
[Book createOrUpdateInRealm:realm withValue:@{@"id": @1, @"price": @9000.0f}];
// the book's `title` property will remain unchanged.
[realm commitWriteTransaction];
```

> If your model class doesn’t include a primary key, then a new copy of the object will be created in Realm each time this method is called.

But in API Reference, it says:

> This method can only be called on object types with a primary key defined.

And I wrote a sample project to test it. I found the app will crash if the object do not have a primary key.
So the documents page is wrong ?

**Comment by mrackwitz** [comment]
Yes, the documentation is wrong. We assert in that case, considering that being a programmer error to prevent misconception about what is going to happen and make the behavior more intuitive. Thanks for pointing that out here! :+1:
