### ISSUE TITLE
App Crashes when second object is added with same primary key. Couldn't catch an exception.

### ISSUE THREAD

**Issue by kamilgryniewicz** [realm/realm-cocoa#3313]
> Please fill out this template when filing an issue.
> All lines marked as quotes (`>`) instruct you with
> what info we expect.
> Remove this opening paragraph.

## Goals

Catch an exception when adding second object with same primary key

## Expected Results

Could catch an exception

## Actual Results

App crashes 

*** Terminating app due to uncaught exception 'RLMException', reason: 'Can't set primary key property 'fileId' to existing value 'aaa'.'
*** First throw call stack:
...

## Steps to Reproduce

Make custom Object subclass with custom primary key
create two objects and assign the same value to primary key property
Add first -> all ok
Add second -> **App crashes**

Doesn't matter if I use `try!` or `do try catch`

## Code Sample
Object:
class MediaFile: Object {
    dynamic var fileId: String = ""
    override class func primaryKey() -> String? { return "fileId" }
}

Code to add MediaFile object to realm:

```
try! realm.write {
            realm.add(file)
        }
```

or

```
  do {
            try realm.write {
                realm.add(file)
            }
        } catch is NSException {
            print("Something went wrong!")
        } catch {
           print("???")
        }
```
Non of texts is printed.
## Version of Realm and Tooling
RealmSwift, 0.98.4
Xcode Version 7.2.1 (7C1002) and Version 7.3 beta (7D162j)

**Comment by mrackwitz** [comment]
That's expected. As our documentation states `realm.write` only throws an error when you run out of disk space. You are supposed to check yourself whether an object with the given primary key already exists.
```swift
if realm.objectForPrimaryKey(MediaFile.self, key: file.key) {
    realm.add(file)
    // do something else e.g. store the file contents in documents dir
}
```
Alternatively you can pass in `update: true`, so that the existing object will be updated with the new values.
```swift
realm.add(file, update: true)
```
