### ISSUE TITLE
Cannot filter results using predicate

### ISSUE THREAD

**Issue by maciekish** [realm/realm-cocoa#3317]
## Goals

Filter all Realm objects of the type Night that ocurred on a specific date

## Expected Results

The code should compile

## Actual Results

.filter() does not accept the NSPredicate.

## Steps to Reproduce

Try to .filter results using an NSPredicate

## Code Sample

![code](https://s3.amazonaws.com/f.cl.ly/items/0L1k0D0V320L1M3Z1501/Screen%20Shot%202016-03-11%20at%2016.28.04.png?v=2f48ee79)

## Version of Realm and Tooling

Xcode 7.2.1
Realm 0.98.4

**Comment by mrackwitz** [comment]
The return type of your method is a Swift standard `Array`. There is no overloading of `Results.filter`, which does return that directly. Instead all possible `filter` methods return a lazy `Results` instance. The compiler tries to find a candidate by the expected return type and assumes you want to use [`Collection.filter`](https://developer.apple.com/library/ios/documentation/Swift/Reference/Swift_CollectionType_Protocol/index.html#//apple_ref/swift/intfm/CollectionType/s:FeRq_Ss14CollectionTypeq_Ss22_CollectionWrapperTypezqq_Ss9Indexable5Indexqqq_S0_4BaseS1_5Indexzqqq_S1_5IndexSs16ForwardIndexType8Distanceqqqq_S0_4BaseS1_5IndexS2_8Distancezqqq_S1_5IndexS2_19_DisabledRangeIndexqqqq_S0_4BaseS1_5IndexS2_19_DisabledRangeIndexzqqqq_S1_5IndexS2_8DistanceSs25IntegerLiteralConvertible18IntegerLiteralTypeqqqqq_S0_4BaseS1_5IndexS2_8DistanceS3_18IntegerLiteralType_SsS_6filteruRq_S_q_S0_zqq_S1_5Indexqqq_S0_4BaseS1_5Indexzqqq_S1_5IndexS2_8Distanceqqqq_S0_4BaseS1_5IndexS2_8Distancezqqq_S1_5IndexS2_19_DisabledRangeIndexqqqq_S0_4BaseS1_5IndexS2_19_DisabledRangeIndexzqqqq_S1_5IndexS2_8DistanceS3_18IntegerLiteralTypeqqqqq_S0_4BaseS1_5IndexS2_8DistanceS3_18IntegerLiteralType_Fq_FFqqqq_S0_4BaseSs12SequenceType9GeneratorSs13GeneratorType7ElementSbGSaqqqq_S0_4BaseS4_9GeneratorS5_7Element_).
Instead try to use the following:
```swift
return objects.filter(predicate).valueForKey("@self")
```

**Comment by maciekish** [comment]
That didn't work but the code below did

    return Array(objects.filter(predicate))

**Comment by jpsim** [comment]
> `return Array(objects.filter(predicate))`

This is definitely how I'd recommend converting a `Results` to an `Array` because it preserves the element type. Although I'd generally discourage you from making this conversion at all since it loses many of Realm's advantages (like efficiency & live results).

**Comment by rahimizad** [comment]
I have a similar issue, the resulting array is correct, and prints ok, however when i iterate through a for look like: for location in locations { the content of each element within location is nil or blank! }  

I have not found a way to get the content of the location to be the valid content that was printed out two lines above!...

 let locationsVisited = Array(realm.objects(Location).filter("dateEntered > %@ AND dateEntered <= %@", chartStartDate!, chartEndDate!).sorted("dateEntered", ascending: true))
print (locationsVisited)
for location in locationsVisited {
                guard (location.icon) != nil else { continue }
}

every element of location is nil or blank but the print statement correctly printed each element's value...

**Comment by mrackwitz** [comment]
@rahimizad: In the sample code, you shared with us here, you check for `location.icon`. I don't think that the actual elements (`location`) of the collection could be nil based on how you construct it.
Please note as well that the retrieved collection is as a collection not auto-updating anymore, but all of the objects are still auto-updated. So if you concurrently clear all fields of those locations, the result you're facing here would be expected. We would likely need more code or a sample project to further assist you, if that shouldn't help. In advance, please note that we prefer StackOverflow for Help-related issues. We monitor for the tag `realm` and will take note of it. This issue was already closed and is only tangentially related to your question.
