### ISSUE TITLE
如何 对 List的属性进行 包含类的查询

### ISSUE THREAD

**Issue by yushuyi** [realm/realm-cocoa#3322]
我有一个
项目 的表，里面包含 参数项目的人员 这个属性是 List。

我想通过人员过滤出 这个 人员 参与过哪些项目

**Comment by mrackwitz** [comment]
Could you share some related code from your model, so that we can assist you easier? /c @beeender

**Comment by beeender** [comment]
Translation to English:

I have a model `Project` which has as List of another Realm model `People`.
How can I query all `Project` that a specific `People` joined?

**Comment by yushuyi** [comment]
@beeender @mrackwitz  
thanks!

My code like this:

class User : Object {
    dynamic var id : String = NSUUID().UUIDString
    dynamic var name : String!
    override class func primaryKey() -> String? {
        return "id"
    }
}

class Card : Object {

    dynamic var id : String = NSUUID().UUIDString
    dynamic var name : String!
    dynamic var createUser : User!
    let joinUsers = List<User>()

    override class func primaryKey() -> String? {
        return "id"
    }
}

**Comment by mrackwitz** [comment]
You can achieve that by using the `IN` operator in a predicate:
```swift
let user : User = …
realm.objects(Card).filter("%@ IN joinUsers", user)
```
Does this answer your question?

**Comment by yushuyi** [comment]
Yes，Thank you very much！

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (123/100 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:40724 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflkW-001gJR-UA
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:58:48 -0400
Date: Mon, 14 Mar 2016 00:00:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457938816;
	bh=NcDOrZ+txTTHoT1yXHFfAlQ0O6IAZ9lHzu/7WscBMBE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=rYE1/8x6LLas0830jKlRSa41+DqJJdGTOBbEWNsgEPtJUeRcS8gMzq3oR7UtsTs3E
	 eyAIL79cO7SYZW3dG00mm+KSx0290kq6OPyQ8ZH/KFAz02LoPqb/A6rXT6MKOX5GAA
	 RCi/ZD5U3TCN1i0ExDKaEs8HYtr1snW21Yrn65zE=
