### ISSUE TITLE
Share access between between the Realm Browser and an iOS simulator

### ISSUE THREAD

**Issue by migrant** [realm/realm-cocoa#3323]
> Realm version is 0.98.4
> Realm Browser version is 0.97.0
> iOS simulator is iPhone 6s. 

But when I run my project and read a realm db file which is opened in Browser, I get the "Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. For sharing files between the Realm Browser and an iOS simulator, this means that you must use a 64-bit simulator." error.

I have read #1659 but my simulator is 6s which is exactly 64-bit. Why do I get this error.

> P.S: I don't get this error before updating Realm from 0.98.3 to 0.98.4

**Comment by jpsim** [comment]
In general, simultaneous multi-process sharing of Realm files is only supported if both processes are using the exact same version of Realm. We just made a release of the Realm Browser using Realm 0.98.5 which you can find here: https://github.com/realm/realm-browser-osx/releases/tag/0.98.5

In this case, Realm 0.98.4 introduced a slightly different lock file format, which is responsible for the incompatibility.

**Comment by migrant** [comment]
hmm... I installed Realm Browser in MAS, when will it release to MAS ?

**Comment by jpsim** [comment]
It's already been submitted to the App Store for review, so you'll have to ask Apple when it'll be out.

**Comment by OlegAnghelov** [comment]
Is there a way to download older versions of browser?

**Comment by TimOliver** [comment]
@OlegAnghelov Hi Oleg! We're maintaining a list of the previous Browser versions on its release page: https://github.com/realm/realm-browser-osx/releases

How far back do you need exactly?

**Comment by OlegAnghelov** [comment]
Funny enough that we use exactly 0.98.1 :)

**Comment by OlegAnghelov** [comment]
We exactly 0.98.1 :)
And now since a new version of realm is available, 0.98.7, it seems that current realm browser cannot open it. When will the app will be updated?

**Comment by TimOliver** [comment]
@OlegAnghelov Ahh okay then!

Uh-oh. Really? Which version of the Browser were you using for that? 0.98.6? Or 0.98.1?

**Comment by OlegAnghelov** [comment]
Ah, sorry, i forgot to mention that because I didn't found the 0.98.1 browser, I decided to debug my problem after updating to 0.98.6. But overnight you released of Realm, and my 0.98.6 browser stopped being helpful. So I regressioned back to 0.98.6 Realm pod, so i can use it with 0.98.6 browser :)

but what about 0.98.1 browser?

**Comment by jhoughjr** [comment]
Would this mean that two mac apps could share the same realm file and things just work?
I'd rather not dig myself deeper. I infer it's possible from the docs and what I've found, but nothing explicitly my situation.

**Comment by MrHubble** [comment]
@jpsim I have this problem and both of the processes are using the same Realm version (Realm Javascript (1.2.0) which uses `REALM_CORE_VERSION=2.5.1`, and Realm Browser 2.1.7 which is also using Realm 2.5). Can you suggest anything else I can do to fix this?
