### ISSUE TITLE
More informative exception message for unsupported property types

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-cocoa#3324]
## Goals

If I'm creating a Realm object and it has a property of unsupported type (like NSURL) the init throws. Since I generally don't expect this to happen in production I don't catch this exception and I get the error description in the console.

The description however doesn't tell me which property is of an unsupported type, which I'd expect so I can quickly fix the problem.

## Expected Results

I'd expect the property name in the error message - something like "The property imageURL is of type NSURL, which is not supported..." in the error description.

## Actual Results

The error message does not include the name of the offending property:

*** Terminating app due to uncaught exception 'RLMException', reason: ''NSURL' is not supported as an RLMObject property. All properties must be primitives, NSString, NSDate, NSData, RLMArray, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information.'

## Steps to Reproduce

Define a property of unsupported type in a realm object, e.g.:

dynamic var imageUrl: NSURL?

## Version of Realm and Tooling

Realm 0.98.3 / Xcode 7.2.1

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (121/100 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:60715 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflkP-001gGm-Rr
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:58:41 -0400
Date: Sun, 13 Mar 2016 07:18:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457878693;
	bh=7OZOBaAo0JvBQ2v8ngxVFeABo3OFXVrUMIg2tSsInuE=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=VkYJts0exWU8FvVjm0Nwd9lzywbJRWsANwA/OFIjHDxcG8jU37R3kJOPv2fUCEsIW
	 gXm+blcGvqR1N3zia6XdbKDqH08FtKIDQ5cGJHKMZFj4bTMm4PXMjM/NwhfZLmlSDf
	 iIicfWOwHrgtJ4lZrlEU4NuEGab9fbyhi6PxMbdI=
