### ISSUE TITLE
RealmSwift object result related instance becomes nil

### ISSUE THREAD

**Issue by markkohdev** [realm/realm-cocoa#3325]
## Goals

Given the following models
```
class User: Object, Mappable {
    
    // User attributes
    var id = RealmOptional<Int>()
    dynamic var email: String!
    dynamic var firstName: String!
    dynamic var lastName: String!
    dynamic var fullName: String!
    dynamic var photo: String?
    dynamic var title: String?
    var userTypes = List<UserType>()
...
}

class UserAuthData: Object {
    var user: User!
    dynamic var token: String!
}
```

I am attempting to write a UserAuthData object to a realm (which is successful) and then retrieve it from the realm, after which I set a singleton instance of the User and Token.

## Expected Results

I expect after retrieving a UserAuthData object from Realm that I would be able to access the user property of the instance as
```
authData.user
```

## Actual Results

After retrieving the UserAuthData object with the correct user info, I receive a nil value when trying to access `user` property.  For some reason, accessing the property through a subscript works however.

With a breakpoint below the following code:
```
let userAuthData = realmDB.objects(UserAuthData)
let authData = userAuthData[0]
```

lldb gives the following output
```
(lldb) po userAuthData
Results<UserAuthData> (
	[0] UserAuthData {
		user = User {
			email = mark@booksmart.it;
			firstName = Mark;
			lastName = Koh;
			fullName = Mark Koh;
			photo = (null);
			title = (null);
			userTypes = RLMArray <0x14cda6b30> (
				[0] UserType {
					name = Tour Manager;
					abbreviation = (null);
				}
			);
			id = 1;
		};
		token = 55ec3b639804bd7df585ee8f646752c01bca0bef;
	}
)

(lldb) po authData
UserAuthData {
	user = User {
		email = mark@booksmart.it;
		firstName = Mark;
		lastName = Koh;
		fullName = Mark Koh;
		photo = (null);
		title = (null);
		userTypes = RLMArray <0x14e21bbd0> (
			[0] UserType {
				name = Tour Manager;
				abbreviation = (null);
			}
		);
		id = 1;
	};
	token = 55ec3b639804bd7df585ee8f646752c01bca0bef;
}

(lldb) po authData.user
fatal error: unexpectedly found nil while unwrapping an Optional value
fatal error: unexpectedly found nil while unwrapping an Optional value
nil

(lldb) po authData["user"]
▿ Optional(User {
	email = mark@booksmart.it;
	firstName = Mark;
	lastName = Koh;
	fullName = Mark Koh;
	photo = (null);
	title = (null);
	userTypes = RLMArray <0x14e252720> (
		[0] UserType {
			name = Tour Manager;
			abbreviation = (null);
		}
	);
	id = 1;
})
  ▿ Some : User {
	email = mark@booksmart.it;
	firstName = Mark;
	lastName = Koh;
	fullName = Mark Koh;
	photo = (null);
	title = (null);
	userTypes = RLMArray <0x14cf0caa0> (
		[0] UserType {
			name = Tour Manager;
			abbreviation = (null);
		}
	);
	id = 1;
}

(lldb) po authData["token"]
▿ Optional(55ec3b639804bd7df585ee8f646752c01bca0bef)
  - Some : 55ec3b639804bd7df585ee8f646752c01bca0bef

(lldb) po authData["token"]
"55ec3b639804bd7df585ee8f646752c01bca0bef"

(lldb) po authData.token
"55ec3b639804bd7df585ee8f646752c01bca0bef"
```

## Steps to Reproduce

 - Implement models as specified above
 - Write an instance to a realm
 - Retrieve all objects of that type from the realm
 - Attempt to access the related object directly as a property

## Code Sample

The below code works, but is far from ideal
```
        let userAuthData = realmDB.objects(UserAuthData)
        if userAuthData.count > 0 {
            let authData = userAuthData[0]
            UserService.currentUser(authData["user"] as! User?)
            APIService.setToken(authData["token"] as! String)
        }
```

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27

/Applications/Xcode.app/Contents/Developer
Xcode 7.2
Build version 7C68

/usr/bin/pod
0.39.0
Realm (0.98.3)
RealmSwift (0.98.3)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)


(not in use here)

/usr/local/bin/git
git version 2.4.2
```

**Comment by bdash** [comment]
```
class UserAuthData: Object {
    var user: User!
    dynamic var token: String!
}
```

Your `user` property must be declared as `dynamic`. When a property is not declared dynamic, Realm has no way to override the getter or setter, which prevents the correct values from being returned.

**Comment by markkohdev** [comment]
Ahh, that was it.  I should've noticed that, thank you @bdash - today you saved me some sanity.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:49139 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmJI-001w9K-M6
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:34:44 -0400
Date: Sun, 13 Mar 2016 11:44:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457894656;
	bh=FUZPjafxpKBQGV4HWo/n3jlWXJwJ0NmP8q6UdKfJhkY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=I1mKtH6RwInjkGwRwpny+0zkfG9Rofyk3klXI4Y2OnDQ1LTWfgGvFReh7ENR5G79x
	 22n5tK/6oAnA1pbQe1f17uULYNwdkYlHtPAw5I6gGxAH8+rJ7hNYxZ0oImcdb2Ox6H
	 kewP3IIM9oTKyywn0PoWSa4DT5YuW5EzWftYNzIQ=
