### ISSUE TITLE
How to kown the notification type?

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#3326]
I received three notification when changed as follows.
I want to kown the difference between them.

->change 1
add data to XXModel table.

->change 2
changed the name of xxxModel.

->change 3
deleted data from xxxModel.

```swift
realm.objects(XXModel).addNotificationBlock{ (result, error) -> () in
           // if change1 

           // if change 2

           // if change 3
}
```

**Comment by mrackwitz** [comment]
We're working on that. See #601 for more info.
