### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by TheHmmka** [realm/realm-cocoa#3327]
## Goals

Hi, I am trying to get access to RLMRealm from didFinishLaunchingWithOptions method.

## Expected Results

Everything should work fine. :-)

## Actual Results

<img width="1280" alt="screenshot 2016-03-14 20 34 22" src="https://cloud.githubusercontent.com/assets/468660/13753485/3657280e-ea24-11e5-8747-f6a4d0a14f01.png">

## Steps to Reproduce

Just try to get access [RLMRealm defaultRealm];

## Code Sample

RLMRealm* realm = [RLMRealm defaultRealm];

## Version of Realm and Tooling

XCode: Version 7.2.1 (7C1002)
Mac OS: 10.10.5 (14F1605)
Realm: 0.98.4

**Comment by bdash** [comment]
Thanks for the report, @TheHmmka. We're tracking this issue via #3321.
