### ISSUE TITLE
OSAtomicCompareAndSwap64Barrier crash when creating default Realm on iPhone 4s

### ISSUE THREAD

**Issue by mitchctodd** [realm/realm-cocoa#3331]
## Goals

Create a default Realm instance.

## Expected Results

A default Realm instance is created without crashing.

## Actual Results

When I try to create the default Realm instance, I experience a crash on my iPhone 4s test device (not using simulator) perhaps related to being a 32-bit device.

#0	0x25ae7c78 in OSAtomicCompareAndSwap64Barrier$VARIANT$mp ()
#1	0x25aec7c6 in _pthread_cond_signal ()
#2	0x002012ba in realm::SharedGroup::low_level_commit(unsigned long long) ()
#3	0x00200e74 in realm::SharedGroup::do_commit() ()
#4	0x002014a2 in realm::SharedGroup::commit_and_continue_as_read() ()
#5	0x00143ea2 in realm::_impl::SharedGroupFriend::commit_and_continue_as_read(realm::SharedGroup&) [inlined] at /Users/realm/workspace/objc_ios/tightdb_objc/core/include/realm/group_shared.hpp:1108
#6	0x00143e9e in realm::LangBindHelper::commit_and_continue_as_read(realm::SharedGroup&) [inlined] at /Users/realm/workspace/objc_ios/tightdb_objc/core/include/realm/lang_bind_helper.hpp:372
#7	0x00143e9e in realm::_impl::transaction::commit(realm::SharedGroup&, realm::BindingContext*) at /Users/realm/workspace/objc_ios/tightdb_objc/Realm/ObjectStore/impl/transact_log_handler.cpp:451
#8	0x00141d28 in realm::Realm::commit_transaction() at /Users/realm/workspace/objc_ios/tightdb_objc/Realm/ObjectStore/shared_realm.cpp:318
#9	0x00141772 in realm::Realm::update_schema(std::__1::unique_ptr<realm::Schema, std::__1::default_delete<realm::Schema> >, unsigned long long) at /Users/realm/workspace/objc_ios/tightdb_objc/Realm/ObjectStore/shared_realm.cpp:254
#10	0x0012bcf0 in +[RLMRealm realmWithConfiguration:error:] at /Users/realm/workspace/objc_ios/tightdb_objc/Realm/RLMRealm.mm:374
#11	0x0012a8fc in +[RLMRealm defaultRealm] at /Users/realm/workspace/objc_ios/tightdb_objc/Realm/RLMRealm.mm:162
#12	0x0009b0aa in -[ViewController viewDidLoad] at /Users/mitch/Documents/Personal/Moto/test/RealmTest/RealmTest/ViewController.m:22

## Steps to Reproduce

1. Create new Single View Application project in Xcode
2. Follow Realm's 'Getting Started' instructions for Static Framework use (same issue experienced with Dynamic Framework)
3. Try and create default Realm instance in viewDidLoad

## Code Sample

this is all my code:

@implementation ViewController

RLMRealm* realmInstance;

- (void)viewDidLoad {
    [super viewDidLoad];

    realmInstance = [RLMRealm defaultRealm];
}

@end

## Version of Realm and Tooling

Realm: 0.98.4
Xcode: 7.2
OS X: 10.10.5
Device: iOS 9.2.1 on iPhone 4s

**Comment by bdash** [comment]
Thanks for the report, @mitchctodd. We're tracking this issue as #3321, and hope to have a fix released in the next couple of hours.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:60604 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMO-001xQn-2p
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:37:56 -0400
Date: Mon, 14 Mar 2016 15:47:46 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457995666;
	bh=171AhWdPCUOamSeWyBZj9wUlWlcQNlrGgitCVYy4Z5A=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lWhFekSzKZMT76OsOibPHpZzfZ1n9nKQL/PN4Q41EFyJpR006uMVS3+Fw2om5By9t
	 Mj1/ltNx8IsgcVhzzNHCQaO2z8XQ3ATUXEqO1P4fe25YHTWG2m9nVsloxE6enSqOqy
	 cR/et2fV4jXVi4AP5BlakAhYSR+mxJBaDxgAOkdU=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (443/400 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:34010 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNm-000b0c-A4
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:36 +0100
Date: Mon, 14 Mar 2016 15:47:46 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457995666;
	bh=pE0gULei9FwVmtgMUdCDKbMRBmYgny396Z/MOAe7Trc=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tDfx5j+pTZqXiBF0te34magQj7nMYiRhdIxihZZnAwHRWhp09DicE+HNxX/+I/x20
	 5F+WFOiqpUGxhNx19OP82ZjnWOm6DTZkM6ckVfn/kKLcGTvWlDfDfbj6ndMCLgjQ9y
	 Jb/cMZqRQOgiK+h14PQEw9P2hNSKIaLdJhZy/Vgg=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (445/400 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 10536 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:45770 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmOW-000bAd-81
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:40:24 +0100
Date: Tue, 15 Mar 2016 03:37:58 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458038278;
	bh=hwIk8F7+XCIUtQIIKce4eR4GxxwXPRhmoNZQOtOx6WM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=b4apAglwHOsIdRlQCjgETetrjWBSFVdnsoWi2Wyui6Nf34H2e9Zvup5un3VLzH8k6
	 kyars/SegLOvXUI1LFyqSdukeaABFvsPw6XEjf6z8ZLgoShmK1GwV27ytt8D1lrCo7
	 BWSTuDZO/hT6e+H4dC/uoPJmX4tWc1h51zwoKW4I=
