### ISSUE TITLE
Realm Browser seems to be not able to open compressed realm files

### ISSUE THREAD

**Issue by victor-kotov-arcadia** [realm/realm-cocoa#3338]
## Goals

I have realm backup copy of the realm DB. I'm trying to open it with Realm Browser app for Mac OS X.

## Expected Results

DB opened and I'm able to check data and structure.

## Actual Results

Realm Browser crashed and next launch it's saying "File encrypted or incompatible".

## Steps to Reproduce

Make backup copy with latest framework version.
Try to open with Realm Browser.

Also: I'm able to open not compressed copy of the DB what was imported into my app from the compressed copy of the DB (so it's not an issues with DB).

## Code Sample

I use code from the Realm guide (section about creation compressed copy of DB for in-bundle usage).

## Version of Realm and Tooling

Realm framework: 0.98.5
Realm browser: 0.97.0 (62)

**Comment by kishikawakatsumi** [comment]
Sorry you've hit this issue, @victor-kotov-arcadia . I've cross-posted this to our Realm Browser repo, realm/realm-browser-osx#145 where we'll continue conversations around this problem.

If you encounter issues with the Realm Browser in the future, please file an issue there. Issues relating to the Realm Objective-C or Realm Swift frameworks can be filed here.
