### ISSUE TITLE
Realm Crash when using in Memory and On Disk realms

### ISSUE THREAD

**Issue by Chris59160** [realm/realm-cocoa#3351]
I have a problem I don't understand with Realm.

Here is the context:

I use an inMemory realm for the data I just want to use across my app view controllers, but I don't want them to be persisted between launches.

It works fine...but as soon as I added a 2nd Realm, used persistently this one, it started crashing when I add a new field to the data saved in the "inMemory" realm.

I can't figure it out. I have tested without using the persistent Realm, and there I can add/remove fields on my inMemory objects and no crash.
But as soon as the persistent realm is created as well, and I add/remove attributes from one of the "inMemory" object, it crashes straight away.

I am using Realm Objective-C 96.3

I create my inMemory realm this way:

                      instance = [[self alloc] init];
                      RLMRealmConfiguration* config = [[RLMRealmConfiguration alloc] init];
                      config.inMemoryIdentifier = @"WeeloyRealmInMemory";

                      NSError* error;
                      instance._in_memory_realm = [RLMRealm realmWithConfiguration:config error:&error];

I create the persistent one this way :

    RLMRealmConfiguration* config = [RLMRealmConfiguration defaultConfiguration];
    config.schemaVersion = CURRENT_CONFIG_SCHEMA;

    NSError* errorRealm;
    RLMRealm* realm = [RLMRealm realmWithConfiguration:config error:&errorRealm];

It crashes on Simulator ios 9.2.1.

I haven't test on physical devices, because I doubt it's device/OS related.

I think it some how points to the same file on the disk, when it shouldn't. 

The error is : [0]	(null)	@"NSLocalizedDescription" : @"Migration is required for object type 'RestaurantRLMObject' due to the following errors:\n- Property '_test_a' is missing from latest object model."	

( I tried delete/add a property, it works fine as long as I am using only one realm, but if I have both, it crashes each time :/ ).

Hopefully it's something stupid I am doing and you can enlight me on what it is.

I have already sent an email to Realm guys, but in case some one else had had the issue and sorted it out, I wanted to post it here too.

**Comment by Chris59160** [comment]
Update on it.

I set up a path on the In-Memory configuration, then I set the in-memory identifier ( so it nullifies the path, but I wanted to be sure, nothing nasty is done by realm with the path).

I have tried like with this update.,...result is that I still get the error when I create the on-disk realm...but if I  increase the CURRENT_CONFIG_SCHEMA number....then the error disappears.

That is not normal behaviour, I have double-checked and the on-disk realm doesn't contain the same objects as the in-memory one...so I still don't understand why the on-disk realm is affected, it makes absolutely no sense.

This happens at the very beginning of the app too, so there's no object in any of the realm either.

If you could help me understand why this is happening ?

**Comment by kishikawakatsumi** [comment]
This issue is followed by https://secure.helpscout.net/conversation/183705997/3451/?folderId=440773

**Comment by fanxiushan** [comment]
I  meet the same issue. How to solve it?

**Comment by mgeerling** [comment]
@fanxiushan , HelpScout is a ticketing system which Realm used to use for support requests.  It is no longer used. 

I took a look over the internal notes and it looks like this user had an error in their schema migration logic.

**Comment by fanxiushan** [comment]
In my case, I found that when I use both memory and disk realm store, my data structure in memory realm will still store my disk realm (only the schema in disk realm,but no data),so when I modify the memory realm schema(ex:I add a field on exsit schema) . Then I launch app, the app crashed.
