### ISSUE TITLE
Obj-C @throw -> NSError ** for graceful Swift exceptions handling

### ISSUE THREAD

**Issue by feighter09** [realm/realm-cocoa#3352]
## Goals

I'd like to gracefully handle Realm transaction errors in Swift, and prevent the app from crashing due to exceptions raised in ObjC code.

## Expected Results

I'd expect the following code to raise an exception that is able to be caught.
```
func doOperation()
{
  do {
    try deleteObject()
  } catch {
    // handle error
  }
}

func deleteObject() throws
{
  realm.beginWrite()
  let object = RealmObject()
  try realm.delete(object)  // object does not exist in the realm, so this will raise an exception
  realm.commitWrite()
}
```
## Actual Results

The exception is `@throw`n in Obj-C code, which Swift cannot handle. As a result, the app crashes rather than catching the thrown exception and handling it accordingly.

```
2016-03-21 17:13:50.372 CoatChex[92393:8528792] *** Terminating app due to uncaught exception 'RLMException', reason: 'Can only delete an object from the Realm it belongs to.'
*** First throw call stack:
(
	0   CoreFoundation                      0x04d8aa14 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x0484be02 objc_exception_throw + 50
	2   Realm                               0x010c5e87 RLMDeleteObjectFromRealm + 167
	3   RealmSwift                          0x01b86065 _TFC10RealmSwift5Realm6deletefS0_FCS_6ObjectT_ + 117
	4   CoatChexTests                       0x14dbcd24 _TFFC13CoatChexTests19RealmJobRunnerTests22testTransactionFailureFS0_FT_T_U_FC10RealmSwift5RealmT_ + 84
	5   CoatChex                            0x000d5d4a _TFC8CoatChex14RealmJobRunner18performTransactionfS0_FzTC10RealmSwift5Realm11transactionFzT5realmS2__T__T_ + 154
	6   CoatChex                            0x000d6a12 _TFFFC8CoatChex14RealmJobRunner18enqueueTransactionFS0_FFzT5realmC10RealmSwift5Realm_T_GC10PromiseKit7PromiseT__U_FTFT_T_FPSs9ErrorType_T__T_U_FT_T_ + 242
	7   CoatChex                            0x000d65cf _TPA__TFFFC8CoatChex14RealmJobRunner18enqueueTransactionFS0_FFzT5realmC10RealmSwift5Realm_T_GC10PromiseKit7PromiseT__U_FTFT_T_FPSs9ErrorType_T__T_U_FT_T_ + 159
	8   CoatChex                            0x000d6cb8 _TTRXFo__dT__XFdCb__dT__ + 40
	9   libdispatch.dylib                   0x05ef49f3 _dispatch_call_block_and_release + 15
	10  libdispatch.dylib                   0x05f126fd _dispatch_client_callout + 14
	11  libdispatch.dylib                   0x05efa33e _dispatch_queue_drain + 1065
	12  libdispatch.dylib                   0x05ef9c89 _dispatch_queue_invoke + 563
	13  libdispatch.dylib                   0x05efb732 _dispatch_root_queue_drain + 442
	14  libdispatch.dylib                   0x05efb571 _dispatch_worker_thread3 + 108
	15  libsystem_pthread.dylib             0x06234270 _pthread_wqthread + 1050
	16  libsystem_pthread.dylib             0x06231f82 start_wqthread + 34
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Steps to Reproduce

1. Set up a write transaction
2. Wrap it in a `try` block as necessary because `write` `throws`.
3. Perform a transaction that will `@throw` an ObjC exception, like deleting an object that doesn't exist in the Realm
4. App crashes due to uncaught exception, even though the entire operation is wrapped in a `try` block

## Code Sample

I've provided a demo app at https://github.com/feighter09/RealmExceptionDemo

## Version of Realm and Tooling

Tested first on Realm `0.96.0`, then upgraded to `0.98.5`. Both were affected
XCode 7.2.1
Cocoapods 0.38.2

## Recommended Path to Happiness

Swift has built in support for error handling by `NSError **`. While I know that `NSError **` is the root of all ObjC evil, it is more aligned with the idioms of ObjC than the `@throw` directive. 
Further, `@throw` is more typically used for operations in which there is no path of recovery, eg `performSelector` has no valid recipient. From Realm's perspective, there's no path to recovery, but the caller has several options for how to handle a failed Realm transaction.

**Comment by tgoyne** [comment]
Realm follows the guidelines of both Foundation and the Swift stdlib of using exceptions in obj-c or `fatalError()` in Swift to report precondition violations and API misuse, and NSError/Swift errors for things which cannot be checked for in advance by the caller. In the example code you gave, trying to delete an object and then catching an exception if it is not a valid object to delete would be needlessly roundabout; instead just first check if the object is in the Realm you are trying to delete it from:

```swift
realm.beginWrite()
let object = RealmObject()
if object.realm == realm {
    realm.delete(object)
} else {
    // do whatever you'd put in your catch block
}
realm.commitWrite()
```

In the places where you can't check in advance if an operation is valid (e.g. when opening a Realm file), we do use NSError/Swift exceptions to report a recoverable error.

**Comment by markst** [comment]
@feighter09 also curious as to how to catch obj-c exceptions in swift. I'm having trouble with our mapping library trying to change the primary key & raising "Primary key can't be changed after an object is inserted." exception which I'd like to catch.

I was looking at implementing something such as:
http://stackoverflow.com/questions/39671519/swift-3-how-to-catch-error-if-nscoder-decodex-function-decodes-wrong-value-type
Although this catches the exception - it seems to deadlock my thread further down the track.

**Comment by jpsim** [comment]
@markst please don't catch Objective-C runtime exceptions thrown by Realm, either in Objective-C *or* Swift. Realm only throws exceptions for _unrecoverable_ errors. Catching these exceptions to work around design constraints in Realm can lead to undefined behavior, including corrupting Realm files.

For recoverable errors, our APIs use `NSError **` pointers in Objective-C, or the `throws` keyword in Swift.

**Comment by feighter09** [comment]
@markst as explained by @tgoyne and @jpsim, the purpose of throwing Obj-C exceptions is different than Swift's `throws`; it's more equivalent to `fatalError()`. My original train of thought was flawed and I don't recommend following it - it's an invalid use of Realm and puts Realm into an error state unnecessarily. Adding the code to guard against invalid operations is a better solution.

On the other hand, there are other situations (strictly in unit tests) in which I've used that exact SO answer to catch Obj-C exceptions, so I think the deadlock is coming from somewhere else

**Comment by markst** [comment]
Thanks for response @jpsim. I follow. Although maybe it's possible for error "Primary key can't be changed after an object is inserted." to be recoverable? 
https://github.com/realm/realm-cocoa/issues/2361

**Comment by akisute** [comment]
I've just hit this issue by `realm.add(object, update: false)` with a duplicated Primary Key on an existing object... It says "Can't create object with existing primary key value %@": Okay now I understand you throw `NSException` because this is *unrecoverable*, yeah I know, but because of this my Swift `do-catch` failover didn't work and caused massive crashes in my production app at a very rare case :(

AS @markst mentioned just before, it is very appreciative to be able to catch errors related to Primary Keys, as sometimes it is really hard to find bugs due to its data structures and feature requirements.

**Comment by feighter09** [comment]
Now that's a fair point - Swift is all about safety at compile time, it would fit the semantics of the language much better (aka more Swifty) to have the compiler point out that you're not handling a potentially critical error, rather than having to read the documentation and write `guard errorCase else { return }` all around
