### ISSUE TITLE
Realm file is currently open in another process which cannot share access with this process.

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#3353]
I pick the "iphone5s","iphone6"..or "iphone6s" simulator,but it doesn't work.
thank you.

![1](https://cloud.githubusercontent.com/assets/3182964/13939498/8d25c0b8-f010-11e5-88a3-bc01710b19ae.jpg)
![2](https://cloud.githubusercontent.com/assets/3182964/13939499/8d26d8c2-f010-11e5-8cbb-f3b54d08db30.jpg)
![3](https://cloud.githubusercontent.com/assets/3182964/13939500/8d273aba-f010-11e5-8974-89725906679b.jpg)

**Comment by bdash** [comment]
Which version of Realm are you using in your application?

**Comment by hengchengfei** [comment]
Realm：0.98.3
RealmSwift：0.98.3

**Comment by bdash** [comment]
Realm v0.98.5, used by Realm Browser v0.98.5, included a change to the format of the lock file. As your application is using an older version of Realm you'll need to use a corresponding version of the Browser that expects the older lock file format. You can find older versions on the [Realm Browser's releases page](https://github.com/realm/realm-browser-osx/releases).

**Comment by hengchengfei** [comment]
I updated to v0.98.5,it does OK.

thank you ,i really appreciate.
