### ISSUE TITLE
How To Close Realm Database

### ISSUE THREAD

**Issue by MickeyHub** [realm/realm-cocoa#3354]
like sqlite, call close method to close database, so what's the close mechanism of realm ?

**Comment by mrackwitz** [comment]
You need to release all accessors you hold to the database.

This includes for Realm Objective-C instances of the following classes:
`RLMRealm`, `RLMResults`, attached instances of `RLMArray`, `RLMDynamicObject` and the user-defined subclasses of `RLMObject`.

For Realm Swift those are:
`Realm`, `Results`, attached instances of `List`, `DynamicObject` and the user-defined subclasses of `Object`.

**Comment by florianlenz** [comment]
I still don't know how I am supposed to close it. I created an instance of the realm database (nothing else) and when I try to open another one (same path) without closing the first (since I don't know how) my app crashes.
