### ISSUE TITLE
how to filter results by special condition

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#3363]
I want to find the GroupCache results that  stocks contains (for example, code = 600600)

> realm.objects(CSFPortfGroupCache).filter("in stocks where code = 600600)")

```swift
public class GroupCache: Object {
    dynamic public var id:String?
    dynamic public var name:String?
    dynamic public var order:Int = 0
    public let stocks = List<StockCache>()
}
```

```swift
public class StockCache: Object {
    dynamic public var code:String?
    dynamic public var name:String?
}
```

**Comment by bdash** [comment]
This will return all `GroupCache`s that have at least one stock with a code of `600600`:
```swift
realm.objects(GroupCache).filter("ANY stocks.code = '600600'")
```

If this isn't what you're after, please clarify which objects you'd like to match.

**Comment by hengchengfei** [comment]
Just i need.

thank you very much!

I really appreciate!

**Comment by bdash** [comment]
Happy to be of help.
