### ISSUE TITLE
Dynamic framework created by older version of the compiler (xcode 7.3)

### ISSUE THREAD

**Issue by mat0pad** [realm/realm-cocoa#3365]
## Goals

Compile RealmSwift.framework again using xcode 7.3.

## Expected Results

That the RealmSwift.framework is built using the new version of the compiler.

## Actual Results

Won't compile with the new xcode version.
Error: Module file was created by an older version of the compiler rebuild "RealmSwift" and try again.

## Steps to Reproduce

Build project using the dynamic framework from realm.io with the new xcode version and that will fail.

## Version of Realm and Tooling

Realm version: 0.98.5

Xcode Version: 7.3 (7D175)

**Comment by jpsim** [comment]
How have you installed `RealmSwift.framework`? Did you drag in a precompiled `.framework` bundle from our release zips? If so, building your project containing that framework with Xcode won't rebuild the framework. See #3355 for more on that.

**Comment by mat0pad** [comment]
So the precompiled RealmSwift.framework can't be used for xcode 7.3 yet? 
When will it be rebuild using the new version?

**Comment by jpsim** [comment]
we'll be making a release with binaries built using Xcode 7.3 in the coming days. Until then, build it from source using one of the methods described in #3355

**Comment by bdash** [comment]
We have just released [Realm Swift v0.98.6](https://github.com/realm/realm-cocoa/releases/tag/v0.98.6), built with Xcode 7.3, to address this issue.
