### ISSUE TITLE
Problems with Realm in XCODE 7.3 and Swift 2.2

### ISSUE THREAD

**Issue by pavlem** [realm/realm-cocoa#3367]
Just installed XCODE 7.3 and cannot build my project because of Realm compiler issues. My project relies heavily on Realm. Please find down below answer to your questions. How can I build it appropriately?

Kind regards,  

## Goals

Build XCODE project which is using realm on XCODE 7.3 (it worked with previous XCODE, before the update) 

## Expected Results

To build my project as usual. 

## Actual Results

"Build failed" happened. 
 Error message is "Module was created by an older version of compiler, rebuild Realm and try again. 

Tried to rebuild from terminal but failed. 

## Steps to Reproduce

In my project just building the file, reports the error. 

## Code Sample

```
import UIKit
import RealmSwift
import Realm
```

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

Xcode 7.3
Build version 7D175

Swift 2.2

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.15
github "realm/realm-cocoa" "v0.98.5"

/usr/bin/git
git version 2.6.4 (Apple Git-63)

**Comment by pnsean** [comment]
Ditto this, I've got the same issue.  Just updated Xcode to 7.3 so I could build on a test device running iOS 9.3, initially I was getting code errors in the Realm pod.  I updated RealmSwift and Realm to the most recent version and I'm seeing the same error as OP

**Comment by cherishloveyou** [comment]
realm is trouble

**Comment by bdash** [comment]
@jpsim's comment in #3355 goes into why you're seeing this error, and what you can do to work around it. It boils down to having Carthage build Realm from source rather than using pre-built binaries, as pre-built binaries of Swift frameworks require that you're using the same version of Xcode that a Realm release was built with.

**Comment by FabianMerkle** [comment]
@bdash the suggestion in #3366 is not working when Uploading to AppStore. 
Building from `RealmSwift-swift2.2` is compiling but when Uploading the archive to iTunes Connect it says: ERROR ITMS-90097: "Unsupported Architectures...RealmSwift.framework contains unsupported architectures [x86_64, i386]" and ERROR ITMS-90209: "Invalid Segment Alignment" and ERROR ITMS-90125: "The binary is invalid".

**Comment by bdash** [comment]
It sounds like your project is missing the script phase to remove the simulator slices from the Realm frameworks when building for devices. See the [final step in the installation instructions](https://realm.io/docs/swift/latest/#getting-started) of both the Dynamic Framework and Carthage approaches to integrating Realm into your project.

**Comment by FabianMerkle** [comment]
@bdash it worked. Had to add the Dynamic Framework instruction, even though I have Carthage set up. thanks.

**Comment by bdash** [comment]
We have just released [Realm Swift v0.98.6](https://github.com/realm/realm-cocoa/releases/tag/v0.98.6), built with Xcode 7.3, to address this issue.
