### ISSUE TITLE
Object losing RLMArray values after partial update

### ISSUE THREAD

**Issue by Rich86man** [realm/realm-cocoa#3368]
When trying to partially update an object using createOrUpdateInDefaultRealmWithValue:, which has a RLMArray property, I expected the array to contain the objects that were inside of it before the partial update was applied. Instead after updating the objects properties other than the array property, the array's contents were no longer present.

```objc
[[RLMRealm defaultRealm] beginWriteTransaction];
SCUser *user = [[SCUser alloc] init];
user.serverId = @20;

SCRoom *room = [[SCRoom alloc] init];
room.serverId = @10;
[room.admins addObject:user];
[SCUser createOrUpdateInDefaultRealmWithValue:user];
[SCRoom createOrUpdateInDefaultRealmWithValue:room];
[[RLMRealm defaultRealm] commitWriteTransaction];

room = [SCRoom objectForPrimaryKey:@10];
XCTAssert(room.admins.count == 1); // pass


[[RLMRealm defaultRealm] beginWriteTransaction];
SCRoom *room2 = [[SCRoom alloc] init];
room2.serverId = @10;
room2.name = @"Slideshow Bob";
[SCRoom createOrUpdateInDefaultRealmWithValue:room2];
[[RLMRealm defaultRealm] commitWriteTransaction];

room = [SCRoom objectForPrimaryKey:@10];
XCTAssert(room.admins.count == 1); // fail
```
Here's a link to the classes used above
https://gist.github.com/Rich86man/dcb91236950294c1e875

```
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

/Applications/Xcode.app/Contents/Developer
Xcode 7.3
Build version 7D175

/Users/richardkirk/.rbenv/shims/pod
0.39.0
Realm (0.98.5)
Realm (~> 0.98.5)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.12.0
(not in use here)

/usr/local/bin/git
git version 2.7.1
```

Is there something that I'm doing incorrectly? I've been pulling my hair out over this for a few hours now. 
A few things I've tried so far
1. assigning NSNull to the admins object right before calling createOrUpdate
2. Making [NSNull null] the default property value for admins

Any help would be greatly appreciated

**Comment by bdash** [comment]
Partial updates of an object cannot be performed by passing an instance of an `RLMObject` subclass to `+createOrUpdateInDefaultRealmWithValue:`. The reason for this is that there's no way to represent _don't update this property_ for a property on your `RLMObject` subclass. You'll instead want to pass a dictionary to `+createOrUpdateInDefaultRealmWithValue:`, where the absence of a given key represents _don't update this property_. Alternatively, you can fetch the existing object from the Realm and mutate the properties that you wish to update.

**Comment by Rich86man** [comment]
Thanks for the prompt feedback! Thats a bummer. I'm going to have to do some rewriting of my json -> object code.
