### ISSUE TITLE
 Module file was created by an older version of the compile - Xcode 7.3 - WatchOS 2.2 

### ISSUE THREAD

**Issue by andre991** [realm/realm-cocoa#3371]
## Goals

What do you want to achieve?
Build my project.
## Expected Results

What did you expected to happen?

Run the project

## Actual Results

What did happened instead?  
 Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

include the RealmSwift.framework for watchOS in your project and Build.

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 0.98.5

Xcode version: 7.3

iOS/OSX version: 9.3

watchOS version: 2.2

Dependency manager + version: Carthage 0.15.2
<img width="303" alt="captura de tela 2016-03-24 as 21 23 26" src="https://cloud.githubusercontent.com/assets/8302454/14034934/0e66ea06-f207-11e5-8abe-449a8adf2500.png">

**Comment by bdash** [comment]
We have just released [Realm Swift v0.98.6](https://github.com/realm/realm-cocoa/releases/tag/v0.98.6), built with Xcode 7.3, to address this issue.

**Comment by andre991** [comment]
Ok. Thanks bdash. The Realm is amazing. Congratulations and have a nice day.

**Comment by faklyasgyuri** [comment]
@bdash I have the same problem with xCode 8.04 beta and swift 3. Are you going to release a new version or shall I use xCode 7.3? Thanks

**Comment by bdash** [comment]
We will release a version of Realm that supports Xcode 8 once a GM release of Xcode 8 is available. Until then you'll need to build Realm from source from our master branch to use it with Xcode 8.
