### ISSUE TITLE
Pushing RealmSwift spec to CocoaPods fails due to Swift 2.2 deprecation warnings

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#3375]
The `push_cocoapods` job failed with these errors:
```
Validating podspec
 -> RealmSwift (0.98.6)
    - WARN  | xcodebuild:  RealmSwift/RealmSwift/RealmCollectionType.swift:50:5: warning: use of 'typealias' to declare associated types is deprecated; use 'associatedtype' instead
```

I re-ran locally with `--allow-warnings` to work around this. We may need to add that flag to the job for now, or find some way to fix the code to avoid the warning.

**Comment by jpsim** [comment]
We no longer have Swift warnings because we dropped support for Swift versions older than 2.2.
