### ISSUE TITLE
"Operation not permitted" when trying using Realm in iOS Keyboard Extension with App Groups

### ISSUE THREAD

**Issue by filippovdev** [realm/realm-cocoa#3376]
I create iOS Keyboard Extension, I want share database between  iOS App and keyboard extension using App Groups. In iOS app I configure Realm like that:

```
let directory: NSURL = NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier("group.myAppGroup")!
var config = Realm.Configuration()
config.path = directory.URLByAppendingPathComponent("db.realm").path
Realm.Configuration.defaultConfiguration = config
```
In iOS app everything work great, I can read and write to this file. But in Extension I make same config and when I try to do:

`let realm = try! Realm()`

I receive an error:
Optional("/private/var/mobile/Containers/Shared/AppGroup/D7E1F908-1918-4C76-8843-EEF9624E86D7/db.realm")
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Operation not permitted" UserInfo={NSFilePath=/private/var/mobile/Containers/Shared/AppGroup/D7E1F908-1918-4C76-8843-EEF9624E86D7/db.realm, NSLocalizedDescription=Operation not permitted, Error Code=2}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.1/src/swift/stdlib/public/core/ErrorType.swift, line 54

**In iPhone Simulator everything working ! Only on real Device I have an error.**

## Goals

Use Real in iOS Keyboard Extension

## Expected Results

Realm is working

## Actual Results

Crash on init

Realm version: 0.98.6

Xcode version: 7.3

iOS/OSX version: 9.3

Dependency manager + version: Cocoapods 0.39

**Comment by filippovdev** [comment]
You should set RequestsOpenAccess to YES in Info.plist then it can access the files.

**Comment by jeffreyhanna** [comment]
Could someone help me understand _why_ this is necessary? I was already using app groups to share UserDefaults between my app and keyboard extension without needing RequestsOpenAccess on. The setting isn't as much of a problem as getting users to turn it on. The flow is annoying and the purpose is not obvious to users.

**Comment by bdash** [comment]
From [Apple's documentation on App Extension Keys]( https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/AppExtensionKeys.html#//apple_ref/doc/uid/TP40014212-SW24)

> ## RequestsOpenAccess
> `Boolean` - iOS. Specifies whether a custom keyboard wants access to such resources as a shared container (shared with the containing app) and network access. Default value is NO. If you set this key’s value to YES, your keyboard gains a variety of capabilities:
> * Network access, supporting server-side processing of keystrokes
> * Shared container access with the keyboard’s containing app, supporting features such as an editing interface for the keyboard’s custom autocorrect lexicon
> * Access to Location Services and the Address Book database, with user approval
> * Via containing app, ability to participate in Game Center and In-App Purchase
> * Ability to to work with managed apps, if custom keyboard supports mobile device management (MDM)
> This key is supported in iOS 8 and later.

Presumably this key is necessary to avoid exfiltrating data a user types in a keyboard without the user's knowledge.

**Comment by jeffreyhanna** [comment]
It just seems odd that I can already share data with the host app through UserDefaults, but to share data in any other form requires this setting. Couldn't a malicious dev keylog through UserDefaults without this if they wanted?

**Comment by bdash** [comment]
If it behaves as you state, it does seem odd. You'd need to ask Apple why it's set up like it is.
