### ISSUE TITLE
Realm browser support

### ISSUE THREAD

**Issue by foobar8675** [realm/realm-cocoa#3382]
Hello, I'm not sure where to ask, but was wondering if there are any plans to support browsers?

**Comment by bdash** [comment]
Can you clarify what you mean by "support browsers"?

**Comment by foobar8675** [comment]
sorry I wasn't clear. I was thinking something like https://pouchdb.com/ our swift app uses realm and our android react native one will too. I was thinking it would be nice if our web app did the same, to minimize re-learning.

**Comment by jpsim** [comment]
This is the wrong place to track adding server-side language bindings, but feel free to email info@realm.io or [tweet realm](https://twitter.com/realm) to express your desire for such products!
