### ISSUE TITLE
How to create realm optional property  in swift

### ISSUE THREAD

**Issue by priya-vr** [realm/realm-cocoa#3386]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@priya-vr 
If you'd like to create optional type of object type (`String`, `NSDate` or `NSData`), you can just declare the properties as optional, like the following:

```swift
class Person: Object {
    dynamic var name: String? = nil
}
```

If create optional type for `Int`, `Float` or `Double`, you should wrap the value with `RealmOptional<T>`, like the following:

```
class Person: Object {
    let age = RealmOptional<Int>()
}
```

Plese see also https://realm.io/docs/swift/latest/#optional-properties

**Comment by priya-vr** [comment]
Thanks @kishikawakatsumi

**Comment by magnett** [comment]
Unfortunately setting optional Int, Float or double doesn't work when using swift models with the obj-c version of the pod.

**Comment by austinzheng** [comment]
Please create a new issue, filling out the Issue Template, rather than commenting on closed issues. Thank you!
