### ISSUE TITLE
“Realm must not be nil” is crashed  in release package. but In debug state is OK, why ???

### ISSUE THREAD

**Issue by codesourse** [realm/realm-cocoa#3387]
“Realm must not be nil” is crashed  in release package.
but In debug state is OK,
why ???
[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 0.96.3

Xcode version: 7.3

iOS/OSX version: 9.3

**Comment by kishikawakatsumi** [comment]
@codesourse The error occurs when failed to instantiate the Realm. Can you show your piece of code around instantiating the Realm? Is there a difference in the file path for Realm between debug build and release build?

**Comment by codesourse** [comment]
Thank you ,I use the lastest version. I have solved it.
It maybe because of using the old version's "Realm.podspec" file.

**Comment by jpsim** [comment]
I'm glad you solved this. In the future, please make sure to fill out the new issue template carefully to provide more information, which will make it easier for us to help you. Thanks!
