### ISSUE TITLE
Can't enumerate objects in migration after deleting

### ISSUE THREAD

**Issue by mladjan** [realm/realm-cocoa#3390]
I'm doing simple STLUser migration because we added new fields in STLUser model.
We are doing this like that: http://hastebin.com/iduyemuxol

Problem happens when we migrate from v7 to v8.

The problem is, that on some cases to some users (not all), migration fails: http://cloud.blgrd.co/413q3r45180T

The reason is that newObjects array has two more objects, and I don't have idea why.
Few more screenshots:
http://cloud.blgrd.co/2b3F44451v2g
http://cloud.blgrd.co/0v1a03320D0i

Has anybody clue why this is happening?

**Comment by jpsim** [comment]
Sorry you're affected by this issue, this is the first report of unmatched old/new migration objects we've ever seen. Could you please share a bit more information so that we can better identify what may have caused this? Please share:

1. The versions of Realm shipped with your app alongside schema versions 7 & 8.
2. Your `STLUser` model definitions for schema versions 7 & 8.
3. Any other relevant information that could help identify why this happened to a subset of users. What's unique (if anything) about the users affected compared to those unaffected?
  1. iOS version.
  2. iOS device.
  3. Number of `STLUser` objects in both the old and new Realms.

The best way to make progress on identifying what may have caused this would be to attempt to reproduce the configuration that lead to this issue, so if you manage to find and share reproducible steps with us, that would greatly accelerate the process.

Thanks!

**Comment by mladjan** [comment]
Hi guys,
1. Both versions have 0.97 ObjC
2. Changes in STLUser model are: http://cloud.blgrd.co/3J3a3h3a2A1X
In v8 model STLUser: http://cloud.blgrd.co/2e0Y1G1U3T3a
In v7 model STLUser: http://cloud.blgrd.co/0Y3h3y0F2h0p
3.1. iOS 9.2
3.2. iPhone 6+
3.3. Based on that screenshots we can see: http://cloud.blgrd.co/413q3r45180T 
old objects: 545
new objects: 542

Note: its happening only for some users, not all of them.

**Comment by jpsim** [comment]
Reading your migration code again, the error is clear: objects from the new Realm are being deleted and then old & new objects are being enumerated:

```objc
if (oldSchemaVersion < 6) {
    [migration enumerateObjects:STLUser.className block:^(RLMObject * _Nullable oldObject, RLMObject * _Nullable newObject) {
        STLUser *oldUser = (STLUser *)oldObject;
        if ([[oldUser objectForKeyedSubscript:@"id"] integerValue] == 0) {
            [migration deleteObject:newObject]; // <= some objects are deleted from the new Realm
        }
        // ...
    }];
}
// ...
if (oldSchemaVersion < 8) {
    // ...
    [migration enumerateObjects:STLUser.className block:^(RLMObject * _Nullable oldObject, RLMObject * _Nullable newObject) {
        // this attempts to iterate over old & new objects assuming no deletions have happened
    }];
}
```

This highlights a fairly concerning design issue with creating or deleting objects during migrations where old and new objects could be mismatched if previous enumerations create or delete objects...

In the meantime, the only way I can think of to avoid this is to not use `-[RLMMigration deleteObject:]`. I'm bringing up this issue internally to consider ways we can improve this and will update this issue as soon as I have more to share.

**Comment by mladjan** [comment]
That was done because I had a problem before where some objects was without id (not sure why), but this was for 5 to 6 migration. Now is 7 to 8.

**Comment by jpsim** [comment]
How are you sure that users affected by this were on version 7? If a user was on version 5 or less, they would go through both codepaths, leading to this issue.

**Comment by mladjan** [comment]
Will try to remove this code and try. Current users will still need to reinstall because their data is corrupted, but lets hope this don't happen again :)

**Comment by jpsim** [comment]
This shouldn't have corrupted any data. The app will just crash with the code as-is if a user is migrating from schema of 5 or less to 8 or more.

Here's a question for you: the code you shared at http://hastebin.com/iduyemuxol, if your `enumerateObject:` blocks are empty, you don't need to enumerate at all.

Another thing you can do is move the object deletion to the very end of your migration.

**Comment by icanzilb** [comment]
Same happens with Swift and Realm 1.0.0 - if you delete some objects, and then enumerate again over the same object type, the code crashes because the enumerator doesn't take in consideration the reduced number of objects.

**Comment by jpsim** [comment]
Yes @icanzilb, that's why this ticket is still open and tracked as a P1.

**Comment by nigarcia88** [comment]
I'm still seeing this issue on Realm 1.1.0 Obj-C. Got knowledge of this because got some reports of a user having app crashes on migration. Any updates on this? In any case, I will apply @jpsim tips to try to avoid the issue if possible. Thanks
