### ISSUE TITLE
Using xcode 7.3 to compile 0.98.6 breaks semver

### ISSUE THREAD

**Issue by danroberts** [realm/realm-cocoa#3394]
This throws an error when I upgrade with carthage that the framework has been built with a later version of Xcode than I am currently using (7.2.1). Not a major issue, but I think that it could be worth a bump to 0.99

**Comment by bdash** [comment]
Technically semantic versioning says that with a major version of 0, anything may break at any time. I take your point though, and we'll keep it in mind if a similar situation occurs in the future.

**Comment by jpsim** [comment]
[SemVer](http://semver.org/) states:

> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

That being said, we do increase the minor version whenever we introduce a breaking change, *but* we don't treat language changes as breaking changes.
