### ISSUE TITLE
optimisation of sample - tableview / swift 

### ISSUE THREAD

**Issue by johndpope** [realm/realm-cocoa#3403]
so I modified this function to insert 50k of rows instead of 5. 
```swift
func backgroundAdd() {
    let queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)
    // Import many items in a background thread
    dispatch_async(queue) {
        // Get new realm and table since we are in a new thread
        let realm = try! Realm()
        realm.beginWrite()
        for _ in 0..<50000 {
            // Add row via dictionary. Order is ignored.
            realm.create(DemoObject.self, value: ["title": TableViewController.randomString(), "date": TableViewController.randomDate()])
        }
        try! realm.commitWrite()
    }
}
```

on subsequent re-runs - the app is loading the entire database from this line.

    let array = try! Realm().objects(DemoObject).sorted("date")

In the past with SQLITE  - I've used some granularity to fetch a single row / and inflate the object where it's equal to an id.

eg. row id = 10 / SELECT * FROM Users LIMIT 1 OFFSET 10

from here - I avoid blocking the ui thread for showing 10 rows on the screen.
Does such a sample exist?

**Comment by bdash** [comment]
Realm objects and their properties are loaded from the database only when they're accessed. Performing a query on a class with 50,000 instances in the database does not allocate 50,000 objects in memory, nor does it copy all of the object's properties into memory. This laziness negates the need for the sort of paginated queries that you might use in SQLite to avoid copying too much data into memory or allocating too many objects.

**Comment by johndpope** [comment]
Hypothetically - if you switch the 50k to 500k and click add a couple of times - I'm seeing boot delays up to 40 seconds.

**Comment by johndpope** [comment]
Ok my bad - on closer inspection - the app is performing great when I drop the sorting. 
    let array = try! Realm().objects(DemoObject)//.sorted("date")
Are there any internal mechanisms to handle indexes to optimise performance?

**Comment by bdash** [comment]
Are you measuring with a debug or release build of Realm? In my testing there's a significant difference in performance on this particular scenario between the two types of build.

We do not yet use indexes for sorting. Doing so would clearly be a win in this situation.
