### ISSUE TITLE
Question about dynamic booleans

### ISSUE THREAD

**Issue by istx25** [realm/realm-cocoa#3404]
Hi everyone, I'm not sure if this is a bug in Realm (or Swift) or if there is a reason, but I was wondering if someone could help explain why this doesn't work.

```swift
import RealmSwift

class SomeObject: Object {

    // Build Error:
    // Property cannot be marked dynamic 
    // because its type cannot be represented in Objective-C.
    dynamic var someBoolean: Bool!

    // Completely OK.
    dynamic var someOtherBoolean: Bool = false

    // Completely OK.
    var someBoolean: Bool!
}
```

What we know?

- having a default value (boolean) on a `dynamic var` works.
- not having a default value causes the build error from above.
- non `dynamic var`'s can be implicitly unwrapped. 

Any ideas why?

**Comment by jpsim** [comment]
`Bool!` is an implicitly unwrapped optional, which cannot be represented in the Objective-C runtime. Realm requires that object properties be accessible by the Objective-C runtime in order to replace setters & getters for those properties.

**Comment by istx25** [comment]
Ohhh, okay. That makes sense.

**Comment by istx25** [comment]
Thanks, @jpsim!
