### ISSUE TITLE
RLMResult notification triggers even the object never exist in the result

### ISSUE THREAD

**Issue by zenghaojim33** [realm/realm-cocoa#3405]
Hey guys, I am using the results notification feature in my project but I found that even RLMResult is empty, changing other objects of the same class in the same realm will still trigger the notification block, like this :
`RLMResults * results = [CBMessage ObjectsWhere:@"orderoptype = 123123123321321"]; //this object will never exist in the RLMResults` 

`    self.token = [results addNotificationBlock:^(RLMResults * _Nullable results, NSError * _Nullable error)` `{`
             `           DLog(@"It shouldn't happen but it does");`
 `  }]; `

Is it a bug? Or am I using it in the wrong way?

**Comment by tgoyne** [comment]
From the [documentation](https://realm.io/docs/objc/latest/api/Classes/RLMResults.html#/c:objc(cs)RLMResults(im)addNotificationBlock:):

> The determination for whether or not a write transaction has changed the results is currently very coarse, and the block may be called even if no changes occurred. The opposite (not being called despite changes) will not happen. This will become more precise in future versions.

The future changes mentioned is https://github.com/realm/realm-cocoa/pull/3359.
