### ISSUE TITLE
Realm Swift NSDate's after sorting

### ISSUE THREAD

**Issue by davros1970** [realm/realm-cocoa#3408]
Hi,

Love Realm Swift, but having a problem with NSDates after sorting. Using 0.98.6

Using Realm Browser, I can clear see my dates in the database well formed.
e.g. 'Jun 8, 1942, 12:00:00 AM'

When I pull the objects out of Realm, the dates are still well-formed.
```
episodes = realm.objects(Episode)
```

However, if I apply a sort to it, then the dates get wonky
```
episodes = realm.objects(Episode).sorted("airdate", ascending: true)
```

e.g. 'Jun 8, 42'. Somehow 1900 got lost?!

property 'airdate' is a NSDate
```swift
class Episode: Object {
    dynamic var airdate = NSDate()
}
```
Thx in advance!
Dave

**Comment by mrackwitz** [comment]
Hi Dave! May I ask whether you double-checked that some episodes in your database were not just accidentally created with a wrongly parsed date, which is actually in the year `42`? Those would logically appear all of the sudden in the beginning if you sort ascending by date. If that shouldn't be the case, it would be helpful if you could share your database with us (privately to help@realm.io), so that we can figure out what's wrong there.

**Comment by davros1970** [comment]
Hi,

DB should be clean. Im fine with sharing it privately. I did find a 'fix' last night which is more on me than Realm. I had a buggy NSPredicate in the equation there. Once I fixed that, then my dates came out sensibly. I'm not sure why that hosed the dates to begin with as the incorrect predicate wound up giving me a list of everything from the DB (12K+ records instead of expected 100). Might be a memory thing?

My happy version:
```
let showTitlePredicate = NSPredicate(format: "show.title = %@", show.title)
self.episodes = realm.objects(Episode).filter(showTitlePredicate).sorted("airdate", ascending: true)
```

And then my buggy sad version:
`
self.episodes = realm.objects(Episode).filter("show.title = show.title").sorted("airdate", ascending: true)
`

I'll send you the realm DB privately and you can play with it. Maybe there's a small improvement in there for Realm, but it was mostly my bad coding.

-Dave

**Comment by bdash** [comment]
Please feel free to share the Realm file with us at help@realm.io so we can investigate further.

**Comment by jpsim** [comment]
Closing this since we haven't heard back from @davros1970 in over two weeks.
