### ISSUE TITLE
Add Xcode Version 7.3 (7D175) compatibility to Realm Plugin

### ISSUE THREAD

**Issue by bcicube** [realm/realm-cocoa#3409]
HI,

"Open Realm Browser" submenu in Xcode "View" menu does not appear when I run an app using Realm on simulator. Please get required UUIDs added.

Thanks

**Comment by kishikawakatsumi** [comment]
@bcicube That had been done several days ago https://github.com/realm/realm-cocoa/pull/3388
Can you reload Alcatraz repository and retry it?

Also, "Open Realm Browser" submenu in Xcode "View" menu is the feature of Realm Browser Plugin. https://github.com/kittinunf/RealmBrowser-Plugin

This is not our product. Can you report this to that repository?

**Comment by jpsim** [comment]
This was added in #3388.
