### ISSUE TITLE
NSString and NSDate property values are removed after migration, when property goes in requiredProperties

### ISSUE THREAD

**Issue by rsahara** [realm/realm-cocoa#3413]
## Goals

Migrate a realm db, keeping old property values if the type of that property is not changed.

## Expected Results

Before migration: NSString nullable property: value "hello world"
After migration: NSString non nullable property: value "hello world"

Before migration: NSDate nullable property: value 2016/04/06 11:45:51
After migration: NSDate non nullable property: value 2016/04/06 11:45:51

## Actual Results

Before migration: NSString nullable property: value "hello world"
After migration: NSString non nullable property: value ""

Before migration: NSDate nullable property: value 2016/04/06 11:45:51
After migration: NSDate non nullable property: value 1970/01/01 9:00:00

Check models ModelSearchParam and ModelTab in the attached realm files persistent_before.realm and persistent_after.realm.
[persistent.zip](https://github.com/realm/realm-cocoa/files/206107/persistent.zip)

## Steps to Reproduce

Perform a migration by moving a property from nullable to non nullable without changing its type/name.

## Code Sample

```
@interface ModelTab : RLMObject
@property NSDate*	modelUpdate;
@property BOOL		modelDelete;
@property NSString* tabId;
@property NSString* tabTitle;
@property int		tabIndex;
@property int		tabType;
@property int		siteId;
@property ModelSearchParam*	searchParam;
@property int		tabParam;
@end

@implementation ModelTab
+ (NSString*)primaryKey {
	return @"tabId";
}
+ (NSDictionary *)defaultPropertyValues {
	return @{
			 @"modelUpdate":[NSDate date],
			 @"modelDelete":@NO,
			 @"tabId":[[NSUUID UUID] UUIDString],
			 @"tabTitle":@"",
			 @"siteId":[NSNumber numberWithInt:ModelSiteIdWomen],
			 @"tabParam":[NSNumber numberWithInt:ModelTabParamNone],
			 };
}
// Just added this method in v. 96 (previous v. is 87)
+ (NSArray *)requiredProperties {
	return @[
			 @"modelUpdate",
			 @"tabTitle",
			 ];
}
@end
```

## Version of Realm and Tooling

Realm version: 0.96.3 (same issue with 0.98.6 linked to the app that perform the migration)

Xcode version: 7.0.1

iOS/OSX version: 9.0

Dependency manager + version: CocoaPods 0.39.0

**Comment by kishikawakatsumi** [comment]
@rsahara 

I think you need to copy old value to new properties in migration block. Like the following:

```objc
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
config.schemaVersion = 88;
config.migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {
    [migration enumerateObjects:[ModelTab className] block:^(RLMObject * _Nullable oldObject, RLMObject * _Nullable newObject) {
        ...

        if (oldSchemaVersion < 88) {
            // You should copy old value to new properties
            newObject[@"tabTitle"] = oldObject[@"tabTitle"]; 
            newObject[@"modelUpdate"] = oldObject[@"modelUpdate"];
        }
    }];
};

RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:nil];
...
```

Perhaps you only increment schema version though, but you didn't write migration block, right?

**Comment by rsahara** [comment]
@kishikawakatsumi 
That's what I did for our current update, when I realized those values were not automatically migrated. It works, but I considered it to be a workaround. I'd appreciate if you can improve this behavior, I believe this kind of migration can be done automatically by the library.
I don't think many people would prefer 1970/01/01 9:00:00 than the old value.
If it is too specific to our case, maybe some warnings or documentation on this behavior would be helpful, because 1970/01/01 9:00:00 was specified nowhere in our project and the migration ended without any warning/error log.
Thanks!

**Comment by kishikawakatsumi** [comment]
It is intended behaviour now, but your thought seems reasonable for me. We'll discuss to support save old value in the auto migration and document the behaviour more clearly. Also considering more verbose logs.

Thank you for pointing out it!
