### ISSUE TITLE
Notifications between Realms

### ISSUE THREAD

**Issue by sochalewski** [realm/realm-cocoa#3416]
## Goals

Notifications between different `Realm.objects()`

## Expected Results

Notifications passed between different `Realm.objects()`

## Actual Results

There are no notifications

## Steps to Reproduce

I've got multiple active `UIViewControllers` placed on `UITabBarController`. Each view controller has its own Realm. Each Realm returns all objects with `objects()`. Changes made in one view controller are not visible for others.
I investigated and it's because different objects' memory addresses. I store my records within a `Results` class and don't cast them to i.e. an `Array`.

## Code Sample

These code sample has two `Results` from Realm in the same class.

```swift
let objects1 = records()
let objects2 = records()

override func viewDidLoad() {
    super.viewDidLoad()

    // Nothing happen here
    objects2?.addNotificationBlock({ (results, error) in
        print("\(results), \(error)")
    })

    objects1?.first?.delete()
}

func records() -> Results<Record>? {
    let realm = try? Realm()
    if let realm = realm {
        return realm.objects(Record)
    } else {
        return nil
    }
}
```

```swift
extension Record {
    func delete() {
        let realm = try? Realm()
        try! realm?.write {
            realm?.delete(self)
        }
    }
}
```

Here goes my debugger prints proving that objects are not given by reference.

```
(lldb) p objects1
(RealmSwift.Results<Project.Record>?) $R0 = 0x000000015e6e8620 {
  RealmSwift.ResultsBase = {
    ObjectiveC.NSObject = {}
    rlmResults = 0x000000015e6e8a40 {
      ObjectiveC.NSObject = {}
    }
  }
}
(lldb) p objects2
(RealmSwift.Results<Project.Record>?) $R1 = 0x000000015e6e8d50 {
  RealmSwift.ResultsBase = {
    ObjectiveC.NSObject = {}
    rlmResults = 0x000000015e6e9180 {
      ObjectiveC.NSObject = {}
    }
  }
}
```

Should I use Realm as singleton? Is it even allowed or recommended?

## Version of Realm and Tooling

Realm version: 0.98.6

Xcode version: 7.3

iOS version: 9.3.1

Dependency manager + version: CocoaPods 0.39.0

**Comment by kishikawakatsumi** [comment]
@sochalewski 
Because you didn't hold `NotificationToken` instance when you add the notification. So the notification token deallocated immediately the method passed. That's why the notification block was not called at all.


> The notification stays active as long as a reference is held to the returned notification token. You should hold onto a strong reference to this token on the class registering for updates, as notifications are automatically un-registered when the notification token is deallocated.

https://realm.io/docs/swift/latest/#notifications

Can you try like the following?

```swift
let objects1 = records()
let objects2 = records()

var token: NotificationToken? // Add a property to hold notification token 

var token: NotificationToken?

override func viewDidLoad() {
    super.viewDidLoad()

    // Nothing happen here
    token = objects2?.addNotificationBlock({ (results, error) in // Hold notification token
        print("\(results), \(error)")
    })

    objects1?.first?.delete()
}
```

**Comment by sochalewski** [comment]
Thank you! That works well :)
