### ISSUE TITLE
reads immediately after writes in blocks is often stale

### ISSUE THREAD

**Issue by foobar8675** [realm/realm-cocoa#3428]
i'm noticing when i do a write in a block and read off in another thread from a notification, the read data is often stale. (as in the first commented block) however the second uncommented block seems ok. is this normal or am I just missing something?

````
// does not work
// try! realm.write({ () -> Void in
//                    realmObj.state = newState
//                })
                
// does work
                realm.beginWrite()
                realmObj.state = newState
                try!realm.commitWrite()
                 NSNotificationCenter.defaultCenter().postNotificationName(NOTIFICATION_FOR_READING_UPDATED_DATA, object: nil)

````

**Comment by mrackwitz** [comment]
These two variants should be functionally equivalent. What do you mean by stale read data?

**Comment by foobar8675** [comment]
i see it happening in my much more complicated project, but i can't reproduce it in a simple test project.

**Comment by bdash** [comment]
If you're performing the write on a different thread or queue than the one that you are later reading the stale data on, the problem may be that you're not calling [`Realm.refresh()`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm7refreshFT_Sb) prior to reading the data.

**Comment by foobar8675** [comment]
you know, that is probably it. so there should be no difference in behavior between the two different ways of writing in regards to pointing to the most recent realm?

**Comment by bdash** [comment]
There should be no difference, no.
