### ISSUE TITLE
The size of watch application has exceeded the 50MB size limit.

### ISSUE THREAD

**Issue by ziadtamim** [realm/realm-cocoa#3430]
I'm using Realm via Cocoapods. I can see that Realm.framework is 17.7 MB in the WatchOS2 which makes it return the error of **"Size Limit Exceeded. The size of watch application (55MB) has exceeded the 50MB size limit."**

**Comment by jpsim** [comment]
There's not a whole lot we can do here. Watch frameworks are required to have bitcode, which takes up a large portion of that space. We constantly keep an eye on binary sizes, and occasionally find ways to shave binary size by a few percent here and there, but ultimately you won't see a version of Realm at 1MB any time soon.

Your best bet is to either remove some of the other code or assets that contribute to the remaining 37MB of your watch app, or to stop using Realm in your watch app altogether.

**Comment by bdash** [comment]
Do bitcode slices really contribute towards the app size limit? Bitcode never makes it to a user's device so it seems strange for Apple to count against the size of the app.

For the record, bitcode takes up close to 14MB of Realm.framework for watchOS. Realm.framework with the watchOS simulator and bitcode portions of the binary removed weighs in at around 3.5MB.

**Comment by jpsim** [comment]
Closing since there's not much we can do here.

**Comment by SuperBarracuda** [comment]
Sometimes you need to watch out that system libraries aren't being linked twice. I had the same issue with private pods that I created using the frameworks option.

http://stackoverflow.com/a/33490415
