### ISSUE TITLE
Some Realm errors don't include sufficient detail to understand their cause

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#3438]
In #3426 a user is seeing an error message of `Unable to open a realm at path '…/foo.realm'`. This error message appears to be generated in the following cases, and possibly others:

1. Opening a file that does not contain a valid Realm file header.
2. Attempting to open an encrypted Realm file with an incorrect encryption key.
3. Attempting to open a directory as a Realm file, or other POSIX-level errors when opening the Realm file.

In the first case we should make it clear that what is being opened is not a valid Realm file.

In the second case we should make it clear that either the encryption key is incorrect or the file is not a valid Realm file (the two cases are indistinguishable).

For other errors that occur when opening the Realm file we should preserve as much information as is possible (e.g., the underlying `std::system_error`, or `errno` value) and use it to populate `NSUnderlyingErrorKey` in the `NSError` we return.

**Comment by fisch0920** [comment]
Currently running into this and would really love this improvement.

Thanks for all your hard work!!

**Comment by austinzheng** [comment]
I pushed a change which should make future errors more descriptive. Please feel free to file another ticket if the next release of Realm Cocoa still has insufficiently descriptive errors.

**Comment by fisch0920** [comment]
Thanks @austinzheng!
