### ISSUE TITLE
Existing code no longer compiles when upgrading from 0.98.6 to 0.98.7

### ISSUE THREAD

**Issue by AndrewBarba** [realm/realm-cocoa#3443]
In response to this conversation: https://github.com/realm/realm-cocoa/commit/7a11e69c6e0a2af65d869a6fdb58a7611be70a0f

Here is the class that compiled in 0.98.6:

```swift
import Foundation
import ObjectMapper
import Realm
import RealmSwift

/**
 Base class for creating any API object from JSON
 */
public class APISchema: Object, Mappable, Equatable, Hashable {

    /**
     Mapping for this object, must be overriden in subclass
     */
    public func mapping(map: Map) {
        // override
    }

    /**
     Initialization
     */
    required public init(_ map: Map) {
        super.init()
    }

    /**
     Initialization
     */
    required public init(realm: RLMRealm, schema: RLMObjectSchema) {
        super.init(realm: realm, schema: schema)
    }

    /**
     Initialization
     */
    required public init() {
        super.init()
    }
}

/**
 Conform to equatable
 */
public func ==(lhs: APISchema, rhs: APISchema) -> Bool {
    return lhs.isEqual(rhs)
}
```

And here is the initializer I needed to add to compile on 0.98.7:

```swift
/**
 Initialization
 */
required public init(value: AnyObject, schema: RLMSchema) {
    super.init(value: value, schema: schema)
}
```

**Comment by mrackwitz** [comment]
Okay, given that this object class is defined in Swift, this breaking *compile-time* change protects you from using this class in a way, which would have caused runtime errors before because required constructors wouldn't be correctly auto-inherited. I guess, you were not using this type in lists or queries? Because these would not have worked before and would have caused crashes.

**Comment by jpsim** [comment]
@AndrewBarba can you use convenience initializers instead? Should be simpler: https://realm.io/docs/swift/latest#adding-custom-initializers-to-object-subclasses

**Comment by AndrewBarba** [comment]
@mrackwitz I heavily use these objects in lists and queries, and have a pretty hefty set of unit tests that's been passing for a number of realm versions now.

@jpsim The `Mappable` protocol requires the `init(_ map: Map)` initializer, once I add that the Swift compiler forces me to make that `required` and then it forces me to add all of the required initializers after that.

**Comment by jpsim** [comment]
Ok, well nonetheless, this is all working as expected then. I see no reason to keep this issue open, unless you feel otherwise

**Comment by AndrewBarba** [comment]
No just wanted to give you guys a heads up. If you feel the need to investigate why something was working when it you don't think it should have been, just let me know, happy to share more code in a private thread.

**Comment by mrackwitz** [comment]
Whoops, just noticed that you had already `init(realm: RLMRealm, schema: RLMObjectSchema)` defined before, which wasn't enforced to be there by the compiler before that change.

Thanks a lot for providing insides here. But what you're facing here is at least expected and all this initializers are actually required at runtime, while the latter might not be required for the specific subset of the API you use. Sorry for the inconveniences through that. But by defining it, you're definitively on the safe side.
