### ISSUE TITLE
How can I fetch a realm tree with single leaves?

### ISSUE THREAD

**Issue by edias** [realm/realm-cocoa#3447]
I have the following scenario:

```
A
|--B - C - D
       |--E - F - G
              |--H - I
```

"A" object contains a collection of objects ("B", "C", "D"), "C" contains ("E", "F", "G") and "F" contains ("H", "I").

I would like to make a query on "I" and fetch only it's parents until the root of the tree, in this case until the "A" object.

The result would be something like this:

I - F - C - A

Also, please keep in mind that siblings nodes should not be included. For example object "F" should only contains object "I", object "C" should only contains object "F" and object "A" should only contains object "C".

Does anyone have any idea on how could I achieve that?

Any help would be welcome!

Thanks

**Comment by jpsim** [comment]
Here's a code sample that uses [`Object.linkingObjects(_:property:)`](https://realm.io/docs/swift/latest/api/Classes/Object.html#/s:FC10RealmSwift6Object14linkingObjectsuRxS0_rFTMx11forPropertySS_GSax_) to get the parents of an object from a query until it reaches the root of the object graph.

```swift
import RealmSwift

class FirstLevel: Object {
  dynamic var name = ""
  let secondLevels = List<SecondLevel>()
}

class SecondLevel: Object {
  dynamic var name = ""
  let thirdLevels = List<ThirdLevel>()
}

class ThirdLevel: Object {
  dynamic var name = ""
  let fourthLevels = List<FourthLevel>()
}

class FourthLevel: Object {
  dynamic var name = ""
}

let realm = try! Realm()
try! realm.write {
  let A = realm.create(FirstLevel.self, value: ["A", []])
  let (B, C, D) = (SecondLevel(value: ["B", []]), SecondLevel(value: ["C", []]), SecondLevel(value: ["D", []]))
  let (E, F, G) = (ThirdLevel(value: ["E", []]), ThirdLevel(value: ["F", []]), ThirdLevel(value: ["G", []]))
  let (H, I) = (FourthLevel(value: ["H"]), FourthLevel(value: ["I"]))

  // A
  // |--B - C - D
  //        |--E - F - G
  //               |--H - I
  A.secondLevels.appendContentsOf([B, C, D])
  C.thirdLevels.appendContentsOf([E, F, G])
  F.fourthLevels.appendContentsOf([H, I])
}
// I would like to make a query on "I" and fetch only its parents
// until the root of the tree, in this case until the "A" object.
let I = realm.objects(FourthLevel).filter("name == 'I'").first!
let parent1OfI = I.linkingObjects(ThirdLevel.self, forProperty: "fourthLevels").first!
print(parent1OfI.name) // => prints 'F'
let parent2OfI = parent1OfI.linkingObjects(SecondLevel.self, forProperty: "thirdLevels").first!
print(parent2OfI.name) // => prints 'C'
let parent3OfI = parent2OfI.linkingObjects(FirstLevel.self, forProperty: "secondLevels").first!
print(parent3OfI.name) // => prints 'A'
```

**Comment by jpsim** [comment]
Closing this, hoping my code sample was useful to @edias

**Comment by edias** [comment]
Thanks @jpsim
