### ISSUE TITLE
0.98.8 using by cocopods and swift2.1.1had this bugs!

### ISSUE THREAD

**Issue by AndroidIosWebEmbeddedFirmwareDver** [realm/realm-cocoa#3448]
'impl/cached_realm.hpp' file not found
 'index_set.hpp' file not found
 'impl/async_query.hpp' file not found
Expected namespace name
Use of undeclared identifier 'realm'

/Users/sin/Documents/iOS/workspace/normalTest/SwiftRealmDatabaseTest/Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:26:24: Expected namespace name
/Users/sin/Documents/iOS/workspace/normalTest/SwiftRealmDatabaseTest/Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:28:1: Use of undeclared identifier 'AsyncQuery'
/Users/sin/Documents/iOS/workspace/normalTest/SwiftRealmDatabaseTest/Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:28:24: Unknown type name 'Results'
/Users/sin/Documents/iOS/workspace/normalTest/SwiftRealmDatabaseTest/Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:38:1: Use of undeclared identifier 'AsyncQuery'
/Users/sin/Documents/iOS/workspace/normalTest/SwiftRealmDatabaseTest/Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:47:1: Unknown type name 'size_t'
/Users/sin/Documents/iOS/workspace/normalTest/SwiftRealmDatabaseTest/Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:47:8: Use of undeclared identifier 'AsyncQuery'
/Users/sin/Documents/iOS/workspace/normalTest/SwiftRealmDatabaseTest/Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:47:33: Use of undeclared identifier 'std'
/Users/sin/Documents/iOS/workspace/normalTest/SwiftRealmDatabaseTest/Pods/Realm/Realm/ObjectStore/impl/async_query.cpp:71:6: Use of undeclared identifier 'AsyncQuery'

**Comment by jpsim** [comment]
Hi @AndroidIosWebEmbeddedFirmwareDver. Xcode here is telling you that it can't find certain files it needs, and therefore can't compile Realm.

Based on the location in your GitHub profile, it seems you may be located in China. Please note that Realm's core binaries are often blocked from being downloaded from China. See #2713 for more information, and some workarounds, on that.

**Comment by batical** [comment]
Having the same issue using my tethering connection ( iPhone, Free Mobile provider from France)
Will try tonight from home

**Comment by batical** [comment]
after pod deintegrate, removing workspace file, pod install, even a pod update I have the same issue

        platform :ios, '8.0'
        use_frameworks!
        target "ThumbZic" do
        pod 'Alamofire'
        pod 'RealmSwift'
       end

got the same issue

so i update to the  lastest version of cocoa pod (CocoaPods 1.0.0.beta.8 )
and it is working fine

**Comment by mcobbin** [comment]
I recommend that Realm relocated to elsewhere so that downloading from China becomes a non-issue.  I also experienced the same issue.

**Comment by jpsim** [comment]
> I recommend that Realm relocated to elsewhere so that downloading from China becomes a non-issue. I also experienced the same issue.

We're working on an [ICP license](https://en.wikipedia.org/wiki/ICP_license) to operate servers in China, but it will take some time for us to do this as it's legally complicated.
