### ISSUE TITLE
Future Xamarin / C# compatibility

### ISSUE THREAD

**Issue by CrimsonKyle** [realm/realm-cocoa#3449]
Wondering if there are any plans to extend Realm to C# and Xamarin for use in cross platform application development? I know my colleagues and I would be thrilled to work with Realm in this environment.

**Comment by bdash** [comment]
Please [register your interest in Realm .NET](https://docs.google.com/forms/d/10DjgHS8KdDLgtBoA3VEB-gq1ncHVy_6uVQs3w7YqFlE/viewform?c=0&w=1) to learn when C# and Xamarin support is available.
