### ISSUE TITLE
Database blows up when doing an async call with the same data as before (db is 100 times larger)

### ISSUE THREAD

**Issue by CedricVanAsch** [realm/realm-cocoa#3451]
## Goals
Do an async call to parse the data to the database, so the main thread doesn't freeze. It should fill up the Realm database.

## Expected Results

Database is filled with JSON data in the background
File size is 2mb or less

## Actual Results

The database is filled, but the file is 50MB!!! If i let it run on the main thread, it's only 500KB large... so running it on an async thread makes it 100x larger for some reason. 

## Steps to Reproduce
Download alamofire, swiftyJSON and use a default realm database. Copy/Paste the below code on a JSON URL that has 1000 entries. (due to this being for a customer, i can't provide their data)

## Code Sample

 func loadDataForLocalCategory() {
        let URL = "SomeURL"
        Alamofire.request(.GET, URL).validate().responseJSON { response in
            switch response.result {
            case .Success:
                let priority = DISPATCH_QUEUE_PRIORITY_DEFAULT
                dispatch_async(dispatch_get_global_queue(priority, 0)) {

                if let value = response.result.value {
                    let realm = try! Realm()
                    let json = JSON(value)
                    for item in json["result"].arrayValue {
                        let localCategory = LocalDataCategory()
                        localCategory.id = item["id"].intValue
                        // print(item["name"].stringValue)
                        localCategory.name = item["name"].stringValue
                        try! realm.write {
                            realm.add(localCategory,update: true)
                        }
                    }
                  }
                }
            case .Failure(let error):
                print(error)
            }
        }
    }

## Version of Realm and Tooling

Realm version: Realm 0.98.8

Xcode version: 7.3

iOS/OSX version: 10.11.3 (OS X El capitan)

Dependency manager + version: ?

**Comment by CedricVanAsch** [comment]
Doing the realm.write on each iteration is what caused the issue. For some reason it's fine on the main thread, but when doing an async, you should place it outside the For loop.

**Comment by jpsim** [comment]
This is a basic behavior of Realm's design. Thread, and therefore transaction, isolation is gained by preserving all internal snapshot versions of the entire database between the oldest in-use transaction version and the most up-to-date one. So the larger that span, the larger the disk space needed to store all these intermediate versions. Holding/pinning one version on one thread while many new versions are created on another is one way to cause the file to explode in size. This is why having fewer write transactions is generally preferable to many small ones.
