### ISSUE TITLE
'Realm/RLMArray.h' file not found - Carthage 0.16.2

### ISSUE THREAD

**Issue by georgepoenaru** [realm/realm-cocoa#3456]
## Goals

Link the RealmSwift.framework including Realm.framework (v0.98.8) against my own Swift framework  with Carthage builded libraries.

I have tried to link also the prebuilded Realm frameworks.  

## Expected Results

Using RealmSwift without integration errors

## Actual Results

Error: 
/Users/george/mdk-sdk-ios/Carthage/Build/iOS/Realm.framework/Headers/Realm.h:21:9: 'Realm/RLMArray.h' file not found

Realm version: 0.98.8

Xcode version: 7.3 (7D175)

iOS/OSX version: 10.11.4

Dependency manager + version: Carthage 0.16.2
![screenshot 2016-04-19 19 17 01](https://cloud.githubusercontent.com/assets/4004883/14648641/8d9d7536-0663-11e6-8b17-7cf9274588e6.png)

**Comment by kishikawakatsumi** [comment]
@georgepoenaru Sorry for the late response.

We can't reproduce this, for 0.99.0 and 0.98.8. I suspect this is due to cache issue for the Cathage. Could you please try doing this and reporting back again? Also try clean project by Xcode and rebuild it?

```
rm -rf Carthage
carthage update
```

**Comment by jpsim** [comment]
Closing since we haven't heard back from @georgepoenaru in over a week and our Carthage tests continue to work...
