### ISSUE TITLE
Value in all objects realm are 0, but realm objects displayed in the console.

### ISSUE THREAD

**Issue by axenovV** [realm/realm-cocoa#3460]
Realm objects are displayed in the console , but yet when I use them in the table , the values ​​of all values ​​are 0 sites.

So I take the object from the Realm Results:
![screen shot 2016-04-21 at 14 57 04](https://cloud.githubusercontent.com/assets/9257530/14708132/dd736db4-07d9-11e6-940a-79249c13ea3b.png)

This is what happens in RAM:
![screen shot 2016-04-21 at 14 58 31](https://cloud.githubusercontent.com/assets/9257530/14708156/f84e2e4e-07d9-11e6-9865-4870982acdbf.png)

But object  displayed in the console: 
![screen shot 2016-04-21 at 14 59 25](https://cloud.githubusercontent.com/assets/9257530/14708181/2b96e4e4-07da-11e6-8e8b-8288e6cf0ba6.png)
But i console log property object's, if you bring a fully object to the console , then all values ​​are correct.
![screen shot 2016-04-21 at 15 17 02](https://cloud.githubusercontent.com/assets/9257530/14708520/9a4badc8-07dc-11e6-8b9c-8dd60ba1f18a.png)

**Comment by bdash** [comment]
This is expected. For persisted objects state is not stored in the object's instance variables, but is fetched from the underlying Realm file when getters are called.
