### ISSUE TITLE
"impl/async_query.hpp" file not found in 0.98.4

### ISSUE THREAD

**Issue by haojian2016** [realm/realm-cocoa#3465]
![Uploading E2868CF6-FE59-48D9-98F4-12FCD6FA331F.png…]()

**Comment by bdash** [comment]
A few people (#3293, #3246, etc.) have reported seeing an error of this nature which was addressed by doing the following from within your project directory:

```sh
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods/
pod install
```

Can you please give that a shot?

**Comment by haojian2016** [comment]
![e2868cf6-fe59-48d9-98f4-12fcd6fa331f](https://cloud.githubusercontent.com/assets/16795422/14728607/df942cfc-0868-11e6-9f81-f876d248560b.png)

**Comment by jpsim** [comment]
@haojian2016 please post the output from running the following commands:

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
```

**Comment by jpsim** [comment]
closing this as we haven't heard back from @haojian2016 in a few weeks
