### ISSUE TITLE
Deprecate all Swift versions other than 2.2.x

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3469]
We should soon deprecate Swift versions older than 2.2.x, which will allow us to avoid an `associatedtype` warning, make use of Swift language version compile-time checks and possibly simplify our build system depending on whether or not we feel comfortable removing the symlink infrastructure temporarily.

**Comment by impopappfactory** [comment]
I'm not able to switch to swift 2.2 in our project targeting ios7, because of swift runtime crash.
Do you plan to deprecate swift 2.2 in realm 1.0 release?

**Comment by jpsim** [comment]
@impopappfactory no we don't plan on deprecating Swift 2.2 at this time. If Swift 2.2 has a regression from previous versions of Swift, you should report that to Apple. They've been quite good at prioritizing regression fixes for path releases.
