### ISSUE TITLE
@"%name IN $NAME_LIST" and @"'name' IN $NAME_LIST" difference

### ISSUE THREAD

**Issue by karepbq** [realm/realm-cocoa#3471]
I use NSPredicate check content,but get result difference.

@"'name' IN $NAME_LIST" return Bool , talk about it,return is Bool value ,is true?

**Comment by jpsim** [comment]
`@"%name IN $NAME_LIST"` is querying for the string literal `%name` in the $NAME_LIST named variable while `@"'name' IN $NAME_LIST"` is querying for the string literal `name`.
