### ISSUE TITLE
Please stop using the term "section" in database design

### ISSUE THREAD

**Issue by xiaodao** [realm/realm-cocoa#3472]
I saw this one in 0.99.0 API:

The change information is available in two formats: a simple array of row indices in the collection for each type of change, and an array of index paths in a requested section suitable for passing directly to UITableView’s batch update methods. 

But do you think the DB should not know how will the data get presented in UI? 

Why did you make such a "UI Driven Design"?

**Comment by jpsim** [comment]
Thanks for voicing your concerns @xiaodao. Feedback from our users is always appreciated.

In this case, if a user has moderately simple needs, they can use our index path APIs as-is. This was a big motivator for our current design. Even then, if a user has more complex UITableView needs, or want to use change notifications in some other context, they can easily use the integer APIs or even just `map` over the index path results to apply an offset or other transformation to the data.

If you care deeply about this, could you propose a preferable alternate API that retains both the ease of use and flexibility of the current one?

Thanks!

**Comment by xiaodao** [comment]
I don't think `if a user has more complex UITableView needs` is a valid argument.

When we design the database API, one should not care about the presentation of the data. Getting the low-level framework coupled with high-level module is way too weird.

Can you explain what is the `section` from the database's point of view

**Comment by jpsim** [comment]
> When we design the database API, one should not care about the presentation of the data. Getting the low-level framework coupled with high-level module is way too weird.
> 
> Can you explain what is the section from the database's point of view

If you don't care about this integration point in our API with a commonly used UI component, why not just ignore it and use the more primitive one instead? The `NSIndexPath` variant is strictly present for convenience with the common use case of Realm users using notifications: for UI updates. If you're not interested in that, just don't use this convenience API.

You have yet to offer what you would consider to be an improvement to the API. It's hard to understand what your goal is here without seeing something more concrete.

**Comment by rudedogg** [comment]
> The change information is available in two formats: a simple array of row indices in the collection for each type of change, and an array of index paths in a requested section suitable for passing directly to UITableView’s batch update methods.

Where is that in the documentation? I don't see any NSIndexPaths being used in the realm source - except in the example (and a code comment), so there's really no coupling with the display. They just provide an array of indexes, which lets you find the objects that have changed inside the notification block. That happens to allow you to create a NSIndexPath if you're not using sections in a tableview/collectionview, so they highlight how easy it can be.

**Comment by xiaodao** [comment]
`You have yet to offer what you would consider to be an improvement to the API`

-> If the peaches begin to rot, I can tell from the putrid smell. I don't need to be a good gardener.

My goal here is to pointing out the API is rotting.

When you add the presentation consideration into your API, it looks like the users will benefit from that, but by adding `section` into the codebase, you definitely broke the principle of `separation of concerns`.

**Comment by jpsim** [comment]
Well you're certainly entitled to that opinion and you can consider your concerns heard, but I don't think there's any further value to gain from continuing this thread.
