### ISSUE TITLE
Realm accessed from incorrect thread on Apple Watch

### ISSUE THREAD

**Issue by kacper1703** [realm/realm-cocoa#3475]
I wish to use a Realm repository on Apple Watch, seperate from the iPhone's. I want to overwrite all data that is stored in Realm once the Watch recieves `applicationContext` from the iPhone with updated data. 

I get an error 
> 'Realm accessed from incorrect thread.'

Call stack:
```
	0   CoreFoundation                      0x00a1cd74 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x012cedf4 objc_exception_throw + 50
	2   Realm                               0x002de312 -[RLMRealm beginWriteTransaction] + 146
	3   Realm                               0x002de66a -[RLMRealm transactionWithBlock:error:] + 90
	4   RealmSwift                          0x00781719 _TFC10RealmSwift5Realm5writefzFT_T_T_ + 201
	5   MyApp Watch App Extension        0x000af77f _TFC28MyApp_Watch_App_Extension12WatchManager20overwriteDataInRealmfGVs10DictionarySSPs9AnyObject__T_ + 287
...
```

Code:
``` swift
let realm = try? Realm()

func session(session: WCSession, didReceiveApplicationContext applicationContext: [String : AnyObject]) {
        if !applicationContext.isEmpty {
            overwriteDataInRealm(applicationContext)
        }
    }

func overwriteDataInRealm(applicationContext: [String : AnyObject]) {
        var storedFlashcards = [WatchFlashcard]()
        
        if let realm = realm {
            do {
                try realm.write() {
                    if let flashcardsQ = applicationContext["flashcardsQuestions"] as? [String],
                        let flashcardsA = applicationContext["flashcardsAnswers"] as? [String],
                        let flashcardIDs = applicationContext["flashcardsIDs"] as? [String],
                        let flashcardsTips = applicationContext["flashcardsTips"] as? [String] {
                        for i in 0..<flashcardsQ.count {
                            storedFlashcards.append(WatchFlashcard(serverID: flashcardIDs[i], question: flashcardsQ[i], answer: flashcardsA[i], tip: flashcardsTips[i]))
                        }
                    realm.deleteAll()
                    realm.add(storedFlashcards)
                    }
                }
            } catch let e {
                debugPrint(e)
            }
        }
    }

```
What I noticed when using breakpoints is that the write block doesn't execute any of the code inside.

Realm version: 0.98.6
Xcode version: 7.3 (7D175)
Dependency manager + version: CocoaPods 1.0.0.beta.6

**Comment by mrackwitz** [comment]
Hey Kacper, you are getting this error because the methods of the [`WCSessionDelegate`](https://developer.apple.com/library/watchos/documentation/WatchConnectivity/Reference/WCSessionDelegate_protocol/) are all called on a background thread like seen in the docs:

>The methods of this protocol are called on a background thread of your app, so any code you write should be written with that fact in mind. 

You initialized your Realm instance on the same thread the class implementing this protocol is initialized. This will be very likely the main thread.

All Realm accessors are bound to their thread, they were initialized on. I'd recommend to initialize your Realm instance directly in `overwriteDataInRealm(_:)` with `let realm = try! Realm()`.
