### ISSUE TITLE
Migrating a custom Realm

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#3481]
Hi!

Coming from here:
https://realm.io/docs/objc/latest/#migrations

It was well explained how to migrate the default Realm.
But what about custom realm?
For instance I have `RLMRealm *newRealm = [RLMRealm realmWithPath:path];`.
How does migration in this case work?
```
newRealm.configuration = configuration
```

Is it enough? Anyway, instead of guessing, I would highly appreciate a documentation example or any explanation on this topic, or a place where it is already explained but I was dumb enough not to find it.

Thanks in advance!

**Comment by mrackwitz** [comment]
No, you can't set the configuration. That would be also to late.

You will need to setup the custom path in your configuration and then you can use [`+[RLMRealm realmWithConfiguration: error:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc%28cs%29RLMRealm%28cm%29realmWithConfiguration:error:).

```objc
RLMRealmConfiguration *newRealmConfig = RLMRealmConfiguration.defaultConfiguration;
newRealmConfig.path = path
NSError *error;
[RLMRealm realmWithConfiguration:newRealmConfig error:&error];
```

**Comment by OlegAnghelov** [comment]
I am a little confused.
Even considering the new API, it's `+[RLMRealm realmWithURL:]`. What is `[RLMRealm realmWithConfiguration:newRealmConfig error:&error];` used for? 
I see that `[RLMRealm realmWithConfiguration:config error:&err]` returns an `instancetype`... 
So this method does two things:
1) assigns the new configuration to the Realm stored at the path which was put in `newRealmConfig.path`
2) Returns the Realm that was already upgraded with the configuration passed as parameter.

So if I want to make a migration for a custom Realm, I should put the path to the configuration object, then add the migration block to migration object, and by passing it to `[RLMRealm realmWithConfiguration:newRealmConfig error:&error];` I will automatically make the custom Realm apply the migrations, so next time I am calling `[RLMRealm realmWithUrl:url]` I will get already a migrated version?

**Comment by OlegAnghelov** [comment]
*i've made dozens of edits, sorry for that. 
Please refresh the page if you opened when you just got the notification about my previous answer.
I will delete this comment later.

**Comment by mrackwitz** [comment]
Yes, if you're using the latest version, you will need to use file URLs instead of file paths as strings.

>So there are two ways of getting a needed realm - via `realmWithURL` and  `realmWithConfiguration:`?

Yes. `+[RLMRealm realmWithURL:]` is based on the default configuration, but allows to use a different location.

>so next time I am calling `[RLMRealm realmWithUrl:url]` I will get already a migrated version?

No, that doesn't apply. You will need to make sure that the `schemaVersion` is set high enough.

**Comment by OlegAnghelov** [comment]
Thanks for quick reply!
Could you please check if you saw the latest version of my post? :)

And what do you think about different "applying" approaches in custom and default realm cases?

**Comment by mrackwitz** [comment]
>Could you please check if you saw the latest version of my post? :)

Yes, saw it.

>And what do you think about different "applying" approaches in custom and default realm cases?

For the default Realm, you can rely on having setup a customized defaultConfiguration as shared instance via `RLMRealmConfiguration`. For all other custom configurations, the best way would be to share your configuration in a similar way and always rely on that configuration instance to access your Realm.

Does that help with your question?

**Comment by OlegAnghelov** [comment]
Just to be sure that I understood you correctly:
If I need to do a schema migration on a default realm, I use `RLMRealmConfiguration ` and apply it via `[RLMRealmConfiguration setDefaultConfiguration:configuration];`.
If I need to do a schema migration on a custom realm, I use `RLMRealmConfiguration` and apply it via `[RLMRealm realmWithConfiguration:newRealmConfig error:&error];`

Did I got it correctly?

**Comment by mrackwitz** [comment]
`[RLMRealmConfiguration setDefaultConfiguration:configuration];` will set the default configuration, but not actually execute the migration.

Migrations happen implicitly on first access with a given configuration.

**Comment by OlegAnghelov** [comment]
I actually appreciate your detailed answers, because they are much better than just a basic "yes/no", since I also get the understanding how it works behind the scenes, which is cool.

Ok, so your answer got it really straight for the default realm case. When you apply a configuration to a realm, next time you access the realm, it checks if any migrations are needed, and does so if any. This is also written in the documentation page.

But you mentioned this:
> Migrations happen implicitly on first access with a given configuration.

So for default realm, these two lines
```
[RLMRealmConfiguration setDefaultConfiguration:configuration];//configuration is set up for default path
[RLMRealm defaultRealm];
```
are equivalent for this one line for custom realm:
```
[RLMRealm realmWithConfiguration:newRealmConfig error:&error];//configuration set up with custom path
```

Since `[RLMRealm realmWithConfiguration:newRealmConfig error:&error];` does both: gives a configuration to a realm and accesses it.
Right?

**Comment by mrackwitz** [comment]
Yes, you got it. :+1:
