### ISSUE TITLE
the RACTableView example of ios-xcode7-objc has a build error

### ISSUE THREAD

**Issue by calvingit** [realm/realm-cocoa#3482]
## Goals

What do you want to achieve?
> Try to run RACTableView example

## Expected Results

What did you expected to happen?
> no errors

## Actual Results

What did happened instead?  
>A building error happened, said that Xcode can't find the ReactiveCocoa library.

## Steps to Reproduce

What are steps we can follow to reproduce this issue?
>Just 'pod install', then open the 'RealmExamples.xcworkspace', run.

## Code Sample
NO.

# Version of Realm and Tooling
Realm version: 0.98.8
Xcode version: 7.3

iOS/OSX version: 10.11

Dependency manager + version: Cocoapods 0.39

## Solution:
The error is the 'Per-configuration Build Products Path' in 'Build Settings', the path is '$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)-static'. If remove the suffix '-static' , it will be OK.

**Comment by mrackwitz** [comment]
I think, you're hitting here an error in CocoaPods, which was fixed in the 1.0 prereleases. Can you try out the latest prerelease by `gem install cocoapods --prerelease`?

**Comment by bdash** [comment]
This may be an error in the Xcode project configuration for the RACTableView target. It appears not to be tested as part of our automated verification of our examples so I can see an error slipping in.

**Comment by jpsim** [comment]
I can reproduce this... probably just a configuration error in our Xcode project with how CocoaPods dependencies are linked.
