### ISSUE TITLE
Autorefresh not working

### ISSUE THREAD

**Issue by heyzooi** [realm/realm-cocoa#3492]
## Goals

Get all records for a class

## Expected Results

Get the results as shown in Realm Browser

## Actual Results

No records are returned until you manually call `realm.refresh()`

## Steps to Reproduce

1. Create a Realm instance with `autorefresh` enabled
2. Add a record
3. Creator another Realm instance with the same configuration
4. Perform a query using this 2nd Realm instance
5. You should see the new record, but the actual result is an empty result.

## Code Sample

I have to create a sample project that reproduces the problem

## Version of Realm and Tooling

Realm version: 0.99.1

Xcode version: 7.3

iOS/OSX version: 9.3.1

Dependency manager + version: Carthage 0.16.2

**Comment by jpsim** [comment]
As you can imagine, we can't reproduce this. Here's a playground:

```swift
import Foundation
import RealmSwift

class A: Object {
    dynamic var prop = 0
}

// 1. Create a Realm instance with autorefresh enabled
let configuration = Realm.Configuration(inMemoryIdentifier: "TemporaryRealm")
let realm = try! Realm(configuration: configuration)
realm.autorefresh // => true

// 2. Add a record
try! realm.write {
    realm.add(A())
}

// 3. Creator another Realm instance with the same configuration
let realm2 = try! Realm(configuration: configuration)

// 4. Perform a query using this 2nd Realm instance
realm2.objects(A).filter("prop = 0")

// 5. You should see the new record, but the actual result is an empty result.
// Results<A> (
//     [0] A {
//         prop = 0;
//     }
// )
```

**Comment by heyzooi** [comment]
You have to run a few times to see it happening, but here's a playground

```
import Foundation
import RealmSwift
import XCPlayground

class A: Object {
    dynamic var prop = 0
}

let memoryIdentifier = "TemporaryRealm"
var finished = false

let configuration = Realm.Configuration(inMemoryIdentifier: memoryIdentifier)
let realm = try! Realm(configuration: configuration)
realm.autorefresh // => true

dispatch_async(dispatch_get_main_queue()) {
    
    try! realm.write {
        realm.add(A())
    }
    finished = true
}

dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0)) {
    while finished {
        //waiting for first realm
    }
    let configuration2 = Realm.Configuration(inMemoryIdentifier: memoryIdentifier)
    let realm2 = try! Realm(configuration: configuration2)
    realm2.autorefresh // => true
    
    //uncomment this call to actually see .count returning 1
    //realm2.refresh()
    
    realm2.objects(A).count // => sometimes returns 0
}

XCPSetExecutionShouldContinueIndefinitely()
```
![screen shot 2016-04-28 at 10 12 50 am](https://cloud.githubusercontent.com/assets/600503/14894737/f9a0471e-0d29-11e6-9a5e-bb316f0d33a8.png)

**Comment by bdash** [comment]
Automatic refresh is only possible on threads that have running runloops. Dispatch queues do not have running runloops and so Realms used on them must be refreshed manually.

**Comment by heyzooi** [comment]
make sense! it's not a big deal, we can perform a manual refresh in this case.
thanks for the clarification!
