### ISSUE TITLE
.hpp文件找不到

### ISSUE THREAD

**Issue by haojian2016** [realm/realm-cocoa#3493]
![c453e354-cc0f-4512-a650-4a665d83925b](https://cloud.githubusercontent.com/assets/16795422/14873617/189decba-0d2b-11e6-88e3-c08865a39b6f.png)

**Comment by bdash** [comment]
Which version of CocoaPods are you using?

**Comment by haojian2016** [comment]
Xcode7.3，CocoaPods0.39.0

**Comment by haojian2016** [comment]
problem solved, Is indeed version of the problem
