### ISSUE TITLE
Fetching data before migrations

### ISSUE THREAD

**Issue by dumoko** [realm/realm-cocoa#3498]
## Goals
`Migration is required for object type 'X' due to the following errors: - Property 'Y' has been added to latest object model.`
We have a mysterious migration crash that was happening in the last versions. We are unable to reproduce it directly on our environments. 
The fact that we used several Realms and already have several schema migrations actually give plenty space to weird things to happen.
I do expect that this issue is not a Realm bug, but just our poor migration management. 
We have 2 realms(deafult and custom), and it seems that one of them didn't get a migration at the right time, so it's crashing(stack trace proves it), right at `[RLMRealm realmWithPath:]`, which I say is smth expected, since it didn't get the right migration.
We have some assumption on why the crash is happening, but it would be very risky to deploy a migration fix in a blind way, our user base is huge and any error would be enormous. 
So with next version we are trying to gather as much data as we can about the DB, and Crashlytics provide some cool APIs for it.

But since the crash happens when we try to access the custom Realm (but the models differ from the schema in that Realm), is there a way to do some very high-level logging? Like try to ask at least the count of rows, or anything? Or, more important, get it's schema version? Or is it possible to get any data about given realm without accessing it in a way it will return the migration crash?

## Version of Realm and Tooling
Realm version: 0.98.1
Xcode version: 7.3
iOS/OSX version: iOS 7-9
Dependency manager + version: cocoapods 0.39.0

**Comment by jpsim** [comment]
> The fact that we used several Realms and already have several schema migrations actually give plenty space to weird things to happen.

Migrations should only happen once per Realm per schema version, no matter the number of processes or threads accessing that Realm. Do you mean "several schema migrations" over the course of multiple schema changes?

> I do expect that this issue is not a Realm bug, but just our poor migration management.

Yes, that seems to be the likely explanation.

> is there a way to do some very high-level logging?

There's quite a bit you can do if you're willing to use private Realm APIs that aren't officially supported (read: our ability to give you advice and fix things for you will be limited).

You could compare your default schema (`[RLMRealmConfiguration customSchema]`, [a private property](https://github.com/realm/realm-cocoa/blob/v0.100.0/Realm/RLMRealmConfiguration_Private.h#L28)) with the schema from the Realm file (some other private instance variables and methods: `[RLMSchema dynamicSchemaFromObjectStoreSchema:*realm->_realm->config().schema`).

> Like try to ask at least the count of rows, or anything?

Again, with private APIs, sure, but I don't think getting the number of objects per model will help you here.

> Or, more important, get it's schema version? Or is it possible to get any data about given realm without accessing it in a way it will return the migration crash?

There's actually an official public API for getting the schema version for a Realm file:
[`+[RLMRealm schemaVersionAtURL:encryptionKey:error:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(cm)schemaVersionAtURL:encryptionKey:error:)

---

I hope this helps.

**Comment by OlegAnghelov** [comment]
Thanks for a cool answer!
If the model was changed, but no migration is added, a realm will crash on first access.
But does this method `+[RLMRealm schemaVersionAtURL:encryptionKey:error:]` actually opens the Realm? So will it crash if I will ask the realm about it's version AND have changed models with no migrations?

**Comment by jpsim** [comment]
> But does this method `+[RLMRealm schemaVersionAtURL:encryptionKey:error:]` actually opens the Realm?

Yes, but in a way that won't trigger a migration check, so for all intents and purposes you shouldn't notice any side effects from this.

**Comment by mrackwitz** [comment]
@dumoko: As you never came back to this issue with further questions, I hope you have all you need to resolve your migration issues. If you have remaining questions, you're welcome anytime, while we prefer in general StackOverflow for help related questions. We actively monitor questions coming in, which are tagged as `realm`. :wink:
