### ISSUE TITLE
RealmCollectionChange.Initial notification not always received

### ISSUE THREAD

**Issue by intrigua** [realm/realm-cocoa#3501]
Newly introduced RealmCollection.addNotificationBlock method not always works as expected. I need to track down only when items are inserted or deleted from the collection. But sometimes the first passed value is `.Update` while `.Initial` is not passed at all. So I forced to use my own `_initialTags` flag. Here's the code:

```
var _initialTags = false
tokens.append(hashtags.addNotificationBlock { (changes: RealmCollectionChange<Results<Hashtag>>) in
    switch changes {
    case .Update(_, let deletions, let insertions, _):
        if deletions.isEmpty && insertions.isEmpty && _initialTags { break }
            fallthrough
    case .Initial:
        self.storedHashtags.removeAll()
        self.storedHashtags.appendContentsOf(self.hashtags)
        if !self.searchMode { self.updateOutline() }
        _initialTags = true
        break
    case .Error(let error):
        fatalError("\(error)")
    }
})
```

```
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

/Applications/Xcode.app/Contents/Developer
Xcode 7.3
Build version 7D175

~/.gem/ruby/2.0.0/bin/pod
0.39.0
Realm (0.99.1)
RealmSwift (0.99.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)


(not in use here)

/usr/bin/git
git version 2.6.4 (Apple Git-63)
```

**Comment by jpsim** [comment]
Sorry @intrigua, I don't think your code sample is sufficient to reproduce the behavior you're seeing... could you please add the relevant code that can demonstrate the `.Initial` notification not being sent?

Here's a small complete program sample you can use as a template:

```swift
import UIKit
import RealmSwift

class Hashtag: Object {
    dynamic var name = ""
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    var token: NotificationToken? = nil

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        let realm = try! Realm()
        let hashtags = realm.objects(Hashtag)
        token = hashtags.addNotificationBlock { (changes: RealmCollectionChange) in
            switch changes {
            case .Initial:
                print("this is the only state this block should be called with")
                break
            case .Update, .Error:
                fatalError("should never be called")
            }
        }
        return true
    }
}
```

**Comment by mrackwitz** [comment]
My guess here would be that the `.Initial` notification was coalesced with the first `.Update`.

>Notifications are delivered via the standard run loop, and so can't be
 delivered while the run loop is blocked by other activity. When
 notifications can't be delivered instantly, multiple notifications may be
 coalesced into a single notification. This can include the notification
 with the initial results. For example, the following code performs a write
 transaction immediately after adding the notification block, so there is no
 opportunity for the initial notification to be delivered first. As a
 result, the initial notification will reflect the state of the Realm after
 the write transaction.

Could this be the case here?

**Comment by intrigua** [comment]
May be, but how can I know whether this `.Update` is actually `.Initial` as well?

**Comment by jpsim** [comment]
@mrackwitz you're reading that documentation incorrectly, if you read closely in the [API docs](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results20addNotificationBlockFFGOS_21RealmCollectionChangeGS0_x__T_CSo20RLMNotificationToken), it includes this code sample:

```swift
let dogs = realm.objects(Dog)
print("dogs.count: \(dogs?.count)") // => 0
let token = dogs.addNotificationBlock { (changes: RealmCollectionChange) in
    switch changes {
        case .Initial(let dogs):
            // Will print "dogs.count: 1"
            print("dogs.count: \(dogs.count)")
            break
        case .Update:
            // Will not be hit in this example
            break
        case .Error:
            break
    }
}
try! realm.write {
    let dog = Dog()
    dog.name = "Rex"
    person.dogs.append(dog)
}
// end of run loop execution context
```

which demonstrates that it's the *initial* state that actually contains updated information, not that `.Initial` is never called, and the first notification mode is `.Update`.

@intrigua your follow up comment isn't relevant based on this information. If you could please provide a sample project that reproduces the issue, I'll be happy to take a closer look at it.

**Comment by jpsim** [comment]
@intrigua just following up on my request for a sample project that reproduces the issue you're seeing... thanks!

**Comment by jpsim** [comment]
I'm closing this until this behavior can be confirmed by user, or until someone can make a reproduction case.

**Comment by iandundas** [comment]
Okay, I think I have an example project. It's a bit strange, but does (I hope) reproduce the issue of the addNotificationBlock callback receiving an .Update before any .Initial event.

(Realm v1.0.0.)

The project is zipped and should run as-is, no need for `carthage update`. 

To reproduce: 
- find RealmNotificationTests.swift 
- drop a breakpoint at `switch changeSet`, line 24
- run the `testWriteAndWait()` test

You should see that in the `addNotificationBlock` block, we receive an `update` first, and no `initial` event.

[download project](https://www.dropbox.com/s/7ax04nwv2nsd8e9/ExampleOfUpdateCalledFirst.zip?dl=00)

**Comment by iandundas** [comment]
_I just edited the above comment to provide a better example project_
