### ISSUE TITLE
Realm, some errors when use pod update

### ISSUE THREAD

**Issue by arden** [realm/realm-cocoa#3504]
Installing Realm 0.100.0 (was 0.99.0)
^@^@^@^@^@[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.98.4
Downloading core failed:
curl: (56) SSLRead() return error -9806

**Comment by jpsim** [comment]
See #2713.
