### ISSUE TITLE
Unable to install from cocoapods

### ISSUE THREAD

**Issue by TiagoVeloso** [realm/realm-cocoa#3508]
## Goals

I want to install realm 0.100.0 via cocoapods

## Expected Results

`pod install` to run without an issue

## Actual Results

It crashed cocoapods here is the error

```
[!] /usr/local/bin/bash -c
set -e
sh build.sh cocoapods-setup

: command not found
: command not found
: invalid option namet: pipefail
: invalid option4: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
```
Note, I am in Portugal. I don't think it's related to some other issues i've seen around.

## Steps to Reproduce

Run `pod install`, thats what doing it for me.

## Version of Realm and Tooling

Realm version: 0.100.0

Xcode version: 7.3

OSX: 10.11.4

Dependency manager + version: CocoaPods 0.39.0

**Comment by bdash** [comment]
I believe those errors are a symptom of incorrect line endings in the build scripts in the Realm repository. We've seen reports of this in the past when a user had Git configured with the `core.autocrlf` setting enabled (#2662). We can confirm whether line endings are the cause by checking the output of:

```
xxd scripts/swift-version.sh | head
```

**Comment by TiagoVeloso** [comment]
I have disabled the `core.autocrlf` setting (it was set to `true`) and `pod install` worked just fine.

**Comment by bdash** [comment]
Great news!
