### ISSUE TITLE
WriteCopytoURL usage is leading to more crashes on next launch

### ISSUE THREAD

**Issue by slreddy1137** [realm/realm-cocoa#3513]
Hi,

I have been trying to use the writeCopyToURL when the app is going to background, this is reducing the Realm file size, but when i re-launch the app there are places where i m creating a Realm instance inside a dispatch queue those are not getting created and ignoring the complete code, and its crashing due to some old references, i have been trying to figure out to fix this but unable to.

my app has become more unstable and don't know when it crashes, it might to trying to refer to some of the old realm references.

code:

    if (![RLMRealm defaultRealm].inWriteTransaction) {
//        [[RLMRealm defaultRealm] invalidate];
        
        __block BOOL copySuccess = NO;
        NSURL *realmURL = [[RLMRealmConfiguration defaultConfiguration] fileURL];
        NSString *copyPath = [realmURL.path stringByAppendingString:@".copy"];
        @autoreleasepool
        {
            [[NSFileManager defaultManager] removeItemAtPath:copyPath error:nil];
            copySuccess = [[RLMRealm defaultRealm] writeCopyToURL:[NSURL URLWithString:copyPath] encryptionKey:nil error:nil];
        }
        
        if (copySuccess && [[NSFileManager defaultManager] removeItemAtPath:realmURL.path error:nil])
        {
            NSError *err;
            [[NSFileManager defaultManager] copyItemAtPath:copyPath toPath:realmURL.path error:&err];
        }
        
    }

can someone guide me with best practise please.

Realm version: 100.0

Xcode version: 7.2

iOS/OSX version: 9.0.2

**Comment by jpsim** [comment]
Hi @slreddy1137, as a best practice, I'd recommend not replacing the Realm file as you're accessing it. This is likely to cause file corruption and depending on timing, a variety of crashes.

To use a compacted copy of the Realm file, I'd recommend performing the copy as the very first step in your application, before any other code has had the chance to access the Realm file.

Or alternatively, don't replace the Realm file you're accessing, just start using Realms at the new location.

**Comment by slreddy1137** [comment]
Hi @jpsim , i have not created any Realm files from the project, i m directly using the "Default Realm" instances which internally creating the Realm file.

1. To perform copy as the very first step : shall i do it in "didFinishLoading" everytime ?

2. Alternate approach : as the default Realm is in Documents folder, can u please suggest me how to start using Realms at new location.

**Comment by jpsim** [comment]
> shall i do it in "didFinishLoading" everytime ?

That depends, do you have any code accessing the Realm that runs before this? Like default property values in your view controllers loaded by storyboards?

> Alternate approach : as the default Realm is in Documents folder, can u please suggest me how to start using Realms at new location.

There's a handy Realm initializer that takes in a location: https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(cm)realmWithURL:

Or you can set a value on the configuration: https://realm.io/docs/objc/latest/api/Classes/RLMRealmConfiguration.html#/c:objc(cs)RLMRealmConfiguration(py)fileURL

**Comment by slreddy1137** [comment]
i m loading the data in viewDidLoad for few controllers, which is increasing the realm file size, in between of the app running i cannot make a copy right ?

Alternate approach:
do  i need to create realm file in a new location, if so how about the classes which are referring to old realm and its data.

sorry, to ask you more.

**Comment by jpsim** [comment]
> i m loading the data in viewDidLoad for few controllers, which is increasing the realm file size, in between of the app running i cannot make a copy right ?

I must be misunderstanding you here, you obviously can't run your application code in between runs of your application...

> do i need to create realm file in a new location, if so how about the classes which are referring to old realm and its data.

If you create a new Realm file, you'll probably want to update any previous Realm-related objects to point to the updated version. This is very similar to the initial problem of replacing the Realm file while pre-existing objects were still accessing the previous file.

> sorry, to ask you more.

No need to be sorry to ask for help, that's what we're here for! 😄

**Comment by slreddy1137** [comment]
since the both approaches doesn't suit my scenario, how can i get the realm file size reduced, its increasing dramatically around 180MB and more

**Comment by jpsim** [comment]
How about compacting the Realm file before any of your application code has a chance to access it? Performing the compaction prior to your `UIApplication` being created could work, as long as the compaction isn't so time consuming as to jetsam your app:

```objc
// main.m
#import <UIKit/UIKit.h>
#import "AppDelegate.h"
#import <Realm/Realm.h>

void CompactRealmFile() {
    __block BOOL copySuccess = NO;
    NSURL *originalURL = [[RLMRealmConfiguration defaultConfiguration] fileURL];
    NSURL *copyURL = [originalURL URLByAppendingPathExtension:@"copy"];
    NSFileManager *fileManager = [NSFileManager defaultManager];
    if (![fileManager fileExistsAtPath:copyURL.path] ||
        ([fileManager removeItemAtURL:copyURL error:nil])) @autoreleasepool {
        copySuccess = [[RLMRealm defaultRealm] writeCopyToURL:copyURL encryptionKey:nil error:nil];
    }

    if (copySuccess && [[NSFileManager defaultManager] removeItemAtURL:originalURL error:nil]) {
        NSError *err;
        if (![[NSFileManager defaultManager] copyItemAtURL:copyURL toURL:originalURL error:&err]) {
            NSLog(@"error copying Realm file: %@", err.localizedDescription);
        } else {
            NSLog(@"compacted Realm file");
        }
    }
}

int main(int argc, char * argv[]) {
    @autoreleasepool {
        @autoreleasepool { CompactRealmFile(); }
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
    }
}
```

**Comment by slreddy1137** [comment]
I ll try this for sure, but my Realm file initially on the first time app launch it will not be available and this realm objects are loaded heavily by making service calls and fetch the data.

**Comment by jpsim** [comment]
@slreddy1137 did you get this to work? any reason to keep this ticket open?

**Comment by slreddy1137** [comment]
Hi,

Even after trying this approach I m seeing more unknown crashes, figuring out ways to get it fixed.

**Comment by jpsim** [comment]
> Even after trying this approach I m seeing more unknown crashes, figuring out ways to get it fixed.

If you show us how we can trigger crashes like these, we're happy to lend our time to look into them and help 😄 😄 😄

**Comment by slreddy1137** [comment]
Sure, I ll get more details soon.

**Comment by slreddy1137** [comment]
@jpsim , we are still testing after making this changes in main.m for optimising the realm file, please give us 2 more days to confirm on the fix.

**Comment by jpsim** [comment]
Looking forward to your results @slreddy1137!

**Comment by slreddy1137** [comment]
Hi Simard,

I see the build is stable now, extensive testing is going on, I can confirm that it's a solution for me, the ticket can closed.

**Comment by jpsim** [comment]
I'm thrilled to hear this @slreddy1137! Thanks for the update.

**Comment by slreddy1137** [comment]
Thanks a lot for your support .
