### ISSUE TITLE
Crash when opening an encrypted Realm

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#3519]
## Goals

Open an encrypted Realm file.

## Expected Results

Realm file can be opened.

## Actual Results

Crash when opening the Realm file.

## Steps to Reproduce

I have sent you the offending Realm file including the encryption key privately.

## Version of Realm and Tooling

Realm version:  0.97.1, 0.100.0

Xcode version: 7.3

iOS/OSX version: 9.3.1

Dependency manager + version: Cocoapods 0.39.0

**Comment by jpsim** [comment]
Let's continue this conversation privately since it deals with privately encrypted material.
