### ISSUE TITLE
realm: Crash when realm.write called from handleEventsForBackgroundURLSession

### ISSUE THREAD

**Issue by harshvishu** [realm/realm-cocoa#3521]
<img width="1068" alt="screen shot 2016-05-03 at 10 49 00 pm" src="https://cloud.githubusercontent.com/assets/10331536/14992418/a8105296-1183-11e6-9004-0e8ae3a62622.png">

I am trying to write to realm when an image is downloaded **in background**.
When the app is in foreground no error is thrown but whenever `realm.write{}` is called as a result of `handleEventsForBackgroundURLSession` app crashes.
Realm version: RealmSwift (0.100.0)

Xcode version:  V7.2

iOS/OSX version: OS X El Captain 10.11.4 (15E65)

Dependency manager + version: cocoapods v 0.39.0

**Comment by mrackwitz** [comment]
Have you made sure that you disabled iOS 8's automatic file encryption as seen [here in the docs](https://realm.io/docs/swift/latest/#using-realm-with-background-app-refresh)?

**Comment by harshvishu** [comment]
No, I haven't done that. Should I add this to project's AppDelegate.swift ?

**Comment by harshvishu** [comment]
I added the code just above realm.write{} block in the completionHandler but it is still crashing

**Comment by mrackwitz** [comment]
You have to make sure to set it after the Realm file is initially created, so that the file already exists at the point when you set the attributes. If you're not setting the attributes for a directory. So if you're already accessing your Realm for e.g. migrations from the AppDelegate, then you could set it directly after that.

**Comment by mrackwitz** [comment]
Your file might been corrupted through modifying it in the background while it was encrypted. You would need to try it from a clean state.

**Comment by harshvishu** [comment]
You were right. That seems to have fixed the issue.Thanks a lot for your help!

**Comment by harshvishu** [comment]
![image](https://cloud.githubusercontent.com/assets/10331536/15065664/9365c3be-137f-11e6-8ba5-8ab2fc8ee121.png)
The issue seems to have came up again. I did as you told, I added the code prevent realm from being encrypted. Now it is crashing once in a ten.

It is crashing on first line when I try to fetch a realm object by query.
`  
                    if let location = realm.objects(DLocation).filter("id = %d", id).first{
                        try! realm.write{
                            location.imageFile = fileName
                        }
                    }`

**Comment by mrackwitz** [comment]
This might be something entirely different. Have you tried the latest release? Does the error / crash log stay the same all the time?

**Comment by harshvishu** [comment]
I am using the latest version of Realm Swift (v 0.100.0) and **the crash log is same every time**.
There is no crashing since I reinstalled from clean state. But this has occurred two times earlier. I just wanted to make sure that there is no bug or mistake from my side before going for release.

At the bottom of the crash log there was a line saying "If you encounter this please mail to help.realm.io ". So, I've already emailed the crash log & screen shots.

**Comment by mrackwitz** [comment]
As seen already in my previous mail, we tracked that issue by #3532 and shipped a fix for it in 0.102.0. If this issue should persist for you after updating, please create a new clean issue.
