### ISSUE TITLE
Sectioning for UITableViewController

### ISSUE THREAD

**Issue by hsavit1** [realm/realm-cocoa#3527]
Hi,

Realm v 0.99 added support for fine grained notifications (major achievement 👍 )

However, I can't seem to use this because my UITableViewController needs sectioning support. I was just wondering if that is in the pipeline or if there is a general accepted solution for that. Thanks

**Comment by KieranHarper** [comment]
Sectioning at the database level would be an interesting concept to see explored. Eg getting sections within Results objects because you provided extra sectioning predicate/s to the query

**Comment by hsavit1** [comment]
@KieranHarper exactly

currently the RBQFetchedResultsController project is alive for the sole purpose of tacking this issue. I was just wondering if Realm would be interested in officially supporting this feature sometime in the near future and what that timeline might look like

**Comment by jpsim** [comment]
This is definitely something we want to do, and we're tracking this feature in #3384. I'll be closing this ticket as a duplicate so we can keep the conversation in one place. Thanks!
