### ISSUE TITLE
Inverse Relationships

### ISSUE THREAD

**Issue by pjebs** [realm/realm-cocoa#3533]
I noticed that you recently deprecated `linkingObjectsOfClass`.
I find the section in the objc readme to be confusing. Perhaps it needs to be clarified.

I am getting a `deprecated` warning but the new system doesn't seem to work the same way.

The first paragraph suggests [Person]->can have many "dogs"->[Dog] and [Dog]->has one "owner"->[Person]

The second paragraph suggests [Dog]->can have many "owners"->[Person]

**Comment by pjebs** [comment]
My situation is similar to first paragraph which I accomplished by having a `readonly` property in the Dog object which used `linkingObjectsOfClass`.

The example only has an example in line with second paragraph scenario.

**Comment by bdash** [comment]
If you can share a snippet of your model showing what you're doing using `-linkingObjectsOfClass:forProperty:` I can show you how to update it to using `RLMLinkingObjects`.

**Comment by pjebs** [comment]
In the old way:

```
@property (readonly) RealmEvent *owner;
...
- (RealmEvent *)owner {
    NSArray *owners = [self linkingObjectsOfClass:@"RealmEvent" forProperty:@"rounds"];
    if ((owners == nil) || (owners.count == 0)) {
        return nil;
    }
    else {
        return [owners firstObject];
    }
}
```

Under new way???? How do I get single item?

```
+ (NSDictionary *)linkingObjectsProperties {
    return @{
             @"owner": [RLMPropertyDescriptor descriptorWithClass:RealmEvent.class propertyName:@"rounds"],
             };
}
```

**Comment by pjebs** [comment]
[RealmEvent] can have many [RealmRound]
[RealmRound] has one "owner" [RealmEvent]

**Comment by bdash** [comment]
For your case, you can use `RLMLinkingObjects` in approximately the same way you were using `linkingObjectsOfClass:forProperty:`.

In your header file:
```objc
@interface RLMRound : RLMObject
// …
@property (readonly) RealmEvent *owner;
@end
```

In your implementation file:
```objc
@interface RLMRound ()
@property (readonly) RLMLinkingObjects *owners;
@end

@implementation RLMRound

+ (NSDictionary *)linkingObjectsProperties {
    return @{
        @"owner": [RLMPropertyDescriptor descriptorWithClass:RealmEvent.class propertyName:@"rounds"],
    };
}

- (RealmEvent *)owner {
    return self.owners.firstObject;
}

@end
```

**Comment by pjebs** [comment]
In the `linkingObjectsProperties` method, change `owner` to `owners` in dictionary key.

What were the advantages of the way? For my use case it seems more verbose.

**Comment by bdash** [comment]
You're quite correct that `RLMLinkingObjects` requires more boilerplate than the old approach. That's mostly due to limitations of Objective-C as with our Swift API they're very similar. There are some advantages to using `RLMLinkingObjects` properties that may be relevant to you: they can be used in queries. For example, you could query for all `RealmRound` objects with no owner.

We're not against reintroducing a programatic way of fetching linking objects if we hear from more users about this.

**Comment by pjebs** [comment]
I think you're right.

**Comment by pplant** [comment]
Hi, I think this is quite a common use-case probably it would be a good idea to add this to your documentation.

**Comment by jpsim** [comment]
Our documentation demonstrates how to set up inverse relationships here: https://realm.io/docs/objc/latest/#inverse-relationships
