### ISSUE TITLE
[RLMRealmConfiguration setFileURL:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by bnAndres** [realm/realm-cocoa#3545]
Hello,
I am trying to use a realm from a bundle. I used to do it like this:

`RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];`
`config.path = [[NSBundle mainBundle] pathForResource:@"Example" ofType:@"realm"];`
`config.readOnly = YES;`
`RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:nil];`

But after updating the realm version (0.99.1 with CocoaPods), since 'path' is deprecated, I am using this:

`config.fileURL = [[NSBundle mainBundle] URLForResource:@"Example" withExtension:@"realm"];`

But I am getting a '[RLMRealmConfiguration setFileURL:]: unrecognized selector sent to instance' exception when setting the file URL.

Thanks for any help.

PS: latest realm version 0.102.0 has another issue. Can't build with that one. But 0.99.1 is ok for now.

**Comment by mrackwitz** [comment]
Have you tried a clean build from scratch?

**Comment by bnAndres** [comment]
Just tried, using fileURL on a new project works. What does that mean now? Do I have some old realm code lying around in the project?
I have tried to remove the Pods folder, .xcworkspace and Podfile.lock and ran pod install again before. But that ended up with the same error.

Thanks for the help

**Comment by mrackwitz** [comment]
Try to delete the cached build products. You can achieve that in Xcode 7 by pressing Option (⌥) and navigating to the menu entry **Product** > **Clean Build Folder…**. (⌥⇧⌘K)

**Comment by bnAndres** [comment]
That did it! Thank you mrackwitz.

I tried a simple "Clean" before, didn't know that there are other options with Option (⌥). When should I use "Clean" and when "Clean Build Folder"?

**Comment by mrackwitz** [comment]
**Clean** removes the build products for the current target and all its dependencies, that usually includes implicit dependencies as used by CocoaPods. But changing the setup of your target can cause that there are left-overs from former setups, which wouldn't be built anymore, but can be still picked up as dependency. **Clean Builder Folder** removes all build products of all targets of the current project / other projects which share the same build folder.
