### ISSUE TITLE
Realm crashing with multiple encrypted configurations

### ISSUE THREAD

**Issue by 00StevenG** [realm/realm-cocoa#3553]
We’re having issues with our Realm setup in which some cases Realm fails to load upon application launch (didFinishLaunchingWithOptions).
We’re currently handling this exception and deleting the local realm file and successfully loading new instance. Of course we’d prefer not to do this.

Our first encrypted realm instance (caches directory) vends an encryption key utilized by our second encrypted realm instance (documents directory) config.

Our sequence is something like this:

-Create Realm config for app instance (stored in documents)
-Retrieve encryption key for the app instance config
-Create Realm config for key instance (stored in caches)
-Fetch encryption key from Keychain for key instance
-Open key instance Realm and vend key to app instance config
-Set Realm config encryption key on app instance
-Open App instance realm.

Are there known Realm issues with that we might be running into here? 

Realm version: .100

Xcode version: 7.3.1

iOS/OSX version: 9.3.1

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Hi @00StevenG,

Thanks for filing a ticket. Can you share the error messages from the errors being thrown when your Realms fail to load?

**Comment by fisch0920** [comment]
@austinzheng I work with @00StevenG; the issue opening the realm file is the same as #3438 and we are unable to get any more detail on the potential cause of Realm failing to open.

**Comment by austinzheng** [comment]
As you saw, the next version of Realm should have better logging. If you do see this problem again, please update this ticket and we'll continue troubleshooting from there.

**Comment by jpsim** [comment]
@fisch0920 do you have any updates on this? Have you managed to reproduce this since your initial report? I'd love to know if you see this again with the latest version of Realm (1.0 as of this writing). Thanks!

**Comment by fisch0920** [comment]
Thanks guys! We're currently in a round of client updates to push out the most recent version of our product, but when we get a chance to break our current "stability" and upgrade to v1.0, I'll definitely follow up here with as much detail as possible.

**Comment by jpsim** [comment]
Hopefully things have been more stable as of late. I'm closing this issue since we haven't heard back from you in a little while, but if you can spare a minute, we'd love to know how things have been going since your last release!
