### ISSUE TITLE
Realm.Configuration is not listed on a sidebar in RealmSwift API Reference

### ISSUE THREAD

**Issue by stel** [realm/realm-cocoa#3555]
https://realm.io/docs/swift/latest/api/Classes.html

The only link I've found is `Realm` class page -> `configuration` property.

**Comment by jpsim** [comment]
Jazzy issue: https://github.com/realm/jazzy/issues/64

**Comment by jpsim** [comment]
Fixed in realm/jazzy#567

![image](https://cloud.githubusercontent.com/assets/474794/15445980/79d4d98a-1ec4-11e6-9ee6-9efcec464e5e.png)
