### ISSUE TITLE
How about latest version for supporting accessing shared data from TodayExtension?

### ISSUE THREAD

**Issue by zxconan** [realm/realm-cocoa#3557]
Is there any good practice, appreciated.

**Comment by jpsim** [comment]
Yes, you can access Realms across processes, including "Today" extensions. Make sure to set the Realm Configuration's `fileURL` to a location accessible to both processes. You can do this using [`NSFileManager.containerURLForSecurityApplicationGroupIdentifier(_:)`](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/#//apple_ref/occ/instm/NSFileManager/containerURLForSecurityApplicationGroupIdentifier:).
