### ISSUE TITLE
Getting -[__NSArrayM UTF8String]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by jiteshwadia** [realm/realm-cocoa#3564]
## Issue
Getting crash in app upgrade scenario. Gives below error and warning. But this issue happens only when I have AppStore build installed and on top of that I install testflight build. 
If I install developer build on AppStore build, than it works fine. 

I found issue #3422, and based on answer I did upgraded my realm but it still crashed
 
Error: -[__NSArrayM UTF8String]: unrecognized selector sent to instance
Warning: An RLMRealm instance was deallocated during a write transaction and all pending changes have been rolled back. Make sure to retain a reference to the RLMRealm for the duration of the write transaction.

## Goals

What do you want to achieve?
App upgrade

## Expected Results

What did you expected to happen?
App realm initialization to complete without issues.

## Actual Results

What did happened instead?  
Crashed.
Dont have any stack trace. Just have device logs.

## Migration code

Below is my migration code for that.

```objc
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.schemaVersion = 3;

    if (oldSchemaVersion < 2)
    {
        [migration enumerateObjects:DB_Class1.className
                              block:^(RLMObject *oldObject, RLMObject *newObject) {
                                  newObject[@"thisIsArray_1"] = nil;
                              }];
        [migration enumerateObjects:DB_Class2.className
                              block:^(RLMObject *oldObject, RLMObject *newObject) {
                                  newObject[@"thisIsInt_1"] = 0;
                                  newObject[@"thisIsInt_2"] = 0;
                                  newObject[@"thisIsInt_3"] = 0;
                              }];            
    }
```

All of the above newObjects are added in this version only

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A284

/Applications/Xcode 2.app/Contents/Developer
Xcode 7.3
Build version 7D175

/usr/local/bin/pod
0.39.0
Realm (0.96.3)
Realm (~> 0.96.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

(not in use here)

/usr/bin/git
git version 2.6.4 (Apple Git-63)

**Comment by austinzheng** [comment]
Hi @jiteshwadia,

Sorry to hear you're experiencing issues with Realm. We've since released several updates since 0.96.3, many of which contain bug fixes for similar issues. If you want, you can try updating your app to use the latest version of Realm, and then see if you can reproduce the issue. If so, any sample project you can make that demonstrates the crash would be appreciated, or just any information you can provide. Let me know if you have any questions or concerns.

**Comment by stel** [comment]
@jiteshwadia do you have any updates on this? Thanks!

**Comment by austinzheng** [comment]
It's been over a month. Please open a new issue, with a reproduction case, if you continue to see this problem. Thanks!
