### ISSUE TITLE
Consistently use managed/unmanaged to refer to persisted/standalone objects

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3566]
In the docs, we use a variety of words to describe Realm objects when they are either attached or detached from a Realm. Java has settled on using the terms managed & unmanaged and I think we should do the same. At the very least, no matter the terms we pick, we should be consistent.

**Comment by austinzheng** [comment]
I still need to edit (and copyedit) the code documentation.

**Comment by austinzheng** [comment]
This is finished. Swift 3 needs its own documentation, but that's contingent on a few other things and orthogonal to this ticket.
