### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by tolgayildirim** [realm/realm-cocoa#3569]
When I download xcode package manager "Realms Plugin" Download is not complemented end stick on % 30 approximately. Exactly what should I do?

**Comment by jpsim** [comment]
Well, there's no such thing as an "xcode package manager", so maybe you're referring to [Alcatraz](https://github.com/alcatraz/Alcatraz)? If you're having trouble downloading the Realm Plugin for Xcode via Alcatraz, try checking your internet connection.

**Comment by tolgayildirim** [comment]
Thanks, I'm using Alcatraz package manager plugin for xcode. I agree with you your right. My network connection may cause trouble.

**Comment by jpsim** [comment]
Alright, please let us know if you have issues that are unrelated to your Internet connection.
