### ISSUE TITLE
Can't access custom configurations from background thread using Swift.

### ISSUE THREAD

**Issue by iJoeCollins** [realm/realm-cocoa#3572]
## Goals
Access a custom configured realm from a background thread in Swift.

## Expected Results
Be able to access a realm using try! Realm(configuration: config) in a background thread.

## Actual Results
No results are returned when queried. And I suspect the realm itself is not accessed.

## Steps to Reproduce

Create a dispatch_async(queue) call and try to access a preinstalled realm using Swift.

## Code Sample

```swift
dispatch_async(queue) {
    // Open the Realm with the configuration
    let realm = try! Realm(configuration: config)

    // Read some data from the bundled Realm
    let results = realm.objects(Dog).filter("age > 5")
}
```

## Version of Realm and Tooling

Realm version: 0.102.0

Xcode version: 7.3.1 (7D1014)

iOS/OSX version: iOS 9.3, OSX 10.11.4

Dependency manager + version: CocoaPods 0.39.0

**Comment by bdash** [comment]
Thanks for the report. We've had a previous report of this and are tracking the issue in #3540.
