### ISSUE TITLE
`RLMResults` should have an `invalidated` property

### ISSUE THREAD

**Issue by joelkraut** [realm/realm-cocoa#3579]
## Goals

Need a way to tell if a `Results` object is invalidated.
http://stackoverflow.com/questions/37201922/how-to-check-for-rlmresults-invalidated

## Expected Results

`Results` should have an `invalidated` property.

## Actual Results

It doesn't.

Realm version: 1.0.2

Xcode version: 7.2.1

iOS/OSX version: 10.11.4

Dependency manager + version: Carthage

**Comment by joelkraut** [comment]
@bdash can you give me some general ETA on this? If it's not going to be fixed by the time I ship, I'm going to have a lot of `.map { $0 }` to do, and I might as well get started.

**Comment by jpsim** [comment]
Results are only ever invalidated if their Realm is, so why not just check `Results.realm.invalidated`?

**Comment by bdash** [comment]
@jpsim, that's not sufficient. A `Results` that depends on a deleted `LinkView` or a backlinks for a deleted row is also invalidated, but there's no way to detect that case.

**Comment by tgoyne** [comment]
When did that change? We made it so that Results that depend on a deleted LinkView are just empty a few versions back, and a change to make it instead be invalid isn't listed in the changelog.

**Comment by bdash** [comment]
`Results::validate_read` contains the following check since fb541e16:
```c++
if (m_mode == Mode::LinkView && !m_link_view->is_attached())
    throw InvalidatedException();
```

**Comment by tgoyne** [comment]
Ah, I think I wrote that before we made queries on deleted LinkViews not crash, and then failed to update that when merging. I think Mode::LinkView isn't actually used for anything that makes it to the user after the change to expose whether a Query uses the table order, though.

I guess the actual task here is to go through all the scenarios and make sure they're all handled sensibly, and then added `Results.invalidated` if it turns out to still be needed.

**Comment by bdash** [comment]
I'll take a crack at doing that.

**Comment by joelkraut** [comment]
Also, as far as I can tell `invalidated` isn't exposed on `Realm` either? Maybe this is an omission in Swift?

**Comment by bdash** [comment]
Right you are. Only `RLMObject` / `Object` and `RLMArray` / `List` can report whether they are invalidated at present.

**Comment by bdash** [comment]
There are two changes we should make:

1. Don't treat a `Results` that depends on a detached link view or table view as invalidated. It should instead be treated as empty.
2. Add an `invalidated` property on `RLMResults` and `Results` so it's possible to determine whether the object has been invalidated by a call to `Realm.invalidate()`. This is now the only way to invalidate a `Results`.
