### ISSUE TITLE
Data won't get saved to a database file. 

### ISSUE THREAD

**Issue by KMKRN** [realm/realm-cocoa#3586]
I am writing a simple test app and I was very excited about getting to work with Realm.
I am trying to store a User object in a database, but the database is always empty. No crush is happening, the data just isn't there.
  ```
func registerNewUser(username: String, password: String, displayName: String){
        do{
            try realm.write({
                let newUser = User()
                newUser.username = username
                newUser.password = password
                newUser.displayName = displayName
                currentUser = newUser
            })
        }
        catch{
            print("error")
        }
        let users = realm.objects(User)
        for u in users{
            print(u.displayName) 
  }
    }

```
I make a simple query which results in nothing, because the data won't get saved. Realm Browser also shows an empty database file. 
      

Realm version: 0.102.1

Xcode version: 7.3

iOS/OSX version: iOS 9.3

Dependency manager + version: Carthage v. 0.16.2

**Comment by bdash** [comment]
You appear to be missing the call to `Realm.add` that would persist your `User` object to the Realm file. If you add:
```swift
realm.add(newUser)
```
within the closure passed to `Realm.write`, do you get the results you expect?

**Comment by KMKRN** [comment]
Yes, my mistake was really stupid. `realm.add(newUser)` fixes it. Thanks for help!
