### ISSUE TITLE
Efficient way to do : "select distinct column order by column DESC"

### ISSUE THREAD

**Issue by helabenkhalfallah** [realm/realm-cocoa#3588]
Hello,

I have an object event :

```
dynamic var eventTitle = ""
dynamic var eventDate = NSDate()
dynamic var eventHtmlDescription = ""
```

I want to "select distinct eventDate order by eventDate DESC".

What i have done :

```
do {
            let realm = try Realm()
            let sortProperties = [SortDescriptor(property: "eventDate", ascending: false)]
            if let dateArray = realm.objects(Event).sorted(sortProperties).valueForKey("eventDate") as? [NSDate]{
                
                //set to eliminate duplicated date
                return Array(Set(dateArray))
            }
        } catch let error as NSError {
            AppLog.e("CalendarEventReader getEventsDates error : \(error)")
        }
```

The first issue is the way in order to have "distinct column", 3 jobs: objects, valueForKey and after using Set.

Then for order, without using Set, i can have a correctly sorted result. But using Set, i loose order.

So, i must re-order Set before returning the array. This is a too much work especially when i have a lot of stored data and specially when using a grouped tableview (scroll lag, not smooth and slow).

Is there any other efficient way to return "select distinct column order by column DESC".

**Comment by jpsim** [comment]
why not use `NSOrderedSet`?: `return Array(NSOrderedSet(array: dateArray))`

**Comment by helabenkhalfallah** [comment]
There's not a way to get the result directly by Realm without valueForKey/Set/NSOrderedSet (like on SQLite, only one request to get result)?
Thank you so much :)

**Comment by jpsim** [comment]
We're tracking adding support for getting distinct results in #1103.
