### ISSUE TITLE
Cannot setup relationship when object already exists in database

### ISSUE THREAD

**Issue by xiaodao** [realm/realm-cocoa#3596]
Given I have a `Person` class which has a `Dog` property

Given I save the `Dog` object first

When I calls

```
realm.transactionWithBlock({
  person.dog = dog
})
```

I will get error: Can't set primary key property 'id' to existing value

---
We have a requirement to save Dog first before creating a Person, so what can we do to setup the relationship? Thanks.

**Comment by tgoyne** [comment]
You need to fetch the existing Dog object from the Realm rather than creating a new one. Rather than something like:

    var dog = Dog()
    dog.id = myDogId

    realm.transactionWithBlock({
      person.dog = dog
    })

instead do something like:

    var dog = realm.objectForPrimaryKey(Dog.self, myDogId)
    realm.transactionWithBlock({
      person.dog = dog
    })

**Comment by xiaodao** [comment]
@tgoyne Thanks, I'll give it a go.

**Comment by xiaodao** [comment]
yes, it worked as following. Thank you. 

```
    let dog = Dog()
    dog.id = NSUUID().UUIDString
    try! RLMRealm.defaultRealm().transactionWithBlock({
      Dog.createInDefaultRealmWithValue(dog)
    })

    let predicate = NSPredicate(format: "id = '\(dog.id)'")
    let dogFromDB = Dog.objectsWithPredicate(predicate).firstObject() as? Dog

    let person = Person()
    person.id = NSUUID().UUIDString
    try! RLMRealm.defaultRealm().transactionWithBlock({
      person.dog = dogFromDB
      Person.createInDefaultRealmWithValue(person)
    })
```
