### ISSUE TITLE
realm with cocoapods 1.0.0

### ISSUE THREAD

**Issue by arden** [realm/realm-cocoa#3598]
i'm use cocoapods 1.0.0, when use
pod update
there some errors:

Installing Realm (0.102.1)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

when update Realm, and cocoapods exit.

**Comment by mrackwitz** [comment]
Could you please try to reset your installation (`rm -rf Pods`), `pod cache clean Realm` and run `pod update --verbose`? If the error still persists, you would get more helpful output.
As your profile indicates that you life in china, this might be very likely another instance of what we track by #2713. You will find there some further hints.
