### ISSUE TITLE
sortedResults

### ISSUE THREAD

**Issue by CYBoys** [realm/realm-cocoa#3610]
## Goals

Sorting can sort from the end of the comparison

## Expected Results

Sorting can sort from the end of the comparison

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 0.102.1

Xcode version: 7.3.1

iOS/OSX version: 1.0

Dependency manager + version: ?

**Comment by mrackwitz** [comment]
Could you try to clarify that? What issue are you facing? Or is this a feature request?

**Comment by bdash** [comment]
@CYBoys, if there's something that you'd like help with you'll need to explain in more detail what it is.
