### ISSUE TITLE
unable to execute command: Segmentation fault: 11

### ISSUE THREAD

**Issue by Anhtastic** [realm/realm-cocoa#3616]
What do you want to achieve? 

Trying to archive my build but i'm getting this weird message: unable to execute command: Segmentation fault: 11 and Linker command failed due to signal (use -v to see invocation).

I can test on my iOS device and simulator perfectly fine, but as soon as I tried to archive it. Build target Realm error shows up. I'm not sure where to begin to look for the errors. Sorry I can't provide anything more than that since I'm not seeing anything else... 

After it compile shared_realm.cpp and transact_log_handler.cpp, it tried to compile Realm_vers.c... and that's when it gave me those errors. 

Using Realm 0.98.8

**Comment by Anhtastic** [comment]
Well this is bad, I updated to Realm 0.103.0 to see if it helps but now I'm getting 44 errors.... However, if I manage enable bitcode = no, I get 2 errors... 
The 2 errors are:  Cannot convert value of type 'AnyRealmCollection <Object> to expected argument type 'AnyRealmCollection' from this line:

swift files: RealmCollectionType.swift and Results.swift
    return _rlmArray.addNotificationBlock { _, change, error in
            block(RealmCollectionChange.fromObjc(anyCollection, change: change, error: error))

**Comment by jpsim** [comment]
Could you please post the output of this script? https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#speeding-things-up-runner

In general, for someone to help you with an issue, it greatly helps if you can tell us how to reproduce it, or better yet, to share a project that demonstrates it.

**Comment by Anhtastic** [comment]
Hi, sorry about that. Here's the info you requested.

ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27

/Applications/Xcode.app/Contents/Developer
Xcode 7.2
Build version 7C68

/usr/bin/pod
1.0.0
Realm (0.103.0)
RealmSwift (0.103.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)


(not in use here)

/usr/bin/git
git version 2.5.4 (Apple Git-61)

Let me know if you need anything else, thank you for your help!

**Comment by jpsim** [comment]
Xcode 7.3 is now required to build Realm. See https://realm.io/news/realm-objc-swift-0.103.0/

**Comment by Anhtastic** [comment]
Thank you kind sir. After updating to the new OS El Captain and Xcode 7.3.1 (always a long process for this...), it works perfectly now. Though I did have to enable bitcode = no. Thanks!

Enjoy your weekend!

**Comment by austinzheng** [comment]
Please feel free to open a new issue if you run into any more problems!
