### ISSUE TITLE
List<String> () : What should I do with this?

### ISSUE THREAD

**Issue by aimobier** [realm/realm-cocoa#3617]
Hello. I regret the data is similar to the way

````json
 {
      "pubTime": "2016-05-19 14:38:45",
      "url": "http://www.yidianzixun.com/article/0DLVtUrn",
      "docid": "http://www.yidianzixun.com/api/q/?path=contents/comments&count=100&docid=0DLVtUrn",
      "commentsCount": 0,
      "pubName": "IT之家",
      "pubUrl": "http://www.ithome.com/html/digi/226590.htm",
      "imgStyle": 1,
      "imgList": [
        "http://bdp-pic.deeporiginalx.com/W0JANzQ5MDE1YTk.png"
      ],
      "title": "2300元，TP-Link Talon路由器上市：4分钟下载一部4K电影",
      "channelId": 4
    }
````

about `imgList` is array.

I want to keep this like the `List<String>`.

It reminds me  `'List' requires that 'String' inherit from 'Object'`

What am I to do？

**Comment by stel** [comment]
`List<T>` is the container type in Realm used to define to-many relationships, it may hold only `Object` subclasses. Please check out the docs [here](https://realm.io/docs/swift/latest/api/Classes/List.html) and a possible solution for your case at http://stackoverflow.com/questions/30612893/store-array-in-realm-object

**Comment by aimobier** [comment]
Thanks for your answer, I have been solved, but I think it's really inconvenient. Also very beautiful.

````swift
   class func RefreshChannleObjects(channelId:Int,finish:(()->Void)?){
    let times = "\(Int(NSDate().timeIntervalSince1970*1000))"  
    NewsAPI.loadGet(cid: "\(channelId)", tstart: times, page: nil, offset: nil) { (data, error) in
        let realm = try! Realm()
        if let _ = error {return }
        if let code = data?.objectForKey("code") as? Int {
            if code != 0 {return}
            if let data = data?.objectForKey("data") as? NSArray {  
                try! realm.write({
                    for channel in data {
                        realm.create(New.self, value: channel, update: true) 
                        
                        if let objcid = channel.objectForKey("docid") as? String,imageList = channel.objectForKey("imgList") as? NSArray {
                            var array = [StringObject]()
                            imageList.enumerateObjectsUsingBlock({ (imageUrl, _, _) in
                                let sp = StringObject()
                                sp.value = imageUrl as! String
                                array.append(sp)
                            })
                            realm.create(New.self, value: ["docid":objcid,"imgLists":array], update: true)
                        }
                    }
                })
                finish?()
            }
        }
    }
}
````

I really like this way, like ` realm.create(New.self, value: channel, update: true) `.
l don't have to do anything. 
But because there is no or like `List<String... > or List<Int... >`  this format,.
I need to do a lot of the operation of the operation. 


Do we have any plans to change this aspect?😃😃😃😃😃

**Comment by stel** [comment]
Glad I could help :)

Check out [Nested Objects](https://realm.io/docs/swift/latest/#nested-objects) article in docs also.

As stated in the [docs](https://realm.io/docs/swift/latest/api/Classes/List.html): "`List<T>` is the container type in Realm used to define to-many **relationships**." ;)
