### ISSUE TITLE
Ordered To-Many Relationships

### ISSUE THREAD

**Issue by rpowelll** [realm/realm-cocoa#3618]
## Goals

I want to be able to model an ordered to-many relationship. This could be something like a playlist in a music app, where the `Playlist` object has an ordered collection of `Song` objects, and where multiple playlists can reference the same songs in a different order.

## Expected Results

I'd like something along the lines of an ordered variant of `List`, or perhaps a way to specify an `order` property on a `LinkingObjects` instance. Ideally whatever solution is implemented would still support auto-updating results.

**Comment by mrackwitz** [comment]
`List` properties are already ordered inherently. Sorting them returns a sorted view, but this doesn't change the persisted order. Auto-updates are supported for their persisted order as well as any results constrained to filters and orders.
