### ISSUE TITLE
RealmMapView: Configuration' has no path

### ISSUE THREAD

**Issue by David2XN** [realm/realm-cocoa#3625]
## Goals

using RealmMapView

## Actual Results

Pods/RealmMapView/RealmMapView/RealmMapView.swift:282:13: Value of type 'Realm.Configuration' has no member 'path'

## Steps to Reproduce

 - Add following lines to podfile

```
pod 'RealmMapView'
# Map data set
pod 'RealmSwiftSFRestaurantData'
```
 - Build

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

/Applications/Xcode.app/Contents/Developer
Xcode 7.3.1
Build version 7D1014

/Users/Air/.rvm/gems/ruby-2.1.1/bin/pod
1.0.0
Realm (0.103.1)
RealmSwift (0.103.1)

**Comment by bdash** [comment]
It looks like RealmMapView needs to be updated to be compatible with v0.103. I'd suggest filing an issue against RealmMapView at https://github.com/bigfish24/ABFRealmMapView.

**Comment by jpsim** [comment]
Closing this as it's clearly just that ABFRealmMapView hasn't been updated for the new version of Realm.
