### ISSUE TITLE
Xcode creating a Realm target by itself

### ISSUE THREAD

**Issue by goktugyil** [realm/realm-cocoa#3626]
http://stackoverflow.com/questions/37211001/xcode-creating-a-realm-target-by-itself

**Comment by jpsim** [comment]
It looks like a CocoaPods or Xcode cacheing issue to me. Try this:

    pod deintegrate || rm -rf Pods
    pod install --verbose

You can also try deleting derived data and cleaning the build folder in Xcode; a number of our users have reported that this solved their CocoaPods issues. To clean the build folder, hold down the ‘Option’ key while opening the ‘Product’ menu, then choose ‘Clean Build Folder…’. You can also type “Clean” into the Xcode help search menu and select the ‘Clean Build Folder…’ menu item when it shows up in the search results.

**Comment by goktugyil** [comment]
Thanks!
