### ISSUE TITLE
Problem with Test Files in XCODE project 

### ISSUE THREAD

**Issue by pavlem** [realm/realm-cocoa#3627]
## Goals

Run Tests in XCODE project

## Expected Results

For the project to work when I run the tests

## Actual Results

If I build the project, it works. 

If target of realm "Object" files (my model files) is set only to the main target, then I get the error "undeclared type and the project wont build when I run the tests"

If target of realm  "Object" files is set to test target as well, then I get the error 
'RLMObject subclasses with the same name cannot be included twice in the same target. Please make sure 'MyModel' is only linked once to your current target.'

I tried the solution from StackOverflow in vain 
http://stackoverflow.com/questions/32273954/unit-testing-swift-2-0-testable-import-and-scheme-targeting-issues/32276984#32276984 

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

/Applications/Xcode.app/Contents/Developer
Xcode 7.3
Build version 7D175

(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.16.2
github "realm/realm-cocoa" "v0.103.1"

/usr/bin/git
git version 2.6.4 (Apple Git-63)

**Comment by jpsim** [comment]
Please provide more details. What's the actual error you're seeing? "undeclared type and the project wont build when I run the tests" isn't actually the exact error message, is it? If you share the steps you took to install Realm and describe your project's configuration, we might be able to help. Or better yet, if you share a project that can reproduce the issue you're seeing, we'll be able to help.

**Comment by pavlem** [comment]
Hi, 

The point of the whole problem is that I cannot implement ANY kind of unit tests while I have Realm in my project. 

**Case when targets for the model objects ARE included for the main target and test target:**
"2016-05-23 09:00:42.427 SatBridge[1667:22533] *** Terminating app due to uncaught exception 'RLMException', reason: 'RLMObject subclasses with the same name cannot be included twice in the same target. Please make sure 'CallLogInfo' is only linked once to your current target.'"

**Case when targets for the model objects ARE NOT included for the test target, but are for the main target:**
In case I remove targets for the tests, I get the error message in the XCODE itself "undeclared type..." when I run the tests again.

Running the project itself works in both cases (when test targets are and are not included), only the tests do not compile. 

Realm was installed via Carthage. 

Down below you have the link for the project and the screens. 

https://github.com/pavlem/realmProblem.git

![targets included](https://cloud.githubusercontent.com/assets/14887690/15463487/239bc7f6-20ca-11e6-939c-855c8fda6b19.png)
![targets not included 1](https://cloud.githubusercontent.com/assets/14887690/15463485/2392dc40-20ca-11e6-9df1-21b0162699a1.png)
![targets not included 2](https://cloud.githubusercontent.com/assets/14887690/15463486/2395ce1e-20ca-11e6-9ac8-6817642a5b16.png)

**Comment by jpsim** [comment]
The problem was that all of the application source files were linked to the unit test target, and so compiled twice, I've submitted a patch here with more details: pavlem/realmProblem#1

**Comment by pavlem** [comment]
I also came to this conclusion yesterday when testing on a new project where source files were not linked to the UNIT targets. I didn't know that this could make a problem and it didn't show up until Realm implementation. Also, I installed Realm via Carthage and had to include both targets (main and test) for the frameworks "Realm.framework" and "RealmSwift.framework" because it wouldn't work otherwise. 

Thank you.

**Comment by AlejandroDeveloper** [comment]
www

**Comment by AlejandroDeveloper** [comment]
I have the same problem but my files is not linked with target Tests , my files is linked two target : TargetApp and Framework Cocoa , help please?
![captura de pantalla 2016-05-26 a las 15 47 46](https://cloud.githubusercontent.com/assets/18003800/15576669/3cb674b6-2359-11e6-893c-07f1894bc2d4.png)

**Comment by jpsim** [comment]
@AlejandroDeveloper please file a new issue, taking care to fill out the issue template and to share any relevant information that could help us reproduce your build issues.
