### ISSUE TITLE
realm browser does not install

### ISSUE THREAD

**Issue by gizmolab10** [realm/realm-cocoa#3632]
## Goals

What do you want to achieve?

install realm browser in Xcode through [already installed] package manager

## Expected Results

What did you expected to happen?

realm browser to appear at the bottom of the View menu

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

no such appearance

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

1. install the package manager
2. open the package manager from the Xcode Window menu
3. install the realm browser successfully
4. run my app on the simulator
5. click on the View menu and look for the realm browser at the bottom

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

```
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

/Applications/Xcode.app/Contents/Developer
Xcode 7.3.1
Build version 7D1014

/usr/local/bin/pod
1.0.0
Realm (0.102.1)
RealmSwift (0.102.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)


(not in use here)

/usr/bin/git
git version 2.7.4 (Apple Git-66)
```

**Comment by jpsim** [comment]
The Realm Xcode Plugin available via Alcatraz does not automatically install the Realm Browser. You can install the Realm Browser via the Mac App Store, Homebrew, zip releases or build it yourself from source. See https://github.com/realm/realm-browser-osx#installing for more details.
