### ISSUE TITLE
Realm in production

### ISSUE THREAD

**Issue by slashburn** [realm/realm-cocoa#3637]
I really love Realm, it's much easier than CoreData. But I have one major concern shipping an app with Realm
The realm docs states:

> **Should I use Realm in production applications?**
> Realm has been used in production in commercial products since 2012.
> 
> You should expect our Objective‑C and Swift APIs to change as we evolve the product from community feedback — and you should expect more features and bugfixes as well.

Say, I ship a production app today with Realm 0.103.x
As far as I've understood it, there is not guarantee that the API is stable. So if I update my app in 2 or 3 months (without changing the schema) and install Realm 0.107.x how do I know that the realm files are compatible?  I don't want my users to lose their data due to a database upgrade. For them the database doesn't matter, for me as a developer it does.

So in the worst case I have the most recent database version but a lot of unhappy users or I might be stuck at the 0.103.x build forever. This might also be a problem with new Swift releases, when certain keywords are deprecated or removed (such as ++ in Swift 3).
What is your opinion on that?

**Comment by tgoyne** [comment]
While we make API breaking changes, we do not make breaking changes to our file format without automated migration to the new format. Files written by Realm in 2012 are still openable by the most recent versions of Realm today, and we'll never release a version that can't open older files (barring bugs which we will hurry to fix as quickly as possible, of course). A database library which doesn't preserve users' data would be quite useless.

**Comment by jpsim** [comment]
I hope @tgoyne's explanations are satisfactory for you @slashburn. If you have any further questions, don't hesitate to comment again and we can reopen this, or you can file a new issue.

**Comment by slashburn** [comment]
Yes, thanks. I'm currently tweaking Realm for my production app :)
