### ISSUE TITLE
many-to-one inverse relationship with 0.102.0

### ISSUE THREAD

**Issue by xiaodao** [realm/realm-cocoa#3640]
Hey team,

I can see great improvement in version 0.102.0 and thank you very much for your great effort on making Realm better.

Meanwhile, I noticed a change on inverse relationship.

With version 0.98.6, for a relationship like 1 Person has many Dogs and 1 Dog has one owner, I can setup the relationship like:

```
Class Dog {
  var owner: Person? {
    return linkingObjectsOfClass(String(Person), forProperty: "dogs").first as? Person
  }
}
```

but `linkingObjectsOfClass` method in deprecated now, and how could I setup an inverse relationship without breaking the existing API - `owner` returns a Person, not a RLMResult?

Thanks.

**Comment by tgoyne** [comment]
The simplest way is to just have a private LinkingObjects property which is then exposed with a computed getter:

```
class Dog {
  private let owners = LinkingObjects(fromType: Person.self, property: "dogs")
  var owner: Person? {
    return owners.first
  }
}
```

**Comment by xiaodao** [comment]
Cool, many thanks.
