### ISSUE TITLE
BUG: When delete records from Realm DB the db is reordering itself in a way i can't figure ?

### ISSUE THREAD

**Issue by YHSX88** [realm/realm-cocoa#3642]
## Goals

I want to delete record/s from Realm DB and when I do so via swift code the DB is reodering itself, at least this is what i can see in the Realm Browser version Version 0.103.1 (75).

The primary goal is to have table view and i want the user to be able to delete records but even after the records are deleted i need what's left there to be ordered by Date. Well don't think this self reordering is intended behaviour or at least i don't know the rules that are used to reorder the data.

## Expected Results

I want to see that I have 3 records and I delete the last 1 one to see that the second becomes first and the third becomes second.

![screen shot 2016-05-24 at 18 06 10](https://cloud.githubusercontent.com/assets/16823745/15509018/86732ba6-21da-11e6-8466-fb1ef51b6698.png)

## Actual Results

There is no crash is just when I have for example 3 records and I delete the first 1 (I'm considering the first one to be with id 0 and you can see the date that was created it's NSDate value.) 

![screen shot 2016-05-24 at 18 09 01](https://cloud.githubusercontent.com/assets/16823745/15509066/c9715752-21da-11e6-919b-5d66f7b95ebf.png)

## Steps to Reproduce

1. Create model like this:

```
import Foundation
import RealmSwift

class Odddddd: Object
{
    dynamic var id = 0
    dynamic var date:NSDate?
    dynamic var sssss = 0
    dynamic var bbbb = 0
    dynamic var ssssffff = 0
    dynamic var aaaa:String = ""
    
    override static func primaryKey() -> String?
    {
        return "id"
    }
}
```

2.Then put some records in the DB
3.Then open it with realm browser with the specified version.
4.Then then from the app delete the cells , actually you can do it directly in the realm browser. They will still reorder themselves.

## Code Sample

The issue can be replicated without code, but just with realm browser as well.

## Version of Realm and Tooling

**Realm version: ?** 
Using RealmSwift (0.103.1)

**Realm Browser version: ?**
Version 0.103.1 (75).

**Xcode version: ?**
Version 7.3 (7D175)

**iOS/OSX version: ?**
El Capitan 10.11.5
Simulator iPhone 6S iOS 9.3 (13E230)

**Cocoapods Version:?**
Cocoapods:  pod --version -> got result of  0.39.0

**Comment by bdash** [comment]
Objects have no inherent order within the Realm. If you'd like to display objects in a particular order, you can sort the `Results` using [`Results.sorted(_:ascending:)`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sortedFTSS9ascendingSb_GS0_x_) or [`Results.sorted(_:)`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sorteduRd__s12SequenceTypeWd__9Generator7Element_zVS_14SortDescriptorrFqd__GS0_x_).

**Comment by YHSX88** [comment]
All clear, thank you very much for the fast response.
