### ISSUE TITLE
Relations between two or more tables

### ISSUE THREAD

**Issue by KevinChris** [realm/realm-cocoa#3647]
I have few tables and one mapping table. For example, Country, State, District as tables. I would like to query in java such that on selection of any Country it has to load only States mapped to the Country. That mapping will be given in mapping table. Below is the mapping tables structure looks like.

**Country State District**
   ABC       123   One
   ABC       123   Two
   DEF       456   Ten

Country table looks like below:

**ID Country**
  1   ABC
  2   DEF

State looks like :
**ID State**
  1   123
  2   456

and similar way district also...

On selection of country I have should pick up the distinct state **(Only state names I need, I don't want ID's of state)** on basis of selected country.

How I'm doing right now:

       `Realm realm = Realm.getDefaultInstance();
        RealmResults<MLocationMappingRealm> mappingRealms = realm.where(MLocationMappingRealm.class).equalTo("StateID", stateID).findAll();
        String[] districts = new String[mappingRealms.size()];
        for (int i = 0; i < mappingRealms.size(); i++) {
            districts[i] = realm.where(MDistrictRealm.class).equalTo("DistrictID",
                    mappingRealms.get(i).getDistrictID()).findFirst().getDistrictValue();
        }`

**But this one doesn't give me the distinct values.** How else can I simply this?

**Comment by bdash** [comment]
@KevinChris, I think you wanted to ask this at https://github.com/realm/realm-java.
