### ISSUE TITLE
Crash when querying...

### ISSUE THREAD

**Issue by ehlersd** [realm/realm-cocoa#3653]
## Goals

What do you want to achieve?

Query and remove Realm objects whose "_expires" field is in the past.

## Expected Results

Query returns an array of Realm objects to delete.

## Actual Results

The app crashes, with the following details in the debugging console:

> Traceback (most recent call last):
>   File "/Users/darrenehlers/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
>     return 'Unevaluated query on ' + class_name
> TypeError: cannot concatenate 'str' and 'NoneType' objects

<img width="411" alt="screenshot 2016-05-25 23 11 22" src="https://cloud.githubusercontent.com/assets/2302997/15563418/0891cb6c-22ce-11e6-9528-47a0bbf1b944.png">

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

```
{
    NSPredicate*                predicate       = [NSPredicate predicateWithFormat:@"_expires < %@", [NSDate date]];
    RLMResults<DAORealmBeer*>*  expiredItems    = [DAORealmBeer objectsWithPredicate:predicate];
    
    [RLMRealm.defaultRealm transactionWithBlock:
     ^()
     {
         [RLMRealm.defaultRealm deleteObjects:expiredItems];
     }];
}
```
## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 0.98.7

Xcode version: 7.3.1

iOS/OSX version: 9.3.2

Dependency manager + version: /usr/local/bin/pod  0.39.0

**Comment by TimOliver** [comment]
Hi @ehlersd! Sorry to hear you've been experiencing a crash.

Before we proceed, there's a few things I'd like to ask first:

* You're running on Ream 0.98.7, which is quite old at this point, and we've shipped a lot of bug fixes since then. Is there a reason why you haven't updated your copy of Realm?
* Can you please post the model definition for your `DAORealmBeer` object?
* Are you performing any checks to see if `expiredItems` actually contains any objects (i.e. `expiredItems.count > 0`) before starting a Realm transaction?

Please let me know these things as soon as you can! Thanks!

**Comment by ehlersd** [comment]
@TimOliver No, I guess I just haven't updated my pods recently.  I will update them and retry.

Also, no, I don't `check for expiredItems.count > 0`.  I can easily do that, but is it required that the array contain at least 1 item?

**Comment by jpsim** [comment]
This looks like #3579, which was fixed in #3603 and included in 0.103.0. @ehlersd could you please update to Realm 1.0 and let us know if you're still seeing this?

**Comment by shanemileham** [comment]
I'm running Realm 1.0 and have the exact same issue. On each of the following lines, I get that error.

Code:
```
NSString *predicateString = [NSString stringWithFormat:@"facebook_token = '%@'", token];
RLMResults<User *> *users = [User objectsWhere:predicateString];
```

Error:
```
Traceback (most recent call last):
  File "/Users/bond/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by SteveTrombley** [comment]
I am having the exact same issue as well.

Code:

`    NSPredicate *pred = [NSPredicate predicateWithFormat:@"batteryTypeId='%@'", batteryId];
    RLMResults<RMScreening *> *screenings=[RMScreening objectsWithPredicate:pred];

Error:
`2016-06-01 10:29:38.912 DANA[65351:1133949] Main View Appeared
Traceback (most recent call last):
  File "/Users/Steve/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
(lldb) `

**Comment by ehlersd** [comment]
@jpsim Updating seems to have resolved the error I was seeing.  I will address it again if it reappears.

**Comment by jpsim** [comment]
@SteveTrombley @shanemileham you're both seeing #3655, which was discovered in this thread but is otherwise unrelated to this issue.
