### ISSUE TITLE
version 1.0.0 via pod install stucks forever (on cocoapods version 1.0.0 also 0.39.0 )

### ISSUE THREAD

**Issue by bayarmanlai** [realm/realm-cocoa#3654]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by jpsim** [comment]
From [our docs](https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers):

> If you have troubles with your CocoaPods integration, it might help to reset the integration state. To achieve that simply run the following commands in Terminal out of your project directory:
>
>
>     pod cache clean Realm
>     pod cache clean RealmSwift
>     pod deintegrate || rm -rf Pods
>     pod install --verbose
>
> You can also try deleting derived data and cleaning the build folder in Xcode; a number of our users have reported that this solved their CocoaPods issues. To clean the build folder, hold down the ‘Option’ key while opening the ‘Product’ menu, then choose ‘Clean Build Folder…’. You can also type “Clean” into the Xcode help search menu and select the ‘Clean Build Folder…’ menu item when it shows up in the search results.

In the future, please fill out the issue template.
