### ISSUE TITLE
LLDB python plugin needs to be updated for changes in RLMResults

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3655]
Noticed this from the report in #3653:

```
Traceback (most recent call last):
File "/Users/darrenehlers/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by shanemileham** [comment]
I'm running Realm 1.0 and have the exact same issue. On each of the following lines, I get that error.

Code:
```
NSString *predicateString = [NSString stringWithFormat:@"facebook_token = '%@'", token];
RLMResults<User *> *users = [User objectsWhere:predicateString];
```

Error:
```
Traceback (most recent call last):
  File "/Users/bond/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by Mehrdadmaskull** [comment]
I'm running Realm 1.0 and I get the same error in the console. It happens every time I use either objectsWhere or objectsWithPredicate.

**Comment by bdash** [comment]
This looks to be because rlm_lldb.py hasn't kept up with recent changes to the implementation of `RLMResults`.

**Comment by shanemileham** [comment]
Note that this causes the RLMResults to be empty following a query.

**Comment by bdash** [comment]
From what I've seen this shouldn't have any impact on the results seen by your program. What makes you think it does?

**Comment by Mehrdadmaskull** [comment]
I haven't had any issues with my results being empty. Projects I've used the latest Realm with have been working well, I was just wondering what that log on the console meant and whether I should be worried about it or not.

**Comment by shanemileham** [comment]
Whoops, that was my mistake. No affect on the running of the program.
