### ISSUE TITLE
Which version of swift realm should I be using for 7.2.1 Xcode?

### ISSUE THREAD

**Issue by rlam3** [realm/realm-cocoa#3656]
Which version of swift realm should I be using for 7.2.1 Xcode? Thanks.

**Comment by jpsim** [comment]
Realm Swift 0.102.1 ([GitHub release link](https://github.com/realm/realm-cocoa/releases/tag/v0.102.1)) was the last version to support Xcode 7.2.1. See our [0.103.0 release post](https://realm.io/news/realm-objc-swift-0.103.0/) where we announced that we completely removed support for older Xcode versions.
