### ISSUE TITLE
XCTAssertNotNil may not work in all cases in Swift

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3661]
Originally reported in #3600, although I haven't reproduced this. The following needs to be done:

- [ ] make a minimized repro case confirming this is actually an XCTest bug
- [ ] file a radar
- [ ] write our own `RLMAssertNotNil` function that works

**Comment by kishikawakatsumi** [comment]
It no longer reproduced in my environment. I'll close this issue after a little more investigation. @jpsim

**Comment by jpsim** [comment]
We can't reproduce this, so closing.
