### ISSUE TITLE
Disable global DidChange notification after write in some cases

### ISSUE THREAD

**Issue by MihaelIsaev** [realm/realm-cocoa#3663]
Hello!

In my project every Object have property named syncStatus.
When object created/changed locally the status is 0, when uploaded status is 1, when downloaded status is 2.
So I upload objects with status=0 only.
After uploading data to server I mark every uploaded object and save it with realm.write function and I don't want to fire DidChange notification because it's run upload again.
The same with downloading, every downloaded object marked and I won't to fire global DidChange notification after realm.write after download.

So, it would be great if realm.write method will have optional value 'skipChangeNotification' or something like that.

Thanks.

**Comment by jpsim** [comment]
I've been meaning to write down an issue tracking something that would accomplish what I think are the same goals that motivated you to come up with your concept, based on the work that @tgoyne did in #3439.

So I just filed #3665 summarizing the approaches that we're currently considering to accomplish this feature. So I'll be closing this ticket in favor of that one. Please don't hesitate to share your thoughts in that thread so we can keep the conversation in one place.

Thanks!
