### ISSUE TITLE
Why I can't sort by relationship property?

### ISSUE THREAD

**Issue by MihaelIsaev** [realm/realm-cocoa#3667]
Hello

Why I can't sort by relationship property?

I have CompanyCurrencies object which have relation to Currencies object by defining

    dynamic var currency: Currency!

and when I tried to get company currencies sorted by currency.name

    let results = realm.objects(CompanyCurrencies.self).filter("removed=NO").sorted("currency.name", ascending: true)

I've got an error

> *** Terminating app due to uncaught exception 'Invalid sort property', reason: 'Cannot sort on 'currency.codeString': sorting on key paths is not supported.'

And after that inside CompanyCurrencies class I created the property

    var name: String {
        return currency.name
    }

and tried to sort

    let results = realm.objects(CompanyCurrencies.self).filter("removed=NO").sorted("name", ascending: true)

and I've got an error again

> *** Terminating app due to uncaught exception 'Invalid sort property', reason: 'Cannot sort on property 'codeString' on object of type 'RCompanyCurrencies': property not found.'

Please tell me right solution

**Comment by mrackwitz** [comment]
You can neither sort on key paths nor on computed properties. We track adding support for the former by #1277.

So long you can sort in memory instead as seen below, but be aware of the performance implications and that the retrieved results are not auto-updated anymore if you cache them.
```swift
let results = realm.objects(CompanyCurrencies.self).filter("removed=NO")
let currencyArray = results.sort { $0.currency.name < $1.currency.name }
```

**Comment by MihaelIsaev** [comment]
It's useless when you use notifications to update the table.

        results = realm.objects(CompanyCurrencies).filter("removed=NO").sorted("currency.name", ascending: true)
        notificationToken = results.addNotificationBlock { [weak self] (changes: RealmCollectionChange) in
            guard let tableView = self?.tableView else { return }
            switch changes {
            case .Initial:
                // Results are now populated and can be accessed without blocking the UI
                tableView.reloadData()
                break
            case .Update(_, let deletions, let insertions, let modifications):
                // Query results have changed, so apply them to the UITableView
                tableView.beginUpdates()
                tableView.insertRowsAtIndexPaths(insertions.map { NSIndexPath(forRow: $0, inSection: 0) },
                    withRowAnimation: .Automatic)
                tableView.deleteRowsAtIndexPaths(deletions.map { NSIndexPath(forRow: $0, inSection: 0) },
                    withRowAnimation: .Automatic)
                tableView.reloadRowsAtIndexPaths(modifications.map { NSIndexPath(forRow: $0, inSection: 0) },
                    withRowAnimation: .Automatic)
                tableView.endUpdates()
                break
            case .Error(let error):
                // An error occurred while opening the Realm file on the background worker thread
                fatalError("\(error)")
                break
            }
        }

And it's real problem! Do we have the solution for this problem?

**Comment by kishikawakatsumi** [comment]
@MihaelIsaev The workaround is adding `currencyName` property to `CompanyCurrencies` for sorting. `currencyName` has the same value as same as `currency.name`. Maintain the values by yourself, though...

**Comment by MihaelIsaev** [comment]
I have done it already by myself but it isn't good solution.

**Comment by mrackwitz** [comment]
I agree that this is problematic for use with fine-grained notifications for table views and the workarounds we try to provide for the meantime are not perfect solutions. For that reason we've said linked issue open around that.

**Comment by asjesset** [comment]
This should be added to the Current Limitations section of the docs. Denormalizing my use-case will be somewhat of a pain.

**Comment by LaxmiSunArc** [comment]
hi my Json file is -> {
    "name": "canteen1",
    "lines": [
        {
            "name": "line1",
            "meals": [
                {
                    "name": "chicken2",
                    "isVegan": false
                },
                {
                    "name": "egges",
                    "isVegan": false
                }
            ]
        },
        {
            "name": "line2",
            "meals": [
                {
                    "name": "chicken",
                    "isVegan": true
                },
                {
                    "name": "egges",
                    "isVegan": true
                }
            ]
        }
    ]
}
  and my Model Class this -> class Canteen: Object {
    @objc dynamic var name: String?
    let lines = List<Line>()
    
    func initWithJSON(json: [String: Any]) {
        self.name = json["name"] as? String
        
        let lines = json["lines"] as! [[String: Any]]
        for lineJSON in lines {
            let line = Line()
            line.initWithJSON(json: lineJSON)
            self.lines.append(line)
        }
        
    }
    
    override static func primaryKey() -> String? {
        return "name"
    }

    
}
class Line: Object {
    @objc dynamic var name: String?
    var meals = List<Meal>()
    let canteens = LinkingObjects(fromType: Canteen.self, property: "lines")
    
    func initWithJSON(json: [String: Any]) {
        self.name = json["name"] as? String
        
        let meals = json["meals"] as! [[String: Any]]
        for mealJSON in meals {
            let meal = Meal()
            meal.initWithJSON(json: mealJSON)
            self.meals.append(meal)
        }
    }
    
    override static func primaryKey() -> String? {
        return "name"
    }

    
}



class Meal: Object {
    @objc dynamic var name: String?
    @objc dynamic var vegan: Bool = false
    let lines = LinkingObjects(fromType: Line.self, property: "meals")
    
    
    func initWithJSON(json: [String: Any]) {
        self.name = json["name"] as? String
        self.vegan = json["isVegan"] as! Bool
    }
    
    override static func primaryKey() -> String? {
        return "name"
    }

    
}
I want to retrieved data from Line Model and my is -> 
 let lines = DB.shared.realm.objects(Line.self).filter("ANY meals.name contains 'chicken2'").toArray(ofType: Line.self)
print(lines.description)
print output is -> 
[Line {
	name = line1;
	meals = List<Meal> <0x60000312d0e0> (
		[0] Meal {
			name = chicken2;
			vegan = 0;
		},
		[1] Meal {
			name = egges;
			vegan = 1;
		}
	);
}]

in this output I want only chicken2 don't want to eggs index , so please suggest me how to do . thank you
