### ISSUE TITLE
Results subscript return different object instance

### ISSUE THREAD

**Issue by leoderbois** [realm/realm-cocoa#3673]
Hi,

## Goals

I work with UIcollectionView and my cells are filled with objects from a `Results<MyRealmObject>` in my Realm DB.

My `MyRealmObject ` can generate an thumbnail (with a function) with information/properties stored in my DB. The thumbnail generation is a little heavy (enough to make slow UICollectionView) so when I finish to generate the thumbnail, I store the `UIImage` in property ignored by Realm Model (because it can be regenerated a lot of time).

The code look like that : 

```swift
private var _cachedThumbnail : UIImage?= nil
func thumbnail()->UIImage{
    if _cachedThumbnail == nil {
        _cachedThumbnail = // loog process which generate thumb
    }
    return _cachedThumbnail!
}


```  

## Expected Results

Get the thumbnail generate once per `MyRealmObject` entity.

## Actual Results

Actually in my UICollectionView Data Source provider method if I wrote that : 

```swift
cell.imageView = myRealmObjectResults[indexPath.row].thumbnail()
```

The thumbnail is always regenerated because `_cachedThumbnail` is always `nil` but if I keep my array like that : ` let myRealmObjectArray =Array(realm.objects(MyRealmObject))` that's work correctly. 

I think every time I do  `myRealmObjectResults[indexPath.row].thumbnail()` from a `let myRealmObjectResults = realm.objects(MyRealmObject)`, the `subscript` return always a new object created by the `Results` class instead to keep them. For me is a bug, but perhaps not if it's that you want, but with this you can't use this type of pattern/process to use some computed data. In my case I can store my `_cachedThumbnail ` as NSData in my Realm base, but it look like more a hack that a real solution, because my `_cachedThumbnail` is not a part of my true model, but more like a computed property. 

Realm version: 1.0.0

Xcode version: 7.3

iOS/OSX version: 9.3

Dependency manager + version: Nope

**Comment by mrackwitz** [comment]
`Results` is a lazy collection in general and does neither eagerly load any objects nor cache them once you retrieve them. The behavior you observe is the intended design. What would help for you in your case, could break and mismatch with the expectations of others.

I'd recommend instead to rethink where you store your generated thumbnails instead. That could e.g. look like seen below:

```swift
class ThumbnailFetcher {
   lazy var cache = [String : UIImage]()
   
   func fetch(object: ImageObject) {
       if let image = cache[object.id] {
           return image
       }
       
       // long process which generate the thumbnail image
       cache[object.id] = image

       // TODO: Maybe prune last accessed image(s) from the cache …

       return image
   }
}

extension ViewController {
    lazy var thumbnailFetcher = ThumbnailFetcher()

    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let object = results[indexPath.row]
        
        let cell = tableView.dequeueReusableCellWithIdentifier(…, forIndexPath: indexPath)
        cell.imageView.image = thumbnailFetcher.fetch(object)
        return cell
    }
}
```

**Comment by leoderbois** [comment]
@mrackwitz  thanks a lot, that can be a solution, after speaking on forums I understand that Realm Objects are made for data only model part and not made for process part of the model. 

Just a question and I done with this thread, why the Array(realm.objects(RealmClass)) code work with my thumbnail system ? And this is a bad solution for realm based model ?

**Comment by mrackwitz** [comment]
You pull all objects into memory at this moment, which means that it is less efficient with memory than just pulling the objects which are currently visible on the screen. Beside that you loose the advantages of the auto-updates / notifications, which you can propagate fine-grained to your collection / table view.

**Comment by leoderbois** [comment]
@mrackwitz perfect, I fully understand what's wrong with my code thanks !

**Comment by danielrhodes** [comment]
I want to reopen this again as I think while "memory efficient", it breaks the expectations for how objects work in Cocoa. 

The expectation is that if you have two references to the same object (say it's held in two different arrays, Array 1 and Array 2), that if you change that object from Array 1, Array 2 will have that same changed object there as well. Likewise, I expect that if I get that object from an Array in two different places, I will get the same object back, not a newly allocated object.

In the same vein, I should expect that if I ask for a Realm object from a `Results` collection, retrieve that object and then later ask for the same object, I would get the same object back. Given that Realm has these auto-update features, I would expect that if there are two `Results` collections which reference the same row in the DB, I would get the same object back as long as those collections are retained.

I don't consider this caching, and I don't think it's unreasonable that if you fetched and accessed the data, that it be retained. I could only see the current design as useful if you are working with a result set that is larger than memory, but that is almost definitely the exceptional case, not the norm.

Correct me if I am wrong, but it seems like this is the behavior of CoreData?
