### ISSUE TITLE
Error ''Realm/RLMArray.h' file not found' with RealmSwift with Xcode 7.1 and CocoaPods 1.0

### ISSUE THREAD

**Issue by doronkatz** [realm/realm-cocoa#3676]
Hi guys,

So, I'm using CocoaPods 1.0 with Xcode 7.1 in Swift and I get the following error:

`/Users/doronkatz/Development/Sandbox/iOS/SwiftyNews/Pods/Realm/include/Realm.h:21:9: 'Realm/RLMArray.h' file not found`

My Podfile resembles something lie:
target 'Swifty News' do
    pod 'RealmSwift', '~> 0.103.1'
    #pod 'Firebase'
    pod 'ARSLineProgress', '~> 1.0'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Fabric'
    pod 'TwitterKit'
    pod "EasyPeasy"
    pod 'Firebase/Messaging'
    pod 'Firebase/Storage'
end

When I roll back cocoa pods i get segment 11 error, probably due to one of the libraries I have, so that doesn't seem to be an option. Ive cleared the Pods cache folder, ive uninstalled and re-installed and still have no ida what the problem is.

**Comment by mrackwitz** [comment]
Please try to clean the whole build folder path / DerivedData and build from scratch.

**Comment by souzainf3** [comment]
Same problem, with the same configuration (Xcode 7.1 and CocoaPods 1.0).

**Comment by jpsim** [comment]
@doronkatz @souzainf3 did following the steps [listed in our documentation](https://realm.io/docs/swift/latest/#cocoapods) help?

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
```

**Comment by doronkatz** [comment]
Yes that did the trick for me. I'm wondering though if the version of Cocoapods conflicted, causing this in the first place


On Jun 7, 2016, at 8:37 AM, JP Simard <notifications@github.com<mailto:notifications@github.com>> wrote:


@doronkatz<https://github.com/doronkatz> @souzainf3<https://github.com/souzainf3> did following the steps listed in our documentation<https://realm.io/docs/swift/latest/#cocoapods> help?

pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose


-

**Comment by jpsim** [comment]
> I'm wondering though if the version of Cocoapods conflicted, causing this in the first place

Yes, updating CocoaPods or Xcode versions often causes cache issues that can easily be resolved by clearing their respective caches.
