### ISSUE TITLE
LinkingObjects always return empty.

### ISSUE THREAD

**Issue by carvalho-oak** [realm/realm-cocoa#3678]
I have the following realm model as below. The variants objects are in the product variants property, but when I try to access the `product` property from the variant it always returns 0 objects. I have already check the database and the relationship is there. (see attached screenshot)

![screen shot 2016-05-31 at 2 27 47 pm](https://cloud.githubusercontent.com/assets/1147251/15663170/2da97ef6-273b-11e6-9eef-fb81c90ec007.png)
![screen shot 2016-05-31 at 2 27 32 pm](https://cloud.githubusercontent.com/assets/1147251/15663171/30cca464-273b-11e6-8544-b60d78aa0279.png)

```
public class Variant: Object {
    public dynamic var id: String = NSUUID().UUIDString
    public let product = LinkingObjects(fromType: Product.self, property: "variants").first
    public override class func primaryKey() -> String { return "id" }
}

public final class Product: Object {
    public dynamic var id: String = NSUUID().UUIDString
    public dynamic var name: String = ""
    public let variants = List<Variant>()
    public override class func primaryKey() -> String { return "id" }
}
```

**Comment by carvalho-oak** [comment]
I am currently using realm version 1.0.0

**Comment by bdash** [comment]
Try:
```swift
private let products = LinkingObjects(fromType: Product.self, property: "variants")
public let product: Product? { return products.first }
```

This gives Realm Swift an opportunity to initialize the `products` property when your `Variant` instances are initialized. With the property declaration you posted Realm Swift has no way of determining which `Variant` the `LinkingObjects` instance is associated with before you call `first` on it.

**Comment by carvalho-oak** [comment]
Thanks @bdash! That works :-)

**Comment by tfe** [comment]
This just bit me; I lost probably an hour to it. Maybe it should be included in the docs? Either way, thank you @bdash!
