### ISSUE TITLE
Project with iOS and OSX targets

### ISSUE THREAD

**Issue by James4Developer** [realm/realm-cocoa#3680]
Hi Guys,

I have problem with the realm. Here is the issue

I got a workspace with OSX and iOS targets but when I use cocopods to integrate Realm with it I get the following,
https://dl.dropboxusercontent.com/u/37686642/Screen%20Shot%202016-05-31%20at%2013.41.53.png

Any idea what it could be?

Kind Regards 

> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by mrackwitz** [comment]
There is an issue in CocoaPods 1.0.0, which prevents Realm to build on OS X. We track this by #3570, but it will require an update of CocoaPods. Meanwhile it might help to use CocoaPods 0.39 to workaround this issue.

**Comment by stel** [comment]
@James4Developer this issue was fixed in CocoaPods 1.0.1, do you have any updates on this? Thanks!
