### ISSUE TITLE
Swift to Objc exposure of List type.

### ISSUE THREAD

**Issue by jazz-mobility** [realm/realm-cocoa#3681]
Is there any way I can expose Realm List type properties in swift to objective c ?
ex - I want to use this class in Objective C, but properties are not accessible as there is nothing objective C type.

@objc public class SPSearchResponseModel: Object, Mappable {

	public let offset = RealmOptional<Int>()
	public let limit = RealmOptional<Int>()
	public let total = RealmOptional<Int>()
	public let count = RealmOptional<Int>()
	public var items = List<SPProductModel>()

	required convenience public init?(_ map: Map) {
		self.init()
	}

	// Mappable
	public func mapping(map: Map) {
		offset.value <- map["offset"]
		limit.value <- map["limit"]
		total.value <- map["total"]
		count.value <- map["count"]
		items <- (map["items"], ListTransform<SPProductModel>())
	}
}

**Comment by stel** [comment]
`List` is a generic type, it can't be represented in Obj-C. So as stated in the docs:

> If you’re looking to use Realm from Objective‑C, or from mixed Objective‑C & Swift apps please see Realm Objective‑C instead.
> The Realm Objective‑C and Realm Swift APIs are not interoperable and using them together is not supported.

**Comment by jazz-mobility** [comment]
Is there any work around for this keeping the swift realm?
I am thinking of exposing the properties as computed properties and return the list type as array. Probably the worst case scenario.

**Comment by jazz-mobility** [comment]
I have changed the class as follows -
Is there any better way to do it ?

@objc public class SPSearchResponseModel: Object, Mappable {

	public var offset = 0
	public var limit = 0
	public var total = 0
	public var count = 0
	public var items: Array<SPProductModel> {
		return Array<SPProductModel>(tempItems)
	}
	private var tempItems = List<SPProductModel>()

	required convenience public init?(_ map: Map) {
		self.init()
	}

	// Mappable
	public func mapping(map: Map) {
		offset <- map["offset"]
		limit <- map["limit"]
		total <- map["total"]
		count <- map["count"]
		tempItems <- (map["items"], ListTransform<SPProductModel>())
	}
}

**Comment by stel** [comment]
If you need a read only access, this might be a solution. Depends on your app.

**Comment by jazz-mobility** [comment]
Yes, i require readonly access in this class. Thanks for your help. 
One last question I have is, Can I use Realm Objective C for pure swift based SDK.

**Comment by kishikawakatsumi** [comment]
@jazz-mobility Yes, you can use Realm Objective-C in pure Swift project. If your model will rewrite in Realm Objective-C in Swift, like the following:

```objc
public class SPProductModel: RLMObject {
    ...
}

public class SPSearchResponseModel: RLMObject, Mappable {
    public dynamic var offset: NSNumber? = 0
    public dynamic var limit: NSNumber? = 0
    public dynamic var total: NSNumber? = 0
    public dynamic var count: NSNumber? = 0
    public dynamic var items = RLMArray(objectClassName: SPProductModel.className())
    ...
```

Above classes can be accessed from both Swift and Objective-C. A disadvantage is a little bit lack of type safety though.

**Comment by jazz-mobility** [comment]
Awesome Answer !
Many thanks for your support.
