### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by tringuyen89** [realm/realm-cocoa#3687]
## Logs from Xcode

alloc_slab.cpp:546: [realm-core-1.0.1] Assertion failed: !cfg.session_initiator
0   Realm                               0x0000000105d5ab68 _ZN5realm4util18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
1   Realm                               0x0000000105d5ae34 _ZN5realm4util9terminateEPKcS2_l + 452
2   Realm                               0x0000000105d5ddd5 _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigE + 2837
3   Realm                               0x0000000105e45c60 _ZN5realm11SharedGroup7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbNS0_15DurabilityLevelEbPKcb + 2288
4   Realm                               0x0000000105d2d18d _ZN5realm11SharedGroup4openERNS_11ReplicationENS0_15DurabilityLevelEPKcb + 205
5   Realm                               0x0000000105d2ce33 _ZN5realm11SharedGroupC2ERNS_11ReplicationENS0_15DurabilityLevelEPKcbNSt3__18functionIFviiEEE + 1427
6   Realm                               0x0000000105d2c86c _ZN5realm11SharedGroupC1ERNS_11ReplicationENS0_15DurabilityLevelEPKcbNSt3__18functionIFviiEEE + 60
7   Realm                               0x0000000105d213c9 _ZN5realm5Realm16open_with_configERKNS0_6ConfigERNSt3__110unique_ptrINS_11ReplicationENS4_14default_deleteIS6_EEEERNS5_INS_11SharedGroupENS7_ISB_EEEERNS5_INS_5GroupENS7_ISF_EEEE + 2633
8   Realm                               0x0000000105b7346b _ZN5realm5_impl16RealmCoordinator11pin_versionEyj + 379
9   Realm                               0x0000000105b73d41 _ZN5realm5_impl16RealmCoordinator17register_notifierENSt3__110shared_ptrINS0_18CollectionNotifierEEE + 177
10  Realm                               0x0000000105b94218 _ZN5realm7Results16update_tableviewEv + 1272
11  Realm                               0x0000000105b943e0 _ZN5realm7Results3getEm + 304
12  Realm                               0x0000000105d097ec _ZZ28-[RLMResults objectAtIndex:]ENK3$_3clEv + 76
13  Realm                               0x0000000105d06216 _ZL15translateErrorsIZ28-[RLMResults objectAtIndex:]E3$_3EDaOT_P8NSString + 38
14  Realm                               0x0000000105d061e8 -[RLMResults objectAtIndex:] + 56
15  Realm                               0x0000000105d0851e -[RLMResults objectAtIndexedSubscript:] + 62
16  RealmSwift                          0x00000001062683a8 _TFC10RealmSwift7Resultsg9subscriptFSix + 136
17  gear                                0x0000000103fe1352 _TFE4gearC10RealmSwift7Results7toArrayurfMqd__GSaqd___ + 322
18  gear                                0x0000000103fecbda _TFC4gear24AssignmentViewController17loadDataFromLocalfT_T_ + 186
19  gear                                0x0000000103feda45 _TFC4gear24AssignmentViewController14viewWillAppearfSbT_ + 309
20  gear                                0x0000000103fedab1 _TToFC4gear24AssignmentViewController14viewWillAppearfSbT_ + 49
21  UIKit                               0x00000001066722bd -[UIViewController _setViewAppearState:isAnimating:] + 710
22  UIKit                               0x0000000106672958 -[UIViewController __viewWillAppear:] + 149
23  UIKit                               0x00000001066a2750 -[UINavigationController _startCustomTransition:] + 1203
24  UIKit                               0x00000001066b2b9b -[UINavigationController _startDeferredTransitionIfNeeded:] + 712
25  UIKit                               0x00000001066b3d0b -[UINavigationController __viewWillLayoutSubviews] + 57
26  UIKit                               0x0000000106862503 -[UILayoutContainerView layoutSubviews] + 248
27  UIKit                               0x000000010658c980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
28  QuartzCore                          0x00000001059aec00 -[CALayer layoutSublayers] + 146
29  QuartzCore                          0x00000001059a308e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
30  QuartzCore                          0x00000001059a2f0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
31  QuartzCore                          0x00000001059973c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
32  QuartzCore                          0x00000001059c5086 _ZN2CA11Transaction6commitEv + 486
33  UIKit                               0x00000001064cc72e _UIApplicationHandleEventQueue + 7135
34  CoreFoundation                      0x0000000108a96301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
35  CoreFoundation                      0x0000000108a8c22c __CFRunLoopDoSources0 + 556
36  CoreFoundation                      0x0000000108a8b6e3 __CFRunLoopRun + 867
37  CoreFoundation                      0x0000000108a8b0f8 CFRunLoopRunSpecific + 488
38  GraphicsServices                    0x000000010becbad2 GSEventRunModal + 161
39  UIKit                               0x00000001064d1f09 UIApplicationMain + 171
40  gear                                0x0000000103f69a72 main + 114
41  libdyld.dylib                       0x00000001099ed92d start + 1
42  ???                                 0x0000000000000001 0x0 + 1

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.0

Xcode version: 7.3.1

iOS/OSX version: 10.11.5

Dependency manager + version: ?

**Comment by jpsim** [comment]
Hi @tringuyen89, sorry you've been affected by this assertion failure. Have you been able to reproduce the problem? We'd appreciate any information that could help us reproduce this.

Thanks.

**Comment by stel** [comment]
This issue was fixed in Realm 1.0.1. @tringuyen89 do you have any updates on this? Thanks!
