### ISSUE TITLE
Crashed when @property NSNumber<RLMInt> is  assigned with unix timestamp value

### ISSUE THREAD

**Issue by modLX4** [realm/realm-cocoa#3688]
Is it because of int overflow ? whats the alternative ? i want to save a NSUInteger as object in realm. What is the solution ?

*** Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value '1464572538' for property 'timestamp''

**Comment by modLX4** [comment]
Whats the max value of  NSNumber<RLMInt> ???

**Comment by kishikawakatsumi** [comment]
@modLX4 The max value of `NSNumber <RLMInt>` is same as 64 bit integer. `1464572538` does not exceed max value. It should work. The error message indicates that a different type of value was assigned the property. 

Could you show your code around assigning the value to `timestamp` for investigation?

**Comment by stel** [comment]
@modLX4 do you have any updates on this? Thanks!

**Comment by jpsim** [comment]
I hope @kishikawakatsumi's answer helped you @modLX4! We're closing this issue now because we haven't heard back from you in a little while.
