### ISSUE TITLE
Using initWithValue with relationships before initializing the shared schema throws an exception

### ISSUE THREAD

**Issue by irishman1921** [realm/realm-cocoa#3690]
What do you want to achieve?

I try create RLMObject initWithValue (dictionary).

What did you expected to happen?

Create new RLMObject.

What did happened instead?  

Crash with log error:

> "Terminating app due to uncaught exception 'RLMException', reason: 'Object type 'DBImage' not persisted in Realm".

When i checked persisted model (created DBImage (initWithValue) before my general object, code working fine. DBImage objects is one-to-many relationships in general model.

What are steps we can follow to reproduce this issue?

Generate dictionary general model -> generate DBImage dictionary (check or uncheck DBImage model persisted(create DBItem model with initWithValue)) -> add all DBImage model to array in general model dictionary -> create general model with initWithValue -> crash (else don't init DBImage before init general model).

Realm version: 1.0

Xcode version: 7.3.1

iOS/OSX version: 9.3.2

Dependency manager + version: cocoaPods + 0.39

**Comment by irishman1921** [comment]
Hm, all work fine, when i call [RLMRealm defaultRealm] before my operation. 
Apparently, realm create realmScheme.

**Comment by jpsim** [comment]
Thanks for reporting this @irishman1921, I think I know what's happening here.

Depending on how we choose to fix this, it's likely that it'll also fix #2377, but that's a completely symptom, so I'm keeping both these issues open.

**Comment by JadenGeller** [comment]
I've been trying very hard to recreate this, but I'm not sure what the issue is. Can you elaborate @jpsim?

**Comment by jpsim** [comment]
@JadenGeller here's a minimal repro case:

```objc
#import "AppDelegate.h"
#import <Realm/Realm.h>

@interface Model1 : RLMObject
@property NSString *prop;
@end
@implementation Model1
@end

RLM_ARRAY_TYPE(Model1)

@interface Model2 : RLMObject
@property RLMArray<Model1> *array;
@end
@implementation Model2
@end

@implementation AppDelegate
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
    NSLog(@"Throws 'Object type 'Model1' not managed by the Realm' exception: %@", [[Model2 alloc] initWithValue:@{@"array": @[@[@""]]}]);
}
@end
```

I think the exception message has changed since this issue was first filed.
