### ISSUE TITLE
schemaVersion not saved after data migration

### ISSUE THREAD

**Issue by xiaodao** [realm/realm-cocoa#3694]
Realm version: 0.98.6 and 1.0.0

I'm using the following code to check if we should do migration or not:

```
  func shouldDoMigration() -> Bool {
    let config = RLMRealmConfiguration.defaultConfiguration()
    let storeURL = NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier("app.id")
    let realmURL = storeURL?.URLByAppendingPathComponent("defaut.realm")
    config.path = realmURL?.path

    print("should do migration? config path: \(config.path)")
    print("config.schemaVersion: \(config.schemaVersion)")
    return config.schemaVersion < 1
  }
```

and use the following code to do migration:

```
func migrateWithCompletion() {
    let config = RLMRealmConfiguration.defaultConfiguration()
    let storeURL = NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier("app.id")
    let realmURL = storeURL?.URLByAppendingPathComponent("default.realm")
    config.path = realmURL?.path
    print("migrating? config path: \(config.path)")

    config.schemaVersion = 1

    config.migrationBlock = { (migration, oldSchemaVersion) in
      if (oldSchemaVersion < 1) {
        // Nothing to do!
        // Realm will automatically detect new properties and removed properties
        // And will update the schema on disk automatically
      }
    }

    RLMRealmConfiguration.setDefaultConfiguration(config)
    print("schemaVersion after migration:\(RLMRealmConfiguration.defaultConfiguration().schemaVersion)")
    RLMRealm.defaultRealm()
  }
```

And I see shouldDoMigration() always returns true and `config.schemaVersion:` always return 0, even if this statement `print("schemaVersion after migration:\(RLMRealmConfiguration.defaultConfiguration().schemaVersion)")` prints 1. 

Is here anything wrong in the code above? 

Many thanks for your help

**Comment by JakeLin** [comment]
`schemaVersion` has updated after the execution of `migrateWithCompletion` but the it will reset to `0` after the app restarts.

It maybe an issue of `init` in `RLMRealmConfiguration`
```
- (instancetype)init {
    self = [super init];
    if (self) {
        static NSURL *defaultRealmURL = [NSURL fileURLWithPath:RLMRealmPathForFile(c_defaultRealmFileName)];
        self.fileURL = defaultRealmURL;
        self.schemaVersion = 0;
    }

    return self;
}
```

**Comment by kishikawakatsumi** [comment]
@xiaodao @JakeLin It's intended behavior. The `RLMRealmConfiguration.schemaVersion` doesn't indicate a version of the file you are trying to open. It is used to set the version of the file to be opened. Then It indicates the version of the file opened.

Use `RLMRealm.schemaVersionAtPath(_:error:)` to get the schema version for a Realm at a given path to check migration is required or not.

**Comment by xiaodao** [comment]
@kishikawakatsumi Thanks for your reply.

I've tried `RLMRealm.schemaVersionAtPath(_:error:)` and it could tell me the correct schema version.

But then here comes another problem, now that I'm using this function to check should migrate or not:

```
  func shouldDoMigration(filepath: String) -> Bool {
    var error: NSError?
    let currentVersion = RLMRealm.schemaVersionAtPath(filepath, error:&error)
    if let actualError = error {
      print("An Error Occurred: \(actualError)")
      return true
    }
    return currentVersion < realmSchemaVersion
  }
```

and I wanted to execute the migration block only when `shouldDoMigration` returns true.

When I delete the app and then reinstall the app in simulator, everything works fine, I got the error message: 

```
An Error Occurred: Error Domain=io.realm Code=1 "Cannot open an uninitialized realm in read-only mode" UserInfo={NSLocalizedDescription=Cannot open an uninitialized realm in read-only mode}
```

but the migration block got executed.

And then when I launched the app for the second time, the app crashed with the error:

```
2016-06-03 07:39:44.357 RESI-Internal[12405:1663078] *** Terminating app due to uncaught exception 'RLMException', reason: 'Provided schema version 0 is less than last set version 1.'
```

Do you know why that happened? 

Many thanks.

**Comment by tgoyne** [comment]
Realm will only run the migration block if the schema version you supply is greater than the one already stored in the file, so there is no need for you to do that check yourself.

**Comment by xiaodao** [comment]
@tgoyne we would like to show some spinner during migration, that's why we want to check first. If the migration is not needed, then we can bypass the spinner.

**Comment by JakeLin** [comment]
@tgoyne should `schemaVersion` it be `set only`? because we can't get the correct version at some time.

**Comment by xiaodao** [comment]
@tgoyne @kishikawakatsumi Sorry, please ignore my code snippet above, I forgot to run 
`config.schemaVersion=1` when we don't need to migration. 

Everything is working fine now, and this issue can be closed.

Just another suggestion, do you think it would be good to mention this in the document? 

```Use RLMRealm.schemaVersionAtPath(_:error:) to get the schema version for a Realm at a given path to check migration is required or not.```

Thanks.

**Comment by stel** [comment]
This method is documented [here](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(cm)schemaVersionAtURL:encryptionKey:error:). The return value could be used for different purposes, not only for checking if migration required.
