### ISSUE TITLE
Access the database

### ISSUE THREAD

**Issue by mcaritesh** [realm/realm-cocoa#3695]
**Questions**: Is there any way to access the realm database through multiple mobile application?
Like two apps wants to use the same database.

**Comment by Kirow** [comment]
just use App Groups to store your realm file

**Comment by jpsim** [comment]
@Kirow's right. Learn more about App Groups in Apple's documentation: https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html#//apple_ref/doc/uid/TP40012582-CH26-SW61

This is similar to sharing data between an extension and your main app, for which we have some documentation (for tvOS), but it's pretty straightforward: https://realm.io/docs/swift/latest/#tvos
