### ISSUE TITLE
'Element' (aka 'RLMObject') is not convertible to ''SPProductModel'

### ISSUE THREAD

**Issue by jazz-mobility** [realm/realm-cocoa#3696]
I am using Realm Objective C framework for my Swift project. When I am trying to access the array it is showing above error.

```swift
@objc public class SPSearchResponseModel: RLMObject, Mappable {

	public dynamic var offset = 0
	public dynamic var limit = 0
	public dynamic var total = 0
	public dynamic var count = 0
	public dynamic var items = RLMArray(objectClassName: SPProductModel.className())

	required convenience public init?(_ map: Map) {
		self.init()
	}

	// Mappable
	public func mapping(map: Map) {
		offset <- map["offset"]
		limit <- map["limit"]
		total <- map["total"]
		count <- map["count"]
		items <- map["items"]
	}
}

for product: SPProductModel in searchResponse.items {
			
}
```

I am using object mapper with realm. Please let me know what I am doing wrong.

**Comment by jazz-mobility** [comment]
A quick response will be appreciated :D

**Comment by austinzheng** [comment]
Hi @jazz-mobility,

Thanks for getting in touch with us. Would you be willing to share the definition of your `SPProductModel` class?

**Comment by austinzheng** [comment]
Also, please declare your `items` property as `let` instead of `dynamic var`.

**Comment by jazz-mobility** [comment]
If I'll change it to let then below line will fail.
items <- map["items"]

**Comment by austinzheng** [comment]
Yeah, sorry about that; I had the Swift bindings in mind. You should keep it as `dynamic var`.

**Comment by jazz-mobility** [comment]
//Product Model v4

@objc public class SPProductModel: RLMObject, Mappable {

	public dynamic var date: NSDate? = nil
	public dynamic var isAddedToWishlist = false

	public dynamic var variationId: String!
	public dynamic var productId: String!
	public dynamic var sku: String!
	public dynamic var title: String!
	public dynamic var productDescription: String?
	public dynamic var status: String!
	public dynamic var strategy: String!
	public var isAvailable = false
	public var stockQuantity = 0
	public var isDefaultVariation = false
	public dynamic var brand: SPProductBrand!
	public dynamic var categories = RLMArray(objectClassName: SPProductCategory.className())
	public dynamic var attributes = RLMArray(objectClassName: SPProductAttributes.className())
	public dynamic var options = RLMArray(objectClassName: SPProductOptions.className())
	public dynamic var media = RLMArray(objectClassName: SPProductMedia.className())
	public dynamic var offers = RLMArray(objectClassName: SPProductOffers.className())
	public dynamic var summary: SPProductSummary!

	required convenience public init?(_ map: Map) {
		self.init()
	}

	public func mapping(map: Map) {
		variationId <- map["id"]
		productId <- map["product_id"]
		sku <- map["sku"]
		title <- map["title"]
		productDescription <- map["description"]
		status <- map["status"]
		strategy <- map["strategy"]
		isAvailable <- map["available"]
		stockQuantity <- map["stock_quantity"]
		isDefaultVariation <- map["is_default_variation"]
		brand <- map["brand"]
		categories <- map["categories"]
		attributes <- map["attributes"]
		options <- map["options"]
		media <- map["media"]
		offers <- map["offers"]
		summary <- map["summary"]
	}
}

**Comment by jazz-mobility** [comment]
I am facing this issues for all RLMArray types

**Comment by jazz-mobility** [comment]
You can refer to https://github.com/realm/realm-cocoa/issues/3681
This is the reason I have to change into objective C

**Comment by austinzheng** [comment]
Hi @jazz-mobility,

Unfortunately, the type of object contained in an `RLMArray` is inferred by Swift to be `RLMObject`, regardless of what you pass in for the object class name. So you'll have to perform a downcast using `as?` or `as!`:

```swift
for object : RLMObject in searchResponse.items {
    let product = object as! SPProductModel
    // do work
}
```

Swift 3 will have [better support for Objective-C generics](https://github.com/apple/swift-evolution/blob/master/proposals/0057-importing-objc-generics.md), so when Swift 3 comes out you should be able to declare your `RLMArray` as `RLMArray<SPProductModel>`, and get rid of the downcast.

Hope that helps! Let us know if it doesn't, or if you have any further questions.

**Comment by jazz-mobility** [comment]
Any other workaround ?
Which directly expose the array objects as SPProductModel ?

**Comment by austinzheng** [comment]
There are no other workarounds as far as I know, unfortunately.

`RLMArray` isn't imported into Swift as a generic type, so there's no way to specify that the `RLMArray` APIs should return your more specific model, instead of the less-specific `RLMObject`.

Apologies for the inconvenience!

**Comment by austinzheng** [comment]
If you have further questions, please feel free to file more tickets. Have a great day!
