### ISSUE TITLE
No Such Module "RealmSwift"

### ISSUE THREAD

**Issue by AAFFTechnologies** [realm/realm-cocoa#3698]
Quick Question, 

Im sure its been answered before 1.0 was released, but for some reason after cocoapoding RealmSwift, I get the famed No such module "RealmSwift" error thrown by XCode. Does anybody know what the fix is for this? Ive got about 3 other pods installed and they installed fine.

Realm version: 1.0.0

Xcode version: 7.3

iOS/OSX version: 10.11.2

Dependency manager + version: Cocoapods 1.0.1

**Comment by jpsim** [comment]
Please try the following to make sure you're operating in a clean state:

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
```

**Comment by AAFFTechnologies** [comment]
No such luck unfortunately after performing the above steps. Podfile setupd:

target "App" do
	pod "Alamofire"
	pod "RealmSwift"
	pod "SwiftAddressBook"
end
use_frameworks!

Any thoughts?

**Comment by austinzheng** [comment]
Apologies for the inconvenience. Can you try cleaning your build and then cleaning your build folder? Also, if you try creating a fresh dummy project, set it up for CocoaPods, and add only `RealmSwift` as a dependency do you see an error as well?

**Comment by AAFFTechnologies** [comment]
Cleaned both, and starting a dummy project produces no errors.

**Comment by AAFFTechnologies** [comment]
Took a look at the dummy project, and somehow it appears my framework search paths werent set in my target. Adding the paths seems to resolve the issue. Closing.

thanks all!

**Comment by jorwan** [comment]
Hi, how did you add the paths to solve this issue ?
Thanks
