### ISSUE TITLE
Swift 3 API renaming

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#3699]
Here is an issue to track and discuss Swift 3 API renaming.

I've put together a preliminary set of suggestions [here](https://gist.github.com/austinzheng/507e16a37e44d07be98f1e56745b8881). Let me know what you think.

@jpsim @bdash @tgoyne @mrackwitz @kishikawakatsumi @stel

**Comment by tgoyne** [comment]
The bulk of them look fine.

> `func filter(with predicateString: String, _ args: AnyObject...) -> Results<T>`

I don't think `with` is correct here; `.filter(with: "x = 5")` reads pretty oddly. I'd be inclined to either have no argument label or to have something that emphasizes that it's an NSPredicate format string and not just a plain string.

> `func minimumValueOf<U: MinMaxType>(property: String) -> U?`

The trailing `Of` in the name feels inconsistent with `index(of:)`. Would `maximumValue(ofProperty:)` violate the naming guidelines? It seems like a better spot to split them to me.

> `func objectForPrimaryKey<T: Object>(_ key: AnyObject, ofType type: T.Type) -> T?`

`object(forPrimaryKey:ofType:)` or maybe even `object(ofType:withPrimaryKey:)` seems better to me.

> func dynamicObjectForPrimaryKey(_ key: AnyObject, ofClass className: String) -> DynamicObject?

This would be good time to fix the problem of that the dynamic API talks about classes and class names while the static API calls things types and type names.

**Comment by austinzheng** [comment]
I agree with the suggestions you've made. Thanks for the review!

`maximumValue(ofProperty:)` should be fine; it flows better too. `students.maximumValue(ofProperty: "age")`.

For no. 1, what do you think of `filter(usingPredicate: "~~~")` or `filter(using: "~~~")`?

For terminology, do you prefer "types" or "classes"?

**Comment by tgoyne** [comment]
> For terminology, do you prefer "types" or "classes"?

Type is the intended terminology, and Class in the dynamic API is just something we didn't catch when porting that over from obj-c.

**Comment by austinzheng** [comment]
I updated the gist.

**Comment by tgoyne** [comment]
It would be good to have these changes in place on a branch for Monday so that our initial Swift 3 preview support at least resembles what the API will end up being. I think it's fine to keep iterating on the exact naming after that.

**Comment by austinzheng** [comment]
https://github.com/realm/realm-cocoa/tree/az-swift3-work has the API changes, and is rebased upon master. Documentation still needs to be updated.

**Comment by JadenGeller** [comment]
Where'd this branch go? @austinzheng Has it already been merged?

**Comment by austinzheng** [comment]
Yeah, I think I ended up creating a new branch, making changes to it, merging it in, and deleting both branches. I can dig it up for you if you want.

**Comment by JadenGeller** [comment]
If I'm understanding correctly, the changes were discarded and did not make it into master?

**Comment by austinzheng** [comment]
The changes should be in master. (None of the Swift 3 source files have the changes, though.)

**Comment by JadenGeller** [comment]
Sorry, I may be misunderstanding. What changes should be in master if not for the Swift 3.0 API changes?

**Comment by austinzheng** [comment]
Sorry, I confused myself.

The Swift 3 API changes are in master. 2e957560804f7f801a8d64f0a9e48d513f6e3c21 is the commit where I merged them into master. I then deleted the branch.

> (None of the Swift 3 source files have the changes, though.)

is completely wrong, disregard it.

**Comment by jpsim** [comment]
Closing this for now since what's in master will suffice for the next little while. We'll do another naming review once Xcode 8 gets closer to its final release.
