### ISSUE TITLE
Method implementation is displayed for one line method declaration in Swift API References

### ISSUE THREAD

**Issue by stel** [realm/realm-cocoa#3701]
https://realm.io/docs/swift/0.103.2/api/Classes/LinkingObjects.html#/s:vC10RealmSwift14LinkingObjects11invalidatedSb

It might be addressed to Jazzy or to "coding guidelines".

**Comment by austinzheng** [comment]
I think this has something to do with SourceKitten. I saw the same thing when dumping the public APIs for Realm Swift yesterday.

**Comment by jpsim** [comment]
Yes, this is due to SourceKit not having enough information to detect where the declaration ends and the body begins.

**Comment by jpsim** [comment]
We're also tracking this in jazzy: realm/jazzy#226

**Comment by jpsim** [comment]
fixed.
