### ISSUE TITLE
File not found exception with realm 1.0

### ISSUE THREAD

**Issue by lehmberg** [realm/realm-cocoa#3702]
## Goals

I want to update Realm to the newest version

## Expected Results

My app to keep working

## Actual Results
I get an exception saying that it is missing a file. This is a new install, so no upgrade of existing app

libc++abi.dylib: terminating with uncaught exception of type realm::util::File::NotFound: open("/Users/alexlehmberg/Library/Developer/CoreSimulator/Devices/8AAB1BCB-5AA3-42A0-9A59-8F4044453EDB/data/Containers/Data/Application/9946D426-A615-48CD-A576-853CBA86D762/Documents/Realm/default.realm.management/log_access") failed: No such file or directory

Next time I run the app it works fine and the files that it complains about are there
## Steps to Reproduce

I am setting up realm to use a specific directory which worked with the previous version:

        var   config = Realm.Configuration()     
        let path = CTFileManager.sharedFileManager().realmPath as NSString
        config.fileURL = NSURL(fileURLWithPath: path.stringByAppendingPathComponent("default.realm"))
        
        // Set this as the configuration used for the default Realm
        Realm.Configuration.defaultConfiguration = config

![2016-06-03_1135](https://cloud.githubusercontent.com/assets/18262180/15775065/2bd91bbc-2980-11e6-80b9-3f9f3fb44ce8.png)

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.0

Xcode version: 7.3.1

iOS/OSX version: 9

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Hi @lehmberg,

Thanks for filing a ticket, and apologies for the inconvenience. While we investigate this problem, could you try explicitly creating the intermediate directory (`Realm/`) before trying to open the Realm using your custom path?

**Comment by lehmberg** [comment]
I am already doing this. That is what happens in line 2 of the code. It is the subdirectory default.realm.management that seem to be the problem or the file that is placed therein

**Comment by gapl** [comment]
@lehmberg What was the conclusion of this issue? I am facing the exact same thing.

```
Error Domain=io.realm Code=1 "open() failed: No such file or directory" UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/2471FDE1-EF41-4004-9496-6205401EC6D0/Documents/user.management/log_access, NSLocalizedDescription=open() failed: No such file or directory, Error Code=1}
```

**Comment by lehmberg** [comment]
@gapl  Have not heard anything from realm yet yet but still have the issue

**Comment by gapl** [comment]
In this case, could you please reopen the issue? Would love to get feedback on this.

**Comment by lehmberg** [comment]
It seems to make a difference where the initialisation is done. I tried moving the code changing the path of the realm file to the app delegate and now it seems to work. But initialising it another place worked in a previous version so something has surely changed

**Comment by gapl** [comment]
Well we are using several realm's where each has a different path. So we are instantiating realm objects through setting their configuration's `fileURL`.

**Comment by lehmberg** [comment]
@austinzheng Any news on this?

**Comment by austinzheng** [comment]
Sorry, I’m still looking into this. I hope to have more to share soon.

**Comment by lehmberg** [comment]
great thanks

Den 14. jun. 2016 kl. 16.47 skrev Austin Zheng <notifications@github.com<mailto:notifications@github.com>>:

Sorry, I'm still looking into this. I hope to have more to share soon.

> On Jun 14, 2016, at 6:37 AM, lehmberg <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> @austinzheng <https://github.com/austinzheng> Any news on this?
>
> -
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/realm/realm-cocoa/issues/3702#issuecomment-225882981>, or mute the thread <https://github.com/notifications/unsubscribe/ADhCjkReWtfR-qKwnB871397pdfQp_hXks5qLq6ogaJpZM4ItXlm>.
>


-

**Comment by lehmberg** [comment]
@austinzheng Do need my help to test something out. Maybe to help pin down which that broke the functionality?

Best
Alex

**Comment by austinzheng** [comment]
Sorry for dropping off the radar; last week was quite hectic for various reasons.

If you could share the code that `CTFileManager.sharedFileManager().realmPath` uses to build its path, that would be great.

**Comment by lehmberg** [comment]
Sure thing:

 private init() {
        fileManager = NSFileManager.defaultManager()
      //  var errorObject : NSError?
        documentPath = try! fileManager.URLForDirectory(NSSearchPathDirectory.DocumentDirectory, inDomain: NSSearchPathDomainMask.UserDomainMask, appropriateForURL: nil, create: true)
   
        thumbNailPath = (documentPath.path! as NSString).stringByAppendingPathComponent("/thumbnails")
        contentFilesPath = (documentPath.path! as NSString).stringByAppendingPathComponent("/contentFiles")
        personalFilesPath = (documentPath.path! as NSString).stringByAppendingPathComponent("/personalFiles")
        layoutFilesPath = (documentPath.path! as NSString).stringByAppendingPathComponent("/layoutFiles")
        realmPath = (documentPath.path! as NSString).stringByAppendingPathComponent("/Realm")
        
        createDirectoryIfNeeded(thumbNailPath)
        createDirectoryIfNeeded(realmPath)
        createDirectoryIfNeeded(contentFilesPath)
        createDirectoryIfNeeded(personalFilesPath)
        createDirectoryIfNeeded(layoutFilesPath)
    }
    
    func createDirectoryIfNeeded(directoryPath : String) {
        var errorObject : NSError?
        
        if !fileManager.fileExistsAtPath(directoryPath) {
            do {
                try fileManager.createDirectoryAtPath(directoryPath, withIntermediateDirectories: false, attributes: nil)
            } catch let error as NSError {
                errorObject = error
            }
            ProcessError("Init",errorPointer:errorObject)
            
            errorObject = nil
            do {
                let url = NSURL(fileURLWithPath: directoryPath)
                try url.setResourceValue(true, forKey: NSURLIsExcludedFromBackupKey)
            } catch let error as NSError {
                errorObject = error
            }
            self.ProcessError("Set exclude from backup",errorPointer:errorObject)
        }
    }

**Comment by austinzheng** [comment]
Thanks! I'll get back to you once I figure out exactly what's going on.

**Comment by austinzheng** [comment]
Hi @lehmberg, 

I'm building a repro case to try to track down the problem you reported. Could you let me know where you are running the setup code to set the Realm file path, and where you are running the code to retrieve an instance of a Realm? (Quick question: does the crash happen when you run the setup code, or when you use `try! Realm()` or similar to get a Realm?)

I noticed you mentioned that moving some of your setup code to the app delegate fixed the issue in your case so the point at which setup happens during the application lifecycle might be important.

Thanks, and let me know if you have any questions!

**Comment by lehmberg** [comment]
I am running the setup code when I initialise a singleton. I can easily start my app and have the setup code run and only when I start modifying a realm will it crash. I have attached a screenshot of where it traps in xcode. Something with notification system it seems.
http://screencast.com/t/XhJlDecX5x

Let me know if you have further questions

Alex

Venlig hilsen / Best regards

Alex Lehmberg
M: (+45) 31 62 47 81
E: aal@contenttap.com

ContentTap
Rosenvængets Allé 11
2100 København Ø

**Comment by austinzheng** [comment]
Hi Alex,

Thank you for your patience, and for providing so much information about the problem.

Unfortunately, I haven't been able to reproduce it myself, thus far.

Is there a chance you might be able to send over a repro case? I understand that this is quite a big thing to ask for, so I'd also be happy to send you my minimal attempted repro project if you'd be interested in taking a look and seeing if I'm doing anything differently from you.

Best,
Austin

**Comment by bogosmer** [comment]
I'm running into the same problem in an app that's "in the wild" - haven't been able to reproduce it myself, but will post it here if I find out.

**Comment by lehmberg** [comment]
I will try to make a repro case that is a bit more clear than just sending my complete project..

**Comment by lehmberg** [comment]
I will just send the complete project - I think I have narrowed it down to a specific point where it fails - It fails no matter where I have my initialization code. 
To what email should I send it? Is it ok with a wetransfer?

**Comment by bdash** [comment]
If it's something you wish to keep private, please send it to help@realm.io.

**Comment by lehmberg** [comment]
I have sent my exact project via wetransfer to help@realm.io and a mail describing how to reproduce the issue

**Comment by austinzheng** [comment]
We resolved the issue privately.

For future reference, to anyone else who might stumble upon this thread: make sure you don't delete Realm files after opening the database, including any Realm files in subdirectories. Thanks!
