### ISSUE TITLE
EXC_BAD_ACCESS on `try! Realm().objects(MyModel)`

### ISSUE THREAD

**Issue by Dschee** [realm/realm-cocoa#3709]
When creating a Realm object and fetching within one line using `try! Realm().objects(MyModel)` I get an EXC_BAD_ACCESS (code=2, address=0x100...) error. 

Here's the top of the output from lldb:
```
(lldb) bt all
Realm was compiled with optimization - stepping may behave oddly; variables may not be available.
* thread #1: tid = 0x14a0d7, 0x000000018016c8e4 libobjc.A.dylib`realizeClass(objc_class*) + 988, queue = 'com.apple.main-thread', activity = 'send control actions', stop reason = EXC_BAD_ACCESS (code=2, address=0x100132948)
    frame #0: 0x000000018016c8e4 libobjc.A.dylib`realizeClass(objc_class*) + 988
    frame #1: 0x000000018016ce90 libobjc.A.dylib`realizeAllClasses() + 88
    frame #2: 0x000000018016ed24 libobjc.A.dylib`objc_copyClassList + 40
  * frame #3: 0x0000000101511600 Realm`+[RLMSchema sharedSchema](self=RLMSchema, _cmd=<unavailable>) + 92 at RLMSchema.mm:228 [opt]
    frame #4: 0x0000000101509660 Realm`+[RLMRealm realmWithConfiguration:error:](self=RLMRealm, _cmd=<unavailable>, configuration=0x000000015d8229a0, error=domain: class name = _TtC11ProjectName18SomeViewController - code: 4296202042) + 1388 at RLMRealm.mm:367 [opt]
    frame #5: 0x000000010128b910 RealmSwift`RealmSwift.Realm.__allocating_init () throws -> RealmSwift.Realm + 120 at Realm.swift:0
```

I also checked for the Realm Swift property cheat sheet, everything seems to be fine, I follow all requirements as far as I can see. Any ideas on how to get this fixed? This started to appear after updating to Realm 1.0.0 -- I'll try going back to an older version and report.

**Comment by bdash** [comment]
Which version of Xcode are you using?

**Comment by Dschee** [comment]
I’m using Xcode 7.3 on a OS X 10.11.5 and integrated Realm-Swift via Carthage (v0.16.2).


Am 5. Juni 2016 um 19:42:20, Mark Rowe (notifications@github.com) schrieb:

Which version of Xcode are you using?

**Comment by bdash** [comment]
Can you please try updating to Xcode 7.3.1 when you have a chance and see if that changes anything?

**Comment by Dschee** [comment]
@bdash I just updated to Xcode 7.3.1 (Apple didn't show any update since I "only" had 12 GB of free space which seems not to be enough for Xcode O.o) and in my first test within the simulator it worked! Thanks for the suggestion, I'll report if this happens again but for now it seems to be solved. 👍

**Comment by blastervla** [comment]
I know this issue is closed and a solution to it was found, but I'll add my experience here just for new people who might stumble upon this.

My app was working fine, no changes made and out of nowhere it started crashing with this error. Deleting and reinstalling the app didn't fix it, but running a super clean did the trick. Be sure to try this if you have this issue or a similar one!
