### ISSUE TITLE
The executable 'Realm.framework' is not a Position Independent Executable

### ISSUE THREAD

**Issue by MihaelIsaev** [realm/realm-cocoa#3710]
Hello,

After uploading my app binary to the iTunes Connect, Apple show me warnings about PIE and the email with the following text:

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "__". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> Non-PIE Binary - The executable 'Payload/_.app/Frameworks/Realm.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable
> 
> Non-PIE Binary - The executable 'Payload/_.app/Frameworks/RealmSwift.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable
> 
> Non-PIE Binary - The executable 'Realm.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable
> 
> Non-PIE Binary - The executable 'RealmSwift.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
> 
> Regards,
> 
> The App Store team

## Version of Realm and Tooling

Realm version: 1.0.0
Xcode version: 7.3.1 build 7D1014
iOS/OSX version: 9.3.2/10.11.5 build 15F34
git version 2.7.4 (Apple Git-66)
Dependency manager + version: don't use it

Please help me to solve it.

**Comment by bdash** [comment]
Can you please share the information listed in the [Filing Issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) section of our documentation about contributing to Realm?

**Comment by MihaelIsaev** [comment]
I've just updated the issue.
Realm installed by latest instruction from realm.io as dynamic framework.
![2016-06-06_07-08-10](https://cloud.githubusercontent.com/assets/1272610/15811081/0ad0aa56-2bb6-11e6-83c5-29c82fca8b5f.png)

**Comment by jpsim** [comment]
@MihaelIsaev have you read and performed the checks explained in the technical note referenced in the iTunes Connect email you received?

From [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/qa/qa1788/_index.html):

> ## Steps for building your application as PIE
> 1. In Xcode, select your target in the "Targets" section, then click the "Build Settings" tab to view its settings.
> 2. For iOS apps, set iOS Deployment Target to iOS 4.3 or later. For Mac apps, set OS X Deployment Target to OS X 10.7 or later.
> 3. Verify that Generate Position-Dependent Code is set at its default value of NO.
> 4. Verify that Don't Create Position Independent Executables is set at its default value of NO.

**Comment by MihaelIsaev** [comment]
Sure, in my Build Settings:
> Generate Position-Dependent Code is NO
> Don't Create Position Independent Executables is NO

**Comment by jpsim** [comment]
Alright, well we can't reproduce this with the information you've provided. Could you share a project that highlights the issue?

**Comment by MihaelIsaev** [comment]
Ok, here is the project https://www.dropbox.com/s/nywys0zz8k1dpyo/AirShopCopy.zip?dl=0

And here is the result of uploading it to the iTunes Connect
![2016-06-07_15-05-30](https://cloud.githubusercontent.com/assets/1272610/15855599/5f278852-2cc1-11e6-8177-bae3794c5ad9.png)

**Comment by bdash** [comment]
People using CocoaPods have been experiencing the same warning with various frameworks so it doesn't seem like this is a Realm issue (CocoaPods/CocoaPods#5453). The CocoaPods folks appear to have determined that it's an issue with iTunes Connect's validation as the notion of a "position independent executable" is specific to executables, and is not applicable to frameworks. I'd suggest following the CocoaPods issue as they'll likely post an update when the iTunes Connect issue is addressed.

**Comment by MihaelIsaev** [comment]
The fact that this warning happens with many other frameworks is not an answer. I think the problem is in frameworks, and the warnings didn't disappear while frameworks didn't fix PIE. I use frameworks other frameworks, let's say Crashlytics, FBSDKCoreKit, and with them there is no warnings in iTunes Connect.
If Facebook and Fabric can make the frameworks with right PIE settings, maybe Realm can do it too?

**Comment by bdash** [comment]
The other frameworks in the app you shared above are static libraries, not dynamic frameworks. Static libraries are linked into your built application and so would not be subject to the check performed by iTunes Connect.

**Comment by MihaelIsaev** [comment]
I tried this solution http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/ but have no luck.

> The other frameworks in the app you shared above are static libraries, not dynamic frameworks. 

Maybe there is some instruction about building Realm framework as static library?

**Comment by bdash** [comment]
Stripping simulator architectures is already handled by the `strip-frameworks.sh` build phase that the Realm Swift installation instructions mentions. I don't see any reason to think this is related to the warning you're seeing.

Realm Swift cannot be built as a static library as Xcode does not support building static libraries containing Swift code.

As mentioned earlier, the information I've seen points to this being a more general issue with how iTunes Connect is validating dynamic frameworks, and not something specific to Realm. I understand that it is frustrating to be seeing warnings that are outside of your control, but they appear to be outside of our control as well. I'd suggest filing a Radar and/or contacting iTunes Connect support about this issue.

**Comment by MihaelIsaev** [comment]
It's good if this warning does not affect the publication to the AppStore. But I didn't check it myself, it will be clear after the publication this month. Thanks for helping)
