### ISSUE TITLE
Always use "Type.self" in documentation

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3711]
According to http://thread.gmane.org/gmane.comp.lang.swift.devel/2148, it turns out that `realm.objects(MyModel)` works due to a bug in Swift, so we should always use an explicit `.self` when referencing types in Realm APIs in our documentation.

Additionally, APIs that take more than one argument _require_ the use of `.self` (e.g. `LinkingObjects(fromType: Person.self, property: "dogs")`) so it's inconsistent to sometimes refer to types without an explicit `.self`.

**Comment by jpsim** [comment]
web docs are updated, still need to do API docs.

**Comment by bitserf** [comment]
FYI, the .self requirement may be relaxed post Swift 3.0, see https://github.com/apple/swift-evolution/blob/master/proposals/0090-remove-dot-self.md.

**Comment by jpsim** [comment]
Thanks for the heads up, though obviously we want our documentation to reflect the current state of affairs.
