### ISSUE TITLE
Realm clears models' records after app launched. 

### ISSUE THREAD

**Issue by mixdesign** [realm/realm-cocoa#3721]
I'm using v1.0.0;
I have simple model:

```
@interface KeyValue : RLMObject
@property NSString *key;
@property NSString *value;
+ (void)addValue:(NSString *)theValue forKey:(NSString *)theKey;
@end

@implementation KeyValue

+ (NSString *)primaryKey {
    return @"key";
}
+ (void)addValue:(NSString *)theValue forKey:(NSString *)theKey
{
    RLMRealm *realm = [RLMRealm defaultRealm];
    KeyValue *object = [KeyValue objectForPrimaryKey:theKey];

    if(!object) {
        object = [KeyValue new];
        object.key = theKey;
        object.value = theValue;

        [realm beginWriteTransaction];
        [realm addObject:object];
        [realm commitWriteTransaction];
    } else {
        [realm beginWriteTransaction];
        object.value = theValue;
        [realm commitWriteTransaction];
    }
}
@end
```

For simple testing, on button action I'm calling:
`[KeyValue addValue:@"kz" forKey:@"lang"];`

In Realm browser I see data I've just added. If I kill app and launch it again, data is on it's place. But, when I kill and relaunch app again, this time data is cleared. There is no script that clears the model, it just renews. Any ideas?

**Comment by jpsim** [comment]
I can't reproduce this. Here's the sample project I used to attempt to trigger the behavior you're describing: [GH3721.zip](https://github.com/realm/realm-cocoa/files/303270/GH3721.zip)

### Run 1

```
2016-06-07 11:13:53.365 GH3721[3212:259386] adding KeyValue object 'lang:kz'
2016-06-07 11:13:53.370 GH3721[3212:259386] all KeyValue objects: RLMResults <0x7fb820541c90> (
  [0] KeyValue {
    key = lang;
    value = kz;
  }
)
```

### Run 2

```
2016-06-07 11:14:40.746 GH3721[3323:262587] all KeyValue objects: RLMResults <0x7ff63a79b260> (
  [0] KeyValue {
    key = lang;
    value = kz;
  }
)
```

### Run 3

```
2016-06-07 11:14:54.288 GH3721[3346:263506] all KeyValue objects: RLMResults <0x7f9f08f61c90> (
  [0] KeyValue {
    key = lang;
    value = kz;
  }
)
```

---

Can you take a look and see what you're doing differently in your app that could cause this to happen there, but not in my sample? Maybe you forgot to share a step?

**Comment by mixdesign** [comment]
@jpsim Thank you for sharing time to help me with sample project. My fault, deep in the classes I've found the script which calls `[realm deleteAllObjects];` Sorry....

Is there a method to enable realm transactions' logging? e.g. new record created in 'KeyValue', all objects in default realm deleted .... etc.
