### ISSUE TITLE
'Realm/RLMArray.h' file not found

### ISSUE THREAD

**Issue by jleach** [realm/realm-cocoa#3723]
## Goals

I'd like to install realm-cocoa from Cocapods 1.0.1

## Expected Results

I expect to install the pod and be able to compile.

## Actual Results

'Realm/RLMArray.h' file not found

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Realm.h"
        ^
/Users/jleach/Library/Developer/Xcode/DerivedData/Rocky-dkcjsjndgvthaeflrhmhoiwhidgu/Build/Products/Debug-iphoneos/Realm/Realm.framework/Headers/Realm.h:21:9: error: 'Realm/RLMArray.h' file not found
#import <Realm/RLMArray.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Realm'
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/RealmSwift-Swift.h"
```

## Steps to Reproduce

I just run pod install.

## Code Sample

none, install issue.

## Version of Realm and Tooling

Realm version: ?

1.0

Xcode version: ?

7.3

iOS/OSX version: ?

n/a

Dependency manager + version: ?

n/a

**Comment by jpsim** [comment]
Have you tried following the troubleshooting steps listed in the [Reinstalling Via Dependency Managers](https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers) section of our docs?

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
```

**Comment by jleach** [comment]
I tried those. Turns out I also (or maybe it was the only problem) was to delete my derived data folder; normal clean was not good enough for me:

This is what worked for me:

```
  gem cleanup cocoapods
  gem uninstall cocoapods
  gem install cocoapods
  pod install
```

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
```

```
cd /Users/`whoami`/Library/Developer/Xcode/DerivedData
rm -rf YourProject-*
```

**Comment by jpsim** [comment]
Glad to hear that you fixed this after all. I'll update that troubleshooting section of our docs to recommend clearing derived data.

**Comment by haligen** [comment]
@jleach you're awesome. I had this same problem and it was driving me insane. Your process worked perfect.

**Comment by olympianoiseco** [comment]
I ran into the same issue, but while manually importing the static framework.  Cleaning the derived data seems to have worked.
