### ISSUE TITLE
Does realm encryption use apple's commoncrypto module?

### ISSUE THREAD

**Issue by asjesset** [realm/realm-cocoa#3724]
I am struggling to figure out exactly what flavor of encryption Realm supports. Can someone tell if it uses commoncrypto under the hood to encrypt/decrypt the data it writes to disk?

Thank you! Excited to use Realm.

**Comment by jpsim** [comment]
We use CommonCrypto on Apple platforms and openssl on Android. Both implementations use AES-256+SHA2.

Don't hesitate to let us know if you have any more questions!

**Comment by KoNEW** [comment]
What kind of AES mode are you using for encryption (CBC/CTR...)?

**Comment by tgoyne** [comment]
The encryption is done in 4KB blocks. Each block uses a unique counter for the IV, and CBC within the block.

**Comment by KoNEW** [comment]
Thanks!

**Comment by puneetx** [comment]
Is padding scheme PKCS#7?

**Comment by tgoyne** [comment]
The Realm file format does not require padding.
