### ISSUE TITLE
How can I do multiple sorting?

### ISSUE THREAD

**Issue by alexliubj** [realm/realm-cocoa#3728]
Hi guys, 

Can someone help?

I want to get all the isTopConversation ( actually has 0 and 1) equals 1 at the top a few then the rest for the conversation I want sorted by updatedUnixTime. Like: 

content, isTopConversation, updatedUnixTime
1. aaaa, 1, 123
2. bbbb, 1, 234
3. cccc, 0, 34343
4. dddd, 0, 34340

my current query is like this, but it seems to be that the first isTopConversation is not working.
`realm.objects(Conversation).filter(predicate).sorted("isTopConversation", ascending: false).sorted("updatedUnixTime", ascending: false)`

**Comment by bdash** [comment]
[`Results.sorted` has a second overload](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sorteduRd__s12SequenceTypeWd__9Generator7Element_zVS_14SortDescriptorrFqd__GS0_x_) that takes a sequence of `SortDescriptor`s to sort by:

```
realm.objects(Conversation).filter(predicate).sorted([SortDescriptor(property: "isTopConversation", ascending: false),
                                                      SortDescriptor(property: "updatedUnixTime", ascending: false)])
````

**Comment by alexliubj** [comment]
Nice, thanks Mark! It works,  closing issue.
