### ISSUE TITLE
readonly Realm does not track changes

### ISSUE THREAD

**Issue by arv3** [realm/realm-cocoa#3731]
I noticed that a (Swift) Realm with the readOnly flag specified in its Configuration will not track changes made in another process, which it does when opening the database read-write.
This makes sense (kind of), since the readOnly feature seems to be intended for use with databases within the application bundle that will never change. Still, this behaviour should be documented.

## Goals
I have an app with a bundled Today extension using a Realm database in a shared App Group location. The extension does not modify the database, hence I would like to open it read-only.
Why? The extension and the main app share a lot of code and I would like to minimise the chance of inadvertent changes to the database.

## Expected Results
When the widget updates, I expect previously fetched objects from the database to be up-to-date.

## Actual Results
Stale data is returned from fetched objects.
Attempts to use `realm.refresh()` produce a crash.

## Mitigation
When setting `configuration.readOnly = false`, it works as expected.

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

/Applications/Xcode.app/Contents/Developer
Xcode 7.3.1
Build version 7D1014

/usr/local/bin/pod
1.0.0
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.16.2
github "realm/realm-cocoa" "v1.0.0"

/usr/bin/git
git version 2.7.4 (Apple Git-66)
```

**Comment by tgoyne** [comment]
I could've sworn this was documented, but there appears to actually be basically zero documentation for readOnly, and certainly nothing that says you can't open a file in both read-only and read-write modes at the same time other than that it'll throw an exception if they're in the same process. That would certainly explain why people haven't been aware of that in the past!
