### ISSUE TITLE
Proper way of doing a migration where you add properties

### ISSUE THREAD

**Issue by erkro1** [realm/realm-cocoa#3734]
## Goals

What do you want to achieve?

I have added some properties to an RLMObject so I need to migrate it, but I can't find anywhere what the correct way is.

## Expected Results

What did you expected to happen?

That it adds the properties.

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

It either gives me a code warning in the migration code or crash. (see Code Sample)

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

    if (oldSchemaVersion < 5) { //we're migrating from version 4
        [migration enumerateObjects: Client.className block: ^ (RLMObject * oldObject, RLMObject * newObject) {
            newObject[@ "idCheck"];
            newObject[@ "idExpiration"];
            newObject[@ "idNumber"];
        }];
    }

The code above works perfectly but it gives me a warning about how the Container access result is unused and it doesn't allow me to set the default values.

    if (oldSchemaVersion < 5) { //we're migrating from version 4
        [migration enumerateObjects: Client.className block: ^ (RLMObject * oldObject, RLMObject * newObject) {
            newObject[@ "idCheck"] = false;
            newObject[@ "idExpiration"] = @ "";
            newObject[@ "idNumber"] = @ "";
        }];
    }

But this code results in the following crash when I try to set an object value 
'RLMException', reason: 'Invalid property value `(null)` for property `idCheck` of class `Client`'

## Version of Realm and Tooling

Realm version: 0.103.2

Xcode version: 7.3.1

**Comment by tgoyne** [comment]
`newObject[@ "idCheck"] = false;` needs to be `newObject[@"idCheck"] = @NO;`. Obj-c container subscripting takes/returns `id`, and `false` implicitly converts to `nil` when cast to `id` rather than a false NSNumber.

Note also that non-optional `bool` properties will default to `false` and non-optional `NSString` properties default to the empty string, so you don't need to explicitly set them to that in the migration block.

**Comment by erkro1** [comment]
@tgoyne The boolean trick worked, thanks!

So you're saying everyone migrates this way and has tons of warnings in their migration file because of unused variables?

**Comment by tgoyne** [comment]
No, there should not be any warnings from your migration. There is no need to read each of the properties added.

**Comment by erkro1** [comment]
I get an warning because for each new property I use 'newObject['PropertyName']' or else it would crash like I said.

**Comment by stel** [comment]
Realm will automatically detect new properties and removed properties, so there is no need to specify it in migration code, see docs [here](https://realm.io/docs/objc/latest/#defining-migrations).

What crash message you see?

**Comment by erkro1** [comment]
I get an error about fields that are added and that I should do a migration.

**Comment by stel** [comment]
> At the very minimum all we need to do is to update the version with an empty block to indicate that the schema has been upgraded (automatically) by Realm.

Did you update the version?

Could you please provide the exact message?

**Comment by erkro1** [comment]
Empty migration blocks do seem to work and don't display any warnings, which was what I wanted.
So the issue is resolved, thanks.
