### ISSUE TITLE
Translation error in Chinese document, Section Models, paragraph 4

### ISSUE THREAD

**Issue by likers** [realm/realm-cocoa#3738]
## Issue

The **Models** section, paragraph 4 of RealmSwift's Chinese version document is not accurate nor easy understood. I believe this new translation will make it better.

### English:
> Since Realm parses all models defined in your code at launch, they must all be valid, even if they are never used.

### Chinese:
> ***由于在代码启动时 Realm 所有模型就需要被定义好***，所以即使代码中没有调用，它们都需要被初始化。

According to English document, the Realm models are defined before code launching, and Realm will parse them at launch. While the Chinese translate mislead it to something like "All the models must be defined at launch." which lost the key word *parse* and cause misunderstanding. What's more, the syntax is also not right.

##### 由于Realm中定义的所有模型在程序启动时就会被解析，

**Comment by jpsim** [comment]
thanks for the suggestion @likers! I've made the change and it's now pending review from the person who maintains the Chinese version of our docs.
