### ISSUE TITLE
Use of unresolved identifier 'linkingObjects'

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [realm/realm-cocoa#3739]
I tried adding Realm v1.0 to my Swift projects when I came across this.

## Goals

Add Realm v1.0 to my Swift project.

## Expected Results
Successful add Realm to the Swift project. 

## Actual Results
Got this build error.
>  Use of unresolved identifier 'linkingObjects'

## Steps to Reproduce

1. Create brand new Swift project.
2. Set the Deployment Target to iOS 8.
3. Initialize CocoaPods for the project. Below is my `Podfile`.
```
platform :ios, '8.0'

target 'RealmTestDrive' do
  use_frameworks!

  pod 'RealmSwift', '~> 1.0'

end
```
4. Run `pod install`. I have CocoaPods v1.0.1 installed on my Mac.
5. Build the project after successful CocoaPods installation.

## Code Sample

This is the model class where the error is present. I've attached a demo Xcode project below.
```swift
import Foundation
import RealmSwift

class Service: Object {
    
    dynamic var id: Int = 0
    dynamic var title: String = ""
    dynamic var desc: String = ""
    dynamic var price: Float = 0
    dynamic var windowStyle: WindowStyle?
    
    var parts: [Part] {
        return linkingObjects(Part.self, forProperty: "services") // This is the error line
    }
    
    override static func primaryKey() -> String? {
        return "id"
    }
    
    override var description: String {
        return title
    }
}
```

[https://www.dropbox.com/s/c85bkhc446780tz/RealmTestDrive.zip?dl=0](https://www.dropbox.com/s/c85bkhc446780tz/RealmTestDrive.zip?dl=0)

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

/Applications/Xcode.app/Contents/Developer
Xcode 7.3
Build version 7D175

/usr/local/bin/pod
1.0.1
Realm (1.0.0)
RealmSwift (1.0.0)
RealmSwift (~> 1.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.16.2
(not in use here)

/usr/bin/git
git version 2.6.4 (Apple Git-63)
```

I tried deleting Derived Data folder, cleaning and building, the whole nine yards several times. I even uninstalled all versions of CocoaPods I had in my machine plus deleted the ~/.cocoapods directory and reinstalled CocoaPods anew. Tried [this](https://github.com/realm/realm-cocoa/issues/2969#issuecomment-163401043) many times too. But nothing worked.

**Comment by jamikado** [comment]
Read the 1.0 release notes. linkingObjects has changed in 1.0
https://realm.io/docs/swift/latest/#inverse-relationships

Replace:
var parts: [Part] {
        return linkingObjects(Part.self, forProperty: "services")
 }

with:
let parts = LinkingObjects(fromType: Part.self, property: "services")

**Comment by ilendemli** [comment]
I am going to hop in here.
I too have updated to Realm 1.0.1 and changed the lines where i had to with the new code (see post above by @jamikado).
Unfortunately I now get an empty list where I got some result with the Realm version I used before.
Nothing else was changed. Is this known?

**Comment by jpsim** [comment]
@ilendemli glad you worked it out, and sorry for the confusion. Realm models should be defined exactly as the documentation describes: https://realm.io/docs/swift/latest/#models

We hope to see further improvements to Swift's reflection mechanism that would allow us to be more flexible with how users define models. If you agree, please file a radar or a Swift bug and we'll be happy to dupe or 👍.

I'll be closing this issue since it seems everyone who's chimed in has since been able to adapt their models to conform to the necessary syntax.
