### ISSUE TITLE
Realm Swift - How to union queries and group by from multiple models?

### ISSUE THREAD

**Issue by Tom29** [realm/realm-cocoa#3740]
I want to query data from multiple models and group it and order it. How do i do it with Realm?

In the SQLite / MySQL, i can use UNION to combine the queries and GROUP BY to group common field's value.

Im switching to Realm and now i'm stucking in how to perform it.

Here is an example about the query in SQLite
```
SELECT next_word, SUM(frequency) AS frequency FROM (
SELECT word2 AS next_word, freq * 2 AS frequency FROM ngram2 WHERE word1 ='love' UNION 
SELECT word3 AS next_word, freq * 5 AS frequency FROM ngram3 WHERE word1='you' AND word2='so' UNION 
SELECT word4 AS next_word, freq * 30 AS frequency FROM ngram4 WHERE word1 ='love' AND word2='you' AND word3='so' ) next_words GROUP BY next_word ORDER BY SUM(frequency) DESC LIMIT 0,3
```

**Comment by stel** [comment]
Realm doesn't support `UNION` at this time. See [Queries docs`](https://realm.io/docs/swift/latest/#queries) for available API.

As a workaround you can query models in separate queries and then combine it in a way you need.

**Comment by jpsim** [comment]
Wouldn't this be mostly possible with OR'd predicates?
