### ISSUE TITLE
This is not a valid Dash or Xcode docset feed. Realm Objective-C v1.0.1

### ISSUE THREAD

**Issue by jaybowong** [realm/realm-cocoa#3741]
I clicked the __Install in Dash__ button at the top on this site https://realm.io/docs/objc/latest/api/.
My Dash version is 2.2.4.

![this-is-not-a-valid-dash-or-xcode-docset-feed](https://cloud.githubusercontent.com/assets/1948533/15998951/d518bf38-3174-11e6-9907-008b6eb9aeeb.png)

**Comment by jpsim** [comment]
This should be fixed. We had a website bug that caused this for about 24 hours yesterday to this morning.

**Comment by atstockland** [comment]
happening again....with https://github.com/Kapeli/feeds/blob/master/Bootstrap_4.xml
