### ISSUE TITLE
What's proper way to do sorting by function?

### ISSUE THREAD

**Issue by Tom29** [realm/realm-cocoa#3743]
I want to do sorting by function like SQLite.
`SELECT field1,field2 FROM table ORDER BY abc(var,field1)`

I've tried with `.sort` but its 10 times slower than SQLite.

```
.sort({a,b in
                        Compare(pam,first: a.str1,second: b.str1)
                    })
func Compare(pam:String,first:String,second:String)->Bool {
        print("\(pam) \(first) \(second)")
        return abc(first) < abc(second)
    }
```

I see the log and i see it compares every single record to each other to find out what's the biggest. This is why it's too slow.

**Comment by stel** [comment]
`print` may dramatically decrease performance, did you try to remove it?

**Comment by Tom29** [comment]
@stel I've test with print for both sqlite and realm. And i realize that realm compare every single record to the whole matched result. SQLite doesn't. It prints the results only 1/10 compare to the Realm. In the SQLite, it has property called `deterministic` https://www.sqlite.org/c3ref/create_function.html 

> SQLITE_DETERMINISTIC to signal that the function will always return the same result given the same inputs within a single SQL statement

Realm doesn't have this so i think thats why i calculate every single record in the sorting result.

**Comment by stel** [comment]
`sort(_:)` in this case is `SequenceType`'s method (see more info in [Apple's docs](https://developer.apple.com/library/watchos/documentation/Swift/Reference/Swift_SequenceType_Protocol/index.html#//apple_ref/swift/intfm/SequenceType/s:FEsPs12SequenceType4sortFFTWx9Generator7Element_WxS0_S1___SbGSaWxS0_S1___)).

Realm `Results` has [some build in sorting methods](https://realm.io/docs/swift/1.0.1/api/Classes/Results.html#/Sorting), but it allows you to sort only by properties.

Also Realm `Results` is a `CollectionType`, so you can implement your own sorting methods.

**Comment by mrackwitz** [comment]
Jumping in here: If you're leveraging Realm's builtin sorting methods, then you will see huge performance benefits, because it can use the internal sorting logic and doesn't need to pull the objects into memory to compare them with each other. That happens though, if you're sorting with the methods given via `CollectionType`.
There are limitations to that though: You can only sort by direct properties on objects. You can't use keypaths as seen in #1277. A possible workaround for now might be to precompute the function results and persist them.

**Comment by jpsim** [comment]
Hopefully Realm's built-in sorting support is enough for your needs @Tom29. If not, please keep an eye on #1277 and #1265 for improvements in this space.
