### ISSUE TITLE
Fix issue with Swift 3 and `RLMSupport.swift`

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#3746]
Right now, the `RLMSupport.swift` extensions to the Objective-C Realm collection types to enable `Sequence` conformance are disabled, because not disabling them causes the compiler to assert. Get the Swift compiler fixed, then fix this (or work around it).

**Comment by austinzheng** [comment]
I filed https://bugs.swift.org/browse/SR-1779 against the Swift compiler.

**Comment by austinzheng** [comment]
Slava Pestov says:

> Yeah, I think this is the issue where allocating constructors cannot be called from an extension of an Obj-C generic class.

**Comment by liuxuan30** [comment]
any solution?

**Comment by bdash** [comment]
No. We're still blocked on the Swift compiler bug AFAIK.

**Comment by liuxuan30** [comment]
Jesus, it's beta 4 now and is not solved yet...

**Comment by bdash** [comment]
I'd encourage you to file a [bug report with Apple](https://bugreport.apple.com/) about the problem if you've not done so already and it's affecting you. That'll help increase the visibility of the issue.

**Comment by liuxuan30** [comment]
@bdash consider it's done

**Comment by romainfrancez** [comment]
Do we have any update on that issue? Cheers

**Comment by jpsim** [comment]
@romainfrancez we're blocked on [SR-1779](https://bugs.swift.org/browse/SR-1779).
