### ISSUE TITLE
Disambiguation of `Array` and `List` in Realm Swift docs

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3753]
The current [documentation](https://realm.io/docs/swift/latest/) sometimes uses the word `Array` to refer to `Swift.Array` and other times to refer to `RealmSwift.List`. Here's a particularly bad example:
> `Array`s have an interface very similar to `Array` and objects contained in a `Array` can be accessed using indexed subscripting. Unlike `Array`s, `Array`s only hold `Object`s of a single subclass type. For more details see `List`.

This phrasing is used throughout the document. I find it especially confusing when we write "Array" in a monospace font but neglect to give "List" the same treatment, such as here:
> Instead, you can simply call the modification methods on `Array` directly, and anyone observing the property it is stored in will be notified. List properties do not need to be marked as dynamic to be observable, unlike normal properties.

I suggest we replace many of these occurrences of `Array` with `List`. If we really do want to refer to a `List` as an array, I suggest we use the lowercase, non-monospaced version of the word. Thoughts?

FYI, the Realm Objective-C documentation does not suffer this same issue as we consistently disambiguate between `RLMArray` and `NSArray`.

**Comment by tgoyne** [comment]
This looks like an error when the terms helper was ported to the new site. https://github.com/realm/realm.io-middleman/blob/master/helpers/cocoa_terms_helper.rb defines the Swift version of RLMArray as Array when it should be List.

**Comment by JadenGeller** [comment]
Fixed by #822
