### ISSUE TITLE
Feature Request: Serial queue access to Realm

### ISSUE THREAD

**Issue by danielrhodes** [realm/realm-cocoa#3755]
From reading issues and help forums, it seems that (as always with DBs) threading continues to be a big problem for Realm users, especially in regards to GCD.

For many people, these ACID type guarantees are totally overkill. On an iOS app that is using Realm as a persistent and queryable cache (I would suspect a large subset of your users), it very rarely matters if one thread overwrites the changes from another thread as most things are about shuffling data from the network to cache and from the cache to the UI.

What would be ideal is if there was an option to have a serial queue to the DB like you see with something like Redis. That would solve this threading madness and give me enough consistency guarantees without the headache. Since the DB is not busy, I am unlikely to see any performance hit.

**Comment by jpsim** [comment]
I'm really not sure what problem you're aiming to solve. What madness about threading are you referring to that would be solved by serial access?

First, I encourage you to read our docs on [threading](https://realm.io/docs/swift/latest/#threading) and this [threading deep dive article](https://realm.io/news/threading-deep-dive/) if you haven't already.

Write access is already serial, reads are concurrent (we wouldn't want to block the UI thread after all 😬).

To make all reads serialized would mean that any background thread reading would block the main thread, blocking your app's UI.

I'd love to hear more about the symptoms of the problem you're seeing in more detail, to see how we can address them. Thanks for taking the time to share your thoughts!

**Comment by danielrhodes** [comment]
That blog post was a great write up. Thanks! 

I'm aware of the consequences of putting things on a serial queue and removing consistency guarantees. 

The perspective I am coming from is probably like a lot of your users: using a database running on a different process than the client in a server environment. So admittedly I am projecting that perspective onto how Realm works or would ideally work for me.

I guess what I am looking for is not a persisted object graph, but for Realm to behave like a traditional database and when I do a query to get a result set, I get a copy of the objects. Thus I can pass around the objects to different threads. Obviously this would require that if I wish to make modifications to the object, I must explicitly do a write, and risk overwriting changes made elsewhere. From what I gather this would be less performant on the query side, but would also enable me to do everything in the background and pass the results to the main thread.

Right now, it seems unusually tedious to code around these threads (although the notifications help quite a bit), and I'm not sure that I need the benefits it gives me (namely the live updating objects and strong consistency).

Having said all that, I really like a number of things about Realm! Good work so far.

**Comment by JadenGeller** [comment]
Would a `detachedCopy()` function on `Object` suit your needs?

**Comment by danielrhodes** [comment]
@JadenGeller Yeah that would probably do the trick.

**Comment by jpsim** [comment]
Materializing a Realm object graph into memory, detaching the entire graph from the database, is at most a workaround for some limitations. The memory overhead of doing this is potentially large, plus you lose essentially all of Realm's features in doing so (live objects, consistency, queries, interprocess/interthread data sharing, notifications, persistence, etc).

There are a few solutions to this:

### 1. Async transactions (#3136)

Explicitly scoping the data available on a new thread or queue gives a large amount of flexibility regarding doing things across multiple threads, with reduced risk of object graphs at different database versions of interacting.

### 2. Version pinning (untracked)

Having the ability to pin or freeze a Realm at a given version, producing immutable Realm objects and other accessors that aren't thread-confined would solve other types of situations. However, this is at greater risk of having users forget which accessor is at which version and attempt to make mismatched accessors interact.

---

It's worth saying that both these approaches are mostly supported in Realm's core, but that coming up with a viable higher-level API without high risk of misuse is challenging.

We also have a more general issue open where we're discussing some of these topics in #1097.

I'll be closing this issue to keep the conversation localized in #1097, but we should definitely continue exploring this.
