### ISSUE TITLE
Unable to parse the format string "word = 'What's'"

### ISSUE THREAD

**Issue by codesourse** [realm/realm-cocoa#3757]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by stel** [comment]
@codesourse please, provide more info by following the guidelines for new issues.

**Comment by codesourse** [comment]
realm 0.98.6 
 xcode 7.3.x
 ios 9.2.x

  RLMResults *newResult =[C_WordTranslationModel objectsInRealm:realm where:[NSString stringWithFormat:@"word = '%@'",wordString]];

**Comment by stel** [comment]
Try to use `NSPredicate` instead:

    RLMResults *newResult =[C_WordTranslationModel objectsInRealm:realm withPredicate:[NSPredicate predicateWithFormat:@"word = %@", wordString]];

Avoid using `stringWithFormat:` while building predicates, 'NSPredicate` parses string in a different way.

Let us know if it helps.

**Comment by codesourse** [comment]
I use this solve it;
RLMResults *newResult =[C_WordTranslationModel objectsInRealm:realm where:[NSString stringWithFormat:@"word =\"%@\"",wordString]];

**Comment by stel** [comment]
Using `stringWithFormat:` is not safe for building predicates, anyway I'm happy that you resolved your problem.

**Comment by StackHelp** [comment]
@stel some same problem here

This is the way I am using a filter with the realm

       `realm.objects(Recipe.self).filter(finalQuery).sorted(byKeyPath: "name")`

and this is some final queries I am using to put in that final query that crashed on some occasion

      type = 'lunch'
      type = 'lunch' AND skill_level = 'advanced'
      skill_level = 'advanced'
      skill_level = 'intermediate'
      skill_level = 'beginner'
      type = 'breakfast' AND skill_level = 'beginner'
      type = 'breakfast'
