### ISSUE TITLE
Issue installing RealmSwift

### ISSUE THREAD

**Issue by afriedman94** [realm/realm-cocoa#3758]
## Goals

Install pod 'RealmSwift'

## Actual Results

The file in the pods folder "RealmSwift" is empty. Pods/Pods/RealmSwift
Pods/Pods/Realm seems to have installed properly. 

## Steps to Reproduce

Not too sure what I did different from any other install. I am taking over a project mid-way. The only issue I am seeing is that the file is not being installed. There are no installtion errors or warning when the pods project has completed and integrated. 

```
## Code Sample
platform :ios, '8.0'
use_frameworks!

def shared_pods
    pod 'RealmSwift'
end

target 'BevBucks' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKCoreKit'
	pod 'Firebase/Core'
	pod 'Alamofire', '~> 3.4'
end

target 'BevBucksTests' do
    shared_pods
end

target 'BevBucksUITests' do
    shared_pods
end

```

## Version of Realm and Tooling

Realm version: Newest

Xcode version: 7.3.1

iOS/OSX version: 9

Dependency manager + version: ?

**Comment by afriedman94** [comment]
I rewrote my podfile to: 

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
    pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git'
end

target 'BevBucks' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKCoreKit'
	pod 'Firebase/Core'
	pod 'Alamofire', '~> 3.4'
	shared_pods
end

target 'BevBucksTests' do

end

target 'BevBucksUITests' do
    shared_pods
end
```

and now the RealmSwift pod folder seems to be installing properly. However, when I build I now get this error
"impl/collection_change_builder.hpp" file not found

**Comment by austinzheng** [comment]
Hi @afriedman94,

It looks like you're still having issues. It shouldn't be necessary to specify the `:git =>` option in CocoaPods.

Would you be willing to share the version of CocoaPods you're using? You can check this using the command `pod --version`.

We have a couple of CocoaPods-related troubleshooting tips in our [documentation](https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers). In particular, you should try cleaning your build folder, and resetting your project's CocoaPods state and caches using the Terminal commands given.

Hope this helps; if you have any questions please do let us know, either in this ticket or by opening a new issue. Thanks!

**Comment by afriedman94** [comment]
Thanks for the tip. I am using cocoapods version 0.39.0.
I switched to carthage for now but this is something I will have to address in the future most likely. Ill take a look into the troubleshooting tips.

**Comment by austinzheng** [comment]
Excellent. If Carthage is working for you then we're all set.

If you switch back to CocoaPods in the future and run into issues getting the pod to work, feel free to open a new issue.

**Comment by xuanzi23** [comment]
@afriedman94 hey, u using the alamofire and realm together?

**Comment by afriedman94** [comment]
@xuanzi23 yes, why?

**Comment by xuanzi23** [comment]
@afriedman94 I have few question to ask you about the alamofire and realm work together, May I?

**Comment by afriedman94** [comment]
@xuanzi23 sure, this is not really the right place though. Do you use slack? my email is andrew.friedman94@gmail.com

**Comment by xuanzi23** [comment]
@afriedman94 invited u. my email is lawlierxuanzi@gmail.com

**Comment by talisk** [comment]
I met the same problem and I find the reason. @afriedman94 

Solution:
1. Open terminal and run `pod cache list`.
2. Find Realm and RealmSwift.
3. Run `pod cache clean Realm` if you find Realm in step 2, then clean the RealmSwift in the same way.
4. Run `pod install` in the project path.

**Comment by donaldking** [comment]
Facing the same issue now... Any way to fix this?

**Comment by bdash** [comment]
@donaldking, please file a new bug report and provide the information outlined in the [Filing Issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) section of the documentation on contributing so we can help you.

**Comment by talisk** [comment]
@donaldking According to my solution, can you fix your problem?

**Comment by donaldking** [comment]
@bdash @talisk Yes this solves the issue for me. Thanks! :)
