### ISSUE TITLE
Merge Realm Swift source files

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3759]
We currently support multiple Swift versions by having a copy of the root `RealmSwift` directory for each supported Swift version (e.g. `RealmSwift-swift3.0`) and at build time, run an Xcode script build phase to detect the Swift version in use for that project and establish a symbolic link from `RealmSwift` to the version-appropriate directory. This is _very_ hacky and now that Swift supports [compile-time version checks](https://github.com/apple/swift-evolution/blob/master/proposals/0020-if-swift-version.md), we have a "better way".

Issues with the current approach:

* We flatten the directories when installing via CocoaPods based on the `xcode-select`'d Xcode version, so changing Xcode versions after installing doesn't update the Swift version used.
* Xcode doesn't handle symlinks well: compiler diagnostics (including SwiftLint violations) don't render in the source files because the real path is different than what Xcode points to.
* It adds significant complexity to the project & build system:
  * Xcode build phases in a few places
  * CocoaPods link flattening step
  * `build.sh set-swift-version`
  * `scripts/swift-version.sh`
  * modifying git indexes to avoid committing symlink changes
* Minor point: not scalable to non-Xcode build systems in the future (e.g. SwiftPM)

---

Solution: concatenate the Swift 2.2 & Swift 3.0 files with a single giant `#if swift(<3.0) ... #else ... #endif` in each file. For some files it may be appropriate to share more code.

---

Potential reasons not to do this:

* We should investigate if combining the files causes Xcode to be (more) sluggish
* ???

**Comment by austinzheng** [comment]
Hmm...unlike with the other checks, it appears that inactive code is not actually parsed:

```
Like other build configurations, #if swift isn't line-based - it encloses whole statements or declarations. However, unlike the others, the compiler won't parse inactive branches guarded by #if swift or emit lex diagnostics, so syntactic differences for other Swift versions can be in the same file.
```

**Comment by jpsim** [comment]
@austinzheng fantastic, that's great (unless I'm missing something)
