### ISSUE TITLE
Realm query takes long with many objects

### ISSUE THREAD

**Issue by emuye** [realm/realm-cocoa#3761]
## Goals

I'm seeing performance that seems quite slow querying for messages. I'd like to understand if this performance is expected, and if not, what I can do to better debug and fix the slowness.

## Expected Results

Query to return quickly even with relatively large numbers of objects in the database.

## Actual Results

This query seems fast with < 1000 messages and threads in the database. But, as the number of messages and threads grows, the query time noticeably increases (quite rapidly). The query takes around 3 seconds with ~15000 messages and ~15000 threads in the database.

## Code Sample
Query:

```swift
realm.objectForPrimaryKey(ThreadModel.self, key: threadId)?.messages.filter("ANY labels.id != \"TRASH\"").sorted("dateSent", ascending: true)
```

Object Models -- FYI I'm leaving out a lot of the properties and trying to include only what seems relevent:

```swift
class ThreadModel: Object {
     override static func primaryKey() -> String? {
        return "id"
    }
    
    override static func indexedProperties() -> [String] {
        return ["id"]
    }

    dynamic var id = ""
    var messages = List<MessageModel>()
}

class MessageModel: Object {
    override static func primaryKey() -> String? {
        return "id"
    }
    override static func indexedProperties() -> [String] {
        return ["dateSent"]
    }

    dynamic var id = ""
    dynamic var dateSent: NSDate? = nil
    var labels = List<LabelModel>()
    
    var thread: ThreadModel? { return threads.first }
    private let threads = LinkingObjects(fromType: ThreadModel.self, property: "messages")
}

class LabelModel: Object {
    dynamic var name: String?
    dynamic var id = ""
    dynamic var isSystem = false
    
    override static func primaryKey() -> String? {
        return "id"
    }
    
    override static func indexedProperties() -> [String] {
        return ["id"]
    }
}
```

Measure (from a view controller):

```swift
let start = NSDate()
self.notificationToken = self.messages.addNotificationBlock { [weak self] (changes: RealmCollectionChange) in
     guard let _ = self?.tableView else { return }
     DDLogDebug("Realm message lookup took: \(NSDate().timeIntervalSinceDate(start))")
      self?.handleRealmNotificationChanges(changes)
}
```
## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: Swift 1.0.1

Xcode version: ? 7.3.1

iOS/OSX version: ? iOS 9.3.2

Dependency manager + version: ? Cocoapods 1.0.1

**Comment by tgoyne** [comment]
It is probably spending most of its time sorting, as that inherently scales poorly. You can test if this is the case by comparing the runtime of the same query without the sort. If that is the problem, there aren't any great solutions. If you're only ever displaying the messages in a single order you could keep that List pre-sorted (or if there's a very small number of orders, you could store a different sorted Lists with the same objects in it for each order).

If it's that slow even without the sort, then you're probably hitting a case which the query engine handles poorly, which we should then fix.

**Comment by emuye** [comment]
The query is much faster without the sort. I'm trying to sort this list of messages by date. Currently there is only one sort although there could eventually be others. 

It makes sense that this would scale poorly, but 3 seconds to sort 15,000 items seems very very slow. Also, while there are 15,000 total messages, I'm showing results for a single thread. This is usually around 1-5 messages. Shouldn't the sort be limited to the messages that have the matching threadId? In this case, isn't it really ~3 seconds to sort 1-5 messages?

**Comment by tgoyne** [comment]
Yes, if it's only matching a few items and sorting is taking a few seconds then something is definitely going wrong. Will need to look into that.

**Comment by jpsim** [comment]
@emuye could you please share a sample project with us, along with the steps you're taking to benchmark this? It'll greatly help us make sure we're looking at the right thing.

**Comment by emuye** [comment]
Actually, I just looked into this a little more and it doesn't matter whether there is a sort or not. When I tested the query without a sort, I had completely synced all of the messages from gmail. So, there was considerably less background processing (and writes to realm).

Here's the setup: 
1. I have a view controller with two result notification listeners (listening on Thread objects). This view controller shows a table where each row corresponds to a thread. I am syncing new threads and messages in the background, so there are many realm notification changes to the collection.

2. When a thread is selected, I push a new view controller with a result notification listener for the messages of this thread (sorted by date). This is usually on a few objects.

3. When the .Initial notification occurs I log the time difference from adding the notification block until. This is ~3 seconds with about 15,000 messages and threads.

If I remove the notification listeners from the first view controller, or stop the realm writes from occurring in the background the message query returns very quickly.

I've tried pausing the debugger while the message query is taking long and often there is a thread that appears to be handling managing the notification changes for the Thread objects (backtrace attached)
[realm_backtrace.txt](https://github.com/realm/realm-cocoa/files/324210/realm_backtrace.txt)

. This is usually the only realm thread running (besides the syncing).

It seems like listening to collection changes on a large collection is somehow causing the query slowdown.

**Comment by jpsim** [comment]
@emuye thanks for the extra info, just following up on my previous request for a sample project. Thanks!

**Comment by emuye** [comment]
What's the best way to give you access to the repository that has this issue? I believe the problem is occurring when lots of changes are being made to a somewhat complex object graph with active notification listeners. So, I don't think I can isolate this outside of our codebase.

**Comment by jpsim** [comment]
If it's a repository on GitHub, you could give access to my account: @jpsim. Or you could email a zip archive of the codebase to help@realm.io

**Comment by emuye** [comment]
Ok, you should have access on GitHub.

**Comment by jpsim** [comment]
We're continuing the conversation via email since the issues reported are specific to @emuye's application. I'll update this issue with whatever information may have more general implications once we know more.

**Comment by RetVal** [comment]
Any update? Using 3.7.3 is still slow the query even the callback when observing lots of objects.

**Comment by vishct** [comment]
Any update on this issue? I am also facing similar issue with a similar app where the number of messages are around ~2000.

**Comment by nirinchev** [comment]
This issue has been closed for more than two years because the problems were specific to that user's codebase. It's unlikely that you have hit a similar case, and even if you have, please file a new issue with details that pertain to your own application.
