### ISSUE TITLE
NSPredicate Issue - Realm logging tracebacks

### ISSUE THREAD

**Issue by modLX4** [realm/realm-cocoa#3765]
Model Object  - People
```objc
@property NSNumber<RLMBool>* isDeleted;
@property NSNumber<RLMInt>* profileID;
@property NSNumber<RLMInt>* eventID;

//A search query is run on People model
NSNumber  * serchEventID =     [NSNumber numberWithInteger:40];
NSNumber  * serchProfileID =     [NSNumber numberWithInteger:40];

RLMResults * results =  [ModelPeople objectsWithPredicate:[NSPredicate predicateWithFormat:[NSString stringWithFormat:@"eventID == %@ AND profileID == %@", serchEventID, serchProfileID]]]
```

The code Logs the following:

```
Traceback (most recent call last):
  File "/Users/febinbabu/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/febinbabu/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/febinbabu/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by stel** [comment]
@modLX4 what version of Realm/Xcode you use?

Your model properties should be defined like this:

```
@property NSNumber<RLMBool>* isDeleted;
@property NSNumber<RLMInt>* profileID;
@property NSNumber<RLMInt>* eventID;
```

> Because Realm uses different storage formats for different types of numbers, the property must be tagged with one of RLMInt, RLMFloat, RLMDouble, or RLMBool. All values assigned to the property will be converted to the specified type.

See more at https://realm.io/docs/objc/latest/#optional-properties.

And also there is no need to use `stringWithFormat:` for building `NSPredicate`, you can just use `[NSPredicate predicateWithFormat:@"eventID == %@ AND profileID == %@", serchEventID, serchProfileID]`.

**Comment by modLX4** [comment]
**Models are defined exactly like you've mentioned :**

@property NSNumber<RLMBool>* isDeleted;
@property NSNumber<RLMInt>* profileID;
@property NSNumber<RLMInt>* eventID;

**query we ran**

NSNumber * serchEventID = [NSNumber numberWithInteger:40];
NSNumber * serchProfileID = [NSNumber numberWithInteger:40];

   RLMResults * queryDelegateObject = [ModelEventDelegate objectsWhere:@"profileID == %@ AND eventID == %@", serchProfileID, serchProfileID];
                

**The above operation logs ::**


Traceback (most recent call last):
  File "/Users/febinbabu/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/febinbabu/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/febinbabu/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
    return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by modLX4** [comment]
Xcode Version : Version 7.3.1 (7D1014)
Realm Version :  Realm, 1.0.1

**Comment by tgoyne** [comment]
Try replacing rlm_lldb.py with the latest one from https://raw.githubusercontent.com/realm/realm-cocoa/master/plugin/rlm_lldb.py. We recently updated it to fix some issues with recent versions of Realm.

**Comment by modLX4** [comment]
Will do that

**Comment by jpsim** [comment]
thanks @modLX4, keep us posted!

**Comment by jpsim** [comment]
@modLX4 I'm assuming this worked for you? Closing this issue now.
