### ISSUE TITLE
 Include of non-modular header inside framework module 'Realm'

### ISSUE THREAD

**Issue by vimalprakashts** [realm/realm-cocoa#3770]
## Goals

Need to integrate Ream to my project. First time using realm . used cocopod and manual installation steps 

## Expected Results

Fail to add to my project , 

## Actual Results

..../Pods/Realm/include/Realm/Realm.h:26:9: Include of non-modular header inside framework module 'Realm'

## Steps to Reproduce

Install vai pod. and create model . and try to use it

## Code Sample

just using your dog code example

## Version of Realm and Tooling

Realm version: ?

tryed 1.0.1. and 1.0.0. both fails

Xcode version: ?

Version 7.2.1 (7C1002)

iOS/OSX version: ?

OSX 10.11.5 (15F34).

Dependency manager + version: ?

**Comment by quver** [comment]
Could you share your `Podfile`

**Comment by vimalprakashts** [comment]
Here is my pod file

```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'projectname' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'iCarousel', '1.8.2'
pod 'ReachabilitySwift', '2.3.3'
pod 'AFNetworking', '3.1.0'
pod 'FontAwesome.swift' , '0.7.3'
pod 'IQKeyboardManagerSwift', '4.0.0'
#pod 'MBProgressHUD', '0.9.2'
pod 'ObjectMapper', '1.1.0'
pod 'DrawerController', '1.1.0'
pod 'SCLAlertView', '0.5.0'
pod 'AlecrimCoreData', '4.1.1'
pod 'GoogleMaps', '1.13.2'
pod 'Cosmos', '1.2.3'


end

target 'projectnameTests' do

end

target 'projectnameUITests' do

end
```

**Comment by quver** [comment]
When I tried to reproduce this, I get 
```
[!] Unable to satisfy the following requirements:
- `SCLAlertView (= 0.5.0)` required by `Podfile`
```
so I removed this line

In empty project I put this line
```
class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        let dog = Dog()
        dog.name = "Rex"
        dog.age = 1
        
        let realm = try! Realm()
        try! realm.write {
            realm.add(dog)
        }   
        print(realm.objects(Dog))
    }
}

class Dog: Object {
    dynamic var name = ""
    dynamic var age = 0
}
```
Project built correctly and put some output to debug console
```
Results<Dog> (
	[0] Dog {
		name = Rex;
		age = 1;
	}
)
```

Try to remove derived data and restart Xcode - it doesn't sound like the solution, but many times helps.

**Comment by jpsim** [comment]
@vimalprakashts please let us know if @quver's advice helps.

Generally this kind of issue can surface when Xcode or CocoaPods has a stale cache, which requires those caches to be cleared. We have instructions in our docs covering how to handle this: https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers

**Comment by vimalprakashts** [comment]
@jpsim  , after this error. I fallback to the plan core data . I will try this and give update very soon. and sorry for the late reply.

**Comment by austinzheng** [comment]
Hi @vimalprakashts,

Can you try uncommenting the line `# use_frameworks!` in your podfile (remove the `#`)?

**Comment by jpsim** [comment]
@austinzheng there's an uncommented call to `use_frameworks!` a bit further down in the file too.

**Comment by TimOliver** [comment]
Hi @vimalprakashts! Just pinging this issue. Are you still having trouble, or were you able to get it working in the end? :)

**Comment by mrackwitz** [comment]
I'm closing this issue now as we've never heard back. I hope the team could assist you to resolve your issue. But if you're still having troubles and want to give Realm another shot, feel free to comment back or open another issue anytime.

**Comment by ntokozotep** [comment]
Hi Realm team,
I'm also experiencing the same issue in an existing project when installing Realm via CocoaPods. We're in the process of switching to Realm from Core Data (Realm Objective-C 1.0.2, Objective-C & Swift mixed project, Xcode 7.3.1). I've tried the steps specified at https://realm.io/docs/objc/latest/#cocoapods but that didn't work. The workaround that I'm currently using is to install Realm as a static framework.

**Comment by jpsim** [comment]
@ntokozotep please file a new issue taking care to fill out the new issue template, including full steps to reproduce so we can help you.
