### ISSUE TITLE
Initializer for conditional binding must have Optional type, not 'NSError', branch: jp-combine-swift, Xcode 8, Swift 3

### ISSUE THREAD

**Issue by iJoeCollins** [realm/realm-cocoa#3775]
## Goals

What do you want to achieve?
Build RealmSwift successfully.
## Expected Results

What did you expected to happen?
Successful build.
## Actual Results

What did happened instead?  
Error: Initializer for conditional binding must have Optional type, not 'NSError'

## Steps to Reproduce

What are steps we can follow to reproduce this issue?
Create a new project in Xcode 8. Create a Podfile using pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'jp-combine-swift'
Run pod install. Then try to build the project.
## Code Sample

Here's my example project: [Dropbox link](https://www.dropbox.com/s/8hsdxabalxrrzky/RealmSwift3ExampleBug.zip?dl=1)

## Version of Realm and Tooling

Realm version: 1.0.1, Branch: jp-combine-swift

Xcode version: Xcode 8 beta 1

iOS/OSX version: iOS 10

Dependency manager + version: Cocoapods 1.0.1

**Comment by jpsim** [comment]
The `RealmSwift` pod depends on the `Realm` pod, so if you point to a custom version of one, you'll have to mirror that for the other. Change your Podfile to this:

```ruby
platform :ios, '9.0'
use_frameworks!

target 'RealmSwift3ExampleBug' do
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'jp-combine-swift'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'jp-combine-swift'
end
```

run `pod install` and you'll be ok.

**Comment by iJoeCollins** [comment]
Thanks. I ran it again. Now i have over 200 errors from the Realm framework. Mach -O linker error. Mostly undefined symbols for architecture x86_64...

**Comment by jpsim** [comment]
I hope you'll understand how bleeding edge this is @iJoeCollins, we're doing our best to provide you with support for latest betas, but this hasn't gone through our full QA process yet.

If you're looking for the smoothest experience, I suggest you use the latest _stable_ releases of Xcode and Realm.

That being said, I managed to resolve the linker errors by changing the Podfile again to this:

```ruby
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'jp-combine-swift'
```

**Comment by iJoeCollins** [comment]
No worries. I agree. I decided to revert back to working tools for now. I was hoping we'd get lucky at most. Anyways, thanks JP!

**Comment by jpsim** [comment]
Alright, keep an eye on our upcoming releases and documentation for updates as to when we'll have tested all the beta stuff. Until then, we'll continue to try to keep everything working, but supporting our users shipping apps with official tooling will be our top priority.
