### ISSUE TITLE
Document what module you need to import

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3778]
In our Swift docs, we never say you need to `import RealmSwift`, so users understandably just do `import Realm` and get sad.

**Comment by austinzheng** [comment]
I'm stealing this ticket so you can work on more interesting stuff.

**Comment by JadenGeller** [comment]
I already did this, I'm just unable to build middleman to test it.

**Comment by austinzheng** [comment]
What sort of build problems are you having?

**Comment by JadenGeller** [comment]
(Though your documentation reads better, so we'll go with your pull request 😄)

**Comment by JadenGeller** [comment]
`bundle` doesn't succeed

**Comment by austinzheng** [comment]
It's up to you; I actually didn't realize the ticket was assigned until I had put the PR together. Sorry!
