### ISSUE TITLE
when I Add  a property in realm the project is crash!

### ISSUE THREAD

**Issue by kernel-lj** [realm/realm-cocoa#3781]
In follow is my realm file:
@property NSString *operator;
@property NSString *publishTime;

Now I add a protery,the realm file is becoming : 
@property NSString *operator;
@property NSString *publishTime;
@property NSString *title;

then I run the project in Xcode,click the button where used realm,the project is crash.The errors is

 File "/Users/ltl/Library/Application Support/Realm/rlm_lldb.py", line 226, in RLMResults_SummaryProvider
    if not is_results_evaluated(obj):
  File "/Users/ltl/Library/Application Support/Realm/rlm_lldb.py", line 213, in is_results_evaluated
    mode_query_value = next(m for m in mode_type.enum_members if m.name == 'Query').GetValueAsUnsigned()
StopIteration

How can I fix it ?
But When I delete the APP from iPhone,run the project again,and click the button where used realm,the project is not crash,so I have no idea how to solve this issue?   God ,it is crash agagin!!!

**Comment by mrackwitz** [comment]
You changed your schema. Schema changes require that you provide a migration. You can [read more about migrations in our docs](https://realm.io/docs/objc/latest/#migrations).

---

Beside that the error you're seeing in LLDB is not really related the cause of the issue. You might have either a non-matching or an outdated version of the LLDB plugin, we're providing.
```
File "/Users/ltl/Library/Application Support/Realm/rlm_lldb.py", line 226, in RLMResults_SummaryProvider
if not is_results_evaluated(obj):
File "/Users/ltl/Library/Application Support/Realm/rlm_lldb.py", line 213, in is_results_evaluated
mode_query_value = next(m for m in mode_type.enum_members if m.name == 'Query').GetValueAsUnsigned()
StopIteration
```

You can update the script by executing the following lines on a terminal:
```sh
mkdir -p ~/Library/Application\ Support/Realm
wget -O ~/Library/Application\ Support/Realm/rlm_lldb.py https://raw.githubusercontent.com/realm/realm-cocoa/master/plugin/rlm_lldb.py
```

If the error should still occur, could you please share which version of Realm and Xcode you're using?

**Comment by jpsim** [comment]
@kernel-lj just following up to see if @mrackwitz's last comment was helpful or if you're still having issues.

**Comment by TimOliver** [comment]
We haven't heard anything back for a little while here, so I'd say it's safe to close this issue now.
Feel free to re-open it if you do need any more help!
