### ISSUE TITLE
Memory leak Realm 1.0.1

### ISSUE THREAD

**Issue by smolskyaleksey** [realm/realm-cocoa#3783]
I catch memory leak when i try to add objects to RLMArrayLinkView
![2016-06-21 14 07 12](https://cloud.githubusercontent.com/assets/6605765/16227648/9910d6c8-37ba-11e6-98da-fe64abd8948a.png)

**Comment by jpsim** [comment]
Can you please share steps to reproduce?

**Comment by smolskyaleksey** [comment]
Please close this issue I found bug in RBQFetchedResultsController
