### ISSUE TITLE
Terminating app due to uncaught exception 'RLMException', reason: 'flock() failed: Interrupted system call

### ISSUE THREAD

**Issue by mcmatan** [realm/realm-cocoa#3793]
## Goals

What do you want to achieve?

A normal user flow

## Expected Results

No crash

## Actual Results

App crash for a reason that a can't find any info about

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

I don't know what triggered it, it seams it happend during a write transaction, but it doesn't happen consistently.

## Code Sample

    JVTRoom *room = [self getRoomFromId:roomId];

    if (room) {

        RLMRealm *realm = [RLMRealm defaultRealm];

        [realm beginWriteTransaction];

        room.isPresentedRoom = presented;

        [realm commitWriteTransaction];

    }

## Version of Realm and Tooling

Realm version: ?

Realm ( 1.0.1 )

Xcode version: ?

7.3.1

iOS/OSX version: ?

9.3.2

Dependency manager + version: ?

Cocoapods 1.0.0

**Comment by Kirow** [comment]
Recently I got similar crash. It seems to happened when 2 threads have opened connection to one database file and making transaction in same time.

**Comment by bdash** [comment]
Appears to be an oversight in core. Wrote up realm/realm-core#1916.

**Comment by Kirow** [comment]
#NeedHelp

I have a problem with parallel data processing (at least I think so). In fact I'm not sure, but something sometimes freeze my app and for some reasons I think it is related to flock() exception.

Is it legal to open same Realm file in different threads and make transactions simultaneously (to different tables if it matters). I'm pretty sure that I did this before and it worked, but intuition says me that it might be a problem now.

**Comment by donaldking** [comment]
I'm getting similar exception. Is there a fix for this yet?

**Comment by bdash** [comment]
A fix for this issue was released in v1.0.2. If you're using an older version, please update. If you're already using v1.0.2, please file a new bug report with all of the information requested in the issue template.
