### ISSUE TITLE
Create a notification block for a single object

### ISSUE THREAD

**Issue by CraigSiemens** [realm/realm-cocoa#3795]
## Goals

Sometimes a view needs to show the details for a single object. It would be nice to have an easy way to be notified when that object changes.

## Expected Results

Have the method on `Object` that will add a notification block.
```swift
myObject.addNotificationBlock {
    // update ui
}
```

## Current Workaround

This only works if the object has a primary key. You can just create a query for that object.

``` swift
let objectQuery = realm.objects(MyObjectSubclass).filter("id == %@", myObject.id)
notificationToken = objectQuery.addNotificationBlock { (changes: RealmCollectionChange) in
    // update ui
}
```

**Comment by jpsim** [comment]
Realm Objects conform to KVO, so that's the mechanism you'll need to use to get per-object updates right now. We're already tracking adding `addNotificationBlock(_:)` to `Object` in #3431. It's something we'll want to do at some point, but it'll mostly be an API shortcut.
