### ISSUE TITLE
Documentation for Xcode 8

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#3796]
Hoping to get feedback for this preliminary, working set of instructions for building for Swift 3 and/or Xcode 8.

Some questions:
* Where should these instructions live?
* Are we going to allow people to use CocoaPods today to build Realm for Swift 3?

@jpsim @tgoyne @bdash 

-------

## Building Realm from source for Xcode 8 Beta

**Important**: Realm for Xcode 8 is not officially supported; the instructions below are intended for developers who are working to port their applications to Swift 2.3 or Swift 3, or otherwise using Xcode 8. During the preview period, the only way to obtain Realm for Xcode 8 is by building from source; we are not supporting dependency managers or providing pre-packaged binaries.

**Prerequisites**: you must have a valid Apple Developer account, with certificates for iOS and/or macOS. Go to https://developer.apple.com and update your certificates if necessary.

1. Clone the Realm Cocoa repository. (Run the Terminal command `git clone git@github.com:realm/realm-cocoa.git` in whatever directory you want the repository to be stored in.)
2. Open _build.sh_ (it is located in the root project directory).
3. Find the line that reads: `CODESIGN_PARAMS="CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO"`, and change it to just read `CODESIGN_PARAMS=""`. (It is line 29 in the file.)
4. Open the Realm Cocoa Xcode project (_Realm.xcodeproj_).
5. If a dialog window appears asking whether to "Convert to Current Swift Syntax?", press the "Later" button.
6. Click on the Realm project in the Project Navigator.
7. Click on the "Realm" target.
8. Click on the "Build Settings" tab (make sure "All" options are shown, not just "Basic"), and scroll down to the "Signing" section.
9. Expand the "Code Signing Identity" field by clicking the triangle.
10. For the "Debug" and "Release" sub-options, choose a "Mac Developer" identity from the drop-down menu (in most cases, just choose the one within the "Automatic" section).
11. If you wish to build Realm for an iOS app (iPhone, Apple TV, Apple Watch), for the "iPhone* SDK" sub-options choose an "iPhone Developer" identity from the drop-down menu (in most cases, choose an appropriate identity from within the "Identities in Keychain" section).
12. Click on the "General" tab.
13. Under the "Signing" category, press the"Enable Development Signing" button, and then uncheck the "Automatically Manage Signing" checkbox.
14. Under "Signing (Debug)" and "Signing (Release)", choose the Apple Developer team associated with the certificates you chose in steps 10 and 11 from the drop-down menus. (If there is only one team listed, just choose that one.)
15. If you want to build Realm Swift, repeat steps 6 through 14 for the "RealmSwift" target. (If you want to build for Swift 2.3, activate the "Use Legacy Swift Language Version" build setting.)
16. Choose the correct scheme (_Realm_ or _RealmSwift_) and device. If you want to build Realm for an OS X application, choose "My Mac". Otherwise choose the appropriate "Generic _*OS_ Device".
17. Build the project.
18. In the Project Navigator, under the "Products" group, right-click on "Realm.framework" and select "Show in Finder" to open up the folder containing the built frameworks.
19. Drag _Realm.framework_ (and, if using Realm Swift, _RealmSwift.framework_) into your Xcode project. Follow the instructions at https://realm.io/docs/objc/latest/#dynamic-install to complete setup.

**Comment by jpsim** [comment]
> Where should these instructions live?

Our installation instructions are kept in one place for consistency. It's in https://realm.io/docs/swift/latest/#installation

The source is in https://github.com/realm/realm.io-middleman/blob/master/source/en/docs/objc/latest/index.html.md.erb

> Are we going to allow people to use CocoaPods today to build Realm for Swift 3?

Yes why wouldn't we?

**Comment by austinzheng** [comment]
I realized that this works with CocoaPods (if you do the same types of permission munging as described above). But on #3752 people are having trouble even getting their projects to compile.

**Comment by jpsim** [comment]
> I realized that this works with CocoaPods (if you do the same types of permission munging as described above).

Why would that be necessary? CocoaPods doesn't reuse our Xcode project.

**Comment by austinzheng** [comment]
It doesn't, but you get the same code signing errors if you try to build a project in Xcode 8 that has the development versions of Realm or RealmSwift as a dependency. If you have any ideas about how to suppress them without having to modify the code signing settings for the Pods project, I would love to hear them.

**Comment by jpsim** [comment]
Does this mean that CocoaPods in general doesn't work with Xcode 8 right now? If this is unique to our podspecs, what in there is causing this to happen?

**Comment by austinzheng** [comment]
Well, I just set up an empty pods-based project that depends only on the `Alamofire` pod and I got the same error. So it doesn't look like a Realm-specific issue.

**Comment by austinzheng** [comment]
Looks like they are aware of the issue: https://github.com/CocoaPods/CocoaPods/pull/5528

Not sure if we want to give our users workaround instructions or have them use a development version of CocoaPods?

**Comment by jpsim** [comment]
Just point to CocoaPods support being blocked on a CocoaPods update.

**Comment by marchy** [comment]
CocoaPods has released support for Xcode 8 in [1.10.beta.1](https://github.com/CocoaPods/CocoaPods/releases).
Can you guys confirm if this issue still exists?

**Comment by austinzheng** [comment]
Between Xcode 8b3 and 1.10.beta1, the issue should be gone. We should have 'official' instructions up shortly; I'll post a link when they are live.

**Comment by marchy** [comment]
@austinzheng Thanks for the update Austin. This helps us time our migration efforts accordingly since we are currently blocked on some new feature dev leveraging new iOS 10 SDKs with this.

**Comment by austinzheng** [comment]
I talked to our other engineers and we've decided we won't be posting "official" installation instructions until Xcode 8 is released. However, anyone who wishes to build from source can try the instructions [here](http://stackoverflow.com/questions/38696369/build-realm-for-swift-3-xcode-8/38707357#38707357), which should work with Beta 3 (and 4).

**Comment by algoterranean** [comment]
I ran into a few issues with this, using the advised instructions from @austinzheng. Some additional details that may help some people:

1. To run build.sh using the XCode beta, you need to set the default xcode version to beta using the command
`sudo xcode-select -switch /Applications/Xcode-beta.app`

This obviously has nothing to do with Realm.

2. After I cloned the realm repo, I had to update the submodules via
`git submodule init && git submodule update`

This is documented somewhere but not on the instructions above or the main source at https://realm.io/docs/swift/latest/#installation


3. The xcode project file has a number of duplicate devices available, and xcodebuild was unable to determine which was supposed to be built. I had to remove all duplicate simulator devices (so that only one remained for each type, e.g, iphone 6, iphone 6s, etc.

The last step in particular wasn't documented anywhere and I was unable to run build.sh until removing those devices.

**Comment by hyouuu** [comment]
Thanks @algoterranean ! 
FYI you can use gem install snapshot; snapshot reset_simulators to reset all your simulators, answer from http://stackoverflow.com/questions/27614197/duplicate-iphone-simulators-appeared-on-my-xcode

**Comment by freak4pc** [comment]
Hey everyone. Xcode 8 GM is out and this still doesn't seem to be resolved.
Any notes on how to get RealmSwift compling under Xcode 8 for either Swift 2.3 (Legacy) or 3.0 ?

**Comment by freak4pc** [comment]
Was able to use the intstructions posted by @austinzheng to make it compile and run the app on my iOS Device. Problem is, I can't get it to work on the Simulator. I'm guessing because this isn't a Universal framework ? Thoughts on how to achieve that?

**Comment by jpsim** [comment]
@freak4pc please wait until our official Xcode 8 support with a finalized API, installation instructions and documentation later this week.

**Comment by freak4pc** [comment]
I eventually was able to build it yesterday with some playing around, but I'll still wait for a more solid build plan before proceeding further. Thanks @jpsim .

**Comment by Maryom** [comment]
Hi,
The steps didn't work with me, I got 5 errors as shown in the attached image:
<img width="263" alt="screen shot 2016-09-14 at 7 23 54 pm" src="https://cloud.githubusercontent.com/assets/3218401/18520516/d1324d64-7ab0-11e6-9492-8aea32e86063.png">

Any help?

**Comment by jpsim** [comment]
@Maryom  `git submodule update --init --recursive`

**Comment by Maryom** [comment]
@jpsim Thanks for your fast reply. It worked perfectly. Thanks again.

**Comment by helloandrewpark** [comment]
Hey,

I'm getting the following error from `sh build.sh ios-swift`
```
error: @escaping attribute only applies to function types
    public func addNotificationBlock(block: @escaping NotificationBlock) -> NotificationToken {
                                             ^
/Path/Realm/realm-cocoa/RealmSwift/Migration.swift:180:57: error: @escaping attribute only applies to function types
internal func accessorMigrationBlock(_ migrationBlock: @escaping MigrationBlock) -> RLMMigrationBlock {
                                                        ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
```

**Comment by jpsim** [comment]
@helloandrewpark you're not on the latest version of `master`...

**Comment by Maryom** [comment]
Hi again 😅

I got another error:

`ld: framework not found Realm for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any help?

**Comment by freak4pc** [comment]
Hey Guys, 
Seems like the latest version of CocoaPods solves the "workarounds" of setting swift version. 
Just do : 

`sudo gem update --pre cocoapods` (should update you to v1.1.1.0.rc.2)

Your Podfile should still include an explicit reference to the GitHub repo e.g. 
```
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
```

Also, you might want to add the new `.swift-version` file with the appropriate version you would be using (defaults to 2.3)

More info here: 
https://github.com/CocoaPods/CocoaPods/pull/5841

**Comment by Maryom** [comment]
Hey @freak4pc,

My cocoa pods version is v1.1.1.0.rc.2:
`/Users/mariam/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.0.rc.2/lib/cocoapods.rb`

I added these lines to my podfile:
`pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true`

And I got these errors 😖👇🏼
<img width="563" alt="screen shot 2016-09-15 at 9 17 19 pm" src="https://cloud.githubusercontent.com/assets/3218401/18561756/e068cef0-7b89-11e6-9cbf-7045064ec99b.png">

Any help?

Thanks.

**Comment by freak4pc** [comment]
Uhm, interesting. That worked fine for me. 

Do you mind trying `pod deintegrate` and `pod install` again ? @mamaral

**Comment by jpsim** [comment]
We've maintained support for Realm Swift across Xcode 8 betas since WWDC, making adjustments to continue compiling and passing tests for Swift 2.2, 2.3 and 3.0 as new betas came out.

However, due to the amount of churn Swift 3 has seen in the last 3 months, we held off on thoroughly reviewing all our Swift 3 API changes and accommodating both Xcode 7.3.1 and Xcode 8 into our continuous integration, testing, docs and release packaging processes.

With Xcode 8 GM last week, we decided to [make a push](https://twitter.com/realm/status/773665903946952704) to finalize our Swift 3 APIs along with the other integration points mentioned above.

That work is now mostly complete and we're preparing a 1.1.0 release for tomorrow, at which point our Swift 3 APIs will be final, binaries will be made available for Swift 2.3 and 3.0 in our release zips, and docs will be updated to reflect the new APIs.

Thanks for your patience.
JP

**Comment by freak4pc** [comment]
Woohoo! that's amazing @jpsim! Thanks :)

**Comment by Maryom** [comment]
@freak4pc Yes I tried and I got the same error. Anyways, thanks for your help. I think it's better to wait for tomorrow release :)

**Comment by Maryom** [comment]
@jpsim That's awesome news :)
