### ISSUE TITLE
Compiler errors when calling allObjects(ofType:) in swift3

### ISSUE THREAD

**Issue by mattdelves** [realm/realm-cocoa#3802]
## Goals

Retrieve a list of all objects of a particular type when calling `allObjects(ofType:)` in swift 3

## Expected Results

A Result of all objects is returned

## Actual Results

Compiler error due to:

`Cannot create a single-element tuple with an element label`

`Missing argument label 'ofType:' in call`

## Steps to Reproduce

Try to compile the following code:

`realm.allObjects(ofType: MyAwesomeRealmObject)`

## Code Sample

`realm.allObjects(ofType: MyAwesomeRealmObject)`

## Version of Realm and Tooling

Realm version: master 8b5b22fae0cabcd2ad579647bec05129e31257b2

Xcode version: 8.0 beta 1

iOS/OSX version: iOS 10

Dependency manager + version: Carthage

**Comment by jroschen** [comment]
I was struggling through this same exact issue as you last night. I looked through the Swift tests that have been updated for allObjects and found my answer. Try appending `.self` to the end of your object like so.

`realm.allObjects(ofType: MyAwesomeRealmObject.self)`

**Comment by mattdelves** [comment]
Yeah, using `.self` allows for it to work. Though chatting with @jpsim on twitter there was some thought that it may be a compiler bug. Happy for this issue to be closed if using `MyRealmObject.self` is the preferred way.

**Comment by austinzheng** [comment]
The original behavior (referring to the value of a type without the `.self`) was a bug in Swift. It was fixed sometime between 2.2 and 3, and the `.self` is now mandatory. This isn't something that Realm can control, unfortunately.

If you see any code samples on the site that omit the `.self`, please let us know!
