### ISSUE TITLE
Adding a deleted or invalidated object to a Realm is not permitted

### ISSUE THREAD

**Issue by todorspetkov** [realm/realm-cocoa#3805]
Hello, I am facing the following problem : after having deleted objects from default Realm
I query for object's of the same type and receive as result deleted/invalidated objects. 
I have tried to call [realm refresh] but this has not solved the problem. 
The deletion and query are performed on the same background thread.

Here are the details :

1. I have an array of objects (each object is called Bin).
2. These objects get refreshed as follows

        [BinDao deleteAll : [Bin class]]; ----> delete all previous Bin objects from default realm
        [BinDao saveArray : bins];        ----> save all new objects to default realm

3. Other objects (called Generic) have a "bin foreign key"
        
        @property RLMArray<Bin*><Bin> * bins;
        @property NSArray * binIds;

4. After having updated the Bins in realm I try to assign the bins property to a Generic object as follows 

                RLMRealm * realm = [RLMRealm defaultRealm];
                [realm refresh];
                [realm beginWriteTransaction];
                for (Generic * generic in array)
                {
                        @try
                        {
                                NSArray * binIds = [generic binIds];
                                RLMResults<Bin*> * bins = [Bin objectsWhere : @"binId IN %@" , binIds];
                                [generic.bins addObjects : bins];
                                [realm addOrUpdateObject : generic];
                        }
                        @catch (NSException * ex)
                        {
                                DLogVerbose( @"%@ - %@" , ex.name , ex.reason);
                                @throw ex;
                        }
                }

                [realm commitWriteTransaction];

I immediately get "RLMException - Adding a deleted or invalidated object to a Realm is not permitted"
when  [realm addOrUpdateObject : generic] is called.

Does anyone have any idea what is going on here ?!
Thanks a lot ,
        Todor Petkov

p.s. The error is thrown here

```objc
static inline RLMObjectBase *RLMGetLinkedObjectForValue
{
        ...    
        if (link.isInvalidated) 
       {
               @throw RLMException(@"Adding a deleted or invalidated object to a Realm is not permitted");
        }
       ...
}
```

**Comment by mrackwitz** [comment]
Your `Bin` objects shouldn't be the problem here as they are freshly retrieved by their ids, before you add them. But where is your `array` of `Generic` objects coming from? It seems like this contains at least one object which was deleted. If you could share some more code around that, we could look into that.

**Comment by todorspetkov** [comment]
Ok, I figured it out : I was deleteing the Bins from one thread and trying to query them from another ...
Sorry for the trouble ...
