### ISSUE TITLE
Recursion records

### ISSUE THREAD

**Issue by smolskyaleksey** [realm/realm-cocoa#3808]
[testbatch.zip](https://github.com/realm/realm-cocoa/files/341265/testbatch.zip)
Hi, could you help me to understand what did happened ? 
I tried to write 100 entities with big text (16 kb). All text is the same. After i wrote first and had crash with same kind of recursion in stack trace.
![2016-06-29 16 42 02](https://cloud.githubusercontent.com/assets/6605765/16454408/4cdfd9b0-3e19-11e6-961b-5afecf6c7854.png)

Could you help me to found the way how can i fix it?

**Comment by smolskyaleksey** [comment]
I provided test project with cocoapods.
Steps to reproduce crash:
1) Open app
2) press button "Press me!"
3)press button "Plus" on top right corner.
4)Crash

**Comment by smolskyaleksey** [comment]
Reproduced only on devices. Simulator is OK.

**Comment by jpsim** [comment]
Hi @smolskyaleksey, sorry you're affected by this. We're aware of this issue and are already tracking it as #3502. There should be more information available in that ticket. I'll close this as a duplicate to keep the conversation all in one place.

Please subscribe to #3502 for updates on this.

I'd recommend not indexing string properties with long common prefixes until we resolve this.

**Comment by smolskyaleksey** [comment]
Thank you very much. I'll wait for solution.
