### ISSUE TITLE
Crash on locked device when querying the default Realm

### ISSUE THREAD

**Issue by chucktee** [realm/realm-cocoa#3812]
## Goals

Read / Write to the default Realm while app is in the background on a locked device.

## Expected Results

Access without a crash.

## Actual Results

On a locked device, I am able to get the default Realm, however when I pull some results, I get an EXC_BAD_ACCESS at the return line in:

```
inline DataType Table::get_column_type(size_t ndx) const noexcept
{
    REALM_ASSERT_3(ndx, <, m_spec.get_column_count());
    return m_spec.get_public_column_type(nix);
}
```

## Steps to Reproduce

Query the default Realm on a locked device.

## Code Sample

I discovered this and addressed it months ago by removing file protection, and it was working until I upgraded to 1.0.1.  The app does not use Apple file protection.

I am making sure to set the default path, and then clearing locks with these 2 functions (modified for 1.0.1 to use fileURL rather than config.path)

```
//---------------------------------------------------------------------------------
+ (void) setDefaultRealmPath {
    
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    
    // Check if the path exists
    NSError *error;
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    NSString *dataPath = [documentsDirectory stringByAppendingPathComponent:@"Data"];
    if(![[NSFileManager defaultManager] fileExistsAtPath:dataPath])
        [[NSFileManager defaultManager] createDirectoryAtPath:dataPath withIntermediateDirectories:NO attributes:nil error:&error];
    
    // Use the default directory
    config.fileURL = [[[config.fileURL URLByDeletingLastPathComponent]
                       URLByAppendingPathComponent:@"Data/default"]
                      URLByAppendingPathExtension:@"realm"];
    
    NSLog(@"Setting default Realm path to: %@", config.fileURL);
    
    // Set this as the configuration used for the default Realm
    [RLMRealmConfiguration setDefaultConfiguration:config];
    
}

//---------------------------------------------------------------------------------
+ (void) clearLocks {
    
    RLMRealm *realm = [RLMRealm defaultRealm];
    
    // Get our Realm file's parent directory
    NSString *folderPath = realm.configuration.fileURL.URLByDeletingLastPathComponent.path;
    
    // Disable file protection for this directory
    NSError *error = nil;
    [[NSFileManager defaultManager] setAttributes:@{NSFileProtectionKey: NSFileProtectionNone} ofItemAtPath:folderPath error:&error];
    if(error) {
        NSLog(@"Error clearing protection on %@", folderPath);
    } else {
        NSLog(@"Clearing protection on %@", folderPath);
    }
}
```
## Version of Realm and Tooling

Realm version: 1.0.1

Xcode version: 7.3.1

iOS/OSX version: 9ish

**Comment by jpsim** [comment]
What are the `NSFileProtection` attributes of your Realm? iOS protects files from being accessed when locked with certain file protection settings and it's up to the developer to avoid accessing those locked files, or to loosen the file protection settings if you need access to the file while the device is locked.

We document how this relates to Realm in the [Using Realm with background app refresh](https://realm.io/docs/objc/latest/#using-realm-with-background-app-refresh) section of our docs.

Could you please read through that and see if it applies to you?

Thanks!

**Comment by chucktee** [comment]
Hi jp-

I've read that- I'm using the code from that section of the docs in my code and noted the same in my post.  It's in the clearLocks function.  Am I missing something?

**Comment by jpsim** [comment]
Sorry @chucktee, my mistake, I definitely skimmed that too quickly, been doing too much support today 😅.

You seem to be doing everything right. I don't see anything that would cause the file to be inaccessible unless you're accessing the Realm prior to setting the default configuration and the file protection attributes?

Any chance you could share a sample project that reproduces this behavior?

**Comment by chucktee** [comment]
No worries JP- I can't imagine.
In trying to build a small sample for you guys to look at, I could not get it to crash- so I completely nuked all cocoa pods and Realm related items and did a full re-install.  Strange this project has been running for a year and this popped up when I updated cocoa pods to >1 and Realm from .98 to 1.0.1

Thanks for your help.

**Comment by jpsim** [comment]
Very odd that re-installing Realm could impact this at all... please let us know if you ever see this again.
