### ISSUE TITLE
Invalid mutex object provided

### ISSUE THREAD

**Issue by Changzw** [realm/realm-cocoa#3819]
util/thread.cpp:176: [realm-core-0.96.2] pthread_mutex_lock() failed: Invalid mutex object provided
0   measurementqm                       0x000000010456baa8 _ZN5realm4util18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
1   measurementqm                       0x000000010456bd7a _ZN5realm4util9terminateEPKcS2_l + 458
2   measurementqm                       0x000000010456c4c6 _ZN5realm4util5Mutex11lock_failedEi + 38
3   measurementqm                       0x00000001046bf7a3 _ZN5realm5Table21discard_row_accessorsEv + 147
4   measurementqm                       0x00000001046c017a _ZN5realm5Table6detachEv + 138
5   measurementqm                       0x0000000104643c20 _ZN5realm5Group6detachEv + 64
6   measurementqm                       0x000000010464d3e4 _ZN5realm11SharedGroup8end_readEv + 68
7   measurementqm                       0x000000010464cb35 _ZN5realm11SharedGroup5closeEv + 69
8   measurementqm                       0x000000010464d4ce _ZN5realm11SharedGroupD2Ev + 14
9   measurementqm                       0x00000001044ce623 _ZN5realm5RealmD2Ev + 2067
10  measurementqm                       0x00000001044ce745 _ZN5realm5RealmD1Ev + 21
11  measurementqm                       0x0000000104338aa9 _ZNSt3__120__shared_ptr_emplaceIN5realm5RealmENS_9allocatorIS2_EEE16__on_zero_sharedEv + 41
12  libc++.1.dylib                      0x0000000104ee86da _ZNSt3__119__shared_weak_count16__release_sharedEv + 44
13  measurementqm                       0x000000010437869c _ZNSt3__110shared_ptrIN5realm5RealmEED2Ev + 44
14  measurementqm                       0x00000001043723c5 _ZNSt3__110shared_ptrIN5realm5RealmEED1Ev + 21
15  measurementqm                       0x000000010449d99e -[RLMRealm .cxx_destruct] + 126
16  libobjc.A.dylib                     0x00000001085b57bb _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
17  libobjc.A.dylib                     0x00000001085c0332 objc_destructInstance + 93
18  libobjc.A.dylib                     0x00000001085c0365 object_dispose + 22
19  measurementqm                       0x000000010449b031 -[RLMRealm dealloc] + 241
20  libobjc.A.dylib                     0x00000001085caafe _ZN11objc_object17sidetable_releaseEb + 232
21  libobjc.A.dylib                     0x00000001085cb0b8 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 488
22  measurementqm                       0x0000000103fd8abb __32-[DataStore bgWriteTransaction:]_block_invoke_2 + 299
23  libdispatch.dylib                   0x0000000109e41d9d _dispatch_call_block_and_release + 12
24  libdispatch.dylib                   0x0000000109e623eb _dispatch_client_callout + 8
25  libdispatch.dylib                   0x0000000109e4882c _dispatch_queue_drain + 2215
26  libdispatch.dylib                   0x0000000109e47d4d _dispatch_queue_invoke + 601
27  libdispatch.dylib                   0x0000000109e4a996 _dispatch_root_queue_drain + 1420
28  libdispatch.dylib                   0x0000000109e4a405 _dispatch_worker_thread3 + 111
29  libsystem_pthread.dylib             0x000000010a19f4de _pthread_wqthread + 1129
30  libsystem_pthread.dylib             0x000000010a19d341 start_wqthread + 13
IMPORTANT: if you see this error, please send this log to help@realm.io.

**Comment by Changzw** [comment]
upgrade version to solve this issue？

**Comment by austinzheng** [comment]
Possibly. What version of Realm Cocoa were you using, and what were you trying to do when this error occurred?

**Comment by bdash** [comment]
The crash log mentions core v0.96.2, which indicates that it's a Realm Cocoa version prior to v0.98.4. We've made numerous releases in the months since then, the most recent being v1.0.1. Please upgrade to that version and reopen this issue if you're still hitting this crash.

**Comment by Changzw** [comment]
thank you for your time and help,
i didn't find the crash any more. (:
