### ISSUE TITLE
Use BETWEEN for dates

### ISSUE THREAD

**Issue by chashmeetsingh** [realm/realm-cocoa#3821]
## Goals

What do you want to achieve?
I want to retrieve results between two dates

## Expected Results

What did you expected to happen?
Get results between two dates
## Actual Results

What did happened instead?  
 Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unable to parse the format string "airDateTime BETWEEN {2016-07-04 10:56:24 +0000, 2016-08-03 10:56:24 +0000}"'

## Steps to Reproduce

What are steps we can follow to reproduce this issue?
```
        let allEpisodes = realm.objects(Episode.self)
        let today = NSDate()//.description
        let later = NSDate().dateByAddingTimeInterval(60 * 60 * 24 * 30)//.description
        let aired = allEpisodes.filter("airDateTime BETWEEN {\(today), \(later)}")
```
## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?
1.0.1
Xcode version: ?
7.3.1
iOS/OSX version: ?
9.3
Dependency manager + version: ?

**Comment by stel** [comment]
You should use `filter(predicateFormat:args:)` instead of passing a simple string. Realm uses `NSPredicate` internally and its initializer looks at the arguments types also.

Try something like this:

`let aired = allEpisodes.filter("airDateTime BETWEEN {%@, %@}", today, later)`

**Comment by chashmeetsingh** [comment]
Ok thanks for the info 👍

**Comment by jesuasir007** [comment]
I have given this format ,that's not fetching the data from the database ,the date format is same as all .please give me sample code ?
