### ISSUE TITLE
Distinct Query to retrieve objects

### ISSUE THREAD

**Issue by chashmeetsingh** [realm/realm-cocoa#3825]
## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?
Get only distinct objects from the db

## Actual Results

What did happened instead?  
Can't find any way (no distinct function in docs)

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?
1.0.1
Xcode version: ?
7.3.1
iOS/OSX version: ?
9.3

**Comment by bdash** [comment]
Hi @chashmeetsingh. This is not currently directly supported. We're tracking requests for this feature in #1103. Please follow that issue to receive updates when we implement it.
