### ISSUE TITLE
Realm Getting realm/util/features.h not found when compiling

### ISSUE THREAD

**Issue by afiq90** [realm/realm-cocoa#3826]
Hey guys, why did I'm getting **realm/util/features.h not found** when compiling. I'm using **Xcode 8 BETA, pod version 1.0.1** and OSX 10.11.5. I tried to do `rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install` but it still doesn't work. Any help will be much appreciated.

**Comment by mrackwitz** [comment]
Please try to clean all build products of all targets of the current project and other projects which share the same build folder.
You can achieve that by holding down the Option key (⌥) and select *Product* > *Clean Builder Folder…* in the Xcode menu. (**⌥⇧⌘K**)

**Comment by afiq90** [comment]
Tried to clean builder folder but still got the error.

**Comment by TimOliver** [comment]
Just to make absolutely sure, you're not trying to build Realm Swift in Xcode 8, are you?
You might also want to try [deleting your project's DerivedData](https://iosdevcenters.blogspot.com/2015/12/how-to-delete-derived-data-and-clean.html) folder as well.

**Comment by mrackwitz** [comment]
If this should be still an issue, please try to run `pod update Realm RealmSwift`. I hope though you could resolve it meanwhile.

**Comment by jpsim** [comment]
I'm closing this since we haven't heard back from @afiq90 in a while and haven't been able to reproduce this ourselves after following the troubleshooting steps shared in [our docs](https://realm.io/docs/objc/latest/#reinstalling-via-dependency-managers).
