### ISSUE TITLE
Objective-C generics as properties of Swift classes show up as type `@` in the runtime

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3843]
We should file a radar and/or a Swift bug report.

**Comment by bdash** [comment]
Is this with all Xcode and Swift versions, or is it new in the Xcode 8 / Swift 3 betas?

**Comment by JadenGeller** [comment]
Objective-C generics did not import into Swift (expect for classes with special bridging already like NSArray) until Swift 3.0 / Xcode 8. I should check that this still is an issue on the latest beta. I think I'm behind a version.

**Comment by JadenGeller** [comment]
I just verified that this is an existing issue in beta 2. Hopefully we can get it fixed by the time Swift 3.0 is released. Regardless, there's a workaround, so we can still run our tests in the meantime. https://github.com/realm/realm-cocoa/commit/f70fb036f3e389f8be9fb74c1d5a54e2dd1f15cf

**Comment by JadenGeller** [comment]
Filed [SR-2031](https://bugs.swift.org/browse/SR-2031).
