### ISSUE TITLE
object confusion

### ISSUE THREAD

**Issue by biskit** [realm/realm-cocoa#3844]
I'm trying to store and read a class that's created by initializing via `mapObjectTo()`. the problem is this.
i can get the values via a getter method, but not via member variable. 

for eg:

```
class Dog: Object {
    var name: String?
}

class D {
   var name: String?
}

let d = D()
d.name = "buggy"

let d2: Dog = d2.mapObjectTo()
print(d2.name)     -> prints "buggy"

let r = try! Realm()
try! r.write() {
   r.add(d2)
}

let d3 = r.objects(Dog.self).first
print(d3.name)     -> prints (nil)
print(d3["name"])   -> prints "buggy"
```

can someone explain why?

**Comment by bdash** [comment]
The `name` property of your `Dog` type [needs to be declared as `dynamic var` rather than just `var`](https://realm.io/docs/swift/latest/#property-attributes).

**Comment by biskit** [comment]
gimme a hug man!  👏 
been scratching my head for days and this should a serious FAQ
