### ISSUE TITLE
Silence undesirable unused result warnings for methods imported into Swift from Objective-C

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3845]
Class methods that return `instancetype` are imported without `@discardableResult` in Swift 3. I don’t think this is desirable for things like `create(in:with:)` to warn about unused results, so we should find a way to prevent this. I don't think Objective-C (yet) has a discardable result attribute, so I'm unsure if a workaround exists.

**Comment by JadenGeller** [comment]
[SE-0047](https://github.com/apple/swift-evolution/blob/master/proposals/0047-nonvoid-warn.md) mentions [Objective-C annotation](https://github.com/apple/swift-evolution/blob/master/proposals/0047-nonvoid-warn.md#objective-c-annotation), but it isn't clear that this is implemented yet.

**Comment by austinzheng** [comment]
Thanks for filing this issue, Jaden! I'm 99% sure we ended up shipping with the discardableResults annotations.
