### ISSUE TITLE
Querying objects having linked objects and live updates

### ISSUE THREAD

**Issue by viktorasl** [realm/realm-cocoa#3853]
## Goals

In our project we have two kind of calendar event types (for example A and B) and we display them in one calendar view filtering them by `employeeId` and `date` (from the example they might seem quite similar but they are really different so treating them as similar ones are not an option). Up until now we were querying both A and B with separate queries and were having two references to `RLMResult`. Now we want to start using fine-grained notifications and redraw calendar view when events (both A and B) are updated, new ones are added or deleted. The problem is that A and B are updated during the same API call so there would be two separate notifications which would lead to redrawing calendar twice. The first idea was to wrap them into some kind of `CalendarEvent`:
```ObjC
@interface CalendarEvent : RLMObject
@property (nonatomic) A* a;
@property (nonatomic) B* b;
@end
```
but it's pretty impossible or at least will require a lot of refactoring around the app wrapping all API responses having `A` or `B` into `CalendarEvent`. Then we've found inverse relationships method and made `CalendarEventToken`:
```ObjC
@interface CalendarEventToken : RLMObject
@property (nonatomic) NSInteger identifier;
@property (readonly) RLMLinkingObjects *aEvents;
@property (readonly) RLMLinkingObjects *bEvents;
@end

@implementation CalendarEventToken
+ (NSString *)primaryKey {
    return @"identifier";
}
+ (NSDictionary *)linkingObjectsProperties {
    return @{
        @"aEvents": [RLMPropertyDescriptor descriptorWithClass:A.class propertyName:@"token"],
        @"bEvents": [RLMPropertyDescriptor descriptorWithClass:B.class propertyName:@"token"]
    };
}
@end
```
and of course added one additional `token` property for each A and B.

## Expected Results

Query
```ObjC
RLMResults *twoTypesOfEventsWrappedIntoTokenResults = [CalendarEventToken objectsWhere:@"(ANY aEvents.employeeId = %@) OR (ANY bEvents.employeeId = %@)", @(self.employeeId), @(self.employee)]
```
worked fine but when events have been updated RLMResults were not updated nor notification block has been called.

I understand that it's a odd case and not sure that it's a good practice doing that but we have not found any other solution. It would be totally understandable if CalendarEventTokens are not updated if their inner objects are updated but would be good to know that.

PS. If you have any ideas how we can solve our problem that would be awesome!

## Actual Results

Actual results are shown in demo project.
https://github.com/viktorasl/Realm-RLMLinkingObjects/blob/master/Realm-RLMLinkingObjects/ViewController.m

## Version of Realm and Tooling

Realm version: 1.0.1 (and some other lower versions)

Xcode version: 7.3.1

iOS/OSX version: 9.3

Dependency manager + version: Cocoapods 1.0.1

**Comment by bdash** [comment]
Thanks for the awesome bug report, @viktorasl! I've determined that query results don't update correctly when the query predicate involves traversing an inverse relationship. This is due to an issue in Realm's underlying core engine (realm/realm-core#1950). A fix is in the works and should hopefully make it into a Realm Objective-C release in the near future.

I noticed from your test case that you observed a second issue with `-[EventFooType initWithValue:]` throwing an exception unless you first explicitly call `+[RLMRealm defaultRealm]`. That looks to be worthy of its own bug report.

**Comment by viktorasl** [comment]
Not sure if it falls under the same issue, but I have noticed that query results are updated if transaction is done on the same dispatch
https://github.com/viktorasl/Realm-RLMLinkingObjects/blob/master/Realm-RLMLinkingObjects/ViewController.m#L82

**Comment by bdash** [comment]
That's due to the details of how `RLMResults` lazily query evaluation interacts with the fine-grained notification mechanism.

**Comment by smolskyaleksey** [comment]
Hi , I need help and explanation how can i fixed it. I have model 

``` obj-c
@interface FCConversation : FCBaseChat

@property NSString *name;
@property NSString *picture;
@property BOOL isPerToPer;

@property (readonly) RLMLinkingObjects *messages;

+ (instancetype)conversationWithName:(NSString *)name
							 picture:(NSString *)picture;

@end
```

``` obj-c
+ (NSDictionary *)linkingObjectsProperties {
    return @{@"messages": [RLMPropertyDescriptor descriptorWithClass:FCMessage.class propertyName:@"conversation"]};
}
```

``` obj-c
@interface FCMessage : FCBaseEntity 
@property NSString *serverID;
@property NSString *text;
@property FCConversation *conversation;
@end

RLM_ARRAY_TYPE(FCMessage)
```

I try to catch changes on any FCConversation object :

``` obj-c
self.conversations = [[FCConversation objectsInRealm:[RLMRealm defaultRealm] withPredicate:nil] sortedResultsUsingProperty:@"lastMessageTime" ascending:NO];
	
	[self.realmNotificationToken stop];
	FCBlockWeakSelf
	self.realmNotificationToken = [self.conversations addNotificationBlock:^(RLMResults<FCConversation *> * _Nullable results, RLMCollectionChange * _Nullable change, NSError * _Nullable error) {
            [weakSelf.tableView beginUpdates];
            [weakSelf.tableView deleteRowsAtIndexPaths:[change deletionsInSection:0] withRowAnimation:UITableViewRowAnimationAutomatic];
            [weakSelf.tableView insertRowsAtIndexPaths:[change insertionsInSection:0] withRowAnimation:UITableViewRowAnimationAutomatic];
            [weakSelf.tableView reloadRowsAtIndexPaths:[change modificationsInSection:0] withRowAnimation:UITableViewRowAnimationAutomatic];
            [weakSelf.tableView endUpdates];
            [weakSelf showEmptyScreenIfNeeded];
	}];

```
And when I delete the last message, nothing happens. Notification block does not called
``` obj-c
NSPredicate *pred =  [NSPredicate predicateWithFormat:@"text == %@",@"Hello"];
RLMResults *result = [FCMessage objectsWithPredicate:pred];

RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[realm deleteObjects:result];
[realm commitWriteTransaction];

```

**Comment by bdash** [comment]
@smolskyaleksey, please file a new issue with any question you have, rather than asking on an unrelated, closed issue.
