### ISSUE TITLE
write failed in release

### ISSUE THREAD

**Issue by demoker** [realm/realm-cocoa#3858]
> **Questions**: Excuse me，I have a question about 
`-[RLMRealm commitWriteTransaction]` and `-[RLMRealm transactionWithBlock:]`。
When using the latter write failed in release, but success after the switch to the former, I don't know what reason is this, in the debug, both can be written to success.

These two methods have what need to be aware of when to use place?Please give advice or comments.Thanks.

> Realm version: latest
> Xcode version: latest
> iOS/OSX version: iOS 9.3
> language： OC

**Comment by TimOliver** [comment]
Hi @demoker!

Actually, `[RLMRealm transactionWithBlock]` is just a convenience wrapper around `[RLMRealm commitWriteTransaction]`. Here is its code straight from [RLMRealm.mm](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm.mm#L501):

```
- (BOOL)transactionWithBlock:(void(^)(void))block error:(NSError **)outError {
    [self beginWriteTransaction];
    block();
    if (_realm->is_in_transaction()) {
        return [self commitWriteTransaction:outError];
    }
    return YES;
}
```

I'm not sure why your attempt at using `[RLMRealm commitWriteTransaction]` would be failing. Are you able to see if there are any `NSError` objects being returned? 

If you are still having trouble, could you please post a copy of your source code here? Thanks!

**Comment by demoker** [comment]
```
- (void)updateBasicInfoWithCarId:(NSString *)carId basic:(LBRBasicInfoModel *)basicModel {
    __weak typeof(self) weakSelf = self;
    __weak LBRCarModel * car = [self fetchACarWithCarId:carId];
    [self.selfRealm transactionWithBlock:^{
        car.basic = basicModel;
        [LBRCarModel createOrUpdateInRealm:weakSelf.selfRealm withValue:car];
    }];
}
```
I'm sorry, that is my problem, I should not be used `__weak` modify the `car` to remove `__weak` in front of the `car`, with respect to ok,thanks! But why?It is ok in debug,not ok in release!

**Comment by bdash** [comment]
Once the last strong reference to an object is dropped, the object will be deallocated and any weak references will become `nil`. Since your `car` variable is weak, it does not keep the object returned by `[self fetchACarWithCarId:carId]` alive. The compiler can be more aggressive at optimizing out unnecessary retains in release builds than debug builds, so it's completely possible for the `car` variable to remain valid for some time in a debug build but to be immediately `nil` in an optimized release build.

**Comment by demoker** [comment]
@bdash ,excuse me . Can you help me look at the above the problem?thanks!

**Comment by bdash** [comment]
Please take a look at the [Threading](https://realm.io/docs/objc/latest/#threading) section of the Realm documentation for information about how Realm works when multiple threads are involved.
