### ISSUE TITLE
Test Swift 3 automatic migration of user code

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3862]
The Swift migrator isn't perfect yet. In [updating Realm Objective-C's Swift tests to Swift 3](https://github.com/realm/realm-cocoa/pull/3846), I faced quite a bit of difficulty guessing what the imported method name was. For example, `transactionWithBlock` was not automatically migrated to `transaction` because Objective-C declares both `transactionWithBlock:error:` (imported as `transaction(_:) throws`) and `transactionWithBlock:` (imported as `transaction(_:)`) even if the second is marked as unavailable. I faced similar problems with other throwing functions, and this issue is tracked by [SR-2026](https://bugs.swift.org/browse/SR-2026).

We should determine what other pain points may exist and take steps to mitigate user problems, whether that be by using different annotations (`NS_REFINED_FOR_SWIFT` instead of `NS_SWIFT_UNAVAILABLE`) or providing migration documentation.

**Comment by austinzheng** [comment]
This issue is probably less relevant to our users now that we've dropped Swift 2 support.
