### ISSUE TITLE
Should async handover support Realm collections?

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3863]
Is there a compelling use case for supporting async handover of Realm collections? https://github.com/realm/realm-cocoa/pull/3828 only pertains to handover of Realm objects, but a logical extension is to support collections as well. There isn't however an easy way to expose such functionality without majorly complicating the API, so maybe it isn't something we should add unless there's a compelling reason?

**Comment by JadenGeller** [comment]
If we are to support it, we ought to decide on the API.

### 1. `RealmBoundObject` Protocol

My first thought was to introduce a protocol `RLMRealmBoundObject` (name pending) that `RLMObject`, `RLMArray`, `RLMResults`, and `RLMLinkingObjects` all conform to. This works well except in the Swift case of passing multiple objects that are *not* all `RLMObject`s.
```swift
func async<O: RealmBoundObject>(handingOver objects: [O], execute block: (Realm, [O]) -> ())
```
Here, a user cannot pass both an `RLMArray` and an `RLMObject` since `O` will not unify to the existential `RealmBoundObject`. We could have to introduce an additional (hopefully not ambiguous) overload.
```swift
func async(handingOver objects: [RealmBoundObject], execute block: (Realm, [RealmBoundObject]) -> ())
```
Note that we would not want to replace the former function with the latter since the latter will *always* require additional casting while the former will often not.

### 2. Collection Overloads

We could alternatively just introduce overloads that take in a single Realm collection. This would be a reasonably simple to understand API, but would probably result in more overloads than the former solution. Further, users would be unable to pass multiple collections or a mixture of collections and objects, and there would be no way for them to implement this on top of what we've built.

**Comment by JadenGeller** [comment]
//cc @bigfish24

**Comment by bigfish24** [comment]
I am in favor of #1

**Comment by JadenGeller** [comment]
I just checked, and it turns out the function overloads discussed in 1 are ambiguous… 😞 If we want 1 still, we need to give the existential method a different name… Thoughts @bigfish24?

**Comment by JadenGeller** [comment]
@austinzheng Do you have any clever workaround for the ambiguity here? If not, what do you suggest?

**Comment by austinzheng** [comment]
What's wrong with just having the second API in option 1? (What's the use case for enforcing homogeneity again?)

**Comment by JadenGeller** [comment]
@austinzheng With only the existential API, users will *always* have to cast from the existential to the correct type. With the protocol constrained generic API, users will often not need to cast.

**Comment by austinzheng** [comment]
I see. I'll think about it. (I guess we don't want to go the cowards' route of just giving the methods slightly different names 😛.)

**Comment by JadenGeller** [comment]
I don't think that it's necessary a bad idea to do that.

**Comment by JadenGeller** [comment]
Potential solution! If we mark `RealmBoundObject` as `@objc`, it's existential will conform to `RealmBoundObject`. This means that two unrelated classes that conform to `RealmBoundObject` can be passed in the generic constraint API!

Unfortunately, you have to give the type checker needs some help in this case, but that's totally reasonable for the advanced use case of passing unrelated types. We should definitely document this though.
```swift
async(handingOver: [results, person] as [RealmBoundObject]) { realm, collection in … }
```
Again, in the case where everything in the array is of a common superclass, no type checker hints are necessary.

What're your thoughts, @austinzheng?

**Comment by austinzheng** [comment]
Oh, that's clever. And given that `RealmBoundObject` is only supported for the `NSObject`-based classes we define, the `@objc` annotation shouldn't affect anything else.

**Comment by JadenGeller** [comment]
Exactly! And hopefully by the time we get a pure Swift API (like a bazillion years from now), Swift will conform its existential to their relevant protocol.

**Comment by JadenGeller** [comment]
Sounds like we'll go with the `@objc protocol RealmBoundObject { }` API.
