### ISSUE TITLE
Eventually merge breaking changes into master

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3864]
Since we don't want to introduce API-breaking changes except in large releases, we should track such issues or PRs here.
- [Annotate nullability for RLMRealm_Dynamic.h](https://github.com/realm/realm-cocoa/pull/3855)
- [Improve consistency add/delete methods on RLMReam](https://github.com/realm/realm-cocoa/pull/3836)
- [Automatically ignore computed properties when building schema](https://github.com/realm/realm-cocoa/pull/3870)

**Comment by JadenGeller** [comment]
Please add new changes by editing the issue rather than by adding new comments.

**Comment by austinzheng** [comment]
Closing, since all 3 linked PRs have long been merged.

**Comment by austinzheng** [comment]
This was closed erroneously.

**Comment by austinzheng** [comment]
All three of these changes have been merged into our `master-3.0` branch.

Better naming for API: https://github.com/realm/realm-cocoa/pull/5189
Detect computed properties: https://github.com/realm/realm-cocoa/pull/5160
Nullability on dynamic API: (already in)
