### ISSUE TITLE
RLMResults ordering is not stable when deleting objects

### ISSUE THREAD

**Issue by oldpotter** [realm/realm-cocoa#3865]
## Goals

删除某一行数据后，数据表中的最后一行数据会移动到删除这一行上来了。同时监听到了chang.insertion的新增数据通知。

## Code Sample
1:生成一些数据
[[RLMRealm defaultRealm] transactionWithBlock:^{
        for (int i = 0; i < [self randomString].count ; i++) {
            
            Model *model = [[Model alloc] initWithValue:@[
                                                          [NSString stringWithFormat:@"%d",i],
                                                          @(YES),
                                                          [NSString stringWithFormat:@"%d条数据",i],
                                                          [NSDate date]
                                                          ]];
            [Model createInDefaultRealmWithValue:model];
        }
    }];

2:删除中间的某一行数据
RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    RLMResults<Model *> *results = [Model allObjects];
    [realm deleteObject:results[20]];
    [realm commitWriteTransaction];

3:查看数据表会发现，表中最后一行数据被移动上来了。使用监听时同时出现了删除和新增数据的通知
Realm version: 1.0.1

Xcode version: 7.3。1

iOS/OSX version: 9.3

Dependency manager + version: ?

**Comment by TimOliver** [comment]
Hi there @oldpotter! Sorry for the reply in English; I cannot speak Chinese unfortunately.

From what I can gather, you're having trouble with the Realm change notifications not reporting the insertion/deletions that you were expecting. Is that correct?

Are you able to post more of your code here? Thanks a lot!

**Comment by talisk** [comment]
I'm a developer from China. I translated issue from @oldpotter. Hoping this helps. ^_^

# Description
When you delete a record, the last line will move to the deleted location, and will receive chang.insertion notification.

# Code Sample
**Step1: Create some data.**
``` objc
[[RLMRealm defaultRealm] transactionWithBlock:^{
for (int i = 0; i < [self randomString].count ; i++) {
        Model *model = [[Model alloc] initWithValue:@[
                                                      [NSString stringWithFormat:@"%d",i],
                                                      @(YES),
                                                      [NSString stringWithFormat:@"No.%d",i],
                                                      [NSDate date]
                                                      ]];
        [Model createInDefaultRealmWithValue:model];
    }
}];
```

**Step2: Delete a record.**
``` objc
RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
RLMResults *results = [Model allObjects];
[realm deleteObject:results[20]];
[realm commitWriteTransaction];
```

**Step3: Check Realm Browser and you will find the last record has been moved to the location which stored the deleted one's. At the same time, you can receive the `delete` and `add` notifications.

# Environment
Realm version: 1.0.1
Xcode version: 7.3.1
iOS/OSX version: 9.3
Dependency manager + version: ?

**Comment by jpsim** [comment]
Hi all, this is actually the intended behavior. To make efficient use of space and other general performance implications, RLMResults aren't guaranteed to preserve their sort order after deletions.

See our docs on [Queries->Sorting](https://realm.io/docs/objc/latest/#sorting):

> Note that the order of `Results` is only guaranteed to stay consistent when the query is sorted. For performance reasons, insertion order is not guaranteed to be preserved. If you need to maintain order of insertion, some solutions are proposed [here](https://realm.io/docs/objc/latest/#realm-doesnt-have-auto-incrementing-properties).
