### ISSUE TITLE
Unable to update Realm to 1.0.2

### ISSUE THREAD

**Issue by rickkaye** [realm/realm-cocoa#3871]
## Goals

What do you want to achieve?

Update to Realm 1.0.2

## Expected Results

What did you expected to happen?

I expected to be able to run my app

## Actual Results

What did happened instead?  
App won't build - On the import RealmSwift line I get the error No Such Module RealmSwift
## Steps to Reproduce

What are steps we can follow to reproduce this issue?

I downloaded Realm 1.0.1 today from the link on the Getting Started section of your web site. I created an app and it worked fine. When I looked in the console, I had a message that Realm 1.0.2 was available. Sure enough I went to the Getting Started page and the link now pointed to version 1.0.2. I downloaded it and followed the instructions to add the frameworks to my project the same way I did with the previous versions except I first deleted the old frameworks from the project. Now the project won't compile. It just gives me the "No Such Module RealmSwift" error.

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.0.2 Swift

Xcode version:  7.3.1

iOS/OSX version: OS X 10.11.5

Dependency manager + version: None

**Comment by TimOliver** [comment]
Hi there @rickkaye! Thanks for the issue!

Sorry to hear you've been having trouble with updating Realm. We've seen similar error messages here before, but they can usually be caused by several different reasons.

Here are some things for you to try out to see if it fixes it:
* Make sure to do a full 'Clean' of your project.
* When you dragged the framework into your project, make sure 'Copy items if needed' was checked.
* If worse comes to worse, delete Realm completely from your project and try again from scratch.

Let me know how you go!

**Comment by rickkaye** [comment]
Actually, I had tried all of those things before posting my problem. In addition, I had tried deleting all derived data in Xcode. But none of that worked.

After my post, I created a new project, installed Realm 1.0.2 from scratch, and then copied all of the source files from my old project to the new one. That worked. The only problem with that is I lost my source control history. I have still not been able to get the original project to compile.

Someday, you will release Realm 1.0.3. It would be helpful if you posted instructions on how to upgrade the version of Realm in an existing project alongside the instructions you have for installing Realm in a new project. I’m sure I did something wrong to cause the problem but I can’t figure out what it could have been.

**Comment by TimOliver** [comment]
Ah, okay! I'm glad to hear you got it working, but it's not ideal that you had to migrate your project to get it working.

I'm still somewhat perplexed as to what could have caused this. Usually updating Realm in your project (If you're not using CocoaPods or Carthage) is simply a matter of downloading the new version and simply drag-dropping the new  `Realm.framework` and `RealmSwift.framework` files straight over the old ones in your project folder, replacing them. There's usually no configuration required within your app itself.

No problems. We're reviewing our installation instructions at the moment to see how we can improve them, so we'll take this into consideration. Thanks!

**Comment by rickkaye** [comment]
I guess that’s why the procedure needs to be documented. I did not drag the framework files into the project folder. I dragged them into the Xcode Embedded Binaries settings, the same way I had installed the earlier version. I don’t know if that is what caused the problem. But, in the absence of instructions, either way seems reasonable.

**Comment by TimOliver** [comment]
Normally you can't overwrite a framework by dragging a replacement over it; Xcode will return an error. You need to manually delete the ones in Embedded Binaries beforehand, and then do it.

If it did actually go through, it meant "Copy items if needed" wasn't checked, and an external reference to the framework was created (Which would most likely cause the error you described).

Either way, we'll keep it in consideration as we improve our installation instructions. Thanks!

**Comment by rickkaye** [comment]
Sorry, I forgot to mention that’s exactly what I did. I deleted the old frameworks through the Xcode interface (selected them and clicked on the “-“), then dragged in the new ones.
