### ISSUE TITLE
Swift 3 / Xcode 8 issues

### ISSUE THREAD

**Issue by slynglen** [realm/realm-cocoa#3872]
Hello there

I encounter some issues when trying to build for Swift 3 using Xcode 8.

![skaermbillede 2016-07-14 kl 10 36 39](https://cloud.githubusercontent.com/assets/3939917/16833300/fa4b3ae0-49ae-11e6-8116-b9c30b7ccade.png)

**Comment by JadenGeller** [comment]
There error messages look like changes made in https://github.com/realm/realm-cocoa/pull/3817/files and https://github.com/realm/realm-cocoa/pull/3815 and https://github.com/realm/realm-cocoa/pull/3818. Those errors are what I'd expect to see if RealmSwift was compiled with an older version of Realm. Can you provide info about your configuration?

**Comment by AEugene** [comment]
Same here. Xcode 8.0 beta 2 (8S162m), CocoaPods 1.0.1
```
CHECKOUT OPTIONS:
  RealmSwift:
    :commit: 3a53bdc97a8ccf200cc032f32b7cff60e408992b
    :git: https://github.com/realm/realm-cocoa.git
```

**Comment by JadenGeller** [comment]
Are you compiling with Swift 2.3 (legacy) or Swift 3?

**Comment by jpsim** [comment]
When using a custom branch of `realm-cocoa` in CocoaPods, you must have the same commit of both the `Realm` pod and `RealmSwift` pod.

For example:

```ruby
  pod 'Realm', git: 'git@github.com:realm/realm-cocoa.git', branch: 'master'
  pod 'RealmSwift', git: 'git@github.com:realm/realm-cocoa.git', branch: 'master'
```

**Comment by AEugene** [comment]
@jpsim You're right  `pod 'Realm'` was behind latest commit. Clearing `Podfile.lock` resolved the issue.

**Comment by jpsim** [comment]
Glad to hear it @AEugene!
