### ISSUE TITLE
Compiler issue with Xcode 8 Beta 2 (RealmSwift 1.0.2)

### ISSUE THREAD

**Issue by gavinb80** [realm/realm-cocoa#3873]
I've recently upgraded to Xcode Beta 2 and used CocoaPods to update to Realm 1.0.2 but have 2 errors I am having difficulty with:

/Users/gavinbeard/Documents/TestApp/Pods/RealmSwift/RealmSwift/Object.swift:70:2: Use of unresolved identifier 'RealmSwiftObject'

And

/Users/gavinbeard/Documents/TestApp/Pods/RealmSwift/RealmSwift/Object.swift:70:1: Expressions are not allowed at the top level

Which is this line of code:

`(RealmSwiftObject)`

The second error is:

/Users/gavinbeard/Documents/TestApp/Pods/RealmSwift/RealmSwift/Realm.swift:96:5: Self.init isn't called on all paths before returning from initializer

Which relates to this block of code:

```
    public convenience init(fileURL: URL) throws {
        var configuration = Configuration.defaultConfiguration
        configuration.fileURL = fileURL
        try self.dynamicType.init(configuration: configuration)
    }
```
Appreciate its just a beta version of Xcode, but wonder if there is a quick fix I can apply until an official update?

**Comment by bdash** [comment]
Realm's support for Swift 3 is still very much a work in progress. To try it out you'll need to use Realm Swift from master, rather than any of our released versions. You can do this by updating your Podfile to include the following:

    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master'
    pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master'

**Comment by marchy** [comment]
What about support for Swift 2.3? That's supposed to be way less impactful. Or are you guys not planning on supporting 2.3?

**Comment by jpsim** [comment]
@marchy Swift 2.3 support couldn't be added for Xcode 8 beta 1 due to an Xcode bug, but I just pushed a PR for 2.3 support here: #3882.

**Comment by marchy** [comment]
@jpsim fantastic thanks for the update JP. Will try once it gets merged

**Comment by bolom** [comment]
the master branch works with Xcode beta 3 ?

**Comment by bdash** [comment]
Yes, it should as of #3896.
