### ISSUE TITLE
Realm/RLMConstants.h:150:1: 'swift_name' attribute cannot be applied to this declaration

### ISSUE THREAD

**Issue by wells1013** [realm/realm-cocoa#3876]
```
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42

/Applications/Xcode.app/Contents/Developer
Xcode 7.1.1
Build version 7B1005

/usr/local/bin/pod
0.39.0
Realm (1.0.2)
Realm (~> 1.0.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)


(not in use here)

/usr/bin/git
git version 2.4.9 (Apple Git-60)
```
use objc, no swift

![image](https://cloud.githubusercontent.com/assets/5172252/16861795/b9b28f92-4a76-11e6-944c-f16728437512.png)

![image](https://cloud.githubusercontent.com/assets/5172252/16861772/7a0c2506-4a76-11e6-959b-6169e9bfcf22.png)

**Comment by JadenGeller** [comment]
I'm guessing that Xcode 7.1.1 didn't support `swift_name` as fully as Xcode 7.3.1. Any reason you're not using the latest version?

**Comment by JadenGeller** [comment]
There's no way to fix this with `#ifdef` since `NS_SWIFT_NAME` is defined, just not valid in all the same places. If we care to maintain backwards compatibility with older versions of Xcode (do we? //cc @bdash), we probably need to roll back https://github.com/realm/realm-cocoa/pull/3818.

**Comment by bdash** [comment]
We [bumped the minimum Xcode version to 7.3 with v0.103.0](https://realm.io/news/realm-objc-swift-0.103.0/). Realm Swift hasn't worked with anything older since that point. It's possible that Realm Objective-C has worked with older versions of Xcode until now, but if so it's by luck as it's not something we test or support.

**Comment by JadenGeller** [comment]
Well, sounds like you can resolve your issue @wells1013 by updating Xcode 🙂
