### ISSUE TITLE
Errors with RealmSwift 1.0.2 (Xcode 7.3.1)

### ISSUE THREAD

**Issue by snahedis** [realm/realm-cocoa#3878]
I wanted to update Realm but I got lot of errors as `collection_notifications.hpp file not found`
Here is a screen : https://www.dropbox.com/s/w0gwvafzic13m07/Capture%20d%27%C3%A9cran%202016-07-15%2012.55.49.png?dl=0

Realm version: 1.0.2
Xcode version: 7.3.1
iOS/OSX version:  iOS 9.3
Dependency manager + version:  cocoapods 1.0.0

As I seem to be the only one with those issues it's probably my fault, I don't known, any ideas ?

**Comment by stel** [comment]
Please try to upgrade cocoapods to the latest version (1.0.1), remove Pods directory and install all pods again. Also try to clean cocoa pods cache with `pod cache clean --all` command before installing.

**Comment by snahedis** [comment]
Upgrade cocoapods solved the problem. Thanks a lot :)

**Comment by stel** [comment]
Awesome!
