### ISSUE TITLE
'swift_name' attribute cannot be applied to this declaration

### ISSUE THREAD

**Issue by pjebs** [realm/realm-cocoa#3879]
This error only occurred recently. Previously it was working fine. I just did a pod update.

`pod 'Realm'`

Compiler error: RLMConstants.h

/Developer/Projects/XXX/Pods/Realm/include/RLMConstants.h:150:1: 'swift_name' attribute cannot be applied to this declaration

/Developer/Projects/SkyLovely-iOS-External/Pods/Realm/include/RLMConstants.h:166:1: 'swift_name' attribute cannot be applied to this declaration

**Comment by pjebs** [comment]
I can see the issue was addressed here: https://github.com/realm/realm-cocoa/issues/3876

I'm still using XCode 7.2. How do I change the pod config to the tag: 0.102.1 presumeably

**Comment by pjebs** [comment]
In the "cocoapods" documentation installation section, it doesn't give correct line.
https://realm.io/docs/objc/0.102.1/

**Comment by stel** [comment]
You can specify `pod 'Realm', '~> 0.102.1'` in your `Podifile` to use `0.102.1` version, but I would suggest you to upgrade Xcode to the latest version.

**Comment by pjebs** [comment]
I can't run XCode 7.3. 7.2 is my limit.

**Comment by stel** [comment]
Ok I see, so is your problem resolved by specifying an older version?

**Comment by bdash** [comment]
@pjebs, can you elaborate on why you're forced to use Xcode 7.2?

**Comment by pjebs** [comment]
Computer not fast enough for requisite macosx

**Comment by JadenGeller** [comment]
Ah, Xcode 7.3 dropped support for macOS Yosemite.

**Comment by tgoyne** [comment]
10.11 did not change the system requirements from 10.10 and from what I've heard is actually faster on older hardware. 10.12 is the first version since 10.8 to actually drop support for older models.

**Comment by JadenGeller** [comment]
Anyway, sounds like this issue is resolved.

@pjebs It doesn't compile because you're using an unsupported version of Xcode. Either use an older version of Realm or upgrade OS X and Xcode (better solution!).
