### ISSUE TITLE
obj-c Realm Bug

### ISSUE THREAD

**Issue by xorshine** [realm/realm-cocoa#3880]
> **Bugs**: 
I found a bug on objective - c Realm, someone is proposed.Now I tell you how to reproduce this bug: through a for loop, create some data stored, and then removes the first element of the database, you will find that the last element will be moved to the location of the first element.Please take a look at this bug.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals
Element position should not be changed
## Expected Results
Element position should not be changed
## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

through a for loop, create some data stored, and then removes the first element of the database, you will find that the last element will be moved to the location of the first element.Please take a look at this bug.

## Code Sample

 RLMResults <0x7be70c00> (
	[0] GSUploadInfo {
		fileName = 查良镛1;
		MIMEType = txt;
		localPath = zly.realm;
		fileUUID = 282DE6EF-F5AF-4078-9D66-F13280DDCEA1;
		servicerAddress = 192.168;
		uploadDate = 2016-07-16 09:13:20 +0000;
		uploadState = 100;
		fileSize = 0;
		uploadOffset = 0;
		progress = 0;
	},
	[1] GSUploadInfo {
		fileName = 金庸永恒;
		MIMEType = doc;
		localPath = /d/jy.doc;
		fileUUID = 78A97F2D-F9A5-4E9C-80EC-A287D2B298FE;
		servicerAddress = (null);
		uploadDate = 2016-07-16 09:05:38 +0000;
		uploadState = 100;
		fileSize = 0;
		uploadOffset = 0;
		progress = 0;
	},
	[2] GSUploadInfo {
		fileName = 查良镛;
		MIMEType = txt;
		localPath = zly.realm;
		fileUUID = 4EAC5791-0959-4883-9D11-96A81604B1BB;
		servicerAddress = 192.168;
		uploadDate = 2016-07-16 09:13:07 +0000;
		uploadState = 100;
		fileSize = 0;
		uploadOffset = 0;
		progress = 0;
	}
)

  GSUploadInfo * info = [[GSUploadInfo objectsInRealm:GSUploadRealm() where:@" fileName = '查良镛1' "] lastObject];
 
            [GSUploadRealm() transactionWithBlock:^{
                [GSUploadRealm() deleteObject:info];
            }];
    
    NSLog(@"%@",[[GSUploadInfo allObjectsInRealm:GSUploadRealm()] description]);

[0] GSUploadInfo {
		fileName = 查良镛;
		MIMEType = txt;
		localPath = zly.realm;
		fileUUID = 4EAC5791-0959-4883-9D11-96A81604B1BB;
		servicerAddress = 192.168;
		uploadDate = 2016-07-16 09:13:07 +0000;
		uploadState = 100;
		fileSize = 0;
		uploadOffset = 0;
		progress = 0;
	}
[1] GSUploadInfo {
		fileName = 金庸永恒;
		MIMEType = doc;
		localPath = /d/jy.doc;
		fileUUID = 78A97F2D-F9A5-4E9C-80EC-A287D2B298FE;
		servicerAddress = (null);
		uploadDate = 2016-07-16 09:05:38 +0000;
		uploadState = 100;
		fileSize = 0;
		uploadOffset = 0;
		progress = 0;
	},
	

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.0

Xcode version: 7.3

iOS/OSX version: 8.4

**Comment by bdash** [comment]
This is expected behavior. Objects of a given type are not stored with any inherent order. You can achieve ordering in two different ways:

1. Sort the objects when fetching them from the Realm.
2. Store the objects in a `RLMArray` property of another class. Arrays are inherently ordered.

**Comment by xorshine** [comment]
Thank you very much.Believe Realm will be better.
