### ISSUE TITLE
Calculate the count is very slow

### ISSUE THREAD

**Issue by skarctop** [realm/realm-cocoa#3881]
RLMResults *result = [Filter_model objectsWhere:@"XXX"];
    NSInteger count = result.count
The model storage 2000 line data, Ten times slower than the sqlite！！！！

**Comment by bdash** [comment]
Can you please share the definition of the model class that you're filtering, and the predicate string you're filtering on? They're both important aspects in understanding the performance of the code you have provided.

**Comment by skarctop** [comment]
Filter_model  
@interface Filter_model : RLMObject
@property (nonatomic, assign) NSInteger id;
@property (nonatomic, copy) NSString *target_lsku;
@property (nonatomic, copy) NSString *target_output;
@property (nonatomic, copy) NSString *target_ssd_id;
@property (nonatomic, copy) NSString *target_type;
@end

Realm Count  
     
    RLMResults *result = [RealmRequest_filter objectsWhere:[NSString stringWithFormat:@"target_lsku == '%@'",target_lsku]];
     count = result.count;

FMDB Count  
```
NSString *sql = [NSString stringWithFormat:@"SELECT count(*) as request_count FROM requests_filtered_view WHERE target_lsku IN (%@)",
                     target_lsku];
FMResultSet *rs = [db executeQuery:sql withArgumentsInArray:args];
while (rs.next) {
        count = [rs intForColumn:@"request_count"];
}
```
      
I need found the count, but result ten times slower than the sqlite.  
why! 
 what is the problem with my code?

**Comment by bdash** [comment]
Can you please also share the schema definition of the `requests_filtered_view` table used in your SQLite example for sake of comparison?

**Comment by bdash** [comment]
A few more questions after experimenting with this myself:
* What do the values in `target_lsku` typically look like?
* How many matches do you expect the query to produce?
* How long is the query taking in Realm? How long with SQLite?

In my experiment I used the model as you provided above. I then populated the Realm with 50,000  instances of `Filter_model`, with the `target_lsku` property of each object set to 1400 bytes of random data. I then measured the time taken to evaluate `[Filter_model objectsWhere:@"target_lsku == %@", needle].count`, where `needle` was a string taken from the `target_lsku` property on one of the objects. On an iPhone 6 Plus, computing the number of matching objects takes < 50ms. If I add an index on the `target_lsku` property:

```objc
@implementation Filter_model
+ (NSArray *)indexedProperties { return @[ @"target_lsku" ]; }
@end
```

the time taken to count the matching objects drops to ~2ms.

**Comment by skarctop** [comment]
Thank for your answer  
* 'target_lsku' was a string
* maybe one or zero
* Realm about 32s, SQLite about 3s
Here are many query requests  
I have tryed add 'indexedProperties', but still as before.

**Comment by bdash** [comment]
Are you able to share the exact code and Realm file you're testing with? 32 seconds is an incredibly long time for any query so I'm very curious what you're doing that takes so long.

**Comment by bdash** [comment]
> `target_lsku` was a string.

What is the typical length of the values stored in this property? Are the values similar between objects (the same except for a small number of characters), or do they vary significantly from object to object?

**Comment by skarctop** [comment]
'target_lsku' about 15 characters in length.
'target_lsku' values are very similar such as 'P160607002' and 'P160607003'  

Take so long, beacause query about Sixty thousand.

**Comment by bdash** [comment]
As I mentioned, my test with 50,000 objects with much larger strings showed the matching and counting taking < 50ms. Updating it to use strings of the same size as your examples makes it take < 10ms. If you're seeing the same operation take 32 seconds, something else is going on. You'll need to share more information for us to be able to help understand why it's taking so long. Can you share the code you're using to measure the performance and the Realm file you're querying? Can you share an Instruments trace covering the time spent performing the query? Can you share which Realm version you're using?

**Comment by skarctop** [comment]
but when write like this, become very soon.
```
__block NSInteger number = count;
dispatch_async(dispatch_get_main_queue(), ^{
    number = [RealmRequest_filter objectsWhere:[NSString stringWithFormat:@"target_lsku == '%@'",target_lsku]].count;
});
return number;
```

**Comment by skarctop** [comment]
![image](https://ooo.0o0.ooo/2016/07/19/578defcc58b2b.png)

**Comment by bdash** [comment]
The screenshot only shows a small subset of the stack trace. Can you share the full Instruments trace? If you'd like to keep it private you can share it via email to help@realm.io.

**Comment by bdash** [comment]
The part of the stack trace that is visible does show that the time is being spent in opening the Realm, not evaluating the query. That makes a little more sense. Will need to see the full trace in order to understand why it's taking so long as opening a Realm is typically very quick.

**Comment by skarctop** [comment]
![screen.png](https://ooo.0o0.ooo/2016/07/19/578e604834571.png)

**Comment by bdash** [comment]
@skarctop, I _really_ want to help you, but if you're not willing to share the information I've asked for it's simply not possible to.

As I mentioned previously, a screenshot of a small part of the Instruments trace isn't sufficient for us to understand what's causing opening the Realm to take as long as it is. We need to see the full Instruments trace. If you don't want to share it publicly you can email it to us privately at help@realm.io. We'll be more than happy to investigate the problem once you've shared the Instruments trace.

**Comment by skarctop** [comment]
One
```
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
config.readOnly = YES;
RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:nil];
return [RealmRequest_filter objectsInRealm:realm where:[NSString stringWithFormat:@"target_lsku == '%@'",target_lsku]].count;
```
Two
```
RLMRealm *realm = [RLMRealm defaultRealm];
return [RealmRequest_filter objectsInRealm:realm where:[NSString stringWithFormat:@"target_lsku == '%@'",target_lsku]].count;
```

One about 10s but Two spend 30s  

![Screen.png](https://ooo.0o0.ooo/2016/07/19/578e72e181b7a.png)
Query operation is carried out within the thread3, as if the reason for the thread

**Comment by jpsim** [comment]
@skarctop very curious as to why you closed this? Did you determine the cause of the long open time? The generic screenshot of Instruments you posted doesn't show much, other than you have a busy GCD worker thread. Doesn't even show anything Realm related.

**Comment by weiminghuaa** [comment]
I'm looking for this. Is realm has method to query only count of data like sql "SELECT count(*) as request_count FROM table WHERE name = xx"?

**Comment by Kirow** [comment]
@weiminghuaa `[table objectsWhere:@"name = 'xx'" ].count`

**Comment by weiminghuaa** [comment]
@Kirow I know. Is this way cause  query slow. In sqlite, it's not need query all data from db.

**Comment by Kirow** [comment]
@weiminghuaa, In my app I have 90k+ records in main table & ~2k in linked tables, not simple query by text like "object.field1 CONTAINS[c] %@ OR name CONTAINS[c] %@ OR ANY objectArray.name = %@". On my iphone5s it takes 0.279722s to process query & 0.000121s to get count. In this test sample I used "ap" input and got 5746 records in result (if this matters). 
So I can not say that it is slow.

**Comment by jpsim** [comment]
@weiminghuaa `[table objectsWhere:@"name = 'xx'" ].count` _is_ an optimized operation to get just the number of objects matching the query. It's generally a faster operation than accessing resulting objects from that query.
