### ISSUE TITLE
 can't find Realm static framework

### ISSUE THREAD

**Issue by xorshine** [realm/realm-cocoa#3887]
Realm of installation directory static framework cannot run the demo, because can't find a static framework.How to download the Realm only static framework? 

Realm version: 1.0.2

Xcode version: 7.3

**Comment by jpsim** [comment]
Sorry @xorshine, I can't quite understand what problem you're experiencing.

If you're referring to running the demo apps, here's a short screencast showing you how to do this:

[realm_static_example.mp4.zip](https://github.com/realm/realm-cocoa/files/374497/realm_static_example.mp4.zip)

**Comment by kishikawakatsumi** [comment]
I'll close this issue for now due to of inactivity. @xorshine if you can provide some more info please feel free to reopen this issue, thanks!
