### ISSUE TITLE
Date String dd/mm/yyyy comparison not accurate

### ISSUE THREAD

**Issue by themythIOS** [realm/realm-cocoa#3888]
## Goals

What do you want to achieve?
>I have list of dates inside swift realm db
>I want to get list of dates that met filter condition:

In Apple swift 
 if("30/5/2015" > "19/07/2016"){
            print("ERROR")
        }
        else{
            print("CORRECT")
        }
IT MUST BE ERROR

but in 

let Query = try!Realm().objects(date_Realm).filter({$0.EventDate >= "\(todaysDate)"})
it accepts this condition.

## Expected Results
RESULT must return any date that is greater or equal from today.

What did you expected to happen?
get all data that met the condition
## Actual Results
Actual Result> it always has 1 date that does not met the condition.
WHY? it accepts the wrong. and put it on results. 

What did happened instead?  
e.g. the stack trace of a crash

No crash.  The result has wrong number of result.

## Steps to Reproduce

Step1:
have a collection of date in realm.

with this format but all are strings.
MM/dd/yyyy.

Step 2: filter today date and convert to String. (dateFromString)

Step 3: filter all those dates from today. (Events >= today)

What are steps we can follow to reproduce this issue?

## Code Sample
//todaysDate is MM/dd/yyyy

 let Query = try!Realm().objects(events_Realm).filter({$0.EventDate >= "\(todaysDate)" })

## Version of Realm and Tooling
latest version as of today. 

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ? 1.0.2

Xcode version: ? 7.3

iOS/OSX version: ? 10.11.5 El Capitan

Dependency manager + version:  cocoapod 1.0.1

**Comment by themythIOS** [comment]
I see.. im using the wrong date format... I need to use this.. yyyy-MM-dd'T'HH:mm:ss.sssZ for better result.

**Comment by bdash** [comment]
Note that in your code you're not even using Realm's filtering. You're using Swift's.
```swift
try! Realm().objects(events_Realm).filter({$0.EventDate >= "(todaysDate)" })
```
The version of `filter` that takes a closure is provided by `SequenceType`, and produces an `Array<T>`. Realm Swift's filtering takes a predicate format string, and returns a live-updating `Results<T>`.
