### ISSUE TITLE
Can't build realm-swift using Xcode 8 beta 3

### ISSUE THREAD

**Issue by bendodson** [realm/realm-cocoa#3895]
## Goals

Build Realm.framework and RealmSwift.framework for Swift 2.3 using xcode-build with Xcode 8 beta 3

## Expected Results

Compile with no errors

## Actual Results

Compilation fails with the following:

	=== BUILD TARGET Realm OF PROJECT Realm WITH CONFIGURATION Release ===

	Check dependencies
	No signing certificate 'iOS Development' found:  No 'iOS Development' signing certificate with a private key was found.

	** BUILD FAILED **

## Steps to Reproduce

Run `./build.sh build` using the latest version of code from master whilst using Xcode 8 beta 3.

## Version of Realm and Tooling

	ProductName:	Mac OS X
	ProductVersion:	10.11.5
	BuildVersion:	15F34

	/Applications/Xcode 8.0.app/Contents/Developer
	Xcode 8.0
	Build version 8S174q

	/usr/local/bin/pod
	1.0.0.rc.1
	(not in use here)

	/bin/bash
	GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

	/usr/bin/git
	git version 2.8.4 (Apple Git-73)

**Comment by jpsim** [comment]
The Xcode 8 betas introduced and subsequently removed the need to codesign iOS frameworks.

You'll need to change the team used for code signing for each target via Xcode's target editor prior to running `build.sh build`.

The changes and conversations in #3801 should help shed more light on this for you.

**Comment by bendodson** [comment]
I wasn't able to get the build to work after manually setting code signing (issues with Swift compatibility) but the fix in pull request #3896 has resolved everything. Thanks for the quick support.
