### ISSUE TITLE
How to use MTLModel protocol with Realm

### ISSUE THREAD

**Issue by skarctop** [realm/realm-cocoa#3900]
Realm and MTLModel protocol how to work together .
No information can be found

**Comment by Kirow** [comment]
Never tried Mantle with Realm, but you can try https://github.com/matthewcheok/Realm-JSON

**Comment by mrackwitz** [comment]
Mantle requires to inherit from `MTLModel`, while with Realm you're bound to the superclass `RLMObject`. You can't combine these two. But as @Kirow already points out, you can use [Realm-JSON](https://github.com/matthewcheok/Realm-JSON) instead, which allows you to declare your JSON mapping with a similar API.

**Comment by jpsim** [comment]
Actually, Mantle now includes an `MTLModel` protocol. Here's a segment from their docs:

> The [new `<MTLModel>` protocol](https://github.com/Mantle/Mantle/pull/219) represents the basic behaviors expected from any model object, and can be used instead of the `MTLModel` class when inheritance is impossible, or to create more generic APIs.
>
> For example, `<MTLModel>` conformance can be added to the objects from other persistence frameworks in order to use those objects in conjunction with Mantle’s adapters.
>
> Accordingly, `MTLJSONAdapter` has been updated to only depend on `<MTLModel>` conformance, and no longer requires a `MTLModel` subclass in order to serialize or deserialize from JSON.

Source: https://github.com/Mantle/Mantle/blob/master/CHANGELOG.md#mtlmodel-protocol

**Comment by stel** [comment]
@skarctop do you need any further help with this or could we close this issue?

**Comment by stel** [comment]
Will close it for now because of inactivity, @skarctop feel free to reopen it or open a new issue if you need any help.
