### ISSUE TITLE
Got stuck on Downloading dependency: core 1.3.1 

### ISSUE THREAD

**Issue by aelam** [realm/realm-cocoa#3904]
## Goals

Install Realm, not Realm-Swift 

## Expected Results

Install successfully

## Actual Results

Same with #2240 
I've got stuck at Downloading dependency: core 1.3.1.

```
pod install --no-repo-update --verbose

Preparing
[!] Unable to load a specification for the plugin /Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0

Analyzing dependencies

Inspecting targets to integrate
Using ARCHS setting to build architectures of target Pods: () Using `ARCHS` setting to build architectures of target `Pods-PackageCLI`: ()
Using ARCHS setting to build architectures of target Pods-PackageDecode: () Using `ARCHS` setting to build architectures of target `Pods-PackageCLITest`: ()

Finding Podfile changes

Expecta
MSPackageManager
Specta
Fetching external sources
-> Fetching podspec for MSPackageManager from ../

Resolving dependencies of Podfile

Comparing resolved specification to the sandbox manifest
A Realm
M MSPackageManager

AFNetworking
Expecta
Specta
Downloading dependencies

-> Using AFNetworking (3.1.0)

-> Using Expecta (1.0.5)

-> Installing MSPackageManager 0.1.0 (was 0.1.0)

-> Installing Realm (1.0.2)

Git download
Git download
$ /usr/local/opt/git/libexec/git-core/git clone https://github.com/realm/realm-cocoa.git
/var/folders/zp/g4lt8dzj4p3b1tb8jwl702m40000gp/T/d20160722-69260-j26dzn --single-branch --depth
1 --branch v1.0.2
Cloning into '/var/folders/zp/g4lt8dzj4p3b1tb8jwl702m40000gp/T/d20160722-69260-j26dzn'...
Note: checking out '10ef693b9935694f58f49b264008f6cf3ccccf61'.
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
Running prepare command
$ /bin/bash -c set -e sh build.sh cocoapods-setup
core is not a symlink. Deleting...
Downloading dependency: core 1.3.1
```

## Code Sample

It's an issue before coding

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version:  Any Realm in OC, not Swift is OK, actually it's checking out core 1.3.1

Xcode version: 

iOS/OSX version: 7.0+

Dependency manager + version: CocoaPods 0.39.0

## Addition

I've found other's solution like this 
```
curl https://static.realm.io/downloads/core/realm-core-1.0.1.tar.bz2 -O
mkdir $TMPDIR/core_bin
mv realm-core-1.0.1.tar.bz2 $TMPDIR/core_bin
```
文／demoker（简书作者）
原文链接：http://www.jianshu.com/p/0fd0a32a1074
著作权归作者所有，转载请联系作者获得授权，并标注“简书作者”。

Then I tried to modify the link to `https://static.realm.io/downloads/core/realm-core-1.3.1.tar.bz2`, but there is no resource of it.

**Comment by bdash** [comment]
Thanks for filing a new issue, @aelam!

How long are you waiting after the `Downloading dependency: core 1.3.1 ` message appears during `pod install`? The core library is around 35MB in size, so depending on your network connection it may take a few minutes to download.

> Then I tried to modify the link to https://static.realm.io/downloads/core/realm-core-1.3.1.tar.bz2, but there is no resource of it.

We changed the file extension recently from `.tar.bz2` to `.tar.xz` for better compression.

**Comment by aelam** [comment]
Oh, maybe that is the problem. I am trying download the tar.xz now. The connection from here China is super slow, though we have a good bandwidth. It needs at least 40 minutes.

**Comment by jpsim** [comment]
Sorry for these issues @aelam, we're aware of connection issues with China and are tracking that generally in #2713.

**Comment by aelam** [comment]
Thank you!

2016-07-26 20:24 GMT+00:00 JP Simard <notifications@github.com>:
