### ISSUE TITLE
Put NS file protection options in Realm.Configuration

### ISSUE THREAD

**Issue by danielrhodes** [realm/realm-cocoa#3908]
Instead of [the method described in the docs](https://realm.io/docs/swift/latest/#using-realm-with-background-app-refresh) for dealing with accessing Realm in the background, it would be nice to be able to set the desired file protection key inside a `Realm.Configuration` and Realm would use that attribute.

How would I go about accomplishing that?

**Comment by mrackwitz** [comment]
The only reasons I see against that is the selective availability on some Apple platforms and that this could cause confusion around the purpose whether it's actually thought for the OS-provided encryption or Realm's built-in encryption.
What are your thoughts? /c @jpsim @tgoyne

**Comment by jpsim** [comment]
We had considered that previously, but decided against it to continue giving users full flexibility over how and when file protection attributes are applied. We've documented this in the [Using Realm with Background App Refresh](https://realm.io/docs/objc/latest/#using-realm-with-background-app-refresh) section of our docs.

**Comment by austinzheng** [comment]
I don't think this should be "idea backlog", given what JP said. Closing.
