### ISSUE TITLE
Can't use subclasses with RLMLinkingObjects

### ISSUE THREAD

**Issue by timothycosta** [realm/realm-cocoa#3912]
I had been putting off updating realm due to my use of the deprecated `linkingObjectsOfClass:forProperty:` method.  Now that I've done so, my "owners" property is never populated due to my use of subclasses.

## Goals

Be able to access owning objects regardless of subclass, as was possible with `linkingObjectsOfClass:forProperty:`

## Expected Results

Properties of type `RLMLinkingObjects` should link to subclasses, not just specific class types.

## Actual Results

Properties of type `RLMLinkingObjects` contain no results when owners are a subclass unless the subclass is specifically added to `linkingObjectsProperties` with a separate property.

## Steps to Reproduce

Create an "owning" class - `SyncableObject`
Create an "owning" subclass - `SyncableObjectSubclass`
Create an "owned" class - `SyncableProperty`

Create an RLMArray of SyncableProperties on SyncableObject
Create an RLMLinkingObjects property on SyncableProperty

Add owned SyncableProperties to SyncableObjectSubclass

Try to access owning objects via RLMLinkingObjects property.  This property contains no values.

## Code Sample

https://github.com/timothycosta/RealmLinkingObjectsWithSubclasses

Output: 

```
Sub.dirtyProperties: RLMArray <0x7fed3bc95dd0> (
	[0] SyncableProperty {
		uuid = 52F0E33B-43B8-4D6D-96C9-2444BFB6FFD4;
	}
)
2016-07-26 16:50:52.523 RealmKVOCrash[70901:3204441] Prop.owners: RLMResults <0x7fed3bf084e0> (

)
2016-07-26 16:50:52.524 RealmKVOCrash[70901:3204441] Prop.subclassOwners: RLMResults <0x7fed3bd31e70> (
	[0] SyncableObjectSubclass {
		dirtyProperties = RLMArray <0x7fed3bd32590> (
			[0] SyncableProperty {
				uuid = 52F0E33B-43B8-4D6D-96C9-2444BFB6FFD4;
			}
		);
	}
)

```

## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: 7.3

iOS/OSX version: 9

Dependency manager + version: Cocoapods 0.39.0

**Comment by ashvar** [comment]
Have the same issue with ObjC solution. Both in 1.0.0 and in 1.0.2 version. How long the fix may take? Is there a walk-around?

**Comment by bdash** [comment]
I'm a little confused as to how you've framed this bug report. `-linkingObjectsOfClass:forProperty:` also only returned instances of the given type, and never instances of subclasses. This falls out of how Realm's relationships work at present, where relationships are only able to refer to instances of the declared class and not an instance of a subclass.

Can you share how you were using `-linkingObjectsOfClass:forProperty:` to clarify what behavior you had that you're having difficultly with when using `RLMLinkingObjects`?

**Comment by ashvar** [comment]
In my case I have RLMObjects subclasses: Item, Tag, Group. They have following relations:
Item <<- Group (One to many).
Item <<->> Tag (Many to many).

And I want to further subclass them to add additional properties. Isn't it possible at all?

**Comment by bdash** [comment]
@ashvar, your question appears to be about the more general issue of polymorphism in Realm (#1109).

**Comment by ashvar** [comment]
@bdash you are right. I thought subclassing support meant full support for inheritance, including relations. Seems like Realm doesn't fit my needs.

**Comment by timothycosta** [comment]
@bdash Thanks for your question.  Now that I've looked at my old code, I realize that there is a major difference between the old and new method.  You used to be able to specify the class each time.  Here's how my old SyncableProperty `owner` method looked:

```- (SyncableObject*)owner{
	NSArray *owners = [self linkingObjectsOfClass:self.ownerClass forProperty:@"dirtyProperties"];
						return owners.firstObject;
}
```

I am saving the owner class as a string on SyncableProperty, but I removed that from my sample project as I wasn't paying attention to the deprecated method signature and didn't realize it was relevant.  Given that `linkingObjectsProperties` is called at startup and not per-object, it seems like this behavior may be impossible now.  Do you have any ideas for how I could work around this?

**Comment by bdash** [comment]
To emulate the pattern you were using, you'll need to have your `SyncableProperty` class declare a `RLMLinkingObjects` property for each class that links to it, and then have your `owner` method pick the appropriate property to use based on the `ownerClass`. Does this sound like it'd provide the behavior you're after?

**Comment by timothycosta** [comment]
I don't think I want to do that.  There are probably 10 subclasses right now, and more all the time.

Instead, I've added properties `ownerId` and `ownerProperty` and used `objectsInRealm:where:`

```
- (SyncableObject*)owner{
	Class c = NSClassFromString(self.ownerClass);
	RLMResults *results = nil;
	NSCharacterSet *numeric = [NSCharacterSet characterSetWithCharactersInString:@"-0123456789"];
	if ([self.ownerId containsCharactersInSet:[numeric invertedSet]]){
		results = [c objectsInRealm:self.realm
							  where:@"%K = %@", self.ownerProperty, self.ownerId];
	} else {
		NSInteger ownerId = [self.ownerId integerValue];
		results = [c objectsInRealm:self.realm
							  where:@"%K = %@", self.ownerProperty, @(ownerId)];

	}
	NSParameterAssert(results.count <= 1);
	return results.firstObject;
}

```

Not quite as nice, but I'm back in business at least.
