### ISSUE TITLE
Notification even the app is killed

### ISSUE THREAD

**Issue by kwstasna** [realm/realm-cocoa#3913]
I'm currently making a TODO app and i save the date that the user has to do a thing. Lets say that he saves the date 28-7-2016 to do something, i make another collumn tobenotified and i take the date minus it by 1 and save it, so the user should be notified the previous day that tomorrow has a thing to do.

But what if the user has closed the app(killed it), how is the proper way to send a notification from realm database when the date tobenotified is equal with NSDate() the current date ???

**Comment by mrackwitz** [comment]
I saw your question over on StackOverflow and [answered over there](http://stackoverflow.com/a/38591792/4194189). That was already the right location to ask. :+1: Closing this issue here.
