### ISSUE TITLE
Add notification block to an object

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3915]
Right now, we have two entirely different mechanisms for observing changes to an object: KVO notifications for `Object` subclasses, and notifications blocks for `List`/`Results`/`Realm` instances. It might make sense to implement change observation via notification blocks for `Object`. KVO feels much less native, especially in Swift, and we cannot expose certain functionality (like ignoring changes from a certain write: https://github.com/realm/realm-cocoa/issues/3665) using KVO.

For example, if a user is building a contacts app, it would be nice if they were easily able to observe changes that may occur on a background thread so they could build a reactive UI.
```swift
person.addNotificationBlock { realm, change in
    switch change {
    case .initial:
        return
    case .changed(let member, oldValue, newValue):
        if update.name == "firstName" {
            nameView.textField.text = newValue as! String
        }
    case .deleted:
        // TODO: dismiss view controller w/ alert
        fatalError()
    }
}
```

**Comment by jpsim** [comment]
Duplicate of #3431?

**Comment by JadenGeller** [comment]
Oh, yes! I searched, but didn't find that.
