### ISSUE TITLE
1.0.2 tagging issue impacting carthage integration with submodules (with solution)

### ISSUE THREAD

**Issue by jeremiegirault** [realm/realm-cocoa#3917]
## Goals

This issue is not very important but may help you for your future releases.

Using realm-cocoa as a carthage submodule dependency we could not checkout latest version (1.0.2).

`carthage update --use-submodules --no-use-binaries --no-build --use-ssh --verbose`

Fails with this strange error message:

<img width="568" alt="capture d ecran 2016-07-27 a 15 01 43" src="https://cloud.githubusercontent.com/assets/1162682/17176030/1037ebb2-540b-11e6-8350-88d436d2e6de.png">
## Expected Results

I expect the git submodule to be updated
## Actual Results

The above message
## Steps to Reproduce

It's not possible to reproduce from a fresh clone because all tags are fetched during clone.

However from a previous version of the repo: 
   Just `git pull` then try either `git checkout v1.0.2` or `git checkout 10ef693b9935694f58f49b264008f6cf3ccccf61`
Both end up with this:
<img width="568" alt="capture d ecran 2016-07-27 a 15 01 43" src="https://cloud.githubusercontent.com/assets/1162682/17176030/1037ebb2-540b-11e6-8350-88d436d2e6de.png">
## Explanation & workaround

It seems the latest version is tagged from a specific branch (maybe orphan)
<img width="659" alt="capture d ecran 2016-07-27 a 14 58 50" src="https://cloud.githubusercontent.com/assets/1162682/17175946/b1c9b880-540a-11e6-8d27-4e55fd6895d4.png">

Previous versions were tagged from master
<img width="617" alt="capture d ecran 2016-07-27 a 14 59 02" src="https://cloud.githubusercontent.com/assets/1162682/17175949/b5e36fa6-540a-11e6-9c45-0cf6ec655c29.png">

As common git functions (e.g `git pull`) only fetch tags with their respective branches and this version tag seem orphan, the commit is not available after the fetch.

**Solution:** 
Client side: You just have to explicitely fetch tags with `git fetch -t` then these commits become available and we can checkout them.
Realm side: push a branch on origin with the tip on 1.0.2 tag (it will be fetched by clients pulling)
## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: N/A

iOS/OSX version: N/A

Dependency manager + version: Carthage 0.17.2 + git 2.9.2

---

Thanks and keep up the good work 👍

**Comment by mrackwitz** [comment]
Thanks for bringing this to attention. Looking at the documentation of [git-fetch](https://git-scm.com/docs/git-fetch), this is indeed the intended behavior of Git by default. I think this should be brought to attention at Carthage as well. But it would help to fix that short-term by making sure to keep around release branches. /c @jpsim @tgoyne @bdash

**Comment by bdash** [comment]
I feel this is something Carthage should address. We can keep branches around as a workaround, but it'd be worth filing an issue against Carthage to address the underlying problem.

**Comment by jeremiegirault** [comment]
Indeed it's more a git issue in this case, but if you manage to always tag from master or non-orphan branch, it's a non-problem. 
You may therefore try to include this rule in your release process.
I submitted this issue as a hint. 

Thanks for the feedback !
