### ISSUE TITLE
Realm 1.0.2 crashes on iOS 9.2, the first time the app runs

### ISSUE THREAD

**Issue by skydivedan** [realm/realm-cocoa#3921]
## Goals

I want to launch my app on iOS 9.2, without crashing at startup.

## Expected Results

The app continuing to run.

## Actual Results

For a newly installed app, on iOS 9.2, it crashes the instant `let realm = try! Realm()` is called. When I relaunch the app, I don't get this.

I get this in the debug logs:
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "No such file or directory" UserInfo={Error Code=2, NSFilePath=/Users/skydivedan/Library/Developer/CoreSimulator/Devices/0B6BA577-C0DB-482D-94F5-526CD58EEF17/data/Containers/Data/Application/1552DB95-B011-4E55-B967-F2C1DAB507B1/Documents/default.realm, Underlying=n/a, NSLocalizedDescription=No such file or directory}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54
## Steps to Reproduce

What are steps we can follow to reproduce this issue?

1 - debugged on iPhone 6s Simulator in Xcode.
2 - copy/paste the code defined here: https://realm.io/docs/swift/latest/#defining-migrations
## Code Sample
This code is the first first thing that is called in application:didFinishLaunching.
3 - If this is a test app, remove the old app from the simulator/device, so that it gets installed. There's no documents or settings belonging to this app yet.

Provide a code sample or test case that highlights the issue.
Code copied directly from your site. First thing that's called in didFininshLaunching.
https://realm.io/docs/swift/latest/#defining-migrations

## Version of Realm and Tooling

Realm version: RealmSwift 1.0.2

Xcode version: 7.3

iOS/OSX version: iOS 9.2

Dependency manager + version: cocoapods 1.0.1

**Comment by skydivedan** [comment]
other comments. I haven't tested on other devices. But I can tell you I don't see this on iOS 9.3.3 (my normal config). So far, only tested on a iPhone 6s

**Comment by jpsim** [comment]
I'm sorry @skydivedan, the steps you've shared in "Steps to Reproduce" aren't actually steps that we can take to reproduce this.

What steps can we take to get the same behavior you're seeing?

**Comment by skydivedan** [comment]
Well, could you install the iOS 9.2 Simulator in Xcode? b/c that's how I'm seeing this.

**Comment by jpsim** [comment]
hmm, seems I can't even install the iOS 9.2 simulators. Here's the `CoreSimulator.log` output I get when attempting to launch it, after installing it via Xcode 7.3.1's "Downloads" pane.

```
ul 27 13:15:49  com.apple.iphonesimulator[34948] <Notice>: Requested watch is is not available for pairing.  Assuming it has the capability.
Jul 27 13:15:49  com.apple.iphonesimulator[34948] <Notice>: Requested watch is is not available for pairing.  Assuming it has the capability.
Jul 27 13:15:49  com.apple.iphonesimulator[34948] <Notice>: Requested watch is is not available for pairing.  Assuming it has the capability.
Jul 27 13:15:49  com.apple.iphonesimulator[34948] <Notice>: Requested phone is is not available for pairing.  Assuming it has the capability.
Jul 27 13:15:49  com.apple.iphonesimulator[34948] <Notice>: Requested watch is is not available for pairing.  Assuming it has the capability.
Jul 27 13:15:49  com.apple.iphonesimulator[34948] <Notice>: Requested phone is is not available for pairing.  Assuming it has the capability.
Jul 27 13:15:59  CoreSimulatorService[28124] <Error>: Error Domain=com.apple.CoreSimulator.SimError Code=159 "Unable to boot device in current state: Creating" UserInfo={NSLocalizedDescription=Unable to boot device in current state: Creating}
Jul 27 13:15:59  com.apple.iphonesimulator[34948] <Error>: Error Domain=com.apple.CoreSimulator.SimError Code=159 "Unable to boot device in current state: Creating" UserInfo={NSLocalizedDescription=Unable to boot device in current state: Creating}
```

Will continue trying to get that to run and will get back to you.

**Comment by skydivedan** [comment]
hmm, standby. I just tried to build a sample app, and it did *not* exhibit this behavior. The only extra pod I'm linking in is Realm 1.0.2, and no crash. I'll try and get a working sample app to you. Weird thing is, this code is the first code that gets called in my app, just as in the sample. I'll have to dig through the settings, etc. oh joy. Wish me luck!

**Comment by jpsim** [comment]
After restarting my computer, I was able to run the iOS 9.2 simulators and could not reproduce this.

Here's my little app:

```swift
import UIKit
import RealmSwift

class MyModel: Object {
    dynamic var prop = 0
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        let config = Realm.Configuration(
            // Set the new schema version. This must be greater than the previously used
            // version (if you've never set a schema version before, the version is 0).
            schemaVersion: 1,

            // Set the block which will be called automatically when opening a Realm with
            // a schema version lower than the one set above
            migrationBlock: { migration, oldSchemaVersion in
                // We haven’t migrated anything yet, so oldSchemaVersion == 0
                if (oldSchemaVersion < 1) {
                    // Nothing to do!
                    // Realm will automatically detect new properties and removed properties
                    // And will update the schema on disk automatically
                }
        })

        // Tell Realm to use this new configuration object for the default Realm
        Realm.Configuration.defaultConfiguration = config

        // Now that we've told Realm how to handle the schema change, opening the file
        // will automatically perform the migration
        let realm = try! Realm()
        try! realm.write {
            realm.add(MyModel())
        }
        print(realm.objects(MyModel.self))
        return true
    }
}
```

which logs this on first launch:

```
Results<MyModel> (
	[0] MyModel {
		prop = 0;
	}
)
```

and this on the subsequent one:

```
Results<MyModel> (
	[0] MyModel {
		prop = 0;
	},
	[1] MyModel {
		prop = 0;
	}
)
```

To recap, I've built an iOS project with Xcode 7.3.1, added the `RealmSwift` pod at version 1.0.2 via CocoaPods 1.0.1, run this multiple times on an iPhone 6s Plus Simulator running iOS 9.2.

I've attached my sample project here:

[GH3921.zip](https://github.com/realm/realm-cocoa/files/387108/GH3921.zip)

You'll need to run `pod install` prior to opening the workspace.

**Comment by skydivedan** [comment]
sorry to bother you with this. It's 100% reproducible in my app, but I can't get it to fail at all on a simple app, with Realm as it's only dependency. Clearly something else is afoot here, but I'm not sure what. If I can get you a real sample app, I'll re-open.

**Comment by jpsim** [comment]
Thanks for taking the time to look closely into this.

**Comment by adomanico** [comment]
@skydivedan does your project have Apptimize as a dependency ? I saw this exact issue and downgrading Apptimize strangely was a workaround for me

**Comment by skydivedan** [comment]
Well, now isn't that interesting. Yes, I am using Apptimize. The latest
version available.

**Comment by adomanico** [comment]
I downgraded to 2.16.8. Going to leave it on that version until Apptimize fixes the issue

**Comment by MikeSilvis** [comment]
@jpsim I created a sample project with just Apptimize and Realm and it causes this crash: https://github.com/MikeSilvis/apptimize-realm

I am also reaching out to Apptimize. Thanks

**Comment by skydivedan** [comment]
we'll be reaching out to them shortly.

**Comment by adomanico** [comment]
Given the output, it looks like Apptimize has for whatever reason deleted the default realm after a failed migration on their end. I also am not sure why they would not create their own realm

**Comment by jpsim** [comment]
Doesn't look like the Apptimize SDK has any knowledge of Realm, though if they're deleting files in the Documents directory, that would affect the default Realm, though it seems like an unlikely major oversight on their part if that's the case.

**Comment by skydivedan** [comment]
it's weirder than that. I see this the first time the app runs, so there shouldn't be any old data lying around.

**Comment by adomanico** [comment]
The output I was seeing was "ApptimizeMigrate() 0 find your realm here Optional(<realmpath>)" 

This is why I tried to downgrade Apptimize and why I think they might have realm in their sdk

**Comment by skydivedan** [comment]
it's weirder than that. I see this the first time the app runs, so there shouldn't be any old data lying around.

**Comment by adomanico** [comment]
Received a response from Apptimize that they are looking into it.

**Comment by jsaptmz** [comment]
We have released a fix for the Apptimize iOS SDK for this (version 2.16.11). Thanks for everybody's help and patience, and sincere apologies for the trouble.

**Comment by MikeSilvis** [comment]
@jsaptmz thanks!
