### ISSUE TITLE
Thread-safe + Cloud Sync = Take my $$$$$!

### ISSUE THREAD

**Issue by basememara** [realm/realm-cocoa#3925]
You devs are awesome. Thanks for making a simple yet powerful mobile database that is also cross-platform and free!

The barrier to enterprises is thread safe support and cloud sync. Core Data is thread safe and Couchbase Lite has cloud sync (a really good one too). If Realm had these, it would be a no brainier for any iOS or Android dev and believe it would make a lucrative add on for Realm.

Nothing new I know, and there are workarounds, but please make this a reality! Sounds like the community will be behind you and contribute if you take the first step.

**Comment by bdash** [comment]
Would you mind providing some detail about what you feel is lacking in Realm's approach to threads?

**Comment by basememara** [comment]
Sure let me try. Having to create new `Realm` instances for each thread is inconvenient, but fine. What really becomes a source of crashes is objects from one thread cannot be worked on from another thread without re-fetching. This becomes quite a ceremony to ensure threading doesn't kill your app.

For example:
```
// Called every second by bluetooth device
func subscribeFromDevice(value: Int) {
    guard let realm = try? Realm() else { return }
  
    let model = MyModel()
    model.date = NSDate()
    model.value = value
    model.cloud = false
    
    do {
        try realm.write {
            realm.add(model, update: true)
        }
    } catch let error as NSError {
        Log.error("\(error)")
        return
    }
}
```
Meanwhile, I have an event that triggers a background thread to flush Realm to the cloud:
```
func flushRealmToCloud() {
    dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0)) {
        guard let realm = try? Realm(),
            let items = realm.objects(MyModel.self).filter("cloud == false")
                else { return }

        let chunkSize = 1000
        var protos: [MyProtobufs] = []

        while !items.isEmpty {
            realm.beginWrite()
            
            // Break up the writing blocks into smaller portions
            for index in 0...chunkSize {
                guard let proto = items.first.toProtoBuf() else { continue }
                
                // Do stuff with protobuf
                ...

                // Restart for new batch if applicable
                if index == chunkSize {
                    protos.streamToCloud()
                    protos.removeAll()
                }
                
                // Append item in memory and mark complete
                protos += [proto]
                item.cloud = true
            }
            
            // Commit the write transaction
            do {
                try realm.commitWrite()
            } catch let error as NSError {
                LogError("\(error)")
            }
        }

        // Handle left overs
        if !protos.isEmpty {
            protos.streamToCloud()
            protos.removeAll()
        }
    }
}
```
The problem is that the background thread has a list that is simultaneously being populated by the main thread in `subscribeFromDevice`. In the `while !items.isEmpty` loop in `flushRealmToCloud`, there could be a clash where it is setting the `cloud` flag for an item that came from another thread, then :collision:.

Where I am chunking the batches, I could re-fetch, but seems non-performant and extra work (a `object.copyToThread()` would help maybe). Also, providing `enumerations` on Realm `Results` could alleviate things as well. What do you think, am I just not approaching this in the best way?

**Comment by JadenGeller** [comment]
https://github.com/realm/realm-cocoa/pull/3828 introduces a way to pass objects between threads.

```swift
let handover = realm.exportHandoverPackage([foo, bar])
dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0)) {
    let (realm, objects) = try! handover.importOnCurrentThread()
    let (foo, bar) = (objects[0], objects[1])
    // do stuff
}
```

**Comment by bdash** [comment]
@basememara, I'm not clear in your example where there's any potential for objects to come from the wrong thread. The only objects your `flushRealmToCloud` works with are those it retrieves from its own `Realm`. Can you clarify what potential problem you see with this code?

**Comment by astigsen** [comment]
I would probably also move this part out of the loop to avoid holding write transactions open while doing expensive (non-realm related) operations:

```swift
                // Restart for new batch if applicable
                if index == chunkSize {
                    protos.streamToCloud()
                    protos.removeAll()
                }
```

**Comment by basememara** [comment]
In `subscribeFromDevice()`, the `realm.write` adds items to the database. In `flushRealmToCloud()`, the query pulling objects that match this criteria.

So the 'items' list in `flushRealmToCloud()` is getting bigger from `subscribeFromDevice()`. I believe this is what I am seeing and seems to match what it says in the docs?

```
On the main UI thread (or any thread with a runloop) objects will automatically update with changes from other threads between each iteration of the runloop.
```

**Comment by basememara** [comment]
Hey @astigsen, thx for the input, but it is out of the loop and its a collection of non-Realm objects. I put that there in case the loop finished before the last chunk size is finished.

**Comment by bdash** [comment]
The contents of `items` will only change when the `Realm` on your background thread advances to a new version of the data. This happens when you call `Realm.refresh()`, begin a write transaction, or begin a new runloop iteration for a thread running an explicit runloop.

**Comment by basememara** [comment]
Maybe I'm not grasping, within the `while-loop` I am immediately calling a `realm.beginWrite()`, won't that update the items collection with items from other threads?

**Comment by bdash** [comment]
Yes, calling `beginWrite` will refresh `items` to include any newly-added `MyModel` objects.

**Comment by basememara** [comment]
Hmmm, then refreshing it will make that item belong to that background thread I'm in then I'm good, right? Maybe I am seeing a race-condition crash. I'm wondering if `flushRealmToCloud()` sometimes calls `realm.beginWrite()` at the same moment `subscribeFromDevice` is within the `realm.write { realm.add.. }` block.

**Comment by bdash** [comment]
Note that they're not the exact same instances of `MyModel` that were added by your other thread. Retrieving objects from a `Results` produces instances of the model class that are associated with the same `Realm` that the `Results` is (i.e., the instances belong to your background thread).

**Comment by bdash** [comment]
If your background thread calls `beginWrite` while your main thread is within the `write` block, the background thread will block until the main thread finishes its write transaction.

**Comment by basememara** [comment]
I see, ok what if my `subscribeFromDevice ` was firing background thread as well, would it change things?
```
// Called every second by bluetooth device
func subscribeFromDevice(value: Int) {
    dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0)) {
        guard let realm = try? Realm() else { return }
        
        let model = MyModel()
        model.date = NSDate()
        model.value = value
        model.cloud = false

        do {
            try realm.write {
                realm.add(model, update: true)
            }
        } catch let error as NSError {
            Log.error("\(error)")
            return
        }
    }
}

**Comment by bdash** [comment]
No. Only a single thread can have a write transaction open at one time. Subsequent threads attempting to open a write transaction will block until the write transaction is either committed or rolled back.

Can you share some more information about what problem you're experiencing? That would help in trying to determine where things are going wrong.

**Comment by bdash** [comment]
I do see one oversight in `flushRealmToCloud`: its block should explicitly call `realm.refresh()` after fetching the Realm, prior to the loop. This will ensure that `items` contains current data, rather than an older version of the data that the `Realm` happened to be looking at. Without doing this it is possible for the block called by `flushRealmToCloud` to not see new items until some point in the future.

**Comment by astigsen** [comment]
> This will ensure that items contains current data, rather than an older version of the data that the Realm happened to be looking at.

The `beginWrite()` should handle this.

**Comment by basememara** [comment]
There's some kind of race condition happening where a crash occurs in the above scenario because an object cannot be accessed from another thread, but happens in rare cases. I realize something reproducible would help, though everyone's tips here are really great and will share more findings back here!

**Comment by bdash** [comment]
`beginWrite` is only called if `items` is not empty. The Realm needs to be refreshed prior to checking if `items` is empty to avoid seeing it as empty when it is not.

**Comment by astigsen** [comment]
> beginWrite is only called if items is not empty. 

You are right.

There shouldn't be much of a window for it to change. The Realm is created right before entering the loop, and when in the loop `isEmpty` is called right after committing the write transaction, so there is not much time for another transaction to sneak in. But it is good to be safe.

**Comment by bdash** [comment]
Realm instances are cached per thread. There's no guarantee that the `Realm` retrieved at the start of the block is looking at the current version of the data unless it is explicitly refreshed. It could be looking at whichever version of data was current the last time the block executed, for instance.

**Comment by astigsen** [comment]
Good point. That seems like something a lot of users could easily trip up on. We should improve the documentation around that, or even better make sure the it get refreshed automatically when used like this.

**Comment by bdash** [comment]
I agree that our current behavior can be surprising to users. I don't think there's any way to know whether it's appropriate to refresh for one call to `Realm()` vs another though.

**Comment by basememara** [comment]
That's sounding spot on like my case: Realm instances cached per thread. Since `flushRealmToCloud()` is called several times during the lifecycle of the app.

Working on the crash log, its a raw app and didn't have error logging hooked up yet =\

I will try to get it to crash again before trying your suggestion of the `refresh`.

**Comment by JadenGeller** [comment]
@bdash Any reason `refresh` shouldn't be called when a `Realm` is initialized?

**Comment by tgoyne** [comment]
> make sure the it get refreshed automatically when used like this.

I'm fairly certain that isn't possible without wrapping dispatch_async(), and if we wrap dispatch_async() we can just wrap the block in an autoreleasepool and eliminate the problem entirely. GCD doesn't have any concept of a current task that we can check and refresh if it's changed.

**Comment by bdash** [comment]
@JadenGeller People write code like this:

```swift
let objects = try! Realm().objects(SomeType.self)
…
let otherObjects = try! Realm().objects(OtherType.self)
```

I don't think users would expect the second call to change the contents of `objects`.

**Comment by astigsen** [comment]
> I'm fairly certain that isn't possible without wrapping dispatch_async()

Then we are back to a `readAsync` method to complement `writeAsync` :-)

**Comment by JadenGeller** [comment]
Fair, but this is just as unexpected, yet happens under our current model!
```swift
let realmA = Realm()
let objects = try! realmA.objects(SomeType.self)

let realmB = Realm()
realmB.refresh()

// The contents of `objects` has changed (maybe)!
```

**Comment by bdash** [comment]
@basememara, as @tgoyne alluded to, the alternative to explicitly calling `refresh` is to ensure that _all_ work you perform on dispatch queues is within an explicit autorelease pool. This ensures the Realm instance is deallocated when the autorelease pool is popped, and that the next block that executes on the same dispatch worker thread will receive a Realm that's looking at the most recent version of the data.

@JadenGeller, that's code that a user is much less likely to write without having a deeper understanding of Realm.

**Comment by astigsen** [comment]
Maybe not as unexpected as `realmA` and `realmB` are the same object.

**Comment by bdash** [comment]
@basememara, did you make any progress on understanding what's going on here? Do you have a crash log you can share with us?

**Comment by basememara** [comment]
I think I finally found the issue thanks to everyone's input here. The original error message was this:
`Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread'**`

Sorry I realize this error message was a little different than what we originally thought, but this discussion still led me to the same solution.

I had a factory for creating Realm instance like this:
```
func getRealmForThread() -> Realm? {
   return try? Realm(configuration: createConfig())
}
```
Innocently or naively, I was using this factory to create instances for within threads like this:
```
dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0)) {
   guard let realm = dataStore.getRealmForThread() else { return }
   ...
}
```
As mentioned in this discussion, Realm instance are cached per thread, but also seemed per block as well. So this was returning the same Realm instance for all my threads, but I was thinking it was getting a fresh instance every time which didn't seem to be the case.

Once I changed it to this, the issue went away:
```
dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0)) {
   guard let realm = try? Realm(configuration: createConfig()) else { return }
   ...
}
```

**Comment by jpsim** [comment]
> Having to create new `Realm` instances for each thread is inconvenient, but fine. 

I feel like Realm's thread confinement design has to be explained in more detail. The fact that Realms and Realm objects are thread-confined isn't a temporary limitation based on Realm's internals, or an artificial constraint. This is part of the design, and freely passing Realms across threads, though implementable, would have tradeoffs that would render it very dangerous and unpredictable to use.

Realm is a transactional database (think the scope of a write transaction) that allows an app to crash halfway through a write without having partially valid data written to disk. To have isolation (the 'I' in ACID), changes in different transactions aren't reflected in other transactions until those transactions advance to the latest version. Otherwise, you'd get 'faults' present in Core Data, or other ORMs. Realm doesn't have faults thanks to this design.

To aid in this isolation, Realms on a given thread are only ever at the same version (under the hood, there's only a single Realm per-thread). Passing a Realm, or Realm objects/queries/etc freely across threads would mean that you're mixing different versions of the database together, which would lead to very surprising results. For example, passing an object to a thread that has since deleted it could cause a crash, or it could change values as it crosses the thread boundary, or an object graph could have different relationships in either transaction version.

One way we've come up to work around this fundamental restriction is to have scoped thread handovers to other threads (see #3828), so that within that scope, you get the same Realm at the same transaction version on this new thread, which could otherwise have its own Realm in a different transaction.

---

> Core Data is thread safe

Faults.

---

Anyway, it seems you've resolved the specific issues that prompted you to create this issue @basememara. Since we're exploring the prospect of sync in #913 and scoped thread handover in #3136 with a PR in #3828, is there anything else we can help you with? If not, feel free to close this issue at your convenience.

Thanks for prompting this discussion!

**Comment by basememara** [comment]
Thank you for the detailed explanation. From this discussion, I actually do have a new sense of appreciation of how Realm handles multiple threads :+1:. I'll leave the syncing discussion in the other thread ;)
