### ISSUE TITLE
Insertion into a row

### ISSUE THREAD

**Issue by shahinali5678** [realm/realm-cocoa#3930]
I have an object in that there are two keys are present. And I am inserting the first value by adding simple text but when I posting that first key I want to add that postID in the same row but eventually it goes to next column i.e. everytime I post it goes to next column. I am using Swift 2.0 and realm swift version of 1.0.2.

I am usually doing this, 

    let id = dic["id"] as! String
    let realm = RLMRealm.defaultRealm()
    realm.beginWriteTransaction()
    notSureItem.postID = id
    realm.addObject(notSureItem)
    print("post: \(id)")
    _ = try? realm.commitWriteTransaction()

![screen shot 2016-08-01 at 11 39 55 am](https://cloud.githubusercontent.com/assets/14871644/17284927/b9521a86-57dc-11e6-869e-f61ebbc3fc5c.png)

I just want that postId besides the title. I tried the above code but not getting success.

**Comment by austinzheng** [comment]
Hello,

Thanks for getting in touch with us. It looks like the problem is with your GUI code, not necessarily with Realm itself. If you can create a small project that demonstrates the problem happening to a Realm object, without any GUI, we'd be happy to look into it further.

**Comment by shahinali5678** [comment]
Actually what I was doing is I am inserting my title from another view controller i.e. from the addViewController and I am inserting postID when I tap on share button from the tableViewCell.
`shareAction = UITableViewRowAction(style: UITableViewRowActionStyle.Default, title: "Share" , handler: { (action:UITableViewRowAction!, indexPath:NSIndexPath!) -> Void in
                // 2
                let currentCell = tableView.cellForRowAtIndexPath(indexPath)! as UITableViewCell
                print(currentCell.textLabel!.text
                let notSureItem = NotSureItem()
                let switchStatusFromDefault = NSUserDefaults.standardUserDefaults().boolForKey("switch")
                if switchStatusFromDefault {
                    if (FBSDKAccessToken.currentAccessToken() != nil) {
                        if FBSDKAccessToken.currentAccessToken().hasGranted("publish_actions") {

                            let param = ["message": "\(currentCell.textLabel!.text!)"]
                            let feedRequest : FBSDKGraphRequest = FBSDKGraphRequest(graphPath: "me/feed", parameters: param, HTTPMethod: "POST")
                            feedRequest.startWithCompletionHandler({ (connection, result, error) -> Void in
                                if ((error) != nil) {
                                    
                                    print("Error: \(error)")
                                    
                                } else {
                                    if let dic = result as? Dictionary<String, AnyObject> {
                                        
                                        let id = dic["id"] as! String
                                        let realm = RLMRealm.defaultRealm()
                                        realm.beginWriteTransaction()
                                        notSureItem.postID = id
                                        realm.addObject(notSureItem)
                                        print("post: \(id)")
                                        _ = try? realm.commitWriteTransaction()
                                    }
                                }
                            })
                        } else {
                            print("require publish_action")
                        }
                    }
                }` 
This is the code where I used the tableRowActionStyle method  from which I am trying to insert the postId into the same row of that cell title.

Is this information could help you to solve my problem. Thank you!
@austinzheng

**Comment by jpsim** [comment]
The relevant parts of your code adds a new `NotSureItem` to the Realm with just a `postID` value:

```swift
let notSureItem = NotSureItem()
// some irrelevant code...
let realm = RLMRealm.defaultRealm()
realm.beginWriteTransaction()
notSureItem.postID = id
realm.addObject(notSureItem)
print("post: \(id)")
_ = try? realm.commitWriteTransaction()
```

You never set the title on this item, and you're not updating an existing Realm item, you're just adding a new item with a `postID` value to the Realm. Of course this creates a new object.

If you want to update an existing Realm object, you'll need to grab it from the Realm. For example:

```swift
let notSureItem = NotSureItem.objectsWhere("title == %@", "Heeloo").first!
let realm = RLMRealm.defaultRealm()
realm.beginWriteTransaction()
notSureItem.postID = id
_ = try? realm.commitWriteTransaction()
```

If this isn't what you're looking for, could you please share what you're trying to do in more specific terms so we can provide you the advice you need? Thanks!

**Comment by jpsim** [comment]
Closing since we haven't heard back from @shahinali5678 for a few weeks.
