### ISSUE TITLE
Realm for iOS in Xcode 8 & Swift 3

### ISSUE THREAD

**Issue by dodomaroc86** [realm/realm-cocoa#3932]
## Goals

Use Realm 1.0.2 for a iOS Swift 3 project

## Expected Results

Compile without errors or warnings

## Actual Results

Compile error
```
ld: .../Products/Debug-iphonesimulator/RealmSwift/RealmSwift.framework/RealmSwift compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps to Reproduce

Following the steps given [here](https://realm.io/docs/objc/latest/#installation)

- Create an empty project
- install Realm using Coacoapods : 

```
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true

pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
```
- Add `RLMSupport.swift` into the File Navigator of the Xcode project

## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: 8 beta 3

iOS version: 9.3.3

Dependency manager + version: Coacoapods 1.0.1

**Comment by austinzheng** [comment]
Hello,

Thanks for getting in touch with us.

To use Realm with Swift 3, you need to explicitly set the `Use Legacy Swift Language` Version flag on the CocoaPod target. This can be done by clicking on the `Pods` project, clicking on the `RealmSwift` target, going to the 'Build Settings' tab, and changing the flag to `Yes`. (Note that you might have set this flag on your actual project's target; you also have to set it separately on the Pod target. This is no longer necessary if you install the latest beta version of CocoaPods.)

Hope that helps.

**Comment by dodomaroc86** [comment]
Thank you for the quick response,
I've already enabled the `Use Legacy Swift Language` flag in the `RealmSwift` target, and the error is still there.
And just to make sure, I've deleted all derived data and restarted with an empty project.

**Comment by austinzheng** [comment]
Sorry that didn't work! Here's another thing to try.

Can you go to Xcode --> Preferences --> Locations tab and make sure the Xcode 8 (not Xcode 7) command line tools are selected?

**Comment by dodomaroc86** [comment]
Command line tools were set to Xcode 7.3.1. Setting them to Xcode 8 had no effect.

**Comment by austinzheng** [comment]
Would you be willing to send over a copy of the empty project that you say is not working? You can create an attachment and link it, or send it directly to `help@realm.io`.

**Comment by dodomaroc86** [comment]
@austinzheng thank you for the support, I've managed to use Realm with Cocoapods and Xcode beta 4

**Comment by anthonycastelli** [comment]
How did you get this resolved? I am having the same issue

**Comment by dodomaroc86** [comment]
What version of Xcode are you using? The beta 5 has been released today

**Comment by anthonycastelli** [comment]
@dodomaroc86 I was using Beta 4, downloading beta 5 now and will test that.

**Comment by anthonycastelli** [comment]
Same issue on Beta 5

**Comment by bdash** [comment]
@anthonycastelli, it's probably best to file a new issue with details of the problem you're seeing so we can help you.

**Comment by anthonycastelli** [comment]
@bdash Thats what I plan on doing soon as I get home. I thought maybe @dodomaroc86 had a few ideas since he got his working.

**Comment by dodomaroc86** [comment]
@anthonycastelli This video from @jpsim  may help https://static.realm.io/debug/realm-swift-xcode8b4.mp4
