### ISSUE TITLE
pod install 0.102.1 failed

### ISSUE THREAD

**Issue by VenuKotha** [realm/realm-cocoa#3933]
Hi
I am using Realm version 0.102.1.  I am getting the issue recently and not able to resolve. It is installed successfully in some machines and failed in some other machines and getting below error.

issue:-
Installing Realm (0.102.1)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.100.4
mv: rename core to core-0.100.4/core: Directory not empty

Can you please help me to resolve this issue?
Thank you
Regards
venugopal

**Comment by austinzheng** [comment]
Hi VenuKotha,

Thanks for getting in touch with us. I presume that you are building Realm from source. Can you try going to the repository directory and running `rm -rf core`, and then trying the build script again?

Best,
Austin

**Comment by austinzheng** [comment]
Hi VenuKotha,

Thanks for getting in touch with us. Can you try running the `pod` commands described in our troubleshooting section? (see: https://realm.io/docs/objc/latest/#cocoapods)

Best,
Austin

**Comment by kishikawakatsumi** [comment]
I'll close this issue for now due to of inactivity. @VenuKotha if you can provide some more info please feel free to reopen this issue, thanks!
