### ISSUE TITLE
Data not persisting between launches

### ISSUE THREAD

**Issue by zoufishanmehdi** [realm/realm-cocoa#3938]
I'm trying to persist data (journal entries associated with a patient) between launches using reachability to check connectivity and load a tableview. While the data is persisting and I'm able to show it using realm object when I launch the app (using wifi) and switch to airplane mode, it doesn't seem to persist after I force quit it and launch it again in airplane mode. 

Below you can see how I write data to realm `func reloadInitialData` and read from it when there's no connectivity in `cellForRow`. I'm fairly new to Swift and Realm, so I would appreciate a nudge in the right direction. 

Main problem: Be able to persist data even after force quitting and launching the app again (both in airplane mode). 

Thanks!

```
//Patient.swift

import Foundation
import RealmSwift

class Patient: Object {
    
    dynamic var patientName = ""
    dynamic var patientAvatar = ""
    dynamic var patientId = 0
    dynamic var isDietitian = false 
    let journalEntries = List<Journal>() 

    override class func primaryKey() -> String {
        return "patientId"
    }
}

//  Journal.swift

import Foundation
import RealmSwift


class Journal: Object {

    dynamic var entryId = ""
    dynamic var entryType = ""
    dynamic var entryImg = ""
    dynamic var entryCaption = ""
    dynamic var entryComment = ""
    dynamic var entryCategory = ""
    dynamic var entryDate = ""
     
    override class func primaryKey() -> String {
        return "entryId"
    }
  
}

//JournalEntryVC.swift

import UIKit
import Alamofire
import BXProgressHUD
import SwiftyJSON
import RealmSwift


class JournalEntryVC: UIViewController, UITableViewDelegate, UITableViewDataSource {


  func reloadInitialData ( ) {
    
    //mutable arrays containing journal entry attributes
    desc.removeAllObjects()
    type.removeAllObjects()
    category.removeAllObjects()
    metric_stat.removeAllObjects()
    entryImages.removeAllObjects()
    dateCreate.removeAllObjects()
    comments.removeAllObjects()
    entryType.removeAllObjects()
    id.removeAllObjects()
    //comments.removeAllObjects()
    content.removeAllObjects()
    patName.removeAllObjects()
    
    
    let priority = DISPATCH_QUEUE_PRIORITY_DEFAULT
    dispatch_async(dispatch_get_global_queue(priority, 0)) {
        let request = Alamofire.request(.GET, "https://gethealthie.com/entries.json", headers: [
            "access-token": userCreds.objectForKey("access-token")! as! String,
            "client": userCreds.objectForKey("client")! as! String,
            "token-type": userCreds.objectForKey("token-type")! as! String,
            "uid": userCreds.objectForKey("uid")! as! String,
            "expiry": userCreds.objectForKey("expiry")! as! String
            ]).responseJSON { response in
                
                print(response.response)
                
                let json = JSON(data: response.data!)
                
                
                if json.count == 0 {
                    BXProgressHUD.hideHUDForView(self.view);
                }else {
                    
                    //Realm- create object instances of Patient and Journal class
                    let newPatient = Patient()
                    let myJournal = Journal()
                    
                    for i in 0 ..< json.count {
                        
                        let entry = json[i]
                        print(entry)
                        
                        let name = entry["entry_comments"]
                        let k = name["id"]
                        
                        //add entry attributes to mutable arrays
                        self.type.addObject(entry["type"].stringValue)
                        self.desc.addObject(entry["description"].stringValue)
                        self.category.addObject(entry["category"].stringValue)
                        self.metric_stat.addObject(entry["metric_stat"].stringValue)
                        self.dateCreate.addObject(entry["created_at"].stringValue)
                        self.comments.addObject(entry["entry_comments"].rawValue)
                        self.entryType.addObject(entry["category"].stringValue)
                        let posterInfo = entry["poster"]
                        let first = posterInfo["first_name"].stringValue
                        let last = posterInfo["last_name"].stringValue
                        let full = first + " " + last
                        self.patName.addObject(full)
                        self.id.addObject(entry["id"].stringValue)
                        self.entryImages.addObject(entry["image_url"].stringValue)
                        
                        
                        //Realm- access properties in Journal class and set it equal to the current journal entry attribute i.e. json[i]
                        myJournal.entryType = entry["type"].stringValue
                        myJournal.entryCaption = entry["description"].stringValue
                        myJournal.entryCategory = entry["category"].stringValue
                        myJournal.metricStat = entry["metric_stat"].stringValue
                        myJournal.entryDate = entry["created_at"].stringValue
                        //  myJournal.entryComment = entry["entry_comments"].rawValue as! String
                        
                        //append a NEW journal entry to the array of journal entries in Patient class i.e. let journalEntries = List<Journal>() as the json loops thru different journal entries
                        newPatient.journalEntries.append(myJournal)
                        
                        if i == json.count - 1 {
                            // do some task
                            dispatch_async(dispatch_get_main_queue()) {
                                self.tableView.reloadData()
                                BXProgressHUD.hideHUDForView(self.view)
                            }
                        }
                        
                    }
                    
                    //Realm- add newPatient object instance to realm
                    let realm = try! Realm()
                    try! realm.write {
                        realm.add(newPatient)
                        
                    }
                }
                
        }
    }
  }

}

//JournalEntryVC.swift

 func tableView(tableView:UITableView, cellForRowAtIndexPath indexPath:NSIndexPath) -> UITableViewCell {

         let cell = tableView.dequeueReusableCellWithIdentifier("foodTextCell", forIndexPath: indexPath) as! EntryTVCell
                
                let userCreds = NSUserDefaults.standardUserDefaults()
                
          if Reachability.isConnectedToNetwork() == false {
            
                Drop.down("Not connected to internet", state: .Warning)
            
                var journalObj = try! Realm().objects(Journal)
                
                var commentObj = try! Realm().objects(Comment)
                
                var patientObj = try! Realm().objects(Patient)
              
                let journal = journalObj[indexPath.row] as Journal
                let comment = commentObj[indexPath.row] as Comment
                print(comment)
                
                if userCreds.boolForKey("isDietitian") == true {
                    cell.patientName.hidden = false
                   // cell.patientName.text = patient.patientName
                }else {
                    cell.patientName.hidden = true
                }
                
                cell.categoryImage.image = UIImage(data: journal.foodIconImg)
                
                 if journal.entryCaption == "Write a description..." {
                    cell.captionLabel.hidden = true
                } else {
                    cell.captionLabel.hidden = false
                    cell.captionLabel.text = journal.entryCaption
                }
                
                 cell.dateLabel.text = journal.entryDate
                 cell.healthyIntLabel.text = journal.metricStat
                cell.hungerIntLabel.text = journal.foodHungriness
                cell.premealLabel.text = journal.foodPremeal
                 cell.postmealLabel.text = journal.foodPostmeal

           }
```

**Comment by zoufishanmehdi** [comment]
Also, I'm having another issue when I try to delete all objects from Realm when a new user logs in. 

Before clearing out previous user's data, the data seemed to be persisting when a user signs in  and the app launches (using wifi) and then switches to airplane mode as mentioned previously. However, the same data from the previous user was persisting even for a different user. 

 ` let realm = try! Realm()
      try! realm.write {
        realm.deleteAll()
      }`

I added the method above to in `func reloadInitialData` in `viewDidLoad` in order to clear previous user's data on the same thread (background thread) where I write to realm objects. 
After adding this method to delete all objects, my index is out of bounds when the `cellForRow method` is called after the user switches to airplane mode and `Reachability` is false. My error message is usually `RLMException: Index 8 is out of bounds (must be less than index 8)` but the index number is different sometimes. Below you can find the updated `func reloadInitialData` 

Any ideas why this might be happening? Thank you so much! I really appreciate your help. 


`//JournalEntryVC.swift

import UIKit
import Alamofire
import BXProgressHUD
import SwiftyJSON
import RealmSwift


class JournalEntryVC: UIViewController, UITableViewDelegate, UITableViewDataSource {


  func reloadInitialData ( ) {

    //mutable arrays containing journal entry attributes
    desc.removeAllObjects()
    type.removeAllObjects()
    category.removeAllObjects()
    metric_stat.removeAllObjects()
    entryImages.removeAllObjects()
    dateCreate.removeAllObjects()
    comments.removeAllObjects()
    entryType.removeAllObjects()
    id.removeAllObjects()
    //comments.removeAllObjects()
    content.removeAllObjects()
    patName.removeAllObjects()


    let priority = DISPATCH_QUEUE_PRIORITY_DEFAULT
    dispatch_async(dispatch_get_global_queue(priority, 0)) {
        let request = Alamofire.request(.GET, "https://gethealthie.com/entries.json", headers: [
            "access-token": userCreds.objectForKey("access-token")! as! String,
            "client": userCreds.objectForKey("client")! as! String,
            "token-type": userCreds.objectForKey("token-type")! as! String,
            "uid": userCreds.objectForKey("uid")! as! String,
            "expiry": userCreds.objectForKey("expiry")! as! String
            ]).responseJSON { response in

                 let realm = try! Realm()
                        try! realm.write {
                            realm.deleteAll()
                        }

                print(response.response)

                let json = JSON(data: response.data!)


                if json.count == 0 {
                    BXProgressHUD.hideHUDForView(self.view);
                }else {

                    //Realm- create object instances of Patient and Journal class
                    let newPatient = Patient()
                    let myJournal = Journal()

                    for i in 0 ..< json.count {

                        let entry = json[i]
                        print(entry)

                        let name = entry["entry_comments"]
                        let k = name["id"]

                        //add entry attributes to mutable arrays
                        self.type.addObject(entry["type"].stringValue)
                        self.desc.addObject(entry["description"].stringValue)
                        self.category.addObject(entry["category"].stringValue)
                        self.metric_stat.addObject(entry["metric_stat"].stringValue)
                        self.dateCreate.addObject(entry["created_at"].stringValue)
                        self.comments.addObject(entry["entry_comments"].rawValue)
                        self.entryType.addObject(entry["category"].stringValue)
                        let posterInfo = entry["poster"]
                        let first = posterInfo["first_name"].stringValue
                        let last = posterInfo["last_name"].stringValue
                        let full = first + " " + last
                        self.patName.addObject(full)
                        self.id.addObject(entry["id"].stringValue)
                        self.entryImages.addObject(entry["image_url"].stringValue)


                        //Realm- access properties in Journal class and set it equal to the current journal entry attribute i.e. json[i]
                        myJournal.entryType = entry["type"].stringValue
                        myJournal.entryCaption = entry["description"].stringValue
                        myJournal.entryCategory = entry["category"].stringValue
                        myJournal.metricStat = entry["metric_stat"].stringValue
                        myJournal.entryDate = entry["created_at"].stringValue
                        //  myJournal.entryComment = entry["entry_comments"].rawValue as! String

                        //append a NEW journal entry to the array of journal entries in Patient class i.e. let journalEntries = List<Journal>() as the json loops thru different journal entries
                        newPatient.journalEntries.append(myJournal)

                        if i == json.count - 1 {
                            // do some task
                            dispatch_async(dispatch_get_main_queue()) {
                                self.tableView.reloadData()
                                BXProgressHUD.hideHUDForView(self.view)
                            }
                        }

                    }

                    //Realm- add newPatient object instance to realm
                    try! realm.write {
                        realm.add(newPatient)

                    }
                }

        }
    }
  }

}
`

**Comment by jpsim** [comment]
Hi @zoufishanmehdi, could you please send us a sample Xcode project with all its dependencies, so that we can compile/run/debug that on our end rather than attempt to recreate a similar project that might end up not behaving the same behavior as you're seeing? Thanks!

**Comment by zoufishanmehdi** [comment]
Hi @jpsim I can email it to you, so you can compile it? It's supposed to be a private repo. Thanks!

**Comment by austinzheng** [comment]
You can email code samples, projects, files, etc to help@realm.io. Anything that is sent to that address is treated as confidential and kept secret.

**Comment by zoufishanmehdi** [comment]
@austinzheng @jpsim Thank you so much! I will send it over.

**Comment by jpsim** [comment]
Closing since we're continuing this via email and it's extremely specific to @zoufishanmehdi's app.
