### ISSUE TITLE
Realm-swift 1.0.2 not copying to device in Xcode 7.3

### ISSUE THREAD

**Issue by Alamoz** [realm/realm-cocoa#3939]
Title says it all. default.realm not getting copied to either simulator or device in Xcode 7.3. default.realm file is added to bundle resources, that isn't the problem. Bottom line: it worked with Realm 0.97 and now it doesn't work. Perhaps this is an Apple issue, but would appreciate if you look into it. Perhaps my code requires some realm configuration (haven't done any in my previous versions.) Please don't refer me to your example migration app, that isn't helpful.

Thanks!

**Comment by bdash** [comment]
Hi @Alamoz, can you provide a little more detail about the problem you're having? You say that a Realm file in your app bundle isn't being copied to the device. How are you verifying that it was not copied to the device?

**Comment by Alamoz** [comment]
First, I can verify that it is not copying to the simulator folder. When I then copy it manually to the simulator folder (~/Library/Developer/CoreSimulator/..../Documents/default.realm) my app can then read and display data from the default.realm file. So I'm pretty sure when my app doesn't display data on an actual device, the reason must be the default.realm file is not getting copied to the device. I've taken all the usual steps (touch default.realm to update the timestamp, resetting the simulator, removing and then re-adding default.realm to Copy Bundle Resources.

**Comment by bdash** [comment]
The "Copy Bundle Resources" build phase copies files into your app bundle's Resources directory (YourApp.app/Resources), not into the Documents directory of your container. If you only want to read the data, you can open the Realm file from your Resources directory directly. If you want to modify the data as well you'll need to explicitly copy the file from your resources directory to your Documents directory, and then open the Realm from there. The [Bundling a Realm with an App](https://realm.io/docs/swift/latest/#bundling-a-realm-with-an-app) section of the documentation talks about both options.

**Comment by Alamoz** [comment]
We've never had to do that before. I will try to follow those examples, but have to say your coding examples are poorly documented - just adding some detailed comments in the code would go a long way. A lot of the code in the "example" is extraneous to the task of simply copying the default.realm file to the device.

**Comment by bdash** [comment]
It's _always_ been necessary to take explicit action to either open a read-only Realm from your bundle's resources, or to copy it from your resources to a writable location. This isn't new.

You're right that most of the code in the migration sample app is not relevant to the task of copying a Realm file from your app bundle. The migration sample app is intended to demonstrate how to perform model migrations. It just happens to also do this copying as part of the greater task.

**Comment by bdash** [comment]
For reference, the relevant portion of the migration example starts with the comment ["copy over old data files for migration"](https://github.com/realm/realm-cocoa/blob/05ca7aad2b74ab9a5e1de11e0f9cbd4598f05458/examples/ios/swift-2.2/Migration/AppDelegate.swift#L64-L73).

**Comment by Alamoz** [comment]
Thanks for pointing me to that block of code. It kind of works, but is poorly conceived so what it actually does is replace the default realm file every time the app starts, which is not how you want an app to behave. Instead, you can do something like this:

      if let realmURL = bundleURL("default") {
        do {
          let path = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)[0] as String
          let url = NSURL(fileURLWithPath: path)
          let filePath = url.URLByAppendingPathComponent("default.realm").path!
          let fileManager = NSFileManager.defaultManager()
          if fileManager.fileExistsAtPath(filePath) {
            print("FILE INSTALLED")
          } else {
            print("FILE NOT INSTALLED, COPYING default.realm from bundle to Documents directory.")
            try NSFileManager.defaultManager().copyItemAtURL(realmURL, toURL: defaultURL)
          }
          
        } catch {}
      }

**Comment by bdash** [comment]
Sure, the policy by which you decide to copy the file is up to your application. It's not something we can predict.
