### ISSUE TITLE
Realm Obj-C Build Failure: Include of non-modular header inside framework module 'Realm'

### ISSUE THREAD

**Issue by ntokozotep** [realm/realm-cocoa#3942]
## Goals

Integrate Realm Objective-C into mixed Objective-C and Swift iOS project, via CocoaPods.

## Expected Results

Build successful

## Actual Results

Build fails with multiple errors reporting: ```Include of non-modular header inside framework module 'Realm'```

## Steps to Reproduce

Install Realm in mixed iOS project using CocoaPods.

## Version of Realm and Tooling

Realm version: Realm Objective-C, 1.0.2.

Xcode version: 7.3.1

iOS/OSX version: iOS8+

Dependency manager + version: CocoaPods 0.39.0
Also attempted with CocoaPods 1.0.1 but build also failed reporting: ```Realm/RLMArray.h file not found ```, ```Could not build Objective-C module 'Realm'```

**Comment by austinzheng** [comment]
Thanks for getting in touch with us.

Could you try the following?

* Clear your build folder: in Xcode, while holding down the Alt key, go to the Product menu and select 'Clean build folder...'
* If that doesn't work, can you try the troubleshooting instructions [here](https://realm.io/docs/objc/latest/#cocoapods)?

If neither of those work please let us know, and post a copy of your `Podfile` if you can share it. Thanks!

**Comment by ntokozotep** [comment]
Hi Austin,

I've tried your suggestions and they didn't work. Here's my ```Podfile```:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

def common_pods
    pod 'DACircularProgress', '2.2.0'
    pod 'SDWebImage', '3.7.1'
    pod 'REFrostedViewController', '~> 2.4.7'
    pod 'FXBlurView'
    pod 'MBProgressHUD'
    pod 'MarqueeLabel'
    pod 'Parse'
    pod 'Crashlytics'
    pod 'CocoaAsyncSocket'
    pod 'Realm'
end

common_pods

target :ProjectTests, :exclusive => true do
    common_pods
    pod 'OCMockito', '~> 2.0.1'
    pod 'Realm/Headers'
end

link_with 'Project','ProjectQA'

# Make all dependencies build for all architectures
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
    # Disable bitcode for all targets
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end


```

Right now, the workaround I'm using is to install Realm as a dynamic framework.

**Comment by austinzheng** [comment]
Your Podfile looks fine to me. I tried setting up and building a project with CocoaPods 0.39.0, Xcode 7, and your Podfile, and couldn't get it to fail.

Are you sure you performed a clean build (as opposed to a normal clean)?

If you're willing, sending over a minimal example project that reproduces the issue you're having will help us further troubleshoot the issue.

**Comment by ntokozotep** [comment]
I tried with a sample project and I'm not able to reproduce the issue. I had suspected something is wrong with our project and I was hoping you could help out. We'll just have to go with the dynamic framework installation for now. You can close this issue. 

Thanks

**Comment by jpsim** [comment]
Thanks for the update @ntokozotep, and sorry for the trouble.

**Comment by springhand** [comment]
I'm having the same issue, this is my Podfile:

platform :ios, '8.0'
use_frameworks!

target 'Focs-Swift' do
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RongCloudIMKitWithVoip', '2.4.0'
pod 'SQLite.swift'
pod 'ZipArchive', '~> 1.4.0'
pod 'RealmSwift'
end
