### ISSUE TITLE
Error while trying to build Realm on XCode 8 beta 4

### ISSUE THREAD

**Issue by raphaelcruzeiro** [realm/realm-cocoa#3944]
## Goals

Build a project that uses RealmSwift on XCode 8 beta 4

## Expected Results

What did you expected to happen?

Project to build successfully

## Actual Results

2 issues while building RealmSwift:
```
RealmSwift/RealmSwift/Error.swift:100:16: Value of type 'RLMError' has no member 'code'
RealmSwift/RealmSwift/Migration.swift:79:13: Type 'RLMRealm' has no member 'performMigration'
```

## Steps to Reproduce

Use Cocoapods to include Realm on a Swift 3 XCode 8 beta 4 project
```
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
```

## Version of Realm and Tooling

Realm version: ? 1.0.2 fetched from the `master` branch

Xcode version: ? 8 beta 4

iOS/OSX version: ? iOS 10

Dependency manager + version: ? Cocoapods 1.1.0.beta.1

**Comment by bdash** [comment]
Please add the following to your Podfile to ensure that you're also using Realm from `master`:
```ruby
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
```

**Comment by raphaelcruzeiro** [comment]
@bdash That was it! thanks so much and sorry for the false alarm.
