### ISSUE TITLE
Realm Browser - Open Common Location grayed out

### ISSUE THREAD

**Issue by EauSauvage** [realm/realm-cocoa#3945]
## Goals

What do you want to achieve?

In the Realm Browser - open database from iPhone Simulator 

## Expected Results
What did you expected to happen?

## Actual Results

"Open Common Location" menu items are all grayed out

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm Browser: 0.103.1 (75)

Realm version: ?

1.0.0

Xcode version: ?

7.3

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by jpsim** [comment]
Hi @EauSauvage, we're tracking making improvements to this menu item in realm/realm-browser-osx#59. Please subscribe to that for updates. In the future, please use the Realm Browser's issue tracker to file issues about that product.
