### ISSUE TITLE
Cannot build RealmSwift from master after the latests merge (RMLDynamicGetByName expects 3 parameters)

### ISSUE THREAD

**Issue by raphaelcruzeiro** [realm/realm-cocoa#3947]
## Goals

Build RealmSwift from master

## Expected Results

Project to build without problems

## Actual Results

Got a compiler error:
RealmSwift/Object.swift:255:44: Missing argument for parameter #3 in call

The problem lies with `RMLDynamicGetByName`:

```
public override subscript(key: String) -> AnyObject? {
        get {
            let value = RLMDynamicGetByName(self, key)
            if let array = value as? RLMArray {
                return List<DynamicObject>(rlmArray: array)
            }
            return value
        }
        set(value) {
            RLMDynamicValidatedSet(self, key, value)
        }
 }
```

## Steps to Reproduce

Install Realm to a Swift 3 project using Cocoapods pointing to Github:

```
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
```

## Version of Realm and Tooling

Realm version: ? 

Xcode version: ? Version 8.0 beta 4 (8S188o)

iOS/OSX version: ? 10.12 Beta (16A270f)

Dependency manager + version: ? Cocoapods 1.1.0.beta.1

**Comment by bdash** [comment]
Thanks for the report, @raphaelcruzeiro. #3949 will fix this.
