### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by josete89** [realm/realm-cocoa#3948]
Hi,

Just checking my application with instruments and I see some memory leaks from realm:

<img width="1396" alt="screen shot 2016-08-09 at 6 00 46 pm" src="https://cloud.githubusercontent.com/assets/1042992/17523546/4ee1054c-5e5b-11e6-81f1-87d76e7b47d7.png">
<img width="1396" alt="screen shot 2016-08-09 at 6 00 54 pm" src="https://cloud.githubusercontent.com/assets/1042992/17523561/57952196-5e5b-11e6-9845-5b66ff1e7a53.png">
<img width="1396" alt="screen shot 2016-08-09 at 6 00 58 pm" src="https://cloud.githubusercontent.com/assets/1042992/17523570/5dbe63ac-5e5b-11e6-98f3-e4af6eb47b36.png">

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version:  Lastest

Xcode version: 7.3.1

iOS/OSX version: 9.3

**Comment by bdash** [comment]
Thanks for the report, @josete89. We're tracking this issue in #2933. Our best understanding is that this is a bug in the Swift runtime, rather than in Realm itself.
