### ISSUE TITLE
Xcode 8 and Swift 3 build issues

### ISSUE THREAD

**Issue by anthonycastelli** [realm/realm-cocoa#3951]
## Goals
Compile RealmSwift with Xcode 8 Beta 5 and Swift 3

## Expected Results
The project should successfully build

## Actual Results
Project fails to build with this error
`error: The following binaries use incompatible versions of Swift:`

## Steps to Reproduce
Create a `Podfile` and add these pods
```
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
```

run `pod install` and then try and compile your project

## Code Sample

(No code example as this is a build time error with Realm and Swift 3)

## Version of Realm and Tooling
Realm version: 1.0.2

Xcode version: 8.0 Beta 5

iOS/OSX version: iOS 10, Swift 3, OS X 10.11.6

Dependency manager + version: Cocoapods 1.0.1

**Comment by jpsim** [comment]
> error: The following binaries use incompatible versions of Swift

This error is indicative of a stale build cache from having used a previous version of Swift. Have you followed the steps listed here? https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers

**Comment by anthonycastelli** [comment]
Yes, I have cleaned out everything and anything else I can think of. This is the first time i'm using Cocoapods with Realm so I don't see how I would have any cache of it.

**Comment by bdash** [comment]
Can you please share the full compiler or linker invocation that is giving you the error message? It's possible you have a stale version of the Realm framework elsewhere in the framework search path that is being found instead of the version you expect.

**Comment by jpsim** [comment]
Or rather, if CocoaPods is using Swift 2.3 to build your pods, which CocoaPods 1.0.1 does by default, yet your app is using Swift 3, then Xcode will complain about these incompatible Swift versions.

The solution here would be to tell CocoaPods to build your pods with Swift 3. Something like this:

```ruby
target 'RealmSwift3App' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by anthonycastelli** [comment]
@bdash That was exactly what I was overlooking, I kept the old precompiled framework in the project directory and never removed it from the search path so that seemed to of caused the issues. 

Seems to be working now.

**Comment by anthonycastelli** [comment]
I'm reopening this issue with some more info from the build logs. This is still happening on Beta 6 as well. 

https://gist.github.com/anthonycastelli/e50fcb0926f44bf8a930e107f85a0727

**Comment by bdash** [comment]
Did you reopen the right issue? The log you shared doesn't appear to have any connection to the original problem this issue tracks.

**Comment by anthonycastelli** [comment]
Oh whoops, I thought I clicked on the correct one, my bad.
