### ISSUE TITLE
Inability to build complex data models. Remove 'RLMObjectType' from RLMArray definition.

### ISSUE THREAD

**Issue by ashvar** [realm/realm-cocoa#3958]
## Goals

I need to build a data model, that contains: groups, tags and items.

1. items have many-to-many relations with items.
2. items also have many-to-one relations with groups.

Due to known issues you can't easily import headers of one class to another class header in big projects. It won't compile... Its long to describe, but i suppose everybody knows that.

So its easier to place all the Realm classes in one header. But even in this case you can't find correct order of classes declaration, as it doesn't exist!

## Expected Results
Easy compilation.

## Actual Results
Errors while building, because ObjC doesn't support defining class superclass within `@class` directive.

## Solution

Your documentation is great and all the property names are self-explanatory.
Please, remove some surplus code to make it easier to compile:
Example from "RLMArray.h" file:
`@interface RLMArray<RLMObjectType: RLMObject *> : NSObject<RLMCollection, NSFastEnumeration>
`
Change to this, or something event simpler:
`
@protocol RLMObjectP;
@interface RLMArray<id< RLMObjectP>> : NSObject<RLMCollection, NSFastEnumeration>
`
Its also relevant for RLMLinkingObjects.

## Code Sample

```
@class Item;
@interface Group : RLMObject
@property (readonly) RLMLinkingObjects<Item  *> *items;
@end
@interface Tag : RLMObject
@property (readonly) RLMLinkingObjects<Item  *> *items;
@end
@interface Item : RLMObject
@property RLMArray<Tag  *> *tags;
@property Group  *group;
@end
```

Task: place those items in the right order to compile.

## Version of Realm and Tooling
Realm version: Last
Xcode version: Last
iOS/OSX version: Last
Dependency manager + version: Last CocoaPods

**Comment by bdash** [comment]
I think there's a little confusion between the use of protocols on `RLMArray` properties to specify the object type contained in the array, and the use of Objective-C generics. The use of a protocols, declared using `RLM_ARRAY_TYPE`, is required and does not cause any problems with declaration order. The use of Objective-C generics is entirely optional, and can be awkward to use when declaring classes that reference each other. If we ignore generics then your example can be declared as follows:

```objc
@interface Group : RLMObject
@property (readonly) RLMLinkingObjects *items;
@end

@interface Tag : RLMObject
@property (readonly) RLMLinkingObjects *items;
@end
RLM_ARRAY_TYPE(Tag);

@interface Item : RLMObject
@property RLMArray<Tag> *tags;
@property Group  *group;
@end
```

To incorporate Objective-C generics you can either omit them from one side of the relationship, or you can [make use of class extensions to declare some properties after the inheritance information is available](http://stackoverflow.com/a/36987537/1991710).

**Comment by ashvar** [comment]
Have been doing the exact same way, just was worried about any potential undefined behavior in the future.

Thanks for fast respond!

**Comment by jpsim** [comment]
Glad to hear @bdash's comment cleared this up for you @ashvar!
