### ISSUE TITLE
Attempting to open an encrypted realm configured with deleteIfMigrationNeeded=true, using a wrong encryption key, causes an internal exception to be thrown, which cannot be caught

### ISSUE THREAD

**Issue by kaspermunck** [realm/realm-cocoa#3961]
## Goals
I want to be able to detect when a realm could not be created due to a wrong encryption key being used to open it, even though `deleteIfMigrationNeeded` is `true`.

## Expected Results
When creating an encrypted realm using the following code, I expect the `catch` statement to be reached if an exception is thrown:

```
var configuration = Realm.Configuration.defaultConfiguration
configuration.deleteRealmIfMigrationNeeded = true
configuration.encryptionKey = // wrong encryption key

var realm: Realm!
do {
    realm = try Realm(configuration: configuration)
}
catch let error {
    print("Could not create realm: \(error)")
}
```

## Actual Results
I expect the catch statement to be reached if a wrong encryption key was used, so I can properly react to the error. Instead, the following exception is thrown, but is not caught by the `catch` statement:

> Unable to open a realm at path '.../default.realm': Realm file decryption failed. The app crashes leaving me unable to detect, nor handle, the error.

The problem seems to be caused by `deleteIfMigrationNeeded = true`. See also [this StackOverflow question](http://stackoverflow.com/questions/38850290/unable-to-catch-realmfileexception-realm-file-decryption-failed-exception).

## Steps to Reproduce

1. Create an encrypted realm using the code above
2. Attempt to open the realm using a different encryption key

## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: 7.3.1 (7D1014)

iOS/OSX version: iOS 9.3

Dependency manager + version: CocoaPods 1.0.0

**Comment by kaspermunck** [comment]
Seems like this has been fixed with [1f2090d](https://github.com/realm/realm-object-store/commit/1f2090dd2faaa34b587d04ddcf3ca76efc8acdb2).

**Comment by jpsim** [comment]
@kaspermunck could you please test against the tip of `master` and let us know if you're still seeing this issue or if it's been resolved? If using CocoaPods, update your Podfile to the following:

```ruby
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
```

**Comment by kaspermunck** [comment]
@jpsim I ran my sample project against the tip of `master` and could not reproduce the problem. I.e. the exception is caught as expected.

**Comment by stel** [comment]
Awesome! Thanks @kaspermunck!
