### ISSUE TITLE
Migrate to Swift 3 Beta 6

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3962]
https://github.com/realm/realm-cocoa/pull/3965#discussion_r75223497

**Comment by sprint84** [comment]
I still can't compile using Swift 3.0, anyone has a workaround?

**Comment by JadenGeller** [comment]
Are you using https://github.com/realm/realm-cocoa/pull/3965#discussion_r75223497? It still hasn't been merged into master. Almost there…! 💃

**Comment by JadenGeller** [comment]
@sprint84 Try building with master now! It's merged.
