### ISSUE TITLE
UIViewController Memory Leak when I add a Result<T> as a property.

### ISSUE THREAD

**Issue by jpmcglone** [realm/realm-cocoa#3963]
## Goals
Fix memory leak.

## Expected Results
No memory leak.

## Actual Results
Memory leak.

## Steps to Reproduce
I added
```
var chats: Results<Chat>!
```
to my UIViewController subclass. Then set that result to a very specific set of Chat objects using `realm.objects(Chat).filter("...")`
This makes it so that my UIViewController never deinits.

If I never set the chats var to anything, it deinits just fine.

What could cause this?

*More info*
I am presenting my UIViewController inside another custom UIViewController that uses View Controller containment. I'm sure the containment is fine because I get no memory leak when presenting any other UIViewController, or even my "ChatListViewController" when I don't set the var "chats" to something in the realm database.

I feel like I've narrowed it down to that causing the leak, but I can't imagine why setting self.chats to a Results object would create some sort of retain cycle. :(

## Code Sample

```
    // ChatListViewController.swift
    var chats = User.me!.chats.filter("name != nil").sorted("lastActivity", ascending: false)
```
```
    // User.swift
    static var me: User? {
        return Auth.currentAuth?.user
    }
```
```
   // Auth.swift
   // var currentAuth: Auth? { ...
   get {
            let realm = try! Realm()
            // there should only be 1 or 0 in Auth
            return realm.objects(Auth).first
    }
    ...
    dynamic var user: User?
```

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.0.2

Xcode version: 7.3.1

iOS/OSX version: iOS 9.2

Dependency manager + version: Cocoapods 1.0.1

**Comment by stel** [comment]
Did you register to any notifications with `addNotificationBlock`? And could you please also provide us some more code related to how you use `chats` in your view controller?

**Comment by jpmcglone** [comment]
I did use addNotificationBlock.. where is the best place to dump that token? O_O

**Comment by jpmcglone** [comment]
I do this in 'viewWillAppear'
```
token = chats.addNotificationBlock { [weak self] changes in
            self?.reloadData()
}
```

and this is viewDidDisappear
```
token.stop()
```

**Comment by jpmcglone** [comment]
In addition to the token code above, here are all the ways I use chats in the VC:

```
func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return chats.count
}
```

```
let cell = tableView.dequeueReusableCellWithIdentifier("cell", forIndexPath: indexPath) as! ChatListTableViewCell

let chat = chats[indexPath.row]
cell.titleLabel.clearLinks()

ChatListViewModel.apply(chat, chatListTableViewCell: cell)
...
```

```
func showChatCard(cell: ChatListTableViewCell) {
    if let indexPath = chatListView.tableView.indexPathForCell(cell),
        name = chats[indexPath.row].name {
        RoutesManager.sharedManager.showChat(named: name, sender: self.parentViewController!)
    }
}
```

**Comment by jpmcglone** [comment]
I just tried removing the notification block--no improvements.

**Comment by stel** [comment]
Thanks for that info, @jpmcglone! All code samples you sent looks good to me and shouldn't lead to retain cycle. Can you make a test Xcode project to reproduce this issue?

It's hard to make any suggestions as I don't see all your code, but when you declare `chats` as `var chats = [Chat]()` it means that the number of cells in table view is 0 and no delegate methods get called, so I would recommend to start the investigation from there.

**Comment by jpmcglone** [comment]
With a blank project I cannot reproduce this issue :(

**Comment by jpmcglone** [comment]
@stel !!! The problem wasn't realm at all! It was a library I was using that has a memory leak in its closures. I was only calling the line that had that closure IF there was a chat in the list >_<

Closing. Thanks for the help!

**Comment by stel** [comment]
Happy to hear that you resolved that issue, @JadenGeller!
