### ISSUE TITLE
Support Swift native `Date` and `Data` types

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3968]
Requires parsing schemas that use `Date` and `Data` types. Also should ensure we have tests that use both these and their NS variants. We also want to make sure they're supported in both Realm Swift and Realm Objective-C from Swift.

**Comment by jpsim** [comment]
Done in #3965 for both Realm Swift & Realm Objective-C, @JadenGeller?

**Comment by JadenGeller** [comment]
Nope, I'm working on this now.

**Comment by JadenGeller** [comment]
Done in https://github.com/realm/realm-cocoa/pull/3979
