### ISSUE TITLE
Vet Realm Swift API `open` members

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3974]
We should probably discuss what members of `Object` should be open. I think most of them should be since user's want flexibility with their model objects, but there are some properties that clearly shouldn't be subclasses. We also are unable to _not_ mark certain properties as `open` since they inherit from Objective-C, which sucks. We might be able to work around this with `NS_REFINED_FOR_SWIFT`. I think most properties of others types (not `Object`) should _not_ be open, but we should think it over.

**Comment by austinzheng** [comment]
All the changes we want to make to `open` members have already been made in previous PRs.
