### ISSUE TITLE
Fix segfaulting Swift functions in Realm Objective-C

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3975]
Some of these issues are caused by Objective-C generics, and it looks like [disabling debug information](https://bugs.swift.org/browse/SR-2360) fixes some of them, but [not](https://bugs.swift.org/browse/SR-2348) [all](https://bugs.swift.org/browse/SR-1779). We also have an extension unrelated to generics that's segfaulting when commented out, so we need to figure out why that's happening.

**Comment by austinzheng** [comment]
Is this still a thing? If not I'm going to close this ticket.

**Comment by austinzheng** [comment]
If these happen to appear again, please open a new ticket. Thanks!
