### ISSUE TITLE
Getting error when inheriting from Object - Swift 3.0 Xcode 8 beta 6

### ISSUE THREAD

**Issue by hjuraev** [realm/realm-cocoa#3977]
## Goals

What do you want to achieve?

Run Realm in Xcode 8 beta 6 with Swift 3

## Actual Results

What did happened instead?  
Getting error when inheriting from Object class in model class

e.g. the stack trace of a crash

## Steps to Reproduce

You can reproduce it when defining model class 

## Code Sample

import Foundation
import RealmSwift

class CRM: Object {  
}
## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: Current branch

Xcode version: Xcode 8 beta 6

iOS/OSX version: iOS 10

Dependency manager + version: Cocoapods 1.0.1

<img width="541" alt="screen shot 2016-08-17 at 2 10 59 pm" src="https://cloud.githubusercontent.com/assets/5513926/17747805/76a28216-6484-11e6-9200-987c70032c9a.png">

**Comment by bdash** [comment]
> Realm version: Current branch

What branch are you referring to?

**Comment by JadenGeller** [comment]
I'd assume they're referring to master since `Object` is not yet marked `open` until https://github.com/realm/realm-cocoa/pull/3965 gets merged.

**Comment by hjuraev** [comment]
Im referring to branch: 'jg-swift-3-beta-6'

**Comment by JadenGeller** [comment]
Really!? Okay, that's surprising. It's 100% marked open. https://github.com/realm/realm-cocoa/pull/3965/commits/f8f34894fb677e2fdb6d26fb33c6ba45143d2974

**Comment by hjuraev** [comment]
I dont know why but this is error message I was receiving, but I just copied that filed manually and it worked.

**Comment by JadenGeller** [comment]
Sorry, I don't understand—you resolved this?

**Comment by hjuraev** [comment]
Yes, I had to manually copy that file. Thanks for help

**Comment by JadenGeller** [comment]
That's super bizarre, and I have no idea why that might happen. All the other files were correct though? And you're sure you're on the latest commit on that branch?

**Comment by hjuraev** [comment]
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'jg-swift-3-beta-6', :submodules => true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'jg-swift-3-beta-6', :submodules => true
I think Im using correct branch. I just copied content of object.swift file from link you provided and I was able to compile it successfully.

**Comment by JadenGeller** [comment]
@hjuraev Now that https://github.com/realm/realm-cocoa/pull/3965 is merged into master, is it working for you?

**Comment by jpsim** [comment]
Closing assuming this works since it was working for @hjuraev it the `jg-swift-3-beta-6` branch.
