### ISSUE TITLE
Require explicit specification of type for aggregate functions?

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3981]
Since Swift 3 gives us the opportunity to make breaking changes to our API, here's my pitch:

I think it would be safer to require users to explicitly specify property type when using aggregate functions.
```swift
results.sum(ofProperty: "foo", withType: Int.self)
```
Currently, the type is inferred based on context. This is bad because it can silently break user code. For example, if I were to call
```swift
bar(results.sum(ofProperty: "foo"))
```
a change in the API of `bar` could silently cause my code to start crashing.

Though the current API looks cleaner, a user will still have to specify the type (e.g. `as Int`) at the call-site, so it's really not that different. And as demonstrated the cases in which the type does not have to be specified are dangerous and should be avoided.

Thoughts? @bdash @tgoyne @austinzheng @jpsim

**Comment by jpsim** [comment]
I'm not so sure about this. I like the terseness of the current API. Since Realm's integer type represents all `Int` sizes, the `bar` API would have to change to say a `Double` for this to crash. Or vice-versa.

**Comment by JadenGeller** [comment]
It actually wouldn't crash in the case of a `Double` since the Objective-C API vends the results as a `NSNumber` which can be converted to a `Double` even if `Int` backed.

**Comment by JadenGeller** [comment]
@jpsim FYI, I don't necessarily feel strongly about this, just thought it was worth bringing up given we're making breaking changes. It does seem safer, but I admit it's a simplicity tradeoff.

That said, a user who writes
```swift
let x = results.sum(ofProperty: "foo")
```
would probably by the error message ("Generic parameter 'U' could not be inferred"), so it isn't clear to me that this API is simpler.

**Comment by jpsim** [comment]
> would probably be confused by the error message ("Generic parameter 'U' could not be inferred"), so it isn't clear to me that this API is simpler.

To me, that's an argument in favor of renaming the generic type parameter something more descriptive, such as `Result`.

**Comment by JadenGeller** [comment]
I feel this issue has been sufficiently discussed, so I'm closing it. I filed an issue for renaming our generic parameter types https://github.com/realm/realm-cocoa/issues/3991.
