### ISSUE TITLE
Dictionary parsing using Realm?

### ISSUE THREAD

**Issue by ranjitDhiman1990** [realm/realm-cocoa#3982]
How do I parse a Dictionary response using Realm? Please help with example.

Here is my response - 

"submission": {
    "qId1": {
      "answerString": "1001"
    },
    "qId2": {
      "answerString": "1001"
    },
    "qId3": {
      "answerString": "f"
    },
    "qId4": {
      "answerString": "1001"
    },
    "qId5": {
      "answerString": "1001"
    },
    "qId6": {
      "answerString": "f"
    },
    "qId7": {
      "answerString": "1001"
    },
    "qId8": {
      "answerString": "1001"
    },
    "qId9": {
      "answerString": "f"
    },
    "qId10": {
      "answerString": "1001"
    },
    "qId11": {
      "answerString": "1001"
    },
    "qId12": {
      "answerString": "f"
    }
  }

**Comment by stel** [comment]
@ranjitDhiman1990 please check JSON section in [Docs](https://realm.io/docs/swift/latest/#json), there is an example how to create Realm objects from a `JSON`. Also check [this list of useful frameworks](https://github.com/realm/realm-cocoa/issues/694#issuecomment-144785299).

Let us know if it helped and feel free to ask any specific questions!

**Comment by jpsim** [comment]
Closing since I think @stel's answer sufficiently covers this.
