### ISSUE TITLE
Carthage install instructions not working on iOS 7.3.1

### ISSUE THREAD

**Issue by paulfreeman** [realm/realm-cocoa#3987]
## Goals
 
Install Realm in a new Swift application

## Expected Results

I expected to follow the Carthage installation instructions on the Getting Started section of the Realm docs at Realm.io

## Actual Results
 
Following the instructions results in a linker error with frameworks not located. 

## Steps to Reproduce

Follow the Carthage installation instructions using Xcode 7.3.1 

 

## Code Sample
n/a

## Suggested fix 

Correct installation instructions.  With Xcode 7.3.1 simply dragging Realm.framework and RealmSwift.framework binaries into the embedded binaries section of the General tab in Xcode is all that is required.  The app store submission bug that the complex instructions addresses is an Xcode 6.x specific bug. 

This is a big time suck if you are new to using embedded binaries as you have to figure out why you are getting linker errors

## Version of Realm and Tooling
 
Realm version: ?  1.0.2

Xcode version: ?  7.3.1

iOS/OSX version: ?  El Capital 10.11.5

Dependency manager + version: ? Carthage

**Comment by jpsim** [comment]
> The app store submission bug that the complex instructions addresses is an Xcode 6.x specific bug.

This bug has still not been resolved as of Xcode 7.3.1 or with any of the Xcode 8 betas. Dynamic frameworks containing simulator architecture slices won't be stripped when archiving an app for submission to the App Store.

Carthage also lists this as required in their usage instructions: https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos.

---

If you're experiencing linker errors, please try following the steps detailed in the [Reinstalling Via Dependency Managers](https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers) section of our docs.
