### ISSUE TITLE
Fix Realm.io's documentation

### ISSUE THREAD

**Issue by haydenholligan** [realm/realm-cocoa#3988]
Since there's no direct contact on realm.io, I guess I'll try here?

https://realm.io/docs/swift/latest/#models

`// Get the default Realm`
`let realm = try! Realm()`

That produces an error in Swift. I believe it should be let realm = RLMRealm.defaultRealm()

`let puppies = realm.objects(Dog.self).filter("age < 2")`

If you try that, you get "Module 'Realm' has no member named "objects". I read around and think it should be Dog.allobjects().objectsWithPredicate(predicate: NSPredicate)

`// Persist your data easily`
`try! realm.write {`
`  realm.add(myDog)`
`}`

this produces an error, assuming realm is RLMRealm.defaultRealm(). Value of type 'RLMRealm' has no member 'write'. Believe it should be try! realm.transactionWithBlock { }

These were in the first few paragraphs of the swift docs. How out of date are they?

**Comment by bdash** [comment]
`RLMRealm` is from the Objective-C API provided by Realm.framework.`Realm` is the equivalent type in the native Swift API provided by RealmSwift.framework. The Swift documentation covers the latter.

**Comment by haydenholligan** [comment]
Yep. That's why I closed it. I think I followed a tutorial from where RealmSwift wasn't yet a thing and RLMRealm was used in swift. Fixing my codebase now :)

**Comment by JadenGeller** [comment]
@bdash @jpsim I wonder if it would be worthwhile to rename `Realm.framework` to `RealmObjC.framework`?

**Comment by bdash** [comment]
Seems like an unnecessary breaking change.

**Comment by tgoyne** [comment]
We talked about doing that when we first added the Swift binding, but didn't because it's gross and thought that having RealmSwift depend on RealmObjectiveC would also be confusing.
