### ISSUE TITLE
Building on Xcode 8 beta 4 for Swift 3

### ISSUE THREAD

**Issue by ph1ps** [realm/realm-cocoa#3990]
## Goals

Build RealmSwift in Xcode 8 beta 4 and Swift 3

## Expected Results

The build works

## Actual Results

I got over 120 build errors
![bildschirmfoto 2016-08-22 um 10 47 34](https://cloud.githubusercontent.com/assets/5064728/17848839/ff19b81a-6855-11e6-8762-bba4d4363982.png)

## Steps to Reproduce

git clone --recursive https://github.com/realm/realm-cocoa.git
Open project in Xcode beta 4, select RealmSwift as target and build

## Code Sample

No samples needed

## Version of Realm and Tooling

Realm version: latest

Xcode version: 8 beta 4

iOS/OSX version: 10/sierra

Dependency manager + version: ---

**Comment by bdash** [comment]
Realm's master currently supports Xcode 8 beta 6.
