### ISSUE TITLE
Improve naming of generic parameters

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3991]
We ought to use more descriptive generic parameter names. Our current naming leads to confusing error messages in pretty common cases.

``` swift
let x = results.sum(ofProperty: "foo")
```

For example, the above line of code will fail to compile with error "Generic parameter 'U' could not be inferred." What is `U`? Maybe it would be better named `Result` or `PropertyType`.

**Comment by austinzheng** [comment]
This isn't actually a breaking change, but it would be fitting to fold it into Realm Cocoa 3.0.

**Comment by jpsim** [comment]
Presumably using Swift 3.2+ Smart KeyPaths would allow us to provide a typesafe version of these aggregate functions.

**Comment by austinzheng** [comment]
Fixed in #5273.
