### ISSUE TITLE
High frequency Random Crash

### ISSUE THREAD

**Issue by eigo0109** [realm/realm-cocoa#3993]
## Goals

any time in application, it's totally random. 

## Expected Results

not crash

## Actual Results

> Attempted to dereference garbage pointer 0x40000000147481bd. Originated at or in a subcall of realm::Column<double>::average(unsigned long, unsigned long, unsigned long, unsigned long*) const
KSCrash  VideoGo                  101c8f4b0  realm::Column::average(unsigned long, unsigned long, unsigned long, unsigned long*) const  29422768
KSCrash  VideoGo                  101c8f288  realm::Column::average(unsigned long, unsigned long, unsigned long, unsigned long*) const  29422216
KSCrash  VideoGo                  101c8bed8  realm::Column::average(unsigned long, unsigned long, unsigned long, unsigned long*) const  29408984
KSCrash  VideoGo                  101cdf7fc  CUDTUnited::TLSDestroy(void*)                                                                      29751292
KSCrash  VideoGo                  101ce53f8  CUDTUnited::TLSDestroy(void*)                                                                      29774840

> Application threw exception NSInvalidArgumentException: (null) Originated at or in a subcall of realm::Column<double>::average(unsigned long, unsigned long, unsigned long, unsigned long*) const
KSCrash  VideoGo                  101bb974c  realm::Column::average(unsigned long, unsigned long, unsigned long, unsigned long*) const  28890956
KSCrash  VideoGo                  101ccd980  CUDTUnited::TLSDestroy(void*)                                                                      30022016
KSCrash  VideoGo                  101ccbecc  CUDTUnited::TLSDestroy(void*)                                                                      30015180
KSCrash  VideoGo                  101ccf4f8  CUDTUnited::TLSDestroy(void*)                                                                      30029048
KSCrash  VideoGo                  101c1f234  realm::Column::average(unsigned long, unsigned long, unsigned long, unsigned long*) const  29307444
KSCrash  VideoGo                  101c1be00  realm::Column::average(unsigned long, unsigned long, unsigned long, unsigned long*) const  29294080
KSCrash  VideoGo                  101c174b0  realm::Column::average(unsigned long, unsigned long, unsigned long, unsigned long*) const  29275312
KSCrash  VideoGo                  10194332c  realm::Column::average(unsigned long, unsigned long, unsigned long, unsigned long*) const  26309420

## Steps to Reproduce

Totally random. We have 10 crash reports in 1 hour on 6 device  in our application. it may crash at any time.

**We just import Realm.framework in application , and import <Ream/realm.h> in some model file. In fact,  we did not use those model file . so Realm should not be used when app running. but the crash happened**  

## Code Sample

it crash totally random, not at some special codes.

## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: 7.3

iOS/OSX version: ios9.x macos 10.11.6

**Comment by eigo0109** [comment]
http://bughd.com/share/issue/e335a21af3262985df60873a5a9821eb

**Comment by jpsim** [comment]
Hi @eigo0109, if this bug is so easy to trigger, could you please share a project that reproduces this? We've never seen the behavior you're experiencing.

**Comment by jpsim** [comment]
@eigo0109 we'd love to work with you on this.

**Comment by eigo0109** [comment]
thank u @jpsim. In the latest version, we don't find this problem again.
