### ISSUE TITLE
Subscripting crashes when cast to `Int8`/`Int16`/`Int32`/`Int64`

### ISSUE THREAD

**Issue by JadenGeller** [realm/realm-cocoa#3995]
Currently Swift subscript is of type `Any?`. As such, we cannot return a different type based on context, so we always return the Objective-C types. Most of these types are implicitly bridged, but those that aren't might unexpectedly cause crashes.

``` swift
foo["intCol"]  as! Int  // 😎
foo["int8Col"] as! Int8 // crash!
```

The workaround is to access the value as an `NSNumber` and then explicitly bridge.

``` swift
(foo["int8Col"] as! NSNumber).int8Value // 😎
```

There are 2 potential ways to solve this. Both break some existing code:
- Convert to Swift property type before returning value. We can look this type up by property name in the schema. Note that this will silently break existing code that assumes `Int8`/`Int16`/`Int32`/`Int64` values are returned as `NSNumber`, which isn't implicitly bridged.
- Supplement `Any?` function with overloads for every possible type so that Swift can infer correct version based on context. This code require a lot of boilerplate. Also, this breaks using subscript in `Any` contexts due to Swift's overload resolution rules.

An ideal solution requires a change in Swift. We could also wait for either:
- Swift adds generic subscripts, allowing us to return `T?` and perform the bridging in the function based on the inferred type.
- Swift adds implicit bridging between `NSNumber` and `Int8`/`Int16`/`Int32`/`Int64`. Note that while this solution may seem ideal (if fixed in Swift), the generic solution is probably preferable since it doesn't rely on any Objective-C compatibility features (and thus would be easier to mirror in a pure Swift API).

EDIT: This issue should also track KVC's lack of bridging which crashes due to the same issue. This is probably slightly less problematic because it's an `NSObject` API more than a Realm API.

**Comment by DominicFrei** [comment]
This was implemented in Swift meanwhile.
https://github.com/realm/realm-cocoa/pull/7057 adds the tests to make sure it works.
