### ISSUE TITLE
Update primary key implementation to use `SetUnique` instruction

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#3998]
See realm/realm-core#2026, realm/realm-object-store-private#12 and realm/realm-object-store#137 for existing related work on this.

**Comment by bigfish24** [comment]
Is this in the object store.... if not any reason why this code isn't there?

**Comment by jpsim** [comment]
> if not any reason why this code isn't there?

Yes, the pk functionality in the object store is entangled with its `object` accessor class, which cocoa doesn't use due to incompatible designs. There isn't an appreciable amount of common code that could be consolidated at this time.

**Comment by tgoyne** [comment]
The overwhelming majority of the object accessor code in every binding has been very specific to the target language, with only the most trivial details being the same between them.

**Comment by bigfish24** [comment]
ok just curious, seems like there can be clean up later but that it would slow things down right now

**Comment by jpsim** [comment]
No, there's no clean up to be had. That's what @tgoyne and I are trying to say.

**Comment by bigfish24** [comment]
fair enough but your comment "cocoa doesn't use due to incompatible designs" seemed to imply that this means the object store could be adapted to support the necessary design. Just didn't understand that, and at any rate, its not worth debating

**Comment by jpsim** [comment]
Done in #4003.
