### ISSUE TITLE
iOS Swift - Data not reflecting on other thread on updation

### ISSUE THREAD

**Issue by girishnair12345** [realm/realm-cocoa#4001]
**Bug**: iOS- Swift : Data not reflecting on other thread on updation 

## Code Sample

    class TestClass: NSObject {
    
    func initialize(){
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
            self.runThroughMsg()
        }
    }
    
    func addObject(msg:String){
        let obj = TestTable()
        obj.message = msg
        let realm = try! Realm()
        try! realm.write({ () -> Void in
            realm.add(obj,update: false)
        })
        
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
            let realm = try! Realm()
            let requests = realm.objects(TestTable.self)
            print("Add Total Items \(requests.count)")
        }
    }
    
    func runThroughMsg(){
        while true {
            let realm = try! Realm()
            let requests = realm.objects(TestTable.self)
            if requests.count > 0 {
                let requestsObject = requests.first
                NSThread.sleepForTimeInterval(1)
                let realm = try! Realm()
                try! realm.write({ () -> Void in
                    realm.delete(requestsObject!)
                })
                print("Running Request. Items remaining \(requests.count)")
            }else{
                print("Sleeping")
                NSThread.sleepForTimeInterval(5)
            }
        }
    }
    
}
    
    class TestTable :Object {
        dynamic var message:String? = nil
    }

## Steps to Reproduce
Create the instance of the TestClass and initialize it

    let test = TestClass()
    test.initialize()

In this initialize method I am creating a thread that runs indefinitely to access the data

now if i add an object 

    test.addObject("Msg")

then the while loop doesnt receive the new data !!!

Let me know if I am doing anything wrong

Realm version: 0.103.0

Xcode version: 7.3

iOS/OSX version: iOS 9.3, Swift 2.2

Dependency manager + version: 0.39.0

Note: I had tried using the new version of pod and realm but the project stopped compiling after upgrading so i had to downgrade

**Comment by jpsim** [comment]
From the [Seeing Changes From Other Threads](https://realm.io/docs/swift/latest/#seeing-changes-from-other-threads) section of our docs:

> When you initially open a Realm on a thread, its state will be based off the most recent successful write commit, and it will remain on that version until refreshed. Realms are automatically refreshed at the start of every runloop iteration, unless Realm's `autorefresh` property is set to `NO`. If a thread has no runloop (which is generally the case in a background thread), then `Realm.refresh()` must be called manually in order to advance the transaction to the most recent state.

So in other words, the thread backing the dispatch queue you create in `initialize()` doesn't have a runloop, so `autorefresh` is turned off, which means that you need to explicitly call `Realm.refresh()` to update to the latest state.

I suggest you read our docs on [Threading](https://realm.io/docs/swift/latest/#threading) for more information.

---

> Note: I had tried using the new version of pod and realm but the project stopped compiling after upgrading so i had to downgrade

Could you please follow the steps listed [here](https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers) and if you're still experiencing installation issues, file a new issue detailing what's failing? Thanks.

**Comment by girishnair12345** [comment]
Ya its working now,
I have a generic class that fetches data from the database independent on what thread its being called on, So if i call refresh on each update will there be any memory implications or performance impact in any manner ??

**Comment by jpsim** [comment]
> Ya its working now

🎉 

> So if i call refresh on each update will there be any memory implications or performance impact in any manner ??

Eagerly refreshing won't have too much of a performance impact, though it will advance all existing references to objects/results/etc (accessors) which will incur work that's linearly proportional to the number of accessors.
