### ISSUE TITLE
Unable to open a realm at path, open() failed: Operation not permitted

### ISSUE THREAD

**Issue by narup** [realm/realm-cocoa#4004]
Team, 

I am getting this error/crash during Realm initialization on my production app. I am never able to reproduce it though. But it's happening during the app launch. Any specific reason?

Here's the detail error:

> Realm initialization failed, Error:Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/796F6052-65E1-4CD8-AB8E-94EF56F3B31E/Documents/db_realm_V4.realm.lock': open() failed: Operation not permitted." UserInfo={Error Code=2, NSFilePath=/var/mobile/Containers/Data/Application/796F6052-65E1-4CD8-AB8E-94EF56F3B31E/Documents/db_realm_V4.realm.lock, Underlying=open("/var/mobile/Containers/Data/Application/796F6052-65E1-4CD8-AB8E-94EF56F3B31E/Documents/db_realm_V4.realm.lock") failed: Operation not permitted, NSLocalizedDescription=Unable to open a realm at path '/var/mobile/Containers/Data/Application/796F6052-65E1-4CD8-AB8E-94EF56F3B31E/Documents/db_realm_V4.realm.lock': open() failed: Operation not permitted.}.

Here's the initialization code:

```
// Use the default directory, but replace the filename with the username
        config.fileURL = config.fileURL!.URLByDeletingLastPathComponent?
            .URLByAppendingPathComponent("db_realm_V4.realm")

        // Set this as the configuration used for the default Realm
        Realm.Configuration.defaultConfiguration = config
        do {
            DataContext.sharedContext._realm = try Realm(configuration: config)
        } catch let error as NSError {
            Logger.logError(Tag.REALM, level: LogLevel.ERROR, error: error)
            Logger.logValue("Realm initialization failed, Error:\(error).", key: "REALM-SETUP")
        }
```

Realm version: ?
1.0.1
Xcode version: ?
7.3.1
iOS/OSX version: ?
Any version
Dependency manager + version: ?
pod, 0.39.0

Thanks

**Comment by chika-kasymov** [comment]
@narup I have the same issue on production. I reproduced bug by installing old version from Fabric, then installing new app from AppStore. 

My error looks like this:
```
Packaged report with id 'd7e818ff7a8a4a65bcf9b7dc3be5aa6d' for submission
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/private/var/mobile/Containers/Shared/AppGroup/33542836-9329-400F-B1E1-28C250836A0F/db.realm'" UserInfo={NSFilePath=/private/var/mobile/Containers/Shared/AppGroup/33542836-9329-400F-B1E1-28C250836A0F/db.realm, NSLocalizedDescription=Unable to open a realm at path '/private/var/mobile/Containers/Shared/AppGroup/33542836-9329-400F-B1E1-28C250836A0F/db.realm', Error Code=2}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54
```

I use custom path for database:
static let directory: NSURL = ```
NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier("group.com.example.App")!
static let realmPath = directory.URLByAppendingPathComponent("db.realm")
static let realm = try! Realm(path: realmPath.path!)
```

And make migration at `didFinishLaunchingWithOptions` method:
```
Realm.Configuration.defaultConfiguration = Realm.Configuration(
    schemaVersion: 2,
    migrationBlock: { migration, oldSchemaVersion in
        if (oldSchemaVersion < 1) {
            migration.enumerate(Card.className()) { oldObject, newObject in
                newObject!["xyz"] = newValue
            }
        }
        if oldSchemaVersion < 2 {
            migration.enumerate(Card.className()) { oldObject, newObject in
                newObject!["abc"] = 0
            }
        }
})
```

On first migration everything worked fine, but when I made second migration on this week crashes occurred for users who already had app.

**Comment by narup** [comment]
Realm Team, 

Any idea what could be the solution on this? We see this crash a lot in our Crashlytics logs. Any pointers would be helpful. 

Thanks
Puran

**Comment by chika-kasymov** [comment]
After updating Realm to 1.x.x version error disappeared. Before I used 0.9x.x version.

**Comment by narup** [comment]
I am using 1.0.1, I think this link https://realm.io/docs/objc/latest/#using-realm-with-background-app-refresh, does explain what could be happening. But, I am not too sure on opting out of iOS encryption. Even if I enable Realm encryption, then I am not sure if our existing users can upgrade seamlessly

**Comment by narup** [comment]
Any response from Realm team would have been helpful.

**Comment by austinzheng** [comment]
Apologies for not responding earlier. Unfortunately, we are only able to offer support on a best-effort basis.

You will either need to configure iOS encryption as specified in the link, or migrate your users's data to an encrypted Realm file by copying over the data. If you have further questions, please feel free to open another ticket.

**Comment by narup** [comment]
Hello,

Even after using NSFileProtectionNone, I got a not permitted crash. 
iOS 10 version
Device iPhone 5C
12% RAM Free 

Realm initialization failed, Error:Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/D9D0C1EE-B2F0-44D1-A7C0-B411822A2DA5/Documents/PhilDB/realm_phildb_V0.realm.lock': open() failed: Operation not permitted." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/D9D0C1EE-B2F0-44D1-A7C0-B411822A2DA5/Documents/PhilDB/realm_phildb_V0.realm.lock, Error Code=2, NSLocalizedDescription=Unable to open a realm at path '/var/mobile/Containers/Data/Application/D9D0C1EE-B2F0-44D1-A7C0-B411822A2DA5/Documents/PhilDB/realm_phildb_V0.realm.lock': open() failed: Operation not permitted., Underlying=open("/var/mobile/Containers/Data/Application/D9D0C1EE-B2F0-44D1-A7C0-B411822A2DA5/Documents/PhilDB/realm_phildb_V0.realm.lock") failed: Operation not permitted}.

Here's my code:

do {
            let realm = try Realm(configuration: config)
            let folderPath = realm.configuration.fileURL!.URLByDeletingLastPathComponent!.path!

            // Disable file protection for this directory
            try NSFileManager.defaultManager().setAttributes([NSFileProtectionKey: NSFileProtectionNone],
                                                             ofItemAtPath: folderPath)
        } catch let error as NSError {
            Logger.logError(PhilTag.REALM, level: LogLevel.ERROR, error: error)
            Logger.logValue("Realm initialization failed, Error:\(error).", key: "REALM-SETUP")
        }

**Comment by kosiakMD** [comment]
+1, the same

**Comment by austinzheng** [comment]
Please file a new issue and fill out the Issue Template, rather than commenting on a closed issue. Thank you!
