### ISSUE TITLE
Realm fails to identity Swift classes with `@objc` names

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-cocoa#4005]
## Goals

> [RealmSwiftObject defaultPropertyValues]: unrecognized selector sent to class 0x10b135cf0
> 
> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RealmSwiftObject defaultPropertyValues]: unrecognized selector sent to class 0x10b135cf0'
> Just one line code

I got above errors with below single line code.

``` swift
let o = Object()
```
## Expected Results

I want to get an unmanaged instance of Object.
## Actual Results

What did happened instead?  
crash
## Steps to Reproduce
1. create a new iOS 10 project.
2. add realm frameworks
3. import RealmSwift and add below code

```
override func viewDidLoad() {
    super.viewDidLoad()

    let o = Object()
}
```
1. run the project
   ## Code Sample
   see above
## Version of Realm and Tooling

Xcode 8 beta 6, Realm Cocoa master #ec83637. Swift 3.

**Comment by JadenGeller** [comment]
The issue is that `Object` is given the `@objc` name `RealmSwiftObject`. In our codebase, we're determining if a class is a Swift class by checking if the name contains a `.` indicating its module scoped. This is not necessary true of classes that are given an `@objc` name, so we ought to find a better way to detect this.

**Comment by JadenGeller** [comment]
True. I wish we could disallow calling `init()` without making subclass init also uncallable, but I don't think that's possible.

**Comment by JadenGeller** [comment]
If we can't prevent it from happening, we should at least make it work in the least surprising way. Alternatively, we could make it crash at runtime with a reasonable error message. If so though, this ought to be tracked in a separate issue.

**Comment by JadenGeller** [comment]
FYI, looks like this bug is not related to Swift 3; it's also broken in 2.x.

**Comment by owenzhao** [comment]
I was implementing an unmanagedCopy() function in Object extension. My theory is using Object() and objectSchema to get a subclass instance. Something like below

```swift
class Dog:Object{
    dynamic var name = "doggy"
} 

extension Object{
    func unmanagedCopy() -> Object {
        let o = Object()
        for p in objectSchema.properties{
            let value = self.value(forKey:p.name) 
            switch (p.type) {
                ...
            default:
                o.set(value, forKey:p.name) 
            } 
        } 
        return o
    }  
} 

let dog1 = Dog()
// realm write, add dog1
let dog2 = dog1.unmanagedCopy() as! Dog 
// ...
```

Since Object() didn't work, I managed to use a global function version, using generics, which is better than my first thought.

```swift
func unmanagedCopy<T>(_ i:T) -> T where T:Object
```

**Comment by JadenGeller** [comment]
Does using `type(of: self).init()` instead of `Object` fix this? While you're at it, you might want to change the return value to `Self` instead of `Object` as well.

**Comment by owenzhao** [comment]
@JadenGeller Many thanks. `type(of: self).init()` and `Self` works fine!

**Comment by santhoshs5** [comment]
I didn't understand the context fully how can I get the unmanaged object from.
 Realm. unmanagedCopy??

**Comment by jpsim** [comment]
@santhoshs5 Realm object's `init(value:)` initializer can accept a KVC-compliant value that responds to all the required property keys, you can pass a managed object to the initializer to make an unmanaged copy, and vice-versa.
