### ISSUE TITLE
RLMResults bug with notification for deletion

### ISSUE THREAD

**Issue by Oleygen** [realm/realm-cocoa#4015]
## Goals
I was using realm notification for UITableView to keep table up-to-date with data and properly animate insertions/deletions/modifications. 

## Expected Results
When I delete an item from realm, notification block property change.deletions should contain one element and no elements in change.insertions

## Actual Results
When I delete an item from realm, notification block property change.deletions contains two element and one more in change.insertions

## Steps to Reproduce
Create new project. Add realm as pod control. Copy and paste related code to default ViewController. Run and click "Delete realm item".

## Code Sample

```
#import <Realm/Realm.h>

@interface MyRLMObject : RLMObject
@property(nonatomic, strong) NSString *text;
@end

@implementation MyRLMObject
@end

#import "ViewController.h"
@interface ViewController ()
@property (nonatomic, strong) RLMResults<MyRLMObject *> *dataSource;
@property(nonatomic, strong) RLMNotificationToken *token;
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    // Add button for item deletion
    UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
    [button setTitle:@"Delete realm item" forState:UIControlStateNormal];
    [button addTarget:self action:@selector(didClickDeleteButton:) forControlEvents:UIControlEventTouchUpInside];
    button.frame = CGRectMake(0, 0, 150, 50);
    [self.view addSubview:button];
   
    // put 100 items in realm
    for (int i = 0; i < 100; i++) {
        MyRLMObject *obj = [[MyRLMObject alloc]init];
        obj.text = [NSString stringWithFormat:@"string #%i",i];
        [[RLMRealm defaultRealm] transactionWithBlock:^{
            [[RLMRealm defaultRealm] addObject:obj];
        }];
    }
    
    // set dataSource
    self.dataSource = [MyRLMObject allObjects];

    // create notification token
    self.token = [self.dataSource addNotificationBlock:^(RLMResults * _Nullable results, RLMCollectionChange * _Nullable change, NSError * _Nullable error) {
        if (change.deletions.count) {
            NSLog(@"%@", change.deletions);
            //output:
            //(
            //0,
            //99
            //)

        }
        if (change.insertions.count) {
            NSLog(@"%@", change.insertions);
            //output:
            //(
            //0
            //)
        }
    }];
}

- (void)didClickDeleteButton:(UIButton *)sender {
   
    //delete item at index 0 (also works with any index)
    MyRLMObject *obj = self.dataSource[0];
    [[RLMRealm defaultRealm] transactionWithBlock:^{
        [[RLMRealm defaultRealm] deleteObject:obj];
    }];
}

@end
```

## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: 7.3.1

iOS/OSX version: Deployment target iOS 8.0+ / Mac OS X 10.11.6

Dependency manager + version: Cocoapods 0.39.0

**Comment by tgoyne** [comment]
This is working as intended. Objects in a Realm do not have a stable order, and the notification is correctly telling you that the order has changed. If you want a stable order, you must sort on a property which gives that order.

**Comment by Oleygen** [comment]
I've searched a lil more and found other related issues created by users (for example: https://github.com/realm/realm-cocoa/issues/3865).
Can you reflect this behavior (unreliable order when delete items) on documentation please. I couldn't find any information related to this issue at https://realm.io/docs/objc/latest/api/Classes/RLMResults.html.

Anyway, love your project very much.
Best regards.

**Comment by jpsim** [comment]
This is documented in the [Sorting](https://realm.io/docs/objc/latest/#sorting) section of our docs:

> Note that the order of `Results` is only guaranteed to stay consistent when the query is sorted. For performance reasons, insertion order is not guaranteed to be preserved. If you need to maintain order of insertion, some solutions are proposed [here](https://realm.io/docs/objc/latest/#realm-doesnt-have-auto-incrementing-properties).
