### ISSUE TITLE
Add support for adding tags to RLMResult

### ISSUE THREAD

**Issue by crrobinson14** [realm/realm-cocoa#4029]
## Goals

Add support for adding a tag to a RLMResult collection.

## Expected Results

Notifications are a HUGE improvement in terms of keeping UITableViews up to date with changes in a RLMResults collection. However, it's a little tricky to reuse code between them. It works fine for simple tables with one section, or hard-coded cases where the sections are known. But I find myself repeating a lot of nearly-identical notification-listener code between controllers.

What I would love to see is the ability to add a tag to the RLMResult object after obtaining it. I could then make a generic "updateTableViewSection" method in a utility class or category and pass it the notification received, a reference to the tableview, and the result set.

My primary purpose is to provide a more generic way to track a data set tied to a tableview section to pass to the `RLMCollectionChange ...InSection` helper methods. But this is just one use-case - I could imagine that tags would be useful for other cases as well.

## Code Sample

This is the block I'm repeating everywhere. It's dupe code across viewcontrollers, which is ugly but tolerable. But in viewcontrollers with multiple tableview sections, especially where those sections come from different queries, it quickly becomes a LOT of duplicated code.

```
    __weakSelf weakSelf = self;
    _notificationToken1 = [self.unreadShares addNotificationBlock:^(RLMResults *data, RLMCollectionChange *changes, NSError *error) {
        if (error) {
            NSLog(@"Failed to open Realm on background worker: %@", error);
            return;
        }

        UITableView *tableView = weakSelf.tableView;

        // Initial run of the query will pass nil for the change information
        if (!changes) {
            [tableView reloadData];
            return;
        }

        // changes is non-nil, so we just need to update the tableview
        [tableView beginUpdates];
        [tableView deleteRowsAtIndexPaths:[changes deletionsInSection:0] withRowAnimation:UITableViewRowAnimationAutomatic];
        [tableView insertRowsAtIndexPaths:[changes insertionsInSection:0] withRowAnimation:UITableViewRowAnimationAutomatic];
        [tableView reloadRowsAtIndexPaths:[changes modificationsInSection:0] withRowAnimation:UITableViewRowAnimationAutomatic];
        [tableView endUpdates];
    }];
```

What I would love to do:

```
+ (void)processRealmTVUpdates:(UITableView *)tableView withResults:(RLMResults *)results andChangeset:(RLMCollectionChange *)changes error:(NSError *)error {
    NSUInteger section = [results.tag integerValue];

    if (error) {
        NSLog(@"Failed to open Realm on background worker: %@", error);
        return;
    }

    // Initial run of the query will pass nil for the change information
    if (!changes) {
        [tableView reloadData];
        return;
    }

    // changes is non-nil, so we just need to update the tableview
    [tableView beginUpdates];
    [tableView deleteRowsAtIndexPaths:[changes deletionsInSection:section] withRowAnimation:UITableViewRowAnimationAutomatic];
    [tableView insertRowsAtIndexPaths:[changes insertionsInSection:section] withRowAnimation:UITableViewRowAnimationAutomatic];
    [tableView reloadRowsAtIndexPaths:[changes modificationsInSection:section] withRowAnimation:UITableViewRowAnimationAutomatic];
    [tableView endUpdates];
}

- (void)viewDidLoad {
    RLMResults *results = [MyType somePredefinedQuery];
    results.tag = @0;

    __weakSelf weakSelf = self;
    token = [self.unreadShares addNotificationBlock:^(RLMResults *data, RLMCollectionChange *changes, NSError *error) {
        [MyHelperClass processRealmTVUpdates:weakSelf.tableView withResults:data andChangeset:changes error:error];
    }];
}
```

I probably have a thousand lines of this boilerplate in the app I'm currently working on.

**Comment by tgoyne** [comment]
You can just capture the tag in the notification block and explicitly pass it in to your helper:

    + (void)processRealmTVUpdates:(UITableView *)tableView withResults:(RLMResults *)results andChangeset:(RLMCollectionChange *)changes section:(NSUInteger)section error:(NSError *)error {
        if (error) {
            NSLog(@"Failed to open Realm on background worker: %@", error);
            return;
        }

        // Initial run of the query will pass nil for the change information
        if (!changes) {
            [tableView reloadData];
            return;
        }

        // changes is non-nil, so we just need to update the tableview
        [tableView beginUpdates];
        [tableView deleteRowsAtIndexPaths:[changes deletionsInSection:section] withRowAnimation:UITableViewRowAnimationAutomatic];
        [tableView insertRowsAtIndexPaths:[changes insertionsInSection:section] withRowAnimation:UITableViewRowAnimationAutomatic];
        [tableView reloadRowsAtIndexPaths:[changes modificationsInSection:section] withRowAnimation:UITableViewRowAnimationAutomatic];
        [tableView endUpdates];
    }

    - (void)viewDidLoad {
        RLMResults *results = [MyType somePredefinedQuery];
        NSUInteger section = 0;

        __weakSelf weakSelf = self;
        token = [self.unreadShares addNotificationBlock:^(RLMResults *data, RLMCollectionChange *changes, NSError *error) {
            [MyHelperClass processRealmTVUpdates:weakSelf.tableView withResults:data andChangeset:changes section:section error:error];
        }];
    }

**Comment by crrobinson14** [comment]
That's what I'm doing today. But if a tag can be included in the result, further cleanup would be possible by making the block more generic.

**Comment by jpsim** [comment]
Agreed with @tgoyne.
