### ISSUE TITLE
Realm leaking RLMAccessor objects when listening notifications from background run loops.

### ISSUE THREAD

**Issue by stoprocent** [realm/realm-cocoa#4030]
## Goals

Run realm notifications on any background thread
I know it has be to run from a run loop.
## Actual Results

Working as expected but leaking objects.
## Steps to Reproduce

I have this simple class to perform blocks on run loops from some background threads.
It gets current run loop from given dispatch queue and perform block on that run loop.

Problem is that if I add notification block using my blocks Realm objects are leaking like crazy.
Everytime notification is recieved objects are adding up (https://cl.ly/hKB4). My notification block is ultra simple (something like): 

``` Swift
runloop.performBlock { [weak self]
    // Add notification
    self?.token = devices.addNotificationBlock { changeset in
        switch changeset {
        case .Initial(let objects):
            print(objects.map { $0.name })
            break
        case .Update(let objects, let deletions, let insertions, let modifications):
            print(objects.map { $0.name })
            break
        case .Error(let error):
            print(error)
            break
        }
    }
}
```

I dont even pass objects further down just get its names and print.
I did record referece counts and I've ended up here: https://cl.ly/hKcA

Now... I I just do it of the main thread `RLMAccessor` objects are deallocated and there is no leak.
I will dig into this again but I feel like I hit dead end now and would be nice to get any help.

My run loop block class is below.

``` Swift
public class RunLoopScheduler {

    private var _runLoop: NSRunLoop?

    private var _mode: AnyObject = kCFRunLoopDefaultMode

    private var _queue : dispatch_queue_t?

    // =========================================================================
    // MARK: - Public Methods

    public init(runLoop: NSRunLoop) {
        _runLoop = runLoop
    }

    public init(runLoop: NSRunLoop, mode: AnyObject) {
        _runLoop = runLoop
        _mode = mode
    }

    public init(fromQueue: dispatch_queue_t) {
        _queue = fromQueue
    }

    public final func performBlock(block: () -> Void) {

        // Check Run Loop
        if let queue = _queue where _runLoop == nil {
            let semaphore = dispatch_semaphore_create(0)
            dispatch_async(queue) { [weak self] in
                guard let strongSelf = self else { return }
                CFRunLoopPerformBlock(CFRunLoopGetCurrent(), strongSelf._mode) { [weak strongSelf] in
                    guard let strongSelf = strongSelf else { return }
                    // Assign Run Lop
                    strongSelf._runLoop = NSRunLoop.currentRunLoop()
                    // Signal Done
                    dispatch_semaphore_signal(semaphore)
                }
                CFRunLoopRun()
            }
            dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
        }

        if let runLoop = _runLoop {
            // Perform Block in run loop
            CFRunLoopPerformBlock(runLoop.getCFRunLoop(), kCFRunLoopDefaultMode) {
               block()
            }
            // Wake Up
            CFRunLoopWakeUp(runLoop.getCFRunLoop())
        }
    }

    deinit {
        if let runLoop = _runLoop {
            CFRunLoopStop(runLoop.getCFRunLoop())
        }
    }
}
```
## Version of Realm and Tooling

Realm version: 1.0.2
Xcode version: Version 7.3.1 (7D1014)
iOS/OSX version: 9.x
Dependency manager + version: Cocoapods

**Comment by bdash** [comment]
@stoprocent, thanks for the bug report!

My initial suspicion is that the "leaked" objects are ending up in autorelease pools in background threads or queues that are not being drained in a timely manner. You could determine whether this is the case by adding an explicit autorelease pool of your own around the invocation of the block passed to `CFRunLoopPerformBlock`.

If an autorelease pool doesn't help, would you be able to share a slightly more complete code sample so we can reproduce the problem you're seeing?

**Comment by jpsim** [comment]
@stoprocent just following up on @bdash's request for more information and a more complete code sample or Xcode project to help us reproduce this leak. Thanks!

**Comment by stoprocent** [comment]
Hi Guys 

Sorry for leaving this issue unresolved for some time. Ive tried autorelease block and it didnt help. I didn't have much time then to test it properly so i took a little different approach. Ive subclassed NSThread instead of using GCD and it's working great. If anyone is interested this is my code:

``` Swift
//
//  Thread.swift
//  Kontakt.io
//
//  Created by Marek Serafin on 26/09/2016.
//  Copyright © 2016 Kontakt.io. All rights reserved.
//

import Foundation

public class Thread: Foundation.Thread {
    
    var runLoop: RunLoop?
    var mainBlock: (() -> Void)?
    
    convenience init(name: String) {
        self.init()
        self.name = name
    }
    
    override public func main() {
        runLoop = RunLoop.current
        guard let runLoop = runLoop else { return }
        
        mainBlock?()
        mainBlock = nil
        
        while !isCancelled {
            autoreleasepool { runLoop.run() }
        }
        
        CFRunLoopStop(runLoop.getCFRunLoop())
    }

    public func runLoopPerformBlock(_ block: @escaping () -> Void) {
        
        if runLoop == nil {
            let semaphore = DispatchSemaphore(value: 0)
            mainBlock = { semaphore.signal() }
            start()
            _ = semaphore.wait(timeout: DispatchTime.distantFuture)
        }
        
        precondition(runLoop != nil, "Cannot add operation to thread before it is started")
        CFRunLoopPerformBlock(runLoop!.getCFRunLoop(), CFRunLoopMode.commonModes.rawValue, block)
        CFRunLoopWakeUp(runLoop!.getCFRunLoop())
    }
    
    
}
```

**Comment by bdash** [comment]
I'm pleased to hear that you've found a solution for the problem you were seeing. If you ever revisit your initial approach and can reproduce the leak, feel free to share a more complete project that demonstrates the problem and reopen this issue.
