### ISSUE TITLE
Build errors on master with XCode 8 Beta 6

### ISSUE THREAD

**Issue by danielrhodes** [realm/realm-cocoa#4040]
Having some build issues on master. Seeing the following errors:
![screenshot 2016-09-01 22 31 56](https://cloud.githubusercontent.com/assets/120044/18183293/f9cbcf1a-7093-11e6-9835-2cda71cf7200.png)

Looks like it's out of sync with realm-object-store? Specifically I couldn't find any alternative for `RLMDynamicGetByName`. The rest are easy to fix.

**Comment by JadenGeller** [comment]
Did you `git submodule update`?

**Comment by JadenGeller** [comment]
@jpsim Do you think we ought to mention this step in the build instructions in the README?

**Comment by jpsim** [comment]
yes

**Comment by danielrhodes** [comment]
Yes. I double checked and went into the `core` directory and pulled - it says it is up to date.

**Comment by JadenGeller** [comment]
@danielrhodes The `core` directory isn't a submodule. It's the `Realm/ObjectStore` directory that is. You shouldn't need to pull though. In the root of the repo (not the `Realm/ObjectStore` directory), fun `git submodule update --init`.

**Comment by danielrhodes** [comment]
Alright I removed my local realm-cocoa directory, re-cloned, ran `git submodule update --init`, and did a clean on my project to make sure. Same errors. Realm/ObjectStore says it is pointing to https://github.com/realm/realm-object-store/tree/7922710805950c353f00c4ba5146e2ff98aa8aa9

**Comment by JadenGeller** [comment]
I just recloned the repo, ran `git submodule update --init`, and opened the project in Xcode Version 8.0 beta 6 (8S201h). I was able to compile and run the Realm and RealmSwift tests successfully.

**Comment by JadenGeller** [comment]
Though for some reason, the submodule shows to be at "HEAD detached at 7922710". Hmm.. 🤔

**Comment by bdash** [comment]
The error messages mentioned above don't seem related to the object store at all, but seem more like Realm Swift is building against the wrong version of Realm?

**Comment by bdash** [comment]
@danielrhodes, can you try blowing away your derived data directory to make sure a stale version of Realm.framework isn't somehow involved? If it still fails after that can you then share the full build log from Xcode's Report navigator (the full output likely contains clues that'll help us understand what's different about your environment).

**Comment by danielrhodes** [comment]
I just created an empty XCode project with this Podfile:

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules=> true

  # Pods for RealmTest

end
```
removed DerivedData, and got the same errors. Here's the build log: 
https://gist.github.com/danielrhodes/4a9a6f36c19095355de7523f4334051d

**Comment by bdash** [comment]
Thanks, that reveals the problem immediately :-)

You need to add the following as well:
```ruby
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :submodules=> true
```

Otherwise CocoaPods will pull down the most recent Realm release to satisfy RealmSwift's dependency on Realm.

**Comment by danielrhodes** [comment]
I think that'll do it. Thanks, much appreciated.

And on that note: I really wish Cocoapods would add the ability to point to a pod in a different repo/branch in the specs. Has made this transition to Swift 3 difficult, but also makes forking a pod hard if it has dependencies.
