### ISSUE TITLE
RealmSwift compiled with older Swift language (2.0) than previous files (3.0)

### ISSUE THREAD

**Issue by hightekjonathan** [realm/realm-cocoa#4046]
When creating a new Xcode project and setting up Realm, I built the default project to make sure the settings were correct, and I get the Mach-O Linker Error "Linker command failed with exit code 1 (use -v to see invocation)"

Here is the raw output from the whole error:

> Ld /Users/jonathanstowe/Library/Developer/Xcode/DerivedData/Record_Store-dxhwlltjuofyzfccpubkdqlpgngi/Build/Products/Debug-iphonesimulator/Record\ Store.app/Record\ Store normal x86_64
    cd "/Users/jonathanstowe/Xcode Projects/Record Store"
    export IPHONEOS_DEPLOYMENT_TARGET=9.3
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -L/Users/jonathanstowe/Library/Developer/Xcode/DerivedData/Record_Store-dxhwlltjuofyzfccpubkdqlpgngi/Build/Products/Debug-iphonesimulator -F/Users/jonathanstowe/Library/Developer/Xcode/DerivedData/Record_Store-dxhwlltjuofyzfccpubkdqlpgngi/Build/Products/Debug-iphonesimulator -F/Users/jonathanstowe/Xcode\ Projects/Record\ Store -filelist /Users/jonathanstowe/Library/Developer/Xcode/DerivedData/Record_Store-dxhwlltjuofyzfccpubkdqlpgngi/Build/Intermediates/Record\ Store.build/Debug-iphonesimulator/Record\ Store.build/Objects-normal/x86_64/Record\ Store.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.3 -Xlinker -object_path_lto -Xlinker /Users/jonathanstowe/Library/Developer/Xcode/DerivedData/Record_Store-dxhwlltjuofyzfccpubkdqlpgngi/Build/Intermediates/Record\ Store.build/Debug-iphonesimulator/Record\ Store.build/Objects-normal/x86_64/Record\ Store_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/jonathanstowe/Library/Developer/Xcode/DerivedData/Record_Store-dxhwlltjuofyzfccpubkdqlpgngi/Build/Intermediates/Record\ Store.build/Debug-iphonesimulator/Record\ Store.build/Objects-normal/x86_64/Record_Store.swiftmodule -framework RealmSwift -framework Realm -Xlinker -dependency_info -Xlinker /Users/jonathanstowe/Library/Developer/Xcode/DerivedData/Record_Store-dxhwlltjuofyzfccpubkdqlpgngi/Build/Intermediates/Record\ Store.build/Debug-iphonesimulator/Record\ Store.build/Objects-normal/x86_64/Record\ Store_dependency_info.dat -o /Users/jonathanstowe/Library/Developer/Xcode/DerivedData/Record_Store-dxhwlltjuofyzfccpubkdqlpgngi/Build/Products/Debug-iphonesimulator/Record\ Store.app/Record\ Store

> ld: /Users/jonathanstowe/Xcode Projects/Record Store/RealmSwift.framework/RealmSwift compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is just the error I'm stuck at, and saw that there wasn't an issue written up about it yet. It seems to only stick with the error because of the Swift 3.0 compiler.

Realm version: 1.0.2

Xcode version: 8.0 beta 6 (8S201h)

iOS/OSX version: iOS 10

**Comment by bdash** [comment]
Prebuilt binaries of Swift frameworks can only be consumed by the same version of Xcode that compiled them. Currently our releases are built with Xcode 7.3. Since you're using a prerelease version of Xcode, you'll need to [build Realm from source](https://github.com/realm/realm-cocoa#building-realm) from our master branch. Once Xcode 8 officials ships we'll release a version of Realm built with it.

**Comment by hightekjonathan** [comment]
Ah perfect, the binary is building now!
