### ISSUE TITLE
Carthage: Is Realm.framework also need for RealmSwift

### ISSUE THREAD

**Issue by puttin** [realm/realm-cocoa#4049]
I'm trying to play with RealmSwift.

According to Carthage tab in https://realm.io/docs/swift/1.0.2/#installation-swift-22

`Drag RealmSwift.framework and Realm.framework from the appropriate platform directory in Carthage/Build/ to the “Embedded Binaries” section of your Xcode project’s “General” settings.`

But is `Realm.framework` also need for RealmSwift?

<details>
<summary>Realm Questions</summary>
## Goals

Integrate Realm correctly

## Steps to Reproduce

using master branch for Swift 3 support
then
`carthage bootstrap --platform ios --no-use-binaries`
ignore the problem #4042

## Version of Realm and Tooling

Realm version: master

Xcode version: Xcode 8 beta 6

iOS/OSX version: 10.11.6

Dependency manager + version: Carthage 0.17.2
</details>

**Comment by mrackwitz** [comment]
Yes! `RealmSwift.framework` is based on `Realm.framework` and depends on it. So you need to embed both.
