### ISSUE TITLE
Realm RealmCollectionChange 

### ISSUE THREAD

**Issue by Miindaugas** [realm/realm-cocoa#4053]
## Goals

Hello i wanna ask why RealmCollectionChange on Swift inserting objects wen you only need to delete them.

## Expected Results

Wen i delete object i expect that only list object will be deleted for example wen i delete object with id 4 this is what happening:

ACTION: DELETE 4
ID STACK: 1 2 3 4 5 6 

At the moment works like this:
DELETE  [4, 6] INSERT  [4] UPDATE [] <- Deletes 4 and 6 and then inserts 6 in to 4 place.

Should be like this:
DELETE  [4] INSERT  [] UPDATE []

## Actual Results

For some odd reason realm takes last object of list and places in place on deleted one and breaking stack order.
It would be nice if realm would only delete object and not reinsert anything.

Realm version: 1.0.2

**Comment by tgoyne** [comment]
The order of objects within a Realm is not stable. If you want your objects to be in a specific order, you must sort them on a property which gives that order.

Note that this is different for RLMArray/List, which do store their objects in a specific order.
