### ISSUE TITLE
Unexpected crash on Test Flight Builds ([RLMRealm cancelWriteTransaction] (RLMRealm.mm:518))

### ISSUE THREAD

**Issue by sauvikatinnofied** [realm/realm-cocoa#4054]
## Goals

Crash Free Transations

## Expected Results

The application must not crash

## Actual Results

The application is crashing repeatedly. Here is the symbolicated crash report.
[RealmCrash.txt](https://github.com/realm/realm-cocoa/files/456460/RealmCrash.txt)

## Code Sample
Can not determine, the symbolicated crash reports are not directing us to a code written by us from `Xcode -> Window -> Organizer -> Crashes`, it just simply opens the project.

## Version of Realm and Tooling

Realm version: ? 
1.0.0

Xcode version: ?
Xcode 7.3.1
Build version 7D1014

iOS version: ?
iOS 9.3.5 (13G36)

Dependency manager + version: ?
git version 2.7.4 (Apple Git-66)

**Comment by kishikawakatsumi** [comment]
@sauvikatinnofied Thanks for the reporting! It seems that the Realm instance was deallocating while write transaction. Could you show your code around saving objects to Realm for investigation? For example `BLEStepServicesRealm.addNewBLEStepInBackground()` etc.

**Comment by sauvikatinnofied** [comment]
@kishikawakatsumi Thank you very much for looking into the issue, here are the code snippets for better debugging purposue

```swift
class BLEStepServicesRealm {
  // MARK: - STEP DATA SERVICES
  
  // MARK: SAVE
  class func addNewBLEStepInBackground(step: UserStepsDTO, completionBlock: RealmUpdateCompletionBlock){
    addOrReplaceBulkBLEStepInBackground([step], completionBlock: completionBlock)
  }
  
  class func addOrReplaceBulkBLEStepInBackground(steps: [UserStepsDTO], completionBlock: RealmUpdateCompletionBlock){
    let realm = RealmManager.getNewRealm()
      do {
        try realm.write({          
          for step in steps {
            if let test = realm.objectForPrimaryKey(UserStepsDTORealm.self, key: step.timestamp) {
              realm.delete(test)
              debugPrint("step already in db:")
              debugPrint("deleting:")
              debugPrint(test)
              debugPrint("replacing for")
              debugPrint(step)
            }
            realm.add(UserStepsDTORealm(mapperObject: step))
          }
        })
        
        Utility.dispatchAsyncInMain({
          completionBlock(success: true, error: nil)
        })
        
      } catch  {
        Utility.dispatchAsyncInMain({
          completionBlock(success: false, error: error as NSError)
        })
      }
  }

  .....
}

class  RealmManager {
    ....

  static var realmFileURL: NSURL {


    var config = Realm.Configuration(

      migrationBlock: { migration, oldSchemaVersion in
         //  oldSchemaVersion <= 5
          if (oldSchemaVersion < 6) {

             // Migration code
           }
        })
    
    // Use the default directory, but replace the filename with the username
    config.fileURL = config.fileURL!.URLByDeletingLastPathComponent?
      .URLByAppendingPathComponent("<MyApp>DB.realm")
    // Tell Realm to use this new configuration object for the default Realm
    Realm.Configuration.defaultConfiguration = config
    
    let documentDirectory = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).last!
    do {
      try  NSFileManager.defaultManager().setAttributes([NSFileProtectionKey: NSFileProtectionNone], ofItemAtPath: documentDirectory)
    } catch(let error as NSError) {
      print("\(error.localizedDescription)")
    }

    return NSURL(string: config.fileURL!.absoluteString)!
  }
  
  class func getNewRealm() -> Realm {
    return try! Realm(fileURL: realmFileURL)
  }
}
```

**Comment by sauvikatinnofied** [comment]
@kishikawakatsumi Did you get a chance to get back to this issue? My application is using `Realm` storage even when the app is in background and phone is locked by passcode. I have seen another issue https://github.com/realm/realm-cocoa/issues/3812 which causes crash.  Earlier I have seen this issue but after adding `NSFileProtectionNone` to `Docuement` directory with the following code
```swift
let documentDirectory = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).last!
do {
      try  NSFileManager.defaultManager().setAttributes([NSFileProtectionKey: NSFileProtectionNone], ofItemAtPath: documentDirectory)
   } catch(let error as NSError) {
      print("\(error.localizedDescription)")
   }
```
I was not able to reproduce the issue. I am not sure about any connection in between these two issues.

**Comment by kishikawakatsumi** [comment]
@sauvikatinnofied Sorry for the late reply. Specifying `NSFileProtectionNone` seems fine.

The crash occurred due to the Realm instance was deallocating while transaction. Did you use the `realm` instance in `addOrReplaceBulkBLEStepInBackground ()` after `Utility.dispatchAsyncInMain()`?

**Comment by sauvikatinnofied** [comment]
@kishikawakatsumi Yes, there might be some **Realm** transaction code which is being executed in the `completionBlock (RealmUpdateCompletionBlock)`. Will you please let me know, what will be the best practice to do more operation on **Realm** on the completion block on another operation? I am using the following `GCD` technique to do that.

```swift
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {

  // More Realm operations

}
```

**Comment by jpsim** [comment]
Hi @sauvikatinnofied, yes using GCD is certainly our recommended way to perform asynchronous operations in Realm.

I'll be closing this issue now because I believe we've addressed all your questions, but feel free to open a new issue if anything else comes up!
