### ISSUE TITLE
[iOS][Cocoapods]Umbrella header 'Realm.h' not found

### ISSUE THREAD

**Issue by lusnaow** [realm/realm-cocoa#4060]
I have tried ：
pod cache clean  --all
pod deintegrate
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
XCode->Project->Clean

Still have this problem.

Realm, 1.0.2

RealmSwift, 1.0.2

Xcode version: Version 7.3 (7D175)

iOS version: 9.3

Cocoapods version: 1.0.1

**Comment by mrackwitz** [comment]
There is another thing you can and should try if you haven't done that yet:

Please clean all build products of all targets of the current project and other projects which share the same build folder.
You can achieve that by holding down the Option key (⌥) and select *Product* > *Clean Builder Folder…* in the Xcode menu. (**⌥⇧⌘K**)

**Comment by lusnaow** [comment]
I have fixed this by deleting "User Header Search Paths" of my target.

**Comment by AlexWoe89** [comment]
I've still this issue, both when I clean all targets and I delete the user header search paths of my target. 
Realm 1.1.0
SwiftRealm 1.1.0
XCode 8

**Comment by jpsim** [comment]
@AlexWoe89 we don't actively monitor old issues, so please file a new issue, taking care to fill out the issue template, with full steps for us to reproduce, and we'll take a look.
