### ISSUE TITLE
Getting two of the same object w/ primary key in Results object

### ISSUE THREAD

**Issue by jpmcglone** [realm/realm-cocoa#4061]
When I add a new chat, Realm Browser shows just 1 new chat (with a primary key), but some reason, my chat list view controller shows two of the new chat!

If I relaunch the app, it fixes itself. 

What is going on??

```
var baseChats: Results<Chat>!
```
```
var chats: Results<Chat>! {
    didSet {
        token = chats.addNotificationBlock { [weak self] changes in
            guard let strongSelf = self else { return }
            let tableView = strongSelf.chatListView.tableView
            switch changes {
            case .Initial:
                tableView.reloadData()
            case .Update(_, let _, let _, let _):
                tableView.reloadData()
            case .Error(let error):
                fatalError("\(error)")
            }
        }
    }
}
```
```
override func queryDidUpdate() {
    chats = refreshChats()
}
```
```
func refreshChats() -> Results<Chat> {
    token?.stop()
    
    if let query = query where query.characters.count > 0 {
        return baseChats.filter("name BEGINSWITH[c] %@", query)
    } else {
        return baseChats
    }
}
```
```
override func viewDidLoad() {
    super.viewDidLoad()
    let sortProperties = [SortDescriptor(property: "lastActivity", ascending: false)]
    baseChats = Chat.myChats.filter("name != nil || alias != nil").sorted(sortProperties)
    chats = refreshChats()
    // ...
}
```

**Comment by TimOliver** [comment]
Hi there! Hmm, if you've got an object with a primary key, then it shouldn't be possible for two copies of it to be saved to the Realm file. My initial impression of this is that somehow the same object is being passed to your view controller twice.

Which `Results` object are you mapping to your `UITableView`? Is it just the `chats` object?

Can you see if you can set a breakpoint at each `chats = refreshChats()` each time they are called, and see if you're actually getting returned two copies of the object?

Thanks!

**Comment by stel** [comment]
@jpmcglone did you resolve this issue? Please let us know if you need any other help or if we can close this issue, thanks!

**Comment by jpsim** [comment]
Closing since we haven't heard back from @jpmcglone in a while.
