### ISSUE TITLE
按照示例编写， 把age设置为NSUInteger就报错，这是为啥？ 

### ISSUE THREAD

**Issue by ytx0574** [realm/realm-cocoa#4066]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?  最新

Xcode version: ?  7.3.1

iOS/OSX version: ?  10.11.5

Dependency manager + version: ? 

2016-09-08 15:22:23.507 RealmTest[10486:281048] *** Terminating app due to uncaught exception 'RLMException', reason: 'Can't persist property 'age' with incompatible type. Add to ignoredPropertyNames: method to ignore.'

**Comment by kishikawakatsumi** [comment]
@ytx0574 Realm doesn't support unsigned integer type yet. Please use signed int (like `NSInteger`, `int` or `long`) instead. It has been on the todo list for a while but low priority. It is tracked by https://github.com/realm/realm-cocoa/issues/651.
