### ISSUE TITLE
jp-xcode8-ci don't build

### ISSUE THREAD

**Issue by brightsider** [realm/realm-cocoa#4074]
I'm install jp-xcode8-ci branch - pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'jp-xcode8-ci', :submodules => true
And this don't help to start project in Xcode 8.

## Actual Results

![errors](https://cloud.githubusercontent.com/assets/4996231/18408064/1353a87e-772c-11e6-85ed-bf1ac690f582.png)

## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: 8 GM

iOS/OSX version: 10 GM

Dependency manager + version: CocoaPods 1.0.1

**Comment by brightsider** [comment]
I'm found resolution - add pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'jp-xcode8-ci', :submodules => true

**Comment by jpsim** [comment]
Please don't use that branch, it's only used to troubleshoot our CI integration. Please use `master`.

**Comment by brightsider** [comment]
master is already support Xcode 8?

**Comment by jpsim** [comment]
yes, though we'll be making API changes this week and making an official Xcode 8 release later this week: https://twitter.com/realm/status/773665903946952704
