### ISSUE TITLE
Notification support for RLMObject

### ISSUE THREAD

**Issue by crrobinson14** [realm/realm-cocoa#4075]
## Goals

Add support for Notifications on RLMObject, or a "version" type property in RLMObjectBase automatically maintained by Realm.

## Expected Results

Notifications are great and make all kinds of things like table/collection views easier to maintain. But if you have a UI wired to a single object, it's a little harder. KVO works well, and combined with ReactiveCocoa can make auto-updating interfaces not a big deal. But if you have, say, 12 fields to update, it can be a lot of boilerplate wiring observers to every field in an RLMObject.

Currently it is not possible to wire a single observer to the entire object, to redraw all fields related to that object. One must observe every field independently. This feature request is to do one of two things:

1. Add support for adding a notification block on a single RLMObject. It is already possible to listen for notifications on an RLMResult * with only one result, and this has been my workaround - set up an `objectsWhere` call against the primary key, so you get just the one record but in an RLMResults * wrapper. Notifications then work properly against the entire object, but this is obviously pretty ugly.
1. Add a read-only version property to RLMObject itself, incremented or otherwise mutated (last-changed?) on every update. This would allow KVO against the entire object by simply observing this one field.

In short, it would be REALLY nice to convert this:

```
    _user = [User myUser]; // Single RLMObject returned here
    [[RACObserve(_user, shareBadgeCount) takeUntil:self.rac_willDeallocSignal] subscribeNext:^(NSNumber *count) {
        User *user = [User myUser]; // Realm is so fast this is easier than doing RAC deliverOn:...
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuShare] value:([user.shareBadgeCount integerValue] + [user.rushBadgeCount integerValue])];
    }];

    [[RACObserve(_user, chatBadgeCount) takeUntil:self.rac_willDeallocSignal] subscribeNext:^(NSNumber *count) {
        User *user = [User myUser];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuChat] value:[user.chatBadgeCount integerValue]];
    }];

    [[RACObserve(_user, rushBadgeCount) takeUntil:self.rac_willDeallocSignal] subscribeNext:^(NSNumber *count) {
        User *user = [User myUser];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuPoints] value:([user.rushBadgeCount integerValue] + [user.rushBadgeCount integerValue])];
    }];

    [[RACObserve(_user, inboxBadgeCount) takeUntil:self.rac_willDeallocSignal] subscribeNext:^(NSNumber *count) {
        User *user = [User myUser];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuInbox] value:[user.inboxBadgeCount integerValue]];
    }];
```

to this:

```
    _user = [User myUser];
    [[RACObserve(self, user.__realmVersion) takeUntil:self.rac_willDeallocSignal] subscribeNext:^(NSNumber *realmVersion) {
        user = [User myUser];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuShare] value:([user.shareBadgeCount integerValue] + [user.rushBadgeCount integerValue])];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuPoints] value:([user.shareBadgeCount integerValue] + [user.rushBadgeCount integerValue])];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuChat] value:[user.chatBadgeCount integerValue]];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuInbox] value:[user.inboxBadgeCount integerValue]];
    }];
```

or this:

```
    _user = [User myUser];
    _notificationToken = [self.user addNotificationBlock:^(RLMObject *record, NSError *error) {
        User *user = record;
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuShare] value:([user.shareBadgeCount integerValue] + [user.rushBadgeCount integerValue])];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuPoints] value:([user.shareBadgeCount integerValue] + [user.rushBadgeCount integerValue])];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuChat] value:[user.chatBadgeCount integerValue]];
        [self setBadge:weakSelf.tabBar.items[NRDrawerMenuInbox] value:[user.inboxBadgeCount integerValue]];
    }];
```

**Comment by beloso** [comment]
I'd also like this feature. It is possible for us to do this though. Without further developments from Realm's team.

We can add a `public readonly` property and make it `readwrite` at class level.
Then whenever you update your record don't forget to increment the "version property".

Using ReactiveCocoa observe that property and do your magic.
I've actually done something similar to this on a project of mine.

Also, beware of your current observer implementation, if a transaction updates all the fields you are observing it will provoke as many UI updates as properties that you are observing. That can slow down you app significantly.

**Comment by crrobinson14** [comment]
Yes, what you noted about doing this via per-field-RAC leading to UI flickers is absolutely true and one of the things I hate about doing it field-by-field. That said, if you have a big object with a bunch of fields, and a view that only renders a few of them, it's not terrible. It's just a lot of judgment-call making by the developer, which increases the defect rate.

There are three things I hate about the version-number approach:
1. It's a big increase in the object definition boilerplate. You need to either swizzle or proxy the Realm "createOrUpdateInDefaultRealmWith..." method(s) (or however you update objects) and add a version to every object, or include this from whatever server/source is the originator of the objects in the first place. It's a super messy, high-touch way to do something so simple.
1. As you noted, it still doesn't address a number of use-cases. You can't tell when an object has been deleted, because once an object is invalidated you can't read fields from it anymore without throwing an exception. And when you do get a legitimate update, you can't tell what fields have been changed so you have the same too-many-updates issue as noted above.
1. With a self-maintained field, the developer has a responsibility to namespace or otherwise protect that field from conflicts by origination-source schema changes. If you call it "version", suppose the upstream source of the data adds a "version" field? It's easy to chuck something like __mine__version in from of the field name, but adding an extra "best practice" step that requires this makes the system more brittle - it's one more thing to keep in mind to avoid breakage, one more opportunity for defects. If this was done in a Realm-enforced namespace like _realmVersion, this chance would be reduced.

I would think the cleanest option would be right here - this is what I've considered swizzling myself:
https://github.com/realm/realm-cocoa/blob/master/Realm/RLMObjectBase.mm#L180-L195

This is where object values are set. It would be pretty straightforward to maintain a mutable set or other collection that tracked value-sets. During the commit, right where collection notifications are built and fired, this mutable set could be checked for individual object mutations. If you want to honor ObjC/Swift concepts you could even just make it a delegate call back from the object. How hot would that be? "myObject.delegate = self" then just define the methods you want callbacks on like "objectWasUpdated". Not that blocks are BAD, but you do end up with pretty long viewDidLoads or wherever you put them...

This option is easy enough that I could probably do it myself and submit a PR, but I wanted to file this for review by the core devs before I went that far. They weren't in love with my last one. :)

If you want a second option, the code to build RLMCollection change notification sets could be enhanced to also fire events on individual objects - it has all the data at hand to know the objects that have changed because it uses it to figure out which collections need a `modified` notification. But this code was more complex and I've only just started looking at it. It's not clear to me whether this could be done efficiently if the bulk of the cases did NOT require a notification. (That is: would it have to do a lot of wasted work just to find out it had nothing to do?)

**Comment by crrobinson14** [comment]
NOTE: I ended up going with a self-written delegate myself. I've added my own proxy `createOrOptionallyUpdate` function to every one of my objects because I receive server updates some times for records that haven't actually changed, or that have fields updated the app doesn't care about. I was getting a lot of collection-change notifications indicating modifications, when values weren't actually being changed.

Since I already had this proxy that checks whether field updates are actually required, I just added a delegate to all my objects, and when this is happening, I fire the delegate. You have to be super careful about threading rules here because when you fire the delegate you're still in a transaction. You have to keep track of what thread you're on (I do my DB updates in a serialized queue in a background thread, so I have to dispatch to the main queue) and you can't do anything in the delegate that would require creating another transaction. It's a super useful pattern for UI updates. It's not so useful for other patterns like trigger->cascade updates unless you're SUPER careful about tracking whether you're in that transaction.

**Comment by crrobinson14** [comment]
Update: Tried the delegate option, doesn't work. Silly me, since the objects on different threads are not the same (they're all just proxies to the base data) a delegate on an object in one thread isn't the same as on another thread, if you add the delegate to your own class. So it seems the only workaround for now is a version number added to every object, making sure EVERY pathway that you have that can update an object also updates that value, and just doing KVO on that.

**Comment by jpsim** [comment]
We're tracking adding a nicer API alternative to KVO on RLMObject/Object in #3431. @crrobinson14 do you think this issue can be closed as a duplicate, or is there more that you'd like to see that isn't covered in #3431?

**Comment by crrobinson14** [comment]
Sorry @jpsim, I searched the open issues before filing this but somehow missed that one. Long weekend I guess. This is clearly a duplicate. #3431 (and #4075) would 100% solve my use-case.
