### ISSUE TITLE
Encryption method not working

### ISSUE THREAD

**Issue by hdoria** [realm/realm-cocoa#4076]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

I 'm trying to encrypt the database file using latest realm (obj-c), Xcode 8 GM and iOS 10.

## Actual Results

The app crashes when trying to store the encryption key in the keychain. This is the error message:

"Failed to insert new key in the keychain"

I think there's something wrong with this like, but I can't figure out where's the problem:

```objective-c
status = SecItemAdd((__bridge CFDictionaryRef)query, NULL);
```

## Steps to Reproduce

I'm calling this method (found here: [https://github.com/realm/realm-cocoa/blob/master/examples/ios/objc/Encryption/LabelViewController.m](https://github.com/realm/realm-cocoa/blob/master/examples/ios/objc/Encryption/LabelViewController.m)):

```objective-c
- (NSData *)getKey {
    // Identifier for our keychain entry - should be unique for your application
    static const uint8_t kKeychainIdentifier[] = "io.Realm.EncryptionExampleKey";
    NSData *tag = [[NSData alloc] initWithBytesNoCopy:(void *)kKeychainIdentifier
                                               length:sizeof(kKeychainIdentifier)
                                         freeWhenDone:NO];

    // First check in the keychain for an existing key
    NSDictionary *query = @{(__bridge id)kSecClass: (__bridge id)kSecClassKey,
                            (__bridge id)kSecAttrApplicationTag: tag,
                            (__bridge id)kSecAttrKeySizeInBits: @512,
                            (__bridge id)kSecReturnData: @YES};

    CFTypeRef dataRef = NULL;
    OSStatus status = SecItemCopyMatching((__bridge CFDictionaryRef)query, &dataRef);
    if (status == errSecSuccess) {
        return (__bridge NSData *)dataRef;
    }

    // No pre-existing key from this application, so generate a new one
    uint8_t buffer[64];
    SecRandomCopyBytes(kSecRandomDefault, 64, buffer);
    NSData *keyData = [[NSData alloc] initWithBytes:buffer length:sizeof(buffer)];

    // Store the key in the keychain
    query = @{(__bridge id)kSecClass: (__bridge id)kSecClassKey,
              (__bridge id)kSecAttrApplicationTag: tag,
              (__bridge id)kSecAttrKeySizeInBits: @512,
              (__bridge id)kSecValueData: keyData};

    status = SecItemAdd((__bridge CFDictionaryRef)query, NULL);
    NSAssert(status == errSecSuccess, @"Failed to insert new key in the keychain");

    return keyData;
}
```

## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: 8.0 GM

iOS/OSX version: 10.0 GM

Dependency manager + version: Carthage 0.17.2-77-g79c63f5

**Comment by hdoria** [comment]
It started to work on simulator by adding **Keychain Access Groups** to the Entitlements file: 

![screenshot 2016-09-11 13 29 13](https://cloud.githubusercontent.com/assets/73786/18418827/c67e9e70-7823-11e6-9060-9d86d8a38752.png)

Is this required now?

**Comment by jpsim** [comment]
This is unrelated to Realm.
