### ISSUE TITLE
为什么realm的results转数组这么麻烦？还需要写一个扩展。

### ISSUE THREAD

**Issue by zyzhangyu** [realm/realm-cocoa#4077]
This problem has been resolved！
Thank you for your answer！

**Comment by puttin** [comment]
You can use AnyRandomAccessCollection with Results

Please use English if you could to help other developers as well.

**Comment by owenzhao** [comment]
You'd better use `Result<T>` instead of `Array<T>`. Because if you use `Array`, you lost the ability of `auto query` and other features, like notification, which makes your app uses more memory and less flexible.

Also, you can always use `let array = Array(Results<T>)` to get an array.

**Comment by jpsim** [comment]
Thanks for your help @puttin and @owenzhao!
