### ISSUE TITLE
Implement the ability to rename a class during a migration.

### ISSUE THREAD

**Issue by mrdavidrees** [realm/realm-cocoa#4080]
## Goals

Implement the ability to rename a class during a migration.

## Expected Results

Often times working in a project with a long term realm database the scope and direction of the project will change with the implementation to match. Although changing names is fundamentally a pointless task, it is important that new developers are not confused by names that are irrelevant and outdated. Although it is possible to create new classes with the exact same properties and copy them from the old objects it is very messy and seems ridiculous. 

This is how I am currently changing the name of my class:

        let realm = try! Realm()
        realm.beginWrite()
        
        //rename StoryNode to DraftMedia
        let storyNodes = realm.objects(StoryNode).map{$0}
        storyNodes.forEach { node in
            let draftMedia = DraftMedia()
            draftMedia._mediaType = node._mediaType
            draftMedia.assetIdentifier = node.assetIdentifier
            draftMedia.comments = node.comments
            draftMedia.creationDate = node.creationDate
            draftMedia.latitude = node.latitude
            draftMedia.longitude = node.longitude
            draftMedia.height = node.height
            draftMedia.width = node.width
            draftMedia.storyFeaturedImage = node.storyFeaturedImage
            draftMedia.parentId = node.draftLocalId
            
            let realm = try! Realm()
            realm.add(draftMedia)
            
            realm.delete(node)
        }
        
        if let error = try? realm.commitWrite() {
            print(error)
        }
   

I would propose we can change the name as such

         migration.renameClass(oldName: "StoryNode", newName: DraftMedia.className())

**Comment by jpsim** [comment]
We're already tracking this feature as #2491, with a partial and outdated implementation in #2499. Closing as a duplicate. Please subscribe to those tickets for updates.

**Comment by mrdavidrees** [comment]
Thanks, was looking for these.
