### ISSUE TITLE
Failed build with Swift 3 caused by missing C++ source files

### ISSUE THREAD

**Issue by msamoylov** [realm/realm-cocoa#4087]
## Goals

I'm trying to build `osx-swift` target with running `sh build.sh osx-swift`.

## Expected Results

**RealmSwift.framework** and **Realm.framework**

## Actual Results

https://gist.github.com/msamoylov/0da2c464258e34243dff1b0c976abb83

## Steps to Reproduce

1. `git clone https://github.com/realm/realm-cocoa.git`
2. `cd realm-cocoa`
3. `sh build.sh osx-swift`

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004

/Applications/Xcode.app/Contents/Developer
Xcode 8.0
Build version 8A218a

/usr/local/bin/pod
0.39.0
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.18
(not in use here)

/usr/bin/git
git version 2.8.4 (Apple Git-73)
```

**Comment by jdanthinne** [comment]
Have you initialized the submodules?
Try `git submodule update --init --recursive`

**Comment by msamoylov** [comment]
@jdanthinne that was not obvious to me. Thank you!

*****BUILD SUCCEEDED***** 

I suppose the Real team should update https://github.com/realm/realm-cocoa/blob/master/README.md or even https://github.com/realm/realm-cocoa/blob/master/build.sh
