### ISSUE TITLE
Unresolved identifier 'RLMRealmDidChangeNotification' 'RLMRealmRefreshRequiredNotification'

### ISSUE THREAD

**Issue by cjg552** [realm/realm-cocoa#4088]
With Xcode 8 and migration to Swift 2.3 - Realm / RealmSwift using Legacy code to YES we get 2 compiling errors of unresolved identifier 'RLMRealmDidChangeNotification' 'RLMRealmRefreshRequiredNotification'

Realm version:  1.0.2 / RealmSwift 1.0.2

Xcode version: Version 8.0 (8A218a)

iOS/OSX version: 10

Dependency manager + version: Cocoapods 1.1.0

**Comment by WayneEld** [comment]
+1

**Comment by cjg552** [comment]
Pointing to master from Podfile now I don´t get errors but several warnings about files missing from working copy 

 pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', submodules: true
    pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', submodules: true
