### ISSUE TITLE
Filter realm with NSPredicate and float values not working

### ISSUE THREAD

**Issue by kgoedecke** [realm/realm-cocoa#4091]
## Goals

Filter objects from Realm using ```NSPredicate``` and float values. 

## Expected Results

I expect the result to contain the filtered elements.

## Actual Results

No elements are returned and error message is thrown.

## Steps to Reproduce

Insert objects with float values into realm and then query them with ```objectsWithPredicate```.

## Code Sample

It get the following error message:

    TypeError: cannot concatenate 'str' and 'NoneType' objects
    Traceback (most recent call last):
      File "/Users/kevin/Library/Application Support/Realm/rlm_lldb.py", line 210, in RLMResults_SummaryProvider
         return 'Unevaluated query on ' + class_name

When using the following NSPredicate:

    float x = -0.948109209;
    float y = -1.45714653;
    float z = -5.74263191;
    NSPredicate *predicate = [NSPredicate predicateWithFormat:@"x > %f AND x < %f AND y > %f  AND y < %f AND z > %f AND z < %f", x - 0.0001,  x + 0.0001, y - 0.0001, y + 0.0001, z - 0.0001, z + 0.0001];`
    RLMResults<Coords *> *filteredCoords = [Coords objectsWithPredicate:predicate];

Also see here for float in NSPredicate: http://stackoverflow.com/questions/22993810/nspredicate-between-float-valueslatitude-and-longitude-from-coredata

## Version of Realm and Tooling

Realm version: ?
Realm Objective-C 1.0.2
Xcode version: ?
XCode 7.3.1
iOS/OSX version: ?
10.11.6 / iOS 9 
Dependency manager + version: ?

**Comment by jpsim** [comment]
This was fixed in #3714. Please update your `rlm_lldb.py` file to the latest version: https://github.com/realm/realm-cocoa/blob/master/plugin/rlm_lldb.py

**Comment by kgoedecke** [comment]
@jpsim thanks that helped!
