### ISSUE TITLE
Compiling Realm Xcode 8 / iOS SDK 10

### ISSUE THREAD

**Issue by Nykho** [realm/realm-cocoa#4093]
Hi

 I'm trying to use Realm with Xcode 8 / iOS 10. I couldn't make it work with Cocoapods, so I'm trying to compile Realm. 

## Goals

Get Realm Binary using iOS SDK 10

## Expected Results

Xcode / build.sh build to compile without failing

## Actual Results

Compiling with Xcode:

https://www.dropbox.com/s/gkw0pgv8isyqmv6/Screenshot%202016-09-14%2014.42.36.png?dl=0

Compiling using build.sh:

> $ sh build.sh ios-dynamic (I also tried with build.sh build)
http://pastebin.com/RSuqwvtj

## Steps to Reproduce

Download code or git clone up to commit https://github.com/realm/realm-cocoa/commit/c508dee7e99411e74370de7dda89461c1688c611 (Sept 13)

## Code Sample

https://www.dropbox.com/s/fxe4ia26t7o1e7k/realm-cocoa-master.zip?dl=0

## Version of Realm and Tooling

```
> ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
>
> /Applications/Xcode.app/Contents/Developer
> Xcode 8.0
Build version 8A218a
>
> /Users/narqueros/.rvm/gems/ruby-2.2.0/bin/pod
1.0.1
> (not in use here)
>
> /bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
>
> /usr/local/bin/carthage
0.18
> (not in use here)
>
> /usr/local/bin/git
git version 2.4.1
> ```

Realm version: Up to commit https://github.com/realm/realm-cocoa/commit/c508dee7e99411e74370de7dda89461c1688c611

Xcode version: Xcode 8.0
Build version 8A218a

iOS/OSX version: iOS 10

Dependency manager + version: -

**Comment by francoisduchemin** [comment]
I have the same problem with Carthage:
github "realm/realm-cocoa"

Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again: /Users/.../Carthage/Build/iOS/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule

**Comment by jpsim** [comment]
@Nykho looks like your submodules are out of date. `git submodule update --init --recursive`

@francoisduchemin looks like you're using different versions of Xcode and/or Swift to build Realm Swift and your app.

**Comment by Jaiyo** [comment]
I'm getting this:
clang: error: no such file or directory: '/Users/me/realm-cocoa/Realm/ObjectStore/src/impl/weak_realm_notifier.cpp'

**Comment by Nykho** [comment]
** BUILD SUCCEEDED **

Thanks @jpsim !!!!

**Comment by cbh2000** [comment]
@jpsim For Carthage, just noting that `github 'realm/realm-cocoa'` in the `Cartfile` doesn't work. This is because the latest (precompiled) release, 1.0.2, was built with an older version of Swift.

**Comment by jpsim** [comment]
That's right. For Carthage, you'd need to specify `github "realm/realm-cocoa" "master"` because 1.0.2 was released before Xcode 8 was officially released.

**Comment by cbh2000** [comment]
I'm doing that now, and it sounds like you're already aware. Just thought I'd mention--just in case. 👍
