### ISSUE TITLE
Module compiled with Swift 2.3 cannot be imported in Swift 3.0

### ISSUE THREAD

**Issue by shobhz** [realm/realm-cocoa#4100]
I'm using the 'master' branch

**Comment by bdash** [comment]
Can you please provide some details about what you're trying to do, what steps you're taking, and what error you're seeing? This is all information that was requested in the [new issue template](https://github.com/realm/realm-cocoa/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by loganSims** [comment]
Sounds like you might be using Swift 3 for your project but compiling Realm with Swift 2.3. Check 'Use Legacy Swift Language Version' in your project's Target under Build Settings as well as your Realm Target. If it is set to 'No' for your project and 'YES' for Realm then that should be the cause of your error.

You'll need to set both to 'NO' if you want to use Swift 3 or set them to 'YES' for Swift 2.3.

**Comment by bdrelling** [comment]
Still unable to properly compile RealmSwift 1.0.2 with my Swift 3 project.

![screen shot 2016-09-16 at 1 03 05 pm](https://cloud.githubusercontent.com/assets/3022693/18594434/0622f0b0-7c0e-11e6-931f-bb196f78ff94.png)

**Comment by jpsim** [comment]
@bdrelling Realm Swift 1.0.2 was released about two months ago, before Swift 3 came out. You'll need to build from `master` to get a version that supports Swift 3. See https://github.com/realm/realm-cocoa/issues/3894#issuecomment-247423249 for temporary installation instructions until we release 1.1.0 later today.

**Comment by shobhz** [comment]
Im sorry guys.. My mistake!

I was using the wrong branch..

Im really sorry!

**Comment by bdrelling** [comment]
@jpsim Got it. I assumed the legacy version check would work. I can fortunately wait until later today, so not a huge deal.

Thanks for the support!
