### ISSUE TITLE
Pod spec lint fails for Realm

### ISSUE THREAD

**Issue by DavidCMurphy** [realm/realm-cocoa#4101]
## Goals

What do you want to achieve?

Successfully run pod spec lint on my private pod repo with realm as a dependancy

## Expected Results

What did you expected to happen?

Lint passes successfully

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

`-> Installing Realm (1.0.2)
 > Git download
 > Git download
     $ /Applications/Xcode.app/Contents/Developer/usr/bin/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/vh/x_pmp6m16t9fxqn60k9dm1sm0000gn/T/d20160916-4289-4kaszm --template= --single-branch --depth 1 --branch v1.0.2
     Cloning into '/var/folders/vh/x_pmp6m16t9fxqn60k9dm1sm0000gn/T/d20160916-4289-4kaszm'...
     Note: checking out '10ef693b9935694f58f49b264008f6cf3ccccf61'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   sh: build.sh: No such file or directory
 -> VelocityClient (1.4.3)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR | [iOS] unknown: Encountered an unknown error (/bin/bash -c 
set -e
sh build.sh cocoapods-setup

sh: build.sh: No such file or directory`

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

listing my private repo using the command pod spec lint --verbose.

I dont know if this is reproducible for anyone else.

## Version of Realm and Tooling

Realm version: ?

1.0.2

Xcode version: ?

Version 8.0 (8A218a)

iOS/OSX version: ?

10.11.6

Dependency manager + version: ?

1.1.0.rc.2

**Comment by DenHeadless** [comment]
Was this issue somehow fixed or is there a workaround?

**Comment by DavidCMurphy** [comment]
I haven't been able to find a solution for this yet, its still failing on the 1.1.0 build as of this morning. It is however a duplicate of #3985 so I'm following that for now.

**Comment by jpsim** [comment]
@DenHeadless @DavidCMurphy if you're experiencing a problem, the only way Realm contributors will look at it is if there's an _open_ issue with clear steps to reproduce. So if you're still experiencing this problem, you should reopen this issue and someone will look into it.

**Comment by DenHeadless** [comment]
@jpsim I think this issue is basically a duplicate of #4112 - error message is the same. So i think we should wait before opening a new one, since that issue has clear steps to reproduce.

**Comment by jpsim** [comment]
Understood. Thanks @DenHeadless.

**Comment by 350541732** [comment]
> I haven't been able to find a solution for this yet, its still failing on the 1.1.0 build as of this morning. #3985 is seeing the same issue and has simply been closed.

same +1
