### ISSUE TITLE
RealmSwift 1.1.0 cocoapods install fails

### ISSUE THREAD

**Issue by maxydon** [realm/realm-cocoa#4103]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

update realmSwift for xcode8

## Expected Results

realm to be installed correctly

## Actual Results

[!] /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/9z/x11srt_112s7yc3v7wq4pj540000gn/T/d20160916-835-1h5rr1p --template= --single-branch --depth 1 --branch v1.1.0 --recursive

Cloning into '/var/folders/9z/x11srt_112s7yc3v7wq4pj540000gn/T/d20160916-835-1h5rr1p'...
Note: checking out '5fbb4ce86b0679c2ced0babd2f1cfaf33f5dd68f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
Cloning into '/private/var/folders/9z/x11srt_112s7yc3v7wq4pj540000gn/T/d20160916-835-1h5rr1p/Realm/ObjectStore'...
error: no such remote ref 7922710805950c353f00c4ba5146e2ff98aa8aa9
Fetched in submodule path 'Realm/ObjectStore', but it did not contain 7922710805950c353f00c4ba5146e2ff98aa8aa9. Direct fetching of that commit failed.

## Steps to Reproduce

pod update/pod install from command line

## Code Sample
NA

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.1.0

Xcode version: na

iOS/OSX version: maxOS 10.11.6

Dependency manager + version: cocoapods 1.0.1

**Comment by DavidLari** [comment]
I think you might need cocoapods 1.1.0 rc 1.

**Comment by maxydon** [comment]
homebrew sees only the 1.0.1 version. it doesn't let me install that version.

**Comment by maxydon** [comment]
Installed cocoapods like so `sudo gem install -n /usr/local/bin cocoapods` and the update worked correctly
