### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 2.3

### ISSUE THREAD

**Issue by PiotrStepien** [realm/realm-cocoa#4105]
I have a big problem with build my project, which I convert to Swift 3. Each time, when i try to build it I receive this message "Module compiled with Swift 3.0 cannot be imported in Swift 2.3". How can I build my project?

Realm version:  1.1.0
Xcode version: 8.0
iOS/OSX version: iOS 10

**Comment by nixzhu** [comment]
My project has converted to Swift 2.3, I use `carthage update --toolchain com.apple.dt.toolchain.Swift_2_3` to update Realm to 1.1.0, but has the same error.

**Comment by smebberson** [comment]
I converted my project to Swift 2.3 and I have the same problem:

- Real version 1.1.0
- Xcode version 8.0

I've used `carthage update --platform iOS --toolchain com.apple.dt.toolchain.Swift_2_3 realm-cocoa` which compiled without error (but when you view in Xcode, the message _Module compiled with Swift 3.0 cannot be imported in Swift 2.3_ is received).

**Comment by xspyhack** [comment]
Look at #4099 , it works for me.

**Comment by smebberson** [comment]
We're trying to use Swift 2.3...

**Comment by smebberson** [comment]
I executed the following `carthage update --platform iOS --toolchain com.apple.dt.toolchain.Swift_2_3 --no-use-binaries realm-cocoa` and received:

```
warning: target specifies SWIFT_VERSION = '3.0', but it is overridden by TOOLCHAINS = 'com.apple.dt.toolchain.Swift_2_3'
```

Despite having chosen 'Use legacy swift version' in both build targets.

**Comment by newbdez33** [comment]
in Cartfile:
>github "realm/realm-cocoa" "master"

and run:
> carthage update 'realm-cocoa' --toolchain com.apple.dt.toolchain.Swift_2_3

**Comment by PiotrStepien** [comment]
Any solution to do this in cocoadopds?

**Comment by smebberson** [comment]
So, I got it to build with `github "realm/realm-cocoa" "master"` in Cartfile and `carthage update --platform iOS --toolchain com.apple.dt.toolchain.Swift_2_3 realm-cocoa` on the command line.

The same thing doesn't work on 1.1.0 so I guess something has changed in the last few commits on master (not that I could pick it).

**Comment by kishikawakatsumi** [comment]
Carthage always download pre-built binary if it is present. The pre-built binary is built by Swift 3.0. So you should not use pre-built binaries if you use Swift 2.3 or 2.2.

You can avoid Carthage download pre-built binaries using `--no-use-binaries` option.

So Cartfile is as follows:
(No need to specify `master` branch)
```
github "realm/realm-cocoa"
```

Then you can install RealmSwift with the following command:

```
carthage update --no-use-binaries
```

**Comment by smebberson** [comment]
@kishikawakatsumi would you expect the following to work:

Cartfile as:

```
github "ream/realm-cocoa" == 1.1.0
```

and

```
carthage update --platform iOS --toolchain com.apple.dt.toolchain.Swift_2_3 --no-use-binaries realm-cocoa
```

**Comment by kishikawakatsumi** [comment]
@smebberson Yes, it should work.

**Comment by jpsim** [comment]
I've added the `--no-use-binaries` argument to the Carthage installation instructions for Swift 2.3: https://realm.io/docs/swift/latest/#installation

> Any solution to do this in cocoadopds?

@PiotrStepien please follow the CocoaPods instructions described in https://realm.io/docs/swift/latest/#installation

**Comment by smebberson** [comment]
@kishikawakatsumi, that doesn't work. Only github `"ream/realm-cocoa" "master"` works...

**Comment by jpsim** [comment]
@smebberson that shouldn't be the case. `--no-use-binaries` builds from source and there have been no relevant changes on master since the 1.1.0 release (https://github.com/realm/realm-cocoa/compare/v1.1.0...master).

**Comment by smebberson** [comment]
@jpsim, yeah, I agree. I already looked. It's strange. I guess I'm doing something wrong but I'm not sure what. Anyway, I've worked around it.

Thanks for your input.
