### ISSUE TITLE
Kingpin setAnnotation(RLMObject) causes realm::IncorrectThreadException:

### ISSUE THREAD

**Issue by FedericoPaliotta** [realm/realm-cocoa#4106]
## Issue Description

Hi, I'm working on a map-based iOS project, and I'm trying to persist my annotation objects through Realm. Also, the annotations are managed by Kingpin's clustering controller. Unfortunately, this is causing a 'realm::IncorrectThreadException:' 

## Steps to Reproduce

- Create an AnnotationObject subclassing a Realm Object and conforming to MKAnnotation protocol.
- Use Kingpin to manage the clusters on the map.
- Add a non-manged AnnotationObject instance to Realm.
- Set the same instance to be managed form Kingpin clustering controller.

## Version of Realm and Tooling

Realm version: Latest version.

Kingpin version: 0.3

Xcode version:  7.3.1

iOS/OSX version: iOS 9.3.5 / 10

**Comment by PiotrStepien** [comment]
Maybe you do some staff in separate thread like `dispatch_get_global` and this it the reason why you have this exception.

**Comment by jpsim** [comment]
You'll get this exception if external libraries, or your code, is using Realm Objects created or added to the Realm on a different thread. This violates Realm's thread confinement rules and therefore throws an exception, to prevent you from using potentially stale or incorrect data.

See Realm's docs on [Threading](https://realm.io/docs/swift/latest/#threading) to learn more about how Realm deals with threads.

**Comment by stel** [comment]
@FedericoPaliotta did you resolve this issue? Can we close this issue or do you still need help?

**Comment by FedericoPaliotta** [comment]
My apologizes, I got caught in this project and didn't take a minute to
follow this thread. I'm so sorry. 😔

The issue is still there, but we ended up decoupling the object that we use
with kingpin and the one we store in realm. So not exactly resolved the
issue itself, but feel free to close it on gitHub.

We tried all of the above suggested as well as what the documentation says.
In any case, we could not get it to work. It's really weird, even though we
create a new realm object each time we access an annotation object, and
even calling fictions like beginTransaction, commitTransaction and so on,
nothing seems to save us from that realm::IncorrectThreadException.

We were able to dig into kingpin's code (I can show you if you are
interested) and isolate the code where the exception raises, but we have no
clue of why that happen.

Thanks for your support.

Federico Paliotta

**Comment by stel** [comment]
@FedericoPaliotta thanks for your response! It would be great if you could provide some sample code that causes this exception for you, so we can try to help with this.

**Comment by FedericoPaliotta** [comment]
Hi, unfortunately I’m not allowed to disclose any code for the actual
project I’m working on, but I’ve made this
<https://github.com/FedericoPaliotta/RealmKingpin-IssueSample> sample
project, replicating the same scenario causing the issue.

I didn’t had time to add the different kind of (non)solutions we tried. So
the code as it is in the sample project is just meant to cause the same
issue. But, the architecture needs to be like described, viewControllers
talk to a dataStore singleton which is in charge of requesting data from a
server an persist it in realm..

Let me know if you have any questions

Best,

Federico Paliotta


2016-10-10 8:56 GMT-04:00 Dmitry Obukhov <notifications@github.com>:

**Comment by stel** [comment]
You've got this exception because you create `AnnotationObj`s on background thread (https://github.com/FedericoPaliotta/RealmKingpin-IssueSample/blob/master/RealmKingpinSample/RealmKingpinSample/DataStore.swift#L43) and then trying to access these instances  on the main thread.

I'd suggest you to not to pass these instances via callback from `fetchAnnotations` method but use Fine-Grained Notifications for updating the map view, check out this tutorial: https://realm.io/news/marin-todorov-fine-grained-notifications/

**Comment by jpsim** [comment]
Closing since @stel's last comment seems to have correctly diagnosed the problem and offered a solution.

**Comment by FedericoPaliotta** [comment]
That's cool. Thanks for your support! ;)
