### ISSUE TITLE
CocaPods [!] Error installing Realm 1.1.0 

### ISSUE THREAD

**Issue by aelam** [realm/realm-cocoa#4107]
## Goals

CocoaPods install Realm 1.1.0
## Actual Results
A bunch of errors 

## Steps to Reproduce

Set dependency of Realm 1.1.0  in Podfile 
pod update 
What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.1.0

Xcode version: 7.1

iOS/OSX version: ?

Dependency manager + version: CocoaPods 0.39.0

```
[!] Error installing Realm
[!] /usr/local/opt/git/libexec/git-core/git clone https://github.com/realm/realm-cocoa.git /var/folders/zp/g4lt8dzj4p3b1tb8jwl702m40000gp/T/d20160918-93744-ew0rg5 --single-branch --depth 1 --branch v1.1.0 --recursive

Cloning into '/var/folders/zp/g4lt8dzj4p3b1tb8jwl702m40000gp/T/d20160918-93744-ew0rg5'...
Note: checking out '5fbb4ce86b0679c2ced0babd2f1cfaf33f5dd68f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
Cloning into '/private/var/folders/zp/g4lt8dzj4p3b1tb8jwl702m40000gp/T/d20160918-93744-ew0rg5/Realm/ObjectStore'...
error: no such remote ref 7922710805950c353f00c4ba5146e2ff98aa8aa9
Fetched in submodule path 'Realm/ObjectStore', but it did not contain 7922710805950c353f00c4ba5146e2ff98aa8aa9. Direct fetching of that commit failed.
```

**Comment by aelam** [comment]
I've found there is no commit 7922710805950c353f00c4ba5146e2ff98aa8aa9 in  (https://github.com/realm/realm-object-store.git) 'Realm/ObjectStore'

**Comment by DavidLari** [comment]
You need to install Cocoapods 1.1 release candidate.

**Comment by aelam** [comment]
😢

发自我的 iPhone

**Comment by jpsim** [comment]
@aelam we have to close this since you neglected to fill out the new issue template. Please follow the instructions in https://realm.io/docs/swift/latest/#installation and https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers and reopen an issue taking care to fill out the entire issue template and we'll gladly take another look.
