### ISSUE TITLE
Rename `addNotificationBlock:` for RealmSwift

### ISSUE THREAD

**Issue by aschuch** [realm/realm-cocoa#4109]
## Goals

I am proposing a naming change to the `addNotificationBlock:` family of functions.
The naming of `addNotificationBlock:` does not seem to be very consistent with the latest Swift naming conventions, thus feels a bit "out of place" in a modern Swift app.
## Expected Results

Something like the following would fit much nicer into a modern Swift code base:

``` swift
let results: Results<X> = ...
results.observe { changes in
    // ...
}
```

`observe:` is my favourite, but there are a few other options towards the new naming that come to mind.
- `addNotification:`
- `notifyOnChanges:`
- `observeChanges:`
- `addObserver:`

What do you think?

**Comment by jpsim** [comment]
Thanks for the suggestions @aschuch! I tend to agree with you, but it's important to keep in mind that Realm is now 1.0 and we have a commitment to not break the API until the next major release. So I'm placing this in our "Idea Backlog".

**Comment by aschuch** [comment]
Right, this would be quite a breaking change to many codebases. Maybe `observe:` can be introduced in one of the next 1.x releases without removing `addNotificationBlock:`? Or would that be too confusing?

**Comment by jpsim** [comment]
That's a possibility. Of course, you can always create an extension in your own apps that adds the names you'd prefer working with in the meantime.

**Comment by aschuch** [comment]
Sure thing, thanks for the heads up. 😎

**Comment by austinzheng** [comment]
Tracked in #5025.
