### ISSUE TITLE
why the latest version in cocoapods is still 1.0.2?

### ISSUE THREAD

**Issue by runningJoey** [realm/realm-cocoa#4110]
i am trying to install the latest version 1.1.0
but cocoapods always install 1.0.2 while "pod install" or "pod update"

i also use "pod search RealmSwift" to search,but the latest version is 1.0.2

anyone knows about this? thx a lot!!

---------------------------------------------
Realm version: try to use 1.1.0

Xcode version: 8.0

iOS/OSX version: 10.11.6

Dependency manager + version: cocoapods 1.0.1

**Comment by simonbengtsson** [comment]
I ran `pod update` and got version `1.1`. On the [cocoa pods website](https://cocoapods.org/pods/Realm), version 1.1 is also listed. You probably has some kind of cache or version constraint set.

**Comment by kishikawakatsumi** [comment]
@runningJoey CocoaPods doesn't update automatically pods master repo from version `1.0.0`. So you should do that explicitly. 

```
pod install --repo-update
```
