### ISSUE TITLE
Realm accessed from incorrect thread

### ISSUE THREAD

**Issue by stephenkopylov** [realm/realm-cocoa#4115]
Hello and thanks everyone for this wonderful ORM!

From time to time I face this problem:
```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
```

Yes, I know that Realm-object needs to be instantiate through "defaultRealm" for every thread.
So, It's really hard to reproduce this bug, but if I leave my app running for a long time (f.e. 2 hours) I almost always get it.
The app crashes here:
![screen shot 2016-09-19 at 17 51 09](https://cloud.githubusercontent.com/assets/5202281/18636484/ae1dcbac-7e91-11e6-91d2-cfe7740e9139.png)

Code example (Following method runs in background serial queue (gcd)):

```objectiveC
+ (void)parseNewObjects:(<NSString*>NSArray *)objectNames //objects - array with strings
{
    RLMRealm *realm = [RLMRealm defaultRealm]; //here I get current instance of Realm
    
    NSMutableArray *parsedObjects = @[].mutableCopy;
    
    [objectNames enumerateObjectsUsingBlock:^(NSString *objectName, NSUInteger idx, BOOL *_Nonnull stop) {
        MyCustomObject *object = [MyCustomObject new];
        
        object.oName = objectName; //here I set object's name

        [parsedObjects addObject:object]; //here I push named object to mutable array
    }];
    
    [realm beginWriteTransaction]; // here I get the crash =(
    [realm addOrUpdateObjectsFromArray:parsedObjects];
    [realm commitWriteTransaction];
}
```

I already checked the app for memory and disk space leaks and found nothing serious. So, this crash happens in absolutely trivial situation:
![screen-shot-2016-09-19-at-18 09 05](https://cloud.githubusercontent.com/assets/5202281/18637222/5fe3e9fa-7e94-11e6-8911-3537faf613c0.jpg)

Last days' crashes:
![screen shot 2016-09-19 at 17 58 58](https://cloud.githubusercontent.com/assets/5202281/18636820/d62f6b40-7e92-11e6-902d-3d5041dbf4f8.png)

version of realm: 1.1.0

versions of ios: 8-9-10

**Comment by austinzheng** [comment]
I wonder if it's possible that the enumeration block is occasionally being called on a queue different from that which `parseNewObjects:` is running on. Can you try getting rid of the `enumerateObjectsUsingBlock:` call and using a for-loop instead, and seeing if you can reproduce the crash?

**Comment by stephenkopylov** [comment]
@austinzheng as you see, enumeration block does nothing with realm and crash happens in `beginWriteTransaction` method.
I try to avoid this crash right now, cause I think it may be my architecture fault. 
So, new version of my app and crashlytics will show the results of this changes.

**Comment by austinzheng** [comment]
Okay, great. Let us know if the new version of your app fixes the problem, or if you need us to help you further!

**Comment by stephenkopylov** [comment]
The problem on my side, I think - I have some OOM's in my App, so it happens when user does not have enough memory.
Sorry for worrying.
![screen shot 2016-10-02 at 04 51 19](https://cloud.githubusercontent.com/assets/5202281/19018047/e34998be-885b-11e6-9b90-f63f9614de2c.png)

**Comment by austinzheng** [comment]
No problem! Thanks for getting back to us, good luck fixing your memory issues, and feel free to open another ticket if you run into any Realm-related issues!
