### ISSUE TITLE
Crashing during enumeration of RLMLinkingObjects

### ISSUE THREAD

**Issue by jpstern** [realm/realm-cocoa#4116]
## Goals
Crash-free enumeration

## Expected Results
Enumeration w/o a crash

## Actual Results
Crash during fast enumeration

## Steps to Reproduce

I am using ObjectMapper to map directly to a RLMObject subclass.
During part of the mapping, I am enumerating a property of RLMLinkingObjects type and it crashes in the realm library at the line indicated below.

The object has not yet been added to a realm.

## Code Sample

```
dynamic var sections: RLMLinkingObjects!

override class func linkingObjectsProperties() -> [String : RLMPropertyDescriptor] {
"sections": RLMPropertyDescriptor(withClass: PartySection.self, propertyName: "party")
}

for section in self.sections {
  ...
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state
                                    count:(NSUInteger)len {
    [_realm verifyThread];
    if (!_tableView.is_attached() && !_collection) {
        @throw RLMException(@"Collection is no longer valid");
    }
    // The fast enumeration buffer size is currently a hardcoded number in the
    // compiler so this can't actually happen, but just in case it changes in
    // the future...
    if (len > RLMEnumerationBufferSize) {
        len = RLMEnumerationBufferSize;
    }

    NSUInteger batchCount = 0, count = state->extra[1];

    Class accessorClass = _info->rlmObjectSchema.accessorClass; //**CRASH - EXC_BAD_ACCESS**
    for (NSUInteger index = state->state; index < count && batchCount < len; ++index) {
        RLMObject *accessor = RLMCreateManagedAccessor(accessorClass, _realm, _info);
        if (_collection) {
            accessor->_row = (*_info->table())[[_collection indexInSource:index]];
        }
        else if (_tableView.is_row_attached(index)) {
            accessor->_row = (*_info->table())[_tableView.get_source_ndx(index)];
        }
        RLMInitializeSwiftAccessorGenerics(accessor);
        _strongBuffer[batchCount] = accessor;
        batchCount++;
    }

    for (NSUInteger i = batchCount; i < len; ++i) {
        _strongBuffer[i] = nil;
    }

    if (batchCount == 0) {
        // Release our data if we're done, as we're autoreleased and so may
        // stick around for a while
        _collection = nil;
        if (_tableView.is_attached()) {
            _tableView = {};
        }
        else {
            [_realm unregisterEnumerator:self];
        }
    }

    state->itemsPtr = (__unsafe_unretained id *)(void *)_strongBuffer;
    state->state += batchCount;
    state->mutationsPtr = state->extra+1;

    return batchCount;
}

```
## Version of Realm and Tooling

Realm version: realm-cocoa v1.1.0

Xcode version: Xcode 8.0, Swift 2.3

iOS/OSX version: 9.3.5

Dependency manager + version: Cocoapods 0.39.0

**Comment by jpsim** [comment]
@jpstern could you please share an Xcode project that reproduces this issue? Anything you can do to simplify us being able to trigger this ourselves will improve this odds of this being resolved quickly.

**Comment by francoisduchemin** [comment]
Also have a crash when accessing a LinkingObjects.
class Reading: Object {
  ...
  let meterOwners = LinkingObjects(fromType: Meter.self, property: "readings")
}


let meterOwners = readingToDelete.meterOwners

(lldb) po meterOwners
expression produced error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x0).
The process has been returned to the state before expression evaluation.

**Comment by jpsim** [comment]
@francoisduchemin could you please share an Xcode project that reproduces this issue? Anything you can do to simplify us being able to trigger this ourselves will improve this odds of this being resolved quickly.

**Comment by francoisduchemin** [comment]
never mind I was doing something wrong... everything is working fine.

**Comment by stel** [comment]
Closing this issue, @francoisduchemin feel free to reopen it or create a new one if you need any other help.
