### ISSUE TITLE
Realm library is missing when signing archive for enterprise distribution

### ISSUE THREAD

**Issue by kljajo** [realm/realm-cocoa#4117]
There seems to be an issue when exporting archive for Enterprise distribution.
I am using Realm and RealmSwift 1.1.0 with Xcode8.

Here is the stack trace:
Termination Description: DYLD, Library not loaded: @rpath/Realm.framework/Realm | Referenced from: /var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/xxxx | Reason: no suitable image found. Did find: | /private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/Frameworks/Realm.framework/Realm: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/Frameworks/Realm.framework/Realm' | /private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxxx.app/Frameworks/Realm.framework/Realm: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/Frameworks/Realm.framework/Realm' | /private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/Frameworks/Realm.framework/Realm: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DF539C48-5
Triggered by Thread: 0

**Comment by jpsim** [comment]
@kljajo could you please share more information? How are you building Realm? If you're using CocoaPods/Carthage/Xcode, what versions of everything are you using? What steps can we take to reproduce this?

There's a reason this information is requested in the new issue template. It's difficult for us to help you without that information.

**Comment by kljajo** [comment]
@jpsim I am using CocoaPods version 0.39.0 with Xcode 8.
Just add realm via CocoaPods in your Swift 3 project. Build it, create an archive, export it for In-House distribution and put it on the device. App will crash on start with above stack trace.
Note that this does not happen with AppStore and AdHoc distributions.

**Comment by jpsim** [comment]
Thanks for sharing that info, @kljajo. I think I have enough information to help you, now I just have to take the time to attempt to reproduce the problem so I can investigate further.

How critical is it for this to be fixed as soon as possible? Do you have a workaround?

**Comment by kljajo** [comment]
Hi @jpsim . Unfortunately I don't have workaround. I am in the middle of the project which has to be delivered to the client before end of a month. I will have to convert the code without Realm if you perhaps don't have some workaround? Thanks.

**Comment by jpsim** [comment]
Understood. Not I don't have a workaround to suggest to you because I'm not sure why this is happening and haven't reproduced it myself yet.

If you do want to accelerate the process of us looking into this, a full reproducible sample Xcode project and steps to trigger the issue would greatly help.

**Comment by kljajo** [comment]
hi @jpsim,
I have resolved the issue. The problem was with enterprise certificate not being properly generated by Developer portal. After I've revoked it and regenerated it, app can be started now with realm libraries included in the project.

**Comment by jpsim** [comment]
Glad to hear it, thanks!
