### ISSUE TITLE
Block of the write function is non-throwable in Swift 3

### ISSUE THREAD

**Issue by akolov** [realm/realm-cocoa#4120]
In Swift 3 version block of the write function is not marked as throwable, even though documentation states that it can throw. Swift 2 version is still implemented with a block that can throw.

```swift
// Declaration in Swift 3 version
public func write(_ block: () -> Swift.Void) throws

// Declaration in Swift 2 version
public func write(@noescape block: (() throws -> Void)) throws
```

**Comment by jpsim** [comment]
Thanks for reporting this, it's an omission caused by splitting our codebase to support both Swift 2.x & 3. The good news is that it's not a breaking change to add `throws` to the block, so when this is fixed, it should be included in the following release.
