### ISSUE TITLE
error: The following binaries use incompatible versions of Swift:

### ISSUE THREAD

**Issue by sreejithsn** [realm/realm-cocoa#4123]
error: The following binaries use incompatible versions of Swift:
RealmSwift.framework/RealmSwift
/Users/xxx/Library/Developer/Xcode/DerivedData/App-cgazqddnhxynjacblakqrxuhwpcc/Build/Products/Debug-iphonesimulator/App.app/

Xcode 8,Swift 3

**Comment by jpsim** [comment]
Swift requires that all dependencies be built with the same version of the compiler.
