### ISSUE TITLE
Failure to compile under Swift 3.0 with CoreLocation

### ISSUE THREAD

**Issue by DominicFrazer** [realm/realm-cocoa#4126]
## Goals

I want to compile Swift 3 class without errors

## Expected Results

Successful compilation

## Actual Results

What did happened instead?  

![actual results](https://cloud.githubusercontent.com/assets/5267564/18752935/385b85f8-80e4-11e6-8e7a-5c1cd00e0fed.png)

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Here is the code sample. A single class that will not compile if the "import RealmSwift" line is included
import UIKit
import RealmSwift   //comment out this line to get the code to compile
import CoreLocation

class PSLocationManager: NSObject, CLLocationManagerDelegate {
    func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
    }
}

## Version of Realm and Tooling

Downloaded Ream 1.1.0 yesterday

Realm version: 1.1.0 Swift 3.0
// Generated by Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)

Xcode version: 8.0 (8A218a)

iOS/OSX version: 10

Dependency manager + version: ?

**Comment by jpsim** [comment]
Swift's namepsacing requires that you fully qualify top-level declarations that could be ambiguous. So you'll need to refer to `Swift.Error` and `RealmSwift.Error` explicitly when both modules are imported.

See #4125 for further discussion.

**Comment by DominicFrazer** [comment]
So, Realm isn't going to change because this is a breaking change. It clearly affects the (new) standard Swift methods. I will reconsider using Realm in projects, it may be easier to revert to CoreData where projects are going to be supported by teams rather than individuals. Cheers.
