### ISSUE TITLE
IncorrectThreadException() when thread is not changed.

### ISSUE THREAD

**Issue by belakva** [realm/realm-cocoa#4127]
Hi!
We're experiencing crashes with following stack trace:
1.
![screen shot 2016-09-22 at 18 16 20](https://cloud.githubusercontent.com/assets/14931273/18754369/721128ba-80f9-11e6-91dd-765ec06124ca.png)
2.
![screen shot 2016-09-22 at 18 16 38](https://cloud.githubusercontent.com/assets/14931273/18754378/7e007cb6-80f9-11e6-94d1-8bf7115e4fff.png)
3.
![screen shot 2016-09-22 at 18 16 52](https://cloud.githubusercontent.com/assets/14931273/18754410/99e4b938-80f9-11e6-9ddf-2ca1e95d4bb5.png)
4.
![screen shot 2016-09-22 at 18 09 41](https://cloud.githubusercontent.com/assets/14931273/18754360/684efe24-80f9-11e6-9067-e85687cc59af.png)

As you can see on pic. 4, threads ids match. Does not it mean that we should not get an exception here?

Realm version: Realm Objective-C 0.102.1 - Realm Objective-C 1.1.0

Xcode version: 7 & 8

iOS/OSX version: OS X el Captain 10.11.6

Dependency manager + version: Cocoapods 1.0.1

**Comment by jmfieldman** [comment]
The underlined numbers in the image do not match.

```
First:  0x16e91f000
Second: 0x16e19f000
```

**Comment by belakva** [comment]
@jmfieldman oh, thank you! That's correct. But if you follow the trace, you can see, that thread is not changed at any point. Or am I wrong here also?

**Comment by tgoyne** [comment]
The stack trace shows a `dispatch_async()`.

**Comment by belakva** [comment]
@tgoyne yes, but the Realm instance is get inside of this asynchroniously dispatched block.

**Comment by austinzheng** [comment]
Tracking this issue further in the linked ticket (4132).
