### ISSUE TITLE
Field Level Encryption as opposed to whole db encryption

### ISSUE THREAD

**Issue by tbeech** [realm/realm-cocoa#4129]
## Goals

What do you want to achieve?
I think a great encryption enhancement would be to enable field level encryption vs. whole database encryption. I think this would be a preferable enhancement over whole db encryption as there might be fields that just aren't sensitive and can remain unencrypted. This would also aid in a more secure encrypted realm that can be used in background processes since the encrypted fields would remain encrypted vs. with whole db encryption, the entire data would need to be unencrypted to support background processing. I think this would negate some of the security features that encryption would provide.

## Expected Results

What did you expected to happen?
I would expect to be able to define fields on the schema as 'secure' and provide Realm with an encryption key (just like in the whole db encryption). 

I've been able to achieve this on my own by overriding the property setters but I think I've ready somewhere in the documentation that this isn't technically supported.

Note that each object or row of data is created with a random initialization vector when the object is first created. I think ideally this IV would be mutated each time the data is written to. The IV and the encrypted data are then written as a base 64 encoded string. Also, I'm using AES 128 here with kCCOptionPKCS7Padding (CBC). I chose AES 128 to be more cross compatible with other languages such as Java which require a JCE policy file to enable > 128.

```obj-c
- (void) setUserId:(NSString *)userId {
  if( userId ) {
    UWRAesCryptoProvider *cryptoProvider = [[UWRAesCryptoProvider alloc] init];
    NSData *iv = [[NSData alloc] initWithBase64EncodedString:_iv options:0];
    NSString *user = ([userId stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]) ? [userId stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]] : @"";
    
    NSError *error;
    NSData *encryptedData = [cryptoProvider encryptData:[user dataUsingEncoding:NSUTF8StringEncoding] withIV:iv error:&error];
    if( !error ) {
      _userId = [encryptedData base64EncodedStringWithOptions:0];
    }
    else {
      DDLogError(@"There was error encrypting app config data. %@", error.localizedDescription);
      [NSException raise:kUWRApplicationException format:@"There was error encrypting app config data. %@", error.localizedDescription];
    }
  }
}
```

**Comment by jpsim** [comment]
The reason we don't offer something like this is that there are lots of crypto options for encrypting & decrypting data on Apple platforms, and you have much more flexibility to do it yourself than if Realm offered one way to do this. If we started down that path, we'd inevitably get requests to offer more flexibility in the ways that per-field data is encrypted and that's a slippery slope.

We tend to focus on features that are either difficult or impossible for our users to do themselves, and this doesn't match that criteria.

> I've been able to achieve this on my own by overriding the property setters but I think I've ready somewhere in the documentation that this isn't technically supported.

You're right that Realm objects [ignore custom setters and getters](https://realm.io/docs/objc/latest/#realm-object-setters--getters-cannot-be-overriden) for managed properties.

But you can create your own setter/getter-like methods that wrap the actual managed properties:

```objc
- (void)setEncryptedUserId:(NSString *)userId {
    // encrypt userId
    self.userId = encryptedUserId;
}

- (NSString *)encryptedUserId {
    // decrypt self.userId
    return decryptedUserId;
}
```

**Comment by tbeech** [comment]
@jpsim Thanks for the feedback. BTW, just wanted to say awesome with Realm. I really enjoy using it.

**Comment by jpsim** [comment]
Glad you enjoy our product @tbeech!
