### ISSUE TITLE
'RLMException', reason: 'Object has been deleted or invalidated.' in a case where I'm explicitly checking for isInvalidated

### ISSUE THREAD

**Issue by raja-baz** [realm/realm-cocoa#4133]
So this is the code:

    - (void)markAsUnfinished 
    {
        if (self.realm) {
            if (!self.isInvalidated) {
                 [self.realm transactionWithBlock:^{
                     self.finished = NO;
                 }];
             }
         }
     }
It's obviously simplified, but not so much. There was other code in else blocks that I've removed and the transaction block is actually defined as a block further up in the code not inline, but those are its contents.

Now, I can't reproduce this, but that code has been showing up in a stack trace in crash logs I get from our app(the app is live on the store with ~400k daily active iOS users, and we're getting about 
50 crashes per day of this). So it looks like some form of rare race condition or something.

Now, it was my understanding that as long as in the same synchronous code I check for isInvalidated it will not change from under me. If I store the object for later use, or I do a dispatch_async or something, sure, but in this case, this is a freshly retrieved object, the full stack trace shows the call to markAsUnfinished coming from a function that would have just retrieved it when it made this call.

Maybe I'm misunderstanding something? Maybe isInvalidated should be checked *inside* the transaction block? I'll happily do that in that case. However, if isInvalidated is supposed to not change between retrieval and use as long as the code is synchronous then there's a bug here. I'll be happy to provide more context for the code, but I'm not at liberty to do so publicly(though I can and will if we need to follow up on this in emails).

## Version of Realm and Tooling

Realm version: 1.0.0

Xcode version: 8 GM

iOS: 8 through 10(which is everything we support)

Dependency manager + version: cocoapods 1.0.1

**Comment by raja-baz** [comment]
I've emailed a screenshot of the stack trace from our reporting tool as well as both code files involved in the stack trace so you can review this without having to rely on simplified code.

**Comment by tgoyne** [comment]
Beginning a write transaction first refreshes the Realm and advances you to the latest version of the data, so if you're performing writes on multiple threads you do need to perform the check within the write transaction.

**Comment by raja-baz** [comment]
Ah damn, I didn't know that. Is that in the docs anywhere? If not, it should be, that's the kind of gotcha that could get a lot of people and be very hard to debug(because it'll only happen due to race conditions and such).

In any case, will having an NSError instance passed to the transactionWithBlock function mitigate a crash in this situation? (I'm fine with dropping the changes silently instead of crashing)

**Comment by tgoyne** [comment]
From the `transactionWithBlock:` documentation:

     Before beginning the write transaction, `transactionWithBlock:` updates the
     `RLMRealm` instance to the latest Realm version, as if `refresh` had been called, and
     generates notifications if applicable. This has no effect if the Realm
     was already up to date.

NSError out parameters are used only to report unavoidable runtime errors, while using a deleted object is a precondition violation.

**Comment by raja-baz** [comment]
Okay, fair enough. That makes sense. However, I would disagree on the design decision of throwing an exception here instead of emitting an error. It makes writing multithreaded code that doesn't crash extremely hard. You either have to wrap all transaction blocks in try-catch constructs or check for invalidation on every single object you handle in the transaction. It can get very tedious that way...

**Comment by austinzheng** [comment]
Thanks for your feedback, we'll keep it in mind as we continue to iterate our API and feature set. If you run into any more issues please feel free to open another ticket.
