### ISSUE TITLE
Module file was created by an older version of the compiler Xcode 8 - Swift 3.0

### ISSUE THREAD

**Issue by JeremyBec** [realm/realm-cocoa#4136]
## Goals

What do you want to achieve?

Migrate my project from swift 2.3 to swift 3.0 and run the project

## Expected Results

What did you expected to happen?

Run the project

## Actual Results

What did happened instead? 

I get this error at the `import RealmSwift` line : 

`/Users/jeremybec/Documents/Labs/XCode Repository/iPilulier/iPilulier/UpdateMedecineTableViewController.swift:2:8: Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again: /Users/jeremybec/Library/Developer/Xcode/DerivedData/iPilulier-edhgfmglzeoxcydgjszqpoillrcj/Build/Products/Debug-iphonesimulator/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64.swiftmodule
`
## Steps to Reproduce

Check the two different code samples below.

## Code Sample

I followed the documentation to update Realm by setting my PodFile this way then running a `pod install` : 

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iPilulier' do

pod 'RealmSwift'

end

target 'iPilulierTests' do

end

target 'iPilulierUITests' do

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3' # or '3.0'
    end
  end
end
```

Unfortunately the `0.97.0` version is getting installed instead of the `1.1.0` So I've tried to explicitly set the path :

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iPilulier' do

pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true

end

target 'iPilulierTests' do

end

target 'iPilulierUITests' do

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3' # or '3.0'
    end
  end
end
```

I get the 1.1.0 version this time, but the error still persists.

I've also set the `Use Legacy Swift LanguageVersion` to `No`.

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004

/Applications/Xcode.app/Contents/Developer
Xcode 8.0
Build version 8A218a

/usr/local/bin/pod
1.0.1
Realm (1.1.0)
RealmSwift (1.1.0)
Realm (from `https//github.com/realm/realm-cocoa.git`, branch `master`)
RealmSwift (from `https//github.com/realm/realm-cocoa.git`, branch `master`)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

carthage not found
(not in use here)

/usr/bin/git
git version 2.8.4 (Apple Git-73)
```

**Comment by jpsim** [comment]
@JeremyBec Swift requires all linked code to be built with the same Swift version. Looks like you're building your app with Swift 3.0, whereas you're building your pods with Swift 2.3 (from the contents of your Podfile). You'll need to pick one and stick with it.

**Comment by JeremyBec** [comment]
Alright thanks. The problem is that even if I specify to use the 3.0 version the error remains. Tried cleaning, restarting Xcode many time, didnt help.

**Comment by jpsim** [comment]
You've followed the instructions at https://realm.io/docs/swift/latest/#installation and https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers?

What are the exact steps we can take to trigger this same problem?

**Comment by cwalo** [comment]
@JeremyBec When you run `carthage update`, for example, does Carthage simply download the compiled binary or does it actually build the project? It does the former in my case.

**Comment by jpsim** [comment]
I'm glad you worked this out!
