### ISSUE TITLE
Could change Object to ReamObject for swift branch

### ISSUE THREAD

**Issue by longxianlin** [realm/realm-cocoa#4139]
Object is a key word for any libs, frameworks. may conflicts.
danger

**Comment by longxianlin** [comment]
recomm use oc branch instead of swift branch. no hesitate

**Comment by jpsim** [comment]
`RealmSwift.Object` will always disambiguate the type if there are other modules with a top-level declaration of `Object`. This is Swift's namespacing as it was designed to work.
