### ISSUE TITLE
为什么 Results 调用 map 方法以后 会转换成 LazyMapRandomAccessCollection ？

### ISSUE THREAD

**Issue by yushuyi** [realm/realm-cocoa#4141]
导致 后续  的 数组方法 无法调用

![image](https://cloud.githubusercontent.com/assets/1632740/18867305/4f421d90-84d6-11e6-9308-2f9255d43060.png)

**Comment by jpsim** [comment]
Looks like you want `channels` to be an `Array`:

```swift
var channels = Array(card.joinUsers.map({ #0.cloudId }))
```

**Comment by stel** [comment]
@yushuyi do you need any other help with this or can we close this issue?

**Comment by yushuyi** [comment]
ok,thanks!
