### ISSUE TITLE
Clarify documentation for RLMRealmRefreshRequiredNotification

### ISSUE THREAD

**Issue by ralph-e-boy** [realm/realm-cocoa#4142]
Hi, wonder if you could please clarify the docs on RLMRealmRefreshRequiredNotification:

The [Cocoa constants reference](https://realm.io/docs/objc/latest/api/Constants.html#/c:@RLMRealmRefreshRequiredNotification) states that this notification is posted "...when an autorefresh occurs, when -[RLMRealm refresh] is called, after an implicit refresh from -[RLMRealm beginWriteTransaction], or after a local write transaction is completed."

The [Swift docs](http://cocoadocs.org/docsets/RealmSwift/0.96.0/Enums/Notification.html#/s:FO10RealmSwift12Notification9DidChangeFMS0_S0_) and notification name suggest that one should call `[RLMRealm refresh]` after receiving this notification. 
From https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealmUtil.mm#L89 

``` c++
    void changes_available() override {
        @autoreleasepool {
            auto realm = _realm;
            if (realm && !realm.autorefresh) {
                [realm sendNotifications:RLMRealmRefreshRequiredNotification];
            }
        }
    }
```

Seems to support the Swift doc version -- can you please clarify? (So far I've yet to see it get posted at all, auto-update or not)
Thanks in advance!

**Comment by jpsim** [comment]
A `RLMRealmRefreshRequiredNotification` notification is only ever sent for Realms with autorefresh disabled, so yes you'll always need to call `-[RLMRealm refresh]` if you want to advance the Realm to its latest state.

You can see a minimal sample of this in action in the [AsyncTests.testManualRefreshUsesAsyncResultsWhenPossible](https://github.com/realm/realm-cocoa/blob/v2.0.2/Realm/Tests/AsyncTests.mm#L274-L296) unit test.

**Comment by ralph-e-boy** [comment]
Thanks @jpsim!    
So that is a documentation bug, the cocoa docs about when notification is fired stating "This can happen when an autorefresh occurs, when -[RLMRealm refresh] is called, after an implicit refresh from -[RLMRealm beginWriteTransaction], or after a local write transaction is completed." ? 

And it follows that there is no possibility of recursion by calling refresh in response to a RLMRealmRefreshRequiredNotification. 
Correct?

Thanks again!
