### ISSUE TITLE
Migration to Realm 2.0.0 - Assertion failed: typeid(Col) == typeid(col)

### ISSUE THREAD

**Issue by kevincador** [realm/realm-cocoa#4143]
I sent a email but I'm opening a ticket too. It could help for communication.

We migrated from RealmSwift 1.1.0 to RealmSwift 2.0.0 and experiencing this at launch (old database being present) :

../realm/table.hpp:1634: [realm-core-2.0.0] Assertion failed: typeid(Col) == typeid(col)
0   Realm                               0x000000010dcbf828 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
1   Realm                               0x000000010dcbfb2a _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 506
2   Realm                               0x000000010de5264c _ZN5realm5Table19upgrade_file_formatEm + 684
3   Realm                               0x000000010dda2ef3 _ZN5realm5Group19upgrade_file_formatEi + 483
4   Realm                               0x000000010ddae3c6 _ZN5realm11SharedGroup19upgrade_file_formatEbi + 102
5   Realm                               0x000000010ddacbb8 _ZN5realm11SharedGroup7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_18SharedGroupOptionsE + 3592
6   Realm                               0x000000010dbf21f8 _ZN5realm11SharedGroup4openERNS_11ReplicationENS_18SharedGroupOptionsE + 344
7   Realm                               0x000000010dbf1eae _ZN5realm11SharedGroupC2ERNS_11ReplicationENS_18SharedGroupOptionsE + 1374
8   Realm                               0x000000010dbf18bd _ZN5realm11SharedGroupC1ERNS_11ReplicationENS_18SharedGroupOptionsE + 29
9   Realm                               0x000000010dbe5a6f _ZN5realm5Realm16open_with_configERKNS0_6ConfigERNSt3__110unique_ptrINS_11ReplicationENS4_14default_deleteIS6_EEEERNS5_INS_11SharedGroupENS7_ISB_EEEERNS5_INS_5GroupENS7_ISF_EEEEPS0_ + 3663
10  Realm                               0x000000010dbe4749 _ZN5realm5RealmC2ENS0_6ConfigE + 1049
11  Realm                               0x000000010da02cf7 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigEEN19make_shared_enablerC2ES1_ + 87
12  Realm                               0x000000010da02c95 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigEEN19make_shared_enablerC1ES1_ + 21
13  Realm                               0x000000010da023e6 _ZNSt3__110shared_ptrIZN5realm5Realm17make_shared_realmENS2_6ConfigEE19make_shared_enablerE11make_sharedIJS3_EEES5_DpOT_ + 1478
14  Realm                               0x000000010d9f4e1a _ZN5realm5Realm17make_shared_realmENS0_6ConfigE + 58
15  Realm                               0x000000010d9f3ce3 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 4339
16  Realm                               0x000000010dbe935c _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 188
17  Realm                               0x000000010db909fc +[RLMRealm realmWithConfiguration:error:] + 3580
18  RealmSwift                          0x000000010e2cae9c _TTOFCSo8RLMRealmCfzT13configurationCSo21RLMRealmConfiguration_S_ + 92
19  RealmSwift                          0x000000010e2cad1e _TFC10RealmSwift5RealmcfzT_S0_ + 110
20  RealmSwift                          0x000000010e2cade6 _TFC10RealmSwift5RealmCfzT_S0_ + 54
21  SeristModel                         0x000000010eaf2d84 _TFFC11SeristModel17DataAccessManagerP33_E46D17F2BBFEEDE342F5F64A6CA3604C22compactInPlaceDatabaseFT_T_U_FT_T_ + 36
22  libswiftObjectiveC.dylib            0x00000001133e5536 _TF10ObjectiveC15autoreleasepoolFFT_T_T_ + 38
23  SeristModel                         0x000000010eaf2c6e _TFC11SeristModel17DataAccessManagerP33_E46D17F2BBFEEDE342F5F64A6CA3604C22compactInPlaceDatabasefT_T_ + 238
24  SeristModel                         0x000000010eaf1bf2 _TFC11SeristModel17DataAccessManager19setupPersitentStackfT18withDataAccessModeOS_14DataAccessMode_T_ + 5170
25  SeristModel                         0x000000010eaef36a _TF11SeristModel19setupPersitentStackFT18withDataAccessModeGSqOS_14DataAccessMode__T_ + 138
26  Serist                              0x000000010c8078db _TFC6Serist11AppDelegate11applicationfTCSo13UIApplication30willFinishLaunchingWithOptionsGSqGVs10DictionaryCSo8NSObjectPs9AnyObject____Sb + 315
27  Serist                              0x000000010c80ed04 _TToFC6Serist11AppDelegate11applicationfTCSo13UIApplication30willFinishLaunchingWithOptionsGSqGVs10DictionaryCSo8NSObjectPs9AnyObject____Sb + 180
28  UIKit                               0x000000010f19861e -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 178
29  UIKit                               0x000000010f19a013 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4236
30  UIKit                               0x000000010f1a03b9 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1731
31  UIKit                               0x000000010f19d539 -[UIApplication workspaceDidEndTransaction:] + 188
32  FrontBoardServices                  0x000000011876376b __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
33  FrontBoardServices                  0x00000001187635e4 -[FBSSerialQueue _performNext] + 189
34  FrontBoardServices                  0x000000011876396d -[FBSSerialQueue _performNextFromRunLoopSource] + 45
35  CoreFoundation                      0x0000000111af0311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
36  CoreFoundation                      0x0000000111ad559c __CFRunLoopDoSources0 + 556
37  CoreFoundation                      0x0000000111ad4a86 __CFRunLoopRun + 918
38  CoreFoundation                      0x0000000111ad4494 CFRunLoopRunSpecific + 420
39  UIKit                               0x000000010f19bdb6 -[UIApplication _run] + 434
40  UIKit                               0x000000010f1a1f34 UIApplicationMain + 159
41  Serist                              0x000000010c812162 main + 114
42  libdyld.dylib                       0x000000011355968d start + 1
43  ???                                 0x0000000000000001 0x0 + 1
IMPORTANT: if you see this error, please send this log to help@realm.io.

**Comment by jegumhon** [comment]
I've got the exactly same situation!

**Comment by ab-rdarts** [comment]
+1

**Comment by jpsim** [comment]
We've fixed this in realm/realm-core#2218, we'll close this issue once we can cut a release of the objc/swift SDKs that includes it.

**Comment by jegumhon** [comment]
If so, could you let me know when I can get the new pod of Realm that included the patch about this situation?

**Comment by jpsim** [comment]
Closing since we updated to core 2.0.1 in #4156 (though we have yet to cut a release with it).

@jegumhon to use CocoaPods with pre-releases of Realm, put this in your Podfile:

```ruby
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
```
