### ISSUE TITLE
Realm 2.0.0 Documentation update for Swift 3 usage of Collection Notifications

### ISSUE THREAD

**Issue by mlusas** [realm/realm-cocoa#4146]
## Goals

What do you want to achieve? Using Realm Collection Notifications to update a tableView in Swift 3.  The documentation simply needs to be updated.  I've provided correct code below.

## Expected Results

What did you expected to happen?  Code to compile.

## Actual Results

What did happened instead?  Code does not compile, and instead gives an error: "Argument labels '(forRows:, inSection:)' do not match any available overloads."

## Steps to Reproduce

What are steps we can follow to reproduce this issue?  Use the code listed in the 2.0.0 Realm Swift Documentation.  [https://realm.io/docs/swift/2.0.0/#collection-notifications](url)

## Code Sample

```
  // Currently documented code that will NOT work in Swift 3
  tableView.insertRowsAtIndexPaths(indexPaths: insertions.map { NSIndexPath(forRow: $0, inSection: 0) }, withRowAnimation: .Automatic)
  tableView.deleteRowsAtIndexPaths(indexPaths: deletions.map { NSIndexPath(forRow: $0, inSection: 0) },withRowAnimation: .Automatic)
  tableView.reloadRowsAtIndexPaths(indexPaths: modifications.map { NSIndexPath(forRow: $0, inSection: 0) }, withRowAnimation: .Automatic)

   // Updated Code that will work in Swift 3
   tableView.insertRows(at: insertions.map({ IndexPath(row: $0, section: 0) }), with: .automatic)
   tableView.deleteRows(at: deletions.map({ IndexPath(row: $0, section: 0)}), with: .automatic)
   tableView.reloadRows(at: modifications.map({ IndexPath(row: $0, section: 0) }), with: .automatic)
```

## Version of Realm and Tooling

Realm version: 2.0.0

Xcode version: 8

iOS/OSX version: iOS 10

Dependency manager + version: Cocoapods 1.1.0

**Comment by jpsim** [comment]
Nice catch, thanks for reporting that! We have code sample validation for Objective-C and Swift in our docs to make sure they're always up to date, but due to limitations in our internal tooling, we can't validate code that wouldn't compile on OS X. So this is the only Objective-C or Swift code sample that opts out of validation, so of course it's infinitely more likely to become outdated.

I'm in the process of updating this now.

**Comment by jpsim** [comment]
I've pushed an update to our website, it'll be live in a few minutes.

**Comment by mlusas** [comment]
Awesome!  Great turnaround.
