### ISSUE TITLE
Not able to save multiple records

### ISSUE THREAD

**Issue by msamoylov** [realm/realm-cocoa#4147]
## Goals

I'm trying to update a few records and delete them from `NSTableView` after that. http://take.ms/6r3IV

## Expected Results

I expect that my records will be updated and `NSTableView` will be reloaded to reflect my changes.

## Actual Results

My application crashes. The stack trace is not very helpful:

```
2016-09-28 00:35:14.928156 Sluggard[32867:14110024] [General] <private>
2016-09-28 00:35:14.933061 Sluggard[32867:14110024] [General] <private>
2016-09-28 00:35:14.954890 Sluggard[32867:14110024] [General] <private>
2016-09-28 00:35:14.957179 Sluggard[32867:14110024] [General] <private>
(lldb) bt
* thread #1: tid = 0x10fcc8b, 0x00007fff7738728e AppKit`-[NSApplication _crashOnException:] + 109, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00007fff7738728e AppKit`-[NSApplication _crashOnException:] + 109
    frame #1: 0x00007fff7744d34e AppKit`__37+[NSDisplayCycle currentDisplayCycle]_block_invoke.31 + 708
    frame #2: 0x00007fff793b0f67 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    frame #3: 0x00007fff793b0ed7 CoreFoundation`__CFRunLoopDoObservers + 391
    frame #4: 0x00007fff79391b79 CoreFoundation`__CFRunLoopRun + 873
    frame #5: 0x00007fff793915b4 CoreFoundation`CFRunLoopRunSpecific + 420
    frame #6: 0x00007fff78932f6c HIToolbox`RunCurrentEventLoopInMode + 240
    frame #7: 0x00007fff78932ca9 HIToolbox`ReceiveNextEventCommon + 184
    frame #8: 0x00007fff78932bd6 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 71
    frame #9: 0x00007fff770295f5 AppKit`_DPSNextEvent + 1093
    frame #10: 0x00007fff777398eb AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
    frame #11: 0x00007fff7701dfbd AppKit`-[NSApplication run] + 926
    frame #12: 0x00007fff76fe8a8a AppKit`NSApplicationMain + 1237
  * frame #13: 0x00000001000345d4 Sluggard`main + 84 at AppDelegate.swift:58
    frame #14: 0x00007fff8e3d1255 libdyld.dylib`start + 1
```

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

https://gist.github.com/msamoylov/27e1b6c9255b254f033f44d6de115d20

## Version of Realm and Tooling

```
Realm version: 2.0.0 (installed as the Dynamic Framework)

Xcode version: 8.0 (8A218a)

macOS version: 10.12
```

**Comment by austinzheng** [comment]
Sorry to hear you're having issues with Realm. Is there any chance you can provide us with a code snippet describing what your application is doing at the time of the crash, or a reproduction case of some sort?

**Comment by jpsim** [comment]
It would help if you could print the contents of the exception. It's possible that AppKit is attempting to use a Realm object you created on a background thread from the main thread.

**Comment by msamoylov** [comment]
http://stackoverflow.com/questions/39741866/not-able-to-save-multiple-records-with-realm

**Comment by jpsim** [comment]
Interestingly enough, that StackOverflow post has the exact same information as this GitHub issue, and still doesn't contain any information about the exception. Have you tried following @bdash's advice on how to get more information about the exception being thrown?

> So the new stacktrace you've shared shows AppKit's code for dealing with uncaught Objective-C exceptions. That's useful as it means we now know there's an Objective-C exception being thrown! You can set [a breakpoint on Objective-C exceptions being thrown](http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions) to tell you the point at which things are really going wrong. Note that the linked article sets a breakpoint on all exceptions (both C++ and Objective-C), while you'll only want to break on Objective-C exceptions for this.

**Comment by msamoylov** [comment]
Yeah, that's the result of "bt".

**Comment by jpsim** [comment]
I understand that, but it's not the contents of the exception. The link shared above and on StackOverflow should help you uncover that: http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions

**Comment by msamoylov** [comment]
Let's continue on http://stackoverflow.com/questions/39741866/not-able-to-save-multiple-records-with-realm?noredirect=1#comment66890618_39741866

I will re-open this issue if we find a bug in Realm.
