### ISSUE TITLE
Redefine or Remove the User type alias

### ISSUE THREAD

**Issue by rwgrier** [realm/realm-cocoa#4153]
## Goals

Please rename the `User` typealias. After running `pod update`, I needed to namespace our User class to remove the collision. If I'm using both RealmSwift and my own homegrown models, I shouldn't have to deal with obvious collisions here. 

## Expected Results

I should be able to use the `User` object in my own code. If I'd like to type alias it, should be able to. 

## Actual Results

Compilation errors when using RealmSwift and an object called `User`

## Steps to Reproduce

N/A

## Code Sample

N/A

## Version of Realm and Tooling

Realm version: 2.0.0
Xcode version: 8.0 (8A218a)
iOS/OSX version: N/A
Dependency manager + version: CocoaPods 1.1.0.rc.2
Swift 3.0

**Comment by skydivedan** [comment]
To add to this, it's not so much that you're using a `typealias`, it's just that `User` is such a common name, probably used by many users of Realm. 

So, when you do a typealias on something that so likely to be used by other people, it's going to be a pain point. Thanks for any reconsideration of this.

**Comment by skydivedan** [comment]
Sorry, not to belabor the point (but I guess I will), you didn't do the same for RLMSyncManager and RLMSyncSession. Those were just typealiased to SyncManager and SyncSession, respectively. Couldn't this just have been named `SyncUser`?

**Comment by bdash** [comment]
It's an oversight that `User` was not prefixed. We've been bitten by Swift's lack of namespacing a few times recently so it's unfortunate that we didn't catch this case.

**Comment by bdash** [comment]
Fixed in #4181.
