### ISSUE TITLE
"Unsupported Realm file format version" crash using Realm 0.95.3 

### ISSUE THREAD

**Issue by cjcoax** [realm/realm-cocoa#4157]
We had been using XCode 7 and Realm 0.95.3 with no issue. Lately we have moved up to XCode 7.3 and have experienced spate of crashes when trying to initialize Realm and the error is:

`Error Domain=io.realm Code=2 "Unsupported Realm file format version" UserInfo={NSFilePath=XXX, NSLocalizedDescription=Unsupported Realm file format version, Error Code=2}`

It's happening when I'm trying to initialize RLMRealm with configuration as below:

```
let filesToMigrate = [
            RealmMigrator.pathForRealmWithName(Constants.Source.RealmDatabaseFileName.tools)
        ]
        
        for path in filesToMigrate {
            let config = RLMRealmConfiguration.defaultConfiguration()

            config.path = path
            config.schemaVersion = version
            
            config.migrationBlock = {(migration, oldSchemaVersion) -> Void in
                if oldSchemaVersion == 0 {
                    migration.enumerateObjects(Photo.className()) {
                        (oldObject: RLMObject?, newObject: RLMObject?) -> Void in
                        guard let newObject = newObject else { return }
                            newObject["sortId"] = 0
                    }
                }
            }
            RLMRealmConfiguration.setDefaultConfiguration(config)
            
            let _ = try! RLMRealm(configuration: config)
        }
    }
```

Realm version: 0.95.3

Xcode version: 7.3

Dependency manager + version: Cocoapods 0.39

**Comment by bdash** [comment]
Realm 0.95.3 is a _very_ old version. We've seen some reports of bugs in older versions when compiled with newer versions of Xcode that are fixed in newer versions of Realm. I'd strongly suggest upgrading to our latest release, v2.0.

**Comment by bdash** [comment]
Please let us know if you continue to have problems after updating to a current version of Realm.
