### ISSUE TITLE
for in RLMResult very slow

### ISSUE THREAD

**Issue by skarctop** [realm/realm-cocoa#4162]
result count = 2W and spend about 0.2s
```
    for (RLMObject *object in results)
```
why is so slow

**Comment by bdash** [comment]
I'm not sure what you mean by "result count = 2W".

Can you please share the query you're using to create `results`, the definitions of any model classes involved, and a rough ballpark figure of the number of instances of the model classes in question, the version of Realm you're using, and whether you're building Realm and your app in the debug or release configuration.

**Comment by jpsim** [comment]
Closing since we never heard back form @skarctop and there's not enough information in this report to proceed.
