### ISSUE TITLE
Error: Table has no Columns

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-cocoa#4169]
## Goals

I wanted to use RealmSwift to store and load my model data.

## Expected Results

I expected my example model object to be stored

## Actual Results

I got the error: Terminating app due to uncaught exception 'RLMException', reason: 'Table has no columns'

## Steps to Reproduce

create an data model and let it inherit from Object. Now try to store it.

## Code Sample

see this [pastebin](http://pastebin.com/a7Nc1zyV)
In the code sample you can see that i have many fields. So there is no reason for the "no columns" error.

## Version of Realm and Tooling

Realm version: 1.1.0

Xcode version: 8.0

iOS/OSX version: 10.11.5

**Comment by bdash** [comment]
Most properties of Swift classes that you wish Realm to persist must be declared with the `dynamic` modifier to allow Realm to manage them. See the [Property Cheatsheet](https://realm.io/docs/swift/latest/#cheatsheet) in the Realm Swift documentation for a quick overview of how to declare properties of various types.

**Comment by Montrazul** [comment]
`dynamic var id: Int64!` Property cannot be marked dynamic because its type cannot be represented in Objective-C

**Comment by Montrazul** [comment]
Ok Thank you. That solve the first problem. But another problem appeared.
I changed everything to dynamic. Now i get another error:

`fatal error: init(realm:schema:) has not been implemented`

There is also nothing mentioned about that in the setup and go documentation. How should i implement this method?

**Comment by luchaoqun123** [comment]
RealmDemo[2494:552449] *** Terminating app due to uncaught exception 'RLMException', reason: 'Table has no columns'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104c3134b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010469221e objc_exception_throw + 48
	2   RealmDemo                           0x000000010378e098 _ZL18createRowForObjectRK12RLMClassInfo + 136
	3   RealmDemo                           0x000000010378c9be _ZL23createOrGetRowForObjectIU8__strongU13block_pointerFP11objc_objectP11RLMPropertyEEmRK12RLMClassInfoT_bPb + 526
	4   RealmDemo                           0x000000010378b48a RLMCreateObjectInRealmWithValue + 2570
	5   RealmDemo                           0x000000010377839a +[RLMObject createInRealm:withValue:] + 138
	6   RealmDemo                           0x000000010365f759 __29-[ViewController viewDidLoad]_block_invoke + 137
	7   RealmDemo                           0x00000001038a8e66 -[RLMRealm transactionWithBlock:error:] + 86
	8   RealmDemo                           0x00000001038a8dce -[RLMRealm transactionWithBlock:] + 62
	9   RealmDemo                           0x000000010365f658 -[ViewController viewDidLoad] + 888
	10  UIKit                               0x00000001052eac99 -[UIViewController loadViewIfRequired] + 1258
	11  UIKit                               0x00000001052eb0cc -[UIViewController view] + 27
	12  UIKit                               0x00000001051b4c51 -[UIWindow addRootViewControllerViewIfPossible] + 71
	13  UIKit                               0x00000001051b53a2 -[UIWindow _setHidden:forced:] + 293
	14  UIKit                               0x00000001051c8cb5 -[UIWindow makeKeyAndVisible] + 42
	15  UIKit                               0x0000000105141c89 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4818
	16  UIKit                               0x0000000105147de9 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1731
	17  UIKit                               0x0000000105144f69 -[UIApplication workspaceDidEndTransaction:] + 188
	18  FrontBoardServices                  0x00000001080e6723 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	19  FrontBoardServices                  0x00000001080e659c -[FBSSerialQueue _performNext] + 189
	20  FrontBoardServices                  0x00000001080e6925 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	21  CoreFoundation                      0x0000000104bd6311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x0000000104bbb59c __CFRunLoopDoSources0 + 556
	23  CoreFoundation                      0x0000000104bbaa86 __CFRunLoopRun + 918
	24  CoreFoundation                      0x0000000104bba494 CFRunLoopRunSpecific + 420
	25  UIKit                               0x00000001051437e6 -[UIApplication _run] + 434
	26  UIKit                               0x0000000105149964 UIApplicationMain + 159
	27  RealmDemo                           0x000000010365fc0f main + 111
	28  libdyld.dylib                       0x0000000106b2068d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

- and i have the same trouble,i have the subclass of RLMObject,when I call `RLMRealm *realm = [RLMRealm defaultRealm];`,crashed.appreciate your answer

**Comment by jpsim** [comment]
@luchaoqun123 this is an issue that's been closed for several weeks. Please open a new issue with more information and steps to reproduce.

**Comment by luchaoqun123** [comment]
@jpsim OK
