### ISSUE TITLE
The document "default" could not be opened.

### ISSUE THREAD

**Issue by rollr76518** [realm/realm-cocoa#4171]
![2016-10-03 5 19 08](https://cloud.githubusercontent.com/assets/10362419/19032843/96bfd9ca-898e-11e6-85b9-7aa3a1a11583.png)

## Goals

What do you want to achieve?
**I want to check my realm data from Simulator.**
## Expected Results

What did you expected to happen?
**Get my realm data**
## Actual Results

What did happened instead?  
**A error message**

## Steps to Reproduce

What are steps we can follow to reproduce this issue?
**Use Xcode 7.3.1 >File> Open Realm...**
## Code Sample
**No code there**
## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: **Realm Browser version:2.0, Realm version:1.1.0**
Xcode version: **Xcode 7.3.1 with macOS 10.11.6**
iOS/OSX version: **iOS 9.3**
Dependency manager + version: **I think no**

**Comment by TimOliver** [comment]
Hi @rollr76518! Sorry to hear you're having some trouble opening this file.

If it's not too much trouble, could you please zip up and attach that Realm file to this issue so I can examine it? Thanks!

**Comment by rollr76518** [comment]
[default.realm.zip](https://github.com/realm/realm-cocoa/files/507499/default.realm.zip)

@TimOliver Hello man, Thank you for the reply so soooooooon!

**Comment by rollr76518** [comment]
Is there other information I can afford?

**Comment by jianghaoyuan2007** [comment]
I also met this problem.

**Comment by jianghaoyuan2007** [comment]
I fixed it finally. Using **Realm Browser Version 1.0.2 (77)**.  https://github.com/realm/realm-browser-osx/releases/download/1.0.2/RealmBrowser-1.0.2.zip

**Comment by jianghaoyuan2007** [comment]
@rollr76518 Try it out.

**Comment by rollr76518** [comment]
It works!!!!! Really Really Really appreciate!!! You are my god!!!

**Comment by jianghaoyuan2007** [comment]
@rollr76518 sorry, I am just a programmer.

**Comment by stel** [comment]
@rollr76518 I wasn't able to reproduce this issue with v2.0.1, the realm you attached was created with an older version of realm, so after upgrading it Browser was able to read its content.
![screen shot 2016-10-10 at 13 43 59](https://cloud.githubusercontent.com/assets/429275/19235100/dcde74dc-8eef-11e6-8829-401c829e30d7.png)

@jianghaoyuan2007 could you please share the realm you trying to open, thanks!

**Comment by rollr76518** [comment]
OK, I can read the older version of ream database now.

But after I click "Proceed with Upgrade", my xcode appear message.

*** Terminating app due to uncaught exception 'RLMException', reason: '/Users/xxxxx/Library/Developer/CoreSimulator/Devices/C34CE202-4F36-4DFE-AE1E-DB5C6BD93035/data/Containers/Data/Application/78562428-2A2F-45E7-BE48-0E1637F4EAD0/Documents/default.realm: Unable to open a realm at path '/Users/xxxxx/Library/Developer/CoreSimulator/Devices/C34CE202-4F36-4DFE-AE1E-DB5C6BD93035/data/Containers/Data/Application/78562428-2A2F-45E7-BE48-0E1637F4EAD0/Documents/default.realm': Unsupported Realm file format version.'

So I must upgrade my realm version to 2.0.0 ?

**Comment by stel** [comment]
@rollr76518 yes, if you've opened realm file with the latest version of Realm you're not able to open it with the previous version anymore.

I'm closing this issue for now and have made https://github.com/realm/realm-browser-osx/issues/220 for tracking error reporting, if you have any other problems with Realm Browser please feel free to make an issue in https://github.com/realm/realm-browser-osx, thanks again!

**Comment by rollr76518** [comment]
OK, I find the problem because I use Realm+JSON, and it works with Realm 0.95 only.

maybe I would use other way and upgrade my Realm to newest.

Thank you guys~

**Comment by zinyakov** [comment]
Same problem with ObjC Realm 2.0.3 in one project and RealmSwift 1.1.0 in another on Xcode 8.1; all trying to open with Realm Browser 2.0.1 on Sierra 10.12.1. Here is an example of invalid realm file:
[default.realm.zip](https://github.com/realm/realm-cocoa/files/599806/default.realm.zip)

**Comment by zhanswift** [comment]
Use old version like this: [Realm Browser on GitHub https://github.com/realm/realm-browser-osx/releases/download/v2.1.7/RealmBrowser-2.1.7.zip](https://github.com/realm/realm-browser-osx/releases/download/v2.1.7/RealmBrowser-2.1.7.zip)
