### ISSUE TITLE
swift inout parameter

### ISSUE THREAD

**Issue by ilyakooo0** [realm/realm-cocoa#4172]
It seems, that if I pass a variable managed by Realm to a function as an `inout` parameter I get this error:
`*** Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'`

What is going on here? Is passing something as an `inout` parameter implicitly modify it? I have commented out the whole body of the function and I still get the same error. It goes away only when I replace the Realm-managed variable with a regular one when calling the function.

**Comment by tgoyne** [comment]
Yes, `inout` modifies the thing passed in that spot. It doesn't pass a reference to that value; instead at the end of the function it assigns the new value of the local variable back to the thing passed in, even if it has not changed. This means that the setter of a property which is passed as an `inout` argument will always get called.

**Comment by ilyakooo0** [comment]
Is there a good way to wrap it in a realm.write {} ?

**Comment by jpsim** [comment]
I'd suggest you do something like this:

```swift
realm.beginWrite()
let didModify = maybeModifyRealmObjectPassedAsInout(myRealmObject)
if didModify {
  try realm.commitWrite()
} else {
  realm.cancelWrite()
}
```

Where `maybeModifyRealmObjectPassedAsInout` returns whether or not the object was modified.
