### ISSUE TITLE
Realm file generated with 2.0.0 is about 14.5x larger than same one generated with 1.1.0

### ISSUE THREAD

**Issue by yonomitt** [realm/realm-cocoa#4184]
## Goals

Generate the data source for my app using Realm v2.0.0

## Expected Results

The Realm file would not change greatly from the last version I generated.

## Actual Results

- Realm v1.1.0 file is 5.2 MB
- Realm v2.0.0 file generated using the same code is 75.5 MB
- Ream file converted from v1.1.0 to v2.0.0 using Realm Browser is 6.8 MB

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

1. Use cocoapods to force Realm 1.1.0
2. Generate a Realm file with lots of data
3. Copy this Realm file somewhere safe
4. Update pod to use Realm 2.0.0
5. Generate the Realm file again
6. Inspect the differences.

## Code Sample

The data is private for my app. If you don't already have a test case that exhibits this behavior, I can try to create a test case with junk data that mimics this behavior, if that helps.

## Version of Realm and Tooling

Realm version: 2.0.0 and 1.1.0

Xcode version: 8.0

iOS/OSX version: OS X 10.11.6

Dependency manager + version: Cocoapods 1.1.0.rc.2

**Comment by jpsim** [comment]
> The data is private for my app. If you don't already have a test case that exhibits this behavior, I can try to create a test case with junk data that mimics this behavior, if that helps.

Yes a code sample would certainly help. If you can't replicate in an isolated sample, you can send us code and data privately to help@realm.io.

There were a few changes in the file format between 1.x and 2.x which could account for this change. The first is that the [transaction log was merged into the main realm file](https://realm.io/news/realm-objc-swift-2.0/#removing-some-extra-files):

> The `.log`, `.log_a` and `.log_b` files no longer exist and the state tracked in them has been moved to the main Realm file. This reduces the number of open files needed by Realm, improves performance of both opening and writing to Realms, and eliminates a small window where committing write transactions would prevent other processes from opening the file.

This could impact the file size if you have a transaction that does a lot of intermediate work (growing the file to accommodate all these operations) but that just results in a small product. In Realm 1.x, all those noisy operations would've been in separate files, which would then have been discarded eventually, but with Realm 2.x, that would grow the file indefinitely, even though it'd be mostly free space. If that's what's happening, you could compact the file on app launch to help mitigate the problem.

**Comment by yonomitt** [comment]
Thanks for the help. I had been pulling the Realm from the default directory it is stored in, as I had done with previous versions of Realm. When I write the Realm to a separate file using:

```swift
Realm().writeCopy(toFile:)
```

I get a file that is 4.9 MB.

Thanks for the help and sorry for the trouble.
