### ISSUE TITLE
Default realm location breaks Apple review rules

### ISSUE THREAD

**Issue by wkoszek** [realm/realm-cocoa#4187]
## Goals

Pass the Apple review with an App using Realm.io

## Expected Results

Review failed. 

```
Your app has the UIFileSharingEnabled key set to true in the info.plist, but the Documents folder includes files and folders not intended for file sharing.
```

The thing I'm seeing is:

![image](https://cloud.githubusercontent.com/assets/483344/19122066/be12b9e8-8add-11e6-88d2-e4fd654f46c1.png)

So I guess they don't like it. While it's nice to have this for debugging and maybe exporting to you Mac and looking through the database with an external tool, I think the default should be safe for the Apple Store submission.

## Actual Results

Maybe we should make a default location be somewhere else, since I suspect more people may forget to change the location.

## Steps to Reproduce

Just enable file sharing with iTunes by setting `UIFileSharingEnabled` and you'll see the problem.

## Code Sample

.

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: `Realm 1.0.2`

Xcode version: Xcode 8

iOS/OSX version: iOS 10 / El Captain

Dependency manager + version: `pod`

## Linked issues

#3238

**Comment by wkoszek** [comment]
Just tried changing the path (below), but it didn't work. 4 files of Realm are still created:

```
    RLMRealmConfiguration *configuration = [RLMRealmConfiguration defaultConfiguration];
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
    NSString *appSupportDirPath = [paths firstObject];
    NSString *realmPath = [appSupportDirPath stringByAppendingPathComponent:@"default.realm"];
    configuration.fileURL = [NSURL fileURLWithPath:realmPath];
    [RLMRealmConfiguration setDefaultConfiguration:configuration];
    NSLog(@"XXXX path=%@ realmURL: '%@'", realmPath, configuration.fileURL);
```

**Comment by jpsim** [comment]
Hi @wkoszek, you're right that we should be opting out those files from backups, but moving them to a separate location isn't the right way to resolve this IMO. Instead, we should be setting the appropriate `NSFileProtection` attributes to prevent those files from being included in iTunes or iCloud backups and file transfers.

Until we get around to doing this, you can do that explicitly in your apps.

**Comment by bdash** [comment]
`NSFileProtection` is about encryption, so doesn't seem relevant here. You may be thinking of `NSURLIsExcludedFromBackupKey` which will prevent a given file from being backed up. I don't think that has any impact on the iTunes file sharing UI though.

We cannot change the default path of Realm files without breaking all existing apps that are using the default path. The only solution here, IMO, is for anyone that wants their app to store Realm files in different location, for whatever reason, to specify a different path in their configuration.

**Comment by jpsim** [comment]
Yes, sorry for the mixup, I was thinking of `NSURLIsExcludedFromBackupKey`.

**Comment by wkoszek** [comment]
@jpsim @bdash Ok, so I gave you an example on how I wanted to deal with the issue, but it didn't seem to work for me. What's the proper way to change the directory for Realm files?

**Comment by jpsim** [comment]
> I don't like the new title of this issue. It's doesn't reflect my problem enough :-)

I apologize, I've conflated your issue with a different issue you made me realize we have. I'll open a new issue for that one.

**Comment by wkoszek** [comment]
@jpsim No worries man.

**Comment by jpsim** [comment]
Created #4189 for the other issue.

To answer your other question:

> What's the proper way to change the directory for Realm files?

You can specify the location of Realm files by setting the [`fileURL`](https://realm.io/docs/objc/latest/api/Classes/RLMRealmConfiguration.html#/c:objc(cs)RLMRealmConfiguration(py)fileURL) property of its `RLMRealmConfiguration`:

```objc
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
config.fileURL = [NSURL URLWithString:@"/path/to/file.realm"];
RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:nil];
```

**Comment by wkoszek** [comment]
@jpsim So can you confirm that an inability of doing:

```
<what you did and I've done before>
[RLMRealmConfiguration setDefaultConfiguration:configuration];
```

is a bug too? I'd expect that this default config will kick in each time I do:

```
RLMRealm *realm = [RLMRealm defaultRealm];
```

At least that's what I do in my data model right now.

**Comment by jpsim** [comment]
I don't understand your last comment.

> 4 files of Realm are still created:

Yes, that's expected. No matter the root directory of the realm file, the auxiliary files will always be created, and they will always be located next to the main file.

I had opened an issue a long time ago to allow specifying a custom location for the auxiliary realm files, but that was closed due to not solving any issue we were aware of: realm/realm-core#911

Sounds like this would require the same solution, but for a different problem.

Unless there's a different solution to this that I'm not aware of.

Does that sound right to you @wkoszek?

**Comment by wkoszek** [comment]
From Apple's Review feedback it looks like I need to get rid of all files from the iTunes shared directory, if I want to have this file sharing functionality enabled. Rephrasing: if I open my app in iTunes and look into shared dir, Realm files can't be there.

I'm looking for a way to do it. 

**Note 1** my hope was that by relocating the `.realm` file all other files (`.lock`, `.management`, `.note`) will also be placed in a different file. I think you're admitting there's no way to do it currently?

Can you confirm if I got that right?

**Comment by jpsim** [comment]
> **Note 1** my hope was that by relocating the `.realm` file all other files (`.lock`, `.management`, `.note`) will also be placed in a different file. I think you're admitting there's no way to do it currently?

Yes, that's correct, those files are always created when opening a Realm, unless the Realm is only ever opened with [`RLMRealmConfiguration.readOnly`](https://realm.io/docs/objc/latest/api/Classes/RLMRealmConfiguration.html#/c:objc(cs)RLMRealmConfiguration(py)readOnly) set to `YES`.

Those files are necessary to ensure safe inter-process access to the Realm. Which is why I think the only solution is to allow developers (you) to override the location of the auxiliary files, as to not have them next to the main `.realm` file in order to satisfy Apple's requirements regarding iTunes file sharing.

**Comment by wkoszek** [comment]
That's a bummer. Here's the "spec" how I want it to work:

I pass `/path/to/dir` and I get `realm.default`, `realm.default.lock`, `realm.default.management` and `realm.default.note` created in there.

Trying to think what my workaround can be. Going to try your code snippet:

```
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
config.fileURL = [NSURL URLWithString:@"/path/to/file.realm"];
RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:nil];
```

now that I'm at home

**Comment by jpsim** [comment]
Again, confused by your last comment. As far as I know, the way to expose this would be:

```objc
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
config.fileURL = [NSURL URLWithString:@"/path/to/realm/file.realm"];
config.supportingFilesRootURL = [NSURL URLWithString:@"/dir/for/aux/files/"];
RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:nil];
```

So that your `/path/to/realm` directory would be "pristine", just have the realm file(s), so that iTunes/Apple would be happy, while making sure the important auxiliary files are still available to Realm.

**Comment by wkoszek** [comment]
Not sure what you're confused about. I'm looking for a way to get rid of these 4 files from the iTunes shared dir. That's all I want :-)

**Comment by jpsim** [comment]
Like I said earlier, those files are always created when opening a Realm, unless the Realm is only ever opened in read-only mode (i.e. `RLMRealmConfiguration.readOnly` set to `YES`).

They're also always created in the same directory as the main realm file, but it would be possible to support specifying a custom location for these files, as we've already considered in realm/realm-core#911, but subsequently closed.

**Comment by wkoszek** [comment]
Ok. I think your confusion comes from distinguishing `.realm` files from `.lock` etc. files. I don't distinguish that. I don't care -- to me these 4 files go together as "Realm database". I don't know which of these Apple doesn't like, so I just want all 4 of them to disappear from a shared folder.

Now I gave you the snippet which I showed. It didn't work for me.

So now I'm using yours:

```
- (RLMRealm *) privDataStore {
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.fileURL = [NSURL fileURLWithPath:@"/tmp/s.realm"];
    [RLMRealmConfiguration setDefaultConfiguration:config]; // just in case
    return [RLMRealm realmWithConfiguration:config error:nil];
}
```

(I've changed the `URLWithString:@"/path/to/file.realm"` to `fileURLWithPath`).

It doesn't seem to work. The files are sill visible in iTunes as if `fileURL` was getting ignored.

Reading Realm source code now...

**Comment by jpsim** [comment]
If you've opened the Realm prior to setting this file URL in the configuration, then the files from the previous access will still exist.

**Comment by wkoszek** [comment]
Bingo. That's the issue. I have Realm migration handling code run early in the app startup, and it was initialising the Realm files 1st time. Now I've fixed it, and it seems like our code works!

I have:

```
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
NSString *appSupportDirPath = [paths firstObject];
NSString *realmPath = [appSupportDirPath stringByAppendingPathComponent:@"default.realm"];
config.fileURL = [NSURL fileURLWithPath:realmPath];
[RLMRealmConfiguration setDefaultConfiguration:config];
```

![image](https://cloud.githubusercontent.com/assets/483344/19142395/0bc5c328-8b52-11e6-97cc-c943d0ed4ec4.png)

Realm files are gone. The BZip'ed JSON files are my data files.

Should we put a note in Realm guide on default location of the database being in conflict with `UIFileSharingEnabled` ?

**Comment by jpsim** [comment]
Can you instead just hide the file(s) you don't want to display in iTunes using [NSURLIsHiddenKey](https://developer.apple.com/reference/foundation/nsurlishiddenkey)?

**Comment by jpsim** [comment]
Unfortunately, iTunes appears to ignore `NSURLIsHiddenKey`, and setting a file as hidden using `chflags("path", UF_HIDDEN)` also doesn't have any effect.

**Comment by wkoszek** [comment]
@jpsim Should we document somehow that `UIFileSharingEnabled` collides with default Realm settings ?

**Comment by jpsim** [comment]
Since that's true of anything stored in Documents, and not unique to Realm, I don't think it warrants a mention in the docs. This is the first time anyone's ever brought this to our attention, so I doubt this is a common occurence.

**Comment by wkoszek** [comment]
Ok. Maybe the `UIFileSharingEnabled` isn't as popular as I expected.

**Comment by vibze** [comment]
Well, this thread has certainly saved me some precious time. Not a common occurrence, but it surely does clash with built-in functionality of `UIFileSharingEnabled`, so I suppose a paragraph in docs wouldn't hurt either.

**Comment by bupojung** [comment]
I have the same issue. And i do this:
`        var config = Realm.Configuration(
            schemaVersion: 5,
            migrationBlock: { migration, oldSchemaVersion in
                
                if oldSchemaVersion <5 {
                    // do something
                }
            }
        )
        if let dataDir = Path.myDataDir() {
            if Path.createDirIfNeed(at: dataDir) {
                config.fileURL = dataDir
                    .appendingPathComponent("\(UserInfo().userId).realm")
                Realm.Configuration.defaultConfiguration = config
            }
        }`

the four Realm files is still appear in iTunes

**Comment by duncangroenewald** [comment]
By default Realm should not be creating the database in the Documents directory, and if it does and needs to be backed up then use a subfolder called 'realm' in the Documents directory.  The contents of which would not be visible to the user unless they copied the folder from iTunes. The correct default folder is "Library/Application Support" - well that is what Apple's Core Data defaults to.

**Comment by sergstav** [comment]
I'm using RealmSwift, I'm trying to change default place for saving/creating realm files from Documents to Library/Application Support, works fine, but Realm continue create files in Documents directory too, and I have to remove it manually, is this issue, or I'm doing something wrong?

```
var realmConfig = Realm.Configuration.defaultConfiguration
        let paths = NSSearchPathForDirectoriesInDomains(.applicationSupportDirectory,
                                                        .userDomainMask,
                                                        true)
        let applicationSupportDirectoryPath = paths.first
        if let applicationSupportDirectoryPath = applicationSupportDirectoryPath {
            let  realmPath = applicationSupportDirectoryPath.appending("/default.realm")
            realmConfig.fileURL = URL(fileURLWithPath: realmPath)
            Realm.Configuration.defaultConfiguration = realmConfig
        }
```

**Comment by vishaldroisys** [comment]
i am getting crash like 'A Subscription can only be created in a Query-based Realm.'

Thanks in advanced.

**Comment by darkForestCat** [comment]
This is a really big problem.I have trashed a lot of time because of this thing and the problem is still not resolved.I think it would be appropriate to do something in the next updates...

**Comment by invisible66** [comment]
@sergstav did you find any solution? I am getting same error..

**Comment by sergstav** [comment]
@invisible66 yes, I have a solution that allows me to pass review.
I use this code
![Screenshot 2019-12-04 at 14 32 49](https://user-images.githubusercontent.com/3393265/70143193-a0b63f00-16a3-11ea-8306-d430a3294579.png)

**Comment by invisible66** [comment]
@sergstav Thank you so much. You saved my day :)

**Comment by mohanrajnkl** [comment]
@sergstav  i have used your code in ios14 version app get crash, the ream files [default.realm, default.realm.lock, default.realm.management, default.realm.note] if i delete means realm database not working getting crash

**Comment by mohanrajnkl** [comment]
finally i got the solution
 Please update xcode 12.5

 Please use pod 'RealmSwift', '~> 10.5.0'

 This 10.5 version only support unrealm concept

 If enable UIFileSharing Enabled the files opening even the realm  auxiliary files downloading
