### ISSUE TITLE
Allow updating of primary keys

### ISSUE THREAD

**Issue by TR4Android** [realm/realm-cocoa#4194]
#### Goals

Currently there is no way to update the primary key of an object after it has been created. I have this requirement though, as the workflow of my app is similiar to the following:

1. User creates a new object in the database while offline
2. This object gets a temporary (negative) id, as the app does not yet know what final id the server will assign to the object
3. User/app syncs the database when online again
4. The server receives the new object and assigns a final id to it
5. The app receives the final id from the server and updates the objects id to the final one (this is currently not directly supported by Realm)

#### Expected Results

I personally see 2 options going forward with this:
* **Allow changing primary key fields:** this would basically allow the following code to update an objects primary key:

    ```swift
let object = realm.objects(TestObject.self).filter("id = \(oldId)").first
object!.id = newId
```

* **Add dedicated method for changing primary keys:** this probably makes more sense if you want to align it more with the Realm API in other languages:

    ```swift
realm.updatePrimaryKey(TestObject.self, from: oldId, to: newId)
```

#### Actual Results

Currently only a rather ugly and not very performant workaround does the job, basically bypassing the check by making an in-memory copy of the object. I'm really looking forward to seeing this fixed in a future update (though I absolutely acknowledge that you have lots of other issues to attend to 😉)

#### Version of Realm and Tooling
Realm version: all
Xcode version: all
iOS/OSX version: all
Dependency manager + version: all

#### References
realm-java: https://github.com/realm/realm-java/issues/3589

**Comment by bmunkholm** [comment]
This is more principal and the discussion is happening here: https://github.com/realm/realm-java/issues/3589

**Comment by jpsim** [comment]
Hi @TR4Android, as the conversation in realm/realm-java#3589 has become more in-depth than this one, I'll close this as a duplicate.

If others land on this, immutable primary keys in Realm is very much a core design decision, as PKs represent "identity" in Realm, and semantically identity cannot mutate.

If you're using primary keys in a way that doesn't represent identity in your object graph, then this is incompatible with Realm's concept.

For example, two objects with the same identity always merge to the same object, whether it's being synchronized with the [Realm Mobile Platform](https://realm.io/products/realm-mobile-platform/), or it's two items being written to from different processes or threads.
