### ISSUE TITLE
Linking Object attributes don't exist when not in realm

### ISSUE THREAD

**Issue by asjesset** [realm/realm-cocoa#4195]
Upgraded to Realm 2.0.1 from 1.X and been having some crashes when adding new objects.

It looks like an object with linking properties crashes if i try to access its linking objects before it's added to realm. I think in 1.X the behavior was to return an empty list.

Did this behavior change? What's expected here:?

**Comment by asjesset** [comment]
I verified the behavior changed from 1.0.2 to 2.0.2.

Accessing an unmanaged RLMObject's linking object properties in 1.0.2 results in an empty RLMResults, but in 2.0.2 you get this exception:
```
#0	0x0000000103b6e3ad in -[RLMFastEnumerator countByEnumeratingWithState:count:] at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/RLMCollection.mm:95
#1	0x0000000103b6eeae in RLMDescriptionWithMaxDepth(NSString*, id<RLMCollection>, unsigned long) at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/RLMCollection.mm:190
#2	0x0000000104ad43d9 in _NSDescriptionWithLocaleFunc ()

```

As a workaround, using "count" appears to still work (returns 0 if not in a realm already). I will be wrapping all my iterators in this unless this is fixed...

**Comment by asjesset** [comment]
The EXC_BAD_ACCESS appears to occurs in RLMCollection.m:95:
```
- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state
                                    count:(NSUInteger)len {
    [_realm verifyThread];
    if (!_tableView.is_attached() && !_collection) {
        @throw RLMException(@"Collection is no longer valid");
    }
    // The fast enumeration buffer size is currently a hardcoded number in the
    // compiler so this can't actually happen, but just in case it changes in
    // the future...
    if (len > RLMEnumerationBufferSize) {
        len = RLMEnumerationBufferSize;
    }

    NSUInteger batchCount = 0, count = state->extra[1];

    Class accessorClass = _info->rlmObjectSchema.accessorClass; //EXC_BAD_ACCESS here
```

**Comment by bdash** [comment]
Thanks for the detailed bug report. I was able to reproduce this by adding a new test case in Realm:

```swift
PersonObject *don = [[PersonObject alloc] initWithValue:@[ @"Don", @60 ]];
XCTAssertEqualObjects(asArray(don.parents), (@[ ]));
for (PersonObject *parent in don.parents) {
    (void)parent;
    XCTFail();
}
```

**Comment by markst** [comment]
Hey I still appear to be having this issue. Using version `2.4.4`.

```swift
class User: Object, Resource {
    
    dynamic var id: String? = nil
    dynamic var email: String? = nil
    dynamic var firstName: String? = nil
    dynamic var lastName: String? = nil
    dynamic var phone: String? = nil
    dynamic var company: String? = nil
    
    var organisations = List<Organisation>()
    
    let sessions = LinkingObjects(fromType: Session.self, property: "user")
```

My linking objects is empty outputting my `sessions` to output log:
```swift
override var description: String {
    print("self.sessions: \(self.sessions)")
```

Until I add all the 'sessions' which should fulfil the linkage to a Realm, then the debug output works fine.

**Comment by markst** [comment]
On further investigation it appears `LinkingObjects` doesn't return any results for unmanaged objects, can I get confirmation?

**Comment by bdash** [comment]
Correct, `LinkingObjects` always returns an empty collection for unmanaged objects.

In the future, please file a new issue rather than tacking your question onto an issue that's been closed for many months.

**Comment by markst** [comment]
@bdash so be it. I thought you'd prefer to keep issues to a minimum!
