### ISSUE TITLE
Can RealmCollection.filter do better with Optional<T>?

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#4197]
In Swift 3 we changed RealmCollection.filter to take variadic arguments of type `Any`. This allows passing `Optional<T>`s as arguments, but they make it down to Objective-C code that has no knowledge of that type. Can our Swift wrapper unwrap the optionals, replacing `none` with `NSNull`, and `some(x)` with `x`?

**Comment by austinzheng** [comment]
#5265 has been merged into `master-3.0`.
