### ISSUE TITLE
Make Swift SDK use a struct for sync configuration

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#4198]
Right now, the Swift SDK uses a `(SyncUser, URL)` tuple to define a configuration for sync. I propose this be changed to a `SyncConfiguration` struct, much like how Objective-C works. Doing so will give us room to add more configuration options in the future without forcing breaking changes or creating awkwardly large tuple types.

We made this design decision quite a few months ago, before the overall shape of the binding APIs was clear, and never revisited the decision. We should do so before leaving beta.

@jpsim @bdash @tgoyne

**Comment by jpsim** [comment]
I agree this is something that needs to happen asap, before the platform drops its beta status.
