### ISSUE TITLE
Is there a way to compare Realm Objects with non realm objects - Obj-C?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [realm/realm-cocoa#4200]
Is there a way to compare Realm Objects with non realm objects - Obj-C?

**Comment by jhanzo** [comment]
I think this kind of question should be in stackoverflow as guidelines issue said : 
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>

Moreover, in your stackoverflow issue try to add more detail about your goals, your description is not detailed enough 😉

**Comment by Sebacho-Barajas** [comment]
already found a solution!
