### ISSUE TITLE
Documentation Showing Outdated Version (2.0.1)

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-cocoa#4203]
The Xcode log shows that RealmSwift version `2.0.2` is available, but the docs show `2.0.1` is the latest: https://realm.io/docs/swift/latest/

![realm-latest](https://cloud.githubusercontent.com/assets/2513753/19248237/ad193a18-8ee3-11e6-9323-1046061c2ac7.png)

Please update the documentation to match. :)

P.S. I love Realm so so so much.

**Comment by jpsim** [comment]
Thanks for reporting this @cliftonlabrum, we had an issue with our website since Thursday last week where some changes would occasionally get reverted, this has since been fixed as of 2 minutes ago.

**Comment by cliftonlabrum** [comment]
Fastest fix ever! 👍
