### ISSUE TITLE
Warnings when building with static Realm.framework

### ISSUE THREAD

**Issue by zpapp** [realm/realm-cocoa#4205]
## Goals

I'd like to build my iOS app with the static Objective-C Realm framework.

## Expected Results

Build succeeds without warnings.

## Actual Results

I get the following warnings:

```
while processing /Users/zpapp/tmp.d/StaticRealmWarnings/StaticRealmWarnings/Realm.framework/Realm(RLMAuthResponseModel.o):
warning: /Users/realm/workspace/objc_ios/tightdb_objc/build/DerivedData/ModuleCache/1SLMU8SXHKS7C/Foundation-3JWVXIADENRHH.pcm: No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
while processing /Users/zpapp/tmp.d/StaticRealmWarnings/StaticRealmWarnings/Realm.framework/Realm(RLMAuthResponseModel.o):
warning: /Users/realm/workspace/objc_ios/tightdb_objc/build/DerivedData/ModuleCache/1SLMU8SXHKS7C/ObjectiveC-26VMO97172RKZ.pcm: No such file or directory
while processing /Users/zpapp/tmp.d/StaticRealmWarnings/StaticRealmWarnings/Realm.framework/Realm(RLMAuthResponseModel.o):
warning: /Users/realm/workspace/objc_ios/tightdb_objc/build/DerivedData/ModuleCache/JWC8IYTTLHHV/Foundation-3JWVXIADENRHH.pcm: No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
while processing /Users/zpapp/tmp.d/StaticRealmWarnings/StaticRealmWarnings/Realm.framework/Realm(RLMAuthResponseModel.o):
warning: /Users/realm/workspace/objc_ios/tightdb_objc/build/DerivedData/ModuleCache/JWC8IYTTLHHV/ObjectiveC-26VMO97172RKZ.pcm: No such file or directory
```

Note: Issue #2642 is similar to this. That issue was closed because the problem went away. That was true at the time; I am pretty sure that for example Realm version 1.0.1 did not have this problem.

## Steps to Reproduce

1. Create a new iOS project with Xcode 8. Select Objective-C for language.

2. Add the static Realm framework (Side note: your documentation says you need to add libc++.tbd; I had to add libz.tbd as well; that's a different issue though)

3. Add some basic Realm code to AppDelegate; I used the AppDelegate from the "Simple" example.

4. Archive the project.

You need to "Archive" as opposed to just "Run" the project because the default build settings for Debug builds don't produce the warnings. The warnings are produced when the dSYM files are created, i.e. you need the Debug Information Format build setting to be "DWARF with dSYM" as opposed to just "DWARF".

## Code Sample

I can provide a sample project if needed. I was going to upload it to Github but apparently the Realm framework is too big for that...

## Version of Realm and Tooling

Realm version: Objective-C 2.0.2

Xcode version: 8.0 (8A218a)

iOS/OSX version: 8.0 and up

Dependency manager + version: N/A

**Comment by jpsim** [comment]
I've just updated the installation instructions to reflect that it's necessary to link against `libz.tbd` when linking the static framework. Thanks for reporting that!

Still looking into the main issue of the linker warnings.

**Comment by jpsim** [comment]
Haven't found much to go on to resolve this. I don't know why this is just happening with that one object file (`RLMAuthResponseModel.o`).

**Comment by austinzheng** [comment]
The referenced PR should fix this issue. Please feel free to re-open it (or make a new one) if it's not fixed by the next release.
