### ISSUE TITLE
Realm + NSClassFromString DOUBT

### ISSUE THREAD

**Issue by Jabelriera** [realm/realm-cocoa#4206]
Hi everyone and thank you for be reading this. 

I am new with Realm and I am stucked with a function that I can't figure out how to build. My intention is to have one function called `func delete(className:String, id:Int){` that should be able to delete any object of any Realm class by its ID. The inner code of the function is:

```
func delete(objectNameV:String, id:Int){

     let theClass = NSClassFromString(objectNameV)

     // Get the default Realm
     let realm = try! Realm()
     let queryResult = realm.objects(theClass as! Object.Type).filter("id = \(id)")
     try! realm.write {
         realm.delete(queryResult)
     }
}
```

But the fact is that `let theClass = NSClassFromString(objectNameV)` it's allways NIL. 

Any help is appreciated, **i just need a function that given a realm classname and the id from an object of that class can delete it**!

Realm version: 2.0.1
Xcode version: 8

**Comment by jpsim** [comment]
Why do you need this? If you want to delete an object in your current schema, you should have the class type to be able to pass to it:

```swift
func delete(type: Object.Type, id: Int) {
     // Get the default Realm
     let realm = try! Realm()
     let queryResult = realm.objects(type).filter("id = %@", id)
     try! realm.write {
         realm.delete(queryResult)
     }
}
```

If you don't have the model class available, is it because you're in a migration and the class may no longer exist? In that case, you should be using [`Migration.deleteData(forType:)`](https://realm.io/docs/swift/latest/api/Classes/Migration.html#/s:FC10RealmSwift9Migration10deleteDataFT7forTypeSS_Sb):

```swift
// in migration block:
migration.deleteData(forType: "RemovedClassName")
```

If you want to expose functionality in your app where you don't know which model should be deleted, you can use Realm's dynamic API to do this:

```swift
func delete(typeName: String, id: Int) {
     // Get the default Realm
     let realm = try! Realm()
     let queryResult = realm.dynamicObjects(typeName).filter("id = %@", id)
     try! realm.write {
         realm.delete(queryResult)
     }
}
```

**Comment by Jabelriera** [comment]
Well in fact the reason why I dont have the class type because to avoid making so many querys to Realm there is some data that is temporaly collected in the controller unless there are changes in the Realm objects (Inserts, Updates, Deletes). I wanted to make a generic function so I do not need to have one per each Realm Class but then I got stucked with that problem.

I am not really sure if I have exposed the problem and context so that you can figure out it all or if what I am doing it's just not necesary and I can go ahed making as many querys as the user requests throw the views but given my experience and my 2-days try on realm that's the best i god. 

Thank you very much for your answer, your examples and your time! I will appreciate any other help :)

**Comment by jpsim** [comment]
Alright, I hope my first example suits your needs then! Let us know if there's anything more we can do to help you.
