### ISSUE TITLE
About using LinkingObjects for two property

### ISSUE THREAD

**Issue by mobilestar0223** [realm/realm-cocoa#4211]
Hello.
I don't know how to use `LinkingObject` in below situation.
```
class Message: Object{
       ...
      dynamic fromUser : User?
      dynamic toUser : User?
}

class User: Object {
      ....
      let messages = List<Message>()
}
```
`messages` should has whole sent and received message.
How can I use LinkingObject?
Thanks.

**Comment by stel** [comment]
@mobilestar0223 I've answered your question on StackOverflow: http://stackoverflow.com/a/39994123/417267, let me know if you need any other help and feel free to reopen this issue.
