### ISSUE TITLE
Invalid property name', reason for save One to Many concept

### ISSUE THREAD

**Issue by Piraban** [realm/realm-cocoa#4212]
I have two entities called "MathSolutions" , "Folder". One folder can have multiple questions. One to Many relationships.

MathSolutions Entity

 ```
class MathSolutions: Object {

    dynamic var question = ""
    dynamic var steps = ""
    dynamic var createdDate = NSDate()
    let solutions = List<Folders>()


    class func JSONInboundMappingDictionary() -> [String:String] {
        return [
            //"id": "id",
            "question"  : "question",
            "steps"     :"steps",
            "createdDate" : "createdDate",
            "solutions"     : "solutions"
        ]
    }
}
```
Folder class

  ```
class Folders: Object {
    dynamic var folderName: String = ""
 }
```

Another processing part

  ```
 let mathSolution = MathSolutions(value: ["question": answers.question,"steps":realmcrud.createJOSNString(answers),"createdDate":NSDate()] )
    realmcrud.saveMySolution(mathSolution,folder: folder!)
```

```
//MARK:-Save Solutions
func saveMySolution(mathSolutions:MathSolutions,folder: Folders){
    let realm = try! Realm()
    try! realm.write{
        mathSolutions.solutions.append(folder)
        realm.add(mathSolutions)
    }
}
```
Created folder is ok working fine. problem is when I save MathSolutions I got below error.

I always get below error

> 2016-10-12 15:39:36.234 JIT[92648:1964826] *** Terminating app due to uncaught exception 'Invalid property name', reason: 'Property 'name' not found in object of type 'Folders''

Please any idea? please suggest

**Comment by stel** [comment]
@Piraban I've noticed your question on StackOverflow: http://stackoverflow.com/questions/39996577/save-object-using-realm-inverse-relationships-swift and requested additional info there, so will close this issue.

**Comment by Piraban** [comment]
Even though delete the app from emulator and installed also same error message. I update in stackoverflow. 

Terminating app due to uncaught exception 'Invalid property name', reason: 'Property 'name' not found in object of type 'Folders''
