### ISSUE TITLE
Realm Object With Primary Key or without primary key, better performance.

### ISSUE THREAD

**Issue by Piraban** [realm/realm-cocoa#4213]
I have two classes Folders and MathSolutions. One to Many relationship. Please suggest me which method is good to develop whether having the id defined as a primary key, keep the refence in the another class. OR apply object mapping ?

**Comment by jpsim** [comment]
Your question is quite vague. Is this the type of schema you're looking for?

```swift
class Folder: Object {
  let solutions = List<MathSolution>()
}
class MathSolution: Object {
  dynamic var content = "<insert content of solution here>"
}
```

This will allow Folders to contain many MathSolutions.

**Comment by jpsim** [comment]
Hoping that my last comment helped you @Piraban. Feel free to reopen this issue if you have any further comments or questions you'd like us to address.
