### ISSUE TITLE
Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'

### ISSUE THREAD

**Issue by wirakoon78** [realm/realm-cocoa#4215]
Hi thanks for great library. I use Swift3.0 and whenever I ran this code snippet : 

``` swift
 internal func storeObject(object: MTImage) {
        let realm = try! Realm()
        do {
            try realm.write({
                realm.add(object, update: false)
                print(" Photo stored.")
            })
        }catch let error {
            print(error)
        }
    }
```

I always get an error: 
Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'

Could you help me find an issue ? 
Thanks in advance

**Comment by stel** [comment]
You get this assertion failure most likely because you're trying to modify `object` somewhere in other place in your code without write transaction, as stated in [Docs](https://realm.io/docs/swift/latest/#writes):
> All changes to an object (addition, modification and deletion) must be done within a write transaction.

Please check if you modify any `Object` instances without write transaction.

**Comment by stel** [comment]
@wirakoon78 were you able to identify the problem? Do you need any other help with this?

**Comment by wirakoon78** [comment]
No, I solved the issue myself. Thank you
On 11/9/2016 4:48:10 PM, Dmitry Obukhov <notifications@github.com> wrote:
@wirakoon78 [https://github.com/wirakoon78] were you able to identify the problem? Do you need any other help with this?

**Comment by stel** [comment]
Awesome!

**Comment by kishan89** [comment]
how'd you solve it?

**Comment by istx25** [comment]
Hi @kishan89. Would you be able to file another issue with your own code samples? Thanks.

**Comment by kishan89** [comment]
My issue is only remotely related. I have a server using digital ocean, and I am trying to read and write from/to my realm on that server rather than a default.realm file on my local machine.

**Comment by ikyh** [comment]
@axiom88-guru Will you please tell how you solved the error

**Comment by axiom88-guru** [comment]
In Appdelegate.swift, add this code below
`let uiRealm = try! Realm()`

In any viewcontrollers or any classes , work with this uiRealm instance. 
```
func storeObject(object: MTImage) {
        do {
            try uiRealm.write({
                uiRealm.add(object, update: false)
                print(" Photo stored.")
            })
        }catch let error {
            print(error)
        }
    }
}
```
It wouldn't give any bugs or exceptions
I hope you'd solve it soon.

**Comment by axiom88-guru** [comment]
Here is a link to sample project :
https://github.com/axiom88-guru/moodTracker/tree/master/MoodTracker
