### ISSUE TITLE
Realm Model Subclass

### ISSUE THREAD

**Issue by pjebs** [realm/realm-cocoa#4220]
[NB: I'm using Realm 0.102.1]

For a realm model, when I create a custom method, I don't seem to be able to access a property using it's backing instance variable:
```
@interface Event : RLMObject
    @property (strong, nonatomic) NSString *preferences;
- (NSDictionary * _Nonnull)preferencesToJSON;
@end

@implementation RealmEvent

- (NSDictionary * _Nonnull)preferencesToJSON
{
    NSData *data = [_preferences dataUsingEncoding:NSUTF8StringEncoding];
    if (data == nil) {
        return @{};
    }
    NSError *error = nil;
    id t = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
    if (error != nil) {
        NSLog(@"preferencesToJSON: %@", error.localizedDescription);
    }
    if (t == nil) {
        return @{};
    }
    return t;
}

@end
```

**_preferences** is nil. How can I access it from my method?

**Comment by kishikawakatsumi** [comment]
@pjebs Use `self. preferences` instead `_preferences`. Realm creates subclass dynamically and swizzle getter/setter for lazy loading and zero copy. Realm objects don't store any values in memory. Direct access instance variables always returns `nil`.

**Comment by pjebs** [comment]
Any feedback on this: https://github.com/realm/realm-cocoa/issues/3296

**Comment by stel** [comment]
@pjebs do you need any other help with this issue? I'm closing it for now, please feel free to reopen it or create a new issue if you have any other questions.
