### ISSUE TITLE
RealmSwift pod install issues?

### ISSUE THREAD

**Issue by yoshyosh** [realm/realm-cocoa#4224]
Saw this today

https://www.reddit.com/r/iOSProgramming/comments/577o9b/is_realmswift_working_for_you_guys_in_xcode/

**Comment by jpsim** [comment]
I replied yesterday morning: https://www.reddit.com/r/iOSProgramming/comments/577o9b/is_realmswift_working_for_you_guys_in_xcode/d8qjl82
