### ISSUE TITLE
Collection notification notified only once.

### ISSUE THREAD

**Issue by superandrew** [realm/realm-cocoa#4226]
## Goals

Refresh the UI when new data are inserted
## Expected Results

Auto updating results should fire a notification with changes
## Actual Results

I have two collections, alerts and standard measures. The same code is used to add a notification block. The alerts fire the notification, the standardMeasures don't
## Steps to Reproduce

I'm afraid I can't reproduce it, but within my code it is consistent
## Code Sample

instantiation:

``` swift
var standardMeasures:Results<StandardMeasure>? = nil
var alerts:Results<AlertStatus>? = nil
var measuresToken:NotificationToken? = nil
var alertsToken:NotificationToken? = nil
```

``` swift
alerts = node?.alerts.sorted(byProperty: "timestamp")
standardMeasures = node?.standardMeasures.sorted(byProperty: "timestamp")


alertsToken = alerts?.addNotificationBlock({ (changes) in
    if !self.isChangingValues{
        self.updateAlertsUI()
    }
})

measuresToken = standardMeasures?.addNotificationBlock({ (changes) in
    if !self.isChangingValues{
        self.updateMeasuresUI()
    }
})
```

Only `alertsToken`'s block is fired every time a data is written. Standardmeasures' block is fired only once. Weird. Also, when the alerts block is fired, I can see node.standardMeasures.count has increased.

```
po node?.standardMeasures.count
▿ Optional<Int>
  - some : 405
----
po node?.standardMeasures.count
▿ Optional<Int>
  - some : 406
```
## Version of Realm and Tooling

RealmSwift 2.0.2

Xcode version: 8

iOS/OSX version: 10.12

Dependency manager + version: CocoaPods

**Comment by jpsim** [comment]
If the number of items in a `Results` being observed changes, its notification block should certainly be fired.

Keep in mind that notifications may be coalesced (grouped), including the initial notification. For example, by the time the `standardMeasures` notification block fires its initial notification, it may have already processed the first change (count from 405 to 406).

I suggest your read our documentation on [Collection Notifications](https://realm.io/docs/swift/latest/#collection-notifications) as well as the docs for [`Results.addNotificationBlock(_:)`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results20addNotificationBlockFFGOS_21RealmCollectionChangeGS0_x__T_CSo20RLMNotificationToken).

**Comment by jpsim** [comment]
@superandrew do you still have questions regarding this?

**Comment by superandrew** [comment]
I think everything has been cleared, thank you.






On Wed, Nov 9, 2016 at 1:10 AM +0100, "JP Simard" <notifications@github.com> wrote:












@superandrew do you still have questions regarding this?
