### ISSUE TITLE
Realm file size inflates when using gcd to create new objects

### ISSUE THREAD

**Issue by kevincador** [realm/realm-cocoa#4229]
## Goals

Would like to create new objects on a background thread with gcd
## Expected Results

Realm file size should not inflate
## Actual Results

Realm file size becomes way bigger when using gcd
## Steps to Reproduce

See code sample
## Code Sample

Tested this with the Backlink sample (Person, Dog).

First version, not using Dispatch.

``` swift
notificationToken = try! Realm().addNotificationBlock { note, realm in
   let allDogs = realm.objects(Dog.self)

   let att = try! FileManager.default.attributesOfItem(atPath: Realm.Configuration.defaultConfiguration.fileURL!.path)
   print("Realm file size \(allDogs.count) dogs : \(att[FileAttributeKey.size])")
}

for _ in 1...10000 {
   let realm = try! Realm()
   try! realm.write {
      realm.create(Person.self, value: ["John", [["Fido", 1]]])
   }
}
```

Gives something like:
`Realm file size 10000 dogs : Optional(589824)`
-> 0,589824 Mégabytes

``` swift
notificationToken = try! Realm().addNotificationBlock { note, realm in
   let allDogs = realm.objects(Dog.self)

   let att = try! FileManager.default.attributesOfItem(atPath: Realm.Configuration.defaultConfiguration.fileURL!.path)
   print("Realm file size \(allDogs.count) dogs : \(att[FileAttributeKey.size])")
}

for _ in 1...10000 {
   DispatchQueue.global().async {
      let realm = try! Realm()
      try! realm.write {
         realm.create(Person.self, value: ["John", [["Fido", 1]]])
      }
   }
}
```

Gives something like:
`Realm file size 10000 dogs : Optional(4718592)`
-> 4,718592 Mégabytes
## Version of Realm and Tooling

Realm version: 2.0.2

Xcode version: 8.0

iOS version: 10

Dependency manager + version: CocoaPods 1.1.0.rc.2

**Comment by kevincador** [comment]
It gets worst...

If I delete all objects with 

```swift
let realm = try! Realm()
try! realm.write {
   realm.deleteAll()
}
```

And run the sample (with the above Dispatch code) 5 times, I get a 23 Megabytes database with only 10000 dogs consisting of only 2-3 properties :(

The space is never recycled.

**Comment by bdash** [comment]
Take a look at the last paragraph in the section on [File size & tracking of intermediate versions](https://realm.io/docs/swift/latest/#file-size--tracking-of-intermediate-versions) in Realm's documentation.

**Comment by kevincador** [comment]
Forgot to mention that I tried to wrap the code in the Dispatch in an autoreleasepool. It didn't help. In fact, the Realm file size took even more space.
Also tried to invalidate the realm that's used for object creation. No effect either.

Here's the code used:
```swift
for _ in 1...10000 {
    DispatchQueue.global().async {
        autoreleasepool {
            let realm = try! Realm()
            try! realm.write {
               realm.create(Person.self, value: ["John", [["Fido", 1]]])
            }
            realm.invalidate()
       }
   }
}
```

**Comment by bdash** [comment]
@kevincador, would you mind attaching the complete Xcode project you're testing with so we can attempt to reproduce with the exact same code that you're using?

**Comment by kevincador** [comment]
@bdash I forked and created a branch called gcd-test. The only file that should require your attention is the AppDelegate : https://github.com/kevincador/realm-cocoa/blob/gcd-test/examples/ios/swift-2.2/Backlink/AppDelegate.swift

You can run the sample Backlink from the branch. You should have the same results as reported above.

**Comment by jpsim** [comment]
Hi @kevincador, looking at your sample code above and the modified version of the example app, you're effectively creating 10,000 concurrent versions of the database, each mutating the db. To preserve isolation between transactions, Realm writes this data in separate locations on disk.

Imagine if Realm didn't do that, you'd lose the isolation between transactions.

Realm preserves each intermediate versions of its state from the oldest still-in-use version (your main thread in this case) and the newest version (the last GCD transaction that fires). Meaning that these 10k copy-on-write versions of the database can't be discarded to reclaim that space.

This is exactly the type of problematic scenario that's documented in the section on [File size & tracking of intermediate versions](https://realm.io/docs/swift/latest/#file-size--tracking-of-intermediate-versions) in Realm's documentation that @bdash linked to earlier.

If you weren't accessing the Realm on the main thread, those intermediate states could be discarded, preventing the Realm file from growing so much.

**Comment by kevincador** [comment]
Hi @jpsim,
I understand this and it would not be a problem if the file size didn't increase constantly. I mean, once the operation is done, there is no need to keep the intermediate versions in the Realm file.
Also, I thought the space would be reused at some point. It doesn't seem to be the case even with an autoreleasepool wrap or after calling invalidate after each transaction.

I think we are using a pretty common pattern:
- read on the main thread to refresh the UI
- write on a background thread after a network activity

The problem is, right now, we have like 30% of our daily user session that crashes with mmap() errors because the database is 1.5 Gigabytes instead of 6 Megabytes.

We tried to work around this by compacting the Realm file (modifying the source to have access to `compact()`) each time we launch the app but since we have other processes reading (like widget, background fetch or Apple Watch app) the compact does not always work.

When the compact doesn't work, we only found one solution. We delete all Realm files and trigger a full sync. Not the best in terms of user experience but there when there is no way to recover from a 1-3 gigabytes database (depending on the device), it is the best we could do.

**Comment by kevincador** [comment]
Hi @jpsim, I would love to have your feedback about my last comment. Don't hesitate to ask me if you need anything.

I don't know if this makes sense but I think the database size grows a lot when we perform background fetch (iOS background fetch). It would make sense since I assume all the jobs are done in background threads. It would mean that no matter the use case, if you touch at the database in a background refresh job it will eventually crash at launch with an impossible mmap since the background refresh is triggered by iOS several times a day.

**Comment by kevincador** [comment]
Hi @jpsim,

You could also delete the intermediate versions when the app starts up (or when the Realm file is first  accessed). I don't mind calling something else than compact() at launch if it can help reduce the size of the database. If it is a fast and safe operation, I don't mind calling this new method after each write transaction.

**Comment by diegomontoya** [comment]
@kevincador There is an interim solution that fixes your solution but there is a catch. 

Do all your db write transactions in a single serialized dispatch queue in swift. Now you have at most 1 version of db in write transactions.

The catch is that of course, you will block other realm writes and you have just manually "removed" the "concurrency" feature of realm. On the other hand, you only "block" other background realm writes, so UI is not effected. There is a fundamental difference between concurrency and speed. Concurrency is not speed. So with this method, you only sacrifice concurrency, but not speed.  Parallel writes in realm, or any other concurrent systems,  are not free and are actually very costly.

**Comment by bmunkholm** [comment]
@dieguoyomontoya Just to clarify: Parallel writes can not happen in Realm. Only one write transaction is possible at a time (making it impossible for you to create conflicts).

**Comment by kevincador** [comment]
Hi @diegomontoya, @bmunkholm,

I've done some refactoring (some heavier than expected) and we now have this configuration:
- Realm read from main thread -> ok
- Realm write from the app (local processing) -> all go through one `OperationQueue` which is backed by a serial `underlyingQueue`
- all other writes (sync, user action,...) -> all go through another `OperationQueue` which is backed by the same serial `underlyingQueue`

I saw some inprovement (🎉) meaning the Realm file size seems to not be as crasy as it was before after 3/4 syncs and 3/4 background fetch. But it is still increasing which is inevitable.

One thing I would like to double check with you guys is that the `Thread` on which the transactions occurs may be different (gcd still creates different threads in the queue even if it is a serial queue). I saw that the thread may be different especially if I go into background and come back to the app. Will this be a problem after running the app for a while? I assume the more the underlying Thread changes, the more we'll see the Realm file size increase. Correct?

**Comment by bdash** [comment]
> One thing I would like to double check with you guys is that the Thread on which the transactions occurs may be different (gcd still creates different threads in the queue even if it is a serial queue). I saw that the thread may be different especially if I go into background and come back to the app. Will this be a problem after running the app for a while? I assume the more the underlying Thread changes, the more we'll see the Realm file size increase. Correct?

The serial dispatch queue being bound to different threads at different times shouldn't cause any additional increase in file size _if_ all of your uses of Realm on that dispatch queue are wrapped in an explicit autorelease pool. The thing that leads to growth is multiple threads having the Realm open at different versions of the data. The explicit autorelease pool ensures that the different threads used by the serial dispatch queue do not keep the Realm open beyond the work they're performing, allowing future write transactions to reclaim space used by older versions of the data within the Realm file.

> I saw some inprovement (🎉) meaning the Realm file size seems to not be as crasy as it was before after 3/4 syncs and 3/4 background fetch. But it is still increasing which is inevitable.

That this results in an improvement is good to hear. There will inherently be some cases in which the file must grow, even when updating existing data, as there is a time window between when the write transaction is committed on a background thread and when the Realm on the main thread is advanced to the latest version of the data. If you perform further writes during this window, the older version of the data is still in use by the main thread and so cannot be used for the newly-written data. This may result in the file being expanded to accommodate the newly-written data. So long as your main thread doesn't block for long periods of times while your background thread is writing this should only result in a small amount of growth that will then be reused as new data is written in the future.

**Comment by TimOliver** [comment]
Hi @kevincador!

I hope that answered all of your questions! I'm going to close this issue now, but please feel free to re-open it if you have additional follow-up questions.

Thanks!
