### ISSUE TITLE
ObjC/Swift interoperability

### ISSUE THREAD

**Issue by danielgindi** [realm/realm-cocoa#4232]
## Goals

Interoperability with Swift & ObjC libraries.

Specifically, https://github.com/danielgindi/Charts.

We want to be able to provide both `Results` and `RLMResults` constructors.

## How to achieve this?

I can think of two easy ways:

1. Turn the `internal` constructors into `public`, so we can init with an `RLMResults` or an `RLMRealm`
2. Expose the internal properties for those.

Making even one of those subtle and easy changes - will allow having the parallel constructors, but either creating a `Results` from passed `RLMResults` and always working with the `Results` object in our code, or accessing the (currently) internal `RLMResults` of the `Results` object, and always working with the `RLMResults` object in our code.

Making both of those changes - will give great flexibility. Maybe even for other cases that we haven't considered.

## Background info

**Charts** is a crossplatform charting library. We worked with Adam Fish in the past for a Realm layer, and we stumbled upon the ObjC vs Swift situation, which we've put aside for some time. Now there's demand for a solution.

**Comment by jpsim** [comment]
Hi @danielgindi, we're already tracking this as #2920, so I'll be closing this as a duplicate.

Our team would happily accept a PR that implemented this, if you're interesting in contributing this to Realm.

Thanks for the Charts project, looks pretty cool!

**Comment by danielgindi** [comment]
I'll try to find the time and make a PR. This should be easy, a few lines of code...
