### ISSUE TITLE
I have queries only, not issues

### ISSUE THREAD

**Issue by sachin-sat** [realm/realm-cocoa#4236]
Sorry for posting this as issue. Actually it isn't.

I have some questions to clarify. Kindly help me, please.
my model has many relationship. for example a model 'Person' has many 'Notes' and many 'Attachments'.
Notes and Attachments are other 2 models.

And again Notes and Attachments has many relationships like Images and Comments.(Images and comments another Two model). I mapped them correctly using your guidelines and it's working fine :-).

What's my question is,
When i get a Person 1 object, it gives me all data of it(10 notes and 2 attachments - those 10 notes and 2 attachments have many images and comments objects) in single fetch. Is it costly?
Will slow our things? and think of getting 50 Persons in a fetch? 
Please help me to get clear on this. 

Thanks in advance :-).

**Comment by kishikawakatsumi** [comment]
@sachin-sat Realm objects lazily load their data. The reason for this is that Realm uses a zero-copy architecture which means we only load data you actually use. In other words, Realm doesn't load any data until you accessed the properties.

For example, the following code doesn't load data to memory at all.

```
let results = realm.objects(Person.self)
```

`results` just holds metadata of query. It doesn't hold any data, even not executing the query. When you accessed an element of `results`, like `let person = results[0]` or `for person in results`,  then the query will execute. But at this time, `person` doesn't load any data. Then you access a property, like `person.name`, then Realm load actual data (all Realm object's getter/setter methods are swizzled with Realm's accessor method).

So, you don't need to worry about cost or memory consumption using Realm.

**Comment by kishikawakatsumi** [comment]
Closing due to no response
