### ISSUE TITLE
App Extension is unable to open shared realm database

### ISSUE THREAD

**Issue by mattjaffa** [realm/realm-cocoa#4240]
## Goals

What do you want to achieve?

Trying to share Realm database between App, and two app extensions
## Expected Results

What did you expected to happen?

It to work
## Actual Results

What did happened instead?  

<Notice>: fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/private/var/mobile/Containers/Shared/AppGroup/CC39427A-47F7-41C5-8B1D-97AC996CD020/db.realm.lock': open() failed: Operation not permitted." UserInfo={Error Code=2, NSFilePath=/private/var/mobile/Containers/Shared/AppGroup/CC39427A-47F7-41C5-8B1D-97AC996CD020/db.realm.lock, Underlying=open("/private/var/mobile/Containers/Shared/AppGroup/CC39427A-47F7-41C5-8B1D-97AC996CD020/db.realm.lock") failed: Operation not permitted, NSLocalizedDescription=Unable to open a realm at path '/private/var/mobile/Containers/Shared/AppGroup/CC39427A-47F7-41C5-8B1D-97AC996CD020/db.realm.lock': open() failed: Operation not permitted.}
## Steps to Reproduce

What are steps we can follow to reproduce this issue?

Write a NetworkExtension app extension for iOS
## Code Sample

open lazy var realm: Realm = {
        guard let directory: URL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.shieldage.ShieldageClient") else {
            fatalError("Unable to setup Realm. Make sure to setup your app group in the developer portal")
        }

```
    let realmPath = directory.appendingPathComponent("db.realm")
    var config = Realm.Configuration()
    config.fileURL = realmPath
    Realm.Configuration.defaultConfiguration = config

    return try! Realm()
}()
```

I am using the above code in the App, and the other two NetworkExtension code
## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?
Latest download

Xcode version: ?
8.0

iOS/OSX version: ?
10.0.2 iOS

Dependency manager + version: ?
Downloaded frameworks directly from realm.io

**Comment by mattjaffa** [comment]
If I can't get this resolved quick unfortunately going to have to drop Realm and go with Core Data.

**Comment by jpsim** [comment]
It would be helpful if you could package your sample code in an Xcode project along with detailed steps to trigger this @mattjaffa.

This looks like it could be related to #4241.

**Comment by mattjaffa** [comment]
The app extensions require special entitlements from Apple to sign. I could develop some sample code but you would not be able to run it without their permission.

**Comment by mattjaffa** [comment]
I will try with a different type of App extension to see if I can't get reproducible code.

**Comment by mattjaffa** [comment]
It appears the ShareExtension shares the realm database just fine from an app group shared location. It is the NEFilterControlProvider and NEFilterDataProvider app extensions that are having the problem. These are NetworkExtensions that need special developer entitlements to develop.

**Comment by bdash** [comment]
It sounds like perhaps the sandbox used by network extensions is different? The [README in one of Apple's sample network extensions](https://developer.apple.com/library/content/samplecode/SimpleTunnel/Listings/README_md.html) says the following:

> The Filter Data Provider extension sandbox prevents the extension from communicating over the network or writing to disk to prevent any leakage of network data. The Filter Control Provider extension can communicate using the network and write to the disk.

Are you perchance hitting that limitation?

**Comment by jpsim** [comment]
@mattjaffa just following up on @bdash's last comment.

**Comment by TimOliver** [comment]
I'm closing this issue since it's been idle for over two weeks.

@mattjaffa - If you're still having trouble, please feel free to re-open it and let us know if there's anything else we can do to help.

Thanks! Happy holidays!
