### ISSUE TITLE
Document that users should avoid writing realms to their unit test bundles

### ISSUE THREAD

**Issue by Damnum** [realm/realm-cocoa#4247]
## Goals

Building and running unit tests containing a realm database.
## Expected Results

Build succeeds
## Actual Results

Build fails during signing step with error:

```
    /usr/bin/codesign --force --sign - --timestamp=none /Users/User/Library/Developer/Xcode/DerivedData/Product-gdwarfvuqpduiwhkukoteppqylrx/Build/Products/Debug\ Product-iphonesimulator/Product\ Debug.app/PlugIns/ProductTests.xctest

/Users/User/Library/Developer/Xcode/DerivedData/Product-gdwarfvuqpduiwhkukoteppqylrx/Build/Products/Debug Product-iphonesimulator/Product Debug.app/PlugIns/ProductTests.xctest: unsupported resource found (something not a directory, file or symlink)
Command /usr/bin/codesign failed with exit code 1
```
## Steps to Reproduce
1. Build and run tests containing realm file. It runs fine
2. Build and run the same tests AGAIN. The mentioned error is shown.

Further investigation has shown that the "unsupported resource" is the pipe helper file *.realm.note. This seems to get injected  into the test host when running tests containing the realm file:

`Product Debug.app/PlugIns/ProductTests.xctest/product_test.realm.note`

A similar error is also documented here: http://stackoverflow.com/a/39912197/888881
## Version of Realm and Tooling

Realm version: 2.0.2

Xcode version: 8.0

iOS version: 10.0

Dependency manager + version: Carthage 0.18

**Comment by jpsim** [comment]
I'm curious what you'd like us to do here to improve this. Perhaps mentioning in the documentation that Realm files shouldn't be located in unit test bundles to avoid this issue? The default Realm location wouldn't do that, so it seems you'd need to go out of your way to place the files in the unit test bundle.

If you'd like us to resolve this some other way, please let me know!

**Comment by Damnum** [comment]
I solved it deleting the help files after all tests are finished:
```
			afterSuite {
				let realmURLs = [
					realmUrl.appendingPathExtension("lock"),
					realmUrl.appendingPathExtension("note"),
					realmUrl.appendingPathExtension("management")
				]
				for url in realmURLs {
					do {
						try FileManager.default.removeItem(at: url)
					} catch {
						// ignore error
					}
				}
			}
```

Indeed a hint in the docs might be helpful. It took me quite a while to figure out that these files were the problem because the build logs don't give details about the error cause.

**Comment by EmDee** [comment]
Since this seems to be the one of the only issue showing up in `Google` when searching for this problem, I wanted to show our solution.

The problem for us was that the `Realm` file is part of an internal framework, so the solution suggested in https://github.com/realm/realm-cocoa/issues/4247#issuecomment-256558582 did not work for us.

Instead I added a run script to framework's build phase:

```bash
rm -rf $CODESIGNING_FOLDER_PATH/poikitMock.realm.note
rm -rf $CODESIGNING_FOLDER_PATH/poikitMock.realm.lock
rm -rf $CODESIGNING_FOLDER_PATH/poikitMock.realm.management
```

`$CODESIGNING_FOLDER_PATH` will point to the app bundle, in our case `/Users/foo/Library/Developer/Xcode/DerivedData/App/Build/Products/Development-iphonesimulator/FooBar.framework`, and this is where the unsupported resource files where.
