### ISSUE TITLE
Getting Index 0 is out of bounds (must be less than 0) in searchBar ? 

### ISSUE THREAD

**Issue by fadylateef** [realm/realm-cocoa#4248]
I've a single view app which has a tableview and a searchbar and the tableview acts as the results view of the search results 
tableview contains data from realm database - it works fine 
also the search works fine for first two characters 
after typing the third character in searchbar it gives >>

`Terminating app due to uncaught exception 'RLMException', reason: 'Index 0 is out of bounds (must be less than 0)'`

<img width="747" alt="screen shot 2016-10-23 at 3 10 03 pm" src="https://cloud.githubusercontent.com/assets/17549441/19626447/d669a476-9932-11e6-89de-a11f23f1c15d.png">

**Comment by fadylateef** [comment]
Index was out of bounds for the RowsInSection method , thanks !

**Comment by cresouls** [comment]
How did you solve the issue?

**Comment by Project112224** [comment]
search data count
if count < 1 to return
