### ISSUE TITLE
Bug found by static analyzer Infer

### ISSUE THREAD

**Issue by dulmarod** [realm/realm-cocoa#4250]
Hi,

I analyzed realm code with the Infer astatic analyzer (www.fbinfer.com) to test the tool and to have examples to present in a talk I'll give at a conference next week. I found the following potential issue, including the trace.
It would be useful to me if you could comment if the bug seems real to you, i.e. will this function ever be called with nil. Also, would you be OK if I use this example in my talk? 

Thanks a lot,
Dulma

----------------------------------------

Pods/Realm/Realm/RLMCollection.mm:172: warning: PARAMETER_NOT_NULL_CHECKED
  Parameter collection is not checked for null, there could be a null pointer dereference: pointer info last assigned on line 171 could be null and is dereferenced at line 172, column 52
Showing all 6 steps of the trace

Pods/Realm/Realm/RLMCollection.mm:164: start of procedure RLMCollectionSetValueForKey()
162.   }
163.   
164. > void RLMCollectionSetValueForKey(id<RLMFastEnumerable> collection, NSString *key, id value) {
165.       realm::TableView tv = [collection tableView];
166.       if (tv.size() == 0) {
167.   

Pods/Realm/Realm/RLMCollection.mm:165: Message tableView with receiver nil returns nil.
163.   
164.   void RLMCollectionSetValueForKey(id<RLMFastEnumerable> collection, NSString *key, id value) {
165. >     realm::TableView tv = [collection tableView];
166.       if (tv.size() == 0) {
167.           return;
168.   

Pods/Realm/Realm/RLMCollection.mm:166: Condition is false
164.   void RLMCollectionSetValueForKey(id<RLMFastEnumerable> collection, NSString *key, id value) {
165.       realm::TableView tv = [collection tableView];
166. >     if (tv.size() == 0) {
167.           return;
168.       }
169.   

Pods/Realm/Realm/RLMCollection.mm:170: Message realm with receiver nil returns nil.
168.       }
169.   
170. >     RLMRealm *realm = collection.realm;
171.       RLMClassInfo *info = collection.objectInfo;
172.       RLMObject *accessor = RLMCreateManagedAccessor(info->rlmObjectSchema.accessorClass, realm, info);
173.   

Pods/Realm/Realm/RLMCollection.mm:171: Message objectInfo with receiver nil returns nil.
169.   
170.       RLMRealm *realm = collection.realm;
171. >     RLMClassInfo *info = collection.objectInfo;
172.       RLMObject *accessor = RLMCreateManagedAccessor(info->rlmObjectSchema.accessorClass, realm, info);
173.       for (size_t i = 0; i < tv.size(); i++) {
174.   

Pods/Realm/Realm/RLMCollection.mm:172: 
170.       RLMRealm *realm = collection.realm;
171.       RLMClassInfo *info = collection.objectInfo;
172. >     RLMObject *accessor = RLMCreateManagedAccessor(info->rlmObjectSchema.accessorClass, realm, info);
173.       for (size_t i = 0; i < tv.size(); i++) {
174.           accessor->_row = tv[i];
175.

**Comment by tgoyne** [comment]
That's a private helper function which is only ever called with `self` as the first parameter, so in practice it cannot be `nil`. If `nil` was passed the application would crash, but much earlier that the report suggests (`tv.size()` will crash, not return a non-zero value).

**Comment by jpsim** [comment]
Yes, you can use this as an example of a false-positive in Infer if you'd like.
