### ISSUE TITLE
cant set config:fileURL for playground 

### ISSUE THREAD

**Issue by ggunders** [realm/realm-cocoa#4254]
ok guys, trying realm 2.02 in xcode 8 playground.

```
let config = Realm.Configuration(
    // Get the URL to the bundled file
    fileURL: Bundle.main.url(forResource: "MyBundledData", withExtension: "realm"),
    // Open the file in read-only mode as application bundles are not writeable
    readOnly: true)

// Open the Realm with the configuration
let realm = try! Realm(configuration: config)
```

im trying to set the default location of the realm file via the config, ive tried a bunch of stuff setting the config object fileUrl property, it appears playgrounds dont allow access to the main file system. 

i just want the realm file to stay in a place to use the realm browser. trying the above code from realm site yielded the error

fatal error: A Realm Configuration must specify a path or an in-memory identifier.: file /Volumes/Mac /XXX/Pods/RealmSwift/RealmSwift/RealmConfiguration.swift, line 203

any suggestions on how to set the fileURL in both playgrounds as well as the simulator. ideally somewhere on my local filesystem

thx

**Comment by TimOliver** [comment]
Hi @ggunders! 

If you're getting the `A Realm Configuration must specify a path or an in-memory identifier` error, that means that your implementation for `Bundle.main.url()` must be returning `nil`. The Swift Playground's access to on-disk resources is limited, so you need to properly import the Realm file into Playgrounds as a resource to access it.

![screen shot 2016-10-25 at 12 55 10 pm](https://cloud.githubusercontent.com/assets/429119/19701904/4886d512-9ab2-11e6-8c11-e55ce920759b.png)

As long as it's able to generate a URL for the Realm file, you should be to copy that URL you see there and open it in the Browser. The Simulator SHOULD work too, assuming it doesn't enforce any sandboxing like iOS does.

I hope that helped!

**Comment by ggunders** [comment]
ok i  moved he default.realm file into the Resources directory in my playground.

then tried the following(changing name to test.realm)

```
var config = Realm.Configuration()
let path = Bundle.main.url(forResource: "test", withExtension: "realm")
config.fileURL = path
let realm = try! Realm(configuration: config)
print(Realm.Configuration.defaultConfiguration.fileURL!)
```
the following error 

`fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/folders/tj/zcchzkcj23x4b1ygms5l7m1m0000gp/T/com.apple.dt.Xcode.pg/resources/AC308449-D16B-4386-A038-12F29549B9FC/test.realm.management': make_dir() failed: Operation not permitted." UserInfo={Error Code=2, NSFilePath=/var/folders/tj/zcchzkcj23x4b1ygms5l7m1m0000gp/T/com.apple.dt.Xcode.pg/resources/AC308449-D16B-4386-A038-12F29549B9FC/test.realm.management, Underlying=make_dir() failed: Operation not permitted, NSLocalizedDescription=Unable to open a realm at path '/var/folders/tj/zcchzkcj23x4b1ygms5l7m1m0000gp/T/com.apple.dt.Xcode.pg/resources/AC308449-D16B-4386-A038-12F29549B9FC/test.realm.management': make_dir() failed: Operation not permitted.}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.46.2/src/swift/stdlib/public/core/ErrorType.swift, line 178`

1. do i have to do anything else to setup the resources directory. ive seen some people create a symbolic back to /User/XXX/Documents

2. are permission attributes necessary for this operation

**Comment by jpsim** [comment]
The playground process only has read-only access to files in the bundle, so you'll need to set [`Realm.Configuration.readOnly`](https://realm.io/docs/swift/latest/api/Classes/Realm/Configuration.html#/s:vVC10RealmSwift5Realm13Configuration8readOnlySb) to `true`.

**Comment by ggunders** [comment]
ok i see, putting the realm db into resources is only useful for reading the database not writing to it. in order to add more data to the realm.db file, it would need to be outside the resources directory correct.

if i want the db to be placed somewhere i designate i should be using a simulator and not the playground correct, otherwise its just a read only file.

**Comment by TimOliver** [comment]
That's correct. If the Playground process is read-only, it won't be possible to make changes to any Realm files from within it.

Yes, you can use the Simulator to test out writing to Realms with no limitations.

**Comment by jpsim** [comment]
> That's correct. If the Playground process is read-only, it won't be possible to make changes to any Realm files from within it.
> 
> Yes, you can use the Simulator to test out writing to Realms with no limitations.

Not quite. The bundle is read-only in playgrounds and on iOS devices. It's technically not read-only in the iOS Simulator, though that's arguably a bug.

Also, playgrounds _can_ write to Realm files, just not in the bundle.

**Comment by jpsim** [comment]
@ggunders I'm closing this since we haven't heard back from you in a few weeks, but don't hesitate to reach out if you have any further questions.
