### ISSUE TITLE
why can not i delete object?? [Can only delete objects from the Realm they belong to.]

### ISSUE THREAD

**Issue by Dev-MJ** [realm/realm-cocoa#4258]
I wanna delete objects in realm.

### My Model class
```swift
class CardInformation: Object {
    dynamic var bankName = ""
    dynamic var cardImage : NSData?
    
    override class func primaryKey() -> String {
        return "bankName"
    }
}
```

### My TableViewController
```swift
class CardListTableViewController : UITableViewController {
    var realm = try! Realm()
    var results : Results<CardInformation>? 
    var cardInfo : CardInformation?
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let objects = results?[indexPath.row]
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell")
            cell?.textLabel?.text = objects?.bankName
        
        return cell!
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        cardInfo = CardInformation()
        cardInfo?.bankName = (results?[indexPath.row].bankName)!
        cardInfo?.cardImage = results?[indexPath.row].cardImage
        performSegue(withIdentifier: "segue_insert", sender: self)
    }
    
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            realm.beginWrite()
             
           //1. Can only delete objects from the Realm they belong to.
            realm.delete(CardInformation(value: ["bankName":(results?[indexPath.row].bankName)!, "cardImage":(results?[indexPath.row].cardImage)!] as [String: Any]))
            
//or
            //2. Can only delete objects from the Realm they belong to.
            realm.delete((results?[indexPath.row])!)    
      
//or      
            //3. Can only delete objects from the Realm they belong to.
            let deleteItem = results?.filter("bankName == %@", (results?[indexPath.row].bankName)!)
            realm.delete(deleteItem!)  

          
            try! realm.commitWrite()
            tableView.reloadData()
        }
    }    
}
```

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 2.0.2

Xcode version: 8.0

iOS/OSX version: 10.0.2

Dependency manager + version: ?

**Comment by TimOliver** [comment]
Hi there! Thanks for the issue!

Just like the error states, you can only delete `Object` model objects from the `Realm` in which they were originally saved. Judging from your code, that would seem to indicate that however you are querying for your `results` object, they're coming from a different `Realm` than the one that is provided with the default `Realm()` call.

One easy way to fix this is to use `results?.realm` to explicitly reference the origin Realm from where it came.

Finally, just to point it out, `realm.delete(CardInformation())` won't work because it's creating a new instance of `CardInformation` that wouldn't have been added to a `Realm` yet.

I hope that answered your question! Let me know if you have any more!

**Comment by Dev-MJ** [comment]
oh i really appreciate that! Thank you!!
