### ISSUE TITLE
EXC_BAD_ACCESS when opening a Realm DB

### ISSUE THREAD

**Issue by crrobinson14** [realm/realm-cocoa#4260]
I'm having an issue that seems to have a lot in common with #2320, https://github.com/realm/realm-core/issues/1558, and so on - an EXC_BAD_ACCESS on open. But my case is a little odd and doesn't seem to be covered by those. It's 100% reproducible, though, so I can easily test any suggestions for a fix.

Steps to reproduce (all on device, no simulator involved, iOS 10 Realm 1.1.0):
1. Set up a shared group for the app to share data with a Share Extension.
2. Configure Realm to store its data in a file in this group. Run the app and get some data in there.
3. Force-close the app.
4. Share something from, say, Safari via the Share Extension.
5. Have the Share Extension use the Realm file for its work. Note that it can read/write Realm data just fine here.
6. Make sure the share extension dismisses properly using `completeRequestReturningItems`. As a test (but it doesn't help), call `invalidate` on the Realm.
7. Quit Safari and start the main app.
8. App crashes with EXC_BAD_ACCESS in realm::SharedGroup::open().

<img width="1012" alt="screen shot 2016-10-25 at 12 28 58 pm" src="https://cloud.githubusercontent.com/assets/1675563/19698979/abc9f1c6-9aae-11e6-934c-3d2c1604ef2c.png">

The app successfully opens on the next attempt. It's as if something from the share extension is "locking" the Realm file. Any thoughts?

**Comment by TimOliver** [comment]
Hi @crrobinson14!

Thanks for reporting this to us! 

Hmm, one thing I might initially try suggesting. In your Safari extension, can you please try encapsulating the code blocks that involving instantiating `Realm` and subsequently performing the read/writes in an `@autoreleasepool`?

It's possible that there are cached references to the `Realm` instance still in memory by the time the extension process is terminated, so Realm isn't getting a chance to clean up after itself. If this is the case, enclosing all operations involving `Realm` in an `@autoreleasepool` will explicitly force Realm to release itself immediately after your code has finished execution.

Please let me know if that helps. If it doesn't, would you be open to sharing your code with us at all?

Thanks!

**Comment by crrobinson14** [comment]
I'll give that a try today and report back.

**Comment by crrobinson14** [comment]
OK I can confirm that this solves the problem. It does create a few challenges regarding how the apps and extensions are written but it works for now.

**Comment by crrobinson14** [comment]
Is it possible to add an explicit `close` operation to Realm? Earlier I tried calling `invalidate` but that didn't fix it. In a normal app you never know when the user might Home out and Apple doesn't like explicit app-close operations. But in share extensions there IS an explicit close operation so we have good information to send to Realm to help it clean up...

**Comment by bdash** [comment]
It'd be useful to understand what exception is being thrown, and why. There's more than one possible exception that can be thrown beneath `SharedGroup::open`.

**Comment by crrobinson14** [comment]
How can I help provide that? All I get is EXC_BAD_ACCESS. There's no subgroup with it.

**Comment by bdash** [comment]
The screenshot from your original report shows a C++ exception being thrown. If you select the next level up from the `__cxa_throw` frame in the backtrace it should show you the disassembly of Realm's core library at the point the exception was thrown, which should include the exception message.

**Comment by crrobinson14** [comment]
Sorry, I don't seem to get anything useful here. Here's a full screen shot of the next frame up. There's a disassembly but no message. I'm compiling in DEBUG mode and all opts off/no stripping. Is there a way to get this layer to be included with symbols?

<img width="1435" alt="screen shot 2016-10-26 at 9 59 54 pm" src="https://cloud.githubusercontent.com/assets/1675563/19754108/c944adda-9bc7-11e6-8dd8-10f347efb422.png">

**Comment by bdash** [comment]
Your backtrace in the most recent screenshot is missing frames that are present in your original screenshot as you appear to now have the "Show only stack frames with debug symbols and between libraries" setting enabled. Disabling that setting and reproducing again should get you to the `SlabAlloc::attach_file` frame that's throwing the exception.

<img width="416" alt="c944adda-9bc7-11e6-8dd8-10f347efb422" src="https://cloud.githubusercontent.com/assets/54825/19754221/6ced4ac6-9bc0-11e6-956e-c23700565c02.png">

**Comment by crrobinson14** [comment]
Gah, sorry, it's been a long day.

<img width="1440" alt="screen shot 2016-10-26 at 10 12 48 pm" src="https://cloud.githubusercontent.com/assets/1675563/19754305/624323da-9bc9-11e6-9c3d-ac988125a0e8.png">

**Comment by bdash** [comment]
Thanks, @crrobinson14. It looks like the exception that is being thrown is [`SlabAlloc::Retry`](https://github.com/realm/realm-core/blob/v1.5.0/src/realm/alloc_slab.cpp#L823-L829). Throwing that exception by itself shouldn't turn into a crash. Do you have a crash log that shows more details about the crash than your initial screenshot?

**Comment by crrobinson14** [comment]
Unfortunately no; we were activating Hockey after Realm. However we've just changed that so I'll add the log here as soon as I get one (hopefully by tomorrow).

**Comment by bdash** [comment]
If you're able to reproduce locally you should get a standard iOS crash log by reproducing outside of Xcode.

**Comment by jpsim** [comment]
@crrobinson14 just following up on our requests for more information. Also a confirmation that the issue still occurs with the latest release ([2.1.1](https://github.com/realm/realm-cocoa/releases/tag/v2.1.1)) would be helpful.

**Comment by crrobinson14** [comment]
Sorry guys, I would close this if you're waiting on me for follow-up. For a variety of internal reasons we've re-architected our app around Firebase in the past week so we won't be able to confirm the new behavior. Thanks for the follow-up, though.

**Comment by jpsim** [comment]
Sounds good.
