### ISSUE TITLE
Prebuilt binary for 2.0.3 is actually built with Swift 3.0

### ISSUE THREAD

**Issue by soffes** [realm/realm-cocoa#4270]
## Goals

Use Realm with Xcode 8.1 via Carthage.

## Expected Results

The prebuilt binary is built with Swift 3.0.1 like [the release](https://github.com/realm/realm-cocoa/releases/tag/v2.0.3) says.

## Actual Results

Xcode 8.1 says it can't compile since RealmSwift was built with Swift 3.0.

```
error: module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: /Users/soffes/.../Carthage/Build/iOS/RealmSwift.framework/Modules/RealmSwift.swiftmodule/i386.swiftmodule
```

## Steps to Reproduce

Try to use realm-cocoa with Xcode 8.1.

## Version of Realm and Tooling

Realm version: 2.0.3

Xcode version: 8.1 (8B62)

iOS/OSX version: 10.1

Dependency manager + version: Carthage 0.18.1

**Comment by jpsim** [comment]
Yup, sorry about that. Only the Carthage binaries should be affected. I'm in the process of rebuilding it now with Xcode 8.1.

**Comment by jpsim** [comment]
Should be fixed now. Thanks for reporting.

**Comment by soffes** [comment]
Confirmed this is fixed. Thanks! ❤️
