### ISSUE TITLE
Swift Documentation for List looks like outdated

### ISSUE THREAD

**Issue by aaadonai** [realm/realm-cocoa#4271]
I am looking at the documentation for Realm Swift [List class](https://realm.io/docs/swift/latest/api/Classes/List.html#/s:FC10RealmSwift4List6appenduRd__s8SequencexzWd__8Iterator7Element_rFT9objectsInqd___T_) and comparing with the code in my pod folder and I can't see the method `public func append<S: Sequence>(objectsIn objects: S) where S.Iterator.Element == T`. On the other hand the method `public func appendContentsOf<S: SequenceType where S.Generator.Element == T>(objects: S)` in List.swift is not in the documentation.

Is the documentation outdated?

I have RealmSwift version 2.0.3 installed via cocoapods.

Thanks.

**Comment by bdash** [comment]
Our API documentation only reflects the Swift 3 API.`append(objectsIn:)` is the name of the method for Swift 3. In Swift 2.x it was known as `appendContentsOf(_:)`.

**Comment by aaadonai** [comment]
That makes sense. Thanks for your help.
