### ISSUE TITLE
Realm Object Server syncing

### ISSUE THREAD

**Issue by jdmarshall90** [realm/realm-cocoa#4272]
According to the Realm Object Server authentication documentation for iCloud here: https://realm.io/docs/realm-object-server/#authentication, you need to configure Realm with a few items from the CloudKit dashboard. 

My question is, if I use iCloud to authenticate, do I still need to have my own server in order for syncing to work? Or is it just as simple as pointing to CloudKit? Same question applies for Facebook or Google authentication. 

If this is already answered in the documentation, I apologize for overlooking it. 

Thanks!

**Comment by poseidonsw** [comment]
you still need the object server running somewhere. The cloudkit is used for login similar to how you would use facebook login on some websites.

**Comment by jdmarshall90** [comment]
Ok, that's what I figured I just wanted to clarify. Thank you.
