### ISSUE TITLE
Building Realm (check out 10/30/2016) fails

### ISSUE THREAD

**Issue by Sil68** [realm/realm-cocoa#4278]
## Goals

Building Realm from the most recent sources found at GitHub.
## Expected Results

After executing "sh build.sh sox-swift" the corresponding libraries/frameworks should have been built and should be available for further use.
## Actual Results

....
al/x86_64/RLMRealmConfiguration+Sync.o
/Volumes/data/Project/Xcode/frameworks/Realm/realm-cocoa-2.0.3-master/Realm/RLMRealmConfiguration+Sync.mm:62:92: error: no member
      named 'user_tag' in 'realm::SyncConfig'
    RLMSyncUser *thisUser = [[RLMSyncManager sharedManager] _userForIdentity:@(sync_config.user_tag.c_str())];
                                                                               ~~~~~~~~~~~ ^
1 error generated.

.....

*\* BUILD FAILED **

The following build commands failed:
    CompileC build/DerivedData/Realm/Build/Intermediates/Realm.build/Release/Realm.build/Objects-normal/x86_64/RLMRealmConfiguration+Sync.o Realm/RLMRealmConfiguration+Sync.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
## Steps to Reproduce
1. get Realm source from GitHub;
2. get ObjectStore source, too, and place the in the corresponding directory;
3. execute "sh build.sh osx-swift".
## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version:  2.0.3 (as of 30/10/2016 at GitHub's)

Xcode version: 8.1

OSX version: 10.12

**Comment by kishikawakatsumi** [comment]
@Sil68 I confirmed building from source (`master` branch) successfully.

```
$ git clone git@github.com:realm/realm-cocoa.git
$ cd realm-cocoa/
$ git submodule update --init
$ sh build.sh osx-swift
```

Can you try again? If build would fail yet, please show more details to reproduce steps for investigation? Thank you for reporting.

**Comment by Sil68** [comment]
@kishikawakatsumi Brilliant! Thanks a lot! Following your instructions did do the trick!

**Comment by Sil68** [comment]
Apparently it's again an issue related to facilitating AFP-mounted volumes.

Cloning the repository to a folder on the internal drive, and building realm there succeeds as expected. Carrying out the very same task with a folder residing on an AFP-mounted volumes leads to a build failure.
