### ISSUE TITLE
Crash at viewLoaded on RealmSearchViewController - Xcode 8

### ISSUE THREAD

**Issue by reicamargo** [realm/realm-cocoa#4279]
Hi. I've updated Xcode to 8.0 with Swift 3.0. When I tried to build I got the error "Cannot override with a stored property 'viewLoaded" on the  RealmSearchViewController.

I've checked where the problem is, it crashes is in RealmSearchViewController.swift at line
"open var viewLoaded: Bool = false"

## Steps to Reproduce
Migrate your Swift 2.3 code to Swift 3.0 and try to build it.

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555

/Applications/Xcode.app/Contents/Developer
Xcode 8.0
Build version 8A218a

/usr/local/bin/pod
1.0.1
Realm (2.0.3)
RealmSwift (2.0.3)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

carthage not found
(not in use here)

**Comment by kishikawakatsumi** [comment]
@reicamargo  It's not related Realm. The cause is Swift API naming conventions are changed in Swift 3.
Also, the issue is tracked by RealmSearchViewController's repository. Ihttps://github.com/bigfish24/ABFRealmSearchViewController/issues/13

Thank you for reporting.
