### ISSUE TITLE
Increment all schema versions when having multiple databases?

### ISSUE THREAD

**Issue by davros1970** [realm/realm-cocoa#4280]
## Goals

What do you want to achieve?

My goal is to have separate Realm databases within the same Swift iOS app. Each with its own schema. Each database is unaware of the others existence. When I add a new property to DB schema A, I roll the schema version in my Realm.Configuration. When I run, I get an exception from the other DB schema B saying there was a schema change. Ultimately, I have to bump that schema B's version as well. This makes developing and packaging each DB in its own Swift Framework problematic (especially if you have separate developers or companies working on each framework). 

## Expected Results

What did you expected to happen?

When I make a schema change to a specific Realm.Configuration, I should not have to increment the schema version for all unrelated Realm.Configurations that just happen to be compiled into the same app binary.

## Actual Results

What did happened instead?  

The DB that did not have any schema changes threw an exception at runtime stating there was a schema change.

## Steps to Reproduce

* Dont use the default Realm.Configuration.
* Make 2 separate Realm.Configurations. Each points to their own file, etc. No relationships between them at all. Although the app itself shall reference both DB's.
* Add a new property to one of the DB schemas.
* Bump the schema version in the DB with the new property.
* Run

Realm version: 2.0.2

Xcode version: 8.1

iOS/OSX version: 10.1

**Comment by kishikawakatsumi** [comment]
@davros1970 You can use `Realm.Configuration.objectTypes` property to isolate model classes as follows.

```swift
let configForSchemaA = Realm.Configuration(objectTypes: [A.self, B.self])
let realmA = try! Realm(configuration: configForSchemaA)

let configForSchemaB = Realm.Configuration(objectTypes: [C.self])
let realmB = try! Realm(configuration: configForSchemaB)
```

Then if you add a property to class `A`, what you need to do is bump version for Realm A. You don't need to bump schema version for Realm B.

See also https://realm.io/docs/swift/latest/#class-subsets

**Comment by davros1970** [comment]
OK, I do use that for one of the DB (where I bumped the schema version to add a property), but the other does not use objectTypes. That explains the issue I'm seeing then! Thx for the quick response!
