### ISSUE TITLE
mobile platform iOS tutorial missing step.

### ISSUE THREAD

**Issue by euwars** [realm/realm-cocoa#4285]
I followed mobile platform iOS tutorial, something that is different when you actually follow the tutorial is having empty database, but in video after connecting to sync server there are 3 objects already.

having empty database causes results to be empty which means .realm is nil and writing will fail.
i went throw RealmTasks source code, to find the part where it adds an object after setting default realm and checks if its an empty database to add one object after.

i think this step should be added to tutorial code and probably to the video also.

**Comment by jpsim** [comment]
Hi @euwars, the tutorial expects that you've followed the "Getting Started" steps. In fact, the second sentence of the [tutorial](https://realm.io/docs/realm-mobile-platform/example-app/cocoa/) states exactly that:

> First, please follow the getting started instructions to get set up with sync and to launch the Mac version of RealmTasks.

Following those steps will ensure that the initial list already exists.

**Comment by euwars** [comment]
@jpsim yeah i did not see that my bad.
