### ISSUE TITLE
Realm (Swift) + j2OBJC not working

### ISSUE THREAD

**Issue by hardysim** [realm/realm-cocoa#4286]
## Goals

I'm trying to setup a swift-project using `RealmSwift`-CocoaPod and some manual setup to use Java-code via **J2OBJC**.

## Expected Results

A working iOS-Swift-project where I can use the cross-compiled Java-classes and realm together.

## Actual Results

When building, an error occurs:

> Apple Match-O Linker Error
```
Undefined symbols for architecture x86_64:
  "_adler32", referenced from:
      -[JavaUtilZipAdler32 updateWithInt:] in libjre_emul.a(Adler32.o)
      -[JavaUtilZipAdler32 updateWithByteArray:withInt:withInt:] in libjre_emul.a(Adler32.o)
      -[JavaUtilZipAdler32 updateImplWithByteArray:withInt:withInt:withLong:] in libjre_emul.a(Adler32.o)
      -[JavaUtilZipAdler32 updateByteImplWithInt:withLong:] in libjre_emul.a(Adler32.o)
  "_crc32", referenced from:
      -[JavaUtilZipCRC32 updateWithInt:] in libjre_emul.a(CRC32.o)
      -[JavaUtilZipCRC32 updateWithByteArray:withInt:withInt:] in libjre_emul.a(CRC32.o)
      -[JavaUtilZipCRC32 updateImplWithByteArray:withInt:withInt:withLong:] in libjre_emul.a(CRC32.o)
      -[JavaUtilZipCRC32 updateByteImplWithByte:withLong:] in libjre_emul.a(CRC32.o)
  "_deflate", referenced from:
      _JavaUtilZipDeflater_deflateImplWithByteArray_withInt_withInt_withLong_withInt_ in libjre_emul.a(Deflater.o)
  "_deflateEnd", referenced from:
      _JavaUtilZipDeflater_endImpl in libjre_emul.a(Deflater.o)
      -[JavaUtilZipDeflater endImplWithLong:] in libjre_emul.a(Deflater.o)
  "_deflateInit2_", referenced from:
      _JavaUtilZipDeflater_createStreamWithInt_withInt_withBoolean_ in libjre_emul.a(Deflater.o)
  "_deflateParams", referenced from:
      _JavaUtilZipDeflater_setLevelsImplWithInt_withInt_withLong_ in libjre_emul.a(Deflater.o)
  "_deflateReset", referenced from:
      _JavaUtilZipDeflater_resetImplWithLong_ in libjre_emul.a(Deflater.o)
  "_deflateSetDictionary", referenced from:
      _JavaUtilZipDeflater_setDictionaryImplWithByteArray_withInt_withInt_withLong_ in libjre_emul.a(Deflater.o)
  "_inflate", referenced from:
      _JavaUtilZipInflater_inflateImplWithByteArray_withInt_withInt_withLong_ in libjre_emul.a(Inflater.o)
  "_inflateEnd", referenced from:
      -[JavaUtilZipInflater end] in libjre_emul.a(Inflater.o)
      -[JavaUtilZipInflater endImplWithLong:] in libjre_emul.a(Inflater.o)
  "_inflateInit2_", referenced from:
      _JavaUtilZipInflater_createStreamWithBoolean_ in libjre_emul.a(Inflater.o)
  "_inflateReset", referenced from:
      _JavaUtilZipInflater_resetImplWithLong_ in libjre_emul.a(Inflater.o)
  "_inflateSetDictionary", referenced from:
      _JavaUtilZipInflater_setDictionaryImplWithByteArray_withInt_withInt_withLong_ in libjre_emul.a(Inflater.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps to Reproduce

The J2OBJC-setup is working fine. It's even working using some other CocoaPods but as soon as I'm adding `RealmSwift` it cannot build anymore.

I'm cross-compiling java-classes using J2OBJC and then using a Swift-Briding-Header to access them. This setup is described at the following link (basically add  `USER_HEADER_SEARCH_PATHS`, `LIBRARY_SEARCH_PATHS` and the flags `-lshared-j2objc` and `-ljre_emul`.

https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#how-do-i-manually-configure-my-xcode-project-to-use-the-translated-libraries

## Code Sample

I'll set up a full Xcode project and link it in a later comment. The actual java-classes I'm translating from are included as a git-submodule (but this shouldn't be a problem as the compiled files are what we need).

https://github.com/hardysim/realm-j2objc-example

## Version of Realm and Tooling

Realm version: 2.0.2

Xcode version: 8.0 (8A218a)

iOS version: 10.0

**Comment by bdash** [comment]
The error message indicates that zlib, required by libjre_emul.a, isn't being linked into your target. It looks like your `realm-j2objc-example` links against libjre_emul.a but doesn't also link against zlib. I'd guess that adding `-lz` to your linker flags for that target should address the problem.

I'm not clear why you believe Realm to be relevant to this?

**Comment by hardysim** [comment]
@bdash it's working **until** I add the realm-cocoapod. So my guess was that realm interferes somehow ?!

**Comment by bdash** [comment]
Have you tried the change I suggested? Did it work?

**Comment by hardysim** [comment]
@bdash your tip adding `-lz` is working. Now I can use realm as well. Any idea why I only need to add it when adding realm?

---

How do I see that I need `zlib` from the error-messages? I'm new to this linker-stuff and cannot see any mention of it...

**Comment by bdash** [comment]
From what I can see you should have needed to link against zlib anyway. I don't know why it happened to work without it.

> How do I see that I need zlib from the error-messages?

There's nothing super obvious in the error message that indicates zlib is needed. I happen to know that the symbols that are missing are all from zlib.
