### ISSUE TITLE
iOS App Crashes with 2.0.3 Carthage Build in Xcode 8.1

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-cocoa#4287]
I just upgraded to Xcode 8.1 and upgraded Realm to 2.0.3. Here are the steps I have taken:

1. I downloaded the pre-built frameworks for Realm and dragged the Swift 3.0.1 versions to my `<Project>/Carthage` folder. 
2. I drag `RealmSwift.framework` and `Realm.framework` frameworks to **Target** > **General** > **Linked Frameworks and Libraries**.
3. I ensure I have a Run Script Build Phase with `/usr/local/bin/carthage copy-frameworks`
4. I build my app and it succeeds.
5. Upon launching, the app crashes with this error:

```
dyld: Library not loaded: @rpath/Realm.framework/Realm
  Referenced from: ~/Library/Developer/CoreSimulator/Devices/B5CAEF86-9F98-4904-A3F4-0ED1D810CA47/data/Containers/Bundle/Application/37AA3D83-CE3E-486C-9616-28B28D4D436A/My App.app/My App
  Reason: image not found
```

All my other Carthage frameworks are fine and don't throw an error.

**Workaround:** I can make this error go away if I drag the 2 frameworks to the **Target** > **General** > **Embedded Binaries** but as I understand it, that defeats the purpose of using Carthage because it's embedding all the unneeded framework overhead in my app binary. I could be wrong, though.

Anyone else hitting this? Any suggestions?

**Comment by kishikawakatsumi** [comment]
@cliftonlabrum Could you please make sure a Run Script Build Phase with `/usr/local/bin/carthage copy-frameworks` is in the last of Build Phase?

**Comment by cliftonlabrum** [comment]
Yeah, I already did that (see my 3rd bullet above).

I have resolved this by creating a new project in Xcode and migrating my code over. Somehow my project configuration got messed up and I'm unsure why.
