### ISSUE TITLE
Import conflict issue with another pods

### ISSUE THREAD

**Issue by smolskyaleksey** [realm/realm-cocoa#4294]
[PJTEST 2.zip](https://github.com/realm/realm-cocoa/files/570893/PJTEST.2.zip)
Hello. I try to add Realm like a pod to my project and I have import conflict issue when I run build.  I attached demo project to show issue. Could you help me to find right way to resolve it? Need to make pod install before run project.
Environment: Xcode 8.1, Cocoapods 1.1.1

**Comment by bdash** [comment]
The error in question is:
```
CompileC Pods.build/Debug-iphonesimulator/Realm.build/Objects-normal/x86_64/list.o Realm/Realm/ObjectStore/src/list.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler

In file included from PJTEST 2/Pods/Realm/Realm/ObjectStore/src/list.cpp:19:
PJTEST 2/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/Versions/A/Headers/pj++/list.hpp:23:10: fatal error: 'pj/list.h' file not found
#include <pj/list.h>
         ^
1 error generated.
```

What's happening is that when building the Realm pod, headers from the Vialer-pjsip-iOS pod are being picked up instead of Realm's headers (list.cpp does `#include "list.hpp"` and expects to find its own list.hpp rather than one from a different directory). I'm not clear whether this is a bug in Realm's CocoaPod spec or Vialer-pjsip-iOS's CocoaPod spec, or if something else is going on. Someone more familiar with CocoaPods can probably shed some more light on this.

**Comment by smolskyaleksey** [comment]
I added this one in my Podfile and it helped me to resolve issue.
```
ost_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'Realm'
                config.build_settings['USE_HEADERMAP'] = 'NO'
            end
        end
    end
end

```

**Comment by bdash** [comment]
@mrackwitz, do you know whether it's expected that different pods can conflict in this fashion?

**Comment by mrackwitz** [comment]
I think this is an expected issue. For historic reasons, CocoaPods still allows to refer to public headers across targets when integrating with static libraries. This shouldn't appear when using frameworks.

**Comment by mrackwitz** [comment]
Also for reference: the concrete conflict is tracked over in the CocoaPods repositories issue tracker as https://github.com/CocoaPods/CocoaPods/issues/6130. There is a discussion around the general underlying issue in https://github.com/CocoaPods/CocoaPods/issues/5941.

**Comment by jpsim** [comment]
Closing as this appears sufficiently tracked in CocoaPods.
