### ISSUE TITLE
Syncs only once for read-only realms

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-cocoa#4296]
## Goals

Access a realm in the root path, e.g. `/realmtasks`

## Expected Results

A non admin user can open a realm in the root path and have read only access,

## Actual Results

The client only syncs once and then the connection is closed.
I think that is because there are 2 sessions opened: 1 with the token that gives read only access to the realm in the root path, and another token that gives the user read-write access in its home directory. Since the latter does not have access rights, the connection gets closed.

## Steps to Reproduce

1. Use the RealmTasks app. Change the realm to be in the root path   e.g. `/realmtasks`.
2. Create an admin user when you start the ROS.
3. Use that admin user to create some tasks.
4. Uninstall the app
5. Create a new regular user and login in the RealmTasks app. 

More details here https://github.com/realm/realm-mobile-platform/issues/30

## Version of Realm and Tooling

RMP 1.0.0-BETA-4.0

Realm version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Is this still a bug? My collection is that read-only Realms cannot be used with Sync at all.

**Comment by tgoyne** [comment]
Read-only here means only read permissions granted by the server and not actual read-only.

**Comment by austinzheng** [comment]
Oh, I see. The original bug description mentions tokens with permissions.

**Comment by jpsim** [comment]
Read-only sync permissions have not yet been fully implemented on the client-side, and may not work at all depending on your situation. We're tracking this internally as realm/product#195, and we have other related bugs that are opened that should be reviewed and consolidated into a single bug tracking the fact that read-only or write-only sync permissions aren't well supported.

See also #4485 and realm/realm-mobile-platform#30, among other related issues.

**Comment by jpsim** [comment]
This has been fixed in #4910.

Note that if a sync user ever has the possibility of only having read access to a Realm, the only safe way to access that Realm is through the `asyncOpen` API. This is because the synchronous API provides access to the Realm immediately (yay offline-first!), which eagerly writes some metadata information to the Realm (e.g. schema), which then fails if the server rejects the changes due to insufficient permissions.

**Comment by dennishahn** [comment]
The information to use asyncOpen API (Realm.asyncOpen(configuration:) was actually very important if you want the read-only behavior for your realm! That should be in the documentation

**Comment by jpsim** [comment]
Thanks for the suggestion @dennishahn, we added the following to our docs shortly after your comment: https://realm.io/docs/swift/latest/#opening-a-synchronized-realm

> If a Realm has read-only [permissions](https://realm.io/docs/swift/latest#access-control "Access Control"), then you _must_ use the `asyncOpen` API as described in [Asynchronously Opening Realms](https://realm.io/docs/swift/latest#asynchronously-opening-realms). Opening a read-only Realm without `asyncOpen` will cause an error.
