### ISSUE TITLE
Documentation update for Realm Swift Migration?

### ISSUE THREAD

**Issue by mlusas** [realm/realm-cocoa#4297]
We're looking to migrate our Realm Swift 2.0.1 to add additional objects to several models. However, the documented code in [Realm Swift 2.0.1 - Migrations](https://realm.io/docs/swift/2.0.1/#migrations) results in an "...tuples have a different number of elements" error.  The documentation for Migrations has not changed for several versions, so I'm thinking it may be outdated.

Any thoughts on the best way to Migrate Realm instances? Thank you,

**Code from Realm Swift Documentation**

```
let config = Realm.Configuration(schemaVersion: 1, migrationBlock: { migration, oldSchemaVersion in
    if (oldSchemaVersion < 1) {
      // Nothing to do!
      // Realm will automatically detect new properties and removed properties
      // And will update the schema on disk automatically
    }
})

Realm.Configuration.defaultConfiguration = config

let realm = try! Realm()
```

**Comment by bdash** [comment]
Which version of Swift are you using? The code in question appears to compile for me with the current version of Realm with both Swift 2.3 and Swift 3.0.

**Comment by stel** [comment]
@mlusas do you still need any help with this? If so, could you provide us more info to reproduce your case? Or feel free to close this issue?
