### ISSUE TITLE
Duplication of entities in Realm

### ISSUE THREAD

**Issue by andertsk** [realm/realm-cocoa#4307]
## Goals

Realm database have only items without duplication.  

## Actual Results

Realm database have duplicate items

## Code Sample

I using the `realm.add(stop, update: true)` and have in the `Stop` class
`override static func primaryKey() -> String? { return "id"
}` but as result i have the picture that below (screenshot from realm browser). But no warnings or errors is popped up.

## Version of Realm and Tooling

Realm version: 2.0.3

Xcode version: 8.0

iOS/OSX version: 10

![2016-11-08 14 45 18](https://cloud.githubusercontent.com/assets/705208/20090804/f3b6bb54-a5c1-11e6-9bd2-d49a3b94716a.png)

**Comment by bdash** [comment]
Are you able to share the Realm file in question? That'll help us understand what's going on. Feel free to email it to help@realm.io, referencing this issue, if its contents are private.

**Comment by andertsk** [comment]
Sorry, it was my mistake - this duplication was in List<Stop> and not in database.
