### ISSUE TITLE
我想问一下，就是我怎么数据模型里面嵌套模型数组，存入数据库

### ISSUE THREAD

**Issue by 953995648** [realm/realm-cocoa#4309]
{
            "attitudes_count" = 22;
            "biz_feature" = 0;
            "biz_ids" =             (
                230935
            );
            "bmiddle_pic" = "http://ww4.sinaimg.cn/bmiddle/884f7263jw1f9kyw0b1amj20ez0ag3zz.jpg";
            cardid = "star_069";
            "comments_count" = 44;
            "created_at" = "Tue Nov 08 20:21:59 +0800 2016";
            "darwin_tags" =             (
            );
            favorited = 0;
            geo = "<null>";
            "gif_ids" = "";
            hasActionTypeCard = 0;
            "hot_weibo_tags" =             (
            );
            id = 4039635925694647;
            idstr = 4039635925694647;
            "in_reply_to_screen_name" = "";
            "in_reply_to_status_id" = "";
            "in_reply_to_user_id" = "";
            isLongText = 0;
            "is_show_bulletin" = 2;
            mid = 4039635925694647;
            mlevel = 0;
            "original_pic" = "http://ww4.sinaimg.cn/large/884f7263jw1f9kyw0b1amj20ez0ag3zz.jpg";
            "pic_urls" =             (
                                {
                    "thumbnail_pic" = "http://ww4.sinaimg.cn/thumbnail/884f7263jw1f9kyw0b1amj20ez0ag3zz.jpg";
                }
            );
            "positive_recom_flag" = 0;
            "reposts_count" = 5;
            rid = "0_0_1_2789438056014392501";
            source = "<a href=\"http://app.weibo.com/t/feed/2O2xZO\" rel=\"nofollow\">\U4eba\U6c11\U7f51\U5fae\U535a</a>";
            "source_allowclick" = 0;
            "source_type" = 1;
            text = "\U3010\U7537\U5b50\U6559\U55063\U5c81\U513f\U5b50\U5f53\U8857\U62e6\U8f66 \U7d22\U8981\U8d22\U7269\U4f9b\U81ea\U5df1\U6325\U970d\U3011\U4e00\U7537\U5b50\U5728\U59bb\U5b50\U79bb\U5bb6\U51fa\U8d70\U540e\Uff0c\U7ecf\U5e38\U5506\U4f7f3\U5c81\U7684\U513f\U5b50\U4e0a\U8857\U62e6\U6c7d\U8f66\U7d22\U8981\U8d22\U7269\U4f9b\U81ea\U5df1\U6325\U970d\Uff0c\U4e14\U9157\U9152\U6210\U6027\U3002\U7ecf\U9274\U5b9a\Uff0c\U7537\U5b50\U60a3\U6709\U9152\U6bd2\U6027\U4eba\U683c\U6539\U53d8\Uff0c\U5177\U6709\U9650\U5236\U884c\U4e3a\U80fd\U529b\U3002\U8fd1\U65e5\Uff0c\U6cd5\U9662\U64a4\U9500\U4e86\U7537\U5b50\U7684\U76d1\U62a4\U4eba\U8d44\U683c\Uff0c\U6307\U5b9a\U5c45\U59d4\U4f1a\U4e3a\U5b69\U5b50\U7684\U76d1\U62a4\U4eba\U3002\Uff08\U626c\U5b50\U665a\U62a5\U7f51\Uff09http://t.cn/Rf7BICI";
            textLength = 272;
            "text_tag_tips" =             (
            );
            "thumbnail_pic" = "http://ww4.sinaimg.cn/thumbnail/884f7263jw1f9kyw0b1amj20ez0ag3zz.jpg";
            truncated = 0;
            user =             {
                "allow_all_act_msg" = 0;
                "allow_all_comment" = 1;
                "avatar_hd" = "http://tva3.sinaimg.cn/crop.1.0.179.179.1024/884f7263jw8ev7jo9p7gtj20500500sy.jpg";
                "avatar_large" = "http://tva3.sinaimg.cn/crop.1.0.179.179.180/884f7263jw8ev7jo9p7gtj20500500sy.jpg";
                "bi_followers_count" = 934;
                "block_app" = 1;
                "block_word" = 0;
                cardid = "star_069";
                city = 1000;
                class = 1;
                "cover_image" = "http://ww3.sinaimg.cn/crop.0.0.920.300/884f7263gw1f2pamn1go1j20pk08cq3g.jpg";
                "cover_image_phone" = "http://ww1.sinaimg.cn/crop.0.0.640.640.640/549d0121tw1egm1kjly3jj20hs0hsq4f.jpg";
                "created_at" = "Fri Aug 05 13:31:32 +0800 2011";
                "credit_score" = 80;
                description = "\U62a5\U9053\U5168\U7403 \U4f20\U64ad\U4e2d\U56fd";
                domain = renminwang;
                "favourites_count" = 16;
                "follow_me" = 0;
                "followers_count" = 35381600;
                following = 1;
                "friends_count" = 5000;
                gender = m;
                "geo_enabled" = 0;
                id = 2286908003;
                idstr = 2286908003;
                lang = "zh-cn";
                location = "\U5317\U4eac";
                mbrank = 6;
                mbtype = 12;
                name = "\U4eba\U6c11\U7f51";
                "online_status" = 0;
                "pagefriends_count" = 3000;
                "profile_image_url" = "http://tva3.sinaimg.cn/crop.1.0.179.179.50/884f7263jw8ev7jo9p7gtj20500500sy.jpg";
                "profile_url" = renminwang;
                province = 11;
                ptype = 0;
                remark = "";
                "screen_name" = "\U4eba\U6c11\U7f51";
                star = 0;
                "statuses_count" = 99149;
                urank = 40;
                url = "";
                "user_ability" = 1540;
                verified = 1;
                "verified_contact_email" = "";
                "verified_contact_mobile" = "";
                "verified_contact_name" = "";
                "verified_level" = 3;
                "verified_reason" = "\U4eba\U6c11\U7f51\U6cd5\U4eba\U5fae\U535a";
                "verified_reason_modified" = "";
                "verified_reason_url" = "";
                "verified_source" = "";
                "verified_source_url" = "";
                "verified_state" = 0;
                "verified_trade" = "";
                "verified_type" = 3;
                "verified_type_ext" = 0;
                weihao = "";
            };
            userType = 0;
            visible =             {
                "list_id" = 0;
                type = 0;
            };
        }

**Comment by jpsim** [comment]
I'm sorry @953995648, but I don't understand your request, even after Google Translate. I can tell you're asking about how to define your models to match the data you've dumped here, so I suggest you read the [Migrations section of our docs](https://realm.io/docs/swift/latest/#models).
