### ISSUE TITLE
Downloading sync failed

### ISSUE THREAD

**Issue by wells1013** [realm/realm-cocoa#4314]
download sync aways failed
>  > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: sync 1.0.0-BETA-3.3
   Downloading sync failed:
   curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 1.0.0-BETA-3.3
Downloading sync failed:
curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**Comment by jpsim** [comment]
Which version of `curl` are you using? This may be curl/curl#619, which was apparently fixed in curl 7.49.0: https://github.com/curl/curl/commit/726ae07b07c4cfba2abc2083d2f4d28ad4a6316d.

Although that's really just a fix for the error message. The problem here being that the network operation timed out, which is out of our control.

Please try again with a stable internet connection.

**Comment by svachmic** [comment]
I'm having very similar issue @jpsim :

```
-> Installing Realm (2.3.0)
 > Git download
 > Git download
     $ /usr/local/git/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/8c/hn8jcjqs757fnb43_4j58x5h0000gn/T/d20170126-19247-8gzoae --template=
     --single-branch --depth 1 --branch v2.3.0
     Cloning into '/var/folders/8c/hn8jcjqs757fnb43_4j58x5h0000gn/T/d20170126-19247-8gzoae'...
     Note: checking out 'a26ff2239e5a0c8b4eec23ac4415218d6421ab3d'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
     $ /usr/local/git/bin/git -C /var/folders/8c/hn8jcjqs757fnb43_4j58x5h0000gn/T/d20170126-19247-8gzoae submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into 'Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out '0ebca0f03141f52131d6d9f0e6b2f2e32ab9a56d'
     Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'external/catch'
     Submodule 'external/pegtl' (https://github.com/ColinH/PEGTL) registered for path 'external/pegtl'
     Cloning into 'external/catch'...
     Submodule path 'Realm/ObjectStore/external/catch': checked out 'f294c9847272b1b92c5119a6f711e57113b5f231'
     Cloning into 'external/pegtl'...
     Submodule path 'Realm/ObjectStore/external/pegtl': checked out '3c4128a7e7e1288eb746418ea60c41477358f26a'
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: sync 1.0.0
```

Except the terminal is just silent and doesn't do anything. I'm in Switzerland on a stable internet connection (office - no restaurant or coffee shop...). I have downloaded previous versions of Realm with no problem. The last one I had was 2.1.0.

**Comment by jpsim** [comment]
I heard other reports of slow transfers from our AWS S3 bucket yesterday. Has the situation improved since then?

**Comment by svachmic** [comment]
Yeah, it works now - I just tried on the same network. Is this a recurring problem? I did troubleshoot my side first for an extensive period of time (system update, newest curl installation, cocoapods reinstall etc.), but it looks like I was just wasting my time. Maybe it could be noted in FAQ or somewhere where people could find it?

**Comment by shevakuilin** [comment]
This answer helped me!
