### ISSUE TITLE
Authentication example

### ISSUE THREAD

**Issue by grantspilsbury** [realm/realm-cocoa#4317]
Hi,
Do you have an example / recipe of a Realm app using (password, Google, Facebook) authentication?
Thanks,
Grant

**Comment by stel** [comment]
Hey @grantspilsbury! Yes!

Check out [RealmTasks](https://github.com/realm/realmtasks/). There is also a tutorial [Build iOS App from Scratch](https://realm.io/docs/realm-mobile-platform/example-app/cocoa/) and of course the [Authentication section in documentation](https://realm.io/docs/swift/latest/#authentication) should also be helpful.

**Comment by cliftonlabrum** [comment]
@grantspilsbury This may help: http://stackoverflow.com/questions/40618751/realm-sync-authentication-in-swift-version-2-0-4/40618752#40618752

**Comment by stel** [comment]
@grantspilsbury do you need any other help or can we close this issue?

**Comment by grantspilsbury** [comment]
You can close it. Thanks. 

On Nov 16, 2016, at 6:41 AM, Dmitry Obukhov <notifications@github.com> wrote:

@grantspilsbury do you need any other help or can we close this issue?

**Comment by revolter** [comment]
@stel, But, as far as I can see, there is no Facebook authentication example, with which I'm struggling ATM :(

**Comment by stel** [comment]
@revolter there is a PR https://github.com/realm/RealmTasks/pull/61 but it seems a bit outdated. Anyway I hope it can help you.

Please also check the docs at https://realm.io/docs/swift/latest/#authentication, all you need to do is to get Facebook token (the easies way is to use `FBSDKLoginKit`) and then use it to create `SyncCredentials`:

```Swift
let facebookCredentials = SyncCredentials.facebook(token: "Facebook token")
```

**Comment by revolter** [comment]
I read the docs and used:

    let facebookCredentials = SyncCredentials.facebook(token: FBSDKAccessToken.current().tokenString)

and then the `SyncUser.logIn` method calls the handler with the error:

> Error Domain=io.realm.sync Code=3 "(null)" UserInfo={statusCode=400}

There doesn't look that the `SyncUser.logIn` method is implemented in RealmTasks.

**Comment by jpsim** [comment]
@revolter have you enabled Facebook as an authentication provider for your instance of the Realm Object Server?

**Comment by revolter** [comment]
No, where is this described at in the documentation?

**Comment by revolter** [comment]
Oh, is it [this one](https://realm.io/docs/realm-object-server/#facebook)? I think I skipped that part, sorry :(

**Comment by revolter** [comment]
Though the error could have been a little more specific 😄
