### ISSUE TITLE
Can i encrypt the realm in iTunesShare?

### ISSUE THREAD

**Issue by demoker** [realm/realm-cocoa#4323]
Hi, Can i encrypt the realm in iTunesShare? But I don‘t want encrypt the realm when reading data and write data in code.

**Comment by jpsim** [comment]
Sure, you could use an unencrypted Realm in a non-iTunes accessible location, and when you're ready to share that file with iTunes, use [`-[RLMRealm writeCopyToURL:encryptionKey:error:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)writeCopyToURL:encryptionKey:error:) specifying the encryption key you want.
