### ISSUE TITLE
"Forget password" and "Reset password" feature are needed

### ISSUE THREAD

**Issue by khle** [realm/realm-cocoa#4325]
Currently, the Realm mobile platform does not provide a way to remind users if they forget password or allow users to reset password programmatically (there's a way to do in the dashboard however).  This would make the Realm mobile platform deficient.

**Comment by jpsim** [comment]
We're tracking this in realm/realm-mobile-platform#16, so I'll be closing this one as a duplicate. Please subscribe to that issue for any updates. Thanks!
