### ISSUE TITLE
IncorrectThreadException small improvements

### ISSUE THREAD

**Issue by kenji21** [realm/realm-cocoa#4328]
## Goals

Clearer error helping debugging threading issues

## Expected Results

App should be crashing with :
libc++abi.dylib: terminating with uncaught exception of type realm::IncorrectThreadException: Realm accessed from incorrect thread. (Created from Thread #1 "main thread", accessed from Thread #12 "unamed thread")

## Actual Results

App is crashing with :
libc++abi.dylib: terminating with uncaught exception of type realm::IncorrectThreadException: Realm accessed from incorrect thread.

## Steps to Reproduce

Accessing an realm from another thread than it have been created

## Version of Realm and Tooling

Realm version: v1.1.0

Xcode version: 8.1

iOS/OSX version: 10

Dependency manager + version: Carthage 0.18.1

**Comment by jpsim** [comment]
Thanks for the suggestion, @kenji21! We're already tracking this as #3350, so I'll be closing this ticket as a duplicate.
