### ISSUE TITLE
Use OC Realm in Swift with crash

### ISSUE THREAD

**Issue by dev-gao** [realm/realm-cocoa#4332]
There is a saying In realm doc:
> If you’re looking to use Realm from Objective‑C, or from mixed Objective‑C & Swift apps please see Realm Objective‑C instead. 

But when I use OC realm in swift. It appears bad access error:

`   
    DBHelper.swift

    import Foundation

    let chartDataBaseName = "chartDB.realm"

    class LDPMDataBaseHelper:NSObject {
    
    // MARK: - Public methods
    public class func setupDataBase() {
        self.createDataBaseWith(dbName:chartDataBaseName)
    }
    
    // MARK: - Private methods
    private class func dbFilePathWith(dbName:String) -> String
    {
        let docPath:String = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
        let filePath:String = docPath.appending("/\(dbName)")
        return filePath
    }
    
    private class func createDataBaseWith(dbName:String)
    {
        let filePath:String = self.dbFilePathWith(dbName: dbName)
        debugPrintLog("数据库 path : \(filePath)")
        let rlmConfig:RLMRealmConfiguration = RLMRealmConfiguration.default()
        rlmConfig.fileURL = URL.init(string: filePath)
        rlmConfig.readOnly = false
        let currentVersion = 1.0;
        rlmConfig.schemaVersion = UInt64(currentVersion)
        
        RLMRealmConfiguration.setDefault(rlmConfig)
    }
}`

When I call **setupDataBase** in AppDelegate method:
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`

It will crash with error of bad access.

Xcode8.1 , compile on release mode , real device: iphone7 / iphone6s plus / iphone6 plus.

**Comment by austinzheng** [comment]
Thanks for getting in touch. Does this happen on the Simulator? I wasn't immediately able to reproduce the problem.

If you could provide us with a reproduction case, or at least a stacktrace, we can look into this issue further.

**Comment by jpsim** [comment]
@dev-gao just following up on @austinzheng's last comment. Also a confirmation that the issue still occurs with the latest release ([2.1.1](https://github.com/realm/realm-cocoa/releases/tag/v2.1.1)) would be helpful.

**Comment by kishikawakatsumi** [comment]
@dev-gao I'm closing this issue because we haven't heard back from you in the last week, but please let us know if what we've posted here helped, and if you have any further questions or suggestions!
