### ISSUE TITLE
Update SyncUser.logIn to have a callbackQueue optional defaulted parameter

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#4338]
The sync login method callback runs on a background queue, which might be surprising behavior to those who expect it to run on the main queue. It might be a good idea to document this and/or allow the queue to be optionally specified.

**Comment by stel** [comment]
I like the idea of specifying the the queue explicitly (with default value).

Reposting @jpsim 's suggestion from #4364 here:
> What could be done, however, is providing an optional default argument of callbackQueue: DispatchQueue? = .main, since the vast majority of users will want to handle the callback on the main queue, but this still leaves the flexibility for users wanting to avoid that overhead to pass in callbackQueue: nil.

**Comment by austinzheng** [comment]
I think for our next breaking release, we should change the callback to just run on the main queue. Most of the time, the developer simply wants to immediately use the logged-in Realm user passed into the callback to configure their synced Realms. There are a number of features that require a run loop to function: auto-updating Realms, notification blocks, permission results, and we should make those use cases as foolproof as possible. In addition, this allows users to update their UI directly from the callback.

Given how infrequent a user log in should be, I don't think there is any real reason to try to optimize performance by allowing a queue to be specified.

**Comment by austinzheng** [comment]
In `master-3.0`.
