### ISSUE TITLE
RLMUtil RLMSetErrorOrThrow(NSError*, NSError* __autoreleasing*)

### ISSUE THREAD

**Issue by romainehinds** [realm/realm-cocoa#4339]
Hey can you guys help me with a weird random migration exception.
The model in question has properties that are all defined as floats.

RLMUtil.mm line 267
RLMSetErrorOrThrow(NSError*, NSError* __autoreleasing*)
Migration is required due to the following errors: - Property 'a' has been changed from 'float' to 'double'. - Property 'b' has been changed from 'float' to 'double'. - Property 'c' has been changed from 'float' to 'double'. - Property 'd' has been changed from 'float' to 'double'. - Property 'e' has been changed from 'float' to 'double'. - Property 'f' has been changed from 'float' to 'double'. - Property 'g' has been changed from 'float' to 'double'. - Property 'h' has been changed from 'float' to 'double'. - Property 'i' has been changed from 'float' to 'double'. - Property 'j' has been changed from 'float' to 'double'.

**Comment by bdash** [comment]
Are your properties declared as `float`, or `CGFloat`? The latter is a type alias for either `float` or `double` depending on the platform's architecture.

**Comment by romainehinds** [comment]
Hey thanks for replying so quickly. The properties are declared as CGFloat.

**Comment by bdash** [comment]
Our documentation on [supported data types](https://realm.io/docs/objc/latest/#supported-types) contains the following note:

> `CGFloat` properties are discouraged, as the type is not platform independent.

What happens is that on 32-bit devices the property ends up having type `float`, and when that Realm file is migrated to a 64-bit device an exception is thrown as it expects it to have type `double`.

I think you'd be able to address this by changing the property type to be one of `double` or `float`, and having a migration step that copies the value from the `CGFloat` property of the old object instances to the explicitly-typed property of the new object instances. This should result in all of your Realm files going forward having the same schema, irrespective of the underlying architecture.

**Comment by romainehinds** [comment]
Awesome thanks for the help so far so good!
