### ISSUE TITLE
pod realm failed

### ISSUE THREAD

**Issue by RenSihao** [realm/realm-cocoa#4342]
pod install Realm 2.0.4
core is not a symlink. Deleting...
Downloading dependency: sync 1.0.0-BETA-3.3
...
......
just loading.....no error message , it is just loading , i try some soulation by google, but it dosen't work

**Comment by bdash** [comment]
At that point it's downloading a prebuilt binary of Realm's core. It's roughly 45MB, so depending on your internet speed it may take a few minutes.

**Comment by RenSihao** [comment]
首先，非常感谢你的回答！刚开始我的想法跟你一样，但是我等了几乎两个小时，它还是卡在那里，我很困惑......

**Comment by RenSihao** [comment]
First of all, thank you very much for your answer! I started my thoughts just like you, but I waited for almost two hours, it was still stuck there, I was confused.....

**Comment by bdash** [comment]
We've had reports of people in China having difficultly downloading the prebuilt core binary. You can read more about that in #2713. Perhaps some of the suggested workarounds will work for you.

**Comment by RenSihao** [comment]
so, Use command line, like this:

curl https://static.realm.io/downloads/sync/realm-sync-cocoa-1.0.0-BETA-3.3.tar.xz -O
mkdir $TMPDIR/core_bin
mv realm-sync-cocoa-1.0.0-BETA-3.3.tar.xz $TMPDIR/core_bin

May be useful
yes？

**Comment by bdash** [comment]
Yes, with the exception that it's now `$TMPDIR/sync_bin` rather than `$TMPDIR/core_bin`.

**Comment by RenSihao** [comment]
Yeah, you're right, thank u very much! By the way, I used the VPN but still very slow, really very slow, about dozens of KB per second, a total of 48.8MB, very helpless.

**Comment by RenSihao** [comment]
I am curious, before I did not encounter such a slow situation, today is exceptionally slow, you can help me answer it?

**Comment by bdash** [comment]
It's hard to say. We've not changed anything about how we serve the files (CloudFlare) so presumably something has changed in the network route between your computer and CloudFlare.

**Comment by liuhongjun719** [comment]
Umbrella header 'Realmh' not found.  Why?

**Comment by liuhongjun719** [comment]
Umbrella header 'Realm.h' not found. Why?

**Comment by jpsim** [comment]
Closing as this issue has been inactive for some time. Please [open a new ticket](https://github.com/realm/realm-cocoa/issues/new) if you still have issues, taking care to fill out the new issue template and provide us with relevant information.
