### ISSUE TITLE
Downloading core failed:

### ISSUE THREAD

**Issue by WilliamXueShao** [realm/realm-cocoa#4347]
Installing Realm (1.0.2)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 1.3.1
Downloading core failed:
curl: (56) SSLRead() return error -9806

**Comment by jpsim** [comment]
Hi @WilliamXueShao, if you're downloading Realm from China, the GFW often prevents the network connection from being properly established. We're already tracking this in #2713, so I'll be closing this ticket as a duplicate. I apologize for the inconvenience.
