### ISSUE TITLE
filter value with unicode

### ISSUE THREAD

**Issue by cinnamon** [realm/realm-cocoa#4350]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

filter "name" property with Korean value.

## Expected Results

Should 2 objects after filter.

## Actual Results

Got only 1 object.

## Steps to Reproduce

1. service.name: 사업일 unicode: [49324, 50629, 51068] unicodeScalars: ["\u{C0AC}", "\u{C5C5}", "\u{C77C}"]
2. service.name: 사업일 unicode: [4361, 4449, 4363, 4453, 4536, 4363, 4469, 4527] unicodeScalars: ["\u{1109}", "\u{1161}", "\u{110B}", "\u{1165}", "\u{11B8}", "\u{110B}", "\u{1175}", "\u{11AF}"]

Add two objects with unicode, or unicodeScalars.

## Code Sample

First one added in code with "String" type from UITextField.
Second one added with name from file system (file name).
They looks same in Korean (by pring > service.name), but in filter method, they're not filtered as wished. Have no idea it's because of predicate (from Apple) or Realm side.

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?

2.1.0

Xcode version: ?

8.1 (8B62)

iOS/OSX version: ?

iOS : 10.1.1

Dependency manager + version: ?

Carthage v0.18

**Comment by kishikawakatsumi** [comment]
@cinnamon This issue is a limitation of both current Realm and NSPredicate. When filtering on external input values, it must be normalized before saving.

```
let service = Service()
service.name = inputText.precomposedStringWithCanonicalMapping
```

**Comment by cinnamon** [comment]
@kishikawakatsumi Yeah, that's what I did, thank you :)
