### ISSUE TITLE
RealmPlugin not installed in Xcode 8.1

### ISSUE THREAD

**Issue by malhobayyeb** [realm/realm-cocoa#4357]
RealmPlugin for Xcode 8.1 cannot be installed at all.

I have downloaded the latest RealmPlugin opened it in Xcode and 'Build' it then I restarted my Xcode.

No Realm menu item found in File menu.

**Comment by jpsim** [comment]
> Xcode 8 uses library validation. It won't load in-process plugins anymore.

Source: https://twitter.com/jckarter/status/742471686935568384

There's more in depth discussion on this here: alcatraz/Alcatraz#475
