### ISSUE TITLE
Best practices for updating existing objects

### ISSUE THREAD

**Issue by alexeychirkov** [realm/realm-cocoa#4360]
## Goals

The goal is to NOT receive a "modification" change when existing RLMObject with primaryKey is updated with the same property value as it has (e.g. the same string)

## Expected Results

"Modification" change is not received

## Actual Results

"Modification" change is received

## Steps to Reproduce

See below

## Code Sample

Assume that we have existing `TestEntity` with primaryKey '`testKey`' and name '`testName`'.

`TestEntity`
```
@interface TestEntity : RLMObject
@property NSString *primaryKey;
@property NSString *name;
@end

@implementation TestEntity
+ (NSString *)primaryKey {
    return @"primaryKey";
}
@end
```

`ViewController`
```
...
@interface ViewController ()
@property (nonatomic) RLMNotificationToken *notification;
@end

@implementation HomeViewController
- (void)viewDidLoad {
    [super viewDidLoad];
    //...
    @weakify(self);
    self.notification = [[[TestEntity allObjects] sortedResultsUsingProperty:@"name" ascending:YES] addNotificationBlock:^(RLMResults *data, RLMCollectionChange *changes, NSError *error) {
        @strongify(self);
        if (error) {
            //handle error
            return;
        }
        
        if (!changes) {
            //reload tableView
            return;
        }
        
        NSLog(@"insertions [%@], deletions [%@], modifications [%@]", [changes.insertions componentsJoinedByString:@","], [changes.deletions componentsJoinedByString:@","], [changes.modifications componentsJoinedByString:@","]);
    }];

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        //get existing TestEntity
        TestEntity *existing = [TestEntity objectForPrimaryKey:@"testKey"];
        //will output "existing entity: primaryKey = 'testKey', name = 'testName'"
        NSLog(@"existing entity: primaryKey = '%@', name = '%@'", existing.primaryKey, existing.name);
        //try to update existing entity with the same "name" value
        [TestEntity createOrUpdateInRealm:realm withValue:@{@"primaryKey": @"testKey", @"name": @"testName"}];
        [realm commitWriteTransaction];
    });
}

@end
```

As a result I get the following change output:
`insertions [], deletions [], modifications [0]`

I am confused, because property had the same value - it means that object was not changed.
Receiving "false positive" changes leads to unnecessary UI redraw (e.g. redraw of the tableView cell).

So we have two methods: `addOrUpdateObject` and `createOrUpdateInRealm`.
Is the following is true?
- `addOrUpdateObject` - this method ALWAYS add new object or replace existing which will lead to "insertions" or "modification" change

But what about `createOrUpdateInRealm` method?

How to achieve my goal?
Lets say I am refreshing the list of TestEntities from the server and want to store (update) this list to Realm. List is already stored in Realm, so it is possible that all entities are the same, list in sync already. How to update the list without getting "modifications" change?

What I do now:
- I've create a method `- (BOOL)isEqualToEntity:(TestEntity *)entity;` in `TestEntity` as analogue of `- (BOOL)isEqual:(id)object;` but without class name check
- Once list is received from the server - I create an array of unmanaged TestEntities
- Retrieve all existing TestEntities from Realm
- Iterate unmanaged TestEntities and check `isEqualToEntity` with existing stored TestEntities
- All unmanaged entities that are not equal (by comparing only properties) - are passed to `[realm addOrUpdateObjectsFromArray:unmanagedTestEntities];` method

## Version of Realm and Tooling

Realm version: Realm (2.1.0)

Xcode version: 8.1

iOS/OSX version: 10.11.6

Dependency manager + version: Cocoapods 1.0.1

**Comment by austinzheng** [comment]
Thanks for getting in touch. The behavior described in your ticket (modification notification even when the values are equal) is a known limitation, and we'd very much like to fix it eventually (see https://github.com/realm/realm-cocoa/issues/3489).

**Comment by alexeychirkov** [comment]
Thanks, I will close this issue
