### ISSUE TITLE
MacOS Synced Realm

### ISSUE THREAD

**Issue by natemann** [realm/realm-cocoa#4363]
in Realm 2.04, I had the following code to initialize a synced realm

```
    if let user = SyncUser.all().first {
        Realm.setDefaultConfiguration(withUser: user)
    }

    public static func setDefaultConfiguration(withUser user: SyncUser) {
        Realm.Configuration.defaultConfiguration = Realm.Configuration(syncConfiguration: (user, Server.realmURL), readOnly: false, schemaVersion: 15, migrationBlock: migrationBlock, deleteRealmIfMigrationNeeded: true)
    }
```

in 2.1.0, I changed the code to:

```
    if let user = SyncUser.all.first?.value {
            Realm.setDefaultConfiguration(withUser: user)
    }

    public static func setDefaultConfiguration(withUser user: SyncUser) {
        Realm.Configuration.defaultConfiguration = Realm.Configuration(syncConfiguration: SyncConfiguration(user: user, realmURL: Server.realmURL), readOnly: false, schemaVersion: 15, migrationBlock: migrationBlock, deleteRealmIfMigrationNeeded: true)
    }
```

Everything works fine in the iOS app with the above new code, but the macOS app constantly returns an empty Realm file. I have checked the realm configuration, and it appears to be pointing to the correct URL and is set up properly.

**Comment by stel** [comment]
Do you see any errors or any log messages? Can you share an example Xcode project that reproduces this issue?

**Comment by natemann** [comment]
@stel, I found my issue, I was fetching realm objects before the synced Realm was configured. Is there a way to get a notification after the realm is fully configured?

**Comment by stel** [comment]
Realm is fully configured as soon as you instantiate it with the valid (logged in) sync user. But note that `SyncUser.logIn` returns the user asynchronously in it's completion handler, so make sure you create Realm only after you get a valid user.

**Comment by stel** [comment]
@natemann do you need any further help here or can we close this issue?

**Comment by natemann** [comment]
@stel, No, your explanations helped. You can close the issue.  Thank you.
