### ISSUE TITLE
Model relationships can crash/thwart Model renaming migrations

### ISSUE THREAD

**Issue by cbess** [realm/realm-cocoa#4366]
## Goals

Rename a model from `BookmarkModel` to `Bookmark` (no `Model` suffix).

## Expected Results

That at the end of the migration, using `migrate.create(...)`, it would "move" the old model data to the new model schema.

## Actual Results

It crashed due to a duplicate `primaryKey` in one of the relationships. Basically, it tried to "create" every object (and nested objects) that was passed to `value`. I only wanted to "create" the `Bookmark`, but it instead attempted to "create" the `Tag` and then found a duplicate `primaryKey` (as it should, but not intended).

## Steps to Reproduce

Create a model that has a "to-many" relationship to another model (like tags), then migrate using `Migration.create`. Both model and related model must have a `primaryKey` field. Realm will attempt to create an entry for each object and fail because it sees a duplicate key for the "tags".

1. Create project using Realm that has two models
1. Make model A have a "to-many" relationship to model B (eg. BookmarkModel to Tags)
1. Change the name of model A to something else (eg. BookmarkData)
1. During migration "move" the data to the new Schema, effectively "renaming" the schema

## Code Sample

None

## Version of Realm and Tooling

Realm version: 2.1.0 (Swift)

Xcode version: 8.2

iOS/OSX version: iOS 10

Dependency manager + version: CocoaPods 1.1.0

**Comment by cbess** [comment]
Also, I saw #2499, which might have fixed my issue, because I'm **not** adding/removing properties, just changing the name. I tried moving it manually within the migration block, but when I "stored" the tags, it crashed when I tried to "copy" the `tags` to then assign them after the new schema object was created.

**Comment by stel** [comment]
Why do you create nested objects (Tags) again? Do you use `add(_:update:true)`/`create(_:update:true)` for creating this objects? Could you share the code of your migration block?

**Comment by cbess** [comment]
Sure thing, and thanks for your prompt response.

Please keep in mind this is for a **migration**. As far as I know, I don't have access to the `Realm` instance because I'm migrating the Realm. So, do I have access to the `Realm` instance (eg. `realm.create(_:update:)`) I'm migrating while inside of a migration block?

Code migration snippet:

```swift
private static let migrationBlock: MigrationBlock = { (migration: Migration, oldSchemeVersion) in
  // previous migrations above ...

  if oldSchemeVersion < 5 {
    // renamed BookmarkModel -> Bookmark
    migration.enumerate("BookmarkModel") { oldObject, newObject in
    // has the "to-many" relationship in a property named "tags"
    let value = newObject ?? oldObject!
      migration.create(Bookmark.className(), value: value)
    }
    migration.deleteData("BookmarkModel")
  }
}
```

**Comment by jpsim** [comment]
Hi @cbess, unfortunately migrations aren't aware of primary keys, which is why we don't have a `-[RLMMigration createOrUpdateObject:value:]` method. We're tracking adding that in #2162.

Also, there was work done over a year ago to add the ability to rename classes in migrations (#2499, tracked in #2491) specifically to make it easier to address more complex cases like your where relationships are involved. However, work on that was stalled and never resumed.

**Comment by cbess** [comment]
Thanks @jpsim for reviewing the issue. Mainly, I was hoping to have a way to skip the relationship or "nested" object creation. I didn't expect the `migration.create` to attempt to re-create relationships. 

I suppose that would be a feature request: 
```swift
migration.create(className: String, value: Any, traverse: Bool = true)
```
Perhaps?

**Comment by jpsim** [comment]
> I didn't expect the `migration.create` to attempt to re-create relationships.

You're creating the object, so relationships (_links_) need to be created because the object didn't exist before.

> ```swift
> migration.create(className: String, value: Any, traverse: Bool = true)
> ```

What is `traverse: Bool = true` traversing?

**Comment by jpsim** [comment]
@cbess is there anything more we can do to help you here?

**Comment by cbess** [comment]
@jpsim Thanks for reminding me to respond.

`traverse` means (google'd):
to iterate (go through each element (an element being a portion of data the size of whatever data type the array [or dictionary] holds))

So, the idea is that the dev would specify if the `create` should `traverse` the `value` (dictionary/object) to also create nested objects/refs (eg. tags, to-many relationships, etc).

**Comment by jpsim** [comment]
Thanks. I'm familiar with the _definition_ of the word "traverse". However, due to objects in a migration block not having primary keys, they can't be "create-or-update"-ed, which is where the #2162 feature request comes in. Without the "create-or-update" logic, what happens is that the object is always created, leading to the duplicate objects in your case.

It seems to me that you want exactly what #2162 provides, but we don't have that today. I think it'd be relatively straightforward to implement, if you're keen on building the feature yourself. We certainly appreciate contributions from the community!

That being said, is there a feature you're requesting that isn't covered by #2162?

**Comment by cbess** [comment]
No prob. I think we are almost on the same page, but I think I'm asking for something more trivial than the #2162. I'm asking for the `create` to *skip* a specified `key` as to not (in my case) recreate an existing object.

**Comment by jpsim** [comment]
> I'm asking for the `create` to _skip_ a specified key as to not (in my case) recreate an existing object.

Does if the object you pass to `create(value:)` doesn't KVC-respond for that key (e.g. if it's a dictionary without that key) the default value for that property will be used instead.

**Comment by cbess** [comment]
Agreed. That is apart of the difficulty. Is a valid Realm object that I want to be ignored because I don't want `create` to re-create it, which causes a *duplicate* key error to be thrown.

**Comment by jpsim** [comment]
I can't come up with a reasonable way to package the feature you're looking for. Besides, I think we'd be best to put our energies behind something like #2162, which would solve your issues, and would be a better fit for the rest of our API.

**Comment by cbess** [comment]
Understood. I'm really appreciate your questions and diligence. I concur with you, #2162 would be preferred.
