### ISSUE TITLE
Upgrading from 1.0.2 to 2.x takes very long

### ISSUE THREAD

**Issue by BObereder** [realm/realm-cocoa#4368]
Hi,
we are using realm in swift.
We recently ran into a huge performance issue when we updated from an older version of realm to a newer one.
Realm-Cocoa
old version: "realm/realm-cocoa" "v1.0.2"
new version: "realm/realm-cocoa" "v2.0.3"

It seems that upgrade_file_format  takes for ever ;(
We have quite some objects in our realm (couple of thousand), the more there are the longer it takes.
We had cases where it would take more than 1 minute.

Here is a screenshot of the instruments time profiler of Xcode:

![screen shot 2016-11-25 at 14 16 10](https://cloud.githubusercontent.com/assets/4548800/20626417/de958cb8-b319-11e6-9d2c-eae50d4b7671.png)

Is there anything we can do to prevent this? A user of the app does obviously not wait minutes for the app to launch.

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323

/Applications/XcodeAppstore.app/Contents/Developer
Xcode 8.1
Build version 8B62

/usr/local/bin/pod
1.2.0.beta.1


/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.18
github "realm/realm-cocoa" "v2.1.0"

/usr/local/bin/git
git version 2.10.0
```

**Comment by tgoyne** [comment]
Can you supply a Realm file which takes a very long time to upgrade? If you have a very large number of indexed string properties with a very large amount of data it is unsurprising that it would take a nontrivial amount of time to upgrade, but there's still probably quite a bit of room for improvement. If you can't post anything publicly but have files that you can share privately you can email it to `help@realm.io`.

**Comment by tgoyne** [comment]
[I've made a PR that should cut the upgrade time for similarly-sized Realms to at most a few seconds](https://github.com/realm/realm-core/pull/2326), which is still kinda awkwardly long but not utterly awful like a minute is.

**Comment by BObereder** [comment]
@tgoyne thanks a lot for your fast help. When can we expect that to be merged and usable for us?

**Comment by BObereder** [comment]
@tgoyne we also have huge performance issues with 

> realm.deleteAll()

is that somehow related?
Should I create another issue for this?

**Comment by tgoyne** [comment]
It's likely that the changes in that PR will also greatly improve the performance of `deleteAll()`.

**Comment by BObereder** [comment]
@tgoyne great! when can we expect that fix to be ready to use for us?

**Comment by tgoyne** [comment]
2.1.1 is now out with this fix.
