### ISSUE TITLE
Fail with query.

### ISSUE THREAD

**Issue by TheHmmka** [realm/realm-cocoa#4369]
## Goals

I want to get query works.

## Actual Results

Always get crash...
```
Terminating app due to uncaught exception 'Invalid property name', reason: 'Property 'New' not found in object of type 'Item''
```

## Code Sample

I have object with properties: 

```
dynamic var categoryTitle = ""
dynamic var isNew: Bool = false
```

Then I try to query them:
```
let realm = try! Realm()
newItems = realm.objects(Item.self).filter("isNew = \(true) AND categoryTitle = \(category.title)")
```

If I use next query - everything is work fine, but I need complex query:
```
newItems = realm.objects(Item.self).filter("isNew = \(true)")
```

Don't know why Realm search property with name New instead of isNew. May be it depends of Swift version - I use Swift 3.

## Version of Realm and Tooling

Realm version: 2.1.0

Xcode version: 8.1 (8B62)

iOS/OSX version: iOS 10.1

Dependency manager + version: CocoaPods

**Comment by stel** [comment]
It looks like the value of `category.title` is treated as property not the string. Try to specify your query like this:

```Swift
.filter("isNew = '\(true)' AND categoryTitle = '\(category.title)'")
```
or
```Swift
.filter("isNew = true AND categoryTitle = %@", category.title)
```

**Comment by TheHmmka** [comment]
Oh! Thanks! It's work.
But any way behavior is strange...

**Comment by stel** [comment]
Awesome! Learn more about queries in docs at https://realm.io/docs/swift/latest/#queries.
