### ISSUE TITLE
pod install 'RealmSwift' download an old version by default!!!

### ISSUE THREAD

**Issue by sadeghshahroodi** [realm/realm-cocoa#4373]
Hi. When i add pod 'RealmSwift' in my Podfile and run pod install, version 1.0.2 installed:
`pod install
Analyzing dependencies
Downloading dependencies
Installing Realm (1.0.2)
Installing RealmSwift (1.0.2)
Generating Pods project
Integrating client project
`

I'm writing a framework and want to add RealmSwift as a dependency in my podspec. I don't want use git version of RealmSwift in my podfile. 
After downloading Realm with git in pod (`pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master’,:submodules => true`
`pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master’,:submodules => true`) and execute pod cache list RealmSwift i got this:
`RealmSwift:`
`  - Version: 2.1.0`
`    Type:    External`
`    Spec:   ` `/X/Library/Caches/CocoaPods/Pods/Specs/External/RealmSwift/80adb4efaf6d5c44f9799c158623d6bb.podspec.json`
`    Pod:    ` `/X/Library/Caches/CocoaPods/Pods/External/RealmSwift/1fce24c94f905f943a226a4e96e7e9b9-4b361`
`  - Version: 1.0.2`
`    Type:    Release`
`    Spec:    /X/Library/Caches/CocoaPods/Pods/Specs/Release/RealmSwift/1.0.podspec.json`
 `   Pod:     /X/Library/Caches/CocoaPods/Pods/Release/RealmSwift/1.0.2-82f3a`

Can i use latest version via Pod 'RealmSwift' ?!

**Comment by austinzheng** [comment]
Please try running `pod repo update`, and then try installing Realm again. CocoaPods does not automatically keep its local pod metadata up to date.

**Comment by jpsim** [comment]
This is how CocoaPods works. Please see their [Master Spec-Repo Rate Limiting-Post Mortem](http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/) blog post for details.
