### ISSUE TITLE
Feature Request: RLMList should behave as a Set?

### ISSUE THREAD

**Issue by younata** [realm/realm-cocoa#4376]
## Goals

It would be pretty nice if I could add the same object to a List more than once, but it would ignore subsequent additions. Naively, I think it would improve performance instead of having to first check if an object exists in the list before adding it, or converting List to a Set then replacing the List with the set.

Maybe as a separate object entirely? I'm sure there are usecases for Realm where you want the double-appending.

## Expected Results

In the simple/naive case, if I have code that looks like:

```swift
class RealmObject: Object {
    let relatedObjects = List<RealmObject>()

    dynamic var id: String = UUID().uuidString
    override static func primaryKey() -> String? {
        return "id"
    }
}

let realm = try! Realm()
realm.beginWrite()

let first = RealmObject()
let second = RealmObject()

realm.add([first, second])

try! realm.commitWrite()

realm.beginWrite()
first.relatedObjects.append(second)
first.relatedObjects.append(second)
try! realm.commitWrite()
```

I would expect `first.relatedObjects` to contain a single reference to `second`. Right now, I get `[second, second]`.

Currently this is achieved with a naive check of contains before running, or (much more performant, by about 2 orders of magnitude):

```swift
let objects = Set(first.relatedObjects).intersection(objectsToAdd)
first.relatedObjects.removeAll()
first.relatedObjects.append(objectsIn: objects)
```

## Code Sample

https://github.com/younata/RealmPlayground

[RealmTesterTests.swift](https://github.com/younata/RealmPlayground/blob/master/RealmTesterTests/RealmTesterTests.swift) shows off a couple things I wanted to check.

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323

/Applications/Xcode.app/Contents/Developer
Xcode 8.1
Build version 8B62

/Users/you/.rbenv/shims/pod
1.0.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.18.1
github "realm/realm-cocoa" "v2.1.0"

/usr/bin/git
git version 2.9.3 (Apple Git-75)

Dependency manager + version: Carthage v0.18.1

**Comment by stel** [comment]
Thanks for suggestions, @younata!

`List` is container type that stores its values in an ordered list and used to define to-many relationships. This is the most general case. However, as you've already described, it's easy to achieve a uniqueness of the elements by checking if the object already exists in the list. You can also add convenient methods to your model for that:

```Swift
class RealmObject: Object {

    ...

    func addDistinct(_ object: RealmObject) {
        guard relatedObjects. index(of: relatedObject) == nil else {
            return
        }

        relatedObjects.append(object)
    }
}
```

Learn more about other collection types at https://realm.io/docs/swift/latest/#collections.

**Comment by jpsim** [comment]
We're tracking this as #1501, so I'll be closing this as a duplicate. Please subscribe to that ticket to be notified any discussions or progress.
