### ISSUE TITLE
Object has been deleted or invalidated.

### ISSUE THREAD

**Issue by Abel94** [realm/realm-cocoa#4377]
## Goals

Delete local old data and replace it with new data obtained from the network.

## Expected Results

The local data is deleted, and the Topic object contains only the data obtained from the network.

## Actual Results

Terminating app due to uncaught exception 'RLMException', reason: 'Object has been deleted or invalidated.'

## Steps to Reproduce

1, query all Topic object;
2, delete the query to get the Topic object;
3. Add a list of Topic objects obtained from the network.

## Code Sample

```swift
guard let topics = event.element?.toArray() else { return }
            
let realm = try! Realm()
let oldTopics = realm.objects(Topic.self)
            
try! realm.write {
    realm.delete(oldTopics)
    realm.add(topics, update: true)
}
```

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 2.1.0

Xcode version: 8.1 (8B62)

iOS/OSX version: iOS 10.1 (14B72)

Dependency manager + version: pod 1.0.1

**Comment by Abel94** [comment]
The problem has been solved because the Topic model data is bound to Tableview using `RxDatasources`. The dataSource uses `RxTableViewSectionedAnimatedDataSource`.

```swift
RxTableViewSectionedAnimatedDataSource<AnimatableSectionModel<String, Topic>>
```

The `AnimatableSectionModel` requires `Topic` to implement the `IdentifiableType` protocol.

Therefore, it may be IdentifiableType and Object have some conflicts.

Thank you all.

**Comment by ogrenich** [comment]
Hey,@Abel94. I have same goals. What is the best way to solve problem described by you?
