### ISSUE TITLE
About API Statbility

### ISSUE THREAD

**Issue by ahmedk92** [realm/realm-cocoa#4378]
I have a project that uses RealmSwift 1.0.2. I think it's a matter of a few weeks till I have to upgrade to the latest code and Swift (3). I've checked the latest RealmSwift (2.1.0); it seems the same API to me fortunately. My question is, what will happen if the API changes, or drastically changes in the future?

It may be a broad question, but I think this is worrisome.

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. We use [semantic versioning](http://semver.org/), so if you don't want to upgrade to a Realm version that changes the API in a breaking way, you can easily avoid doing so. (Breaking changes only occur when the major version number increments; e.g. 1 --> 2 between versions 1.0.2 and 2.1.0.)

We also try our best to avoid making breaking changes on a frequent basis, and to provide documentation (docstrings, change notes, API references) that assist users in migrating between versions. Hope that helps.

**Comment by ahmedk92** [comment]
Thanks for the reply.

I'm aware of that. The issue is I can't stick with for e.g. Swift 2.2 forever. For iOS development specific needs, xcode will eventually be updated (regardless I want or not), and thus I have to upgrade for example Swift 3 (if not 4, 5, ...etc in the future). The question here is, will I be able to use RealmSwift 1.0.2 with Swift 3 (and the latest iOS SDK)?

**Comment by stel** [comment]
No, it's not possible. Realm supports Swift 3 only starting from version 1.1.0.

**Comment by ahmedk92** [comment]
That's the answer @stel . Thanks.
