### ISSUE TITLE
realm encryption

### ISSUE THREAD

**Issue by skarctop** [realm/realm-cocoa#4383]
config.encryptionKey is 64 nsdata  

however i want to open the file (.realm) 
Prompted for password

please enter a valid encryption key for this Realm file
the encryption key must be entered as a 128-character string of hexadecimal values

but how to convert  config.encryptionKey to 128-character string of hexadecimal values

**Comment by stel** [comment]
Encryption key is an `NSData` object, so you can just make `NSString` object that represents this data as hexadecimal values, this StackOverflow question could be useful: http://stackoverflow.com/questions/7520615/how-to-convert-an-nsdata-into-an-nsstring-hex-string

**Comment by skarctop** [comment]
@stel 
think you, this very big help!!!
