### ISSUE TITLE
realm 2.1.0 beginWriteTransaction crash always said in a write transaction

### ISSUE THREAD

**Issue by WeeTom** [realm/realm-cocoa#4384]
I just updated realm framework for Objective-C for my iOS app.
It was all working fine in realm 1.0.0.
When I call [self method]; it will crash saying 

    *** Terminating app due to uncaught exception 'RLMException', reason: 'The Realm is already in a write transaction'

The code is like:

    - (void)method
    {
        [self methodA];
        [self methodB];
    }
    - (void) methodA {
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        object.key = A;
        [realm commitWriteTransaction];
    }
    - (void) methodB {
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        object.key = B;
        [realm commitWriteTransaction];
    }

But it works fine in old version.
Also this simple code works in a test project...
So I really can't judge what is wrong..

Note that I have also tried to add a judgment like:

        - (void) methodB {
            RLMRealm *realm = [RLMRealm defaultRealm];
            if (![realm isInWriteTransaction]) {
                [realm beginWriteTransaction];
            }
            object.key = B;
            [realm commitWriteTransaction];
        }

Yes, it goes in to call beginWriteTransaction, but still crashes!
So I have to use realm 1.0.0 back. Sadly I cannot use Realm App in Mac to browse data.

**Comment by stel** [comment]
@WeeTom the example code you posted looks fine to me, could you please share an example Xcode project that reproduces this issue?

**Comment by WeeTom** [comment]
Ops! My fault!
It was like:
I have set a token to observe the change of the objects.
But when I detected the change, I have another write transaction.
So the problem happens inside the notification block.
But it indeed works in realm 1.0.0.
I'll try to adapt to the new version. Thanks! @stel

**Comment by stel** [comment]
Happy to hear that you've solved your problem, @WeeTom!
