### ISSUE TITLE
Connection to Realm Object Server does not resume after starting app offline.

### ISSUE THREAD

**Issue by ugiacoman** [realm/realm-cocoa#4385]
## Goals

Start app offline, add an item, go back online, syncing across devices resumes. Not sure if this is a bug or the intended use. If it is intended, is there a way to retry the connection to the server without calling authenticate again? Thanks!

## Expected Results

As soon as app comes back online, resume syncing across devices.

## Actual Results

No sync occurs / connection to object server not attempted.

## Steps to Reproduce

Using the realmTasks app you can reproduce this error by doing the following. Using multiple devices is necessary (or simulator and one physical device) to observe the syncing. Alternatively, you can watch through the Realm Browser.

1) Logging in
2) Create an item
3) Kill the app
4) Open app
5) Create item
6) Go online
7) Wait for sync (doesn't happen)

Realm version: 2.1.0

Xcode version: 8.1

iOS/OSX version: 9.3

Dependency manager + version: CocoaPods RealmSwift 2.1.0

**Comment by stel** [comment]
Realm uses incremental backoff in order to reconnect if the connection was lost. So after a long time being offline there could be a delay before the next attempt to connect. There is no API to force retry the connection right now, but most likely it should be implemented in some way.

**Comment by ugiacoman** [comment]
Interesting, the way I'm circumventing this delay is by having a connectivity listener, logging out, and re-authenticating with realm when internet connection is restored.

**Comment by stel** [comment]
@ugiacoman yes, currently it should work and is probably the only workaround for that.
