### ISSUE TITLE
filter with argument NotFound but return Success with No argument 

### ISSUE THREAD

**Issue by AlasKuNull** [realm/realm-cocoa#4395]
I sort object Success.

NSInteger indx = [res indexOfObjectWhere:@"BarCode = %@ AND Type = 'Old'",model.barCode];
This Code return NotFound.

NSInteger indx = [res indexOfObjectWhere:@"BarCode = '1234' AND Type = 'Old'"];
But This Code return 1

please help me,Thanks

**Comment by stel** [comment]
Hi @AlasKuNull!

What does `model.barCode` return? Is it string or the number?

**Comment by AlasKuNull** [comment]
Thanks a lot！I fixed it.
when i NSLog model.barCode，it return expect string,but when I catch it in breakpoint,I found unexpected "\x1d" in the string. I replace it and fixed the bug.
Thank for your reply!


发自网易邮箱大师
On 12/01/2016 23:25, Dmitry Obukhov wrote:

Hi @AlasKuNull!

What does model.barCode return? Is it string or the number?

**Comment by stel** [comment]
Awesome!
