### ISSUE TITLE
Inserting objects with nested relationships rapidly inflates the database size

### ISSUE THREAD

**Issue by jasper-chan** [realm/realm-cocoa#4396]
> **Bugs**: We have discovered that if you try to insert an object such that has a relationship with another object, it will greatly increase the database file size. We have been able to reproduce the problem at will in our production app. We are happy to provide a video/Skype/whatever to help you better understand the situation, and provide anything else necessary to help the Realm team resolve this critical issue.

## Goals

What do you want to achieve?
File size should increase at a reasonable amount.

## Expected Results
Using Realm Framework v1.x, the database size would increase to 1MB. We are expecting a similar file size increase.

## Actual Results
With Realm Framework v2.1.0, the database size increases to 18.9MB with the same operation

## Version of Realm and Tooling
Realm version: Realm Version 2.1.0

Xcode version: 7.3

iOS/OSX version: iOS 9.3

**Comment by bdash** [comment]
Hi @jasper-chan, can you share a code snippet that demonstrates the problem?

**Comment by jasper-chan** [comment]
Hello @bdash 
Would it be alright if I emailed you screenshots/video? Its a bit difficult to share just a snippet of it as I feel like you would need a larger context in order to understand what the method is doing.

**Comment by bdash** [comment]
I don't find screenshots and videos to be a particularly effective mechanism for sharing code. If you're unable to demonstrate the problem via standalone test code, feel free to share any code snippets you'd like kept private via email to help@realm.io.

**Comment by jasper-chan** [comment]
@bdash I just sent an email with a brief explanation of the situation. I have also included the header file of our data models to give you proper information regarding what our realm objects look like. I can also provide the realm file if that will help in your investigation. Please advise what else I can do to assist you in this matter.

**Comment by jasper-chan** [comment]
@bdash I sent @TimOliver an email over the weekend with more code and explanation to help explain this situation. If you could kindly connect with him to get the information, it might be of significant help to helping you resolve this issue.

Thanks!

**Comment by jpsim** [comment]
You might be interested in the discussion in realm/realm-core#2343.

**Comment by jasper-chan** [comment]
@jpsim Based on our discussions via email with Tim Oliver, it seems like 2343 is the issue we are experiencing. Is there any information regarding if 2343 will be pushed higher up in priority? Or what the timeline is for this enhancement?

**Comment by jpsim** [comment]
You're best to coordinate with @finnschiermer in realm/realm-core#2343 on that. I'll be closing this issue since the best place to continue this conversation will be in realm/realm-core#2343. I hope you'll be active in those conversations.
