### ISSUE TITLE
Follow up with affected users once core 2.2.0 is included in a release

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#4397]
Core 2.2 supposedly addresses all these issues:

* realm/realm-core#2269
* realm/realm-core#2289
* realm/realm-core#2290
* realm/realm-core#2292
* realm/realm-core#2293
* realm/realm-core#2295
* realm/realm-core#2301
* realm/realm-cocoa#4238
* realm/realm-cocoa#4387

Once we cut a cocoa release including this version of core, we should take the time to follow up with the affected users tracked in all those tickets and inform them about the new release available.

**Comment by rex-remind101** [comment]
@jpsim did this get into 2.1.1?

**Comment by jpsim** [comment]
Yes, Realm Cocoa 2.1.1 includes core 2.2.0. See the release notes here: https://github.com/realm/realm-cocoa/releases/tag/v2.1.1

This ticket is more of a meta-issue tracking following up with affected users (such as yourself).

**Comment by jpsim** [comment]
I've reached out to everyone who contacted us about this.
