### ISSUE TITLE
Realm refresh() is slow after moving to 2.1.0

### ISSUE THREAD

**Issue by f3n1kc** [realm/realm-cocoa#4402]
## Goals

Using Realm write on background thread and refreshing manually on main thread

## Expected Results

Realm.refresh will not affect UI performance

## Actual Results

UI is constantly freezing

## Steps to Reproduce

After upgrading from 1.1.0 to 2.1.0 app started to freeze on every write and update. All write operations are performed on serial queue, and after that refresh() is called on main thread. After switching from 1.1.0 to 2.1.0 I saw, that my app was freezing inside that part of code:

```
template<typename Pred>
std::unique_lock<std::mutex> RealmCoordinator::wait_for_notifiers(Pred&& wait_predicate)
{
    std::unique_lock<std::mutex> lock(m_notifier_mutex);
    bool first = true;
    m_notifier_cv.wait(lock, [&] {
        if (wait_predicate())
            return true;
        if (first) {
            wake_up_notifier_worker();
            first = false;
        }
        return false;
    });
    return lock;
}
```

Switching back to 1.1.0 solves problem (tried several times switching between 1.1.0 and 2.1.0). It freezes even if I try to insert / update one item into huge DB (20k+ records). I will try to replicate problem in new project once I have more time, but thought maybe you already know about that issue. 

## Version of Realm and Tooling

Realm version: RealmSwift (1.1.0) and RealmSwift (2.1.0)

Xcode version: Xcode 8.0, Build version 8A218a

iOS/OSX version: iOS 10

Dependency manager + version: git version 2.8.4 (Apple Git-73)

**Comment by tgoyne** [comment]
Prior to 2.1.0, calling refresh() will cause any collection notifications which are not ready for delivery to simply be skipped (and the block will never be called), while in 2.1.0 it will wait for them to be ready. If you have not added any notification blocks to any Results or Lists, the behavior should be the same in both versions.

**Comment by f3n1kc** [comment]
Thanks for quick response.

I followed suggestion from that issue https://github.com/realm/realm-cocoa/issues/3049. As I understood, best practice is to have async write to not block UI and and refresh() on main(?) thread.

```
so instead of performing a new fetch, you should just need to call the refresh() method on the Realm() object in that thread, and the Results() objects should update on your behalf
```

But now it appears, that refresh() blocks UI as well. What I am trying to archive is to have async write and completion block to know, when exactly this operation was completed (and using notification blocks in others parts of app). Is there any way to do it without blocking UI?

**Comment by jpsim** [comment]
> Is there any way to do it without blocking UI?

@tgoyne's comment just above mentions exactly how to do that: you can either not call `refresh()` or remove the notification blocks on `Results` or `List`s.

However, in general I think you may be using the wrong architecture for this. The whole point behind change notifications is that you can react to changes no matter where they originate from: other threads, processes, or even devices. Having a single point of change handling helps simplify and localize code.

In your case, it sounds like you're using both change notifications, as well as a callback mechanism to be notified when changes are available in other ways. I suggest you reconsider this architecture to simplify it to use this single point of change handling concept.

You can learn more about how to architect apps to be reactive and notification-based in our recent series of articles ending with [Live Objects and Fine-Grained Notifications: Updates with Realm](https://realm.io/news/live-objects-fine-grained-notifications-realm-update/).

**Comment by kharmabum** [comment]
@tgoyne I know this isn't pretty and probably not a pattern you're trying to encourage, but won't the following ensure that the `block` provided is always invoked on the main thread after the main thread's realm has refreshed with all previously completed write transactions:

```
static func executeOnMainThread(_ block: @escaping VoidClosure) {

        // Move to main thread
        DispatchQueue.main.async {

            var didComplete = false
            let complete: (()->Void) = {
                guard !didComplete else { return }
                didComplete = true
                
                // Invoke block
                block()
            }
            
            // Observe write commit on main thread
            var token: RealmSwift.NotificationToken? = nil
            token = Model.realmStore?.addNotificationBlock { _, _ in
                token?.stop()
                complete()
            }
            
            // In the event no transactions are pending ensure a write commit event is triggered
            DispatchQueue.global(qos: .userInitiated).async() {
                autoreleasepool(invoking: {
                    guard let realm = Model.realmStore else { return }
                    realm.beginWrite()
                    try? realm.commitWrite()
                })
            }
        }
    }
```
