### ISSUE TITLE
RealmModels from Framework Show up in default/other realms

### ISSUE THREAD

**Issue by kevinmlong** [realm/realm-cocoa#4406]
I have a project that uses a framework that has RealmSwift as a dependency. The project only defines one Realm model. After writing to the Realm (with a unique name - e.g. feedback.realm) and opening this Realm in RealmBrowser, it shows the added object as well as all the models (all 0 records) from the included framework's Realm.

## Expected Results
Realm files should only have models/objects that are written to them

## Actual Results
Any model/object that in the project (even those model definitions defined in dependencies) are contained in Realms created within the project.

## Version of Realm and Tooling

Realm version: 2.0.3
Xcode version: 8.1
iOS/OSX version: 10.1

**Comment by jpsim** [comment]
That's what [`+[RLMObject shouldIncludeInDefaultSchema]`](https://github.com/realm/realm-cocoa/blob/v2.1.0/Realm/RLMObjectBase.h#L36-L37) is for.

**Comment by kevinmlong** [comment]
@jpsim - could you please elaborate on this? How should someone utilize this in RealmSwift? The documentation isn't very clear on this, at least from what I could find in a quick look through it. Thanks!

**Comment by kevinmlong** [comment]
Disregard - I figured it out.

In Realm.Configuration you can specify the objects to be managed in the Realm as shown below:

```swift
var config = Realm.Configuration()
config.objectTypes = [MyRealmObjectClass.self]
```

**Comment by jpsim** [comment]
This is already documented in Realm Swift's docs: https://realm.io/docs/swift/latest/#class-subsets

> In some scenarios you may wish to limit which classes can be stored in a specific Realm.
> For example, if you have two teams working on different components of your application which both use Realm internally, you may not want to have to coordinate [migrations](https://realm.io/docs/swift/latest/#migrations) between them.
> You can do this by setting the `objectTypes` property of your `Realm.Configuration`:
>
> ```swift
> let config = Realm.Configuration(objectTypes: [MyClass.self, MyOtherClass.self])
> let realm = try! Realm(configuration: config)
> ```

**Comment by kevinmlong** [comment]
Fair enough. I clearly missed that. Thanks!
