### ISSUE TITLE
Compile error after upgrading Realm to 2.1.1 with Carthage

### ISSUE THREAD

**Issue by xiaodao** [realm/realm-cocoa#4409]
## Actual Results

XCode report compile error on this line:

`#if __has_attribute(ns_error_domain) && (!__cplusplus || __cplusplus >= 201103L)`

in `RLMConstant.h` with error message:

`__cplusplus is not defined, evaluates to 0`

## Version of Realm and Tooling

Realm version: 2.1.1 (Realm Objective-C)
Xcode 8.0: Build version 8A218a
Swift Version: 2.3
Carthage version: 0.15.2
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

**Comment by stephenyao** [comment]
I'm also having the same issue, did you get it resolved by any chance? Any help is appreciated. Thanks.

**Comment by jpsim** [comment]
This can happen if you're compiling Realm with custom compiler flags such as `-Wundef`. This flag is also included in `-Weverything`.

This is a harmless warning, but could cause Realm not to compile if you also have the `-Werror` flag (treat warnings as errors). In the short term, you can simply not use those compiler flags when building Realm. In the long term, we might want to widen the warnings settings we build with to minimize the chances of users with different settings running into issues.

**Comment by xiaodao** [comment]
@jpsim thanks a lot, I'll try it and get back to you later

**Comment by xiaodao** [comment]
@jpsim we have a `-Werror` flag in project build settings, is it possible to only use `-Wno-error` flag for the Realm framework? Thanks.

**Comment by jpsim** [comment]
> is it possible to only use `-Wno-error` flag for the Realm framework? Thanks.

Sounds like you want to use that flag everywhere _but_ Realm.framework...

**Comment by xiaodao** [comment]
Yes,

**Comment by jpsim** [comment]
> btw, we were using `carthage update`, not `carthage update --no-use-binaries`

That's of no significance when dealing with defines in the headers.

> Sounds like you want to use that flag everywhere but Realm.framework...

This is entirely dependent on your project's build configuration and out of our hands. You can ask general programming forums for advice on how to configure your project's build settings to achieve the results you want.

**Comment by xiaodao** [comment]
cool, I'll try that

**Comment by xiaodao** [comment]
couldn't find any solution, I have to wait for the release of this fix: https://github.com/realm/realm-cocoa/pull/4418

**Comment by jpsim** [comment]
@xiaodao rather than wait for us to make a release to accommodate the non-standard compiler flags you use in your project, perhaps you could just remove those flags from your Xcode project's build settings in the meantime?
