### ISSUE TITLE
Why does 2.1.1. not include Realm Swift? 

### ISSUE THREAD

**Issue by bensarz** [realm/realm-cocoa#4413]
## Goals

Not having to compile Realm when installing Carthage dependencies.

## Expected Results

Download the 2.1.1 binary, which includes RealmSwift

## Actual Results

The 2.1.1 binary only includes ObjC

## Steps to Reproduce

```ruby
github "realm/realm-cocoa"
```

```zsh
$ carthage bootstrap --platform iOS
```
## Version of Realm and Tooling

Realm version: 2.1.1

Xcode version: 8.1

Dependency manager + version: Carthage 0.18.1

**Comment by jpsim** [comment]
Looks like our 2.1.1 release process from last week didn't fully complete. Appears to be missing carthage binaries and the `realm-swift-2.1.1.zip` archive from GitHub releases. Looks like everything else in the release worked though.

I'll fix up the GH release assets now.

**Comment by jpsim** [comment]
Fixed: https://github.com/realm/realm-cocoa/releases/v2.1.1.

**Comment by bensarz** [comment]
@jpsim thanks for being so fast on this!

**Comment by jpsim** [comment]
No problem. It's all automated. But automation can sometimes fail. In this case, we got a 502 error when uploading the assets to the GitHub release, and didn't notice. Thanks for reporting this!
