### ISSUE TITLE
Can't build realm at all

### ISSUE THREAD

**Issue by iosdevben** [realm/realm-cocoa#4416]
## Goals

Build realm according to the readme.

## Expected Results

No compilation errors.

## Actual Results

Compiler errors, such as the following:
```
clang: error: no such file or directory: '/Users/Ben/Downloads/realm-cocoa-master/Realm/ObjectStore/src/impl/collection_change_builder.cpp'
clang: error: no input files
```
## Steps to Reproduce

1. Download the ZIP from Github
1. Unzip it
1. cd into the top level directory `realm-cocoa-master`
1. Run `build.sh build` at the command line

## Version of Realm and Tooling

Realm version: 

https://github.com/realm/realm-cocoa/archive/master.zip

Xcode version:
8.1

iOS/OSX version:
10.12.1

Dependency manager + version: none

**Comment by jpsim** [comment]
Looks like you're missing a step from the prerequisites section: https://github.com/realm/realm-cocoa#building-realm

> If cloning from git, submodules are required: `git submodule update --init --recursive`.

**Comment by iosdevben** [comment]
> If cloning from git

I've downloaded the zip, not cloned from git, so that step does not apply.

**Comment by bdash** [comment]
The zip file that you linked to is a snapshot of the current head of the master branch of the realm-cocoa repository. It does not contain submodules. I'd suggest cloning the repository using git instead so that you can easily download the submodules.

**Comment by jpsim** [comment]
Right. Perhaps we could adapt that prerequisite point:

```diff
-* If cloning from git, submodules are required: `git submodule update --init --recursive`.
+* Git submodules are required: `git submodule update --init --recursive`. If not using git, obtain these submodules another way.
```
