### ISSUE TITLE
Share encrypted realm database between app container and today extension

### ISSUE THREAD

**Issue by adrianodiasx93** [realm/realm-cocoa#4417]
## Goals

What do you want to achieve?
Share encrypted realm database between app container and today extension

## Expected Results

What did you expected to happen?
Collect data from database in the today extension controller.

## Actual Results

What did happened instead?

Crash

```fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/Users/adrianodias/Library/Developer/CoreSimulator/Devices/F45934BB-247A-4A28-8132-CAB4D252E776/data/Containers/Shared/AppGroup/FE61E7E0-D378-4DE0-8B89-49E1CAFEB3AF/Library/Caches/default.realm': Realm file decryption failed.” ```

```UserInfo={Error Code=2, NSFilePath=/Users/adrianodias/Library/Developer/CoreSimulator/Devices/F45934BB-247A-4A28-8132-CAB4D252E776/data/Containers/Shared/AppGroup/FE61E7E0-D378-4DE0-8B89-49E1CAFEB3AF/Library/Caches/default.realm, Underlying=Realm file decryption failed,```

```NSLocalizedDescription=Unable to open a realm at path '/Users/adrianodias/Library/Developer/CoreSimulator/Devices/F45934BB-247A-4A28-8132-CAB4D252E776/data/Containers/Shared/AppGroup/FE61E7E0-D378-4DE0-8B89-49E1CAFEB3AF/Library/Caches/default.realm': Realm file decryption failed.}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.58.6/src/swift/stdlib/public/core/ErrorType.swift, line 178```

## Steps to Reproduce

What are steps we can follow to reproduce this issue?
Invoke realm object by calling `RealmManager.getRealm()` from today extension controller.

Previously, I've done the following steps: 

-  Unable app groups it in both targets with same identification `group.com.myapp`.

-  add the model, and the class `RealmManager` which  `getRealm()` belongs as `Compile Sources`.

The crash only happens when I set the `encryptionKey` in `Real.Configuration`. I am not sure why since the app container also invokes `RealmManager.getRealm()` and there's no crash. Every time `getKey` gets called it looks for key in the keychain, if there's no key it creates a new key and stores it in the keychain.

## Code Sample

```
 class func getRealm() -> Realm {
        let fileURL = FileManager.default
            .containerURL(forSecurityApplicationGroupIdentifier: "group.com.myapp")!
            .appendingPathComponent("Library/Caches/default.realm")
        let configuration = Realm.Configuration(fileURL: fileURL, encryptionKey: getKey() as Data)
        let realm = try! Realm(configuration: configuration)
        return realm
    }
```

## Version of Realm and Tooling

Realm version: ?
2.0.4
Xcode version: ?
8.1
iOS/OSX version: ?
macos Sierra
Dependency manager + version: ?
carthage 0.17.2

**Comment by jpsim** [comment]
Sharing encrypted Realms between processes is something we'd like to enable, but isn't possible for now. We're tracking this functionality in #1693, so I've marked this ticket as a duplicate and would encourage you to subscribe to the original one and continue the conversation there.

The feature would require changes to Realm's core: realm/realm-core#1845

**Comment by alinradut** [comment]
Oof 😳 

I've been using Realm for the last 8ish years and this is the first time I've heard this, read only mode was the only way to use an encrypted Realm in an extension. 

Is there an alternative? 

I see that multiprocess encryption has finally been added, I'll also give that a try.
