### ISSUE TITLE
Filter/query doesn't work

### ISSUE THREAD

**Issue by danipralea** [realm/realm-cocoa#4426]
## Goals

Filter/query an object

## Expected Results

Have the object returned

## Actual Results
The object is returned, but with default values

## Steps to Reproduce

Call my filter function
```swift
self.channel = DatabaseManager.channel(with: channelId)
```

## Code Sample

Model:

```swift
class func channel(with id:Int) -> MSChannel? {
        let realm = try! Realm()
        let predicate = NSPredicate(format: "identifier = %d", id)
        let channels = realm.objects(MSChannel.self).filter(predicate)
        let array = Array(channels)
        return array.first
    }
```

## Version of Realm and Tooling

Realm version: 2.1.0

Xcode version: 8.1

iOS/OSX version: iOS 9

Dependency manager + version: Cocapods 1.1.1

I tried querying all objects, and they all come as default:
![screenshot 2016-12-09 02 22 04](https://cloud.githubusercontent.com/assets/768893/21033024/57af4a98-bdb6-11e6-8de8-aca7877ca359.png)

And my fetched object, is, of course, also a default one:
![screenshot 2016-12-09 02 23 10](https://cloud.githubusercontent.com/assets/768893/21033039/791beeca-bdb6-11e6-85b5-517ef06da508.png)

And my objects actually exist (queried with Realm Mac OS app):
![screenshot 2016-12-09 02 25 06](https://cloud.githubusercontent.com/assets/768893/21033081/c1481246-bdb6-11e6-9a7f-30ca9bd3a508.png)

And yes, all properties on my model are dynamic
```swift
class MSChannel: Object, Mappable {
    
    dynamic var identifier: Int = MappingDefaultIdentifer
    private dynamic var privateSection = MSChannelSection.none.rawValue
    var section: MSChannelSection {
        get { return MSChannelSection(rawValue: privateSection)! }
        set { privateSection = newValue.rawValue }
    }
    
    private dynamic var privateType = MSChannelType.none.rawValue
    var type: MSChannelType {
        get { return MSChannelType(rawValue: privateType)! }
        set { privateType = newValue.rawValue }
    }
    
    dynamic var name: String?
    dynamic var descriptionString: String?
    dynamic var context: MSChannelContext?
    dynamic var membersCount: Int = 0
//    dynamic var tags: [String]? // Channel Details
    dynamic var isPrivate = false
    dynamic var createdAt: Date?
    dynamic var directMessageEntity: Entity?
    dynamic var owner: Entity?
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    override class func primaryKey() -> String? {
        return "identifier"
    }
    
    func mapping(map: Map) {
        if identifier == MappingDefaultIdentifer {
            identifier              <- map["id"]
        }
        section                 <- (map["section"], EnumTransform<MSChannelSection>())
        type                    <- (map["channel_type"], EnumTransform<MSChannelType>())
        name                    <- map["name"]
        descriptionString       <- map["description"]
        context                 <- map["entity_context"]
        membersCount            <- map["entity_count"]
//        tags                    <- map["raw_tags"]
        isPrivate               <- map["is_private"]
        createdAt               <- (map["created_at_ts"], DateTransform())
        directMessageEntity     <- map["direct_message_entity"]
        owner     <- map["owner"]
    }
}
```

**Comment by kishikawakatsumi** [comment]
@danipralea It's intended behavior. Realm does not copy any data until actually access the properties. When access the properties, Realm fetch the data directly from its file. So Realm does not store any data to its ivar. That's why you cannot see any values via the debugger.

Can you make sure that an output of `print(self.channel)` is correct?

**Comment by danipralea** [comment]
@kishikawakatsumi thank you for your reply

no, it's not correct. If I try to print it, I get `*** Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'`

**Comment by danipralea** [comment]
I also tried only passing the `id` and then fetch for the `channel` entity again from the realm, but it still fetches a default object

```swift
var channel: MSChannel?
    var channelId: Int = MappingDefaultIdentifer {
        didSet {
            self.channel = DatabaseManager.channel(with: channelId)
            print(self.channel) // This is where it crashes
        }
    }
```

**Comment by kishikawakatsumi** [comment]
@danipralea How to convert `Results` to `Array` is:

```
let channels = realm.objects(MSChannel.self)
let channelArray = Array(channels)
```

or 

```
let channels = realm.objects(MSChannel.self)
let channelArray = channels.map { MSChannel(value: $0) }
```

The difference is that the latter is that each element is detached from Realm on the latter.

However, we strongly recommend using `Results` directly as a data source. Because converting `Results` to `Array` loses the advantages of Realm objects such like auto-update, zero-copy and lazy loading.

**Comment by danipralea** [comment]
converting them to array is the actual cause of my crash

The thing is that I need to support server loading as well. and those objects come inside an array

**Comment by kishikawakatsumi** [comment]
It should work. @danipralea Can you please share reproducible project?

**Comment by danipralea** [comment]
The reproducible code is all here, @kishikawakatsumi. I couldn't share the project.

**Comment by jpsim** [comment]
@danipralea Xcode has this very nifty feature where it can set a symbolic lldb breakpoint to break when an exception is thrown. This is super useful for debugging what part of your code is mutating a property outside of a Realm transaction. http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions

**Comment by danipralea** [comment]
Thank you very much for your suggestion @jpsim

**Comment by danipralea** [comment]
that.... didn't helped @jpsim 😢

**Comment by jpsim** [comment]
what do you mean that didn't help? if no exception is being thrown, than this report is incorrect. Is the breakpoint not being hit? Then it might be an issue with how you're setting it up in Xcode. Make sure it's not disabled and that the "automatically continue after breakpoint" checkbox isn't set.

If that's not what you mean by didn't help, please explain.

**Comment by danipralea** [comment]
I don't get the crash on the line that crashes it and no extra information either. I've set ip up exactly like in the article you sent

**Comment by jpsim** [comment]
> I don't get the crash on the line that crashes it and no extra information either. I've set ip up exactly like in the article you sent

You don't get a crash when you get the crash? That's contradictory.

In an earlier comment, you mentioned that you're not getting a crash, but rather an uncaught exception:

> `*** Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'`

If this is still the same problem you're debugging, you can use an exception breakpoint to detect when this exception is being thrown...
