### ISSUE TITLE
Update instead of insert when user close keyboard

### ISSUE THREAD

**Issue by carmelo-ruota** [realm/realm-cocoa#4430]
I created a chat using XMPP,  and Realm for storing messages. 
When the user press the "send message" button, I write an object on realm and  I receive an insert notification, so I can update the tableview UI.
But I have this problem: if the user close the keyboard by RETURN key, and then tap on "send message" button, Realm notify me an update instead of an insert and this cause me an NSInternalInconsistencyException.

Recap: 
- User press "send" with keyboard visible -> All works right!
- User press "send" after closing keyboard -> NSInternalInconsistencyException caused by update instead insert notification

**Comment by kishikawakatsumi** [comment]
@carmelo-ruota Can you show me your code? I do not know what is different in each cases.

**Comment by bmunkholm** [comment]
@carmelo-ruota Please fill out the template we provide when you open an issue, so we can better help.

**Comment by TimOliver** [comment]
Hi @carmelo-ruota!

I'm sorry, but we need a lot more information from you before we can help.

If you're still having trouble, can you please re-open this issue, go back and properly fill out the template we provided with all of the information requested in it?

Additionally, if you can show us your code responsible for receiving the callback events from the keyboard and performing the Realm write transaction, that would help a lot.

Thanks! Have a happy holiday!
