### ISSUE TITLE
How to add an object without a primary key (but has one mapped)

### ISSUE THREAD

**Issue by danipralea** [realm/realm-cocoa#4432]
## Goals

I have a `Message` entity. with an **identifier** as a primary key. But the messages recently sent do not have an **identifier**, but a **temporaryIdentifier**, and after it comes from the server, I have a valid **identifier**. But until then, I need to be able to add it to the realm.

I also tried with `update` set to `false`, but I get the same error.

## Expected Results

I want the object to be added to the realm

## Actual Results

```*** Terminating app due to uncaught exception 'RLMException', reason: 'Can't create object with existing primary key value '2'.'```

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample
```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Can't create object with existing primary key value '2'.'
```

```swift
class Message: Object, Mappable {
    dynamic var identifier: Int = MappingDefaultIdentifer
    dynamic var temporaryIdentifier: String?
    dynamic var channelId: Int = MappingDefaultIdentifer
    dynamic var text: String?    
    dynamic var createdAt: Date?
    dynamic var deletedAt: Date?
    dynamic var sender: Entity?
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    override class func primaryKey() -> String? {
        return "identifier"
    }
    
    func mapping(map: Map) {
        identifier              <- map["id"]
        temporaryIdentifier     <- map["temporary_identifier"]
        channelId               <- map["channel_id"]
        text                    <- map["text"]
        createdAt               <- (map["created_at_ts"], DateTransform())
        deletedAt               <- (map["deleted_at_ts"], DateTransform())
        sender                  <- map["entity"]
    }
}

## Version of Realm and Tooling

Realm version: 2.1.0

Xcode version: 8.1

iOS/OSX version: 9.1

Dependency manager + version: 1.1.1

**Comment by kishikawakatsumi** [comment]
@danipralea It is impossible to save multiple objects with the same primary key. Also you can not change the primary key. To solve the issue, you probably need to remove the primary key from the model.

**Comment by danipralea** [comment]
Thanks @kishikawakatsumi 
So I basically need to implement my own custom system for adding, identifying objects etc. I thought I could do it a bit more easily

**Comment by jpsim** [comment]
> So I basically need to implement my own custom system for adding, identifying objects etc. I thought I could do it a bit more easily

That's absolutely not what @kishikawakatsumi said... and you cross-posted this via email, so I'll restate my response here:

> It's hard to me to understand what you mean by having some objects in a Realm, you receive a crash. You experience a crash... when doing what exactly?
>
> Trying to read between the lines, it seems like you might be creating two 'Entity' objects with the same primary key, which is a programmer error (aka incorrect usage of Realm's APIs).
>
> There can only be a single object of a given type with a given primary key. Trying to add an 'Entity' object with a primary key value of '2' to a Realm that already contains an 'Entity' object with a primary key value of '2' will throw a runtime exception, indicating to the user (you) that this isn't what you want to do.
>
> If you wish to "create or update" the 'Entity' object with a primary key value of '2' with some new data, then you should use the [Realm.create(_:value:update: true)](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6createuRxCS_6ObjectrFTMx5valueP_6updateSb_x) method.
>
> Of course, it's impossible for me to know if this advice even applies to you, but I'm doing my best based on the information you've provided to me. In the future, we'd greatly appreciate if you could include a bit more information when asking for help.
>
> There's a great guide on how to write thorough bug reports that you can find here: https://pspdfkit.com/blog/2016/writing-good-bug-reports/
>
> It has some great advice that will improve how well we can help you.
>
> Cheers and thanks for using Realm!

---

As a side-note, we work hard to offer free and timely support to all our users, but cross-posting issues multiple places is a great way to make us spend more time managing our support load rather than actually helping users, or working on bug fixes or new functionality. I ask that you please keep this in mind in your future interactions with us.

**Comment by ZhannySunny** [comment]
Can you say how can I delete primary key and set a new one in Swift?

**Comment by jsflax** [comment]
@ZhannySunny if you mean modifying the primary key, you can remove the object and re-insert it with a new primary key.
