### ISSUE TITLE
Use RealmSwift with Xcode 8.1...

### ISSUE THREAD

**Issue by cwilliamsnh** [realm/realm-cocoa#4436]
I'm trying to use RealmSwift on a new iOS project in Xcode 8.1. I've followed what I thought I needed to follow to get this to work, but I'm still getting a linker error telling me that RealmSwift was compiled with a different version of Xcode.

How long before there's a clean branch that supports Xcode 8.1 (and also 8.2 that just came out today)?

**Comment by jpsim** [comment]
Hi @cwilliamsnh, which of the installation steps did you follow over in our docs? https://realm.io/docs/swift/latest/#installation

You'll notice that there are 3 supported installation methods for Realm Swift: "Dynamic Framework", "CocoaPods" and "Carthage".

Including this information in help requests is very useful for us to be able to understand what went wrong in your installation process.

Judging by the error you got, you're likely using a precompiled Swift binary in your project, which rules out CocoaPods.

As you may know, Swift isn't ABI stable yet, which means that you need to use the same Swift binary  as the version of Xcode you're using.

If you're using Carthage, that installation method only supports a single Swift version at a time, so we stick with the latest stable Xcode release at time of our release. For Realm Swift 2.1.1, that'd be Swift 3.0.1 (Xcode 8.1).

If you're using the release zips (the "Dynamic Framework" installation method in our docs), we provide Swift binaries for 4 different versions of Swift (2.2, 2.3, 3.0 and 3.0.1). So make sure you're using the right version.

![image](https://cloud.githubusercontent.com/assets/474794/21117547/0c15c43e-c06f-11e6-8996-76b4e54e05e9.png)

If you need to use Xcode 8.2 (which as you say just became the latest stable release today), you'll need to build from source (using CocoaPods or Carthage is easiest) or you'll need to wait for us to cut a new release to have a binary. Which might take a week or two.

**Comment by cwilliamsnh** [comment]
Actually, I am using CocoaPods.

Here's the entry in my Podfile:

`pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true`

**Comment by cwilliamsnh** [comment]
Ok, seems I didn't follow the CocoaPods installation completely! Fixing that now!
