### ISSUE TITLE
Compile error when using append in a Realm List (Swift 3)

### ISSUE THREAD

**Issue by D-32** [realm/realm-cocoa#4442]
## Goals

I want to be able to add multiple objects to a Realm List.

## Expected Results

Code compiles without errors.

## Actual Results

Unable to compile both variants of the code.
`project.messages.append(contentsOf: foundMessages)` gives me following error: `Extraneous argument label 'contentOf:' in call`
But when I remove the extraneous argument I get following error:
`project.messages.append(foundMessages)`, `Cannot convert value of type '[Message]' to expected argument type 'Message'`

## Code Sample

```
import Foundation
import RealmSwift

class Demo {
  func test() {
    let house1 = House()
    let house2 = House()
    let village = Village()
    village.houses.append(contentsOf: [house1, house2])
    //village.houses.append([house1, house2])
    // both variants cause a compiler error
  }
}

class House: Object {
}

class Village: Object {
  let houses = List<House>()
}
```

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31

/Applications/Xcode.app/Contents/Developer
Xcode 8.2
Build version 8C38

/usr/local/bin/pod
1.1.1
Realm (2.1.1)
RealmSwift (2.1.1)
RealmSwift (~> 2.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.17.2
(not in use here)

/usr/bin/git
git version 2.10.1 (Apple Git-78)

**Comment by kishikawakatsumi** [comment]
@D-32 Use `append(objectsIn:)` instead `append(contentsOf:)`.

```swift
...
village.houses.append(objectsIn: [house1, house2])
...
```

**Comment by D-32** [comment]
That's an easy fix, works! :)
I didn't get any warning about it being deprecated though...
