### ISSUE TITLE
logInWithCredentials: fails for macOS

### ISSUE THREAD

**Issue by dsanghan** [realm/realm-cocoa#4443]
## Goals

What do you want to achieve?

Login to realm with a username/password pair and synchronize across iOS/Mac.

## Expected Results

Realm logs in correctly on iOS and Mac and synchronizes.

## Actual Results

What did happened instead?  

RLMSyncUser is successfully created for iOS and fails for Mac. The code is exactly the same:

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

```
- (void)enableRealmForSession:(NSString *)username {
    if (!username) {
        return;
    }
    NSString *realmUser = [NSString stringWithFormat:@"REALM_USER_%@", username];
    NSString *realmPass = [NSString stringWithFormat:@"REALM_PASS_%@", username];
    RLMSyncCredentials *usernameCredentials = [RLMSyncCredentials credentialsWithUsername:realmUser
                                                                                 password:realmPass
                                                                                 register:YES];
    [RLMSyncUser logInWithCredentials:usernameCredentials authServerURL:SERVER_URL timeout:30 onCompletion:^(RLMSyncUser * _Nullable user, NSError * _Nullable error) {
        if (user) {
            [self openRealmForUser:user andUsername:username];
        } else if (error) {
            // handle error
        }
    }];
}
```

```logInWithCredentials:``` succeeds for iOS and fails for Mac with: ```Error Domain=io.realm.sync Code=3 "(null)" UserInfo={statusCode=400}```

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.0.0-BETA-4.2

Xcode version: 8.1

iOS/OSX version: 10.1.1 / 10.11.6

Dependency manager + version: Using frameworks downloaded from realm.io for Objc on the client side and ubuntu + apt-get for server

**Comment by stel** [comment]
According to your code sample you register an account each time you try to log in. Please register an account only once and then use an existing one by specifying `register:NO` for `logInWithCredentials` method.

The error reporting was improved in https://github.com/realm/realm-cocoa/pull/4246.

**Comment by dsanghan** [comment]
How would I go about checking if a user is already created from a new client?

Ideally shouldn't the realm server deal with this appropriately and create a user if needed otherwise return an existing user when register is YES?

**Comment by stel** [comment]
Currently the only way to detect if something is wrong with the credentials is to check the `statusCode` of the returned error, but unfortunately right now it doesn't contain the info about what exactly went wrong. #4246 introduces the new error codes:
- `RLMSyncAuthErrorInvalidCredential`
- `RLMSyncAuthErrorUserDoesNotExist`
- `RLMSyncAuthErrorUserAlreadyExists`

**Comment by jpsim** [comment]
@stel `RLMSyncAuthErrorUserDoesNotExist` and `RLMSyncAuthErrorUserAlreadyExists` will never be returned in practice, as that would leak private details about which accounts exist.

**Comment by dsanghan** [comment]
Then for the current version of realm, the way to go about this is first perform a login with register:YES and then attempt to retry with register:NO if it fails?

**Comment by jpsim** [comment]
No, if you expect the user with the provided credentials to exist, you should pass in `register: NO`. You probably shouldn't be synchronizing username and password across versions of your app before you know that they're valid.

**Comment by TimOliver** [comment]
I hope that answered your question @dsanghan!

If you have additional follow-up questions, please feel free to re-open this issue and ask them in here. :)

Happy holidays!

**Comment by revolter** [comment]
Couldn't the error description be something like:

> The provided credentials are invalid or a user with these credentials already exists.

instead of just

> The provided credentials are invalid.

?

As it's pretty confusing now. And the "new" message is pretty standard and doesn't leak private details.

**Comment by jpsim** [comment]
Thanks for the suggestion @revolter, I've forwarded the request to our server team.

**Comment by revolter** [comment]
What if `Error Domain=io.realm.sync.auth Code=3 "(null)" UserInfo={statusCode=400}` is returned when trying to log in using `SyncCredentials.facebook(token: facebookAccessToken)`?
