### ISSUE TITLE
KVO support when updating property on background thread

### ISSUE THREAD

**Issue by jvdijk** [realm/realm-cocoa#4449]
## Goals

I would like to get informed via KVO when a property has changed on a Realm Object even when this property has been changed on the equivalent Object on a background thread.

## Expected Results

I would have expected 
`func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?)` 
to be called on the observer when the property changed on the background object. The property has been changed on the main thread object, but KVO didn't trigger.

## Actual Results

KVO does not trigger even though the property has been changed.

## Steps to Reproduce

1. Create a Realm Object on the main thread
2. KVO a property
3. Create a background thread and fetch the object created in step 1
4. Update the observed property
5. KVO is not triggered

## Code Sample

        let realm = try! Realm()
        let user = User()
        user.id = "1234"
        user.name = "John"
        try! realm.write {
            realm.add(user)
        }
        user.addObserver(self, forKeyPath: "name", options: [], context: nil)
        
        DispatchQueue.global(qos: .background).async {
            let realm = try! Realm()
            let user = realm.object(ofType: User.self, forPrimaryKey: "1234")!
            try! realm.write {
                user.name = "Jorn"
            }
        }`

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555

/Applications/Xcode.app/Contents/Developer
Xcode 8.1
Build version 8B62

/Users/jornvandijk/.rvm/rubies/ruby-2.3.1/bin/pod
1.1.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

carthage not found
(not in use here)

/usr/local/bin/git
git version 2.10.2
```

Realm version:

- Realm (2.1.1):
    - Realm/Headers (= 2.1.1)
  - Realm/Headers (2.1.1)
  - RealmSwift (2.1.1):
    - Realm (= 2.1.1)

**Comment by kishikawakatsumi** [comment]
@jvdijk Realm's KVO should notify when updating a property on a background thread. I believe that the reason is observing object `user` has been deallocated before changes happen. Could you try to keep `user` as an instance property instead a local variable?

**Comment by jvdijk** [comment]
@kishikawakatsumi You are absolutely right in the example I gave. I'm unable to reproduce it my project today… Thanks for the reply.
