### ISSUE TITLE
Realm/Realm.h not found

### ISSUE THREAD

**Issue by fabiofai** [realm/realm-cocoa#4451]
## Goals

What do you want to achieve?
I update realm 1.0.0 to 2.1.1 with cocoapod.  After "pod install", the classes which I implemented Realm get error. #import<Realm/Realm.h> file not found.

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?
2.1.1
Xcode version: ?
8
iOS/OSX version: ?
9
Dependency manager + version: ?
cocoapod 1.1.1

**Comment by fabiofai** [comment]
![screen shot 2016-12-15 at 3 09 05 pm](https://cloud.githubusercontent.com/assets/7869112/21214878/7af63bca-c2d8-11e6-9a37-8f0fa6f1bee8.png)
Here is a screen shot about my issue

**Comment by kishikawakatsumi** [comment]
@fabiofai It is probably a problem due to caching of CocoaPods. Can you try to execute following commands?

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
```

See also [Trouble Shooting#Reinstalling Via Dependency Managers#CocoaPods](https://realm.io/docs/objc/latest/#reinstalling-via-dependency-managers)

**Comment by fabiofai** [comment]
thanks, it works.  I miss the last step.  However, when I need to do these steps?

**Comment by kishikawakatsumi** [comment]
> when I need to do these steps?
When weird build error occurred, it probably due to package manager or Xcode cache.

**Comment by Fouda** [comment]
I tried with the commands but still facing the same problem 
any suggestions ??

**Comment by Fouda** [comment]
I solved by setting pod build architecture to NO

**Comment by gang018** [comment]
@Fouda can you plz provide a source code?
