### ISSUE TITLE
Run Script Invocation Error due to Realm run script

### ISSUE THREAD

**Issue by Alamoz** [realm/realm-cocoa#4454]
Realm version: 2.1.1

Xcode version: 8.2

iOS/OSX version: 10.2/10.11.6

Dependency manager + version: ?

Hey guys, I'm trying to create an Archive and it dies with an error of "Run Script Invocation Error" due to the run script we've been adding to our apps to work around an App Store submission bug. When I remove the run script I can create the Archive, but will that Archive then raise the App Store submission bug?

**Comment by kishikawakatsumi** [comment]
@Alamoz Did you use the pre-built framework? If you use CocoaPods or Carthage, you do not need to add `Run Script Phase`. It is needed for the pre-built framework.
Another possibility, `Run Script Phase` should be later than other build phases. Could you make sure the position of `Run Script Phase` that you are added?

**Comment by Alamoz** [comment]
Yes, I'm using the pre-built framework and the Run Script Phase is defined after the other build phases. I'm going to try using Carthage or CocoaPods.

Related to this, I've come across a post where someone states that using a pre-built framework could be grounds for Apple denying an app submission. Have you ever heard of that happening?

**Comment by jpsim** [comment]
> Have you ever heard of that happening?

I've never heard this happen, although Apple _does_ state that precompiled Swift frameworks aren't encouraged.

**Comment by Alamoz** [comment]
@kishikawakatsumi CocoaPods didn't work. Carthage did work so I'm using Carthage.

**Comment by jpsim** [comment]
Glad you got this working eventually. If you feel like sharing a detailed bug report detailing how we can reproduce the issues you've seen with CocoaPods, please file a new issue and we'll happily take a look at it.

**Comment by Alamoz** [comment]
Thanks @jpsim. I like the Carthage approach. Noticed you closed this issue but the problem did occur and didn't go away. Maybe my environment contains some glitch, don't see others reporting this.

**Comment by jpsim** [comment]
> Noticed you closed this issue but the problem did occur and didn't go away

Sure, but it didn't look like you'd be providing more info since you've moved on. If you plan on working with us to identify and fix this, let's reopen.
