### ISSUE TITLE
Object's className var differs from Object's className() static func

### ISSUE THREAD

**Issue by nemesis** [realm/realm-cocoa#4456]
## Goals

I have a simple Object subclass named `Model`, and I want to use the `className` property on `Model`'s instances.

## Expected Results

Expected to get the same result as calling `Model.className()`

## Actual Results

Getting an empty string `""`

## Steps to Reproduce

1. Create an `Object` subclass
2. Create an instance of that subclass
3. Try using `instance.className` and `Class.className()` and notice that they differ

## Code Sample

```swift
// Model.swift

import Realm
import RealmSwift

final class Model: Object {
    dynamic var uuid: String = ""

    override static func primaryKey() -> String? {
        return #keyPath(Model.uuid)
    }
}
```

```swift
// FailingSpec.swift

class RealmClassNameTests: XCTestCase {
    func testClassName() {
        let uuid = UUID().uuidString
        let model = Model(value: [#keyPath(Model.uuid): uuid])

        XCTAssertNotNil(model) // OK
        XCTAssertEqual(uuid, model.uuid) // OK
        XCTAssertEqual(Model.className(), "Model") // OK
        XCTAssertEqual(model.className, "Model") // 😿
    }
}
```

## Version of Realm and Tooling

```
ProductName:  Mac OS X
ProductVersion: 10.12.2
BuildVersion: 16C67

/Applications/Xcode.app/Contents/Developer
Xcode 8.2
Build version 8C38

/Users/nemesis/.rvm/gems/ruby-2.2.2/bin/pod
CocoaPods 1.1.1
Realm (2.1.1)
RealmSwift (2.1.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/git
git version 2.10.2
```

**Comment by kishikawakatsumi** [comment]
@nemesis This is intentional. Please see the discussion https://github.com/realm/realm-cocoa/pull/2319
@jpsim Do you have additional explanation about this?

**Comment by nemesis** [comment]
@kishikawakatsumi Thanks for the response, but I think you misunderstood the issue. AFAIK #2319 is about `className` being overriden, whilst this issue is about the fact that an instance's `className` property returns an empty string, and the `static func className()` returns the appropriate result.

Please let me know if I'm missing something.

**Comment by jpsim** [comment]
Please see my fix and explanation in #4467.

**Comment by nemesis** [comment]
👍 I wanted to do a pull request using `instance.classForCoder.className()` but I guess this is the way to do it :)

Glad to help!

**Comment by austinzheng** [comment]
Just for closure: the instance property `className` was added incorrectly. #5201 removes it from the API, and this change will ship with our upcoming 3.0 release. The class method `className()` continues to work properly as before.
