### ISSUE TITLE
How to do failable mapping of Dictionaries/Arrays to RealmSwift Objects

### ISSUE THREAD

**Issue by Coeur** [realm/realm-cocoa#4458]
## Context
We have some `[String: Any]` dictionaries and `[[String: Any]]` arrays coming from `JSONSerialization.jsonObject()` and we would like to make it class instances of Realm `Object` models (let's say a `PersonModel` for below example). According to documentation, we need to design models with properties like that:

    class PersonModel : Object {
        dynamic var id = ""
        dynamic var name = ""
        dynamic var imagePath: String?
        let friends = List<PersonModel>()
        let movies = List<MovieModel>()
    }

## Our wishes for making the instances
* The creation of an instance based on a dictionary should be conditional: i.e. it should return a `Person?` because sometimes the data is invalid.
* The creation of a List based on an array should filter (or flatmap) valid objects only.
* The key names of the dictionary and the variable names of the class do not match: i.e. the JSON may have a "username" but the corresponding class variable would be "name". That's why we can't avoid a manual *mapping* solution of the dictionaries.

## Problems
* Unlike [Apple's recommendations on how to turn a JSON to an instance](https://developer.apple.com/swift/blog/?id=37),  `Realm.create(_:value:update:)` doesn't throw and never returns nil, which means it seems unable to deal with invalid data.
* We couldn't find any mapping implementation inside Realm. In fact, I believe Realm is asking, [according to its doc on json support](https://realm.io/docs/swift/latest/#json), to deal with the validity of json data beforehand using third parties. Examples of those third parties could be find on [JSONShootout](https://github.com/bwhiteley/JSONShootout) and on ["Support custom model mappings" github issue](https://github.com/realm/realm-cocoa/issues/694).

## Question
Let's say we have this `[[String:Any]]` array of dictionaries:

    [["userid": "u1",
      "username": "bob",
      "image": "http://example.com/bob.jpg",
      "friendIds": ["u2", "u3"],
      "movieIds": ["sw4", "sw5", "sw6", "ro"]],
     ["userid": "u2",
      "username": "max",
      "image": "http://example.com/max.jpg",
      "friendIds": ["u1", "u3"],
      "movieIds": ["sw4", "sw5", "sw6", "sw7"]],
     ["userid": "u3",
      "username": false],
    ]

The desired result would be to have:

* no instance creation at all of a "u3" PersonModel, because it has invalid name.
* a PersonModel instance with name `"bob"` and friends being `List(max)`.
* a PersonModel instance with name `"max"` and friends being `List(bob)`.

But it's not obvious to us how we're supposed to achieve those conditions with RealmSwift. We don't see how to write code to workaround the non-fallible constructor `Realm.create(_:value:update:)`. And we don't see how third-parties JSON mappers (like [lyft/mapper](https://github.com/lyft/mapper) or [JohnSundell/Unbox](https://github.com/JohnSundell/Unbox)) can to the job of filtering/converting a given non appropriate `[[String:Any]]` to a `[[String:Any]]` compatible with RealmSwift `create()` method.

**Comment by kishikawakatsumi** [comment]
@Coeur We recommend using third-party mapping library to bind JSON to Realm model. I think ObjectMapper https://github.com/Hearst-DD/ObjectMapper provide failable initializer to validate JSON structure while mapping process. Is this answer for you?

**Comment by jpsim** [comment]
There are so many great 3rd party model mapping libraries out there, that we've decided not to build our own into Realm, instead letting you use the framework of your choosing. See https://github.com/realm/realm-cocoa/issues/694#issuecomment-144785299 for more.

**Comment by TimOliver** [comment]
Thanks for the issue @Coeur! I hope that answered your question. 
Please give ObjectMapper a try and see if that provides the functionality you need.

Have a happy holiday! :)
