### ISSUE TITLE
pod install fails every time with Realm

### ISSUE THREAD

**Issue by danat8x8** [realm/realm-cocoa#4463]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>

** BUG**

realm fails to install from 'pod install'
[Podfile.zip](https://github.com/realm/realm-cocoa/files/662025/Podfile.zip)
[output.txt](https://github.com/realm/realm-cocoa/files/662082/output.txt)

error:(note, text below was in red
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

This is repeatable.
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by TimOliver** [comment]
Hi @danat8x8!

Thanks for your issue! Sorry to hear you're having some trouble installing Realm via CocoaPods.

I just looked at your `Podfile`. And noticed two things that may be causing the problem.

* If you're using Realm in Swift, I recommend you use Realm Swift instead of Realm Objective-C. As such you should use `pod 'RealmSwift'` instead of `pod 'Realm'`.
* There's a space after your specified version of the Realm pod, but still inside the quotes (`pod 'Realm', '~> 2.1.1 '`). This may cause issues with CocoaPods.

Can you please try addressing those points and let me know if that fixed it? Thanks!

**Comment by jpsim** [comment]
@TimOliver none of that explains the failure in `build.sh cocoapods-setup` in this case.

@danat8x8 could you please try the following commands in Terminal and report the full output?

```shell
$ git clone https://github.com/realm/realm-cocoa.git
$ cd realm-cocoa
$ git submodule update --init --recursive
$ sh build.sh cocoapods-setup
```

Thanks!

**Comment by danat8x8** [comment]
Thanks for the help!
Our project is primarily legacy ObjC; we are trying to transition to swift gradually, so I need to keep using Realm-Cocoa. (with the swift extensions)

**Comment by danat8x8** [comment]
It looks like the extra space happened when pasting into GitHub.

**Comment by danat8x8** [comment]
here's the output ...
dwalkowski@MBP15-N5G8WP iOS-v7 (master) $ git clone https://github.com/realm/realm-cocoa.gitCloning into 'realm-cocoa'...
remote: Counting objects: 68844, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 68844 (delta 5), reused 0 (delta 0), pack-reused 68829
Receiving objects: 100% (68844/68844), 48.10 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (48068/48068), done.
Checking connectivity... done.
Checking out files: 100% (1108/1108), done.
dwalkowski@MBP15-N5G8WP iOS-v7 (master) $ cd realm-cocoa
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $ 
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $ git submodule update --init --recursive
Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
Cloning into '/Users/dwalkowski/Desktop/Fresh/iOS-v7/realm-cocoa/Realm/ObjectStore'...
Submodule path 'Realm/ObjectStore': checked out '6ab62460c4022a6233c3a817270eab0855f19770'
Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'Realm/ObjectStore/external/catch'
Submodule 'external/pegtl' (https://github.com/ColinH/PEGTL) registered for path 'Realm/ObjectStore/external/pegtl'
Cloning into '/Users/dwalkowski/Desktop/Fresh/iOS-v7/realm-cocoa/Realm/ObjectStore/external/catch'...
Cloning into '/Users/dwalkowski/Desktop/Fresh/iOS-v7/realm-cocoa/Realm/ObjectStore/external/pegtl'...
Submodule path 'Realm/ObjectStore/external/catch': checked out 'f294c9847272b1b92c5119a6f711e57113b5f231'
Submodule path 'Realm/ObjectStore/external/pegtl': checked out '3c4128a7e7e1288eb746418ea60c41477358f26a'
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $ 
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $ 
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $ git submodule update --init --recursive
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $ 
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $ sh build.sh cocoapods-setup
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $

**Comment by jpsim** [comment]
So there's no output at all when you run `sh build.sh cocoapods-setup`?

You know, I think I did have this happen to me before, as described in #4138.

Can you try accepting Xcode's license and try again? `sudo xcodebuild -license accept`

**Comment by danat8x8** [comment]
Oh Crap:
I'm on 8.2

xcrun: error: active developer path ("/Applications/Xcode 8.1.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
dwalkowski@MBP15-N5G8WP realm-cocoa (master) $

**Comment by jpsim** [comment]
That would do it! I'll close this issue now based on this. There might be some way for us to detect this in `build.sh` invocations, so I've created #4465 to track that.

**Comment by danat8x8** [comment]
it appears my machine thinks I'm I'm on 8.1
whats my best course of action here?

**Comment by jpsim** [comment]
Do as the error message says:

`sudo xcode-select -s /Applications/Xcode-8.2.app/Contents/Developer`

Replace `/Applications/Xcode-8.2.app` with wherever you've installed Xcode.

**Comment by danat8x8** [comment]
it failed, any suggestions?

dwalkowski@MBP15-N5G8WP ~ $ sudo xcode-select -s /Applications/Xcode-8.2.app/Contents/Developer
Password:
xcode-select: error: invalid developer directory '/Applications/Xcode-8.2.app/Contents/Developer'
dwalkowski@MBP15-N5G8WP ~ $

**Comment by jpsim** [comment]
@danat8x8 where did you install Xcode?

```
$ ls /Applications | grep Xcode
```
