### ISSUE TITLE
Fatal Exception: RLMException ftruncate() failed: No such file or directory

### ISSUE THREAD

**Issue by cclogg** [realm/realm-cocoa#4468]
Hey guys, I have a pretty rare crash that says the following:
_RLMException ftruncate() failed: No such file or directory._
I was hoping to find a bug in my code and not have to resort to posting here, but so far no luck... Maybe someone will have some insight!

I haven't been able to reproduce it myself, but Crashlytics has reported it in the wild (very occasionally). It has happened across iOS 9 & 10, a variety of iPhones, and across several Realm versions (most recent it occurred on is objc-2.1.1). It has also happened from different parts of my code, but it always comes from _commitWriteTransaction_:
<img width="376" alt="screen shot 2016-12-19 at 5 38 09 pm" src="https://cloud.githubusercontent.com/assets/1407377/21335204/f7d2418e-c611-11e6-8600-b63509260bf0.png">
I checked each of the crashes and there were no hardware space issues, but I did find a common thread: memory was very low (around 1-5% free device memory left)... so my theory is that maybe it is related to this. Unfortunately it's not easy to get an iPhone into a state of that low memory, and test code I added to waste memory didn't make this crash (in fact the app doesn't really have any crashes other than this rare one).

The code that crashes looks like this:

`RLMRealm *realm = [RLMRealm defaultRealm];`
`SomeRealmObject *myObject = [[SomeRealmObject alloc] init];`
` [realm beginWriteTransaction];`
`    myObject.someProperty = @"blabla";`
  `  myObject.someDate = [NSDate date];`
    `myObject.someAmount = 25.0f;    `
    `[realm addOrUpdateObject: myObject];`
`    [realm commitWriteTransaction];`

Any help is appreciated, thanks!

P.S. I also tried writing an endless loop that ran my realm transaction code several thousand times in a second or so, and that had no issues either.

**Comment by tgoyne** [comment]
`ftruncate()` is used to grow the file when needed during a write transaction.  It makes some sense for that to fail when the device is out of memory, although not with that specific error (`ENOENT` isn't even listed as one of the possible error codes for `ftruncate`). I don't really have any ideas of what could cause that other than things like a memory allocation failure within `ftruncate()` causing funny issues, but if allocations are failing I would expect a bunch of similar crashes elsewhere.

**Comment by cclogg** [comment]
Okay thanks for the info, I will keep playing around and see what I can find. Hopefully it's just some issue in my code.

**Comment by jpsim** [comment]
You could try to clean up some of the memory allocations that are contributing to the low available memory of your app when you get notified of such pressure. See Apple's docs on [Using Memory Efficiently](https://developer.apple.com/library/content///documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/PerformanceTips/PerformanceTips.html#//apple_ref/doc/uid/TP40007072-CH7-SW8) for details.

**Comment by stel** [comment]
@cclogg do you have any info related to this case? Do you need any other help or can we close this issue?

**Comment by cclogg** [comment]
I haven't been able to reproduce... it still seems to only happen with 'slow' phones and related to low memory. You can close for now, thanks.

**Comment by stel** [comment]
Ok, I'm closing it for now. Feel free to reopen it or create a new one if you need any further help.
