### ISSUE TITLE
Query log / verbose mode?

### ISSUE THREAD

**Issue by i-schuetz** [realm/realm-cocoa#4474]
Is it possible to see somewhere a query log? Similar to e.g. the query log of MySQL. 

If it's not supported (I can't find it), is this something you would add? It's very helpful for debugging. It could be enabled with a configuration setting.

**Comment by jpsim** [comment]
If you have a debugger attached, you can set a breakpoint on [RLMPredicateToQuery()](https://github.com/realm/realm-cocoa/blob/v2.1.2/Realm/RLMQueryUtil.mm#L1351) to log `@predicate.description@` and to check the breakpoint box to "Automatically continue after evaluating breakpoint actions".

![image](https://cloud.githubusercontent.com/assets/474794/21400589/b6c6267e-c765-11e6-84bb-d243997cca4b.png)

which will log all the Realm queries performed:

```
@"1 != bool2"
@"1 != double1"
@"1 != float2"
@"1 < float2"
@"1 <= float2"
@"1 == bool1"
@"1 == double1"
@"1 == float1"
@"1 == int1"
@"1 > float1"
@"1 >= float1"
@"2 != int2"
@"2 < int1"
@"2 <= int1"
@"2 > int1"
@"2 >= int1"
@"5 < double2"
@"5 > double2"
@"5.55 <= double2"
@"5.55 >= double2"
@"\"a\" != string2"
@"\"a\" == string2"
@"\"Amazon\" BEGINSWITH string2"
@"\"Realm\" CONTAINS string1"
@"\"Tuba\" ENDSWITH string1"
```

**Comment by i-schuetz** [comment]
That helps a lot, thanks. But would it be possible to have a full log? Here for example it's not always clear to which object the properties belong, there's also no time, etc.

**Comment by jpsim** [comment]
You can edit breakpoints to do all sorts of useful things:

![image](https://cloud.githubusercontent.com/assets/474794/21401047/a07e3080-c767-11e6-9dcb-1d891383cb58.png)

which outputs:

```
Wed Dec 21 10:23:46 PST 2016
Query on @"IntObject": @"intCol == 0"
```

if you're building Realm from source, you can also just an `NSLog` and get even more flexibility:

```objc
NSLog(@"Query on %@: %@", objectSchema.className, predicate);
```

which outputs:

```
2016-12-21 10:25:46.986665 MyApp[3435:3742831] Query on EmployeeObject: name == "Jill"
2016-12-21 10:25:46.986793 MyApp[3435:3742831] Query on EmployeeObject: name == "Joe"
2016-12-21 10:25:46.986876 MyApp[3435:3742831] Query on EmployeeObject: name == "John"
2016-12-21 10:25:46.987009 MyApp[3435:3742831] Query on EmployeeObject: age > 30
2016-12-21 10:25:46.987123 MyApp[3435:3742831] Query on EmployeeObject: name == "Joe"
2016-12-21 10:25:46.987355 MyApp[3435:3742831] Query on EmployeeObject: name == "Bill"
2016-12-21 10:25:46.987416 MyApp[3435:3742831] Query on EmployeeObject: name == "John"
2016-12-21 10:25:46.987472 MyApp[3435:3742831] Query on EmployeeObject: name == "Jill"
```

**Comment by i-schuetz** [comment]
Ok, that's very practical! Is it possible to see writes in a similar way?

**Comment by jpsim** [comment]
Sure! You can set breakpoints anywhere you'd like in Realm. For example, set a breakpoint in [Realm::commit_transaction()](https://github.com/realm/realm-object-store/blob/6ab62460c4022a6233c3a817270eab0855f19770/src/shared_realm.cpp#L482) to trigger whenever a write transaction is committed.

---

It seems like you might benefit from reading Apple's overview of its [Debugging Tools](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/debugging_tools.html), which shows you all sorts of options at your disposal to do this kind of thing.

**Comment by i-schuetz** [comment]
Thanks, it seems indeed that I have to improve my knowledge about the debugger.

However I still think a full fledged logger could be convenient, as using breakpoints is cumbersome, if the code changes or even is restructured in such way that the information is not complete/legible they will not work. Having to dig in the c++  implementation files to enable this doesn't seem optimal.

With a logger it would be also possible to e.g. easily enable showing properly formatted query results. Things like that.

**Comment by jpsim** [comment]
Perhaps you could write up a detailed proposal for how you think such a feature could be exposed, how it could be used, what kinds of information it should log, maybe even how it could be built? If we had a clearer idea of what you were looking for, we could convert this ticket to track that as a feature request.

**Comment by i-schuetz** [comment]
It could be exposed via a setting in `Realm.Configuration`, something like a `enableQueryLogs` boolean. Or something more granular, that controls level of detail, operation types, etc. It would log with a format similar to what you showed in your 2nd message, e.g. 

> 2016-12-21 10:25:46.986665 MyApp[3435:3742831] Query on EmployeeObject: name == "Jill"

And analogously for inserts, updates and deletes.

Adding more features like the option of showing the query results would not be included in this request, to keep it simple.

**Comment by jpsim** [comment]
Honestly, given that it takes less time to set up a breakpoint to provide exactly that information, and that breakpoints are much more flexible than whatever approach we'd expose for this type of logging, I'm inclined to not build something like that into Realm.

Rather than setting breakpoints on lines specifically, you could set them symbolically on the selectors and functions involved.

You could also check in an `.lldbinit` file to your Realm-using projects where you could keep a collection of useful debugger commands specifically to Realm usage. You could even open source it and encourage others to use and contribute back!

**Comment by i-schuetz** [comment]
I don't think that configuring these breakpoints and possibly having to edit them if the selectors change (for which you'd have to study the new implementation, in order to find the correct selectors) takes less time than adding something like `enableQueryLogs: true` (or e.g. `queryLogs: default` in the more granular case) to the configuration. 

It's of course only a convenience feature since as you showed it's possible to emulate most of this functionality using breakpoints.

However, couldn't this be used to log also the object server activity? In such case it's not possible to use breakpoints. MySQL and some ORMs, or similar, logging, is very handy when debugging server issues.

**Comment by jpsim** [comment]
Turns out, we are tracking this as a low priority enhancement already in #2617. Feel free to move the conversation there.
