### ISSUE TITLE
iOS app crashing

### ISSUE THREAD

**Issue by vipindhangar** [realm/realm-cocoa#4479]
Hi,

I'm using Firebase for chat messaging feature and Realm is used in it internally. 
The issue is :- 
The app is crashing when I start chat (User A) with another user (User B). The case is :-

1. When User A chats with User B.
2. Now both users switch the devices, (means now User B is using User A's device and vice versa) app crashes first time and if same scenario is repeated then it works fine.

I have found the below code snippet which crashes the app.

```
static NSUInteger getRowForObjectWithPrimaryKey(RLMClassInfo const& info, id primaryValue) {
	REALM_ASSERT_DEBUG(info.propertyForPrimaryKey());

	RLMProperty *const primaryProperty = info.propertyForPrimaryKey();
	const NSUInteger primaryPropertyColumn = info.tableColumn(primaryProperty);

	switch (primaryProperty.type) {
		case RLMPropertyTypeString:
			return info.table()->find_first_string(primaryPropertyColumn, RLMStringDataWithNSString(primaryValue)); //At this point the app crashes

		case RLMPropertyTypeInt:
			if (primaryValue) {
				return info.table()->find_first_int(primaryPropertyColumn, [primaryValue longLongValue]);
			} else {
				return info.table()->find_first_null(primaryPropertyColumn);
			}

		default:
			REALM_UNREACHABLE();
	}
}

static inline realm::StringData RLMStringDataWithNSString(__unsafe_unretained NSString *const string) {
	static_assert(sizeof(size_t) >= sizeof(NSUInteger),
	"Need runtime overflow check for NSUInteger to size_t conversion");
	return realm::StringData(string.UTF8String,
	[string lengthOfBytesUsingEncoding:NSUTF8StringEncoding]);
}
```

**Comment by TimOliver** [comment]
Hi @vipindhangar!

Thanks for the issue. Sorry to hear you're experiencing a crash.

What is your app doing when the user switches devices in step 2? Are you changing the default Realm configuration or shuffling any Realm files around on disk?

**Comment by vipindhangar** [comment]
Hi
Actually user2 just logged in to device in which previously user1 was
logged in and try to fetch the messages shared between each other and
nothing.

The default Realm configuration is same and no shuffling of any Realm files.

Thanks
Vipin

Hi @vipindhangar <https://github.com/vipindhangar>!

Thanks for the issue. Sorry to hear you're experiencing a crash.

What is your app doing when the user switches devices in step 2? Are you
changing the default Realm configuration or shuffling any Realm files
around on disk?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/realm/realm-cocoa/issues/4479#issuecomment-268809536>,
or mute the thread

**Comment by TimOliver** [comment]
Hi @vipindhangar!

Thanks for that! I think I need a little more information to work out what's going on here. It sounds like the resources from user1 aren't getting cleaned up properly before user2 comes in, causing some kind of inconsistent state.

How does user1 log out before user2 is allowed to log in? Are you able to post some code samples?

Thanks!

**Comment by vipindhangar** [comment]
Hello Tim,

Please find the code flow which is creating problem : -

1.
//-------------------------------------------------------------------------------------------------------------------------------------------------
- (void)updateRealm:(NSDictionary *)message
//-------------------------------------------------------------------------------------------------------------------------------------------------
{
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    [DBMessage createOrUpdateInRealm:realm withValue:message];
    [realm commitWriteTransaction];
}

2. + (instancetype)createOrUpdateInRealm:(RLMRealm *)realm
withValue:(id)value {
    // verify primary key
    RLMObjectSchema *schema = [self sharedSchema];
    if (!schema.primaryKeyProperty) {
        NSString *reason = [NSString stringWithFormat:@"'%@' does not have
a primary key and can not be updated", schema.className];
        @throw [NSException exceptionWithName:@"RLMExecption" reason:reason
userInfo:nil];
    }
    return (RLMObject *)RLMCreateObjectInRealmWithValue(realm, [self
className], value, true);
}


Vipin Dhangar
9893074069
8770280434

**Comment by vipindhangar** [comment]
Hello Tim,

Please ignore the last message.

Please find the code flow which is creating problem : -

1. //----------------------------------------------------------
------------------------------------------------------------
---------------------------
- (void)updateRealm:(NSDictionary *)message
//----------------------------------------------------------
------------------------------------------------------------
---------------------------
{
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    [DBMessage createOrUpdateInRealm:realm withValue:message];
    [realm commitWriteTransaction];
}

2. + (instancetype)createOrUpdateInRealm:(RLMRealm *)realm
withValue:(id)value {
    // verify primary key
    RLMObjectSchema *schema = [self sharedSchema];
    if (!schema.primaryKeyProperty) {
        NSString *reason = [NSString stringWithFormat:@"'%@' does not have
a primary key and can not be updated", schema.className];
        @throw [NSException exceptionWithName:@"RLMExecption" reason:reason
userInfo:nil];
    }
    return (RLMObject *)RLMCreateObjectInRealmWithValue(realm, [self
className], value, true);
}

3. + (instancetype)createOrUpdateInRealm:(RLMRealm *)realm
withValue:(id)value {
    // verify primary key
    RLMObjectSchema *schema = [self sharedSchema];
    if (!schema.primaryKeyProperty) {
        NSString *reason = [NSString stringWithFormat:@"'%@' does not have
a primary key and can not be updated", schema.className];
        @throw [NSException exceptionWithName:@"RLMExecption" reason:reason
userInfo:nil];
    }
    return (RLMObject *)RLMCreateObjectInRealmWithValue(realm, [self
className], value, true);
}

4. static NSUInteger getRowForObjectWithPrimaryKey(RLMClassInfo const&
info, id primaryValue) {

    REALM_ASSERT_DEBUG(info.propertyForPrimaryKey());

    RLMProperty *const primaryProperty = info.propertyForPrimaryKey();
    const NSUInteger primaryPropertyColumn =
info.tableColumn(primaryProperty);

    switch (primaryProperty.type) {
        case RLMPropertyTypeString:
            return info.table()->find_first_string(primaryPropertyColumn,
RLMStringDataWithNSString(primaryValue));
//In this line the app get crashed
        case RLMPropertyTypeInt:
            if (primaryValue) {
                return info.table()->find_first_int(primaryPropertyColumn,
[primaryValue longLongValue]);
            } else {
                return info.table()->find_first_null(primaryPropertyColumn);
            }

        default:
            REALM_UNREACHABLE();
    }
}

Thanks

Vipin Dhangar
9893074069
8770280434

**Comment by TimOliver** [comment]
Hi @vipindhangar!

Thanks for that, but it would help a lot more if you could send us some sample code from your app. Like I asked earlier, when both users switch devices, how is this handled in the code? Could you please paste that code sample? :)

Thanks!

**Comment by vipindhangar** [comment]
Hello Tim,

Please find the code snippet which is being used when user log out

I'm calling  [self LogoutfromApp] when user log out from the device

One more case I have found that when  userA logout from the device and
restart the app(means fresh launch the app) and logs in with userB then the
app works fine.

1. -(void)LogoutfromApp {
          LogoutUser(DEL_ACCOUNT_ONE);

         if ([FUser logOut]) {
                 [CacheManager cleanupManual];
        }
}


//LogoutUser(DEL_ACCOUNT_ONE);
void LogoutUser(NSInteger delAccount)
//-------------------------------------------------------------------------------------------------------------------------------------------------
{
    ResignOneSignalId();

//---------------------------------------------------------------------------------------------------------------------------------------------
    if (delAccount == DEL_ACCOUNT_ONE) [Account delOne];
    if (delAccount == DEL_ACCOUNT_ALL) [Account delAll];

//---------------------------------------------------------------------------------------------------------------------------------------------
    if ([FUser logOut])
    {
        [CacheManager cleanupManual];

//-----------------------------------------------------------------------------------------------------------------------------------------
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        [realm deleteAllObjects];
        [realm commitWriteTransaction];

//-----------------------------------------------------------------------------------------------------------------------------------------
        [NotificationCenter post:NOTIFICATION_USER_LOGGED_OUT];
    }
    else [ProgressHUD showError:@"Network error."];
}


//[FUser logOut])
+ (BOOL)logOut
//-------------------------------------------------------------------------------------------------------------------------------------------------
{
    NSError *error;
    [[FIRAuth auth] signOut:&error];

//---------------------------------------------------------------------------------------------------------------------------------------------
    if (error == nil)
    {
        [[NSUserDefaults standardUserDefaults] removeObjectForKey:@
"CurrentUser"];
        [[NSUserDefaults standardUserDefaults] synchronize];
        return YES;
    }

//---------------------------------------------------------------------------------------------------------------------------------------------
    return NO;
}

What I'm doing when user login in the the app :-

1. - (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [FIRApp configure];
return YES;
}

//Login to firebase
2. [FUser signInWithEmail:userName password:firebasePassword
completion:^(FUser *user, NSError *error) {
      if (error == nil) {

       } else {
       }
  }];

Thanks
Vipin Dhangar

Vipin Dhangar
9893074069
8770280434

**Comment by TimOliver** [comment]
Hmm, all of that looks fine. You call logout on Firebase and when that succeeds, you delete all of the local Realm references.

When the app crashes, do you get any error messages in the console?

Also, this might go a bit faster if I can try out the code myself. Would you be willing to email your app's source code to help@realm.io?

**Comment by vipindhangar** [comment]
Hi Tim,

Actually there is no error message in the cinsole.

The app gets stuck on the line of code which I sent you earlier today with
line where it crashes and it shows exe bad acces.

To send you the code to test I have to prepare a demo code with the
functionality but I'm unable to send it today but on monday.

Thanks
On Dec 23, 2016 7:52 PM, "Tim Oliver" <notifications@github.com> wrote:

Hmm, all of that looks fine. You call logout on Firebase and when that
succeeds, you delete all of the local Realm references.

When the app crashes, do you get any error messages in the console?

Also, this might go a bit faster if I can try out the code myself. Would
you be willing to email your app's source code to help@realm.io?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/realm/realm-cocoa/issues/4479#issuecomment-268996968>,
or mute the thread

**Comment by TimOliver** [comment]
Hi @vipindhangar!

Cool okay. Please send us the code when you get the chance. Most of Realm will be going on holidays next week, so it might be a little while before we can address it, but we'll try our best.

Happy holidays!

**Comment by vipindhangar** [comment]
Hello Tim,

I'm unable to send the demo source code to you for the crash issue.
Can you help me in any other way?

Thanks

Vipin Dhangar
9893074069
8770280434

**Comment by vipindhangar** [comment]
Hello Tim,

The same issue was reported in this link

https://github.com/realm/realm-cocoa/issues/4155

Vipin Dhangar
9893074069
8770280434

**Comment by vipindhangar** [comment]
Hello Tim,

Please also check the attachments in which there is crash logs.

Vipin Dhangar
9893074069
8770280434

**Comment by vipindhangar** [comment]
I'm still waiting for your reply.


Vipin Dhangar
9893074069
8770280434

**Comment by TimOliver** [comment]
Hi @vipindhangar!

Sorry for the delay! I was on holiday for last week! I'm back into it now though!

What attachment are you referring to? If you replied to this GitHub issue via an email and attached a file to it, I don't think it was automatically posted here...

**Comment by vipindhangar** [comment]
![screen shot 2016-12-27 at 2 29 08 pm](https://cloud.githubusercontent.com/assets/2247243/21761144/0ae240d8-d677-11e6-82f5-738e4219f540.png)
![screen shot 2016-12-27 at 2 29 39 pm](https://cloud.githubusercontent.com/assets/2247243/21761140/0aded3a8-d677-11e6-944d-600df243c8f9.png)
![screen shot 2016-12-27 at 2 29 54 pm](https://cloud.githubusercontent.com/assets/2247243/21761142/0adff67a-d677-11e6-8900-17072c09cb44.png)
![screen shot 2016-12-27 at 2 30 05 pm](https://cloud.githubusercontent.com/assets/2247243/21761145/0ae2ea9c-d677-11e6-9615-cbdabbb07020.png)
![screen shot 2016-12-27 at 2 30 09 pm](https://cloud.githubusercontent.com/assets/2247243/21761141/0adf19f8-d677-11e6-850f-bdfe91cd3064.png)
![screen shot 2016-12-27 at 2 30 14 pm](https://cloud.githubusercontent.com/assets/2247243/21761143/0ae1adee-d677-11e6-9b13-b63088bd0ec7.png)

I have attached the screen shots. Hope this will help you.

**Comment by TimOliver** [comment]
Hmm, that's rather curious! It looks like something is wrong with the primary key configuration. Is the console printing out anything during this crash as well?

**Comment by vipindhangar** [comment]
Actually we are not getting any error logs in the console.

**Comment by vipindhangar** [comment]
We are getting few logs, hope if this will be helpful.

2017-01-10 11:28:15.235 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03424] Was connected, and added as index: 23
2017-01-10 11:28:15.239 BookWithMe[606] <Debug> [Firebase/Database][I-RDB08205] Sending: {
	    d =     {
	        a = m;
	        b =         {
	            d =             {
	                audio = "";
	                "audio_duration" = 0;
	                "audio_md5" = "";
	                createdAt = "1484027895.164255";
	                groupId = fc9b072595c6028c0814f24c1ea496f9;
	                isDeleted = 0;
	                latitude = 0;
	                longitude = 0;
	                objectId = "-Ka5x8o7kAdi2M5eVTGU";
	                picture = "";
	                "picture_height" = 0;
	                "picture_md5" = "";
	                "picture_width" = 0;
	                senderId = JxOOJK8DHmMtDpRRYKsAFSDL29C2;
	                senderInitials = mm;
	                senderName = "mukeshpal.yashco";
	                status = Sent;
	                text = "AwGyZ7VthqFrq6ZOLks6Bt7weZM4zqcKs7TivIi3T97Md5tU7RsoLfuflReScX6hC6x6coJA/SbLPgjOrrBL2wLXs6IQGVfdNRojM9WkCqetjA==";
	                type = text;
	                updatedAt = "1484027895.164255";
	                video = "";
	                "video_duration" = 0;
	                "video_md5" = "";
	            };
	            p = "/Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU";
	        };
	        r = 71;
	    };
	    t = d;
	}
2017-01-10 11:28:15.246 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/audio
2017-01-10 11:28:15.247 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/audio_duration
2017-01-10 11:28:15.249 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/audio_md5
2017-01-10 11:28:15.250 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/createdAt
2017-01-10 11:28:15.251 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/groupId
2017-01-10 11:28:15.253 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/isDeleted
2017-01-10 11:28:15.254 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/latitude
2017-01-10 11:28:15.255 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/longitude
2017-01-10 11:28:15.256 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/objectId
2017-01-10 11:28:15.258 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/picture
2017-01-10 11:28:15.258 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/picture_height
2017-01-10 11:28:15.258 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/picture_md5
2017-01-10 11:28:15.258 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/picture_width
2017-01-10 11:28:15.262 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/senderId
2017-01-10 11:28:15.263 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/senderInitials
2017-01-10 11:28:15.264 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/senderName
2017-01-10 11:28:15.265 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/status
2017-01-10 11:28:15.266 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/text
2017-01-10 11:28:15.267 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/type
2017-01-10 11:28:15.269 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/updatedAt
2017-01-10 11:28:15.287 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/video
2017-01-10 11:28:15.290 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/video_duration
2017-01-10 11:28:15.290 BookWithMe[606] <Debug> [Firebase/Database][I-RDB03805] Cancelling transactions at path: /Message/fc9b072595c6028c0814f24c1ea496f9/-Ka5x8o7kAdi2M5eVTGU/video_md5

**Comment by TimOliver** [comment]
Sorry @vipindhangar but I don't think there's enough information to help here still. :(

There should be some kind of output in the console explaining what kind of error occurred. Are you sure you can't retrieve a stack trace for this crash?

What is the contents of the `message` dictionary that you're providing? Is a valid primary key value in there?

It would definitely help if you could share the code with us. :)

**Comment by vipindhangar** [comment]
OK, if there is need to share the code, how I would be sharing the code? 
Can a zip file attached here?

**Comment by TimOliver** [comment]
Sure! If you don't mind the code being public, you can zip it and upload it here. Otherwise you can send it to help@realm.io in private.

**Comment by vipindhangar** [comment]
This type of crash logs are generated now on console : -

Cannot get file size: (null)
  (null)
2017-01-12 12:53:49.899 BookWithMe[3779:68090] unexpected response data (uploading to the wrong URL?)
{
  "name": "L2FJTZPKmBQerImAm681kiriezk2/profile_picture/1484205828.jpg",
  "bucket": "demobwm-ec496.appspot.com",
  "generation": "1484205829638000",
  "metageneration": "1",
  "contentType": "application/json; charset=UTF-8",
  "timeCreated": "2017-01-12T07:23:49.579Z",
  "updated": "2017-01-12T07:23:49.579Z",
  "storageClass": "STANDARD",
  "size": "114",
  "md5Hash": "Muk53cdk+0y4BoekUc/NPg==",
  "contentEncoding": "identity",
  "contentDisposition": "inline; filename*=utf-8''1484205828.jpg",
  "crc32c": "EVn86Q==",
  "etag": "CPCO/8mJvNECEAE=",
  "downloadTokens": "3d787194-c7cf-48d2-a8d1-d9c445db1c10"
}
2017-01-12 12:53:49.900 BookWithMe[3779:68090] beginChunkFetches has unexpected upload status for headers {
    "Access-Control-Allow-Origin" = "*";
    "Content-Length" = 617;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Thu, 12 Jan 2017 07:23:49 GMT";
    Server = UploadServer;
    "access-control-expose-headers" = "X-Firebase-Storage-XSRF";
    "alt-svc" = "quic=\":443\"; ma=2592000; v=\"35,34\"";
    "x-content-type-options" = nosniff;
    "x-guploader-uploadid" = "AEnB2UoW2-rsjYKAABfnGukCgg4apLHVoo6LzbnD3FtVYqEc_dNln1VLLwmftEZNH7klg_fxOD1xrz6mWGAaUyCaXYRxZK_17ZxVdcaW0n7HVKXDduphpAk";
}
2017-01-12 12:53:49.900 BookWithMe[3779:68090] Premature failure: upload-status:"(null)"  location:(null)

**Comment by vipindhangar** [comment]
There is a good new for us. We have resolved the crash issue which we were facing.
Thanks for coordination and help. :-)

In future if we find any issue we will surely contact you.
Thanks Again!!!
Happy Weekend.

**Comment by TimOliver** [comment]
Oh! That's good to hear! How did you resolve it in the end?
No worries! Let us know if you have any more issues!

Have a nice weekend!

**Comment by vipindhangar** [comment]
Hi Tim,

Actually the code was missing -

- (void)actionBack
//-------------------------------------------------------------------------------------------------------------------------------------------------
{
	//---------------------------------------------------------------------------------------------------------------------------------------------
	// This can be removed once JSQAudioMediaItem audioPlayer issue is fixed
	//---------------------------------------------------------------------------------------------------------------------------------------------
	for (DBMessage *dbmessage in dbmessages)
	{
		if ([dbmessage.type isEqualToString:MESSAGE_AUDIO])
		{
			JSQMessage *jsqmessage = jsqmessages[dbmessage.objectId];
			AudioMediaItem *mediaItem = (AudioMediaItem *)jsqmessage.media;
			[mediaItem stopAudioPlayer];
		}
	}
	//---------------------------------------------------------------------------------------------------------------------------------------------

	//---------------------------------------------------------------------------------------------------------------------------------------------
	[self actionCleanup];
	[Recent clearCounter:groupId];
	//---------------------------------------------------------------------------------------------------------------------------------------------
	[self.navigationController popViewControllerAnimated:YES];
}

- (void)actionCleanup
//-------------------------------------------------------------------------------------------------------------------------------------------------
{
	[NotificationCenter removeObserver:self];
	//---------------------------------------------------------------------------------------------------------------------------------------------
	[messages actionCleanup]; messages = nil;
	//---------------------------------------------------------------------------------------------------------------------------------------------
	[firebase removeAllObservers]; firebase = nil;
}

That's it.
