### ISSUE TITLE
pod install Realm fail  always！

### ISSUE THREAD

**Issue by xingyong723** [realm/realm-cocoa#4484]
pod 'Realm', '~> 2.1.2'
 
Today ， I install realm a few times， always fail

reason

[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 1.0.0-BETA-5.1
Downloading sync failed:
curl: (35) Server aborted the SSL handshake

**Comment by austinzheng** [comment]
Thank you for getting in touch with us!

Are you located in Mainland China? Sometimes our users from there have trouble downloading the prebuilt binary files. Please take a look at [this thread](https://github.com/realm/realm-cocoa/issues/2713) for some potential workarounds. If you have any more questions, please post again to this ticket. Thanks!

**Comment by jpsim** [comment]
Hi @xingyong723, I'm just following up on @austinzheng's last comment. Thanks!

**Comment by stel** [comment]
I'm closing this issue because we didn't get any response. @xingyong723 please feel free to reopen it if you need any further help.

**Comment by lonkly** [comment]
Well I am located in Ukraine and here's what I've got: 

Installing Realm (2.1.2)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 1.0.0-BETA-5.1
Downloading sync failed:
curl: (56) SSLRead() return error -9806

**Comment by stel** [comment]
@lonkly please take a look at https://github.com/realm/realm-cocoa/issues/2713 for some potential workarounds.

**Comment by mrramdhas** [comment]
**pod update --verbose**
