### ISSUE TITLE
RealmSwift List not saving after application close and re-open

### ISSUE THREAD

**Issue by MahmoudTarek** [realm/realm-cocoa#4487]
I have two RealmSwift objects:

```
final class ListDB: Object {
    dynamic var name:String?
    dynamic var server_id:String?

    let friends = List<Friend>()

    override static func primaryKey() -> String? {
        return "server_id"
    }
}
```
And

```
final class Friend: Object {
    dynamic var id:String?
    dynamic var name:String?

    let lists = LinkingObjects(fromType:ListDB.self, property: "friends")

    override static func primaryKey() -> String? {
        return "id"
    }
}
```
I try appending Friend to ListDB as the following:

```
let list = self.realm.object(ofType: ListDB.self, forPrimaryKey: "SomeListID")
let friend = self.realm.object(ofType: Friend.self, forPrimaryKey: "SomeFriendID")
if friend != nil && list != nil {
      try! self.realm.write {
            list?.friends.append(friend!)
      }
}
```
And it works fine if I try to

`
print(list?.friends)
`
It works fine while I'm still in same session but if I close the app and re-open it, the friends in the specified list are gone like they were never added, what am I doing wrong?

I'm using RealmSwift latest version, iOS 10.0 as deployment target.

I also tried to update the list after I've added friends, but it won't work neither.

```
try! self.realm.write {
    self.realm.add(list!, update: true)
}
```
Any help would be appreciated, Thanks in advance.

**Comment by austinzheng** [comment]
Thanks for getting in touch with us, and sorry you're experiencing difficulties.

Nothing in your code stands out as incorrect to me. Would you be willing to send over a reproduction case, so we can examine it in more detail? Also, how are you constructing your `self.realm` -- are you using the default configuration, or building one yourself? Make sure you're not creating a temporary, "in-memory" Realm.

**Comment by MahmoudTarek** [comment]
I have been using a global 
    let realm = try! Realm()
Adding a new instance of realm in the same scope solved the issue, thanks for your advice 👍

**Comment by MahmoudTarek** [comment]
False alarm, the problem still occurs, my bad.

**Comment by austinzheng** [comment]
Please send us a reproduction case so we can take a closer look at the problem. Thanks!

**Comment by MahmoudTarek** [comment]
Excuse me, what exactly is a reproduction case?

**Comment by MahmoudTarek** [comment]
[Archive.zip](https://github.com/realm/realm-cocoa/files/676767/Archive.zip)

Here we go, I hope that this is what you've asked for!

**Comment by austinzheng** [comment]
Are you sure the `group_id` you're using to fetch the `list` property is the same between runs of your app?

By "reproduction case" I mean a minimal project, with as few dependencies as possible, that can be immediately run to demonstrate the problem.

**Comment by MahmoudTarek** [comment]
[Realm Test 2.zip](https://github.com/realm/realm-cocoa/files/680022/Realm.Test.2.zip)

I've created this example and surprisingly it worked fine..
I don't know what am I doing wrong in my main project. But it worked fine in this example.
