### ISSUE TITLE
'Realm/Realm.h' file not found

### ISSUE THREAD

**Issue by Rcrosp** [realm/realm-cocoa#4488]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 2.1.2

Xcode version: 8.2

iOS/OSX version: iOS10

Dependency manager + version:

**Comment by austinzheng** [comment]
We need more information to help.

Are you using CocoaPods, Carthage, or downloading the binaries directly from GitHub?

If you are using CocoaPods or Carthage, which version are you using?

Do you have a sample project you can share that exhibits this error?

**Comment by jpsim** [comment]
Hi @Rcrosp, I'm just following up on @austinzheng's last comment. Thanks!

**Comment by Rcrosp** [comment]
target 'app' do
pod 'Realm'
end
Use CocoaPods: "pod install"
Realm/Realm.h' file not found

**Comment by jpsim** [comment]
@Rcrosp could you please post the full output of the following commands (without truncating anything):

```
$ pod --version
$ xcodebuild -version
$ xcode-select -p
$ pod deintegrate
$ pod install --verbose
```

**Comment by istx25** [comment]
Hi @Rcrosp. Would you be able to follow the instructions in @jpsim's last comment? Thanks.

**Comment by jpsim** [comment]
We need to close this since we haven't heard back from @Rcrosp in some time and this is likely not a Realm issue.
