### ISSUE TITLE
Override Realm file by another Realm file has same structure

### ISSUE THREAD

**Issue by hunganh0403** [realm/realm-cocoa#4491]
## Goals

Complete replace all objects from one Realm to other Realm.
At this post, i'm try to achieve that by delete all files of the RealmA need to be replaced, then copy all files of the RealmB will overriding to that path.

## Expected Results

RealmA should have same data as RealmB

## Actual Results

RealmA keeps its old data, RealmB can't override its data to RealmA

## Code Sample

````Swift
class Database {
    private let identifyName: String

    private lazy var realmConfiguration: Realm.Configuration = {
        var config = Realm.Configuration()
        config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent("\(self.identifyName).realm")
        return config
    }()

    private var realm: Realm {
        return try! Realm(configuration: self.realmConfiguration)
    }
    
    init(indentifyName: String) {
        self.identifyName = indentifyName
    }
    
    //MARK: add
    func addPet(withName name: String) {
        let obj = Pet()
        obj.name = name
        try! realm.write {
            self.realm.add(obj)
        }
    }

    //MARK: complete delete Realm file
    func deleteRealmFile() {
        try! realm.write {
            if let path = self.realmConfiguration.fileURL?.path {
                let pathLock = path + ".Lock"
                let pathManagement = path + ".Management"
                try! FileManager.default.removeItem(atPath: path)
                try! FileManager.default.removeItem(atPath: pathLock)
                try! FileManager.default.removeItem(atPath: pathManagement)
            }
        }
    }

    //MARK: copy file function
    func overrideByWriteCopy(toManager managerDataNeedToBeOverrided: Database) {
        let otherUrl = managerDataNeedToBeOverrided.realm.configuration.fileURL!
        managerDataNeedToBeOverrided.deleteRealmFile()
        try! self.realm.writeCopy(toFile: otherUrl)
    }
    
    func overrideByCopyFile(toManager managerDataNeedToBeOverrided: Database) {
        let thisUrl     = self.realm.configuration.fileURL!
        let otherUrl    = managerDataNeedToBeOverrided.realm.configuration.fileURL!
        managerDataNeedToBeOverrided.deleteRealmFile()
        try! FileManager.default.copyItem(at: thisUrl, to: otherUrl)
    }
}

class Pet: Object {
    dynamic var name: String = ""
}

let db1: Database = Database(indentifyName: "db1")
let db2: Database = Database(indentifyName: "db2")

// Insert code here to initialize your application
db1.addPet(withName: "1")
db2.addPet(withName: "A")
//db1: [1], db2: [A]

// db1.overrideByCopyFile(toManager: db2) // Already tried this, same result
db1.overrideByWriteCopy(toManager: db2)
//Result: db1: [1], db2: [A,2] 
//Expected: db1: [1], db2: [1,2] 

````

Sample project here:
[RealmUnicode.zip](https://github.com/realm/realm-cocoa/files/673792/RealmUnicode.zip)

## Version of Realm and Tooling

Realm version: "v2.1.2"

Xcode version: Version 8.1 (8B62)

Swift version: 3.0.1

OSX: 10.11.6 (15G1108)

**Comment by austinzheng** [comment]
Realm Swift doesn't support deleting a Realm's files after it's been opened.

Your options are to:
* Delete the original Realm files without opening the Realm, copy the new Realm files to the original location, and then open the Realm at then open the Realm at the original location.
* Open both Realm files, and then use the Realm APIs to delete objects from the first Realm and copy them from the second Realm to the first Realm.

You might want to investigate the `myRealm.deleteAll()` API to delete all objects from a Realm.

**Comment by hunganh0403** [comment]
Is there anyway to safely close the Realm while it has been opened (to delete it) ? 
My data is about thousands to millions and it need to be replaced completely each time update, so i rather a solution that can achieve it easily, not by taking some times to read all data to update. 

I've used realm.deleteAll() then copy all (`func overrideByDeleteAll` bellow)
Currently i'm using override data by compare two realm to insert/delete needed objects (`func overrideByCompare` bellow) (because my new data not use to completely different from old data)
````Swift
func enumerateAllItemThat(notBeingContainedByManager otherManager: HCDItemDataManager, andExecuteAction action: (HCDItemObject)->Void) {
    self.allItems.forEach {
        if otherManager.allItems.filterByPath(exactly: $0.path).isEmpty {
            action($0)
        }
    }
}
//MARK: - Override By delete and copy file
func overrideByCompare(toManager managerDataNeedToBeOverrided: HCDItemDataManager) {
//copy needed files
    self.writeWithBlock {
        self.enumerateAllItemThat(notBeingContainedByManager: managerDataNeedToBeOverrided) {
            managerDataNeedToBeOverrided.add(fromItem: $0.item)
        }
    }
//delete needed files
    managerDataNeedToBeOverrided.writeWithBlock {
        managerDataNeedToBeOverrided.enumerateAllItemThat(notBeingContainedByManager: self) {
            managerDataNeedToBeOverrided.realm.delete($0)
        }
    }
}
//MARK: - Override By delete all then copy all
func overrideByDeleteAll(toManager managerDataNeedToBeOverrided: HCDItemDataManager) {
    managerDataNeedToBeOverrided.deleteAll()
    self.allItems.forEach {
        managerDataNeedToBeOverrided.add(fromItem: $0.item)
    }
} 
````
If there're any better solutions or any ways to improve my code, please let me know.
Thank you guys a lot.

**Comment by austinzheng** [comment]
Hi, unfortunately Realm Cocoa does not support closing a Realm after it's been opened. Your options are to either copy the files before opening either Realm, or to use Realm's object APIs to delete and copy objects once the Realms are opened. Thanks for getting in touch with us!
