### ISSUE TITLE
The .realm file takes 900M

### ISSUE THREAD

**Issue by ghysrc** [realm/realm-cocoa#4492]
I am using realm in a swift project for months. I updated to the latest release (2.1.2) several days ago. My coworker just show me this problem.
![image](https://cloud.githubusercontent.com/assets/4082752/21496889/b0fc402e-cc5c-11e6-8147-39649d710367.png)
Every login user has an unique .realm file named by ID. So on  this test device, there are 10+ .realm file in the "Documents" folder. The rests are fine, they are only like 74k, 5M, etc. But only this file, it takes 939.5M ! But it only contains several tables and columns.
![image](https://cloud.githubusercontent.com/assets/4082752/21497049/98ba947e-cc5d-11e6-9b65-d7d0a65c5ffd.png)
And I only stored some strings in it, no data, just like this:
![image](https://cloud.githubusercontent.com/assets/4082752/21497106/e098cdec-cc5d-11e6-8050-b91dba64b0f6.png)
So I can't figure it out. What make this realm file so special? And how to avoid this?

**Comment by austinzheng** [comment]
Thanks for getting in touch and sorry to hear your Realm file got so big :(.

We recently had another user experience a similar issue. Perhaps the tips in that thread might be of use to you? [See here](https://github.com/realm/realm-cocoa/issues/4353). We're also making changes to the underlying storage engine to mitigate this issue; see [this ticket](https://github.com/realm/realm-core/issues/2343).

**Comment by ghysrc** [comment]
OK, I understand. I will use "writeCopy" for a temporary solution.

**Comment by austinzheng** [comment]
Great! Please note that you should use `writeCopy` before opening that Realm at all; once you open a Realm you shouldn't touch its files until the next time the app is launched.

Hope that helps, and if you have any more problems feel free to open a new ticket or comment on this one!
