### ISSUE TITLE
Diacritic insensitive filtering not supported on string type

### ISSUE THREAD

**Issue by tirrorex** [realm/realm-cocoa#4493]
## Goals
filtering my results with a diacritic insensitive

## Expected Results
Getting filtered results

I expected the predicate to work according to your cheatsheet : https://realm.io/news/nspredicate-cheatsheet/

## Actual Results
My app crashed with an error located in realm, after some research in the trace i bumped on a method with this two lines : 
        bool diacriticInsensitive = (predicateOptions & NSDiacriticInsensitivePredicateOption);
    RLMPrecondition(!diacriticInsensitive, @"Invalid predicate option",
                    @"NSDiacriticInsensitivePredicateOption not supported for string type");

I didn't see this in the doc, if NSDiacriticInsensitivePredicateOption is not supported for string type, with what type is it supported???

What did happened instead?  
e.g. the stack trace of a crash
(how do i get this for an export?)

## Steps to Reproduce

You need to create a realm object with a method taking in parameter a text and trying to filter results with a CONTAINS[d] on the text parameter.

## Code Sample

This is the method i used:

        static func getFilteredArtists(filter: String) -> Results<Artist>? {
        do {
            let aRealm = try Realm()
            let sortProperties = [SortDescriptor(property: "addeektFollowers", ascending: false), SortDescriptor(property: "facebookFollowers", ascending: false)]
            let artists = aRealm.objects(Artist).sorted(sortProperties).filter("name CONTAINS[d] %@ AND deleted == %@", filter, false)
            return artists
        } catch {
            print(error)
        }
        return nil
    }

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?
realmswift v 2.1.0

Xcode version: ?
7.3.1

iOS/OSX version: ?
ios 10.1.1

Dependency manager + version: ?
cocoapods 1.1.1

**Comment by tirrorex** [comment]
I fixed this temporarily by adding another variable to my realm object which contains the string i want to filter on already folded with diacritic.
Would like to know if you guys will implement the feature on realmswift though. Thanks

**Comment by bdash** [comment]
This is being tracked as part of #1490.
