### ISSUE TITLE
Only the values that exist are updated.

### ISSUE THREAD

**Issue by Abel94** [realm/realm-cocoa#4494]
## Goals

This should not be a bug, but I think the database should work for the fish.

Only the fields returned by the server are updated and the fields not provided by the server remain unchanged.

## Expected Results

It is expected that only the fields provided will be updated.

## Actual Results

In fact, the entire record has been updated, the server does not return the field is replaced by the model's default value.

## Steps to Reproduce & Code Sample

```swift
class Article: Object
{
    dynamic var author: Author?
    // others...
}

class Author: Object
{
    dynamic var isSubscribe = 0
    // others...
}

```

The first page - the list of articles: the server returns a list of articles, but only contains a simple author information, no isSubscribe field.
The second page - author information: the server returns a detailed author information, including isSubscribe field, if the user has been concerned about the author, then isSubscribe = 1, saved to Realm.

After the first page is refreshed, isSubscribe is overridden by the model's default value of 0.

So, I do not quite understand what to do to prevent this from happening.

## Version of Realm and Tooling

Realm version: 2.1.2

Xcode version: 8.2

iOS/OSX version: 10.2

**Comment by austinzheng** [comment]
Can you either post your code, or send us a reproduction case? There's not enough in your description for us to figure out what is going on.

**Comment by Abel94** [comment]
Thank you very much for your reply. I elaborate on the process. Because the code involved more, I simplified part of it.

## This is the article model and the author model.
```swift
class Article: Object
{
    dynamic var id = 0
    dynamic var title = ""
    dynamic var author: Author?
    dynamic var content = ""
    // others...
    
    func mapping(map: Map) {
        id      <- map["id"]
        title   <- map["title"]
        content <- map["content"]
        author  <- map["author"]
    }
}

class Author: Object
{
    dynamic var id = 0
    dynamic var nickname = ""
    dynamic var isSubscribe = 0
    // others...
    
    func mapping(map: Map) {
        id          <- map["id"]
        nickname <- map["nickname"]
        isSubscribe <- map["isSubscribe"]
    }
}
```

## The article list page.

 Get list, store.

```swift
class ArticleTableViewController: UIViewController
{
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // ... List of articles obtained from the server.
        api.request(.articles)
            .mapObject(Response<Article>.self)
            .subscribe(onNext: { response in
                guard let articles = response.content else { return }
                let realm = try! Realm()
                realm.write {
                    realm.add(articles, update: true)
                }
            })
            .addDisposableTo(self.disposeBag)
        // ... Others
    }
}
```

The server returns data that looks like this.
```json
{
    "content": [
        {
            "id": 1,
            "author": {
                "id": 1,
                "nickname": "Tom"
            },
            "title": "xxx",
            "content": "xxx"
        },
        {
            "id": 2,
            "author": {
                "id": 2,
                "nickname": "June"
            },
            "title": "xxx",
            "content": "xxx"
        }
        // others...
    ]
}
```

## Author Information page
Get author information, store.

```swift
class AuthorViewController: UIViewController
{
    override func viewDidLoad() {
        super.viewDidLoad()
        
        api.request(.author)
            .mapObject(Response<Author>.self)
            .subscribe(onNext: { response in
                guard let author = response.content else { return }
                let realm = try! Realm()
                realm.write {
                    realm.add(author, update: true)
                }
            })
            .addDisposableTo(self.disposeBag)
        
        // ... Others
    }
}
```

The server returns data that looks like this.
```json
{
    "content": {
        "id": 1,
        "nickname": "Tom",
        "isSubscribe": 1
    }
}
```

After obtaining the author information. At this point Tom's isSubscribe should be 1. after the article list page is refreshed, the isSubscribe becomes 0, but the article list page does not provide the isSubscribe field, but changes the value of isSubscribe.

I guess the model may be author isSubscribe default value is 0 caused, but how to avoid this happening? I did not find a good solution.

**Comment by austinzheng** [comment]
Can you set a breakpoint in the `realm.add` line in 

```
realm.write {
    realm.add(author, update: true)
}
```

and make sure that the fields in `author` are actually properly set? In particular, is `author.isSubscribe` equal to 1 at the point when you save it to the Realm?

Also, it's not obvious from your code where your `Author` object is coming from when you refresh your view controller.

**Comment by Abel94** [comment]
Yes, I see changes to isSubscribe using the Realm browser, and it was changed to 0 after the refresh.

**Comment by Abel94** [comment]
It seems this should not be realm problem.

very sorry!
