### ISSUE TITLE
uncaught exception in notifier thread: N5realm10LogicErrorE: Bad version number

### ISSUE THREAD

**Issue by kirtiparghi** [realm/realm-cocoa#4497]
I have integrated realm cocoa using carthage dependency tool. Here is the configuration that i have used,

Xcode : 8.2.1
Carthage File : github "realm/realm-cocoa" ~> 2.1.2
OS X : 10.11.5

I have tried different version of realm cocoa but "Bad Version Number" exception occurs in each version of realm cocoa.

Here i have mentioned stack trace which i got during this exception:

warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.
  thread #1: tid = 0x545ed, 0x015de212 Realm`-[RLMRealm beginWriteTransaction](self=<unavailable>, _cmd=<unavailable>) + 94 at RLMRealm.mm:435, queue = 'com.apple.main-thread'
    frame #0: 0x015de212 Realm`-[RLMRealm beginWriteTransaction](self=<unavailable>, _cmd=<unavailable>) + 94 at RLMRealm.mm:435 [opt]
    frame #1: 0x0062ee54 RealmSwift`RealmSwift.Realm.write (() throws -> ()) throws -> () + 52 at Realm.swift:808
    frame #2: 0x00114630 Sumondo`Sync.(type=Session, items=1 value, self=0x18841900)(Type, items : [Uploadable]) -> () + 152 at Sync.swift:344
    frame #3: 0x0010c668 Sumondo`Sync.(response=Alamofire.Response<AnyObject, Foundation.NSError> @ 0x005dab04, self=0x18841900, type=Session, items=1 value)(Type, items : [Uploadable]) -> ()).(closure #1) + 276 at Sync.swift:160
    frame #4: 0x008289f4 Alamofire`partial apply forwarder for reabstraction thunk helper from @callee_owned (@owned Alamofire.Response<__ObjC.NSData, __ObjC.NSError>) -> (@unowned ()) to @callee_owned (@in Alamofire.Response<__ObjC.NSData, __ObjC.NSError>) -> (@unowned ()) + 152 at ResponseSerialization.swift:0
    frame #5: 0x008284cc Alamofire`generic specialization <Alamofire.ResponseSerializer<Swift.AnyObject, __ObjC.NSError> with Alamofire.ResponseSerializer<Swift.AnyObject, __ObjC.NSError> : Alamofire.ResponseSerializerType in Alamofire, __ObjC.NSError with __ObjC.NSError : Swift.ErrorType in Foundation, Swift.AnyObject> of Alamofire.Request.(response <A where A: Alamofire.ResponseSerializerType> (queue : Swift.Optional<__ObjC.OS_dispatch_queue>, responseSerializer : A, completionHandler : (Alamofire.Response<A.SerializedObject, A.ErrorObject>) -> ()) -> Self).(closure #1).(closure #1) + 192 at ResponseSerialization.swift:142
    frame #6: 0x02f0db7e libdispatch.dylib`_dispatch_call_block_and_release + 10
    frame #7: 0x02f0db6a libdispatch.dylib`_dispatch_client_callout + 22
    frame #8: 0x02f12654 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 1680
    frame #9: 0x22ac9b6c CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
    frame #10: 0x22ac8066 CoreFoundation`__CFRunLoopRun + 1574
    frame #11: 0x22a17228 CoreFoundation`CFRunLoopRunSpecific + 520
    frame #12: 0x22a17014 CoreFoundation`CFRunLoopRunInMode + 108
    frame #13: 0x24007ac8 GraphicsServices`GSEventRunModal + 160
    frame #14: 0x270eb188 UIKit`UIApplicationMain + 144
    frame #15: 0x000ea5d8 Sumondo`main + 172 at AppDelegate.swift:18
    frame #16: 0x226bf872 libdyld.dylib`start + 2

  thread #4: tid = 0x54611, 0x227942f8 libsystem_kernel.dylib`kevent_qos + 24, queue = 'com.apple.libdispatch-manager'
    frame #0: 0x227942f8 libsystem_kernel.dylib`kevent_qos + 24
    frame #1: 0x02f1e470 libdispatch.dylib`_dispatch_mgr_invoke + 256
    frame #2: 0x02f0f83e libdispatch.dylib`_dispatch_mgr_thread + 38

* thread #7: tid = 0x5463f, 0x22294584 libc++abi.dylib`__cxa_throw, name = 'RLMRealm notification listener'
    frame #0: 0x22294584 libc++abi.dylib`__cxa_throw
  * frame #1: 0x0160bcfe Realm`void realm::LangBindHelper::advance_read<(anonymous namespace)::TransactLogValidator>(realm::SharedGroup&, (anonymous namespace)::TransactLogValidator&&, realm::VersionID) [inlined] void realm::SharedGroup::advance_read<(anonymous namespace)::TransactLogValidator>(this=<unavailable>)::TransactLogValidator*, realm::VersionID) + 260 at group_shared.hpp:915 [opt]
    frame #2: 0x0160bc5c Realm`void realm::LangBindHelper::advance_read<(anonymous namespace)::TransactLogValidator>(realm::SharedGroup&, (anonymous namespace)::TransactLogValidator&&, realm::VersionID) [inlined] void realm::_impl::SharedGroupFriend::advance_read<(anonymous namespace)::TransactLogValidator>(sg=<unavailable>)::TransactLogValidator*, realm::VersionID) at group_shared.hpp:1086 [opt]
    frame #3: 0x0160bc5c Realm`void realm::LangBindHelper::advance_read<(anonymous namespace)::TransactLogValidator>(sg=<unavailable>, observer=<unavailable>, version=<unavailable>)::TransactLogValidator&&, realm::VersionID) + 98 at lang_bind_helper.hpp:335 [opt]
    frame #4: 0x01607964 Realm`realm::_impl::transaction::advance(realm::SharedGroup&, realm::BindingContext*, realm::SchemaMode, realm::VersionID) [inlined] auto realm::_impl::transaction::advance(args=<unavailable>)::$_0::operator()<(anonymous namespace)::TransactLogValidator>((anonymous namespace)::TransactLogValidator&&) const + 308 at transact_log_handler.cpp:823 [opt]
    frame #5: 0x01607952 Realm`realm::_impl::transaction::advance(realm::SharedGroup&, realm::BindingContext*, realm::SchemaMode, realm::VersionID) [inlined] (anonymous namespace)::TransactLogObserver::TransactLogObserver<realm::_impl::transaction::advance(this=<unavailable>, context=<unavailable>, sg=<unavailable>, notifiers=<unavailable>)::$_0>(realm::BindingContext*, realm::SharedGroup&, realm::_impl::transaction::advance(realm::SharedGroup&, realm::BindingContext*, realm::SchemaMode, realm::VersionID)::$_0&&, realm::util::Optional<realm::SchemaMode>, realm::_impl::NotifierPackage&) + 190 at transact_log_handler.cpp:274 [opt]
    frame #6: 0x01607894 Realm`realm::_impl::transaction::advance(realm::SharedGroup&, realm::BindingContext*, realm::SchemaMode, realm::VersionID) [inlined] (anonymous namespace)::TransactLogObserver::TransactLogObserver<realm::_impl::transaction::advance(context=<unavailable>, sg=<unavailable>, notifiers=<unavailable>)::$_0>(realm::BindingContext*, realm::SharedGroup&, realm::_impl::transaction::advance(realm::SharedGroup&, realm::BindingContext*, realm::SchemaMode, realm::VersionID)::$_0&&, realm::util::Optional<realm::SchemaMode>, realm::_impl::NotifierPackage&) at transact_log_handler.cpp:262 [opt]
    frame #7: 0x01607894 Realm`realm::_impl::transaction::advance(sg=<unavailable>, context=<unavailable>, schema_mode=<unavailable>, version=<unavailable>) + 100 at transact_log_handler.cpp:822 [opt]
    frame #8: 0x01542588 Realm`(anonymous namespace)::IncrementalChangeInfo::advance_to_final(this=<unavailable>, version=<unavailable>) + 880 at realm_coordinator.cpp:468 [opt]
    frame #9: 0x01541c0a Realm`realm::_impl::RealmCoordinator::run_async_notifiers(this=<unavailable>) + 1182 at realm_coordinator.cpp:587 [opt]
    frame #10: 0x015416c2 Realm`realm::_impl::RealmCoordinator::on_change(this=0x17644d30) + 34 at realm_coordinator.cpp:410 [opt]
    frame #11: 0x0152da3e Realm`realm::_impl::ExternalCommitHelper::listen(this=<unavailable>) + 168 at external_commit_helper.cpp:217 [opt]
    frame #12: 0x0152e1a2 Realm`std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() [inlined] realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0::operator()() const + 82 at external_commit_helper.cpp:159 [opt]
    frame #13: 0x0152e178 Realm`std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() [inlined] std::__1::__invoke<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(decltype(std::__1::forward<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(fp)(std::__1::forward<>(fp0))), realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0&&) + 32 at __functional_base:416 [opt]
    frame #14: 0x0152e158 Realm`std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() [inlined] _ZNSt3__112__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS2_16RealmCoordinatorEE3$_0JEE9__executeIJEEEvNS_15__tuple_indicesIJXspT_EEEE(this=<unavailable>) at future:2348 [opt]
    frame #15: 0x0152e158 Realm`std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator(this=<unavailable>)() + 8 at future:2341 [opt]
    frame #16: 0x0152e0ba Realm`std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute(this=<unavailable>) + 86 at future:1031 [opt]
    frame #17: 0x0152e348 Realm`std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) [inlined] std::__1::__invoke<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*, void>(decltype(*(std::__1::forward<std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*>(fp0)).*fp(std::__1::forward<>(fp1))), void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*&&)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*&&) + 144 at __functional_base:383 [opt]
    frame #18: 0x0152e32c Realm`std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) [inlined] _ZNSt3__116__thread_executeIMNS_19__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS4_16RealmCoordinatorEE3$_0JEEEEEFvvEJPSA_EJLm1EEEEvRNS_5tupleIJT_DpT0_EEENS_15__tuple_indicesIJXspT1_EEEE at thread:347 [opt]
    frame #19: 0x0152e32c Realm`std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(__vp=<unavailable>) + 116 at thread:357 [opt]
    frame #20: 0x2283b85a libsystem_pthread.dylib`_pthread_body + 138
    frame #21: 0x2283b7ce libsystem_pthread.dylib`_pthread_start + 110
    frame #22: 0x22839724 libsystem_pthread.dylib`thread_start + 8

  thread #8: tid = 0x54640, 0x2277e8d0 libsystem_kernel.dylib`mach_msg_trap + 20, name = 'com.apple.NSURLConnectionLoader'
    frame #0: 0x2277e8d0 libsystem_kernel.dylib`mach_msg_trap + 20
    frame #1: 0x2277e6d4 libsystem_kernel.dylib`mach_msg + 40
    frame #2: 0x22ac9ac4 CoreFoundation`__CFRunLoopServiceMachPort + 136
    frame #3: 0x22ac7e4c CoreFoundation`__CFRunLoopRun + 1036
    frame #4: 0x22a17228 CoreFoundation`CFRunLoopRunSpecific + 520
    frame #5: 0x22a17014 CoreFoundation`CFRunLoopRunInMode + 108
    frame #6: 0x230689f6 CFNetwork`+[NSURLConnection(Loader) _resourceLoadLoop:] + 486
    frame #7: 0x233314a4 Foundation`__NSThread__start__ + 1148
    frame #8: 0x2283b85a libsystem_pthread.dylib`_pthread_body + 138
    frame #9: 0x2283b7ce libsystem_pthread.dylib`_pthread_start + 110
    frame #10: 0x22839724 libsystem_pthread.dylib`thread_start + 8

  thread #9: tid = 0x54643, 0x2277e8d0 libsystem_kernel.dylib`mach_msg_trap + 20, name = 'com.apple.CoreMotion.MotionThread'
    frame #0: 0x2277e8d0 libsystem_kernel.dylib`mach_msg_trap + 20
    frame #1: 0x2277e6d4 libsystem_kernel.dylib`mach_msg + 40
    frame #2: 0x22ac9ac4 CoreFoundation`__CFRunLoopServiceMachPort + 136
    frame #3: 0x22ac7e4c CoreFoundation`__CFRunLoopRun + 1036
    frame #4: 0x22a17228 CoreFoundation`CFRunLoopRunSpecific + 520
    frame #5: 0x22a57dd2 CoreFoundation`CFRunLoopRun + 98
    frame #6: 0x27d1ddb8 CoreMotion`___lldb_unnamed_function2162$$CoreMotion + 940
    frame #7: 0x2283b85a libsystem_pthread.dylib`_pthread_body + 138
    frame #8: 0x2283b7ce libsystem_pthread.dylib`_pthread_start + 110
    frame #9: 0x22839724 libsystem_pthread.dylib`thread_start + 8

  thread #10: tid = 0x54648, 0x22792eec libsystem_kernel.dylib`__select + 20, name = 'com.apple.CFSocket.private'
    frame #0: 0x22792eec libsystem_kernel.dylib`__select + 20
    frame #1: 0x22acef12 CoreFoundation`__CFSocketManager + 566
    frame #2: 0x2283b85a libsystem_pthread.dylib`_pthread_body + 138
    frame #3: 0x2283b7ce libsystem_pthread.dylib`_pthread_start + 110
    frame #4: 0x22839724 libsystem_pthread.dylib`thread_start + 8

  thread #11: tid = 0x54679, 0x22793864 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x22793864 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x22839b34 libsystem_pthread.dylib`_pthread_wqthread + 1036
    frame #2: 0x22839718 libsystem_pthread.dylib`start_wqthread + 8

  thread #12: tid = 0x546d0, 0x22793864 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x22793864 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x22839b34 libsystem_pthread.dylib`_pthread_wqthread + 1036
    frame #2: 0x22839718 libsystem_pthread.dylib`start_wqthread + 8

  thread #13: tid = 0x546d1, 0x22793864 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x22793864 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x22839b34 libsystem_pthread.dylib`_pthread_wqthread + 1036
    frame #2: 0x22839718 libsystem_pthread.dylib`start_wqthread + 8
Warning: hit breakpoint while running function, skipping commands and conditions to prevent recursion.

**Comment by austinzheng** [comment]
Thanks for getting in touch with us, and sorry you're having this problem. We're already tracking this issue in #4422, so I'm going to close this ticket. Please follow that one for updates.

**Comment by bmunkholm** [comment]
@kirtiparghi You didn't use the issues template which actually has an important question: Are you able to replicate this problem reliably? Any repo case/app would be really useful to move us further. Thanks!
