### ISSUE TITLE
Build fail: When I upgrading realm from 2.1.1 to 2.1.2

### ISSUE THREAD

**Issue by gyzerocc** [realm/realm-cocoa#4498]
## Goals

Build success!

## Expected Results

Build success!

## Actual Results

Headers folder was disappear when I use CocoaPods upgrading realm.
It cause an mistake:

/Users/LY/doctor-znjtys-ios/Pods/Realm/Realm/ObjectStore/src/collection_notifications.cpp:19:10: 'collection_notifications.hpp' file not found

And 

'Realm.h'file not found

## Steps to Reproduce

target 'app' do
  pod 'Realm', '2.1.2'
end
Use CocoaPods:  "pod install"

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

/Applications/Xcode.app/Contents/Developer
Xcode 8.2.1
Build version 8C1002

/Users/LY/.rvm/rubies/ruby-2.2.4/bin/pod
1.1.1
Realm (2.1.2)
Realm (= 2.1.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)


(not in use here)

/usr/local/bin/git
git version 2.10.2
```

**Comment by kishikawakatsumi** [comment]
@gyzerocc 
I believe that the compile error due to CocoaPods or Xcode cache issues.

Please see the troubleshooting section,
https://realm.io/docs/swift/latest/#reinstalling-via-dependency-managers

and try to perform the following commands to purge caches.

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
```

**Comment by gyzerocc** [comment]
OK,I have upgraded the realm to 2.1.2. thank you!
