### ISSUE TITLE
Automatic triggers to clean up realm

### ISSUE THREAD

**Issue by ammoqq** [realm/realm-cocoa#4510]
Could we have a feature that works as follows ? :

## Goals

Automatic triggers on realm objects

## Expected Results

I have database that stores a lot of data
I would like to invalidate objects after they are too old for my user and delete them. Could we have some auto notifications in realm that would auto-trigger such deletion ? 

Example:
I have an object called Listing
listing has "createdAT" property which is a Date type

I would like realm to send me notification when that objects createdAT date is older than 2 days. So that my app can auto delete it.

**Comment by istx25** [comment]
Hey @ammoqq, thank you for reaching out for support. I will look into your question and have someone respond with an answer as soon as possible. In the meantime, we appreciate your patience while we recover from backlog.

**Comment by stel** [comment]
Hi @ammoqq! I don't think this feature should be implemented in database itself however you can easily implement it in your app. You can query all the "old" objects periodically or, say, on app startup and delete it from Realm:

```Swift
let oldObjects = realm.objects(MyObject.self).filter("date < %@", specificDate)

try! realm.write {
    realm.delete(oldObjects)
}
```

Please check out the docs for more info about queries here: https://realm.io/docs/swift/latest/#queries

**Comment by istx25** [comment]
@stel's comment seems like a sufficient answer. @ammoqq, please feel free to file a new issue if you need any additional response. Closing.
