### ISSUE TITLE
Clarify in docs that methods with setter/getter signatures also can't be overridden/provided

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#4512]
See the following for context:

* https://twitter.com/AusinErck/status/816385936317526016
* http://stackoverflow.com/questions/41455166/realm-reserved-words
* https://realm.io/docs/swift/latest/#realm-object-setters--getters-cannot-be-overriden

**Comment by jpsim** [comment]
@chipotle is this something you could write? Should be very quick. I'm sure any member of the cocoa team would be happy to explain the situation if it's at all unclear.

Would you like us to file this elsewhere to help it get addressed? What process should we follow for docs fixes?

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
