### ISSUE TITLE
Downloading dependency: sync 1.0.0-BETA-5.1 error

### ISSUE THREAD

**Issue by qinfensky** [realm/realm-cocoa#4513]
Realm version: 2.1.2

Xcode version: 8.2.1

iOS/OSX version: 10.12.2

CocoaPods version: 1.2.0.beta.3

------------------------------------------
"pod install" integration error.

![image](https://cloud.githubusercontent.com/assets/7803520/21710703/586153de-d425-11e6-83ce-51643bf6a39e.png)

**Comment by jpsim** [comment]
Thank you for getting in touch with us!

Are you located in Mainland China? Sometimes our users from there have trouble downloading the prebuilt binary files. Please take a look at [this thread](https://github.com/realm/realm-cocoa/issues/2713) for some potential workarounds. If you have any more questions, please post again to this ticket. Thanks!

**Comment by qinfensky** [comment]
@jpsim 
Yes, I am a Chinese……

**Comment by jpsim** [comment]
I'm sorry for the inconvenience. Please refer to https://github.com/realm/realm-cocoa/issues/2713 for more information.
