### ISSUE TITLE
Can I use `Date` instead of `NSDate`?

### ISSUE THREAD

**Issue by Coeur** [realm/realm-cocoa#4514]
According to [cheatsheet](https://realm.io/docs/swift/latest/#cheatsheet), I'm supposed to use `NSDate` (and `NSData` too). Can I instead use the Foundation structs from Swift 3, `Date` (and `Data`), or not?

Examples:

    dynamic var valueA = Date()
    dynamic var valueB: Date? = nil

Any best practice on the matter?

ps: on a different subject, [this PR](https://github.com/apple/swift-evolution/pull/577), if accepted in the future, will cause `dynamic` to no longer infer `@objc` in Swift4.

**Comment by jdkelley** [comment]
I would also like to know if/when using `Date` and `Data` instead of `NSDate` and `NSData` will be acceptable.

**Comment by istx25** [comment]
Happy to hear you found #3979 and that it was helpful.
