### ISSUE TITLE
Duplicated table schemas in multiple database files

### ISSUE THREAD

**Issue by mobilinked** [realm/realm-cocoa#4517]
Hi Team,

## Goals

I am using realm databases in a macOS app

- One realm database (a .realm file) at default storage position
- Another one realm database file created by the app in a app group storage (to share data between the main macOS app and it's today widget app) 
```
if let directory: URL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "com.xxx.xxx") {
            let dbURL = directory.appendingPathComponent(TodayManager.dbFileName)
            let dbConfig = Realm.Configuration(fileURL: dbURL)
            if let db = try? Realm(configuration: dbConfig) {
                        .......
            }
}
```
Let call them as DB1 and DB2 

## Expected Results

The two databases will not impact each other 

#### Problem 2 - App crashed when access DB1 (not DB2) after add a field to a table of DB2 (not DB1)
```
final class DemoDbMap: Object {
    dynamic var id = "" 
    
    dynamic var name = "" 
    dynamic var newField = "" // added this field, then to run the application 
}
```
After added a new field, debug the app, exception throw at accessing DB1 (not DB2):
`let db = try! Realm()`

## Version of Realm and Tooling

Realm version: ?
2.1

Xcode version: ?
8.2

iOS/OSX version: ?
10.12.2

**Comment by kishikawakatsumi** [comment]
@mobilinked You can use `objectTypes` to separate the schemas by file.

```swift
let db1 = try! Realm(configuration: Realm.Configuration(objectTypes: [DemoDbMap.self]))
let db2 = try! Realm(configuration: Realm.Configuration(objectTypes: [AnotherMocel.self]))
```

**Comment by mobilinked** [comment]
Thanks @kishikawakatsumi. This solution works to separate table schemas, but auto migration does not work (even worse, as no exception) 

##Step 1
```
let db1 = try? Realm(configuration: Realm.Configuration(objectTypes: [table1.self, table2.self]))
let db2 = try? Realm(configuration:Realm.Configuration(fileURL: url, objectTypes: [table3.self]))
```
Clean the run-time folders include the old .realm files 

##Result of step 1
Works without problem, the datatable schemas not be cloned (db1 just include table1, table 2, db2 just includes table3) 

##Step 2
Add a new filed to table3 (of db2, db2 in a app group storage) 
'dynamic var testing = "" '

##Result of step 2
Test app again, not no exception raised when access db1 (not db2) - before this solution, after add a new field to table3, when access db1, exception raised 
But now: **access db2 return nil** 
`let db2 = try? Realm(configuration:Realm.Configuration(fileURL: url, objectTypes: [table3.self]))`

##Step3 
Add a new filed to table1 (of db1, db1 in default app storage) 
'dynamic var testing = "" '

##Result of step3
now: **access db1 return nil** 
`let db1 = try? Realm(configuration: Realm.Configuration(objectTypes: [table1.self, table2.self]))`

**Comment by kishikawakatsumi** [comment]
@mobilinked `try?` ignored any errors. It hides what error has happened. Please use `try!` at the moment for investigating. `try? Realm(...)` returning `nil` means that an error occurs.

You separate schemas for `db1` and `db2`, it seems fine.

```swift
let db1 = try! Realm(configuration: Realm.Configuration(objectTypes: [table1.self, table2.self]))
let db2 = try! Realm(configuration:Realm.Configuration(fileURL: url, objectTypes: [table3.self]))
```

Then you added a new field to `table3`. It does not affect db1. But `db3` needs migration.


```swift
// Leave this as-is
let db1 = try! Realm(configuration: Realm.Configuration(objectTypes: [table1.self, table2.self]))

// This needs migration, because `table3` was added a new property
let db2 = try! Realm(configuration:Realm.Configuration(
    fileURL: url, 
    objectTypes: [table3.self]),
    schemaVersion: 1,
    migrationBlock: {...}
)
```

Then you added a new property to `table1`. Leave `db2` as-is, but `db1` needs migration.

```swift
// db1 needs migration, because `table3` was added a new property
let db1 = try! Realm(configuration: Realm.Configuration(
    objectTypes: [table1.self, table2.self]),
    schemaVersion: 1,
    migrationBlock: {...}
)

// Leave db2 as-is
let db2 = try! Realm(configuration:Realm.Configuration(
    fileURL: url, 
    objectTypes: [table3.self]),
    schemaVersion: 1,
    migrationBlock: {...}
)
```

**Comment by mobilinked** [comment]
Thanks much @kishikawakatsumi 

(I thought the migration for adding fields is automatic)
