### ISSUE TITLE
Filter for object contain list returns more result thatn expected

### ISSUE THREAD

**Issue by winniepooh001** [realm/realm-cocoa#4518]
## Goals
I want to be able to filter an object by the child property (a list)
I have an object called account type
class accountType: Object{
...
account_type = ""
accounts = List<Accounts>
}
class Accounts: Object{
account_type = ""
account_name = ""
...
}

## Expected Results
I expect to see only the parent and the child that meets the requirement
the account type with accounts filtered to only account_name that matches the filter condition
## Actual Results
I receive the account_type and all its children, including these that does not meet the filter condition

## Steps to Reproduce
accountsList = [Accounts(value:["account_type":"Cash","account_name":"Gift Card"]),Accounts(value:["account_type":"Cash","account_name":"Store Credit"])]
accountType = AccounType(value: ["account_type": "Cash","accounts":accountsList])
## Code Sample
 func searchBar(searchBar: SearchBar, didChange textField: UITextField, with text: String?) {
        let searchText = textField.text!
        let predicate = "ANY accounts.compoundKey CONTAINS[c] '\(searchText)'"
        print(predicate)
        searchResult = rawData.filter(predicate)
        isExpand = [Bool](repeatElement(false, count: searchResult.count))
        print(searchResult[0].accounts[0].compoundKey)
        print(searchResult[0].accounts[1].compoundKey)
        sectionTitles = [String]()
        for i in 0..<searchResult.count{
            sectionTitles.append(searchResult[i].account_type)
        }
        DispatchQueue.main.async{
            self.tableView.reloadData()
        }
    }
 
if the search text is "gift" I'm expecting to see only account_type object return with only one record of accounts 
## Version of Realm and Tooling
Realm version: 2.1.2

Xcode version: 8.2.1

iOS/OSX version: 10.12

Dependency manager + version: CocoaPod

Thank you :)

**Comment by kishikawakatsumi** [comment]
@winniepooh001 It's intended behavior. The `AccountType` class has "Gift Card" account and "Store Credit" account as a relationship. The query that you performed means filtering the `AccountType` objects that match the predicate. The search text "gift" matches the `AccountType` object that has "Gift Card" account and "Store Credit". So the query returns the `AccountType` object, that has "Gift Card" account and "Store Credit".

If you'd like to filter `Accounts` objects, perform the query again for the `accounts` property.

```swift
let filteredAccounts = searchResult[0].accounts.filter("accountName CONTAINS[c] %@", "gift")
```

Or, add a reverse relationship property to `Accounts` like the following (see `accountTypes` property in `Accounts` class):

```swift
class AccountType: Object{
    ...
    dynamic var accountType = ""
    let accounts = List<Accounts>()
}
class Accounts: Object{
    ...
    dynamic var accountType = ""
    dynamic var accountName = ""
    let accountTypes = LinkingObjects(fromType: AccountType.self, property: "accounts")
}
```

Then query for the `Accounts` class like the following:

```swift
let accounts = realm.objects(Accounts.self).filter("accountName CONTAINS[c] %@", "gift")
```

To retrieve `AccountType` objects, use the reverse relationship property.

FYI: Please always use `NSPredicate`'s substitution syntax like `%@` and `%K`. String interpolation in Swift causes unexpected behaviors.

**Comment by winniepooh001** [comment]
Thank you. In general, if the objects are all interconnected in some ways, could I have many reverse relationship (to different objects) in one object? Akin to sql  of a central mapping table.

**Comment by stel** [comment]
@winniepooh001 you can define many reverse relationship in one object if that object is linked by other objects with to-many relationship, see more in [docs](https://realm.io/docs/swift/latest/#inverse-relationships).

**Comment by istx25** [comment]
Do you have any other questions or follow-up, @winniepooh001?

**Comment by winniepooh001** [comment]
Thank you,
