### ISSUE TITLE
If submodules are necessary for success of basic build, they should in main git repo

### ISSUE THREAD

**Issue by xyzisinus** [realm/realm-cocoa#4519]
I run into issue #4330, too.  It turns out I need to 

git submodule update --init --recursive

However, if the submodules are necessary for basic build to succeed, they should NOT be submodules.  They should be integral part of the main git repo.  That is, "git clone" should give the user the critical files in the current submodules.

**Comment by bdash** [comment]
The need to check out submodules is mentioned in the [repository's README file](https://github.com/realm/realm-cocoa#building-realm).
