### ISSUE TITLE
Delete Object from Realm and all Referenced Objects

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-cocoa#4522]
I have a realm `Objectd` containing another realm `Object`:

```
class User : Object {
    var address: Address!;
}

class Address: Object {

}
```

When I perform a delete on a given user:

```
try! self.realm.write {
    self.realm.delete(user);
}
```

The user is getting deleted correctly but the address is still present in realm. What do I have to do to not only delete the user but also ALL objects which are related to the deleted Object?

**Comment by kishikawakatsumi** [comment]
We have an issue tracking cascading deletes on https://github.com/realm/realm-cocoa/issues/1186, so you'll see any updates on that front over there. We are working on that.

Until then, you should delete related objects yourself.

```swift
try! self.realm.write {
    self.realm.delete(user.address);
    self.realm.delete(user);
}
```

**Comment by amrObjection** [comment]
Even Updating the Object , create a new linked objects , so we should only access this Object through the Object properties , and not use `Realm.Objects(type)` to access linked objects
