### ISSUE TITLE
Delete objects of type RandomAccessSlice deletes unexpectedly

### ISSUE THREAD

**Issue by tako3** [realm/realm-cocoa#4525]
## Goals

I would like to delete objects of type RandomAccessSlice as Array does.

## Expected Results

Deletes given objects of type RandomAccessSlice.

## Actual Results

Deletes unexpected objects.

## Steps to Reproduce & Code sample

- Realm object for example:

```swift
class MyObject: Object {
    dynamic var i: Int = 0
}
```

- Code sample

```swift
func test() {
  let realm = try! Realm()
  // Add MyObject to Realm
  for i in 0..<5 {
    let myObject = MyObject()
    myObject.i = i
    try? realm.write {
      realm.add(myObject)
    }
  }
  // Retrieve MyObject
  let myObjects = realm.objects(MyObject.self).sorted(byProperty: "i")
  print("Added")
  myObjects.forEach { print($0.i) } // outputs: 0, 1, 2, 3, 4
  // Take first two of MyObject
  // sliced contains MyObject of variable "i" with value 0 and 1 since I sorted with "i"
  let sliced: RandomAccessSlice = myObjects[0..<2]
  print("Sliced")
  sliced.forEach { print($0.i) } // outputs: 0, 1
  // Delete the sliced from Realm
  try? realm.write {
    realm.delete(sliced)
  }
  // Retrieve MyObject for checking
  let myObjectsAfterDelete = realm.objects(MyObject.self).sorted(byProperty: "i")
  print("Result")
  myObjectsAfterDelete.forEach { print($0.i) } 
  // outputs: 1, 3, 4
  // expected outputs: 2, 3, 4
}
```

If I change 
realm.delete(sliced)
to
realm.delete(Array(sliced))
then, I get as expected

## Version of Realm and Tooling

Realm version: 2.1.2

Xcode version: 8.2

iOS/OSX version: 10.1

Dependency manager + version: Carthage 0.18.1

**Comment by tgoyne** [comment]
The problem is that `RandomAccessSlice` simply stores indices into the source collection, and deleting objects shifts what objects the subsequent indices refer to. After the first object is deleted, the object that was at `1` is now at `0`, and the object which was at `2` is now at `1`, so deleting `0..<2` actually deletes `0` and `2`.

`realm.delete(sliced.reverse())` would solve this without first copying the objects into an array.

**Comment by tako3** [comment]
Thank you for the help, now I see the problem 😄
