### ISSUE TITLE
Primary Key Migration

### ISSUE THREAD

**Issue by KelvinEC** [realm/realm-cocoa#4526]
I'm trying to change my Primary Key from one property of String type to ID of type Int.

I can't do that because i can't intercept migration to set the value of ID and Realm Migration is trying to put e-mail inside Int ID.

I'm receiving error: ```"Invalid value email@email.com of type String for int primary key.```

**Comment by istx25** [comment]
Hi @KelvinEC, thanks for reaching out for support. Would you be able to share a code example or sample project for us to review? Thanks.

**Comment by KelvinEC** [comment]
Hi @istx25

My Class before:
`class LKUserRealm: Object {

    dynamic var firstName: String?
    dynamic var lastName: String?
    dynamic var email: String = ""
    dynamic var phone: String?
    dynamic var id: Int = 0

    override static func primaryKey() -> String? {
        return "email"
    }
}`


My Class After:
`class LKUserRealm: Object {

    dynamic var firstName: String?
    dynamic var lastName: String?
    dynamic var email: String = ""
    dynamic var phone: String?
    dynamic var id: Int = 0

    override static func primaryKey() -> String? {
        return "id"
    }
}`

Migration Code:
` migration.enumerateObjects(ofType: LKUserRealm.className(), { oldObject, newObject in
                    if oldSchemaVersion < 3 {
                                newObject!["id"] = oldObject!["id"]
                    }
        })`

Ps: I've changed the Schema version correctly.

**Comment by KelvinEC** [comment]
The problem was fixed. Is a problem on other part of code that searching a User by e-mail as primary key. Thanks!

**Comment by istx25** [comment]
Awesome, happy to hear you resolved the issue. Cheers!
