### ISSUE TITLE
sometimes crash at group_shared.hpp line 933

### ISSUE THREAD

**Issue by Clear2** [realm/realm-cocoa#4529]
<img width="900" alt="27e154d6-a9e4-4d35-8abd-b4d52d06e3b4" src="https://cloud.githubusercontent.com/assets/8678314/21841525/6ed6cfe4-d81d-11e6-87f4-e98d7316e8fc.png">

**Comment by tgoyne** [comment]
Can you share any code which reproduces this? If you can't post anything publicly, you can also email it to help@realm.io.

**Comment by istx25** [comment]
Bringing attention back to the issue. @Clear2: Can you please share a snippet of code or better yet, a sample project which reproduces this issue? Cheers.

**Comment by istx25** [comment]
Bringing attention back to the issue. @Clear2: Can you please share a snippet of code or better yet, a sample project which reproduces this issue? Cheers.

**Comment by istx25** [comment]
Bringing attention back to the issue. @Clear2: Can you please share a snippet of code or better yet, a sample project which reproduces this issue? Cheers.

**Comment by jpsim** [comment]
Closing as it's likely that this was the same issue as #4422, and we haven't heard back in several weeks.
