### ISSUE TITLE
cascading delete by manually

### ISSUE THREAD

**Issue by NancyZY** [realm/realm-cocoa#4530]
Hi, guys, I want  to  cascading delete, but I met bug information "Terminating app due to uncaught exception 'RLMException', reason: 'Object has been deleted or invalidated.'"

here is my model : 

```swift
import RealmSwift
class Dog: Object {
    dynamic var name = ""
    dynamic var owner: Person? 
}

class Person: Object {
    dynamic var name = ""
    dynamic var birthdate = NSDate(timeIntervalSince1970: 1)
    let dogs = List<Dog>()
}
```

## Code Sample

```swift
let dogs = person.dogs
try! realm.write {
    realm.delete(dogs)
    realm.delete(person)
}
```

Before delete action, the person  exist, and I can sure about it. when I perform delete, then the app will occur the above information. please help me to solve the problem

RealmSwift version: 2.1.2
Xcode version: 8.2.1

**Comment by stel** [comment]
It seems that you have references either to `person` or `dogs` objects somewhere in your code and after deleting this objects they become invalid. You can try to set exceptions breakpoint in Xcode to find the exact place when this exception is generated.

**Comment by istx25** [comment]
Do you have any additional questions or follow-up, @NancyZY?
