### ISSUE TITLE
Copy object via initWithValue: keeps reference to source Realm in nested objects

### ISSUE THREAD

**Issue by bogosmer** [realm/realm-cocoa#4532]
## Goals

I want to copy a Realm object from one RLMRealm instance to another.
The Realm instances doesn't share backing store. 
The Realm object contains nested objects.
I'm using initWithValue: where the value is the original object.

Overall goal is to keep a memory Realm with a copy of an object, that can be deleted from the disk Realm before deleting the respective data on the backend. If the delete request to the backend should fail, I want to copy the object from the memory Realm back to the disk Realm as a fallback.

## Expected Results

I expect the object to be copied recursively via KVC such that the nested objects new objects with no attachment to the Realm instance of the source. 

## Actual Results

The nested objects are NOT copied but merely assigned to the property in the parent, so I get an exception when I add the object that has been created via initWithValue: to the memory Realm.

## Steps to Reproduce

Create 2 RLMObject subclasses where one of them reference the other.
Instantiate one of and assign the child to the parent.
Add to one Realm
Create a copy of the parent instance via initWithValue:
Add to another Realm

## Code Sample

Will provide on request, but the steps are so simple that I don't believe a sample is necessary

## Version of Realm and Tooling

Realm version: 2.1.2

Xcode version: 8.2.1

iOS/OSX version: iOS 8+

Dependency manager + version: Cocoapods 1.1.1

**Comment by stel** [comment]
Unfortunately deep copying of nested objects is not supported currently, we track this issue in https://github.com/realm/realm-cocoa/issues/3381. There is also an example how it could be implemented: https://github.com/realm/realm-cocoa/issues/3381#issuecomment-256243390

**Comment by istx25** [comment]
Awesome. Deep copying of nested objects is tracked as a feature request in issue #3381 and an example of how a workaround can be implemented can be found https://github.com/realm/realm-cocoa/issues/3381#issuecomment-256243390 (here). Closing.
