### ISSUE TITLE
Swift 3 "Cannot create asynchronous query while in a write transaction" exception

### ISSUE THREAD

**Issue by Jufina** [realm/realm-cocoa#4539]
## Goals

Fix a crashes.

## Expected Results

Transactions completes successful without crashes.

## Actual Results

Part of stack trace:

2017-01-12 14:53:56.523 MyApp [5631:145205] An uncaught exception was raised
2017-01-12 14:53:56.523 MyApp[5631:145205] Cannot create asynchronous query while in a write transaction
2017-01-12 14:53:56.523 MyApp[5631:145205] (
	0   CoreFoundation                      0x00007fff98e5c4f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff9874373c objc_exception_throw + 48
	2   Realm                               0x0000000100be4f2c -[RLMRealm beginWriteTransaction] + 77
	3   RealmSwift                          0x0000000100a47b8e _TFC10RealmSwift5Realm5writefzFzT_T_T_ + 46

## Steps to Reproduce

We migrated our project from swift 2 to swift 3. Realm changed from v1.0.2 to v2.1.1.
Some of transactions worked in past now crashes.
On iOS same transactions works good. On OSX it's throws exception.

## Code Sample

    let realm = try Realm()
    let allMessages = realm.objects(Message.self)
    let messages = allMessages.filter("(state == 1) AND (dateSent <= %@)",  dateSent)

    try realm.write ({
        messages.forEach { message in message.state = .seen }
    })

## Version of Realm and Tooling

Realm version: Realm v2.1.1

Xcode version: 8.2.1

iOS/OSX version: iOS (10.2) OSX (10.12)

Dependency manager + version: Carthage v0.18.1

**Comment by tgoyne** [comment]
Are you using Realm notification elsewhere in your app? The stack trace may simply be misleading, but if it is accurate then the exception is being thrown from within `beginWriteTransaction`, which would indicate either a bug in Realm or that you're doing something from within a notification block which is causing it.

**Comment by istx25** [comment]
@Jufina: Just bringing attention back to @tgoyne's question: _Are you using Realm notification elsewhere in your app?_

Some additional information would be appreciated. :)

**Comment by istx25** [comment]
Bringing attention back to my request, @Jufina.

>@Jufina: Just bringing attention back to @tgoyne's question: _Are you using Realm notification elsewhere in your app?_

**Comment by Jufina** [comment]
Solved this.
The issue is about that Realm handle block is called while in write transaction.
We just used a main queue for handler.

```
fileprivate func obtainDialoguesChanges(_ changes: RealmCollectionChange<Results<Dialogue>>) {
        DispatchQueue.main.async {
            switch changes {
            case .initial:
                self.tableView.reloadData()
                break
            case .update(_, let deletions, let insertions, let modifications):
                let insertionsIdxSet = NSMutableIndexSet()
                let deletionsxSet = NSMutableIndexSet()
                let modificationsIdxSet = NSMutableIndexSet()
                
                if insertions.count > 0 {
                    insertions.forEach{insertionsIdxSet.add($0)}
                }
                
                if deletions.count > 0 {
                    deletions.forEach{deletionsxSet.add($0)}
                }
                
                if modifications.count > 0 {
                    modifications.forEach{modificationsIdxSet.add($0)}
                }
                
                self.tableView.beginUpdates()
                self.tableView.removeRows(at: deletionsxSet as IndexSet, withAnimation: .effectFade)
                self.tableView.insertRows(at: insertionsIdxSet as IndexSet, withAnimation: .effectFade)
                self.tableView.reloadData(forRowIndexes: modificationsIdxSet as IndexSet, columnIndexes: IndexSet(integer: 0))
                self.tableView.endUpdates()
                
                break
                
            default:
                break
            }
            
            self.updateTableView()
        }
    }
```

**Comment by istx25** [comment]
@Jufina: Do you need any more assistance with this issue in particular?

**Comment by Jufina** [comment]
@istx25 
No, thanks for help with notifications handler. It works now.

**Comment by istx25** [comment]
Awesome, good to hear. :-)

**Comment by Gurpartap** [comment]
Thanks @Jufina. That fixed it for me too.

For reference, I was getting `libc++abi.dylib: terminating with uncaught exception of type NSException` exception on a `Realm().write {}` call. It wasn't printing that particular exp in the console. Console only said blah NSException useless blah. I tracked it down through breakpoint stepping in.

Wrapping the notification callbacks to run in main thread fixed it.
