### ISSUE TITLE
Stuck on problem with ObjectMapper and Realm

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#4541]
Stuck with Object mapper and Realm -- JSON comes in form of dictionary and object mapper expects me to declare as dictionary but realm does not accept it.

These are my models:

```swift
class UserInfo:Object,Mappable {
    var name:String?
    var identifier:String?
    var accountType:String?
    var devices:[String:UserDevice]?
    
    required init?(map: Map) {
    
    }

    // Mappable
    func mapping(map: Map) {
        name <- map["username"]
        identifier <- map["identifier"]
        accountType <- map["accountType"]
        devices <- map["devices"]
    }
}

class UserDevice:Object,Mappable {
    var deviceName:String?
    var deviceType:String?
    var deviceIdentifier:String?

    required init?(map: Map) {

    }

    // Mappable
    func mapping(map: Map) {
        deviceName <- map["name"]
        deviceType <- map["type"]
        deviceIdentifier <- map["identifier"]
    }
}
```

This is my JSON:

```
{
username = santhosh;
"identifier" = "IDJSDJSJS";
configstatus = SET;
configtype = DEFAULT;
"data_center" = "abc.bees.com";
devices = {
"Ankita\LKKKK" = {
identifier = LJJDFDD;
name = "Ankita iPAD";
type = iPad;
};
"ARUN\LKKKHJH" = {
identifier = LJJDFDFFD;
name = "ARUN iPhone";
type = ipHone;
};

accountStatus = 2;
acctype = Test;
```

**Comment by istx25** [comment]
Hey @santhoshs5, thank you for reaching out for support. Would you be able to clarify a few things for me so we can better assist you?

1. What versions of Xcode, ObjectMapper and Realm are you using?
2. Can you provide the code where you actually transform the JSON to a Realm object?
3. Where specifically in your code does "Realm not accept it"?

Please provide any extra details that you can. :-)

**Comment by santhoshs5** [comment]
Xcode version : 8.2 Objectmapper :2.2  Realm : 2.2.0

UserInfo Object  : 


class UserInfo:Object,Mappable {
    var name:String?
    var identifier:String?
    var accountType:String?
    var devices:[String:UserDevice]? // This object should be declared this other wise ObjectMappper does not understand about this.Because JSON is coming in the form of Array of dictionaries.

 var devices:List<UserInfo>? // I have tried this also 
    
    required init?(map: Map) {
    
    }
    // Mappable
    func mapping(map: Map) {
        name <- map["username"]
        identifier <- map["identifier"]
        accountType <- map["accountType"]
        devices <- map["devices"] //  Tried this also devices <- map["devices",ListTransform<UserDevice>] 
    }
}

class UserDevice:Object,Mappable {
    var deviceName:String?
    var deviceType:String?
    var deviceIdentifier:String?

    required init?(map: Map) {

    }

    // Mappable
    func mapping(map: Map) {
        deviceName <- map["name"]
        deviceType <- map["type"]
        deviceIdentifier <- map["identifier"]
    }
}


I am trying convert UserInfo object using 

Alamofire.request.response(Dataresponse<userInfo>)   {

let userInfo = response.result.value // this is 
}


I have tried using ObjectMapper+Realm where I can declare as ListTransform You can refer in my commnets .




MY JSON:


{
username = santhosh;
"identifier" = "IDJSDJSJS";
configstatus = SET;
configtype = DEFAULT;
"data_center" = "evs.idrive.com";
devices = {
"Ankita\LKKKK" = {
identifier = LJJDFDD;
name = "Ankita iPAD";
type = iPad;
};
"ARUN\LKKKHJH" = {
identifier = LJJDFDFFD;
name = "ARUN iPhone";
type = ipHone;
};

accountStatus = 2;
acctype = Test;
}

**Comment by stel** [comment]
The first issue I've noticed in your code is that your models' properties are not declared as `dynamic` (see [docs](https://realm.io/docs/swift/latest/#property-attributes)). Second: if you want to have relationship between `UserInfo` and `UserDevice` you should use `List` type and declare this property as `let devices = List<UserDevice>()` (see [docs](https://realm.io/docs/swift/latest/#to-many-relationships) for more info). However the `List` type is not supported by ObjectMapper out of the box so you'll probably need to implement your own `TransformType` to map JSON to your models. See more info and examples here: https://github.com/Hearst-DD/ObjectMapper/issues/143

**Comment by santhoshs5** [comment]
I am using dynamic that I missed it while writing in Git.I will check the tagged github link and let  you know if it solves. But I tried with List type and LIst transform specified by Objectmapper+Realm it was not working.

**Comment by stel** [comment]
Awesome! Let us know if you have any further Realm related questions.
