### ISSUE TITLE
Upgrade from 2.1.1 to 2.2.0 causes missing references warnings

### ISSUE THREAD

**Issue by slashburn** [realm/realm-cocoa#4550]
## Goals
A clean compilation of Realm without warnings. 

## Actual Results
When I upgrade from Realm 2.1.1. to 2.2.0, I get 4 warnings in my workspace as shown in the screenshots. My version control shows me that these files must indeed have been removed.
Will the warnings cause any problems? Is Realm 2.2.0 stable and shippable?

<img width="310" alt="modified" src="https://cloud.githubusercontent.com/assets/7759983/21966438/61b30270-db73-11e6-910a-70a6758f8efa.png">

<img width="273" alt="screenshot 2017-01-15 22 28 11" src="https://cloud.githubusercontent.com/assets/7759983/21966447/8973738a-db73-11e6-9b1e-334cc289da04.png">

## What did happened instead?  
The project compiled with 4 warnings, somehow the .xcworkspace must contain some references to deleted files

## Steps to Reproduce
Upgrade from an existing Realm 2.1.1. project to Realm 2.2.0 by running pod update in the console.

## Version of Realm and Tooling

Realm version: 2.2.1

Xcode version: 8.2.1

iOS/OSX version: iOS 10.2. / macOS El Capitan

Dependency manager + version: Cocoapods 1.1.1

**Comment by stel** [comment]
These files have been removed in https://github.com/realm/realm-object-store/pull/157, so if you have Realm in your working copy you need to update it. However you can consider to not to check out `Pods` folder into your repo, see more info [here](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control).

**Comment by slashburn** [comment]
Thanks for your answer stel. I guess Xcode was a little confused yesterday (I installed Realm 2.2.0) When I reopened the project today the warnings were gone.
So it was probably an Xcode problem.
