### ISSUE TITLE
Encrypted deleted realm conflicts when creating new

### ISSUE THREAD

**Issue by netgfx** [realm/realm-cocoa#4553]
Hello,

## Goals

I want to delete an encrypted realm file and recreate it at a later point in time (without closing the App)

## Expected Results

The deleted Realm file to be deleted and not conflict when trying to create another in the same path.

## Actual Results

Realm file when trying to create it throws error that the Realm file is already created with another encryption key.

**Note**: If I close the App and restart it and try to create a new encrypted Realm it will succeed.

## Steps to Reproduce

Delete an encrypted Realm file:

```
var realmURL = Realm.Configuration.defaultConfiguration.fileURL!.deletingLastPathComponent().appendingPathComponent("something.realm")
        
        let result = FileManager.default.fileExists(atPath: realmURL.path)
        
        let realmURLs = [
            realmURL,
            realmURL.appendingPathExtension("lock"),
            realmURL.appendingPathExtension("log_a"),
            realmURL.appendingPathExtension("log_b"),
            realmURL.appendingPathExtension("note")
        ]
        for URL in realmURLs {
            do {
                try FileManager.default.removeItem(at: URL)
            } catch {
                // handle error
            }
        }
```

and later on try to create another

```
let _namePath = "something.realm"
                let realmURL = Realm.Configuration.defaultConfiguration.fileURL!.deletingLastPathComponent().appendingPathComponent("something.realm")
           
                var configuration = Realm.Configuration(
                    encryptionKey: key as Data,
                    schemaVersion: 1,
                    migrationBlock: { migration, oldSchemaVersion in
                        // We haven’t migrated anything yet, so oldSchemaVersion == 0
                        if (oldSchemaVersion < 1) {
                            // Nothing to do!
                            // Realm will automatically detect new properties and removed properties
                            // And will update the schema on disk automatically
                        }
                })
                configuration.fileURL = configuration.fileURL!.deletingLastPathComponent().appendingPathComponent(_namePath)
                do {
                    try let someRealm = Realm(configuration: configuration)
                } catch {
                    print(error)
                }
```

## Code Sample

as seen above

## Version of Realm and Tooling

 `2.1.2`

Realm version: 2.1.2

Xcode version: 8.2.1

iOS/OSX version: Siera 10.12.2

Dependency manager + version: Carthage

**Comment by stel** [comment]
Realm doesn't support deleting files after it's opened, so I suggest you either delete all the objects from your existing realm with `Realm.deleteAll()` or, in case you want to use a different encryption key, create a new realm at another location or with a different file name. You can delete the original realm next time your app starts.

**Comment by netgfx** [comment]
The problem is that the Realm at that point hasn't been opened, or my understanding of open is misguided. This delete happens when the App starts. Before anything is accessed from it.

**Comment by stel** [comment]
Well in this case there shouldn't be an issue but make sure you delete all the files related to the realm:
`something.realm`, `something.realm.lock` and `something.realm.management` directory.

**Comment by netgfx** [comment]
Yes I believe this code is handling that:
```
let realmURLs = [
            realmURL,
            realmURL.appendingPathExtension("lock"),
            realmURL.appendingPathExtension("log_a"),
            realmURL.appendingPathExtension("log_b"),
            realmURL.appendingPathExtension("note")
        ]
```

Does realm keep some kind of cache that prevents the Realm file from being released before the App is closed? Because after I restart the App the Realm file is gone.

**Comment by stel** [comment]
If the realm file hasn't been opened (like `let realm = try! Realm(...)`) there is nothing that prevents it from being deleted.

I've tried the code you've posted and it works fine to me.

**Comment by istx25** [comment]
Do you have any additional questions or follow-up, @netgfx?

**Comment by netgfx** [comment]
Well I went with the `deleteAll` approach after I check if the file exists. I will close this since I have found something that works in my case. 

If I discover anything else about the delete, I will post here or create another issue.

However the functionality to be able to "close" a realm file in order to delete it, is not such a bad idea.
