### ISSUE TITLE
Slow performance using objects coming from NOT IN query

### ISSUE THREAD

**Issue by ppaulojr** [realm/realm-cocoa#4564]
## Goals

Read 40k objects and filter out those that match a category.

## Expected Results

Performance faster than Core Data

## Actual Results

Performance much slower than Core Data (reference times in the code below)

```
2017-01-17 15:59:54.884 Orchid Staging[32243:3865356] FOR_TIME: 1.508549
2017-01-17 15:59:54.898 Orchid Staging[32243:3865356] ARRAY_TIME: 0.013498
2017-01-17 15:59:55.011 Orchid Staging[32243:3865356] REALM_QUERY_DELETE_TIME: 0.112714
2017-01-17 16:01:45.481 Orchid Staging[32243:3865356] REALM_DELETE_TIME: 110.469327
2017-01-17 16:01:45.481 Orchid Staging[32243:3865356] TOTAL_REALM_TIME: 112.108052
```

## Steps to Reproduce

Related to #1115 it seems that Realm's team is aware of the problem with `NOT IN` queries.

## Code Sample

```
- (void)createOrUpdateStaffRoundablesWithResponse:(NSArray<CHResponseRoundableMemberStaff *> *)response
{
    TICK(FOR_TIME);
    for (CHResponseRoundableMemberStaff *staffResponse in response) {
        RealmStaff *staff = [RealmStaff createOrUpdateWithResponse:staffResponse];
        staff.careProvider = self;
    }
    TOCK(FOR_TIME);

    TICK(ARRAY_TIME);
    NSArray *ids = [response bk_map:^NSString *(CHResponseRoundableMemberStaff *staffResponse) {
        return staffResponse.uid;
    }];
    TOCK(ARRAY_TIME);

    TICK(REALM_QUERY_DELETE_TIME);
    RLMResults *results = [RealmStaff objectsWithPredicate:[NSPredicate predicateWithFormat:@"NOT uid IN %@", ids]];
    TOCK(REALM_QUERY_DELETE_TIME);

    TICK(REALM_DELETE_TIME);
    [results.realm deleteObjects:results];
    TOCK(REALM_DELETE_TIME);
}
```
## Version of Realm and Tooling
Realm version: 2.2.0

Xcode version: Version 8.2.1 (8C1002)

iOS/OSX version: 10.2 (14C92)

Dependency manager + version: CocoaPods 1.1.1

**Comment by bdash** [comment]
Realm core's query engine doesn't have any direct support for `IN` operations, so we lower predicates of the form `NOT X IN {Y1, Y2, …, Yn}` into the equivalent of `NOT (X == Y1 OR X == Y2 … OR X == Yn)`. That's obviously not optimal.

**Comment by kunalsood** [comment]
Is there any chance we can get some movement on this? I have mostly avoided using this kind of query on the database for years (I have been using Realm since before version 1.0), opting instead to filter in-memory as that is faster, but I'm now at the architectural design phase of an app where not having this query run on the database (in a performant manner) would be the only keeping me from using Realm in it. Thanks for any consideration.

**Comment by tgoyne** [comment]
3.15.0 changed `IN` to use a hash table rather than a naive OR chain, so this may actually be fixed now. If the performance is still unacceptable with the new implementation then there's probably some room for easy improvements.

**Comment by kunalsood** [comment]
> 3.15.0 changed `IN` to use a hash table rather than a naive OR chain, so this may actually be fixed now. If the performance is still unacceptable with the new implementation then there's probably some room for easy improvements.

@tgoyne Thanks for responding. Great news. Sorry for commenting before trying this.

Unfortunately, in the little bit of testing I have done so far, the performance is as bad (if not worse) as it was before. What takes 0.117705 seconds with an in-memory filter seems to take 18.909157 seconds using the IN query on the database.

In case my use case matters, I'm using this query a pre-sorted RLMArray (so there is no database level sorting involved here). The query is run on a string primary key property of 9500-9600 objects. So the predicate looks something like `[NSPredicate predicateWithFormat:@"uniqueIdentifier IN %@", identifiers]`. Once I have the `RLMResults` from this query, I build an in memory array of one of the object's properties from it using `valueForKey:` on it.

**Comment by tgoyne** [comment]
Is the property you're querying on indexed? It appears that the IN optimization isn't used when there's an index under the assumption that the index lookups will be faster which... isn't true. In the scenario tested by a small modification to one of our benchmarks adding an index slows the query from 140ms to 16 seconds.

I guess I need to put together some measurements on when the index is and isn't worth using.

**Comment by kunalsood** [comment]
The property I'm querying is a string primary key property. So, if `Indexes are created automatically for primary key properties.` still holds true, then, yes, it is indeed indexed.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-core/pull/3926 makes it so that NOT IN on an indexed property takes O(N) time rather than O(M*N). There's also some room for constant-factor improvements but that'll at least make it so that it's in a reasonable range of performance.

**Comment by kunalsood** [comment]
Brilliant! Thank you!
