### ISSUE TITLE
Improve documentation regarding sorting by multiple keypaths

### ISSUE THREAD

**Issue by SlashDevSlashGnoll** [realm/realm-cocoa#4565]
## Goals

We are trying to use a result set to drive Rx code and that result set would have a primary and secondary sort (e.g. sort by a name and within that name group sort by a date).  

## Expected Results

We ran into an issue where after deleting an item from the result set that items within the secondary sort (the date) were reordered.  It behaves as though the result set was only honoring the last sort criteria used and doing so in a "destructive sort" way.

## Actual Results

We would see a grouping initially like so (sorted by Name and then by Date)

Item | Name | Date
-----|------- | -------------
Item1 | Abc123 | May 29
Item3 | Abc123 | Jun 2
Item2 | Pdq567 | May 30
Item4 | Pdq567 | June 3
Item5 | Pdq567 | June 4
Item6 | Pdq567 | June 5

Then after deleting Item4 we'd see Item6 change position:

Item | Name | Date
-----|------- | -------------
Item1 | Abc123 | May 29
Item3 | Abc123 | Jun 2
Item6 | Pdq567 | June 5
Item2 | Pdq567 | May 30
Item5 | Pdq567 | June 4

We also tried using the sorting() overload that accepts SortDescriptors but that didn't seem to work either.

## Steps to Reproduce

1. Create a result set using 2 sorts as explained in the previous section.
2. Remove one item in the result set from the realm
3. Observe the result set in step1 after the change and the order of the items in the set has changed

## Code Sample

We are accessing the the realm objects like this and sorting twice to accomplish the 2 column sort.

```swift
let queueItems = realm.objects(UploadQueueItemDbEntity.self).sorted(byProperty: "dateAddedToQueue").sorted(byProperty: "projectName")
return Observable.changesetArrayFrom(queueItems)
```

## Version of Realm and Tooling

Realm version: ?
2.1.2

Xcode version: ?
8.2

iOS/OSX version: ?
OSX 10.11.6/iOS 10.2

Dependency manager + version: ?
Cocoapods/1.1.1

**Comment by istx25** [comment]
Hi @SlashDevSlashGnoll. Thanks for reaching out for support. I will have someone review what you've submitted and respond with a solution or follow-up questions as soon as possible. We appreciate your patience.

**Comment by bdash** [comment]
`Results.sorted(byProperty:)` replaces any existing sort criteria. If you'd like to sort by multiple properties, you can use [`Results.sorted(by:)`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sorteduRd__s8SequenceWd__8Iterator7Element_zVS_14SortDescriptorrFT2byqd___GS0_x_) and pass multiple [`SortDescriptor`](https://realm.io/docs/swift/latest/api/Structs/SortDescriptor.html)s.

**Comment by SlashDevSlashGnoll** [comment]
Hi bdash, we had tried that as well (mentioned that briefly above) but it didn't seem to work.

**Comment by bdash** [comment]
Hmm. In that case I think we'll need to be able to reproduce this to understand what's going on. Can you provide some code that demonstrates the problem?

**Comment by istx25** [comment]
Just bringing attention back to this. @SlashDevSlashGnoll: Would you be able to provide some code that demonstrates the problem? If you need to (for confidentiality), you can email us the project to help@realm.io. Thanks!

**Comment by SlashDevSlashGnoll** [comment]
Apologies, things have been busy.  I will try to put together something that exhibits the behavior

**Comment by SlashDevSlashGnoll** [comment]
So after some digging I think we've determined that it's working fine and we had a misunderstanding.  I think this does point to an issue with the [documentation](https://realm.io/docs/swift/latest/#sorting) so perhaps that's all it needs.  A few points that could be addressed in the docs:

1. The docs say that sorting can be done "based on a single or multiple properties or key paths" and the example uses the [byKeyPath](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sortedFT9byKeyPathSS9ascendingSb_GS0_x_) method.  This does not support multiple properties and it lead us to believe you can chain sorts in a fluent way like the other operations (the very next section talks about chaining).  Perhaps the docs should be clearer that sorting on multiple fields requires the SortDescriptors method
2. The [Results.sorted(by:)](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results6sorteduRd__s8SequenceWd__8Iterator7Element_zVS_14SortDescriptorrFT2byqd___GS0_x_) method should document the order in which the sort descriptors are applied, e.g. which one is the "outermost" sort

Thanks for the attention and sorry for the false alarm!

**Comment by jpsim** [comment]
Thanks for the suggestions to improve our docs @SlashDevSlashGnoll! Maybe @chipotle would be interested in making these clarifications?

By the way, I hope you don't mind I modified this ticket to track making these docs improvements rather than creating a new issue in order to preserve the conversation.

**Comment by chipotle** [comment]
Okay, I'll take a stab at it. Someone who actually knows Swift/Objective-C will need to review my pull request to make sure what I'm saying isn't a complete lie. :)

**Comment by chipotle** [comment]
Fixed in the commit referenced above (and now live on the web site)
