### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.0

### ISSUE THREAD

**Issue by kmkrn** [realm/realm-cocoa#4566]
I've been trying to update to latest Realm version and Swift 3.0 using Carthage, but get a "module compiled with Swift 3.0.2 cannot be imported in Swift 3.0" error and 1500+ missing file warnings in Xcode. Using `Carthage bootstrap --platform iOS --no-use-binaries --toolchain com.apple.dt.toolchain.Swift_3_0`
didn't resolve the issue (using it actually results in Build folder being empty). I also deleted Derived Data, no luck. 

- Swift version: 3.0
- Xcode version: 8.0
- Carthage version: 0.18.1

Will appreciate any help.

**Comment by jpsim** [comment]
That appears to be the correct Carthage command to build with the Swift 3.0.0 toolchain. Are you sure your Xcode project's framework search paths and linked framework point the the build from this run of Carthage? It looks like it might be pointing to a build artifact that lives elsewhere.

**Comment by jpsim** [comment]
What are the inherited settings? Also, if you've "dragged and dropped" the framework into your Xcode project, that might point to a different path.

Trying to debug your project's configuration one screenshot at a time might be time consuming? Could you send us the project at help@realm.io?

**Comment by kmkrn** [comment]
"Inherited settings" tag makes specific target inherit from project settings, and I believe this is hardly the issue. I've sent a link to the test project.

**Comment by istx25** [comment]
@kmkrn: We'll review the project you shared and follow-up soon. :)

**Comment by jpsim** [comment]
@kmkrn the framework was indeed compiled with Swift 3.0.2: https://github.com/kmkrn/Homework/blob/master/Carthage/Build/iOS/RealmSwift.framework/Headers/RealmSwift-Swift.h#L1

> Generated by Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)

You're compiling Realm Swift with Xcode 8.2, but attempting to build your project with Xcode 8.0. You need to use the same version of Xcode to compile all Swift binaries used by your project.

**Comment by istx25** [comment]
@jpsim's seems sufficient. Closing the issue due to inactivity but feel free to re-open if someone things that it still needs to be.

**Comment by kiraninfogird** [comment]
I also have the same problem as below;

Module compiled with Swift 3.1 cannot be imported in Swift 3.2: /Users/iipl5/Documents/Projects/ClearCarRental/src/CcrCustIosApp/ccr/Pods/Instamojo/Instamojo.framework/Modules/Instamojo.swiftmodule/x86_64.swiftmodule


Please give me the solution over it???

**Comment by bdash** [comment]
@kiraninfogird, rather than commenting on an issue that's been closed for 6 months, please file a new issue and provide the information that is requested in the new issue template. We'll then be able to help you troubleshoot your problem.
