### ISSUE TITLE
Realm Objects never deallocated, thus app inevitably crashes because of memory. (Memory Management)

### ISSUE THREAD

**Issue by JPROFFICIAL** [realm/realm-cocoa#4571]
## Goals

What do you want to achieve?

UIViewController `deinit` is called -- 0 memory leaks

## Expected Results

Realm objects deallocated, thus reference count = 0 and allows uiviewcontroller to deinit

## Actual Results

Realm object never deallocated, standard Out Of Memory crash as no uiviewcontrollers are deinitialized.

## Steps to Reproduce

Create a few object models, with a major model containing instances of those. Parse data into those optional object models inside the initializer for the major model. This should give you these results.

## Code Sample

Here is a standard object I am using (There is more variables but this is an example)

```
class FullData: Object {
    dynamic var venueType: VenueType?
    dynamic var travelerType: TravelerType?
    
    dynamic var owner: ProfileData?
    
    let keywords = List<NewKeywords>()
    let cuisines = List<NewCuisines>()
    let images = List<Images>()
}
```

In the `convenience` initialization of this model, I will use a function to create a new `VenueType` Instance , and assign that new instance to the optional variable in the model.
```
    fileprivate func parseVenueType(_ dictionary: NSDictionary) {
        let venues = VenueType()
        dictionary.forEach { (key, val) in
            let keyString = key as! String
            let value = val as! Bool
            switch keyString {
            case "Bar":
                if value == true {
                    venues.bar = true
                }
                break
            case "Restaurant":
                if value == true {
                    venues.restaurant = true
                }
                break
            case "Cafe":
                if value == true {
                    venues.cafe = true
                }
                break
            default:
                break
            }
        }
        venueType = venues
    }
```

Using the `Leaks` tool in `Instruments`, I see that there are tons of leaks, all regarding situations almost identical to this. A new instance of an object is created to assign to an object in our model.

Here are some Images detailing these leaks. 
![screen shot 2017-01-20 at 12 25 04 pm](https://cloud.githubusercontent.com/assets/14960440/22164407/f97f68fa-df0b-11e6-83f1-ba2d44ec891c.png)
![screen shot 2017-01-20 at 11 28 56 am](https://cloud.githubusercontent.com/assets/14960440/22164405/f97e492a-df0b-11e6-842b-970388ba0e35.png)
![screen shot 2017-01-20 at 11 27 21 am](https://cloud.githubusercontent.com/assets/14960440/22164406/f97f8af6-df0b-11e6-9ec5-30692a725037.png)
![screen shot 2017-01-20 at 12 33 22 pm](https://cloud.githubusercontent.com/assets/14960440/22164784/7dd3a804-df0d-11e6-8b1c-7a6e9f002e62.png)

I create new instances of a basic `Realm()` all across my app, but 99.99% of the time I don't persist the models I am creating. I use these as basic models to populate cells, etc. In theory, they should be deallocated once they are done.

Im really unsure what I am doing wrong, as all of my leaks are because of Realm Objects. Its almost as if none of the created models I am using for my data are being deallocated once they leave the view controller.

Am I supposed to do this manually? I have read a few comments on `autoreleasepools` and also `realm.invalidate` but am unsure if this would fit my case. 

Some help on this ASAP would be extremely helpful. We are stalling our current release until we can address these memory issues as they inevitably will crash our app. (No VC's ever deinit because refCounts never reach 0)

Thanks so much!! I love realm and enjoy using it. Thanks for a great platform.

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

Xcode 8.2.1
Build version 8C1002

/usr/local/bin/pod
1.1.1
Realm (2.2.0)
RealmSwift (2.2.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)


(not in use here)

/usr/bin/git
git version 2.10.1 (Apple Git-78)
```

Realm version: 1.1.1
Realm (2.2.0)
RealmSwift (2.2.0)

Xcode version: Xcode 8.2.1
Build version 8C1002

iOS/OSX version: ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

Dependency manager + version: git version 2.10.1 (Apple Git-78)

**Comment by bdash** [comment]
Can you please share the declaration of your `VenueType` and `TravelerType` classes?

**Comment by JPROFFICIAL** [comment]
```
class VenueType: Object {
    dynamic var cafe = false
    dynamic var bar = false
    dynamic var restaurant = false
}
```
```
class TravelerType: Object {
    dynamic var single = false
    dynamic var couple = false
    dynamic var group = false
    dynamic var family = false
}
```

**Comment by bdash** [comment]
In Instruments' Leaks instrument you should be able to navigate to a given leaked object and see all of the retain / release activity on that object. Presumably there are mismatched retains and releases on some of these objects. Determining which code is responsible for these mismatched retains and releases should reveal where the leak is originating.

**Comment by JPROFFICIAL** [comment]
@bdash Thanks for the information. Doing further research using leaks, Going down the retain / release list I get to this last object: 
![screen shot 2017-01-20 at 12 59 19 pm](https://cloud.githubusercontent.com/assets/14960440/22165390/5ee1f254-df10-11e6-83fa-7aaa9dae39aa.png)
![screen shot 2017-01-20 at 12 58 56 pm](https://cloud.githubusercontent.com/assets/14960440/22165391/5ee30c7a-df10-11e6-8ec6-ca420b285707.png)

It seems that the object `venues` in the function screenshotted above is never released. Should I/How do I/ do that manually? As you can see, Im using that object to assign it to the model being initialized. If I release that, will it null out the object it was assigned to?

Thanks in advance for your help and the quick support. Anything I can do give you more insight I will be more than happy.

**Comment by bdash** [comment]
You can look at the backtrace of each event (in the sidebar at the right of the window) to see what code was responsible for each retain / release event. You can then use that information to determine which retain event is missing its corresponding release, which tells you who is responsible for the leak.

**Comment by JPROFFICIAL** [comment]
It's giving me the initialization of the object as the last user written trace in that stack. It seems that the `Malloc` Is the one giving it the extra retain count, as every other retain/release is accounted for. 

I tried making `venues` an optional and nulling it out after it is assigned, but the leak remains. Do I have to mark something in that class with weak? Is Malloc supposed to give the retain count + 1: so that would mean it's the last retain count without an immediate release that is my issue? - If that is the case, It still leads me back to the `93 byte` code screenshot attached in my last response.

![screen shot 2017-01-20 at 1 34 04 pm](https://cloud.githubusercontent.com/assets/14960440/22166386/a368e838-df15-11e6-805d-68324b5b7cf5.png)
![screen shot 2017-01-20 at 1 33 59 pm](https://cloud.githubusercontent.com/assets/14960440/22166385/a3685f58-df15-11e6-86c2-5c9cd476f65f.png)
![screen shot 2017-01-20 at 1 33 39 pm](https://cloud.githubusercontent.com/assets/14960440/22166387/a368e73e-df15-11e6-8573-43d5d0dd3e16.png)

**Comment by springhand** [comment]
hi JPROFFICIAL. Did you solve the problem of the memory leaks, I have found the same problem.

**Comment by JPROFFICIAL** [comment]
@springhand nope. I fixed a good few of my leaks by adding `[weak self]` inside all of my closures containing `self`, and checking for it. The memory leaks regarding these realm models is my only leak sources left.

**Comment by springhand** [comment]
@JPROFFICIAL . I am so. Can't completely solve the problem of leakage.

**Comment by jpsim** [comment]
@springhand @JPROFFICIAL can either of you share a project that reproduces this leak? You can send code to us privately at help@realm.io (making sure to reference this issue by URL).

If you're not in a position to share that, we could spend some time on our side preparing a basic project that attempts to reproduce this and share back with you if we can't trigger the leak so you can modify it to highlight the issue.

**Comment by istx25** [comment]
Bringing attention back to @jpsim's request:

>@springhand @JPROFFICIAL can either of you share a project that reproduces this leak? You can send code to us privately at help@realm.io (making sure to reference this issue by URL).

>If you're not in a position to share that, we could spend some time on our side preparing a basic project that attempts to reproduce this and share back with you if we can't trigger the leak so you can modify it to highlight the issue.

**Comment by bdash** [comment]
It's been three weeks since we've asked for further information and we've not heard back. There's nothing we can do to help you further until more information is provided. Please feel free to file a new issue, reopen this issue, or contact us via email as mentioned above, if you're still encountering this problem.
