### ISSUE TITLE
Remove support for Swift 2.x

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#4575]
We've been encouraging users to move to Xcode 8 [for over 4 months](https://realm.io/news/realm-objc-swift-1.1.0/). Less than 6% of our Swift users on Realm 2.1 or later are still on Swift 2.x, with that number continuing to decline. Supporting Swift 2.x incurs a significant engineering overhead, since we have to duplicate all our Swift code for both language versions, as well as run two full sets of our CI jobs on Swift 2.2 and Swift 2.3, which takes time and requires maintaining old versions of Xcode on our infrastructure.

For all these reasons, I propose we remove Swift 2.x support in the next release.

**Comment by austinzheng** [comment]
Closing this issue, unless JP wants to use it to track related work.
