### ISSUE TITLE
Implicit conversion warning in protocol.hpp

### ISSUE THREAD

**Issue by skydivedan** [realm/realm-cocoa#4578]
version is : RealmSwift 2.3.0

When I compile, I'm getting a warning in RealmSyncSession, `addProgressNotificationForDirection`. Line 164. The values being passed into the block call are uint64_t values, but the block is expecting an NSUInteger.

Also seeing a similar problem with protocol.hpp, line 338. 

`Implicit conversion loses integer precision` is the warning. 

I'm using Realm in a private cocoapod, and it won't lint unless I tell it to ignore warnings.

**Comment by jpsim** [comment]
This was fixed in #4572 and realm/realm-sync#1118. That first PR is already available to you if you build from `master`, but the second one requires a release of our sync binaries for you to be able to pull in. I'll keep this issue open until a new release is cut and we can update to it.

**Comment by istx25** [comment]
Has this been included in a release yet? I'm guessing this was included in 2.4.0?

**Comment by istx25** [comment]
@jpsim: Has this been included in a release yet? I'm guessing this was included in 2.4.0?

**Comment by jpsim** [comment]
Yes this was resolved in 2.4.0
