### ISSUE TITLE
Typo/repetition in the inline docs `addProgressNotificationForDirection:mode:block:`

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-cocoa#4579]
The [inline docs state](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMSyncSession.h#L120) (emphasis mine):
> The progress notification block will always be called once immediately upon registration **in order to** provide up-to-date registration **in order to** provide the latest available status information.

It feels like we should only keep one of the statements.

**Comment by nirinchev** [comment]
Additionally, the cocoa docs (and unfortunately, OS variable names) use `transferrable` which seems to be misspelled.

**Comment by austinzheng** [comment]
According to http://www.dictionary.com/browse/transferrable and some other dictionary sites, `transferrable` and `transferable` are both acceptable spellings (hooray English orthography), so I'll let @jpsim decide whether he wants to act on the spelling.

I'll submit a PR to fix the typo, thanks for pointing it out.

**Comment by jpsim** [comment]
Let's keep it as `transferrable` just of the sake of not breaking APIs that are already spelled correctly.
