### ISSUE TITLE
Error with sum aggregation in Lists

### ISSUE THREAD

**Issue by kimdv** [realm/realm-cocoa#4602]
## Goals

Sum all the properties in the list. 

## Expected Results

Sum all the properties in the List

## Actual Results

The xcode said there is an error: Generic parameter ‘U’ could not be inferred. 

## Code Sample

The periods are made like this
`let periods: List<Period> = List<Period>()`

Sum code
```
 do {
    let realm: Realm = try Realm()
    let predicate = NSPredicate(format: "date == %@", Date().startOfDay as CVarArg)

     let test: Double? = realm.objects(Day.self).filter(predicate).first?.periods.sum(ofProperty: "steps")

     print(test)
    } catch {     
}
```

Average code
```
 do {
            let realm: Realm = try Realm()
            let predicate = NSPredicate(format: "date == %@", Date().startOfDay as CVarArg)

            let test: Double? = realm.objects(Day.self).filter(predicate).first?.periods.average(ofProperty: "steps")

            print(test)
            return realm.objects(Day.self).filter(predicate).first
        } catch {            
}
```

## Version of Realm and Tooling

Realm version: 2.4.1

Xcode version: 8.2.1

iOS/OSX version: OSX: 10.12.2, IOS 10.2.1

Dependency manager + version: Cocoapods 1.1.1

**Comment by kimdv** [comment]
I have just tested the other aggregations and min, max and average works on List<>. 

Sum also works on Result lists

**Comment by istx25** [comment]
Hi @kimdv! Thanks for reaching out. I'll review what you've shared and have someone respond with a solution or follow-up questions. Cheers! 🚀

**Comment by tgoyne** [comment]
`sum()` does not return an optional, while the other aggregation functions do (the sum of an empty set is zero, while the maximum of an empty set does not exist).

**Comment by kimdv** [comment]
I figured it out. 

Day is optional, and then will sum not work because the property that holds the Int have to be optional. 

An idea is to make some ducomentaion about this?

I will close
