### ISSUE TITLE
Xcode 8.3 compile with 7 errors

### ISSUE THREAD

**Issue by meteorSD** [realm/realm-cocoa#4603]
Hi, i am currently having issues using Realm (version 2.4.2) with Xcode 8.3 (beta version). The project compile with 7 errors.

Here's a screenshot of the errors 
<img width="381" alt="capture d ecran 2017-01-30 a 15 23 57" src="https://cloud.githubusercontent.com/assets/14254230/22426881/587295ec-e701-11e6-9f0c-1dc16a73dfec.png">

**Comment by istx25** [comment]
Hi @meteorSD. I noticed you closed this issue pretty soon after opening it. I assume this means you fixed it yourself but let us know if you need help with this or anything else. :-)

**Comment by jpsim** [comment]
This was likely closed because it's a duplicate of #4586, not that the user resolved this themselves.

**Comment by istx25** [comment]
Good to know. Thanks for clarifying, @jpsim.
