### ISSUE TITLE
Issues building framework with Realm dependancy

### ISSUE THREAD

**Issue by iandundas** [realm/realm-cocoa#4608]
## Goals

I have a project, "Tacks". Using Carthage, I'm pulling in a dependancy called [HotTakeRealm](https://github.com/iandundas/HotTakeRealm/). HotTakeRealm has Realm as a dependancy, given in it's own Cartfile. Tacks also uses Realm, and has Realm (same version) in it's Cartfile too.

The workspace for HotTakeRealm framework project has Realm & RealmSwift linked to the HotTakeRealm target as sibling projects in the workspace like so: 

<img width="1123" alt="screen shot 2017-01-30 at 23 15 22" src="https://cloud.githubusercontent.com/assets/1131967/22445945/ffe08b0a-e741-11e6-9845-9059a67164bc.png">

I want to be able to build HotTakeRealm and add it as a dependancy to my main project ("Tacks") via Carthage. Currently, whilst Carthage can build `Realm` and `RealmSwift` on their own, when building the HotTakeRealm dependancy something goes wrong.

In addition, if I use `--no-use-binaries`, Carthage does indeed download the precompiled version, but ignores this for the `HotTakeRealm` dependancy step, and for that dependancy seems to build it from scratch.

## Expected Results

I should be able to build 'HotTakeRealm' using Carthage

## Actual Results

	*** Building scheme "HotTakeRealm" in HotTakeRealm.xcworkspace
	** BUILD FAILED **

	The following build commands failed:
		PhaseScriptExecution Download\ Core\ and\ Sync /Users/ian/Desktop/trial/Carthage/Checkouts/HotTakeRealm/Build/Intermediates/Realm.build/Release-iphoneos-static/Realm\ iOS\ static.build/Script-5DD7557D1BE056DE002800DA.sh
	(1 failure)
	A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/ian/Desktop/trial/Carthage/Checkouts/HotTakeRealm/HotTakeRealm.xcworkspace -scheme HotTakeRealm -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
	** BUILD FAILED **

	The following build commands failed:
		PhaseScriptExecution Download\ Core\ and\ Sync /Users/ian/Desktop/trial/Carthage/Checkouts/HotTakeRealm/Build/Intermediates/Realm.build/Release-iphoneos-static/Realm\ iOS\ static.build/Script-5DD7557D1BE056DE002800DA.sh
	(1 failure)

If I run the shell task mentioned in the error: `/usr/bin/xcrun xcodebuild -workspace /Users/ian/Desktop/trial/Carthage/Checkouts/HotTakeRealm/HotTakeRealm.xcworkspace -scheme HotTakeRealm -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build`, I eventually get: 

> ** BUILD SUCCEEDED **

So that's strange.

## Steps to Reproduce

In an empty folder, run `carthage bootstrap --platform iOS --no-use-binaries` with the following Cart file: 

```
github "iandundas/HotTakeRealm" ~> 1.3
```

## Code Sample
n/a

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

/Applications/Xcode 8.2.1.app/Contents/Developer
Xcode 8.2.1
Build version 8C1002

/Users/ian/.rbenv/shims/pod
1.1.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.18.1
github "realm/realm-cocoa" "v2.4.1"

/usr/local/bin/git
git version 2.10.0
```

Thanks!

**Comment by istx25** [comment]
Thanks for reaching out, @iandundas. Someone will review this and be in touch soon. :-)

**Comment by iandundas** [comment]
Thanks :) as a stop-gap I've added a precompiled release for HotTakeRealm to github and it just downloads that now. But for the future it would be good to solve this. Cheers

**Comment by stel** [comment]
@jpsim could you please help with this? Does Realm/Cartage support this scenario?

**Comment by bitomule** [comment]
Any update on this? How did you fix it @iandundas ? I really need help with this.

**Comment by iandundas** [comment]
Strange - the prebuilt binary solution did work for me. What's the exact error?

**Comment by bitomule** [comment]
@iandundas así fynally managed to get the prebuilt solution to work. It was an issue on my side. Still waiting for the "real" solution.

**Comment by jpsim** [comment]
I think "exit code 65" is an error reported by `xcodebuild` when the Xcode EULA hasn't yet been accepted. Anyway, it seems like everyone in this thread was able to eventually resolve the issues they were running into.

Is there anything more we can help you with in this thread @iandundas @bitomule ?

**Comment by bitomule** [comment]
@jpsim serving my project as static library isn't a good fix. It just broke on last realm-cocoa release. It's not related to Xcode EULA, something changed on last realm release that broke it.

I've test running that need to fetch realm-cocoa using carthage and all crashes because of this issue.

**Comment by jpsim** [comment]
Sorry @bitomule I wasn't aware that was the final state of where you were at. It would help if you reiterated exact steps and versions to reproduce your issue(s) and explained why you think it's a problem with Realm and not Carthage.

**Comment by bitomule** [comment]
@jpsim The issue is related to Realm because version change on realm produced the issue. I was already using realm with carthage as a dependency before. I can't reproduce the issue as I've published the precompiled version but I had the same issue @iandundas described. I think any package with realm as a carthage dependency will have the same issue.

**Comment by iandundas** [comment]
@jpsim I think the Steps To Reproduce in my initial post above should reproduce it on any machine 🤞🏻

**Comment by iandundas** [comment]
I will verify it again and get back to you (I think the EULA thing is a side issue but I'll double check)

**Comment by bdash** [comment]
I was able to reproduce this by following the steps to reproduce listed in the original report. I'm not yet sure why it fails, but I did notice that Realm appears to be built in two different ways. It's built by Carthage due to being listed as a dependency in HotTakeRealm's Cartfile, and it's built as part of HotTakeRealm's workspace due it including Realm's Xcode project from a checked-in copy of Realm's source in HotTakeRealm's git repository. The build is failing when included as part of HotTakeRealm's workspace.

**Comment by bdash** [comment]
@iandundas, is it intentional that you're building Realm both via Carthage and as a subproject? Building Realm in two different ways as part of the same project seems like it's asking for weird behaviors.

**Comment by iandundas** [comment]
Hey @bdash, thanks for debugging it - I'll try just adding the built Realm.framework to the HotTakeRealm project instead

**Comment by austinzheng** [comment]
Thanks. If you have any further questions feel free to open new issues.
