### ISSUE TITLE
"collection_notifications.hpp" not found

### ISSUE THREAD

**Issue by colasbd** [realm/realm-cocoa#4614]
## Goals
Use Realm

## Expected Results
My Project builds

## Actual Results
The building fails
> "collection_notifications.hpp" not found

## Code Sample
I use Realm in two projects. In project 1, the `pod update` failed with this message
![capture d ecran 2017-01-31 a 16 04 50](https://cloud.githubusercontent.com/assets/4303814/22470275/07fe5186-e7cf-11e6-99bf-35223078ed34.png)
(my internet connexion was unstable)

In project 2, I did `pod update` (now my connexion is sound and stable). But the files are not installed:
![capture d ecran 2017-01-31 a 16 06 11](https://cloud.githubusercontent.com/assets/4303814/22470336/36fc5d70-e7cf-11e6-949a-f42b79ae686c.png)

## Version of Realm and Tooling
Realm version: 2.4.2
Dependency manager + version: CocoaPods 1.1.1

**Comment by istx25** [comment]
Hi @colasbd! Thanks for reaching out. I'll have someone review what you've shared and respond with a solution or follow-up questions as soon as we can. Cheers! 🚀

**Comment by colasbd** [comment]
Hi @istx25 
Thanks for your 🚀 reply.
I've found a solution:
```
#!/usr/bin/env bash

rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by colasbd** [comment]
I'll let you close the issue.

**Comment by istx25** [comment]
Awesome. Happy to hear you resolved it. Seems this was more of an issue with CocoaPods than Realm so I'll close it but @jpsim can follow-up if he has anything more to comment. Cheers! :)

**Comment by jpsim** [comment]
CocoaPods could do with improved logic about not caching incomplete downloads, but this is out of our hands.

**Comment by istx25** [comment]
@jpsim: I'll look into filing an issue with CocoaPods about this or if there's an existing issue being tracked that I can add to.
