### ISSUE TITLE
The client only sends a REFRESH message when sending data

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-cocoa#4615]
In the 1.0.1 ROS, the server stops sending messages to clients with expired tokens.(default time for that is 10 min).

However, the cocoa binding only sends a refresh token when it wants to send some data. 
That means it will stop receiving data after the access token expires until it will try to send new data.

Currently the server does not send any message to indicate that the client will not be receiving any data.

We will have to revert the fix in the ROS 1.0.1 until the clients can handle it.

cc @austinzheng @jpsim

**Comment by austinzheng** [comment]
I thought this was fixed? Upon receiving the refresh token, the binding and object store immediately forwards it to `sync`. However, I have noticed that the server does not seem to receive the token until the client attempts to transfer data, so it may be an issue with how `sync` decides to schedule sending up the token.

**Comment by radu-tutueanu** [comment]
You are right, this looks a bug in realm-sync. I'll open an issue.

**Comment by austinzheng** [comment]
Great, thanks ❤️! Sorry for not reporting the sync issue earlier; I wasn't sure if it was intended behavior or not.
