### ISSUE TITLE
Should persisted realm objects keep a hard reference to realm?

### ISSUE THREAD

**Issue by sipersso** [realm/realm-cocoa#4616]
## Goals
In CoreData it is a common practice to pass persisted objects to the next viewcontroller. If you do this in realm it seems as if the persisted object seems to have a hard reference to realm, which results in problems if you want to replace the realm file at runtime. You have to kill the app for the replaced database file to be used.  Should persisted realm objects keep a hard reference to realm? If so, shouln't the documentation be updated to reflect the fact that you should never, for example, pass realm objects between viewcontrollers or fetch them in viewdidload if you ever want to replace the database file? 
 
## Expected Results

1: The initial viewcontroller has no references to realm
2: The initial viewcontroller pushes second viewcontroller that fetches a persisted object when the view appears. 
3: The second viewcontroller is popped from the stack
4: The realm file is deleted and replaced by another realm file (in the way described in the docs)
5: The inital viewcontroller pushes the second viewcontroller again.
6: The second viewcontroller should have refreshed data

## Actual Results
6: The second viewcontroller shows the data from the initial realm file and you have to kill the app for the realm to be refreshed 

Realm version: 2.4.2

Xcode version: 8.2.1

**Comment by istx25** [comment]
Hiya @sipersso. Thanks for reaching out. We're working through a bit of backlog but someone will be in touch with an explanation/solution soon. Cheers! 😸

**Comment by tgoyne** [comment]
[There is already a section in the documentation covering this](https://realm.io/docs/swift/latest/#deleting-realm-files). Is there anything further that you feel needs to be covered there?

**Comment by sipersso** [comment]
@tgoyne if Realm works as expected in this case, the documentation is incomplete. The documentation says "Realm instances hold a database connection for the exact duration of their lifetime.". But it doesn't say anything about that you can't keep any references of type RealmSwift.Object either. 

For deleting and refreshing the realm file I need to clear, not only any references to Realm, but also to any object that is of type Realm.Object. If I don't do this, I have to kill the application for the content from the new Realm file to appear.

This means I can't pass persisted objects between viewcontrollers as you have no way of knowing when the viewcontrollers are dealloced (and the realm instance is freed). It forces me to only pass a primary key, load the persisted object when the view appears and then manually unload it when the view dissapears (which is very error prone). There is no mention of this in the documentation.

**Comment by istx25** [comment]
Bringing attention back to this issue. cc/ @tgoyne
