### ISSUE TITLE
Swift var with get and set are not automatically ignored 

### ISSUE THREAD

**Issue by dmorrow** [realm/realm-cocoa#4617]
## Goals

Add ignored property without using `ignoredProperties()`

## Expected Results

Properties not to be persisted.  When adding 

    var name {
      return "John"
    }

The property `name` is not persisted and does not need to be added to `ignoredProperties()`.  However, using a swift `get` and `set` block in a `var` it does get persisted.

## Actual Results

Properties were persisted

## Code Sample
    var pushNotifications:Bool {
        get {
            return pushBroadcastPosts && pushEventReminders && pushEventUpdates && pushGroupInvites && pushGroupJoinRequests && pushMentions && pushNewMessage
        }
        set {
            pushBroadcastPosts = newValue
            pushEventReminders = newValue
            pushEventUpdates = newValue
            pushGroupInvites = newValue
            pushGroupJoinRequests = newValue
            pushMentions = newValue
            pushNewMessage = newValue
        }
    }

## Version of Realm and Tooling

Realm version: 2.1.2

**Comment by tgoyne** [comment]
Wanting to have overridden getters and setters for a property on unmanaged objects while still wanting the property to be persisted in Realm would be somewhat odd, but there's nothing inherently broken about it, so even if we could reliably detect this case and implicitly ignore the property it's not obvious that it would be the right thing to do.

**Comment by dmorrow** [comment]
@tgoyne I apologize if my issue report wasn't clear - I don't want the property to be persisted.  Its purely a synthesized property.
I am using the setter to set a number of synthesized properties in one shot.
I'd like it to perform exactly like the other example I gave:

    var name {
      return "John"
    }

**Comment by tgoyne** [comment]
Yes, what I mean is that someone else may want a similar property to be persisted, so we can't just automatically make it not persisted.

**Comment by dmorrow** [comment]
I see.  Thanks for the explanation.
I can imagine validating the newValue in the setter block, so I understand the use case.
