### ISSUE TITLE
Help correct code for uncaught exception: Realm accessed from incorrect thread

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#4634]
**Original Title**: _terminating with uncaught exception of type realm::IncorrectThreadException: Realm accessed from incorrect thread._ 

I am using Realm for my persistence. Now I really confused should i use realm or not. I am using AlamoFire, ObjectMapper and Realm. The following is my code:

```swift
class UserInfo:Object,Mapper
{
    dynamic var name:String?
    dynamic var accountTye:String?
    dynamic var loginResult: String?
}
```

Once I get success response from server for my login.

```swift
// UserSessionManager

UserSessionManager.shared().saveSession()

// This has userInfo object as instance

func saveSession()
{
    RealmHelper.shared().save(userInfo!)
}

// RealmHelper

func save<T:Object>(_ realmObject:T) {
    let backgroundQueue = DispatchQueue(label: ".realm", qos: .background)
    backgroundQueue.async {
        let realm = try! Realm()
        debugPrint("Realm Creation \(Thread.current)") // I am getting same thread 
        if realm.isInWriteTransaction{
            return
        }
        try! realm.write {
            debugPrint("Realm add \(Thread.current)") I am getting same thread 
            realm.add(realmObject)
        }
    }
}
```

When I am trying to accessing `UserSessionManager.shared().userInfo` object I am getting this crash. I did not understand why it is happening.

**Comment by istx25** [comment]
Please follow-up on https://github.com/realm/realm-cocoa/issues/4635. I believe the problems are linked so we can continue the conversation over there.
