### ISSUE TITLE
Can't we access an object which is added to realm

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#4635]
I have an object "User" model declared as realm object.

```swift
class User:Object
{
}
```

Now i am adding it to realm like below.

```swift
let backgroundQueue = DispatchQueue(label: ".realm", qos: .background)
backgroundQueue.async {
    let realm = try! Realm()
    debugPrint("Realm Creation \(Thread.current)")
    if realm.isInWriteTransaction{
        return
    }
    
    realm.beginWrite()
    realm.add(user)
    do{
        debugPrint("Realm commitWrite \(Thread.current)")
        try realm.commitWrite()
    }catch let error{
        debugPrint("realm commit error \(error)")
    }
}
```

The same object i have in singleton class `UserSession`. If i access the object from singleton after adding it to realm, I am getting incorrect thread exception but I have already add the object.

```
let user = UserSession.shared().user
print(user.name)
```

I am getting the on above line. I did not understand.

**Comment by istx25** [comment]
Hi @santhoshs5. Thanks for reaching out about this. Although some additional sample code would be helpful (specifically the code right before the `backgroundQueue` ivar) but from what you have provided, I believe this issue has to do with the passing an instance (in this case: `user`) across threads without any accommodation for the fact that it's crossing into a different thread.

I recommend reading up on the documentation for [Passing Instances Across Threads](https://realm.io/docs/swift/latest/#passing-instances-across-threads). Hopefully that will put you in the right direction and feel free to follow-up if you need additional help.

**Comment by santhoshs5** [comment]
@istx25  Thanks for follow up.
Let me clear my understandings.
I have a Realm Object called (User) which I added it to realm.

the same object i have in some singleton as instance variable so I cant use the object which is there in singleton as I have already added that object to Realm.

am I correct ?

Please correct if anything is wrong.

**Comment by istx25** [comment]
Hi @santhoshs5. Thanks for following-up. I have a few questions:

"I have a Realm Object called (User) which I added it to realm."

- Is there only one User object _added to Realm_ or are there many?
- What benefits do you want the singleton to provide? Is it to determine the "current" user?
- How do you fetch the object and store it in the singleton when it's created?

Let me know and I'll try to better answer your question. :-)

**Comment by santhoshs5** [comment]
Sorry for late reply.



User object 

1. I have only one User Object.
2.we need User object in singleton to use through out the application which has all crucial information such as account type and many details which are required to pass in other APIs even.
3.User object has created after a successful LoginResponse(Network call) using ObjectMapper which I am saving this object in singleton and then in Realm.

**Comment by istx25** [comment]
Thank you for responding, @santhoshs5. I personally see nothing especially wrong with this but I recommend using the singleton as facade between your code and Realm instead of just duplicating the data in Realm and your singleton.

```swift
import RealmSwift
import Foundation

struct UserProvider {
    static let current: User? = {
        let realm = try! Realm()
        return realm.objects(User.self).first
    }()
}
```

This will ensure that if a User object exists in the "singleton", it exists in Realm and if it exists in Realm, it exists in the "singleton." I put singleton in quotes because this example isn't exactly a singleton anymore but you could make my code example into a singleton and still fetch the user from Realm directly. Let me know if you have any other questions.

**Comment by santhoshs5** [comment]
Thanks for responding.I am actually doing the same now.

**Comment by istx25** [comment]
Awesome! Do you need anymore assistance?

**Comment by santhoshs5** [comment]
thanks for quick response but I still did not understood why cant i use same object.
Can i use same object if save user using threadSafeRef(User.self).

**Comment by austinzheng** [comment]
Please make sure you don't access your singleton `User` object from multiple threads. If you are accessing your `User` from both a network callback and from the UI, you are almost certainly accessing it from multiple threads.

If you really need a singleton `User` object, please define it with a hardcoded primary key (see [our documentation on primary keys](https://realm.io/docs/objc/latest/#primary-keys)).

Then, whenever you need to access it, fetch it from the Realm using that primary key on the same thread (using [`Realm.object(ofType:forPrimaryKey:)`](https://realm.io/docs/swift/2.4.2/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6objectu0_RxCS_6ObjectrFT6ofTypeMx13forPrimaryKeyq__GSqx_), and then immediately use it and then throw it away. Don't keep the `User` object around unless you can ensure that _it will only ever be accessed from the thread where it was created_.

**Comment by istx25** [comment]
@santhoshs5: I've responded to your SO question as well. http://stackoverflow.com/a/42212670/7443852

**Comment by istx25** [comment]
Closing the issue due to inactivity. @santhoshs5: Feel free to follow-up if you have any more questions and we can re-open the issue. Cheers!
