### ISSUE TITLE
Acknowledgments text format in pods-acknowledgments.plist not well formatted

### ISSUE THREAD

**Issue by tkallioras** [realm/realm-cocoa#4636]
## Goals

Produce an Acknowledgements section in Settings.bundle by use of cocoapods-acknowledgements plugin

## Expected Results

Have the Realm Acknowledgements text shown in the Settings among all other framework acknowledgements

## Actual Results

Realm Acknowledgements do not appear. There is a large gap where the text should appear. The other acknowledgement texts appear just fine.

## Steps to Reproduce

Follow this guide: https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements

and then use in podfile:

`plugin 'cocoapods-acknowledgements', :settings_bundle => true`

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

Xcode 8.2.1
Build version 8C1002

Realm (2.4.2)
RealmSwift (2.4.2)

Cocoapods: 1.2.0

**Comment by istx25** [comment]
Hi @tkallioras. Thanks for letting us know about this! We'll look into fixing this soon.

**Comment by jpsim** [comment]
Hi @tkallioras, please file this issue on CocoaPods' issue tracker as this is a problem with the way pod data is parsed, sanitized and rendered rather than a problem with Realm: https://github.com/CocoaPods/CocoaPods/issues/new
