### ISSUE TITLE
Property not ignored in swift 3.0

### ISSUE THREAD

**Issue by macvinod** [realm/realm-cocoa#4637]
have this kind of property how can i ignore this property
` var photos = Array<RLMFile>()
`
I am ignoring below way 
```swift
override class func ignoredProperties() -> [String] {
        return ["photos" as String]
    }
```
but didn't ignored #2734

**Comment by istx25** [comment]
Hi @macvinod. Thanks for reaching out about this. As the [documentation states](https://realm.io/docs/swift/latest/#ignored-properties), you can ignore properties using the following syntax: 

```swift
override static func ignoredProperties() -> [String] {
    return ["photos"]
}
```

You'll want to use the `static` keyword instead of the `class` keyword and remove `as String`. Please let me know if this helped and/or you have any other questions.

**Comment by macvinod** [comment]
It's not working for me .
Here is my complete code for this. 
```
class Key : ModelWithPrimaryKey {
    dynamic var report: RLMReport!
    dynamic var index = Int.max
    dynamic var name = ""
    dynamic var notes = ""
    dynamic var type = ""
    dynamic var location = ""
    dynamic var quantity = 0
    var photos = Array<RLMFile>()
    convenience init(forReport: RLMReport) {
        self.init()
        self.report = forReport
        self.index = forReport.keys.count
    }
      override static func ignoredProperties() -> [String]
      {
        return ["photos"]
      }
    
}

class ModelWithPrimaryKey : RLMObject {
    dynamic var pk:String = UUID().uuidString
    
    override class func primaryKey() -> String {
        return "pk"
    }
    
    func initializePrimaryKeyIfNeeded() {
        if(self.pk.isEmpty) {
            self.pk = UUID().uuidString
        }
    }
    func ignoredProperties()->[String]
    {
        return [" "]
        
    }
}
```

**Comment by istx25** [comment]
Would you be able to share the versions of Realm and Tooling that you're using? [In the CONTRIBUTING guidelines](https://git.io/vgxJO), there's a script that can help determine these versions for you.

**Comment by istx25** [comment]
However, in the meantime - there's a few things in your code that I've noticed:

- The presence of `RLM` in Realm class names leads me to believe that you're either using an old version of RealmSwift or attempting to use Realm (Objective-C) in Swift. Please make sure you're importing `RealmSwift` into your Swift files and I recommend using the latest version of Realm.
- `Key` is inheriting `ModelWithPrimaryKey`, which has `func ignoredProperties()->[String]`. As the superclass isn't adding any keys, I recommend removing it but this could also be the source of your issue as the `override` in `Key` may be overriding `ModelWithPrimaryKey` and not the appropriate class/protocol inside Realm.

Let me know if this helps resolve anything. If not, we can bring one of the engineers into the question (as I'm still in training). :-)

**Comment by macvinod** [comment]
Using Realm (2.4.1)
Using RealmSwift (2.4.1)

**Comment by istx25** [comment]
Okay. Thanks for providing those values, @macvinod. Please review my last message but please also make sure you `import RealmSwift` not `import Realm`.

**Comment by macvinod** [comment]
please wait . I will try your suggestions

**Comment by macvinod** [comment]
Now it's working . Thanks for your excellent support  👍

**Comment by istx25** [comment]
😸 Awesome. Happy to hear that, @macvinod! We're here if you need anything else.
