### ISSUE TITLE
addNotificationBlock for Result<T> does not fire for changes to properties of children of T

### ISSUE THREAD

**Issue by siemensikkema** [realm/realm-cocoa#4639]
## Goals

I have 2 Realm object types: T and U where T has many U.

When adding a notification block to a Results\<T\> container type, I want to receive notifications for changes to properties of instances of U belonging to one of the Ts in the container.

## Expected Results

I expect to be notified when the value of a property of U changes.

## Actual Results

No notification is sent. However, notifications are sent when deleting (and probably when inserting) an instance of U into one of the T objects from the Results\<T\> container.

## Version of Realm and Tooling

Realm version: 2.4.2

Xcode version: 8.2.1

iOS version: 10.2.1

Dependency manager + version: Carthage 0.18.1

---

I will gladly write an example project to recreate this if you believe this behavior is a bug. The [documentation](https://realm.io/docs/swift/latest/#collection-notifications) seems to suggest my expectations should be possible (_"You modify the age property of a Dog belonging to that Person."_).

**Comment by istx25** [comment]
Hi @siemensikkema. Thanks a lot for reaching out. I'll have one of the engineers look into this. In the meantime, would you be able to share that example project you mentioned? Just to speed up diagnosis of if this is expected behaviour or a bug with Realm. Cheers!

**Comment by siemensikkema** [comment]
@istx25 @bdash I'm working on an example project. So far, the most basic version does not reproduce the error. I'm still figuring out how to reproduce my results.

**Comment by istx25** [comment]
Sounds good. Thanks for preparing that for us. 😸

**Comment by siemensikkema** [comment]
@istx25 @bdash I finally managed to get to the bottom of the issue. I made [an example project](https://github.com/siemensikkema/realmNotificationBug) to demonstrate it (all relevant code is [here](https://github.com/siemensikkema/realmNotificationBug/blob/master/NotificationBug/Realm.swift)). It turns out the problem occurs when there is a third type of object involved.
In the example I have a Guide that has many Places. A Guide can also have an owner of type User but this is optional. When I set the owner I don't receive update notifications but when I leave the owner set to nil notifications work fine.

**Comment by istx25** [comment]
Thanks for sharing this with us. We'll have someone look at this as soon as possible.

**Comment by tgoyne** [comment]
Oops. It's only checking if the first non-nil linked objects is modified rather than if any of them are modified.

**Comment by siemensikkema** [comment]
@tgoyne it's good to know I'm not crazy!

**Comment by austinzheng** [comment]
The fix for this shipped in 2.4.4.
