### ISSUE TITLE
Running crashes

### ISSUE THREAD

**Issue by Xiahaiquan** [realm/realm-cocoa#4642]
Being given as follows：

> **Questions**:  fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1744830464 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1744830464 offset: 0, Error Code=9}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.63/src/swift/stdlib/public/core/ErrorType.swift, line 178

How can i fix this
Thank you

**Comment by Xiahaiquan** [comment]
对象未被正确初始化

**Comment by istx25** [comment]
Hi @Xiahaiquan. Happy to hear you could resolve the issue yourself. Let us know if you need help with anything else. :-)

**Comment by hyouuu** [comment]
My user faced the similar issue, and I don't think he meant he fixed it just found a not-so-helpful side effect that the object was not properly initialized.

**Comment by jpsim** [comment]
@hyouuu repro cases are always appreciated, and the best way to help us fix issues 👍

**Comment by hyouuu** [comment]
Understood - however, the "lime" issue is that I think no developers have been able to repro yet :(

**Comment by hyouuu** [comment]
Oh actually, according to https://github.com/realm/realm-cocoa/issues/4820#issuecomment-292405655 they can reproduce it
