### ISSUE TITLE
Change `internal init(rlmArray: RLMArray<RLMObject>)` to `public`

### ISSUE THREAD

**Issue by rex-remind101** [realm/realm-cocoa#4644]
## Goals

Our app is mixed Swift/Objective-C with all new code written in Swift. We find ourselves having to duplicate complex logic in Swift for both `RangeReplaceableCollection` and `RLMArray` because `RLMArray` does not support `RangeReplaceableCollection`. However `List` does support `RangeReplaceableCollection` but there is no exposed way to convert `RLMArray` to `List` for swift code. Please change `internal init(rlmArray: RLMArray<RLMObject>)` to `public` so that we can stop duplicating so much code :)

https://github.com/realm/realm-cocoa/blob/master/RealmSwift/List.swift#L77

## Expected Results

`internal init(rlmArray: RLMArray<RLMObject>)` changes to `public`.
No longer having to write duplicate code for `RangeReplaceableCollection` and `RLMArray`.

**Comment by bdash** [comment]
This conversion is already exposed as [`ObjectiveCSupport.convert(object:)`](https://github.com/realm/realm-cocoa/blob/47f3c9cd036910c496c7f9d48dd510b15062bfba/RealmSwift/ObjectiveCSupport.swift#L48-L51).

**Comment by rex-remind101** [comment]
Oh man, awesomesauce, thanks!

**Comment by rex-remind101** [comment]
@bdash is there a way to convert `Object` to a `T: RLMObject` if the `List` was generated from an `RLMArray<T>`?

**Comment by rex-remind101** [comment]
Looks like `unsafeBitCast(object, to: T.self)` may be the path forward.

**Comment by jpsim** [comment]
yes, it should always be safe to bitcast an `Object` to an `RLMObject`

**Comment by rex-remind101** [comment]
@jpsim I keep crashing on `RLMIterator` it looks like when I call `contains`
```swift
// Calling:
listRLMArray.contains(unsafeBitCast(myObj, to: Object.self))

// crashes at this line: 
let accessor = unsafeBitCast(generatorBase.next() as! Object?, to: Optional<T>.self)
```
The exception is
```swift
Could not cast value of type 'RLMAccessor_1_MyObj' (0x7f9c69c38e90) to 'RealmSwift.Object' (0x11955fc08).
```
My guess is `as! Object?` is dynamically type checking and failing since `MyObj`'s type does not derive from `Object`. Should this be changed to 
```swift
let accessor = unsafeBitCast(unsafeBitCast(generatorBase.next(), to: Object?.self), to: Optional<T>.self)
```
or more simply
```swift
let accessor = unsafeBitCast(generatorBase.next(), to: Optional<T>.self)
```
?

**Comment by rex-remind101** [comment]
Hmmm.... 
```swift
let accessor = unsafeBitCast(generatorBase.next(), to: Optional<T>.self)
```
leads to
```swift
can't unsafeBitCast between types of different sizes
```
something odd is up

**Comment by jpsim** [comment]
No, that's not odd at all. `unsafeBitCast` requires that the same internal layout be used between types it's bitcasting. Going from `Object` to `RLMObject` should be safe since the first is a subclass of the second, but the other way around is not safe.

**Comment by rex-remind101** [comment]
How do I convert from `RLMObject` to `Object`?

**Comment by jpsim** [comment]
Looks like that conversion is missing from `ObjectiveCSupport.swift`'s conversion methods.

**Comment by rex-remind101** [comment]
Would it be easy enough to write on my end? Have a deadline I'm trying to meet :)

**Comment by jpsim** [comment]
We've always made it quite clear that the Objective-C and Swift Realm APIs aren't designed to interoperate. There are partial solutions to converting RLMObjects to Objects and vice-versa, but a complete solution is more involved than I can provide right now.

You may have some luck with [`Object.unsafeCastToRLMObject()`](https://github.com/realm/realm-cocoa/blob/v2.4.2/RealmSwift/Util.swift#L48-L54) but there be dragons and you're on your own if you end up using that and get a crash,.

**Comment by tgoyne** [comment]
You can't pass an object which is actually an `RLMObject` subclass to something expecting an `Object` subclass. It works the other way around because `Object` secretly implements all of `RLMObjects`'s methods and just doesn't expose some of them publicly, but the inverse is not true.

**Comment by rex-remind101** [comment]
How does `func convert(object: RLMArray<RLMObject>) -> List<Object>` work safely then?

**Comment by tgoyne** [comment]
The only safe use of it is when it's called on an RLMArray of an `Object` subclass (i.e. when it's passed a thing that isn't actually a `RLMArray<RLMObject>`).
