### ISSUE TITLE
Property used to populate MFMailComposeViewController slow to resolve

### ISSUE THREAD

**Issue by dmorrow** [realm/realm-cocoa#4646]
## Goals
Populate MFMailComposeViewController.setToRecipients() with an email that is a property of a relationship on a Realm object

## Expected Results

To: in the MFMailComposeViewController should show the email from the Realm object

## Actual Results

The To: field is only populated intermittently, and never on the first attempt.  Almost like a cache needs to be created for this property.

If I delay the presentation of the MFMailComposeViewController by even 0.1 seconds then the fields are properly populated.

Less often the group.name is not populated.  But not as frequently as the email address.

## Code Sample

    if let group = group, let admin = group.admin {
        let mailComposerVC = MFMailComposeViewController()
        mailComposerVC.setToRecipients([admin.email])
        mailComposerVC.setSubject(group.name)
        Router.shared.navigationController?.present(mailComposerVC, animated: true, completion: nil)
    }

------------

    open class Group: IDObject {
        dynamic var name: String = ""
        dynamic var admin: Parent?
        ...
    }

    class Parent: IDObject {
        dynamic var email: String = ""
        ...
    }

`IDObject` is a subclass of `Object`

## Version of Realm and Tooling

Realm version: 2.4.2

**Comment by dmorrow** [comment]
Sorry, this was an issue with our API service

**Comment by istx25** [comment]
Hi @dmorrow. Happy to hear you figured out what was causing the problem. Let us know if you need help with anything else. :-)
