### ISSUE TITLE
Object deleted or invalidated when deleting referenced objects

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-cocoa#4654]
I want to delete an object with all its referencing objects. Since there is not yet a cascading delete I do the following:

```
try! self.realm.write {
    self.realm.delete(customer.address);
    self.realm.delete(customer.contact);
    self.realm.delete(customer.history);
    self.realm.delete(customer); // app crashes here
}
```

Deleting the address, the contact and the history object works fine. But when it comes to deleting the customer object itself the error is:

`'RLMException', reason: 'Object has been deleted or invalidated.'`

I thought doing all this inside the write transaction would do the trick but it doesnt. So how am I supposed to delete the customer object after I deleted all referenced objects?

**Comment by istx25** [comment]
Hi @Montrazul. Thanks for reaching out about this. We will review what you've provided and have someone follow-up with you soon. Cheers!

**Comment by istx25** [comment]
Hi @Montrazul. How are you fetching/creating the `customer` object shown in your code example?Please provide that portion of your code as well. Thanks.

**Comment by istx25** [comment]
Considering you closed the issue, I assume you resolved the issue? Would you be able to elaborate what you did for others who run into the issue? Thanks.

**Comment by Montrazul** [comment]
I can try but I did not really understand the problem and the solution.
I am holding my customer objects in a `List<Customer>()` and they are presented in a `UITableView`. Im using realm together with the realm mobile platform and I implemented the `RLMNotificationToken` to notify me when there are changes in the dataset. When there is a notification I trigger a UI refresh.

The process I was able to debug is the following

1. Delete `customer.address`
2. Get notified by the mobile platform that something got changed
3. UI refresh
4. Delete `customer.contact`
5. Get notified by the mobile platform that something got changed
6. UI refresh
7. Delete `customer.history`
8. Get notified by the mobile platform that something got changed
9. UI refresh
10. Delete customer
11. Get notified by the mobile platform that something got changed
12. UI refresh
13. sometimes crash, sometimes not

After the last UI refresh when the customer got deleted I sometimes got the error `object has been deleted or invalidated` and sometimes not. So I thought maybe there is some kind of race condition between when the `customer` is really physically deleted from the local realm and when there is the notification triggering the UI refresh.

So what I did to solve it was:

1. First delete the customer from the list
2. UI Refresh
3. Perform the deletion of the `custeromer` and all referenced objects

With that solution the error is never occuring. First I thought putting those four delete statements all toghter in a `write` block would mean that they all are done locally first and only synchronized when everything is done but Im wrong. I get a change notification after each step.
