### ISSUE TITLE
Skipping write block (Swift 3.0)

### ISSUE THREAD

**Issue by ethamine** [realm/realm-cocoa#4659]
## Goals

Process a write transaction.

## Expected Results

The write to happen

## Actual Results

Write block is just being skipped

## Steps to Reproduce

Follow your docs, i guess.
When i check it with the debugger realm is not nil. I also tried wrapping everything in do {} catch {} block, but it doesnt throw any errors, just goes past the write block. I've tried resetting simulator and building on a device.

## Code Sample

                let realm = try! Realm()
                let accountList = realm.objects(Account.self)
                var account = accountList.first
                try! realm.write {
                   ... write code ...
                }

## Version of Realm and Tooling

Swift version turned out to be 3.0.2

Realm version: 2.4.2 (also tried downgrading to 2.4.1)

Xcode version: 8.2.1

iOS/OSX version: 10.2,10.3/10.11.6

Dependency manager + version: Cocoapods 1.2.0

**Comment by istx25** [comment]
Hi @ethamine. Thanks for reaching out about this! I saw you closed the issue which makes me think you resolved the issue. If that's the case, awesome! We're here to help if you need anything else.
