### ISSUE TITLE
New feature: filtering string properties using inequalities

### ISSUE THREAD

**Issue by LiborZ** [realm/realm-cocoa#4664]
## Goals

Realm's query engine does not currently support filtering string properties using inequalities. I would like if this could be changed. I can sort results by string with Realm and I would like to filter by inequality operators (>, <)  too.

## Expected Results

I have attribute `itemIdForDateOrder` which is string (looks something like this: `11e6-eef3-09306910-baa7-417b3207abf6`). Sorting works without problem. I would like to be working this in predicate:
```
if let item = newerThan {
   formatString += " AND itemIdForDateOrder > '" + item.itemIdForDateOrder + "'"
}
```

Thanks

**Comment by bdash** [comment]
Thanks for the suggestion. I've added this request to the list of currently unsupported predicates at #1490.
