### ISSUE TITLE
Cannot concatenate ‘str’ and ‘NoneType’ objects

### ISSUE THREAD

**Issue by CesarRN** [realm/realm-cocoa#4667]
## Notes

Traceback (most recent call last):

```
File "/Users/cesar/Library/Application Support/Realm/rlm_lldb.py", line 227, in RLMResults_SummaryProvider
return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**I have check "rlm_lldb.py", it is the last one and it has the last changes to solve the error above.**
But I got it :frowning:

How can I do?

Thanks!

## Goals

Query with `NSPredicate`.

## Expected Results

Make a query.

## Actual Results

```
Traceback (most recent call last):
File "/Users/cesar/Library/Application Support/Realm/rlm_lldb.py", line 227, in RLMResults_SummaryProvider
return 'Unevaluated query on ' + class_name
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

## Steps to Reproduce

Create a NSPredicate with filter, like " field == '%@'", fieldValue

## Version of Realm and Tooling

- Realm version: 2.4.2
- Xcode version: 8.2
- iOS/OSX version: 10.11.6 (iPad Mini 10)
- Dependency manager + version: Cocoa Pods 1.1.0.rc.2

**Comment by bdash** [comment]
This sounds a lot like the issue fixed by #3714. Can you try installing the latest version of `rlm_lldb.py` and report as to whether that fixes the problem?

**Comment by CesarRN** [comment]
Hello bdash, I compare my rlm_lldb.py with the latest in the #3714 and I have the same file with the latest changes.

How can I reinstall the file?

Thanks

**Comment by bdash** [comment]
You can reinstall it by running the new version of `rlm_lldb.py` from the Terminal.

The line numbers from your error message do suggest you may already have the latest version though.

**Comment by bdash** [comment]
I was able to reproduce this and track down the problem.

**Comment by CesarRN** [comment]
Hello bdash, Can I try anything? 

I would like to help to resolve this issue. I am very interesting.

Thanks.

**Comment by bdash** [comment]
Please install the version of rlm_lldb.py that's in current Git master. I just merged a fix for this problem.

**Comment by CesarRN** [comment]
What is the best way to install the rlm_lldb.py last version?

Thanks bdash

**Comment by bdash** [comment]
You can install it by running the new version of rlm_lldb.py from the Terminal.
