### ISSUE TITLE
Realm at path already opened with a different schema mode

### ISSUE THREAD

**Issue by tzm41** [realm/realm-cocoa#4670]
## Goals

Update Realm model in network request observable `flatMap` function.

## Expected Results

Works fine? Or maybe I am doing something wrong.

## Actual Results

Crashed with exception `Realm at path '%1' already opened with a different schema mode`

## Steps to Reproduce

Specifically, the setter of this variable in class `UserProfileModel`:
```Swift
var avatarURL: URL? {
    get {
        guard realm_avatarURL.characters.count > 0 else { return nil }
        return URL(string: realm_avatarURL)
    }
    set {
        let newURLString = newValue?.absoluteString ?? ""
        let realm = try! Realm()
        try! realm.write {
            if newURLString != realm_avatarURL {
                realm_avatarURL = newURLString
            }
        }
    }
}
```
is called in my network method where `userProfile` is a `UserProfileModel`:
```Swift
requestObservable = s3Object.flatMap { s3Object -> Observable<Bool> in
    userProfile.avatarURL = URL(string: s3Object.publicURL)
    userProfile.avatarKey = s3Object.key
    ...
```

## Version of Realm and Tooling

Realm version: 2.4.2

Xcode version: 8.2

iOS/OSX version: iOS 10.2.1

Dependency manager + version: CocoaPods 1.2.0

**Comment by jpsim** [comment]
I'm not sure, but I think what's happening here is that you're opening a Realm at a same path twice (or more) with different configurations. Is it possible you're opening a Realm at the default location but with a custom configuration, while also opening it with the default configuration in the code you posted? Thanks!

**Comment by tzm41** [comment]
Thanks for the reply! I was suspecting the same thing. Will post update very soon.

**Comment by tzm41** [comment]
If I try to create the Realm with the same configuration to execute the write, incorrect thread exception occurs:
```Swift
var avatarURL: URL? {
    get {
        guard realm_avatarURL.characters.count > 0 else { return nil }
        return URL(string: realm_avatarURL)
    }
    set {
        let newURLString = newValue?.absoluteString ?? ""
        guard let configuration = self.realm?.configuration else { return }
        let realm = try! Realm(configuration: configuration)
        try! realm.write {
            if newURLString != realm_avatarURL {
                realm_avatarURL = newURLString
            }
        }
    }
}
```

**Comment by tzm41** [comment]
Ok, issue resolved by observing using main scheduler. Thanks much!

**Comment by istx25** [comment]
Awesome to hear that, @tzm41. Feel free to reach out again if you need any more assistance. :)
