### ISSUE TITLE
RLM crashes when primary key is configured by two properties

### ISSUE THREAD

**Issue by neetin** [realm/realm-cocoa#4672]
It does not occur every time though.

````
 // here is the code 
class Observation: Object {
  dynamic var value: Double = 0
  dynamic var unit: String = ""
  dynamic var date: Date = Date() {
    didSet {
      compoundKey = compoundKeyValue()
    }
  }
  dynamic var code: String = "" {
    didSet {
      compoundKey = compoundKeyValue()
    }
  }
  
  public dynamic var compoundKey: String = ""
  public override static func primaryKey() -> String? {
    return "compoundKey"
  }
  
  private func compoundKeyValue() -> String {
    return "\(date.timeIntervalSince1970)\(code)"
  }
}
````
<img width="1160" alt="rlm_crash" src="https://cloud.githubusercontent.com/assets/386799/22971909/7fe2c9c6-f39f-11e6-87d9-9865d3cf671a.png">

**Comment by istx25** [comment]
Hi @neetin. Thanks for reaching out. One of our engineers will review what you've provided and follow-up with you soon. Cheers!

**Comment by bdash** [comment]
@neetin, how are you using the class in question to trigger the crash? Presumably declaring the class isn't itself sufficient to trigger it. Can you share a self-contained code sample that reproduces the problem?

One thing to note is that `willSet` / `didSet` aren't supported on persisted properties of Realm model classes. I don't know if this is relevant to your crash, but it's something that will likely cause you other problems.

**Comment by istx25** [comment]
Hi @neetin. Echoing @bdash's request, would you be able to share a self-contained code sample or a piece of code that reproduces the issue? Thanks.

**Comment by jpsim** [comment]
Hi @neetin, I'm just following up on our last few requests for more information. Thanks!
