### ISSUE TITLE
Autoupdating query - single item

### ISSUE THREAD

**Issue by dmorrow** [realm/realm-cocoa#4677]
## Goals

Results are able to autoupdate even if the initial query is empty.

```swift
class IDObject: Object { 
    dynamic var identifier:Int
}

let results:Results<IDObject> = realm.objects(IDObject.self).filter(NSPredicate(format:"identifier = %d", 1)
print (results.count)  //=>0
let obj = IDObject()
obj.identifier = 1
realm.add(obj) 
print (results.count)  //=>1
```

However, what if we want a single object?

```swift
let result:IDObject? = realm.objects(IDObject.self).filter(NSPredicate(format:"identifier = %d", 1).first
print (result)  //=> result is nil
let obj = IDObject()
obj.identifier = 1
realm.add(obj) 
print (result)  //=> result is still nil
```

## Expected Results

One way to handle this would be to always get a `Results` object and then have to unwrap `.first` every time we wanted to access the single object. 

However, it would be great if there was a `SingleResult<T>` class which would only hold one or zero objects.  That object could be autoupdating as well, which would protect from this use case.

**Comment by istx25** [comment]
Hi @dmorrow. Thanks for reaching out about this. Someone will review what you've shared and follow-up with a solution or additional questions. Cheers!

**Comment by austinzheng** [comment]
Thanks for getting in touch with us! This sounds like a great idea for an enhancement; I will add it to our backlog until the relevant engineers can discuss it.

**Comment by jpsim** [comment]
I'm not sure this is something we'd want. It would lead to super surprising results. Just as an example, keep in mind that Results aren't guaranteed to preserve their sorting order across Realm transaction versions, so the object you're holding on to could become a whole different object at a later time.

Even if you sort the Results, the same thing could happen when a different object becomes first in the ordering.

Not to mention that we'd need to keep the query alive and running for the duration of this object's lifecycle, which is a lot more expensive than just keeping a pointer to the object you got originally...

For these reasons, I'm closing this ticket. I hope you understand @dmorrow.
