### ISSUE TITLE
I am getting bad access with following code

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#4678]
I am storing User object in realm.
Afterwards I am using this object as follows from a singleton class.

```swift
class UserSingleton{
    private static var _currentUser: User!

    private static var sharedManager: UserSingleton = {
       let shared = UserSingleton()
       return shared
    }()
    
    class func shared() -> UserSingleton {
        return sharedManager
    }

    static var currentUser: User?{
        set {
            _currentUser = currentUser
        }
        get {
            let results = try! RealmHelper.shared().fetch(type: User.self, predicate: nil)
            if let userInfo = results.last {
                _currentUser = userInfo
                return _currentUser!
            }
            return nil
        }
    }
}
```

User class
=========
```swift
class User:Object, Mappable
{
    dynamic var newUser: String?
    override static func ignoredProperties() -> [String] {
       return ["isNewUser"]
    }
//======
    lazy var isNewUser: Bool = { [weak self] in
        return self!.newUser == "yes" ? true :false
    }()
}
```

I am accessing this variable in a function like this.
```swift 
func foo{
        let newUser = UserSingleton.currentUser?.isNewBackupApproach
}
```

after this function call i am getting this error.

[CFString release]: message sent to deallocated instance 0x19758270

**Comment by istx25** [comment]
Hi @santhoshs5. Thanks for reaching out about this. Someone will review what you've provided and follow-up with you soon. Cheers!

**Comment by istx25** [comment]
Hi @santhoshs5. Would you be able to provide the full models? `isNewBackupApproach` is not in the code samples you provided.

**Comment by istx25** [comment]
Due to inactivity, I assume you've corrected the issue? I'm closing the issue but if you still require assistance, please follow-up and we can reopen the issue and continue. Cheers!
