### ISSUE TITLE
Feature Request: add deleteRealmIfMigrationFailed property

### ISSUE THREAD

**Issue by puttin** [realm/realm-cocoa#4685]
## Goals

What do you want to achieve?
deleteRealmIfMigrationFailed
## Expected Results

What did you expected to happen?
if migration is needed but failed delete that realm

**Comment by istx25** [comment]
Hi @puttin. Thanks for reaching out! Would you be able to provide us with more information on your tooling setup and what version of Realm you're using? And if possible, a sample project or code sample of where you're trying to do this and where it's failing. Thanks!

**Comment by puttin** [comment]
Hi @istx25 , as you can see in the title, it's a feature request.

So it's a feature request on last version which is 2.4.3 currently.

---

`RLMRealmConfiguration` has a property `deleteRealmIfMigrationNeeded` which delete Realm files if migration needed.

Sometimes developers may expect migration to be executed first, but if migration fails, the Realm files should be delete to cleanup.

**Comment by istx25** [comment]
Hi @puttin. My apologies, I guess I misread. Let me change the labels and get some eyes on this.

**Comment by jpsim** [comment]
I'm struggling to find situations in which you as a developer won't be able to write a valid migration block, requiring this feature. @puttin could you please provide some examples of where our current functionality fails you? Thanks.

**Comment by puttin** [comment]
Developers may use the Realm as a local cache of remote datas.
They bump the scheme version but may don't really care migration manually by migration block.
Auto migration is good enough for most situation. But when migration block is required to do migration, they prefer to delete the cache directly.

**Comment by jpsim** [comment]
I really don't think that specifying a migration block which sometimes works, sometimes doesn't, encourages good developer practices.
