### ISSUE TITLE
Error: No such file collection_notifications.cpp while build

### ISSUE THREAD

**Issue by nikunjazilen** [realm/realm-cocoa#4686]
Hi,

I am facing error like below "library not found for -lRealm"

Can you please help me to build this project?

```
library not found for -lRealm
```
Best Regards,
Nikunj Jadav

**Comment by clementleroy** [comment]
Hi !

Maybe this issue #4498 can help you resolve your problem.

**Comment by istx25** [comment]
Hi @nikunjazilen. Would you be able to report what versions of tooling and Realm you're using. There's a script in the contributing guidelines which will help you determine these values, which can be found [here](https://git.io/vgxJO). From there, we'll be able to better assist you.

**Comment by nikunjazilen** [comment]
Hi,

Thanks for the reply, Issue resolve after made demo myself and installed pod of realm. Now I am integrate draw demo [https://github.com/realm/realm-cocoa/tree/master/examples/ios/objc/Draw](url) and its successfully working in different devices. I have some questions. If you help me that would be great help for me to go ahead on next step.

1) Can you please explain me authURL:::::::::::http://192.168.X.XX:9080 and Login syncURL:::::::::::realm://192.168.X.XX:9080/~/Draw?

2) There is a static NSString *const kIPAddress = @"192.168.X.XX" in Constant.h file. Is it the server IP Address which is the central of my network?

3) Is not supported different network? For example: I run the draw demo with step 2 IP Address in different device and one my device connected to hotspot wifi network and other 2 devices are own connected wifi network. But when I drawing from hotspot wifi network its not reflect to other devices. Can you tell me the issue what is the problem there? I have logged in all devices with same credentials.

4) How can I realm set up with my own sever to implement the drawing demo? Is it free or paid service?

5) Why Login failed: the request time out occurred even realm object server connected?

Best Regards,
Nikunj

**Comment by istx25** [comment]
Okay, happy to hear you could resolve the issue. We're here to help if you need anything else.
