### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JQHee** [realm/realm-cocoa#4689]
I want to make the attribute (NSInteger) type (id) into the realm of behind me change (id) to insert (nsstrings) type, crash message realm must not be nil.

**Comment by istx25** [comment]
Hi @JQHee. Thanks for reaching out. Unfortunately, I don't really understand your question. Would you be able to elaborate further and provide a crash log, sample code or any other supporting information that would lead us in the right direction. Thanks!

**Comment by jpsim** [comment]
Closing this since we haven't heard any clarifications.
