### ISSUE TITLE
Uncaught Exception: 'Property names beginning with 'new' are not supported'

### ISSUE THREAD

**Issue by Jinkeycode** [realm/realm-cocoa#4692]
**Original title**: _*** Terminating app due to uncaught exception 'RLMException', reason: 'Property names beginning with 'new' are not supported. Swift follows ARC's ownership rules for methods based on their name, which results in memory leaks when accessing properties which return retained values via KVC.'_

I got an error after I update realm form 2.1 to 2.4.3：

*** Terminating app due to uncaught exception 'RLMException', reason: 'Property names beginning with 'new' are not supported. Swift follows ARC's ownership rules for methods based on their name, which results in memory leaks when accessing properties which return retained values via KVC.'

how can I fix it

**Comment by bensarz** [comment]
We have received the same error when upgrading from 2.4.2 to 2.4.3.
However, 2.4.3 claims to not have any breaking API changes:
https://github.com/realm/realm-cocoa/releases/tag/v2.4.3

**Comment by bdash** [comment]
Presumably due to #4633. Thoughts, @tgoyne?

**Comment by tgoyne** [comment]
It is not listed as a breaking change because properties which such names appeared to never have worked in the first place, and the goal of the change was just to make it fail in a more understandable way. Do you have an example of a model which works correctly with Realm 2.4.2 which is rejected by 2.4.3? It may be that the check is overly broad.

**Comment by bensarz** [comment]
We did have a model that had a property called `newValue` but it wasn't being used yet, so we didn't see it as a problem. We have renamed our property and should be good to go now.
Thanks for the feedback guys.

**Comment by Jinkeycode** [comment]
@tgoyne my data model has no property with prefix 'new'，it works correctly in Realm 2.1.0 ，but is  failed in 2.4.3.

![image](https://cloud.githubusercontent.com/assets/12148377/23288295/b05f4cb6-fa7d-11e6-856f-233625b6d842.png)

**Comment by bdash** [comment]
@Jinkeycode, are those all of the properties declared in your class? Is that your only model class? None of those names look like they'd be rejected by the check added by #4633.

**Comment by Jinkeycode** [comment]
@bdash，oh！it's not the only model I have, I figure out that I have a property with prefix 'new'. I will fix it,thanks. Except 'new', is there any other prefix can not be used?

**Comment by bdash** [comment]
Names starting with `alloc`, `new`, `copy`, `mutableCopy` are disallowed if followed by a non-lowercase letter (or nothing).

**Comment by Jinkeycode** [comment]
@bdash ，I got it. Thanks for your help !

**Comment by istx25** [comment]
Do you have any other questions, @Jinkeycode?

**Comment by austinzheng** [comment]
I'm closing this ticket. If you have any more questions, feel free to file another one!
