### ISSUE TITLE
Can not run after importing Realm.framework

### ISSUE THREAD

**Issue by SoKoDaMie** [realm/realm-cocoa#4695]
## Goals

Run the project after importing Realm.framework

## Expected Results

The project to build and run successfully.

## Actual Results

The XCode compiler prompts me bash: 

/Users/wangming/Library/Developer/Xcode/DerivedData/TestRealm-agwbcitbddgewybfnhldxljtcuor/Build/Products/Debug-iphonesimulator/TestRealm.app/Frameworks/Realm.framework/strip-frameworks.sh: No such file or directory

## Steps to Reproduce

_No reproduce steps were provided_ ^@istx25.

## Code Sample

_No code sample was provided_ ^@istx25.

## Version of Realm and Tooling

- Realm version: 2.4.3
- Xcode version: 8.3
- iOS/OSX version:  ?
- Dependency manager + version: 
![Uploading EBDBD9BB-90A8-4515-A165-B2D4DA38C908.png…]()

**Comment by istx25** [comment]
Hi there, @SoKoDaMie. Would you be able to provide us with what dependency manager and version(s) you are using (the screenshot you tried to share failed to upload) as well as any other supporting information that you can provide.

**Comment by jpsim** [comment]
Hi @SoKoDaMie, I'm just following up on @istx25's request for more information. Thanks.

**Comment by austinzheng** [comment]
It's been a week, closing this ticket. Please file a new one if you need additional support.
