### ISSUE TITLE
Realm filesize increasing without storing new data causing mmap() failed: Cannot allocate memory size

### ISSUE THREAD

**Issue by pplant** [realm/realm-cocoa#4696]
Hi there, currently I'm observing a strange behaviour while using Realm. It seems that every time I open the my App (be it a restart of the app, or a background foreground process) seems to increase the size of the realm file without having new objects being stored. So the amount of objects stored are not changing at least not dramatically, explaining an increase of Realm file size by 1000%. Weird?! 

So I'm not sure if this is a problem how I implemented/integrated Realm in my app or if it is a issue from your side. 

A test with my iPhone 6s has shown that the Realm file increased from 4 mb to 200 mb by closing, reopening, moving it to background and back to foreground again multiple times.

Is there away to extract a Realm file to see where/what all this data is if it is not coming from stored object data it must be Metadata, right? I can also provide a copy of the big file!

**This is the full stack trace (Crashlytics):**

Fatal Exception: RLMException
mmap() failed: Cannot allocate memory size: 2147483648 offset: 0

`
Fatal Exception: RLMException
0  CoreFoundation                 0x192c811b8 __exceptionPreprocess
1  libobjc.A.dylib                0x1916b855c objc_exception_throw
2  MyApp         0x1002eb170 RLMSetErrorOrThrow(NSError*, NSError* __autoreleasing*) (RLMUtil.mm:269)
3  MyApp         0x1002d44fc RLMRealmTranslateException(NSError* __autoreleasing*) (RLMRealm.mm:242)
4  MyApp         0x1002d5220 +[RLMRealm realmWithConfiguration:error:] (RLMRealm.mm:299)
5  MyApp         0x1002d4154 +[RLMRealm defaultRealm] (RLMRealm.mm:165)
6  MyApp         0x1004ed7dc -[VLRealm setupRealms] (VLRealm.m:60)
7  MyApp         0x1000b19b4 -[VLCAppDelegate application:didFinishLaunchingWithOptions:] (VLCAppDelegate.m:51)
8  UIKit                          0x198ba86a4 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
9  UIKit                          0x198db8a98 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
10 UIKit                          0x198dbe808 -[UIApplication _runWithMainScene:transitionContext:completion:]
11 UIKit                          0x198dd3104 __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke.3139
12 UIKit                          0x198dbb7ec -[UIApplication workspaceDidEndTransaction:]
13 FrontBoardServices             0x19485792c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
14 FrontBoardServices             0x194857798 -[FBSSerialQueue _performNext]
15 FrontBoardServices             0x194857b40 -[FBSSerialQueue _performNextFromRunLoopSource]
16 CoreFoundation                 0x192c2eb5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
17 CoreFoundation                 0x192c2e4a4 __CFRunLoopDoSources0
18 CoreFoundation                 0x192c2c0a4 __CFRunLoopRun
19 CoreFoundation                 0x192b5a2b8 CFRunLoopRunSpecific
20 UIKit                          0x198ba17b0 -[UIApplication _run]
21 UIKit                          0x198b9c534 UIApplicationMain
22 MyApp         0x1000c4ef4 main (main.m:14)
23 libdispatch.dylib              0x191b3d5b8 (Missing)
`

**Metadata:**

Realm version: 2.4.2

Xcode version: 8.2.1

iOS/OSX version: iOS 10.2

Dependency manager + version: Cocoapods 1.0.1

**Updated 24.02.2017 12.15:**

After moving back to Realm version 2.0.3 used in a previous release and not touching my Realm code it seems this issue is not occurring.

**Comment by pplant** [comment]
Seems to be a duplicate of [https://github.com/realm/realm-cocoa/issues/4590](#4590). Is there already a version in production fixing this?

**Comment by istx25** [comment]
Hi @pplant. Thanks for reporting this. As you've seen, this issue was being tracked in #4590 and @bdash merged a fix for it in #4598. Please ensure you're using the latest version of Realm and if you're still seeing the issue, we can try to reproduce it here and continue with debugging.

**Comment by yuldong** [comment]
see the lastest release version2.4.3 notes
hope 2.4.3 fixed this issue.
