### ISSUE TITLE
Swift example in Objective-C documentation

### ISSUE THREAD

**Issue by istx25** [realm/realm-cocoa#4697]
We received an email in HelpScout saying that they found a Swift example inside the Objective-C documentation. Took a couple minutes to find the line but eventually did and it's in [Relationships](https://realm.io/docs/objc/latest/#relationships), "To-One Relationships" subsection.

>When using RLMObject properties, you can access nested properties using normal property syntax. For example `rex.owner?.address.country` will traverse the object graph and automatically fetch each object from Realm as needed.

`rex.owner?.address.country` has a Swift optional and should not.

**Comment by jpsim** [comment]
I still don't get why you think this is necessary...

**Comment by austinzheng** [comment]
Closing because this is resolved.
