### ISSUE TITLE
Query operation result infinite memory

### ISSUE THREAD

**Issue by yuldong** [realm/realm-cocoa#4704]
## would query operation result a huge memory? 
Besides, the memory won’t decrese in a few minutes 

## Goals

according the condition, judge is the any data in realm fit it, and then return a new NSObject by the result?

## Expected Results

just a little memory increase.

## Actual Results

the app's memory increase almost 100M every time.
After few times, the app was killed itself.

## Steps to Reproduce

query RLMObjects in a loop.

## Code Sample
```objc
CHDRealm *realm = [CHDRealm defaultCashier];
    [self.shopGoodsCategoryArray enumerateObjectsUsingBlock:^(CHDGoodsCategory * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        @xStrongify
        if (obj.categoryType != kCategoryType_search) {
            [self refreshMemberDiscountWithCategory:obj.commodities memberTypeID:memberTypeID realm:realm];
        }
    }];

- (void)refreshMemberDiscountWithCategory:(CHDGoodsCategory *)category memberTypeID:(NSString *)memberTypeID realm:(CHDRealm *)realm {
    
    [CHDCommodityService updateCommoditiesDiscountValueWithCommodityArray:category.commodities memberTypeID:memberTypeID realm:realm];
}

// **Class CHDCommodityService**
+ (void)updateCommoditiesDiscountValueWithCommodityArray:(NSArray <CHDBaseCommodity *> *)commodityArray
                                                    memberTypeID:(NSString *)memberTypeID
                                                   realm:(CHDRealm *)realm{
    realm = realm ? realm : [CHDRealm defaultCashier];
    for (CHDBaseCommodity *commodity in commodityArray) {
        CHDCommodityMemberDiscount *discountModel = nil;
        if (isStringWithAnyText(memberTypeID)) {
            
            discountModel = [CHDCommodityMemberDiscountTableManager getMemberDiscountWithCommodityID:commodity.commodityID memberTypeID:memberTypeID realm:realm];
            if (!discountModel) {
                
                discountModel = [CHDCategoryMemberDiscountTableManager getMemberDiscountWithCategoryID:commodity.categoryId memberTypeID:memberTypeID realm:realm];
            }
            
            if (discountModel) {
                discountModel.commodityID = commodity.commodityID.integerValue;
            }
        }
        commodity.commodityMemberDiscount = discountModel;
    }
}

+ (CHDCommodityMemberDiscount *)getMemberDiscountWithCommodityID:(NSString *)commodityID
                                                    memberTypeID:(NSString *)memberTypeID
                                                           realm:(CHDRealm *)realm {
    if (commodityID.length == 0 || memberTypeID.length == 0 || !realm) {
        return nil;
    }
    
    NSString *where = [NSString stringWithFormat:@"itemID=%@ AND memberTypeID=%@",commodityID, memberTypeID];
    RLMResults *objects = [CHDCommodityMemberDiscountTable objectsInRealm:realm where:where];
    CHDCommodityMemberDiscountTable *discountRlm = objects.firstObject;
    
    if (discountRlm) {
        CHDCommodityMemberDiscount *discountModel = [[CHDCommodityMemberDiscount alloc] init];
        discountModel.discountID = discountRlm.discountID;
        discountModel.memberTypeID = discountRlm.memberTypeID;
        discountModel.discount = discountRlm.discount;
        discountModel.discountType = kMemberDiscountType_Commodity;
        discountModel.commodityID = commodityID.integerValue;
        return discountModel;
    }
    
    return nil;
}

+ (CHDCommodityMemberDiscount *)getMemberDiscountWithCategoryID:(NSString *)categoryID
                                                    memberTypeID:(NSString *)memberTypeID
                                                          realm:(CHDRealm *)realm {
    
    if (categoryID.length == 0 || memberTypeID.length == 0 || !realm) {
        return nil;
    }
    
    NSString *where = [NSString stringWithFormat:@"categoryID=%@ AND memberTypeID=%@",categoryID, memberTypeID];
    RLMResults *objects = [CHDCategoryMemberDiscountTable objectsInRealm:realm where:where];
    CHDCategoryMemberDiscountTable *discountRlm = objects.firstObject;
    
    if (discountRlm) {
        CHDCommodityMemberDiscount *discountModel = [[CHDCommodityMemberDiscount alloc] init];
        discountModel.discountID = discountRlm.discountID;
        discountModel.memberTypeID = discountRlm.memberTypeID;
        discountModel.discount = discountRlm.discount;
        discountModel.discountType = kMemberDiscountType_Category;
        return discountModel;
    }
    
    return nil;
}
```
## Version of Realm and Tooling
Realm version: 2.4.3

Xcode version: 8.2

iOS/OSX version: 10.2

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us, and sorry you're experiencing issues. Unfortunately, it looks like your code listings are incomplete (for example, there is no definition of `refreshMemberDiscountWithCategory:memberTypeID:realm:`. Would you be willing to build a small project that reproduces the behavior so we can examine it ourselves and help you further? You can send a zip file containing a project to help@realm.io.

**Comment by bdash** [comment]
It'd also be useful to reproduce the problem under Instruments' memory allocation instrument. This will give you insight into which objects are allocated and tying up memory. One thing this can help you spot is cases where you're allocating objects inside a loop and they're escaping into the containing autorelease pool, resulting in the heap growing constantly while the loop progresses. This case is commonly addressed by inserting an explicit autorelease pool within the body of the loop to limit the lifetimes of any objects generated during the body of the loop.

**Comment by yuldong** [comment]
@austinzheng i have updated the issue， and I will send a project later. thanks.

**Comment by yuldong** [comment]
@bdash thanks for the advice, I will try your way and share the conclusion.

**Comment by yuldong** [comment]
![image](https://cloud.githubusercontent.com/assets/5005006/23441122/4a906c76-fe5b-11e6-90fc-8960c0da8d6f.png)
@bdash @austinzheng

**Comment by yuldong** [comment]
![image](https://cloud.githubusercontent.com/assets/5005006/23441275/527ff4c8-fe5c-11e6-9c70-d0cf09b87c9f.png)
@bdash added autorelease pool.
```
    CHDRealm *realm = [CHDRealm defaultCashier];
    [self.shopGoodsCategoryArray enumerateObjectsUsingBlock:^(CHDGoodsCategory * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        @xStrongify
        if (obj.categoryType != kCategoryType_search) {
            @autoreleasepool {
                [self refreshMemberDiscountWithCategory:obj memberTypeID:memberTypeID realm:realm];
            }
        }
    }];
```

**Comment by austinzheng** [comment]
We'll wait for you to send over a demonstration project.

**Comment by yuldong** [comment]
@austinzheng 
因为当前这个问题比较紧急，而当前的项目又不能单独拉出来发给你们。
目前我的处理方式：
通过先将数据库中的相关结果[这种数据比较少]查出来，放在内存中，然后在循环中对在内存中的的结果集进行filter。从而避免在循环里面对realm进行filter.
调整后，该问题暂时解决了。
暂时将改问题关闭，后续我会将单独拉出来的project发给你们。
再次感谢
Because this problem is more urgent, and  I couldn't send you the current project in time.
Now my way:First, query the realm results [just a few data] into memory, then filtering the memory results in the loop. By avoiding query the realm in the loop. the problem has been solved for now.
so i closed this problem temporarily. The follow-up, I will send you the demonstration  project.
Thanks again.

**Comment by austinzheng** [comment]
Thank you! I'm glad you were able to find a workaround. Please do send us your demonstration project whenever you have time. If you have any more questions feel free to file another ticket.
