### ISSUE TITLE
Return current transaction in transactionWithBlock or beginWriteTransaction

### ISSUE THREAD

**Issue by tbeech** [realm/realm-cocoa#4707]
## Goals

What do you want to achieve?
When beginning a write transaction whether using beginWriteTransaction or by using transactionWithBlock, it would be nice if the realm is already in a write transaction to just return the current transaction. I have public methods that can be used stand alone (e.g. a transaction needs to be created) but are also called from other methods where a transaction will have already been started.

## Expected Results
If I'm currently in a write transaction, return the current transaction otherwise begin a new transaction.

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample
While I realize that I can check if the realm is currently in a transaction it results in code that looks like this: 
``` obj-c
        if( [[RLMRealm defaultRealm] inWriteTransaction] ) {
          DLLibrary *document = [DLLibrary objectForPrimaryKey:documentId];
          document.isCached = NO;
          document.bytesWritten = 0;
        }
        else {
          [[RLMRealm defaultRealm] transactionWithBlock:^{
            DLLibrary *document = [DLLibrary objectForPrimaryKey:documentId];
            document.isCached = NO;
            document.bytesWritten = 0;
          }];
        }
```

Instead it would be nice if all I had to do was:
``` obj-c
        [[RLMRealm defaultRealm] transactionWithBlock:^{
            DLLibrary *document = [DLLibrary objectForPrimaryKey:documentId];
            document.isCached = NO;
            document.bytesWritten = 0;
        }];
```

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 2.4.3

Xcode version: Version 8.2.1 (8C1002)

iOS/OSX version: 10

Dependency manager + version: ? cocoapods v1.1.1

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. I'll add this to our feature backlog and then discuss with our engineers whether we want to pursue this route.

**Comment by jpsim** [comment]
There's no such thing as a transaction "object" in Realm. Seems like what you'd like is for beginWriteTransaction and commitWriteTransaction to essentially act as ref-count operations, so that a transaction would only be committed when the last pair of begin/commit was closed up.

We're already tracking this in #2502, calling the feature "nested transactions".

Without nested transactions, calling `cancelWriteTransaction` from your example would have surprising effects.

**Comment by jpsim** [comment]
I'm closing this as a duplicate, but please reopen if you think I've misunderstood.
