### ISSUE TITLE
Crash: When I want to store a array of RLMObejct

### ISSUE THREAD

**Issue by YioMidd** [realm/realm-cocoa#4708]
First, show the code following...
MCSMyFriendItem: a custom data model, inherit NSObject
MCSFriend: a RLMObject
``` Objective-c
NSMutableArray *entityArray = [NSMutableArray array];
    [friendItems enumerateObjectsUsingBlock:^(MCSMyFriendItem  *_Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        MCSFriend *friend = [obj entity]; // convert to MCSFriend
        [entityArray addObject:friend];
    }];
    [MCSDataBase writeTransaction:^{
        [MCSFriend createOrUpdateInDefaultRealmWithValue:entityArray];
    } result:^(NSError *error) {
        if (error) {
            MCSLog(@"writeTransctionError: %@", error.localizedDescription);
        }
    }];
```

and then, the crash log:
```Objective-c
-[RLMUnmanaged_MCSFriend longLongValue]: unrecognized selector sent to instance 0x7fa165295200
```
should use RLMArray for instead?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. 

Are you trying to add all the `MCSFriend` objects in your `entityArray` into the Realm? If you are trying to do that you should not use `createOrUpdateInRealmWithValue:`. Instead, use the `addObjects:` method on `RLMRealm`.

The `createOrUpdateInRealmWithValue:` method is for creating a _single_ object, and the value you pass in is used to set the properties on that object. You would use if it you wanted to add a single `MCSFriend` to your Realm, and to set the properties on that Realm using a `NSDictionary` or other such object.

Please try using `addObjects:` and see if that solves your problem.

**Comment by YioMidd** [comment]
@austinzheng Thanks! It works.  But that also a another problem, I must delete all objects in realm before I writing into realm again... if not, get crash 
```objective-c
*** Terminating app due to uncaught exception 'RLMException', reason: 'Can't create object with existing primary key value '4421875'.'
```
Whether affect the performance?

**Comment by austinzheng** [comment]
If your models have primary keys you may want to use `RLMRealm`'s `addOrUpdateObjectsFromArray:` method instead. For each object in your array, if an object with the same primary key already exists it'll just update the value. Otherwise it'll add the object.

**Comment by YioMidd** [comment]
3Q!! work correctly.

**Comment by YioMidd** [comment]
@austinzheng Hi, austinzheng! I have another question ask for you. Is there a limit that using the ``createInDefaultRealmWithValue``to update the stored data under the condition of storing data via  ``addOrUpdateObjectsFromArray``? Because it crashed when I do that.

**Comment by YioMidd** [comment]
The crash log like this:
```
libc++abi.dylib: terminating with uncaught exception of type realm::LogicError: Data type mismatch
```
The value is a dictionary as @{NSString : NSString}, and then the property I want to update which also is a ``NSString`` type.
