### ISSUE TITLE
Memory leak with Realm sorting ?

### ISSUE THREAD

**Issue by denisenkoaj** [realm/realm-cocoa#4709]
## Goals
What do you want to achieve?
I create app that uses CallKitDirectory Extension (for blocking and identification numbers)
Extension can get numbers from realm database placed in app container. Numbers must be in ascending order. I want to get numbers from realm with sorting

## Expected Results
realm.Objects(..)sorted -  should take same memory size as without sorted

## Actual Results

When i sort realm results, i have a memory leak (not leak, it's rather a jump of memory using), and extension is closed. Because CallKit have memory limit (in iOS 10.2 it's about 13 mb) and my base has more than 1 000 000 entries. (extension limit is 2 millions)
## Steps to Reproduce

What are steps we can follow to reproduce this issue?
## Code Sample

That's function that work ok: (but we have extension error when reach number that less than current , i.e. entriesOutOfOrder error)

`let phones =  realm.objects(PhoneExtModel.self).filter(NSPredicate(format: "isBlocked == %@ AND groupId == %d", NSNumber(booleanLiteral: isBlocked), (group.id)))
`

That's create memory 'jump' and shut down extension
`let phones =  realm.objects(PhoneExtModel.self).filter(NSPredicate(format: "isBlocked == %@ AND groupId == %d", NSNumber(booleanLiteral: isBlocked), (group.id))).sorted(byProperty: "number", ascending: true)`

I want to use second functions because it takes me ascending order of numbers.

Shutting down of extension have place not when i create 'phones' - it is when i called next function:

```
for i in 0 ..< phones.count {
                    autoreleasepool{
                        self.defaults?.set("addIdentificationPhoneNumbers : \(phones[i].value(forKey: "number")!)", forKey: "currentNumber")
                        context.addIdentificationEntry(withNextSequentialPhoneNumber: (phones[i].value(forKey: "number") as! Int64), label: (phones[i].value(forKey: "label") as! String))
                    }
                }

```
To be precise - when call `phones[i].value `

No matter if i call by key-value or like phones[i].number , difference just in declaring 'phones'

If test these declarations with base about 100-200k entries - the behavior is the same, but memory uses less and extension is not shut down.

## Version of Realm and Tooling
Realm version: 2.4.3

Xcode version: Version 8.2 (8C38)

iOS/OSX version: 10.2.1

Dependency manager + version: pod 1.1.1

**Comment by tgoyne** [comment]
Sorting data inherently requires scratch space proportional to the number of items being sorted. Currently we require 16 bytes per row being sorted (for 64-bit; 8 bytes for 32-bit), which naturally won't fit in 13 MB if you have a million objects.

If you have just a single sort order, you could avoid the memory hit by doing the sorting in the main app, and then storing the sorted data as a `List` which you would then query rather than doing the sorting on demand. An unsorted Results needs only 1-4 bytes per matching object.

**Comment by denisenkoaj** [comment]
Hello @tgoyne  ! Thank you for your answer!
Could you help me, how to save sorted `List` in main app for querying it from extension ?  
As i understand - i should create new class inherited from `Object`, create 1 variable of `List` type , and put in this variables sorted `Results` and then save in realm it ?

**Comment by austinzheng** [comment]
> i should create new class inherited from Object, create 1 variable of List type , and put in this variables sorted Results and then save in realm it ?

Yes, that is correct. Create an `Object` that just wraps a single `List`, and add the items in the sorted `Results` to that `List`.

**Comment by denisenkoaj** [comment]
@austinzheng Thank you! Everything is work great!
