### ISSUE TITLE
Realm crashes when using with AsyncDisplayKit

### ISSUE THREAD

**Issue by tungvoduc** [realm/realm-cocoa#4710]
I am not sure where to ask so I put this question in AsyncDisplayKit issue and here as well.
I recently integrated Realm to my existing project and encountered a lot of crashes. All of them are  **libc++abi.dylib: terminating with uncaught exception of type realm::IncorrectThreadException: Realm accessed from incorrect thread.**.
I make sure that all of Realm objects' creation, access happen in main thread. And it looks like the crashes happen only when the attributed string contains emojis or special characters. Any idea what could be wrong?
![crash](https://cloud.githubusercontent.com/assets/6437873/23485785/9e11ce78-fee5-11e6-852f-f0e251a0dd9e.png)

**Comment by arunlj561** [comment]
I am also looking for the same issue. Please can anyone help, Can we use Realm With AsyncDisplayKit or not ?
<img width="1280" alt="screen shot 2017-03-02 at 6 17 15 pm" src="https://cloud.githubusercontent.com/assets/13132856/23507787/a4e2801e-ff74-11e6-8d9c-7b01fc87087f.png">

**Comment by arunlj561** [comment]
@tungvoduc - To avoid this, you can use ThreadSafeReference https://realm.io/news/obj-c-swift-2-2-thread-safe-reference-sort-properties-relationships/ it can be passed across the threads. Follow this I was also facing the same issue, got the answer on Realm Slack Channel.

**Comment by jpsim** [comment]
Thread-safe references are definitely the answer to this. Closing.
