### ISSUE TITLE
Need a new build for Swift 3.1

### ISSUE THREAD

**Issue by account-archived-270316** [realm/realm-cocoa#4711]
It appears the latest build in `realm-swift-2.4.3` works as far as `swift-3.0.2`.

For Xcode 8.3 beta 3 we would need a build for `swift-3.1` or else we would run into `module compiled with Swift 3.0.2 cannot be imported to Swift-3.1` error

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. We don't guarantee any support for Xcode betas with our pre-built versions. You are welcome to follow the instructions [in our README](https://github.com/realm/realm-cocoa#building-realm) to build from source.

**Comment by account-archived-270316** [comment]
@austinzheng I see. Thank you

**Comment by nogginme** [comment]
the instructions don't work

**Comment by armandzwan** [comment]
3.1 is out now!

**Comment by danieldelouya** [comment]
Just updated to 3.1, and i get the error: Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1
