### ISSUE TITLE
Fabric crash logs realm descriptor deattach

### ISSUE THREAD

**Issue by hovox** [realm/realm-cocoa#4712]
We are receiving crashes from Fabric, here is the link to the crash:

http://crashes.to/s/03114cd32b8

Realm version: 1.1.0

Xcode version: 8.2.1

iOS/OSX version: You can find from the link above

Dependency manager + version: Cocoapods 1.1.1

Please let me know if you want more info about this crash, we couldn't reproduce this, but in fabric we receiving a lot of this.

Thanks in advance

**Comment by austinzheng** [comment]
Thanks for bringing this to our attention. Any additional information you can provide would be much appreciated; we've taken a look at the Fabric crash report but unfortunately there's not enough there for us to move forward with.

**Comment by jpsim** [comment]
I'm sorry to see you're seeing so many crashes @hovox. We'd love to resolve this quickly for you but need to be able to reproduce ourselves first.

**Comment by hovox** [comment]
[
![untitled](https://cloud.githubusercontent.com/assets/1732834/23740400/d36764c0-04bc-11e7-9702-7cfc3109f3ea.jpeg)
](url)

here is a detailed page log, I don't know how crashlytics grouping crashes, but it's different then the main log.

And the message is:
`CRASH_INFO_ENTRY_1
*** error for object 0x103aa92e8: pointer being freed was not allocated
CRASH_INFO_ENTRY_0
abort() called`

**Comment by hovox** [comment]
Sorry, it's stacktrace from the different thread then crashing one

**Comment by hovox** [comment]
Also in almost all cases ram is almost full
