### ISSUE TITLE
Realm addObject stop execution

### ISSUE THREAD

**Issue by elabi3** [realm/realm-cocoa#4713]
I had an app that used Realm to save information about a notification in a Realm instance stored inside an App Group. Notification Extension save that notification inside the database and after that the information was read from main target.

This code worked fine but after a month i recompile the same code (discarting changes in my git repository) and stop works, I already review:

- Certificates, app id, app groups, provisioning profiles, entitlement files

- Save a .txt file from extension in app group container and read it from main target and thats works fine

-  Explore files in container directory and .realm, .lock, etc files exist

- Remove every call to database and only use addObject method from extension 

- Clean project, remove derived data

- Uninstall and install in every device i've tested that used to works a month ago

- Update Realm version to the last one 

- Test addObjectOrUpdate method and not works 

## Goals

-  Solve the problem 

- Debug Realm method addObject to know what's happening 

## Expected Results

I expected that the addObject opperations works fine

## Actual Results

addObject opperation **finish** during execution and commiWriteTransaction **never executes**

## Code Sample

#define GROUP_ID @"group.com.MyGroup"
#define REALM_FILE_NAME @"Library/Caches/Notifications.realm"

Method 1

    // Configuration
    NSURL *containerURL = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:GROUP_ID];
    NSURL *realmURL = [containerURL URLByAppendingPathComponent:REALM_FILE_NAME];
    
    RLMRealmConfiguration *configuration = [RLMRealmConfiguration defaultConfiguration];
    configuration.fileURL = realmURL;
    
    return [RLMRealm realmWithConfiguration:configuration error:nil];

Method insertion

    RLMRealm *realm = [RealmInterface getRealmInstance];
    
    NotificationObject * notificationRealm = [[NotificationObject alloc] initWithNotification:notification];
    
    [realm beginWriteTransaction];
    [realm addObject:notificationRealm]; // This line stop execution on debug mode but app not crash
    [realm commitWriteTransaction]; // This line never execute!

## Version of Realm and Tooling

Realm version: 2.4.3

Xcode version: 8.2.1

iOS/OSX version: 
iPad Air 2
iPhone 7 Plus 10.2
iPhone 5C 10.2.1

El Capitan/Sierra (both, tested on iMac and Macbook Pro) 

Dependency manager + version: none, framework was include as static library from the zip downloaded in the official Realm site

Thank you for your time,

**Comment by austinzheng** [comment]
Thanks for getting in touch with us, and sorry you're having this problem. Can you build a demonstration project we can run ourselves to see this bug, and send it to help@realm.io?

**Comment by elabi3** [comment]
Thank you for your response, I've been working on this without any result and it is not possible to me develop an example project at this moment.

Sorry, I've decided to replace realm, i am going to use ios serialization with encoders and decoders.

Thank you for your time.
