### ISSUE TITLE
Realm file gets randomly deleted when observing changeset

### ISSUE THREAD

**Issue by freak4pc** [realm/realm-cocoa#4714]
## Goals

I'm a bit of panicking over this since it's a production-level issue we're dealing with at the moment. 

We're using RxRealm that wraps Realm object notifications to perform some change observing for object. I noticed that after creating objects, they randomly "disappears", and then noticed that whenever this Observable is being used, not just an object or two are gone, but actually my entire Realm file is randomly being deleted (or is never there to begin with?), and not just the Realm file but also the auxiliary files. 

Trying to create a new Realm object doesn't seem to create a fresh file, as well, at this point.

Discussing with @icanzilb (maintainer of RxRealm), it seems RxRealm is only a wrapper around the Realm notifications so this seems like a Realm issue and not a RxRealm issue.

**Important:** This seems to only happen the first time ever the app runs (when rebooting the app it will create a fresh realm file and continue)

I would truly appreciate your help as I'm not sure anymore what's going on and this is causing serious havoc. 

The observable code in question:
![image](https://cloud.githubusercontent.com/assets/605076/23587893/09609372-0183-11e7-92a0-ac6f38b37f45.png)

## Expected Results

The Realm file(s) should be consistently available but seems to get destroyed randomly by something more lower-level, or even not being created to begin with.

## Actual Results

When using the following code to check for the existence of the files:

```swift
let urls = [
    realmURL,
    realmURL.appendingPathExtension("lock"),
    realmURL.appendingPathExtension("note"),
    realmURL.appendingPathExtension("management")
]

for url in urls {
    print("(pre) \(url.lastPathComponent): \(FileManager.default.fileExists(atPath: url.path))")
}

let _ = THRealms.main() // This is just doing a fresh Realm(configuration: _) all

for url in urls {
    print("(post) \(url.lastPathComponent): \(FileManager.default.fileExists(atPath: url.path))")
}
```

If the observing code is there, it outputs: 
```
(pre) main.realm: false
(pre) main.realm.lock: false
(pre) main.realm.note: false
(pre) main.realm.management: false
(post) main.realm: false
(post) main.realm.lock: false
(post) main.realm.note: false
(post) main.realm.management: false
```

If the observing code is replaced with `ongoingOrder = .empty()` (e.g. not there), it outputs:

```
(pre) main.realm: true
(pre) main.realm.lock: true
(pre) main.realm.note: true
(pre) main.realm.management: true
(post) main.realm: true
(post) main.realm.lock: true
(post) main.realm.note: true
(post) main.realm.management: true
```

That is the only difference within the entire app for that situation.

## Steps to Reproduce

1. Delete app completely from simulator 
2. Open app that tries to create a realm / create some objects 
3. Have the observing code in the app (for me its in a Singleton).
4. At some points look for the existence of the realm file or try to fetch objects from the realm, the file doesn't exist and the objects aren't returned

If 3 isn't at hand (no observing code), the Realm file exists as described in the "Actual Results" section.

## Code Sample

Described above, also providing the code that creates the Realm.
As you can see it's just storing it in the Application Support folder, making sure it exists before setting it.

![image](https://cloud.githubusercontent.com/assets/605076/23587982/007b2b68-0184-11e7-867b-1ed217c3aebb.png)

## Version of Realm and Tooling

Xcode 8.2.1
RealmSwift 2.4.2
RxRealm 0.5.1 (which seems to depend on RealmSwift 2.2)
iOS Simulator latest
CocoaPods 1.2.0

**Comment by bdash** [comment]
Hi @freak4pc, that's very strange behavior you're seeing, and I can understand why you'd be worried about it. It sounds like it's reproducible though which should hopefully make it easy to track down and understand. If you can build an IPA of your app and share it with us at help@realm.io, I'm happy to take a look.

**Comment by freak4pc** [comment]
Thanks @bdash for your prompt response
Highly appreciated

I'm gonna try creating a blank reproducible project to send to you and if that won't work I'll send an IPA or our app.

Thanks !

**Comment by freak4pc** [comment]
@bdash Was able to more accurately pinpoint the problem. This seems to be related to a situation where, if the Realm file was deleted after creation, consecutive `try! Realm(configuration:_)` won't create a new Realm file for some reason. 

I made a reproduction project, here it is: 
[RealmNukeExample.zip](https://github.com/realm/realm-cocoa/files/819781/RealmNukeExample.zip)

A good way I could "work around" this for now is only destroy the realm if it's not empty, but I would still love to understand what's causing this.

Flow of things: 
1. AppDelegate initializes THOrderManager singleton that creates the first empty realm (file exists) - `AppDelegate.swift:L16 , OrderManager.swift:L13`
2. Quite immediately after (on viewWillAppear of first view controller), the realm file is deleted by a method that is supposed to make sure "everything in the app is clean" before initial onboarding - `ViewController.swift:L24`
3. Consecutive calls to create a fresh realm past that point don't help and the realm isn't actually being created. - `Realms.swift - Lines 19-29` 

If past that point, the next call won't have the delete (which my app won't for the second time), the realm will be created successfully after a restart of the app. 

Again, I highly appreciate your help!

**Comment by bdash** [comment]
Based on your description, and a quick look at the code, it looks like you're deleting the Realm file while it's open. When combined with the fact that open Realm instances are cached, this results in your attempt to create a "fresh Realm" actually returning the same Realm instance whose files on disk you've just deleted. The end result is that any data you store into that Realm instance will disappear as soon as the Realm instance is closed (file data remains on disk so long as there is at least one name for the inode the file system, or at least one open file descriptor to it).

To safely delete a Realm file you need to ensure that there are no open "accessors" to the Realm (`Realm` instances, and any live objects retrieved from it such as `List`, `Results`, and such). The easiest way to ensure this is to only delete the Realm file during app launch, before you've opened the Realm. If you need to delete it at any other point of your app's lifecycle you'll need to ensure that all of the accessors mentioned above have been invalidated or deallocated. For a log-in / log-out type workflow it may be easier to store the Realms for each log-in session at a different path, and to remove any inactive Realms during next app launch.

**Comment by freak4pc** [comment]
@bdash Thanks again. Is there anything problematic with just moving to an approach of just removing the objects of the realm instead of deleting the realm itself ? 

Is there any way to actual understand which objects are "retained" in the Realm or perhaps a more verbose way to clear the cache in that situation? I assumed a `try! Realm()` always creates a new Realm file if one doesn't exist. Since realms can be created in many threads where the data needs to be accessed in, it might be tricky to actually make sure everything is closed in that specific moment.

Also, in the example I posted, There is no data inserted into the Realm, it is just created and then deleted so no references should be held from any of the objects, so just the empty Realm is cached? Perhaps it could be more verbose in creating a new realm and clearing the cache if the file doesn't exist at that path anymore? (clearly aware there is probably more to this I'm not considering)

I currently changed my `destroy` to a `THRealms.reset` method just clearing the objects. Is there anything problematic with this approach? 

```
/// Reset realm (remove all objects)
public static func reset() {
    THLogger.Warning("Resetting Realm Database...")

    let realm = THRealms.main()
    do {
        try realm.write {
            realm.deleteAll()
        }
    } catch let err {
        THLogger.Failure("Can't delete all objects from Realm: \(err)")
    }
}
```

Many thanks,
Shai.

**Comment by bdash** [comment]
The only downside to deleting all objects rather than deleting the Realm files is that deleting all objects won't currently cause the Realm file to shrink. This is likely only a concern if the Realm file was large to begin with. The space that was occupied by the now-deleted objects will be used as new objects are inserted.

Instruments' memory allocation instrument can be used to determine whether there are any references to a given Realm file currently open. You're quite right that it can be difficult to ensure that all references are dropped, hence the suggestion to prefer deleting Realms only at app launch.

> Also, in the example I posted, There is no data inserted into the Realm, it is just created and then deleted so no references should be held from any of the objects, so just the empty Realm is cached? 

In the specific case of your example code, `OrderManager.init()` opens the Realm and captures a `Results` originating from that Realm. That is what keeps the Realm open.

**Comment by freak4pc** [comment]
Thanks again @bdash , I'll close it for now. My data set is relatively small so I'm fine with that cost for the added stability. 

Maybe it'll be good to consider refreshing that cache if the underlying file doesn't exist anymore, not a huge deal but just a thought :) 

Again thanks so much for the help in resolving this

Shai
