### ISSUE TITLE
Typo in Sync.swift

### ISSUE THREAD

**Issue by dakeshi** [realm/realm-cocoa#4716]
I think that it should be `SyncUser` instead of `User` in UserCompletionBlock comments

```
/**
 A closure type for a closure which is used by certain APIs to asynchronously return a `User` object to the application.

 - see: `RLMUserCompletionBlock`
 */
public typealias UserCompletionBlock = RLMUserCompletionBlock
```

**Comment by stel** [comment]
Thanks for reporting this, @dakeshi!

**Comment by dakeshi** [comment]
Thanks. @stel 
But API reference is still not changed. Does It need to fix manually?
https://realm.io/docs/swift/latest/api/Typealiases.html#/s:10RealmSwift19UserCompletionBlock

**Comment by jpsim** [comment]
@dakeshi those are the docs for the latest release, 2.4.3, so the next release will include this change.

**Comment by dakeshi** [comment]
@jpsim It is the bad news for developers who prefer to read API reference through web pages, even though they can find out the correct info from source code.

**Comment by bdash** [comment]
The documentation on the website will be automatically updated when we next make a release, hopefully in the next few days.
