### ISSUE TITLE
use vendered_framework with Rrealm.framework

### ISSUE THREAD

**Issue by pkjijie** [realm/realm-cocoa#4720]
## Goals

What do you want to achieve?

I want to use Realm.framework with cocoapods, and I create a private pod lib named TNRealm,   made a podspec as bellow:

s.library = 'c++','z'
s.dependency 'FMDB'
s.ios.preserve_paths      = 'TNRealm/Realm.framework'
s.ios.vendored_frameworks  = 'TNRealm/Realm.framework'

## Expected Results

when do the pod lint, error occurs:

TNRealm/TNRealm.framework/Headers/Realm.h:21:9: fatal error: 'Realm/RLMArray.h' file not found

but if I create a new framework and dependend on it , all works fine

What did you expected to happen?

pod lint should be successful

## Actual Results

error occured

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

1. put the Realm.framework to a folder with named 'TNRealm'
2. put two files named LICENSE and README.md to the folder 'TNRealm'
3. edit the TNRealm.podspec file with bellow content:

Pod::Spec.new do |s|

  s.name         = "TNRealm"
  s.version      = "0.0.1"
  s.summary      = "For toon modules' base functions."
  s.description  = 'For toon modules base functions and additions'

  s.homepage     = "http://172.28.6.24:8080/#/admin/projects/TNLogSDK"
  s.license          = 'MIT'
  s.author           = { '144976' => 'luhongdeng@syswin.com' }
  s.source           = {
        :git => 'http://172.28.6.24:8080/TNLogSDK',
        :tag => "0.0.1" }

  s.ios.deployment_target = '7.0'
  s.source_files = 'TNRealm/**/*'
#s.public_header_files = 'LogSource/**/*.h'

  s.frameworks = 'UIKit', 'Foundation', 'CoreMedia', 'QuartzCore', 'CoreTelephony'

s.library = 'c++','z'
s.dependency 'FMDB'
s.ios.preserve_paths      = 'TNRealm/Realm.framework'
s.ios.vendored_frameworks  = 'TNRealm/Realm.framework'
end

do pod lint: pod lib lint --allow-warnings  --verbose

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?
2.4.3
Xcode version: ?
8.2.1
iOS/OSX version: ?
8.0
Dependency manager + version: ?

**Comment by jpsim** [comment]
Why not specify the Realm pod as a dependency instead, just like you're doing with FMDB? `s.dependency 'Realm'`

**Comment by pkjijie** [comment]
because use dependency will hang up for a long time when do pod update and always failed to load, so I want to use framework and make it a private pod lib, so other people can use dependency and update quickly

**Comment by jpsim** [comment]
Ok, well if you're intent on doing this, looks like you have some complexity to deal with, since CocoaPods expects `Realm.h` to be copied into `TNRealm/TNRealm.framework/Headers/Realm.h`. You can do this with post-installation scripts, but it won't be straightforward.

**Comment by pkjijie** [comment]
I use the Realm.framework from https://github.com/realm/realm-cocoa/releases, and just set the 's.vendered_framework = Realm.framework' in my private pod, the the Realm.h file is right there

**Comment by jpsim** [comment]
The error message you shared indicates that CocoaPods expects Realm's headers to be elsewhere:

> TNRealm/TNRealm.framework/Headers/Realm.h:21:9: fatal error: 'Realm/RLMArray.h' file not found

Why is that?

**Comment by pkjijie** [comment]
to simplify my question:  may I use Realm.framework in a podspec and how ?

**Comment by jpsim** [comment]
Yes you may use a binary framework in your podspec. "How" is just like any other dynamic framework. If you're looking for an example, this tutorial describing how to make binary podspecs could be a good start: http://markspanbroek.github.io/2016/04/14/binary-cocoapods.html
