### ISSUE TITLE
How to create a realm in custom file directory?

### ISSUE THREAD

**Issue by YioMidd** [realm/realm-cocoa#4721]
Imitating the official sample code in doc, I configurate following this:
``` objective-c
+ (void)setDefaultRealmForUser:(NSString *)userName userId:(NSString *)userId {
    
    RLMRealmConfiguration *defaultconfig = [RLMRealmConfiguration defaultConfiguration];
    defaultconfig.fileURL = [[[[defaultconfig.fileURL URLByDeletingLastPathComponent] URLByAppendingPathComponent:[userName stringByAppendingString:userId] isDirectory:YES] URLByAppendingPathComponent:userName] URLByAppendingPathExtension:@"realm"];
    [RLMRealmConfiguration setDefaultConfiguration:defaultconfig];
}
```
it works fine, but when I use ``[RLMRealm defaultRealm]`` or ``[RLMRealm realmWithConfiguration:realmConfigurarion error:nil]`` to get ``RLMRealm`` instance, crash and log
```
Terminating app due to uncaught exception 'RLMException', 
reason: '/Users/kiben/Library/Developer/CoreSimulator/Devices/1C00477C-EEE5-4B2B-A61C-9CD5EEEE3D73/data/Containers/Data/Application/130EC6F1-A3D7-4B30-B272-90C8D009C7DC/Documents/Jimmy7518338/Jimmy.realm.management: 
Unable to open a realm at path '/Users/kiben/Library/Developer/CoreSimulator/Devices/1C00477C-EEE5-4B2B-A61C-9CD5EEEE3D73/data/Containers/Data/Application/130EC6F1-A3D7-4B30-B272-90C8D009C7DC/Documents/Jimmy7518338/Jimmy.realm.management': make_dir() failed: No such file or directory.'

```

**Comment by bdash** [comment]
The directory in which you're creating the Realm file must already exist. Your code does not appear to do anything to guarantee this.

**Comment by YioMidd** [comment]
So.... I need to manually create a realm file before configuration? And then the realm file just only appear at /Documents/xxxx.realm ?

**Comment by bdash** [comment]
You must create the _directory_ that you wish to contain the Realm file. Realm will create the file itself, but will not create any intermediate directories.

From your exception message, the Realm you're trying to open is at `…/Documents/Jimmy7518338/Jimmy.realm`. You need to ensure that the directory `…/Documents/Jimmy7518338` exists before you can open that Realm.

**Comment by YioMidd** [comment]
Ohhhh.... The directory.... Thanks, it works.
