### ISSUE TITLE
Deletion operation should be executed in main thread?  

### ISSUE THREAD

**Issue by canny09** [realm/realm-cocoa#4725]
```objective-c
+ (void)deleteFriendItems:(NSArray *)friendItems {

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSMutableArray *deletedItems = [NSMutableArray array];
        [friendItems enumerateObjectsUsingBlock:^(MCSMyFriendItem  *_Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            MCSFriend *friend = [MCSFriend objectForPrimaryKey:obj.userId];
            [deletedItems addObject:friend];
        }];
        
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        [realm deleteObjects:deletedItems];
        [realm commitWriteTransaction];
    });
}
```
Deleting some data via the above code, without any error or exception, but the data which I want to delete still in realm file.(through by Realm Browser)

And then, remove the ``dispatch_async`` and run again, delete successful...

Confused....

**Comment by jpsim** [comment]
Hi @canny09, the code and explanations you shared is not enough to understand what is happening.

What I suspect is happening is that different threads are at different versions of the transaction history. This is a key behavior of Realm's thread safety, consistency and isolation of transactions. See our [Threading](https://realm.io/docs/objc/latest/#threading) docs for details.

What you could do to ensure your background thread sees the latest version of the Realm would be to call [`-[RLMRealm refresh]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)refresh) at the beginning of the GCD block:

```objc
+ (void)deleteFriendItems:(NSArray *)friendItems {

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [[RLMRealm defaultRealm] refresh];
        NSMutableArray *deletedItems = [NSMutableArray array];
        [friendItems enumerateObjectsUsingBlock:^(MCSMyFriendItem  *_Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            MCSFriend *friend = [MCSFriend objectForPrimaryKey:obj.userId];
            [deletedItems addObject:friend];
        }];
        
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        [realm deleteObjects:deletedItems];
        [realm commitWriteTransaction];
    });
}
```

Even then, depending on the rest of your code, there could be a race condition where between the refresh and the write transaction, other changes are made, so you could leverage Realm's single-writer pattern to do this:

```objc
+ (void)deleteFriendItems:(NSArray *)friendItems {

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        
        NSMutableArray *deletedItems = [NSMutableArray array];
        [friendItems enumerateObjectsUsingBlock:^(MCSMyFriendItem  *_Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            MCSFriend *friend = [MCSFriend objectForPrimaryKey:obj.userId];
            [deletedItems addObject:friend];
        }];
        
        [realm deleteObjects:deletedItems];
        [realm commitWriteTransaction];
    });
}
```

**Comment by canny09** [comment]
@jpsim Thanks for reply. But I modify my code like which you suggest above, which not work successfully, the data still been.

**Comment by jpsim** [comment]
@canny09 alright, how do you suggest we help you further? Could you share code with us that exhibits the same behavior you're seeing so we can investigate why that's happening?

**Comment by canny09** [comment]
@jpsim Thank you! I have checked the cause of the problem, that is my negligence. Orz... The ``friendItems ``parameter has been clean up all objects in main thread before converting to the ``MCSFriend ``.

**Comment by stel** [comment]
@canny09 does this mean you resolved your problem? Can we close this issue?
