### ISSUE TITLE
Xcode plugin in Swift/Objc docs

### ISSUE THREAD

**Issue by dakeshi** [realm/realm-cocoa#4730]
Hi. I find out two issues in the Xcode plugin section in the latest Swift docs.

In the documentation, it seems that we can install RealmPlugin through Alcatraz.
> The easiest way to install the Realm Xcode plugin is through Alcatraz under the name “RealmPlugin”. 

But, as it mentioned in #4357, we can not use Alcatraz anymore in Xcode 8 later without unsigned or resigned Xcode.  (refer to https://github.com/alcatraz/Alcatraz/issues/475, https://github.com/inket/update_xcode_plugins, https://github.com/XVimProject/XVim/blob/3167408ade82cfef87acc704822da61af69688f8/INSTALL_Xcode8.md). 
I think that removing contents about Alcatraz will be helpful to avoid confusion.
Are there some reasons to remain this description for Alcatraz? 

Another issue is the README.md for RealmPlugin which downloads from the release.zip link in docs.
> 3. A menu item in Xcode's 'File' menu to quickly launch the Realm Browser.

I install RealmPlugin with RealmPlugin.xcodeproj but I can not see Realm Browser menu in File menu. Is it normal? or wrong info in README.md?

**Comment by jpsim** [comment]
Thanks for asking these questions, @dakeshi! We should certainly update our docs to reflect that Alcatraz requires resigning Xcode.

As for your second question, the "Open Realm..." menu item is only added if the Realm Browser is installed on your Mac. https://github.com/realm/realm-cocoa/blob/v2.4.3/plugin/RealmPlugin/RLMPRealmPlugin.m#L87-L108

**Comment by dakeshi** [comment]
Thanks for your response @jpsim 

>We should certainly update our docs to reflect that Alcatraz requires resigning Xcode.

I’m not sure that we need to mention how to resign or unsign Xcode 8 to use Alcatraz. 
Without Alcatraz support, we can still install RealmPlugin in Xcode 8(with release.zip)
Actually, it is not the RealmPlugin issue but 3rd party plugin issue.
Using Alcatraz is more convenient but it is not the mandatory to use RealmPlugin, I think. 
If some users want to install RealmPlugin using Alcatraz tools, 
they could get the solution from the Alcatraz repo.

> As for your second question, the "Open Realm..." menu item is only added if the Realm Browser is installed on your Mac. https://github.com/realm/realm-cocoa/blob/v2.4.3/plugin/RealmPlugin/RLMPRealmPlugin.m#L87-L108

Even though I successfully installed Realm Browser from Mac Store, I have not found out “Open Realm…”  menu under File menu in the Xcode 8.2.1.  I checked the Browser path with source you mentioned

> let urlString = NSWorkspace.shared().fullPath(forApplication: "Realm Browser")

urlString is ”/Applications/Realm Browser.app". How to solve this issue?

**Comment by jpsim** [comment]
> Without Alcatraz support and resigning/unsigning Xcode, we can successfully install RealmPlugin in Xcode 8(with release.zip)

Seems like this is the crux of your problem, since the "Open Realm..." menu item is the only part of the "plugin" that's actually a proper Xcode plugin. The other things it installs (file templates and lldb plugin) don't require resigning Xcode, and from what I can tell from your comments those appear to have successfully installed.

So my most likely guess at this point is that the actual Xcode plugin is _silently_ failing to install.

**Comment by dakeshi** [comment]
Thanks for your reply. @jpsim 
Yes. I'm get successfully installed file template, lldb plugin but not file menu.
So, we could say the plugin is not perfectly installed.  

I hope that docs will be updated as soon as possible to provide the correct info.

**Comment by jpsim** [comment]
Update the plugin readme to reflect this in #4763
