### ISSUE TITLE
Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)  (continued)

### ISSUE THREAD

**Issue by timbroder** [realm/realm-cocoa#4733]
## Goals

Understand this crash, why it happens, and how to work around it

Note: this feels like a continuation of #3122

## Expected Results

This Realm write to not crash

## Actual Results

This recently started happening in our Dev build and in the build we recently sent out to Testflight. During that time we upgraded Realm from 2.3 to 2.4.2 (I understand there is a newer version at the moment). Because of the nature of this, it is possible that this crash could happen in 2.3, I just don't have a record of it happening in crashlytics

Crash:

```
Fatal Exception: RLMException
0  CoreFoundation                 0x192bb51b8 __exceptionPreprocess
1  libobjc.A.dylib                0x1915ec55c objc_exception_throw
2  Realm                          0x10177bf40 -[RLMRealm beginWriteTransaction] (RLMRealm.mm:446)
3  RealmSwift                     0x101cae2e4 Realm.write(() throws -> ()) throws -> () (Realm.swift)
4  KidFund                        0x1000fc504 specialized BaseNetworkService.(refreshTokens(Bool) -> ()).(closure #1) (BaseNetworkService.swift:88)
5  KidFund                        0x1000f6024 BaseNetworkService.(refreshTokens(Bool) -> ()).(closure #1) (BaseNetworkService.swift)
6  KidFund                        0x1001b2064 thunk (GiftsViewController.swift)
7  KidFund                        0x1000ff684 specialized specialized specialized BaseNetworkService.(request(HTTPMethod, apiUrl : String, parameters : [String : Any]?, headers : [String : String]?, object : Object?, networkQueueKey : String?, tries : Int, successCallback : (JSON, Object?) -> ()?, failureCallback : (NSError, Object?) -> ()?) -> ()).(closure #3) (BaseNetworkService.swift)
8  KidFund                        0x1000f6750 specialized BaseNetworkService.(request(HTTPMethod, apiUrl : String, parameters : [String : Any]?, headers : [String : String]?, object : Object?, networkQueueKey : String?, tries : Int, successCallback : (JSON, Object?) -> ()?, failureCallback : (NSError, Object?) -> ()?) -> ()).(closure #3) (BaseNetworkService.swift)
9  KidFund                        0x1000fd41c _TPA__TTSf2n_n_n_n_n_i_n_n_n_n___TFFC7KidFund18BaseNetworkService7requestFTO9Alamofire10HTTPMethod6apiUrlSS10parametersGSqGVs10DictionarySSP___7headersGSqGS3_SSSS__6objectGSqC10RealmSwift6Object_15networkQueueKeyGSqSS_5triesSi15successCallbackGSqFTV10SwiftyJSON4JSONGSqS5___T__15failureCallbackGSqFTCSo7NSErrorGSqS5___T___T_U1_FGVS1_12DataResponseS7__T_ (BaseNetworkService.swift)
10 Alamofire_SwiftyJSON           0x10077f698 partial apply for thunk (Alamofire-SwiftyJSON.swift)
11 Alamofire                      0x100944d04 DataRequest.(response<A where ...> (queue : DispatchQueue?, responseSerializer : A, completionHandler : (DataResponse<A.SerializedObject>) -> ()) -> Self).(closure #1).(closure #1) (ResponseSerialization.swift:166)
12 libdispatch.dylib              0x191a3e1fc _dispatch_call_block_and_release
13 libdispatch.dylib              0x191a3e1bc _dispatch_client_callout
14 libdispatch.dylib              0x191a42d68 _dispatch_main_queue_callback_4CF
15 CoreFoundation                 0x192b62810 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
16 CoreFoundation                 0x192b603fc __CFRunLoopRun
17 CoreFoundation                 0x192a8e2b8 CFRunLoopRunSpecific
18 GraphicsServices               0x194542198 GSEventRunModal
19 UIKit                          0x198ad57fc -[UIApplication _run]
20 UIKit                          0x198ad0534 UIApplicationMain
21 KidFund                        0x1000c5bf4 main (AppDelegate.swift:21)
22 libdispatch.dylib              0x191a715b8 (Missing)
```

Screenshot from crashlytics if helpful:

![image](https://cloud.githubusercontent.com/assets/121503/23909053/14850884-08ac-11e7-92be-d68622ae3050.png)

## Steps to Reproduce

I have a success handler in an AlamoFire API request that does a realm write on the main thread. The callback happens to be a JWT token refresh so forcing the crash to happen is a little tricky.

It is possible but unlikely that other code is also writing to the main thread because if this call has been invoked, then all other API calls have been queued up for reprocessing. From what I've seen in the logs, the user hasn't also been interacting with the app in a way that would cause a conflicting write

## Code Sample

Extra code removed to keep the discussion simple. 

With this sample, here is what I'm unsure of:

1. Is this a valid crash/bug?
1. Should I just run this on a background thread and would that solve my problem?
1. If I check for if the realm is already isInWriteTransaction, can I tell where that got called from or what it's doing?
1. If I check for isInWriteTransaction, how can I wait for it to be done?
1. We recently changed an iteration & write (of about 30 items) from a setup where each iteration was creating a write transaction, to wrapping the whole iteration in a write transaction to be more in line with the way the docs explain to do things. Is it possible that this "long" write isn't closing in time or is still writing when this hits. Which would lead me back to a) breaking up that write again into smaller chunks, or #2 in this list

```swift
UserNetworkService().refreshJwtToken({
            response, _ in
            // Logging removed for simplicity

            let realm = KidRealm.realm()
            if let user = UserDataService.getCurrentUser(realm) {
                try! realm.write {
                    user.token = newToken
                } // crashing line
                // cleanup removed for simplicity
            } else {
                // logging and logout removed for simplicity
                return
            }

        
        }, failureCallback: {
            // removed for simplicity
```

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

/Applications/Xcode.app/Contents/Developer
Xcode 8.2.1
Build version 8C1002

/Users/timbroder/.rvm/gems/ruby-2.3.0/bin/pod
1.2.0
Realm (2.4.2)
RealmSwift (2.4.2)
RealmSwift (~> 2.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

carthage not found
(not in use here)

git: aliased to hub
git version 2.8.1
hub version 2.2.3
```

**Comment by istx25** [comment]
Hi @timbroder. Thanks for sharing all of this! I personally don't know what would be causing this issue but I wanted to let you know that we've seen the issue and that I'm going to assign this to one of our Cocoa engineers who will read through this and follow-up soon. Cheers!

**Comment by gordanyang** [comment]
i also have same problem.

```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000111d11d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011177321e objc_exception_throw + 48
	2   Realm                               0x0000000110a245b1 -[RLMRealm beginWriteTransaction] + 77
	3   RealmSwift                          0x0000000110866998 _TFC10RealmSwift5Realm5writefzFzT_T_T_ + 40
`````

**Comment by timbroder** [comment]
@gordanyang can you post sample code so we have more examples?

**Comment by Zeeker** [comment]
I think we are experiencing the same issue. I can not pinpoint it to a specific line of code but we only experienced the crashes when we performed multiple write operations at the start of the application.

Mainly our user updating logic which quickly performs three requests on startup and then writes the results of this requests into the user object, each in their own transaction lead to a repeated crash.

Splitting up the logic to perform the requests sequentially - and as such having a larger interval between the transactions - helped us avoid the crashes.

**Comment by timbroder** [comment]
@Zeeker did you notice a difference in transaction length? This seems to have cropped up when we're doing more in each transaction; EG 1 transaction looping over 20 object updates, vs 20 transactions

**Comment by TimOliver** [comment]
@Zeeker That's interesting! Could you please elaborate some more on what your app was doing at its startup? Were they on a background thread?

There shouldn't be a need to manually line up write transactions sequentially, so I'm wondering how these transactions are being handled.

**Comment by Zeeker** [comment]
@TimOliver I'm currently in the process of refactoring the app quite a bit and also touched the problematic code during that.

In the past the transactions were done in the main thread; after my refactoring everything is now done in a background thread. It seems that this has also solved the issue. For testing purposes I've moved the logic back into the main thread and indeed that led to a crash.

**Comment by TimOliver** [comment]
@Zeeker Okay no worries. I was curious as to what those three requests were and what order they may have been occurring in each time. Never mind.

---

In any case, it's good to know that moving the transactions to a background thread mitigated the immediate problem. But it would be excellent if anyone would be willing to post a sample app reproducing the issue in order for us to analyze the problem.

Would anyone be able to do that? It would help us out a lot. :)

**Comment by bdash** [comment]
#4815 is about the same exception and contains a standalone project that reproduces the problem . I'm not sure if it has the same cause as what people in this issue were reporting.

**Comment by TimOliver** [comment]
Hmm, if we're tracking the same exception in another issue, is it worth leaving this issue open still then?

**Comment by jpsim** [comment]
We should decide what to do with this. Does #4818 sufficiently cover the awkwardness brought up here?

**Comment by jpsim** [comment]
Will assume that's the case.
