### ISSUE TITLE
Authenticates to Object Server but fails to sync with error: HTTP: Failed to switch protocols (response status = 404)

### ISSUE THREAD

**Issue by einsteinx2** [realm/realm-cocoa#4735]
## Goals

I want to sync realms with the Realm Object Server

## Expected Results

I expect it to connect to the shared realm

## Actual Results

2017-03-14 15:49:25.205667 Balance[47764:2441965] Sync: Connection[1]: Session[1]: Starting session for '/Users/bbaron/Library/Containers/software.balanced.balancemac/Data/Library/Application Support/realm-object-server/14ab940fc23cd7b61daa1f92f47d0902/realms%3A%2F%2Fsync.balancemy.money%2F%7E%2Fprefs'
2017-03-14 15:49:25.205819 Balance[47764:2441965] Sync: Connection[1]: Resolving 'sync.balancemy.money:443'
2017-03-14 15:49:25.207596 Balance[47764:2441965] Sync: Connection[1]: Connecting to endpoint '159.203.84.96:443' (1/1)
2017-03-14 15:49:25.305577 Balance[47764:2441965] Sync: Connection[1]: Connected to endpoint '159.203.84.96:443' (from '192.168.2.117:55452')
2017-03-14 15:49:25.803748 Balance[47764:2441965] Sync: Connection[1]: HTTP: Failed to switch protocols (response status = 404)
2017-03-14 15:49:25.803877 Balance[47764:2441965] Sync: Connection[1]: Connection closed due to error

## Steps to Reproduce

Install Realm Object Server on a VM
Install Nginx and SSL reverse proxy port 443 traffic to localhost port 9080
Connect to the server using the RealmSwift SDK

## Code Sample

fileprivate func openRealm(url: URL) -> Realm? {
        if let user = SyncUser.current {
            let config = Realm.Configuration(syncConfiguration: SyncConfiguration(user: user, realmURL: url))
            do {
                let realm = try Realm(configuration: config)
                return realm
            } catch {
                log.severe("Failed to open realm for url: \(url)  error: \(error)")
            }
        }
        
  return nil
}

Note that the realm opens successfully and my catch block does not fire. The error seems internal to the Realm SDK.

## Version of Realm and Tooling

Realm version:

v2.4.3

Xcode version:

Xcode 8.2.1
Build version 8C1002

iOS/OSX version:

10.12.3

Dependency manager + version:

/usr/local/bin/carthage
0.18.1

**Comment by einsteinx2** [comment]
Note that I can't debug the problem further because setting logLevel to all is not working: https://github.com/realm/realm-cocoa/issues/4734

**Comment by einsteinx2** [comment]
I was able to successfully set the logLevel in the OS X Realm Browser app, so I could finally see what the problem was. Looks like I need to explicitly handle web socket proxying in my Nginx config. Working on fixing now and will post my solution and close this ticket when I have it solved.

**Comment by bdash** [comment]
I suspect this comment https://github.com/realm/realm-mobile-platform/issues/100#issuecomment-278996285 may have information that's relevant to what you're trying to do.

**Comment by einsteinx2** [comment]
@bdash Yep, ended up finding similar info here right before you commented: https://www.nginx.com/blog/websocket-nginx/

Seems to be getting me further now, but still won't connect. Getting messages about "Using already open Realm file" and then it closes the Realm file and I get this: "Sync: Connection[3]: Session[1]: Sending: UNBIND"

Still probably something up with my Nginx config, but at least I'm getting closer. Maybe I'm not forwarding all necessary headers or something.

For what it's worth I tried the exact location block from your link as well as what I had tried based on the info I found and am getting similar issues.

Anyway once I get it working I'll post my complete config.

**Comment by bdash** [comment]
If you continue to have problems I'd suggest filing an issue in the [realm-mobile-platform](https://github.com/realm/realm-mobile-platform) repository since it looks like a problem with your server-side configuration rather than with the Realm Swift SDK.

**Comment by einsteinx2** [comment]
Never mind, it's actually working. The problem was once I fixed it using the info by setting up websocket proxying (your link or mine works fine for that for anyone coming across this in the future), I forgot to connect using my actual app first, so of course the realm didn't exist yet when I connected using the browser d'oh.
