### ISSUE TITLE
Realm file is growing larger than a gig when it is only holding ~50mb

### ISSUE THREAD

**Issue by bruce-lumo** [realm/realm-cocoa#4736]
## Goals

Store user data on iOS ranging from a few k to a few hundred MB.

## Expected Results

Realm db grows in size relative to amount of data stored + unreclaimed space overhead

## Actual Results

See exceptions generated from 17 users. There is no way there are actually storing that much data. Also, how are multiple users hitting the exact same number of bytes?

     03/11 22:56:19.024 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1744830464 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1744830464 offset: 0, Error Code=9}
     03/08 22:31:25.407 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1744830464 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1744830464 offset: 0, Error Code=9}
     03/09 09:22:09.426 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1744830464 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1744830464 offset: 0, Error Code=9}

     03/09 20:04:23.569 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}
     03/09 21:50:19.254 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}
     03/09 20:40:01.597 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}
     03/09 22:55:33.892 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}
     03/14 07:23:50.626 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}
     03/11 15:56:05.498 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}
     03/11 17:19:14.941 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}
     03/14 07:23:50.626 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1476395008 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1476395008 offset: 0, Error Code=9}

     03/12 16:30:29.516 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1207959552 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1207959552 offset: 0, Error Code=9}

     03/12 23:19:18.476 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1610612736 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1610612736 offset: 0, Error Code=9}
     03/12 23:23:48.896 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1610612736 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1610612736 offset: 0, Error Code=9}
     03/12 23:27:21.660 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1610612736 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1610612736 offset: 0, Error Code=9}
     03/10 12:46:59.726 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1610612736 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1610612736 offset: 0, Error Code=9}

     03/13 15:45:18.168 (LLDatabaseManager:26) [E] Error creating Realm instance: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1073741824 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1073741824 offset: 0, Error Code=9}

I have a hunch that copying the db in place (compressing) would make this go away, but my current code in production only does this at night, and when there is 3x db size storage in overhead, so this is unlikely to happen.

## Steps to Reproduce

I do not have deterministic steps to reproduce, I've seen this in 17 out of thousands of users. I have not been able to dupe this in the lab.

## Code Sample

     do{
                 return try Realm()
             } catch {
                 DDLogError("Error creating Realm instance: \(error)")
                 return nil
             }

## Version of Realm and Tooling

Realm version: 2.4.2

Xcode version: 8.2

iOS/OSX version: iPhone 6s, iOS 10.0.2

Thanks for your help!

**Comment by Florelit** [comment]
I have the similar issue with realm 2.4.3

here is a part of a log
`Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1207959552 offset: 0"`

**Comment by istx25** [comment]
Hi @bruce-lumo! Please update Realm to at least v2.4.3 (but I recommend running the latest version which is v2.4.4). In most cases, #4598 should've fixed the issue.

**Comment by istx25** [comment]
@Florelit: Please file another issue with your own set of repro steps and information. It's possible there are multiple issues causing this to happen or some other reason in your codebase. Thanks!

**Comment by bruce-lumo** [comment]
Thanks, I'll upgrade.

**Comment by shenAlexy** [comment]
I have the similar issue with realm 2.7.0

**Comment by jpsim** [comment]
You'll need to share more details about what issue you're facing for us to be able to help, @shenAlexy. Please file a new issue taking care to fill out the new issue template: https://github.com/realm/realm-cocoa/issues/new

Thanks!
