### ISSUE TITLE
Realm freezes CFRunLoopRun

### ISSUE THREAD

**Issue by waffleboot** [realm/realm-cocoa#4737]
## Goals

We have legacy project in ObjC and wanted to use Realm as additional database inside iOS application and our application uses SOAP and NSURLConnection as network transport but Realm makes livelock inside CFRunLoopRun.

- app has serial queue for running NSURLConnection
- app is subscribed to connectionDidFinishLoading: event
- app makes simple 'ping' to site and runs CFRunLoopRun in queue to enable events
- app closes connection after receiving connectionDidFinishLoading: event
- on CFRunLoopRun exit we log it and after exit from queue's task yet another task will receive slot for execution
- but if we add Realm then CFRunLoopRun will run indefinitely and now our queue is locked 

## Expected Results

RLMRealm (1) doesn't affect runloop

## Actual Results

CFRunLoopRun() is frozen in step (2) when [Realm defaultRealm] is invoked in line (1).
I see a sequence of steps of (1), (2), (5) but queue's internal runloop runs indefinitely in step (2) so I never see steps (3) and (4) and as result my queue is not valid anymore, i.e. I can dispatch tasks to this queue but they will not be processed . If I remove realm then everything is fine, I see as closing connection stops runloop.

## Steps to Reproduce

- create single view's iOS project
- cocoapods `pod init`
- add pod 'Realm', '~> 2.4' to target
- `pod install`
- add my code to initial view controller
- set breakpoints to steps
- run

OR open attached xcworkspace

## Code Sample

[realm_conn.zip](https://github.com/realm/realm-cocoa/files/843387/realm_conn.zip)

```
#import "Realm/Realm.h"

@interface ViewController () <NSURLConnectionDataDelegate>
@end

@implementation ViewController {
  dispatch_queue_t my_queue;
  NSURLConnection *_connection;
}

- (void)viewDidLoad {
  [super viewDidLoad];

  my_queue = dispatch_queue_create("my queue", NULL);

  dispatch_async(my_queue, ^{

    [RLMRealm defaultRealm];      // (1) // comment me make it running
    NSURLRequest *req = [NSURLRequest requestWithURL:[NSURL URLWithString:@"http://google.com"]];
    _connection = [[NSURLConnection alloc] initWithRequest:req delegate:self startImmediately:YES];
    CFRunLoopRun();               // (2) infinite loop inside ios so (3) and (4) as result never been called
    NSLog(@"done");               // (3)

  });
}

- (void)connectionDidFinishLoading:(NSURLConnection *)connection {
  dispatch_async(my_queue, ^{
    NSLog(@"test");               // (4) // never been called when realm is used in the same queue
  });
  _connection = nil;              // (5) // without (1) this line stops runloop so (2) and (3) will be called
}

@end
```

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217

/Applications/Xcode.app/Contents/Developer
Xcode 8.1
Build version 8B62

/usr/local/bin/pod
1.2.0
Realm (2.4.4)
Realm (~> 2.4)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)


(not in use here)

/usr/bin/git
git version 2.9.3 (Apple Git-75)
```

**Comment by waffleboot** [comment]
@autoreleasepool {
      [RLMRealm defaultRealm];      // workaround, but I don't understand why
    }

**Comment by waffleboot** [comment]
Log of Runloop events
With Realm

    kCFRunLoopEntry 
    kCFRunLoopBeforeTimers 
    kCFRunLoopBeforeSources 
    kCFRunLoopBeforeWaiting 
    kCFRunLoopAfterWaiting 
    kCFRunLoopBeforeTimers 
    kCFRunLoopBeforeSources 
    kCFRunLoopBeforeTimers 
    kCFRunLoopBeforeSources 
    kCFRunLoopBeforeWaiting 
    kCFRunLoopAfterWaiting 
    kCFRunLoopBeforeTimers 
    kCFRunLoopBeforeSources 
    kCFRunLoopBeforeWaiting <-- and that's all, no more after it

Without Realm

    kCFRunLoopEntry 
    kCFRunLoopBeforeTimers 
    kCFRunLoopBeforeSources 
    kCFRunLoopBeforeWaiting 
    kCFRunLoopAfterWaiting 
    kCFRunLoopBeforeTimers 
    kCFRunLoopBeforeSources 
    kCFRunLoopBeforeTimers 
    kCFRunLoopBeforeSources 
    kCFRunLoopBeforeWaiting 
    kCFRunLoopAfterWaiting 
    kCFRunLoopExit

**Comment by waffleboot** [comment]
or I need to stop runloop by this way

    if (dispatch_get_current_queue() != dispatch_get_main_queue()) {
        CFRunLoopStop(CFRunLoopGetCurrent());
    }

**Comment by bdash** [comment]
`CFRunLoopRun` runs the runloop in the default mode until all sources and timers are removed, or `CFRunLoopStop` is called. Your code appears to be operating under the assumption that no-one else will ever add a runloop source or register a timer on that runloop, and that all runloop sources will be removed when your network request concludes. I don't think it's safe to make assumptions about the behavior of any third-party code you call into, whether it be Realm's or Apple's.

Furthermore, I'd advise against running a runloop on a dispatch queue. Dispatch queues a serviced by a limited number of system-owned threads, and it's frowned upon to block them for indeterminate amounts of time such as while waiting for a network request. `NSURLConnection` will happily let you [schedule the connection on a different runloop](https://developer.apple.com/reference/foundation/nsurlconnection/1417485-scheduleinrunloop?language=objc), such as the main thread's runloop, or even [schedule delegate callbacks to happen on a dispatch queue](https://developer.apple.com/reference/foundation/nsurlconnection/1411849-setdelegatequeue?language=objc).

If you _absolutely_ must continue to run a runloop on a dispatch queue like this, you should use some explicit signal to determine when to stop running the runloop and then invoke `CFRunLoopStop`. Note that `dispatch_get_current_queue` has been deprecated for a number of years now so shouldn't be relied upon in new code.

**Comment by waffleboot** [comment]
Yes, it looks like it my mistake. Realm uses runloop sources.
external_commit_helpder.cpp:

    // When a RLMRealm instance is created, we add a CFRunLoopSource to the current
    // thread's runloop. On each cycle of the run loop, the run loop checks each of
    // its sources for work to do, which in the case of CFRunLoopSource is just
    // checking if CFRunLoopSourceSignal has been called since the last time it ran,
    // and if so invokes the function pointer supplied when the source is created,
    // which in our case just invokes `[realm handleExternalChange]`.

and event_loop_signal.hpp:

    CFRunLoopGetCurrent
    CFRunLoopSourceCreate
    CFRunLoopAddSource
