### ISSUE TITLE
Counting on realm mobile database

### ISSUE THREAD

**Issue by i-am-chris** [realm/realm-cocoa#4739]
## Goals

I want to get the object size.

## Expected Results

To count and get the data from synced realm

## Actual Results

I get 0 length and nothing on NSLog

## Steps to Reproduce

realm DB on server works

## Code Sample

```
NSURL *serverURL = [NSURL URLWithString:@"http://eat:9080"];
RLMSyncCredentials *usernameCredentials = [RLMSyncCredentials credentialsWithUsername:@"api@as" password:@"api" register:NO];
    
RLMResults<room *> *puppies = [room allObjects];
NSLog(@"🔴 %d",(int)puppies.count); >> this always returns 0 
```

I update the realm remote with:

```objective-c
[RLMSyncUser logInWithCredentials:usernameCredentials authServerURL:serverURL onCompletion:^(RLMSyncUser *user, NSError *error) {
    if (user) {
        NSURL *realmURL = [NSURL URLWithString:[NSString stringWithFormat:@"realm://___:9080/~/%@",hashBooking]];
        RLMRealmConfiguration *config = [[RLMRealmConfiguration alloc] init];
        config.syncConfiguration = [[RLMSyncConfiguration alloc] initWithUser:user realmURL:realmURL];
        RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:nil];
        //room *realm = [room realmWithConfiguration:config error:nil];
            
        room *dataRoom = [[room alloc] init];
        dataRoom.from_name   = [prefs valueForKey:@"FbLoginUser"];
        dataRoom.from_id     = [prefs valueForKey:@"FbIdUser"];
        dataRoom.from_hash   = hashParent;
        dataRoom.to_hash     = hashSitter;
        dataRoom.hashBooking = hashBooking;
        dataRoom.message     = text;
        [realm beginWriteTransaction];
        [realm addObject:dataRoom];
        [realm commitWriteTransaction];
        // Read some data from the bundled Realm
        //RLMResults<room *> *room = [room objectsInRealm:realm where:@"age > 5"];
          
        RLMSyncUser *user = [RLMSyncUser currentUser];
        // PROBLEM HERE:  Still shows zero ... :/
        NSLog(@"☕️ REALM USER: %@ in realm: %@", user,realm);
    } else if (error) {
        // handle error
        NSLog(@"EROARE: %@",error);
    }
}];

RLMResults<room *> *dataRoomCount = [room allObjects] ;
// THIS ALSO SHOWS ZERO 👎 
NSLog(@">>>>>>>>>>>> %lu",(unsigned long)dataRoomCount.count);

// MY ROOM:
@interface room : RLMObject

@property NSString *hashBooking;
@property NSString *message;
@property NSString *from_hash, *from_id, *from_push, *from_name;
@property NSString *to_hash, *to_id, *to_push, *to_name;

@end

RLM_ARRAY_TYPE(room)
```

## Version of Realm and Tooling

Mobile DB 

Realm version: last stable 

Xcode version: 8

iOS/OSX version: iOS 10

Dependency manager + version: ??

**Comment by i-am-chris** [comment]
Can anyone shed a light here?
Maybe I am wrongly loading objects in a [RLMSyncUser logInWithCredentials  method? 
Should i request the count outside?
Thanks,

**Comment by istx25** [comment]
Hey @i-am-chris! I am personally quite new to RMP but I believe the problem you're experiencing has to do with the fact that you're creating an instance to a non-default Realm and using it to persist the `dataRoom` object in `logInWithCredentials` scope but you're looking for the object in the default Realm by using `[room allObjects]`.

Read [Queries](https://realm.io/docs/objc/latest/#queries) for more information. Namely the code block at the bottom of the section stating: `RLMResults<Dog *> *dogs = [Dog allObjects];` retrieves all Dogs from the default Realm.

I recommend initializing your custom Realm outside of the `logInWithCredentials` scope such as:

```objective-c
RLMRealmConfiguration *config = [[RLMRealmConfiguration alloc] init];
config.syncConfiguration = [[RLMSyncConfiguration alloc] initWithUser:user realmURL:realmURL];
RLMRealm *myCustomRealm = [RLMRealm realmWithConfiguration:config error:nil];
```

Then make use of `myCustomRealm` inside the `logInWithCredentials` scope:

```objective-c
room *dataRoom = [[room alloc] init];
/* Set the properties */

[myCustomRealm beginWriteTransaction];
[myCustomRealm addObject:dataRoom];
[myCustomRealm commitWriteTransaction];
```

And then fetching all of the objects using:

```objective-c
RLMResults<room *> *dataRoomCount = [room allObjectsInRealm:myCustomRealm]
```

This would ensure you're using the same Realm when persisting objects and looking for objects.

**Comment by istx25** [comment]
I'm going to still escalate this issue up to one of the Cocoa engineers in case there's a better solution but I believe this should get you in the right direction (while the engineers work through their queues to this issue).

**Comment by i-am-chris** [comment]
was trying it  

Terminating app due to uncaught exception 'RLMException',
 reason: 'Realm accessed from incorrect thread.'

**Comment by istx25** [comment]
Ack, my apologies. The problem is that (by design) Realm objects can't pass through thread boundaries. Since I don't know how all of RMP works yet, I'm going to leave it to the Cocoa and RMP engineers to answer this further. They should follow-up with you soon.

**Comment by i-am-chris** [comment]
I think this is a small issue and solvable pretty easy / but I cannot see it atm 
Thanks, waiting... 👍

**Comment by austinzheng** [comment]
Your code beginning at `RLMResults<room *> *dataRoomCount = [room allObjects] ;` is being executed synchronously with your call to `logInWithCredentials:...`. The code in the completion block is being executed _asynchronously_, and almost certainly after the code where you get `allObjects`. Please read about how callback functions work [here](https://en.wikipedia.org/wiki/Callback_(computer_programming)).

Also, `[room allObjects]` gets the objects of type `room` (which should be capitalized as `Room`) from the default Realm. The room in the completion block is being placed in a Realm that isn't the default Realm.

**Comment by i-am-chris** [comment]
Hello back, 
Can you give me a full example on how to get data?
I am mostly intrigued on how to use this on  given array, when i call the mobile DB for updates. 
(think about updates on a chat room - which can be a very good example on how to move this data async)

Objective-c obviously - might be old-school but i am looking fwd into implementing this

Thanks,
Chris

**Comment by austinzheng** [comment]
Please consult our [documentation](https://realm.io/docs/objc/latest/) and [API reference](https://realm.io/docs/objc/2.4.4/api/), which contains extensive information about how to use Realm's APIs and sample code.
