### ISSUE TITLE
Realm List doesn't update in Browser after write call

### ISSUE THREAD

**Issue by cmyers78** [realm/realm-cocoa#4740]
## Goals

Have an empty List that I want to set equal to another list and write it to Realm database

## Expected Results

GameDataCollection contains my Score objects

## Actual Results

Empty List contains the data I set it to, but does not write to the Realm database

## Steps to Reproduce
I save some data to SDNormalDataObject on one VC.  A few VCs later, I pull it back out to update the remaining values of the model.  Everything else write/saves fine except for the answerCollectionSD
which is a List<Scores>.  The Scores object has two properties.

```
do {
          let realmChallenge = try Realm()
            // grab the last SDNormalData Object that was written
            if let model = realmChallenge.objects(SDNormalData.self).last {
                try realmChallenge.write {
                    model.answerCollectionSD = challengeData.answerCollectionSD
                        print("Model answer Collection: \(model.answerCollectionSD)")   
         }
     }
```
## Version of Realm and Tooling
Realm version: most recent

Xcode version: 8

iOS/OSX version: 10

Dependency manager + version:

**Comment by bdash** [comment]
Can you please share the declaration of your `SDNormalData` class?

**Comment by tgoyne** [comment]
Assigning directly to a `List` property does not do anything (because Swift does not have any way for us to make it do something).  This is why we say [`List` properties should always be declared with `let`](https://realm.io/docs/swift/latest/#property-attributes).

**Comment by cmyers78** [comment]
```
class SDNormalData: Object {

      // Challenge Mode Data
    dynamic var timeAwayBetweenGamesNMSD = Double() 
      // must pull from normal mode time ended to calculate the time the participant waited between       games
    dynamic var timesPlayedSD = Int()
    dynamic var completedGameSD = Int()
    dynamic var startTimeSD = String()
    dynamic var endTimeSD = String()
    dynamic var submissionTypeSD = Int()
    
    dynamic var totalCorrectSD = Int()
    dynamic var totalIncorrectSD = Int()
    var answerCollectionSD = List<UpdatedScore>()
    
    dynamic var leftGameSD = Int()
    var timeStampCollectionSD = List<TimeStampString>()
}
```

This is the part I update on a later VC.

**Comment by bdash** [comment]
As @tgoyne mentioned, your `List<T>` properties should be declared with `let` rather than `var` as assigning directly to them has no effect. You should instead mutate the `List<T>` in place.

**Comment by cmyers78** [comment]
I'm not sure I follow.  what does "mutate in place" mean?

**Comment by bdash** [comment]
Instead of assigning to the property:
```swift
model.answerCollectionSD = challengeData.answerCollectionSD
```

Call mutating methods on the existing value of the property:
```swift
model.answerCollectionSD.removeAll()
model.answerCollectionSD.append(contentsOf: challengeData.answerCollectionSD)
```

**Comment by cmyers78** [comment]
oh okay.  thank you!
