### ISSUE TITLE
Support installation via SPM

### ISSUE THREAD

**Issue by BrandonZacharie** [realm/realm-cocoa#4745]
## Goals

What do you want to achieve?

To install Realm via SPM (Swift Package Manager)

## Expected Results

What did you expected to happen?

To install RealmSwift after running `swift build` when `Package.swift` contains something like
```
import PackageDescription

let package = Package(
  dependencies: [
    .Package(url: "https://github.com/realm/realm-cocoa.git", majorVersion: 2)
  ]
)
```

**Comment by jpsim** [comment]
We'd like this too! In fact, we're already tracking this in #4555. So I'll be closing this one as a duplicate.
