### ISSUE TITLE
Thread exception when printing Object description with relationships

### ISSUE THREAD

**Issue by markst** [realm/realm-cocoa#4747]
## Goals

Wish to log a resolved realm object description on a separate thread. 

## Expected Results

`descriptionWithMaxDepth:` to appropriately return description. 

## Actual Results

`IncorrectThreadException` raised. 

## Code Sample

Create `Object` subclass which has at least one relationship. 

```swift
class Group: Object {

    dynamic var id: String = ""
    dynamic var name: String = ""

    dynamic var site: Site?
```

Now create an instance of the object & give it a relationship object, in this case an instance of `Site`.

Now create a `ThreadSafeReference`.

On a new thread create an instance of Realm, resolve the thread reference & then try logging:
```swift
let realm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "MyInMemoryRealm"))
realmObject = realm.resolve(resourceThreadRef)
print("realmObject: \(realmObject)")
```

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

/Applications/Xcode.app/Contents/Developer
Xcode 8.2.1
Build version 8C1002

/usr/local/bin/pod
1.2.0
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.15.2
(not in use here)

/usr/bin/git
git version 2.10.1 (Apple Git-78)
```

**Comment by jpsim** [comment]
Thanks for reporting this @markst, I'm looking into it.

**Comment by markst** [comment]
@jpsim I think this is largely to do with Realm not complaining when setting a relationship from a different realm. i.e:
```swift
let group = Group(value: ["id":NSUUID().uuidString])
group.site = self.site
```

Resolution for above exception is:
```swift
group.site = realm.create(Site.self, value: self.site, update: true)
```

**Comment by markst** [comment]
This also appears to happen if making an unmanaged copy of a realm object which has relationships:
```swift
let unmanagedUser = User(value: self.user!)
print("unmanagedUser: \(unmanagedUser)")
```

**Comment by markst** [comment]
Haven't been able to delve too deep, but could be due to `RLMIsObjectValidForProperty()` not correctly identifying whether it's a valid object for property.
https://github.com/realm/realm-cocoa/blob/master/Realm/RLMUtil.mm#L151

Otherwise the correct duplication of array would occur here:
https://github.com/realm/realm-cocoa/blob/master/Realm/RLMObjectBase.mm#L95

**Comment by markst** [comment]
This is bizarre & seems to happen even if creating unmanaged copies of the relationships also:
```swift
// Create unmanaged if necessary
var fitting: Fitting = self.fitting.realm == nil ? self.fitting : Fitting(value: self.fitting)
fitting = self.fittingInformationViewController!.fittingInformationView.updateFitting(fitting: fitting)

// Update test relationship with umanaged if necessary
let test: Test = fitting.test?.realm == nil ? fitting.test! : Test(value: fitting.test!)
fitting.test = self.testResultViewController!.testResultView.update(test: test)

// Update group relationship with umanaged if necessary 
let group: Group = fitting.group?.realm == nil ? fitting.group! : Group(value: fitting.group!)
fitting.group = group
```

My solution for now is to return nil for description:
```objc
- (NSString *)description
{
    NSLog(@"self.class.className: %@ self: %@ description: %@",self.class.className,self,self.realm);
    return nil;
}
```

**Comment by bdash** [comment]
The problems mentioned in https://github.com/realm/realm-cocoa/issues/4747#issuecomment-287668924 and https://github.com/realm/realm-cocoa/issues/4747#issuecomment-289986583 seem at first glance like they stem from an expectation that `Object(value:)` will perform a deep copy of the passed-in object, when in fact only a shallow copy is performed. This means that any objects referenced via relationships (either properties that are of an `Object` subclass type or `List<T>`) would still refer to the instances from the original Realm (and thus from a different thread if the copied object is passed to a different thread). As @jpsim mentioned at https://github.com/realm/realm-cocoa/issues/4882#issuecomment-296810821, we have #3381 tracking adding a built-in way to perform a deep copy in the future.

The initial comment mentions seeing this problem when using a `ThreadSafeReference`, which must have a different cause. It'd be worth seeing if we can reproduce that.

**Comment by bdash** [comment]
@markst, can you please share self-contained steps to reproduce the problem when you're able (keeping in mind my point above about `Object(value:)` only performing a shallow copy)?

**Comment by austinzheng** [comment]
Given the age of this issue and the lack of movement, I am closing it. If you see this problem again with the latest version of Realm and are able to build a repro case (or at least offer reproduction steps), please feel free to re-open this ticket or to file a new one.
