### ISSUE TITLE
suck documentation

### ISSUE THREAD

**Issue by mihailsalari** [realm/realm-cocoa#4749]
Where is the right documentation?

**Comment by bdash** [comment]
You'll need to provide more information. What documentation are you looking for?

**Comment by mihailsalari** [comment]
Ok, lets look for this, I want to save every time an item(string) to array. For official documentation I created that:

```
import Foundation
import RealmSwift
import Realm

class Item: Object {
    
    // MARK: - Properties
    
    dynamic var scannedText = ""
}


class ScanObjects: Object {
    
    // MARK: - Properties
    
    var items = List<Item>()
}
```

Looks good, but I start to save data to that "list":
```
 if let scannedText = scannedText {
            if let realm = try? Realm() {
                do {
                    try realm.write {
                        let item = Item()
                        item.scannedText = scannedText
                        
                        let scannedObject = ScanObjects()
                        scannedObject.items.insert(item, at: 0)
                        realm.add(scannedObject)
                    }
                } catch {
                    print(error.localizedDescription)
                }
            }
        }
```

Also, looks verry good, but, how to retrieve that array from database, I cant explain:
I tried:
```
if let realm = try? Realm() {
                let objects = realm.objects(Item.self)
                print(objects.count) /// 0 objects
            }
```


also:

```
if let realm = try? Realm() {
                let objects = realm.objects(ScanObjects.self)
                print(objects.count) // 0 objects
            }
```

I you create that "magnifique" database, please provide a normal documentation to use:

1: Ho to save data: array, dicts, primitive data etc;
2. How to retrieve saved data: array, dicts, primitive data;
3. Ho to archive that data(before save), after, how to dearchive
4. How to delete and update data: array, dicts, primitive data, etc.


HOW???

Thanks!

**Comment by bdash** [comment]
I dropped the code you provided into a test project and got the expected result (1 of each object).

The first thing to check is whether your `if let scannedText = scannedText` block is even being entered. If the block isn't entered, no objects will be stored. A breakpoint or print statement would help confirm this.

**Comment by mihailsalari** [comment]
Ok, why I retrieve 0? I run the same code. How to retrieve data? Please provide the full answer no 5%.

**Comment by mihailsalari** [comment]
Or let admin of this Repo respond to my question.

**Comment by bdash** [comment]
As I stated, the most likely reason you're seeing zero is that `scannedText` is nil and so you're never adding any objects to the Realm. In my test I'm explicitly setting it to a non-nil value:

```swift
let scannedText: String? = "Scanned text"
```

See https://gist.github.com/bdash/799e9c496d387bda98e196289e2def71 for the full code I tested.

**Comment by mihailsalari** [comment]
I cant see the resolve of this problem from you.

**Comment by mihailsalari** [comment]
The conclusion is: Realm has a suck documentation!

**Comment by bdash** [comment]
I'm really not clear what you expected here. I demonstrated that given correct inputs, the code you shared works correctly, and I provided a hypothesis as to which of your inputs is incorrect and is leading to the incorrect behavior you're seeing. If you're not willing to debug your own code to test this hypothesis, I don't think there's anything we can do to help you.

**Comment by mihailsalari** [comment]
Man, are you ill? What I'm write at start?

If you create that "magnifique" database, please provide a normal documentation to use:

1: Ho to save data: array, dicts, primitive data etc;
2. How to retrieve saved data: array, dicts, primitive data;
3. Ho to archive that data(before save), after, how to dearchive
4. How to delete and update data: array, dicts, primitive data, etc.

**Comment by mihailsalari** [comment]
I cant found that info on official super realmwebsite.

**Comment by bdash** [comment]
All of that information is covered at https://realm.io/docs/swift/latest/, which you'd get to by clicking on the Docs link at the top of the Realm homepage.

**Comment by mihailsalari** [comment]
Sorry, but this documentation is not useful.

**Comment by istx25** [comment]
@mihailsalari: I wanted to chime in here and affirm that @bdash's example ([available here](https://gist.github.com/bdash/799e9c496d387bda98e196289e2def71) indeed works and that I also saw one object returned in my own tests.

We are happy to help you resolve this (and any other) issue you may experience (now or in the future) but I/we don't appreciate the personal attacks on @bdash or anyone else. 

**Please take some time to read through [Realm's Code of Conduct](https://realm.io/conduct).**
