### ISSUE TITLE
Live updating Results on date filter.

### ISSUE THREAD

**Issue by kajensen** [realm/realm-cocoa#4765]
Please enlighten me if there is someway to do this, but i've poked around and tried a couple different things but haven't found a solution

## Feature Request

My scenario: I have a list of data with a createdDate. I want to support insert (animations) via a NotificationToken based on a "delay" for the createdDate. So when setting up the notification/results, this would be the call:
`comments = realm.objects(Comment.self).filter("createdDate < %@", Date(timeIntervalSinceNow: -60))`
to essentially wait one minute to show new comments.

The issue is that date is static. I don't want to periodically refresh the notification with a new date as reloading the tableview is not a good user experience.

**Comment by bdash** [comment]
This sounds similar to what was requested in #4674.

**Comment by kajensen** [comment]
Whoops- yeah pretty much the same request.

It would be awesome if filters had a closure option to include or not, not sure if thats even feasible.

**Comment by istx25** [comment]
@kajensen: Please follow-up on that issue showing your support for the feature. :) Closing this issue since it's basically a duplicate.
