### ISSUE TITLE
Can we delete all objects of particular type

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#4769]
I want to delete all objects of particular type.

Eg: let realm = Realm()
realm.delete(Uploading.self)

Uploading is an realm object it has so many entries in realm i want to delete all of them.

**Comment by TimOliver** [comment]
Hi @santhoshs5!

Yep! If you want to delete all objects of a particular type, but preserve the rest of the contents of a Realm file, you can query for just those objects and then delete them manually.

```swift
let realm = try! Realm()
let allUploadingObjects = realm.objects(Uploading.self)

try! realm.write {
    realm.delete(allUploadingObjects)
}
```

I hope that helped! Let me know if you have any more questions. :)

**Comment by santhoshs5** [comment]
can't we delete them without querying them.

**Comment by santhoshs5** [comment]
In my case i am going to delete all objects of particular type and no need of considering what values it has.

let realm = Realm()
realm.delete(Uploading.self)

I was expecting some thing like above let me know if it is available .

**Comment by bdash** [comment]
As @TimOliver mentioned, you can do what you're after by combining `Realm.objects(_:)` and `Realm.delete(_:)`.

```swift
let realm = try Realm()
try realm.write {
   realm.delete(realm.objects(Uploading.self))
}
```

**Comment by santhoshs5** [comment]
Thanks @bdash

**Comment by crontab** [comment]
@bdash is that method memory efficient though? Doesn't it load all objects before deleting them?

**Comment by bdash** [comment]
Yes, it's memory efficient. No, it doesn't load all objects.

**Comment by JonathanEsposito** [comment]
Nor does @TimOliver's solution. 
(All queries (including queries and property access) are lazy in Realm. Data is only read when the properties are accessed. ref: [realm documentation](https://realm.io/docs/swift/latest/#queries)) 
It is only more readable. So I prefer his.. :)
