### ISSUE TITLE
Realm Delete All

### ISSUE THREAD

**Issue by scottazord** [realm/realm-cocoa#4772]
Hey All,

Just wondering what the correct process is for deleting all realm objects when there are multiple threads using realm. 

Is there a way to block all threads from inserting into the realm database once it has been cleared?

The use-case is that when the user logs out, i want to delete all their realm information. 

Regards,
Scott.

**Comment by istx25** [comment]
Hi @scottazord! I wanted to let you know that we've received your question and that someone will follow-up with you hear and provide an answer soon. Still working through the backlog from the weekend and whatnot. Thanks!

**Comment by bdash** [comment]
The simplest approach for dealing with this use case would be to use a unique Realm path per log-in, so when a user logs out and a new user logs in you'd start writing to a Realm at a different path. You could then remove the original Realm once all aspects of your app have stopped using it.

**Comment by scottazord** [comment]
Hey Mark,

I think that's a good solution.

Appreciate your response,

Regards,
Scott.
