### ISSUE TITLE
Migration Required Even After deleting App from device and reinstalling....

### ISSUE THREAD

**Issue by sirvon** [realm/realm-cocoa#4774]
## Goals

All I'm trying to do is included a pre populated realm file created from csv using realm browser
the realm file has 2 models in it.

## Expected Results

After deleting app from device and rebuilding and installing, I expected to receive the results queried.**

## Actual Results

I receive a error msg telling me to migrate....

```swift
UserInfo={NSLocalizedDescription=Migration is required due to the following errors:
- Property 'Destination.lat' has been changed from 'string' to 'double'.
- Property 'Destination.lng' has been changed from 'string' to 'double'.
- Primary Key for class 'Destination has been added.
- Primary Key for class 'Site has been added., Error 
```

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

```swift
func getHebronDestinations() -> Results<Destination> {
    Log.info?.message("\(Realm.Configuration.defaultConfiguration.fileURL!)")
    let bundleUrl = Bundle.main.url(forResource: "default", withExtension: "realm")
    let config = Realm.Configuration(
        fileURL: bundleUrl,
        readOnly: true,
        schemaVersion: 0,
        migrationBlock: { migration, oldSchemaVersion in
            if (oldSchemaVersion < 1) {
                Log.info?.message("\(oldSchemaVersion)")
                Log.info?.message("wtf")
            }
            
            if (oldSchemaVersion < 2) {
                Log.info?.message("\(oldSchemaVersion)")
            }
            
            Log.info?.message("Realm migration did run")  // Log to know migration was executed
        }
    )
        
    let realm = try! Realm(configuration: config)
    let naoHebronResults = realm.objects(Destination.self)
    Log.info?.message("\(naoHebronResults)")
        
    for res in naoHebronResults{
        Log.info?.message(res.destinationName)
    }
    
    return naoHebronResults
}
```

## Version of Realm and Tooling

- Realm version: Latest
- Xcode version: 8.2.1
- iOS/OSX version: ?
- Dependency manager + version: Carthage

**Comment by istx25** [comment]
Hi @sirvon. Thanks for writing in. I wanted to let you know that someone will review what you've shared and follow-up with you soon. In the meantime, would you be able to provide us with the actual version of Realm you're using (since "Latest" can change between response times) as well as the iOS or macOS version you're compiling for. Thanks.

**Comment by kishikawakatsumi** [comment]
@sirvon `schemaVersion` starts `0` by default. So specifying schemaVersion `0` doesn't fire migration process. You should increase `schemaVersion` more than `0` if you changed your data model.

**Comment by sirvon** [comment]
I got this to work. The types were wrong in one of the realm models I prepopulated with a csv via realm browser. Had to recreate the csv/file used to make the csv. thank you.
