### ISSUE TITLE
Realm Swift 2.4.4 do not support Swift 3.1? Only to Swift 3.0.2?

### ISSUE THREAD

**Issue by ZeKaiDev** [realm/realm-cocoa#4775]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. We do not support pre-release versions of Xcode or Swift (such as 3.1) with our prebuilt binaries. You are welcome to clone this repository and build Realm from source, though.

**Comment by jpsim** [comment]
Austin is correct but we do make a best effort to compile and pass all tests as Xcode betas are released, so you should be able to build Realm Swift from source with any of the Xcode 8.3 betas starting with beta 2.

**Comment by vojto** [comment]
It's not beta anymore...

**Comment by austinzheng** [comment]
It was when I commented. We should have a new release out today that supports Xcode 8.3 (and contains a few minor enhancements) if all goes to plan.

**Comment by jpsim** [comment]
No guarantees about binaries being made available today. Might be tomorrow depending on how our infrastructure upgrades go.

**Comment by gianina-ingenuity** [comment]
hi any update on realm for 8.3?

**Comment by jpsim** [comment]
Our [2.5](https://github.com/realm/realm-cocoa/releases/tag/v2.5.0) and [2.5.1](https://github.com/realm/realm-cocoa/releases/tag/v2.5.1) release archives both include binaries built with Xcode 8.3.
