### ISSUE TITLE
Xcode 8.3-Swift 3.1

### ISSUE THREAD

**Issue by saham** [realm/realm-cocoa#4784]
## Goals

Realm to work with Xcode 8.3 ad Swift 3.1
## Expected Results

Just runs normally
## Actual Results
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

## Code Sample
import RealmSwift

## Version of Realm and Tooling

Realm version: ? 2.4.4

Xcode version: ? 8.3

iOS/OSX version: ? MacOS 10.12.4

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. We're currently preparing a new release that will be compatible with Swift 3.1 and hope to release it within the next few days.

**Comment by din** [comment]
This is still happening for me on Xcode 8.3 + RealmSwift 2.5.
<img width="583" alt="screen shot 2017-03-31 at 17 18 00" src="https://cloud.githubusercontent.com/assets/78038/24550094/01eef774-1636-11e7-87e6-abf77344586d.png">

**Comment by bdash** [comment]
@din, that's a different issue than what was originally reported here. Please file a new bug report and provide all of the information listed in the new issue template.
