### ISSUE TITLE
The size of `Realm.framework/Realm` becomes too big when built with Swift 3.1 in Xcode 8.3

### ISSUE THREAD

**Issue by yuzushioh** [realm/realm-cocoa#4785]
## I am using

- Realm version:  2.4.4
- Xcode version:  8.3
- OSX version:  10.12.4
- Dependency manager + version: Carthage 0.14.0

## What's happening

After updating Xcode to 8.3, Swift 3.1, and Carthage builds by running `carthage update realm-cocoa --platform ios --no-use-binaires`, the size of `Realm.framework/Realm` becomes 155.50 MB. It was only 54 MB in Xcode 8.2, Swift 3.0.1.

#### I already tried below but wouldn't fix
- clean up all the cache in Xcode
- delete the existing build and build again

## Problem

Because all the `.framework` built with Carthage are committed to the repository in my project, the size of each frameworks needs to be less than 100MB since GitHub's file size limit is 100MB. I want to make it smaller than that. Is there any suggestions or tricks to fix this problem? 

Thank you!

**Comment by tgoyne** [comment]
I'm seeing the same result building `master` locally. The Swift and macOS frameworks are roughly the same size; it's only the iOS Realm.framework that's larger.

**Comment by tgoyne** [comment]
The `__LLVM` segment is now 70 MB in each of the device slices, so this does look like it's due to bitcode.

**Comment by jpsim** [comment]
Alright, well there's no much we can do to alleviate that then.

**Comment by jpsim** [comment]
[rdar://31302382](http://www.openradar.me/31302382): Xcode 8.3 produces binaries 3x larger than Xcode 8.2 due to a 4x increase in bitcode

**Comment by h-anders-unext** [comment]
Sorry to comment on a closed issue.
Is this claim in the FAQ still correct:
> Once your app is built for release, Realm should only add around one megabyte to its size.

?

**Comment by jpsim** [comment]
No, that's incorrect. For example, if you look at the macOS framework, which only has a single architecture slice and no bitcode, it weighs in at 7MB.

And some quick checks would indicate that iOS slices are closer to 5.7MB for Realm Objective-C, 1.2MB for Realm Swift:

```
$ ./build.sh ios-swift
$ cd build/ios/swift-3.1
$ xcrun bitcode_strip -r Realm.framework/Realm -o Realm.nobitcode
$ xcrun bitcode_strip -r RealmSwift.framework/RealmSwift -o RealmSwift.nobitcode
$ lipo -thin arm64 RealmSwift.nobitcode -o RealmSwift.arm64
$ lipo -thin arm64 Realm.nobitcode -o Realm.arm64
$ size Realm.arm64
5.7M	Realm.arm64
$ size RealmSwift.arm64 
1.2M	RealmSwift.arm64
```

Thanks for bringing this to our attention. I've updated this section of our docs to reflect this information, it should be live momentarily.

**Comment by nevil** [comment]
@jpsim 
Thanks for responding so quickly and updating the docs!

**Comment by harryworld** [comment]
Does that mean I cannot include Realm in watchOS? It is now exceeding the 50MB limit.

**Comment by jpsim** [comment]
The watchOS framework should just add 5.1MB to your app installed on user devices via the App Store. From the release archive:

```
$ lipo -thin armv7k Realm.framework/Realm -o Realm.armv7k
$ xcrun bitcode_strip -r Realm.armv7k -o Realm.armv7k.nobitcode
$ size Realm.armv7k.nobitcode 
5.1M	Realm.armv7k.nobitcode
```

That being said, would you know if bitcode counts towards that limit? We never got clarification on that in #3430.

**Comment by fishfisher** [comment]
I'm unable to upload new builds to iTunesConnect as it says my watchOS app is exceeding the limit. It is now 101 MB. Any tips?

**Comment by jpsim** [comment]
To avoid the bitcode explosion issue present in Xcode 8.3, I'd suggest using a previous version of Xcode that produces binaries with smaller bitcode slices.

**Comment by adomanico** [comment]
@jpsim I am actually seeing building with 8.2.1 still produce the same inflated sizes in iTunes Connect. 

This seems to indicate a massive regression on Apple's end.

Facebook's app size on the AppStore is 320mb on a iPhone 7 Plus (and they just shipped the update today)

**Comment by jpsim** [comment]
From the measurements I reported in [rdar://31302382](http://www.openradar.me/31302382), Xcode 8.2.1 produces much smaller bitcode slices than 8.3. I haven't compared 8.2.1 with earlier versions to see if it also regressed.

**Comment by adomanico** [comment]
To anyone else that needs an immediate resolution, you will have to disable bitcode as well as use Xcode 8.2.1 until this bug is fixed by Apple.

**Comment by harryworld** [comment]
Our latest built was archived in Xcode 8.2.1 with bitcode enabled after Xcode 8.3 is out
We have RealmSwift in both iPhone and Watch
It does not inflate the Realm binary, and the sizes of variations range from 71.1MB to 72.4MB

I guess the problem only happens in Xcode 8.3

**Comment by kidsid-Ixigo** [comment]
Where I can download XCode 8.2.1 now?

**Comment by bdash** [comment]
https://developer.apple.com/download/more/

**Comment by harryworld** [comment]
Does Xcode 8.3.1 solve the problem?

**Comment by bdash** [comment]
Yes, it should do.
