### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by danieldelouya** [realm/realm-cocoa#4787]
Any news about when newest Realm build is coming for 3.1? Can't compile my code after updating to Xcode 8.3 / Swift 3.1.
Cheers

**Comment by Tintenklecks** [comment]
Had the same problem. Just used the method provided in another post. As I use carthage (which itself downloads the binary by default) just add the --no-use-binaries option to the update command: 

carthage update --no-use-binaries

It takes a while .... really a while ... 15 min on a MBP 2015 ;-) but it worked for me and I have the swift 3.1 frameworks now

**Comment by kishikawakatsumi** [comment]
@Tintenklecks @danieldelouya Or update Carthage to 0.20. Carthage uses pre-built binary only when they were built with the same version of the Swift compiler from 0.20. No longer need to --no-use-binaries :)
https://github.com/Carthage/Carthage/releases/tag/0.20.0

**Comment by danieldelouya** [comment]
What if I've added the Realm frameworks manually?

**Comment by kishikawakatsumi** [comment]
@danieldelouya We've released Realm 2.5.0 that is built by Xcode 8.3 https://realm.io/docs/swift/latest/

**Comment by danieldelouya** [comment]
@kishikawakatsumi Yes thank you! Updated some hours ago and everything works :) Appreciate you guys being quick with these kind of things. Cheers
