### ISSUE TITLE
Without Carthage - Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by danieldelouya** [realm/realm-cocoa#4788]
How does one update if I don't wanna use Carthage as suggested by others as a solution?

**Comment by jpsim** [comment]
There are several options. You can build from source using CocoaPods, Xcode subprojects, you can produce a binary yourself using `build.sh`.

**Comment by danieldelouya** [comment]
I installed Realm manually in my project and would like to keep doing so. But thanks. Think I'll just use Carthage from now on. Haven't tried producing a binary myself yet

**Comment by danieldelouya** [comment]
Just tried via Carthage. I still get the same error actually. 

Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: xxxx/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule

**Comment by jpsim** [comment]
That error is telling you that you built Realm Swift with Xcode 8.2 (Swift 3.0.2), but you're trying to use it with Xcode 8.3 (Swift 3.1). If you have multiple Xcodes installed, you can specify which one Carthage should use by setting the `DEVELOPER_DIR` environment variable.

Also make sure you're building from source `carthage update --no-use-binaries`.

**Comment by danieldelouya** [comment]
Thanks. I did use `carthage update --no-use-binaries` and I only have one xcode installed (8.3).

**Comment by jpsim** [comment]
Then how did you produce a binary compiled with Swift 3.0.2?

**Comment by danieldelouya** [comment]
Zero clue. I'll just wait for the 3.1 release if it's on its way anyways
