### ISSUE TITLE
Please enter valid encryption key for realm file

### ISSUE THREAD

**Issue by saham** [realm/realm-cocoa#4795]
<img width="1034" alt="screen shot 2017-03-29 at 9 09 46 am" src="https://cloud.githubusercontent.com/assets/4553478/24456888/6f5c49f4-1462-11e7-9e50-6e931599102b.png">

## Goals

Open my realm DB
## Expected Results

Opens the file as usual
## Steps to Reproduce

Just open a realm DB created with Realm-Swift 2.5.0
## Version of Realm and Tooling

Realm version: ?
2.1.6
Xcode version: ?
8.3.1
iOS/OSX version: ?
MacOS Sierra 10.12.4
Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@saham This means that you attempt to open encrypted Realm file, synced Realm file that was produced by Realm Mobile Platform or a corrupted Realm file. If you don't use encryption feature, the file may be corrupted. Could you share more details? Please share your code around using Realm.

**Comment by saham** [comment]
It's a big project but I will share some codes working on realm. I even deleted all realm database files and folders but I still get the same error. How can I find if I am using synced one? Where it is synced to?
Thank you

**Comment by saham** [comment]
It happened after I used realm swift 3.5.0 ro work with swift 3.1 and Xcode 8.3

**Comment by kishikawakatsumi** [comment]
@saham It figures out. Realm 2.5 introduces new file format. Existing files will automatically be upgraded when they are opened. The Realm browser in AppStore doesn't support the new file format. You can use new version of browser that can be downloaded from GitHub until new version will be passed AppStore review.

https://github.com/realm/realm-browser-osx/releases/tag/v2.1.7

**Comment by saham** [comment]
Problem solved. Thanks a million

**Comment by intiocean** [comment]
The same thing happened again with the upgrade to the latest version of realm - get the latest realm browser off github: https://github.com/realm/realm-browser-osx/releases/

**Comment by tomkoptel** [comment]
Happened to me as wellon Realm Browser `3.0.1`

**Comment by aalenliang** [comment]
Happened to me sometimes with `Realm Browser Version 3.0.1 (98)`, `RealmSwift (3.17.1)`

**Comment by ashmenon** [comment]
Happening to be as well,  on `Version 3.0.1 (98)`. And I can confirm this is a brand new Realm database (just installed the pod 5 mins ago).

**Comment by anshuvij** [comment]
happening to me as well. using 3.0.1 from AppStore

**Comment by salvoeffe** [comment]
Happening to me as well, found any solutions?

**Comment by leofr1cs** [comment]
Realm browser is deprecated - the developer now has released realm studio (not available on app store but from their website) with one catch... its not fully updated for Catalina (Apple can't scan it for virus') - solution, open in finder, then right click to open it (I guess I'm ok with taking risks... )
... and realm studio CAN open the default.realm file without a prompt for a 128bit encryption key! hooray

**Comment by mhamidg** [comment]
I am also facing the same issue after updating realm version 5....
I am unable to open in realm browser as well as real studio. Same 128 bit encryption error. even I didn't put any encryption.

**Comment by mhamidg** [comment]
I just downloaded Realm Studio latest verison 3.11.0. and its working fine.

**Comment by stevhens** [comment]
Downloaded `Realm Browser 3.0.1` on the App Store and facing the same issue.

> solution:
> Realm browser is deprecated - the developer now has released realm studio (not available on app store but from their website) with one catch... its not fully updated for Catalina (Apple can't scan it for virus') - solution, open in finder, then right click to open it (I guess I'm ok with taking risks... )
> ... and realm studio CAN open the default.realm file without a prompt for a 128bit encryption key! hooray

Referring to @leofr1cs answer above, eventually I could open .realm file with current `Realm Studio 3.11.0 Version`.

To download, go to "Get Started with Realm" section near the bottom of below page and you'll find it:
[Download Realm Studio here](https://www.mongodb.com/realm/mobile/database)

**Comment by shinhyogeun** [comment]
i think best solution is just download realm Studio in https://docs.realm.io/sync/realm-studio 
and they might be considered virus but i think that's because Catalina update is not complited.. 
and i also this @leofr1cs 's opinion (I guess I'm ok with taking risks... ) i think they will update realm Studio in Big sur
