### ISSUE TITLE
Lightweight generics support with Realm on iteration in Swift3

### ISSUE THREAD

**Issue by ashishprasadgit** [realm/realm-cocoa#4801]
**Request**: 
In swift 3, Objective-C type declarations using lightweight generic parameterization are automatically imported by Swift with information about the type of their contents preserved.

```
@interface RLUserAccount: RLMObject
@property NSString *name;

+(nonnull RLMResults<RLUserAccount *> *)userAccounts;
@end

//On calling in swift, 
let userAccounts = RLUserAccount .userAccounts()
//userAccount type in swift comes out be RLMResults<RLUserAccount>

for userAccount in userAccounts {
            print(userAccount.name)
// Throws error as userAccount is referenced as RLMObject not as RLUserAccount. To access name, will have to typecast to RLUserAccount first.
}
```

## Result :
**On iterating through userAccount, name is not directly accessible. Rather typecasting from RLMObject to RLUserAccount is needed to access the name.  Type of content information is lost on iterating through RLMResults in swift.**

Realm version: 2.5.0
Xcode version: 8.2.1 (8C1002) - Swift3

**Comment by istx25** [comment]
Hi, @ashishprasadgit. Thanks for sharing this feature request. I've added those tags and I'll share this issue with the team to see how it might be prioritized in the future.

**Comment by jpsim** [comment]
Realm Objective-C certainly leverages lightweight Objective-C generics in its API, as you've stated in most of your code. The fact that fast enumeration doesn't preserve type information appears unrelated to Realm.

This seems like something that would need to be improved in the ClangImporter component of the Swift compiler. @ashishprasadgit have you [filed a Swift Bug](https://bugs.swift.org)? I'd be happy to chime in on the topic there.

**Comment by ashishprasadgit** [comment]
@jpsim I believe that problem is related with RLMSupport. RLMSupport provides support to enumerate RLMResults in swift classes. 

`public final class RLMIterator: IteratorProtocol {
    private let iteratorBase: NSFastEnumerationIterator
    
    internal init(collection: RLMCollection) {
        iteratorBase = NSFastEnumerationIterator(collection)
    }
    
    public func next() -> RLMObject? {
        return iteratorBase.next() as! RLMObject?
    }
}

extension RLMArray: Sequence {}
extension RLMResults: Sequence {}
`

Here in RLMSupport, return of next iterator is RLMObject. If we can change the RLMSupport to support light-weight generics, then I believe, light-weight generics would be automatically supported in swift.

**Comment by jpsim** [comment]
You're right @ashishprasadgit, however the Objective-C generic information is not available to Swift's type system. Here's the compiler error that prevents us from doing this:

> Extension of a generic Objective-C class cannot access the class's generic parameters at runtime.

We opened [SR-2348](https://bugs.swift.org/browse/SR-2348) in August of last year to track this.

I reiterate that we cannot do this without changes to the Swift compiler. If you manage to find a way, we'd appreciate a pull request.
