### ISSUE TITLE
memory leak when using `List<T>`

### ISSUE THREAD

**Issue by pabloruan0710** [realm/realm-cocoa#4806]
## Goals
I have memory leak when use List<T> in realm 2.5.0 

`class Horario: Object {
   dynamic var Horario:String = "" }`

`class Dia: Object{`
    
    dynamic var Dia:String = ""
    dynamic var Ordem:Int = 0
    var horario = List<Horario>()
    
    override static func primaryKey() -> String? {
        return "Dia"
    }

## Expected Results
I have use weak or unowned reference for list properties

## Actual Results
When defined `weak var horario = List<Horario>()` i can't set value for list, always return nil after set value

## Version of Realm and Tooling

Realm version: 2.5.0

Xcode version: 8.3

iOS/OSX version: 10.2

Dependency manager + version: pod 1.1.1

**Comment by ppamorim** [comment]
Don't use `weak var` or `var` for lists.
