### ISSUE TITLE
Installing RealmSwift pod increasing my app size to 100 mb?

### ISSUE THREAD

**Issue by kidsid-Ixigo** [realm/realm-cocoa#4808]
Hi,

I am using realm in my app and realize after integrating realm my app size grew from 30mb to 128mb. I couldn't believe that so made a sample project and installed the realm as single pod and the same thing happened. My pod file looks like this.

I am scratching my head around how come Realm increases that much app size. 
Am I missing something? 

Thanks in advance!

#### Code Sample

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ream_Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ream_Sample

  pod 'RealmSwift'

  target 'Ream_SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ream_SampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

#### Tooling

- Swift version: 3.1
- Realm version: 2.4.5
- Xcode version: 8.3
- iOS/OSX version: iOS 9 and above
- Dependency manager + version: CocoaPods 1.2.2

**Comment by istx25** [comment]
Hi @kidsid-Ixigo. Thanks for reaching out about this. Would you be able to share us with all of the Realm models that you're using in your project? From there, we'll be able to better assist you.

**Comment by jpsim** [comment]
There's no need to send us your models @kidsid-Ixigo. We've identified a large increase in the bitcode slice that Xcode 8.3 generates compared to previous versions. We've filed a radar with Apple to make them aware of the situation: [rdar://31302382](http://www.openradar.me/31302382).

Using Xcode 8.2.1 should help reduce the generated bitcode slice to a more reasonable size.

However, please keep in mind that bitcode is never downloaded from apps on the App Store, so your users won't be affected by this increased binary size.

Our latest measurements show Realm adding [5 to 8 MB to final app sizes](https://realm.io/docs/swift/latest/#how-big-is-the-realm-library).
