### ISSUE TITLE
Unable to open bundled realm file  on real device

### ISSUE THREAD

**Issue by Eric0625** [realm/realm-cocoa#4809]
**Questions**: 
Hello

When I tested my app on a real iPhone, it says: Unable to open a realm at path '/var/containers/Bundle/Application/E14E2F71-E34F-466E-B56A-836A4E76BCC5/SimpleFit.app/DefaultData.realm.management': make_dir() failed: Operation not permitted.

**But when I tested on the simulator, nothing wrong happened.** Any clue?

The file is included in Build Phases.
![2017-04-01 2 39 54](https://cloud.githubusercontent.com/assets/18132007/24585200/4dfd463e-17b7-11e7-9d4e-88023e4a1631.png)

## Goals

read data from the bundled realm file on real iPhone
## Expected Results

read data successfully
## Actual Results

returning with no permission error:
Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/containers/Bundle/Application/FC0B253C-2EB5-4484-AA75-064F09F29767/SimpleFit.app/DefaultData.realm.management': make_dir() failed: Operation not permitted." UserInfo={Error Code=2, NSFilePath=/var/containers/Bundle/Application/FC0B253C-2EB5-4484-AA75-064F09F29767/SimpleFit.app/DefaultData.realm.management, Underlying=make_dir() failed: Operation not permitted, NSLocalizedDescription=Unable to open a realm at path '/var/containers/Bundle/Application/FC0B253C-2EB5-4484-AA75-064F09F29767/SimpleFit.app/DefaultData.realm.management': make_dir() failed: Operation not permitted.}
## Steps to Reproduce

connect an iPhone and run
## Code Sample

```
let dataFile = Bundle.main.url(forResource: "DefaultData", withExtension: "realm")
let config = Realm.Configuration(
            fileURL: dataFile,
            readOnly: false
        )        
let r = try! Realm(configuration: config) //that's where the error happened
```
## Version of Realm and Tooling

Realm version: 2.4.4
Xcode version:  8.2.1 (8C1002), 
iOS/OSX version: simulator: iPhone 6s-iOS 10.2(14C89), real iPhone: iPhone 6-iOS 10.2, realm version: 2.4.4
Dependency manager + version: cocoa-pod 1.2.0

**Comment by Tripwire999** [comment]
Same here on Realm version: 2.5.0 using a Simulator and real device.

**Comment by kishikawakatsumi** [comment]
@Eric0625 @Tripwire999  Bundle directory is read only. You should copy Realm file to a writable directory (such like documents or library) before opening. Or you can open it as read only.

**Comment by Tripwire999** [comment]
I'm instantiating Realm as a Default instance, i'm not configuring it to store in the bundle directory whatsoever. Plus it does work, but sometimes crashes giving the message.

**Comment by Eric0625** [comment]
@kishikawakatsumi thanks. It worked! But why the simulator allows writing in bundle directory? I thought they are the same, at least on accessing directory.

**Comment by kishikawakatsumi** [comment]
@Eric0625 Devices and simulators behave differently in file IO. The simulator simply runs on the host's file system. For example, a simulator is on case-insensitive (Mac's default settings), but devices are on case-sensitive. Simulators can read a file on Mac's desktop, but of course devices cannot. About the file permissions, it's same.

**Comment by kishikawakatsumi** [comment]
@Tripwire999 Hi, what do you mean? Can you share your code?

**Comment by Tripwire999** [comment]
@kishikawakatsumi I mean I'm not configuring realm to store the file at a certain directory I'm using the default realm configuration. It just sometimes crashes when navigating through my app and doing realm stuff (deleting objects, adding objects e.t.c.). This started to happen after updating to Realm 2.4.4 and Realm 2.5.0 which I'm currently on. I'll upload my code tonight when I'm at home.

**Comment by TimOliver** [comment]
Since @Eric0625 has managed to solve his issue here, I'm going to close this issue. :)

@Tripwire999 It sounds like you might be bumping up against a different, but similar issue. Can you please open a new issue and provide us with a sample of your code and the nature of the crash you're seeing? Thanks!

**Comment by liwenDeng** [comment]
i have met this error too. In my project,i need to read the native realm file which stored the provinces、cities and countries,so i changed the code like this:

    //before
    NSURL *url = [[NSBundle mainBundle] URLForResource:@"area" withExtension:@"realm"];
    RLMRealm *realm = [RLMRealm realmWithURL:url];
    
    //after
    RLMRealmConfiguration *config = [[RLMRealmConfiguration alloc]init];
    config.readOnly = YES;
    config.fileURL = [[NSBundle mainBundle] URLForResource:@"area" withExtension:@"realm"];
    NSError *error = nil;
    RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:&error];

**Comment by tsgin2** [comment]
@Tripwire999 or anyone on this topic, I've got the same issue that you've solved. Apparently, I use React Native in this case. Could you help me how did you replace the file into document folder or could you tell me how did you solve it?

**Comment by davidrazmadze** [comment]
`  override func viewDidLoad() {
    super.viewDidLoad()
    
    /// Initiliaze the realm database
    let realmPath = Bundle.main.url(forResource: "default", withExtension: "realm")!
    let config = Realm.Configuration(fileURL: realmPath, schemaVersion: 1, migrationBlock: { migration, oldSchemaVersion in if (oldSchemaVersion < 1) {} })
    
    do {
      try realm = Realm(configuration: config)
      streetListings = realm.objects(StreetListings.self)
      allListings = streetListings
      print("[Loading] Successfully loaded the database")
      
    } catch {
      print("\(error.localizedDescription)")
    }
    
  }`

**Comment by davidrazmadze** [comment]
Unable to open a realm at path '/private/var/containers/Bundle/Application/059A1774-9D42-4D83-9657-F751F59E93D2/NorthTrash.app/default.realm.management': make_dir() failed: Operation not permitted

**Comment by Tapestes** [comment]
We started seeing this issue in Realm 5.4.0.  Prior to that, setting readOnly: true in the config prevented this issue.  In 5.4.0, readOnly: true raises the make_dir() error.  We reverted back to 5.3.5, and everything works fine....

```        
var config = Realm.Configuration (
            fileURL: Bundle.init(identifier: "your.id.here")?.url(forResource: "realmFileName", withExtension: "realm"),
            readOnly: true,
            schemaVersion: 5,
            migrationBlock: { migration, oldSchemaVersion in
                // Do nothing....
            }
        )
```

**Comment by joaopdcgarcia** [comment]
how is this closed? we're seeing the same issue on RealmSwift
