### ISSUE TITLE
Carthage build fails 2.5.0 version with Xcode 8.3

### ISSUE THREAD

**Issue by iceman201** [realm/realm-cocoa#4810]
#### Description

Carthage build fails 2.5.0 version with Xcode 8.3

#### Log

```
Liguos-MacBook-Pro:ThorCordova-ios Liguo_Jiao$ carthage update --platform iOS
*** Fetching realm-cocoa
*** Checking out Reachability.swift at "v3"
*** Downloading realm-cocoa.framework binary at "v2.5.0"
*** Checking out RxSwift at "3.0.0"
*** xcodebuild output can be found in /var/folders/97/d0f1p2h95svff0_t5vmjqtwh0000gn/T/carthage-xcodebuild.o6ww8F.log
*** Building scheme "Reachability" in Reachability.xcodeproj
*** Building scheme "Realm" in Realm.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/Liguo_Jiao/work_project/thor/plugins-src/ThorCordova-ios/Carthage/Checkouts/realm-cocoa/Carthage/Realm.xcworkspace -scheme Realm -configuration Release -derivedDataPath /Users/Liguo_Jiao/Library/Caches/org.carthage.CarthageKit/DerivedData/realm-cocoa/v2.5.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/97/d0f1p2h95svff0_t5vmjqtwh0000gn/T/carthage-xcodebuild.o6ww8F.log
Liguos-MacBook-Pro:ThorCordova-ios Liguo_Jiao$ vim /var/folders/97/d0f1p2h95svff0_t5vmjqtwh0000gn/T/carthage-xcodebuild.o6ww8F.log

/Users/Liguo_Jiao/work_project/thor/plugins-src/ThorCordova-ios/Carthage/Checkouts/realm-cocoa/Realm/module.modulemap:1:18: error: redefinition of module 'Realm'
framework module Realm {
                 ^
/Users/Liguo_Jiao/Library/Caches/org.carthage.CarthageKit/DerivedData/realm-cocoa/v2.5.0/Build/Intermediates/Realm.build/Release-iphoneos/Realm.build/module.modulemap:1:18: note: previously defined here
framework module Realm {
                 ^
1 error generated.

** BUILD FAILED **


The following build commands failed:
        CompileC /Users/Liguo_Jiao/Library/Caches/org.carthage.CarthageKit/DerivedData/realm-cocoa/v2.5.0/Build/Intermediates/Realm.build/Release-iphoneos/Realm.build/Objects-normal/armv7/RLMAuthResponseModel.o Realm/RLMAuthResponseModel.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

#### Tooling

- Realm version: 2.5.0
- Xcode version: 8.3
- iOS/OSX version: iOS 10
- Dependency manager + version: ?

**Comment by istx25** [comment]
Thanks for reaching out, @iceman201. 

Would you be able to let us know which version of Carthage you're using? My initial thought was to try running `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and `carthage update` again. If that doesn't work, please make sure you're running the latest version of Carthage.

Looking forward to hearing from you.

**Comment by istx25** [comment]
Do you need any more help with this?

**Comment by akolov** [comment]
I can confirm that the issue is reproducible on multiple machines with the latest version of Carthage (0.20.1) and after deleting it's caches.

**Comment by jpsim** [comment]
Seeing as how we cut the 2.5.1 release with Carthage 0.20.1 with Xcode 8.3, I'm having trouble identifying what's different in @akolov and @iceman201's configurations that would cause things to work for us, but fail for them.

@akolov @iceman201 step-by-step instructions on a fresh macOS installation to produce this failure might be the next step in identifying if something else is at fault here.

**Comment by LeonidKokhnovich** [comment]
Have the same issue, but with Facebook SDK.

**Comment by cwalo** [comment]
I ran into this as well with 2.5.1. I deleted the project from Checkouts/ and the compiled frameworks from/Builds/ then ran `carthage update --no-use-binaries`

**Comment by tinpont** [comment]
I ran into the same issue, but solved by @cwalo's method. Thanks, @cwalo .

**Comment by jpsim** [comment]
Our Carthage binaries are always produced with the latest stable version of Xcode, and the Swift compiler requires that all linked modules be built with the same version of the compiler.
