### ISSUE TITLE
Question: How to add an unmanaged RealmObject to a managed RealmObject's RLMArray if the managed object has no primary key?

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-cocoa#4816]
I'm really a bystander in regards to iOS development as a whole, so I can't even write the proper syntax in Swift to illustrate my question; please forgive me on that part.

We had a RealmObject that does not have primary key, but it was already persisted to Realm.

We also had another RealmObject that did have a primary key, but it wasn't yet persisted to Realm.

So we wanted to add the unmanaged RealmObject to the managed RealmObject.

In Realm-Java, you'd do it like this:

    // in write transaction
    MyObject myObject = realm.copyToRealmOrUpdate(unmanagedObj);
    theManagedObj.getListOfMyObject().add(myObject);

However, Realm-Cocoa's `realm.addObject()` seems to return `void`, meaning you don't get the managed object.

If I do not have a primary key for the object, then how can I access the newly inserted managed object so that I can set it as a member of a managed object's list? I can't query it back as I can't really identify it, but I do not get the managed object.

Sooo... how do I set up relation with an unmanaged object that has no primary key?

(I did check the documentation but didn't find this example)

**Comment by jpsim** [comment]
Hi @Zhuinden, we actually "promote" unmanaged Realm objects to managed ones when you add them to a Realm. For example:

```swift
class Dog: Object {
  dynamic var name = ""
}

// Create unmanaged Realm object
let myDog = Dog()
myDog.name = "Rex"
myDog.realm == nil // true

// Get the default Realm
let realm = try! Realm()

// Add myDog to the Realm
try! realm.write {
  realm.add(myDog)
}

// myDog is now a 'managed' Realm object
myDog.realm == realm // true
```

**Comment by Zhuinden** [comment]
Oh, so the input unmanaged object becomes the managed proxy. Interesting. 

How does it make the input become the proxy? That might be a silly question, but I have java's generated RealmProxy class in my head, and this is clearly something very different.

**Comment by bdash** [comment]
@Zhuinden, when adding an unmanaged object to a Realm we [change the class of the object](https://github.com/realm/realm-cocoa/blob/f0b120d9cc9f16ea20286d95d0fd153198c1bda8/Realm/RLMObjectStore.mm#L319-L320#L319-L320) to that of our managed object accessor class. The managed and unmanaged accessor classes are subclasses of the user-declared object class that we [define at runtime](https://github.com/realm/realm-cocoa/blob/f0b120d9cc9f16ea20286d95d0fd153198c1bda8/Realm/RLMAccessor.mm#L560-L595), with getters / setters overridden where necessary to achieve the desired behavior (for example, to read / write from the underlying Realm for managed accessor classes).

**Comment by Zhuinden** [comment]
A-ha! Proxies are generated runtime, essentially like dynamic method invocation / reflection in Java.

Thank you for the answers! :smile:
