### ISSUE TITLE
Support Xcode Version 8.3 (8E162)

### ISSUE THREAD

**Issue by ecsoya** [realm/realm-cocoa#4819]
Hi, 

Can you upgrade the RealmSwift to support the lastest Xcode Version 8.3 (8E162)?

**Comment by bdash** [comment]
[Realm Swift v2.5.0](https://github.com/realm/realm-cocoa/releases/tag/v2.5.0), released on March 28th, support Swift 3.1. Are you encountering some issue when attempting to use it?

**Comment by ecsoya** [comment]
Thank you

I am planing to upgrade my app to using xcode 8.3.
