### ISSUE TITLE
Crash blocking

### ISSUE THREAD

**Issue by Patrick-Remy** [realm/realm-cocoa#4821]
## Goals
In some cases, I have to replace new data before drawing the view. To not ending in an endless notification call I am using commitWrite(withoutNotifying:). Therefore I have to use the main thread, because addNotificationBlock is only available in a runloop and I have to commit the write on the same realm - which have to be called from the same thread - to use withoutNotifying.
 
The disadvantage is that the main thread is blocking the UI.

## Expected Results
If data of type SomeClass changes and some case is given, the data should be replaced by a server response. After that the view should draw with the most recent data.

## Actual Results
The application crashes with this backtrace:
https://pastebin.com/DD6JEndN

## Code Sample
```swift
override func viewDidLoad() {
    let realm = try! Realm()
    let notificationToken = realm.objects(SomeClass.self).addNotificationBlock { _ in
        if someCase {
           self.updateDataWithoutNotifying(realm, notificationToken: notificationToken) {
               self.redraw()
           }
        }
    }
}

private func updateDataWithoutNotifying(_ realm: Realm, notificationToken: NotificationToken, completionHandler: () -> ()) {
    Request(...) { response in 
        // viewDidLoad runs in main queue
        OperationQueue.main.addOperation {
            defer {
                completionHandler()
            }
            realm.beginWrite() 
            Storage.someClass = SomeClass(response)
            do {
                try realm.commitWrite(withoutNotifying: [notificationToken])
            } catch {
                if realm.isInWriteTransaction {
                    realm.cancelWrite()
                }
                print("Error!")
            }
        }
    }
}
```

## Version of Realm and Tooling
Realm framework version: 2.5.0

Realm Object Server version: -

Xcode version: 8.3

iOS/OSX version: iOS 10.3

Dependency manager + version: Cocoapods 1.2.0

**Comment by istx25** [comment]
Hi @Patrick-Remy. Thanks for reaching out about this. I wanted to let you know that we've received your issue and that someone will follow-up with you soon with a solution or further questions.

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. The crash you're seeing looks like a bug. Can you create a minimal reproduction case and send it to help@realm.io? Thanks.

**Comment by jpsim** [comment]
@Patrick-Remy thanks for filing this. I'll be closing the ticket since we haven't heard back from you in a few weeks. Please open a new issue if you see similar issues with more recent releases, such as 2.6 or later.
