### ISSUE TITLE
Cannot open Realm file after updating to Xcode 8 and Realm 2.4.

### ISSUE THREAD

**Issue by SusanKern** [realm/realm-cocoa#4823]
## Goals
We have an existing app with tens of thousands of users.  For this release, we need to update codebase to Xcode 8.

## Expected Results
The updated app would be able to read in Realm database created with earlier version.

## Actual Results

```2017-04-05 14:57:07.086792 gPACT[24937:10010912] +[RealmHelper startupDatabase] [Line 30]Path to Realm: file:///var/mobile/Containers/Data/Application/EBD97003-D570-4306-833B-2A4349F669FF/Documents/default.realm
2017-04-05 14:57:18.357427 gPACT[24937:10010912] __28+[APIManager sharedInstance]_block_invoke [Line 41]Server Environment: Development
2017-04-05 14:57:18.357566 gPACT[24937:10010912] __28+[APIManager sharedInstance]_block_invoke [Line 42]Server URL: http://pact-api.lgs.littlegreensoftware.com:3000/api/
2017-04-05 14:57:18.359510 gPACT[24937:10010912] -[APIManager loadAccessToken] [Line 479]Loading accessToken q9hLentGeS3jEL2smu6dcIyKls8fKH59FDh3AvDG6eXcUfKsUkoXRUwjqWPnDxBZ
2017-04-05 14:57:18.510652 gPACT[24937:10010912] *** Terminating app due to uncaught exception 'RLMException', reason: '/var/mobile/Containers/Data/Application/EBD97003-D570-4306-833B-2A4349F669FF/Documents/default.realm: Unable to open a realm at path '/var/mobile/Containers/Data/Application/EBD97003-D570-4306-833B-2A4349F669FF/Documents/default.realm': Not a Realm file.'
*** First throw call stack:
(0x18ed141c0 0x18d74c55c 0x10064611c 0x10062fb64 0x10063092c 0x10062f7f4 0x1005bf4bc 0x1000a5030 0x1001116d0 0x100110174 0x10010f678 0x10010f634 0x10191521c 0x10191604c 0x10010f710 0x100104578 0x100104c08 0x19505ed68 0x1951ae83c 0x1951ae9b0 0x1951ae584 0x194ebc848 0x194ee8f4c 0x1001078e0 0x10010798c 0x19505ed68 0x1951ae83c 0x1951ae584 0x19505ea0c 0x1951ae83c 0x1951ae9b0 0x1951ae584 0x19505dd0c 0x195315468 0x1000aaa30 0x1000aa864 0x1000aa584 0x1000a9e4c 0x194bce61c 0x194dded60 0x194de4ad0 0x194df9270 0x194de1ab4 0x1908b5904 0x1908b5770 0x1908b5b18 0x18ecc2278 0x18ecc1bc0 0x18ecbf7c0 0x18ebee048 0x194bc77cc 0x194bc2550 0x1000837e4 0x18dbd05b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```
The Realm database cannot be opened by Realm Browser.  The error message is:
`'default' could not be opened.  It may be encrypted, or it isn't in a compatible file format." `
Note that the database is not encrypted. 

## Steps to Reproduce
The crash happens the first time the app accesses the database, using `[RLMRealm defaultRealm];`.  Actual database migration code was never run - the crash happened before that.  

## Code Sample
This is a very large app - I'm not sure how to get you a small sample.  However, I have sent the realm database in a separate email.

## Version of Realm and Tooling
The previous version of Realm (Objective-C) was 2.0.  The current version is 2.4.4.

Realm framework version: ?

Xcode version: 
The previous version was Xcode 7.4.  The current version is Xcode 8.2.

iOS/OSX version: 
10.2

Dependency manager + version:  CocoaPods

**Comment by SusanKern** [comment]
I have resolved this problem.  Apparently the database created in that earlier version was encrypted, even though the flag  REALM_DISABLE_ENCRYPTION was set.

**Comment by jpsim** [comment]
I'm glad you were able to resolve this, although I'm puzzled as to why setting `REALM_DISABLE_ENCRYPTION` would still encrypt the Realm. If you can manage to reproduce that, please share steps for us to do so as well by filing a new issue. Thanks!
