### ISSUE TITLE
delete data error

### ISSUE THREAD

**Issue by lyjpost** [realm/realm-cocoa#4825]
object->_row.get_table()->move_last_over(object->_row.get_index());

eg:I delete the third data in a table,the last data will move to third position.how to resolve this problem?

**Comment by bdash** [comment]
Objects in a Realm are inherently unordered. If you wish to retrieve objects in a specific order that you control, you can do so by inserting them into a `List`/`RLMArray` property of an object, or by sorting the `Results`/`RLMResults` that you use to retrieve them.

**Comment by lyjpost** [comment]
Okay,I try to sort。Thank you very much！
