### ISSUE TITLE
iOS Static Library is 490.3 Megabytes

### ISSUE THREAD

**Issue by RyanCopley** [realm/realm-cocoa#4829]
## Goals
To pre-compile realm as a static library for iOS. 

## Expected Results
A static library under 100 megabytes. Preferably under just a few megabytes...

## Actual Results
<img width="561" alt="screen shot 2017-04-06 at 6 39 54 pm" src="https://cloud.githubusercontent.com/assets/819591/24778413/75403abe-1af8-11e7-933c-35a9adb76847.png">

## Steps to Reproduce
```bash
sh build.sh ios-static
```

## Version of Realm and Tooling
Commit 899c0ada49e178e917e69680949f494ffe7f2f8a
Xcode version: 8.3
OS X version: 10.12.3 (16D32)

**Comment by tgoyne** [comment]
Xcode 8.3.1 fixes a bug introduced in 8.3.0 that results in bitcode being far larger than it should be.

**Comment by RyanCopley** [comment]
Oh gosh. Updating now...

**Comment by RyanCopley** [comment]
@tgoyne On 8.3.1 it is now 498.9 MB... wrong direction :s

**Comment by RyanCopley** [comment]
I disabled bitcode and got it down to 326.1 MB, but that's still really large.

**Comment by bdash** [comment]
I'm guessing a large portion of the file size is debug symbols. The object files within the static framework contain DWARF debug symbols. When linked into your built application these symbols will be included in your app's `.dSYM` bundle rather than being part of the final linked image.

**Comment by RyanCopley** [comment]
Agh. I was hoping to keep a copy of it in the git repo to reduce build times but github has a max filesize of 100 megabytes. I guess I can submodule and build it once at compile time.

**Comment by bdash** [comment]
You could strip debug symbols (`strip -S`) to get the binary below 100MB, with the tradeoff being you'd not be able to step into Realm's source files in the debugger.

**Comment by TimOliver** [comment]
I hope that answered your question @RyanCopley. Sadly when we bake in the debug symbols and the bitcode, the size of the static framework binary grows to a pretty epic size.

Something else you might be interested in trying is the [Git Large File Storage integration for GitHub](https://git-lfs.github.com).

In any case, I'm going to close this issue now. Feel free to re-open it if you have anymore questions. Thanks! :)
