### ISSUE TITLE
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1744830464 offset: 0"

### ISSUE THREAD

**Issue by hyouuu** [realm/realm-cocoa#4832]
**Bugs**: Crashes on launch for some users.
> fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1744830464 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1744830464 offset: 0, Error Code=9}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.48/src/swift/stdlib/public/core/ErrorType.swift, line 182

## Goals
Not crashing

## Expected Results
Not crashing

## Actual Results
Some user crash on app launch

## Steps to Reproduce
Cannot reproduce on my test device

## Code Sample
```swift
results = try! Realm()
            .objects(NoteR.self)
            .sorted(byKeyPath: "date", ascending: dateAscending)
```

## Version of Realm and Tooling

- Realm framework version: 2.5.1
- Realm Object Server version: NA
- Xcode version: 8.3
- iOS/OSX version: 10.3
- Dependency manager + version: CocoaPod 1.2.0

## Further information

As asked in https://github.com/realm/realm-cocoa/issues/4820, the answers are:
Can you reproduce this problem yourself at all, or has it only been reported by users?
Only by users

Can you reproduce it on demand, or does it only appear to happen at random?
For the affected users it happen constantly

Can you describe how your application uses Realm with respect to multiple threads. For instance:
a. Do you only use Realm on the main thread? Yes
b. Do you use Realm on dispatch queues? No
c. Do you use Realm on NSOperationQueues? No
d. Do you use Realm on background threads that you've created? No
e. On which threads / queues do you write to the Realm? Main
f. On which threads / queues do you read from the Realm? Main

Is your Realm file only accessed by a single process at a time? Multiple process may be involved if you have multiple apps in an app group that share a Realm, or if you have application extensions that share a Realm with your main app.
Only one app

How frequently do you write to the Realm? 
Not frequent

Do you have multiple threads attempting to write to the Realm simultaneously?
No

Have you tested with the most recent version of Realm? v2.5.0 includes a fix for a problem that could lead to unexpected file size growth when you have write contention (i.e., multiple threads attempting to write to the Realm concurrently for an extended period of time).
Using 2.5.1

cc @bdash 

Stacktrace - Pendo is my app's name, and RootVC._reloadData calls fetch(), which looks like:
```swift
func fetch() {
    results = try! Realm()
            .objects(NoteR.self)
            .sorted(byKeyPath: "date", ascending: dateAscending)
}
```

```
0	libswiftCore.dylib	
__hidden#17347_ line 134
specialized _assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never
1	libswiftCore.dylib	
__hidden#18979_ line 221
Error<A where ...>._code.getter
2	libswiftCore.dylib	
swift_errorInMain + 26
3	Pendo	
(Missing)
4	Pendo	
RootVC.swift line 0
specialized RootVC._reloadData(Bool, src : String) -> ()
5	Pendo	
RootVC.swift line 0
specialized RootVC.refetchData(String) -> ()
6	Pendo	
RootVC.swift line 0
RootVC.init(collectionViewLayout : UICollectionViewLayout, moc : NSManagedObjectContext?) -> RootVC
7	Pendo	
PendoAppDelegate.swift line 98
specialized PendoAppDelegate.application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool
8	Pendo	
PendoAppDelegate.swift line 0
@objc PendoAppDelegate.application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool
9
UIKit	
-[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 380
22
UIKit	
UIApplicationMain + 208
23	Pendo	
DetailVC+Cmd.swift line 17
main
24	libdyld.dylib	
start + 4
```

**Comment by istx25** [comment]
Hi @hyouuu. Thanks for filing this separate issue. We'll review what you've shared and someone will follow-up with you where necessary.

**Comment by bdash** [comment]
A few more questions:
1. Do you use Realm's collection or object notifications at all?
2. Are you 100% sure you're never using Realm off the main thread? You're not using Realm in any callbacks from networking libraries, or any other asynchronous work?

**Comment by hyouuu** [comment]
1. I don't use Realm collection - for a 1-N relationship A-B, I just store B's IDs in a comma separated string field and manually retrieve them; I don't use object notification either.

2. Correct in that I only write or read Realm in main thread. Because the issues Realm has with multi-threading, my approach is that whenever I get network callback etc off main thread, I'll create a Realm object A, then call a centralized rlmAdd() function which always dispatch to main, then use Object(value:) to copy the stuff from A to the storage

**Comment by bdash** [comment]
Would you mind sharing code snippets that are representative of what you mention in 2 (both moving the data from background thread to main thread to write it, and moving it from main thread to background thread to do work on it)?

**Comment by hyouuu** [comment]
Model looks like:
`public class NoteR: RealmSwift.Object {
    public dynamic var id = uid() // uuid generator
    public dynamic var update = Date().i // timeSince1970 Int value
    public dynamic var title = ""
}`
rlmAdd() looks like:
`public func rlmAdd(_ src: String,
                   obj: NoteR,
                   touchUpdate: Bool = true) {
    toMain {
        pr("rlmAdd src:\(src) touchUpdate:\(touchUpdate) note:\n\(obj)")
        if let rlmExistingNote = rlm().object(ofType: NoteR.self, forPrimaryKey: obj.id) {
            // If existing obj has newer update, means there's some race condition on the cloud - we should re-trigger sync
            if rlmExistingNote.update > obj.update {
                delay2Sec {
                    Syncer.one.schedule("rlmAdd note conflict update")
                }
            }
        }

        if touchUpdate {
            obj.update = Date().i
        }
        rlmWrite {
            if obj.id.isEmpty {
                fail("note id should never be empty")
                obj.id = uid()
            }
            rlm().add(NoteR(value: obj), update: true)
        }
}`

When I get a NoteR from cloud for example, I call:
`func upsertLocalNote(_ note: NoteR) {
        pr("upsertLocalNote:\(note)")
        removeCacheFor(id: note.id)
        
        rlmAdd("upsertLocalNote", obj: note, touchUpdate: false)
        checkEditingConflict(note)
        delayedReloadData(false, src: "upsertLocalNote \(note.id)")
    }
`

**Comment by hyouuu** [comment]
DataSource:
```
class NoteDataSource {

    var results: Results<NoteR>?
    var searchResults: Results<NoteR>?

    func fetch(_ src: String) {
        guard isOnMain() else {
            toMain {
                self.fetch(src)
            }
            return
        }
        let dateAscending = false

        results = rlm()
            .objects(NoteR.self)
            .sorted(byKeyPath: "date", ascending: dateAscending)
        postNotif(notifNoteCountUpdated, obj: results?.count)
    }

    func count() -> Int {
        guard let results = results else {
            fetch("notesCount 0")
            return 0
        }
        return results.count
    }

    func at(_ index: Int) -> NoteR? {
        // Synchronize
        guard assertOnMain() else { return nil }

        if let searchResults = searchResults {
            guard searchResults.count > index else { return nil }
            return NoteR(value: searchResults[index])
        }
        guard let results = results else {
            fetch("at()")
            return nil
        }
        guard results.count > index else { return nil }
        return NoteR(value: results[index])
    }
}
```

**Comment by hyouuu** [comment]
Sorry @bdash there is one occurrence where I read Realm stuff on background queue:
```
  func bgNotes(_ completion: @escaping ([NoteR]) -> ()) {
        guard isOnSerial() else {
            // Wait for rlm to catch up
            delayAnime {
                asyncSerial {
                    self.bgNotes(completion)
                }
            }
            return
        }

        var results = [NoteR]()
        let dateAscending = false
        // Note: Need to refetch every time this is used, because asyncSerial still can't gurantee the same thread (although the same queue)
        let bgRlmResults = rlm()
            .objects(NoteR.self)
            .sorted(byKeyPath: "date", ascending: dateAscending)
        guard bgRlmResults.count > 0 else {
            completion(results)
            return
        }

        results = bgRlmResults.toArray(first: nil)
        postNotif(notifNoteCountUpdated, obj: results.count)
        pr("notes count:\(results.count)")

        completion(results)
    }
```

The toArray basically does a copy, which is expensive but I was trying to avoid cross thread issues:
```
public extension Results {
    func toArray(first: Int?) -> [NoteR] {
        guard let first = first, first > 0 else {
            return self.map { NoteR(value: $0) }
        }

        var notes = [NoteR]()
        for i in 0 ..< Swift.min(self.count, first) {
            notes.append(NoteR(value: self[i]))
        }
        return notes
    }
}
```

**Comment by hyouuu** [comment]
Of course, any suggestions to how to improve the efficiency of using Realm are welcome ;)

**Comment by bdash** [comment]
Any Realm-related work on a dispatch queue that's not inside an explicit autorelease pool has the potential to cause file size growth. The reason for this is that each Realm accessor object (`Realm`, `Object` instances, `Results`, `List`, etc.) has a reference to a specific version of the data within the Realm file. That version of data within the Realm file can only be reclaimed and reused by future write transactions once all accessor objects that refer to it have been deallocated. If these objects are not allocated within explicit autorelease pools when on a dispatch queue, they will escape into the dispatch queues autorelease pool. GCD only drains the queue-level autorelease pools relatively infrequently, which can result in the lifetimes of these objects (and thus of the older versions of data in the Realm file) being significantly longer than you expect. Your `bgNotes` function has this issue. I'd suggest fixing this, auditing your code to ensure there are no other places with this problem, and re-testing to see if the file size growth problem can re-occur.

**Comment by hyouuu** [comment]
Thanks! Could you give an example how I could make bgNotes in an autorelease pool?

**Comment by bdash** [comment]
Wrap an `autoreleasepool { … }` around the entirety of the body of the function (and any others that access Realm on background queues).

**Comment by hyouuu** [comment]
Thanks! I'll push this to the next app update and report back if any issues occur.

**Comment by bdash** [comment]
Do be aware that this should prevent the file size growth that leads to the failure to open the Realm file. It won't fix any Realm files that area already in that state. To recover from that situation you'd need to catch the error in question (`addressSpaceExhausted`) and move aside the file.

**Comment by aalenliang** [comment]
@bdash Can you be more specific about what to do when I catch the `addressSpaceExhausted` error?

**Comment by bdash** [comment]
Remove the file that is too large to be opened.

Compact on launch will help to mitigate any surprising file size growth, but in general the solution is to avoid the surprising growth in the first place using the techniques discussed in the documentation, this issue, and other similar issues on GitHub.

**Comment by aalenliang** [comment]
@bdash Thank you!
