### ISSUE TITLE
Update the release 2.5.1 with the new HASH commit

### ISSUE THREAD

**Issue by huy-le** [realm/realm-cocoa#4833]
## Goals
Release 2.5.1 should point to a correct HASH commit, otherwise, the use-submodule in Carthage will break because the HASH does not exist anymore

## Expected Results
Release 2.5.1 should point to the HASH `721c4f8` commit in history.

## Actual Results
Release 2.5.1 point to `f8d9bca`, which disappeared from the history.

**Comment by bdash** [comment]
Can you elaborate on what problem you're having?

The tag [v2.5.1](https://github.com/realm/realm-cocoa/tree/v2.5.1) points at f8d9bca, which [exists in the realm-cocoa Git repository](https://github.com/realm/realm-cocoa/commits/v2.5.1). 721c4f8 is a commit that updated the version number and change log on master in preparation for the release.

**Comment by huy-le** [comment]
Hmm, sorry, maybe this is the problem of carthage. I cannot reproduce it again. Thanks for your help.
