### ISSUE TITLE
Ignored property of UIImage type is not ignored.

### ISSUE THREAD

**Issue by khambir** [realm/realm-cocoa#4835]
## Goals
Create ignored property for getting UIImage from persisted property of Data() type

## Expected Results
user?.userpic - UIImage from Data

## Actual Results

> Property 'userpic' is declared as 'UIImage', which is not a supported RLMObject property type. All properties must be primitives, NSString, NSDate, NSData, NSNumber, RLMArray, RLMLinkingObjects, or subclasses of RLMObject.

## Code Sample

```
import Foundation
import RealmSwift
import UIKit


internal class User: Object {
    
    // MARK: - Persisted properties
    private dynamic var userpicData = Data()
    
    // MARK: - Non-persisted properties
    internal var userpic: UIImage? {
        get {
            return UIImage(data: userpicData)
        }
        set {
            try! CHDataStore.realm.write {
                userpicData = (newValue ?? UIImage()).data
            }
        }
    }
    
    // MARK: - Model meta information
    override class func ignoredProperties() -> [String] {
        return ["userPic"]
    }
    
}
```

Realm framework version: 2.5.1

Xcode version: 8.3 (8E162)

iOS/OSX version: iOS 10

**Comment by nirinchev** [comment]
May be an oversight, but shouldn't the casing of the property be the same? Looks like your property is called `userpic` (lowercase), while you're telling Realm to ignore `userPic` (camelCase).

**Comment by khambir** [comment]
@nirinchev, check my code above. As can you see, I have two different properties: **userpicData** & **userpic**. I am using completely different names.

**Comment by nirinchev** [comment]
Right. However you're telling Realm to ignore userPic (uppercase **P**) while your property is called userpic (lowercase **p**).

**Comment by khambir** [comment]
Really, it is my silly fault. Thank you.

**Comment by nirinchev** [comment]
No worries, glad I could help!
