### ISSUE TITLE
How to create schema dynamically with realm?

### ISSUE THREAD

**Issue by zhaoxy2850** [realm/realm-cocoa#4836]
Hi guys, I'm looking for a way to create schema dynamically with realm. 

I want to create many tables with different names but same schema, like conversation data with different users in different tables. I tried to create subclass at runtime but it didn't work well.

I wonder is there a way to do it with realm?

Thank you very much!

**Comment by istx25** [comment]
Hey @zhaoxy2850, thanks for reaching out about this. We don't have any public support for creating schemas at runtime at this time but I recommend reading through [this issue](https://github.com/realm/realm-cocoa/issues/4811). 

As suggested by @bdash in #4811, if you want to rely on Realm internals (which are subject to change at any time), you could likely use -[RLMRealmConfiguration setCustomSchema:] and then pass the RLMRealmConfiguration instance with the custom schema configured on it to +[RLMRealm realmWithConfiguration:error:]. You can see examples of this in our unit tests.

If you have any further questions, please feel free to ask and we'll try to help where possible.

**Comment by zhaoxy2850** [comment]
@istx25 Thanks, I will try it.

**Comment by hyDevil1109** [comment]
@istx25 I have tried your method. But it seems that “customSchema”  is a readonly property. I'm sure  that my realm is the latest version. I wonder how to deal with it.

`        RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
        config.fileURL = [NSURL URLWithString:path];
        config.readOnly = NO;
        RLMSchema *schema = [[RLMSchema alloc] init];
        [config setCustomSchema:schema];`

error :  No visible @interface for 'RLMRealmConfiguration' declares the selector 'setCustomSchema:

**Comment by bontoJR** [comment]
Hey @istx25,

I am trying to do the same, anyway, to solve that issue you need add:

```
#import <Realm/RLMRealmConfiguration_Private.h>
```

At that point you have the `customSchema` property available.
