### ISSUE TITLE
realm objects cannot call functions ?

### ISSUE THREAD

**Issue by khanhankkhan** [realm/realm-cocoa#4838]
I have a realm object with two properties

    @property NSDate *start;
    @property NSDate *end;

I wrote a function for my object

    -(BOOL) date_is_safe
    {
        return(_start && _end);
    }

the function date_is_safe always returns false. However if I instead type

    if(user.start && user.end)

manually, my conditional statement returns true.

Is this supposed to happen?

## Goals

have @property attributes on a Realm Object that I've made, and write functions that access those properties
## Expected Results

I expect my class instance to read it's own @property inside its member function

in the code example, i would want  'safe' to be printed to console

## Actual Results

'not safe' is printed.

@properties appear undefined at the scope of the member function.

## Steps to Reproduce

Make a class with 2 variables and a function

@interface User : RLMObject
    @property NSDate *start;
    @property NSDate *end;

    -(BOOL) date_is_safe;
    {
        return(_start && _end);
    }

@end 

## Code Sample

Save a user object with a start & end

	RLMRealm *r = [RLMRealm defaultRealm];
	[r beginWriteTransaction];

        User *u = [[User alloc] init];
        u.id = @"1";
        u.start = [NSDate date];
        u.end = [NSDate date];

	[r commitWriteTransaction];

		User *myuser = [User objectForPrimaryKey:@"1"];
                if([myuser date_is_safe])
                    printf("\n safe \n");
                else 
                    printf("\n not safe \n");

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us.

Realm works by swizzling the setters and getters of `RLMObject` subclasses to point to code that works with the underlying database engine. This means it's never safe to work with the ivars of a Realm object's properties unless (1) the property is explicitly marked as ignored or (2) the object is never added to a Realm.

**Comment by khanhankkhan** [comment]
hi @austinzheng thanks. i should've made my comment more generic - i'm actually not using iVars, I am using @property

**Comment by austinzheng** [comment]
I know you're using properties. When you write code like

```
-(BOOL) date_is_safe
{
    return(_start && _end);
}
```

you are accessing the ivars that Xcode automatically synthesizes to back those properties.

When you call `user.start` or `user.end` instead, you are sending messages to the property getters, which is why that code works.

**Comment by khanhankkhan** [comment]
thanks @austinzheng - so shall I not write functions on my class?  The reason i am writing functions like this is so my class is easier to use, and things that come up often like 'type=cat' or 'type=dog' don't get mis-typed by users of my class, so instead i wanted to have something like 
 
    -(BOOL) is_cat

etc... 

It sounds like i should manually type of things like [user.type isEqualToString:@"cat"]; instead of writing a function?

**Comment by austinzheng** [comment]
You can write methods on your class. What you _cannot_ do is access ivars in those methods (for example, `_start` and `_end`).

**Comment by khanhankkhan** [comment]
thank you. would it be advisable to have global functions like      

     user_is_cat(NSString *id)
    {
       User *myuser = [User objectForPrimaryKey:id];
       if([myuser isEqualToString:@"cat"])
         return true;
       else
         return false;
    }

**Comment by austinzheng** [comment]
Realm is indifferent as to whether you use global functions or methods. You are free to use whichever you prefer.

**Comment by khanhankkhan** [comment]
i'd prefer to user a method attached to my object.  could i write an object on User like 


     -(BOOL) is_safe:(NSString*)id
    {
       User *myuser = [User objectForPrimaryKey:id];
       if(myuser.start && myuser.end)
         return true;
       else
         return false;
    }

 then implement like


   if([user is_safe:user.id])
     ....

**Comment by austinzheng** [comment]
All of those things are safe.

Just don't write any variable names in your functions or methods that begin with an underscore and you should be fine.
