### ISSUE TITLE
binding_callback_thread_observer.h file not found

### ISSUE THREAD

**Issue by wenlanhuitai** [realm/realm-cocoa#4839]
xcode version 8.1  , swift 3.0

Yesterday I updated realm swift by  "pod update",  then The program compiled error binding_callback_thread_observer.h file not found...

**Comment by istx25** [comment]
Hi @wenlanhuitai. Please copy the issue template from https://github.com/realm/realm-cocoa/issues/new and post it here with the fields filled. We will need more information in order to be able to help you. Thanks.

**Comment by wenlanhuitai** [comment]
thanks, I have solved the problem:

#!/usr/bin/env bash
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update

**Comment by philku79** [comment]
I had the same issue. the mention solution didn't fix it.

**Comment by TimOliver** [comment]
@wenlanhuitai Cool! Glad to hear you fixed it! Thanks for letting us know.

@philku79 You can also try `pod deintegrate` to completely remove CocoaPods from the Xcode project and then `pod update` to force a complete reinstall from scratch.

If that doesn't work, please file a new issue and be sure to fill out our form with as much information as possible about your current setup. Thanks! :)
