### ISSUE TITLE
Deleting Realm --> then recreating it causes crash "Object has been deleted or invalidated"

### ISSUE THREAD

**Issue by danieldelouya** [realm/realm-cocoa#4843]
## Goals

When a user logs out of the app, I want to delete everything on realm in case a new user logs in right after. I can do that using the following code when user taps on logout button. 
```
 try realm.write {
    realm.deleteAll()
}
```
Now, if a new user logs in (or the existing user), then i get the exception "Object has been deleted or invalidated". 

How do I create new realm objects again? I'm using a realm model throughout the app called rUser that i instantiate globally in my xcode project, so I'm suspecting that's the one that needs to be reinstantiated? I just don't know how. Or maybe I'm completely wrong. 

## Version of Realm and Tooling

Realm framework version: ?
3.1

Realm Object Server version: ?
-
Xcode version: ?
8.3

iOS/OSX version: ?
10.3.1

Dependency manager + version: ?
-

**Comment by mamaral** [comment]
+1

**Comment by danieldelouya** [comment]
Anyone at Realm care to help?

**Comment by istx25** [comment]
My apologies for the delay in getting back to you, @danieldelouya. Our waiting times are typically longer during the weekend since our support and engineers generally only work M-F. However, with that said, I wanted to let you know that we've received your issue and that someone will follow-up with you soon (now that we've started the week).

In the meantime, would you please provide these values:

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining some of these versions.

- Realm framework version: ?
- Realm Object Server version: ?
- Xcode version: ?
- iOS/OSX version: ?
- Dependency manager + version: ?

**Comment by austinzheng** [comment]
Once an object is deleted from a Realm, attempts to access it will cause an exception to be thrown (as you've already seen).

You can either delete objects by their model class instead of deleting all objects (sparing your user object from being deleted). This a straightforward solution, but only works well if you don't have many model classes.

Otherwise, you can initialize a new user object, add it to your newly-cleared Realm, and then assign that new user object to your global `rUser` variable. As long as you don't use any reference to the old `rUser` object after your Realm has been cleared, you should be fine.

**Comment by danieldelouya** [comment]
Thanks @austinzheng 👍  I'll give it a shot and get back to you. Cheers

**Comment by mamaral** [comment]
@austinzheng Regarding the comment:

> As long as you don't use any reference to the old rUser object after your Realm has been cleared, you should be fine.

Does this also apply to `RLMResults`?

If I have a `RLMResults` property for all my objects, delete all the objects, and then fetch them again from the server (effectively getting the same objects back that I just deleted) and set the new results for [MyModel allObjects] on this property, it appears as though I get the same issue as the newly created objects are still the "same" as the deleted ones?

**Comment by danieldelouya** [comment]
@austinzheng 
Could not get approach two to work, but since I actually only need to reset the rUser model class, approach one seems to fit better. However, how do i set all objects in rUser til nil if I'm using a primary key? 

I can set all other values to nil except the primary key. Getting the exception: 
'Primary key can't be changed after an object is inserted.'

**Comment by danieldelouya** [comment]
@austinzheng  Turns out i could not get to work

 ("You can either delete objects by their model class instead of deleting all objects (sparing your user object from being deleted). This a straightforward solution, but only works well if you don't have many model classes".). 

How do you delete a model class if it's based on a primary key? If i do the following, and try to sign up a new user with a new primary key i still get the crash 'Object has been deleted or invalidated.'

```
try! realm.write {
                
                let user = realm.objects(RealmUser.self)
                realm.delete(user)
}
```

If i dont delete it, the next users data gets into the previous users data based on the primary key.

**Comment by austinzheng** [comment]
Cool! If you run into further issues please file more tickets, and thank you for using Realm!

**Comment by rromanchuk** [comment]
A little late to the party, but I was wondering if anyone could offer any insights/best practices. 

Let's say a user logs out, and I then proceed to cleanup everything related to that user's session, included in this cleanup task is

```swift
try? Realm().safeWrite {
   realm.deleteAll()
}
```

Let's say there is a code smell somewhere and there's a a `NotificationToken` still active, or maybe an instance of one of these objects is being retained by a presented controller. Usually this is predicated on some other abuse or bad practice, but are there any precautions I can take, or a different/better solution to this scenario? Should I be instead completely destroying/recreating the database? Although, that's not going to be any more resilient. 

Makes me think it might be interesting to put `realm.deleteAll()` on a random timer while testing/developing, as it might speed up uncovering fragile implementation.

**Comment by dipkasyap** [comment]
@danieldelouya  , i think you should check your memory leak or Strong retain issue on your app, i was having the save issue  deleting all user data on logout and then on logging another user it as crashing with "Object has been deleted or invalidated" message , after spending whole day it was the the old realm object. 

```
    try uiRealm.write {
            uiRealm.deleteAll()
        }
    
```

**Comment by hemantbavle1** [comment]
I get the same error for this condition. My use case is
1. Login as a user - say UserA
2. It shows a list of 10 items in a tableview
3. Tap on a row to get details of an item(Say Item 5 in a list on 10 items) using server call if not present
4. Opens a ViewController to show the details of item 5
5. Logout( contains `uiRealm.deleteAll() ` to delete all the data of the user on logout.
6. Repeat from Step 1 to 3, it doesn't reach 4, and crashes with exception `Object has been invalidated or deleted`

**Comment by varungoyal44** [comment]
Are there any updates on this? Or do we still have to delete every model one at a time?

**Comment by Nwachuks** [comment]
Any updates on this please? When I delete the previous user's details and a new user logs in, the old user's details are re-instantiated, causing a crash.

**Comment by way2dipak** [comment]
let realm = try! Realm()
try! realm.write {
    realm.deleteAll()
}
// Close Realm instance
realm.invalidate()

// Accessing objects after calling deleteAll()
let newRealm = try! Realm()
// ... re-populate Realm with data ...
// Access objects
if !object.isInvalidated {
    // ... do something with the object ...
}
newRealm.invalidate()
