### ISSUE TITLE
Write objects async 

### ISSUE THREAD

**Issue by allsome** [realm/realm-cocoa#4844]
## Goals
Write objects async

## Expected Results
Write objects async

## Actual Results
Objects can't be ThreadSafeReferenced, because they are unmanaged
It's a Infinite loop: need realm write objects in background thread or else blocking main thread, but these new objects can't be ThreadSafeReferenced, because realm has not saved them

## Code Sample
```
let objectsRef = ThreadSafeReference(to: objects)
 background({
       guard let safeObjects = realm.resolve(objectsRef) else { return }
       try realm.write {
             realm.add(safeObjects, update: true)
       }
})
```

## Version of Realm and Tooling

Realm framework version: newest

Realm Object Server version: newest

Xcode version: newest

iOS/OSX version: newest

Dependency manager + version: newest

**Comment by nirinchev** [comment]
@allsome unmanaged objects are intrinsically safe to pass between threads. So when you fetch an object, you don't need to create a thread safe reference for it, simply pass it to your background thread as it is.

**Comment by allsome** [comment]
but object realm saved in background can't be accessed in main thread, realm will crash with **Realm accessed from incorrect thread**

**Comment by nirinchev** [comment]
You should create the thread safe reference on the background thread after saving the objects to Realm, pass that to the main thread and resolve it.

**Comment by jpsim** [comment]
@allsome hopefully @nirinchev's comments helped clarify what's happening and how you can use both unmanaged objects and Thread Safe References to pass instances of Realm models across threads. I'll be closing this now since we haven't heard back from you in over a week.
