### ISSUE TITLE
Documentations have wrong parameter names

### ISSUE THREAD

**Issue by tzm41** [realm/realm-cocoa#4853]
## Goals
Warning free builds.

## Expected Results
Realm has documentation errors.

## Actual Results
<img width="214" alt="screen shot 2017-04-11 at 10 48 04 pm" src="https://cloud.githubusercontent.com/assets/5728283/24939096/194f52de-1f09-11e7-96b9-2a4252f194a0.png">

## Steps to Reproduce
Build the project.

## Code Sample
N/A

## Version of Realm and Tooling
Realm framework version: 2.5.1

Xcode version: 8.3.1

iOS/OSX version: iOS 10.3.1

Dependency manager + version: CocoaPods 1.2.1

**Comment by istx25** [comment]
Hi @tzm41. Thanks for reporting this. We'll look into this and try to fix this soon.

**Comment by BelminSalkica** [comment]
I have same problem and I'm using:
Realm framework version: 2.5.1

Xcode version: 8.3.1

iOS/OSX version: iOS 10.3.1

Dependency manager + version: CocoaPods 1.2.1

**Comment by masashi-sutou** [comment]
I have the same problem, too.
I'm using tools same version @BelminSalkica .

**Comment by tzm41** [comment]
If you want to disable documentation warnings instead of all warnings for the time being, you could use something like this in your pod file:
```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
```

**Comment by BelminSalkica** [comment]
Hi @tzm41,
This solution works great for me but is it the best solution for this problem?
I read that it is dangerous to ignore documentation warnings so I'm not sure what to do now.

**Comment by khambir** [comment]
I have the same issue. Please, fix it. 
@tzm41, thank you for temporary problem fixing, but ignore documentation warnings is bad as for me.

**Comment by tzm41** [comment]
I don't think it is that dangerous to ignore documentation warnings for now before the team fixes it…

**Comment by bdash** [comment]
The issue here is that the pod spec adds Realm core's headers to the header search path as a regular directory rather than as a system directory (system directories have any warnings suppressed, and is how Realm core's headers are configured in the Cocoa Xcode project).

**Comment by ShaharHD** [comment]
@bdash Is this an easy fix?

**Comment by bdash** [comment]
I'm not familiar with CocoaPods, so I cannot speak to the difficulty of the change I described.

**Comment by derekhealthtap** [comment]
I modified settings in the xcode project as described in other threads however when using xcodebuild on a jenkins machine, they didn't stick.  I added the following to the xcodebuild line which worked
xcodebuild ...  CLANG_WARN_DOCUMENTATION_COMMENTS=NO
