### ISSUE TITLE
App freezes because of Realm?

### ISSUE THREAD

**Issue by kidsid-Ixigo** [realm/realm-cocoa#4854]
I am using Realm as the mobile database in one of my apps and while using app start freezing randomly. I was not sure what's happening so while debugging when I paused in XCode during app freeze I saw Realm in stack traces but couldn't make out of it anything. I am attaching here a screenshot. Anyone know what's happening here?
<img width="473" alt="screen shot 2017-04-12 at 11 50 16 am" src="https://cloud.githubusercontent.com/assets/22613154/24944813/53602fcc-1f7a-11e7-931e-dfd84f589983.png">

Realm framework version: 2.5.5
Xcode version: XCode 8.3
iOS/OSX version: iOS 10
Dependency manager + version: Cocoapods

**Comment by jvieiraABC** [comment]
So what was the problem?
