### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by liufsd** [realm/realm-cocoa#4862]
## Goals

To build the project without error.

## Actual Results

```
/Users/liupeng/Documents/workspace/macstore/PhotoCloud/Carthage/Checkouts/realm-cocoa/Realm/module.modulemap:1:18: error: redefinition of module 'Realm'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/liupeng/Documents/workspace/macstore/PhotoCloud/Carthage/Checkouts/realm-cocoa/Carthage/Realm.xcworkspace -scheme RealmSwift -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/liupeng/Library/Developer/Xcode/DerivedData/Realm-dniksdmiugtvldawcddszgswgzwf/Build/Intermediates/Realm.build/Release/Realm.build/Objects-normal/x86_64/NSError+RLMSync.o Realm/NSError+RLMSync.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

## Steps to Reproduce

_None provided._

## Code Sample

_None provided._

## Version of Realm and Tooling

- Realm framework version: v2.5.1
- Xcode version: 8.3
- iOS/OSX version: 10.12
- Dependency manager + version: ?

**Comment by istx25** [comment]
Hi @liufsd. Thanks for reaching out. I've edited the issue to follow our format. Please edit it and provide more information including the version of Carthage that you're using as well as any other supporting information that you can offer that would help us reproduce/solve the issue.

**Comment by liufsd** [comment]
i have update my carthage version to 0.20.1

and build success by 'carthage update' 

thanks.
