### ISSUE TITLE
Add default/initial predicate to LinkingObjects initializer

### ISSUE THREAD

**Issue by AndrewBarba** [realm/realm-cocoa#4865]
## Goals
I want api added to the initializer of `LinkingObjects` that allows me to specify an initial predicate to be applied to the collection when I access it. Something like:

```swift
public let tickets = LinkingObjects(
    fromType: Ticket.self, 
    property: #keyPath(Ticket.order), 
    predicate: NSPredicate(format: "status == %@", "ACTIVE")
)
```

## Expected Results

```swift
let order = Order(...)
realm.add(Ticket(order: order, status: "ACTIVE"))
realm.add(Ticket(order: order, status: "CANCELLED"))
order.tickets.count.should.equal(1)
```

## Explanation

We currently use a soft delete model for all of our objects in Realm. Meaning, we have an indexed `deleted: Bool` property on our objects and in general we set this property to true instead of removing them from the realm (they are cleaned up at later times). The problem with this model is we often need to exclude these objects from queries and it is particular annoying when it comes to `LinkingObjects`. We have tried something like:

```swift
let tickets = LinkingObjects(...).filter("deleted == false")
```
when we declare our properties but this causes a crash, or no results to ever show up in the query.

**Comment by AndrewBarba** [comment]
Potential PR https://github.com/realm/realm-cocoa/pull/4866

**Comment by TR4Android** [comment]
I can only agree here, an option to specify the sort order would also be welcome. I need to filter out the deleted objects and have them sorted by their date. Thanks! :+1:

**Comment by istx25** [comment]
Hi there, @AndrewBarba. Thanks for reaching out about this and filing PR #4866. Someone will take a look at this issue and your PR soon. Cheers!

**Comment by AndrewBarba** [comment]
@TR4Android I updated the PR to take in optional sort descriptors as well

**Comment by jpsim** [comment]
An example of how you can do this today fairly easily and succinctly, without any changes to Realm, was provided here: https://github.com/realm/realm-cocoa/pull/4866#issuecomment-295422786

Reposted here for convenience:

> You can do what your PR does fairly easily today by using computed properties, btw:
>
> ```swift
> class Person: Object {
>   dynamic var name = ""
>   dynamic var age = 0
>   let children = List<Person>()
>   private let allParents = LinkingObjects(fromType: Person.self, property: "children")
>   // all parents whose name isn't 'Diane'
>   var parents: Results<Person> { return allParents.filter("name != 'Diane'") }
> }
> ```
>
> I really should have come up with a better example since "parents who aren't Diane" doesn't make much sense, but you get the idea.

**Comment by TR4Android** [comment]
@jpsim This is the workaround I currently use, but it seems more natural if it is specified with the `LinkingObjects` initializer. Also, computed properties are re-evaluated every time they are accessed and since I don't need the original (unfiltered/unsorted) objects that seems like a waste. So, yes, one can certainly develop around this, but it would be much better if the `LinkingObjects` initializer supported this. Thanks!
@AndrewBarba Thanks for your efforts :+1:!

**Comment by jpsim** [comment]
You're welcome to extend @AndrewBarba's PR to complete it and extensively test it.

**Comment by TR4Android** [comment]
@jpsim I might look into it, but don't expect anything too soon. I don't have much time at the moment. :wink: Thanks!
