### ISSUE TITLE
realm::IncorrectThreadException with Alamofire

### ISSUE THREAD

**Issue by Entsch** [realm/realm-cocoa#4869]
## Goals

I want to use a realm instance inside of the callback method of an Alamofire request.  The request itself is executed inside an NSOperation (using ProcedureKit).

## Expected Results

No crash.

## Actual Results

> libc++abi.dylib: terminating with uncaught exception of type realm::IncorrectThreadException: Realm accessed from incorrect thread.

The crash occurs on the last command `self.finish()`.  The Block runs inside a Alamofire (resp. AFNetworking) callback. Hence, I guess this crash has to do with the realm instance being released on a different thread by Alamofire. However, I have no idea how the prevent this.

## Steps to Reproduce

If you do not see any obvious mistake I might have made, I will try to come up with a runnable example.

## Code Sample

```swift
UserAPI.shared.requestGetUserInfo(userid: self.accountId) { [unowned self] response in
    let realm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "InMemoryRealm"))
    realm.beginWrite()
    var account = realm.objects(Account.self).first

    if account == nil {
        account = Account()
        realm.add(account!)
    }
            
    if account?.realm == nil {
        realm.add(account!)
    }

    // self.syncAccount(account: account!, fromResponse: response)
            
    try! realm.commitWrite()       
    self.finish()
 }
```

## Version of Realm and Tooling

- Realm framework version: 2.4.4
- Realm Object Server version: ?
- Xcode version: 8.2
- iOS/OSX version: 10.3
- Dependency manager + version: CocoaPods 1.2.0.beta.1

**Comment by istx25** [comment]
Hi @Entsch. Thanks for reaching out about this. Would you be able to show us the code that's inside the `self.finish()` function? Thanks.

**Comment by Entsch** [comment]
Thanks for the quick reply! The `self.finish()` function belongs to [ProcedureKit](https://github.com/ProcedureKit/ProcedureKit). Hence, it does not call any Realm specific code.

**Comment by istx25** [comment]
No worries! :) Other than that, I don't see anything that's particularly wrong. Would you be able to prepare that sample project you mentioned and I'll get someone to review it. Thanks!

**Comment by jpsim** [comment]
Does ProcedureKit's `finish()` function invoke any Realm code? It would have to if invoking that function is what's responsible for the incorrect thread access exception. Unless that's not actually the function responsible for the exception. Any further information would be appreciated @Entsch!

**Comment by jarklee** [comment]
Can you share me about full code of the function that contain all code you have post above, I guess that when self.finish() statement get called, ProceduceKit would call another relate code that use a realm instance.

**Comment by TimOliver** [comment]
Hi @Entsch!

Assuming you still maintain a strong reference to that in-memory Realm on the main thread, you should be able to enclose all of that Realm logic before `self.finish()` in an `@autoreleaspool` to force it to release itself before `self.finish()` is executed.

Can you please try that and see if that fixes it? Thanks!

**Comment by stel** [comment]
Hi @Entsch did you try the suggestions above? Do you still need further help or can we close this issue?

**Comment by austinzheng** [comment]
I'm going to close this ticket since it hasn't been touched for a while. If you have further questions please feel free to file new tickets against us.
