### ISSUE TITLE
Updating an object without overwriting existing attributes

### ISSUE THREAD

**Issue by markst** [realm/realm-cocoa#4882]
I think this is related to issue #2872

I'm having trouble where by if I insert an unmanaged instance of an object which uses the same primary key of an object already in my realm, the undefined attributes overwrite existing.

I suppose this might be expected behaviour in some scenarios.
My immediate thoughts are to fetch the existing object from the realm, make modifications & then update the changes. However this causes dramas with threading issues as my object has relationships, some of these issues I've outlined here: https://github.com/realm/realm-cocoa/issues/4747

```swift
let object = Object(value: ["id":"abc"])
realm.add(object, update: true)
```

---

Use case:

Since I'm using multiple threads across my mapping stack, it's most straightforward to use unmanaged objects & then insert upon completion of mapping. 

We're using jsonapi for our json payloads which include information on an object relationship & it's id. jsonapi.org

Here's an example:
```json
 "relationships":{  
    "site":{  
       "data":{  
          "id":"92cac26f-0d49-47de-9d23-a108717c5653",
          "type":"sites"
       }
    }
 }
```
 
So Ideally upon mapping an object, I'd like to establish a relationship using this information without overwriting all the existing attributes in "Site" object in mention. 

---

Is there a way realm objects can only update attributes which have been modified?
Or is there a way I can create an unmanaged copy of an object & be sure all it's relationships are not thread unsafe?

**Comment by markst** [comment]
My current resolution is copy all the existing `string` of my fetched realm object into my unmanaged copy. This is only temporary:

```swift
if let link = realm.object(ofType: T.self as! Object.Type, forPrimaryKey: id) {
    let unmanagedLink = type(of: link).init()
    let schema = RLMSchema.partialShared().schema(forClassName: String(describing: T.self))
    for property in schema!.properties {
        if property.type == .string {
            unmanagedLink[property.name] = link[property.name]
        }
    }
```

**Comment by istx25** [comment]
Hi @markst. I wanted to let you know that we've seen your issue and that someone will follow-up soon with more information. Cheers!

**Comment by jpsim** [comment]
I'm having a hard time following what it is that you're trying to do. Perhaps you could share the ideal API you have in mind, including the inputs & outputs you'd expect from it, contrasting that against what the current behavior is?

**Comment by markst** [comment]
@jpsim sorry I haven't explained well. I think ultimately I'd like to be able to create an unmanaged copy of a managed object & all it's relationships so I can freely pass it between threads without raising exceptions. Then insert it into realm once ready.

**Comment by jpsim** [comment]
If I understand you correctly, you'd need `initWithValue:` to perform a deep copy of the value passed in, including arbitrarily nested relationships & links, as tracked in #3381. Is that ticket sufficient for what you're looking for? If not, what's different about what you need?

**Comment by TimOliver** [comment]
Hi @markst! Was performing a deep copy with `initWithValue:` all you needed? Please let us know if you need anymore help! :)

**Comment by markst** [comment]
Well yes and no. If I am able to fetch the existing resource from store then I am fine to create an unmanaged copy. Here is my current example:

```swift
let realm = try? Realm()
if let object = realm?.object(ofType: Linked.self as! Object.Type, forPrimaryKey: id) {
    linkedResource = object.detached() as? Linked
} else {
    linkedResource = factory.dispense(Linked.self, id: id, pool: &pool)
}
```

Which works fine since all my relationships are copied & upon reinserting into realm - the relationships remain. 

@TimOliver: my issue is when creating a new unmanaged object with the same primary key as already in my Realm - upon adding to realm the relationships are overwritten.

Here is my example model with a `site` relationship:

```swift
class Group: Object {
    dynamic var id: String?   = nil
    dynamic var name: String? = nil
    dynamic var site: Site?
```

I create a new unmanaged instance, set the id to that of an object which exists in the realm (which I know has a relationship resolved):
```swift
let group = Group()
group.id = <an existing id in realm>
realm.add(object, update: true)
````

Now upon adding to Realm, my existing `site` relationship is nulled as can been seen when printing output:
```swift
....
updatedAt = 2017-05-02 09:57:41 +0000;
collected = 1;
group = Group {
  id = ced683e3-6d0d-46b0-b94d-4417208f682c;
  name = (null);
  site = (null);
  updatedAt = (null);
};
```

**Comment by markst** [comment]
Still digging deeper, but it could be something to do with `RLMAddObjectToRealm`

```
(lldb) po object
Group {
	id = ced683e3-6d0d-46b0-b94d-4417208f682c;
	name = (null);
	site = Site {
		id = 92cac26f-0d49-47de-9d23-a108717c5653;
		updatedAt = (null);
	};
	updatedAt = 2017-04-19 01:23:51 +0000;
}

(lldb) po prop.getterName
site

(lldb) po [object valueForKey:prop.getterName]
 nil
```

**Comment by bdash** [comment]
When you do:
```swift
let group = Group()
group.id = <an existing id in realm>
realm.add(group, update: true)
```

You're telling Realm to update the existing `Group` instance with the matching `id` so all of its properties match that of your newly-created `group`. Since you've not initialized the `site` property of `group`, it has its initial value of `nil`, meaning that you're clearing that relationship.

**Comment by markst** [comment]
@bdash which is why this issue exists. I'd like to insert an unmanaged object into Realm without updating existing `site` property if 'untouched'. This should be an option. 

Based on the comment above, the following changes fixed this issue for me:  
```
else if ([object respondsToSelector:prop.getterSel]) {
    value = RLMDynamicGet(object, prop);
    if (!value) {
        value = [object valueForKey:prop.getterName];
    }
}
```

**Comment by bdash** [comment]
I'm not sure what you mean by "untouched".

Given an instance of `Group`, there's no way that Realm can know whether `site` is nil because you don't want to update it or whether it's nil because you want to clear the relationship. Distinguishing those two cases fundamentally requires more information than an instance of `Group` alone can provide. [`Realm.create(_:value:update:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6createuRxCS_6ObjectrFTMx5valueP_6updateSb_x), for instance, can handle this when passed a dictionary as there's a meaningful distinction between the absence of a key in the dictionary and the presence of the key with a nil value. There's no such distinction with an instance of your `Group` class.

**Comment by markst** [comment]
@bdash ah it's good to have confirmation this is the expected behaviour & how I've confused it with https://github.com/realm/realm-cocoa/issues/2872

I also see how my changes above has "fixed" this issue for me - by introducing `RLMDynamicGet` we retrieve the value from the realm table. 

By untouched I mean attributes are dirty / changed. 
Is it possible that could be a feature request? to allow dirty checking on attributes - 
i.e attributes are dirty checked for changes when inserting into Realm...

**Comment by markst** [comment]
Perhaps also the documentation should be clearer as to how two following two can produce such different results in this regard:

```swift
realm.create(type(of: object), value: object, update: true)
```

```swift
realm.add(object, update: true)
```

(note that I'm passing object & not a dictionary)

**Comment by bdash** [comment]
In what respect should the documentation be clarified? Passing an object to `Realm.create(_:value:update:)` should have the same semantics with respect to relationships as calling `Realm.add(_:update:)`.

**Comment by markst** [comment]
As a really crude example:
```swift
let existingGroup = realm.objects(Group.self).first
print("existingGroup: \(existingGroup)")

try? realm.write {
    let groupOne = Group()
    groupOne.id = existingGroup?.id
    groupOne.name = "Test 1"
    let testOne = realm.create(Group.self, value: groupOne, update: true)
    print("testOne: \(testOne)")

    let groupTwo = Group()
    groupTwo.id = existingGroup?.id
    groupTwo.name = "Test 2"
    realm.add(groupTwo, update: true)
    print("testTwo: \(groupTwo)")
}
```

output:
```

existingGroup: Optional(Group {
  id = f32ab5f9-9084-4a10-aef8-20f903fa1e2c;
  name = 123;
  site = Site {
    id = 92cac26f-0d49-47de-9d23-a108717c5653;
    placeId = -----;
    address = -----;
    businessName = -----;;
    buildingName = -----;;
    contactName = Barry;
    contactEmail = barry@example.com;
    updatedAt = (null);
  };
  updatedAt = 2017-04-19 01:23:51 +0000;
  fittingsCount = 39;
  siteGroupNumber = 3;
})
testOne: Group {
  id = f32ab5f9-9084-4a10-aef8-20f903fa1e2c;
  name = Test 1;
  site = Site {
    id = 92cac26f-0d49-47de-9d23-a108717c5653;
    placeId = -----;
    address = -----;;
    businessName = -----;;
    buildingName = -----;;
    contactName = Barry;
    contactEmail = barry@example.com;
    updatedAt = (null);
  };
  updatedAt = 2017-04-19 01:23:51 +0000;
  fittingsCount = 39;
  siteGroupNumber = 3;
}
testTwo: Group {
  id = f32ab5f9-9084-4a10-aef8-20f903fa1e2c;
  name = Test 2;
  site = (null);
  updatedAt = (null);
  fittingsCount = (null);
  siteGroupNumber = (null);
}
```

**Comment by bdash** [comment]
That doesn't match my expectations, but it's late so I'm probably overlooking something. Would you mind sharing the definitions of the two model classes that are involved so your code snippet is runnable, so I can take a closer look at it in the morning?

**Comment by markst** [comment]
Understood. Thanks for help.
I can't provide you will entirety, but this should be enough:

```swift
class Group: Object {

    dynamic var id: String?   = nil
    dynamic var name: String? = nil
    
    let siteGroupNumber = RealmOptional<Int>()
    let fittingsCount   = RealmOptional<Int>()

    dynamic var site: Site?
    dynamic var updatedAt: Date?
    
    // MARK: -
    
    override static func primaryKey() -> String? {
        return "id"
    }


class Site: Object {

    dynamic var id: String? = nil
    dynamic var placeId: String? = nil
    dynamic var address: String? = nil
    dynamic var businessName: String? = nil
    dynamic var buildingName: String? = nil
    dynamic var contactName: String? = nil
    dynamic var contactEmail: String? = nil
    dynamic var updatedAt: Date?

    let groups = LinkingObjects(fromType: Group.self, property: "site")

    override static func primaryKey() -> String? {
        return "id"
    }
```

**Comment by jpsim** [comment]
Here's what's happening:

```swift
let groupTwo = Group()
// ^ 'groupTwo.site' is nil here, matching that property's default value
groupTwo.id = existingGroup?.id
groupTwo.name = "Test 2"
// ^ 'groupTwo.site' hasn't been updated before passing it to "add or update"
realm.add(groupTwo, update: true)
// ^ 'add or update' finds the object with the same primary key and updates all its properties to the values from the passed object's properties, including 'nil' ones. 'nil' is a valid value for optional properties. So here 'nil' overrides the previous value.
```

This is intended behavior. To avoid this, you can use `Realm.create(_:value:update:)` instead, only passing in the key/value pairs you want to update:

```swift
realm.create(Group.self, value: ["id": existingGroup!.id, "name": "Test 2"], update: true)
// ^ no 'site' key is passed, so the 'site' value of the existing Group with that 'id' will remain untouched
```

**Comment by bdash** [comment]
JP, we covered that back in https://github.com/realm/realm-cocoa/issues/4882#issuecomment-298819045. The current question is why `Realm.create(_:value:update)` and `Realm.add(_:update:)` handle this situation differently.

**Comment by jpsim** [comment]
Ah, sorry I missed that. We should definitely realign that then when we are ready to make breaking changes.

**Comment by bdash** [comment]
@markst, I wrote up #4926 about the discrepancy you noticed between `Realm.create(_:value:update:)` and `Realm.add(_:update:)`.

To circle back, where do you stand on the original problem you were having? Do you need further assistance with it?

**Comment by markst** [comment]
@bdash brilliant, thanks. Nope since our discussions & discoveries, I've now updated all my code to use: ```realm.create(Object.Type, value: resource, update: true)``` rather than ```Realm.add(_:update:)``` and my mapping stack is working as expected. Thanks for all the assistance!

**Comment by bdash** [comment]
Happy to hear everything is working for you now!

**Comment by markst** [comment]
Saying that. It seems the issue you've outlined in (4926) suggests that ```create()``` should in fact overwrite relationship attributes - which if resolved would break my code again. But since this is the expected behaviour, I can simply make appropriate changes my end to only pass key/value pairs I wish to update as discussed.

**Comment by bdash** [comment]
Yes, you'll likely have to update when #4926 is addressed. I'd suggest subscribing to it so you receive a notification when there's activity on that issue.

**Comment by rromanchuk** [comment]
hey @markst sorry to hijack your thread, but saw your usage of jsonapi and i was wondering if you could help fill in the gaps for me. I'm toying with the idea of switching over to `fast_jsonapi`, i'm having trouble when it comes to mapping fully included relationships

```swift
import Foundation
import RealmSwift
import ObjectMapper


class CheckIn: Object, Mappable {
    @objc dynamic var id = ""
    @objc dynamic var challengeID = ""
    
    @objc dynamic var challenge: Challenge?
    
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        id <- map["id"]
        challengeID <- map["attributes.challenge_id"]
        challenge <- map["relationships.challenge.data"]
    }
    
    override static func primaryKey() -> String? {
        return "id"
    }
}
```

I found this for inspiration https://github.com/Hearst-DD/ObjectMapper/commit/64623e982bfab3ad7892238ced38b8365e371b52#diff-78876daf8e26d313050bf493f4c8dbaaR73

But isn't `challenge <- map["relationships.challenge.data"]` the wrong field because this is simply the `type` and `id`, which would create a stubbed object with just the primary id set. I see the full data being returned in included.  I probably just need to actually read the spec sounds like conflating realm and jsonapi best practices

**Comment by markst** [comment]
@rromanchuk see: http://jsonapi.org/format/#document-compound-documents
your server mayb allow include params to be sent in the request in which to define which associated relationships to respond in the payload within the `included` key value.

**Comment by rromanchuk** [comment]
@markst so i got the included payload being delivered, but now i'm struggling with how to load this with ObjectMapper/Realm  I guess this is a problem for ObjectMapper, just not sure how to cleanly take an array of various typed objects and get them mapped to realm.

**Comment by markst** [comment]
@rromanchuk we've been using a privately forked version of https://github.com/wvteijlingen/Spine which performs a lot of the mapping layer you describe. I've yet to find an existing solution for JSON:API + Realm mapping which has continued development.

**Comment by Johncy1997** [comment]
```
export const UserSchema = {
    name:USER,
    properties:{
        id:{
            type:'int',
            optional:true
        },
        first_name:{
            type:'string',
            optional:true
        },
        last_name:{
            type:'string',
            optional:true
        },
        email:{
            type:'string',
            optional:true
        },
        phone:{
            type:'string',
            optional:true
        },
        gender:{
            type:'string',
            optional:true
        },
        otp_code:{
            type:'int',
            optional:true
        },
        is_verified:{
            type:'int',
            optional:true
        },
        is_active:{
            type:'bool',
            optional:true
        },
        dob:{
            type:'date',
            optional:true
        },
        token:{
            type:'string',
            optional:true
        }
    }
}
export const AppDataSchema = {
    name:APP_DATA,
    primaryKey:'id',
    properties:{
        id:{
            type:'string',
            default:'pharmacy'
        },
        language:{
            type:'string',
            default:'en',
            optional:true
        },
        firstInstallation:{
            type:'bool',
            default:true,
            optional:true
        },
        helpNeeded:{
            type:'bool',
            default:true,
            optional:true
        },
        userData:{
            type:USER
        }
    }
}
const databaseOptions = {
    path:'pharmacy.realm',
    deleteRealmIfMigrationRequired:true,
    schema: [UserSchema, AppDataSchema],
    schemaVersion:0
};
export const userLoggedIn = (userDetails) => new Promise((resolve,reject)=>{
    Realm.open(databaseOptions).then(
        realm=>{
            realm.write(()=>{
                let appData = realm.objectForPrimaryKey(APP_DATA,'pharmacy');
                console.log(JSON.stringify(appData.userData));
                appData.userData.id = userDetails.id;
                appData.userData.first_name=userDetails.first_name;
                appData.userData.last_name=userDetails.last_name;
                appData.userData.email=userDetails.email;
                appData.userData.phone=userDetails.phone;
                appData.userData.gender=userDetails.gender;
                appData.userData.otp_code=userDetails.otp_code;
                appData.userData.is_verified=userDetails.is_verified;
                appData.userData.is_active=userDetails.is_active;
                appData.userData.token=userDetails.token;
                appData.userData.dob=userDetails.dob;
            }); 
            resolve();
        }
    ).catch((error)=>{
        reject(error);
    })
})
```
It crashes the whole app.I can't update the user details.Someone please tell me what is the issue in my code.

**Comment by rromanchuk** [comment]
@markst hate to bring this up again, but i've just been doing some spring cleaning and found myself here again. Assume every object has a primary key.  Let's say i create an unmanaged object using an initializer `let comment = Comment(message: message)` everything works fine. Now lets say i know i'm going to receive a collection of comments knowing that the entire relationship won't be included, but I would still like to find or create + link the relationship

```swift
class Comment: Object {
 
    @objc dynamic var id = UUID().uuidString
    @objc dynamic var message: String?
    @objc dynamic var createdAt = Date()     
    @objc dynamic var user: User?

    override static func primaryKey() -> String? {
        return "id"
    }

    required convenience init(comment: CodableComment) {
        self.init()
        self.id = comment.id
        self.message = comment.message
        
        if let user = comment.user {
            self.user = User(compactUser: user)
        }
        
    }
    
}
```

I've read the difference between `create`  `add`, but wouldn't the only safe way to do this is using the values param? How does realm know not to clobber existing values on create with unmanaged object via instantiation? Does it just ignore optionals that are nil when already set on the existing record?

```swift
let user = User()
user.id = "id-of-object-that-already-exists"

comment.user = user
```

Latest docs are confusing me again. For example, below, what if `Book()` already exists, and has an optional `ISBN` property defined in the model. Wouldn't realm clobber this value with nil if it already existed? Or is there something I don't understand, like realm using KVC to track what was dirtied?

> If your model class includes a primary key, you can have Realm intelligently update or add objects based off of their primary key values using Realm().add(_:update:).

```swift
// Creating a book with the same primary key as a previously saved book
let cheeseBook = Book()
cheeseBook.title = "Cheese recipes"
cheeseBook.price = 9000
cheeseBook.id = 1

// Updating book with id = 1
try! realm.write {
    realm.add(cheeseBook, update: .modified)
}
```

**Comment by tgoyne** [comment]
Realm does not try to magically determine which properties from the thing you pass to add() or create() should be used. If you pass an unmanaged object to `add()` and an object with the same primary key exists, then all properties of the existing object will be set to the values of the object you passed in, including ones which are nil. If you do not want a property to be set, you need to pass something to `create()` which does not have that property at all. This normally means a dictionary containing only the keys which you want to update.

**Comment by rromanchuk** [comment]
So if i'm understanding this correctly "The only way to create and attach an existing associated object, in a single call, is to use a swift Dictionary"

Given these assumptions: 
- all objects have primary keys
- Two realm models `Post` and `Comment` with the pseudo code below
```
Post(id: String, name: String, comments: LinkingObjects)
Comment(id: String, commentText: String, post: Post?)
```

Given that all post already exists, i request a collection of comments for a `Post`, that return the full json collection of comments which also include the belongs_to association post, but only enough properties (the primary key) for simple association linkage

```swift
try! realm.write {
    realm.create(Comment.self, value: ["id": "1", "commentText": "my comment", "post": ["id": "1" ]], update: .modified)
}
```

It gets super ugly because i have to take the `Codable` stucts i get from a previous abstraction layer and encode them back into a swift dictionary. All i'm trying to do is attach an existing association by primary key, at the same time as my create. I haven't found any implementation more elegant than scrapping all associations, storing the foreign key myself and then subscribing to multiple object types with the appropriate predicates to mock the functionality of associations.

**Comment by wlyu2001** [comment]
Realm should provide an easy way to distinguish "nil to update" and "nil to ignore". If every time I need to ignore a field, I have to pass a dict to realm.create(), the object oriented principle of Realm is meaningless. 

Also if the field I want to ignore is deep down in the object hierarchy, how do I use realm.create() to do it?

**Comment by rromanchuk** [comment]
One of the most valuable aspect of realm when using models with primary keys is being able to create and update with values. This is especially true when you want to establish associations, not create update entire models. It allows any subscriptions to react appropriately and is fundamental common server/client paradigms.  

It's been a few years and i have yet found to find a solution any better than preventing unmanaged instance instantiation, and hand constructing dictionary literals of type `[String: Any]`. You would think a  using structures + codable would be trivial but going from a perfectly constructed struct to back out with value types  to utilize full/nested key/value dictionaries ends up crazy complexity.
 
This is the golden interface i need to somehow interface with modern network layer
`realm.create(Object.self, value: ["id": "1", "name": "sad", "post": ["id": "1" ], "complexObjectAlreadyLoaded": ["id": "1"]], update: .modified)`

I either only ever send full responses of every single associated object for ever, or face nullification from instance instantiation or insane stuff like this. Literally to just pass in FKs.
```
managedFooObjects.forEach { (object) in
            guard let unmanagedBarDict: [String: Any] = object.place_holder_bar?.toPartial() else { return }
            // Now managedFooObjects will have links updated by setting the belongs to  FKs with primary keys
            let managedBar = realm.create(Bar.self, value: unmanagedBarDict, update: .modified) 
        }
```
Anyone ever user realm AND complex associations?  Or is everyone just fishing their data out with predicates? Anyone know of some server/client production use cases in the wild beyond `Dog`/`Pet`?
