### ISSUE TITLE
App crashes by increase of Realm database file size

### ISSUE THREAD

**Issue by tebica** [realm/realm-cocoa#4887]
## Goals
Avoid app crash due to Realm DB size. want to compact Realm DB without starting Realm instance.

## Expected Results
keep the Realm DB size with reasonable size

## Actual Results
We see many crashes due to huge Realm DB file size (3Gb)

## Steps to Reproduce
Couldn't fine the reproduce scenario yet.

## Code Sample
N/A

## Version of Realm and Tooling
Realm Objective-C 2.4.2

## Xcode version:
8.3
## iOS/OSX version: 
I think it happens on many versions
## Dependency manager + version:
cocoapods 1.0.1 

# More info:
1. Can you reproduce this problem yourself at all, or has it only been reported by users?
   Getting call/ crash report from many users.

2. Can you reproduce it on demand, or does it only appear to happen at random?
  I suspect that it happening on certain circumstances but couldn't find that point yet.

3. Can you describe how your application uses Realm with respect to multiple threads. For instance:
  Using on `dispatch_get_main_queue` in `dispatch_async` only.
4. Is your Realm file only accessed by a single process at a time? Multiple process may be involved if you have multiple apps in an app group that share a Realm, or if you have application extensions that share a Realm with your main app.
using only in my app
5. How frequently do you write to the Realm?
we write very often.
6. Do you have multiple threads attempting to write to the Realm simultaneously?
using on main thread only
7. Have you tested with the most recent version of Realm? v2.5.0 includes a fix for a problem that could lead to unexpected file size growth when you have write contention (i.e., multiple threads attempting to write to the Realm concurrently for an extended period of time).
Haven't tested yet.

# My Quesiton
I am @hang-h moving to Realm from SQLite. I see many crashes from report and getting calls from CS.
We reproduced it and found that it crashes because Realm DB is 3Gb. I want to compact the Realm DB before starting Realm instance. Is it possible?

**Comment by tebica** [comment]
he @hang-h  just found some code that using Realm on the other thread.
Since [v2.5.0](https://github.com/realm/realm-cocoa/releases/tag/v2.5.0) include fix regarding this, he will update to new Realm version.

**Comment by austinzheng** [comment]
Hello! Did upgrading to 2.5.0 fix your issue? Please let us know if you have any other questions regarding this issue, or if you would like additional support.

**Comment by tebica** [comment]
@austinzheng I've just talk to the developer who reported this. and this issue is resolved when he update to v2.6.1.
Closing this issue.

**Comment by austinzheng** [comment]
Excellent! If you or that developer run into any more issues, please do open new tickets. And thank you for using Realm!
