### ISSUE TITLE
Cannot delete realm file from iPad.

### ISSUE THREAD

**Issue by ormaa** [realm/realm-cocoa#4888]
**Original title**: _BUG : Cannot delete realm file from iPad._

## Goals

I started to use Realm to read and save class on the iPad. For some reason, I want to rid all files on the iPad that are related to Realm. I can delete the default.realm file but there is 2 files that are still remaining, impossible to delete (manually or by code):

- `default.realm.management` folder
- `default.realm.note`

Formatting the iPad is not an option.

I need some code, some steps, some ideas, please, to delete those files.

Thanks,

Olivier

## Code Sample

I tried:

```swift
do {
    try FileManager.default.removeItem(at: Realm.Configuration.defaultConfiguration.fileURL!)
} catch { }
```

I've also tried:

```swift
guard var path = Realm.Configuration.defaultConfiguration.fileURL?.absoluteString else {
    fatalError("no realm path")
}

path = path.replacingOccurrences(of: ".realm", with: ".realm.note")
do {
    try FileManager().removeItem(atPath: path)
} catch {
    print(error.localizedDescription)
    fatalError("couldn't remove at path : ")
}
```

Without success. Is it impossible to delete `default.realm.note`?

## Version of Realm and Tooling

- Realm framework version: Realm Swift 2.5.1
- Realm Object Server version: ?
- Xcode version: ?
- iOS/OSX version: iOS 10.1.1 on iPad
- Dependency manager + version: ?

**Comment by istx25** [comment]
Hi @ormaa. Thanks for reaching out about this. I've edited your issue to use the template that's available [here](https://github.com/realm/realm-cocoa/issues/new) and I wanted to let you know that we've received your issue and that someone will follow-up soon.

**Comment by jpsim** [comment]
Odds are that you still have some instances of `Realm` objects in memory. Realm read transaction lifetimes are tied to their memory lifetimes, so as long as you have a strong reference to a `Realm` either directly or indirectly and haven't taken precautions to explicitly drain the autoreleasepool(s) managing their life cycle, those instances will stick around, causing Realm to continue accessing its backing files.

You can also call [`Realm.invalidate()`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm10invalidateFT_T_) explicitly on all Realm instances for each thread that is still holding a strong reference to a Realm instance at that disk location. This will cause any further access to the Realm at that location (say via `Results`, Realm `Object`s, etcetera to fail.

**Comment by TimOliver** [comment]
Hopefully that answered your question @ormaa! Please feel free to re-open the issue if you have any followup questions! :)
