### ISSUE TITLE
Documentation for create(_:value:update:) is ambiguous

### ISSUE THREAD

**Issue by IsaiahJTurner** [realm/realm-cocoa#4904]
As you will see here: https://realm.io/docs/swift/2.6.2/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6createuRxCS_6ObjectrFTMx5valueP_6updateSb_x

The documentation sates that the update parameter works such that:

> If true, the Realm will try to find an existing copy of the object (with the same primary key), and update it. Otherwise, the object will be added.

However, this can be interpreted in one of two ways and the correct unambiguous interpretation should be added to the docs.

Is it:

> If true, the Realm will try to find an existing copy of the object (with the same primary key), and update it such that any properties not provided in the value dictionary are not modified. Otherwise, the object will be added.

Or is it:

> If true, the Realm will try to find an existing copy of the object (with the same primary key), set it's properties, and delete any properties not provided within the value dictionary. Otherwise, the object will be added.

Thanks!

**Comment by istx25** [comment]
Hey @IsaiahJTurner. Thanks for pointing this out. I'll get this in front of the right people and they'll follow-up soon with more information. We'll also get a fix out there in the docs as soon as we can.
