### ISSUE TITLE
Swift 2.1 Realm 0.98.6 The Realm is already in a write transaction to mmap() failed: Cannot allocate memory size:

### ISSUE THREAD

**Issue by Genhain** [realm/realm-cocoa#4907]
## Context
A bizarre title and circumstance yes but the reason were on this version is due to using a multitude of other libraries that prevent upgrading to to the latest version of most things, Personally not my doing it's part of the project i picked when joining.

So initially Xcode was crashing with "The Realm is already in a write transaction" which vexed me as i was not nesting any transactions. So I the caught the exception and printed it and it was saying "mmap() failed: Cannot allocate memory size:"

After some research i think I have come across the reason for my pain not using `autoreleasePool` on background threads that access realm. Adding this seems to have reduced the crashes but they were quite infrequent so i'm not 100% certain if i fixed or not since in this case it would have been a size issue.

Is there any other advice people can give me for avoiding said issue, Like compacting? which is a little tricker on Realm 0.98.6 since the API for doing it hasn't been explicitly created yet.

## Goals
Write without exception

## Expected Results
Call write as many times as needed without an exception

## Actual Results
After undetermined amount of time or usage the app crashes with the exception "Fatal Exception - The Realm is already in a write transaction"

## Steps to Reproduce
No concrete steps just after after an undetermined amount of calls to write to realm.

## Code Sample
	func handle() -> Promise<Booth?> {
		return Promise<Booth?> { fulfill, _ in
			self.thread.background {
				let realm = (try? Realm())!

				self.addToRealm(realm)

				self.handleErrorsFromServer(realm)

				self.updateBoothMetaWithLatestContactSyncTime(realm)

				self.removeContactsNotOnServer(realm)

				let booth = realm.objectForPrimaryKey(Booth.self, key: self.boothPrimaryKey)
				
				let attributes = (try? NSFileManager.defaultManager().attributesOfItemAtPath(realm.path))!
				logger.info("realm info after sync: \(attributes)")

				fulfill(booth)
			}
		}
	}

unfortunately i cant share much more with you but i can tell you that writes to realm occur in the functions
- *addToRealm*
- *handleErrorsFromServer*
- *updateBoothMetaWithLatestContactSyncTime*
- *removeContactsNotOnServer*

## Version of Realm and Tooling
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217

/Applications/Xcode-7.3.1.app/Contents/Developer
Xcode 7.3.1
Build version 7D1014

/Users/benfowler/.rbenv/shims/pod
1.2.0.beta.1
Realm (0.98.6)
RealmSwift (0.98.6)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.17.2
(not in use here)

/usr/bin/git
git version 2.7.4 (Apple Git-66)

**Comment by istx25** [comment]
Hi @Genhain. Thanks for reaching out. I wanted to let you know that we've seen your issue and that someone (probably @kishikawakatsumi) will follow-up with you soon. ✨

**Comment by Genhain** [comment]
Thus far I have wrapped any usage of realm in background threads in an autoreleasePool closure, So far the crashes that were happening before do not seem to be happening. But I am tentative as the crash was not particularly consistent and i have been reading on people running out of space in various scenarios and now i am unsure if i am heading in the right direction.

Is the reason for the realm exception **The Realm is already in a write transaction** in my case because

- **Accessing too many write transactions even if they are on separate background threads?** the code sample shown in the original post can be called a fair few times e.g we continuously create user profiles and save to realm for a minute with an ideal connection to server as fast as the UI will allow, i estimate the function will be called 30-40 times.

- **Realm growing too large due to not using autoreleasePools?** from what i read if you don't invalidate the previous realm or its blocked on long running thread this will cause another realm to be created to keep intermediate versions which expands the space the next time you access it, And the realm size is limited in some way. is it possible that once reaching this limit write operations never complete and don't close causing the next call to write to raise this exception?

The reason i ask is i addressed the second (adding realm access in background threads to an autoreleasePool closure) point and the crashes don't seem to be happening yet, but other people who had expanding realm issues crashed on start rather than how i am experiencing them which has no known triggers accept when trying to write to realm after an unknown amount of times.

Another vexing point is after wrapping the realm write closure in a *do try* closure the exception returned is **mmap() failed: Cannot allocate memory size:** this is why i ask the question above. Are they related? or separate issues?

The only reason i am being so thorough with my enquiry is the nature of the crash, it's hard to reproduce and it's hard to measure the effectiveness of the solution without knowing it's root cause. Even though it seems to no be happening currently, because of it's inconsistent nature i remain cautious.

**Comment by kishikawakatsumi** [comment]
@Genhain 

> The Realm is already in a write transaction

This error doesn't relate too many threads. It's a logical error. You should make sure that you have not opened more than one transaction for the same Realm file.

> Realm growing too large due to not using autoreleasePools?

It might be possible. Not doing so could cause the Realms to leak, pinning its version, causing unnecessary file size growth.

> mmap() failed: Cannot allocate memory size

This means that the Realm file has exceeded the size can open. Before this happens, you need to reduce the size, such as by performing compaction.

**Comment by Genhain** [comment]
@kishikawakatsumi Thanks for the reply, it is much appreciated.

> This error doesn't relate too many threads. It's a logical error. You should make sure that you have not opened more than one transaction for the same Realm file.

Agreed, this is the first thing we looked for and i do not see me nesting a write closure within another write closure anyway. Which vexed me, so i tried wrapping it in a do, try, catch block and once it caught the exception and printed out the error it was instead 

> mmap() failed: Cannot allocate memory size

So do you know why this might be? 

Much appreciated

**Comment by Genhain** [comment]
@TimOliver 
> We've seen cases in the past where a Realm commitWriteTransaction() call fails, leaving the transaction open, eventually leading to an exception when another transaction is attempted on the same thread. This could be any potential write transaction, which would explain the randomness you described.

This ease's my mind slightly, I mean as much as one can be eased by the news that their concerns are legitimate, The devil you do know is better the one you don't.

However i did then add this code.

	extension Realm {
		
		func safeWrite(@noescape block: (() -> Void)) {
			
			if self.inWriteTransaction {
				block()
				
				do {
					try self.commitWrite()
				} catch {
					logger.error("\(error)")
				}
			} else {
				do {
					try self.write(block)
				} catch {
					logger.error("\(error)")
				}
			}
		}
	}

And it stopped the crashing, but it then started acting a little weird, nothing horrendous, but not ideal either and i felt as though although not a terrible way to go about using it to prevent crashes in the future, it felt like a band aid over a gaping wound. I needed to address the problem more directly rather than having a safety net in case it happened.

So i started using `autoreleasePool` closure in all Async threads, minimised the amount of times a class uses `let realm = try! Realm()` and got rid of a few instances of

    for thing in things {
        try! realm.write {
            thing.value = other
        }
    }

Which was obviously calling write an abundant of times when it only needed to be once. So i reduced the size of the realm going up even calling write with minimal to no changes in data.

> We added a proper API for this in a recent version, but even in older versions of Realm, you can export a compacted copy of a Realm file using writeCopy(toFile:encryptionKey). 

i have also added this on startup, i also read if you want to do it any time after startup you have to ensure there are no other realms open at the time.

As for upgrading, i am pushing my team to do so, were still on swift 2.1...

anyway i am happy to close this issue, if you can think of dropping anything else that might be helpful please let me know.

Much appreciated.
