### ISSUE TITLE
Get EXC_BAD_ACCESS when using realm Object as generic type in swift

### ISSUE THREAD

**Issue by klemenzagar91** [realm/realm-cocoa#4908]
## Goals
I want to compare if `Object` conforms to one of my protocols

## Actual Results
App crashed EXC_BAD_ACCESS

## Steps to Reproduce
Run attached xcode project. And it needs to be run on real device, not on xcode simulator.

## Code Sample
[RealmGenericExample.zip](https://github.com/realm/realm-cocoa/files/961595/RealmGenericExample.zip)

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195

/Applications/Xcode.app/Contents/Developer
Xcode 8.3.2
Build version 8E2002

/Users/klemen/.rvm/gems/ruby-2.3.0/bin/pod
1.2.1
Realm (2.6.2)
RealmSwift (2.6.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)


(not in use here)

/usr/bin/git
git version 2.11.0 (Apple Git-81)
```

**Comment by kishikawakatsumi** [comment]
@klemenzagar91 I think it's probably Apple's Swift compiler bug. Even if removing the Realm dependency, it still crashes. It doesn't crash on simulator and Release build (`SWIFT_OPTIMIZATION_LEVEL = -Owholemodule`). So it is probably compiler optimization failure.

Could you please report to Apple? The reproducible code without Realm is the following:

```
import UIKit

class TestObject: NSObject {
    override required init() {}
}

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        let child = Child<ChildCache>()
    }
}

protocol MyProtocol: class { }

class Child<O: TestObject>: NSObject {
  override init() {
    let o = O() as? MyProtocol // here I get error
  }
}

class ChildCache: TestObject {}
```

**Comment by austinzheng** [comment]
Hello! Did Katsumi's response above answer your question? If you need additional help, please let us know.

**Comment by stel** [comment]
I'm closing this issue for now. @klemenzagar91 please feel free to reopen it if you need any further help.
