### ISSUE TITLE
Support Stable IDs

### ISSUE THREAD

**Issue by simonask** [realm/realm-cocoa#4909]
Support stable IDs as provided by upstream. Unfortunately, we cannot wait for a proper release of upstream packages for work on this to begin.

There should be no change in user-facing APIs or behavior.

Corresponding issue in realm-dotnet: https://github.com/realm/realm-dotnet/issues/1371
Corresponding issue in realm-java: https://github.com/realm/realm-java/issues/4542
Corresponding issue in realm-js: https://github.com/realm/realm-js/issues/985

Upstream PR: https://github.com/realm/realm-sync/pull/1170

Object Store PR: https://github.com/realm/realm-object-store/pull/434

**Comment by jpsim** [comment]
@simonask how should migrations from existing stable ID Realms be handled? Will this be transparently handled by realm-sync, or do the bindings need to take special steps to kick off that process, or copy the old file to one with the new format?

**Comment by cmelchior** [comment]
I was under the impression that Bindings need to manually add the Stable ID column to existing Realms, but some clarification there would be nice.

**Comment by simonask** [comment]
Right now, stable IDs are not supported on non-synced Realms. We think it's cheaper to maintain these separate code paths than adding support for that, but of course if there is considerable demand for the feature outside of synced Realms, it can be added.

In the first iteration, the "migration" process essentially consists of recreating the Realm file (including running all migrations) and resynchronizing with the server.

**Comment by Zhuinden** [comment]
That sounds like non-sync "migration" would be super tricky as you'd need to support both ID types at the same time.

**Comment by bdash** [comment]
We expect this to be almost entirely handled by the object store changes being made in realm/realm-object-store#434 and related PRs.

**Comment by bdash** [comment]
This is supported in master-3.0 after #5068 was merged.
