### ISSUE TITLE
`LinkingObjects` limited to one result

### ISSUE THREAD

**Issue by markst** [realm/realm-cocoa#4911]
I'd like to use `LinkingObjects` which is limited to only one relationship on a database level. 

Currently I can create a computed property to return the first result sorted in this example:

```swift
extension Fitting {
    var test:Test? {
        get {
            return self.tests.sorted(byKeyPath: "updatedAt").first
        }
    }
}
```

However this does not limit the relationship to just one result. 

What I'd like to achieve is the following:

```swift
class Fitting: Object {
    dynamic var id: String? = nil
    dynamic var test: Test?
```

```swift
class Test: Object {
    dynamic var id: String? = nil
    dynamic var fitting: Fitting?
```

Where by a `Fitting` can only belong to one `Test` and visa versa...

But my understanding is this is bad behaviour & means I'd have to maintain the inverse rather than a an auto-updating 'container'.

>Because manually synchronizing pairs of relationships is error prone, complex and duplicates information, Realm provides linking objects properties to represent these inverse relationships.

----

This is actually the behaviour of CoreData when using one-to-one relationships with their inverse.

**Comment by istx25** [comment]
Hi @markst. Thanks for reaching out. I wanted to let you know that we've received your issue and that someone (probably @kishikawakatsumi) will follow-up with you soon.

**Comment by jpsim** [comment]
In Core Data, all relationships are modeled by a foreign key mapping, incurring a `JOIN` operation to resolve relationships. Inverse relationships in core data basically just automates doing the double bookkeeping that you can also do with Realm as you mentioned in your comment.

In contrast, Realm's relationships are a first-class concept in the database, with _links_ to objects actually being represented all the way down to the db file format on disk. No `JOIN` operation. Resolving a relationship is as simple as following the pointer to the object.

This is much more analogous to in-memory _pointers_ than it is to Core Data relationships.

Not only can you follow a pointer from _linker_ to _linkee_ in Realm, you can also find *all* linkers to a linked object. Just like there's no way to enforce that only one pointer exist to an in-memory object, Realm has no way to enforce that exactly one linker will link to a given linkee.

So "linking objects" just means "all objects of type X that link to me via property Y". This is true not just at Realm's public API level, but remains valid all the way down to the way data is represented on disk.

If you can guarantee in your app's logic what Realm cannot enforce at the file format level, you're free to add additional assertions in your usage of Realm such as hiding the `LinkingObjects` property as `internal` or `private` and only exposing the single-linker getter, just like you're doing today.

**Comment by austinzheng** [comment]
I'm going to close this issue, since it's been several days. If you have additional questions feel free to re-open it, or to open a new issue for unrelated problems. Thanks for using Realm!
