### ISSUE TITLE
Can't add new object inside migration

### ISSUE THREAD

**Issue by GZaccaroni** [realm/realm-cocoa#4913]
## Goals

I wanted to migrate my realm, I have changed both className and inside properties due to a complete refactoring of the code.

## Expected Results
I expected realm to add my new object without errors, because it has absolutely NO indexed properties.

## Actual Results

> *** Terminating app due to uncaught exception 'RLMException', reason: 'Can't create object with existing primary key value '0'.'

My app crashed when trying to add the new object, following line:
`migration.create(Subject.className(), value: tmpSubject)`

## Steps to Reproduce

You only need to recreate the same situation.

## Code Sample
Migration Part
```swift
migration.enumerateObjects(ofType: "Materie"){ oldObject, newObject in
    let aID = oldObject!["aID"] as! Int
    if let thisAcc = accounts.filter({ $0.aID == aID}).first {
        let subjID = oldObject!["iD"] as! Int
        print(Subject.className())
        let tmpSubject = Subject()
        tmpSubject.account = thisAcc
        tmpSubject.shortenedName = oldObject!["nomeAccorciato"] as! String
        tmpSubject.name = oldObject!["nome"] as! String
        tmpSubject.theme = oldObject!["theme"] as! Int
        migration.create(Subject.className(), value: tmpSubject)
        subjects[thisAcc]?[subjID] = tmpSubject
    }
}
```
New object

```swift
public class Subject: Object {
    dynamic var account: Account?
    dynamic var name = ""
    dynamic var shortenedName = ""
    dynamic var theme = 0
    let marks = LinkingObjects(fromType: Mark.self, property: "subject")
    let homeworks = LinkingObjects(fromType: Homework.self, property: "subject")
    let topics = LinkingObjects(fromType: Topic.self, property: "subject")
}
```

Old object

```swift
public class Materie: Object {
    dynamic var aID = 0
    dynamic var iD = 0
    dynamic var nome = ""
    dynamic var nomeAccorciato = ""
    dynamic var theme = 0
    override public static func indexedProperties() -> [String] {
        return ["aID", "iD"]
    }
}
```

## Version of Realm and Tooling

Realm framework version: 2.6.2

Xcode version: 8.3.2

iOS/OSX version: 10.3.1

Dependency manager + version: CocoaPods 1.2.1

**Comment by jpsim** [comment]
Looks like you're referring to some models that you haven't shared with us. Notably `Account`. I suspect you're creating new `Account` objects with primary keys that already exist, causing this exception.

**Comment by GZaccaroni** [comment]
@jpsim here it is account code, sorry. The problem is that I'm not creating any new account, I'm only linking the one previously created in the account property.
```
public class Account: Object {
    dynamic var aID = 0
    dynamic var name = ""
    let subjects =  LinkingObjects(fromType: Subject.self, property: "account")
    override public static func indexedProperties() -> [String] {
        return ["aID"]
    }
    override public static func primaryKey() -> String? {
        return "aID"
    }
    override public var hashValue: Int {
        return aID.hashValue
    }
}
```

**Comment by jpsim** [comment]
> The problem is that I'm not creating any new account, I'm only linking the one previously created in the account property.

I think you're mistaken here. Your sample doesn't include where the `accounts` variable comes from or what it is.

```swift
migration.enumerateObjects(ofType: "Materie"){ oldObject, newObject in
    let aID = oldObject!["aID"] as! Int
    if let thisAcc = accounts.filter({ $0.aID == aID}).first {
                     ^~~~~~~~
                     // Where is this from?
```

Then when you run `migration.create(Subject.className(), value: tmpSubject)` that will always _create_ an `Account`. This is because `Migration.create(_:value:)` doesn't have an `update:` flag like its `Realm.create(...)` counterpart does. Migration blocks don't enforce primary keys because they could change between the old and new schemas. See #2162.

**Comment by GZaccaroni** [comment]
Thanks @jpsim , you linked exactly my problem. You're always great!
