### ISSUE TITLE
Custom Realm file location

### ISSUE THREAD

**Issue by ekimia** [realm/realm-cocoa#4914]
By default, a .realm is created if a file wasn't specified. I want a unique name for my realms, and want the same auto creation behavior if the realm at the specified path does not exist. Is this currently possible? Looked through the docs but still scratching my head.

## Version of Realm and Tooling

Realm framework version: 2.6.2

Realm Object Server version: NA

Xcode version: 8.3.2

iOS/OSX version: 10

Dependency manager + version: Carthage (latest version)

**Comment by bdash** [comment]
If you specify a custom `fileURL` in the Realm configuration, Realm will automatically create the file if it does not exist when opening it. It _is_ necessary to ensure that the directory containing the file exists, as Realm will not create intermediate directories on your behalf.

**Comment by ekimia** [comment]
@bdash I closed it because I realized it was grabbing a nonexistent documents directory since I'm using realm in a framework in developing.
