### ISSUE TITLE
Bad error message: 

### ISSUE THREAD

**Issue by Mozahler** [realm/realm-cocoa#4918]
I'm seeing this error:
<img width="857" alt="variablenameviolation" src="https://cloud.githubusercontent.com/assets/9641531/25616290/c6299702-2f09-11e7-93ae-ca2a486cae60.png">
The message says the variables are capitalized, but you can see that they are not.
Realm generated by Carthage on April 21st.
macOS 10.12.4
Xcode 8.3.2

**Comment by jpsim** [comment]
I think you meant to file this on SwiftLint: https://github.com/realm/SwiftLint/issues/new

**Comment by Mozahler** [comment]
yup. sorry
