### ISSUE TITLE
pod xcbuild failed

### ISSUE THREAD

**Issue by okayz** [realm/realm-cocoa#4927]
AppDelegate.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

## Version of Realm and Tooling

Realm framework version: 2.6.2
Xcode version: 8.3

**Comment by bdash** [comment]
Please provide all of the information requested in the [new issue template](https://raw.githubusercontent.com/realm/realm-cocoa/master/.github/ISSUE_TEMPLATE.md). Of particular interest in your case would be whatever error you're encountering when your build fails.

**Comment by okayz** [comment]
It's script problem,thanks...
