### ISSUE TITLE
requires a protocol defining the contained type - example: RLMArray<Person>

### ISSUE THREAD

**Issue by skander300** [realm/realm-cocoa#4928]
i am having this error , any help ?
Terminating app due to uncaught exception 'RLMException', reason: 'Property 'documents' requires a protocol defining the contained type - example: RLMArray<Person>.'

this is my code that is causing my issue : 
@interface CategoryRealm : RLMObject
@property NSString *categoryId;
@property NSString *name;
@property NSString *imagePath;
@property NSString *categoryDescription;
@property RLMArray<DocumentRealm * >*documents;

-(id)initWithMantleModel : (Category*)category;

@end

**Comment by nhatlee** [comment]
I have the same problem, how to fix it?
