### ISSUE TITLE
RLMObject returning nil in objective c

### ISSUE THREAD

**Issue by matloobhasnain** [realm/realm-cocoa#4929]
Hi guys I have an RLMObject

```objc
@interface Job : RLMObject <NSCoding, NSCopying>
@property (nonatomic, strong) Contact *contact; // this is another RLMObject
@property (nonatomic, strong) Location *location; // this is another RLMObject
```

Its saving fine and once I try to Load  all object giving excellent result ,

```objc
RLMResults<Job *> *jobListArray = [Job allobjects];
```

but issue is once I get job object from this `jobListArray` its returning me `Contact` and `Location` Object Nil. If any one can help would be appreciated.

**Comment by jpsim** [comment]
To-one relationships in Realm are nullable, so if there's no relationship set, it's expected that the properties would return `nil`. Please see our docs on [Relationships](https://realm.io/docs/objc/latest/#relationships) for details.

**Comment by austinzheng** [comment]
To expand on what JP said above, when you create an object any properties that point to other objects (like `contact` and `location`) start off as nil, and you have to manually set them for them to be non-nil. I hope that helps! If you have any other issues please feel free to open new tickets.
