### ISSUE TITLE
Realm objects were not sorted by character code

### ISSUE THREAD

**Issue by hmuronaka** [realm/realm-cocoa#4937]
I sorted realm objects by string property. But the objects were not sorted by character code

```swift

class TestObject: Object {
      dynamic var name:String?
}

func test() {
        let realm:Realm = try! Realm()
        let obj1 = TestObject()
        obj1.name = "@1234"
        let obj2 = TestObject()
        obj2.name = "1234"
        
        try! realm.write {
            realm.add(obj1)
            realm.add(obj2)
        }
        let results = realm.objects(TestObject.self).sorted(byKeyPath: "name")
        XCTAssertEqual(results.map { $0.name! }, ["1234", "@1234"]) //  NG!!!!
}
```
I want to sort the objects ["1234", "@1234"] 
And I want to get results as a Results object for using NotificationBlock.
Why weren't realm objects  sorted by character code?
How do I sort by character code?

- Realm framework version: 2.7.0
- Xcode version: Version 8.3.1 (8E1000a)
- iOS version ? 10.3 / 
- Dependency manager + version: carthage 0.22.0

**Comment by austinzheng** [comment]
Thanks for using Realm, and for getting in touch with us!

Unfortunately, our underlying database engine only supports lexicographic sort on strings. If you want to sort on ASCII character code, you will need to use the Swift standard library map and sort methods.

**Comment by hmuronaka** [comment]
Thank you, your answer.
I understand that symbols are less than any digits and any letters.
