### ISSUE TITLE
Realm accessed from incorrect thread

### ISSUE THREAD

**Issue by tiandabao** [realm/realm-cocoa#4938]
```objc
@interface TableViewController ()
@property (nonatomic, strong) RLMResults *array;
@end

@implementation TableViewController
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        self.array = [[DemoObject allObjects] sortedResultsUsingKeyPath:@"date" ascending:YES];
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.tableView reloadData];
        });
    });
}

#pragma mark - UITableViewDataSource
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return self.array.count;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kCellID];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle
                                      reuseIdentifier:kCellID];
    }
    DemoObject *object = self.array[indexPath.row];
    cell.textLabel.text = object.title;
    cell.detailTextLabel.text = object.date.description;
    return cell;
}
@end
```

Asynchronous data, the main line to refresh, then crash “Realm accessed from incorrect thread.”

**Comment by BlueVirusX** [comment]
Hi,

I think your problem here is that you are setting the `self.array` property inside a background queue block, but you are accessing this property in the main queue/thread.
Accessing Realm object instances from different threads is not allowed, as mentioned in the docs [https://realm.io/docs/objc/latest/#passing-instances-across-threads](url).

To fix your problem you can remove the blocks for switching the queues:
> dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
> ...
> dispatch_async(dispatch_get_main_queue(), ^{
> ...
> });
> });

**Comment by tiandabao** [comment]
If the amount of data is large, so the data without blocking the main thread？？？？？？

**Comment by austinzheng** [comment]
You are right that doing a large amount of computation can block the main thread.

A better solution is to perform your query on a background thread (as you are doing now), and then use `RLMThreadSafeReference` (docs [here](https://realm.io/docs/objc/2.7.0/api/Classes/RLMThreadSafeReference.html)) to move the results from the background thread to the main thread. Note that you will want to first access the results object to force it to evaluate the query (see the [docs for `RLMResults`](https://realm.io/docs/objc/2.7.0/api/Classes/RLMResults.html) for more detail).

**Comment by stel** [comment]
@tiandabao do you need any further help here or can we close this issue? Thanks!

**Comment by austinzheng** [comment]
I'm going to close this ticket since it hasn't been touched for a while. If you have further questions please feel free to file new tickets against us.
