### ISSUE TITLE
realm crashes in BpTree

### ISSUE THREAD

**Issue by dwalkowski** [realm/realm-cocoa#4945]
**Bugs**: To help you as fast as possible with an issue please describe your issue
and the steps you have taken to reproduce it in as many details as possible.

Sorry for the screenshot; extenuating circumstances, this is all I have

Realm crashes frequently at the highlighted spot in BpTree!

![screen shot 2017-05-09 at 3 44 04 pm](https://cloud.githubusercontent.com/assets/25169691/25877665/9e465402-34d9-11e7-853e-9a53e98198f1.png)

**Comment by austinzheng** [comment]
Thanks for getting in touch, and sorry you're experiencing issues with Realm. Without additional information it won't really be possible for us to proceed. Is this happening on a single device or multiple devices, what version of Realm is being used, and how often does it happen? Is the crash `EXC_BAD_ACCESS`? Crashing on the allocation of a new object is rather atypical, and may or may not indicate a problem with the underlying database engine.

**Comment by austinzheng** [comment]
Unfortunately we don't have anything actionable to take this issue forward, so I'll be closing it.
