### ISSUE TITLE
Results<T> gets updated even autoRefresh is false

### ISSUE THREAD

**Issue by jovanpreet** [realm/realm-cocoa#4947]
Is there a way to stop Results<T> from auto refreshing.

**Comment by bdash** [comment]
A `Results` always reflects the version of the Realm file that the `Realm` instance it was created from is using. `Realm.autorefresh` controls whether the `Realm` instance automatically advances to newer versions of data within the Realm as they become available. Can you clarify what behavior you're seeing from `Results` that leads you to believe that `autorefresh` is not being honored? Providing a self-contained code sample that demonstrates the issue would be ideal. Please also provide the information that [the new issue template](https://raw.githubusercontent.com/realm/realm-cocoa/master/.github/ISSUE_TEMPLATE.md) requests.

**Comment by jovanpreet** [comment]
**Goals**
Results<T> should not reflect to latest data if `Realm.autorefresh` is `false`.

**Expected Results**
let realm1 = Realm()
realm1.autoRefresh = false
let feeds = realm1.objects(NewsFeed.self).sorted(byKeyPath: "news.createdAt", ascending: false)
print(feeds) //feed data

let realm2 = Realm()
realm2.create(NewsFeed.self, value: ["virtualNewsId": 1, "news": feed.dictionaryObject!], update: true)

print(feeds) //old feed data
realm1.refresh()
print(feeds) //new feed data

**Actual Results**
let realm1 = Realm()
realm1.autoRefresh = false
let feeds = realm1.objects(NewsFeed.self).sorted(byKeyPath: "news.createdAt", ascending: false)
print(feeds) //feed data

let realm2 = Realm()
realm2.create(NewsFeed.self, value: ["virtualNewsId": 1, "news": feed.dictionaryObject!], update: true)

print(feeds) //new feed data
realm1.refresh()
print(feeds) //new feed data

**Version of Realm and Tooling**
Realm version : 2.5.1
ios version : 10.3.1

**Comment by bdash** [comment]
In your example code you're adding new objects via the same `Realm` instance as the `Results` is associated with (the `Realm()` initializer returns an existing instance if one exists), so naturally the `Results` reflects these changes. [`Realm.autorefresh`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:vC10RealmSwift5Realm11autorefreshSb) only impacts whether the `Realm` automatically refreshes to reflect changes made in the Realm by other threads (or processes).

**Comment by jovanpreet** [comment]
The how to create two different instances or how to use threads so that realm1 will not autoupdate.

**Comment by bdash** [comment]
This example demonstrates how disabling autorefresh works.

```swift
let realm = try! Realm()
realm.autorefresh = false

let feeds = realm.objects(NewsFeed.self).sorted(byKeyPath: "news.createdAt",
                                                ascending: false)
print(feeds)

// Create the NewsFeed on a background thread, waiting for the operation to complete.
// In real-world code you'd typically not wait like this, but would instead use a
// notification to know when the work has completed.
DispatchQueue.global().sync {
    let realm = try! Realm()
    try! realm.write {
        realm.create(NewsFeed.self,
                     value: ["virtualNewsId": 1, "news": feed.dictionaryObject!],
                     update: true)
    }
}

print(feeds)
realm.refresh()
print(feeds)
```

**Comment by jovanpreet** [comment]
I already tried `DispatQueue.global()` before and this doesn't do anything and feeds gets autoupdated. Sorry but your code is of no help.

```
Results<NewsFeed> (

)
Results<NewsFeed> (
	[0] NewsFeed {
		virtualNewsId = 1;
	}
)
Results<NewsFeed> (
	[0] NewsFeed {
		virtualNewsId = 1;
	}
)
```

Here is the output of 3 print statements of your above code

**Comment by austinzheng** [comment]
Can you explain exactly what you are trying to accomplish? Perhaps we aren't correctly understanding the context of your question.

**Comment by bdash** [comment]
@jovanpreet, I attempted to simplify the threading aspect of the example to avoid obscuring the point, but in doing so I overlooked that `dispatch_sync` attempts to be clever and perform its work on the current thread if possible. An updated example that avoids this pitfall:

```swift
let realm = try! Realm()
realm.autorefresh = false

let feeds = realm.objects(NewsFeed.self).sorted(byKeyPath: "news.createdAt",
                                                ascending: false)
print(feeds)

// Create the NewsFeed on a background thread, and wait for the operation to complete.
// In real-world code you'd typically not wait like this, but would instead use a
// notification to know when the work has completed.
let group = DispatchGroup()
group.enter()
DispatchQueue.global().async {
    let realm = try! Realm()
    try! realm.write {
        realm.create(NewsFeed.self,
                     value: ["virtualNewsId": 1, "news": "Test news"],
                     update: true)
    }
    group.leave()
}

group.wait()

print(feeds)
realm.refresh()
print(feeds)
```

I second @austinzheng's request for more information about what it is you're trying to accomplish. Why is it that you want to disable auto refresh?

**Comment by jovanpreet** [comment]
I am using collectionView with refreshControl. As i do pull refresh  I add some data to feeds. I also use realm notificationBlock for changes to get updated in collectionView but feeds(Results<NewsFeed>) gets updated before notification block is called which cause issues because feeds  has media(List<Media>) and different feeds has different media count then collectionView `cellForItemAt:` tries to access feeds media and as collectionView is not yet updated(notification block is not yet called) i get crashes.

**Comment by austinzheng** [comment]
Can you try @bdash's updated code and see if that does what you're expecting? I can see why if you have multiple data sources for your collection view you might want to control updating of Realms more tightly.

**Comment by jovanpreet** [comment]
@austinzheng i tried @bdash's code it did work but then notification blocks aren't called.

**Comment by austinzheng** [comment]
On which thread are your notification blocks being called? Notification blocks are only called if there is an [active run loop on the thread](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/RunLoopManagement/RunLoopManagement.html), which threads handling blocks dispatched to the global background queues lack.

**Comment by jovanpreet** [comment]
```
class ViewController: UIViewController {
    
    let realm = try! Realm()

    var feeds:Results<NewsFeed>!
    var notifBlock: NotificationToken!
    override func viewDidLoad() {
        super.viewDidLoad()
        realm.autorefresh = false
        feeds = realm.objects(NewsFeed.self).sorted(byKeyPath: "virtualNewsId", ascending: false)
        try! realm.write {
            realm.deleteAll()
            realm.create(NewsFeed.self,
                         value: ["virtualNewsId": 2],
                         update: true)
        }
        print(feeds)
        self.notifBlock = self.feeds.addNotificationBlock({ changes in
            print("notif")
            print(self.feeds)
            //print(changes)
        })
        print(feeds)
    }
    override func viewDidAppear(_ animated: Bool) {
        DispatchQueue.global().async {
            let realm2 = try! Realm()
            try! realm2.write {
                realm2.create(NewsFeed.self,
                              value: ["virtualNewsId": 1],
                              update: true)
            }
        }
    }
}

```

In the above code notification for feed with virtualNewsId = 1 is not fired. Or we can say notificationBlock is not called.

**Comment by austinzheng** [comment]
Notification blocks on collections don't fire if auto-refreshing is disabled.

**Comment by jpsim** [comment]
> Notification blocks on collections don't fire if auto-refreshing is disabled.

Not quite correct because refreshing can happen even when `autoRefresh` is turned off on that Realm. For example, explicitly calling `Realm.refresh()` or `Realm.beginWriteTransaction()`/`Realm.write()` will refresh the Realm.

**Comment by jovanpreet** [comment]
Yes agree with @jpsim. If i turn `autoRefresh` off and then do any realm write on same thread Notification block gets called but if i do write transaction on some other thread then notification block aren't called. But if `autoRefresh` is on then notification block gets called when write transaction is performed on any thread.

Basically my issue was `Results<T>` gets updated before the notification block gets called (which causes index out of bound error as feeds get deleted but `collectionView` is not yet notified) so i try to disable `autoRefresh` and tried to manually call refresh when notification block gets called but i am actually going in wrong direction and realised that realm is not designed in this way. So finally i solve my issue by enabling `autoRefresh` and doing all write transaction in in different thread in this way realm refresh `Results<T>` and call notification block at same time(might be at next run loop) which solves my issue. I think if realm auto refresh `Results<T>` instantly if write transaction is performed on same thread then it should also call notification block that are on same thread instantly without waiting for the next run loop. You should think how app will use your realm and how to handle such kind of scenarios by making as many examples as possible.
