### ISSUE TITLE
Project stopped compiling, because of Realm errors

### ISSUE THREAD

**Issue by adamsmaka** [realm/realm-cocoa#4948]
Hey, I don't know what happend, I have never any issues but today I can't compile my project because of Realm errors like this:

<img width="868" alt="screen shot 2017-05-10 at 3 21 51 pm" src="https://cloud.githubusercontent.com/assets/22574704/25900716/a8b78698-3594-11e7-8be0-19eace1b91ad.png">

Why is it happening ? I have the newest version of Realm. Tried to clean project and pod install it again but for nothing.

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. Did you run `pod install` or `pod update` right before seeing these errors? Regardless, here are a few things to try:

* Clean the build folder (Go to the Xcode `Product` menu while holding down the Option key, then choose `Clean Build Folder...`), then rebuild the project. (Note that this is different from just cleaning the project).
* Follow the steps to reset CocoaPods for your project found [here](https://realm.io/docs/objc/latest/#cocoapods).

If these don't fix your problem please reply to this thread and we'll look into the issue further. Thanks for using Realm!

**Comment by adamsmaka** [comment]
thank you! it helped! now project compile (after deintegrating and installing pods again)
but there are still warrnings like this:
<img width="423" alt="screen shot 2017-05-10 at 8 15 24 pm" src="https://cloud.githubusercontent.com/assets/22574704/25914180/ab7c0ab0-35bd-11e7-99cd-6147ae0bbd1c.png">

**Comment by bdash** [comment]
Those remaining warnings are being tracked at #4853.
