### ISSUE TITLE
Returning optional of generic type parameter constrained by `Object` causes crash

### ISSUE THREAD

**Issue by gligorkot** [realm/realm-cocoa#4951]
## Goals

Trying to get an object from my Realm database

## Expected Results

Successfully get the required object

## Actual Results

I get a crash with an uncaught exception:
```
"Inside init: Current thread <NSThread: 0x600000075700>{number = 5, name = (null)}"
"Inside getObject: Current thread <NSThread: 0x600000075700>{number = 5, name = (null)}"
libc++abi.dylib: terminating with uncaught exception of type NSException
```
At first I thought it was a threading issue, but you can see that I init the Realm and getObject on the same thread.

## Code Sample

```swift
private var database: Realm!

init(some_var: String) {
  var configuration = Realm.Configuration()
  configuration.fileURL = configuration.fileURL!.deletingLastPathComponent().appendingPathComponent("\(some_var).realm")
  do {
    debugPrint("Inside init: Current thread \(Thread.current)")
    self.database = try Realm(configuration: configuration)
  } catch {
    debugPrint("realmInit: Can't create realm database.")
  }
}

func getObject<T: Object, K>(with primaryKey: K) -> T? {
  debugPrint("Inside getObject: Current thread \(Thread.current)")
  return self.database.object(ofType: T.self, forPrimaryKey: primaryKey) // THIS LINE THROWS EXCEPTION
}
```

## Version of Realm and Tooling

Realm framework version: 2.6.2

Realm Object Server version: N/A not using

Xcode version: 8.3.2

iOS/OSX version: OSX 10.12.3

Dependency manager + version: Cocoapods 1.1.1

**Comment by gligorkot** [comment]
Hi @austinzheng, thanks for your quick response. Unfortunately I'm unable to send a full reproduction case, but I did get somewhere with the Exception breakpoint (how on Earth did I not think of that, end of the week tiredness maybe)

The exception is thrown in RLMClassInfo.mm line 89:
```obj-c
@throw RLMException(@"Object type '%@' is not managed by the Realm. "
                            @"If using a custom `objectClasses` / `objectTypes` array in your configuration, "
                            @"add `%@` to the list of `objectClasses` / `objectTypes`.",
                            name, name);
```

**Comment by austinzheng** [comment]
I wonder if Swift generics have anything to do with this issue. Just a couple of questions:

* First, what code is calling `getObject<T>()` that it crashes? In particular, what type is the type variable `T` being instantiated as?
* I assume you don't use a custom Realm configuration to open up your `self.database` Realm?
* What happens if you replace the generic version of `getObject()` with a non-generic version(s) that explicitly hardcodes the type?

**Comment by gligorkot** [comment]
Thanks for working through this issue with me @austinzheng, here are the answers:

- The code that is calling `getObject<T>()` is the following:
```swift
if let directMessage = StorageFacade.database(for: some_var).getObject(with: id) as? RealmDirectMessage {
  // do something with directMessage
}
```

- The extent of custom Realm configuration is the path to the file as seen in my `init(some_var: String)` function above

- Interestingly this works!?! not really sure how or why?

**Comment by gligorkot** [comment]
Wow... Doing some more testing on this, it looks like the problem comes from using a generic optional. This piece of code also works, although I obviously wouldn't want to throw a `fatalError()` if my object wasn't found, this was just for testing purposes:

```swift
func getObject<T: Object, K>(with primaryKey: K) -> T {
  debugPrint("Inside getObject: Current thread \(Thread.current)")
  if let object = database.object(ofType: T.self, forPrimaryKey: primaryKey) {
    return object
  }
  fatalError()
}
```

**Comment by austinzheng** [comment]
So the only difference between your working and non-working function is `T` vs `T?` (and of course the fatal error)? That seems like a bug.

To work around this, you may want to change your `getObject()` method to be something like `getOrCreateObject()` (make it if it doesn't exist), and then have another method that checks for the existence of an object and returns a boolean. That being said this is still a workaround, and we should figure out why the optional version is broken.

**Comment by gligorkot** [comment]
That's exactly right. I will implement the version you suggest with the boolean as a workaround for now, but would be good to have this fixed if at all possible. Very weird issue. Thank you so much for your help detect the problem too.

**Comment by jpsim** [comment]
@austinzheng I'd appreciate if you could rephrase the issue title based on your understanding of the bug, if necessary. Thanks.
