### ISSUE TITLE
Xcode warnings "Documentation Issue"

### ISSUE THREAD

**Issue by Jackhammer42** [realm/realm-cocoa#4955]
I am seeing several xcode warnings in the realm pod under the headline "Documentation Issue". The problem is described in this thread: 

https://forums.realm.io/t/documentation-issue-xcode/206

Realm framework version: Realm Swift 2.7.0

Xcode version: 8.3.1

Dependency manager + version: Cocoapods 1.1.1

**Comment by stel** [comment]
This issue has been fixed and will be available in next release. For now you can use the workaround from https://github.com/realm/realm-cocoa/issues/4853#issuecomment-293778843.
