### ISSUE TITLE
Trace Log for Realm Operations

### ISSUE THREAD

**Issue by kashifshaikh** [realm/realm-cocoa#4963]
## Goals

I want to be able to log/trace Realm operations during the debugging phase of my app.
Because of the lazy nature of Realm queries, you never know if a particular operation is loading from disk or has already been loaded in memory.

This way I can get visibility into I/Os from happening when loading the first item of a collection and when read I/Os occur when iterating through a Results collection.

We want to avoid the UI from slowing down (e.g. scrolling through a table view) if going through Results.

I don't see anywhere in the API where this can be enabled - I only see it for Object Server (which I don't use).

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by stel** [comment]
There is no api for that. Personally I don't think tracing could be useful in this case and I'd recommend to use profiling tools instead to determine any bottlenecks in your app.

Also I think [this article](https://news.realm.io/news/realm-api-optimized-for-performance-and-low-memory-use/) can be useful for understanding how realm queries work internally.

**Comment by austinzheng** [comment]
Thanks for using Realm; If you have any further questions feel free to file new tickets.
