### ISSUE TITLE
Migration for multiple realm files

### ISSUE THREAD

**Issue by Talgat777** [realm/realm-cocoa#4965]
Hey,

I have 2 realm files:
1) Realm A (cache) - can be deleted on migration
2) Realm B (sensitive data) - needs migration

Each of the Realm files has it's own configuration+migration. 

On Login I use Realm B. Realm A I use later.

Problem: if I change RLMObject that belongs only to Realm A and try to use Realm B (before I use Realm A), the crash happens due to migration needed. 

Expected behaviour: do migration for each of the Realm files separately and only when one tries to access it. Maybe check if the type belongs to that Realm?

Thanks!

**Comment by stel** [comment]
Does `Realm B` contains types from `Realm A` (let's call them `Types A`)? In this case you should handle the migration for these types in `Configuration B` migration block.

If you don't need to have `Types A` in `Realm B` you should specify a class subset to the configuration. Learn more at https://realm.io/docs/swift/latest/#class-subsets.

**Comment by Talgat777** [comment]
Nice! Haven't noticed `Class Subsets`, thanks!
