### ISSUE TITLE
SyncUser login register:true too many callbacks with errors

### ISSUE THREAD

**Issue by ashhanai** [realm/realm-cocoa#4966]
Hello, I bump into an error when after registering new user, by calling login with parameter register:true, I first get callback with user object (expected result) and then 2 callbacks with "Already existing user" error.

It looks like the login method is invoked several times and that causes the last 2 error callbacks.

Loging with username and password.

Login with register:false do not have the same problem.

**Comment by stel** [comment]
@ashhanai could you please provide an example xcode project/code sample in order to reproduce this case? Thanks!

**Comment by jpsim** [comment]
Hi @ashhanai, I'm following up on @stel's request for a sample project so that we have enough information to help you.

**Comment by austinzheng** [comment]
If this is still an issue, please re-open this ticket and provide us with a sample project. We haven't been able to replicate this ourselves.
