### ISSUE TITLE
Realm "Error" class confused with Swift 3's "Error" class

### ISSUE THREAD

**Issue by abdulla-allaith** [realm/realm-cocoa#4967]
## Goals
I have been trying to use Alamofire 4 with the latest version of Realm on Swift 3.           
In Swift 3, when Alamofire requests fail, they return an "Error" object (Swift class).          
I am using that error value to return a failure function as a completion handler with the error passed back.          
The problem is that using that inside Realm makes Xcode confused between Realm's "Error" class and Swift's "Error" class!

## Expected Results
If Realm's "Error" class was named differently, the code would run smoothly and the function would return a Swift "Error" class.

## Actual Results
Xcode shows compile time errors (unable to compile) because the "Error" parameter is considered as a Realm "Error" class and therefore, what Alamofire is passing back is an invalid "Error" class.

## Steps to Reproduce
The code below shows the compile time error that states that:

> Cannot convert value of type 'Error' to expected argument type 'Realm.Error'

The code will work with Alamofire, Realm in Swift 3

## Code Sample
```
extension Realm {
        func update<T:Object>(_ object:T, success:@escaping ()->Void, fail:@escaping (_ error:Error)->Void) {
            Alamofire.SessionManager.default.request("http://www.google.com", method: .get, encoding: URLEncoding.default)
                .responseJSON { response in
                    switch response.result {
                    case .success( _):
                        success()
                    case .failure(let error):
                        fail(error)
                    }
            }
        }
    }
```

## Version of Realm and Tooling
Realm framework version: 2.7.0

Realm Object Server version: -

Xcode version: 8.2.1

iOS/OSX version: Mac OS X 10.12.4

Dependency manager + version: Cocoapods 1.1.1

Alamofire version: 4.4.0

**Comment by bdash** [comment]
Realm's error type is nested within the `Realm` class as `Realm.Error`. Since you're extending the `Realm` class, an unqualified reference to `Error` naturally refers to the type declared within the same scope. To refer to Swift's normal `Error` type within such a context, you'll want to explicitly qualify references to `Swift.Error` (that is, write `Swift.Error` rather than simply `Error`) .

**Comment by abdulla-allaith** [comment]
I know that is possible. However, why does a Realm class have to conflict with a Swift class? I believe it might be better practice to not have such conflict. I have not seen a pod/library that creates their own String class and requires developers to call `Swift.String` instead because they're in the library's scope. It's just a matter of naming convention and I think it is unnecessary to have `Realm.Error`, maybe `Realm.RealmError` or `Realm.RLMError` would be better following the namings of `RealmCollection` or `RLMSchema`

**Comment by austinzheng** [comment]
Thanks for your feedback. The merits of naming our error type `Error` versus something else were discussed extensively during our transition to Swift 3, and we tried both variants in beta versions before settling on the current behavior. We have no plans to change our type names at this time.
