### ISSUE TITLE
init(value:) on Array of Results

### ISSUE THREAD

**Issue by marinofaggiana** [realm/realm-cocoa#4968]
I use `init(value:)` for return a single unmanaged instance of a Realm object after a result[0] 

`realm.objects(object.self).filter(predicate)`

but for several result(s) (array) exists a rapid function ?

thanks a lot

**Comment by iband2011** [comment]
You need to set a primary key of you RLMObject model.You can create a @property like "Id" and do nothing after.That would be ok.

**Comment by austinzheng** [comment]
We don't have a dedicated API for what you want, but the Swift standard library `map()` API on collections should do what you want.

**Comment by marinofaggiana** [comment]
Thanks.

**Comment by marinofaggiana** [comment]
I have try with : 

let tests =results.map { $0 }

but the objects of tests are still managed ... 

This is the unique way for convert results managed in unmanaged ?

var recordsUnmanaged = [table]()
for result in results {
            recordsUnmanaged.append(table.init(value:result))
 }

Thanks
