### ISSUE TITLE
Fix warnings appearing in XCode 8, when using Realm in an iOS project written in Swift

### ISSUE THREAD

**Issue by balazsgerlei** [realm/realm-cocoa#4973]
## Goals
Eliminate warnings when compiling the project, and only see the actual problems. It is quite annoying when debugging to see 14 issues (warnings) after every build, caused by Realm.

## Expected Results
Realm should not produce warning in XCode.

## Actual Results
XCode signals a huge ammount of warnings when compiling the project, for example:
.../Pods/Realm/include/core/realm/sync/history.hpp:124:69: Empty paragraph passed to '\param' command
.../Pods/Realm/include/core/realm/sync/history.hpp:124:61: Parameter 'progress.' not found in the function declaration

## Steps to Reproduce
Include Realm in your Swift project via CocoaPods

## Version of Realm and Tooling
Realm framework version: 2.7.0
Xcode version: 8.3.2

**Comment by adamstener** [comment]
Seeing the same issue.

**Comment by ppamorim** [comment]
Happening here too. So annoying! Tons of unnecessary warnings!

**Comment by austinzheng** [comment]
Sorry you're experiencing this issue. We fixed the problem in https://github.com/realm/realm-cocoa/pull/4950, and the fix will roll out with our next Cocoa release. Hope that helps.
