### ISSUE TITLE
Leaks issue

### ISSUE THREAD

**Issue by lowki93** [realm/realm-cocoa#4975]
Hello, 

I have this leaks with Xcode inspector : 
![capture d ecran 2017-05-24 a 14 36 54](https://cloud.githubusercontent.com/assets/5473017/26403420/7bf6d776-408e-11e7-9cd1-aa926398e444.png)

Do you have an idea ?

thanks

**Comment by jpsim** [comment]
This appears to be the same issue as #4334. Closing as a duplicate.
