### ISSUE TITLE
Error on Crashlytics

### ISSUE THREAD

**Issue by jovanpreet** [realm/realm-cocoa#4976]
Fatal Exception: realm::LogicError: Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)

**Comment by austinzheng** [comment]
It's not possible for us to look into this unless, at the very least, you give us a stacktrace and the version of Realm that was being used.

**Comment by jovanpreet** [comment]
Is it a realm crash or my code error?

**Comment by austinzheng** [comment]
Since it was an exception, not a Realm assertion failing (or worse), it is most likely an error in your code.

**Comment by jovanpreet** [comment]
I think then i can close this issue as this occurs during beta testing of my app and not a single instance has been reported by crashlytics in the latest beta so might be fixed by some member of my team. 

Thanks for your help.

**Comment by austinzheng** [comment]
Sounds good! If you run into this, or any other problem again, please do file more tickets against us.
