### ISSUE TITLE
[PBUser objectsWhere] method crashed

### ISSUE THREAD

**Issue by iband2011** [realm/realm-cocoa#4978]
# [PBUser objectsWhere] method crashed

Hi:
I create a RLMObject model, ...
when i call [PBUser objectsWhere] method once, i get a list datas,
then in a nother place, I call [PBUser objectsWhere] method second, It crashed.
here is sth error message  below:

+[RLMObject objectsWhere:args:](NSString *, __va_list_tag *):
    0x10893bec8 <+0>:   pushq  %rbp
    0x10893bec9 <+1>:   movq   %rsp, %rbp
    0x10893becc <+4>:   pushq  %r15
    0x10893bece <+6>:   pushq  %r14
    0x10893bed0 <+8>:   pushq  %rbx
    0x10893bed1 <+9>:   pushq  %rax
    0x10893bed2 <+10>:  movq   %rdi, %r14
    0x10893bed5 <+13>:  movq   0xbc0d74(%rip), %rdi      ; (void *)0x000000010cfa1738: NSPredicate
    0x10893bedc <+20>:  movq   0xbae1d5(%rip), %rsi      ; "predicateWithFormat:arguments:"
    0x10893bee3 <+27>:  callq  *0x9dce67(%rip)           ; (void *)0x000000010e88bac0: objc_msgSend
    0x10893bee9 <+33>:  movq   %rax, %rdi
    0x10893beec <+36>:  callq  0x10913a56a               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10893bef1 <+41>:  movq   %rax, %r15
    0x10893bef4 <+44>:  movq   0xbae1c5(%rip), %rsi      ; "objectsWithPredicate:"
    0x10893befb <+51>:  movq   %r14, %rdi
    0x10893befe <+54>:  movq   %r15, %rdx
    0x10893bf01 <+57>:  callq  *0x9dce49(%rip)           ; (void *)0x000000010e88bac0: objc_msgSend
    0x10893bf07 <+63>:  movq   %rax, %rdi
    0x10893bf0a <+66>:  callq  0x10913a56a               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10893bf0f <+71>:  movq   %rax, %rbx
    0x10893bf12 <+74>:  movq   %r15, %rdi
    0x10893bf15 <+77>:  callq  *0x9dce4d(%rip)           ; (void *)0x000000010e888d20: objc_release
    0x10893bf1b <+83>:  movq   %rbx, %rdi
    0x10893bf1e <+86>:  addq   $0x8, %rsp
    0x10893bf22 <+90>:  popq   %rbx
    0x10893bf23 <+91>:  popq   %r14
    0x10893bf25 <+93>:  popq   %r15
    0x10893bf27 <+95>:  popq   %rbp
    0x10893bf28 <+96>:  jmp    0x10913a4a4               ; symbol stub for: objc_autoreleaseReturnValue
    0x10893bf2d <+101>: movq   %rax, %r14
    0x10893bf30 <+104>: movq   %r15, %rdi
    0x10893bf33 <+107>: callq  *0x9dce2f(%rip)           ; (void *)0x000000010e888d20: objc_release
    0x10893bf39 <+113>: jmp    0x10893bf3e               ; <+118> at RLMObject.mm:126
    0x10893bf3b <+115>: movq   %rax, %r14
    0x10893bf3e <+118>: movq   %r14, %rdi
    0x10893bf41 <+121>: callq  0x10913a6ba               ; symbol stub for: _Unwind_Resume

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. I assume `PBUser` is a subclass of `RLMObject`. Can you post the code where this crashes, as well as a stacktrace?

**Comment by austinzheng** [comment]
If this is still an issue for you, and you have the additional information for us requested previously, please feel free to re-open this ticket.
