### ISSUE TITLE
Realm do not write un background Thread

### ISSUE THREAD

**Issue by marinofaggiana** [realm/realm-cocoa#4981]
Hi,
I use realm for write a record in several thread ... but I have a issue ... example

Main Thread update a record ID = 100 Name = A result : (ok) 
Main Thread update a record ID = 100 Name = B result : (ok) 
Main Thread update a record ID = 100 Name = C result : (ok) 
Background Thread update a record ID = 100 Name = D result : (ok)  but on disk Name = C !???

No Error, the update are fast and the issue is random but frequent and repeatable 

```
let realm = try! Realm()
let result = realm.objects(tableMetadata.self).filter(predicate).first
if result != nil {
      try! realm.write {                
              result!.Name = variable
      }   
}
```

... Why ??? Where is the issue ?

Thanks a lot

**Comment by ppamorim** [comment]
Try this: https://realm.io/docs/swift/latest/#using-realm-with-background-app-refresh

**Comment by marinofaggiana** [comment]
Thanks.!
