### ISSUE TITLE
Schema inconsistency between TestFlight and AppStore builds

### ISSUE THREAD

**Issue by asalom** [realm/realm-cocoa#4982]
Hi,

We have the current situation:
We released a TestFlight build for some users with changes in the realm model objects and upgraded the Schema version from 1 to 2.
We later created another version with different model changes but we increased to schema version also from 1 to 2. This version we released into the App Store.
So now when the TestFlight users try to upgrade from TestFlight to AppStore version the app crashes because the models are different but the schema version are both 2 so the automatic migration doesn't work.

Old AppStore version has model A and schema version number 1
TestFlight version has model B and schema version number 2
New AppStore version has model C and schema version number 2

Migration from Old AppStore to New AppStore is fine.
Migration from TestFlight to new AppStore crashes because of a model missmatch with the same schema version number.

Do you have a suggestion on how to solve the issue without having to update the App Store build?

**Comment by jpsim** [comment]
I think your best option would be to push an updated TestFlight version that copies data from the affected Realm to a new one matching the schema version 0, 1 or 2 from the App Store variant of the app. Replace the affected Realm with this new one. Then when your TestFlight users move to the App Store version, it'll perform the migration to schema version 2 if needed.

**Comment by austinzheng** [comment]
If you have any further questions, or if you would like JP's suggestion clarified, please feel free to re-open this ticket and post your question.
