### ISSUE TITLE
swift3 - Wrong sort of RealmSwift - by Date

### ISSUE THREAD

**Issue by raphaels17** [realm/realm-cocoa#4997]
**Questions**: when sorting date realm results I have a wrong result   :-(

**Bugs**: here are the results  
![image](https://cloud.githubusercontent.com/assets/3678600/26755879/048cce46-4897-11e7-9f3b-2b392a3dbb90.png)

Thanks for helping us help you! :-)
-->

## Goals
being able to sort dates

## Expected Results
having dates in proper order

## Code Sample
reOrderedObjects = (Objects.sorted(){ (object1,object2) in
                
                object1.DateUTC  < object2.DateUTC ?? 
              })

## Version of Realm and Tooling

Realm framework version: 2.7.0

Realm Object Server version: ?

Xcode version: 8.3.2

iOS/OSX version: 10.12.4 

Dependency manager + version: ?

**Comment by bdash** [comment]
Your code sample appears to have been mangled. Can you please revise it to reflect the code you're using, and also include the definition of a) the model class on which you're sorting, and b) the collection variable that you're sorting (`Objects`, from what I can see).

**Comment by austinzheng** [comment]
If this is still an issue for you, feel free to reopen this ticket, providing us with the sample code @bdash asked for above (or, better yet, a sample project that demonstrates the issue). Thanks.
