### ISSUE TITLE
Multiple Realm instances from multiple frameworks causes Crashes

### ISSUE THREAD

**Issue by ahmadmuhsink** [realm/realm-cocoa#4999]
I am using 2 inhouse frameworks for my app. Both using Realm.
Let say framework A and framework B.

#### Objects
- Fact
- Input
- Action

#### Config
```
var config = Realm.Configuration(
    schemaVersion: 1,
    migrationBlock: { migration, oldSchemaVersion in },
    deleteRealmIfMigrationNeeded: true,
    objectTypes: [Input.self, Action.self]
)
```
and
```
var config = Realm.Configuration(
    schemaVersion: 1,
    migrationBlock: { migration, oldSchemaVersion in },
    objectTypes: [Fact.self]
)
```

#### Objects
- Sensor
- Datapoint

#### Config

None. use default realm configuration. bare `Realm()` to get realm instance.

### Problem

In our app. Whenever Framework B tries to access sensor or datapoint. It crash with the followng message :
```
Object type `Sensor` is not managed by the Realm. If using a custom `objectClasses` / `objectTypes` array in configuration, add `Sensor` to the list of `objectClasses` / `objectTypes`.
```
or
```
Object type `Datapoint` is not managed by the Realm. If using a custom `objectClasses` / `objectTypes` array in configuration, add `Sensor` to the list of `objectClasses` / `objectTypes`.
```

## Goals
Be able to use multiple frameworks that has multiple realm instances with different configurations.

## Expected Results
Framework B can access its own Objects.

## Actual Results
Crash.
```
Object type `Sensor` is not managed by the Realm. If using a custom `objectClasses` / `objectTypes` array in configuration, add `Sensor` to the list of `objectClasses` / `objectTypes`.
```

## Steps to Reproduce
Within your app. Use 2 or more frameworks that use Realm.
Use custom configuration for one of the framework and default realm configuration for another.

## Code Sample
All are private repos.
I may create sample repo if necessary but it will requires 2 frameworks and 1 sample app so it will not coming soon.

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

/Applications/Xcode.app/Contents/Developer
Xcode 8.3.2
Build version 8E2002

/Users/ahmadmuhsin/.rvm/gems/ruby-2.4.0/bin/pod
1.2.0
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.23.0
github "realm/realm-cocoa" "v2.7.0"

/usr/bin/git
git version 2.11.0 (Apple Git-81)
```

**Comment by austinzheng** [comment]
If you specify a custom array of object types in a Realm configuration, only objects of those types can be stored in the corresponding Realm. Why are you specifying the `objectTypes` argument? If you remove it the problem you are seeing should go away.

**Comment by ahmadmuhsink** [comment]
@austinzheng 
Thanks for the response.

First of all. Sorry I put wrong configuration before. 
I remove `deleteRealmIfMigrationNeeded: true` from Fact.self group.

>Why are you specifying the objectTypes argument?

Because on Framework A. I want to separate realm instance for 2 group of objects. Input group and Fact group. Fact group will less likely to change, can change in the future but not that frequent and also dont delete when migration occurs. While Input group may have a lot of changes, and also OK to delete when migration occurs.

Framework B doesnt really have this configuration and exist before Framework A so it still use Realm default configuration.

>If you remove it the problem you are seeing should go away.

I am not really sure if there is other way to have above requirements without separating Realm instances and using `objectTypes`

Any help would be much appreciated.

**Comment by austinzheng** [comment]
Can you provide additional code snippets? _How_ exactly is framework B working with Realms? Are they the same Realm files as the ones framework A are using? Are you passing Realm objects between framework A and framework B?

**Comment by ahmadmuhsink** [comment]
@austinzheng 
>How exactly is framework B working with Realms? Are they the same Realm files as the ones framework A are using?

Framework A use custom files : 
For this : 
```
var config = Realm.Configuration(
    schemaVersion: 1,
    migrationBlock: { migration, oldSchemaVersion in },
    deleteRealmIfMigrationNeeded: true,
    objectTypes: [Input.self, Action.self]
)
```

use `store.realm`
and
use `fact.realm` for this config :
```
var config = Realm.Configuration(
    schemaVersion: 1,
    migrationBlock: { migration, oldSchemaVersion in },
    objectTypes: [Fact.self]
)
```
---
Framework B use default file. like I said earlier use default Realm init. `try Realm()`

Framework B is used to store many sensors data. and thats it. Let say I want to record any accelerometer data. When I receive any accelerometer data, I store it on `Sensor` via Framework B.

Only app accessing Framework A and B. Each framework doesnt have any direct communication.

---
>Are you passing Realm objects between framework A and framework B?

No. Framework A and B are not passing any Realm Objects

---

> Can you provide additional code snippets?

which part of code snippets do you need?

**Comment by ahmadmuhsink** [comment]
@austinzheng 

I created sample app and sample frameworks to reproduce this crash.

App: 
https://github.com/ahmadmuhsink/RealmIssue4999

Frameworks:

https://github.com/ahmadmuhsink/FrameworkA
https://github.com/ahmadmuhsink/FrameworkB

Both frameworks use similar configuration like stated in this issue.

stack trace when crashing in sample app:
```
2017-06-08 14:44:50.283 RealmIssue4999[63031:1544943] *** Terminating app due to uncaught exception 'RLMException', reason: 'Object type 'Sensor' is not managed by the Realm. If using a custom `objectClasses` / `objectTypes` array in your configuration, add `Sensor` to the list of `objectClasses` / `objectTypes`.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112a5bb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010fdae141 objc_exception_throw + 48
	2   Realm                               0x000000011cd4fb70 _ZN13RLMSchemaInfoixEP8NSString + 110
	3   Realm                               0x000000011cd5fa8a RLMAddObjectToRealm + 239
	4   RealmSwift                          0x000000011c99ef6f _TFC10RealmSwift5Realm3adduRxs8SequenceWx8Iterator7Element_CS_6ObjectrfTx6updateSb_T_ + 943
	5   FrameworkB                          0x0000000111b05679 _TFFC10FrameworkB9FBStorage20insertOrUpdateSensorFT7sensorsGSaCS_6Sensor__T_U_FT_T__merged + 137
	6   RealmSwift                          0x000000011c99e728 _TFC10RealmSwift5Realm5writefzFzT_T_T_ + 56
	7   FrameworkB                          0x0000000111b077e6 _TFC10FrameworkB10FrameworkB9addSensorfT4nameSS7versionSi_T_ + 550
	8   RealmIssue4999                      0x000000010f7d66ea _TFC14RealmIssue499914ViewController11viewDidLoadfT_T_ + 490
	9   RealmIssue4999                      0x000000010f7d6a02 _TToFC14RealmIssue499914ViewController11viewDidLoadfT_T_ + 34
	10  UIKit                               0x000000011042301a -[UIViewController loadViewIfRequired] + 1235
	11  UIKit                               0x000000011042345a -[UIViewController view] + 27
	12  UIKit                               0x00000001102eb98a -[UIWindow addRootViewControllerViewIfPossible] + 65
	13  UIKit                               0x00000001102ec070 -[UIWindow _setHidden:forced:] + 294
	14  UIKit                               0x00000001102feebe -[UIWindow makeKeyAndVisible] + 42
	15  UIKit                               0x000000011027837f -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4346
	16  UIKit                               0x000000011027e5e4 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1709
	17  UIKit                               0x000000011027b7f3 -[UIApplication workspaceDidEndTransaction:] + 182
	18  FrontBoardServices                  0x000000011416b5f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	19  FrontBoardServices                  0x000000011416b46d -[FBSSerialQueue _performNext] + 186
	20  FrontBoardServices                  0x000000011416b7f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	21  CoreFoundation                      0x0000000112a01c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00000001129e70cf __CFRunLoopDoSources0 + 527
	23  CoreFoundation                      0x00000001129e65ff __CFRunLoopRun + 911
	24  CoreFoundation                      0x00000001129e6016 CFRunLoopRunSpecific + 406
	25  UIKit                               0x000000011027a08f -[UIApplication _run] + 468
	26  UIKit                               0x0000000110280134 UIApplicationMain + 159
	27  RealmIssue4999                      0x000000010f7d7b47 main + 55
	28  libdyld.dylib                       0x00000001139fb65d start + 1
	29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by bdash** [comment]
Thanks so much for taking the time to create and share a reproducible example for us!

The root of your problem is that FrameworkA [changes the default Realm configuration](https://github.com/ahmadmuhsink/RealmIssue4999/blob/d99a7b6b846bef4f86706c187946914b1f92c78c/Carthage/Checkouts/FrameworkA/FrameworkA/RealmHelper.swift#L26-L39):
```swift
var config = Realm.Configuration(
    schemaVersion: 1,
    // At the very minimum all we need to do is to update the version with an empty block to indicate that the schema has been upgraded (automatically) by Realm.
    migrationBlock: { migration, oldSchemaVersion in },
    deleteRealmIfMigrationNeeded: true,
    objectTypes: RealmGroup.factEngineGroup
)

// Use the default directory, but replace the filename
config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent(RealmFileUrl.factEngineUrl)

Realm.Configuration.defaultConfiguration = config

// …
let realm = try! Realm()
```

This means that when FrameworkB access the default Realm, it ends up using a class subset defined by FrameworkA's configuration.

Rather than changing the default configuration, FrameworkA should instead open a Realm that explicitly uses the custom configuration:

```swift
let realm = try! Realm(configuration: config)
```

**Comment by ahmadmuhsink** [comment]
@bdash 

Thanks for the proposed solution. I will try that in my real Frameworks. will report back soon.

**Comment by ahmadmuhsink** [comment]
This solved my issue. You can close it. Thanks
