### ISSUE TITLE
iOS 11 - Date equality issue when filtering

### ISSUE THREAD

**Issue by AndrewBarba** [realm/realm-cocoa#5002]
## Goals
After updating a device to iOS 11, I expect an app with Realm to behave as it did on iOS 10 (the app was not rebuilt for iOS 11)

## Expected Results
All `Results` filtered by a date, ex. `.filter("date == %@", self.date)`, are properly included if they have a matching date

## Actual Results
All `Results` filtered by a date, ex. `.filter("date == %@", self.date)`, are absent from the `Results`

## Steps to Reproduce
Working on this...

## Code Sample
Working on this...

## Version of Realm and Tooling
Realm framework version: 2.7.0
Xcode version: 9.0.0
iOS/OSX version: iOS 11.0

I know this isn't useful yet, but wanted to log the issue here and I will report back as I keep investigating. This is a critical bug for our application, as almost every screen is backed by a single date and results filtered based on that date (indexed in realm). I'm guessing this isn't even an issue with Realm, but something I need to file with Apple. Regardless, I wanted to log it here incase other's are experiencing a similar issue.

**Comment by AndrewBarba** [comment]
This is definitely an issue with iOS, I believe timezone related, but can confirm that it is not an issue with Realm and Dates

**Comment by jpsim** [comment]
Do you have a Swift JIRA bug number, or bug report on Open Radar so that we're aware of this?

**Comment by AndrewBarba** [comment]
I don't, but I narrowed it down to `NSTimeZone.defaultTimeZone`. I would set that to UTC when my app started, and even though `TimeZone` in swift 3 doesn't have that property it seemed to respect it. However on iOS 11 setting that does not seem to be respected else where so I had to update the way I was dealing with dates in my controllers.

If/when I file/find a radar I will post here

**Comment by jpsim** [comment]
Thanks, I appreciate you keeping us in the loop!
