### ISSUE TITLE
Carthage + Xcode 9: Build error

### ISSUE THREAD

**Issue by beseder42** [realm/realm-cocoa#5003]
## Goals

Build Realm with Carthage and Xcode 9

## Expected Results

It builds without error.

## Actual Results

It fails with this error:

`Carthage/Checkouts/realm-cocoa/RealmSwift/RealmCollection.swift:35:38: error: cannot use mutating member on immutable value: 'generatorBase' is a 'let' constant
        let accessor = unsafeBitCast(generatorBase.next() as! Object?, to: Optional<T>.self)`

## Version of Realm and Tooling

Realm framework version: Newest Master commit: 778017d76fb61699ac6c02979a350f0539889f8b

Xcode version: 9 Beta1

iOS/OSX version: iOS 11

Dependency manager + version: Carthage 0.23

**Comment by austinzheng** [comment]
This will be fixed when https://github.com/realm/realm-cocoa/pull/5006 lands.

**Comment by tirrorex** [comment]
@austinzheng hi, will this be made available for cocoapods also?
I fail to see why a working code in swift 3.2 doesn't compile on the new version of xcode, seems like feeling a radar would be the way to go.

**Comment by austinzheng** [comment]
Yes, feel free to file radars. We've already found a number of regressions involving our existing code base when compiling with the 3.2. compiler.

**Comment by NasirMalik** [comment]
I am facing same issue with Cocoapods. Can you tell me how to solve the issue?

**Comment by austinzheng** [comment]
Please create a new issue, and fill out the issue template completely. Thanks!
