### ISSUE TITLE
Array (ont to many relation)

### ISSUE THREAD

**Issue by ahegazi18** [realm/realm-cocoa#5004]
## Goals

I am trying to add object that have array object inside.

## Expected Results

that the data is inserted in Realm and stored there.

## Actual Results

that the data is only saved in the data base as long as the app is running once i close the app and open it again the 2 arrays i have inside the object become empty (this happened if i only re - opened the app using Xcode ), not by closing and open the app from iPhone

## Code Sample

```swift
class ExpensesRealm: Object {
    
    func incrementID() -> Int {
        
        let realm = try! Realm()
        return (realm.objects(ExpensesRealm.self).max(ofProperty: "expenseId") as Int? ?? 0) + 1
    }

    dynamic var expenseId : Int = 0
    dynamic var createDate : NSDate = NSDate()
    dynamic var amount : String?
    dynamic var date : String?
    dynamic var merchant : String?
    dynamic var purpose : String?
    dynamic var merchantPlaceholder : String? = ""
    dynamic var category : CategoryRealm?
    dynamic var currency : CurrencyRealm?
    let receiptIds = List<ReceiptsIdRealm>()
    let images = List<ExpensesImagesRealm>()
    
    override static func primaryKey() -> String? {
        
        return "expenseId"
    }
}

class ReceiptsIdRealm : Object {
    
    dynamic var id : String?
}

class ExpensesImagesRealm: Object {

    dynamic var uuid : String?
}

```
and that's how i insert and get the data from `Realm`

```swift
private func selectWithoutFilter(type : AnyClass) -> Results<Object> {

		let realm = try! Realm()
		return realm.objects(type as! Object.Type)
	}
func insertInDataBase(object : Object) {

		let realm = try! Realm()

		try! realm.write {

			realm.add(object)
		}
	}

```

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. It's not clear how you are using `insertInDataBase()` or how you are constructing your objects. Please put together a reproduction case demonstrating the behavior you're seeing. You can either attach it to this ticket or email it to help@realm.io.

**Comment by austinzheng** [comment]
If you're still having this problem, feel free to reopen this ticket, providing us with the information we requested above. At the very least we'll need to see the definitions for all the non-Realm methods in your code sample that perform any sort of non-trivial work, as well as your model definitions. Thanks.
