### ISSUE TITLE
Realm.refresh() blocks upwards of 5 minutes after 2.6.2

### ISSUE THREAD

**Issue by onesupercoder** [realm/realm-cocoa#5007]
## Goals
Keep multiple instances of realm in sync across background threads

## Expected Results
Realm.refresh() is pretty quick on 2.6.2.  After that all time stands still.

## Actual Results
No crash, just locks up for several minutes

## Steps to Reproduce
RealmSwift 2.8.0 realm.refresh in 3 background threads of a db greater than 7mb with active writes running in the foreground.

## Code Sample
There are too many writes and reads across too many files.  If needs be i will create a sample application to reproduce it, i would just think you guys have one for this.  I may be calling refresh too often which is a problem on my part, but i do have so many different threads reading and writing it is kind of necessary.  When i eliminate the refresh i get unexpected results and data all over the place and on 2.6.2 it works great, after that all write transactions and refreshes are nearly unusable.  Thanks for your help.

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

/Applications/Xcode.app/Contents/Developer
Xcode 8.3.2
Build version 8E2002

/Users/jaredmdobson/.rbenv/shims/pod
1.2.1
Realm (2.8.0)
RealmSwift (2.8.0)
Realm (= 2.8.0)
RealmSwift (= 2.8.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

carthage not found
(not in use here)

/usr/bin/git
git version 2.11.0 (Apple Git-81)
```

**Comment by austinzheng** [comment]
It would be best if you could build us a sample application. If we had one already, we would have fixed the problem by now :). Please attach it here or send it to help@realm.io.
