### ISSUE TITLE
'Target table row index out of range' realm2.8.0 just in release crashed ！！！

### ISSUE THREAD

**Issue by icoder20150719** [realm/realm-cocoa#5008]
2017-06-07 21:45:49.432367+0800 Cashier[11261:4530714] *** Terminating app due to uncaught exception 'RLMException', reason: 'Target table row index out of range'
*** First throw call stack:
(0x190cfafd8 0x18f75c538 0x101eebb5c 0x101ecf910 0x101ed3f4c 0x101ed4e48 0x101ed4918 0x101eebfc4 0x101eeba7c 0x101ecf910 0x101ed3f4c 0x101ed4e48 0x101ed4918 0x101eebfc4 0x101eeba7c 0x101ecf910 0x101ed3f4c 0x101ed4e48 0x101ed4918 0x101eebfc4 0x101eeba7c 0x100228c20 0x100515dd0 0x100507704 0x1004c26f4 0x100295434 0x196e580ec 0x196e5806c 0x196e425e0 0x196e57950 0x1973ec46c 0x1973e87b8 0x190ca89a0 0x190ca6628 0x190ca6a74 0x190bd6d94 0x192640074 0x196e88130 0x1000f04e8 0x18fbe559c)
libc++abi.dylib: terminating with uncaught exception of type NSException

![image](https://user-images.githubusercontent.com/13404370/26882117-08c8d238-4bcc-11e7-8e87-7ee2960ea9bf.png)

Realm framework version: 2.8.0
Xcode version: 8.3

iOS/OSX version: 10.3.1

Dependency manager + version: ?

**Comment by icoder20150719** [comment]
![image](https://user-images.githubusercontent.com/13404370/26882185-42e23a7c-4bcc-11e7-9603-ba590b0e557d.png)

**Comment by icoder20150719** [comment]
Can you help me ?

**Comment by icoder20150719** [comment]
![image](https://user-images.githubusercontent.com/13404370/26882401-e2941afe-4bcc-11e7-9264-cace6bead628.png)
just in release crashed ！！！

**Comment by austinzheng** [comment]
Can you provide us with a reproduction case, or at least more of your code and the inputs that cause the problem to crash, including the `RLMOrder` definition and whatever code you are using to create and set it up before starting the write transaction?

**Comment by icoder20150719** [comment]
![image](https://user-images.githubusercontent.com/13404370/26909136-745eabde-4c31-11e7-8c99-e402ac3ba4ec.png)

**Comment by icoder20150719** [comment]
![image](https://user-images.githubusercontent.com/13404370/26909197-cef52d8e-4c31-11e7-8339-2f79b0bca287.png)
![image](https://user-images.githubusercontent.com/13404370/26909198-d3693482-4c31-11e7-91d4-edd098896bf0.png)

**Comment by icoder20150719** [comment]
and NSLog RLMOrder object print this:
![image](https://user-images.githubusercontent.com/13404370/26909266-33048996-4c32-11e7-9396-15154f763cb9.png)

**Comment by icoder20150719** [comment]
Can you guess what went wrong?

**Comment by kishikawakatsumi** [comment]
@icoder20150719 Sorry for the delay. Could you create a sample Xcode project along with exact steps for us to reproduce? Or please send the entire project that reproduces the bug? You could send it privately to us at help@realm.io if you don't wish to share this publicly. Without understanding your code it's difficult to make any progress. If you do we'd be happy to continue looking into the problem. Thanks!

**Comment by jpsim** [comment]
@icoder20150719 I'm just following up on @kishikawakatsumi's request for a sample project that would allow us to debug this for you. Thanks!

**Comment by icoder20150719** [comment]
@jpsim thanks  a lot;
we has find the  problem that is my code ;my orderModel has a property  without managed by realm;
i am very sorry ;
thank you again;

**Comment by austinzheng** [comment]
No problem! Feel free to file new issues if you run into any other problems!

**Comment by ivanicspeter92** [comment]
I came along the same error message and crash today after upgrading from Realm 2.1.2 to 2.10.1. The crash happens on iOS 11 and iOS 10 devices and simulators constantly, when the execution reaches the realm.add() function call in the following snippet:

```  
  func insertOrUpdate(object: Object) {
        do {
            let realm = try Realm()
            
            try realm.write {
                realm.add(object, update: true) // crash here: Target table row index out of range
            }
        } catch let error {
            log.error(error.localizedDescription)
        }
    }
```

This happens only for some of my Object subclasses, which seemingly share no similarity between one another. If I comment the add() call out, my application runs smoothly without any problems by the way.
