### ISSUE TITLE
RealmSwift 2.7.0 -> 2.8.0 strange list behaviour change

### ISSUE THREAD

**Issue by owenbirdsall** [realm/realm-cocoa#5009]
I've just updated to version 2.8.0 and found an issue when copying list objects

Previously I could write:
`newVersionOfObject.listVar = oldVersionOfObject.listVar`

All the objects in listVar would remain when oldVersionOfObject was overwritten

Since the 2.8.0 update the objects are all removed when oldVersionOfObject is overwritten, even though they are now referenced by newVersionOfObject.listVar

If, rather than doing a simple assignment operation, I iterate over oldVersionOfObject.listVar and append each object to newVersionOfObject.listVar, it will behave as it did before.

Was this an intentional change?

## Version of Realm and Tooling

Realm framework version: 2.8.0

Realm Object Server version: ?

Xcode version: 8.3.3

iOS/OSX version: 10.3.2

Dependency manager + version: Cocoapods 1.1.1

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. Realm's `List<T>` isn't a Swift-like COW collection, and you shouldn't expect assigning a list property to copy the elements from the source list into the destination list, so this was probably knock-on behavior from other bug fixes that were folded into 2.8.0. If you need to copy the elements of a list from one list into another, please copy them manually.

**Comment by owenbirdsall** [comment]
Yes, I suspected it must have been something along those lines, given that there was no mention of it in the change log. Thanks for clarifying Realm's List<T> assignment behaviour, appreciate the quick response.
