### ISSUE TITLE
Clarification shouldCompactOnLaunch documentation 

### ISSUE THREAD

**Issue by bb-git** [realm/realm-cocoa#5010]
The example in the documentation (https://realm.io/docs/swift/latest/#compacting-realms) is not very clear to me, as I don't know if the compaction could be called all the time during app use or only once at startup. Is the implementation below correct or would it be better to make a separate config including shouldCompactOnLaunch to call once on app launch. 

If I add shouldCompactOnLaunch to the default configuration I see the block being called every time I create a realm instance.

            Realm.Configuration.defaultConfiguration = Realm.Configuration(schemaVersion: schemaVersion, migrationBlock: migrationBlock,shouldCompactOnLaunch: { totalBytes, usedBytes in
            // totalBytes refers to the size of the file on disk in bytes (data + free space)
            // usedBytes refers to the number of bytes used by data in the file
            
            // Compact if the file is over 100MB in size and less than 50% 'used'
            let oneHundredMB = 100 * 1024 * 1024
            print ("totalbytes \(totalBytes)")
            print ("usedbytes \(usedBytes)")
            if (totalBytes > oneHundredMB) && (Double(usedBytes) / Double(totalBytes)) < 0.7{
                print("will compact realm")
            }
            return (totalBytes > oneHundredMB) && (Double(usedBytes) / Double(totalBytes)) < 0.7
        })
        do {
            // Realm is compacted on the first open if the configuration block conditions were met.
            _ = try Realm(configuration: config)
        } catch {
            // handle error compacting or opening Realm
        }

And one more thing would be interesting to me: What happens if the compaction fails? Too little storage would be a reason. Will I still be able to access the data and the compaction will just be skipped?

**Comment by kishikawakatsumi** [comment]
@bb-git `shouldCompactOnLaunch` block is invoked again if the Realm instance is cleared from internal cache. It's intended behavior.

For the second question, the compaction operation reads the entire contents of the Realm file, rewrites it to a new file at a different location, then replaces the original file. So if compaction fails or skipped, it is not replaced the original file. So you can still access the data.

**Comment by bb-git** [comment]
So what's the best practise then? 
I now made a seperate config for the compaction in the app delegate and did not include the compaction in the default configuration, so if necessary it should be done on app launch.

As you manage everything now, I guess there is no autoreleasepool needed for the realm instance that includes compaction in the config in this configuration?

Thanks

**Comment by kishikawakatsumi** [comment]
@bb-git If you do not need to handle multiple configurations (it means your app doesn't have multiple Realm files), the best practice is setting the configuration to default configuration once, then use `try! Realm()`.

No autorelease block is needed. The compaction process is all done by Realm. The only situation which autorelease block needed is multi-threading. Use autorelease block to avoid unintentional version pinning. Please see https://realm.io/docs/swift/latest/#threading

**Comment by bb-git** [comment]
So I'm doing it like this now:
```
        let config = Realm.Configuration(schemaVersion: schemaVersion, migrationBlock: migrationBlock,shouldCompactOnLaunch: { totalBytes, usedBytes in
            // totalBytes refers to the size of the file on disk in bytes (data + free space)
            // usedBytes refers to the number of bytes used by data in the file
            
            // Compact if the file is over 20MB in size and less than 60% 'used'
            let twentyMB = 20 * 1024 * 1024
            return (totalBytes > twentyMB) && (Double(usedBytes) / Double(totalBytes)) < 0.6
        })
        do {
            // Realm is compacted on the first open if the configuration block conditions were met.
            _ = try Realm(configuration: config)
        } catch {
            // handle error compacting or opening Realm
        }
        
        Realm.Configuration.defaultConfiguration = Realm.Configuration(schemaVersion: schemaVersion, migrationBlock: migrationBlock)
```
I guess this is also fine, as it all happens on the same thread? I'm just afraid of data loss.

I will have a look in using autoreleasepools on background threads, as I suffer from rapidly growing database size without this size really being necessary and used.

**Comment by kishikawakatsumi** [comment]
> I guess this is also fine, as it all happens on the same thread? I'm just afraid of data loss.

Correct, it's fine. And it all happens on the main thread.

**Comment by DaveWoodCom** [comment]
@kishikawakatsumi Came here via the StackOverflow question: https://stackoverflow.com/q/44407812/144857

I'm seeing the same issue as @bb-git, where the `shouldCompactOnLaunch` block is being called excessively. Here's my configuration:

        var realmConfig: Realm.Configuration = Realm.Configuration.defaultConfiguration
        realmConfig.fileURL = ....
        realmConfig.shouldCompactOnLaunch = { (totalBytes: Int, usedBytes: Int) -> Bool in
            guard totalBytes > 100 * 1_048_576 else { return false }
            guard Double(usedBytes) / Double(totalBytes) < 0.5 else { return false }
            log.warning("Should compact Realm database: \(usedBytes) / \(totalBytes)")
            return true
        }

I'm seeing this `shouldCompactOnLaunch` block called constantly, whenever I'm updating objects. In one place in my code I'm updating hundreds of objects, and `shouldCompactOnLaunch` is being called over 100 times per second. This doesn't feel correct, since it's no longer 'on launch', and Realm isn't acting on a `true` value anyway at this point as the file isn't compacted until the next app launch.

Also, Realm seems to be caching this block, because even if I set it to `nil` at some point later, the block still fires.

Is this really expected behaviour? If so, I'm tempted to stop setting `shouldCompactOnLaunch` on most app launches, and perhaps just have it set every 25th app launch or something.

Let me know if you'd like a sample project or any other info.

Thanks.

**Comment by tgoyne** [comment]
It looks like current the compactOnLaunch block is called each time a Realm is opened on a new thread, even if that Realm is already open on other threads.

Why is this a problem for you? Is it just that you're logging messages from within the block? The overhead of calling it too often should be unmeasurably small compared to the time it takes to open the Realm at all.

**Comment by jpsim** [comment]
I have some fixes for this awaiting review in https://github.com/realm/realm-object-store/pull/496 and https://github.com/realm/realm-cocoa/pull/5114.

**Comment by DaveWoodCom** [comment]
@tgoyne Sorry for the delay, got distracted. That makes sense for what I was seeing.

I've worked around this issue for now by using an `autoreleasepool` on app start up.  I use a Realm Config with a `shouldCompactOnLaunch` block, have it do the check, then exit the pool and set up a Realm stack without the `shouldCompactOnLaunch` block. Seems to be working much better now.

**Comment by liuxuan30** [comment]
@kishikawakatsumi sorry to dig this up, but really the compacting happens on main thread? Won't i slow down UI tasks?

**Comment by tgoyne** [comment]
The compaction happens on the thread that you first open a Realm on. This typically means that when it happens it will delay your application launch and have no impact after that.

**Comment by liuxuan30** [comment]
So should I put it on background queue like in applicationDidFinishLaunch? Can I add `shouldCompactOnLaunch` block as a default Realm configuration?
