### ISSUE TITLE
Updating a saved object in swift

### ISSUE THREAD

**Issue by LamourBt** [realm/realm-cocoa#5014]
Hello realmers, 
Since I do not wish to delete the object from realm, I want to update a member of that class and save it.

```
class GItem: Object {
  dynamic var id = ""
  //... other properties 
  dynamic var isMoved = false  // I wish to change this member field to true
  override static func primaryKey()-> String? {  return "id" }
}
```

 **I have `Realm` into a Generic Object with CRUD operation (yes the operation works).**

``let service =  try?  RealmService<GItem>(withRealm:Realm())`` 

**First Case, query item, modify field and save it**

```
guard let item = try! service.query().filter ({$0.id == someId }).first else { return }
item.isMoved = true
 try! service.save(object: item, update: true) 
```

I go the following error, 

>  Error when saving directly after change 
                 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'

I read in the docs that realm doesn't operate in the same thread, so wrapped the code around `beginWrite & commitWriting` would refreshed the object.. (I did try it) nada :(  same error.

**Second Case, create a deep copy of that object using Object**

Thus in my service object, I have a method that return a new object from the current one ``

 ```
func deepCopy(object:T) ->T {  // where T:Object 
       let new =  Object.init(value: object)
        return new as! T
  }
```
so  after I query the item, i create a newItem and modified it  
```
let newItem = service.deepCopy(object: item)
newItem.isMoved = true
try! service.save(object: newItem, update: true) 

```
I go the following error

> +[RealmSwiftObject defaultPropertyValues]: unrecognized selector sent to class 0x110a0d0f8
2017-06-09 15:12:40.519 Nesty[69519:1195807] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RealmSwiftObject defaultPropertyValues]: unrecognized selector sent to class 0x110a0d0f8'

**Comment by austinzheng** [comment]
Did you wrap your _entire_ code block within a write transaction? Can you show us the code sample where you attempted to use a write transaction, and the entire body of that method?

**Comment by LamourBt** [comment]
```
service.writting() // beforeWrite()
item.isMoved = false 
try! service.save(object: item, update: true)  // i wasn't to sure this, it seems it should create a new 
try! service.commit() // commitWritting   
```

>  Terminating app due to uncaught exception 'RLMException', reason: 'The Realm is already in a write transaction'

**Comment by austinzheng** [comment]
I can only guess as to what your helper methods are doing, but `save()`ing the object after you've changed one of its properties is unnecessary. If you are in a write transaction with an object that you retrieved from a Realm (as you did above, with your queries), and you change any of its property values, the changes are automatically saved once you commit the write transaction.

Furthermore, you can't nest write transactions, and it looks like your `save()` method starts a write transaction, so that's why you're getting that error.

**Comment by LamourBt** [comment]
so you are saying after `item.isMoved = true`, i should just `commitWriting()` instead of saving

**Comment by austinzheng** [comment]
Yes, exactly. Try that and let us know if it works.

**Comment by LamourBt** [comment]
yes sir you just save my life lol and I thank you for your help :) 👍 💯

**Comment by austinzheng** [comment]
Awesome!

Just for future reference, our [`addOrUpdate()` method](https://realm.io/docs/objc/2.8.0/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)addOrUpdateObject:) is intended if you want to either add a new object or update an existing object without manually checking to see if it already exists, or if you want to populate an object using something like a JSON dictionary.
