### ISSUE TITLE
msg __NSCFString * "mmap() failed: Cannot allocate memory size: 3489660928 offset: 0" 0x0000000157ea14c0

### ISSUE THREAD

**Issue by naoya0731** [realm/realm-cocoa#5018]
(iOS application issue)

We forgot to put a feature to compact realm database.
so our app that realm db increased memory size cannot launch with below error.

`msg __NSCFString * "mmap() failed: Cannot allocate memory size: 3489660928 offset: 0" 0x0000000157ea14c0`

We tried `shouldCompactOnLaunch`. However our app's realm database is already too big to execute this method.

Is there any way to execute a compaction for too big realm database?

**Comment by kishikawakatsumi** [comment]
@naoya0731 There is no way to rescue the Realm file that already exceeded a `mmap()` limitation on the same device. I'm sorry for hitting the issue. The only way is to transfer the file to another device that has a bigger memory limit (e.g. Simulator on Mac), then perform the compaction on that device.

**Comment by naoya0731** [comment]
@kishikawakatsumi thanks. I got it.
