### ISSUE TITLE
Swift 4 LinkedObjects results in the swift compiler crashing

### ISSUE THREAD

**Issue by hishnash** [realm/realm-cocoa#5019]
I know this is most likely a bug with the swift4 compiler and not an issue with your code but if you could enlighten me a little as to what might be happing on this line so that I can better reproduce this in a way for the swift4 team that does not depend upon a third party lib it would help to get it fixed faster.

## Goals
Add a reverse reference

## Expected Results
Swift4 compiles

## Actual Results
Swift4 compiler segfaults
`Command failed due to signal: Segmentation fault: 11`

https://gist.github.com/hishnash/54e8b713430d3d4568fb137a9cbc9529

## Steps to Reproduce
Create an object that has a one-to-many relationship to itself then add a Link back over that relationship and compile...
  
## Code Sample
```swift

import Foundation
import RealmSwift

class Frame: Object {
    @objc dynamic var created: NSDate? = nil
    @objc dynamic var isUpstream: Bool = false
    
    enum Direction {
        case upstream
        case downstream
    }
    
    var direction: Direction {
        get {
            if self.isUpstream {
                return .upstream
            }
            return .downstream
        }
        set {
            switch newValue {
                case .upstream:
                    self.isUpstream = true
                default:
                    self.isUpstream = false
            }
        }
    }
    
    // Frames that make up this frame, eg HTTP server side events etc
    let subFrames = List<Frame>()
    
    // Frames that are associated with this one, eg responses to this request
    
    let associatedFrames = List<Frame>()
    let inverseAssosatedFrames = LinkedObjects(fromType: Frame.self, property: "associatedFrames")
\
}
```

if I remove 
```swift
let inverseAssosatedFrames = LinkedObjects(fromType: Frame.self, property: "associatedFrames")
```
then it compiles no issue.

## Version of Realm and Tooling 

Realm Framework version:   `master` https://github.com/realm/realm-cocoa/commit/217fb6d6830c9c079b00c1fc5655257521721ee0

Xcode version: Version 9.0 beta (9M136h)

iOS/OSX version: 10.13 Beta (17A264c)

Dependency manager + version: CocoPods 1.2.1

**Comment by bdash** [comment]
One thing that sticks out to me is the reference to `LinkedObjects`. Is that name the type you're intending to use? There's a similar Realm type named `LinkingObjects`.

**Comment by hishnash** [comment]
oh... I see the typo... yer i meant to use `LinkingObjects ` strange i don't have `LinkedObjects` defined anywhere.
