### ISSUE TITLE
how to install realm

### ISSUE THREAD

**Issue by common-infyom** [realm/realm-cocoa#5022]
## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by hishnash** [comment]
I suggest using CocoPods

first set up your xcode project to support cocopods:
https://guides.cocoapods.org/using/getting-started.html

# then if you are using xcode8 (swift3)

add 
```
pod 'Realm' 
```
to the `target` section of your `Podfile`

and in the terminal run `pod install`

# if you are testing xcode9 (with swift4)
add
```
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', submodules: true
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', submodules: true
```
to your pod file and run the `pod install`

**Comment by austinzheng** [comment]
Please read our instructions for [Objective-C](https://realm.io/docs/objc/latest/#getting-started) or [Swift](https://realm.io/docs/swift/latest/#getting-started). Thanks.
