### ISSUE TITLE
Align notification API with Swift 4 KVO API

### ISSUE THREAD

**Issue by tgoyne** [realm/realm-cocoa#5025]
Swift 3.2/4's new block-based API for KVO is similar enough to our existing API for notifications that we should probably make them the same whereever possible.

Some things we may want to do:

1. Rename `stop()` to `invalidate()`, with a deprecated alias for Swift <4. It's a little unfortunate that we already use `invalidate()` for something different, but it doesn't directly conflict.
2. Rename `addNotificationBlock` to `observe()`. I think this won't conflict with using the native `observe()` method on objects (the KVO one requires a keypath argument), but need to double-check. Does this have the potential to be confusing? We already see some confusion between our `filter()` method on `Results` and the Swift-native `filter()` method.
3. Remove `NotificationToken` from the API entirely and return `NSKeyValueObservation`. Probably a bad idea.

If we do rename things, should we also do the same for objective-c?

**Comment by austinzheng** [comment]
I'm going to provisionally put the `breaking` tag on this, because it's conceivable we could make it as a breaking change for 3.0 if the timeframe works. If we think it's better to not break the API even across 2.* to 3.0, I'll remove the tag.

**Comment by jpsim** [comment]
> Rename `stop()` to `invalidate()`

Sure.

> Rename `addNotificationBlock` to `observe()`

Definitely.

> Remove `NotificationToken` from the API [...] Probably a bad idea.

Agreed, let's not do that.

---

Let's keep this as `breaking`. The fewer ways to do the same thing, the better.

**Comment by jpsim** [comment]
Done in #5193.
