### ISSUE TITLE
Ability to inspect permissions for an arbitrary SyncUser 

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-cocoa#5031]
## Goals

As Admin have the ability to introspect permissions for an arbitrary ROS user either by ID or to to get a SyncUser by ID and then call the retrieve permissions for that user.

## Expected Results

I should be able to, as an admin, get permissions listing for any user known to the system

## Actual Results

Currently permissions can inly be examined for the current user, e.g.:

```swift 
SyncUser.current?.retrievePermissions { permissions, error in
  if let error = error {
    // handle error
    return
  }
  // success! access permissions
}
```
as described in https://realm.io/docs/swift/latest/#retrieving-permissions

## Steps to Reproduce
N/A

## Code Sample

N/A
## Version of Realm and Tooling

Realm framework version: RealmSwift version 2.8.0

Realm Object Server version: ? NA

Xcode version: ? 8.3.2

iOS/OSX version: ? 10.12.5

Dependency manager + version: ? N/A

**Comment by dhmspector** [comment]
Actually both would be useful - not having to iterate over a potentially long list of permissions would be great to have too

**Comment by astigsen** [comment]
This Function allows you to get a list of all realms for a given user and what permissions that user has to the realms: https://github.com/realm/realm-sync-demos/tree/master/realmsearch

**Comment by dhmspector** [comment]
ah - cool - a little deep for this demo of the AsyncOpen() bug .. but will come in handy for some other apps :)

**Comment by astigsen** [comment]
In general those things are really easy to implement as Functions, we just need a lot of examples.

**Comment by dhmspector** [comment]
of course, the inverse - being able to supply a Realm and get all its permissions would be super useful. (pretty sure we already have a ticket for that...)

**Comment by astigsen** [comment]
You can do that with a small modification of the above Function:

```javascript
const Realm = require('realm');
const server_url        = 'realm://localhost:9080';
const REALM_ADMIN_TOKEN = "INSERT ADMIN TOKEN HERE!";
const adminUser = Realm.Sync.User.adminUser(REALM_ADMIN_TOKEN);

console.log("Starting realm search function");


var adminRealm = null;
Realm.openAsync({sync: {user: adminUser, url: server_url + '/__admin'}},
        (error, realm) => {
          adminRealm = realm;
          console.log("Admin Realm loaded");
        });


console.log("Registering change handler");

module.exports = function(changeEvent) {
    console.log("changes in:", changeEvent.path);
    var r = Realm; // keepalive
    
    if (adminRealm == null) {
        console.log("Error: admin realm not loaded");
        return;
    }
    
    // only do work if there are requests
    const changes = changeEvent.changes["RealmPermissions"];
    if (typeof changes === "undefined" || changes.insertions.length == 0)
        return;
    
    const searchRealm = changeEvent.realm; // workaround for GN returning new instance on every access
    const requests    = searchRealm.objects("RealmPermissions");
    const realms = adminRealm.objects('RealmFile');
    const permissions = adminRealm.objects('Permission');
    
    // Get the permission list for a given realm
    searchRealm.write(() => {
        changes.insertions.forEach((index) => {
            const obj = requests[index];
            
            const target_realms = realms.filtered("path == $0");
            
            if (target_realms.length == 0) {
                obj.status = "Error: invalid realm path";
                return;
            }
            const target_realm = target_realms[0];
            
            const matches = permissions.filtered("file == $0", target_realm);
                
            matches.forEach((match) => {
                obj.permissions.push({userid: match.user.id, read: match.mayRead, write: match.mayWrite, manage: match.mayManage});
            });
            
            obj.status = "success";
        });
    });
};
```

**Comment by mrackwitz** [comment]
As admin user you've also the privileges to open the user-specific permission-Realm (`/userA/__permission`) and inspect all the relevant permissions for that user. That isn't exposed though by convenience APIs.

**Comment by jpsim** [comment]
Product-level feature requests like these should really be tracked and discussed in the product issue tracker to open up the discussion and design to all products. Closing.
