### ISSUE TITLE
Set deleteRealmIfMigrationNeeded depending on schemaVersion

### ISSUE THREAD

**Issue by dmorrow** [realm/realm-cocoa#5034]
## Goals && Expected Results
I have an existing app with multiple schema versions.  For a major feature change (and a bunch of object renaming), I'd like to just delete the Realm and start from scratch.  It would be great if I could specify the deleteRealmIfMigrationNeeded based on the schema version, similar to the method to specifying specific migrations.

**Comment by kishikawakatsumi** [comment]
@dmorrow `deleteRealmIfMigrationNeeded` flag doesn't have such conditional feature. But you can do that easily to combine [`schemaVersionAtURL(_:encryptionKey:)`](https://realm.io/docs/swift/latest/api/Functions.html#/s:F10RealmSwift18schemaVersionAtURLFzTV10Foundation3URL13encryptionKeyGSqVS0_4Data__Vs6UInt64) method. It can let you know the schema version of the file. So you can change the behavior for each schema versions. Like the following:

```swift
if schemaVersionAtURL(fileURL) < 9 {
    config. migrationBlock = { ... }
} else {
    config. deleteRealmIfMigrationNeeded = true
}
```

**Comment by dmorrow** [comment]
@kishikawakatsumi Thanks for this recommendation.  I've tried it, but now I seem to have put Realm in an unstable condition.  Having set the config to deleteRealmIfMigrationNeeded, the Realm file is not being recreated and is throwing errors when I try to access it.

**Comment by kishikawakatsumi** [comment]
@dmorrow Could you share your code around that or entire project?

If you have a Realm instance as a property of ViewController, like the following, it will be called by the Storyboard BEFORE `applicationDidFinishLaunching:`. In that case, Realm will be instantiated before setting `deleteRealmIfMigrationNeeded`.

```swift
class ViewController: UIViewController {
    let realm = try! Realm()
}
```

To avoid this issue, make it `lazy` variable.

```swift
class ViewController: UIViewController {
    lazy var realm = try! Realm()
}
```

**Comment by dmorrow** [comment]
I rolled back my code, recreated the Realm and then tried to reproduce the issue.  I could not.  For reference, I am configuring my migration block and other Realm configs in the `didFinishLaunchingWithOptions`, and then first accessing the Realm in a VC `viewWillAppear`, so sequencing shouldn't have been an issue.  I'm not really clear what happened, but its not happening any further.

**Comment by kishikawakatsumi** [comment]
Closing it seems resolved. Feel free to reopen if you have any further questions, thanks.

**Comment by dmorrow** [comment]
@kishikawakatsumi I am still having issues, which probably means I don't fully understand how `deleteRealmIfMigrationNeeded` works.

While I am doing a major change to my Realm, I have something like this set
```
var config = Realm.Configuration(
            schemaVersion: schemaVersion,
            migrationBlock: migrationBlock)
if let path = Realm.Configuration.defaultConfiguration.fileURL, try schemaVersionAtURL(path) < 100 {
    config.migrationBlock = nil
    config.deleteRealmIfMigrationNeeded = true
}
```

The first time, this works well.  However, if I make additional changes without updating the `schemaVersion` that I pass to the config object then I get a crash when I try to access the Realm.  The error states

> Directory at path '/Users/***/Library/Developer/CoreSimulator/Devices/42BFE373-4547-4B47-917B-7BCF874F54D6/data/Containers/Data/Application/9DEF2E22-0A58-4FB8-A1B7-4C49B71B6269/Documents/default.realm' does not exist."

Do I need to increment the `schemaVersion` even if I am always deleting the Realm?
