### ISSUE TITLE
Using Realm in an iOS framework

### ISSUE THREAD

**Issue by kanishkatn** [realm/realm-cocoa#5036]
## Goals
I want to add realm to my iOS framework project

## Expected Results
Compile without errors

## Actual Results

I am getting an error saying "framework not found Realm for architecture x86_64" at runtime.

## Steps to Reproduce
Add realm to a framework and run the test

## Version of Realm and Tooling

Realm framework version: realm-swift-2.8.0

Xcode version: 8.3.1

iOS/OSX version: OS X Sierra 10.12.2

**Comment by kishikawakatsumi** [comment]
It resolved, I chatted with him at another place.
