### ISSUE TITLE
App Stuck on 'try Realm()' when upgrading from previous version

### ISSUE THREAD

**Issue by PuneetKohli** [realm/realm-cocoa#5040]
So, we've an iOS app that was using the Objective C version of Realm and we recently migrated our whole app to Swift, including Realm. We're now on RealmSwift 2.7.0

When the users freshly install the app, it works fine without any issues. When trying to upgrade from a previous version of the app, the app is stuck on launch screen and goes into a limbo until when the OS decides to shut it down. 

## Goals
Trying to get users to run our app and use Realm when upgrading from a previous version of the app

## Expected Results
App should run fine without any issues

## Actual Results
There is no real crash, the app is just stuck. We narowed down the problem to any calls of the following code :-

`let realm = try Realm()
`
It seems the app is unable to find Realm?

## Steps to Reproduce
 For reference, here are a few code samples called via our AppDelegate where we are using this (and all reproducing the crash)

_In our realm configuration code (We thought there may be a schema/data problem so we deleted all data from older versions):_

```
if oldSchemaVersion < 5 {
                let realm = try! Realm()
                try! realm.write {
                    realm.deleteAll()
                }
}
```

_This is a general use case where we fetch all active reminders on app launch:-_

```
do {
            let realm = try Realm()
            let reminders = realm.objects(DMReminder.self).filter("isActive==1")
            return reminders
        }
        catch let error as NSError{
            print(error)
            return nil
        }

```

## Version of Realm and Tooling

Xcode version: 8.3.2
iOS/OSX version: Tested on iOS 8,9, and 10.
Dependency manager + version: Cocoapods 1.2.1

**Comment by kishikawakatsumi** [comment]
@PuneetKohli You cannot open the Realm during migration. The Realm is already opened by migration. The Realm file holds the lock because the migration has started the write transaction. So if you try to open the Realm it will wait forever for the lock.

```
if oldSchemaVersion < 5 {
    let realm = try! Realm()
    try! realm.write {
        realm.deleteAll()
    }
}
```

^ Instead of that, you can use `migration.deleteData(forType:)` to delete a class. Also, you can use `create(_:value:)` to create new object.

**Comment by stel** [comment]
@PuneetKohli do you need any further help or can we close this issue?

**Comment by PuneetKohli** [comment]
This is good to close, thanks.

as a side-note: We ended up just using `.deleteRealmIfMigrationNeeded()` in our migration logic, as we figured it's better than deal with all the previous versions as we had a lot of schema changes.

**Comment by stel** [comment]
Awesome, thanks!
