### ISSUE TITLE
Carthage binary not available for 2.8.2

### ISSUE THREAD

**Issue by bsarrazin** [realm/realm-cocoa#5044]
## Goals
Use Carthage's download capability instead of building every dependency.

## Expected Results
Carthage should be downloading 2.8.2 from the GitHub release.

## Actual Results
Binary not available; forces us to build Realm by ourselves.

Realm framework version: 2.8.2
Xcode version: 8.3.3
iOS/OSX version: 10.12.5
Dependency manager + version: Carthage 0.23.0

**Comment by bdash** [comment]
The [v2.8.1](https://github.com/realm/realm-cocoa/releases/tag/v2.8.1) release page shows a Carthage framework download. Can you please share the output from `carthage` prior to it deciding to build Realm as that likely includes information about why it is choosing to do so.

**Comment by bsarrazin** [comment]
@bdash I totally made a typo!
I meant to say for 2.8.2, fixed in the title.

**Comment by tgoyne** [comment]
Carthage binaries for 2.8.2 are now up.
