### ISSUE TITLE
Print Representation of List shows wrong type

### ISSUE THREAD

**Issue by hishnash** [realm/realm-cocoa#5049]
## Goals
When printing a `List` of realm objects the nested lists should have the correct type.
## Expected Results
```swift
class HTTPFramePayload: Object, FramePayload {
    @objc dynamic var host: String? = nil
    @objc dynamic var schema: String? = nil
    @objc dynamic var path: String? = nil
    let port = RealmOptional<Int>()
    let headers = List<HTTPFramePayloadHeader>()
}
/// ....
print(frames)
```

```swift
Optional(List<Frame> (
	[0] Frame {
		created = 2017-06-20 08:48:10 +0000;
		isUpstream = 0;
		framePayloadWSData = (null);
		framePayloadWSString = (null);
		framePayloadWSConnected = (null);
		framePayloadWSDisconnected = (null);
		framePayloadHTTP = HTTPFramePayload {
			host = echo.websocket.org;
			schema = ws;
			path = ;
			headers = List<HTTPFramePayloadHeader> (
			
			);
			port = (null);
		};
		subFrames = List<Frame> (
		
		);
		associatedFrames = List<Frame> (
		
		);
	},
       // ...
))


```
## Actual Results
```swift
Optional(List<Frame> (
	[0] Frame {
		created = 2017-06-20 08:48:10 +0000;
		isUpstream = 0;
		framePayloadWSData = (null);
		framePayloadWSString = (null);
		framePayloadWSConnected = (null);
		framePayloadWSDisconnected = (null);
		framePayloadHTTP = HTTPFramePayload {
			host = echo.websocket.org;
			schema = ws;
			path = ;
			headers = List<Frame> (
			
			);
			port = (null);
		};
		subFrames = List<Frame> (
		
		);
		associatedFrames = List<Frame> (
		
		);
	},
	// ....
))

```
Notice the `headers` key prints as if it is a `List<Frame>` it should be a `List<HTTPFramePayloadHeader>`.

## Steps to Reproduce
Create a `Frame` object that has a `one-to-one` pointer to a `HTTPFramePayload` object that has a `one-to-many` relationship to a  `HTTPFramePayloadHeader`. 

then print a `List` of `frames`.

## Code Sample
https://gist.github.com/hishnash/f8822cb62a41b3ec7e16318fe9c4dff2

## Version of Realm and Tooling

Realm framework version: ? 2.8.2

Realm Object Server version: ? NA

Xcode version: ? Version 9.0 beta (9M136h)

**Comment by bdash** [comment]
Good catch. This is due to the [search / replace shenanigans that `List.description` makes use of](https://github.com/realm/realm-cocoa/blob/15afc8f3620f70ef8fd98f053490839777567555/RealmSwift/List.swift#L34-L37) in order to delegate to `-[RLMArray description]`.
