### ISSUE TITLE
Multiple Realm.Configuration doesn't migrate the database

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-cocoa#5057]
## Goals
Migrate the database using multiple configurations.

## Expected Results
Remove a not used property of a table.

## Actual Results
The database doesn't migrate.

## Steps to Reproduce
Just create your Realm.Configuration on the very first step of your application, generally on the method `func application(application, didFinishLaunchingWithOptions)`. Currently on my code, the migration is the very first action to run.

## Code Sample

Give a `Realm` object, the property `something: String` exists on the previous version (2) of the database, but It was removed of the model on the current version (3) and it will be removed of the database on the next migration:

```swift
class Foo: Object {
  
  dynamic var id: Int = 0
  dynamic var bar: String = ""

//Property to be removed.
//dynamic var something: String? = ""

  convenience init(id: Int) {
    self.init()
  }
  
  override static func primaryKey() -> String? {
    return "id"
  }
  
}
```

There is a generic method for migration, like this:

```swift

let migrationBlock: MigrationBlock = { migration, oldSchemaVersion in

  //Other migrations...

  if schema < 3 {

    migration.enumerateObjects(ofType: Foo.className()) { _, newObject in
      newObject!["bar"] = ""
    }

    schema += 1

  }

}
```

On `func application(application, didFinishLaunchingWithOptions)`:

```swift
let config = Realm.Configuration(
    schemaVersion: 3,
    migrationBlock: migrationBlock)

// Tell Realm to use this new configuration object for the default Realm
Realm.Configuration.defaultConfiguration = config

```

On another configuration:

```swift
do {

  let configuration = Realm.Configuration(
      schemaVersion: 3,
      migrationBlock: migrationBlock,
      objectTypes: [Foo.self])

  let realm: Realm = try Realm(configuration: configuration)
  //Does queries and other things.

} catch {
  print(error)
}
```

If you try to use it, simply using ` try Realm()`, the database will not migrated and returns error code 10:

![untitled](https://user-images.githubusercontent.com/5521682/27403768-8caac05a-56c3-11e7-82ae-2cb885b2a856.png)

The migration process is working, I have added a `print()` to check if the `Realm` migration is being invoked and it is.

## UPDATE:

After some research, I discovered that the application uses the method `applicationDidBecomeActive(_ application: UIApplication)` to load some information using Realm, like a counter badge for example. Even using this Realm with a configuration that provides the migration, this method creates a conflict between the method `didFinishLaunchingWithOptions`. So I am validating/adding delays on it.

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: None

Xcode version: 8.3.3

iOS/OSX version: All versions

Dependency manager + version: Cocoapods

Thank you.

**Comment by bdash** [comment]
I assembled the code snippets you provided into a test app and was *not* able to reproduce the problem when doing the following:
1. Uncomment the `something` property of `Foo`.
2. Set the schema version to 2.
3. Run the app.
4. Comment out the `something` property once more.
5. Bump the schema version to 3.
6. Re-run the app.

You can see the complete code I tested with at https://gist.github.com/bdash/235e8638f813bf4684dfa7a9878b26cc.

Can you please share more information about what steps are necessary to reproduce the problem? Sharing self-contained code that I can run to reproduce the problem would optimal.

Can you please also share the complete error message you're seeing? The error message you shared has portions obscured, which makes it challenging to see what is amiss.

**Comment by bdash** [comment]
Also, in the code you provided your two different configurations appear to point to the same file, and have the same schema version numbers. Is that really the case?

**Comment by ppamorim** [comment]
@bdash I will check if my code is using Realm before the migration, but I don't believe that's happening.
The error there is everything that the console prints. Just three lines. :( Would be cool to Realm shows here the problem happened.

No, the previous version (2) contains the property `something`, the current version (3) doesn't. This is changing otherwise the migration could never work.

**Comment by ppamorim** [comment]
Probably this is a conflict between the methods `didFinishLaunchingWithOptions` and `applicationDidBecomeActive`.

**Comment by ppamorim** [comment]
@bdash Can this issue be related with any problem on Realm?

**Comment by bdash** [comment]
It sounds like you've found the cause of your problem. Can you clarify what questions, if any, still remain to be addressed?

**Comment by ppamorim** [comment]
I would like to know if this issue can be related with the Realm's migration structure. 
It sounds like a clash of migrations running on the very first application process, interesting...

**Comment by bdash** [comment]
If you're opening the same Realm file from multiple places within your app you should be sure to do so using the same `Realm.Configuration` object. This will ensure that the appropriate migrations are performed, no matter which code path in your app happens to be hit first.

Beyond that, if you have any more questions please share code snippets that demonstrate what you're asking about.
