### ISSUE TITLE
Reconsider blocks in `NSError.userInfo`

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#5058]
Right now we have a design (used for client reset and other features) where we pass a block in an `NSError`'s `userInfo` dictionary and have the user invoke that block if they want to perform a certain action. This pattern is unusual and non-idiomatic, so we should use the opportunity of a breaking change to come up with something better.

c.f. https://github.com/realm/realm-cocoa/pull/5056

**Comment by austinzheng** [comment]
One idea is to have the `userInfo` pass back some sort of opaque token object, and have an API on `SyncUser`/`SyncSession`/whatever the relevant sync type is that takes the token object to perform the action. That way we avoid passing blocks, but we also avoid having an API that can be called at the "wrong" time by users.

**Comment by jpsim** [comment]
I like the token idea. The `userInfo` blocks _are_ a little gross. We could also expose methods that take in the `NSError` as a parameter. But I like the token approach more.

**Comment by austinzheng** [comment]
#5092 contains a possible implementation of the token idea. We don't have to go with it, of course, if we can come up with something better.

**Comment by austinzheng** [comment]
#5092 merged into `master-3.0`.
