### ISSUE TITLE
RLMSyncSession lasting forever for non Admin users

### ISSUE THREAD

**Issue by michael-mckenna** [realm/realm-cocoa#5061]
When I am trying to download for currently outstanding work for a global user realm (in testing I only had 10 objects in there), the completion handler is never called.

## Expected Results
If there was some sort of error in the download, I'd expect there to be an error reported explaining what was wrong instead of running forever. In my Admin account I set permissions for all users to have r/w access to the global user realm by doing:
`let permission = SyncPermissionValue(
                          realmPath: RealmURL.userObjects.absoluteString, userID: "*", accessLevel: .write) //                     may write
        SyncUser.current!.applyPermission(permission) { (error) in
            if let error = error {
                print(error)
            }`
so perhaps I'm doing something wrong with setting the permissions?

## Actual Results

The line `if progress.isTransferComplete` isn't even being hit. As mentioned earlier, the function just runs indefinitely. Even if there's only 10 objects in the database.

## Steps to Reproduce
1. Login as an Admin user and create a global Realm
2. Logout
3. Login a non admin user and start a download session inside the SyncUser.login completion

## Code Sample
https://gist.github.com/michael-mckenna/c164bfb3d316c9cc90ee7b792bce62ce

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: 1.7.6

Xcode version: 8.3.3

iOS/OSX version: 10.3.2

Dependency manager + version: Cocoapods 1.2.1

**Comment by austinzheng** [comment]
For the `realmPath` argument in your permissions code snippet, please don't pass the entire path (e.g "realm://example.org/my/globalRealm"), but only the path component ("/my/globalRealm").

**Comment by michael-mckenna** [comment]
That worked!! Whoop! Thanks. Can the docs be updated to be more explicit? For the realmPath, the docs state "The remote Realm path on which to apply the changes", when instead they should state the "...Realm path component..." or however you want the verbiage to be.
