### ISSUE TITLE
how can i Iterate over realm List 

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#5064]
I am getting a server response which i am converting into List<User> , it is basically array of users data.
Now I have another array of tuples which are having name and age, Now I need to filter the server response based on this array of tuples.

Can any body help me how can I iterate or use **filter** method on List so that I will get filtered List and finally I can save it in realm.

**Comment by bdash** [comment]
Hi @santhoshs5. Can you please share a code snippet that demonstrates what approach you’ve tried, and how the result you get differs from what you expect? Without that information the best I can do is to refer you to the `filter` method on Swift’s `Collection` protocol (which Realm’s collections conform to).

**Comment by stel** [comment]
@santhoshs5 do you still need help or can we close this issue?

**Comment by santhoshs5** [comment]
Its fixed.Thanks.
