### ISSUE TITLE
We get a probable for help. The crash report get information "Too many open files"

### ISSUE THREAD

**Issue by betterton** [realm/realm-cocoa#5071]
/var/mobile/Containers/Data/Application/E9EE7F3D-3BAA-42A7-A2AD-E9D4DC8A9D7F/Documents/ShopOrderTab.realm.management/log_b: Unable to open a realm at path '/var/mobile/Containers/Data/Application/E9EE7F3D-3BAA-42A7-A2AD-E9D4DC8A9D7F/Documents/ShopOrderTab.realm.management/log_b': open() failed: Too many open files.
(null)

Realm framework version: ?
1.1.0

Xcode version: ?
8.3.3

**Comment by stel** [comment]
Please check out https://github.com/realm/realm-cocoa/issues/4435 and provide some more info about your case in order to reproduce and investigate it, thanks!
