### ISSUE TITLE
Better way to define models?

### ISSUE THREAD

**Issue by komocode** [realm/realm-cocoa#5072]
## Goals
I would like a model generator. Right now it's a pain to write the models for Javascript, Android, and iOS and try to use the Sync feature on the mobile platform. Maybe somehow incorporate Google's Protocol Buffers into this mix? Basically I should be able to define my models in a language/platform agnostic way, click a button, and get the code for all three platforms.

## Expected Results
I would like Realm to spit out code that I can copy and paste into my model files for all languages.

**Comment by astigsen** [comment]
The Realm browser can generate models for all the platforms. Just open a Realm and select "Save Model Definitions" from the File menu.

**Comment by jpsim** [comment]
Closing as I believe the mac browser is a suitable current solution to this.
