### ISSUE TITLE
Use custom initializer on an Realm object inside a class with generic type

### ISSUE THREAD

**Issue by klemenzagar91** [realm/realm-cocoa#5073]
I have a class called `ObjectManager` which has generic type `O: Object, Persistable`. This way I can have one class that can operate with multiple different subclasses of realm `Object`. But the problem is in the last line  `cache = O(message: "hello world")` the error is:  **Incorrect argument label in call (have 'message:', expected 'value:')**

When typing it suggests me that I can use initializer of `Persistable` protocol, but complain during the compiling, that it expect an initializer from `Object` class. Is it possible to cast Persistable initializer?
```swift
protocol Persistable {
  init(message: String)
}

class CustomObject: Object, Persistable {
  dynamic var message: String = ""
  required convenience init(message: String) {
    self.init()
    self.message = message
  }
}

class ObjectManager<O>: NSObject where O: Object, O: Persistable {
  var cache: O?
  
  func didReceive(message: String) {
    cache = O(message: "hello world")
  }
}

```

**Comment by klemenzagar91** [comment]
One workaround I found is to replace init fit a function that I apply on the object right after initialization. 
Can somebody tell me I there is a better way?
```
protocol Persistable {
  func fillWith(message: String)
}

class CustomObject: Object, Persistable {
  dynamic var message: String = ""

  
  func fillWith(message: String) {
    self.message = message
  }
}

class ObjectManager<O>: NSObject where O: Object, O: Persistable {
  var cache: O?
  
  func didReceive(message: String) {
    let object = O()
    object.fillWith(message: message)
  }
}
```

**Comment by bdash** [comment]
@austinzheng provided an [answer on your StackOverflow question](https://stackoverflow.com/a/44791896/1991710).
