### ISSUE TITLE
Accessing my Realm from an iOS extension when using Realm Mobile Platform

### ISSUE THREAD

**Issue by gerbil802** [realm/realm-cocoa#5074]
## Goals

Access my Realm from an iOS extension, when using the Realm Mobile Platform

## Expected Results

According to Apple guidelines I should be able to access Realm via App Group.

## Actual Results

The local path is unavailable when using the Realm Mobile Platform.  
I'm submitted this question following this stackoverflow: https://stackoverflow.com/questions/44786619/accessing-realm-from-an-ios-extension-while-using-realm-mobile-platform
And was answered this is a feature request and to open a ticket here.

**Comment by stel** [comment]
Thanks for this issue, @gerbil802! This is something we're going to support in future updates.

**Comment by gerbil802** [comment]
What's the difference feature a Feature an an Enhancement? 😯

**Comment by stel** [comment]
I'd say Enhancement is always a small Feature 😆 We actually have a support for working with sync'd realms from different process internally but it's not exposed to the users and some design needs to be done for that.

**Comment by jpsim** [comment]
We're already tracking this as #4490, so I'm closing this ticket as a duplicate. Please subscribe to #4490 to be notified of any progress regarding this functionality.

**Comment by Mridul56** [comment]
any updates on this issue ?
