### ISSUE TITLE
SyncPermissionResults's method names aren't consistent with RealmCollection

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#5075]
## Goals

The query and sorting capability on `SyncPermissionResults` is exposed using the Objective-C API's naming conventions rather than those used in the Swift API.

## Expected Results
```swift
// Not available!
permissions.filter(predicate)
permissions.sorted(byKeyPath: keyPath, ascending: true)

// Instead:
permissions.objects(with: predicate)
permissions.sortedResults(using: keyPath, ascending: true)
```

**Comment by bdash** [comment]
[`addNotificationBlock` exists and is tested](https://github.com/realm/realm-cocoa/blob/819abe022f2af3339f8c83a54106b9554ed7ced9/Realm/ObjectServerTests/SwiftPermissionsAPITests.swift#L177-L184), from what I can see.

**Comment by bdash** [comment]
In the other cases, it looks like the methods exist but are exposed using names consistent with the Objective-C API rather than the Swift API (`objects(with:)` instead of `filter(_:)`, `sortedResults(using:ascending:)` instead of `sorted(byKeyPath:ascending:)`).

**Comment by bdash** [comment]
Note that the Swift API starts with `public typealias SyncPermissionResults = RLMSyncPermissionResults`, which exposes the Objective-C type to Swift under a different name. That means all API on `RLMSyncPermissionResults` is available from Swift (with the exception of symbols annotated with `NS_SWIFT_UNAVAILABLE`), even though they don't appear to have been exposed using the expected names.

**Comment by bigfish24** [comment]
Ah, ok I was misreading this then.

**Comment by bigfish24** [comment]
I will update the issue to reflect the naming changes needed.

**Comment by austinzheng** [comment]
I'm planning on refactoring `SyncPermissionResults` to be a subclass of `Results<SyncPermissionValue>`, so the issues you raised in this ticket should be resolved by that.

**Comment by austinzheng** [comment]
#5168 addresses this.
