### ISSUE TITLE
(RLM)SyncPermissionResults notification does not return collection change information

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#5076]
## Goals
The callback passed to `(RLM)SyncPermissionResults` does not support the full collection notification capabilities and instead just returns an `NSError`:
```objc
[permissions addNotificationBlock:^(NSError *error) {
    // Permissions Changed
}];
```
This block is defined as a [`RLMPermissionStatusBlock`](https://github.com/realm/realm-cocoa/blob/dd0f2a24d8eda2241b599036eb83aff00106569c/Realm/RLMSyncUser.h#L44).

## Expected Results
I expect that the block would return collection change information so that I would know the inserted, deleted, or modified permissions as such:
```objc
[permissions addNotificationBlock:^(RLMSyncPermissionResults *permissions, 
                                         RLMCollectionChange *changes, 
                                                     NSError *error) {
    // Inserted permissions indexes
    NSArray *insertedIndexes = changes.insertions;

    // Deleted permissions indexes
    NSArray *deletedIndexes = changes.deletions;

    // Modified permissions indexes
    NSArray *modifiedIndexes = changes.modifications;
}];
```

## Actual Results
Block returns a nullable `NSError`.

**Comment by austinzheng** [comment]
This should also include exposing the Swifty names for the APIs instead of the direct Obj-C translations, per https://github.com/realm/realm-cocoa/issues/5075#issuecomment-311513398.

**Comment by bdash** [comment]
Fixing the naming is what #5075 tracks. This is specifically about adding the collection change information to the callback.

**Comment by austinzheng** [comment]
#5168 addresses this.
