### ISSUE TITLE
How to close an realm object?

### ISSUE THREAD

**Issue by betterton** [realm/realm-cocoa#5082]
We got the error like 
/var/mobile/Containers/Data/Application/F7B60998-EA3A-4A0B-882B-2E1243AD57ED/Documents/ShopOrderTab.realm: Unable to open a realm at path '/var/mobile/Containers/Data/Application/F7B60998-EA3A-4A0B-882B-2E1243AD57ED/Documents/ShopOrderTab.realm': open() failed: Too many open files.
(null)

 and i found close realm object can resolve this problems. but i don't know how to close it. help

**Comment by stel** [comment]
Please check out https://github.com/realm/realm-cocoa/issues/4435 and provide some more info about your case in order to investigate it, thanks!
