### ISSUE TITLE
Operation "List1 + List2" modifies List1

### ISSUE THREAD

**Issue by wjling** [realm/realm-cocoa#5084]
## Goals

```
var list1 = List<SomeObject>()
var list2 = List<SomeObject>()
let newObject = SomeObject()
list2.append(newObject)
let list3 = list1 + list2
```

## Expected Results

```
list1: []
list2: [newObject]
```

## Actual Results

```
list1: [newObject]
list2: [newObject]
```
Elements in list2 have been added into list1

## Version of Realm and Tooling

Realm framework version: 2.7.0

Realm Object Server version: ?

Xcode version: 8.3.3 (8E3004b)

iOS/OSX version: iOS10

Dependency manager + version: ?

**Comment by tgoyne** [comment]
I'm not sure there's anything we can do about this. `+` fundamentally doesn't make any sense for `List` and can't work, but it's coming from `RangeReplaceableCollection` which we don't actually fully conform to.

**Comment by wjling** [comment]
Generally speaking,  list3 = list1 + list2 should not modify list1 and list2 and just copies list1's elements and list2's elements to list3. But now I find that list1 is modified. It is weird. I think it is a bug. According to your words, maybe it is not your bug

**Comment by stel** [comment]
I believe we should treat this as a bug. My only suggestion is to overload `+` and throw an assertion failure, that should cover most of the cases.

@wjling in your case I suggest to use `List.append(objectsIn:)` instead.

**Comment by wjling** [comment]
I have used `List.append(objectsIn:)` to add list1 and list2 into list3 to avoid the problem
