### ISSUE TITLE
RealmSwift RLMIterator iVar needs to be mutable in Xcode9beta 2 (Swift 3.2 mode)

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-cocoa#5094]
## Goals

Compile RealmSwift in Swift 3.2 mode for use with Xode9beta2/iOS11

## Expected Results

binding should compile cleanly in Swift 3.2 mode (not sure if this is a issue with our default build or if t'is a new issue with a language change in Swift 3.2 or with the LLVM shipped with the Xcode9 beta).

## Actual Results

RealmSwift compile fails; Xcode 9beta2 compiler asserts that an iVar needs to be mutable 

## Steps to Reproduce

Compile RealmSwift using Cocoapods with Xcode9 beta 2 

## Code Sample

The Xcode9 compiler (in swift 3.2 mode) asserts that  `generatorBase` must be  mutable:

```swift
/**
 An iterator for a `RealmCollection` instance.
 */
public final class RLMIterator<T: Object>: IteratorProtocol {
    private var i: UInt = 0
    private let generatorBase: NSFastEnumerationIterator

    init(collection: RLMCollection) {
        generatorBase = NSFastEnumerationIterator(collection)
    }

    /// Advance to the next element and return it, or `nil` if no next element exists.
    public func next() -> T? {
        let accessor = unsafeBitCast(generatorBase.next() as! Object?, to: Optional<T>.self)
        if let accessor = accessor {
            RLMInitializeSwiftAccessorGenerics(accessor)
        }
        return accessor
    }
}
```

## Version of Realm and Tooling
Realm framework version: ? RealmSwift 2.7.0 via Cocoapods
```
PODS:
  - Realm (2.7.0):
    - Realm/Headers (= 2.7.0)
  - Realm/Headers (2.7.0)
  - RealmSwift (2.7.0):
    - Realm (= 2.7.0)

```

Realm Object Server version: ? N/A

Xcode version: ? 9.2Beta2

iOS/OSX version: ? iOS 11.beta2

Dependency manager + version: ? Cocoapods 1.2.1

**Comment by tgoyne** [comment]
This was fixed in 2.8.1.
