### ISSUE TITLE
Support building with CocoaPods entirely from source, without sync

### ISSUE THREAD

**Issue by hovox** [realm/realm-cocoa#5095]
We are using only mobile db, is there a way to strip classes which are intended only for synchronization? For example we can create a pods subspec for mobile db, is it possible?

Thanks.

**Comment by jpsim** [comment]
I have a work-in-progress PR for this here: #4851

**Comment by hovox** [comment]
Cool, thank you, will wait for this pull request merge. I can help to complete this pull request  ASAP if you point me out what needs to be done.

**Comment by jsflax** [comment]
We are closing this as there are no intentions of decoupling sync from Realm.
