### ISSUE TITLE
Problem Revoking an Active User's Access to Object Server

### ISSUE THREAD

**Issue by ChrisChares** [realm/realm-cocoa#5097]
## Goals
Revoke a user's access to our Object Server.  For background we use Amazon Cognito as a custom auth provider and do the revocations through there.  

## Expected Results
After revoking a user's access, they should no longer be able to access the server.  Additionally there should be some kind of in app notification or property to observe allowing us to update the UI state accordingly. 

## Actual Results
Revoking a user's access eventually locks them out of the server, but there is no way to act on this in the app.  Logs show the server connection is eventually closed and retries fail to reopen it, but the `RLMSyncSession` `status` property continues to report `RLMSyncSessionStateActive`.  Also in our testing we occasionally observed the connection to fail ( app side changes not reflected in the object server browser and visa versa ) without even notifying the logs.

Logs:
```
2017-06-30 16:20:55.259451-0600 fieldFLOW[1763:649451] Sync: Connection[2]: Resolving 'realmobj-tst.cartasite.com:9443'
2017-06-30 16:20:55.265088-0600 fieldFLOW[1763:649451] Sync: Connection[2]: Connecting to endpoint '54.91.44.57:9443' (1/1)
2017-06-30 16:20:55.315921-0600 fieldFLOW[1763:649451] Sync: Connection[2]: Connected to endpoint '54.91.44.57:9443' (from '10.0.1.224:57119')
2017-06-30 16:20:55.582264-0600 fieldFLOW[1763:649451] Sync: Connection[2]: Session[1]: Sending: BIND(server_path='/fieldFlow', signed_user_token_size=621, need_file_ident_pair=0)
2017-06-30 16:20:55.583063-0600 fieldFLOW[1763:649451] Sync: Connection[2]: Session[1]: Sending: IDENT(server_file_ident=1, client_file_ident=678, client_file_ident_secret=4475077953977722014, scan_server_version=17599, scan_client_version=285, latest_server_version=17599, latest_server_session_ident=6750056724695107441)
2017-06-30 16:20:55.629110-0600 fieldFLOW[1763:649451] Sync: Connection[2]: Received: ERROR(error_code=202, message_size=20, try_again=0, session_ident=1)
2017-06-30 16:20:55.630080-0600 fieldFLOW[1763:649451] Sync: Connection[2]: Connection closed due to error reported by server: Access token expired (202)
```

## Steps to Reproduce

+ Reduce Realm refresh token expiration time something really short (e.g. 2 minutes)
+ Log a user in
+ Deactivate that user account in Cognito (our custom auth provider)
+ Wait until the logs show disconnection
+ Check the current `RLMSyncSession`'s `status` property

## Code Sample

Can't really show a code sample of the Cognito stuff, but here is the quick class we drew up to check the current status of the `RLMSyncSession`.  The `checkConnectivity()` function will always print `active`, even after the user has been disconnected.

```swift
class RealmConnectivity: NSObject {
    
    var timer: Timer? = nil
    
    @objc func start() {
        timer = Timer.scheduledTimer(timeInterval: 5, target: self, selector: #selector(RealmConnectivity.checkConnectivity), userInfo: nil, repeats: true)
    }
    
    func checkConnectivity() {
        guard let user = RLMSyncUser.__current() else { return }
        
        for session in user.allSessions() {
            switch session.state {
            case .active: print("active")
            case .inactive: print("inactive")
            case .invalid: print("invalid")
            }
        }
    }
}
```

## Version of Realm and Tooling

Realm framework version: 2.7.0

Realm Object Server version: 1.7.6 (dev) 1.8.1 (prod)

Xcode version: 8.3.3

iOS/OSX version: 10.3.2

Dependency manager + version: Cocoapods 1.2.1

Thank you for looking into this!

**Comment by bigfish24** [comment]
@ChrisChares how do you propagate the revocation from Cognito to Realm Object Server? Does this just happen when the app/user attempts to login forcing a check then or does ROS continually check?

**Comment by bigfish24** [comment]
Copying over the solution for this provided privately:
>Realm Object Server does not persist the AWS Cognito token when you send that from the client.
>
>The custom auth code in JS is only run when you call the [`authenticate()`](https://github.com/realm-demos/realm-loginkit/blob/master/RealmLoginKit%20Apple/RealmLoginKit/Models/AuthenticationProviders/AWSCognitoAuthenticationProvider.swift#L62) method and get `RLMSyncCredentials)` (i.e. the token from AWS) and then you call `SyncUser.login(credentials)`, thus the problem is that ROS actually does not know when your AWS token is revoked
>
>The `202` error is not related to that but is instead what we use to tell the client to refresh the access token ROS provides to the client, so it is unrelated to this and the behavior with the sync session is correct.
>
>So what I believe the issue is, is that ROS never knows when the AWS access token is expired because it doesn’t check on its own. The access token refreshing from ROS will continue unabated in the absence of being told to revoke.
>
>To fix this, I would recommend doing the following:
>
>1. Always calling [`authenticate()`](https://github.com/realm-demos/realm-loginkit/blob/master/RealmLoginKit%20Apple/RealmLoginKit/Models/AuthenticationProviders/AWSCognitoAuthenticationProvider.swift#L62) on ever app launch (such as in the background on subsequent launches when you have `SyncUser.current!`)
>
>2. If this returns an `Error` then simply call `logout()` which is then the signal ROS needs to inform it that access has been revoked
>
>Then pop back to the login screen
