### ISSUE TITLE
RealmSwift library getting too big!

### ISSUE THREAD

**Issue by lawgimenez** [realm/realm-cocoa#5103]
I just pushed to my repo here in Github with RealmSwift library and I am getting a LFS warning from Github.

Is there any way to trim down this library? 

I am currently using `pod 'RealmSwift', '2.8.3'`

![screen shot 2017-07-10 at 9 46 07 am](https://user-images.githubusercontent.com/7910468/27999947-d833cc5c-6554-11e7-8f67-1e9d8a88ee67.png)

**Comment by Raghvendra7** [comment]
Please add particular core library path into git ignore.

**Comment by jpsim** [comment]
Hopefully @Raghvendra7's suggestion works for you @lawgimenez!
