### ISSUE TITLE
Support Xcode 9 beta 3

### ISSUE THREAD

**Issue by ishabazz** [realm/realm-cocoa#5105]
A project with a RealmSwift 2.8.3 dependency won't compile in  Xcode 9 Beta 3

## Goals
Compile a project containing RealmSwift

## Expected Results
Succesful compilation

## Actual Results
Compilation fails

## Steps to Reproduce
 Create a new project.
Install Realm via CocoPods
Build
## Code Sample
No code needed. An empty project containing only  Realm and RealmSwift versions 2.8.3, won't compile because line 226 of RealmConfiguration.swift  returns an error "Generic Parameter 'U' could not be inferred"

## Version of Realm and Tooling

Realm framework version: ? 2.8.3

Realm Object Server version: ?

Xcode version: ? 9 beta 3

iOS/OSX version: ? iOS 11

Dependency manager + version: ? CocaPods 1.2.1

**Comment by luispadron** [comment]
Can confirm this is a problem when building with Swift 4 and Xcode 9 beta 3.

Using cocoapods for building.

**Comment by jpsim** [comment]
Thanks for your patience as we update Realm Objective-C and Realm Swift to support Xcode 9 beta 3, released this morning.

**Comment by ishabazz** [comment]
No worries. It’s a beta. Just wanted you to be aware.

**Comment by jpsim** [comment]
Addressed in #5107 and #5109.

**Comment by luispadron** [comment]
Well that error went away, however getting a few others ones now.

```swift
// LinkingObjects.swift:109:16: Use of unresolved identifier 'RLMDescriptionWithMaxDepth'
return RLMDescriptionWithMaxDepth("LinkingObjects<\(rlmResults.objectClassName)>", rlmResults, RLMDescriptionMaxDepth)

// RealmSwift/List.swift:35:16: Use of unresolved identifier 'RLMDescriptionWithMaxDepth'
return RLMDescriptionWithMaxDepth("List<\(_rlmArray.objectClassName)>", _rlmArray, depth)

// RealmSwift/Object.swift:101:43: Type 'RLMSchema' has no member 'partialPrivateShared'
super.init(value: value, schema: .partialPrivateShared())

// RealmSwift/Results.swift:84:16: Use of unresolved identifier 'RLMDescriptionWithMaxDepth'
return RLMDescriptionWithMaxDepth("Results<\(rlmResults.objectClassName)>", rlmResults, RLMDescriptionMaxDepth)

// RealmSwift/Sync.swift:128:16: Value of type 'NSError' has no member '__rlmSync_deleteRealmBlock'
return _nsError.__rlmSync_deleteRealmBlock()
```
Wasn't sure if I should open a new issue or just update this one, just wanted you guys to be aware of this.

**Comment by jpsim** [comment]
Are you using CocoaPods, and are you pointing both the `Realm` and `RealmSwift` pods to `master`? Looks like your `Realm` pod is out of date but you're using the latest `RealmSwift` pod...

**Comment by luispadron** [comment]
You were correct, my mistake!

I hadn't added the `Realm` pod to my podfile after pointing `RealmSwift` to master

Adding `Realm` as a pod fixed it

```ruby
  pod 'Realm',      :git => "https://github.com/realm/realm-cocoa.git", 
                    :branch => "master", 
                    :submodules => true
```
