### ISSUE TITLE
does not comiple Xcode 9 beta 3 

### ISSUE THREAD

**Issue by hishnash** [realm/realm-cocoa#5113]
## Goals
Compile Realm

## Expected Results
It compiles
## Actual Results
Get this error:
Swift Compiler Error Group
/Users/xxxxx/learning/Sockets/Pods/RealmSwift/RealmSwift/RealmConfiguration.swift:226:78: Generic parameter 'U' could not be inferred

## Steps to Reproduce
Try to compile

## Code Sample
NA

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: NA

Xcode version: Version 9.0 beta 3 (9M174d)

iOS/OSX version: iOS11 (beta3)

Dependency manager + version: 1.3.0.beta.1

**Comment by qubblr** [comment]
Hi @hishnash. I'm experiencing exactly the same problem. Did you manage to solve it?
