### ISSUE TITLE
Cocoapod Xcode 9b3

### ISSUE THREAD

**Issue by ronaldmannak** [realm/realm-cocoa#5116]
## Goals
I've used RealmSwift in Xcode 9b2 without a problem, but 9b3 seems to break a few things, even after yesterday's jp-xcode9b3 commit.

## Expected Results
RealmSwift working with 9b3

## Actual Results

Using the remote master branch will result in a **[!] Failed to download 'RealmSwift'**. cocoa pods error.

    pod 'Realm', git: 'git@github.com:realm/realm-cocoa.git', branch: 'master'
    pod 'RealmSwift', git: 'git@github.com:realm/realm-cocoa.git', branch: 'master'

Using local pods, will result in a **RLMSyncUtil.h:19:9: 'Realm/RLMConstants.h' file not found** compile error.

    pod 'Realm', :path => "~/Development/Tools/realm-cocoa"
    pod 'RealmSwift', :path => "~/Development/Tools/realm-cocoa"

## Version of Realm and Tooling

Realm framework version: master branch

Xcode version: 9b3

**Comment by jpsim** [comment]
You can pull in a custom Realm source via CocoaPods by specifying the following in your Podfile:

```ruby
pod 'Realm', git: 'git@github.com:realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'git@github.com:realm/realm-cocoa.git', branch: 'master', submodules: true
```

So you're just missing the `submodules: true` bit.

**Comment by ronaldmannak** [comment]
yep, that was it. Thanks JP!
