### ISSUE TITLE
RLMPrecondition(bool, NSString*, NSString*, ...)

### ISSUE THREAD

**Issue by marinofaggiana** [realm/realm-cocoa#5117]
In Backtrace I have found this exception : 

```
RLMPrecondition(bool, NSString*, NSString*, ...) 
```

ref. this query : 

```swift
results = realm.objects(tableMetadata.self).filter(predicate).sorted(byKeyPath: sorted, ascending: ascending)
```

Where is the issue ? from predicate, sorted or ascending ?

Thanks for Help me.

![schermata 2017-07-12 alle 11 22 47](https://user-images.githubusercontent.com/8616947/28111051-7be585f2-66f4-11e7-8549-d836c4c34fac.png)

**Comment by kishikawakatsumi** [comment]
@marinofaggiana It indicates that the property represented by the key path is not defined in the object. Probably the property to be sorted is incorrect.

**Comment by marinofaggiana** [comment]
strange ... how I can know if the property (dynamic var) passed on byKeyPath exists on object  ?

thanks

**Comment by jpsim** [comment]
Presumably you're in control of your Realm models, so you would know from your source code if you're attempting to access a keypath that isn't defined on your object.

**Comment by marinofaggiana** [comment]
Yes ... but this property is passed via code ... so I should check if this property exists on Object ..  some advice ?

**Comment by jpsim** [comment]
If you can't refactor the code to avoid accessing an invalid keypath on a Realm object, you could check its [`RLMObjectSchema`](https://realm.io/docs/swift/latest/api/Classes/ObjectSchema.html) to see if it contains the property you expect it to.

**Comment by marinofaggiana** [comment]
oh ! yes this is perfect.

thanks

**Comment by jpsim** [comment]
Glad we could work this out.
