### ISSUE TITLE
Is the entry correct in filter?

### ISSUE THREAD

**Issue by alexsanderkhitev** [realm/realm-cocoa#5119]
Hi! Please tell me if I wrote the condition correctly. I need to get a user from Realm by id, but there must also be one of two conditions, either it must be a friend or it must be just an interlocotor (I called this property isNonFriendInterlocutor).

At me this all works, but I simply wished to learn correctly whether the given condition is written down and whether it is possible to improve it. Thank you.

```
   func getInterlocutor(_ id: String) -> RealmUser? {
        do {
            let realm = try Realm()
            let interlocutor = realm.objects(RealmUser.self).filter("id == %@ && isFriend == %@ || isNonFriendInterlocutor == %@", id, true, true).first
            return interlocutor
        } catch {
            debugPrint(error.localizedDescription)
            return nil
        }
    }
```

**Comment by jpsim** [comment]
Seems reasonable to me. There are a few things you could do to potentially improve this slightly, such as group the comparisons to reflect how they work together, and avoid interpolation of constant value checks, but those are all purely stylistic:

```swift
func getInterlocutor(_ id: String) -> RealmUser? {
    do {
        let realm = try Realm()
        let interlocutor = realm.objects(RealmUser.self).filter("id == %@ && (isFriend == true || isNonFriendInterlocutor == true)", id).first
        return interlocutor
    } catch {
        debugPrint(error.localizedDescription)
        return nil
    }
}
```

I'd also recommend considering if you can decouple this method from the default Realm (aka dependency injection), which would make maintaining this code easier, for example as you add more Realms to your app:

```swift
extension Realm {
  func getInterlocutor(id: String) -> RealmUser? {
      let predicate = "id == %@ && (isFriend == true || isNonFriendInterlocutor == true)"
      return objects(RealmUser.self).filter(predicate, id).first
  }
}
```

I also made `id` an explicitly labeled function argument to conform to Swift's API Design Guidelines. See the segment on [**Compensate for weak type information** to clarify a parameter’s role](https://swift.org/documentation/api-design-guidelines/#weak-type-information).

**Comment by alexsanderkhitev** [comment]
@jpsim thank you so much!
