### ISSUE TITLE
Downloading sync failed - SSL problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by abdulla-allaith-7** [realm/realm-cocoa#5120]
## Goals

Installing Realm through Cocoapods using `pod 'RealmSwift'`.

## Expected Results

Realm installs successfully.

## Actual Results

Cocoapods `pod install --verbose` output:        
```
Downloading dependencies

-> Installing Realm (2.8.3)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/q7/l_1t3jx11nqcxq19jsg14sj00000gn/T/d20170712-13217-1o6ihno
     --template= --single-branch --depth 1 --branch v2.8.3
     Cloning into '/var/folders/q7/l_1t3jx11nqcxq19jsg14sj00000gn/T/d20170712-13217-1o6ihno'...
     Note: checking out '15afc8f3620f70ef8fd98f053490839777567555'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
     $ /usr/local/bin/git -C
     /var/folders/q7/l_1t3jx11nqcxq19jsg14sj00000gn/T/d20170712-13217-1o6ihno
     submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into 'Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out '39d33531363d8ac9faf0333c9abd9b7c86588d13'
     Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'external/catch'
     Submodule 'external/pegtl' (https://github.com/ColinH/PEGTL) registered for path 'external/pegtl'
     Cloning into 'external/catch'...
     Submodule path 'Realm/ObjectStore/external/catch': checked out 'ce37f48ffad2401e6c23a54cae3f015c01fdc200'
     Cloning into 'external/pegtl'...
     Submodule path 'Realm/ObjectStore/external/pegtl': checked out '3c4128a7e7e1288eb746418ea60c41477358f26a'
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: sync 1.10.0
   Downloading sync failed:
   	https://static.realm.io/downloads/sync/realm-sync-cocoa-1.10.0.tar.xz
   	curl: (60) SSL certificate problem: unable to get local issuer certificate
   More details here: http://curl.haxx.se/docs/sslcerts.html
   
   curl performs SSL certificate verification by default, using a "bundle"
    of Certificate Authority (CA) public keys (CA certs). If the default
    bundle file isn't adequate, you can specify an alternate file
    using the --cacert option.
   If this HTTPS server uses a certificate signed by a CA represented in
    the bundle, the certificate verification probably failed due to a
    problem with the certificate (it might be expired, or the name might
    not match the domain name in the URL).
   If you'd like to turn off curl's verification of the certificate, use
    the -k (or --insecure) option.
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 1.10.0
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-1.10.0.tar.xz
	curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

The main issue is with `curl` trying to download
`Downloading sync failed:
   	https://static.realm.io/downloads/sync/realm-sync-cocoa-1.10.0.tar.xz`
which shows the error:
`curl: (60) SSL certificate problem: unable to get local issuer certificate`
I have tried `curl` alone with the sync file and got the same issue.      
However, when trying the `curl` command with `http` instead of `https`, it works fine!!          
        
I also tried a method found in other issues in the Realm repo, which consisted of downloading the file and moving it using the following commands:
```
curl http://static.realm.io/downloads/sync/realm-sync-cocoa-1.10.0.tar.xz -O
mkdir $TMPDIR/sync_bin
mv realm-sync-cocoa-1.10.0.tar.xz $TMPDIR/sync_bin/realm-sync-cocoa-1.10.0.tar.xz
```
The first command downloaded the file (successful because I used `http`).        
The second command created the `sync_bin` directory successfully.
The third command moved the file to the directory.
I tried the same steps with the `core_bin` folder as well.
**None of the above worked.**

## Steps to Reproduce

Running the `pod install` command for a pod file with `pod 'RealmSwift'`.

## Code Sample

No code samples, this issue happens with the installation of realm.

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: ?

Xcode version: 8.3.3

iOS/OSX version: 10

Dependency manager + version: Cocoapods 1.2.1

**Comment by jpsim** [comment]
Interesting. I'm sorry you're experiencing some difficulty downloading Realm.

I couldn't reproduce this myself just now:

```
$ curl -O https://static.realm.io/downloads/sync/realm-sync-cocoa-1.10.0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42.5M  100 42.5M    0     0  6459k      0  0:00:06  0:00:06 --:--:-- 6795k
$ echo $?
0
```

**Comment by abdulla-allaith-7** [comment]
@jpsim I am getting the issue when running the same command you ran.
<br>
<img width="900" alt="screen shot 2017-07-12 at 9 56 05 pm" src="https://user-images.githubusercontent.com/29616360/28134924-3bf0a022-674d-11e7-9e74-63f8dd388f4b.png">

**Comment by abdulla-allaith-7** [comment]
I tried the suggested commands, the first one resulted in the same issue:
`curl: (60) SSL certificate problem: unable to get local issuer certificate`
However, I manually downloaded the file and moved it to the working directory in terminal, then ran the second command and it worked (started downloading).

On a related, possible needed, note:
I tried the command `curl --cacert nonExistingFile.pem https://www.google.com` so I can check my CApath, but the result was `CApath: none`.

As for the version:
```
curl 7.30.0 (x86_64-apple-darwin10.0.0) libcurl/7.30.0 OpenSSL/1.0.1m zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
```

**Comment by abdulla-allaith-7** [comment]
After more research, I did not find a one-post solution, but the fragments here and there helped me, so I'm putting the simple fix for future reference:

1- Download the `.pem` file from: https://curl.haxx.se/ca/cacert.pem
2- Move/copy it to the following directory: `/etc/ssl/certs`
3- Run the following command: `echo 'cacert=/etc/ssl/certs/cacert.pem' > ~/.curlrc`

That's it. `curl` was not set to use the `.pem` file by default, and these steps makes sure it does. Subsequently, this makes the `pod install` command work and not fail anymore.

Thanks @jpsim for the help, the commands you posted made me realize my `curl` was not downloading from any `https` links at all!

**Comment by jpsim** [comment]
🎉

**Comment by bdash** [comment]
This suggests that we may want to hard-code `/usr/bin/curl` in build.sh so we always get the system version rather than a user-installed version. The system version of curl on recent versions of macOS uses SecureTransport rather than OpenSSL for SSL, which means it relies on the system keychain for verifying the certificate chain.

**Comment by jpsim** [comment]
That does sound nice. PR incoming.

**Comment by zykis** [comment]
```
Downloading dependency: 11.14.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.14.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.14.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
```

Could you please update static.realm.io certificate, so tuist/carthage would be able to build my project?
