### ISSUE TITLE
Realm 2.8.3 Reports itself as Out of Date in Xcode Log

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-cocoa#5123]
This is a small issue, but I thought I'd report it.

I recently updated to version `2.8.3` of Realm with Carthage. The Carthage log confirms the version in its installation log:

![image](https://user-images.githubusercontent.com/2513753/28151299-9f8bc066-674e-11e7-92bd-668796b02d31.png)

But with each subsequent build of my app in Xcode, it still logs that I'm out of date:
```
Version 2.8.3 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v2.8.3/CHANGELOG.md
```
Thanks! 🙂

**Comment by jpsim** [comment]
Hmm, is it possible that despite Carthage pulling in the 2.8.3 versions of the Realm frameworks, that your Xcode project is actually referencing a different Realm framework?

I just created a sample iOS app with Carthage using prebuilt binaries, Xcode 8.3.3 and Realm 2.8.3 and didn't get the outdated version log message...

What's the result of this command?

```
$ plutil -p Carthage/Build/iOS/Realm.framework/Info.plist
```

**Comment by cliftonlabrum** [comment]
Here's the output:
```
{
  "DTXcode" => "0833"
  "DTSDKName" => "iphoneos10.3"
  "NSHumanReadableCopyright" => "Copyright © 2014 Realm. All rights reserved."
  "CFBundleName" => "Realm"
  "DTSDKBuild" => "14E8301"
  "CFBundleDevelopmentRegion" => "English"
  "CFBundleVersion" => "2.5.1"
  "BuildMachineOSBuild" => "16F73"
  "DTPlatformName" => "iphoneos"
  "CFBundleShortVersionString" => "2.5.1"
  "CFBundlePackageType" => "FMWK"
  "CFBundleSupportedPlatforms" => [
    0 => "iPhoneOS"
  ]
  "CFBundleInfoDictionaryVersion" => "6.0"
  "CFBundleExecutable" => "Realm"
  "DTCompiler" => "com.apple.compilers.llvm.clang.1_0"
  "MinimumOSVersion" => "8.0"
  "CFBundleIdentifier" => "io.Realm.Realm"
  "UIDeviceFamily" => [
    0 => 3
    1 => 2
    2 => 1
    3 => 4
  ]
  "DTPlatformVersion" => "10.3"
  "DTXcodeBuild" => "8E3004b"
  "CFBundleSignature" => "????"
  "DTPlatformBuild" => "14E8301"
}
```
Does that mean I'm on **2.5.1**!? That's crazy. I have `github "realm/realm-cocoa"` in my Cartfile. 🤔

**Comment by jpsim** [comment]
Yes, that means you have Realm 2.5.1 in your `Carthage/Build` directory.

Maybe run `rm -rf Carthage && carthage update` to clear out whatever internal state it has?

**Comment by cliftonlabrum** [comment]
That fixed it. Thank you very much, @jpsim! I'm lucky I didn't run into a dozen other issues being on a much older version of Realm than I thought I was. 🙂
