### ISSUE TITLE
Carthage will not checkout Realm 2.8.x

### ISSUE THREAD

**Issue by greimers** [realm/realm-cocoa#5131]
## Goals
I use Carthage for packet management and wanted to upgrade from Realm 2.7.0 to 2.8.3. So I changed the version in cart file.

## Expected Results
When I do `carthage update --platform iOS` it should download Realm 2.8.3

## Actual Results
When I set the cart file to use `github "realm/realm-cocoa" == 2.8.3`, carthage will log `*** Checking out realm-cocoa at "v1.1.0-3"`. Also the update will never complete.

When I  change that to `github "realm/realm-cocoa"`, carthage will download Realm 2.7.0

I looks like the 2.8.x versions are not correctly linked to be pulled by carthage.

I did of course try to clean the Carthage output folder. But it did not have any effect.

## Steps to Reproduce
Load Realm 2.8.x using Carthage.

## Version of Realm and Tooling

Realm framework version: 2.8.3

Xcode version: 8.3.3

iOS/OSX version: 10.12.5

Dependency manager + version: Carthage 0.24.0

**Comment by jpsim** [comment]
I can't reproduce this:

```bash
$ carthage version
0.24.0
$ echo "github \"realm/realm-cocoa\"" > Cartfile
$ carthage update --platform iOS
*** Fetching realm-cocoa
*** Downloading realm-cocoa.framework binary at "v2.8.3"
*** xcodebuild output can be found in /var/folders/tv/cc131sv94cv_xk5bzg81559r0000gn/T/carthage-xcodebuild.nQZ701.log
```

**Comment by greimers** [comment]
Thanks for checking @jpsim. You are right. This is not a general problem but actually specific to my setup. I did a lot of testing and finally found out the this issue appears because I have another dependency in Carthage that depends on Realm 2.7.0. Obviously Carthage will not pull newer versions than the lowest version of any dependency.

Anyway, this is not a Realm issue but a Carthage issue.
