### ISSUE TITLE
Issue : partial apply

### ISSUE THREAD

**Issue by marinofaggiana** [realm/realm-cocoa#5134]
Hi have this strage issue on bugreport : 

> partial apply for NCManageDatabase.(addMetadata(tableMetadata, activeUrl : String, serverUrl : String) -> tableMetadata?).(closure #1)

the addMetadata function is very simple :  

```
func addMetadata(_ metadata: tableMetadata) -> tableMetadata? {
        
        guard self.getAccountActive() != nil else {
            return nil
        }
        
        let realm = try! Realm()
        
        do {
            try realm.write {
                realm.add(metadata, update: true)
            }
        } catch let error {
            print("Could not write to database: ", error)
        }
           
        return tableMetadata.init(value: metadata)
    }

```

Where is the problem ?

**Comment by austinzheng** [comment]
Hi Marino,

"partial apply" isn't an error, it's an implementation detail as to how Swift calls certain types of blocks. Can you provide the actual error that is being thrown or fired?

**Comment by kishikawakatsumi** [comment]
Closing due to no response. Feel free to reopen if you have further questions.

**Comment by marinofaggiana** [comment]
Sorry, I'm here : 

<img width="933" alt="schermata 2017-07-27 alle 10 58 28" src="https://user-images.githubusercontent.com/8616947/28662487-a53ed206-72ba-11e7-8760-a2e65c5b1919.png">

**Comment by austinzheng** [comment]
Unfortunately, that stack trace is incomplete and `EXC_BREAKPOINT` is a non-indicative error. Unless you are able to provide a full stack trace or a project that reproduces the crash, we regrettably cannot continue investigating.
