### ISSUE TITLE
RealmSwift List Issue 

### ISSUE THREAD

**Issue by gal-orlanczyk** [realm/realm-cocoa#5135]
Hi,

I first want to mention the your product is awesome but documentation is very basic for some cases like inverse relationships and one-many.

I have created an object with List type like this for example:
```swift
class MyClass: Object {
    var number: Int = 0
    let list = List<Item>()
}
```

number is primary key and I am creating the object without the list at the start.
```swift
var myClass = MyClass()
myClass.number = 0
let realm = try! Realm()
try! realm.write {
    realm.add(myClass, update: true)
}
```

now when I want to append to the list later on (inside a realm.write of course) the objects are added to realm but not as linked objects under list which makes them unusable to me because I need them to be connected to an object. now I know I can create an extra foreign key like regular database but from what I understood it is not needed for the same Realm file.

Any help solving this would be appreciated because I haven't found how to solve this.

Thanks,
Gal

**Comment by austinzheng** [comment]
Sorry, it's not clear what you're asking. Please provide code listings for everything you're doing, including "append[ing] to the list later on". Are you calling `list.append(_:)` and passing in the object you're adding to the list inside the write transaction, or just adding the `Item` in question directly to the Realm?

**Comment by gal-orlanczyk** [comment]
@austinzheng hi, what I am doing later is exactly as I said I'm appending items to an object that is already added to db :
```swift
let item = realm.object(Item.self, forPrimaryKey: "key") 
try! realm.write {
    item.list.append(itemsToAppend)
}
```
when doing it this way the items are added to the realm but no link is created, I see that using the realm browser. for example if I added 10 items to the list the items are added to realm but when I am looking at the parent object containing the list there was no link made between it and the other items meaning my one to many relation doesn't work and I can make queries this way.

let me know if something else is still unclear.

**Comment by austinzheng** [comment]
Please provide a complete code listing or sample project. Your code is invalid (`itemsToAppend` isn't defined), and unless you provide a listing it's almost impossible to figure out what might the issue be. Thanks.

**Comment by gal-orlanczyk** [comment]
```swift

class SubItem: Object {
    dynamic var id: String = ""
}

class Item: Object {
    dynamic var id: String = ""
    let list = List<SubItem>()
}

// now in some class at the start I do the following:
var item = Item()
item.id = "1"
let realm = try! Realm()
try! realm.write {
    realm.add(item)
}

// at some later point I am doing the following:
var item = realm.object(Item.self, forPrimaryKey: "1") 
var subitem = SubItem()
subitem.id = "2"
try! realm.write {
    item.list.append(subitem)
}
```

this code appends the subitems to realm but doesn't create the connection between Item and subitem list and I can't query items because if it.

**Comment by austinzheng** [comment]
Your code is working fine for me:

```swift
 // now in some class at the start I do the following:
var item = Item()
item.id = "1"
let realm = try! Realm()
try! realm.write {
    realm.add(item)
}

// at some later point I am doing the following:
var item2 = realm.object(ofType: Item.self, forPrimaryKey: "1")!
var subitem = SubItem()
subitem.id = "2"
try! realm.write {
    item2.list.append(subitem)
}

print("item2's list has \(item2.list.count) objects")
print("they are: \(item2.list)")
let firstSubitem = item2.list.first!
print("the first subitem is: \(firstSubitem)")
```
produces the console output

```
item2's list has 1 objects
they are: List<SubItem> (
	[0] SubItem {
		id = 2;
	}
)
the first subitem is: SubItem {
	id = 2;
}
```

Are you trying to extract items from the list in a different way? Can you explain exactly what you are doing, what the expected output is, and what the actual output is?

**Comment by kishikawakatsumi** [comment]
I'm going to close this issue due to lack of information. Please feel absolutely free to reopen if you have more questions.
