### ISSUE TITLE
XCode 9 beta 3 

### ISSUE THREAD

**Issue by mobilinked** [realm/realm-cocoa#5139]
## Goals
Clone the project to compile using XCode 9 Beta 3 

## Expected Results
Pass compiling

## Actual Results
Failed at 
`class CocoaSyncUserContext : public CocoaSyncUserContext {`
with error message: "Base class has incomplete type" 

## Steps to Reproduce
1. Download "Master" branch as zip file, and unzip on Mac device 
2. Open realm project and compile 

## More...
1. Download framework from realm.io website and using the framework files directly in a project, failed compiling with error related to realm.framework

**Comment by jpsim** [comment]
Zip archives from GitHub don't include git submodules, which is the reason this is failing for you.

> Download framework from realm.io website and using the framework files directly in a project, failed compiling with error related to realm.framework

This is a bit less clear what might be going wrong. What version of Realm? Just Realm Objective-C or Realm Swift too? What's the error you're seeing?

**Comment by mobilinked** [comment]
Thanks @jpsim, would you please help to check following my comments? 

I did not use CocoaPod to add RealmSwift to my project, so I directly copy the Realm and RealmSwift frameworks to my project. It works well before using XCode 9 Beta 3. Now I have problem to use the frameworks directly using XCode 9 Bete 3, following the steps to reproduce the problem: 

1. Download the latest package from https://static.realm.io/downloads/swift/realm-swift-2.8.3.zip
2. Create a new Mac application project using XCode 9 Bete 3, config Swift Language version to 4.0. No problem to compile
3. Drag Realm.framework and RealmSwift.framework from the downloaded package (/osx/swift3.1)
4. Compiling failed with error: 
```
ld: framework not found RealmSwift
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
5. Change project Swift Language Version to 3.2, compiling still failed with same error. 

----------------------- 
So I tried to download the source code and to compile the source code directly. 2 days ago I tried to download the source code as zip file and manually download ObjectStore for the project.

Today I tried using "GitHub Desktop" app to clone the project, and compile using XCode 9 Beta 3, it works.  

----------------------

Thanks much for your help.
