### ISSUE TITLE
RealmSwift target does not build TestHost automatically

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#5145]
QOL fix: if possible, make it so TestHost or Realm don't have to be built manually before building RealmSwift for testing.

**Comment by tgoyne** [comment]
Xcode 9's new build system reports that there's a dependency cycle that I suspect the old build system is resolving by just not building TestHost.app. Unfortunately it doesn't really give any actionable information for how to go about fixing the problem or where the cycle is coming from.

**Comment by austinzheng** [comment]
This is good to know. I will get acquainted with the new build system and take a look at some point later this month.

**Comment by jsflax** [comment]
TestHost is now built automatically.
