### ISSUE TITLE
Realm is not updated automatically on the main thread

### ISSUE THREAD

**Issue by Heckscheibe** [realm/realm-cocoa#5146]
## Goals

Updated Realm and Realm objects automatically on the main thread when writes (changes) are done on a background thread.

## Expected Results

As stated [here in the docs](https://realm.io/docs/swift/latest/#seeing-changes-from-other-threads), the Realm and its objects should be updated automatically.

## Actual Results

I have to call `Realm.refresh()` to get the updated objects.

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: ?

Xcode version: 8.3.3

iOS/OSX version: iOS 10.3.2

Dependency manager + version: CocoaPods

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. Auto-refreshing Realm objects within a thread with an active runloop don't get refreshed until the next iteration of the runloop, hence the need to call `refresh()` in your case to immediately get the most up-to-date data. You can register a notification on a query concerning the involved objects if you don't want to use `refresh()`.

**Comment by Heckscheibe** [comment]
Ok, thanks for the clarification and the feedback.
