### ISSUE TITLE
Build error in Xcode 9 beta 3

### ISSUE THREAD

**Issue by hovox** [realm/realm-cocoa#5147]
## Goals
Fix compile error issue
## Expected Results
Compile without errors

## Actual Results
![untitled](https://user-images.githubusercontent.com/1732834/28408645-3564f2b0-6d49-11e7-91d7-75bde54726a4.jpeg)

## Steps to Reproduce
Checkout to realm's 1.1.0 version with Cocoapods
Use Xcode 9 beta 3

## Version of Realm and Tooling

Realm framework version: 1.1.0

Xcode version: 9 beta 3

iOS/OSX version: macos 10.12.6

Dependency manager + version: Cocoapods version 1.2.1

**Comment by austinzheng** [comment]
We don't support 1.* versions of Realm anymore. Sorry.

**Comment by hovox** [comment]
I have solved it by downloading static library for that version. I will be glad to update, but the thing is we would like to have a version without sync classes, because we do not using sync feature. Thanks

**Comment by PreetidhankarIOS** [comment]
realm file not found.


Realm framework version: 1.1.0
Xcode version: 9 beta 3
iOS/OSX version: macos 10.12.6
Dependency manager + version: Cocoapods version 1.2.1

**Comment by bdash** [comment]
@PreetidhankarIOS, if you're having a problem, please file a new issue and fill out the new issue template. Leaving a comment without meaningful details on an issue that's been closed for 2.5 months isn't helpful.
