### ISSUE TITLE
Would computed properties substitute unsupported types?

### ISSUE THREAD

**Issue by megas781** [realm/realm-cocoa#5157]
## Goals

Good day, Realm team! I understand that Realm Object class supports only few primitive types.
I needed to store UIImage as Data class. So I decided to directly 'store' its png representation as Data, but when I work with an object, I want to use computed property of UIImage  type, because it would be intuitively more convenient.

## Expected Results

I want to have an `image` property, that converts `imageData` property to `UIimage` in getter and converts given `UIImage` instance to `Data` in setter.

## Actual Results

If the computed property has only `getter`, all work well. But as I add a `setter`, `Realm` suddenly starts to complain, that `RLMObject` class doesn't support `UIImage` type, in spite of that this is not a stored property; it is just a convenient way to work with `imageData`

## Steps to Reproduce

Just create any computed property of type, which is not supported by RLMObject.
## Code Sample

```swift
//swift 3.1

  class Human: Object {
   
   //Actually stored property
   dynamic var imageData : Data? = nil
   
   //A property to simply get and set imageData
   dynamic var image : UIImage? {
      get {
         if let data = self.imageData {
            return UIImage(data: data)
         } else {
            return nil
         }
      }
      set {
         if let image = newValue {
            self.imageData = UIImagePNGRepresentation(image)
         } else {
            self.imageData = nil
         }
      }
   }
   
}
```
## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: ?

Xcode version: 8.3.3

iOS/OSX version: iOS 10.3

Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@megas781 Read-only properties are automatically ignored. But read-write properties aren't. You need to override `ignoredProperties()` explicitly.


```
override class func ignoredProperties() -> [String] {
   return ["image"]
}
```

**Comment by kishikawakatsumi** [comment]
It seems to resolve
