### ISSUE TITLE
Unsigned integers not supported

### ISSUE THREAD

**Issue by JimDuskes** [realm/realm-cocoa#5158]
## Goals

Use unsigned integers in databases.

## Expected Results

Use unsigned integers in databases.

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by austinzheng** [comment]
We are aware that this is a feature our users want to see, and have a ticket to track it (#651).
