### ISSUE TITLE
Change Realm.Configuration Argument Order

### ISSUE THREAD

**Issue by kbduvall** [realm/realm-cocoa#5159]
## Goals
Swift allows you to move blocks out of the argument list when the argument is last. I propose moving `migrationBlock` to the end of the argument list in `Realm.Configuration`. It provides for much cleaner code. 

When defined as:
```swift
public init(fileURL: URL? = URL(fileURLWithPath: RLMRealmPathForFile("default.realm"), isDirectory: false),
   inMemoryIdentifier: String? = nil,
   syncConfiguration: SyncConfiguration? = nil,
   encryptionKey: Data? = nil,
   readOnly: Bool = false,
   schemaVersion: UInt64 = 0,
   migrationBlock: MigrationBlock? = nil,
   deleteRealmIfMigrationNeeded: Bool = false,
   shouldCompactOnLaunch: ((Int, Int) -> Bool)? = nil,
   objectTypes: [Object.Type]? = nil)
```

You have to define a migration block like so:
```swift
Realm.Configuration.defaultConfiguration = Realm.Configuration(
  schemaVersion: 1,
  migrationBlock: { migration, oldSchemaVersion in
    if (oldSchemaVersion < 1) {
      migration.enumerateObjects(ofType: Person.className()) { oldObject, newObject in
        let firstName = oldObject!["firstName"] as! String
        let lastName = oldObject!["lastName"] as! String
        newObject!["fullName"] = "\(firstName) \(lastName)"
      }
    }
  })
```
  
But if you move migrationBlock to the end of the argument list, you can define it like so:
```swift
Realm.Configuration.defaultConfiguration = Realm.Configuration(schemaVersion: 1) { migration, oldSchemaVersion in
  if (oldSchemaVersion < 1) {
    migration.enumerateObjects(ofType: Person.className()) { oldObject, newObject in
      let firstName = oldObject!["firstName"] as! String
      let lastName = oldObject!["lastName"] as! String
      newObject!["fullName"] = "\(firstName) \(lastName)"
    }
  }
}
```

## Expected Results
```swift
public init(fileURL: URL? = URL(fileURLWithPath: RLMRealmPathForFile("default.realm"), isDirectory: false),
	         inMemoryIdentifier: String? = nil,
	         syncConfiguration: SyncConfiguration? = nil,
	         encryptionKey: Data? = nil,
	         readOnly: Bool = false,
	         schemaVersion: UInt64 = 0,
	         deleteRealmIfMigrationNeeded: Bool = false,
	         shouldCompactOnLaunch: ((Int, Int) -> Bool)? = nil,
	         objectTypes: [Object.Type]? = nil,
	         migrationBlock: MigrationBlock? = nil)
```

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Thanks for the suggestion. Since we are planning a release with breaking changes in the near future it would be an ideal time to make such a change. I will discuss it with the team.

**Comment by austinzheng** [comment]
We've discussed this suggestion with the team, and after significant deliberation have decided to keep the method signature as-is.

Swift's trailing-closure syntax is intended for use in situations where:
- The method is intended to simulate control flow or scope, with the trailing closure serving as the body of the control flow. (An example of this is the `autoreleasepool()` function in Swift.) 
- The block argument to a method is the primary "object" of the method and it is unambiguous from both the naming and implied semantics of the method that the block is the argument of the method the caller would be expected to be most concerned about or interested in.

We don't feel that the migration block argument meets either criterion. The migration block is not the "most important" argument to the configuration initializer. It is also not immediately obvious what the semantics of an unlabeled trailing block argument to this initializer should be for someone not familiar with Realm. Requiring the block to be specified in-line with the rest of the arguments makes it absolutely clear to the reader of the code what its purpose is, and prevents it from being unduly privileged by the initializer syntax.

Thank you for your suggestion, and we hope you continue to enjoy using Realm!
