### ISSUE TITLE
RealmSwift object without final modifier

### ISSUE THREAD

**Issue by MarcoSantarossa** [realm/realm-cocoa#5181]
## Goals

My objects `Realm` and `Result` conform to a protocol to abstract these two objects. Then, I would like writing some tests to test the implementation of these protocols. My idea was to extend `Realm` and `Result` and check if the method of `super` are called. Unfortunately, I'm not able to do it since they are `final`.

## Expected Results

I want to be able to extend the objects.

## Actual Results

The classes are final

## Code Sample

```
protocol RealmType {
	func objects<T: Object>(type: T.Type) -> RealmResultType
}


extension Realm: RealmType {

	func objects<T: Object>(type: T.Type) -> RealmResultType {
                // I want to test that the protocol implementation calls this `objects` method
		return objects(type) as RealmResultType
	}
}
```

**Comment by austinzheng** [comment]
Thanks for using Realm.

For various internal reasons, it's not feasible for us to make those types non-final, nor do we intend to in the future.

I suggest you test your protocol by creating a dummy object that doesn't inherit from `Realm` or `Results` but has the correct methods, and ensure that the methods on that dummy object are called.
