### ISSUE TITLE
Attempting to modify object outside of a write transaction

### ISSUE THREAD

**Issue by wz1383691** [realm/realm-cocoa#5187]
## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
Could you please fill out [the template](https://raw.githubusercontent.com/realm/realm-cocoa/master/.github/ISSUE_TEMPLATE.md) with a couple of bits of important information: the version of Realm you are using, whether sync is enabled, the iOS version on which the problem occurs? Any suggestions about how to reproduce the issue.

This information will give us a much better chance of helping you.

Generally, the error occurs when attempting to save/modify/delete an object without using a transaction.


See https://realm.io/docs/swift/latest/#writes

**Comment by bdash** [comment]
@wz1383691, if there's still something we can help you with here, please provide the information requested in the issue template and reopen the issue.
