### ISSUE TITLE
2.9.0 crash with sortedResultsUsingKeyPath

### ISSUE THREAD

**Issue by aimobier** [realm/realm-cocoa#5194]
## Goals
Upgraded to 2.9.0 so that he can run the 2.8.3 version of the code. No changes were made to any code

## Expected Results
Normal execution

## Actual Results
carsh

````
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString containsString:]: unrecognized selector sent to instance 0x8fdd90'
````

## Code Sample
````objective-c
    RLMResults<OddityChannel *> *results =  [[[OddityChannel allObjectsInRealm:realm] objectsWhere:@"is_children = false"] sortedResultsUsingKeyPath:@"orderindex" ascending:true];
    
````

## Version of Realm and Tooling

Realm framework version: 2.9.0

Realm Object Server version:   Not in use

Xcode version: Version 8.3.3 (8E3004b)

iOS/OSX version:  7.1.2

Dependency manager + version: Cocoapods  1.3.0.rc.1

**Comment by austinzheng** [comment]
Can you provide us with a stacktrace please?

**Comment by bdash** [comment]
I think the issue here is that `-[NSString containsString:]` is new in iOS 8, while this app is running on iOS 7.

**Comment by aimobier** [comment]
I don't know how to express it. Hello, this is my[example](https://github.com/aimobier/realm_issues_5194). Running on a ios7 device must crash.

**Comment by bdash** [comment]
Please note that iOS 7 will not be supported for much longer. Our upcoming 3.0 release will drop support for it going forwards.
