### ISSUE TITLE
xcode8.3 - 使用swift3.3语言编写的项目，打包adHoc的时候提示Failed to verify bitcode in Realm.framework/Realm: error: Cannot extract bundle from /var/folders/bv/10kx4k9n5ks52m84rbx9tr240000gr/T/XcodeDistPipeline.sxT/Root/Payload/XFAWealthForPC.app/Frameworks/R…信息，不知道该怎么解决，求赐教！谢谢

### ISSUE THREAD

**Issue by JoyGY** [realm/realm-cocoa#5198]
## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by bdash** [comment]
Please provide all of the information requested in the new issue template.

**Comment by JoyGY** [comment]
问题已经解决，原因是自己创建的项目默认的Bitecode是开启的，但是这个框架的bitecode估计是关闭的，所以在打包的时候提示上面的问题，所以在”Build Settings”->”Enable Bitcode”设置为NO即可。如果工程需要支持bitcode，则必要要求所有引入的第三方库都支持bitcode。
