### ISSUE TITLE
Realm Cocoa fails to build with Carthage under Xcode9beta5

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-cocoa#5207]
## Goals
Build Realm cocoa with Xcode9 (beta 5) for use with iOS11 testing

## Expected Results
Carthage build of Realm Cocoa would complete successfully 

## Actual Results
Carthage buid fails with a timeout on RealmExamples.xcworkspace:

`xcodebuild timed out while trying to read RealmExamples.xcworkspace 😭`

## Steps to Reproduce

1. Download Xcode9beta5 (released 7-Aug-17)
2. Set it to be the default version of Xcode with xcode-select
3. Create a new single view iOS11 project
4. Create. new Cartfile in the project root directory for Realm, it should contain 1 line: `github "realm/realm-cocoa" "master"`
5. Attempt to build the Carthage artifacts with `carthage bootstrap` or `carthage update` from the command line
6. After 5-6 mins the build will fail with the following error:
`xcodebuild timed out while trying to read RealmExamples.xcworkspace 😭`

This doesn't fail with code 8.3.3 and did it fail with Xcode9beta4.

## Code Sample
N/A

## Version of Realm and Tooling

Realm framework version: N/A - building from Realm master which as present is 

Realm Object Server version: N/A

Xcode version: ? 
Xcode9Beta5 (9M202q)

iOS/OSX version: ? 
10.12.6 (16G29)

Dependency manager + version: ? 
Carthage v0.24.0

**Comment by bdash** [comment]
This appears to be an Xcode bug, introduced in Xcode 9 beta 5. It can be reproduced independently of Carthage by running the following command from the top level of the realm-cocoa source tree:

```
xcodebuild -workspace examples/tvos/swift-3.1/RealmExamples.xcworkspace -scheme PreloadedData -configuration Release clean -showBuildSettings -skipUnavailableActions
```

**Comment by bdash** [comment]
@dhmspector mentioned via Slack that he would report this issue to Apple. David, would you please share the Radar number here after you've done so?

**Comment by dhmspector** [comment]
done: filed as #33763197
