### ISSUE TITLE
SyncPermissionValue Closure Never Invoked in v3.0.0-beta.2

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-cocoa#5211]
## Goals
I want to apply permissions to a shared realm for an admin user as well as all over uers.

## Expected Results
Using `SyncPermissionValue` should apply permissions.

## Actual Results
The closure inside `SyncPermissionValue` is never called.

## Steps to Reproduce
1. Install ROS v2.0.0-rc2 on Ubuntu 16.04
2. Install Realm v3.0.0-beta.2 and build in Xcode 8.3.3
3. Authenticate with an admin user.
4. Apply permissions.
5. Wimper softly at your desk and go home from work early.

## Code Sample
```
let admin = SyncCredentials.usernamePassword(username: "admin@email.com", password: "abc123")
let sharedRealmURL = URL(string: "realms://myrealmserver.net:9443/shared")!

SyncUser.logIn(with: admin, server: serverURL) { user, error in
  if let user = user {

  print("Got the admin? \(user.isAdmin)") //This logs 'true'

  //Setup synced realm with a shared 
  let configShared = Realm.Configuration(
    syncConfiguration: SyncConfiguration(user: user, realmURL: sharedRealmURL),
    objectTypes: [Announcement.self, Version.self]
  )

  //Initialize to create the "shared" realm    
  let _ = try! Realm(configuration: configShared)

  //Set admin permissions for shared realm (this may not be necessary)
  let permission = SyncPermissionValue(realmPath: "/shared", userID: "help@pilotpro.com", accessLevel: .write)
  user.applyPermission(permission) { error in
    if let error = error {
      print("Permissions error:\n\(error)") //Never logged
      return
    }
    print("Permissions successfully applied") //Never logged
  }

  //Give all users access to this shared realm  
  let permission2 = SyncPermissionValue(realmPath: "/shared", userID: "*", accessLevel: .read)
  user.applyPermission(permission2) { error in
    if let error = error {
      print("Permissions error 2:\n\(error)") //Never logged
      return
    }
    print("Permissions successfully applied 2") //Never logged
  }
      
  //Sign out admin
  user.logOut()
  
  } else {
    print("Error signing in:\n\(error)") //Not logged
  }
}
```
At this point, I see the `/shared` realm on my server, but no permissions applied. Screenshot: http://d.pr/i/hSnWVE

All the user-specific realms and syncing work fine otherwise.

## Version of Realm and Tooling
Realm framework version: **3.0.0-beta.2**
Realm Object Server version: **2.0.0-rc2**
Xcode version: **8.3.3**
iOS/OSX version: **macOS 10.12.6**
Dependency manager + version: **Carthage 0.24.0**

**Comment by bdash** [comment]
@austinzheng, can you please take a look at this?

**Comment by austinzheng** [comment]
Hi Clifton,

There are at least two issues with your code.

- You are fetching permissions on a queue that doesn't come with a runloop. You should dispatch to the main queue and then perform your work there. (We plan to change this behavior in an upcoming release candidate so that the login callback runs on the main queue by default, since this has been a perennial source of user issues since we released the product.)

-  The callbacks to `applyPermission` run asynchronously, which means if you write out your code synchronously like you've done here your code will just make all the calls and immediately log out without waiting for any of the permission calls to actually succeed or fail.

Hope that helps.

**Comment by cliftonlabrum** [comment]
Thank you very much, @austinzheng. You are very smart. 🙂

**Comment by cliftonlabrum** [comment]
I have a follow-up question. When I do this:

```
SyncUser.logIn(with: admin, server: serverURL) { user, error in
  DispatchQueue.main.async{
    if let user = user {
      //Set permissions for shared realm
      let permission = SyncPermissionValue(realmPath: "/shared", userID: "*", accessLevel: .read)
      user.applyPermission(permission) { error in
        if let error = error {
          print("Permissions error:\n\(error)")
          return
        }
        print("Permissions successfully applied")
        //Sign out admin
        user.logOut()
      }
    }else{
      print("no user!")
    }
  }
}
```
...I get the following error in the Xcode console: 

```
Sync: Connection[2]: Session[2]: Sending: BIND(server_path='//ae42e46923193f05338d98917d3c21f9/__management', signed_user_token_size=665, need_file_ident_pair=1)

Sync: Connection[2]: Received: ERROR(error_code=204, message_size=25, try_again=0, session_ident=2)

Sync: Connection[2]: Connection closed due to error reported by server: Illegal Realm path (BIND) (204)
```

Is the illegal path the `/shared` one I'm using? Or the virtual path `server_path='//ae42e46923193f05338d98917d3c21f9/__management'` that I see in the console? I'm not specifying that `server_path` so I believe Realm is choosing it. the `ae42e...` is the `UserId` of my administrator user.

**Comment by cliftonlabrum** [comment]
@austinzheng Are you able to reproduce the issue I have shown above?

**Comment by austinzheng** [comment]
Hi Clifton,

That is a very distressing error message indeed. What is your `serverURL` you are using to log in? If it contains a final slash, can you try stripping it? (Regardless of whether or not that works the fact that ROS is rejecting the path you reported above is a bug we need to fix.)

**Comment by cliftonlabrum** [comment]
Ah, interesting. My `serverURL` did, in fact, have a trailing slash. 

**Before:** `https://myrealmserver.net:9443/`
**After:** `https://myrealmserver.net:9443`

I removed it and it now works. In fact, several of the permissions-related functions I had been trying to use weren't working until now. 🙂 I'm relieved. Thanks for pointing that out!

**Comment by austinzheng** [comment]
I'm glad it works! Feel free to let us know if you run into any other issues.
