### ISSUE TITLE
RealmSwift Module compiled with Swift 3.1 cannot be imported in Swift 3.2 in iOS 11 beta 5

### ISSUE THREAD

**Issue by Sudhi55** [realm/realm-cocoa#5229]
<!---
RealmSwift v2.9.1 module is compiled in Swift 3.1 & cannot be imported into Swift 3.2 for iOS 11 Beta 5 in Xcode 9.0 beta 5 (9M202q). And it generates a compiler error. 

Realm framework version: 2.9.1

Xcode version: Xcode 9.0 beta 5 (9M202q)

iOS/OSX version: iOS 11 beta 5

Dependency manager + version: Carthage

**Comment by bdash** [comment]
We don't publish prebuilt binary frameworks built with prerelease versions of Xcode as there's no guarantee of compatibility between beta versions. Prebuilt binary frameworks for Swift 3.2 will be available after Xcode 9 is out of beta.

For now, the recommended means of using Realm Swift with beta versions of Xcode 9 is to build Realm from source. [CocoaPods](https://realm.io/docs/swift/latest/#cocoapods-install) and [Carthage](https://realm.io/docs/swift/latest/#carthage-install) are the easiest ways to do this as they either always build from source (CocoaPods) or will automatically fall back to building from source if the prebuilt binary is from a different Swift version (Carthage).

**Comment by kishikawakatsumi** [comment]
It looks to me as if we've answered your question. I'm going to close this issue. Please feel absolutely free to open a new one if you have more questions.

**Comment by Sudhi55** [comment]
Yes, we were able to get RealmSwift working on iOS 11 beta 6 with Xcode 9 beta 5 (latest Aug 21, 2017). Here's the steps for users still having issues:

-  Move Xcode-beta.app to Applications folder
-  Point command line tools to Xcode 9.0 by using below command  or change it directly in Xcode preference
sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer
-  Delete cartfile.resolved and carthage folders
-  Do carthage update by using the command - carthage update --platform iOS --no-use-binaries

**Comment by bogdan-razvan** [comment]
Is there any change to get RealmSwift to work with Xcode9 Beta and Swift 4 if I'm using Cocoapods, and not Carthage?

**Comment by jannejava** [comment]
+1

**Comment by bdash** [comment]
Using Realm Swift with Xcode 9 beta and CocoaPods should only require that you've configured CocoaPods to use the appropriate Swift version. If you're hitting a specific problem when doing this, please file a new issue and provide the details requested in the issue template.
