### ISSUE TITLE
"Linker Command Failed" when Including RealmSwift framework into a private pod project

### ISSUE THREAD

**Issue by ivsall2012** [realm/realm-cocoa#5230]
Hi guys, I'm developing a project in pieces of private pods.
Currently, my database layer is using regular "s.dependency 'RealmSwift' " in its podspec file.
And the building for Realm module is really slow. It takes even more time when I do a "pod spec lint"(over 5 minutes). 
This also slows down the development of those pods that involves with the database layer -- Xcode rebuild all pods in the project after every "pod install".

So I decided to use RealmSwift as a framework in the database layer, instead of source codes.

## Goals

Including Realm/RealmSwift dynamic frameworks into the database layer pod project in order to speed up compiling time. 
(Realm.framework is a C/Objective-C static framework and ReamSwfit.framework is a swift dynamic framework right?)

## Expected Results

Here's the line I added to my podspec:
s.vendored_frameworks = 'XXXX/Realm.framework', 'XXXX/RealmSwift.framework'

After I "pod install", those two frameworks are indeed added into the project:
![Image of The developing pod](https://firebasestorage.googleapis.com/v0/b/savori-6387d.appspot.com/o/Screen%20Shot%202017-08-12%20at%204.06.55%20PM.png?alt=media&token=9f1cf7e5-8250-44a9-ba25-aa07d120de5a)

And I can import RealmSwift and use it as usual with autocompletion but Xcode just won't build it!

## Actual Results
![](https://firebasestorage.googleapis.com/v0/b/savori-6387d.appspot.com/o/Screen%20Shot%202017-08-12%20at%204.06.49%20PM.png?alt=media&token=48d0d4db-348d-4569-aa75-0e6f143e7018)

## Steps to Reproduce
1. Use "pod lib create XXXX" to create  a private pod.
2. Within the project folder, copy Realm.framework and RealmSwift.framework into folder XXXX.
3. Add the following line to the XXXX.podspec file:
s.vendored_frameworks = 'XXXX/Realm.framework', 'XXXX/RealmSwift.framework'
4. Do a "pod install" then in Xcode, import RealmSwift to any swift class file.
5. Now everything seems right, and you can use Realm. But Xcode won't build and gives a linker error shown in the image attached above.
 
## Code Sample
Here's the sample pod project:
https://firebasestorage.googleapis.com/v0/b/savori-6387d.appspot.com/o/Realm_Test_ProjectAA.zip?alt=media&token=fc7607e8-f5ef-4521-aed8-1e5ea15fbfd5

## Version of Realm and Tooling
Realm framework version: 2.8.3

Xcode version: 8.3.2

iOS/OSX version: 10.3

Dependency manager + version: CocoaPods, 1.3.0.beta.2

**Comment by bdash** [comment]
Note that the image doesn't show the actual linker error, only the fact that an error occurred. The actual linker error, available via the Report navigator (View -> Navigators -> Show Report Navigator) then clicking on the failing build, will provide details that will help understand what's going wrong.

**Comment by ivsall2012** [comment]
Hey Mark, thank you for your reply!
The linker error is "Framework not found Realm for architecture x86_64".
I tried to build it in generic iOS device and iPhone 5 and they all failed.
Basically Xcode couldn't find all of the architectures: i386, x86_64, armv7, arm64.
I did a "lipo -info" to both Realm/RealmSwift and they actually do support all four architectures.

I noticed that all those errors are from the test target.
So I deleted the test target, all its related files and deleted it from the Podfile as well.
Surprisingly, the build succeeded!
I then tried to do the same for my database project, deleting all test related things. 
But I got the same errors about Xcode not being able to find the architecture supports.

**Comment by bdash** [comment]
If the frameworks you checked have all of the architectures in question, my guess is that Xcode is instead finding _different_ copies of those frameworks, with different architectures, that you have lying around somewhere. I'd suggest checking the framework search paths that Xcode is passing through to the compiler (look for `-F/some/path` in the build log), and seeing if you can't find different copies of the Realm / RealmSwift frameworks somewhere in those search paths.

**Comment by ivsall2012** [comment]
I found the `-F` path and here's the relevant report:
1. the warning
> ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/Developer/Library/Frameworks'
2. the error
> ld: framework not found Realm for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The only `-F` path I can find is from the warning which complains the path doesn't exist. This warning also appears on every my pod projects created by `pod lib create` , don't know why. 

To verify if this error comes CocoaPods or Realm, I created a dummy framework which supports all of the architectures and added it to the project.
With Realm disable, the project gets built successfully.

I have been stuck with this problem for days!
Could you spend a few minutes and take a look at the sample project? 
Here is the updated project including Realm and the dummy framework: [zip(32.96 MB)](https://firebasestorage.googleapis.com/v0/b/savori-6387d.appspot.com/o/Realm_Test_ProjectBB.zip?alt=media&token=24db5807-23e8-482c-bc14-39581d9b7658) 

Thanks a lot!

**Comment by bdash** [comment]
The warning you're seeing is harmless. That path is something Xcode adds automatically to the framework search path, even though it happens to not exist.

> Could you spend a few minutes and take a look at the sample project?

What steps do I need to take with the zip file in question in order to reproduce the problem? I opened RealmTest.xcworkspace within the Example directory and it builds and runs in the iOS simulator without problems.

**Comment by ivsall2012** [comment]
Can you uncomment `import RealmSwift` at the top of the class file `TestClass.swift` which is under group path `Development Pods/RealmTest/RealmTest/Classes` within the `Pods` project in RealmTest.xcworkspace?

**Comment by bdash** [comment]
Thanks, that does produce the problem you describe.

This looks to me like a problem with the Xcode project generated / modified by CocoaPods. I'd suggest reaching out to the CocoaPods team for help in understanding what's going wrong. It's hard to see any way that Realm itself could be responsible for the problem here. If you find otherwise, please do report back with more information and we'll be happy to help address the problem.

**Comment by hellomaya** [comment]
Unfortunately I have seen the same issue in my Xcode project too, the project is a Cocoa Touch Static Library, and I have tried both dynamic and static Realm.framework, it just gave me the same error as above:

```
ld: framework not found Realm for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The project was a react native based iOS project, so might be something wrong with react native? And the Realm.framework assed to the static library only.

I am using Realm.framework 2.9.1, it was running with Xcode 8.3.2 and iPhone Simulator.

**Comment by bdash** [comment]
Please file a new issue about build problems you're having unless you're 100% sure you're hitting the exact same problem for the exact same underlying reason. From the information you've provided there's no reason to think you're seeing the same problem that @ivsall2012 initially reported here.

**Comment by hellomaya** [comment]
OK， I will do, thanks.
