### ISSUE TITLE
why do not open Realm Browser

### ISSUE THREAD

**Issue by taogeyijiu** [realm/realm-cocoa#5231]
<img width="717" alt="wx20170814-153327 2x" src="https://user-images.githubusercontent.com/17825349/29262504-766c0808-8107-11e7-9eb4-6416c53ed60c.png">

**Comment by bdash** [comment]
Please provide the information that was requested in the new issue template and described in our [documentation on filing issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues).

Other information that is likely to be relevant in this case, beyond that listed in the Filing Issues section of the documentation:
* What does the configuration look like that you're using to create the Realm?
* Which version of the Realm Browser are you using to open the Realm file?

**Comment by bdash** [comment]
If you're still encountering this problem, please provide the information requested above and then reopen the issue.
