### ISSUE TITLE
To have Dynamic Realms API in objc similar to java API

### ISSUE THREAD

**Issue by hellomaya** [realm/realm-cocoa#5232]
## Goals

I am working on a react native native module, which is simply a static lib of an iOS app by objc, because it had to calculate a large data set from realm db, for example, sum, or get average of them. I had to use native module to do so, as it's too slow in JS, simply by using Realm objc api.

In JS, it had defined the Realm schema and saved the data, so to access those data in objc is all necessary, the problem is that, after I have read the objc docs, I didn't find the similar way as same as the java API https://realm.io/docs/java/latest/#dynamic-realms.

By using dynamic realms in java, it's possible to access the data with schema name only, not model class. It makes possible to access the schema and data defined in JS, then to calculate a large data set in objc possible by interaction with javascript as well.

So is it anyway else to access the data by using schema name only, or we can have similar dynamic realms in objc too?

## Expected Results

To access Realm-JS defined schema data by schema name.

## Actual Results

Can't do it.

## Version of Realm and Tooling

Realm framework version: ?

2.9.1

Realm Object Server version: ?

None

Xcode version: ?

8.3.2

iOS/OSX version: ?

10.12.6

Dependency manager + version: ?

None

**Comment by bdash** [comment]
Cocoa has a dynamic API available in [RLMRealm_Dynamic.h](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm_Dynamic.h) and [RLMObjectBase_Dynamic.h](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMObjectBase_Dynamic.h).

**Comment by hellomaya** [comment]
Thank you, it do have what I am looking for, but when I try Realm.framework at Xcode, I have got this issue:

https://github.com/realm/realm-cocoa/issues/5230

See the comment I have added there.
