### ISSUE TITLE
Whats the correct way to make Realm compatible with XCode Beta 9 and Swift 4 using Carthage?

### ISSUE THREAD

**Issue by ggirotto** [realm/realm-cocoa#5235]
I would like to know how can I build Realm from source using Carthage. I currently working in a project for watchOS 4 using Swift 4, and I when I try to build the project It's return the following error message

**Module compiled with Swift 3.1 cannot be imported in Swift 4.0**

I was looking for a solution when I found here in issues that @bdash said [here](https://github.com/realm/realm-cocoa/issues/5229) that the recommendation for using Realm with Beta Versions is to build it from the source, but how do I exactly do this using Carthage?

I've tried to install Realm using ```--platform iOS --no-use-binaries``` but no success.

**Comment by bdash** [comment]
When running `carthage update --platform iOS`, I see output similar to the following:
```
*** Fetching realm-cocoa
*** Downloading realm-cocoa.framework binary at "v2.9.1"
*** Skipped installing realm-cocoa.framework binary due to the error:
        "Incompatible Swift version - framework was built with swiftlang-802.0.53 clang-802.0.42 and the local version is swiftlang-900.0.59 clang-900.0.34.2."
*** Checking out realm-cocoa at "v2.9.1"
*** xcodebuild output can be found in /var/folders/cy/9dj49tyx5sbb5nthgbndrwlc0000gn/T/carthage-xcodebuild.AXhSZo.log
```

This indicates that Carthage downloaded the Realm v2.9.1 binary release, noticed that it was built with an older version of Xcode, and then reverted to downloading and building from source.

If you're _not_ seeing this happen, it's likely that your Xcode command-line tools are configured to use a different version of Xcode than you're building with. You can confirm this by looking at the output of `xcode-select -p` and `xcodebuild -version`. If they don't return values that indicate that Xcode 9 beta is being used, then you need to change the version of the Xcode command-line tools that Carthage is using. You can do this in two ways:

1. `sudo xcode-select -s /path/to/Xcode-beta.app`
   This will change the Xcode version used by the Xcode command-line tools until the next time you run a similar command.

2. `DEVELOPER_DIR=/path/to/Xcode-beta.app carthage update --platform iOS`
   This overrides the Xcode version for the single command invocation only. You'll need to remember to override the Xcode version the next time you run `carthage update`.

**Comment by ggirotto** [comment]
Actually I was using xcode 8.3.3. Thank you man 👍

**Comment by bdash** [comment]
Happy to help!
