### ISSUE TITLE
Performance issue. Re-sort when record's value changed. 

### ISSUE THREAD

**Issue by Kirow** [realm/realm-cocoa#5237]
## Steps to Reproduce
1. Create table.
2. Add two field
3. Make RLMResults sorted by one field.
4. modify any record by another field

## Code Sample
I've created [sample project here](https://github.com/Kirow/RealmSortIssue)

## Actual Results
Got freezes because of re-sort of large data source
![Screenshot from Instruments](https://github.com/Kirow/RealmSortIssue/blob/master/Screen%20Shot%202017-08-16%20at%202.23.25%20PM.png?raw=true)

## Expected Results
Re-sort must not happen, because I did not change any values that involved in filter predicate or sort descriptor.

## Version of Realm and Tooling
Realm framework version: 2.9.1
Xcode version: 8.3.3
iOS/OSX version: iOS 10.3
Dependency manager + version: COCOAPODS 1.3.1

**Comment by bdash** [comment]
Thanks for providing the test case that demonstrates the performance optimization you noted. I've filed realm/realm-core#2803 to track it and several related optimizations. Since this optimization would be made entirely at the realm-core level, please follow that issue for updates.

**Comment by RetVal** [comment]
@bmunkholm here is the same case I think
