### ISSUE TITLE
Changing ignoredProperty through LinkingObjects has no effect on the property

### ISSUE THREAD

**Issue by Pattio** [realm/realm-cocoa#5238]
## Goals
I want to change ignoredProperty (animateCircle) value like that:

```
let realm = try! Realm()
var memorySections = Array(realm.objects(MemorySection.self))

print(memorySections[0].memories[0].animateCircle)
memorySections[0].memories[0].animateCircle = false
print(memorySections[0].memories[0].animateCircle)
```

However I get wrong output. If I had animateCircle property directly in MemorySection instead of Memory, code below would work and I would get desired output.

```
let realm = try! Realm()
var memorySections = Array(realm.objects(MemorySection.self))

print(memorySections[0].animateCircle)
memorySections[0].animateCircle = false
print(memorySections[0].animateCircle)
```
## Expected Results

I expect to get this output:

true
**false**

## Actual Results

However I get this output:

true
**true**

## Steps to Reproduce
Use Code Sample bellow, try to build, see console

## Code Sample

**MemorySection.swift** 

```
class MemorySection: Object {
    let memories = LinkingObjects(fromType: Memory.self, property: "section")
}

```
**Memory.swift**

```
class Memory: Object {
    dynamic var section: MemorySection?
    var animateCircle: Bool = true
    
    override static func ignoredProperties() -> [String] {
        return ["animateCircle"]
    }
}
```

**MainViewController.swift** 

```
let realm = try! Realm()
var memorySections = Array(realm.objects(MemorySection.self))

print(memorySections[0].memories[0].animateCircle)
memorySections[0].memories[0].animateCircle = false
print(memorySections[0].memories[0].animateCircle)
```

## Version of Realm and Tooling
Realm framework version: 2.9.1

Xcode version: 8.3.3 (8E3004b)

iOSversion: 10.3

**Comment by Kirow** [comment]
I guess that every time you make ```memorySections[0].memories[0]``` you will get newly created object. Just check reference, it should be different. That will explain your issue.

to get desired output you may do this:
```
var memory = memorySections[0].memories[0]
print(memory.animateCircle)
memory.animateCircle = false
print(memory.animateCircle)
```

**Comment by Pattio** [comment]
So if I access property which has LinkingObjects type, realm basically does new query each time to get those objects? And yeah, I noticed that making an explicit copy of single Memory and then changing value gives desired output, however it is not useful for my problem. I guess to solve my problem I could  create an array of bool values in MemorySection model to represent animateCircle property for each memory. 

Also, if indeed realm makes new queries each time I access a property of LinkingObjects type isn't it expensive. And is it also semantically correct that changing property of an object which is stored in array doesn't have any effect?

Thank you for your reply.

**Comment by bdash** [comment]
All Realm collection types (`Results`, `Lists`, and `LinkingObjects`) create instances of their corresponding `Object` subclass as the items in the collection are accessed. The collection types do not store any references to these objects, they're only returned to the caller. This means that each time you retrieve an object from such a collection, you see a unique, freshly-allocated object.

**Comment by Pattio** [comment]
@bdash Thank you for your response, now it makes sense.
