### ISSUE TITLE
'RLMObject subclasses with the same name cannot be included

### ISSUE THREAD

**Issue by sphairo** [realm/realm-cocoa#5243]
Terminating app due to uncaught exception 'RLMException', reason: 'RLMObject subclasses with the same name cannot be included twice in the same target. Please make sure 'CMParserModels' is only linked once to your current target.

**Comment by bdash** [comment]
@sphairo, can you please provide the information that was requested in the new issue template, which is also listed in the [Filing Issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) section of our documentation on contributing to Realm. Please also let us know what it is about the error message you're seeing that you're having trouble with.

**Comment by bdash** [comment]
@sphairo, we need the information I requested above in order to assist you with this. If you still need assistance with this problem, please provide that information and reopen the issue.
