### ISSUE TITLE
Realm Swift 3.0 Beta Can't Be Submitted to the App Store

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-cocoa#5249]
Avi Warner at Realm suggested I ship my app with the Realm 3.0 beta and ROS 2.0 beta to avoid a nightmarish migration later.

When attempting to archive the binary for the App Store, I get the following error:

<img width="502" title="The value for key CFBundleVersion [3.0.0-beta.2] in the Info.plist file must be a period-separated list of at most three non-negative integers." src="https://user-images.githubusercontent.com/2513753/29550435-8ee81f64-86c2-11e7-872d-9b6807842819.png">

> The value for key CFBundleVersion [3.0.0-beta.2] in the Info.plist file must be a period-separated list of at most three non-negative integers.

These seems to just be a naming issue. Is this something I can modify on my own to allow my app to be submitted?

Thanks!

**Comment by bdash** [comment]
Thanks for this report. We'll look to fix this shortly. Until then you should be able to tweak `CFBundleVersion` in Realm's Info.plist yourself to drop the `-beta.2` suffix.

**Comment by bdash** [comment]
Fixed by #5256.
