### ISSUE TITLE
Realm outgoing network data

### ISSUE THREAD

**Issue by pokerman79** [realm/realm-cocoa#5250]
I understand that per:
https://github.com/realm/realm-cocoa/blob/master/Realm/RLMAnalytics.mm#L19-L53

when conditions are meet (simulator, debugger is attached) Realm will emit analytics data to mixpanel

When environment variable REALM_DISABLE_ANALYTICS is set, by the code no analytic data will be sent, and this is true, there will be no outgoing connection to mixpanel

But now there is new outgoing connection to academy.realm.io on port 443

What is purpose of this connection if not analytics ?

ios 9.0
Realm Swift 2.9.1

**Comment by kishikawakatsumi** [comment]
@pokerman79 We don't send network requests to `academy.realm.io`, probably `static.realm.io`?

We check whether it is the latest version or not if Realm is running on simulators. 

Https://github.com/realm/realm-cocoa/blob/216333cf82e1afcba5e6c4547e6fb983165d510f/Realm/RLMUpdateChecker.mm#L28-L48

This request just get a version number. User data is not sent. If you also want to stop this network connection, set `REALM_DISABLE_UPDATE_CHECKER` environment variable.
