### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by qq565999484** [realm/realm-cocoa#5257]
2017-08-23 18:17:48.548 RealmSwiftDemo[20671:3180440] *** NSForwarding: warning: object 0x103cd97b0 of class 'RealmSwiftDemo.Dog' does not implement methodSignatureForSelector: -- did you forget to declare the superclass of 'RealmSwiftDemo.Dog'?
2017-08-23 18:17:48.549 RealmSwiftDemo[20671:3180440] *** NSForwarding: warning: object 0x103cd97b0 of class 'RealmSwiftDemo.Dog' does not implement doesNotRecognizeSelector: -- abort

**Comment by kishikawakatsumi** [comment]
Please provide the information that was requested in the new issue template and described in our documentation on filing issues.

Also, please provide your code including at least the definition of the model. We have never seen such a log. I think that there is probably something wrong with the definition of the model.

@qq565999484

**Comment by qq565999484** [comment]
#------this is alll code:
```swift

import UIKit
import RealmSwift

class Dog: Object
{
    
    @objc dynamic var name = ""
    @objc dynamic var age = 0
 
    override var description: String { return "dog {\(name), \(age)}" }
}
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        let myDog = Dog(value: ["name":"1xasxa22","age" : 2])
        let myDog2 = Dog()
        myDog2.name = "DeLorean"
        myDog2.age = 111

        let realm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "TemporaryRealm"))
        
        try! realm.write {
            realm.add(myDog)
            realm.add(myDog2)
        }
        return true
    }
```

**Comment by qq565999484** [comment]
#------this is alll code: ---》Of course, I've tried it：
```swift

import UIKit
import RealmSwift

class Dog: Object
{
    
     dynamic var name = ""
     dynamic var age = 0
 
    override var description: String { return "dog {\(name), \(age)}" }
}
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        let myDog = Dog(value: ["name":"1xasxa22","age" : 2])
        let myDog2 = Dog()
        myDog2.name = "DeLorean"
        myDog2.age = 111

        let realm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "TemporaryRealm"))
        
        try! realm.write {
            realm.add(myDog)
            realm.add(myDog2)
        }
        return true
    }
```

**Comment by qq565999484** [comment]
**My Realm.FrameWork was towed directly to the project**

**Comment by bdash** [comment]
@qq565999484, did you see the list of information requested in the new issue template and [in our documentation on filing issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues)? It appears that the majority of the information requested in those two places has not yet been provided.

**Comment by qq565999484** [comment]
Sorry, I may not understand what you mean because of my low level

**Comment by austinzheng** [comment]
Can you send us your project? You can make it into a zip file and attach it to this GitHub ticket. Then we can run it and see what is happening.

**Comment by qq565999484** [comment]
[RealmSwiftDemo.zip](https://github.com/realm/realm-cocoa/files/1247470/RealmSwiftDemo.zip)
I'm sorry, because I will upload limit, to cancel the inside of the Realm.framework and RealmSwift.framework. You need to add.Framework.

**Comment by bdash** [comment]
Which version of Realm are you using? That's one of the pieces of information that we requested earlier.

**Comment by qq565999484** [comment]
**realm-swift-2.10.0.zip=>swift-3.1 xcode: xcode8.3.3  OS:10.12.6**

**Comment by austinzheng** [comment]
I opened your project in Xcode and note that you only have the RealmSwift framework defined in your project navigator. [Our instructions](https://realm.io/docs/swift/latest/#installation) say you need _both_ the `RealmSwift.framework` and `Realm.framework`. Can you add `Realm.framework` to your application and try again please?

**Comment by austinzheng** [comment]
Once I added both frameworks, the project built and ran without errors on my computer.

**Comment by qq565999484** [comment]
thanks。

**Comment by qq565999484** [comment]
**# Thank you very much for your help**
![error](https://user-images.githubusercontent.com/12536862/29695954-422e9884-8978-11e7-9de3-09bc268f6b7b.png)
