### ISSUE TITLE
DELETING MULTIPLE ROWS FROM TABLEVIEW, 3 sections, 3 arrays for them, and delete

### ISSUE THREAD

**Issue by arerbol** [realm/realm-cocoa#5263]
## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by arerbol** [comment]
func okHandler(alert: UIAlertAction!){
        if selectedindex == 0 {
            if selectedcellindexes1.count > 0 {
                for i in selectedcellindexes1 {
                        try! uiRealm.write {
                            uiRealm.delete(completedAsgn[i])
                            ReadAndUpdate()
            }
                }
            }
            if selectedcellindexes2.count > 0{
                for i in self.selectedcellindexes2 {
                    
                        try! uiRealm.write {
                            uiRealm.delete(self.currentAsgn[i])
                            ReadAndUpdate()
                        }
                        
                    }
                    
                }
            
        
        }else {
            if selectedcellindexes.count > 0{
                for i in selectedcellindexes{
                    try! uiRealm.write {
                        uiRealm.delete(bitkenAsgn[i])
                        ReadAndUpdate()
                    }
                }
            }
        }
        

        updatevc()
        ReadAndUpdate()
        
    }

**Comment by austinzheng** [comment]
Hi. Please provide all the information we ask for in our issue template and _clearly state the problem you need help with_. Thank you.

**Comment by austinzheng** [comment]
If you are still experiencing this problem and can provide us with the information in the issue template, please feel free to reopen this issue.
