### ISSUE TITLE
Type-safe NSPredicates and SortDescriptors using #keyPath()

### ISSUE THREAD

**Issue by blwinters** [realm/realm-cocoa#5269]
With Swift 4 it seems we are required to use the `@objc` attribute when using the `dynamic` modifier. Since Realm `Object` subclasses need their properties to be `dynamic`, it seems natural to use `#keypath()` to create type-safe `NSPredicate` and `SortDescriptor` for Realm queries.

Example:

    class Person: Object {
    
        @objc dynamic var parent: Person?
    
        @objc dynamic var name: String?
    
        init(name: String) {
            self.init()
            self.name = name
        }
    }

    let grandparent = Person(name: "Bill")
    let path = #keyPath(Person.parent.parent)
    let predicate = NSPredicate(format: "\(path) == %@", grandparent)

I recently did some heavy restructuring/renaming that would have been much easier if the compiler could have checked these key paths. I don't see this approach mentioned in the documentation and maybe it's too soon to target Swift 4, but I think it would be good to add for Swift developers like myself who aren't accustomed to using `#keyPath()`. That being said, I'm not an expert so please let me know if there are drawbacks or other considerations.

*This issue is partly a suggestion to include something about* `#keyPath()` *in the Realm Swift documentation and also a request for some discussion on type-safe key path usage with Realm.*

**Comment by kishikawakatsumi** [comment]
@blwinters Probably https://github.com/kishikawakatsumi/RealmTypeSafeQuery is what you want? This library uses undocumented API because Swift's KeyPath doesn't provide an API to retrieve string representation. (https://bugs.swift.org/browse/SR-5220)

So we cannot use it in Realm public API for now, we provide the library as separated instead.

**Comment by blwinters** [comment]
@kishikawakatsumi Yes, that's exactly what I had in mind. I'll be watching both that project and the Swift bug. I'd rather not have a separate library just for this behavior, but I'll definitely incorporate it when it's available natively.
