### ISSUE TITLE
deleteRealmIfMigrationNeeded not working

### ISSUE THREAD

**Issue by yusufoos** [realm/realm-cocoa#5272]
In my realm configuration I am using:
`        var configuration = Realm.Configuration(fileURL: appURL, schemaVersion: 0)
        configuration.deleteRealmIfMigrationNeeded = true
`

And yet I see the following errors in my logs:

Realm database error. Error Domain=io.realm Code=10 "Migration is required due to the following errors:
- Primary Key for class 'FalxEventEntity has been added.
- Property 'FalxEventEntity.processedByAggregator' has been added.
- Property 'FalxEventEntity.primaryID' has been added." UserInfo={NSLocalizedDescription=Migration is required due to the following errors:
- Primary Key for class 'FalxEventEntity has been added.
- Property 'FalxEventEntity.processedByAggregator' has been added.
- Property 'FalxEventEntity.primaryID' has been added., Error Code=10}

## Expected Results
Because of the schema mismatch it should just delete the schema as I specified deleteRealmIfMigrationNeeded = true

## Actual Results
It does not delete realm, instead I get the realm database error

**Comment by bdash** [comment]
The error in question should definitely be suppressed by `deleteRealmIfMigrationNeeded`, which makes me think that you happen to be opening the Realm before you've enabled that configuration option.

Can you set a breakpoint (or add a print statement) before you do `configuration.deleteRealmIfMigrationNeeded = true` and verify that it is hit before you see the error raised?

**Comment by yusufoos** [comment]
I'm not able to reproduce it consistently, I noticed it on the logs of some of our devices, I wonder if something is stopping it form performing a migration. I see the error every time we try to save an event, which is odd. Also odd that I don't see it on all devices.
