### ISSUE TITLE
Problem while converting realm object to NSDictionary

### ISSUE THREAD

**Issue by siddharthsuneel** [realm/realm-cocoa#5282]
I have used Relam in my project & whenever I m trying to convert or typecast any relam Object/Data to NSDictionary App crashes.
Any assistance in this regard will be very helpful.

**Comment by bdash** [comment]
Please share a sample of the code you're using that's causing you trouble. Please also provide the information that was requested in the GitHub issue template, which you can [also see requested in our documentation on Filing issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues).

**Comment by siddharthsuneel** [comment]
let realm = try! Realm()
let countryData = realm.objects(CountryData.self)
var dataSource = [CountryData]()
dataSource.append(contentsOf: countryData)

//Now I have passed this data source to another View Controller where this CountryData will get displayed on a UITableView with custom UITableViewCell

cell.setDataInCell(modelObj: dataSource.object(at: indexPath.row) as! NSDictionary)*
Note: This method "setDataInCell" takes NSDictionary as an argument

*This is the line where I am getting crash issue.

And this is how CountryData Model looks like-
class CountryData:Object {
    dynamic var id:Int = -1
    dynamic var name:String?
    dynamic var countryCode:String?
    dynamic var servicesApplicable:Bool = false
}

**Comment by bdash** [comment]
In your code snippet `dataSource` is an array of `CountryData` objects, meaning that `dataSource.object(at: indexPath.row)` returns a single `CountryData` object. A `CountryData` isn't an `NSDictionary`, so doing a force-cast to `NSDictionary` will always fails. If you want a dictionary representation of your object you'll need to write code to create and populate one.

**Comment by siddharthsuneel** [comment]
@bdash I got your point but I want to have a generic method which can convert any kind of realm object to required dictionary. In order to create some kind of reusable component.

Like below code snippet converts CountryData to NSDictionary:
func toDictionary(countryData:CountryData) -> NSDictionary {
        let dict:NSDictionary = ["id":countryData.id, "name":countryData.name!, "countryCode":countryData.countryCode!, "servicesApplicable":countryData.servicesApplicable]
        return dict
    }

I am looking for something which can take any realm object as an argument & returns the desired dictionary.

**Comment by bdash** [comment]
There's no built-in functionality to provide what you're after. You should be able to implement it yourself by retrieving the [`ObjectSchema` from a given `Object`](https://realm.io/docs/swift/latest/api/Classes/Object.html#/s:vC10RealmSwift6Object12objectSchemaVS_12ObjectSchema), iterating its properties, and then using `value(forKeyPath:)` to retrieve each value by name.
