### ISSUE TITLE
Documentation needs to be updated for changes in Swift 4 (@objc)

### ISSUE THREAD

**Issue by dakeshi** [realm/realm-cocoa#5289]
In property attributes section,  it said that `@objc` attribute is mandatory to declare model property.
> Realm model properties must have the `@objc` dynamic var attribute to become accessors for the underlying database data

But the sample code for Realm Swift 2.10.0 documents still use `dynamic var` instead of `@objc dynamic var`. In realm-swift-2.10.0 examples, all of swift examples uses `@objc` for model property.

**Comment by bdash** [comment]
Thanks for the reminder, @dakeshi. The `@objc` attribute is becoming mandatory with Swift 4 so we preemptively updated our documentation to mention it. We've not yet released a final Swift 4 compatible release as there's no Xcode 9 GM build yet, but when we do we'll ensure that all of our documentation is compatible with Swift 4 as well.

**Comment by dakeshi** [comment]
> when we do we'll ensure that all of our documentation is compatible with Swift 4 as well.

Thanks. And it will be helpful for developers to mention this change one more in 2.10.0 blog posting like https://blog.realm.io/realm-objc-swift-2.9.

**Comment by bdash** [comment]
Done in realm/realm.io#3854.
