### ISSUE TITLE
would this SDK work on a Linux Swift server?

### ISSUE THREAD

**Issue by PierBover** [realm/realm-cocoa#5293]
I'd like to access the Realm server from a Swift server running Perfect or Vapor.

I was wondering if this SDK would work in a pure Swift runtime without Cocoa.

**Comment by bdash** [comment]
Not at present, no. Realm Swift is based on top of Realm Objective-C, and relies on many Objective-C runtime shenanigans for its functionality. We're tracking potential routes for supporting Swift on Linux in #3263.
