### ISSUE TITLE
How to add new column to old object with realm migrate swift?? plz

### ISSUE THREAD

**Issue by oaksoeshein** [realm/realm-cocoa#5294]
let config = Realm.Configuration(
    // Set the new schema version. This must be greater than the previously used
    // version (if you've never set a schema version before, the version is 0).
    schemaVersion: 1,
    
    // Set the block which will be called automatically when opening a Realm with
    // a schema version lower than the one set above
    migrationBlock: { migration, oldSchemaVersion in
        // We haven’t migrated anything yet, so oldSchemaVersion == 0
        if (oldSchemaVersion < 1) {
            migration.enumerateObjects(ofType: Config.className()) { oldObject, newObject in
                oldObject!["rent_slider_link"] = ""
            }
            // Nothing to do!
            // Realm will automatically detect new properties and removed properties
            // And will update the schema on disk automatically
        }
})

// Tell Realm to use this new configuration object for the default Realm
Realm.Configuration.defaultConfiguration = config

// Now that we've told Realm how to handle the schema change, opening the file
// will automatically perform the migration
let _ = try! Realm()

I got this error >>>> *******
Terminating app due to uncaught exception 'RLMException', reason: 'Invalid property name 'rent_slider_link' for class 'Config'.

**Comment by bdash** [comment]
To add a new property to an existing model class you need to do two things:
1. Add the property to the class declaration.
2. Increment the schema version in your Realm configuration, and provide an empty migration block.

If you wish to populate the new property you can provide logic in the migration block to do so. In your migration block, you should modify the _new_ object passed to the `enumerateObjects(ofType:)` callback. The old object provided to that callback represents the object at is existed prior to the schema being migrated, which means it doesn't have the newly added properties. This is why you're seeing a problem with your migration.

**Comment by lutluthfi** [comment]
> To add a new property to an existing model class you need to do two things:
> 
> 1. Add the property to the class declaration.
> 2. Increment the schema version in your Realm configuration, and provide an empty migration block.
> 
> If you wish to populate the new property you can provide logic in the migration block to do so. In your migration block, you should modify the _new_ object passed to the `enumerateObjects(ofType:)` callback. The old object provided to that callback represents the object at is existed prior to the schema being migrated, which means it doesn't have the newly added properties. This is why you're seeing a problem with your migration.

Hi, I was try with your answer and what I get is Realm wipe all my data. How about this?
