### ISSUE TITLE
How to add new column to old object with realm migrate swift?? I also use >>> https://realm.io/docs/swift/latest/#migrations

### ISSUE THREAD

**Issue by oaksoeshein** [realm/realm-cocoa#5295]
let config = Realm.Configuration(
                    schemaVersion: 1,
                    migrationBlock: { migration, oldSchemaVersion in
                        if (oldSchemaVersion < 1) {
                            migration.enumerateObjects(ofType: Config.className()) { oldObject, newObject in
                                oldObject!["rent_slider_link"] = ""
                            }
                        }
                })
                Realm.Configuration.defaultConfiguration = config

               let realm = try! Realm()

i get the error message >>> Terminating app due to uncaught exception 'RLMException', reason: 'Invalid property name 'rent_slider_link' for class 'Config'.'

**Comment by bdash** [comment]
You appear to have filed both this issue and #5294. We'll follow up in the other issue.
