### ISSUE TITLE
Getting a crash while creating a new Realm Object.

### ISSUE THREAD

**Issue by siddharthsuneel** [realm/realm-cocoa#5297]
## Goals
I was trying to create realm object using code: let realm = try! Realm()
It was working fine earlier, but don't know why it is throwing this error

## Expected Results
Expected was its object gets created without any error.

## Actual Results
getting this error: libc++abi.dylib: terminating with uncaught exception of type NSException
e.g. the stack trace of a crash
![stack trace of a crash](https://user-images.githubusercontent.com/15324076/30290330-98287f2a-974c-11e7-9806-005fa8ea860b.png)

Please refer to the attachment.

## Code Sample
Please refer to the attachment.
![code snippet](https://user-images.githubusercontent.com/15324076/30290234-41cd49ee-974c-11e7-8230-f65fa43db8f6.png)

Xcode version: 8.1

iOS/OSX version: ios-10.0.2/OSX-10..11.6

Dependency manager + version: dependency manager- cocoa pod version: 2.6.2

**Comment by bdash** [comment]
The screenshot you've provided of the stack trace omits the relevant stack frames between `+[RLMRealm sharedSchema]` and `__pthread_kill`. Instead of sharing a screenshot, can you please enter `bt all` in Xcode's LLDB console and share the output it produces?

**Comment by siddharthsuneel** [comment]
@bdash  I have made some changes & now it is crashing at this point:
![screen shot 2017-09-12 at 12 34 02 am](https://user-images.githubusercontent.com/15324076/30292036-3ced6d4a-9752-11e7-8a42-c1ecf16b703d.png)


As you asked, I have run the command `bt all` & it is showing a lot of debugging output.Should I post them also ?

**Comment by bdash** [comment]
It seems likely that the error message from the exception shown in your screen shot describes the underlying cause of your problem, namely that you have a property declared in one of your model classes that is not of a supported type. The error message of the exception that's thrown should tell you the name of the property and the unsupported property type.

**Comment by siddharthsuneel** [comment]
@bdash Got it, thanks for your help. It is fixed now
