### ISSUE TITLE
Calling Realm.asyncOpen always fails with “Operation Cancelled”

### ISSUE THREAD

**Issue by geraldeersteling** [realm/realm-cocoa#5298]
## Goals
I want to async open a realm after logging in with a `SyncUser`.

## Expected Results
That the realm would be opened.

## Actual Results
The call to open a realm came back didn't succeed in opening the realm. Instead came back with an error: `Error Domain=io.realm.sync Code=4 "Operation canceled" UserInfo={NSLocalizedDescription=Operation canceled, statusCode=89}`

## Steps to Reproduce
Opening a realm using `Realm.asyncOpen`.

## Code Sample
```swift

/// Logs in a user with info provided earlier (credentials and server URL)
/// if completed, the `user` property should contain a valid `SyncUser`
func login(_ subscriber: Observer<Void, RealmUserError>? = nil) {
        user?.logOut()
        
        if let subscriber = subscriber {
            syncStateSignal.observe(subscriber)
        }
        SyncUser.logIn(with: credentials,
                       server: AppConfig.Network.RealmPlatform.webAddress) { (user, error) in
                        
                        guard
                            let user = user,
                            error == nil
                        else {
                            self.syncStateObserver.send(error: .loginFailed(reason: error))
                            return
                        }
                        self.user = user
                        
                        self.syncStateObserver.sendCompleted()
        }
    }
    
/// Connects the `user` to the realm at `realmURL`, provided `user` is valid
    func connectToRealm(_ realmURL: URL,
                        onConfigured:((RealmUserError?) -> Void)? = nil) {
        guard let user = user
        else {
            onConfigured?(.noRealmUserConfigured)
            return
        }
        guard user.state == .active
        else {
            let error: RealmUserError = user.state == .loggedOut ? .syncedUserLoggedOut : .syncedUserIsInvalid
            onConfigured?(error)
            return
        }
        
        let config = Realm.Configuration(syncConfiguration: SyncConfiguration(user: user,
                                                                              realmURL: realmURL))
        storage = RealmStorage(config)
        storage.configure { (error) in // <-- the configure function is explained below
            guard error == nil
            else {
                onConfigured?(.connectingToRealmFailed(reason: error))
                return
            }
            onConfigured?(nil)
        }
    }


/*
    The storage's `configure` function (resides in another class)
*/
func configure(_ done: ((_ error: NSError?) -> Void)? = nil) {
        Realm.asyncOpen(configuration: config,
                        callbackQueue: DispatchQueue.main) { (realm, error) in
                            if let error = error {
                                print(error)
                                done?(error as NSError)
                                return
                            }
                            self.realm = realm
                            done?(nil)
        }
    }
```

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

/Applications/Xcode.app/Contents/Developer
Xcode 8.3.3
Build version 8E3004b

/usr/local/bin/pod
1.2.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)


(not in use here)

/usr/bin/git
git version 2.11.0 (Apple Git-81)

Realm framework version: (after `pod repo update` and `pod install`)
Using Realm (2.7.0)
Using RealmSwift (2.7.0)

Realm Object Server version: 1.8.2
```

> Before opening this issue I also asked the question [on StackOverflow](https://stackoverflow.com/questions/45896331/calling-realm-asyncopen-always-fails-with-operation-cancelled)

**Comment by austinzheng** [comment]
Thanks for reaching out, and apologies for the delay.

I noted in the code sample that you create your sync configuration with `tableUser`, which is never assigned a value. Did you mean to use `user` or `self.user` instead? (Also, `SyncUser.logIn()` doesn't return a `SyncUser` synchronously, so assigning the result of it won't do anything meaningful.) Can you try fixing that and seeing if the issue persists?

**Comment by geraldeersteling** [comment]
No worries, any help is already appreciated.

The `SyncConfiguration` should be made with `user` instead. A copy/paste error. I adjusted my code to make the code snippet a bit smaller, but made some errors along the way.

I'll update the snippet.

**Comment by geraldeersteling** [comment]
Alright @austinzheng I updated the code snippet. 
The issue is located at the `configure` method in my 'storage' class, it worked before but suddenly just stopped working.

**Comment by geraldeersteling** [comment]
Ok so I dug a little further; it _might_ be the ROS which is acting up.
After trying to create a Realm, the server's log state the following (I've hidden some tokens and hashes...don't know if they should be kept private):

```
2017-09-18T18:52:59.472Z - info: sync: Sync Connection[5]: Connection closed by client: End of input
2017-09-18T18:52:59.581Z - info: sync: HTTP Connection[9]: Connection from 127.0.0.1:60230
2017-09-18T18:52:59.595Z - info: sync: HTTP Connection[9]: Received: Sync HTTP request(protocol_version=18)
2017-09-18T18:52:59.633Z - info: sync: Sync Connection[9]: Session[2]: Session initiated (session_ident=2).
2017-09-18T18:52:59.635Z - info: sync: Sync Connection[9]: Session[2]: Received: BIND(server_path=/HIDDEN_HASH/tafel_1, signed_user_token='...+HIDDEN_TOKEN==', need_file_ident_pair=0)
2017-09-18T18:52:59.718Z - info: sync: Sync Connection[9]: Session[2]: Received: IDENT(server_file_ident=1, client_file_ident=2, client_file_ident_secret=HIDDEN_SECRET, scan_server_version=1, scan_client_version=4, latest_server_version=1, latest_server_session_ident=HIDDEN_SOME_HASH)
2017-09-18T18:52:59.719Z - error: sync: Sync Connection[9]: Session[2]: Bad client file ident (client_file_ident=2,  client_file_ident_secret=HIDDEN_SECRET).
2017-09-18T18:52:59.719Z - info: sync: Sync Connection[9]: Session[2]: Session terminated (session_ident=2).
2017-09-18T18:52:59.720Z - info: sync: Sync Connection[9]: Sending: ERROR(error_code=208, message_size=34, try_again=0, session_ident=2)
2017-09-18T18:52:59.723Z - info: sync: Sync Connection[9]: Connection closed by client: End of input
```
I've got no clue which is the culprit now: the ROS or my iPhone...

**Comment by bdash** [comment]
`Bad client file ident` indicates that the "identity" of the client's copy of the synced Realm file doesn't match the identity of the Realm on the server. Uninstalling and reinstalling your app on the device should clear out the client's synced Realm file and pull down the server's copy, and should result in the error going away.

As to why you're seeing the error in the first place… This error typically only appears if you manually delete Realms from the server without also resetting the state on the client. This results in the Realm being recreated on the server with a new identity that no longer matches the identity of the older file that the client has. Does this sound like something you may have done?

**Comment by geraldeersteling** [comment]
@bdash Thanks for reaching out, your explanation makes sense. 
I might have done that while testing out some things. Sadly I'm not able to try it out till Saturday, but I think re-installing should help!

In any case; what's the best practice if you delete the realm on the server? You mentioned resetting the state of the client, could you elaborate?

**Comment by austinzheng** [comment]
Apologies for the delayed response.

If you want to delete a Realm on the server, your application code needs to handle "client reset" errors. The Swift and Objective-C bindings provide APIs to properly handle a client reset. You can read more about this topic [in our documentation](https://realm.io/docs/objc/latest/#client-reset).
