### ISSUE TITLE
Retrieve a List of Objects From Realm - returns a nil even though the list is not empty

### ISSUE THREAD

**Issue by tinenerio** [realm/realm-cocoa#5300]
`<!---`

**Questions**: If you have questions about how to use Realm, ask on
[StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
We monitor the `realm` tag.

**Feature Request**: Just fill in the first two sections below.

**Bugs**: To help you as fast as possible with an issue please describe your issue
and the steps you have taken to reproduce it in as many details as possible.

-->

## Goals
 Retrieve a List of Objects from Realm

## Expected Results
 The List will be displayed

## Actual Results
 The List of Objects is nil even though the list is not empty

## Code Sample

`print("Data: \(data)")`

Output:

`availability = Immediately;
		user_id = 599ce9fb0083f2ac403cf8eb;
		industries = RLMArray <0x6000002e1a00> (
			[0] MultiIndustryPositionObject {
				industry = IndustryObject {
					updated_at = 2017-09-12 07:38:00 +0000;
					created_at = 2017-09-12 07:38:00 +0000;
					deleted_at = 2017-09-12 07:38:00 +0000;
					deleted = 2017-09-12 07:38:00 +0000;
					id = 1;
					name = Accounting;
				};
				positions = RLMArray <0x6000002ecc00> (
					[0] <Maximum depth exceeded>,
					[1] <Maximum depth exceeded>
				);
			}
		);
`

but when I want to retrieve "industries" by doing:

`print("Industries: \(data?.industries)")` ---> this will return NIL

but when I try to access the "availability" property:

`print("Availability: \(data?.availability)")` ---> this will output: Optional("Immediately")

## Version of Realm and Tooling

Realm framework version: 2.10.0

Realm Object Server version: ?

Xcode version: 8.2

iOS/OSX version: macOS Sierra Version 10.12.2 

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. Can you post the definitions of your model objects and the code you're using to build and print out `data`? Even better would be a reproduction case that we can run.

**Comment by kishikawakatsumi** [comment]
Closing due to no response
