### ISSUE TITLE
Some issues about one to many relation

### ISSUE THREAD

**Issue by FrankSwift** [realm/realm-cocoa#5301]
For Example:One person have many dogs, one dog only have one person. 
According to the official document
The code will be：
```objc
@interface FWDog : RLMObject
@property NSString *dogId;
@property NSString *name;
@end
RLM_ARRAY_TYPE(FWDog);

@interface FWPerson : RLMObject
@property NSString *personId;
@property RLMArray<FWDog *><FWDog> *dogs;
@end
```

But, this is different from my understanding about the database.

For my way：
```objc
@interface FWDog : RLMObject
@property NSString *dogId;
@property NSString *name;
@property NSString *personId;
@end

@interface FWPerson : RLMObject
@property NSString *personId;
@end
```

I don't understand why the official practice to be like this

**Comment by bdash** [comment]
Realm supports storing relationships between objects directly, either as a to-one relationship using a property whose type is an `RLMObject` subclass, or as a to-many relationship using `RLMArray`. It's not necessary or desirable to simulate relationships using object identifiers as you suggest. See our documentation on [Relationships](https://realm.io/docs/objc/latest/#relationships) for more information.

**Comment by FrankSwift** [comment]
Thank you very much !

**Comment by bdash** [comment]
Is there a reason you reopened this?
