### ISSUE TITLE
Realm DataBase throws at runtime 

### ISSUE THREAD

**Issue by Gtwatt1** [realm/realm-cocoa#5312]
i have been using realm very fine for my iOS App in Xcode 8.3. i downloaded Xcode 9 and i opened my code in  Xcode 9, it compiled and run very well.

 but suddenly  my app  began to breaks at the initialization of Realm using the "realm = try! Realm". i debugged and found out that realm was throwing from Rlmschema.mm class at  the block code.

      `try {
            // Make sure we've discovered all classes
            {
                unsigned int numClasses;
                using malloc_ptr = std::unique_ptr<__unsafe_unretained Class[], decltype(&free)>;
                malloc_ptr classes(objc_copyClassList(&numClasses), &free);
                RLMRegisterClassLocalNames(classes.get(), numClasses);
            }
           [s_localNameToClass enumerateKeysAndObjectsUsingBlock:^(NSString *, Class cls, BOOL *) {
                RLMRegisterClass(cls);
            }];
        }
        catch (...) {
            s_sharedSchemaState = SharedSchemaState::Uninitialized;
            throw;
        }`

I am so  confused now and i don't have a clue what to do..

**Comment by Gtwatt1** [comment]
i have been able to fix it, i changed my primary Id but didn't change it in the realm primary id setter. Xcode wasn't turning out any error while debugging on a real device but i ran it on a simulator and the error showed itself.

Thanks for the great Pod

**Comment by snievesZafiro** [comment]
Hi @burkarddev 
I have the same bug
Did you find any solution?
