### ISSUE TITLE
version 2.10.1 doesn't appear to be Swift 4.0 compatible

### ISSUE THREAD

**Issue by ryanbaldwin** [realm/realm-cocoa#5314]
## Goals
Use Realm 2.10.1 in a Swift 4 project, via Carthage

## Expected Results
For carthage to pull down and install v2.10.1 

## Actual Results
Received incompatible swift version clang error in carthage

## Steps to Reproduce
1. Added `GitHub "realm/realm-cocoa" == 2.10.1`
2. Tried a `carthage update --platform iOS`

The following output was produced (note: at the time of this writing my `carthage update` is still going as it's building the `Realm.xcworkspace` as a backup to the binaries)

    *** Fetching realm-cocoa
    *** Downloading realm-cocoa.framework binary at "v2.10.1"
    *** Checking out fhir-parser at "70f814c190a06c0d37baf08a850f0399f0888bde"
    *** Skipped installing realm-cocoa.framework binary due to the error:
    	"Incompatible Swift version - framework was built with swiftlang-802.0.53 clang-802.0.42 and the local version is swiftlang-900.0.65 clang-900.0.37."
    *** Checking out realm-cocoa at "v2.10.1"
    *** xcodebuild output can be found in /var/folders/dl/9jnz4rmn5zj2kp49gfn7158w0000gp/T/carthage-xcodebuild.077kAk.log
    *** Building scheme "Realm" in Realm.xcworkspace

Xcode version: Xcode9 GM (9A235)

Dependency manager + version: Carthage v0.24.0

**Comment by bdash** [comment]
With Carthage it is only possible for us to publish prebuilt binaries for a single Swift version, which for Realm v2.10.1 is currently Swift 3.1. When using Carthage with a different Swift version, it will detect the incompatibility and automatically fall back to building from source. This is the expected and correct behavior, and is what the output you provided indicates is happening.

**Comment by ryanbaldwin** [comment]
Ah, of course. That makes sense. I was under the impression now that Xcode 9GM is out, and the release notes for v2.10.1 that the carthage binaries would also be 3.2+. Makes sense though.

What's Realm's plan for cutting Carthage binaries over to Swift 3.2+? 

For now I'll download the actual release binary and manually bring those in.

**Comment by bdash** [comment]
Our approach to the prebuilt binaries for Carthage is to target the version of Xcode that the majority of our users are using, as in theory that will save our users the most amount of time.

**Comment by icanswiftabit** [comment]
Since Xcode 9 is out will you prebuild Realm for Swift 3.2/4.0?

**Comment by bdash** [comment]
See my comments above.

**Comment by rjouvet** [comment]
So if my understanding is correct, there will be a build for Swift 4 later when the number of user using it will be big enough?

**Comment by bdash** [comment]
It is not necessary or possible for us to provide prebuilt binaries for Carthage for more than one Swift version. With Carthage it is only possible for us to publish prebuilt binaries for a single Swift version, which for Realm v2.x is currently Swift 3.1. When using Carthage with a different Swift version, it will detect the incompatibility and automatically fall back to building from source. At some point in the future we will switch the prebuilt binaries to Swift 4, but until then Carthage will continue to do the right thing for all Xcode / Swift versions.

**Comment by glennmd** [comment]
If Realm wants to be the "BEST" DB solution for IOS it best service the developers and Apple users with all the update compatible versions for Swift and Xcode. If not then they should stop bragging that they are the best DB solution for iOS. Takes work to be the best!

**Comment by austinzheng** [comment]
If you review the comments posted prior to yours, you can note firstly that the "problem" the user was seeing is a limitation intrinsic to the Carthage utility, something unfortunately out of our control, and secondly that there was no problem at all; Carthage displayed a slightly confusing error message and built the dependency from source as it was designed to do. If you have a legitimate issue please feel free to create a ticket, and thank you for using Realm!
