### ISSUE TITLE
Missing .hpp file !

### ISSUE THREAD

**Issue by xeonarno** [realm/realm-cocoa#5316]
## Expected Results
Correct install in project

## Actual Results
#include "impl/primitive_list_notifier.hpp" missing ! 

## Steps to Reproduce
install RealmSwift with cocoapod

## Version of Realm and Tooling
Realm framework version: RealmSwift (2.10.1)
Realm Object Server version: N.A.
Xcode version: 8.2.1
iOS/OSX version: iOS 9.0
Dependency manager + version: cocoapods 1.3.1

**Comment by bdash** [comment]
It sounds like CocoaPods somehow failed to check out the object store submodule that provides `primitive_list_notifier.hpp`. I'd recommend following the [steps for reintegrating CocoaPods into your app](https://realm.io/docs/swift/latest/#dependency-managers):

```sh
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
```

If you still see problems, please share the output of `pod install --verbose`, the relevant section of your `Podfile`, and the complete compiler output including the error.

**Comment by xeonarno** [comment]
It's kind of violent solution :)  but it works well !
