### ISSUE TITLE
Filtering with the IN operator using an empty array throws an exception in Realm 2.0.4+

### ISSUE THREAD

**Issue by mcontin** [realm/realm-cocoa#5317]
## Goals
Filter Results with the IN operator using an array which might be empty.

## Expected Results
The Results object should be filtered even if the array is empty.

## Actual Results
The following exception is thrown:
Terminating app due to uncaught exception 'Invalid value', reason: 'IN clause requires an array of items'

## Steps to Reproduce
Use a predicate like the following:
`let predicate = NSPredicate(format: "NOT (id IN %@)", arrayOfIDs)`

## Code Sample
```
// arrayOfIDs might or might not be empty 
let predicate = NSPredicate(format: "NOT (id IN %@)", arrayOfIDs)
let something = someResults.filter(predicate)
```

## Version of Realm and Tooling
Realm framework version: working in 2.0.1, crashes in 2.0.4 and 2.10

Realm Object Server version: not used

Xcode version: XCode 8.2.1 with Swift 2.3 and Realm 2.0.1, XCode 8.3.3 with Swift 3 and Realm 2.0.4/2.10

iOS version: iOS 10

Dependency manager + version: Cocoapods, latest

I am aware of an identical ticket [here](https://github.com/realm/realm-java/issues/4011) in the Java version but I couldn't find any mention about the Cocoa one.

**Comment by kishikawakatsumi** [comment]
@mcontin It should work if you pass an empty array to the `IN` operator. But I could not reproduce the exception in Realm 2.10. To be exact, the exception occurs when `arrayOfIDs` does not conform to the` NSFastEnumeration` protocol. That is, I guess that the variable is not an empty array but a different object. Could you please provide a sample project that reproduces the problem if possible? Or please provide more information, such as what is `arrayOfIDs`?, what is the type of `id`?, or model definitions of `someResults`? You can send the project to `help@realm.io` Thanks!

**Comment by mcontin** [comment]
Hello, at the moment I am not able to reproduce the bug myself and I have no idea why, this problem bugged me for days, I tried different versions of XCode, Swift and Realm and now it's simply gone. I will investigate further and try to find out what was going on on my code. Sorry for the useless ticket.
