### ISSUE TITLE
Realm 0.102.1 failing in jenkins

### ISSUE THREAD

**Issue by KiranMantana** [realm/realm-cocoa#5318]
We are getting a issue in Realm when running pods, 

Installing Realm (0.102.1)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.100.4
mv: rename core to core-0.100.4/core: Directory not empty

Tried a your suggested solution: 

pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData

But still facing the same issue. 

 Running prepare command

   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: core 0.100.4
   mv: rename core to core-0.100.4/core: Directory not empty
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.100.4
mv: rename core to core-0.100.4/core: Directory not empty

/Users/administrator/Software/ruby/gems/cocoapods-1.2.1/lib/cocoapods/executable.rb:69:in `execute_command'

It used to work well earlier, but got this issue suddenly.

**Comment by bdash** [comment]
v0.102.1 was released nearly 18 months ago. We cannot provide support for such an old version. I’d strongly recommend updating to our latest release, currently v2.10.1.
