### ISSUE TITLE
Ambiguous use of 'filter' when filter the `List<T>`

### ISSUE THREAD

**Issue by icanswiftabit** [realm/realm-cocoa#5319]
## Goals

The first element of `List<T>` with given are requirement

## Expected Results
First element

## Actual Results

Compile error: Ambiguous use of 'filter'

## Code Sample

Let say I have such object
```swift
class Car: Object {
    let similarCars = List<Car>() 
}

let car = Car()
// similarCars are not empty
let talkWithThisId = car.similarCars.filter { $0.color == color }.first // Ambiguous use of 'filter'
```

This code worked just fine on swift 3.1/3.2

## Version of Realm and Tooling

Realm framework version:  2.10.1

Xcode version:  Xcode 9 GM, Swift 4

Dependency manager + version: Carthage 0.25.0

**Comment by kishikawakatsumi** [comment]
@icanswiftabit It seems probably Swift compiler issue. We will find the way to avoid it, in the meanwhile, the workaround is split it into two sentences using a temporaly variable instead method chain like the following.

```
let cars = car.similarCars.filter { $0.color == color }
let car = cars.first
```

**Comment by icanswiftabit** [comment]
Update: Xcode 9 and still same issue

**Comment by chrisaljoudi** [comment]
Here’s the relevant bug on bugs.swift.org:

https://bugs.swift.org/browse/SR-1996

**Comment by stefanomondino** [comment]
have you tried to wrap the filter closure with round parentheses?
```
 car.similarCars.filter ({ $0.color == color }).first
```
it usually works form me when I use the `guard let` statement.
