### ISSUE TITLE
How to encrypt existing realm database?

### ISSUE THREAD

**Issue by mohitaddval** [realm/realm-cocoa#5320]
Hi,

I am trying the encrypt the exisiting realm database with the code below:

    NSURL *path = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject];
    path = [path URLByAppendingPathComponent:@"RealmEncryptedPath"];
    [[RLMRealm realmWithConfiguration:config error:nil] writeCopyToURL:path encryptionKey:[self getKey] error:nil];

Crashing at the moment. Can somebody please help me with this.

Thanks

**Comment by kishikawakatsumi** [comment]
@mohitaddval Please provide all of the information requested in the [new issue template](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues).

@mohitaddval Your code snippet should only work if the Realm file exists in the default file path. What is an exception thrown? What error message is displayed? Could you provide a reproducible sample project?

**Comment by mohitaddval** [comment]
@kishikawakatsumi thanks for the support. I got that to work. I have to make a copy of existing non encrypted realm first and provide the file path to configuration.
