### ISSUE TITLE
App crashes while launching

### ISSUE THREAD

**Issue by prajyot133** [realm/realm-cocoa#5323]
## Goals
Launch the app properly

## Expected Results
To launch properly without crash

## Actual Results

It is crashing on the iPhone 5 simulator while launching

> Terminating app due to uncaught exception 'RLMException', reason: 'Object cannot be inserted unless the schema is initialized. This can happen if you try to insert objects into a RLMArray / List from a default value or from an overriden unmanaged initializer (`init()`).'
*** First throw call stack:
(
	0   CoreFoundation                      0x05c73ded __exceptionPreprocess + 189
	1   libobjc.A.dylib                     0x05223d6f objc_exception_throw + 49
	2   Realm                               0x021712d2 _ZL29RLMValidateMatchingObjectTypeP8RLMArrayP9RLMObject + 242
	3   Realm                               0x021716d5 -[RLMArray insertObject:atIndex:] + 85
	4   Realm                               0x02170123 -[RLMArray addObject:] + 131
	5   RealmSwift                          0x02b80c58 _TFC10RealmSwift4List6appendfxT_ + 168
	6   MyApp                             0x005a71ae _TFC7MyApp5Habits16isCompletedTodaySb + 110
	7   MyApp                             0x005a711f _TToFC7MyApp5Habits16isCompletedTodaySb + 63
	8   Foundation                          0x04db27c1 _NSSetCharValueForKeyWithMethod + 87
	9   Foundation                          0x04da7f59 _NSSetUsingKeyValueSetter + 125
	10  Foundation                          0x04da7af8 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 279
	11  Realm                               0x021c918d -[RLMProperty initSwiftPropertyWithName:indexed:linkPropertyDescriptor:property:instance:] + 2253
	12  Realm                               0x021aa04d +[RLMObjectSchema propertiesForClass:isSwift:] + 1837
	13  Realm                               0x021a7c36 +[RLMObjectSchema schemaForObjectClass:] + 1030
	14  Realm                               0x022ec023 _ZL16RLMRegisterClassP10objc_class + 307
	15  Realm                               0x022ed2b4 __25+[RLMSchema sharedSchema]_block_invoke + 84
	16  CoreFoundation                      0x05bfb902 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
	17  CoreFoundation                      0x05bfb80b -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 187
	18  CoreFoundation                      0x05bfb243 -[NSDictionary enumerateKeysAndObjectsUsingBlock:] + 35
	19  Realm                               0x022ecf9c +[RLMSchema sharedSchema] + 892
	20  Realm                               0x022cc001 +[RLMRealm realmWithConfiguration:error:] + 5409
	21  RealmSwift                          0x02b943c6 _TTOFCSo8RLMRealmCfzT13configurationCSo21RLMRealmConfiguration_S_ + 166
	22  RealmSwift                          0x02b941fd _TFC10RealmSwift5RealmcfzT_S0_ + 125
	23  RealmSwift                          0x02b942d6 _TFC10RealmSwift5RealmCfzT_S0_ + 54
	24  MyApp                             0x002ca899 _TZFC7MyApp19FALocalDatabaseUtil21storeEquipmentToRealmfT_T_ + 57
	25  MyApp                             0x00218afa _TFC7MyApp11AppDelegate15loadDefaultDatafT_T_ + 26
	26  MyApp                             0x00218a8a _TFC7MyApp11AppDelegate8loadDatafT_T_ + 26
	27  MyApp                             0x002139b7 _TFC7MyApp11AppDelegate11applicationfTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVs10DictionaryVSC29UIApplicationLaunchOptionsKeyP____Sb + 311
	28  MyApp                             0x00213b87 _TToFC7MyApp11AppDelegate11applicationfTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVs10DictionaryVSC29UIApplicationLaunchOptionsKeyP____Sb + 199
	29  UIKit                               0x0311347f -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 299
	30  UIKit                               0x03114fce -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4702
	31  UIKit                               0x0311bd07 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1828
	32  UIKit                               0x0313cd5e __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke.3147 + 50
	33  UIKit                               0x03118ace -[UIApplication workspaceDidEndTransaction:] + 160
	34  FrontBoardServices                  0x0ccd9590 __37-[FBSWorkspace clientEndTransaction:]_block_invoke_2 + 59
	35  FrontBoardServices                  0x0ccd90b9 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 46
	36  FrontBoardServices                  0x0cd01635 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 23
	37  FrontBoardServices                  0x0cd01499 -[FBSSerialQueue _performNext] + 168
	38  FrontBoardServices                  0x0cd0186e -[FBSSerialQueue _performNextFromRunLoopSource] + 52
	39  FrontBoardServices                  0x0cd00cb5 FBSSerialQueueRunLoopSourceHandler + 29
	40  CoreFoundation                      0x05c18a5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	41  CoreFoundation                      0x05bfe1c4 __CFRunLoopDoSources0 + 500
	42  CoreFoundation                      0x05bfd69c __CFRunLoopRun + 1084
	43  CoreFoundation                      0x05bfcfd4 CFRunLoopRunSpecific + 372
	44  CoreFoundation                      0x05bfce4b CFRunLoopRunInMode + 123
	45  UIKit                               0x031171e6 -[UIApplication _run] + 488
	46  UIKit                               0x0311dcb9 UIApplicationMain + 148
	47  MyApp                             0x00236cbb main + 75
	48  libdyld.dylib                       0x07e6a779 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

## Steps to Reproduce
I can run it on other simulators except the iPhone 5, it is crashing with the above crash log. Ran on devices and the same story. Don't know what exactly is the problem here.
According to the crash log, it is crashing on the `isCompletedToday` setter for a `Habit` object, FYI.

## Code Sample
`class Habit: Object {
    
    dynamic var id = 0
    dynamic var type: String!
    dynamic var name: String!
    dynamic var detail: String!
    dynamic var creationDate = Foundation.Date()
    dynamic var uuid = UUID().uuidString
    dynamic var isExpanded = false
    let datesDone = List<HabitDate>()
    
    convenience required init(id habitID: Int, type habitType : String,name habitName: String, detail habitDetail: String ) {
        self.init()
        self.id = habitID
        self.type = habitType
        self.name = habitName
        self.detail = habitDetail
    }
    
    var isCompletedToday: Bool {
        get {
            if let lastCompletedDate = self.datesDone.last {
                return Calendar.current.isDateInToday(lastCompletedDate.date)
                
            } else {
                // There is no date in the "datesDone" list
                return false
            }
        }
        set {
            if newValue {
                // Check if the date is already present, otherwise add the date to datesDone list
                if !isCompletedToday {
                    
                    // If it is not completed today, add the todays date to the datesDone list
                    self.datesDone.append(HabitDate())
                    
                } else {
                    
                    // If it is already completed today, then don't add the today's date again to the "datesDone" list
                    // i.e DO NOTHING
                    
                }
            } else {
                
                // Check if the today's date is present in the "datesDone" list
                if isCompletedToday {
                    
                    // Remove the last date from "datesDone" list
                    self.datesDone.removeLast()
                    
                } else {
                    
                    // It is not completed today, then don't remove the last date from "datesDone" list
                    // i.r DO NOTHING
                }
                
            }
        }
    }
    
    
    var wasCompletedYesterday: Bool {
        get {
            
            if let lastCompletedDate = self.datesDone.last {
                if Calendar.current.isDateInToday(lastCompletedDate.date) {
                    
                    if self.datesDone.count > 1 {
                        
                        let secondLastCompletedDate = self.datesDone[self.datesDone.count - 2]
                        
                        return Calendar.current.isDateInYesterday(secondLastCompletedDate.date)
                        
                    } else {
                        
                        return false
                    }
                    
                } else {
                    
                    if Calendar.current.isDateInYesterday(lastCompletedDate.date) {
                        
                        return true
                        
                    } else {
                        
                        return false
                        
                    }
                    
                }
                
            } else {
                // There is no date in the "datesDone" list
                return false
            }
            
        }
        
    }
}

class HabitDate: Object {
    dynamic var date = Foundation.Date()
}`

## Version of Realm and Tooling
Realm framework version:
I was using old Realm version first (1.1)
Updated to 2.10.1 to see if problem is fixed, but it still crashes

Xcode version:
8.3.2

iOS/OSX version:
macOS 10.12.6

**Comment by kishikawakatsumi** [comment]
@prajyot133 Thanks for reporting. This is a limitation of Realm. When instantiating Realm for the first time, Realm enumerates the subclasses of `Object` and retrieve the property definitions to initialize data schema. At that time, if Realm found `Bool` or `Int` properties on 32-bit devices, Realm assigns actual value `2` to inspect whether `Bool` or `Int`. Since `Bool` and `Int` cannot be distinguished from each other on a 32-bit device. `isCompletedToday` is the case.

So `isCompletedToday` is a computed property, the setter code runs when the value is assigned. At that time, the object is added to `datesDone`.

```
var isCompletedToday: Bool {
    get {
        ...
    }
    set {
        if newValue {
            // Check if the date is already present, otherwise add the date to datesDone list
            if !isCompletedToday {
                // If it is not completed today, add the todays date to the datesDone list
                self.datesDone.append(HabitDate())
            } else {
            ...
```

Realm doesn't allow to create an object while initializing the schema. This is the cause of the exception.

To solve this problem, exclude `isCompletedToday` (probably ` wasCompletedYesterday` too) from Realm's schema as to be ignored properties. Like the following:

```
...
    override class func ignoredProperties() -> [String] {
        return ["isCompletedToday", "wasCompletedYesterday"]
    }
...
```

**Comment by prajyot133** [comment]
@kishikawakatsumi Hey many thanks for looking into the issue and replying, I appreciate it. Thanks for your insight on what's going wrong here. So by making these two properties as `ignoredProperties`, how will it affect the functionality of the app? Can you please tell?
Also, will this bug be resolved in future updates of Realm?

**Comment by austinzheng** [comment]
If a property is specified in `ignoredProperties`, it won't be stored in the database. It is always safe to mark computed properties as ignored, since by definition their values are calculated on the fly and not saved or loaded.

Our recently released version of Realm, 3.0.0, is smarter about knowing which properties to ignore automatically (including computed properties), so you may want to try it out and see if it fixes your issue.

**Comment by prajyot133** [comment]
@austinzheng Thanks for the info and the tip. I will surely try the new version.

**Comment by mohsinka** [comment]
This issue is happening again for 32 bit devices for Realm 4.1.1

**Comment by bmunkholm** [comment]
@mohsinka Please create a new issue with all details.
