### ISSUE TITLE
Property names beginning with 'new' are not supported

### ISSUE THREAD

**Issue by Raghvendra7** [realm/realm-cocoa#5325]
Terminating app due to uncaught exception 'RLMException', reason: 'Property names beginning with 'new' are not supported. Swift follows ARC's ownership rules for methods based on their name, which results in memory leaks when accessing properties which return retained values via KVC.

```
open class AccessTokenObject :Object{
   public  dynamic var organizationId:String = ""
     public dynamic var token:String = ""
    public  dynamic var userId:String = ""
   public dynamic var organizationName:String = ""
   public dynamic var expires  = 0
   public dynamic var userName:String = ""
   public dynamic var orgFeatures:String = ""
     
    //dynamic var primeKey :String?
    //Impl. of Mappable protocol
    
   override open static func primaryKey() -> String? {
        return "organizationId"
    }

  }
    
```
## Version of Realm and Tooling

Realm framework version: 2.10.1

Xcode version: 9.0

iOS/OSX version: 11.0

**Comment by Raghvendra7** [comment]
I also tried with
 public  dynamic var organizationId:String? = nil Still not working

**Comment by kishikawakatsumi** [comment]
@Raghvendra7 Properties cannot be named starting with 'new'. It is because of it violates with Swift's ARC rule. There seems to be no property starting with 'new' in this model, but is it defined in other models?

**Comment by Raghvendra7** [comment]
@kishikawakatsumi thanks
