### ISSUE TITLE
Perform Batch Updates in Swift 4 Crashes When Updated

### ISSUE THREAD

**Issue by DavidOliverDoswell** [realm/realm-cocoa#5329]
## Goals

Perform Batch Updates API in CollectionView without crashing

## Expected Results

Success

## Actual Results

`Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (8) must be equal to the number of items contained in that section before the update (8), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).`

## Steps to Reproduce

1.) Create a instance of Realm `Results<T>` like `var item : Results<T>?`
2.) Create a `addNotification` block in `viewDidLoad`
3.) Call `performBatchUpdates(_:)` with deletions, insertions & modifications params in `viewDidLoad`
4.) Call `items.count` in collectionView like `guard let items = items?.count else { return }`

`return items`

Also followed [this](https://github.com/realm/realm-cocoa/issues/4186) and several other tickets. Not sure if the merge from last year was modified or is a bug when converting to Swift 4.

## Code Sample

    // Set up realm
    var realm : Realm!
    
    var items : Results<Article>?
    
    var notificationToken: NotificationToken!`

    private func setUpRealm() {
        DispatchQueue.main.async {
            
            // Acknowledge the user and access the realm on the main thread
            self.realm = try! Realm(configuration: exampleConfig(user: SyncUser.current!))
            
            self.items = self.realm.objects(Article.self).sorted(byKeyPath: "created", ascending: false)
            
            // Observe notifications and update the UI when the underlying data has been changed
            self.notificationToken = self.items?.addNotificationBlock { [weak self] (changes: RealmCollectionChange) in
                
                guard (self?.collectionView) != nil else { return }
                
                switch changes {
                case .initial:
                    self?.collectionView.reloadData()
                    break
                    
                case .update(_, let deletions, let insertions, let modifications):
                    self?.collectionView.performBatchUpdates({
                        self?.collectionView.deleteItems(at: deletions.map({ IndexPath(row: $0, section: 0)}))
                        self?.collectionView.insertItems(at: insertions.map({ IndexPath(row: $0, section: 0)}))
                        self?.collectionView.reloadItems(at: modifications.map({ IndexPath(row: $0, section: 0)}))
                        
                    }, completion: nil)
                    break
                    
                case .error(let error):
                    print(error.localizedDescription)
                    break
                }
            }
        }
    }

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        guard let items = items?.count  else { return 0 }
            return items
    }

## Version of Realm and Tooling

Realm framework version: ?

Realm Swift 2.10.1

Realm Object Server version: ?

RMP Release 1.8.3

Xcode version: ?

Xcode 9

iOS/OSX version: ?

iOS 11

Dependency manager + version: ?

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods.rb

**Comment by kishikawakatsumi** [comment]
We are trying to reproduce the problem with a code similar to the code snippet that you indicated, but we can not reproduce it yet.

Could you please share a reproducible sample project, or more information such like model  definitions and the actual data when an error occurs?

Thank you for reporting.

**Comment by DavidOliverDoswell** [comment]
Yes. My model definitions are as follows

    final class Item: Object {
    @objc dynamic var username =  String()
    @objc dynamic var title =  String()
    @objc dynamic var text =  String()
    @objc dynamic var place =  String()
    @objc dynamic var favorite = Int()
    @objc dynamic var created = Date()
    }

**NOTE** I can send either a sample project or my own project to `help@realm.io` I believe with discretion? Need to finish work here and can have it over by late tonight (EST) if nothing below makes sense:

The actual data is the above error. I have two view controllers, call them `First View` and `Second View`, unlike with the Realm Tasks Sample project. One view is for reading and the other for posting.  

I am able to successfully present `First View` at runtime. 

Next, I can present `Second View` via `modelPresentationStyle = .overCurrentContext` and begin crafting my post. When I go to post via a simple button, `First View` presents but then freezes and crashes with the above error 

`Invalid update: invalid number of items in section 0. The number of items contained in an existing section after the update (8) must be equal to the number of items contained in that section before the update (8), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).` 

The underlying data is added and I can see it update in the Realm Browser, which is really cool. My first thought is I am updating faster than the UI can count. But how is that possible? I tested my theory with a `timer` object but this was hacky, error prone and it got me no where.   

 For the record, this works fine with the Mobile Database. My troubles began when I started using the Object Server. Again, if my project is required, I have no issue sending it over.

**Comment by DavidOliverDoswell** [comment]
Hi, @kishikawakatsumi 

Having a few issues reproducing a sample project, namely creating the exact conditions on my end for you to get the best look at what I'm struggling with, here. May I provide a link to the repo? I can further share our results and success here for others.

**Comment by DavidOliverDoswell** [comment]
This seems pretty simple. I can do this in Swift 3 with the Realm Database but not with the Object Server (although I'm certain that has nothing to do with it). I have tried adding and subtracting the number of articles in my `numberOfItemsInSection` e.g. `articles -= 1`. 

This raises the exception `Left side of mutating operator isn't mutable: 'articles' is a 'let' constant`

Here's what I am trying to accomplish:

**Second VC**

     //  Write article to the realm
    func publishToRealm() {
        DispatchQueue.main.async {
            let article = Article()
            self.realm = try! Realm(configuration: myConfig(user: SyncUser.current!))
            article.username = self.usernameLabel.text!
            article.text = self.editorTextView.text
            article.title = self.editorTitleTextField.text!
            try! self.realm.write {
                self.realm.add(article)
            }
        }
    }

**First VC**

These are my variables

    // Set up realm
    var realm : Realm!
    var articles : Results<Article>?
    var notificationToken: NotificationToken!

This is what I call in `viewDidLoad` e.g. `setUpRealm()`

     // Open realm using the Daily configuration
    private func setUpRealm() {
        DispatchQueue.main.async {
            // Acknowledge the user and access the realm on the main thread
            self.realm = try! Realm(configuration: myConfig(user: SyncUser.current!))
            self.articles = self.realm.objects(Article.self).sorted(byKeyPath: "created", ascending: false)
            
            // Observe notifications and update the UI when the underlying data has been changed
            self.notificationToken = self.articles?.addNotificationBlock { [weak self] (changes: RealmCollectionChange) in
                
                guard (self?.collectionView) != nil else { return }
                
                switch changes {
                case .initial:
                    self?.collectionView.reloadData()
                    break
                    
                case .update(_, let deletions, let insertions, let modifications):
                    self?.collectionView.performBatchUpdates({
                        self?.collectionView.deleteItems(at: deletions.map({ IndexPath(row: $0, section: 0)}))
                        self?.collectionView.insertItems(at: insertions.map({ IndexPath(row: $0, section: 0)}))
                        self?.collectionView.reloadItems(at: modifications.map({ IndexPath(row: $0, section: 0)}))
                        
                    }, completion: nil)
                    break
                    
                case .error(let error):
                    print(error.localizedDescription)
                    break
                }
            }
        }
    }

This is my data source

    /// Data Source Methods
    extension DailyViewController: UICollectionViewDataSource {
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return  1
    }
    
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        guard let articles = articles?.count  else { return 0 }
            return articles 
    }

    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath) as! ArticleCell
        
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium
        
        if (articles?.count) != nil {
            let article = articles?[indexPath.item]
            cell.usernameLabel.text = article?.username
            cell.articleTitleLabel.text = article?.title
            cell.articleTextView.text = article?.text
        }
    }

Apologies for the delay. Thank you, again, for your help.

**Comment by DavidOliverDoswell** [comment]
**UPDATE**

Not sure if this is best practice with this API (or collection views, for that matter), but after several interactions with the application my solution was to simply remove `Dispatch.main.async` from the function. Perhaps because once logged into the `Realm Object Server` there is no need to continue updating the collection view on the main thread.

 _I think_  this is because Realm's `RealmCollectionChange` API takes care of a lot of what we are used to doing manually with `UICollectionView`. Best practice is to always update the UI on the main thread **but** I believe the Collection Change API handles this, viz; `"Reactive programming just means reacting to the changes that are happening, and trying to minimize the number of different code paths they have to maintain to notify interested parties that changes have happened."`via @jpsim [https://academy.realm.io/posts/meetup-jp-simard-mastering-realm-notifications/?](url) 

Closing this issue for now unless anyone has anything further to contribute.
