### ISSUE TITLE
CocoaPods doesn't install last version of Realm !

### ISSUE THREAD

**Issue by X901** [realm/realm-cocoa#5335]
Hi , 

I just notice when I write `pod 'RealmSwift'` in  Podfile file
then I use `pod Install` 
it will installed version 2.7.0 

so I need to use `pod update`
to get version 2.10.1

it will be much better If it will downloading last version immediately 
without need to use `pod update`

**Comment by bdash** [comment]
Have you run `pod repo update` to have CocoaPods fetch the most recent version of the available pod specs?

**Comment by X901** [comment]
@bdash
it work when install then update 
the issue is I didn't know there is Update i was thinking i'm on the last update why there are many errors in swift 4 

so you need to make it install last update when user use `pod install` 

or at lease mention you need to use `pod update` after using `pod install`  on iOS Doc at Realm website

**Comment by bdash** [comment]
To quote [Realm Swift's CocoaPods installation instructions](https://realm.io/docs/swift/latest/#cocoapods-install) (emphasis is mine):
> * Install CocoaPods 1.1.0 or later.
> * __Run `pod repo update` to make CocoaPods aware of the latest available Realm versions.__
> * In your Podfile, add `use_frameworks!` and `pod 'RealmSwift'` to your main and test targets.
> * From the command line, run `pod install`.
> * Use the `.xcworkspace` file generated by CocoaPods to work on your project!
