### ISSUE TITLE
 Analyze 时，Xcode产生了3个issues，希望可以处理下

### ISSUE THREAD

**Issue by MyColourfulLife** [realm/realm-cocoa#5338]
**Questions**:
Product -> Analyze 时，Xcode产生了3个issues，不知道有没有事，希望处理下。
因为我打包upload to appstore 时，我的Xcode 总是崩溃。不知道跟这个有没有关系。
这是升级到Xcode9之后的事，Realm同步更新到RealmSwift (2.10.1)Realm (2.10.1)

## Goals
如图
![relam_issues](https://user-images.githubusercontent.com/24448234/30790748-6f5cbaf4-a1e0-11e7-9103-669723cb4550.png)

希望能 解决这些issues 

## Steps to Reproduce
Product -> Analyze

## Version of Realm and Tooling
Realm (2.10.1)
RealmSwift (2.10.1)
Xcode version: 9

iOS/OSX version: 
MacOSSierra 10.12.6

**Comment by kishikawakatsumi** [comment]
@MyColourfulLife Thank you for reporting, we will fix analyzer issue soon. But crashing Xcode when archiving seems not related to Realm. Can you provide a reproducible project for us? Try Xcode 8.3 or command line?

**Comment by austinzheng** [comment]
Closing because of lack of response.
