### ISSUE TITLE
Can not fetch data from Realm Database when application is awake using interactive notification (application terminated)

### ISSUE THREAD

**Issue by parth10136** [realm/realm-cocoa#5342]
**Can not fetch data from Realm Database when application is awake using interactive notification (application terminated)**

**Bugs**: I am Facing issue (Not get any data) when i fetch data from Realm Database in "handleActionWithIdentifier" method when application was Terminated.

## Goals
In to Interactive Notification, Give Replay of Message Like WhatsApp.
When Application was Terminated.

## Expected Results
 I want to fetch data from Realm Database when application is terminated or awake in Interactive Notification. 

## Actual Results
Getting Empty Result Array from Realm Database when application was terminated.
NOTE :- When application in Background that time it's working.

## Steps to Reproduce
1) Terminate Application.
2) Get Interactive Notification and Replay.
3) Call Realm method in this method.
```objc
- (void)application:(UIApplication *)application handleActionWithIdentifier:(nullable NSString 
         *)identifier forRemoteNotification:(NSDictionary *)userInfo withResponseInfo:(NSDictionary 
         *)responseInfo completionHandler:(void(^)())completionHandler {}
```

## Code Sample
```objc
- (void)application:(UIApplication *)application handleActionWithIdentifier:(nullable NSString *)identifier forRemoteNotification:(NSDictionary *)userInfo withResponseInfo:(NSDictionary *)responseInfo completionHandler:(void(^)())completionHandler {

NSString *strGroupID = [responseInfo valueForKey:@"UIUserNotificationActionResponseTypedTextKey"];

NSPredicate *predicateQuery = [NSPredicate predicateWithFormat:@"group_id = %@",strGroupID];
    id object = [[RecentModel allObjects] objectsWithPredicate:predicateQuery];
    
    NSLog(@"===================================================");
    NSLog(@"Recent Model : %@", [RecentModel allObjects]);
    NSLog(@"===================================================");
    NSLog(@"Needed Object : %@", object);
    NSLog(@"===================================================");
```

## Version of Realm and Tooling

Realm framework version: 2.0

Realm Object Server version: ?

Xcode version: 8.3.3

iOS/OSX version: 10.0

Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@parth10136 Sorry for the late reply. It seems that a new Realm file has been created. If you are changing the location of the Realm file in your application, you need to pass the same configuration in `- [UIApplicationDelegate application: handleActionWithIdentifier: forLocalNotification: completionHandler:]`.

Or, when `- [UIApplicationDelegate application: handleActionWithIdentifier: forLocalNotification: completionHandler:]` is called from the terminated state, `- [UIApplicationDelegate application: didFinishLaunchingWithOptions:]` `is also called before that, so please make sure whether you are clearing the data at that.

**Comment by parth10136** [comment]
@kishikawakatsumi Thanks for your replay.
I am not clear any kind of data when application is terminated.
and not change location of Realm file also.

I am use same configuration when i terminate application.

**Comment by kishikawakatsumi** [comment]
To isolate the problem, can you show logs of `[RecentModel allObjects]` and `[[RLMRealm defaultRealm] configuration] fileURL];` before the application terminates and after it woke up by notification.

**Comment by parth10136** [comment]
Thank you so much.
I find out the problem, problem is changed path of Realm Database when i woke up application by notification.

Before terminate application : 
> Realm Config: file:///var/mobile/Containers/Data/Application/772D76C8-09FD-4282-A152-A8A607DD9318/Documents/160.realm

after it woke up :
> Realm Config: file:///var/mobile/Containers/Data/Application/772D76C8-09FD-4282-A152-A8A607DD9318/Documents/default.realm
