### ISSUE TITLE
Fail when running prepare command

### ISSUE THREAD

**Issue by sibinlutoken** [realm/realm-cocoa#5343]
## Goals
I want to pod update and install realm

## Expected Results
Install realm successfully by 

Podfile:
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true

Command:
pod update --verbose

## Actual Results
Fetching external sources
-> Pre-downloading: `Realm` from `https://github.com/realm/realm-cocoa.git`, submodules `true`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/nw/tmdm02d568gf7ty3tgx2_5rr0000gn/T/d20170927-96877-16aewwv
     --template= --single-branch --depth 1
     Cloning into '/var/folders/nw/tmdm02d568gf7ty3tgx2_5rr0000gn/T/d20170927-96877-16aewwv'...
     $ /usr/bin/git -C
     /var/folders/nw/tmdm02d568gf7ty3tgx2_5rr0000gn/T/d20170927-96877-16aewwv
     submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into '/private/var/folders/nw/tmdm02d568gf7ty3tgx2_5rr0000gn/T/d20170927-96877-16aewwv/Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out '54a98b215284e58b73e0664723fbd852ffb04902'
     Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'Realm/ObjectStore/external/catch'
     Submodule 'external/pegtl' (https://github.com/ColinH/PEGTL) registered for path 'Realm/ObjectStore/external/pegtl'
     Cloning into '/private/var/folders/nw/tmdm02d568gf7ty3tgx2_5rr0000gn/T/d20170927-96877-16aewwv/Realm/ObjectStore/external/catch'...
     Cloning into '/private/var/folders/nw/tmdm02d568gf7ty3tgx2_5rr0000gn/T/d20170927-96877-16aewwv/Realm/ObjectStore/external/pegtl'...
     Submodule path 'Realm/ObjectStore/external/catch': checked out 'ee67ac6b7c3595251342671485c65cf81d725896'
     Submodule path 'Realm/ObjectStore/external/pegtl': checked out '3c4128a7e7e1288eb746418ea60c41477358f26a'
  $ /usr/bin/git -C
  /var/folders/nw/tmdm02d568gf7ty3tgx2_5rr0000gn/T/d20170927-96877-16aewwv
  rev-parse HEAD
  52dbb71bfd8ed20d7b8813f3999aaa8cd71396e6
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
[!] Failed to download 'Realm'.
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:119:in `rescue in block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:114:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:686:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:662:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:661:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:661:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:660:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:242:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

## Version of Realm and Tooling

Cocoapods: 1.3.1
Xcode version: 9
Mac OSX version: 10.12.6

Any idea about this error?

**Comment by kishikawakatsumi** [comment]
@sibinlutoken It seems temporary network error. Does it reproduce a lot of times? 

> 1. Your IP address range is from a region that is on the list of United States embargoes. In order to comply with U.S. law, Realm has not been made available in that region. For more information, please see our license.
> 2. You are located in mainland China, and due to the country-wide firewall are not able to properly access CloudFlare or Amazon AWS S3 services at the moment. Please see this Realm-Cocoa Issue for more information.
> 3. Amazon AWS S3 could be experiencing service issues. Please check the AWS Service Health Dashboard and try again later.


Please see also,
https://realm.io/docs/swift/latest/#realm-core-binary-fails-to-download
