### ISSUE TITLE
Project wont build in xcode 9

### ISSUE THREAD

**Issue by LonerganOnline** [realm/realm-cocoa#5350]
I opened a project that was working in xocde 8 but now wont build in xcode 9.

 - Semantic issue 
    - No Viable Overload '='
       - [Project_DIR]/Pods/Realm/include/impl/collection_notifier.hpp:234:13: Candidate function not viable: no known conversion from 'typename enable_if<!is_array<ResultsNotifier>::value, shared_ptr<ResultsNotifier> >::type' (aka 'std::__1::shared_ptr<realm::_impl::ResultsNotifier>') to 'const realm::_impl::CollectionNotifier::Handle<realm::_impl::ResultsNotifier>' for 1st argument

I have found the problem searching on google but all answers suggest upgraging to version 2.8.1 but i have installed version 2.10.2 and it is still not working.

![realm](https://user-images.githubusercontent.com/5843951/30957786-23b233ae-a433-11e7-8997-de3c2dff4253.png)

Version of Realm and Tooling

Realm framework version: ?
2.10.2

Xcode version: ?
9.0

iOS/OSX version: ?
11.0

Dependency manager + version: ?
pod

**Comment by LiuDeng** [comment]
@LonerganOnline how do you fix this?

**Comment by alimahfoudhi** [comment]
Try to change your podfile to the latest version of Realm:
pod 'Realm', '~> 3.0.1'
