### ISSUE TITLE
Exception: Invalid value for property on Xcode 9

### ISSUE THREAD

**Issue by aluco100** [realm/realm-cocoa#5351]
I have a bug when I update the pod version on my Podfile. I'm using the latest version of RealmSwift's framework on Xcode 9. This is my model:

```
import Foundation
import RealmSwift
import ObjectMapper

class Salesman: Object,Mappable,DataElementDelegate, ObjectDelegate {

   //MARK: - properties
   public dynamic var id: Int = 0
   public dynamic var name: String = ""
   public dynamic var amount: Int = 0
   public dynamic var updated_at_timestamp: Int = 0

   //MARK: - Init
   required convenience init?(map: Map) {
       self.init()
   }

   //MARK: - Mapping
   func mapping(map: Map) {
       id<-map["id"]
       name<-map["name"]
       amount<-map["amount"]
       updated_at_timestamp<-map["updated_at_timestamp"]
   }

   //MARK: - Realm methods
   override static func primaryKey()->String?{
       return "id"
   }

   //MARK: - Methods
   public func getID()->Int{
       return self.id
   }

   //MARK: - Data delegate

   func getAmount() -> String {
       return "\(self.amount)"
   }

   func getName() -> String {
       return self.name
   }

   func getLastUpdate() -> Int {
       return self.updated_at_timestamp
   }

}

```
Now when I try to insert values on my realmn I have this crash: '`RLMException', reason: 'Invalid value '1000' for property 'Salesman.amount''.`

What could be happen?
--

Realm framework version: 2.10.2

Xcode version: 9.0

iOS version: 11.0.1

**Comment by bdash** [comment]
Can you please share a) the code that triggers the exception, b) which version you're updating from that the same code worked correctly on.

**Comment by aluco100** [comment]
My code that triggers the exception is there:

`//MARK: - Mocks Salesman
public func mocksSalesman()->[Salesman]{

    var array: [Salesman] = []

    let sale1 = Salesman()
    sale1.id = 1
    sale1.name = "Raul"
    sale1.amount = 1000

    let sale2 = Salesman()
    sale2.id = 2
    sale2.name = "Tomas"
    sale2.amount = 500

    let sale3 = Salesman()
    sale3.id = 3
    sale3.name = "Luciano"
    sale3.amount = 700

    array.append(sale1)
    array.append(sale2)
    array.append(sale3)

    return array

}

public func insert(){
    let list = self.mocksSalesman()
    let realm = try! Realm()
    for item in list{
        try! realm.write {
            realm.add(item, update: true)
        }
    }
}`

And what do you mean about which version I'm updating from ?

Regards

**Comment by bdash** [comment]
You said "I have a bug when I update the pod version on my Podfile". Which version of Realm are you updating from?

**Comment by aluco100** [comment]
I've updated to 2.10.2 realmswift's pod version.
Regards

**Comment by bdash** [comment]
Yes, that's the version you're using now. Which version were you using prior to updating to v2.10.2?

**Comment by aluco100** [comment]
I've been using 2.7.0 realmswift's pod version.

**Comment by bdash** [comment]
The problem is the presence of these methods in your class:
```

   func getAmount() -> String {
       return "\(self.amount)"
   }

   func getName() -> String {
       return self.name
   }

   func getLastUpdate() -> Int {
       return self.updated_at_timestamp
   }
```

When Realm uses [Key-Value Coding](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/KeyValueCoding/BasicPrinciples.html#//apple_ref/doc/uid/20002170-BAJEAIEE) to retrieve the value of the `amount` property, [KVC follows a search pattern](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/KeyValueCoding/SearchImplementation.html#//apple_ref/doc/uid/20000955-CJBBBFFA) that includes looking for appropriate named getters. It tries `getFoo` before `foo`, which results in `getAmount()` being called and the string it returns being used in the attempt to initialize the `amount` property.

I'd strongly suggest avoiding method names that conflict with KVC's searching for this reason.

**Comment by aluco100** [comment]
Ok, that's work correctly.

Thanks a lot!
