### ISSUE TITLE
Failed to verify bitcode in Realm.framework/Realm:

### ISSUE THREAD

**Issue by NickJorgensen** [realm/realm-cocoa#5353]
A watch OS project with realm does not Export, Validate or Upload to the App Store...

## Actual Results

Received a variety of errors (see below).  I have attempted to recreate a blank Watch OS project with just realm added and got the same errors.

## Steps to Reproduce
basically we are creating a new Watch OS Xcode project, adding realm to the Watch Os target, archiving, then attempting to create an adHoc export, and also attempting to validate for upload to the iTunes store
1. Open xcode
2. In the "Welcome to xcode" screen click "Create new xcode project"
3. Select WatchOs tab, then under Applications select iOS App with Watchkit App
4. Name your project and select your team
5. After your project opens follow the instructions for installing realm on Watch OS
6. Make sure your app compiles and runs in the simulator on mobile and on watch simulators
7. Select Build Only Device and then Product menu, then Archive
8. In Organizer select the archive the click Export button, then selected add hoc
9. The App Thinning dial spins and then the following error is shown

Failed to verify bitcode in Realm.framework/Realm:
error: Cannot extract bundle from /var/folders/0l/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/T/IDEDistributionOptionThinning.TQ5/Payload/wkTestOnRealm.app/Watch/wkTestOnRealm WatchKit App.app/PlugIns/wkTestOnRealm WatchKit Extension.appex/Frameworks/Realm.framework/Realm

10. proceeding onto validating for upload to the app store close out of the export error screen.
11. this time click Validate on the right hand side with the Archive selected 

The following errors are shown

iTunes Store Operation Failed
Invalid Segment Alignment. The app binary at 'wkTestOnRealm.app/Watch/wkTestOnRealm WatchKit App.app/PlugIns/wkTestOnRealm WatchKit Extension.appex/Frameworks/Realm.framework/Realm' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

iTunes Store Operation Failed
Invalid Segment Alignment. The app binary at 'wkTestOnRealm.app/Watch/wkTestOnRealm WatchKit App.app/PlugIns/wkTestOnRealm WatchKit Extension.appex/Frameworks/RealmSwift.framework/RealmSwift' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

## Version of Realm and Tooling

Realm framework version: realm-swift-2.10.2

Realm Object Server version: -

Xcode version: 9.0 (9A235)

iOS/OSX version: 10.12.6

Dependency manager + version: git version 2.13.5 (Apple Git-94)

**Comment by bdash** [comment]
To clarify, are you integrating the prebuilt Realm / Realm Swift frameworks that we provide as part of our releases? Have you tried integrating Realm via CocoaPods or Carthage to see if you have different results?

**Comment by bdash** [comment]
I followed your steps and was only able to reproduce this if I skipped step 4 from our Dynamic Framework installation instructions:
> If using Realm in an iOS, tvOS or watchOS project, create a new “Run Script Phase” in your app’s target’s “Build Phases” and paste the following snippet in the script text field:
>
>```sh
>"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh"
>```
>This step is required to work around an App Store submission bug when archiving universal binaries.

Can you please ensure that any targets that embed the Realm frameworks contain this step?

**Comment by NickJorgensen** [comment]
Yes that was it.

The following script listed in the installation instuctions needs to be added to both the watchkit extension target and the mobile app target.

bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh"

Thanks, I feel like this changed from 8.0.


For some reason It wasn't needed before I upgraded

**Comment by bdash** [comment]
I'm glad to hear that fixed things for you. As far as I'm aware that step has been required for quite some time. I'm not sure why it would have been working for you previously without it.
