### ISSUE TITLE
fatal error: can't unsafeBitCast between types of different sizes

### ISSUE THREAD

**Issue by kruyvanna** [realm/realm-cocoa#5355]
## Goals

check if List contains an element

## Expected Results

Empty list should return false

## Actual Results

Error. StackTrace attached

## Steps to Reproduce

Define a Class with List as property
init an object from that class
check if List contains a value

## Code Sample

    import RealmSwift

    class DictionaryItem: Object {
        var suggestions = List<Int>()
        var count = 0 as Int
    }

    let di = DictionaryItem()
    let has = di.suggestions.contains(1)

## Version of Realm and Tooling

Realm framework version: ?
3.0.0-beta.4

Realm Object Server version: ?

Xcode version: ?
8
iOS/OSX version: ?
10/10.12.6
Dependency manager + version: ?
CocoaPod 1.3.1

**Comment by bdash** [comment]
Thanks very much for the bug report!

**Comment by kruyvanna** [comment]
Sorry I forgot to attach the stacktrace
Here it is
<img width="830" alt="screen shot 2017-09-29 at 6 39 37 pm" src="https://user-images.githubusercontent.com/1171793/31026452-b1728cdc-a570-11e7-9231-7d792e104715.png">

**Comment by austinzheng** [comment]
Thank you for the bug report and the stacktrace! The fix will be included in the next beta release.
