### ISSUE TITLE
mmap() failed: Cannot allocate memory size: 268435456 offset: 2684354560 on RealmSwift 2.10.2

### ISSUE THREAD

**Issue by aluco100** [realm/realm-cocoa#5357]
Hi there,

My realm was growing up so much so I have an exception for memory allocation size. My realm size is about 3.2 GB so I put this realm's configuration to resolve this:

```
let config = Realm.Configuration(
            // Set the new schema version. This must be greater than the previously used
            // version (if you've never set a schema version before, the version is 0).
            schemaVersion: 11,
            
            // Set the block which will be called automatically when opening a Realm with
            // a schema version lower than the one set above
            migrationBlock: { migration, oldSchemaVersion in
                
        },shouldCompactOnLaunch: {totalBytes, usedBytes -> Bool in
            guard totalBytes > 10 * 1024 * 1024 * 1024 else { return false }
            guard Double(usedBytes) / Double(totalBytes) < 0.5 else { return false }
            print("Should compact Realm database: \(usedBytes) / \(totalBytes)")
            return true
            
        })
        
        Realm.Configuration.defaultConfiguration = config

```

However, the issue still occurs. What am I doing wrong?

Regards

Realm framework version: 2.10.2

Xcode version: 9.0

iOS/OSX version: 11.0.1

Dependency manager + version: cocoapods 1.3.1

**Comment by kishikawakatsumi** [comment]
@aluco100 You can not rescue the file that is already too large to open. This is because compaction needs to create a Realm instance. Compaction should be done before mmap errors.

**Comment by aluco100** [comment]
I found that exception. The problem was the api that I'm using returning the same objects. Therefore, I'm using a recursive Promise with PromiseKit framework so I have an infinite bucle. Now I have a question, How can I catch that exception if the api will fail again?

Regards

**Comment by kishikawakatsumi** [comment]
@aluco100 You can catch the error like the following, but generally, there is no way to continue running the app other than deleting the file in which the mmap() error occurred. The important thing is not to enlarge the file. Does it answer for you?

 ```swift
 let realm: Realm?
 do {
     realm = try Realm()
 } catch Realm.Error.addressSpaceExhausted {
    ...
 }
 ```

**Comment by aluco100** [comment]
Ok, that's it. Thanks @kishikawakatsumi
