### ISSUE TITLE
Crash: Writing/Reading an Object with Date member 

### ISSUE THREAD

**Issue by ashleybrgr** [realm/realm-cocoa#5367]
## Goals

To have an Object that contains members of swift type Date

## Expected Results

Reading and writing objects with swift Date members should behave like other types

## Actual Results
 
After switching to Swift 4, the objects that contain Date members are no longer able to be written to. If you manually change the date (to a non nil date) in Realm Browser and try to read, a crash also occurs.

The crash when writing occurs on line 643 of `RLMAccessor.mm`
`value = static_cast<RLMOptionalBase *>(object_getIvar(obj, prop.swiftIvar)).underlyingValue;`

The crash when reading occurs on line 98 of `RLMObjectStore.mm` `RLMOptionalBase *optional = object_getIvar(object, prop.swiftIvar);`
## Steps to Reproduce

When you create any Object with a Date member and try to write to it a crash will occur. If you then manually change that member in the realm browser to be any non nil date and try to read it, another crash will occur. 

Both of these crashes are related to `object_getIvar` and `swiftIvar`
## Code Sample
 
This reproduces the writing crash at line 643
```import RealmSwift

class date: Object {
    public var startDate: Date?
}

let realm = try! Realm()
        
let dateObject1 = date()
dateObject1.startDate = Date()

try! realm.write {
    realm.add(dateObject1)
}
    
```

After changing the startDate manually in the Realm Browser and running this you get the crash at line 98:
```
        var find: Results<date>?
        find = realm.objects(date.self)
        find!.filter{ $0.startDate == Date() }

```
## Version of Realm and Tooling

Realm framework version: 2.10.2

Realm Object Server version: 2.10.2

Xcode version: 9.0

Swift version: 4

Dependency manager + version: cocoapods 1.3.1

**Comment by bdash** [comment]
The immediate cause of your crash is that you're missing the `@objc` annotation from the property. This annotation is required as of Swift 4 in order for a property to be visible to the Objective-C runtime, which is the primary way that Realm interacts with your objects. Additionally, the property should be declared as `dynamic` to ensure that accesses to it are always dynamically dispatched, allowing Realm to intercept gets / sets from the property and read / write the value from the underlying storage when needed. The [Property Attributes](https://realm.io/docs/swift/latest/#property-attributes) section of the Realm documentation discusses both of these issues.
