### ISSUE TITLE
Cannot connect to synced realm using v.3.0.0 beta.4 and rc.1 

### ISSUE THREAD

**Issue by drejer** [realm/realm-cocoa#5370]
## Goals

Connect to a realm with a sync configuration.

After updating to beta 4 of Realm Frameworks, the app no longer can connect to synced realms. 
* The codebase is the same except the few function renames required by beta 4. The parallel project using beta 3 is running fine against the same server. 
* The realms are newly defined realms.
* Can create syncUser. The problem only arises when connecting to synced realms.

## Expected Results

Successful connection as it happens with beta.1, beta.2 and beta.3 

## Actual Results
**Xcode log:**
2017-10-03 08:20:15.645302 Sync: Connection[1]: Resolving ' SERVERIP:9080'
2017-10-03 08:20:15.646018 Sync: Connection[1]: Connecting to endpoint ' SERVERIP:9080' (1/1)
2017-10-03 08:20:15.780425 Sync: Connection[1]: Connected to endpoint ' SERVERIP:9080' (from '192.168.1.211:51739')
2017-10-03 08:20:15.927879 Sync: Connection[1]: Writing failed: End of input
2017-10-03 08:20:15.928723 Sync: Connection[1]: Connection closed due to error

**Server log**
sync: HTTP Connection[11]: Connection is closed after HTTP response.
1:33:53 PMdetail
sync: HTTP Connection[11]: 404 Not Found
1:33:53 PMdebug
sync: HTTP Connection[11]: HTTP request received, url = /realm-sync/%2F2afb43bb6162978159987dce2e42c4c1%2FsyncFixed
1:33:53 PMdebug
sync: HTTP Connection[11]: Connection initiates HTTP receipt
1:33:53 PMinfo
sync: HTTP Connection[11]: Connection from 127.0.0.1:44830
1:33:53 PMdebug
proxy: attempting to upgrade client ::ffff:62.198.206.52:56214 => headers: {"authorization":"Realm-Access-Token version=1 token=\"[TOKEN]\","connection":"Upgrade","host":"[SERVERIP]","sec-websocket-key":"ZaUxn8oiYTOhkSie02wwsg==","sec-websocket-protocol":"io.realm.sync.21","sec-websocket-version":"13","upgrade":"websocket"}.}

## Steps to Reproduce

Happens when trying to connect to a synched Realm.
The synched realm is defined after successful userlogin. 

## Code Sample
        if let user = SyncUser.current {

            // Configure Realm
            let configuration = Realm.Configuration(
                    syncConfiguration: SyncConfiguration(user: user, realmURL: Constants.syncServerURL! ),
                    objectTypes: [Area.self, Task.self, Action.self, DateRange.self, User.self, MasterData.self]
                )
            Realm.Configuration.defaultConfiguration = configuration
            
            let realm = try! Realm()
            print(realm.objects(Task.self).count)  // HERE THE CONNECTION FAILS WITH THE ABOVE LOGS
        } else {
            print("Could not configure sync REALM, since there is no syncUser")
        }

## Version of Realm and Tooling

Realm framework version: 
v3.0.0-rc.1 (same issue with v3.0.0-beta.4)

Realm Object Server version: 
2.0.0-rc2-285

Xcode version: 
Xcode 9.0. Build version 9A235

iOS/OSX version: 
iOS11

Dependency manager + version: ?
Carthage, v0.25.0 . Cartfile: github "realm/realm-cocoa" "v3.0.0-rc.1"

**Comment by bdash** [comment]
The version of ROS you mention does not look to be a recent enough version for the version of Realm Cocoa you’re using. I’d recommend contacting help@realm.io to learn about updating to the appropriate version of ROS.

**Comment by drejer** [comment]
"Help" send me info on how to get an up to date ROS. 
No it's working!
Thanks!
