### ISSUE TITLE
Issue with Object: Equatable

### ISSUE THREAD

**Issue by truemetal** [realm/realm-cocoa#5371]
## Goals
`==` for equal objects should return true

## Expected Results
`==` for equal objects should return true

## Actual Results
At random `==` for equal objects return false

## Steps to Reproduce
Please consider the code sample below

## Code Sample
```
lazy var photos: Results<Photo> = { film.photos.sorted(byKeyPath: #keyPath(Photo.createdDate), ascending: false) }()
var selectedPhotos = Set<Photo>()

// later in cellForItemAt indexPath; this piece of code fails randomly
let isSelected = selectedPhotos.contains(photos[indexPath.row])

// later in select button handler
if selected { selectedPhotos.insert(photos[indexPath.row]) }
else { selectedPhotos.remove(photos[indexPath.row]) }
```

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A365

/Applications/Xcode.app/Contents/Developer
Xcode 9.0
Build version 9A235

/usr/local/bin/pod
1.3.1
Realm (2.10.2)
RealmSwift (2.10.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

/usr/local/bin/carthage
0.17.1
(not in use here)

/usr/bin/git
git version 2.13.5 (Apple Git-94)
```

**Comment by austinzheng** [comment]
If the model has a primary key, `==` returns true iff the two objects have the same primary key value. Otherwise, it returns the same thing as `===`, just like `NSObject`. If you want custom equality behavior for your `Object` subclass, you will have to implement a version of `==` for that subclass.

**Comment by truemetal** [comment]
The documentation is a bit misleading. Maybe it should mention the private keys? In my case they are both managed by the same Realm and point to the same database record. 

> Objects are considered equal if and only if they are both managed by the same Realm and point to the same underlying object in the database.

**Comment by austinzheng** [comment]
I'll see what I can do about the documentation.

Is there a simple repro project you can provide that we can take a look at? We fixed a bug related to equality recently, but since it changes the behavior of equality we won't be able to ship it until we release our forthcoming 3.0.0 release. In the meantime I can take a closer look at your issue and see if there's anything you can do to work around the issue.

**Comment by truemetal** [comment]
Attached test project was my case - just check some cells and scroll to see the issue. The solution is simple - just use a unique property to compare for equality. It's just I've killed some time with this issue, and submitting the ticket so that somebody else would not. 

Please let me know if you know how to get it reproduce without table view, using e.g. `dispatch async`. I'm curious, as I was unable to make an example without table view.

[realm-test.zip](https://github.com/realm/realm-cocoa/files/1369911/realm-test.zip)

**Comment by truemetal** [comment]
Ok, in my case it's got something to do with how swift's `Set` tests for equality. And if we dig a bit deeper - `Set` sometimes uses `isEqual()` and sometimes `hashValue`, seemingly randomly. When it uses `isEqual` the equality test works fine, and when it uses `hashValue` equality test fails. 

Here's a simpler demo project: [realm-test 3.zip](https://github.com/realm/realm-cocoa/files/1369995/realm-test.3.zip)

![screen shot 2017-10-10 at 01 33 17](https://user-images.githubusercontent.com/2472186/31361262-348234dc-ad5b-11e7-96b2-a03f8389f076.png)

**Comment by austinzheng** [comment]
Ah, the additional information you provided confirms that what you're seeing is [this problem](https://github.com/realm/realm-cocoa/issues/4705). It's been fixed for Swift 3.0.0, which we hope to release soon.

**Comment by truemetal** [comment]
@austinzheng I can see this bug still reproduces on 3.0.1

```
PODS:
  - Realm (3.0.1):
    - Realm/Headers (= 3.0.1)
  - Realm/Headers (3.0.1)
  - RealmSwift (3.0.1):
    - Realm (= 3.0.1)
```

**Comment by austinzheng** [comment]
If you can make a reproduction case and send it to us, we'd be happy to investigate further.

**Comment by truemetal** [comment]
The previous example in .zip still works, please just do ‘pod update’ on it

Cheers,
Dan

**Comment by truemetal** [comment]
@austinzheng please reopen this issue as this still reproduces in `v3.0.2`.
Please let me know if you need any additional info from me.

**Comment by austinzheng** [comment]
Your objects don't have primary keys and your "custom" implementations of `hashValue` and `isEqual` simply forward (through `Object`, then `RLMObjectBase`) to `NSObject`'s. So I really don't think this is an issue on our side.

For what it's worth, running your sample project on my machine with Realm 3.0.2 and Xcode 9.1 always returns false.
