### ISSUE TITLE
NSDICTIONARY not ignored

### ISSUE THREAD

**Issue by intNameless** [realm/realm-cocoa#5372]
Hi everyone,

I have some trouble since an update. My code works in the new beta of realm but when I downgrade the version of realm swift.. some troubles appears.

here is the class : 
```
import Foundation
import RealmSwift
class Commande: Object{
    @objc private dynamic var _id = UUID().uuidString
    @objc private dynamic var _client:Client? = nil
    @objc private dynamic var _tabArticle:Data?
    @objc private dynamic var _prixTotal:Double = 0.0
    
    @objc var dico: [String: Int] {
        get {
            guard let _tabArticle = _tabArticle else {
                return [String: Int]()
            }
            do {
                let dict = try JSONSerialization.jsonObject(with: _tabArticle, options: []) as? [String: Int]
                return dict!
            } catch {
                return [String: Int]()
            }
        }
        
        set {
            do {
                let data = try JSONSerialization.data(withJSONObject: newValue, options: [])
                _tabArticle = data
            } catch {
                _tabArticle = nil
            }
        }
    }
    
    override static func primaryKey() -> String? {
        return "_id"
    }

    override static func ignoredProperties() -> [String]{
        return ["dico"]
    }
```

the error is this : 
> Terminating app due to uncaught exception 'RLMException', reason: 'Property 'dico' is declared as 'NSDictionary', which is not a supported RLMObject property type.

If someone have an idea, it should be great !!!

**Comment by bdash** [comment]
Which version of Realm Swift are you seeing the problem with? And which version of Realm Swift are you seeing the code work with?

**Comment by intNameless** [comment]
RealmSwift 3.0.0-rc.1

**Comment by bdash** [comment]
Which of my two questions is that the answer to?

**Comment by bdash** [comment]
For what it is worth, I dropped the code snippet that you provided into a project using Realm Swift v2.10.2 and it compiled and ran without problems. It also works fine with Realm Swift v3.0.0-rc.1. Are you sure the problem is specific to the code snippet you shared, rather than another class in your app?

**Comment by intNameless** [comment]
hey, thanks for ur answers! Yes I'm sure the problem is in this class because I use NSDictionnary and this property is not ignored. I Upgrade my realmSwift to 3.0.0-rc.1 and it works so I stay in this version and I wait realmBrowser to read the realmFile without encryption key.

Thank you !
