### ISSUE TITLE
Object properties are not assigned in Objective-C

### ISSUE THREAD

**Issue by crontab** [realm/realm-cocoa#5373]
## Goals
Store and retrieve simple objects by primary key. The objects have the following structure:

```
@interface RealmObject : RLMObject
@property (nonatomic) NSString* key;
@property (nonatomic) NSData* value;
+ (NSString *)primaryKey; // returns @"key"
@end
```

## Actual Results
When trying to retrieve an existing object by its primary key I get an object with both key and value set to nil. While debugging I found that Realm's internal function `RLMInitializeSwiftAccessorGenerics()` checks for `object->_objectSchema->_isSwiftClass` and bails out without updating the properties because `isSwiftClass` is false. I've found the place where `isSwiftClass` is initialized: the condition is the custom object should be derived from `RealmSwiftObject`, which is not the case here, hence `isSwiftClass` is set to false and the property assignment is skipped if you use Objective-C.

## Steps to Reproduce
Please see above. The custom object should be derived from RLMObject, code should be in Objective-C. Don't know if this is relevant or not: I use a custom Realm configuration with an encryption key.

The objects are retrieved using `[RLMObject objectInRealm: forPrimaryKey:]`

## Version of Realm and Tooling
Realm framework version: 2.10.2

Realm Object Server version: ?

Xcode version: 9.0

iOS/OSX version: iOS11

Dependency manager + version: ?

**Comment by bdash** [comment]
Perhaps I’m overlooking something, but you haven’t shared details of how you’re _using_ the class definition that you shared. How are you creating it, how’re you retrieving it, and how are you determining that the retrieved object has properties that are nil?

**Comment by crontab** [comment]
@bdash I can see in the debugger that `[RLMObject objectInRealm: forPrimaryKey:]` returns an object of my custom class `RealmObject` but both my properties `key` and `value` are nil. While doing detailed step by step debugging in Realm source I found that the exact place where the properties are supposed to be assigned from the row, but that part is skipped because `isSwiftClass` is false. That happens in function `RLMInitializeSwiftAccessorGenerics()`, like I explained above.

https://github.com/realm/realm-cocoa/blob/9df4bcb39459bb58a376a4ef0e088f8fc2376a83/Realm/RLMObjectStore.mm#L78

**Comment by bdash** [comment]
Instance variable values are not meaningful for managed objects. Their getters / setters are rewritten to read / write from the underlying storage rather than the ivars. For this reason you should use the getters / setters when accessing any properties managed by Realm.

The code you’re referencing is only used for Swift types such as `List<T>` which have a different access model than Objective-C types due to the use of Swift generics.

**Comment by crontab** [comment]
@bdash the code I'm referencing is executed as part of my `[RLMObject objectInRealm: forPrimaryKey:]` call in my Objective-C app. We don't use any Swift at all. Also this is a Cocoapods installation if that helps.

Again, I can see this when debugging step by step and it looks like a bug. Has anyone even tried this version of Realm (with primary keys specifically) from Objective-C?

**Comment by bdash** [comment]
Please show me the code you’re using to print the values of the properties on the object you’ve retrieved from the Realm.

**Comment by bdash** [comment]
The reason I ask to see the code you’re using to look at the values is that is the easiest way to verify whether you’re looking at the values of the instance variables or the values returned by the getter. As I mentioned earlier, the former are meaningless for managed objects.

**Comment by crontab** [comment]
@bdash Yes you are right. I was accessing the properties directly from within methods defined in the custom object. Changing that to self.XXX fixed the problem. I think the documentation should mention this (unless I missed it in the docs of course).

Thanks for your help!
