### ISSUE TITLE
Fetching data by date time not working for same date object in range.

### ISSUE THREAD

**Issue by HrishiPol** [realm/realm-cocoa#5378]
Hi all,

I'm trying to fetch data from table for given date range which is working fine.
I'm using below code to do so:
let appointmentData = Array(self.realmInstance.objects(Appointment.self).filter("startTime >= %@ && endTime <= %@",startDate, endDate))

But when I pass same date object as startDate and endDate then it not returning expected result value.
Can anyone help me with this.
Also please let me know if anything is missing from my end.

Thank you in advance.

**Comment by kishikawakatsumi** [comment]
@HrishiPol It looks like an expected result. If you pass the same value to `startTime` and `endTime`, the data that matches the query must have the same `startTime` and `endTime`, or the value of `endTime` should earlier than `startTime`. Guessing from the property name, it is unlikely to think that `endTime` is earlier than `startTime`.

**Comment by HrishiPol** [comment]
Its my mistake. startTime and endTime both are nothing but startDate and EndDate only.

**Comment by kishikawakatsumi** [comment]
Resolved https://realm-public.slack.com/archives/C03V60PJP/p1507320529000114
