### ISSUE TITLE
Unable to run project in Xcode 9 with iOS 11 and Swift 4

### ISSUE THREAD

**Issue by Rubenfer** [realm/realm-cocoa#5380]
I'm trying to use Realm in my Xcode project for iOS 11 using Swift 4 and Carthage but I can't run it.

> *** Downloading realm-cocoa.framework binary at "v2.10.2"
> 
> Skipped installing realm-cocoa.framework binary due to the error:
> 	"Incompatible Swift version - framework was built with 3.1 (swiftlang-802.0.53 clang-802.0.42) and the local version is 4.0 (swiftlang-900.0.65 clang-900.0.37)."

**Comment by bdash** [comment]
Did you see any further output from Carthage after the portion you quoted? Typically immediately after that output you'll see:
```
*** Checking out realm-cocoa at "v2.10.2"
*** xcodebuild output can be found in /var/folders/dl/…/T/carthage-xcodebuild.….log
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
```

Carthage only supports using prebuilt binaries for a single version of Xcode. Currently Realm's prebuilt binaries are built with Xcode 8.3.3. If the version of Xcode you're using differs from the version used to build the prebuilt binaries, Carthage will detect this, and fall back to building Realm from source. The end result should still be working Realm frameworks.

**Comment by Rubenfer** [comment]
The complete output that I get in Terminal is this:

```
*** Fetching realm-cocoa
*** Downloading realm-cocoa.framework binary at "v2.10.2"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 (swiftlang-802.0.53 clang-802.0.42) and the local version is 4.0 (swiftlang-900.0.65 clang-900.0.37)."
*** Checking out realm-cocoa at "v2.10.2"
*** xcodebuild output can be found in /var/folders/5h/zthvl6312vsbw2wm2dxbphc00000gn/T/carthage-xcodebuild.jmr8jF.log
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
```

I'm trying to use Realm in **Xcode 9 and Swift 4 with Carthage**. How can I solve it? Thanks!

**Comment by bdash** [comment]
The output clearly shows Carthage falling back to building Realm and RealmSwift from source, and it appears to have succeeded in doing so. I'm not sure what problem you think there is to solve?

**Comment by Rubenfer** [comment]
I can't use Realm in my project. When I try to run the Xcode project, I have this error:

`Module compiled with Swift 3.1 cannot be imported in Swift 3.2: /Users/.../Frameworks/realm-swift/ios/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64.swiftmodule`

I tried to run the project with Swift 4 and Swift 3.2, but in the two cases I have the same error.

**Comment by bdash** [comment]
That path to RealmSwift.framework doesn't look like where Carthage puts its frameworks. Carthage puts them at `$(SRCROOT)/Carthage/Build/iOS/`. Are you sure your Xcode project is configured to use Realm Swift from Carthage, rather than from some other source? I'd suggest checking where the framework at the path referenced in the error message is and where it came from.

**Comment by Rubenfer** [comment]
Solved! Thanks so much!!
