### ISSUE TITLE
Converting local realm to synced realm in Swift

### ISSUE THREAD

**Issue by i-schuetz** [realm/realm-cocoa#5381]
## Goals
Convert local Realm to synced Realm in Swift

## Actual Results
I tried to follow the [obj-c recipe](https://realm.io/docs/cookbook/objc/local-realm-to-synced/) provided in the documentation, but there are issues - e.g. configuration doesn't have a `dynamic` property and `customSchema` is private, such that it's not possible to port this line: `syncConfig.customSchema = [realm.schema copy];`.

What would be the Swift recipe? Is the objc recipe maybe also outdated?

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

/Applications/Xcode.app/Contents/Developer
Xcode 9.0
Build version 9A235

/usr/local/bin/pod
1.3.1
Realm (2.10.1)
RealmSwift (2.10.1)
RealmSwift (~> 2.10)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.25.0
(not in use here)

/usr/bin/git
git version 2.13.5 (Apple Git-94)
```

**Comment by kishikawakatsumi** [comment]
Dynamic Realm is provided as a separate module. In order to use the function, you need to import `Realm.Dynamic` module. Since `Realm.Dynamic` module is not provided RealmSwift, you need to use Realm Objective-C from Swift.

The following code is a port of recipe's code to Swift.

```swift
import Realm
import Realm.Dynamic
import RealmSwift

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    let sourceFilePath = Bundle.main.url(forResource: "fieldFlow", withExtension: "realm")
    let configuration = RLMRealmConfiguration()
    configuration.fileURL = sourceFilePath
    configuration.dynamic = true
    configuration.readOnly = true

    let localRealm = try! RLMRealm(configuration: configuration)

    let creds = SyncCredentials.usernamePassword(username: "admin@realm.io", password: "password")
    SyncUser.logIn(with: creds, server: URL(string: "http://localhost:9080")!) { (syncUser, error) in
        DispatchQueue.main.async {
            if let syncUser = syncUser {
                self.copyToSyncRealmWithRealm(realm: localRealm, user: syncUser)
            }
        }
    }
}

func copyToSyncRealmWithRealm(realm: RLMRealm, user: RLMSyncUser) {
    let syncConfig = RLMRealmConfiguration()
    syncConfig.syncConfiguration = RLMSyncConfiguration(user: user, realmURL: URL(string: "realm://localhost:9080/~/fieldRow")!)
    syncConfig.customSchema = realm.schema

    let syncRealm = try! RLMRealm(configuration: syncConfig)
    syncRealm.schema = syncConfig.customSchema!
    try! syncRealm.transaction {
        let objectSchema = syncConfig.customSchema!.objectSchema
        for schema in objectSchema {
            let allObjects = realm.allObjects(schema.className)
            for i in 0..<allObjects.count {
                let object = allObjects[i]
                RLMCreateObjectInRealmWithValue(syncRealm, schema.className, object, true)
            }
        }
    }
}
```

**Comment by i-schuetz** [comment]
Awesome, thanks! However `RLMRealm.allObjects()` seems not to exist, am I missing something?

Also it would be great if this recipe can be added to the cookbook, together with the obj-c and javascript version, so other people find it more easily!

**Comment by kishikawakatsumi** [comment]
`RLMRealm.allObjects()` is defined in `Realm.Dynamic` module.

https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm_Dynamic.h#L45

Can you make sure importing `Realm.Dynamic` ?

I will add this to the cookbook soon, thanks.

**Comment by i-schuetz** [comment]
My bad! I moved the (unfinished) code to another file and forgot to import it again. It's compiling now, thanks!

**Comment by i-schuetz** [comment]
I'm having a problem running this. It crashes, because there's already a realm opened with different dynamic settings (`dynamic` property) or rights (`readOnly` property). E.g.:

'Realm at path '/myPath/default.realm' already opened with different dynamic settings'

I'm not sure how to solve this - why is a local realm already open? (I'm not aware of being using the local realm at the moment this method is called). I also wouldn't know how to "close" it?

**Comment by kishikawakatsumi** [comment]
@i-schuetz Probably there is something wrong in your code. Can you share your code? Opening with `dynamic` option is for local realm, do not specify `dynamic` to synced Realm. and also if you open the local Realm in the document directory, do not need to specify `readOnly`, it is for reading main bundle ( the app bundle is read-only).

> Also, could you please explain why these snippets (including yours) use Bundle to locate the realm, while by default it seems to be stored in the documents directory?

The recipe is a scenario in which master data pre-installed in an application is converted to synchronized Realm. If you convert a Realm located elsewhere, such as the Document directory, please change it as necessary. Local Realm's path is not essential.

**Comment by i-schuetz** [comment]
Sorry for having abandoned this, I'm working on something else, but I'll come back and answer as soon as I can!

**Comment by i-schuetz** [comment]
@kishikawakatsumi okay, I think the issue is this: contrary to what I said in my previous comment, my local realm is already in use when I open it with `RLMRealm.asyncOpen(with: localConfig, callbackQueue: .main)`. Or at least I assume it is, as I'm using it everywhere in the app with `Realm()` (to load / save my data...) and this initializer uses the default configuration, which is not dynamic. So when I try to open it again with `dynamic` it complains.

How do I solve this? Do I have to open everywhere my local realm with dynamic? Or what else?

**Comment by vincentgigandet** [comment]
@kishikawakatsumi Hi, could you please answer [this question](https://stackoverflow.com/questions/56438304/converting-local-realm-to-synced-realm-in-the-middle-of-app-life-cycle-in-swift)? I'm really stuck on this issue.

**Comment by LikeCarter** [comment]
The code from kishikawakatsumi worked with a few modifications for me. 

```swift
            let syncRealm = try! RLMRealm(configuration: syncConfig)
            try! syncRealm.transaction {
                let objectSchema = realm.schema.objectSchema
                for schema in objectSchema {
                    let allObjects = realm.allObjects(schema.className)
                    for i in 0 ..< allObjects.count {
                        let object = allObjects[i]
                        if syncRealm.object(withClassName: schema.className, forPrimaryKey: object["id"]!) == nil {
                            syncRealm.createObject(schema.className, withValue: object)
                        }
                    }
                }
            }
```

You can see the full function here:
https://gist.github.com/LikeCarter/b9f9da8ce6c0c1feadddeedfab474f38
