### ISSUE TITLE
could not open the Realm file in the realM browser 2.1.12

### ISSUE THREAD

**Issue by UmaRajesh** [realm/realm-cocoa#5387]
i am using 3.0.0-rc1 realM and i could not open a file generated. i am using realM browser 2.1.12
When i try to open, its asking for encryption key

Realm framework version: 3.0.0-rc1

Realm Object Server version: ?

Xcode version: 9
 Swift  : 4

**Comment by tgoyne** [comment]
Because 3.0 has file format changes, you must use a [3.0-compatible release of the browser](https://github.com/realm/realm-browser-osx/releases/tag/v3.0.0-rc)
