### ISSUE TITLE
Providing "Export Compliance" when using encryption

### ISSUE THREAD

**Issue by dmitrysimkin** [realm/realm-cocoa#5388]
Please help to understand how to answer "Export Compliance" questions. What people usually answer when submitting apps that encrypt their data in Realm by setting encryptionKey? 

> 1. Does your app use encryption? Select Yes even if your app only uses the standard encryption in iOS and macOS.

Answer is YES

but then 

> 2. Does your app qualify for any of the exemptions provided in Category 5, Part 2 of the U.S. Export Administration Regulations?
> 
> Make sure that your app meets the criteria of the exemption listed below. You are responsible for the proper classification of your product. Incorrectly classifying your app may lead to you being in violation of U.S. export laws and could make you subject to penalties, including your app being removed from the App Store. Read the FAQ thoroughly before answering this question.
> 
> You can select Yes for this question if the encryption of your app is:
> (a) Specially designed for medical end-use
> (b) Limited to intellectual property and copyright protection
> (c) Limited to authentication, digital signature, or the decryption of data or files
> (d) Specially designed and limited for banking use or “money transactions”; or
> (e) Limited to “fixed” data compression or coding techniques
> 
> You can also select Yes if your app meets the descriptions provided in Note 4 for Category 5, Part 2 of the U.S. Export Administration Regulations.

**What to answer here?** 
As I understand Realm inside uses CommonCrypto provided by iOS and it's also exemption as `Use of encryption is limited to encryption within the operating system (iOS or macOS)
`, so the answer is **YES** and I **do not need to request** anything to BIS or elsewhere? Am I right?

Thanks

**Comment by bdash** [comment]
Please see Apple's FAQ entry titled [How do I answer each of the export compliance questions?](https://itunespartner.apple.com/en/apps/faq/Managing%20Your%20Apps_Export%20Compliance#21109148) for detailed guidance on this issue. You are correct that Realm only makes use of encryption provided by the operating system.
