### ISSUE TITLE
  Unable to install Realm via Cocoapods

### ISSUE THREAD

**Issue by AravindBG** [realm/realm-cocoa#5390]
I'm using Realm in my app and I'm able to install it via Cocoapods before. Recently whenever I tried to install the Realm version using cocoapods,`    pod 'Realm', '0.95’`

I'm getting the following error

>     [!] /bin/bash -c set -e sh build.sh cocoapods-setup
> 
>     core is not a symlink. Deleting... 
>     Downloading dependency: core 0.92.1.1 
>     mv: rename ./RealmSwift-swift2.0/../Realm/Realm-Info.plist to ./RealmSwift-swift2.0/RealmSwift-Info.plist: No such file or directory

Any idea why this is happening?

**Comment by bdash** [comment]
You're using a version of Realm that's over two years old. We cannot provide support for such an old version.
