### ISSUE TITLE
User data loss during migration from realm-cocoa 2.10.1 to 2.10.2

### ISSUE THREAD

**Issue by molind** [realm/realm-cocoa#5391]
## Goals
Start application with updated realm version.

## Expected Results
Everything migrated correctly and data is available in synchronised realm.

## Actual Results
Exception happened inside
realm::Realm::Realm constructor

underlying	std::__1::string	"Realm file decryption failed"	
error_kind	realm::RealmFileException::Kind	AccessError

[RLMSyncUser allUsers] call returns empty array. And app thinks that it's not in synchronized mode.

## Steps to Reproduce

Install Galileo 3.6.1 from Testflight, turn Sync on. Add some data. Update it to Galileo 3.7.1. After update it displays that it's not synchronized anymore and there is no user data. I think you could reproduce it with any app with synchronized realm during migration from realm-cocoa 2.8.1 to 2.10.2.

## Code Sample
As I found from debugging the issue caused changed storage of metadata encryption key. Seems that in 2.8.1 encryption key was stored in some different place. Or there was no encryption at all.

## Version of Realm and Tooling
Realm framework version: 2.10.2

Realm Object Server version: 1.8.3

Xcode version: 9

iOS/OSX version: 11.0.2

Dependency manager + version: Cocoapods

**Comment by molind** [comment]
Updated data. Migration from 2.8.2 to 2.10.1 was ok. And issue is most likely between 2.10.1 and 2.10.2. Checking now.

**Comment by molind** [comment]
Ok. Bug has been found.

First you move `path` variable, and then you check if file exists at path. Sure it's not. And legacy key is not checked. Beep.

https://github.com/realm/realm-object-store/blob/master/src/sync/impl/sync_metadata.cpp#L90-L98

**Comment by molind** [comment]
Worst thing that now we have new encryption key and old encryption key in keychain.

**Comment by bdash** [comment]
@molind, I'm sorry for the trouble this has caused you, and greatly appreciate the diagnostic efforts.

**Comment by austinzheng** [comment]
Thanks for reporting this; we regret the inconvenience. The next version we release will contain a fix.
