### ISSUE TITLE
Reaml object extension fail swift compiler 

### ISSUE THREAD

**Issue by codalamanp** [realm/realm-cocoa#5392]
When I create extension of realm object swift compiler gives me error like command failed due to signal segmentation fault 11 swift 

class InventoryProduct : Object {
    dynamic var productNumber : Int = 0
    dynamic var productReportingName : String?
    dynamic var productPosName : String?
    dynamic var productType : String?
    dynamic var fullDescription : String?
    dynamic var shortDescription : String?
    dynamic var quantity : Int = 0
} 

extension InventoryProduct {
     var totalTax:Float = 0.0
}

**Comment by bdash** [comment]
Am I correct in understanding that the Swift compiler is crashing when attempting to compile the code you share? If so, you should [file a bug against the Swift compiler](https://swift.org/contributing/#reporting-bugs).
