### ISSUE TITLE
iOS 11 device crash [OK on simulator]

### ISSUE THREAD

**Issue by sroik** [realm/realm-cocoa#5394]
group.cpp:308: [realm-core-2.8.6] Assertion failed: top_size == 3 || top_size == 5 || top_size == 7 with (top_size) =  [0]

0   Realm                               0x000000010159ec44 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 44

1   Realm                               0x000000010159f12c _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 452

2   Realm                               0x000000010170ecdc _ZN5realm14SortDescriptor6SorterC1ERKNSt3__16vectorINS3_IPKNS_10ColumnBaseENS2_9allocatorIS6_EEEENS7_IS9_EEEERKNS3_IbNS7_IbEEEERKNS_6ColumnIxEE + 0

3   Realm                               0x000000010164c6c8 _ZN5realm5Group6attachEmb + 180

4   Realm                               0x000000010164cd30 _ZN5realm5Group4openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKcNS0_8OpenModeE + 192

5   Realm                               0x000000010147d708 _ZN5realm5GroupC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKcNS0_8OpenModeE + 512

6   Realm                               0x000000010147d4f0 _ZN5realm5GroupC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKcNS0_8OpenModeE + 52

7   Realm                               0x0000000101472748 _ZN5realm5Realm16open_with_configERKNS0_6ConfigERNSt3__110unique_ptrINS_11ReplicationENS4_14default_deleteIS6_EEEERNS5_INS_11SharedGroupENS7_ISB_EEEERNS5_INS_5GroupENS7_ISF_EEEEPS0_ + 240

8   Realm                               0x0000000101471f14 _ZN5realm5RealmC2ENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEE + 748

9   Realm                               0x000000010128ca40 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerC2ES1_S6_ + 192

10  Realm                               0x000000010128c968 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerC1ES1_S6_ + 28

11  Realm                               0x000000010128c25c _ZNSt3__110shared_ptrIZN5realm5Realm17make_shared_realmENS2_6ConfigENS0_INS1_5_impl16RealmCoordinatorEEEE19make_shared_enablerE11make_sharedIJS3_S6_EEES8_DpOT_ + 1648

12  Realm                               0x000000010127e81c _ZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEE + 76

13  Realm                               0x000000010127da0c _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 1600

14  Realm                               0x0000000101476048 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 144

15  Realm                               0x000000010140bea0 +[RLMRealm realmWithConfiguration:error:] + 2676

16  RealmSwift                          0x0000000101c75200 _T010RealmSwift0A0CA2C13ConfigurationV13configuration_tKcfcTf4gn_n + 224

17  RealmSwift                          0x0000000101c72144 _T010RealmSwift0A0CA2C13ConfigurationV13configuration_tKcfC + 368

18  PixelArt                            0x000000010077f034 _T08PixelArt8DatabaseC5realm33_037C6A9916AE5201BA692C88AEA70A28LL10RealmSwift0L0Cfg + 764

19  PixelArt                            0x000000010077ec0c _T08PixelArt8DatabaseC05pixelB5MetasSayAA0aB10MetaEntityCGfg + 40

20  PixelArt                            0x0000000100765d6c _T08PixelArt16DatabaseInjectorV6injectyAA0C0C8database_AF4intotF + 600

21  PixelArt                            0x0000000100770b24 _T08PixelArt14StorageServiceC9bootstrapyyF + 272

22  PixelArt                            0x0000000100748f54 _T08PixelArt11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0F16LaunchOptionsKeyVypGSg022didFinishLaunchingWithI0tF + 268

23  PixelArt                            0x00000001007492f8 _T08PixelArt11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0F16LaunchOptionsKeyVypGSg022didFinishLaunchingWithI0tFTo + 216

24  UIKit                               0x000000018b4f7050 <redacted> + 384

25  UIKit                               0x000000018b6ea898 <redacted> + 3428

26  UIKit                               0x000000018b6ef6e4 <redacted> + 1712

27  UIKit                               0x000000018b97d454 <redacted> + 800

28  UIKit                               0x000000018bc4d1f0 <redacted> + 160

29  UIKit                               0x000000018b97d0b8 <redacted> + 252

30  UIKit                               0x000000018b97d928 <redacted> + 748

31  UIKit                               0x000000018c0e66e8 <redacted> + 260

32  UIKit                               0x000000018c0e658c <redacted> + 448

33  UIKit                               0x000000018be629c0 <redacted> + 220

34  UIKit                               0x000000018bff7fc8 _performActionsWithDelayForTransitionContext + 112

35  UIKit                               0x000000018be62870 <redacted> + 252

36  UIKit                               0x000000018bc4c850 <redacted> + 364

37  UIKit                               0x000000018b6ede28 <redacted> + 540

38  UIKit                               0x000000018baf16ec <redacted> + 364

39  FrontBoardServices                  0x0000000184719768 <redacted> + 364

40  FrontBoardServices                  0x0000000184722070 <redacted> + 224

41  libdispatch.dylib                   0x0000000102a3945c _dispatch_client_callout + 16

42  libdispatch.dylib                   0x0000000102a45b74 _dispatch_block_invoke_direct + 268

43  FrontBoardServices                  0x000000018474da04 <redacted> + 36

44  FrontBoardServices                  0x000000018474d6a8 <redacted> + 404

45  FrontBoardServices                  0x000000018474dc44 <redacted> + 56

46  CoreFoundation                      0x0000000182020358 <redacted> + 24

47  CoreFoundation                      0x00000001820202d8 <redacted> + 88

48  CoreFoundation                      0x000000018201fb60 <redacted> + 204

49  CoreFoundation                      0x000000018201d738 <redacted> + 1048

50  CoreFoundation                      0x0000000181f3e2d8 CFRunLoopRunSpecific + 436

51  GraphicsServices                    0x0000000183dcff84 GSEventRunModal + 100

52  UIKit                               0x000000018b4eb880 UIApplicationMain + 208

53  PixelArt                            0x0000000100749b6c main + 76

54  libdyld.dylib                       0x0000000181a6256c <redacted> + 4

IMPORTANT: if you see this error, please send this log to help@realm.io

**Comment by kishikawakatsumi** [comment]
@sroik We've seen this error occasionally when the Realm file is damaged. Might you have access to copies of any of these Realm files so we can investigate them? Also, do you know if these Realm files have grown very large in size (hundreds of megabytes)? Does your application perform any sort of file operation on Realm files after a Realm has been opened for the first time? Could you provide us a reproducible sample project?

**Comment by amccarri** [comment]
We are seeing this in production with one of our users.  Analytics shows their device is very low on disk space (< 1%).  Could running out of disk space cause this assertion failure?

**Comment by austinzheng** [comment]
Hi @amccarri. Lack of disk space shouldn't corrupt the Realm file and cause an assertion failure like this one; instead, we should throw an exception indicating that there's not enough disk space. I don't know what version of Realm you're running, but recent versions of the underlying database engine have fixed a bunch of bugs that could possibly lead to the issue you're seeing, so if you're not running 3.0.0 or later and can upgrade I encourage you to do so.

**Comment by amccarri** [comment]
Yeah looks like we are on 2.10.2.  I'll see if I can update.
