### ISSUE TITLE
Need ability to subscribe to multiple partial-sync queries

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-cocoa#5397]
Adapted from a slack convo earlier with @austinzheng:

It would be really helpful if there was a way to launch multiple subscriptions when you need a bunch of things sycn’d before your app is ready to run .   Running into this right now with Teamwork.  For example, the user’s own person record needs to be subscribed to, as do the collection of Locations, Teams and Tasks before the app is ready to display its first view controller.

At present the only way to effect with is with multiple chained asynchronous requests which is pretty cumbersome at best.

Something like `someRealm.subscribeTo(queryDictionary)`  where the dict’s keys/vals are Model references and query strings (or NSPredicates) …

## Version of Realm and Tooling
Realm framework version: ? 3.0.0-rc1

Realm Object Server version: ? 2.0.0-rc.7

Xcode version: ? Xcode 9.0

iOS/OSX version: ? 10, 11

Dependency manager + version: ? N/A

**Comment by bdash** [comment]
This sounds like a perfect place to use a dispatch group rather than increasing our API surface area.

Here's some pseudo-Swift demonstrating what I mean:

```swift
let group = DispatchGroup()
for (type, query) in subscriptions {
    group.enter()
    realm.subscribe(to: type, where: query) { result, error in
        // Do something with the results of this query.
        group.leave()
   }
}
group.notify() {
    // This will fire when all queries in `subscriptions` have been executed for the first time.
}
```

Depending on your needs, you might choose to forgo the loop in favor of having multiple calls to `Realm.subscribe(to:where:completion:)`.

**Comment by austinzheng** [comment]
It seems like the dispatch group solution outlined above should be sufficient for your needs. Feel free to re-open if it doesn't meet your requirements.
