### ISSUE TITLE
A Strange Crash

### ISSUE THREAD

**Issue by LucasDang** [realm/realm-cocoa#5398]
### Code:

    self.chatList = [[SGChatListM allObjects] sortedResultsUsingKeyPath:@"latestMsgTime" ascending:NO];
    
    WeakObj(self);
    self.rlmNototificationToken = [self.chatList addNotificationBlock:^(RLMResults * _Nullable results, RLMCollectionChange * _Nullable change, NSError * _Nullable error) {
        
        if (error) {
            NSLog(@"Failed to open Realm on background worker: %@", error);
            return;
        }
        
        if (!change) {
            [selfWeak.myTableView reloadData];
            return;
        }
        
        [selfWeak.myTableView beginUpdates];
        [selfWeak.myTableView deleteRowsAtIndexPaths:[change deletionsInSection:0]
                         withRowAnimation:UITableViewRowAnimationAutomatic];
        [selfWeak.myTableView insertRowsAtIndexPaths:[change insertionsInSection:0]
                         withRowAnimation:UITableViewRowAnimationAutomatic];
        [selfWeak.myTableView reloadRowsAtIndexPaths:[change modificationsInSection:0]
                         withRowAnimation:UITableViewRowAnimationAutomatic];
        [selfWeak.myTableView endUpdates];
        
    }];

    - (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{
        return self.chatList.count;
    }
    - (UITableViewCell*)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath        *)indexPath{
        SGChatListTableViewCell * cell = [tableView    dequeueReusableCellWithIdentifier:@"SGChatListTableViewCell" forIndexPath:indexPath];
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
        [cell setCellValueWithData:self.chatList[indexPath.row]];
        return cell;
    }

### While show success,but crash when I click a cell.

The crash is  'RLMException', reason: 'Index 18446744073709551615 is out of bounds (must be less than 0)'

Need your help, thank you.

**Comment by kishikawakatsumi** [comment]
@LucasDang Could you please provide more details? `18446744073709551615` means maximum value of `int`. It is used for the expression of `-1` (same meaning as `NotFound`.). We would like to know where the value is generated/passed. 

Where is the line that is crashing?
Can you share the stack trace of the exception?

Also, can you share the code of "click a cell"?  (Probably, `didSelectRowAtIndexPath:`?)

**Comment by LucasDang** [comment]
Yes,I want push to next viewController when i click a cell.

The Code:

    - (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{   
        SHChatMessageViewController *chatView = [[SHChatMessageViewController alloc] init];
        [self.navigationController pushViewController:chatView animated:YES];    
    }

The stack trace:

    *** First throw call stack:
    (
	    0   CoreFoundation                      0x000000010b939b0b __exceptionPreprocess + 171
	    1   libobjc.A.dylib                     0x000000010eff7141 objc_exception_throw + 48
	    2   SGChat_iOS                          0x0000000109bf541c _ZL10throwErrorP8NSString + 652
	    3   SGChat_iOS                          0x0000000109bf1627 _ZL15translateErrorsIZ28-[RLMResults objectAtIndex:]E3$_3EDaOT_P8NSString + 103
	    4   SGChat_iOS                          0x0000000109bf155e -[RLMResults objectAtIndex:] + 110
	    5   SGChat_iOS                          0x0000000109860934 -[SHChatMessageViewController loadMessageData] + 644

Thank you for your reply.

**Comment by kishikawakatsumi** [comment]
@LucasDang According to the stack trace the problem is occurring in `loadMessageData` and the notification block seems not to be relevant.
Could you show me the code of `loadMessageData`?

**Comment by LucasDang** [comment]
I'm so stupid. 
i have found the problem,it's because my error code in method `loadMessageData`.
Thanks a lot.
