### ISSUE TITLE
Client library should give an explicit error message when trying to connect to an older ROS server

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-cocoa#5404]
Client library should give an explicit error message when trying to connect to an older ROS server - right now a 3.0 client trying to connect to ROS v1.x will merely say `Connection closed due to error `:

```
2017-10-17 13:43:39.390878-0700 Teamwork[67339:9493712] Sync: Connection[1]: Writing failed: End of input
2017-10-17 13:43:39.391416-0700 Teamwork[67339:9493712] Sync: Connection[1]: Connection closed due to error
2017-10-17 13:43:40.252205-0700 Teamwork[67339:9493712] Sync: Connection[1]: Connected to endpoint '138.197.205.99:9080' (from '172.20.21.68:63472')
```

It should tell the user it's trying to talk to an older, unsupported (by this version of the client) version and point the product page or docs for upgrade instructions. 

Realm framework version: ? 3.0.0

Realm Object Server version: ? 1.x

Xcode version: ? N/A

iOS/OSX version: ? N/A

Dependency manager + version: ?

**Comment by SiarheiSm** [comment]
trying to connect ROS v1.8.3 with android realm 4.1.0 
```
Connection[1]: Writing failed: End of input 
Connection[1]: Connection closed due to error
Connection[1]: Reconnecting in 472 milliseconds
Connection[1]: Resolving 'ec2-34-215-139-88.us-west-2.compute.amazonaws.com:9080'
Connection[1]: Connecting to endpoint '34.215.139.88:9080' (1/1)
Connection[1]: Connected to endpoint '34.215.139.88:9080' (from '10.0.2.15:35808')
Connection[1]: WebSocket::initiate_client_handshake()
Connection[1]: HTTP request =
                                                              GET /realm-sync/%2F0e38f9551d63d9e08f0d0bf%2Faccount HTTP/1.1
                                                              Authorization: Realm-Access-Token version=1 token="ey.......=="
                                                              Connection: Upgrade
                                                              Host: ec.....us-west-2.compute.amazonaws.com
                                                              Sec-WebSocket-Key: azTr3bmRnl1FbSvLCK0pvA==
                                                              Sec-WebSocket-Protocol: io.realm.sync.22
                                                              Sec-WebSocket-Version: 13
                                                              Upgrade: websocket
```
is it version incompatibility issue as well?

**Comment by nirinchev** [comment]
@SiarheiSm, yes - the [Java changelog](https://github.com/realm/realm-java/blob/master/CHANGELOG.md#breaking-changes) mentions that versions 4.0+ are only compatible with ROS 2.0 and higher.

**Comment by austinzheng** [comment]
In the future, please file Android-related issues against our [Realm Java repository](https://github.com/realm/realm-java/issues). Thanks.

**Comment by austinzheng** [comment]
@dhmspector I did some investigation, and unfortunately the error that results from a Realm 3.* client trying to connect to a ROS 1.* server is not distinctive enough to identify this error case. (It's reported as an "End of input" error, and the error category is not one of the ones recognized by Realm 3, so the error handler ignores it.)
