### ISSUE TITLE
Carthage cannot building scheme for realm with Xcode 9.0.1

### ISSUE THREAD

**Issue by SpriggyDesmond** [realm/realm-cocoa#5406]
Realm framework version: v3.0.0
Xcode version: 9.0.1
iOS/OSX version: Version 10.13
Dependency manager + version: Carthage, tried on 0.24.0 0.25.0 0.26.2

The log is very long
[carthage-xcodebuild.7gVe03.log](https://github.com/realm/realm-cocoa/files/1393734/carthage-xcodebuild.7gVe03.log)

```
realm_coordinator.cpp:170:39: error: reference to non-static member function must be called; did you mean to call it with no arguments?
            if (m_config.sync_config->realm_url != config.sync_config->realm_url) {
                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
                                               ()
/Users/zhongdian/Desktop/Spriggy/pm-app-ios/app/Frameworks/SpriggyFoundation/Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/src/impl/realm_coordinator.cpp:170:72: error: reference to non-static member function must be called; did you mean to call it with no arguments?
            if (m_config.sync_config->realm_url != config.sync_config->realm_url) {
                                                   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
                                                                                ()
2 errors generated.
```

```
The following build commands failed:
	CompileC /Users/zhongdian/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/realm-cocoa/v2.10.1/Build/Intermediates.noindex/Realm.build/Release-iphoneos/Realm.build/Objects-normal/armv7/realm_coordinator.o Realm/ObjectStore/src/impl/realm_coordinator.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by bdash** [comment]
That error indicates that the Git checkout of Realm has a mismatched submodule (that is, the submodule at `Realm/ObjectStore` points to an older version than is expected). I don't know why this would happen as I'd expect Carthage to ensure that the submodules are at the appropriate commits. Can you run `git status` from within `Carthage/Checkouts/realm-cocoa`?

**Comment by SpriggyDesmond** [comment]
We use a separate repo to maintain all the carthage dependencies. It turns out in `Cartfile` we set realm-cocoa to newest but our submodule has the checkout of realm-cocoa v2.10.0, and we ignored the checkout step to make it faster.
