### ISSUE TITLE
How to monitoring save data success?

### ISSUE THREAD

**Issue by FrankSwift** [realm/realm-cocoa#5407]
Sorry about my English.

User *user = [User alloc] init];
user.name = @"user"；
RLMRealm *realm = [RLMRealm defaultRealm];

[realm transactionWithBlock:^{
realm addObject:user];
}];

Now,I want do something when save user finised.
How can l know save user  finished. 
Add notifiction or other good ways?

**Comment by bdash** [comment]
`-[RLMRealm transactionWithBlock:]` executes synchronously. When the write transaction has completed, your subsequent code will be executed..

**Comment by FrankSwift** [comment]
thanks!

**Comment by FrankSwift** [comment]
Anthor quesion:
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
// save some datas to realm
RLMRealm *realm = [RLMRealm defaultRealm];
[realm transactionWithBlock:^{
for(int i = 0; i < 100； i++) {
User *user = [User alloc] init];
user.name =  [NSString stringWithFormat:@"%ld",i];
realm addObject:user];
}];
}
};

Now,I want do something in main thread when save users finised.

**Comment by bdash** [comment]
Depending on what you're trying to accomplish, you could either use one of [Realm's notification mechanisms](https://realm.io/docs/objc/latest/#notifications), or use `dispatch_async` to enqueue a block to be executed on the main queue after your write completes. Note that when using `dispatch_async` for this purpose it may be necessary to call `-[RLMRealm refresh]` to see the changes made during the write transaction as it's possible for the dispatch queue to process the enqueued block before the main thread's Realm automatically refreshes itself to the latest version of the Ream.

Please also keep in mind [the importance of wrapping any work you perform on background threads or queues in autorelease pools](https://realm.io/docs/objc/latest/#threading).

**Comment by FrankSwift** [comment]
Thank u so much
