### ISSUE TITLE
Equal comparisons fail on models containing a list of itself.

### ISSUE THREAD

**Issue by tuacker** [realm/realm-cocoa#5409]
## Goals
I have a `category` model which has a list of subcategories. A subcategory is just a `category` itself. 

```swift
class Category: Object {
  @objc dynamic var name = ""

  let subcategories = List<Category>()
}
```

Comparing the `category` with another query result fails the comparison even though the `categories` are the same.

This issue was introduced with Realm 3.0.0.

## Expected Results
Making an equal comparison between two `categories` that are the same results in true.

## Actual Results
The comparison fails because the `subcategory` list is different every time.

## Steps to Reproduce
```swift
let realm = try! Realm()
let category = Category()
category.name = "category"

try! realm.write { realm.add(category) }

let search = realm.objects(Category.self).filter("name == %@", category.name)
let search2 = realm.objects(Category.self).filter("name == %@", category.name)

print(category)
print(search.first!)
print(search2.first!)

category       == search.first! ? print("We are equal!") : print("Category NOT EQUAL to SEARCH")
search2.first! == search.first! ? print("We are equal!") : print("SEARCH NOT EQUAL to SEARCH2")
```

Results in the following output:
```
Category {
	name = category;
	subcategories = RLMArray<Category> <0x600000306ff0> (
	
	);
}
Category {
	name = category;
	subcategories = RLMArray<Category> <0x600000307350> (
	
	);
}
Category {
	name = category;
	subcategories = RLMArray<Category> <0x600000307500> (
	
	);
}

Category NOT EQUAL to SEARCH
SEARCH NOT EQUAL to SEARCH2
```

## Version of Realm and Tooling

Realm framework version: 3.0.0

Realm Object Server version: None

Xcode version: 9.0 (9A235)

iOS/OSX version: iOS 11

Dependency manager + version: None

**Comment by kishikawakatsumi** [comment]
@tuacker The `==` comparison uses the `isEqual:` method. This works as you would expect if the primary key is set. Otherwise, is just considers the equivalence of the object identity. You can use `isSameObject(as:)` to get what you expected instead.

Please see also: https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Object.swift#L275-L292

**Comment by tuacker** [comment]
Thank you for the explanation, I was not aware of this. I've actually only used `==` comparisons in a couple unit tests so this didn't affect any actual code. `isSameObject(as:)` is gonna be just fine for what I need.
