### ISSUE TITLE
Swift 4 KVO & Realm unmanaged object lead to crash

### ISSUE THREAD

**Issue by timefrancesco** [realm/realm-cocoa#5410]
Here is the steps to replicate the issue:  

* Instantiate a new unmanaged Realm Object 
* Observe some of its properties with KVO
* Trigger the observer (changing one of the observed properties)
* Perform a Realm write transaction for another object of the same type of the first object

Realm will crash with the following error:  
`Object 'NSKVONotifying_RLM:Unmanaged ' has properties that are declared multiple times in its class hierarchy: list of properties'`

 I'm creating a new object and the user will fill the properties and then save it or cancel and exit the screen.  The issue happens when they start filling the fields and then cancel and refresh the page which triggers a server download which retrieves a list of the same object type and store them in the database.  
I cannot use Realm object notifications since it's an unmanaged object and I don't want to write to the DB since the user didn't save it yet and may bail out.  

Note that the properties declared multiple times are not necessarily the one observed, it seems there is no actual correlation between them.  
I'm also invalidating the observers when dismissing the screen.   

The properties are not declared multiple times, and everything works fine if I disable KVO observers.  
## Goals
User Swift 4 KVO to observe an unmanaged Realm object

## Expected Results
It works

## Actual Results 
`Object 'NSKVONotifying_RLM:Unmanaged ' has properties that are declared multiple times in its class hierarchy: list of properties'`

## Steps to Reproduce
* Instantiate a new unmanaged Realm Object 
* Observe some of its properties with KVO
* Trigger the observer (changing one of the observed properties)
* Perform a Realm write transaction for another object of the same type of the first object

## Code Sample
```
 nameObserver = model.observe(\.name) { [weak self] object, _ in
            self?.handleNameChanged(newValue: object.name)
        }
```

## Version of Realm and Tooling

Realm framework version: 2.10.2 & 3.0.0

Realm Object Server version: N/A

Xcode version: 9

iOS/OSX version: iOS 11

Dependency manager + version: Cocoapods 1.2.1

**Comment by tgoyne** [comment]
Creating an instance of `Realm` prior to ever observing any objects should work around this, as that exception is thrown by initialization code that's only run the first time a Realm which may contain that object type is created.

**Comment by timefrancesco** [comment]
Ah yep, makes sense and it actually solve the issue.  
Thank you!
