### ISSUE TITLE
how can I use GeoShape in realm?

### ISSUE THREAD

**Issue by emadhejazian** [realm/realm-cocoa#5413]
I need object model that support these kind of JSON data

"shape": {
		"type": "polygon",
		"coordinates": [[
			[51.373532, 35.73539],
			[51.387216, 35.669966],
			[51.458711, 35.740612],
			[51.373532, 35.73539]
		]]
	}

"location": {
                    "type": "Point",
                    "coordinates": [
                        51.4185269999999974288584780879318714141845703125,
                        35.73472000000000292629920295439660549163818359375
                    ]
                }

**Comment by austinzheng** [comment]
Please review our documentation on [model objects](https://realm.io/docs/objc/latest/#models), especially [supported property types](https://realm.io/docs/objc/latest/#supported-types). Thanks.
