### ISSUE TITLE
Missing primary key exception for object type

### ISSUE THREAD

**Issue by markst** [realm/realm-cocoa#5414]
When creating a Realm object as following:

```swift
realm.create(type(of: object), value: object, update: true)
```

an exception is raised:
```
*** Terminating app due to uncaught exception 'RLMException', reason: ''RLM:Unmanaged Site' does not have a primary key and can not be updated'
```

This appears to be due to `typeName` resolving to "RLM:Unmanaged Site"
```
(lldb) po typeName
"RLM:Unmanaged Site"
```
Which fails lookup in `schema` for identifying `primaryKeyProperty`. 

When adding a breakpoint within `[RLMObjectBase className]`  
The output is as follows:
```
(lldb) po [self className]
Site

(lldb) po className
RLM:Unmanaged Site

(lldb) po [self sharedSchema]
Site {
	id {
		type = string;
		objectClassName = (null);
		linkOriginPropertyName = (null);
		indexed = YES;
		isPrimary = YES;
		array = NO;
		optional = YES;
	}
```

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

/Applications/Xcode.app/Contents/Developer
Xcode 9.0
Build version 9A235

/usr/local/bin/pod
1.4.0.beta.1
Realm (3.0.0)
RealmSwift (3.0.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/bin/git
git version 2.13.5 (Apple Git-94)
```

**Comment by austinzheng** [comment]
Realm automatically creates subclasses for each model object and swizzles the class of any newly-created object to one of these subclasses. Swift's `type(of:)` built-in returns the dynamic type of the object, hence it returns the name of the unmanaged subclass instead of the expected base class.

The fact that the internals are looking up the schema based on the subclass name is an oversight in our code and I'll fix it. In the meantime you can work around this by explicitly specifying the type object rather than using `type(of:)`.

**Comment by markst** [comment]
@austinzheng thanks for the response. I'm afraid the solution advised is simply not possible. I've rolled back to `2.10.2` until this is resolved.

**Comment by markst** [comment]
Since I'm using generics, I've also tried the following:
```swift
self.create(T.self, value: object, update: true)
```

But unfortunately typeName resolves to `RealmSwiftObject`:
```
(lldb) po type
RealmSwift.Object

(lldb) po typeName
"RealmSwiftObject"
```

**Comment by markst** [comment]
☝🏾 think that's actually my drama. since further up the chain I'm casting my generic protocol type to `Object.Type`. which is actually the reason for using dynamic `type(of:)`. 

Thanks for the fix @austinzheng

**Comment by austinzheng** [comment]
I'm glad it worked, and thank you for reporting this bug! I've added some unit tests so hopefully it won't show up again once we fix it...

**Comment by markst** [comment]
@austinzheng how might I use a pre-release Realm?

I've tried:
```
pod 'RealmSwift', :git => 'git@github.com:realm/realm-cocoa.git', commit: '457e1f8ec7b466fe823e15f01d2a78cf8d570486'
```

but CocoaPods fails due to:
```
   
   ERROR: One of Realm's submodules is missing!
   
   If you're using Realm and/or RealmSwift from a git branch, please add 'submodules: true' to
   their entries in your Podfile.
   
```

**Comment by austinzheng** [comment]
You need to add `'submodules: true` to that line as one of the arguments.
