### ISSUE TITLE
Generic Types not accepted anymore

### ISSUE THREAD

**Issue by jpChan015** [realm/realm-cocoa#5415]
## Issue
In RealmSwift 2.10.0, generic types was accepted in the code below but after updating the pods to 3.0.0 it produced a _**"Cannot convert value of type 'T' to expected argument type 'Object'"**_ error. And once I cast it, it has an error of _**"Could not cast value of type 'RealmSwift.Results<RealmSwift.Object>' (0x101f8cbb8) to 'RealmSwift.Results<Project.Project>' (0x101f8cd90)."**_

## Code Sample
```
class func createUpdate<T>(records: List<T>) {
        let realm = try! Realm()
        try! realm.write {
            for item in records {
                realm.add(item, update: true)
            }
        }
}
```

## Version of Realm and Tooling
Realm framework version: 3.0.0

Xcode version: 9.0

iOS/OSX version: 11

Dependency manager + version: Cocoapods 1.3.1

**Comment by kishikawakatsumi** [comment]
@jpChan015 It looks like that code should be `createUpdate<T: Object>` instead of `createUpdate<T>`. I do not know why `createUpdate<T>` could be compiled, but it seems correct that `createUpdate<T>` will produce a compile error.

```
class func createUpdate<T: Object>(records: List<T>) {
    let realm = try! Realm()
    try! realm.write {
        for item in records {
            realm.add(item, update: true)
        }
    }
}
```
