### ISSUE TITLE
Throwing error after adding new libraries e.g. Firebase/Core

### ISSUE THREAD

**Issue by smalam119** [realm/realm-cocoa#5417]
I am doing a project on Swift 3 and using RealmSwift 2.9.1 . It was working fine until I added some new libraries e.g. Firebase/Core through pod. It is now throwing some error:
**Use of undeclared identifier 'source_shared_group**
**Use of undeclared identifier 'find_container_column**

Can anyone please provide some urgent help?

**Comment by kishikawakatsumi** [comment]
Can you try to clean build after deleting `derivedData`? Or deintegrate all pods and re-install pods? Or can you make sure it reproduces in another clean project from scratch?

See more details https://realm.io/docs/swift/latest/#cocoapods

I believe something wrong your setup. If the problem won't be fixed, please send the project to be reproduced to `help@realm.io`.

**Comment by smalam119** [comment]
I will try all the things you have mentioned and come back. Thanks a lot.

**Comment by smalam119** [comment]
Actually updating Realm to 3.0.0 fixes the problem. Thanks.
