### ISSUE TITLE
No such module 'RealmSwift'

### ISSUE THREAD

**Issue by FredyBellidoTenorio** [realm/realm-cocoa#5418]
When I compile in Test I always get this result "No such module 'RealmSwift'".

I have the following in the podfile.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
# ignore all warnings from all pods
inhibit_all_warnings!

target 'App' do
   use_frameworks!
    pod 'RealmSwift'
    pod 'Fabric', '~> 1.6.3'
    pod 'Answers', '~> 1.3.5'
    pod 'DropDown', '~> 2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # or '3.0'
    end
  end
end
```

I've tried it and I'm still getting the same result.

```
pod --version
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
```
I have also deleted the "Pods" folder of my project, the file "Podfile. lock" and the "App. xcworkspace" and then I run pod install.

I'm working with Xcode 8.3.3 and Swift 3

![captura de pantalla 2017-10-19 a las 11 45 32](https://user-images.githubusercontent.com/7362951/31910794-e8da2f50-b83e-11e7-9c70-32b7a15bae6b.png)

**Comment by tgoyne** [comment]
You have not added the `RealmSwift` pod to your test target. With recent versions of cocoapods, this is done by inheriting the search paths from the app:

```ruby
target 'App' do
  # ...
  target 'AppTests' do
    inherit! :search_paths
  end
end
```

**Comment by guoyingtao** [comment]
I have the similar problem.
I'm working with Xcode 9.0.1 and Swift 4

**Comment by FredyBellidoTenorio** [comment]
I had to add to the test targets:

  target' AppTests' do
    inherit! : search_paths
  end

The "@testable import App" must be included in each Test file (which corresponds to the name of the main Target)

The Test file MUST NOT include any files (in the target membership) that are not Test files.

**Comment by austinzheng** [comment]
Please file a new ticket if you have an issue.
