### ISSUE TITLE
Realm v3.0.0 does not compile in debug configuration

### ISSUE THREAD

**Issue by eliburke** [realm/realm-cocoa#5419]
This works: `carthage update --no-use-binaries --platform iOS realm-cocoa`
This fails: `carthage update --no-use-binaries --platform iOS --configuration Debug realm-cocoa`

XCode's log file has the error:
````
"/var/folders/t_/m9rfl27527756l3j41hnjsm40000gn/T/carthage-xcodebuild.bK4qjL.log" 2299L, 1067961C
ld: bitcode bundle could not be generated because 'core/librealm-ios-dbg.a(bptree.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
````

I cannot rule out the possibility that this is the fault of Carthage or XCode, but I typically build debug frameworks and this has worked up until now, through v2.10.2

## Version of Realm and Tooling

Realm framework version: v3.0.0

Realm Object Server version: ?

Xcode version: 9.0.1

iOS/OSX version: targeting 10.2 and up

Dependency manager + version: Carthage 0.26.2

**Comment by tgoyne** [comment]
We exclude bitcode from the prebuilt core library (because it'd double the size of the download and isn't used for anything for builds not submitted to the app store), but Carthage passes `BITCODE_GENERATION_MODE=bitcode` to xcodebuild, overriding what we have set in the project. There may be some way to make it not do this, but I don't know the details of how to configure Carthage.

**Comment by eliburke** [comment]
I'm passingly familiar with the issue, but I have to admit I don't understand the specific problem here. I'm not using your prebuilt binary, I'm building locally. 

Are you saying that Carthage overrides the BITCODE_GENERATION flag when it is building Realm-Swift, but does not override it for Realm/ObjectStore, and it is because of how you have the build files set up for your binary artifacts? Is this something that could be solved by adding another Configuration?

**Comment by austinzheng** [comment]
Sorry for the delayed response. We make a distinction between the prebuilt Realm Objective-C or Realm Swift binding framework, and the prebuilt binary for the underlying database engine which is a dependency of the binding. The latter is always prebuilt without bitcode whether or not you build either of the Cocoa bindings from source, and is what's causing the error message you're seeing. So the resolution to the problem still lies in somehow convincing Carthage to build the project without bitcode. Unfortunately I don't know enough about how Carthage works internally to point you in the right direction; perhaps their help channels may be more useful.
