### ISSUE TITLE
Realm crash: 'Object type 'RLM:Unmanaged <...>' is not managed by the Realm

### ISSUE THREAD

**Issue by SticklyMan** [realm/realm-cocoa#5422]
## Goals
After upgrading to RealmSwift 3.0.0, I started getting this crash in previously working code. The gist of it is that I have a static method on a parent model class whose purpose is to provide the next auto-increment id of any sub-model. The first time it is accessed for a given sub-model, Realm must be queried to find the current maximum id.

Since this is called in a static context by many sub-models, I have to use dynamic typing. So, I pass 'self' as the type of object to query. See code sample below for more details.

## Expected Results
From a static context, ```realm.objects(self)``` should resolve the type as ```ProjectName.SubObject.Type```, which should behave the same as manually specifying ```realm.objects(ProjectName.SubObject.self)```

## Actual Results
Realm appears to treat the dynamic type 'self' as an Unmanaged object, and the following error occurs:
```
po realm.objects(SubObject.self)
Results<SubObject> <0x11be81d20> (

)
```
```
po realm.objects(self)
error: Execution was interrupted, reason: breakpoint 2.1.
The process has been returned to the state before expression evaluation.
```

**Error:**
```2017-10-23 22:08:59.235366-0600 Project Dev[792:555411] *** Terminating app due to uncaught exception 'RLMException', reason: 'Object type 'RLM:Unmanaged SubObject' is not managed by the Realm. If using a custom `objectClasses` / `objectTypes` array in your configuration, add `RLM:Unmanaged SubObject` to the list of `objectClasses` / `objectTypes`.'```

## Steps to Reproduce
Hopefully the code below is enough to reproduce. I have stripped quite a bit out of it and made some names generic, but am happy to provide more context if this doesn't trigger it.

## Code Sample
```
class ParentObject: Object {
    @objc dynamic var id: Int = 0
    override static func primaryKey() -> String? {
        return "id"
    }

    private static var nextId: [String: Int] = [:]
    static func getNextId() -> Int {
        let className = self.className()
        if nextId[className] == nil {
            let realm = try! Realm(configuration: Config.defaultRealm)
            let maxId: Int? = realm.objects(self).max(ofProperty: "id")
            nextId[className] = max(0, maxId ?? 0)
        }
        nextId[className] = nextId[className]! + 1
        return nextId[className]!
    }

    convenience init(someOption: Bool) {
        self.init()
        self.id = type(of: self).getNextId()
    }
}

class SubObject: ParentObject {
    convenience init(someOption: Bool) {
        self.init(someOption: someOption)
    }
}

func codeThatTriggersIt() {
    let obj = SubObject(someOption: false)
}
```

Alternately, getNextId() could be stripped down to:
```
    static func getNextId() -> Int {
        let realm = try! Realm(configuration: Config.defaultRealm)
        let maxId: Int? = realm.objects(self).max(ofProperty: "id")
        return (maxId ?? 0) + 1
    }
```

## Version of Realm and Tooling

**Realm framework version:** 3.0.0

**Realm Object Server version:** 3.0.0

**Xcode version:** 9.0.1

**iOS/OSX version:** Mac OS X 10.13. Targeting min: iOS 9.0, testing with iOS 11.0.3

**Dependency manager + version:** CocoaPods 1.4.0.beta.1

**Comment by tgoyne** [comment]
This is probably a duplicate of #5414, which we're working on fixing.

**Comment by SticklyMan** [comment]
Yup, that seems to be the case- apologies for missing that issue in my cursory search. I can confirm that PR #5421 resolves my issue. Thanks!
