### ISSUE TITLE
App Crash on Launch After Updating Realm from 2.10.2 to 3.0.0

### ISSUE THREAD

**Issue by kumarc-123** [realm/realm-cocoa#5423]
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM insertObject:atIndex (inlove) : index 20 beyond bounds [0 .. 18]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b06b1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010a9d5f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b0aae8c _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010af9a733 -[__NSArrayM insertObject:atIndex (inlove) + 1299
	4   Realm                               0x00000001077c8300 _ZZ46+[RLMObjectSchema propertiesForClass (idea) sSwift (inlove) ENK3$_1clEP11RLMPropertyl + 288
	5   Realm                               0x00000001077c6ae3 +[RLMObjectSchema propertiesForClass (idea) sSwift (inlove) + 4115
	6   Realm                               0x00000001077c414d +[RLMObjectSchema schemaForObjectClass (inlove) + 941
	7   Realm                               0x0000000107938e5b _ZL16RLMRegisterClassP10objc_class + 299
	8   Realm                               0x000000010793a1bd __25+[RLMSchema sharedSchema]_block_invoke + 77
	9   CoreFoundation                      0x000000010afeff72 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock (inlove) + 226
	10  Realm                               0x0000000107939e74 +[RLMSchema sharedSchema] + 1044
	11  Realm                               0x000000010791665b +[RLMRealm realmWithConfiguration:error (inlove) + 5627
	12  RealmSwift                          0x00000001082988f2 _T0So8RLMRealmCABSo0A13ConfigurationC13configuration_tKcfCTO + 162
	13  RealmSwift                          0x000000010829908b _T010RealmSwift0A0CA2C13ConfigurationV13configuration_tKcfc + 923
	14  RealmSwift                          0x0000000108298c59 _T010RealmSwift0A0CA2C13ConfigurationV13configuration_tKcfC + 681
	15  eCustoms Œ±                         0x00000001057f6f62 _T00013eCustoms__yxg15DatabaseManagerC20setupMasterDataRealm33_DA8624FE7A2806B35CA7F0347E9FDA04LLyyF + 3026
	16  eCustoms Œ±                         0x00000001057f637a _T00013eCustoms__yxg15DatabaseManagerCACyc33_DA8624FE7A2806B35CA7F0347E9FDA04Llfc + 1066
	17  eCustoms Œ±                         0x00000001057f575a _T00013eCustoms__yxg15DatabaseManagerCACyc33_DA8624FE7A2806B35CA7F0347E9FDA04LlfC + 42
	18  eCustoms Œ±                         0x00000001057f5714 globalinit_33_DA8624FE7A2806B35CA7F0347E9FDA04_func0 + 20
	19  libdispatch.dylib                   0x000000010cb5443c _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000010cb559c7 dispatch_once_f + 297
	21  eCustoms Œ±                         0x00000001057f5794 _T00013eCustoms__yxg15DatabaseManagerC6GlobalACfau + 36
	22  eCustoms Œ±                         0x00000001058e1ed6 _T00013eCustoms__yxg14AccountManagerCACyc33_F845380C86A3C08A86FA951134509462Llfc + 598
	23  eCustoms Œ±                         0x00000001058e154a _T00013eCustoms__yxg14AccountManagerCACyc33_F845380C86A3C08A86FA951134509462LlfC + 42
	24  eCustoms Œ±                         0x00000001058e1504 globalinit_33_F845380C86A3C08A86FA951134509462_func0 + 20
	25  libdispatch.dylib                   0x000000010cb5443c _dispatch_client_callout + 8
	26  libdispatch.dylib                   0x000000010cb559c7 dispatch_once_f + 297
	27  eCustoms Œ±                         0x00000001058e1584 _T00013eCustoms__yxg14AccountManagerC6GlobalACfau + 36
	28  eCustoms Œ±                         0x0000000105a5a75d _T00013eCustoms__yxg18HomeViewControllerC18checkAccountSTatusyyF + 29
	29  eCustoms Œ±                         0x0000000105a5a561 _T00013eCustoms__yxg18HomeViewControllerC11viewDidLoadyyF + 2721
	30  eCustoms Œ±                         0x0000000105a5a724 _T00013eCustoms__yxg18HomeViewControllerC11viewDidLoadyyFTo + 36
	31  UIKit                               0x0000000108893d51 -[UIViewController loadViewIfRequired] + 1235
	32  UIKit                               0x00000001088db4dc -[UINavigationController _updateScrollViewFromViewController:toViewController (inlove) + 68
	33  UIKit                               0x00000001088db818 -[UINavigationController _startTransition:fromViewController:toViewController (inlove) + 153
	34  UIKit                               0x00000001088dc92f -[UINavigationController _startDeferredTransitionIfNeeded (inlove) + 841
	35  UIKit                               0x00000001088ddb90 -[UINavigationController __viewWillLayoutSubviews] + 115
	36  UIKit                               0x0000000108b342ae -[UILayoutContainerView layoutSubviews] + 231
	37  UIKit                               0x00000001087c4551 -[UIView(CALayerDelegate) layoutSublayersOfLayer (inlove) + 1331
	38  QuartzCore                          0x00000001124b04ba -[CALayer layoutSublayers] + 153
	39  QuartzCore                          0x00000001124b45a9 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	40  QuartzCore                          0x000000011243d1cd _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 365
	41  QuartzCore                          0x0000000112468ae4 _ZN2CA11Transaction6commitEv + 500
	42  UIKit                               0x0000000108711706 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 141
	43  CoreFoundation                      0x000000010b00e20c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	44  CoreFoundation                      0x000000010aff2a3b __CFRunLoopDoBlocks + 203
	45  CoreFoundation                      0x000000010aff2214 __CFRunLoopRun + 1300
	46  CoreFoundation                      0x000000010aff1a89 CFRunLoopRunSpecific + 409
	47  GraphicsServices                    0x0000000110fcf9c6 GSEventRunModal + 62
	48  UIKit                               0x00000001086f5d30 UIApplicationMain + 159
	49  eCustoms Œ±                         0x000000010588b1e7 main + 55
	50  libdyld.dylib                       0x000000010cbd0d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by alexandremorgado** [comment]
I was experiencing the same problem here. Then I discovered that there was a 'let' property on my model that was not set to 'ignoredProperties', which did not cause problens in previous versions, but it seems is a problem on Realm 3.0.0.

**Comment by staticdreams** [comment]
I'm getting the same issue only my "`reason:" '*** -[__NSArrayM insertObject:atIndex:]: index 1 beyond bounds for empty array'`.
Prior upgrading to 3.0 everything worked fine

**Comment by kumarc-123** [comment]
I was able to resolve this issue. The problem was that for one model class I did not set the property as @objc and for another class I did not add dynamic to one field. After adding @objc and dynamic the crash didn't happen.

Hope it helps others as well.

Thanks.
