### ISSUE TITLE
Updating an object by assigning new boolean value crashes the app

### ISSUE THREAD

**Issue by danielstorch** [realm/realm-cocoa#5424]
## Goals
Im trying to update an boolean value of my realm object. This im doing by getting the object by the primary key and changing the value. Than writing the object to the DB. But when assigning the boolean value, the app crashes.

## Expected Results
App not crashing when i assigning the new value..

## Actual Results
Error message is not very long...
`libc++abi.dylib: terminating with uncaught exception of type NSException`

## Code Sample

Code that crashes:

```
static func toggleIsSelectedStateForCatId(_ id: Int){
        
        let realm = RealmManager.realm()

        guard let newsCategory = realm.object(ofType: NewsCategory.self, forPrimaryKey: id) else {
            return
        }
        
         //Here the crash happens...
        newsCategory.isSelected = !newsCategory.isSelected
        
        try! realm.write {
            realm.add(newsCategory, update: true)
        }
    }
```

Than i tried this and it works:

```
static func toggleIsSelectedStateForCatId(_ id: Int){ 
        let realm = RealmManager.realm()
        guard let newsCategory = realm.object(ofType: NewsCategory.self, forPrimaryKey: id)else {
            return
        }
        
        try! realm.write {
            newsCategory.isSelected = !newsCategory.isSelected
        }
    }
```

The problem with the second code snippet is that the observer will not be invoked. From my understanding is because of the missing `update: true` parameter

In some other class...

```
token = RealmManager.realm().objects(NewsCategory.self).observe({ changes in
            self.tableView.reloadData()
        })
```

What am i missing?

## Version of Realm and Tooling

Realm framework version: 3.0

Xcode version: 9

iOS/OSX version: iOS 11

**Comment by austinzheng** [comment]
Since your `newsCategory` is a managed object (an object representing data inside the database), you have to make any changes to its property values within the context of a write transaction, so the behavior you are seeing is expected.

Can you elaborate about your observer being invoked? Is this a KVO observer, a Swift `didSet`/`willSet`block, or a Realm notification?

**Comment by danielstorch** [comment]
Ok, thanks for the explantation. The observer is a Realm notification. Before the update to realm 3.0 everything worked fine. But now it won't trigger the observer anymore when changing the realm object like this:

```
try! realm.write {
            newsCategory.isSelected = !newsCategory.isSelected
        }
```

Observer code

```
class NewsTableViewController: UITableViewController{
    
    var token: NotificationToken?
  
    override func viewDidLoad() {
        super.viewDidLoad()
       
        token = RealmManager.realm().objects(NewsCategory.self).observe({ changes in
             //Not triggered!
            self.tableView.reloadData()
        })
    }
}
```

**Comment by austinzheng** [comment]
I built a simple sample app to try replicating this problem, but could not.

In your `NewsCategory` model, did you declare the model using `@objcMembers` or declare all your properties with `@objc`? Can you paste the definition of your model object?

**Comment by danielstorch** [comment]
I declared them with `@objc`

Here the model

```
class NewsCategory: Object, Mappable {

    @objc dynamic var term_taxonomy_id: String?
    @objc dynamic var category_parent: String?
    @objc dynamic var count: String?
    @objc dynamic var parent: String?
    @objc dynamic var cat_name: String?
    @objc dynamic var category_nicename: String?
    @objc dynamic var slug: String?
    @objc dynamic var term_group: String?
    @objc dynamic var category_count: String?
    @objc dynamic var category_description: String?
    @objc dynamic var taxonomy: String?
    @objc dynamic var term_id: String?
    @objc dynamic var name: String?
    @objc dynamic var cat_ID: Int = 0
    
    @objc dynamic var isSelected: Bool = false

    override static func primaryKey() -> String? {
        return "cat_ID"
    }
}
```

**Comment by austinzheng** [comment]
Can you build a simple reproduction case and send it to us? There's nothing obviously incorrect about what you're doing but I still can't replicate the problem based on your instructions.

**Comment by danielstorch** [comment]
Sorry for the long wait. I extracted the crucial part out of our app into a new project. Since the app is using some private API, i created a private repository and invited you to the it. There is a issue describing the problem.

**Comment by bdash** [comment]
As an FYI, @austinzheng is on vacation at the moment.

**Comment by danielstorch** [comment]
OK, thanks for the notification. How long will he be gone? We want to release the app soon and this is a stopper for us. Or maybe someone else could look into the issue?

**Comment by bdash** [comment]
He'll be back on Wednesday. If you'd like to invite me to the repository containing the repro case I may be able to take a look prior to then.

**Comment by danielstorch** [comment]
Waiting until Wednesday should be fine. I still invited you, if you have time and want to take a look.

**Comment by austinzheng** [comment]
I took a preliminary look and commented on the issue you opened in the private repo. You're welcome to continue the conversation either here or there, whichever you prefer.
