### ISSUE TITLE
realm List<T> is not persistent after app relaunch 

### ISSUE THREAD

**Issue by athemer** [realm/realm-cocoa#5426]
## Goals
I need to save search history,
When user tapped on a search result, 
I insert realm model at index 0 into a List property in an realm object.

the realm model class is as the following 

```
class CompanySearchResultListModel: Object {
    
    dynamic var id: String = ""
    let companyModelSearchResult_List = List<CompanyModel>()

    required convenience init?(map: Map) {
        self.init()
    }
    override static func primaryKey() -> String {
        return "id"
    }
}
```

## Expected Results

I expect that every time I launch the app and read from realm,
The search history will be there.

## Actual Results

So I checked realm browser, it works fine when I insert model at 0 into List<T>.
And yet, when I relaunch the app, the List<T> got cleared and have 0 model inside.

## Steps to Reproduce

Every time I relaunch the app, the models in List<T> will no longer be there.

## Code Sample

this is how I insert model into List
`self.companySearchResultListModelManager.insert(object: self.companySearchResultListModel, objToInsert: companyModel)`

and 

```
public func insert(object: Object?, objToInsert: Object) {
        if let obj = object as? CompanySearchResultListModel{
            var realm: Realm?
            do {
                realm = try Realm()
            } catch(let e) {
                print("Create Realm error: \(e)")
            }
            if let realm = realm {
               guard let insert = objToInsert as? CompanyModel else { return }
                
                realm.beginWrite()
                obj.companyModelSearchResult_List.insert(insert, at: 0)
                
                do {
                    try realm.commitWrite()
                } catch (let e) {
                    print("Realm Committing write cause the error: \(e)")
                }
            }
        }
    }
```

I checked issue #4740 

But it's not helping.

Also, I don't know if this mattes but I am using default realm config

`var configuration = Realm.Configuration.defaultConfiguration
        configuration.schemaVersion = 29
        Realm.Configuration.defaultConfiguration = configuration`

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: ?

Xcode version: 9

iOS/OSX version:  iOS 11 / OSX 10.12.6 

Dependency manager + version: cocoapods

**Comment by austinzheng** [comment]
Can you make a small project that reproduces this bug, then send it to us? Nothing in your code stands out as incorrect.

**Comment by kishikawakatsumi** [comment]
Closing due to no response. Feel free to reopen you have further information.
