### ISSUE TITLE
LinkingObjects items are not equal to the "original" Objects

### ISSUE THREAD

**Issue by joaocolaco** [realm/realm-cocoa#5427]
## Goals
Compare two Realm Objects. One from a search/filter result, another from LinkingObjects.

## Expected Results
That they are equal when are the same.

## Actual Results

The comparison is false. Also the memory address from them are different. However they are from the same realm, on the same thread and have the same data.
This issue started with Realm 3.0.0

## Steps to Reproduce

If I get a LinkingObjects item from an object that belongs to another, the latter is different from the  LinkingObjects item.
 
## Code Sample
Here goes a Swift Playground with a demonstration of the issue.

```
import Foundation
import RealmSwift

//define the objects
//The db will have owners that can have multiple cars. From the cars we can have the owner using LinkingObjects

class Person: Object {
    @objc dynamic var name = ""
    let cars = List<Car>()

    override var description: String { return "Person {\(name)}" }
}

class Car: Object {
    @objc dynamic var brand = ""

    let owners = LinkingObjects(fromType: Person.self, property: "cars")
    override var description: String { return "Car {\(brand)}" }
}

//Create a realm
let realm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "TemporaryRealm"))

//create a car
let car = Car(value: ["brand": "BMW"])

// Create a person called Jennifer
let owner = Person()
owner.name = "Jennifer"

//she gets the car
owner.cars.append(objectsIn: [car])


//write the objects
try! realm.write {
    realm.add(owner)
}

//Now we will get the owner back from the realm, its car.
//From the car we will the owner back and compare it with the original

let favorites = ["Jennifer"]

//get Jeniffer back from Realm
let favoritePerson = realm.objects(Person.self)
    .filter("name IN %@", favorites)

//first instance of Jeniffer
if let firstJennifer = favoritePerson.first  {
    firstJennifer
    
    //a Jennifer car
    if let car = firstJennifer.cars.first  {
        car.brand
        
        //get the car owner from LinkingObjects. Should be Jennifer again.
        if let secondJennifer = car.owners.first {
            secondJennifer
            
            //But they are different!!
            firstJennifer == secondJennifer
        }
    }
}

try! realm.write {
    realm.deleteAll()
}
```

## Version of Realm and Tooling

Realm framework version: 3.0.0

Xcode version: 9.0.1

iOS/OSX version: 10.13

**Comment by tgoyne** [comment]
3.0 changed the behavior of the equality operator on `Object` to comply with Foundation's requirement that objects which compare equal have the same hash. We now only override it for classes which have a primary key (as was already done in obj-c for RLMObject). You can use `Object.isSameObject(as:)` to perform the same check as `Object`'s equality operator did in 2.x.

**Comment by joaocolaco** [comment]
Thanks, I didn't notice Object.isSameObject(as:).
