### ISSUE TITLE
I got an error when I installing Realm use Carthage

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-cocoa#5429]
@jiangshang0514 commented on [Thu Oct 26 2017](https://github.com/realm/realm-dotnet/issues/1606)

 I got an error when I installing Realm use Carthage 

Xcode version is 9.0.1 , Carthage version is 0.26.2 ,carthage file: github "realm/realm-cocoa" , run "carthage update --platform ios" ,then I got an error : "
*** Skipped installing realm-cocoa.framework binary due to the error: "Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65.2 clang-900.0.37)."
"

## Version of Realm and Tooling

- Realm Object Server Version: v3.0.1
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?
- Xcode Version:9.0.1
- Carthage Version:0.26.2 

---

@jiangshang0514 commented on [Thu Oct 26 2017](https://github.com/realm/realm-dotnet/issues/1606#issuecomment-339546384)

This is the success？

---

@nirinchev commented on [Thu Oct 26 2017](https://github.com/realm/realm-dotnet/issues/1606#issuecomment-339588336)

This repo contains the code and issues for the .NET SDK. It seems you're interested in the Swift/Obj C SDK, so I'll move your issue to https://github.com/realm/realm-cocoa.

**Comment by austinzheng** [comment]
Hi @jiangshang0514. Are you _actually_ experiencing an error, or are you just concerned about the error mismatch? If Carthage can't use the framework because of a version mismatch, it will log an error message and then build from source, which is not actually a problem.

**Comment by jiangshang0514** [comment]
@austinzheng ,thanks for your help,my program can be built in xcode, realm can also be used normally,I just concerned about this error message will produce unknown problems.
现在realm可以正常使用，除了这个，没有发现什么提示错误的地方。我只是担心抛出这个信息会不会产生一些我不知道的问题。

**Comment by bdash** [comment]
As @austinzheng mentioned, the "Skipped installing realm-cocoa.framework binary" message isn't as scary as it sounds. Carthage falls back to building the frameworks from source in this case. This is expected and correct.
