### ISSUE TITLE
Data race inThread Sanitizer

### ISSUE THREAD

**Issue by a-25** [realm/realm-cocoa#5430]
Hello. I suspect I experience a bug with realm multithreading. Or maybe I lack some experience to protect from such cases. Could you point out where the problem is?

## Goals

I want to create several dispatch queues that are reading from database simultaneously.

## Expected Results

I expect that everything is working without crashes.

## Actual Results

When I use "Thread Sanitizer" instrument it reports about data race between threads.

## Steps to Reproduce

Just put the code below in the app delegate "application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?)" method.
The data race will happen in "first" method invocation. Rarely it occurs on realm.object(ofType:) method invocation.

## Code Sample

    let dispatchQueue = DispatchQueue(label: "Test.Queue”, qos: .utility, attributes: .concurrent)
    let productId = "00000002-0000-0000-0000-000000000000"
    let cityId = "00000002-0000-0000-0000-000000000000"
       
    for i in 0...1000 {
           dispatchQueue.async {
               let realm = try! Realm()
               let product = realm.object(ofType: ProductObjectModel.self, forPrimaryKey: productId)!
               let test = product.productCityList.filter({
		$0.city!.id == cityId
              }).first
          }
    }

    class ProductObjectModel: Object {
        dynamic var id = ""
        var productCityList = List<ProductCityObjectModel>()
    
        override static func primaryKey() -> String? {
            return "id"
        }
    }

ProductCityObjectModel is also an Object (in my opinion it does not matter what should be put there).

## Version of Realm and Tooling

Realm framework version: 2.10.2 (latest of 2.x RealmSwift available)

Realm Object Server version: None

Xcode version: 9.0

iOS/OSX version: 10.3

Dependency manager + version: None

**Comment by austinzheng** [comment]
It's highly unlikely that this is a problem with Realm, given your test case. Can you provide the output of running tsan here so we can investigate further?

**Comment by a-25** [comment]
Hello. Sorry for being late.
I made a test project using only code I posted, and it works while my real project fails every time. I guess that something could be with using Realm.List.filter method and so on (this method moves internal array pointer while list is being read from another thread). 
Could you provide how should I wrap getters to realm lists to be thread-safe?

**Comment by bdash** [comment]
Can you share the Thread Sanitizer output so we have some idea what the purported race is?

**Comment by a-25** [comment]
Hello.
I was able to fix it using Realm 3x version. Now it does not crash there.
