### ISSUE TITLE
Bug: Calling refresh does not fire all awaiting notifications on realm

### ISSUE THREAD

**Issue by hhanesand** [realm/realm-cocoa#5432]
## Goals
I want to make sure all notifications have been fired before starting a write transaction. I do this by calling `refresh` on the realm before I start the transaction.
I do this because we have other listeners that need to create thread safe references before the transaction starts, in order to avoid the crash seen in the stack trace.

## Expected Results
All notification blocks should be executed before the write transaction starts.

## Actual Results
Notification block does not get called until I open the realm.
Stack trace :
https://gist.github.com/hhanesand/e3933371d5648ae03e436a3b1925b557

Here is my code in the `writeTransactionWithDefaultRealm` method :
```objectivec
@autoreleasepool {
    RLMRealm *realm = [self openRealm];

    if (realm.inWriteTransaction) {
        safe_block(block, realm);
        return safe_block(completion);
    }

    // Fire any notifications waiting before we start a write tranaction
    [realm refresh];

    NSError *error = nil;

    [realm transactionWithBlock:^{
        safe_block(block, realm);
    } error:&error];

    if (error) {
        NSLog(@"Warning : realm write error : %@", error);
    }

    safe_block(completion);
}
```

Here is the code that observes the notificaiton :
https://gist.github.com/hhanesand/50eb99d56c5dc4694b84a774e06a2c59

`startCreatingTasksForOperationType` in the above sample is called on the main thread on near app startup.

## Steps to Reproduce
1. Open realm
2. Call refresh, expecting notifications to fire
3. Start write transaction, notification fires

I can only reproduce this intermittently, so could this be a race somewhere?

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

/Applications/Xcode-9.0.1.app/Contents/Developer
Xcode 9.0.1
Build version 9A1004

/Users/xxx/.rbenv/shims/pod
1.3.1
Realm (2.10.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)


(not in use here)

/usr/local/bin/git
git version 2.14.2
```

**Comment by tgoyne** [comment]
If you are performing writes on other threads, then one may occur in between the call to `refresh` and the call to `transactionWithBlock` and beginning the write transaction will send a notification.

**Comment by hhanesand** [comment]
Hmm, ok. This is the only method that opens a realm in my app. I will see if it is called on a background thread somewhere.

**Comment by hhanesand** [comment]
I have changed the queue I am scheduling realm reads and writes on to a serial queue, and that seems to have fixed the issue.

@tgoyne This isn't really the optimal solution in the long term, since reads should be able to happen concurrently. Dispatching writes as `dispatch_barrier_async`, and reads as `dispatch_async` should also work without running into the threading issue correct?
