### ISSUE TITLE
I can't install 'RealmSwift' pod

### ISSUE THREAD

**Issue by mo3bius** [realm/realm-cocoa#5434]
Hi, I'm trying to install 'RealmSwift', '~> 3.0.1'  pod but the installation lasts infinitely. 
I thought it was a cocoapods problem but if I try to install another pod as alamofire works perfectly.
if I try to do the verbose of the installation hangs in this point:
` > Running prepare command $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: sync 2.1.0`

I have cocoapods-1.3.1 and Xcode 9.0.1

**Comment by moppymopperson** [comment]
I'm having the same problem now. Were you able to solve this somehow?
