### ISSUE TITLE
realm not created upon migration (needed) if deleteRealmIfMigrationNeeded=true with non-default fileURL

### ISSUE THREAD

**Issue by kajensen** [realm/realm-cocoa#5435]
## Goals
Delete the realm that needs migration and create an empty one with new schema at the specified custom fileURL.

## Expected Results
Create an empty realm db with new schema at fileURL.

## Actual Results
The realm is deleted, but a new one is not created. Error (code 5) upon 
```
try? Realm()
```
"'<custom_file_url_path>/default.realm' does not exist."

## Steps to Reproduce
Create a realm that needs migration. Use configuration options:

```
let fileURL = FileManager.default
    .containerURL(forSecurityApplicationGroupIdentifier: "MyAppGroup")!
    .appendingPathComponent("Library/Caches/default.realm")
let configuration = Realm.Configuration(fileURL: fileURL,
schemaVersion: 2,
migrationBlock: { (migration, schemaVersion) in
    //
},
deleteRealmIfMigrationNeeded: true)

Realm.Configuration.default = configuration
```

## Code Sample
N/A

## Version of Realm and Tooling
Realm framework version: 3.0.0

Realm Object Server version: N/A

Xcode version: 9.0

iOS/OSX version: macOS 10.12

Dependency manager + version: Cocoapods 1.3.1

**Comment by bdash** [comment]
Does the directory in which the Realm file lives exist? Realm doesn’t create intermediate directories, so you’ll see an error like this if the parent directory does not exist.

**Comment by kajensen** [comment]
Yeah, I can still see the realm.default.lock and default.realm.management folder.

I'm not sure if this matters, but I guess I didnt specify- this is with a macOS application.

**Comment by austinzheng** [comment]
I tried building a simple macOS repro case but couldn't get this behavior to trigger. Might you have a repro case we can look at? It's possible there's some subtlety of behavior that my repro case is missing that makes a difference.

**Comment by tulaibpirzada** [comment]
I also faced that issue, this was because I had realm browser opened at that time due to which new realm file was not being created after deletion. As soon as I closed the realm browser and re-run the app. It worked fine!!

**Comment by bmunkholm** [comment]
Will close due to lacking repro case. 
Please reopen when/if you can provide more details.
