### ISSUE TITLE
Class does not conform "Encodable" while using List<String> in swift 4.0

### ISSUE THREAD

**Issue by magic3584** [realm/realm-cocoa#5437]
## Goals
Using Codable and Realm in swift 4.0 with List\<String\>

## Actual Results
Type 'News' does not conform to protocol 'Encodable'

## Code Sample
    class News: Object, Codable {
        var pictureList = List<String>()

        private enum CodingKeys: String, CodingKey {
            case  pictureList       
        }

        public required convenience init(from decoder: Decoder) throws {      
            self.init()
        
            let container = try decoder.container(keyedBy: CodingKeys.self)

            let pictures = try container.decodeIfPresent([String].self, forKey: .pictureList) ?? [""]
            pictureList = List(pictures)
        }
    }

JSON is like

    {
        "pictureList": [ 
            "String 1",
            "String 2",
            "String 3"
         ]
    }

## Version of Realm and Tooling

Realm framework version:  3.0.1

Xcode version: Version 9.0.1 (9A1004)

iOS/OSX version: iOS 10.0

Is it possible in this way? If not, is there any other way to meet my goal?

Thanks~

**Comment by kishikawakatsumi** [comment]
@magic3584 `Codable` is defined as `typealias Codable = Decodable & Encodable`, so you should implement `encode(to encoder: Encoder)` method to conform `Codable` protocol. Or you can 
 conform `Decodable` if you do not need to encode Realm object to another format.

Also, assigning `List` property doesn't work. `List` properties should be declared `let`. So you can only `append`/`remove` objects to it/


```
class News: Object, Decodable {
    let pictureList = List<String>()

    private enum CodingKeys: String, CodingKey {
        case  pictureList
    }

    public required convenience init(from decoder: Decoder) throws {
        self.init()

        let container = try decoder.container(keyedBy: CodingKeys.self)

        let pictures = try container.decodeIfPresent([String].self, forKey: .pictureList) ?? [""]
        pictureList.append(objectsIn: pictures)
    }
}
```

**Comment by magic3584** [comment]
@kishikawakatsumi I added a compute [String] property with only **get** ,and a String property to save to Realm, but it's a little more ugly, your solution is perfect! 
Thanks ~

**Comment by magic3584** [comment]
Is it possible meet the goal without the func **init(from decoder: ) throws** because I have to write a few codes like **property = try container.decodeIfPresent()**

**Comment by kishikawakatsumi** [comment]
@magic3584 Currently, no. Compiler code generation support of Codable protocol works only a class has non-argument initializer (`init()`). Realm Object cannot be initialized by `init()`.

**Comment by magic3584** [comment]
@kishikawakatsumi  I have ask on stackoverflow [https://stackoverflow.com/questions/47031302/how-to-conform-to-codable-and-using-realm-in-swift-4-when-class-has-a-array-of-s](url) 
So the answer is no?

**Comment by kishikawakatsumi** [comment]
@magic3584 No. You should write mapping code in `required convenience init(from decoder: Decoder) throws` yourself. Compiler code generation doesn't work.

**Comment by magic3584** [comment]
@kishikawakatsumi Got it, thanks~

**Comment by sa7bi** [comment]
Hi,
I have basically the same issue with `List<CustomObject>`. My xcode project doesn't compile and gives me this error: `Unit.swift:27:6: Cannot automatically synthesize 'Encodable' because 'List<Test>' does not conform to 'Encodable'`
More info here [StackOverflow: List is not conforming to Encodable
](https://stackoverflow.com/questions/48619049/list-is-not-conforming-to-encodable)
