### ISSUE TITLE
what should to do after rename a model property?

### ISSUE THREAD

**Issue by czjeep** [realm/realm-cocoa#5438]
## Version of Realm and Tooling

Realm framework version: realmswift3.0.0

Realm Object Server version: ?

Xcode version: xcode9,swift3.2

iOS/OSX version: ?

Dependency manager + version: pod 1.1.1

**Comment by czjeep** [comment]
after I update my Xcode from 8.* to Xcode9.*,I have to update realmSwift From 2.* to 3.0.0 under swift3.2, and there are some change have to do. one is I have to change some realm model's property name like "newRegistWithFCode", I change it to "newregistWithFCode" and build and run successful. now the "newregistWithFCode" schemaVersion is 22, but i don't know "newRegistWithFCode" is what schemaVersion，what should i do to migrate the data?

**Comment by austinzheng** [comment]
We have [extensive documentation on migrations](https://realm.io/docs/objc/latest/#migrations). Please read through it.

**Comment by czjeep** [comment]
i read this before. in rename function, the from name seen to must be exist, but the case is i forget the version this property begin. i mean if there is a old version have't the property, this rename migration would cause crash.

**Comment by austinzheng** [comment]
I see what you're trying to do.

The migration block takes two arguments. The first of the two arguments is a `Migration` object. It has `oldSchema` and `newSchema` properties, corresponding to the old and new schemas.

Each schema value has an `objectSchema` property, which is a Swift array of `ObjectSchema` values describing a single model. Each `ObjectSchema` in turn has a `properties` array of `Property` values describing each property on a given model. Finally, each `Property` has a number of properties describing it, including a `name` string property.

If you don't know what schema version you changed the property, your migration block can examine the old schema and check to see if the property you're looking for exists as the old version or the new version. Here's some simple sample code, assuming your class is named `MyClass`:

```swift
var config = Realm.Configuration.defaultConfiguration
config.schemaVersion = // (your new schema version)

config.migrationBlock = { oldRealm, newRealm in
    let oldObjectSchema = oldRealm.oldSchema.objectSchema

    // Find the the object schema for "MyClass".
    guard let index = oldObjectSchema.index(where: { $0.className == "MyClass" }) else {
        // The old schema doesn't contain "MyClass", stop.
        return
    }
    let myClassObjectSchema = oldObjectSchema[index]

    // Now look for a property named "newRegistWithFCode"
    let propertyExists = myClassObjectSchema.properties.index(where: { $0.name == "newRegistWithFCode" }) != nil
    // If propertyExists == true, there is a property on MyClass called newRegistWithFCode and we can rename it
    // Otherwise, if it's false, there's no such property.
    // ...
}
```

Hope this helps, please let us know if you have more questions!

**Comment by bdash** [comment]
I think the typical approach would be to check the old schema version number, and if you're updating from a version that _didn't_ have the property that is being renamed you'd do something different than if you're updating from a version that _does_ have the property.

**Comment by austinzheng** [comment]
That would be the preferred approach; I think in this case the user doesn't actually know what their old schema number is.

**Comment by yuldong** [comment]
@austinzheng the approach is work for me.
 If I know the schema version I changed the property, is there anyother  preferred approach ?

**Comment by austinzheng** [comment]
If you know the schema version, you can just check the version number passed into the block (I edited my code sample above, since the argument names were incorrect). If the version number is before the version where you changed the property, you can update it in the block. If it's after, you don't need to do anything.

**Comment by czjeep** [comment]
@austinzheng your advice work for me, thank you
