### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2

### ISSUE THREAD

**Issue by frankxzx** [realm/realm-cocoa#5442]
install realm with carthage, in Xcode 9.1

**Comment by akhilvarma8** [comment]
Same issue here after updating to Xcode 9.1, Installed Realm through Dynamic Framework.

**Comment by james-rantmedia** [comment]
Did you use Carthage's `--no-use-binaries` options to build from source?

**Comment by akhilvarma8** [comment]
I guess we need to deal with this until Swift ABI becomes stable. I'll wait for Realm team to update the binaries. Thanks.

**Comment by james-rantmedia** [comment]
Unfortunately, yeah.

**Comment by austinzheng** [comment]
This is the correct answer. We can only provide one version's prebuilt binary for Carthage, so someone is always going to have to build from source.

**Comment by Coolncamp** [comment]
carthage update --platform iOS --no-use-binaries

**Comment by dunqi** [comment]
Yeah - have the same issue with Xcode 9.1 - thanks for the info, that I can build it from source

**Comment by amirpervaiz086** [comment]
guys, I compiled latest from source code and uploaded here https://github.com/amirpervaiz086/Realm-swift-4.0.2
