### ISSUE TITLE
Realm in Swift 4.0.1 ?

### ISSUE THREAD

**Issue by carlchungrekki** [realm/realm-cocoa#5443]
## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Sorry, what is the question here?

**Comment by v-andr** [comment]
in swift 4.0.2 (which has been just released together with the new xcode 9.1) the module RealmSwift doesn't seem to work

**Comment by frankxzx** [comment]
@v-andr same issue

**Comment by v-andr** [comment]
anyway it was already mentioned here https://github.com/realm/realm-cocoa/issues/5442
either rebuilding manually or downgrading the swift version manually (using external toolchain)

**Comment by austinzheng** [comment]
I'm assuming everyone here is seeing the carthage message in the above linked issue. If there is a different problem please open a new ticket, making sure to fill out the Issue Template.
