### ISSUE TITLE
How to define List-in-List via Swift

### ISSUE THREAD

**Issue by akring** [realm/realm-cocoa#5445]
I use Realm with ObjectMapper, and now I got some JSON data like :

```json
{
    "objects": [
        [
            {
                "value1": "1",
                "value2": "2"
            }, {
                "value1": "1",
                "value2": "2"
            }
        ]
    ]
}
```

I know how to define a `List<Object>` to parse and store a list, but How can I define the `List in List` struct in my model ?

**Comment by austinzheng** [comment]
Define a wrapper `Object` containing one property: the inner `List`, and then have an outer `List` containing those objects.

**Comment by akring** [comment]
Thanks for the reply !

As I mentioned before, I'm using realm with ObjectMapper, so another problem is how to define the `outer list`, because it doesn't have any key in the JSON data, so I can't write the map code
```swift
someObject                <- map["jsonObjects"]
```

**Comment by austinzheng** [comment]
You may want to check out the [ObjectMapper project](https://github.com/Hearst-DD/ObjectMapper) and see what help channels they offer, and whether they can answer your question.

**Comment by akring** [comment]
OK, thank you for reply.
