### ISSUE TITLE
How to migrate multiple realm files in one App

### ISSUE THREAD

**Issue by magic3584** [realm/realm-cocoa#5448]
Sorry to open this issue, but I got a little trouble when migrate multiple realm files in one App.

[Question on stackOverFlow](https://stackoverflow.com/questions/47070443/how-to-migrate-multiple-realm-files-in-one-app)

Realm framework version:  3.0.1

Xcode version: 9.1

iOS/OSX version: iOS 10

Thanks

**Comment by austinzheng** [comment]
Please see the answer to your SO question.
