### ISSUE TITLE
Cannot modify managed objects outside of a write transaction in write block.

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#5453]
@xxKRASHxx commented on [Mon Nov 06 2017](https://github.com/realm/realm-object-server/issues/300)

## Goals

Observe changes and make side effects on a ROS

## Expected Results

Change Realm Object property

## Actual Results

Error: Cannot modify managed objects outside of a write transaction.
at Realm.change.realm.write

## Steps to Reproduce
Subscribe on change event in ROS and try make changes on changed object.

## Code Sample
```
observe(change: Realm.Sync.ChangeEvent) {

let perform = (change: Realm.Sync.ChangeEvent, changed: Movie) => {
            try {
                change.realm.write(() => {
                    changed.status = 'processing'
                })
            } catch (e) {
                console.log("Error on creation" + e)
            }
        }

    let allMovies = change.realm.objects('Movie')    as Realm.Results<Movie>
    perform(change, allMovies[0])
}
```
## Version of Realm and Tooling

- Realm Object Server Version: 2.0.13
- Flavor:
  - [ ] Developer
  - [x] Professional
  - [ ] Enterprise

---

@bigfish24 commented on [Mon Nov 06 2017](https://github.com/realm/realm-object-server/issues/300#issuecomment-342199354)

moving this to `realm-cocoa` since it is an SDK issue not the server

**Comment by tgoyne** [comment]
That code is TypeScript, not Swift.

**Comment by bigfish24** [comment]
Issue moved to [realm/realm-js #1471](https://github.com/realm/realm-js/issues/1471) via [**ZenHub**](https://www.zenhub.com/)
