### ISSUE TITLE
Crash: terminating with uncaught exception of type realm::LogicError: Bad version number

### ISSUE THREAD

**Issue by hhanesand** [realm/realm-cocoa#5455]
Realm crashes after calling refresh : `libc++abi.dylib: terminating with uncaught exception of type realm::LogicError: Bad version number`

https://gist.github.com/hhanesand/e5f8fe16c9bd70e3bb4a852705eeaeb7

shareMultitrack:toGroups:
https://gist.github.com/hhanesand/b15c2fecd65e6da95e038d038ed685ec

writeTransactionWithDefaultRealm:completion:
https://gist.github.com/hhanesand/d3bf5c87b0a925f4e4cbab48d0d5e4e4

I am happy to send entire project over via email, but other than that I don't have any more information.

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

/Applications/Xcode-9.0.1.app/Contents/Developer
Xcode 9.0.1
Build version 9A1004

/Users/hhanesand/.rbenv/shims/pod
1.3.1
Realm (3.0.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)


(not in use here)

/usr/local/bin/git
git version 2.15.0
```

**Comment by austinzheng** [comment]
Is the problem consistently reproduceable? If you could send the reproduction case to help@realm.io we'd be happy to investigate it.

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
