### ISSUE TITLE
Deep copying of nested objects?

### ISSUE THREAD

**Issue by hendyevan** [realm/realm-cocoa#5460]
## Goals

To know why List<T: Object>: ListBase changes to List<Element: RealmCollectionValue>: ListBase

## Expected Results

Element are type of Object

## Actual Results

Element are not type of Object

## Steps to Reproduce

Im using workaround from https://github.com/realm/realm-cocoa/issues/3381#issuecomment-256243390

## Code Sample

protocol DetachableObject: AnyObject {
    
    func detached() -> Self
    
}

extension Object: DetachableObject {
    
    func detached() -> Self {
        let detached = type(of: self).init()
        for property in objectSchema.properties {
            guard let value = value(forKey: property.name) else { continue }
            if let detachable = value as? DetachableObject {
                detached.setValue(detachable.detached(), forKey: property.name)
            } else {
                detached.setValue(value, forKey: property.name)
            }
        }
        return detached
    }
    
}

extension List: DetachableObject {
    
    func detached() -> List<Element> {
        let result = List<Element>()
        forEach {
            result.append($0.detached())
        }
        return result
    }
    
}

## Version of Realm and Tooling

Realm framework version: 3.0.1

Realm Object Server version: ?

Xcode version: 9.1

iOS/OSX version: High Sierra

Dependency manager + version: ?

**Comment by austinzheng** [comment]
It's different because we changed the API in Swift 3. A different user reported success with a [modified approach](https://github.com/realm/realm-cocoa/issues/5433#issuecomment-340138315), although I can't officially endorse his code or promise that this behavior will work.

**Comment by hendyevan** [comment]
Hi @austinzheng thanks for your feedback. I will try that [modified approach](https://github.com/realm/realm-cocoa/issues/5433#issuecomment-340138315).
