### ISSUE TITLE
How to get latest Realm Mobile Platform data?

### ISSUE THREAD

**Issue by cp3hnu** [realm/realm-cocoa#5461]
In my App I can watch how rows get deleted, modified and created when I log in with a Sync User, like it is getting synced slowly, when I login my app I would like to know when this sync ends, or better, get only the latest data at once and not the whole history of it.
I don't know if is a setting in Realm Object Server (Ubuntu) or in my App (iOS Swift)

The problem is also on https://stackoverflow.com/questions/40751931/how-to-get-latest-rmp-data?answertab=oldest#tab-top

Have you solved the problem already？

**Comment by bdash** [comment]
After logging in a sync user, use [`Realm.asyncOpen(configuration:callbackQueue:callback:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:ZFC10RealmSwift5Realm9asyncOpenFT13configurationVS0_13Configuration13callbackQueueCSo13DispatchQueue8callbackFTGSqS0__GSqPs5Error___T__T_) to open the Realm. The callback will be called, and the Realm instance provided to you, only after the local Realm has been brought up to date with the server.

Alternatively, you can use [`Realm.init(configuration:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5RealmcFzT13configurationVS0_13Configuration_S0_) to open the Realm in the usual fashion, and then use [`SyncSession.addProgressNotification(for:mode:block:)`](https://realm.io/docs/swift/latest/api/Extensions/SyncSession.html#/s:FE10RealmSwiftCSo14RLMSyncSession23addProgressNotificationFT3forOES_S0_17ProgressDirection4modeOES_S0_12ProgressMode5blockFVES_S0_8ProgressT__GSqCSo28RLMProgressNotificationToken_)  with a mode of `.forCurrentlyOutstandingWork` to get progress updates you can use to display some form of progress UI while the local Realm is brought up to date with the data on the server.

**Comment by cp3hnu** [comment]
Thank you for your help
