### ISSUE TITLE
'binding_callback_thread_observer.hpp' file not found

### ISSUE THREAD

**Issue by xxrForIOS** [realm/realm-cocoa#5468]
`pod 'Realm'`
pods version 1.4.0.beta.2

get error 
'binding_callback_thread_observer.hpp' file not found

in fact,has binding_callback_thread_observer.cpp

good days

## Version of Realm and Tooling

Realm framework version: 3.0.2

Realm Object Server version: ?

Xcode version: 9.0

iOS/OSX version: 11/10.13.1

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Can you try the CocoaPods troubleshooting instructions at [this link](https://realm.io/docs/objc/latest/#cocoapods), and report back if that doesn't fix your issue?
