### ISSUE TITLE
RealmOptional - value(forKey:) returns number value, not object reference

### ISSUE THREAD

**Issue by Alarson93** [realm/realm-cocoa#5469]
I'm in a bit of a pickle. I had built out a workaround for detachable objects/copies in issue #5433.

This seemed to be working correctly, however I realized I forgot to add support for RealmOptionals (int, double, etc). I figured this would be a simple enough matter - I could use the same approach I used for Lists. I can use value(forKey:) on a List and be returned the List's reference (so I can do things like append).

However, when I used value(forKey:) on RealmOptional - I get the number that is stored in the optional instead of a reference to the optional itself. This means I cannot do something like:

let myValue = myObject.value(forKey: "myRealmOptional")
myValue.value = 5

This is problematic for me. Is there any way that I can get the reference to a RealmOptional instead of the value it contains?

Thank you!

**Comment by tgoyne** [comment]
`myObject.setValue(5, forKey: "myRealmOptional")` is supported for `RealmOptional` properties. When using KVC a `RealmOptional<Int>` property tries to behave like a `Int?` one would.

**Comment by Alarson93** [comment]
That doesn't seem to be working for me. Here is the exact code I am working with:

```
class MyObject: Object {
    let myRealmOptional = RealmOptional<Int>()
}
```

```
let myObject = MyObject()
myObject.setValue(5, forKey: "myRealmOptional")
```

Printing out myObject.myRealmOptional.value returns nil.

**Comment by kishikawakatsumi** [comment]
I tried to run your code sample, but I cannot reproduce the issue.

```
let myObject = MyObject()
myObject.setValue(5, forKey: "myRealmOptional")

print(myObject.myRealmOptional.value) // Optional(5)
```

It also isn't reproduced regardless an object is managed or not. 

Could you please share a complete executable reproducible Xcode project for investigation? @Alarson93

**Comment by Alarson93** [comment]
Aha! After starting a clean project I can confirm it works. I have also narrowed down where the problem comes in. It seems that when I use EVReflection (specifically the Realm extension of it) the issue appears.

So, it would appear that this is not a Realm issue but an issue introduced by another library. 

I appreciate your help :)
I will work with the EVR dev in order to get this resolved!

**Comment by allenhumphreys** [comment]
@Alarson93 Was EVReflection responsible for your issues in #5433 as well? I ask because I am not experiencing that issue, and I'm curious as to why.

**Comment by Alarson93** [comment]
@allenhumphreys The answer appears to be yes!

However, while using setValueForKey on lists (in the detachable method from #5433) works - it is dangerous because the list would be passed by reference. We need a list that contains elements no managed by Realm.
