### ISSUE TITLE
Cannot create asynchronous query while in a write transaction

### ISSUE THREAD

**Issue by AyeChanPyaeSone** [realm/realm-cocoa#5470]
*** Terminating app due to uncaught exception 'realm::InvalidTransactionException', reason: 'Cannot create asynchronous query while in a write transaction'

## Goals
I want to check whether there are changes in Post objects, if there are i would like to reload my data. 

## Expected Results
Table reload and data refreshed. 

## Actual Results
<img width="1242" alt="screen shot 2017-11-12 at 5 36 06 pm" src="https://user-images.githubusercontent.com/8436265/32697632-02c5c226-c7d0-11e7-8dae-573538f908f2.png">

## Steps to Reproduce
I am not sure when does it happen. I saw them in crash logs. 

## Code Sample
**ListingVC viewdidload**

```
self.notification = [[Post allObjects] addNotificationBlock:^(RLMResults *data, RLMCollectionChange *changes, NSError *error) {
        if (error)
        {
            NSLog(@"Failed to open Realm on background worker: %@", error);
            return;
        }
        
        UITableView *tv;
        
        if (weakSelf.isSearchMode)
        {
           tv = weakSelf.searchDisplayController.searchResultsTableView;
        }
        else
        {
             tv = weakSelf.tblListing;
        }
    
        // Initial run of the query will pass nil for the change information
        if (!changes)
        {
            [tv reloadData];
            return;
        }
        
        [weakSelf updateArray];
        
    }];

```

## Version of Realm and Tooling

Realm framework version: 3.0.2

Xcode version:8.3.3

iOS version: 11.0.3

**Comment by austinzheng** [comment]
Can you show us the code for the `updateArray` method you're calling?

**Comment by AyeChanPyaeSone** [comment]
Here. I just reloading the tableview. 

```
- (void)updateArray{
    
    if (self.isSearchMode) {
        [self.searchDisplayController.searchResultsTableView reloadData];
    } else {
        [self.tblListing reloadData];
    }
}
```

**Comment by kishikawakatsumi** [comment]
The error message says adding notification block within a write transaction. Could you make sure not to call `-[RLMRealm beginWriteTransaction:]` or enclosing `-[RLMRealm transactionWithBlock:]` that method?

Also, you seem different version of Realm. `RLMResults.mm:427` is not `addNotificationBlock:` and so on. Can you please confirm what version of Realm are you using? @AyeChanPyaeSone

**Comment by bdash** [comment]
Closing due to the lack of further information. Feel free to reopen this if you're still in need of assistance and are able to provide the requested information.
