### ISSUE TITLE
Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'

### ISSUE THREAD

**Issue by ikyh** [realm/realm-cocoa#5472]
Please help me with this [question.](https://stackoverflow.com/questions/47264246/rlmexception-attempting-to-modify-object-outside-of-a-write-transaction-sw). I have tried hard but did not get any solution. Please help!

**Comment by austinzheng** [comment]
You can't modify a managed object outside of a write transaction. In the code sample in the SO question you linked, if you set `users.messageSenderNumber` or any other property on `users` when `users` is already in a Realm, you will get a crash. Just move all the code that sets properties on Realm objects into the write transaction and the problem should go away.

**Comment by ikyh** [comment]
@austinzheng Hello. Thanks a lot for reply. I have tried that as well. I just moved setting values code in realm.write {}  block, But then I got primaryKey error. "user with primary key already exist". Can you please explain in SO what is wrong and what is to be done. Please!!

**Comment by austinzheng** [comment]
Please review [our documentation](https://realm.io/docs/swift/latest/). Doing so would have answered both of your SO questions. as well as the one you have right now.

**Comment by ikyh** [comment]
After I tried as u suggested I got this error, `Primary key can't be changed after an object is inserted`. I have to add messages to database and then show them in tableView. My primary key is `messageSenderNumber`. I am getting this error as soon as user sends another message. If I close the app and when I send the message then it works. It should be real-time
