### ISSUE TITLE
Submitting Issue - crash

### ISSUE THREAD

**Issue by cityinthepark** [realm/realm-cocoa#5477]
## Goals

Submit my iOS app to App Store

## Expected Results

Archiving the app, upload to App Store. (Realm was ok when developing the app. It runs with no issue at all. The app runs on both simulator and real device perfectly.)

## Actual Results

At Archiving stage, start to have issue about Realm. Get "/Frameworks/Realm.framework: unknown error -1=ffffffffffffffff
Command /bin/sh failed with exit code 1"

## Steps to Reproduce

Nothing special. My app was building totally fine, no issues. Then cleaned and tried to Archive it. Started to report same thing over and over for Realm.framework: unknown error -1

I've tried many times to uninstall and reinstall Realm on Cocoapod, by both way: 

## Code Sample
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master',     submodules: true
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch =>     'master', submodules: true
(This way gives me Realm 3.0.2 and RealmSwift 3.0.2)

and:
pod 'Realm'
pod 'RealmSwift'
(This way gives me Realm 2.9.1 and RealmSwift 2.9.1)

I also tried the way to download latest Realm package and drag and drop the frameworks from latest version, which is Realm 3.0.2. Also copied the Run Script: 

bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh"

I tried both Swift-4.0 and Swift-4.0.2 version, none worked.

Now still have the same error, and I don't know where to go. Please help me with this issue, as my app is ready to submit for the store. I hope to make it before Christmas. 

Thanks a lot!!
Joyce 

Realm framework version: 3.0.2

Realm Object Server version: n/a

Xcode version: ?9.1

iOS/OSX version: 11

Dependency manager + version: n/a

**Comment by kishikawakatsumi** [comment]
@cityinthepark Could you send us `help@realm.io` your project? Archiving issue is not difficult but debugging remotely is very hard. We keep your project completely private.

**Comment by cityinthepark** [comment]
OK. Please do keep my work secure. Will you please delete it right after solve the problem?

And which folder should I send? The root folder of the whole project? Or some subfolder of it? Right now the zip file is 138mb.

Thanks a lot!

**Comment by cityinthepark** [comment]
Oh I've solved the issue. 

By doing this:
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose

**Comment by kishikawakatsumi** [comment]
@cityinthepark We keep your project secure. Also, will delete it right after solving the problem.

We need a reproducible case. So please send the root folder of the whole project. Probably a mail server cannot receive 138MB zip file. Can you upload it to cloud storage like google drive and let us know share URL?

**Comment by kishikawakatsumi** [comment]
@cityinthepark Sounds good.
