### ISSUE TITLE
Xcode is crashing on Realm migration

### ISSUE THREAD

**Issue by msamoylov** [realm/realm-cocoa#5479]
## Goals

Run and debug my app.

## Expected Results

A running app with the migrated realm.

## Actual Results

Xcode crashes http://take.ms/yeHzS

## Steps to Reproduce

Create a macOS app and try to modify its schema. 

Running the app against the previous Realm schema crashes Xcode immediately. It's crashing with both synchronous and asynchronous access to Realm.

I think I should mention that my initial schema was created with Realm v2.

## Code Sample

```
import Foundation
import RealmSwift

func handleMigrations() {
    let config = Realm.Configuration(schemaVersion: 1, migrationBlock: { migration, oldSchemaVersion in

        if oldSchemaVersion < 1 {
            migration.renameProperty(onType: Exercise.className(), from: "typical_set", to: "baseSet")
        }
    })

    Realm.asyncOpen(configuration: config) { realm, error in
        if let realm = realm {
        } else if let error = error {
            // Handle error that occurred while opening the Realm
        }
    }
}
```

## Version of Realm and Tooling

Realm framework version: 3.0.2

Xcode version: 9.1 (9B55)

OSX version: 10.13.1 (17B48)

Dependency manager + version: CocoaPods 1.3.1

**Comment by msamoylov** [comment]
Update: Xcode is crashing even without trying to alter the schema, but just trying run the app against the old realm.

**Comment by kubatruhlar** [comment]
@msamoylov Did you solve that? Same version, when migration is needed, Xcode crashes.

**Comment by msamoylov** [comment]
@kubatruhlar I didn't solve that really. Somehow it just stopped crashing, no idea why.

**Comment by simonbromberg** [comment]
Still happening for me. Sure the simulator app could crash, but doesn't make sense that Xcode should crash. Not even getting a "Problem Report", Xcode just closes unexpectedly.

**Comment by jekirl** [comment]
Facing the same problem with RealmSwift. Extremely frustrating.

**Comment by bdash** [comment]
If Xcode is crashing, file a bug report with Apple about it. It's not possible for us to fix bugs in Xcode.
