### ISSUE TITLE
deleteAllObjects is not working 100%

### ISSUE THREAD

**Issue by magen** [realm/realm-cocoa#5485]
## Goals
I am trying to delete all values from my default Realm object!

## Expected Results
All tables need to be empty

## Actual Results
It's not delete 100% of the times.

## Steps to Reproduce
Just calling the method

## Code Sample
        [[RLMRealm defaultRealm] transactionWithBlock:^{
            [[RLMRealm defaultRealm] deleteAllObjects];
            GRLogInfo(@"Logout >>>>> defaultRealm removed");
        }];

## Version of Realm and Tooling
  - Realm (2.10.1):

Xcode version: 8.3.3

iOS/OSX version: 11.0

I am trying to understand what are the reasons that can cause such thing?  and when it's happen, how i can know what is the reason that it's not delete? 
BTW: if i am working on the DB on different thread? maybe this can cause such issue?

**Comment by bdash** [comment]
How are you determining that the database is not empty after calling `-[RLMRealm deleteAllObjects]`?

**Comment by magen** [comment]
i am opening the database with Realm Browser and i can see some values.

i saw this [issue](https://github.com/realm/realm-cocoa/issues/1974) and i am thinking to change 

    [[RLMRealm defaultRealm] transactionWithBlock:^{
        [[RLMRealm defaultRealm] deleteAllObjects];
        GRLogInfo(@"Logout >>>>> defaultRealm removed");
    }];
with:

```
RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[realm deleteAllObjects];
[realm commitWriteTransaction];

```

**Comment by kishikawakatsumi** [comment]
@magen The two code is exactly the same. Can you make sure `NSLog(@"%@", [YourModel allObjects]);` returning empty results or not instead using Realm Browser? Like the following:

```
[[RLMRealm defaultRealm] transactionWithBlock:^{
    [[RLMRealm defaultRealm] deleteAllObjects];
    GRLogInfo(@"Logout >>>>> defaultRealm removed");
}];

NSLog(@"%@", [YourModel allObjects]);
````

**Comment by 0xdatou** [comment]
@kishikawakatsumi  Why Realm Browser can't 100% determining it?

**Comment by kishikawakatsumi** [comment]
@0xdatou There is no problem in Realm Browser. But we can not make sure that you open the correct file. For example, you may open a different file. We just say a reliable method to isolate the problem.

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
