### ISSUE TITLE
Supporting Auto Type-casting during RLMObject Creation

### ISSUE THREAD

**Issue by jeancky** [realm/realm-cocoa#5486]
## Goals

Here is our Class definition:
```
@interface OScoreModel : RLMObject

@property   NSInteger   score;
@property   NSString*   from;

@end
```

We want to create a object from the JSON string. It maybe mix int with string, such as 0 and '0' for score property.

So, That will be nice if RLMObject can provide some sort of switch property to turn on the auto-cast feature.

## Expected Results
When the JSON string is 
`{"score":'0', "from":"school"}`

Realm can provide something like 
`"+ (NSArray<NSString *> *)autoCastProperties
{
       return @[@"score"];
}
;" `

then the creation won't crash.
 
## Actual Results

it crashed with "Invalid value '0' for type xxxx"

## Code Sample
Here is our Code now, as you can see, It's very ugly and not robust. 

```
- (instancetype)initWithValue:(id)value schema:(RLMSchema *)schema {
    
    if ([value isKindOfClass:[NSDictionary class]] && [self.class respondsToSelector:@selector(sharedSchema)]){
        NSMutableDictionary* mDict = [value mutableCopy];
        RLMObjectSchema * schema = [self.class performSelector:@selector(sharedSchema)];
        
        [mDict enumerateKeysAndObjectsUsingBlock:^(id  _Nonnull key, id  _Nonnull obj, BOOL * _Nonnull stop) {
            if (![key isEqualToString:kModelTypeNSString]){
                RLMPropertyType type = [schema objectForKeyedSubscript:key].type;
                if ([obj isKindOfClass:NSString.class]){
                    switch (type) {
                        case RLMPropertyTypeInt:
                        case RLMPropertyTypeBool:
                            [mDict setObject:@([obj intValue]) forKey:key];
                            break;
                        case RLMPropertyTypeFloat:
                        case RLMPropertyTypeDouble:
                            [mDict setObject:@([obj doubleValue]) forKey:key];
                            break;
                        default:
                            break;
                    }
                    
                }else if ([obj isKindOfClass:NSNumber.class]){
                    if (type == RLMPropertyTypeString){
                        [mDict setObject:[obj stringValue] forKey:key];
                    }
                }
            }
        }];
        value = mDict;
    }
    return [super initWithValue:value];
}
```

## Version of Realm and Tooling

Realm framework version: ?
  Realm Object-c 3.0.1  

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@jeancky Auto type-casting in library side is not a good idea. Also, `String` to `Int` isn't type-casting, it's conversion. There is always a chance of failure, and how to convert is not obvious. It is necessary to judge on a case-by-case basis for each application how to handle a failure case or how to convert it.
