### ISSUE TITLE
Openning encrypted realm created using NOT iOS Realm SDK

### ISSUE THREAD

**Issue by GrigoryUlanov** [realm/realm-cocoa#5488]
I want to use pre-filled encrypted realm db in my iOS Application. I tried to put it in Bundle and then to read it. It works well if I will use NOT encrypted realm DB, but if I use encrypted app can't open realm.

I tried to create pre-filled encrypted realm db using my own Mac app and using node.js sdk. In both cases iOS app can't open and decrypt realm. Without encryption everything works perfect.

If then I will try to open this realm file using Realm browser everything will open! I am sure that realm is encrypted, because Realm Browser asks me for the key. I entered it and it works.

What is interesting is that encrypted realm is easily can be read by simulator but not the real device.

## Goals
To make Swift Realm working with encrypted realm files created using not iOS sdk.

## Actual Results
Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/containers/Bundle/Application/73CBF3CD-1E1E-4C7B-85E3-607D20217DCC/app-app.app/config.realm': Realm file decryption failed." UserInfo={Error Code=2, NSFilePath=/var/containers/Bundle/Application/73CBF3CD-1E1E-4C7B-85E3-607D20217DCC/app-app.app/config.realm, Underlying=Realm file decryption failed, NSLocalizedDescription=Unable to open a realm at path '/var/containers/Bundle/Application/73CBF3CD-1E1E-4C7B-85E3-607D20217DCC/app-app.app/config.realm': Realm file decryption failed.}

## Code Sample
```
let encryptionConfig = Realm.Configuration(
            fileURL: pathToRealmInBundle,
            encryptionKey: encryptionKey,
            readOnly: true,
            objectTypes: [
                ...
            ]
        )
        guard let realm = try? Realm(configuration: encryptionConfig) else {
            print("Fail")
            return nil
        }
```

## Version of Realm and Tooling
Realm framework version: 3.0.2

Xcode version: Version 9.1 (9B55)

iOS/OSX version: 
iPhone 6 iOS 11.1.2

Dependency manager + version: 
Pod 1.3.1

**Comment by kishikawakatsumi** [comment]
@GrigoryUlanov It seems that the 1encryptionKey1 parameter is not specified in 1encryptionConfig`. Is the code you shared correct?

**Comment by GrigoryUlanov** [comment]
@kishikawakatsumi, thank you! You are right!
I forgot to include it here.
I have updated the question.

But I had a mistake only in issue description. In code everything was correct, but still not working

**Comment by GrigoryUlanov** [comment]
@kishikawakatsumi, @jpsim

**Comment by GrigoryUlanov** [comment]
@kishikawakatsumi, @jpsim 
Hello!
Do you have any ideas. I will be really glad if you will help me with this.

I spend today a whole  day looking for a solution. But without results. All code with encryption works on simulator but not works on real devices. 

I only understand that it fails inside group.hpp while calling open func inside `inline Group::Group(const std::string& file, const char* key, OpenMode mode)`

**Comment by GrigoryUlanov** [comment]
I'm sure it should be a bug inside the ios realm (

**Comment by kishikawakatsumi** [comment]
@GrigoryUlanov We cannot reproduce the issue. Can you share the reproduction case? If you'd like to keep private your code, please send it to `help@realm.io`.

**Comment by GrigoryUlanov** [comment]
@mikeartfay 

Unfortunately, I haven't found a solution. I've decided to encrypt realm myself without the realm api.

**Comment by bmunkholm** [comment]
From https://github.com/realm/realm-core/issues/3040:

Encrypted Realm files are not platform independent. The data is encrypted in chunk sizes equal to the platform's page size, and currently there's no way to read or write files with a different chunk size.
