### ISSUE TITLE
Support of primitive types for List

### ISSUE THREAD

**Issue by Bobozee** [realm/realm-cocoa#5489]
## Goals
```
class Entry : Object {
   ...
   dynamic var tags = List<String>()
}
```

and then:
```
let results = realm.objects(Entry.class).filter("any tags == %@", "foo")   // or
let results = realm.objects(Entry.class).filter("any tags contains[c] %@", "foo") // or
let results = realm.objects(Entry.class).filter("any SELF.tags in %@", ["foo"])
```

## Expected Results
Results<Entry> populated with Entry objects having "foo" in tags field

## Actual Results
'Invalid value', reason: 'Expected object of type (null) in IN clause for property 'tags' on object of type 'Entry', but received: foo'

## Steps to Reproduce
just create a realm and put one instance of Entry class then try to fetch it by searching by tags 

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

/Applications/Xcode.app/Contents/Developer
Xcode 9.1
Build version 9B55


(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)


(not in use here)

/usr/bin/git
git version 2.13.6 (Apple Git-96)
```
Realm framework version: 3.0.2

Xcode version: 9.1

iOS/OSX version: HIGH Sierra 10.13.1

Dependency manager + version: ?

**Comment by Bobozee** [comment]
On one side:

> Lists can be filtered and sorted with the same predicates as Results<Element>.

and 

> The aggregate expressions @count, @min, @max, @sum and @avg are supported on List and Results properties

but on the other side:

> Note that querying Lists containing primitive values is currently not supported.

This is actually not an issue, primitive types in queries for List are not supported yet.

**Comment by bdash** [comment]
Support for queries involving arrays of primitives is being tracked at https://github.com/realm/realm-cocoa/issues/5334.
