### ISSUE TITLE
Build failed because of Semantic Issue

### ISSUE THREAD

**Issue by dmachacon** [realm/realm-cocoa#5492]
I can't build successfully after updating podfile. 

Semantic Issue under Realm Framework

<img width="792" alt="screen shot 2017-11-28 at 1 45 46 pm" src="https://user-images.githubusercontent.com/2116191/33304385-6872883c-d443-11e7-8822-f3d3e67e7390.png">

Realm framework version: 2.10.2
Xcode version: 8.3.3

**Comment by austinzheng** [comment]
Please follow the instructions [here](https://realm.io/docs/objc/latest#cocoapods) and then get back to us if they don't fix your problem.

**Comment by bdash** [comment]
Closing due to the lack of further information. Feel free to reopen this if you're still in need of assistance and are able to provide the requested information.
