### ISSUE TITLE
Realm update to 3.0.2: Missing Array PropertyType

### ISSUE THREAD

**Issue by sheinix** [realm/realm-cocoa#5494]
I've updated my RealmSwfit pod to Realm 3.0.2 and I'm getting an error about the PropertyType has no member Array.

## Goals
I want to know how to fix this compiling error and why is happening.

## Expected Results
Compile with no problems, as in other versions was working all ok.

## Actual Results
`Type 'PropertyType' (aka 'RLMPropertyType') has no member 'Array'`

## Steps to Reproduce
Update to Realm 3.0.2

## Code Sample
I'm accessing the object like this:
```
if let existingObject = realm.object(ofType: type(of: entity), forPrimaryKey: value as AnyObject) {
                    
                    let relationships = existingObject.objectSchema.properties.filter {
                        $0.type == PropertyType.Array
                    }
```

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

/Applications/Xcode.app/Contents/Developer
Xcode 9.1
Build version 9B55

/Users/juannuvreni/.rvm/rubies/ruby-2.4.0/bin/pod
1.3.1
Realm (3.0.2)
RealmSwift (3.0.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)


(not in use here)

/usr/bin/git
git version 2.13.6 (Apple Git-96)
```

**Comment by tgoyne** [comment]
`property.IsArray && property.type == .Object` is the equivalent of the old `Array` property type.

**Comment by sheinix** [comment]
Thank you! I missed that when I read the changelog.
