### ISSUE TITLE
Modifications indexes incorrect on results notifications

### ISSUE THREAD

**Issue by Fab1n** [realm/realm-cocoa#5499]
## Goals
Have a sorted results notification spit out the correct modifications indexes upon changing the results. What I want to have is correct indexes of modifications that apply to the result after the transaction that triggered the notification.

I want to stay as close as I can to your test suite cases, so picture this (ObjC, like your test cases):

Let's have some simple objects in the db like these:
0
1
2
3
4
5

I have results with the predicate format: `@"intCol > 0 AND intCol < 5"`, sorted by `intCol`, ascending.

When doing a write transaction and deleting objects and modifying objects, I want to have correct indexes in the resulting notification

## Expected Results
The initial expected results of my query should equal the following values:
1
2
3
4

When deleting the following values:
1
2
3

And then modifying the following value: 
4

Now the expected results of my query would look like this:
1

I'd expect a notification with the following changed indexes:
Deleted indexes should be:
0
1
2

Inserted indexes should be empty.

Modified indexes should be: 
0

## Actual Results
The initial results of my query are as expected, so:
1
2
3
4

After the deletion and modification in the write transaction the results of the query equal the expected values:
1

The actual indexes I've got are the following:
Deleted indexes are like expected:
0
1
2

Inserted indexes should be empty, like expected.

Modified indexes are: 
3

## Steps to Reproduce
It is very easy to reproduce. Just use your own tests with `Realm.xcodeproj` and test `NotificationTests.m`.
To accurately reproduces the issue replace the method `- (void)testModifyObjectShiftedByDeletion` with the following code: 

``` objc
- (void)testModifyObjectShiftedByDeletion {
    ExpectChange(self, @[@0, @1, @2], @[], @[@0], ^(RLMRealm *realm) {
        [realm deleteObjects:[IntObject objectsInRealm:realm where:@"intCol < 4"]];
        [[IntObject objectsInRealm:realm where:@"intCol = 4"] setValue:@1 forKey:@"intCol"];
    });
}
```

I also made sure to sort the results in the `- (RLMResults *)query` method with the following code:
``` objc
- (RLMResults *)query {
    return [[IntObject objectsWhere:@"intCol > 0 AND intCol < 5"] sortedResultsUsingKeyPath:@"intCol" ascending:YES];
}
```

If you now just run the replaced method `- (void)testModifyObjectShiftedByDeletion` you will see that the test fails.
The test accurately represents the results I'd expect.

Because we are currently still using `v2.10.0` in our project I had to test this issue first with the older version. Then I tested to see, if the issue exists in the newest build (`v3.0.2`). And it does.

I think the test you wrote not accurately tests the case when modifying and deleting in the same transaction. I don't know exactly, but I think your test only succeeds because the results of your query are `[4,4]` and I don't know how you identify which of these two is the correct `4`, as both of them could match, right?

## Version of Realm and Tooling
Realm framework version: 2.10.0/3.0.2

Xcode version: 9.1 (9B55)

---

So my question is: Is this expected behaviour? 
If so, I don't know if this makes sense, because people could not really deal with the modifications indexes, as when deleting objects before the modified indexes, the reported indexes point to the wrong objects in the updated results. 

Thus, for iOS for example, table views are not updated according to the real changes (the wrong cells are reloaded). 

Worst case scenario are `index-out-of-bounds exceptions`, which happen here in our app. Because of these crashes I am writing you and informing you.
Indexes that are not there anymore because of deletion of objects before modified objects cannot be accessed anymore for an update of cells in a table view. Thus the app crashes. 

I now need to readjust the modifications indexes until you can come up with a solution.

Many, many thanks to your great product and I hope I can help you with this detailed bug report.

**Comment by Fab1n** [comment]
The same thing is also true when inserting items before modified indexes.

For example consider this test inside of `NotificationTests.m`:
``` objc
- (void)testModifyObjectShiftedByInsertion {
    ExpectChange(self, @[], @[@1], @[@2], ^(RLMRealm *realm) {
        [[IntObject objectsInRealm:realm where:@"intCol = 3"] setValue:@4 forKey:@"intCol"];
        [IntObject createInRealm:realm withValue:@[@2]];
    });
}
```

I also like to use a customized version of `- (void)prepare`: 
``` objc
 - (void)prepare {
    @autoreleasepool {
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm transactionWithBlock:^{
            [realm deleteAllObjects];
            for (int i = 0; i < 10; ++i) {
                if (i%2 == 0) {
                    continue;
                }
                IntObject *io = [IntObject createInDefaultRealmWithValue:@[@(i)]];
                [ArrayPropertyObject createInDefaultRealmWithValue:@[@"", @[], @[io]]];
            }
        }];
    }
 }
```

This only fills my realm with:
1
3
5
7
9

This is then easier to use to uniquely identify, sort objects and track their index at any given time.

**Comment by tgoyne** [comment]
The modified indexes are reported in the collection before insertions/deletions are applied because that's what UITableView wants for batched animations (see the last paragraph of the [reloadRows() documentation](https://developer.apple.com/documentation/uikit/uitableview/1614935-reloadrows).

**Comment by austinzheng** [comment]
As Thomas said, this behavior is intentional and we have no plans to change it. Thank you for your feedback, though!
