### ISSUE TITLE
Need to re-authenticate after migrating 2.x ➡ 3.x (ROS 1.x ➡ 2.x)

### ISSUE THREAD

**Issue by raudabaugh** [realm/realm-cocoa#5503]
## Goals
Check status of `SyncUser.current` to determine whether re-authentication is needed, or throw a `SyncAuthError`.

## Expected Results

ROS 1 to 2 migration means client will need to log in again. After updating a 2.x client to 3.x, either `SyncUser.current?.state != .active` should evaluate to true, or `SyncManager.shared.errorHandler` should be executed. 

## Actual Results
After updating a 2.x client to 3.x, `SyncUser.current?.state == .active`, and no `SyncAuthError` is thrown.

## Steps to Reproduce

Update a client using RealmSwift 2.x to 3.x. Include the code below in the app delegate of the client using 3.x, then attempt to `Realm.openAsync` with current user.

## Code Sample

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        ...
        if SyncUser.current?.state != .active {
            // never executed
            print("need to login again")
        }
        ...

        SyncManager.shared.errorHandler = { error, session in
            // never executed
            print("error=\(error), session=\(String(describing: session))")
        }
        ...
        return true
    }
```

## Version of Realm and Tooling

Realm framework version: Swift 3.0.2

Realm Object Server version: 2.0.23

Xcode version: 9.2

iOS/OSX version: iOS 11.2

Dependency manager + version: Carthage 0.26.2

**Comment by raudabaugh** [comment]
This may be related to #5188

**Comment by ianpward** [comment]
I believe we fixed this in a later sync release - closing
