### ISSUE TITLE
Getting multiple users exception when calling SyncUser.current when SyncUser.all.count == 1

### ISSUE THREAD

**Issue by raudabaugh** [realm/realm-cocoa#5505]
## Goals
Want to retrieve the current user after logging all other users out.

## Expected Results
SyncUser.current returns SyncUser.all.first when SyncUser.all.count == 1.

## Actual Results
Exception: 

```
+currentUser cannot be called if more that one valid, logged-in user exists.
(null)

(lldb) po SyncUser.all.count
1
```
## Steps to Reproduce
Could be related to URL change / cached users? I was first logged into my app with SSL disabled. Saw the error only after updating the app with SSL enabled and changing the URLs to use https/realms.

## Version of Realm and Tooling

Realm framework version: Swift 3.0.2

Realm Object Server version: 2.0.23

Xcode version: 9.2

iOS/OSX version: iOS 11.2

Dependency manager + version: Carthage 0.26.2

**Comment by bdash** [comment]
> Could be related to URL change / cached users? I was first logged into my app with SSL disabled. Saw the error only after updating the app with SSL enabled and changing the URLs to use https/realms.

That's almost certainly it. `SyncUser.all` returns a dictionary keyed by user identity, but if you change the URL by which you access a given server, you can end up with multiple users with the same identity (one for each server URL). This means that the result returned by `SyncUser.all` represents only a subset of the users.

**Comment by ianpward** [comment]
@bmunkholm Assigning to you for SDK EngBacklog
