### ISSUE TITLE
Crash when filtering with ALL operator on a relationship list

### ISSUE THREAD

**Issue by jdanthinne** [realm/realm-cocoa#5506]
## Goals
Filter a relationship array with the ALL operator to make sure all elements are IN a given array.

## Expected Results
Get all results where predicate is true

## Actual Results
`libc++abi.dylib: terminating with uncaught exception of type NSException` without any backtrace or message.

## Steps to Reproduce
Use the simplified code sample.

## Code Sample
```swift
final class Group: Object {
    @objc dynamic var id: Int = 0

    override static func indexedProperties() -> [String] {
        return ["id"]
    }
}

final class Category: Object {
    @objc dynamic var title: String = ""

    let groupsAllOf = List<Group>()
    let groupsOneOf = List<Group>()
}

let userGroups: [Int] = [1, 2]

// The Following is working nicely:
let oneOfFilter = NSCompoundPredicate(orPredicateWithSubpredicates: [
                NSPredicate(format: "groupsOneOf.@count = 0"),
                NSCompoundPredicate(andPredicateWithSubpredicates: [
                    NSPredicate(format: "groupsOneOf.@count != 0"),
                    NSPredicate(format: "ANY groupsOneOf.id IN %@", userGroups)
                    ])
                ])
let categoriesOneOf = realm.objects(Category.self).filter(oneOfFilter)

// The following crash:
let allOfFilter = NSCompoundPredicate(orPredicateWithSubpredicates: [
                NSPredicate(format: "groupsAllOf.@count = 0"),
                NSCompoundPredicate(andPredicateWithSubpredicates: [
                    NSPredicate(format: "groupsAllOf.@count != 0"),
                    NSPredicate(format: "ALL groupsAllOf.id IN %@", userGroups)
                    ])
                ])
let categoriesAllOf = realm.objects(Category.self).filter(allOfFilter)

```
## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88

/Applications/Xcode.app/Contents/Developer
Xcode 9.2
Build version 9C40b

/usr/local/bin/pod
1.3.1
Realm (3.0.2)
RealmSwift (3.0.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

/usr/local/bin/carthage
0.25.0
(not in use here)

/usr/bin/git
git version 2.14.3 (Apple Git-98)
```

**Comment by jdanthinne** [comment]
Just saw in the Sheatsheet that "ALL" is not supported, and tried
`NSPredicate(format: "NONE (NOT groupsAllOf.id IN %@)", userGroups)`
instead of
`NSPredicate(format: "ALL groupsAllOf.id IN %@", userGroups)`
but same result…

Having no error message is strange…

**Comment by bdash** [comment]
When an NSException is raised and not caught, details about it, including the error message it contains, typically end up logged to the console. If for some reason you're not seeing this, you can set an Objective-C exception breakpoint to find the point at which it is raised and examine the error from there.

**Comment by jdanthinne** [comment]
With the exception breakpoint set, execution is stopped exactly on the subpredicate itself `NSPredicate(format: "ALL groupsAllOf.id IN %@", userGroups)`, but still no clue why…

**Comment by bdash** [comment]
When I copy-paste the code you shared into a fresh Xcode app and build and run it, this is what I see in Xcode's Console area:

```
2017-12-07 15:03:50.037154-0800 Simple[5648:212423] *** Terminating app due to uncaught exception 'Invalid predicate', reason: 'ALL modifier not supported'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f59b12b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010ec37f41 objc_exception_throw + 48
	2   Realm                               0x000000010df7c4e7 _ZL15RLMPreconditionbP8NSStringS0_z + 332
	3   Realm                               0x000000010df7ca2c _ZN12_GLOBAL__N_112QueryBuilder15apply_predicateEP11NSPredicateP15RLMObjectSchema + 732
        …
	42  libdyld.dylib                       0x00000001125f3d81 start + 1
	43  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

As the first line of the output states, the `ALL` modifier is not yet supported.

**Comment by jdanthinne** [comment]
Are you getting the same thing with the NONE version? Any idea on why I don’t get these errors displayed? Maybe because I’m importing Realm with Cocoapods?

**Comment by jdanthinne** [comment]
Not very pretty, but I finally found a workaround…
`NSPredicate(format: "SUBQUERY(groupsAllOf, $g, !($g.id IN %@)).@count == 0", userGroups)`
