### ISSUE TITLE
can't install my mac latest OS High Sierra

### ISSUE THREAD

**Issue by karthickkck315** [realm/realm-cocoa#5509]
## Version of Realm and Tooling

Realm framework version: latest

Realm Object Server version: ?

Xcode version: 9.1

iOS/OSX version: 10.13

Dependency manager + version: ?

**Comment by bdash** [comment]
You'll need to provide a lot more information for us to be able to help you. What steps are you following? What's not working? What errors are you seeing? What version of Realm are you trying to install?

**Comment by karthickkck315** [comment]
can you please give the steps to install realm on my macbook Pro.
once again i ill try to install it

**Comment by bdash** [comment]
The [steps to integrate Realm into your project](https://realm.io/docs/swift/latest/#installation) can be found in the documentation.
