### ISSUE TITLE
Crash on inverse relationship within MKAnnotation

### ISSUE THREAD

**Issue by Skornos** [realm/realm-cocoa#5511]
The goal is to obtain inverse relationship properties on `MKAnnotation's` `title` and `subtitle`.

I have a `MainObject` which has relationship property to `Location` object:
```
class MainObject: Object, StaticMappable {
    @objc dynamic var location: Location?
    @objc dynamic var name: String        = ""
```
The linked `Location` object has inverse relationship back to `MainObject`
```
class Location: Object, StaticMappable {
    @objc dynamic var latitude: Double  = 0.0
    @objc dynamic var longitude: Double = 0.0

    let mainObjects = LinkingObjects(fromType: MainObject.self, property: "location")
    var mainObject: MainObject? { return mainObjects.first }
```
The problem is that `Location` object also conforms to `MKAnnotation` (so I could easily display the object on the mapView)
```
extension Location: MKAnnotation {
    // coordinate already set
    // set other optional vars
    public var title: String? { return mainObject?.name }
}
```

The collection of `MainObject`'s is fetched on the main thread (`com.apple.main-thread (serial)`) but when the `Location` is displayed on the map the MKAnnotation is processed on the background thread (`com.apple.vectorkit.dispatch.layoutqueue`) and this causes the obvious crash: `Realm accessed from incorrect thread`.

`MKAnnotation`'s `title` and `subtitle` are get-only so I cannot set them on the main thread when I am creating the annotations.

Is there anything I can do about this?

**Comment by bdash** [comment]
If objects conforming to `MKAnnotation` are required to be usable on different threads than they were retrieved / created on, your `Object` subclass cannot realistically conform to this protocol. Instead you'd want to have some type conform to this protocol, and re-fetch the `Object` on the current thread before accessing its values.
