### ISSUE TITLE
Interaction between AsyncDisplayKit and RealSwift breaks accors

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-cocoa#5516]
## Goals

Be able to use standard property accessors on Realm objects with RealmSwift in a project that also uses [ASyncDisplayKit](https://github.com/facebookarchive/AsyncDisplayKit)

## Expected Results
Accessing a property of a Realm object should return the value of that property

## Actual Results

All accessors return ether nil (for optionals) or whatever the default value is created by the object's constructor; setters have the same problem.  However accessing (or setting) the properties with KVO and all the values are returned (or set) as expected... 

## Steps to Reproduce
1. `git clone https://github.com/realm/reach.git`
2. `git checkout dhms/rooms-work`
3. `cd reach/server`
4. `yarn` to get all packages, etc updated
5. Run server in `vscode` or by hand with `npm run build && node dist/index.js`
6. Run Realm Studio, open the local server; then open the `/RealmChat` Realm; there will be 3 users (`ios-user`, `electron-user` and `android-user`) in the User table created by the server setup
7. `cd ../ios`
8. Update pods with `pod update`
9. Open `Reach.xcworkspace`
10. Pick a simulator; then build and run 
11. Log in to the local server (users are `ios-user`, `electron-user` and `android-user` all with the password of `password`)
12. Swipe left to reveal the utility menu which should have 2 menu items: `Settings…` and `Logout…`
13. Tap `Settings` - a breakpoint should fire at line 71 in the file `SettingsViewModel.swift`. This is where the user’s profile is returned by a static method on the `User` class. You can examine the Realm object and see (as per the attached screen shot, below) that the object is populated… however attempting to access the properties yields the defaults for a new record rather than the values read in from the Realm into the `myProfile` object.
14. allowing the app to continue will show the Settings view but, of course, nothing is correctly populated (you can continue to step thru’ here too.. and the object itself will remain intact, but the properties are still inaccessible…).

As mentioned above accessing the properties with KVO and all the values are returned as expected... 

![reach-ios-inaccessible-properties](https://user-images.githubusercontent.com/21057/33856222-4e84e4cc-de7c-11e7-8cc1-644c694c004d.png)

<hr>
@austinzheng  did some preliminary analysis on this issue -- here are the salient parts from our slack conversation: - in a nutshell it seems to be a problem with method swizzling affecting Realm objects:

Austin Zheng [2:33 PM]
as far as I can tell your object is correctly being created at the objective-C layer (and behaves accordingly), but somehow loses its swizzled methods when it gets unsafe bit casted to a Swift object.

David Spector [2:34 PM] 
Yikes.  Sounds like AsyncDisplayKit _must_ be the wildcard….

Austin Zheng [2:59 PM] 
just to sum up: I investigated code that called into `public func object<Element: Object, KeyType>(ofType type: Element.Type, forPrimaryKey key: KeyType) -> Element?`. The object that is created behaves correctly at all points during the Objective-C phase of execution. Unfortunately it's not possible to inspect the object once it bubbles back up to the Swift layers because LLDB crashes.

Austin Zheng [1:23 PM] 
I made a tiny, tiny bit of progress. Once the object gets back to Swift, if I cast it from `Any?` to `AnyObject?` and then use the universal member look-up to get the value of `displayName`, it seems to work. I think the unsafe downcast/bitcast we're doing might have something to do with the swizzled method impls disappearing? (edited)

## Code Sample

See above

## Version of Realm and Tooling

Realm framework version: ? 3.01 and 3.0.2

Realm Object Server version: ? 2.0.23

Xcode version: ? Xcode9.1, Xcode9.2

iOS/OSX version: ? iOS 11.1

Dependency manager + version: ? 1.3.1

**Comment by tgoyne** [comment]
You have not marked the properties as `dynamic`.

**Comment by dhmspector** [comment]
doh.

**Comment by dhmspector** [comment]
we really should catch that....

**Comment by tgoyne** [comment]
We've tried. There does not appear to be any way to.
