### ISSUE TITLE
Compile error: No member named 'is_partial' in 'realm::SyncConfig'

### ISSUE THREAD

**Issue by dickyj** [realm/realm-cocoa#5520]
## Goals
Trying to compile a project using pod RealmSwift, but end up with compile error. Not sure how it happened. Yesterday it was still compiling fine...

## Expected Results
Compile success.

## Actual Results
Compile error:
No member named 'is_partial' in 'realm::SyncConfig'

## Code Sample
   auto sync_config = realm->config().sync_config;
   // error in this line
    if (!sync_config || !sync_config->**is_partial**)
        throw std::logic_error("A partial sync query can only be registered in a partially synced Realm");

    if (realm->schema().find(object_class) == realm->schema().end())
        throw std::logic_error("A partial sync query can only be registered for a type that exists in the Realm's schema");

    auto matches_property = object_class + "_matches";

## Version of Realm and Tooling

Realm framework version: latest

Realm Object Server version: ?

Xcode version: 9.2

iOS/OSX version: 11.2

Dependency manager + version: ?

**Comment by bdash** [comment]
The error you're seeing indicates that one of Realm's submodules is not at the correct version. Please see the section in our documentation on [troubleshooting issues with CocoaPods](https://realm.io/docs/swift/latest/#cocoapods), including the steps it mentions to reset the integration.

**Comment by dickyj** [comment]
Thanks for the help. I tried running this couple of times already, but I still has the same issue:
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData

**Comment by bdash** [comment]
I don't know what to suggest. For you to be seeing this error, CocoaPods must be somehow failing to check out the appropriate version of the realm-object-store submodule. I do not know why this would be happening for you. We've had no other reports of this happening.

**Comment by dickyj** [comment]
Its very strange indeed. I even downgraded to 3.0.1 and it still has the same error.

**Comment by dickyj** [comment]
In fact, there are compile errors in this file too all of a sudden:
![screen shot 2017-12-14 at 2 38 14 pm](https://user-images.githubusercontent.com/6478334/33980680-7db3bde2-e0dc-11e7-945f-368be82e1103.png)

**Comment by dickyj** [comment]
I tried on another machine, and this is the error I got, its getting stranger and stranger...
![screenshot 2017-12-14 18 32 17](https://user-images.githubusercontent.com/6478334/33990349-3a2598ea-e0fd-11e7-8331-580d3442d4dd.png)

**Comment by bdash** [comment]
The most recent screenshot suggests that the core binary failed to download. Resetting the CocoaPods state, as described above, should address this (unless the problem with downloading the binary is somehow persistent).

**Comment by bdash** [comment]
I can't think of anything else we can do to help here.

**Comment by dickyj** [comment]
Just to update. What I ended up doing is create a new project again. And run this command:
rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;

Somehow it fixes the problem.
