### ISSUE TITLE
The daily working time of Beijing time cannot open https://realm.io

### ISSUE THREAD

**Issue by GG526** [realm/realm-cocoa#5529]
<img width="185" alt="2017-12-20 9 38 46" src="https://user-images.githubusercontent.com/11623029/34186947-a9c5bfac-e569-11e7-8949-3b2d7d05074b.png">
<img width="1211" alt="2017-12-20 9 38 54" src="https://user-images.githubusercontent.com/11623029/34186948-acdc8f18-e569-11e7-9d89-7bd39b27e9d4.png">

**Comment by bmunkholm** [comment]
Sorry, I'm not sure what we can do about that.

**Comment by GG526** [comment]
。。。。。。。
