### ISSUE TITLE
Xcode says: Update to recommended settings for CocoaPod RealmSwift

### ISSUE THREAD

**Issue by phoney** [realm/realm-cocoa#5534]
## Goals

I want to use RealmSwift from CocoaPods on iOS.

## Expected Results

I expect no project warnings.

## Actual Results

Xcode says: "Update to recommended settings"

I get the two warnings shown in the screenshot. (You can ignore the HockeyApp warning and the Project Pods warning).

Target 'RealmSwift' - Update Swift Optimization Setting
This update the Swift optimization level to use Whole Module Optimization, and remove the obsolete definition of "Whole Module Optimization" for the Debug configuration.

Target 'RealmSwift' - Update Swift Optimization Setting
This update the Swift optimization level to use Whole Module Optimization, and remove the obsolete definition of "Whole Module Optimization" for the Release configuration.

When I install RealmSwift with CocoaPods I get two warnings from Xcode about the settings in the RealmSwift Target. 
<img width="585" alt="screen shot 2017-12-22 at 11 55 25 am" src="https://user-images.githubusercontent.com/3106038/34306251-3b29a736-e710-11e7-8d96-19f05ec9dc70.png">

## Steps to Reproduce

I'm using CocoaPods 1.3.1 and Xcode Version 9.2 (9C40b). When I pod update I get 

  - Realm (3.0.2):
    - Realm/Headers (= 3.0.2)
  - Realm/Headers (3.0.2)
  - RealmSwift (3.0.2):
    - Realm (= 3.0.2)

## Code Sample

//Podfile
  pod 'Realm', '~> 3.0'
  pod 'RealmSwift', '~> 3.0'

Sorry about the markdown funny business.

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: Version 9.2 (9C40b)

iOS/OSX version: ?

Dependency manager + version: ?

CocoaPods 1.3.1

  - Realm (3.0.2):
    - Realm/Headers (= 3.0.2)
  - Realm/Headers (3.0.2)
  - RealmSwift (3.0.2):
    - Realm (= 3.0.2)

**Comment by bdash** [comment]
https://github.com/realm/realm-cocoa/blob/95d69bebbeebf30a5bf00f8923638ed16e3899ce/RealmSwift.podspec#L26-L27

I think we'll want to replace `SWIFT_WHOLE_MODULE_OPTIMIZATION = YES` with `SWIFT_OPTIMIZATION_LEVEL = -Owholemodule`. It looks like the latter is supported from Xcode 8 onward, which is every version of Xcode that we currently support.

**Comment by markjarecki** [comment]
+1

**Comment by at-truongnguyen** [comment]
+1

**Comment by phoney** [comment]
@bdash Actually I think all that needs to be done is to remove SWIFT_WHOLE_MODULE_OPTIMIZATION from the Podspec. I think the cocoapod default is to enable whole module optimization in Release builds. Podspecs for other Cocoapods don't include this setting and they use whole module optimization (see AlamoFire, FontAwesome etc.)

Also, see this Cocoapod issue
https://github.com/CocoaPods/CocoaPods/issues/4439

**Comment by phoney** [comment]
This is now fixed due to pull #5696 .
