### ISSUE TITLE
Notification service extension crash, when the realm instance tries to initialize. iOS 10.3.3

### ISSUE THREAD

**Issue by BarredEwe** [realm/realm-cocoa#5539]
Notification service extension crash, when the realm instance tries to initialize. Crash only on iOS 10.3.3. In main target, realm initializes successfully.

## Initialize

            fileURL = FileManager.default
                .containerURL(forSecurityApplicationGroupIdentifier: "group.lol.mobile")!
                .appendingPathComponent("Library/Caches/default.realm")

            let configuration = Realm.Configuration(fileURL: fileURL)
            let folderPath = configuration.fileURL!.deletingLastPathComponent().path

            // Disable file protection for this directory
            let attributes = [FileAttributeKey.protectionKey: FileProtectionType.none]
            try! FileManager.default.setAttributes(attributes, ofItemAtPath: folderPath)

            Realm.Configuration.defaultConfiguration = configuration

            realm = try! Realm()

## Crash on 

            public convenience init() throws {
                let rlmRealm = try RLMRealm(configuration: RLMRealmConfiguration.default())
                self.init(rlmRealm)
            }

## Logs 

            Program ended with exit code: 0

Realm framework version: 3.0.1

Xcode version: 9

iOS/OSX version: 10.3.3

Device: iPhone 7

**Comment by kishikawakatsumi** [comment]
@BarredEwe There is a very strict limit on memory usage to app extensions. I'm pretty sure that memory is exhausted by calling `objc_copyClassList ()` which Realm calls internally. We recommend that you specify the classes to be managed by a Realm explicitly in order to avoid a costly call to `objc_copyClassList()`:

```
let config = Realm.Configuration(objectTypes: [Dog.self, Person.self])
let realm = try! Realm(configuration: config)
```

See: https://realm.io/docs/swift/latest/#operating-with-low-memory-constraints

**Comment by BarredEwe** [comment]
Many thanks. Everything worked!
