### ISSUE TITLE
realm.io server banned Iraq ☹️

### ISSUE THREAD

**Issue by HusamAamer** [realm/realm-cocoa#5540]
## Issue
Unable to install Realm using cocoa pods.

## Expected problem
**`realm.io` server banned Iraq ☹️.**
I can't open realm.io website in browser without using VPN
here is error message appeared in website 

> Error 1009
> Access denied
> 
> What happened?
> The owner of this website (realm.io) has banned the country or region your IP address is in (IQ) from accessing this website.

## Error appeared 
```
Installing Realm (3.0.2)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 2.1.1
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-2.1.1.tar.xz
	curl: (22) The requested URL returned error: 403 
```

## Steps to Reproduce
my pod file contains this line as usual
`pod 'RealmSwift'`

## Version of Realm and Tooling
Realm framework version: 3.0.2
Xcode version: 9
Dependency manager + version: Cocoapods 1.3.1

**Comment by bluemix** [comment]
the same. thanks @HusamAamer for reporting the issue.

**Comment by ahmedraad** [comment]
I hope they gonna fix this issue

**Comment by msxenon** [comment]
Yes we screwed up with this issue

**Comment by hamdongunner** [comment]
many developers in iraq want realm back 😔

**Comment by Faisal-AlNeela** [comment]
Same problem!!!!
Waiting for solution 😕......

**Comment by nirinchev** [comment]
Sorry for the inconvenience. I've reached out to our web team and hopefully, we'll have a fix shortly.

**Comment by DevZaid** [comment]
same here

**Comment by mustafa96m** [comment]
Same here.

**Comment by fiftysoft** [comment]
+1 same here

**Comment by bdash** [comment]
Please don't pile on with the redundant comments. We'll look into this after the holidays are over.

**Comment by bdash** [comment]
We believe that this issue has been addressed.

**Comment by bmunkholm** [comment]
@nadia-am If you are in Iraq - you are not allowed to use Realm unfortunately. The solution is to use something else.
