### ISSUE TITLE
realm file size is increasing fast

### ISSUE THREAD

**Issue by liuxuan30** [realm/realm-cocoa#5541]
## Goals
ream file size should not grow that fast without compact

## Expected Results
ream file size should not grow that fast without compact

## Actual Results
4k each time, while my data size is not increased.

My model:
```swift
class AirQuality: Object
{
    @objc dynamic var datetime = ""
    @objc dynamic var concentration = 0.0
    @objc dynamic var AQI = 0
    @objc dynamic var city = 0
}
```
One example record is:
> Dec 30, 2017 6 PM | 14 | 55 | 1

My feature requirement is simple at the moment, I only get max 24 records in realm all the time, which means every time I got new data, I delete all data first and add my array like below
```swift
    func write(airquality set: [AirQuality])
    {
        autoreleasepool {
            DispatchQueue(label: "background").async {
                do
                {
                    let realm = try Realm()
                    try realm.write
                    {
                        realm.deleteAll()
                        realm.add(set)
                    }
                }
                catch
                {
                    NSLog("Failed to write Realm")
                }
            }
        }
    }
```
I notice the initial file size is already 8k, considering only 24 records, realm internal data is a large chunk. 
Then I tried 2 more times running above code, the record count is still 24, however, the file size is 8k -> 12k -> 16k, which, I assume realm is writing 4k more each time, and all of it is realm internal info, rather than my data.

## Steps to Reproduce
see above code

## Question
I went reading the doc, it says realm is storing thread info or other internal info to the file, but giving the test result, I think it's kind of too much, as my data size is not growing at all.

It's said `DispatchQueue(label: "background")` does not guarantee the same thread will be used.

1 The first question is, how realm recognize it's a different thread, based on what?

2 second, Is this the current by design limitation, and any plan to improve it?

3 Is there any way to get same thread so I don't have to compact/delete realm file every time?

4 I remember I learned somewhere the thread pool is also a fixed count, so after DispatchQueue iterate every thread, will the file size stop growing?

One alternative is I write them directly into a file; but I predict in the future I will be asked to store all data, rather than only 24 at max, so I need to enable a database implementation.

## Version of Realm and Tooling
Realm framework version: ? latest master

Realm Object Server version: ? NOT APPLIED
Xcode version: ? 9.2
iOS/OSX version: ? 11.2
Dependency manager + version: ? Carthage

**Comment by bdash** [comment]
One thing that stands out to me is the lack of autorelease pools within the async block. See the note at the top of the [Threading](https://realm.io/docs/swift/latest/#threading) section of our documentation:
> Realm read transaction lifetimes are tied to the memory lifetime of Realm instances. Avoid “pinning” old Realm transactions by using auto-refreshing Realms and wrapping all use of Realm APIs from background threads in explicit autorelease pools.

**Comment by liuxuan30** [comment]
Thanks for pointing it out! Start using Realm in my app.

**Comment by bdash** [comment]
It sounds like that addressed your problem. If not, please let us know.
