### ISSUE TITLE
Compact on launch when Realm fails to initialise.

### ISSUE THREAD

**Issue by iShavgula-TacTill** [realm/realm-cocoa#5545]
Is it possible to compact realm file when having **mmap() failed: Cannot allocate memory size: 2684354560 offset: 0** error ?

I know how to avoid this problem in further releases, but we've been using Realm since v0.96 and some of the users are still using Realm versioned below 2.6, meaning that one day their application will crash and they won't be able to preserve data even after updating to the latest version.

Is there any way to compact the realm file without deleting it ?

## Version of Realm and Tooling

Realm framework version: 3.0.2

Xcode version: 9.2

iOS version: 9.1 or above

**Comment by liuxuan30** [comment]
I'm curious on this too

**Comment by bdash** [comment]
> Is there any way to compact the realm file without deleting it ?

I think the answer here is no, not without significant changes to how compacting is implemented. Compacting requires the ability to read the Realm file, which currently is not possible unless the file can be mapped into memory.

**Comment by liuxuan30** [comment]
@bdash sorry to jump in, could we put compact in a default Realm config? Any side effect? 
like
```
    func defaultRealmConfig() -> RealmSwift.Realm.Configuration
    {
        var config = Realm.Configuration(shouldCompactOnLaunch: { totalBytes, usedBytes in
            // totalBytes refers to the size of the file on disk in bytes (data + free space)
            // usedBytes refers to the number of bytes used by data in the file
            let oneMB = 1 * 1024 * 1024
            return (totalBytes > oneMB) && (Double(usedBytes) / Double(totalBytes)) < 0.5
        })

        // Use the default directory, but change filename
        config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent("xxx.realm")
        return config
    }
```
Or should we only compact at app launch, with a separate config?

**Comment by bdash** [comment]
@liuxuan30, please don't hijack other people's issues with unrelated questions.

That said, I see no reason what you mention wouldn't work.
