### ISSUE TITLE
Is it possible to create realm class with properties coming from JSON ?

### ISSUE THREAD

**Issue by Venkata-Maniteja** [realm/realm-cocoa#5547]
In my app the field names will be provided via  JSON.

The JSON contains the fields upto 100 (max) and they are like firstName, lastName etc

Based on these properties I need to create the realm database.

Is there a way of creating the realm database without hardcoding these properties in realm class ?

**Comment by liuxuan30** [comment]
curious on this too

**Comment by bmunkholm** [comment]
There is a dynamic API you can use to create the classes on the fly (our Realm Browser uses this). Alternatively you can make a generic class to hold a map: type, name for to tell what it is and then a property for each of the types you expect: string, int, date, binary, ... and then you obviously only store the value in one of those.
