### ISSUE TITLE
Is `RealmCollectionValue` protocol supposed to be public?

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-cocoa#5548]
It is currently public as per [here](https://github.com/realm/realm-cocoa/blob/13a3cb44c10436d4fb575bfcddc879698ae956e3/RealmSwift/RealmCollection.swift#L133) but I don't know if it should be public.

Anyone?

**Comment by tgoyne** [comment]
It has to be public as it's the constraint for `List` and `Results`'s generic type, and in theory a user might want to use it for their own generic function which can accept any type which can be stored in a `List`.

**Comment by Zhuinden** [comment]
Cool! Thanks
