### ISSUE TITLE
Cannot build Realm as a static framework with Carthage

### ISSUE THREAD

**Issue by maxmeyers** [realm/realm-cocoa#5550]
## Goals
Carthage provides a handy guide on how to build your dependencies as static frameworks rather than dynamic frameworks. So far, this has worked great -- except for Realm.

My goal is to build all of my Carthage dependencies as static frameworks so that they don't have to be loaded dynamically when the app is launched, increasing launch time.

I am using the directions listed here:
https://github.com/Carthage/Carthage/blob/5b2d2ad23e740dd93cd81e8f273c013a15c490ff/Documentation/StaticFrameworks.md

## Expected Results
The output of `file Realm.framework/Realm` should include `current ar archive` to indicate a static framework.

## Actual Results
```maxmeyers$ ./carthage-build-static.sh --platform iOS
*** xcodebuild output can be found in /var/folders/b7/xhtbl2xn6_d46d9w6wjc_sd80000gn/T/carthage-xcodebuild.hK8fLb.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Quick-iOS" in Quick.xcworkspace
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
*** Building scheme "SnapKit" in SnapKit.xcworkspace

maxmeyers$ file Carthage/Build/iOS/RealmSwift.framework/RealmSwift 
Carthage/Build/iOS/RealmSwift.framework/RealmSwift: Mach-O universal binary with 4 architectures: [arm_v7:current ar archive] [arm64]
Carthage/Build/iOS/RealmSwift.framework/RealmSwift (for architecture armv7):	current ar archive
Carthage/Build/iOS/RealmSwift.framework/RealmSwift (for architecture i386):	current ar archive
Carthage/Build/iOS/RealmSwift.framework/RealmSwift (for architecture x86_64):	current ar archive
Carthage/Build/iOS/RealmSwift.framework/RealmSwift (for architecture arm64):	current ar archive

maxmeyers$ file Carthage/Build/iOS/Realm.framework/Realm
Carthage/Build/iOS/Realm.framework/Realm: Mach-O universal binary with 4 architectures: [i386:Mach-O dynamically linked shared library i386] [arm64]
Carthage/Build/iOS/Realm.framework/Realm (for architecture i386):	Mach-O dynamically linked shared library i386
Carthage/Build/iOS/Realm.framework/Realm (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Carthage/Build/iOS/Realm.framework/Realm (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Carthage/Build/iOS/Realm.framework/Realm (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

RealmSwift is build correctly as a static framework, but Realm continues to build as a dynamic framework. Additionally, all of the other frameworks in our Cartfile are built as static frameworks.

## Steps to Reproduce
1. Set up `ld.py` and `carthage-build-static.sh` as indicated in the link above
2. Run `./carthage-build-static.sh --platform iOS`
3. `file Carthage/Build/iOS/Realm.framework/Realm`

## Version of Realm and Tooling

Realm framework version: `github "realm/realm-cocoa" "v2.8.3"`

Realm Object Server version: N/A

Xcode version: `Version 9.2 (9C40b)`

iOS/OSX version: `10.13.2 (17C88)`

Dependency manager + version: `0.27.0`

**Comment by maxmeyers** [comment]
P.S. - I wasn't sure whether this was a Realm or Carthage issue, so I started here since Realm was the outlier among the other dependencies.

**Comment by bdash** [comment]
It looks to me like a bug with the script that Carthage provides. The script assumes that setting the `LD` Xcode configuration setting will override the linker being used, but that does not appear to work for targets that contain C++ code.

**Comment by maxmeyers** [comment]
Got it, thanks!

**Comment by hyouuu** [comment]
@maxmeyers did you file a Carthage issue or changed the script to fix it? Am trying to follow the path you did, and any help is appreciated!

**Comment by maxmeyers** [comment]
I did not do either of those things.

But CocoaPods just recently announced support for Swift static libraries, so that's probably what we'll try next.

**Comment by jhoughjr** [comment]
I'm having issues using Carthage in any capacity with realm-cocoa-converter.

**Comment by bmunkholm** [comment]
@jhoughjr This issue is closed. Please open another with all needed details (specially on how to reproduce). Thanks!
