### ISSUE TITLE
Dynamic create stuck in loop if two way relationship

### ISSUE THREAD

**Issue by markst** [realm/realm-cocoa#5558]
Apologies if this is already an issue. I couldn't find any existing.

If I have two models which have relationships which reference each other as follows:
```swift
class Fitting: Object {
    @objc dynamic var id: String? = nil
    @objc dynamic var latestTest:Test?
    let tests = LinkingObjects(fromType: Test.self, property: "fitting")
}
```

```swift
class Test: Object {
    @objc dynamic var id: String? = nil
    @objc dynamic var fitting: Fitting?
```

Then I use dynamic create to create the object from an unmanaged version:
```swift
self.dynamicCreate("Fitting", value: fitting, update: true)
```

My application eventually reaches `EXC_BAD_ACCESS` state after being stuck in a loop:

![image](https://user-images.githubusercontent.com/274318/34708467-fd609f3a-f566-11e7-9dfd-346363c82b1b.png)

**Comment by bdash** [comment]
The stack trace in the screenshot suggests you're adding an object graph that contains cycles. Can you confirm that's the case?

**Comment by markst** [comment]
@bdash yes that's the issue. If I define both `latestTest` & `fitting` relationships referencing each other as per example above, then I'm creating a cycle. 
Is there no way around this if I wish to have multiple relationships whilst also maintaining an inverse?

**Comment by markst** [comment]
It works fine If I establish the relationship after creating the Fitting:
```swift
try! realm.write {
    realm.create(Fitting.self, value: fitting, update: true)
    fitting.latestTest = theTest
}
```

However I can't do such a thing with my current mapping library.
For example I fetch an unmanaged copy of the Fitting and relationships from the store, update it's attributes & relationships, then use `dynamicCreate()` to update the store.

**Comment by bdash** [comment]
Handling cyclic object graphs in `Realm.create` and friends is tracked in https://github.com/realm/realm-cocoa/issues/1800.
