### ISSUE TITLE
`Sync.retrievePermissions(callback:)` fails without error message if login url contains trailing `/`

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#5565]
@dmead28 commented on [Thu Jan 11 2018](https://github.com/realm/realm-core/issues/2977)

### 1. Goals

`Sync.retrievePermissions(callback:)` does not work when the login url has a trailing `/`, such as: `URL(string: "http://localhost:9080/")`. The callback is never called. The goal is to either:

    A) validate the URL and pass an error if it's invalid
    B) Strip the trailing `/`

### 2. Expected results

    A) `Sync.retrievePermissions(callback:)` returns an error if the url is not formatted properly
    B) `Sync.retrievePermissions(callback:)` succeeds whether the format is: "http://localhost:9080/" or "http://localhost:9080"

### 3. Actual results

`Sync.retrievePermissions(callback:)` fails and completion is never called.

### 4. Steps to reproduce

1) Log in using a url with a trailing `/`, such as `"http://localhost:9080/"`
2) Make a call to `Sync.retrievePermissions(callback:)`
3) The call will not return

### 5. Code sample that highlights the issue (full project that we can compile ourselves are ideal)
```
        let syncCredentials = SyncCredentials.usernamePassword(username: "test", password: "abc123", register: false)

        guard let loginUrl = URL(string: "http://localhost:9080/") else {
            print("Could not construct loginUrl")
            return
        }

        SyncUser.logIn(with: syncCredentials, server: loginUrl) { (newUserResult, error) in
            guard let newUser = newUserResult else {
                print("Error getting new user. Error: \(error?.localizedDescription ?? "")")
                return
            }

            // Permissions on main explicitly (suggested in docs)
            DispatchQueue.main.async { 
                newUser.retrievePermissions(callback: { (permissionResults, error) in
                    // THIS IS NEVER CALLED
                    guard let permissions = permissionResults else {
                        print("Could not get permissions. Error: \(error?.localizedDescription ?? "")")
                        return
                    }

                    print("Realms I have permission to")
                    permissions.forEach({ (permission) in
                        print("  - \(permission)")
                    })
                })
            }
```

Also, see test project at: https://github.com/dmead28/RosTest

### 6. **Version of Realm
Realm (3.0.2)
RealmSwift (3.0.2)

**Comment by dmead28** [comment]
```
SharedRealm Permissions::permission_realm(std::shared_ptr<SyncUser> user, const ConfigMaker& make_config)
{
    // FIXME: maybe we should cache the permission Realm on the user, so we don't need to open it every time.
    const auto realm_url = util::format("realm%1/~/__permission", server_url.substr(4));
    Realm::Config config = make_config(user, std::move(realm_url));
    config.sync_config->stop_policy = SyncSessionStopPolicy::Immediately;
    config.schema = Schema{
        {"Permission", {
            {"updatedAt", PropertyType::Date},
            {"userId", PropertyType::String},
            {"path", PropertyType::String},
            {"mayRead", PropertyType::Bool},
            {"mayWrite", PropertyType::Bool},
            {"mayManage", PropertyType::Bool},
        }}
    };
    config.schema_version = 0;
    auto shared_realm = Realm::get_shared_realm(std::move(config));
    user->register_permission_session(shared_realm->config().path);
    return shared_realm;
}
```

Proposed fixes are to regex the url before calling 
`const auto realm_url = util::format("realm%1/~/__permission", server_url.substr(4));`

or require validation of the login url somewhere
