### ISSUE TITLE
Would love to be able to delete a Class via Realm Studio 

### ISSUE THREAD

**Issue by dev-ios-sogo** [realm/realm-cocoa#5568]
## Goals
Quick and easy ability to delete a Class (that is also sync'd with ROS) right from within Realm Studio. For us this would primarily be used when iterating on class schema design (eg. change a field type), and then re-loading data to that Class. At moment is cumbersome for this particular use case via code migration etc.

## Expected Results
Right click on a Class, select delete, and have a confirmation dialogue

**Comment by bdash** [comment]
I've filed this as an enhancement request against Realm Studio for you.
