### ISSUE TITLE
PermissionOffer for Non-Registered User

### ISSUE THREAD

**Issue by kevinmlong** [realm/realm-cocoa#5579]
Have posted a question here and could use some feedback from the Realm staff.

https://stackoverflow.com/questions/48235906/permissionoffer-for-non-registered-user

Would like to understand the suggested implementation for inviting a user and handling respective permissions. Understand that doing functions with ROS could work, but these are restricted to PE and EE, and I'm trying to explore how it could work with the DE. Thanks!

**Comment by kevinmlong** [comment]
@bigfish24 - I know you respond to a lot of issues here and on Stackoverflow. Any suggestions on this?

**Comment by morteg** [comment]
@kevinmlong 
When you create permission offer, you get invitation key, that saves to the Realm. 
All permissions to your realm which you have generated are linked to the invitation key.
You can send this key through e-mail to the target user. He will have to register on your realm server and enter invitation key. 
You process this key (token) with realmUser.acceptOffer(forToken: token) { (realmURL, error)...

And user will be able to connect to your shared realm via realmURL.

**Comment by kevinmlong** [comment]
@morteg - Thanks for the clarification! I guess I didn't realize that you didn't need the user id for the whom the token is being generated. This make sense now. Thanks!

**Comment by morteg** [comment]
@kevinmlong 
You are welcome )
