### ISSUE TITLE
Unable to run project on Xcode 9.1, Swift version - 3.2

### ISSUE THREAD

**Issue by chetan15aggarwal** [realm/realm-cocoa#5581]
I am Unable to run project on Xcode 9.1, Swift version - 3.2
with Error : Module compiled with Swift 4.0 cannot be imported in Swift 3.2.2:

I have manually integrated Realm Swift DB framework in it. I have tried with different version provided in download file for my iOS Project
Realm framework version: tried with swift 3.2, 3.2.2 and 4.0

Xcode version: 9.1

iOS/OSX version: 10.12.6

Dependency manager: Manually

**Comment by bdash** [comment]
You should be able to use the prebuilt binary for Swift 3.2.2 / 4.0.2 with Xcode 9.1. If you're seeing a message stating that the module was built with Swift 4.0 when trying to use the Swift 3.2.2 / 4.0.2 framework, double-check very carefully that Xcode is finding the framework that you expect it to find.

**Comment by chetan15aggarwal** [comment]
Thanks @bdash , I have done that too. Eventually I ended up using RealmSwift via cocoa pods, since it fetch directly from source as specified by you in other answers. 👍
