### ISSUE TITLE
swift compiler error    

### ISSUE THREAD

**Issue by AmalaPaindla** [realm/realm-cocoa#5582]
## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

x code .   swift language .  /Users/paindlaamala/Library/Developer/Xcode/DerivedData/LivePools-giwlaaumqmgvgncjllyfapkkurjb/Build/Products/Debug-iphoneos/Pods_LivePools.framework

**Comment by bdash** [comment]
Please provide the information requested in the issue template. Without it, we cannot understand what problem you're seeing, let alone begin to help you with it.
