### ISSUE TITLE
Ignore Model

### ISSUE THREAD

**Issue by zachwhelchel** [realm/realm-cocoa#5584]
Is it possible to flag a model as ignored so that it's not stored in Realm? For a lot of our models we have a code-generated portion and a non-code-generated portion. We've been keeping them separate/clean like this:

_Event.swift (<- Subclass of "Object", code-generated)
Event.swift (<- Subclass of "_Event", non-code-generated)

This has worked well and allowed us to keep code-generated files locked down... but when we look at the project in the Realm browser we can see that it has both _Event and Event sections in it. The _Event portion always has 0 objects. We would love to be able to flag that entire class such that it just doesn't store in Realm... is this possible?

**Comment by bdash** [comment]
Implement the following method in each of your classes:
```swift
public override class func shouldIncludeInDefaultSchema() -> Bool
```

Return `false` in the parent class, and `true` in the subclass. That should have the effect you're after.
