### ISSUE TITLE
Unable to build using Carthage: compiler Incompatibility errors

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-cocoa#5589]
## Goals
Build an iOS app using Carthage instead of Cocoapods

## Expected Results
Carthage should build Realm from scratch and result in successful build of usable frameworks

## Actual Results
Carthage fails due to a switch compiler version mismatch between the Realm binary and the current version of the Swift compiler in Xcode 9.2

```
espresso:iOSToDoApp spector$ carthage bootstrap
*** Downloading realm-cocoa.framework binary at "v3.1.0"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out realm-cocoa at "v3.1.0"
```
## Steps to Reproduce

1. Create an empty iOS project (the single view template for example)
2. Add a Cartfile 
2. Add repo name to include Realm:  `github "realm/realm-cocoa" `
3 Run `carthage update` or `carthage bootstrap`

Error above will happen during installation process

## Code Sample
n/a

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C205

/Applications/Xcode.app/Contents/Developer
Xcode 9.2
Build version 9C40b

/usr/local/bin/pod
1.4.0.rc.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

/usr/local/bin/carthage
0.27.0
(not in use here)

/usr/bin/git
git version 2.14.3 (Apple Git-98)
```: ?

iOS/OSX version: ? 11.x

**Comment by bdash** [comment]
The message is mostly harmless. Carthage only supports prebuilt binaries for a single Xcode version at a time. If you're using a different version of Xcode than the binaries were built with, Carthage will display this message and fall back to building Realm Swift from source.
