### ISSUE TITLE
addObject to array of primitives crashes

### ISSUE THREAD

**Issue by hyb175** [realm/realm-cocoa#5592]
## Goals

Add object to array of primitives, (in this case, array of NSDates)

## Expected Results

Successfully add a NSDate object to the array

## Actual Results

Adding object cause the app to crash

## Code Sample

```
// Counter.h
#import <Foundation/Foundation.h>
#import <Realm/Realm.h>

@interface Counter : RLMObject
  @property int id;
  @property int count;
  @property RLMArray<RLMDate> *dates;
@end
```

```
// SomeSyncFile.m
...
[[RLMRealm defaultRealm] transactionWithBlock:^{
    NSNumber *id = [NSNumber numberWithInt:1];
    NSLog(@"Setup id");
    Counter *counter = [Counter objectForPrimaryKey: id];
    NSLog(@"Got counter back with id");
    counter.count += 1;
    NSLog(@"increment count");
    NSDate *now = [NSDate date];
    NSLog(@"Got current date -> %@", now.description);
    [counter.dates addObject:now];
    NSLog(@"Add date object to dates");
}];
```

## Version of Realm and Tooling

Realm framework version: Using the Realm available through latest Realm-js with react native (v2.2.4)

Realm Object Server version: N/A

Xcode version: 9.2

iOS/OSX version: iOS 8 and above

Dependency manager + version: N/A

## Additional information
We are using Realm with React Native and trying to implement the native side as well.
It seems array of primitives is supported as recently and creating an object with array of primitives is working on the JS side. However, when I tried to update the object from the native side, it crashes with the following message

> MyApp(513,0x10e109340) malloc: *** mach_vm_map(size=105827997351936) failed (error code=3)
> *** error: can't allocate region
> *** set a breakpoint in malloc_error_break to debug
> libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

Also tried commenting out the line `[counter.dates addObject:now];` and it does not crash any more. It definitely looks like a problem with the newly supported array of primitives. Any help appreciated!

**Comment by dotcom900825** [comment]
Me and @hyb175 worked on the same project, I created a demo project to illustrate the issue: https://github.com/dotcom900825/rn-hybrid-realm-example.

We have a hybrid setup for our own project, it is using Realm.js 2.2.4 and Realm Cocoa 3.0.2 (As embedded binary), we realized that the Realm.js 2.2.4 is using Realm core 5.1.2 where Realm Cocoa 3.0.2 is using Realm Core 4.0.3.

Here is the screenshot of the exception, if I try the same `[person.dates addObject:now]`, the app will also crash with the same exception as @hyb175 showed above.

We are able to get around with the issues by upgrading Realm.js to 2.2.7 and Realm Cocoa to 3.1.1

**Comment by bdash** [comment]
Using two copies of Realm in the same application isn't something we test or support. Using two different versions of Realm in the same application is even less supported, and as you've observed, will almost certainly result in incorrect behavior.
