### ISSUE TITLE
LinkingObjects empty for newly added objects

### ISSUE THREAD

**Issue by humblehacker** [realm/realm-cocoa#5598]
## Goals
Access `LinkingObjects` on a new object added to a Realm.

## Expected results
After adding an object with a `LinkingObjects` property to a Realm, accessing the `LinkingObjects` property returns the expected results.

## Actual results
The `LinkingObjects` property returns no results.  Note that if I use an object retrieved from a Realm rather than the original object added to the Realm, the `LinkingObjects` property works as expected.

## Steps to reproduce
1. Define two Object classes with a bidirectional relationship, with a `LinkingObjects` property that points from child to parent.
2. Create one object of each class, and connect the child to the parent.
3. Create a Realm and add the parent object to it.
4. Access the `LinkingObjects` property on the child object.

## Code sample that highlights the issue
 [Playground project](https://github.com/humblehacker/RealmLinkingObjectsIssue)

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47

/Applications/Xcode-9.2.app/Contents/Developer
Xcode 9.2
Build version 9C40b

/usr/local/bin/pod
Realm (3.1.0)
RealmSwift (3.1.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

/usr/local/bin/carthage
0.27.0
(not in use here)

/usr/local/bin/git
git version 2.16.1
```

**Comment by JettF** [comment]
I am experiencing this issue as well.

**Comment by maroony** [comment]
This bug is still present in 3.19.0. What's interesting: If you create a second child object and put it to the parent with the first child object, all is working as expected for the second child.

**Comment by amkomatz** [comment]
Any updates or workarounds for this? Our app is facing this issue in several places.

**Comment by amkomatz** [comment]
Okay, after further inspection, I can confirm that this is only happening on instances that were inserted into Realm. If you were to do a reload of that object, any `LinkingObjects` properties work fine. That appears to be the only workaround for now.

**Comment by ericjordanmossman** [comment]
I updated @humblehacker 's project to Swift 5, RealmSwift 4.4.1 and line 33 now shows expected results.

If anyone is still seeing the issue after 4.3.0 ([#6834](https://github.com/realm/realm-cocoa/pull/6384)), please comment.
