### ISSUE TITLE
Parsing JSON and Adding them to realm object takes too long time. What should i do?

### ISSUE THREAD

**Issue by iostransavia** [realm/realm-cocoa#5599]
## Expected Results
It's too long for this app

## Actual Results
It takes 20 sec

## Code Sample
`func downloadCities(link: String){
    let url = URL(string: link)
    URLSession.shared.dataTask(with:url!, completionHandler: {(data, response, error) in
        guard let data = data, error == nil else { return }
        do {
            let json = try JSONSerialization.jsonObject(with: data, options: .allowFragments) as! [String:Any]
            let cities = json["response"] as? [[String: Any]]
            let request = json["request"] as? [String: Any]
            let language = request!["lang"] as? String
            let main = DispatchQueue.main
            main.async {
            try! realm.write {
            for item in cities! {
                let country_code = item["country_code"] as? String
                var country : Country!
                if let count = allCountries.index(where: {$0.code == country_code! }){
                    country = allCountries[count]
                }
                let newCity = CityCode()
                newCity.code = item["code"] as! String
                newCity.name = item["name"] as! String
                newCity.lang = language!
                newCity.country = country
                realm.add(newCity)
                print(newCity)
                }
            }
            }
        } catch let error as NSError {
            print(error)
        }
    }).resume()
}`

## Version of Realm and Tooling

Realm framework version: 3.1.0

Realm Object Server version: ?

Xcode version: 9

iOS/OSX version: 11

Dependency manager + version: ?

**Comment by Zhuinden** [comment]
``` swift
func downloadCities(link: String){ 
    let url = URL(string: link) 
    URLSession.shared.dataTask(with:url!, completionHandler: {
        (data, response, error) in guard let data = data, error == nil else { return } 
        do { 
            let json = try JSONSerialization.jsonObject(with: data, options: .allowFragments) as! [String:Any] 
            let cities = json["response"] as? [[String: Any]] 
            let request = json["request"] as? [String: Any] let language = request!["lang"] as? String 
            let main = DispatchQueue.main main.async { 
                   try! realm.write { 
                          for item in cities! { 
                                let country_code = item["country_code"] as? String var country : Country! 
                                if let count = allCountries.index(where: {$0.code == country_code! }) { 
                                       country = allCountries[count] } 
                                       let newCity = CityCode() newCity.code = item["code"] as! String 
                                       newCity.name = item["name"] as! String 
                                       newCity.lang = language! 
                                       newCity.country = country 
                                       realm.add(newCity) 
                                       print(newCity) 
                                 }
                             }
                         } 
                  } catch let error as NSError { print(error) } }).resume() }
```

**Comment by dotcom900825** [comment]
I think one thing you can try out is instead of calling `realm.add(newCity)` every single time when you are iterating through the list, try adding them to a mutable array and in the end call realm.add(cityArray) instead. See if that give you any performance improvement

**Comment by bmunkholm** [comment]
Closing since ii is stale.
