### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Vactorwang** [realm/realm-cocoa#5601]
## Goals

let realm = try! Realm()
let sets: Results<TradeCurrencyPair> = realm.objects(TradeCurrencyPair.self)

## Expected Results

The sets autorealse
## Actual Results

The sets donot autorealse
## Version of Realm and Tooling

Realm framework version: ?
3.1.1
Realm Object Server version: ?
3.1.1
Xcode version: ?
9.2   swift
iOS/OSX version: ?
11.2 ios
Dependency manager + version: ?

**Comment by bmunkholm** [comment]
Please provide a repro case that clearly demonstrates the problem. Thanks!

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
