### ISSUE TITLE
Use * as regular character when filtering object with 'LIKE' in Realm

### ISSUE THREAD

**Issue by titkov5** [realm/realm-cocoa#5602]
I try to find string which contains substring with * symbol. At following example string should confirm pattern (any symbols '*' any symbols 'p' any symbols) . I try this code to search objects from Realm
```
class ServiceMessage: Object {
  @objc dynamic var desc = ""
}

let realm = try! Realm()

let dataSource = [
    "Domain CheckService",
    "IMEI check",
    "Compliant about service provider",
    "Compliant about TRA",
    "Enquires",
    "Suggestion",
    "SMS* S[pam",
    "Poor Coverage",
    "Pure *Signal",
    "Help Salim"
]

for text in dataSource {
    let sm = ServiceMessage()
    sm.desc = text;
    try! realm.write {
        realm.add(sm)
    }
}


let searchString = "*\\**p*"
let predicate = NSPredicate(format: "SELF.desc LIKE[c] %@", searchString)
let errors = realm.objects(ServiceMessage.self).filter(predicate)

```
I got nothing. If i try to filter simple array of strings with this Predicate everything work fine.  I try add [w] after LIKE it's doesn't help me. I use the same predicate but with realm it doesn't work properly, could you help me please.

Realm framework version: 3.1.1
Realm Object Server version: 3.1.1
Xcode version: 9.2
OSX version: 10.12.6
Dependency manager + version: ?

**Comment by jsflax** [comment]
Hey @titkov5,
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the realm tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).
