### ISSUE TITLE
Realm Swift overrides the swizzling made to managed properties.

### ISSUE THREAD

**Issue by minuscorp** [realm/realm-cocoa#5604]
## Goals

So the main issue here is the following, I know that Realm uses swizzling under the hood in order to listen the value changes in the properties of the model. The goal here is to achieve a swizzling that, above what Realm does, is capable of add a layer that encapsulates the Realm swizzled behavior. This might be useful if, for example, you want to make a `getter` listener that, automatically if the object is already managed, open and closes a write operation linked to a certain serial queue, in a way that `realm.write { }` shouldn't be necessary anymore. The queue performs some optimizations, so if the write queue is the same that the predefined at initialization of the object, the write is made synchronously, and if not, it could be done async, or sync using a semaphore. 

## Expected Results

So after defining all the swizzling that does the behavior explained above, this should work:

```swift
class ob: Object {
    @objc dynamic var property: String = ""
}

let obj = Ob()
let realm = try! Realm()
obj.property = "change" // This is not intercepted by Realm because the object is not managed, my swizzling does nothing also in this case.
try! realm.write {
    realm.add(obj)
}
// Now that the object is managed, lets make a change...
obj.property = "crash" // This crash because of RLMException, it is out of a write scope. So the swizzling made by the user that wraps this is a write operation is not being called, because Realm has overwrited it when the manage is being done.
```
If more details of the swizzling being made is necessary I can provide it, but making things shorter, using Sourcery creates a designed swizzled method for every model property setter to wrap it in a write operation in a certain queue (always the same and with a serial behavior).

I don't know if this can even be adopted by the Realm core itself, easing the task of writing and possible mistakes that can be easily be made when using Realm in a multithreaded environment.

Thank you very much! 🚀 

## Version of Realm and Tooling

Realm framework version: 3.1.1

Realm Object Server version: -

Xcode version: 9.2

iOS/OSX version: 11.2

Dependency manager + version: Cocoapods 1.4.0

**Comment by bdash** [comment]
Is this an enhancement request? If so, would you mind being more explicit about what it is you want us to provide?

**Comment by minuscorp** [comment]
Not sure if this should be a fixed addition to Realm or just something that the developer should be able to achieve using swizzling... But the main objective of both cases is to remove any references of `.write` operations in favor of Realm automatically detaching the object from the thread, create a thread safe reference, and perform (in a queue that is shared across the object references in the application life cycle) the operation of writing synchronously, removing any chance that the user messes up the threads and gets crashes out weird race conditions.

**Comment by bdash** [comment]
> But the main objective of both cases is to remove any references of .write operations in favor of Realm automatically detaching the object from the thread, create a thread safe reference, and perform (in a queue that is shared across the object references in the application life cycle) the operation of writing synchronously, removing any chance that the user messes up the threads and gets crashes out weird race conditions

I'm not sure that the behavior you describe is actually desirable. One obvious result of it would be that the effects of setting a property are not reflected on the current thread until a future runloop iteration.

There's also the fundamental issue that write transactions are akin to taking a lock: all logically-related mutations need to be made within a single write transaction, and cannot be safely split across multiple transactions. Having each mutation of a property result in an independent write transaction would result in object invariants being violated due to the potential for modifications to multiple properties on an object being interleaved with some independent modifications to the same object.

**Comment by minuscorp** [comment]
As far as I can understand (because I don't know the deepest parts of the library), all changes made for an object (using for instance a safe thread reference) aren't shared across all threads instantly? As for the second part you explain, I cannot fully understand that rationale, is something related to how transactions are actually scheduled in blocks before being committed into storage? Is a performance issue edit a single property of an object for each transaction? And lastly, is there some **safe** approach to secure writes of managed objects in a multithreaded and multiqueue environment? Rx and other Reactive approaches heavily rely on threading and scheduling in order to perform asynchronous operations over time, in most cases these triggers are not under concrete time circumstances where the developer can ensure that there are not going to be race conditions between operations, and this make me wonder and try to find solutions that could help avoid tons (even yourself might suffered) of exceptions during write transactions. I'd like to investigate some approach that could ease this long discussed issue (there are hundreds of them in Realm history) and reach a final solution where the foundations of the library are respected but some steps are polished in favor of the developer. Thank you!!

**Comment by minuscorp** [comment]
The approach I have proposed is the following simple and basic example (without `Sourcery`), using RxSwift to perform the asynchronous work through a serial queue scheduler:

```swift
//: Playground - noun: a place where people can play

import UIKit
import Dispatch
import RxSwift
import RealmSwift

class User: Object {
    @objc dynamic var id: String = UUID().uuidString
    @objc dynamic var name: String = ""
    @objc dynamic var surname: String = ""
}

struct AssociatedKeys {
    static var queue: UInt8 = 0
}

protocol SerialQueue {
    
    func performSerial<O: Object>(with reference: ThreadSafeReference<O>, block: @escaping ((_ object: O) -> Void)) -> Completable
}

extension SerialQueue {
    
    private(set) var queue: SerialDispatchQueueScheduler {
        get {
            guard let value = objc_getAssociatedObject(self, &AssociatedKeys.queue) as? SerialDispatchQueueScheduler else {
                return SerialDispatchQueueScheduler(qos: .default)
            }
            return value
        }
        set(newValue) {
            objc_setAssociatedObject(self, &AssociatedKeys.queue, newValue, objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }
        
    
    func performSerial<O: Object>(with reference: ThreadSafeReference<O>, block: @escaping ((_ object: O) -> Void)) -> Completable {
        print("This gets called")
        return Completable.create { completable in
            print("This works")
            let realm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "MyInMemoryRealm"))
            print("This works too")
            guard let object = realm.resolve(reference) else { return Disposables.create() }
            try! realm.write {
                block(object)
            }
            completable(.completed)
            return Disposables.create()
        }
        .subscribeOn(self.queue)
    }
}
extension User: SerialQueue { }

var hasSwizzled = false

internal func swizzle(_ v: User.Type) {
    let originalMethod = class_getInstanceMethod(v, #selector(setter: User.name))!
    let swizzledMethod = class_getInstanceMethod(v, #selector(setter: User.swizzledName))!
    
    let didAddViewDidLoadMethod = class_addMethod(v,
                                                  #selector(setter: User.name),
                                                  method_getImplementation(swizzledMethod),
                                                  method_getTypeEncoding(swizzledMethod))
    
    if didAddViewDidLoadMethod {
        class_replaceMethod(v,
                            #selector(setter: User.swizzledName),
                            method_getImplementation(originalMethod),
                            method_getTypeEncoding(originalMethod))
    } else {
        method_exchangeImplementations(originalMethod, swizzledMethod)
    }
}

extension User {
    
    @objc dynamic internal var swizzledName: String {
        set {
            if let _ = self.realm, !self.isInvalidated {
                let ref = ThreadSafeReference(to: self)
                _ = self.performSerial(with: ref) { user in
                    user.swizzledName = newValue
                }
                .subscribe()
            } else {
                self.swizzledName = newValue
            }
        }
        get {
            return self.swizzledName
        }
    }
    
    final public class func doSwizzleStuff() {
        guard !hasSwizzled else { return }
        
        hasSwizzled = true
        swizzle(self) /* This is pseudo - run your method here */
    }
}

extension User: PropertyNames { }

User.doSwizzleStuff()

let user: User = User()

user.name = "Jorge" // This works as intended, swizzled method is called and, because is not a managed object, it just sets the value to the object.

let realm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "MyInMemoryRealm"))

try! realm.write {
    realm.add(user)
}
print(user.name)
print(user.realm)
user.name = "Herrero" // This crashes because it is not in a write transaction, even when I have swizzled its setter to wrap it in a write transaction.
```

**Comment by minuscorp** [comment]
Is this getting some attention? ^^

**Comment by bdash** [comment]
I explained above the serious issues with what you propose. We're unlikely to expend any engineering effort to make it possible for users to shoot themselves in the foot like this.

**Comment by minuscorp** [comment]
Alright! I'll close this then. Thank you for the support!
