### ISSUE TITLE
Realm fire notification everytime receive a new object regardless of equatable?

### ISSUE THREAD

**Issue by peihsendoyle** [realm/realm-cocoa#5606]
## Goals
- We have one object in the database, and it's observed by Realm Notification. When we receive a new object with the same id with the first one. Realm know which key is changed and fire notification, if not Realm ignore it.

## Expected Results
- Realm know how to compare between old and new object.

## Actual Results
- Realm always fire notification.

**Comment by peihsendoyle** [comment]
Nobody helps me in this case 😢 , really?

**Comment by ivanmih** [comment]
Hey @bmunkholm shouldn't this behavior be considered a bug?
If we do realm.write and the object with all its properties is the same we really do not expect notification to be triggered.

**Comment by bmunkholm** [comment]
Thanks for the feedback - I'll let @tgoyne comment if this is a bug or working as intended.

**Comment by tgoyne** [comment]
v3.16.0 added the ability to specify if you would like to produce notifications even if the values have not changed when calling `realm.create()`.
