### ISSUE TITLE
Insanely large database upon creation with no deletion ever

### ISSUE THREAD

**Issue by fpillet** [realm/realm-cocoa#5607]
## Goals
I'm using Realm on Mac to create and provision a database. I have a middle-sized model (25 classes) and not that many objects (two models have 30k objects, the other ones a few tens or hundreds)

I prepare all my objects, create a new database, write and commit. At this point, Realm (3.1.0) has created a 75MB database. If I later compact this database at launch, it shrinks to 4MB.

## Expected Results
A new database from which I never deleted any object should (and used to) be optimal in file size.

## Actual Results
This 75MB database is full of emptiness. This doesn't use to be the case: Realm 2.x never exhibited such a behaviour.

## Version of Realm and Tooling
Realm framework version: 3.1.0
Xcode version: 9.2
iOS/OSX version: macOS 10.12.6
Dependency manager + version: Cocoapods 1.4.0

**Comment by bmunkholm** [comment]
@fpillet Sorry about the lack of response. Is this still an issue or have you resolved it?
Sounds like perhaps you are holding on to some older versions of the DB. Some things have been optimized since. Have you tried the latest version?

**Comment by fpillet** [comment]
@bmunkholm I have not changed my code so it is still happening I guess -- I remember @icanzilb finding the cause of the problem and suggesting a fix, although I didn't implement his fix -- mine is to copy the DB an open it separately, Realm caches access to database I can perform a shrink on the same DB.

**Comment by icanzilb** [comment]
I had last tried this few months ago - the case was that whenever there is an attached debugger to the process the database file exploded, the same code would create a "normally" sized file when run out of Xcode.

**Comment by fpillet** [comment]
Ha! it's possibly related since this tool is usually being launched from Xcode.

**Comment by bmunkholm** [comment]
Thanks @icanzilb and @fpillet - I'll then close this issue.
