### ISSUE TITLE
pod 'Realm', '~> 0.102.1'

### ISSUE THREAD

**Issue by pjebs** [realm/realm-cocoa#5608]
I mentioned a few years ago that I was stuck on `v0.102.1`: https://github.com/realm/realm-cocoa/issues/3879

I have now finally got a computer fast enough to run Xcode 7.3. (Previously max was 7.2 due to macOS Yosemite support being dropped).

Is it easy for me to upgrade to the latest version of REALM (or a later version) with minimal code changes given I need to deploy  and get app approval within the next few days.

**Comment by pjebs** [comment]
@stel @bdash @JadenGeller

**Comment by bdash** [comment]
Please don't ping random people on GitHub issues. It is rude.

If I understand correctly, you're asking if it'll be easy to update from a pre-1.0 version of Realm using Xcode 7.x to a current version of Realm that requires Xcode 8.3 or greater. It's certainly doable, but as the version number implies there have been a number of API changes in that time period. You can learn about these API changes by reading over our release notes. It's impossible to know whether they'll affect you, and how much work adapting to them will take. The only way to find out would be to update and see what problems you run into.

**Comment by pjebs** [comment]
Thank you for response. I appreciate that.

But please don't pretend that the social conventions have been unambiguously established yet in terms of GitHub etiquette. You were not ransom because you responded to my prior issue which I linked to above.
