### ISSUE TITLE
try catch for .filter()

### ISSUE THREAD

**Issue by zachwhelchel** [realm/realm-cocoa#5612]
From what I'm reading it seems like Realm intentionally doesn't allow you to catch errors if your predicate is invalid? (like mentioning a property that doesn't exists for example)

`            do {
                results = try Datastore.sharedInstance.realm!.objects(objectType).filter(predicate).sorted(by: sortDescriptors)
            } catch {
                print("WE CAUGHT A BAD REALM QUERY")
            }
`

I'm trying to call for results here in a generic way in which the query itself itself is prone to error. Is there no way to fail out of this gracefully? I tried wrapping in a do catch as seen above but I get a message that: "No calls to throwing functions occur within 'try' expression".

So is there no way to fail gracefully if your predicate is invalid?

**Comment by tgoyne** [comment]
An objective-c exception is thrown, which is not catchable from Swift.

The assumption behind the API was that all queries would be constructed by the app developer, and so the way to "handle" errors is for the developer to read the error message and correct the invalid code. If you have user-entered predicates this doesn't hold, and we really should have some sort of validation method to handle that case. Currently the best you can do is write an obj-c helper function which tries to perform the query within a `@try/@catch`.

**Comment by zachwhelchel** [comment]
@tgoyne Thanks for the reply. Are there are examples of calling this in an obj-c helper function?

**Comment by bmunkholm** [comment]
Sorry tgoyne didn't get back on that. I assume you have come past this by now so closing.
