### ISSUE TITLE
addOrUpdateObject will set nested object's attributes to nil if not specified

### ISSUE THREAD

**Issue by dotcom900825** [realm/realm-cocoa#5613]
## Goals

When using `[realm addOrUpdateObject]` for an object that has nested association, if this nested associated object already exists and if I don't explicitly set the attributes for the nested object, `addOrUpdateObject` will override the existing nested object's unspecified field with nil value.

This behavior is different from the Realm.js implementation where the unspecified attributes value gets preserved in the nested object upsert.

Example:
```
@interface Car : RLMObject
  @property int id;
  @property NSString *make;
  @property NSString *model;
  @property NSInteger miles;
@end

@implementation Car
  + (NSDictionary *)defaultPropertyValues {
    return @{@"miles" : @0};
  }

  + (NSString *)primaryKey {
    return @"id";
  }
@end

RLM_ARRAY_TYPE(Car)

@interface Person : RLMObject
  @property int id;
  @property NSString *name;
  @property NSDate *birthday;
  @property RLMArray<Car> *cars;
  @property RLMArray<RLMString> *options;
  @property RLMArray<RLMDate> *dates;
  @property NSData *picture;
@end

@implementation Person
  + (NSArray *)requiredProperties {
    return @[@"name", @"birthday", @"options", @"dates"];
  }
  + (NSString *)primaryKey {
    return @"id";
  }
@end

 RLMRealm *realm = [RLMRealm defaultRealm];
  
    [realm transactionWithBlock:^{
      [realm addOrUpdateObject:[[Car alloc] initWithValue:@{@"id" : @2, @"miles" : @2000, @"make" : @"Nissan", @"model" : @"GTR"}]];
      Car *car = [[Car alloc] initWithValue:@{ @"id" : @2 }];
      [realm addOrUpdateObject:[[Person alloc] initWithValue:@{@"id" : @2, @"name" : @"test", @"birthday" : [NSDate dateWithTimeIntervalSinceNow:100], @"options" : @[@"123", @"456"], @"cars" : @[car]}]];
    }];
```
## Expected Results

Expect all the make, model and miles field's value stays the same.
## Actual Results

In the end for the car object with id of 2, the make, model fields will become nil and miles will become the default value 0.
## Steps to Reproduce and code sample

I have created a example repo to reproduce the issue: https://github.com/dotcom900825/RealmUpsertExample

in the App.js, you can find the javascript implementation of the model and the upsert operation to update a nested car object.

in the ios/ExampleBridgeManager.m file, you can find the Objective-C implementation of the model and the upsert operation update a car object.

You can examine the Realm file through the Realm browswer to see the difference. In the end, Car id 2's make and model all becomes nil and miles become 0.

## Version of Realm and Tooling

Realm framework version: Realm Cocoa 3.1.1 and Realm.js 2.2.7

Realm Object Server version: ?

Xcode version: 9.2

iOS/OSX version: macOS Sierra version 10.12.6, iOS 11

Dependency manager + version: NPM

**Comment by tgoyne** [comment]
The object you are passing to `addOrUpdateObject:` does not have any "unspecified" values; it just has some properties which happen to be `nil`, and in objective c a property which is `nil` because no value was assigned to it is not distinguishable from a property which was explicitly set to `nil`.

In the Javascript code you're calling `create()` with an object which does not have the field at all, and doing the same thing in obj-c (calling `createOrUpdateObject:` with a dictionary that does not contain the fields you don't want to touch) will have the same result.

**Comment by dotcom900825** [comment]
@tgoyne Thanks for your prompt answer, I just tried the 
`[Car createOrUpdateInDefaultRealmWithValue:@{@"id" : @2, @"name" : @"test", @"birthday" : [NSDate dateWithTimeIntervalSinceNow:100], @"options" : @[@"123", @"456"], @"cars" : @[car]}];` 

to replace my original

`[realm addOrUpdateObject:[[Person alloc] initWithValue:@{@"id" : @2, @"name" : @"test", @"birthday" : [NSDate dateWithTimeIntervalSinceNow:100], @"options" : @[@"123", @"456"], @"cars" : @[car]}]]`

and is working perfectly fine now;
