### ISSUE TITLE
Value of oldProperty is always nil

### ISSUE THREAD

**Issue by TheHmmka** [realm/realm-cocoa#5616]
## Expected Results
Old value must not be nil.

## Actual Results
old value of property is nil.

## Steps to Reproduce
See code below.

## Code Sample
notificationToken = picture.observe({ [weak self] (change) in
                guard let strongSelf = self else { return }

                switch change {
                case .change(let properties):
                    for property in properties {
                        if property.name == "selectedColor", let newColor = property.newValue as? Color, let oldColor = property.oldValue as? Color, newColor != oldColor  {
                            strongSelf.collectionView.reloadData()
                            if let value = property.newValue as? Color {
                                strongSelf.scrollTo(value)
                            }
                        }
                    }
                    break
                case .deleted:
                    break
                case .error(_):
                    break
                }
            })

## Version of Realm and Tooling

Realm framework version: 3.1.1

Realm Object Server version: ?

Xcode version: 9.2 (9C40b)

iOS/OSX version: iOS 11

Dependency manager + version: CocoaPods 1.4.0

**Comment by bmunkholm** [comment]
@TheHmmka Is this still a problem or did you get past this? It would help a lot if you are able to provide a self-contained repro case that demonstrates the problem you are facing. Thanks!

**Comment by hk05** [comment]
I encountered the same with a simple Bool. When I change the Boolean in RealmStudio, the old and new values are observed correctly, but when I change the boolean in code, the old blue is always nil.

**Realm property:**
@objc dynamic var show: Bool = false

**function on Realm object:**
  func toggleShow(in realm: Realm = try! Realm())  {
        try! realm.write {
            show.toggle()
        }
  }

**Observer:**
token = currentProfile?.observe { change in
        log.debug("Change: \(change)")

**log:**
Change: change([RealmSwift.PropertyChange(name: "show", oldValue: **nil**, newValue: Optional(0))])

**Comment by LorienMan** [comment]
@bmunkholm Can you help please? Same even with code from docs, old values are still nil

Observing:
```
class StepCounter: Object {
    @objc dynamic var steps = 0
}

let stepCounter = StepCounter()
let realm = try! Realm()
try! realm.write {
    realm.add(stepCounter)
}
var token : NotificationToken?
token = stepCounter.observe { change in
    switch change {
    case .change(let properties):
        for property in properties {
            if property.name == "steps" && property.newValue as! Int > 1000 {
                print("Congratulations, you've exceeded 1000 steps.")
                token = nil
            }
        }
    case .error(let error):
        print("An error occurred: \(error)")
    case .deleted:
        print("The object was deleted.")
    }
}
```

Updates are in the same thread:
```
let realm = try! Realm()
try! realm.write {
    stepCounter.steps += 1
}
```

Properties
```
(lldb) po properties
▿ 1 element
  ▿ 0 : PropertyChange
    - name : "steps"
    - oldValue : nil
    ▿ newValue : Optional<Any>
      - some : 6
```

Podfile.lock
```
  - Realm (3.13.1):
    - Realm/Headers (= 3.13.1)
  - Realm/Headers (3.13.1)
  - RealmSwift (3.13.1):
    - Realm (= 3.13.1)
```

But everything works correct when I manually call **realm.refresh()**:
```
let realm = try! Realm()
try! realm.write {
    stepCounter.steps += 1
}
realm.refresh()
```

**Comment by tgoyne** [comment]
`oldValue` is not populated when the write was made on the same thread as the notification due to an implementation limitation (the value no longer exists anywhere by the time the notification is generated).

This is documented in the description of the `oldValue` property ([obj-c](https://realm.io/docs/objc/3.13.1/api/Classes/RLMPropertyChange.html#/c:objc(cs)RLMPropertyChange(py)previousValue), [swift](https://realm.io/docs/swift/3.13.1/api/Structs/PropertyChange.html#/s:10RealmSwift14PropertyChangeV8oldValueypSgvp)])

**Comment by hk05** [comment]
Hi LorienMan,

Unfortunately I never got a good understanding on this issue of oldValues always being nil. I wasted a good amount of time on this, and still could not figure it our. Eventually, I did circumvent this issue by using standard swift observers, that is:

`addObserver(self, forKeyPath: #keyPath(theKeyPath), options: [.old, .new], context: nil)`
`self.removeObserver(self, forKeyPath: #keyPath(theKeyPath))`
`override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?)`

With this, you can obtain the old value as intended.

**Comment by hien352911** [comment]
Perhaps you are testing by changing the value directly in the code. I have tested the same. The old value is always nil. But if the value is changed at the realm studio or view controller, old value is always correct.
