### ISSUE TITLE
Crash when filtering empty Realm List

### ISSUE THREAD

**Issue by Moriquendi** [realm/realm-cocoa#5619]
## Goals
Filter `List<Object>` using predicate format.

```swift
public class MyObject: Object {
    internal(set) public var myList = List<Event>()

    func something() {
        let events = myList.filter("type == 2048")
        ...
    }
}
```

## Expected Results
Filtered results are returned.

## Actual Results
Crash.
```swift
- (RLMResults *)objectsWithPredicate:(NSPredicate *)predicate {
    @throw RLMException(@"This method may only be called on RLMArray instances retrieved from an RLMRealm");
}
```

## Steps to Reproduce
The crash occurs when the `List` is empty and I try to filter it.
If I add some events to that list, it works as expected.
For example, when List is not empty, `myList` has realm.
```swift
print(myList.realm) // Yup, non-nil value
```

But realm is nil when it's empty.
```swift
print(myList.count) // 0
print(myList.realm) // nil
```

## Version of Realm and Tooling
Realm framework version: 3.0.2

Xcode version: 9.2

iOS version: 11.2.5

Dependency manager + version: CocoaPods

**Comment by bdash** [comment]
Are you sure the problem is empty vs non-empty, and not for managed vs non-managed objects as the exception suggests? Can you please share a more complete code snippet that reproduces the problem?

**Comment by Moriquendi** [comment]
@bdash Ayayay, you are right.
I was creating a new empty list somewhere else in the code and overriding the one I was filtering. That was causing the crash.

Sorry for bothering!
