### ISSUE TITLE
To-many relation with primary key, giving multiple objects with same primary key in relation

### ISSUE THREAD

**Issue by jkmathew** [realm/realm-cocoa#5623]
I have a class `A`(with primary key) which contains a to-many relation to `B`(with primary key).
If I create object of `B` with existing primary key and add to A's relation, The relation shows count more than 1 and if I fetch All objects of `B` from db, it shows count 1
My Schema looks like
```
class A: Object {
    @objc dynamic var text: String?
    @objc dynamic var idx: Int = 0
    let bList = List<B>()
    override static func primaryKey() -> String? {
        return "idx"
    }
}

class B: Object {
    @objc dynamic var text: String?
    @objc dynamic var idx: Int = 0
    let aList = LinkingObjects(fromType: A.self, property: "bList")
    
    override static func primaryKey() -> String? {
        return "idx"
    }
}
```

## Expected Results
Once I add an object of `B` with existing primary key, it should also update in `A`'s relation.

## Actual Results
Adding duplicate objects to `A`'s relation, But it is not present if I fetch all objects of `B`

## Steps to Reproduce

```
func check1() {
    let realm = try! Realm()
    let a: A
    if let existing = realm.object(ofType: A.self, forPrimaryKey: 10) {
        a = existing
    } else {
        a = A()
        a.idx = 10
        a.text = "Test modified"
        do {
            try realm.write {
                realm.add(a, update: true)
            }
        } catch let error {
            print("error 1 \(error)")
        }
    }
    
    let b = B()
    b.idx = 11
    b.text = "child modified"
    
    do {
        try realm.write {
            realm.add(b, update: true)
            a.bList.append(b)
        }
    } catch let error {
        print("error 1 \(error)")
    }
    
    print("a.bList.count \(a.bList.count)")
    print("realm.objects(B.self).count \(realm.objects(B.self).count)")
}
```
And  call the function twice
like
```
check1()
check1()
```
This will print
```
a.bList.count 1
realm.objects(B.self).count 1
a.bList.count 2
realm.objects(B.self).count 1
```

We can also see weird thing in realm browser also
![1](https://user-images.githubusercontent.com/1732366/36488930-b31c9400-174a-11e8-91d1-024e95a9c979.png)

## Version of Realm and Tooling

Realm framework version: `RealmSwift (3.1.1)`

Realm Browser version: `3.0.1`

Xcode version: `9.0`

iOS/OSX version: `iOS 11.0`

Dependency manager + version: `Cocoapods 1.4.0`

**Comment by bdash** [comment]
The code you've shared adds the _same `B` instance_ to `A.bList` multiple times. There's only one `B` instance involved. If you don't want it to appear in `bList` multiple times, don't append it multiple times.

**Comment by jkmathew** [comment]
@bdash Okay, then should I check each time before adding?

like 
```
if a.bList.contains(b) {
    print("not added")
} else {
    a.bList.append(b)
}
```

**Comment by bdash** [comment]
Sure, that’s one way to accomplish that.
