### ISSUE TITLE
can not pod install the Realm

### ISSUE THREAD

**Issue by elliotxin** [realm/realm-cocoa#5629]
after i type "pod install", some error coming:
"
Installing Realm (3.1.1)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 2.2.9
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-2.2.9.tar.xz
	curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

[!] Automatically assigning platform `ios` with version `11.2` on target `Realm` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
"
Please help me figure out how to fix this issue.

**Comment by bdash** [comment]
Does it happen if you simply try again? errno 54 is "connection reset by peer", which indicates your connection to static.realm.io was interrupted.

**Comment by elliotxin** [comment]
After i reinstall, then it's successful, thanks a lot.
