### ISSUE TITLE
Realm UI Issue. Id stored in Realm OS is rounding Off. When sending a int value from iOS app, the value is getting stored and getting retrieved too. But somehow, the int getting stored is rounding off in Realm OS

### ISSUE THREAD

**Issue by TechnoBlogger14o3** [realm/realm-cocoa#5630]
## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by bdash** [comment]
Please provide the information requested in the issue template. The body of the issue is also a much more appropriate place to place the information than the title of the issue.
