### ISSUE TITLE
Realm doesn't reconnect, after device goes to sleep automatically, and 5-10 minutes pass

### ISSUE THREAD

**Issue by probi86** [realm/realm-cocoa#5631]
## Goals
Make sure device is always in sync when there is network connection and app is opened.

## Expected Results
When device sleeps, and 5-10 minutes pass, reopen app: changes made should be pushed, changes on other devices should be received.

## Actual Results
In the steps described below, the device gets out of sync. 

## Steps to Reproduce
1. Open synced realm using asyncOpen
2. Let the device go to sleep (note: device should not be connected via lightning cable)
3. Wait 5-10 minutes
4. Reopen app
5. Make changes either on this device or on other connected devices
6. Changes from this device are not pushed, changes on other synced devices are not received

## Version of Realm and Tooling

Realm framework version: RealmSwift 3.1.1

Realm Object Server version: ROS 2.0

Xcode version: 9.2 (9C40B)

iOS/OSX version: iOS 11.2.6

Dependency manager + version: Cocoapods v 1.3.1

**Comment by bmunkholm** [comment]
Do you have a small app where this can be demonstrated? It works fine on an app I tested.

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
