### ISSUE TITLE
`Realm.asyncOpen` callback not called

### ISSUE THREAD

**Issue by i-schuetz** [realm/realm-cocoa#5635]
## Goals
Open the realm with `Realm.asyncOpen`

## Expected Results
The callback is called - either with success or an error

## Actual Results
The callback is never called. Also, no log messages.

## Steps to Reproduce
Logged in via `SyncUser.logIn(with: credentials, server: authUrl)`. With the returned user, and the other config data (the sync server url, added below, and an array with my object types), create a `Realm.Configuration` and then with that call `Realm.asyncOpen`.

This started happening after I switched to Realm Cloud beta - with the previous local ROS it was working correctly. I, too, just upgraded to Realm 3.1.1 (was 3.0.2 before) to see if the problem was my version being outdated, but the same problem still happens.

When I say "switched to Realm Cloud beta" I mean only that I updated the auth and sync urls.
The urls I have now are:
Sync url: realms://myapp.us1.cloud.realm.io
Auth url: https://myapp.us1.cloud.realm.io

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1036

/Applications/Xcode.app/Contents/Developer
Xcode 9.2
Build version 9C40b

/usr/local/bin/pod
1.3.1
Realm (3.1.1)
RealmSwift (3.1.1)
RealmSwift (~> 3.1.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.25.0
(not in use here)

/usr/bin/git
git version 2.14.3 (Apple Git-98)
```

**Comment by i-schuetz** [comment]
Tried again with Realm 3.3.0. Still happening. I debugged in Realm and found this is the line where it hangs:

`session->wait_for_download_completion([=](std::error_code error_code) {` in `RLMRealm.mm`

Is there maybe a timeout missing somewhere?

**Comment by i-schuetz** [comment]
Ok, I found out why it can't connect - I had a mistake in the realm sync url (was not passing the realm path). Still, this is a bug - there should be an error.

**Comment by tgoyne** [comment]
This error is probably reported to the handler set at `SyncManager.shared().errorHandler`, but that's not super useful as we don't expose a way to manually cancel the wait from there.
