### ISSUE TITLE
Realm objects are not updated when collection notification is posted

### ISSUE THREAD

**Issue by hipwelljo** [realm/realm-cocoa#5638]
## Issue Description
I am seeing a crash that occurs because the data source is not correctly updated when a collection notification is posted after deleting a nested object. This results in a crash, array index out of bounds, trying to create a cell at an index path where no realm object exists.

I have an Artist object that contains many Album objects, and each Album object contains many Song objects. I’m observing changes to the artist (and thus all nested properties). When I delete all the songs in an album, then delete the album itself, I’m properly notified of the song deletions. But when the album is deleted, the observer block is called, says the artist has been modified but the album still exists in the artist and it contains 0 songs, which is not true because the album was deleted. This results in a crash trying to populate the data because we reloaded the table but it thought an album existed when it actually no longer does.

## Steps to Reproduce
1) Open the provided Xcode project
2) Drag and drop Realm and RealmSwift frameworks in (v3.1.1)
3) Set a breakpoint on line 24 in ViewController (see notes below)
4) Run the app
5) Tap the Add Data button to create the sample data: 1 artist, which contains 2 albums, each contains 3 songs
6) Tap the Delete Album button to delete the last album
7) Hit play each time the breakpoint is hit

## Expected Results
The album should be deleted and table updated without crashing the app.

## Actual Results
The app crashes, see crash details below. 

## Notes
This seems to be a timing issue. In our real app, this crash occurs every time, but in this demo app, it only sometimes occurs when running without the breakpoint set. With it stopping on the breakpoint, it has always crashed for me.

Check out the logs that are printed. You can see after the observer block is called the last time (when the album is deleted), the data source still has two albums, so `numberOfRowsInSection` returns 2, but then the app crashes in `cellForRowAt` because there is no album at index 1. It must be that between the time those two functions are called the data source changes.

## Code Sample
Xcode project: [Test.zip](https://github.com/realm/realm-cocoa/files/1765499/Test.zip)

## Crash Details
```
2018-02-27 19:41:59.112385-0700 Test[51115:3061770] *** Terminating app due to uncaught exception 'RLMException', reason: 'Index 1 is out of bounds (must be less than 1).'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104c6512b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000101793f41 objc_exception_throw + 48
	2   Realm                               0x00000001005f7c13 _ZL10throwErrorP15RLMManagedArrayP8NSString + 246
	3   Realm                               0x00000001005f4c8a -[RLMManagedArray objectAtIndex:] + 203
	4   RealmSwift                          0x0000000100cad3ff _T010RealmSwift4ListC9subscriptxSicfg + 127
	5   Test                                0x000000010029de7a _T04Test14ViewControllerC05tableB0So07UITableB4CellCSo0eB0C_10Foundation9IndexPathV12cellForRowAttF + 442
	6   Test                                0x000000010029e3dc _T04Test14ViewControllerC05tableB0So07UITableB4CellCSo0eB0C_10Foundation9IndexPathV12cellForRowAttFTo + 92
	7   UIKit                               0x0000000102189484 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 778
	8   UIKit                               0x0000000102189a2a -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 74
	9   UIKit                               0x000000010214f1f6 -[UITableView _updateVisibleCellsNow:isRecursive:] + 3031
	10  UIKit                               0x00000001021712e6 -[UITableView layoutSubviews] + 176
	11  UIKit                               0x00000001020f9a6d -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1439
	12  QuartzCore                          0x000000010985361c -[CALayer layoutSublayers] + 159
	13  QuartzCore                          0x00000001098577ad _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	14  QuartzCore                          0x00000001097de86c _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 364
	15  QuartzCore                          0x000000010980b946 _ZN2CA11Transaction6commitEv + 500
	16  UIKit                               0x00000001020227ee _UIApplicationFlushRunLoopCATransactionIfTooLate + 167
	17  UIKit                               0x0000000102993a1b __handleEventQueueInternal + 6894
	18  CoreFoundation                      0x0000000104c08101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	19  CoreFoundation                      0x0000000104ca7f71 __CFRunLoopDoSource0 + 81
	20  CoreFoundation                      0x0000000104beca19 __CFRunLoopDoSources0 + 185
	21  CoreFoundation                      0x0000000104bebfff __CFRunLoopRun + 1279
	22  CoreFoundation                      0x0000000104beb889 CFRunLoopRunSpecific + 409
	23  GraphicsServices                    0x000000010910e9c6 GSEventRunModal + 62
	24  UIKit                               0x00000001020285d6 UIApplicationMain + 159
	25  Test                                0x000000010029f327 main + 55
	26  libdyld.dylib                       0x000000010530cd81 start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Version of Realm and Tooling
Realm framework version: 3.1.1

Realm Object Server version: NA

Xcode version: 9.2 (9C40b)

iOS/OSX version: iOS 11.2 (and 10)

Dependency manager + version: NA

**Comment by bdash** [comment]
Thanks for the great bug report. From a brief look at the provided repro case, the problem appears to stem from the fact that the Delete Album button triggers numerous write transactions, one for each object that is deleted. Each new write transaction forces the pending change notifications from the previous write transaction to be delivered synchronously. The end result is that `UITableView.reloadData()` is called a number of times on the same runloop iteration, with the data source in a different state at each call. I'm not entirely clear what state ends up appearing inconsistent to `UITableView`, but I suspect it's related to the fact that it synchronously fetches some data from the data source inside `reloadData()` but fetches other data on-demaned when laying out the table view.

The simplest solution, and one that is a better way of using Realm, is to pull the write transaction out to the highest level possible, so all of the deletions are performed within a single transaction, rather than in many transactions. Write transactions have a certain amount of overhead in order to ensure the Realm file remains consistent in event of a crash or power failure on the device. It's far preferable to only incur this overhead once for a given batch of operations, rather than many times.

In this case, I pulled the write transaction out to `deleteAlbum(_:)` and `deleteAll()`, and no longer see the exception.

**Comment by hipwelljo** [comment]
Thank you for the detailed response! Can confirm that resolves the crash. I will restructure our real app similarly.

**Comment by jonchui** [comment]
Hey @hipwelljo & @bdash , we had a similar problem in our app and found that calling `tableView.layoutIfNeeded` right after the `tableView.reloadData`, seems to solve the inconsistent state without having to always monitor that you're only calling one write block. 

I found this out b/c it seems `reloadData` calls `numberOfRows` and `numberOfSections` but DOES NOT call `cellForRow` until the NEXT run loop iteration: [source](https://stackoverflow.com/a/16071589)
