### ISSUE TITLE
Optional unwrapping bug when using Release build configuration

### ISSUE THREAD

**Issue by gnrcampos** [realm/realm-cocoa#5640]
I'm having a problem with optionals that only happens when I  run the app using a release configuration. I have two models, Sale and CoreSale, and a Sale contains a CoreSale

```
class Sale: Object
{
    dynamic var id: String?
    dynamic var coreSale: CoreSale?
    ......
}

class CoreSale: Object
{
    ......
    var soldPrice: RealmOptional<Double> = RealmOptional<Double>()
    ......
}
```
At a certain point in the code, I fetch a Sale from the database and store the result in a property called _item:
`var _item: Sale`
However, when I print the following expressions I get very strange results:
```
print("Sold price: \(_item.coreSale?.soldPrice)")
print("Sold price: \(_item.coreSale!.soldPrice)")
print("Sold price: \(_item.coreSale?.soldPrice.value)")
print("Sold price: \(_item.coreSale!.soldPrice.value)")
print("Sold price: \(_item.coreSale!.soldPrice.value!)")
```
Results:
```
Sold price: Optional(RealmSwift.RealmOptional<Swift.Double>)
Sold price: RealmSwift.RealmOptional<Swift.Double>
Sold price: nil
Sold price: Optional(200000.0)
Sold price: 200000.0
```
The first, second, fourth and fifth prints seem ok to me but the third one should be exactly the same as the fourth. When I run the code using a debug configuration it prints the correct values, but as soon as I change it to release this strange behaviour shows up again. Am I missing something here? Please let me know if any further information is required to figure this out.

Realm framework version: 3.1.1
Realm Object Server version: Not using ROS
Xcode version: Version 9.2 (9C40b)
iOS/OSX version: Simulator running iOS 11.2 (15C107), iPad running iOS 11.2.6 (15D100)
Dependency manager + version: Cocoapods version 1.3.1

**Comment by bdash** [comment]
Can you please share a complete code snippet that reproduces the problem? It will be difficult for us to investigate this unless we can reproduce it.

**Comment by gnrcampos** [comment]
Hi @bdash , thanks for the quick response. I created a project that replicates the issue, please clone this repo:
https://github.com/gnrcampos/realmOptionalBug
To replicate it, run the project with a release profile using XCode 9.2. After the first run, the database url will be printed to XCode's console. Open the database using Realm Studio, add a CoreSale with a soldPrice and a Sale that has that CoreSale. Run the app again and observe the console.

**Comment by gnrcampos** [comment]
Also, I have just downloaded XCode 8 to test it and it works over there.

**Comment by tgoyne** [comment]
The problem appears to be that Swift has gotten more aggressive about releasing references to objects mid-statement.

In a release build, the expression `_item.coreSale?.soldPrice.value` is decomposing to something conceptually like the following:

    var soldPrice: RealmOptional<Double>? = nil
    autoreleasepool {
        if let coreSale = _item.coreSale {
            soldPrice = coreSale.soldPrice
        }
    }
    print("\(soldPrice?.value")

The problem with this is that `_item.coreSale` creates and returns a brand new object which is deallocated at the end of the autoreleasepool block. RealmOptional holds a weak reference to the object which owns it and uses that to obtain the current value on each call to `value`. This only works if the RealmOptional never outlives the containing object, and if it does it starts to just return `nil`.

Fixing this will unfortunately have a bit of a performance impact.
