### ISSUE TITLE
Add support for customizing the Authorization header

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#5641]
When ROS is running behind a proxy or a firewall that already attaches meaning to the `Authorization` header, users want to be able to supply a token with the header.

In addition, based off [ROS/sync changes](https://github.com/realm/realm-object-server-private/pull/924), need to expose the ability to change the name used to supply the ROS auth token in the header.

**Comment by bmunkholm** [comment]
@fealebenpae This has been done, but need to be included in an official release still?

**Comment by ianpward** [comment]
@fealebenpae Should we merge this to trunk?

**Comment by ianpward** [comment]
@tgoyne can we merge this to master?

**Comment by tgoyne** [comment]
Merge what? This isn't a PR.
