### ISSUE TITLE
if you see this error, please send this log to help@realm.io

### ISSUE THREAD

**Issue by iShavgula-TacTill** [realm/realm-cocoa#5642]
Hello, I'm having "if you see this error, please send this log to help@realm.io" error in my production code, the application crashes very frequently at random behavior.

I've sent this to help@realm.io and an account has been created for me, but all the pages of the site are blocked for my region, I'm localized in France.

So, i'm posting this error here hoping that someone can help me to figure out how to avoid it.

Realm version: 3.0.0 - 3.0.2

`/Users/realm/workspace/realm_realm-core_PR-2921-KRZQVOGV6QNV4VTLKF7FZYBJS45TOKJXEZA7N2KFU6F5R5HNA7CA/src/realm/util/file.cpp:922: [realm-core-4.0.3] Assertion failed: r == 0
0   Realm                               0x0000000105ba78c8 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 44
1   Realm                               0x0000000105ba7ba0 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 388
2   Realm                               0x0000000105ba28a0 _ZN5realm4util4File6unlockEv + 84
3   Realm                               0x0000000105ae79c0 _ZN5realm11SharedGroup14close_internalENSt3__111unique_lockINS_4util17InterprocessMutexEEE + 600
4   Realm                               0x0000000105ae7af4 _ZN5realm11SharedGroupD2Ev + 44
5   Realm                               0x000000010591ce8c _ZN5realm5RealmD2Ev + 1496
6   Realm                               0x000000010572ae40 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerD2Ev + 36
7   Realm                               0x000000010572ae04 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerD1Ev + 28
8   Realm                               0x000000010572aacc _ZNSt3__120__shared_ptr_emplaceIZN5realm5Realm17make_shared_realmENS2_6ConfigENS_10shared_ptrINS1_5_impl16RealmCoordinatorEEEE19make_shared_enablerNS_9allocatorIS8_EEE16__on_zero_sharedEv + 44
9   libc++.1.dylib                      0x0000000182f1af64 _ZNSt3__119__shared_weak_count16__release_sharedEv + 72
10  Realm                               0x000000010569b108 _ZNSt3__110shared_ptrIN5realm5RealmEED2Ev + 48
11  Realm                               0x00000001056928bc _ZNSt3__110shared_ptrIN5realm5RealmEED1Ev + 28
12  Realm                               0x00000001058b4470 -[RLMRealm .cxx_destruct] + 196
13  libobjc.A.dylib                     0x0000000182f62ef4 <redacted> + 148
14  libobjc.A.dylib                     0x0000000182f70638 objc_destructInstance + 88
15  libobjc.A.dylib                     0x0000000182f70690 object_dispose + 16
16  Realm                               0x00000001058b20c8 -[RLMRealm dealloc] + 244
17  libobjc.A.dylib                     0x0000000182f82138 <redacted> + 836
18  libswiftObjectiveC.dylib            0x0000000107188e28 _T010ObjectiveC15autoreleasepoolxxyKc8invoking_tKlF + 80
19  Tactill_Pay_pre                     0x0000000101a19f2c _T015Tactill_Pay_pre16RealmCertifEventC4syncySo13DispatchGroupCF6deleteL_yyF + 136
20  Tactill_Pay_pre                     0x0000000101a1a1d4 _T015Tactill_Pay_pre16RealmCertifEventC4syncySo13DispatchGroupCFyycfU_ + 48
21  Tactill_Pay_pre                     0x00000001018417f0 _T015Tactill_Pay_pre16APICertificationC6EventsC6createyAA16RealmCertifEventC_yyc7successySScSg5errorAJ7failuretFy10SwiftyJSON0N0VcfU_ + 160
22  Tactill_Pay_pre                     0x000000010139db58 _T015Tactill_Pay_pre17AppSessionManager33_C6B18BBF85EE696D7097C208FE35F958LLC7doACally9Alamofire10HTTPMethodO_SS3urls10DictionaryVySSypGSg6paramsy10SwiftyJSON0W0Vc7successyAQc5erroryAQc7failuretFyAA6StatusO_AKyS2SGSgtcfU_yAF12DataResponseVyypGcfU_ + 1296
23  Tactill_Pay_pre                     0x00000001013a56c4 _T015Tactill_Pay_pre17AppSessionManager33_C6B18BBF85EE696D7097C208FE35F958LLC7doACally9Alamofire10HTTPMethodO_SS3urls10DictionaryVySSypGSg6paramsy10SwiftyJSON0W0Vc7successyAQc5erroryAQc7failuretFyAA6StatusO_AKyS2SGSgtcfU_yAF12DataResponseVyypGcfU_TA + 308
24  Alamofire                           0x00000001044e397c _T09Alamofire11DataRequestC8responseACXDSo13DispatchQueueCSg5queue_x0D10SerializeryAA0B8ResponseVy16SerializedObjectQzGc17completionHandlertAA0biH8ProtocolRzlFyycfU_yycfU_ + 792
25  Alamofire                           0x00000001044a2d40 _T0Ix_IyB_TR + 48
26  libdispatch.dylib                   0x00000001072c92cc _dispatch_call_block_and_release + 24
27  libdispatch.dylib                   0x00000001072c928c _dispatch_client_callout + 16
28  libdispatch.dylib                   0x00000001072d7f80 _dispatch_queue_serial_drain + 696
29  libdispatch.dylib                   0x00000001072cc7ec _dispatch_queue_invoke + 332
30  libdispatch.dylib                   0x00000001072d8f6c _dispatch_root_queue_drain_deferred_wlh + 428
31  libdispatch.dylib                   0x00000001072e0020 _dispatch_workloop_worker_thread + 652
32  libsystem_pthread.dylib             0x0000000183942f1c _pthread_wqthread + 932
33  libsystem_pthread.dylib             0x0000000183942b6c start_wqthread + 4
IMPORTANT: if you see this error, please send this log to help@realm.io.2018-03-01 14:27:36.059581+0100 Tactill_Pay_pre[4917:4070057] /Users/realm/workspace/realm_realm-core_PR-2921-KRZQVOGV6QNV4VTLKF7FZYBJS45TOKJXEZA7N2KFU6F5R5HNA7CA/src/realm/util/file.cpp:922: [realm-core-4.0.3] Assertion failed: r == 0
0   Realm                               0x0000000105ba78c8 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 44
1   Realm                               0x0000000105ba7ba0 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 388
2   Realm                               0x0000000105ba28a0 _ZN5realm4util4File6unlockEv + 84
3   Realm                               0x0000000105ae79c0 _ZN5realm11SharedGroup14close_internalENSt3__111unique_lockINS_4util17InterprocessMutexEEE + 600
4   Realm                               0x0000000105ae7af4 _ZN5realm11SharedGroupD2Ev + 44
5   Realm                               0x000000010591ce8c _ZN5realm5RealmD2Ev + 1496
6   Realm                               0x000000010572ae40 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerD2Ev + 36
7   Realm                               0x000000010572ae04 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerD1Ev + 28
8   Realm                               0x000000010572aacc _ZNSt3__120__shared_ptr_emplaceIZN5realm5Realm17make_shared_realmENS2_6ConfigENS_10shared_ptrINS1_5_impl16RealmCoordinatorEEEE19make_shared_enablerNS_9allocatorIS8_EEE16__on_zero_sharedEv + 44
9   libc++.1.dylib                      0x0000000182f1af64 _ZNSt3__119__shared_weak_count16__release_sharedEv + 72
10  Realm                               0x000000010569b108 _ZNSt3__110shared_ptrIN5realm5RealmEED2Ev + 48
11  Realm                               0x00000001056928bc _ZNSt3__110shared_ptrIN5realm5RealmEED1Ev + 28
12  Realm                               0x00000001058b4470 -[RLMRealm .cxx_destruct] + 196
13  libobjc.A.dylib                     0x0000000182f62ef4 <redacted> + 148
14  libobjc.A.dylib                     0x0000000182f70638 objc_destructInstance + 88
15  libobjc.A.dylib                     0x0000000182f70690 object_dispose + 16
16  Realm                               0x00000001058b20c8 -[RLMRealm dealloc] + 244
17  libobjc.A.dylib                     0x0000000182f82138 <redacted> + 836
18  libswiftObjectiveC.dylib            0x0000000107188e28 _T010ObjectiveC15autoreleasepoolxxyKc8invoking_tKlF + 80
19  Tactill_Pay_pre                     0x0000000101a19f2c _T015Tactill_Pay_pre16RealmCertifEventC4syncySo13DispatchGroupCF6deleteL_yyF + 136
20  Tactill_Pay_pre                     0x0000000101a1a1d4 _T015Tactill_Pay_pre16RealmCertifEventC4syncySo13DispatchGroupCFyycfU_ + 48
21  Tactill_Pay_pre                     0x00000001018417f0 _T015Tactill_Pay_pre16APICertificationC6EventsC6createyAA16RealmCertifEventC_yyc7successySScSg5errorAJ7failuretFy10SwiftyJSON0N0VcfU_ + 160
22  Tactill_Pay_pre                     0x000000010139db58 _T015Tactill_Pay_pre17AppSessionManager33_C6B18BBF85EE696D7097C208FE35F958LLC7doACally9Alamofire10HTTPMethodO_SS3urls10DictionaryVySSypGSg6paramsy10SwiftyJSON0W0Vc7successyAQc5erroryAQc7failuretFyAA6StatusO_AKyS2SGSgtcfU_yAF12DataResponseVyypGcfU_ + 1296
23  Tactill_Pay_pre                     0x00000001013a56c4 _T015Tactill_Pay_pre17AppSessionManager33_C6B18BBF85EE696D7097C208FE35F958LLC7doACally9Alamofire10HTTPMethodO_SS3urls10DictionaryVySSypGSg6paramsy10SwiftyJSON0W0Vc7successyAQc5erroryAQc7failuretFyAA6StatusO_AKyS2SGSgtcfU_yAF12DataResponseVyypGcfU_TA + 308
24  Alamofire                           0x00000001044e397c _T09Alamofire11DataRequestC8responseACXDSo13DispatchQueueCSg5queue_x0D10SerializeryAA0B8ResponseVy16SerializedObjectQzGc17completionHandlertAA0biH8ProtocolRzlFyycfU_yycfU_ + 792
25  Alamofire                           0x00000001044a2d40 _T0Ix_IyB_TR + 48
26  libdispatch.dylib                   0x00000001072c92cc _dispatch_call_block_and_release + 24
27  libdispatch.dylib                   0x00000001072c928c _dispatch_client_callout + 16
28  libdispatch.dylib                   0x00000001072d7f80 _dispatch_queue_serial_drain + 696
29  libdispatch.dylib                   0x00000001072cc7ec _dispatch_queue_invoke + 332
30  libdispatch.dylib                   0x00000001072d8f6c _dispatch_root_queue_drain_deferred_wlh + 428
31  libdispatch.dylib                   0x00000001072e0020 _dispatch_workloop_worker_thread + 652
32  libsystem_pthread.dylib             0x0000000183942f1c _pthread_wqthread + 932
33  libsystem_pthread.dylib             0x0000000183942b6c start_wqthread + 4
IMPORTANT: if you see this error, please send this log to help@realm.io.`

If I update to the version 3.1.0 - 3.1.1 the application still crashes but the error message is different: 

`2018-03-01 14:14:37.686945+0100 Tactill_Pay_pre[4900:4064765] Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=1 "mmap() failed: Bad file descriptorsize: 1184offset: 0" UserInfo={
    "Error Code" = 1;
    NSLocalizedDescription = "mmap() failed: Bad file descriptorsize: 1184offset: 0";
}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.74.1/src/swift/stdlib/public/core/ErrorType.swift, line 181`

I'm not posting any code, because this is happening when doing even a simple 'add' within a write transaction and I've already 40+ different places in my code which was followed by this crash and still counting.

I need help ASAP please.

<img width="294" alt="capture d ecran 2018-03-01 a 14 42 34" src="https://user-images.githubusercontent.com/15924394/36847576-0f6e6c14-1d5f-11e8-9880-f2561c88a48b.png">

**Comment by iShavgula-TacTill** [comment]
Hi @bmunkholm,
The concerned application updates database very frequently, I think something was stacking up as I could only reproduce the crash when I was stress testing those DB updates, but we need to consider that I have an iPad Pro and probably that's why it was harder for me than for the customers to reproduce the crash.
Finally, 3.1.1 fixed the issue, no fix was applied on our side to give us a clue about the source of the issue.

**Comment by bmunkholm** [comment]
@iShavgula-TacTill Thanks for the update! Happy to hear it's fixed now. I'll close this then. Thanks!
