### ISSUE TITLE
maxOfProperty returning wrong value 

### ISSUE THREAD

**Issue by Venkata-Maniteja** [realm/realm-cocoa#5643]
I'm trying to implement the auto increment feature using the maxOfProperty method.

However it is not returning the correct value.

   RLMResults *contactArr = [RealmContact allObjects];
    int num = [contactArr maxOfProperty:@"oldPk"] + 1 ;
    realmContact.oldPk = num; //oldPk is a int property 
    

I'm calling this everytime I add a contact. 

For the first 10 contacts, the values returned are 0 , 323, 5187,  83011,  1328195 ....

I expect the num to be 0 , 1, 2, .....10

I'm not sure if I miss something. Can someone please point this out ?

https://stackoverflow.com/questions/49056463/ios-realm-maxofproperty-returning-wrong-value

**Comment by tgoyne** [comment]
`maxOfProperty:` returns a NSNumber, not an int. Your code is adding one to a pointer and then casting that to an int rather than adding one to the value stored in the NSNumber.

C's implicit conversions between pointers and ints sure is wonderful.

**Comment by Venkata-Maniteja** [comment]
Thank you for quick response. You are right~!
