### ISSUE TITLE
Sort List object in Realm object

### ISSUE THREAD

**Issue by morteza2128** [realm/realm-cocoa#5646]
I want to get list of category but I want to get list of categories with sorted subcategiries.

```
class CategoryRealm: Object, Category {
    @objc dynamic var id = -1
    @objc dynamic var slug = "-1"
    @objc dynamic var title = "aaa.com"
    @objc dynamic var subcategiries = List<SubCategoryRealm>()
}
```

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!
