### ISSUE TITLE
how to use it 

### ISSUE THREAD

**Issue by cadaverousblue** [realm/realm-cocoa#5647]
i can't find Realm.framework to put it in my project.
i don't want to use cocoapods

**Comment by Pinwheeler** [comment]
Consider using Carthage. It's very easy and the installation instructions are pretty detailed

**Comment by bdash** [comment]
Our [documentation has detailed installation instructions](https://realm.io/docs/swift/latest/#installation). Are you having trouble with something in those instructions?
