### ISSUE TITLE
Database file are not case sensitive.

### ISSUE THREAD

**Issue by MingyaoLiu** [realm/realm-cocoa#5648]
**Bugs**: realm database are not case sensitive.

## Expected Results
databases are case sensitive

## Actual Results
databases are not case sensitive

## Steps to Reproduce

run the code, console prints
Before Old: 0
Before New: 0
After add Old: 1
After add New: 2
After delete Old: 0
After delete New: 2

but all data are removed from both database, which probably mean only one database existed.
Run it everytime will produce same result that data are removed from both database( or the same database)

## Code Sample

`
class TestMO: Object {
    @objc dynamic var date: Date?
}
`

`
var configuration = Realm.Configuration.defaultConfiguration
        let documentDirectory = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask,
                                                             appropriateFor: nil, create: false)
        let url = documentDirectory.appendingPathComponent("Global.realm")
        configuration.fileURL = url
        var configuration2 = Realm.Configuration.defaultConfiguration
        let documentDirectory2 = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask,
                                                             appropriateFor: nil, create: false)
        let url2 = documentDirectory2.appendingPathComponent("global.realm")
        configuration2.fileURL = url2
        
        guard let oldGlobalRealm = try? Realm(configuration: configuration) else { return }
        guard let newGlobalRealm = try? Realm(configuration: configuration2) else { return }
        print("Before Old: \(oldGlobalRealm.objects(TestMO.self).count)")
        print("Before New: \(newGlobalRealm.objects(TestMO.self).count)")
        let a = TestMO()
        a.date = Date()
        try! oldGlobalRealm.write {
            oldGlobalRealm.add(a)
        }
        try! newGlobalRealm.write {
            newGlobalRealm.add(TestMO(value:a))
        }
        print("After add Old: \(oldGlobalRealm.objects(TestMO.self).count)")
        print("After add New: \(newGlobalRealm.objects(TestMO.self).count)")
        try! oldGlobalRealm.write {
            oldGlobalRealm.delete(oldGlobalRealm.objects(TestMO.self))
        }
        print("After delete Old: \(oldGlobalRealm.objects(TestMO.self).count)")
        print("After delete New: \(newGlobalRealm.objects(TestMO.self).count)")
`

## Version of Realm and Tooling

Realm framework version: 3.1.1

Realm Object Server version: X

Xcode version: 9.2 (9C40b)

iOS/OSX version: 11.2

Dependency manager + version: cocoapod 1.4

Am I being stupid here? I understand that the second print from the realm instance is probably not updated yet that's why it's returning objects count 2 instead of 0, but shouldn't the database be case sensitive?

**Comment by tgoyne** [comment]
Are you testing this in a simulator? While the filesystem is case-sensitive on iOS, by default it is not on macOS.

**Comment by MingyaoLiu** [comment]
let me test this again, it might be the simulator!

**Comment by MingyaoLiu** [comment]
@tgoyne omg you are right, thanks! I will close this ticket now.
