### ISSUE TITLE
SyncManager.shared.errorHandler not being set in versions later than 3.0.1. Multiple `SyncManager.shared` initialization?

### ISSUE THREAD

**Issue by piotr-dudek** [realm/realm-cocoa#5649]
It looks like there is a problem with `SyncManager.shared` initialization caused by this change: https://github.com/realm/realm-cocoa/commit/1161ef19f9abd56c4d112487cf99ba5121342247
After reversing the mentioned commit `errorHandler` seems to work fine.
The problem came up when I was trying to set the `errorHandler`. Here are some symptoms:

## Goals
Set `SyncManager.shared.errorHandler` in order to recover from critical errors.

## Expected Results
The errorHandler is being set and called when e.g. client receives `209 “Bad server version (IDENT, UPLOAD)`

## Actual Results
The errorHandler is not being called or even set. `SyncManager.shared.errorHandler == nil` returns `true`.

## Code Sample
```
import RealmSwift

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        SyncManager.shared.errorHandler = { error, session in
            print(error)
        }
        print("SyncManager errorHandler is nil: \(SyncManager.shared.errorHandler == nil)")
        return true
    }
}

```

## Version of Realm and Tooling

Realm framework version: RealmSwift from 3.0.2 to 3.2.0-beta.3
Xcode 9.2 (9C40b)
cocoapods 1.3.1
tested on iOS 10.x, 11.x Simulator

**Comment by tgoyne** [comment]
Whoops, the `once_flag` needs to be `static`...

Clearly we're missing some tests here too. I think the problem is that the relevant tests bypass the normal initialization method to ensure state doesn't persist between runs and so don't test this code.
