### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HebeTienCoder** [realm/realm-cocoa#5651]
crash when "objectsWhere:"
<img width="864" alt="qq20180306-221238 2x" src="https://user-images.githubusercontent.com/8787417/37036769-960cbbb0-218b-11e8-81eb-ee13f05f748f.png">
![Uploading QQ20180306-221300@2x.png…]()

## Version of Realm and Tooling

Realm framework version: 3.1.1 Newest

Realm Object Server version: ?

Xcode version: Newest

iOS/OSX version: iOS 9.3

Dependency manager + version: ?

**Comment by bdash** [comment]
The screenshot does not appear to show a crash, but a breakpoint being hit when a C++ exception is thrown. It's possible that the exception then leads to the application to terminate, but in that case I'd expect the exception information to be printed to your app's console with details about what went wrong. Please share that information so we can help you understand what's going on.
