### ISSUE TITLE
[XCTestCase] Cannot create Realm instance in Global queues?

### ISSUE THREAD

**Issue by zhihuitang** [realm/realm-cocoa#5652]
My code works fine in the App, but it doesn't work in **XCTest**.
I found the reason was that when I tried to create Realm instance in **Global queue**, then the process just died, no error, no exception thrown out.

See the code below, when it executes to `let realm = try! Realm()`, it dies. The codes after it won't be executed.

```swift
class DepartureViewModelTests: XCTestCase {

    func testExample() {
        DispatchQueue.global().async {
            let realm = try! Realm() // it dies here

           // the code below won't be executed
            let siteRecord = realm.objects(SiteRecord.self)
            print("finish")
        }
    }
}
````

I am using Xcode9.2 + Swift + Realm 3.1.1

Does anyone know the reason, or is it a bug?

**Comment by bdash** [comment]
There's no reason I'm aware of why creating a Realm on a global queue wouldn't work. When you say "it does", what does that mean? Are you seeing a crash? An exception? A breakpoint being hit? Please share more details about this to help understand what's going on.

**Comment by zhihuitang** [comment]
Thanks, @bdash . I found the reason, it was my bad.  The reason is that XCTestCase finishes before `try! Realm()` returns, since`try! Realm()` takes time to execute.
