### ISSUE TITLE
RealmSwift compile failure due to swiftLanguageVersion unresolved in Object.swift

### ISSUE THREAD

**Issue by sibinlu** [realm/realm-cocoa#5654]
RealmSwift compile failure due to swiftLanguageVersion unresolved in Object.swift

it is ok on version 3.1.0.

Realm framework version: 3.1.1

Xcode version: 9.2 swift 3

**Comment by bdash** [comment]
`swiftLanguageVersion` is a constant in a generated file. It not being found indicates that you're either not building the generated source file, or the generated file has the wrong contents. Please share how you're building Realm Swift from source.

**Comment by sibinlu** [comment]
I don't think I have built it. I include use pod 'RealmSwift'

**Comment by bdash** [comment]
Please follow the instructions listed in our documentation's section on [Troubleshooting CocoaPods](https://realm.io/docs/swift/latest/#dependency-managers), and see if that improves your situation.
