### ISSUE TITLE
How to add a new table in a empty realm db

### ISSUE THREAD

**Issue by BoySimonHu** [realm/realm-cocoa#5659]
First of all, I create a empty realm db, and then i use runtime dynamically to add some properties to a RLMObject class.
  But when i operate this class, realm will tall me 'Table has no columns', so can i dynamically add a new table or some properties in a empty realm db.

**Comment by bmunkholm** [comment]
Not officially. But you can check the (deprecated) Browser which handles models dynamically: https://github.com/realm/realm-browser-osx.
