### ISSUE TITLE
Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to create an object of type 'XXX' with an existing primary key value 'XXX'

### ISSUE THREAD

**Issue by CodeKunal** [realm/realm-cocoa#5664]
I am creating a chat application. I have chats and messages for these chats. 

MessageThread class contains the chatId and an array of **Message**  with chatID as primary key. Every **Message** has a messageID as primary key. 

Now if I try to fetch new messages of a chat and append them to the messages array of the particular message I get a crash with below crash log.

Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to create an object of type 'Message' with an existing primary key value 'XXX'

My realm code is below.

try! realm.write {
            messageThreadToStore.messages.append(contentsOf: messages)
            self.realm.create(**MessagesThread**.self, value: messageThreadToStore, update: true)
        }

I guess the problem is that it is trying to append a new message with same primary key as the existing message primary key. My point is that if I have said it to update then it should just update.

**Comment by tgoyne** [comment]
I am guessing that it is the `append()` line that is throwing, not the `create()`. If `messageThreadToStore` is a managed Realm object, then `append(contentsOf: messages)` will attempt to add all of the objects in `messages` to the Realm, and the `realm.create()` call is just a no-op.

One possible fix for this would be to change your write to:
```
try! realm.write {
    realm.add(messages, update: true)
    messageThreadToStore.messages.append(contentsOf: messages)
}
```

**Comment by CodeKunal** [comment]
Thanks a lot @tgoyne . Your solution works like a charm saved me a few hours of debugging. Was just wondering that once I did realm.add(messages, update: true) it would store new messages somewhere in my iPhone local db. But after this when I append same messages to my messageThreadToStore Realm object messages property it does not throw RLMException. So basically what I am doing is add these new messages to realm and then tell messageThreadToStore.messages to append these new messages.
