### ISSUE TITLE
[Mac OS] Realm files growing exponentially in a multi App configuration (Swift & ObjC)

### ISSUE THREAD

**Issue by thunderkerrigan** [realm/realm-cocoa#5668]
## Goals
We're using Realm with a single local Realm shared between 4 Mac Os Apps which could be running simultaneously.

## Expected Results
Realm file size should stay steady with some growing expected from normal transaction.

## Actual Results
No issue while running only one App at a time. Issue starting while running at least 2 Apps simultaneously.

## Steps to Reproduce
Have 2 apps using the same realm configuration running simultaneously. Both have notification blocks. One should create and/or update entries/records in realm db (not even shared records necessary).
in a matter of minutes, Realm file size start growing unexpectedly. (easily reproduced with Realm Studio as an alternative app).

Our realm file is starting at ~12MB(less than 4k entries).
After 8 Hours of test running, we got a file size of >40GB.
After 36 Hours of test running, we got a file size of >380GB.

We're planning to add Realm backup tools (copyFile) and compact the realm file using the shouldCompactOnLaunch configuration periodically at off-peak time but we're a bit confused at why this issue might happen (it's not even systematic, sometimes they run altogether for hours and the Realm file is not growing that much). 

Our apps are heavily threaded but it was never an issue before (we migrated from CoreData to Realm as a matter of fact). We still mainly develop in Objective-C but we got the same issue in Swift(3.x to 4).

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1212

/Applications/Xcode.app/Contents/Developer
Xcode 9.2
Build version 9C40b

/usr/local/bin/pod
1.4.0
Realm (3.1.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.18.1
(not in use here)

/usr/bin/git
git version 2.14.3 (Apple Git-98)
```

**Comment by bmunkholm** [comment]
Did you check the documentation on this point? https://realm.io/docs/swift/latest#limitations-file-size
It sounds as you are maybe holding on to multiple snapshots (versions) of the data.

**Comment by thunderkerrigan** [comment]
It seems like it's our issue here. I never saw this documentation until now (or at least one as detailed as this one on this issue). Thank you. It gives us some leads to follow.
