### ISSUE TITLE
Fix Carthage install tutorial

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-cocoa#5669]
## Goals

Load the library successfully, if I follow the sample provided [here](https://realm.io/docs/swift/latest/#installation), the project compiles but crashes (even on debug) while loading the library.

## Actual Results
```
dyld: Library not loaded: @rpath/Realm.framework/Realm
  Referenced from: /var/containers/Bundle/Application/BB57298E-5283-4718-B7CA-49C885C4911C/Bugs.app/Bugs
  Reason: image not found
```

## Steps to Reproduce
Add carthage, add the dependencies, create the frameworks `Realm.framework` and `RealmSwift.framework`, add these files as the tutorial says on `Linked Frameworks and Libraries` section of your Xcode project’s `General` settings. Compile and 💣.

## Workaround for App Store submission bug 

This part of the tutorial is really confusing, I think a image there could be very useful to explain how to set this part of setup.
Another problem is the Input Files, there is a `<br />` field that should be:

![screen shot 2018-03-13 at 13 23 29](https://user-images.githubusercontent.com/5521682/37344234-c01c5a7e-26c1-11e8-8eb7-5c44efc61d15.png)

## Version of Realm and Tooling

Realm framework version: 3.1.1

Realm Object Server version: ?

Xcode version: 9.2

iOS/OSX version: ?

Dependency manager + version: Carthage 0.28.0

**Comment by houmanMP** [comment]
This bug still present on xcode 10

**Comment by ericjordanmossman** [comment]
Under "Frameworks and Libraries", what are the settings for embedding 'Realm' and 'RealmSwift'?

If the issue is [similar to this](https://github.com/realm/realm-cocoa/issues/4300) then we can change the documentation to help with that.

**Comment by ericjordanmossman** [comment]
Closing because of age/inactivity. See [this link for more](https://github.com/realm/realm-cocoa/issues/4300) reading. Please open a new issue if you're still seeing anything similar with Carthage.
