### ISSUE TITLE
Crash when deleting Realm objects on iPhone 4s, iOS 9.0.1

### ISSUE THREAD

**Issue by stefanprutianu** [realm/realm-cocoa#5672]
## Goals
We're using Realm Objective-C, version 3.0.2 and we're experiencing a recurrent crash on a particular device and iOS version configuration.

## Expected Results
To not crash when deleting Realm objects. 

## Actual Results
Please see the relevant stack trace attached.
[delete-object-crash.txt](https://github.com/realm/realm-cocoa/files/1810313/delete-object-crash.txt)

## Steps to Reproduce
Insert some realm objects and then attempt to delete them. Please note that our objects have relationship to other objects so before deleting the original object we're deleting the children objects.

Realm framework version: ?
Realm Objective-C, version 3.0.2

Xcode version: ?
8.3.3

iOS/OSX version: ?
iOS 9.0.1, iPhone 4s

**Comment by bmunkholm** [comment]
@stefanprutianu We have unit tests testing this. So could you possibly provide a self-contained repro project or testcase?

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
