### ISSUE TITLE
Realm Swift 3.1.1 (Latest) cannot extend Object class, Swift 4

### ISSUE THREAD

**Issue by avjiang** [realm/realm-cocoa#5676]
**Bugs**:

so I created totally new project and add 'RealmSwift' pod into the project

then I import RealmSwift

    import RealmSwift

    class TestObject: Object { // the Object is not being suggested by the autocomplete 

        let dog = List<Dog>() // the List also not being suggested by the autocomplete
    }

Above codes do not give compiler error. But because of this I have another problem. 

I need to call my List object and then call the property. 

When I tried to call the list object property from another ViewController, the suggested data type of the list property is <<error type>>. I don't know what to do because i really need to access the property but I can't. And now my compiler gives me error.

Is there something wrong? It has never happened to me in my previous projects, just this once. Can someone help me? 

Xcode version: 9.2 

iOS/OSX version: MacOS High Sierra (10.13.3)

Dependency manager + version: RealmSwift 3.1.1 (Latest)

**Comment by RVijay007** [comment]
Not from realm but did you make another object subclass Dog?

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

For your particular case, did you try to start with our sample apps and go from there?
