### ISSUE TITLE
How to get array of distinct property values from array of realm objects where some objects have repeating property values like name or height.

### ISSUE THREAD

**Issue by remosingh** [realm/realm-cocoa#5678]
## Goals
To create array of distinct properties retrieved from an array of objects

## Expected Results
No expected results. Do not how to do it. Tried using the "@distinctUnionOfObjects" predicate but I don't know what they mean by "run on array of arrays".

## Actual Results
I am trying to get data from a realm database and show it on four different pickers side by side, each getting data from one of the properties I have set up in my realm object class. This actually orks fine and I am able to see my values in the picker view.

However, the issue is that as I have repeating data in my database for example people having same name which I don't want to show multiple times, I have repeating data in the pickerview because when I read from Realm it also includes any repeating values in my Results<Class> variable. From this variable I want to make a new variable which is an array of distinct property values based on which property I specify, for example of type [String] or [Int], etc.

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!
