### ISSUE TITLE
Duplicate interface definition for class 'Permission'

### ISSUE THREAD

**Issue by mohammdsss1** [realm/realm-cocoa#5679]
## Goals

To compile the project without errors

## Expected Results

Compilation without any error

## Actual Results

I have received an error:
Duplicate interface definition for class 'Permission'

## Steps to Reproduce

Update realm from 2.10.2 to 3.2.0
## Code Sample

I found out that there is a Permission class within the Sync.swift file beside my Permission class too,
Mine is:
`final class Permission: Object, Mappable { }.`

Realm framework version: ?
3.2.0

Xcode version: ?
9.2

iOS/OSX version: ?
iOS 11

Dependency manager + version: ?
Cocoapods

What should I do in this case?

**Comment by tgoyne** [comment]
Having a class named Permission in both your application and in RealmSwift should be perfectly fine, as Swift has per-target namespacing. I wonder if cocoapods is doing something strange.

**Comment by tgoyne** [comment]
I just tried creating a small test project which imports Realm Swift 3.2 via cocoapods and defines a class named `Permission`. I did not hit any compilation errors, but I did get a runtime error when trying to open the Realm due to having multiple Object subclasses named `Permission`, which is a bug we'll need to fix.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-cocoa/pull/5681 fixes the runtime error I hit.

**Comment by mohammdsss1** [comment]
This is what I got inside MyProject-Swift.h file

<img width="797" alt="screen shot 2018-03-19 at 19 18 27" src="https://user-images.githubusercontent.com/7831855/37611215-67ede37a-2baa-11e8-9bda-fc39cee9bef4.png">

**Comment by tgoyne** [comment]
Ah, a bridging header issue. That should be fixed by #5681 then as it'll also change the name that appears in the bridging header.

**Comment by tgoyne** [comment]
This was fixed by 3.3.0.
