### ISSUE TITLE
Terminated due to memory issue

### ISSUE THREAD

**Issue by raphaels17** [realm/realm-cocoa#5682]
I dont have message debug apart from "Terminated due to memory issue"

I load a result with 2.8k results. I have no clue what to do, reducing the number of results works.... but i believe the issue is a leak of some kind. ANy idea?

Realm framework version: 'RealmSwift','~> 2.10.1'

Xcode version: 9

iOS/OSX version: 11

Dependency manager + version: ?

**Comment by jlong2000** [comment]
I have got a same issue.
Any ideas to solve this issue?

**Comment by hanl001** [comment]
sad

**Comment by raphaels17** [comment]
FYI for me, there was an issue regarding images. Though the result was loaded on a collection view, all 2.8 images were loaded,( and not only those on sight), leading to the crash. What I did is to ref one standard image in the controller and replacing it later on, to avoid the crash.

**Comment by bmunkholm** [comment]
Sounds like you got this solved yourself. Closing.
