### ISSUE TITLE
Cannot download CocoaPods from Artifactory

### ISSUE THREAD

**Issue by jeanfleblanc** [realm/realm-cocoa#5684]
**Bugs**

## Goals
When we try to use Realm as a dependency in our Podfile through Artifactory:
 
platform :ios, '10.0'
 
target 'MyTarget' do
use_frameworks!
pod 'RealmSwift', '~> 3.1'
end
 
## Expected Results
We want to download the Realm dependency

## Actual Results
We get this error:
 
Installing Realm (3.1.1)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup
 
core is not a symlink. Deleting...
Downloading dependency: sync 2.2.9
 
ERROR: One of Realm's submodules is missing!
 
If you're using Realm and/or RealmSwift from a git branch, please add 'submodules: true' to
their entries in your Podfile.
 
***Please note that the same is working if we connect directly to the Internet and we bypass Artifactory.***

## Steps to Reproduce
Setup the PodFile to download the dependencies from Artifactory
Run pod install

## Code Sample
platform :ios, '10.0'
 
target 'MyTarget' do
use_frameworks!
pod 'RealmSwift', '~> 3.1'
end

## Version of Realm and Tooling

Realm framework version: 3.1.1

Realm Object Server version: N/A

Xcode version: 9.2

iOS/OSX version: macOS Sierra

Dependency manager + version: CocoaPods 1.4.0

**Comment by bdash** [comment]
This output:
> ERROR: One of Realm's submodules is missing!

indicates that object store code we expect to exist at `Realm/ObjectStore/src` does not exist. The fact that this works with CocoaPods directly indicates this problem is likely due to your use of Artifactory. I'd suggest contacting them for support with this issue.

**Comment by forceunwrap** [comment]
@jeanfleblanc did you ever have success with this?
