### ISSUE TITLE
Initialize objects and subclass of that object throughout Decoder

### ISSUE THREAD

**Issue by Jasperav** [realm/realm-cocoa#5688]
## Goals
Initialize objects and subclass of that object throughout Decoder

## Stackoverflow
https://stackoverflow.com/questions/49394672/initialize-realm-object-through-decodable

## Expected Results
See goals

## Actual Results
Code does not compile

## Steps to Reproduce
See this code:

```
    class A: Object, Decodable{

        let listA = List<Int>()
        
        required init() {
            self.init()
        }
        
        required init(realm: RLMRealm, schema: RLMObjectSchema) {
            fatalError("init(realm:schema:) has not been implemented")
        }
        
        required init(value: Any, schema: RLMSchema) {
            fatalError("init(value:schema:) has not been implemented")
        }
        
        private enum CodingKeys: CodingKey{}
        
        public required convenience init(from decoder: Decoder) throws {
            self.init()
        }
    }
    
    class B: A{

        let listB = List<Int>()

        private enum CodingKeys: CodingKey{}
        
            public required init(from decoder: Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                let encoder = try container.superDecoder()
                try super.init(from: encoder)
            }
        
            required init(value: Any, schema: RLMSchema) {
                fatalError("init(value:schema:) has not been implemented")
            }
        
            required convenience init() {
                self.init()
            }
        
            required init(realm: RLMRealm, schema: RLMObjectSchema) {
                fatalError("init(realm:schema:) has not been implemented")
            }
    }

This is my JSON:

    {
      "A": [
        1,
        2,
        3
      ],
        "B": [
        1,
        2,
        3
      ]
    }
```

How can I initialize object B with my JSON data in a way that object B:
-has listB with the values in the JSON with key B
-has listA with the values in the JSON with key A

## Version of Realm and Tooling

Realm framework version: 3

Xcode version: 9

iOS/OSX version: 11

**Comment by RVijay007** [comment]
I'm not part of Realm, but from what I can see, unless you have a top level object that has property A and property B both pointing to arrays of their respective object types, you'll need to Decode each array individually with Decoder. Decoder().decode([A.self], from: json["A"]), Decoder().decode([B.self], from: json["B"]). Also might require Swift 4.1 for conditional conformance capability since it is an array of Codable types.

**Comment by Jauzee** [comment]
@Jasperav one note — you can create `convenience` initializer to avoid these required initializers.

**Comment by bmunkholm** [comment]
Looks like you got your question answered, so closing for now.
