### ISSUE TITLE
Realm crashing on ios

### ISSUE THREAD

**Issue by RajaReddyiOS** [realm/realm-cocoa#5690]
i was initialise realm as global on main thread. and am adding objects at another thread leads to crash message is "Realm accessed from incorrect thread". is it mandatory intialization and adding objects at same thread.
```swift
let realm = try! Realm() ---> Global

func startUpdatingAccelerometer() {
    self.motionManager.startAccelerometerUpdates(to: motionQueue) { (accelerometerData, err) -> 
     Void in
            if let data = accelerometerData {
                print("force casting thread: ")
                let accelerationRealm = AccelerometerRealm()
                accelerationRealm.time = Date().timeIntervalSince1970
                accelerationRealm.activityType = self.activityType
                accelerationRealm.xAxis = data.acceleration.x
                accelerationRealm.yAxis = data.acceleration.y
                accelerationRealm.zAxis = data.acceleration.z
                    do {
                        try realm.write {
                             realm.add(accelerationRealm, update: false)
                        }
                    } catch let error {
                        print("fails while writing to db: ",error)
                    }
            }
        }
}
```
how come resolve this issue?

my accelerometer sensor data updates is in every 1milli seconds. so if i can initialize realm inside a block its taking more than 1 second. and when i running this in main thread realm causing block my UI.
I need to update this in background thread.

**Comment by bdash** [comment]
Please take a look at our [documentation on threading](https://realm.io/docs/swift/latest/#threading), in particular the section on using a Realm across threads.

> my accelerometer sensor data updates is in every 1milli seconds. so if i can initialize realm inside a block its taking more than 1 second. and when i running this in main thread realm causing block my UI.

Don't open a new Realm instance on every update. Instead, push all of the writes to a single background thread, and keep a Realm instance open on that thread. And I'd also suggest coalescing writes so you're not adding a single object at a time. Instead, batch the data in memory and flush it to the Realm periodically. This will spread the cost of the write transaction over more objects.
