### ISSUE TITLE
Versioning comparison is wrong

### ISSUE THREAD

**Issue by haithngn** [realm/realm-cocoa#5704]
Hi,
I'm using latest Realm version 3.3.0 but the console still show warning like this:
`Version 3.1.2 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v3.1.2/CHANGELOG.md`

Version number comparison is now wrong ?

Realm framework version: ? 
3.3.0

Realm Object Server version: ?

Xcode version: ? 
9.2

iOS/OSX version: ?

iOS 11

**Comment by tgoyne** [comment]
This will be fixed whenever the website deploy for 3.3.1 completes.
