### ISSUE TITLE
Need RealmSwift for Swift 4.1

### ISSUE THREAD

**Issue by doncl** [realm/realm-cocoa#5709]
Xcode 9.3 is released.   Swift 4.1 is the language of the land.

When I try to link to RealmSwift 3.0.3 frameworks, I get 
'Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1:'

Trying to build realm-cocoa with Xcode 9.3 fails also.

What's the ETA for Swift 4.1 / Xcode 9.3 support?   

thanks.

**Comment by BoilingLime** [comment]
Xcode 9.3 : Module compiled with Swift 4.0.2 cannot be imported in Swift 3.3:

**Comment by wangjinwei0806** [comment]
when ?

**Comment by acehippo** [comment]
after update Xcode to 9.3 that include Swift 4.1
carthage update failed to build, show below error message.

```
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."
```

**Comment by tgoyne** [comment]
You can tell Carthage to skip trying to use the prebuilt binary for Xcode 9.2 by passing `--no-use-binaries` to carthage bootstrap.

**Comment by acehippo** [comment]
I tried to build sources of realm-cocoa latest(v3.3.1) with Swift 4.1 not using carthage.
It is woking fine.

**Comment by doncl** [comment]
I wonder if I should close this issue; after a little head-scratching, it wasn't at all hard to build RealmSwift from source using Xcode 9.3, so maybe it really isn't such an issue, and the Realm guys can deliver us pre-built binaries when they get to it.    As to Cocoapods and Carthage, well....I'm starting to think like [this](https://jobs.zalando.com/tech/blog/how-the-zalando-ios-app-abandoned-cocoapods-and-reduced-build-time/?gh_src=4n3gxh1)

**Comment by acehippo** [comment]
@doncl thanks, I think so it isn't such an issue for me from now on. and I am also trying to work like link that you share. good to read.

**Comment by wangjinwei0806** [comment]
1.add this to you projects 
![image](https://user-images.githubusercontent.com/3974508/38143149-c7567cb2-3471-11e8-9f4f-a2287368b733.png)
2.use  Realm.framework
![image](https://user-images.githubusercontent.com/3974508/38143169-dd1781cc-3471-11e8-9198-1b555e05cd38.png)
 it's work for me !

**Comment by saham** [comment]
As of March 30, I still have this issue. I have no idea how to use Carthage :(

**Comment by saham** [comment]
Realm 3.3.1 also did NOT solved the issue. There is no swift 4.1

**Comment by 5SMNOONMS5** [comment]
+1, need

**Comment by saham** [comment]
I follows this link https://github.com/realm/realm-cocoa#building-realm
When I tried to compile, I get lot of file missing errors :(
Same issue every time there is new version of IOS/Xcode. Is it a time to move to CoreData and not using realm any more?

**Comment by hikokwei** [comment]
Any updates on the release for Swift 4.1?

**Comment by X901** [comment]
when we will see new update to support Swift 4.1 ?

**Comment by doncl** [comment]
Hey, Realm-guys, I'd like to say I am competent to build it myself.   Well, I am.   But when I upload to TestFlight, it complains about a bad Mach-O header.   

Yes, I'm lame, I should be able to solve this myself.   But I've elected to just wait for you guys to compile it for me.     

Pretty Please?

**Comment by saham** [comment]
I cannot event compile with out getting errors. I am thinking to move to CoreData

**Comment by Endanke** [comment]
@saham You need to clone the repo then update the submodules as described in the readme. It sounds like an optional step, but this is the way to do it.

**Comment by saham** [comment]
@Endanke That's what I get when I run git submodule update --init --recursive

fatal: Not a git repository (or any of the parent directories): .git

**Comment by acehippo** [comment]
I did build from source with Xcode 9.3 and Swift 4.1
and using frameworks(Realm, RealmSwift) is fine
```bash
$ git clone https://github.com/realm/realm-cocoa
$ cd realm-cocoa
$ git submodule update --init --recursive
$ sh build.sh ios-swift
```

**Comment by saham** [comment]
Thanks @acehippo 
After getting realmswift 4.1, I am getting this error at build time in Xcode (building my app)
bash: PATH_TO_APP/DerivedData//Build/Products/Debug-iphonesimulator/APP_NAME.app/Frameworks/Realm.framework/strip-frameworks.sh: No such file or directory
I can manually copy two framework files but what's wrong ?

**Comment by MingyaoLiu** [comment]
@saham if it's in the DerivedData directory, I suppose you gotta clean build folder?

**Comment by saham** [comment]
I did clean/clean build folder. I even manually deleted the folder
![image](https://user-images.githubusercontent.com/4553478/38203017-c39bfb0a-366b-11e8-895f-550d36d14db5.png)

![image](https://user-images.githubusercontent.com/4553478/38203046-d4bf15f2-366b-11e8-8727-e8427c21e54d.png)
![image](https://user-images.githubusercontent.com/4553478/38203057-dbde759e-366b-11e8-88fb-8741d8a3a03f.png)
![image](https://user-images.githubusercontent.com/4553478/38203079-f38189ca-366b-11e8-802d-5ace5ab8f235.png)

Thank you

**Comment by jwarhurst** [comment]
Make sure you add realm.framework and realmswift.framework to the Embedded Binaries.

**Comment by saham** [comment]
Same result :(

**Comment by joeblau** [comment]
I cleared out all of my deprived data and rebuilt and everything worked fine.  I still see the error, but it doesn't affect importing any of my dependencies.

**Comment by saham** [comment]
Can you run your app on a simulator?

**Comment by joeblau** [comment]
Yep, app is running in the simulator on Xcode version 9.3 (9E145)

**Comment by saham** [comment]
Good for you 👍🏻Mine compliments about derived data. I cleaned /cleaned build folder. I even manually deleted the derived data folder. Nothing works for me:(

**Comment by saham** [comment]
It's not even working on my device.I blame on what I compiled

**Comment by doncl** [comment]
To the realm team:  any ETA on getting the Swift 4.1 version done?

**Comment by wangjinwei0806** [comment]
Compile successfully  check [this](https://pan.baidu.com/s/182iZIOsE4OmxIT5nTNLVTw)

**Comment by tgoyne** [comment]
3.3.2 is now out and includes a Xcode 9.3 binary.

**Comment by EmDee** [comment]
@tgoyne Was `3.3.2` built with the correct compiler? I still get 

```
 *** Skipped installing realm-cocoa.framework binary due to the error:
[15:23:35]: ▸ "Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."
```

**Comment by ydemartino** [comment]
Using cocoapods, I also still have the error

**Comment by tgoyne** [comment]
Cocoapods does not use the prebuilt frameworks and whatever error you're seeing is unrelated to them.

**Comment by EmDee** [comment]
@tgoyne That answer was not directed and me, was it? I'm using `Carthage`.

**Comment by glennmd** [comment]
I am trying iOS12 with latest Xcode so I can try out a CreateML machine language model in my project however the latest Realm.framework etc. is not compatible. (what else is new). I assume they are still pushing Cocoa Pods as a bandaid. I sort of knew I would not have a chance  to try my project with good old Realm since it has a track record of dragging its feet when it comes to upgrading to newest MacOS/ iOS version/ Swift/Xcode. Come on guys if I moved that fast I would be sued for malpractice every day. Realm should be happy that their followers-programmers (patients) that have bought into their hype are not suffering from a serious illness; they suffer only from simple Relam anticipatory derangement syndrome. This illness is insidious in onset and steadily worsens in the absence of Realm updates. The cure (core data) violates the dogma of "do no harm". That leaves those suffering up a creek without a paddle. One day someone will see there is a need, a new market for paddles. GT

**Comment by wAIsHAN** [comment]
Same result too.I remove realm from pod and pod install after remove realm I installed back but can't install and fail with this error "The active Xcode command line tools, as returned by 'xcode-select -p', are not from Xcode" how can i do this?
