### ISSUE TITLE
Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by janosiatti** [realm/realm-cocoa#5715]
I'm still getting this error: Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1 with realm 3.3.2. I added Realm.framework and RealmSwift.framework manually to my project.

Realm framework version: 3.3.2

Xcode version: 9.3

iOS/OSX version: 8+

**Comment by TarekSalama** [comment]
Same problem for me. I added Realm using Carthage.

**Comment by EmDee** [comment]
@janosiatti Is that a typo and it should say `Swift 4.0.3`? Because that's what I'm getting as well and have already reported it in the issue that supposedly built the binary with 4.1: https://github.com/realm/realm-cocoa/issues/5709

**Comment by TarekSalama** [comment]
I had to delete the old Carthage folder and remove the frameworks manually from my project and then I redid all the Carthage installation steps. I am certain that it took more time to add the files though (over 20-30 minutes) when I did `carthage update`

**Comment by janosiatti** [comment]
And it works now?

**Comment by TarekSalama** [comment]
@janosiatti Yes it works now.

**Comment by janosiatti** [comment]
Thank you @TarekSalama, i will try it too.

**Comment by EmDee** [comment]
@iGranDav I suppose you have the same (wrong) assumption as I did. Realm doesn't provide a binary for Swift 4.1 through Carthage yet. See my other issue: https://github.com/realm/realm-cocoa/issues/5725

**Comment by iGranDav** [comment]
@EmDee exactly! Thanks a lot for your help 👍
