### ISSUE TITLE
The size of `Realm.framework/Realm` becomes too big when built with Swift 4.1 in Xcode 9.3

### ISSUE THREAD

**Issue by yuzushioh** [realm/realm-cocoa#5722]
Related to #4785

## I am using

- Realm version:  v3.3.2
- Xcode version:  9.3
- OSX version:  10.13.3
- Dependency manager + version: Carthage 0.29.0

## What's happening

After updating Xcode to 9.3, Swift 4.1, and Carthage builds by running `carthage update realm-cocoa --platform ios --no-use-binaires`, the size of `Realm.framework/Realm` becomes 143.03 MB. 

#### I already tried below but wouldn't fix
- clean up all the cache in Xcode
- delete the existing build and build again

## Problem

Because all the `.framework` built with Carthage are committed to the repository in my project, the size of each frameworks needs to be less than 100MB since GitHub's file size limit is 100MB. I want to make it smaller than that. Is there any suggestions or tricks to fix this problem? 

Thank you

**Comment by 3a4oT** [comment]
@yuzushioh  I have the same problem. But seems like *Realm.framework.dSYM/Contents/Resources/DWARF/Realm* has 143.0 MB. Basically, I would try just to remove Realm.framework.dSYM for a short-term fix. For the midterm, I gonna to try use binary [Carthage approach ](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks)

@syky27 well if you will not include binary it would take more time to compile than your own sources. The situation even worst if u using, for example, Moya and RxSwift in addition(or any other frameworks). It's not so critical for local development but become critical when u using CI/CD and have more than 10 builds per day. 

I'm happy to hear any other suggestions.

**Comment by syky27** [comment]
@3a4oT I was dealing with the same issue where a build on CI took over 4 hours, so I builded them once and stashed them. 

I would help if there would be prebuilded framework with 4.1 swift version, so you would not have to build it your self....

**Comment by 3a4oT** [comment]
@syky27 so basically you have a copy of you Carthage folder on CI and after a project was fetched just copy it? I hope with Swift 5 and ABI stability I will never back to those workarounds. Now it's a big pain to migrate from Swift to Swift.

**Comment by syky27** [comment]
Yes, and when it fails to build, I just rebuild those Carthage libs with current Swift version

**Comment by bmunkholm** [comment]
Looks like you got this "resolved" in some form for now.

**Comment by pjcau** [comment]
I have the same issue on Xcode 10.1. The size it’s so big. The frameworks are around 100 MB and 150 MB symbols. It’s very fastidious !!!
