### ISSUE TITLE
No Swift 4.1 pre-built binary for Realm-Cocoa 3.3.2

### ISSUE THREAD

**Issue by EmDee** [realm/realm-cocoa#5725]
## Goals

Using `carthage` to get pre-built Realm binary.

## Expected Results

Downloading `v3.3.2` binary without error.

## Actual Results

`"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."`

## Steps to Reproduce

Run `carthage bootstrap realm-cocoa` with `github "realm/realm-cocoa" "v3.3.2"` in the `Cartfile.resolved`.

## Version of Realm and Tooling

Realm framework version: 3.3.2

Xcode version: 9.3

iOS/OSX version: 11.3

Dependency manager + version: Carthage 0.29.0

**Comment by tgoyne** [comment]
Carthage only supports shipping prebuilt binaries for a single version of Xcode at a time, and 9.2 is still the most-used version. Once that changes to 9.3 we will switch the Carthage binary to that.

**Comment by EmDee** [comment]
I guess I got confused by the release note of 3.3.2 that states: `Add a prebuilt binary for Xcode 9.3.`. Thought you guys meant pre-built for Carthage.
