### ISSUE TITLE
Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by u84six** [realm/realm-cocoa#5726]
After upgrading xcode to 9.3 /swift 4.1, I got incompatibility errors with realm, so I deleted the realm frameworks (3.3.2) that were built using swift 4.0.2 and then added the 4.1 frameworks (3.3.2) back to the project. I'm still getting the same error.

## Steps to Reproduce
- Click on project target, go to General, delete embedded libraries RealmSwift.framework, Realm.framework.
- Got to downloaded Real folder and under ios/swift4.1, drag both frameworks into Embedded frameworks section.
- Clean the project, fire off a build, and I get the error: "Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1 and it's pointing to import RealmSwift in one of my files.

## Version of Realm and Tooling

Realm framework version: 3.3.2

Xcode version: 9.3

iOS/OSX version: 11

Dependency manager + version: I don't use a dependency manager.

**Comment by u84six** [comment]
I just found a dupe of this problem on here, but none of the solutions have worked for me. I tried compiling/building the source, and while the build was successful, the error is the same after adding the frameworks. I also tried the new 3.3.2 version and the swift 4.1 build gives the same error. I deleted the DerivedData folder, cleaned, restarted, etc, same error.

**Comment by u84six** [comment]
I figured out what it was. The original dependency was still local and the bash script was building the wrong one!

**Comment by imran20487** [comment]
@u84six   How do I correct the bash script?
