### ISSUE TITLE
CompactMap iterates more times than number of objects within results

### ISSUE THREAD

**Issue by RVijay007** [realm/realm-cocoa#5728]
## Goals
Iterating over a Realm Collection (realm.objects(ObjectType)) using compactMap. Example:

```
DDLogVerbose("Object Type: \(objectType) has count \(realm.objects(objectType).count): \(realm.objects(objectType))")
var jsonData = [Data]()

                    let contents = realm.objects(objectType).compactMap({ (realmObject: Object) -> String? in
                        if let appObject = realmObject as? (LLTransient & Codable), let data = appObject.toJSONData() {
                            DDLogVerbose("Adding data for \(appObject.objectId)")
                            jsonData.append(data)
                            return appObject.objectId
                        } else {
                            return nil
                        }
                    })
```

## Expected Results
I expect the internal loop that creates json data from all the objects to only loop for as many objects are in the collection results.

## Actual Results
Printing the count of objects in the query return 1 (Correct)
```
04/11 16:05:24.786 (LLDatabaseManager:143) [V] Object Type: LLRTCSynchronization has count 1: Results<LLRTCSynchronization> <0x108f3ad30> (
	[0] LLRTCSynchronization {
		peripheralDate = 2018-04-11 23:04:37 +0000;
		centralDate = 2018-04-11 23:04:38 +0000;
		objectName = LLRTCSynchronization;
		objectId = 1523487878;
		schemaVersion = 0;
		creationDate = 2018-04-11 23:04:38 +0000;
		secondsFromGMT = -25200;
	}
)
```

Printing the result of the compactMap is also correct
```
04/11 16:05:24.787 (LLDatabaseManager:155) [V] Contents Count: 1
```

Printing the internal loop which also creates secondary data that is stored runs mulitple times:
```
04/11 16:05:24.787 (LLDatabaseManager:146) [V] Adding data for 1523487878
04/11 16:05:24.787 (LLDatabaseManager:146) [V] Adding data for 1523487878
04/11 16:05:24.787 (LLDatabaseManager:146) [V] Adding data for 1523487878
04/11 16:05:24.787 (LLDatabaseManager:146) [V] Adding data for 1523487878
04/11 16:05:24.787 (LLDatabaseManager:146) [V] Adding data for 1523487878
```

## Steps to Reproduce

Code above

## Code Sample

Code above

## Version of Realm and Tooling

Realm framework version: 3.3.2

Realm Object Server version: None

Xcode version: 9.3

iOS/OSX version: 11.3

Dependency manager + version: Cocoapods 1.5.0

**Comment by tgoyne** [comment]
`Results` conforms to `LazyCollectionProtocol`, which means that `compactMap()` returns a `LazyMapCollection`, which computes the transformation on-demand and does not cache the result. This means that code like `let result = collection.compactMap{ ...}; print("\(result)"); print("\(result)")` will call the transform function on each element twice.

If you want to eagerly evaluate the transformation and store the result in an array, you should call `Array()` on the result of `compactMap()`.

**Comment by RVijay007** [comment]
Ah cool. Thanks!
