### ISSUE TITLE
Reduce realm file size on logout of the application.

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#5731]
I am using Realm for my application. On logout of the application I am using deleteAll on Realm but Realm file size is same as before logout.

What else I need to do before logout to delete all and reduce transaction size of the file.

I am using should compact on launch which is working. are there any other methods to be used to reduce the file size during logout.

**Comment by bmunkholm** [comment]
Nothing to vacuum it when closing the file, unfortunately. Depending on how you "logout", you could close the file, and reopen with compactOnLaunch.

**Comment by santhoshs5** [comment]
How can I close the file using realm object?

**Comment by bmunkholm** [comment]
The file is closed automatically when all objects referring to it has been deallocated. You can ensure that with autoreleasepool - see https://realm.io/docs/swift/latest/#deleting-realm-files
