### ISSUE TITLE
How Define Realm Model in Swift if using Realm OBJC

### ISSUE THREAD

**Issue by expertalex** [realm/realm-cocoa#5732]
In the oficial website you say:

> Realm Objective‑C is designed to work well with mixed Objective‑C and Swift projects. From Swift, you can do everything you can do when using Realm from Objective‑C, like **defining models** and using Realm’s Objective‑C API. 

How can we define a model in .swift file when using Realm OBJC.

Issues 1: Inherid from Object: **Use of undeclared type 'Object'**
```Swift
@objcMembers class UserDBO :Object{
       @objc dynamic var userId : String;
       @objc dynamic var name : String?
}
```

Issue 2:  Inherid from  RLMRObject: **Class 'UserDBO' has no initializers**
```Swift
@objcMembers class UserDBO :RLMObject{
       @objc dynamic var userId : String;
       @objc dynamic var name : String?
}
```

Can you provide an example for a model definition in swift?

Thanks

**Comment by RVijay007** [comment]
For issue 1, did you import RealmSwift?

**Comment by expertalex** [comment]
NO, Because we are using Realm OBCJ. (pod 'Realm')
We Imported Realm.
And added **RLMSupport.swift** as recommended in the main page:

> We recommend you compile the Swift/RLMSupport.swift file (which is also available in our release zip). This file adds Sequence conformance to Realm Objective‑C collection types and re-exposes Objective‑C methods that aren’t natively accessible from Swift like methods including variadic arguments.

We follow this instructions:
1. Install CocoaPods 1.1.0 or later.
2. Run pod repo update to make CocoaPods aware of the latest available Realm versions.
3. In your Podfile, add pod 'Realm' to your app target and pod 'Realm/Headers' to your test target.
4. From the command line, run pod install.
5. Use the .xcworkspace file generated by CocoaPods to work on your project!
6. If using Realm with Swift, drag the file at Swift/RLMSupport.swift into the File Navigator of your Xcode project, checking the Copy items if needed checkbox.

**Comment by expertalex** [comment]
Ok.

Now I have a runtime error:

> Terminating app due to uncaught exception 'RLMException', reason: 'Property 'languages' is declared as 'NSArray', which is not a supported RLMObject property type. All properties must be primitives, NSString, NSDate, NSData, NSNumber, RLMArray, RLMLinkingObjects, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information...

```Swift
import Realm

@objcMembers class UserDBO: RLMObject{

 @objc dynamic var userId : String?

 @objc dynamic var name : String?

@objc dynamic var presence : Int8 = 0

 @objc dynamic var languages : Array<String> = []

}
```


As I understood Array is not supported.
So i change it to RLMArray:

```Swift
@objc dynamic var languages : RLMArray<String> = []
```

But The following error happened: RLMArray' requires that 'String' be a class type 

Thanks

**Comment by ccortessanchez** [comment]
I'm having a similar problem. Models in Swift are being saved to database unless they have an RLMArray property, then addOrUpdate method fails

**Comment by lets-swapcode** [comment]
try this,

@objc dynamic var languages: RLMArray = RLMArray<String>(objectClassName: String.className())

**Comment by ericjordanmossman** [comment]
@expertalex 
If the above didn't work for you are you able to declare `RLMArray<NSString>` then define within `init()`?

**Comment by ericjordanmossman** [comment]
After looking into this more, we do not support defining arrays of primitives on swift subclasses of RLMObject.
