### ISSUE TITLE
'Realm/Realm.h' file not found

### ISSUE THREAD

**Issue by habiburrahuman** [realm/realm-cocoa#5741]
I have install Realm POD in my project. I can build my project , But when i archive the project for release we face 'Realm/Realm.h' file not found.

Please help us to fix this issue.

Realm framework version: Realm (3.4.0)
Xcode version: 9.3
iOS/OSX version: 10.13.4

same issue https://stackoverflow.com/questions/44923754/realm-realm-h-file-not-found-in-ios-when-archiving

**Comment by bmunkholm** [comment]
Was answered on SO - which it the right place for issues like this ;-)
