### ISSUE TITLE
Crash on `do_get_table` of `group.hpp`

### ISSUE THREAD

**Issue by iShavgula-TacTill** [realm/realm-cocoa#5743]
## Goals
Avoid this crash.

## Expected Results
Normal application launch.

## Actual Results
Infinite crash loop on application launch.
As well, the application Realm Browser crashes directly after trying to open the .realm file which I got from my device. Realm Studio can not open the file neither. I can provide you with the file itself if it helps.

## Steps to Reproduce
Force restart iOS device and launch the application. Doesn't reproduce every time and for every device.

Realm framework version: 3.1.1 - 3.5.0

Xcode version: 9.3

iOS/OSX version: iOS 11

**Comment by bmunkholm** [comment]
Sounds like you are trying to open a file that is corrupt.
Please provide the full stack trace.

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
