### ISSUE TITLE
Update selectively fields provided from object mapper

### ISSUE THREAD

**Issue by superandrew** [realm/realm-cocoa#5744]
## Goals

I have a lists of item provided by a server. Such items are located on a map. I want to provide results in the list ordered by distance. When I request the data from server, distance is related to coordinates provided to the API method. So when you are in new york the list contains the event ordered following the ascending distance from new york. In the map API method, distance isn't provided, because if you zoom to Boston it will give you distances like if you were in Boston, so when you go back to the list distances aren't correct.

To accomplish this, we dont't provide the `distance` field in the map service. However the Object Mapper when updating the realm record, puts the default value in the distance which is a Max Double value.

## Expected Results

I would like realm to leave the fields I don't pass to the Object Mapper to be ignored, or provide a way to ignore fields in an update.
## Actual Results

The `distance` field isn't provided, so realm updates the record with the default value.
## Code Sample

    
    for event in events{
        var e2 = event
        e2.removeValue(forKey: "distance")
        let e = Mapper<Event>().map(JSONObject:e2)            
        realm.create(Event.self, value: e!, update: true)
                 
    }
## Version of Realm and Tooling

Realm framework version: ?
3.5.0
Realm Object Server version: ?

Xcode version: ?
9
iOS/OSX version: ?
11
Dependency manager + version: ?
cocoapod 1.4.0

**Comment by tgoyne** [comment]
If you pass a Dictionary containing only the keys you wish to update to `realm.create()`, then any other fields not present will be left unchanged. By mapping the data from your API to an `Event` object, the information about what keys should and shouldn't be updated is lost.
