### ISSUE TITLE
Limiting Queries Might be required ? for number of realm objects over 500K

### ISSUE THREAD

**Issue by ArEnSc** [realm/realm-cocoa#5746]
## Goals

I have a table view and I created 500K transaction objects.

I did a simple realm.objectsAll() on the transactions.

It blocked the main thread UI.

I used global queue and a thread reference and it made no difference when having it change over to a different thread.

I want it not to block the main thread.

From what I understand, reading about limiting queries, I should read maybe the first 10 rows before I have a tableview access it ? 

## Expected Results

For it not to block the main thread and ramp up memory to 300 mb
## Actual Results

It ramped up memory to 300mb and brought it back down

## Steps to Reproduce

Create a 500K transactions with 5 fields, make them strings.
Then create a list or table view and load it. It should block the main ui even if you query using a thread reference.

## Code Sample
Ill provide a code sample later.

## Version of Realm and Tooling

Realm framework version: ?

3.3.0

Realm Object Server version: ?

Xcode version: ?
latest 

iOS/OSX version: ?

ios 11.0

Dependency manager + version: ?

**Comment by bmunkholm** [comment]
@ArEnSc Is this synthetic test, or do you really need to get 500k objects at once?

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
