### ISSUE TITLE
Application freezing issues 

### ISSUE THREAD

**Issue by tech4solitude** [realm/realm-cocoa#5749]
Application freezes after using sometime after integrating Realm manager. I'm not sure on how to use it in background thread and how to avoid this deadlock. Can you guys help me out 
Realm framework version:  Latest one

Xcode version: 9.2

iOS/OSX version: 11.0

![screen shot 2018-04-25 at 10 27 20](https://user-images.githubusercontent.com/13044958/39501131-aedcb93e-4dd6-11e8-91ac-a4eabbc08701.png)
![screen shot 2018-04-25 at 10 27 35](https://user-images.githubusercontent.com/13044958/39501132-af390d60-4dd6-11e8-8af3-d49629f24911.png)

**Comment by tgoyne** [comment]
I'm not sure what those screenshots are supposed to show. They don't show the app in a deadlock.

**Comment by bmunkholm** [comment]
@tech4solitude Did you check the docs about threading here? https://realm.io/docs/swift/latest/#threading

As mentioned in the issue template, we aim to use this repo for bug reports and feature requests only. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!
