### ISSUE TITLE
The database is empty, the next day or later.

### ISSUE THREAD

**Issue by BarredEwe** [realm/realm-cocoa#5750]
The database is empty, the next day or later. 
These are simply no available data in the database, but new data is recorded and stored by a couple of days.

## Version of Realm and Tooling

Realm framework version: 3.4.0

Xcode version: 9.3

iOS/OSX version: 11.3

Dependency manager + version: Swinject

**Comment by bmunkholm** [comment]
@BarredEwe I'm sorry, but it's not enough information to help you in any way. You have to be much more explicit about your problem and why you think there should be a bug in Realm that causes your issue.

**Comment by BarredEwe** [comment]
@bmunkholm In the appendix there are no methods for database cleanup. But the database is completely cleared in a few days.

    init() {
            let fileURL = FileManager.default
                .containerURL(forSecurityApplicationGroupIdentifier: "*************")!
                .appendingPathComponent("Library/Caches/default.realm")
            Realm.Configuration.defaultConfiguration.fileURL = fileURL
        self.realm = try! Realm()
    }

**Comment by BarredEwe** [comment]
@nirinchev Precisely, thanks, I think the problem was solved.
