### ISSUE TITLE
important latency mid day

### ISSUE THREAD

**Issue by raphaels17** [realm/realm-cocoa#5751]
**Bugs**: The apps gets super slow over the course of the day. We write couple hundred objects a day (with an average 25 property/ ref to another object). By the middle of the day, writing an object takes several seconds, We compact realm at night to gain in efficiency but we believe we might be something wrong.
Is this reduction in speed normal? What can be achieved to limit it?

Realm framework version: 'RealmSwift','~> 2.10.1'

Xcode version: latest

iOS/OSX version:  11

Dependency manager + version: cocoaPod

**Comment by tgoyne** [comment]
No, write performance does not normally get worse over time. Without seeing any of the code involved it's hard for me to make any guesses about what could be causing it for you.

**Comment by raphaels17** [comment]
Indeed After some further deep dive the write performance is what is affected.
What gets slower the Notification block to be notified from object being written. "the notif is received + 00:00:05  after the object is written" after 2 hundreds write


I have a class Boat
```
changeSpeed(speed:Int)
try! realm.write {
                self.hasChanged = true
                 self.speeed = speed
} 

```
A BoatviewController which I see from a boatlistView 
on the boatview controller I can change speed and the UI is change using a Notification block on the boat.
We change speed (an plenty of other characterics) of boats couple hundreds times a day.
Is there anything known about notification block performance we should take into account ?

**Comment by raphaels17** [comment]
This is what I observe regarding Realmlisteners thread after a certain time. Would this help
assessing what is wrong with our realm notifications ?
Please tell you me this is crystal clear to you :-)

[
<img width="659" alt="screen shot 2018-05-10 at 3 03 29 pm" src="https://user-images.githubusercontent.com/3678600/39872409-2e168652-5468-11e8-84a4-dff27f2e24c2.png">
](url)

**Comment by raphaels17** [comment]
Hi 


I m trying to understand. We are properly deinit the notification everywhere however I m looking at our different notification, I see some are missing the   [weak self] in
.addNotificationBlock { [weak self]

could this cause the issue?

**Comment by raphaels17** [comment]
Closing We have noticed an issue in memory when invoking realm object. I will investigate open  issues regarding this topics and act accordingly
