### ISSUE TITLE
realm json

### ISSUE THREAD

**Issue by 350541732** [realm/realm-cocoa#5752]
Realm is really a good way to store, I really like it. But what model does I use to convert json data into a realm-supported model?

**Comment by bmunkholm** [comment]
Did you check the docs here: https://realm.io/docs/swift/latest/#json?

As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!
