### ISSUE TITLE
可以关联性更新吗？

### ISSUE THREAD

**Issue by yushuyi** [realm/realm-cocoa#5755]
final class Card: Object {
    @objc dynamic var date: String!
    @objc dynamic var number: Int = 0
}

当我修改 date = "2015-06-29" 时
检测到这条数据有更新时， 自动修改 number 字段 的值 自动写入 29

**Comment by Lax** [comment]
You can use [Notification](https://www.realm.io/docs/objc/latest/#notifications) to

**Comment by yushuyi** [comment]
`        VarForCurrentCards.notificationToken = pointerCurrentNotes?.observe({ (changes: RealmCollectionChange<Results<Note>>) in
            switch changes {
            case .error(_):
                ();
                break
            case .update(let r,let deletions,let insertions,let modifications):
                Note.update({ () -> [Note] in
                    modifications.forEach {
                        let note = r[$0]
                        note.number = Float(self.computeInterval(note.subTitle, kind: note.clockKind))
                    }
                    return []
                })
                break
            default:
                ();
            }
        })`

这样写 会不停的循环调用

**Comment by yushuyi** [comment]
@Lax 我尝试使用了  Notification， 我在回调里面更新了另外一个字段的值， 结果 无限递归调用了。

**Comment by Lax** [comment]
Check `RLMPropertyChange` and exclude `date` property to terminate endless loop.

**Comment by yushuyi** [comment]
@Lax 谢谢
