### ISSUE TITLE
'Property 'error' is declared as 'id',

### ISSUE THREAD

**Issue by 350541732** [realm/realm-cocoa#5759]
'Property 'error' is declared as 'id', which is not a supported RLMObject property type. All properties must be primitives, NSString, NSDate, NSData, NSNumber, RLMArray, RLMLinkingObjects, or subclasses of RLMObject.
but it works well yesterday..
class User: Object{
    @objc dynamic var username:String = ""
    @objc dynamic var password:String = ""
    
  class  func tetxToModelWith(_ username:String,_ password:String)->User{
        let user = User()
        user.username = "RY"+username
        user.password = password
        return user
    }
}

        viewModel.signedIn
            .subscribe(onNext: { [weak self] _ in
                //
                let realm = try! Realm(configuration: RealmConfiguration.shareInstance.setDefaultRealmForUser())
                try! realm.write {
                    print(realm.configuration.fileURL!)
                    realm.deleteAll()
                }
                if let username = self?.usernameOutlet.text, let password = self?.passwordOutlet.text{
                   try! realm.write {
                       realm.add(User.tetxToModelWith(username, password))
                    }
                }
            })
            .disposed(by:disposeBag)

class RealmConfiguration {
    static let shareInstance = RealmConfiguration()
    func setDefaultRealmForUser()->Realm.Configuration{
        var config = Realm.Configuration()
        config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent("User.realm")
        return config
    }
}
can u help me ?

**Comment by 350541732** [comment]
solve it 。。。。

**Comment by dwirandytlvk** [comment]
how do you solve it?
