### ISSUE TITLE
realm exception:RLMErrorAddressSpaceExhausted

### ISSUE THREAD

**Issue by zyx449678686** [realm/realm-cocoa#5761]
Last Exception Backtrace:
0   CoreFoundation                	0x182976d8c 0x182831000 + 1334668
1   libobjc.A.dylib               	0x181b305ec 0x181b28000 + 34284
2   APPNAME               	0x1006e6a8c RLMSetErrorOrThrow(NSError*, NSError* __autoreleasing*) + 6466188 (RLMUtil.mm:336)
3   APPNAME              	0x1006c3654 RLMRealmTranslateException(NSError* __autoreleasing*) + 6321748 (RLMRealm.mm:316)
4   APPNAME               	0x1006c4958 translateSharedGroupOpenException(RLMRealmConfiguration*, NSError* __autoreleasing*) + 6326616 (RLMRealm.mm:354)
5   APPNAME               	0x1006c46f0 +[RLMRealm realmWithConfiguration:error:] + 6326000 (RLMRealm.mm:403)
6   APPNAME               	0x1006c2b34 +[RLMRealm defaultRealm] + 6318900 (RLMRealm.mm:177)
7   APPNAME               	0x100474f68 -[OCRealmDataManager initRealmCenter:] + 3903336 (OCRealmDataManager.m:173)
8   APPNAME               	0x100474970 -[OCRealmDataManager init] + 3901808 (OCRealmDataManager.m:78)
9   APPNAME               	0x1004748b4 __35+[OCRealmDataManager shareInstance]_block_invoke + 3901620 (OCRealmDataManager.m:68)

Realm framework version: ?
The latest version
Xcode version: ?
9.3
iOS/OSX version: ?
11.4

I have been experiencing such a carsh, can you help me solve it? Thanks a lot.

**Comment by bmunkholm** [comment]
If we should have a chance to progress on this we would very much appreciate a self-contained reproduction case either as a project, a test-case PR or a Playground example. Thanks for your help!

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
