### ISSUE TITLE
hide default.realm and other realm files/folders from itunes sharing?

### ISSUE THREAD

**Issue by byjoh** [realm/realm-cocoa#5762]
Is there an option for hiding realm files from itunes sharing?  I would like to turn it on for my users to allow them to download videos taken by the app but don't want them messing with the realm files.

**Comment by tgoyne** [comment]
Filenames starting with a dot (`.`) will not appear in iTunes file sharing, so you can just change the path of the default realm to `.default.realm`.

**Comment by byjoh** [comment]
Ah perfect.  Thanks for the help.
