### ISSUE TITLE
Realm problem 

### ISSUE THREAD

**Issue by eleyanSaad** [realm/realm-cocoa#5763]
Hi 

i created an ios swift 4 app  to add a photo in collection view, with Realm, but when I opened the app in other iPhone simulation and login with email and password, I didn't see any photo  that i added before 
for example :::

when I open it in iPhone 8 and log in, and add a photo it's added and I can see the photo.
but, when I close it , and open the app in iphone 7 simulation and login agian with the same username i didn't see any change "empty", when I opened my realm local host and acces to the file "empty "

please help me to solve this problem 
![screen shot 2018-05-11 at 11 51 14 pm](https://user-images.githubusercontent.com/38811888/39954541-77d47a24-5576-11e8-93de-566c35cab319.png)
![screen shot 2018-05-11 at 11 51 46 pm](https://user-images.githubusercontent.com/38811888/39954542-780eabfe-5576-11e8-9c21-b40c87935902.png)
![screen shot 2018-05-11 at 11 52 10 pm](https://user-images.githubusercontent.com/38811888/39954543-7841c868-5576-11e8-992a-904e44ab11c1.png)
![screen shot 2018-05-11 at 11 52 29 pm](https://user-images.githubusercontent.com/38811888/39954544-7876c5b8-5576-11e8-82ac-a3a2512113bd.png)
![screen shot 2018-05-11 at 11 52 36 pm](https://user-images.githubusercontent.com/38811888/39954545-789d318a-5576-11e8-8653-ded5084285f6.png)
![screen shot 2018-05-11 at 11 52 40 pm](https://user-images.githubusercontent.com/38811888/39954546-78dca8a6-5576-11e8-9c1d-61bc28329402.png)

**Comment by bmunkholm** [comment]
@eleyanSaad Did you resolve your problem?

Sorry about the lacking response, but as mentioned in the issue template we aim to use this repo only for bug reports or feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!
