### ISSUE TITLE
Memory inflation  Realm _pthread_body

### ISSUE THREAD

**Issue by raphaels17** [realm/realm-cocoa#5764]
Hi 

**Bug ** 
The memory allocated to realm inflate steadily up 3M each we write an object (even if that object is an ID + a Bool).

**Impact:** 
This  Unbounded memory growth is messing with the performance of our app big time. After at the end of the day the app lags terribly 

**Expected** 
Reduce the memory growth, and free up memory be able release realm Object
<img width="1048" alt="screen shot 2018-05-13 at 11 25 44 am" src="https://user-images.githubusercontent.com/3678600/39966159-60ede6ce-56a7-11e8-9452-0ea46a7241eb.png">

**Version 2.10.1**

Our  findings in Instrument (Snapshot Attached) : 
-**with the timer** that the  _pthread_body, that has realm ref takes all resources
it seems to keeps all my object alive long after we are done looking at them ? Is that it?

- **with the allocation** that
I tried to understand what exactly grow and found + 1M on _ContiguousArrayStorage<MetadataTerritory> every time.  Is this were realm object are stored?

**Comment by tgoyne** [comment]
`_ContiguousArrayStorage` is the backing storage for a Swift `Array`. As Realm is not implemented in Swift (the Swift API is a thin wrapper around the objective-c API) it is unlikely that these objects are being allocated directly by Realm. With the information provided I can't really make any guesses as to what is being allocated.

**Comment by raphaels17** [comment]
Thank you so much, this seems to have solved most of our issue!

 unfortunately we had hope this would also solved our latency in our realm notification, but that is still a work in progress
