### ISSUE TITLE
Make Query-based Sync the default mode for syncing data

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-cocoa#5767]
All bindings need to adopt Query-based synchronization (formerly named Partial Sync) as the default mode of synching. This is most likely a breaking API change which requires a major API bump.

Java merged their PR here: realm/realm-java#5893

In particular the setting on SyncConfiguration was renamed from partialRealm() to fullSynchronization().

- [ ] Change API
- [ ] Update documentation to use Query-based Sync instead of Partial Sync

**Comment by bmunkholm** [comment]
Done
