### ISSUE TITLE
`pod install` took VERY LONG time

### ISSUE THREAD

**Issue by yijiasu** [realm/realm-cocoa#5769]
## Version of Realm and Tooling

Realm framework version: 
Latest

Realm Object Server version: N/A

Xcode version: Xcode 9.3

iOS/OSX version: 11.3

Dependency manager + version: 
➜  ~ pod --version
1.5.2

**Comment by bmunkholm** [comment]
Ok. Not sure we can do much about that. Not clear what a long time is, but it's likely related to you internet connection speed.
