### ISSUE TITLE
Ambiguous reference to member 'transactionWithBlock'

### ISSUE THREAD

**Issue by expertalex** [realm/realm-cocoa#5771]
Hello. We are using Realm Objc in a Swift project.

But we can't translate this int swift:
```OBJC
[realm transactionWithBlock:^{
            person.name = @"Jane Doe";
}];
```

We try this:
```Swift
do {
    try realm.transactionWithBlock{
                            
    }
 }
catch{
       printError(message: error.localizedDescription);
}
```
**Error: Ambiguous reference to member 'transactionWithBlock'** 

What is the alternative? Thanks

P.S. Using Relam Swift is not an option

**Comment by jsflax** [comment]
Objc, when compiled to Swift, automatically converts the naming Objc naming convention `with...` to be a named Swift Parameter. So `- (void)fooWithBar:(Bar *)bar` becomes `func foo(bar: Bar)`.

In your use case, this is sufficient:
```swift
do {
    try realm.transaction {
                            
    }
 } catch {
       printError(message: error.localizedDescription);
}
```
