### ISSUE TITLE
Database growing significantly

### ISSUE THREAD

**Issue by OURZSMJ** [realm/realm-cocoa#5772]
code like this:
    man *m = [[man alloc] init];
    m.uid = 1;    //long
    m.time = 0; //long
    [[RLMRealm defaultRealm] beginWriteTransaction];
    [man createOrUpdateInDefaultRealmWithValue:m];
    [[RLMRealm defaultRealm] commitWriteTransaction];
    NSLog(@"%@",[RLMRealm defaultRealm].configuration.fileURL);
    while (1) {
        // Query and update the result in another thread
        dispatch_async(dispatch_queue_create("background", 0), ^{
            @autoreleasepool {
                man *m1 = [[man objectsWhere:@"uid = 1"] firstObject];
                RLMRealm *realm = [RLMRealm defaultRealm];
                [realm refresh];
                [realm beginWriteTransaction];
                m1.time += 1;
                
                [realm commitWriteTransaction];
                NSLog(@"%ld",m1.time);
            }
        });
        usleep(100000);
    }

the size of "default.realm"  grow  significantly.Any help or guidelines on how to access the Realm across multiple threads is welcome, thanks

**Comment by bmunkholm** [comment]
Please be specific about "significantly"? When adding an object we don't just expand the file for that particular object, but also for future data. So it will grow in larger "steps".

As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!
