### ISSUE TITLE
Emoji decoding fails

### ISSUE THREAD

**Issue by skyfoxa** [realm/realm-cocoa#5774]
## Goals
I have a chat screen in my app, where we want to be able to use emojis as well. The message is sent to the backend via Socket.io framework where is handled. The messages go through this socket and are stored on the device using Realm. 

## Expected Results
When a message is created/received it should be stored with Realm as usual string value. 

## Actual Results
The string value from the sender arrives fine, I've checked it in the debugger. It is parsed with the Object Mapper and shown to the user. It works fine as well. But when the app is killed and relaunched, I guess the realm takes part here, the variable with the message contains wrongly decoded unicode chars for emojis. 

## Steps to Reproduce
Try to send e.g. ✈️, the received JSON value is "\U00e2\U009c\U0088\U00ef\U00b8\U008f". After relaunching the app the string value is "âï¸".

## Code Sample
```
class TextMessageChat: Object, Mappable {
    private struct Keys {
        static let id = "_id"
        static let messageType = "messageType"
        static let createdAt = "createdAt"
        static let seen = "seen"
        static let updatedAt = "updatedAt"
        static let message = "message"
        static let videoURL = "videoURL"
        static let userId = "userId"
        static let error = "error"
        static let seenMessageId = "message_id"
    }
    
    enum MessageType: String, Codable {
        case text = "TEXT_MESSAGE"
        
        var title: String {
            switch self {
            case .text:
                return "Text"
            }
        }
    }
    
    @objc dynamic var _id: String!
    @objc dynamic var _messageType: String!
    
    var messageType: MessageType! {
        get {
            return MessageType(rawValue: _messageType)!
        }
        
        set {
            self._messageType = messageType.rawValue
        }
    }
    
    @objc dynamic var createdAt: String!
    var updatedAt = RealmOptional<Int>()
    
    var message: String? {
        get {
            guard let decoded = self.messageRaw else {
                return decoded 
        }

        set {
            guard let encoded = newValue else {
                self.messageRaw = nil
                return
            }
            
            self.messageRaw = encoded 
        }
    }
    
    @objc dynamic var messageRaw: String?
    @objc dynamic var videoURL: String?
    @objc dynamic var userId: String!
    let lastReceiver = RealmOptional<Bool>()
    let seen = RealmOptional<Bool>()
    var error: ErrorMessage?
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    // Mappable
    func mapping(map: Map) {
        _id            <- map[Keys.id]
        _messageType   <- (map[Keys.messageType])
        createdAt     <- (map[Keys.createdAt])
        updatedAt     <- map[Keys.updatedAt]
        
        message <- map[Keys.message]
        
        videoURL      <- map[Keys.videoURL]
        userId        <- map[Keys.userId]
        seen.value    <- map[Keys.seen]
        if seen.value == nil {
            seen.value = false
        }
        error         <- map[Keys.error]
    }
    
    convenience init(message: String) {
        self.init()
        self.message = message
        
    }
}
```
## Version of Realm and Tooling

Realm framework version: 3.3.0

Realm Object Server version: --

Xcode version: 9.2 (9C40b)

iOS/OSX version: iOS 11.2.2

Dependency manager + version: CocoaPods 1.4.0

**Comment by tgoyne** [comment]
We [do have a test which verifies that we can store and retrieve emoji](https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Tests/SwiftUnicodeTests.swift), and adding ✈️ to the test string works fine. If you can reduce your problem to a concise repro case that would be helpful.

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
