### ISSUE TITLE
Unnecessary received Modifications Objects in observer

### ISSUE THREAD

**Issue by jayarajm** [realm/realm-cocoa#5776]
**Questions**: I initiated observer for particular Object like "Team". Already I have 20 Teams. I added few(Ex. 5) Team objects to realm. But My observer received "0 deletions, 5 insertions, 20 modifications". I don't know why I get this 20 modifications in my observer. Because of this notification I get some blink and some more Issues. Please Kindly help me.

Goal:
I need to achieve unwanted loading

Expected result:
I don't want to get 20 modification unnecessary

Thanks,
Jayaraj M

**Comment by JayarajTrans** [comment]
Initiated Observer
`func addObserRecent() {
        items = realm.objects(Recent.self).filter("has_deleted == 0").sorted(byKeyPath: "created_ts", ascending: false)
        notificationToken = items.observe { (changes: RealmCollectionChange) in
            switch changes {
            case .initial:
                self.tableView.reloadData()
                break
            case .update(let items, let deletions, let insertions, let modifications):
                self.tableView.reloadData()
                break;
            case .error(_):
                break;
            }
        }
    }`

Load into Realm
`                    for item in items as! NSArray {
                        realm.add(item as! Recent, update: true)
                    }
`

I Loaded only 10 items. But I already have 20 items. 
The observer is display 10 insertions and 20 modifications.
I didn't update any old items.

**Comment by nikok** [comment]
The same problem happens to me. I did some testing and found out that in my case it happnes when both of these conditions are met
1. The realm is synchronized with Realm Cloud and the objects are added on another device. (When they are added on the same device, it doesn’t happen.)
2. The model object that is observed (collection notifications), has a relationship to another model object. (When observing model objects that have no relationships, it doesn’t happen.)

When inserting,I get the modification indexes of all other objects that are linked to the same object by the relationship.
In my case these can be 1000s of modification indexes of objects that have not been modified, which causes a lot of overhead:(

**Comment by bmunkholm** [comment]
@nikok @jayarajm @JayarajTrans It's really helpful if you can provide a self-contained repro-example. That expedites the resolution a lot. Thanks for your help!

**Comment by jsflax** [comment]
@nikok @jayarajm @JayarajTrans Is there any update on this? Otherwise we will close this out.

**Comment by leemaguire** [comment]
Closed due to age, if you have any more questions please open a new issue.

Thanks.
