### ISSUE TITLE
mmap() failed: Cannot allocate memory size

### ISSUE THREAD

**Issue by omidgolparvar** [realm/realm-cocoa#5778]
## Goals

I developed an iOS application which contain one `Personal Framework` and two `Today Extension`. In order to access/modify data from app and extensions, I used `AppGroup` and all data will be accessible from shared storage. 
I have access to data, wherever I need, by a Singleton in my `Framework`; in `Main Application` and `Today Extension`s, and there was no problem in accessing/modifying data. I also modify data from `AppDelegate` background fetch method (`application(_, performFetchWithCompletionHandler:)`) .

But, in SOME cases (for SOME users/testers), it is crashing with this error message:
```
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: 
Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 2013265920 
offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory 
size: 2013265920 offset: 0, Error Code=9}
```

I read other issues related to this error messages, and now, I have some note to tell, and some question to ask:

1. [Note] In some issues, there is suggestions for putting Realm transaction codes in `autoreleasepool { }`. I really don't know what `autoreleasepool { }` is and what does it do!! I'm almost sure, that this `autoreleasepool { }` was NOT in the [official documentation](https://realm.io/docs/swift/latest/)! I know it is in documentation NOW, but at the time of developing first version of my application (near 18 months ago) with `Realm 2.4.4`, there was NO word about `avoiding pinning` or `autoreleasepool`.

2. [Question] If it is wrong to perform Realm transactions, out of `DispatchQueue(label: "background").async { }` and without `autoreleasepool { }`, why the crash/error occurred for SOME of users/tester? (and not occurred for ALL of them, including me!!) I did not have any problem with Realm in my usage of the app. 

3. [Question] Is my approach (using a Singleton `App.shared.realmObject`) right? Is it right to use this in all targets (`Main Application` and `Today Extensions`) in order to access/modify data?

4. [Question] Does using `autoreleasepool { }` and performing all actions in `DispatchQueue(label: "background").async { }` solve my (our!) problem?

## Expected Results

Initialize `Realm` object, and access/modify data from multiple targets.

## Actual Results

At first access to shared `App` object (Singleton), `Realm` object starting to initialize and I will get the error and app will crash. 

## Steps to Reproduce

As I mentioned above, this error/crash is occurred for SOME of our testers/users. And I really don't know how to reproduce this.

## Code Sample

In my personal framework, I use Singleton (so there will be only one instance of `RealmObject`) to use `Realm` object.
```
public final class App {
	public static var shared = App()

	public var realmObject: Realm!
	...
	
	public init() {
		...
		setupRealm()
		...
	}
	
	private func setupRealm() {
		var config = Realm.Configuration()
		config.schemaVersion = 11
		config.fileURL = FileManager
			.default
			.containerURL(forSecurityApplicationGroupIdentifier: "...")!
			.appendingPathComponent("db.realm")
		config.migrationBlock = { migration, oldSchemaVersion in }
		
		Realm.Configuration.defaultConfiguration = config
		realmObject = try! Realm()
	}
	...
}
```

Now, whenever I have `read/write transactions`, I use this:
```
//Read
let objects = App.shared.realmObject.objects(Model.self)
...

//Write
try! App.shared.realmObject.write {
	App.shared.realmContextObject.add(modelObject, update: true)
}
``` 

At first access to `App.shared` (in `AppDelegate`), initialize method is called, and app crashs at `realmObject = try! Realm()`.

## Version of Realm and Tooling

Realm framework version: `3.1.0`

Xcode version: `9.2`

Swift Version: `4.0`

Dependency manager + version: `Cocoapod 1.4.0`

**Comment by omidgolparvar** [comment]
Hello again my friends,

I changed my codes, and did these:
- Using `shouldCompactOnLaunch`:
```
var config = Realm.Configuration()
config.fileURL = FileManager
    .default
    .containerURL(forSecurityApplicationGroupIdentifier: App.UserDefaultsConfig.SuiteName)!
    .appendingPathComponent("db.realm")
config.migrationBlock = { migration, oldSchemaVersion in
    ...
}
config.shouldCompactOnLaunch = { totalBytes, usedBytes in
    let oneHundredMB = 100 * 1024 * 1024
    let result = (totalBytes > oneHundredMB) && (Double(usedBytes) / Double(totalBytes)) < 0.5
    return result
}

Realm.Configuration.defaultConfiguration = config
realmContextObject = try! Realm()
```

- Using `autoreleasepool { ... }`: 
All **write** actions are in `autoreleasepool { ... }` 

Even after these changes, unfortunately, the error is **occurred** again. 

**👉 NOTE**:
I'm using **Background Fetch** in my app (using `application(_, performFetchWithCompletionHandler)` and interval for this is setting based on user's choice. (5, 10, 30 or 60 minutes; Default is 10 minutes)

I think when we have  **Background Fetch**, the app will remain in memory, and it will not close, terminate, or suspend (Unless users manually terminate app, or etc.); In other word, app state is `background`.

So, whenever app performs Background Fetch (or even works with new data while app is in `foreground`), and new data stored in Realm, the function that creates and configures `Realm` object, **WILL NOT** call again, because I call it in `AppDelegate` (once), consequently, `shouldCompactOnLaunch` closure **WILL NOT** call, and size of the Realm file starts to grow; without **ANY** control.

If I am right, and you have any suggestion, tell me to give it a try.

**Comment by bmunkholm** [comment]
The problem is your database file is growing too much. That's why you don't see it with little testing but others do after a while.
I suggest you:
1. Use Google to understand what autoreleasepool means
2. Read the docs about Threading: https://realm.io/docs/swift/latest/#threading
3. From 2. ensure you create a Realm instance specific for each thread you are using. You can't use the same instance across threads. 
4. Use SO for these questions as you get much faster and better response there and we try to use this repo only for bugs and feature requests - as mentioned in the issue template ;-)

Thanks!
