### ISSUE TITLE
Filtered list index(of:) returns index out of bounds after creating Array from collection

### ISSUE THREAD

**Issue by gshahbazian** [realm/realm-cocoa#5779]
## Goals
Filter a `List`, find the index of an element, pass the filtered list as an array, access that index to get the same element back.

## Expected Results
`index(of:)` in the sample should return 0 since the count of the list is 1.

## Actual Results
`index(of:)` returns 1

## Steps to Reproduce
Run code sample below:

## Code Sample
<details><summary>AppDelegate.swift</summary>

```swift
import UIKit
import RealmSwift

class Dog: Object {
    override static func primaryKey() -> String? {
        return "name"
    }

    @objc dynamic var name = ""
    @objc dynamic var age = 0
    let owners = LinkingObjects(fromType: Person.self, property: "dogs")
}

class Person: Object {
    @objc dynamic var name = ""
    let dogs = List<Dog>()
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
        window = UIWindow(frame: UIScreen.main.bounds)
        window?.rootViewController = UIViewController()
        window?.makeKeyAndVisible()

        do {
            try FileManager.default.removeItem(at: Realm.Configuration.defaultConfiguration.fileURL!)
        } catch {}

        let realm = try! Realm()
        try! realm.write {
            realm.create(Person.self, value: ["John", [["Fido", 1], ["Fun Dog", 3]]])
        }

        let dog = realm.objects(Dog.self).last!
        let owner = dog.owners.first!

        let filteredDogs = owner.dogs.filter({ $0.name == "Fun Dog" })
        guard filteredDogs.count > 0 else {
            return true
        }

        guard let index = filteredDogs.index(of: dog) else {
            return true
        }

        let arrayOfFilteredDogs = Array(filteredDogs)
        print("Found dog \(arrayOfFilteredDogs[index])")

        return true
    }
}
```

</details>

## Version of Realm and Tooling
Realm framework version: master @ 8c78a19
Xcode version: 9.3.1
iOS/OSX version: iOS 11.3

**Comment by tgoyne** [comment]
This is just how `LazyCollection` works, and you can observe the same behavior without involving any Realm types at all:

        let values = [1, 2, 3]
        let filteredValues = values.lazy.filter({ $0 == 3 });
        guard let index = filteredValues.index(of: 3) else {
            return
        }
        let arrayOfFilteredValues = Array(filteredValues)
        print("Found \(arrayOfFilteredValues[index])") // crashes as `index` is `2`

`LazyCollection.index(of:)` returns an index usable in that collection, not in an array created from that collection.

If you use Realm's queries rather than the standard library's filtering (i.e. `let filteredDogs = owner.dogs.filter("name = %@", "Fun Dog")`) this does not occur.
