### ISSUE TITLE
Intermediate migration commits

### ISSUE THREAD

**Issue by borut-t** [realm/realm-cocoa#5787]
I have an issue with linear migrations. Let me present the issue with example:

Lets say we are migrating MyObject in realm, that was constructed initially like this:
```swift
MyObject {
  @objc private(set) dynamic var preTaxPrice: Int = 0
  @objc private(set) dynamic var tax: Int = 0
}
```

In schema version 1 we did change props type from `Int` to our custom object `Currency` derived from `Object`.

```swift
if oldSchemaVersion < 1 {
  migration.enumerateObjects(ofType: MyObject.className()) { (oldObject, newObject) in
    let oldPreTaxPrice = oldObject?["preTaxPrice"] as? Int ?? 0
    newObject?["preTaxPrice"] = Currency(cents: oldPreTaxPrice)

    let oldTax = oldObject?["tax"] as? Int ?? 0
    newObject?["tax"] = Currency(cents: oldTax)
  }
}
```

In schema 2 we renamed added `postTaxPrice` prop calculated from `preTaxPrice` and `tax`:

```swift
if oldSchemaVersion < 2 {
  migration.enumerateObjects(ofType: MyObject.className()) { (oldObject, newObject) in
    if let preTaxObjectOld = oldObject?["price"] as? MigrationObject,
      let preTaxPriceAmount = preTaxObjectOld.value(forKey: "cents") as? Int64,
      let taxObjectOld = oldObject?["tax"] as? MigrationObject,
      let taxAmount = taxObjectOld.value(forKey: "cents") as? Int64 {
      let postTaxPriceObjectNew = migration.create(CurrencyStore.className(), value: preTaxObjectOld)
      postTaxPriceObjectNew.setValue(preTaxPriceAmount + taxAmount, forKey: "cents")
      newObject?["postTaxPrice"] = postTaxPriceObjectNew
    }
  }
}
```

Here is the problem I'm facing.
If I migrate from 0 -> 1 and then from 1 -> 2, it works fine. Everything is migrated as it should be.
But when I migrate from 0 -> 2 (e.g. didn't update the app for migration 1), when second migration block is run, `oldObjects` still refers to `Int` as datatype, and that totally makes sense. Because I am currenlty on version 0 (ints) and want to migrate to version 2 (currency).

How to solve this transitional migrations?
It looks like changes aren't persisted yet when enumerating objects. Is there a way to somehow commit changes after enumeration block is done?

**Comment by tgoyne** [comment]
This is a shortcoming of our migrations design that doesn't have a great solution. Ideally when migrating from version 0 to 2 we would do the 0 -> 1 migration, update the schema, then run the 1 -> 2  migration. Unfortunately, we don't actually know what the version 1 schema is; only the initial and final ones.

In practice this means that when you have migrations which rely on previous migrations having run, you need to write separate versions of the logic for migrating from version 0 and from version 1 rather than being able to reuse the old 0 -> 1 migration.

**Comment by borut-t** [comment]
That's what I had in mind also. But I thought there is some better solution to this case. 🤷🏼‍♂️
Thanks, @tgoyne for an explanation.

**Comment by borut-t** [comment]
@tgoyne thought though, I think you should put that into your docs. 🤷🏼‍♂️
