### ISSUE TITLE
New Warnings from C++ Compiler

### ISSUE THREAD

**Issue by phoney** [realm/realm-cocoa#5792]
When I build version 3.6.0 of realm-swift for iOS I get a compiler warning that wasn't there in version 3.5.0.

In sync_session.cpp line 545 there is a switch statement that isn't exhaustive.

        switch (static_cast<ClientError>(error_code.value())) {

Enumeration values 'connect_timeout' and 'bad_timestamp' not handled in switch.

**Comment by bmunkholm** [comment]
Nothing to worry about, but it will be fixed.

**Comment by bmunkholm** [comment]
Fixed
