### ISSUE TITLE
How to keep the original sort when I delete a piece of data

### ISSUE THREAD

**Issue by CHENDONGY** [realm/realm-cocoa#5797]
## Goals
When I delete a piece of data from the database, I want to keep all the data in the original order

## Actual Results
When I delete one of the data, the sort is disorderly

## Steps to Reproduce
original
![2018-06-04 6 03 50](https://user-images.githubusercontent.com/26021469/40911933-c085791c-6822-11e8-9467-d0a7792f0c4f.png)
![2018-06-04 6 04 11](https://user-images.githubusercontent.com/26021469/40911938-c247c46c-6822-11e8-90c1-2675515d4364.png)

## Code Sample

```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.view.backgroundColor = [UIColor redColor];
    
    for (int i = 0; i < 10; i++) {
        Person *person = [[Person alloc] init];
        person.name = [NSString stringWithFormat:@"Jack %d",i];
        person.age = i + 10;
        [self addObject:person];
        
    }
    
//    NSLog(@"%@",NSHomeDirectory());
    
}

- (void)addObject:(Person *)person
{
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm addObject:person];
    }];
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event
{
    NSLog(@"delete");
    
    RLMResults *results = [Person objectsWhere:@"age=12"];
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm deleteObject:results.firstObject];
    }];
}

```

## Version of Realm and Tooling

Realm framework version: 3.5.0

Realm Object Server version: 3.5.0

Xcode version: 9.3

iOS/OSX version: 9.3

**Comment by tgoyne** [comment]
If you want objects to appear in a specific order you must sort by a property which gives that order.
