### ISSUE TITLE
Type mismatch:Signed to unsigned

### ISSUE THREAD

**Issue by pprraasshhaanntthh** [realm/realm-cocoa#5800]
We have a security check tool for verifying any vulnerabilities in realm framework which are using in our app. Can anyone look into the below? let me know any additional information required.

The function value_of_hex_digit() in sync_file.cpp is declared to return an unsigned value, but on line 50 it returns a signed value. 

The function safe_copy_n() in utilities.hpp is declared to return an unsigned value, but on line 273 it returns a signed value.

The function max_size() in transact_log.hpp is declared to return an unsigned value, but on line 894 it returns a signed value.

The function value_of_hex_digit() in sync_file.cpp is declared to return an unsigned value, but on line 54 it returns a signed value.

The function value_of_hex_digit() in sync_file.cpp is declared to return an unsigned value, but on line 52 it returns a signed value.

The function data() in buffer.hpp is declared to return an unsigned value, but on line 65 it returns a signed value.

The function encode() in transact_log.hpp is declared to return an unsigned value, but on line 854 it returns a signed value.

**Comment by pprraasshhaanntthh** [comment]
Any updates?

**Comment by bmunkholm** [comment]
@pprraasshhaanntthh Please ensure to always fill out the issue template. I'm e.g. unaware which version this is, which can affect the checking of the specific line numbers.
But in terms of security, there is nothing in those files that should cause alarms.
