### ISSUE TITLE
Realm/RLMConstants.h file not found

### ISSUE THREAD

**Issue by charvoa** [realm/realm-cocoa#5802]
## Goals
Compile the app on Xcode Version 10.0 beta (10L176w)

## Expected Results
The compilation to run smoothly without errors. 

## Actual Results
Realm/RLMConstants.h file not found
---- 1. In file included from /Users/USERNAME/Documents/Work/APPNAME/iOS/Pods/Realm/Realm/RLMUpdateChecker.mm:22:

## Steps to Reproduce

Podfile : 

    pod 'Realm', :git => 'https://github.com/realm/realm-cocoa', :branch => 'tg/xcode-10', submodules: true
    pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :branch => 'tg/xcode-10', submodules: true

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

/Users/USERNAME/Documents/Work/APPNAME/iOS/../../../../../../Applications/Xcode-beta.app/Contents/Developer
Xcode 10.0
Build version 10L176w

/usr/local/bin/pod
1.5.3
Realm (3.7.0)
RealmSwift (3.7.0)
Realm (from `https//github.com/realm/realm-cocoa`, branch `tg/xcode-10`)
RealmSwift (from `https//github.com/realm/realm-cocoa`, branch `tg/xcode-10`)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

carthage not found
(not in use here)

/usr/bin/git
git version 2.17.0 (Apple Git-106)
```

## Step to remove this error (did not work) 

```
Clean build foler
pod cache clean Realm 
pod cache clean RealmSwift
pod deintegrate
rm -rf Pods
rm -rf ~/Library/Caches/CocoaPods
pod install --verbose
```

**Comment by bmunkholm** [comment]
@charvoa Is this still the case? (I know things have improved since :-) )

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
