### ISSUE TITLE
Invalid redeclaration of 'removeSubrange' in List.swift in Xcode 10 

### ISSUE THREAD

**Issue by EonKid** [realm/realm-cocoa#5803]
i am getting this error when i use this framework on Xcode 10:
"Invalid redeclaration of 'removeSubrange' in List.swift in Xcode 10 "

Realm framework version: v3.7.0

Xcode version: 10

iOS/OSX version: iOS 11

cocoapods version: 1.5.2

**Comment by tgoyne** [comment]
Xcode 10 support will be added in the upcoming 3.7.1 release.

**Comment by mungaiandela** [comment]
Has this been supported?
