### ISSUE TITLE
How do I know if the encrypted database is successful

### ISSUE THREAD

**Issue by zhenghongyi** [realm/realm-cocoa#5804]
I used "writeCopyToURL:encryptionKey:error:" to create a database and encrypt it from an unencrypted database.
but if there is a lot of datas in the unencrypted database, many many datas, and the data tables has a complex structure, there must be need some time to copy to the encrypted database, how do i know if it copy and encrypt successfully?
"writeCopyToURL:encryptionKey:error:" return a BOOL result, if it mean copy and encrypt successful? And if the method will blocking threads?
Thanks and hope to get a reply

**Comment by bmunkholm** [comment]
Please see the docs which explains: https://realm.io/docs/objc/3.7.4/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)writeCopyToURL:encryptionKey:error:
