### ISSUE TITLE
Get average of values in a field in realm react native

### ISSUE THREAD

**Issue by Damilee** [realm/realm-cocoa#5805]
This is telling me 'Can't find variable: gpa' It is also saying unresolved variable Double. I want to fetch all the values submitted in a particular field and compute the average. The average is to be displayed in an alert box. The code is in a function named dbtotal below.

    realm = new Realm({
        schema: [{name: 'CalcGP',
            properties:
                {
                    student_id: {type: 'int',   default: 0},
                    student_name: 'string',
                    semester: 'int',
                    gpa: 'double'
                }}]
    });

}

add_Student=()=>{

    realm.write(() => {

        let ID = realm.objects('CalcGP').length + 1;

        realm.create('CalcGP', {
            student_id: ID,
            student_name: this.state.Student_Name,
            semester: this.state.Semester,
            gpa : this.state.GPA,

        });

    });
    Alert.alert("Details Added Successfully.");
};

   

}

dbtotal() {

    let cgpa: Double = realm.objects('CalcGP').avg(gpa) ;
    Alert.alert(cgpa);

}

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!
