### ISSUE TITLE
Realm Database file size huge when copying objects

### ISSUE THREAD

**Issue by L4grange** [realm/realm-cocoa#5810]
## Goals

I am trying to copy all of the objects of one Realm DB to another one.

## Expected Results

The two databases should have the same size, my original DB is 2.6 MB with about 2220 objects.

## Actual Results

The resulting DB (the new copy) is 37.7MB big.

## Steps to Reproduce

Imagine my schema: I have a Realm DB with Books. Each book has chapters, and each chapter has Articles. In my original realm there is only 1 book for now, but I want to be able to merge multiple "books" into one single realm.
The only thing I did is open the original Realm, get the top (book) object (that has lists containing all other objects) and copy that to my new Realm. The final Realm, is 37.7MB big, instead of the normal 2.6MB

## Version of Realm and Tooling

Realm framework version: 3.0.2, 3.7.1 and 3.7.2 (in my tests, just updated Realm and the issue is still there)

Realm Object Server version: -

Xcode version: 9.3

iOS/OSX version: OSX 10.13.4

Dependency manager + version: CocoaPods 1.4.0

Thanks for the help and this great Database!

**Comment by bmunkholm** [comment]
Try to compact the file and compare results. You can do that by opening the file in the OSX Browser. Or programmatically with compactOnLaunch (or something like that) when you open the file.
The reason is that the file may have allocated additional storage for future writes.

**Comment by L4grange** [comment]
This did the trick! Thank you so much, I was unaware of the "compactOnLaunch"  parameter (and the Export To capability of the Browser). Now my Realm is only 3.1MB big. Thanks again!
