### ISSUE TITLE
Carthage incompatible version for 3.7.1

### ISSUE THREAD

**Issue by NikKovIos** [realm/realm-cocoa#5811]
Carthage update gives an error: `Skipped installing realm-cocoa.framework binary due to the error: "Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)."`

**Comment by tgoyne** [comment]
Despite it using the word "error", this is actually just a warning that it's building from source due to Carthage only supporting packaging a prebuilt binary for a single Xcode version at a time.

**Comment by olejnjak** [comment]
Yep, but it is quite annoying that even the latest version (3.7.4) is still not built using the latest Xcode (9.4.1) 🤷‍♂️
