### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported in Swift 4.1.50

### ISSUE THREAD

**Issue by charvoa** [realm/realm-cocoa#5814]
## Goals
Build on Xcode beta 1 and Swift 4

## Expected Results
Smooth compilation

## Actual Results
Module compiled with Swift 4.1 cannot be imported in Swift 4.1.50: /Users/nicolascharvoz/Documents/Work/RogerVoice/iOS/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule

## Steps to Reproduce
1. Import Realm and RealmSwift as Framework

## Code Sample

`import RealmSwift`

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

/Users/nicolascharvoz/../../Applications/Xcode.app/Contents/Developer
Xcode 9.4
Build version 9F1027a

/usr/local/bin/pod
1.5.3


/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

carthage not found
(not in use here)

/usr/bin/git
git version 2.15.1 (Apple Git-101)
```

**Comment by tgoyne** [comment]
Using Realm with beta versions of Xcode requires building it from source. This can be done in two steps:

```
git clone --recursive https://github.com/realm/realm-cocoa.git
cd realm-cocoa
DEVELOPER_DIR=/Applications/Xcode-beta.app/Contents/Developer sh build.sh ios-swift
```

If you installed the Xcode beta to a different location, adjust the `DEVELOPER_DIR` path to match.

**Comment by charvoa** [comment]
I have a **BUILD FAILED** with this error : 

error: Build input file cannot be found: '/Users/nicolascharvoz/Documents/Work/***/realm-cocoa/RealmSwift/SwiftVersion.swift'
[...] 
The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(2 failures)

Any help ?
