### ISSUE TITLE
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1744830464 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1744830464 offset: 0, Error Code=9}

### ISSUE THREAD

**Issue by akhillifeincontrol** [realm/realm-cocoa#5822]
I got this error for some user on the app store build. After that I have done the "compact on launch" and added all the realm operations running on DispatchQueue in autoreleasepool{...}. But how to handle the users who have already got this issue. I can not make them to reinstall the app

Realm framework version: 3.1.1

Realm Object Server version: ?

Xcode version: 9.2

**Comment by akhillifeincontrol** [comment]
Can anyone help me on this issue.

**Comment by tgoyne** [comment]
Unexplained large file size growth was a possible symptom of the bug which was fixed there, but the fix won't help open existing files which have run into trouble.

**Comment by akramhussein** [comment]
@tgoyne understood - thank you.

We have an issue where after trying to do a realm swap and adding data, it crashes and becomes irreparable for some users (from what we can tell, with low memory devices e.g. iPhone 5s)

Before before try Realm()) is even called in app (so nothing is pointing to it):

1. Download new seed `seed.realm`
2. Rename the `default.realm` to `temporary.realm`
3. Rename `seed.realm` to `default.realm`
4. Copy across user data only from `temporary.realm` to `default.realm`

We've tried multiple ways by using intermediate temporary realms but this is the most efficient.
When I profile step 4, we can see a significant memory increase but I was able to get this down to just 200mb memory for a few seconds in the worst case, which most users won't hit. 

Yet, once the app gets to `try Realm()` it crashes for some users with:

`Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/C54C7FEB-40B4-40AB-96DE-45BC130046F7/Documents/default.realm': Realm file has bad size." UserInfo={Error Code=2, NSFilePath=/var/mobile/Containers/Data/Application/C54C7FEB-40B4-40AB-96DE-45BC130046F7/Documents/default.realm, Underlying=Realm file has bad size, NSLocalizedDescription=Unable to open a realm at path '/var/mobile/Containers/Data/Application/C54C7FEB-40B4-40AB-96DE-45BC130046F7/Documents/default.realm': Realm file has bad size.}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-902.0.48/src/swift/stdlib/public/core/ErrorType.swift, line 184`

Our hunch is during the copy, mmap succeeds but it fails to execute correctly as memory ran out and you are left with a faulty realm file. It's quite hard to diagnose as it happens for some users. I thought it was a low RAM issue, but one user had 29% left on a iPhone 8 according to Crashlytics which is ~500MB of RAM.

Previously I wasn't calling invalidate on the old and new realms but everything was done in `autoreleasepool`. 

I'm wondering if this fix may help this issue and perhaps the `invalidate()`

Do you have any pointers to code on what exactly `bad file size` might entail so I can investigate further? Any help is greatly appreciated.

**Comment by tgoyne** [comment]
"Realm file has bad size" is thrown is the file being opened is not large enough to contain the 24-byte file header (and note that an empty file is not treated like a nonexistent file) or the file size is not a multiple of 8.

One possible cause for this would be if the download failed in a way that created `seed.realm` and left it as a zero-byte file. Missing or incomplete error-handling for the download would also plausibly be something that would only cause problems for some users.

If you're sure that step 4 is succeeding and it's when you subsequently try to re-open the Realm later in the app that it's crashing then I'm not sure what could be causing it. Even a full disk shouldn't result in hitting that specific error.

**Comment by akramhussein** [comment]
@tgoyne I think you are on to something!

Thankfully we log the MD5 hash of these files generated from the client and I totally forgot to check this. After extensive spelunking into the logs and watching the upgrades happen, the user ids with crashes correspond to the logs where the MD5 hash is not the correct one.

Now I need to identify why it failed to download correctly.

**Comment by donelasurya** [comment]
''Unexplained large file size growth was a possible symptom of the bug which was fixed there, but the fix won't help open existing files which have run into trouble.''

@tgoyne What should we do for the existing files which ran into trouble. This is the error we are facing- 
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1744830464 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1744830464 offset: 0, Error Code=9}

**Comment by donelasurya** [comment]
@tgoyne Please help us with it. We are facing the issue in production. Need to update it soon.

**Comment by donelasurya** [comment]
@tgoyne We searched a lot on what to do for the users who have already run into the trouble and we are helpless. There is no documentation anywhere stating this. Please, we really need some quick assistance on this.

**Comment by tgoyne** [comment]
We don't have a good solution for recovering files which have grown too large for a device to open. Uploading the Realm file to a server, compacting it there (via the JS SDK), and then sending it back to the device is pretty much the only thing you can do.

**Comment by donelasurya** [comment]
Thanks @tgoyne
