### ISSUE TITLE
Nested List Search Filtering (Help)

### ISSUE THREAD

**Issue by zuil7** [realm/realm-cocoa#5825]
## Goals
Search Filtering in City. I want to search on city then will return the State result.
Example Array List

[0] StateModel {
		name = Alabama;
		cityArr = List<CityModel> <0x608000106e40> (
			[0] CityModel {
				name = auburn;
			},
			[1] CityModel {
				name = birmingham;
			},
			[2] CityModel {
				name = dothan;
			},
			[3] CityModel {
				name = florence / muscle shoals;
			},
			[4] CityModel {
				name = gadsden-anniston;
			},
			[5] CityModel {
				name = huntsville / decatur;
			},
			[6] CityModel {
				name = mobile;
			},
			[7] CityModel {
				name = montgomery;
			},
			[8] CityModel {
				name = tuscaloosa;
			}
		);
		isChecked = 0;
	},
	[1] StateModel {
		name = Alaska;
		cityArr = List<CityModel> <0x608000106ed0> (
			[0] CityModel {
				name = anchorage / mat-su;
			},
			[1] CityModel {
				name = fairbanks;
			},
			[2] CityModel {
				name = kenai peninsula;
			},
			[3] CityModel {
				name = southeast alaska;
			}
		);
		isChecked = 0;
	},

## Expected Results
i have List below. I will search on auburn(City) it will return me statemodel result
[0] StateModel {
		name = Alabama;
		cityArr = List<CityModel> <0x608000106e40> (
			[0] CityModel {
				name = auburn;
			}
}

## Code Sample
@objcMembers class StateModel: Object  {
    dynamic var name: String = ""
    var cityArr = List<CityModel>()
}

@objcMembers class CityModel: Object {
    dynamic var name: String = ""
    dynamic var href: String = ""    
}

## Version of Realm and Tooling

Realm framework version: 3.7.4

Xcode version: 9.3.1 

iOS/OSX version: 10.13.4

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!
