### ISSUE TITLE
Ability to make RLMObject use a shared table.

### ISSUE THREAD

**Issue by nRewik** [realm/realm-cocoa#5826]
## Goals
Ability to use the shared database table among many `RLMObject` classes.

I have an `Group: RLMObject` which represent full object.

I want to create another realm object, let's say `PartialGroup: RLMObject`, represent only the data that need to be displayed.

They share the same properties, using the approach where I create two classes, I need to maintain consistency by myself, and have redundant data.

![1](https://user-images.githubusercontent.com/6581089/41587107-95186b56-73d8-11e8-8f64-050a9d199dad.png)

Another approach might be using only a single `Group: RLMObject`, but have a flag `isPartial` or `isFull`. But I think this is quite error prone. When I write the code, I need to remember not to forget checking `isPartial` or `isFull` flag.

Is there a way that two classes can point to the same table like this. So I don't need to maintain consistency, but still be able to work on separate classes.

![2](https://user-images.githubusercontent.com/6581089/41638587-667eab14-7484-11e8-8ca5-964da3c2d193.png)

## Expected Results
Be able to create RLMObject that use a shared table.

**Comment by astigsen** [comment]
Have you considered just embedding `PartialGroup` in `Group`?

**Comment by nRewik** [comment]
Yeah, already. There are many partial classes not only one. Partial classes can have different requirements. One might have the same properties with another, but also can have different properties as well. 

For example, 
- `Full` has `prop_1`, `prop_2`, `prop_3`, `prop_4`, `prop_5`
- `Partial A` has `prop_1`, `prop_2`, `prop_3`
- `Partial B` has `prop_1`, `prop_4`

Since `prop_1`, is in all classes, using embedding approach, I also need to create a new class and embed the shared `prop_1` to all. This introduce one more level of hierarchy.

I think it is harder to manage, and it increases code complexity.

---

I just come up with another approach, that I have `Group: RLMObject` as a single table, then create `FullGroup: NSObject` and `PartialGroup: NSObject` as a wrapper to access `Group` table.

However this will be easier, if `RLMObject` can used shared table as I mentioned above.
