### ISSUE TITLE
Xcode 10 Beta Won't Compile When using RealmSwift

### ISSUE THREAD

**Issue by mmdock** [realm/realm-cocoa#5827]
Xcode version:
10 Beta

Swift Version:
Swift 4 (according to Xcode 10 Beta)
Swift 4.1 (according to latest stable Xcode 9)

What I was trying to do:
Compile my application that uses RealmSwift

What happened:
Wouldn't compile because problems with RealmSwift List.swift file (Invalid Re-declarations.)

<img width="866" alt="screen shot 2018-06-21 at 4 15 30 pm" src="https://user-images.githubusercontent.com/2423465/41743311-63c23036-756e-11e8-949d-2ac75718c39d.png">
<img width="713" alt="screen shot 2018-06-21 at 4 15 19 pm" src="https://user-images.githubusercontent.com/2423465/41743312-63d51584-756e-11e8-8b35-24f260ea3c2b.png">

**Comment by Semty** [comment]
@mmdock Update RealmSwift pod

**Comment by abbasmousavi** [comment]
I am using XCode 10 beta 3 and it gives this error when compiling my project
`open ... Realm/Realm.framework/Headers/RLMPlatform.h: Permission denied`

**Comment by grangej** [comment]
@abbasmousavi thanks for this, I thought I was going crazy :) 

Any updates?

**Comment by Pomanks** [comment]
Thanks to @apoltix it's fixed for me ! 😀
See [#5840](https://github.com/realm/realm-cocoa/issues/5840)
