### ISSUE TITLE
Is it possible to have several database files in one project?

### ISSUE THREAD

**Issue by TheHmmka** [realm/realm-cocoa#5830]
## Goals
I want to use several Databases in one project.

## Expected Results

I need to not update schemaVersion in all different databases with changes in one of them. Databased with different file URL path.

## Actual Results

I need to update schemaVersion in all realm instance (databased with different file URL path)

## Steps to Reproduce

Just load two data based with different urls.

## Version of Realm and Tooling
Realm framework version: 3.7.4

Xcode version: 9

iOS/OSX version: Any

Dependency manager + version: CocoaPods

**Comment by tgoyne** [comment]
If you use different, non-overlapping sets of classes in each of the files you can set the `objectTypes` property of the Realm configuration to an array of just those types, and then changes to classes not in that array will not require a migration for that Realm. By default all classes are included in every Realm, so changing any of them will require updating the schema version for every Realm.

**Comment by TheHmmka** [comment]
Looks like a plan! Thank you!
