### ISSUE TITLE
RLMProperty.isPrimary is always false on new schema during migration

### ISSUE THREAD

**Issue by stonesam92** [realm/realm-cocoa#5831]
## Goals
My high level goal is to write a migration block which takes the differences between the old and new schema and deletes only the object of types whose schema have changed, providing an alternative to `deleteRealmIfMigrationNeeded` which avoids deleting objects that aren't (and don't have relationships to other objects that are) changed.

To do this, for each type I'm comparing the `ObjectSchema` objects in the old and new schema on the `Migration` object.

## Expected Results
When I compare two `ObjectSchema` for the same class and whose definition is unchanged since the last migration, they should be equal.

## Actual Results
For objects which define a primary key, the two `ObjectSchema` are never equal. This appears to be because on the `RLMProperty` object for the primary key property `isPrimary` is always false in the new schema.

## Steps to Reproduce
- Create a project with a Realm `Object` subclass that defines a primary key
- Configure realm with a migration block which retrieves the `ObjectSchema` for the class from both the new schema and the old schema and compares them
- Increase the configuration's `schemaVersion` so that the migration block is called, but do not make any changes to the subclass definition
- See that the two `ObjectSchema` objects are not equal, even though their definitions haven't changed

## Code Sample
I have a realm object defined:

    final public class TestRealmRecord: Object {
        @objc dynamic var testProperty: String = ""
    
        override public static func primaryKey() -> String? {
            return "testProperty"
        }
    }

And the following migration block:

    configuration.migrationBlock = { migration, _ in
        let oldSchema = migration.oldSchema.objectSchema.first(where: { $0.className == "TestRealmRecord" })!         let newSchema = migration.newSchema.objectSchema.first(where: { $0.className == "TestRealmRecord" })!
                   
        print("old object schema: \(oldSchema)")
        print("new object schema: \(newSchema)")
        print("schema are equal: \(oldSchema == newSchema)")            
    }

Below is the output of the migration block when I increase the `schemaVersion` but make no change to `TestRealmRecord`

![realmmigrationoutput](https://user-images.githubusercontent.com/825146/41976137-2aaa9324-7a14-11e8-94c0-47a024f9a290.png)

## Version of Realm and Tooling
Realm framework version: 3.1.1

Xcode version: 9.4

iOS version: 11.4

Dependency manager + version: Cocoapods: 1.5.3

**Comment by tgoyne** [comment]
Primary keys are disabled during migrations as a way to sidestep some of the issues around adding a new primary key to an existing class (and thus temporarily having a lot of default values for the primary key). The fact that this leaks out to the public API is an unfortunate result of that the public schema objects are the same ones that we use internally.
