### ISSUE TITLE
type(of:) in combination with generic function crashes on real device

### ISSUE THREAD

**Issue by Jasperav** [realm/realm-cocoa#5833]
## Goals
Printing the type of an object through a generic function

## Expected Results
Printing the type of an object through a generic function

## Actual Results
EXC_BAD_ACCES

## Steps to Reproduce
I am facing some very weird problem getting a function to work from an class which I want to use with Realm. It crashes on a real device, but it does not on a simulator. It crashes on my real device when I use the function below, when directly using `type(of:)`, it doesn't. This is what I mean:

    import Realm
    import RealmSwift

    class A: Object {} // It has to inhert from Object to get the problem
    
    // Some class, lets say appDelegate:
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
        print(type(of: A())) // Works on both simulator and real device
        testt(typee: A()) // Only works in simulator

    }

    func testt<T: A>(typee: T) {
        print(type(of: typee)) // EXC_BAD_ACCESS
    }

I am running iOS 11.0 on my real device and iOS 11.0.1 on the simulator.

Stackoverflow link:
https://stackoverflow.com/questions/51069886/typeof-in-combination-with-generic-function-crashes-on-real-device

**Comment by bmunkholm** [comment]
@Jasperav Can you please post the detailed info from the crash?

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
