### ISSUE TITLE
Wrong data while fetching Results.

### ISSUE THREAD

**Issue by vishaldandge** [realm/realm-cocoa#5836]
## Goals
Get data from database through realm.

## Expected Results
Data is incorrect

## Actual Results
Results fetched on viewController are incorrect but while debugging the results are correct

## Steps to Reproduce
Fetching results with realm database as Results<ObjectType>

## Version of Realm and Tooling
Realm framework version: ?
Updated realm version through cocoapods

Realm Object Server version: ?
Not using Object Server 
Xcode version: ?
9.3
iOS/OSX version: ?
11.0

Dependency manager + version: ?
Cocoapods

**Comment by vishaldandge** [comment]
When i add breakpoints to check the issue. The Result data is as expected but without breakpoint its incorrect. Am i missing some important part to implement?

**Comment by bmunkholm** [comment]
@vishaldandge In "Steps to reproduce" please add the steps we need to take to reproduce this issues. Ideally a self-contained example project we can just run. Thanks!

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
