### ISSUE TITLE
Xcode 10 Beta 3 header issue

### ISSUE THREAD

**Issue by grangej** [realm/realm-cocoa#5840]
While trying to compile with Xcode 10 beta 3 it fails with header permission issue, I have tried several things such as clearing pods, clearing pod cache, clearing derived data etc. 

This works as expected in Xcode beta 2

## Expected Results
👍 Compile :)

## Actual Results
open ... Realm/Realm.framework/Headers/RLMPlatform.h: Permission denied

## Steps to Reproduce
Compile with latest Realm modules from Cocoapods

## Version of Realm and Tooling
Realm framework version: Latest

Realm Object Server version: Latest

Xcode version: Xcode 10 beta 3

iOS/OSX version: OS X 10.14 Beta 3

Dependency manager + version: Cocoapods 1.5.3

This is related to - #5827 but specific to Xcode 10 Beta 3

**Comment by apoltix** [comment]
It seems Xcode has an issue with the fact the file is empty. Insert a comment or something into the file, e.g. `// This file is blank` and Xcode compiles the project just fine.

**Comment by avjiang** [comment]
@apoltix 

Hi i am having problem when compiling the project using Xcode 10 Beta 3 with following error : 
'impl/weak_realm_notifier.hpp' file not found

Also i couldnt find the Pods/Realm/include/RLMPlatform.h 
inside my Realm. I am using RealmSwift latest version.

Hopefully you can guide me thanks

**Comment by CedricGatay** [comment]
For the record `chmod 666 Pods/Realm/include/RLMPlatform.h` also does the trick for building.

**Comment by bartoszhernas** [comment]
@CedricGatay Your tip fixed the problem, thanks !
