### ISSUE TITLE
Pod Install Fails installing realm and RealmSwift even now.

### ISSUE THREAD

**Issue by brucekk248** [realm/realm-cocoa#5843]
I use xcode 9.4.1
OS 10.13
Command line installed yet i keep getting this error. 
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   : command not found
   : command not found
   : invalid option namet: pipefail
   : invalid option4: set: -
   set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

: command not found
: command not found
: invalid option namet: pipefail
: invalid option4: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]

There is no document either. Could anyone help me on this?
@realm-admin

**Comment by tgoyne** [comment]
See https://github.com/realm/realm-cocoa/issues/2662 for some steps that solved this problem for other users.

**Comment by brucekk248** [comment]
@tgoyne : Thanks man 
These steps helped 
git config --global core.autocrlf input
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install )"
