### ISSUE TITLE
Realm 'impl/weak_realm_notifier.hpp' file not found Xcode 10 Beta 3

### ISSUE THREAD

**Issue by avjiang** [realm/realm-cocoa#5845]
**Questions**: Unable to Compile Project with Xcode 10 beta 3

Realm 
'impl/weak_realm_notifier.hpp' file not found

RealmSwift
Umbrella header 'Realm.h' not found
Could not build Objective-C module 'Realm'

![screenshot 2018-07-06 at 2 51 21 pm](https://user-images.githubusercontent.com/19270457/42364069-81872b48-812c-11e8-8ac3-ef396a2a76c4.png)

## Goals
Able to compile project with Realm using Xcode 10 beta 3

## Actual Results
Could not able to compile the project

## Steps to Reproduce
Pod install the realm into project using cocoapods

Realm framework version: 3.7.4

Realm Object Server version: N/A

Xcode version: 10 beta 3

iOS/OSX version: Mojave Beta 3

Dependency manager + version: cocoapods version 1.4.0

**Comment by bmunkholm** [comment]
@avjiang Is this still an issue for you?

**Comment by avjiang** [comment]
Hi @bmunkholm  thanks for the response. I have resolved this by deleting the realm from the Pods folder and then clean build folder and then pod install back. the error didnt show up anymore.

Hope this will help others with the same problem in the future. Thanks

**Comment by s4rv4d** [comment]
I'm still facing this issue even after reinstalling after clean build folder

**Comment by bmunkholm** [comment]
@s4rv4d Sorry this was missed. But commenting on a closed issue is highly likely not to be seen. Please create a new issue with your specific details if this is still a problem for you. Thanks!

**Comment by goa** [comment]
For anyone interested. I had the same problem in Xcode 10.1 stable. 

I had installed Realm via Cocoapods, along with RxRealm which depends on it. 

I had specified no versions for the pods and everything was fixed by doing a `pod update`.
