### ISSUE TITLE
Realm crashes after accessing "objectForPrimaryKey:" 

### ISSUE THREAD

**Issue by vsridharan6** [realm/realm-cocoa#5846]
!!! MANDATORY TO FILL OUT !!!

## Goals
Trying to use Realm for our React Native and Native needs. 

## Expected Results
We use Realm Native version - 3.7.4
Using Realm React Native - 2.12.15

When are saving a value onto Realm, we fetch for "objectWithPrimaryKey". If that object does not exist, we create a new entry and "addOrUpdateObject".

        RLMRealm *realm = [RLMRealm defaultRealm];

        [realm transactionWithBlock:^{

            RealmKeyValuePair *authKey = [RealmKeyValuePair objectForPrimaryKey:AUTH_KEY];

            if (!authKey) {
                authKey = [[RealmKeyValuePair alloc] init];
                authKey.key = AUTH_KEY;
            }
        
            authKey.value = new_value;
            [realm addOrUpdateObject: authKey];
        }];

## Actual Results

App crashes. The issue is that the crash is not consistent. It's a little hard to reproduce the bug.

Here's the crash that happened while debugging.

For some reason, when we retrieve the call with "RealmKeyValuePair *authKey = [RealmKeyValuePair objectForPrimaryKey:AUTH_KEY];", 

This mostly returns the key in db, but it's sometimes returns nil.

So we end up executing the code to create a new key, and it returns an RLM: unmanaged object and it crashes. 

if (!authKey) {
      authKey = [[RealmKeyValuePair alloc] init];
}

The crash happens immediately after we call "Realm addOrUpdateObject".

Note: This does not happen all the time which makes our debugging a nightmare.

Here's some details on the crash from debugger.

(lldb) po realm
<RLMRealm: 0x7d0a5d30>

(lldb) p * authKey
(RealmKeyValuePair) $5 = {
  RLMObject = {
    RLMObjectBase = {
      NSObject = {
        isa = RLM:Unmanaged RealmKeyValuePair
      }
      _realm = 0x7d0a5d30
      _objectSchema = 0x7a69e720
    }
  }
  _key = 0x01746844 @"Auth-Token"
  _value = nil
}
(lldb) po authKey.class
RLM:Unmanaged RealmKeyValuePair

### Here's a crash from a real device in production. ###

Thread 0 Crashed:
0   Realm                                0x0000000104c7b4bc 0x1049fc000 + 2618556
1   Realm                                0x0000000104a7702c 0x1049fc000 + 503852
2   Realm                                0x0000000104a75608 0x1049fc000 + 497160
3   Realm                                0x0000000104a75378 0x1049fc000 + 496504
4   Realm                                0x0000000104ad13e8 0x1049fc000 + 873448
5   TestApp                           0x0000000103212044 __37+[RealmDBUpdater updateAuthToken:]_block_invoke (RealmDBUpdater.m:132)
6   Realm                                0x0000000104ad0df4 0x1049fc000 + 871924

## Steps to Reproduce
No direct steps to reproduce. We make an api call to update our auth token, after the app is launched. Sometimes the app crashes becuase it returns a nil objectWithPrimaryKey.

## Version of Realm and Tooling

Realm framework version: 3.7.4

Using Realm JS - 2.12.15

Realm Object Server version: ?

Xcode version:  Xcode 9

iOS/OSX version: 11.2, 11.3, 11.4

Dependency manager + version: ?

**Comment by vsridharan6** [comment]
Any update on this? @realm-admin

**Comment by jsflax** [comment]
Hi @vsridharan6 can you please give us more complete sample code?
