### ISSUE TITLE
Archive - No such module 'RealmSwift' 

### ISSUE THREAD

**Issue by TwitchedDesign** [realm/realm-cocoa#5847]
## Goals
Archive product 

## Expected Results
Archive succesfull

## Actual Results
error, No such module 'RealmSwift' 

## Steps to Reproduce
Open an project and archive product. 

## Version of Realm and Tooling
Realm framework version: ?
3.7.4 

Xcode version: 9.4.1 

iOS version:  11.0 

Tried multiple solutions. pod install , pod update, pod deintegrate and pod install. restarting the computer. 

i tried: 

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

**Comment by TwitchedDesign** [comment]
Removed all ios versions in the project and in podfile did the trick.

**Comment by soushu** [comment]
Specifically, how can this be done?
