### ISSUE TITLE
Compact functionality seems to randomly take an extremely long time to finish compacting

### ISSUE THREAD

**Issue by jasper-chan** [realm/realm-cocoa#5848]
**Bugs**: 
If there is a tmp_compaction_space file in the same directory as the Realm database on compaction, sometimes the tmp_compaction_space file is not removed and creates a deadlock.

## Goals
Directory should be cleaned every time automatically by Realm prior executing compaction

## Expected Results
tmp_compaction_space file should be deleted and compaction should be completed

## Actual Results
Deadlock occurs and our application waits indefinitely for it to finish

## Steps to Reproduce
No reliable steps to reproduce the problem

## Version of Realm and Tooling

Realm framework version: 3.5.0

Realm Object Server version: N/A

Xcode version: 9.2

iOS/OSX version: 11.1.2

Please find enclosed a Google Drive link to the realm files to help with your analysis. I do not have access to the encryption key to open the database.
https://drive.google.com/open?id=1ECS7L8TWaqOiX3crdkz9l7WLjpPoKA3s

**Comment by tgoyne** [comment]
`compact()` does try to remove the temporary file. I suspect that's failing (due to a permissions issue?), and we aren't handling that error correctly.

**Comment by tgoyne** [comment]
I wrote a basic test for this that passes (https://github.com/realm/realm-cocoa/pull/5852). It appears that the file existing is fine, and not being able to delete the existing file is handled properly.

**Comment by jasper-chan** [comment]
Thank you for responding @tgoyne. This is a concern of ours as its occurred enough to our customers where the only solution they have currently is to delete the application and re-install. This has caused users to lose their data.

1. Is there something I can do in the meantime to help us discover whether this is the problem?
2. In the meantime, can we just search for this file before we attempt to open realm and just delete it as a preventative matter?

**Comment by tgoyne** [comment]
Deleting it yourself first *shouldn't* help, but trying and logging any errors that occur might help identify what's going wrong? The main thing to be careful about is to be sure to delete it at a time when there's no possibility of a compaction actually being in progress.

**Comment by jasper-chan** [comment]
@tgoyne based on our log files, we don't see any errors. It seems like once the application calls defaultRealm, it never completes.

**Comment by tgoyne** [comment]
Do you do anything nontrivial in the predicate function? That's called with some locks held, so doing anything more complicated than some arithmetic could produce deadlocks.

Other than that the compaction logic is all pretty simple so it's not at all obvious what could be going wrong.

**Comment by jasper-chan** [comment]
Are you referring to the compaction code block? If so, no we are not. I essentially copied what is available in the guide.

`    defaultConfiguration.shouldCompactOnLaunch = ^BOOL(NSUInteger totalBytes, NSUInteger usedBytes){
        // totalBytes refers to the size of the file on disk in bytes (data + free space)
        // usedBytes refers to the number of bytes used by data in the file
        
        // Compact if the file is over 50MB in size and less than 50% 'used'
        NSUInteger fiftyMB = 50 * 1024 * 1024;
        return (totalBytes > fiftyMB) && (usedBytes / totalBytes) < 0.5;
    };`

**Comment by jasper-chan** [comment]
Hi Realm,

We have an update on this issue. We can somewhat make this happen reliably now. Please find enclosed a link to my Google drive that has access to the data:

https://drive.google.com/drive/folders/1YZNpljRmKJ_F5h2wqQf1SZ1EzjfeBY7U?usp=sharing

On our director's request, I have been instructed to not provide the encryption key to the database on this forum. Could I have someone directly from the Realm support team to email me at: jasper.chan@scenedoc.com? I would be glad to provide the key through the email.

Thanks,

**Comment by jasper-chan** [comment]
Another update,

We tried another experiment on an iPhone 6s and after waiting 40+ minutes, it eventually finished doing whatever it was doing, and our application was able to continue working as normal.

**Comment by tgoyne** [comment]
Is this with a Realm version older than 3.7.6? That version eliminated some pointless work when compacting Realms which could potentially be very slow.

In the video I notice that the file is being compacted several times in sequence. Is this something you were specifically triggering for testing purposes? If not, then either the compaction predicate is wrong or we're reporting incorrect sizes for encrypted realms.

**Comment by jasper-chan** [comment]
@tgoyne 
1) Yes this was done on Realm version 3.5.0. We upgraded to v3.7.6 in our own branch with the same database in hopes that the new version would help us resolve this, but it didn't.

2) No we do not do anything intentional with the compaction. The default RLMRealmConfiguration is set once, using the code snippet I provided above demonstrating what we do in the compact block. If it is compacting multiple times (it just keeps doing it and doesn't seem to ever stop), it is not intentional.

**Comment by jasper-chan** [comment]
Hi @tgoyne,

Is there an update in response to my last reply? We are very anxious and nervous about this problem. We have customers who cannot open the database and sync up data to our server because of this issue.

**Comment by tgoyne** [comment]
I've tried testing compact on launch with encrypted realms of various sizes and my guess that maybe the difference between the logical size and physical size for them was causing problems seems to be incorrect.

I suppose it's possible that there's something specific to your realm file that's causing problems. I've sent you an email from my realm.io account which you can send the key to.

**Comment by tgoyne** [comment]
Okay, I think I see what's wrong. For this specific file we're reporting that only 92% of the file is in use even immediately after compaction, which may or may not be a bug (I need to look into that more). This results in it triggering compaction every time the file is opened, because the example code in the obj-c docs divides two ints and requests compaction any time the file is over the minimum size and is anything short of 100% used. The fix here should be to just do what the Swift example code does and cast the sizes to `double` before dividing so that it actually does the intended thing of compacting files that are at least 50% free space.

**Comment by jasper-chan** [comment]
@tgoyne 

That is very interesting. I have implemented your fix and it fixed the problem! Let me know if there is anything else I can do to assist you in your investigation. Thank you for your swift response and actions behind this issue.
