### ISSUE TITLE
Sync UITableView with sections

### ISSUE THREAD

**Issue by AppleFlash** [realm/realm-cocoa#5850]
Similar problem was in https://github.com/realm/realm-cocoa/issues/4506, but i couldn't find right answer.
I'm use approach like in GroupedTableView example in RealmSwift, but with some modifications - I'm not reload tableView every time when Results change, instead I use array of NotificationToken to determine what sections and items was changed. It works perfectly by adding one new item manually. But I'm faced the problem with updating tableView during adding item by click to "BG add" button (insert few items in background).

## Goals
Need some mechanism to determine when all Results items updated and after it update tableView (something like delegate methods `func realmDidStartUpdate(_ realm: Realm)` and `func realmDidEndUpdate(_ realm: Realm)`).

## Expected Results
Update UITableView with sections without reloadData()

## Actual Results
Because of the model (array of Results) updates before observation block will called I get crash when insert/delete/modif items in different sections at once 

> 'Invalid update: invalid number of rows in section 1. The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (0), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

## Code Sample
I use code from https://github.com/realm/realm-cocoa/tree/master/examples/ios/swift/GroupedTableView, but instead of
`notificationToken = realm.observe { [unowned self] note, realm in
            self.tableView.reloadData()
}`
I'm use this

```objectsBySection.forEach { (section) in
    let notificationToken = section.observe({ (changes) in 
        switch changes { 
        case .initial(let items):
                self.tableView.reloadData() 
        case .update(let items, deletions: let del, insertions: let ins, modifications: let modif):
                 if let index = objectsBySection.index(of: items) {
                         self.tableView.beginUpdates() 
                         self.tableView.insertRows(at: ins.map { IndexPath(item: $0, section: index) }, with: .left) 
                         self.tableView.deleteRows(at: del.map { IndexPath(item: $0, section: index) }, with: .fade) 
                         self.tableView.reloadRows(at: modif.map { IndexPath(item: $0, section: index) }, with: .none) 
                         self.tableView.endUpdates() // Crash here!
                } 
        case .error(let error): 
               print(error)
        } 
    }) 
     notificationTokens.append(notificationToken) 
}

**Comment by tgoyne** [comment]
The reason this fails is because all of the Results are updated to the new state at once, but only one observation block can be called at a time. This means that when the data for multiple sections change, the call to `endUpdates()` within the first changed section's observation block happens before the tableview has been told about all of the changes to its datasource.

There currently isn't an elegant way to handle this, but one thing you can do is to take advantage of that observation blocks on the Realm itself are called after all of the Results ones and do the call to `endUpdates()` there instead.

**Comment by leemaguire** [comment]
Closing this issue due to age, if you have any other questions please open a new issue.

Thanks.
