### ISSUE TITLE
Application crashed when init realm ?

### ISSUE THREAD

**Issue by ngocdtph03070** [realm/realm-cocoa#5854]
I call create realm in app delegate app has problem not update  user interface and remove init Realm app run normal.

**Comment by bmunkholm** [comment]
@ngocdtph03070 Please fill out the issue template with a self-contained repro case that demonstrates a bug in Realm. It's impossible to help you with the little information you have provided.

**Comment by ngocdtph03070** [comment]
Thanks for response i created 
let realm = try! Realm() issues 
I handle register subclass extend Object of realm is app run
