### ISSUE TITLE
Primary key property 'id' has duplicate values after migration 

### ISSUE THREAD

**Issue by afrodev** [realm/realm-cocoa#5855]
I receive this error of some user from Appstore. 

> Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=1 "Primary key property 'Attendance.id' has duplicate values after migration."

I made a migration of a object **A**. And the error comes from another object **B** that I don't changed anything. 

What can cause this?

Realm framework version: RealmSwift 3.0.1
Xcode version: 9.4.1
iOS/OSX version: 11.4.0
Dependency manager + version: CocoaPods 1.5.3

**Comment by bmunkholm** [comment]
After your migration, you now have two objects with the same primary key - which is not allowed.
