### ISSUE TITLE
I have an issue from Fabric. Please alert it .Thanks

### ISSUE THREAD

**Issue by michaelmou** [realm/realm-cocoa#5862]
!!! MANDATORY TO FILL OUT !!!

0  libsystem_kernel.dylib         0x7fff59900b66 __pthread_kill + 10
1  libsystem_pthread.dylib        0x7fff59acb080 pthread_kill + 333
2  libsystem_c.dylib              0x7fff5985c1ae abort + 127
3  AppName                     0x1092ae3a9 please_report_this_error_to_help_at_realm_dot_io + 389753
4  AppName                     0x1092ae924 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 391156
5  AppName                     0x1092aebe5 realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 391861
6  AppName                     0x10935d0ac realm::ArrayBlob::replace(unsigned long, unsigned long, char const*, unsigned long, bool) + 574572
7  AppName                     0x109363f53 realm::ArrayStringLong::insert(unsigned long, realm::StringData) + 602899
8  AppName                     0x10936472c realm::ArrayStringLong::bptree_leaf_insert(unsigned long, realm::StringData, realm::TreeInsertBase&) + 604908
9  AppName                     0x109386204 realm::StringColumn::bptree_insert(unsigned long, realm::StringData, unsigned long) + 742852
10 AppName                     0x109386418 realm::StringColumn::do_insert(unsigned long, realm::StringData, unsigned long, bool) + 743384
11 AppName                     0x1094596c4 realm::Table::insert_empty_row(unsigned long, unsigned long) + 589860
12 AppName                     0x10916809c realm::Object realm::Object::create<objc_object* __strong, RLMAccessorContext>(RLMAccessorContext&, std::__1::shared_ptr<realm::Realm> const&, realm::ObjectSchema const&, objc_object* __strong, bool, realm::BasicRow<realm::Table>*) (bind_ptr.hpp:176)
13 AppName                     0x109167cfe RLMAddObjectToRealm (RLMObjectStore.mm:132)
## Steps to Reproduce

this is fabric's data , don't have any reproduce router

## Code Sample

setting:
  WebModel* webModel = [self querry:key];
    RLMRealm* realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    if (nil == webModel) {
        webModel = [[WebModel alloc] init];
        webModel.key = key;
        [realm addObject:webModel];
    }
    webModel.value = [string copy];
    [realm commitWriteTransaction];

getting:
 WebModel* webModel = [self querry:key];
    if (nil == webModel) {
        return nil;
    }

    return [webModel.value copy];

querry:
    if (key == nil || [key isEqualToString:@""]) {
        return nil;
    }
    NSPredicate* pred = [NSPredicate predicateWithFormat:@"key = %@", key];
    RLMResults<WebModel*>* webModels = [WebModel objectsWithPredicate:pred];
    return webModels.firstObject;

## Version of Realm and Tooling

Realm framework version:  pod 'Realm', '~>2.9.1'

Realm Object Server version: NO

Xcode version: 9.2

iOS/OSX version: 
Operating Systems
<img width="357" alt="image" src="https://user-images.githubusercontent.com/5761759/43112683-ce43e484-8f29-11e8-842b-182b95d6968f.png">

Dependency manager + version: ?

**Comment by leemaguire** [comment]
Closing this issue due to age, if you have any other questions please open a new issue.

Thanks.
