### ISSUE TITLE
realm cloud notification only fired once, not during the synchronization

### ISSUE THREAD

**Issue by avjiang** [realm/realm-cocoa#5863]
## Goals
Show the progress when syncing the realm local db from the realm cloud

## Expected Results

The syncsession progress notification will keep reporting the data during synchronization

## Actual Results

The progress notification will only fire after the synchronization complete

## Steps to Reproduce

Just add the progress notification from Sync Session class

## Code Sample

    override func viewDidLoad() {
     let session = SyncUser.current!.session(for: Constants.REALM_URL)!
     var token: SyncSession.ProgressNotificationToken?
     token = session.addProgressNotification(for: .download,
                                                mode: .forCurrentlyOutstandingWork) { progress in
                                                    self.updateProgressBar(fraction: progress.fractionTransferred)
                                                    if progress.isTransferComplete {
                                                        //                                                        hideProgressBar()
                                                        token?.invalidate()
                                                    }
                                                    else {
                                                        print("TOTAL DOWNLOAD DATA: \(progress.transferrableBytes)")
                                                    }
        }
     }

    private func updateProgressBar(fraction: Double) {
        print("DOWNLOAD PROGRESS : \(fraction)")
    }

## Version of Realm and Tooling

Realm framework version: 3.7.4

Realm Object Server version: NEWEST

Xcode version: Xcode 10 beta 4

iOS/OSX version: Mojave beta 4

Dependency manager + version: Cocoapods

**Comment by ericjordanmossman** [comment]
@avjiang 
Could you share which [sync type](https://docs.realm.io/sync/using-synced-realms/choosing-your-sync-type) you're using? This may be relevant.

Thanks for the information!
