### ISSUE TITLE
Feature request: Delete with predicate

### ISSUE THREAD

**Issue by noamtamim** [realm/realm-cocoa#5865]
## Goals
Delete object that match a predicate; something like the following SQL statement:
`DELETE FROM Books WHERE genre != 'SciFi'`
This has to be more efficient than loading those objects just to delete them.

## Expected Results
As above -- an easy and efficient way to delete objects that match a predicate.

**Comment by tgoyne** [comment]
The Realm equivalent of that query is`realm.delete(realm.objects(Book.self).filter("genre != 'SciFi'"))`, and this does skip a large amount of the work that a manual loop over the objects would do.

**Comment by noamtamim** [comment]
This should be documented, in particular the fact that in the above snippet, Realm does not load all objects just to delete them.
