### ISSUE TITLE
Observing a collection nests too far

### ISSUE THREAD

**Issue by RikvanderLinde** [realm/realm-cocoa#5867]
I have a very realm structure thats very nested, with things hooked in lists in list.
I want to observe a primary list, checking the date properties of only the entity of the list.
A quick diagram to give a simple idea of the setup:

class Agenda

Property: dateStart
Property: dateEnd
Property: List[B]

class B
Property: List[C]

class C
Property: List[A]
Property: foo
Property: bar

Now the problem is, the observer triggers on ANYTHING changing, even foo or bar, and with this setup thats pretty much the entire realm.

I am aware that you can put observers on specific object, and check their properties. Potentially with KVO.
But that would result in observing the start date and end date for every entity already in the list, plus an observer that checks when a new agenda entry gets added or removed, and then assigning those new observers to the new entry as well or taking them away.

I also know you can do an insert without notifying a token, but that means I need to make the token global, letting my UI side send random tokens back and forth between the back end async realm data that comes in. 

A way to limit the depth on the observer would work, but an exclude list that works on result sets would be prefered.

## Goals

Observe changes in a result set, but not nested indefinitly
## Expected Results

I expected to get updated when something in the direct result set changes, and not some random instance down the line.
## Actual Results

When an instance somewhat related to my list is changed, the observer triggers with a generic "Something updated somewhere with something"

## Code Sample
```
refreshToken = results.observe
{
        changes in
        switch changes
        {
                case .update(_, let deletions, let insertions, let modifications):
                // So this triggers on anything changing, anywhere.
                if deletions.count > 0 || insertions.count > 0
                {
                        // This at least narrows it down to the result set, but only gives me addons and removals
                }
                default: break
        }
}
```

Realm framework version: 3.3.2

Realm Object Server version: ?

Xcode version: 9.4.1

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by ericjordanmossman** [comment]
@RikvanderLinde 

- One primary method would be [object notifications](https://realm.io/docs/swift/latest/#object-notifications), which you mentioned.

- Another method may be selectively notifying when you're making a write transaction. ex)

```
let realm = try! Realm()

// Observe Realm Notifications
let token = realm.observe { notification, realm in
    // ... handle update
}

// Later, pass the token in an array to the realm.write(withoutNotifying:)
// method to write without send a notification to that observer.
try! realm.write(withoutNotifying: [token]) {
    // ... write to realm
}
```

- Dependent on the ultimate goal of your object relationships you may also want to consider [inverse relationships](https://realm.io/docs/swift/latest/#inverse-relationships). Inverse relationships will not take notifications into account.

**Comment by RikvanderLinde** [comment]
@ericjordanmossman 

This idea does work, but as you can imagine with any kind of model this quickly becomes a hassle.
For every write you make, you will have to keep track of a subset of tokens you wish to exclude.
At that point it probably becomes easier to write a wrapper around your write call and just notify things yourself, which is not the direction to go I'd say.

Inverse relationships would work, but it does mean you lock yourself down to that. If I did want something to update on a change you would look to having them cascade their changes up to force a trigger.

For some of these cases I changed the property back to an ID, using the class getter to fetch my object again. Not the greatest solution, but perhaps I can clean that up with an inverse relationship.


Some finer grained selection on a token seems like an interesting feature, but with some model changes I can work around it for now.

**Comment by ericjordanmossman** [comment]
@RikvanderLinde 
I'll close this this issue because related objects are intended to trigger notifications and we've touched on various tools you can use to reach the desired behavior.

Thanks!
