### ISSUE TITLE
Updated binary framework in releases

### ISSUE THREAD

**Issue by aramikg** [realm/realm-cocoa#5870]
## Goals
Update framework in releases to be built with swift 4.1.2
so we can download the binary framework from releases through Carthage

## Expected Results
doesn't build the project, just downloads the framework.

## Actual Results
the framework is not built with 4.1.2, it's built with 4.1 so it builds the project.

**Comment by yutae** [comment]
+1 

![2018-08-02 6 25 06](https://user-images.githubusercontent.com/14192093/43575283-70136e84-9681-11e8-8c6c-218db91e3ab5.png)

Building scheme currently takes 7 minutes.

**Comment by EmDee** [comment]
Out of interest: Does Realm collect data which compiler their users are using, and provide Carthage binaries according to that data?

**Comment by tgoyne** [comment]
Yes, when we're running in a simulator (but not on a device!) we report some basic information about target platform, xcode version, etc. to help us judge what we need to support. You can see the logic in [RLMAnalytics.mm](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMAnalytics.mm).

**Comment by tgoyne** [comment]
The last few releases have been built with Xcode 9.4.
