### ISSUE TITLE
Advice on how to open a read-only sync realm when offline

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-cocoa#5872]
## Goals
Reliably open a  read-only sync realm. Use a mobile-first  both OFFLINE and online.

## Expected Results
A read-only sync realm that has previously been downloaded should be available when a user is offline.

## Actual Results
`Realm.asyncOpen` **hangs indefinitely**, causing the app to hang with no available data.

https://github.com/realm/realm-cocoa/issues/5186 mentions this is a known issues, but does not give any advice as to how to handle this situation. What would be recommended?

Should we simply set all read-only realm back to writable, then have an error time out and `try! Realm(configuration:)` ?

I have tried using `SyncManager.shared.errorHandler`, but it has proved unreliable in an asynchronous context. It seems obvious that `Realm.asyncOpen(configuration: configuration, callback: { (realm, error) ...` should callback with an error, perhaps, `Realm doesn't currently support read-only synchronised realms when the the network is unavailable`. This way, each `asyncOpen` could report its own error. I had two asynchronous `Realm.asyncOpen`, but `SyncManager.shared.errorHandler` got confused.

I also receive thousands of... 
```
TIC TCP Conn Failed [6:0x608000170a40]: 1:50 Err(50)
Task <3A6D17E4-9674-40C1-8229-166FAEF5D40D>.<6> HTTP load failed (error code: -1009 [1:50]
Task <3A6D17E4-9674-40C1-8229-166FAEF5D40D>.<6> finished with error - code: -1009
TIC TCP Conn Failed [7:0x600000170980]: 1:50 Err(50)
Task <1202CCB9-91F9-4A8D-B5E0-636FCF0A2A6A>.<7> HTTP load failed (error code: -1009 [1:50]
Task <1202CCB9-91F9-4A8D-B5E0-636FCF0A2A6A>.<7> finished with error - code: -1009
```
messages in the console, making monitoring the app a bore.

I noticed that https://github.com/realm/realm-object-store/pull/511 was merged almost a year ago. Does this fix the issue? 

Thanks,

Daniel

## Steps to Reproduce
Call `Realm.asyncOpen` without an active internet connect.

## Code Sample
Deactivate wifi, then:
```
SyncManager.shared.errorHandler = { err, _ in
print.error("\(err)")
}
Realm.asyncOpen(configuration: configuration, callback: { (realm, error) in
}
```
causes `Error Domain=io.realm.sync Code=8 "(null)" UserInfo={underlying_error=Error Domain=io.realm.sync.auth Code=1 "(null)"}`

## Version of Realm and Tooling
Realm framework version: 3.7.5

Realm Object Server version: Release 3.6.3

Xcode version: 9.4.1

iOS/OSX version: 11/ 10.13.6

Dependency manager + version: Carthage 0.30

**Comment by tgoyne** [comment]
All that `asyncOpen()` does is download the latest data for the Realm before opening it. If you do not want to wait for the download to complete, then you should not use `asyncOpen()` and should instead just use the normal `Realm` initializer to open the Realm immediately. Using `asyncOpen()` to open a read-only Realm is only required if you do not already have a local copy of the Realm downloaded.
