### ISSUE TITLE
'Realm accessed from incorrect thread.' While accessing Realm via Siri Shortcuts.

### ISSUE THREAD

**Issue by kidsid-Ixigo** [realm/realm-cocoa#5874]
## Expected Results
I am expecting it to work it seamlessly with Siri Shortcut like it works with my main app.

## Actual Results
e.g. the stack trace of a crash
2018-08-07 09:05:36.498102+0530 TrainsIntents[21484:1449214] *** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010feea73b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010f2dc735 objc_exception_throw + 48
	2   Realm                               0x000000010dc23819 -[RLMRealm verifyThread] + 137
	3   Realm                               0x000000010daeae37 _ZL18RLMVerifyRealmReadP8RLMRealm + 87
	4   Realm                               0x000000010daea71a RLMGetObjects + 90
	5   RealmSwift                          0x000000010e5699d5 $S10RealmSwift0A0C7objectsyAA7ResultsCyxGxmAA6ObjectCRbzlF + 277
	6   TrainsIntents                       0x000000010bc66ec6 $S13TrainsIntents12RealmManagerC7objects6ofType0C5Swift7ResultsCyxGxm_tAF6ObjectCRbzlF + 38
	7   TrainsIntents                       0x000000010bdc3f1c $S13TrainsIntents17TrainRouteManagerC5route4withAA0C6DetailCSgSS_tF + 92
	8   TrainsIntents                       0x000000010bc3bbd7 $S13TrainsIntents20RunningStatusManagerC18fetchTrainSchedule4with9isRefresh10completionySS_SbySayAA0gH0CGSg_s5Error_pSgtctF + 135
	9   TrainsIntents                       0x000000010bc3e3b6 $S13TrainsIntents20RunningStatusManagerC05fetchD04with9startDate9isRefresh43shouldShowLocationPermissionErrorIfRequired0L16ConsiderNTESData10completionySS_10Foundation0I0VS3byAA05TraincD0CSg_APSayAA0W8ScheduleCGSgARSgs0P0_pSgtctF + 1286
	10  TrainsIntents                       0x000000010bc2cb01 $S13TrainsIntents26RunningStatusIntentHandlerC6handle6intent10completionyAA0cdE0C_yAA0cdE8ResponseCctF + 385
	11  TrainsIntents                       0x000000010bc2cefb $S13TrainsIntents26RunningStatusIntentHandlerC6handle6intent10completionyAA0cdE0C_yAA0cdE8ResponseCctFTo + 139
	12  Intents                             0x000000011069e371 __50-[INExtensionContext handleIntent:withCompletion:]_block_invoke.199 + 237
	13  Intents                             0x000000011069fb81 __47-[INExtensionContext _deliverIntent:withBlock:]_block_invoke + 94
	14  libdispatch.dylib                   0x000000011196152d _dispatch_call_block_and_release + 12
	15  libdispatch.dylib                   0x0000000111962597 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x0000000111969054 _dispatch_lane_serial_drain + 720
	17  libdispatch.dylib                   0x0000000111969b97 _dispatch_lane_invoke + 401
	18  libdispatch.dylib                   0x00000001119729c6 _dispatch_workloop_worker_thread + 645
	19  libsystem_pthread.dylib             0x0000000111d44fd2 _pthread_wqthread + 980
	20  libsystem_pthread.dylib             0x0000000111d44be9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

## Steps to Reproduce
The way to preproduce is access realm via siri shortcut.

## Version of Realm and Tooling

Realm framework version: 2.10.2

Realm Object Server version: ?

Xcode version: 10.0 beta 5

iOS/OSX version: iOS 12

Dependency manager + version: Cocoapods

**Comment by bmunkholm** [comment]
@kidsid-Ixigo You are not allowed to access a realm object from another thread than the one you obtained it from. Please see the section about threading here: https://realm.io/docs/swift/latest/#threading

**Comment by kidsid-Ixigo** [comment]
@bmunkholm I am not doing any thread-specific things with Realm and its working fine in my main app. Its created on the main thread as usual I believe but accessing it in the same way with Siri Shortcuts throws this error. Now I am wondering that the way Realm instance is created and the way it's used is used is same in main app and Siri shortcut while it works fine with the main app but throwing an error with shortcuts.

**Comment by bmunkholm** [comment]
@kidsid-Ixigo Ok, thanks for the update. The best way to expedite this would be if you could be helpful and try to replicate this in a minimal app so we can start to narrow it down.

**Comment by VojtaStruhar** [comment]
Common practise is, that databases should be accessed on background thread. Realm, however, likes to be called on main thread only. If you call it only on 1-2 places in your app, you can get away with using background threads, but in larger apps not (according to my experience).

So - call realm on main thread only and you should be fine. It solved my problem

**Comment by nirinchev** [comment]
It's not a problem to call Realm from background threads, you just need to make sure to obtain a Realm instance for the background thread, rather than try and access the one you opened on the main thread.

**Comment by jsflax** [comment]
@kidsid-Ixigo do you have a sample code or a sample app to send us? I haven't worked with Siri shortcuts yet, but I suspect you may simply have to allocate another realm instance.

**Comment by leemaguire** [comment]
Closing this issue due to age. If you have any other questions please open a new issue.

Thanks.
