### ISSUE TITLE
Clone copy of Objects (Including recursive models)

### ISSUE THREAD

**Issue by ods2-hamid** [realm/realm-cocoa#5877]
!!! MANDATORY TO FILL OUT !!!

## Goals

- We have multiple nested tables inside parent table. We are unable to copy/clone of a whole object including nested objects.

- We need delete record as well for nested objects. I have done this part, I will share the line of code as well in the bottom to recursive delete nested objects.

## Expected Results

If we clone/copy a parent table object, it should copy/clone all inside nested and inner nested objects as well.

## Actual Results

It only copy/clone the parent table (record) values and put the same record's reference for nested objects.

## Steps to Reproduce

Just create a patent table having reference of child table also child table having reference of inner child table and so on 3/4 times inner child. it will easily generate copy/clone objects.

## Code Sample
- (void)deleteRecusiveObject:(RLMObject *)object {
    RLMObjectSchema *schema = object.objectSchema;
    for (RLMProperty *property in schema.properties) {
        if ([object[property.name] isKindOfClass:[RLMArray class]]) {
            RLMArray *objects = object[property.name];
            for (RLMObject *childObject in objects) {
                [self deleteRecusiveObject:childObject];
            }
        }
        else if ([object[property.name] isKindOfClass:[RLMObject class]]) {
            RLMObject *childObject = object[property.name];
            [self deleteRecusiveObject:childObject];
        }
    }
    
    [FMSDatabase.instance deleteObject:object];
}

## Version of Realm and Tooling

Realm framework version: ?
I am getting all latest updates

Realm Object Server version: ?
Only using in iOS app.

Xcode version: ?
xcode9

iOS/OSX version: ?
ios11

Dependency manager + version: ?
N/A

**Comment by leemaguire** [comment]
Closing this issue due to insufficient information and age. If you have any other questions please open a new issue.

Thanks.
