### ISSUE TITLE
Unable to receive notification on RLMObject with RLMArray property after array member change

### ISSUE THREAD

**Issue by kosyak** [realm/realm-cocoa#5878]
## Goals
Being able to receive object update notifications when object has `RLMArray` property and one of the array members has been changed.

## Expected Results
One of `RLMArray` elements changes - and object containing this `RLMArray` property receives a notification with this property update info.

## Actual Results
Such notification does not get triggered.

## Code Sample
```Swift
class MyElement: RLMObject {
    @objc dynamic var id: Int = 0
    @objc dynamic var value: Int = 0

    override class func primaryKey() -> String? {
        return #keyPath(MyElement.id)
    }
}

class MyModel: RLMObject {
    @objc dynamic var id: Int = 0
    @objc dynamic var value: Int = 0
    @objc dynamic var elements: RLMArray<MyElement> = RLMArray(objectClassName: "MyElement")

    override class func primaryKey() -> String? {
        return #keyPath(MyModel.id)
    }
}

// Setting up

try? RLMRealm.default().transaction {
    RLMRealm.default().addObjects([ MyModel(), MyElement() ] as NSFastEnumeration)
    MyModel.object(forPrimaryKey: 0)?.elements.add(MyElement.object(forPrimaryKey: 0)!)
}

let token = MyModel.object(forPrimaryKey: 0)?.addNotificationBlock { _, change, _ in
    print("Object did update props:", change?.map { $0.name } ?? [])
    // I want to receive `Object did update props: ["elements"]` here
}

// Actual changes

try? RLMRealm.default().transaction {
    let object = MyModel.object(forPrimaryKey: 0)!
    object.value = 1 // object will be notified of this change
    object.elements.firstObject()?.value = 1 // object WILL NOT be notified of this change
}
```

Sample project: https://github.com/kosyak/RealmTest

## Version of Realm and Tooling
```
ProductName:    Mac OS X
ProductVersion: 10.14
BuildVersion:   18A353d

/Applications/Xcode-beta.app/Contents/Developer
Xcode 10.0
Build version 10L221o

/usr/local/bin/pod
1.5.3
Realm (3.7.6)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)


(not in use here)

/usr/bin/git
git version 2.17.1 (Apple Git-112)
```

**Comment by tgoyne** [comment]
This is the intended behavior. The intention was to add the ability to explicitly opt-in to deep change notifications, but that has not been implemented yet.

A moderately awkward workaround would be to instead do `MyModel.objects(where: "id = %@", 0).addNotificationBlock`, as Results notifications do notify when it is a linked object which changed (up to 4 levels deep).

**Comment by kosyak** [comment]
Thanks for clarifying! Currently I'm using the same workaround, it works fine.

Is there an issue about deep change notifications to follow?

Also I'm curious about '4 levels deep' change notifications in Results, is there any information about this functionality in the docs? Does it mean that Results notifications have some kind of deep change notification system already implemented (and it isn't presented in object notifications)?

I guess this issue can be closed now.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-cocoa/issues/3704 is the inverse (excluding certain nested changes on collection notifications), but it's basically the same chunk of work.

We don't really describe what we consider "modifications" to be in the documentation, mostly because it was supposed to be a pretty temporary state of affairs. For collection notifications, the idea is that a row in the collection is marked as modified if *any* value reachable from that row has changed, including over links, but for performance reasons that's capped at a depth of 4 links (i.e. `a.b.c.d.e = 5` reports `a.b` as modified but not `a`).

**Comment by kosyak** [comment]
Got it, thank you.
