### ISSUE TITLE
Can't open db again after encryption

### ISSUE THREAD

**Issue by NosovPavel** [realm/realm-cocoa#5879]
**Questions**:  I'm trying to encrypt existing db but unfortunately after making a copy of existing db with key I can't initialise DB stack again. 

## Goals

Encrypted and working copy of existing db

## Expected Results

I expect that I will open encrypted copy of db and continue using it

## Actual Results
I got only @throw RLMException(@"Cannot migrate Realms that are already open."); when i'm trying to initialise db at the end of provided example

## Code Sample

    let migrationBlock: MigrationBlock = { migration, oldSchemaVersion in

	    if (oldSchemaVersion < kCurrentRealmSchemaVersion) {
	        // Nothing to do!
	        // Realm will automatically detect new properties and removed properties
	        // And will update the schema on disk automatically
	    }
	}

	guard let defaultURL = Realm.Configuration.defaultConfiguration.fileURL else {
	    return
	}

	let defaultParentURL = defaultURL.deletingLastPathComponent()

	let dataBaseNames = "db1";
	    
	let fullName = databaseName + ".realm"
	let url = defaultParentURL.appendingPathComponent(fullName)

	let encDbName = databaseName + "enc" + ".realm"

	let encFileUrl = defaultParentURL.appendingPathComponent(encDbName)

	if !FileManager.fileExists(encDbName) {
	    
	    do {
	        var config = Realm.Configuration.init(fileURL: url, schemaVersion: kCurrentRealmSchemaVersion, migrationBlock: migrationBlock)
	        let realm = try Realm(configuration: config)
	        try realm.writeCopy(toFile: encFileUrl, encryptionKey: getRealmEncryptionKey())
	        
	        FileManager.removeFile(fileUrl: url)
	        
	    } catch let error as NSError {
	        print(#function)
	        print(error)
	    }
	}

	let config = Realm.Configuration.init(fileURL: encFileUrl, encryptionKey: getRealmEncryptionKey(), schemaVersion: kCurrentRealmSchemaVersion, migrationBlock: migrationBlock)
	do {
	    try Realm.performMigration(for: config)
	} catch let error as NSError {
	    print(#function)
	    print(error)
	}

## Version of Realm and Tooling
Realm framework version:  3.7.5
Realm Object Server version: -
Xcode version: 9.4.1 (9F2000)
iOS/OSX version: 11+
Dependency manager + version: Cocoapods 1.5.0

**Comment by leemaguire** [comment]
Closing this issue due to age, if you have any other questions please open a new issue.

Thanks.
