### ISSUE TITLE
any solution for list of objects ???

### ISSUE THREAD

**Issue by M0TRIX** [realm/realm-cocoa#5881]
i'm trying to cast my JSON into my model.

i have list of object in my model how to declare in ream way ?? i need it

```
class person:Object, Mappable{
    
    
    dynamic var firstNameFa:String=""
    dynamic var lastLoginDate:String=""

    dynamic var phone:String=""

    dynamic var id:String=""
    dynamic var identityId:String=""
    dynamic var userAccount:UserAccount?
    dynamic var account:Account?
    dynamic var code:String?
    dynamic var address:Address? // tttt
  var defaultAddressList:List<DefaultAddress>? // this is not i want
 // dynamic var defaultAddressList=[DefaultAddress]() // this is what i want


 func mapping(map: Map) {
        
        firstNameFa <- map["firstNameFa"]
        lastNameFa <- map["lastNameFa"]
        identityId <- map["identityId"]
        phone <- map["phone"]
        email <- map["email"]
        id <- map["id"]
        userAccount <- map["userAccount"]
        address <- map["address"]
        defaultAddressList <- map["defaultAddressList"]

        account <- map["account"]
        code <- map["code"]

    }
 }
```

and i'm casting into my model this way : 

```
let json = try! JSONSerialization.jsonObject(with: content, options: .allowFragments) as! [String:Any]
                    
 let ersonJson =  json["data"] as! AnyObject
 self.psInfo = Mapper<person>().map(JSONObject: ersonJson)!

```

i need that DefaultAddress in my model which can not cast it because of realm limitation of declaring Lists.

what is the soloution

**Comment by tiwariammit** [comment]
Changed **Mappable** protocol to **StaticMappable**

and add initiallization code  
public class func objectForMapping(map: Map) -> BaseMappable? {
        return self.init()
    }

and for array object used 
public struct ListTransform<T: RealmSwift.Object>: TransformType where T: BaseMappable {
    
    public init() { }
    
    public typealias Object = List<T>
    public typealias JSON = Array<Any>
    
    public func transformFromJSON(_ value: Any?) -> List<T>? {
        if let objects = Mapper<T>().mapArray(JSONObject: value) {
            let list = List<T>()
            list.append(objectsIn: objects)
            return list
        }
        return nil
    }

    public func transformToJSON(_ value: Object?) -> JSON? {
        return value?.compactMap{ $0.toJSON() }
    }
}


and fetch as
  var defaultAddress: List< DefaultAddress>?
    
  required convenience init?(map: Map) {
    self.init()
  }
  override func mapping(map: Map) {
    super.mapping(map: map)
    defaultAddress <- (map["defaultAddressList"], ListTransform< DefaultAddress>())
  }


if any problem then comment i will help as i can.
