### ISSUE TITLE
Warnings when using as static library with CP 1.6.0.beta1

### ISSUE THREAD

**Issue by marcelofabri** [realm/realm-cocoa#5886]
## Goals

Use static libraries to reduce the launch time on an app (artsy/eigen#2561).

## Expected Results

RealmSwift would build without any warnings.

## Actual Results

```
<module-includes>:1:1: warning: umbrella header for module 'Realm' does not include header 'RLMMigration_Private.h'
#import "Realm.h"
^
<module-includes>:1:1: warning: umbrella header for module 'Realm' does not include header 'RLMSyncManager_Private.h'
#import "Realm.h"
^
```

## Steps to Reproduce

1. Create a Gemfile:

```ruby
source 'https://rubygems.org'

gem 'cocoapods', '1.6.0.beta.1'
```

2. Run `bundle install`
3. Change your Podfile to use

```ruby
use_frameworks!(false)
use_modular_headers!
```

4. Run `bundle install && bundle exec pod install`
5. Try to build the app

## Version of Realm and Tooling

Realm framework version: ? 3.7.6

Realm Object Server version: ? -

Xcode version: ? 9.4.1

iOS/OSX version: ? 11.4

Dependency manager + version: ? CocoaPods 1.6.0.beta1

**Comment by SquaredTiki** [comment]
@tgoyne I'm still seeing this issue even with the fix in #5890.

**Comment by SquaredTiki** [comment]
My module map looks like the following: 

```swift
module Realm {
    umbrella header "Realm.h"

    export *
    module * { export * }

    explicit module Private {
        header "RLMAccessor.h"
        header "RLMArray_Private.h"
        header "RLMCollection_Private.h"
        header "RLMListBase.h"
        header "RLMObject_Private.h"
        header "RLMObjectBase_Dynamic.h"
        header "RLMObjectBase_Private.h"
        header "RLMObjectSchema_Private.h"
        header "RLMObjectStore.h"
        header "RLMOptionalBase.h"
        header "RLMProperty_Private.h"
        header "RLMRealm_Private.h"
        header "RLMRealmConfiguration_Private.h"
        header "RLMResults_Private.h"
        header "RLMSchema_Private.h"
        header "RLMSyncConfiguration_Private.h"
        header "RLMSyncUtil_Private.h"
    }

    explicit module Dynamic {
        header "RLMRealm_Dynamic.h"
        header "RLMObjectBase_Dynamic.h"
    }
}
```

**Comment by SquaredTiki** [comment]
I think the issue is rather that the two files `RLMMigration_Private.h` and `RLMSyncManager_Private.h` are in the 'Headers' build phase (along with all other headers, within the 'Project' section) but are not included as a header in either the `Private` module, `Dynamic` module or umbrella header `Realm.h` within the module map. Thus the error.

Going through all the other headers I can see that either directly or indirectly they are included. Should `RLMMigration_Private.h` and `RLMSyncManager_Private.h` be in one of those 3 places, and if not, should they be in the 'Headers' build phase?

**Comment by tgoyne** [comment]
#5890 removed `RLMMigration_Private.h` and `RLMSyncManager_Private.h` from the generated xcode project specifically so that they do not get added to the Headers build phase. This has not been included in a release yet, so unless you're manually pointing the `Realm` pod at `master` you'll continue to see the warnings.

**Comment by SquaredTiki** [comment]
Interesting. I pointed the `Realm` pod at master, cleaned the build folder, `pod install`'d and built again, still seeing the error. I'll give it another go.

**Comment by SquaredTiki** [comment]
OK, I've re-generated `Pods.xcodeproj` from scratch and I'm still seeing `RLMMigration_Private.h` and `RLMSyncManager_Private.h` in the Headers build phase. For clarity, this is the line in my Podfile:

```
pod 'RealmSwift', :git => 'git@github.com:realm/realm-cocoa.git', :branch => 'master', :submodules => true  # Change back to version once 3.7.6+1 is released
```

And the build phase I see:

<img width="602" alt="screen shot 2018-08-22 at 22 56 39" src="https://user-images.githubusercontent.com/146159/44493137-cf4f0880-a65e-11e8-8fb2-c940f2e58d4b.png">

Does yours correctly omit `RLMMigration_Private.h` and `RLMSyncManager_Private.h` from the Headers build phase?

Also, apologies for misunderstanding the fix! I didn't realise that the changes in #5890 were for the end goal of removing the headers from the Headers build phase.

**Comment by tgoyne** [comment]
`RLMMigration_Private.h` isn't mentioned in the podspec anywhere and there now aren't any wildcards that match it (only `*.cpp` and `*.{m,mm}`), so I have no idea how it could be showing up in the xcode project if you've deleted Pods.xcodeproj. CocoaPods using the wrong version of the podspec is the only explanation that I can think of. Maybe delete the lockfile too?

**Comment by SquaredTiki** [comment]
Deleted the lock file too and no luck. But I realised the issue, I was only including:

```
pod 'RealmSwift', :git => 'git@github.com:realm/realm-cocoa.git', :branch => 'master', :submodules => true  # Change back to version once 3.7.6+1 is released
```

in the Podfile which is fine normally as `RealmSwift` has a dependency on `Realm` but the `RealmSwift` podspec uses the associated _version_ of the `Realm` pod (i.e. not pointing to `master`).

Adding:

```
pod 'Realm', :git => 'git@github.com:realm/realm-cocoa.git', :branch => 'master', :submodules => true  # Can be removed once RealmSwift pod is versioned again
```

to the Podfile as well resolved the issue.

My apologies for not checking this earlier! 🤦‍♂️
