### ISSUE TITLE
Realm use in iOS extension hangs app

### ISSUE THREAD

**Issue by pankajsoni19** [realm/realm-cocoa#5887]
We are keeping realm file in shared group that we open both from App and notification extension.

iOS extension run time varies greatly and sometimes when we are in between write transaction iOS cancels the thread.

Now user opens the notification > app launches and the realm compaction block runs. As the extension still holds some sort of lock on realm file the entire app hangs.

How will you guys suggest to handle this?

**Comment by leemaguire** [comment]
This is a known issue and we do not have a fix for this. Wrapping writes in a background task fixes one app blocking another app, but that API isn't available in extensions.
