### ISSUE TITLE
RLMSupport.swift compile error under Swift 4.1 and Xcode 9.4

### ISSUE THREAD

**Issue by jeancky** [realm/realm-cocoa#5889]
## Goals

Using Realm-objective-c with RLMSupport.swift under swift 4.1

## Expected Results

no compile error and work fine 

## Actual Results
Swift code fragment which using Realm compile error.

## Code Sample

`for model in banners {`
`//     do some stuff`
`}`

banners is a RLMArray of instances of BannerModel, which defined in Objective-C. The definition like this:
`@interface BannerModel : RLMObject`
`// iid`
`@property NSString* _Nonnull iid;`
`@end`
`RLM_ARRAY_TYPE(BannerModel)`

the compile error:
'RLMArray<AnyObject> & BannerModelProtocol' cannot be used as a type conforming to protocol 'Sequence' because 'Sequence' has static requirements

## Version of Realm and Tooling
Xcode 9.4
Swift 4.1
I have tried:

`pod 'Realm' , '~> 3.6.0'`
`pod 'Realm' , '~> 3.7.0'`

Realm framework version: ?

3.6.0, 3.7.4

Xcode version: ?
Xcode 9.4

iOS/OSX version: ?
iOS 11.0.1

Dependency manager + version: ?

**Comment by tgoyne** [comment]
Please supply a complete repro case for this which does not work. It seems to work fine for me.
