### ISSUE TITLE
How to save multidimensional array in realm swift?

### ISSUE THREAD

**Issue by nooralam6** [realm/realm-cocoa#5892]
!!! MANDATORY TO FILL OUT !!!

## Goals

I want to save multidimensional array in realm swift, the json is:
"multiOperationalHours": [
            [
                {
                    "day": 1,
                    "from": "15:31:02",
                    "endOn": "sameDay",
                    "to": "15:31:03"
                },
                {
                    "day": 2,
                    "from": "15:31:02",
                    "endOn": "sameDay",
                    "to": "15:31:03"
                },
                {
                    "day": 3,
                    "from": "15:31:02",
                    "endOn": "sameDay",
                    "to": "15:31:03"
                },
                {
                    "day": 4,
                    "from": "15:31:02",
                    "endOn": "sameDay",
                    "to": "15:31:03"
                },
                {
                    "day": 5,
                    "from": "15:31:02",
                    "endOn": "sameDay",
                    "to": "15:31:03"
                },
                {
                    "day": 6,
                    "from": "15:31:02",
                    "endOn": "sameDay",
                    "to": "15:31:03"
                },
                {
                    "day": 7,
                    "from": "15:31:02",
                    "endOn": "sameDay",
                    "to": "15:31:03"
                }
            ]
        ],
my model in vague is:
var multiOperationalHours : [[MultiOperationalHours]]?
giving error 
## Expected Results

to have a multidimensional array of objects in realm
## Actual Results

array or nsdata or nsarray is not a realm collection type.
## Steps to Reproduce

try to decode multidimensional array simply 
## Code Sample

@objc dynamic var multiOperationalHours : [[MultiOperationalHours]]?
multiOperationalHours = try values.decode([[MultiOperationalHours]].self, forKey: .multiOperationalHours)

## Version of Realm and Tooling

Realm framework version: 3.7.5

Realm Object Server version: ?

Xcode version: 10 beta

iOS/OSX version: 10.13.5

Dependency manager + version: Cocoapods

**Comment by tgoyne** [comment]
You need an intermediate object which stores an array of the objects:
```
class MyObject: Object {
    let hoursLists = List<MultiOperationalHoursList>()
}
class MultiOperationalHoursList: Object {
    let hours = List<MultiOperationalHours>()
}
class MultiOperationalHours: Object {
    @objc dynamic var day: Int = 0
    // etc.
}
```

**Comment by nooralam6** [comment]
This is how i tried to implement,
class A : Object, Decodable {

———

——

@objc dynamic var defaultOperationalHours : DefaultOperationalHours?

enum CodingKeys: String, CodingKey {

--------

multiOperationalHours = "multiOperationalHours"

--------

}

public required convenience init(from decoder: Decoder) throws {

        self.init()

let values = trydecoder.container(keyedBy: CodingKeys.self)
———
------
try values.decodeIfPresent(MultiHours.self, forKey: .multiOperationalHours) ?? MultiHours
------
}

class MultiHours: Object {

let hoursLists = List<MultiOperationalHoursList>()

}

class MultiOperationalHoursList: Object {

let hours = List<Shift0>()

}

class MultiOperationalHoursM : Object, Decodable {

var shift0 = List<Shift0>()

    var shift1 = List<Shift0>()

    var shift2 = List<Shift0>()

enum CodingKeys: String, CodingKey {
case shift0 = "shift0"
case shift1 = "shift1"
case shift2 = "shift2"
}

public required convenienceinit(from decoder: Decoder) throws {
self.init()
let values = trydecoder.container(keyedBy: CodingKeys.self)
let shif0 = tryvalues.decodeIfPresent([Shift0].self, forKey: .shift0) ?? [Shift0]()
 shift0.append(objectsIn: shif0)
let shif1 = tryvalues.decodeIfPresent([Shift0].self, forKey: .shift1) ?? [Shift0]()
shift1.append(objectsIn: shif1)
let shif2 = tryvalues.decodeIfPresent([Shift0].self, forKey: .shift2) ?? [Shift0]()
shift2.append(objectsIn: shif2)

 }

}

Getting this error

> A.swift:68:44: No ‘decodeIfPresent’ candidates produce the expected contextual result type ’MultiHours?
