### ISSUE TITLE
RealmSwift Swift Compiler Error

### ISSUE THREAD

**Issue by martheli** [realm/realm-cocoa#5893]
## Goals
Add the RealmSwift pod to my brand new Xcode project

## Expected Results
Have RealmSwift available to me in my Xcode project by using `import RealmSwift`

## Actual Results
Build failure with following Swift compiler error:

```
<unknown>:0: error: fatal error encountered while reading from module 'RealmSwift'; please file a bug report with your project and the crash log

*** DESERIALIZATION FAILURE (please include this section in any bug report) ***
top-level value not found
Cross-reference to module 'Realm'
... RLMObjectBase
```

## Steps to Reproduce

1. I ran `pod update` to update my pods.
2. Added `pod 'RealmSwift'` to my podfile.
3. Verified Realm version 3.7.6 was being installed.
4. Added `import RealmSwift` to my project.

## Version of Realm and Tooling

Realm framework version: 3.7.6

Xcode version: 9.4.1

Swift version: 4.1

**Comment by Sajjon** [comment]
@martheli how did you solve this? I am experiencing this for another pod, not Realm.
