### ISSUE TITLE
Failing to initialize Realm -  Invalid mnemonic - Error Code 2

### ISSUE THREAD

**Issue by Abreu0101** [realm/realm-cocoa#5896]
## Expected Results

App should be able to initialize Realm

## Actual Results

Unable to open a realm at path '/var/mobile/Containers/Data/Application/XXXXXXXXXXXXXXXXXXXX/Documents/chat_data.realm': Invalid mnemonic. top_ref[0]: 0, top_ref[1]: 0, mnemonic: 0 0 0 0, fmt[0]: 0, fmt[1]: 0, flags: 0.

## Goals
Understand, why `Invalid mnemonic` error can happen

## Steps to Reproduce

First i was receiving a migration required issue. I added `config.deleteRealmIfMigrationNeeded = true`. After that start receiving this issue (but i see for other users the same error, that doesn't have the `deleteRealmIfMigrationNeeded`. This start happening when users upgrade application).

## Version of Realm and Tooling

Realm framework version: ?
3.7.6

Xcode version: ?
9.4.1

iOS/OSX version: ?
11.3

Dependency manager + version: ?
Cocoapods 1.5.2

**Comment by doddyth** [comment]
Similar crash issue with me, but my issue is forget setup realm configuration and then called `try! Realm().`

Solved by setup realm before any realm initialization.
Ex:
```
Realm.Configuration.defaultConfiguration = createConfig(encryptionKey: encryptionKey)
```

**Comment by leemaguire** [comment]
Closing this issue due to age, if you have any other questions please open a new issue.

Thanks.
