### ISSUE TITLE
Sorting by [SortDescriptor] compile error: incorrect argument label, expected byKeyPath

### ISSUE THREAD

**Issue by rubengarciam** [realm/realm-cocoa#5897]
Sorting alphabetically when a string contains numbers and characters seems to be a well known issue. I.e., when using `.sorted(byKeyPath: 'title', ascending: true)` the output is

```
title #1
title #10
title #2
```
when instead it should be

```
title #1
title #2
title #10
```

When trying to check if using`.sorted(by: [SortDescriptor])`   could fix the issue, I bumped into a compile error. RealmSwift seems to only accept `byKeyPath`? 

## Goals
Filter by multiple properties, as stated in the [RealmSwift documentation](https://realm.io/docs/swift/latest/index.html#sorting)

## Expected Results
Filter a `Result` object by the specified properties

## Actual Results
Compile error:

```Incorrect argument label in call (have'by:'; expected 'byKeyPath:'). Replace 'by' with 'byKeyPath'```

## Steps to Reproduce
Check code sample.

## Code Sample
```
realm.objects(Object.self).sorted(by: [SortDescriptor(byKeyPath: "property1", ascending: false),
                                                       SortDescriptor(byKeyPath: "property2", ascending: false)])
```

## Version of Realm and Tooling
RealmSift 3.7.6
Xcode version: 10.0b6
iOS/OSX version: irrelevant, compile error

**Comment by knine79** [comment]
I met a same error when using `.sorted(by areInIncreasingOrder: (T, T) throws -> Bool)`.

**Comment by leemaguire** [comment]
This is not an issue in the latest version of Realm. Closing.
