### ISSUE TITLE
Completely delete an object and its schema

### ISSUE THREAD

**Issue by borut-t** [realm/realm-cocoa#5899]
## Goals
When deleting object class from the app and its objects from the database I would expect object schema is deleted from the db schema also.

I've also tried setting `shouldCompactOnLaunch` to true and not returning deleted class in `objectTypes` list.

## Expected Results
Object's db schema removed from the database.

## Actual Results
Object's db schema still present in the database.

## Steps to Reproduce
1. Create class A and save it to the database.
2. Remove all objects of type A from the database and remove class A completely from the app.
3. Observe `Realm Studio` and class A schema is still present.

## Code Sample
Nothing special to show here.

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

/Applications/Xcode.app/Contents/Developer
Xcode 9.4.1
Build version 9F2000

/usr/local/bin/pod
1.5.3
Realm (3.0.0)
RealmSwift (3.0.0)
RealmSwift (= 3.0.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)


(not in use here)

/usr/bin/git
git version 2.15.2 (Apple Git-101.1)
```

**Comment by tgoyne** [comment]
Completely removing the data for a class is done by calling [`deleteData(forType:)`](https://realm.io/docs/swift/latest/api/Structs/Migration.html#/s:10RealmSwift9MigrationV10deleteDataSbSS7forType_tF) within a migration block. We do not automatically remove the tables for object types which aren't currently used to support opening Realm files with schema subsets and to make it harder to accidentally lose data.
