### ISSUE TITLE
mmap() failed: Cannot allocate memory size: 603979776 offset: 0

### ISSUE THREAD

**Issue by LucyJeong** [realm/realm-cocoa#5901]
## Bugs
When file size was grown almost 1 GB, data can't save and return **this message mmap() failed: Cannot allocate memory size: 603979776 offset: 0**  I tried two way `shouldCompactOnLaunch` strategy and wrapping reads in `autoreleasepool`. But, it can't solve that problem. 

## Goals
I'd like to save some data which are an image created by user and text attributes into realm file.
(I'm using only realm database)

## Expected Results
I expect that data can save into Realm file. 

## Actual Results
I can't save data and return that error **mmap() failed: Cannot allocate memory size: 603979776 offset: 0**
This message is changed depend on iPhone device. I think it happen when file size is almost 1 GB. 
- iPhone 5S : mmap() failed: Cannot allocate memory size: 603979776 offset: 0
- iPhone 7 plus : mmap() failed: Cannot allocate memory size: 903979776 offset: 0

## Steps to Reproduce
When I try to save an Image user created and several text attribute information, if that file size is almost 1GB,  Realm file can't save that data and return "map() failed: Cannot allocate memory size: 603979776 offset: 0" This message.

## Code Sample
```swift
//AppDelegate.swift 
DispatchQueue.global().async {
            autoreleasepool {
                var realmConfiguration = Realm.Configuration(shouldCompactOnLaunch: { totalBytes, usedBytes in
                    
                    let oneHundredMB = 100 * 1024 * 1024
                    return (totalBytes > oneHundredMB) && (Double(usedBytes) / Double(totalBytes)) < 0.5
                })                    
                    realmConfiguration.schemaVersion = SQRealmSchemeVersion
                    realmConfiguration.migrationBlock = SQRealmMigrator.realmMigrationBlock
                    realmConfiguration.fileURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: SQExtensionAppGroupIdentifier)!.appendingPathComponent("spark_quote.realm")
                do {
                    _ = try Realm(configuration: realmConfiguration)
                } catch {
                    print(error)
                }
                    Realm.Configuration.defaultConfiguration = realmConfiguration
            }
```

This code is problem code.
```swift
DispatchQueue.global().async {
                        autoreleasepool {
                            do {
                                var quote : SQQuote!

                                var configuration: Realm.Configuration = Realm.Configuration()
                                configuration.schemaVersion = SQRealmSchemeVersion
                                configuration.migrationBlock = SQRealmMigrator.realmMigrationBlock
                                configuration.fileURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: SQExtensionAppGroupIdentifier)!.appendingPathComponent("spark_quote.realm")
                                Realm.Configuration.defaultConfiguration = configuration
                                let realm = try Realm(configuration: configuration)

                                if self.currentQuoteType == .myPhoto && self.selectedMyPhotoImage != #imageLiteral(resourceName: "bg_myphoto_mainphoto") {
                                    quote = SQQuote(text: text, backgroundImage: nil, quoteImage: quoteImage, saveOrigianlImage: true)
                                }else {
                                    quote = SQQuote(text: text, backgroundImage: nil, quoteImage: quoteImage, saveOrigianlImage: false)
                                }
                                
                                **realm.beginWrite()
                                realm.add(quote)
                                try realm.commitWrite()**
                            
                            }
                            catch let error as NSError {
                                self.presentErrorAlert(message: "Error occupied. \(error.localizedDescription)")
                            }
                        }
```

## Version of Realm and Tooling
Realm framework version: 3.7.6

Xcode version: 9.4.1 (9F2000)

iOS/OSX version: iOS 10.2.1 and 11.4.1

**Comment by HonzaMac** [comment]
We had exact same issue. For us, we found, that we did not delete some relations.
```
...
let projects List<Project>
...
```
When we delete entity, it does not clean List data from Realm, they keep to be there, until we hit Cannot allocate memory limit. 
See [StackOverFlow](https://stackoverflow.com/a/29094983) for actual memory limits per device.

**Comment by imhafeez** [comment]
How to fix this?

**Comment by LucyJeong** [comment]
@HonzaMac Thank you for reply. In your case, when you delete object, it didn't delete all clearly. So this problem came from that. is it right? 

@imhafeez I didn't fix yet 😢 But, I got some hint. Some time, this problem is happened and some time this problem is not happened. I think it's depend on device memory condition. So I will try to change realm architecture, if device memory condition is okay. 

I'm not sure that is solution. If it work, I will comment about it in here.

**Comment by imhafeez** [comment]
@LucyJeong  Please update then. Because it is effecting our customers with random crashes. 
It didn't happen on launch. mostly it happen while using the App
Thanks

**Comment by HonzaMac** [comment]
We did several fixes, one I already mention (we introduced cascade delete for Realm)
Second is to use compactOnLaunch option when instantiating Realm configuration. (if you do a lot deletes & inserts, Realm keeps old objects in DB even if there is no reference to them)
Third option would be for us to make sure that every operation is in autorelease block. (not implemented yet)

**Comment by LucyJeong** [comment]
@HonzaMac Thank you for comments :) I guess I can do only three way you mentioned to solve for this problem. I tried to same way. thanks :)
