### ISSUE TITLE
find_first(realm::StringData, unsigned long, unsigned long) const + 200

### ISSUE THREAD

**Issue by sanchitgarg1909** [realm/realm-cocoa#5912]
For the past 2 months, we are observing a lot of crashes in Fabric through Realm. These crashes are not reproducible by us, but are affecting a lot of real users. I've attached some images from our Fabric Dashboard where you will see a lot of different Realm crashes. Additionally, I have attached the stack trace of the top most crash. It is happening in different areas of code but root cause remains same. I'm unable to find anything on the internet or in your docs related to this issue. Please help me find a solution.

## Goals
No crashes while using realm.

## Expected Results
Realm queries should not crash.

## Actual Results
For real users, Realm crashes while performing queries

## Steps to Reproduce
Not able to reproduce.

## Code Sample

The queries in function chooseLessonsForHome()

        let updatedLessons = RealmBaseUtils.getObjects(LessonList.self, predicate: NSPredicate(format: "completionStatus == 2 AND hasVideo == false"), sortKey: "submittedOn", isAscending: true)
        
        let freeQbankLessons = RealmBaseUtils.getObjects(LessonList.self, predicate: NSPredicate(format: "completionStatus != 2 AND isPaid == false AND isComingSoon == false AND hasVideo == false"), sortKey: "masterOrder", isAscending: true)

        let freeVideoLessons = RealmBaseUtils.getObjects(LessonList.self, predicate: NSPredicate(format: "completionStatus != 2 AND isPaid == false AND isComingSoon == false AND hasVideo == true"), sortKey: "masterOrder", isAscending: true)
        
        let paidQbankLessons = RealmBaseUtils.getObjects(LessonList.self, predicate: NSPredicate(format: "completionStatus != 2 AND isPaid == true AND isComingSoon == false AND hasVideo == false"), sortKey: "masterOrder", isAscending: true)

        let paidVideoLessons = RealmBaseUtils.getObjects(LessonList.self, predicate: NSPredicate(format: "completionStatus != 2 AND isPaid == true AND isComingSoon == false AND hasVideo == true"), sortKey: "masterOrder", isAscending: true)

Our custom functions to get objects 

    class func getObjects<R: Object>(_ entityClass : R.Type, predicate: NSPredicate? = nil, sortKey: String? = nil, isAscending: Bool = true) -> Results<R> {
            var objects = realmInstance().objects(entityClass)
            if predicate != nil {
                objects = objects.filter(predicate!)
            }
            if sortKey != nil {
                objects = objects.sorted(byKeyPath: sortKey!, ascending: isAscending)
            }
            return objects
    }
    
    class func getFirstObject<R: Object>(_ entityClass : R.Type, predicate: NSPredicate? = nil, sortKey: String? = nil, isAscending: Bool = true) -> R? {
        var objects = realmInstance().objects(entityClass) as Results<R>
        if predicate != nil {
            objects = objects.filter(predicate!)
        }
        if sortKey != nil {
            objects = objects.sorted(byKeyPath: sortKey!, ascending: isAscending)
        }
        return objects.first
    }
    
    class func getObject<R: Object>(_ entityClass : R.Type, primaryKey: String) -> R? {
        return realmInstance().object(ofType: entityClass, forPrimaryKey: primaryKey as AnyObject)
    }

## Version of Realm and Tooling

Realm framework version: 3.7.6

Xcode version: 9.4.1

iOS/OSX version: iOS 11

Dependency manager + version: Cocoapods 1.5.0
<img width="1117" alt="screen shot 2018-09-12 at 1 18 59 pm" src="https://user-images.githubusercontent.com/15670158/45416695-25cbc780-b69e-11e8-8a30-ae01ce3d13d6.png">
<img width="645" alt="screen shot 2018-09-12 at 1 19 37 pm" src="https://user-images.githubusercontent.com/15670158/45416696-25cbc780-b69e-11e8-8979-bcd7c8781d63.png">
<img width="1072" alt="screen shot 2018-09-12 at 1 20 24 pm" src="https://user-images.githubusercontent.com/15670158/45416697-26645e00-b69e-11e8-9770-8337aa21a729.png">
<img width="1073" alt="screen shot 2018-09-12 at 1 20 42 pm" src="https://user-images.githubusercontent.com/15670158/45416698-26645e00-b69e-11e8-957d-d6a07f56ce38.png">

**Comment by tgoyne** [comment]
All of the stacktraces shown are in the first place where we touch the file on disk for the given operation. This is usually due to NSFileProtection: if the data protection capability is enabled for your app, the OS revokes access to the file while the device is locked (but only on an actual device with a pin set), and trying to read from it will fail. Is it possible that this is what you're hitting?

**Comment by sanchitgarg1909** [comment]
We have the data protection capability enabled. Should we try disabling it?

**Comment by tgoyne** [comment]
Repro steps would be something like: install app on device with PIN set, kick off some operation which performs i/o after a delay, immediately lock device. It may take several tries to actually trigger the problem, and as the crash happens while the device is locked the crash may not actually be noticeable.

Potential solutions are:

1. Disable the data protection capability entirely
2. [Disable NSFileProtection for just the Realm files](https://realm.io/docs/swift/latest/#using-realm-with-background-app-refresh) (or set it to `NSFileProtectionCompleteUntilFirstUserAuthentication`).
3. Listen for `UIApplicationProtectedDataWillBecomeUnavailable` notifications and somehow ensure that you don't touch the Realm file until you receive the corresponding WillBecomeAvailable notification.

**Comment by sanchitgarg1909** [comment]
Thank you for the repro steps. I was able to simulate the crashes on my device. However, the exception still occurs even after disabling the Data protection capability entirely. PFA the crash which I see after disabling data protection. Also, this exception is different than "find_first" exception. One last question, is there a way to catch these errors rather than crashing the app?

<img width="1071" alt="screen shot 2018-09-14 at 5 25 33 pm" src="https://user-images.githubusercontent.com/15670158/45548808-441ef800-b843-11e8-80bc-13bb9bf60cb1.png">

<img width="1071" alt="screen shot 2018-09-14 at 5 27 02 pm" src="https://user-images.githubusercontent.com/15670158/45548895-7deffe80-b843-11e8-9278-b0854eb96f7a.png">

**Comment by sanchitgarg1909** [comment]
@tgoyne Hi, can you please look into this issue? It is still not solved.

**Comment by leemaguire** [comment]
@sanchitgarg1909 please update to the latest version of Realm. I will now close this issue, if you have any other questions please open a new issue.

Thanks.
