### ISSUE TITLE
How can I find an object with support for case insensitive forPrimaryKey ?

### ISSUE THREAD

**Issue by sedwo** [realm/realm-cocoa#5913]
The uuid strings in my Realm DB fluctuate with either being uppercase or lowercase.

This creates an issue when I want to find `.object(ofType: T.self, forPrimaryKey: withID)`, because `withID` can be:

> BCB51DF3-0ECB-4C7E-8CB2-AE49E8307D15

or

> bcb51df3-0ecb-4c7e-8cb2-ae49e8307d15

Is there a simple way to have realm be case insensitive in such matters?

**Comment by tgoyne** [comment]
Realm does not support case-insensitive primary keys. You should convert your strings to a consistent case.
