### ISSUE TITLE
Does filtering realm objects on main thread frequently cause massive memory growing?

### ISSUE THREAD

**Issue by KenShih522** [realm/realm-cocoa#5916]
## Code Sample

```
class TestObject: Object {

    @objc dynamic var id: String = ""   

}
```

in my view controller
```
override func viewDidLoad() {

    super.viewDidLoad()

    self.timer = Timer.scheduledTimer(timeInterval: 0.03, target: self, selector: #selector(timerTask), userInfo: nil, repeats: true)

}

@objc func timerTask() {
        
    DispatchQueue.main.async {
                        
        let realm = try! Realm()
            
        realm.objects(TestObject.self).filter("id = '123456'").first

    }
        
}
```

## Version of Realm and Tooling

Realm framework version: 3.8.0

Xcode version: 9.4.1

iOSversion: 11.4

**Comment by tgoyne** [comment]
Your dispatch block allocates some autoreleased memory each time. By default, GCD only drains its autorelease pool when the queue is empty, which will probably never be the case with a timer interval of `.03`. You can either create your own dispatch queue with `DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL` to ask GCD to drain the autorelease pool after every work item (which requires iOS 10), or surround the contents of the dispatch block with `autoreleasepool {}` to explicitly clean up all autoreleased objects before returning.

**Comment by KenShih522** [comment]
Thanks for your response.  
In my ongoing project, I create realm objects on the main thread and need to access them later.         
Since realm objects can't be accessed on a different thread, I have to dispatch those call to the main thread.  Consequently, even though I wrap my contents by `autoreleasepool {}`, the issue seems still there.

**Comment by trungnguyen1791** [comment]
@KenShih522 
Hi,
Did you find a solution yet?

**Comment by trungnguyen1791** [comment]
@KenShih522 Did you found a solution yet? I have no idea but without the filter(), the memory seems normal :(
