### ISSUE TITLE
Decouple sync-related code to a new package

### ISSUE THREAD

**Issue by goa** [realm/realm-cocoa#5918]
**Feature Request**:

Could all the sync-related code be decoupled from the RealmSwift / Realm libraries?

I am only using the local Realm database (as I suspect many people do) and the all the sync-related code is not required. Besides the extra binary size (which I imagine is not that much), there is an impact on the app's start-up time. 

Using the Instruments `Initializer Calls` tool with my app, Realm Obj-C++ classes are by far the ones taking up the most time to initialise (after the Swift system classes) compared to all other libraries. On that list of Realm classes, sync-related classes come up near the top of the slow-to-initialize code. I am talking about classes such as `RLMSyncPermission`, `RLMSyncSessions` and others.

Of course the delay is not catastrophic, but since I don't really need to sync with a Realm Object Server, I would love to be able to get rid of all those.

Please note I am only using static libraries (Realm as well).

## Version of Realm and Tooling

Realm framework version: 3.9.0

I get roughly the same results on Xcode 9 / iOS 11 as well as Xcode 10 / iOS 12.0 on real devices and on simulators.

Dependency manager + version: Cocoapods 1.5.3 (with `use_modular_headers!`)

**Comment by bmunkholm** [comment]
@goa Since you did measure this, could you be a bit more concrete on the benefits of doing this work? How much time could be saved?

**Comment by goa** [comment]
@bmunkholm I guess the best way to measure that consistently would be to compare a lean version of Realm without the sync features to the current one. 

I don't know if it would be helpful for you (since you can get the traces yourself) but I can provide my Instruments traces from the `Initializer Calls` instrument, that show that after system libraries, the Realm C++ libraries are the slowest ones to initialize by far (when measuring the duration of their Static Initializer Calls).

Of course the actual initialisation duration differs for each device, but you will see that they are consistently at the top of the list with a great

**Comment by tgoyne** [comment]
I don't think there's any good reason for any of the sync functionality to have an impact on the startup time when it isn't being used.

**Comment by tgoyne** [comment]
On my ipad mini 2, the Static Initializer Calls instrument reports that the Realm library as a whole takes 36ms to initialize, of which a bit under 5ms is sync-related things. It's been a while since we've taken a pass at speeding up initialization so there's probably some room for improvement, but the sync functionality doesn't appear to be a large portion of the initialization time.

**Comment by jsflax** [comment]
Closing this as a lot of time has passed on there are no plans to separate these packages.
