### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/chenxihang/Desktop/IOSBCS/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by Hanrovey** [realm/realm-cocoa#5920]
Error message：
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/chenxihang/Desktop/IOSBCS/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64.swiftmodule

build environment：
Xcode Version 10.0 (10A255)

**Comment by Hanrovey** [comment]
3.9.0 Release notes (2018-09-10)
=============================================================

### Enhancements

* Expose RLMSyncUser.refreshToken publicly so that it can be used for custom
  HTTP requests to Realm Object Server.
* Add RLMSyncSession.connectionState, which reports whether the session is
  currently connected to the Realm Object Server or if it is offline.
* Add `-suspend` and `-resume` methods to `RLMSyncSession` to enable manually
  pausing data synchronization.
* Add support for limiting the number of objects matched by a query-based sync
  subscription. This requires a server running ROS 3.10.1 or newer.

**Comment by prsolucoes** [comment]
Any solution?

**Comment by tgoyne** [comment]
As with every time a new version of Xcode comes out, you need to either build from source with the new version, or wait a day or two for an official release built with the new version.

**Comment by prsolucoes** [comment]
Ok. Thanks anyway for the answer. We are waiting.

**Comment by mariedm** [comment]
I have the same issue but updated my pods and the last version 3.10.0 is supposed to work with Xcode 10 right?

**Comment by pjcau** [comment]
Me too, I have the same issue.

**Comment by rpaszniuk** [comment]
I have the same issue too!

**Comment by tgoyne** [comment]
If you're seeing this with CocoaPods, you just need to clean the build folder and rebuild the entire workspace. If you're seeing it with a manual installation, you need to install the swift 4.2 framework from 3.10 rather than the swift 4.1 framework.

**Comment by mariedm** [comment]
I already did that but it didn't work. I installed manually instead and now it's working.

**Comment by rpaszniuk** [comment]
The same for me! I installed manually and now it is working.

**Comment by cbigas-cgi** [comment]
Hello @mariedm , @rpaszniuk , 
When you said " I installed manually and now it's working".
How you install manually please ?

**Comment by mariedm** [comment]
@cbigas-cgi you need to download the zip file [here](https://realm.io/docs/swift/latest/) then follow the instructions under Installation > Dynamic framework.

**Comment by cbigas-cgi** [comment]
I didn't understand that. It's finally easy :) 
Thank you.

**Comment by invisible66** [comment]
Any solution?

**Comment by cbigas-cgi** [comment]
Like @mariedm said. 
Just follow the manually installation of the new version of RealmFramework.
https://realm.io/docs/swift/latest/
(Dynamic Framework)

It's work for me

**Comment by invisible66** [comment]
@cbigas-cgi Thanks 👍

**Comment by MEGAMES** [comment]
upgraded to 10.2. and followed instructions for manual install. 
still getting this error: 
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

all work grinds to a halt.

any fixes or suggestions?
