### ISSUE TITLE
Implicitly unwrapped relationships using Swift 4 and Xcode 10

### ISSUE THREAD

**Issue by mohammdsss1** [realm/realm-cocoa#5921]
## Goals
Able to use force unwrapped properties on Xcode 10

## Expected Results
The app should start without any crash

## Actual Results
The app crashes with an exception: 
The `The Person.car property must be marked as being optional.'

## Steps to Reproduce
Declare Object properties as force unwrapped  

## Code Sample
```
This is a sample code which alike the actual one I use to avoid unnecessary complex code.

class Car: Object {
  @objc dynamic var id = 0
}
```

```
class Person: Object {
  @objc dynamic var tmpID = 0
  @objc dynamic var car: Car!
}
```

## Version of Realm and Tooling
Realm framework version: ?
2.10.2

Realm Object Server version: ?
NA

Xcode version: ?
10

iOS/OSX version: ?
iOS 12

Dependency manager + version: ?
CocoaPods

Note: This was working fine until I update to Xcode 10 last night!

**Comment by tgoyne** [comment]
We have some tests for this that work fine with Xcode 10 compiling in all of Swift 3, Swift 4, and Swift 4.2 modes, so more detail is needed.

**Comment by mohammdsss1** [comment]
@tgoyne thanks for the response, 
I have to mention that the crash is happening while instantiating the first Realm instance in my app.
 
I made a separate project with the same Realm models that crashed to mimic the crash behavior, however, its working fine! but it stills crash on the original project.

I suppose there is something else I don't know? how can I reproduce then?
I attached the sample project (not the original) in case you want to have a look at it.

[RealmForce.zip](https://github.com/realm/realm-cocoa/files/2395984/RealmForce.zip)

**Comment by mohammdsss1** [comment]
I also discovered this weird thing, the property called `sale` in both projects for `OpenTab` class is evaluated differently as in both images below.

This screenshot is from the original project (triggered by the excption) where the property is treated as non optional because `property.optional` is returning `<nil>`. Which resulted in triggering the exception as in the image since it will be non optional.

<img width="1440" alt="original project" src="https://user-images.githubusercontent.com/7831855/45749468-6bdfd880-bc14-11e8-9279-b2054be11f5c.png">


This screenshot is from the sample project I sent earlier, however, the property is evaluated properly and returned `YES` whcih means its optional!

<img width="1440" alt="sample project" src="https://user-images.githubusercontent.com/7831855/45749038-1c4cdd00-bc13-11e8-8637-14543e69c39e.png">

**Comment by mohammdsss1** [comment]
New input: be noted that the origin project is using Swift 4.1, meanwhile the sample is using 4.2, however, nothing changed when I upgraded to Swift 4.2 on the original project.

**Comment by tgoyne** [comment]
There's a wide variety of project settings which could potentially be influencing this. If you share the pbxproj file from the thing that exhibits problems I could check what's different there from the attempt at reproducing it.

**Comment by mohammdsss1** [comment]
@tgoyne Thanks a lot for keeping an eye on this issue,
Can I share the file with you through your email?

**Comment by tgoyne** [comment]
You can email anything which you do not want shared publicly to `tg@realm.io`.

**Comment by mohammdsss1** [comment]
Sent to you @tgoyne, kindly check your email 👍

**Comment by tgoyne** [comment]
The project file has `SWIFT_VERSION` set to 4.0 rather than 4.2, but otherwise everything seems to match the repro attempt. I tried building each combination of RealmSwift and the application as Swift 3, 4, and 4.2 to check if it was maybe something related to compiling the framework as a different version from the application, but all 9 combinations seemed to work fine.

As I understand it, with Xcode 10 Implicitly-unwrapped Optionals are no longer a distinct type from normal Optionals and should just show up as the latter in reflection. Maybe you could try stepping through `ObjectUtil.getOptionalProperties()` for the type that's causing problems? The IUO property should be hitting the `mirror.displayStyle == .optional` case and setting `properties[name] = NSNull()`. Maybe `displayStyle` is something else for some reason?

**Comment by mohammdsss1** [comment]
Hey @tgoyne,

Finally, the problem solved, I didn't pay attention to Xcode 10 console telling me that it unable to find field metadata for the type X as in the image below:

<img width="1169" alt="screen shot 2018-09-21 at 16 32 14" src="https://user-images.githubusercontent.com/7831855/45884648-20b4f980-bdbd-11e8-8440-ec76cf2a73bf.png">


I searched for that error and found this on [stackoverflow](https://stackoverflow.com/questions/52392719/string-interpolation-of-an-enum-produces-unknown-string) 

The "Reflection Metadata Level" was set to "None" so I set it to "All" and the exception didn't trigger again!
I think when it was set to "None", there was some hidden info that needed by Realm in order to evaluate the properties correctly.

So I am closing the issue, thanks again @tgoyne

**Comment by tgoyne** [comment]
Good to hear that you got it working!
