### ISSUE TITLE
Crash when create RLMArray

### ISSUE THREAD

**Issue by quba88** [realm/realm-cocoa#5922]
## Goals
Create RLMArray of subclasses RLMObject in Swift

## Actual Results

After run project Realm throw exception

Terminating app due to uncaught exception 'RLMException', reason: 'Property 'array' is declared as 'id', which is not a supported RLMObject property type. All properties must be primitives, NSString, NSDate, NSData, NSNumber, RLMArray, RLMLinkingObjects, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information.'

## Steps to Reproduce
In subclass of RLMObject create RLMArray of subclasses RLMObject, run project

## Code Sample

```
class Class: RLMObject {

    @objc dynamic var array = RLMArray(objectClassName: Class2.className())

    override init() {
        super.init()
    }
}

class Class2: RLMObject {
@objc dynamic var number: Int = 0
    override init() {
        super.init()
    }
}
```

## Version of Realm and Tooling

Realm framework version: 0.94

Xcode version: 9.4.1
iOS/OSX version:  11
Swift version: 3.3.2

**Comment by leemaguire** [comment]
Closing this issue due to age, if you have any other questions please open a new issue.

Thanks.
