### ISSUE TITLE
Realm save an empty object rather than object I passed.

### ISSUE THREAD

**Issue by emagrorrim** [realm/realm-cocoa#5926]
I met a problem in realm-cocoa 2.8.0(in 2.7.0 it works good) which is when I want to save an object into the realm file, I saw an empty object with default value is saved into the realm rather than the object I created(even the primary key is different.)
Eg.
```swift
class XXXRealmObject: RLMObject {
  @objc dynamic var id: String = UUID().uuidString.lowercased()
  @objc dynamic var name: String = ""
  
  @objc init(name: String) {
    self.name = name
    super.init()
  }
  
  @objc override init() {
    super.init()
  }
  
  override class func primaryKey() -> String {
    return "id"
  }
}

let obj = XXXRealmObject(name: "jojo")
let realm = try! RLMRealm(configuration: .default())
try? realm.transaction {
    *breakpoint*
    realm.addOrUpdate(object)
}
```
I add a before `realm.addOrUpdate(object)` and print the object, it show correct object, but after `realm.addOrUpdate(object)` get executed, in realm file, I can only see an object 
```
{
    id: 169e6bc2-9b34-44ae-8ac3-70e6b9145adc,
    name: ""
}
```
and the id is also different from what I saw in break point. It looks like Realm create an object rather use the object I passed in. I am asking for some help here for the internal logic is unclear. 

So what will cause realm create an empty object(maybe default value?) rather than save the object I passed. I just want to get some possible reasons here.

## Expected Results
Object should be saved into realm file with the value I want.

## Actual Results
A new object with empty default value is saved to the realm.

## Version of Realm and Tooling
Realm framework version: 2.8.0

Realm Object Server version: -

Xcode version: all versions

iOS/OSX version: all versions

Dependency manager + version: Cocoapods v1.5.3

**Comment by tgoyne** [comment]
I tried running the following code using Xcode 10 and Realm 2.8.0:

```swift
class XXXRealmObject: RLMObject {
    @objc dynamic var id: String = UUID().uuidString.lowercased()
    @objc dynamic var name: String = ""

    @objc init(name: String) {
        self.name = name
        super.init()
    }

    @objc override init() {
        super.init()
    }

    override class func primaryKey() -> String {
        return "id"
    }
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
        let obj = XXXRealmObject(name: "jojo")
        let realm = try! RLMRealm(configuration: .default())
        try? realm.transaction {
            print("\(obj)")
            realm.addOrUpdate(obj)
            print("\(obj)")
        }
        return true
    }
}
```

This printed the expected result:
```
XXXRealmObject {
	id = 60a2e186-f6f8-4d92-a680-1ab4c735dc04;
	name = jojo;
}
XXXRealmObject {
	id = 60a2e186-f6f8-4d92-a680-1ab4c735dc04;
	name = jojo;
}
RLMResults <0x7fcd9ac1ea40> (
	[0] XXXRealmObject {
		id = 60a2e186-f6f8-4d92-a680-1ab4c735dc04;
		name = jojo;
	}
)
```

**Comment by emagrorrim** [comment]
@tgoyne Thanks for replying, I also try a lot in other projects, they all working good, so I believe the problem may be caused by our project, but I saw https://github.com/realm/realm-cocoa/issues/5446, it may be related to this issue, so this is not a problem just we have.

Here, I  am wondering if we some logic when we call `create`, `createOrUpdate`, ... like 
```
if (condition) {
    // return empty default object
} else {
    // create object in realm
}
```
if so, what is that `condition`, one hint is this happened from 2.8.0. before that, everything going really good.

**Comment by emagrorrim** [comment]
I think I got it, in my project, we have a category for `NSObject` which include a method called `objectForKey`, and in `Realm`'s src, when we read value from `RLMObject`, we check if it can response to `objectForKey`, normally it should return false and keep executing following code to get the real value, but in my project, the code will return nil because it's not a dictionary.

So will close this
