### ISSUE TITLE
Error when implementing Hashable in Xcode 10

### ISSUE THREAD

**Issue by NCrouther** [realm/realm-cocoa#5927]
## Goals
My entity classes all implement Hashable so that I can store them properly in collections.  I use my _id field as the only component of the hash since it uniquely identifies each instance.  Under Xcode 9.X, this entailed overriding hashValue.  After the upgrade to Xcode 10, Xcode displays a warning that 'hash' should be overridden rather than 'hashValue':

> Override of 'NSObject.hashValue' is deprecated; override 'NSObject.hash' to get consistent hashing behavior

When I try to do so, I get 2 compiler errors:

> Overriding non-open instance method outside of its defining module
> Overriding declarations in extensions is not supported

It looks like it might be due to a collision with the "hash" function in RLMObjectBase.mm since if I rename the function, these errors go away (but then the function doesn't fulfill the Hashable protocol any more).

## Code Sample

Old Code (raises a deprecation warning under Xcode 10):

    public override var hashValue: Int {
        return _id.hashValue
    }

Attempted New Code (raises errors under Xcode 10):

    public func hash(into hasher: inout Hasher) {
        hasher.combine(_id)
    }

## Version of Realm and Tooling

Realm framework version: 3.7.4

Xcode version: 10

Dependency manager + version: Carthage

**Comment by tgoyne** [comment]
You have to override the property named `hash`, not the function named `hash(into:)`. The only change required is renaming `hashValue` to `hash`.

**Comment by phoney** [comment]
This appears to work. It still uses hashValue, but there's no warning. Is it only required to override hash if there's no primaryKey?

    override var hash: Int {
        return id.hashValue
    }
