### ISSUE TITLE
After migrate Swift to 4.2 error happen

### ISSUE THREAD

**Issue by Thuran** [realm/realm-cocoa#5933]
After I migrated Swift 4 to 4.2, errors began to occur both in the run of a select and in the time of adding something in the database.

![screen shot 2018-09-26 at 11 03 03 am](https://user-images.githubusercontent.com/19709285/46085153-c11f6b00-c17b-11e8-8b72-1b6aae9a4b8b.png)
![screen shot 2018-09-26 at 10 13 37 am](https://user-images.githubusercontent.com/19709285/46085163-c4b2f200-c17b-11e8-8457-b2caafabeb6a.png)
![screen shot 2018-09-26 at 10 11 47 am](https://user-images.githubusercontent.com/19709285/46085167-c5e41f00-c17b-11e8-9584-c8e127ce6cfc.png)
![screen shot 2018-09-26 at 10 13 54 am](https://user-images.githubusercontent.com/19709285/46085169-c7ade280-c17b-11e8-9318-afdff3e8850a.png)

**Comment by tgoyne** [comment]
Looks like the same issue as https://github.com/realm/realm-cocoa/issues/5923. The problem there turned out to be a non-`@objc dynamic` optional property which previously was ignored and now is being misdetected.

**Comment by Thuran** [comment]
Thanks @tgoyne, my problem was solved, I had a var whitout @objc dynamic that shouldn't be read by Realm, it must just be an object property. To solve that I added this property in ignoredProperties function from Realm and this worked flawlessly
`
override public static func ignoredProperties() -> [String] {
        return ["varName"]
}
`
