### ISSUE TITLE
RLMResults returns <invalid NS/CF object>

### ISSUE THREAD

**Issue by godyolops** [realm/realm-cocoa#5935]
## Goals

To read and print the data in realm obj-c
## Expected Results

 Dogs {
   accessToken: "123",
   msgApiUrl: "123",
  apiKey: "123",
 appName = "123";
}
## Actual Results

RLMResults returns <invalid NS/CF object>

![screen shot 2018-09-27 at 9 57 39 pm](https://user-images.githubusercontent.com/43644809/46150995-70edf900-c2a0-11e8-88d7-b7ee9751edcd.png)

## Steps to Reproduce

I have a react-native app and I installed a Realm Framework in obj-c (native side)
and open and copy the bundledfiles in javascript side. 
## Code Sample

 ```
 Dogs *data = [[Dogs alloc] init];
  data.accessToken = @"123";
  data.apiKey = @"123";
  data.appName = @"123";
  data.msgApiUrl = @"123";
  
  [realm beginWriteTransaction];
  [realm addObject:data];
  [realm commitWriteTransaction];
  
  // Read some data from the bundled Realm
  RLMResults<Dogs *> *mantra = [Dogs allObjects];
  
  NSLog(@"==mantra== %@", mantra);
```

## Version of Realm and Tooling

Obj-c 3.9
Realm framework version: ? 

Realm Object Server version: ? 

Xcode version: ? 9.4.2

iOS/OSX version: ? 10.0

Dependency manager + version: ?

**Comment by godyolops** [comment]
![screen shot 2018-09-28 at 2 38 43 pm](https://user-images.githubusercontent.com/43644809/46192011-4184ce00-c32c-11e8-9dfc-34b3f6c41a70.png)

**Comment by TOTHO09** [comment]
I am also experiencing this issue. Please fix this issue

**Comment by Sherlzy** [comment]
I'm having this problem also in my react native app. Please fix this issue. Thanks

**Comment by ericjordanmossman** [comment]
Is anyone able to share version numbers of Realm? Is this happening to anyone with later versions?

**Comment by godyolops** [comment]
Hi already fixed this issue. The issue was my RealmJS is not compatible to the Realm im using in native for obj-c. Thanks 😊Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: ericjordanmossman <notifications@github.com> Date: 7/2/20  7:09 AM  (GMT+08:00) To: realm/realm-cocoa <realm-cocoa@noreply.github.com> Cc: godyolops <gerrytanjr@gmail.com>, Author <author@noreply.github.com> Subject: Re: [realm/realm-cocoa] RLMResults returns <invalid NS/CF object> (#5935) 
Is anyone able to share version numbers of Realm? Is this happening to anyone with later versions?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/realm/realm-cocoa/issues/5935#issuecomment-652688805",
"url": "https://github.com/realm/realm-cocoa/issues/5935#issuecomment-652688805",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
