### ISSUE TITLE
Realm failed to initialise in unit test target.

### ISSUE THREAD

**Issue by PawelPalkaPerform** [realm/realm-cocoa#5937]
## Expected Results
Make Realm instance with path ```'/Users/UserName/Library/Developer/CoreSimulator/Devices/2EE8CD31-49BC-4825-B554-61C05648D899/data/Documents'```

## Actual Results

```Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/Users/UserName/Library/Developer/CoreSimulator/Devices/2EE8CD31-49BC-4825-B554-61C05648D899/data/Documents/CommonRealm.management': make_dir() failed: No such file or directory." UserInfo={Error Code=2, NSFilePath=/Users/UserNamel/Library/Developer/CoreSimulator/Devices/2EE8CD31-49BC-4825-B554-61C05648D899/data/Documents/CommonRealm.management, Underlying=make_dir() failed: No such file or d```

## Steps to Reproduce
Create realm with this configuration on Unit Test target. (code below)

## Code Sample

``` let documentsDir = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0].absoluteString
        let realmPath = documentsDir + "CommonRealm"
        let fileURL = URL(string: realmPath)
        let configuration = Realm.Configuration(
            fileURL: fileURL,
            inMemoryIdentifier: nil,
            encryptionKey: nil,
            readOnly: false,
            schemaVersion: self.schemaVersion(),
            migrationBlock: self.migration(),
            deleteRealmIfMigrationNeeded: false,
            objectTypes: nil
        )

        return configuration
```
### Method use to run Realm
```
Realm(configuration: configuration)
```

## Version of Realm and Tooling
Realm framework version: v3.10.0

Realm Object Server version: ?

Xcode version: 10.0 (10A255)

iOS/OSX version: simulator (X,XR,8,7) 12.0.0 / Mojave 10.14

Dependency manager + version: Carthage 30.1

**Comment by tgoyne** [comment]
Make sure that the Bundle Loader build setting for your unit test target is set to `$(BUILT_PRODUCTS_DIR)/MyAppName.app/MyAppName` and Test Host is set to `$(BUNDLE_LOADER)`, as otherwise the unit tests don't run in the app's container, and the app's documents directory won't exist unless the app itself has been run.

**Comment by PawelPalkaPerform** [comment]
This is not the app, it is framework created 1.5 year ago, fully tested and working since Xcode 8 without any issue, now after migration to Swift 4.2 (from 4.1) and upgrade to Xcode 10 tests are failing, so I presume on app it will also not initialise. So in this case it won't work.

**Comment by PawelPalkaPerform** [comment]
Ok got decent explanation and reason why it is not working.
