### ISSUE TITLE
Feature Requests for a Simpler Developer Experience

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-cocoa#5943]
I've been using Realm for a few years now, and overall it's **fantastic**. It's so much easier to work with than SQLite or Core Data. I have a few **_lofty_** dreams that would make it even better.

### 🌟Wish 1: Eliminate the Idea of a Write Transaction
Just let me write to an object whenever, wherever. Wow would that be cool. This would also eliminate one of the most pesky issues I run into which is mistakenly setting up a notification while in a write transaction.

### 🌟Wish 2: Simplify Notification Listeners
Allow me to turn on a feature in a view controller that enables live-listening of all Realm objects and collections. If something changes, auto-refresh the values. Or at least coalesce all object/collection changes into a single closure where I can fire my UI refresh code.

For complex UIs I can have like 9 different listeners running. Setting up all that code with their `NotificationToken`s can be cumbersome. I just wish my collections/objects would just stay up-to-date.

### 🌟Wish 3: Make it Thread Safe
I know, I know. This must be really complicated. But 90% of my Realm crashes are because of thread issues. To not have to worry about that anymore would be amazing.

I imagine pulling these off would require putting all Realm actions into some kind of operational queue that manages Realm's state (writing, reading, observing, current thread, etc.). But figuring that out would put **_a lot less_** burden on the developer and would make Realm mind-blowingly easy to use. 😀

I love Realm. Thank you so much for creating it. Please keep up the great work! 😁👍🏼🙏🏼

**Comment by bmunkholm** [comment]
Thanks a lot for using Realm for this long - and for all the great suggestions @cliftonlabrum!
I would prefer to have the suggestions as separate issues so we can better discuss them individually. I can easily split them up and close this one, but that would make me the author, so would you mind doing that?

**Comment by cliftonlabrum** [comment]
Split into 3 separate issues as referenced above. Closing. Thanks!
