### ISSUE TITLE
Who is allowed to used Realm?

### ISSUE THREAD

**Issue by moldovaniosif** [realm/realm-cocoa#5954]
In the git hub description there is the next statement:
**This product is not being made available to any person located in Cuba, Iran, North Korea, Sudan, Syria or the Crimea region, or to any other person that is not eligible to receive the product under U.S. law.**

1. What means " not eligible to receive the product under U.S. law."? Is it allow to be used (develop / distribute) in the EU (European Union)?

2. Can an app using the "realm framework" developed in the EU be distributed to the banded countries (Cuba, Iran, etc)?

**Comment by bmunkholm** [comment]
1. As Realm includes encryption technology, US law prohibits the export of that technology to certain countries as listed. The law could potentially change to include fewer or more countries and we therefore refer to the current US laws as the "source of truth". EU is not included in the banned countries, so yes today you are allowed to develop and distribute in the EU.

2. No
