### ISSUE TITLE
How to declare optional int variable in swift 4.2?

### ISSUE THREAD

**Issue by amraamandal** [realm/realm-cocoa#5955]
![screen shot 2018-10-17 at 4 37 02 pm](https://user-images.githubusercontent.com/35094072/47073512-04c13e00-d22b-11e8-89f0-7f61e28e3ed0.png)

**Comment by tgoyne** [comment]
`RealmOptional` properties are declared as `let balance = RealmOptional<Int>()`, and then you read from and write to the `value` property of that object.
