### ISSUE TITLE
The Realm cannot be initialized because the Realm file is too large. How to fix this Realm file?

### ISSUE THREAD

**Issue by JJson** [realm/realm-cocoa#5966]
When Realm initializes, the following error is thrown:
{NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1744830464 offset: 0, Error Code=9}

we have fixed the problem in my code, but how to fix a file that is too large. The file contains the user's non-renewable data, and we don't want the user's data to be deleted.

**Comment by bmunkholm** [comment]
If the file is too large for the app to open it, you have to transfer the file to a device (any computer) wich can open it. You then have to programmatically make it smaller and then send it back to the device where you delete the original file and replace it with the compressed.

**Comment by JJson** [comment]
> If the file is too large for the app to open it, you have to transfer the file to a device (any computer) wich can open it. You then have to programmatically make it smaller and then send it back to the device where you delete the original file and replace it with the compressed.

 Is there any way to fix it on the mobile app? Ask the user copy the file out and upload it to us, we fix it and send it back, which is too much trouble for the general user. We hope to fix this file by updating the app. Is there any way to do this?

**Comment by bmunkholm** [comment]
Unfortunately if the file is somehow too big to open there is nothing you can do in the app.

**Comment by JJson** [comment]
> Unfortunately if the file is somehow too big to open there is nothing you can do in the app except doing what I outlined programmatically. You don't need to ask your user to do anything. You could send the database to a server that would then return the compressed database. Assuming you know why it was big (you say you fixed the problem) and know how to get it smaller.

All right.
Although this situation has occurred, most of the time it is the reason for our Realm users. However, whether it is possible to add a remedy for Realm to this situation.
Anyway, thank you for your answer.
