### ISSUE TITLE
How to clear write transaction in Realm.

### ISSUE THREAD

**Issue by AnandYahoo** [realm/realm-cocoa#5967]
Hi,
     I am using a realm for my project. It was good.
I am facing some issues which was very critical. Suppose if i do operation with CRUD. Sometimes i am facing "Realm already in write transaction". This will occurs because of some mismatch with data types. that we can clear if it is developing stage. but if it is live if i face this issue. it will occur forever even i restart the app. This should not happen, then it will be a big issue for us. **So please do let me know how to clear this error**. I have seen some post saying that they are asking to check the conditions "inWriteTransaction". but this will avoid the operation but we need to clear the realm instance and write it again.

Realm framework version: 3.11.1

Realm Object Server version: 3.0.1

Xcode version: 10.0

iOS/OSX version: 10.13.6

**Comment by bmunkholm** [comment]
@AnandYahoo This is an error in your program logic so that's hard for us to fix.
In your logic you need to ensure that you don't try to open a write transaction when you already have one open. You can use `inWriteTransaction` to check for that.

**Comment by AnandYahoo** [comment]
@bmunkholm 
We will follow, What you have suggested. But how can I clear this error. What is the use of checking of this. anyway its not going to allow me to write for other write transaction. Please help us to clear this error instance.

**Comment by AnandYahoo** [comment]
@bmunkholm if this error happens. the app is not at all working. I can't do any action after this. So what I have to do is, simply uninstall the app and install it again. Please guide us to fix this.

**Comment by bmunkholm** [comment]
You can only have one write transaction at a time for each thread. This error indicates that you open a write transaction and before you commit that transaction you open another write transaction. You have to write your code in a way that avoids that. 
The only situation where you would need to use `inWriteTransaction` is if you have a method that needs to make a write transaction and where you call that method from different code where you sometimes already are in a write transaction and sometimes you are not. You can then either pass a parameter to indicate if you already started the write transaction or not. Or alternatively, use `inWriteTransaction` to know if you should start a transaction or not.

**Comment by AnandYahoo** [comment]
@bmunkholm  I have handled open and close transaction properly, but the question is, while in write mode due to some exception it will come out of the function without commit or close transaction. After that It will be always in Write transaction so the other transaction is not happening at all. I want to avoid this instance and kill it.

**Comment by bmunkholm** [comment]
Well, you have to handle your exceptions properly and when they occur commit or cancel the transaction.

**Comment by AnandYahoo** [comment]
Those things we handled properly, but incase some exception happen how we have to handle the error.That is my question, but you are always saying us to correct something.
So better I will close this issue..Thanks.
