### ISSUE TITLE
RealmExamples playground crashes Xcode 10

### ISSUE THREAD

**Issue by davidpasztor** [realm/realm-cocoa#5975]
## Goals

Run the `GettingStarted.playground` file in Xcode 10

## Expected Results

Playground runs successfully without Xcode crashing

## Actual Results

Xcode crashes, so the playground cannot be used

## Steps to Reproduce

Open `RealmExamples.xcworkspace` and then `GettingStarted.playground`. Make some modifications to the playground file and it will crash Xcode.

## Version of Realm and Tooling

Realm framework version: 3.11.1

Realm Object Server version: -

Xcode version: 10.0

iOS/OSX version: macOS 10.14

Dependency manager + version: -

**Comment by leemaguire** [comment]
Closing this issue due to age, if you have any other questions please open a new issue.

Thanks.
