### ISSUE TITLE
While configuring one realm, another realm is accessed and crashes due to an encryption issue.

### ISSUE THREAD

**Issue by rethinkautismdev** [realm/realm-cocoa#6004]
## Goals
I have an issue where the wrong realm is being accessed while running a migration/setting up a different realm configuration.
## Expected Results
Launch a realm with the specified configuration and migration block successfully.

## Actual Results
While setting up the Realm config file, for a small amount of our users, Realm tries to migrate a different realm with a different encryption key and crashes. The error below happens on a line while configuring a different realm. One realm is to store login info, the other is for user info. While setting up the user realm configuration, the app sometimes crashes on the migration line, failing to decrypt the login realm. The crash happens because of a decryption error, but the issue is that for some reason a different realm is being accessed.

Error from Crashlyitics: 
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/application_id/Documents/user_login.realm': Realm file decryption failed." UserInfo={Error Code=2, NSFilePath=/var/mobile/Containers/Data/Application/application_id/Documents/rt_user_login.realm, Underlying=Realm file decryption failed, NSLocalizedDescription=Unable to open a realm at path '/var/mobile/Containers/Data/Application/application_id/Documents/user_login.realm': Realm file decryption failed.}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.37.1/src/swift/stdlib/public/core/ErrorType.swift, line 184

## Steps to Reproduce
Unfortunately I cannot reproduce this. It only happens for a small amount of our users, about 40, and I have had no luck reproducing on my end.

## Code Sample

The crash happens even when I do not set the login realm config as the default realm config.
Code for user and login realm setup:

```
    private func setupUserRealm(_ login:RTLogin) {
        do {
            Crashlytics.sharedInstance().setUserIdentifier(ID)
            Appsee.setUserID(ID)

            var userConfig = Realm.Configuration()
            userConfig.fileURL = userConfig.fileURL!.deletingLastPathComponent().appendingPathComponent("\(login.username!).realm")
            userConfig.encryptionKey = login.realmKey
            userConfig.schemaVersion = 2
            userConfig.migrationBlock = { migration, oldSchemaVersion in // Crash happens at this line.
                if (oldSchemaVersion < 2) {}
            }
            
            userConfig.deleteRealmIfMigrationNeeded = false
            Realm.Configuration.defaultConfiguration = userConfig
            try Realm()
        } catch let error as NSError {
            Crashlytics.reportError(name: "Setup User Realm Error: " + error.localizedDescription, error: error.debugDescription + "\nkey: \(login.realmKey ?? Data(capacity: 0))", code: Constants.ErrorCodes.realmAccessError)
        }
    }
```
```
    
    private func setupLoginRealm() {
        do {
            Crashlytics.sharedInstance().setUserIdentifier("Login Realm")
            var loginRealmConfig = Realm.Configuration()
            loginRealmConfig.fileURL = loginRealmConfig.fileURL!.deletingLastPathComponent().appendingPathComponent("user_login.realm")
            loginRealmConfig.encryptionKey = getLoginKeyFromKeyChain() as Data
            loginRealmConfig.schemaVersion = 2
            
            loginRealmConfig.migrationBlock = { migration, oldSchemaVersion in
                if (oldSchemaVersion < 2) {}
            }
            
            loginRealmConfig.deleteRealmIfMigrationNeeded = false
            Realm.Configuration.defaultConfiguration = loginRealmConfig
            try Realm()
        } catch let error as NSError {
            Crashlytics.reportError(name: "Setup Login Realm Error: " + error.localizedDescription, error: error.debugDescription + "\nkey: \(getLoginKeyFromKeyChain())", code: Constants.ErrorCodes.realmAccessError)
        }
    }
```

## Version of Realm and Tooling

Realm framework version: 3.11.1

Realm Object Server version: N/A

Xcode version: 10.1

iOS/OSX version: happens across ios versions 10 - 12, which are the versions the app supports

Dependency manager + version: cocoapods 1.6.0.beta.1

**Comment by axenovV** [comment]
I have exactly the same problem. You have not found a solution?

**Comment by nomannasim786** [comment]
Same problem here. Its only happening for around 1% users regardless of devices or iOS versions.

**Comment by leemaguire** [comment]
Sorry for the late reply but please update to the latest version of Realm and let us know if this solves your issue.
