### ISSUE TITLE
Lexical or preprocessor issue version 3.11.2

### ISSUE THREAD

**Issue by AFcgi** [realm/realm-cocoa#6009]
## Goals
Compile pod 'RealmSwift', '3.11.2' successfully

## Expected Results
Build successful

## Actual Results
After updating to pod 'RealmSwift', '3.11.2' it throws an error Lexical or Preprocessor Issue with the description of 'collection_notifications.hpp' and  'binding_callback_thread_observer.hpp' file not found

## Steps to Reproduce
Run pod 'RealmSwift', '3.11.2'

## Version of Realm and Tooling

Realm framework version: 3.11.2

Realm Object Server version: ?

Xcode version: 10.1

iOS/OSX version: ?

Dependency manager + version: cocoa pods 1.5.3

**Comment by ricardopereira** [comment]
It happens to me as well:

![screenshot 2018-11-20 at 17 06 05](https://user-images.githubusercontent.com/3541185/48790134-9c142800-ece6-11e8-86c5-a58f22d7d5a0.png)

**Comment by tgoyne** [comment]
This error indicates that the files from the git submodule are missing. If you explicitly imported the pod using the git repository, you have to include `submodules: true` in the `pod` line. If not, you may have just hit a cocoapods bug, and deleting the `Pods` directory and reinstalling may fix it.

**Comment by ricardopereira** [comment]
@tgoyne I removed the `Pods` directory, did run the `pod update` again and the issue persists.

My **Podfile** has:

```ruby
pod 'RealmSwift', '3.11.2'
```

**Comment by huangMingHua** [comment]
@ricardopereira I have the same problem，Later I solved the problem after deleting the local pod.
'''
pod cache clean --all
removed the Pods directory
pod update
'''

**Comment by ricardopereira** [comment]
@huangMingHua Ok, thanks for sharing!

**Comment by AFcgi** [comment]
Fixed with `Realm 3.12.0`
