### ISSUE TITLE
Fine-grained notifications

### ISSUE THREAD

**Issue by ipeisong** [realm/realm-cocoa#601]
Can I find the object type info? The parameter realm seems does not contain any specific info. That's to say I need update UIs all over the app correct? Thanks.

**Comment by bigfish24** [comment]
This isn't really an ideal solution, but I built a replacement for NSFetchedResultsController, RBQFetchedResultsController, that works along side a singleton class: RBQRealmNotificationManager that broadcasts object changes. 

https://github.com/Roobiq/RBQFetchedResultsController

Currently the notification manager is limited to the developer manually logging the changes when they occur (which will then be rebroadcasted after Realm updates), but an obvious improvement would be to subclass RLMObject and RLMRealm to log the change or the add/delete automatically.

**Comment by xtazz** [comment]
Any update on that? This can really help especially when displaying Realm objects in the table view to nicely display row animations for deleted, inserted, added or updated rows. Thank you!

**Comment by Coltspb** [comment]
:+1: I need it too

**Comment by mgleason** [comment]
> Support for more fine-grained notifications (per object) will come soon.

... Any update/timeframe for this (been almost 9-months:()?

**Comment by Antol** [comment]
+1

**Comment by skeeet** [comment]
All hope is gone by now :(

**Comment by esummers** [comment]
@skeeet Just a guess, but they will probably use the syncing architecture they are developing to implement that.

**Comment by bigfish24** [comment]
While I know it would be ideal if Realm supported it natively now, if you need something soon check out: https://github.com/Roobiq/RBQRealmNotificationManager. 

It's easy to track changes when editing a RLMObject by building a wrapper method for the object that uses blocks such as:

-(void)editObject:(void(^)(id anObject))block
{
     block(self);
     [[RBQRealmChangeLogger defaultLogger] didChangeObject:self];
}

this way every time you edit an object, just use this method to get automatic change tracking:

[anObject editObject:^(id anObject) {
    anObject.property = foo;
}

the RBQRealmNotificationManager will pass along the change to any listeners. (This is what powers RBQFetchedResultsController that I referenced earlier).

**Comment by mgleason** [comment]
Yea, but RBQRealmNotificationManager doesn't seem to work with swift.  

Even after fixing the #import "Realm.h" issues, it still won't fetch results - although  fetchedResultsController.performFetch returns success, but there are zero results...

**Comment by bigfish24** [comment]
RE: Swift, sorry about that but we are still using objc for our projects so I haven't tested any of the code with Swift. 

Feel free to ping me at adam@roobiq.com if you want to try and debug.

**Comment by mgleason** [comment]
My Apologies Adam - It's RBQFetchedResultsController that wasn't returning results, not RBQRealmNotificationManager.  I'll delete both of these comments and take it off-line...

**Comment by Brisdo** [comment]
+1 

1) This really should be renamed "Fine-grained notifications" or some-such.
2) I sense that once folks saw the comment it was "coming soon" they stopped commenting/requesting it (assuming it was being worked on) and as a result, it's not prioritized or getting the attention it needs.

**Comment by AlDrago** [comment]
+1

**Comment by zocario** [comment]
+1

**Comment by phatblat** [comment]
+1

**Comment by rynti** [comment]
+1

**Comment by treylon** [comment]
+1

**Comment by thbaja** [comment]
+1

**Comment by thbaja** [comment]
The number of stars that this project has is a testament to the interest in this feature: https://github.com/Roobiq/RBQFetchedResultsController

**Comment by veritech** [comment]
+1

**Comment by krzyzanowskim** [comment]
+2

**Comment by LouisCo** [comment]
+1 from me and my Company, but for Android side

**Comment by tuo** [comment]
+1
this would be really helpfull

**Comment by sunflash** [comment]
+2
Until this is done, realm is not real alternative to core data, if you have lots of tableview and collection view all over the place. Reload whole tableView and collectionView is not very efficient. 
RBQFetchedResultsController is cool, but it will be nice that notification is bake into the DB at lower level. Wait this feature for almost 1 year now..

**Comment by jlandrum** [comment]
If it's that imperative that you have notifications for new data, you should arrange a notification system at the point you are inserting data. To say that it is not a "real alternative" to CoreData doesn't make sense, as Realm is not a KVO library, or anything of the sort. It is strictly for data persistence. To add KVO to it, especially to add it to Android, it's very likely to break the Separation of Concerns principal - much like having a refrigerator that is also a toaster. Yes, it would be nice to be able to pull toast from your fridge, but it adds more areas in which the code can break.

That said, it's probably a bad idea to rely on your database to control aspects of your application, even with CoreData. Even CoreData has limited KVO support as it stands for that very reason.

**Comment by LouisCo** [comment]
That said, I moved to [SnappyDB](https://github.com/nhachicha/SnappyDB) on Android as building my own notification system with realm gave me  unsolvable issues with multi thread Realm rigid policy.

**Comment by kunalsood** [comment]
To further @jlandrum's point, it is worth mentioning that, as far as most people are aware, even Core Data's notification system, is built on top of sqlite, not in the sqlite engine/library itself.

While I agree that calling Realm not a "real alternative" to Core Data does not make sense, I have found myself in a situation where I started building my own notification system on top of Realm, as the available open-source ones weren't efficient enough for my use-case, and ran into issues that were unsolvable without resorting to insane hacks.

A built-in notification system with hopefully alleviate those issue. So... +1

**Comment by ninjazoete** [comment]
I can't believe it is over a year now and it seems no progress was made with notifications. 
I give +1 so it gets more attenion.
I also implemented my solution for this but I don't want to hack runtime to use Realm.

**Comment by neilpa** [comment]
Can you lock this so people stop +1'ing it. Makes subscribing to it worthless

**Comment by pzbyszynski** [comment]
@neilpa People +1'ing is what marks importance of feature request

**Comment by bcapps** [comment]
+1

**Comment by paulbruneau** [comment]
Regarding @jlandrum's point about the toaster and the refrigerator, I'd say this is more like a refrigerator without in-door water and ice service. Few _need_ it, but it's extremely convenient for almost everybody and fits completely within the reasonable feature set of such an appliance.

The absence of this feature itself doesn't bother me--I can get by. What bothers me is how can it be possible that this feature, which they said was coming soon last September (and maybe earlier), isn't here yet. It makes me question either their judgment in public statements, or their ability to get stuff done (both are important to me when considering an investment in 3rd party technology).

So +1

**Comment by esummers** [comment]
@paulbruneau I’m not on the Realm team, but I would imagine this feature would be built on top of the replication/synchronization system they are planning.  With all the changes to core, I'm not surprised this is taking additional time to complete.

**Comment by cgst** [comment]
+1

**Comment by timanglade** [comment]
Sorry this is taking a long time. We _are_ working on it at the moment. It starts with KVO support (PR #2050, which is just pending final review) and from there we will add full changesets to notifications. 

We know how much you want this, and how painful it can be to work around it; but the fact is, in most cases, you *can* work around it so this is we have dealt with this feature as the lowest priority of the big features we were missing at launch (e,.g. null support, async queries, etc.). We have also been prioritizing support & bugfixes above _all_ new features in order to make sure everyone already using Realm is not stuck waiting for an answer or fix from us to get their app going. That’s how we would like to be treated as users, and we hope you agree.

We built apps & other stuff on Realm all the time, so we’re not blind to these missing features… Trust me when I say we feel the pain at least as much as you do. We’ll keep going as fast as we can on these features, using the prioritization system explained above. If you want to help we _are_ [hiring](https://realm.io/jobs/#senior-ios-developer-brwith-strong-c-experience).

**Comment by paulbruneau** [comment]
Thanks for the nice response. My co-worker Laura and I watched your webinar the other day and were very happy with your answer. I think your prioritization is logical, thanks for explaining that too. We are looking forward to working with your product.

**Comment by jessepollak** [comment]
+1 thanks for the hard work!

**Comment by SteveTrewick** [comment]
+1 This was a dealbreaker for me when evaluating Realm for use in some upcoming iOS apps.

**Comment by peterpaulis** [comment]
+1

**Comment by enricenrich** [comment]
+1

**Comment by edwardIshaq** [comment]
:+1:

**Comment by dltlr** [comment]
+1

**Comment by scherroman** [comment]
+1

**Comment by meilers** [comment]
Wow is this happening? Congrats guys! Really need this one!

**Comment by jpsim** [comment]
Detailed change information is now included in collection notifications as of #3359 which was just merged into master.
