### ISSUE TITLE
crash happened

### ISSUE THREAD

**Issue by lzx2015** [realm/realm-cocoa#6014]
!!! MANDATORY TO FILL OUT !!!

## Goals

Solve the problem

## Expected Results

no crash

## Actual Results

crash

## Steps to Reproduce

RealmSwift is used with KVO, when used 'open func addObserver(_ observer: NSObject, forKeyPath keyPath: String, options: NSKeyValueObservingOptions = [], context: UnsafeMutableRawPointer?)' On the 11-inch iPad Pro，crash is happened.
## Code Sample

self.model.addObserver(self, forKeyPath: "***", options: [.new, .old], context: &myContext)

## Version of Realm and Tooling

Realm framework version: ?
3.11.2
Realm Object Server version: ?
no server
Xcode version: ?
Version 10.1 (10B61)
iOS/OSX version: ?
12.1(16B92)
Dependency manager + version: ?

**Comment by bmunkholm** [comment]
@lzx2015 We need much more information to be able to help you.
Which crash are you getting? Please give as much info as possible.
Is it reproducible? How exactly - please provide a project or test case that demonstrate the issue.

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
