### ISSUE TITLE
Invalid redeclaration of 'removeSubrange' in Xcode 10

### ISSUE THREAD

**Issue by vitovalov** [realm/realm-cocoa#6020]
**Bugs**: 
Project fails to compile due to `Invalid redeclaration of 'removeSubrange' in List.swift in Xcode 10.1`
And more from here:
Same as here: https://github.com/realm/realm-cocoa/issues/5803

I found this error for the first time now in one of my old projects I compiled a year ago and tried to update today.

What bothers me is that the tooling used here is the same version as in other 3 projects that currently compile fine and never had this error.

Working workaround add *use_modular_headers!*. But why others projects compile fine and this needs a workaround?

Tried:
clean build
clean build folder

pod deintegrate 

## Goals
Find out why this project fails to compile due to this error and others with same tooling compile fine.

## Expected Results
project compiles 

## Actual Results
compilation error

## Steps to Reproduce
Build project

## Version of Realm and Tooling
Realm framework version: v3.11.2

Xcode version: 10.1

iOS/OSX version: iOS 12

Dependency manager + version: cocoapods version: 1.5.3

**Comment by tgoyne** [comment]
This may be related to mixing Swift versions. Swift theoretically allows mixing a framework compiled as Swift 3 with one compiled as Swift 4 as long as the same compiler is used, but in practice the set of methods available on standard library types varies depending on what version of Swift is used, which can cause problems like this one. As such, one thing to check would be what version of Swift is used for both your app and the Pods framework in both the working and non-working projects.

**Comment by vitovalov** [comment]
Thanks @tgoyne , I've checked that and both projects use 4.2 and the majority of pods too. Realm uses 3.0 but that applies to both of my projects.

**Comment by Nixon506E** [comment]
Any update on this? Specifically having the issue with watchOS.

**Comment by stennie** [comment]
Closing this issue as it appears to have been resolved with XCode 10 support.
