### ISSUE TITLE
Values are not updated even though transaction is committed on main thread

### ISSUE THREAD

**Issue by jasper-chan** [realm/realm-cocoa#6027]
**Bugs**: One of our functions in the application is the ability to retrieve numbers that can only be used once. We control this by updating a state (type int), which can only be 3 states: Available, Finalized, Delete. We are noticing that in some instances, even though we Finalize the number, the database itself doesn't reflect this. This causes the application confusion and allows the user to retrieve the same number again. Eventually it fixes itself, but this is a huge concern... if the values won't update after a write transaction. This was all done on the main thread.

The number is first used 2018-11-30 11:39:22:680 and used again 2018-11-30 11:39:51:611. The zip file is too large to be attached here, could I send it directly to the responding support member so they can diagnose the logs on Realm's side?

## Goals
At the end of a write transaction, the updated values should be persisted in the database.

## Expected Results
At the end of a write transaction, the updated values should be persisted in the database.

## Actual Results
Updated value was not persisted.

## Steps to Reproduce
N/A

## Code Sample
N/A

## Version of Realm and Tooling

Realm framework version: 3.7.6

Realm Object Server version: N/A

Xcode version: 10.1

iOS/OSX version: 12.1

Dependency manager + version: N/A

**Comment by jasper-chan** [comment]
@bdash @TimOliver 

Update on this situation:

We have been able to somewhat reproduce it at will. Our initial hypothesis is that if there are too many Realm instances going around in the application, and each of them writes at different times, eventually the Realm framework fails to merge them together. We have done a few tests that seem to indicate this: We turned off our back-end such that only the front end is doing work, and that only the Main Thread is accessing the Realm database -- Weren't able to reproduce the problem.

We have also created a log file such that the application would dump the entire description of an object before it gets modified, and after it gets modified (with timestamps). We also changed the code such that once a record is modified, its state is set to a given ENUM such that it will never be used again; however, we noticed the object was retrieved again as if though it was available for usage. Our log dump showed that the parameters were reverted back to its original state. 

At the request of our CTO, could someone from the Realm team contact me privately at the following email (jasper.chan@scenedoc.com) so I can email the Realm file and log file to you for examination?

**Comment by tgoyne** [comment]
There is no concept of merging changes in a local database. Only one write transaction can occur at a time, and they always operate on the latest version of the data (implicitly performing a refresh after acquiring the write lock if needed). This does mean that if you perform a query, grab a reference to an object from that query and then begin the write transaction, the object may no longer be in a state where it would have matched that query.

**Comment by jasper-chan** [comment]
@tgoyne thank you for responding.

My current understanding is such that if there are multiple threads, and each of them make write locks, the MVCC design causes there to be a total of 3 versions until it can be reconciled. Am I incorrect in that?

This is generally the flow of our use case:
1) Query to find the object
2) Update the state so it cannot be used again
3) End flow

All I have added are two additional logs that dumps the description of the object in question in between steps 1 and 2, 2 and 3. At one point, we see that the object was successfully updated, but roughly 30 seconds later, the object's properties are reverted back to when it started. We noticed this by recognizing the lastModifiedDate parameter became identical to the creationDate, even though we know 30 seconds prior, they were not the same due to the object being successfully updated.

**Comment by tgoyne** [comment]
There is no reconciliation. We always refresh the Realm immediately after acquiring the write lock, so write transactions are always operating on the latest version of the data. Long lived reads can see stale data, but there's always a linear sequence of versions.

If you have a sequence of operations like the following that can run on multiple threads at a time:

1. Obtain a reference to an object
2. Perform a long operation
3. Log the state of the object before the write transaction
4. Update the object
5. Log the new state of the object after the write transaction

The logs will sometimes show the object in the initial state, then the final state, and then back to the initial state. If the first thread did step 4 while the second thread was in step 2, then in step 3 the second thread is looking at a stale view of the data. If instead the before-modification log was done inside of the write transaction which made the update, then it would always show the up-to-date values.

**Comment by jasper-chan** [comment]
@tgoyne 

Your explanation makes sense; however that leads to two things:

1) The need to perform the log in the write transaction seems to defeat the purpose of a live object, no? My current understanding is that a key advantage of Realm is the introduction of live objects, whereby the objects are always reflecting the latest version. While some exceptions may occur (e.g. if you're in the background thread and another background thread inserts a new object into the table, you may not see it immediately due to background threads only refreshing at the beginning of a run-loop), that isn't the case in this situation as only one thread is operating, which is the Main thread.

2) The system is designed such that once the object is updated to a final state, it cannot be used again. We mark it with an integer value and queries are written to exclude objects with that specific state; therefore, the scenario where multiple threads are all updating the same table record is not possible.

Would it be simpler if I emailed you our Realm file, with the log file and their corresponding time stamps to help you dig a little deeper into the situation?

**Comment by tgoyne** [comment]
With only one thread involved it should not be possible to ever have stale reads.

Realm files for non-synchronized Realms don't persist any history information in a useful form, so I don't know what the file would show or how useful any logs would be without seeing the code that produces them.

**Comment by jasper-chan** [comment]
@tgoyne 

Thank you very much for answering my questions. I was able to pinpoint where our application went wrong with your explanation. I consider this issue closed now. Thanks!
