### ISSUE TITLE
Realm could not be initialized

### ISSUE THREAD

**Issue by charlesburks** [realm/realm-cocoa#6028]
## Goals
To fix this crash.

## Expected Results
To init realm.

## Actual Results
instant crash
## Steps to Reproduce
See below.
## Code Sample
Calling `let realm = try! Realm()` causes a crash.
Xcode opens to this:
```
inline void SharedGroup::open(Replication& repl, const SharedGroupOptions options)
{
    // Exception safety: Since open() is called from constructors, if it throws,
    // it must leave the file closed.

    REALM_ASSERT(!is_attached());

    repl.initialize(*this); // Throws

    typedef _impl::GroupFriend gf;
    gf::set_replication(m_group, &repl);

    std::string file = repl.get_database_path();
    bool no_create = false;
    bool is_backend = false;
    do_open(file, no_create, is_backend, options); // Throws
}
```

Thread breakpoint 
```
0x102841108 <+2980>: bl     0x1027a3b6c               ; realm::SlabAlloc::attach_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, realm::SlabAlloc::Config&)
0x10284110c <+2984>: str    x0, [sp, #0x28]
```
App was working like normal before. Now it crashes instantly.
## Version of Realm and Tooling

Realm framework version: ?
just updated all cocoapods 
Realm Object Server version: ?

Xcode version: ?
10.1
iOS/OSX version: ?
10.14.1 
Dependency manager + version: ?

**Comment by tgoyne** [comment]
If you catch the error thrown rather than using `try!` it will have an error message that may prove useful.

**Comment by charlesburks** [comment]
I used `try! FileManager.default.removeItem(at: Realm.Configuration.defaultConfiguration.fileURL!)` to clean the database, it worked,  but this if obviously not ideal.

**Comment by charlesburks** [comment]
Super hacky way to fix this.
```
func checkForCorruptDB(){
        do {
            let _ = try Realm()
        } catch {
            try! FileManager.default.removeItem(at: Realm.Configuration.defaultConfiguration.fileURL!)
        }
    }
```
