### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lumengru** [realm/realm-cocoa#6033]
Trapped uncaught exception 'RLMException', reason: '/Users/qeeniao35/Library/Developer/CoreSimulator/Devices/D5D82D1D-0A26-485B-A096-0F5564E37B67/data/Containers/Data/Application/97989B7F-47D1-47A0-9122-58E7A631E3AD/Documents/Qeeniao.realm.lock: Unable to open a realm at path '/Users/qeeniao35/Library/Developer/CoreSimulator/Devices/D5D82D1D-0A26-485B-A096-0F5564E37B67/data/Containers/Data/Application/97989B7F-47D1-47A0-9122-58E7A631E3AD/Documents/Qeeniao.realm.lock': open() failed: Too many open files in system.'

**Comment by stennie** [comment]
The error message indicates there were too many open files in your system, which is an error outside of Realm. To address this you need to look into open files or increase the file limit using the `ulimit` command.
