### ISSUE TITLE
leveldb-library/include/leveldb/slice.h:21:10: 'string' file not found 

### ISSUE THREAD

**Issue by MrReyesA** [realm/realm-cocoa#6034]
Im trying to connect to Firebasee database, im using swift 4, but when y install pod "Firebase/Database" 
i get this error:
![image](https://user-images.githubusercontent.com/37433830/49801148-067d1e80-fd0f-11e8-88df-ee640e9e52bf.png)
![image](https://user-images.githubusercontent.com/37433830/49801183-1bf24880-fd0f-11e8-8092-8237033af47d.png)

 I all ready delete de pod files and re-install, clean cache, change the versions of the project and the problem seem to not be solve, any idea????

**Comment by bmunkholm** [comment]
@MrReyesA Please report that to Firebase instead of Realm :-)
