### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value in realm.add

### ISSUE THREAD

**Issue by baljinderkamboj** [realm/realm-cocoa#6035]
This is my json that I'm writing using realm.add 

        serviceid = 1
        actualpickupdate = (null)
	actualdeliverydate = (null)

// actualpickupdate and actualdeliverydate are option parameter in json.

while I'm writing to realm: like

           do {
                let beer = try decoder.decode(UserOrderHistory.self, from: data)
                    for d in beer.orderlist! {
                    try? realm!.write {
                        realm?.add(d)
                    }
                }
                }catch {
                     print(error)
                }

// realm.add method throw error (fatal error: unexpectedly found nil while unwrapping an Optional value)

**Comment by leemaguire** [comment]
We need see a stack trace in order to validate if this is an issue with Realm.
