### ISSUE TITLE
About the problem of deleting array elements

### ISSUE THREAD

**Issue by JJson** [realm/realm-cocoa#6037]
I delete an element in an array, and the index of the callback in the corresponding listener closure does not correspond to the element I deleted.Even if I delete an element, the parameter index in the closure is two.

This will cause the use of this array as the DataSource of the UITableView, which will cause a crash when doing the delete operation.

## Steps to Reproduce
For complete sample code, please see : https://github.com/JJson/RealmIssueReportExample.git

Results are as follows：

delete index: 37
deletions: [37, 45], insertions: [37], modifications: []
delete index: 4
deletions: [4, 44], insertions: [4], modifications: []
delete index: 31
deletions: [32, 43], insertions: [32], modifications: []
delete index: 34
deletions: [36, 42], insertions: [36], modifications: []

## Code Sample

    import UIKit
    import RealmSwift

    class Dog: Object {
        @objc dynamic var name = ""
        @objc dynamic var age = 0
        override static func primaryKey() -> String? {
            return "name"
        }
    }

    class ViewController: UIViewController {
        var dogs = [Dog]()
        var token: NotificationToken?
        override func viewDidLoad() {
            super.viewDidLoad()
            initData()
            query()
        }

        @IBAction func deleteAction(_ sender: Any) {
            guard dogs.count > 0 else {
                return
            }
            let realm = try! Realm()
            try! realm.write {
                let index = Int(arc4random()) % dogs.count
                print("delete index: \(index)")
                let randomDog = dogs[index]
                realm.delete(randomDog)
                dogs.remove(at: index)
            }
        }
        func query() {
            let realm = try! Realm()
            let result = realm.objects(Dog.self).filter("age > 3")
            dogs = Array(result)
            token = result.observe { (change) in
                switch change {
                
                case .initial(_):
                    break
                case .update(_, let deletions, let insertions, let modifications):
                    print("deletions: \(deletions), insertions: \(insertions), modifications: \(modifications)")
                case .error(let error):
                    fatalError("\(error)")
                }
            }
        }
    
        func initData() {
            do {
                let realm = try Realm()
            
                try realm.write {
                    for i in 0..<50 {
                       realm.create(Dog.self, value: ["name\(i)",i], update: true)
                    }
                }
            } catch {
                fatalError("\(error)")
            }
        
        }
    }

Realm framework version: 3.12.0

Xcode version: 10.1

**Comment by tgoyne** [comment]
The order of objects in an unsorted Results is not stable, and will change when objects are deleted. In this case, there is an additional deletion and insertion because the object which was at the end was moved to the position of the deleted object.

You need to either sort the query on a property which gives the objects a stable ordering, or handle these additional insertion and deletion pairs.
