### ISSUE TITLE
io error

### ISSUE THREAD

**Issue by lgl2444** [realm/realm-cocoa#6038]
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 1048576 offset: 99614720" UserInfo={Error Code=9, NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 1048576 offset: 99614720}:

**Comment by leemaguire** [comment]
Closing due to age and insufficient information.
