### ISSUE TITLE
Non-linear migration fails when adding and then deleting a property

### ISSUE THREAD

**Issue by sarveshmathi** [realm/realm-cocoa#6039]
## Goals

Migrating from schema v0 to v2

Schema Version 0 

```
class Item: Object { 
  @objc dynamic var name: String? = nil
  @objc dynamic var date = Date()
  }
```

Schema Version 1

```
class Item: Object {
@objc dynamic var name: String? = nil
@objc dynamic var date = Date()
@objc dynamic var isDeleted: Bool = false 
}
```

Schema Version 2

```
class Item: Object {
@objc dynamic var name: String? = nil
@objc dynamic var date = Date()
}
```

My migration block 

```
if oldSchemaVersion < 1 {
migration.enumerateObjects(ofType: Item.className(), { (oldObject, newObject) in
        newObject!["isDeleted"] = false
    })
}

if oldSchemaVersion < 2 {
//Nothing to do, since I removed isDeleted property 
}
```

## Expected Results

A correct migration, whether going from schema v0 to v1 or v0 to v2

## Actual Results

Apps migrating from schema v0 to v2 crash at start with following error:
`Terminating app due to uncaught exception 'RLMException', reason: 'Invalid property name 'isDeleted' for class 'Item'.'`

## Version of Realm and Tooling

Realm framework version:
Realm (3.11.2)
RealmSwift (3.11.2)

Xcode version:
Xcode 10.1
Build version 10B61

iOS/OSX version: 
iOS 12.1.2

**Comment by leemaguire** [comment]
Please see our documentation on this issue: https://realm.io/docs/swift/latest/#linear-migrations
