### ISSUE TITLE
error while installing realm

### ISSUE THREAD

**Issue by nadia-am** [realm/realm-cocoa#6040]
when i want to install realm from podfile i face this error! 
`Installing Realm (3.13.0)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 3.13.3
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-3.13.3.tar.xz
	curl: (22) The requested URL returned error: 403 `

Xcode version: 10.0

**Comment by Li-Qun** [comment]
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 3.13.3
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-3.13.3.tar.xz
	curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by XiangJiangzhou** [comment]
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 3.13.3
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-3.13.3.tar.xz
	curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by mehdico** [comment]
Similar Problem :(

**Comment by leemaguire** [comment]
Please try installing with the latest version of Realm. Thanks.
