### ISSUE TITLE
Add Realm module map generation

### ISSUE THREAD

**Issue by matt** [realm/realm-cocoa#6042]
## Goals
Allow RealmSwift to be added as a static library via Cocoapods.

## Expected Results
Realm defines modules

## Actual Results
**Cocoapods Error:**
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `RealmSwift` depends upon `Realm`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

## Pull Request
https://github.com/realm/realm-cocoa/pull/6041

**Comment by leemaguire** [comment]
Given the linked issue is closed and the lack of demand for a static library I am closing this issue.
