### ISSUE TITLE
Object isInvalidated after app is in background

### ISSUE THREAD

**Issue by BartoszNowacki** [realm/realm-cocoa#6051]
## Goals
I have extended my model with Realm Object. Then I am using its object in a class and I am using it throughout this class. In this class I'm also sending user to safari.

## Expected Results
object is ready to use even after app was in the background.

## Actual Results
After apps going to background (for example: I was sending user to safari) and coming back to app, object.isInvalidated = true. And I can't use this object anymore. App crash if I try, or I can make check for isInvalidated
-->

## Steps to Reproduce
You should store object of model which extend Realm Object in a class, and try to use it after app was in background (use safari or other app instead).

## Code Sample
If needed I will provide more data

Realm framework version: Current version

Xcode version: 10.1

iOS/OSX version: All, last tested on 11.2

**Comment by tgoyne** [comment]
There is nothing in Realm which automatically closes the file or invalidates objects when the app goes into the background. This is probably due to something that your specific app is doing.

**Comment by tgoyne** [comment]
There is nothing in Realm which automatically closes the file or invalidates objects when the app goes into the background. This is probably due to something that your specific app is doing.
