### ISSUE TITLE
Invalid value 'https://someurl' of type 'NSURL' for string

### ISSUE THREAD

**Issue by adamofsky** [realm/realm-cocoa#6054]
## Goals
What do you want to achieve? -->String

## Expected Results
What did you expect to happen? -->
Achieved String

## Actual Results
 Throw in RLMUtil.mm on line 180     
`@throw RLMException(@"Invalid value '%@' of type '%@' for '%@%s'%s property '%@.%@'.",
                        obj, [obj class],
                        prop.objectClassName ?: RLMTypeToString(prop.type), prop.optional ? "?" : "",
                        prop.array ? " array" : "", objectSchema.className, prop.name);`

 
Nothing printing because it is throwing on this line, but in the debugger I can reproduce the message and see the following:
"Invalid value 'https://assets.myurl/file.png?1510040391' of type 'NSURL' for 'string' 'MyObject' property 'imageUrl'"

## Steps to Reproduce
Try to achieve string that has real URL value.

## Code Sample
`@objcMembers`
`class MyObject: Object, Decodable{`
    `enum CodingKeys: String, CodingKey{`
        `case imageUrl`
    `}`
`@objc dynamic private(set) var imageUrl: String!`
    `convenience required init(from decoder: Decoder) throws{`
        `let container = try decoder.container(keyedBy: CodingKeys.self)`
        `self.init()`
        `self.imageUrl = try? container.decode(String.self, forKey: .imageUrl)`
`var realm = try? Realm()`
                `do {`
           `try realm?.write {`
                `realm?.add(self, update: true)`
           ` }`
       `} catch let error as NSError {`
            `assertionFailure(error.localizedDescription)`
        `}`
    }`

## Version of Realm and Tooling
Realm framework version: 3.11.0

Realm Object Server version:  No Realm server

Xcode version: Version 10.1 (10B61)

iOS/OSX version: 11.0.1

**Comment by mstralka** [comment]
@adamofsky did you solve this?
