### ISSUE TITLE
Realm calculate and sort using subquery

### ISSUE THREAD

**Issue by Urkman** [realm/realm-cocoa#6055]
I already asked this question on StackOverflow, but did not get an answer :( So try here again.

Is there a way calculating and sorting using subquerys?

I have this objects(simplified) in my Realm database:

```
class Customer: RealmSwift.Object {
    @objc dynamic var id: String? = nil
    @objc dynamic var name: String? = nil
}

```
```
class Order: RealmSwift.Object {
    @objc dynamic var id: String? = nil
    @objc dynamic var customer_id: String? = nil
    @objc dynamic var region_id: String? = nil

    let total = RealmOptional<Float>()
}
```
Now I want to get only customers with orders in a region (using region_id) and sort the customers by calculating the total of all orders in that region.

Thanks, Urkman

**Comment by tgoyne** [comment]
Realm does not currently support sorting on a computed value.
