### ISSUE TITLE
Is it possible to filter child list?

### ISSUE THREAD

**Issue by MattW86** [realm/realm-cocoa#6064]
Hi realm community, I hope I can get some support for my problem. Thanks in advance.

## Goals
I am trying to filter a child list inside a parent object.  Ideally, I would like to filter both parent and child at the same time using predicates. 

## Expected Results
At least ability to filter child lists. Ideally, ability to filter both parent and child.

## Actual Results
Unable to achieve what I want at the moment.

## Code Sample
For instance, given this schema:
```
class Parent: Object {
    var children = List<Child>()
}

class Child: Object, Decodable {
    @objc dynamic var name: String?
    let parent = LinkingObjects(fromType: Parent.self, property: "children")
}

```

And I have the following data:
```
[
  {
    "parent1": [
      "child1",
      "child2",
      "child3",
      "child11"
    ]
  },
  {
    "parent2": [
      "child4",
      "child5"
    ]
  },
  {
    "parent3": [
      "child1",
      "child6",
      "child7"
    ]
  }
]
```

What I would like to get parents with children where children name contains "child1". In this scenario, expected output would be

```
[
  {
    "parent1": [
      "child1",
      "child11"
    ]
  },
  {
    "parent3": [
      "child111"
    ]
  }
]
```

What kind of query can I write to achieve what I want?

**Comment by tgoyne** [comment]
`realm.objects(Parent.self).filter("ANY children.name CONTAINS %@", "child1")` will give you all `Parent` objects with at least one child whose name contains `child1`. Realm does not support projected views of objects, so the code processing those `Parent` object then needs to apply the desired filter to the `children` List (i.e. something like `parent.children.filter("name CONTAINS %@", "child1")`).
