### ISSUE TITLE
Realm framework and download size qustion

### ISSUE THREAD

**Issue by aryan-ghassemi-ck** [realm/realm-cocoa#6065]
I'm considering using realm in a project, but I read so many issues with app size and framework size. I currently can't even check in the framework in github.

Are there metrics on how much realmsSwift adds to the download size of the app?

**Comment by tgoyne** [comment]
You can measure how much adding Realm to your app will increase the download size by:

1. Disable bitcode generation in the project build settings (bitcode *massively* increases the size of the archive you upload to Apple, but is not downloaded by end users)
2. Disable debug symbol generation (also included in the archive and uploaded to Apple, but not sent to end users)
3. Remove all but one architecture from your app
4. Archive the app
5. Add Realm to your app
6. Archive again, and compare sizes

**Comment by aryan-ghassemi-ck** [comment]
Thakns
