### ISSUE TITLE
Realm file gets deleted when app crashes in the middle of a write transaction, whole database is cleared and recreated (empty file on next run)

### ISSUE THREAD

**Issue by pierrewehbe** [realm/realm-cocoa#6066]
**Questions**:
No where in my app I delete the realm file.

**Feature Request**:

**Bugs**: Realm file gets deleted when app crashes in the middle of a write transaction, whole database is cleared and recreated (empty file on next run)
If it helps the write transaction is inside the "convenience init" method of a Realm object
I am able to reproduce it consistently 
Also, my other files in the same directory (default documents directory) including downloaded files and created folders are still intact.

## Goals
How can I prevent my realm file to be deleted/ cleared when my app crashes or if the user suddenly exists the app while there is still a write transaction being processed

## Expected Results
App crashes but realm data is still available

## Steps to Reproduce
Crash app while in a write transaction 
(optional: do this inside convenience init of Realm object)

## Version of Realm and Tooling
Realm framework version: 3.13.1

Xcode version: 10.1

iOS/OSX version: 12.0

Also I am using a RELEASE build of my app

**Comment by tgoyne** [comment]
This is not a normal thing to have happen, and the Realm file format is specifically designed to not lose data on a crash, including one during a write transaction.

**Comment by pierrewehbe** [comment]
I was able to reproduce the issue using the following steps:
- Within a convenience init of a realm object call a function: populateList()
- populateList():

func populateList() {
     DispatchQueue.main.async {
             try! realm.write {
                    creating new Realm objects..., // when crash occurs within this block, my realm file is 
                                                                           deleted and reinitialized on the next app launch
             }
    }
}

**Comment by leemaguire** [comment]
We need more information on how you are using Realm (code samples and a crash log). I am closing this issue because of insufficient information and an outdated Realm version. If you have any other questions please open a new issue.

Thanks.
