### ISSUE TITLE
Notifications for sorted Results

### ISSUE THREAD

**Issue by AF-cgi** [realm/realm-cocoa#6070]
## Goals
Achieve the observing of notification in combination with sorted `Results`.

## Expected Results
Correct notification observation.

## Actual Results
If I change the `sortedBy` property of all my Objects in the results, my expectations are that I get a `modification` notification for all my objects. But it isn't so. Most of the objects get a `insert` and `delete` notification. What's the problem?

## Steps to Reproduce
If you shuffle a `Results` the issue is reproducible.

## Code Sample
```swift
let realm = try! Realm()
let results = realm.objects(Object.self).sorted(byKeyPath: "sortedBy")
results.observe { ... }
```

## Version of Realm and Tooling
Realm framework version: current version 3.13.1

Realm Object Server version: ?

Xcode version: 10.1

iOS/OSX version: 12.1

Dependency manager + version: cocoapods

**Comment by tgoyne** [comment]
Changes to the order of objects in a collection is reported as the moved object being deleted from the old location and inserted into the new location.

**Comment by AFcgi** [comment]
Ok, but then occur a problem with the update of the ui. I use the following code snippet to do that:
```swift
token = collection.observe { changes in
    switch changes {
    case .initial:
        tableView.reloadData()
    case .update(_, let deletions, let insertions, let modifications):
        // Query results have changed, so apply them to the UITableView
        tableView.beginUpdates()
        tableView.insertRows(at: insertions.map({ IndexPath(row: $0, section: 0) }),
                             with: .automatic)
        tableView.deleteRows(at: deletions.map({ IndexPath(row: $0, section: 0)}),
                             with: .automatic)
        tableView.reloadRows(at: modifications.map({ IndexPath(row: $0, section: 0) }),
                             with: .automatic)
        tableView.endUpdates()
    case .error(let error):
        // handle error
        ()
    }
}
```
How could I solve this? What is the best practice for that case? In my opinion it does make sense that a sorted `Results` trigger a insert and deletion if I change the `sortedBy` property.

**Comment by leemaguire** [comment]
Please see this article explaining the proper use case for UITableViews: https://academy.realm.io/posts/live-objects-fine-grained-notifications-realm-update/
