### ISSUE TITLE
crash when do migration

### ISSUE THREAD

**Issue by weiminghuaa** [realm/realm-cocoa#6073]
The new version adds two fields: is_valid and priority, which are Boolean and INT types.
<img width="407" alt="ce2464a9094cbab5b302892251b6b785" src="https://user-images.githubusercontent.com/2723525/52032501-2cc77980-255c-11e9-8c33-728badc0cd48.png">

Use the following code to do a database table structure upgrade, crash
<img width="519" alt="89ecd62a932f502a8011b7915049e92f" src="https://user-images.githubusercontent.com/2723525/52032510-33ee8780-255c-11e9-94dd-4f02e2f1255c.png">

It is normal to use this code instead.
<img width="517" alt="a6b141dc3018cca23f02413b5e3d0a11" src="https://user-images.githubusercontent.com/2723525/52032515-3b159580-255c-11e9-8a6d-58044a9d1972.png">

**Comment by BaluNaik** [comment]
@weiminghuaa I have similar kind of issue with `NSInteger` type. Don't assign the default value to primitive type it works fine.

**Comment by JohnnyTseng** [comment]
I've got same issue with you, for unknown reason, lots of crashes...

**Comment by weiminghuaa** [comment]
@BaluNaik  Thank you!

**Comment by weiminghuaa** [comment]
What is T:* label? What that mean, how to do it?
