### ISSUE TITLE
Is it possible to transfer RLMObject (Objective-C) properties into  Object(Swift)?

### ISSUE THREAD

**Issue by BaluNaik** [realm/realm-cocoa#6077]
Is it possible to transfer RLMObject (Objective-C) properties into  Object(Swift)?

**Goal**

- We have a data model subclass of RLMObject with many properties and we are storing everything in the realm but not using all those properties.

- We are planning to enhance our local database structure with the new Swift based realm model to utilizing memory more efficiently.

**Expected Results** 

- From all existing data model object, we want to transfer some properties into the new model(table) using some realm migration.

@bmunkholm  @jpsim @austinzheng @segiddins @tgoyne @alazier Can you guys help me on this?

Thanks!!!

_Originally posted by @BaluNaik in https://github.com/realm/realm-cocoa/issues/4583#issuecomment-460616047_

**Comment by tgoyne** [comment]
Realm files are cross-platform and there is nothing stopping you from opening a file written by obj-c code using swift with swift-defined models as long as the schema matches.
