### ISSUE TITLE
Large Result collection observation issue (time lag)

### ISSUE THREAD

**Issue by dmitryzawadsky** [realm/realm-cocoa#6085]
## Goals
I'm trying to observe large Result object and obtain notifications quickly. There's time lag while observing Results contains of 40k entities , each with extra subentity, like Dog->Owner, one to one. Data is provided using pagination algorithm.
Is there is a way I can obtain Results change notification in faster way?

## Expected Results
Observing small list (65 entities):
**15:46:25006** new pax value = 1 (property change)
**15:46:25039**
filteredInsertions = []
filteredDeletions = []
filteredModifications = [0]

delta is **33ms**

Works pretty fast, tableview modifies it's cell according to new value almost instantly (places checkmark on cell)

## Actual Results
40k entities (like described above)
**15:44:15178** new pax value = 4 (property change)
**15:44:15832**
filteredInsertions = []
filteredDeletions = []
filteredModifications = [0]

delta is **654ms**

Works pretty slow, it takes time (even after swipe left/right cell animation finished) to renew cell state

## Code Sample
Just regular Result collection observation.
```
notificationToken = rsvps.observe { [weak self] (changes) in

                guard let self = self else {
                    Logger.log("Unable to resolve self")
                    return
                }

                self.updateRsvpCounters()
                switch changes {
                case .initial:
                    self.tableView.reloadData()
                case .update(_, let deletions, let insertions, let modifications):

                    Logger.log("""
                        \nfilteredInsertions = \(insertions)
                        filteredDeletions = \(deletions)
                        filteredModifications = \(modifications)
                        """)

                    self.tableView.beginUpdates()
                    self.tableView.insertRows(at: insertions.map { IndexPath(row: $0, section: 0) },
                                              with: .fade)
                    self.tableView.deleteRows(at: deletions.map { IndexPath(row: $0, section: 0) },
                                              with: .left)
                    self.tableView.reloadRows(at: modifications.map { IndexPath(row: $0, section: 0) },
                                              with: .none)
                    self.tableView.endUpdates()
                case .error(let error):
                    Logger.log("Error: \(error)")
                }
            }
```

## Version of Realm and Tooling
Realm framework version: 3.13.0
Xcode version: Version 10.1 (10B61)
iOS/OSX version: Mojave 10.14.2
Dependency manager + version: CocoaPods 1.6.0.beta.2

PS: Issues which can be related to my, but I found no answer there: #5689

**Comment by ericjordanmossman** [comment]
@dmitryzawadsky 

> Is there is a way I can obtain Results change notification in faster way?

The first thing to consider are the other properties of `rsvps`. With [collection notifications](https://realm.io/docs/swift/latest/#collection-notifications) every nested object property could trigger a notification.

You could explore [inverse relationships](https://realm.io/docs/swift/latest/#inverse-relationships) for properties you do not want to trigger. And [Object notifications](https://realm.io/docs/swift/latest/#object-notifications) are another method to more granularly observe objects.

And in the event that you're measuring the delta time via the UI, you may also want to use dispatch groups to update the UI. I've seen cases where a developer's notifications are firing promptly, but the UI update is de-prioritized, causing a visual lag.
