### ISSUE TITLE
Add options to avoid the `mmap() failed`

### ISSUE THREAD

**Issue by CraigSiemens** [realm/realm-cocoa#6086]
## Goals
Add options to avoid the `mmap() failed`.

Getting the `mmap() failed: Cannot allocate memory size:` error is probably the worst error one could get from Realm. It happens when the app launched and there is no way to recover other than deleting the database or the app.

## Expected Results
Add the ability to compact a realm without mmaping it into memory.

* This would allow apps to recover from the above error without losing the users data. 

Add the ability to compact a realm some time after launch

* This would allow apps that are not terminated to compact the realm. This would fix the case where the realm grows over time but the app never gets an opportunity to compact it.

Add messaging or debugging steps to find out why the realm file is multiple GB.

* The largest DB one of my users should ever see is 10 MB. There is no reason the realm file should get that large.
* I was able to find a cause a while ago that I posted about in https://github.com/realm/realm-cocoa/issues/5482#issuecomment-431960796 but I'm running into the issue again and the same troubleshooting is coming up empty.

**Comment by diegomontoya** [comment]
@CraigSiemens Do not write to the same realm on multiple threads. Limit your realm reads to only UI and DB thread and only write on DB thread. Your GB sized realm file issue wil go away. This sounds counter intuitive but that's how the internals work. Realm is multi-thread capable but having multiple threads open with realm and having transaction going on will cause file bloat.

**Comment by leemaguire** [comment]
A Realm file can grow in size for multiple reasons:

- You are holding onto an instance of Realm that is no longer used.
- Realm files reserve space for future transactions, although this can be reduced with compaction.
- Realm files carry transaction history if sync is enabled.
- Improper use of threading.

`This would allow apps that are not terminated to compact the realm. This would fix the case where the realm grows over time but the app never gets an opportunity to compact it.` - You do not need to use one Realm instance for your entire app lifetime. It is fine to have multiple Realm instances once the proper cleanup is in place. You could then do a compaction sometime into your app lifetime.
