### ISSUE TITLE
Schema version not set until first migration

### ISSUE THREAD

**Issue by cchhom-bsm** [realm/realm-cocoa#6088]
## Goals

Set the schema version to a non-zero version after a fresh install

## Expected Results

When performing the first migration, I expected the oldSchemeVersion to be 3, not 0.

## Actual Results

The old schema version number was 0 the first time migration was triggered.

## Steps to Reproduce

1. fresh install schema version set to 3 > migration not called, as expected
2. no change in version but install/launch the app again > migration called, old version = 0 ?
3. no change in version, but install/launch the app one more time > migration not called, as expected
4. change schema to version 4, update app > migration called, old version = 3, as expected

Is step 2 the expected value for the old schema version? The reason this causes and issue, is because in the code sample below, we are trying to rename a property that does not exist and it crashes. For testing the above scenario, I commented the renameProperty line out.

## Code Sample

```
let config = Realm.Configuration(
    schemaVersion: RealmRepositoryMigration.schemaVersion,
    migrationBlock: RealmRepositoryMigration.migrationBlock)
Realm.Configuration.defaultConfiguration = config
let realm = try! Realm() 
```

```
enum RealmRepositoryMigration {

    static let schemaVersion: UInt64 = 3

    static let migrationBlock: MigrationBlock = { migration, oldSchemaVersion in
        log.d("schema: \(oldSchemaVersion)")
        if oldSchemaVersion < 1 {
            migration.enumerateObjects(ofType: UserRealmObject.className()) { _, newObject in
                guard let newObject = newObject else {
                    return
                }
                newObject["dTime"] = 0
            }
        }

        if oldSchemaVersion < 2 {
            migration.renameProperty(onType: UserRealmObject.className(), from: "userName", to: "username")
        }

        if oldSchemaVersion < 3 {
            migration.enumerateObjects(ofType: UserRealmObject.className()) { _, newObject in
                guard let newObject = newObject else {
                    return
                }
                newObject["logAs"] = ""
            }
        }
    }
}

```

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391

/Applications/Xcode.app/Contents/Developer
Xcode 10.1
Build version 10B61

/usr/local/bin/pod
1.5.3
Realm (3.12.0)
RealmSwift (3.12.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

/usr/local/bin/carthage
0.31.0
(not in use here)

/usr/bin/git
git version 2.17.2 (Apple Git-113)
```

**Comment by tgoyne** [comment]
That is not the expected behavior, but I can't really say what could be going wrong from just that code snippet.

**Comment by cchhom-bsm** [comment]
Thanks for the confirmation. We just found the issue on our end. We were initializing it in one more place without providing the configuration.
