### ISSUE TITLE
Realm filter based on RealmOptional property : 'Property 'rid' not found in object of type 'User''

### ISSUE THREAD

**Issue by NorbertKorosi** [realm/realm-cocoa#6090]
## Goals
After I updated my project to swift 4.2 and also updated the realm pod, the query what is worked before always crash. The crash is happens with xCode 10.1, with xCode 9.4.1 worked.

I declared the  'rid' RealOptional property in my realm model:
class User:Object {
        @objc dynamic var deletedAt : Date?
        @objc dynamic var markedForDeletion : Bool = false
        @objc dynamic var createdAt : NSDate = NSDate()
        @objc dynamic var updatedAt : NSDate?
        let rid = RealmOptional<Int64>()
}

## Expected Results
I did the following query:
var user: User! = realm.objects(User.self).filter("rid == %@", signInItem.userItem.uniqueId).first

## Actual Results
Terminating app due to uncaught exception 'Invalid property name', reason: 'Property 'rid' not found in object of type 'User''

## Steps to Reproduce
This started to happen when I updated the project to swift 4.2, and also updated the realm pod.

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by Gargo** [comment]
I have the same issue
