### ISSUE TITLE
Ignoring fields while using polymorphism

### ISSUE THREAD

**Issue by ali-zahedi** [realm/realm-cocoa#6091]
I'm using some classes which all inhertance from `RawModel`:

```
class RawModel: Object{
    @objc dynamic var pk: Int = 0
    @objc fileprivate dynamic var id: String = "0"
    @objc dynamic var _resourcetype: String = ""
	
    // MARK: -Function
    override static func primaryKey() -> String? {
        return "id"
    }

    override class func ignoredProperties() -> [String] {
	var keys: [String] = []
		
	keys.append("realm")
	return keys
    }

}

```

If I explicitly ignore one field it will ignore it all classes and database correctly doesn't insert it. But If I want child classes doesn't contain parent fields, this doesn't work and all ignored fields are inserted.

I'm using following function to ignore my desired fields:

```
override class func ignoredProperties() -> [String] {
        var keys: [String] = []
        let instance = self.init()
        var mirror: Mirror? = Mirror(reflecting: instance).superclassMirror
        repeat {
            guard let m = mirror else{
                return keys
            }
            for case let (label?, _) in m.children {
                if label == "id"{
                    continue
                }
                keys.append(label)
            }
            mirror = m.superclassMirror
        } while mirror != nil

        keys.append("realm")
        return keys
    }
```

But this doesn't work.

My logs shows that my desired fields are ignored in the program but realm doesn't follow it. 
I'm not looking for polymorphism implementation. I'm just looking for a way to tell realm explicitly ignore some fields for me.

Here is my complete code for my classes: 

```
class BaseModel: RawModel{
    @objc dynamic var url: String?
    @objc dynamic var reviewCount: Int = 0
    @objc dynamic var reviewAverage: Int = 0

}

class Product: BaseModel{
    
    
    @objc dynamic var title: String = ""
    @objc dynamic var price: Int = 0
    @objc dynamic var isBuy: Bool = false
}

class File: Product{
    
    @objc fileprivate dynamic var _fileURLRelative: String?
    @objc fileprivate dynamic var _password: String?
    @objc fileprivate dynamic var _previewURL: String?
}
```

This is my logs:

BaseModel
`["pk", "_resourcetype", "realm"]`

Product
`["url", "reviewCount", "reviewAverage", "pk", "_resourcetype", "realm"]`

File
`["title", "price", "isBuy", "url", "reviewCount", "reviewAverage", "pk", "_resourcetype", "realm"]`

Realm framework version: 3.13.1

Xcode version: 10.1

iOS/OSX version: 12

**Comment by ericjordanmossman** [comment]
@ali-zahedi 
Realm parses all models defined in your code at launch. So any property defined at launch will be in the Realm schema. You may be able use [`ObjectTypes`](https://github.com/realm/realm-cocoa/blob/v5.1.0/RealmSwift/RealmConfiguration.swift#L209) configuration on the realm if you'd like to manage different classes.
