### ISSUE TITLE
Realm Object Server goes down automatically because of server file size grows automatically into GB's.

### ISSUE THREAD

**Issue by sagarshirbhate** [realm/realm-cocoa#6092]
**Questions**: Realm Object Server goes down automatically. All Realm Files its configuration works properly but in the meantime server assigned memory space gets full automatically and its stops working. I had attached some Screenshots. How the server files are shown on console.

![aa3c41f8-4df1-46eb-81ee-0dee4190f308](https://user-images.githubusercontent.com/10905330/53785255-dd4ee180-3f3d-11e9-84aa-9c6c3230b3d0.JPG)

In The File structure you can see the **data size of realm is just 39Mb** and the Node_modules and Realm_object_server file size is **43GB**

Something is going very wrong on realm server side we are not able to figure this out why its going into GB's.

Because of this server goes down.

## Goals
Server should not go down.

## Expected Results
Server should not go down and it should not use a whole memory assigned to it.

## Steps to Reproduce
Whenever we create a new instance of realm its working fine a couple of hours as users gets incremented then the size of server also gets incremented and then its gets Stopped.

## Version of Realm and Tooling
Realm framework version: 3.18
Realm Object Server version: 3.18.1
Xcode version: 10.1
iOS/OSX version: 12.0
Pod Version : 3.10

**Comment by bmunkholm** [comment]
@sagarshirbhate I noticed you also created a support ticket and since this is not a Cocoa issue, I'll close this one.
