### ISSUE TITLE
Support updating queries in subscriptions and expose timestamps

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-cocoa#6093]
Object-store PR with functionality: realm/realm-object-store#775

We need to expose

* Being able to update the query held by a subscription.
* Be able to set the TTL when creating the subscription.
* New timestamp fields added to the subscription class.

API Proposal:
```
// To be determined
```

**Comment by tgoyne** [comment]
Implemented in https://github.com/realm/realm-cocoa/pull/6142.
