### ISSUE TITLE
Exception when trying to observe list

### ISSUE THREAD

**Issue by Pei116** [realm/realm-cocoa#6094]
RealmSwift 3.11, Xcode 10.1
I want to observe changes in the List items according to [here].(https://realm.io/docs/swift/latest#collection-notifications)

```
var devices: List<Device> = List<Device>()
// Some stuffs go here
self.subscriptionToken = self.devices.observe { [weak self] (changes) in // Exception occurs here
    guard let self = self else { return }
    self.filterDevices()
}
```
But when trying to call observe, it crashes with following exception:
*** Terminating app due to uncaught exception 'RLMException', reason: 'This method may only be called on RLMArray instances retrieved from an RLMRealm'

**Comment by ericjordanmossman** [comment]
@Pei116 

> This method may only be called on RLMArray instances retrieved **from an RLMRealm**

The second half of the error is indicating that the object has be retrieved from a realm instance. Try to retrieve the `device` from a realm via `realm.objects(Device.self)` and see if the error still throws.
