### ISSUE TITLE
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/Application/B0B94891-E949-441B-9861-0D1B89BE8B9B/Documents/default.realm.management': make_dir() failed: No such file or directory."

### ISSUE THREAD

**Issue by Mahesh160393** [realm/realm-cocoa#6098]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by bmunkholm** [comment]
@Mahesh160393 Please fill out the entire template as is clearly requested. We can't get any further without context.

**Comment by Mahesh160393** [comment]
@bmunkholm This not an issue. i am working on pdf tool when i am want to delete one pdf from /Library/Developer/CoreSimulator/Devices/E9DAFDFC-D9B8-4A0C-9584-CD09609F99EB/data/Containers/Data/Application/A8C5C88B-2767-44BA-AEF6-8A8AFA774937/Documents folder sometimes the document folder will delete. That why realm object did not get context. This is not an issue... Thank You For Replying.
