### ISSUE TITLE
Pod install is throwing this error:  Xcode specified (10.1) does not support the Swift version required: 4.2.2

### ISSUE THREAD

**Issue by chrisbull** [realm/realm-cocoa#6099]
!!! MANDATORY TO FILL OUT !!!

## Goals

To install `RealmSwift`

## Expected Results

`pod install` should install the RealmSwift pod with no errors

## Actual Results

When running `pod install` im consistently getting the following error, only when attempting to install RealmSwift

```
Installing Realm (3.13.1)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

The version of Xcode specified (10.1) does not support the Swift version required: 4.2.2
```

## Steps to Reproduce

Create an ios app and create Podfile and add `pod 'RealmSwift'`
Then `pod install`

## Code Sample

NA

## Version of Realm and Tooling

Realm framework version: 3.13.1

Realm Object Server version: NA

Xcode version: 10.1

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by tgoyne** [comment]
Swift 4.2.2 is a linux-only release of Swift. Unless you've built your own copy of the swift toolchain I have no idea how anything could be trying to use that version of swift.

This is almost certainly some sort of problem with your local environment, but I don't have any guesses as to what it could be.

**Comment by leemaguire** [comment]
Closing this issue, if you have any other questions please open a new issue.

Thanks.
