### ISSUE TITLE
Simulator Crash on realm multi-colum result.count (x86)

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-cocoa#6101]
Latest Realm (Swift)
Simulator: iPhone 7

The following code crashes on UI thread on simulator only.

`r.objects(RealmObj.self).filter(RealmObj.COLUMN_INT64One + " > " + RealmObj.COLUMN_INT64Two).count
`

However, the following does not crash. Notice we just appended an extra predicate in front.

`r.objects(RealmObj.self).filter(RealmObj.COLUMN_INT64One + " > 0 AND " + RealmObj.COLUMN_INT64One + " > " + RealmObj.COLUMN_INT64Two).count
`

This very strange and suspect there is something wrong the x86 compilation within realm that is causing this since simulator is x86 only.

    0x10b1be1ca <+330>: movq   %r15, %rdx
    0x10b1be1cd <+333>: callq  0x10b1bda60               ; realm::Query::do_count(unsigned long, unsigned long, unsigned long) const
    0x10b1be1d2 <+338>: movq   %rax, %r14 <--- crash

Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

**Comment by diegomontoya** [comment]
Correction. With or without the extra predicate the multicolumn compare crashed. So it is not related to predicate order but directly related to multicolumn compare.

**Comment by diegomontoya** [comment]
The crash is somewhat random. Occurs 100% of the time on our iPhone 7 simulator with simple column1 > column2 int64 compare predicate. However, adding other predicates in from of the mul-column match somehow alleviates the crash but only to some extent. 

For example, the following rarely crash:

`r.objects(RealmObj.self).filter(RealmObj.COLUMN_INT64One + " > 0 AND  RealmObj.COLUMN_INT64Two + " > 0 AND" + RealmObj.COLUMN_INT64One + " > " + RealmObj.COLUMN_INT64Two).count`

**Comment by tgoyne** [comment]
Can you share complete code which reproduces this? It's plausible that we have a bug here, but we do have tests for this functionality that run under asan and valgrind.

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
