### ISSUE TITLE
Deprecate isPartial in the sync configuration and update docs

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-cocoa#6108]
The 'isPartial' option here: https://realm.io/docs/swift/3.13.1/api/Structs/SyncConfiguration.html#/s:10RealmSwift17SyncConfigurationV9isPartialSbvp
and here: https://realm.io/docs/objc/3.13.1/api/Classes/RLMSyncConfiguration.html#/c:objc(cs)RLMSyncConfiguration(py)isPartial
must be deprecated to match the "Query Based Sync" terminology used now.

**Comment by tgoyne** [comment]
Those were marked as deprecated in 3.7.0 when we added the fullSynchronization option to replace them.

**Comment by bmunkholm** [comment]
Oh great. We can at least remove the warning now though

**Comment by tgoyne** [comment]
What? Why would we remove the deprecation warning?

**Comment by bmunkholm** [comment]
No not remove the deprecation warning - just the 
" -warning: Partial synchronization is a tech preview. Its APIs are subject to change."

Btw, while the deprecation warning shows up in xcode, there is nothing in the docs that says it's deprecated.

**Comment by tgoyne** [comment]
The deprecation warning is not appearing in the generated HTML docs because the current version of the docs was generated with a fairly old version of jazzy. The updated CI VMs have the newest version of jazzy, so they'll appear once we make a new release.

**Comment by jsflax** [comment]
This is no longer valid with the v10 MongoDB Realm beta, as the above functionality is now deprecated.
