### ISSUE TITLE
Debug configuration will not build through Carthage

### ISSUE THREAD

**Issue by mc7h** [realm/realm-cocoa#6109]
## Goals
Build debug configuration of Realm via Carthage. It is useful to build debug frameworks  so that you can get logs, asserts and "step into" third-party code whilst debugging. 

## Expected Results

Executing: `carthage update --platform iOS --configuration Debug` against `realm-cocoa` dependency should produce two debug frameworks: `Realm.framework` and `RealmSwift.framework`. 

## Actual Results

Command fails with:
```
ld: bitcode bundle could not be generated because 'core/librealm-ios-dbg.a(bptree.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
```

## Steps to Reproduce
1. Create `Cartfile` with `realm-cocoa` dependency.
2. `carthage update --platform iOS --configuration Debug`

(Release config is, obviously, absolutely fine)

## Code Sample

I have managed to get everything building with the following workaround:
1. `carthage update --no-build`
2. Manually edit the xcconfig files under Carthage/Checkouts/realm-cocoa to turn off bitcode (ENABLE_BITCODE=NO) for  both Realm and RealmSwift targets.
3. `carthage build --no-use-binaries --configuration Debug --platform ios`

Tidying up the Debug configuration and disabling bitcode should fix the issue. I don't see any problem with disabling bitcode for code that won't be shipped.

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

/Applications/Xcode.app/Contents/Developer
Xcode 10.1
Build version 10B61

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

/usr/local/bin/carthage
0.32.0
github "realm/realm-cocoa" "v3.13.1"

/usr/bin/git
git version 2.17.2 (Apple Git-113)
```

**Comment by pavel-ship-it** [comment]
Cannot reproduce on
Realm 5.4.7
Carthage 0.36.0
