### ISSUE TITLE
'dynamic' property '' must also be '@objc'

### ISSUE THREAD

**Issue by shabirjan** [realm/realm-cocoa#6114]
Facing an issue after I updated Xcode to 10.2 which Contain Swift 5 on this line of code:

`dynamic let openingHours = List<ShopHourRealm>()`
and the error is 
> 'dynamic' property 'openingHours' must also be '@objc'

Even i tried adding **@objc** like this 
`@objc dynamic let openingHours = List<ShopHourRealm>()` 

but than i got this error:

> Property cannot be marked @objc because its type cannot be represented in Objective-C

Before I updated my Xcode the same line of code was working fine.

## Goals
I should be able to use **ShopHourRealm** as _List_ in my **ShopRealm**. i.e 
`dynamic let openingHours = List<ShopHourRealm>()`

## Expected Results
I should not get any errors

## Actual Results
And If I add **@objc** , a new error appears

> Property cannot be marked @objc because its type cannot be represented in Objective-C

## Code Sample
This is the **ShopHourRealm** object which is declared with **@objcMember** and every property is marked with **dynamic**. I tried changing **objcMember** to **@objc** and changed **dynamic** to **@objc** as well. But the error remained same.
```
@objcMembers class ShopHourRealm: Object {
    dynamic var weekDayId: Int = -1
    dynamic var weekName: String = ""
    dynamic var openingHour: String = "Lukket"
    dynamic var closingHour: String = "Lukket"
    
    convenience init(shopHour value: ShopHourDTO) {
        self.init()
        weekDayId = value.weekDayId
        
        weekName = value.weekName
        if let openingHr = value.openingHour, let closingHr = value.closingHour {
            openingHour = openingHr
            closingHour = closingHr
        }
    }
}
```

Above Realm Object is used like this:

```
@objcMembers class ShopRealm: Object {
    dynamic var shopID: String = "0"
    dynamic var shopName: String = ""
    dynamic var latitude: Double = 0.0
    dynamic var longitude: Double = 0.0
    dynamic var shopStreet: String = ""
    dynamic var shopZipcode: String = ""
    dynamic var city: String = ""
    dynamic var imageURL: String?
    dynamic let openingHours = List<ShopHourRealm>() // This is line where I am getting this error.
    }
```

## Version of Realm and Tooling

Realm framework version: ?
3.13.1
Xcode version: ?
10.2

iOS/OSX version: ?
iOS 12.2

Dependency manager + version: ?
CocoaPods: 1.5.3

**Comment by nikolay-kapustin** [comment]
I found some workaround. Just remove dynamic keyword and error is gone.

**Comment by shabirjan** [comment]
Yes @nikolay-kapustin  Thanks, I realized I don't have to use dynamic with List.

**Comment by hjh5696** [comment]
Thanks for workaround! 
So is it because Xcode 10.2 changed something on dynamic keyword?

**Comment by kos9kus** [comment]
We are waiting for decent answer, it looks like a magic, what will I expect if I use a class it in objc code ?
