### ISSUE TITLE
Realm() init expensive on CPU

### ISSUE THREAD

**Issue by anansi** [realm/realm-cocoa#6124]
## Goals

I want to launch an instance of Realm without creating processing overhead in Realms initialisation procedure. 

## Expected Results

I expect the Realm() instance to have a minimal initialisation time and CPU cost.

## Actual Results

I see that Realm called the shouldCompactOnLaunch() function of the config, every time I call Realm(). I also have iOS energy crash logs because of Realm() initialising. Although, this, may be 2 separate initialisation performance overhead bugs.

## Steps to Reproduce

Init a Realm() instance, observe that the shouldCompactOnLaunch function is called. I use iOS DispatchQueue's. One dispatchqueue is created for my bluetooth data to be received, then it calls the function from the code snippet below.

## Code Sample

    private var _realm: Realm {
        return try! Realm()
    }
    
    internal func insertPicoStatData(_ picoStatData: PicoStatData) {
        
        self.picoStatDataWriteQueue.async {
            autoreleasepool {
                let realm = self._realm
                defer { realm.invalidate() }
                try! realm.write {
                    // DVG CHECK THE DIFF!!!
                    //realm.add(picoStatData, update: true)
                    realm.create(PicoStatData.self, value: picoStatData, update: false)
                }
            }
            
            // Pass only if anybody is watching
            if (!self._rx_picoStatDataSubject.isDisposed && self._rx_picoStatDataSubject.hasObservers
                && picoStatData.statDataType == StatDataType.DataType.primary) {
                self._rx_picoStatDataSubject.onNext(picoStatData)
            }
            
            let foreground = UserDefaults.standard.bool(forKey: "app_in_foreground")
            if foreground   {
                // Pass only if anybody is watching
                if (!self._rx_picoStatDataForegroundSubject.isDisposed && self._rx_picoStatDataForegroundSubject.hasObservers
                    && picoStatData.statDataType == StatDataType.DataType.primary) {
                    self._rx_picoStatDataForegroundSubject.onNext(picoStatData)
                }
            }
            
        }
    }
    
## Time Profiler Snippet
![image](https://user-images.githubusercontent.com/84054/55711988-2e933a80-59ee-11e9-9ed3-4cdddd6649d1.png)

## Version of Realm and Tooling

Realm framework version: ?
Realm (3.9.0)
RealmSwift (3.9.0)

Realm Object Server version: ?
Not in my Podfile or project. (unless Realm imports it itself?)

Xcode version: ?
Xcode 10.1
Build version 10B61

iOS/OSX version: ?
iOS 12.2  but I see this issue on many iOS builds

Dependency manager + version: ?
CocaoPods 1.5.3

**Comment by leemaguire** [comment]
Hi @anansi 

A compaction may be expensive if the Realm file is quite large. 

Also note that 'compaction will be skipped even if the configuration block’s conditions were met. That’s because compaction cannot be safely performed while a Realm is being accessed.' So ensure your Realm if not being accessed by your Bluetooth functionality while the compaction is performing. 

See more here: https://realm.io/docs/swift/latest/#compacting-realms

Thanks,
Lee
