### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by Menrol** [realm/realm-cocoa#6128]
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 3.13.3
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-3.13.3.tar.xz
	curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by bmunkholm** [comment]
I assume you have come past this by now? If not please reopen and fill out the entire issue template. Thanks!
