### ISSUE TITLE
Confused by RealmCollectionChange behavior

### ISSUE THREAD

**Issue by bmt2018** [realm/realm-cocoa#6130]
## Goals
I'm sure that collection change notifications are working as intended but I'm a little confused by some behavior that I'm seeing.  I have an object that I store in Realm, let's called it a widget.  I want to know any time a new widget is inserted into the Realm so I can notify my user with a badge, sound, haptic feedback, etc.  To achieve this, I declare the following in my AppDelegate:

`var results: Results<Widget>!`

In application(_:didFinishLaunchingWithOptions:), I define my results like this:

`results = realm.objects(Widget.self) // unsorted`

I then use a notification token to observe the results for changes and print out the number of deletions, insertions and modifications.

Elsewhere in my app, I have a view controller with a table view which displays all of the widgets (sorted by a "name" property).  My view controller defines the following:

`var results: Results<Widget>!`

in viewDidLoad(), I define results like this:

`results = realm.objects(Widget.self).sorted(byKeyPath: "name")`

If I delete a widget from the table view, the results observer in my view controller shows:

1 deletion
0 insertions
0 modifications

But the results observer in AppDelegate often shows:

2 deletions
1 insertion
0 modifications

I believe this behavior stems from the fact that the results in my AppDelegate are not sorted while the results in my view controller are sorted by the "name" property.

## Expected Results
I expected to see 1 deletion in my view controller and 1 deletion in my AppDelegate.

## Actual Results
I always see 1 deletion in my view controller but in my AppDelegate, I *often* see:

2 deletions
1 insertion
0 modifications

Sometimes, however, the AppDelegate will show the same thing as the view controller (which is to say, 1 deletion and nothing else).

If I sort the results in my AppDelegate (as I do in my view controller), then the RealmCollectionChange results are consistent between the two observers.  Again, I assume that this is working as intended and I just don't quite understand the 2 deletions and 1 insertion that are usually indicated by the results observer in the AppDelegate.  Where does the "extra" deletion come from?  And why is there an insertion?  Is it just the unsorted results being re-arranged following the delete of a single widget?

## Code Sample
I posted this on SO a few months ago but never got any replies.  Source is included in that question at: https://stackoverflow.com/questions/53211113/observing-changes-to-realm-result-set

## Version of Realm and Tooling
Realm framework version: 3.14.1
Xcode version: 10.2
iOS version: 12.2
Dependency manager + version: Cocoapods 1.6.1

**Comment by tgoyne** [comment]
Yes, unsorted results are rearranged when objects are deleted. If you don't ask for an explicit sort order, then the objects are simply listed in the order that they happen to be stored on disk, and that is an unstable order that changes when objects are deleted.

We currently report the object at the end moving to the place of a deleted object as that object also being deleted and then inserted in the new location.

**Comment by bmt2018** [comment]
@tgoyne thanks very much for the explanation!  That explains the behavior that I'm seeing.
