### ISSUE TITLE
Getting “Adding a deleted or invalidated object to a Realm is not permitted” from realm

### ISSUE THREAD

**Issue by vm-dasglobtech** [realm/realm-cocoa#6131]
I have used the realm in one of my projects and added Firebase to identify the crashes. Now, in one of the crash, I am getting "Adding a deleted or invalidated object to a Realm is not permitted" in Firebase but did not get more details. I have used below code everywhere, where I am trying to delete the object from the realm.

```
let realm = try! Realm()

            do {
                try realm.write {
                    realm.delete(object)
                }
            } catch let error as NSError {
                // handle error
                Crashlytics.sharedInstance().setObjectValue(error.localizedDescription, forKey: "key")
            }
```
Am I missing anything?

Thank you for your help

**Comment by leemaguire** [comment]
Hi @vm-dasglobtech,

As the error is describing. the `object` you are trying to delete is most likely not managed by a Realm object hence why you are getting this issue. We would need to see more of your code in order to understand your issue better.

Thanks,
Lee
