### ISSUE TITLE
Notification after all results in realm are updated in run loop

### ISSUE THREAD

**Issue by ahammad94** [realm/realm-cocoa#6135]
Currently I have a composite collection of results that observes all their respective changes. The problem I'm facing is that all the results are updated at first but only one result is notified at a time iteratively in the respective run loop. 

## Goals
Be able to identify when the last result has been updated so that I can push the aggregate updates of all the internal results to the UI on the execution of this runloop

## Expected Results
Realm notification that is sent at the end of the runloop when all the results have been iteratively updated

**Comment by leemaguire** [comment]
Hi @ahammad94 we need to see a code sample of how you are using Realm in order to advise you further.

Thanks,
Lee

**Comment by ericjordanmossman** [comment]
Closing because inactivity.
