### ISSUE TITLE
Use of unresolved identifier 'Realm'

### ISSUE THREAD

**Issue by PulkitAppz** [realm/realm-cocoa#6137]
**Questions**: How to resolve this error in swift while using objective-C realm? 

## Goals
  I have objective-C project, in which I have swift file. I am want to use realm in that class. But getting error after doing all the steps as mentioned in documentation. I have also added RLMsupport.swift in my project.

## Actual Results
Use of unresolved identifier 'Realm' at this line  " let realm = try! Realm()" in my swift class.

## Code Sample
 func setRealm(){
        
        // Use them like regular Swift objects
        let myDog = Dog()
        myDog.name = "Rex"
        myDog.age = 1
        print("name of dog: \(myDog.name)")
        

        // Get the default Realm
        let realm = try! Realm() ----------> Use of unresolved identifier 'Realm'
        
        // Query Realm for all dogs less than 2 years old
        let puppies = realm.objects(Dog.self).filter("age < 2")
        print(puppies.count)// => 0 because no dogs have been added to the Realm yet
        
        // Persist your data easily
        try! realm.write {
            realm.add(myDog)
        }
        
        // Queries are updated in realtime
        print(puppies) // => 1
    }

## Version of Realm and Tooling

Realm framework version: 3.14.0

Realm Object Server version: NA

Xcode version: 10.1

iOS/OSX version: 12

Dependency manager + version: NA

**Comment by tgoyne** [comment]
The code sample is using the Swift API, which is different from using the obj-c API from Swift. In a mixed obj-c/swift project you need to use the obj-c API in both languages, i.e. continue to use RLMRealm etc.
