### ISSUE TITLE
data missing

### ISSUE THREAD

**Issue by bassamyan** [realm/realm-cocoa#6140]
i use realm as my app's local database for almost 6 months, and i changed the structure of models for many times.
and i test the migration process for a lot of times with no error. However, when i send the new versions to the apple store, many users complains the data which stored in the realm database is missing.
it happens for many times already, does any one has the same problem? or just i write the wrong code for migration.

**Comment by ppamorim** [comment]
@bassamyan Is your database encrypted?

**Comment by do784208** [comment]
I has same problem, and realm version is 3.14.2.

**Comment by do784208** [comment]
ok,  I know the reason now.
 
when databse ranmed property, need to check table version

https://stackoverflow.com/questions/42251736/realm-version-migration-renaming-property-not-existed/43164882#43164882
