### ISSUE TITLE
realm::_impl::ExternalCommitHelper::~ExternalCommitHelper() (external_commit_helper.cpp:194)

### ISSUE THREAD

**Issue by ganesh-ananthan** [realm/realm-cocoa#6145]
!!! MANDATORY TO FILL OUT !!!

## Goals
Application should not crash.

## Expected Results
Realm should be accessible and app should not crash.

## Steps to Reproduce
Not sure

## Code Sample
Not applicable.

## Version of Realm and Tooling

Realm framework version: 'RealmSwift', '~> 3.14.1'

Realm Object Server version:

Xcode version: 10.1 (10B61)

iOS version: 10.3.3 and above all.

Dependency manager + version: Cocoapod

**Comment by bmunkholm** [comment]
@ganesh-ananthan This is impossible to debug without further information. Can you please provide the full stacktrace?

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
