### ISSUE TITLE
Folders are incorrectly named in the precompiled binaries

### ISSUE THREAD

**Issue by davidpasztor** [realm/realm-cocoa#6146]
## Goals

Have correctly named folders representing the Swift compiler version used for compiling the specific Realm frameworks when downloading the [precompiled frameworks](https://static.realm.io/downloads/swift/realm-swift-3.15.0.zip).

## Expected Results

Swift versions are correct in the folder names.

## Actual Results

Folders are incorrectly named, i.e.: `swift-9.2`, `swift-10.2.1`.

## Steps to Reproduce

1. [Download](https://static.realm.io/downloads/swift/realm-swift-3.15.0.zip) the precompiled frameworks from the official website.
2. Open one of the framework folders, i.e: `realm-swift-3.15.0/ios`
3. Check folder names

## Version of Realm and Tooling

Realm framework version: 3.15.0

Realm Object Server version: N/A

Xcode version: N/A

iOS/OSX version: N/A

Dependency manager + version: precompiled binary

**Comment by tgoyne** [comment]
They're now named after the Xcode version they're built with rather than the Swift version because we no longer support any versions of Xcode which require separate builds for the various versions of Swift they support.

**Comment by davidpasztor** [comment]
@tgoyne the folders are still incorrectly named. They should be changed to xcode-version then, not swift-xcodeversion.
