### ISSUE TITLE
bad wifi  set db version  can not enter app

### ISSUE THREAD

**Issue by luckycherry** [realm/realm-cocoa#6155]
let config = Realm.Configuration(
            // Set the new schema version. This must be greater than the previously used
            // version (if you've never set a schema version before, the version is 0).
            schemaVersion: UInt64(version),
            
            // Set the block which will be called automatically when opening a Realm with
            // a schema version lower than the one set above
            migrationBlock: { migration, oldSchemaVersion in
                // We haven’t migrated anything yet, so oldSchemaVersion == 0
                if (oldSchemaVersion < 1) {
                    // Nothing to do!
                    // Realm will automatically detect new properties and removed properties
                    // And will update the schema on disk automatically
                }
        })
        
        // Tell Realm to use this new configuration object for the default Realm
        Realm.Configuration.defaultConfiguration = config

the code in didFinishLaunchingWithOptions

the wifi have not network

**Comment by bmunkholm** [comment]
@luckycherry From this description it's not clear what your issue is - can you please use the issue template and provide more details?
Thanks!

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
