### ISSUE TITLE
Support Project Catalyst/UIKitForMac

### ISSUE THREAD

**Issue by rjchatfield** [realm/realm-cocoa#6165]
## Goals
Compile and use Realm for iOS in a Project Catalyst (iPad app for macOS) project. 

## Expected Results
Currently it compiles, but it just hung when we tried. It should work as it always does ;)

**Comment by iPhoNewsRO** [comment]
how did you got it running? i keep getting

> building for UIKitForMac, but linking in object file built for iOS Simulator, for architecture x86_64
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jlubeck** [comment]
Probably with this: https://github.com/realm/realm-cocoa/pull/6164

I'm getting the same errors as @iPhoNewsRO but I'll see if I can try that pull request

**Comment by rjchatfield** [comment]
This is a dupe of the #6163 (which seems like a huge ticket!)
