### ISSUE TITLE
UICollectionView crashing when updating via Realm collection change

### ISSUE THREAD

**Issue by bmt2018** [realm/realm-cocoa#6166]
## Goals
I'm trying to update (modify, delete, insert) my Realm objects and have a UICollectionView that is used to display the Realm objects update accordingly.

## Expected Results
The UICollectionView to update accordingly.

## Actual Results
The app crashes with the following error:

```
[CollectionView] An attempt to prepare a layout while a prepareLayout call was already in progress (i.e. reentrant call) has been ignored. Please file a bug. UICollectionView instance is (<MessageKit.MessagesCollectionView: 0x10c01b400; baseClass = UICollectionView; frame = (0 0; 414 896); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2830aa670>; layer = <CALayer: 0x283ea44a0>; contentOffset: {0, 137}; contentSize: {414, 604}; adjustedContentInset: {88, 0, 429, 0}> collection view layout: <MessageKit.MessagesCollectionViewFlowLayout: 0x10b7069d0>)
[CollectionView] An attempt to update layout information was detected while already in the process of computing the layout (i.e. reentrant call). This will result in unexpected behaviour or a crash. This may happen if a layout pass is triggered while calling out to a delegate. UICollectionViewFlowLayout instance is (<MessageKit.MessagesCollectionViewFlowLayout: 0x10b7069d0>)
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'

```

## Steps to Reproduce
I'm using Realm together with the [MessageKit](https://github.com/MessageKit/MessageKit) framework to implement chat in my app.  For anyone who might not have used MessageKit before, it uses a UICollectionView internally and each chat message is placed into it's own section of the collection view.

My chat message model looks like this:

```
class ChatMessage: Object {
    
    @objc dynamic var id: Int = generateMessageId()
    @objc dynamic var timestamp = Date()
    @objc dynamic var senderId: Int = -1    
    @objc dynamic var text: String = ""

    var recipients = List<Recipient>()

    @objc dynamic var receivedByServer = false
    var readReceipts = List<Recipient>()
}

```

And I have an array of chat messages declared like this:

```
var messages: Results<ChatMessage>!
// and later in viewDidLoad()...
messages = conversation.messages.sorted(byKeyPath: "timestamp", ascending: true)

```

This array serves as the data source for the UICollectionView underlying MessageKit.  I'm observing this array for changes and when I detect that a change occurred, I'm updating the sections of the UICollectionView accordingly like this:

```
notificationToken = messages.observe { [weak self] (changes: RealmCollectionChange) in
    switch changes {
    case .initial:
        print("Messages collection has been populated...")
    case .update(_, let deletions, let insertions, let modifications):
        print("Messages collection has been updated...")
        self?.messagesCollectionView.performBatchUpdates( {
            if modifications.count > 0 {
                print("modifications count: \(modifications.count)")
                self?.messagesCollectionView.reloadSections(IndexSet(modifications))
            }
            if deletions.count > 0 {
                print("deletions count: \(deletions.count)")
                self?.messagesCollectionView.deleteSections(IndexSet(deletions))
            }
            if insertions.count > 0 {
                print("insertions count: \(insertions.count)")
                self?.messagesCollectionView.insertSections(IndexSet(insertions))
            }
        }, completion: { [ weak self] _ in
            print("Scroll to bottom of UICollectionView...")
            self?.messagesCollectionView.scrollToBottom(animated: true)
        })
    case .error(let error):
        print("Error occurred while observing messages: \(error)")
    }
}

```

Initially, this code seemed to be working ok but then I started seeing an issue that appears to be related to multiple updates occurring very quickly. For example, when I send a chat message, the server will acknowledge that the the message was received which will cause the chat message object to be modified. When a recipient reads the message, that, too, will cause the chat message object to be updated. In some cases, these two events occur together very quickly and I believe that my code that calls `messagesCollectionView.reloadSections(IndexSet(modifications))` will be run twice. It seems like the second call actually occurs while the first call is still being processed and this results in a crash.  Or at least I believe that's what is causing the problem.

Is this the proper way to update a UICollectionView when using a Realm collection as the data source and observing that collection for changes or am I doing this all wrong?  On a side note, I'm updating sections (vs items) because MessageKit puts each chat message into it's own section by default.

## Version of Realm and Tooling
Realm framework version: 3.16.1
Xcode version: 10.2
iOS/OSX version: 12.3.1
Dependency manager + version: CocoaPods 1.7.1

**Comment by jsflax** [comment]
Hmm... could you try dispatching your UI changes synchronously to the main thread? Doing that serially should clear up the reentrant issue.

**Comment by ericjordanmossman** [comment]
Closing.
See recommendation above ^.
