### ISSUE TITLE
Memory Leaks when try to get Count of RLMResults

### ISSUE THREAD

**Issue by dharmendra-ios** [realm/realm-cocoa#6167]
## Steps to Reproduce
Get all data from table and store in RLMResults type object. After that trying to Get Count of RLMResutls object and get memory leak. Please see attached screenshots for reference.

## Code Sample
[(RLMResults *)[arrEvents objectAtIndex:section] count];

## Version of Realm and Tooling

Realm framework version: 3.16.1

Xcode version: 10.1

iOS/OSX version: 12.2

![Screenshot 2019-06-05 at 6 07 36 PM](https://user-images.githubusercontent.com/16112306/58956821-f2e1da80-87bc-11e9-9cfd-eddee7a09b2e.png)
![Screenshot 2019-06-05 at 6 09 05 PM](https://user-images.githubusercontent.com/16112306/58956855-07be6e00-87bd-11e9-96e0-de8e8771084e.png)

**Comment by ppamorim** [comment]
Can you give more source code?

**Comment by dharmendra-ios** [comment]
Following is the sample code where I get memory leak when I try to get count of Events List.


NSPredicate *predicate1 = [NSPredicate predicateWithFormat:@"SUBQUERY(events_eventsusers_relation,$eventsusers,$eventsusers.user_id == %@ AND $eventsusers.status == %@).@count > 0",currentUser.ids,Kvalidated];

NSPredicate *predicate2 = [NSPredicate predicateWithFormat:@"SUBQUERY(events_eventssessions_relation,$eventssessions, $eventssessions.status == %@ AND $eventssessions.end_date >= %@).@count > 0",Kvalidated,[NSDate date]];
RLMResults *arrEvents = [[Events objectsWithPredicate:[NSCompoundPredicate andPredicateWithSubpredicates:@[predicate1,predicate2]]]; sortedResultsUsingKeyPath:@"eventsSessionMinDate" ascending:YES]
NSLog(@"Upcoming Events Count %ld",(long)[arrEvents  count]);

For instance please see attached Screenshot. 

![Screenshot 2019-06-06 at 11 48 59 AM](https://user-images.githubusercontent.com/16112306/59011079-19515580-8851-11e9-9d79-322e2ffb095c.png)

**Comment by Mehdzor** [comment]
@dharmendra-ios did you have this issue before? On earlier realm versions. 
Because all my subqueries just went mad after updating.

**Comment by dharmendra-ios** [comment]
@Mehdzor I don't know the exact realm version. But I getting this memory leak. If you could provide any solution then it would be helpful.

**Comment by dharmendra-ios** [comment]
Mainly SUBQUERY causes memory leak.

**Comment by ironage** [comment]
Thanks for your report. We've identified and fixed a memory leak, which I believe is also the one you report here. Please try out the fix in cocoa version v3.17.1.
