### ISSUE TITLE
在Xcode11 运行 构建Realm 表的时候 字符串类型的字段无法构建

### ISSUE THREAD

**Issue by yushuyi** [realm/realm-cocoa#6168]
代码如下：
    @objc dynamic var cloudId  : String = UUID().uuidString
跟下来 发现 
内部判断 isComputed 会被判断为 YES 导致无法有效构建 但实际上它不是一个只读字段

unsigned int count;
    objc_property_attribute_t *attrs = property_copyAttributeList(property, &count);

iOS 12
count = 4
T N C V

iOS 13
count = 3
T N C

**Comment by cddjr** [comment]
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'tg/xcode-11-b1', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'tg/xcode-11-b1', submodules: true

使用这个分支的代码可兼容swift5.1

**Comment by bmunkholm** [comment]
@yushuyi Unfortunately we are only able to support in English.

**Comment by yushuyi** [comment]
@bmunkholm   cddjr has  help me solve the problem
