### ISSUE TITLE
Crash on try! Realm() with XCode 11 Beta iOS 13

### ISSUE THREAD

**Issue by patchthecode** [realm/realm-cocoa#6170]
Using realm 3.16.1
iOS
Swift 5

I have an empty project.
This is my code
```swift
 override func viewDidLoad() {
        super.viewDidLoad()
        
        let x = try! Realm()
    }
```

App crashes:
```
019-06-07 06:45:56.429052-0400 RealmTest[37738:5602779] *** Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'name' does not exist on object 'RealmSwiftClassPermission''
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104477b6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x000000010321cf57 objc_exception_throw + 48
...
```

Here is the zipped project:  [RealmTest.zip](https://github.com/realm/realm-cocoa/files/3265603/RealmTest.zip)

Any thing i am doing wrong?

**Comment by jsflax** [comment]
Hi @patchthecode ,

I've opened up your project and ran it, and it seems to work fine for me.

What versions of XCode/iOS are you on? I'm using XCode 10.2.1 and iOS 12.

**Comment by patchthecode** [comment]
OK.

I see now.
I loaded up XCode 10.2.1 and it works.
I guess i should re-title this to say: **Crash with Xcode 11 Beta iOS 13**

Because this is the platform on which it is crashing.

**Comment by tgoyne** [comment]
3.16.1 does not support Xcode 11. See https://github.com/realm/realm-cocoa/issues/6163 for using Realm with Xcode 11.

**Comment by patchthecode** [comment]
Thanks. Issue is resolved on the master branch,
