### ISSUE TITLE
Crash on Xcode 11 beta 1. I got Primary key property 'name' does not exist on object 'RealmSwift Class Permission'

### ISSUE THREAD

**Issue by andriypohorilko** [realm/realm-cocoa#6173]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by nirinchev** [comment]
This appears to be a duplicate of https://github.com/realm/realm-cocoa/issues/6163. Please review the workarounds posted there.
