### ISSUE TITLE
Query and insert data is not the same .realm file used

### ISSUE THREAD

**Issue by ameue** [realm/realm-cocoa#6174]
!!! MANDATORY TO FILL OUT !!!

## Goals

How I use it:
When I create xxx.realm via [[xxxDBManager shared] setup], when I save the data using the -addObject method, I can see that the data is saved in the xxx.realm file.
But when I use -list to query the data, I see a new default.realm file created under the ../Document/ folder, and the query data is nil.

hope:
I hope that when I use the -list query, I am querying the saved data in the xxx.realm file instead of creating a default.real.
## Code Sample

setting:

@interface xxxDBManager : NSObject

@property (nonatomic, strong) RLMRealm *realm;
@property (nonatomic) dispatch_queue_global_t access_queue;
@property (nonatomic) dispatch_queue_t queue;

+ (instancetype)shared;
- (void)setup;

@end

@implementation xxxDBManager

+ (instancetype)shared {
    static xxxDBManager *manager;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        manager = [[self alloc] init];
    });
    return manager;
}

- (instancetype)init
{
    self = [super init];
    if (self) {
        self.access_queue = dispatch_get_global_queue(0, 0);
        self.queue = dispatch_queue_create("com.concurrent.queue", DISPATCH_QUEUE_CONCURRENT);
    }
    return self;
}

- (void)setup {
    
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    NSString *realmPath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
    realmPath = [realmPath stringByAppendingPathComponent:@"xxx.realm"];
    config.fileURL = [NSURL URLWithString:realmPath];
    dispatch_async(self.queue, ^{
        NSError *error;
        self.realm = [RLMRealm realmWithConfiguration:config error:&error];
        if (error) {
            NSLog(@"realm configuration error:%@", error.localizedDescription);
        }
    });
}

query:
+ (RLMArray<xxxModel *> *)list {
    RLMResults<xxxModel *> *all = [xxxModel allObjects];
    if (all.count > 0) {
        RLMArray *array = [[RLMArray alloc] initWithObjectClassName:all.objectClassName];
        [array addObjects:all];
        return array;
    }
    return nil;
}

save:
- (void)addObject {
    xxxModel *model = [[xxxModel alloc] init];
    model.url = xxxURL;
    model.parameter = parameters;
    [model addObject:model];
    RLMRealm *realm = [ReporterDBManager shared].realm;
    dispatch_async([ReporterDBManager shared].queue, ^{
        [realm transactionWithBlock:^{
            [realm addObject:model];
        }];
    });
}
## Version of Realm and Tooling

Realm framework version: ?
3.16.1
Realm Object Server version: ?

Xcode version: ?
10.14
iOS/OSX version: ?
ios12
Dependency manager + version: ?

**Comment by tgoyne** [comment]
`[xxxModel allObjects]` returns all objects of that type in the default Realm, which is not the Realm you added the objects to. You need to either read from that Realm (using `[xxxModel allObjectsInRealm:ReporterDBManager.shared.realm]`) or set the default Realm configuration in `setup` to be your specific Realm.

`dispatch_async(queue, ^{ [realm transactionWithBlock:^{ ... }]; });` also does not work. Realm objects are thread-confined, and dispatch queues are not tied to any particular thread. Instead you must open the Realm inside the dispatched block.

**Comment by ameue** [comment]
Thank you for your reply, my idea is to let the data increase, delete, change, check are executed in the child thread, what should I do
