### ISSUE TITLE
Unsupported Swift Version in iOS example swift-10.1, on Xcode 10.2.1

### ISSUE THREAD

**Issue by peterkos** [realm/realm-cocoa#6183]
## Goals

Provide a version of the Realm Swift iOS example code that can run on Xcode 10.2.1 match the framework's corresponding version in swift-10.2.1. 

## Expected Results

Run Realm Swift iOS example playground in the provided .xcworkspace

## Actual Results

Xcode reported that the version of Swift used in RealmSwift is unsupported in Xcode 10.2 or later.
<img width="446" alt="Screen Shot 2019-06-18 at 2 09 13 PM" src="https://user-images.githubusercontent.com/2782749/59720453-c0c87380-91d3-11e9-9c96-3aeea56bfdc2.png">

## Steps to Reproduce

Navigate to `examples/ios/swift-10.1`, and open the `RealmExamples.xcworkspace` file in Xcode 10.2 or later.
## Code Sample

N/A

## Version of Realm and Tooling

Realm framework version: 3.16.2

Realm Object Server version: N/A

Xcode version: 10.2.1

iOS/OSX version: 12.2

Dependency manager + version: N/A (example code directly from Realm site)

**Comment by peterkos** [comment]
I've tried manually updating the example version myself (duplicating the project, linking to the `swift-10.2.1` RealmSwift framework, and updating the Swift version to 4.2.1 in all projects' Build Settings), however this causes a different issue:
`Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler`

**Comment by jsflax** [comment]
I don't believe this is still an issue.
