### ISSUE TITLE
Swiftui module importing failed, Xcode beta 3

### ISSUE THREAD

**Issue by Stoneman790** [realm/realm-cocoa#6197]
I am trying to use Realm with Swiftui.  I initially had an issue with Swiftui List and Realm List, but solved that while using Xcode beta 2.  
Everything was working until upgrading to Xcode beta 3.

## Goals
Run the app

## Expected Results
 Expected the app to run like it did in Xcode  beta 2

## Actual Results

I then got this error when trying to run the app:  

error: module importing failed: invalid token (rlm_lldb.py, line 37)
  File "temp.py", line 1, in <module>

libsystem_kernel.dylib`mach_msg_trap:
    0x7fff510e838c <+0>:  movq   %rcx, %r10
    0x7fff510e838f <+3>:  movl   $0x100001f, %eax          ; imm = 0x100001F 
    0x7fff510e8394 <+8>:  syscall 
->  0x7fff510e8396 <+10>: retq   
    0x7fff510e8397 <+11>: nop    

The app hangs at that point.

## Steps to Reproduce
Try to run the app.

## Code Sample
I believe the app hangs before much code has run.

The code was working prior to the Xcode update.

## Version of Realm and Tooling

I am using the latest versions of Realm (3.17.0), Xcode 11 beta 3, Catalina (10.15 Beta (19A501i), CocoaPods (1.7.3)

/Applications/Xcode.app/Contents/Developer

** This is not the correct version of Xcode.  See above.  I have two versions installed.**

Xcode 10.2.1
Build version 10E1001

/usr/local/bin/pod
1.7.3
Realm (3.17.0)
RealmSwift (3.17.0)
Realm (from `https//github.com/realm/realm-cocoa.git`, branch `master`)
RealmSwift (from `https//github.com/realm/realm-cocoa.git`, branch `master`)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

carthage not found
(not in use here)

/usr/local/bin/git
git version 2.7.1
```

**Comment by Stoneman790** [comment]
The issue seems to have solved itself with updates of Xcode, and iOS 13 betas as of July 9th. One thing that helped was creating a new project, copying the contents of the SceneDelegate, and pasting it into the existing project.

**Comment by BillinX** [comment]
I have met the similar problem when using SwiftUI Xcode Version 11 Beta 5(Version 11.0 beta 5 (11M382q))

error: module importing failed: invalid token (rlm_lldb.py, line 37)
  File "temp.py", line 1, in <module>

**Comment by Stoneman790** [comment]
The error still shows in the console but the app seems to run fine.  If your app is not running there is probably another issue.
