### ISSUE TITLE
write crash

### ISSUE THREAD

**Issue by vojtechvosmik** [realm/realm-cocoa#6203]
App crashes while trying to write new object to db.

object:
`class Photo: Object {`
`       dynamic var photo: Data? = nil`
`       dynamic var thumbnail: Data? = nil`
`       dynamic var date: Date? = nil`
`       dynamic var lat: Double? = nil`
`       dynamic var lng: Double? = nil`
}`
`

write:
`let realm = try! Realm()`
`      let newPhoto = Photo()`
`      newPhoto.date = Date()`
`      newPhoto.photo = photo.pngData()`
`      newPhoto.thumbnail = UIImage(named: "samplePhoto")?.pngData()`
`       try! realm.write {`
`       realm.add(newPhoto)`

error:
![Snímek obrazovky 2019-07-19 v 10 11 36](https://user-images.githubusercontent.com/31731743/61521245-16c94a80-aa10-11e9-8308-6e173acc33c6.png)

Realm framework version: v3.17.1

Xcode version: 10.2.1

iOS/OSX version: 12.3.1/Mojave 10.14.5

Dependency manager + version: CocoaPods

**Comment by owenzhao** [comment]
You didn't add `@objc` on your properties.

`@objc dynamic var photo: Data? = nil`
