### ISSUE TITLE
Can't archive app on Xcode 11 beta 4

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-cocoa#6204]
The app can run successfully, but can't archive.

RealmSwift 3.17.1.
Xcode 11 beta 4.
macOS 10.15 beta 4.

<img width="2992" alt="Screen Shot 2019-07-19 at 20 33 58" src="https://user-images.githubusercontent.com/2182896/61535495-055e5d80-aa65-11e9-9e8a-3f23104132ae.png">

**Comment by ppamorim** [comment]
Do not archive apps on Xcode beta.

**Comment by owenzhao** [comment]
> Do not archive apps on Xcode beta.

No. Everything was fine in beta 3.

**Comment by owenzhao** [comment]
This is a known issue of Xcode 11 beta 4. https://stackoverflow.com/questions/57116047/xcode-11-beta-4-archive-swift-errors

Workaround:

<img width="787" alt="Screen Shot 2019-07-20 at 08 42 23" src="https://user-images.githubusercontent.com/2182896/61571985-8e5bb000-aaca-11e9-90b4-d76eb181a440.png">

**Comment by owenzhao** [comment]
More, the above setting must set on the target of RealmSwift, not your own app.
<img width="1527" alt="Screen Shot 2019-07-20 at 09 07 57" src="https://user-images.githubusercontent.com/2182896/61572332-5eaea700-aace-11e9-8bf6-bcc6b501e1bf.png">

**Comment by smartcat32** [comment]
I have a similar build problem to owenzhao, at least it looks like the same error.

In my case, I'm simply trying to build RealmSwift from command line, using today's master branch, 
SHA1: 026a03308360ab301e647754c44881a2ee3b15e1
trying to build using Xcode 11 beta 4 (and yes, Command Line Tools is set to Xcode 11's)
(ios-static and ios-dynamic build fine, btw).

On command line I did:  DEVELOPER_DIR=/Applications/Xcode-beta.app/Contents/Developer ./build.sh ios-swift

Undefined symbols for architecture arm64:
  "Swift.String.UTF16View._nativeGetOffset(for: Swift.String.Index) -> Swift.Int", referenced from:
      function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded, Arg[2] = Exploded, Arg[3] = Dead> of RealmSwift.gsub(pattern: Swift.String, template: Swift.String, string: Swift.String, error: Swift.AutoreleasingUnsafeMutablePointer<__C.NSError?>?) -> Swift.String? in Util.o
  "Swift.String.UTF16View._foreignCount() -> Swift.Int", referenced from: ...

Anyone know how to build RealmSwift from command line using Xcode 11 beta 4?

**Comment by owenzhao** [comment]
I think you just need the command line way to modify the build settings like I did in Xcode.

However, I didn't know how to that with command line. 

If I were you, I would create an empty project and did what I did above. The changes could easily watched by git. So you can use vim to change the project accordingly.

**Comment by ajmeerkhan** [comment]
@owenzhao I have tried the workaround, but it is helpless, same error result...

**Comment by owenzhao** [comment]
> @owenzhao I have tried the workaround, but it is helpless, same error result...

Please provide your sample Xcode project and I will try it.

**Comment by owenzhao** [comment]
My issue is solved by Xcode beta 5. If you can confirm yours @ajmeerkhan , I will close this issue.

**Comment by ajmeerkhan** [comment]
@owenzhao its working fine now.

**Comment by rkittinger** [comment]
Hello, what was the working solution to this problem?

**Comment by owenzhao** [comment]
> Hello, what was the working solution to this problem?

You should not encounter this issue as it is fixed in Xcode 11 beta 5.

**Comment by rkittinger** [comment]
Was is release version, problem with SwiftSoup. Here solution for that:

https://stackoverflow.com/questions/58001433/xcode-11-stuck-on-archiving
