### ISSUE TITLE
Build Fails Xcode 10.3

### ISSUE THREAD

**Issue by shial4** [realm/realm-cocoa#6206]
## Goals
Fix build proces under Xcode 10.3

## Expected Results
Successfully build.

## Actual Results
Failed. Due to:

```
Realm.build/module.modulemap:2:21: Umbrella header 'Realm.h' not found
```
and
```
RealmSwift/RealmSwift/Aliases.swift:20:8: Could not build Objective-C module 'Realm'
```

## Version of Realm and Tooling

Realm framework version: ?
Realm (3.17.1) 
RealmSwift (3.17.1)

Xcode version: ?
10.3

iOS/OSX version: ?
Mojave 10.14.5 

Dependency manager + version: ?
CocoaPods 1.7.3

**Comment by GalCohen** [comment]
Same :(

**Comment by nzayatz14** [comment]
+1

**Comment by tgoyne** [comment]
Seems to work fine for me. Did you delete  ~/Library/Developer/Xcode/DerivedData after upgrading Xcode?

**Comment by GalCohen** [comment]
computer restart fixed it for me, lol. For now I'll take it 🤨🤷‍♂️

**Comment by shial4** [comment]
I did nuke Cocoapods, ruby installations. Restarted  Xcode, my machine, deleted all the files like derived data and so on so on. 

After all I am stuck here: 

>Ambiguous reference to member 'subscribe'

>'RxTimeInterval' (aka 'DispatchTimeInterval') cannot be constructed because it has no accessible initializers

>Extraneous argument label 'onNext:' in call

**Comment by tgoyne** [comment]
Those all sound like RxSwift things, not Realm things.

**Comment by shial4** [comment]
I am not sure it realm thing is still there. My compile process won't pass thru RxSwift now

**Comment by shial4** [comment]
All right, restarting computer fixes it
