### ISSUE TITLE
Crash in  realm::util::File::unlock() <- ~SharedGroup()

### ISSUE THREAD

**Issue by SunnyGit** [realm/realm-cocoa#6207]
!!! MANDATORY TO FILL OUT !!!

## Goals

App to run without crashes.

## Expected Results
No Crashes

## Actual Results
About 200 Crashes in the app.

## Steps to Reproduce

It crashes during launch and also while using the app.

## Code Sample

Can't share the code this is happening in production

## Version of Realm and Tooling

Realm framework version:  3.16.2

Realm Object Server version: ?

Xcode version:  10.1

iOS/OSX version: 10.3 and above

Dependency manager + version: ?

0   libsystem_kernel.dylib               0x00000001f521f104 __pthread_kill + 8
1   libsystem_pthread.dylib              0x00000001f529b020 pthread_kill$VARIANT$mp + 376
2   libsystem_c.dylib                    0x00000001f5176d78 abort + 136
3   Realm                                0x0000000106a9caa4 please_report_this_error_to_help_at_realm_dot_io + 8
4   Realm                                0x0000000106a9cdb0 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 260
5   Realm                                0x0000000106a9d17c realm::util::terminate_with_info(char const*, char const*, long, char const*, std::initializer_list<realm::util::Printable>&&) + 420
6   Realm                                0x0000000106a876d4 void realm::util::terminate_with_info<int&, int&>(char const*, int, char const*, char const*, int&&&, int&&&) + 72
7   Realm                                0x0000000106a87670 realm::util::File::unlock() + 96
8   Realm                                0x00000001069b70ac realm::SharedGroup::close_internal(std::__1::unique_lock<realm::util::InterprocessMutex>) + 568
9   Realm                                0x00000001069b7234 realm::SharedGroup::~SharedGroup() + 44
10  Realm                                0x00000001068da53c realm::Realm::~Realm() (memory:2285)
11  Realm                                0x00000001067db3c8 std::__1::shared_ptr<realm::CollectionChangeCallback::Base>::~shared_ptr() (memory:3490)
12  libobjc.A.dylib                      0x00000001f4858478 object_cxxDestructFromClass(objc_object*, objc_class*) + 144
13  libobjc.A.dylib                      0x00000001f486871c objc_destructInstance + 64
14  libobjc.A.dylib                      0x00000001f4868784 object_dispose + 12
15  Realm                                0x00000001068a5d58 -[RLMRealm dealloc] (RLMRealm.mm:734)
16  RealmSwift                           0x0000000106fd2f84 RealmSwift.Realm.__deallocating_deinit (<compiler-generated>:0)
17  libswiftCore.dylib                   0x000000010a697584 _swift_release_dealloc + 24
18  Edison                               0x0000000104d91990 0x104870000 + 5380496
19  libswiftCore.dylib                   0x000000010a697584 _swift_release_dealloc + 24
20  Alamofire                            0x0000000105f24814 0x105ef4000 + 198676
21  libswiftCore.dylib                   0x000000010a697584 _swift_release_dealloc + 24
22  libsystem_blocks.dylib               0x00000001f511ea44 _Block_release + 148
23  libdispatch.dylib                    0x00000001f50c2484 _dispatch_client_callout + 12
24  libdispatch.dylib                    0x00000001f506e9a4 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1064
25  CoreFoundation                       0x00000001f5619ce4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
26  CoreFoundation                       0x00000001f5614bac __CFRunLoopRun + 1960
27  CoreFoundation                       0x00000001f56140e0 CFRunLoopRunSpecific + 432
28  GraphicsServices                     0x00000001f788d584 GSEventRunModal + 96
29  UIKitCore                            0x00000002229a8c00 UIApplicationMain + 208
30  Edison                               0x000000010487a9f4 main (AppDelegate.swift:33)
31  libdyld.dylib                        0x00000001f50d2bb4 start + 0

**Comment by bmunkholm** [comment]
@SunnyGit Are these 200 different users that experience this or the same user?
Have you been able to reproduce this in your testing?

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
