### ISSUE TITLE
关于 使用 iOS13 NSDiffableDataSourceSnapshot

### ISSUE THREAD

**Issue by yushuyi** [realm/realm-cocoa#6209]
尝试通过 iOS13的 新特性 NSDiffableDataSourceSnapshot 并 加载 RealmObject， 但是 当删除一个对象时 会导致 NSDiffableDataSourceSnapshot 在对比 hash时 会 Crash。 有什么解决办法吗？

**Comment by bmunkholm** [comment]
@yushuyi We only provide support in English unfortunately.

**Comment by yushuyi** [comment]
Try to pass the new feature iOS13 NSDiffableDataSourceSnapshot and load RealmObject, but when you delete an object will cause NSDiffableDataSourceSnapshot to Crash when comparing hashes. Is there any solution? @bmunkholm

**Comment by matijag1** [comment]
Same problem on my side. 

Is there any official documentation or example on how to use Realm with NSDiffableDataSourceSnapshot? 

Thanks
