### ISSUE TITLE
Duplicate PrimaryKey (Write Two Same Data at One Write Transaction)

### ISSUE THREAD

**Issue by saeedmozaffari** [realm/realm-cocoa#6210]
Hi,
I have a big problem with write data on realm. i have a loop for write data at realm and at this state i have two same data with same primaryKeyId , also before make each object i check if exist primaryKey at realm just find data and update that otherwise make new one, but at this state because of write block not ended yet my query for find old inserted data at this loop will be returned nil (data not exist at realm) and because of data not exist i add this data again at my realm table. In this state app will be crashed, because of two same primaryKeyId.
our project is open source and i link of my crash -> i call [this method](https://github.com/KianIranian-STDG/iGap-iOS/blob/319f0b764e41c856982d11f3adf0fee3b9ccab1d/iGap/Model/Objects/IGRoomMessage.swift#L274) at loop and [loop method is here](https://github.com/KianIranian-STDG/iGap-iOS/blob/319f0b764e41c856982d11f3adf0fee3b9ccab1d/iGap/Model/Managers/IGMessageLoader.swift#L887). my crash is duplicate primaryKey.

Realm framework version: v3.14.2
Xcode version: 10.2.1
iOS/OSX version: 12.3

**Comment by leemaguire** [comment]
Closing this issue due to age, if you have any other questions please open a new issue and fill out the template.

Thanks.
