### ISSUE TITLE
IN query not working in version 3.17.3

### ISSUE THREAD

**Issue by prasenraj** [realm/realm-cocoa#6219]
entity = groupURI
value =  "static:182@10924710ClientATP2"

When ever we are fetching the data from db using “groupURI IN %@“ query. we are not getting any result in realm version 3.17.3. But in realm 3.14.0 it’s working properly. More than 3.14.0 version this type of “IN” query is not working. How to resolve this issue?   

We found root cause when numbers are being suffixed after "@" symbol in queried string. Can someone look into this? 

Realm version 3.17.3
xcode 10.1
ios version - 12

**Comment by jsflax** [comment]
Hi there, this should no longer be an issue in the latest version of Realm. Please update your Realm SDK and if this persists, please open up a new issue.
