### ISSUE TITLE
Don't receive object notification, when update linked object

### ISSUE THREAD

**Issue by Daivest** [realm/realm-cocoa#6221]
## Goals
Receive correct notifications from object notification block

## Expected Results
I receive notification from object notification block, when update linked realm objects.

## Actual Results
From object notification block I receive notification if i change:
a) object properties

From RLMResult notification block, which contains this object, I receive notification if i change:
a) object properties
b) linked objects properties 

## Steps to Reproduce
a) Create chat object with RLMArray linked members, and store it in realm
b) Fetch chat from realm by primary key
c) Subscribe to chat changes, by applying object notification block
d) Update linked member

## Code Sample
https://gist.github.com/Daivest/3b65f0f132fd69e3237e773eb2381df1

[testRealmUpdateChat.zip](https://github.com/realm/realm-cocoa/files/3480240/testRealmUpdateChat.zip)

## Version of Realm and Tooling
Realm framework version: 3.17.3

Xcode version: 10.2

iOS/OSX version: 10.14.4

Dependency manager + version: Cocoapods 1.7.1

**Comment by jsflax** [comment]
Hi @Daivest ,

Declaring linking objects does not trigger notifications right now. There are probably use cases where it would be desirable though, and is something we can consider for the future.
