### ISSUE TITLE
Property does not exist

### ISSUE THREAD

**Issue by dalba1992** [realm/realm-cocoa#6223]
I am facing this issue while sorting with keypath after upgrading swift version.
When I am using swift 3 and realm 2.10.1, it was working well.
Now I upgraded them, but it stopped to work with following message.

Terminating app due to uncaught exception 'RLMException', reason: 'Cannot sort on key path 'titleForSort': property 'Book.titleForSort' does not exist.'

This is my current code.
..........
 let books = realm.objects(Book.self)     
return books.sorted(byKeyPath: "titleForSort", ascending: true)
...............
Realm framework version: 3.17.3
Xcode version: 10.3
Swift version :5
iOS/OSX version: 12.3

**Comment by tgoyne** [comment]
What does the definition of your Book class look like?

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
