### ISSUE TITLE
Archiving is stuck when building RealmSwift

### ISSUE THREAD

**Issue by mrarronz** [realm/realm-cocoa#6224]
!!! MANDATORY TO FILL OUT !!!

## Goals

Archive works normally

## Expected Results

Archive product successfully and get package for uploading

## Actual Results

Archive product is always stuck when building RealmSwift.

I use cocoapods to install RealmSwift, following the official guide document. My app works normally on simulator and device in debug mode. But when I'm trying to archive a build to upload to app store, the problem occurs.

I use RealmSwift 3.15.0 at first, after I update version to 3.17.3, it's still stuck on archiving, there is no any reaction, just building...  no error and no successful response, it's just stuck here. This really annoying me.

Can anyone help? I've looked up the issues, but didn't find a really helpful way to solve this issue.

## Steps to Reproduce

clean my project and select 'product' -> 'archive'

## Version of Realm and Tooling

Swift version: 5.0

Realm framework version: 3.17.3

Xcode version: 10.3

iOS/OSX version: iOS 12, mac OS 10.14.6

**Comment by mrarronz** [comment]
Finally the build is archived successfully with realm version 3.17.3, it really takes a long time. With version 3.15, that takes more time and will be failed. 

Building a project should be easy with xcode and usually takes a few minutes, but building only RealmSwift cost too much time, 3.17.3 cost about 30 minutes more, 3.15 cost hours and fail, which cannot be tolerated.

**Comment by rubenvde** [comment]
I got the same issue too but I waited more than 10 hours and the progress still gets stuck on RealmSwift. I hope someone can fix this as soon as possible
