### ISSUE TITLE
invocation function for block in objc_object* (anonymous namespace)::makeBoxedGetter<realm::StringData>(unsigned long) + 45

### ISSUE THREAD

**Issue by jjy4880** [realm/realm-cocoa#6227]
`RLMObject_Private.hpp line 45
invocation function for block in objc_object* (anonymous namespace)::makeBoxedGetter<realm::StringData>(unsigned long) + 45` 

## Actual Results
 can't reproduce
![스크린샷 2019-08-12 오후 2 55 29](https://user-images.githubusercontent.com/28885318/62847432-43236e80-bd11-11e9-93b7-5cc4eff70870.png)

`
CoreFoundation | __exceptionPreprocess
-- | --
1 | libobjc.A.dylib | objc_exception_throw
2 | Realm | RLMObject_Private.hpp line 45invocation function for block in objc_object* (anonymous namespace)::makeBoxedGetter<realm::StringData>(unsigned long) + 45
3 | GLAM | RealmBrowse.swift line 81HomeRatingViewModel.popLastUser() + 81
4 | GLAM | HomeRatingCollectionViewCell.swift line 191HomeRatingCollectionViewCell.createCardView() + 191
5 | GLAM | HomeRatingCollectionViewCell.swift line 353closure #2 in HomeRatingCollectionViewCell.removeCard(userId:toRight:) + 353
6 | GLAM | <compiler-generated> line 0thunk for @escaping @callee_guaranteed (@unowned Bool) -> ()
7 | UIKitCore | -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
17 | UIKitCore | UIApplicationMain
18 | GLAM | HomeRatingViewModel.swift line 28main + 28
`

## Code Sample

```swift
self._characters             = json["characters"].description

func popLastUser() -> User {
        return User(browses.removeLast().toJSON())
    }

func toJSON() -> JSON {
        var newValue = super.swiftyJSON
        newValue["characters"] = JSON(parseJSON: self._characters)
        return newValue
    }
```

## Version of Realm and Tooling

Realm framework version: 3.17.3

Realm Object Server version: 

Xcode version: ?
10.2
iOS/OSX version: ?
12.2

Dependency manager + version: ?
cocoadpods 1.7.5

**Comment by tgoyne** [comment]
This exception is reporting that you're trying to access a property on an object which has been deleted.

**Comment by Pratik-Sodha** [comment]
Can we apply any preventing fix?
