### ISSUE TITLE
iOS 13 beta, Realm is crashing when compiled using xcode 11 beta

### ISSUE THREAD

**Issue by abhimanyukr02** [realm/realm-cocoa#6236]
RealmSwift is crashing on iOS 13 when compiled using xcode 11 beta

Crash information: 

*** Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'identity' does not exist on object 'RealmSwiftPermissionUser''

## Version of Realm and Tooling

Realm framework version:  3.7.5 
Using CocoaPod

Realm Object Server version: NA

Xcode version: xcode 11 beta

iOS/OSX version: iOS 13 beta

[RealmCrash.pdf](https://github.com/realm/realm-cocoa/files/3539848/RealmCrash.pdf)

**Comment by ostatnicky** [comment]
You have to update RealmSwift at least to v3.16.2. And after it try to clean your project. It looks that they have already fixed it in https://github.com/realm/realm-cocoa/pull/6164.

**Comment by abhimanyukr02** [comment]
Thanks for the update. Verified with v3.17.3.
