### ISSUE TITLE
BLOBs

### ISSUE THREAD

**Issue by shmidt** [realm/realm-cocoa#624]
How to store BLOBs? Docs says that `NSData` is supported property type.
But when I add to SimpleExample `@property NSData        *photoData;` it crashes.

Also, will it be `NSFetchedResultsController` analogue?

**Comment by easingboy** [comment]
is this issue fix now?

**Comment by easingboy** [comment]
is this issue fix now?
"There's a design in place for optional properties, but that has yet to be implemented. Until then, every model property must be set."

**Comment by jpsim** [comment]
@easingboy we've made beta releases with null support for strings & data, see https://github.com/realm/realm-cocoa/issues/628#issuecomment-106952727. Now this is merged to master behind a compiler flag, and will be officially released at some point in the future.
