### ISSUE TITLE
A crash when realm try save sth.

### ISSUE THREAD

**Issue by michaelmou** [realm/realm-cocoa#6240]
#0. Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x7fff606abb66 __pthread_kill + 10
1  libsystem_pthread.dylib        0x7fff60876080 pthread_kill + 333
2  libsystem_c.dylib              0x7fff606071ae abort + 127
3  XXX                     0x10f9320a9 please_report_this_error_to_help_at_realm_dot_io + 389305
4  XXX                     0x10f932624 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 390708
5  XXX                     0x10f9328e5 realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 391413
6  XXX                     0x10fa2919a realm::GroupWriter::write_group() + 869498
7  XXX                     0x10fa25b03 realm::SharedGroup::low_level_commit(unsigned long long) + 855523
8  XXX                     0x10fa255bc realm::SharedGroup::do_commit() + 854172
9  XXX                     0x10fa25f85 realm::SharedGroup::commit_and_continue_as_read() + 856677
10 XXX                     0x10f7c2431 realm::_impl::RealmCoordinator::commit_write(realm::Realm&) + 1504 (vector:1504)
11 XXX                     0x10f8710fd realm::Realm::commit_transaction() + 591 (shared_realm.cpp:591)
12 XXX                     0x10f84c921 -[RLMRealm commitWriteTransaction:] + 550 (RLMRealm.mm:550)

please look at this problem. thx

!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: 2.9.1

Realm Object Server version: none

Xcode version: 10.2

iOS/OSX version: 10.14.6

Dependency manager + version: ?

**Comment by bmunkholm** [comment]
@michaelmou As the version you are using (2.9.1) is more than 2 years old, I recommend you upgrade to the most recent version as many bugs have been fixed since this version was released.

**Comment by michaelmou** [comment]
I was tried to upgrade, but since that ,the old data had been modified and can not been used...How can I solve this problem ??

**Comment by bmunkholm** [comment]
Do you mean that you updated your app to use the latest version of Realm, but the app can no longer load the old database stored with the old version?
The new version should migrate the old database automatically.
