### ISSUE TITLE
Realm Collection Observe vs Object Observe

### ISSUE THREAD

**Issue by Zanchee** [realm/realm-cocoa#6246]
## Goals
While messing around with Realm, I noticed some inconsistencies with the observers.

## Expected Results
Given I have `Person` object who has a `List` of `Dog`s, I would expect to get an observation notification when observing all `Person`s in the repo as well as that specific `Person`

## Actual Results
Only the observation on the collection receives a notification that the `Person` changed.

## Code Sample
In the below example, `User` has a `List` of `Habits`. When I modify a `Habit` on the user, the collection observation fires a notification, but the user observation does not.
```
        usersObservationToken = realm.objects(User.self).observe { [weak self] notification in
            print("A user in the users changed.")
        }
        
        guard let user = user else { return }
        userObservationToken = user.observe { [weak self] notification in
            print("This user changed!")
        }
```

## Version of Realm and Tooling
Realm framework version: 3.17.3

Realm Object Server version: N/A

Xcode version: 11 Beta 7

iOS/OSX version: 13

Dependency manager + version: Cocoa 1.8

**Comment by jsflax** [comment]
I have reproduced this. Going to mark as a bug and move forward.
