### ISSUE TITLE
Filtering objects with IN query returning incorrect results

### ISSUE THREAD

**Issue by gshahbazian** [realm/realm-cocoa#6249]
## Goals
Filter objects with two `IN` queries eg: `"id IN %@ AND NOT name IN %@"`.

## Expected Results
Objects that have an `id` in the first set and a `name` in the second set are excluded.

## Actual Results
Objects that have an `id` in the first set and a `name` in the second set are included. See assert in the sample project.

## Steps to Reproduce
Run sample app, hit button in view controller, code asserts.

## Code Sample
Download xcode project here: https://www.dropbox.com/s/iud1xt4we4fcuv7/RealmTests.zip?dl=0

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95

/Applications/Xcode.app/Contents/Developer
Xcode 11.0
Build version 11A419c

/usr/local/bin/pod
1.7.5
Realm (3.17.3)
RealmSwift (3.17.3)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

/usr/local/bin/carthage
0.32.0
(not in use here)

/usr/local/bin/git
git version 2.23.0
```

---

Note:

* I am able to reproduce this with Realm 3.15.0 and greater, and also with Xcode 10.3.
* Adding an index on `LabelModel.name` fixes the issue.

**Comment by bmunkholm** [comment]
Was released in 3.19.0.
