### ISSUE TITLE
Xcode 11 beta Crash

### ISSUE THREAD

**Issue by AmrAbedal** [realm/realm-cocoa#6250]
Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'partnerId' does not exist on object 'Partner''
xcode 11 Beta
despite it works in xCode 10.1
dependency manager : CocoaPods

**Comment by tgoyne** [comment]
What version of Realm are you using? This should have been fixed in 3.16.2.

**Comment by eXhausted** [comment]
Have the same on 3.18

**Comment by abhilashdonepudi** [comment]
Any update on this issue? We have the same issue with XCode 11 GM Seed 2. We are using 3.18.0.

**Comment by tgoyne** [comment]
Please provide some sort of sample code or repro case for this.

**Comment by abhilashdonepudi** [comment]
Do you know if RealmSwift 3.18.0 is ready for XCode 11?

**Comment by tgoyne** [comment]
Yes, it is built and tested with Xcode 11.

**Comment by abhilashdonepudi** [comment]
Just want to give a quick update. Once I comment out the "migrationBlock", I am not getting that error anymore. Any insight into this?

**Comment by litaibye** [comment]
Xcode 11 beta Crash

**Comment by nirinchev** [comment]
Saying "we get a crash" is far too vague for anyone to meaningfully help you. As Thomas pointed out, 3.18.0 is expected to work with Xcode 11. If it doesn't work for you, providing a project that reproduces the crash or at least instructions on how to reproduce it is the bare minimum that we need to start looking into the issue.

**Comment by smelloftime** [comment]
I also encountered the same problem and have solved it.
Xcode11 Version 11.0 (11A420a)
RealmSwift 3.13.1 -> 3.18.0
The processing method is as follows:
1. Remove 'realm' from 'pod', mask the realm in 'podfile', then 'pod install'
2. Reinstall the 3.18.0 version of 'realm'
The project is ok!

**Comment by lamatatwany** [comment]
@smelloftime Hi,
what do you mean by "mask the realm in 'podfile'"? how to do so?

**Comment by uwemeier-sclable** [comment]
> @smelloftime Hi,
> what do you mean by "mask the realm in 'podfile'"? how to do so?

put a `#` in front of `pod 'Realm'` in your Podfile (i.e. commenting this line out)  
After running `pod install`, remove the `#` again and run `pod install` again

**Comment by jsflax** [comment]
This should no longer be applicable with Xcode 11 and the 12 beta. Please open another ticket if this persists.
