### ISSUE TITLE
Invalid link to "Download macOS version of the Realm Mobile Platform" in examples/README.md

### ISSUE THREAD

**Issue by stennie** [realm/realm-cocoa#6255]
The [Installation Instructions in the examples README](https://github.com/realm/realm-cocoa/tree/master/examples#installation-instructions) has a dud link to install the macOS version of the Realm mobile platform: https://realm.io/docs/realm-mobile-platform/get-started/

This link results in a 0 byte download for me (tried in Chrome 77, Safari 12.1.2, and `curl`).

I'm not sure what the canonical generic link should be, but it looks like https://static.realm.io/downloads/swift/realm-swift-3.18.0.zip is the expected download.

**Comment by tgoyne** [comment]
That link was to the Developer Edition of the Realm Object Server, but that no longer exists and we currently don't have a free thing that you can run locally. I guess it should be a link to the Realm Cloud free trial signup instead?

**Comment by bmunkholm** [comment]
@tgoyne Are all examples still being compiled on CI to ensure they work?

**Comment by tgoyne** [comment]
They're compiled but not run.

**Comment by jsflax** [comment]
This is no longer applicable with MongoDB Realm.
