### ISSUE TITLE
Incompatible Swift version - framework was built with 5.1

### ISSUE THREAD

**Issue by Bhanualopa** [realm/realm-cocoa#6256]
Am trying to use "realm" in my new iOS project using **swift** through **Carthage** 
and am following [this](https://realm.io/docs/swift/latest/) tutorial.

But am getting some error while downloading realm-cocoa.framework.
Please find the attached screenshot for the reference

<img width="577" alt="Screenshot 2019-09-20 at 2 32 24 PM" src="https://user-images.githubusercontent.com/54078824/65317228-0de42900-dbb9-11e9-8ae5-5443acb522b6.png">

**Comment by tgoyne** [comment]
That is not an error. It's just notifying you that since you're using a different Xcode version from the one used to build the prebuilt library, it's falling back to building Realm from source.
