### ISSUE TITLE
3.18.0 crashes on some devices

### ISSUE THREAD

**Issue by lszzy** [realm/realm-cocoa#6257]
Before the 3.17.3 version, the function has been running normally. After the 3.18.0 was online, some devices received feedback flashback. The code has not been changed. The check found that the problem is caused by the 3.18.0 version.

## Code Sample
Cart *cart = [Cart objectForPrimaryKey:@(shopId)];
    if (!cart) {
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        cart = [[Cart alloc] init];
        cart.shop_id = shopId;
        [realm addObject:cart];
        [realm commitWriteTransaction];
    }
    return cart;

It Crashes at  [realm addObject:cart]; since version 3.18.0

<img width="376" alt="屏幕快照 2019-09-23 上午10 45 41" src="https://user-images.githubusercontent.com/4383651/65399518-ae239300-ddef-11e9-86c1-1fd3081f8b88.png">

<img width="952" alt="屏幕快照 2019-09-23 上午10 46 43" src="https://user-images.githubusercontent.com/4383651/65399488-7fa5b800-ddef-11e9-9112-de65d546a397.png">

## Version of Realm and Tooling

Realm framework version: ?
3.18.0
Realm Object Server version: ?

Xcode version: ?
10.3
iOS/OSX version: ?

Dependency manager + version: ?

**Comment by jeandigiovanni-next** [comment]
Hello,

I think we have the same issue on our side. Some devices have this crash after updating our app.
We updated Realm from 3.14.0 to 3.18.0

<img width="622" alt="Capture d’écran 2019-10-02 à 11 57 20" src="https://user-images.githubusercontent.com/46992999/66035791-12d79f80-e50c-11e9-8538-d1f0565bda60.png">

Realm framework version: 3.18.0
Xcode version: 11.0
iOS/OSX version: 
<img width="236" alt="Capture d’écran 2019-10-02 à 11 58 47" src="https://user-images.githubusercontent.com/46992999/66035772-081d0a80-e50c-11e9-923b-1782e72fbe62.png">

Dependency manager + version: Cocoapod 1.8.1

Hopefully these information can help fix the issue.

**Comment by andreadelfante** [comment]
Hi,
I got this issue too! Anyone has an idea about why this crash happens after the upgrade?

**Comment by DavidFafinski** [comment]
Hello,
Same problem here :( please send help. We have thousand of user who cannot launch our app anymore

**Comment by aliabbas90** [comment]
Hello, 
Any update for issues ? We are encountered the same issue.

**Comment by tgoyne** [comment]
This is probably the same thing as https://github.com/realm/realm-cocoa/issues/6268, as there's only one other assertion in that function. We will hopefully have a release out fixing that early next week.
