### ISSUE TITLE
Add support for Sync when installing via Swift Package Manager

### ISSUE THREAD

**Issue by tgoyne** [realm/realm-cocoa#6262]
Currently SPM does not support binary libraries, which means that we can't use the closed-source sync library. There's a [pitch](https://forums.swift.org/t/pitch-support-for-binary-dependencies/27620) to add support for this (and Apple has said it's something they want to do in some form), so we should adopt it once we can.
Alternatively Open Source Sync.

**Comment by AlexLike** [comment]
Can we get an update on this? Swift 5.3 is shipping SPM [support for distributing binary frameworks as Swift Packages](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages).

**Comment by tgoyne** [comment]
With how swiftpm's tools versioning works, using features added in new versions of Xcode requires dropping support for older versions. This means that at the minimum we need to wait for Xcode 12 to make it out of beta.

**Comment by tgoyne** [comment]
You can now use spm with sync by pointing at the [tg/spm-framework](https://github.com/realm/realm-cocoa/pull/6746) branch. This branch drops support for Xcode 11.
