### ISSUE TITLE
Crash on Xcode 11.0 (11A420a)

### ISSUE THREAD

**Issue by lv-kingsoft** [realm/realm-cocoa#6264]
Realm.asyncOpen() is crashed when Xcode is updated to 11 (Non-beta)
 Realm version: 3.18.0
How can I to fix it ?

running these codes in AppDelegate.swift lead to crash (it worked fine on Xcode 10.3)

let config = Realm.Configuration(schemaVersion: schemaVersion, migrationBlock: { migration, 
             oldSchemaVersion in           
            if (oldSchemaVersion < schemaVersion) {}
        })
 Realm.Configuration.defaultConfiguration = config
 Realm.asyncOpen { (realm, error) in
    if let _ = realm {
        let realm = try! Realm()
        // Get our Realm file's parent directory
        if let fileUrl = realm.configuration.fileURL {
                let folderPath = fileUrl.deletingLastPathComponent().path
                // Disable file protection for this directory
                try! FileManager.default.setAttributes([FileAttributeKey.protectionKey:FileProtectionType.none], ofItemAtPath: folderPath)
            }
    }
    else if let error = error {
    }
}

**Comment by bmunkholm** [comment]
@lv-kingsoft Please fill in the issue template when reporting bugs. Specifically detail how it crashed and what to do to replicate the issue.

**Comment by stennie** [comment]
@lv-kingsoft For more information on building with Xcode 11, please also see issue #6163.

Reinstalling the Realm pod and clearing the build folder data is likely to resolve issues if you have upgraded to Xcode 11 and still have Xcode 10 build artifacts.

**Comment by lv-kingsoft** [comment]
> @lv-kingsoft For more information on building with Xcode 11, please also see issue #6163.
> 
> Reinstalling the Realm pod and clearing the build folder data is likely to resolve issues if you have upgraded to Xcode 11 and still have Xcode 10 build artifacts.

it works for me. Thank you very much!

**Comment by ericjordanmossman** [comment]
Closing the issue because of @stennie 's help [here](https://github.com/realm/realm-cocoa/issues/6264#issuecomment-536263082)
