### ISSUE TITLE
iPhone5, iOS12.4.1 Crashed when realm init

### ISSUE THREAD

**Issue by cellgit** [realm/realm-cocoa#6269]
iPhone5, 12.4.1, xcode11,isCrashed
```
if let realm = try? Realm() {}
```
![image](https://user-images.githubusercontent.com/24635226/65662202-2dba9780-e066-11e9-8116-dac4deb2e64b.png)

**Comment by bmunkholm** [comment]
Please fill out the issue template - it's there to get the needed information to help you.
Specifically, whats the error? Your screenshot cut's the error message. 
Can you reproduce this? How?
Which Realm version are you using?

**Comment by cellgit** [comment]
Solved it,Thanks
