### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by shiangyichen** [realm/realm-cocoa#6270]
**Questions**: 
Realm build error which run on Xcode11
error: Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler
After we tested project on xcode11, it cannot build success.
I tried update carthage with github "realm/realm-cocoa" "master" & "realm/realm-cocoa" "tg/xcode-11-b1", but have same problem!
Need help!

## Expected Results
build success like normal

## Actual Results
error: Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

## Steps to Reproduce
just run on Xcode 11.0 (11A419c) beta

## Version of Realm and Tooling
Realm framework version: ?
v3.18.0

Realm Object Server version: ?
none

Xcode version: 
Version 11.0

iOS/OSX version: ?
iOS 12.2, iOS 13

Dependency manager + version: ?
Carthage 0.33.0

**Comment by tgoyne** [comment]
This error indicates that you are trying to use a framework built with Xcode 10.2.1. The prebuilt Carthage framework for Realm 3.18.0 is built with Xcode 11, so you just need to upgrade to the latest version.
