### ISSUE TITLE
Cannot modify managed objects outside of a write transaction.

### ISSUE THREAD

**Issue by situxinxin** [realm/realm-cocoa#6271]
RealmSwift取出数据
objects(MultipleDetModel.self).filter("sid = \(id) AND userName = '\(userName)'") ,arr.count != 0 {

            let ar = Array(arr).first
            self.model = MultipleDetModel(value: ar as Any)
            self.model.info = MultipleModel(value: ar?.info as Any)
}

在 
          for dic in arr {
                let trou = TroubleModel(JSONString: dic!)
                if let tro = trou {
                    self.model.info?.property.append(tro)
                }
            }

这个时候,偶现
Cannot modify managed objects outside of a write transaction.

我实在不明白,我已经把取出来的数据变成了 临时变量,不在是数据库对象了,这个时候我去更改,为什么还会出现这个问题呢? 这明显是操作数据库对象时候发生的问题.

实在没理解,希望能够得到您的回复与解答. 十分感谢!

**Comment by bmunkholm** [comment]
@situxinxin Sorry, but you have to write in English if we should be able to help you.

**Comment by situxinxin** [comment]
> @situxinxin抱歉，如果我们应该能够为您提供帮助，则必须用英语写。
> 创建问题时，您还需要填写提供的整个模板。

ok,sorry.

objects(MultipleDetModel.self).filter("sid = (id) AND userName = '(userName)'") ,arr.count != 0 {

        let ar = Array(arr).first
        self.model = MultipleDetModel(value: ar as Any)
        self.model.info = MultipleModel(value: ar?.info as Any)
}


for dic in arr {
     let trou = TroubleModel(JSONString: dic!)
         if let tro = trou {
              self.model.info?.property.append(tro)
         }
}




At this time, occasionally
Managed objects cannot be modified outside of a write transaction.

I really do not understand, I have taken out the data into a temporary variable, no longer a database object, this time I go to change, why will there be this problem? This is obviously a problem when manipulating database objects.

Really did not understand, hope to get your reply and answer. Thank you very much!
