### ISSUE TITLE
IN filters not working on non-indexed string properties with values longer then 63 characters

### ISSUE THREAD

**Issue by LukasGram** [realm/realm-cocoa#6272]
## Goals
Filter for objects whose string property has value from a given array or set using the IN operator.

## Expected Results
A result which contains the objects.

## Actual Results
An empty result is returned even if objects would fulfil the filter requirements.

## Steps to Reproduce
1. Create an object with a non-indexed string property.
2. Save multiple of them to the database. At least one object should have a string value with more than 63 characters.
3. Read the objects from the database and filter them using the IN operator and an array of strings with more than two items.

The result will be empty even if you filter using values which exist in the database. The array also does not need to contain the string with more than 63 characters. It's enough that the database contains such a value for that property. As soon as such a value was written all filters using the IN operator on that field are broken. And they remain broken even if deleting the object containing the long string value.

## Code Sample
```
class MyObject: Object {

    @objc dynamic var indexed = ""
    @objc dynamic var notIndexed = ""

    override class func indexedProperties() -> [String] {
        return ["indexed"]
    }
}

class MyModel {

    private let realm: Realm

    private let ids = [
        Array(repeating: "1", count: 64).joined(),
        "2"
    ]

    init() {
        if let url = Realm.Configuration.defaultConfiguration.fileURL {
            try? FileManager.default.removeItem(at: url)
        }

        realm = try! Realm()

        try! realm.write {
            realm.delete(realm.objects(MyObject.self))

            for id in ids {
                let object = MyObject()
                object.indexed = id
                object.notIndexed = id
                realm.add(object)
            }
        }
    }

    func runQuery() {
        let objects = realm.objects(MyObject.self)
        print("objects count: \(objects.count)")

        let indexedEquals = objects.filter("indexed == %@", ids[0])
        print("indexed ==: \(indexedEquals.count)")

        let notIndexedEquals = objects.filter("notIndexed == %@", ids[0])
        print("notIndexed ==: \(notIndexedEquals.count)")

        let indexedIn = objects.filter("indexed IN %@", [ids[0]])
        print("indexed IN single: \(indexedIn.count)")

        let notIndexedIn = objects.filter("notIndexed IN %@", [ids[0]])
        print("notIndexed IN single: \(notIndexedIn.count)")

        let indexedInMulti = objects.filter("indexed IN %@", ids)
        print("indexed IN multiple: \(indexedInMulti.count)")

        let notIndexedInMulti = objects.filter("notIndexed IN %@", ids)
        print("notIndexed IN multiple: \(notIndexedInMulti.count)")
    }
}
```

`runQuery()` will print the following:
> objects count: 3
> indexed ==: 1
> notIndexed ==: 1
> indexed IN single: 1
> notIndexed IN single: 1
> indexed IN multiple: 2
> notIndexed IN multiple: 0

Note that the last print statement where one would expect 2 objects but gets 0.

## Version of Realm and Tooling
Realm framework version: Reproducible with 3.17.3 and 3.18.0

Xcode version: 11.0

iOS/OSX version: 13.0

Dependency manager + version: CocoaPods 1.7.1

**Comment by bmunkholm** [comment]
Thanks @LukasGram for a role model bug report!
It seems we are in luck as that has just been [fixed in realm-core](https://github.com/realm/realm-core/blob/master/CHANGELOG.md#fixed-1), and will be included in the next release of Cocoa.
