### ISSUE TITLE
3.19.0 fails to process in iTunes Connect

### ISSUE THREAD

**Issue by aehlke** [realm/realm-cocoa#6278]
!!! MANDATORY TO FILL OUT !!!

## Goals

Submit a binary with bitcode compilation to iTunes Connect

## Expected Results

iTunes Connect rejects the binary due to a missing symbol in RealmSwift.

## Actual Results

```
 Undefined symbols for architecture arm64:\n      \"_$s10RealmSwift0A0C5writeyyyyKXEKF\", referenced from:\n          __hidden#5633_ in 052.o\n    ld: symbol(s) not found for architecture arm64\n    Exited with 1
```

## Steps to Reproduce

Install realm-cocoa 3.19.0 via Carthage, archive, and try to distribute an ad-hoc provisioned app.

## Version of Realm and Tooling

Realm framework version: 3.19.0

Realm Object Server version: ?

Xcode version: 11.0

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by jsflax** [comment]
Hi there, could you please update to the latest version of Realm to determine whether or not this still an issue?

**Comment by jsflax** [comment]
Going to close this out as it's been a couple of months and a number of releases have occurred. If this is still an issue, please open a new ticket.
