### ISSUE TITLE
RealmSwift API `add(_:update:)` isn't work on updating object intelligently in version 3.17.3

### ISSUE THREAD

**Issue by RollingHeaven** [realm/realm-cocoa#6284]
## Goals
Hello Realm,

There is an API issue, in Realm swift document section `Objects with primary keys` the method `realm.add(_:update:)` isn't work as expected for updating database intelligently with a subclass of `Object` with `primary key` .

Hope you can help us to find out the problem.

## Expected Results
Document indicates this method can do intelligent update for `Object` with `primary key` .

## Actual Results
If the object is managed by Realm, it updates the object, however, if the object is an unmanaged one, it won't be added to database.

It isn't like the document description that can update/add `Object` intelligently.

## Code Sample
```swift
@objcMembers
class Book: Object {
    dynamic var id: Int = 0

    override static func primaryKey() -> String? {
        return "id"
    }
}
```

I update the book object in realm's write block
```swift
try realm.write {
    realm.add(aBook, update: .modified)
}

```

## Version of Realm and Tooling

Realm framework version: 3.17.3

Realm Object Server version: Didn't use this.

Xcode version: 10.2.1, 11.1 GM

iOS/OSX version: 12.2, 13.1

Dependency manager + version: CocoaPods 1.7.5

**Comment by jsflax** [comment]
Hi there, I can no longer reproduce this with the latest version of Realm. If you are still finding this to be an issue, please open a new ticket.
