### ISSUE TITLE
Bitcode error with Swift Package Manager

### ISSUE THREAD

**Issue by mbt-laurent-n** [realm/realm-cocoa#6287]
## Goals
Use Realm swift with Swift Package Manager in a project that enable bitcode.

## Expected Results
Add Realm swift to package manager and build the project.

## Actual Results
I got the following error at the build time:
`bitcode bundle could not be generated because '/Users/myName/Library/Developer/Xcode/DerivedData/MyApp-evxhrhgdhrhjpkcwapjiniivvrzt/Build/Products/Release-iphoneos/Realm.o' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/myName/Library/Developer/Xcode/DerivedData/MyApp-evxhrhgdhrhjpkcwapjiniivvrzt/Build/Products/Release-iphoneos/Realm.o' for architecture arm64`

## Steps to Reproduce
Create an Xcode project
Enable bitcode
Add Realm as a Package dependency ( https://github.com/realm/realm-cocoa )
Build

## Version of Realm and Tooling

Realm framework version: 3.18.0 and 3.19.0

Realm Object Server version: 

Xcode version: 11

iOS/OSX version: 9.3

Dependency manager + version: Swift Package Manager from Xcode 11

**Comment by marcocattai** [comment]
What do you mean by adding a T-* label? 
We are experiencing the same issue - any solution guys?
