### ISSUE TITLE
Crash on Xcode 11

### ISSUE THREAD

**Issue by TTLoveQX** [realm/realm-cocoa#6288]
Hello! there is a crash in realm when I run on Xcode 11, the message is 'libc++abi.dylib: terminating with uncaught exception of type NSException'

**Comment by bmunkholm** [comment]
Could you please fill out the issue template. Thanks!

**Comment by boardmain** [comment]
same problem i think

**Comment by Mixast** [comment]
Same issue after upgrading Xcode to Version 11.0 (11A420a). With let realm = try! Realm () crashes an error. (libc ++ abi.dylib: terminating with uncaught exception of type NSException)

**Comment by jsflax** [comment]
@Mixast @TTLoveQX Are you still encountering this issue?

**Comment by jsflax** [comment]
Going to close this out as it's been a couple of months and a number of releases have occurred. If this is still an issue, please open a new ticket.
