### ISSUE TITLE
Mac Catalyst for architecture x86_64

### ISSUE THREAD

**Issue by X901** [realm/realm-cocoa#6297]
Hi , 

I did try everything on [#6163](https://github.com/realm/realm-cocoa/issues/6163)

but I have no luck to make my app build Successfully 

it always give me this error 

I did try Cocoapods and Carthage
both give me same error 

I did try install version 3.18.0 and 3.19.0

should I change smething on Podfile file ?

last thing I did is tring to install last version by adding
`pod 'RealmSwift'`

but whatever I tried it same error !

> /Pods/Realm/core/librealmcore-ios.a(bptree.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, for architecture x86_64

**Comment by tgoyne** [comment]
Neither carthage nor cocoapods support catalyst yet. You can either use swift package manager or manually install the framework.

**Comment by X901** [comment]
@tgoyne 
Ok thank for for that info

I did try manyally 

but I get error 

`Command PhaseScriptExecution failed with a nonzero exit code
`

image :
https://cl.ly/2d3a85

**Comment by X901** [comment]
Finally it working
I add the library to copy file by mistake
and see the library on Embedded Binaries so I was thinking it's OK
but after I get the error and drag the library also to Embedded Binaries
and Now ot working fine 

Thank !

**Comment by MrFuFuFu** [comment]
I had the same problem as well. Use Swift Package Manager imported realm-cocoa solved my problem.

**Comment by SaifTadros** [comment]
I add it using swift packages as a dependancy but i get this error: 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIWebView", referenced from:
      objc-class-ref in RxWebViewDelegateProxy.o

**Comment by tgoyne** [comment]
That object file is not part of Realm.

**Comment by jbarros35** [comment]
librealmcore-ios.a(array_binary.o),

building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

yes its happening but this project is IOS only.
