### ISSUE TITLE
Memory leak while translate class.

### ISSUE THREAD

**Issue by kosspeed** [realm/realm-cocoa#6298]
!!! MANDATORY TO FILL OUT !!!

## Goals

My application shouldn't have memory leak about Realm.

## Expected Results

Issue 1:
When translate initial Realm Object class to NSObject class. This method is leak -> `RLMCreateManagedAccessor(objc_class*, RLMRealm*, RLMClassInfo*)` -> Which shouldn't leak.

Issue 2:
When translate NSObject class to Realm Object class. This method is leak -> `maybeInitObjectSchemaForUnmanaged(RLMObjectBase*)` -> Which shouldn't leak.
Reference

Issue 3:
When save data to Realm my business logic must translate NSObject class to Realm Object class then save. This method is leak -> `RLMInitializeSwiftAccessorGenerics`  -> Which shouldn't leak.

## Actual Results

Issue 1:
[Reference](https://drive.google.com/file/d/10wG2PAZArMMH1mNgP5haKgBegGstlB1I/view?usp=sharing)

issue 2:
[Reference](https://drive.google.com/file/d/147E47tSNZP8A-45wfFcteqaQ7yc4Lgwn/view?usp=sharing)

Issue 3:
[Reference](https://drive.google.com/file/d/1sBYu37FyzfPCrOFWCVNFegNjaDIfTf8X/view?usp=sharing)

## Steps to Reproduce

Realm Object class: [Link](https://drive.google.com/file/d/19PJ2BeKsW_AD4J2oEfsYlghCeoWc9PSn/view?usp=sharing)

NSObject class: [Link](https://drive.google.com/file/d/1IrgDYwabiejPQP3dmObpyKcHrVYUMvAH/view?usp=sharing)

You should create classes like this and insert data into every property. Then translate from NSObject to Object and Object to NSObject, Then save

## Code Sample

Database managements extension of Object class. Please [download](https://drive.google.com/file/d/1ei9_dpgrWRZH0FBnkY_kjA1eBRtp8WFD/view?usp=sharing)

## Version of Realm and Tooling

Realm framework version: 3.19.0

Realm Object Server version: Unused

Xcode version: Version 11.0 (11A420a)

iOS/OSX version: 13.1.2 (iPad Air 2)

Dependency manager + version: Unused

**Comment by tiendv-teko** [comment]
I am having the same problem.
![image](https://user-images.githubusercontent.com/47714299/70769685-1e153a00-1d9d-11ea-8dc2-a9655cb0d1e9.png)

**Comment by leemaguire** [comment]
It is not advised to use Realm with the design pattern you have chosen, this may be why you are experiening memory issues.

I would recommend taking a look at some of our examples: 

https://github.com/realm/realm-cocoa/tree/master/examples/ios/swift

https://academy.realm.io/posts/try-swift-nyc-2017-nataliya-patsovska-mvvm-at-scale/

Please let us know if you have any questions.

Thanks,
Lee

**Comment by randyhill** [comment]
Why is this pattern not advised and why would it leak?

**Comment by leemaguire** [comment]
I don't have access to the code sample provided any more. @randyhill could you provide more context on what issue you are having?
