### ISSUE TITLE
Cocoapod produces linker errors about OS mismatch from 3.18 onwards

### ISSUE THREAD

**Issue by mildm8nnered** [realm/realm-cocoa#6299]
## Goals

Clean compilation via CocoaPods.

My podspec file has `inhibit_all_warnings!`, but I'm seeing linker warnings for an OS mismatch between the pod project deployment target (10.9), and the version that the precompiled binaries were built for (10.14)

This is problematic because we have a zero warnings policy.

I think the problem is an interaction between the OS version that the binaries were built for, and the deployment target specified in the podspec (10.9)

## Expected Results

No warnings

## Actual Results

67 linker warnings, like this:

`ld: warning: object file (/Volumes/Untitled/Source/Sportscode64/Pods/Realm/core/librealmcore-macosx.a(bptree.cpp.o)) was built for newer OSX version (10.14) than being linked (10.9)`

## Steps to Reproduce

Install Realm into a project via Cocoapods, specifying Realm version 3.18 or above
Using Xcode 10.3

Realm 3.17.3 does not suffer from this issue.

## Code Sample

I don't currently have a test case I can share

## Version of Realm and Tooling

Realm 3.18 and up, installed via Cocoapods

Xcode version: 10.3

iOS/OSX version: 10.13.6

Dependency manager + version: COCOAPODS: 1.7.5

**Comment by tgoyne** [comment]
We had to rework a bunch of build system things to support catalyst, and I guess in the process the deployment target is no longer getting set correctly? The intention is still for it to be targeting 10.9 and should be easy to fix.
