### ISSUE TITLE
Feature request - older database files

### ISSUE THREAD

**Issue by prmacias** [realm/realm-cocoa#6305]
## Goals
I want to see a function that lets Realm create the older realm database files and the current realm (either can be in migration, or a straightforward realm creation functionality

## Expected Results
I didn't test the migration at first and was still new to Swift. My app is getting complicated and I need to test realm migrations due to a bug but I realized that I didn't have the older database versions afterwards. (That's where the realm unshines and need to be polished due to poor unit testing in my opinion)

So, I need to revisit the migrations and get each realm database according to the database versions. That's tedious and prone error work. 

If it'll be nice to add the feature which lets me to get the older database files and I can go ahead test them right away. 

Cheers,
Peter

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by tgoyne** [comment]
Realm doesn't have any way of knowing what your schema was at some point in the past other than by opening a Realm file which has that older schema.
