### ISSUE TITLE
Semantic Issue Realm Xcode 11.1

### ISSUE THREAD

**Issue by VanMinh-sudo** [realm/realm-cocoa#6316]
<img width="286" alt="Screen Shot 2019-10-28 at 09 46 46" src="https://user-images.githubusercontent.com/54099282/67650590-1d9d1d00-f970-11e9-8816-b020558a058d.png">
I've found this issue when run my project in Xcode 11.1, my current Realm version is 2.10. When I update Realm to the lastest version, the result is the same

**Comment by tgoyne** [comment]
The errors are when parsing the standard library headers, so there's something wrong with your Xcode installation.

**Comment by VanMinh-sudo** [comment]
> The errors are when parsing the standard library headers, so there's something wrong with your Xcode installation.

thanks bro! I have reinstalled my Xcode 11.1 and solved my issue

**Comment by VanMinh-sudo** [comment]
close issue because we find the problem! if you want, you can reopen it every time
