### ISSUE TITLE
pod update or use Swift Package Manager always failed 

### ISSUE THREAD

**Issue by yumengqing** [realm/realm-cocoa#6317]
Realm framework version: ?
latest
Realm Object Server version: ?

Xcode version: ?
Xcode11.1
iOS/OSX version: ?
Mac OS 10.15

when I update RealmSwift,  I  use "pod update", but I get  a error 
"
Pre-downloading: `Realm` from `https://github.com/realm/realm-cocoa.git`, branch `master`, submodules `true`

[!] Error installing Realm
[!] Failed to download 'Realm': [!] /usr/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/7c/pc0hhjfj5s72q2ty1jrm6crc0000gn/T/d20191028-14811-dgthqb --template=

Cloning into '/var/folders/7c/pc0hhjfj5s72q2ty1jrm6crc0000gn/T/d20191028-14811-dgthqb'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
"
Then, I use Swift Package Manager. I get a error 
"
Cloning into '/Users/sven/Library/Developer/Xcode/DerivedData/SPMTest-ditlgorglmvpzfebwatrofwqalay/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore'...
    Submodule 'external/catch' (https://github.com/catchorg/Catch2) registered for path 'Realm/ObjectStore/external/catch'
    Cloning into '/Users/sven/Library/Developer/Xcode/DerivedData/SPMTest-ditlgorglmvpzfebwatrofwqalay/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/external/catch'...
    error: RPC failed; curl 18 transfer closed with outstanding read data remaining
    fatal: the remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed
    fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/Users/sven/Library/Developer/Xcode/DerivedData/SPMTest-ditlgorglmvpzfebwatrofwqalay/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/external/catch' failed
    Failed to clone 'external/catch'. Retry scheduled
    Cloning into '/Users/sven/Library/Developer/Xcode/DerivedData/SPMTest-ditlgorglmvpzfebwatrofwqalay/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/external/catch'...
    error: RPC failed; curl 18 transfer closed with outstanding read data remaining
    fatal: the remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed
    fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/Users/sven/Library/Developer/Xcode/DerivedData/SPMTest-ditlgorglmvpzfebwatrofwqalay/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/external/catch' failed
    Failed to clone 'external/catch' a second time, aborting
    Cloning into '/Users/sven/Library/Developer/Xcode/DerivedData/SPMTest-ditlgorglmvpzfebwatrofwqalay/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/external/catch'...
    Failed to recurse into submodule path 'Realm/ObjectStore'
"
I can use other  framework normally

**Comment by bmunkholm** [comment]
@yumengqing It looks like you are "just" having problems downloading? It's not clear how we can help with that?

**Comment by rromanchuk** [comment]
@bmunkholm spm is consistently failing on this package after running "Reset package cache". So although it might be network related, SEO is telling me there might be something ~unique~ specifically to this repo that is causing git to an edge case
