### ISSUE TITLE
Model with "Data" type property not working

### ISSUE THREAD

**Issue by SolorzanoJose** [realm/realm-cocoa#6318]
## Goals
I want to be able to use the Data type for objects in swift 5

## Expected Results
Realm persisting those properties

## Actual Results
Data is always 0 bytes

## Steps to Reproduce
Create a model with a data property
Persist objects with some data

## Code Sample
```
@objcMembers class ChatMessage : Object {
    var message : String = "Hello1"
    var channel : String = "CHANNEL1"
    var id : Int = 0
    var file : Data = Data()
    
    convenience init(message : String, channel : String, id : Int, data : Data) {
        self.init()
        self.id = id
        self.channel = channel
        self.message = message
        self.file = data
    }
    
    override static func primaryKey() -> String? {
        return "id"
    }
    
    override static func indexedProperties() -> [String] {
        return ["channel"]
    }
}
```

## Version of Realm and Tooling

Realm framework version: Latest

Xcode version:  11

iOS/OSX version: 13

Dependency manager: Cocoapods

**Comment by SolorzanoJose** [comment]
If I print the realm result, it says my data property (called file) is 67 bytes, when I access the property, however, its 0 bytes... does anyone know what's going on?

**Comment by bmunkholm** [comment]
@SolorzanoJose It would we helpful if you post your entire (minimal!) test. Cook it down to the most trivial test case you can and post the output of that test.

**Comment by SolorzanoJose** [comment]
Hey @bmunkholm thanks for replying. I found that this is not only for the data property, but for ALL of the object properties, if I print them they are ok but once accessed, they give me the default values of the object, this is so weird.

I fetch the messages using: 

`let messages = self.realm.objects(ChatMessage.self)
 for message in messages {
                print( message.message ) // prints "Hello1" which is my default value
}`

but

`let messages = self.realm.objects(ChatMessage.self)
 for message in messages {
                print( message) // prints Default value instead of what I saved
}`

outputs 

`ChatMessage {
	message = a different message;
	channel = channel2;
	id = 999;
	file = <length = 24, bytes = 0x48657920746869732069732074686520737472696e672049 — 67 total bytes>;
}`

they were saved using 

`let config = Realm.Configuration(encryptionKey: key)
 let realm = try! Realm(configuration: config)
  try! realm.write {
         realm.add(messages, update: .modified)
         print("todo ready")
 }`

**Comment by tgoyne** [comment]
You have not declared your properties as `@objc dynamic`, so they are not managed by Realm.
