### ISSUE TITLE
-[RLMRealmConfiguration syncConfiguration]: unrecognized selector sent to instance when accessing Realm.Configuration.defaultConfiguration

### ISSUE THREAD

**Issue by adamawolf** [realm/realm-cocoa#6324]
## Goals
While linking to Realm as an `.xcframework` and after configuring my realm, I'm attempting to access `Realm.Configuration.defaultConfiguration` in code.

## Expected Results
I would be able to access `Realm.Configuration.defaultConfiguration` and its properties.

## Actual Results
Upon accessing `Realm.Configuration.defaultConfiguration` I receive the following crash:

```
2019-11-01 06:54:44.758145-0700 ContentGenTool[31892:2317349] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RLMRealmConfiguration syncConfiguration]: unrecognized selector sent to instance 0x101572590'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2bc2ef43 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff61de9835 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2bcb9116 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff2bbd56af ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff2bbd5088 _CF_forwarding_prep_0 + 120
	5   RealmSwift                          0x000000010045d03d $s10RealmSwift0A0C13ConfigurationV012fromRLMRealmC0yAESo0eC0CFZ + 765
	6   RealmSwift                          0x000000010045d30b $s10RealmSwift0A0C13ConfigurationV07defaultC0AEvgZ + 59
	7   ContentGenTool                      0x000000010000403f $s14ContentGenCore0A12FileProducerC07produceA03foryAA7ProductV_tKF + 383
	8   ContentGenTool                      0x00000001000028a6 $s14ContentGenCore20CommandLineInterfaceC3runyyKF + 2374
	9   ContentGenTool                      0x0000000100001ae9 main + 105
	10  libdyld.dylib                       0x00007fff6314c2e5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**If I remove all of my app's accesses to `Realm.Configuration.defaultConfiguration` Realm internally seems able to function as expected. That is, my app is able to store and retrieve data from the realm file using the `fileURL` that my app indicated in the `Realm.Configuration`.**

## Steps to Reproduce
1) Include realm as an `.xcframework`. The command I used to build was:

`./build.sh xcframework ios osx`

2) Configure a realm in code:

```
import RealmSwift

...

let fileURL = (string: FileManager.default.currentDirectoryPath).appendingPathComponent("Example.realm")
var configuration = Realm.Configuration()
configuration.fileURL = self.realmFileURL
self.realm = try Realm(configuration: configuration)
```

3) Access `Realm.Configuration.defaultConfiguration`. In my case, attempting to read `fileURL`:

```
let realmURL = Realm.Configuration.defaultConfiguration.fileURL
```

Observe crash.

## Code Sample
Provided above.

## Version of Realm and Tooling

Realm framework version: 3.20.0

Realm Object Server version: whatever is included in 3.20.0.

Xcode version: Version 11.1 (11A1027)

iOS/OSX version: 10.15.1 Beta (19B68f)

Dependency manager + version: manual (I'm fetching Realm source using this command: `git clone git@github.com:realm/realm-cocoa.git  && cd realm-cocoa && git checkout v3.20.0 && git submodule update --init --recursive`)

**Comment by jsflax** [comment]
Do you have a sample project you can send over?

At first glance, it seems like you also need to link the RealmSwift framework.

**Comment by adamawolf** [comment]
@jsflax that's not it.

I'll add the following to my initial description:

If I remove all accesses to `Realm.Configuration.defaultConfiguration`, the app functions as expected, able to store and retrieve data from the realm file as expected (and using the correct `fileURL` that I indicated in the `Realm.Configuration` that I set).

**Comment by w0mba7** [comment]
I am getting a similar issue.  I am linking RealmSwift and RealmObjc through xcframeworks.  This was working before with carthage. 

`    func configVersionUser(syncUser:SyncUser) -> Realm.Configuration {
        var config = syncUser.configuration(realmURL: RealmConstants.REALM_VERSION_URL, fullSynchronization: true)`


`019-11-12 10:49:34.557843-0500 RealmIO Admin[5172:4559481] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RLMRealmConfiguration setSyncConfiguration:]: unrecognized selector sent to instance 0x7fc9d950e270'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23bcb154 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23baef6c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23bb10f8 _CF_forwarding_prep_0 + 120
	5   RealmSwift                          0x00000001009bc68e -[RLMSyncUser configurationWithURL:fullSynchronization:enableSSLValidation:urlPrefix:] + 558
	6   RealmSwift                          0x00000001008babef`
