### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by timefrancesco** [realm/realm-cocoa#6327]
!!! MANDATORY TO FILL OUT !!!

## Goals
Compile a project with a static Realm Framework

## Expected Results
to compile

## Actual Results
Compilation error:  Module compiled with Swift 5.1 cannot be imported by Swift 5.1.2 compiler

## Steps to Reproduce
Add Realm 3.20 framework to a project and try to compile

## Version of Realm and Tooling

Realm framework version: 3.20

Xcode version: 11.2

Maybe is a matter of just compiling the framework with flag:
`BUILD_LIBRARY_FOR_DISTRIBUTION = YES;`

**Comment by saeedmozaffari** [comment]
I have same error and now can't run project !!!

**Comment by jsflax** [comment]
It seems that according to the WWDC videos, the flag you mention is the correct flag to add: https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

Let me explore whether or not we need to add that flag on the Realm library itself.

**Comment by jsflax** [comment]
After looking into this, I am unable to reproduce. Are you able to send a sample project that contains this error?

**Comment by tgoyne** [comment]
As with every time that a new version of Xcode comes out, you will need wait for us to release a new version with a library built for that version of Xcode if you want to use prebuilt libraries.

**Comment by jjohnstonspm** [comment]
I'm running into the same issue, but am actually unable to reproduce the issue when I create a new project. Still attempting to get into this state.

> As with every time that a new version of Xcode comes out, you will need wait for us to release a new version with a library built for that version of Xcode if you want to use prebuilt libraries.

Out of curiosity, what's the reason for this despite the module stability supposedly added with Swift 5.1?

**Comment by tgoyne** [comment]
Building a xcframework with BUILD_LIBRARY_FOR_DISTRIBUTION has a bunch of semantic differences from normal Swift that breaks things. Some I were able to find workaround for, but I couldn't figure out how to get Object class autodiscovery to work, so you have to always explicitly set `objectTypes` on the Configuration. I filed radars for all of the issues I ran into so maybe one day they'll get fixed.

**Comment by Begoodi** [comment]
> As with every time that a new version of Xcode comes out, you will need wait for us to release a new version with a library built for that version of Xcode if you want to use prebuilt libraries.

When will it be available ? Still can't compile for months now, always get "Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.3 compiler" whatever I try reading all possible solutions on the net :(

**Comment by tgoyne** [comment]
Prebuilt binaries for Xcode 11.2 were added in 3.21.0, released 2019-11-04. Make sure you are importing the library built for the version of Xcode you are using.

**Comment by mkoleva** [comment]
So if we want to distribute a forwards compatible binary framework to our clients (e.g. 5.2+), which depends on RealmSwift, is there a way to do that?
