### ISSUE TITLE
Unresolved identifier SyncCredentials & SyncUser with Package manager

### ISSUE THREAD

**Issue by Krysbe** [realm/realm-cocoa#6329]
**Bugs**: To help you as fast as possible with an issue please describe your issue
and the steps you have taken to reproduce it in as many details as possible.

I would like to connect to the realm Cloud to sync data across device. 

I try to create the login in SwiftUI

With realm installed with PODS, everything is working fine but installed with package manager there is an error.

## Goals
Want to login to Realm Cloud

## Expected Results
Build and execute

## Actual Results
Swift Build Error with this errors :

- Use of unresolved identifier 'SyncCredentials'
- Use of unresolved identifier 'SyncUser'

## Steps to Reproduce

- Create a project with SwiftUI
- Install Realm with the Xcode package manager
- Use the sample code bellow

## Code Sample

```
import SwiftUI
import RealmSwift

struct ContentView: View {
    var body: some View {
        Button(action: {
            self.setupRealm(user: "UI", password: "SwiftUI")
        }) {
            Text("Login To Realm Cloud")
        }    }
    
        func setupRealm(user:String, password:String) {

            let serverURL = URL(string: "https://**********.cloud.realm.io")!
            let credentials = SyncCredentials .usernamePassword(username: user, password: password, register: true)

            SyncUser.logIn(with: credentials, server: serverURL) { user, error in
                if let user = user {
                    let syncURL = URL(string: "realms://*********.de1a.cloud.realm.io/*******")!
                    let syncConfig = SyncConfiguration(user: user, realmURL: syncURL)
    //                self.configuration = Realm.Configuration(syncConfiguration: syncConfig)
    //                self.setupDataSource()

                } else if let error = error {
                    // handle error
                    debugPrint("error: \(error.localizedDescription)")
                }
            }

        }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

## Version of Realm and Tooling
Realm 3.19.1 or 3.20
Realm framework version: ?

Realm Object Server version: ?

Xcode version: 11.2 

iOS/OSX version: 10.15.1

Dependency manager + version: 13.2

**Comment by tgoyne** [comment]
Sync is currently not supported when building via swift package manager due to spm's lack of support for binary frameworks.

**Comment by rs658726** [comment]
> Sync is currently not supported when building via swift package manager due to spm's lack of support for binary frameworks.

Is there any alternative?
