### ISSUE TITLE
RLMAddObjectToRealm crash -- Help

### ISSUE THREAD

**Issue by qasimmajeed** [realm/realm-cocoa#6332]
Crashlytics is showing this crash for a some users. 

![](https://user-images.githubusercontent.com/12518819/68290223-044b4d80-00a1-11ea-913b-22b79f38dde0.png)
`

**Comment by qasimmajeed** [comment]
@tgoyne any help in this ?

**Comment by davidchristiandy** [comment]
Hi @qasimmajeed , I'm also interested in this issue. What is your Realm version, tooling version, etc.?

**Comment by qasimmajeed** [comment]
hi @davidchristiandy my issue resolved after updating to the new version of realm
