### ISSUE TITLE
Xcode 11.2 and RealmSwift Primary key property issue

### ISSUE THREAD

**Issue by Channu2** [realm/realm-cocoa#6337]
!!! MANDATORY TO FILL OUT !!!

I get the Primary Key for a particular RealmObject not found when I run my project using XCode11.2. Tried all the steps whatever mentioned in issue [(6163)](https://github.com/realm/realm-cocoa/issues/6163)

## Expected Results
Should not crash the app for Primary key property.

## Actual Results

*** Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'email' does not exist on object 'UserManagementModel''

## Steps to Reproduce

- Create a realm object class with a property defined
- Create some method to save objects 
- Retrieve object stored in the realm(Retrieving the object before saving into Realm. Expected result should return an empty list but getting a crash.)

## Code Sample
```
    class UserManagementModel: Object {
          dynamic  var email: String = ""
          dynamic  var index: Int = 0
          dynamic  var userId: String = ""
          dynamic  var syncStatus: Bool = false
          dynamic  var isDeleted: Bool = false
    
    override class func primaryKey() -> String? {
        return "email"
    }
}

//Save.
   func saveUserList(userObject: UserManagementModel) {
        realmObject.beginWrite()
    realmObject.add(userObject, update: .modified)
        do {
            try realmObject.commitWrite()
        }catch{
            print(error)
        }
    }
// Reterive 
func getUserList()->[UserManagementModel] {
        let predicate = NSPredicate(format:"syncStatus == %@",NSNumber(value: false) )
        let userList = realmObject.objects(UserManagementModel.self).filter(predicate).toArray(UserManagementModel.self)
        return userList
    }

```

Realm framework version: Realm 4.0.0

Xcode version:  11.2 (11B52)

iOS/OSX version: IOS 12.4 / 10.15.1

**Comment by kishikawakatsumi** [comment]
@Channu2 Because you forgot to add `@objcMembers` or `@objc` to your model properties.
`dynamic` properties in Realm object should be declared as `@objc`.

To change your code like the following, it fixes the error.

```swift
@objcMembers
class UserManagementModel: Object {
          dynamic  var email: String = ""
          dynamic  var index: Int = 0
          dynamic  var userId: String = ""
          dynamic  var syncStatus: Bool = false
          dynamic  var isDeleted: Bool = false
    
    override class func primaryKey() -> String? {
        return "email"
    }
}
```

See also https://realm.io/docs/swift/latest/#property-attributes

**Comment by Channu2** [comment]
> @Channu2 Because you forgot to add `@objcMembers` or `@objc` to your model properties.
> `dynamic` properties in Realm object should be declared as `@objc`.
> 
> To change your code like the following, it fixes the error.
> 
> ```swift
> @objcMembers
> class UserManagementModel: Object {
>       dynamic  var email: String = ""
>       dynamic  var index: Int = 0
>       dynamic  var userId: String = ""
>       dynamic  var syncStatus: Bool = false
>       dynamic  var isDeleted: Bool = false
>     
>     override class func primaryKey() -> String? {
>         return "email"
>     }
> }
> ```
> 
> See also https://realm.io/docs/swift/latest/#property-attributes

**Comment by Channu2** [comment]
> > @Channu2 Because you forgot to add `@objcMembers` or `@objc` to your model properties.
> > `dynamic` properties in Realm object should be declared as `@objc`.
> > To change your code like the following, it fixes the error.
> > ```swift
> > @objcMembers
> > class UserManagementModel: Object {
> >       dynamic  var email: String = ""
> >       dynamic  var index: Int = 0
> >       dynamic  var userId: String = ""
> >       dynamic  var syncStatus: Bool = false
> >       dynamic  var isDeleted: Bool = false
> >     
> >     override class func primaryKey() -> String? {
> >         return "email"
> >     }
> > }
> > ```
> > 
> > 
> > See also https://realm.io/docs/swift/latest/#property-attributes

**Comment by Channu2** [comment]
> @Channu2 Because you forgot to add `@objcMembers` or `@objc` to your model properties.
> `dynamic` properties in Realm object should be declared as `@objc`.
> 
> To change your code like the following, it fixes the error.
> 
> ```swift
> @objcMembers
> class UserManagementModel: Object {
>       dynamic  var email: String = ""
>       dynamic  var index: Int = 0
>       dynamic  var userId: String = ""
>       dynamic  var syncStatus: Bool = false
>       dynamic  var isDeleted: Bool = false
>     
>     override class func primaryKey() -> String? {
>         return "email"
>     }
> }
> ```
> 
> See also https://realm.io/docs/swift/latest/#property-attributes

> @Channu2 Because you forgot to add `@objcMembers` or `@objc` to your model properties.
> `dynamic` properties in Realm object should be declared as `@objc`.
> 
> To change your code like the following, it fixes the error.
> 
> ```swift
> @objcMembers
> class UserManagementModel: Object {
>       dynamic  var email: String = ""
>       dynamic  var index: Int = 0
>       dynamic  var userId: String = ""
>       dynamic  var syncStatus: Bool = false
>       dynamic  var isDeleted: Bool = false
>     
>     override class func primaryKey() -> String? {
>         return "email"
>     }
> }
> ```
> 
> See also https://realm.io/docs/swift/latest/#property-attributes

**Comment by Channu2** [comment]
@kishikawakatsumi Thank you for your response i tried with adding @objcMembers or @objc to properties got same issue
