### ISSUE TITLE
EXC_BAD_ACCESS with SPM on iOS, only in Release mode

### ISSUE THREAD

**Issue by acools-luna** [realm/realm-cocoa#6351]
## Goals
I want to use Realm database with SPM for an iOS and Catalyst project (because Pods are not working with Catalyst).

## Expected Results
When I add the latest version of Realm to my project, if I compile and run the project, I'd like to get all objects stored in the database by doing something like:

```
let realm = try? Realm()
let objects = realm?.objects(MyObject.self)
```

But instead of that, I have a crash (who was not in the version 3.21.0)

## Actual Results
That's work perfectly fine in a debug environment, but in release, I got an error:
Thread 1: EXC_BAD_ACCESS (code=1, address=0x16693d7ce)

![Screenshot 2019-11-14 at 09 36 25](https://user-images.githubusercontent.com/53743354/68840058-3d4b7980-06c2-11ea-8007-28ae42428e4f.png)

## Steps to Reproduce
* Create a new project
* Install Realm with SPM (version 4.0.0 or 4.1.0)
* Create a small database
* Try to get all object by calling:

```
let realm = try? Realm()
let objects = realm?.objects(MyObject.self)
```

* Run the app in debug (by default mode): everything should be fine
* Go to Scheme and edit the scheme: set Build configuration to "Release" in the "Run" section
* Try to run the app again: should crash

## Code Sample
```
let realm = try? Realm()
let objects = realm?.objects(MyObject.self) // Crash in release on this line
```

## Version of Realm and Tooling
Realm framework version: master branch

Realm Object Server version: / Server is not used

Xcode version: Version 11.2.1 (11B500)

iOS/OSX version: 13.2.2

Dependency manager + version: SPM in Xcode, Realm master branch and RealmCore 5.23.6

**Comment by RobertGillett** [comment]
I Second This issue

**Comment by tgoyne** [comment]
This is due to [SR-11643](https://bugs.swift.org/browse/SR-11643), and turning off dead code stripping in the project settings should fix it.
