### ISSUE TITLE
RMLResults not being returned (CRASH: Object has been deleted or invalidated)

### ISSUE THREAD

**Issue by doniekelly** [realm/realm-cocoa#6354]
Hi all, have code like this I realm for a while now...

-(CTXConfig *) config {
    
    if(![[CTXConfig allObjects] firstObject]) {
        
        BeginWriteTransaction;
        [realm addObject:[CTXConfig new]];
        CommitWriteTransaction;
    }
    
    return [[CTXConfig allObjects] firstObject];
}

I use these macros to avoid writing the begin/end transaction code all over the place...

#define BeginWriteTransaction RLMRealm *realm = [RLMRealm defaultRealm];[realm refresh]; if(![realm inWriteTransaction])[realm beginWriteTransaction]
#define CommitWriteTransaction if([realm inWriteTransaction])[realm commitWriteTransaction]

When this function is called I can stop in the debugger (Xcode) at the if(... 

po [CTXConfig allObjects] returns this empty array which is correct. 

RLMResults< CTXConfig > <0x10c12e1a0> (

)

The idea here is that if the object doesn't exist then I create a new one. So that only one entry exists in the table ever.

But on first run the object needs to be created. It adds the object. Confirmed later by check with Realm Studio.

However, it then tries to get the object to return but crashes. CRASH: Object has been deleted or invalidated with crash log pointing to code above.

In debugger I do this
po [CTXConfig allObjects] which I expect to be the entry I added above but it's just an address... 

0x0000000108e21640

So this worked under Realm pre 3.20.0 and after we updated the pods we are using we are now on Realm 4.1.0. Is this a bug or am I doing this wrong now?

Thanks
Donie

**Comment by doniekelly** [comment]
No comments on this?

**Comment by bmunkholm** [comment]
Hi @doniekelly As you might have seen in the issue template, we are really only tracking bugs in this repo. This appears more like a question for help, which is better served by StackOverflow or our Forum (where I noticed you posted the same). So I'll close this issue, and ask a few clarifying questions in the Forum.
