### ISSUE TITLE
Crash on accessing binay  data from realm

### ISSUE THREAD

**Issue by manojverma-cs** [realm/realm-cocoa#6355]
I am getting a crash on accessing binary data from realm. Can anyone check this?

Last Exception Backtrace:
0   CoreFoundation                	0x1a6b5580c __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1a687dfa4 objc_exception_throw + 56 (objc-exception.mm:565)
2   Foundation                    	0x1a6f184b0 NSAllocateObject + 176 (NSObject.m:117)
3   Foundation                    	0x1a6e132e8 -[_NSPlaceholderData initWithBytes:length:copy:deallocator:] + 76 (NSData.m:206)
4   Foundation                    	0x1a6e15958 ﹍[NSData(NSData) dataWithBytes:length:]﹍  56 (NSData.m:741)
5   Realm                         	0x102e8ed10 RLMAccessorContext::box(realm::BinaryData) + 48 (RLMUtil.hpp:123)
6   Realm                         	0x102e8ec5c invocation function for block in objc_object* (anonymous namespace)::makeBoxedGetter<realm::Binar... + 212 (RLMAccessor.mm:58)
7   Sample                        	0x101a4d194 outlined bridged method + 13750676 (pb) of @objc Model.imageData.getter + 24
8   Sample                        	0x1014e315c closure #1 in closure #1 in closure #1 in LogsManager.updateLocalName() + 8073564 (LogsManager.swift:870)
9   RealmSwift                    	0x103700df8 Realm.write(withoutNotifying:_:) + 64 (Realm.swift:213)
10  Sample                        	0x1014e2b34 closure #1 in closure #1 in LogsManager.*updateLocalName*() + 8071988 (LogsManager.swift:856)
11  Sample                        	0x100d7718c thunk for @callee_guaranteed () ~~> (@error @owned Error) + 291212 (<compiler~~generated>:0)
12  Sample                        	0x1014e7d14 partial apply for thunk for @callee_guaranteed () ~~> (@error @owned Error) + 8092948 (<compiler~~generated>:0)
13  libswiftObjectiveC.dylib      	0x107402e34 0x1073fc000 + 28212
14  Sample                        	0x1014e29ac closure #1 in LogsManager.updateLocalName() + 8071596 (LogsManager.swift:854)
15  Sample                        	0x100e8b0ec thunk for @escaping @callee_guaranteed () ~~> () + 1421548 (<compiler~~generated>:0)
16  libdispatch.dylib             	0x1a6822610 _dispatch_call_block_and_release + 24 (init.c:1408)
17  libdispatch.dylib             	0x1a6823184 _dispatch_client_callout + 16 (object.m:495)
18  libdispatch.dylib             	0x1a6809238 _dispatch_root_queue_drain + 640 (inline_internal.h:2484)
19  libdispatch.dylib             	0x1a68098b0 _dispatch_worker_thread2 + 116 (queue.c:6628)
20  libsystem_pthread.dylib       	0x1a6872f48 _pthread_wqthread + 212 (pthread.c:2336)
21  libsystem_pthread.dylib       	0x1a6875ad4 start_wqthread + 8

**Comment by ericjordanmossman** [comment]
@manojverma-cs 
Could you provide version info and fill in detail with the issue template?

**Comment by ericjordanmossman** [comment]
Closing because of issue template/context and inactivity.
