### ISSUE TITLE
Iteration causes crash

### ISSUE THREAD

**Issue by georgescumihai** [realm/realm-cocoa#6356]
# Goals
Iterate in Swift over a RLMArray created in Objc.

## Expected Results
Array is iterated.

## Actual Results
The array iteration calls `[[alloc] init]`, on the iterated object, which is where you normally set the primary key and it throws an exception.
`RLMException', reason: 'Primary key can't be changed after an object is inserted.'`
This throws an exception.

## Steps to Reproduce
Iterate over an array of RLMObjects.

I added a sample project to reproduce the issue, you need to run 
`carthage bootstrap --platform iOS`
Run the app
Press start button

## Code Sample
The change that causes the issue is

```
RLMObjectBase.mm
id RLMCreateManagedAccessor(Class cls, RLMClassInfo *info) {
    RLMObjectBase *obj = [[cls alloc] init];
```

before it was

```
id RLMCreateManagedAccessor(Class cls, __unsafe_unretained RLMRealm *realm, RLMClassInfo *info) {
    RLMObjectBase *obj = [[cls alloc] initWithRealm:realm schema:info->rlmObjectSchema];
```

Sample Code from the sample project:

```
@interface Parent : RLMObject

@property (nonatomic, strong) NSString *key;

@property (nonatomic, strong) RLMArray<Child *><Child> *childrens;

@end


@implementation Child

+ (NSString*)primaryKey {
    return @"key";
}

- (id)init {
    if (self = [super init]) {
        self.key = [[NSUUID UUID] UUIDString];
    }
    return self;
}

@end
```

Iteration in swift

```
    func iterate() {
        guard let parent = self.parentModel else {
            return
        }

        rlm_iterate(parent.childrens) { (child) in
            print(child.name)
        }
    }

public func rlm_iterate<T>(_ array: RLMArray<T>?, block: (T) -> Void) {
    guard let array = array else { return }
    array.enumerated().forEach { (_, element) in
        guard let castedElement = element as? T else { return }
        block(castedElement)
    }
}
```

This change was introduced in 4.0.0. with 

```
[RealmIterate.zip](https://github.com/realm/realm-cocoa/files/3853553/RealmIterate.zip)
The designated initializers defined by RLMObject and Object other than
zero-argument init have been replaced with convenience initializers.
```

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88

/Applications/Xcode11.1.app/Contents/Developer
Xcode 11.1
Build version 11A1027

/Users/mihaigeorgescu/.rvm/gems/ruby-2.3.1/bin/pod
1.7.3
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

/usr/local/bin/carthage
0.34.0
(not in use here)

/usr/bin/git
git version 2.21.0 (Apple Git-122)
```

Realm framework version: 4.1.0

Realm Object Server version: Not used

iOS/OSX version: 13.1 iPhone Simulator

Dependency manager + version: Carthage 0.34.0

**Comment by tgoyne** [comment]
You should set default values for properties by overriding `+defaultPropertyValues`, not `-init`.

**Comment by georgescumihai** [comment]
Did not thought of that, looks like it works on the sample project, will try to test it in the real project as well.

Still, `self.realm` is nil when `RLMObjectBase *obj = [[cls alloc] init];` is called, and the exception is thrown exactly during the init.

**Comment by georgescumihai** [comment]
Basically any override of `init()` will cause a crash at iteration.

**Comment by georgescumihai** [comment]
Last time I checked issue was still reproducing, the workaround was not to override `init()` anymore, issue can be closed.
