### ISSUE TITLE
fileExists or deleteFiles RealmSwift- Error

### ISSUE THREAD

**Issue by fbarraganef** [realm/realm-cocoa#6364]
There is an issue where don't detect the fileExists or deleteFiles after update my pod. 

![Screen Shot 2019-11-26 at 15 39 02](https://user-images.githubusercontent.com/28632162/69676446-61b23900-1066-11ea-80e1-9b92d2b7db17.png)

Use cocoapods, use RealmSwift 4.1.1

**Comment by tgoyne** [comment]
You appear to be using RealmSwift master with an older version of Realm.
