### ISSUE TITLE
Unable to retrieve a property in a public global/common realm

### ISSUE THREAD

**Issue by Krysbe** [realm/realm-cocoa#6369]
!!! MANDATORY TO FILL OUT !!!

## Goals
Would like to print or whatever a property of an object from a public global/common realm

## Expected Results
The name stored in an object property

## Actual Results
by exemple print something :
Can print the object with all properties
Can't print one property of the object

## Steps to Reproduce
Retrieve the object from Realm

```
class User: Object, Identifiable {
    
    @objc private var _id:String = ""
    @objc private var _name:String = ""
    @objc private var _surname:String = ""
    @objc private var _email:String = ""
    var _schools = List<School>()
    
    override static func primaryKey() -> String? {
        return "_id"
    }
    
    var id:String {
        get {
            return _id
        }
        set {
            realm?.beginWrite()
            _id = newValue
            try? realm?.commitWrite()
        }
    }
    
    var name:String {
        get {
            return _name
        }
        set {
            realm?.beginWrite()
            _name = newValue
            try? realm?.commitWrite()
        }
    }
    
    var surname:String {
        get {
            return _surname
        }
        set {
            realm?.beginWrite()
            _surname = newValue
            try? realm?.commitWrite()
        }
    }
    
    var email:String {
        get {
            return _email
        }
        set {
            realm?.beginWrite()
            _email = newValue
            try? realm?.commitWrite()
        }
    }
}



    func SyncGlobalRealm() -> Realm {
        var syncGlobalConfiguration = SyncUser.current!.configuration(realmURL: self.constants.globalRealm, fullSynchronization: true, enableSSLValidation: true, urlPrefix: nil)

        syncGlobalConfiguration.objectTypes = [User.self, School.self]

         let syncGlobalRealm = try! Realm(configuration: syncGlobalConfiguration)
        return syncGlobalRealm
    }



    func GetUserInfos() {
        let id = SyncUser.current?.identity
        let user = self.dbmanager.SyncGlobalRealm().object(ofType: User.self, forPrimaryKey: id)
        print("Object")
        print(user!)
        print("object property")
        print("Name : \(user!.name)")
        print("Name : \(user!.surname)")
    }
```

CONSOLE : 

> Object
> User {
> 	_id = tpNpZ3pV93V268bbwF5OMjjsvuH2;
> 	_name = Jean;
> 	_surname = D**********;
> 	_email = jean@************;
> 	_schools = List<School> <0x600000ad77b0> (
>

> 	);
> }
> object property
> Name : 
> Surame : 

## Version of Realm and Tooling

Realm framework version: 3.19

Realm Object Server version: Cloud platform

Xcode version: 11.2 beta 2 (11B44)

iOS/OSX version: 13.2

Dependency manager + version: ?

**Comment by jsflax** [comment]
You need to add the `dynamic` modifier to your variable declarations.

That said, I would not recommend you write to the realm in the way that you are. While it is "convenient", the secondary effect of writing to the Realm every time you call a setter may create undesired, unexpected effects– and may make debugging more complicated.

**Comment by Krysbe** [comment]
Oups sorry ! In front of my eyes :) 

Thanks for the advice.
