### ISSUE TITLE
Background worker thread Realm degradation

### ISSUE THREAD

**Issue by rinat-enikeev** [realm/realm-cocoa#6371]
## Goals
I want to save in Realm from background worker thread. 

## Expected Results
I expect that no degradation occurs after saving thousands of records to the Realm in background. 

## Actual Results
Realm crashes on app start. On my device it was something like "can't allocate 7Gb realm file". 

## Steps to Reproduce
Download production code from the [public repository](https://github.com/ruuvi/com.ruuvi.station.ios/tree/realm-report), `realm-report` branch, `station` target. 
Run on the device and connect to multiple tags in order to populate the database. 

I understand that it is hard to reproduce without physical devices. I'll describe my findings in the first comment, any help is greatly appreciated. 

## Code Sample
Full repository: https://github.com/ruuvi/com.ruuvi.station.ios/tree/realm-report - `realm-report` branch. 

Most interesting parts are: 

```
import Foundation

class BackgroundWorker: NSObject {
    var thread: Thread!
    private var block: (()->Void)!
    
    @objc internal func runBlock() { block() }
    
    internal func start(_ block: @escaping () -> Void) {
        self.block = block
        
        let threadName = String(describing: self)
            .components(separatedBy: .punctuationCharacters)[1]
        
        thread = Thread { [weak self] in
            while (self != nil && !self!.thread.isCancelled) {
                RunLoop.current.run(
                    mode: RunLoop.Mode.default,
                    before: Date.distantFuture)
            }
            Thread.exit()
        }
        thread.name = "\(threadName)-\(UUID().uuidString)"
        thread.start()
        
        perform(#selector(runBlock),
                on: thread,
                with: nil,
                waitUntilDone: false,
                modes: [RunLoop.Mode.default.rawValue])
    }
    
    public func stopWork() {
        perform(#selector(stopThread),
                on: thread,
                with: nil,
                waitUntilDone: false,
                modes: [RunLoop.Mode.default.rawValue])
    }
    
    @objc func stopThread() {
        Thread.exit()
    }
    
}
```

and the meat from the actual [implementation](https://github.com/ruuvi/com.ruuvi.station.ios/blob/realm-report/station/Classes/Business/Daemons/Background/Heartbeat/BTKit/RuuviTagHeartbeatDaemonBTKit.swift): 

```
import Foundation
import RealmSwift

class RuuviTagHeartbeatDaemonBTKit: BackgroundWorker {

func start() {
        start { [weak self] in
            self?.invalidateTokens()
            self?.realm = try! Realm()
            self?.ruuviTags = self?.realm.objects(RuuviTagRealm.self).filter("isConnectable == true")
            self?.ruuviTagsToken = self?.ruuviTags?.observe({ [weak self] (change) in
                switch change {
                case .initial:
                    break
                case .update(_, let deletions, let insertions, _):
                    if deletions.count > 0 || insertions.count > 0 {
                        self?.handleRuuviTagsChange()
                    }
                case .error(let error):
                    print(error.localizedDescription)
                }
            })
        }
    }
    
    func stop() {
        invalidateTokens()
        stopWork()
    }

   func onReceivedData() {
        let pair = RuuviTagHeartbeatDaemonPair(uuid: uuid, device: ruuviTag)
        self.perform(#selector(RuuviTagHeartbeatDaemonBTKit.persist(_:)),
        on: self.thread,
        with: pair,
        waitUntilDone: false,
        modes: [RunLoop.Mode.default.rawValue])
   }

   @objc private func persist(_ pair: RuuviTagHeartbeatDaemonPair) {
       // save to the realm for this particular thread
    }

}
```

and the [crashlog.crash.zip](https://github.com/realm/realm-cocoa/files/3914959/crashlog.crash.zip)

## Version of Realm and Tooling
Realm framework version: 4.1.1

Xcode version: Version 11.2.1 (11B500)

iOS/OSX version: iOS 13.2.2

Dependency manager + version: cocoapods 1.8.4

**Comment by rinat-enikeev** [comment]
What I found from Realm docs:  

> you may call `invalidate` on Realm
> use `shouldCompactOnLaunch` 
> wrap Realm usage into autoreleasepool

I'm going to try everything from this list, if there is a chance to fix the crash.

**Comment by davidchristiandy** [comment]
hi @rinat-enikeev , did you try the solutions that you've found and did it work for your case?

**Comment by rinat-enikeev** [comment]
Hi @davidchristiandy. I tried `invalidate` and `shouldCompactOnLaunch` and didn't see the crashes yet. But I have no strong confidence that I won't see them.

**Comment by rinat-enikeev** [comment]
reproduced 
> Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 7516192768 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 7516192768 offset: 0, Error Code=9}:

**Comment by ericjordanmossman** [comment]
@rinat-enikeev 
[Compaction](https://realm.io/docs/swift/latest/#compacting-realms) will address free space that accumulates over time through normal use. However file size growth encountered while [mutli-threading](https://realm.io/docs/swift/latest/#threading) has to be addressed through correct practice.

Please [read through this thread](https://github.com/realm/realm-cocoa/issues/5931) to ensure you're not pinning a Realm version across threads.
