### ISSUE TITLE
Creating a unmanaged object using a managed object does not copy ignored properties

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-cocoa#6373]
I noticed that when created a unmanaged object by using `Foo(value: realmFoo)` does not copy the ignored properties, even if they have values. I was able to detect using the Xcode debugger and verifying the Realm object and the non managed instance of this Realm object.

## Goals
Copy all possible fields by using Foo(value:)

## Expected Results
All values, even the ignored ones being copied

## Actual Results
Only Realm values are copied.

## Steps to Reproduce
Just copy the script below in a test example. I hope you are able to reproduce it.

## Code Sample
```swift
class Foo: Object {

  @objc dynamic var id: Int = -1
  @objc dynamic var bar: Int = -1

  //init

  override class func ignoredProperties() -> [String] {
    return ["id"]
  }

  override static func primaryKey() -> String? {
    return "bar"
  }

}
```

Then call:

```swift
let realmFoo = realm.object(Foo.self, primaryKey)!
print("\(realmFoo.id)") //Returns 100 for example
let copyFoo = Foo(value: realmFoo)
print("\(copyFoo.id)") //Returns -1
```

## Version of Realm and Tooling

Realm framework version: 4.1.1

Realm Object Server version: ?

Xcode version: 11.2.1

iOS/OSX version: 13

Dependency manager + version: Framework compiled manually using Realm's script

**Comment by tgoyne** [comment]
This is working as intended. Ignored properties do not exist at all as far as Realm is concerned.

**Comment by ppamorim** [comment]
@tgoyne Let me fix the description:
```swift
let realmFoo = realm.object(Foo.self, primaryKey)!
realmFoo.id = 100
print("\(realmFoo.id)") //Returns 100
let copyFoo = Foo(value: realmFoo)
print("\(copyFoo.id)") //Returns -1
```

Why Realm cannot copy ignored values from a managed version? What `Object(value:)` stands for? Shouldn't be a deep copy?

**Comment by tgoyne** [comment]
Realm does not copy ignored properties because the whole point of ignoring a property is to have Realm not touch it.

**Comment by ppamorim** [comment]
@tgoyne This should be written in the documentation. I think Realm should copy ignored properties when using `Object(value:)` since they are Swift classes. Or at least add a new constructor allowing deep copy of the value. 
For my application I will be overriding this initializer.
