### ISSUE TITLE
Support this form

### ISSUE THREAD

**Issue by LAnqxpp** [realm/realm-cocoa#6378]
NSString *sqlsql = @"select t.PLAN_ID,p.TITLE,SUM(t.MINUTE_COUNT) as total from TIME_RECORD_ENTITY as t left join PLAN_ENTITY as p on t.PLAN_ID = p.OBJECT_ID GROUP BY t.PLAN_ID";

**Comment by ppamorim** [comment]
Realm is not SQL, sorry.

**Comment by bmunkholm** [comment]
True. @LAnqxpp that is something we don't plan doing.
