### ISSUE TITLE
Compile weak_realm_notifier.cpp error

### ISSUE THREAD

**Issue by weiminghuaa** [realm/realm-cocoa#6402]
pod 'RealmSwift', '~> 5.0.0-beta.1'

compile error: 

Showing Recent Errors Only
/Pods/Realm/include/core/realm/alloc.hpp:376:19: Aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer
inline Allocator::~Allocator() noexcept

5.0.0 is only support iOS 11 or newer?

**Comment by weiminghuaa** [comment]
<img width="961" alt="截屏2020-01-1315 40 18" src="https://user-images.githubusercontent.com/2723525/72239166-08549800-361b-11ea-9565-341324d9ec83.png">

**Comment by tgoyne** [comment]
Looks like I forgot to add `-fno-aligned-new` to the podspec when I added it to the xcode project.

**Comment by weiminghuaa** [comment]
How can I add hook like this?

`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_ENABLE_OBJC_GC'] = 'supported'
     config.build_settings['COMPILER_FLAGS'] = '-fno-aligned-new'
    end
  end
end`

**Comment by tgoyne** [comment]
This should be fixed in v5.0.0-beta.2.
