### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by vincedev** [realm/realm-cocoa#6403]
## Goals

No particular goal, our application is crashing.

## Expected Results

I expected the app to run as usual.

## Actual Results

The app is crashing. It seems to happen only on macOS 10.10.
Here is an excerpt of the crash report :

```
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: __os_log_default
  Referenced from: /Applications/Application.app/Contents/MacOS/../Frameworks/Realm.framework/Versions/A/Realm
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Application.app/Contents/MacOS/../Frameworks/Realm.framework/Versions/A/Realm
```

It looks like Realm is calling a function that do not exist in `libSystel.B.dylib`.

## Steps to Reproduce

Launching an application using Realm should be sufficient, on macOS 10.10. This particular crash from which the excerpt is taken is happening on macOS 10.10.5 (14F2511).

## Code Sample

No code to share.

## Version of Realm and Tooling

Realm framework version: "v3.21.0"

Realm Object Server version: none

Xcode version: 11.3

iOS/OSX version: macOS 10.10.5 (14F2511)

Dependency manager + version: Carthage, v 0.34.0

## Comments

I'm still trying to understand how this is happening... is it the version of Xcode used to build the dependency ?  
I don't know.. any pointer to a solution will be appreciated.

**Comment by tgoyne** [comment]
It's failing on startup because os_log() doesn't exist yet on macOS 10.10. I'm not sure why Realm.framework is references it, though, as we don't call it anywhere.
