### ISSUE TITLE
Realmswift cocoapod installing issue

### ISSUE THREAD

**Issue by ghost** [realm/realm-cocoa#6405]
Installing Realm (4.3.0)

[!] Error installing Realm
[!] /usr/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/mm/60jtp5m50776pzp211xltmr00000gn/T/d20200116-3562-tnrjjx --template= --single-branch --depth 1 --branch v4.3.0

Cloning into '/var/folders/mm/60jtp5m50776pzp211xltmr00000gn/T/d20200116-3562-tnrjjx'...
fatal: unable to access 'https://github.com/realm/realm-cocoa.git/': Could not resolve host: github.com

**Comment by leemaguire** [comment]
Hi,

What version of Cocoapods are you using?

Thanks,
Lee
