### ISSUE TITLE
getSwiftProperties Memory Leak

### ISSUE THREAD

**Issue by iDevid** [realm/realm-cocoa#6409]
## Actual Results
Seems that there is a memory leak in getSwiftProperties method in Object.swift at line 738
![Schermata 2020-01-20 alle 14 14 44](https://user-images.githubusercontent.com/1254022/72729335-414aba80-3b8f-11ea-836b-40222a6e4ee4.png)

## Steps to Reproduce
Seems that happens during the Realm initialization

## Version of Realm and Tooling

Realm framework version: 4.3.1
Xcode version: 11.2.1
iOS version: 12.0
Dependency manager + version: Cocoapods 1.8.4

**Comment by Greeeeyyyss** [comment]
I'm noticing the same leak when creating first realm instance. 
<img width="1025" alt="Screen Shot 2020-01-22 at 1 31 22 PM" src="https://user-images.githubusercontent.com/10753499/72867976-9582a580-3d1b-11ea-9d6d-028458a73fc2.png">

We're using:
Realm version: 4.1.1
Xcode version: 11.2.1

**Comment by Coledunsby** [comment]
I'm having the same issue using 4.3.1
