### ISSUE TITLE
`RealmSwift` does not specify a Swift version and none of the targets

### ISSUE THREAD

**Issue by hnrqsss** [realm/realm-cocoa#6414]
## Goals
Install RealSwift

## Actual Results
`RealmSwift` does not specify a Swift version and none of the targets (`target name`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

## Steps to Reproduce
Just follow the steps in docs to reproduce
1. Install CocoaPods 1.6.0 or later.
2. Run pod repo update to make CocoaPods aware of the latest available Realm versions.
3. In your Podfile, add use_frameworks! and pod 'RealmSwift' to your main and test targets.
From the command line, run pod install. (Here the error appears)
4. Use the .xcworkspace file generated by CocoaPods to work on your project!

## Code Sample
my podfile:
`
```
platform :ios, '9.0'
use_frameworks!
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'project_name' do
    ...
    pod 'RealmSwift'
   ...
end
```
`
cocoapods version: 
1.6.1
Xcode version: ?
11.1
iOS/OSX version: ?
9.0

Dependency manager + version: ?

**Comment by tgoyne** [comment]
This error should only occur if you're trying to import RealmSwift into a target which doesn't actually use Swift. If you are using Swift you need to set the swift version on that target, and if you aren't then there's no point in pulling in RealmSwift.

**Comment by hnrqsss** [comment]
> This error should only occur if you're trying to import RealmSwift into a target which doesn't actually use Swift. If you are using Swift you need to set the swift version on that target, and if you aren't then there's no point in pulling in RealmSwift.

thank you i 'll try it

**Comment by hnrqsss** [comment]
> This error should only occur if you're trying to import RealmSwift into a target which doesn't actually use Swift. If you are using Swift you need to set the swift version on that target, and if you aren't then there's no point in pulling in RealmSwift.

Could you share with me how can i set it?

**Comment by tgoyne** [comment]
Swift Language Version is one of the settings on the Build Settings tab of the target settings in Xcode.
