### ISSUE TITLE
Realm() threw unrelated error on initialization

### ISSUE THREAD

**Issue by hyouuu** [realm/realm-cocoa#6416]
## Goals
Use Realm normally

## Expected Results
Realm() is created normally

## Actual Results
When calling `try Realm()`, get the following:
Domain: io.realm Code: 10 Migration is required due to the following errors:
- Property '__Class.permissions' has been removed.
- Property '__Role.members' has been removed.

It firstly happened when my laptop is not connected to internet, so the simulator was in airplane mode; then I thought maybe it needs migration once and bumped the schemaVersion by 1; as I connected to internet it threw the same error again. I don't even use Realm sync so I think it's an internal bug.

## Steps to Reproduce
Maybe the above step - airplane mode run app, then connect to internet 

Note I also saw warnings in the console:

warning: the Swift runtime was unable to demangle the type of field 'users'. the mangled type name is '10RealmSwift4ListCy\232l\367\377G'. this field will show up as an empty tuple in Mirrors
2020-01-28 13:18:54.744511-0800 Pendo[99505:6551715] warning: the Swift runtime was unable to demangle the type of field 'users'. the mangled type name is '10RealmSwift4ListCy\^A\M^Zl\M-w\M^?G'. this field will show up as an empty tuple in Mirrors
warning: the Swift runtime was unable to demangle the type of field 'permissions'. the mangled type name is '10RealmSwift4ListCy\266k\367\377G'. this field will show up as an empty tuple in Mirrors
2020-01-28 13:18:54.745265-0800 Pendo[99505:6551715] warning: the Swift runtime was unable to demangle the type of field 'permissions'. the mangled type name is '10RealmSwift4ListCy\^A\M-6k\M-w\M^?G'. this field will show up as an empty tuple in Mirrors
warning: the Swift runtime was unable to demangle the type of field 'roles'. the mangled type name is '10RealmSwift14LinkingObjectsVyl\367\377G'. this field will show up as an empty tuple in Mirrors
2020-01-28 13:18:54.745910-0800 Pendo[99505:6551715] warning: the Swift runtime was unable to demangle the type of field 'roles'. the mangled type name is '10RealmSwift14LinkingObjectsVy\^A\^Sl\M-w\M^?G'. this field will show up as an empty tuple in Mirrors

## Code Sample
func genRlm() -> Realm {
    var rlm: Realm?
    do {
        rlm = try Realm()

    } catch let err {
        print("try Realm() err:\(err.localizedDescrption)")
      
        // For now just try again
        rlm = try? Realm()
    }
}

## Version of Realm and Tooling
productName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57

/Applications/Xcode.app/Contents/Developer
Xcode 11.3.1
Build version 11C504

/Users/shawngong/.rvm/gems/ruby-2.5.3/bin/pod
1.9.0.beta.2
Realm (4.3.1)
RealmSwift (4.3.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

carthage not found
(not in use here)

/usr/bin/git
git version 2.21.1 (Apple Git-122.3)
```

Realm Object Server version: Not using

iOS simulator version: 13.3

**Comment by leemaguire** [comment]
Hi,

I have not been able to reproduce this issue with your code sample and configuration. Could you please provide more context on how you are using Realm, or send us a sandbox app that can reproduce this issue.

Thanks,
Lee

**Comment by hyouuu** [comment]
Thanks for looking into this @leemaguire! This was when I ran on a simulator but then somehow it stopped from showing up for normal runs. However, it still shows the error if I run in XCTests when there is @testable import ProjectName - maybe you could try run some XCTests and see if it's reproducible for you?

**Comment by leemaguire** [comment]
@hyouuu This is not reproducible on our end. Can you please send us a sandbox app that can reproduce this issue.

Thanks,
Lee

**Comment by hyouuu** [comment]
Sorry I won't have time to make a sandbox app in the near future as I'm super occupied recently. Since it seems to only affect unit test I'll just close for now. Thanks for looking into this!
