### ISSUE TITLE
Support `xcframework` for distribute binary framework

### ISSUE THREAD

**Issue by cuongtv51** [realm/realm-cocoa#6424]
## Goals
Make RealmSwift dependency for custom binary framework 

## Expected Results
Can build `xcframework` with RealmSwift as dependency

## Actual Results
`Module 'RealmSwift' was not compiled with library evolution support; using it means binary compatibility for 'xxx' can't be guaranteed`

## Steps to Reproduce
Install RealmSwift with steps of `Dynamic Framework`
When import RealmSwift & build, it produce:
`Module 'RealmSwift' was not compiled with library evolution support; using it means binary compatibility for 'xxx' can't be guaranteed`

## Version of Realm and Tooling
Realm framework version: 4.3.2

Realm Object Server version: ?

Xcode version: 11.3.1

iOS/OSX version: 10.15.1

Dependency manager + version: None

**Comment by tgoyne** [comment]
You can manually build a xcframework for Realm by cloning the repo and running `sh build.sh xcframework`, but enabling library evolution mode breaks `objc_copyClassList()` which means that we are unable to automatically discover your `Object` subclasses and you must instead explicitly list the types in your `Realm.Configuration`.

**Comment by cuongtv51** [comment]
When i run `sh build.sh xcframework` on Mac 10.15.1, Xcode 11.3.1, It has error:
`Libtool /Users/cuongkc/Projects/realm-cocoa/build/DerivedData/Realm/Build/Products/Release/Realm.framework/Versions/A/Realm normal x86_64 (in target 'Realm' from project 'Realm')
    cd /Users/cuongkc/Projects/realm-cocoa
    export MACOSX_DEPLOYMENT_TARGET=10.9
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -D -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/cuongkc/Projects/realm-cocoa/build/DerivedData/Realm/Build/Products/Release -Lcore -filelist /Users/cuongkc/Projects/realm-cocoa/build/DerivedData/Realm/Build/Intermediates.noindex/Realm.build/Release/Realm.build/Objects-normal/x86_64/Realm.LinkFileList -lrealm-maccatalyst -target x86_64-apple-ios13.0-macabi -o /Users/cuongkc/Projects/realm-cocoa/build/DerivedData/Realm/Build/Products/Release/Realm.framework/Versions/A/Realm
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `t' in: -target
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
Command Libtool failed with a nonzero exit code

** BUILD FAILED **
`
Then i remove disable build for `catalyst` vs `catalyst-swift`, It work ok, 
It produce 3 xcframework: Realm, RealmObjc, RealmSwift xcframework
I put 3 framework to build my xcframework, when it run test, 
I log with
`
objc[9967]: Class RLMThreadSafeReference is implemented in both /Users/cuongkc/Library/Developer/Xcode/DerivedData/MyKit-brwraifuraywqodllqaefqtgsptk/Build/Products/Debug-iphonesimulator/Realm.framework/Realm (0x105732e08) and /Users/cuongkc/Library/Developer/Xcode/DerivedData/MyKit-brwraifuraywqodllqaefqtgsptk/Build/Products/Debug-iphonesimulator/RealmSwift.framework/RealmSwift (0x104d5be30). One of the two will be used. Which one is undefined.
`
Then It crash with 
`
Terminating app due to uncaught exception 'RLMException', reason: 'Object type 'PersionList' is not managed by the Realm. If using a custom `objectClasses` / `objectTypes` array in your configuration, add `PersionList` to the list of `objectClasses` / `objectTypes`.'
`

**Comment by cuongtv51** [comment]
Are there any updates on this?
