### ISSUE TITLE
Compile error when RealmSwift bridge Objective-C ++

### ISSUE THREAD

**Issue by weiminghuaa** [realm/realm-cocoa#6425]
ViewController.mm
```
#import "ViewController.h"
#import "TestMMC-Swift.h"

NSString *const kJoyrunCacheDocumentPath = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject] stringByAppendingPathComponent:@"message"];

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // ...
}
@end
```

XMMessage.swift
```
class XMMessage: Object, HandyJSON {
    @objc dynamic var sequnce = 0
    @objc dynamic var packetId = ""
    
    override static func primaryKey() -> String? {
        return "packetId"
    }
}
```

Compile error:

In file included from /Users/weiminghua/Documents/test/TestMMC/TestMMC/ViewController.mm:10:
/Users/weiminghua/Library/Developer/Xcode/DerivedData/TestMMC-esgjzclasjgelictgaogrncmaypv/Build/Intermediates.noindex/TestMMC.build/Debug-iphonesimulator/TestMMC.build/DerivedSources/TestMMC-Swift.h:217:24: error: **cannot find interface declaration for 'RealmSwiftObject', superclass of 'XMMessage'**
@interface XMMessage : RealmSwiftObject

**Comment by jsflax** [comment]
I have tested calling a Realm `Object` declared in Swift from ObjC and did not encounter issues.

Could you please answer the following:

- How are you including the `RealmSwift` dependency? Pods? Carthage? SPM? 

Also, sending along a self contained project with your issue would be helpful.

**Comment by jsflax** [comment]
Apologies, I misunderstood that you were calling this from ObjC++. 

It is not possible to call Swift from ObjC++: https://stackoverflow.com/questions/24042774/can-i-mix-swift-with-c-like-the-objective-c-mm-files.

I would recommend following the advice of that issue:

> You cannot import C++ code directly into Swift. Instead, create an Objective-C or C wrapper for C++ code.
