### ISSUE TITLE
Xcode11.3.1: property cannot be marked @objc because its type cannot be represented in Objective-C

### ISSUE THREAD

**Issue by sandeepbol** [realm/realm-cocoa#6426]
## Goals
I have a code that's similar to the model example given in RealmSwift official documentation:
```swift
import RealmSwift

// Dog model
class Dog: Object {
    @objc dynamic var name = ""
    @objc dynamic var owner: Person? // Properties can be optional
}

// Person model
class Person: Object {
    @objc dynamic var name = ""
    @objc dynamic var birthdate = Date(timeIntervalSince1970: 1)
    let dogs = List<Dog>()
}
```

## Expected Results
I expect code to compile with Xcode 11.3.1 as it does with Xcode 10.3.

## Actual Results

Instead, it throws an error

> property cannot be marked @objc because its type cannot be represented in Objective-C

right at the second line in `Dog` declaration where `owner` is declared.

## Steps to Reproduce

This is the exact command used:

```sh
xcodebuild -workspace "${FRAMEWORK_NAME}.xcworkspace" -scheme "${FRAMEWORK_NAME}" -configuration "${CONFIGURATION}" -arch arm64 -arch armv7 only_active_arch=no CLANG_ENABLE_CODE_COVERAGE=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO BITCODE_GENERATION_MODE=bitcode BUILD_LIBRARY_FOR_DISTRIBUTION=YES defines_module=yes -sdk "iphoneos" -derivedDataPath "${OUTPUT_DIR}"
```

The error is thrown both in Xcode and CI environment with Xcode 11.3.1 (11C504) command-line tools. I tried changing command-line tools to 10.3 (10G8) but results are the same. Has anyone faced this issue?

## Version of Realm and Tooling

Realm framework version: 4.3.2

Xcode version: 11.3.1

iOS/OSX version: macOS Catalina 10.15.2

Dependency manager + version: ? cocoapod version 1.8.4

**Comment by sandeepbol** [comment]
turned out `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` option was the cause of trouble, I have no idea why. The issue had nothing to do with the realm. Sorry for creating a non-realm issue. Closing, Thanks.

**Comment by lixiaoyu** [comment]
@sandeepbol Hello, i meet same issues,is there any solution if BUILD_LIBRARY_FOR_DISTRIBUTION=YES  is required. For our  framework need to be distribution to support swift evolution.

**Comment by sandeepbol** [comment]
@lixiaoyu We are using xcframework now. So this issue is not relevant. We are using [create_xcframework](https://github.com/bielikb/fastlane-plugin-create_xcframework) plugin in Fastlane and it works like a charm. BUILD_LIBRARY_FOR_DISTRIBUTION=YES is ensured.

**Comment by lixiaoyu** [comment]
oh thanks @sandeepbol,it works!
