### ISSUE TITLE
Realm inconsistent data in background query

### ISSUE THREAD

**Issue by raphaels17** [realm/realm-cocoa#6432]
**Bugs**: 
I run the exact Same query

it returns zero when the app is on the foreground and else 24 ????. the correct value is zero. the realm is running on autorefresh... still the same result is I relaunch the app

## Goals
have a correct result

## Expected Results
queyr return zero in background

## Actual Results
return last 24 objects

## Version of Realm and Tooling

Realm framework version: 'RealmSwift', '~> 3.18.0'

Xcode version: Version 11.3.1 

iOS/OSX version:  113.1

**Comment by leemaguire** [comment]
Hi,

Can you send us a sample app showing us how you are using Realm?

Thanks,
Lee

**Comment by raphaels17** [comment]
Found the mystery. due to the magic of threading, another one was modifying my realm in a part of the code i didn't. so quiet on the contrary realm works like a charm
