### ISSUE TITLE
Module 'RealmSwift' was created for incompatible target x86_64-apple-macos10.9

### ISSUE THREAD

**Issue by gezn** [realm/realm-cocoa#6446]
## Goals
I want to compile RealmSwift as a swift dependency after I saw on the GitHub repository that it comes with a package file
## Expected Results

after adding the repository and the version, it should be able to compile.
## Actual Results
I am getting  the following error at compile time
Module 'RealmSwift' was created for incompatible target x86_64-apple-macos10.9
## Steps to Reproduce
add latest RealmAwift as a swift dependency on Xcode, by the time I write this is version 4.3.2
## Code Sample
import RealmSwift
## Version of Realm and Tooling
Realm framework version: 4.3.2

Xcode version:  11.3.1

Dependency manager + version:  swift package manager from Xcode

**Comment by leemaguire** [comment]
Hi @gezn 

When using SPM the minimum deployment target is macOS 10.0 

It is described here: https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html

To solve this issue I would suggest bumping your deployment target to macOS 10.10
