### ISSUE TITLE
Crash is happening on Realm() ! after migration

### ISSUE THREAD

**Issue by kishore94** [realm/realm-cocoa#6447]
I have added do , catch statement to see what kind of error it is throwing but it is not returning anything .

**What I did ?**

1. I have updated Realm from 3.20.0 to 4.3.2 
2. Removed the deprecated methods .
3. Trying to run crashed 

**Realm Configuration** 

```
var config = Realm.Configuration()
        config.deleteRealmIfMigrationNeeded = true;
        let fileManager = FileManager.default
        if let directory = fileManager.containerURL(forSecurityApplicationGroupIdentifier: "group.b.share") {
            let newDirectory = directory.appendingPathComponent("default.realm")
            try? fileManager.createDirectory(at: newDirectory, withIntermediateDirectories: false, attributes: nil)
            config.fileURL = newDirectory
        }
        Realm.Configuration.defaultConfiguration = config
```

**Where it is crashing ?**

```
[public init() throws {
        let rlmRealm = try RLMRealm(configuration: RLMRealmConfiguration.default())
        self.init(rlmRealm)
    }
]
```

**How I am trying to access it** 

    [static func getObjects<T:Object>()->[T] {
        do{
            let realm = try Realm()
            let realmResults = realm.objects(T.self)
            return Array(realmResults)
        }catch let error as NSError {
            print(error.localizedDescription)
            return []
        }
       
        
    }]

**Source**

Xcode 11.3.1
Swift 5

**Comment by leemaguire** [comment]
Hi @kishore94 

- Would you be able to give us the stack trace from your crash?
- Could you place a `do catch` around `try? fileManager.createDirectory(at: newDirectory, withIntermediateDirectories: false, attributes: nil)`
- Where in your app are you setting the configuration?

Thanks, 
Lee

**Comment by kishore94** [comment]
@leemaguire yes I have added those code also and I am using do catch still nothing is coming in catch

**Comment by leemaguire** [comment]
@kishore94 I would check if the Realm file exists in that location and then not proceed with creating the directory.

**Comment by kishore94** [comment]
@leemaguire but crash is not happening at that position it is happening when trying to access it .

**Comment by leemaguire** [comment]
@kishore94 Would you be able to send us a stack trace or crash log from your issue?

**Comment by kishore94** [comment]
@leemaguire  I am getting dyld: Symbol not found: _$s10RealmSwift6ObjectC10dynamicGet33_95A69397B44B27F7A8F436871D45D9E6LL3keyypSgSS_tF

in crash report

**Comment by kishore94** [comment]
dyld: Symbol not found: _$s10RealmSwift6ObjectC10dynamicGet33_95A69397B44B27F7A8F436871D45D9E6LL3keyypSgSS_tF
  Referenced from: /Users/kk/Library/Developer/CoreSimulator/Devices/F1121A4D-B79B-4DB4-9086-7B7E8527A269/data/Containers/Bundle/Application/2CFD3AB6-79C3-42C9-AD52-85CEED955777/Brand Dev.app/Brand Dev
  Expected in: /Users/kk/Library/Developer/CoreSimulator/Devices/F1121A4D-B79B-4DB4-9086-7B7E8527A269/data/Containers/Bundle/Application/2CFD3AB6-79C3-42C9-AD52-85CEED955777/Brand Dev.app/Frameworks/RealmSwift.framework/RealmSwift
 in /Users/kk/Library/Developer/CoreSimulator/Devices/F1121A4D-B79B-4DB4-9086-7B7E8527A269/data/Containers/Bundle/Application/2CFD3AB6-79C3-42C9-AD52-85CEED955777/Brand Dev.app/Brand Dev

**Comment by jsflax** [comment]
@kishore94 Can you try updating to the latest version? Also what "deprecated methods" are you removing? That's likely to be the cause of this crash.
