### ISSUE TITLE
Able to perform CRUD operations even if we delete .realm file from disk storage in a running app

### ISSUE THREAD

**Issue by Dinesh370** [realm/realm-cocoa#6449]
**Questions**: Able to perform CRUD operations even if we delete .realm file from disk storage in a running app

**Feature Request**: 

**Bugs**: Able to perform CRUD operations even if we delete .realm file from disk storage in a running app

## Goals
If .realm file is deleted in a running app, it should be created automatically with blank model.

## Expected Results
If .realm file is deleted in a running app, .realm file should be created with 0 records in models

## Actual Results
If .realm file is deleted in a running app, .realm file is not created and if we print model records, realm model is  giving results and able to add more records in model.

## Steps to Reproduce
Steps:
1. Created "test.realm" file on disk storage using below line of code:
`var config = Realm.Configuration()
config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent("test.realm")`

2. Open the realm database with realm config using below line of code:
`realm = try! Realm(configuration: config)`

3. Created a dog model:
`class Dog: Object {
    @objc dynamic var name = ""
    @objc dynamic var age = 0
}`

4. On a button click, adding data to dog model.
`let myDog = Dog()`
`myDog.name = names.randomElement()! //names array`
`myDog.age = Int.random(in: 1 ... 100)`
`try! realm.write {`
    `realm.add(myDog)`
`}`

5. Deleted .realm file using below line of code:
`let file = Realm.Configuration.defaultConfiguration.fileURL!
try? FileManager.default.removeItem(at: file)`

6. Now performing the step 4 and printing records:
`let results = realm.objects(Dog.self)`

Data is added successfully even .realm file is not present on disk.

7. Kill and relaunch the app. Now .realm file is created again with zero records.

## Code Sample

    override func viewDidLoad() {
        super.viewDidLoad()
        setDefaultRealmForUser()
        printData("")
    }
    
    func setDefaultRealmForUser() {
        var config = Realm.Configuration()

        // Use the default directory, but replace the filename with the username
        config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent("test.realm")

        // Set this as the configuration used for the default Realm
        Realm.Configuration.defaultConfiguration = config

        // Open the Realm with the configuration
        realm = try! Realm(configuration: config)
        
        print(Realm.Configuration.defaultConfiguration.fileURL)
    }
    
    @IBAction func addData(_ sender: Any) {
        self.lblData.text = ""
        // Use them like regular Swift objects
        let myDog = Dog()
        myDog.name = names.randomElement()!
        myDog.age = Int.random(in: 1 ... 100)
        print("name of dog: \(myDog.name)")
        
        // Persist your data easily
        try! realm.write {
            realm.add(myDog)
        }
        
        printData(sender)
    }
    
    @IBAction func deleteRealm(_ sender: Any) {
        self.lblData.text = ""
        let file = Realm.Configuration.defaultConfiguration.fileURL!
        try? FileManager.default.removeItem(at: file)
        printData(sender)
    }
    
    @IBAction func printData(_ sender: Any) {
        // Read some data from the bundled Realm
        let results = realm.objects(Dog.self)
        self.lblData.text = "Total results: \(results.count)"
    }

## Version of Realm and Tooling
Realm framework version: RealmSwift

Realm Object Server version: 

Xcode version: 11.3.1

iOS/OSX version: 13

Dependency manager + version: CocoaPods

**Comment by anshulsolanki89** [comment]
We are also facing similar issue in our project. Tried lot of things but nothing seemed to work.

**Comment by tgoyne** [comment]
Deleting a file which is open on unix-like platforms merely removes the entry in the filesystem linking the name to the inode, and the file is not actually deleted until it's closed. Since the Realm is already open when you delete the file, we continue to read from and write to the now nameless file until it's closed and reopened.
