### ISSUE TITLE
Getting a frequent crash report from apple.

### ISSUE THREAD

**Issue by ahsanaasim** [realm/realm-cocoa#6451]
!!! Realm: please_report_this_error_to_help_at_realm_dot_io + 12 !!!

We are getting this crash report from apple. This actually doesn't happen in our devices or while debugging. We couldn't reproduce. But we are getting this error in apple dashboard and firebase crashlytics. Maybe its an internal crash or something.
**Attached the xccrashpoint file below**
[IDpM9PtaBzywPifkSNnkr.xccrashpoint.zip](https://github.com/realm/realm-cocoa/files/4334017/IDpM9PtaBzywPifkSNnkr.xccrashpoint.zip)

## Goals
As this crash is reported frequently, we are getting negative impressions. So we need to get this issue resolved as soon as possible.

## Steps to Reproduce
The crash occurs in this line. 
```
try realm.write {
                    realm.add(self, update: .all)
                }
```

## Code Sample
```
func savePrayerTime() -> Promise<PrayerTimeScheduler> {
        return Promise<PrayerTimeScheduler> { seal in
            do {
                let realm = try Realm()
                try realm.write {
                    realm.add(self, update: .all)
                }
                seal.fulfill(self)
            } catch {
                print("Unexpected error: \(error).")
                seal.reject(error)
            }
        }
    }
```

## Version of Realm and Tooling
Realm framework version: 4.3.2

Realm Object Server version: nil

Xcode version:  11.3.1 (11C505)

iOS/OSX version: iOS 13.3

Dependency manager + version: cocoapod 1.8.4

**Comment by leemaguire** [comment]
@ahsanaasim It is possible that this is related to threading, can you please ensure that if your objects are passed between threads you are using `ThreadSafeReferences`

Thanks,
Lee
