### ISSUE TITLE
Direct property access gives nil, while subscript gives actual value

### ISSUE THREAD

**Issue by javruben** [realm/realm-cocoa#6459]
## Goals
Access a property via `myObject.propertyName`, but I can only access the value via `myObject["propertyName"]`

## Expected Results
```
print(realmItem!["uid"]!) // Prints 0x05
print(realmItem!.uid) // Prints 0x05
```

## Actual Results
```
print(realmItem!["uid"]!) // Prints 0x05
print(realmItem!.uid) // Prints nil
```

## Code Sample
I didn't test this code, but this is basically what I'm doing.
```
class Note:DataItem {
    @objc var title:String? = nil
}
class DataItem:Object {
    @objc var uid:String? = nil
}
let typeTable:[String:Object.Type] = [
    "note": Note.self
]
try! self.realm!.write() {
    realm.add(Note(uid:"0x05", title:"test"))
}
let type = self.typeTable["note"]
if let type = type {
    let obj = realm.objects(type).filter("uid = '\(0x05)'").first
    print(obj!["uid"]!) // Prints 0x05
    print(obj!.uid) // Prints 0x05
}
```

## Version of Realm and Tooling
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

/Applications/Xcode.app/Contents/Developer
Xcode 11.4
Build version 11E146

pod not found
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

carthage not found
(not in use here)

/usr/bin/git
git version 2.24.1 (Apple Git-126)

**Comment by tgoyne** [comment]
You need to declare your properties as `@objc dynamic` and not just `@objc`.

**Comment by javruben** [comment]
Ah thanks! The reason for removing dynamic is that setting uid in the init of Note like this fails:

```
required init () {
    super.init()     
    uid = "0x01"
}
```

With the error: `Thread 1: EXC_BAD_ACCESS (code=1, address=0x18`

This is a probably a noob issue, but your guidance is appreciated.

**Comment by tgoyne** [comment]
Setting the default value in the property definition rather than in the init function should fix that.
