### ISSUE TITLE
Install with `Dynamic Framework` method should include a fat framework or `xcframework` for support universal target

### ISSUE THREAD

**Issue by cuongtv51** [realm/realm-cocoa#6464]
## Goals
I have prj that target support `iphone`, `ipad`, `mac(catalyst)`
Now, i have split to 2 target & take 2 step to import framework

## Expected Results
We should include a fat framework or `xcframework` to support universal target

## Version of Realm and Tooling
Realm framework version: 4.4.0

Realm Object Server version: ?

Xcode version: 11.4

iOS/OSX version: 10.15.4

Dependency manager + version: ?

**Comment by tgoyne** [comment]
A Catalyst fat framework is not possible. Simulator/device fat frameworks are a hack that take advantage of that the two platforms don't have any overlap in supported architectures, but that's no longer the case with Catalyst.

XCFrameworks unfortunately require building with Swift Evolution mode, which comes with changes to the language semantics that break Realm.
