### ISSUE TITLE
Realm crash at "-[RLMRealm dealloc]"

### ISSUE THREAD

**Issue by KlausLiu** [realm/realm-cocoa#6466]
We encountered some crashes in published packages.

![image](https://user-images.githubusercontent.com/957847/78339355-ed187980-75c6-11ea-92b7-3cd281a1d3f0.png)

```
libsystem_kernel.dylib	__pthread_kill + 8
libsystem_pthread.dylib	_pthread_kill$VARIANT$mp + 380
libsystem_c.dylib	abort + 140
Realm	realm::util::terminate(char const*, char const*, long)
Realm	realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 264
Realm	realm::util::terminate_with_info(char const*, char const*, long, char const*, std::initializer_list<realm::util::Printable>&&) + 388
Realm	realm::util::File::map(realm::util::File::AccessMode, unsigned long, int, unsigned long) const
Realm	realm::util::File::unlock() + 100
Realm	realm::SharedGroup::close_internal(std::__1::unique_lock<realm::util::InterprocessMutex>) + 580
Realm	realm::SharedGroup::~SharedGroup() + 48
Realm	std::__1::unique_ptr<realm::SharedGroup, std::__1::default_delete<realm::SharedGroup> >::reset(realm::SharedGroup*) (memory:2339)
Realm	realm::Realm::~Realm() (memory:2649)
Realm	std::__1::shared_ptr<realm::_impl::CollectionNotifier>::~shared_ptr() (memory:3587)
libobjc.A.dylib	object_cxxDestructFromClass(objc_object*, objc_class*) + 148
libobjc.A.dylib	objc_destructInstance + 68
libobjc.A.dylib	object_dispose + 16
Realm	-[RLMRealm dealloc] (RLMRealm.mm:776)
libobjc.A.dylib	(anonymous namespace)::AutoreleasePoolPage::pop(void*) + 672
CoreFoundation	_CFAutoreleasePoolPop + 28
CoreFoundation	___CFRunLoopRun + 1932
CoreFoundation	CFRunLoopRunSpecific + 436
GraphicsServices	GSEventRunModal + 104
UIKitCore	UIApplicationMain + 212
MyApp	main (<compiler-generated>:0)
libdyld.dylib	_start + 4
```

Realm framework version: v4.3.2

Xcode version: 11.3.1 (11C505)

**Comment by KlausLiu** [comment]
Is there a response?

**Comment by leemaguire** [comment]
Hi @KlausLiu,

Could you give us some context on how are using Realm? Are you by any chance trying to write to the database when he app is in a background state?

Thanks,
Lee

**Comment by KlausLiu** [comment]
@leemaguire  Thanks for reply.
Write to the database when the app is in a background state is not supported?

**Comment by leemaguire** [comment]
Writing to the database while in the background is supported. 

Please see our documentation on this: https://realm.io/docs/swift/latest/#using-realm-with-background-app-refresh

I think you may be running into an NSFileProtection error, where the operating system is locking the .realm file while the app is in the background.

**Comment by KlausLiu** [comment]
We will run the following code when app launch

```
let realmVersion: UInt64 = 5
var configuration = Realm.Configuration()
configuration.schemaVersion = realmVersion
if let userId = loginUserId,
  let fileURL = configuration.fileURL {
  configuration.fileURL = fileURL.deletingLastPathComponent().appendingPathComponent("\(userId).realm")
}
configuration.migrationBlock = { migration, oldSchemaVersion in
  // Do some migration
}
Realm.Configuration.defaultConfiguration = configuration

// Get our Realm file's parent directory
let folderPath = Realm.Configuration.defaultConfiguration.fileURL!.deletingLastPathComponent().path

// Disable file protection for this directory
try? FileManager.default.setAttributes([FileAttributeKey.protectionKey: FileProtectionType.none],
                                        ofItemAtPath: folderPath)
```

**Comment by KlausLiu** [comment]
We have not encountered this crash before 2.10 (the version of our application), and the realm version is also v4.3.2.
In 2.10, we deleted a class that inherited from Object, and did nothing else.

**Comment by KlausLiu** [comment]
@leemaguire Can you help us?

**Comment by leemaguire** [comment]
@KlausLiu your realm initialisation code looks fine. As far as you deleting a class that inherits from `Object` goes, once you handle the migration correctly there should be no issues. 

The stack trace you have provided to us more so indicates that your crash is related to file locking issues, as seen here : `Realm	realm::util::File::unlock() + 100`

Do you have any analytics around when this crash happens? i.e. you see an event where the app is sent to the background and then the crash occurs?

**Comment by KlausLiu** [comment]
> once you handle the migration correctly there should be no issues.
How to handle the migration when deleting a class that inherits from `Object`?

We see information similar to this in the log.

```
04-09 17:26:16.756 UIApplication WillResignActive
04-09 17:26:16.788 UIApplication DidEnterBackground
04-09 17:38:49.628 UIApplication WillEnterForeground
04-09 17:38:50.219 UIApplication DidBecomeActive
04-09 17:38:50.649 UIApplication WillResignActive
04-09 17:38:51.256 UIApplication DidEnterBackground (crash here)
```
```
04-09 16:08:50.526 UIApplication DidBecomeActive (crash here)
```
```
04-08 14:53:59.693 UIApplication WillResignActive
04-08 14:53:59.790 UIApplication DidEnterBackground
04-08 14:54:00.456 UIApplication WillEnterForeground
04-08 14:54:00.504 UIApplication DidBecomeActive
04-08 14:54:01.813 [ OurViewController ] WillAppear (crash here)
```

**Comment by leemaguire** [comment]
I would run something like this to delete all data related to your old `Object`

`Realm.Configuration(schemaVersion: 11, migrationBlock: { migration, oldSchemaVersion in
    if oldSchemaVersion < 11
        migration.deleteData(forType: Account.className)
        ...`
