### ISSUE TITLE
Include deleted / invalidated objects in results provided by the callback of addNotificationBlock

### ISSUE THREAD

**Issue by peteranny** [realm/realm-cocoa#6479]
## Goals
```
RLMResults.addNotificationBlock((results: RLMResults, change: RLMCollectionChange, error: Error))
``` 
The method receives uncorresponding `results` and `change`, which might need a fix.

## Expected Results
If there are deletions in `change`, **corresponding deleted / invalidated objects should be included in `results`** so that every index in `change` (insertions, modifications, deletions) refers to the correct one object in `results`.

## Actual Results
The deleted objects are not included in `results`. Hence indices of modifications or insertions may refer to the wrong position in `results`.

In edge cases with deletions, accessing `results` with `change.modification` or `change.insertions` will lead to crash like:
```
Terminating app due to uncaught exception 'RLMException', reason: 'Index 1 is out of bounds (must be less than 1).'
```

## Steps to Reproduce
1. Monitor changes to a realm collection. Access modified objects with indices provided by `change` every time it receives a notification.
1. Add objects to the collection in one transaction
1. Modify the last object and remove another object in one transaction

- Expected: The modified index provided by `change` corresponds to `results` is correct
- Actual: The modified index provided by `change` does not correspond to `results`

## Code Sample
Podfile:
```
target 'DogExample' do
  use_frameworks!
  pod 'Realm', '4.4.1'
end
```
ViewController.m:
```swift
final class Dog: RLMObject {
    @objc dynamic var name: String = ""
    @objc dynamic var age: Int = 0
    override static func primaryKey() -> String { return "name" }
    convenience init(name: String) {
        self.init()
        self.name = name
    }
}

class DogViewController: UIViewController {
    var token: RLMNotificationToken?
    viewDidLoad() {
        // Monitor dog changes
        let results = Dog.allObjects()
        token = results.addNotificationBlock { (dogs, changes, error) in
            if let idxs = changes?.modifications {
                for idx in idxs {
                    print(dogs?[UInt(idx)]) // Print modified dogs
                }
            }
        }

        // First change: add dogs
        let realm = RLMRealm.default()
        try? realm.transaction {
            realm.add(Dog(name: "A"))
            realm.add(Dog(name: "B"))
        }

        // Second change: modify the second dog and remove the first dog
        try? realm.transaction {
            if let dog = Dog.object(in: realm, forPrimaryKey: "B") {
                dog.age = 1
            }
            if let dog = Dog.object(in: realm, forPrimaryKey: "A") {
                realm.delete(dog)
            }
        }
    }
}
```

Crash happens:
```
Terminating app due to uncaught exception 'RLMException', reason: 'Index 1 is out of bounds (must be less than 1).'
```

Because the change that the token receives is:
```
insertions: []
deletions: [0] // Dog A is removed
modifications: [1] // Dog B is modified
```
And the dogs that the token receives are:
```
[Dog B]
```

Since Dog A is removed, the referenced modified index becomes incorrect.
Expected results may be:
```
[Dog A(invalidated), Dog B]
```

## Version of Realm and Tooling

Realm framework version: 4.4.1

Xcode version: 11.3

iOS/OSX version: 10.14.6

Dependency manager + version: CocoaPods 1.8.4

**Comment by peteranny** [comment]
Similar discussions: https://github.com/realm/realm-cocoa/issues/4993

**Comment by leemaguire** [comment]
Hi @peteranny 

"The deleted objects are not included in results" - This is correct as `results` is to only include the new collection.

What you are trying to do will not work as you cannot use `changes.modifications` to iterate through `results` as they are mutually exclusive. `changes` will only include the deleted object in the regard.

Thanks,
Lee

**Comment by peteranny** [comment]
Got it. Just curious -- what can we do with `changes.modifications`? I mean, If it is exclusive to `results` then what is the possible usage of the index list? Because I can barely think of a proper usage of it but think it as almost useless.
