### ISSUE TITLE
Lexical or Preprocessor issue: 'realm/keys.hpp' file not found

### ISSUE THREAD

**Issue by AkshayNG** [realm/realm-cocoa#6480]
**Question**: I recently switched to Xcode 11.4 and using Swift 5. I run pod install, Realm and  RealmSwift installed with the latest version till date. Now when I run the project, its showing me an error: **....Pods/Realm/include/binding_context.hpp:24:10: 'realm/keys.hpp' file not found**
Why?

## Goals
To get rid of the error above.

## Expected Results
Successful build.

## Actual Results
![Screenshot 2020-04-21 at 8 27 50 PM](https://user-images.githubusercontent.com/15035623/79881282-a15f3000-840e-11ea-9909-3a10ab13101e.png)

## Steps to Reproduce
podfile:
```
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
```

Realm framework version: 4.4.1

Xcode version: 11.4

iOS/OSX version: 12.4

Dependency manager + version: cocoapod v1.9.1

**Comment by leemaguire** [comment]
Hi @AkshayNG Can you confirm if you are still experiencing this issue with the latest version of Realm and Cocoapods? Could you also make sure you do a `pod repo update`

Thanks,
Lee

**Comment by AkshayNG** [comment]
@leemaguire `pod repo update` didn't help me fix the issue. I had to:

1. remove `pod 'RealmSwift'` from my podfile, 
2. run `pod install`,
3.  re-add `pod 'RealmSwift'` in my podfile, and 
4. run `pod install` again to get latest version and resolve the issue.
