### ISSUE TITLE
Use of undeclared types SyncUser and SyncCredential

### ISSUE THREAD

**Issue by rs658726** [realm/realm-cocoa#6485]
## Goals
How do I install Realm and get Realm Sync and Mac Catalyst support?

## Expected Results
I installed Realm via SPM and tried the manual install as well, and while I'm able to port my app to Catalyst, I get the following error: Use of undeclared types SyncUser and SyncCredential

## Version of Realm and Tooling
Realm framework version: 4.4.1

Realm Object Server version: v3.28.2

Xcode version: 11.4

iOS/OSX version: 13.0/10.15.3

Dependency manager + version: SPM and manual install.

**Comment by leemaguire** [comment]
Hi @rs658726 

Realm Sync is a feature that is not yet available on SPM, this means that `SyncUser` and `SyncCredential` are not available. Using Cocoapods as your package manager would be the way around this.

**Comment by rs658726** [comment]
Hi Lee,
The problem with installing Realm via Cocoapods is that doesn't support Mac Catalyst. (#6460 ) What are my options in this case? And, do we have a timeline for when Realm Sync will be available on SPM? 
Thanks.

**Comment by leemaguire** [comment]
Hi @rs658726 

We are about 4 months out from getting Sync on SPM. In the meantime you can use either Carthage or Submodules to use Realm Sync with your Catalyst app.

Thanks,
Lee

**Comment by rs658726** [comment]
Hi @leemaguire 

Great. Do you have any tutorial on how to use submodules to use Realm Sync with Catalyst? 

Thank you.

**Comment by leemaguire** [comment]
@rs658726 Catalyst currently does not support Realm Sync. If we can help you with any other questions please open a new issue.
