### ISSUE TITLE
Realm termination handling issue

### ISSUE THREAD

**Issue by Mehdzor** [realm/realm-cocoa#6486]
When Realm is experiencing an unrecoverable issue it performs std::abort(). Basically, killing an application without a chance to catch an exception and recover. 

```c++
// LCOV_EXCL_START
extern "C" REALM_NORETURN REALM_NOINLINE void please_report_this_error_to_help_at_realm_dot_io()
{
    std::abort();
}
// LCOV_EXCL_STOP
```
The approach is deeply wrong because it is not up for third-party framework to decide whether to kill my app or not. Especially leaving developers no chance to gather up meaningful data to reproduce and debug the issue in the future. 

Ofc there is a way to handle signals and do something about it but it is significantly more complicated than handling an exception in place. 

**Suggestion:** replace std::abort() with a meaningful exception. After all why Realm can politely throw an exception but sometimes it just decides to kill everything with fire? 

Realm framework version: General issue

Xcode version: 11.4.1

iOS/OSX version: 13.3, 10.15.4

Dependency manager + version: Carthage 0.33

**Comment by tgoyne** [comment]
Anything which you can do which results in Realm calling abort() is by definition a bug in Realm as we only call it for internal assertion failures. Replacing the call to abort() with an exception throw would typically simply result in a crash in a different place within Realm with a less useful stack trace.

**Comment by leemaguire** [comment]
Closing this issue. If you experience anything else please open a new issue.

Thanks.
