### ISSUE TITLE
'RLMException', reason: 'Table has no columns

### ISSUE THREAD

**Issue by nipunV001** [realm/realm-cocoa#6490]
!!! MANDATORY TO FILL OUT !!!

## Goals
Want a solution for this. As I can check you have closed few tickets for the same issue but I'm still facing same issue.

I don't why its happing I have Implemented the all the thing but when I tried to add something in DB app crashed

## Expected Results
App should save the Data.

## Actual Results
App is crashing while saving the data.
Terminating app due to uncaught exception 'RLMException', reason: 'Table has no columns

## Steps to Reproduce
Try to save data using this line. 
realm.add(myVideo)

## Code Sample
import Foundation
import RealmSwift

class BaseVideo: Object {
  dynamic var title: String = ""
  dynamic var duration: Int = 0
  dynamic var playbackRate: Double = 1.0

  dynamic var looping: Bool = false

  dynamic var startDuration: Int = 0
  dynamic var startSet: Bool = false

  dynamic var endDuration: Int = 0
  dynamic var endSet: Bool = false

  dynamic var url: String = ""
  dynamic var createdAt: Date = Date()
}

======================================

let myVideo = currentSegment == .local ? LocalVideo() : WebVideo()

    myVideo.title = title
    myVideo.duration = source.duration
    myVideo.playbackRate = source.playbackRate

    myVideo.looping = source.loop.looping
    myVideo.startDuration = source.loop.start.duration
    myVideo.startSet = source.loop.startSet

    myVideo.endDuration = source.loop.end.duration
    myVideo.endSet = source.loop.endSet
    myVideo.url = url
    
    //swiftlint:disable:next force_try
    let realm = try! Realm()

    do {
      try realm.write {
        realm.add(myVideo)
      }

      delegate?.videoDidSave()
    } catch {
      displaySaveError()
    }

## Version of Realm and Tooling

Realm framework version: 4.4.1

Realm Object Server version: 3.16.0

Xcode version: 11.4.1

iOS/OSX version: 13.4.1/10.15.4

Dependency manager + version:

**Comment by tgoyne** [comment]
Your property declarations are missing `@objc`.

**Comment by bmunkholm** [comment]
Perhaps we could change the error msg to "No properties was defined. Did you remember to add '@obj' in your model?" or similar?

**Comment by nipunV001** [comment]
Hello @tgoyne thanks for quick reply.

Yes I tried to run my app with @objc but my app crashed with @objc too.
please check error message
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=10 "Migration is required due to the following errors:

**Comment by nipunV001** [comment]
Hello @tgoyne and @bmunkholm thanks for your help.

I found the solutions. I just need to uninstall the app and again install it. 
It works for me.

Thank you
