### ISSUE TITLE
librealmcore-ios.a(bptree.o), building for Mac Catalyst, but linking in object file built for iOS Simulator

### ISSUE THREAD

**Issue by jlaws** [realm/realm-cocoa#6493]
## Goals
Use Realm for iOS, iOS Extensions and Mac Catalyst

## Expected Results
Build and successfully run our iOS app using Mac Catalyst

## Actual Results
Build fails with this error:

```
Pods/Realm/core/librealmcore-ios.a(bptree.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, for architecture x86_64
```

## Steps to Reproduce
Setup an iOS app that uses cocoapods to share realm between an iOS app and iOS extensions then enable Mac Catalyst support

## Code Sample
```
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

def data_framework_pods
  pod 'RealmSwift'
  pod 'RxRelay'
  pod 'RxSwift'
  pod 'RxSwiftExt/Core'
  pod 'SwiftProtobuf'
end

target 'NotificationContent' do
  platform :ios, '13.0'
  data_framework_pods
end

target 'NotificationService' do
  platform :ios, '13.0'
  data_framework_pods
end

target 'MainApp' do
  platform :ios, '13.0'
  data_framework_pods
end
```

## Version of Realm and Tooling
Realm framework version: 4.4.1

Realm Object Server version: 4.4.1

Xcode version: 11.4.1

iOS/OSX version: 13.4.1 / 10.15.4

Dependency manager + version: Cocoapods v1.9.1

## Notes

Tried the cocoapods related ideas from comments in #6163 and #6297 but none of them work.

**Comment by jlaws** [comment]
I removed realm from the extensions so it is just in the main iOS app via cocoapods and the issue persists.

**Comment by jlaws** [comment]
We decided to stop using realm

**Comment by ericjjj** [comment]
same error , when i build mac app, 
```
/Pods/Realm/core/librealmcore-ios.a(utilities.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, for architecture x86_64
```
xcode 11.5
realm 5.0.1

**Comment by Pehon1** [comment]
Same issue. I understand Cocapods doesn't support Mac Catalyst?
