### ISSUE TITLE
Keychain returned unexpected status code: -25299

### ISSUE THREAD

**Issue by Krysbe** [realm/realm-cocoa#6494]
## Goals
Update project to test frozen objects with SwiftUI

## Actual Results
Crash on App launch. And receive this :

> Terminating app due to uncaught exception 'RLMException', reason: 'Keychain returned unexpected status code: -25299'

## Steps to Reproduce
I made a copy of my project and update Realm to 5.0.0 beta-3

I launch the app in the simulator

Realm framework version: 5.0.0 beta-3

Realm Object Server version: ?

Xcode version: 11.4.1

iOS/OSX version: bêta 10.15.5 (19F62f)

**Comment by Krysbe** [comment]
Same with beta 6

**Comment by ni79ls** [comment]
Anyone able to resolve this? I receive the same error with the official 5.0.0 release. Using Xcode 11.3.1.

**Comment by Krysbe** [comment]
Problem with SyncUser ? 

0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   Realm                               0x000000010b8ba087 _ZZ31+[RLMSyncManager sharedManager]ENK3$_0clEv + 231
	3   Realm                               0x000000010b8b9f5d _ZNSt3__1L8__invokeIZ31+[RLMSyncManager sharedManager]E3$_0JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOS2_DpOS3_ + 29
	4   Realm                               0x000000010b8b9f38 _ZNSt3__117__call_once_paramINS_5tupleIJOZ31+[RLMSyncManager sharedManager]E3$_0EEEE9__executeIJEEEvNS_15__tuple_indicesIJXspT_EEEE + 40
	5   Realm                               0x000000010b8b9f05 _ZNSt3__117__call_once_paramINS_5tupleIJOZ31+[RLMSyncManager sharedManager]E3$_0EEEEclEv + 21
	6   Realm                               0x000000010b8b9ddd _ZNSt3__117__call_once_proxyINS_5tupleIJOZ31+[RLMSyncManager sharedManager]E3$_0EEEEEvPv + 29
	7   libc++.1.dylib                      0x00007fff4f8fac8a _ZNSt3__111__call_onceERVmPvPFvS2_E + 139
	8   Realm                               0x000000010b8b2ccc _ZNSt3__1L9call_onceIZ31+[RLMSyncManager sharedManager]E3$_0JEEEvRNS_9once_flagEOT_DpOT0_ + 92
	9   Realm                               0x000000010b8b2c50 +[RLMSyncManager sharedManager] + 32
	10  Realm                               0x000000010b8eacbe +[RLMSyncUser currentUser] + 46
	11  RealmSwift                          0x000000010cdd8a0b $sSo11RLMSyncUserC10RealmSwiftE7currentABSgvgZ + 43

**Comment by jsflax** [comment]
@Krysbe do you have any sample code we could see?

**Comment by Krysbe** [comment]
The problem is that the app crash on lunch and Xcode don’t point any problem somewhere in my code. 

Everything works with realm 4.4.1

**Comment by Krysbe** [comment]
![image](https://user-images.githubusercontent.com/47786830/82150360-d49fae00-9858-11ea-994c-1b1e89f5838b.png)

`class SessionStore : ObservableObject {
    
    var didChange = PassthroughSubject<SessionStore, Never>()
    
    @Published var session:SyncUser? { didSet { self.didChange.send(self) }}
    
    
    init() {
        session = SyncUser.current
        listen()
    }
    
    func listen() {
        if let user = SyncUser.current {
//            print("we got a user \(String(describing: user.identity))")
            self.session = user
        }else{
            self.session = nil
        }
    }
    
    func logOut() {
        do {
            session?.logOut()
            try Auth.auth().signOut()
            listen()
            return
        } catch {
            return
        }
    }
}`

**Comment by MagicZP** [comment]
I have the same error with the official 5.0.0 release. I'm using Xcode 11.4.1. It's working on simulator, but doesn't work on real device with iOS 13.4.

**Comment by Krysbe** [comment]
Same on simulator and real device for me.

**Comment by Krysbe** [comment]
But on Xcode 11.5 beta only crash on real device.

**Comment by d4raffy** [comment]
Just updated. Have the same error on 5.0. Works ok now on Simulator not on the iPhone. Running at X11.4.1 & 13.4.1.  Have to delete all data and reset Simulator to get it going. Frustrating ...
<img width="1109" alt="Screenshot 2020-05-18 at 17 09 50" src="https://user-images.githubusercontent.com/45092507/82235266-64f9f380-992a-11ea-9b48-2c65555ab9ba.png">

**Comment by tgoyne** [comment]
The error code is `errSecDuplicateItem`, which indicates that we're trying to insert an item that's already present in the keychain. The relevant code is at https://github.com/realm/realm-object-store/blob/820b74e2378f111991877d43068a95d2b7a2e404/src/impl/apple/keychain_helper.cpp: `metadata_realm_encryption_key()` is called by SyncManager, which calls `get_key()` to look up the existing encryption key, and if that fails generates a new random key and calls `set_key()` to save it.

Getting `errSecDuplicateItem` means that `get_key()` failed to find the stored key even though it exists, and we use the exact same search dictionary for both getting and settings so it's not obvious why this would happen.

**Comment by tgoyne** [comment]
Actually, now that I look at it again, it is obvious why it would happen: we changed from using `kSecAttrAccessibleAlways` to `kSecAttrAccessibleAfterFirstUnlock` and that's being used for the lookup as well as the set, so it's going to fail to find the key for existing installs...

**Comment by tgoyne** [comment]
Actually, I don't think the above change can be blamed as it was introduced in 5.0 and so does not explain seeing the problem in 4.x.

**Comment by jsflax** [comment]
Any chance one of you can send a sandboxed version of your application that has the crash? Would be easier to debug that way.

**Comment by Krysbe** [comment]
Sure. How to ?

**Comment by jsflax** [comment]
Should be able to zip up your project dir and just attach it to a comment here.

**Comment by Krysbe** [comment]
No other way than publicly ?

**Comment by jsflax** [comment]
Do you have an email address I can contact you on? Otherwise, contact me through the email on my GitHub profile.

**Comment by sipersso** [comment]
I get the same error here. In my case the crash was when accessing SyncManager.shared. I was trying to set up sync logging before signing in (in my app delegate) using SyncManager.shared.logLevel = .all

See stacktrace: 

```
#0	0x00000001ae9855f0 in __exceptionPreprocess ()
#1	0x00000001ae6a7bcc in objc_exception_throw ()
#2	0x00000001049ef5a0 in +[RLMSyncManager sharedManager]::$_0::operator()() const at /Users/repcount/Code/app-iphone/Pods/Realm/Realm/RLMSyncManager.mm:136
#3	0x00000001049ef484 in decltype(std::__1::forward<+[RLMSyncManager sharedManager]::$_0>(fp)()) std::__1::__invoke<+[RLMSyncManager sharedManager]::$_0>(+[RLMSyncManager sharedManager]::$_0&&) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:4425
#4	0x00000001049ef45c in void std::__1::__call_once_param<std::__1::tuple<+[RLMSyncManager sharedManager]::$_0&&> >::__execute<>(std::__1::__tuple_indices<>) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:629
#5	0x00000001049ef42c in std::__1::__call_once_param<std::__1::tuple<+[RLMSyncManager sharedManager]::$_0&&> >::operator()() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:621
#6	0x00000001049ef2bc in void std::__1::__call_once_proxy<std::__1::tuple<+[RLMSyncManager sharedManager]::$_0&&> >(void*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:657
#7	0x00000001ae7fbf30 in std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*)) ()
#8	0x00000001049e8414 in void std::__1::call_once<+[RLMSyncManager sharedManager]::$_0>(std::__1::once_flag&, +[RLMSyncManager sharedManager]::$_0&&) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:675
#9	0x00000001049e8388 in +[RLMSyncManager sharedManager] at /Users/repcount/Code/app-iphone/Pods/Realm/Realm/RLMSyncManager.mm:129
#10	0x0000000105e002d8 in static RLMSyncManager.shared.getter at /Users/repcount/Code/app-iphone/Pods/RealmSwift/RealmSwift/Sync.swift:55

```

If I remove access to syncmanager, the app is running fine.

**Comment by cuzv** [comment]
Same on Xcode 11.5 (11E608c),  Realm (5.0.0), only crash on real device.

**Comment by sipersso** [comment]
Device or simulator doesn't make any difference whatsoever for me. All access to the SyncManager crashes with keychain error on both the simulator and real device.

Realm: Any updates on this issue?

**Comment by sipersso** [comment]
> e change can be blamed as it was introduced in 5.0 and so does not explain seeing the problem in 4.x.

But the problem wasn't there in 4.x right? Or was the change you are talking about introduced in 4.x and thus not the reason for the crashes that started in 5.0?

**Comment by d4raffy** [comment]
This is a show-stopper for me .. had to back out 5

**Comment by levelchanger** [comment]
This a crashing bug for which there is no workaround besides backtracking to 4.x. It was reported 24 days ago and still there is no resolution. This is not a good look for the company and does not instill confidence in developers.

**Comment by sipersso** [comment]
@levelchanger Looks like this one has been reported twice. Realm is working on it and it looks like they have a fix for it ready to be merged. https://github.com/realm/realm-cocoa/issues/6538
