### ISSUE TITLE
Value of type 'Results<Object>' has no member 'dictionaryWithValues'

### ISSUE THREAD

**Issue by waleednour** [realm/realm-cocoa#6503]
After update the realm sdk to last version i received this error:
Value of type 'Results<Object>' has no member 'dictionaryWithValues'

In this function:
realm.objects(TableName).dictionaryWithValues(by: SelectData)

**Comment by leemaguire** [comment]
Hi @waleednour,

`dictionaryWithValues ` is a method of `NSObject` or `NSKeyValueCoding ` to be specific,` Results<>` are a Swift struct so they do not support this. Only `RLMResults` supports this method.

Thanks,
Lee
