### ISSUE TITLE
Realm work fine on simulator, but crashes on real device

### ISSUE THREAD

**Issue by kupriknikita** [realm/realm-cocoa#6506]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: last

Realm Object Server version: ?

Xcode version: last

iOS/OSX version: last

Dependency manager + version: ?

**Comment by bmunkholm** [comment]
@kupriknikita You will need to give us some information to be able to help us. Please fill out the template and I'll reopen the issue.
