### ISSUE TITLE
Cannot open .realm file on exFAT and FAT32 drives

### ISSUE THREAD

**Issue by gangsports** [realm/realm-cocoa#6508]
## Goals
Open a saved `.realm` file on an exFAT drive in Realm Studio

## Expected Results
The file is opened as expected

## Actual Results
Realm Studio reports an error 
```
fcntl() inside prealloc() failed allocating 1184 bytes, new_size=1184, cur_size=0, allocated_size=0, event: Operation not supported
```

#### 1. Create a sample CSV file has the following content and save as `sample.csv` on an APFS drive (In my case, it was my Macintosh HD on my MBP)
```
T1,T2,T3
one,two,three
```
#### 5. Ream Studio reports the following error 
```
fcntl() inside prealloc() failed allocating 1184 bytes, new_size=1184, cur_size=0, allocated_size=0, event: Operation not supported
```

## Code Sample
Above replication does not require a sample code, but the same issue happens to our OS X application too when it tries to read a saved Realm file on exFAT or FAT32 drives.

## Version of Realm and Tooling
Realm framework version: 4.4.1

Realm Object Server version: ?

Xcode version: 11.3.1

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by tgoyne** [comment]
@ironage This sounds like File::prealloc() is failing to fall back to manual prealloc when the filesystem doesn't support it. I assigned you since I think you were the one to write that bit of code, but just let me know if you won't be able to get this.

**Comment by gangsports** [comment]
Thanks for checking this! 
When we say `filesystem doesn't support it`, did the `it` refer to `File::prealloc()` or `RealmCocoa`?

Appreciate your time.

**Comment by tgoyne** [comment]
Prealloc. We use a APFS feature to expand the Realm file when needed, and just aren't properly falling back to the non-APFS case.

**Comment by gangsports** [comment]
Thanks for your reply. So, is RealmCocoa supposed to support non-APFS? For example, exFAT?
This is quite important for us to understand the limitation of our current project.

Really looking forward to your reply, and thanks.

**Comment by tgoyne** [comment]
It is supposed to work and the fact that it doesn't in a bug which should be simple to fix.

**Comment by gangsports** [comment]
This is awesome! 
I will forward the information back to my team. Looking forward to the fix!

Thank you very much for the quick and helpful replies!
