### ISSUE TITLE
About maxNumberOfActiveVersions and clean versions manually

### ISSUE THREAD

**Issue by KimiChiu** [realm/realm-cocoa#6509]
According to the release notes, the new transaction will be failed when the versions are exceed this limitation.
But it may lead to another problem, which is no new transactions will be made anymore.
The problem which is causing the realm grows up, is the versions not released properly.
It may because of too many transactions or the thread problems.
So the versions are increasing the whole time.
It only prevent it to be crashed due to the size issue, not really fix the problem.
I'm just wondering, these versions should be no longer needed after the app is terminated.
Is there a way to clean these versions manually?
At least we can clean this up on app cold startup.
Does realm.writeCopy(toFile: compactedURL) do the trick?

**Comment by leemaguire** [comment]
Hi @KimiChiu,

The versions are cleaned up automatically but Realm keeps the space so it can be used for future writes. 

Please see our docs for how to use compaction: https://realm.io/docs/swift/latest/#compacting-realms

Compaction is the way to clean up this reserved space in the Realm file.

Thanks,
Lee

**Comment by KimiChiu** [comment]
But why are there so many issues reported about the realm size was increasing drastically? I always do compact realm when the app was launched. But I still have this problem.

**Comment by leemaguire** [comment]
There could be a few reasons for this:

- If you are using Sync a large transaction history will be held in the Realm file.
- Your app may be holding on to an old to an old version of a Realm, ensure your app logic does not allow for this.

Also please ensure you are always using the latest version of Realm.

Thanks,
Lee

**Comment by KimiChiu** [comment]
I'm not using sync.
And I always use the autorelease block to get Realm instance while doing transaction.
What implementation is the way to hold old version of a Realm?

**Comment by ianpward** [comment]
@KimiChiu if you do not set all realm variables to nil in the dispatch queue then intermediary versions will be pinned and the file size grow:
https://realm.io/docs/java/latest/#faq-large-realm-file-size

**Comment by KimiChiu** [comment]
Here's how I do the write operation.

    try autoreleasepool {
            let realm = try Realm()
            let now = NSDate()

            try realm.write {
                palette.json = json
                palette.lastUpdateDate = now
            }
        }

Do I still need to set it to nil?
I thought the `autoreleasepool` won't hold anything last long.
