### ISSUE TITLE
freeze - V5

### ISSUE THREAD

**Issue by marinofaggiana** [realm/realm-cocoa#6510]
Hi all,
I have create a test with the new freeze() but I have immediately find at start a crash in my procedure; now, where is the difference from the freeze() and the init(value object) :

```
example:
let realm = try! Realm()
realm.refresh()
        
guard let result = realm.objects(tableMetadata.self).filter(predicate).first else {
 return nil
}
     
difference from freeze and init() <--- memory a part   
1) return result.freeze()
2) return tableMetadata.init(value: result) 

```

**Comment by ericjordanmossman** [comment]
> start a crash in my procedure
Could you share more information on this, including the crash? 

Is the issue during the comparison or the init()?
