### ISSUE TITLE
Realm v5.0.0: reference binding to null pointer of type 'realm::Transaction'

### ISSUE THREAD

**Issue by aplusm** [realm/realm-cocoa#6512]
## Expected Results
No error logs at startup

## Actual Results
No crash occurs but the following errors are displayed in the Xcode console
```
[1m/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3931:17:[1m[31m runtime error: [1m[0m[1mreference binding to null pointer of type 'std::__1::shared_ptr<realm::Transaction>::element_type' (aka 'realm::Transaction')[1m[0m
[1m/iOS/Pods/Realm/Realm/ObjectStore/src/impl/realm_coordinator.cpp:910:52:[1m[31m runtime error: [1m[0m[1mreference binding to null pointer of type 'realm::Transaction'[1m[0m
[1m/iOS/Pods/Realm/Realm/ObjectStore/src/impl/realm_coordinator.cpp:795:12:[1m[31m runtime error: [1m[0m[1mreference binding to null pointer of type 'realm::Transaction'[1m[0m
```

## Steps to Reproduce

No steps required. This occurs at startup.

## Version of Realm and Tooling
Realm framework version:  v5.0.0

Xcode version:  Version 11.4.1 (11E503a)

iOS/OSX version: i0S 13.4.1

Dependency manager + version: Cocoapods 1.9.1

**Comment by bmunkholm** [comment]
@aplusm Can you please fill out the entire issue template? Especially about how to reproduce this.
Thanks!

**Comment by aplusm** [comment]
Sorry, the issue is not clear on my side. Will close this and reopen when things will be clearer.
