### ISSUE TITLE
`.publisher` unexpected behaviour

### ISSUE THREAD

**Issue by MortyMerr** [realm/realm-cocoa#6516]
Bug or misunderstanding from my side.   
I expect that `realm.objects(...).publisher` will emit all changes of collection, however, it receives nothing. `Swift.Sequence.publisher` is getting called, which is obviously empty. 
I looked through docs and example project but didn't find any mistakes in my code. What's wrong with it?

## Goals
A `.publisher` should receive all changes in the collection.

## Expected Results
Expected output:
```
Test {
 id = 1
}
```

## Actual Results
Empty output

## Steps to Reproduce
Run provided codesample

## Code Sample
```swift
var cancelBag = [AnyCancellable]() // class property
...
let realm = try! Realm()
try! realm.write {
    realm.deleteAll()
}
realm.objects(Test.self).publisher.sink { // Swift.Sequence.publisher called
    print($0)
}
.store(in: &cancelBag)
let test = Test(id: "1")
try! realm.write {
    realm.add(test, update: .all)
}
```
## Version of Realm and Tooling

Realm framework version: 5.0.0

Realm Object Server version: -

Xcode version: 11.4.1 (11E503a)

iOS/OSX version: 13.4

Dependency manager + version: Cocoapods 1.9.1

**Comment by jsflax** [comment]
I am able to reproduce this. A couple of observations:
Initialising the publisher after the first `Test` object has been adding works as expected.
Using the `changesetPublisher` always works, regardless of placement.
@tgoyne any ideas?

**Comment by MortyMerr** [comment]
> Initialising the publisher after the first Test object has been added works as expected.

Yes, because in this moment `.objects` collection is not empty, publisher simply emits array.

> Using the changesetPublisher always works, regardless of placement.

Because there is no conflicting name in swift library and realm publisher is getting called :)

**Comment by MortyMerr** [comment]
@tgoyne @jsflax  I investigated it a little bit more.
The reason, why we got this error, is `Publisher` extension for `Self.Failure == Never` which accept only one closure.
```swift
extension Publisher where Self.Failure == Never {
    public func sink(receiveValue: @escaping ((Self.Output) -> Void)) -> AnyCancellable
}
```
`Sequence.publisher.Failure` is `Never`. That's why `publisher` in following code is resolved as `Sequence.publisher`
```
realm.objects(Test.self).publisher.sink { // Swift.Sequence.publisher called
    print($0)
}
```

However, if we use the usual `sink` method (for Failure == Error) everything works as expected and proper Realm publisher is getting called:
```swift
realm.objects(Test.self)
  .publisher // RealmCollection.publisher is getting called
  .sink(
    receiveCompletion: { _ in},
    receiveValue: { print($0) }
  )
```

So, there is no bug, just a very confusing API. I am afraid that `Sequence.publisher` and `RealmCollection.publisher` will be confusing for all users, not only me.

**Comment by tgoyne** [comment]
Ah, that is pretty confusing and probably something we should do something about. Maybe it'd be best to use a name other than `.publisher`? We could override the `Never` failure version too, but maybe there's places people would actually want to use the `Sequence` version?

**Comment by MortyMerr** [comment]
IMO new name is better. `.collectionPublisher` os smth like that.

**Comment by MortyMerr** [comment]
@tgoyne any updates on this?

**Comment by marchy** [comment]
Hey guys, ran into the same/related issue here and the behaviour seems to be completing the subscription right away, despite a `.store(in: &cancellables)` being invoked.

This is what we're seeing:

**Comment by MortyMerr** [comment]
@marchy it's explained here: https://github.com/realm/realm-cocoa/issues/6516#issuecomment-631411045
Shortly, conflicting `publisher` name of Swift.Collection and Results (which is also Swift.Collection)

**Comment by marchy** [comment]
Thanks for taking on those changes in https://github.com/realm/realm-cocoa/pull/6622 @tgoyne.

Much better with the '.collectionPublisher' naming! --> no mistakenly missed updates now
