### ISSUE TITLE
Lexical Or Preprocessor Issue

### ISSUE THREAD

**Issue by jain926** [realm/realm-cocoa#6520]
## Goals
Build and run the app normally

## Expected Results
Building without any error since it was working perfectly before

After adding a new different pod file, this issue occurred.

<img width="1274" alt="Screenshot 2020-05-19 at 9 09 03 PM" src="https://user-images.githubusercontent.com/64659330/82347809-b7640e80-9a15-11ea-8c39-c93048f0e4ea.png">
## Actual Results
Error**#include "util/scheduler.hpp"** not found.

Realm framework version: 4.4.0

Xcode version: 11.4.1

**Comment by leemaguire** [comment]
Hi @jain926 

Have you tried clearing derived data and doing a clean rebuild? Maybe you could show us your pod file too?

Thanks,
Lee

**Comment by jain926** [comment]
Hey Lee,
Problem was solved when I upgraded the version of RealmSwift pod file to 5.0.0 .
Thanks
