### ISSUE TITLE
Single quote problem

### ISSUE THREAD

**Issue by dvera128** [realm/realm-cocoa#6521]
## Goals
Successfully search items that contains single quote 

## Expected Results
Success filtering results

## Actual Results
When the `name` variable (String) contains (') like `Pepe's`. I'm getting the following error:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unable to parse the format string "name = 'Pepe's'"'

## Steps to Reproduce
No clear reproduction steps unfortunately

## Code Sample
`let predicate = NSPredicate(format:"name ==[cd] %@ AND isSmart = false", name)`
`let lists = dataManager.dataSource.objects(ListEntity.self).filter(predicate)`

## Version of Realm and Tooling

Realm framework version: v4.3.2

Xcode version: 11.4.1

iOS/OSX version: 13.4.1 / 10.15.4

Dependency manager + version: Cocoapods 1.9.1

**Comment by tgoyne** [comment]
Are you sure that's the exact code hitting this? The error message given would make sense if there's a spot where you're doing `NSString(format: ...)` rather than `NSPredicate(format: ...)`, but with the given code there's no point where a string containing the substituted value is ever parsed.

**Comment by leemaguire** [comment]
Because it's been 3 weeks since this has been reported, we will close this out for now. If the issue persists please open a new ticket.
