### ISSUE TITLE
Realm 5.0.0 Release Build Error - Swift Package Manager

### ISSUE THREAD

**Issue by mandrusiaks** [realm/realm-cocoa#6522]
## Goals

Successfully build my iOS app with Realm 5.0.0 in Release mode.

## Expected Results

Expected the app to build successfully in Release mode after updating to Realm 5.0.0.

## Actual Results

When I build my app in Release mode, I receive a build error due to Realm. The error is as follows:
```
Aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer
```

<img width="209" alt="realm-errors" src="https://user-images.githubusercontent.com/9358677/82389793-4400d380-99fa-11ea-96e4-3080b64a3dc0.png">

## Steps to Reproduce

1. Install Realm 5.0.0 using Swift Package Manager
2. Edit scheme to run in Release mode
3. Build and run application
## Version of Realm and Tooling

Realm framework version: 5.0.0

Xcode version: 11.4.1

iOS version: Project setting iOS 12+

Dependency manager + version: Swift Package Manager

**Comment by tgoyne** [comment]
Are you trying to build your app for armv7? That error should be specific to 32-bit iOS, which is mutually exclusive with a deployment target of iOS 12.

Perhaps SPM is just trying to build for all arches and not just the ones used by the app and we need to update the package to explicitly not support armv7.

**Comment by mandrusiaks** [comment]
Not intentionally. I did notice armv7 was in my project's "Valid Architectures". I removed armv7 and armv7s from valid architectures, as well as set "Build Active Architectures Only" to true for Release config. However, I am still seeing the same issue.
