### ISSUE TITLE
Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'identity' does not exist on object 'RealmSwiftPermissionUser''

### ISSUE THREAD

**Issue by huangwz** [realm/realm-cocoa#6531]
!!! MANDATORY TO FILL OUT !!!

Questions: Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'identity' does not exist on object 'RealmSwiftPermissionUser''
## Code Sample

` var config = Realm.Configuration(
            schemaVersion: 3,
            migrationBlock: {[weak self] migration, oldSchemaVersion in
                self?.upRealmData()
        })
        var fileName = "0.realm"
        if self.realmFileName?.count ?? 0 > 0 {
            fileName = self.realmFileName ?? "0.realm"
        } else {
            printLog("error！！！")
        }`

when i run will print error！！！
## Version of Realm and Tooling

Realm framework version: 'RealmSwift', '~> 3.13.0'

Realm Object Server version: ?

Xcode version: Version 11.5 (11E608c)

iOS/OSX version: 10.15.4 (19E287)

Dependency manager + version: 'RealmSwift', '~> 3.13.0'

Swift version:4.2

Looking forward to your reply. Thank you very much!

**Comment by huangwz** [comment]
I had  update RealmSwift at least to v3.17.3. But problems remain

**Comment by huangwz** [comment]
also update to v5.0.0 , But problems remain  . please help

**Comment by leemaguire** [comment]
Hi @huangwz 

Please update to the latest version of Realm as it’s expected that this has been fixed in a recent release.

Thanks,
Lee
