### ISSUE TITLE
Usage of deprecated API UIWebView in iOS

### ISSUE THREAD

**Issue by cah-siddharth-paneri** [realm/realm-cocoa#6534]
### Apple has [deprecated UIWebView](https://developer.apple.com/documentation/uikit/uiwebview) starting iOS 13.0 and so Apple requires us to [update](https://developer.apple.com/news/?id=12232019b) the apps that use UIWebView to WKWebView, When I submit the application to App Store, we get an email saying

> ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

## Goals
Apple has [deprecated UIWebView](https://developer.apple.com/documentation/uikit/uiwebview) starting iOS 13.0 and so Apple requires us to [update](https://developer.apple.com/news/?id=12232019b) the apps that use UIWebView to WKWebView.

## Expected Results
I want to be able to submit the iOS app to Appstore without any issues pointing towards the AP deprecation

## Actual Results
When I submit the application to App Store, we get an email saying.
> ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

## Steps to Reproduce

1. Open latest Xcode (I am using Xcode 11.3.1)
2. Create a demo project
3. Add pods
4. Add `pod 'RealmSwift'` to the podfile
5. Run `pod install`
6. Build you project and create an archive
7. Open folder where Archive is stored.
8. Open Terminal app and run `cd` command to change the directory to the one where your archive is stored.
9. Run this command on your folder `grep -r "UIWebView" .`
10. You will see result like
```
Binary file ./Myapp.xcarchive/dSYMs/RealmSwift.framework.dSYM/Contents/Resources/DWARF/RealmSwift matches
Binary file ./Myapp.xcarchive/dSYMs/Realm.framework.dSYM/Contents/Resources/DWARF/Realm matches
```

## Code Sample
Should not be required, this is easily reproducible, using above steps

## Version of Realm and Tooling
Realm framework version:
```
Realm (5.0.0)
RealmSwift (5.0.0)
```

Realm Object Server version:  `NA`

Xcode version: `11.3.1`

iOS/OSX version: `13.0`

Dependency manager + version:  `Cocoapods 1.9.2`

**Comment by tgoyne** [comment]
Realm does not contain any references to UIWebView.
