### ISSUE TITLE
object forPrimaryKey publisher

### ISSUE THREAD

**Issue by Kdoherty11** [realm/realm-cocoa#6535]
## Goals
Subscribe to changes to a single objects attribute

## Actual Results
Only the initial value is published, not subsequent updates

## Code Sample
```swift
realm.object(ofType: Foo.self, forPrimaryKey: foo.id)!
  .publisher(for: \.name)
  .print()
  .assign(to: \.fooName, on: self)
  .store(in: &self.subscribers)

try! realm.write { foo.name = "Test" } // Not printed or stored in fooName
```

## Version of Realm and Tooling
Realm framework version: 5.0.0

Xcode version: 11.4.1

iOS/OSX version: 10.15.4

Dependency manager + version: Pod 1.8.4

**Comment by tgoyne** [comment]
If `foo` is a managed object, then `realm.object(ofType: Foo.self, forPrimaryKey: foo.id)` isn't doing anything useful; it's just looking up the object you already have and returning another reference to it. If `foo` isn't a managed object, then `try! realm.write { foo.name = "Test" }` isn't actually modifying anything in the Realm.

Assuming that's just an issue with the reduction to a small code sample, there's still another issue: `publisher(for:)` uses KVO to observe the property on the object. One of KVO's footguns is that it does not retain the object being observed, and this extends to `publisher(for:)`. As a result, the object returned by `realm.object(ofType:forPrimaryKey:)` is deallocated at the end of the statement (in Release builds; in Debug builds it'll be autoreleased and be deallocated an unspecified time later), which means that by the time the write occurs the object being observed no longer exists and the subscription has already been torn down.

To fix this you'll need to hold onto a reference to the object being observed.

**Comment by Kdoherty11** [comment]
@tgoyne Makes sense, thanks a lot for the explanation. Holding onto the object reference fixed it for me!
