### ISSUE TITLE
App crash with keychain error 25299 after upgrading to RealmSwift v5.0.0

### ISSUE THREAD

**Issue by adrianchirita** [realm/realm-cocoa#6538]
!!! MANDATORY TO FILL OUT !!!

## Goals

Upgrade Realm pod to v5.0.0 in our iOS app that used RealmSwift v4.4.0 pod and worked without issues.

## Expected Results

App to work seamlessly after upgrade without need to change it (backward compatibility).

## Actual Results

We get the following error at startup right after the upgrade from RealmSwift 4.4.0 to 5.0.0:

*** Terminating app due to uncaught exception 'RLMException', reason: 'Keychain returned unexpected status code: -25299'

<img width="406" alt="Screenshot 2020-05-27 at 18 53 12" src="https://user-images.githubusercontent.com/53476433/83043454-95890e00-a04b-11ea-88f7-4a2129d94f6a.png">

## Steps to Reproduce

1. ran pod update
2. cleaned derivedData xcode folder
3. cleaned project
4. deleted app from iPhone
5. ran the project from xcode (on the device)
6. when build finished and was launched on the device, the error occured.
**7. rolling back to pod Realm 4.4.0 and repeating steps 2-5, the app launches fine on the device.**

the app has entitlements, but does not have the keychain sharing entitlement added. when keychain sharing entitlement added, the error still occured.

## Version of Realm and Tooling

Realm framework version: 5.0.0

Realm Object Server version: v3.28.2

ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

/Applications/Xcode.app/Contents/Developer
Xcode 11.5
Build version 11E608c
iOS 13.3.1

Dependency manager + version: ?
/usr/local/bin/pod
1.9.2

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

carthage not found
(not in use here)

/usr/bin/git
git version 2.24.3 (Apple Git-128)

**Comment by sipersso** [comment]
I am seeing the same thing. The app crashes whenever trying to access the syncmanager. 

This issue was reported here: https://github.com/realm/realm-cocoa/issues/6494

The issue was created 24 days ago and it has been 10 days since the last comment by the realm team. Any updates?

**Comment by adrianchirita** [comment]
Any updates? #6494 is a beta issue and is not in the release notes, this is on GA.

**Comment by jsflax** [comment]
We are actively debugging this issue.

**Comment by ericjordanmossman** [comment]
@adrianchirita 
I've reproduced this consistently today. We think that @tgoyne 's first thought [here](https://github.com/realm/realm-cocoa/issues/6494#issuecomment-630298573) was correct.

I'll link the pull as soon as it's ready.
