### ISSUE TITLE
Getting Lipo error while archiving build

### ISSUE THREAD

**Issue by pavanbalu** [realm/realm-cocoa#6548]
Hi,

I am using Realm 5.0.1 with COCOAPODS. Everything is working fine when I debug my application with out any issues. But when I tried to archive my application getting following error

Build/Intermediates.noindex/ArchiveIntermediates/WhiteCoats\ QA/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Realm.framework/Realm
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't move temporary file: /DerivedData/MyProject-ahsjmvfmwijwylcysqqjxydwbhiv/Build/Intermediates.noindex/ArchiveIntermediates/MyProject/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Realm.framework/Realm to file: Path/Xcode/DerivedData/MyProject-ahsjmvfmwijwylcysqqjxydwbhiv/Build/Intermediates.noindex/ArchiveIntermediates/MyProject/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Realm.framework/Realm.lipo (No such file or directory)
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo emitted errors but did not return a nonzero exit code to indicate failure

**Comment by ericjordanmossman** [comment]
@pavanbalu 
Could you share more detail using the issue format?

Please include the Xcode version as well. Thanks!
