### ISSUE TITLE
Value of type 'Results<>' has no member 'addNotificationBlock'

### ISSUE THREAD

**Issue by PatilRupaliAress** [realm/realm-cocoa#6550]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by bmunkholm** [comment]
@PatilRupaliAress Please fill out the template.

**Comment by PatilRupaliAress** [comment]
Thanks for instant replay
