### ISSUE TITLE
Support non-relationship nested objects

### ISSUE THREAD

**Issue by UrosZivaljevic** [realm/realm-cocoa#6552]
## Goals

It would be great to have possibility to store nested objects as properties which aren't stored as relationships, something similar to CoreData `Transformable`. 

Let's say we parse JSON response with some computed properties for charts without `id`s or any primary keys, that looks like this:
```
{
    "id": 1,
     "chartName": "Hello World",
    "chartData": {
          "xAxisValue": 10,
         "yAxisValue": 12,
         "xAxisMax": 30,
         "yAxisMin": 0,
     }
}
```

Realm objects to reflect that would look something like this:
```
class Chart: Object {
    @objc dynamic var id: String = ""
    @objc dynamic var chartName: String = ""
    @objc dynamic var chartData: ChartData?

    override class func primaryKey() -> String? {
        "id"
    }
}

class ChartData: Object {
    @objc dynamic var xAxisValue: Double = 0.0
    @objc dynamic var yAxisValue: Double = 0.0
    @objc dynamic var xAxisMax: Double = 0.0
    @objc dynamic var yAxisMin: Double = 0.0
}
```

Since `ChartData` has no primary key, each time JSON above is parsed it will add the same ChartData to realm and cause "duplicates", while there will be only one `Chart` since it has primary key.

I guess one way to work around this is to have `Chart` object look like:
```
class Chart: Object {
    @objc dynamic var id: String = ""
    @objc dynamic var chartName: String = ""
    @objc dynamic var xAxisValue: Double = 0.0
    @objc dynamic var yAxisValue: Double = 0.0
    @objc dynamic var xAxisMax: Double = 0.0
    @objc dynamic var yAxisMin: Double = 0.0
}
```

and have computed property which returns instance of `ChartData` with necessary values passed in.

Though, this solution doesn't really work if for example `Chart` object had `chartData`, `chartDataStocks`, `chartDataActivity` etc.

## Expected Results

Have something like `RealmEmbedded<Object>` or something similar to mark nested object as non-relationship. Maybe behind the scenes it can use possibility of `Data` type property and use `NSKeyedArchiver` and `NSKeyedUnarchiver` to serialize data.

for example:
```
class Chart: Object {
    @objc dynamic var id: String = ""
    @objc dynamic var chartName: String = ""
    @objc dynamic var chartData: RealmEmbedded<ChartData>?
}
```

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by tgoyne** [comment]
Well, there's some good news. Embedded objects are a feature of the upcoming next major version of Realm, and have already been implemented on the `v10` branch. There'll be an official beta release in the next few days, but you can also try building against that branch now if you want to try it out.

The API is slightly different (`ChartData` will inherit from `EmbeddedObject` rather than it being something determined per-property) but semantically it should match what you're asking for.

**Comment by UrosZivaljevic** [comment]
Hah that's awesome! thanks @tgoyne
