### ISSUE TITLE
reason: 'RLMObject subclasses with the same name cannot be included twice in the same target

### ISSUE THREAD

**Issue by haokunjiang** [realm/realm-cocoa#6581]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by haokunjiang** [comment]
xcode 11.5
iOS11(任何系统都有问题)
cocoapods 1.9.3
realm 5.0.2

**Comment by ericjordanmossman** [comment]
@haokunjiang 
Based on the title, is [this related](https://stackoverflow.com/questions/33750402/rlmobject-subclasses-with-the-same-name-cannot-be-included-twice-in-the-same-tar)?
