### ISSUE TITLE
Problems with incorrect use

### ISSUE THREAD

**Issue by Jacket12** [realm/realm-cocoa#6584]
![image](https://user-images.githubusercontent.com/16936767/84972384-508b5f80-b151-11ea-9f5c-50e48bea88c3.png)

After the update, the original method cannot be used. What method should I use to replace it? Please give me some advice?

**Comment by bguidolim** [comment]
@Jacket12 it's in the error message: `.error`, `.modified` or `.all`

**Comment by Jacket12** [comment]
@bguidolim  I know that the wrong prompt here is to tell me that this method is not available. What I want to ask is, then this method is not available. In the new version, which method should I use to replace this unavailable method?

**Comment by bguidolim** [comment]
@Jacket12 I never used this method with a boolean before, so I don't know exactly what it does, but I would guess that you should use `.modified`, which means, if the object doesn't exist, it will be added, if it exists, it will update only the changed properties.
If you want to update the whole object, then you should use `.all`.
Or you can use `.error` and handle the conflicts manually.

**Comment by ianpward** [comment]
@bguidolim Correct

@Jacket12 See API docs - https://docs.mongodb.com/realm-sdks/swift/10.0.0-beta.2/Structs/Realm/UpdatePolicy.html#/s:10RealmSwift0A0V12UpdatePolicyO8modifiedyA2EmF
