### ISSUE TITLE
Can't open Realm file with realm studio- Please enter valid encryption key for realm file.

### ISSUE THREAD

**Issue by NourMustafa5** [realm/realm-cocoa#6585]
I download a realm file from my device to view on realm browser version3 and it asks me to enter valid encryption key for realm file.

Realm framework version: 5.0.3

Xcode version: [`11.2.1`](url
![Screen Shot 2020-06-18 at 4 10 32 PM](https://user-images.githubusercontent.com/67109798/85031462-fef9c980-b17e-11ea-9408-31c87f48b73f.png)
)

iOS version: 13.3.1 
macOS Catalina 10.15.5

**Comment by leemaguire** [comment]
Hi @NourMustafa5 do you have encryption enabled when using Realm? If so you will need to retrieve the encryption key from the device in order to open the Realm file.

Thanks,
Lee

**Comment by NourMustafa5** [comment]
Hi @leemaguire, No I am not using any encryption just CRUD operations, this happened when I installed the last updated version of Realm, I tried updating my Realm Browser also but I still get this window.

Thanks.

**Comment by leemaguire** [comment]
@NourMustafa5,

Would you be able to send us your Realm file so that we can have a look? My email is lee.maguire@mongodb.com

Thanks

**Comment by Fonceur** [comment]
Make sure you are using Realm Studio 3.11.0 (or newer) from their web site...

**Comment by edward-gray** [comment]
Download the new realm browser from https://www.mongodb.com/realm/mobile/database
also update your pods

**Comment by edward-gray** [comment]
> Download the new realm browser from https://www.mongodb.com/realm/mobile/database
> also update your pods
In the Bottom of the page

**Comment by leemaguire** [comment]
https://github.com/realm/realm-studio/releases/tag/v3.11.0 is the Realm Studio you should target with v5 and above.

**Comment by pavel-ship-it** [comment]
I'll close this issue due to inactivity. If the you still see the same issue please comment and we can re-open it.
