### ISSUE TITLE
The Realm file format must be allowed to be upgraded in order to proceed.

### ISSUE THREAD

**Issue by ADevelopStudio** [realm/realm-cocoa#6586]
After updating the Realm to 5+ 
getting this error: 

```
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=6 "The Realm file format must be allowed to be upgraded in order to proceed." UserInfo={Error Code=6, NSFilePath=/private/var/containers/Bundle/Application/0D8EB349-6652-43EC-ABE0-C29FD52A64B3/MY_APP.app/default.realm, Underlying=Realm file needs upgrade before opening in RO mode Path: /private/var/containers/Bundle/Application/0D8EB349-6652-43EC-ABE0-C29FD52A64B3/TakeMyFlight.app/default.realm

56  libdyld.dylib                       0x00000001ad5ad2dc E5E56A85-E4D6-332E-9F32-FED4B986AFE0 + 4828, NSLocalizedDescription=The Realm file format must be allowed to be upgraded in order to proceed.}:

```
**I'm using URL to my realm file
so my code is:**

```
    static let realm = try! Realm(configuration: Realm.Configuration(
        fileURL: Bundle.main.url(forResource: "default", withExtension: "realm"),
        readOnly: true))


```

**Comment by bmunkholm** [comment]
Sounds like you are including a realm as read-only in the app. You need to upgrade that read-only embedded realm file to the same version that you use in your app.

**Comment by ADevelopStudio** [comment]
how can I update the realm file? I did update the Realm Studio and opened the file, hopping that it'd help... no success @bmunkholm

**Comment by bmunkholm** [comment]
Are you using the correct version of Studio? Studio will ask to upgrade the file if it's an older version.

**Comment by tgoyne** [comment]
You'll need to download [Realm Studio 3.11.0](https://github.com/realm/realm-studio/releases/tag/v3.11.0) (the auto-update currently only updates to 3.10.), open the Realm file, then do File -> Save data -> Local Realm to write a new compacted copy of it. The last step is optional, but will reduce the size of the file shipped with your app.

**Comment by ADevelopStudio** [comment]
Catalina 10.15.5: 
![Uploading Screen Shot 2020-06-19 at 2.14.25 pm.png…]()

**Comment by ADevelopStudio** [comment]
Catalina 10.15.5:

<img width="532" alt="Screen Shot 2020-06-19 at 2 14 25 pm" src="https://user-images.githubusercontent.com/5238454/85096352-6d01c780-b237-11ea-875c-85487bf3c097.png">

**Comment by bmunkholm** [comment]
@ADevelopStudio That's very weird. Can you please create a realm-studio issue with details [here](https://github.com/realm/realm-studio/issues).

**Comment by joaopdcgarcia** [comment]
I'm already saving it with realm 3.11.0 but I'm getting the same error

`ERROR {"errorCode":6,"failureReason":"Content: Error loading up ReadOnlyContent.realm","domain":"io.realm","errorDescription":"The Realm file format must be allowed to be upgraded in order to proceed."}`
