### ISSUE TITLE
please enter a valid encryption key for this realm file

### ISSUE THREAD

**Issue by moxiaohui** [realm/realm-cocoa#6587]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by bmunkholm** [comment]
@moxiaohui There is not much we can help with without you giving more details by filling out the issue template. Feel free to reopen this issue when you can fill that out. Thanks!

**Comment by KylChiang** [comment]
Hi, I have same problem,
I was using RealmSwift v4.3.0, it's fine to open the file default.realm by Realm Browser,
after I upgrade the version of RealmSwift to v5.2.0, it always ask me to enter encryption key, but actually I haven't settings any key in the project.

Is it a default key that I should fill with in v5.2.0?

--
Realm framework version: v5.2.0

Realm Object Server version: ?

Xcode version: 11.5

iOS/OSX version: 13.3

Dependency manager + version: ?


--

![截圖 2020-07-06 下午4 40 29](https://user-images.githubusercontent.com/6602239/86575422-cdb83080-bfa9-11ea-92fb-d213454f8015.png)

**Comment by KylChiang** [comment]
@bmunkholm Hi, help please and re-open the issue.

**Comment by leemaguire** [comment]
@KylChiang you need to use this version to open a Realm created with v5.2.0 https://github.com/realm/realm-studio/releases/tag/v3.11.0

**Comment by KylChiang** [comment]
> @KylChiang you need to use this version to open a Realm created with v5.2.0 https://github.com/realm/realm-studio/releases/tag/v3.11.0

Thank you! It works 😄

**Comment by KryukovAndrey** [comment]
Hi 
i have the same problem http://joxi.ru/12MklwlhkJxoGr


Realm Studio Version 3.11.0
Realm Version 10.5.0
Xcode version: Version 12.2 (12B45b)

Realm Object Server version: how can I find it?
Dependency manager + version: how can I find it?

**Comment by vbst** [comment]
@KryukovAndrey try this https://studio-releases.realm.io/latest/download/mac-dmg

**Comment by AhmedMousa7** [comment]
> @KryukovAndrey try this https://studio-releases.realm.io/latest/download/mac-dmg

That works for me thanks.

**Comment by Tate-zwt** [comment]
> @KryukovAndrey try this https://studio-releases.realm.io/latest/download/mac-dmg

thanks

**Comment by william63960** [comment]
> @KryukovAndrey try this https://studio-releases.realm.io/latest/download/mac-dmg

That works for me Thanks 🙏

**Comment by ohohohoh** [comment]
thanks again as it worked for me on MBP 2018 and Big Sur 11.2.2 
helps solve the problem if you are following  Udemy: Swift with Angela chapter 261 "Intro to Realm" steps.

**Comment by mrmillmill** [comment]
The mac download of the latest version for Realm studio continuously stops downloading after 0.1 or 0.3 / 99.9 mb. Cannot figure out how to download.

**Comment by alsonick** [comment]
> @KryukovAndrey try this https://studio-releases.realm.io/latest/download/mac-dmg

tysm!
