### ISSUE TITLE
'util/event_loop_signal.hpp' file not found

### ISSUE THREAD

**Issue by tmck20** [realm/realm-cocoa#6590]
## Goals
Trying to build application with Realm

## Expected Results
App should run

## Actual Results
I get this error when building - 'util/event_loop_signal.hpp' file not found and it will not build

## Steps to Reproduce
I've installed Realm, tried reinstalling cocoapods and Realm and still get the error

## Code Sample
<img width="1148" alt="Screenshot 2020-06-22 at 13 23 53" src="https://user-images.githubusercontent.com/67266264/85287701-910a1680-b48c-11ea-9c7e-f141d51f7472.png">

## Version of Realm and Tooling
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

/Applications/Xcode.app/Contents/Developer
Xcode 11.5
Build version 11E608c

/usr/local/bin/pod
1.9.3
Realm (5.0.3)
RealmSwift (5.0.3)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

carthage not found
(not in use here)

/usr/bin/git
git version 2.24.3 (Apple Git-128)

**Comment by leemaguire** [comment]
Hi @tmck20 

Have you done a `pod repo update`, cleaned your build and derived data?

Thanks,
Lee

**Comment by tmck20** [comment]
Thanks for the reply - I have done the pod repo update, cleaned the build and derived data, but unfortunately I'm still getting the same message. 
Thanks
Tom

**Comment by tmck20** [comment]
Just another update - I've just tried updating pods again and there was a new version of Realm. Now that's been updated, it has worked! Thanks for your help again, I was running out of options.

**Comment by tmck20** [comment]
I've installed Realm on a new project and am having similar issues. I think there is some issue with other pods working too, but I've cleaned the build and derived data, done pod repo update and am just getting lots of errors. I'm really stuck and getting very frustrated because I want to get on with my app, so I'd really appreciate any suggestions please. Here's a screenshot of the errors
Thanks for your help
<img width="1072" alt="Screenshot 2020-07-09 at 15 03 02" src="https://user-images.githubusercontent.com/67266264/87049912-6f7f8d80-c1f5-11ea-9749-f6e267fa852f.png">

**Comment by leemaguire** [comment]
@tmck20 can you point to the latest version of Realm (5.2.0) in your pod file and try?

Thanks

**Comment by tmck20** [comment]
Thanks for your message. I've just tried that, but it still is generating the same errors.

**Comment by leemaguire** [comment]
Could you send us a sample app that replicates this issue? Thanks.

**Comment by tmck20** [comment]
Thanks for your quick replies. I'm going to create a new basic app trying to recreate the situation and I'll upload that if the problem reoccurs.

**Comment by pavel-ship-it** [comment]
I'll close this issue due to inactivity. If the you still see the same issue please comment and we can re-open it.
