### ISSUE TITLE
please_report_this_error_to_help_at_realm_dot_io

### ISSUE THREAD

**Issue by dataports** [realm/realm-cocoa#6592]
**Bugs**: To help you as fast as possible with an issue please describe your issue
and the steps you have taken to reproduce it in as many details as possible.

Several of our iOS users were experiencing a migration error that was crashing the app as of our most recent release. Though we haven't done a migration in a recent release, it seems like the one of the users that we got in contact wit may have been updating the app from several versions back where there _was_ a migration. In the release we have updated to Realm 5.0.1 from 4.4.1.

## Goals

More knowledge into what caused this crash so we can prevent it happening again.

## Expected Results

The migration to succeed and not crash the app.

## Actual Results

libsystem_kernel.dylib
__pthread_kill
libsystem_c.dylib
abort
Realm
please_report_this_error_to_help_at_realm_dot_io
Realm
realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)
Realm
realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&)
Realm
realm::Table::migrate_objects(realm::util::FunctionRef<void ()>)
Realm
realm::Transaction::upgrade_file_format(int)
Realm
realm::DB::upgrade_file_format(bool, int, int, int)
Realm
realm::DB::do_open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, realm::DBOptions)
Realm
realm::DB::open(realm::Replication&, realm::DBOptions)
Realm
realm::DB::create(realm::Replication&, realm::DBOptions)
Realm
realm::_impl::RealmCoordinator::open_db()
Realm
realm::_impl::RealmCoordinator::do_get_realm(realm::Realm::Config, std::__1::shared_ptr<realm::Realm>&, realm::util::Optional<realm::VersionID>, realm::util::CheckedUniqueLock&)
Realm
realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config, realm::util::Optional<realm::VersionID>)
Realm
realm::Realm::get_shared_realm(realm::Realm::Config) shared_realm.cpp:144
Realm
+[RLMRealm realmWithConfiguration:queue:error:]
RealmSwift
RealmSwift.Realm.init(queue: __C.OS_dispatch_queue?) throws -> RealmSwift.Realm <compiler-generated>:0
PelotonProdView
closure #1 (__C.NSHTTPURLResponse) -> PromiseKit.Promise<__C.NSHTTPURLResponse> in PelotonProdView.ProdViewAPI.request(baseURL: Foundation.URL?, endpoint: Swift.String, httpMethod: PelotonCommon.HTTPMethod, additionalPath: Swift.String?, requestBody: Foundation.Data?, queryItems: [Foundation.URLQueryItem], cachePolicy: __C.NSURLRequestCachePolicy?, headerOverrides: [Swift.String : Swift.String]) -> PromiseKit.Promise<__C.NSHTTPURLResponse> ProdViewAPI.swift:125
PelotonProdView
partial apply forwarder for reabstraction thunk helper from @escaping @callee_guaranteed (@guaranteed __C.NSHTTPURLResponse) -> (@owned PromiseKit.Promise<__C.NSHTTPURLResponse>, @error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed __C.NSHTTPURLResponse) -> (@owned PromiseKit.Promise<__C.NSHTTPURLResponse>, @error @owned Swift.Error) <compiler-generated>:0
PromiseKit
closure #1 () -> () in closure #1 (PromiseKit.Result<A.T>) -> () in (extension in PromiseKit):PromiseKit.Thenable.then<A where A1: PromiseKit.Thenable>(on: __C.OS_dispatch_queue?, flags: Dispatch.DispatchWorkItemFlags?, _: (A.T) throws -> A1) -> PromiseKit.Promise<A1.T> Thenable.swift:40
PromiseKit
reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> () <compiler-generated>:0
libdispatch.dylib
_dispatch_call_block_and_release
libdispatch.dylib
_dispatch_client_callout
libdispatch.dylib
_dispatch_main_queue_callback_4CF$VARIANT$mp
CoreFoundation
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
GraphicsServices
GSEventRunModal
UIKitCore
UIApplicationMain
PelotonProdView
main main.swift:16
libdyld.dylib
start

## Steps to Reproduce

Not sure.

## Code Sample

``` static func configurationWithMigration() -> Configuration {
        let config = Realm.Configuration(
 // Set the new schema version. This must be greater than the previously used
 // version (if you've never set a schema version before, the version is 0).
            schemaVersion: 12,
 
 // Set the block which will be called automatically when opening a Realm with
 // a schema version lower than the one set above
            migrationBlock: { _, oldSchemaVersion in
 // We haven’t migrated anything yet, so oldSchemaVersion == 0
                if oldSchemaVersion < 13 {
 // 0-> 1, simply added estimateMissingDays to MeasurementPoint so its automatic migration
 // 1-> 2, simply added MeasurementPoint.requireDailyEntry and removed RouteUnit.status its automatic migration
 // 2-> 3, added MeasurementPoint.entrySource and RouteUnit.subType, TableMetadata.recordDescriptor, TableMetadata.captionShortPlural for water go
 // 3-> 4, added EntiyName and TypDispHCLiq to TicketLocations, Added TypDispHCLiq to RouteUnit
 // 3-> 4, added UnitSet
 // 4-> 5, added defaultValue to FieldMetadata
 // 6-> 7, added hideDate to measurement points
 // 7-> 8, added ImageUpload
 // 8-> 9, added flowDirection to measurement method
 // 9-> 10, added excludeFromProduction to measurement point
 // 10-> 11, added UOMGasStat, uomGasDiff to measurement point
 // 11-> 12, added pumpDiameter to MeasurementPoint
 // 12-> 13, added dttmStart and dttmEnd to ticketLocations
 // Realm will automatically detect new properties and removed properties
 // And will update the schema on disk automatically
 }
 })
        return config
 }```

## Version of Realm and Tooling
<!---
[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining some of these versions.
-->
Realm framework version: ?
5.0.1
Realm Object Server version: ?
n/a
Xcode version: ?
11.4.1
iOS/OSX version: ?
13.4, 13.1.3, 13.3.1 (iOS versions)
Dependency manager + version: ?
1.9.1

**Comment by ericjordanmossman** [comment]
@dataports 
This crash appears to be the same as [this](https://github.com/realm/realm-cocoa/issues/6530#issuecomment-634287010).

If you're able to, could you provide a realm file this happened to or a reproduction project in #6530 ?

If you find #6530 is different and doesn't fit this report, feel free to comment and we can re-open #6592
