### ISSUE TITLE
When I put the data in and I went to query it it came out nil and it reported some errors（resolved，Thanks）

### ISSUE THREAD

**Issue by fridayyue** [realm/realm-cocoa#6598]
```
RLMResults` *result = [OrgCustomQuestionsEntity objectsWhere:@"question != %@",@"上传图片"];
    NSMutableArray *questions = @[].mutableCopy;
    for (OrgCustomQuestionsEntity *question in result) {
        [questions addObject:question];
    }
    return questions;
```
This is my query code, and "title" is my primary key and search key.But it comes up nil, so I can see through Realm Studio that I already have this data.
```
RecursionError: maximum recursion depth exceeded
The above exception was the direct cause of the following exception:
SystemError: <class 'rlm_lldb.RLMCollection_SyntheticChildrenProvider'> returned a result with an error set
Traceback (most recent call last):
  File "/Users/xxx/Library/Application Support/Realm/rlm_lldb.py", line 227, in RLMResults_SummaryProvider
    if not is_results_evaluated(obj):
  File "/Users/xxx/Library/Application Support/Realm/rlm_lldb.py", line 213, in is_results_evaluated
    mode_query_value = next(m for m in mode_type.enum_members if m.name == 'Query').GetValueAsUnsigned()
StopIteration
```
What should I do about it, thank you.

**Comment by leemaguire** [comment]
Hi @fridayyue,

What version of Realm are you using? Please ensure you have updated to all the latest versions of Realm and Studio.

Thanks,
Lee

**Comment by fridayyue** [comment]
> Hi @fridayyue,
> 
> What version of Realm are you using? Please ensure you have updated to all the latest versions of Realm and Studio.
> 
> Thanks,
> Lee

I used Realm version 5.1.0 and Realm Studio version 3.10.0.
https://tva1.sinaimg.cn/large/007S8ZIlly1gg2e46s86xj30ta0go0vd.jpg

**Comment by leemaguire** [comment]
Would you be able to provide us with a sandbox app showing how you are getting nil? Or could you show us the model for `OrgCustomQuestionsEntity`?

Thanks.

**Comment by fridayyue** [comment]
Of course,
.h
```
#import <Realm/Realm.h>

@interface OrgCustomQuestionsEntity : RLMObject
/// 问题
@property NSString *question;

/// 是否必填
@property BOOL must;

/// 是否上传图片
@property BOOL upload;
@end

// This protocol enables typed collections. i.e.:
// RLMArray<OrgCustomQuestionsEntity *><OrgCustomQuestionsEntity>
RLM_ARRAY_TYPE(OrgCustomQuestionsEntity)
```
.m
```
+ (NSString *)primaryKey {
    return @"question";
}
+ (NSArray *)indexedProperties {
    return @[@"question"];
}
```
"question"is the primary key and index entry.
The orgQuestionSentity storage method:
```
-(void)addQuestion:(NSString *)title must:(BOOL)must upload:(BOOL)upload{
    OrgCustomQuestionsEntity *question = [[OrgCustomQuestionsEntity alloc] init];
    question.question = title;
    question.must = must;
    question.upload = upload;
    [self.realm transactionWithBlock:^{
        [self.realm addOrUpdateObject:question];
    }];
}
```
self.realm to create：
```
-(RLMRealm *)creatUserRealm:(NSString *)userName{
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.fileURL = [[[config.fileURL URLByDeletingLastPathComponent]
                            URLByAppendingPathComponent:userName]
                            URLByAppendingPathExtension:@"realm"];
    NSError *error = nil;
    _realm = [RLMRealm realmWithConfiguration:config error:&error];
    return _realm;
}
```
Thanks~

**Comment by leemaguire** [comment]
Hi @fridayyue 

Because you're specifying a path for the Realm file you must also pass the Realm object when querying.

I was able to retrieve results using the following:

```
    RLMResults<OrgCustomQuestionsEntity *> *result = [OrgCustomQuestionsEntity objectsInRealm:self.realm
                                                                                        where:@"question != %@",@"上传图片"];
    NSMutableArray *questions = @[].mutableCopy;
    for (OrgCustomQuestionsEntity *question in result) {
        [questions addObject:question];
    }
    return questions;
```

**Comment by fridayyue** [comment]
WOW!That's true! Thank you very much!

**Comment by fridayyue** [comment]
> Hi @fridayyue
> 
> Because you're specifying a path for the Realm file you must also pass the Realm object when querying.
> 
> I was able to retrieve results using the following:
> 
> ```
>     RLMResults<OrgCustomQuestionsEntity *> *result = [OrgCustomQuestionsEntity objectsInRealm:self.realm
>                                                                                         where:@"question != %@",@"上传图片"];
>     NSMutableArray *questions = @[].mutableCopy;
>     for (OrgCustomQuestionsEntity *question in result) {
>         [questions addObject:question];
>     }
>     return questions;
> ```

WOW!That's true! Thank you very much!
