### ISSUE TITLE
Realm studio exception backtrace occurs when opening 'default.realm' file.

### ISSUE THREAD

**Issue by trevorphillips** [realm/realm-cocoa#6602]
## Goals
open the default.realm file for my 11 pro simulator with the realm studio app.

## Expected Results
to open normally.

## Actual Results
it crashes every time i open it.

## Steps to Reproduce
I get my path to the default.realm file using Xcode. I copy and paste that in terminal prepended with 'open' so as to open the file and it opens realm studio and the default.realm app but then it comes up with a grey screen and an exception backtrace.

## Code Sample
print(Realm.Configuration.defaultConfiguration.fileURL) to retrieve the path in xcode.

## Version of Realm and Tooling

Realm framework version: 5.1.0

Realm Studio: 3.10.0

ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

/Applications/Xcode.app/Contents/Developer
Xcode 11.5
Build version 11E608c

/usr/local/bin/pod
1.9.3
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

carthage not found
(not in use here)

/usr/bin/git
git version 2.24.3 (Apple Git-128)

Attached here are screenshots of the backtrace that occurs.

[Screenshot 1](https://user-images.githubusercontent.com/43789702/85502006-b76ea580-b5a3-11ea-88ef-4537a5f9262a.png)

[Screenshot 2](https://user-images.githubusercontent.com/43789702/85502011-bb9ac300-b5a3-11ea-818a-ae541cfa7bea.png)

**Comment by leemaguire** [comment]
Hi @trevorphillips 

You need to upgrade to Realm Studio 3.11.0, Realm files created with Cocoa version 5 and above are incompatible with version 3.10.0 of Studio.

Thanks,
Lee

**Comment by trevorphillips** [comment]
> Hi @trevorphillips 
> 
> 
> 
> You need to upgrade to Realm Studio 3.11.0, Realm files created with Cocoa version 5 and above are incompatible with version 3.10.0 of Studio.
> 
> 
> 
> Thanks,
> 
> Lee

@leemaguire , Well the thing is I keep that I keep checking for updates using the ‘checking for updates’ button and it says I’m on the latest. But I’ll just do a full reinstall. Thank you.

**Comment by leemaguire** [comment]
Hi Trevor,

Please grab the latest version of Studio from here https://github.com/realm/realm-studio/releases/tag/v3.11.0

Thanks,
Lee
