### ISSUE TITLE
List.append() causes memory leaks

### ISSUE THREAD

**Issue by haoyuant** [realm/realm-cocoa#6603]
I use RxSwift to subscribe to a data stream and write the data to the realm file repeatedly. I notice that the `append()` method of the `List` will not release the memory usage and thus the app crashes after running overnight. But if I stop streaming, which will immediately dispose of the Rx subscription, the memory will be released immediately. If I comment out the `append()`, the memory will not increase. Actually I am not sure if the bug is caused by Rx or Realm.

## Expected Results
Memory should not keep increasing when appending items to a `List<>`

## Actual Results

Memory keeps increasing, but after the disposal of the Rx subscription, the memory will be released

## Code Sample

When having the `append()`, the memory will keep increasing
![BC94D59B7B4D088C81D283D3D154C59E](https://user-images.githubusercontent.com/45114697/85660482-0548f200-b6f9-11ea-96c5-a6128980506e.jpg)
When commenting it out, the memory will not increase
![469E1A1E0FA3B3BD5775F14471C10078](https://user-images.githubusercontent.com/45114697/85660492-08dc7900-b6f9-11ea-9bcb-7f5397eee334.jpg)
Stop streaming
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/45114697/85661187-c5363f00-b6f9-11ea-9459-f4373e0ae874.png">

here is my schema
```
class LiveDataSession: Object {
    @objc dynamic var id = UUID().uuidString
    @objc dynamic var startTime = Date()
    @objc dynamic var endTime = Date()
    let acceleration = List<AccelerationData>()
    
    override class func primaryKey() -> String? {
        return "id"
    }
    
    override class func indexedProperties() -> [String] {
        return ["startTime", "endTime"]
    }
}

extension LiveDataSession: Identifiable {
    var identity: String {
        return self.isInvalidated ? "" : id
    }
}
```

## Version of Realm and Tooling

Realm framework version: 
- RealmSwift (4.4.1):
    - Realm (= 4.4.1)

RxSwift framework version:
  - RxCocoa (5.1.1):
    - RxRelay (~> 5)
    - RxSwift (~> 5)
- RxSwift (5.1.1)
  - RxSwiftExt (5.2.0):
    - RxSwiftExt/Core (= 5.2.0)
    - RxSwiftExt/RxCocoa (= 5.2.0)
  - RxSwiftExt/Core (5.2.0):
    - RxSwift (~> 5.0)
  - RxSwiftExt/RxCocoa (5.2.0):
    - RxCocoa (~> 5.0)

Xcode version: 11.5

iOS/OSX version: iOS 13.4.1 MacOS 10.15.5

**Comment by haoyuant** [comment]
Actually, the memory usage is fluctuating, e.g. 30M->50M->30.1M->52M->30M->53M, it feels like every time I try writing to the list, it will consume more memory than last time and eventually eat up all the memory.

**Comment by leemaguire** [comment]
Hi @haoyuant 

You should create the `Realm` inside the block as opposed to referencing `self.realm` I think that might be your issue.

Thanks,
Lee

**Comment by haoyuant** [comment]
`self.realm` actually calls a computed property to run a new `Realm` instance. Actually it is my fault that to set the buffer time range to 1000 microseconds, which should be 10000 milliseconds, and looks like this fix the memory creeping issue. But I run into a different issue. When I checked the app this morning, it already crashed, and XCode says `failed: Cannot allocate memory size xxxxxxxx (3+ GB)`
