### ISSUE TITLE
CodingKeys not working in mongodb realm sync

### ISSUE THREAD

**Issue by leocassioo** [realm/realm-cocoa#6605]
## Goals

Override Mongo properties for my model class in Swift. Because I use a different standard than the nomenclature that is in the cloud. Ex.: (in swift: partition, in cloud: _partition).

## Expected Results

I hope I don't have to write my classes in Swift with the same nomenclature used on the servers.
## Code Sample

```swift
class Project: Object, Codable {
    
    @objc dynamic var id = ObjectId.generate()
    @objc dynamic var partition = ""
    @objc dynamic var name = ""
    
    enum CodingKeys: String, CodingKey {
        case id = "_id"
        case partition = "_partition"
        case name
    }
    
    override static func primaryKey() -> String? {
        return "id"
    }
    
    convenience init(partition: String, name: String) {
        self.init()
        self.partition = partition
        self.name = name
    }
}
```

## Version of Realm and Tooling

Realm framework version: `pod 'RealmSwift', '=10.0.0-beta.2'`

Realm Object Server version: 4.4.0-rc9

Xcode version: 11.5 (11E608c)

iOS/OSX version: 13.5

**Comment by leemaguire** [comment]
Currently with the way our property accessors work you need to match the schema in the cloud. If you would like to use `partition` instead of `partition` then I would suggest to create `partition` as an ignored property and specify `get` `set` to `_partition`

```
class Project: Object {
    // MongoDB Realm Schema
    @objc dynamic var id = ObjectId.generate()
    @objc dynamic var _partition = ""
    @objc dynamic var name = ""

    // Swift specific
    var partition: String {
        get {
            _partition
        }
        set {
            _partition = newValue
        }
    }

    override class func ignoredProperties() -> [String] {
        ["partition"]
    }

    override static func primaryKey() -> String? {
        return "id"
    }

    convenience init(partition: String, name: String) {
        self.init()
        self.partition = partition
        self.name = name
    }
}
```
