### ISSUE TITLE
Apple Silicon/arm macOS support

### ISSUE THREAD

**Issue by joaocolaco** [realm/realm-cocoa#6619]
## Goals

Support for Apple Silicon/arm macOS so that realm can build and link with this platform.

This is especially important for me, as I have a macOS app that uses realm and would be useful to test it in advance.

For now the linker gives this error, and all the symbols are not available:
```
Ignoring file core/librealm-macosx-dbg.a, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
```

## Expected Results

Realm is made available for arm64 on macOS.

## Version of Realm and Tooling

Realm framework version: 5.2.0

Xcode version: 12.0 beta (12A8158a)

**Comment by tgoyne** [comment]
We've signed up for a dev kit, so hopefully that arrives soon. Even if it doesn't we should be able to start providing untested arm builds fairly quickly after xcode 12 beta 2 comes out. If you aren't using sync, installing Realm via Swift Package Manager might just work already.

**Comment by joaocolaco** [comment]
> If you aren't using sync, installing Realm via Swift Package Manager might just work already.

I'm using Git submodules, so easy to be fairly current, but still doesn't work.

**Comment by duncangroenewald** [comment]
I am interested in this as well as my DTK just arrived.  I am stuck on 4.4.1 because of unresolved realm-core errors when upgrading to 5.x so any suggestions on what modification are required to get a v4.4.1 build for arm64 would be appreciated.  The V4.4.1 builds fine under the Xcode 12 beta for macOS x64. The current build errors are above my pay grade unfortunately.

**Comment by duncangroenewald** [comment]
> We've signed up for a dev kit, so hopefully that arrives soon. Even if it doesn't we should be able to start providing untested arm builds fairly quickly after xcode 12 beta 2 comes out. If you aren't using sync, installing Realm via Swift Package Manager might just work already.

Can you explain how to do that - I don't need sync for testing the app.

**Comment by duncangroenewald** [comment]
I just did a rosetta build on 4.4.1 version and that seemed to build with no errors - so I'll start with getting that up and fully tested.

**Comment by joaocolaco** [comment]
For Rosetta it seems to build.
Also the Realm examples for iOS also build and run natively for ARM under Catalyst.

**Comment by duncangroenewald** [comment]
I just followed the instructions here to add Realm and Realm Swift packages using Xcode package manager and the app is up and running native.  Sadly the main app needs to have the sync dependencies removed before it will work so that will take a couple of hours.  Cool bananas!! - looking forward to seeing what the performance is like as we have some reports that take a good 15 minutes to generate.  

https://medium.com/better-programming/add-swift-package-dependency-to-an-ios-project-with-xcode-11-remote-local-public-private-3a7577fac6b2

**Comment by duncangroenewald** [comment]
I have just built the native arm64 version of out application but get the following error when trying to open a copy of the database - and I am assuming one should be able to open the same realm file on the arm64 platform as is used on the x86 platform.

"Error opening Realm: Migration is required due to the following errors:\n- Property \'AppPermission.!OI"

AppPermission is one of the Realm Objects - this schema version is the same as the version used to open the same file on x86.

**Comment by duncangroenewald** [comment]
OK I solved that by simply bumping the schema version number - although that strikes me as potential for other problems because the file will not be portable back to the original platform unless the version number if bumped again !?

Perhaps some clarity required over file version compatibility that can be expected across platforms.

**Comment by duncangroenewald** [comment]
Anyway the native app arm64 version is up and running.

**Comment by duncangroenewald** [comment]
Further feedback - we are seeing some performance issues with our application but the realm-core build time on the DTK is considerably faster than on the i7 2020 MacBook Air. One of the realm-core tests fails completely but the others are for the most part faster than the Air.  The last set of tests completes in 1:32 vs 1:59 - have not had a look at the realm-cocoa yet to see if that has tests.  Not sure what that missing file is all about as it doesn't show up in the x86 logs and the file doesn't appear to be present anywhere.

Also v6.x fails to compile with some errors.  If anyone is interested I can post them.

Realm version: 5.23.9 with Debug Disabled
Encryption: Enabled at compile-time (always encrypt = no)

REALM_MAX_BPNODE_SIZE = 1000
REALM_MEMDEBUG = Disabled

sizeof (size_t) * 8 = 64

Compiler supported SSE (auto detect):       No
This CPU supports SSE (auto detect):        None
Compiler supported AVX (auto detect):       No
This CPU supports AVX (AVX1) (auto detect): No

Unit test random seed:                      1234567

/Users/duncangroenewald/Development/realm-core/test/test_shared.cpp:3945: ERROR in Shared_DecryptExisting: Unhandled exception realm::util::File::NotFound: open("test_shared_decrypt_16k_page.realm") failed: No such file or directory Path: test_shared_decrypt_16k_page.realm
Exception backtrace:
0   realm-tests                         0x00000001010fcfc4 _ZN5realm4util4File13open_internalERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS1_10AccessModeENS1_10CreateModeEiPb + 848
1   realm-tests                         0x00000001010fef20 _ZN5realm4util4File4copyERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEESA_ + 64
2   realm-tests                         0x0000000100dd8714 _ZN38Realm_UnitTest__Shared_DecryptExisting8test_runEv + 396
3   realm-tests                         0x0000000100ddc758 _ZN5realm9test_util9unit_test12RegisterTestI38Realm_UnitTest__Shared_DecryptExistingE8run_testERNS1_11TestContextE + 24
4   realm-tests                         0x0000000100ef1714 _ZN5realm9test_util9unit_test8TestList17ThreadContextImpl3runENS2_17SharedContextImpl5EntryERNS_4util10UniqueLockE + 140
5   realm-tests                         0x0000000100ef15d0 _ZN5realm9test_util9unit_test8TestList17ThreadContextImpl13nonconcur_runEv + 112
6   realm-tests                         0x0000000100ef0a4c _ZN5realm9test_util9unit_test8TestList3runENS2_6ConfigE + 3432
7   realm-tests                         0x00000001004a56b8 _Z8test_alliPPcPN5realm4util6LoggerE + 5268
8   realm-tests                         0x0000000100eee974 main + 92
9   libdyld.dylib                       0x00000001e7682844 start + 4
FAILURE: 1 out of 1350 tests failed (0 out of 17560778 checks failed).
Test time: 3m36s

**Comment by duncangroenewald** [comment]
I just discovered the performance issue only surfaces in DEBUG mode - release builds or profiling it runs blazingly fast, like knock your socks off fast.  And horizontal scaling is awesome - we have some long jobs processing the data and realm database allows very easy horizontal scaling to process different segments concurrently.  

So now if someone could help me figure out how to fix the upgrade from 4.4.1 to 5.x I would love to test the newer version performance/stability.

**Comment by earltedly** [comment]
I'm seeing the same issues with:

`ignoring file .../Pods/Realm/core/librealmcore-macosx.a, building for macOS-arm64 but attempting to link with file built for unknown-x86_64`

Is there a way of resolving this whilst remaining on Cocoapods? I was wondering what swift package manager does differently which fixes the issue?

**Comment by tgoyne** [comment]
When using SPM the core library is built from source, while with cocoapods we use a prebuilt library which does not yet have a arm64 slice. We're actively working on adding that.

**Comment by owenzhao** [comment]
> When using SPM the core library is built from source, while with cocoapods we use a prebuilt library which does not yet have a arm64 slice. We're actively working on adding that.

One whole month passed and I still got this issue with Realm 5.3.5.

- building for macOS-arm64 but attempting to link with file built for macOS-x86_64

**Comment by duncangroenewald** [comment]
@tgoyne any indication yet when a binary with support for Apple Silicon might be available for beta testing? 

I assume there is still no way to build a full RealmSwift framework with the sync support from source code.

**Comment by owenzhao** [comment]
Now this is a real issue in Xcode 12.2. macOS-arm64 doesn't support.

**Comment by owenzhao** [comment]
This issue can be closed. @joaocolaco
