### ISSUE TITLE
SwiftUI Previews in Xcode 12 beta 1, 2, or 3 fail to display, undefined symbols while using SPM

### ISSUE THREAD

**Issue by mikeyusc** [realm/realm-cocoa#6625]
## Goals
Be Able to See a SwiftUI View Preview in Xcode 12 Beta 1 (12A6159) while using Realm

## Expected Results
SwiftUI Preview Displays

## Actual Results
Tons of missing symbol errors 

## Steps to Reproduce
Create Sample Xcode project in Xcode 12
Add RealmSwift via SwiftPM
Browse to ContentView in Project Browser

## Code Sample
See Attached Project File

## Version of Realm and Tooling

Realm framework version: 5.2.0

Realm Core 6.0.8

Xcode version: 12 Beta 1 (12A6159), Version 12.0 beta 2 (12A6163b), or Version 12.0 beta 3 (12A8169g)

iOS/OSX version: iOS 14

[UndefinedSymbolErrors.txt](https://github.com/realm/realm-cocoa/files/4867521/UndefinedSymbolErrors.txt)
[RealmTest.zip](https://github.com/realm/realm-cocoa/files/4867518/RealmTest.zip)

**Comment by lbrun25** [comment]
Same issue, the canvas does not compile, but installation on a physical device works.

After googling, I found that 'Require Only App-Extension-Safe API' needs to be YES from the build settings.

**Comment by mikeyusc** [comment]
> Same issue, the canvas does not compile, but installation on a physical device works.
> 
> After googling, I found that 'Require Only App-Extension-Safe API' needs to be YES from the build settings.

That's not an option for me... I have numerous API that I use that aren't Extension Safe.

**Comment by alexandremorgado** [comment]
Same issue here, as well. It can't compile SwiftUI canvas even setting 'Require Only App-Extension-Safe API' to YES.  

This problem happens only linking Realm via SPM. If I add Realm via Cocoapods, SwiftUI preview works properly.

**Comment by LiYanan2004** [comment]
I have the same issue with the SPM

**Comment by mikeyusc** [comment]
Update: this is still failing exactly the same way in Realm 5.3.1, Core 6.0.11

**Comment by mikeyusc** [comment]
So apparently the SwiftUI preview generator is now using x86_64, and like #6649 the preview build is failing for the same reason.

**Comment by LiYanan2004** [comment]
> So apparently the SwiftUI preview generator is now using x86_64, and like #6649 the preview build is failing for the same reason.

But I also want to build a macOS app. I really want to see Realm support x86_64

**Comment by mikeyusc** [comment]
Same on Xcode 12 Beta 3..

**Comment by LiYanan2004** [comment]
> Same on Xcode 12 Beta 3, works fine on Xcode 11.6

I guess this issue can only be solved by realm's team￼. Hopefully next release will fix this issue￼😄

**Comment by LiYanan2004** [comment]
How to install this branch? I cannot find it. Thank you all working on watchOS x86_64 simulator supporting.

**Comment by saltyskip** [comment]
I believe there is still currently no known workaround for this issue

**Comment by tgoyne** [comment]
https://github.com/realm/realm-core/pull/3833 should fix this. While waiting for a release, you can tell spm to use the `tg/template-instantiate` branch of realm-core by explicitly adding https://github.com/realm/realm-core as a package dependency in your Xcode project (but don't add it to any targets).

**Comment by mikeyusc** [comment]
This ALMOST fixes it.. You need to add the ConstLstIf set as well, then it will work.

**Comment by tgoyne** [comment]
Oh whoops, I merged the fix from a different branch that didn't have ConstLstIf any more.

**Comment by mikeyusc** [comment]
I sent up a pull request.

**Comment by mikeyusc** [comment]
This does fix it! Thanks!
