### ISSUE TITLE
Potential performance regression in Realm 5

### ISSUE THREAD

**Issue by allenhumphreys** [realm/realm-cocoa#6629]
## Goals

Over at https://github.com/insidegui/WWDC we are working on upgrading to Realm v5 to take advantage of DispatchQueue-bound realms. Unfortunately, we have encountered what seems to be a performance bug in Realm v5. I have compared the behavior of updating ~1600 realm objects before and after the upgrade.

Unfortunately, we use RxRealm in addition to Realm, which means we have 2 dependency updates happening at the same time. We're upgrading Realm specifically to work through some crashing, so the Realm 5 branch has changes including moving to queue-bound Realms in some areas.

As a result, our goal here is to determine whether the issue lies within Realm or how we're using it.

## Expected Results

We expected that the same operations with the same features would behave roughly the same before and after the upgrade.

## Actual Results

Realm v4 shows a roughly 2 second 100% thread usage after the updates are committed.

<img width="1765" alt="Screen Shot 2020-07-05 at 12 37 28 PM" src="https://user-images.githubusercontent.com/8225090/86538756-f23adc80-bec5-11ea-98d1-b109da07c0bb.png">

Realm v5 shows a roughly 40 second 100% thread usage after the updates are committed.
<img width="1765" alt="Screen Shot 2020-07-03 at 8 23 08 PM" src="https://user-images.githubusercontent.com/8225090/86538757-f404a000-bec5-11ea-9d6f-ad739d89f586.png">

## Steps to Reproduce

I have created 2 branches in our repository targeting different realm versions that will ensure the issue is always observed after app launch.

These branches can easily be built and run on the `WWDC` scheme with no additional changes.

1. checkout branch
2. execute `./bootstrap.sh` to setup appropriate versions
3. open `WWDC.xcodeproj`
4. Run the application, the transcripts take around 20-30 seconds to download and get committed

Realm v4: https://github.com/insidegui/WWDC/compare/master...ah/master-plus-always-index-transcripts
Realm v5: https://github.com/insidegui/WWDC/compare/master...ah/realm5-plus-always-index-transcripts

## Code Sample

Unfortunately the app is not as simple as a concise code block for reproduction, but the core code path that precedes the CPU usage is [here](https://github.com/insidegui/WWDC/blob/ah/realm5-plus-always-index-transcripts/ConfCore/TranscriptIndexer.swift#L125..L148)

```swift
fileprivate func store(_ transcripts: [Transcript]) {
    storage.backgroundUpdate { [weak self] backgroundRealm in
        guard let self = self else { return }
        os_log("Start transcript realm updates", log: self.log, type: .debug)

        transcripts.forEach { transcript in
            guard let session = backgroundRealm.object(ofType: Session.self, forPrimaryKey: transcript.identifier) else {
                os_log("Corresponding session not found for transcript with identifier %{public}@",
                       log: self.log,
                       type: .error,
                       transcript.identifier)

                return
            }

            session.transcriptIdentifier = transcript.identifier
            session.transcriptText = transcript.fullText

            backgroundRealm.add(transcript, update: .modified)
        }

        os_log("Finished transcript realm updates", log: self.log, type: .debug)
    }
}
```

## Version of Realm and Tooling

Realm framework version: 4.4.1 vs 5.2.0
Xcode version: Version 11.5 (11E608c)

iOS/OSX version: 10.15.5

Dependency manager + version: Carthage @0.34.0

**Comment by vinnyt** [comment]
seeing similar behavior as well.

**Comment by tgoyne** [comment]
It looks like it's spending 2/3 of its total runtime scanning the transaction log to check for schema changes in places where there isn't actually a schema change listener registered. Should be pretty simple to just not do that.

**Comment by tgoyne** [comment]
Turns out 2/3 was a dramatic underestimate. Before/after comparison with https://github.com/realm/realm-core/pull/3811:

<img width="1680" alt="Screen Shot 2020-07-08 at 12 43 13 PM" src="https://user-images.githubusercontent.com/408944/86963318-2e19b000-c119-11ea-9697-958a3144375e.png">
<img width="1680" alt="Screen Shot 2020-07-08 at 12 43 38 PM" src="https://user-images.githubusercontent.com/408944/86963330-340f9100-c119-11ea-901e-dd1940cd1615.png">

**Comment by allenhumphreys** [comment]
@tgoyne Thank you so much for the rapid turn around! As we're trying to cut a new release with Realm 5, could you help us plan our strategy by providing a rough ETA on a release with this fix?
