### ISSUE TITLE
Missing model data during migration

### ISSUE THREAD

**Issue by deRonbrown** [realm/realm-cocoa#6639]
## Goals
I want to rename a model, and given that there isn't first-class support for renaming, my current plan is to delete the old model, create a new model, and copying the data over.

## Expected Results
I'm deleting a model class and creating the new model class in a single schema migration. I expect the data from the old model class to be available within the migration block.

## Actual Results
When attempting to query for the old model's data in the migration block with
```
enumerateObjects(ofType typeName: String, _ block: MigrationObjectEnumerateBlock)
```
the `MigrationObjectEnumerateBlock` is never called as it appears the data for the old has already been removed.

## Steps to Reproduce
1. Create a model with a single `String` property.
2. Run the app and seed the database with a few records.
3. Delete this model class and create a new model class with identical properties.
4. Increase the schema version and within the migration block try to enumerate objects with the old model's class name.

## Code Sample
Attempting to rename `Foo` to `Bar`. [Master branch](https://github.com/deRonbrown/RealmRenaming/tree/master) includes initial model and database seeding. [Rename branch](https://github.com/deRonbrown/RealmRenaming/tree/rename) for attempted model renaming and data copying.

## Version of Realm and Tooling
Realm framework version: 5.2.0
Xcode version: 11.5 (11E608c)
iOS: 13

**Comment by leemaguire** [comment]
You need to keep the `Foo` object in your project while you are performing this migration.

**Comment by helimarrabago** [comment]
Hi. Were you able to solve this?

**Comment by deRonbrown** [comment]
We decided to "rename" in the models by namespacing them in Swift, but keeping the original model names in Objective-C. This allows us to reclaim the names we wanted in our codebase without Realm having to do any migrations.

### Before
```
class Example: Object {
    @objc dynamic var uuid: String = ""
    @objc dynamic var title: String = ""

    override static func primaryKey() -> String? {
        return "uuid"
    }
}
```

### After
```
class RealmObject {
    @objc(Example) class Example: Object {
        @objc dynamic var uuid: String = ""
        @objc dynamic var title: String = ""

        override static func primaryKey() -> String? {
            return "uuid"
        }
    }
}
```
