### ISSUE TITLE
user.identities property is not persisted between app restarts.

### ISSUE THREAD

**Issue by theolampert** [realm/realm-cocoa#6647]
## Goals
Be able to determine if a user is logged in anonymously or with an oauth provider. I used signin with apple for example and am not able to tell how a user has authenticated.

## Expected Results
when calling `app.currentUser()` the oauth provider used to authenticate the current session is persisted in `user.identities` array.

## Actual Results
Identities array is populated after initial call to `app.login` or `app.link` and can verify it contains the correct results, however on subsequent app restarts calling `app.currentUser()` the identities property is empty. I can't tell if this is the expected behaviour or not? it seems as if it's a bug.

## Steps to Reproduce
- Install the latest Realm beta 10.0.0.beta.2
- Login through oauth, verify the login was successful and the returned user object contains the correct string inside of the `identities` property
- Restart the app and call `app.currentUser()` and verify that the identities property is now empty

## Code Sample
N/A

## Version of Realm and Tooling

Realm framework version: 10.0.0.beta.2

Realm Object Server version: MongoDB Realm beta

Xcode version: 11.5

iOS/OSX version: 13.5

Dependency manager + version: cocoapods 1.9.1

**Comment by leemaguire** [comment]
This is a bug on our side, we will look into it.

Thanks,
Lee

**Comment by jlavyan** [comment]
I have exactly same issue. Are there any progress ?

**Comment by jeanbaptistebeau** [comment]
Is this fix released? I'm on 10.0.0 beta 3 but the bug seems to be still here.

**Comment by jeanbaptistebeau** [comment]
@leemaguire has this been pushed to realm-cocoa? I looked at the commit linked above, but I can't see if this has been added to Realm Swift. I'm still having this issue. 

Thanks a lot!
