### ISSUE TITLE
Realm reads slower when Realm is managed via SPM

### ISSUE THREAD

**Issue by crousselle2** [realm/realm-cocoa#6653]
## Goals

We have been using Realm as a DB for our Swift iOS Application for over a year now. 
Recently, our codebase went under a massive refactor to separate our monolithic core into more targeted Swift Packages (Model, Network, Database, etc.).

Realm was previously imported via CocoaPods but is now managed by SPM and became a dependency in our Database package.
Prior to this move, Realm was a direct dependency on our App Target.
We have seen a significant slowdown (90-100%) in Realm reads since moving Realm to SPM. 

We perform a large DB read on launch, and have seen slowdowns that can be linked to before / after moving to SPM. 

## Expected Results
_Realm Pod read Times_
60k objects in 0.6 seconds (average over 5+ runs)

## Actual Results
_Realm Package read Times_
60k objects in 1.2 seconds (average over 5+ runs)

## Steps to Reproduce
- Remove 'RealmSwift' pod dependency
- Add `.package(name: "Realm", url: "https://github.com/realm/realm-cocoa.git", from: "5.0.0")` as a dependency in a Swift 'Database' Package 
- Add 'Database' as a Linked Library on our App Target
- Use `import Database` whenever necessary, and call methods that trigger Realm read calls. 
- No other updates, Realm code is unchanged, models are unchanged and codepath is unchanged. 

## Version of Realm and Tooling
Realm framework version: 5.0.3 (tried 5.0.0 and 3.19.0) 
Realm Object Server version: 6.0.9
Xcode version: 11.5
iOS/OSX version: 13.5
Dependency manager + version: 5.0.0

**Comment by tgoyne** [comment]
Are you comparing Release builds with runtime sanitizers disabled? One of the big differences is that when using CocoaPods we already use a prebuilt release build of the realm-core library, while with spm the core library is built from source using the same build settings as the rest of your app. This means that debug builds will inherently be slower, and if you're using address sanitizer (or any of the other sanitizers) the core library will also be built with the sanitizer, which will slow down things more.

**Comment by prayash** [comment]
Thank you @tgoyne, this was the issue for us! Testing on a release build and the speed has improved drastically — it's faster than our original speed now which is really great news. 😄
