### ISSUE TITLE
Realm reads slower in swift for loop

### ISSUE THREAD

**Issue by Venkata-Maniteja** [realm/realm-cocoa#6660]
I have a db of 30k+ items. All my datamodels are of type structs. Realm fetch from db is so quick. But when I loop through them and read one of the property and print to console, it becomes too slow. 

I want to know if this is expected behaviour or not. If this is expected, how can I achieve the same in a better way so that it takes around 30secs instead of 300secs. 

## Goals
 Improve read speed of realm objects. I need a static copy of rlm objects, so that I can temporarily copy them into a separate array for complex filtering operations on structs.

## Expected Results
 Realm basic read on for loop should be fairly quick.

## Actual Results
 For loop read is too slow. Only able to read 100 rows per 1 second. So for 30k db, it takes around 300 seconds to go through all records. 

## Code Sample

```
   static func all() -> Results<Contact>? {
        if let realm = try? Realm() {
            return realm.objects(Contact.self)
        }
        return .none
    }

    if let contacts = Contact.all() {
          print("contact fetch start")
          for cnt in contacts {
                   print(cnt.firstName)
           }
           print("contact fetch end")
      }

```

Realm framework version:  5.3.1

Xcode version: 11.5

OSX version: 10.15.4 Catalina

**Comment by ericjordanmossman** [comment]
Based on the info provided, it sounds expected. The i/o speed to the console may be the contributing factor, especially if you find reading objects behavior normally without the console.

**Comment by ericjordanmossman** [comment]
I'll close #6660 for now. If you believe this still a bug, feel free comment and share more details.
