### ISSUE TITLE
Array does not keep the order of objects after saving to Realm

### ISSUE THREAD

**Issue by dangthaison91** [realm/realm-cocoa#6665]
## Goals
When saving an array to a Realm file, we want to keep the order of the original objects. Cause our API already orders JSON object and they are not supported to re-order on the mobile side.

It is work as expected with Realm version 4.4.1, but it is broken as version 5.x. We also tried with the latest version 5.3.1 but Realm still returns unorder arrays. Is it unexpected behavior?

## Expected Results

Realm 4.4.1
```ruby
Results<TickCounter> <0x7fd07bf0d5d0> (
	[0] TickCounter {
		id = 77489E08-8983-4174-804B-956725AA7DA7;
		ticks = 0;
	},
	[1] TickCounter {
		id = 41FA924E-F9AD-4499-90B6-75F91635AAB6;
		ticks = 1;
	},
	[2] TickCounter {
		id = 4F2D3232-CB16-48D4-9F5E-D9B5DDAF8A43;
		ticks = 2;
	},
	[3] TickCounter {
		id = 4AE89A33-BD74-47DB-A437-2330DEE09677;
		ticks = 3;
	},
	[4] TickCounter {
		id = 206CE85B-A8B6-4DD9-B471-B6313F97AAC8;
		ticks = 4;
	}
)
```

Open Realm file with Realm Studio:

<img width="1047" alt="Screen Shot 2020-07-22 at 00 11 54" src="https://user-images.githubusercontent.com/6436310/88086673-ee8ba300-cbb1-11ea-8692-692041ebffc3.png">

## Actual Results
Realm 5.3.1

```ruby
Results<TickCounter> <0x7fd44cc16300> (
	[0] TickCounter {
		id = BD47C265-C142-4F1A-BAB4-F028D6B0627E;
		ticks = 3;
	},
	[1] TickCounter {
		id = 9CEC50BE-9F75-4C41-B49F-EA3303B216B0;
		ticks = 1;
	},
	[2] TickCounter {
		id = C3BA0367-488D-4196-87D5-D37DA077B2C5;
		ticks = 0;
	},
	[3] TickCounter {
		id = A0A8BDFF-49A8-4636-B755-A34DD8BAF31F;
		ticks = 2;
	},
	[4] TickCounter {
		id = 6E215637-E63B-442C-AA30-A6B46C802414;
		ticks = 4;
	}
)
```

<img width="1044" alt="Screen Shot 2020-07-22 at 00 31 09" src="https://user-images.githubusercontent.com/6436310/88087266-d6685380-cbb2-11ea-9355-2fc91176e0e1.png">

## Steps for others to Reproduce
Example code

## Code Sample
```swift

final class TickCounter: Object {
    @objc dynamic var id = UUID().uuidString
    @objc dynamic var ticks: Int = 0
    override static func primaryKey() -> String? { return "id" }
}

let realm = try! Realm()
let items: [TickCounter] = (1..<10).map { index in
    let counter = TickCounter()
    counter.ticks = index
    return counter
}
try! realm.write {
    realm.add(items)
}

debugPrint(realm.objects(TickCounter.self))
```

## Version of Realm and Tooling
Realm framework version: 5.3.1

Realm Object Server version: ?

Xcode version: 11.5

iOS/OSX version: iOS 13

Dependency manager + version: Cocoapods

**Comment by tgoyne** [comment]
This is working as intended. Unsorted Results do not preserve insertion order and never have, although the circumstances where it differs have changed. Pre-5.0 deleting objects changed the order of the remaining object, while now the order never changes but insertions do not always happen at the end.

A List can be used to store object in a particular order.

**Comment by dangthaison91** [comment]
@tgoyne Thanks for the tips, we are using List as array items container in some features and it works great with Realm 5.0.

The following code will preserve objects order:

```swift
final class Ticks: Object {
    @objc dynamic var id = 1
    override static func primaryKey() -> String? { return "id" }
    var items = List<TickCounter>() /// help to preserve objects order
}

final class TickCounter: Object {
    @objc dynamic var id = UUID().uuidString
    @objc dynamic var ticks: Int = 0
    override static func primaryKey() -> String? { return "id" }
}
```

```swift
        let realm = try! Realm()
        let items: [TickCounter] = (1..<10).map { index in
            let counter = TickCounter()
            counter.ticks = index
            return counter
        }
        
        let tick = Ticks()
        tick.items.append(objectsIn: items)

        try! realm.write {
            realm.add(items)
            realm.add(tick)
        }

        debugPrint(realm.objects(Ticks.self).first)
```
