### ISSUE TITLE
Follow up to ticket #6644 and v5.3.2

### ISSUE THREAD

**Issue by WickedChicken42** [realm/realm-cocoa#6668]
RealmSwift v5.3.2 was released and contained the fix for ticket #6644.

With v5.3.2, an older database may still experience the crashing issue during the upgrade but it will recover and succeed if the upgrade is re-attempted (app restarted) usually on the 2nd or 3rd try.  Versions used were a database at v4.4.0 upgraded to v5.3.2.

With a database that had already been impacted by the bug in ticket #6644, that database is not recovering when the latest upgrade is attempted And continues to crash at startup.  The comments in the ticket seemed to indicate that previously affected databases would recover with the fix applied.  Versions used were a database impacted by v5.2.0 upgraded to v5.3.2.

I have these databases for testing if would like them.

## Goals
Older databases to upgrade without crashing.
Previously impacted databases to recover from issue #6644 with database update.

## Expected Results
Upgrade of previous versions, before v5, upgrade without crashing.

## Actual Results

With v5.3.2, an older database may still experience the crashing issue during the upgrade but it will recover and succeed if the upgrade is re-attempted (app restarted) usually on the 2nd or 3rd try.  Versions used were a database at v4.4.0 upgraded to v5.3.2.

With a database that had already been impacted by the bug in ticket 6644, that database is not recovering when the latest upgrade is attempted And continues to crash at startup.  The comments in the ticket seemed to indicate that previously affected databases would recover with the fix applied.  Versions used were a database impacted by v5.2.0 upgraded to v5.3.2.

I have these databases for testing if would like them.

## Steps for others to Reproduce
Launch app with Realm v5.3.2 on a DB from v4.4.0.
Launch app with Realm v5.3.2 on a DB previously impacted by v5.2.0
## Code Sample
Same as #6644.

## Version of Realm and Tooling
Using v5.3.2

Xcode version: v11.6

iOS/OSX version: 
v13.6

**Comment by WickedChicken42** [comment]
I had assumed the error was the same as in #6644 but upon further inspection it was not.  This is the error I receive when trying to launch a database with v5.3.2 that had been impacted by v5.2.0:

/Users/realm/workspace/realm_realm-core_release_6.0.12/src/realm/table.cpp:1197: [realm-core-6.0.12] Assertion failed: s == number_of_objects
0   Realm                               0x0000000101843c70 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   Realm                               0x0000000101843f14 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 328
2   Realm                               0x0000000101808934 _ZN5realm5Table15migrate_objectsENS_6ColKeyENS_4util11FunctionRefIFvvEEE + 16260
3   Realm                               0x00000001017763c0 _ZN5realm11Transaction19upgrade_file_formatEi + 1656
4   Realm                               0x00000001017800cc _ZN5realm2DB19upgrade_file_formatEbiii + 292
5   Realm                               0x000000010177dd78 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 3516
6   Realm                               0x00000001017806ec _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 244
7   Realm                               0x0000000101784ea8 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 392
8   Realm                               0x0000000101335910 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 972
9   Realm                               0x0000000101334b64 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 72
10  Realm                               0x00000001013349fc _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 268
11  Realm                               0x0000000101587568 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 152
12  Realm                               0x00000001014d1db4 +[RLMRealm realmWithConfiguration:queue:error:] + 1760
13  RealmSwift                          0x00000001028cf0fc $sSo8RLMRealmC13configuration5queueABSo0A13ConfigurationC_So012OS_dispatch_C0CSgtKcfCTO + 156
14  RealmSwift                          0x00000001029068b0 $s10RealmSwift0A0V5queueACSo012OS_dispatch_C0CSg_tKcfC + 140
15  sports-audio-dj                     0x0000000100a42414 $s15sports_audio_dj11AppDelegateC24handleRealmConfigChangesyyF + 560
16  sports-audio-dj                     0x0000000100a40e20 $s15sports_audio_dj11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0l6LaunchK3KeyaypGSgtF + 72
17  sports-audio-dj                     0x0000000100a40f90 $s15sports_audio_dj11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0l6LaunchK3KeyaypGSgtFTo + 232
18  UIKitCore                           0x0000000189d9cc14 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 10636308
19  UIKitCore                           0x0000000189d9e9a0 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 10643872
20  UIKitCore                           0x0000000189da423c F486088D-724E-3713-B9A5-7C9FE0A817D8 + 10666556
21  UIKitCore                           0x0000000189548a2c F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1903148
22  UIKitCore                           0x00000001899f91e8 _UIScenePerformActionsWithLifecycleActionMask + 100
23  UIKitCore                           0x0000000189549510 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1905936
24  UIKitCore                           0x0000000189548f64 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1904484
25  UIKitCore                           0x000000018954933c F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1905468
26  UIKitCore                           0x0000000189548bfc F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1903612
27  UIKitCore                           0x000000018954d098 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1921176
28  UIKitCore                           0x000000018991d2ac F486088D-724E-3713-B9A5-7C9FE0A817D8 + 5919404
29  UIKitCore                           0x0000000189a1262c _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 244
30  UIKitCore                           0x000000018954cdf4 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1920500
31  UIKitCore                           0x0000000189a12528 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 100
32  UIKitCore                           0x000000018954cc5c F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1920092
33  UIKitCore                           0x00000001893bce30 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 282160
34  UIKitCore                           0x00000001893bb9d0 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 276944
35  UIKitCore                           0x00000001893bcb68 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 281448
36  UIKitCore                           0x0000000189da2488 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 10658952
37  UIKitCore                           0x0000000189942598 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 6071704
38  FrontBoardServices                  0x000000018ae7961c 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 50716
39  FrontBoardServices                  0x000000018ae9e194 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 201108
40  FrontBoardServices                  0x000000018ae83bfc 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 93180
41  FrontBoardServices                  0x000000018ae9de50 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 200272
42  libdispatch.dylib                   0x0000000102a8f730 _dispatch_client_callout + 16
43  libdispatch.dylib                   0x0000000102a92bb0 _dispatch_block_invoke_direct + 232
44  FrontBoardServices                  0x000000018aec2850 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 350288
45  FrontBoardServices                  0x000000018aec251c 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 349468
46  FrontBoardServices                  0x000000018aec2a44 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 350788
47  CoreFoundation                      0x0000000185c70ad8 E2D6A76B-6879-31A3-8168-DF49F94E17CD + 690904
48  CoreFoundation                      0x0000000185c70a30 E2D6A76B-6879-31A3-8168-DF49F94E17CD + 690736
49  CoreFoundation                      0x0000000185c701b8 E2D6A76B-6879-31A3-8168-DF49F94E17CD + 688568
50  CoreFoundation                      0x0000000185c6b1e8 E2D6A76B-6879-31A3-8168-DF49F94E17CD + 668136
51  CoreFoundation                      0x0000000185c6aba8 CFRunLoopRunSpecific + 424
52  GraphicsServices                    0x000000018fdda344 GSEventRunModal + 160
53  UIKitCore                           0x0000000189da63e4 UIApplicationMain + 1932
54  sports-audio-dj                     0x0000000100a4368c main + 80
55  libdyld.dylib                       0x0000000185af28f0 0CB11832-70AD-3EC6-A191-AFB85E3BF348 + 6384!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.2020-07-22 13:06:19.816860-0600 sports-audio-dj[1360:302495] /Users/realm/workspace/realm_realm-core_release_6.0.12/src/realm/table.cpp:1197: [realm-core-6.0.12] Assertion failed: s == number_of_objects
0   Realm                               0x0000000101843c70 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   Realm                               0x0000000101843f14 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 328
2   Realm                               0x0000000101808934 _ZN5realm5Table15migrate_objectsENS_6ColKeyENS_4util11FunctionRefIFvvEEE + 16260
3   Realm                               0x00000001017763c0 _ZN5realm11Transaction19upgrade_file_formatEi + 1656
4   Realm                               0x00000001017800cc _ZN5realm2DB19upgrade_file_formatEbiii + 292
5   Realm                               0x000000010177dd78 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 3516
6   Realm                               0x00000001017806ec _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 244
7   Realm                               0x0000000101784ea8 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 392
8   Realm                               0x0000000101335910 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 972
9   Realm                               0x0000000101334b64 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 72
10  Realm                               0x00000001013349fc _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 268
11  Realm                               0x0000000101587568 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 152
12  Realm                               0x00000001014d1db4 +[RLMRealm realmWithConfiguration:queue:error:] + 1760
13  RealmSwift                          0x00000001028cf0fc $sSo8RLMRealmC13configuration5queueABSo0A13ConfigurationC_So012OS_dispatch_C0CSgtKcfCTO + 156
14  RealmSwift                          0x00000001029068b0 $s10RealmSwift0A0V5queueACSo012OS_dispatch_C0CSg_tKcfC + 140
15  sports-audio-dj                     0x0000000100a42414 $s15sports_audio_dj11AppDelegateC24handleRealmConfigChangesyyF + 560
16  sports-audio-dj                     0x0000000100a40e20 $s15sports_audio_dj11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0l6LaunchK3KeyaypGSgtF + 72
17  sports-audio-dj                     0x0000000100a40f90 $s15sports_audio_dj11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0l6LaunchK3KeyaypGSgtFTo + 232
18  UIKitCore                           0x0000000189d9cc14 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 10636308
19  UIKitCore                           0x0000000189d9e9a0 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 10643872
20  UIKitCore                           0x0000000189da423c F486088D-724E-3713-B9A5-7C9FE0A817D8 + 10666556
21  UIKitCore                           0x0000000189548a2c F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1903148
22  UIKitCore                           0x00000001899f91e8 _UIScenePerformActionsWithLifecycleActionMask + 100
23  UIKitCore                           0x0000000189549510 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1905936
24  UIKitCore                           0x0000000189548f64 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1904484
25  UIKitCore                           0x000000018954933c F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1905468
26  UIKitCore                           0x0000000189548bfc F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1903612
27  UIKitCore                           0x000000018954d098 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1921176
28  UIKitCore                           0x000000018991d2ac F486088D-724E-3713-B9A5-7C9FE0A817D8 + 5919404
29  UIKitCore                           0x0000000189a1262c _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 244
30  UIKitCore                           0x000000018954cdf4 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1920500
31  UIKitCore                           0x0000000189a12528 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 100
32  UIKitCore                           0x000000018954cc5c F486088D-724E-3713-B9A5-7C9FE0A817D8 + 1920092
33  UIKitCore                           0x00000001893bce30 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 282160
34  UIKitCore                           0x00000001893bb9d0 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 276944
35  UIKitCore                           0x00000001893bcb68 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 281448
36  UIKitCore                           0x0000000189da2488 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 10658952
37  UIKitCore                           0x0000000189942598 F486088D-724E-3713-B9A5-7C9FE0A817D8 + 6071704
38  FrontBoardServices                  0x000000018ae7961c 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 50716
39  FrontBoardServices                  0x000000018ae9e194 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 201108
40  FrontBoardServices                  0x000000018ae83bfc 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 93180
41  FrontBoardServices                  0x000000018ae9de50 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 200272
42  libdispatch.dylib                   0x0000000102a8f730 _dispatch_client_callout + 16
43  libdispatch.dylib                   0x0000000102a92bb0 _dispatch_block_invoke_direct + 232
44  FrontBoardServices                  0x000000018aec2850 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 350288
45  FrontBoardServices                  0x000000018aec251c 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 349468
46  FrontBoardServices                  0x000000018aec2a44 844B6EAF-CB58-368E-B8E3-127C411DDE27 + 350788
47  CoreFoundation                      0x0000000185c70ad8 E2D6A76B-6879-31A3-8168-DF49F94E17CD + 690904
48  CoreFoundation                      0x0000000185c70a30 E2D6A76B-6879-31A3-8168-DF49F94E17CD + 690736
49  CoreFoundation                      0x0000000185c701b8 E2D6A76B-6879-31A3-8168-DF49F94E17CD + 688568
50  CoreFoundation                      0x0000000185c6b1e8 E2D6A76B-6879-31A3-8168-DF49F94E17CD + 668136
51  CoreFoundation                      0x0000000185c6aba8 CFRunLoopRunSpecific + 424
52  GraphicsServices                    0x000000018fdda344 GSEventRunModal + 160
53  UIKitCore                           0x0000000189da63e4 UIApplicationMain + 1932
54  sports-audio-dj                     0x0000000100a4368c main + 80
55  libdyld.dylib                       0x0000000185af28f0 0CB11832-70AD-3EC6-A191-AFB85E3BF348 + 6384!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.

**Comment by dmirmanov** [comment]
Any news on this?

**Comment by leemaguire** [comment]
The core library will do its best to try resolve any issues when upgrading. As a last resort if the failure continues to happen the best thing to do is discard the broken Realm file and start fresh on a clean Realm file.
