### ISSUE TITLE
Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'

### ISSUE THREAD

**Issue by Elamuruga** [realm/realm-cocoa#6674]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by Elamuruga** [comment]
My code sample: Could you please help me?

Async.background {
            autoreleasepool {
                let realm = try! Realm()
                let sampleRepository = sampleRepository(realm)
                sampleRepository.persistMedias(medias: self.medias, clean: self.clean, isBookmarked: self.isBookmarked)

                let payload: [String: Any] = [
                    "VCSource": self.VCSource,
                    "pagination": self.pagination
                ]

                SwiftEventBus.post(.mediaRetrieved, sender: payload)
            }
        }

**Comment by ericjordanmossman** [comment]
@Elamuruga 
For regular help on using Realm across threads please check out existing material on the subject with stackoverflow and our documentation.

If you still believe this a bug (especially if the same code works in 4.4.1 and not later versions), could you please fill out the issue template and provide a sample reproduction project? Thanks!

**Comment by ericjordanmossman** [comment]
Closing because of lacking information.
