### ISSUE TITLE
Crash when indexing Results<Element> and repeatedly writing to Realm.

### ISSUE THREAD

**Issue by adamk77** [realm/realm-cocoa#6677]
Reproduction steps:

1. Call the `filter` method that returns `Results<Element>`
2. Index an element
3. Repeatedly write to Realm

Note: only happens on a physical device

The Realm database file continues to increase in size and eventually leads to a crash stating that mmap() failed or that Realm is already in a write transaction.

## Goals
Being able to write to the Realm database without it crashing. The sample code provided writes 1000 / sec to more easily illustrate the problem, but I've seen it happen when writing to it less frequently (e.g., once every 5 seconds).

## Expected Results
The database does not grow and does not crash on writes.

## Actual Results
Crashes with either:

`Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 44040192 offset: 603979776" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 44040192 offset: 603979776, Error`

` *** Terminating app due to uncaught exception 'RLMException', reason: 'The Realm is already in a write transaction'`

## Steps for others to Reproduce
Please see sample code.

## Code Sample
Attached is RealmTest.zip.  

```
class Video: Object {
    @objc dynamic var slug = ""
    @objc dynamic var secondsWatched: TimeCode?
    init(slug: String, secondsWatched: TimeCode) {
        super.init()
        self.slug = slug
        self.secondsWatched = secondsWatched
    }
    
    required init() {
        super.init()
    }
    
    public override static func primaryKey() -> String? {
        return "slug"
    }
}

class TimeCode: Object {
    @objc dynamic var slug = ""
    @objc dynamic var seconds = 0
    init(slug: String, seconds: Int) {
        self.seconds = seconds
        self.slug = slug
    }
    
    required init() {
        super.init()
    }
    
    public override static func primaryKey() -> String? {
        return "slug"
    }
}

class ViewController: UIViewController {
    var videos: [Video]?
    var videosCrash: Results<Video>?
    
    override func viewDidLoad() {
        super.viewDidLoad()

        let realm = try! Realm()

        print(Realm.Configuration.defaultConfiguration.fileURL!)
        try! realm.write {
            realm.add(Video(slug: "video_1", secondsWatched: TimeCode(slug: "video_1", seconds: 10)), update: .all)
            realm.add(Video(slug: "video_2", secondsWatched: TimeCode(slug: "video_2", seconds: 20)), update: .all)
            realm.add(Video(slug: "video_3", secondsWatched: TimeCode(slug: "video_3", seconds: 30)), update: .all)
        }
            
        // Crashes when calling .filter() that returns Results  and indexing result.        
        videosCrash = realm.objects(Video.self).filter("TRUEPREDICATE")

        // Will not crash without this line.
        print(videosCrash?[0])   
        
        // Does not crash
        /*
        videos = Array(realm.objects(Video.self).filter("TRUEPREDICATE"))
        print(videos?[0])
        */
        
        // Does not crash
        /*
        videos = try! realm.objects(Video.self).filter { video throws in true }
        print(videos?[0])
        */
                            
        var counter = 0
        Timer.scheduledTimer(withTimeInterval: 0.001, repeats: true) {_ in 
            do {
                try realm.write {
                    realm.add(TimeCode(slug: "video_10", seconds: counter), update: .all)
                    counter += 1
                    if counter % 100 == 0 {
                        print(counter, terminator: " ")
                    }
                }
            } catch {
                print(error.localizedDescription)
            }
        }
    }
}
```
[RealmTest.zip](https://github.com/realm/realm-cocoa/files/4997091/RealmTest.zip)

## Version of Realm and Tooling
Realm framework version: 5.3.1

Realm Object Server version: N/A

Xcode version: 11.6

iOS/OSX version: iOS 13.6

Dependency manager + version: COCOAPODS 1.9.1

**Comment by tgoyne** [comment]
Oh, this is a sort of embarrassingly obvious bug. I think I assumed that whatever was causing file size explosions in 5.x had to be something more complex than what it actually is.
