### ISSUE TITLE
Realm crashes on physical Series 1-3 Apple Watches

### ISSUE THREAD

**Issue by mphill** [realm/realm-cocoa#6682]
## Goals
Run Realm / RealmSwift on Apple Watch Series 1-3

**NOTE:**
Works great on Series 4+, also on Series 1-3 simulators it works fine as well.  Its only on physical apple watches series 1-3

**UPDATE:**
I can run this on a physical Series 3 device when hooked up to a debugger in release and debug! This appears to happens in release code distributed idea via app store connect.  Maybe a bitcode issue?

**UPDATE 2:**
Although the exception mentions Date, it doesn't matter what the type is, its just the first one in the object during reflection

## Expected Results
Query Realms without crashes

## Actual Results

App crashes immediately when accessing Realm:

Property Log.date is declared as Date, which is not a supported managed Object property type. If it is not supposed to be a managed property, either add it to `ignoredProperties()` or do not declare it as `@objc dynamic`. See https://realm.io/docs/swift/latest/api/Classes/Object.html for more information.

## Steps for others to Reproduce
Create a model:

```
class Log: Object {
    @objc dynamic var date = Date()
    @objc dynamic var detail = ""
}
```

## Code Sample

`let last = realm.objects(Log.self).sorted(byKeyPath: "date", ascending: false).first`

## Version of Realm and Tooling

Realm framework version: Realm 5.3.2 + RealmCore 6.0.12

Realm Object Server version: N/A Local only

Xcode version: 11.6

iOS/OSX version: 10.15.5 macOS / 6.2.8 watchOS

Dependency manager + version: Swift PM

**Comment by docterd** [comment]
Still got this issue? I suspect that i'm fighting a similar problem.

**Comment by leemaguire** [comment]
@mphill I'm looking into this now. If you or @docterd have any crash logs / stack traces that would be really helpful.

Thanks

**Comment by leemaguire** [comment]
I'm able to reproduce this with TestFlight, so I'll go from here and let you know my findings.

**Comment by leemaguire** [comment]
In the meantime as a workaround, I didn't get any crashes while using Cocoapods.

**Comment by mphill** [comment]
I was able to get the code to compile and run by turning off the remove dead code optimization in the project.  For some reason the app thinning for the older 32 bit cpu removes code that uses reflection which causes the run time issue.

**Comment by leemaguire** [comment]
@mphill good stuff! I think this issue can be closed now. For anyone else experiencing the same just make sure 'Dead Code Stripping' is set to NO in your Xcode project/target settings.
