### ISSUE TITLE
Cannot write to a database on exFAT drive

### ISSUE THREAD

**Issue by gangsports** [realm/realm-cocoa#6691]
## Goals
Modify a realm database on an exFAT drive 

## Expected Results
The target realm database is saved or throws an exception

## Actual Results
The program hangs due to `realm.write` never returning

## Steps for others to Reproduce
Create a new realm database on exFAT causing the application hanging.

Some background:
I reported an issue that Realm cannot read the database on exFAT in https://github.com/realm/realm-cocoa/issues/6508 and it was fixed in https://github.com/realm/realm-core/pull/3733. I am able to open a saved Realm database on exFAT now as the fix indicates. However, I cannot write or modify. 

By playing around a little with the source code, it seems `tr.commit_and_continue_as_read();` in `void RealmCoordinator::commit_write(Realm& realm)` and `realm->get_number_of_versions();` in `static void check_can_create_write_transaction(const Realm* realm)` never return. 

## Code Sample
```
override func createDatabase() throws {
        // realmFileURL is pointing to exFAT drive 
        let realm = try Realm(fileURL: realmFileURL)
        try realm.write {
            // insert any record or do nothing
        }
        print("Done") // This line is never called and the function never throws too.
}
```

## Version of Realm and Tooling
Realm framework version: 5.3.2

Realm Object Server version: ?

Xcode version: Version 11.3.1 (11C505)

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by gangsports** [comment]
Hi people. Just wondering if any updates for this? Much appreciate it.

**Comment by tgoyne** [comment]
Running the core unit tests on an exFAT volume hits this issue, and there's a few other tests that fail as well. The good news is that it looks like that assuming I can get it to work it should be easy to test each filesystem on CI...

**Comment by tgoyne** [comment]
[I made a PR to fix this](https://github.com/realm/realm-core/pull/3883) and the core test suite at least now passes on exFAT.

**Comment by gangsports** [comment]
Thanks so much for your update! Really appreciate it.
