### ISSUE TITLE
5.3.2 filter results gets duplicated double or triple times whenever some record changes

### ISSUE THREAD

**Issue by hyouuu** [realm/realm-cocoa#6694]
## Goals
`filter` works normally as in 4.x.x

## Expected Results
after filtering results, it should keep the result consistent and not get duplicated

## Actual Results
after filtering results, if any of the result record's properties got updated, then the results would contain the same records duplicated 1-n times

## Steps for others to Reproduce

let pred = NSPredicate(/*whatever predicates e.g. type == journal*/)
let results = rlm.objects(Note.self).sorted(byKeyPath: "date", ascending: false)
let searchResults = results?.filter(pred)

 e.g. if I have filtered searchResults A, B, C, then if I update B, searchResults will now contain A, B, C, A, B, C; if I update C, then it could become A, B, C, A, B, C, A, B, C. This only happens in 5.3.2 as when I rolled back to 4.x it behaves perfectly normal

## Version of Realm and Tooling
Realm framework version: ? 5.3.2

Realm Object Server version: N/A

Xcode version: 11.6

iOS/OSX version: iOS 13.6

Dependency manager + version: SPM with Xcode 11.6

**Comment by tgoyne** [comment]
A complete repro case would be very helpful for this, as I have been unable to reproduce it.

**Comment by hyouuu** [comment]
Thank for looking into this @tgoyne ! I'm sorry currently too busy to make a complete repro case. But I'd imagine this scenario should be easy to reproduce. The core logic involved is:

```
 public var searchPred: NSPredicate?
 private var results: Results<Note>?
 private var searchResults: Results<Note>?

func fetch() {
    let results = try Realm().objects(Note.self).sorted(byKeyPath: "date", ascending: false)
    self.results = results
}

func search(_ pred: NSPredicate?) {
    if results == nil { fetch("search without results") }

    guard searchPred != pred else { return }

    guard let pred = pred else {
        searchPred = nil
        searchResults = nil
        return
    }

    searchPred = pred
    searchResults = results?.filter(pred)
}
```

**Comment by hyouuu** [comment]
@tgoyne did some more research into this, and confirmed that whenever I call realm.write { realm.add() }, the existing searchResults will get duplicated, triplicated or restored to no duplication (kind of undefined outcome), and redo `searchResults = results?.filter(pred)` will make it result correctly. However, on 4.3.2 it was not necessary to re-filter. It feels like a bug in 5.x.x, and re-filter all the time would for sure impact the performance so please help double check on it. Thanks!

**Comment by hyouuu** [comment]
Further info - if I have `var searchResults: Results<Note>?`,  then do a `searchResults = rlm.objects(NoteR.self).sorted(byKeyPath: "date", ascending: false).filter(pred)`, then every time I access `searchResults.count` the results adds a copy of its initial value - e.g. if I have 12 search results, then in debugger type `po searchResults.count` would give me 12 initially, and subsequent `po searchResults.count` would give 24, 36, 48, 60 etc - it feels ridiculous and wonder if there's some behavior change that I should adopt to? 4.3.2 definitely didn't have this behavior. @tgoyne

**Comment by leemaguire** [comment]
@hyouuu Thanks for the further information, but I cannot reproduce the issue with the scenario you described. Could you please create a small sandbox app that reproduces the issue?

**Comment by tgoyne** [comment]
If your predicate involves a case-insensitive equality query on an indexed string property then https://github.com/realm/realm-core/pull/3962 might fix this.

**Comment by hyouuu** [comment]
Good to know it's all related - will test when a new Realm release is out

**Comment by hyouuu** [comment]
@tgoyne when can we get a new RealmSwift release? Got some other weird behaviors on filtered results which might be related and want to test the new version ASAP then get to users if fixed. Thanks!!

**Comment by hyouuu** [comment]
Confirmed that it's fixed with a forked repo with the updated core. Thanks! (and surprising to me that it seems nobody else uses case insensitive search?!)
