### ISSUE TITLE
Copying objects from Realm Sync to local Realm fails with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by vib8m** [realm/realm-cocoa#6698]
## Goals

Copy objects from a synced Realm to a local Realm file for backup

## Expected Results

Successfully copy objects from synced Realm to local Realm

## Actual Results

Using create(_:value:update:) fails with EXC_BAD_ACCESS

## Steps for others to Reproduce

Created a button to update the local Realm manually

## Code Sample

```
var localConfig = Realm.Configuration()
localConfig.fileURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0].appendingPathComponent("local.realm")
let localRealm = try! Realm(configuration: localConfig)
let syncedRealm = try! Realm(configuration: app.currentUser()!.configuration(partitionValue: Constants.REALM_PARTITION_VALUE))
let accounts = syncedRealm.objects(Account.self)
let transactions = syncedRealm.objects(Transaction.self)
let productTypes = syncedRealm.objects(ProductType.self)
localRealm.beginWrite()
accounts.forEach { account in
    localRealm.create(Account.self, value: account, update: .all)
}
transactions.forEach { transaction in
    localRealm.create(Transaction.self, value: transaction, update: .all)
}
productTypes.forEach { type in
    localRealm.create(ProductType.self, value: type, update: .all)
}
try! localRealm.commitWrite()
```

## Version of Realm and Tooling

Realm framework version: 10.0.0-beta.2

Xcode version: 11.5

iOS/OSX version: 13.5.1

**Comment by ericjordanmossman** [comment]
Keep in mind that the Realm database on the device is [already a local copy](https://docs.mongodb.com/realm/get-started/glossary/#term-realm-sync).
If you need to copy the entire for file management, see the `writeCopy` in [file management](https://realm.io/docs/swift/5.3.4/api/Structs/Realm.html#/s:10RealmSwift0A0V9writeCopy6toFile13encryptionKeyy10Foundation3URLV_AG4DataVSgtKF).

If neither of those resolve the issue and you still believe this is a bug, please comment with the full stack trace.

**Comment by ericjordanmossman** [comment]
Closing because of[ recommendation above](https://github.com/realm/realm-cocoa/issues/6698#issuecomment-676667790). If anyone sees a similar exception, please open a new issue with the full stack trace.
