### ISSUE TITLE
Xcode 12 Beta 4 - SPM - watchOS - ld: symbol(s) not found for architecture arm64_32

### ISSUE THREAD

**Issue by cnstoll** [realm/realm-cocoa#6706]
## Goals
Improve reliability of building with beta versions of Xcode

## Expected Results
Builds normally with beta versions of Xcode

## Actual Results
Build fails for watchOS extension when linking Realm and RealmSwift via Swift Package Manager

## Steps for others to Reproduce
Currently this is only happening for me in a debug build
I added Realm as a dependency via Swift Package Manager, pointing at master (the latest release version wasn't working via SPM for me either, but with different issues)

## Version of Realm and Tooling
Realm framework version: master - 263023adebb0b0f81f86e4f6307362f5c62ba2d3

Realm Object Server version: ?

Xcode version: Xcode 12 Beta 4

iOS/OSX version: iOS 13 minimum, watchOS 5 minimum

Dependency manager + version: Swift Package Manager

It looks like the issue only happens on debug builds, but I haven't found a way to get around it yet. Archiving for release does work, but debug builds are failing. I've tried changing build only active architecture to no for debug builds for both the iOS and watchOS target but that doesn't seem to help.

<img width="1368" alt="Screen Shot 2020-08-15 at 9 17 42 PM" src="https://user-images.githubusercontent.com/1586401/90341343-7c498b00-dfc4-11ea-9492-171054c98ad1.png">
<img width="587" alt="Screen Shot 2020-08-15 at 9 17 59 PM" src="https://user-images.githubusercontent.com/1586401/90341345-7eabe500-dfc4-11ea-9e74-190b789e5c24.png">
<img width="501" alt="Screen Shot 2020-08-15 at 9 17 20 PM" src="https://user-images.githubusercontent.com/1586401/90341351-84a1c600-dfc4-11ea-9425-93028703ce43.png">

**Comment by tgoyne** [comment]
Those errors indicate that Realm is being built with ubsan enabled, but the extension is not. This is probably an Xcode bug as AFAIK there isn't even any way to configure that for packages. Toggling "Undefined Behavior Sanitizer" on and off in the scheme settings might fix it.

**Comment by cnstoll** [comment]
Oh my god that totally fixed it. Thank you!
