### ISSUE TITLE
5.3.4 crash "Realm accessed from incorrect thread"

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#6712]
## Goals
Running reporting jobs on background threads.  This exception appears to occur randomly since v5.x.  This issue is reported elsewhere against v5.3.x and earlier but I am creating a new issue against v5.3.4.

## Expected Results
Do not expect to get this crash since call to Realm() and subsequent access of the realm is occurring on the same thread.

## Actual Results
2020-08-19 12:46:02.455571+1000 MakeSpace[2462:172263] *** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff32706b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6b54d5bf objc_exception_throw + 48
	2   Realm                               0x0000000102391915 -[RLMRealm verifyThread] + 70
	3   Realm                               0x000000010232dd12 RLMGetObjects + 80
	4   RealmSwift                          0x0000000102bee120 $s10RealmSwift0A0V7objectsyAA7ResultsVyxGxmAA6ObjectCRbzlF + 112
	5   MakeSpace                           0x00000001007b5051 $s9MakeSpace010BrandMicroB11DataExtractC20processReportSegment7segment5codes9operation10completionySi_s10ArraySliceVySSGAA17OSReportOperationCySSSg_yptctFyyXEfU_ + 1105
	6   MakeSpace                           0x00000001007b645f $s9MakeSpace010BrandMicroB11DataExtractC20processReportSegment7segment5codes9operation10completionySi_s10ArraySliceVySSGAA17OSReportOperationCySSSg_yptctFyyXEfU_TA + 47
	7   MakeSpace                           0x000000010007d77f $ss5Error_pIgzo_ytsAA_pIegrzo_TR + 15
	8   MakeSpace                           0x00000001007be224 $ss5Error_pIgzo_ytsAA_pIegrzo_TRTA + 20
	9   libswiftObjectiveC.dylib            0x00007fff6c3a9d8e $s10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 46
	10  MakeSpace                           0x00000001007b4b8b $s9MakeSpace010BrandMicroB11DataExtractC20processReportSegment7segment5codes9operation10completionySi_s10ArraySliceVySSGAA17OSReportOperationCySSSg_yptctF + 395
	11  MakeSpace                           0x00000001007bf28c $sTA + 44
	12  MakeSpace                           0x0000000100c95a4b $s9MakeSpace17OSReportOperationC13processReport33_8052702ECD28E6803A02135FC2E5BA3DLL7segment5codes10completionySi_s10ArraySliceVySSGySSSg_yptctFyycfU_ + 219
	13  MakeSpace                           0x0000000100c96387 $s9MakeSpace17OSReportOperationC13processReport33_8052702ECD28E6803A02135FC2E5BA3DLL7segment5codes10completionySi_s10ArraySliceVySSGySSSg_yptctFyycfU_TA + 55
	14  MakeSpace                           0x0000000100049e20 $sIeg_IeyB_TR + 48
	15  libdispatch.dylib                   0x0000000102d23844 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x0000000102d24826 _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000102d26e8d _dispatch_queue_override_invoke + 1038
	18  libdispatch.dylib                   0x0000000102d38391 _dispatch_root_queue_drain + 334
	19  libdispatch.dylib                   0x0000000102d38e03 _dispatch_worker_thread2 + 127
	20  libsystem_pthread.dylib             0x0000000102db231b _pthread_wqthread + 220
	21  libsystem_pthread.dylib             0x0000000102db149b start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

## Steps for others to Reproduce
Unable to reliably reproduce this yet.

## Code Sample
N/A

## Version of Realm and Tooling

Realm framework version: RealmSwift 5.3.4

Realm Object Server version: ?

Xcode version: 11.6

iOS/OSX version: macOS 10.15.6

Dependency manager + version: N/A

**Comment by duncangroenewald** [comment]
I just managed to get another crash, this time ever so slightly different.

2020-08-19 13:10:35.441117+1000 MakeSpace[2511:184305] *** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff32706b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6b54d5bf objc_exception_throw + 48
	2   Realm                               0x0000000102394c43 -[RLMRealm refresh] + 73
	3   RealmSwift                          0x0000000102beeac0 $s10RealmSwift0A0V7refreshSbyF + 16
	4   MakeSpace                           0x0000000100cffd94 $s9MakeSpace27MonthlyStoreReportOperationC06createE010completionyyyc_tFyycfU_ + 756
	5   MakeSpace                           0x0000000100049e20 $sIeg_IeyB_TR + 48
	6   libdispatch.dylib                   0x0000000102d23844 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x0000000102d24826 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x0000000102d26e8d _dispatch_queue_override_invoke + 1038
	9   libdispatch.dylib                   0x0000000102d38391 _dispatch_root_queue_drain + 334
	10  libdispatch.dylib                   0x0000000102d38e03 _dispatch_worker_thread2 + 127
	11  libsystem_pthread.dylib             0x0000000102db231b _pthread_wqthread + 220
	12  libsystem_pthread.dylib             0x0000000102db149b start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
2020-08-19 13:10:35.441052+1000 MakeSpace[2511:177028] [General] Realm accessed from incorrect thread.
2020-08-19 13:10:35.441970+1000 MakeSpace[2511:177028] [General] (
	0   CoreFoundation                      0x00007fff32706b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6b54d5bf objc_exception_throw + 48
	2   Realm                               0x0000000102394c43 -[RLMRealm refresh] + 73
	3   RealmSwift                          0x0000000102beeac0 $s10RealmSwift0A0V7refreshSbyF + 16
	4   MakeSpace                           0x0000000100cffd94 $s9MakeSpace27MonthlyStoreReportOperationC06createE010completionyyyc_tFyycfU_ + 756
	5   MakeSpace                           0x0000000100049e20 $sIeg_IeyB_TR + 48
	6   libdispatch.dylib                   0x0000000102d23844 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x0000000102d24826 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x0000000102d26e8d _dispatch_queue_override_invoke + 1038
	9   libdispatch.dylib                   0x0000000102d38391 _dispatch_root_queue_drain + 334
	10  libdispatch.dylib                   0x0000000102d38e03 _dispatch_worker_thread2 + 127
	11  libsystem_pthread.dylib             0x0000000102db231b _pthread_wqthread + 220
	12  libsystem_pthread.dylib             0x0000000102db149b start_wqthread + 15
)
(Recorded stack frame)

**Comment by duncangroenewald** [comment]
It seems I can now reliably get a crash by running a particular batch of reports - and the crash seems to occur much sooner than before.  Note that these reports are generated by NSOperations, each NSOperation opens the realm and generates the report for a particular input code.  Usually the queue has 4 concurrent operations but the crash is occurring regardless of whether maxConcurrentOperations = 1 or 4.  The thread ID does not change between the calls to open the realm and the calls to realm.refresh() - which is where the exception gets thrown.

Let me know if you are still looking for a repro case for this issue since I may be able to recreate one more easily now.  

I am just about to test this with a non synced realm (i.e. local realm file) to see if it still occurs.

**Comment by tgoyne** [comment]
A repro case would be wonderful if you can put one together.

**Comment by duncangroenewald** [comment]
Ok I'll see what I can do.

**Comment by duncangroenewald** [comment]
This is annoying - I haven't been able to reproduce in a test app but seem to be able to repeatedly cause the exception with one particular sequence of steps in the application.  Other sequences cause the crash eventually as well but not consistently in the same place.  The crash seems to happen on the first call(realm.refresh(), realm.objects(), etc.) immediately after a realm is opened on a new thread.  If the thread gets passed this point then it does not appear to subsequently crash.

**Comment by duncangroenewald** [comment]
@tgoyne - is there any way I can help debug this issue since I can reproduce it pretty easily in the production application but not in the test app.  Perhaps I am barking up the wrong tree here but it seems this call is failing when it shouldn't be.  I don't have any understanding of how the realm code works but presumably m_runloop is getting set when Realm() is called and subsequent access to the realm uses the call below to check that calls are from the same thread.

Let me know if you have any suggestions as to how I might try and debug this.  I was thinking of putting in some debug logging to log when the m_runloop value is set and when the call below is being made.  Is there some realm id that can be used to identify which realm instance the call is being made on?

bool RunLoopScheduler::is_on_thread() const noexcept
{
    return CFRunLoopGetCurrent() == m_runloop;
}

**Comment by tgoyne** [comment]
Are you opening the Realm in one NSOperation and then accessing it in another? If so that would explain the error; to make that work you would need to use a Realm confined to a queue and run the NSOperation on that queue.

---

If no queue-bound threads are involved (i.e. you don't use asyncOpen, never specify a queue when opening a Realm, and never specify a queue to deliver to when adding an object/collection change notification), the basic flow is:

When the Realm is opened, we [generate a cache key for that Realm](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm.mm#L440), which is `1` for the main thread and `pthread_self()` for other threads. If we have a Realm for the path being opened and that key already we return that, and otherwise create a new RLMRealm instance and cache it using that key.

When a new Realm instance is created, we [create a new default scheduler](https://github.com/realm/realm-object-store/blob/master/src/impl/realm_coordinator.cpp#L206), which on Apple platforms is [RunLoopScheduler](https://github.com/realm/realm-object-store/blob/master/src/util/apple/scheduler.hpp#L29). No runloop is explicitly passed in, so RunLoopScheduler calls CFRunLoopGetCurrent() to capture the current thread's runloop and retains that.

Each time data is read from the Realm, we check that we're on the correct thread, which in RunLoopScheduler's case consists of calling CFRunLoopGetCurrent() and checking if it returned the same thing as when the scheduler was constructed.

---

The problem is presumably in one of these spots. A bug in the caching logic could mean that you're incorrectly getting a Realm for a different thread. The caching code is largely unchanged from 4.x though, so if it's wrong that suggests it was always wrong but in a way that didn't matter until now.

One explanation for the problem would be that our assuption that `CFRunLoopGetCurrent() == CFRunLoopGetCurrent()` always holds is actually incorrect. This part is the biggest difference from 4.x so it's an obvious thing to blame (in 4.x the equivalent assumption was `std::this_thread::id() == std::this_thread::id()`). The documentation explicitly states that there's always exactly one run loop per thread, so unless that's wrong it's not obvious how that could be false, though.

A possibility could be that thread IDs being reused after the thread is terminated are causing problems. If a thread terminates while we have a cached Realm for that thread, then a new thread is created with the same ID, we could get that old Realm from the cache. It would have the correct thread id, but a different CFRunLoop instance. In 4.x we wouldn't notice this happening because we only checked thread id, but in 5.x we would notice it and throw an incorrect thread exception. You could try adding `NSLog(@"thread id: %p, runloop: %p", (void *)pthread_self(), (void *)CFRunLoopGetCurrent());` to the start of [realmWithConfiguration:queue:error:](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm.mm#L429). If this is the problem, immediately before the incorrect thread exception you'll see a threadid which appeared previously but with a different runloop.

I'll also try to put together a test which tests thread ID reuse handling. Even if it turns out to not be what's causing problems for you I think the logic may be incorrect.

**Comment by duncangroenewald** [comment]
@tgoyne No the realm is opened in one operation only.  I think the idea that something is being reused and upsetting your cache seems the more likely scenario.  

I'll try logging what you have suggested.

Currently I am using the Swift Package Manager version - the source files are readonly - is it possible to somehow incorporate this version with source code into my project so I can add the debug comment to the Realm source files ?

**Comment by duncangroenewald** [comment]
Bingo!!


2020-08-20 17:35:29.111117+1000 MakeSpace[5738:133398] <UI>ReportListTableViewController.viewDidLoad()[79]: " called"
thread id: 105553171629632, runloop: 105553147511808
thread id: 105553177572992, runloop: 105553147560448
thread id: 105553177572992, runloop: 105553147560448
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
2020-08-20 17:36:19.298474+1000 MakeSpace[5738:133837] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L001"
thread id: 105553171261888, runloop: 105553147555328
thread id: 105553171261888, runloop: 105553147555328
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
thread id: 105553171403712, runloop: 105553147560192
2020-08-20 17:37:14.194563+1000 MakeSpace[5738:133837] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L002"
thread id: 105553177440768, runloop: 105553214124800
thread id: 105553177440768, runloop: 105553214124800
thread id: 105553177318720, runloop: 105553213604096
thread id: 105553177318720, runloop: 105553213604096
thread id: 105553177318720, runloop: 105553213604096
thread id: 105553177318720, runloop: 105553213604096
thread id: 105553177318720, runloop: 105553213604096
thread id: 105553177318720, runloop: 105553213604096
2020-08-20 17:38:13.213062+1000 MakeSpace[5738:134277] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L006"
thread id: 105553176920384, runloop: 105553213882368
thread id: 105553176920384, runloop: 105553213882368
thread id: 105553176991808, runloop: 105553213898752
thread id: 105553176991808, runloop: 105553213898752
thread id: 105553176991808, runloop: 105553213898752
thread id: 105553176991808, runloop: 105553213898752
thread id: 105553176991808, runloop: 105553213898752
thread id: 105553176991808, runloop: 105553213898752
2020-08-20 17:39:08.381499+1000 MakeSpace[5738:134329] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L007"
thread id: 105553176773440, runloop: 105553214120448
thread id: 105553176773440, runloop: 105553214120448
thread id: 105553176920384, runloop: 105553213882368
thread id: 105553176920384, runloop: 105553213882368
thread id: 105553176920384, runloop: 105553213882368
thread id: 105553176920384, runloop: 105553213882368
thread id: 105553176920384, runloop: 105553213882368
thread id: 105553176920384, runloop: 105553213882368
2020-08-20 17:39:59.178079+1000 MakeSpace[5738:134518] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L011"
thread id: 105553179051712, runloop: 105553214587392
2020-08-20 17:40:02.398492+1000 MakeSpace[5738:134910] *** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018ab819c4 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001c517510c objc_exception_throw + 60
	2   MakeSpace                           0x00000001056f0e28 -[RLMRealm refresh] + 116
	3   MakeSpace                           0x000000010575ffb0 $s10RealmSwift0A0V7refreshSbyF + 52
	4   MakeSpace                           0x0000000104c97308 $s9MakeSpace18StoreChangeReportsC10createData5codes15progressCounter0I7MessageSSSgSaySSG_ySdcySSctF + 836
	5   MakeSpace                           0x0000000104ead714 $s9MakeSpace19BaseReportGeneratorC14createDataFile15progressCounter0I7Message10completionyySdc_ySScySSSgctFyycfU_ + 756
	6   MakeSpace                           0x00000001049337cc $sIeg_IeyB_TR + 52
	7   libdispatch.dylib                   0x00000001084a8120 _dispatch_call_block_and_release + 32
	8   libdispatch.dylib                   0x00000001084a9bfc _dispatch_client_callout + 20
	9   libdispatch.dylib                   0x00000001084c018c _dispatch_root_queue_drain + 848
	10  libdispatch.dylib                   0x00000001084c0b54 _dispatch_worker_thread2 + 140
	11  libsystem_pthread.dylib             0x000000010854b628 _pthread_wqthread + 216
	12  libsystem_pthread.dylib             0x000000010854a398 start_wqthread + 8
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
terminating with uncaught exception of type NSException
(lldb)

**Comment by duncangroenewald** [comment]
If you could give me some guidance on how I can add the realm source code to my project such that I can edit the source code I want to check the values in the call below.  Is there anywhere else that could be generating the same exception that is worth checking?

bool RunLoopScheduler::is_on_thread() const noexcept
{
    return CFRunLoopGetCurrent() == m_runloop;
}

**Comment by duncangroenewald** [comment]
OK I've managed to figure out how to edit the source code and have added the following code:

Swift Class
            let realm = try Realm(configuration: self.realmConfig)
            print("open realm>>thread id: \(ObjectIdentifier(Thread.current)), runloop: \( ObjectIdentifier(CFRunLoopGetCurrent()))");


RunLoopScheduler::RunLoopScheduler(CFRunLoopRef run_loop)
: m_runloop(run_loop ?: CFRunLoopGetCurrent())
{
    CFRetain(m_runloop);
    printf("thread: %p, m: %p\n", (void *)pthread_self(), (void *)m_runloop);
}

bool RunLoopScheduler::is_on_thread() const noexcept
{
    CFRunLoopRef t_runloop = CFRunLoopGetCurrent();
    if (t_runloop != m_runloop) {
       printf("m: %p, c: %p\n", (void *)m_runloop, (void *)t_runloop);
    }
    return t_runloop == m_runloop;
}

The output at the bottom shows that m_runloop has a different value to the current runloop. And that runloop value shows up earlier.  The thread ids don't match between the C++ calls and the Swift calls.  Is there some translation required ?

...
createReport() about to open realm
thread: 0x16df0b000, m: 0x6000037d4500
open realm>>thread id: ObjectIdentifier(0x0000600001eabf40), runloop: ObjectIdentifier(0x00006000037d4500)
realm.refresh>>thread id: ObjectIdentifier(0x0000600001eabf40), runloop: ObjectIdentifier(0x00006000037d4500)
**thread: 0x16daab000, m: 0x6000037f8000**
open realm>>thread id: ObjectIdentifier(0x0000600001e16dc0), runloop: ObjectIdentifier(0x00006000037f8000)
thread: 0x16db37000, m: 0x6000037d6300
realm.refresh>>thread id: ObjectIdentifier(0x0000600001e16dc0), runloop: ObjectIdentifier(0x00006000037f8000)
open realm>>thread id: ObjectIdentifier(0x0000600001e174c0), runloop: ObjectIdentifier(0x00006000037d6300)
thread: 0x16dbc3000, m: 0x6000037c8a00
realm.refresh>>thread id: ObjectIdentifier(0x0000600001e174c0), runloop: ObjectIdentifier(0x00006000037d6300)
open realm>>thread id: ObjectIdentifier(0x0000600001e14f80), runloop: ObjectIdentifier(0x00006000037c8a00)
realm.refresh>>thread id: ObjectIdentifier(0x0000600001e14f80), runloop: ObjectIdentifier(0x00006000037c8a00)
open realm>>thread id: ObjectIdentifier(0x0000600001eabf40), runloop: ObjectIdentifier(0x00006000037d4500)
open realm>>thread id: ObjectIdentifier(0x0000600001eabf40), runloop: ObjectIdentifier(0x00006000037d4500)
open realm>>thread id: ObjectIdentifier(0x0000600001e16dc0), runloop: ObjectIdentifier(0x00006000037f8000)
open realm>>thread id: ObjectIdentifier(0x0000600001e16dc0), runloop: ObjectIdentifier(0x00006000037f8000)
open realm>>thread id: ObjectIdentifier(0x0000600001e174c0), runloop: ObjectIdentifier(0x00006000037d6300)
open realm>>thread id: ObjectIdentifier(0x0000600001e174c0), runloop: ObjectIdentifier(0x00006000037d6300)
open realm>>thread id: ObjectIdentifier(0x0000600001e14f80), runloop: ObjectIdentifier(0x00006000037c8a00)
open realm>>thread id: ObjectIdentifier(0x0000600001e14f80), runloop: ObjectIdentifier(0x00006000037c8a00)
open realm>>thread id: ObjectIdentifier(0x0000600001eabf40), runloop: ObjectIdentifier(0x00006000037d4500)
open realm>>thread id: ObjectIdentifier(0x0000600001eabf40), runloop: ObjectIdentifier(0x00006000037d4500)
open realm>>thread id: ObjectIdentifier(0x0000600001e174c0), runloop: ObjectIdentifier(0x00006000037d6300)
open realm>>thread id: ObjectIdentifier(0x0000600001e174c0), runloop: ObjectIdentifier(0x00006000037d6300)
open realm>>thread id: ObjectIdentifier(0x0000600001e16dc0), runloop: ObjectIdentifier(0x00006000037f8000)
open realm>>thread id: ObjectIdentifier(0x0000600001e16dc0), runloop: ObjectIdentifier(0x00006000037f8000)
open realm>>thread id: ObjectIdentifier(0x0000600001e14f80), runloop: ObjectIdentifier(0x00006000037c8a00)
open realm>>thread id: ObjectIdentifier(0x0000600001e14f80), runloop: ObjectIdentifier(0x00006000037c8a00)
open realm>>thread id: ObjectIdentifier(0x0000600001eabf40), runloop: ObjectIdentifier(0x00006000037d4500)
open realm>>thread id: ObjectIdentifier(0x0000600001e16dc0), runloop: ObjectIdentifier(0x00006000037f8000)
open realm>>thread id: ObjectIdentifier(0x0000600001e174c0), runloop: ObjectIdentifier(0x00006000037d6300)
open realm>>thread id: ObjectIdentifier(0x0000600001e14f80), runloop: ObjectIdentifier(0x00006000037c8a00)
2020-08-20 20:02:24.252615+1000 MakeSpace[6506:190623] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L011"
createReport() about to open realm
thread: 0x16dc4f000, m: 0x6000037cfe00
open realm>>thread id: ObjectIdentifier(0x0000600001e63540), runloop: ObjectIdentifier(0x00006000037cfe00)
realm.refresh>>thread id: ObjectIdentifier(0x0000600001e63540), runloop: ObjectIdentifier(0x00006000037cfe00)
open realm>>thread id: ObjectIdentifier(0x0000600001e63540), runloop: ObjectIdentifier(0x00006000037cfe00)
open realm>>thread id: ObjectIdentifier(0x0000600001e63540), runloop: ObjectIdentifier(0x00006000037cfe00)
open realm>>thread id: ObjectIdentifier(0x0000600001e63540), runloop: ObjectIdentifier(0x00006000037cfe00)
open realm>>thread id: ObjectIdentifier(0x0000600001e63540), runloop: ObjectIdentifier(0x00006000037cfe00)
2020-08-20 20:02:31.988262+1000 MakeSpace[6506:190668] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L006"
2020-08-20 20:02:32.837665+1000 MakeSpace[6506:190690] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L002"
2020-08-20 20:02:35.074163+1000 MakeSpace[6506:190545] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L007"
open realm>>thread id: ObjectIdentifier(0x0000600001e63540), runloop: ObjectIdentifier(0x00006000037cfe00)
2020-08-20 20:03:08.546080+1000 MakeSpace[6506:190546] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L001"
StoreChangeReports.createData() about to open realm
thread: 0x16d907000, m: 0x60000b7b2600
open realm>>thread id: ObjectIdentifier(0x00006000013e29c0), runloop: ObjectIdentifier(0x000060000b7b2600)
realm.refresh>>thread id: ObjectIdentifier(0x00006000013e29c0)-<NSThread: 0x6000013e29c0>{number = 14, name = (null)}, runloop: ObjectIdentifier(0x000060000b7b2600)
open realm>>thread id: ObjectIdentifier(0x00006000013e29c0), runloop: ObjectIdentifier(0x000060000b7b2600)
createReport() about to open realm
thread: 0x16de7f000, m: 0x6000037ce800
open realm>>thread id: ObjectIdentifier(0x0000600001e2c280), runloop: ObjectIdentifier(0x00006000037ce800)
realm.refresh>>thread id: ObjectIdentifier(0x0000600001e2c280), runloop: ObjectIdentifier(0x00006000037ce800)
open realm>>thread id: ObjectIdentifier(0x0000600001e2c280), runloop: ObjectIdentifier(0x00006000037ce800)
open realm>>thread id: ObjectIdentifier(0x0000600001e2c280), runloop: ObjectIdentifier(0x00006000037ce800)
open realm>>thread id: ObjectIdentifier(0x0000600001e2c280), runloop: ObjectIdentifier(0x00006000037ce800)
open realm>>thread id: ObjectIdentifier(0x0000600001e2c280), runloop: ObjectIdentifier(0x00006000037ce800)
open realm>>thread id: ObjectIdentifier(0x0000600001e2c280), runloop: ObjectIdentifier(0x00006000037ce800)
2020-08-20 20:03:43.255156+1000 MakeSpace[6506:190622] <BG>MonthlyStoreReportOperation.createReport(completion:)[118]: "Report completed for L012"
StoreChangeReports.createData() about to open realm
open realm>>thread id: ObjectIdentifier(0x0000600001001700), runloop: ObjectIdentifier(0x000060000b7c8900)
realm.refresh>>thread id: ObjectIdentifier(0x0000600001001700)-<NSThread: 0x600001001700>{number = 15, name = (null)}, runloop: ObjectIdentifier(0x000060000b7c8900)
m: 0x6000037f8000, c: 0x60000b7c8900
2020-08-20 20:03:43.264027+1000 MakeSpace[6506:191305] *** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'

**Comment by tgoyne** [comment]
I was able to reproduce this with a nice small test:

```
- (void)testThreadIDReuse {
    NSMutableArray *realms = [NSMutableArray array];
    std::unordered_set<pthread_t> threadIds;
    bool done = false;
    while (!done) {
        std::thread([&] {
            RLMRealm *realm = [RLMRealm defaultRealm];
            [realms addObject:realm];
            (void)[IntObject allObjectsInRealm:realm].count;
            [realm refresh];
            if (!threadIds.insert(pthread_self()).second) {
                done = true;
            }
        }).join();
    }
}
```

I think this'll be pretty straightforward to fix now that I understand what's going wrong.

**Comment by tgoyne** [comment]
> Just curious as to why you changed from using the thread id itself ?

The 5.0 changes to support delivering notifications to different threads requires that the main thread's scheduler be based on the runloop because that's something we can get from different threads in a documented way, while you technically can't get the main thread's threadid from different threads. Rather than special-casing the main thread's scheduler I just made them all use the runloop because there didn't appear to be any downside to that.

**Comment by xinsight** [comment]
This seems to be an issue with older versions of realm as well - I'm currently seeing this on a project with v3.18.0.

I was able to replicate the crash by background/foregrounding my app several times (we do some Realm querying when the app comes to the foreground).

Here's a simple test based on @tgoyne's awesome explanation above.

```swift
// define this somewhere that will persist in memory
var temp_thread_runloops: [String: String] = [:]
```

```swift
var realm: Realm {
            // log thread and current run loop right before creating your realm instance
            let t1 = String(format: "%p", pthread_self())
            let t2 = String(format: "%p", unsafeBitCast(CFRunLoopGetCurrent(), to: UnsafeMutablePointer<Void>.self))
            if temp_thread_runloops[t2] != nil, temp_thread_runloops[t2] != t1 {
                fatalError("🔥 bug in realm instance cacheing!!")
            }
            NSLog("t1: \(t1) t2: \(t2)")
            temp_thread_runloops[t2] = t1
            return try! Realm(configuration: configuration)
}
```

Guess i'll have to backport the patch in #6714 until this project moves to a more modern version of realm.
