### ISSUE TITLE
Performance issue: Lag and slow performance when write(create) and delete objects.

### ISSUE THREAD

**Issue by ismmajl** [realm/realm-cocoa#6713]
I have a problem while saving/deleting objects.

I have an array with objects and i want to change every object a property.This takes an non acceptable amount of time for 1000 objects (5-8 seconds).

Here is my code to write or delete objects:

 

> @discardableResult
>  static func save(items: [Object]) -> Success {
>     let instance = self.instance()
>        
>     do {
>         for item in items {
>                
>             if let realm = item.realm {
>                 try realm.write {
>                     realm.create(type(of: item), value: item, update: .all)
>                 }
>             } else {
>                 instance.beginWrite()
>                 instance.create(type(of: item), value: item, update: .all)
>                 try instance.commitWrite()
>             }
>         }
>         return true
>     } catch {
>         return false
>     }
> }

> @discardableResult
> static func delete(items: [Object]) -> Success {
>     let instance = self.instance()
>     
>     instance.beginWrite()
>     
>     for item in items {
>         guard let primaryKey = item.objectSchema.primaryKeyProperty else { continue }
>         guard let value = item.value(forKey: primaryKey.name) else { continue }
>         
>         if let object = instance.dynamicObject(ofType: String(describing: item.classForCoder), forPrimaryKey: value) {
>             instance.delete(object)
>         }
>     }
>     
>     do {
>         try instance.commitWrite()
>         return true
>     } catch {
>         return false
>     }
> }

**Comment by tgoyne** [comment]
```
        if let realm = item.realm {
            try realm.write {
                realm.create(type(of: item), value: item, update: .all)
            }
        }
```

This is a very slow no-op. Updating an object with it current value doesn't do anything.

For the case where the objects passed in aren't managed by Realm and actually do need to be added, you should use a single write transaction instead of a write transaction per object. Each write transaction has some fixed overhead which is much more expensive than creating a single object.
