### ISSUE TITLE
RealmSwift 5.3.5 Failure to migrate from V4.4.1 database correctly

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#6716]
## Goals

Upgrade the Realm Cloud client application from RealmSwift v4.4.1 to v5.3.5 automatically.

Note this issue has been logged previously against earlier versions

## Expected Results

Expect upgrade to complete successfully when new version of the client application using RealmSwift v5.3.5 opens an existing synced or non-synced realm file.

## Actual Results

The local realm file appears to upgrade but certain subsequent realm queries return nil instead of the correct list or realm objects.

## Steps for others to Reproduce

Update an existing Realm client application from RealmSwift v4.4.1 to v5.3.5 and run the application using the existing v4.4.1 realm file.

There should be a slight delay while the realm file gets upgraded to the new realm-core file format when first opening the realm file - i.e. call to Realm() api.

Once the realm has been opened perform a real query such as the following:

let items = realm.objects(Item.self).filter("id = %@", "some")

In general this query returns nil whereas the following returns the correct list of items

let items = realm.objects(Item.self)

## Code Sample

See above

## Version of Realm and Tooling

Realm framework version: RealmSwift v 5.3.5

Realm Object Server version: Realm Cloud

Xcode version: 11.6

iOS/OSX version: macOS 10.15.6

Dependency manager + version: N/A

**Comment by ZComwiz** [comment]
I think this is not an upgrade issue— this is a fundamental problem in Realm 5.x.x/5.3.x which is progressively getting worse with each update. We are seeing duplicate objects being created and very wacky stuff. I hope you didn't push your update out to production like we did when we upgraded to 5.3.3 and didn't see any bugs until our we started receiving crash reports @duncangroenewald

**Comment by duncangroenewald** [comment]
Fortunately we have a bunch of automated tests and we generally do a few months of usage in development before going to production.

Have you tried deleting the existing local realm files and then recreating them from the 5.3.5 client ?  That seems to work fine so far - it's seems when the old file format gets upgraded something goes wrong.  We also didn't see any issues yet if we used the non-sync version i.e. installed using Swift Package Manager.

**Comment by geragray** [comment]
@ZComwiz @duncangroenewald apologies for not hearing back from us earlier. Realm Core team right now is focusing on the migration issue that you and a handful of other users have experienced. We are prioritizing this work over everything else.

**Comment by duncangroenewald** [comment]
Good to hear, let us know if there is anything we can do to help debug these issues

**Comment by jedelbo** [comment]
@duncangroenewald Just to be sure how the problem manifests: Once you have upgraded the file, the query will not return the expected number of objects - in fact it returns none. You can run the query multiple times and get the same wrong result. The error is not seen, if Sync is not involved.

It would be very helpful to us, if you could provide a realm file where this behavior can be seen. You can share it privately with us by sending it to jorgen.edelbo@mongodb.com

**Comment by duncangroenewald** [comment]
@jedelbo 
Yes it appears that any time any filter is applied the result is nil - of course I have not tried every possibility though.  If no filter is applied then the full result set is returned correctly.

I will send you two files - one the v4.4.1 file and the second the upgraded file that shows this behaviour.  

To further clarify there are two scenarios here, that both appear to show the same problem:
1.  A local realm file
2. A synced realm file (I don't know if I know how to find the component parts of this one to send since there is some sort of directory structure containing a bunch of files)

For the purposes of this exercise I will just send you the local realm file - which is just a backup of the synced realm file made using the writeCopy() api.

**Comment by jedelbo** [comment]
@duncangroenewald Thank you for the file. I am sure this can help us finding the root cause of this problem.

**Comment by jedelbo** [comment]
Root cause found! Now we just have to pick the right solution.

**Comment by duncangroenewald** [comment]
You're the man! nice work.

**Comment by duncangroenewald** [comment]
@jedelbo btw what is the process for getting this into a new realm swift release so we can start using it? Just want to understand what the turnaround time on these kinds of issues typically is for future reference - thanks

**Comment by geragray** [comment]
@duncangroenewald after @jedelbo will implement a fix in Realm Core it will take around a day to get the new Cocoa SDK release. It is a top priority in our backlog now.

**Comment by duncangroenewald** [comment]
This is fixed in RealmSwift 5.4.0 - thanks.
