### ISSUE TITLE
Xcode12 beta5 Carthage build fail

### ISSUE THREAD

**Issue by AlexanderPan** [realm/realm-cocoa#6717]
## Goals
Carthage version:0.35.0 build Realm 

## Expected Results
Carthage version:0.35.0 build Realm Success

## Actual Results
```
/Users/PathToProject/Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/src/object_changeset.hpp:24:10: fatal error: 'realm/keys.hpp' file not found
#include <realm/keys.hpp>
         ^~~~~~~~~~~~~~~~
/Users/PathToProject/Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/src/object_changeset.hpp:24:10: note: did not find header 'keys.hpp' in framework 'realm' (loaded from '/Users/UserName/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189h/realm-cocoa/v5.3.5/Build/Products/Release-iphonesimulator')
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC /Users
```

## Steps for others to Reproduce
```
carthage update --platform iOS --cache-builds --no-use-binaries
```

## Version of Realm and Tooling

Realm framework version: v 5.3.5

Realm Object Server version: N/A

Xcode version: 12 beta 5

iOS/OSX version: 14

Dependency manager + version: Carthage with Xcode 11.6

**Comment by gemmakbarlow** [comment]
Also seeing this using the Xcode 12 Beta 5 command-line tools, Carthage 0.35.0

**Comment by David2XN** [comment]
I have the same problem on with Xcode12 beta6.

**Comment by leemaguire** [comment]
Have you tried clearing all derived data, cached builds and cleaned your workspace?

**Comment by SakuragiYoshimasa** [comment]
I also have the problem when using Xcode 12 Beta6 even though after I cleared all derived data of Xcode and cache files of carthage.

**Comment by Patrick-Remy** [comment]
Can confirm, also when clearing ~/Library/Caches/org.carthage.CarthageKit/DerivedData/ and using the script of https://github.com/Carthage/Carthage/issues/3019#issuecomment-681825436 the build fails with the above error message

**Comment by aalenliang** [comment]
Tried 5.4.0, still got the same error.

```
.../Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/src/object_changeset.hpp:24:10: fatal error: 'realm/keys.hpp' file not found
#include <realm/keys.hpp>
         ^~~~~~~~~~~~~~~~
.../Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/src/object_changeset.hpp:24:10: note: did not find header 'keys.hpp' in framework 'realm' (loaded from '.../Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/realm-cocoa/v5.4.0/Build/Products/Release-iphonesimulator')
1 error generated.
```

**Comment by ericjordanmossman** [comment]
I'm seeing the same with 5.4.0 too (`fatal error: 'realm/keys.hpp' file not found`). We'll still need to narrow down the cause.

**Comment by chchrn** [comment]
I have the same problem on with Xcode12 beta 6, realm 5.4.0, carthage 0.35.0

**Comment by jafara** [comment]
i moved to cocoapods, carthage is dead

**Comment by olejnjak** [comment]
Any progress on this? Or any hints how this could be fixed? 🙂

**Comment by ericjordanmossman** [comment]
@olejnjak No update yet. Will let you know. :slightly_smiling_face:

**Comment by olejnjak** [comment]
Thanks for quick update 🙂 is there any hint where to start when trying to fix this issue? I'm open to contribution but it would be nice to know where to start 🙂

**Comment by Senocico** [comment]
The same issue 😱

**Comment by ericjordanmossman** [comment]
[carthage-xcodebuild.HvGU99.log](https://github.com/realm/realm-cocoa/files/5240559/carthage-xcodebuild.HvGU99.log)
@tgoyne Take my failing build log for example -- the build fails on `fatal error: 'realm/keys.hpp' file not found
#include <realm/keys.hpp>`.

`realm/keys.hpp` is a header file in realm-core.
Sure enough I can see that in the process of downloading the submodule realm-core, the download script claims that `5.0.23` is already present. But evidently realm/keys.hpp is not in my `/Library/Caches/org.carthage.CarthageKit/DerivedData/`.

The tar.xz is downloaded earlier, though:
```
PhaseScriptExecution Download\ Core\ and\ Sync /Users/mdb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/realm-cocoa/v5.4.1/Build/Intermediates.noindex/ArchiveIntermediates/RealmSwift/IntermediateBuildFilesPath/Realm.build/Release-watchos/Download\ Core\ Library.build/Script-5D659E7F1BE04556006515A0.sh (in target 'Download Core Library' from project 'Realm')
    cd /Users/mdb/Downloads/test-carthage/Carthage/Checkouts/realm-cocoa
    /bin/sh -c /Users/mdb/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/realm-cocoa/v5.4.1/Build/Intermediates.noindex/ArchiveIntermediates/RealmSwift/IntermediateBuildFilesPath/Realm.build/Release-watchos/Download\\\ Core\\\ Library.build/Script-5D659E7F1BE04556006515A0.sh
Downloading dependency: sync 5.0.23 from https://static.realm.io/downloads/sync/realm-sync-xcframework-5.0.23.tar.xz
```
Is the order of the compiling causing a problem?

**Comment by tgoyne** [comment]
So far it appears to be a combination of Xcode 12's xcframework logic being incorrect when more than one target in a project depends on the same xcframework and carthage building a scheme that it shouldn't be building, which causes it to hit the xcode problem. I'm currently experimenting with workarounds.

**Comment by tgoyne** [comment]
v5.4.2 switches the prebuilt carthage artifact to being built with Xcode 12, but this is unfortunately via [ridiculous hacks](https://github.com/realm/realm-cocoa/blob/f64ac045d8cb171d8e317d9b854df7215aed7466/Jenkinsfile.releasability#L129) and not by fixing the root problem, so if you specifically want to build from source that still won't work.

**Comment by caobug** [comment]
Not working, Realm version: v5.4.2, Carthage: 0.35.1
```
#include <realm/keys.hpp>
         ^~~~~~~~~~~~~~~~
```

**Comment by tgoyne** [comment]
https://github.com/realm/realm-cocoa/pull/6787 adds a better workaround that should make `carthage update --no-use-binaries` work.
