### ISSUE TITLE
XCode 12 Beta 5 Undefined Symbol Build Fail

### ISSUE THREAD

**Issue by AlexNoseworthy** [realm/realm-cocoa#6718]
## Goals
Build project containing Realm in XCode12 Beta 5

## Expected Results
Successfully build project containing Realm in XCode12 Beta 5

## Actual Results
warning: ignoring file ~/Pods/Realm/core/librealmcore-watchos.a, missing required architecture arm64 in file ~/Pods/Realm/core/librealmcore-watchos.a (4 slices)
Undefined symbols for architecture arm64:

![Screen Shot 2020-08-24 at 4 48 02 PM](https://user-images.githubusercontent.com/23081088/91090947-43489080-e62c-11ea-80f4-d7ca16d1743e.png)

![Screen Shot 2020-08-24 at 4 48 15 PM](https://user-images.githubusercontent.com/23081088/91090969-49d70800-e62c-11ea-9882-2e8aa85b0894.png)
-->

## Steps for others to Reproduce
Try building project using Realm via Cocoapod on XCode12 Beta 5

## Version of Realm and Tooling

Realm framework version: 5.3.5

Realm Object Server version: N/A

Xcode version: 12 beta 5

iOS/OSX version: iOS14 + OSX 10.15.6

Dependency manager + version: Cocoapod 1.9.3

**Comment by tgoyne** [comment]
See https://github.com/realm/realm-cocoa/issues/6684.
