### ISSUE TITLE
RLMException in 5.x.x reason: 'Can only delete an object from the Realm it belongs to

### ISSUE THREAD

**Issue by seki-ne** [realm/realm-cocoa#6720]
## Goals

migration.delete not crash like 4.4.1
## Expected Results

migration.delete not crash like 4.4.1
## Actual Results

'RLMException', reason: 'Can only delete an object from the Realm it belongs to.'
## Steps for others to Reproduce

https://github.com/seki-ne/sample
build one time, update schemeversion, then got the crash

## Version of Realm and Tooling

Realm framework version: 5.3.5, 5.3.4, 5.3.3

Realm Object Server version: ?

Xcode version: 11.4.1

iOS/OSX version: 13.4.1

Dependency manager + version: ?

**Comment by leemaguire** [comment]
Hi @seki-ne 

To solve your issue you can use:

`
let config = Realm.Configuration(
            schemaVersion: schemaVersion,
            migrationBlock: { migration, oldSchemaVersion in
                if oldSchemaVersion < 3 {
                    migration.deleteData(forType: Cat.className())
                }
            }
        )
        Realm.Configuration.defaultConfiguration = config
`
