### ISSUE TITLE
Xcode12 beta6 build fail

### ISSUE THREAD

**Issue by kevin3747118** [realm/realm-cocoa#6725]
## Goals
Build APP successfully

## Actual Results
ld: in /Users/XXX/Desktop/XXXX/XXXX/Pods/Realm/core/librealmcore-ios.a(array_binary.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Version of Realm and Tooling
Realm framework version: 5.3.5
Xcode version: 12.0 Beta 6

![截圖 2020-08-28 上午11 23 39](https://user-images.githubusercontent.com/16334296/91517787-33c59200-e921-11ea-8b61-35703df1a37a.png)

**Comment by perlasivakrishna** [comment]
I have the same issue, unable to build in xcode12

**Comment by jsflax** [comment]
@kyungho-kim @perlasivakrishna are you talking about SwiftUI previews? Does this issue persist on a clean build?

**Comment by kyungho-kim** [comment]
@jsflax Right, SwiftUI preview. I cleaned build folder many times but failed to build.

**Comment by perlasivakrishna** [comment]
No in my case not in  SwiftUI Previews, it's happening while building project.

**Comment by jiyeonlab** [comment]
I have same issue. 
Realm version: 5.2
Xcode version: 12.0 beta 6

**Comment by mrezk** [comment]
I had this same issue.
You should add arm64 to the excluded architectures both in your main project and in the Pods project (if you use cocoapods).  
<img width="700" alt="Screen Shot 2020-08-31 at 12 01 13" src="https://user-images.githubusercontent.com/1587829/91734986-0c213480-eb82-11ea-8ccc-af75bf65f97b.png">

Let me know if that works for you!

**Comment by perlasivakrishna** [comment]
@mrezk Adding arm64 to the excluded archs that error was gone, but another error not sure whether it's because of adding arm64 to excluded one. 
![Screenshot 2020-08-31 at 9 20 20 PM](https://user-images.githubusercontent.com/6779941/91740237-a6a86480-ebd0-11ea-9173-dabb7d3782b0.png)
Also Would love to know the reason to add arm64 in excluded archs.

**Comment by mrezk** [comment]
@perlasivakrishna have you tried a clean & build?

**Comment by perlasivakrishna** [comment]
@mrezk  yes tried it, tried clearing derived data,  both didn't help

**Comment by kyungho-kim** [comment]
@mrezk In my case, resolved! I add "arm64" to the excluded architectures both in my project and the pod project. Now SwiftUI preview works. Thanks 🙏

**Comment by duncangroenewald** [comment]
See #6684
