### ISSUE TITLE
Crash related to Swift 5 Exclusivity Enforcement

### ISSUE THREAD

**Issue by adamk77** [realm/realm-cocoa#6728]
## Goals
To be able to use the `filter` method of the `Result<Element>` object. 

## Expected Results
Method works without crashing.

## Actual Results
Crashes with:
`Thread 1: Simultaneous accesses to 0x7ffca400a210, but modification requires exclusive access`

## Steps for others to Reproduce
Please see sample code below. Attached is also the XCode project.

## Code Sample
Summary:

- If I call the `filter` method that returns Realm's `Result<Element>` object, it crashes. 
- It does NOT crash if I call the `filter` method (the `throws` variant) that returns an array instead of `Result<Element>`.
- It does NOT crash if I convert `Result` into an `Array` and call the same `filter` on the array. 

```
class Video: Object {
    @objc dynamic var slug = ""
    init(slug: String) {
        super.init()
        self.slug = slug
    }
    
    required init() { super.init() }
    
    public override static func primaryKey() -> String? { return "slug" }
}

class ViewController: UIViewController {
    let realm = try! Realm()
    var episodesArray = [Video]()
    var videos: [Video]?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        addData()
        crash()
        // noCrash()
    }

    func crash() {
        // Note: returns Result<Video>
        let videos = realm.objects(Video.self) 

        let filteredVideos = videos.filter { !self.episodesArray.contains($0) }
        episodesArray.append(contentsOf: filteredVideos)
        print(episodesArray)
    }

    func noCrash() {
        // Note: returns Array<Video>
        let videos = Array<Video>(realm.objects(Video.self)) 

        let filteredVideos = videos.filter { !self.episodesArray.contains($0) }
        episodesArray.append(contentsOf: filteredVideos)
        print(episodesArray)
    }

    func addData() {
        try! realm.write {
            for i in 0..<3 {
                realm.add(Video(slug: "video_\(i)"), update: .all)
            }
        }
    }
}
```
## Version of Realm and Tooling

Realm framework version: 5.3.5

Realm Object Server version: n/a

Xcode version: 11.6

iOS/OSX version: Simulator iPhone 11 Pro (13.6)

Dependency manager + version: Cocoapods 1.10.0.beta.2

[RealmTest_Exclusivity_Crash.zip](https://github.com/realm/realm-cocoa/files/5143626/RealmTest_Exclusivity_Crash.zip)

**Comment by tgoyne** [comment]
Swift's `filter()` returns a lazy view rather than immediately evaluating the filter and creating an array. This means that in `foo.append(contentsOf: bar.filter { ... })`, the filter function is called from inside `append()`.  Since your filter function access the array which is being appended to, this violates Swift's exclusivity requirements. Converting the Results to an Array first sidesteps this because Array's filter() function, unlike Collection's, is eager and produces another Array. Other ways to fix this would be to force the filter to be eager by converting the result of that to an Array, or acquire a local reference to `episodesArray` and check that instead of the property inside the filter function.

**Comment by adamk77** [comment]
> Swift's `filter()` returns a lazy view rather than immediately evaluating the filter and creating an array. This means that in `foo.append(contentsOf: bar.filter { ... })`, the filter function is called from inside `append()`. Since your filter function access the array which is being appended to, this violates Swift's exclusivity requirements. Converting the Results to an Array first sidesteps this because Array's filter() function, unlike Collection's, is eager and produces another Array. Other ways to fix this would be to force the filter to be eager by converting the result of that to an Array, or acquire a local reference to `episodesArray` and check that instead of the property inside the filter function.

Ah -- lazy evals. Thanks for explanation. Makes perfect sense.
