### ISSUE TITLE
Operation not permitted when trying to open realm

### ISSUE THREAD

**Issue by zhiliang729** [realm/realm-cocoa#6732]
!!! MANDATORY TO FILL OUT !!!

version 5.3.5 crash again!!!

## Goals

Know the reason why it happens
## Expected Results

apps not crashing
## Actual Results

Unable to open a realm at path '/var/mobile/Containers/Data/Application/311B2E33-55D3-4CCF-BACA-3F51F83CEA16/Documents/balance.realm.lock': open() failed: Operation not permitted Path: /var/mobile/Containers/Data/Application/311B2E33-55D3-4CCF-BACA-3F51F83CEA16/Documents/balance.realm.lock

Exception backtrace:
0 Realm                               0x000000010132ed78 _ZN5realm4util4File13open_internalERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS1_10AccessModeENS1_10CreateModeEiPb + 712
2 Realm                               0x0000000101267310 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 1352
3 Realm                               0x000000010126a43c _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 244
4 Realm                               0x000000010126eb68 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 392
5 Realm                               0x0000000101046034 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1156
6 Realm                               0x00000001010451a8 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 68
7 Realm                               0x000000010104503c _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 168
8 Realm                               0x000000010111b668 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 120
9 Realm                               0x00000001010eaae4 _Z26RLMRealmTranslateExceptionPU15__autoreleasingP7NSError + 2676
## Steps for others to Reproduce

No clue how.
## Code Sample

realmQueue.async {
            
            autoreleasepool {
                
                let data = balance.value.description
                
                if let realm = self.realm {  //   <----- crash here， the call is below
                          // to do some thing
                }
            }
}

    var realm: Realm? {
        get {
            do {
                return try Realm(configuration: cfg)
            } catch  {
                Crashlytics.crashlytics().log("\(error.localizedDescription)")    // the log here
                return nil
            }
        }
    }

## Version of Realm and Tooling

Realm framework version: ?
5.3.5
Realm Object Server version: ?

Xcode version: ?
11.6
iOS/OSX version: ?
iOS   12.4.1 (16G102)
Dependency manager + version: ?

**Comment by zhiliang729** [comment]
same to the issue  #6505

**Comment by leemaguire** [comment]
Hi @zhiliang729 Can you give us more context with how you are using Realm? Are you using any app extensions, multithreading etc? Is this issue intermittent? Could you also share with us your Realm Configuration object?

Thanks

**Comment by zhiliang729** [comment]
@leemaguire I have a singleton to manage all the realm action like this: 

class TWBalanceData: Object {
    @objc dynamic var tokenID: Int32 = 0
    
    @objc dynamic var symbol: String = ""
    
    @objc dynamic var changeRate: String = ""
    
    @objc dynamic var balance: String = "0"
    
    @objc dynamic var freeze: String = "0"
    
    @objc dynamic var totalBalance: String = "0"
    
    @objc dynamic var lockdropBalance: String = "0"
    
    @objc dynamic var tigrisStakeAmount: String = "0"
    
    @objc dynamic var tigrisWithdrawingAmount: String = "0"
    
    @objc dynamic var address: String = ""
    
    @objc dynamic var id: String = NSUUID().uuidString

    override class func primaryKey() -> String? { return "id" }
}

struct TWBalance {
    var balance: String
    var freeze: String
    var totalBalance: String
    var lockdropBalance: String
    var tigrisStakeAmount: String
    var tigrisWithdrawingAmount: String
}

enum TWBalanceDataType {
    case balance
    case freeze
    case totalBalance
    case lockdropBalance
    case tigrisStakeAmount
    case tigrisWithdrawingAmount
    case changeRate
}

fileprivate let BalanceDataVersion: UInt64 = 3

class TWBalanceDataManager: NSObject {
    
    let realmQueue: DispatchQueue
    let cfg: Realm.Configuration
    
    var realm: Realm? {
        get {
            do {
                return try Realm(configuration: cfg)
            } catch  {
                Crashlytics.crashlytics().log("BalanceDataManager realm get error: \(error.localizedDescription)")
                return nil
            }
        }
    }
    
    @objc static let shared: TWBalanceDataManager = TWBalanceDataManager()
    
    override init() {
        
        realmQueue = DispatchQueue(label: "RealmQueue")
        
        var realmPath = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first ?? ""
        realmPath += "/balance.realm"
        var bid = Bundle.main.bundleIdentifier ?? ""
        bid = bid.md5()
        var ACN = "Balance-" + bid
        ACN = ACN.md5()
        var key = ACN + bid
        let i = key.index(key.startIndex, offsetBy: 64)
        key = String(key.prefix(upTo: i))
        let data = key.data(using: .utf8) ?? Data()
        
        do {
            try FileManager.default.setAttributes([FileAttributeKey.protectionKey: FileProtectionType.none], ofItemAtPath: realmPath)
        } catch {
            logger.debug("balanceRealm setAttributes FileProtectionType.none error, path: \(realmPath)")
        }
        
        cfg = Realm.Configuration.init(fileURL: URL(string: realmPath), encryptionKey: data, readOnly: false, schemaVersion: BalanceDataVersion, migrationBlock: nil, deleteRealmIfMigrationNeeded: false, shouldCompactOnLaunch: nil, objectTypes: [TWBalanceData.self])
    }
    
    func updateDataChangeRate(_ toeknID: Int32, changeRate: String) {
        
        realmQueue.async {
            autoreleasepool {
                do {
                    if let realm = self.realm, let address = TWWalletManager.shared.currentAddress {
                        if let results = realm.objects(TWBalanceData.self).filter("tokenID = %d AND address = %@", toeknID, address).first {
                            if changeRate != results.changeRate {
                                try realm.write {
                                    results.changeRate = changeRate
                                }
                            }
                        }
                    }
                } catch {
                }
            }
        }
    }
    
    func updateData(_ tokenID: Int32, type: TWBalanceDataType, balance: Balance) {
        realmQueue.async {
            
            autoreleasepool {
                
                let data = balance.value.description
                
                if let realm = self.realm,
                    let address = TWWalletManager.shared.currentAddress {
                    
                    if let results = realm.objects(TWBalanceData.self).filter("tokenID = %d AND address = %@", tokenID, address).first {
                        
                        var isHasWrite = false
                        switch type {
                        case .balance:
                            if results.balance != data {
                                isHasWrite = true
                            }
                        case .freeze:
                            if results.freeze != data {
                                isHasWrite = true
                            }
                        case .totalBalance:
                            if results.totalBalance != data {
                                isHasWrite = true
                            }
                        case .lockdropBalance:
                            if results.lockdropBalance != data {
                                isHasWrite = true
                            }
                        case .tigrisStakeAmount:
                            if results.tigrisStakeAmount != data {
                                isHasWrite = true
                            }
                        case .tigrisWithdrawingAmount:
                            if results.tigrisWithdrawingAmount != data {
                                isHasWrite = true
                            }
                        default:
                            break
                        }
                        
                        if isHasWrite {
                            do {
                                
                                try realm.write {
                                    switch type {
                                    case .balance:
                                        results.balance = data
                                    case .freeze:
                                        results.freeze = data
                                    case .totalBalance:
                                        results.totalBalance = data
                                    case .lockdropBalance:
                                        results.lockdropBalance = data
                                    case .tigrisStakeAmount:
                                        results.tigrisStakeAmount = data
                                    case .tigrisWithdrawingAmount:
                                        results.tigrisWithdrawingAmount = data
                                    default:
                                        break
                                    }
                                }
                                
                            } catch let error {
                                Crashlytics.crashlytics().log("BalanceDataManager updateData tokenID: \(tokenID),"
                                    + "type: \(type), balance: \(data),  error: \(error.localizedDescription)")
                            }
                        }
                    }
                }
            }
        }
    }
    
    func create(_ data: TWBalanceData, completion :@escaping (Bool) -> Void) {
        realmQueue.async {
            autoreleasepool {
                do {
                    if let realm = self.realm {
                        if let _ = realm.objects(TWBalanceData.self).filter("tokenID = %d AND address = %@", data.tokenID, data.address).first {
                            
                        } else {
                            try realm.write {
                                realm.add(data, update: .modified)
                            }
                        }
                    } else {
                        completion(false)
                    }
                } catch {
                    completion(false)
                }
            }
        }
    }
}




Some where in the app, I will update or create data, the calls are like this:

.....
let global = DispatchQueue(label: "TWNonceAsync")
........

global.async {
       ...........
       TWBalanceDataManager.shared.update(1234, type: .balance, balance: someObject)
       ...........
}

**Comment by leemaguire** [comment]
@zhiliang729 does this still happen in 5.4.2? We have added changes to our file locking mechanism, and since added a guard around it causing issues on older versions of iOS.

**Comment by ericjordanmossman** [comment]
I'm closing #6732 in favor of #6505. Please continue discussion there.

**Comment by niralishaha25** [comment]
Still facing the crash for real 5.5.0
