### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by marinofaggiana** [realm/realm-cocoa#6733]
Hi, I call several time a little query that return an array freeze(), every results has > 3000 records:
Note. update today the v5.3.6 but this issue continue 

```
let realm = try! Realm()
  realm.refresh()
  var metadatas: [tableMetadata] = []
                
  let results = realm.objects(tableMetadata.self).filter(predicate).sorted(byKeyPath: sorted, ascending: ascending)
        
  if results.count > 0 {
      return Array(results.freeze())
```

after 100/200 or 300 time crashed with;

Could not write to database: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 23887872 offset: 201326592" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 23887872 offset: 201326592, Error Code=9}

Possible that the issue is before this call when I write in database but 23887872 is not a big database ... whats happens?

<img width="705" alt="Schermata 2020-09-03 alle 16 25 09" src="https://user-images.githubusercontent.com/8616947/92128391-a2fc2400-ee02-11ea-9aae-a16fe5e3921d.png">

**Comment by pavel-ship-it** [comment]
Hi @marinofaggiana 

Is it happening on your physical device (what kind of it) or is it on iOS simulator?

Thanks

**Comment by marinofaggiana** [comment]
Hi @pavel-ship-it , 
I can reproduce this issue only with physical device because I need a big amount of images

Thanks !

**Comment by pavel-ship-it** [comment]
Hi @marinofaggiana,
In this case the memory could be arranged for the images - each image will be expanded in to a bitmap in memory and may occupy significant piece if space. 
Could you please check this case?
You could roughly estimate a memory usage by multiplying image's width by height by 4 bytes. Available memory could vary depending on the device model.

**Comment by marinofaggiana** [comment]
Hi @pavel-ship-it , thanks for your answer, no the memory of images are under control (the images are (files) only send via network), but I have found the issue:

replaced: result.freeze() with table.init(value: result) 

So, as I imagined, **the freeze() is totally unreliable**, the table.init(value: result) occupy more memory in my task but is correctly released.

**Comment by pavel-ship-it** [comment]
Thank you for getting back with it.
freeze() needs a space to create a copy of required data. If youк device haven't enough space it will cause a crash. Could you please check it?

**Comment by marinofaggiana** [comment]
Hi, my phone has over 9 GB free ... I don't think that's the cause

**Comment by leemaguire** [comment]
@marinofaggiana It would be great if you could get a sample app to us that reproduces this issue. Also make sure you are not keeping a Realm instance alive when it is not needed as that will also take up memory. Version 5.4.6 is out now I would recommend updating too.

**Comment by ericjordanmossman** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
