### ISSUE TITLE
Confining Realm to serial background queue: Exception on iOS 9 / iPhone 4s

### ISSUE THREAD

**Issue by goa** [realm/realm-cocoa#6735]
## Goals
Initialize a Realm confined to a serial background queue via `Realm(queue:)` on iOS 9 and iPhone 4s.

## Expected Results
Realm should have been initialized properly (it was on newer devices).

## Actual Results
The following error is thrown:
`Error Domain=io.realm Code=1 "Invalid queue 'serial-background' (OS_dispatch_queue): Realms can only be confined to serial queues or the main queue." UserInfo={Error Code=1, NSLocalizedDescription=Invalid queue 'serial-background' (OS_dispatch_queue): Realms can only be confined to serial queues or the main queue.}`

## Steps for others to Reproduce
Please use the Code Sample below, on an iPhone 4s device using the latest iOS 9 version.

## Code Sample
``` 
let queue = DispatchQueue(label: "serial-background")
do {
	let realm = try Realm(queue: queue)
	print(realm)
} catch {
	print(error)
}
```

## Version of Realm and Tooling

Realm framework version: 5.3.6

Xcode version: 11.7

iOS/OSX version: 9.3.6

Dependency manager + version: Cocoapods 1.9.3

**Comment by pavel-ship-it** [comment]
Hi @goa,
Queue-confined Realm instances can be obtained when not on that queue, but attempting to do anything with that instance without first dispatching to the queue will throw an incorrect thread exception.

In this case it means you have to wrap the call:
```
let queue = DispatchQueue(label: "serial-background")
queue.sync {
    do {
        let realm = try Realm(queue: queue)
        print(realm)
    } catch {
        print(error)
    }
}
```
Please let us know if it helps or not.

**Comment by goa** [comment]
Hey @pavel-ship-it ! Thanks for your help.

Unfortunately I get the exact same result with your code, copy pasted from here to an empty app's `application(_:didFinishLaunchingWithOptions:)` AppDelegate method.

Again, it works properly on newer devices.

**Comment by tgoyne** [comment]
There's no public API for checking the type of a queue, so we're checking it based on an implementation detail that appears to have been added in iOS 12. One fix might be to just not do the check on older versions of iOS, as presumably no one will ever test their app *exclusively* devices running old versions of iOS.
