### ISSUE TITLE
error exchanging access code with OAuth2 provider (Google login, RealmSwift iOS SDK)

### ISSUE THREAD

**Issue by FaultyJuggler** [realm/realm-cocoa#6738]
!!! MANDATORY TO FILL OUT !!!

## Goals
Use Google Sign In instead of email/password for users

## Expected Results
After running google sign in, user should be logged into Realm and presented with tableview

## Actual Results
Login Failed: error exchanging access code with OAuth2 provider', code: 47

## Steps for others to Reproduce
Setup googlesignin in your iOS app
Have fully working Realm integration that works with email/password
Switch FROM:
app.login(withCredential: AppCredentials(username: username!, password: password!)) { [weak self](user, error) in
TO:
app.login(withCredential: AppCredentials.init(googleToken: gToken!)) { [weak self](user, error) in

See error when calling login with google token instead of username/password combo for new user

Likely related to https://github.com/realm/realm-js/issues/3116

## Code Sample
N/A

## Version of Realm and Tooling
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G73

/Applications/Xcode.app/Contents/Developer
Xcode 11.7
Build version 11E801a

/usr/local/bin/pod
1.9.3
Realm (10.0.0-beta.2)
RealmSwift (10.0.0-beta.2)
RealmSwift (= 10.0.0-beta.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

carthage not found
(not in use here)

/usr/bin/git
git version 2.24.3 (Apple Git-128)

Realm framework version: 10.0.0-beta.2

Realm Object Server version: 10.0.0-beta.2 ? (not sure)

Xcode version: 11.7

iOS/OSX version: testing iOS 13. on MAC 10.15.6

Dependency manager + version: N/A?

**Comment by jsflax** [comment]
Please update to `10.0.0-beta.4`. If that does not work still, please consult the examples for how to setup Google auth.

**Comment by FaultyJuggler** [comment]
@jsflax  I was trying to upgrade to beta4 but then it won't compile because it complains about

`let app = RealmApp(id: Constants.REALM_APP_ID)`
Use of unresolved identifier 'RealmApp'

and
`app.login(withCredential: AppCredentials.init(googleToken: gToken!))`
Use of unresolved identifier 'AppCredentials'

And will not compile

**Comment by ianpward** [comment]
@FaultyJuggler Try `App` instead of `RealmApp`

**Comment by FaultyJuggler** [comment]
@ianpward thanks, I went through and updated about 10 lines that needed changing from beta2 to beta4, but still when I run I get

"error exchanging access code with OAuth2 provider" UserInfo={NSLocalizedDescription=error exchanging access code with OAuth2 provider, realm::app::ServiceError=AuthError}

**Comment by pavel-ship-it** [comment]
Hi @FaultyJuggler ,
Could you please try the workaround described in [realm-js/issues/3116](https://github.com/realm/realm-js/issues/3116#issuecomment-699986432)
> The API documentation has been confusing: you should use the auth code (and not token) as parameter. We have updated it in #3267 and it will be included in the next release.

**Comment by ericjordanmossman** [comment]
@FaultyJuggler 
Could you please try our [release candidate](https://github.com/realm/realm-cocoa/releases/tag/v10.0.0-rc.1)? We've changed the `Credentials` to [an enum](https://github.com/realm/realm-cocoa/blob/v10.0.0-rc.1/RealmSwift/App.swift#L84), which is more explicit about what you need to pass in. You can create credentials with:
```
let credentials = Credentials.google(serverAuthCode: "serverAuthCode")
```
where the serverAuthCode is retrieved from the Google sdk [with these instructions](https://developers.google.com/identity/sign-in/ios/offline-access#enable_server-side_api_access_for_your_app).
Let me know if this sorts out the error. If not, please post the full stack trace and we can keep working on this.

**Comment by ericjordanmossman** [comment]
Closing because inactivity - If you're still having issues please comment and we can re-open if needed.

**Comment by FaultyJuggler** [comment]
@ericjordanmossman 

Finally got updated to Realm 10 official, made all the changes to switch over to using Google Sign in rather than email password, now:

`Login failed: Error Domain=realm::app::ServiceError Code=47 "error exchanging access code with OAuth2 provider" UserInfo={NSLocalizedDescription=error exchanging access code with OAuth2 provider, realm::app::ServiceError=AuthError}`

The sign in is working fine on google's end, and I am getting a valid serverAuthCode, but when I pass it in, no go

**Comment by FaultyJuggler** [comment]
@ericjordanmossman for clarity when setting up google oauth info within the Realm UI on the mongodb website, should the cliendID and secret be the same as what's set in the iOS app?  Or should it be different?  Currently I generated a clientID and secret for each separately.

**Comment by anton-plebanovich** [comment]
I had to use `OpenID Connect` instead. Was getting `error exchanging access code with OAuth2 provider` error when tried to use `Credentials.google(serverAuthCode:)`

**Comment by ericjordanmossman** [comment]
@anton-plebanovich Could you explain more?

**Comment by anton-plebanovich** [comment]
Hi @ericjordanmossman not sure what to explain I tried to follow the guide of how to use Google Auth and ended up getting `error exchanging access code with OAuth2 provider` in the end. I'm also using accounts linking before the first login but not sure if it's the reason. The strange thing though it that accounts are linked but login fails afterward.
