### ISSUE TITLE
Crashing when creating partial realms on write_subscription

### ISSUE THREAD

**Issue by juanjo72** [realm/realm-cocoa#6739]
## Goals
App not crashing when opening partial realms

## Expected Results
Opening partial realms successfuly

## Actual Results
Crashed: Thread
0  libsystem_kernel.dylib         0x1ad062d88 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1acf7b1e8 pthread_kill$VARIANT$mp + 136
2  libsystem_c.dylib              0x1acece934 abort + 100
3  Realm                          0x104fe7a34 realm::util::terminate(char const*, char const*, long) + 10
4  Realm                          0x104fe7d40 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 780
5  Realm                          0x104fe7eb8 realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 328
6  Realm                          0x104fb3280 realm::Table::allocate_object_id_squeezed() + 394
7  Realm                          0x104ce0de0 realm::partial_sync::(anonymous namespace)::write_subscription(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, realm::util::Optional<long long>, bool, realm::Group&) + 387 (partial_sync.cpp:387)
8  Realm                          0x104ce3ad0 std::__1::__function::__func<realm::partial_sync::(anonymous namespace)::enqueue_registration(realm::Realm&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::util::Optional<long long>, bool, std::__1::function<void (std::exception_ptr)>)::$_8, std::__1::allocator<realm::partial_sync::(anonymous namespace)::enqueue_registration(realm::Realm&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::util::Optional<long long>, bool, std::__1::function<void (std::exception_ptr)>)::$_8>, void ()>::operator()() + 423 (partial_sync.cpp:423)
9  Realm                          0x104de6374 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::partial_sync::WorkQueue::create_thread()::$_0> >(void*) + 1396 (iterator:1396)
10 libsystem_pthread.dylib        0x1acf83d98 _pthread_start + 156
11 libsystem_pthread.dylib        0x1acf8774c thread_start + 8

## Steps for others to Reproduce
Very difficult to reproduce. Only some clients are affected

## Code Sample
It happens when a subscription is going to be created:
let subscription = checkInsInThisEvent.subscribe(named: name, update: true, timeToLive: .timeToLive)

## Version of Realm and Tooling
Realm framework version: 5.3.6

Realm Object Server version: 3.28.2

Xcode version: 11.7

iOS/OSX version: 13.6.1

Dependency manager + version: Cocoapods 1.9.3

**Comment by pavel-ship-it** [comment]
Hi @juanjo72 ,
This version of Realm Cloud is now referred to as legacy Realm Cloud. It is recommended that for sync, you upgrade to v10.

**Comment by juanjo72** [comment]
Hi, Pavel,
I have see this version is a beta one and I am afraid I am using RxRealm 3.1, released last July which is incompatible with v10.
What you mention as Realm Cloud I am assuming you are referring to the RealmSwift sdk.

**Comment by bmunkholm** [comment]
@juanjo72 I believe what Pavel refers to is that "Realm Object Server" is now legacy, and we encourage to upgrade to MongoDB Realm (which is the successor). It's out of beta now, so I would suggest upgrading if you can.
