### ISSUE TITLE
App won't finish launching on simulator when the realm file is open in realm studio

### ISSUE THREAD

**Issue by mkoorn** [realm/realm-cocoa#6743]
Since I upgraded to RealmSwift Cocoapod v5.3.6 the app hangs when I run it on the simulator while the realm file is open in RealmStudio.

Before I was able to relaunch the app while the file was open. I now have to close it every time I relaunch the app and then open the realm file again.

It was great being able to keep the realm file open while relaunching the app.

I am hoping this can be re-enabled.

Realm-cocoa 5.3.6
Realm Studio 3.11.0.719
Xcode 11.7

**Comment by pavel-ship-it** [comment]
Hi @mkoorn ,

This issue will be fixed in the new release of Realm Studio.

I'll close this ticket. If the you still see the same issue in a new version please comment and we can re-open it.
