### ISSUE TITLE
如何使用 Swift Package Manager 来集成 realm ？

### ISSUE THREAD

**Issue by luocunshun** [realm/realm-cocoa#6747]
想要使用  Swift Package Manager 来集成 realm， 但发现好像没有这种集成方式。
我也试过，但没有成功。希望更新这种集成方式。谢谢。

**Comment by pavel-ship-it** [comment]
Hi @luocunshun ,
You can import the package using Swift Package Manager from repository at https://github.com/realm/realm-cocoa
