### ISSUE TITLE
Multiply user logout issue

### ISSUE THREAD

**Issue by jlavyan** [realm/realm-cocoa#6754]
## Bug

**instead of user logout called current user logout see images below**. 

![Screen Shot 2020-09-11 at 6 29 47 PM](https://user-images.githubusercontent.com/3755088/92938476-a5dbc200-f45d-11ea-9231-1d598e52984f.png)
![Screen Shot 2020-09-11 at 6 28 03 PM](https://user-images.githubusercontent.com/3755088/92938481-a83e1c00-f45d-11ea-8687-957a86b10b4d.png)
![Screen Shot 2020-09-11 at 6 28 10 PM](https://user-images.githubusercontent.com/3755088/92938487-a8d6b280-f45d-11ea-88c7-56869706954f.png)

## Expected Results

I should be able logout specific user. currently it not working as expected

## Actual Results

when we call logout called current user logout

## Steps for others to Reproduce

login in two user then try to logout

## Version of Realm and Tooling

Realm framework version: v10.0.0-beta.4

**Comment by pavel-ship-it** [comment]
Hi @jlavyan , you could use `switchToUser` method or call `logOut` directly on User object (please notice there are 2 logOut methods for User - with completion (you're using it) and without it).

**Comment by jlavyan** [comment]
Hi @pavel-ship-it  thanks for response

1. I don't think switchToUser best way for logout from specific user
2. Check first image i call logout directly on User, but when i check method functionality looks like it called current user logout instead of user which called logout

**Comment by ericjordanmossman** [comment]
@jlavyan 
Thanks. This is a bug. Should be resolved with #6765 .
