### ISSUE TITLE
Add support for suppressing notifications when using Combine

### ISSUE THREAD

**Issue by tgoyne** [realm/realm-cocoa#6760]
`Realm.write()` takes an array of `NotificationToken`s which will not be notified about the write, which is intended to be used when the UI has been updated prior to writing to the Realm rather than the normal flow of writing to the Realm and then updating the UI from that. It currently isn't possible to use this in conjunction with the Combine publishers as those do not expose the `NotificationToken`

**Comment by traviskaufman** [comment]
I know this would be a very major undertaking, and there's probably an easier way to do (I'm just pretty unfamiliar with Realm's codebase) but I wonder how crazy/possible would it be to extend the concept of Realm's NotificationToken out into a protocol that AnyCancellable could be extended to adopt?

**Comment by tgoyne** [comment]
Sorta unrelated, but now that you mention it `NotificationToken` probably should conform to `Cancellable`.

The notification skipping logic is embedded pretty deeply into the (c++) changeset calculation code so that it can properly handle things like notification coalescing (if you make a series of small writes we deliver a single notification with the changes from all of them rather than one notification per write, but naturally you don't want to coalesce them into a notification that'll get skipped), so it probably isn't generalizable in any interesting way.

**Comment by natemann** [comment]
This was discussed a long time ago with NotificationTokens, but without knowing what this API would look like, it would be very beneficial if the API could simply state do not notify all tokens instead of having to supply explicit tokens.

**Comment by leemaguire** [comment]
Closed via https://github.com/realm/realm-cocoa/pull/6816

**Comment by aehlke** [comment]
Was this meant to exclude writeAsync? Should I open another ticket to add this for writeAsync? I use actors but also need to manage combine publishers...

**Comment by nirinchev** [comment]
No, I don't believe we explicitly wanted to exclude writeAsync, so feel free to create a ticket requesting it.

**Comment by aehlke** [comment]
Thanks - I meant asyncWrite which maybe even came after this PR my mistake. Will file thanks
