### ISSUE TITLE
Unable to Archive RealmSwift with Xcode 12 GM

### ISSUE THREAD

**Issue by tengfoung** [realm/realm-cocoa#6774]
## Goals
Successfully archive RealmSwift

## Expected Results
Able to archive RealmSwift with Xcode 12 GM

## Actual Results
Compilation error:
```
error: “realm.hpp” couldn’t be copied to “include” because an item with the same name already exists. (in target 'Realm' from project 'Realm')
```
<img width="1059" alt="Screenshot 2020-09-17 at 1 45 23 PM" src="https://user-images.githubusercontent.com/4436592/93425178-0b133580-f8ec-11ea-8b8c-8c03c9f4aa0b.png">

## Version of Realm and Tooling

Realm framework version: 5.4.0

Xcode version: Xcode 12 GM

iOS/OSX version: iOS 14

Dependency manager + version: Carthage 0.35.0

**Comment by Rep2** [comment]
Same issue here

**Comment by tengfoung** [comment]
Looks like pre-built binary is otw (https://github.com/realm/realm-cocoa/pull/6770). Let's wait and see.
