### ISSUE TITLE
RealmSwift报错：Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by zht415** [realm/realm-cocoa#6776]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by ericjordanmossman** [comment]
I'm closing because the template is not filled out. If this is unintentional, please re-open a new ticket instead of editing the original post.
