### ISSUE TITLE
v5.4.2 cannot be carthage update

### ISSUE THREAD

**Issue by myammm** [realm/realm-cocoa#6784]
## Goals
Successful carthage update.

## Actual Results
xcodebuild log ↓
/Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/src/object_changeset.hpp:24:10: fatal error: 'realm/keys.hpp' file not found

## Steps for others to Reproduce
I tried to update by the following method.
$ ./carthage-build.sh update --no-use-binaries --platform iOS realm-cocoa
(https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506)

## Version of Realm and Tooling
Realm framework version: v5.4.2
Xcode version: Xcode 12 GM

**Comment by bguidolim** [comment]
@myammm please try using this: https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5

It was mentioned some comments below: https://github.com/Carthage/Carthage/issues/3019#issuecomment-694329329

**Comment by bguidolim** [comment]
Ah, it's not about the script, same error here.

**Comment by bguidolim** [comment]
Could it be related to https://github.com/realm/realm-cocoa/issues/6774 ?

**Comment by tgoyne** [comment]
Duplicate of https://github.com/realm/realm-cocoa/issues/6717.

If using the prebuilt library is acceptable and you don't specifically need to build from source, you can simply remove `--no-use-binaries`.

**Comment by myammm** [comment]
@bguidolim @tgoyne 
I tried the script and it worked.
Thank you!
