### ISSUE TITLE
XCode 12 compilations issue for Undefined symbol RLMNotificationToken, RLMRealmPathForFile, RLMObjectBase, RLMSchema

### ISSUE THREAD

**Issue by amittiwaribit** [realm/realm-cocoa#6804]
Getting a compilation issue for the multiple classes (Undefined symbol RLMNotificationToken, RLMRealmPathForFile, RLMObjectBase, RLMSchema), when 2 classes defined in the single files. 
Currently using realm version **5.4.2**

For Example, RLMRealm.h file, in this file two classes defined RLMNotificationToken and RLMRealm. Hence Xcode 12 now giving error Undefined symbol RLMNotificationToken.

Please get the screenshot attached.
<img width="390" alt="Compiler issue Xcode12" src="https://user-images.githubusercontent.com/5095009/94151561-2e178980-fe98-11ea-8e3f-892ae6815d78.png">

**Comment by jsflax** [comment]
@amittiwaribit How are you including Realm in your project?

**Comment by amittiwaribit** [comment]
Hi @jsflax,
Thank you for the quick response. I am adding realm on pod file as **pod 'RealmSwift', '5.4.3'**. we are adding a realm in our custom SDK.

Thanks
Amit Tiwari

**Comment by nomanyousuf** [comment]
I am getting the same error in Xcode 12 please review the screenshot.
<img width="1444" alt="Screen Shot 2020-09-24 at 7 23 47 AM" src="https://user-images.githubusercontent.com/56045092/94158190-f298a300-fe36-11ea-940e-110e8ec894cb.png">

Thanks

**Comment by amittiwaribit** [comment]
SDK building cause the following compilation issue attached.
<img width="817" alt="Screenshot 2020-09-24 at 9 35 50 PM" src="https://user-images.githubusercontent.com/5095009/94170705-029f9980-feae-11ea-9281-d5ce22666695.png">

**Comment by tgoyne** [comment]
Those are all errors in your code.

**Comment by amittiwaribit** [comment]
it's ok, now but still we are facing Undefined symbol RLMNotificationToken, RLMRealmPathForFile, RLMObjectBase, RLMSchema.

**Comment by mentrena** [comment]
Do you have
```
post_install do |installer|
     installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                 config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
           end
     end
 end
```

in your Podfile?

**Comment by amittiwaribit** [comment]
Yes, we did as well. Now what we found is that, when we do pod install via pod version 1.9.3 that compilation error appears, but when do pod install via pod version 1.8.3, then these compilation errors disappear and the realm works fine.
So need confirmation from the realm team, that is it related to the pod version issue.

**Comment by Limoo** [comment]
Can confirm downgrading to 1.8.3 worked for me. Before I tried everything with 1.9.3: Deleted derived data, deintegrated Pods, cleared Cocoapods cache and still had this error. The issue appeared when I builded for arm64 and not for the simulator

**Comment by amittiwaribit** [comment]
yes, It's working after downgrading to 1.8.3, after that its works in both device and simulator as well, also for arm64.

**Comment by leemaguire** [comment]
This is no longer an issue in v10.1.1

**Comment by amittiwaribit** [comment]
Hi @leemaguire, are talking about the cocoa pod version 10.1.1?

**Comment by leemaguire** [comment]
@amittiwaribit Use Realm Cocoa v10.1.1 and Cocoapods version 1.10

**Comment by amittiwaribit** [comment]
Hi @leemaguire, I have verified again that the issue still exists in Realm Cocoa v10.1.1 and Cocoapods version 1.10.
[
<img width="1444" alt="error" src="https://user-images.githubusercontent.com/5095009/98906979-10ec5800-24e4-11eb-86f0-2e6141989578.png">
](url)

**Comment by sirnacnud** [comment]
Updating to Xcode 12.3 fixed the issue for me.
