### ISSUE TITLE
Carthage / CocoaPods update fails at cloning Catch2 submodule

### ISSUE THREAD

**Issue by AndreVasilev** [realm/realm-cocoa#6807]
After updating to Xcode 12 I had to update Carthage dependencies. But updating realm-cocoa (both v5.0.2 and v5.4.3) fails at cloning Catch2 submodule
(seems to be similar to https://github.com/realm/realm-cocoa/issues/6317)

## Expected Results
Carthage update successful

## Actual Results
```
*** Checking out realm-cocoa at "v5.4.3"
A shell task (/usr/bin/env git submodule --quiet update --init --recursive (launched in /Users/andrey/Documents/Xcode/Altatec/Sberdisk/Carthage/Checkouts/realm-cocoa/Realm/ObjectStore)) failed with exit code 1:
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/Users/andrey/Documents/Xcode/Altatec/Sberdisk/Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/external/catch' failed
Failed to clone 'external/catch'. Retry scheduled
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/Users/andrey/Documents/Xcode/Altatec/Sberdisk/Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/external/catch' failed
Failed to clone 'external/catch' a second time, aborting
```

## Steps for others to Reproduce
`carthage update realm-cocoa --platform iOS --cache-builds --no-use-binaries`

## Version of Realm and Tooling

Realm framework version: 5.4.3 (and 5.0.2)
Xcode version: 12.0
Dependency manager + version: Carthage 0.36.0 / CocoaPods 1.9.0
MacOS: 10.15.6
Git: 2.24.3 (Apple Git-128)

**Comment by rhys-rantmedia** [comment]
Also having this issue!

**Comment by Jilocasin** [comment]
Going explicitly for v.5.4.2 didn't do the trick for me sadly.

**Comment by AndreVasilev** [comment]
CocoaPods 1.9.0 fails with the same error

**Comment by rhys-rantmedia** [comment]
> Going explicitly for "v5.4.2" didn't do the trick for me sadly.

Ah, my mistake... Resetting Xcode caches, cleaning the project, resetting some more, etc. a few times finally got it to stop building for me too, on v5.4.2 as well. Same problem.

**Comment by crousselle2** [comment]
Having the same issue with checking out an older version of Realm via SPM. 
A Swift Package with Realm 3.21.0 as a dependency.

`
Showing Recent Messages
Submodule path 'Realm/ObjectStore': checked out '8416010e4be5e32ba552ff3fb29e500f3102d3db'
Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
Cloning into '/Users/xxxx/Library/Developer/Xcode/DerivedData/Cue/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore'...
Submodule 'external/catch' (https://github.com/catchorg/Catch2) registered for path 'Realm/ObjectStore/external/catch'
Cloning into '/Users/xxx/Library/Developer/Xcode/DerivedData/Cue/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/external/catch'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining

fatal: the remote end hung up unexpectedly
`

**Comment by AndreiGalkin** [comment]
Got similar issue runnning `pod install`
```
[!] Error installing Realm
[!] /usr/bin/git -C /var/folders/fh/7s50ns0x77bd6g6bn1p44_cnt0z4m2/T/d20200925-5700-9skxip submodule update --init --recursive

Submodule path 'Realm/ObjectStore': checked out 'f59cb85414b22722660ad06186357ecfa01bc64f'
Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
Cloning into '/private/var/folders/fh/7s50ns0x77bd6g6bn1p44_cnt0z4m2/T/d20200925-5700-9skxip/Realm/ObjectStore'...
Submodule 'external/catch' (https://github.com/catchorg/Catch2) registered for path 'Realm/ObjectStore/external/catch'
Cloning into '/private/var/folders/fh/7s50ns0x77bd6g6bn1p44_cnt0z4m2/T/d20200925-5700-9skxip/Realm/ObjectStore/external/catch'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/private/var/folders/fh/7s50ns0x77bd6g6bn1p44_cnt0z4m2/T/d20200925-5700-9skxip/Realm/ObjectStore/external/catch' failed
Failed to clone 'external/catch'. Retry scheduled
Cloning into '/private/var/folders/fh/7s50ns0x77bd6g6bn1p44_cnt0z4m2/T/d20200925-5700-9skxip/Realm/ObjectStore/external/catch'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/private/var/folders/fh/7s50ns0x77bd6g6bn1p44_cnt0z4m2/T/d20200925-5700-9skxip/Realm/ObjectStore/external/catch' failed
Failed to clone 'external/catch' a second time, aborting
Failed to recurse into submodule path 'Realm/ObjectStore'
```

Tried different versions of realm, clearing cache and updating cocoapods with fresh Xcode 12. 
And nothing..

**Comment by crousselle2** [comment]
https://github.com/realm/realm-cocoa/issues/6806 provides a decent temporary solution that unblocked our project.

**Comment by AndreiGalkin** [comment]
Thanks @crousselle2 it helped me as well!

**Comment by rhys-rantmedia** [comment]
Also works for me! Thanks @crousselle2. Here's hoping it's a relatively simple fix...

**Comment by leemaguire** [comment]
Closing as this is a Github issue and not related to Realm.
