### ISSUE TITLE
Locking the thread inside a observe causes all Realm instances to hang

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-cocoa#6808]
## Goals

- Be able to use the `observe` without locking other Realm instances.

I notice this happening in our application when the dataset was bigger than 1000 items, the application started getting slow and hanging for 1.5 seconds when interacting with the `objects` of the example below.

I was thinking about dispatching this workload to another thread, but this is not allowed since it's not easily possible to transfer live objects between threads.

## Expected Results

When doing a heavy work inside the closure from the `observe` function, other Realm instances should not hang.

## Actual Results

All Realm instances get stuck while doing a locking process inside the observer.

## Code Sample

Given the code below in a part of the project:

```swift
notificationToken = objects?.observe { (changes: RealmCollectionChange) in
      Thread.sleep(forTimeInterval: 5.0) //Simulates a heavy work with objects
}
```

By doing the code above the application gets very slow, but only because the realm instances are hanging, even work that is being done outside the main thread gets stuck.

If you call this very shortly after:

```swift
let realm = try! Realm()
realm.refresh() //hangs for 5 seconds
```

## Version of Realm and Tooling

Realm framework version: 5.4.3 and older

Realm Object Server version: nil

Xcode version: 11.7

iOS/OSX version: All

Dependency manager + version: Submodules

**Comment by leemaguire** [comment]
Hi @ppamorim Observing on a user defined should solve your issue. This thread would be solely used for observing and performing your processing tasks.


```
On main thread
try! self.realm.write {
                let dog = Dog()
                dog.name = "Jim"
                self.realm.add(dog)
            }
```

```
On your defined queue
self.notificationToken = self.realm.objects(Dog.self).observe(on: self.myQueue) { (change: RealmCollectionChange<Results<Dog>>) in
                Thread.sleep(forTimeInterval: 5.0)
            }
```

**Comment by ppamorim** [comment]
@leemaguire That's far from ideal.

**Comment by tgoyne** [comment]
By default change notifications are delivered on the thread which you called `observe()` on. Sleeping for five second (or doing an equivalent amount of work) within the notification callback with then naturally occupy that thread for that amount of time. There's no reason why this should block other threads, though. We don't hold any locks while calling the notification callback and the notification system is specifically designed to support different threads picking up notifications at different rates (or even a thread with observers hanging forever inside a callback).

**Comment by ppamorim** [comment]
"There's no reason why this should block other threads," this enter in conflict with the fact that realm objects are not thread-safe and I cannot use the very same query. If there is a collection of items stored in the main thread it's not possible to attach an observer and listen to it without locking other realm instances. It's what I am experiencing.

It's not really blocking other threads, but it's the functions `refresh` and `write` keeping locked until the notification block completes. I am not sure exactly what is happening.

My solution was to isolate the required data, transform to swift objects and process the data in another thread.

**Comment by leemaguire** [comment]
Closing this issue as it has been inactive for some time now. If you have any other questions please open a new issue.
