### ISSUE TITLE
Migrating from Realm 2.10.2 (Yeah... not a typo!)

### ISSUE THREAD

**Issue by GalCohen** [realm/realm-cocoa#6809]
I have a medium sized iOS app with mixed objc/swift codebase that has neglected maintenance over the years. The app is on version 2.10.2 and I'd like to know what my options are for upgrading. I know this is a bit of a crazy request given that the latest version is... 5.4?  

I just want to know if it's worth it, and if so, how would you go about it?  
- follow the changelogs over the years? :-/ 
- Do I migrate from v2 to v3 to v4? Jump to 5? 
- How would the data stored on device handle it?
 - Are there tools to help me here?

## Goals
Possibly update Realm to the latest stable version.

## Expected Results
As least work and bugs as possible? Haha. This might be more of a research / discover type of question where in the end I decide it's not worth tackling yet. 

## Actual Results
Nothing yet.

## Steps for others to Reproduce
ummm download v2, put some data in... try to migrate up? Actually, I maybe I should try that on a toy app.

## Version of Realm and Tooling

Realm framework version: ?
2.10.2

Realm Object Server version: ?

Xcode version: ?
12 

iOS/OSX version: ?
14

Dependency manager + version: ?
cocoapods 1.9.3 (bonus if I could switch to swift package manager!)

**Comment by tgoyne** [comment]
Opening non-sync Realms written by 2.10 shouldn't be an issue. We dropped support for reading pre-1.0 Realms in 5.0, but the only file format changes in 2.0-4.x were strictly sync related.

I'd probably start with just trying to build your app with the latest version of Realm and see what breaks. The main awkwardness will probably be that we've removed some of the older fixits and rename helpers, so renames done in 3.0 won't have an easy helper in Xcode for them. The [3.0.0](https://github.com/realm/realm-cocoa/releases/tag/v3.0.0), [4.0.0](https://github.com/realm/realm-cocoa/releases/tag/v4.0.0) and [5.0.0](https://github.com/realm/realm-cocoa/releases/tag/v5.0.0) release notes are the important ones to look at as we've had a few changes in functionality that don't result in compilation errors.

**Comment by ZComwiz** [comment]
Gal. Do not update past 3.x series. Nothing in 5.x is stable.

**Comment by geragray** [comment]
@ZComwiz I am sorry got hit by Core6 data migration issue that we could not catch in time on our end. I believe it was resolved here https://github.com/realm/realm-cocoa/issues/6699. If you still see major issues with the lastest Cocoa SDK, it would be much more productive to open a separate issue with repro case. As much as we try, we will never be able to test all corner cases and desperately need your help to discover them.

**Comment by GalCohen** [comment]
Thanks! Will keep this all in mind... just trying to find the right time and place to do this now. I'll open up with specific issues as I come across them.
