### ISSUE TITLE
xcode12 cocoapod pod lib lint error:	Ld /Users/xxxx/Library/Developer/Xcode/DerivedData/App-brhsnyjzdntvcufqhukpqdhzdqzh/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Realm.build/Objects-normal/arm64/Binary/Realm normal arm64

### ISSUE THREAD

**Issue by initGalen** [realm/realm-cocoa#6811]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?
4.4.0
Realm Object Server version: ?

Xcode version: ?
Xcode 12
iOS/OSX version: ?

Dependency manager + version: ?

**Comment by ericjordanmossman** [comment]
Please see: #6785
