### ISSUE TITLE
Minimum deployment target is 11 when installing through SPM.

### ISSUE THREAD

**Issue by emisvx** [realm/realm-cocoa#6818]
## Goals
Install Realm through SPM on a project targeting iOS 10

## Expected Results
Realm would be installed and building properly.

## Actual Results
`compiling for iOS 10.0, but module 'RealmSwift' has a minimum deployment target of iOS 11.0`
The Package.Swift on the repository specified iOS 11 as the minimum deployment version while the documentation (https://realm.io/docs/swift/latest/) states that for SPM installation, iOS 10 or higher is required.

## Version of Realm and Tooling

Realm framework version: 5.4.5

Xcode version: 12

iOS/OSX version: 10

**Comment by leemaguire** [comment]
This was a documentation mistake. The minimum required version is iOS 11 when SPM is used as the package manager.
