### ISSUE TITLE
Carthage build errors with xcode 12.2

### ISSUE THREAD

**Issue by pitoneux** [realm/realm-cocoa#6822]
I'm using Realm and Realm swift as framework in our application. Executing carthage build with error:

ERROR | [iOS] xcodebuild: error: module 'RealmSwift' was created for incompatible target arm64-apple-ios9.0: Frameworks/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule

## Goals
Carthage build should build RealmSwift  fine.

## Version of Realm and Tooling

Realm framework version: ?
both release v4.4.1 and v5.4.6
Realm Object Server version: ?

Xcode version: ?
xcode 12.2 beta 2
iOS/OSX version: ?
10.15.6
Dependency manager + version: ?
carthage version 0.36

**Comment by leemaguire** [comment]
Hi @pitoneux What command are you using for building with Carthage? Do any of the suggestions mentioned in https://github.com/realm/realm-cocoa/issues/6717#issuecomment-695126669 help?

**Comment by pitoneux** [comment]
We were already using --no-use-binaries. I got it to work by using the script that wrap around carthage mentioned in [carthage forum](https://github.com/Carthage/Carthage/issues/3019#issuecomment-699143260) and using "bootstrap --platform ios --cache-builds --no-use-binaries"
