### ISSUE TITLE
5.4.7 crash on launch with EXC_BAD_ACCESS in Realm.Configuration()

### ISSUE THREAD

**Issue by hyouuu** [realm/realm-cocoa#6823]
## Goals
Use Realm normally

## Expected Results
App can launch normally without crashing

## Actual Results
App crash immediately on launch with EXC_BAD_ACCESS in Realm.Configuration()

## Steps for others to Reproduce
Upgrade to 5.4.7 (Tried with CocoaPod and Dynamic framework installation; SPM installation fails which is also a weird issue for 5.4.7)

## Code Sample
 let config = Realm.Configuration(schemaVersion: 12)

## Version of Realm and Tooling
Realm framework version: 5.4.7

Realm Object Server version: NA

Xcode version: 12.0.1

iOS/OSX version: 14.0

Dependency manager + version: Tried both CocoaPod 1.10.0 rc1 & Dynamic framework installation; SPM failed to install latest Realm (which was what I was using before 5.4.4)

Some context: I was trying to upgrade to 5.4.7 because saw it fixes https://github.com/realm/realm-dotnet/issues/2025 - I don't use .NET but on iOS when accessing a filtered `Results` count property e.g. `searchResults.count` it would crash sometimes with Crashlytics reporting "Key not found", so I think it's probably from the same cause (please let me know if it's not). I'm seeing lots of crashes from that issue so please help fix this issue asap. Thanks!

**Comment by leemaguire** [comment]
@hyouuu Could you please provide us with a stack trace? If this crash is reproducible, could you boil it down into a small reproduction case? Thanks.

**Comment by hyouuu** [comment]
Actually just tried again and it worked (SPM) - guess the propagation of the new version has some undefined behavior before completing? Feels weird but maybe never mind :/
