### ISSUE TITLE
Carthage will build "Realm iOS static" scheme.

### ISSUE THREAD

**Issue by r-plus** [realm/realm-cocoa#6824]
## Goals
Skip "Realm iOS static" scheme when build by carthage with `--no-use-binaries` option if this is not expected behavior.

## Expected Results
Only build "Realm" and "RealmSwift" scheme.

## Actual Results
additionally building "Realm iOS static" scheme.

## Steps for others to Reproduce

v5.3 no need building "Realm iOS static"

```
$ carthage update --platform iOS --no-use-binaries
Please update to the latest Carthage version: 0.36.0. You currently are on 0.35.0
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v5.3.0"
*** xcodebuild output can be found in /var/folders/y8/jt2b97z12lg4xms5_pgcdcr40000gn/T/carthage-xcodebuild.A6awb9.log
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
```

v5.4 building "Realm iOS static"

```
$ carthage update --platform iOS --no-use-binaries
Please update to the latest Carthage version: 0.36.0. You currently are on 0.35.0
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v5.4.0"
*** xcodebuild output can be found in /var/folders/y8/jt2b97z12lg4xms5_pgcdcr40000gn/T/carthage-xcodebuild.JTHZ02.log
*** Building scheme "Realm iOS static" in Realm.xcworkspace
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
```

## Code Sample
n/a

## Version of Realm and Tooling
Realm framework version: tested 5.3.0 and 5.4.0
Realm Object Server version: n/a
Xcode version: 11.7
iOS/OSX version: 13.7
Dependency manager + version: Carthage 0.35.0

**Comment by leemaguire** [comment]
@r-plus Can you take a look at v5.4.3+, we introduced some changes to help with Carthage installation issues.

**Comment by r-plus** [comment]
@leemaguire Hi, thanks for your response.
But v5.4.3 also building "Realm iOS static" scheme.

```
$ carthage update --platform iOS --no-use-binaries
Please update to the latest Carthage version: 0.36.0. You currently are on 0.35.0
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v5.4.3"
*** xcodebuild output can be found in /var/folders/y8/jt2b97z12lg4xms5_pgcdcr40000gn/T/carthage-xcodebuild.mAMsD7.log
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "Realm iOS static" in Realm.xcworkspace
^C
```

**Comment by r-plus** [comment]
and latest stable version v5.4.7 too.

```
$ carthage update --platform iOS --no-use-binaries
Please update to the latest Carthage version: 0.36.0. You currently are on 0.35.0
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v5.4.7"
*** xcodebuild output can be found in /var/folders/y8/jt2b97z12lg4xms5_pgcdcr40000gn/T/carthage-xcodebuild.f3Oc2y.log
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
*** Building scheme "Realm iOS static" in Realm.xcworkspace
```

**Comment by tgoyne** [comment]
Carthage does not provide us with any way to control which schemes are built.

**Comment by bguidolim** [comment]
I've created a script for me, feel free to copy and adapt for your needs.

https://gist.github.com/bguidolim/46f05bea5e0e9534493010dd444d24f9

**Comment by r-plus** [comment]
Is this expected behavior? If so that’s fine.

**Comment by bguidolim** [comment]
It is, the only thing Carthage allows you to configure is "which plataform", but not the target of that platform.

**Comment by leemaguire** [comment]
Closing as we cannot control which schemes are built by Carthage.
