### ISSUE TITLE
Crash when upgrading from Realm 5.4.6 to Realm 10.0.0-rc1

### ISSUE THREAD

**Issue by sipersso** [realm/realm-cocoa#6847]
The app currently crashes when upgrading a file from 5.4.6 to 10.0.0-rc1. Judging by the error message it is pretty clear that the latest 10.0.0-rc1 build can't upgrade the file generated by 5.4.6 yet (v11). It would be nice if this was listed in the release notes so I could have waited to attempt to upgrade. 

## Goals
Upgrade to Realm 10.x apis

## Expected Results
Upgrade should succeed

## Actual Results
When opening a local realm file the app crashes with the message "Assertion failed: current_file_format_version >= 5 && current_file_format_version <= 10 with (current_file_format_version) =  [11]"

## Steps for others to Reproduce
1: Create a local realm using Realm 5.4.6
2: Switch to the new 10.0.0-rc1 sdk
3: Open realm file

## Version of Realm and Tooling
Realm framework version: 5.4.6, 10.0.0-rc1

┆Attachments: <a href="https://jira.mongodb.org/secure/attachment/281984/delcrash-914-6847.zip">delcrash-914-6847.zip</a>

**Comment by pavel-ship-it** [comment]
@sipersso ,
I can reproduce this crash. Thank you

**Comment by sipersso** [comment]
Awesome! @pavel-ship-it

**Comment by pavel-ship-it** [comment]
It's fixed already and will be available in upcoming release.

**Comment by sipersso** [comment]
Thanks @pavel-ship-it! I'll wait for the release then ;)

**Comment by jedelbo** [comment]
FIxed by https://github.com/realm/realm-core/pull/3989
