### ISSUE TITLE
Write transaction is not blocking notifications with valid token in all cases.

### ISSUE THREAD

**Issue by scottcarter** [realm/realm-cocoa#6849]
## Goals
I wish to block any notifications for specific write transactions.

## Expected Results
Notifications are blocked when calling realm.write(withoutNotifying:) with a valid notification token in array argument.

## Actual Results
In a small percentage of cases, a notification is generated.  The code sample writes 2,000 objects sequentially and can see 1 - 3 unexpected notifications in most runs.

An example run produced the following unexpected results in the console.

```
NoteModel: Processing  
 0  deletions =  [] 
 1  insertions =  [49] 
 0  modifications =  []

NoteModel: Processing  
 0  deletions =  [] 
 1  insertions =  [289] 
 0  modifications =  []

```

## Steps for others to Reproduce

Create a NotificationToken and subscribe to notifications.  

Call realm.write(withoutNotifying:) with token in a large loop adding objects and monitor for notifications.

See example in code sample.

## Code Sample

https://github.com/scottcarter/RealmWriteIssue

## Version of Realm and Tooling

```
Realm: 5.4.8
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021

Deployment target: iOS 14.0

Dependency manager:  SPM

/Applications/Xcode.app/Contents/Developer
Xcode 12.0.1
Build version 12A7300

/usr/local/bin/pod
1.9.3
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
(not in use here)

/usr/bin/git
git version 2.24.3 (Apple Git-128)
```

**Comment by tgoyne** [comment]
https://github.com/realm/realm-object-store/pull/1103 will probably fix this once it's included in a release.

**Comment by tgoyne** [comment]
Pointing the test app to realm-cocoa master fixes it, so it looks like it is that bug.
