### ISSUE TITLE
Anonymous Sign In Crash

### ISSUE THREAD

**Issue by visdyn** [realm/realm-cocoa#6854]
##  Goals
Realm should not crash when signing in with Anonymous sign in. The crash is occurring with 10.0.0-beta.6, however I believe it did not crash with beta.4

## Expected Results
See above

## Actual Results
When signing in with anonymous sign in, Realm Crashes

Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

## Steps for others to Reproduce
Use anonymous authentication

## Code Sample
```
MyRealmApp.login(credentials: Credentials.anonymous()) { user, error in
    DispatchQueue.main.sync { //<------- this is the line that crashes
        guard error == nil else {
            print("Login failed: \(error!)")
            return
        }
        print("anon login success")  // Now logged in, do something with user
    }
}
```

## Version of Realm and Tooling
MongoDB Realm
pod 'RealmSwift', '=10.0.0-beta.6'
macOS 10.14 & 10.15
XCode 11.3

**Comment by ericjordanmossman** [comment]
Creating a quick ad-hoc app confirms the same. This occurs when an anonymous user has previously logged in on the device.
<img width="998" alt="Screen Shot 2020-10-13 at 12 11 07 PM" src="https://user-images.githubusercontent.com/25092858/95886924-33f0e400-0d4d-11eb-9564-7e1fcfae36a1.png">

We'll need to look into this more.

**Comment by ericjordanmossman** [comment]
For what it's worth, a check for logging out current users appears to workaround the crash. But I'll still update here once I know more.

**Comment by ericjordanmossman** [comment]
@visdyn 
When logging in an anonymous user we check to see if a logged-in anonymous user exists. If so, we'll pull the existing anonymous user from the syncManager, set that as the current user, then return that user in the callback.

I believe the `DispatchQueue.main.sync` within the callback is causing a deadlock when this happens. If you remove this do you still see the crash?

**Comment by ericjordanmossman** [comment]
@visdyn 
Perfect, thanks. I'm going to close this issue because `.logIn` is behaving as expected. 
The recommendation here is: steer away from using the `main.sync` in completion blocks. It's not guaranteed as legal in most completion handlers. If you need to dispatch something to .main, please use `.async`.

**Comment by visdyn** [comment]
@ericjordanmossman 

If the issue is being closed, you may want to also update the documentation example(s)

https://docs.mongodb.com/realm/ios/authenticate/#anonymous-authentication

**Comment by ericjordanmossman** [comment]
Yes for sure :). They've been notified.
