### ISSUE TITLE
Unable to install Realm in my project with use of Cocoapods

### ISSUE THREAD

**Issue by PareshPatel721** [realm/realm-cocoa#6859]
Below is my Podfile look like

target 'RealmDatbaseDemo' do
  use_frameworks!
    pod 'RealmSwift'
end

When i hit command  Pod Install in terminal
I'm getting below error

pod install
Analyzing dependencies
Downloading dependencies
Installing Realm (5.5.0)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

Downloading dependency: sync 5.0.29 from https://static.realm.io/downloads/sync/realm-sync-cocoa-5.0.29.tar.xz
clang: error: no such file or directory: '11.6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk'
clang: warning: no such sysroot directory: '/Applications/Xcode' [-Wmissing-sysroot]

[!] Automatically assigning platform `iOS` with version `11.0` on target `RealmDatbaseDemo` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Realm Pod is not able to install in my project.
I'm able to run other pods as well.

**Comment by ericjordanmossman** [comment]
@PareshPatel721 
Which Xcode version? 11.6?

> clang: error: no such file or directory: '11.6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk'

Appears unable to find a 13.6 simulator. Checking Xcode -> Preferences -> Components may give more detail. Also please reset your state by removing the `Pods` the file. Then `pod install --repo-update`.

**Comment by PareshPatel721** [comment]
@ericjordanmossman 
Yes it is Xcode 11.6.

**Comment by McKuzmich** [comment]
Well, looks like your path to Xcode 11 contains spaces and this line of code
https://github.com/realm/realm-cocoa/blob/b61081f0d48f57384ef6572eda717524e5baf93e/build.sh#L714
is not taking that into account. Just a pair of quote marks would fix that. Or you could rename Xcode 11 to Xcode11

Had same problem. Fixed by renaming Xcode app

**Comment by PareshPatel721** [comment]
> Well, looks like your path to Xcode 11 contains spaces and this line of code
> 
> https://github.com/realm/realm-cocoa/blob/b61081f0d48f57384ef6572eda717524e5baf93e/build.sh#L714
> 
> 
> is not taking that into account. Just a pair of quote marks would fix that. Or you could rename Xcode 11 to Xcode11
> Had same problem. Fixed by renaming Xcode app

Thanks It works
Now I'm using Xcode 12 and i had not make any space in name, it worked fine.
Thank you so much

**Comment by LucasVanDongen** [comment]
Quotes in the path would be really handy as my hard disk name "Macintosh HD" (default name assigned by macOS) also has a space in it.

**Comment by AkhileshSharma-MindRuby** [comment]
> Well, looks like your path to Xcode 11 contains spaces and this line of code
> 
> https://github.com/realm/realm-cocoa/blob/b61081f0d48f57384ef6572eda717524e5baf93e/build.sh#L714
> 
> 
> is not taking that into account. Just a pair of quote marks would fix that. Or you could rename Xcode 11 to Xcode11
> Had same problem. Fixed by renaming Xcode app

It worked.
