### ISSUE TITLE
Realm Swift mutex lock failed: Invalid argument, Error Code=22

### ISSUE THREAD

**Issue by thomasarogers** [realm/realm-cocoa#6860]
## Goals
Got a react native project and have been using RealmJS in RN without issue. Project now has a need for a native module so imported RealmSwift as a cocoa pods dependency and are trying to create a Realm instance on the native side in a Swift file for storing data in an App Group container to share with an App Extension.

## Expected Results
New Realm is created without error

## Actual Results
When calling the code below:
![image](https://user-images.githubusercontent.com/42372294/95970771-3f551580-0e08-11eb-9127-0a88a2390a46.png)

It fails with the following error:
![image](https://user-images.githubusercontent.com/42372294/95970551-fdc46a80-0e07-11eb-9b95-fca8fed43a19.png)

## Steps for others to Reproduce
Create a RN project, add RealmJS as an npm dependency in the RN project and add RealmSwift as a cocoa pod dependency and add a swift file in the iOS project. Try to create a new Realm in the swift file. 

## Version of Realm and Tooling
Realm framework version: 
RealmJS - 5.0.5
RealmSwift - 5.5.0

Xcode version: 
11.6

iOS/OSX version: 
iOS - 13.6
OS X - 10.15.7

Dependency manager + version: 
react-native-cli: 2.0.1
react-native: 0.61.4

**Comment by thomasarogers** [comment]
***** UPDATE: 
If I remove the npm RealmJS dependency from the React Native part of the project it solves the issue. Looks like by having Realm in npm and RealmSwift in cocoa pods separately for the Swift side there is a thread conflict. 

I guess RealmJS is using Realm-cocoa under the hood same as RealmSwift. I need to use RealmJS on the RN side and I need to use RealmSwift on the swift side, how can I stop this conflict? I am not clear how to call Realm on the swift side without adding it as dependency in cocoa pods.

**Comment by ericjordanmossman** [comment]
I asked the team for more info on this. 
It's impossible to have two Realm libraries in the same app if either is built as a static framework.
If the two libraries are dynamic frameworks then the two copies can function independently of each other. You still _couldn't_ pass objects between them (even if the two realm libraries had the realm-core version). 

> I guess RealmJS is using Realm-cocoa under the hood same as RealmSwift.

RealmJS isn't exactly using Realm-cocoa. But they share the same foundation, which includes some things like file locking. So having two different Realm libraries in the same app will pose problems if they're accessing the same data.

**Comment by thomasarogers** [comment]
Thanks for you response, sorted the issue by reverting both versions to ensure both RealmJS and RealmSwift are using the same RealmCore version, seems to have fixed it
