### ISSUE TITLE
Invalid top array size

### ISSUE THREAD

**Issue by KimiChiu** [realm/realm-cocoa#6871]
## Goals
Get realm instance.

## Expected Results
Return realm instance

## Actual Results
2020/10/16 10:35:48:762  [RealmHelper/getDefaultRealm] [ERROR] Failed to get realm, error = Unable to open a realm at path '/var/mobile/Containers/Data/Application/A4620727-4E79-4490-99E1-89E1CE48A458/Documents/default.realm': Invalid top array size (ref: 43002032, size: 0)
Exception backtrace:
0   Realm                               0x0000000103016c24 _ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 60
1   Realm                               0x0000000103005b28 _ZN5realm5Group18validate_top_arrayERKNS_5ArrayERKNS_9SlabAllocE + 1188
2   Realm                               0x000000010300bb30 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 1136
3   Realm                               0x000000010300ee20 _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 244
4   Realm                               0x00000001030135f8 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 392
5   Realm                               0x0000000102dee1c0 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1044
6   Realm                               0x0000000102ded2fc _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 68
7   Realm                               0x0000000102ded190 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 168
8   Realm                               0x0000000102ec2868 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 120
9   Realm                               0x0000000102e9217c +[RLMRealm realmWithConfiguration:queue:error:] + 956
10  RealmSwift                          0x000000010367e2a8 $s10RealmSwift0A0V5queueACSo012OS_dispatch_C0CSg_tKcfC + 104
11  pitt                                0x00000001007ad1d0 pitt + 2806224
12  pitt                                0x00000001007ad62c pitt + 2807340
13  pitt                                0x00000001007a45bc pitt + 2770364
14  UIKitCore                           0x0000000183c58a68 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12032616
15  UIKitCore                           0x0000000183c5aac4 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12040900
16  UIKitCore                           0x0000000183c60478 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12063864
17  UIKitCore                           0x00000001832f1d70 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2174320
18  UIKitCore                           0x000000018383d4d4 _UIScenePerformActionsWithLifecycleActionMask + 112
19  UIKitCore                           0x00000001832f28c0 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2177216
20  UIKitCore                           0x00000001832f238c 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2175884
21  UIKitCore                           0x00000001832f26d0 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2176720
22  UIKitCore                           0x00000001832f1f48 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2174792
23  UIKitCore                           0x00000001832fa078 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2207864
24  UIKitCore                           0x000000018374fc28 47154C6D-47DF-3ABB-A152-56B159B014E4 + 6753320
25  UIKitCore                           0x0000000183855810 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 272
26  UIKitCore                           0x00000001832f9df0 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2207216
27  UIKitCore                           0x000000018312eeb0 47154C6D-47DF-3ABB-A152-56B159B014E4 + 327344
28  UIKitCore                           0x000000018312d86c 47154C6D-47DF-3ABB-A152-56B159B014E4 + 321644
29  UIKitCore                           0x000000018312ead8 47154C6D-47DF-3ABB-A152-56B159B014E4 + 326360
30  UIKitCore                           0x0000000183c5e668 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12056168
31  UIKitCore                           0x0000000183778274 47154C6D-47DF-3ABB-A152-56B159B014E4 + 6918772
32  FrontBoardServices                  0x00000001902f42dc A1960BD9-CE29-3E96-817D-955EBEB140BE + 37596
33  FrontBoardServices                  0x000000019031ea00 A1960BD9-CE29-3E96-817D-955EBEB140BE + 211456
34  FrontBoardServices                  0x0000000190302d24 A1960BD9-CE29-3E96-817D-955EBEB140BE + 97572
35  FrontBoardServices                  0x000000019031e6d0 A1960BD9-CE29-3E96-817D-955EBEB140BE + 210640
36  libdispatch.dylib                   0x0000000180f40ac8 8E662F82-B1E4-3E7E-A376-18E9755A8F51 + 15048
37  libdispatch.dylib                   0x0000000180f44348 8E662F82-B1E4-3E7E-A376-18E9755A8F51 + 29512
38  FrontBoardServices                  0x00000001903460e0 A1960BD9-CE29-3E96-817D-955EBEB140BE + 372960
39  FrontBoardServices                  0x0000000190345d88 A1960BD9-CE29-3E96-817D-955EBEB140BE + 372104
40  FrontBoardServices                  0x00000001903462ac A1960BD9-CE29-3E96-817D-955EBEB140BE + 373420
41  CoreFoundation                      0x00000001812bf81c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 649244
42  CoreFoundation                      0x00000001812bf718 472C9193-115D-34CD-AD1D-0E7E091C9432 + 648984
43  CoreFoundation                      0x00000001812bea28 472C9193-115D-34CD-AD1D-0E7E091C9432 + 645672
44  CoreFoundation                      0x00000001812b8d20 472C9193-115D-34CD-AD1D-0E7E091C9432 + 621856
45  CoreFoundation                      0x00000001812b84bc CFRunLoopRunSpecific + 600
46  GraphicsServices                    0x0000000197d3d820 GSEventRunModal + 164
47  UIKitCore                           0x0000000183c5c734 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12048180
48  UIKitCore                           0x0000000183c61e10 UIApplicationMain + 168
49  pitt                                0x0000000100509784 pitt + 38788
50  libdyld.dylib                       0x0000000180f7fe60 90A4E82E-250C-35E3-8B2D-51D6D8B1119B + 3680 Path:Exception backtrace:
0   Realm                               0x0000000103016c24 _ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 60
1   Realm                               0x000000010300d4e0 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 7712
2   Realm                               0x000000010300ee20 _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 244
3   Realm                               0x00000001030135f8 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 392
4   Realm                               0x0000000102dee1c0 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1044
5   Realm                               0x0000000102ded2fc _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 68
6   Realm                               0x0000000102ded190 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 168
7   Realm                               0x0000000102ec2868 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 120
8   Realm                               0x0000000102e9217c +[RLMRealm realmWithConfiguration:queue:error:] + 956
9   RealmSwift                          0x000000010367e2a8 $s10RealmSwift0A0V5queueACSo012OS_dispatch_C0CSg_tKcfC + 104
10  pitt                                0x00000001007ad1d0 pitt + 2806224
11  pitt                                0x00000001007ad62c pitt + 2807340
12  pitt                                0x00000001007a45bc pitt + 2770364
13  UIKitCore                           0x0000000183c58a68 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12032616
14  UIKitCore                           0x0000000183c5aac4 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12040900
15  UIKitCore                           0x0000000183c60478 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12063864
16  UIKitCore                           0x00000001832f1d70 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2174320
17  UIKitCore                           0x000000018383d4d4 _UIScenePerformActionsWithLifecycleActionMask + 112
18  UIKitCore                           0x00000001832f28c0 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2177216
19  UIKitCore                           0x00000001832f238c 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2175884
20  UIKitCore                           0x00000001832f26d0 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2176720
21  UIKitCore                           0x00000001832f1f48 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2174792
22  UIKitCore                           0x00000001832fa078 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2207864
23  UIKitCore                           0x000000018374fc28 47154C6D-47DF-3ABB-A152-56B159B014E4 + 6753320
24  UIKitCore                           0x0000000183855810 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 272
25  UIKitCore                           0x00000001832f9df0 47154C6D-47DF-3ABB-A152-56B159B014E4 + 2207216
26  UIKitCore                           0x000000018312eeb0 47154C6D-47DF-3ABB-A152-56B159B014E4 + 327344
27  UIKitCore                           0x000000018312d86c 47154C6D-47DF-3ABB-A152-56B159B014E4 + 321644
28  UIKitCore                           0x000000018312ead8 47154C6D-47DF-3ABB-A152-56B159B014E4 + 326360
29  UIKitCore                           0x0000000183c5e668 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12056168
30  UIKitCore                           0x0000000183778274 47154C6D-47DF-3ABB-A152-56B159B014E4 + 6918772
31  FrontBoardServices                  0x00000001902f42dc A1960BD9-CE29-3E96-817D-955EBEB140BE + 37596
32  FrontBoardServices                  0x000000019031ea00 A1960BD9-CE29-3E96-817D-955EBEB140BE + 211456
33  FrontBoardServices                  0x0000000190302d24 A1960BD9-CE29-3E96-817D-955EBEB140BE + 97572
34  FrontBoardServices                  0x000000019031e6d0 A1960BD9-CE29-3E96-817D-955EBEB140BE + 210640
35  libdispatch.dylib                   0x0000000180f40ac8 8E662F82-B1E4-3E7E-A376-18E9755A8F51 + 15048
36  libdispatch.dylib                   0x0000000180f44348 8E662F82-B1E4-3E7E-A376-18E9755A8F51 + 29512
37  FrontBoardServices                  0x00000001903460e0 A1960BD9-CE29-3E96-817D-955EBEB140BE + 372960
38  FrontBoardServices                  0x0000000190345d88 A1960BD9-CE29-3E96-817D-955EBEB140BE + 372104
39  FrontBoardServices                  0x00000001903462ac A1960BD9-CE29-3E96-817D-955EBEB140BE + 373420
40  CoreFoundation                      0x00000001812bf81c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 649244
41  CoreFoundation                      0x00000001812bf718 472C9193-115D-34CD-AD1D-0E7E091C9432 + 648984
42  CoreFoundation                      0x00000001812bea28 472C9193-115D-34CD-AD1D-0E7E091C9432 + 645672
43  CoreFoundation                      0x00000001812b8d20 472C9193-115D-34CD-AD1D-0E7E091C9432 + 621856
44  CoreFoundation                      0x00000001812b84bc CFRunLoopRunSpecific + 600
45  GraphicsServices                    0x0000000197d3d820 GSEventRunModal + 164
46  UIKitCore                           0x0000000183c5c734 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12048180
47  UIKitCore                           0x0000000183c61e10 UIApplicationMain + 168
48  pitt                                0x0000000100509784 pitt + 38788
49  libdyld.dylib                       0x0000000180f7fe60 90A4E82E-250C-35E3-8B2D-51D6D8B1119B + 3680.

## Steps for others to Reproduce
Can't do it. It's reported by a user.
The realm file wasn't able to be opened.

## Code Sample
```
    // always be called in the main thread, no need to use synchronization
    func getDefaultRealm() {
            do {
                try Realm()
                realmInitialized = true
            }
            catch {
                let logHelper = LogHelper(subsystem: "RealmHelper", category: "getDefaultRealm")
                logHelper.e("Failed to get realm, error = %@", error: error)
                Crashlytics.crashlytics().record(error: error)
                return;
            }
    }
```
## Version of Realm and Tooling

Realm framework version: ?
5.3.2

Realm Object Server version: ?
N/A

Xcode version: ?
12.0.1

iOS/OSX version: ?
14.0.1

Dependency manager + version: ?
CocoaPods 1.8.3

**Comment by jsflax** [comment]
@KimiChiu we'll take a look at this.

**Comment by leemaguire** [comment]
@KimiChiu have you been able to test out Realm v10.1.4 to see if this fixes the issue?

**Comment by KimiChiu** [comment]
@leemaguire I will submit a new version with Realm v10.1.4 for TestFlight in these days.

**Comment by KimiChiu** [comment]
The new version with Realm v10.1.4 is working well on TestFlight.
I'll submit to App Store review today.

**Comment by leemaguire** [comment]
@KimiChiu Great to hear! I'll close the issue. If you have any more questions please open a new Github issue. Thanks!
