### ISSUE TITLE
Bugs: Carthage - Skipped installing realm-cocoa.framework binary due to the error

### ISSUE THREAD

**Issue by jesusmateos1234** [realm/realm-cocoa#6876]
!!! MANDATORY TO FILL OUT !!!

## Goals
Binary it's downloaded

## Expected Results
Binary it's downloaded

## Actual Results
Skipped, binary not downloaded and not compiled

## Steps for others to Reproduce
execute:  Carthage update --platform iOS

Realm framework version: 5.3.6

Dependency manager: Carthage version: 0.36

**Comment by jsflax** [comment]
@jesusmateos1234 what's the error? Have you tried running a clean install?

**Comment by trr-amsiq** [comment]
@jesusmateos1234 are you using Xcode 12+?

**Comment by jesusmateos1234** [comment]
i'm using Xcode 11.7 , swift 5.2.4

**Comment by jesusmateos1234** [comment]
Yes, i'm tried to make a clean install, but nothing change, we need to up versión to realm 5.5.0

**Comment by leemaguire** [comment]
@jesusmateos1234 Can you update to the latest Xcode. Our changelog states for 5.5.0: `Carthage release for Swift is built with Xcode 12`

**Comment by jesusmateos1234** [comment]
I build 5.5.0 from code, this solve my problem
