### ISSUE TITLE
Appending object with primary key to List throws error because element already exists instead of updating it.

### ISSUE THREAD

**Issue by jrpinteno** [realm/realm-cocoa#6885]
Hi,
   I'm not sure whether this would be a bug or feature enhancement. I have the following models (simplified for task at hand) in a swift application and in an Android application (not showing that one but their definitions are analogue)

```swift
class Message: Object {
   @objc dynamic var messageId: String = ""

   override class func primaryKey() -> String? {
      return "messageId"
   }
}

class Channel: Object {
   @objc dynamic var uuid: String = ""
   let messages = List<Message>()

   override class func primaryKey() -> String? {
      return "uuid"
   }
}
```

Then I have a method to append messages to said channel

```swift
func addMessage(_ message: Message) {
   do {
      let realm = try Realm()
      try realm.write {
         messages.append(message)
      }
   } catch {
   }
}
```

In realm-java version adding the message to the equivalent `RealmList<Message>` would use internally `copyToRealm(...)` or `copyToRealmOrUpdate(...)` if the object has a primary key.
But in realm-cocoa I get an exception because object did already exist in Realm.

Of course, I could do a workaround and check for object existence and act accordingly either appending the object or modifying its properties.

Would this be a bug in realm-cocoa?

## Version of Realm and Tooling
Realm framework version: 5.5.0

**Comment by jsflax** [comment]
I wouldn't say it's a bug. How should the List know the intentions of the user? I would say the onus is on the user to explicitly run those checks. RealmSwift has the ability to add and update on the Realm struct itself, but having that implicitly be behaviour on a list feels wrong. 

Unless you feel strongly about this (or would want to open a PR demonstrating a clean way to add this functionality to a list), would you mind closing this out?

**Comment by tgoyne** [comment]
You can choose how PK conflicts are handled by explicitly calling `realm.add()` on the object before calling `append()`, which has the `update:` parameter. This is a no-op if the object is already managed by the Realm.

**Comment by jrpinteno** [comment]
> I wouldn't say it's a bug. How should the List know the intentions of the user? I would say the onus is on the user to explicitly run those checks. RealmSwift has the ability to add and update on the Realm struct itself, but having that implicitly be behaviour on a list feels wrong.

I was pointing out as well the difference between Realm for java and cocoa.

> You can choose how PK conflicts are handled by explicitly calling `realm.add()` on the object before calling `append()`, which has the `update:` parameter. This is a no-op if the object is already managed by the Realm.

That's good to know, documentation was not clear on that point. I'll adapt my code to take that into account.
