### ISSUE TITLE
Framework not found `realm-sync` (RealmSwift 10.1.0)

### ISSUE THREAD

**Issue by mkran** [realm/realm-cocoa#6888]
## Goals

Build an empty iOS XCode project after installing RealmSwift v10.1.0 using cocoa pods in a simulator

## Expected Results

Build succeeded.

## Actual Results

```
ld: framework not found realm-sync
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps for others to Reproduce

Follow the instructions here: [Install Realm for iOS](https://docs.mongodb.com/realm/ios/install/)

## Version of Realm and Tooling

Realm framework version: 10.1.0

Realm Object Server version: ?

Xcode version: 12.0 beta 6

iOS/OSX version: 14.0 (iOS)

Dependency manager + version: COCOAPODS: 1.9.3

**Comment by leemaguire** [comment]
You need to use Cocoapods 1.10

**Comment by mkran** [comment]
Thanks so much @leemaguire. That was easy!
