### ISSUE TITLE
Build error under Travis: "Undefined symbols for architecture x86_64: Symbol: realm::ConstLstIf<realm::Decimal128>::min(unsigned long*) const"

### ISSUE THREAD

**Issue by farktronix** [realm/realm-cocoa#6889]
!!! MANDATORY TO FILL OUT !!!

## Goals

I'm trying to get our project building under Travis. It builds fine on my local machine using both Xcode and the `xcodebuild` command

## Expected Results

The build should succeed without error, just like it does under Xcode and `xcodebuild` on my local machine

## Actual Results

The build fails with an undefined symbol error for this symbol:

```
❌  Undefined symbols for architecture x86_64
Symbol: realm::ConstLstIf<realm::Decimal128>::min(unsigned long*) const
Referenced from: vtable for realm::Lst<realm::Decimal128> in thread_safe_reference.o
```

You can view the full build log here: https://travis-ci.org/github/farktronix/relisten-ios/builds/738864526

My only guess here is that the Travis builder lists AMD64 as its architecture, so this might be due to cross-compiling and something in Realm assuming the native architecture is the target architecture.

I've included the suggested workaround from #6685 and I have this in my Podfile:
```
config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
```

I also double-checked that all of the targets in my project have `EXCLUDED_ARCHS[sdk=iphonesimulator*] = 'arm64'` set as well.

## Steps for others to Reproduce

I haven't tried reducing this to a sample project yet, but you can fork/pull Relisten [here](https://github.com/RelistenNet/relisten-ios) and you're welcome to make a dummy PR so that Travis builds it.

## Version of Realm and Tooling

Realm framework version:   RealmSwift (10.1.0), Realm (= 10.1.0)

Realm Object Server version: N/A

Xcode version: Version 12.1 (12A7403)

iOS/OSX version: 14.0

Dependency manager + version: Cocoapods 1.10.0

**Comment by tgoyne** [comment]
"Could not find proper version of cocoapods (1.10.0) in any of the sources" in the logs suggests that whatever version of cocoapods it's using, it isn't 1.10 and that version is now required by Realm 10.1.

**Comment by farktronix** [comment]
That error message is a false alarm- it's because the script checks to see if cocoapods is installed, and if it isn't it installs it. Line 926 and 927 show that Cocoapods 1.10.1 is installed:

```
926> Fetching cocoapods-core 1.10.0
927> Installing cocoapods-core 1.10.0
```

**Comment by farktronix** [comment]
I wasn't able to reproduce this with a sample project, which led me to eventually discover this line in our project's `.gitignore`:

```
Pods/Realm/**/*.a
```

That meant we were keeping around most of the Realm cocoapod in git, but not the libraries. This led to some unexpected behavior on Travis and it looks like it wasn't always fetching the static libraries that it needed.

I fixed this by just excluding all of the Realm cocoapod in our `.gitignore`, which means the full pod will be re-downloaded by Travis.

```
Pods/Realm
```
