### ISSUE TITLE
Xcode and ReamSwift 10.1: framework not found realm-sync

### ISSUE THREAD

**Issue by tklocek** [realm/realm-cocoa#6891]
!!! MANDATORY TO FILL OUT !!!

I have Xcode ver 12.1 and RealmSwift in version 10.1 throw this error:
ld: framework not found realm-sync
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It happens on existing project when I update all my pods and on new clean project only with import RealmSwift.

When I deintegrated and change RealmSwift version to 5.5.0 everything works. 

## Actual Results

Ld /Users/tomaszklocek/Library/Developer/Xcode/DerivedData/COVID-19_Casestudy-drottjqhvdkdwrafrptpulplxrju/Build/Products/Debug-iphonesimulator/Realm/Realm.framework/Realm normal (in target 'Realm' from project 'Pods')
    cd /Users/tomaszklocek/Documents/Xcode\ playground/COVID-19\ Casestudy/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-ios12.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk -L/Users/tomaszklocek/Library/Developer/Xcode/DerivedData/COVID-19_Casestudy-drottjqhvdkdwrafrptpulplxrju/Build/Products/Debug-iphonesimulator/Realm -F/Users/tomaszklocek/Library/Developer/Xcode/DerivedData/COVID-19_Casestudy-drottjqhvdkdwrafrptpulplxrju/Build/Products/Debug-iphonesimulator/Realm -F/Users/tomaszklocek/Documents/Xcode\ playground/COVID-19\ Casestudy/Pods/Realm/core -F/Users/tomaszklocek/Documents/Xcode\ playground/COVID-19\ Casestudy/Pods/Realm/core/realm-sync.xcframework/ios-arm64_i386_x86_64-simulator -F/Users/tomaszklocek/Documents/Xcode\ playground/COVID-19\ Casestudy/Pods/Realm/core/realm-sync.xcframework/ios-armv7_arm64 -F/Users/tomaszklocek/Documents/Xcode\ playground/COVID-19\ Casestudy/Pods/Realm/core/realm-sync.xcframework/ios-x86_64-maccatalyst -filelist /Users/tomaszklocek/Library/Developer/Xcode/DerivedData/COVID-19_Casestudy-drottjqhvdkdwrafrptpulplxrju/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Realm.build/Objects-normal/x86_64/Realm.LinkFileList -install_name @rpath/Realm.framework/Realm -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/tomaszklocek/Library/Developer/Xcode/DerivedData/COVID-19_Casestudy-drottjqhvdkdwrafrptpulplxrju/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Realm.build/Objects-normal/x86_64/Realm_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -fapplication-extension -lc++ -lz -framework Security -framework realm-sync -framework Foundation -framework Security -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/tomaszklocek/Library/Developer/Xcode/DerivedData/COVID-19_Casestudy-drottjqhvdkdwrafrptpulplxrju/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Realm.build/Objects-normal/x86_64/Realm_dependency_info.dat -o /Users/tomaszklocek/Library/Developer/Xcode/DerivedData/COVID-19_Casestudy-drottjqhvdkdwrafrptpulplxrju/Build/Products/Debug-iphonesimulator/Realm/Realm.framework/Realm

ld: framework not found realm-sync
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Steps for others to Reproduce

This is my Cocoapods file.
Install RealmSwift on new project. 
In my case it crash.

target 'COVID-19 Casestudy' do
  use_frameworks!

  # Pods for COVID-19 Casestudy
  pod 'RealmSwift'
  
end

## Version of Realm and Tooling

Realm framework version: 10.1

Realm Object Server version: ?

Xcode version: 12.1

iOS/OSX version: 10.15.7 (19H2)

Dependency manager + version: ?

**Comment by leemaguire** [comment]
You need to be using Cocoapods v1.10

**Comment by tklocek** [comment]
I’m using 1.5.2 version.
Must I downgrade?

Pozdrawiam serdecznie,

Tomasz Klocek
tel: +48 604 261 883
tomek@klocek.info

**Comment by jsflax** [comment]
@tklocek 1.10 is an upgrade– it is the latest version of Cocoapods.

**Comment by tklocek** [comment]
It helps.
Thanks

Pozdrawiam serdecznie,

Tomasz Klocek
tel: +48 604 261 883
tomek@klocek.info

**Comment by summonerriftofficial** [comment]
Same problem

**Comment by tklocek** [comment]
write this in terminal: 
`sudo gem install cocoapods`

**Comment by cupofheat** [comment]
> write this in terminal:
> `sudo gem install cocoapods`

Doesn't help :(

**Comment by tklocek** [comment]
Try 
`pod --version`
Now I have result 1.10.0.

After update Cocoapods I closed Xcode and use:
```
pod deintegrate 
pod install
```
when pods are installing you will see which version of realm they will use. 
Then I build&run app and it works for me.

**Comment by phntxx** [comment]
Same issue on Cocoapods version 1.9.3. `pod deintegrade` and `pod install` did not help.

**Comment by tklocek** [comment]
I make this same mistake, you are checking version of graphic interface not Cocoapods.
You must use this line in terminal:
'sudo gem install cocoapods'

Pozdrawiam serdecznie,

Tomasz Klocek
tel: +48 604 261 883
tomek@klocek.info

**Comment by cupofheat** [comment]
That's helped. Thank you!
