### ISSUE TITLE
V3.16.2 support for Xcode 12

### ISSUE THREAD

**Issue by VinodComlink** [realm/realm-cocoa#6895]
!!! MANDATORY TO FILL OUT !!!

**Bugs**: Getting Compilation error in Xcode 12 with realm version 3.16.2.

## Goals
Compile realm version 3.16.2 with Xcode 12 with 

## Expected Results
Should compile successfully

## Actual Results
 No exact matches in call to intializer 

## Steps for others to Reproduce
Try ro compile V3.16.2 on Xcode 12 

## Code Sample
extension ModelMappeable where Self: BaseModel {

    static func getOrCreate(realm: Realm, values: JSON?, updates: UpdateBlock<Self>?) -> Self {
        var object: Self!
        print("object object = \(object)")

        if let primaryKey = values?["_id"].string {
            if let newObject = realm.object(ofType: Self.self, forPrimaryKey: primaryKey as AnyObject) {
                    object = newObject
            }
        }

        if object == nil {
            object = Self()
        }
        

        if let values = values {
            object.map(values, realm: realm)
        }

        updates?(object)
        return object
    }

## Version of Realm and Tooling

Realm framework version:  3.16.2

Realm Object Server version: ?

Xcode version: Xcode 12

iOS/OSX version: 10.15.6

Dependency manager + version: ?

**Comment by VinodComlink** [comment]
![Uploading Screenshot 2020-10-28 at 6.02.59 PM.png…]()

**Comment by VinodComlink** [comment]
<img width="1106" alt="Screenshot 2020-10-28 at 6 02 59 PM" src="https://user-images.githubusercontent.com/32677695/97436627-4f144400-1948-11eb-8835-9286a9b0e0c9.png">

**Comment by VinodComlink** [comment]
We can not update realm version due to certain limitations.

**Comment by leemaguire** [comment]
@VinodComlink This version of Realm works and compiles within Xcode 12.1. Have you tried changing `object = Self()` and does `ModelMappeable` have a valid initialiser it can call from?

**Comment by VinodComlink** [comment]
@leemaguire I am able to fix the issue by adding initialiser in the base Class of ModelMappable. Thank for reply
