### ISSUE TITLE
realm.objects(Object.self).sorted is not working properly in swift 5

### ISSUE THREAD

**Issue by darkForestCat** [realm/realm-cocoa#6897]
## Goals
I want to sort my objects by the key in ascending, the key is my lastPath component for the image of the object
## Expected Results
So I am expecting that using realm.objects(Object.self).sorted I can show users my objects in ascending by the key
The key example is:  .numberOfImage.png

IT MUST BE SORTED LIKE THIS:

.44.png
.46.png
.59.png
.60.png
.61.png
.154.png
.155.png
.156.png

## Actual Results
So it is sorted, but a little bit in a strange mode...
Like this : 
.154.png
.155.png
.156.png
.44.png
.46.png
.59.png
.60.png
.61.png

NO ONE KNOWS WHY 154 IS COMING BEFORE 44....

## Steps for others to Reproduce
Just do a realm  object with  a string property that will be in a format .number.png and try to sort it using 
`        let list = realm.objects(ObjectName.self).sorted(byKeyPath: "propertyname", ascending: true)
`
## Code Sample
    
 `class YourObject: Object {  `
    
    @objc dynamic var yourPropety = ""

    override class func primaryKey() -> String {
        return "yourPropety"
    }
 `}
//and then sort is somewhere like this `
 `  let list = realm.objects(YourObject.self).sorted(byKeyPath: "yourPropety", ascending: true) `

## Version of Realm and Tooling

Realm framework version: 10.1

Xcode version: 12.0.1

iOS/OSX version: 14.1

**Comment by DShamaev** [comment]
It's not Realm issue. When you are sorting strings it uses lexicographic or natural order, where '19999' is earlier than '200' (asssuming ascending direction) because it starts with '1'

**Comment by darkForestCat** [comment]
@DShamaev  Yeah I forgot  about this, but now if I have a string property like this how  could  I  sort it correctly?Because it is causing bug in my UITableView :(

**Comment by leemaguire** [comment]
@darkForestCat You might want to add another `Int` property to your object that helps you index the items in a meaningful way.
