### ISSUE TITLE
Xcode archiving fails with SPM

### ISSUE THREAD

**Issue by xavierLowmiller** [realm/realm-cocoa#6906]
# Description

I'm using realm-cocoa 10.1.1, which depends on realm-core 10.0.0. The dependency is managed using Swift Package Manager.

## Goals
I'm trying to archive an iOS app that uses Realm(Swift) integrated via Swift Package Manager

## Expected Results
The app is archived for distribution

## Actual Results
This error is produced:
<img width="808" alt="Screenshot 2020-11-03 at 13 12 39" src="https://user-images.githubusercontent.com/16212751/97983920-4acba900-1dd6-11eb-9592-3dba2eec6f93.png">

The error actually happens in `realm-core`, but [they told me to open an issue here](https://github.com/realm/realm-core/issues/4035).

## Steps for others to Reproduce
1. Create a new iOS app in Xcode
2. Add the dependency to Realm via Swift Package Manager
3. Try to archive the project

## Code Sample
n/a

## Version of Realm and Tooling

Realm framework version:
Realm Cocoa: 10.1.1
Realm Core: 10.0.0

Realm Object Server version: not used

Xcode version: 12.1

iOS/OSX version: iOS 11-14.1

Dependency manager + version: Swift Package Manager 5.3

**Comment by leemaguire** [comment]
@xavierLowmiller The minimum deployment target when using SPM is iOS 11, changing your project to support a minimum version of iOS 11 should help.

**Comment by xavierLowmiller** [comment]
Our main project only supports iOS 11 and up, and my test project to reproduce the issue is iOS 14+.

I think that Realm Core's Package.swift file should be limited to iOS 11+, like Realm Cocoa's Package.swift file:

```swift
platforms: [
        .macOS(.v10_10),
        .iOS(.v11),
        .tvOS(.v9),
        .watchOS(.v2)
    ],
```

**Comment by leemaguire** [comment]
@xavierLowmiller So all targets in your project are iOS 11+ and it still gives this issue trying to archive?

**Comment by xavierLowmiller** [comment]
Yes. Adding the lines to `realm-core`'s Package.swift locally file resolves the issue for me.

**Comment by xavierLowmiller** [comment]
Solved by https://github.com/realm/realm-core/pull/4039.

**Comment by Tommecpe** [comment]
@xavierLowmiller I've got the same problem, I don't understand how did you solve it ?
can you give a bit more detail ?

Thank-you very much

**Comment by xavierLowmiller** [comment]
It won't work out of the box until a new version of `realm-core` is released. Until then you can add an explicit dependency to `realm-core` pointing at the current `master`.

**Comment by Tommecpe** [comment]
Adding `RealmCore` git: `https://github.com/realm/realm-core` branch: `master`
Seam to work ! thank-you for you very quick answer !!

**Comment by devedup** [comment]
> It won't work out of the box until a new version of `realm-core` is released. Until then you can add an explicit dependency to `realm-core` pointing at the current `master`.

Tried that, but it didn't work. 

`Swift package target 'RealmCore' is linked as a static library by 'TestRealm' and 'RealmCoreDynamic'. This will result in duplication of library code.`

If you know the reason for this, I'd be interested to know. But for now I'll just use CocoaPods until the SPM version is ready. 

Thanks
