### ISSUE TITLE
Unable to open encrypted realm file after upgrade from RealmSwift 5.3.5 to 10.1.1

### ISSUE THREAD

**Issue by chajuss** [realm/realm-cocoa#6907]
I have an iOS app that used Realm Swift 5.3.5 as an internal database. We were had our realm file encrypted, and were able to open it using Realm Studio 5.0.1.6 with our stored key.

After upgrading to Realm Swift 10.1.1, we're unable to open the file in Realm Studio 5.0.1 as we get the following error: **Opening Realm files of format version 20 is not supported by this version of Realm**

Using MongoDB Realm Studio 10.0.0.4, I have the following error:

`Unable to open a realm at path '/Users/oric/Documents/new realm/***.realm': Realm file initial open failed Path:Exception backtrace:
0 .com.mongodb.realm-studio.kTxtnK 0x000000010dba19d1 _ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 49
1 .com.mongodb.realm-studio.kTxtnK 0x000000010db644cd _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigE + 3453
2 .com.mongodb.realm-studio.kTxtnK 0x000000010dba3caa _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 3482
3 .com.mongodb.realm-studio.kTxtnK 0x000000010dba6d73 _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 243
4 .com.mongodb.realm-studio.kTxtnK 0x000000010dbab986 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 342
5 .com.mongodb.realm-studio.kTxtnK 0x000000010d651db5 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1277
6 .com.mongodb.realm-studio.kTxtnK 0x000000010d650d42 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 62
7 .com.mongodb.realm-studio.kTxtnK 0x000000010d650ba8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 530
8 .com.mongodb.realm-studio.kTxtnK 0x000000010d63af8e _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 128
9 .com.mongodb.realm-studio.kTxtnK 0x000000010d5251ca _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEN4Napi3EnvENS_5Realm6ConfigEbONSt3__13mapINS9_12basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEENSA_ISG_NS0_9ProtectedINS5_5ValueEEENS9_4lessISG_EENSE_INS9_4pairIKSG_SJ_EEEEEESL_NSE_INSM_ISN_SQ_EEEEEEONSA_ISG_NSH_INS5_8FunctionEEESL_NSE_INSM_ISN_SW_EEEEEE + 234
10 .com.mongodb.realm-studio.kTxtnK 0x000000010d52390e _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEN4Napi3EnvENS5_6ObjectERNS0_9ArgumentsIS3_EE + 334
11 .com.mongodb.realm-studio.kTxtnK 0x000000010d520289 _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE20constructor_callbackERKN4Napi12CallbackInfoE + 135
12 .com.mongodb.realm-studio.kTxtnK 0x000000010d5228da _ZN5realm4node13WrappedObjectINS_2js10RealmClassINS0_5TypesEEEEC2ERKN4Napi12CallbackInfoE + 128
13 .com.mongodb.realm-studio.kTxtnK 0x000000010d5227af _ZZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ENKUlvE_clEv + 67
14 .com.mongodb.realm-studio.kTxtnK 0x000000010d522525 _ZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ + 71
15 Electron Framework 0x0000000106d907ca napi_create_function + 858
16 Electron Framework 0x000000010223d2ec _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 16844
17 Electron Framework 0x000000010223c4b8 _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 13208
18 Electron Framework 0x000000010223bd9f _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 11391
19 Electron Framework 0x0000000102c3f999 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 501289.`

## Version of Realm and Tooling

Realm framework version: 5.3.5 - 10.1.1

Realm Object Server version: - N/A

Xcode version: 12.1

iOS/OSX version: 14.1

Dependency manager + version: cocoapods 1.10.0

**Comment by leemaguire** [comment]
@chajuss Please use Realm Studio v10 to open your Realm file https://github.com/realm/realm-studio/releases/tag/v10.0.0

**Comment by chajuss** [comment]
> @chajuss Please use Realm Studio v10 to open your Realm file https://github.com/realm/realm-studio/releases/tag/v10.0.0

@leemaguire Thanks for the fast reply, however please read carefully my post:  I did try to open with Realm Studio v10 and got  the exception backtrack I've provided.

**Comment by leemaguire** [comment]
@chajuss could you send the Realm file to lee.maguire@mongodb.com so we an investigate. Also are you seeing this issue with any other Realm files you have?

**Comment by chajuss** [comment]
@leemaguire I've sent you the file to provided email.
This occurs with every Realm file we are using (all are structured the same as provided one), and we don't have any other types of Realm files to test with.

**Comment by leemaguire** [comment]
@chajuss Are you using compaction, or did you do any schema changes during the upgrade?

**Comment by chajuss** [comment]
@leemaguire not using compaction, but did a schema change during the upgrade

**Comment by leemaguire** [comment]
Linking https://github.com/realm/realm-studio/pull/1351 as it may serve as the solution.

**Comment by leemaguire** [comment]
@chajuss does the latest version of Realm Studio solve your issue?

**Comment by chajuss** [comment]
@leemaguire I'll check and post an update ASAP

**Comment by chajuss** [comment]
Using Version 10.1.2 (10.1.2.43) solved the issue. Thanks!
