### ISSUE TITLE
Archiving with Realm 5.5.0 fails for armv7

### ISSUE THREAD

**Issue by intiocean** [realm/realm-cocoa#6909]
When archiving (building all architectures rather than just the target architecture I get the following error) so cannot create an archive build. NB. I'm using Realm objc as I have a mixed objc/swift project.

<img width="1308" alt="Screenshot 2020-11-03 at 21 16 07" src="https://user-images.githubusercontent.com/725843/98036975-3067ee80-1e1b-11eb-9177-7120e6281312.png">

## Steps for others to Reproduce
I have added Realm as a SPM dependency because cocoapods wasn't working for me (pre 1.10 cocoapods release so may try cocoapods again and see if that works)

## Version of Realm and Tooling
Realm framework version: 5.5.0

Realm Object Server version: N/A

Xcode version: 12.1

iOS/OSX version: target version 10.0

Dependency manager + version: N/A

**Comment by intiocean** [comment]
Just tried with cocoapods and I get a different issue but still can't create an archive build

<img width="1314" alt="Screenshot 2020-11-03 at 22 09 16" src="https://user-images.githubusercontent.com/725843/98041021-8dff3980-1e21-11eb-84ee-27d97e2f4bf5.png">

**Comment by intiocean** [comment]
Added realm as a Cartharge dependency and I can create archives! Yay! No idea why the others aren't working thought

**Comment by leemaguire** [comment]
@intiocean I'm not seeing this with 5.5.0 or 10.1.1, Did you try clean your derived data & pods directory?

**Comment by intiocean** [comment]
Cleaned the project and deleted derived data (not the pods directory though) @leemaguire 

It looks like the pod errors and the SPM errors are different issues to me?

**Comment by leemaguire** [comment]
They are different errors but I believe they are due to the project being in an unclean state.
