### ISSUE TITLE
Release compilation issue using Swift PM

### ISSUE THREAD

**Issue by devedup** [realm/realm-cocoa#6914]
## Goals

Build project with Realm via Swift Package Manager

## Expected Results

The project to build successfully, but it doesn't (However it works ok with same version on Cocoapods)

## Actual Results

Showing All Messages
/Users/dave/Library/Developer/Xcode/DerivedData/TestRealm-cexqmmixscidkqairqvranppknzi/SourcePackages/checkouts/realm-core/src/realm/alloc.hpp:328:5: Aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer

## Steps for others to Reproduce

1. Create a new Xcode project - i'm using 12.1. I don't change any of the defaults. 
2. iOS deployment target is 14.1
3. I add swift package dependency at repo: https://github.com/realm/realm-cocoa
4. I do an archive/release build
5. It doesn't build

(note that if I use Cocoapods, then it works ok)

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: 12.1

iOS/OSX version: 14.1 / Mac 10.13.6

Dependency manager + version: Swift PM

**Comment by devedup** [comment]
Sorry...closing/opening... i hit enter by mistake... it's late.. i'm tired. 😂😢

**Comment by leemaguire** [comment]
The fix for this will be available in the next release of Realm Cocoa.

**Comment by xavierLowmiller** [comment]
Until then you can point `realm-core` to `master` if you need to release, the fix is [already there](https://github.com/realm/realm-cocoa/issues/6906#issuecomment-722460653).
