### ISSUE TITLE
Did you remember to mark them with '@objc' in your model?

### ISSUE THREAD

**Issue by aliawais** [realm/realm-cocoa#6925]
#6668  Goals

App to compile and run seamlessly as before.

## Expected Results

App to compile and run seamlessly as before.

## Actual Results
App Crashing on launch with following error on Realm 10.1.1 (works fine with Realm 10.0.0)
**Thread 1: "No properties are defined for 'DocumentEntity'. Did you remember to mark them with '@objc' in your model?"**

## Steps for others to Reproduce
Launch the app with Realm version given below. I have issue in unit testing as it was not compiling due class Document which has same name as a class in Realm library, now it is crashing with above message, complete code of DocumentEntity given below.

## Code Sample
```
import Foundation
import RealmSwift

class DocumentEntity: Object {
    @objc dynamic let assetId: String
    @objc dynamic let name: String
    @objc dynamic let filePath: String

    required override init() {
        assetId = ""
        name = ""
        filePath = ""

        super.init()
    }

    init(document: Document) {
        assetId = document.assetId!
        name = document.name
        filePath = document.filePath

        super.init()
    }

    init(assetId: String, document: Document) {
        self.assetId = assetId
        name = document.name
        filePath = document.filePath

        super.init()
    }
}
```

## Version of Realm and Tooling

Realm framework version: ?

- Realm - 10.1.1
- RealmSwift 10.1.1

Xcode version: ?

- 12.1

iOS/OSX version: ?

- 13.6

Dependency manager + version: ?

- 1.10.0

**Comment by pavel-ship-it** [comment]
Hi @aliawais,
Realm model properties need the dynamic var attribute in order for these properties to become accessors for the underlying database data.

There are two exceptions to this: List and RealmOptional properties cannot be declared as dynamic because generic properties cannot be represented in the Objective-C runtime, which is used for dynamic dispatch of dynamic properties, and should always be declared with let

**Comment by aliawais** [comment]
Thanks @pavel-ship-it I will have a look.

I was looking in my code, only this entity have '@objc dynamic let', but it was working fine till updated to 10.1.1.

**Comment by AhmedAlsebaei** [comment]
thanks

**Comment by sushmalatha** [comment]
> #6668 Goals
> 
> App to compile and run seamlessly as before.
> 
> ## Expected Results
> App to compile and run seamlessly as before.
> 
> ## Actual Results
> App Crashing on launch with following error on Realm 10.1.1 (works fine with Realm 10.0.0)
> **Thread 1: "No properties are defined for 'DocumentEntity'. Did you remember to mark them with '@objc' in your model?"**
> 
> ## Steps for others to Reproduce
> Launch the app with Realm version given below. I have issue in unit testing as it was not compiling due class Document which has same name as a class in Realm library, now it is crashing with above message, complete code of DocumentEntity given below.
> 
> ## Code Sample
> ```
> import Foundation
> import RealmSwift
> 
> class DocumentEntity: Object {
>     @objc dynamic let assetId: String
>     @objc dynamic let name: String
>     @objc dynamic let filePath: String
> 
>     required override init() {
>         assetId = ""
>         name = ""
>         filePath = ""
> 
>         super.init()
>     }
> 
>     init(document: Document) {
>         assetId = document.assetId!
>         name = document.name
>         filePath = document.filePath
> 
>         super.init()
>     }
> 
>     init(assetId: String, document: Document) {
>         self.assetId = assetId
>         name = document.name
>         filePath = document.filePath
> 
>         super.init()
>     }
> }
> ```
> 
> ## Version of Realm and Tooling
> Realm framework version: ?
> 
> * Realm - 10.1.1
> * RealmSwift 10.1.1
> 
> Xcode version: ?
> 
> * 12.1
> 
> iOS/OSX version: ?
> 
> * 13.6
> 
> Dependency manager + version: ?
> 
> * 1.10.0

Have you got the solution for that

**Comment by sushmalatha** [comment]
> #6668 Goals
> 
> App to compile and run seamlessly as before.
> 
> ## Expected Results
> App to compile and run seamlessly as before.
> 
> ## Actual Results
> App Crashing on launch with following error on Realm 10.1.1 (works fine with Realm 10.0.0)
> **Thread 1: "No properties are defined for 'DocumentEntity'. Did you remember to mark them with '@objc' in your model?"**
> 
> ## Steps for others to Reproduce
> Launch the app with Realm version given below. I have issue in unit testing as it was not compiling due class Document which has same name as a class in Realm library, now it is crashing with above message, complete code of DocumentEntity given below.
> 
> ## Code Sample
> ```
> import Foundation
> import RealmSwift
> 
> class DocumentEntity: Object {
>     @objc dynamic let assetId: String
>     @objc dynamic let name: String
>     @objc dynamic let filePath: String
> 
>     required override init() {
>         assetId = ""
>         name = ""
>         filePath = ""
> 
>         super.init()
>     }
> 
>     init(document: Document) {
>         assetId = document.assetId!
>         name = document.name
>         filePath = document.filePath
> 
>         super.init()
>     }
> 
>     init(assetId: String, document: Document) {
>         self.assetId = assetId
>         name = document.name
>         filePath = document.filePath
> 
>         super.init()
>     }
> }
> ```
> 
> ## Version of Realm and Tooling
> Realm framework version: ?
> 
> * Realm - 10.1.1
> * RealmSwift 10.1.1
> 
> Xcode version: ?
> 
> * 12.1
> 
> iOS/OSX version: ?
> 
> * 13.6
> 
> Dependency manager + version: ?
> 
> * 1.10.0

**Comment by sushmalatha** [comment]
Did you remember to mark them with '@objc' in your model?


Please help me on this how to resolve. i'm also facing same issue

**Comment by pavel-ship-it** [comment]
@sushmalatha what is your objects model? Did you define the properties with '**@objc dynamic var**'?
