### ISSUE TITLE
Request for RealmSwift 4.4.1 build with XCode 12

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#6929]
## Goals
User RealmSwift v4.4.1 with Xcode 12.x

RealmSwift v4.4.1 has provide extremely reliable and we would like to be able to continue using this version with XCode 12 but require a new binary build for XCode 12/Swift 5.3 (I think it is)

## Expected Results
Please can a new v4.4.1 binary build be created with XCode 12

**Comment by pavel-ship-it** [comment]
Hi @duncangroenewald,
I would still recommend you to try our latest version 10.1.2.

**Comment by duncangroenewald** [comment]
@pavel-ship-it - how would we be able to use that with Realm Cloud ?  As we understand it 10.1.12 will only work with the new Mongo Realm.  We do plan to migrate there over the coming 12 months so there seems little point in also upgrading to 5.5.0 - particularly as there seem to still be some issue.

**Comment by duncangroenewald** [comment]
@pavel-ship-it - btw I have been trying to find documentation on migration from Realm Cloud/RealmSwift 4.4.1 to Mongo Realm but it is rather light.  There is a migration guide but it doesn't seem to provide any useful detail for how one would migrate and existing Realm Cloud applications data.  Some questions:

1.  Is there a detailed explanation somewhere of the differences between Realm Cloud and Mongo Realm ?
     - Is the client side RealmSwift 10 api essentially identical to the RealmSwift 5.x with the exception of the authorisation and sync apis
     - With the RealmSwift 10 api is it necessary to set or reference the "_partition" property or is this automatically handled under the covers depending on the client connection?
2. Is there a detailed explanation of how one migrates data from an existing Realm Cloud solution to Mongo Realm ?

And then related to conversion of an existing application:
3. As I understand it in order to migrate and existing application one has to modify the existing schema to include new "_id" and "_partition" properties for each object.
4. Presumably this would also required that all existing data needs to be migrated to the new schema with some custom migration code.  We use UUID for the "id" property currently so presumably we could create new objects using the same values from the "id" property.  Is it also necessary to set the "_partition" value of is this automatically handled by the api or backend?
5. For existing List properties presumably we would have to recreate these lists using more custom migration code.
6. Similarly for any object reference properties that exist we would have to recreate them by referring to the new objects.

**Comment by ianpward** [comment]
@duncangroenewald We don't provide pre-built binaries for past versions but you are welcome to download the repo and compile it yourself if you'd like. 

There is a migration guide here - https://docs.realm.io/realm-legacy-migration-guide/

If you have additional questions then please take them to the forums.realm.io  OR there is a a form at the bottom of the migration guide where you can request more help with the migration from our Professional Services team.

I hope this helps

**Comment by duncangroenewald** [comment]
@ianpward - bear in mind we need to be able to sync with Realm Cloud and I was under the impression that the sync component source code was not available to download ? 

> @duncangroenewald We don't provide pre-built binaries for past versions but you are welcome to download the repo and compile it yourself if you'd like.
> 
> There is a migration guide here - https://docs.realm.io/realm-legacy-migration-guide/
> 
> If you have additional questions then please take them to the forums.realm.io OR there is a a form at the bottom of the migration guide where you can request more help with the migration from our Professional Services team.
> 
> I hope this helps
