### ISSUE TITLE
Realm Sync Doesn't Support mac-arm64 When Building in Xcode 12.2

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-cocoa#6936]
## Goals

build with Xcode 12.2.

## Expected Results

build successfully

## Actual Results

build failed.

## Steps for others to Reproduce

1. create a macOS app
2. create Podfile with RealmSwift
3. pod update
4. open .workspace file
5. include RealmSwift.
6. build

## Version of Realm and Tooling

Realm framework version: ?
RealmSwift 10.1.3
Realm Object Server version: ?

Xcode version: ?
Xcode 12.2 (12B45b)

iOS/OSX version: ?
macOS 10.15.7 (19H15)

Dependency manager + version: ?
CocoaPods 1.10.0

<img width="770" alt="sc" src="https://user-images.githubusercontent.com/2182896/99141591-ce638080-2687-11eb-9c9c-9c550b3c9a3d.png">

**Comment by zcohan** [comment]
The latest binaries (v10.1.3) built for Xcode 12.2 don't include a framework with mac-arm64 support either.

**Comment by wojciech-kulik** [comment]
+1 I can't release my app for Apple Silicon.

**Comment by jsflax** [comment]
Hi folks, `v10.1.4` now supports mac-arm64. @owenzhao , can you please upgrade and, if the new release solves your issue, close this out?

**Comment by wojciech-kulik** [comment]
@jsflax it looks like on cocoapods there is still version `10.1.3`

**Comment by wojciech-kulik** [comment]
@jsflax it looks like on cocoapods there is still `10.1.3` version (https://cocoapods.org/pods/RealmSwift)

**Comment by jsflax** [comment]
It appears there was an issue last night pushing 10.1.4 to Cocoapods for RealmSwift. We're going to look into this ASAP.

**Comment by tgoyne** [comment]
RealmSwift 10.1.4 is now actually out.

**Comment by wojciech-kulik** [comment]
Now it works, thanks guys!
