### ISSUE TITLE
Apple Sign in fails with "invalid number of segments"

### ISSUE THREAD

**Issue by FaultyJuggler** [realm/realm-cocoa#6938]
## Goals
Use Apple Sign In for Realm users on iOS

## Expected Results
Sign in would register a new user and open the app to realm data

## Actual Results
After Apple Sign in is completed, fails with error:

`Login failed: Error Domain=realm::app::ServiceError Code=47 "token contains an invalid number of segments" UserInfo={NSLocalizedDescription=token contains an invalid number of segments, realm::app::ServiceError=AuthError}`

## Steps for others to Reproduce
Setup Apple Sign in following directions from https://docs.mongodb.com/realm/authentication/apple/#apple-id-authentication as well as Apple documentation.

Tap Sign In, see failed results when Realm connection is attempted

Documentation isn't very clear on why we create a Service ID in addition to the App ID being setup for Apple Sign In.  We don't have an accompanying app website, so redirect URIs seem unnecessary for an app signing in alone.  The steps were also confusing as far as exactly which items need to go into generating the JWT.  My assumption is after the app successfully signs in, Realm will talk to apple ID servers from within Atlas?

Lack of screenshots and sample code leave me unsure on if the configuration beforehand was done correctly, but this problem is not a configuration issue as far as I can tell.

On this page https://docs.mongodb.com/realm/ios/authenticate/#ios-login-apple
The line in the documentation "Fetch IDToken via the Apple SDK" is extremely vague, so likely I'm supplying the wrong information to the Credentials creation step.

## Code Sample
 ```
guard let appleIDCredential = authorization.credential as? ASAuthorizationAppleIDCredential else { return }
            
            print("apple user: " + appleIDCredential.user)//, appleIDCredential.fullName, appleIDCredential.email)
        
        let appleIDtoken = (appleIDCredential.identityToken?.base64EncodedString())!
        UserDefaults.group.set(appleIDtoken, forKey: "appleIDtoken")
        
        signIn(userCredentials: Credentials.apple( idToken: appleIDtoken ) )
```

Then
```
func signIn( userCredentials: Credentials ) {
        app.login(credentials: userCredentials) { result in
            DispatchQueue.main.sync {
                switch result {
                    case .failure(let error):
                        print("Login failed: \(error)");
                        self.errorLabel.text = "Login failed: \(error.localizedDescription)"
                        return
                    case .success(let user):
                        print("Successfully logged in as user \(user)")
```

## Version of Realm and Tooling
Realm framework version: 10.1.0

Xcode version: 12.2 beta 4

iOS/OSX version: 14.2

Dependency manager + version: cocoapods 1.10.0

**Comment by leemaguire** [comment]
Hi @FaultyJuggler 

Realm will do a lot of the heavy lifting for you with Apple Sign In. See our example here: 

https://github.com/realm/realm-cocoa/tree/master/examples/ios/swift/AppleAuthentication

Also make sure your bundle ID matches the client id you used in MongoDB Realm Cloud.

**Comment by FaultyJuggler** [comment]
@leemaguire  managed to figure it out, 
The example code really should clarify that the latest Realm version is expecting the JWT to be converted to a string in the following way:
`let appleIDtoken = String(data: appleIDCredential.identityToken!, encoding: .utf8)`

Once I got that, I was getting another vague error, which really should be more explicit that there was a client ID mismatch between JWT data and what was set within Realm authentication configuration within Atlas, the documentation in the tutorial made it confusing which ID to set as client ID.

But I'm fully online now.  Let me know how best to create a ticket for these two changes that should be put into the documentation and error message

**Comment by leemaguire** [comment]
@FaultyJuggler I'll file the issue on your behalf. Thanks for the feedback. If you're all good would you mind closing the ticket?

Thanks

**Comment by FaultyJuggler** [comment]
@leemaguire  certainly, thanks for following up early on a Monday!
