### ISSUE TITLE
Apple Sign In no longer working

### ISSUE THREAD

**Issue by FaultyJuggler** [realm/realm-cocoa#6954]
## Expected Results
Log in to Realm using Apple Sign In

## Actual Results
fails with error:
`Login failed: Error Domain=realm::app::ServiceError Code=2 "OAuth2 configuration consists of only clientId, clientSecret, and openId" UserInfo={NSLocalizedDescription=OAuth2 configuration consists of only clientId, clientSecret, and openId, realm::app::ServiceError=InvalidSession}`

## Steps for others to Reproduce
All apple sign in is failing with the same error, apple sign in with our app and realm was working the past few days just fine, no code changes to our login logic, I did have to terminate and start Sync again after it got a bad change state error

Realm framework version: 10.1.0

Realm Object Server version: ?

Xcode version: 12.2

iOS/OSX version: 14.2

Dependency manager + version: cocoapods 1.10.0

**Comment by theolampert** [comment]
Experiencing this as well. @FaultyJuggler do you know if downgrading fixes this?

**Comment by leemaguire** [comment]
I can reproduce the issue and we are looking into it now.

**Comment by leemaguire** [comment]
This looks to be resolved now.

**Comment by theolampert** [comment]
@leemaguire just confirmed here, looks resolved thank you!
