### ISSUE TITLE
Miss one or more architectures required by this target: arm64, x86_64.

### ISSUE THREAD

**Issue by rantianhua** [realm/realm-cocoa#6957]
## Goals

Use realm-cocoa in watchOS target through Carthage.
## Expected Results

I can use realm framework build through Carthage in watchOS target.
## Actual Results

```
error: The linked framework 'RealmSwift.framework' is missing one or more architectures required by this target: arm64, x86_64
```

## Steps for others to Reproduce

Use Carthage 0.36.0 to build realm 5.3.0 with the watchOS platform. Then link this framework in Xcode 12.2 to build.

## Version of Realm and Tooling

Realm framework version: ?
5.3.0
Realm Object Server version: ?
??
Xcode version: ?
12.2
iOS/OSX version: ?
Build settings from command line:

    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchos7.1
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

Dependency manager + version: ?
Carthage 0.36.0

**Comment by jsflax** [comment]
You'll have to upgrade to realm v10.1.4 for arm64 support.

**Comment by rantianhua** [comment]
@jsflax Another two questions:

1. Is v10.1.4 compatible with v5.3.0?
2. How about x86_64? Still not support in Xcode 12.2?

**Comment by ZComwiz** [comment]
@jsflax — When building the app on v10.1.4 for archiving to the app store the error occurs:

Umbrella header 'Realm.h' not found in module.map
and could not build Objective-C module 'Realm'

(latest version of cocoapods 1.10.0)

Already attempted to clear derivedData/build folder.

**Comment by leemaguire** [comment]
@ZComwiz I cannot reproduce on Xcode 12.2, Cocoapods 1.10 and Realm Swift 10.1.4, Are you able to reproduce the issue with a new test project?

**Comment by ZComwiz** [comment]
@leemaguire The fix for me was to move all Realm files from private to public when archiving the project.

**Comment by leemaguire** [comment]
@ZComwiz It's strange you had to do that. Another thing I could suggest is deleting the pods folder and doing a fresh `pod install`

**Comment by ZComwiz** [comment]
@leemaguire I suppose I should have mentioned that I did that already as well, but working on iOS and React Native apps for so long I just figured it was implied that one should try that first haha

**Comment by leemaguire** [comment]
@ZComwiz I can reproduce when archiving for Catalyst, good catch!

**Comment by JonnyBeeGod** [comment]
> @leemaguire The fix for me was to move all Realm files from private to public when archiving the project. 

Can you elaborate on how to do this? Running into similar issues here

**Comment by ZComwiz** [comment]
> > @leemaguire The fix for me was to move all Realm files from private to public when archiving the project.
> 
> Can you elaborate on how to do this? Running into similar issues here

Hi @JonnyBeeGod. So its a bit of a hack work around that only works for archiving the app, but will break your ability to run it in debug mode because of redundant module files being compiled so you will need to revert your changes by either reversing this or deleting pods and re `pod install`ing.

1. Navigate to Pods project file in XCode.
2. Find Realm in the targets list on the left hand side.
3. Navigate to Build Phases tab.
4. Move all the private header h files from private to public.
5. Do the same for RealmSwift framework if necessary.

**Comment by JonnyBeeGod** [comment]
> Hi @JonnyBeeGod. So its a bit of a hack work around that only works for archiving the app, but will break your ability to run it in debug mode because of redundant module files being compiled so you will need to revert your changes by either reversing this or deleting pods and re `pod install`ing.
> 
> 1. Navigate to Pods project file in XCode.
> 2. Find Realm in the targets list on the left hand side.
> 3. Navigate to Build Phases tab.
> 4. Move all the private header h files from private to public.
> 5. Do the same for RealmSwift framework if necessary.

Thank you. Unfortunately that did not solve my issues but it was worth a try ;)

**Comment by jsflax** [comment]
@rantianhua can you confirm that this is still an issue?

@JonnyBeeGod you as well? We find that most Cocoapods issues are due to a bad cache.

**Comment by JonnyBeeGod** [comment]
It did not in my case I was cleaning pods folder and cocoa pods cache before my builds. Found the solution to my problem however in another issue somewhere. I had a private pod A with realmswift and realm as dependencies. When I used this pod as dependency in another pod B I was having those linker issues. The solution was to add realm as dependency to pod B podspec as well.
