### ISSUE TITLE
build.sh xcframework failing to link for Catalyst

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-cocoa#6960]
## Goals
I would like to compile the library into an `xcframework` containing the libraries for `ios-swift` and `catalyst-swift`.

## Expected Results
`build.sh` should create a `xcframework` with the libraries described above.

## Actual Results

Crash when compiling using Xcode 12:

<img width="700" alt="Screenshot 2020-11-26 at 14 09 21" src="https://user-images.githubusercontent.com/5521682/100360616-0c9a6180-2ff1-11eb-9781-2d99f2217115.png">

## Steps for others to Reproduce

Clone the project, sync the code (submodule) and run `./build.sh xcframework`.

## Code Sample

Not applicable.

## Version of Realm and Tooling

Realm framework version: 10.1.4

Realm Object Server version: ?

Xcode version: 12.2

iOS/OSX version: ?

Dependency manager + version: Submodules (all in sync)

### Additional question:

The documentation in the `build.sh` file says that I can call `build.sh xcframework [plats]` but I am not sure how to use it. Analysing the code I can't find any line that reads the arguments from `[plats]`, is that right? I would like to create the `xcframework` only for `ios` and `catalyst`.

**Comment by leemaguire** [comment]
@ppamorim you should use `./build.sh xcframework ios catalyst` to build for just iOS and Catalyst.

**Comment by ppamorim** [comment]
I tried to compile the library twice, one framework for `iOS` and another for `Catalyst`:

<img width="762" alt="Screenshot 2020-11-26 at 14 51 53" src="https://user-images.githubusercontent.com/5521682/100365131-fa232680-2ff6-11eb-88cd-4d44ef20d65e.png">

But I am getting this error when compiling the Catalyst project:

`.../ios/Realm.framework/Headers/RLMPlatform.h:32:2: Attempting to use Realm's iOS framework in a non-iOS target.`

<img width="461" alt="Screenshot 2020-11-26 at 14 50 33" src="https://user-images.githubusercontent.com/5521682/100365078-e4adfc80-2ff6-11eb-9a6d-8ef70357284a.png">

**Comment by ppamorim** [comment]
@leemaguire I am trying to compile it again with your command.

**Comment by leemaguire** [comment]
I do see an issue here related to how Catalyst uses macOS style versioned frameworks

**Comment by ppamorim** [comment]
@leemaguire Same issue with your command: 

<img width="700" alt="Screenshot 2020-11-26 at 14 58 15" src="https://user-images.githubusercontent.com/5521682/100365795-da403280-2ff7-11eb-9854-8a4f36ef91a2.png">
