### ISSUE TITLE
Crash happens when use login(credentials): "[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]"

### ISSUE THREAD

**Issue by zyphs21** [realm/realm-cocoa#6965]
## Goals
I would like to Login to a user for the Realm. 

## Expected Results
Login success

## Actual Results

It crash ！

```
"*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]"
```

![image](https://user-images.githubusercontent.com/4511324/100714958-7780d980-33f1-11eb-81b7-541e6a9b501e.png)

in 

```
NSError *RLMAppErrorToNSError(realm::app::AppError const& appError) {
    return [[NSError alloc] initWithDomain:@(appError.error_code.category().name())
                                      code:appError.error_code.value()
                                  userInfo:@{
                                      @(appError.error_code.category().name()) : @(appError.error_code.message().data()),
                                      NSLocalizedDescriptionKey : @(appError.message.c_str())
                                  }];
}
```

from

```
- (void)loginWithCredential:(RLMCredentials *)credentials
                 completion:(RLMUserCompletionBlock)completionHandler {
    auto completion = ^(std::shared_ptr<SyncUser> user, util::Optional<app::AppError> error) {
        if (error && error->error_code) {
            return completionHandler(nil, RLMAppErrorToNSError(*error));
        }

        completionHandler([[RLMUser alloc] initWithUser:user app:self], nil);
    };
    return RLMTranslateError([&] {
        return _app->log_in_with_credentials(credentials.appCredentials, completion);
    });
}
```

The code below is not safe:
```
@{@(appError.error_code.category().name()) : @(appError.error_code.message().data()),
     NSLocalizedDescriptionKey : @(appError.message.c_str())
}
```

## Steps for others to Reproduce

I think it happens when the user haven't Allow the WLAN& Cellular, because at that time, the network connection is not working. 

![IMG_0047](https://user-images.githubusercontent.com/4511324/100716675-fbd45c00-33f3-11eb-9c8b-224f5ef497d8.jpg)

## Code Sample

 Here is my login code:

```
let anonymousCredentials = Credentials.anonymous
app.login(credentials: anonymousCredentials) { (result) in
    switch result {
       case .failure(let error):
            print(error)
       case .success(let user):
           reamlConfig = user.configuration(partitionValue: _partitionId)
       }
}
```

## Version of Realm and Tooling

Realm framework version: 10.1.4

Realm Object Server version: ?

Xcode version: 12.2

iOS/OSX version: iOS 13.5.1

Dependency manager + version: ?

**Comment by pavel-ship-it** [comment]
Hi @zyphs21 ,
Is there any chance to have an error value you're passing to RLMAppErrorToNSError?

**Comment by zyphs21** [comment]
Hello @pavel-ship-it, 
I have checked my code, and I only simply call the `login(credentials:)` function.

**Comment by DominicFrei** [comment]
@zyphs21 I tried to reproduce this on my side but I could not.
Can you provide a small example app? Or provide some introspection on `appError`?

**Comment by zyphs21** [comment]
@DominicFrei  Hello, thanks for your replying.

The crash exception is :
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', 
reason: 
'*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
```

The problem code in `RLMApp.mm Line 213-216`:
https://github.com/realm/realm-cocoa/blob/a4d1342a43b5ea4ccb0586d37d48197bdbc1d8a1/Realm/RLMApp.mm#L213-L216

It is **not a safe way**  to create an NSDictionary like that. If `appError.message.c_str()` is nil it will crash.

**Comment by pavel-ship-it** [comment]
Hi @zyphs21 ,
Thank you for posting the issue here. I have a fix for it. It will be available in the upcoming releases.
Problem was with the appError value - it wasn't initialised and therefore dictionary initialisation has failed.
