### ISSUE TITLE
[crash] mutex lock failed: Invalid argument

### ISSUE THREAD

**Issue by rogerluan** [realm/realm-cocoa#6966]
## Goals

Unit test objects CRUD in a background queue.

## Expected Results

CRUD should work without throwing exceptions.

## Actual Results

Fun Fact Number 1: I get thrown the following exception **sometimes** (which's the tricky part). About 10-30% of the time I'd say.

>Terminating app due to uncaught exception 'RLMException', reason: 'mutex lock failed: Invalid argument'

Fun Fact Number 2: Sometimes this crash is thrown and I can't recover from it (my tests actually crash). Sometimes it's caught by my `do { } catch { }` - not sure what drives this different behavior (my tests finish without crashing, but fail due to the caught unexpected exception).

Fun Fact Number 3: The stacktrace is different (there're at least 3 different places where it crashes from).

#### Stacktrace 1 (`realm.deinit`)

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/8419048/100771860-abea9a80-33dd-11eb-9c3e-9ea54a9ce4c1.png">

#### Stacktrace 2 (`realm.add(_:update)`)

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/8419048/100773425-9f674180-33df-11eb-8704-2eb1674b51ac.png">

#### Stacktrace 3 (`realm.object(ofType:forPrimaryKey:)`)

// Couldn't capture (hard to reproduce)

## Steps for others to Reproduce

Run a unit test that either adds an object to realm or fetches object by PK, in a background queue.
I tried adding/removing `Realm().refresh()` before and after executing such task. I tried wrapping the task around `autoreleasepool` and also tried without wrapping it.

I read these issues: 
https://github.com/realm/realm-cocoa/issues/4702 - no help
https://github.com/realm/realm-cocoa/issues/6860 - not a JS project, code is in pure Swift using SPM
https://github.com/realm/realm-cocoa/issues/6686 - this issue wasn't resolved yet. All they said was like "we released a new major version, please re-test and report" 😕 Well I tested in v5.3.5, v5.5.0 and v10.1.4, and still no luck 😞 

## Code Sample

This is my Realm API wrapper class:

```swift
public final class ZLRealm {
    static let realmQueue = DispatchQueue(label: "ZLRealm.realmQueue", qos: .userInitiated)
    private let callbackQueue = DispatchQueue.main

    /// Executes the given work closure within the Realm serial queue, and invoke the completion handler upon completion.
    /// If the work closure throws, the exception is caught and returned as a failure result in the completion handler.
    ///
    /// - Parameters:
    ///   - work: the work closure to be executed.
    ///   - completion: the completion handler to be executed once the work completes.
    func execute<T>(_ work: @escaping () throws -> T, completion: @escaping ((Result<T, Error>) -> Void)) {
        Self.realmQueue.async { [callbackQueue] in
            do {
//                try autoreleasepool {
//                    try Realm().refresh()
                    let product = try work()
                callbackQueue.async {
                        completion(.success(product))
                    }
//                }
            } catch {
                callbackQueue.async {
                    completion(.failure(error))
                }
            }
        }
    }
```

We have this utility:
```swift
extension Realm {
    public func transactionUnlessNested<T>(_ transaction: () throws -> T) rethrows -> T {
        if isInWriteTransaction {
            return try transaction()
        } else {
            beginWrite()
            defer { try? commitWrite(withoutNotifying: []) }  // Also execute in case of an error
            return try transaction()
        }
    }
}
```

And our code crashes when `work` contains one of these scenarios:

```swift
let realm = try Realm()
let realmObject: MyRealmClass = …
realm.transactionUnlessNested {
    realm.add(realmObject, update: .all) // Exception thrown here ❗️
}
```
```swift
let realm = try Realm()
let realmObjects: [MyRealmClass] = …
realm.transactionUnlessNested {
    realm.add(realmObjects, update: .all) // Exception thrown here❗️
}
```
```swift
let realm = try Realm()
realm.object(ofType: MyRealmClass.self, forPrimaryKey: aPrimaryKey) // Exception thrown here❗️
```

## Version of Realm and Tooling

Realm framework version: I tried on v5.3.5, v5.5.0 and v10.1.4.

Realm Object Server version: 🤷‍♀️

Xcode version: Version 12.0 (12A7209)

iOS/OSX version: macOS 10.15.7

Dependency manager + version: Added Realm via SPM, running Swift 5.3 on Xcode 12

**Comment by pavel-ship-it** [comment]
Hi @rogerluan,
I cannot reproduce it with the provided information. Can you share the details of configuration and schema?
Is it possible to squeeze the minimum reproducible code out of your project?
 
regarding fact 2 - it depends on what part of code it's raised - you can catch Swift errors but Cpp level errors will crash.

**Comment by rogerluan** [comment]
This issue has been resolved!

The problem is that I was running async code in purely sync unit tests (i.e. without using `expectations`)! Shame on me.

For future readers, [this](https://www.swiftbysundell.com/articles/unit-testing-asynchronous-swift-code/) and [this](https://www.swiftbysundell.com/articles/asyncawait-in-swift-unit-tests/) guides helped me! 

Hope this helps someone out there! 

Thanks for jumping in @pavel-ship-it 😊 

Closing.
