### ISSUE TITLE
Build script does not create module for the arm64 simulator

### ISSUE THREAD

**Issue by FelixII** [realm/realm-cocoa#6968]
## Goals

I want to build Realm as a precompiled framework, embed it into an iOS app and run it in the simulator.

**Important:** I'm using a M1 MacBook Air and therefore need to compile code for the arm64 simulator.

## Expected Results

Xcode compiles the app with Realm as an embedded binary.

## Actual Results

Xcode compilation fails with the following error message:

`Module 'RealmSwift' was created for incompatible target arm64-apple-ios9.0: /Users/<user>/Developer/realm-cocoa/build/ios/swift-12.2/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule`

## Steps for others to Reproduce
You need an Apple Silicon Mac to reproduce this issue.

1. Compile Realm for iOS: `./build.sh ios-swift`
2. Create a new iOS project
3. Add `Realm` and `RealmSwift` as an embedded binary and to the framework search paths
4. Add `import RealmSwift` to your `ViewController.swift`
5. Select an iOS simulator as the run target and build the app

## Version of Realm and Tooling

Realm framework version: 10.1.4

Xcode version: 12.2

iOS/OSX version: 14.2

## Notes

* Realm integration works fine with CocoaPods. I would prefer to integrate Realm as a precompiled framework to accelerate local build and CI compilation time.
* The `RealmSwift.framework` from CocoaPods contains `swiftdoc` and`swiftmodule` files for `arm64` and `arm64-apple-ios-simulator`. The precompiled framework contains module files for `arm`, `arm64` and `arm64-apple-ios` but is missing the arm64 simulator.
* I've noticed that the Realm project has configured `arm64` as an excluded architecture for the iOS simulator. I've tried to remove this setting, but that causes the Realm build script to fail with the following error message:

`fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: build/DerivedData/Realm/Build/Products/Release-iphonesimulator/Realm.framework/Realm and build/DerivedData/Realm/Build/Products/Release-iphoneos/Realm.framework/Realm have the same architectures (arm64) and can't be in the same fat output file`

* I receive a similar compiler error for the watchOS simulator (same steps to reproduce):
`error: The linked and embedded framework 'RealmSwift.framework' is missing one or more architectures required by this target: arm64.`
I assume this issue in already covered in #6957 

## Related Issues

* #6785 (Same error message with CocoaPods)
* #6822 (Same error message with Carthage)

**Comment by tgoyne** [comment]
A fat framework cannot contain both arm64-for-simulator and arm64-for-device slices because the file format only distinguishes on architecture and not the platform, so they're both just "arm64". Instead you have to use a xcframework, which can be built with `sh build.sh xcframework ios`. Currently the xcframework build is a bit weird and different, but https://github.com/realm/realm-cocoa/pull/6964 will resolve that and hopefully will be released today.

**Comment by FelixII** [comment]
Thanks for your quick response. I've compiled the new Realm version 10.2.0 with `./build.sh xcframework ios` and also tried the precompiled binaries from GitHub. In both cases I get the following error message when building my project for the arm64 simulator:

`Could not find module 'RealmSwift' for target 'arm64-apple-ios-simulator'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator`

Is there anything else I need to configure or is the arm64 simulator slice still missing in the new release?

**Comment by FelixII** [comment]
If you want me to try something, please let me know. I'm happy to help.

**Comment by FelixII** [comment]
I think I've found the cause of this issue. The latest Realm version still defines `arm64` as an excluded architecture for the iOS simulator:

https://github.com/realm/realm-cocoa/blob/af4b201bb955736f250f5af1c1b6bc335a43c385/Configuration/Base.xcconfig#L65

I've removed this value and rebuilt with `./build.sh xcframework ios`. The `arm64-apple-ios-simulator` slice is now present and my example project builds successfully! 👍

**Comment by FelixII** [comment]
I've found another minor issue with the build script: It does not accept more than three input parameters:

https://github.com/realm/realm-cocoa/blob/7a812029d05890f35501dcbcb00f346ac196a7d9/build.sh#L282-L285

This prevents calls like `./build.sh xcframework ios watchos tvos catalyst`

**Comment by FelixII** [comment]
The latest Realm version 10.4.0 has fixed the `arm64` compiler issue. Thank you!
