### ISSUE TITLE
LinkingObjects function does not autocomplete in XCode

### ISSUE THREAD

**Issue by visdyn** [realm/realm-cocoa#6970]
## Goals
When typing LinkingObjects in XCode it should autocomplete

## Expected Results
LinkingObjects should autocomplete

## Actual Results
LinkingObjects does not autocomplete

## Steps for others to Reproduce
In a RealmSwift project in XCode 11 or 12, type in

let someObject = LinkingObjects(

and let the popup autocomplete window appear

## Code Sample

<img width="627" alt="LinkingObjects 1" src="https://user-images.githubusercontent.com/19558530/100921186-326cae00-34aa-11eb-9e5c-7cbb10a989a5.png">

<img width="949" alt="Linking Objects 2" src="https://user-images.githubusercontent.com/19558530/100921196-3698cb80-34aa-11eb-9d19-f8bf6cb2f42e.png">

## Version of Realm and Tooling
RealmSwift 10.1.4
XCode 11 or 12
macOS 10.14 or 10.15

**Comment by tgoyne** [comment]
This is something you should report to Apple. We do not have any influence on autocomplete.

**Comment by visdyn** [comment]
You would think so, right? However, with RealmSwift 5.3.3 it works (and actually has worked up until v10, correctly. Here's a screen shot from a project with RealmSwift 5.3.3

<img width="522" alt="LinkingObjects 5 3 3" src="https://user-images.githubusercontent.com/19558530/100926390-5f708f00-34b1-11eb-99e5-fb4b52a91098.png">

**Comment by visdyn** [comment]
Ah, I see the reason. The definition changed from

`public struct LinkingObjects<Element: Object> {`

to 

`@frozen public struct LinkingObjects<Element: ObjectBase> where Element: RealmCollectionValue {`

**Comment by AbdallahShaqrah** [comment]
> Ah, I see the reason. The definition changed from
> 
> `public struct LinkingObjects<Element: Object> {`
> 
> to
> 
> `@frozen public struct LinkingObjects<Element: ObjectBase> where Element: RealmCollectionValue {`

so what should I do

**Comment by visdyn** [comment]
@AbdallahShaqrah

What should you do about what?

Since that post about two years ago, LinkingObjects has changed so when adding LinkingObjects as a property to a class, it would now look like this

`@Persisted(originProperty: "dogs") var linkedPersons: LinkingObjects<Person>`

where the Person object as a `List` property of `dogs`.

So there is really no longer any autocomplete on LinkingObjects because all of that has to be manually typed anyway.
