### ISSUE TITLE
Property Parent.child is declared as Optional<Child>, which is not a supported managed Object property type

### ISSUE THREAD

**Issue by aphex3k** [realm/realm-cocoa#6978]
## Goals

I want to use my realm objects and RealmDatabase in XCode unit tests.

## Expected Results

Realm database should work as documented.

## Actual Results

    /Pods/RealmSwift/RealmSwift/Object.swift:749: error: -[appTests.RealmTests testRealm] : failed:
    caught "RLMException", "Property Parent.child is declared as Optional<Child>, which is not a supported
    managed Object property type. If it is not supposed to be a managed property, either add it to
    `ignoredProperties()` or do not declare it as `@objc dynamic`. See
    https://realm.io/docs/swift/latest/api/Classes/Object.html for more information."

## Steps for others to Reproduce

    //
    //  Child.swift
    //
    class Child: Object {
        let graduated = RealmOptional<Bool>()
    }

&nbsp;

    //
    //  Parent.swift
    //
    class Parent: Object {
        @objc dynamic var child: Child?
    }

I am adding RealmDatabase to an iOS app project. The framework is installed via cocoapods. I want to unit test my code but I get the error listed above.

I can not provide the entire repository (private repo) but I pasted my XCTestCase subclass below.

## Code Sample

    //
    //  RealmTests.swift
    //

    import XCTest
    import RealmSwift
    @testable import App

    class RealmTests: XCTestCase {

        override func setUpWithError() throws {

            Realm.Configuration.defaultConfiguration.inMemoryIdentifier = self.name
            Realm.Configuration.defaultConfiguration.objectTypes = [
                Parent.self,
                Child.self
            ]

            let realm = try! Realm(configuration: Realm.Configuration.defaultConfiguration)
        }

        func testRealm() throws {

            assert(true)
        }
    }

## Version of Realm and Tooling

- Realm 10.2.0
- RealmSwift 10.2.0
- Xcode version: 11.7
- iOS 13.7 (Simulator)

### Podfile

    source 'https://github.com/CocoaPods/Specs.git'
    source 'https://github.com/goinstant/pods-specs-public'

    # Uncomment this line to define a global platform for your project
    platform :ios, '12.4'

    target 'app' do
      # Uncomment this line if you're using Swift or would like to use dynamic frameworks
      # use_frameworks!

      # Pods for app

      # https://realm.io/docs/swift/latest/
      pod 'Realm', '~> 10.2.0', :modular_headers => true
      pod 'RealmSwift', '~> 10.2.0'

      target 'appTests' do
          # Uncomment this line if you're using Swift or would like to use dynamic frameworks
          # use_frameworks!

          # https://realm.io/docs/swift/latest/
          pod 'Realm', '~> 10.2.0', :modular_headers => true
          pod 'RealmSwift', '~> 10.2.0'
      end
    end

**Comment by tgoyne** [comment]
You're statically linking Realm into both your app and your tests. This results in two separate copies of Realm in your process at runtime, and subclasses of the app's copy of RealmSwift.Object can't be used with the test's copy of RealmSwift.

The simplest fix for this is to uncomment use_frameworks! so that it's dynamically linked and you don't duplicate the library by linking it into multiple targets.

**Comment by aphex3k** [comment]
> The simplest fix for this is to uncomment use_frameworks! so that it's dynamically linked and you don't duplicate the library by linking it into multiple targets.

`use_frameworks!` for the app and the tests target or only one of them? (which one?)

**Comment by tgoyne** [comment]
Unless you have some reason you specifically want to avoid dynamic frameworks, setting it at the top level of the podfile will result in the least amount of surprising behavior. It's something that really should be the default now but CocoaPods hasn't made a major version bump since that became the case.

**Comment by aphex3k** [comment]
Thanks for pointing that out. I wasn't looking outward enough I guess.
