### ISSUE TITLE
Unable to Compile with Realm v10.0+ via Cocoapods (v1.10)

### ISSUE THREAD

**Issue by Suri1044** [realm/realm-cocoa#6979]
**Bugs**: Unable to Compile with Realm v10.0+ via Cocoapods (v1.10)

## Goals
Realm version(10.2.0) is not compiling. Migrating from (5.3.2 to latest 10.2.0)

## Expected Results
Compilation success 

## Actual Results
Error: 
**Instance method 'objects' requires that 'ObjectBase' (aka 'RLMObjectBase') inherit from 'Object' (aka 'RealmSwiftObject')**

## Steps for others to Reproduce
Added sample code below with screenshot as well (*Instance method 'objects' requires that 'ObjectBase' (aka 'RLMObjectBase') inherit from 'Object' (aka 'RealmSwiftObject')).

## Code Sample

do {
                let realmIdentifier = Settings.shared.infoPlistSettings.myAccountSettings.realmIdentifier
                let realm = try Realm(configuration: Realm.Configuration(inMemoryIdentifier: realmIdentifier))
                let keepObjectTypes: [Object.Type] = [
                    ModelClass.self
                ]
                try realm.write {
                    realm.configuration.objectTypes?.filter({ type -> Bool in
                        return !keepObjectTypes.contains { $0 == type }
                    }).forEach({ type in
                       //  The below line is not compiling. Error description: **Instance method 'objects' requires that 'ObjectBase' (aka 'RLMObjectBase') inherit from 'Object' (aka 'RealmSwiftObject')**

                        realm.delete(realm.objects(type))

                    })
                }
            } catch let error {
                print("Error clearing Realm while switching accounts: ", error.localizedDescription)
            }

<img width="889" alt="Screenshot 2020-12-07 at 7 12 47 PM" src="https://user-images.githubusercontent.com/68360396/101357982-3e98a700-38c0-11eb-9619-caf88c46b1d4.png">

## Version of Realm and Tooling

Realm framework version: ? current 5.3.2 attempting for 10.2.0

Xcode version: ? 12.2

macOS version:? 10.15.7 (Catalina)

iOS/OSX version:  N/A (though min target 11.2)

Dependency manager + version: ? cocoapods v1.10

**Comment by tgoyne** [comment]
Only subclasses of Object can be deleted via realm.delete(), but the objectTypes array can also contain subclasses of EmbeddedObject. You'll want to add `.compactMap { $0 as? Object }` before forEach().

**Comment by Suri1044** [comment]
@tgoyne : Thanks for the info and it works. May i know why this issue didn't occur in v5.3.2 or before ones?

**Comment by drinkius** [comment]
Got an error here:
`Cast from 'ObjectBase.Type' (aka 'RLMObjectBase.Type') to unrelated type 'Object' (aka 'RealmSwiftObject') always fails`

**Comment by thanhdolong** [comment]
> Got an error here:
> `Cast from 'ObjectBase.Type' (aka 'RLMObjectBase.Type') to unrelated type 'Object' (aka 'RealmSwiftObject') always fails`

This one should work:
``.compactMap { $0 as? Object.Type }`` or ``guard let objectType = objectType as? Object.Type else { return }``

**Comment by jsflax** [comment]
Closing this out since the question has been answered.
