### ISSUE TITLE
Related to mac catalyst

### ISSUE THREAD

**Issue by sakthi-d** [realm/realm-cocoa#6989]
Followed the ticket [https://github.com/realm/realm-cocoa/issues/6163](#6163) to support mac catalyst. 
And I preferred getting xcframework and embedded in my app. I'm still getting the issue saying

"While building for Mac Catalyst, no library for this platform was found in 'Realm.xcframework'"

Note : Built them using XCode 11.3.1

Thanks in advance.

**Comment by jsflax** [comment]
Hey @sakthi-d,

Could provide us with more information on how you copied over the xcframeworks?

Please check https://realm.io/docs/swift/latest/ for further instructions.

**Comment by sakthi-d** [comment]
hey @jsflax ,

never mind about my issue. I've configured to package manager(which seems to be very smooth). 

Thank you
