### ISSUE TITLE
RealmOptional properties fail to be decoded if the key is not present

### ISSUE THREAD

**Issue by rogerluan** [realm/realm-cocoa#6991]
## Goals
I'd like to use make a realm model that has a `RealmOptional` property conform to Codable, and properly encode/decode properties in all scenarios.

## Expected Results
I expected my object to be encodable and decodable when the key:value pairs are present, existing, or null, in a JSON structure.

## Actual Results
Scenario 1: It works when the `RealmOptional` value is present.
Scenario 2: It works when the `RealmOptional` value is `null`.
Scenario 3: It does not work when the `RealmOptional` is not present.

## Steps for others to Reproduce

<details><summary>Scenario 1 (it works)</summary>
<p>

Given the class:
```swift
class MyObject : Object, Decodable {
    dynamic var myOptional = RealmOptional<Double>()
}
```

And the following JSON:

```js
{
    "myOptional" : 42.42
}
```

Decoding the JSON into `MyObject.self` works as expected.

</p>
</details>

<details><summary>Scenario 2 (it works)</summary>
<p>

Given the class:
```swift
class MyObject : Object, Decodable {
    dynamic var myOptional = RealmOptional<Double>()
}
```

And the following JSON:

```js
{
    "myOptional" : null
}
```

Decoding the JSON into `MyObject.self` works as expected.

</p>
</details>
 
<details><summary>Scenario 3 (it doesn't work)</summary>
<p>

Given the class:
```swift
class MyObject : Object, Decodable {
    dynamic var myOptional = RealmOptional<Double>()
}
```

And the following JSON:

```js
{
}
```

Decoding the JSON into `MyObject.self` fails, because the key cannot be found.

</p>
</details>

## Code Sample
Code samples are located in the section below.

## Version of Realm and Tooling

Realm framework version: 10.3.0

Realm Object Server version: idk

Xcode version: 12.2

iOS/OSX version: macOS 10.15.7

Dependency manager + version: SPM

## Further Details

This issue was already raised over 3 years ago here: https://github.com/realm/realm-cocoa/issues/5012#issuecomment-326252157
I read that entire thread and the issue I'm referring to doesn't seem to have a closure. I checked [this code](https://gist.github.com/mishagray/9a595806a15dca07ad6a9fd5867bf0ff) posted [here](https://github.com/realm/realm-cocoa/issues/5012#issuecomment-343982132) but that seemed to be an overkill to solve the problem. Maybe 3.5 years later there's a better solution.

**Comment by jsflax** [comment]
@rogerluan this does seem to be a bug. We'll investigate.

**Comment by rogerluan** [comment]
For anyone facing the same problem, as a workaround, I was able to use `String?` instead of e.g. `RealmOptional<Double>` and convert the Double to String when encoding/decoding. However, this is not possible if you need to make number-based queries (e.g. "sum of X property of all Y models").

**Comment by DominicFrei** [comment]
@rogerluan Thank you for providing those details. This is something we will most likely be tackling when working on PropertyWrappers.

As of now, apart from the already stated workarounds (custom `CodingKeys` and `init`, your `String?`, etc.) I prepared a solution that lets you keep using `RealmOptional` with a small extension of `JSONDecoder`:
https://github.com/DominicFrei/Playground/blob/realm/realm-cocoa/issues/6991/Tests/PlaygroundTests/PlaygroundTests.swift

The only adjustment you would need to make to your code would be the additional `allowMissingKeys` parameter in the `decode` call on `JSONDecoder`:
```try JSONDecoder().decode(CodableObject.self, from: Data(jsonString.utf8), allowMissingKeys: true)```

Does this solve your problem for now?

**Comment by rogerluan** [comment]
@DominicFrei thanks for your reply and for providing a solution. However, unfortunately that solution won't work in my project, because Realm is abstracted away from the decoding logic, so I couldn't constrain `where T : RealmSwift.Object` for instance. It's a creative solution, thanks for that, but there's no real gain over what I currently have (since I don't _need_ the values to be `Double`, because I don't query on their numeric values). It would just be a lot better if I could not parse to/from `String?`, but I can live with it for now 😅

**Comment by DominicFrei** [comment]
@rogerluan Thank you for the feedback. Good to hear you have a solution for now. As soon as #7044 is fixed, this issue should be fixed as well.

**Comment by rogerluan** [comment]
Property wrapper support has been added as of https://github.com/realm/realm-cocoa/releases/tag/v10.10.0
