### ISSUE TITLE
Compile warning: RLMUser_Private.h

### ISSUE THREAD

**Issue by marinofaggiana** [realm/realm-cocoa#6995]
Realm 10.4.0
XCode 12.2
Build with SPM
--------------

Several Swift compile warning

Umbrella header for module 'Realm' does not include header 'RLMUser_Private.h'

**Comment by jsflax** [comment]
@marinofaggiana is this a warning or an error?

**Comment by marinofaggiana** [comment]
> Several Swift compile warning

**Comment by jsflax** [comment]
@marinofaggiana this will have gone away in the latest Realm release. Can you test and confirm?

**Comment by marinofaggiana** [comment]
Hi @jsflax seems be fixed with the 10.5.0 Thanks
