### ISSUE TITLE
“RealmSwift.framework” cannot be opened because the developer cannot be verified 

### ISSUE THREAD

**Issue by 3a4oT** [realm/realm-cocoa#7003]
I tried to use Relm and RealmSwift as `.xcframework` for macCatalyst.
App builds just fine, but on the launch, I get `“RealmSwift.framework” cannot be opened because the developer cannot be verified ` (for Realm too). `embedded and sign` option is set at Xcode project settings.

## Version of Realm and Tooling

Realm framework version: 10.4.0

Xcode version: 12.2

iOS/OSX version: macOS 10.5.6

**Comment by jsflax** [comment]
This appears to be an Xcode bug, as running the app not via Xcode works.

If you run
`xattr -d -r com.apple.quarantine <my-directory>/Realm.xcframework `
and
`xattr -d -r com.apple.quarantine <my-directory>/RealmSwift.xcframework `
on your downloaded and linked xcframeworks, you will be able to run the app without receiving any errors or warnings.

Could you test this out and close the issue if you find this solution sufficient?

**Comment by 3a4oT** [comment]
@jsflax thanks! That did the trick.

**Comment by timothycosta** [comment]
I'm using the objective c version of realm still. I had to run `xattr` on each `framework` under the `xcframework` directory before I could launch.
