### ISSUE TITLE
Collection notifications incorrect for insertions on Mac Catalyst and Simulator

### ISSUE THREAD

**Issue by alexeichhorn** [realm/realm-cocoa#7014]
The collection notification feature of Realm, which many rely upon, has some serious inconsistency issues when adding a lot of items (more than 6 in my experience) at the same time. The problem seems only to surface when running it on my Mac directly - that is Mac Catalyst or iOS Simulator. When running on an iOS device, the problem doesn't appear. Maybe it's an x86 issue, therefore. 

## Goals
Observe a Realm collection for insertions and get always a correct notification.
Especially when I have an empty collection and add 10 items. Few seconds later add another 10 items, the newly added 10 items should be fully reported by the notification block and no items of the previous insertion should be reported. (See Code Samples for more details)

## Expected Results
On the second insertion (of 10 items) the inserted items reported by the notification are exactly all the items just inserted.
In the code sample the output should be (similar to this):
```
added items: [2, 3, 8, 6, 1, 7, 9, 0, 5, 4]
added items: [12, 13, 18, 16, 11, 15, 14, 19, 10, 17]
```

## Actual Results
The second insertion notification contains 10 items, but when accessing the reported indexes, the item below are sometimes duplicated or items, that were inserted before.
In the code sample the output when running in iOS Simulator or Mac Catalyst (x86):
```
added items: [2, 3, 8, 6, 1, 7, 9, 0, 5, 4]
added items: [2, 3, 8, 16, 18, 5, 14, 14, 10, 15]
```

## Steps for others to Reproduce
- Create iOS application and add Realm as SPM package
- Create a small Realm Model:
```
class TestModel: Object {
    @objc dynamic var id = UUID().uuidString
    @objc dynamic var number: Int = 0
    
    override class func primaryKey() -> String? {
        "id"
    }
}
```
- Add an observation block of the newly created collection, which instantly reads out the items property:
```
notificationToken = realm.objects(TestModel.self).observe { changes in
    switch changes {
    case .update(let items, _, let insertions, _):
        print("added items: \(insertions.map { items[$0].number })")
        
    default: break
    }
}
```
- Insert two batches of (for example) 10 items with a time difference:
```
DispatchQueue.main.asyncAfter(deadline: .now() + 3.0) {
            
    let newObjects: [TestModel] = (0..<10).map {
        let item = TestModel()
        item.number = $0
        return item
    }
    
    let realm = try! Realm()
    
    try! realm.write {
        realm.add(newObjects)
    }
    
}


DispatchQueue.main.asyncAfter(deadline: .now() + 6.0) {
    
    let newObjects: [TestModel] = (10..<20).map {
        let item = TestModel()
        item.number = $0
        return item
    }
    
    let realm = try! Realm()
    
    try! realm.write {
        realm.add(newObjects)
    }
    
}
```

## Code Sample
Sample project with code listed above combined into a iOS project: https://github.com/alexeichhorn/RealmNotificationBug

## Version of Realm and Tooling

Realm framework version: 10.5

Xcode version: 12.3

iOS/OSX version: tested on 14.3 and 13.3 Simulator and on macOS 10.15.7 in Catalyst mode (x86 used everywhere)

Dependency manager + version: SPM

**Comment by DominicFrei** [comment]
Hi @alexeichhorn,

Thank you for providing all the information above including a code sample.

I have looked into the code example and did some tests on my own. I did find some occasions where duplicates appear.
While further analysing needs to be done here on our side, can you try to use a custom queue as an interim solution and check out if that works?

In the meantime we'll look further into that.

@tgoyne Do you have some additional insights on this for us?

Thanks,
Dominic

**Comment by tgoyne** [comment]
This looks like it's actually a bug in indexing a Results which directly wraps a Table with no filter or sort involved which is retained over multiple writes rather than incorrect notification results.

**Comment by alexeichhorn** [comment]
Thanks to all of you
