### ISSUE TITLE
Bad Changeset (Download)

### ISSUE THREAD

**Issue by michaeljajou** [realm/realm-cocoa#7023]
**SDK**: Realm Swift 10.5.0
**Xcode Version**: 12.3

**Error message:** Error Domain=io.realm.sync Code=112 "Bad changeset (DOWNLOAD)" UserInfo={Category=realm::sync::Client::Error, NSLocalizedDescription=Bad changeset (DOWNLOAD), Error Code=112}
Bad changeset (DOWNLOAD)

**Result of Error**
 After receiving this error, it seems that sync is prevented from running and all realm files are not able to be opened. I have tried deleting the app from the device, wiping all realm data from the device, and rebooting the device and the error still happens, preventing any realm files from opening. I have also tried reinitializing sync, terminating it, and enabling it again.

**Steps to Reproduce**
I added a new collection to Realm and wrote a schema for it. After implementing that schema in the iOS App, this error presented itself.

**Additional Information**
I've looked online about this error, and have found that some other people have experienced it as well. I remember seeing this error about 3 days ago, and after a while it just stopped happening. Some have said this is due to a mismatch of schemas on the client and the server, yet my schemas are an exact match. I also switched to a previous version where realm was syncing perfectly fine, but this error was presented there again.

**Comment by michaeljajou** [comment]
**More Information**

I removed all new schema configurations that were added, and I dropped their collections from the cluster. Then I terminated sync and reenabled it. Unfortunately, none of these steps fixed the issue.

**Comment by DominicFrei** [comment]
Hi @michaeljajou !

Thank you for the information above.

Would you be able to show us a code example that reproduces the above problem so that we can reproduce it on our end?

Thanks!

Kind regards,
Dominic

**Comment by michaeljajou** [comment]
@DominicFrei Thanks for the response. The problem is I do not have a code snippet I can add in that reproduces the problem. This problem occurred after I added a collection to my schema, and inputted the automatically generated Swift models from Realm. 

As mentioned above, it seemed to have broken my realm sync process because I removed all new collections and code (essentially putting everything back to a point where realm was working fine again) yet this error still persists.

**Comment by michaeljajou** [comment]
The initial error message was:

**The client and server disagree about the history. Please wipe the file.**

After wiping the file, and reinstalling the app: the bad changeset error is presented.

**Comment by DominicFrei** [comment]
@michaeljajou Thank you for the additional information.

@simonask @tkaye407 Can you maybe have a look at that too?

**Comment by michaeljajou** [comment]
@DominicFrei Hey, I found the issue. This was yet again a mismatch of schemas, sometimes even double checking is not enough. I had one value as optional in the schema, and required in the client causing the bad changeset. 

Error message makes a lot more sense now, you're free to close this!

**Comment by DominicFrei** [comment]
Hi @michaeljajou,

Thank you for reporting back to us. I know how you feel. Happened to me too many times as well. :)

**Comment by georgesjamous** [comment]
_Version 10.5.0_

I have started receiving this issue recently. I believe it's the same.
However, I haven't changed the Schema.

It starts to happen when I update a specific field who's type is 'EmbeddedObject' 
(I have double-checked the schema)

So it's failing to download the realm initially.
if I Stop the sync, then re-enable it, it works until I try to re-update the field.
The value is updated correctly in the database, however, on the next Realm Download, I get the error.

Any pointers?

Error:
```
Error Domain=io.realm.sync Code=112 "Bad changeset (DOWNLOAD)" UserInfo={Category=realm::sync::Client::Error, NSLocalizedDescription=Bad changeset (DOWNLOAD), Error Code=112}
```

Trace:
```
xception backtrace:
0   Realm                               0x0000000105a3caba _ZNK5realm4sync18InstructionApplier19bad_transaction_logIJmRKjEEEvPKcDpOT_ + 394
1   Realm                               0x0000000105a3c057 _ZN5realm4sync18InstructionApplier20resolve_list_elementIRNS_4util8overloadIJZNS1_clERKNS0_5instr11ArrayInsertEE4$_22ZNS1_clES8_E4$_23EEEEEvRNS_7LstBaseEmNSt3__111__wrap_iterIPKN5mpark7variantIJNS0_12InternStringEjEEEEESN_PKcOT_ + 2807
2   Realm                               0x0000000105a3b15e _ZN5realm4sync18InstructionApplier13resolve_fieldIRNS_4util8overloadIJZNS1_clERKNS0_5instr11ArrayInsertEE4$_22ZNS1_clES8_E4$_23EEEEEvRNS_3ObjENS0_12InternStringENSt3__111__wrap_iterIPKN5mpark7variantIJSF_jEEEEESN_PKcOT_ + 686
3   Realm                               0x0000000105a3b103 _ZN5realm4sync18InstructionApplier13resolve_fieldIRNS_4util8overloadIJZNS1_clERKNS0_5instr11ArrayInsertEE4$_22ZNS1_clES8_E4$_23EEEEEvRNS_3ObjENS0_12InternStringENSt3__111__wrap_iterIPKN5mpark7variantIJSF_jEEEEESN_PKcOT_ + 595
4   Realm                               0x0000000105a2c677 _ZN5realm4sync18InstructionApplierclERKNS0_5instr11ArrayInsertE + 263
5   Realm                               0x0000000105a580f4 _ZN5realm4sync18InstructionApplier5applyIS1_EEvRT_RKNS0_9ChangesetEPNS_4util6LoggerE + 100
6   Realm                               0x0000000105a53b8d _ZN5realm5_impl17ClientHistoryImpl27integrate_server_changesetsERKNS_4sync12SyncProgressEPKyPKNS2_11Transformer15RemoteChangesetEmRNS2_11VersionInfoERNS2_21ClientReplicationBase16IntegrationErrorERNS_4util6LoggerEPNSE_20SyncTransactReporterE + 1053
7   Realm                               0x0000000105a6765d _ZN5realm5_impl14ClientImplBase7Session29initiate_integrate_changesetsEyRKNSt3__16vectorINS_4sync11Transformer15RemoteChangesetENS3_9allocatorIS7_EEEE + 173
8   Realm                               0x0000000105a2392a _ZN12_GLOBAL__N_111SessionImpl29initiate_integrate_changesetsEyRKNSt3__16vectorIN5realm4sync11Transformer15RemoteChangesetENS1_9allocatorIS6_EEEE + 42
9   Realm                               0x0000000105a6614d _ZN5realm5_impl14ClientImplBase7Session24receive_download_messageERKNS_4sync12SyncProgressEyRKNSt3__16vectorINS3_11Transformer15RemoteChangesetENS7_9allocatorISA_EEEE +
589
10  Realm                               0x0000000105a630af _ZN5realm5_impl14ClientProtocol22parse_message_receivedINS0_14ClientImplBase10ConnectionEEEvRT_PKcm + 6271
11  Realm                               0x0000000105a5d894 _ZN5realm5_impl14ClientImplBase10Connection33websocket_binary_message_receivedEPKcm + 52
12  Realm                               0x00000001059ecb43 _ZN12_GLOBAL__N_19WebSocket17frame_reader_loopEv + 1491
13  Realm                               0x0000000105a6b950 _ZN5realm4util7network7Service9AsyncOper22do_recycle_and_executeINSt3__18functionIFvNS5_10error_codeEmEEEJRS7_RmEEEvbRT_DpOT0_ + 224
14  Realm                               0x0000000105a6b414 _ZN5realm4util7network7Service14BasicStreamOpsINS1_3ssl6StreamEE16BufferedReadOperINSt3__18functionIFvNS8_10error_codeEmEEEE19recycle_and_executeEv + 196
15  Realm                               0x0000000105b22a44 _ZN5realm4util7network7Service4Impl3runEv + 484
16  Realm                               0x0000000105a17a5d _ZN5realm4sync6Client3runEv + 29
17  Realm                               0x0000000105c1022d
_ZNSt3__1L14__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN5realm5_impl10SyncClientC1ENS2_INS7_4util6LoggerENS4_ISB_EEEERKNS7_16SyncClientConfigENS_10shared_ptrIKNS7_11SyncManagerEEEEUlvE0_EEEEEPvSN_ + 45
18  libsystem_pthread.dylib             0x00007fff5e73d109 _pthread_start + 148
19  libsystem_pthread.dylib             0x00007fff5e738b8b thread_start + 15
2021-01-06 19:19:02.263019+0200 Pet Health[57279:11319918] Sync: Connection[3]: Connection closed due to error
```

**Comment by DominicFrei** [comment]
It looks like the conversation has been moved to #7018 already. Is it ok for you to continue there, @georgesjamous?
