### ISSUE TITLE
Documentation could use an update

### ISSUE THREAD

**Issue by jaywardell** [realm/realm-cocoa#7024]
## Goals
The documentation at  https://realm.io/docs/swift/latest/#migrations could use a slight tweak with more up to date information about how too delete Realm files.

## Expected Results
The documentation could make reference to the method     
    public static func deleteFiles(for config: Configuration) throws -> Bool
on line 918 of Realm.swift 

In the section Deleting Realm files at https://realm.io/docs/swift/latest/#migrations, the documentation explains a way to delete Realm files with FIleManager, but RealmSwift actually seems to provide a better approach via the method deleteFiles(for config Configuration:).  It would be helpful if this method were mentioned in the documentation.

## Actual Results
embarrassment: A client asked me to look into whether I should be using the code recommended in the documentation in my project for him.  I snapped back that this was the approach recommended by Realm at their site, so it must be the right way.  I then found the above method while researching something else and had to eat crow. Not fun.

## Steps for others to Reproduce
The error is with the documentation, so I guess reading the documentation is all that needs to happen...

**Comment by DominicFrei** [comment]
Hi @jaywardell,

Thank you for your suggestion.

I am working on a PR to update the documentation and will let you know as soon as it's done.

Kind regards,
Dominic

**Comment by DominicFrei** [comment]
@jaywardell You can find the updated version at https://realm.io/docs/swift/latest/#deleting-realm-files

Thanks for pointing this out!

**Comment by jaywardell** [comment]
> @jaywardell You can find the updated version at https://realm.io/docs/swift/latest/#deleting-realm-files
> 
> 
> 
> Thanks for pointing this out!

Thanks Dominic. That was fast.
