### ISSUE TITLE
Realm not syncing documents from atlas cluster even though all documents pass schema validation

### ISSUE THREAD

**Issue by michaeljajou** [realm/realm-cocoa#7026]
I apologize in advance for the lack of information provided, it is just that nothing was truly changed and realm stopped syncing documents. 

**Overview**
I was writing a new schema for a new collection, and I went back to my app and realm stopped syncing documents for all collections. So I removed the configuration for the schema (did not change anything with the iOS app, since I didn't implement the class definition for that collection yet). Still, Sync did not transfer any documents from mongo to realm. 

**Additional Information**
As mentioned above, I reverted the app back to the exact state it was when realm sync was working perfectly fine, yet sync still wasn't working. 

- All documents pass schema validation
- Opening realm from the iOS client is successful (no errors are printed) however, just an empty realm is returned which is not aligned with the data on MongoDB. 
- I tried creating a new app with the same schema configurations, but still an empty realm was returned. 
- Sync was being initialized and re-initialized multiple times. 
- Sync logs show 0 errors, all status messages are "Ok"

**Goal**
I know the information in here is vague. Unfortunately, I don't have much information to give about the issue since I truly don't know why it's happening. 

I guess the only question I can ask is: are there any known issues with realm sync where it just stops syncing documents after initializing and reinitializing multiple times. Maybe a possible overload?

**Comment by ianpward** [comment]
@michaeljajou I would encourage you to open a support ticket on the MongoDB cloud portal since this is a sync related question. The Github repo's are generally reserved for local-only non-sync Realm bugs or issues.

**Comment by michaeljajou** [comment]
@ianpward I opened one, thanks. They said they'll try to get back to me in a few days. In the meantime, you've never ran into this sort of issue?

**Comment by michaeljajou** [comment]
**Log**

`Sync: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, async open = false, client reset = false`

**Comment by michaeljajou** [comment]
This is a Realm Sync error as sync started working again hours later without any changes being made.

**Comment by jhoughjr** [comment]
I wonder if that is what im experiencing now. I was chasing down why my data didnt sync to atlas, only for it to appear there after some time, but though it looks correct, the data isnt coming down, and there are NO errors reported in the logs in the admin interface or on the device console. Ive really got enough complexity trying to suss out a data model without having to second guess yet another tool. I started pretty happy with realm sync but keep running into walls like this and spending hours getting nowhere or running in circles.
