### ISSUE TITLE
Realm accessed from incorrect thread.

### ISSUE THREAD

**Issue by ahmedsafadii** [realm/realm-cocoa#7028]
## Goals
Remove data from an array of the realm object

## Expected Results
data inside realm to be deleted

## Actual Results
2021-01-06 15:11:04.927332+0300 Eco Capture[1758:443269] *** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
*** First throw call stack:
(0x1991719d4 0x1acb22b54 0x104644d38 0x1044840d4 0x10448afc4 0x10448af9c 0x102d48a08 0x102d4739c 0x1037715f8 0x1036ae28c 0x1066b3ce4 0x1066b5528 0x1066c3994 0x1990f15d0 0x1990eba78 0x1990eab90 0x1af40d598 0x19b9d4638 0x19b9d9bb8 0x1abec5b54 0x102d3fcac 0x102d3fc24 0x102d40d14 0x198dc9588)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
terminating with uncaught exception of type NSException

some time that error

2021-01-06 15:36:21.142714+0300 Eco Capture[1793:456577] *** Terminating app due to uncaught exception 'RLMException', reason: 'Can only delete an object from the Realm it belongs to.'
*** First throw call stack:
(0x1991719d4 0x1acb22b54 0x1058bb134 0x1059ba678 0x10778593c 0x1040f4f00 0x1040f3e8c 0x1040f6264 0x107783814 0x1040f4c48 0x1079458d8 0x1079459d8 0x19a32a4d8 0x1990d4360 0x1990d4320 0x1990d3918 0x1990d3310 0x107946780 0x1040f5038 0x1040f37b0 0x104ae15f8 0x104a1e28c 0x107a3fce4 0x107a41528 0x107a4f994 0x1990f15d0 0x1990eba78 0x1990eab90 0x1af40d598 0x19b9d4638 0x19b9d9bb8 0x1abec5b54 0x1040ec0c0 0x1040ec038 0x1040ed128 0x198dc9588)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RLMException', reason: 'Can only delete an object from the Realm it belongs to.'
terminating with uncaught exception of type NSException
(lldb) 

## Steps for others to Reproduce
- Create Alamofire request
- Put the delete or add or read inside the request
- Crash happen 
## Code Sample

```Swift
    func uploadData(deleted: List<DataAcc>, sending: [[String: Double]]) {
        
        DataAccManager.shared.dataAccsData(data: sending, onSuccess: { result in
            do {
                let realm = try Realm()
                for object in deleted {
                    let test = realm.objects(DataAcc.self).filter("timestamp == " + "\(object.timestamp)")
                    print("Data", test.count)
                }
                print("Data has been deleted")
            } catch let error as NSError {
                print("Error Delete Data: ", error.localizedDescription)
            }
        }, onFailure: { error in
            print("Error uploading data", error)
        })
        
    }
```

Edit - This method is working but in that case, i can't make sure that the response is a success so I can confirm remove data

```Swift
func uploadData(deleted: List<DataAcc>, sending: [[String: Double]]) {
            do {
                let realm = try Realm()
                try realm.write {
                    realm.delete(deleted)
                    print("Data has been deleted")
                }
            } catch let error as NSError {
                print("Error Delete Data: ", error.localizedDescription)
            }
        
        DataAccManager.shared.dataAccsData(data: sending, onSuccess: { result in
            self.status = true
            print("Data has been sent")
        }, onFailure: { error in
            print("Error uploading data", error)
        })
        
    }
```

## Version of Realm and Tooling

Realm framework version: 10.5.0

Realm Object Server version: Don't use

Xcode version: Version 12.2 (12B45b)

iOS/OSX version: 14

Dependency manager + version: Latest

**Comment by DominicFrei** [comment]
Hi @ahmedsafadii,

for sync we recommend Realm Sync.

To not disregard your question though: Can you show us a little more context?
Where is this list coming from? Could you just pass in the object it is attached to?

The SDK offers a `ThreadSafeReference`: https://realm.io/docs/swift/latest/#passing-instances-across-threads

You could pass in the object in question a parameter and then pass it on (wrapped as a `ThreadSafeReference`) into the success block.

**Comment by ahmedsafadii** [comment]
@DominicFrei this is the full cycle 



This is executed every 1 sec
```
    func didReceiveAccelerationX(_ x: Int8, y: Int8, z: Int8, withTimestamp timestamp: Double, fromDevice device: EmpaticaDeviceManager!) {
        DataAccManager.shared.writeData(object: DataAcc(value: ["timestamp" : timestamp, "xPos" : Double(x), "yPos" : Double(y), "zPos" : Double(z)]))
    }
```

this is the manager

```
class DataAccManager {
    
    static let shared = DataAccManager()
    var size: Int = 1000
    var status: Bool = true
    
    func dataAccsData(data: [[String: Double]], onSuccess: @escaping([AccResponseElement]) -> Void,
                      onFailure: @escaping(String) -> Void) {
        
        let requestUrl = APIManager.sharedInstance.apiUrl + APIManager.dataAccs
        
        var headers: HTTPHeaders = []
        headers.add(.acceptLanguage(Constants.Setting.langauge))
        
        if Defaults[\.token] != "" {
            headers.add(.authorization(bearerToken: Defaults[\.token]))
        }
        
        AF.request(requestUrl, method: .post, parameters: data, encoder: JSONParameterEncoder.default, headers: headers).responseData { response in
            switch response.result {
            case .success:
                guard let data = response.data else {
                    return
                }
                do {
                    let data = try JSONDecoder().decode([AccResponseElement].self, from: data)
                    print("finish", data.count)
                    onSuccess(data)
                } catch let error {
                    onFailure(error.localizedDescription)
                }
            case .failure(let error):
                onFailure(error.localizedDescription)
            }
        }
    }
    
    func writeData(object: DataAcc) {
        
        do {
            let realm = try Realm()
            try realm.write {
                realm.add(object)
            }
        } catch let error as NSError {
            print("Data Acc Write Error: ", error.localizedDescription)
        }
        checkData()
    }
    
    func checkData() {
        do {
            let realm = try Realm()
            let accSize = realm.objects(DataAcc.self)
            if accSize.count > size {
                if status {
                    status = false
                    print("Should Upload Here")
                    self.prepareData(data: accSize)
                }
            }
            print("Size Is: ", accSize.count)
        } catch let error as NSError {
            print("Error calcualte size: ", error.localizedDescription)
        }
    }
    
    func prepareData(data: Results<DataAcc>) {
        
        let deleted = List<DataAcc>()
        var sending = [[String: Double]]()
        
        for i in 0..<size {
            deleted.append(data[i])
            sending.append([
                "timestamp": data[i].timestamp,
                "z": data[i].xPos,
                "y": data[i].yPos,
                "x": data[i].zPos,
            ])
        }
        
        print("Before Sending", deleted.count)
        print("Before Sending", sending.count)
        
        uploadData(deleted: deleted, sending: sending)
        
    }
    
    func uploadData(deleted: List<DataAcc>, sending: [[String: Double]]) {
        
        DataAccManager.shared.dataAccsData(data: sending, onSuccess: { result in
            self.status = true
        }, onFailure: { error in
            print("Error uploading data", error)
        })
        
        // TODO: This should excute when the request is finish

        self.clearData(deleted: deleted)

    }
    
    func clearData(deleted: List<DataAcc>) {
        do {
            let realm = try Realm()
            try realm.write {
                realm.delete(deleted)
                print("Data has been deleted")
            }
        } catch let error as NSError {
            print("Error Delete Data: ", error.localizedDescription)
        }
    }
```

**Comment by ahmedsafadii** [comment]
@DominicFrei also I try the way that inside the documentation about ThreadSafeReference

```Swift
    func uploadData(deleted: List<DataAcc>, sending: [[String: Double]]) {
        
        let personRef = ThreadSafeReference(to: deleted)
        DataAccManager.shared.dataAccsData(data: sending, onSuccess: { result in
            autoreleasepool {
                let realm = try! Realm()
                guard let data = realm.resolve(personRef) else {
                    return // person was deleted
                }
                try! realm.write {
                    realm.delete(data)
                }
            }
            self.status = true
        }, onFailure: { error in
            print("Error uploading data", error)
        })
    }
```

I got this error

```
2021-01-06 20:44:00.465916+0300 Eco Capture[2135:538356] *** Terminating app due to uncaught exception 'RLMException', reason: 'Cannot construct reference to unmanaged object, which can be passed across threads directly'
*** First throw call stack:
(0x1991719d4 0x1acb22b54 0x106651a70 0x106651bec 0x1083ea344 0x1083ea2a8 0x104d1c5ac 0x104d1c4bc 0x104d1bc10 0x104d1b6d0 0x104d0e224 0x104d0e2a8 0x104d33c6c 0x104d62854 0x104d34b44 0x1b1209528 0x1b1209724 0x1b1209a24 0x1b12039e4 0x1b11f299c 0x1b1232f44 0x1b121ead0 0x10867bce4 0x10867d528 0x1086845ac 0x108685268 0x1086843f0 0x108685234 0x108690a5c 0x1df7d25a4 0x1df7d5874)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RLMException', reason: 'Cannot construct reference to unmanaged object, which can be passed across threads directly'
terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by DominicFrei** [comment]
> @DominicFrei also I try the way that inside the documentation about ThreadSafeReference
> 
> [SWIFT (18 lines)](#)
> ```swift
>     func uploadData(deleted: List<DataAcc>, sending: [[String: Double]]) {
>         
>         let personRef = ThreadSafeReference(to: deleted)
>         DataAccManager.shared.dataAccsData(data: sending, onSuccess: { result in
>             autoreleasepool {
>                 let realm = try! Realm()
>                 guard let data = realm.resolve(personRef) else {
>                     return // person was deleted
>                 }
>                 try! realm.write {
>                     realm.delete(data)
>                 }
>             }
>             self.status = true
>         }, onFailure: { error in
>             print("Error uploading data", error)
>         })
>     }
> ```
> 
> I got this error
> 
> ```
> 2021-01-06 20:44:00.465916+0300 Eco Capture[2135:538356] *** Terminating app due to uncaught exception 'RLMException', reason: 'Cannot construct reference to unmanaged object, which can be passed across threads directly'
> *** First throw call stack:
> (0x1991719d4 0x1acb22b54 0x106651a70 0x106651bec 0x1083ea344 0x1083ea2a8 0x104d1c5ac 0x104d1c4bc 0x104d1bc10 0x104d1b6d0 0x104d0e224 0x104d0e2a8 0x104d33c6c 0x104d62854 0x104d34b44 0x1b1209528 0x1b1209724 0x1b1209a24 0x1b12039e4 0x1b11f299c 0x1b1232f44 0x1b121ead0 0x10867bce4 0x10867d528 0x1086845ac 0x108685268 0x1086843f0 0x108685234 0x108690a5c 0x1df7d25a4 0x1df7d5874)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> *** Terminating app due to uncaught exception 'RLMException', reason: 'Cannot construct reference to unmanaged object, which can be passed across threads directly'
> terminating with uncaught exception of type NSException
> (lldb) 
> ```

@ahmedsafadii You are trying to create a `ThreadSafeReference` to the `List<DataAcc>` which is not an object managed by your realm. As pointed our in the error message this can be passed directly and you do not (and cannot) create a`ThreadSafeReference` to that.

`ThreadSafeReference`s are created for realm objects: https://realm.io/docs/swift/latest/#passing-instances-across-threads

**Comment by DominicFrei** [comment]
> @DominicFrei this is the full cycle
> 
> This is executed every 1 sec
> 
> ```swift
>     func didReceiveAccelerationX(_ x: Int8, y: Int8, z: Int8, withTimestamp timestamp: Double, fromDevice device: EmpaticaDeviceManager!) {
>         DataAccManager.shared.writeData(object: DataAcc(value: ["timestamp" : timestamp, "xPos" : Double(x), "yPos" : Double(y), "zPos" : Double(z)]))
>     }
> ```
> 
> this is the manager
> 
> [SWIFT (114 lines)](#)
> ```swift
> class DataAccManager {
>     
>     static let shared = DataAccManager()
>     var size: Int = 1000
>     var status: Bool = true
>     
>     func dataAccsData(data: [[String: Double]], onSuccess: @escaping([AccResponseElement]) -> Void,
>                       onFailure: @escaping(String) -> Void) {
>         
>         let requestUrl = APIManager.sharedInstance.apiUrl + APIManager.dataAccs
>         
>         var headers: HTTPHeaders = []
>         headers.add(.acceptLanguage(Constants.Setting.langauge))
>         
>         if Defaults[\.token] != "" {
>             headers.add(.authorization(bearerToken: Defaults[\.token]))
>         }
>         
>         AF.request(requestUrl, method: .post, parameters: data, encoder: JSONParameterEncoder.default, headers: headers).responseData { response in
>             switch response.result {
>             case .success:
>                 guard let data = response.data else {
>                     return
>                 }
>                 do {
>                     let data = try JSONDecoder().decode([AccResponseElement].self, from: data)
>                     print("finish", data.count)
>                     onSuccess(data)
>                 } catch let error {
>                     onFailure(error.localizedDescription)
>                 }
>             case .failure(let error):
>                 onFailure(error.localizedDescription)
>             }
>         }
>     }
>     
>     func writeData(object: DataAcc) {
>         
>         do {
>             let realm = try Realm()
>             try realm.write {
>                 realm.add(object)
>             }
>         } catch let error as NSError {
>             print("Data Acc Write Error: ", error.localizedDescription)
>         }
>         checkData()
>     }
>     
>     func checkData() {
>         do {
>             let realm = try Realm()
>             let accSize = realm.objects(DataAcc.self)
>             if accSize.count > size {
>                 if status {
>                     status = false
>                     print("Should Upload Here")
>                     self.prepareData(data: accSize)
>                 }
>             }
>             print("Size Is: ", accSize.count)
>         } catch let error as NSError {
>             print("Error calcualte size: ", error.localizedDescription)
>         }
>     }
>     
>     func prepareData(data: Results<DataAcc>) {
>         
>         let deleted = List<DataAcc>()
>         var sending = [[String: Double]]()
>         
>         for i in 0..<size {
>             deleted.append(data[i])
>             sending.append([
>                 "timestamp": data[i].timestamp,
>                 "z": data[i].xPos,
>                 "y": data[i].yPos,
>                 "x": data[i].zPos,
>             ])
>         }
>         
>         print("Before Sending", deleted.count)
>         print("Before Sending", sending.count)
>         
>         uploadData(deleted: deleted, sending: sending)
>         
>     }
>     
>     func uploadData(deleted: List<DataAcc>, sending: [[String: Double]]) {
>         
>         DataAccManager.shared.dataAccsData(data: sending, onSuccess: { result in
>             self.status = true
>         }, onFailure: { error in
>             print("Error uploading data", error)
>         })
>         
>         // TODO: This should excute when the request is finish
> 
>         self.clearData(deleted: deleted)
> 
>     }
>     
>     func clearData(deleted: List<DataAcc>) {
>         do {
>             let realm = try Realm()
>             try realm.write {
>                 realm.delete(deleted)
>                 print("Data has been deleted")
>             }
>         } catch let error as NSError {
>             print("Error Delete Data: ", error.localizedDescription)
>         }
>     }
> ```

@ahmedsafadii The recommended way to go would be [Realm Sync](https://docs.mongodb.com/realm/sync/get-started) instead of doing it manually yourself.
Have you had a chance to look into that?

**Comment by DominicFrei** [comment]
@ahmedsafadii In addition to the above posts an the recommendation to look into Realm Sync as the recommended way to go I have created a solution for your situation in case you want to keep this one:
https://github.com/DominicFrei/Playground/blob/realm/realm-cocoa/issues/7028/Tests/PlaygroundTests/PlaygroundTests.swift

Important notes:
- `RealmSwift.List` is not meant to be used as a list of objects like an array, set, etc. It is meant to be used as a reference to other Realm objects within a Realm object.
- As shown in my example you have to use `ThreadSafeReference` on the Realm objects you want to pass to another thread and then solve them their before using them.

**Comment by ahmedsafadii** [comment]
@DominicFrei 

I will give it a look for the realm sync

for your example, it didn't work

```Swift
    func uploadData(deleted: List<DataAcc>, sending: [[String: Double]]) {
        
        let threadSafeObjects = deleted.map{ ThreadSafeReference(to: $0) }
        
        DataAccManager.shared.dataAccsData(data: sending, onSuccess: { result in
            DispatchQueue.init(label: "queue1").async {
                let realm = try! Realm()
                try! realm.write {
                    threadSafeObjects.forEach { (threadSafeObject: ThreadSafeReference<DataAcc>) in
                        realm.delete(realm.resolve(threadSafeObject)!)
                    }
                }
            }
            self.status = true
        }, onFailure: { error in
            print("Error uploading data", error)
        })
    }

```
I have this error

```
2021-01-07 22:03:40.027594+0300 Eco Capture[397:23273] *** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
*** First throw call stack:
(0x1b05e99d4 0x1c3f9ab54 0x105efdb6c 0x105efda90 0x105efdbec 0x107c96344 0x107c962a8 0x1045bb7d8 0x1045bb7fc 0x1b40fc360 0x1b4083610 0x1045bbf74 0x1045baa04 0x1045bd9d0 0x107c6b814 0x1045bbde0 0x104586a10 0x107f27ce4 0x107f29528 0x107f305ac 0x107f31234 0x107f3ca5c 0x1f6c4a5a4 0x1f6c4d874)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
terminating with uncaught exception of type NSException
```

**Comment by ahmedsafadii** [comment]
i also try realm sync the same crash @DominicFrei 

can you provide an example for my works

Note that the crash only happens when the  completion of Alamofire finish

**Comment by DominicFrei** [comment]
> for your example, it didn't work

@ahmedsafadii Trying to understand this step by step since your code looks fine at first.

Did you check out the above linked playground (https://github.com/DominicFrei/Playground/tree/realm/realm-cocoa/issues/7028) and ran the test in there?

Did it succeed?

**Comment by ahmedsafadii** [comment]
@DominicFrei yes it works fine, I'm saying that if I enter it inside alamofire request completion only this problem happens

**Comment by DominicFrei** [comment]
@ahmedsafadii Alright, understood. Can you extend my example or create a similar (simplified) one where you use Alamofire and it crashes? I could not reproduce the crash on my side so far.

**Comment by ericjordanmossman** [comment]
@ahmedsafadii Were you able to reproduce what Dominic mentioned?

**Comment by summonerriftofficial** [comment]
nop :(, I had to change the library
