### ISSUE TITLE
let realm = try! Realm() crash in iOS < 13

### ISSUE THREAD

**Issue by snievesZafiro** [realm/realm-cocoa#7032]
Hi!
I have a problem when I initialize Realm with the next line:
let realm = try! Realm()

**In iOS < 13** (Device and Simulator), we have a error on line 262 of the file RLMSchema.mm
malloc_ptr classes(objc_copyClassList(&numClasses), &free);

**In iOS >= 13** This works well

Realm framework version: Realm 10.5.0
Xcode version: 12.3
Swift 5.1

Please help me how to fix this issue.

**Comment by DominicFrei** [comment]
Hi @snievesZafiro,

it's hard to tell what's happening here with that one line. Can you provide a code example including a full stack trace so that we can reproduce this on our side and find out what's going on?

**Comment by snievesZafiro** [comment]
Hi @DominicFrei 

The bug is not from Realm Pod
This morning I've made an update with the next result:

Installing Alamofire 5.4.1 (was 5.4.0)
Installing Kingfisher 6.0.1 (was 5.15.8)
Installing Mixpanel 3.6.4 (was 3.6.3)
Installing PromisesObjC 1.2.12 (was 1.2.11)
Installing Realm 10.5.0 (was 10.4.0)
Installing RealmSwift 10.5.0 (was 10.4.0)


I thought the problem was related to the Realm Pod but after I've made a downgrade and the bug error is for another of the libraries....and now I have to find out which of all

Thanks!!

**Comment by snievesZafiro** [comment]
Hi @DominicFrei 

The problem is with Kingfisher 6.0.1...luckily with the previous version it works correctly again

Realm 10.5.0 + KingFisher 5.15.8 -> OK
Realm 10.5.0 + KingFisher 6.0.1 -> BUG
