### ISSUE TITLE
app.syncManager.errorHandler Not being called

### ISSUE THREAD

**Issue by georgesjamous** [realm/realm-cocoa#7034]
## Goals
Handle Sync errors of an application. For example when the session was revoked (Client Reset).

## Expected Results
`app.syncManager.errorHandler = { _ in }` to be called

## Actual Results
The block does not get called.
```
Sync: Connection[1]: Connection closed due to error
Sync: Connection[2]: Websocket: Expected HTTP response 101 Switching Protocols, but received:
HTTP/1.1 401 Unauthorized
cache-control: no-cache, no-store, must-revalidate
connection: close
content-length: 190
content-type: application/json
date: Fri, 08 Jan 2021 08:47:11 GMT
server: envoy
vary: Origin
x-envoy-max-retries: 0
x-frame-options: DENY
Sync: Connection[2]: Connection closed due to error
```

## Steps for others to Reproduce
Login, revoke session from UI, and watch the Logs.

## Code Sample
```
        app.syncManager.errorHandler = { error, session in
            print(error)
        }
```

## Version of Realm and Tooling
Realm Version: 10.4.0 and 10.5.0

**Comment by DominicFrei** [comment]
Hi @georgesjamous, I've seen this issue in older version but it has been fixed.

Can you give us some more context or maybe even a code example that reproduces the above issue?

**Comment by georgesjamous** [comment]
This is a light version of code from my implementation

```swift
final class Authentication {
    static let current: Authentication = Authentication()
    let app: App
    init() {
        app = App(id: "...")
        app.authorizationDelegate = self
        app.syncManager.errorHandler = { error, session in
            print(error, session)
        }
    }
}
```

1- initialize the Authentication (creates the app and error handler listener)
2- log in the user
3- Open a Realm and the realm is Syncing all good

4- Revoke the user's session
5- The realm stops synching because the session is not valid

The block should be called at this point right?

Even after revoking the session and restarting the App
app.currentUser is not null
app.currentUser.accessToken is not null
app.currentUser.refreshToken is not null

**Comment by georgesjamous** [comment]
I am looking around for a way to handle session invalidation (or client reset) for Sync. To force the user to re-authenticate because it looks like it's not done automatically under the hood or because the 'refreshToken' gets invalidated too.
I can't find any solution, so I assumed that  `app.syncManager.errorHandler` does the trick. Or am I mistaken?


What I have found however, for older version this snippet [Stack](https://stackoverflow.com/questions/63397385/realm-ios-how-to-handle-client-reset)
```swift 
SyncManager.shared.errorHandler = { error, session in
    let syncError = error as! SyncError
    switch syncError.code {
    case .clientResetError:
        if let (path, clientResetToken) = syncError.clientResetInfo() {
            closeRealmSafely()
            saveBackupRealmPath(path)
            SyncSession.immediatelyHandleError(clientResetToken)
        }
    default:
        // Handle other errors...
        ()
    }
}
```

**Comment by georgesjamous** [comment]
I tested this today on a fresh Realm application and looks like it's working. The block is being called.
I am gonna close this issue for now.

**Comment by DominicFrei** [comment]
Glad it worked. Thanks for reporting the result back to us, @georgesjamous.
