### ISSUE TITLE
RLMUser sessionForPartitionValue issue

### ISSUE THREAD

**Issue by versoworks** [realm/realm-cocoa#7036]
!!! MANDATORY TO FILL OUT !!!

## Goals

Retrieve a valid `RLMSyncSession `from the `RLMUser `when specifying the` RLMRealmConfiguration fileURL` property on a synced realm.
## Expected Results

Calling `RLMUser sessionForPartitionValue` returns a valid `RLMSyncSession `when specifying the `RLMRealmConfiguration fileURL` property on a synced realm.
## Actual Results

Calling `RLMUser sessionForPartitionValue` returns `nil `when setting the `RLMRealmConfiguration fileURL` property on a synced realm.
## Steps for others to Reproduce

We have a requirement for realm files to be stored in the Application Group directory, hence we set the `RLMRealmConfiguration fileURL` property accordingly. This causes `RLMUser sessionForPartitionValue` to return nil. Following the call in the debugger, we see the line `auto path = [self pathForPartitionValue:s.str()];` is at fault, as it returns a path in the Application Document directory.
## Version of Realm and Tooling

Realm framework version: ?
10.5.0
Realm Object Server version: ?
Unknown
Xcode version: ?
12.3 (12C33)
iOS/OSX version: ?
Big Sur 11.1
Dependency manager + version: ?

**Comment by leemaguire** [comment]
Hi @versoworks ,

Could you give us more context as to why you require the synced Realm to be in an App Group Container? 

By using a synced Realm you should not need to rely on using an App Group Container to share a Realm between apps. You can simply instantiate the Realm as you would if you are using Sync, and both Realms will sync accordingly.

**Comment by versoworks** [comment]
Hi @leemaguire,

this is an existing app we're adding cloud sync to, where design choices were made based on a local realm at the time, where changing the directory now breaks existing functionality.

Before raising the issue here, we checked the docs to see if the RLMRealmConfiguration fileURL property had any caveats in regards to synced realms, and also confirmed `RLMRealm realmWithConfiguration:error:` was not returning an error when the `RLMRealmConfiguration fileURL` property was set on a synced realm. As neither of those indicated otherwise, this appears to be a bug, as the `RLMRealmConfiguration fileURL` property is not being respected in this instance.

**Comment by leemaguire** [comment]
@versoworks We don't expose the functionality to set the root directory with the synced Realm. Sorry for not explicitly stating this in the documentation. I will raise this issue with the team.

**Comment by versoworks** [comment]
@leemaguire, we noticed under the hood that the `rootDirectory` property is set to `nil`. Ideally, since the the `RLMRealmConfiguration fileURL` property exists, the sync methods should refer to it in order to determine the root directory automatically, without the need to set or expose that property.

Thanks for raising the issue internally.

**Comment by versoworks** [comment]
@leemaguire, is there any progress on this issue? It's the only unresolved issue we have impeding the release of a sync enabled version.

**Comment by leemaguire** [comment]
@versoworks I don't have an update. If the Realm is synced there isn't much need to have it in a app group container because each target will have a copy of the synced Realm. I may be missing something from your requirements though.

**Comment by versoworks** [comment]
@leemaguire I was trying to understand the friction behind not allowing the path of a synced Realm to be specified and found [this](https://github.com/realm/realm-cocoa/issues/4490#issuecomment-313888360). Is that reason still current? If so, then perhaps update the docs explaining as much, so as to avoid users wasting time pursuing a solution given the long standing nature of the issue.

**Comment by versoworks** [comment]
@leemaguire our app allows users to create a Realm via Siri. The created Realm is then initialised with any number of `RLMObject`s. Initialisation must occur at time of creation, it cannot be delayed. The issues we're facing with a synced Realm are;

- The Siri Intent is short lived; it deallocates before sync completes (we set an `RLMSyncSession` upload progress notification to wait for sync to complete).
- If the device is offline, or sync otherwise doesn't complete, these Realms either don't exist or are broken, negating this functionality.

These issues don't arise when the path of the Realm file can be specified, as placing it in the AppGroup directory means the app will find the Realms regardless of device connectivity or sync completion.

If a synced Realm cannot be accessed by multiple processes, why not document it as a known limitation so developers are aware of the issue. This will then allow the synced Realm path to specified subject to that limitation.

**Comment by leemaguire** [comment]
@versoworks I'll talk with the team about being able to have a synced Realm in an App Group to see if its feasible. One thing to possibly consider is to not create a new Realm on each Siri intent, but instead to Reuse an existing Realm for this purpose and specify a partitionValue for the users Siri intent. That way the short lived process can complete and the sync can be processed at a later date without the risk of losing data.

**Comment by versoworks** [comment]
@leemaguire cheers for the follow up. At this point, we're resigned to not allow synced Realms to be created by Siri as the issues I've outlined make them unreliable. While I admit to not knowing the technical limitations behind not allowing the file path of a synced Realm to be specified, I would argue to your Team that given that sync is how Realm is monetised, removing barriers to use would be at the top of their to-do list.

**Comment by leemaguire** [comment]
@versoworks Given that you have a work around I should be ok to close this issue?

**Comment by rouuuge** [comment]
hi @leemaguire

>  I'll talk with the team about being able to have a synced Realm in an App Group to see if its feasible. One thing to possibly consider is to not create a new Realm on each Siri intent, but instead to Reuse an existing synced Realm for this purpose and specify a partitionValue for the users Siri intent. That way the short lived process can complete and the sync can be processed at a later date without the risk of losing data.

can you describe this in more detail or do you have an example? 

@versoworks or can you describe your solution? I would like to write with Siri on a sych realm. With realm-legacy server this still worked....
