### ISSUE TITLE
Crash: malloc: can't allocate region / realm::AddressSpaceExhausted

### ISSUE THREAD

**Issue by miklselsoe** [realm/realm-cocoa#7040]
I am experiencing a crash while syncing a rather large dataset from MongoDB. It happens during initial sync of the partition.

In the app, I have two partitions, both syncing from Mongo. A fairly small one and a big one with about 270.000 rows of data. I initialize the small one first and after it has finished syncing, I present the main user interface and start syncing the big one in the background. After a while (seems to be around the same spot every time), it crashes. See details below.

While investigating the issue, I have come to understand that I need to place autorelease pools around realms when opening them on a background queue. Also, I have refactored my code to make sure that realms are relatively short lived. I used to pass open realms around and reusing them across views and within the same view for multiple queries, but it seems like it's better to open realms when you need them and then throw them away - especially on background threads. Is this correct? Or should I keep them alive for longer? Does the recommendation change when dealing with a realm as large as the one mentioned above (~270k rows)?

Anyway, I have managed to reduce the number of simultaneously open realms and that has made it less prone to crashing, but it still can't complete the sync without crashing. (before it could crash around 30% downloaded, now it makes it to 90%). 

Now I only have one instance of the big realm open while syncing. It's on a background queue and I have placed an autoreleasepool around the opening of the realm. I call this (not even accessing the realm after creation) and just wait for the crash.

```
self.syncingQueue.async {
    autoreleasepool {
        let user = RealmManager().realmUser // My own class that returns an instance of RLMUser
        var config = user.configuration(partitionValue: "SHARED")
        config.objectTypes = kSyncedObjectTypesShared // 37 object classes
        let realm = try! Realm(configuration: config, queue: nil)
    }
}
```

This runs successfully in the simulator but pretty consistently crashes across a range of newer and older iPads.

## Goals
Successfully sync a Realm from MongoDB

## Expected Results
Sync successfully completes

## Actual Results
The app crashes with either of these two messages are printed in the console, interchangeably:

```
malloc: can't allocate region
:*** mach_vm_map(size=125829120, flags: 100) failed (error code=3)
malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
```

```
libc++abi.dylib: terminating with uncaught exception of type realm::AddressSpaceExhausted: mmap() failed: Cannot allocate memory size: 33554432
terminating with uncaught exception of type realm::AddressSpaceExhausted: mmap() failed: Cannot allocate memory size: 33554432
```

The crash happens on a background thread:

```
* thread #14, stop reason = signal SIGABRT
  * frame #0: 0x00000001adf6284c libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x00000001ca17e9e8 libsystem_pthread.dylib`pthread_kill + 212
    frame #2: 0x000000018b5218f4 libsystem_c.dylib`abort + 100
    frame #3: 0x0000000196c98cc8 libc++abi.dylib`abort_message + 128
    frame #4: 0x0000000196c8ac88 libc++abi.dylib`demangling_terminate_handler() + 272
    frame #5: 0x0000000196b9ce14 libobjc.A.dylib`_objc_terminate() + 140
    frame #6: 0x0000000196c98154 libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame #7: 0x0000000196c9ae68 libc++abi.dylib`__cxa_rethrow + 144
    frame #8: 0x0000000102097c88 Realm`void realm::util::network::Service::AsyncOper::do_recycle_and_execute<std::__1::function<void (std::__1::error_code, unsigned long)>, std::__1::error_code&, unsigned long&>(bool, std::__1::function<void (std::__1::error_code, unsigned long)>&, std::__1::error_code&, unsigned long&) + 452
    frame #9: 0x00000001020976b0 Realm`realm::util::network::Service::BasicStreamOps<realm::util::network::ssl::Stream>::BufferedReadOper<std::__1::function<void (std::__1::error_code, unsigned long)> >::recycle_and_execute() + 240
    frame #10: 0x00000001021335f8 Realm`realm::util::network::Service::Impl::run() + 404
    frame #11: 0x000000010204c724 Realm`realm::sync::Client::run() + 36
    frame #12: 0x000000010220de7c Realm`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::shared_ptr<realm::SyncManager const>)::'lambda0'()> >(void*) + 44
    frame #13: 0x00000001ca17db3c libsystem_pthread.dylib`_pthread_start + 288
```

I'm assuming (for now at least) that the two crash messages take root in the same problem. Note that the memory pressure is not that high. In Xcode I can see the memory graph developing in a sawtooth patters, slowly increasing to around 325MB, then dropping to around 80MB and increasing again to ~325MB and so on.

## Code Sample
See above.

## Version of Realm and Tooling
```
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69

/Applications/Xcode 12.2.app/Contents/Developer
Xcode 12.2
Build version 12B45b

/usr/local/bin/pod
1.9.3
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

/usr/local/bin/carthage
0.36.0
github "realm/realm-cocoa" "v10.5.0"

/usr/bin/git
git version 2.24.3 (Apple Git-128)
```

**Comment by leemaguire** [comment]
Hi @miklselsoe 

You're facing an issue with virtual memory. Whats happening is that as you are trying to sync a large set of items the Realm instance will require more virtual memory in order to map the database. It makes sense that this does not happen on your simulator as you likely have enough disk space + RAM available on your machine to allow you to perform the full sync.

A potential solution here is that you increase the amount of partition values for the large dataset so that they can be synced to multiple Realms. Eg you could append a number to the of the value for a specific batch of items.
```
var config = user.configuration(partitionValue: "SHARED1")
var config = user.configuration(partitionValue: "SHARED2")
var config = user.configuration(partitionValue: "SHARED3")
```

Could I also ask what specific iPad models you faced the error with?

Also to answer your question:
 "I used to pass open realms around and reusing them across views and within the same view for multiple queries, but it seems like it's better to open realms when you need them and then throw them away - especially on background threads. Is this correct?", Yes this is correct, keeping a Realm alive will increase memory usage and it's always best to create a fresh Realm instance when access is required.

Thanks!

**Comment by miklselsoe** [comment]
It seems that opening the realm asynchronously instead of synchronously on a background queue makes all the difference. At least it doesn't seem to crash anymore. It would be great if the documentation was more clear on the potential risks of opening (large) realms synchronously.
