### ISSUE TITLE
2 BUGS - Crash & [/Users/ragu/Projects/PineTreesHealth/Radiata-iOS/Pods/Realm/Realm/RLMUser.mm:57:20: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'NSUInteger' (aka 'unsigned int')]

### ISSUE THREAD

**Issue by ragu-pth** [realm/realm-cocoa#7043]
!!! MANDATORY TO FILL OUT !!!

## Goals

No Crashes

## Expected Results

No Crashes

## Actual Results

Crashes

libsystem_kernel.dylib
__pthread_kill
libsystem_c.dylib
abort
Realm
please_report_this_error_to_help_at_realm_dot_io
Realm
realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)
Realm
realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&)
Realm
realm::DB::grab_read_lock(realm::DB::ReadLockInfo&, realm::VersionID)
Realm
realm::DB::start_read(realm::VersionID)
Realm
realm::_impl::RealmCoordinator::begin_read(realm::VersionID, bool)
Realm
realm::Realm::begin_read(realm::VersionID)
Realm
realm::Realm::read_group()
Realm
RLMClassInfo::table() const RLMClassInfo.mm:42
Realm
RLMGetObjects RLMObjectStore.mm:195
RealmSwift
RealmSwift.Realm.objects<A where A: __C.RealmSwiftObject>(A.Type) -> RealmSwift.Results<A> Realm.swift:641
Radiata
merged generic specialization <Radiata.SystemTimeZoneObject> of (extension in Radiata):RealmSwift.Realm.contentUpdated<A where A: Radiata.ContentEquatable, A: Radiata.Persistent>(_: A, filter: __C.NSPredicate?) -> Swift.Bool
Radiata
generic specialization <Radiata.ReaderInformationObject> of (extension in Radiata):RealmSwift.Realm.writeIfContentUpdate<A where A: Radiata.ContentEquatable, A: Radiata.Persistent>(_: A, filter: __C.NSPredicate?) -> A? Realm+ContentEquatable.swift:20
Radiata
closure #1 () -> () in Radiata.BluetoothService.peripheral(_: __C.PBPeripheral, deviceInformation: __C.PBDeviceInformation) -> () BluetoothService.swift:177
Radiata
Radiata.RunLoopThread.(execute in _25C052638766C1F8EA472462436432EF)(Radiata.(BlockWrapper in _25C052638766C1F8EA472462436432EF)) -> () RunLoopThread.swift:69
Radiata
@objc Radiata.RunLoopThread.(execute in _25C052638766C1F8EA472462436432EF)(Radiata.(BlockWrapper in _25C052638766C1F8EA472462436432EF)) -> () <compiler-generated>:0
Foundation
__NSThreadPerformPerform

Also another issue:
Pods/Realm/Realm/RLMUser.mm:57:20: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'NSUInteger' (aka 'unsigned int')
Pods/Realm/Realm/RLMApp.mm:201:47: Implicit conversion loses integer precision: 'unsigned long long' to 'NSUInteger' (aka 'unsigned int')
Pods/Realm/Realm/RLMApp.mm:235:20: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'NSUInteger' (aka 'unsigned int')

## Steps for others to Reproduce

Unsure as this is happening at random on other people's devices. Not everyone experiencing, but enough are.

## Code Sample

                try self.write {
                    retVal = self.create(T.self, value: object, update: .error)
                }

## Version of Realm and Tooling

Realm framework version: 10.5.0

Realm Object Server version: None

Xcode version: 12.3

iOS/OSX version: iOS 14.3

Dependency manager + version: Cocoapods Latest

**Comment by leemaguire** [comment]
Hi @ragu-pth Can you give us a larger code sample that may help us with this issue? Thanks

**Comment by ericjordanmossman** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
