### ISSUE TITLE
Unable to execute a migration that changes the "embeddedness" of an object

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-cocoa#7060]
## Goals
A user has reported on the [forums](https://developer.mongodb.com/community/forums/t/migrating-to-using-the-new-embedded-object-in-mongodb-realm/11920) that they would like to be able to migrate a model from `Object` to `EmbeddedObject`. 

## Expected Results
Migration function gets executed allowing them to ensure each object only has one parent, after which the "embeddedness" of the table changes and the model is now treated as embedded.

## Actual Results
App crashes with `Cannot convert object type ‘MyObject’ to embedded because objects have multiple incoming links*.`. Based on a conversation with @jsflax and @tgoyne, it appears the reason is that the SDK eagerly changes the table to embedded before running the migration function, which then triggers a guard at Core that ensures that only one parent points to the child object.

## Steps for others to Reproduce
Don't have exact steps, but seems like:
1. Create a model as inheriting from `Object`.
2. Have several other objects link to it.
3. Bump schema version and modify your model to inherit from `EmbeddedObject`.

## Version of Realm and Tooling

Realm framework version: 10.5.0

**Comment by sipersso** [comment]
Thanks for reporting the issue @nirinchev!

In this case, there is actually only one parent for each child object. So in step two, I think it is enough to have one object linking to it. If you need any more info from me, let me know here or in the forums.

**Comment by sipersso** [comment]
Just tried the doing the same migration on Android/Java and the migration works perfectly there using the same data models. So this seems to be an issue on iOS only.

**Comment by DominicFrei** [comment]
Note about the difference:
The iOS SDK uses `SchemaMode::Automatic` whereas the Java SDK uses `SchemaMode::Manual` while migrating which leads to `apply_pre_migration_changes` not being executed on their side.
On the Java side the user takes care of all those migrations themselves (within the migration function).

**Comment by sipersso** [comment]
@DominicFrei What does this mean in practice? Does that mean that this migration won't be possible to do with the iOS SDK? Is there a way to run the iOS SDK using manual schema mode?

**Comment by DominicFrei** [comment]
@sipersso I did have a longer conversation about this yesterday. We need to fix two things to make this work. So at the moment it actually does not which is a bug.
Regarding the mode: at the moment it is run in automatic and the iOS SDK does not offer manual since it's supposed to 'just work' with automatic which it will after the aforementioned bug fixes.

**Comment by DominicFrei** [comment]
The [relevant core changes](https://github.com/realm/realm-core/pull/4414) have been released with [Realm Cocoa 10.7.0](https://github.com/realm/realm-cocoa/tree/v10.7.0).
