### ISSUE TITLE
Modifying a single property of a single object in a Realm with notifications degrades the user interface experience

### ISSUE THREAD

**Issue by HKdAlex** [realm/realm-cocoa#7072]
## Goals

A change in a single property of a single object should not degrade the user experience with a Realm that has a complex structure.

## Expected Results

I expected a change in a single property would not overload the CPU and I'd have to wait for all the  DeepChangeCheckers to be completed to change another property of the same object or another object or the same property of the same object.

## Actual Results

Here is the issue with my app:

* It is a book production project management app that lets one manage:
	* Publications
	* Editions of publications
	* Stages of work on publication (prepress work) and editions (editorial work).
	* Tasks that can be assigned to publications, editions, stages and so on.
	* Editorial and production staff database
	* etc etc
* Using RealmSwift 5.5.0

I am having an issue with my app that uses RealmSwift and also used for collaboration via the Realm Sync. The schema is quite complex taking in account I am more of a project management person.

The current version of the RealmSwift I use is 5.5.0.

I could elaborate more on the app and its schema but I created a sample app where I can reproduce the scope of the issue (see the `Code Sample` section of the issue).

The sample app is an augmented version of the Dogs/Persons Realm example. Here are the Realm classes:

```swift

class Person: Object {
    @objc dynamic var name = “”
    let dogs = List<Dog>()
    
    @objc dynamic var uuid: String = “”
    override static func primaryKey() -> String? {
        return “uuid”
    }
}
class Dog: Object {
    @objc dynamic var name = “”
    @objc dynamic var age: Int = 0
    let owners = LinkingObjects(fromType: Person.self, property: “dogs”)
    
    @objc dynamic var uuid: String = “”
    override static func primaryKey() -> String? {
        return “uuid”
    }
    
}
```

To make the problem manifest in the same way I am experiencing it in my app, I have 100 000 dogs and 100 000 persons in the database (the sample app generates all of these on the first launch of the app), so wait around a minute for it to finish generating the sample data.

The `dogs` (List<Dog>) is populated for each person with a random number of dogs per person (between  0 and 50 dogs per person). But that is again just the setup of the database.

As you can see the backlink from a dog to the person owning it is:

```swift

LinkingObjects(fromType: Person.self, property: “dogs”)
```

As you can see there are two notification tokens in the app: one for all the dogs and one for all the persons.

The app allows you to change/regenerate the name of a random dog or a random person by clicking the buttons in the interface.

Now to usage and the issue:

When I click either of the two buttons, only one property of a single object in the database changes (a dog’s or a person’s name). As you can see in the Instruments, a “realm notification listener” thread goes into heavy action, the CPU is 100%+ and it last for a few seconds.

As fat as I understand the following is happening here:

### In the case when a dog’s name is changed: 

Once the button is clicked and the value is changed, the Realm goes into “DeepChangeChecker mode” by checking every instance of a dog (and perhaps persons too) to make sure no other object got changed and traversing each and every property of every dog/person.

As you can see the collection notifications for the “updated” persons fire (all of them who happen to own that dog).

I cannot click the button to change the name of a person (or a dog) immediately since the “realm notification listener” thread will be blocking the realm till the DeepChangeChecker is finalized.

It means the data entry/changes are crippled/delayed/the beach ball spins but I am changing a single value in a single object.

### In the case when a person’s name is changed:

Since the owners are linking object, only the person’s name change notification token is triggered…but… the Realm happily goes into the “DeepChangeChecker mode” which I thought it should not be doing in case of linkingObjects.

I understand that it is probably not the Realm’s problem since the same behavior can be observed both in the older RealmSwift 5 and the latest RealmSwift 10.

Perhaps the problem is the schema of the app or my misconception about the way the notification tokens should be created.

E.g. if I remove all the tokens, naturally things work fast.

But imagine the following example: I have a NSOutlineView that displays all persons  at the first level and then the dogs they own when you disclose an item. And a colleague of mine looks at the same view from his/her computer and wants to see the changes in real time, etc.

## Steps for others to Reproduce

Run the supplied sample app, click any of the two buttons and observe the CPU/thread activity in Xcode or Instruments.

## Code Sample

Here are two GitHub repositories with the sample apps: they are identical with one difference: one uses RealmSwift 5.5.0 and the other one RealmSwift 10.5.1 (latest as of today):

[GitHub - HKdAlex/Realm-5.5.0](https://github.com/HKdAlex/Realm-5.5.0)
[GitHub - HKdAlex/Realm-10](https://github.com/HKdAlex/Realm-10)

## Version of Realm and Tooling

Realm framework version: RealmSwift 5.5.0 and RealmSwift 10.5.1

Realm Object Server version: Irrelevant in this case.

Xcode version: 12.3 (12C33)

iOS/OSX version: macOS Big Sur, 11.1 (20C69)

Dependency manager + version: Swift Package Manager

**Comment by visdyn** [comment]
I can verify the behavior stated in the question.

An interesting note is that if the `personsToken` is not set (e.g. comment out the `personsToken = realm.objects(Person.self).observe` code, the app becomes totally responsive if the random dogs name is modified. 

Maybe the title should be "Slow notifications on objects with lists containing the object being modified"

**Comment by HKdAlex** [comment]
Yes, visdyn. I agree the title of the issue can and should be formulated better. The actual issue is probably not the "degraded user interface experience" but "degraded user experience".

In the meantime I have also tried the following: moving the write transaction to a background queue makes the interface responsive again. But e.g. I observed the following in my real app: there is a table view that lists the objects and next to the table view is the details view for the object selected in the table. So, I change a property (in this case a `Bool` represented by a checkbox) of the selected object in the details view, switch to some other object in the table view and, if I then switch to see the details of the changed object, it displays the old value of that checkbox. Then, after the DeepChangeChecker calls etc are completed, the checkbox value finally updates (2-3 seconds).

In this way, the interface becomes responsive, if the write transactions take place on a background thread, but the new value becomes available only much later (I guess it means either the write transaction completes only after the deep change checking is done? Probably not, but I wonder why the new value becomes available so much later...).

**Comment by HKdAlex** [comment]
> An interesting note is that if the `personsToken` is not set (e.g. comment out the `personsToken = realm.objects(Person.self).observe` code, the app becomes totally responsive if the random dogs name is modified.

Yes, interesting. When the `personsToken` is commented out, the Instruments report 100% CPU usage of a `Realm notification listener` thread that lasts for around 200 ms but no `DeepChangeChecker` calls are there.

I guess one of the reason why disabling the `personsToken` changes things is that the `Person` Realm class contains a `List<Dogs>`. But I wonder why do we have to disable the `personsToken` at all, since when changing a `Dog` object's `name` property those `personsToken` notifications should not be triggered because the Dog does not have a hard link to its owners but just a `LinkingObjects` connection... Do I misunderstand it?

**Comment by jsflax** [comment]
@HKdAlex and @visdyn , we have made a series of improvements and optimisations to our underlying observation code that should have improved this experience. We have also released KeyPath Filtering which will allow you to only be notified when specific properties have been changed.

Can you please retest this with the latest version of Realm and let us know if this is still an issue?

**Comment by dianaafanador3** [comment]
As @jsflax mentioned we have made a lot of improvements and optimisations to our observation code which should be able to provide a better user experience. 
Since there is no comment on this I'm closing this issue, @HKdAlex and @visdyn if you keep having issues with notifications after updating to our latest version, we can reopen this.
