### ISSUE TITLE
Add Xcode 12.4 binary to release package.

### ISSUE THREAD

**Issue by anatoliykant** [realm/realm-cocoa#7076]
**Bugs**: 
We in the company use our own private **Driven framework**, which contains **Realm** as a **dependency**.
Our **development team** and **pipeline** have gone and are **using** the new version of **Xcode12.4**.
When linking a project using `pod lib lint`, I get the error `symbol(s) not found for architecture x86_64`.
**Command used:**
```
bundle exec pod lib lint --verbose --allow-warnings --sources='ssh://git@inhousesmcompany.com/ma/mobile-apps-ios-sdk.git,https://github.com/CocoaPods/Specs'
```
**Error:**
```
...
** BUILD FAILED **

    The following build commands failed:
    	Ld /Users/user/Library/Developer/Xcode/DerivedData/App-adpiuzybiuevsradkmgfceoiuawk/Build/Products/Release-iphonesimulator/Driven/Driven.framework/Driven normal
    (1 failure)
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_RealmSwiftObject", referenced from:
          type metadata for Driven.Action in Action.o
          type metadata for Driven.DictionaryInfo in DictionaryInfo.o
          type metadata for Driven.NonCondWare in NonCondWare.o
          type metadata for Driven.Portion in Portion.o
          type metadata for Driven.RejectReason in RejectReason.o
          type metadata for Driven.SpecWare in SpecWare.o
          objc-class-ref in StorageConfigurator.o
          ...
      "_OBJC_METACLASS_$_RealmSwiftObject", referenced from:
          _OBJC_METACLASS_$__TtC6Driven6Action in Action.o
          _OBJC_METACLASS_$__TtC6Driven14DictionaryInfo in DictionaryInfo.o
          _OBJC_METACLASS_$__TtC6Driven11NonCondWare in NonCondWare.o
          _OBJC_METACLASS_$__TtC6Driven7Portion in Portion.o
          _OBJC_METACLASS_$__TtC6Driven12RejectReason in RejectReason.o
          _OBJC_METACLASS_$__TtC6Driven8SpecWare in SpecWare.o
          _OBJC_METACLASS_$__TtC6Driven22SystemParametersObject in SystemParametersObject.o
          ...
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Goals
Please **release** a **new version** of the **Realm framework** binary with **Xcode12.4 support**.
If you need help and welcome contributions from other developers, then I'm ready to help you with the release of the new version ?!

If I use **Xcode12.2** the project is **successfully linted**.

## Expected Results
**No Realm error** occurs when executing `pod lib lint` command
and **our framework** is **successfully tested**.

## Actual Results
**Error:**
```
...
** BUILD FAILED **

    The following build commands failed:
    	Ld /Users/user/Library/Developer/Xcode/DerivedData/App-adpiuzybiuevsradkmgfceoiuawk/Build/Products/Release-iphonesimulator/Driven/Driven.framework/Driven normal
    (1 failure)
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_RealmSwiftObject", referenced from:
          type metadata for Driven.Action in Action.o
          type metadata for Driven.DictionaryInfo in DictionaryInfo.o
          type metadata for Driven.NonCondWare in NonCondWare.o
          type metadata for Driven.Portion in Portion.o
          type metadata for Driven.RejectReason in RejectReason.o
          type metadata for Driven.SpecWare in SpecWare.o
          objc-class-ref in StorageConfigurator.o
          ...
      "_OBJC_METACLASS_$_RealmSwiftObject", referenced from:
          _OBJC_METACLASS_$__TtC6Driven6Action in Action.o
          _OBJC_METACLASS_$__TtC6Driven14DictionaryInfo in DictionaryInfo.o
          _OBJC_METACLASS_$__TtC6Driven11NonCondWare in NonCondWare.o
          _OBJC_METACLASS_$__TtC6Driven7Portion in Portion.o
          _OBJC_METACLASS_$__TtC6Driven12RejectReason in RejectReason.o
          _OBJC_METACLASS_$__TtC6Driven8SpecWare in SpecWare.o
          _OBJC_METACLASS_$__TtC6Driven22SystemParametersObject in SystemParametersObject.o
          ...
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps for others to Reproduce
1. **Install** and **use** default **Xcode12.4**
2. **Add** to **your framework** (you can create a new empty one) **Realm** as a **dependency**.
3. **Run** the **command** `pod lib lint`
4. **Your framework successfully lints**

## Version of Realm and Tooling

**Realm framework version**: Realm (10.5.1)/RealmSwift (10.5.1)
**Xcode version**: Xcode 12.4 (12D4e)
**iOS/OSX version**: iOS 14.4/10.15.7 Catalina (19H2)
**Dependency manager + version**: Cocoapods 1.10.1

**Comment by tgoyne** [comment]
CocoaPods installs don't use anything from us that's xcode-version specific; the only thing we do CocoaPods-related for each version of Xcode is adding the new version to our test matrix.

Installing 10.5.1 via CocoaPods with Xcode 12.4 works for me locally and on our CI.

**Comment by anatoliykant** [comment]
Hey, @tgoyne
Thanks for the quick response.
Are you talking about installing Realm in your application or framework?

**Comment by ZsoltMolnarrr** [comment]
Hello!
Our team would highly appreciate a binary release supporting Xcode 12.4.
Thanks :)

**Comment by savage7** [comment]
Why don't you just release xcframeworks with library evolution support enabled? 
I looked throw the build scripts and it seams you actually support this already.
