### ISSUE TITLE
QueryBuilder crashing when adding BETWEEN constraint as a string

### ISSUE THREAD

**Issue by TheLuckyWan** [realm/realm-cocoa#7078]
## Goals
Create predicate within the `String` argument of the filter method. Without the need to create a NSPredicate instance.

## Expected Results
Actual filtered results, based on the predicate.

## Actual Results
`*** Terminating app due to uncaught exception 'Invalid value', reason: 'NSArray object must contain exactly two objects for BETWEEN operations'`

**Relevant part of thrown stack**

`*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   Realm                               0x0000000104e44e42 _ZL15RLMPreconditionbP8NSStringS0_z + 626
	3   Realm                               0x0000000104ee310d _ZN12_GLOBAL__N_134validate_and_extract_between_rangeEP11objc_objectP11RLMPropertyPU15__autoreleasingS1_S5_ + 237
	4   Realm                               0x0000000104ecee4d _ZN12_GLOBAL__N_112QueryBuilder22add_between_constraintERKNS_15ColumnReferenceEP11objc_object + 1037
	5   Realm                               0x0000000104e48188 _ZN12_GLOBAL__N_112QueryBuilder22apply_value_expressionEP15RLMObjectSchemaP8NSStringP11objc_objectP21NSComparisonPredicate + 424
	6   Realm                               0x0000000104e46449 _ZN12_GLOBAL__N_112QueryBuilder15apply_predicateEP11NSPredicateP15RLMObjectSchema + 4345
	7   Realm                               0x0000000104e44faf _Z19RLMPredicateToQueryP11NSPredicateP15RLMObjectSchemaP9RLMSchemaRN5realm5GroupE + 271`

## Steps for others to Reproduce

Run a query using the following `NSPredicate` string and array as options:
`
let dateRange = [date1, date2]
let test = Realm.objects(RealmObject.self).filter("startTime BETWEEN %@", dateRange)
`

### **Actual method crashing :** [Link to Method](https://github.com/realm/realm-cocoa/blob/dd411665f72193f23a93e8dc271594445d7f4ff2/Realm/RLMQueryUtil.mm#L693)
```
void QueryBuilder::add_between_constraint(const ColumnReference& column, id value) {
    if (column.has_any_to_many_links()) {
        auto link_column = column.last_link_column();
        Query subquery = get_table(m_group, link_column.link_target_object_schema()).where();
        QueryBuilder(subquery, m_group, m_schema).add_between_constraint(column.column_ignoring_links(subquery), value);

        m_query.and_query(link_column.resolve<Link>(std::move(subquery)).count() > 0);
        return;
    }

    id from, to;
    validate_and_extract_between_range(value, column.property(), &from, &to);

    RLMPropertyType type = column.type();

    m_query.group();
    add_constraint(type, NSGreaterThanOrEqualToPredicateOperatorType, 0, column, from);
    add_constraint(type, NSLessThanOrEqualToPredicateOperatorType, 0, column, to);
    m_query.end_group();
}
```

### **Workaround:**
Pass the first object of the array, since it's the one that contains the actual variables array. It's not been tested throughout, maybe it's causing other errors.
`validate_and_extract_between_range(value[0], column.property(), &from, &to);`

## Version of Realm and Tooling
Realm framework version: 
    - Realm (= 10.5.0)
    - RealmSwift (= 10.5.0)

Realm Object Server version: N/a

Xcode version: Xcode 12.4 (12D4e)

iOS/OSX version: iOS 14.4

Dependency manager + version: Cocoapods 1.10.0

**Comment by jsflax** [comment]
Hey @TheLuckyWan , could you provide us with a bit more info? Specifically, what `date1`, `date2`, and `RealmObject` look like?

**Comment by TheLuckyWan** [comment]
Hello,

Here's an example of the schema of the Object i'm trying to retrieve:

```
class DatabaseObject: Object {
@objc dynamic var name = ""
@objc dynamic var startTime = Date()
```

And date1 and date2 is simply two date objects (1 day apart), that get passed as an array.
 
Thank you!

**Comment by leemaguire** [comment]
Hi @TheLuckyWan is it possible that `let dateRange = [date1, date2]` contains optional dates?

**Comment by TheLuckyWan** [comment]
Hello,

Sorry for the late answer.

But the actual date inside the array is simply two `Date()` objects in swift, for example one being `let date1 = Date()` and the second one being `let date2 = Date(timeInterval: -(24 * 60 * 180), since: Date())`

They are created on the fly when I need to filter data between those dates. They are never nil.

If I create my own `NSPredicate` object directly, it works.

Thanks.

**Comment by jsflax** [comment]
@TheLuckyWan I've written a test like so:
```swift
let dateRange = [Date(timeIntervalSince1970: 0), Date(timeIntervalSince1970: 2)]
XCTAssertEqual(1, realm.objects(SwiftObject.self).filter("dateCol BETWEEN %@", dateRange).count)
```
Where the `dateCol` property on the swift object is instantiated as `Date(timeIntervalSince1970: 1)`. The test passes and does not crash, so I cannot reproduce your issue.

Can you try upgrading to the latest version of Realm and trying again? If it still fails, can you create a small xcodeproj reproducing the issue and send it our way?
