### ISSUE TITLE
Xcode 12.5 beta - Swift Compiler Error for RealmSwift module

### ISSUE THREAD

**Issue by jkochcode** [realm/realm-cocoa#7083]
## Goals
Build Realm on Xcode 12.5 beta

## Expected Results
To be able to build project

## Actual Results
Got a Swift Compiler Error for the RealmSwift module in Combine.swift
with the error being that 'Identifiable' is only available in iOS 13 or newer.

## Steps for others to Reproduce
Add Realm and RealmSwift modules via SPM in Xcode 12.5 beta
Build project

## Version of Realm and Tooling

Realm framework version: 10.5.1

Realm Object Server version: ?

Xcode version: 12.5 beta

iOS/OSX version: macOS 11.2

Dependency manager + version: SPM (also tried with same error with Cocoapods)

**Comment by jsflax** [comment]
Hey, this issue seems legitimate. We'll get to it shortly.

**Comment by rubengarciam** [comment]
@jsflax any update?

**Comment by dejiapps** [comment]
I am having the same issue.

**Comment by rittermobile** [comment]
Same issue here. When will this be fixed and available?

**Comment by randyhill** [comment]
I'm having this issue. XCode 12.5 Beta, application build. "Identifiable' is only available in application extensions for iOS 13 or newer" on on the following line in Combine.swift.

```
public protocol ObjectKeyIdentifiable: Identifiable, ObjectBase {
    /// The stable identity of the entity associated with `self`.
    var id: UInt64 { get }
}
```

**Comment by tgoyne** [comment]
This was fixed in 10.5.2.

**Comment by randyhill** [comment]
Thanks, I copied the Realm Cocoapods example too literally, didn't notice it was set to '=10.1.4'

**Comment by JulianKahnert** [comment]
From #7098:
> @jsflax the problem still exists in `v5.5.0` any chance to fix this in that version? Not sure if we can update from `v5.5.0` to `v10.x.x` at this point.
> 
> I've fixed it in this [fork](https://github.com/worldiety/realm-cocoa/tree/v5.5.0-availability-fix).

Does anyone know if there is a fix planned for `v5.5.0`?

**Comment by tgoyne** [comment]
[I've started assembling a v5.5.1 release](https://github.com/realm/realm-cocoa/pull/7178) that'll include this.

**Comment by JulianKahnert** [comment]
Awesome thx 🙏

**Comment by michaelguren** [comment]
> [I've started assembling a v5.5.1 release](https://github.com/realm/realm-cocoa/pull/7178) that'll include this.

Any update on v5.5.1?

**Comment by tgoyne** [comment]
It was released a month ago.

**Comment by michaelguren** [comment]
> It was released a month ago.

Oh, thanks for the quick reply.  

I didn't see v5.5.1 in the release notes and my cocoa pods weren't finding it using ~> '5.5.1'.  I ended up using pod 'RealmSwift', '5.5.1' and it worked.  Thanks again.

**Comment by JonyFang** [comment]
Xcode 12.5 binaries has been added to the [release-v10.7.4](https://github.com/realm/realm-cocoa/releases/tag/v10.7.4)  package. `pod update Realm RealmSwift` will work.

**Comment by mnkadafi** [comment]
Thanks

**Comment by yves8833** [comment]
I have a similar issue, when build Realm(10.10.0) on Xcode 13 BETA3, Xcode error shows 'AnyCancellable', 'Publisher', 'CAncellable' is only available in iOS 13.0 or newer, but the error only occurs on the device under iOS 12.
i'm not sure it is the same one or anything i did wrong

**Comment by dianaafanador3** [comment]
Hi @yves8833 are you using Cocoapods or SPM to install Realm?

**Comment by yves8833** [comment]
Hi @dianaafanador3 i use cocoapods (v1.10.1)

**Comment by dianaafanador3** [comment]
It's working fine on my part on Xcode 13 (Beta 4), Realm(v10.10.0) Cocoapods (v1.10.0), Device (Simulator iOS 11.4)
Can you update to the latest Xcode beta version?, maybe it is something they fixed between versions.

**Comment by yves8833** [comment]
Thanks i will try it.

**Comment by dianaafanador3** [comment]
Hi @yves8833 there are some users having a similar error, seems like an Xcode issue, you can follow the thread here https://github.com/realm/realm-cocoa/issues/7368

**Comment by zohairhadi** [comment]
When I updated to Xcode 13.2.1, it started showing me Swift Compiler Error in RealmSwift/SwiftUI like 

- Cannot find type 'Binding' in scope
- Unknown attribute 'StateObject'

<img width="316" alt="Screenshot 2021-12-25 at 3 30 15 PM" src="https://user-images.githubusercontent.com/45510142/147383106-a8b81e73-bb93-4786-aa9b-de9dec7639f0.png">

**Comment by vicmosin** [comment]
@zohairhadi  was you able to solve the issue?

**Comment by alissone** [comment]
It seems to work for me after changing the iOS Deployment Target of RealmSwift pod to 12.0 and do a `pod upgrade`.

**Comment by zohairhadi** [comment]
@alissone so what version did RealmSwift jump to? If it jumped to their latest version, they stated in their release that they fixed this issue. I suppose a simple `pod update` would work as well

**Comment by zohairhadi** [comment]
Furthermore, what is support for iOS 11 is needed?

**Comment by vicmosin** [comment]
It seems like I fixed the issue by just bumping the RealmSwift to the latest version (`~> 10.21`) without adjusting deployment target explicitly.

**Comment by zohairhadi** [comment]
Yes, updated to 10.21 works now. Thanks
