### ISSUE TITLE
Signed integer overflow: 16777216 * 255 cannot be represented in type 'int'

### ISSUE THREAD

**Issue by hyouuu** [realm/realm-cocoa#7096]
## Goals
No compiler warnings

## Expected Results
No compiler warnings

## Actual Results
While archiving Xcode would give:
Undefined behavior: Signed integer overflow: 16777216 * 255 cannot be represented in type 'int'
in index_string.cpp at line 408

## Steps for others to Reproduce
Use any Realm 10+ version (I've seen it for a while in 10+ releases, and right now on 10.5.1)

## Code Sample
Not related

## Version of Realm and Tooling
Realm framework version: 10.5.1

Realm Object Server version: NA

Xcode version: 12.4

iOS/OSX version: Not related

Dependency manager + version: SPM

<img width="2212" alt="Screen Shot 2021-02-04 at 11 03 18 AM" src="https://user-images.githubusercontent.com/5061867/106942447-0a334280-66d9-11eb-9690-077d2439ec9c.png">

**Comment by leemaguire** [comment]
@hyouuu I cannot reproduce this on my end, does this happen if you archive a new sample app?

**Comment by ericjordanmossman** [comment]
@hyouuu
If this is still happening can you provide the info Lee requested above ^?

**Comment by leemaguire** [comment]
Closing as there has been no further response from the author.
