### ISSUE TITLE
v10.5.2 pod not found

### ISSUE THREAD

**Issue by sacredsoul** [realm/realm-cocoa#7105]
My question is simple , I just can not find the latest pod of v10.5.2 . Sorry , I don't know if I am too early to update because it has been 14 hours since it released .
```
[!] CocoaPods could not find compatible versions for pod "RealmSwift":
  In Podfile:
    RealmSwift (= 10.5.2)

None of your spec sources contain a spec satisfying the dependency: `RealmSwift (= 10.5.2)`.
```

**Comment by leemaguire** [comment]
@sacredsoul the issue is on our end, we are working on a fix.

**Comment by leemaguire** [comment]
Issue has been resolved, closing.
