### ISSUE TITLE
How can I force trigger a sync?

### ISSUE THREAD

**Issue by sedwo** [realm/realm-cocoa#7106]
## Goals
As a user, there’s always a UI element (button or pull-to-refresh) in my app that gives me control to trigger a sync refresh anytime I want, instead of waiting on the app.

## Expected Results
I don't want to be at the whim of when Realm _decides to sync_.  As it can take a while for it to figure out that it's back online and then try to sync.  I've tested delays of over a minute.

As a user in the field that's late for dinner and just got back to my car with a slow data connection, the last thing I want is to wait for my app to figure it out and sync.  Machines should wait on us, not the other way around.

## Version of Realm and Tooling
Realm framework version: ?
  - Realm (10.5.1):
    - Realm/Headers (= 10.5.1)
  - Realm/Headers (10.5.1)
  - RealmSwift (10.5.1):
    - Realm (= 10.5.1)

Realm Object Server version: ?

Xcode version: 12.4

iOS version: 14.x

**Comment by leemaguire** [comment]
@sedwo `RLMSyncSession.resume()` might solve your issue here

**Comment by sedwo** [comment]
> @sedwo `RLMSyncSession.resume()` might solve your issue here

Tried that.  Doesn't affect my result.

**Comment by pavel-ship-it** [comment]
You can observe the sync progress with [addProgressNotification(for:mode:block:)](https://docs.mongodb.com/realm/sdk/ios/examples/sync-changes-between-devices/#check-upload---download-progress-for-a-sync-session) It could give you some information on why you can't see the result.

**Comment by sedwo** [comment]
> You can observe the sync progress with [addProgressNotification(for:mode:block:)](https://docs.mongodb.com/realm/sdk/ios/examples/sync-changes-between-devices/#check-upload---download-progress-for-a-sync-session) It could give you some information on why you can't see the result.

That doesn't really answer my question of how to force trigger a sync.

**Comment by jlavyan** [comment]
I am facing same issue. on my side sync starting only after I am write/read something to realm. so my observers triggering only after write/read something. how we can ping for sync without write/read something

**Comment by sedwo** [comment]
@tgoyne RE: [developer.mongodb.com](https://developer.mongodb.com/community/forums/t/realm-swift-tutorial-failing-offline-first-usage/14136/61)
"... it’s not hard to imagine scenarios where it’s useful (e.g. if the device has a very flakey connection we usually don’t want to kill the battery spamming connection attempts, unless the user is mashing a refresh button because they really do need the data ASAP)."

Any further thought or potential progress on this functionality?

**Comment by ericjordanmossman** [comment]
No progress, but this functionality does make sense to me. Dragging your thumb down for a refresh _is_ really common. 
@ianpward @jsflax

**Comment by ianpward** [comment]
You might try pausing first and then resuming on the syncSession - that might get what you need

**Comment by dianaafanador3** [comment]
Closing this as there is no answer from the user.
In addition to the suggestion below, if you are using SwiftUI you can use our new property wrapper `AsyncOpen`, you can find an article on how to use it here https://www.mongodb.com/developer/how-to/realm-asyncopen-autoopen/.
