### ISSUE TITLE
Swift SDk V 10.5.2 not available yet

### ISSUE THREAD

**Issue by vishaldroisys** [realm/realm-cocoa#7109]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by leemaguire** [comment]
Closing as 10.5.2 is now available on Cocoapods

**Comment by vishaldroisys** [comment]
> Closing as 10.5.2 is now available on Cocoapods

[!] CocoaPods could not find compatible versions for pod "RealmSwift":
  In Podfile:
    RealmSwift (= 10.5.2)

None of your spec sources contain a spec satisfying the dependency: `RealmSwift (= 10.5.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by vishaldroisys** [comment]
EBSMAC-Vishal:iOS_Source droisys$ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/8/a/8/AWSS3/2.22.3/AWSS3.podspec.json Response: Timeout was reached
