### ISSUE TITLE
Database contains NULL value on Object's non-optional String field (Swift)

### ISSUE THREAD

**Issue by Fab1n** [realm/realm-cocoa#7111]
## Goals
Find out how it is possible that a Database contains Objects with NULL values on fields that have always been non-optional.

## Expected Results
No NULL values should ever be stored in fields that are explicitly marked as non-optional (String fields!).

## Actual Results
We have a customer's database which contains an Object with a string field value of NULL (is NSNull).

## Steps for others to Reproduce
We cannot reproduce the issue without more information. I'll give you all information I have here so you can find out if - in older or current realm versions - it somehow was possible to store NULL on non-optional string fields.

## Explanation
We stumbled about the object with a NULL value in one of its string fields because we had users whose app crashed when migrating from 3.19.0 to 10.1.4. 
The database file version was updated there and in the Core migration logic inside `Obj obj = m_clusters.insert(obj_key, init_values);` in `bool Table::migrate_objects(ColKey pk_col_key)` in `table.cpp` it crashes then.

I compiled a debug version of Core, built a realm-cocoa version with that core containing debug symbols and was able to log the contents of the object (row) that causes the crash.

It turned out that a non-nil field of type `String` contained an `NSNull()` value.

How is this possible?

The issue really was worse in the Android version of our App. There lots more people had these crashes.
So the question is if the Android version was causing the issue and users who restored a backup of that database on iOS just got this wrong data from Android.

In Swift I didn't find a way to store a NULL value in such a field and I think this shouldn't have been the case with the older Realm version (2.1.2). But I can be wrong.

The Field gets filled in Swift, but the String value for that field is generated in C++, then Wrapped in an ObjC layer using djinni and from there used inside Swift to write to that field.
When writing to a string property of an Object the string gets converted/bridged to an NSString again as far as I can see and there should be no chance of accidentally writing an `[NSNull null]` value, right?

So the other option, what is left, is that the Realm version on realm-java was capable of writing NULL values to fields of an object, without noticing it. Java is much more dynamic than Swift (although ObjC is dynamic, too - but we're using the Swift interface here) and it could be that the value at some point became NULL and was written as NULL to disk.

Question: Should I open a ticket in `realm-java` or can you pass the question to the team from here?

### How to workaround this issue
Customers cannot open their database or backups of that database on Realm versions that updated the file format to anything greater than used in `3.19.0`.
The file version migration always crashes.
We now need to somehow open users databases using Realm `3.19.0` (the last working version) and manually set that NULL field to EmptString ("").

## Version of Realm and Tooling
The object containing the NULL string was created in 2017.
Thus I'll list here all details for that time. I'll also add details for Android because we used Realm on Android during that time, too and it could be that the data was written on Android and the DB imported to iOS. The explanation for all that is written above.

We're using RealmSwift through Cocoapods.

Realm framework version: 
iOS:             2.1.2 (now we're on 10.5.1)
Android:     io.realm:realm-gradle-plugin:2.2.2

Realm Object Server version: 
iOS:            1.0.0-BETA-4.8 (from dependencies.list for version 2.1.2)
Android:    REALM_OBJECT_SERVER_DE_VERSION=1.0.0-BETA-4.11-449 (from dependencies.list for realm-java version 2.2.2)

Xcode version: most probably 8.2/8.3 (now we're on 12)
Android Studio: I don't know

iOS/OSX version: 10 (now 14)
Android version: I don't know (in May 2017 the object was written, but the device could have had any version upon the most current Android version to this date)

Dependency manager + version: Cocoapods 1.1.1 (now we're on 1.10.0)
Android: Don't know the Gradle version at that time (cannot see it in the repo) - but it really doesn't matter in this case

**Comment by Fab1n** [comment]
I have new findings for this issue and will share them with you later. I then will maybe update this issue or close it and open a new one.

**Comment by leemaguire** [comment]
@Fab1n please continue your findings on this issue.

@cmelchior @jedelbo have you's ever seen such a scenario occurring before?

**Comment by Fab1n** [comment]
Ok, I will continue here because then we have the context.

We nailed it down and now have the underlaying `StringData` value available.
`m_data or data` has the value of `"AAAA\x11"`, the same value that will be produced using `std::string("AAAA\x11")` (`\x11` is a control character - this sometimes happens to us, that some service sends rubbish strings like this).
`m_size or size` however has the value of `18446744073709551615`, the same value as `UINT64_MAX` in Cocoa.

Remember, the value was written in 2017 (and in 2016, too, another customer reported). So we used `realm-gradle-plugin:2.2.2` on Android and `realm-cocoa 2.1.2` on iOS.

We tried to write the value on iOS with realm 3.19.0 and the value was correctly written into the DB.

There are now 2 possibilities:

1. The string object we want to write is somehow broken (don't know how this could be possible)
2. The string with the control character when written to the object's string field did produce a `StringData` object with the wrong size (maybe there was some broken conversion, maybe in Android - Java to Cpp)

The migration crash happened a lot more on Android with this broken value.

**Comment by Fab1n** [comment]
@leemaguire I think I provided a good amount of data to investigate now. 

Unfortunately I cannot provide a sample project because with `realm-cocoa` and `3.19.0` and upwards everything gets written nicely to the DB.
I cannot try much lower Realm versions because with Big Sur you cannot install such an old Xcode version, needed to compile a project with Swift 3 and the appropriate Realm Version. I would need to try some version 2 (2.1.2 or lower).

Still, I guess, because we've seen the most crashes on Android, it is highly likely that the issue arose there.
I don't know if the issue exists there now, my team is looking into it, but is also limited I think in terms of going back in our versions.
My best guess then there is that there can be a Java `String` with some contents, but the wrong length of the String (don't know if this is even possible in Java), written into the DB which took this wrong length value. Or Realm couldn't deal with the string which originally comes through C++ (`std::string("AAAA\x11")`) and gets translated to Java String (using Dropbox's `Djinni`). 

Either the Java String object is broken and Realm couldn't handle (or didn't protect against) such a malicious string or the Realm Java framework itself wrote wrong data, even if from application side everything looks fine.

The same could basically be true for the cocoa-side of things. But there I cannot see how `NSString` could deliver a broken string, I think the Class there is properly guarded against many scenarios.

**Comment by jedelbo** [comment]
@Fab1n I am sure the string "AAAA\x11" comes from a header we use in front of all data stored in the realm file. How that data can end being interpreted as user data is very strange. Since you are able to debug a case where you get this value, I am assuming that you have a file produced by a version 2 Realm. Is that correct? And if so, would you be able to share that realm file with us?

**Comment by Fab1n** [comment]
Oh, that makes things a lot more clear.
We only have 1 user's database with his password and that's how we found out the string content with the wrong length.
I didn't know that this is an internal string.
The entry with the corrupt string field has a timestamp of may 2017 at which time we used Realm 2.1.2, but we also have customers which have similar entries in 2016 where the app also crashes during migration, so it could have been introduced earlier.

Can I strip the DB down somehow or something similar in order to not share our DB Scheme and private user information? And then only share the relevant bits?
I thought about removing all other tables except the one needed for the affected object and then removing every other object...

If we didn't write "AAAA\x11", what did we write then? In the core code I only read about "AAAA". Where does the control character then come into play? Maybe we tried to write the control character only?

**Comment by jedelbo** [comment]
The header consists of 8 bytes where the first 4 bytes are 'A'. The 5th byte contains information about the width of each element and the remaining 3 bytes hold the size of the array. So the 6th byte could very well b '\0' making it look like a 5 byte string.

I am not sure how you would be able to modify the database. As I understand the problem then the crash occurs during migration, so what you have is a half way migrated realm file. And you cannot modify it before it is fully migrated. I fully understand why you would not want to share the realm file in public, but I just want you to know that you can share it privately by sending it to jorgen.edelbo@mongodb.com.

**Comment by Fab1n** [comment]
Thank you @jedelbo. 
We have a backup of the database from before the migration. This one I can open freely with 3.19.0 and thus modify freely. 
So, do you think I can strip that down?

**Comment by jedelbo** [comment]
Ok, you can of course try to strip it down and then check if the error still exists.

**Comment by jedelbo** [comment]
... but you should know that deleting the data does not remove it from the realm file and you should not try to compact the file. So if you would not hesitate to send me the stripped down version, you could just as well send me the original file.

**Comment by Fab1n** [comment]
Uh ok. When I delete something, unless the database has been compacted, the data still resides on disk, but isn't accessible through the app anymore, is that what you say?

**Comment by Fab1n** [comment]
The backup we have, already is compacted (because it was written with `writeCopyToFile`) and the data is still invalid. 
So I will try to strip everything and try if the compacted version still contains the error.

**Comment by Fab1n** [comment]
@jedelbo Thanks for your fix. It seems to work for some customers.

We still have currently one customer where it crashes during file migration. It crashes when trying to `migrate_objects` on `Table` and then when `realm::ArrayString::init_from_mem`.

Here is the relevant part of the stackframe:
```
0   libsystem_kernel.dylib        	0x00000001bdf6a84c 0x1bdf43000 + 161868
1   libsystem_pthread.dylib       	0x00000001da2be9e8 0x1da2b4000 + 43496
2   libsystem_c.dylib             	0x000000019b5298f4 0x19b4b6000 + 473332
3   <our app>                       	0x0000000106db3108 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (in <our app>) + 0
4   <our app>                       	0x0000000106db3250 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (in <our app>) + 328
5   <our app>                       	0x0000000106db33c8 realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) (in <our app>) + 328
6   <our app>                       	0x0000000106c6fea0 realm::ArrayString::init_from_mem(realm::MemRef) (in <our app>) + 800
7   <our app>                       	0x00000001056b54a8 realm::BPlusTree<realm::StringData>::cache_leaf(realm::MemRef) (in <our app>) (bplustree.hpp:574)
8   <our app>                       	0x0000000106c74afc realm::BPlusTreeInner::bptree_access(unsigned long, realm::util::FunctionRef<void (realm::BPlusTreeNode*, unsigned long)>) (in <our app>) + 348
9   <our app>                       	0x0000000106d7c290 realm::Table::migrate_objects(realm::ColKey) (in <our app>) + 5388
10  <our app>                       	0x0000000106c9ae24 realm::Transaction::upgrade_file_format(int) (in <our app>) + 2244
11  <our app>                       	0x0000000106c8b9f4 realm::DB::upgrade_file_format(bool, int, int, int) (in <our app>) + 288
12  <our app>                       	0x0000000106c8990c realm::DB::do_open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, realm::DBOptions) (in <our app>) + 3472
13  <our app>                       	0x0000000106c8bff0 realm::DB::open(realm::Replication&, realm::DBOptions) (in <our app>) + 244
14  <our app>                       	0x0000000106c90160 realm::DB::create(realm::Replication&, realm::DBOptions) (in <our app>) + 392
15  <our app>                       	0x0000000106e59f88 realm::_impl::RealmCoordinator::open_db() (in <our app>) + 1296
16  <our app>                       	0x0000000106e58f64 realm::_impl::RealmCoordinator::do_get_realm(realm::Realm::Config, std::__1::shared_ptr<realm::Realm>&, realm::util::Optional<realm::VersionID>, realm::util::CheckedUniqueLock&) (in <our app>) + 72
17  <our app>                       	0x0000000106e58d88 realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config, realm::util::Optional<realm::VersionID>) (in <our app>) + 400
18  <our app>                       	0x0000000106eb8694 realm::Realm::get_schema_version(realm::Realm::Config const&) (in <our app>) + 136
19  <our app>                       	0x0000000105706da0 +[RLMRealm schemaVersionAtURL:encryptionKey:error:] (in <our app>) (RLMRealm.mm:0)
20  <our app>                       	0x000000010574777c schemaVersionAtURL(_:encryptionKey:) (in <our app>) (Migration.swift:55)
```

I think this still has to do with invalid data and I am kind of lost right now. We don't seem to get the users data.
I really hope you can deduce some scenarios from this stackframe above.

The user is just like the user from the case of this issue. He cannot open his 3.19.0 DB with 10.7.0, also with the core fix applied.
Can you help us further?

**Comment by jedelbo** [comment]
Unfortunately there is too little info in the stack dump to figure out what could be wrong. We would need an actual file.
