### ISSUE TITLE
Compile warning - Umbrella header does not include '/core/realm.h'

### ISSUE THREAD

**Issue by LowAmmo** [realm/realm-cocoa#7113]
!!! MANDATORY TO FILL OUT !!!

## Goals

No warnings when building

## Expected Results

Have no warnings when building

## Actual Results

Seeing a warning - 

     Umbrealla header for module 'Realm' does not include header '/core/realm.h'

## Steps for others to Reproduce

Build 10.5.2, using cocoapods and Xcode 12.4

## Code Sample

In a podspec - 

    s.dependency 'RealmSwift', '~> 10.5.2'

## Version of Realm and Tooling

Realm framework version: 10.5.2

Realm Object Server version: n/a

Xcode version: 12.4

iOS/OSX version: 14.4

Dependency manager + version: cocoapods - 1.10.1

**Comment by Ariandr** [comment]
Have the same issue switching from 5.5 to 10.6

**Comment by dianaafanador3** [comment]
Hi @LowAmmo we will check this and get back to you as soon as possible

**Comment by LowAmmo** [comment]
I know it's not really hurting anything....and is just a little OCD. But, I appreciate you putting some attention on it!

-Thanks!

**Comment by ManueleGrassi** [comment]
I have the same issue with Realm and RealmSwift 10.6.0

**Comment by mrjslau** [comment]
Same issue with Realm and RealmSwift 10.7.0.  Clean Build Folder and Pod reinstall does not help.

**Comment by dianaafanador3** [comment]
@ManueleGrassi, @mrjslau we will try to remove this warning in future releases.

**Comment by DHaacke** [comment]
Same issue here with 10.7.0 as of Feb 28

**Comment by SuperTully** [comment]
Same issue here, using latest GA versions as of 3/1/21.  What's interesting is that I inadvertently committed the Pods directory to my local git repository, and then the warning went away, but then I could no longer push committed changes to my remote repository for whatever reason.  So I made a new clone in Xcode and re-installed the Pod, and then the warning came back (but at least I can push to the remote repository again!).

**Comment by ohohohoh** [comment]
I had the same issue. Managed to solve the problem by changing the Location to 'Relative to Developer Directory' (in the Identity and Type right hand window) 
this is for the Deployment  > Installation Directory  of RealmSwift
