### ISSUE TITLE
Undefined symbols for architecture x86_64 "protocol descriptor for Swift.Identifiable"

### ISSUE THREAD

**Issue by EricWiener** [realm/realm-cocoa#7114]
## Goals
I am trying to make a minimal example of RealmJS + RealmSwift to help RealmJS debug an [issue](https://github.com/realm/realm-js/issues/3588). When trying to make this minimal example, I was unable to compile RealmSwift with an error: `Undefined symbol: protocol descriptor for Swift.Identifiable`

## Expected Results
I expected to be able to compile (or at least to run into the same issue I described in the RealmJS issue).

## Actual Results
```
Undefined symbols for architecture x86_64:
  "protocol descriptor for Swift.Identifiable", referenced from:
      protocol requirements base descriptor for RealmSwift.ObjectKeyIdentifiable in libRealmSwift.a(Combine.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps for others to Reproduce
Here is a [Github repo](https://github.com/EricWiener/react-native-realm-demo) with the sample project. It's a react-native project, so you will need to set it up as such:
1. [Install npm](https://www.npmjs.com/get-npm)
2. Install Yarn: `npm install --global yarn`
3. CD into the repository and run `yarn install`
4. CD into the `ios` folder and run `pod install`
5. Open up the .xcworkspace and run the app

## Code Sample
Please see above

## Version of Realm and Tooling
```
ProductName:	macOS
ProductVersion:	11.2.1
BuildVersion:	20D74

/Applications/Xcode.app/Contents/Developer
Xcode 12.4
Build version 12D4e

/usr/local/bin/pod
1.10.1
Realm (10.5.1)
RealmSwift (10.5.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

carthage not found
(not in use here)

/usr/bin/git
git version 2.24.3 (Apple Git-128)
```

**Comment by dianaafanador3** [comment]
Hey @EricWiener, We'll try to reproduce this and get back ass soon as we can

**Comment by EricWiener** [comment]
@dianaafanador3 thanks so much! I just updated the Podfile in the example to have compatible versions for RealmSwift and RealmJS. The issue still persists, but hopefully, this will be one less problem to deal with.

**Comment by dianaafanador3** [comment]
Hi @EricWiener I haven't had time to get into this. Have you been able to fix this issue?, if the response is no, i'll take a look at this next week. Also, can you test this with our latest version of realm version 10.7.2

**Comment by EricWiener** [comment]
@dianaafanador3 this is still an issue using RealmSwift 10.4.0. Unfortunately, I can't upgrade RealmSwift to 10.7.2 because RealmJS and RealmSwift need to have matching Core + Sync versions

Currently, RealmJS (10.2.0) is on RealmSync v10.1.6 and RealmCore v10.1.4. It looks like RealmSwift (10.7.2 ) is on RealmSync v10.1.5 and RealmCore v10.5.5, so that won't be compatible.

**Comment by mungbeans2** [comment]
I'm having the same problem using RealmSwift 10.7.2, however in my case I'm trying to run on iOS so the error is 

Undefined symbols for architecture arm64: "protocol descriptor for Swift.Identifiable", referenced from: l_got.$ss12IdentifiableMp in libRealmSwift.a(Combine.o) ld: symbol(s) not found for architecture arm64

Its very easy to reproduce - create the minimal React Native AwesomeApp Xcode project template (from the getting started with React Native web pages).

Now to the podfile that gets generated try adding RealmSwift*, do pod install and try and build the Xcode workspace and you get this error.


*I've been trying various variations of specifying RealmSwift in the pod file to eliminate pod warnings/errors. At the moment I have the following in the pod file:
 pod 'Realm', :modular_headers => true
 pod 'RealmSwift', :modular_headers => true

**Comment by junaid-cloud9** [comment]
i am also facing this issue. @mungbeans2 any luck ?

**Comment by dianaafanador3** [comment]
Hi @junaid-cloud9 I'm taking a look at this, trying to reproduce it. On the meantime can you elaborate more on the error, and how to reproduce it?

**Comment by junaid-cloud9** [comment]
specific error is this

Undefined symbols for architecture arm64: "protocol descriptor for Swift.Identifiable", referenced from: l_got.$ss12IdentifiableMp in libRealmSwift.a(Combine.o) ld: symbol(s) not found for architecture arm64

Steps to reproduce are exactly the same as these

> @dianaafanador3
> I'm having the same problem using RealmSwift 10.7.2, however in my case I'm trying to run on an iPhone so the error is
> 
> _Undefined symbols for architecture arm64: "protocol descriptor for Swift.Identifiable", referenced from: l_got.$ss12IdentifiableMp in libRealmSwift.a(Combine.o) ld: symbol(s) not found for architecture arm64_
> 
> Its very easy to reproduce - create the minimal React Native AwesomeApp Xcode project template (from the getting started with React Native tutorial web pages https://reactnative.dev/docs/environment-setup).
> 
> Now to the podfile that gets generated add RealmSwift(*), run pod install and then try and build the Xcode workspace and you get this error.
> 
> (*) I've been trying various variations of specifying RealmSwift in the pod file to eliminate pod warnings/errors. At the moment I have the following in the pod file:
> pod 'Realm', :modular_headers => true
> pod 'RealmSwift', :modular_headers => true

**Comment by mungbeans2** [comment]
> i am also facing this issue. @mungbeans2 any luck ?

@junaid-cloud9 If I dropped down to version 4.4.0 of RealmSwift/Realm then its possible to eliminate the warning

**Comment by jsflax** [comment]
@EricWiener could you elaborate on how you are using RealmJS and RealmSwift? Seems like the big hint here.

**Comment by mungbeans2** [comment]
> @EricWiener could you elaborate on how you are using RealmJS and RealmSwift? Seems like the big hint here.

Errm, as mentioned its totally possible to reproduce this issue without the use of RealmJS at all.

**Comment by dianaafanador3** [comment]
Hi @EricWiener i was able to reproduce this issue and I think I have a workaround that will help you run your project.

I would first recommend you  to add `use_frameworks!` to you Podfile, which tells cocoa pods to use dynamic libraries instead of static libraries. You can even remove `RealmSwift` from the podfile, as your project is in objective-c and there is no need to import RealmSwift to you main project.

You can see a sample of the Podfile that worked on my project
``` shell
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!

target 'RNRealm' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Realm', :modular_headers => true
  pod 'IceCream', :git => 'https://github.com/EricWiener/IceCream.git', :commit => '37f73610f23335de98082a96be5478749ae25fce'

  target 'RNRealmTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'RNRealm-tvOS' do
  # Pods for RNRealm-tvOS

  target 'RNRealm-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

And then finally, i would recommend you to add a swift file into your project, this will create automatically a bridging header for your project, to tell your compiler there is some swift code within you project (your IceCream library and RealmSwift which is a subdependency of your library)

Let me know if you have anymore questions

**Comment by dianaafanador3** [comment]
@junaid-cloud9 and @mungbeans2  you can follow the below guide for your projects if you're case is similar.
I also uploaded a playground using react-native/realm in swiftUI which you can use an example for your projects https://github.com/dianaafanador3/PlaygroundReactRealmSwiftUI

**Comment by mungbeans2** [comment]
@dianaafanador3 Hello, unfortunately for the workaround to work its necessary to comment out flipper, and flipper is important to have enabled when running React Native project

**Comment by EricWiener** [comment]
@dianaafanador3 thanks so much! I will check this out soon and get back to you.

@mungbeans2 I believe flipper is commented out because of an issue with React Native not Realm. You might have luck using Flipper following the solution I mentioned [here](https://github.com/facebook/react-native/issues/30922#issuecomment-776758668)

**Comment by dianaafanador3** [comment]
@mungbeans2 did you check https://github.com/dianaafanador3/PlaygroundReactRealmSwiftUI, on that example I'm using flipper with a swift project and it's working fine

**Comment by EricWiener** [comment]
@dianaafanador3 your changes made the demo work perfectly! Thanks so much!

Would you mind explaining why the RealmSwiftUI demo Podfile doesn't need `use_frameworks!` and does need to specify `pod 'RealmSwift'`, but the Podfile for my example project doesn't. Aren't all React Native projects using Objective-C?

**Comment by dianaafanador3** [comment]
@EricWiener I don't have much that much experience in react-native but taking a look at the documentation (https://reactnative.dev/docs/integration-with-existing-apps), i think you can integrate react-native components into any swift/objective-c/java project. And the use of use_frameworks! in this case is to tell cocoapods to use dynamic libraries instead of static libraries for our swift libraries, I think in this case solve the issue of interoperability between your objective-c project and your swift libraries.

**Comment by EricWiener** [comment]
Got it. Thanks so much for the help. I'll look into it more. A bit puzzled because RealmJS + RealmSwift works perfectly in my existing apps (without specifying `use_frameworks!` or included `RealmSwift` in the Podfile), but only works in the new app with your workaround.

Regardless, thanks so much for your help and for solving this issue. I'll mark it as closed now.

**Comment by Gregoirevda** [comment]
I had this error for a while and fixed it by adding
`"$(SDKROOT)/usr/lib/swift"` in the build settings of the **project** for `LIBRARY_SEARCH_PATH`

It's important that this is the 1st value in the list.

Your `LIBRARY_SEARCH_PATH` should look like this
```
$(SDKROOT)/usr/lib/swift
$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
$(inherited)
```
