### ISSUE TITLE
"mmap() failed: Cannot allocate memory size" and "Number of active versions exceeded the limit" crashes

### ISSUE THREAD

**Issue by lidorgotech** [realm/realm-cocoa#7115]
## Goals
No crash when adding or updating MessageObject.

## Expected Results
No crash when adding or updating MessageObject.

## Actual Results
Crash when adding or updating MessageObject.

## Steps for others to Reproduce
Calling create and update functions multiple times.

## Code Sample
https://gist.github.com/lidorgotech/4cbf263ad5ee9346c6232f88efa40309

## Version of Realm and Tooling
Realm framework version: 10.3.0

Realm Object Server version: 1.0

Xcode version: 12.4

iOS/OSX version: 14.4

Dependency manager + version: CocoaPods

## Explaination
We are building a messaging application and some of our users experience crashes like this one:
**mmap() failed: Cannot allocate memory size: 63963136 offset: 0**

We think the problem is caused by multiple versions of the same object, **MessageObject**, because when we are setting maximumNumberOfActiveVersions to 32, the application crashes in less than a minute:
**Number of active versions (33) in the Realm exceeded the limit of 32**

The crashes are happening in 3 main functions: **writeMessage, updateMessage, updateMessageUserAck** which makes sense as all three of them are handling with MessageObject.
The problem is, we can't find the place where multiple versions of this object are created. We are using RxSwift to get updates from Realm but we are not sure it causes the problem.
We attached added the entire DataService file to this issue.

**Comment by leemaguire** [comment]
@lidorgotech If you could also post some stack traces / crash logs it would be a great help. I took a look at the gist. I'd liked to know what `.detached()` does. Also with methods such as `writeMessage` does something continue to hold onto the `MessageObject` that was passed in?

**Comment by lidorgotech** [comment]
Hi @leemaguire, here is the crash log: https://gist.github.com/lidorgotech/1d36306bbeff01ff45142fbb9fd6ba06
And here is the use of writeMessage: https://gist.github.com/lidorgotech/81e13f8926878b7362242623866eaaf0

**Comment by leemaguire** [comment]
@lidorgotech Could you show the code for `detached()`? what does the lifecycle of a `MessageObject` look like? Does it have an owner? Is it transient? etc.

**Comment by lidorgotech** [comment]
`detached()` looks like this: 

```
extension Object: DetachableObject {
    func detached() -> Self {
        let detached = type(of: self).init()
        for property in objectSchema.properties {
            guard let value = value(forKey: property.name) else {
                continue
            }
            if let detachable = value as? DetachableObject {
                detached.setValue(detachable.detached(), forKey: property.name)
            } else { // Then it is a primitive
                detached.setValue(value, forKey: property.name)
            }
        }
        return detached
    }
}
```

The lifecycle starts and ends in those two functions, `sendMessage` and `writeMessage`, as I understand.

**Comment by leemaguire** [comment]
From `sendMessage`, where is `MessageObject` being passed in from / where is it stored? I can't see why you would need to call `.detached` from line 14 in `sendMessage`. It would be good if you could send us a small sandbox app / reproduction case to realm-help@mongodb.com

**Comment by ericjordanmossman** [comment]
@lidorgotech 
Are you able provide what Lee mentioned?

**Comment by leemaguire** [comment]
@lidorgotech were you able to solve your issue?

**Comment by bmunkholm** [comment]
@lidorgotech We will need more information from you to help on this. Thanks!
