### ISSUE TITLE
Not obvious how to build the Examples, & `build.sh` fails

### ISSUE THREAD

**Issue by iandundas** [realm/realm-cocoa#7120]
## Goals
Run the ListSwiftUI example 

## Expected Results
- (perform some documented installation)
- Run the ListSwiftUI scheme
- Build successfully

## Actual Results
Build error:

![CleanShot 2021-02-16 at 09 57 09](https://user-images.githubusercontent.com/1131967/108040331-78fb8e80-703d-11eb-9632-13a51e224851.png)

And when building just RealmSwift:
![CleanShot 2021-02-16 at 09 57 19](https://user-images.githubusercontent.com/1131967/108040353-7e58d900-703d-11eb-8cec-2115204647b0.png)

Browsing to the `/examples/installation` folder shows a `build.sh` but it's only for testing.

Browsing to `/build.sh`, I see I can run `./build.sh examples-ios` but that itself fails too: 

![image](https://user-images.githubusercontent.com/1131967/108044657-d6460e80-7042-11eb-854a-f82ad4c7708e.png)

## Steps for others to Reproduce
See above, primarily that `./build.sh examples-ios` fails with error shown above.

## Code Sample
n/a

## Version of Realm and Tooling
Realm framework version: Current `master` - `44b9632b22240`

Realm Object Server version: n/a

Xcode version: 12.4

iOS/OSX version: macOS 10.15.7

Dependency manager + version: n/a

**Comment by iandundas** [comment]
The solution is to `build.sh build` first, before `build.sh examples-ios`

I just feel that this process could be documented, as probably others would stumble over the same stuff of just opening the example projects and expecting them to build

**Comment by dianaafanador3** [comment]
Hello @iandundas. I guess you already figure it out. Thanks for the suggestions about the documentation, We'll review it and make sure everything is as simple and explanatory as possible.

**Comment by iandundas** [comment]
Cool - happy to close it, this can be googled by someone in my shoes (probably me in 6 months)
