### ISSUE TITLE
Disable encryption

### ISSUE THREAD

**Issue by mohsinalimat** [realm/realm-cocoa#7125]
Hello,

I want to disable the encryption on the realm database.

How to solve it?

I use like this 

```
var config = Realm.Configuration()
config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent("users.realm")
print("config.fileURL --- \(config.fileURL)")
config.encryptionKey = RealmKeychain.getKey() as Data
```

**Comment by dianaafanador3** [comment]
Hi @mohsinalimat, if you don't set up a `encryptionKey` into the realm configuration, you would have an unencrypted realm. 
```swift
var config = Realm.Configuration()
config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent("users.realm")
let realm = try! Realm(configuration: config)
```

You can even use realm default configuration to set up your realm database

```swift
var config = Realm.Configuration.defaultConfiguration
config.fileURL!.deleteLastPathComponent()
config.fileURL!.appendPathComponent(user)
config.fileURL!.appendPathExtension("realm")
let realm = try! Realm(configuration: config)
```
Refer to realm documentation https://docs.mongodb.com/realm/ios/open-a-realm/ for more information, and if you have anymore question feel free to ask.

**Comment by mohsinalimat** [comment]
@dianaafanador3 I use your comment code but not the open realm database. you can see my attached a screenshot.

![Screenshot 2021-02-20 at 5 00 33 PM](https://user-images.githubusercontent.com/973676/108593987-29022c00-739d-11eb-8b8a-0f46a2ef9273.png)

**Comment by mohsinalimat** [comment]
Also i set 

  ```
var config = Realm.Configuration()
  config.fileURL = config.fileURL!.deletingLastPathComponent().appendingPathComponent("users.realm")
  print("config.fileURL --- \(config.fileURL)")
  =config.encryptionKey = nil
```

but not working same error

**Comment by dianaafanador3** [comment]
Hi @mohsinalimat there is no need to set the encryptionKey to nil, if you don't set up an `encryptionkey` into the configuration, the realm does not encryption by default. 
Have in mind that if you already created a realm with an encryption key, setting the `encryptionkey` to nil or not setting it up later, will not make the realm unencrypted, and will cause an error when opening the realm. 
If you want to test an unencrypted realm, clear any App data on the simulator (`~/Library/Developer/CoreSimulator/Devices/`), or delete the App before setting again an unencrypted realm.

**Comment by mohsinalimat** [comment]
I try with the above comment but not working.

**Comment by mohsinalimat** [comment]
Same issue when I use below the repo

https://github.com/RMizin/FalconMessenger

**Comment by dianaafanador3** [comment]
On the FalconMessenger project, when they initialise the realm database, they use a `encryptionKey`, that's why the realm file need an encryption key to read.
They have this on their code
```swift
let realm = try! Realm(configuration: RealmKeychain.realmUsersConfiguration())
```
if you replace the below code to this on their project, the realm file will not be encrypted
```swift
let realm = try! Realm()
```

**IMPORTANT**: Clear app data before doing this changes, so you can test with a clean state an the realm will be created as unencrypted

**Comment by mohsinalimat** [comment]
@dianaafanador3 

I try with this in my project and FalconMessenger project but getting the same result.

`let realm = try! Realm()
`

And, I delete my app from my iPhone as well.

**Comment by dianaafanador3** [comment]
@mohsinalimat Are you using MongoDB Realm Studio to read the realm file?

**Comment by mohsinalimat** [comment]
Realm Browser Version 3.0.1 (98)

**Comment by dianaafanador3** [comment]
Can you please use MongoDB Realm Studio instead https://docs.mongodb.com/realm-legacy/products/realm-studio.html

**Comment by mohsinalimat** [comment]
Ok, let me check.

**Comment by mohsinalimat** [comment]
Now, it's working fine.

Thanks, @dianaafanador3

**Comment by dianaafanador3** [comment]
@mohsinalimat 🎉 yeii, if you have any more issues let us know.

**Comment by mohsinalimat** [comment]
Sure
