### ISSUE TITLE
FR: Split Carthage.zip into Realm-swift_iOS.zip, Realm-swift_MacOs.zip etc

### ISSUE THREAD

**Issue by jesusmateos1234** [realm/realm-cocoa#7128]
!!! MANDATORY TO FILL OUT !!!

## Goals
Split Carthage zip into frameworks zip to not download all platforms nor Frameworks needed.

**Comment by tgoyne** [comment]
The layout of the Carthage zip is dictated by Carthage, not us.

**Comment by jesusmateos1234** [comment]
@tgoyne not is for Carthage... Other repositories has this split.
