### ISSUE TITLE
When updating an Object's property, Object Change Listener always calls .delete block

### ISSUE THREAD

**Issue by homathko** [realm/realm-cocoa#7130]
## Goals
To observe changes to an object using object change listener

## Expected Results
The appropriate switch case is executed (i.e. `.change(_:_): { ... }`)

## Actual Results
Only the `.delete` case is executed, but object still exists

## Steps for others to Reproduce
1. Get the id of an existing object in your realm
2. Run the included test function with the object's type and id - it should run for a few minutes
3. In MongoDB Atlas, modify a property of the object with the id
4. Observe the execution of the object change handler

## Code Sample
```
func testRealmObjectChange () {
        let x = XCTestExpectation()

        let target = { ... } // configuration is for a sync'd realm

        Realm.asyncOpen(configuration: target.configuration()) { result in
            switch result {
                case .success(let realm):
                    if let object: Event = realm.object(
                            ofType: Event.self,
                            forPrimaryKey: try! ObjectId(string: "<< add_id_here >>")
                    ) {
                        dump(object)
                        self.testToken = object.observe { change in
                            switch change {
                                case .change(let object, let props):
                                    print("Changed")
                                case .deleted:
                                    print("Deleted")
                                case .error(let err):
                                    print(err.localizedDescription)
                            }
                        }
                    }
                case .failure(let err):
                    print(err.localizedDescription)
            }
        }

        wait(for: [x], timeout: 300.0)
    }
```
## Version of Realm and Tooling
RealmSwift SDK v10.5.1
Realm Object Server version: ?
Xcode version: 12.3

iOS/OSX version: 14.3

Dependency manager + version: Swift Package Manager

## More Info
In `RealmSwift/Object.swift`:
```
public func observe<T: Object>(on queue: DispatchQueue? = nil,
                                   _ block: @escaping (ObjectChange<T>) -> Void) -> NotificationToken {
        precondition(self as? T != nil)
        return RLMObjectBaseAddNotificationBlock(self, queue) { object, names, oldValues, newValues, error in
            if let error = error {
                block(.error(error as NSError))
                return
            }
            guard let names = names, let newValues = newValues else { // object, names, oldValues, newValues and error are all nil
                block(.deleted)
                return
            }

            block(.change(object as! T, (0..<newValues.count).map { i in
                PropertyChange(name: names[i], oldValue: oldValues?[i], newValue: newValues[i])
            }))
        }
    }
```

**Comment by tgoyne** [comment]
Document replace operations from Mongo get translated as a delete followed by creating a new object with the same id, which in Realm will show up as a deletion notification but an object with that PK will still exist if you query for it afterwards. If you're explicitly using updateDocument() and it's still doing that then that sounds like a bug in the server.

**Comment by homathko** [comment]
If that is the case, what is the best practice for working around this? I need to listen for updates at the property level. It would seem that each time I receive a `.delete` event, I need to overwrite the existing `NotificationToken` with the result of a new `.observe` call. Even then, I would not get any info on which property changed. And what happens when the object is deleted? How would I be able to distinguish what's happening other than querying a final time to prove that the object with that PK is no longer? I feel like I'm missing something very straightforward. I understand your explanation of how Mongo handles document updates (or replaces) but why, oh why, would the Realm API send a delete event for an object that has not been deleted?

**Comment by nirinchev** [comment]
I guess the most straightforward solution would be to update the document on the server rather than replace it. Would it be possible to modify your server-side code to call the update API instead of the replace ones? We could definitely go for a first-party solution - either support replace at the sync protocol level or have the SDK special-case delete+create for an object with the same primary key, but that will require a fair amount of design considerations and is unlikely to be done in the short term.

**Comment by homathko** [comment]
Thank you, this has made it clearer for me. I misunderstood @tgoyne's response. I was attempting to simulate an update using Atlas - but now I understand that is not suitable since it translates to the client incorrectly. If I run updates from the client, it works as expected. Thank you for your time!

**Comment by nirinchev** [comment]
No problem, happy to hear you got things working! The data explorer behavior in Atlas has been consistently tripping folks who want to just try things out quickly, so we'll definitely want to find a more robust solution there.

**Comment by homathko** [comment]
I found the Realm Studio app to be quite useful for a lot of my testing (although now the MongoDB Realm Studio apparently does not allow connecting to a cloud realm - only local files, which I find odd)

**Comment by DominicFrei** [comment]
It looks to me like this issue was resolved so I am going to close it.

Feel free to re-open at any time if there is anything open in here.
