### ISSUE TITLE
SwiftUI: RLMException thrown when freezing RealmSwift.List<Item>

### ISSUE THREAD

**Issue by SecyWecy** [realm/realm-cocoa#7133]
!!! MANDATORY TO FILL OUT !!!

Hi, 
 The following error occurs whenever I attempt to freeze a RealmSwift.List:

  ```Terminating app due to uncaught exception 'RLMException', reason: 'This method may only be called on RLMArray    instances retrieved from an RLMRealm' ```

I am following this example https://docs.mongodb.com/realm/ios/swiftui/ and so I have something of this nature in my project: 

``` 
... 
 List {
       if let items = viewModel.items {
               ForEach(items.freeze()){ item in
                   ItemRowView(notification: getThawedItem(item))
           }
      }
 }
...
```

and in the view model 

```
    @Published var  items: RealmSwift.List<Item>?
```

## Version of Realm and Tooling

Realm framework version: 10.5.2

Xcode version: 12.4 

iOS/OSX version: iOS 14

**Comment by DominicFrei** [comment]
@SecyWecy Can you show us some more code around the `items` property? I would especially be interested in how it gets set and what kind of data (or rather type) was set there.

**Comment by jsflax** [comment]
@SecyWecy you cannot freeze Objects/Lists that are not managed by a realm, which is what the error message is saying. The swiftUI example is also out of date (we are in the process of updating it). Please use the propertyWrappers we introduced in [10.6.0](https://github.com/realm/realm-cocoa/releases/tag/v10.6.0). There is an example in the examples directory in the realm-cocoa repo called ListSwiftUI that shows proper usage.

This feature obviates the need to be freezing or thawing your Realm types.

Let us know if you need any help implementing the new propertyWrappers, otherwise, please close this ticket out once you're ready.

**Comment by SecyWecy** [comment]
@DominicFrei Here is the code around the items property.
The class inheriting for ObservableObject:

```
class ItemsObservableObject: ObservableObject{
    
    /// Cancellables to be retained for any Future.
    private var cancellables = Set<AnyCancellable>()
    
    @Published var items: RealmSwift.List<Item>?
    
    init() {
        getItems()
    }
    
    func getItems(){
        let realmPublisher = PassthroughSubject<Realm, Error>()
        
        realmPublisher.sink { result in
            // Check for failure.
            if case let .failure(error) = result {
                print("Failed to log in and open realm: \(error.localizedDescription)")
            }
        } receiveValue: { realm in
            // The realm has successfully opened.
            let items = realm.objects(Item.self)
            
            if items.count > 0{
                let list = RealmSwift.List<Item>()
                list.append(objectsIn: items)
                self.items = list
            }
        }
        .store(in: &cancellables)
        
        // Directly open the default local-only realm.
        realmPublisher.send(try! Realm())
    }
```

The Item data class:

```
class Item: Object, Identifiable{
    @objc dynamic var id: String = ""
    @objc dynamic var message: String? = nil
    @objc dynamic var title: String? = nil

    override static func primaryKey() -> String? {
          return "id"
     }
}
```

**Comment by SecyWecy** [comment]
@jsflax Thank you for this timely update.

**Comment by DominicFrei** [comment]
@SecyWecy Did the information provided by Jason solve your problem? Please let me know if there are unanswered questions.

**Comment by SecyWecy** [comment]
@DominicFrei
Yes, the information provided by @jsflax  solved  my problem. Thank yay

**Comment by SecyWecy** [comment]
@DominicFrei
Yes, the information provided by @jsflax  solved  my problem. Thank you
