### ISSUE TITLE
Crash on watching the change of the collection due to Realm Sync

### ISSUE THREAD

**Issue by ananfang** [realm/realm-cocoa#7134]
!!! MANDATORY TO FILL OUT !!!

## Goals
Using app.currentUser?.mongoClient("mongodb-atlas").database(named: "database-name").collection(withName: "collection-name").watch() to watch the change of the collection. (This database is set for Realm Sync)

## Expected Results
It will get the notification when the change is happened in that collection.

## Actual Results
If using realm.write {} block to insert / update / delete document, it will crash due to 
`
case realm::bson::Bson::Type::Uuid:
REALM_COMPILER_HINT_UNREACHABLE();
`

## Steps for others to Reproduce
1. make sure the collection is set for Realm Sync
2. All Realm Sync functions work well
3. Using watch() method to watch the change of the collection will be crashed

## Version of Realm and Tooling

Realm framework version: 10.6.0

Xcode version: 12.4

iOS/OSX version: 14.0

**Comment by DominicFrei** [comment]
@ananfang I could not reproduce this. Hence I want to try and understand your code better.
Can you maybe show some example code here? I'd like to understand better what exactly you are doing.

And where exactly the crash happens:
In `Actual Results` you say the crash happens on `realm.write`.
In `Steps for others to Reproduce` you say the crash happens on `watch()`.

Also, you can maybe show us the stack trace of the crash?
Or maybe even a small sample repo to reproduce this?
