### ISSUE TITLE
App crash after update 10.6.0

### ISSUE THREAD

**Issue by mkchoi80** [realm/realm-cocoa#7140]
!!! MANDATORY TO FILL OUT !!!

## Goals
Realm-related issues are being registered in crashlycits after 10.6.0 update. But we do not have a history of realm related modifications and crash logs are not registered when reverting to the previous version.
It is difficult to analyze only with logs, so please register an issue.

<img width="928" alt="스크린샷 2021-02-24 오후 3 29 11" src="https://user-images.githubusercontent.com/13324356/108964132-6c6eda00-76be-11eb-9a8b-370deaafc4eb.png">
<img width="528" alt="스크린샷 2021-02-24 오후 3 29 25" src="https://user-images.githubusercontent.com/13324356/108964141-6ed13400-76be-11eb-9856-70fc2ae0e216.png">
## Expected Results
We hope that no crash will occur even if it is updated.

## Actual Results
App  sometimes crashed

## Steps for others to Reproduce
Previous version download and update current version, goto main menu => sometimes crash 

## Code Sample
import RealmSwift
import Realm

@objcMembers
class TALogModel: Object {
    dynamic var date: String?
}

## Version of Realm and Tooling

Realm framework version: ?
10.6.0
Xcode version: ?
12.4
iOS/OSX version: ?
ios 14
Dependency manager + version: ?

**Comment by tgoyne** [comment]
This is probably fixed by 10.7.0.

**Comment by DominicFrei** [comment]
@mkchoi80 Can you give https://github.com/realm/realm-cocoa/tree/v10.7.0 a try? Does this solve your problem?

**Comment by mkchoi80** [comment]
@DominicFrei The problem does not occur after updating to v1.0.7  
Thanks

**Comment by DominicFrei** [comment]
Great. Thank you for the feedback, @mkchoi80 !
