### ISSUE TITLE
Diacritic insensitive [d] not working

### ISSUE THREAD

**Issue by leocassioo** [realm/realm-cocoa#7142]
!!! MANDATORY TO FILL OUT !!!

## Goals

Perform searches using diacritic insensitive [d]

## Expected Results

return items with special characters (é -> e, ã -> a, ...)

## Actual Results

no results are returned when searching for an item that has a special character.
Example: researched "depressao", I should return the records containing "depressão"

## Code Sample

``` sql
(
   title BEGINSWITH[cd] '\(key)'
   OR
   title CONTAINS[cd] ' \(key)'
)
```

## Version of Realm and Tooling

Realm framework version: 10.7.0 

Xcode version: 12.4

iOS/OSX version: 14.4

**Comment by samuelgambs** [comment]
same problem here...

**Comment by DominicFrei** [comment]
@leocassioo @samritchie Can you have a look at https://github.com/DominicFrei/Playground/tree/realm-cocoa/issues/7142 ?

I tried to reproduce this issue and it seems to work fine on my side.

Can you maybe provide a code example of your own?

**Comment by leocassioo** [comment]
> @leocassioo @samritchie Can you have a look at https://github.com/DominicFrei/Playground/tree/realm-cocoa/issues/7142 ?
> 
> I tried to reproduce this issue and it seems to work fine on my side.
> 
> Can you maybe provide a code example of your own?

Thank you very much for your answer, it helped me a lot.
The problem was with a second filter that was applied to the application's business rule.
Where I compared the searched word with the found string. 
``` swift
if key.title.folding(options: .diacriticInsensitive, locale: .current).lowercased().contains(searchedWord) {
   ....
}
```

**Comment by DominicFrei** [comment]
@leocassioo Glad I could help. And thank you for letting us know what the actual problem was! :)

@samuelgambs Does this also solve your problem?
