### ISSUE TITLE
Property Wrapper for String Enum

### ISSUE THREAD

**Issue by starletsky** [realm/realm-cocoa#7149]
## Goals
I'm trying to write Property Wrapper for String Enum

## Expected Results
Realm should save wrappedValue from Property Wrapper as basic Realm property

## Actual Results
Property Wrapper work as expected, but Realm doesn't save it's wrappedValue

## Code Sample
```
@propertyWrapper
struct RealmStringEnumWrapper<V, R: RawRepresentable> {
    var wrappedValue: V
    var projectedValue: R? {
        get { (wrappedValue as? R.RawValue).flatMap(R.init) }
        set {
            guard let value = newValue?.rawValue as? V else { return }
            wrappedValue = value
        }
    }
    init(wrappedValue value: V, _ type: R.Type) { wrappedValue = value }
}

enum StringEnum: String {
    case a = "a"
    case b = "b"
    case c = "c"
}

class Model: Object, Mappable {
    @RealmStringEnumWrapper(StringEnum.self)
    @objc dynamic var enumRaw: String? = nil
    
    required init?(map: Map) {}
    
    func mapping(map: Map) {
        $enumRaw <- (map["enumRaw"], EnumTransform<StringEnum>())
    }
}

//saving
let model = Model()
model.$enumRaw = .b

try! realm.write {
    // here enumRaw is filled
    realm.add(model)
    // here enumRaw is NIL
}
```
When passing filled model into write transaction to save model into Realm DB, wrapped property contains both wrapped and projected values. After model has been saved, property is **NIL**.

Am I missing something or Realm can't work like that?

## Version of Realm and Tooling

Realm framework version: 10.5.2

Xcode version: 12.2

iOS/OSX version: 14.2

**Comment by leemaguire** [comment]
Closing as there has been no response from the user and the fact we are currently working on property wrappers.

**Comment by rogerluan** [comment]
Property wrapper support has been added as of https://github.com/realm/realm-cocoa/releases/tag/v10.10.0
