### ISSUE TITLE
Xcode 12.5 beta 1+2: Sync times out in iOS Simulator

### ISSUE THREAD

**Issue by iandundas** [realm/realm-cocoa#7152]
## Goals
I want to login to Realm Sync from the iOS Simulator

## Expected Results
Successfully login

## Actual Results
Persistently get a timeout, on two different laptops. **Only** with Xcode 12.5 beta 1+2. (Xcode 12.4 is fine).

## Steps for others to Reproduce
- Create a simple iOS Realm Sync project (simple reproducible project: https://github.com/iandundas/RealmSync_SimulatorIssue)
- Run the project, tap to login
- Check the console.

On macOS (11.2) and a physical iOS device (14.4) it works just fine: 

> Result: success(<RLMUser: 0x600002aa7680>)

But when running on an iOS Simulator: 

> Result: failure(Error Domain=realm::app::CustomError Code=-1001 “The request timed out.” UserInfo={NSLocalizedDescription=The request timed out., realm::app::CustomError=code -1001})

As mentioned above, I tried this on two different laptops with the same result. Xcode 11.4 works fine though.

## Code Sample

Really just:

```swift
import SwiftUI
import RealmSwift

let realmApp = RealmSwift.App(id: "tacksdev-ldkft")

struct ContentView: View {

    var body: some View {
        Button("Login..") {
            realmApp.login(credentials: .anonymous) { result in
                print("Result: \(result)")
            }
        }
    }
}
```

But here is a sample project: https://github.com/iandundas/RealmSync_SimulatorIssue

## Version of Realm and Tooling
Realm framework version: `master` @ c5c5e67

Realm Object Server version: ?

Xcode version: 12.5 beta 2

iOS/OSX version: iOS 14.5

Dependency manager + version: Swift Package Manager

**Comment by pavel-ship-it** [comment]
Hi @iandundas ,
Thanks for reporting the issue. I can reproduce in. I'll take a deeper look into it.

**Comment by pavel-ship-it** [comment]
From what I've found it could be an issue with the XCode 12.5 beta. I see a similar problem on stackoverflow, for example. I'll leave this issue opened for a while to get back to it later. At the moment I can only recommend to use a stable version.

**Comment by pavel-ship-it** [comment]
Now it's known issue with the 14.5 simulator. Should be fine in Xcode 12.5 beta 3
https://developer.apple.com/forums/thread/674277?answerId=662833022#662833022%29,
