### ISSUE TITLE
Cocoapods compile failure 10.5.2+

### ISSUE THREAD

**Issue by cltnschlosser** [realm/realm-cocoa#7154]
## Goals
Compile

## Expected Results
Compile Successfully

## Actual Results
```
Pods/RealmSwift/RealmSwift/Aliases.swift:20:8: Could not build Objective-C module 'Realm'
/<module-includes>:1:1: Umbrella header for module 'Realm' does not include header '/core/realm.h'
```

## Version of Realm and Tooling
Realm framework version: 10.5.2+ (10.5.1 works)

Realm Object Server version: ?

Xcode version: 12.4

iOS/OSX version: ?

Dependency manager + version: Cocoapods 1.10.1

**Comment by cltnschlosser** [comment]
I did a bit of investigation and the `realm.h` header was introduced with realm-core 10.4.0, which was the version updated to in 10.5.2. The Headers subspec is including `"include/**/Realm.h"`. I'm guessing that is doing a case insensitive match and pulling in the core header into the project incorrectly.

Does this need to use `**` in the include path for these headers?

**Comment by pavel-ship-it** [comment]
Hi @cltnschlosser 
We know about this issue. Please follow #7119 for the further updates. Would be great if you can post your findings there.
I'll close this issue as a duplicate.
