### ISSUE TITLE
EXC_BAD_ACCESS error when accessing Results

### ISSUE THREAD

**Issue by DHaacke** [realm/realm-cocoa#7155]
!!! MANDATORY TO FILL OUT !!!

## Goals
Enumerate results 

## Expected Results
Expected to be able to enumerate results object. I have other apps using older versions of Realm that enumerate the results just fine.

## Actual Results

![image](https://user-images.githubusercontent.com/6235004/109591991-c101c300-7acb-11eb-97da-9d245589c829.png)

## Steps for others to Reproduce

See code sample
## Code Sample

class UsgsStreamGage : Object {
  @objc dynamic var llid        = "1"
  @objc dynamic var stationName = ""
  @objc dynamic var latitude    = 0.0
  @objc dynamic var longitude   = 0.0
  @objc dynamic var hucCode     : String?
  @objc dynamic var hucName     = ""
  @objc dynamic var basinCode   = ""
  @objc dynamic var basinName   = ""

  override class func primaryKey() -> String? {
    return "llid"
  }
}

// in viewDidLoad of main ViewController

  let realm = try! Realm()
  
  override func viewDidLoad() {
      super.viewDidLoad()
      print("Default realm path is \(realm.configuration.fileURL?.absoluteString ?? "No realm")")

      let gages = realm.objects(UsgsStreamGage.self)
      print("\(gages[0])")  // this line runs correctly returning the first record with appropriate data
      for gage in gages.enumerated() {      // crash happens here
        // ...
      }
  }

## Version of Realm and Tooling

Realm framework version: 10.7.0

Realm Object Server version: ?

Xcode version: 12.4

iOS/OSX version: 14.x

Dependency manager + version: ?

**Comment by pavel-ship-it** [comment]
You have **@objc dynamic var llid = "1"** claimed as a primary key - it should be a unique value. I'd recommend 
```
    @objc dynamic var llid = UUID().uuidString
```

**Comment by DHaacke** [comment]
Pavel, thanks for your help! I had put that in for testing/debugging and forgot to remove it.... my bad.  So I fixed that and also remove the primary key so that the model is just:

class UsgsStreamGage : Object {
  @objc dynamic var llid        = ""
  @objc dynamic var stationName = ""
  @objc dynamic var latitude    = 0.0
  @objc dynamic var longitude   = 0.0
  @objc dynamic var hucCode     : String?
  @objc dynamic var hucName     = ""
  @objc dynamic var basinCode   = ""
  @objc dynamic var basinName   = ""
}

The migration is also failing, so I deleted the default.realm to start fresh. I have a process to populate the table, which it does fine, and I can view the data in mongoDB Realm Studio.  Unfortunately, it still crashes with the same error message at the same place on the same line.

Any other thoughts?

**Comment by pavel-ship-it** [comment]
If you have an empty realm and a new model for UsgsStreamGage then the code above should work fine.
It will can crash on line **print("\(gages[0])")** if you have an empty collection but the enumeration will work fine.
if it crashing anyway I'd appreciate if you can share the code with me.

**Comment by DHaacke** [comment]
Pavel, its still not working with the new model and with the gages[0] code removed. Fortunately, I'm just starting on the project, so its small. I can zip it up, but what's the best way to send it without posting it in this forum?

**Comment by pavel-ship-it** [comment]
@DHaacke you can send it to my email pavel.yakimenko@mongodb.com
