### ISSUE TITLE
Crash：Cannot set a sync configuration which has an errored-out user

### ISSUE THREAD

**Issue by lacklock** [realm/realm-cocoa#7156]
**Bugs**: 

*** Terminating app due to uncaught exception 'RLMException', reason: 'Cannot set a sync configuration which has an errored-out user.'

Writing data to realms will crash.

Realm framework version: RealmSwift (4.4.1)

Realm Object Server version: ?

Xcode version: 12.3

iOS/OSX version:  iOS14

**Comment by pavel-ship-it** [comment]
Hi @lacklock ,
With the info provided I can say that the user credentials causing the issue cannot be used (user was removed?). You should try to use another user.

**Comment by leemaguire** [comment]
Closing this issue as information has been provided to the user.
