### ISSUE TITLE
Crashlytics: Realm please_report_this_issue_in_github_realm_realm_core

### ISSUE THREAD

**Issue by NikBorawar** [realm/realm-cocoa#7159]
!!! MANDATORY TO FILL OUT !!!

## Goals

Realm shouldn't crash app

## Expected Results

Realm shouldn't crash 

## Actual Results

FIRST STACK TRACE
Crashed: Realm notification listener
0  libsystem_kernel.dylib         0x1d9dd6414 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1f7930b50 pthread_kill + 272
2  libsystem_c.dylib              0x1b52afb74 abort + 104
3  Realm                          0x1083e83b4 please_report_this_issue_in_github_realm_realm_core + 10
4  Realm                          0x1083e86c0 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 328
5  Realm                          0x1083e8838 realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 328
6  Realm                          0x10851e948 realm::_impl::RealmCoordinator::run_async_notifiers() + 3756
7  Realm                          0x10851da20 realm::_impl::RealmCoordinator::on_change() + 24
8  Realm                          0x1085078c0 realm::_impl::ExternalCommitHelper::listen() + 140
9  Realm                          0x108507a24 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*) + 52
10 libsystem_pthread.dylib        0x1f792fcb0 _pthread_start + 320
11 libsystem_pthread.dylib        0x1f7938778 thread_start + 8

com.apple.main-thread
0  FirebaseDatabase               0x10711c5e8 -[FValueEventRegistration repo] + 6
1  FirebaseDatabase               0x10711bf88 -[FValueEventRegistration initWithRepo:handle:callback:cancelCallback:] + 132
2  FirebaseDatabase               0x1070d7934 -[FIRDatabaseQuery removeObserverWithHandle:] + 104
3  FirebaseDatabase               0x1070d9df0 -[FIRDatabaseReference removeObserverWithHandle:] + 40
4  FirebaseDatabase               0x1070d9e24 -[FIRDatabaseReference removeAllObservers] + 40
5 DemoApp                  0x10424a780 +[FirebaseRealtimeDBHelper observeStationList] + 449 (FirebaseRealtimeDBHelper.m:449)
6  DemoApp                  0x10424a704 +[FirebaseRealtimeDBHelper startAllObserver] + 438 (FirebaseRealtimeDBHelper.m:438)
7  DemoApp                  0x104114984 -[DemoAppAppDelegate application:didFinishLaunchingWithOptions:] + 287 (DemoAppAppDelegate.m:287)
8  UIKitCore                      0x1ae833228 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 360
9  UIKitCore                      0x1ae835290 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 5136
10 UIKitCore                      0x1ae83acec -[UIApplication _runWithMainScene:transitionContext:completion:] + 1244
11 UIKitCore                      0x1ade90c74 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 152
12 UIKitCore                      0x1ae3fef9c _UIScenePerformActionsWithLifecycleActionMask + 112
13 UIKitCore                      0x1ade9180c __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 224
14 UIKitCore                      0x1ade912cc -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 484
15 UIKitCore                      0x1ade9161c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 768
16 UIKitCore                      0x1ade90e58 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 340
17 UIKitCore                      0x1ade993a4 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 196
18 UIKitCore                      0x1ae30b60c +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 892
19 UIKitCore                      0x1ae4176c4 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 272
20 UIKitCore                      0x1ade9909c -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 384
21 UIKitCore                      0x1adcc05a0 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 776
22 UIKitCore                      0x1adcbef14 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 256
23 UIKitCore                      0x1adcc01c8 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 248
24 UIKitCore                      0x1ae838e8c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 572
25 UIKitCore                      0x1ae334e38 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 388
26 FrontBoardServices             0x1bbbec3bc -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 432
27 FrontBoardServices             0x1bbc17d04 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.200 + 128
28 FrontBoardServices             0x1bbbfb4a0 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
29 FrontBoardServices             0x1bbc179c8 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 372
30 libdispatch.dylib              0x1aba75db0 _dispatch_client_callout + 20
31 libdispatch.dylib              0x1aba79738 _dispatch_block_invoke_direct + 268
32 FrontBoardServices             0x1bbc40250 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
33 FrontBoardServices             0x1bbc3fee0 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 448
34 FrontBoardServices             0x1bbc40434 -[FBSSerialQueue _performNextFromRunLoopSource] + 32
35 CoreFoundation                 0x1abdfd76c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
36 CoreFoundation                 0x1abdfd668 __CFRunLoopDoSource0 + 208
37 CoreFoundation                 0x1abdfc9cc __CFRunLoopDoSources0 + 376
38 CoreFoundation                 0x1abdf6a8c __CFRunLoopRun + 824
39 CoreFoundation                 0x1abdf621c CFRunLoopRunSpecific + 600
40 GraphicsServices               0x1c39c2784 GSEventRunModal + 164
41 UIKitCore                      0x1ae836ee8 -[UIApplication _run] + 1072
42 UIKitCore                      0x1ae83c75c UIApplicationMain + 168
43 DemoApp                  0x10412c774 main + 35 (main.m:35)
44 libdyld.dylib                  0x1abab66b0 start + 4

SECOND STACK TRACE
Crashed: Realm notification listener
0  ???                            0x1b246184c (Missing)
1  ???                            0x1ced2c9e8 (Missing)
2  ???                            0x18f2988f4 (Missing)
3  Realm                          0x1048943b4 please_report_this_issue_in_github_realm_realm_core + 10
4  Realm                          0x1048946c0 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 328
5  Realm                          0x104894838 realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 328
6  Realm                          0x1049ca948 realm::_impl::RealmCoordinator::run_async_notifiers() + 3756
7  Realm                          0x1049c9a20 realm::_impl::RealmCoordinator::on_change() + 24
8  Realm                          0x1049b38c0 realm::_impl::ExternalCommitHelper::listen() + 140
9  Realm                          0x1049b3a24 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*) + 52
10 ???                            0x1ced2bc9c (Missing)
11 ???                            0x1ced30880 (Missing)

com.apple.main-thread
0  Realm                          0x104a0ff38 std::__1::enable_if<(__is_forward_iterator<std::__1::pair<realm::TableKey, unsigned long long>*>::value) && (is_constructible<std::__1::pair<realm::TableKey, unsigned long long>, std::__1::iterator_traits<std::__1::pair<realm::TableKey, unsigned long long>*>::reference>::value), void>::type std::__1::vector<std::__1::pair<realm::TableKey, unsigned long long>, std::__1::allocator<std::__1::pair<realm::TableKey, unsigned long long> > >::assign<std::__1::pair<realm::TableKey, unsigned long long>*>(std::__1::pair<realm::TableKey, unsigned long long>*, std::__1::pair<realm::TableKey, unsigned long long>*) + 308
1  Realm                          0x104a0ff9c realm::ConstTableView::operator=(realm::ConstTableView&&) + 80
2  Realm                          0x104a07b9c realm::Results::operator=(realm::Results&&) + 144
3  Realm                          0x10464a734 -[RLMResults initWithObjectInfo:results:] + 84
4  Realm                          0x10464a7a0 +[RLMResults resultsWithObjectInfo:results:] + 44
5  Realm                          0x1045ef004 RLMGetObjects + 688
6  Realm                          0x1045e51f4 +[RLMObject allObjectsInRealm:] + 56
7  ???                            0x10590b7a0 (Missing)
8  ???                            0x10590d5a4 (Missing)
9  ???                            0x105903c2c (Missing)
10 DemoApp                  0x10096a774 ChatManager.registerDevice(with:) + 4309084020 (<compiler-generated>:4309084020)
11 DemoApp                  0x100971350 specialized static ChatManager.registerDevice() + 4309111632 (<compiler-generated>:4309111632)
12 DemoApp                  0x1005c4498 -[DemoAppAppDelegate application:didFinishLaunchingWithOptions:] + 233 (DemoAppAppDelegate.m:233)
13 ???                            0x188e048c0 (Missing)
14 ???                            0x188e06860 (Missing)
15 ???                            0x188e0bf48 (Missing)
16 ???                            0x1884e1164 (Missing)
17 ???                            0x188a0a2b0 (Missing)
18 ???                            0x1884e1c4c (Missing)
19 ???                            0x1884e16a0 (Missing)

## Steps for others to Reproduce

This is a crash is reported on Firebase Crashlytics.
Can not reproduce.
## Code Sample

This is a crash is reported on Firebase Crashlytics.

## Version of Realm and Tooling

Realm framework version:  10.6.0

Realm Object Server version:  NA

Xcode version: 12.0.1

iOS/OSX version: iOS 12, iOS 13, iOS 14.0+

Dependency manager + version:  Cocoapod

**Comment by pavel-ship-it** [comment]
Hi @NikBorawar 
Thank you for reporting. This issue should be fixed in 10.7.0
Related to [realm-core/#4449](https://github.com/realm/realm-core/pull/4449)
I'm closing this ticket for now. If you think it is another case or it's happened again in a newer version please comment and we will reopen the ticket.

**Comment by NikBorawar** [comment]
Thanks, @pavel-ship-it. Will upgrade to 10.7.0
