### ISSUE TITLE
Realm folks have requested to use this version and above. You cannot use .rc.1 version for it.  Please file an issue with Realm github repo about this as the pod author requests this version constraint, possibly due to xcframework support.

### ISSUE THREAD

**Issue by peterkuch** [realm/realm-cocoa#7176]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by dianaafanador3** [comment]
@peterkuch  can you add any information about this issue?

**Comment by dianaafanador3** [comment]
Closed. More information needed, unclear information.
