### ISSUE TITLE
How we remove existing Realm database when added the inMemoryIdentifier in Realm Configuration

### ISSUE THREAD

**Issue by dfg-1310** [realm/realm-cocoa#7179]
!!! MANDATORY TO FILL OUT !!!

## Version of Realm and Tooling

Realm framework version: 2.8.1

Realm Object Server version: NA

Xcode version: 11.5

iOS/OSX version: Swift 4.2

Dependency manager + version: NA

Due to security concerns, I do not want to save the realm database on the hard disk so I added the **inMemoryIdentifier** in Realm Configuration. Realm database file is not creating for the new build.

But I have an issue with the existing build, We still have an existing realm database device hard disk so My question is How I can delete the existing realm database from the app?

Thanks in Advance!

**Comment by jsflax** [comment]
We provide a static convenience method on the Realm class to do this: `Realm.deleteFiles(for: `Realm.Configuration`)`. Sending your configuration to that method will delete the local realm file and associated temporary files.

If you find this solves your problem, please close the ticket.

**Comment by dfg-1310** [comment]
Thanks, @jsflax for your reply!

I think, Realm.deleteFiles(for: Realm.Configuration) method is not in Realmswift version '2.8.1'.

Do you have an idea how I can delete DB files in Realmswift version '2.8.1'?

**Comment by dianaafanador3** [comment]
Hi @dfg-1310 Can you update to latest Realm version 10.7.2?, Latest version provides a way to delete the local realm file. 
If you can't update to our latest version, you can replicate what we are doing on `deleteFiles(for: Realm.Configuration)`
```objectiveC
+ (BOOL)deleteFilesForConfiguration:(RLMRealmConfiguration *)config error:(NSError **)error {
    auto& path = config.config.path;
    bool anyDeleted = false;
    NSError *localError;
    bool didCall = DB::call_with_lock(path, [&](auto const& path) {
        NSURL *url = [NSURL fileURLWithPath:@(path.c_str())];
        NSFileManager *fm = NSFileManager.defaultManager;

        anyDeleted = [fm removeItemAtURL:url error:&localError];
        if (localError && localError.code != NSFileNoSuchFileError) {
            return;
        }

        [fm removeItemAtURL:[url URLByAppendingPathExtension:@"management"] error:&localError];
        if (localError && localError.code != NSFileNoSuchFileError) {
            return;
        }

        [fm removeItemAtURL:[url URLByAppendingPathExtension:@"note"] error:&localError];
    });
    if (error && localError && localError.code != NSFileNoSuchFileError) {
        *error = localError;
    }
    else if (!didCall) {
        if (error) {
            NSString *msg = [NSString stringWithFormat:@"Realm file at path %s cannot be deleted because it is currently opened.", path.c_str()];
            *error = [NSError errorWithDomain:RLMErrorDomain
                                         code:RLMErrorAlreadyOpen
                                     userInfo:@{NSLocalizedDescriptionKey: msg}];
        }
    }
    return anyDeleted;
}
```

**Comment by dianaafanador3** [comment]
Closing this as there is no response from the user
