### ISSUE TITLE
Expected a Realm with no or in-realm history, but found history type 3

### ISSUE THREAD

**Issue by fabriciomasiero** [realm/realm-cocoa#7180]
Hi,

I'm trying to save my sync realm locally, but I'm receiving the crash error: **Expected a Realm with no or in-realm history, but found history type 3**

So, after successful anonymous login, I call **asyncOpen** like the code below

## Code Sample
```
        var config = app.currentUser!.configuration(partitionValue: "myValue")
        config.schemaVersion = 1
        config.objectTypes = [tracks_scheduled.self,
                                     tracks_scheduled_metadata.self,
                                     tracks_scheduled_playtime.self,
                                     transition.self,
                                     station.self]
        let username = "Example"
        config.fileURL = Realm.Configuration.defaultConfiguration.fileURL
        config.fileURL!.deleteLastPathComponent()
        config.fileURL!.appendPathComponent(username)
        config.fileURL!.appendPathExtension("realm")
        
        Realm.asyncOpen(configuration: config, callbackQueue: DispatchQueue.main) { result in
            switch result {
            case .success(let theRealm):
                let stations = theRealm.objects(station.self)
                try! theRealm.write {
                    theRealm.add(stations)
                }
                let arrayStations = Array(stations)
                callback(arrayStations, nil)
            case .failure(let error):
                callback(nil, error)
            }
        }
```

Ok, fine! It works perfectly!

But, when I go through an offline scenario, I found the issue.

How do I get my station list from offline? Look at the code below

## Code Sample
```
let username = "Example"
        var configuration = Realm.Configuration.defaultConfiguration
        
        configuration.fileURL!.deleteLastPathComponent()
        configuration.fileURL!.appendPathComponent(username)
        configuration.fileURL!.appendPathExtension("realm")
        
        let realm = try! Realm(configuration: configuration) ~> brokes here
        
        let offlineStations = realm.objects(station.self)
```

## Goals
I want to grab all offline data

## Expected Results
Getting error when trying to open realm file in offline mode

## Actual Results
`try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/Users/fabriciomasiero/Library/Developer/CoreSimulator/Devices/32F5028E-0A6A-4F6A-88F5-F01AEA5EC6BD/data/Containers/Data/Application/4C20900E-C42A-449D-8C0C-2DB19497B36D/Documents/Example.realm': Incompatible histories. Expected a Realm with no or in-realm history, but found history type 3 Path:Exception backtrace:`

## Version of Realm and Tooling
Realm framework version:  10.6

Realm Object Server version:?

Xcode version:  12.4

iOS/OSX version:  iOS 14.4

Dependency manager + version:  Cocoapods

**Comment by tgoyne** [comment]
You need to use the same configuration to open the file regardless of if you are online or offline.

**Comment by fabriciomasiero** [comment]
I'm using the same Realm.Configuration @tgoyne

**Comment by tgoyne** [comment]
Your code sample does not use the configuration from the user to open the Realm in the failing case.

**Comment by fabriciomasiero** [comment]
So I need to persistent the user to login offline?
How I get the user when I'm offline?

**Comment by tgoyne** [comment]
`app.currentUser` is persisted between runs of an application. The initial login requires being online, but subsequent launches do not.

**Comment by pavel-ship-it** [comment]
I close this issue due to inactivity.
