### ISSUE TITLE
Setting 'objectClasses' property of RLMRealmConfiguration breaks objects invalidation.

### ISSUE THREAD

**Issue by bzdybowicz** [realm/realm-cocoa#7181]
Setting 'objectClasses' property of RLMRealmConfiguration break 'isInvalidated' property, which returns false for deleted objects. Calling 'rlmValidated' on given object throws an exception.

## Expected Results
'isInvalidated' returns true for deleted objects.

## Actual Results
'isInvalidated' returns false for deleted objects if objectClasses are set.

## Steps for others to Reproduce
Just copy paste code sample.

## Code Sample

```
class SimpleObject: RLMObject {
    @objc dynamic var value: String = ""
}

```
This passes:

```
func testInvalidatedObjectWithoutObjectClasses() {
        let config = RLMRealmConfiguration.default()
        config.inMemoryIdentifier = #function
        let realm = try! RLMRealm(configuration: config)
        let object = SimpleObject()
        try! realm.transaction {
            realm.add(object)
        }
        XCTAssertEqual(object.isInvalidated, false)
        try! realm.transaction {
            realm.delete(object)
        }
        XCTAssertEqual(object.isInvalidated, true)
    }
```
but this does NOT pass:
```
    func testInvalidatedObjectWithObjectClasses() {
        let config = RLMRealmConfiguration.default()
        config.objectClasses = [SimpleObject.self]
        config.inMemoryIdentifier = #function
        let realm = try! RLMRealm(configuration: config)
        let object = SimpleObject()
        try! realm.transaction {
            realm.add(object)
        }
        XCTAssertEqual(object.isInvalidated, false)
        try! realm.transaction {
            realm.delete(object)
        }
        XCTAssertEqual(object.isInvalidated, true)
    }
```

## Version of Realm and Tooling
Realm framework version: 10.0.0 - 10.7.2 (It works fine on 5.5.x)

Xcode version: 12.3

iOS/OSX version: iOS 14

Dependency manager: CocoaPods / Carthage

**Comment by dianaafanador3** [comment]
Hi @bzdybowicz this is happening because our Realm (Objective-C) is not enable to receive a swift class as an option for the configuration `objectClasses`.
As we already support a Swift SDK, we suggest instead use `Realm.Configuration`, as the example below
``` swift
class SimpleObject: Object {
    @objc dynamic var value: String = ""
}

 func testInvalidatedObjectWithoutObjectClasses() {
        var config = Realm.Configuration.defaultConfiguration
        config.inMemoryIdentifier = #function
        let realm = try! Realm(configuration: config)
        let object = SimpleObject()
        try! realm.write {
            realm.add(object)
        }
        XCTAssertEqual(object.isInvalidated, false)
        try! realm.write {
            realm.delete(object)
        }
        XCTAssertEqual(object.isInvalidated, true)
    }

func testInvalidatedObjectWithObjectClasses() {
        var config = Realm.Configuration.defaultConfiguration
        config.objectTypes = [SimpleObject.self]
        config.inMemoryIdentifier = #function
        let realm = try! Realm(configuration: config)
        let object = SimpleObject()
        try! realm.write {
            realm.add(object)
        }
        XCTAssertEqual(object.isInvalidated, false)
        try! realm.write {
            realm.delete(object)
        }
        XCTAssertEqual(object.isInvalidated, true)
    }
```

**Comment by piellarda** [comment]
@dianaafanador3 The issue is the same with an ObjC class.

**Comment by dianaafanador3** [comment]
Hi @piellarda, can you show me your code, the issue happens when using `RLMConfiguration` from swift, the below code works using Configuration instead of `RLMConfiguration`, i haven't tested code in objective-C

**Comment by piellarda** [comment]
@dianaafanador3 You can find it [here](https://github.com/kolibree-git/Realm-test).

**Comment by dianaafanador3** [comment]
Hi @piellarda same issue on https://github.com/kolibree-git/Realm-test/blob/main/Realm-test/AppDelegate.swift, we have a Swift SDK, `RLMConfiguration` is not meant to be used from Swift. Instead test using RealmSwift.Configuration to setup ypur `objectTypes`

**Comment by piellarda** [comment]
What about https://github.com/kolibree-git/Realm-test/blob/main/Realm-testTests/DummyTest.m ?

**Comment by dianaafanador3** [comment]
Hey @piellarda I'll take a look at that and let you know what i find, thanks for code

**Comment by piellarda** [comment]
Thank you @dianaafanador3
