### ISSUE TITLE
Last "realm-cocoa" version incorrect on Release Notes

### ISSUE THREAD

**Issue by RicardoBarroso** [realm/realm-cocoa#7186]
Hi all!

Looking at the last [Release Notes](https://github.com/realm/realm-cocoa/releases), the last version number is v5.5.1
(7ec5df0) when the previous version was  v10.7.2 (ae8e646).

I'm not aware of the project but from what I've seen on https://github.com/realm/realm-cocoa/commit/7ec5df0a700ef76ad930dcedb9c63c1b354979e1 this seems like a kind of limitation on publishing new versions. If so I suggest adding a note in the beginning of the text and explaining which real version it corresponds to.

Thanks,
Ricardo Barroso

**Comment by leemaguire** [comment]
@RicardoBarroso Thanks for your feedback, we will keep it in mind. v5.5.1 was a back-ported release that addressed a few issues. v10.7.2 is what you should use if you are developing with Realm from now on. If that is all, would you mind closing the issue? Thanks!
