### ISSUE TITLE
Some Carthage flags are probably ignored

### ISSUE THREAD

**Issue by budikpet** [realm/realm-cocoa#7193]
## Goals

Unexpected behaviour when downloading realm-cocoa using Carthage.
Flags ```--platform``` and ```--use-xcframeworks``` seem to be ignored.

## Expected Results

If both flags were to function then *Carthage/Build/Realm.xcframework* folder.
If at least ```--platform``` was to function then *Carthage/Build/iOS/Realm.framework* folder.

## Actual Results

The following folder structure is created:
- Carthage
    - Build
        - iOS
        - Mac
        - watchOS
        - tvOS

## Steps for others to Reproduce

I have tried these commands each with a clean folder:
```bash
$ carthage bootstrap --platform iOS --use-xcframeworks

$ carthage bootstrap --platform iOS

$ carthage bootstrap --use-xcframeworks
```

Each command generated the same folders.

## Version of Realm and Tooling

Realm framework version: v5.5.1

OSX version: Mac OS Catalina 10.15.7

Dependency manager + version: Carthage 0.37.0

**Comment by budikpet** [comment]
Also it seems that #7031 is already handeling ```--use-xcframeworks``` flag.

**Comment by tgoyne** [comment]
We don't have any sort of influence on what Carthage decides to build and you should report issues you have with it to them.

**Comment by budikpet** [comment]
@tgoyne Ok, I'll try. I have no idea how Carthage actually does the building behind the scenes and realm-cocoa is the only framework I had problems with so far.

**Comment by leemaguire** [comment]
Closing as this is a Carthage issue, not a Realm issue.
