### ISSUE TITLE
Undefined symbols for architecture arm64 on OS X during Archive action

### ISSUE THREAD

**Issue by MagicZP** [realm/realm-cocoa#7201]
Made a project with build targets to iOS and OS X.
Added Pods file specifying realm:
target 'project_osx' do
    use_frameworks!
    pod 'RealmSwift', '5.5.0'
end

Run pod install
Open xcworkspace, try to archive OS X project
Errors

## Goals
OS X project archiving

## Expected Results
OS X Project archives

## Actual Results
101 errors

Undefined symbol: realm::ArrayBinary::set(unsigned long, realm::BinaryData)

Undefined symbol: realm::ArrayBinary::clear()

Undefined symbol: realm::ArrayBinary::erase(unsigned long)

Undefined symbol: realm::ArrayBinary::insert(unsigned long, realm::BinaryData)

Undefined symbol: realm::ArrayString::set(unsigned long, realm::StringData)

Undefined symbol: realm::ArrayString::clear()

Undefined symbol: realm::ArrayString::erase(unsigned long)

Undefined symbol: realm::ArrayString::insert(unsigned long, realm::StringData)

Undefined symbol: realm::ArrayString::ArrayString(realm::Allocator&)

Undefined symbol: realm::ClusterTree::ConstIterator::ConstIterator(realm::ClusterTree::ConstIterator const&)

Undefined symbol: realm::ClusterTree::ConstIterator::operator[](unsigned long)

Undefined symbol: realm::ClusterTree::ConstIterator::operator++()

Undefined symbol: realm::ClusterTree::get(realm::ObjKey)

Undefined symbol: realm::ClusterTree::get(unsigned long)

Undefined symbol: realm::Transaction::import_copy_of(realm::ConstTableRef)

Undefined symbol: realm::Transaction::import_copy_of(realm::LstBase const&)

Undefined symbol: realm::Transaction::import_copy_of(realm::ConstObj const&)

Undefined symbol: realm::Transaction::import_copy_of(std::__1::unique_ptr<realm::LnkLst, std::__1::default_delete<realm::LnkLst> > const&)

Undefined symbol: realm::Transaction::import_copy_of(realm::Query&, realm::PayloadPolicy)

Undefined symbol: realm::Transaction::import_copy_of(realm::TableView&, realm::PayloadPolicy)

Undefined symbol: realm::Transaction::set_transact_stage(realm::DB::TransactStage)

Undefined symbol: realm::Transaction::commit_and_continue_as_read()

Undefined symbol: realm::Transaction::get_version_of_current_transaction()

Undefined symbol: realm::Transaction::close()

Undefined symbol: realm::Transaction::commit()

Undefined symbol: realm::Transaction::rollback()

Undefined symbol: realm::Transaction::duplicate()

Undefined symbol: realm::ArrayIntNull::avoid_null_collision(long long)

Undefined symbol: realm::ArrayPayload::~ArrayPayload()

Undefined symbol: realm::ConstLstBase::ConstLstBase(realm::ColKey, realm::ConstObj const*)

Undefined symbol: realm::ConstLstBase::~ConstLstBase()

Undefined symbol: realm::GetIndexData<realm::Timestamp>::get_index_data(realm::Timestamp const&, std::__1::array<char, 12ul>&)

Undefined symbol: realm::LinkPathPart::LinkPathPart(realm::ColKey, realm::ConstTableRef)

Undefined symbol: realm::BPlusTreeBase::bptree_erase(unsigned long, realm::util::FunctionRef<unsigned long (realm::BPlusTreeNode*, unsigned long)>)

Undefined symbol: realm::BPlusTreeBase::bptree_insert(unsigned long, realm::util::FunctionRef<unsigned long (realm::BPlusTreeNode*, unsigned long)>)

Undefined symbol: realm::BPlusTreeBase::create_root_from_ref(unsigned long)

Undefined symbol: realm::BPlusTreeBase::create()

Undefined symbol: realm::BPlusTreeBase::destroy()

Undefined symbol: realm::BPlusTreeBase::~BPlusTreeBase()

Undefined symbol: realm::BPlusTreeBase::operator=(realm::BPlusTreeBase&&)

Undefined symbol: realm::BPlusTreeBase::operator=(realm::BPlusTreeBase const&)

Undefined symbol: realm::BPlusTreeLeaf::bptree_erase(unsigned long, realm::util::FunctionRef<unsigned long (realm::BPlusTreeNode*, unsigned long)>)

Undefined symbol: realm::BPlusTreeLeaf::bptree_access(unsigned long, realm::util::FunctionRef<void (realm::BPlusTreeNode*, unsigned long)>)

Undefined symbol: realm::BPlusTreeLeaf::bptree_insert(unsigned long, realm::BPlusTreeNode::State&, realm::util::FunctionRef<unsigned long (realm::BPlusTreeNode*, unsigned long)>)

Undefined symbol: realm::BPlusTreeLeaf::bptree_traverse(realm::util::FunctionRef<bool (realm::BPlusTreeNode*, unsigned long)>)

Undefined symbol: realm::BPlusTreeNode::~BPlusTreeNode()

Undefined symbol: realm::ArrayTimestamp::set(unsigned long, realm::Timestamp)

Undefined symbol: realm::ArrayTimestamp::insert(unsigned long, realm::Timestamp)

Undefined symbol: realm::ArrayTimestamp::ArrayTimestamp(realm::Allocator&)

Undefined symbol: realm::ConstTableView::apply_descriptor_ordering(realm::DescriptorOrdering const&)

Undefined symbol: realm::ConstTableView::ConstTableView(realm::ConstTableView const&, realm::Transaction*, realm::PayloadPolicy)

Undefined symbol: realm::QueryStateBase::dyncast()

Undefined symbol: realm::SortDescriptor::SortDescriptor(std::__1::vector<std::__1::vector<realm::ColKey, std::__1::allocator<realm::ColKey> >, std::__1::allocator<std::__1::vector<realm::ColKey, std::__1::allocator<realm::ColKey> > > >, std::__1::vector<bool, std::__1::allocator<bool> >)

Undefined symbol: realm::TableKeyIterator::operator*()

Undefined symbol: realm::TableKeyIterator::operator++()

Undefined symbol: realm::ColumnsDescriptor::ColumnsDescriptor(std::__1::vector<std::__1::vector<realm::ColKey, std::__1::allocator<realm::ColKey> >, std::__1::allocator<std::__1::vector<realm::ColKey, std::__1::allocator<realm::ColKey> > > >)

Undefined symbol: realm::IncludeDescriptor::IncludeDescriptor(realm::ConstTableRef, std::__1::vector<std::__1::vector<realm::LinkPathPart, std::__1::allocator<realm::LinkPathPart> >, std::__1::allocator<std::__1::vector<realm::LinkPathPart, std::__1::allocator<realm::LinkPathPart> > > > const&)

Undefined symbol: realm::DescriptorOrdering::append_sort(realm::SortDescriptor, realm::SortDescriptor::MergeMode)

Undefined symbol: realm::DescriptorOrdering::append_limit(realm::LimitDescriptor)

Undefined symbol: realm::DescriptorOrdering::append_include(realm::IncludeDescriptor)

Undefined symbol: realm::DescriptorOrdering::append_distinct(realm::DistinctDescriptor)

Undefined symbol: realm::DescriptorOrdering::DescriptorOrdering(realm::DescriptorOrdering const&)

Undefined symbol: realm::DescriptorOrdering::operator=(realm::DescriptorOrdering const&)

Undefined symbol: realm::disable_sync_to_disk()

Undefined symbol: realm::make_in_realm_history(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)

Undefined symbol: realm::DB::start_read(realm::VersionID)

Undefined symbol: realm::DB::start_write(bool)

Undefined symbol: realm::DB::do_end_write()

Undefined symbol: realm::DB::start_frozen(realm::VersionID)

Undefined symbol: realm::DB::call_with_lock(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>)

Undefined symbol: realm::DB::do_begin_write()

Undefined symbol: realm::DB::grab_read_lock(realm::DB::ReadLockInfo&, realm::VersionID)

Undefined symbol: realm::DB::wait_for_change(std::__1::shared_ptr<realm::Transaction>)

Undefined symbol: realm::DB::release_read_lock(realm::DB::ReadLockInfo&)

Undefined symbol: realm::DB::do_try_begin_write()

Undefined symbol: realm::DB::enable_wait_for_change()

Undefined symbol: realm::DB::get_number_of_versions()

Undefined symbol: realm::DB::wait_for_change_release()

Undefined symbol: realm::DB::get_version_of_latest_snapshot()

Undefined symbol: realm::DB::close(bool)

Undefined symbol: realm::DB::create(realm::Replication&, realm::DBOptions)

Undefined symbol: realm::DB::compact(bool, realm::util::Optional<char const*>)

Undefined symbol: realm::Lst<realm::BinaryData>::insert_repl(realm::Replication*, unsigned long, realm::BinaryData)

Undefined symbol: realm::Lst<realm::BinaryData>::set_repl(realm::Replication*, unsigned long, realm::BinaryData)

Undefined symbol: realm::Lst<realm::StringData>::insert_repl(realm::Replication*, unsigned long, realm::StringData)

Undefined symbol: realm::Lst<realm::StringData>::set_repl(realm::Replication*, unsigned long, realm::StringData)

Undefined symbol: realm::Lst<realm::util::Optional<bool> >::insert_repl(realm::Replication*, unsigned long, realm::util::Optional<bool>)

Undefined symbol: realm::Lst<realm::util::Optional<bool> >::set_repl(realm::Replication*, unsigned long, realm::util::Optional<bool>)

Undefined symbol: realm::Lst<realm::util::Optional<double> >::insert_repl(realm::Replication*, unsigned long, realm::util::Optional<double>)

Undefined symbol: realm::Lst<realm::util::Optional<double> >::set_repl(realm::Replication*, unsigned long, realm::util::Optional<double>)

Undefined symbol: realm::Lst<realm::util::Optional<float> >::insert_repl(realm::Replication*, unsigned long, realm::util::Optional<float>)

Undefined symbol: realm::Lst<realm::util::Optional<float> >::set_repl(realm::Replication*, unsigned long, realm::util::Optional<float>)

Undefined symbol: realm::Lst<realm::util::Optional<long long> >::insert_repl(realm::Replication*, unsigned long, realm::util::Optional<long long>)

Undefined symbol: realm::Lst<realm::util::Optional<long long> >::set_repl(realm::Replication*, unsigned long, realm::util::Optional<long long>)

Undefined symbol: realm::Lst<realm::ObjKey>::insert_repl(realm::Replication*, unsigned long, realm::ObjKey)

Undefined symbol: realm::Lst<realm::ObjKey>::do_set(unsigned long, realm::ObjKey)

Undefined symbol: realm::Lst<realm::ObjKey>::set_repl(realm::Replication*, unsigned long, realm::ObjKey)

Undefined symbol: realm::Lst<realm::ObjKey>::do_insert(unsigned long, realm::ObjKey)

Undefined symbol: realm::Lst<realm::Timestamp>::insert_repl(realm::Replication*, unsigned long, realm::Timestamp)

Undefined symbol: realm::Lst<realm::Timestamp>::set_repl(realm::Replication*, unsigned long, realm::Timestamp)

## Steps for others to Reproduce
Make a project with build targets to iOS and OS X.
Added Pods file specifying realm:
target 'Test_osx' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks! 
    pod 'RealmSwift', '5.5.0'
end

Archive the project

## Version of Realm and Tooling

Realm framework version: 5.5.0

Realm Object Server version: N/A

Xcode version: 12.3

iOS/OSX version: macOS 10.15.7

Dependency manager + version: CocoaPods 1.10.1

**Comment by DominicFrei** [comment]
Hello @MagicZP !

Your observation is correct, this does not work with RealmSwift 5.5.0.
The issue was fixed with a later version and I just verified it with the most recent one (10.7.2) creating a multi-platform app and archiving the macOS target.

Does this work for you with 10.7.2?

**Comment by MagicZP** [comment]
Hello Dominic. Thank you very much for your answer.
Could you please clarify, I'm using Realm Cloud and 5.5.0 version of realm library. 
In order to use 10.7.2 do I need to migrate my data from Realm Cloud to Mongo Db Cloud?

**Comment by DominicFrei** [comment]
Yes, @MagicZP, unfortunately you would have to migrate. `v10` is not compatible with legacy Realm Cloud which will be discontinued in 1 November 2021. Further information about that can be found in https://docs.realm.io/realm-legacy-migration-guide/

**Comment by MagicZP** [comment]
Thank you very much Dominic!

**Comment by DominicFrei** [comment]
Always happy to help. 🙃
