### ISSUE TITLE
Including objectTypes in Realm.Configuration for object with EmbeddedObject causes crash

### ISSUE THREAD

**Issue by homathko** [realm/realm-cocoa#7202]
## Goals
I have a `RealmSwiftObject` with an `EmbeddedObject` property. My goal is to use Realm Sync and also use a local, read-only realm. So I need to specify `objectTypes` in my `Realm.Configuration`s.

## Expected Results
I specify subset classes for any configuration whether sync or local. When I specify my object that has the `EmbeddedObject` property for a Realm.Configuration involving Sync, all should be well.

## Actual Results
On executing `try! Realm(configuration: config)` I'm scolded with a runtime exception: `'Invalid class subset list: 'Notification.event' links to class 'EmbeddedEvent', which is missing from the list of classes managed by the Realm'`

And right away, I realize I'm stuck because `EmbeddedObject` is a base class and will not be accepted into the `objectTypes` property of `Realm.Configuration`, which must be of type `RealmSwiftObject.Type`

I am initializing the configuration object the only way I can because I don't see a way to use the `Realm.User.configuration(partitionValue:)` API in a way that includes `objectTypes` specification.

## Steps for others to Reproduce
Supply a configuration for a Realm with `objectTypes` property of an `Object` with an `EmbeddedObject` property using the `user.configuration(partitionValue:)` method. Use that configuration to access a realm instance.

## Code Sample
    @objcMembers class Notification: Object {
        dynamic var _id = ObjectId.generate()
        override class func primaryKey () -> String? { "_id" }
        ///--------------------------------------------------
        dynamic var created_at: Date = Date()
        dynamic var title: String = ""
        dynamic var message: String = ""

        dynamic var event: EmbeddedEvent?
    }

    @objcMembers class EmbeddedEvent: EmbeddedObject {
        dynamic var type_code: String = ""
        dynamic var created_at: Date = Date()
    }

    ///...
    ///...
    var config = user.configuration(partitionValue: "my_partition")
    config.objectTypes = [Notification.self]
    let realm = try! Realm(configuration: config) /// Exception

## Version of Realm and Tooling
Realm framework version: 10.7.1

Realm Object Server version: ?

Xcode version: 12.4

iOS/OSX version: 14.4

Dependency manager + version: SPM

**Comment by nirinchev** [comment]
How does `location.objectTypes()` look like? Can you try adding `EmbeddedEvent` there?

**Comment by homathko** [comment]
Sorry, `location` evaluates to an array of Object.Type. Missed swapping that bit of my code out trying to simplify it.

**Comment by tgoyne** [comment]
`objectTypes` needs to include all of the types used, including embedded objects.

**Comment by homathko** [comment]
That makes sense but how do I include it when it inherits from a different type? Am I missing something really, really basic here? In the example above, `EmbeddedEvent` is an `EmbeddedObject` and `objectTypes` is an array of `Object.Type`. The compiler won't accept it.

**Comment by tgoyne** [comment]
`objectTypes` is an array of `ObjectBase`, which is the common base class of `Object` and `EmbeddedObject`.

**Comment by homathko** [comment]
Thanks, I was able to find the reference eventually 🙄  however, I can't seem to convert the types. I've attempted casting `EmbeddedEvent.self as Object.Type`..It still won't compile

**Comment by homathko** [comment]
I figured it out. `objectTypes` is `[ObjectBase.Type]`. Not `[Object.Type]`. Nailed it. Totally did not nail it.
