### ISSUE TITLE
can not install realm into swift proj

### ISSUE THREAD

**Issue by Serikios** [realm/realm-cocoa#7208]
~ pod install 
Analyzing dependencies
Downloading dependencies
Installing Realm (10.1.4)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

WARNING: The active Xcode command line tools, as returned by 'xcode-select -p', are not from Xcode.
         The newest version of Xcode will be used instead.
No version of Xcode could be found

can you help me?

**Comment by pavel-ship-it** [comment]
Hi @Serikios 
Realm 10.1.4 is relatively old version. Can you try to run **pod repo update** before running **pod install**?

Regarding the message you've got. It could happened you have several XCode versions at your machine (any beta versions?).
You could try to use **xcode-select** to choose a proper version of XCode or install/reinstall Additional Command Line Tools. Also you can try to update/reinstall XCode.
