### ISSUE TITLE
Realm Swift SPM not building in iOS 10

### ISSUE THREAD

**Issue by sidneivl** [realm/realm-cocoa#7214]
Hello,

I was using realm through Carthage with 10.7.2 version and it was working great, but when I tried using SPM it download the same version, but the realm not compiling using iOS 10

![Screen Shot 2021-04-20 at 09 50 18](https://user-images.githubusercontent.com/5385276/115402774-1c922800-a1c2-11eb-8e34-361516a5f638.png)

And in the new doc says that it is compatible with iOS 8+

<img width="812" alt="Screen Shot 2021-04-20 at 10 21 34" src="https://user-images.githubusercontent.com/5385276/115402931-48ada900-a1c2-11eb-8029-78228b53e5f4.png">

Is a bug with SPM version or something wanted using this kind of distribution?

Regards

**Comment by tgoyne** [comment]
SPM does not expose a way for us to set the compiler flag required to be able to target pre-11 versions of iOS with a modern toolchain, so it has a higher deployment target than the other installation methods.

**Comment by pavel-ship-it** [comment]
Thank you @sidneivl, I open a ticket to fix the documentation.
