### ISSUE TITLE
10.7.3 Prebuilt Carthage XCFramework Lacks Info.plist And Xcode Won't Compile.

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-cocoa#7216]
<img width="1109" alt="截屏2021-04-23 下午12 13 03" src="https://user-images.githubusercontent.com/2182896/115817376-51ee7e00-a42d-11eb-9321-d1797e3ccb35.png">

https://github.com/realm/realm-cocoa/releases/tag/v10.7.3

The Info.plist is used by Xcode to identify the framework from xcframework. Without it, Xcode could find the specify framework for specific architecture and target.

The full package "realm-swift-10.7.3.zip" contains the Info.plist that xcframework lacks. Anyone has to download the full package to get the whole xcframework.

Also, it would be welcomed to provide the prebuilt xcframework for Xcode 12.5 RC. RC is the name for GM for Apple's products.

**Comment by pavel-ship-it** [comment]
Hi @owenzhao,
Thank you for reporting the issue. Will be fixed asap
