### ISSUE TITLE
Warning: 'clock_gettime' is only available on iOS 10.0 or newer

### ISSUE THREAD

**Issue by cltnschlosser** [realm/realm-cocoa#7219]
## Goals
Build app without warnings

## Expected Results
No warning

## Actual Results
When using cocoapods, get the warning `'clock_gettime' is only available on iOS 10.0 or newer` when building `interprocess_condvar.hpp`. Either need the availability check or change the deployment target for cocoapods. It's currently set to 9.0. SPM is using `.iOS(.v11)`.

## Version of Realm and Tooling

Realm framework version: 10.7.3

Realm Object Server version: ?

Xcode version: 12.4

iOS/OSX version: iOS 14.4

Dependency manager + version: Cocoapods 1.10.1

**Comment by ericjordanmossman** [comment]
I see the same when I set `platform :ios, '9.0'` in the podfile.
We'll need to wrap this with "@available" to silence warning.

**Comment by tgoyne** [comment]
This is fixed in 10.7.6.
