### ISSUE TITLE
BUG: M1 not Building:  apps example or using realm.xcframework or framework

### ISSUE THREAD

**Issue by jesusmateos1234** [realm/realm-cocoa#7226]
## Goals
Build and run simulator on mac M1 with simulator iOS 14.X (14.3, 14.4) with realm.xcframework or framework v10.7.3 or v10.7.2 (PRECOMPILED FRAMEWORK OR XCFRAMEWORK)
iOS 12.2 and iOS 13.3 WORKS

## Expected Results
Simulator run

## Actual Results
![image](https://user-images.githubusercontent.com/68072718/116108883-9a6b9d00-a6b4-11eb-8da8-b13667f7cd02.png)
![image](https://user-images.githubusercontent.com/68072718/116116982-0ac9ec80-a6bc-11eb-9c77-6fe3386277d5.png)

iOS 12.2 and iOS 13.3 WORKS. iOS 14 NOT WORKS.

## Steps for others to Reproduce
Use realm-objc-10.7.3.zip
Try to build and run the project example "Simple" or whatever you want with a simulator iOS 14

## Version of Realm and Tooling
Realm framework version:  v10.7.3 or v10.7.2 

Dependency manager + version: Not used

- Undefined symbol: _OBJC_CLASS_$_RLMRealmConfiguration
- Undefined symbol: _OBJC_METACLASS_$_RLMObject
- Undefined symbol: _OBJC_CLASS_$_RLMRealm
- Undefined symbol: _OBJC_CLASS_$_RLMPropertyDescriptor
- Undefined symbol: _OBJC_CLASS_$_RLMObject

**Comment by ericjordanmossman** [comment]
@jesusmateos1234 
I took a first look at what could have happened. But I didn't figure anything out yet.

> with realm.xcframework or framework v10.7.3 or v10.7.2

Does this imply that your iOS 14 simulator was building before 10.7.2

**Comment by jesusmateos1234** [comment]
@ericjordanmossman, thanks for attend me. I don't know if apple iOS 14 Simulators work before 10.7.2 in M1, because before our team works with intel processors (and of course in that macs works well), but, last and this week, we starting to work with M1s. Tomorrow i speak with the team and we prove your example app with another version. What's the first precompiled version assets that supports M1 for the objc realm? 

Thanks for all

**Comment by tgoyne** [comment]
The obj-c release zip is built with Xcode 11 and so doesn't have arm64 slices. The swift release zip has a copy of Realm.xcframework built with newer versions of Xcode that do have arm64 slices and you can just grab it from that.

Probably no reason not to switch the obj-c release over to Xcode 12 at this point, though.

**Comment by jesusmateos1234** [comment]
Okey, i close the issue. I use last prebuilt xcframework.

Thanks for all guys!
