### ISSUE TITLE
ObservedRealmObject Crashes with Bool toggle() in SwiftUI

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-cocoa#7230]
_Realm 10.7.3, Xcode 12.5_

For a Realm model like this:
```
class Item: Object, ObjectKeyIdentifiable{
  @objc dynamic var recordName = ""
  @objc dynamic var text = ""
  @objc dynamic var updated = false
  
  override class func primaryKey() -> String? {
    return "recordName"
  }
}
```

You can edit a `@ObservedRealmObject`'s `text` value via a binding in SwiftUI like this:

```
struct ContentView: View{
  @ObservedRealmObject var item: Item

  var body: some View{
    TextField("", $item.text)
  }
}
```
The change to the `item` will automatically be written to the Realm database. 

If you want to change a `Bool`, however, you will get a crash that the change is being performed outside of a write transaction:
```
struct ContentView: View{
  @ObservedRealmObject var item: Item

  var body: some View{
    Button("Toggle Boolean"){
      item.updated.toggle() //<-- CRASH
    }
  }
}
```
It seems to me that the `@ObservedRealmObject` should allow mutating any of its properties without an explicit write transaction.

**Comment by ericjordanmossman** [comment]
Does using a StateRealmObject as described [here](https://github.com/realm/realm-cocoa/blob/master/RealmSwift/SwiftUI.swift#L198) accomplish your goal?

**Comment by cliftonlabrum** [comment]
It looks like `@StateRealmObject` and my original `@ObservedRealmObject` will both work, but the `toggle` syntax has to be a little different. It seems it has to operate on a `Binding` like this:

```
Button("Toggle Boolean"){
  $item.updated.wrappedValue.toggle()
}
```
Thanks!
