### ISSUE TITLE
Cannot declare fields on Codable class without initial values

### ISSUE THREAD

**Issue by jsflax** [realm/realm-cocoa#7231]
## Goals
Declare a Decimal128 on my Realm Object.

## Expected Results
Schema discovery should succeed. If I add default values, schema discovery is successful, but for many Codable types, this feels redundant.

## Actual Results
```swift
@objcMembers class Account: Object, ObjectKeyIdentifiable, Codable {
    dynamic var currency: String
    dynamic var balance: Decimal128
    dynamic var id: String

    override class func primaryKey() -> String? {
        "id"
    }
}
```

<img width="911" alt="Screenshot 2021-04-28 at 15 06 30" src="https://user-images.githubusercontent.com/4356928/116417593-52bf4f80-a833-11eb-9b91-e10c9fba7d3d.png">
<img width="563" alt="Screenshot 2021-04-28 at 15 06 51" src="https://user-images.githubusercontent.com/4356928/116417634-5eab1180-a833-11eb-9b87-74bf293935f1.png">

## Steps for others to Reproduce
Declare the above model, open a Realm.

## Version of Realm and Tooling
Realm framework version: 10.7.4

Xcode version: 12.5

iOS/OSX version: 14.5

**Comment by tgoyne** [comment]
This is not just for schema discovery. Reading data from the Realm also requires that we be able to create objects.
