### ISSUE TITLE
Realm crashes as it refers to the SwiftUI framework when run on older iOS versions

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#7234]
## Goals

Run an app that uses RealmSwift as a dependency on an iOS 11.4 simulator.

## Expected Results

Project can be run and it does not crash.

## Actual Results

Launching the app in the simulator crashes with the following error message:

```
dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
  Referenced from: /.../myApp.app/Frameworks/RealmSwift.framework/RealmSwift
  Reason: image not found
```

This issue seems to affect all version of iOS 11 and 12 that do not contain the SwiftUI framework. The bug was first introduced in release v10.6.0 and affects all later releases. Last working release is therefore v10.5.2.

## Steps for others to Reproduce

I suppose this can be reproduced simply by creating a new iOS application that uses the latest (10.7.4) RealmSwift as a dependency.

## Code Sample

N/A

## Version of Realm and Tooling

Realm framework version: 10.7.4

Xcode version: 12.5

iOS/OSX version: iOS 11.4 simulator

Dependency manager + version: CocoaPods 1.10.1

**Comment by jongarate** [comment]
+1

**Comment by kubankredit** [comment]
+1 I've added SwiftUI.framework as Optional in Link libraries phase in Xcode and app crashes anyway

**Comment by aelam** [comment]
for cocoapods users
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'RealmSwift'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -weak_framework SwiftUI'
      end
    end

  end
end
```

**Comment by kubankredit** [comment]
Thank you, the code above did the trick!

**Comment by jongarate** [comment]
Initial tests reveal that it's possible to set `SwiftUI` as `-weak_framework` reference in the `OTHER_LDFLAGS` setting of the module that imports the SwiftPM dependency. Now it successfully compiles on both iOS 12 and iOS 14.

**Comment by jsflax** [comment]
This is an interesting one. We only reference SwiftUI if it can be imported using `canImport`. Might be tied to this: https://forums.swift.org/t/weak-linking-of-frameworks-with-greater-deployment-targets/26017/28. It's a bit odd as well that no one seems to have to do this with Combine.

**Comment by dianaafanador3** [comment]
@anlaital Have you checked @jongarate answer?. This is something that should not be happening but this workaround should help you successfully compile the project

**Comment by KeimyPlaza** [comment]
The workaround is ok for me.

But there are an idea to fix on the next version? Maybe with this approach https://github.com/aws-amplify/amplify-ios/issues/878

**Comment by dianaafanador3** [comment]
Fixed by https://github.com/realm/realm-cocoa/pull/7268
