### ISSUE TITLE
 NSInternalInconsistencyException · *** -[NSHashTable NSHashTable { [30] <RLMFastEnumerator: 0x108010200> } ] count underflow

### ISSUE THREAD

**Issue by raphaelcruzeiro** [realm/realm-cocoa#7237]
## Goals

Have Realm working and not crashing frequently in production.

## Expected Results

Realm would not crash so frequently or it would at least crash with a meaningful error message.

## Actual Results

Realm occasionally crashes with the following stack trace:

```
NSInternalInconsistencyException: *** -[NSHashTable NSHashTable {
[30] <RLMFastEnumerator: 0x108010200>
}
] count underflow

0  CoreFoundation   ___exceptionPreprocess
1  libobjc.A.dylib  _objc_exception_throw
2  Foundation       -[NSConcreteHashTable raiseCountUnderflowException]
3  Foundation       _hashProbe
4  Foundation       -[NSConcreteHashTable removeItem:]
5  Tangerine        -[RLMRealm unregisterEnumerator:] (RLMRealm.mm:986:5)
6  Tangerine        -[RLMFastEnumerator dealloc] (RLMCollection.mm:99:9)
7  libobjc.A.dylib  AutoreleasePoolPage::releaseUntil(objc_object**)
8  libobjc.A.dylib  _objc_autoreleasePoolPop
9  CoreFoundation   __CFAutoreleasePoolPop
10 CoreFoundation   ___CFRunLoopPerCalloutARPEnd
11 CoreFoundation   ___CFRunLoopRun
12 CoreFoundation   _CFRunLoopRunSpecific
13 GraphicsServices _GSEventRunModal
14 UIKitCore        -[UIApplication _run]
15 UIKitCore        _UIApplicationMain
16 Tangerine        main
```

## Steps for others to Reproduce

Not really sure how to reproduce this issue.  Our app has hundreds of thousands of users and this is by far the most frequent crash we have. We cannot replicate it in debug mode. All we know is that this error started showing up on our crash logs after we updated to Realm 10.7.2 and quickly became the most frequent crash in our app. Updating to Realm 10.7.4 did not fix the issue.

## Code Sample

Based on the stack trace, it's really hard to figure out which part of the code might be causing this issue.

## Version of Realm and Tooling

Realm framework version: ? 10.7.4

Xcode version: ? 12.5 (12E262)

iOS/OSX version: ? iOS 13 and up

Dependency manager + version: ? Cocoapods 1.10.0

**Comment by tgoyne** [comment]
I'm not sure what this exception is even reporting. Each time you you for-in on a Realm collection we create an object which we store a weak reference to in a NSMapTable and removing that object is failing for some reason, but the documentation doesn't give any hint as to what a count underflow means. There also haven't been any changes to that code for a few years.

**Comment by raphaelcruzeiro** [comment]
@tgoyne any suggestion on how I can better debug this? Our app had been on the App Store and using Realm for a full year before this started happening on a release that basically upgraded some dependencies (including Realm).

<img width="299" alt="Screenshot 2021-05-03 at 22 42 00" src="https://user-images.githubusercontent.com/425640/116937348-02942300-ac61-11eb-81d1-f76d66eda4de.png">

Looking for iterations on a Realm collection might be a good first step (perhaps an object being removed from the collection as the collection is being iterated upon)? We have never experienced the crash ourselves but this is happening to a significant amount of users.

**Comment by tgoyne** [comment]
Are you using frozen Realms? Insufficient locking around our use of NSHashTable could explain this. `-[NSHashTable removeObject:]` checks if the object is in the table, then returns if it isn't. It then calls `count` and throws this exception if that returns zero, so we're clearly corrupting its data structure's somehow.

**Comment by raphaelcruzeiro** [comment]
@tgoyne Yes, I freeze every object that I propagate to other layers of my app and I fetch a new one by its primary key if any mutation needs to be made.

**Comment by tgoyne** [comment]
Okay, it makes sense for things to be going wrong now that I've looked at it again (although I'm not sure why it wasn't previously running into trouble...). I think it'll be simple to fix.

**Comment by raphaelcruzeiro** [comment]
Thanks for working on this @tgoyne! Looking forward to testing this on the next release.
