### ISSUE TITLE
Backlinks are not updated after an update to the linked object

### ISSUE THREAD

**Issue by mush159** [realm/realm-cocoa#7240]
## Goals

I wish to display a view of a list of objects along with other objects that are linked via a backlink. The example below uses Owners and Dogs where I am trying to display a list of dogs along with the number of owners for each dog.
It is possible to add dogs into this view as well as attach owners to dogs from the same view.
## Expected Results

As owners are added to dogs, the list should be updated to reflect the number of owners each dog has

## Actual Results

The UI is not updated to reflect the latest data

## Steps for others to Reproduce

Given the sample code below
1. Tap "Add dog" button
2. Tap on the on newly added dog row
3. Tap "Add person" button
4. The UI will present no changes.
5. Restarting the application will then display the correct number of owners.

## Code Sample

Models:
```swift
@objcMembers class Owner: Object, ObjectKeyIdentifiable {
    dynamic var _id = UUID().uuidString
    dynamic var name = "Owner"

    var dogs = RealmSwift.List<Dog>()

    override static func primaryKey() -> String? {
        return "_id"
    }
}

@objcMembers class Dog: Object, ObjectKeyIdentifiable {
    dynamic var _id = UUID().uuidString
    dynamic var name = "Fido"

    var owners = LinkingObjects(fromType: Owner.self, property: "dogs")

    override static func primaryKey() -> String? {
        return "_id"
    }
}
```

View:
```swift
struct ContentView: View {
    @ObservedResults(Dog.self) var dogs
    @State var selectedDog: Dog?
    var body: some View {
        NavigationView {
            List {
                ForEach(dogs) { dog in
                    Text("\(dog.name) has \(dog.owners.count) owners")
                        .onTapGesture {
                            selectedDog = dog
                        }
                }
            }
            .navigationTitle("Dogs")
            .navigationBarItems(
                leading: Button("Add owner", action: addOwnerToDog).disabled(selectedDog == nil),
                trailing: Button(action: { $dogs.append(Dog()) }) {
                    Image(systemName: "plus.app.fill")
                }
            )
        }
    }

    func addOwnerToDog() {
        let realm = try! Realm()
        let newOwner = Owner()
        let dog = realm.object(ofType: Dog.self, forPrimaryKey: selectedDog!._id)

        try! realm.write {
            if let dog = dog {
                newOwner.dogs.append(dog)
            }
            realm.add(newOwner)
        }
    }
}
```
## Version of Realm and Tooling

Realm framework version: 10.7.4

Xcode version: 12.5

iOS/OSX version: 14.5

Dependency manager + version: Swift Package Manager

**Comment by jsflax** [comment]
Hey @mush159,

You're not actually observing the Dog being modified.

I would recommend making the row in your `ForEach` a sub view (which would be more practical in a real world case anyway):

```swift
struct DogRowView: View {
    @ObservedRealmObject var dog: Dog
    @Binding var selectedDog: Dog?

    var body: some View {
        Text("\(dog.name) has \(dog.owners.count) owners")
            .onTapGesture {
                selectedDog = dog
            }
    }
}
struct ContentView: View {
    @ObservedResults(Dog.self) var dogs
    @State var selectedDog: Dog?
     var body: some View {
        NavigationView {
            List {
                ForEach(dogs) { dog in
                    DogRowView(dog: dog, selectedDog: $selectedDog)
                }
            }
            .navigationTitle("Dogs")
            .navigationBarItems(
                leading: Button("Add owner", action: addOwnerToDog).disabled(selectedDog == nil),
                trailing: Button(action: { $dogs.append(Dog()) }) {
                    Image(systemName: "plus.app.fill")
                }
            )
        }
    }

    ...
}
```

Let me know if that clears it up for you.

**Comment by mush159** [comment]
Hey @jsflax, thanks for the response!

Agree that each row it would be better as a sub view so I tried modifying the example code to the above but still hit the same issue.

In the original example, should the `@ObservedResults(Dog.self) var dogs` query not be notified of a change to any object in the dog collection and re-render the view anyway?

Interestingly adding `@ObservedResults(Owner.self) var owners` to  `ContentView` does cause a re-render, which makes sense as adding an owner to a dog is modifies the owner collection, prompting a re-render.

I guess a change to the to the owner via the `LinkingObjects` backlink isn't being tracked for some reason?

**Comment by dianaafanador3** [comment]
Hi @mush159 we don't generate notifications for changes to `LinkingObjects` because the relevant code doesn't know what backlinks the user actually cares about, so in your case changes to the backlink will not re-render the view when observing `Dog`. 
Observing `Owner` even though you are not using within the View will cause a view update and will work for your example. 
We are developing a new feature  [Keypath Filtering](https://github.com/realm/realm-cocoa/pull/7249), which lets you explicitly include `LinkingObjects` properties which you do want notifications for.
