### ISSUE TITLE
Impossible to delete objects of removed type during Migration

### ISSUE THREAD

**Issue by jeanbaptistebeau** [realm/realm-cocoa#7244]
## Goals
Let's say I had objects of type `Dog` and `Person` in my Realm database, where `Person` has a property of `List<Dog>`. In my update, I want to remove completely the dogs. So I do the following:

- I remove the property of type `List<Dog>` from `Person`
- I remove `Dog.self` from `configuration.objectTypes` to that the type `Dog` is no longer used in this Realm. In my case, I keep the `Dog` class because I need it for another Realm.
- I increment the schema version number
- I add a migration block that deletes all the objects of type `Dog`

## Expected Results
I expect that the migration block completes without error and that after, there is no more object of type `Dog` in my database. In fact, if my database only contained `Person` and `Dog` objects, and I removed all the Person objects for some reason, I expect that `realm.isEmpty` is true.

## Actual Results
If I do `migration.deleteData(forType: "Dog")` in the migration, I get the error `Table is target of cross-table link columns`. Note that Dog was referenced by `Person` in the old schema, but is not referenced by any other class in the new schema.

If I do:
```
migration.enumerateObjects(ofType: "Dog") { (oldObject, newObject) in
     migration.delete(oldObject!)
}
```
I get the error `Can only delete an object from the Realm it belongs to`. See #6799.

If I do:
```
migration.enumerateObjects(ofType: "Dog") { (oldObject, newObject) in
     migration.delete(newObject!)
}
```
It crashes because `newObject` is nil for all the objects of type `Dog`.

## Steps for others to Reproduce
Have a first schema version with types `Dog` and `Person` where `Person` has a `List<Dog>`. Now remove the `List<Dog>` property of Person, and remove `Dog.self` from `configuration.objectTypes`. In your migration block, try to delete the objects of type `Dog`.

## Code Sample
See above.

## Version of Realm and Tooling
Realm framework version: 10.7.2
Xcode version: 12.4
iOS/OSX version: 14.4.2
Dependency manager + version: CocoaPods

**Comment by jeanbaptistebeau** [comment]
EDIT: Forgot to mention that the `Dog` class had a backlink property (`LinkingObjects`) to `Person` in the old schema.

In #3686, in 2016, @kishikawakatsumi mentioned that it's not possible to delete a model class with a backlink property. Is that still the case?

**Comment by dianaafanador3** [comment]
HI @jeanbaptistebeau, We'll take a look at your code and let you know how to solve this as soon as we can

**Comment by jeanbaptistebeau** [comment]
@dianaafanador3 any news?

**Comment by dianaafanador3** [comment]
Hello @jeanbaptistebeau I've been able to reproduce your issue, and we do need to support deleting tables with a backlink property to other tables during migration, like in your case. 
For now this is still the case and cannot be done.

What I can do is help you to migrate your current schema to the desire one.
I split your change into two schema versions updates:

First schema version bump
* Remove your property of type `List<Dog>` from `Person`
* Remove your backlink from your `Dog` object
* Keep your `Dog` type in your objectTypes configuration
* And add this migration block
`migration.enumerateObjects(ofType: "Dog") { (oldDogObject, newDogObject) in
       migration.delete(newDogObject!)
}`
This will remove all your `Dog` objects from your their table, your backlinks to your `Person` table and your property dogs from your `Person` table

Second schema version bump
* Remove your `Dog` type in your objectTypes configuration
* Delete the inheritance from `Object` to your type `Dog`
* Add this to your migration block
`migration.deleteData(forType: "Dog")`
This will remove your `Dog` table from your realm file.

**Comment by jeanbaptistebeau** [comment]
@dianaafanador3 Your solution worked! Thanks a lot for your help!

**Comment by dianaafanador3** [comment]
Hi @jeanbaptistebeau I'm glad you've been able to solve this. Closing the issue.

**Comment by quentinfasquel** [comment]
> @dianaafanador3 Your solution worked! Thanks a lot for your help!

I am not really sure how this works in every case.
If you execute your app migrating from 1 to 2, then execute migrating from 1 to 3, this will work.
However when a user migrates directly from 1 to 3, then newDogObject will be nil and crash or the same issue will happen.

This seems like a missing feature in Realm, or I am missing something...
