### ISSUE TITLE
Flutter build fails when the xcode was updated to latest version

### ISSUE THREAD

**Issue by ohm1998** [realm/realm-cocoa#7245]
**Bugs**: Updated my Xcode version and throws me this error.

`/Users/apple/Desktop/dt2/ios/Pods/RealmSwift/RealmSwift/Combine.swift:38:40: error: 'Identifiable' is only available in application extensions for iOS 13 or newer
    public protocol ObjectKeyIdentifiable: Identifiable, Object {
                                           ^
    /Users/apple/Desktop/dt2/ios/Pods/RealmSwift/RealmSwift/Combine.swift:38:17: note: add @available attribute to enclosing protocol
    public protocol ObjectKeyIdentifiable: Identifiable, Object {
                    ^
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:111:11: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
            else if (![upgradeHeaderValue caseInsensitiveCompare:@"WebSocket"] == NSOrderedSame) {
                     ^                                                         ~~
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:111:11: note: add parentheses after the '!' to evaluate the comparison first
            else if (![upgradeHeaderValue caseInsensitiveCompare:@"WebSocket"] == NSOrderedSame) {
                     ^
                      (                                                                        )
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:111:11: note: add parentheses around left hand side expression to silence this warning
            else if (![upgradeHeaderValue caseInsensitiveCompare:@"WebSocket"] == NSOrderedSame) {
                     ^
                     (                                                        )
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:181:28: warning: sending 'WebSocket *__strong' to parameter of incompatible type 'id<GCDAsyncSocketDelegate> _Nullable'
                    [asyncSocket setDelegate:self delegateQueue:websocketQueue];
                                             ^~~~
    In module 'CocoaAsyncSocket' imported from /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:3:
    /Users/apple/Desktop/dt2/ios/Pods/CocoaAsyncSocket/Source/GCD/GCDAsyncSocket.h:112:58: note: passing argument to parameter 'delegate' here
    - (void)setDelegate:(nullable id<GCDAsyncSocketDelegate>)delegate delegateQueue:(nullable dispatch_queue_t)delegateQueue;
                                                             ^
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:171:30: warning: code will never be executed [-Wunreachable-code]
                            NSData *requestHeaders = [aRequest messageData];
                                                      ^~~~~~~~
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:218:3: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    delegate = newDelegate;
                    ^
                    self->
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:237:7: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    if (isStarted) return;
                        ^
                        self->
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:238:3: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    isStarted = YES;
                    ^
                    self->
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:240:7: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    if (isVersion76)
                        ^
                        self->
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:263:4: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    [asyncSocket disconnect];
                     ^
                     self->
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:414:21: warning: code will never be executed [-Wunreachable-code]
                    NSString *temp = [[NSString alloc] initWithData:responseHeaders encoding:NSUTF8StringEncoding];
                                      ^~~~~~~~~~~~~~~~
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:496:19: warning: code will never be executed [-Wunreachable-code]
                    NSString *s1 = [[NSString alloc] initWithData:d1 encoding:NSASCIIStringEncoding];
                                    ^~~~~~~~~~~~~~~~
    /Users/apple/Desktop/dt2/ios/Pods/KTVCocoaHTTPServer/KTVCocoaHTTPServer/Classes/WebSocket.m:39:20: warning: unused function 'WS_OP_IS_FINAL_FRAGMENT' [-Wunused-function]
    static inline BOOL WS_OP_IS_FINAL_FRAGMENT(UInt8 frame)`

## Version of Realm and Tooling

Realm framework version: ?

Xcode version: 12.5

iOS/OSX version: 14+

Dependency manager + version: ?

**Comment by jsflax** [comment]
Hey, it looks like there are a number of issues with the pods you are using, but in the Realm case, be sure to be using the latest version. That issue was fixed in 10.5.2.

**Comment by ohm1998** [comment]
Okay . I reverted back to Xcode 12.4 and it worked for me.
