### ISSUE TITLE
Is it possible to combined Results<> in a query

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7247]
I am trying to get a list of all "Child" objects from a set of "Parent" Objects.  Something like below:

The model is as follows (simplified example)

```
    class Parent: Object {
       let id = ObjectId()
       let name: String = "some name"
    
       let children = List<Child>
    }
    
    class Child: Object {
       let id = ObjectId()
       let name: String = "some name"
    
    }
```

How can I get all the parents children back as a since results set ?  It seems odd to define the `var all` as a `LazySequence<FlattenSequence<LazyMapSequence<Results<Parent>, List<Child>>.Elements>>`
    
 ```
   extension Child {
    
       var all: Results<Child> {
          let parents = realm.objects(Parent.self)
    
          // Returns LazyMapSequence<Results<Parent>, List<Child>>
          let children = parents.map({$0.children})
    
          // Returns LazySequence<FlattenSequence<LazyMapSequence<Results<Parent>, List<Child>>.Elements>>
          let all = children.joined()
    
          return all
       }
    }
```

**Comment by dianaafanador3** [comment]
HI @duncangroenewald, 
First, Why don't just get all the children from
```swift
let children = realm.objects(Child.self)
```
, this will return all of the objects from the `Child` table.

Second, If you want to get all the children from the parents (because maybe you want to get duplicated values from children who belong to different parents). You can have something like this
```swift 
static var all: [Child] {
        let realm = try! Realm()
        let parents = realm.objects(Parent.self)
        var childArray: [Child] = []
        for element in parents {
            childArray.append(contentsOf: element.children.compactMap { $0 })
        }
        return childArray
    }
    ```
    
Even though you can use transformation methods (map, compactMap and flatMap) with Results, this type is not a `Sequence` and will not return what you expect.

**Comment by duncangroenewald** [comment]
Sure I can always just convert the results to arrays and join the arrays.

The basic issue is that each parent knows which of its children to return depending on the circumstances.

For example

```
extension Parent {

   func getChildrenFor(_ event: SomeEvent) -> Results<Child> {
    let somePredicate = .... // "some predicate based on the parent"
    return self.children.filter(somePredicate)
   }
}
```

So of course I could just do this

`let childrenForEvent: [Child] = parents.map({$0.getChildrenFor(someEvent)}).map({Array($0)}).joined()`

But this is no longer a live Results<> set and won't auto update.

Anyway I am now thinking to just get the Parent to return the [NSPredicate] array and then I can use this

```
extension Parent {

   func getChildrenPredicatesFor(_ event: SomeEvent) -> [NSPredicate] {

    let predicates = [NSPredicate]()

    let somePredicate1 = .... // "some predicate based on the parent"
    predicates.append(somePredicate1)
    ...
   let somePredicateN = .... // "some predicate based on the parent"
    predicates.append(somePredicateN)
    
    return predicates
   }
}

let compoundPredicate = NSCompoundPredicate( andPredicateWithContents: parents.map({$0. getChildrenPredicatesFor(someEvent)}))

let childrenForEvent = realm.objects(Child.self).filter(compoundPredicate)
```

Something like this anyway -  I will give it a try and provide an update.  Can't see why to wouldn't work though.

**Comment by dianaafanador3** [comment]
Hello again @duncangroenewald, what you need is to get a live object, sorry i didn't go that way. 
Correct me if I'm wrong, but you want to get a live Results<Child>, from a live Results<Parent> which has been filtered already.
Let me know if your solution works, on my part I'll try to investigate more how to do this.

**Comment by dianaafanador3** [comment]
Hi @duncangroenewald just passing around to make sure you found a solution for this?

**Comment by duncangroenewald** [comment]
There is no way to combine results so I ended up creating a compound predicate to then filter the "child" objects.

**Comment by dianaafanador3** [comment]
Hi @duncangroenewald This is something that will be easier to implement with our 'Type safe query' syntax project, we are always working to make our API easier and modern.
Thanks for getting back to us so quickly.
Closing this as the user solve it
