### ISSUE TITLE
Linker error "ld: library not found for -lc++"

### ISSUE THREAD

**Issue by toriaezunama** [realm/realm-cocoa#725]
I followed the instructions from http://realm.io/docs/cocoa/0.81.0/ to the letter for installing Realm with Swift but I get the following linker error:

```
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am using XCode 6 Beta 4 and the device I am targeting is an iPhone 4S

Does anyone have any ideas what is causing this?

**Comment by owenoak** [comment]
I had the same problem with a swift project in Xcode 6.3.1 (6D1002).  To fix it I:

1) Cloned the github project:
    > git clone https://github.com/realm/realm-cocoa
2) cd into that dir and run the build command
   > cd realm-cocoa
   > sh build.sh build
3) Found the "RealmSwift.framework" file and use that to follow the installation instructions at:
   http://realm.io/docs/swift/latest/

**Comment by jpsim** [comment]
@owenoak how did you install Realm for it to fail in the first place, before you fixed it?

**Comment by owenoak** [comment]
1) I downloaded "Realm Swift" via the big blue button here:
http://realm.io/docs/swift/latest/

2) I attempted to integrate into my project following the instructions on that page.
