### ISSUE TITLE
Crash "Key already used" after upgrading RealmSwift 3.21.0 --> 5.5.1

### ISSUE THREAD

**Issue by Ogerets** [realm/realm-cocoa#7250]
## Goals
Save new object with **Int** primary key after upgrading RealmSwift 3.21.0 --> 5.5.1

## Expected Results
Object created in Realm

## Actual Results
Crash with "Key already used" message on adding new object
```
2021-05-10 15:09:13.622839+0300 realm-test[12261:2913798] *** Terminating app due to uncaught exception 'RLMException', reason: 'Key already used'
*** First throw call stack:
(0x1bfe65654 0x1bfb87bcc 0x105009ca8 0x104bc94e8 0x1049509d4 0x10494fe70 0x1049508dc 0x104950938 0x104bc86a8 0x104950820 0x10494fda0 0x10494fccc 0x10494d960 0x10494daac 0x1c3f0fc14 0x1c3f119a0 0x1c3f1723c 0x1c36bba68 0x1c3f13280 0x1c3f135d4 0x1c3f193e4 0x1f6a602b4 0x10494e310 0x10494e288 0x10494e354 0x1bfc658f0)
libc++abi.dylib: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RLMException', reason: 'Key already used'
```

## Steps for others to Reproduce
Create at least one object in Realm for Entity, which primaryKey is Int at RealmSwift 3.21.0
Upgrade RealmSwift to 5.5.1
Try to create new object with new id

## Code Sample
https://github.com/Ogerets/realm-test/tree/develop-v3.21.0
https://github.com/Ogerets/realm-test/tree/develop-v5.5.1

## Version of Realm and Tooling

Realm framework version: 3.21.0 --> 5.5.1

Xcode version: 12.4

iOS/OSX version: 13.7

Dependency manager + version: Cocoapods 1.10.1

## Extra Info
- Trying to create new object in RealmStudio 5.0.0 also fails with same error "Key already used", despite there's no object with such key. [Here](https://drive.google.com/file/d/1_-tFfLzG4btMyS656530d3sb36fXHCGK/view?usp=sharing) is realm file after upgrade on which it can be reproduced.
- Upgrading 3.21.0 --> 5.5.0 works fine.
- For Entities with **String** primary key no problem occurs.
- Downgrade to 5.5.0 after 5.5.1 does not help.
- Upgrading from versions >3.21.0 to 5.5.1 seems to be okay.

**Comment by dianaafanador3** [comment]
HI @Ogerets, Can you migrate to latest version 10.7.5 (https://github.com/realm/realm-cocoa/releases/tag/v10.7.5)? On the meantime I'll take a look at your code, and will give you an answer as soon as I can.

**Comment by Ogerets** [comment]
Hi @dianaafanador3, thanks for the response!
I can confirm **v10.7.5** fixes the issue. However, we're considering upgrading to v10 only as last possible case, since we experienced pretty stable behaviour of v5.5.0 version. 
Also we tried testing v10.5.0 at winter and had very frequent crashes, connected with [this](https://github.com/realm/realm-cocoa/issues/7011) issue. It's probably fixed by now, but it's still hard decision, cause there's no rollback option.

**Comment by Ogerets** [comment]
@ianpward, Sounds great. I've just tried it in test project and found created backup file. As I understood, for versions pre v10.7.3, I need to catch unsupported format error on Realm open, then find backup, which filename is different for different upgraded fileformats, swap them and delete unsupported format realm file. Sounds a little bit tricky, but having such possibility is better then nothing.

**Comment by Ogerets** [comment]
@dianaafanador3 I tried transition from 3.21.0 to most of v10 versions, including early ones, and wasn't able to reproduce an issue. Sounds like it's specific for v5.5.1. 
Unfortunately, updating to the latest version is still a problem for us. In fact, the biggest issue is that users who experienced transition 3.21.0 --> 5.5.1 --> 5.5.0 can't use our app. And we can't identify them to force clean db. So, if fixing 5.5.1 is a struggle, it would be great at least to have a way to identify corrupted realm. Can you help us with that, please? [Corrupted realm file](https://drive.google.com/file/d/1_-tFfLzG4btMyS656530d3sb36fXHCGK/view?usp=sharing) after upgrade could be useful for it.

**Comment by bmunkholm** [comment]
> As I understood, for versions pre v10.7.3, I need to catch unsupported format error on Realm open, then find backup, which filename is different for different upgraded fileformats, swap them and delete unsupported format realm file. Sounds a little bit tricky, but having such possibility is better then nothing.

If there is a crash while migrating a realm file, we will automatically revert to the backup file when rebooting.

**Comment by Ogerets** [comment]
@bmunkholm, Got it. But starting from which version Realm has such behaviour? Also rolling back Realm version doesn't always mean there will be a crash on migration (unless direct fatal from code). Please, correct me if I'm wrong. 
Is there a way to trigger reverting to the backup file in sdk after catching unsupported realm format error? I like this approach more, since there will be no initial crashes.

**Comment by dianaafanador3** [comment]
Hi @Ogerets to answer your questions. 
This behaviour is available from v10.7.3, as mentioned if there is a crash during migration, we will automatically revert to the backup file.

**Comment by Ogerets** [comment]
@dianaafanador3, is there any progress on this issue?

**Comment by dianaafanador3** [comment]
HI @Ogerets, support for reverting to the backup file when rebooting when there is a crash on migrations is available from v10.7.3. 
Reverting to the backup file is done by core, and there is no api to force this from our SDK.

**Comment by Ogerets** [comment]
@dianaafanador3, okay, I got it, thanks. What about fixing v5.5.1 transition from v3.21.0 or at least identifying [corrupted realm file](https://drive.google.com/file/d/1_-tFfLzG4btMyS656530d3sb36fXHCGK/view)?

**Comment by dianaafanador3** [comment]
Hello @Ogerets the bug in core may take a while to be addressed, as we are focusing our effort into releasing new features and fixing bug in our latest version,  also we are maintaining this version (v5.5.1) for current RealmCloud users which will be migrated shortly to use MongoDBRealm so the best option is to update to our latest version. 
I've been checking your realm file and it does not look like there is any corrupted data, the issue with 'Key already used' is not your realm file but some bug in core, so if you force this users to update to latest version they can still use the same realm file.
Let me know if I'm mistaken in something or anything else we can help.

**Comment by duncangroenewald** [comment]
@Ogerets - hi - we had the same issue and the bug has never been fixed.  It is caused by more than one record in the database that has an internal ID = 0 - which should be impossible.  Somewhere there is a report back from one of the Realm team regarding this issue.  Unfortunately I never did find out how to debug this to find the faulty records so they could be deleted to allow the upgrade to proceed.

In the end I think we managed to make a backup and then upgrade using the backup file.  The errant records seem to get created if we opened the backup file with the older SDK first, anyway something like that - I can't recall the exact details now.  We are running with Realm Cloud and found the upgrade seemed to work fine on the synced clients but failed when done in development with a local client.   In any event we have been running 5.5.1 and 5.5.2 for some 3 months now and they seem stable and very fast.

Just recently trying to upgrade to 10.7.x and seeing a very bad performance hit on queries that makes the application unusable.  Just starting to raise the issue so we will see what happens.

Not sure if this helps you much but there you go.  Cheers.

**Comment by bb-git** [comment]
I also see this error and I just updated from 5.5.0 to 5.5.1

**Comment by bb-git** [comment]
> @Ogerets We now create a backup of the realm file when you upgrade major versions - so we are now giving you the capability to rollback if you are seeing serious regressions
> https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md#enhancements-2

@ianpward can you clarify this? Does it mean upgrading to 10.7.6 creates and backup and I could go back to 5.5.0? I didn't get that working. Or does this account only to future versions?

**Comment by dianaafanador3** [comment]
HI @bb-git upgrading from v5.5.0 to 10.7.6 for example will update realm format version file from v11 to v20, which will indeed trigger a backup creation. Have you been able to solve this issue?

**Comment by dianaafanador3** [comment]
Closing this as there is no response from the user. I can open it again if it is not solved by now.
