### ISSUE TITLE
Building error on Xcode 12.5

### ISSUE THREAD

**Issue by dabaicaifen** [realm/realm-cocoa#7251]
## Goals
Migrate from Cocoapods to SPM to integrate Realm.

## Expected Results
No Buiding error

## Actual Results
<img width="480" alt="Screen Shot 2021-05-10 at 16 50 40" src="https://user-images.githubusercontent.com/25300313/117723290-38309300-b1b0-11eb-8718-c413c402ab0c.png">
<img width="606" alt="Screen Shot 2021-05-10 at 16 50 20" src="https://user-images.githubusercontent.com/25300313/117723298-3a92ed00-b1b0-11eb-80a2-aca603da8650.png">

## Steps for others to Reproduce
1, Import Realm and RealmSwift to multiple modules.
2, Build and run

## Version of Realm and Tooling

Realm framework version: 10.7.4

Xcode version: 12.5

iOS/OSX version: iOS 14.5 / Big Sur 11.3.1

Dependency manager + version: Swift Package Manager

**Comment by dianaafanador3** [comment]
HI @dabaicaifen, Realm and RealmSwift should work fine with Xcode 12.5 and Swift Package manager. Maybe you have some different setup for modularisation or even different dependencies managers (cause you are migrating) in the same project. Can you maybe explain a little bit further your current setup?

**Comment by dianaafanador3** [comment]
Hi @dabaicaifen I will try to duplicate your current setup in a local project and been able to duplicate this error. Also, If you can share your SPM configuration for one/many modules on your app that will be very helpful.

**Comment by dabaicaifen** [comment]
@dianaafanador3 
I didn't do any special setup for Realm, imported using Xcode.
Here's the `Package.resolved` if it is helpful......

```
{
        "package": "Realm",
        "repositoryURL": "https://github.com/realm/realm-cocoa.git",
        "state": {
          "branch": null,
          "revision": "239a6a383af5d4b445626a95aa6356925e6acf22",
          "version": "10.7.4"
        }
      },
      {
        "package": "RealmDatabase",
        "repositoryURL": "https://github.com/realm/realm-core",
        "state": {
          "branch": null,
          "revision": "28ed052d10d2245542b4fbdc71d388febb1e9bc4",
          "version": "10.6.0"
        }
      }

**Comment by dianaafanador3** [comment]
Hi @dabaicaifen, it looks like the issue you are seeing comes from the core module, but it may be something to do with your configuration rather on how our SPM is created. 
I added a sample project using SPM an importing it to several SPM modules, I added a dependency with cocoapods to simulate a mix project, too. Maybe this can help you as template for your project.
https://github.com/dianaafanador3/RealmModulesPlayground/tree/master

**Comment by dianaafanador3** [comment]
HI @dabaicaifen Have you been able to solve this?

**Comment by dabaicaifen** [comment]
@dianaafanador3  Your sample is not similar to my case. The multiple modules, I mean
<img width="52" alt="Screen Shot 2021-05-28 at 5 51 56 PM" src="https://user-images.githubusercontent.com/25300313/120045245-8b427c80-bfdd-11eb-9b91-c37ef3cb930b.png">

**Comment by dianaafanador3** [comment]
Hi @dabaicaden I haven't been able reproduce your issue. I created another project that may be more similar to yours https://github.com/dianaafanador3/RealmModulesProjectsPlaygorunds/tree/master that you can take as a reference. 
I try always to start with a clean project, first installing my cocoa-pods dependencies and then adding my local modules to the workspace. 
This error may be caused by old project configurations from your old Realm dependencies from cocoapods and creates some conflicts within your project. Also, please update to latest Realm version 10.7.6.

**Comment by dabaicaifen** [comment]
@dianaafanador3 I only saw 1 available module......
<img width="236" alt="Screen Shot 2021-06-06 at 4 47 47 PM" src="https://user-images.githubusercontent.com/25300313/120939646-00e9cf00-c6e7-11eb-9340-f795139c0e79.png">

**Comment by dianaafanador3** [comment]
Hi @dabaicaifen I already updated the repo with the right setup https://github.com/dianaafanador3/RealmModulesProjectsPlaygorunds/tree/master

**Comment by dianaafanador3** [comment]
Hi @dabaicaifen any changes you took a look at this or somehow solve this issue?

**Comment by ericjordanmossman** [comment]
Closing this issue because of no response.
@dabaicaifen - If this is still an issue and I'm incorrectly closing it, please respond and we can re-open it. :)
