### ISSUE TITLE
Question on xcframework

### ISSUE THREAD

**Issue by keithcml** [realm/realm-cocoa#7258]
May I know is the prebuilt xcframework supports Swift ABI compatibility?

a.k.a. BUILD_LIBRARY_FOR_DISTRIBUTION set to YES

**Comment by leemaguire** [comment]
Hi @keithcml while we do support Swift evolution mode, `BUILD_LIBRARY_FOR_DISTRIBUTION ` is set to `NO` by default

**Comment by keithcml** [comment]
@leemaguire great to hear about that.
So from now on, we can upgrade the binary when we need an updates instead of new Swift version forces us to upgrade the binary.

**Comment by leemaguire** [comment]
While we support it, we are not distributing the binary with `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`.

**Comment by leemaguire** [comment]
Closing as question has been answered.
