### ISSUE TITLE
Problem compiling 10.7.6 SPM with Swift development toolchain

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7265]
## Goals
Trying to sort out an Swift compiler bug and testing using the latest Swift development toolchain and have run into this error in file to_string.cpp (RealmDatabase/src/realm/util)

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/13807324/119241128-98074080-bb97-11eb-9454-f880c8176d36.png">

## Expected Results
Expect to be able to compile SPM 10.7.6 with the latest Swift toolchain

## Actual Results
Does that reference to strtoul(). need to be changed to std::strtoul() 

## Steps for others to Reproduce
Install latest Swift toolchain and select this in Xcode 12.5 and build project using SPM 10.7.6

## Code Sample
see above

## Version of Realm and Tooling

Realm framework version: RealmSwift SPM 10.7.6

Xcode version: 12/5

iOS/OSX version: maxOS11.3

Dependency manager + version: -

**Comment by jsflax** [comment]
Are you trying to use the development snapshot for Swift 5.5? If so, there are a number of changes we need to make on our side first before that's going to work properly.

I have a local setup that has it working, so let me know if you would like some help in setting that up.

**Comment by duncangroenewald** [comment]
Yes - trying to fix a Swift compiler crash/bug and Apple asked to test with the latest swift toolchain - which presumably is using Swift 5.5.

The compiler bug is unrelated to the Realm libraries but the project is using SPM 10.7.6 so of course won't build without it.

By local setup I assume you mean a clone of realm-cocoa repo with some changes you have made? 

(If I sound stupid that's because this is like the race car driver being asked to change the oil ! )

**Comment by jsflax** [comment]
I would recommend cloning Realm Cocoa, building it once (this is important to generate the core xcframework) with the current Xcode 12.5 toolchain, and then checking out `jf/async-write`. From there, reference the local `realm-cocoa` directory in your `Package.swift`. Your `Package.swift` should look something like this:

```swift
let package = Package(
    name: "RainyDay",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .executable(
            name: "RainyDay",
            targets: ["RainyDay"]),
    ],
    dependencies: [
        .package(name: "Realm", path: "../realm-cocoa")
    ],
    targets: [
        .target(
            name: "RainyDay",
            dependencies: [
                .product(name: "RealmSwift", package: "Realm")
            ],
            swiftSettings: [
                .unsafeFlags(["-parse-as-library"]), // @main at top level
                .unsafeFlags([
                    "-Xfrontend", "-enable-experimental-concurrency",
                    "-Xfrontend", "-disable-availability-checking"
                ])
            ]),
        .testTarget(
            name: "RainyDayTests",
            dependencies: ["RainyDay"]),
    ]
)
```

Please keep in mind that anything on this branch is experimental 😄 .

**Comment by leemaguire** [comment]
Closing this issue as steps have been provided.
