### ISSUE TITLE
 'Primary key property 'id' does not exist on object '''

### ISSUE THREAD

**Issue by 624990742** [realm/realm-cocoa#7267]
使用的是RealmSwift  10.8.0-beta.1出现如下错误：

两个错误：
1. error: module importing failed: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/Library/Application Support/Realm/rlm_lldb.py", line 37
    os.makedirs(destination, 0744)
                                ^
2.Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'id' does not exist on object '''
请问这两个问题怎么解决呢？

**Comment by ericjordanmossman** [comment]
@624990742 Could you please fill out the [issue template](https://github.com/realm/realm-cocoa/blob/master/.github/ISSUE_TEMPLATE.md) so we can better understand the issue?

**Comment by 624990742** [comment]
!!! MANDATORY TO FILL OUT !!!


## Goals


## Expected Results


## Actual Results


## Steps for others to Reproduce


## Code Sample


## Version of Realm and Tooling

Realm framework version: RealmSwift 10.8.0-beta.1

Xcode version: xcode 12.5

iOS/OSX version: 14.5

Dependency manager + version: cocoapods 1.10.1

**Comment by 624990742** [comment]
Thank you very much. At present, the second problem has been solved. It's my own mistake. That's all that's left.Error log:
error: module importing failed: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jiachen/Library/Application Support/Realm/rlm_lldb.py", line 37
    os.makedirs(destination, 0744)

Realm framework version: RealmSwift 10.8.0-beta.1
Xcode version: 12.5
iOS/OSX version: ios 14.5
Dependency manager + version: cocoapods  1.10.1

**Comment by leemaguire** [comment]
@624990742 Are you using any old Realm Xcode plugins? Please see https://github.com/realm/realm-cocoa/issues/6367 as it may have the answer to your issue.
