### ISSUE TITLE
Realm Config Fails To Create Intermediate Directories

### ISSUE THREAD

**Issue by bdkjones** [realm/realm-cocoa#7270]
## Goals

I want Realm to consistently create directories when needed so that I can organize all the various database files into a subfolder of my Application Support folder.

## Expected Results
Given this code:

```
let supportFolder: URL = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!.appendingPathComponent(Bundle.main.bundleIdentifier!)

var config = Realm.Configuration()
config.fileURL = supportFolder.appendingPathComponent("database").appendingPathComponent("main.realm")

let realm = Realm(configuration: config)
```

I expect Realm to *create* the folder `database` when it's missing:

    ~/Library/Application Support/com.appname/database/main.realm

This expectation is valid because Realm automatically creates OTHER missing folders it needs, such as `mongodb-realm`. It also automatically creates the final file `main.realm` as long as the folder `database` already exists.

## Actual Results
Realm throws an error:

```
Error opening main Realm: Unable to open a realm at path '~/Library/Application Support/com.appname/database/main.realm.management': make_dir() failed: No such file or directory
```

The folder `database` must exist. Then Realm operates correctly. But this is inconsistent with the other folders/files that Realm creates, which need not exist and are created on-demand. That pattern should extend to `fileURL`. I've told Realm where the database file lives. If it's missing (i.e. this is the app's first launch), create it!

## Steps for others to Reproduce
Do the above.

## Code Sample
Above.

## Version of Realm and Tooling

Realm framework version: 10.7.6

Xcode version: 12.5

iOS/OSX version: macOS 11.4

Dependency manager + version: Swift Package Manager

**Comment by pavel-ship-it** [comment]
Hi @bdkjones 
This is not a bug. The directory in which you're creating the Realm file must already exist.

Creation of each directory involves assignment of access rights and error handling which is responsibility to the app itself.

**Comment by bdkjones** [comment]
I think the primary issue is that I’m expecting this API to do one thing and its official purpose is something else. What I REALLY want is to tell Realm, “Stop polluting the root of my Application Support folder with a bunch of files and folders. Instead, put all your stuff in this subfolder called ‘database’”.

Realm appears to create a bunch of files/folders in the root Application Support folder regardless, leading to a bunch of disorganization with other content that my app puts there.

The reason I want all of Realm’s local data in a subfolder is so that I can easily nuke it when a user holds a certain key combo while launching my app. Right now, I have to sift through all the clutter in the root Application  Support folder and delete Realm’s files and folders one by one.

**Comment by pavel-ship-it** [comment]
Creation of auxiliary files is a [documented](https://docs.mongodb.com/realm/sdk/ios/fundamentals/realms/#realm-files) behaviour.
Also you still can use custom directory for a Realm and aux-files:
``` 
        let docURL = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
            .appendingPathComponent(Bundle.main.bundleIdentifier!)
            .appendingPathComponent("database")
        if !FileManager.default.fileExists(atPath: docURL.absoluteString) {
            try! FileManager.default.createDirectory(at: docURL, withIntermediateDirectories: true, attributes: nil)
        }
        var config = Realm.Configuration()
        config.fileURL = docURL.appendingPathComponent("main.realm")
        let realmReal = try! Realm(configuration: config)
```
Please be careful while deleting a Realm files. Alternatively you can use `deleteAll()` to wipe the data in a Realm.

**Comment by bdkjones** [comment]
Thanks. That’s what I mean: I wanted to relocate all the auxiliary files AND the *.realm file to a subfolder. That does not appear to be possible.

-Bryan
