### ISSUE TITLE
realm::GroupWriter::FreeList::move_free_in_file_to_size_map+ 

### ISSUE THREAD

**Issue by raghunrmediacorp** [realm/realm-cocoa#7276]
!!! MANDATORY TO FILL OUT !!!
Crashing on app Launch after upgraded the app with new SDK - RealmSwift (10.7.6)

Hardware Model:      iPhone12,8
AppStoreTools:       12E262
AppVariant:          1:iPhone12,8:13
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]

Date/Time:           2021-06-04 12:39:46.0610 +0800
Launch Time:         2021-06-04 12:39:25.9729 +0800
OS Version:          iPhone OS 14.6 (18F72)
Release Type:        User
Baseband Version:    2.05.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, <RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-create watchdog transgression:  exhausted real (wall clock) time allowance of 19.60 seconds | ProcessVisibility: Unknown | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 23.660 (user 23.660, system 0.000), 20% CPU", | "Elapsed application CPU time (seconds): 3.562, 3% CPU" | ) reportType:CrashLog maxTerminationResistance:Interactive>
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_malloc.dylib        	0x0000000194e7cff8 0x194e6f000 + 57336
1   libsystem_malloc.dylib        	0x0000000194e7cf40 0x194e6f000 + 57152
2   libsystem_malloc.dylib        	0x0000000194e7cf40 0x194e6f000 + 57152
3   libsystem_malloc.dylib        	0x0000000194e819a0 0x194e6f000 + 76192
4   libc++abi.dylib               	0x000000019a407894 0x19a3f2000 + 88212
5   Realm                         	0x0000000106077224 realm::GroupWriter::FreeList::move_free_in_file_to_size_map+ 1372708 (std::__1::multimap<unsigned long, unsigned long, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, unsigned long> > >&) + 112
6   Realm                         	0x00000001060763b4 realm::GroupWriter::read_in_freelist+ 1369012 () + 960
7   Realm                         	0x0000000106075628 realm::GroupWriter::write_group+ 1365544 () + 64
8   Realm                         	0x000000010605ca48 realm::DB::low_level_commit+ 1264200 (unsigned long long, realm::Transaction&) + 380
9   Realm                         	0x000000010605c884 realm::DB::do_commit+ 1263748 (realm::Transaction&) + 152
10  Realm                         	0x000000010605dd1c realm::Transaction::commit_and_continue_writing+ 1269020 () + 88
11  Realm                         	0x000000010606c0a0 realm::Transaction::upgrade_file_format+ 1327264 (int) + 2336
12  Realm                         	0x0000000106059458 realm::DB::upgrade_file_format+ 1250392 (bool, int, int, int) + 288
13  Realm                         	0x0000000106057144 realm::DB::do_open+ 1241412 (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, realm::DBOptions) + 3992
14  Realm                         	0x0000000106059b64 realm::DB::open+ 1252196 (realm::Replication&, realm::DBOptions) + 148
15  Realm                         	0x000000010605ec4c realm::DB::create+ 1272908 (realm::Replication&, realm::DBOptions) + 288
16  Realm                         	0x0000000106297730 realm::_impl::RealmCoordinator::open_db+ 3602224 () + 884
17  Realm                         	0x00000001062966e4 realm::_impl::RealmCoordinator::do_get_realm+ 3598052 (realm::Realm::Config, std::__1::shared_ptr<realm::Realm>&, realm::util::Optional<realm::VersionID>, realm::util::CheckedUniqueLock&) + 68
18  Realm                         	0x000000010629650c realm::_impl::RealmCoordinator::get_realm+ 3597580 (realm::Realm::Config, realm::util::Optional<realm::VersionID>) + 400
19  Realm                         	0x0000000106304978 realm::Realm::get_shared_realm+ 4049272 (realm::Realm::Config) + 120
20  Realm                         	0x0000000105ff9890 +[RLMRealm realmWithConfiguration:queue:error:] + 858256 (RLMRealm.mm:441)
21  RealmSwift                    	0x00000001065dbab8 Realm.init(queue:) + 244408 (Realm.swift:76)

## Version of Realm and Tooling

Realm framework version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by jsflax** [comment]
@finnschiermer @jedelbo  can't say I've seen the top of this stack trace before– looks like an upgrade issue? Any thoughts?

**Comment by jedelbo** [comment]
Could this be due to memory exhaustion? Seems like the exception comes from within malloc?

**Comment by jsflax** [comment]
@raghunrmediacorp is this a particularly large Realm, or is the device low on memory?
