### ISSUE TITLE
"Called realm::util::terminate() with wrong number of arguments")

### ISSUE THREAD

**Issue by ashwaniInsigma** [realm/realm-cocoa#7280]
Hi,

I am using RealmSwift (10.7.6):
   
I have faced this during write operation to add new realm object

 static_assert(sizeof...(infos) == 2 || sizeof...(infos) == 4 || sizeof...(infos) == 6,
                  "Called realm::util::terminate() with wrong number of arguments");
    terminate(message, file, line, {Printable(infos)...});

**Comment by jsflax** [comment]
Hey @ashwaniInsigma , do you have any sample code you can show us that triggered this error? Not a very useful stack trace, I know, but more info could help us here.
