### ISSUE TITLE
Realm Studio Version 11.0.0-beta.1 not compatible with Realm v10.8.0-beta.2

### ISSUE THREAD

**Issue by ravikirankhareedi** [realm/realm-cocoa#7281]
## Goals
Browse the realm database generated using Realm v10.8.0-beta.2.  

## Expected Results
As per the doc, Realm Studio Version 11.0.0-beta.1 should be compatible. 

## Actual Results
Opening Realm files of format version 22 is not supported by this version of Realm

## Steps for others to Reproduce
Use Realm v10.8.0-beta.2 with a swift application. Make use of the new feature, AnyRealmValue. Write to the DB. Try opening the file with the above mentioned version of Realm Studio.  

## Code Sample
NA

## Version of Realm and Tooling
Realm v10.8.0-beta.2
Realm Studio Version 11.0.0-beta.1

Xcode version: ?
Version 12.5

iOS/OSX version: ?
11.1

**Comment by dianaafanador3** [comment]
HI @ravikirankhareedi You can report this on the realm studio repository page https://github.com/realm/realm-studio/issues, This will take you directly to the people taking care of this.
