### ISSUE TITLE
No type named 'ListBase' in module 'RealmSwift'

### ISSUE THREAD

**Issue by waleednour** [realm/realm-cocoa#7288]
when update pods for last version 10.8.0
we receive this error

 No type named 'ListBase' in module 'RealmSwift'

in this function

```
    private func resolve(element: Object, toBeDeleted: inout Set<RLMObjectBase>) {
        element.objectSchema.properties.forEach {
            guard let value = element.value(forKey: $0.name) else { return }
            if let entity = value as? RLMObjectBase {
                toBeDeleted.insert(entity)
            } else if let list = value as? RealmSwift.ListBase {
                for index in 0 ..< list._rlmArray.count {
                    if let realmObject = list._rlmArray.object(at: index) as? RLMObjectBase {
                        toBeDeleted.insert(realmObject)
                    }
                }
            }
        }
        delete(element)
    }
```

**Comment by dianaafanador3** [comment]
Hi @waleednour Thanks for sharing this issue. Are you using Cocoapods or SPM?, Which version of Xcode are you using?, Which OS version are you testing on?, this help us try to reproduce the issue. 
If you are using Cocoapods, please clean derived data and try to make a clean install of the pods.

**Comment by waleednour** [comment]
> Hi @waleednour Thanks for sharing this issue. Are you using Cocoapods or SPM?, Which version of Xcode are you using?, Which OS version are you testing on?, this help us try to reproduce the issue.
> If you are using Cocoapods, please clean derived data and try to make a clean install of the pods.

Cocoapods
Xcode 12.5
OS version  14.6
i  tried that

**Comment by tgoyne** [comment]
Your code is not using Realm's public API, and is instead relying on implementation details which have changed. The proper way to write this function would be:

```
    private func resolve(element: Object, toBeDeleted: inout Set<RLMObjectBase>) {
        element.objectSchema.properties.forEach {
            guard $0.type == .object else { return }
            if $0.isArray {
                for object in element.dynamicList($0.name) {
                    toBeDeleted.insert(object)
                }
            } else if let value = element[$0.name] as? ObjectBase {
                toBeDeleted.insert(value)
            }
        }
        delete(element)
    }
```

(Not tested, may have typos and such)

**Comment by dianaafanador3** [comment]
HI @waleednour, the above code has worked?

**Comment by waleednour** [comment]
Thanks, 
it worked

**Comment by dianaafanador3** [comment]
Closing this as it was resolved by @tgoyne comment
