### ISSUE TITLE
Rename SwiftPM target "Core" to "RealmCore"

### ISSUE THREAD

**Issue by GreaseMonk** [realm/realm-cocoa#7290]
## Goals
Rename the swiftPM product name "Core" to "RealmCore"

## Expected Results
I have a local swift package named "Core" in which I kept all of my APIs and my repositories for the frontend to use. 
After updating to the latest version of Realm through swift package manager, I got the error "multiple targets named Core in: Core, RealmDatabase". 
after checking the package.swift, I soon realized I had to rename my own swift package in order to continue using realm. 

Maybe I should have seen this coming with an obtuse and non-specific name like "Core" , but I felt the need to report it here because I think the product name "Core" in the "RealmDatabase" package is not specific enough to be related to Realm.

<img width="604" alt="Screenshot 2021-06-16 at 13 38 32 (1)" src="https://user-images.githubusercontent.com/1354802/122214491-6e95b800-ceaa-11eb-9728-583cd1c1f193.png">

**Comment by dianaafanador3** [comment]
Hi @GreaseMonk thanks for reporting this, this is already been mentioned on this issue https://github.com/realm/realm-cocoa/issues/7289 and there is a ticket in core for this change, you can follow the progress of this ticket here https://github.com/realm/realm-core/issues/4763

**Comment by GreaseMonk** [comment]
Oops, thank you. I searched for "Core" in the issues, but not in the closed ones. thank you

**Comment by dianaafanador3** [comment]
Issue has been fixed on realm-core repository https://github.com/realm/realm-core/issues/4763, probably will be released on next version
