### ISSUE TITLE
Bad Changeset - incorrect partition value but doesn't make sense

### ISSUE THREAD

**Issue by EcoChampions** [realm/realm-cocoa#7292]
## Goals

I'm trying to write to a realm and as part of my test am hard coding the partition value (a required field in my schema)
## Expected Results

I expected to get a new record in Atlas.  Instead I get a new entry on the device but it is not syncing to Atlas
## Actual Results

Error:

failed to validate upload changesets: SET instruction had incorrect partition value for key "partition" { expectedPartition: {team=BC21BE45-E402-4DC7-A85E-142DEAABDC19}, foundPartition: {team=BC21BE45-E402-4DC7-A85E-142DEAABDC19} } (ProtocolErrorCode=212)

## Code Sample

```
func writeActivityData(locationName: String) {
        let teampartitionValue = "team=BC21BE45-E402-4DC7-A85E-142DEAABDC19"
        let user = app.currentUser!
        
        let activity = ActivityMessage()
        
        activity.text = locationName
        activity.partition = "{team=BC21BE45-E402-4DC7-A85E-142DEAABDC19}"
        activity.timestamp = Date()
        activity.points = 50

        Realm.asyncOpen(configuration: (user.configuration(partitionValue: teampartitionValue))) { [self] result in
        switch result {
                    case .failure(let error):
                        print("Failed to open realm: \(error.localizedDescription)")
                        // handle error
                    case .success(let realm):
                        print("writeActivivityData routine:  Successfully opened realm for useractivity: \(realm)")
                        // Use realm
                        
                        try! realm.write {
                            realm.add(activity)
                            
                        }
                        
                        }
                    }
             }
```

## Version of Realm and Tooling

Realm framework version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by nirinchev** [comment]
Looks like `teampartitionValue` is set to `team=BC21BE45-E402-4DC7-A85E-142DEAABDC19` while `activity.partition` is `{team=BC21BE45-E402-4DC7-A85E-142DEAABDC19}` - i.e. the same, but with curly braces around it. You should either make them identical or just remove `activity.partition` from your model altogether and have the server populate it (if you don't set it, the server will automatically set to the partition of the Realm instance).

**Comment by nirinchev** [comment]
Regarding the log message - I agree it's confusing and we filed a ticket for the cloud team to fix the formatting. Closing this now, but feel free to reopen if you need more help.

**Comment by EcoChampions** [comment]
Thanks @nirinchev I tried with and without the brackets based on the log message but this didn't make any difference.  I've now removed activity.partition but it now states 

Error:

Ending session with error: failed to validate upload changesets: SET instruction had incorrect partition value for key "partition" { expectedPartition: {team=BC21BE45-E402-4DC7-A85E-142DEAABDC19}, foundPartition: } (ProtocolErrorCode=212)

**Comment by EcoChampions** [comment]
Given I'm using partition for sync, the schema is forcing me to make partition a required field?

**Comment by nirinchev** [comment]
Regarding the brackets - can you confirm that if you modify your code to set `activity.partition = teampartitionValue` (i.e. ensure that they're identical), you get the same error? Also, remember to wipe your local state as it's possible that your simulator is still trying to upload the original changeset that contained the bracket mismatch.

Regarding removing `activity.partition` - you should be able to delete the field from your model - I'm guessing when you got the empty string error, you only removed the line which sets `activity.partition = ...` rather than the field altogether.

**Comment by EcoChampions** [comment]
thanks @nirinchev setting activity.partition = teampartitionValue works.  Interesting given I had previously defined them by copy pasting the id into each!

**Comment by nirinchev** [comment]
Great - I'm glad to hear you've got it working now and we will most definitely address the confusing log messages!
