### ISSUE TITLE
Spurious Build Warnings in Xcode 13

### ISSUE THREAD

**Issue by bdkjones** [realm/realm-cocoa#7295]
## Goals

Using Realm in Xcode 13 results in several build warnings, as shown in this screenshot:
![Screen Shot 2021-06-17 at 11 53 34](https://user-images.githubusercontent.com/926566/122456925-f212e000-cf62-11eb-9fa6-8df252e523f7.png)

## Expected Results

These warnings should not appear. 

The build runs correctly, but the extra 6 warnings pollute the project and make it harder to see when ACTUAL issues are happening.

## Actual Results

These warnings appear in Xcode 13 but NOT in Xcode 12.5.

## Steps for others to Reproduce

1. Install Realm via Swift Package Manager
2. Import `Realm` and `RealmSwift` into a file and build the project.

## Attempted Fixes

I have tried clearing the Package cache and re-installing the packages. No difference.
As far as I can see, there's no way for me to configure them in a way that would remove these warnings?

## Version of Realm and Tooling

Realm framework version: 10.7.7

Xcode version: 13.0 Beta 1

iOS/OSX version: macOS 11.4

Dependency manager + version: Swift Package Manager

**Comment by tgoyne** [comment]
Newer versions of SPM have the wonderful behavior where it warns if there's any files not explicitly excluded and also warns if there's any excluded files which don't exist, which AFAICT make it impossible to always build without warnings if there's files which conditionally exist. I guess we should probably prioritize building without warnings when the package is being installed over having no warnings when we're developing it.

**Comment by bdkjones** [comment]
> I guess we should probably prioritize building without warnings when the package is being installed over having no warnings when we're developing it.

That seems right. It doesn't look good to have the "caution sign" icon next to `Realm` and `RealmDatabase` in Xcode's sidebar, leading you to believe there's something wrong with the packages.

I looked for a flag to disable that specific warning, but was not able to find one.

**Comment by nacho4d** [comment]
Using Xcode13 beta1 and I am having the same problem. 

My project is quite big and Realm is the one that shows a warning. I don't know if a warning in one package could be affecting others (Xcode bug?) but so far all others SPM packages I have do not work at all. Maybe this is helpful to Realm team to prioritize on this. 

<img width="864" alt="Screen Shot 2021-06-21 at 18 14 44" src="https://user-images.githubusercontent.com/111651/122739235-c161dc00-d2bd-11eb-9934-0c0d4529d059.png">
