### ISSUE TITLE
List<T> and Results<T> should support access by IndexSet

### ISSUE THREAD

**Issue by bdkjones** [realm/realm-cocoa#7298]
## Goals
Swift's `Array` type offers an API to return all indexes in a given `IndexSet`: 

    let objects: [Any] = someArray.objects(at: someIndexSet)

Currently, Realm's collection types do not support this API. This is inconvenient because `NSTableView` extensively uses `IndexSet`. If I want to translate the selected rows in the table to an Array of objects on which I can act, I can't just pass the `IndexSet` returned by `selectedRowIndexes` to the Realm collection. Instead, I must manually loop through the indexes.

Additionally, because `IndexSet` is heavily optimized for its task, I assume the `objects(at:)` API is more performant than the naive for-loop approach.

## Expected Results

Realm collection types should support accessing objects by `IndexSet`.

## Actual Results

Realm collection types do not support `IndexSet`.

## Steps for others to Reproduce

N/A

## Code Sample

N/A

## Version of Realm and Tooling

Realm framework version: 10.7.2

Xcode version: 13.0 Beta 1

iOS/OSX version: macOS 11.4

Dependency manager + version: SPM

**Comment by tgoyne** [comment]
There isn't really much room for us to do anything significantly faster; skipping some redundant checks might make it 5-10% faster but there isn't a lot of unnecessary overhead to begin with. A convenience helper would be easy to add, though.

**Comment by bdkjones** [comment]
The convenience method would make interfacing with NSTableView much nicer, for sure.
