### ISSUE TITLE
This is not a valid Dash or Xcode docset feed. Realm Swift v10.8.0

### ISSUE THREAD

**Issue by jessehao** [realm/realm-cocoa#7299]
Cannot install docs to Dash(v6.0.6 978).

<img width="529" alt="image" src="https://user-images.githubusercontent.com/5467890/122634681-27a9fb80-d112-11eb-85f1-141d95c2f861.png">

I've tried 6 version of realm doc below, only 10.5.0 works.
- https://realm.io/docs/swift/10.8.0/api/docsets/RealmSwift.xml ❌
- https://realm.io/docs/swift/10.7.7/api/docsets/RealmSwift.xml ❌
- https://realm.io/docs/swift/10.7.2/api/docsets/RealmSwift.xml ❌
- https://realm.io/docs/swift/10.7.0/api/docsets/RealmSwift.xml ❌
- https://realm.io/docs/swift/10.6.0/api/docsets/RealmSwift.xml ❌
- https://realm.io/docs/swift/10.5.0/api/docsets/RealmSwift.xml ✅

When I open the [link](https://realm.io/docs/swift/10.8.0/api/docsets/RealmSwift.xml) in web browser, it shows 403 forbidden.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/5467890/122634789-fe3d9f80-d112-11eb-80b1-297e58f7b9ba.png">

**Comment by tgoyne** [comment]
It's now published at https://docs.mongodb.com/realm-sdks/swift/10.8.0/docsets/RealmSwift.xml, but it looks like we never updated the link to the new location.
