### ISSUE TITLE
Opening Realm files of format version 22 is not supported by this version of Realm

### ISSUE THREAD

**Issue by dlsolution** [realm/realm-cocoa#7304]
I use the MongoDB Realm Studio v.10.1.2
Realm v10.8.0

**Comment by dlsolution** [comment]
Update: I downgraded Realm v10.7.0 with no issue!!

**Comment by leemaguire** [comment]
We have yet to release a version of studio that supports this version of Realm Cocoa

**Comment by jun784lr** [comment]
> Update: I downgraded Realm v10.7.0 with no issue!!

If your Realm files are already upgraded and your Realm Studio application is not, you won't be able to view your Realm files until they release a newer version of Realm Studio application. So watch out for that.

**Comment by ianpward** [comment]
Realm Studio v11 has been released with support for file format v22 - 
https://studio-releases.realm.io/v11.0.0

**Comment by jun784lr** [comment]
Installing the Zip archive version for MacOS gave me this error: 
<img width="268" alt="Screen Shot 2021-06-25 at 6 37 45 PM" src="https://user-images.githubusercontent.com/69073108/123405400-bf14c000-d5e4-11eb-90ab-85371d704107.png">

But installing with MacOS (Apple Disk Image) worked without a problem.
