### ISSUE TITLE
Opening Realm files of format version 22 is not supported by this version of Realm

### ISSUE THREAD

**Issue by mxnmike** [realm/realm-cocoa#7308]
!!! MANDATORY TO FILL OUT !!!
RealmSwift doesn't work. When trying to open default.realm through Realm Studio, an error appears:
Opening Realm files of format version 22 is not supported by this version of Realm.

**Comment by ianpward** [comment]
Realm Studio v11 has been released with support for file format v22 - 
https://studio-releases.realm.io/v11.0.0

**Comment by nrj** [comment]
FWIW - version of Realm Studio 10.1.12 is currently reporting that it is the latest version.
