### ISSUE TITLE
Unable to open a realm at path ''. Realm file initial open failed: Realm file has bad size (163)

### ISSUE THREAD

**Issue by arthur-stpnv** [realm/realm-cocoa#7309]
## Problem

I'm trying to load realm from file that is stored in iCloud (was uploaded from another device with same iCloud) and got this error:

Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/0ADE8CA2-8518-4232-92A3-080A94D527A1/Documents/default.realm': Realm file initial open failed: Realm file has bad size (163)

If I try the same logic on device from which realm file was uploaded - no crash happens.

## Code Sample

```
let config = Realm.Configuration(schemaVersion: Constants.shared.realmVersion)
Realm.Configuration.defaultConfiguration = config
loadRealmFromCloud(realmUrl: config.fileURL)
```

```
func loadRealmFromCloud(realmUrl: URL?) {
        guard let defaultRealmUrl = realmUrl,
              let cloudRealmUrl = getCloudRealmFileUrl(type: .download),
              FileManager.default.fileExists(atPath: cloudRealmUrl.path) else { return }
        
        if FileManager.default.fileExists(atPath: defaultRealmUrl.path) {
            try? FileManager.default.removeItem(at: defaultRealmUrl)
        }
        
        try? FileManager.default.copyItem(atPath: cloudRealmUrl.path, toPath: defaultRealmUrl.path)
}
```

```
private func getCloudRealmFileUrl(type: CloudRealmUrlType) -> URL? {
        guard let cloudUrl = FileManager.default.url(forUbiquityContainerIdentifier: nil)?
              .appendingPathComponent("Documents", isDirectory: true) else { return nil }
        
        if type == .download {
            return cloudUrl.appendingPathComponent(".default.realm.icloud", isDirectory: false)
        }
        
        return cloudUrl.appendingPathComponent("default.realm", isDirectory: false)
}
```

I got error on calling `let realm = try! Realm()` right after all stuff above.

File was saved to iCloud this way:

```
func uploadRealmToCloud() {
        guard let cloudRealmUrl = getCloudRealmFileUrl(type: .upload) else { return }
        
        createDirectoryIfNeeded()
        
        if FileManager.default.fileExists(atPath: cloudRealmUrl.path) {
            try? FileManager.default.removeItem(at: cloudRealmUrl)
        }
        
        let realm = try! Realm()
        try! realm.writeCopy(toFile: cloudRealmUrl)
}
```

```
private func createDirectoryIfNeeded() {
        guard let documentsUrl = FileManager.default.url(forUbiquityContainerIdentifier: nil)?
              .appendingPathComponent("Documents", isDirectory: true) else { return }
        
        var isDirectory: ObjCBool = true
        if FileManager.default.fileExists(atPath: documentsUrl.path, isDirectory: &isDirectory) { return }
        try? FileManager.default.createDirectory(atPath: documentsUrl.path, withIntermediateDirectories: true, attributes: nil)
}
```

## Version of Realm and Tooling

Realm framework version: 10.7.6

Xcode version: 12.5 (12E262)

iOS version: 14.5

Dependency manager + version: CocoaPods 1.10.1

**Comment by leemaguire** [comment]
Hi @arthur-stpnv What model device uploaded the Realm file and what model device is trying to read the Realm file?

**Comment by arthur-stpnv** [comment]
@leemaguire hi, uploaded from iPhone 11 Pro Max, trying to read from iPad Pro (3rd generation)

**Comment by arthur-stpnv** [comment]
Hey, any updates?

**Comment by ericjordanmossman** [comment]
I just read over this. Not completely sure yet.
@leemaguire - what about the different device types would read the file differently, potentially?

**Comment by tgoyne** [comment]
This error message indicates that the thing you're trying to open is either not a Realm file at all, or is a truncated prefix of a Realm file. As you appear to be downloading the file, obvious explanations would be that it's actually an error page, the download did not complete, or whatever is on the server is invalid.

**Comment by arthur-stpnv** [comment]
@tgoyne Hi, thank you for answer, but if I download the file on device from which it was uploaded - there is no error, so we can be sure that file was uploaded correctly and that this file is Realm file

**Comment by arthur-stpnv** [comment]
I’ve found two more files in Realm local directory - realm.manager and realm.lock, maybe I should upload them too?

**Comment by arthur-stpnv** [comment]
Maybe there is better way to make realm copy?

**Comment by arthur-stpnv** [comment]
Or maybe you could advice some logic to sync realms between 2 iOS devices?

**Comment by arthur-stpnv** [comment]
@tgoyne @leemaguire @ericjordanmossman @tonyarnold guys, any updates?

**Comment by leemaguire** [comment]
Hi @arthur-stpnv Can you confirm that the uploaded Realm file can be opened with Realm Studio? Maybe the corruption is happening during upload to iCloud.

**Comment by arthur-stpnv** [comment]
I've end up with Realm Sync solution bu Mongo DB

**Comment by 342261733** [comment]
> I've end up with Realm Sync solution by Mongo DB

Can you talk about the detail ?
