### ISSUE TITLE
 Multiple Realm switch write crash

### ISSUE THREAD

**Issue by ChenShengZhe** [realm/realm-cocoa#7311]
## Goals
I want to modify the Object object in the write transaction 

## Expected Results
data changed 

## Actual Results
app crashed , reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'

## Steps for others to Reproduce
I used the user account to create two realms for the distinction. When I did a write transaction in the first realm, everything was normal. At this time, I switched the user account and crashed when I tried the write operation using the second realm.reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.' 

## Code Sample
init realm（will swich realm when i login diffrent account） :
  ```swift
func configDB(userAccount:String){
        userAccount.forEach { (realmDBType) in
            let dbPath = docPath.appending("/\(userAccount).realm")
            let config = Realm.Configuration(
                fileURL: URL.init(string: dbPath),
                inMemoryIdentifier: nil,
                syncConfiguration: nil,
                encryptionKey: nil,
                readOnly: false,
                schemaVersion: dbVersion,
                migrationBlock: { (migration, oldSchemaVersion) in
                },
                deleteRealmIfMigrationNeeded: false,
                shouldCompactOnLaunch: nil,
                objectTypes: nil)
            Realm.Configuration.defaultConfiguration = config
            Realm.asyncOpen { (result) in
                switch result{
                case .success(_) :
                    print("init realm success \(docPath)")
                case .failure(let err):
                    print(err)
                }
            }
        }
    }
```

try to write:

 ```swift
try? realm.write {
                realmModel.content = string.toJSONString()
                realmModel.time = 1000
                }
```

## Version of Realm and Tooling

Realm framework version: Realm-swift 10.1.4

Xcode version: 12.5

iOS/OSX version: 14.2

**Comment by ChenShengZhe** [comment]
The strange thing is that if I continue to use the first Realm, the error will not occur

**Comment by leemaguire** [comment]
Hi @ChenShengZhe you need to make sure that the `realmModel` you are trying to modify belongs to the `realm` that is invoking the write transaction block

**Comment by ChenShengZhe** [comment]
> 嗨@ChenShengZhe您需要确保`realmModel`您尝试修改的属于`realm`正在调用写入事务块的


I can confirm that the realmModel belongs to the current Realm, and it comes from the Realm's Results：
```swift
let result = realm.objects(ChatMessageEntity.self).filter("fromId = \(userInfo?.id ?? -1) AND roomJid = '\(muc)'")
realmModel = result[0]
```

**Comment by leemaguire** [comment]
When you are switching to your second realm, you will need to retrieve the result again, if you do not do this the results still belong to the initial realm. Maybe this is the problem you are seeing?

**Comment by ChenShengZhe** [comment]
u r right，I found the problem, but I can’t solve it because when I initialized the results, the log I printed showed that the data in it belonged to the realm of the current account, but when I fetched the data from the results, it gave me an error. The data belonging to this library, I suspect it has something to do with swift's data recovery, because deinit was not executed, resulting in the results not being recovered, so that there was a problem when I assigned the value again.
