### ISSUE TITLE
Realm notification listeners hijacks CPU (app freeze)

### ISSUE THREAD

**Issue by jonashinge** [realm/realm-cocoa#7316]
## Goals
No app freeze when using realm notification listeners.

## Expected Results
App freeze for several seconds when interacting with realm objects that has a notification listener attached (> minute(s) in some cases).

## Actual Results
We are experiencing that our app is freezing in some cases when using realm notification listeners. This is especially happening for users that have a lot of data in realm. It started happening in some realm version after 10.5.1. We tried upgrading to newest realm version 10.8.1 without any luck. Analysing threads using Instruments shows that a Realm notification listener thread is taking up 100% CPU for an extensive amount of time (see screenshot).

<img width="1250" alt="Screenshot 2021-06-30 at 10 45 22" src="https://user-images.githubusercontent.com/1147758/123932812-183c7500-d992-11eb-9ebf-f4c538039eb5.png">

## Version of Realm and Tooling

Realm framework version: Any version above 10.5.1

Xcode version: 12.5

iOS/OSX version: 14.5

Dependency manager + version: CocoaPods 1.10.1

**Comment by ericjordanmossman** [comment]
So versions earlier than 10.5.1 were _not_  having this problem? 
I was thinking [that this](https://github.com/realm/realm-cocoa/pull/7249) might help, depending on the objects being observed. But if the same code was working prior to 10.5.1, then I wonder if something changed in the DeepChangeChecker.

**Comment by jonashinge** [comment]
Thanks @ericjordanmossman. Key path filtering looks promising! However I think something changed in the DeepChangeChecker because we were not having this problem in 10.5.1. After we upgraded from 10.5.1 to 10.7.6 the freeze issues started.

**Comment by weibel** [comment]
I'm a collegue to @jonashinge above. Our case seems very similar to the one described in this issue https://github.com/realm/realm-cocoa/issues/7072
Except in our case a person would have 10.000 dogs.

**Comment by tgoyne** [comment]
There were a lot of changes to this code between v10.5.1 and v10.8.1 to add support for the new data types, but nothing that should have meaningfully impacted the performance when using the existing types. With v10.5.1 are you seeing the worker thread using negligible CPU, or is it using a decent amount and just not enough to be a problem? If it's the latter then a small loss in performance might've just pushed it over some important threshold, while if it's the former then it suggests we accidentally made a change which made the asymptotic performance worse. The performance of this code is unfortunately so schema and use-case specific that it's hard to do good performance testing for it.

**Comment by weibel** [comment]
After digging into it I have decided to look closer into this commit on the DeepChangeChecker. 
https://github.com/realm/realm-core/commit/36439bc1702ac4886fffd264b28ed6de647ec96d#diff-8742ebffe87d6dea5ac92a6c9a13348aa394055aaf75e256e5fbe48c319899ca
It's the one change that stands out between the current version and the one that still works for us
For reference: The last version that still works for us https://github.com/realm/realm-core/blob/0b1f8aae0573f0c15d9c684f226c583705fe1c4c/src/realm/object-store/impl/collection_notifier.cpp
Current version https://github.com/realm/realm-core/blob/affc0982e23caf868ad1bd086d7288b511663d70/src/realm/object-store/impl/deep_change_checker.cpp

**Comment by jonashinge** [comment]
> There were a lot of changes to this code between v10.5.1 and v10.8.1 to add support for the new data types, but nothing that should have meaningfully impacted the performance when using the existing types. With v10.5.1 are you seeing the worker thread using negligible CPU, or is it using a decent amount and just not enough to be a problem? If it's the latter then a small loss in performance might've just pushed it over some important threshold, while if it's the former then it suggests we accidentally made a change which made the asymptotic performance worse. The performance of this code is unfortunately so schema and use-case specific that it's hard to do good performance testing for it.

In v10.5.1 we see the thread having short spikes reaching ~max CPU so it's not a problem as the time used in the spikes are so short. In v10.7.6 the thread stays on ~max CPU up to 1 minute.

Our scenario is that as soon as we have attached a notification listener on a realm object x and start writing to objects that are related to that object x, the thread gets stuck. This is why we assume/guess that the deep change checking has become too aggressive.

I tried to revert the suggested change mentioned by @weibel above but it still freezes up.
As this is a critical issue for us we're now forced to remove notification listeners as a workaround.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-core/pull/4816 may improve things for you.

**Comment by dianaafanador3** [comment]
Closing this as there is no response from the user and realm/realm-core#4816 may help improving issue with notification listeners. If you keep having issue we will reopen the issue.
