### ISSUE TITLE
manu errors after RealSwift version 10.8.0 and 10.9.0

### ISSUE THREAD

**Issue by vishaldroisys** [realm/realm-cocoa#7319]
!!! MANDATORY TO FILL OUT !!!

## Goals

we need to upgrade RealmSwift sdk.

## Expected Results

we need to upgrade version.

## Version of Realm and Tooling

Realm framework version: ?
10.9.0

Xcode version: ?
12.4

iOS/OSX version: ?
iOS 14

Dependency manager + version: ?
Pod 1.10.1

**Comment by ericjordanmossman** [comment]
If you have questions about how to use Realm, ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), or in our [Swift Forum](https://forums.realm.io/c/swift).
If you're reporting a potential bug, please fill in the details of the issue template.

**Comment by vishaldroisys** [comment]
HI @ericjordanmossman,

there is not any functional bug, please see screenshot: https://drive.google.com/file/d/1-4HqczbbvIEmz5NWyusvvf4sOVpS1byU/view?usp=sharing

**Comment by vishaldroisys** [comment]
@ericjordanmossman issue has been resolved.

referenced from below URL: https://stackoverflow.com/questions/68013781/reference-to-generic-type-map-requires-arguments-in-swift
