### ISSUE TITLE
Crash in Core get_version_and_history_info() when opening a realm

### ISSUE THREAD

**Issue by lfb-cd** [realm/realm-cocoa#7322]
0   足迹                              0x0000000102e0c5c4 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 44
1   足迹                              0x0000000102e0c814 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 388
2   足迹                              0x0000000102ec2a24 _ZN5realm5Group28get_version_and_history_infoERKNS_5ArrayERyRiS5_ + 316
3   足迹                              0x0000000102ebde04 _ZN5realm11SharedGroup7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_18SharedGroupOptionsE + 2056
4   足迹                              0x0000000102d848a8 _ZN5realm11SharedGroup4openERNS_11ReplicationENS_18SharedGroupOptionsE + 180
5   足迹                              0x0000000102d845a8 _ZN5realm11SharedGroupC2ERNS_11ReplicationENS_18SharedGroupOptionsE + 752
6   足迹                              0x0000000102d7ed3c _ZN5realm5Realm16open_with_configERKNS0_6ConfigERNSt3__110unique_ptrINS_11ReplicationENS4_14default_deleteIS6_EEEERNS5_INS_11SharedGroupENS7_ISB_EEEERNS5_INS_5GroupENS7_ISF_EEEEPS0_ + 736
7   足迹                              0x0000000102d7e878 _ZN5realm5RealmC2ENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEE + 204
8   足迹                              0x0000000102cdb3c0 _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerC2ES1_S6_ + 88
9   足迹                              0x0000000102cdb170 _ZNSt3__110shared_ptrIZN5realm5Realm17make_shared_realmENS2_6ConfigENS0_INS1_5_impl16RealmCoordinatorEEEE19make_shared_enablerE11make_sharedIJS3_S6_EEES8_DpOT_ + 136
10  足迹                              0x0000000102cd79c8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 400
11  足迹                              0x0000000102d800b8 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 112
12  足迹                              0x0000000102d6d3b0 +[RLMRealm realmWithConfiguration:error:] + 600
13  足迹                              0x0000000102d6c988 +[RLMRealm defaultRealm] + 76
14  足迹                              0x0000000102133198 +[RealmModeManager setDefaultRLMConfig] + 468
15  足迹                              0x0000000102133514 +[RealmModeManager checkDefaultRLMConfig] + 116
16  足迹                              0x00000001021352f0 +[RealmModeManager queryTodayAllSteps] + 40
17  足迹                              0x00000001020692fc -[locationManager startLocation] + 1216
18  足迹                              0x000000010209e88c -[AppDelegate handApplicationState:] + 232
19  足迹                              0x00000001020956e0 -[AppDelegate application:didFinishLaunchingWithOptions:] + 764
20  CoreFoundation                      0x0000000182eca130 F3021642-E3C0-33F8-9911-DD303A6056D0 + 1175856
21  CoreFoundation                      0x0000000182dad1d0 F3021642-E3C0-33F8-9911-DD303A6056D0 + 8656
22  足迹                              0x0000000102230e80 -[BaiduMobStatDelegate mtjApplication:didFinishLaunchingWithOptions:] + 320
23  UIKitCore                           0x000000018572c8c0 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 11708608
24  UIKitCore                           0x000000018572e860 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 11716704
25  UIKitCore                           0x0000000185733f48 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 11738952
26  UIKitCore                           0x0000000184e09164 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 2126180
27  UIKitCore                           0x00000001853322b0 _UIScenePerformActionsWithLifecycleActionMask + 100
28  UIKitCore                           0x0000000184e09c4c CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 2128972
29  UIKitCore                           0x0000000184e09754 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 2127700
30  UIKitCore                           0x0000000184e09a78 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 2128504
31  UIKitCore                           0x0000000184e09334 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 2126644
32  UIKitCore                           0x0000000184e10fe0 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 2158560
33  UIKitCore                           0x000000018524b1c4 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 6590916
34  UIKitCore                           0x00000001853499d8 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 244
35  UIKitCore                           0x0000000184e10cd4 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 2157780
36  UIKitCore                           0x0000000184c4f9b8 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 317880
37  UIKitCore                           0x0000000184c4e458 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 312408
38  UIKitCore                           0x0000000184c4f604 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 316932
39  UIKitCore                           0x0000000185732120 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 11731232
40  UIKitCore                           0x0000000185271ab8 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 6748856
41  FrontBoardServices                  0x00000001921ef704 E42FBC3B-619C-32AB-A210-4A25F8B5373F + 38660
42  FrontBoardServices                  0x0000000192217130 E42FBC3B-619C-32AB-A210-4A25F8B5373F + 201008
43  FrontBoardServices                  0x00000001921fce60 E42FBC3B-619C-32AB-A210-4A25F8B5373F + 93792
44  FrontBoardServices                  0x0000000192216e44 E42FBC3B-619C-32AB-A210-4A25F8B5373F + 200260
45  libdispatch.dylib                   0x0000000106f7d528 _dispatch_client_callout + 16
46  libdispatch.dylib                   0x0000000106f809f0 _dispatch_block_invoke_direct + 232
47  FrontBoardServices                  0x000000019223be60 E42FBC3B-619C-32AB-A210-4A25F8B5373F + 351840
48  FrontBoardServices                  0x000000019223bb28 E42FBC3B-619C-32AB-A210-4A25F8B5373F + 351016
49  FrontBoardServices                  0x000000019223bffc E42FBC3B-619C-32AB-A210-4A25F8B5373F + 352252
50  CoreFoundation                      0x0000000182e45bf0 F3021642-E3C0-33F8-9911-DD303A6056D0 + 633840
51  CoreFoundation                      0x0000000182e45af0 F3021642-E3C0-33F8-9911-DD303A6056D0 + 633584
52  CoreFoundation                      0x0000000182e44e38 F3021642-E3C0-33F8-9911-DD303A6056D0 + 630328
53  CoreFoundation                      0x0000000182e3f3e0 F3021642-E3C0-33F8-9911-DD303A6056D0 + 607200
54  CoreFoundation                      0x0000000182e3eba0 CFRunLoopRunSpecific + 572
55  GraphicsServices                    0x0000000199ba7598 GSEventRunModal + 160
56  UIKitCore                           0x00000001857302f4 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 11723508
57  UIKitCore                           0x0000000185735874 UIApplicationMain + 164
58  足迹                              0x000000010217a550 main + 160
59  libdyld.dylib                       0x0000000182b1d568 0B475C78-3C12-3121-B7F8-2B95B83DAF44 + 5480
IMPORTANT: if you see this error, please send this log to help@realm.io.

**Comment by pavel-ship-it** [comment]
@lfb-cd If you're reporting a potential bug, please fill in the details of the issue template.

**Comment by lfb-cd** [comment]
> @lfb-cd If you're reporting a potential bug, please fill in the details of the issue template.

Sorry, there are no more details. This error was reported Just during initialization. 

And this is the database：[default.realm.zip](https://github.com/realm/realm-cocoa/files/6775199/default.realm.zip)

**Comment by pavel-ship-it** [comment]
@lfb-cd no worries,
What is the framework version you're using? is it appears on a real device or in simulator?

**Comment by lfb-cd** [comment]
> @lfb-cd no worries,
> What is the framework version you're using? is it appears on a real device or in simulator?

I findout the version is 2.5.0. It`s a old version? it appears on a real device. is there any way to fix this database ?

**Comment by pavel-ship-it** [comment]
yes, it's an old version. Could you please try the latest version?

**Comment by lfb-cd** [comment]
> yes, it's an old version. Could you please try the latest version?

ok, i will try it. How about the data of this database? is there any way to recycle the data?

**Comment by pavel-ship-it** [comment]
@lfb-cd you should be able to access all the data after migration on the newer version.
Can you tell me please about your progress with this issue?
