### ISSUE TITLE
[RealmSwift] Using `Map` properties in a predicate does not work as expected

### ISSUE THREAD

**Issue by lukaskollmer** [realm/realm-cocoa#7324]
## Goals

I want to filter a `Results` collection based on the string value of a specific key in a `Map` property on that class
I'm trying to create a predicate that lets me do that, but realm doesn't seem to support these kinds of predicates.

## Expected Results
It should be possible to use predicates to filter based on a `Map` property's key-value pairs.

## Actual Results
Realm throws an exception, saying that the `objectFrom:withIndex:` (which is what NSPredicate (or, rather, NSExpression) uses to implement the `map['intKey']` part of the predicate) is not supported by realm.

I get that it probably would not be possible for realm to support map predicates for dynamic (i.e. non-constant) keys, but IMO it should be possible to use this kind of syntax in cases where the key into the map is a static string constant.

## Steps for others to Reproduce
Run the second code sample below.

## Code Sample

The default NSPredicate+NSDictionary behaviour (this works fine, and is what I'm using as reference here):
```swift
class TestClassObjC: NSObject {
    @objc let map: NSDictionary
    
    init(intValue: Int) {
        self.map = ["intKey": intValue]
        super.init()
    }
}

let objects: NSArray = [
    TestClassObjC(intValue: 0),
    TestClassObjC(intValue: 1),
    TestClassObjC(intValue: 2)
]
let filtered = objects.filtered(using: NSPredicate(format: "map['intKey'] == 0"))
precondition(filtered.count == 1 && (filtered[0] as! TestClassObjC) == (objects[0] as! TestClassObjC))
```

The NSPredicate+RealmSwift.Map behaviour:
We're using the exact same predicate in here, and since the class hierarchy is equivalent (class contains a dictionary-like property; we're filtering an array of instances of the class based on a value in the dict) i'd expect it to work the same way as the program above does.

```swift
class TestClassRealm: RealmSwift.Object {
    let map = Map<String, Int>()
    
    convenience init(intValue: Int) {
        self.init()
        self.map["intKey"] = intValue
    }
}


let realm = try! Realm()
let filtered = realm
    .objects(TestClass.self)
    .filter(NSPredicate(format: "map['intKey'] == 0")) // realm throws an exception bc it doesn't like the predicate
```

## Version of Realm and Tooling

- Realm framework version: 10.9.0
- Xcode version: 12.5.1 (12E507)
- iOS/OSX version: iOS 14.6
- Dependency manager + version: SPM, the version that comes with the above-mentioned Xcode release

**Comment by leemaguire** [comment]
You are using the wrong datatype, for objective-c `RLMDictionary` should be used in place of `NSDictionary`

**Comment by leemaguire** [comment]
This is a limitation with our query engine, use dot notation to achieve the desired query. [Example here](https://github.com/realm/realm-cocoa/blob/b0dbcebbf11b544b9559cb0d55b6ce6734ee06f1/Realm/Tests/QueryTests.m#L2033)

**Comment by lukaskollmer** [comment]
@leemaguire in the example you linked, `stringCol` is the name of another property, rather than a literal key into the map, right?

If i adjust my sample code to use the dot syntax instead, it still doesn't work, and realm throws an exception
> Property 'map' is not a link in object of type 'TestClassRealm'

```swift
class TestClassRealm: RealmSwift.Object {
    let map = Map<String, Int>()
    
    convenience init(intValue: Int) {
        self.init()
        self.map["intKey"] = intValue
    }
}


let filtered = realm
    .objects(TestClassRealm.self)
    .filter("map.intKey > 0") // raises an exception
```


Am i missing something here?

**Comment by leemaguire** [comment]
Hi @lukaskollmer sorry for the confusion. As the bracket syntax is not supported, here is a work around for your issue:

```
class TestClassRealm: Object {
    let map = Map<String, Int>()
}

func testFoo() {
        let realm = try! Realm()
        try! realm.write {
            realm.create(TestClassRealm.self, value: [["intKey": 1]])
            realm.create(TestClassRealm.self, value:  [["intKey": 2]])
            realm.create(TestClassRealm.self, value: [["intKey": 3]])
        }

        let filtered = realm.objects(TestClassRealm.self).filter("map.@allKeys == 'intKey' AND map.@allValues > 1")
        print(filtered)
    }
```

**Comment by lukaskollmer** [comment]
@leemaguire The snippet you posted simply checks whether the map's keys contain the specified string and whether the map's values contain the specified value, but it does not check whether the specified value is in fact associated with the specified key.

Example:
```swift
class TestClassRealm: RealmSwift.Object {
    let map = RealmSwift.Map<String, Int>()

    convenience init(intValue1: Int, intValue2: Int) {
        self.init()
        self.map["intKey1"] = intValue1
        self.map["intKey2"] = intValue2
    }
}


try! realm.write {
    realm.add(TestClassRealm(intValue1: 1, intValue2: 2))
}

let filtered = realm
    .objects(TestClassRealm.self)
    .filter("map.@allKeys == 'intKey1' AND map.@allValues == 2")
print("#filtered: \(filtered.count)") // <-- this prints '1', should be '0' if the predicate was matching for only that specific key
```

Is there a reference somewhere listing the predicate types realm supports for maps?
Is it at all possible to write a query that filters based on the value associated with a specific key?

**Comment by leemaguire** [comment]
Hi @lukaskollmer 

We cannot currently query dictionaries specifying a key, and we should look into it and see if it's something we can achieve. It also looks like theres a bug in combining `@allKeys` and `@allValues` so we will need to look into that too. For the best reference on NSPredicates and Map the best place to look is our [query tests](https://github.com/realm/realm-cocoa/blob/8ea6e472fdc6df1dfd91fcfa54c930ee56efcb87/Realm/Tests/QueryTests.m#L3404).

Although not as efficient as using queries (or as pretty) I was able to achieve something with `value(forKeyPath:)`
```
        try! realm.write {
            realm.add(TestClassRealm(intValue1: 1, intValue2: 2))
            realm.add(TestClassRealm(intValue1: 3, intValue2: 4))
            realm.add(TestClassRealm(intValue1: 5, intValue2: 6))

        }

        let nilValue = (realm.objects(TestClassRealm.self).value(forKeyPath: "map.intKey3") as! [Int?])
            .filter { $0 != .none }
            .map { $0! }
            .filter { $0 > 2 }
        print("value: \(nilValue)") // nil

        let hasValue = (realm.objects(TestClassRealm.self).value(forKeyPath: "map.intKey2") as! [Int?])
            .filter { $0 != .none }
            .map { $0! }
            .filter { $0 > 2 }
        print("value: \(hasValue)") // [4, 6]
```
