### ISSUE TITLE
SortDescriptor' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by kaustabh-hcah** [realm/realm-cocoa#7334]
I've recently downloaded Xcode 13 beta 2 and it is throwing the error mentioned in the title. I've also imported RealmSwift already and it was working fine in Xcode 12.5.1. Is there any way to fix this issue at this moment?

Realm framework version: 10.10.0

Xcode version: 13 beta 2

iOS/OSX version: 15/Monterey

Dependency manager + version: CocoaPod 1.1.0

**Comment by pavel-ship-it** [comment]
Hi @kaustabh-hcah 
How did you archive this issue? I try to create a sample iOS project with RealmSwift added via Swift Package Manager and it seems working good. 
Could you please provide more info on the reproduction steps?

**Comment by kaustabh-hcah** [comment]
@pavel-ship-it  I've downloaded Xcode 13 beta 2 and ran the existing project that's it. Also, I'm using pod instead of SPM. It is working fine in Xcode 12.5.1.

**Comment by pavel-ship-it** [comment]
@kaustabh-hcah
I cannot reproduce with cocoa pods too.
Can you provide a crashlog or a stack trace?
In XCode you can type in console `p Thread.callStackSymbols.forEach{print($0)}` That could help me to understand what's going on.

**Comment by kaustabh-hcah** [comment]
@pavel-ship-it This error is coming in the Xcode editor in a line, where I used SortDescriptor. It is not allowing me to build. Build fails and Xcode editor throws this in red color.

**Comment by kaustabh-hcah** [comment]
@pavel-ship-it For your reference:

<img width="923" alt="Screenshot 2021-07-09 at 11 34 28 AM" src="https://user-images.githubusercontent.com/63723304/125031133-d0140580-e0a9-11eb-89ef-337828ff2a47.png">

**Comment by pavel-ship-it** [comment]
This is XCode beta issue. Meanwhile you can define it as 
```
        let descriptor: [RealmSwift.SortDescriptor] = ...
```
