### ISSUE TITLE
Crash:Trapped uncaught exception 'RLMException', reason: 'Missing value for property 

### ISSUE THREAD

**Issue by humoroutlaw** [realm/realm-cocoa#7341]
Trapped uncaught exception 'RLMException', reason: 'Missing value for property 'HomeListModelDB.hid'' 
     Procedure: I combine the other framework to my project while it crashed 100% under database operation,showing 'Missing value for property',when I remove that framework, everything goes fine.

## Version of Realm and Tooling

Realm framework version: ?
3.18.0
Xcode version: ?
12.0
iOS/OSX version: ?
iOS14.0.1

**Comment by humoroutlaw** [comment]
Procedure: I combine the other framework to my project while it crashed 100% under database operation,showing 'Missing value for property',when I remove that framework, everything goes fine.

**Comment by jsflax** [comment]
Hey @humoroutlaw , what is the other framework you are using? We need a good bit more information to help you with your query.

Do you have a code sample of/near the crash? What is "HomeListModelDB.hid"? What does your data model look like?

Also, notably, your version of Realm is fairly outdated. We're on 10.10 now.

**Comment by humoroutlaw** [comment]
@jsflax Thanks for your prompt reply! The framework is "MiCombo_APConnectFramework",It is a private one.

Sample codes as below;
+ (void)addHome:(HomeListModel*)home{
    HomeListModelDB *homedb = [[HomeListModelDB alloc] initWithDBModel:home];
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    [realm addOrUpdateObject:homedb];
    [realm commitWriteTransaction];
}

#import "HomeListModelDB.h"

@property (nonatomic, assign)NSInteger hid;
@property (nonatomic, assign)NSInteger userId;
@property (nonatomic,   copy)NSString  *homeName;
@property (nonatomic, assign)NSInteger createDate;
@property (nonatomic, assign)NSInteger status;
@property (nonatomic,   copy)NSString  *homeLocation;
@property (nonatomic, assign)NSInteger userType;
@property (nonatomic, assign)NSInteger homeCurrent;
@property (nonatomic, assign)NSInteger deviceCount;
@property (nonatomic, assign)NSInteger roomCount;
@property (nonatomic,   copy)NSString *homeWallpaper;
@property (nonatomic,   copy)NSString *secKey;
![crash](https://user-images.githubusercontent.com/17940371/125596129-153787f6-1dd4-4cc8-bdf8-c992de7eb079.jpg)


@implementation HomeListModelDB
+ (NSString *)primaryKey {
    return @"hid";
}
+ (NSString *)primaryKey {
    return @"hid";
}
- (instancetype)initWithDBModel:(HomeListModel*)dbmodel{
    if (self = [super init]) {
        _hid = dbmodel.hid;
        _userId = dbmodel.userId;
        _homeName = dbmodel.homeName;
        _createDate = dbmodel.createDate;
        _status = dbmodel.status;
        _homeLocation = dbmodel.homeLocation;
        _userType = dbmodel.userType;
        _homeCurrent = dbmodel.homeCurrent;
        _deviceCount = dbmodel.deviceCount;
        _roomCount = dbmodel.roomCount;
        _homeWallpaper = dbmodel.homeWallpaper;
        _secKey = dbmodel.secKey;
    }
    return self;
}

**Comment by humoroutlaw** [comment]
I have a demo crash visible, is it possible for me to send to you?
