### ISSUE TITLE
SyncManager.errorHandler not fired after read limit error

### ISSUE THREAD

**Issue by ksiwei** [realm/realm-cocoa#7343]
## Goals
Be able to handle the SyncError if the change set is too large e.g. by chunking the change set.

## Expected Results
`app.syncManager.errorHandler` should get called when I see the following error in the application log 
```
Error:
could not decode next message: error reading body failed to read: read limited at 16777217 bytes
```

## Actual Results
`app.syncManager.errorHandler` is not called. Occasionally I can see the following message in the xcode console
```Sync: Connection[1]: Connection Closed Due to Error```

## Steps for others to Reproduce

1. Set up a `syncManager.errorHandler` in your application
2. Create a large database, and then open a synced realm to trigger the `read limited at xxx` application error

## Code Sample
```        
app.syncManager.errorHandler    = {  error, session in
        print("Sync Error ", error) // not fired
}
syncedRealm.write {
    //create a lot of rows with blobs 
}
```
## Version of Realm and Tooling

Realm framework version: 10.10.0

Xcode version: 12.5

iOS/OSX version: 14.4

**Comment by jsflax** [comment]
Hey @ksiwei, I've written this test to try to reproduce the error:
```swift
func testReadLimitError() {
    do {
        let user = try logInUser(for: basicCredentials())
        let realm = try openRealm(partitionValue: #function, user: user)

        var theError: SyncError?
        let ex = expectation(description: "Waiting for error handler to be called...")
        app.syncManager.errorHandler = { (error, _) in
            if let error = error as? SyncError {
                theError = error
            } else {
                XCTFail("Error \(error) was not a sync error. Something is wrong.")
            }
            ex.fulfill()
        }

        try! realm.write {
            for _ in 0..<100 {
                realm.add(SwiftHugeSyncObject.create())
            }
        }
        waitForExpectations(timeout: 60, handler: nil)
        XCTAssertNotNil(theError)
        guard let error = theError else { return }
        XCTAssertTrue(error.code == SyncError.Code.clientInternalError)
        XCTAssertNotNil(realm)
    } catch {
        XCTFail("Got an error: \(error) (process: \(isParent ? "parent" : "child"))")
    }
}
```

However, I am unable to reproduce it.

The test logs in, opens a Realm for some partitionValue, sets an `errorHandler` that ensures that we receive a `SyncError`, and then proceeds to write ~100mb of data to the synced Realm. The test then waits for for the Error, which is indeed triggered.

Is there anything I'm missing here that may help me trigger the error (or lack thereof) that you're seeing?

**Comment by ksiwei** [comment]
hmm 🤔 Your test looks exactly like what I was trying to do. I tried on a separate Realm app, but was still not able to trigger the error. 
```swift
        if let appUser = app.currentUser {
            self.config = appUser.configuration(partitionValue: "user=\(appUser.id)")
            
            do {
                let remoteRealm = try Realm(configuration: self.config)
                
                app.syncManager.errorHandler = { error, session in
                    print("Sync Error ", error)
                }
                
                try remoteRealm.write {
                    print("Write to realm")
                    
                    for _ in 0..<20 {
                        let img = ImageObject()
                        img.imageData = UIImage(named: "Image4")?.pngData()
                        remoteRealm.add(img)
                    }
                }
            } catch {
            }
        }
```

Does anything obviously wrong jump out to you? Thanks for the help!

**Comment by leemaguire** [comment]
@ksiwei Is it possible that you are losing the reference to `app` during the time of the operation?

**Comment by dianaafanador3** [comment]
@ksiwei Any updates on this?

**Comment by ksiwei** [comment]
We found a workaround to this. Still not sure what happened. Will close the issue for now. Thanks for all the tips.
