### ISSUE TITLE
Warning: "Missing creator task for discovered dependency input node"

### ISSUE THREAD

**Issue by backslash-f** [realm/realm-cocoa#7348]
Hallo, would you guys know what's going on here?
I got `193` warnings from Realm with Xcode 13 beta 3. `¯\_(ツ)_/¯`

## Goals
To build w/o warnings.

## Expected Results
No warnings.

## Actual Results
Warnings.

![](https://i.imgur.com/Sp1GFrK.jpg)

## Steps for others to Reproduce
Create an Xcode Swift project and add Realm as a dependency via Cocoapods.

## Code Sample
N/A

## Version of Realm and Tooling
```
ProductName:	macOS
ProductVersion:	12.0
BuildVersion:	21A5284e

Xcode 13.0
Build version 13A5192j

Cocoapods 1.10.1
Realm (10.10.0)
RealmSwift (10.10.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)

/usr/local/bin/git
git version 2.30.1
```

Let me know if more info is needed. Danke!

**Comment by kbendelow** [comment]
I'm seeing this issue with an entirely different library, but it also seems to have to do with .hpp files

**Comment by pavel-ship-it** [comment]
It's fixed in XCode 13 beta 4
