### ISSUE TITLE
No such module 'Realm' - Error on Catalina (10.15.7)

### ISSUE THREAD

**Issue by ravikirankhareedi** [realm/realm-cocoa#7356]
**No such module 'Realm' - Error on Catalina (10.15.7)**

## Goals
Integrate Realm as a binary framework (xcframework) in Swift Package Manager

## Expected Results
The code is expected to compile. 
The same works on BigSur but not on Catalina

## Actual Results
I get an error during build - "No such module 'Realm'"

## Steps for others to Reproduce

1. Downloaded the package from: [Realm-Git](https://github.com/realm/realm-cocoa) - 10.10.0
3. On console, navigate to the realm source code (../realm-cocoa-master)
4.  `sh build.sh help` - Should show list of all the options
5.  `sh build.sh clean`
6.  `sh build.sh xcframework osx`

xcframework successfully written out to: /realm-cocoa-master/build/Realm.xcframework
xcframework successfully written out to: /realm-cocoa-master/build/RealmSwift.xcframework    

Added the depdency to XCFramework in package.swift
        .binaryTarget(name: "Realm", path: "Dependencies/Realm.xcframework"),
        .binaryTarget(name: "RealmSwift", path: "Dependencies/RealmSwift.xcframework"),

Package build fails. (The same works on BigSur). I re-built the framework on Catalina to make sure there aren't any compatibility issues. 

## Version of Realm and Tooling

Realm framework version: 10.10.0

Xcode version: Version 12.3 (12C33)

iOS/OSX version: 10.15.7

**Comment by leemaguire** [comment]
Hi @ravikirankhareedi just to be clear, on Catalina the XCFramework build succeeds, just the failure is when you try to build the swift package that references it?

**Comment by ravikirankhareedi** [comment]
> Hi @ravikirankhareedi just to be clear, on Catalina the XCFramework build succeeds, just the failure is when you try to build the swift package that references it?

Yes, That is correct.

**Comment by leemaguire** [comment]
Can we see what your `swift.package` for your project looks like?

**Comment by ravikirankhareedi** [comment]
```
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MyDB",
    platforms: [.macOS(.v10_15)],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "MyDB",
            targets: ["MyDB", "Realm", "RealmSwift"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(path: "Cmn")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "MyDB",
            dependencies: [
                "Cmn"
            ],
            path: "Sources/",
            swiftSettings:[.unsafeFlags(["-enable-testing"])]),
        .binaryTarget(name: "Realm", path: "Dependencies/Realm.xcframework"),
        .binaryTarget(name: "RealmSwift", path: "Dependencies/RealmSwift.xcframework"),
        .testTarget(
            name: "MyDBTests",
            dependencies: ["MyDB"]),
    ]
)

```

**Comment by leemaguire** [comment]
Maybe adding the binaryTarget to a wrapper might work, as described here https://stackoverflow.com/a/65255303

**Comment by leemaguire** [comment]
Closing as this is an Xcode related issue and not a Realm issue.
