### ISSUE TITLE
Do not want to save application data on the phone device including Realm

### ISSUE THREAD

**Issue by dfg-1310** [realm/realm-cocoa#7366]
## Goals

Due to security concerns, we do not want to save application data on phone devices.  

I tried to put the realm database is in-memory. After saving data is in the realm database when trying to retrieve it then gets blank or nil. Need to know the solution how we can fix it.

In-memory realm database approach is good for not saving data on the device?

## Expected Results

Should be able to get saved data from in-memory realm database.
## Actual Results

Not able to get saved data from in-memory realm database.

## Code Sample

var config = Realm.Configuration(
               schemaVersion: 16,
               migrationBlock:
                {
                migration, oldSchemaVersion in
                
                // We haven’t migrated anything yet, so oldSchemaVersion == 0
                if (oldSchemaVersion < 1)
                {
                }
               } 
                                
        **config.inMemoryIdentifier = “App Memory Identifier”** // set in memory identifier here
        config.deleteRealmIfMigrationNeeded = true
        
        
        Realm.Configuration.defaultConfiguration = config
        let _ = try! Realm()
    }

## Version of Realm and Tooling

Realm framework version: pod 'RealmSwift', '2.8.1'

Xcode version: Version 12.5.1 

iOS/OSX version: 9.0

Dependency manager + version: ?

**Comment by jsflax** [comment]
Hey @dfg-1310– by design, using an in memory Realm will not persist data to the device, so I'm not entirely sure what you mean here.
