### ISSUE TITLE
RealmSwift build with Realm Core 11.2.0

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7374]
## Goals
Build and test application using RealmSwift SDK with fix for realm-core crash (realm-core v11.2.0)

Could someone provide an indication of when a new RealmSwift SDK is likely to be released with the new realm-core v11.2.0.  This contains a bug fix we need to complete testing.

Just for future reference what is the typical build cycle to incorporated realm-core fixes into the RealmSwift SDK ?

Thanks.
Duncan

**Comment by jsflax** [comment]
Hey @duncangroenewald , the latest version should be released later today: https://github.com/realm/realm-cocoa/pull/7373. Generally speaking, there is a 24-48 hour turnaround for new versions off of core releases (depends on if the core version has breaking changes, of course).

**Comment by duncangroenewald** [comment]
@jsflax - great thanks.
