### ISSUE TITLE
Multiple Realm Tables of same Class

### ISSUE THREAD

**Issue by HMWDavid** [realm/realm-cocoa#7377]
I have a RealmObject Class. I want multiple tables of the same class

**Comment by jsflax** [comment]
@HMWDavid this isn't something we support nor do we intend to. What would the purpose of this be? Maybe we can offer a workaround.

**Comment by HMWDavid** [comment]
I'm developing a chat application. I plan to build a message table for each session, so I asked the above question

**Comment by HMWDavid** [comment]
Thank you for your answer.
I've abandoned this idea and put the messages in the message table, distinguished by session identifiers.
