### ISSUE TITLE
✏️ Typos on v10.10 release notes

### ISSUE THREAD

**Issue by phatblat** [realm/realm-cocoa#7384]
## Minor Typos on Release Notes

The [v10.10](https://github.com/realm/realm-cocoa/releases/tag/v10.10.0) release notes are missing the `var` keyword in two places in the 2nd bullet point which shows the new `@Persisted` attribute syntax. Current text:

> No more overriding class methods like primaryKey(), indexedProperties() or ignoredProperties(). The primary key and indexed flags are set directly in the property declaration with @Persisted(primaryKey: true) _id: ObjectId or @Persisted(indexed: true) indexedProperty: Int. If any @Persisted properties are present, all other properties are implicitly ignored.

There should be a `var` after the `@Persisted` attribute and before the property name. Correct examples below:

- `@Persisted(primaryKey: true) var _id: ObjectId`
- `@Persisted(indexed: true) var indexedProperty: Int`

## Goals

Copy and paste the example syntax into Xcode to build my Swift model.

## Expected Results

Pasting `@Persisted(primaryKey: true) _id: ObjectId` into a Swift class source file will not generate an error.

## Actual Results

Xcode generates a compiler error: "Expected 'var' keyword in property declaration" with a fix-it of "Insert 'var '"

## Code Sample

```swift
import RealmSwift
class Project: Object, ObjectKeyIdentifiable {
    @Persisted(primaryKey: true) _id: ObjectId
    @Persisted(indexed: true) indexedProperty: Int
}
```

## Version of Realm and Tooling

Realm framework version: v10.10 to v10.12

Xcode version: 12.5.1 or 13 beta 4

iOS/OSX version: iOS version 14.7 or 15 beta 4

Dependency manager + version: Swift Package Manager 5.4-5.5

**Comment by pavel-ship-it** [comment]
Hi @phatblat . Thank you for reporting the issue. I'll update the example.
