### ISSUE TITLE
No Prebuilt xcframework for Xcode 13 betas but Promised

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-cocoa#7389]
!!! MANDATORY TO FILL OUT !!!

## Goals

Get the prebuilt xcframework for Xcode 13 beta 5. 

Besides, in the release note, it says 

> Xcode: 12.2-13.0 beta 4. On iOS Xcode 13 beta 2 is the latest supported
version due to betas 3 and 4 having a broken Combine.framework.

It will be better to leave a track id here so we could all get update the state of the issue. In current situation, I have no where to  track the issue.

## Expected Results

Get the prebuilt xcframework for Xcode 13 beta 2.

## Actual Results

No prebuilt xcframework for Xcode 13.

<img width="973" alt="Screen Shot 2021-08-12 at 10 37 11 AM" src="https://user-images.githubusercontent.com/2182896/129129950-32589011-a7da-45ec-95c2-79addbb9c2a7.png">

## Steps for others to Reproduce

1. go to release.
2. download the latest `realm-swift-10.12.0.zip`.
3. unzip the download file.

## Code Sample

No need.

## Version of Realm and Tooling

Realm framework version: ?
v10.12.0

Xcode version: ?
 13.0 beta 5 (13A5212g)

iOS/OSX version: ?
iOS 15 beta 5

Dependency manager + version: ?
Carthage 0.38.0

**Comment by tgoyne** [comment]
Apple has still not fixed the bug.

**Comment by gongzhang** [comment]
I cherry-picked [Work around canImport(Combine) being broken in Xcode 13](https://github.com/gongzhang/realm-cocoa/commit/d8503514b320a002f6f38aa98e6ebfbca61551b6) and [Add support of arm64 in Carthage build](https://github.com/gongzhang/realm-cocoa/commit/f3fab3390d835d5202d6604b8692cfc2709e160d) on `v10.8.1`. Then I can build XCFramework successfully using Carthage 0.38 + Xcode 13 beta 5.

However, I still can't build my app in Xcode 13 due to linker error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RealmSwiftObject", referenced from:
      type metadata for HiCoffee.LogCaffeineIntentGroupRealmObject in LogCaffeineIntentGroup.o
      type metadata for HiCoffee.CoffeeRecordRealmObject in CoffeeRecord.o
      type metadata for HiCoffee.CoffeeKindRealmObject in CoffeeKind.o
  "_OBJC_METACLASS_$_RealmSwiftObject", referenced from:
      _OBJC_METACLASS_$__TtC8HiCoffee33LogCaffeineIntentGroupRealmObject in LogCaffeineIntentGroup.o
      _OBJC_METACLASS_$__TtC8HiCoffee23CoffeeRecordRealmObject in CoffeeRecord.o
      _OBJC_METACLASS_$__TtC8HiCoffee21CoffeeKindRealmObject in CoffeeKind.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
