### ISSUE TITLE
RLMException crash: Index out of bounds in results observer

### ISSUE THREAD

**Issue by miklselsoe** [realm/realm-cocoa#7390]
I am seeing a crash coming in from the field where I am reacting to a change in an observer on a `Results` object.

This is the exception:
```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Index 2 is out of bounds (must be less than 2).'
```

This is the code that crashes:

```swift
    let orders = realm.objects(Order.self)
    self.observerToken = orders.observe(on: self.processingQueue) { [weak self] (change) in

        switch change {
            case .update(let ordersAfterUpdate, _, _, let modifications):
                let updatedOrders = modifications.map { ordersAfterUpdate[$0] } // <- Crash
                if updatedOrders.isEmpty == false {
                    self?.updateOrders(updatedOrders)
                }
            default:
                break
        }
    }
```

It was my understanding that the indices in the `modifications` array matched what was available in the `ordersAfterUpdate` list, although the documentation isn't very clear on that. I have also tried to open a realm and fetch the orders after an update, but indicies can still be out of bounds. Since this is happening in the field, I don't what leads to this state.

How am I supposed to use the `modifications` list if not as indices on the `ordersAfterUpdate` list? I just want to find the orders that was updated.

## Version of Realm and Tooling
Realm framework version: 10.12.0

Xcode version: 12.5.0

iOS/OSX version: 14.6

Dependency manager + version: Carthage 0.38.0

**Comment by tgoyne** [comment]
The modifications indices are the indices in the previous version of the collection which were modified, as that's what UITableView requires for its batch update functions and the API was designed to make it easy to drive a UITableView. If any of the objects were deleted or you perform non-end insertions then they will be incorrect.

Translating these into indices in the new collection is moderately awkward. There's probably a better way to write this, but the naive version is:
```
func modificationInNew(index: Int, deletions: [Int], insertions: [Int]) -> Int {
    var i = index - deletions.prefix { $0 < index }.count
    for insertion in insertions {
        if insertion > i { break }
        i += 1
    }
    return i
} 
```

If you never do non-end insertions then `index - deletions.prefix { $0 < index }.count` is the only part you need.

**Comment by miklselsoe** [comment]
It seems like this is a documentation issue then. Documentation:
https://github.com/realm/realm-cocoa/blob/83a07f6a508c3427058d9e2c466208d0b6a960fa/RealmSwift/RealmCollection.swift#L158

This is what it says about the `modifications` parameter:
```
 - parameter modifications: The indices of the objects in the new collection which were modified in this version.
```

I can't interpret it any other way than the modifications indices refer directly to the new collection (which would make sense)?

**Comment by bmunkholm** [comment]
Fixed in https://github.com/realm/realm-cocoa/pull/7424
