### ISSUE TITLE
Maintainers: can we remove autorelease blocks with GCD autoreleaseFrequency: .workItem?

### ISSUE THREAD

**Issue by rromanchuk** [realm/realm-cocoa#7394]
All latest documentation still wraps writes in autorelease blocks. 
https://docs.mongodb.com/realm/sdk/ios/advanced-guides/threading/#pass-instances-across-threads

There is very little information on the actual internals, but wondering if anyone has confirmed it's a NOOP when removing manual autorelease blocks and instead instantiating the dispatch queue with `autoreleaseFrequency: .workItem`

This question is three years old and still no confirmation, so I want to pose this question here. 
https://stackoverflow.com/questions/49459967/for-realm-swift-could-i-use-dispatchqueue-with-autorelease-frequency-of-workit

**Comment by tgoyne** [comment]
It should work, yes. I guess we really should be recommending that now; we only didn't originally because iOS 10 was once an unreasonably new requirement and obviously that's no longer the case.

**Comment by rromanchuk** [comment]
@tgoyne cool thanks.  Closing to reduce noise
