### ISSUE TITLE
possible developer induced regression, .id result coerced to "ObjectIdentifier<hex representation>"

### ISSUE THREAD

**Issue by rromanchuk** [realm/realm-cocoa#7407]
my `id` is defined as `@Persisted(primaryKey: true) var id: String`

Just recently a  `[String, Any]` payload began failing when an associated (nested) value like  `dog.owner.id` was returning what looks like a debug description `"ObjectIdentifier<hex representation>"`

```
["id"; dog.id, "owner_attributes": ["id": dog.owner.id]]
// -> ["id"; "374fjd-34732-fakeuuid", "owner_attributes": ["id": "ObjectIdentifier<hex representation>"]]

["id"; dog.id, "owner_attributes": ["id": dog.owner.id.string]] // explicit call to string 
// -> ["id"; "374fjd-34732-fakeuuid", "owner_attributes": ["id": "38FDS-normal-string-uuid"]]
```

My first guess is recent conformity to `extension Object: Identifiable {}` for limited swiftUI support, changed behavior in dictionary building triggering https://developer.apple.com/documentation/swift/objectidentifier/2298468-debugdescription

Closing as i don't believe this to be specific to realm, but posting for visibility as it's difficult to catch unless you're paying close attention to the resulting string. This may have been responsible for additional issues ( such as notify subscriptions not being called) when manually setting associations via partial updates using value dictionaries.

**Comment by dianaafanador3** [comment]
Hi @rromanchuk thanks for taking the time to inform us about this. Closing as this is not causing any issue at the moment.
