### ISSUE TITLE
Atlas Connections are NOT closed

### ISSUE THREAD

**Issue by kaeferfreund** [realm/realm-cocoa#7428]
### How frequently does the bug occur?

All the time

### Description

We are using realm-coca to connect to realm-sync on our atlas account.

Since the beginning of 2021 we are using it in production with around 20 devices. Since then the connection count on the atlas db was hovering around 50-80 connections.

Since we switched our development device to using the `@ObservedResults(Data.self) var data` command **our connection count is constantly climbing on our atlas tier, reaching 500, 800 and even 1.0000 connections.**

The connection count dropped from 1.000 to 600, to 400, to 100 with a time delay of many hours, after I _stopped testing our development app_. Whenever I continue testing, the connection count starts rising the same way again

Whenever I start the dev app there is between 5 and 10 connections beeing opened on the atlas realtime monitor, that are not beeing closed.

Any ideas why? Is there something I have to do when using `@ObservedResults(Data.self) var data` to close the connections in realm-swift?

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Start the dev app
2. Call a view that uses the `@ObservedResults(Data.self) var data`

### Version

10.14.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

14.7.1

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by jsflax** [comment]
@kaeferfreund Did anything else change in your app? `@ObservedResults` is effectively shorthand for allowing the view to observe the `Results` without you having to hook it in yourself– but under the hood, it's still only referencing the Results set once.

**Comment by ianpward** [comment]
@kaeferfreund Can you open a support ticket on this? The Github repo's are intended for non-sync bugs - for sync please use the support portal on your cloud dashboard.

**Comment by kaeferfreund** [comment]
Okay, many thanks. That is what we have done
