### ISSUE TITLE
Can't compile for catalyst on Xcode 13.0

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-cocoa#7440]
### How frequently does the bug occur?

All the time

### Description

I am trying to compile the`xcframework` manually using the command on Version 13.0 (Swift 5.5):

```
sh build.sh xcframework ios catalyst
```

By running the similar command without `catalyst`, it compiles sucessfully:

```
sh build.sh xcframework ios
```

It demonstrate that the bug is something with `catalyst`.

### Stacktrace & log output

```shell
realm-cocoa/RealmSwift/App.swift:552:26: error: cannot find 'withCheckedThrowingContinuation' in scope
        return try await withCheckedThrowingContinuation { continuation in
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
realm-cocoa/RealmSwift/Realm.swift:1060:23: error: cannot find 'withCheckedThrowingContinuation' in scope
            try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Swift.Error>) in
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

GenerateDSYMFile realm-cocoa/build/DerivedData/Realm/Build/Products/Release-maccatalyst/Realm.framework.dSYM realm-cocoa/build/DerivedData/Realm/Build/Products/Release-maccatalyst/Realm.framework/Versions/A/Realm (in target 'Realm' from project 'Realm')
    cd realm-cocoa
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil realm-cocoa/build/DerivedData/Realm/Build/Products/Release-maccatalyst/Realm.framework/Versions/A/Realm -o realm-cocoa/build/DerivedData/Realm/Build/Products/Release-maccatalyst/Realm.framework.dSYM

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 (in target 'RealmSwift' from project 'Realm')
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'RealmSwift' from project 'Realm')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'RealmSwift' from project 'Realm')
	CompileSwift normal arm64 (in target 'RealmSwift' from project 'Realm')
(4 failures)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

- Use Xcode 13.0 (Swift 5.5)
- Clone the project from the master branch
- Run `sh build.sh xcframework ios catalyst`

### Version

v10.15.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

 Xcode 13.0

### Build environment

Xcode version: 13.0 (Swift 5.5)
Dependency manager and version: Manual

**Comment by tgoyne** [comment]
The Xcode 13 RC has dropped the macOS 12 SDK and reverted back to the 11.3 SDK, which means that anything using async/await doesn't compile for macOS.

**Comment by ppamorim** [comment]
@tgoyne Good to keep this on track for other developers.

**Comment by ppamorim** [comment]
@tgoyne is it possible to set any flag to disable the use of `async/await`? Is there any workaround? I don't need the apps production ready because I will be using this RC build of Xcode to build the apps for iOS 13.

**Comment by leemaguire** [comment]
@ppamorim take a look here https://github.com/realm/realm-cocoa/issues/7441#issuecomment-919855162

**Comment by ppamorim** [comment]
@leemaguire Sadly we support maccatalyst :(

**Comment by ppamorim** [comment]
@leemaguire When running `sh build.sh xcframework ios` it compiles but I get this error:

```
error: unable to read the file at '../realm-cocoa/build/DerivedData/Realm/Build/Products/Release-maccatalyst/RealmSwift.framework/RealmSwift'
```

Should I ignore that?
