### ISSUE TITLE
Realm upgrade  

### ISSUE THREAD

**Issue by vaibhavlaghane** [realm/realm-cocoa#7445]

**Comment by dianaafanador3** [comment]
Hi @vaibhavlaghane any reason you are not upgrading to our latest version [v10.15.1](https://github.com/realm/realm-cocoa/releases/tag/v10.15.1)?

**Comment by vaibhavlaghane** [comment]
Hello,

Appreciate your response.
Looking to work with minimal version change as dependent libraries in the app use 4.4.1 or 5.5.2 .
Testing and releasing them will be huge task.

Is there a file format change between the versions?
Any specific script to upgrade?
Is there a patch fix for 5.5.2 ?

Thanks
