### ISSUE TITLE
Module compiled with Swift 5.5 cannot be imported by the Swift 5.4 compiler

### ISSUE THREAD

**Issue by ravikirankhareedi** [realm/realm-cocoa#7446]
### How frequently does the bug occur?

All the time

### Description

I am using the compiler Realm package 10.15.1 (https://github.com/realm/realm-cocoa/releases/download/v10.15.1/realm-swift-10.15.1.zip). I used the xcframework built on Xcode 13. I get the error "Module compiled with Swift 5.5 cannot be imported by the Swift 5.4 compiler" when I try to build the project with Xcode 12.5 

### Stacktrace & log output

```shell
Module compiled with Swift 5.5 cannot be imported by the Swift 5.4 compiler
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Use the xcframework for 13.0 (realm-swift-10.15.1/13.0)with Xcode 12.5. 

### Version

Realm 10.15.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

11.4 Mac OS

### Build environment

Xcode version: 12.5

**Comment by dianaafanador3** [comment]
Hi @ravikirankhareed You need to add the XCFramework for your XCode version, so if you are using Xcode 12.5 you should be using the `XCFramework` for 12.5.1.

**Comment by dianaafanador3** [comment]
@ravikirankhareedi closing this as there is no issue in our side.
