### ISSUE TITLE
Crash on update (Error Domain=io.realm Code=6)

### ISSUE THREAD

**Issue by johnswifttt** [realm/realm-cocoa#7457]
### How frequently does the bug occur?

All the time

### Description

I have an app in the App Store that has Realm. For a new app version, I updated Realm to latest with Swift Package Manager. This causes a crash when opening app after updating.

Does this mean I should not update to the latest Realm? I can't delete the old Realm database because that contains user data.

Here is a picture of crash
<img width="1278" alt="crash" src="https://user-images.githubusercontent.com/10701375/134828844-63baa881-8940-4684-9e11-223946b9f0dd.png">

### Stacktrace & log output

```shell
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=6 "Opening Realm files of format version 20 is not supported by this version of Realm" UserInfo={Error Code=6, NSFilePath=/var/mobile/Containers/Data/Application/RRtC6C44-26B9-46C4-A54C-836UIYP352E/Documents/default.realm, Underlying=Database has an unsupported version and cannot be upgraded
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

This is the test that crashes app:
1. I download my app from App Store. This will use old Realm to store user data.
2. Run new version of app from Xcode. This is to mimic an upgrade users would do.
3. The app crashes

### Version

Realm 5.5.2 and RealmCore 6.2.4

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 13, 14, and 15

### Build environment

Xcode version: 13.0
Dependency manager and version: Swift Package Manager

**Comment by dianaafanador3** [comment]
Are you upgrading from Realm version 5.5.2 to our latest release 10.5.1?

**Comment by johnswifttt** [comment]
This seems to work for me now. When I switched from Cocoapods to SPM, I accidentally chose major version `5`. The problem is that SPM defaults to this instead of the latest major version which is `10`.

Your question helped @dianaafanador3 thank you!
