### ISSUE TITLE
'Identifiable' is only available in application extensions for iOS 13 or newer

### ISSUE THREAD

**Issue by maciaspeter** [realm/realm-cocoa#7460]
The error message is 'Identifiable' is only available in application extensions for iOS 13 or newer
The issue is coming from Combine. I don't use it and my app is at 11.2 IOS version. I am switching to a new laptop from old laptop and got this error.

I tried doing this below but didn't work.
  pod 'RealmSwift', '~>10'

the original is   pod 'RealmSwift'
didn't work either.

Here's my pod file - 
```
platform :ios, '11.2'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = "4.2"
    end
  end
end

abstract_target 'Big Note App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  pod 'RealmSwift', '~>10'
  pod 'lottie-ios'
  
  target 'Big Note' do
  end
  target 'Big Note Prod' do
  end

  target 'Big NoteTests' do
      inherit! :search_paths
      # Pods for testing
  end

  target 'Big NoteUITests' do
      # Pods for testing
  end

end
```

**Comment by maciaspeter** [comment]
The error message is coming from - 

`public protocol ObjectKeyIdentifiable: Identifiable, ObjectBase {`

**Comment by tgoyne** [comment]
This sounds like you are trying to use an old version of Realm. You made need to run `pod repo update` and then `pod update` to ensure you are using the latest version.

**Comment by maciaspeter** [comment]
it worked, thanks!
