### ISSUE TITLE
Cannot inherit from class 'Object' because it has overridable members that could not be loaded

### ISSUE THREAD

**Issue by Zeropointer11** [realm/realm-cocoa#7465]
### How frequently does the bug occur?

All the time

### Description

Xcode: 13.0 (13A233)
CocoaPod  Version: 1.11.2
Realm Version: 10.16.0

I have setuped an new Project with Xcode 13 and add Realm with Cocoa Pods. When i would Create an RealmSwift Object i get the following Errors:
1: Cannot inherit from class 'Object' because it has overridable members that could not be loaded
2: Unknown attribute 'Persisted

![Bildschirmfoto 2021-10-04 um 20 04 54](https://user-images.githubusercontent.com/3930333/135901578-de343027-9ae3-48f6-881f-2d77e57c6d7b.png)
'

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Open Xcode 13
2. Create new Project with SwiftUI
3. pod init
4. add ' pod 'RealmSwift', '~> 10.16'
5.  crate new Realm Object

### Version

10.16

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOs 11.6

### Build environment

```
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

/Applications/Xcode.app/Contents/Developer
Xcode 13.0
Build version 13A233

/usr/local/bin/pod
1.11.2
Realm (10.16.0)
RealmSwift (10.16.0)
RealmSwift (~> 10.16)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

carthage not found
(not in use here)

/usr/bin/git
git version 2.30.1 (Apple Git-130)
```

**Comment by leemaguire** [comment]
Hi @Zeropointer11 I cannot reproduce your issue. Are you opening the project from workspace Cocoapods creates?

**Comment by Zeropointer11** [comment]
@leemaguire yes i have opend the project with the workspace file from cocoapods.

I have reinstalled xCode 12 and run the Project with it after that it also worked with xCode 13 dont know why
