### ISSUE TITLE
Could not find module 'RealmSwift' for target 'arm64-apple-ios-simulator';

### ISSUE THREAD

**Issue by eguchi-t** [realm/realm-cocoa#7468]
### How frequently does the bug occur?

All the time

### Description

In Xcode13, when I install and build with carthage, I get the following error.

The Mac is an M1 Mac mini.  
carthage has been run with the following commands and exited successfully.

```
carthage update --platform iOS --no-use-binaries --use-xcframeworks
```

It was fine in Xcode12.

### Stacktrace & log output

```shell
Could not find module 'RealmSwift' for target 'arm64-apple-ios-simulator'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios- simulator, at:`path`
```

### Can you reproduce the bug?

Yes, always

### Version

v10.16.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS 11.5.2

### Build environment

Xcode version: Xcode13
Dependency manager and version: Carthage 0.38.0

**Comment by Sam-Davis** [comment]
We can replicate this on xcdode 12.5.1 with Carthage 0.38.0 and an M1 chip. 
Works on same versions, but without the M1 chip.

**Comment by dianaafanador3** [comment]
@Sam-Davis @eguchi-t If you can use this branch as a workaround https://github.com/realm/realm-cocoa/pull/7158

**Comment by md-rubel** [comment]
is this problem solved? i'm facing related problem for cocoapod install, version `10.22.0`
Here is the error:

`Could not find module 'RealmSwift' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/username/Library/Developer/Xcode/DerivedData/app-name-fexncfaxdkhiqpaooqdgayaicvlg/Build/Products/Debug-iphonesimulator/RealmSwift/RealmSwift.framework/Modules/RealmSwift.swiftmodule`

**Comment by harshad1242** [comment]
Any solution for those who using Swift package manager?

**Comment by dianaafanador3** [comment]
@harshad1242 this is fixed for Carthage as mentioned on the original issue. If this is happening for SPM it is not related to this, and most probably has to do with your project settings.
