### ISSUE TITLE
SSL/TLS protocol not supported

### ISSUE THREAD

**Issue by kyungho-kim** [realm/realm-cocoa#7474]
### How frequently does the bug occur?

All the time

### Description

When I run the macOS app in Xcode 13, the app is terminated. Run in an iOS simulator, it works normally.

### Stacktrace & log output

```shell
libc++abi: terminating with uncaught exception of type realm::util::network::ssl::ProtocolNotSupported: SSL/TLS protocol not supported
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Run macOS app on Xcode 13

### Version

10.17.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 11.6

### Build environment

Xcode version: 13.0
Dependency manager and version: SPM

**Comment by leemaguire** [comment]
@kyungho-kim is this a Catalyst app?

**Comment by kyungho-kim** [comment]
@leemaguire Yes, this is a Catalyst app.

**Comment by kyungho-kim** [comment]
@leemaguire No... I've never touched the openssl library. The problem occurs only in the Catalyst app, not iOS simulator or macOS target.
