### ISSUE TITLE
Unknown attribute 'Persisted'

### ISSUE THREAD

**Issue by iAmcR** [realm/realm-cocoa#7485]
### How frequently does the bug occur?

All the time

### Description

Following the installation instructions (https://docs.mongodb.com/realm/sdk/ios/install/) using Swift Package Manager, I get the following compilation error: 

`Unknown attributed 'Persisted'`, when using the `@Persisted` annotation, for example: 

`@Persisted
var whyIsThisNotWorking: String?`

The instruction from the above link is to use to default dependency rule: Up to Next Major. When this is done, the Swift package manager dialog only gives the option of 5.0.0 for the version, which seemingly is the root of the error. 

If I set the dependency rule to **Branch: master** the above error goes away.

However, this shouldn't be the case. Up to Next Major should work as well and give the latest package that doesn't result in the above error. 

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Create a new Xcode 13 swift project, follow the instructions here: https://docs.mongodb.com/realm/sdk/ios/install/ to install the Realm via Swift Package Manager. 

Create a class as follows: 

```
import RealmSwift

class StoreMe: Object {
    @Persisted
    var whyIsThisNotWorking: String?
}```


### Version

Swift Package Manager Up to Next Major Version 5.0.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS Big Sur (version 11.6),  Xcode 13.0 (13A233)

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by tgoyne** [comment]
It appears to be doing a naive lexicographical sort, so it considers 5.0.0 to be greater than 10.0.0.

**Comment by iAmcR** [comment]
Thank you @tgoyne 

I guess this bug should be reported to Xcode team then.
