### ISSUE TITLE
Error backing up data: Could not write file as not all client changes are integrated in server

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7486]
### How frequently does the bug occur?

All the time

### Description

We are creating a backup of the Realm file using Realm.writeCopy() and are suddenly getting this error message.

We have just migrated data to the new MongoDB Realm cloud service and have initialised a new desktop application instance.  The desktop makes a backup of the realm file on startup and for some reason we have suddenly started getting this error message when calling the Realm.writeCopy() API.

Any suggestion on what the problem could be - there don't appear to be any errors in the MongoDB Realm cloud logs.

### Stacktrace & log output

```shell
Not applicable
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Not applicable

### Version

Realm-cocoa v10.17.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS11.6

### Build environment

Xcode version: 13
Dependency manager and version: SPM

**Comment by duncangroenewald** [comment]
I am not getting this error message when using realm-cocoa v10.12.0 and it seems to be intermittent under 10.17.0 - meaning that occasionally it does not show this message.

I will test with other versions to see at what version this message starts showing up.

**Comment by jsflax** [comment]
So, the quick fix for you is to use the progress notifier on your `syncSession` to check if sync progress is complete. Once it is, you would be free to call writeCopy.

**Comment by ericjordanmossman** [comment]
I was previously running into this issue too. Not anymore after #7514.
Is that same for you @duncangroenewald ?

**Comment by duncangroenewald** [comment]
That's a good question. I will have to double check that to see if I can reproduce it now - I didn't notice anything after upgrading the SDK to v10.19.0 and it usually always happened in debug mode so should have seen it if it was there.

**Comment by duncangroenewald** [comment]
@ericjordanmossman @jsflax - I am closing this as since reverting to creating the local (non-synced) compatible backup file this issue no longer occurs - that is when using SDK v10.19.0.

Thanks
