### ISSUE TITLE
Impossible to come back to normal after `expired refresh token` error

### ISSUE THREAD

**Issue by jeanbaptistebeau** [realm/realm-cocoa#7494]
### How frequently does the bug occur?

All the time

### Description

After 30 days of being logged in, users get a `expired refresh token` error, that I catch in `syncManager.errorHandler`. This seems to be the normal behavior. My problem is, I can't get back to a normal state after getting this error. **If I logout/login the user, I get the same error.**

I'm using email/password auth, I don't know if this happens with other authentication providers.

What to do after this error?

### Stacktrace & log output

```shell
expired refresh token
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Repo: https://github.com/jeanbaptistebeau/realm_expiredrefreshtoken

 1. Change the realm app ID in Authentication.swift
 2. Run the app
 3. Press register to create the user
 4. Press sign in
 5. Now the app should be working fine, you can add objects, log out and login again
 6. Quit the app
 7. Now go to the device settings > General > Date and time and set it manually to 2 months in the future
 8. Run the app again
 9. You should get the "expired refresh token" error and thus be logged out of your account
 10. Try pressing sign in: from now on, you should get the same error everytime you log in

### Version

10.15.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14

### Build environment

Xcode version: 12.5.1
Dependency manager and version: Cocoapods

**Comment by jsflax** [comment]
@jeanbaptistebeau we've merged a PR in core that may address this issue– was your original issue that the clock was too far forward on your device?

**Comment by jeanbaptistebeau** [comment]
@jsflax it seems to be included in cocoa v10.19.0.

Could you tell me what happens now, when the user gets an "expired refresh token" error? The error handler of the sync manager won't be called?

**Comment by dianaafanador3** [comment]
HI @jeanbaptistebeau It looks like instead of checking this on core, we are checking this on the server, so you can still use the error handle to check if you need to refresh the user access token. 
Let us know if the fix worked for you, and close the issue if that's the case.
