### ISSUE TITLE
"mmap() failed: Cannot allocate memory" when using a custom thread with a run loop

### ISSUE THREAD

**Issue by juanj** [realm/realm-cocoa#7500]
### How frequently does the bug occur?

All the time

### Description

I'm getting crashes due to `mmap() failed: Cannot allocate memory size: 24117248 offset: 201326592`.

After looking at some related issues, I believe this is happening because Realm is keeping many active versions, and the file size is increasing.

I did some debugging using `maximumNumberOfActiveVersions` and it seems that my implementation of a thread with a run loop is causing Realm to keep many active versions.

The behavior that I'm seeing is that when I keep a reference to a `Results` object in the main thread, and then proceed to create multiple write transactions from a background thread, an active version is kept for each write transaction.
However, when I do the same using a global dispatch queue, this does not happen.

I may be doing something fundamentally wrong, as I do not completely understand how Realm manages active versions. If that is the case, please let me know. 

### Stacktrace & log output

```shell
*** Terminating app due to uncaught exception 'RLMException', reason: 'Number of active versions (200) in the Realm
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Sample project: [Example.zip](https://github.com/realm/realm-cocoa/files/7421396/Example.zip)

This code makes it happen:
```swift
var config = Realm.Configuration()
config.maximumNumberOfActiveVersions = 199
if let realm = try? Realm(configuration: config) {
    objects = realm.objects(TestObject.self)
}

for _ in 0 ..< 200 {
    thread.sync {
        autoreleasepool {
            let realm = try? Realm(configuration: config)
            try? realm?.write {}
        }
    }
}
```

And the thread implementation looks like this:
```swift
private class BackgroundThreadCall<ResultType>: NSObject {
    private let block: () throws -> ResultType
    var result: ResultType!

    init(_ block: @escaping () throws -> ResultType) {
        self.block = block
        super.init()
    }

    func invoke(on thread: Thread, sync: Bool) {
        perform(#selector(call), on: thread, with: nil, waitUntilDone: sync, modes: [RunLoop.Mode.default.rawValue])
    }

    @objc private func call() throws {
        result = try block()
    }
}

class BackgroundThread {
    private enum Const {
        static let runloopSleepInterval = 0.5 // in seconds
    }

    private var thread: Thread!

    init(name: String, qos: QualityOfService) {
        thread = Thread(target: self, selector: #selector(main), object: nil)
        thread.name = name
        thread.qualityOfService = qos
        thread.start()
    }

    deinit {
        thread.cancel()
    }

    func sync<R>(_ block: @escaping () -> R) -> R? {
        let call = BackgroundThreadCall(block)
        call.invoke(on: thread, sync: true)
        return call.result
    }

    @objc private func main() {
        autoreleasepool {
            repeat {
                if !RunLoop.current.run(mode: .default, before: Date.distantFuture) {
                    Thread.sleep(forTimeInterval: Const.runloopSleepInterval)
                }
            } while !thread.isCancelled
        }
    }
}
```

### Version

10.18.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.0

### Build environment

```
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

/Applications/Xcode.app/Contents/Developer
Xcode 13.0
Build version 13A233

/Users/juan/.rbenv/shims/pod
1.10.1
Realm (10.18.0)
RealmSwift (10.18.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

/usr/local/bin/git
git version 2.23.0
```

**Comment by dianaafanador3** [comment]
@juanj It looks like this was solved by @tgoyne comment. I'm gonna close this, if you still having issues with this you can reopen this again.
