### ISSUE TITLE
Cannot set up Google Auth on iOS and Android at the same time.

### ISSUE THREAD

**Issue by adaneko** [realm/realm-cocoa#7506]
### How frequently does the bug occur?

All the time

### Description

I have successfully implemented Google Sign in on both iOS and Android, but have run into an issue with getting them both working at the same time.

On the Android implementation, I am required to have:
a) A Google Cloud Platform Android OAuth credential that uses the SHA1 from my signing key
b) A GCP Web Client OAuth that provides a clientId and secret
c) A Realm Google Authorisation that uses the clientId and secret from b)

For the iOS implementation,  I am required to have:
a) A Google Cloud Platform iOS OAuth credential 
b) A Realm Google Authorisation that uses the clientId and URL scheme from b)

Observed behaviours:
* Passing the GCP Web clientId to Google results in a error from the sign in page: `"Authorisation Error" 400: Custom scheme URIs are not allowed to 'WEB' client type`.
* Passing the GCP iOS credential allows the Google sign in page to work, and returns an idToken, but then passing that to Realm gives the error: `47 - invalid id token: ‘aud’ must be a string containing the client_id`
* Replacing the Realm Google Authorisation clientId with the GCP iOS clientId allows me to sign in as expected.

The issue is that for Android to work requires using a GCP web clientId in the Realm Google authorisation, and for iOS to work requires using the GCP iOS clientId.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

As above

### Version

Latest

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14,15

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by ericjordanmossman** [comment]
Hey @adaneko I have a couple questions:
Are you using openID Connect?
Could you show how you're initializing the credentials?

**Comment by ericjordanmossman** [comment]
> Passing the GCP Web clientId to Google results in a error from the sign in page: "Authorisation Error" 400: Custom scheme URIs are not allowed to 'WEB' client type.

I also get this error if using a "Web application" type ID on the iOS client. Though I believe that a "Web application" type ID should be configured on the Realm server for both cases - iOS and Android.

I'm wondering if this error:
> 47 - invalid id token: ‘aud’ must be a string containing the client_id

Is potentially being caused by OpenID Connect when creating the Realm Credentials.

**Comment by adaneko** [comment]
Hi @ericjordanmossman,

Thanks for the reply.

I am using OpenID Connect. I was unable to get Android to work without it. This is the code I'm using to manage Google Sign in. Google.clientId holds the value of the GCP iOS clientId.

```swift

// MainViewController.swift

@IBAction func onSignInGoogleTapped(_ sender: Any) {
// this just wraps the success and failure conditions for convenience
    makeAPICall(call: userProxy.signInGoogle(from: self)
                    .flatMap(MongoProxy.shared.signInGoogle(user:)),
                success: onSignInComplete,
                fail: onSignInFailed)
}

// UserProxy.swift

private var googleSignInConfig: GIDConfiguration?

init () {
     googleSignInConfig = GIDConfiguration.init(clientID: Google.clientId.rawValue)
}

func signInGoogle(from presenter: UIViewController) -> Observable<GIDGoogleUser> {
        return Observable<GIDGoogleUser>.create { observable in
            guard let gConfig = self.googleSignInConfig else {
                observable.onError(CustomError(message: Ln.GoogleError.no_google_config))
                return Disposables.create()
            }
            GIDSignIn.sharedInstance.signIn(with: gConfig, presenting: presenter) {
                user, error in
                if let error = error {
                    observable.onError(error)
                } else if let gUser = user {
                    observable.onNext(gUser)
                    observable.onCompleted()
                } else {
                    observable.onError(CustomError(message: Ln.GoogleError.no_google_user))
                }
            }
            
            return Disposables.create()
        }
}

// MongoProxy.swift

func signInGoogle (user: GIDGoogleUser) -> Observable<Bool> {
    if let idToken = user.authentication.idToken {
        return signin(credentials: Credentials.googleId(token: idToken))
    }
            
    return Observable<Bool>.create { observable in
        GIDSignIn.sharedInstance.signOut()
        GIDSignIn.sharedInstance.disconnect()
        observable.onError(CustomError(message: Ln.GoogleError.no_google_auth))
        return Disposables.create()
    }
}

func signin(credentials: Credentials) -> Observable<Bool> {
    return Observable<Bool>.create { [weak self] observable in
        if let wSelf = self {
            wSelf.app.login(credentials: credentials) { result in
                switch result {
                case .failure(let error):
                    observable.onError(error)
                case .success(_):
                    observable.onNext(true)
                    observable.onCompleted()
                }
            }
        } else {
            observable.onCompleted() // complete without result
        }
       
      return Disposables.create()
   }
}
    
```

**Comment by ericjordanmossman** [comment]
Okay that does look like the correct flow for openID connect.

For 
> Replacing the Realm Google Authorisation clientId with the GCP iOS clientId allows me to sign in as expected

Which are you replacing? Are you  changing the iOS device's clientID to the "iOS clientID" type. Or are you changing the Realm Sync App's clientID to an "iOS" client type (in atlas)?

Ultimately the the backend Realm App should have the GCP "Web Application" type clientID, with the respective secret. And the iOS client should have GCP iOS type.

**Comment by adaneko** [comment]
I'm replacing the id (and secret) inside the Google Authentication Provider -> Client Id field

**Comment by ericjordanmossman** [comment]
Instead of using `if let idToken = user.authentication.idToken`, could you try getting the [idToken with](https://developers.google.com/identity/sign-in/ios/reference/Classes/GIDAuthentication#-dowithfreshtokens:) `doWithFreshTokens`.

```
googleUser.authentication.do { authentication, error in
guard error == nil else { ... }
guard let authentication = authentication else { ... }
                
 let idToken = authentication.idToken
```

I just noticed that we're getting the idTokens slightly different. Maybe that's where the validity is changing.

**Comment by ericjordanmossman** [comment]
@adaneko 
Did this work for you?
