### ISSUE TITLE
SSL/TLS protocol not supported

### ISSUE THREAD

**Issue by adamek314** [realm/realm-cocoa#7507]
### How frequently does the bug occur?

All the time

### Description

Whenever I try to open a synced realm in Mac Catalyst (iOS on Mac). I get

2021-10-31 23:05:01.075673-0400 Foody23Swift[3205:23982] Sync: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, client reset = false
2021-10-31 23:05:01.111175-0400 Foody23Swift[3205:23982] Sync: Connection[1]: Connected to endpoint '34.227.4.145:443' (from '192.168.1.132:49253')
libc++abi: terminating with uncaught exception of type realm::util::network::ssl::ProtocolNotSupported: SSL/TLS protocol not supported
terminating with uncaught exception of type realm::util::network::ssl::ProtocolNotSupported: SSL/TLS protocol not supported

Errors look similar to #7474, 
https://github.com/realm/realm-cocoa/issues/7474

Works fine on iPhone, just crashing on Mac.

### Stacktrace & log output

```shell
2021-10-31 23:05:01.075673-0400 Foody23Swift[3205:23982] Sync: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, client reset = false
2021-10-31 23:05:01.111175-0400 Foody23Swift[3205:23982] Sync: Connection[1]: Connected to endpoint '34.227.4.145:443' (from '192.168.1.132:49253')
libc++abi: terminating with uncaught exception of type realm::util::network::ssl::ProtocolNotSupported: SSL/TLS protocol not supported
terminating with uncaught exception of type realm::util::network::ssl::ProtocolNotSupported: SSL/TLS protocol not supported


Stacktrace

Thread 12
#0	0x00000001ab0519b8 in __pthread_kill ()
#1	0x0000000104fa3044 in pthread_kill ()
#2	0x00000001aafc2314 in abort ()
#3	0x00000001ab041b50 in abort_message ()
#4	0x00000001ab032f4c in demangling_terminate_handler() ()
#5	0x00000001aaf2a150 in _objc_terminate() ()
#6	0x00000001ab040ee4 in std::__terminate(void (*)()) ()
#7	0x00000001ab043efc in __cxa_rethrow ()
#8	0x00000001014b95d4 in void realm::util::network::Service::AsyncOper::do_recycle_and_execute<realm::_impl::ClientImplBase::Connection::initiate_tcp_connect(realm::util::network::Endpoint::List, unsigned long)::$_5, std::__1::error_code&>(bool, realm::_impl::ClientImplBase::Connection::initiate_tcp_connect(realm::util::network::Endpoint::List, unsigned long)::$_5&, std::__1::error_code&) at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/util/network.hpp:2852
#9	0x00000001014b949c in realm::util::network::Socket::ConnectOper<realm::_impl::ClientImplBase::Connection::initiate_tcp_connect(realm::util::network::Endpoint::List, unsigned long)::$_5>::recycle_and_execute() at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/util/network.hpp:3178
#10	0x00000001016299e0 in realm::util::network::Service::Impl::execute(std::__1::unique_ptr<realm::util::network::Service::AsyncOper, realm::util::network::Service::LendersOperDeleter>&) at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/util/network.cpp:1631
#11	0x0000000101625250 in realm::util::network::Service::Impl::run() at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/util/network.cpp:1392
#12	0x0000000101625120 in realm::util::network::Service::run() at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/util/network.cpp:1755
#13	0x0000000101416274 in realm::_impl::ClientImplBase::run() at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/sync/noinst/client_impl_base.hpp:1115
#14	0x00000001013fd15c in (anonymous namespace)::ClientImpl::run() at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/sync/client.cpp:667
#15	0x00000001013fd0ec in realm::sync::Client::run() at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/sync/client.cpp:1827
#16	0x0000000101190140 in realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::weak_ptr<realm::SyncManager const>)::'lambda0'()::operator()() const at /Users/adamek/Library/Developer/Xcode/DerivedData/Foody23Workspace-eiirzadkrepqsgfbyngcnhvuduxq/SourcePackages/checkouts/realm-core/src/realm/object-store/sync/impl/sync_client.hpp:79
#17	0x0000000101190014 in decltype(std::__1::forward<realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::weak_ptr<realm::SyncManager const>)::'lambda0'()>(fp)()) std::__1::__invoke<realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::weak_ptr<realm::SyncManager const>)::'lambda0'()>(realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::weak_ptr<realm::SyncManager const>)::'lambda0'()&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/type_traits:3694
#18	0x000000010118ffac in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::weak_ptr<realm::SyncManager const>)::'lambda0'()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::weak_ptr<realm::SyncManager const>)::'lambda0'()>&, std::__1::__tuple_indices<>) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/thread:286
#19	0x000000010118f7dc in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::weak_ptr<realm::SyncManager const>)::'lambda0'()> >(void*) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/thread:297
#20	0x0000000104fa1b40 in _pthread_start ()
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Here's part of my code:

realmApp.login(credentials: credentials) { (loginResult) in
            
            switch loginResult {
            case .failure(let error):
                NSLog("WARNING: Login failed: \(error)")
            case .success(let user):
                NSLog("DEBUG: Logged in. Set up configuration.")
                var loginConfiguration = user.configuration(partitionValue: uuidFamily)
                loginConfiguration.objectTypes = [DBUser.self,
                                                  Categories.self,
                                                  Commodities.self,
                                                  Units.self,
                                                  Stores.self,
                                                  Accounts.self,
                                                  ShoppingItems.self,
                                                  Ledgers.self,
                                                  Journals.self,
                                                  Vehicles.self,
                                                  Packages.self]
                NSLog("DEBUG: Logged in. Now asyncOpen.")
                
                Realm.asyncOpen(configuration: loginConfiguration) { result in
                    switch result {
                    case .failure(let error):
                        NSLog("WARNING: Unhandled error. Failed to open realm: \(error.localizedDescription)")
                    case .success(let realm):
                        NSLog("DEBUG: Successfully opened realm: \(realm)")
                        // Use realm to find dbUser
                        if let thisUser = realm.object(ofType: DBUser.self, forPrimaryKey: uuidUser) {
                            self.dbUser = thisUser
                            self.dbConfig = realm.configuration
                            NSLog("DEBUG: Found dbUser: \(thisUser._id.uuidString)")
                        } else {
                            NSLog("DEBUG: Create dbUser.")
                            
                            let newUser = DBUser()
                            newUser._id = uuidUser
                            newUser.uuidUser = uuidUser
                            newUser.uuidFamily = uuidFamily
                            do {
                                try realm.write({
                                    realm.add(newUser)
                                })
                                NSLog("DEBUG: Created dbUser: \(newUser._id.uuidString)")
                                self.dbUser = newUser
                                self.dbConfig = realm.configuration
                            } catch {
                                NSLog("WARNING: Unhandled error writing dbUser; \(error.localizedDescription)")
                                return
                            }
                        }
                        self.checkLoggedIn()
                    }
                }
            }

I get as far as the  NSLog("DEBUG: Logged in. Now asyncOpen.") message. The log error messages are right after that. It's crashing somewhere in asyncOpen.

### Version

10.18.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS 12.1 Beta (21C5021h)

### Build environment

Xcode version: Version 13.1 (13A1030d)
Dependency manager and version: Swift Package Manager, Realm 10.18.0

**Comment by dianaafanador3** [comment]
Closing this as it is a duplicate from this https://github.com/realm/realm-cocoa/issues/7474, and the fix is already merged on core side. This will be available in the next release.
