### ISSUE TITLE
Error when opening Realm backup file: "Incompatible histories. Expected a Realm with no or in-realm history, but found history type 3"

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7513]
### How frequently does the bug occur?

All the time

### Description

When opening a backup file that was created using Realm.writeCopy() we are now getting the following error message

"Incompatible histories. Expected a Realm with no or in-realm history, but found history type 3"

Realm SDK:  realm-cocoa v10.17.0 (RealmSwift)

File can be opened without error using Realm Studio v11.1.0

### Stacktrace & log output

```shell
2021-11-05 02:30:16.993986+1100 MakeSpace2[19143:215017] <BG>DataManager.realmI[206]: "Error opening Realm: Unable to open a realm at path \'/Users/xxxx/Documents/xxxx/Database/xxxx.realm\': Incompatible histories. Expected a Realm with no or in-realm history, but found history type 3 Path:Exception backtrace:\n0   xxxx                          0x00000001039d3dec _ZN5realm4util6detail26ExceptionWithBacktraceBaseC2Ev + 48\n1   xxxx                          0x00000001039dfc34 _ZN5realm4util22ExceptionWithBacktraceISt13runtime_errorEC2IJRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEEEEDpOT_ + 88\n2   xxxx                          0x00000001039dfa34 _ZN5realm4util4File11AccessErrorC2ERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEESB_ + 68\n3   xxxx                          0x0000000103a859d0 _ZN5realm21IncompatibleHistoriesC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 100\n4   xxxx                          0x0000000103a78ca4 _ZN5realm21Incompatible
xxxx/DataManager.swift:212: Fatal error
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Create a backup file using Realm.writeCopy().

Open backup file using RealmSwift v10.17.0 SDK

### Version

RealmSwift v10.17.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 12.0.1

### Build environment

Xcode version: 13.1
Dependency manager and version: SPM

**Comment by tgoyne** [comment]
This error indicates that you're opening a sync Realm in non-sync read-write mode, which isn't supported. If you just want to read from the file you can open it in read-only mode.

**Comment by duncangroenewald** [comment]
@tgoyne - is this a recent change in behaviour as we have been using this code for two years or more and never encountered this issue before.

**Comment by tgoyne** [comment]
This restriction predates the first public release of sync. The behavior of writeCopy() on synchronized Realms did change recently, though. It used to produce Realms which couldn't be opened in sync mode afterwards and the justification for not calling that a breaking change was that supposedly the old behavior was just broken, but converting a sync Realm to a local Realm sounds like a pretty valid thing to me.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-cocoa/pull/7514 reverts to the old behavior. v10.12.0 appears to be the version where we first shipped this change.

**Comment by duncangroenewald** [comment]
@tgoyne sorry I need a bit of help understanding this.  Looking at the code changes it seem one file has a history and the other does not.  I am assuming the one that has no history is the sync compatible file and the other can be opened as a local realm file.  Presumably that explains why the backup files suddenly became smaller.

1.  Are you intending on reverting to the old behaviour with #7514 in the SDK (i.e backup file can be opened as local realm file) and if so will this be in the next or future RealmSwift SDK version ?

2.  We do use this API to make production backups currently - presumably we just need to set the readOnly flag in our current restore scripts in order to be able to open these new backup files.

3.  Should we wait for (1) (i.e will it be soon) or should we just use v10.11.0 in the mean time.  We are currently using v10.17.0 in production but will just use v10.11.0 to sync and create a backup for development purposes.

4.  If there is a desire to keep this functionality (i.e. create the backup file to be compatible with sync) then should we develop a script to copy from the backup file (read only) and to create a local realm file.  It would be easier to have a flag on writeCopy() API to output the required format.

Thanks

**Comment by tgoyne** [comment]
It's the other way around: we switched from writing the copy with no history (which makes it openable as a local Realm but not in sync mode) to writing it with sync history, which made it no longer possible to open it in non-sync mode. The intended purpose of this is to make it possible to bundle a Realm with your app and use that as the starting point for synchronization rather than downloading all of the data on first launch of the app, but that needs to be exposed via a different function rather than changing the behavior of writeCopy().

Barring unexpected delays a release with #7514 should be out today.

**Comment by duncangroenewald** [comment]
@tgoyne - oh ok got the history mixed up then.

FYI - I just reverted to v10.11.0 and synced with the server and then created a backup using writeCopy() but when opening this file as a local realm file I had to perform a migration - i.e. update the schema version because the backup file now includes the '_partitionKey' property - which is not defined in the ReamSwift schema, but as I understand it this is automatically added by the Sync SDK.  

When opening as a local realm file the schema won't have this property present.  

So either writeCopy() needs to be smart enough to exclude writing this property to the backup file or we need to add this property to the RealmSwift object definitions to avoid having to force a migration each time.

Is there any issue with adding this property to the existing RealmSwift object definitions so we can avoid the need to increment the schema version when opening the backup file ?  

We will obviously have to test this but I assume doing so would not result in a clash with what the SDK does - for example will the property defined in the SDK connection parameters override any values stored in the objects themselves e.g. a default value for the _partitionKey property ?

Thanks

**Comment by tgoyne** [comment]
It's valid to add the partition value property to your schema, but that does mean that you'll have to make sure it's set to the correct value when creating objects. I would generally recommend just setting the schema version to zero when opening synchronized Realms (i.e. at the default) and a non-zero when opening local Realms. The schema version isn't actually used for anything useful for synchronized Realms.

**Comment by duncangroenewald** [comment]
@tgoyne - ah yes that is a much better idea.  Thanks.
