### ISSUE TITLE
How to create RLMArray of primtive data type  in swift using  RLMArray(objectClassName: ...)

### ISSUE THREAD

**Issue by tusharmutreja200** [realm/realm-cocoa#7517]
### How frequently does the bug occur?

All the time

### Description

As there is support from creating the RLMArray with primitive data types, but there is no documentation to define the same in swift using realm-objective-c.

eg: we can define the RLMArray using primitive types like **@property RLMArray<NSNumber *><RLMInt> *numbers;**

then how can we define the same using swift.

In docs, they define what we need to do like this  **RLMArray(objectClassName: Dog.className())**, but I am not able to define the same with primitive type.

Any help will be quite appreciated

### Can you reproduce the bug?

Yes, always

### Version

10.18.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

objective-c IOS

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by sarinashish** [comment]
I am also facing the same issue

**Comment by sharmalabhyafareye** [comment]
Facing same issue.

**Comment by jsflax** [comment]
This can be done using the other constructor:
```swift
@objcMembers class Test: RLMObject {
    dynamic var array = RLMArray<NSNumber>(objectType: .int, optional: false)
}

let realm = RLMRealm()
realm.beginWriteTransaction()
let test = Test()
test.array.add(123)
realm.add(test)
try realm.commitWriteTransaction()
}
```

**Comment by tusharmutreja200** [comment]
@jsflax Thanks for the reply, but I am still facing this issue while creating schema, as it shows only one constructor of RLMArray **objectClassName
<img width="643" alt="Screenshot 2021-11-08 at 5 15 05 PM" src="https://user-images.githubusercontent.com/62887002/140736713-c5744fa8-4b66-495c-8eaa-f5e21124be1d.png">
**

**Comment by jsflax** [comment]
What version of Realm are you using?

**Comment by tusharmutreja200** [comment]
I am using realm pod of version **10.18.0**

**Comment by tusharmutreja200** [comment]
@jsflax I found the solution. As I have checked in Pod file RLMArray.h, 
`- (instancetype)initWithObjectClassName:(NSString *)objectClassName;
`
only the above constructor is exposed that's why we are not able to access **initWithObjectType** constructor.

if I add `- (instancetype)initWithObjectType:(RLMPropertyType)type optional:(BOOL)optional;
`
in RLMArray.h, then everything works fine and we are able to create RLMArray with the primitive type.

Please suggest, is this has been done intentionally or this is a bug and in which version this has been released.

**Comment by vikas-singh-fareye** [comment]
+1 @tusharmutreja200

**Comment by pavel-ship-it** [comment]
@tusharmutreja200 
you can `import Realm.Private`

**Comment by tusharmutreja200** [comment]
@pavel-ship-it this import is not working in the Objective-c header file, can you please suggest the specific import syntax for the objective-c file.

Thanks in advance

**Comment by tusharmutreja200** [comment]
@pavel-ship-it @jsflax please help to understand, how to Import the realm Private class in the objective C file.

**Comment by pavel-ship-it** [comment]
Hi @tusharmutreja200 you don't need to import anything else in Objective-С.
To achieve same effect you can do next:
```
@interface PrimitiveArray : RLMObject
@property RLMArray<RLMInt> *intObj;
@end
```
You can find more in the Realm documentation https://docs.mongodb.com/realm/sdk/ios/
Feel free to open another ticket if you need help.
