### ISSUE TITLE
library not found problem using Cocoapods-binary

### ISSUE THREAD

**Issue by danya61** [realm/realm-cocoa#7527]
### How frequently does the bug occur?

All the time

### Description

Hi all!

I've updated realm version from 3.19.0 -> 10.17.0 and tried to build project with a new one. As an output, I got the error:

> ld: library not found for -lrealm-monorepo
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

After a little research, it turned out that the problem only exists when using CocoaPods-binary, so the podfile looks like this: 

> pod 'RealmSwift', '10.17.0', binary: true

However, using version 3.19.0 in the same way, the build was successful. 
Unfortunately, I have no idea how to fix this aside from remove 'binary: true', however i wish it didn't.

Thank you in advance

### Stacktrace & log output

```shell
ld: library not found for -lrealm-monorepo
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Can you reproduce the bug?

Yes, always

### Version

10.17.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Any

### Build environment

Xcode version: 13.0 beta 4
Dependency manager and version: Cocoapods '1.10.1', cocoapods-binary '0.4.4'

**Comment by SyedSaifAli** [comment]
How was this issue solved?

**Comment by dianaafanador3** [comment]
@SyedSaifAli are you having a similar issue?, There should be no problem when using Realm with Cocoapods.
