### ISSUE TITLE
Use of prefix(xxx) results in random crashes later

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7528]
### How frequently does the bug occur?

All the time

### Description

Using the following line to limit batch size deletes for Synced realm

let userChanges = user.changes.filter("tstamp < %@", archiveDate).prefix(500)

....
realm.beginWrite()
realm.delete(userChanges)
do {
  try realm.commitWrite()
} catch {
...
}
...

However this results in random crashes and very slow performance

The problem no longer occurs is the results is converted to an array prior to performing the delete.  Performance is also substantially improved.

let userChanges = Array(user.changes.filter("tstamp < %@", archiveDate).prefix(500))

### Stacktrace & log output

```shell
N/A
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

See code above

### Version

10.19.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 12.0.1

### Build environment

Xcode version: 13 
Dependency manager and version: SPM

**Comment by tgoyne** [comment]
https://docs.mongodb.com/realm-sdks/swift/latest/Structs/Realm.html#/s:10RealmSwift0A0V6deleteyyxSTRzSo13RLMObjectBaseC7ElementRczlF

> Do not pass in a slice to a Results or any other auto-updating Realm collection type (for example, the type returned by the Swift suffix(_:) standard library method). Instead, make a copy of the objects to delete using Array(), and pass that instead. Directly passing in a view into an auto-updating collection may result in ‘index out of bounds’ exceptions being thrown.

Each time you delete an object the Results are recomputed and only include the objects still in the Realm, which invalidates the Slice.

**Comment by duncangroenewald** [comment]
I knew that !! lol !!
