### ISSUE TITLE
'Query' results in ambiguous type lookup error

### ISSUE THREAD

**Issue by LoopingLouieX** [realm/realm-cocoa#7530]
### How frequently does the bug occur?

All the time

### Description

Hi,

after I updated Realm/RealmSwift from 10.17.0 to 10.19.0, xCode is displaying the following error:

> 'Query' is ambiguous for type lookup in this context

```
import RealmSwift
class DataObserver: NSObject {

	private var query: Query!
}
```

According to the release notes there were no changes in 'Query'.
Does anybody face that issue too?
What's the solution?
Thanks!

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

- Integrate Realm/RealmSwift 10.19 via Cocoapods
- Insert the code above

### Version

10.19.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

15.0

### Build environment

Xcode version: 13.1
Dependency manager and version: Cocoa Pods (latest version)

**Comment by tgoyne** [comment]
We first added a type named Query in 10.19.0. If you have another library which also has a type named Query, you'll now need to disambiguate it with the library name.

**Comment by LoopingLouieX** [comment]
Oh, that's the reason!
Thanks!
