### ISSUE TITLE
 Cannot find type 'Query' in scope after pod update

### ISSUE THREAD

**Issue by lowfreq2010** [realm/realm-cocoa#7539]
### How frequently does the bug occur?

All the time

### Description

After pod update I am getting a lot of compile errors with the same description:

/Pods/RealmSwift/RealmSwift/List.swift:123:46: Cannot find type 'Query' in scope

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

just issue pod update and your project won't compile anymore.

### Version

10.15.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS

### Build environment

Xcode version: 13.1
Dependency manager and version: cocoapods 1.11.2

**Comment by pavel-ship-it** [comment]
Hi @lowfreq2010 ,
Did you get this error after update from RealmSwift 10.15.1 or after update to RealmSwift 10.15.1? What is the another version?

**Comment by lowfreq2010** [comment]
seems like problem got fixed itself on pod deintegrate/install
