### ISSUE TITLE
@Persisted lack of support for 1-to-1 object association

### ISSUE THREAD

**Issue by gongzhang** [realm/realm-cocoa#7544]
### Problem

Hello! I used to declare properties to create 1-to-1 object associations between models like this:

```swift
// reference an optional user-defined object
// (this is not embedded object)
@objc dynamic var myObject: MyClass?
```

However, when I switch to using the `@Persisted` wrapper, I find that it no longer seems to support this form. I also don't see anything like `@Persisted var myObject: MyClass?` in the [documentation](https://docs.mongodb.com/realm/sdk/ios/data-types/supported-property-types/).

In addition, when I use `@Persisted var myObject: MyClass?` in my project, it breaks some of my unit-tests. Is this 1-to-1 object association no longer supported indeed? 🤔

### How important is this improvement for you?

I'd like to see it, but have a workaround

**Comment by dianaafanador3** [comment]
Hi @gongzhang, You should be able to declare an object `@Persisted var myObject: MyClass?` in your model, can you tell us the error you are getting on your unit tests? 
And many thanks for letting us know about the missing documentation on this.

**Comment by gongzhang** [comment]
@dianaafanador3 ☺️ Thanks for the reply. I checked and the failed test cases seem to be related to KVO.

When I set an associated object via the `setValuesForKeys(:)` method, the properties defined via `@Persisted` fail, while the previous `@objc dynamic` is fine.

```swift
import XCTest
import RealmSwift
@testable import LearnRealmPersisted

final class LearnRealmPersistedTests: XCTestCase {
    
    func testSetValues() throws {
        let person = Person()
        XCTAssertNil(person.dog)
        
        person.setValuesForKeys(["dog" : ["name" : "Puppy"]])
        XCTAssertNotNil(person.dog) // ❌ only failed when use @Persisted
    }
    
}

class Dog: Object {
    @Persisted(primaryKey: true) var id: UUID
    @Persisted var name: String
}

class Person: Object {
    @Persisted(primaryKey: true) var id: UUID
    @Persisted var name: String
    @Persisted var dog: Dog?
}

/*
class Dog: Object {
    @objc dynamic var id = UUID()
    @objc dynamic var name = ""
    
    override class func primaryKey() -> String? { "id" }
}

class Person: Object {
    @objc dynamic var id = UUID()
    @objc dynamic var name = ""
    @objc dynamic var dog: Dog? = nil
    
    override class func primaryKey() -> String? { "id" }
}
*/

```

In addition I found that there is no problem with the similar constructor `Person(values: ["dog" : ["name" : "Puppy"]])` provided by RealmSwift.

**Comment by dianaafanador3** [comment]
@gongzhang, you need to add the attribute `@objc` to your property to be key-value coding complaint.

**Comment by gongzhang** [comment]
@dianaafanador3 🤯 Wow. `@Persisted @objc var dog: Dog?` works.

**Comment by gongzhang** [comment]
@dianaafanador3 You guys are doing a really good job! 🙏 I have no further questions. You can close this issue or use it to track document updates. 😄
