### ISSUE TITLE
Internal support for modicationDate timestamp?

### ISSUE THREAD

**Issue by gongzhang** [realm/realm-cocoa#7553]
### Problem

I'd like to implement `modificationDate` or `updatedAt` timestamps for models in my app. However, I found it was more tricky than I thought. 

First, I need to manually update the timestamp in all of the write transactions in my code, which will make the code messy. And it's easy to forget.

Second, since objects support associations, once the associated object is deleted, the association is automatically updated. It is less easy to manually update the timestamp when such changes occur.

So, is there a mechanism in Realm that would make it easier for me to implement the `modificationDate` or `updatedAt` timestamps? Thanks.

### How important is this improvement for you?

Would be a major improvement

**Comment by tgoyne** [comment]
No, we don't currently have any built-in support for this. You could technically do something with notifications:


```swift
let token = realm.objects(Class.self)
    .changesetPublisher(keyPaths: Class.objectSchema().properties.map({ $0.name }).filter({ $0 != "updatedAt" && $0 != "createdAt" }))
    .deliver(on: DispatchQueue(label: "updatedAt updater"))
    .sink { change in
        guard case .update(let collection, deletions: _, insertions: let insertions, modifications: let modifications) else { return }
        let now = Date()
        try! collection.realm.write {
            for insertion in insertions {
                collection[insertion].createdAt = now
                collection[insertion].modifiedAt = now
            }
            for modification in modifications {
                collection[modification].modifiedAt = now
            }
        }
    }
```
but this is probably a bad idea that'll just cause you pain.

**Comment by gongzhang** [comment]
Thank you for your reply, @tgoyne 👍. I have no further questions.

**Comment by dianaafanador3** [comment]
Hi @gongzhang closing this as we don't plan to support this for now.
