### ISSUE TITLE
Freezing object resets ignored properties to nil or default values

### ISSUE THREAD

**Issue by UrosZivaljevic** [realm/realm-cocoa#7556]
### How frequently does the bug occur?

All the time

### Description

Expecting the frozen copy of managed object to have same ignored properties values as managed object the copy is made of. 

What currently happens is that `freeze`-ing managed object with ignored properties just resets them to default (or nil)

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Here is the code to reproduce this:

```
class TestObject: Object {
    @Persisted(primaryKey: true) var id: String
    @Persisted var name: String
    var cardNumber: String?
}
```

```
let realm = try! Realm()
let object = TestObject()
object.id = "1"
object.name = "Test"
object.cardNumber = "4343"

try! realm.write {
      realm.add(object, update: .modified)
}

print("stored ignored is \(object.cardNumber)")
let frozenObject = object.freeze()
print("frozen ignored is \(frozenObject.cardNumber)")
```

it prints out:
```
stored ignored is Optional("4343")
frozen ignored is nil
```

Which shows that after freezing, the property is lost even if managed object has the ignored value set.

### Version

10.15.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS

### Build environment

Xcode version: 13.1

**Comment by tgoyne** [comment]
This is working as intended. Realm does not interact with ignored properties in any way, which among other things means that each accessor object has its own copy of those properties. `freeze()` returns a new object which refers to the same data in the Realm, but it doesn't know anything about the values of the ignored properties on the object you called it on.

**Comment by UrosZivaljevic** [comment]
Okay thanks for clarification 👍
