### ISSUE TITLE
Linker fails to find libswift_Concurrency.dylib for RealmSwift in release build

### ISSUE THREAD

**Issue by vyacheslavvorona** [realm/realm-cocoa#7559]
### How frequently does the bug occur?

Sometimes

### Description

We've been using Realm for quite some time in our application and haven't faced this kind of problem until now.
We have deployed a new version of the app to TestFlight. It contains just some minor fixes, nothing suspicious. 
However, the app has suddenly started to crash on launch.

The previous app version was made with the same Xcode version and using the same RealmSwift version.
And it is running perfectly fine on both devices without any problem.

### Stacktrace & log output

```shell
...
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dyld: Using shared cache: 49CD0239-2973-3F3D-833C-7796735EA360 | dependent dylib '@rpath/libswift_Concurrency.dylib' not found for '/private/var/containers/Bundle/Application/9E4092CC-2482-4403-AD39-9F003CEB7A72/AppName.app/Frameworks/RealmSwift.framework/RealmSwift', tried but didn't find: '/private/var/containers/Bundle/Application/9E4092CC-2482-4403-AD39-9F003CEB7A72/AppName.app/Frameworks/libswift_Concurrency.dylib' '/private/var/containers/Bundle/Application/9E4092CC-2482-4403-AD39-9F003CEB7A72/AppName.app/Frameworks/RealmSwift.framework/Frameworks/libswift_Concurrency.dylib' '/usr/lib/swift/libswift_Concurrency.dylib' '@rpath/libswift_Concurrency.dylib' '/usr/local/lib/libswift_Concurrency.dylib' '/usr/lib/libswift_Concurrency.dylib'
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b38e020   x3: 0x00000000000000bf
    x4: 0x000000016b38dc20   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x0000000000000002
   x12: 0x0000000000000039  x13: 0x0000000000000029  x14: 0x0000000000000073  x15: 0x000000000000003f
   x16: 0x0000000000000209  x17: 0x00000001055117b4  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b38dc20  x21: 0x00000000000000bf  x22: 0x000000016b38e020  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016b38e8e8  x26: 0x0000000105538778  x27: 0x0000000105538000
   x28: 0x0000000000000000   fp: 0x000000016b38dbf0   lr: 0x000000010551f6e0
    sp: 0x000000016b38dbb0   pc: 0x0000000105517440 cpsr: 0x00000000
   esr: 0x00000000  Address size fault

Binary images description not available

Error Formulating Crash Report:
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯
...
```

### Can you reproduce the bug?

Yes, sometimes

### Reproduction Steps

It is reproducible on some devices to which I don't have direct access, but I'm in contact with their owners.

Reproduction steps:
- Install the app from TestFlight
- Attempt to run it

### Version

10.19.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14.2; iOS 14.4.2 (both are iPads)

### Build environment

Xcode version: 10.19.0
Dependency manager and version: CocoaPods 1.11.2
The app is built via Bitrise pipeline if that matters.

**Comment by kei-sidorov** [comment]
The same problem here. 
Builds uploaded to TF crashes with the same DYLD error. 
In case I made AdHoc release from **the same** xcarchive all works perfectly.

**Comment by hijamoya** [comment]
Same issue here.

**Comment by vyacheslavvorona** [comment]
Update:
Building the app with Xcode 13.2 RC indeed allowed us to run it on those two iPads. But using an unreleased Xcode version in prod doesn't seem like a proper solution. On well.

Anyway, since the root of the problem is unrelated to RealmSwift I'm closing the thread.

**Comment by DouweBos** [comment]
@vyacheslavvorona You can also disable bitcode to get around this issue. Which itself obviously also has its down sides, just like using a release candidate for prod builds.

**Comment by liamnichols** [comment]
This does lead to an interesting question though since we have also hit this issue with our app that supports iOS 12+. 

We have no intention in using Swift Concurrency features for a while still, but if Apple's strategy is to bundle libswift_Concurrency.dylib with any app that references the concurrency APIs then its going to increase the size of our app bundle for no reason, which is something I'd like to avoid. 

I wonder if libraries like Realm would be able to explore with moving async APIs into a separate opt-in framework 🤔 It's probably a little too early to tell for sure though.

**Comment by tgoyne** [comment]
We could probably find a way to make it optional for spm and cocoapods installations, but we'll want to wait to let things stabilize a bit rather than run off to solve a problem that Apple might resolve on their end soon.
