### ISSUE TITLE
Is it possible to add support to open Realm on an array of partitions?

### ISSUE THREAD

**Issue by anton-plebanovich** [realm/realm-cocoa#7566]
### Problem

Currently, we must open a separate Realm for each partition value. If we try to provide an array of partitions to open we receive an error:
```
Session error: Error Domain=io.realm.sync Code=4 "Illegal Realm path (BIND): expected partition to have type string but found []
```

We want to change the partition value on all our objects and so we need to release a version that will open two Realms on two partitions and then select one that is currently used. Then, release the app that will drop the old one. The main issue is the complexity of managing multiple realms on our side and also it looks like multiple Realms are opened one after another so it also impacts the app launching time.

The other thing is that I think that relations between partitions aren't possible atm but not sure. As I remember I tried to do something like that but failed. We have a public data partition and user data partition and it looks like we can't set up relations from the user data to public data because it's two separate partitions and Realms.

### Solution

It will be much easier to just open one Realm on several partition values. This will simplify the client code drastically.

### How important is this improvement for you?

I'd like to see it, but have a workaround

**Comment by ianpward** [comment]
This is not possible at this time but we are working on an initiative known as realm flexible sync that will give you a similar capability. Stay tuned
https://www.mongodb.com/developer/article/realm-flexible-sync-preview/
