### ISSUE TITLE
.searchable make list swipe not work in SwiftUI

### ISSUE THREAD

**Issue by XHMM** [realm/realm-cocoa#7567]
### How frequently does the bug occur?

All the time

### Description

when use  realm-provided `.searchable` modifier, swipe action on list not work, when I switched to builtin `.searchable`, I can swipe to delete as normal

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1.  paste below to a new xcode ios project: 

```swift

import SwiftUI
import RealmSwift

class TodoModel: Object, ObjectKeyIdentifiable {
    @Persisted var content: String
}

struct ContentView: View {
    @ObservedResults(TodoModel.self) var list
    @State var searchText: String = ""
    init() {
        let realm = try! Realm()
        try! realm.write {
            realm.deleteAll()
            
            let todo1 = TodoModel()
            todo1.content = "todo1"
            
            let todo2 = TodoModel()
            todo2.content = "todo2"
            
            realm.add([todo1, todo2])
        }
    }
    var body: some View {
        NavigationView {
            Form {
                    ForEach(list) {
                        Text($0.content)
                    }.onDelete(perform: $list.remove)
            }
            // [1] this made onDelete swipe not work
            .searchable(text: $searchText, collection: $list, keyPath: \.content)
            
            // [2]  use system builtin modifier is well
            // .searchable(text: $searchText)
            
        }
    }
}
```

2. build and run(I'm using iphone11 ios15,  simulator and physical device both tried)

3. swipe on list, you can see no delete button appear

4. comment `[1]` and uncomment `[2]` above code, build and run
5. swipe on list, you can swpie and delete
3. swipe on list, you can see no delete button appear

### Version

10.20.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS big Sur 11.6

### Build environment

ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

/Applications/Xcode.app/Contents/Developer
Xcode 13.0
Build version 13A233

/opt/homebrew/bin/pod
1.10.2
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)

carthage not found
(not in use here)

/usr/bin/git
git version 2.30.1 (Apple Git-130)

**Comment by dianaafanador3** [comment]
HI @XHMM Thanks for letting us know about this, I'll take a look at it

**Comment by dianaafanador3** [comment]
Hi @XHMM Are you sure this is working for you?, the new searchable SwiftUI modifier is only available from macOS 12.0 and should not be used in lower versions

**Comment by XHMM** [comment]
Thanks for reply.

But my depolyment target is IOS15.0,  so I can use this modifier without build failed, and the result is this modifier not work.

Do you mean that I must build on MacOS12.0 to make it work?

**Comment by dianaafanador3** [comment]
@XHMM Because you mentioned that the Platform you are using is `macOS big Sur 11.6` I was not sure how this was working. If you are testing on iOS 15.0 or greater this should work (I tested in a local project and it worked), Can you upload a sample project to a repository so I can check this?

**Comment by XHMM** [comment]
Here's the [sample repo](https://github.com/XHMM/demo_realm) you can try to reproduce.

**Comment by dianaafanador3** [comment]
Hi @XHMM I'm trying to figure this out, seems to be working if the showed view comes from a previous navigation, this may be an Apple's bug. A workaround for this will be to do something like this

**Comment by dianaafanador3** [comment]
struct ContentView: View {
    @State var navigate: Bool = false

    init() {
        let realm = try! Realm()
        try! realm.write {
            realm.deleteAll()

            let todo1 = TodoModel()
            todo1.content = "todo1"

            let todo2 = TodoModel()
            todo2.content = "todo2"

            let todo3 = TodoModel()
            todo3.content = "todo3"

            let todo4 = TodoModel()
            todo4.content = "todo4"

            let todo5 = TodoModel()
            todo5.content = "todo5"

            realm.add([todo1, todo2, todo3, todo4, todo5])
        }
    }

    var body: some View {
        NavigationView {
            NavigationLink("", isActive: $navigate, destination: {
                TodoView()
            })
        }
        .onAppear {
            navigate = true
        }

    }
}

struct TodoView: View {
    @ObservedResults(TodoModel.self) var list
    @State var searchText: String = ""

    var body: some View {
        Form {
            ForEach(list) {
                Text($0.content)
            }.onDelete(perform: $list.remove)
        }
        // this made onDelete swipe not work
        .searchable(text: $searchText, collection: $list, keyPath: \.content)
        .navigationBarBackButtonHidden(true)

        // use system builtin modifier is well
//         .searchable(text: $searchText)

    }
}

**Comment by XHMM** [comment]
Thanks for reply, I tried it and worked. 

Althought writing like this seems a little weird, nothing better to solve this. 😬

**Comment by dianaafanador3** [comment]
I'll keep looking at the issue, but it looks like something on Apple's side specifically for 'NavigationView', any update I'll add it to this issue
