### ISSUE TITLE
RLM_ARRAY_TYPE has been deprecated. Use RLM_COLLECTION_TYPE instead.

### ISSUE THREAD

**Issue by dwirandytlvk** [realm/realm-cocoa#7924]
### How frequently does the bug occur?
All the time

### Description
Hello,
i would like to ask related to deprecated `RLM_ARRAY_TYPE`, when i upgrade realm version from `3.20` to `10.28.2` i see the warning that said: `RLM_ARRAY_TYPE has been deprecated. Use RLM_COLLECTION_TYPE instead.` in my RLMObject

```
@property RLMArray<DisplayID> *displayIds;
```

Since the documentation https://www.mongodb.com/docs/realm/sdk/swift/model-data/define-model/relationships/#define-a-to-many-relationship-property did not mention RLMArray is the deprecated, what is the alternative to replace `RLMArray`?

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
Build source code that use `RLMArray`

### Version
10.28.2

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
13.0

### Build environment
Xcode version: xcode 13.4.1
Dependency manager and version: Cocoapod v1.11.2

**Comment by leemaguire** [comment]
Hi @dwirandytlvk thanks for reporting this. CC @dacharyc can we update the docs to use `RLM_COLLECTION_TYPE`?

**Comment by leemaguire** [comment]
Hey @dacharyc that is correct.

**Comment by dwirandytlvk** [comment]
how about backward compatibility?
is it safe to use `RLM_COLLECTION_TYPE` macro when i use realm v.3.20? since we are still on progress to migrate realm to 10.28.0
