### ISSUE TITLE
How to figure out whether an once attached `RLMObject` instance is detached recently or not

### ISSUE THREAD

**Issue by dismory** [realm/realm-cocoa#803]
Once
- you fetch an non-empty `RLMArray` instance from an `RLMRealm` instance
- you hold a strong reference to the first `RLMObject` instance in the returned `RLMArray` instance
- then you delete the `RLMObject` instance in the Realm

Now if you try to access any properties of the deleted `RLMObject` instance, you get a `RLMException` exception says that:

> Object has been deleted and is no longer valid.

Yes, this is an expected behavior, however, neither `RLMRealm` or `RLMObject` has provided a way to detect whether an once attached `RLMObject` instance is detached recently or not.(Catch exceptions to do this? You must be kidding...)

Also, it's weird that the detached `RLMObject` instance's `realm` property is not `nil` but the `RLMRealm` instance previously attached, while it's `nil` on newly created standalone `RLMObject` instance.

What's more, a detached object can be added back to the `RLMRealm` instance using `-addObject:` without any error. Even though, after doing that you still get an exception if you access any properties of it.

**Comment by tgoyne** [comment]
The property is named isInvalidated.

**Comment by dipkasyap** [comment]
@tgoyne  Thanks, i was making wrong assumption about realm object. I was trying to find that property on Realm instance , now i knew its for realm object (Modal) :D
