### ISSUE TITLE
addProgressNotification only calls at 100%

### ISSUE THREAD

**Issue by tcollins590** [realm/realm-cocoa#8033]
### How frequently does the bug occur?

All the time

### Description

When using flexible sync, the addProgressNotification callback is only called when the object sync is complete. 

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Open a flexible synced realm and add a progress notification to the syncsession of that realm.

### Version

10.32.2

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 16.1

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by ianpward** [comment]
@captn590 At this time, the subscription API does not work correctly for Flexible Sync, we are looking to fix it this quarter.
