### ISSUE TITLE
Interprocess: Support accessing realms from multiple processes

### ISSUE THREAD

**Issue by ksmandersen** [realm/realm-cocoa#824]
I get a hard crash when I try to begin a transaction on a realm that is located in a shared container. The problem only occurs if both the containing app and the app extensions tries to use the realm. Both "apps" can read from the realm just fine but calling beginWriteTransaction crashes with the output:

```
commit_log.cpp:234: Assertion failed: is_a_known_commit(version)
```

![screen shot 2014-08-20 at 15 05 28](https://cloud.githubusercontent.com/assets/178181/3981125/b1c2b328-286a-11e4-885a-bdb78383ce55.png)
![screen shot 2014-08-20 at 15 17 18](https://cloud.githubusercontent.com/assets/178181/3981284/61b453e4-286c-11e4-8dab-d6a4c09d83fa.png)

Not sure If I'm doing something wrong here.

![screen shot 2014-08-20 at 15 07 05](https://cloud.githubusercontent.com/assets/178181/3981144/ec6b8e1e-286a-11e4-981a-48def62681ce.png)

Unfortunately it is quite cumbersome to replicate a clean project with the same issue since you need to create two App IDs for the App and the extension and set up a App Group too.

**Comment by timanglade** [comment]
We now have support in core for multi-process, including notifications, as long as people use compatible pthread libraries. We need to wrap up the implementation of notifications at the cocoa level, and highlight what we support (iOS 8 extensions, WatchKit, …) + caveats (incompatible pthread libraries) in our docs.

**Comment by RTimal** [comment]
@timanglade Is this support present in v0.90.4? Seeing no query results in my Watchkit extension after committing a write transaction in the parent app.

**Comment by timanglade** [comment]
@RTimal Some things are working yes, but right now there are no change notifications, lots of tests are missing and there’s also an Apple bug we need to address in a more elegant way. We have some builds working internally and we’ll update this ticket as we make progress :)

**Comment by tgoyne** [comment]
This is now fully supported on master and we'll release 0.91.0 with it soon.

**Comment by Fab1n** [comment]
0.91.0? You mean 0.97.0, did you?

**Comment by nwalter08** [comment]
Could someone provide an overview of how I could get Realm to work with an extension. I am making a WatchKit extension.

**Comment by yoshyosh** [comment]
Here you go http://fancypixel.github.io/blog/2015/03/29/share-data-between-watchkit-and-your-app-with-realm/. We are working on a tutorial as well, it should be up soon

**Comment by nwalter08** [comment]
You da real MVP @yoshyosh http://stream1.gifsoup.com/view2/20140902/5101733/you-the-real-mvp-o.gif

**Comment by yoshyosh** [comment]
![drop mic](http://media0.giphy.com/media/149R89yoMrIFgI/giphy.gif)

**Comment by leisim** [comment]
What is the status oft this issue? I think in iOS this is already working...
