### ISSUE TITLE
Printing out object / array

### ISSUE THREAD

**Issue by staticdreams** [realm/realm-cocoa#840]
Using Swift, I remember that in previous versions of (Xcode 6b / Realm.io ?? I'm not sure which one is responsible) I use to be able to do something as simple as ``println(myObject)`` and it would print out the contents of an RLMObject / RLMArray. Now this is gone. Well, it doesn't print out anything. No errors either.

However, doing ``println(object.propertyName)`` would yield a printed line of text in the console. But I want to be able to inspect the whole object..

Has the object printing functionality has been removed or it is just a bug? Or maybe it has been changed and now printing out object/arrays has to be implemented otherwise?

**Comment by Cform** [comment]
I know this is closed, but using NSLog() instead of print() seems to work.

**Comment by timanglade** [comment]
This works in RealmSwift now (available on master but not released yet).
