### ISSUE TITLE
Case Insensitive RLMObject.objectsWhere

### ISSUE THREAD

**Issue by dusave** [realm/realm-cocoa#912]
While using a search display controller and attempting to do a query based on the input text, the query needs to either be case insensitive or use the LIKE keyword like Apple suggests.

**Comment by GokhanArik** [comment]
How about for Android?

**Comment by bmunkholm** [comment]
@GokhanArik : Just saw this by coincident (closed issues are normally not monitored). Case insensitive queries are supported which should be very clear from the API - if not, let us know on the Android github.
Thx

**Comment by GokhanArik** [comment]
@bmunkholm Yes, I found it. I missed that part in docs. Sorry for inconvenience.
