### ISSUE TITLE
Using Realm from RubyMotion throws "framework not found for architecture i386" error

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#981]
More details in https://github.com/realm/realm-cocoa/pull/964 /cc @alloy

**Comment by apinrdw** [comment]
Hi, 
I am trying using Realm+Rubymotion and test to run the example on the repo.
But i got an error `./RubyMotionRealmObject.h:1:9: fatal error: 'Realm/Realm.h' file not found`.
@alloy any suggestion to this problem?

**Comment by apinrdw** [comment]
solved previous problem 
http://community.rubymotion.com/t/integrate-rubymotion-realm-got-an-error/1602/3?u=apinrdw
