### ISSUE TITLE
Group By / Sections / Distinct Values 

### ISSUE THREAD

**Issue by seventyone-ben** [realm/realm-cocoa#982]
Hi,

I want to create a grouped UITableView, so I need somehow a grouping functionality, but I can't figure out how to do that...

Can I fetch distinct values of a row? Then I could fetch the objects for each value in the next step.

Or is there another way for "easy" section grouping?

**Comment by dltlr** [comment]
Has there been any work towards this?

**Comment by jpsim** [comment]
@dltlr have you seen our GroupedTableView example? https://github.com/realm/realm-cocoa/blob/master/examples/ios/objc/GroupedTableView/TableViewController.m

If you're referring to querying for distinct values, we're tracking that in #1103.
