### ISSUE TITLE
How do I set a auto increment key in Realm?

### ISSUE THREAD

**Issue by drinking** [realm/realm-cocoa#987]
Here is my question
http://stackoverflow.com/questions/26252432/how-do-i-set-a-auto-increment-key-in-realm

**Comment by ahmad-atef** [comment]
`//
//  PlayList.swift
//  MP3Quran
//
//  Created by Ahmad Atef on 6/13/16.
//  Copyright © 2016 Smartech-Solutions. All rights reserved.
//

import Foundation
import RealmSwift
import ObjectMapper

class PlayList:Object, Mappable {
    
    dynamic var id = 0
    dynamic var name = ""
    var tracks = List<Track>()
    
    required convenience init?(_ map: Map) {
        self.init()
    }
    
    override static func primaryKey() -> String? {
        return "id"
    }

    func IncrementaID() -> Int{
        let realm = try! Realm()
        let RetNext: NSArray = Array(realm.objects(PlayList).sorted("id"))
        let last = RetNext.lastObject
        if RetNext.count > 0 {
            let valor = last?.valueForKey("id") as? Int
            return valor! + 1
        } else {
            return 1
        }
    }
    
    func mapping(map: Map) {
        id            <- map["id"]
        name          <- map["name"]
        tracks        <- map["tracks"]
    }
}

`
